Rustfoc : stop cloning html render context
rust-lang/rust pull request #100271
Opened 2022-08-08 11:58 UTC by Wardenfar

The issue was about cleaning the shared context in html rendering.
The problem was that the Context was clone for each item rendered.

I change the rendering process to not clone the context so the shared context do not require anymore to be in a std::rc::Rc

Feel free to give me feedback
This PR may impact performance: should we run perf-test ? 

Resolves #82381

2022-08-08 11:58 UTC, rust-highfive commented
r? @CraftSpider

(rust-highfive has picked a reviewer for you, use r? to override)

2022-08-08 12:33 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/7724936601?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/29ef2577989b528c27f76afeea9f389469ce3c1f/checks/7724936601/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
running 55 tests
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
failures:

thread 'main' panicked at 'I/O failure during tests: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/tools/compiletest/src/main.rs:430:13
---- [rustdoc-json] src/test/rustdoc-json/fn_pointer/generics.rs stdout ----
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: rustdoc failed!
status: exit status: 101
status: exit status: 101
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc-json/fn_pointer/generics/auxiliary" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc-json/fn_pointer/generics" "--deny" "warnings" "/checkout/src/test/rustdoc-json/fn_pointer/generics.rs" "--output-format" "json" "-Zunstable-options"
stdout: none
--- stderr -------------------------------
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustdoc/json/mod.rs:311:16
   0:     0x7f642583df9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h60ee82f7913f042c
   1:     0x7f64258a49f8 - core::fmt::write::hea2bca18d4c7e8ed
   2:     0x7f642582e651 - std::io::Write::write_fmt::h8dac55ee3be476d7
   2:     0x7f642582e651 - std::io::Write::write_fmt::h8dac55ee3be476d7
   3:     0x7f6425840f5e - std::panicking::default_hook::{{closure}}::h6b633c4c8fca9f4f
   4:     0x7f6425840c1f - std::panicking::default_hook::h87db6d77693ccfe9
   5:     0x7f64261fa044 - rustc_driver[8bafddba79f7d41c]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:     0x7f6425841712 - std::panicking::rust_panic_with_hook::h685f84a1718c5070
   7:     0x7f64258414f9 - std::panicking::begin_panic_handler::{{closure}}::hb39cb4dcc38b9fc9
   8:     0x7f642583e514 - std::sys_common::backtrace::__rust_end_short_backtrace::h5bbbcc259388a57b
   9:     0x7f6425841202 - rust_begin_unwind
  10:     0x7f64257f0e13 - core::panicking::panic_fmt::hd4d2c8cf7ca7398f
  11:     0x7f64257f0cdd - core::panicking::panic::h6647217039e322be
  12:     0x56545ed068a5 - <rustdoc[5e348fabbf908524]::json::JsonRenderer as rustdoc[5e348fabbf908524]::formats::renderer::FormatRenderer>::after_krate
  13:     0x56545edf5707 - rustdoc[5e348fabbf908524]::formats::renderer::run_format::<rustdoc[5e348fabbf908524]::json::JsonRenderer>
  14:     0x56545ed1c96e - rustdoc[5e348fabbf908524]::run_renderer::<rustdoc[5e348fabbf908524]::json::JsonRenderer>
  15:     0x56545ee2c378 - <rustc_session[90272e15b8c85301]::session::Session>::time::<core[11457ffc0d08deb2]::result::Result<(), rustc_errors[a5a14b99e1b00533]::ErrorGuaranteed>, rustdoc[5e348fabbf908524]::main_options::{closure#0}::{closure#0}::{closure#1}::{closure#2}>
  16:     0x56545edc0672 - <rustc_interface[ed8c02c5e442a77]::passes::QueryContext>::enter::<rustdoc[5e348fabbf908524]::main_options::{closure#0}::{closure#0}::{closure#1}, core[11457ffc0d08deb2]::result::Result<(), rustc_errors[a5a14b99e1b00533]::ErrorGuaranteed>>
  17:     0x56545eca6d53 - <rustc_interface[ed8c02c5e442a77]::interface::Compiler>::enter::<rustdoc[5e348fabbf908524]::main_options::{closure#0}::{closure#0}, core[11457ffc0d08deb2]::result::Result<(), rustc_errors[a5a14b99e1b00533]::ErrorGuaranteed>>
  18:     0x56545ef2da1b - rustc_span[65855187f00bea3d]::with_source_map::<core[11457ffc0d08deb2]::result::Result<(), rustc_errors[a5a14b99e1b00533]::ErrorGuaranteed>, rustc_interface[ed8c02c5e442a77]::interface::create_compiler_and_run<core[11457ffc0d08deb2]::result::Result<(), rustc_errors[a5a14b99e1b00533]::ErrorGuaranteed>, rustdoc[5e348fabbf908524]::main_options::{closure#0}>::{closure#1}>
  19:     0x56545ed1f441 - rustdoc[5e348fabbf908524]::main_options
  20:     0x56545ed2a769 - <scoped_tls[c5b47b3bf6710703]::ScopedKey<rustc_span[65855187f00bea3d]::SessionGlobals>>::set::<rustdoc[5e348fabbf908524]::main_args::{closure#0}, core[11457ffc0d08deb2]::result::Result<(), rustc_errors[a5a14b99e1b00533]::ErrorGuaranteed>>
  21:     0x56545ee3a609 - std[35caa551f2bd943b]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[ed8c02c5e442a77]::util::run_in_thread_pool_with_globals<rustdoc[5e348fabbf908524]::main_args::{closure#0}, core[11457ffc0d08deb2]::result::Result<(), rustc_errors[a5a14b99e1b00533]::ErrorGuaranteed>>::{closure#0}, core[11457ffc0d08deb2]::result::Result<(), rustc_errors[a5a14b99e1b00533]::ErrorGuaranteed>>
  22:     0x56545ef872ee - std[35caa551f2bd943b]::panicking::try::<core[11457ffc0d08deb2]::result::Result<(), rustc_errors[a5a14b99e1b00533]::ErrorGuaranteed>, core[11457ffc0d08deb2]::panic::unwind_safe::AssertUnwindSafe<<std[35caa551f2bd943b]::thread::Builder>::spawn_unchecked_<rustc_interface[ed8c02c5e442a77]::util::run_in_thread_pool_with_globals<rustdoc[5e348fabbf908524]::main_args::{closure#0}, core[11457ffc0d08deb2]::result::Result<(), rustc_errors[a5a14b99e1b00533]::ErrorGuaranteed>>::{closure#0}, core[11457ffc0d08deb2]::result::Result<(), rustc_errors[a5a14b99e1b00533]::ErrorGuaranteed>>::{closure#1}::{closure#0}>>
  23:     0x56545ed939f2 - <<std[35caa551f2bd943b]::thread::Builder>::spawn_unchecked_<rustc_interface[ed8c02c5e442a77]::util::run_in_thread_pool_with_globals<rustdoc[5e348fabbf908524]::main_args::{closure#0}, core[11457ffc0d08deb2]::result::Result<(), rustc_errors[a5a14b99e1b00533]::ErrorGuaranteed>>::{closure#0}, core[11457ffc0d08deb2]::result::Result<(), rustc_errors[a5a14b99e1b00533]::ErrorGuaranteed>>::{closure#1} as core[11457ffc0d08deb2]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  24:     0x7f642584c9e5 - std::sys::unix::thread::Thread::new::thread_start::hd79f73c4cf20808a
  25:     0x7f6425747609 - start_thread
  26:     0x7f642551b133 - clone
  27:                0x0 - <unknown>
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

---
---- [rustdoc-json] src/test/rustdoc-json/generic-associated-types/gats.rs stdout ----

error: rustdoc failed!
status: exit status: 101
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc-json/generic-associated-types/gats/auxiliary" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc-json/generic-associated-types/gats" "--deny" "warnings" "/checkout/src/test/rustdoc-json/generic-associated-types/gats.rs" "--output-format" "json" "-Zunstable-options"
stdout: none
--- stderr -------------------------------
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustdoc/json/mod.rs:311:16
stack backtrace:
   0:     0x7f2d0d768f9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h60ee82f7913f042c
   1:     0x7f2d0d7cf9f8 - core::fmt::write::hea2bca18d4c7e8ed
   2:     0x7f2d0d759651 - std::io::Write::write_fmt::h8dac55ee3be476d7
   3:     0x7f2d0d76bf5e - std::panicking::default_hook::{{closure}}::h6b633c4c8fca9f4f
   4:     0x7f2d0d76bc1f - std::panicking::default_hook::h87db6d77693ccfe9
   5:     0x7f2d0e125044 - rustc_driver[8bafddba79f7d41c]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:     0x7f2d0d76c712 - std::panicking::rust_panic_with_hook::h685f84a1718c5070
   7:     0x7f2d0d76c4f9 - std::panicking::begin_panic_handler::{{closure}}::hb39cb4dcc38b9fc9
   8:     0x7f2d0d769514 - std::sys_common::backtrace::__rust_end_short_backtra [...]

2022-08-08 14:04 UTC, Kobzol commented
@bors try @rust-timer queue

2022-08-08 14:04 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

2022-08-08 15:55 UTC, rust-timer commented
Queued b4cf7bf90d47893ae5c2eb77817f496726eb8678 with parent f03ce30962cf1b2a5158667eabae8bf6e8d1cb03, future [comparison URL](https://perf.rust-lang.org/compare.html?start=f03ce30962cf1b2a5158667eabae8bf6e8d1cb03&end=b4cf7bf90d47893ae5c2eb77817f496726eb8678).

2022-08-08 17:10 UTC, rust-timer commented
Finished benchmarking commit (b4cf7bf90d47893ae5c2eb77817f496726eb8678): [comparison url](https://perf.rust-lang.org/compare.html?start=f03ce30962cf1b2a5158667eabae8bf6e8d1cb03&end=b4cf7bf90d47893ae5c2eb77817f496726eb8678&stat=instructions:u).


### [Instruction count](https://perf.rust-lang.org/compare.html?start=f03ce30962cf1b2a5158667eabae8bf6e8d1cb03&end=b4cf7bf90d47893ae5c2eb77817f496726eb8678&stat=instructions:u)

- Primary benchmarks: 😿 relevant regressions found
- Secondary benchmarks: no relevant changes found

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions 😿 <br /> (primary) | 0.9%     | 1.9% | 3         |
| Regressions 😿 <br /> (secondary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (primary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (secondary) | N/A      | N/A | 0         |
| All 😿🎉 (primary) | 0.9%     | 1.9% | 3         |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=f03ce30962cf1b2a5158667eabae8bf6e8d1cb03&end=b4cf7bf90d47893ae5c2eb77817f496726eb8678&stat=max-rss)
<details>
<summary>Results</summary>


- Primary benchmarks: 🎉 relevant improvement found
- Secondary benchmarks: 🎉 relevant improvements found

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions 😿 <br /> (primary) | N/A      | N/A | 0         |
| Regressions 😿 <br /> (secondary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (primary) | -1.8%    | -1.8% | 1         |
| Improvements 🎉 <br /> (secondary) | -1.8%    | -1.8% | 2         |
| All 😿🎉 (primary) | -1.8%    | -1.8% | 1         |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=f03ce30962cf1b2a5158667eabae8bf6e8d1cb03&end=b4cf7bf90d47893ae5c2eb77817f496726eb8678&stat=cycles:u)
<details>
<summary>Results</summary>


- Primary benchmarks: 😿 relevant regressions found
- Secondary benchmarks: no relevant changes found

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions 😿 <br /> (primary) | 5.5%     | 7.8% | 2         |
| Regressions 😿 <br /> (secondary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (primary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (secondary) | N/A      | N/A | 0         |
| All 😿🎉 (primary) | 5.5%     | 7.8% | 2         |
</details>

[^1]: *the arithmetic mean of the percent change*
[^2]: *number of relevant changes*

If you disagree with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).

Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf +perf-regression

2022-08-09 06:13 UTC, jyn514 commented on src/librustdoc/formats/renderer.rs
> -        // cases. Use an explicit match instead.
You removed this comment. Please add it back.

2022-08-20 10:28 UTC, Wardenfar commented
Do I have to do something ?

2022-08-20 16:17 UTC, jyn514 commented
r? @camelid

2022-08-26 03:01 UTC, camelid commented
Thanks for doing this! I will do my best to look at soon. :)

2022-09-06 05:39 UTC, camelid commented
I was able to look at this today, and overall it looks very good! I will give it a full review within a few days.

2022-09-14 15:28 UTC, camelid requested changes
Sorry for taking so long to review this!

My one concern is that you added several `RefCell`s and `Cell`s to the new `ContextItemFrame` struct and changed `&mut Context` to `&Context` everywhere. I don't see why this is necessary, and we've been trying really hard to move away from interior mutability. Is it possible to directly mutate `ContextItemFrame` through `&mut Context` instead?

If that's not possible, please let me know and we'll figure out how to go forward.

2022-09-15 14:59 UTC, Wardenfar commented
@camelid 
In a lot of places, when removing `RefCell<Shared>` the code no longer compiles with the borrow checker.
In the rendering/printing process, only the `ContextItemFrame` is mutated. To remove completely `RefCell` / `Cell`, you need to remove the `ContextItemFrame` from the `Context` struct (to allow `&Context` and `&mut ContextItemFrame` at the same time)

I tried today but `Context` is everywhere. This is why i choose to keep `RefCell` (but in a smaller part of the struct)

The other way is to rewrite places when the borrow checker fail, but this is a lot of time.

2022-09-17 03:49 UTC, camelid commented
Thanks for your reply!

Why do we need `&Context` and `&mut ContextItemFrame` simultaneously? Can't we have `&mut Context` and use that to get the item frames? I haven't looked at this code in a while, so apologies if I'm missing something.

2022-11-06 01:17 UTC, JohnCSimon commented
@Wardenfar 
Ping from triage: 
Can  you address the comment from the reviewer and fix the merge conflicts?

FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

2022-11-06 11:06 UTC, Wardenfar commented
@JohnCSimon 
Sorry I don't have time to work on it
Should I close the PR ?

2022-11-27 01:18 UTC, JohnCSimon commented
> @JohnCSimon Sorry I don't have time to work on it Should I close the PR ?

I'll close it for you. 
Please reopen when you are ready to continue with this. 
Note: if you do please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

2022-11-27 01:18 UTC, closed without merging