implied bounds: explicitly state which types are assumed to be wf
rust-lang/rust pull request #100676
Opened 2022-08-17 10:32 UTC by lcnr

Adds a new query which maps each definition to the types which that definition assumes to be well formed. The intent is to make it easier to reason about implied bounds.

This change should not influence the user-facing behavior of rustc. Notably, `borrowck` still only assumes that the function signature of associated functions is well formed while `wfcheck` assumes that the both the function signature and the impl signature is well formed. Not sure if that by itself can trigger UB or whether it's just annoying.

As a next step, we can add `WellFormed` predicates to `predicates_of` of these items and can stop adding the wf bounds at each place which uses them. I also intend to move the computation from `assumed_wf_types` to `implied_bounds` into the `param_env` computation. This requires me to take a deeper look at `compare_predicate_entailment` which is currently somewhat weird wrt implied bounds so I am not touching this here.

Would like a crater run for this after niko signed off the approach, as I am not completely confident that I didn't change the behavior of `wfcheck`.

r? @nikomatsakis

2022-08-17 15:57 UTC, nikomatsakis requested changes
r=me with a helper function

2022-08-17 15:57 UTC, nikomatsakis commented on compiler/rustc_typeck/src/check/wfcheck.rs
> +        let assumed_wf_types = tcx.assumed_wf_types(body_def_id);
can we make a helper function for this repeated code?

2022-08-17 15:57 UTC, nikomatsakis commented on compiler/rustc_typeck/src/impl_wf_check/min_specialization.rs
> +        let implied_bounds = implied_bounds;
also here :)

2022-08-17 16:01 UTC, jackh726 commented
👍 I'm generally in favor of cleaning up how we calculate wf and implied bounds. It's a bit of mess and confusing in some places.

2022-08-17 16:15 UTC, lcnr commented
@bors r+ rollup=never

2022-08-17 16:15 UTC, lcnr commented
@bors r=nikomatsakis

2022-08-22 08:32 UTC, merged

2022-08-22 09:57 UTC, rust-timer commented
Finished benchmarking commit (a9bb589cd678e034d194193fa892942315b10e2a): [comparison url](https://perf.rust-lang.org/compare.html?start=d0ea1d767925d53b2230e2ba81197821514781f0&end=a9bb589cd678e034d194193fa892942315b10e2a&stat=instructions:u).


### [Instruction count](https://perf.rust-lang.org/compare.html?start=d0ea1d767925d53b2230e2ba81197821514781f0&end=a9bb589cd678e034d194193fa892942315b10e2a&stat=instructions:u)

- Primary benchmarks: ❌ relevant regressions found
- Secondary benchmarks: ❌ relevant regressions found

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions ❌ <br /> (primary) | 0.3%     | 0.5% | 22        |
| Regressions ❌ <br /> (secondary) | 0.4%     | 0.8% | 22        |
| Improvements ✅ <br /> (primary) | -        | -   | 0         |
| Improvements ✅ <br /> (secondary) | -        | -   | 0         |
| All ❌✅ (primary) | 0.3%     | 0.5% | 22        |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=d0ea1d767925d53b2230e2ba81197821514781f0&end=a9bb589cd678e034d194193fa892942315b10e2a&stat=max-rss)
<details>
<summary>Results</summary>


- Primary benchmarks: ❌ relevant regressions found
- Secondary benchmarks: ✅ relevant improvements found

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions ❌ <br /> (primary) | 2.0%     | 3.3% | 2         |
| Regressions ❌ <br /> (secondary) | -        | -   | 0         |
| Improvements ✅ <br /> (primary) | -        | -   | 0         |
| Improvements ✅ <br /> (secondary) | -2.4%    | -3.5% | 5         |
| All ❌✅ (primary) | 2.0%     | 3.3% | 2         |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=d0ea1d767925d53b2230e2ba81197821514781f0&end=a9bb589cd678e034d194193fa892942315b10e2a&stat=cycles:u)
<details>
<summary>Results</summary>


- Primary benchmarks: ❌ relevant regression found
- Secondary benchmarks: ✅ relevant improvement found

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions ❌ <br /> (primary) | 1.7%     | 1.7% | 1         |
| Regressions ❌ <br /> (secondary) | -        | -   | 0         |
| Improvements ✅ <br /> (primary) | -        | -   | 0         |
| Improvements ✅ <br /> (secondary) | -2.7%    | -2.7% | 1         |
| All ❌✅ (primary) | 1.7%     | 1.7% | 1         |
</details>

[^1]: *the arithmetic mean of the percent change*
[^2]: *number of relevant changes*

If you disagree with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).

**Next Steps**: If you can justify the regressions found in this perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please open an issue or create a new PR that fixes the regressions, add a comment linking to the newly created issue or PR, and then add the `perf-regression-triaged` label to this PR.

@rustbot label: +perf-regression
cc @rust-lang/wg-compiler-performance

2022-08-23 07:28 UTC, lcnr commented
this does actually change user visible behavior. We are now adding implied bounds for unnormalized types during wfcheck. I expect that this is the case of the perf regression. This means that the following now compiles:
```rust
struct Foo<T>(T);

trait GoodBye {
    type Forget;
}
impl<T> GoodBye for T {
    type Forget = ();
}

trait NeedsWf<'a, 'b> {
    type Assoc;
}

impl<'a, 'b> NeedsWf<'a, 'b> for Foo<<&'a &'b () as GoodBye>::Forget> {
    type Assoc = &'a &'b ();
}

fn main() {}
```
When using an impl, we don't actually check wf for these types before normalization, so while this change is desirable, it is currently unsound. I want to avoid reverting this PR and fixing this should be straightforward. Am on vacation right now, going to open an issue for this and intend to fix that once I am back. The fix will be fairly small so 2 weeks until the next beta-cutoff should be enough.

2022-08-24 14:56 UTC, pnkfelix commented
Nominating for discussion at T-compiler meeting tomorrow.

My gut tells me that we should revert this (primarily due to injection of unsoundness; secondarily due to it causing small-but-widespread performance regression).

(If we were to revert it, the intention would be to let lcnr reland a fixed version of it when they are back from vacation.)

That, or someone else should put effort into putting in a fix in the meantime.

----

Note: I do *understand* the argument  that lcnr is making; namely, that the branch of beta from nightly is on September 16 2022 and so lcnr would have a little over a week to land a fix.

I just don't agree with the above argument. We should be very willing to do reverts in reaction to scenarios like this, unless there is *immediate* need for this change from T-types.

@rustbot label: I-compiler-nominated

2022-08-25 09:23 UTC, lcnr commented
opened #100989 which reverts the behavior changes and (probably) the perf regression of this PR.