migrate rustc_query_system to use SessionDiagnostic
rust-lang/rust pull request #100844
Opened 2022-08-21 13:28 UTC by evopen

issues:
* variable list is not supported in fluent
* cannot have two sub diagnostic with the same tag (eg. 2 .note or 2 .help)

2022-08-21 13:28 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @TaKO8Ki (or someone else) soon.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2022-08-22 12:49 UTC, davidtwco requested changes
Looks good, I've left a suggestion for how we might translate the remaining part if you're up for looking into that.

2022-08-22 12:49 UTC, davidtwco commented on compiler/rustc_query_system/src/error.rs
> +            // FIXME: use fluent translation
```suggestion
            // FIXME(#100717): use fluent translation
```

2022-08-22 12:49 UTC, davidtwco commented on compiler/rustc_query_system/src/error.rs
> +            diag.span_note(span, &format!("...which requires {}...", desc));
I wonder if we could add support for `#[subdiagnostic] subs: Vec<SomeSubdiagnosticType>` and represent this that way?

2022-08-24 01:22 UTC, evopen commented on compiler/rustc_query_system/src/error.rs
> +    // #[note(query_system::cycle_recursive_ty_alias)]
cannot have two note attrs here like the IncrementCompilation below

2022-08-24 01:22 UTC, evopen commented
currently Vec<SubDiagType> does not solve the problem of list of variable in fluent.

2022-08-24 06:50 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/7988270160?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/542196e41dca7951a4b21336885f852b5d8c10ec/checks/7988270160/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
---- [ui] src/test/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs stdout ----
diff of stderr:

58    |
59    = help: first argument of the attribute should be the diagnostic slug
60 
- error: diagnostic slug must be first argument of a `#[label(...)]` attribute
-   --> $DIR/subdiagnostic-derive.rs:128:1
-    |
- LL | #[label()]
- 
- 
67 error: `code` is not a valid nested attribute of a `label` attribute
69    |

108    |
108    |
109    = help: first argument of the attribute should be the diagnostic slug
110 
- error: diagnostic slug must be first argument of a `#[label(...)]` attribute
-   --> $DIR/subdiagnostic-derive.rs:217:5
-    |
- LL |     #[label(code = "...")]
- 
- 
- error: subdiagnostic kind not specified
-   --> $DIR/subdiagnostic-derive.rs:234:5
- LL |     B {
-    |     ^
- 
- 
123 error: the `#[primary_span]` attribute can only be applied to fields of type `Span` or `MultiSpan`
125    |

175    | |_^
176 
176 
177 error: specified multiple times
-   --> $DIR/subdiagnostic-derive.rs:314:1
+   --> $DIR/subdiagnostic-derive.rs:318:5
179    |
- LL | #[label(parser::add_paren)]
-    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
+ LL |     #[primary_span]
182    |
183 note: previously specified here
-   --> $DIR/subdiagnostic-derive.rs:311:1
+   --> $DIR/subdiagnostic-derive.rs:318:5
+   --> $DIR/subdiagnostic-derive.rs:318:5
185    |
- LL | #[label(parser::add_paren)]
-    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
+ LL |     #[primary_span]
188 
- error: specified multiple times
-   --> $DIR/subdiagnostic-derive.rs:314:1
-    |
-    |
- LL | #[label(parser::add_paren)]
-    |
- note: previously specified here
-   --> $DIR/subdiagnostic-derive.rs:311:1
-    |
-    |
- LL | #[label(parser::add_paren)]
- 
- 
201 error: `#[label(parser::add_paren)]` is not a valid attribute
203    |


218 LL |     #[primary_span]
220 
220 
- error: subdiagnostic kind not specified
-   --> $DIR/subdiagnostic-derive.rs:342:8
-    |
- LL | struct AG {
- 
227 error: specified multiple times
228   --> $DIR/subdiagnostic-derive.rs:379:47
229    |
229    |

395 LL | #[label(slug)]
396    |         ^^^^ not found in `rustc_errors::fluent`
- error: aborting due to 52 previous errors
+ error: aborting due to 47 previous errors
399 
400 For more information about this error, try `rustc --explain E0425`.
---
To only update this specific test, also pass `--test-args session-diagnostic/subdiagnostic-derive.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/session-diagnostic/subdiagnostic-derive" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/session-diagnostic/subdiagnostic-derive/auxiliary"
stdout: none
--- stderr -------------------------------
error: label without `#[primary_span]` field
   |
   |
LL | / #[label(parser::add_paren)]
LL | | //~^ ERROR label without `#[primary_span]` field
LL | | struct C {
LL | |     var: String,
LL | | }


error: `#[label]` is not a valid attribute
   |
LL | #[label]
   | ^^^^^^^^


error: `#[foo]` is not a valid attribute
   |
LL | #[foo]
   | ^^^^^^


error: `#[label = ...]` is not a valid attribute
   |
   |
LL | #[label = "..."]


error: `#[label(bug = ...)]` is not a valid attribute
   |
   |
LL | #[label(bug = "...")]
   |
   |
   = help: first argument of the attribute should be the diagnostic slug

error: `#[label("...")]` is not a valid attribute
   |
   |
LL | #[label("...")]
   |
   |
   = help: first argument of the attribute should be the diagnostic slug

error: `#[label(slug = ...)]` is not a valid attribute
   |
   |
LL | #[label(slug = 4)]
   |
   |
   = help: first argument of the attribute should be the diagnostic slug

error: `#[label(slug(...))]` is not a valid attribute
   |
   |
LL | #[label(slug("..."))]
   |
   |
   = help: first argument of the attribute should be the diagnostic slug

error: `code` is not a valid nested attribute of a `label` attribute
   |
   |
LL | #[label(parser::add_paren, code = "...")]


error: `applicability` is not a valid nested attribute of a `label` attribute
   |
   |
LL | #[label(parser::add_paren, applicability = "machine-applicable")]

error: unsupported type attribute for subdiagnostic enum
  --> /checkout/src/test/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:155:1
   |
   |
LL | #[foo]
   | ^^^^^^

error: `#[bar]` is not a valid attribute
   |
LL |     #[bar]
   |     ^^^^^^


error: `#[bar = ...]` is not a valid attribute
   |
   |
LL |     #[bar = "..."]


error: `#[bar = ...]` is not a valid attribute
   |
   |
LL |     #[bar = 4]


error: `#[bar("...")]` is not a valid attribute
   |
   |
LL |     #[bar("...")]
   |
   |
   = help: first argument of the attribute should be the diagnostic slug

error: the `#[primary_span]` attribute can only be applied to fields of type `Span` or `MultiSpan`
   |
   |
LL |     #[primary_span]


error: label without `#[primary_span]` field
   |
   |
LL | / #[label(parser::add_paren)]
LL | | //~^ ERROR label without `#[primary_span]` field
LL | | struct W {
LL | |     #[primary_span]
LL | |     //~^ ERROR the `#[primary_span]` attribute can only be applied to fields of type `Span` or `MultiSpan`
LL | |     span: String,
LL | | }


error: `#[applicability]` is only valid on suggestions
   |
LL |     #[applicability]
   |     ^^^^^^^^^^^^^^^^


error: `#[bar]` is not a valid attribute
   |
LL |     #[bar]
   |     ^^^^^^
   |
   |
   = help: only `primary_span`, `applicability` and `skip_arg` are valid field attributes

error: `#[bar = ...]` is not a valid attribute
   |
   |
LL |     #[bar = "..."]


error: `#[bar(...)]` is not a valid attribute
   |
   |
LL |     #[bar("...")]

error: unexpected unsupported untagged union
  --> /checkout/src/test/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:304:1
   |
   |
LL | / union AC {
LL | | //~^ ERROR unexpected unsupported untagged union
LL | |     span: u32,
LL | |     b: u64
LL | | }

error: specified multiple times
  --> /checkout/src/test/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:318:5
   |
   |
LL |     #[primary_span]
   |
note: previously specified here
  --> /checkout/src/test/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:318:5
   |
   |
LL |     #[primary_span]


error: `#[label(parser::add_paren)]` is not a valid attribute
   |
   |
LL | #[label(parser::add_paren, parser::add_paren)]
   |
   |
   = help: a diagnostic slug must be the first argument to the attribute
error: specified multiple times
  --> /checkout/src/test/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:336:5
   |
   |
LL |     #[primary_span]
   |
note: previously specified here
  --> /checkout/src/test/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:333:5
   |
   |
LL |     #[primary_span]

error: specified multiple times
  --> /checkout/src/test/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:379:47
   |
   |
LL | #[suggestion(parser::add_paren, code = "...", code = "...")]
   |
note: previously specified here
  --> /checkout/src/test/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:379:33
   |
   |
L [...]

2022-08-25 01:12 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/8006648624?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/fffe11b295330d8baf3d6b92b649d22dcb06404d/checks/8006648624/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

```

</details>

2022-08-25 14:29 UTC, davidtwco commented on compiler/rustc_macros/src/diagnostics/subdiagnostic.rs
> +    slugs: Vec<(Path, proc_macro::Span)>,
This will conflict with #100970 but they should be otherwise compatible

2022-08-25 14:33 UTC, davidtwco approved these changes

2022-08-25 14:35 UTC, davidtwco commented
@bors r+

2022-08-25 15:10 UTC, jyn514 commented on compiler/rustc_query_system/src/query/job.rs
> +    // let cycle_usage = usage.map(|(span, query)| query.default_span(span))
stray comment

2022-08-25 15:24 UTC, davidtwco commented
@bors r-

to fix the stray comment

2022-08-25 15:35 UTC, jyn514 commented
@bors r=davidtwco

2022-08-27 04:36 UTC, evopen commented
r? @davidtwco

2022-08-27 04:54 UTC, evopen commented
@rustbot ready

2022-08-30 16:23 UTC, davidtwco commented
@bors r+

2022-08-31 12:07 UTC, evopen commented
@rustbot ready
wow, it will never merge

2022-09-01 00:26 UTC, merged

2022-09-01 05:23 UTC, Xiretza commented
This accidentally reverted (at least) #100970, I'll clean that up in a couple hours unless someone else gets to it first.

2022-09-01 05:58 UTC, evopen commented
> This accidentally reverted (at least) #100970, I'll clean that up in a couple hours unless someone else gets to it first.

I apologize for this. I didn't review my changes in the last rebase. Truely sorry.

2022-09-01 08:02 UTC, davidtwco commented
> This accidentally reverted (at least) #100970, I'll clean that up in a couple hours unless someone else gets to it first.

My bad, I should have noticed this in the review.