Reduce right-side DOM size
rust-lang/rust pull request #100956
Opened 2022-08-24 14:35 UTC by GuillaumeGomez

This is another follow-up of https://github.com/rust-lang/rust/pull/100429 but not in code blocks this time.

So the idea is: if there is only one element in the `.rightside` element, there is no need to wrap it, we can just create one node.

On each page, I run this JS: `document.getElementsByTagName('*').length`. Important to note: the bigger the number of elements inside the page, the greater the gain. It also doesn't work very nicely on std docs because there are a lot of version annotations. So with this PR, It allows to get the following results:

| file name | before this PR | with this PR | diff |
|-|-|-|-|
| std/default/trait.Default.html | 2189 | 1331 | 39.2% |
| std/vec/struct.Vec.html | 14073 | 13842 | 1.7% |
| std/fmt/trait.Debug.html | 5313 | 4907 | 7.7% |
| std/ops/trait.Index.html | 642 | 630 | 1.9% |
| gtk4/WidgetExt | 3269 | 3061 | 6.4% |

You can test it [here](https://rustdoc.crud.net/imperio/reduce-rightsize-dom-size/gtk4/prelude/trait.WidgetExt.html).

r? @notriddle

2022-08-24 16:19 UTC, notriddle requested changes

2022-08-24 18:05 UTC, GuillaumeGomez commented on src/test/rustdoc-gui/anchors.goml
> -assert-css: (".srclink", {"color": "rgb(56, 115, 173)"})
Sure!

2022-08-24 18:05 UTC, GuillaumeGomez commented on src/librustdoc/html/render/mod.rs
> +    if let Some(l) = cx.src_href(item) {
I'm ashamed of this one...

2022-08-24 18:05 UTC, GuillaumeGomez commented on src/librustdoc/html/render/mod.rs
> +    extra: &str,
:+1:

2022-08-24 18:25 UTC, GuillaumeGomez commented
Fix the bad double call and extended GUI tests.

2022-08-26 15:47 UTC, merged

2022-08-26 18:44 UTC, Kobzol commented
Doc size wins from the rollup where this PR was merged (probably coming from this PR): https://perf.rust-lang.org/compare.html?start=8a13871b69924b74cfa1d737f2894068b37ea7ea&end=42fa8ac7236f4f78a82aeea543bdd445a59f02e0&stat=size%3Adoc_bytes