add InProgress ErrorKind to io::ErrorKind
rust-lang/rust pull request #101155
Opened 2022-08-29 12:54 UTC by aviramha

2022-08-29 12:54 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @thomcc (or someone else) soon.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2022-08-29 15:40 UTC, thomcc requested changes
Please read the about adding new functionality to the stdlib: https://std-dev-guide.rust-lang.org/feature-lifecycle/summary.html. In particular, this needs an API change proposal, as described here: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

However, this seems redundant with [`ErrorKind::WouldBlock`](https://doc.rust-lang.org/nightly/std/io/enum.ErrorKind.html#variant.WouldBlock), so you'll need to explain how this is different and worth adding.

2022-08-29 15:40 UTC, thomcc commented on library/std/src/io/error.rs
> +    InProgress,
You need an unstable annotation. Something like `#[unstable(feature = "io_error_inprogress", issue = "none")]`

2022-08-29 15:41 UTC, thomcc commented
@rustbot author

2022-08-29 15:59 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/8071193184?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/e48327c8c7999fec567ee4909b36982c3180c128/checks/8071193184/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
Attempting with retry: make prepare
---
skip untracked path cpu-usage.csv during rustfmt invocations
skip untracked path src/doc/book/ during rustfmt invocations
skip untracked path src/doc/rust-by-example/ during rustfmt invocations
skip untracked path src/llvm-project/ during rustfmt invocations
Diff in /checkout/library/std/src/io/error.rs at line 435:
             Unsupported => "unsupported",
             WouldBlock => "operation would block",
             WriteZero => "write zero",
-            InProgress => "in progress"
+            InProgress => "in progress",
     }
 }
 }
Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/library/std/src/io/readbuf.rs" "/checkout/library/std/src/io/tests.rs" "/checkout/library/std/src/io/stdio/tests.rs" "/checkout/library/std/src/io/util.rs" "/checkout/library/std/src/io/impls.rs" "/checkout/library/std/src/io/prelude.rs" "/checkout/library/std/src/io/cursor.rs" "/checkout/library/std/src/io/error.rs"` failed.
If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
```

</details>

2022-08-29 16:02 UTC, aviramha commented
> Please read the about adding new functionality to the stdlib: https://std-dev-guide.rust-lang.org/feature-lifecycle/summary.html. In particular, this needs an API change proposal, as described here: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html
> 
> However, this seems redundant with [`ErrorKind::WouldBlock`](https://doc.rust-lang.org/nightly/std/io/enum.ErrorKind.html#variant.WouldBlock), so you'll need to explain how this is different and worth adding.

Thanks for the review, followed your lead and opened an issue - https://github.com/rust-lang/libs-team/issues/92. Let's discuss there?

2022-09-20 12:25 UTC, aviramha commented
@rustbot label -S-waiting-on-author +S-waiting-on-review

2023-07-25 16:35 UTC, thomcc commented
The updated PR looks fine to me, although I'm unsure if this needs API approval. I've nominated it to sort that out.

2023-08-15 13:23 UTC, m-ou-se commented
Closing this while we figure out what we want here: https://github.com/rust-lang/libs-team/issues/92 :)

2023-08-15 13:23 UTC, closed without merging