Simplify codeblock and their associated tooltip
rust-lang/rust pull request #101613
Opened 2022-09-09 14:23 UTC by GuillaumeGomez

It is based on https://github.com/rust-lang/rust/pull/101600 so it needs to wait for this one to be merged first.

This PR does two things:

 * Remove CSS class duplication by setting CSS classes such as `compile_fail` directly on the `div` wrapping both the codeblock and the tooltip.
 * Simplify DOM: no need to wrap the tooltip into a `<div>`, it can work just as well without it.

You can test it [here](https://rustdoc.crud.net/imperio/codeblock-tooltip/std/string/struct.String.html#deref).

r? @notriddle

2022-09-09 15:03 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/8272170020?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/d07d814304ee741621adc069fb794d0876dde566/checks/8272170020/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

Some tests failed in compiletest suite=rustdoc mode=rustdoc host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
---- [rustdoc] src/test/rustdoc/codeblock-title.rs stdout ----

error: htmldocck failed!
status: exit status: 1
command: "/usr/bin/python3" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/codeblock-title" "/checkout/src/test/rustdoc/codeblock-title.rs"
stdout: none
--- stderr -------------------------------
3: @has check failed
 `XPATH PATTERN` did not match
 // @has foo/fn.bar.html '//*[@class="tooltip compile_fail"]' "ⓘ"
4: @has check failed
 `XPATH PATTERN` did not match
 // @has foo/fn.bar.html '//*[@class="tooltip ignore"]' "ⓘ"
5: @has check failed
 `XPATH PATTERN` did not match
 // @has foo/fn.bar.html '//*[@class="tooltip should_panic"]' "ⓘ"
Encountered 3 errors
------------------------------------------


```

</details>

2022-09-09 15:14 UTC, notriddle requested changes

2022-09-09 15:58 UTC, GuillaumeGomez commented
I'll give it a try locally to see how it looks like but that seems like a really good idea.

2022-09-09 18:15 UTC, GuillaumeGomez commented
Applied your idea and updated the online demo.

2022-09-09 23:12 UTC, notriddle approved these changes

2022-09-10 08:19 UTC, GuillaumeGomez commented
Done!

2022-09-11 01:44 UTC, merged

2022-09-11 04:37 UTC, rust-timer commented
Finished benchmarking commit (781ef3e99582fee003264087b0eea106a8c7518f): [comparison URL](https://perf.rust-lang.org/compare.html?start=2287107588d92889d282e6cd3c1ca5df34cd34a5&end=781ef3e99582fee003264087b0eea106a8c7518f&stat=instructions:u).

### Overall result: ❌ regressions - ACTION NEEDED


**Next Steps**: If you can justify the regressions found in this perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please open an issue or create a new PR that fixes the regressions, add a comment linking to the newly created issue or PR, and then add the `perf-regression-triaged` label to this PR.

@rustbot label: +perf-regression
cc @rust-lang/wg-compiler-performance



### [Instruction count](https://perf.rust-lang.org/compare.html?start=2287107588d92889d282e6cd3c1ca5df34cd34a5&end=781ef3e99582fee003264087b0eea106a8c7518f&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|            | mean[^1] | range | count[^2] |
|:----------:|:--------:|:-----:|:---------:|
| Regressions ❌ <br /> (primary) | 1.3%     | [1.3%, 1.3%] | 1         |
| Regressions ❌ <br /> (secondary) | 3.4%     | [3.1%, 3.9%] | 6         |
| Improvements ✅ <br /> (primary) | -        | -     | 0         |
| Improvements ✅ <br /> (secondary) | -        | -     | 0         |
| All ❌✅ (primary) | 1.3%     | [1.3%, 1.3%] | 1         |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=2287107588d92889d282e6cd3c1ca5df34cd34a5&end=781ef3e99582fee003264087b0eea106a8c7518f&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|            | mean[^1] | range | count[^2] |
|:----------:|:--------:|:-----:|:---------:|
| Regressions ❌ <br /> (primary) | -        | -     | 0         |
| Regressions ❌ <br /> (secondary) | 2.4%     | [1.0%, 3.3%] | 4         |
| Improvements ✅ <br /> (primary) | -4.7%    | [-4.7%, -4.7%] | 1         |
| Improvements ✅ <br /> (secondary) | -        | -     | 0         |
| All ❌✅ (primary) | -4.7%    | [-4.7%, -4.7%] | 1         |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=2287107588d92889d282e6cd3c1ca5df34cd34a5&end=781ef3e99582fee003264087b0eea106a8c7518f&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

[^1]: *the arithmetic mean of the percent change*
[^2]: *number of relevant changes*

2022-09-11 08:53 UTC, GuillaumeGomez commented
Perf results are noise. No perf change should be detected in here.

2022-09-11 09:23 UTC, lqd commented
@rustbot label: +perf-regression-triaged