Remove some unused CSS rules
rust-lang/rust pull request #101898
Opened 2022-09-16 12:45 UTC by GuillaumeGomez

Since we now have list of items for the ones on the page, we don't need the CSS rules anymore in the sidebar (`.sidebar a`). As for the `.content` ones, they are used to show the definition of the items which have their own pages, so any rule for associated item is unused.

cc @jsha
r? @notriddle

2022-09-16 15:42 UTC, notriddle requested changes

2022-09-16 15:47 UTC, GuillaumeGomez commented on src/librustdoc/html/static/css/themes/ayu.css
> -}
Indeed. Only `.externcrate` should have been removed. Updating shortly.

2022-09-16 16:21 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3069099756/jobs/4957350572) [(plain)](https://github.com/rust-lang/rust/commit/785bab8d9b2c723bf7e75718c8b63d520b464021/checks/8396982044/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling rustdoc-themes v0.1.0 (/checkout/src/tools/rustdoc-themes)
    Finished release [optimized] target(s) in 0.44s
rustdoc: [check-theme] Starting tests! (Ignoring all other arguments)
 - Checking "/checkout/src/librustdoc/html/static/css/themes/ayu.css"... FAILED
  Missing ".content span.mod,.content a.mod,.block a.current.mod" rule
Build completed unsuccessfully in 0:26:26
```

</details>

2022-09-17 03:25 UTC, notriddle approved these changes

2022-09-17 08:15 UTC, merged