Add missing checks for `doc(cfg_hide(...))`
rust-lang/rust pull request #102954
Opened 2022-10-12 09:36 UTC by GuillaumeGomez

Part of  #43781.

The `doc(cfg_hide(...))` attribute can only be used at the crate level and takes a list of attributes as argument.

r? @Manishearth

2022-10-12 12:49 UTC, GuillaumeGomez commented
Fixed the conflict.

2022-10-13 21:09 UTC, Manishearth requested changes
before stabilizing we probably _should_ support it on items too, though

2022-10-13 21:09 UTC, Manishearth commented on compiler/rustc_passes/src/check_attr.rs
> +    /// Check that the `#![doc(cfg_hide(...))]` attribute is well formatted. Returns `true` if
issue: please document what the rules for it being well formatted are

2022-10-14 09:33 UTC, GuillaumeGomez commented
I updated the docs. Allowing it on items sounds like a good idea even though I'm not completely sure why you would want to hide a `cfg` specifically on one item and no on all but I'm sure there will be a use case for it. :laughing: Better discuss it first (with the of the `doc_cfg` attributes before making changes.

2022-10-14 15:40 UTC, Manishearth approved these changes

2022-10-14 15:41 UTC, Manishearth commented
@bors r+

@GuillaumeGomez because you're using internal cfgs or something weird for your module. This is quite common.

2022-10-15 13:30 UTC, merged