Loosen `From<&[T]> for Box<[T]>` bound to `T: Clone`
rust-lang/rust pull request #103406
Opened 2022-10-22 16:37 UTC by Jules-Bertholet

Also loosens `From<Cow<'_, [T]>> for Box<[T]>`'s bound.

[Discussion on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/From.3C.26.5BT.5D.3E.20impls.20consistency)

2022-10-22 16:37 UTC, rust-highfive commented
r? @thomcc

(rust-highfive has picked a reviewer for you, use r? to override)

2022-10-22 16:37 UTC, Jules-Bertholet commented
@rustbot label +T-libs-api -T-libs

2022-10-22 18:03 UTC, thomcc commented
Needs FCP.

r? @m-ou-se

2022-12-30 13:07 UTC, m-ou-se commented
@rfcbot merge

2023-01-17 22:53 UTC, dtolnay requested changes
`stack-protector-heuristics-effect` test is failing in CI. Presumably in relation with this `From<&[T]> for Box<[T]>` usage:

https://github.com/rust-lang/rust/blob/b0f2d6f23fbf847ee1c12d55ab7a3f96561bfd94/src/test/assembly/stack-protector/stack-protector-heuristics-effect.rs#L362

https://github.com/rust-lang/rust/blob/b0f2d6f23fbf847ee1c12d55ab7a3f96561bfd94/src/test/assembly/stack-protector/stack-protector-heuristics-effect.rs#L383

2023-04-27 02:55 UTC, jyn514 commented
Hi @Jules-Bertholet, it's been a while - are you still planning to work on this? Do you know how to make progress? Feel free to ask for help here or [on Zulip](https://rust-lang.zulipchat.com/) if you get stuck.

2023-04-27 04:18 UTC, Jules-Bertholet commented
@rustbot ready

2023-04-27 04:22 UTC, jyn514 approved these changes
This looks good to me but it should probably have a T-libs reviewer, especially to double-check the specialization.

2023-04-29 22:08 UTC, dtolnay commented on library/alloc/src/boxed.rs
> +trait BoxFromSlice<T> {
This would be dead code in no_global_oom_handling mode.

```suggestion
#[cfg(not(no_global_oom_handling))]
trait BoxFromSlice<T> {
```

2023-04-29 22:12 UTC, dtolnay approved these changes
Thanks!

2023-04-29 22:12 UTC, dtolnay commented
@bors r+

2023-04-30 16:54 UTC, merged

2023-04-30 18:27 UTC, rust-timer commented
Finished benchmarking commit (831c9298c8e6542e3ab395216e98aec21f60b470): [comparison URL](https://perf.rust-lang.org/compare.html?start=89158e210ce0b9550b42c65ede244087f2e144b5&end=831c9298c8e6542e3ab395216e98aec21f60b470&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=89158e210ce0b9550b42c65ede244087f2e144b5&end=831c9298c8e6542e3ab395216e98aec21f60b470&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=89158e210ce0b9550b42c65ede244087f2e144b5&end=831c9298c8e6542e3ab395216e98aec21f60b470&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.2% | [0.5%, 2.0%] | 2     |
| Regressions ❌ <br /> (secondary)  | 6.1% | [6.1%, 6.1%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 1.2% | [0.5%, 2.0%] | 2     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=89158e210ce0b9550b42c65ede244087f2e144b5&end=831c9298c8e6542e3ab395216e98aec21f60b470&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.