Fix unwated merge of inline doc comments for impl blocks
rust-lang/rust pull request #103523
Opened 2022-10-25 14:31 UTC by GuillaumeGomez

Fixes https://github.com/rust-lang/rust/issues/102909.

We need this merge mechanism for inlined items but it's completely unwanted for impl blocks (at least the doc comments are, not the other attributes) since we want to keep what `cfg()` is put on the `pub use` or other attributes.

r? @notriddle

2022-10-25 15:45 UTC, notriddle requested changes

2022-10-25 16:25 UTC, GuillaumeGomez commented on src/librustdoc/clean/inline.rs
> +    if ret.last().unwrap().doc_value().map(|x| x == "These are the docs for Foo.").unwrap_or(false)
I forgot to remove my debug prints...

2022-10-25 21:25 UTC, GuillaumeGomez commented
Removed the forgotten debug code.

2022-10-28 01:23 UTC, notriddle approved these changes

2022-10-28 12:50 UTC, merged