x86_64 SSE2 fast-path for str.contains(&str) and short needles
rust-lang/rust pull request #103779
Opened 2022-10-30 20:52 UTC by the8472

Based on Wojciech Muła's [SIMD-friendly algorithms for substring searching](http://0x80.pl/articles/simd-strfind.html#sse-avx2)

The two-way algorithm is Big-O efficient but it needs to preprocess the needle
to find a "criticla factorization" of it. This additional work is significant
for short needles. Additionally it mostly advances needle.len() bytes at a time.

The SIMD-based approach used here on the other hand can advance based on its
vector width, which can exceed the needle length. Except for pathological cases,
but due to being limited to small needles the worst case blowup is also small.

benchmarks taken on a Zen2:

```
16CGU, OLD:
test str::bench_contains_short_short                     ... bench:          27 ns/iter (+/- 1)
test str::bench_contains_short_long                      ... bench:         667 ns/iter (+/- 29)
test str::bench_contains_bad_naive                       ... bench:         131 ns/iter (+/- 2)
test str::bench_contains_bad_simd                        ... bench:         130 ns/iter (+/- 2)
test str::bench_contains_equal                           ... bench:         148 ns/iter (+/- 4)

16CGU, NEW:
test str::bench_contains_short_short                     ... bench:           8 ns/iter (+/- 0)
test str::bench_contains_short_long                      ... bench:         135 ns/iter (+/- 4)
test str::bench_contains_bad_naive                       ... bench:         130 ns/iter (+/- 2)
test str::bench_contains_bad_simd                        ... bench:         292 ns/iter (+/- 1)
test str::bench_contains_equal                           ... bench:           3 ns/iter (+/- 0)

1CGU, OLD:
test str::bench_contains_short_short                     ... bench:          30 ns/iter (+/- 0)
test str::bench_contains_short_long                      ... bench:         713 ns/iter (+/- 17)
test str::bench_contains_bad_naive                       ... bench:         131 ns/iter (+/- 3)
test str::bench_contains_bad_simd                        ... bench:         130 ns/iter (+/- 3)
test str::bench_contains_equal                           ... bench:         148 ns/iter (+/- 6)

1CGU, NEW:
test str::bench_contains_short_short                     ... bench:          10 ns/iter (+/- 0)
test str::bench_contains_short_long                      ... bench:         111 ns/iter (+/- 0)
test str::bench_contains_bad_naive                       ... bench:         135 ns/iter (+/- 3)
test str::bench_contains_bad_simd                        ... bench:         274 ns/iter (+/- 2)
test str::bench_contains_equal                           ... bench:           4 ns/iter (+/- 0)
```

2022-10-30 21:20 UTC, the8472 commented
@bors try @rust-timer queue

2022-10-30 21:20 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

2022-10-30 23:29 UTC, rust-timer commented
Queued 00a98801b5deff4884bae13cf558c2f7e3beb9ca with parent f42b6fa7cad0d221b0c5407dca70b085784b1b5e, future [comparison URL](https://perf.rust-lang.org/compare.html?start=f42b6fa7cad0d221b0c5407dca70b085784b1b5e&end=00a98801b5deff4884bae13cf558c2f7e3beb9ca).

2022-10-31 00:48 UTC, rust-timer commented
Finished benchmarking commit (00a98801b5deff4884bae13cf558c2f7e3beb9ca): [comparison URL](https://perf.rust-lang.org/compare.html?start=f42b6fa7cad0d221b0c5407dca70b085784b1b5e&end=00a98801b5deff4884bae13cf558c2f7e3beb9ca&stat=instructions:u).

### Overall result: ✅ improvements - no action needed


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf -perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=f42b6fa7cad0d221b0c5407dca70b085784b1b5e&end=00a98801b5deff4884bae13cf558c2f7e3beb9ca&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -0.8% | [-1.8%, -0.3%] | 9     |
| Improvements ✅ <br /> (secondary) | -2.0% | [-3.9%, -0.3%] | 12    |
| All ❌✅ (primary)                 | -0.8% | [-1.8%, -0.3%] | 9     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=f42b6fa7cad0d221b0c5407dca70b085784b1b5e&end=00a98801b5deff4884bae13cf558c2f7e3beb9ca&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.2% | [0.2%, 0.2%] | 1     |
| Regressions ❌ <br /> (secondary)  | 1.8% | [1.8%, 1.8%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 0.2% | [0.2%, 0.2%] | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=f42b6fa7cad0d221b0c5407dca70b085784b1b5e&end=00a98801b5deff4884bae13cf558c2f7e3beb9ca&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

2022-10-31 03:01 UTC, thomcc commented
Hmm, is this the first libcore function with architecture-specific SIMD intrinsics? At one point I know this was kinda discouraged. I think part of the reason was miri (which we could check with `#[cfg(not(miri))]`) and cranelift (which IDK if we can check) (CC @RalfJung, @bjorn3).

This *could* be ported to `core::simd` fairly easily (it doesn't use anything we're missing or unhappy with), but the heavy use of movemsk means we should make sure it doesn't regress perf on non-x86 (and continue gating on it if it does), since that operation has has codegen issues on many other targets even at the best of times[^1].

On the bright side, this would remove most of the unsafe!

[^1]: The `core::simd` equivalent to `_mm_movemask_epi8` (`mask8x16::any`) has awful scalarized codegen on [some non-x86 targets](https://github.com/llvm/llvm-project/issues/50466), but the fact that this actually uses the resulting bitmask for more than something like a test against 0 (which can be done more efficiently), which means it probably would need more changes to avoid the hot part of the loop getting scalarized.

2022-10-31 04:56 UTC, thomcc commented
I had kind of a hard time following some parts of this (mainly the index arithmetic). To understand that, I wrote out what this the algorithm is doing. I think this has slightly less handwaving than the linked page but it could be personal.
---

The SIMD optimized code is used for part of the algorithm seems to apply for needles between 2..=8 bytes (0b is impossible, 1b uses memchr), if the haystack is sufficiently big (`haystack.len()` must be greater or equal to `needle.len() + 16`). If these are met, we do the following:

1. Take the first (index = 0) and last (index = `needle.len() - 1`) bytes of the needle, and make two vectors by splatting each into a 16-byte vector.

    That is `first_bytes = u8x16::from([needle[0]; 16])` and `last_bytes = u8x16::from([needle[needle.len() - 1]; 16])` (NB. the code uses `first` and `last` rather than the `_bytes` suffix).

    Using the first and last bytes allows some minor optimizations and simplifies some logic, but the indexes get used elsewhere and (IMO) are very important to understanding why this code works.

2. Iterate over the haystack in steps of 16, and load two 16 byte vectors at each step, one at the start of the chunk, and one offset from that by `needle.len() - 1`, stopping before this would go out of bounds (see step 5).

    That is, `chunk_a = u8x16::from_slice(&haystack[i+0..][..16])` and `chunk_b = u8x16::from_slice(&haystack[i+needle.len()-1..][..16])` (NB: the code uses `a` and `b` rather than a `chunk_` prefix), where `i` is the offset to load from (e.g. the iteration count * 16).

    Note: The `+ 0` and `+ needle.len() - 1` the same as the indices inside `needle` where we took the bytes from in step 1.

3. Do packed equality tests for `chunk_a` vs `first_bytes` and `chunk_b` vs `last_bytes` to produce two masks, `eq_first` and `eq_last`. These are `bitand`ed together to and we have a potential match if the result is non-zero.

   The goal of that is to test if there are any indices in the vectors where a match has been hit in the same index of *both* comparisons.

   Because the `chunk_` vectors are offset by an amount equal to the index used to make each `_bytes` vector, a test being true for `simd_eq(chunk_a, first_bytes)` and `simd_eq(chunk_b, last_bytes)` at some index means that at least two bytes of the needle are correct in `haystack` starting at `chunk_offset + {index that matched}`.

4. If we've found a potential match, then go over the indexes that are true in both `eq_first` and `eq_last`, and check for a match at that index using the equivalent of `needle == &haystack[i+that_index..][..needle.len()]`.

    Small note: The code actually avoids comparing the first and last indices of `needle` here, since effectively, that's what we tested in step 3 to get `eq_first` and `eq_last`.

5. Our main loop in step 2 has a conservative end bound, so in order ensure there's no trailing bytes we didn't check perform steps 2-4 but use an offset of `haystack.len() - (needle.len() - 1) - 16` instead of `i`.

    This offset is chosen so that the slice loaded into `chunk_b` is exactly at the end of the haystack, ensuring there's no slop, and that we've tested the whole input.

    This could be done conditionally to avoid testing extra work on certain needle sizes, which might be worth while, but might not (a potentialy-successful match requires iterating over the bits in the `eq_first & eq_last` bitmask, which is perhaps costly enough to warrant doing this conditionally).

---

I think some parts of this are clear in the code, but others aren't. The index arithmetic in particular isn't really (IMO), nor is the relationship between the byte indexs in the search vectors and the offset in the chunks (which is important to understand *why* this works).

The index arithmetic seems to be avoidable with iterators, which would clear a lot of this up (and also possibly might help perf by avoiding bounds checks?).

I suppose `haystack.array_chunks::<16>().zip(haystack[needle.len()-1..].array_chunks::<16>())` is close to what the main iteration wants to be doing (although it does not have), but `haystack.windows(needle.len() + 16).step_by(16)` is closer to what it currently does, so maybe less disruptive.

(Along those lines, I also kind of find use of the term `chunk` a little misleading, since it implies the iteration would be more like `haystack.array_chunks::<16>()`. I don't have a real alternative to suggest tho, and certainly used the term above, so whatever)

---

(I think I'm invested enough to want to take this review at this point...)

r? @thomcc

2022-10-31 05:18 UTC, thomcc requested changes
This is great (and has great numbers), but I'd like to see this get a couple (big-ish) changes. https://github.com/rust-lang/rust/pull/103779#issuecomment-1296542618 has some rationale for these.

1. Use `core::simd` instead of manual `core::arch`. I think this is needed for miri and non-LLVM codegen backends, but even if it is not, getting rid of the the need for safety comments like `// SAFETY: no preconditions other than sse2 being available` on trivial stuff is kinda worth it IMO.

    I'd probably say still keep the `cfg(all(target_arch = "x86_64", target_feature = "sse2"))` for now  -- we probably don't want to start using `core::simd` on every target without careful thought, and I suspect even `aarch64` is likely to have sub-par codegen for this under `core::simd` (even without the LLVM issue, the algorithm would need some tweaks on targets without a `movemsk`-style instruction).

2. I think using iterators would make the index arithmetic and iteration logic a lot more clear. As mentioned, I had to spend a bit of time figuring out what it was doing, and this would have helped some (maybe a lot) of that.

3. I think I'd also like some (inline) comments to explain what it's doing at a high level (no need to explain how simd works ofc, but the actual algorithm is kinda galaxybrain IMO, so *some* notes would be nice).  Feel free to punt on this til after the others, since they might make it so that a link is enough.

Feel free to push back on these if you disagree (for example, iterators are def not the only way to make this clearer)

2022-10-31 05:18 UTC, thomcc commented on library/core/src/str/pattern.rs
> +    result |= test_chunk(haystack.len() + 1 - needle.len() - CHUNK);
nit: I think this reads a lot clearer as `haystack.len() - (needle.len() - 1) - CHUNK`, since `needle.len() - 1` is how we spell it everywhere else.

2022-10-31 05:29 UTC, thomcc commented
CC @BurntSushi (who has talked about this from time to time before)

2022-10-31 07:43 UTC, the8472 commented
> I had kind of a hard time following some parts of this (mainly the index arithmetic).

That's not just you. This went through several rounds of fixing out of bounds and integer overflow errors and lots of debug-printing to get the pieces aligned 😅

2022-10-31 07:45 UTC, the8472 commented on library/core/src/str/pattern.rs
> +    let check_mask = #[cold]
Yes `bench_contains_short_long` time ~doubles without it.

2022-10-31 07:50 UTC, RalfJung commented
> Hmm, is this the first libcore function with architecture-specific SIMD intrinsics? 

Seems like it is. At least Miri doesn't implement the vast majority of them and so far that has not caused errors from stdlib functions, to my knowledge.

2022-10-31 07:50 UTC, marmeladema commented
Not sure if you have seen it, but we already maintain a crate for this algorithm: https://github.com/cloudflare/sliceslice-rs

2022-10-31 08:24 UTC, the8472 commented
Thanks, I wasn't aware. I may steal some tweaks from there. Although the AVX parts wouldn't be useful in core unless we start shipping some x86-64-v3 toolchain.

2022-10-31 08:28 UTC, marmeladema commented
If that makes it easier for rustc, we could split out the sse2 / SSE 4.2 versions out of the avx2 one.
Anyway, if you'd rather use an external crate for this and sliceslice fits your needs, we are open to discuss  changes to make integration easier.

2022-10-31 12:41 UTC, bjorn3 commented
@thomcc cg_clif should implement all intrinsics used in this PR, however they are implemented using scalar emulation. With the exception of _mm_movemask_epi8 all used vendor intrinsics are implemented using simd_* platform intrinsics or even without any simd related intrinsics at all. _mm_movemask_epi8 is implemented using llvm.x86.sse2.pmovmskb.128 which cg_clif implements for supporting the memchr crate used by regex.

2022-10-31 12:43 UTC, bjorn3 commented
> Hmm, is this the first libcore function with architecture-specific SIMD intrinsics? At one point I know this was kinda discouraged.

The main issue is that libcore is almost never recompiled and as such would never benefit from the SIMD at all. However SSE2 is a mandatory feature for x86_64, so using SSE2 SIMD on x86_64 should be fine I think.

2022-10-31 12:55 UTC, BurntSushi commented
`memchr::memmem` also implements a variant of this approach and AIUI `memchr` is already a dependency of `std`: https://github.com/BurntSushi/memchr/blob/8037d11b4357b0f07be2bb66dc2659d9cf28ad32/Cargo.toml#L34-L36 (Although I don't know if that means it can be used as a dependency of `core`.)

In practical terms, I think this is a great addition and will make a lot of common cases faster. So :+1: from me. I do agree with @thomcc though that using `core::simd` might be wiser here, if only as a way of dog-fooding.

One concern I do have here is whether this is a correct optimization or not. My understanding was that even though SSE2 is part of `x86_64`, the _operating system_ might still choose to disable it because SSE2 requires support for the `xmm` registers. What that means is that, in my understanding, to be completely correct, you still have to do a CPUID check in order to use SSE2 on `x86_64`. But... I am not sure about this, and even if it is true, it may be irrelevant for all OS'es that we support? Dunno, but maybe something to look into.

Bigger picture, I'd like to point out that the [`memchr::memmem`](https://docs.rs/memchr/latest/memchr/memmem/index.html) implementation kind of already did all of this substring litigation while maintaining std's time complexity guarantees. Two-Way is its path of last resort. And it uses almost exactly the algorithm implemented in this PR to accelerate the vast majority of substring searches on `x86_64`, even with needles bigger than 8 bytes. It also has special cases for optimizing latency in the presence of small haystacks. The only thing I can think of that would be needed to make it suitable for std is some internal rejiggering to make it so the same searcher can scan both forwards and backwards. (`memchr::memmem` supports reverse searching, but you have to specify that at construction time. And once the searcher is built, you can only use it for reverse searching. Similarly for forward searching. But I did this only because it's simpler, not because there is some fundamental reason why it cannot be done otherwise.)

Now whether it makes sense to depend on an external crate for such a core part of std, I'm not sure about that. We could bring `memchr` into the `regex` repo to make it a bit more official if that helps. Or maybe it makes sense to just take pieces from `memchr` and re-implement them in `core`. But there's a lot there.

In terms of the algorithm choice, `memchr::memmem` does effectively the same thing with one small tweak: it recognizes the choice of `first` and `last` as arbitrary, and instead tries to choose the prefilter bytes based on which bytes are thought to be less common. It's obviously a heuristic, but it works surprisingly well and is IMO better than just always selecting the first and last bytes.

Another algorithm choice would be to use the SIMD routine as a prefilter for Two-Way in the case of longer needles. But that is a more invasive change I think. (It is what `memchr::memmem` does.)

2022-10-31 13:20 UTC, bjorn3 commented
> https://github.com/BurntSushi/memchr/blob/8037d11b4357b0f07be2bb66dc2659d9cf28ad32/Cargo.toml#L34-L36 (Although I don't know if that means it can be used as a dependency of core.)

Nothing can be a dependency of core as everything depends on core. (technically `#![no_core]` exists, but you have to define a lot of lang items to do anything practical with it. Those definitions will conflict with the definitions in core)

> One concern I do have here is whether this is a correct optimization or not. My understanding was that even though SSE2 is part of x86_64, the operating system might still choose to disable it because SSE2 requires support for the xmm registers. What that means is that, in my understanding, to be completely correct, you still have to do a CPUID check in order to use SSE2 on x86_64. But... I am not sure about this, and even if it is true, it may be irrelevant for all OS'es that we support? Dunno, but maybe something to look into.

LLVM already uses SSE2 everywhere (including for passing float function arguments as per the x86_64 sysv abi) without runtime checks as the target specs for almost all x86_64 targets enable SSE2. If an OS disables SSE2 it will have to be disabled in the target spec, at which point the SSE2 fast path in this PR will simply be compiled out.)

2022-10-31 15:06 UTC, thomcc commented
> AIUI memchr is already a dependency of std

Unless I'm missing something subtle, `memchr` isn't a dep of std, at least not anymore (I think it used to be and was removed?). It's not in `cargo tree -p std --target all --all-features`, at least (which should catch all transitive deps AFAIK?). I suspect that you can remove the `rustc-dep-of-std` feature (but you might want to look for when it got removed to be sure).

> Nothing can be a dependency of core as everything depends on core

If we *really* wanted this, we could do for `memchr` by using a submodule/subtree, and pulling in what we want via `#[path]` (basically vendoring the code), like we do for `core::simd`. That'd for sure need a t-libs FCP, and honestly, would probably be pretty painful for everybody involved, but it *might* be viable? For example, if we could replace a large amount existing search code with a higher quality implementation. (Not totally sure how code we currently have for this tho -- my hunch would be it's not likely to replace enough to be worth the pain, but I could be wrong)

Either way, adding a dep to libcore is not the right approach for this patch. It's a small amount of code that uses very common SSE2 intrinsics.

> I do agree with @thomcc though that using core::simd might be wiser here, if only as a way of dog-fooding

My reasons for wanting to use `core::simd` are:

1. To remove all the `SAFETY: we have sse2` noise. I think this makes the important safety comments harder to notice, but obviously the best way to remove it is by making the code safe.

2. I'd like to use it on aarch64 (and maybe power) in the near future, just I don't want to regress the existing performance in the mean-time. (I'd ideally like to find a way to extend the `core::simd` API to be able to contain some (probably higher-level) idiom for this kind of pattern, something that is efficient with or without `movemsk`).

3. Dogfooding, yes. Using `core::simd` internally is a good way to discover it's issues, and this doesn't need any missing, incomplete, or high-churn functionality.

> What that means is that, in my understanding, to be completely correct, you still have to do a CPUID check in order to use SSE2 on x86_64

You can trust `cfg(target_feature)` totally. You're right that users can can compile code with one set of target features, and  then run the binary on a machine (or OS) without those, but there's nothing we can do about that. This is essentially the same as compiling code for the wrong target triple, which is firmly in the camp of "not our problem".

More concretely about the CPUID check -- note that macros like `std::is_x86_feature_detected!` already will [skip](https://github.com/rust-lang/stdarch/blob/676ca68f5b581e7445e9b828754ccc1ad4d39e1a/crates/std_detect/src/detect/macros.rs#L8-L9) runtime detection/CPUID if the corresponding `cfg!(target_feature = "whatever")` is true.

2022-10-31 15:22 UTC, BurntSushi commented
> Either way, adding a dep to libcore is not the right approach for this patch. It's a small amount of code that uses very common SSE2 intrinsics.

I agree. But just wanted to call out the bigger picture here, because the path between the status quo and what's in `memchr::memmem` might just be a sequence of very small patches until you wind up in a very similar place. Basically, I'm suggesting it might be a good idea to (for example) accept this patch but also reflect a bit on the longer term plan for improving substring search internals.

2022-10-31 17:33 UTC, the8472 commented
> even with needles bigger than 8 bytes

Yeah, there's room for improvement. Currently there's no fallback in case of pathological inputs and with small needs it's still mostly well-behaved.

I also only implemented it for `contains` rather than the full pattern/searcher API to keep the change small and because the `Pattern` trait seems kinda poorly designed for string-matching. It doesn't have a way to pre-compute things once (e.g. the needle pre-procesing) like regex libs usually do. It should be `Pattern` -> `CompiledPattern` -> `Searcher` or something like that. But then if we have fallbacks between algorithms then it would be better to do this lazily, which is tricky if the `CompiledPattern` is `Sync`.

> [...] also reflect a bit on the longer term plan for improving substring search internals.

Agreed, started a [zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/SIMD.20string.20search.20in.20core/near/307162258)

2022-10-31 18:17 UTC, RalfJung commented
> _mm_movemask_epi8 is implemented using llvm.x86.sse2.pmovmskb.128 which cg_clif implements for supporting the memchr crate used by regex.

FWIW if it's only very few needed intrinsics that really help, we can also add them to Miri. We already have `llvm.x86.addcarry.64` for that reason.

2022-10-31 18:28 UTC, BurntSushi commented
> It should be `Pattern` -> `CompiledPattern` -> `Searcher` or something like that. But then if we have fallbacks between algorithms then it would be better to do this lazily, which is tricky if the `CompiledPattern` is `Sync`.

We can carry this over into Zulip if you like, but I'll mention two things here:

1. The inability to build a searcher once and reuse it is indeed a bad drawback, and played a big role [in aspects of the `bstr` API design](https://blog.burntsushi.net/bstr/#motivation-based-on-performance). (And indeed, `memchr::memmem` supports building a searcher and reusing it multiple times.)
2. The "build stuff lazily but still maintain `Sync`" is what `regex` does, and it is indeed a huge pain and a source of problems. Would love to talk about this separately because I'd love to have a great answer to this problem.

2022-10-31 23:45 UTC, the8472 commented
```
       │     let a: Block = Block::from_slice(&haystack[i..]);                                                                                                                                                                                                                                                              ▒
       │       mov       %r15,%rdx                                                                                                                                                                                                                                                                                          ▒
       │       mov       %rdi,%rbp                                                                                                                                                                                                                                                                                          ▒
       │     → call      core::core_simd::vector::Simd<T,_>::from_slice                                                                                                                                                                                                                                                     ▒
       │     <core::ops::range::RangeFrom<usize> as core::slice::index::SliceIndex<[T]>>::index:                                                                                                                                                                                                                            ▒
       │     if self.start > slice.len() {                                                                                                                                                                                                                                                                                  ▒
       │       lea       (%r12,%rbx,1),%rdi                                                                                                                                                                                                                                                                                 ▒
       │       dec       %rdi                                                                                                                                                                                                                                                                                               ▒
       │       cmp       %r13,%rdi                                                                                                                                                                                                                                                                                          ▒
  0.45 │     ↓ ja        3b0                                                                                                                                                                                                                                                                                                ▒
       │     core::str::pattern::simd_contains::{{closure}}:                                                                                                                                                                                                                                                                ▒
       │       movaps    0x10(%rsp),%xmm0                                                                                                                                                                                                                                                                                   ▒
  0.45 │       movaps    %xmm0,0x30(%rsp)                                                                                                                                                                                                                                                                                   ▒
  0.83 │       mov       0x58(%rsp),%rax                                                                                                                                                                                                                                                                                    ▒
       │     <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::get_unchecked:                                                                                                                                                                                                                        ▒
       │     ptr::slice_from_raw_parts(slice.as_ptr().add(self.start), self.end - self.start)                                                                                                                                                                                                                               ▒
       │       lea       (%rax,%rbx,1),%rsi                                                                                                                                                                                                                                                                                 ▒
 10.08 │       mov       0x50(%rsp),%rax                                                                                                                                                                                                                                                                                    ▒
       │     core::str::pattern::simd_contains::{{closure}}:                                                                                                                                                                                                                                                                ▒
       │     let b: Block = Block::from_slice(&haystack[(i + needle.len() - 1)..]);                                                                                                                                                                                                                                         ▒
       │       lea       (%rax,%r15,1),%rdx                                                                                                                                                                                                                                                                                 ▒
       │       mov       %rbp,%rdi                                                                                                                                                                                                                                                                                          ▒
       │     → call      core::core_simd::vector::Simd<T,_>::from_slice                                                                                                                                                                                                                                                     ▒
       │       movdqa    0x10(%rsp),%xmm0                                                                                                 
```

https://doc.rust-lang.org/src/core/up/up/portable-simd/crates/core_simd/src/vector.rs.html#181-191

😱😬😱

Sweet jesus, pooh. That's not SIMD.

2022-11-01 21:46 UTC, the8472 commented
> The index arithmetic seems to be avoidable with iterators, which would clear a lot of this up (and also possibly might help perf by avoiding bounds checks?).
> 
> I suppose `haystack.array_chunks::<16>().zip(haystack[needle.len()-1..].array_chunks::<16>())` is close to what the main iteration wants to be doing (although it does not have), but `haystack.windows(needle.len() + 16).step_by(16)` is closer to what it currently does, so maybe less disruptive (also maybe more optimizable? That would be something you'd probably have a better idea about, probably).

I tried, it's bad for performance. zipping over `slice.as_chunks` mostly works for the outer loop (but still costs ~20ns on one of the benchmarks) but then we lack the index for the inner loop. Adding `enumerate` or deriving the offset unsafely via `offset_from` again works but then the bounds checks don't get optimized out in the inner loop. `step_by` would be worse since it currently lacks some specializations.

We need an unaligned load for `a` and `b` and then if mask != 0 we need to load `sub` for the final comparisons. Pleasing the optimizer to eliminate the bounds checks for all of these is difficult. Using unchecked accesse for everything has the lowest overhead of the approaches I have tried.

I'd say "let's count on Miri", but the tests that would exercise this code properly are disabled under Miri 🙁

2022-11-01 22:21 UTC, BurntSushi commented
@the8472 I've had a very similar experience when trying to migrate similarish SIMD code to more convenient higher level abstractions. Kind of a bummer. I've in general found these sorts of routines to be quite volatile in their codegen. It's not uncommon to have to make tweaks to regain perf when the compiler gets updated.

2022-11-01 22:45 UTC, RalfJung commented
> I'd say "let's count on Miri", but the tests that would exercise this code properly are disabled under Miri 

Which tests are that and is there something that could be done to make them run in Miri?

2022-11-01 22:53 UTC, the8472 commented
https://github.com/rust-lang/rust/blob/ab5a2bc7316012ee9b2a4a4f3821673f2677f3d5/library/alloc/tests/str.rs#L1618-L1623

because it calls 

https://github.com/rust-lang/rust/blob/ab5a2bc7316012ee9b2a4a4f3821673f2677f3d5/library/alloc/tests/str.rs#L1593-L1600

which does a quadratic number of `str.contains(str)` calls which in turn do lots of slice accesses.

And this PR makes it cubic.

https://github.com/rust-lang/rust/blob/f23374740b495d91f8a1efa767129fe5f34a521a/library/alloc/tests/str.rs#L1593-L1616

2022-11-03 11:14 UTC, RalfJung commented
Can't we still test it for some cases? Instead of *all* combinations of i, j, k only check some of them?

2022-11-03 18:22 UTC, the8472 commented
The issue is picking the interesting values that would trigger a bug, which can depend what one is doing wrong, e.g. a +1 or -1 in the wrong place. And it also depends on various parameters when which algorithm is used.

I can add a few more cases to the non-brute-force tests, but when I was writing it in an external crate I had some manual tests that looked all good, when I then moved it to std the existing test caught some errors, generalizing it caught another one.

2022-11-03 18:31 UTC, RalfJung commented
It might also be worth testing the exhaustive version on Miri by hand once on a shorter string, and just letting it run for a few hours or so. You can get a 200x speedup or so by using `-Zmiri-disable-stacked-borrows`, which can still help find other kinds of bugs.

2022-11-13 22:14 UTC, the8472 commented
some significant changes were added since the last perf run

@bors try @rust-timer queue

2022-11-13 22:14 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2022-11-13 22:41 UTC, the8472 commented
> It might also be worth testing the exhaustive version on Miri by hand once on a shorter string, and just letting it run for a few hours or so. You can get a 200x speedup or so by using `-Zmiri-disable-stacked-borrows`, which can still help find other kinds of bugs.

👍 with that flag it merely took 30 minutes.

2022-11-14 00:55 UTC, rust-timer commented
Queued 99aa00406e2da7505cab5e1f91dd30730d587c5b with parent e631891f7ad40eac3ef58ec3c2b57ecd81e40615, future [comparison URL](https://perf.rust-lang.org/compare.html?start=e631891f7ad40eac3ef58ec3c2b57ecd81e40615&end=99aa00406e2da7505cab5e1f91dd30730d587c5b).
<!-- rust-timer: temporary -->

2022-11-14 04:07 UTC, rust-timer commented
Finished benchmarking commit (99aa00406e2da7505cab5e1f91dd30730d587c5b): [comparison URL](https://perf.rust-lang.org/compare.html?start=e631891f7ad40eac3ef58ec3c2b57ecd81e40615&end=99aa00406e2da7505cab5e1f91dd30730d587c5b&stat=instructions:u).

### Overall result: ❌ regressions - ACTION NEEDED


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf +perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=e631891f7ad40eac3ef58ec3c2b57ecd81e40615&end=99aa00406e2da7505cab5e1f91dd30730d587c5b&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.4% | [0.3%, 0.6%] | 5     |
| Regressions ❌ <br /> (secondary)  | -    | -            | 0     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 0.4% | [0.3%, 0.6%] | 5     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=e631891f7ad40eac3ef58ec3c2b57ecd81e40615&end=99aa00406e2da7505cab5e1f91dd30730d587c5b&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 4.3%  | [0.2%, 8.4%]   | 2     |
| Regressions ❌ <br /> (secondary)  | 3.4%  | [3.4%, 3.4%]   | 1     |
| Improvements ✅ <br /> (primary)   | -3.2% | [-3.2%, -3.2%] | 1     |
| Improvements ✅ <br /> (secondary) | -3.5% | [-3.5%, -3.5%] | 1     |
| All ❌✅ (primary)                 | 1.8%  | [-3.2%, 8.4%]  | 3     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=e631891f7ad40eac3ef58ec3c2b57ecd81e40615&end=99aa00406e2da7505cab5e1f91dd30730d587c5b&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -4.4% | [-4.4%, -4.4%] | 1     |
| All ❌✅ (primary)                 | -     | -              | 0     |
</details>

2022-11-14 20:37 UTC, the8472 commented
Hrm, this has lost the rustdoc speedups from the previous PR

2022-11-14 22:09 UTC, the8472 commented
@bors try @rust-timer queue

2022-11-14 22:09 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2022-11-14 23:42 UTC, thomcc approved these changes
This is a lot more readable to me now, thanks for the changes and for adding comments. I think it's basically good.

r=me once you're happy with the perf.

2022-11-15 00:50 UTC, rust-timer commented
Queued 6898f9e98ecc21769db8dad737892466a2c786f4 with parent 96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef, future [comparison URL](https://perf.rust-lang.org/compare.html?start=96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef&end=6898f9e98ecc21769db8dad737892466a2c786f4).
<!-- rust-timer: temporary -->

2022-11-15 02:10 UTC, rust-timer commented
Finished benchmarking commit (6898f9e98ecc21769db8dad737892466a2c786f4): [comparison URL](https://perf.rust-lang.org/compare.html?start=96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef&end=6898f9e98ecc21769db8dad737892466a2c786f4&stat=instructions:u).

### Overall result: ❌✅ regressions and improvements - ACTION NEEDED


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf +perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef&end=6898f9e98ecc21769db8dad737892466a2c786f4&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.4%  | [0.3%, 0.5%]   | 4     |
| Regressions ❌ <br /> (secondary)  | 1.0%  | [1.0%, 1.0%]   | 1     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -1.1% | [-1.3%, -0.6%] | 3     |
| All ❌✅ (primary)                 | 0.4%  | [0.3%, 0.5%]   | 4     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef&end=6898f9e98ecc21769db8dad737892466a2c786f4&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 3.2%  | [0.1%, 5.7%]   | 3     |
| Regressions ❌ <br /> (secondary)  | 2.5%  | [2.5%, 2.5%]   | 1     |
| Improvements ✅ <br /> (primary)   | -3.3% | [-3.3%, -3.3%] | 1     |
| Improvements ✅ <br /> (secondary) | -2.5% | [-2.5%, -2.5%] | 1     |
| All ❌✅ (primary)                 | 1.6%  | [-3.3%, 5.7%]  | 4     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=96ddd32c4bfb1d78f0cd03eb068b1710a8cebeef&end=6898f9e98ecc21769db8dad737892466a2c786f4&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | 2.3%  | [2.3%, 2.3%]   | 1     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -4.9% | [-4.9%, -4.9%] | 1     |
| All ❌✅ (primary)                 | -     | -              | 0     |
</details>

2022-11-15 17:31 UTC, the8472 commented
@bors try @rust-timer queue

2022-11-15 19:38 UTC, rust-timer commented
Queued b926bd75207e52f30bfdaec8a2efdaae590de6b0 with parent 6d651a295e0e0c331153288b10b78344a4ede20b, future [comparison URL](https://perf.rust-lang.org/compare.html?start=6d651a295e0e0c331153288b10b78344a4ede20b&end=b926bd75207e52f30bfdaec8a2efdaae590de6b0).
<!-- rust-timer: temporary -->

2022-11-16 17:45 UTC, Manishearth commented
@bors p=1

going to close the tree for non-nevers for a while so they can drain out

2022-11-17 07:42 UTC, merged

2022-11-17 09:32 UTC, rust-timer commented
Finished benchmarking commit (9340e5c1b9dee53fd32a18f7bfb54faabfe00b7b): [comparison URL](https://perf.rust-lang.org/compare.html?start=251831ece9601d64172127b6caae9087358c2386&end=9340e5c1b9dee53fd32a18f7bfb54faabfe00b7b&stat=instructions:u).

### Overall result: ❌✅ regressions and improvements - ACTION NEEDED


**Next Steps**: If you can justify the regressions found in this perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please open an issue or create a new PR that fixes the regressions, add a comment linking to the newly created issue or PR, and then add the `perf-regression-triaged` label to this PR.

@rustbot label: +perf-regression
cc @rust-lang/wg-compiler-performance



### [Instruction count](https://perf.rust-lang.org/compare.html?start=251831ece9601d64172127b6caae9087358c2386&end=9340e5c1b9dee53fd32a18f7bfb54faabfe00b7b&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.4%  | [0.3%, 0.6%]   | 4     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -0.4% | [-0.5%, -0.3%] | 5     |
| Improvements ✅ <br /> (secondary) | -1.0% | [-1.3%, -0.6%] | 4     |
| All ❌✅ (primary)                 | -0.1% | [-0.5%, 0.6%]  | 9     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=251831ece9601d64172127b6caae9087358c2386&end=9340e5c1b9dee53fd32a18f7bfb54faabfe00b7b&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 3.4%  | [0.1%, 6.9%]   | 4     |
| Regressions ❌ <br /> (secondary)  | 2.5%  | [2.5%, 2.5%]   | 1     |
| Improvements ✅ <br /> (primary)   | -2.1% | [-2.1%, -2.1%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | 2.3%  | [-2.1%, 6.9%]  | 5     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=251831ece9601d64172127b6caae9087358c2386&end=9340e5c1b9dee53fd32a18f7bfb54faabfe00b7b&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.8% | [1.6%, 2.1%] | 3     |
| Regressions ❌ <br /> (secondary)  | 1.8% | [1.2%, 2.4%] | 2     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 1.8% | [1.6%, 2.1%] | 3     |
</details>

2022-11-18 02:02 UTC, nnethercote commented
A few wins, a few losses, it roughly balances out.

@rustbot label: +perf-regression-triaged