Replace libstd, libcore, liballoc terminology in docs
rust-lang/rust pull request #103707
Opened 2022-10-29 00:21 UTC by jonathanCogan

Fixes #103551.  I changed line comments containing the outdated terms as well.

It would be great if someone with more experience could weigh in on whether these changes introduce ambiguity as suggested in https://github.com/rust-lang/rust/issues/103551#issuecomment-1291225315.

2022-11-03 22:50 UTC, H4x5 requested changes

2022-11-03 22:50 UTC, H4x5 commented on library/alloc/src/slice.rs
> +///    --> src/alloc/slice.rs:608:6
The correct path here is actually `library/alloc/src/slice.rs`

2022-11-03 22:50 UTC, H4x5 commented on library/core/tests/str.rs
> +// All `str` tests live in alloc/tests
Maybe this should be `library/alloc/tests/str.rs`?

2022-11-03 22:50 UTC, H4x5 commented on library/core/src/lib.rs
>  // separate crate, libcoretest, to avoid bizarre issues.
the "libcoretest" crate lives at `library/core/tests`, maybe mention that here?

2022-11-03 23:01 UTC, H4x5 approved these changes

2022-11-04 19:26 UTC, jonathanCogan commented
@bors r=H4x5

2022-12-30 12:58 UTC, m-ou-se commented
@bors r+

2022-12-30 13:02 UTC, m-ou-se commented
@bors r+

2022-12-30 19:21 UTC, merged