WIP: Avoid `GenFuture` shim when compiling async constructs
rust-lang/rust pull request #104321
Opened 2022-11-12 13:06 UTC by Swatinem

Previously, async constructs would be lowered to "normal" generators, with an additional `from_generator` / `GenFuture` shim in between to convert from `Generator` to `Future`.

The compiler will now special-case these generators internally so that async constructs will *directly* implement `Future` without the need to go through the `from_generator` / `GenFuture` shim.

The primary motivation for this change was hiding this implementation detail in stack traces and debuginfo, but it can in theory also help the optimizer as there is less abstractions to see through.

---

This is still very much WIP, I just hacked together something that can compile & achieve my desired results for a tiny demo program.

Given the demo code from https://swatinem.de/blog/async-codegen/:

```rust
pub async fn a(arg: u32) -> Backtrace {
    let bt = b().await;
    let _arg = arg;
    bt
}

pub async fn b() -> Backtrace {
    Backtrace::force_capture()
}
```

I would get the following with the latest stable compiler (on Windows):

```
   4: async_codegen::b::async_fn$0
             at .\src\lib.rs:10
   5: core::future::from_generator::impl$1::poll<enum2$<async_codegen::b::async_fn_env$0> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\mod.rs:91
   6: async_codegen::a::async_fn$0
             at .\src\lib.rs:4
   7: core::future::from_generator::impl$1::poll<enum2$<async_codegen::a::async_fn_env$0> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\future\mod.rs:91
```

whereas now I get a much cleaner stack trace:

```
   3: async_codegen::b::async_fn$0
             at .\src\lib.rs:10
   4: async_codegen::a::async_fn$0
             at .\src\lib.rs:4
```

2022-11-12 13:21 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3451055077/jobs/5760024048) [(plain)](https://github.com/rust-lang/rust/commit/60c0ad815bf1cc85248936e2a2c256e58435eb0f/checks/9450054677/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
iiii.....................i..................i........................................... 264/13827
........................................................................................ 352/13827
........................................................................................ 440/13827
........................................................................................ 528/13827
.................................................................F..F.F..F.........F..F. 616/13827
.....F..................F...F............................................F...FF..FF..... 704/13827
.................F.......................F..F....F..F................F.F.FF.FF.FF.F..... 792/13827
..F.F.F..F......i............F.......................................................... 880/13827
........................................................................................ 1056/13827
........................................................................................ 1144/13827
........................................................................................ 1232/13827
........................................................................................ 1320/13827
---
........................................................................................ 4136/13827
...................iii.................................................................. 4224/13827
.........................................................................i.............. 4312/13827
........................................................................................ 4400/13827
F...............................................F....................................... 4488/13827
......................F................................................................. 4576/13827
.......................................FF......F........................................ 4664/13827
........................................................................................ 4840/13827
........................................................................................ 4928/13827
..........................................................F............................. 5016/13827
..........................................................F............................. 5016/13827
.....F..F................................F.............................................. 5104/13827
........................................................................................ 5280/13827
........................................................................................ 5368/13827
...i.....................................................................i.............. 5456/13827
........................................................................................ 5544/13827
---
........................................................................................ 10032/13827
........................................................................................ 10120/13827
...................................................ii...............i...iii............. 10208/13827
........................................................................................ 10296/13827
.....................................................................F..........F....... 10384/13827
........................................................................................ 10560/13827
........................................................................................ 10648/13827
........................................................................................ 10736/13827
........................................................................................ 10824/13827
........................................................................................ 10824/13827
........................................................................................ 10912/13827
...........iiiii...i....i.i............................................................. 11000/13827
........................................................................................ 11088/13827
..........i............................................................................. 11176/13827
....................iiiiii.i..iiiiiiiii.i...........................F................... 11264/13827
.F...FF...F..F..FF..F..............................F.................................... 11352/13827
........................................................................................ 11528/13827
........................................................................................ 11616/13827
........................................................................................ 11704/13827
........................................................................................ 11792/13827
---
---- [ui] src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-assoc-fn-anon-lifetimes" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-assoc-fn-anon-lifetimes/auxiliary" "--edition=2018"
stdout: none
--- stderr -------------------------------
error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc(x: &u32, y: B<'_>) {
   |  _______________________________________^
LL | |         async fn nested(x: &u32, y: A<'_, '_>) {}
LL | |     }
   |
   |
   = note: hidden type `[static generator@/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs:12:39: 14:6]` captures lifetime '_#28r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc(x: &u32, y: B<'_>) {
   |  _______________________________________^
LL | |         async fn nested(x: &u32, y: A<'_, '_>) {}
LL | |     }
   |
   |
   = note: hidden type `[static generator@/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs:12:39: 14:6]` captures lifetime '_#29r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |         async fn nested(x: &u32, y: A<'_, '_>) {}
   |
   |
   = note: hidden type `[static generator@/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs:13:48: 13:50]` captures lifetime '_#19r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |         async fn nested(x: &u32, y: A<'_, '_>) {}
   |
   |
   = note: hidden type `[static generator@/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs:13:48: 13:50]` captures lifetime '_#20r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc2(x: &u32, y: A<'_, '_>) {
   |  ____________________________________________^
LL | |         impl A<'_, '_> {
LL | |             async fn nested_assoc(x: &u32, y: B<'_>) { [...]

2022-11-12 16:00 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3451366736/jobs/5760538068) [(plain)](https://github.com/rust-lang/rust/commit/dfabfd8180dbd9dd2410f51de4393dba2fc51249/checks/9450660292/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
iiiii....................i..................i........................................... 264/13827
........................................................................................ 352/13827
........................................................................................ 440/13827
........................................................................................ 528/13827
...................................................................F.FF..F..........F.F. 616/13827
..F......................FF................................................F.FFF..F..... 704/13827
..................F.......................F.F.....FF..................FF.F.FF.F.F.FF.... 792/13827
..FF.F......F...i............F.......................................................... 880/13827
........................................................................................ 1056/13827
........................................................................................ 1144/13827
........................................................................................ 1232/13827
........................................................................................ 1320/13827
---
........................................................................................ 4136/13827
...................iii.................................................................. 4224/13827
.........................................................................i.............. 4312/13827
........................................................................................ 4400/13827
...F...........................................F........................................ 4488/13827
........................F............................................................... 4576/13827
......................................FF..........F..................................... 4664/13827
........................................................................................ 4840/13827
........................................................................................ 4928/13827
.............................................................F.......................... 5016/13827
.............................................................F.......................... 5016/13827
....F.....F...............................F............................................. 5104/13827
........................................................................................ 5280/13827
........................................................................................ 5368/13827
...i.....................................................................i.............. 5456/13827
........................................................................................ 5544/13827
---
........................................................................................ 10032/13827
........................................................................................ 10120/13827
...................................................ii...............i...iii............. 10208/13827
........................................................................................ 10296/13827
..................................................................F...............F..... 10384/13827
........................................................................................ 10560/13827
........................................................................................ 10648/13827
........................................................................................ 10736/13827
........................................................................................ 10824/13827
........................................................................................ 10824/13827
........................................................................................ 10912/13827
...........iiiii...i....i.i............................................................. 11000/13827
........................................................................................ 11088/13827
..........i............................................................................. 11176/13827
.....................iiiiiii..iiiiiiiii.i.........................F..................... 11264/13827
..F...FFF.....F.F.F..F...............................F.................................. 11352/13827
........................................................................................ 11528/13827
........................................................................................ 11616/13827
........................................................................................ 11704/13827
........................................................................................ 11792/13827
---
---- [ui] src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-assoc-fn-anon-lifetimes" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-assoc-fn-anon-lifetimes/auxiliary" "--edition=2018"
stdout: none
--- stderr -------------------------------
error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc(x: &u32, y: B<'_>) {
   |  _______________________________________^
LL | |         async fn nested(x: &u32, y: A<'_, '_>) {}
LL | |     }
   |
   |
   = note: hidden type `[static generator@/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs:12:39: 14:6]` captures lifetime '_#28r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc(x: &u32, y: B<'_>) {
   |  _______________________________________^
LL | |         async fn nested(x: &u32, y: A<'_, '_>) {}
LL | |     }
   |
   |
   = note: hidden type `[static generator@/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs:12:39: 14:6]` captures lifetime '_#29r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |         async fn nested(x: &u32, y: A<'_, '_>) {}
   |
   |
   = note: hidden type `[static generator@/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs:13:48: 13:50]` captures lifetime '_#19r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |         async fn nested(x: &u32, y: A<'_, '_>) {}
   |
   |
   = note: hidden type `[static generator@/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs:13:48: 13:50]` captures lifetime '_#20r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc2(x: &u32, y: A<'_, '_>) {
   |  ____________________________________________^
LL | |         impl A<'_, '_> {
LL | |             async fn nested_assoc(x: &u32, y: B<'_>) { [...]

2022-11-12 17:48 UTC, cjgillot commented on compiler/rustc_mir_transform/src/generator.rs
> +            }
It would be more readable if this block went back into `make_state`, eventually taking an `&mut Vec<Statement>`.

2022-11-12 17:48 UTC, cjgillot commented on compiler/rustc_trait_selection/src/traits/project.rs
> +        let fut_def_id = tcx.require_lang_item(LangItem::Future, None);
Could you make a dedicated `confirm_async_future_candidate` for this?

2022-11-12 17:48 UTC, cjgillot commented on compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs
> +        if tcx.lang_items().future_trait() == Some(obligation.predicate.def_id()) {
Could you make a dedicated `assemble_future_candidates`?

2022-11-12 17:48 UTC, cjgillot commented on compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs
> +                candidates.vec.push(GeneratorCandidate { is_async: false });
Could you make a dedicated variant for this?

2022-11-12 17:48 UTC, cjgillot commented on compiler/rustc_trait_selection/src/traits/select/confirmation.rs
>      fn confirm_generator_candidate(
Could you make a dedicated method for this?

2022-11-12 17:48 UTC, cjgillot commented on compiler/rustc_trait_selection/src/traits/select/confirmation.rs
> +            self.generator_trait_ref_unnormalized(obligation, substs)
`generator_trait_ref_unnormalized` is quite small, it could probably be inlined here.

2022-11-12 17:48 UTC, cjgillot commented on compiler/rustc_trait_selection/src/traits/select/confirmation.rs
> +        Ok(ImplSourceGeneratorData { generator_def_id, substs, nested, is_async })
This may need a dedicated variant too.

2022-11-12 22:29 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3452540326/jobs/5762518020) [(plain)](https://github.com/rust-lang/rust/commit/de8a305113ca2a2214b833dec13c07428be81680/checks/9453045251/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
iiiii.....................i..................i.......................................... 264/13831
........................................................................................ 352/13831
........................................................................................ 440/13831
........................................................................................ 528/13831
....................................................................FF...FF..........F.F 616/13831
.F........................FF...........................................F......F.FF..F... 704/13831
...............F............................FF...F....F...............FF.F.FF...FFFF.... 792/13831
...FFFF...........i............F........................................................ 880/13831
........................................................................................ 1056/13831
........................................................................................ 1144/13831
........................................................................................ 1232/13831
........................................................................................ 1320/13831
---
........................................................................................ 4136/13831
....................iii................................................................. 4224/13831
..........................................................................i............. 4312/13831
........................................................................................ 4400/13831
..F.............................................F....................................... 4488/13831
....................F................................................................... 4576/13831
......................................F..F......F....................................... 4664/13831
........................................................................................ 4840/13831
........................................................................................ 4928/13831
............................................................F........................... 5016/13831
............................................................F........................... 5016/13831
.....F....F...............................F............................................. 5104/13831
........................................................................................ 5280/13831
........................................................................................ 5368/13831
....i......................................................................i............ 5456/13831
........................................................................................ 5544/13831
---
........................................................................................ 10032/13831
........................................................................................ 10120/13831
....................................................ii...............i...iii............ 10208/13831
........................................................................................ 10296/13831
.....................................................................F..............F... 10384/13831
........................................................................................ 10560/13831
........................................................................................ 10648/13831
........................................................................................ 10736/13831
........................................................................................ 10824/13831
........................................................................................ 10824/13831
........................................................................................ 10912/13831
............iiiii...i....i.i............................................................ 11000/13831
........................................................................................ 11088/13831
...........i............................................................................ 11176/13831
.....................iiiii.ii..i.iiiii.iiiiii..........................F................ 11264/13831
.....FF......FF.FF....FF.............................F.................................. 11352/13831
........................................................................................ 11528/13831
........................................................................................ 11616/13831
........................................................................................ 11704/13831
........................................................................................ 11792/13831
---
---- [ui] src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-assoc-fn-anon-lifetimes" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-assoc-fn-anon-lifetimes/auxiliary" "--edition=2018"
stdout: none
--- stderr -------------------------------
error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc(x: &u32, y: B<'_>) {
   |  _______________________________________^
LL | |         async fn nested(x: &u32, y: A<'_, '_>) {}
LL | |     }
   |
   |
   = note: hidden type `[static generator@/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs:12:39: 14:6]` captures lifetime '_#28r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc(x: &u32, y: B<'_>) {
   |  _______________________________________^
LL | |         async fn nested(x: &u32, y: A<'_, '_>) {}
LL | |     }
   |
   |
   = note: hidden type `[static generator@/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs:12:39: 14:6]` captures lifetime '_#29r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |         async fn nested(x: &u32, y: A<'_, '_>) {}
   |
   |
   = note: hidden type `[static generator@/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs:13:48: 13:50]` captures lifetime '_#19r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |         async fn nested(x: &u32, y: A<'_, '_>) {}
   |
   |
   = note: hidden type `[static generator@/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs:13:48: 13:50]` captures lifetime '_#20r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc2(x: &u32, y: A<'_, '_>) {
   |  ____________________________________________^
LL | |         impl A<'_, '_> {
LL | |             async fn nested_assoc(x: &u32, y: B<'_>) { [...]

2022-11-13 11:36 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3455041157/jobs/5766770751) [(plain)](https://github.com/rust-lang/rust/commit/8de93413cbf29dd23e2f3b1d19959bf4e09c6765/checks/9458058003/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
iiiii.....................i..................i.......................................... 264/13831
........................................................................................ 352/13831
........................................................................................ 440/13831
........................................................................................ 528/13831
......................................................................F.F.............FF 616/13831
.F.........................F..................................................FFF..F.... 704/13831
..........................................F.F......F..................F.F..FFFF..F.F.... 792/13831
.....F....F......i........F............................................................. 880/13831
........................................................................................ 1056/13831
........................................................................................ 1144/13831
........................................................................................ 1232/13831
........................................................................................ 1320/13831
---
........................................................................................ 10032/13831
........................................................................................ 10120/13831
....................................................ii...............i...iii............ 10208/13831
........................................................................................ 10296/13831
.................................................................F...............F...... 10384/13831
........................................................................................ 10560/13831
........................................................................................ 10648/13831
........................................................................................ 10736/13831
........................................................................................ 10824/13831
........................................................................................ 10824/13831
........................................................................................ 10912/13831
............iiiii...i.....ii............................................................ 11000/13831
........................................................................................ 11088/13831
...........i............................................................................ 11176/13831
.....................iiiiii.i..iiiiiiiiiii.i.........................F.................. 11264/13831
.....F..F...F...FFFF.....F...........................F.................................. 11352/13831
........................................................................................ 11528/13831
........................................................................................ 11616/13831
........................................................................................ 11704/13831
........................................................................................ 11792/13831
---
---- [ui] src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-assoc-fn-anon-lifetimes" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-assoc-fn-anon-lifetimes/auxiliary" "--edition=2018"
stdout: none
--- stderr -------------------------------
error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc(x: &u32, y: B<'_>) {
   |  _______________________________________^
LL | |         async fn nested(x: &u32, y: A<'_, '_>) {}
LL | |     }
   |
   |
   = note: hidden type `impl Future<Output = ()>` captures lifetime '_#28r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc(x: &u32, y: B<'_>) {
   |  _______________________________________^
LL | |         async fn nested(x: &u32, y: A<'_, '_>) {}
LL | |     }
   |
   |
   = note: hidden type `impl Future<Output = ()>` captures lifetime '_#29r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |         async fn nested(x: &u32, y: A<'_, '_>) {}
   |
   |
   = note: hidden type `impl Future<Output = ()>` captures lifetime '_#19r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |         async fn nested(x: &u32, y: A<'_, '_>) {}
   |
   |
   = note: hidden type `impl Future<Output = ()>` captures lifetime '_#20r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc2(x: &u32, y: A<'_, '_>) {
   |  ____________________________________________^
LL | |         impl A<'_, '_> {
LL | |             async fn nested_assoc(x: &u32, y: B<'_>) {}
LL | |         }
LL | |     }
   |
   |
   = note: hidden type `impl Future<Output = ()>` captures lifetime '_#33r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc2(x: &u32, y: A<'_, '_>) {
   |  ____________________________________________^
LL | |         impl A<'_, '_> {
LL | |             async fn nested_assoc(x: &u32, y: B<'_>) {}
LL | |         }
LL | |     }
   |
   |
   = note: hidden type `impl Future<Output = ()>` captures lifetime '_#34r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |             async fn nested_assoc(x: &u32, y: B<'_>) {}
   |
   |
   = note: hidden type `impl Future<Output = ()>` captures lifetime '_#28r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |             async fn nested_assoc(x: &u32, y: B<'_>) {}
   |
   |
   = note: hidden type `impl Future<Output = ()>` captures lifetime '_#29r
error: aborting due to 8 previous errors

For more information about this error, try `rustc --explain E0700`.
------------------------------------------
---

40 LL | |     panic!()
41 LL | | }
42    | |_^
-    = note: required because it captures the following types: `ResumeTy`, `Option<bool>`, `impl Future<Output = !>`, `()`
+ note: required because it appears within the type `impl Future<Output = !>`
+    |
+    |
+ LL | async fn bar2<T>(_: T) -> ! {
+    |                           ^
+    = note: required because it captures the following types: `&mut Context<'_>`, `Option<bool>`, `impl Future<Output = !>`, `()`
44 note: required because it's used within this `async fn` body
46    |

51 LL | |     };
52 LL | | }
52 LL | | }
53    | |_^
+ note: required because it appears within the type `impl Future<Output = ( [...]

2022-11-13 11:37 UTC, Swatinem commented
@cjgillot thanks for the review.

I implemented the feedback, defining separate structures / functions for the future case in trait selection.

I also fixed a couple of tests and blessed some test assertions that are clear improvements:
- better spans for async blocks, (now covers the whole `async {}` instead of just the `{}` part)
- tests that assumed `from_generator` wrapping (including moves)
- removed a couple of `error[E0391]: cycle detected when computing type of …` errors, though I’m not entirely confident about that one.

Maybe I missed a couple of things though.

---

The main regression that now remains is, and that you pointed out on zulip:

```
error[E0700]: hidden type for `impl Future<Output = _>` captures lifetime that does not appear in bounds
```

This may be related to another change in diagnostics:

```
-	   = note: required because it captures the following types: `ResumeTy`, `(NotSend,)`, `impl Future<Output = ()>`, `()`
+	   = note: required because it captures the following types: `&mut Context<'_>`, `(NotSend,)`, `impl Future<Output = ()>`, `()`
```

As this now avoids the whole `ResumeTy` in favor of using the `Context` directly, that might be a reason for both these changes.

`ResumeTy` as it exists today in the shim I believe has the purpose to hide all these lifetimes behind some raw pointers and `unsafe` code to then conjure up the lifetimes again out of thin air in `get_context`:

https://github.com/rust-lang/rust/blob/084ad5962275c05e0e1962606cf0501cca4757ae/library/core/src/future/mod.rs#L106

As I was asking on zulip: Do we need this at all, or can we just avoid checking the resume type at all? I’m also wondering why the generator is "capturing" that type at all? It shouldn’t be?

---

As a separate question: Should I remove the whole `from_generator` glue code from the std library right away, or rather wait one cycle in case some external code might rely on that directly?

2022-11-13 16:07 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3455850386/jobs/5768160996) [(plain)](https://github.com/rust-lang/rust/commit/69930d3490ff0b4a43030cdfa0828beaaf02549a/checks/9459688872/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
iiiii.....................i..................i.......................................... 264/13831
........................................................................................ 352/13831
........................................................................................ 440/13831
........................................................................................ 528/13831
...................................................................F.....F............FF 616/13831
F............................F................................................FFF...F... 704/13831
...........................................F..F...F..................F....FFFF...F.FF... 792/13831
.....F..F........i............F......................................................... 880/13831
........................................................................................ 1056/13831
........................................................................................ 1144/13831
........................................................................................ 1232/13831
........................................................................................ 1320/13831
---
........................................................................................ 10032/13831
........................................................................................ 10120/13831
...............................................ii...............i...iii................. 10208/13831
........................................................................................ 10296/13831
................................................................F.............F......... 10384/13831
........................................................................................ 10560/13831
........................................................................................ 10648/13831
........................................................................................ 10736/13831
........................................................................................ 10824/13831
........................................................................................ 10824/13831
........................................................................................ 10912/13831
..........iiiii...i....i.i.............................................................. 11000/13831
........................................................................................ 11088/13831
.........i.............................................................................. 11176/13831
....................iiiiiii..iiiiiiiiiii.i...........................F.................. 11264/13831
.F.F.....F.F..F..F.FF...............................F................................... 11352/13831
........................................................................................ 11528/13831
........................................................................................ 11616/13831
........................................................................................ 11704/13831
........................................................................................ 11792/13831
---
---- [ui] src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/async-await/async-assoc-fn-anon-lifetimes.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-assoc-fn-anon-lifetimes" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-assoc-fn-anon-lifetimes/auxiliary" "--edition=2018"
stdout: none
--- stderr -------------------------------
error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc(x: &u32, y: B<'_>) {
   |  _______________________________________^
LL | |         async fn nested(x: &u32, y: A<'_, '_>) {}
LL | |     }
   |
   |
   = note: hidden type `impl Future<Output = ()>` captures lifetime '_#28r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc(x: &u32, y: B<'_>) {
   |  _______________________________________^
LL | |         async fn nested(x: &u32, y: A<'_, '_>) {}
LL | |     }
   |
   |
   = note: hidden type `impl Future<Output = ()>` captures lifetime '_#29r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |         async fn nested(x: &u32, y: A<'_, '_>) {}
   |
   |
   = note: hidden type `impl Future<Output = ()>` captures lifetime '_#19r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |         async fn nested(x: &u32, y: A<'_, '_>) {}
   |
   |
   = note: hidden type `impl Future<Output = ()>` captures lifetime '_#20r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc2(x: &u32, y: A<'_, '_>) {
   |  ____________________________________________^
LL | |         impl A<'_, '_> {
LL | |             async fn nested_assoc(x: &u32, y: B<'_>) {}
LL | |         }
LL | |     }
   |
   |
   = note: hidden type `impl Future<Output = ()>` captures lifetime '_#33r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |       async fn assoc2(x: &u32, y: A<'_, '_>) {
   |  ____________________________________________^
LL | |         impl A<'_, '_> {
LL | |             async fn nested_assoc(x: &u32, y: B<'_>) {}
LL | |         }
LL | |     }
   |
   |
   = note: hidden type `impl Future<Output = ()>` captures lifetime '_#34r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |             async fn nested_assoc(x: &u32, y: B<'_>) {}
   |
   |
   = note: hidden type `impl Future<Output = ()>` captures lifetime '_#28r

error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL |             async fn nested_assoc(x: &u32, y: B<'_>) {}
   |
   |
   = note: hidden type `impl Future<Output = ()>` captures lifetime '_#29r
error: aborting due to 8 previous errors

For more information about this error, try `rustc --explain E0700`.
------------------------------------------
---

40 LL | |     panic!()
41 LL | | }
42    | |_^
-    = note: required because it captures the following types: `ResumeTy`, `Option<bool>`, `impl Future<Output = !>`, `()`
+ note: required because it appears within the type `impl Future<Output = !>`
+    |
+    |
+ LL | async fn bar2<T>(_: T) -> ! {
+    |                           ^
+    = note: required because it captures the following types: `&mut Context<'_>`, `Option<bool>`, `impl Future<Output = !>`, `()`
44 note: required because it's used within this `async fn` body
46    |

51 LL | |     };
52 LL | | }
52 LL | | }
53    | |_^
+ note: required because it appears within the type `impl Future<Output = ( [...]

2022-11-14 10:18 UTC, oli-obk commented
r? @cjgillot 

@bors try @rust-timer queue

2022-11-14 11:25 UTC, rust-log-analyzer commented
The job **`dist-x86_64-linux`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/3460520048/jobs/5777141843) [(plain)](https://github.com/rust-lang-ci/rust/commit/eaf9cebf4a95bc065d5aee8056b24fc910ac20e0/checks/9470759631/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
[2022-11-14T10:54:24Z DEBUG collector::execute] Benchmark iteration 1/1
[2022-11-14T10:54:24Z INFO  collector::execute] run_rustc with incremental=false, profile=Debug, scenario=Some(Full), patch=None
[2022-11-14T10:54:24Z DEBUG collector::execute] "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "rustc" "--manifest-path" "Cargo.toml" "-p" "file:///tmp/.tmpCUBCYt#hyper@0.14.18" "--features=client,http1,http2,server,stream" "--" "--wrap-rustc-with" "Eprintln"
Finished benchmark hyper-0.14.18 (3/7)
collector error: Failed to profile 'hyper-0.14.18' with Eprintln, recorded: expected success, got exit status: 101

stderr=   Compiling tokio v1.16.1
"/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" ["--crate-name", "tokio", "--edition=2018", "/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.16.1/src/lib.rs", "--error-format=json", "--json=diagnostic-rendered-ansi,artifacts,future-incompat", "--crate-type", "lib", "--emit=dep-info,metadata,link", "-C", "embed-bitcode=no", "-C", "debuginfo=2", "--cfg", "feature=\"bytes\"", "--cfg", "feature=\"default\"", "--cfg", "feature=\"fs\"", "--cfg", "feature=\"io-std\"", "--cfg", "feature=\"io-util\"", "--cfg", "feature=\"macros\"", "--cfg", "feature=\"memchr\"", "--cfg", "feature=\"num_cpus\"", "--cfg", "feature=\"rt\"", "--cfg", "feature=\"rt-multi-thread\"", "--cfg", "feature=\"sync\"", "--cfg", "feature=\"test-util\"", "--cfg", "feature=\"time\"", "--cfg", "feature=\"tokio-macros\"", "-C", "metadata=a385249852872367", "-C", "extra-filename=-a385249852872367", "--out-dir", "/tmp/.tmpCUBCYt/target/debug/deps", "-C", "linker=clang", "-L", "dependency=/tmp/.tmpCUBCYt/target/debug/deps", "--extern", "bytes=/tmp/.tmpCUBCYt/target/debug/deps/libbytes-5e8424a0f7103369.rmeta", "--extern", "memchr=/tmp/.tmpCUBCYt/target/debug/deps/libmemchr-e6bbee201eb478c9.rmeta", "--extern", "num_cpus=/tmp/.tmpCUBCYt/target/debug/deps/libnum_cpus-266fedb888314087.rmeta", "--extern", "pin_project_lite=/tmp/.tmpCUBCYt/target/debug/deps/libpin_project_lite-d4223cfaa04037d7.rmeta", "--extern", "tokio_macros=/tmp/.tmpCUBCYt/target/debug/deps/libtokio_macros-02fe0df9f514a20a.so", "--cap-lints", "allow", "-Adeprecated", "-Aunknown-lints", "-Zincremental-verify-ich"]
exiting -- non-wrapped rustc
error: could not compile `tokio`

 stdout=

Executing benchmark regex-1.5.5 (4/7)
```

</details>

2022-11-14 22:16 UTC, Swatinem commented
I switched back to using `ResumeTy` and `get_context` which solves most of the new `E0700` issues.

I’m down to 12 failures:
- 6 are adding a new `note` that I believe I can figure out how to get rid of
- 2 now falsely assume async blocks are `const`. well as they are "just data", they are, but there is still that feature flag for it I should respect ;-)
- `src/test\ui\generic-associated-types\bugs\issue-100013.rs` suggests adding a `async move`, though not sure where that is coming from.

That leaves:
- `src/test\ui\regions\issue-72051-member-region-hang.rs` and `src/test\ui\self\self_lifetime-async.rs` are complaining about `E0700` captured lifetimes.
- `src/test\ui\impl-trait\in-trait\default-body-with-rpit.rs` now has a `E0720` cannot resolve opaque type.

I believe for these I might need to hook up the return type in a different way somehow, not yet sure how to do that.

2022-11-14 22:39 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3465559164/jobs/5788433961) [(plain)](https://github.com/rust-lang/rust/commit/5158b3d2984a82d53237cfec376e1b259e30fc01/checks/9485858713/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
iiiii.....................i..................i.......................................... 264/13840
........................................................................................ 352/13840
........................................................................................ 440/13840
........................................................................................ 528/13840
........................................................................F............... 616/13840
...............................................................................FF..F.... 704/13840
........................................................................................ 792/13840
..........F..F...i...................................................................... 880/13840
........................................................................................ 1056/13840
........................................................................................ 1144/13840
........................................................................................ 1232/13840
........................................................................................ 1320/13840
---

40 LL | |     panic!()
41 LL | | }
42    | |_^
+ note: required because it appears within the type `impl Future<Output = !>`
+    |
+    |
+ LL | async fn bar2<T>(_: T) -> ! {
+    |                           ^
43    = note: required because it captures the following types: `ResumeTy`, `Option<bool>`, `impl Future<Output = !>`, `()`
44 note: required because it's used within this `async fn` body

51 LL | |     };
52 LL | | }
53    | |_^
53    | |_^
+ note: required because it appears within the type `impl Future<Output = ()>`
+   --> $DIR/async-await-let-else.rs:21:32
+    |
+ LL | async fn foo2(x: Option<bool>) {
54 note: required by a bound in `is_send`
55   --> $DIR/async-await-let-else.rs:19:15
56    |



The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-await-let-else.drop-tracking/async-await-let-else.drop-tracking.stderr
To only update this specific test, also pass `--test-args async-await/async-await-let-else.rs`


error in revision `drop-tracking`: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/async-await/async-await-let-else.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--cfg" "drop_tracking" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-await-let-else.drop-tracking" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-await-let-else.drop-tracking/auxiliary" "--edition=2021" "-Zdrop-tracking=yes"
stdout: none
--- stderr -------------------------------
error: future cannot be sent between threads safely
   |
   |
LL |     is_send(foo(Some(true)));
   |             ^^^^^^^^^^^^^^^ future returned by `foo` is not `Send`
   |
   = help: within `impl Future<Output = ()>`, the trait `Send` is not implemented for `Rc<()>`
note: future is not `Send` as this value is used across an await
   |
   |
LL |         let r = Rc::new(());
   |             - has type `Rc<()>` which is not `Send`
LL |         bar().await
   |              ^^^^^^ await occurs here, with `r` maybe used later
LL |     };
   |     - `r` is later dropped here
  --> /checkout/src/test/ui/async-await/async-await-let-else.rs:19:15
   |
   |
LL | fn is_send<T: Send>(_: T) {}


error[E0277]: `Rc<()>` cannot be sent between threads safely
   |
   |
LL | async fn foo2(x: Option<bool>) {
   |                                - within this `impl Future<Output = ()>`
...
LL |     is_send(foo2(Some(true)));
   |     ------- ^^^^^^^^^^^^^^^^ `Rc<()>` cannot be sent between threads safely
   |     required by a bound introduced by this call
   |
   |
   = help: within `impl Future<Output = ()>`, the trait `Send` is not implemented for `Rc<()>`
note: required because it's used within this `async fn` body
   |
   |
LL |   async fn bar2<T>(_: T) -> ! {
LL | |     panic!()
LL | | }
   | |_^
   | |_^
note: required because it appears within the type `impl Future<Output = !>`
   |
   |
LL | async fn bar2<T>(_: T) -> ! {
   |                           ^
   = note: required because it captures the following types: `ResumeTy`, `Option<bool>`, `impl Future<Output = !>`, `()`
note: required because it's used within this `async fn` body
   |
   |
LL |   async fn foo2(x: Option<bool>) {
   |  ________________________________^
LL | |     let Some(_) = x else {
LL | |         bar2(Rc::new(())).await
LL | |     };
LL | | }
note: required because it appears within the type `impl Future<Output = ()>`
  --> /checkout/src/test/ui/async-await/async-await-let-else.rs:21:32
   |
   |
LL | async fn foo2(x: Option<bool>) {
note: required by a bound in `is_send`
  --> /checkout/src/test/ui/async-await/async-await-let-else.rs:19:15
   |
   |
LL | fn is_send<T: Send>(_: T) {}

error: future cannot be sent between threads safely
  --> /checkout/src/test/ui/async-await/async-await-let-else.rs:52:13
   |
   |
LL |     is_send(foo3(Some(true)));
   |             ^^^^^^^^^^^^^^^^ future returned by `foo3` is not `Send`
   |
   = help: within `impl Future<Output = ()>`, the trait `Send` is not implemented for `Rc<()>`
note: future is not `Send` as this value is used across an await
   |
   |
LL |         (Rc::new(()), bar().await);
   |          -----------       ^^^^^^ await occurs here, with `Rc::new(())` maybe used later
   |          |
   |          has type `Rc<()>` which is not `Send`
note: `Rc::new(())` is later dropped here
   |
   |
LL |         (Rc::new(()), bar().await);
note: required by a bound in `is_send`
  --> /checkout/src/test/ui/async-await/async-await-let-else.rs:19:15
   |
   |
LL | fn is_send<T: Send>(_: T) {}

error: future cannot be sent between threads safely
  --> /checkout/src/test/ui/async-await/async-await-let-else.rs:54:13
   |
   |
LL |     is_send(foo4(Some(true)));
   |             ^^^^^^^^^^^^^^^^ future returned by `foo4` is not `Send`
   |
   = help: within `impl Future<Output = ()>`, the trait `Send` is not implemented for `Rc<()>`
note: future is not `Send` as this value is used across an await
   |
   |
LL |         let r = Rc::new(());
   |             - has type `Rc<()>` which is not `Send`
LL |         bar().await;
   |              ^^^^^^ await occurs here, with `r` maybe used later
LL |     };
LL |     };
   |     - `r` is later dropped here
  --> /checkout/src/test/ui/async-await/async-await-let-else.rs:19:15
   |
   |
LL | fn is_send<T: Send>(_: T) {}

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0277`.
---
diff of stderr:

53 LL | | }
54    | |_^
55 note: required because it appears within the type `impl Future<Output = Arc<RefCell<i32>>>`
+    |
+    |
+ LL | async fn ready2<T>(t: T) -> T {
+    |                             ^
+ note: required because it appears within the type `impl Future<Output = Arc<RefCell<i32>>>`
57    |
57    |
58 LL | fn make_non_send_future2() -> impl Future<Output = Arc<RefCell<i32>>> {
59    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
59    |               [...]

2022-11-18 15:51 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3498183208/jobs/5858215440) [(plain)](https://github.com/rust-lang/rust/commit/35fbfc30f3c25b32c2d9dc6c4d7869a178f7cca1/checks/9578053752/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

---- [ui] src/test/ui/consts/async-block.rs#without_feature stdout ----
diff of stderr:

- error[E0658]: `async` blocks are not allowed in constants
-   --> $DIR/async-block.rs:12:47
+ error: fatal error triggered by #[rustc_error]
3    |
3    |
- LL | const _: i32 = { core::mem::ManuallyDrop::new(async { 0 }); 4 };
-    |
-    = note: see issue #85368 <https://github.com/rust-lang/rust/issues/85368> for more information
-    = help: add `#![feature(const_async_blocks)]` to the crate attributes to enable
+ LL | fn main() {}
+ LL | fn main() {}
+    | ^^^^^^^^^
9 
- error[E0658]: `async` blocks are not allowed in statics
-   --> $DIR/async-block.rs:15:51
-    |
- LL | static _FUT: &(dyn Future<Output = ()> + Sync) = &async {};
-    |
-    = note: see issue #85368 <https://github.com/rust-lang/rust/issues/85368> for more information
-    = help: add `#![feature(const_async_blocks)]` to the crate attributes to enable
+ error: aborting due to previous error
---
22 


The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/async-block.without_feature/async-block.without_feature.stderr
To only update this specific test, also pass `--test-args consts/async-block.rs`


error in revision `without_feature`: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/consts/async-block.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--cfg" "without_feature" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/async-block.without_feature" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/async-block.without_feature/auxiliary" "--edition=2018"
stdout: none
--- stderr -------------------------------
error: fatal error triggered by #[rustc_error]
   |
   |
LL | fn main() {} //[with_feature]~ fatal error triggered by #[rustc_error]

error: aborting due to previous error
------------------------------------------



---- [ui] src/test/ui/impl-trait/in-trait/default-body-with-rpit.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/impl-trait/in-trait/default-body-with-rpit.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-trait/in-trait/default-body-with-rpit" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-trait/in-trait/default-body-with-rpit/auxiliary" "--edition=2021"
stdout: none
--- stderr -------------------------------
error: concrete type differs from previous defining opaque type use
   |
LL |         ""
LL |         ""
   |         ^^ expected `impl Debug`, got `&'static str`
note: previous use here
  --> /checkout/src/test/ui/impl-trait/in-trait/default-body-with-rpit.rs:10:39
   |
   |
LL |       async fn baz(&self) -> impl Debug {
LL | |         ""
LL | |     }
   | |_____^


error[E0720]: cannot resolve opaque type
  --> /checkout/src/test/ui/impl-trait/in-trait/default-body-with-rpit.rs:10:28
   |
LL |     async fn baz(&self) -> impl Debug {
   |                            ^^^^^^^^^^ cannot resolve opaque type
   |
   = note: these returned values have a concrete "never" type
   = help: this error will resolve once the item's body returns a concrete type
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0720`.
------------------------------------------
------------------------------------------


---- [ui] src/test/ui/impl-trait/issues/issue-78722.rs stdout ----
diff of stderr:

- error[E0658]: `async` blocks are not allowed in constants
-   --> $DIR/issue-78722.rs:13:20
-    |
- LL |         let f: F = async { 1 };
-    |
-    = note: see issue #85368 <https://github.com/rust-lang/rust/issues/85368> for more information
-    = help: add `#![feature(const_async_blocks)]` to the crate attributes to enable
- 
- 
- error[E0493]: destructor of `F` cannot be evaluated at compile-time
-   --> $DIR/issue-78722.rs:13:13
-    |
- LL |         let f: F = async { 1 };
-    |             ^ the destructor for this type cannot be evaluated in constants
- LL |     }],
-    |     - value is dropped here
- 
- 
19 error[E0271]: expected `impl Future<Output = ()>` to be a future that resolves to `u8`, but it resolves to `()`
21    |

22 LL |         fn concrete_use() -> F {
23    |                              ^ expected `()`, found `u8`
---
To only update this specific test, also pass `--test-args impl-trait/issues/issue-78722.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/impl-trait/issues/issue-78722.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-trait/issues/issue-78722" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-trait/issues/issue-78722/auxiliary" "--edition=2018"
stdout: none
--- stderr -------------------------------
error[E0271]: expected `impl Future<Output = ()>` to be a future that resolves to `u8`, but it resolves to `()`
   |
LL |         fn concrete_use() -> F {
   |                              ^ expected `()`, found `u8`

---
---- [ui] src/test/ui/regions/issue-72051-member-region-hang.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/regions/issue-72051-member-region-hang.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/regions/issue-72051-member-region-hang" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/regions/issue-72051-member-region-hang/auxiliary" "--edition=2018"
stdout: none
--- stderr -------------------------------
error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL | pub async fn query<'a>(_: &(), _: &(), _: (&(dyn std::any::Any + 'a),) ) {}
   |                    |
   |                    |
   |                    hidden type `impl Future<Output = ()>` captures the lifetime `'a` as defined here
error [...]

2022-11-18 23:11 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3500803474/jobs/5863833795) [(plain)](https://github.com/rust-lang/rust/commit/81206607d59b0bae4459aa3efa30bd64cb84a27c/checks/9585700280/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
---- [ui] src/test/ui/impl-trait/in-trait/default-body-with-rpit.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/impl-trait/in-trait/default-body-with-rpit.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-trait/in-trait/default-body-with-rpit" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-trait/in-trait/default-body-with-rpit/auxiliary" "--edition=2021"
stdout: none
--- stderr -------------------------------
error: concrete type differs from previous defining opaque type use
   |
LL |         ""
LL |         ""
   |         ^^ expected `impl Debug`, got `&'static str`
note: previous use here
  --> /checkout/src/test/ui/impl-trait/in-trait/default-body-with-rpit.rs:10:39
   |
   |
LL |       async fn baz(&self) -> impl Debug {
LL | |         ""
LL | |     }
Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
   | |_____^
   | |_____^

error[E0720]: cannot resolve opaque type
  --> /checkout/src/test/ui/impl-trait/in-trait/default-body-with-rpit.rs:10:28
   |
LL |     async fn baz(&self) -> impl Debug {
   |                            ^^^^^^^^^^ cannot resolve opaque type
   |
   = note: these returned values have a concrete "never" type
   = help: this error will resolve once the item's body returns a concrete type
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0720`.
------------------------------------------
------------------------------------------


---- [ui] src/test/ui/regions/issue-72051-member-region-hang.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/regions/issue-72051-member-region-hang.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/regions/issue-72051-member-region-hang" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/regions/issue-72051-member-region-hang/auxiliary" "--edition=2018"
stdout: none
--- stderr -------------------------------
error[E0700]: hidden type for `impl Future<Output = ()>` captures lifetime that does not appear in bounds
   |
   |
LL | pub async fn query<'a>(_: &(), _: &(), _: (&(dyn std::any::Any + 'a),) ) {}
   |                    |
   |                    |
   |                    hidden type `impl Future<Output = ()>` captures the lifetime `'a` as defined here
error: aborting due to previous error

For more information about this error, try `rustc --explain E0700`.
------------------------------------------
------------------------------------------


---- [ui] src/test/ui/self/self_lifetime-async.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/self/self_lifetime-async.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/self/self_lifetime-async" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/self/self_lifetime-async/auxiliary" "--edition=2018"
stdout: none
--- stderr -------------------------------
error[E0700]: hidden type for `impl Future<Output = &'a ()>` captures lifetime that does not appear in bounds
   |
   |
LL |     async fn bar<'a>(self: &Alias, arg: &'a ()) -> &() { arg }
   |
   |
   = note: hidden type `impl Future<Output = &'a ()>` captures lifetime '_#17r
error: aborting due to previous error

For more information about this error, try `rustc --explain E0700`.
------------------------------------------
```

</details>

2022-11-20 21:00 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3509626591/jobs/5878855566) [(plain)](https://github.com/rust-lang/rust/commit/324f0c531ba65c7f67e4c2c2fb25dae8dedd4373/checks/9603609601/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
 finished in 6.881 seconds
Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 383 tests
i.....i..............i....i...ii................iii........ii.i........i..F............. 88/383
i.........i.iii.....i..................i...i...i.....ii..i.ii.................ii........ 264/383
................i.i..ii.ii............i..i....i......iii.......i...ii................... 352/383
Some tests failed in compiletest suite=codegen mode=codegen host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
..iiiiiiii.i...................
..iiiiiiii.i...................
failures:

---- [codegen] src/test/codegen/async-fn-debug-awaitee-field.rs stdout ----

error: verification with 'FileCheck' failed
status: exit status: 1
command: "/usr/lib/llvm-13/bin/FileCheck" "--input-file" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/async-fn-debug-awaitee-field/async-fn-debug-awaitee-field.ll" "/checkout/src/test/codegen/async-fn-debug-awaitee-field.rs" "--allow-unused-prefixes" "--check-prefixes" "CHECK,NONMSVC"
stdout: none
--- stderr -------------------------------
/checkout/src/test/codegen/async-fn-debug-awaitee-field.rs:18:13: error: NONMSVC: expected string not found in input
// NONMSVC: [[AWAITEE_TYPE]] = !DICompositeType(tag: DW_TAG_structure_type, name: "async_fn_debug_awaitee_field::foo::{async_fn_env#0}",
            ^
/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/async-fn-debug-awaitee-field/async-fn-debug-awaitee-field.ll:306:100: note: scanning from here
!163 = !DIDerivedType(tag: DW_TAG_member, name: "__awaitee", scope: !161, file: !2, baseType: !164, size: 8, align: 8, offset: 8)
                                                                                                   ^
/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/async-fn-debug-awaitee-field/async-fn-debug-awaitee-field.ll:306:100: note: with "AWAITEE_TYPE" equal to "!164"
!163 = !DIDerivedType(tag: DW_TAG_member, name: "__awaitee", scope: !161, file: !2, baseType: !164, size: 8, align: 8, offset: 8)
                                                                                                   ^
/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/async-fn-debug-awaitee-field/async-fn-debug-awaitee-field.ll:307:3: note: possible intended match here
!164 = !DICompositeType(tag: DW_TAG_structure_type, name: "{async_fn_env#0}", scope: !165, file: !2, size: 8, align: 8, elements: !166, templateParams: !23, identifier: "fc5c7c428ba260b5e550e492531a6410")

Input file: /checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/async-fn-debug-awaitee-field/async-fn-debug-awaitee-field.ll
Check file: /checkout/src/test/codegen/async-fn-debug-awaitee-field.rs


-dump-input=help explains the following input dump.
Input was:
<<<<<<
            .
            .
            .
            .
          301: !158 = !DIDerivedType(tag: DW_TAG_member, name: "2", scope: !152, file: !144, line: 12, baseType: !159, size: 16, align: 8, extraData: i64 2) 
          302: !159 = !DICompositeType(tag: DW_TAG_structure_type, name: "Panicked", scope: !149, file: !2, size: 16, align: 8, elements: !23, identifier: "60d20a5c259ef18931f3a6d28e02c23d") 
          303: !160 = !DIDerivedType(tag: DW_TAG_member, name: "3", scope: !152, file: !144, line: 11, baseType: !161, size: 16, align: 8, extraData: i64 3) 
          304: !161 = !DICompositeType(tag: DW_TAG_structure_type, name: "Suspend0", scope: !149, file: !2, size: 16, align: 8, elements: !162, templateParams: !23, identifier: "dd26c3c7e95d3b14be06904441662544") 
          305: !162 = !{!163} 
          306: !163 = !DIDerivedType(tag: DW_TAG_member, name: "__awaitee", scope: !161, file: !2, baseType: !164, size: 8, align: 8, offset: 8) 
check:18'0                                                                                                        X~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ error: no match found
check:18'1                                                                                                                                        with "AWAITEE_TYPE" equal to "!164"
          307: !164 = !DICompositeType(tag: DW_TAG_structure_type, name: "{async_fn_env#0}", scope: !165, file: !2, size: 8, align: 8, elements: !166, templateParams: !23, identifier: "fc5c7c428ba260b5e550e492531a6410") 
check:18'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:18'2       ?                                                                                                                                                                                                           possible intended match
          308: !165 = !DINamespace(name: "foo", scope: !145) 
check:18'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          309: !166 = !{!167} 
check:18'0     ~~~~~~~~~~~~~~~
          310: !167 = !DICompositeType(tag: DW_TAG_variant_part, scope: !164, file: !2, size: 8, align: 8, elements: !168, templateParams: !23, identifier: "6ce0ae470bb762954c3e3e086aaf2e87", discriminator: !175) 
check:18'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          311: !168 = !{!169, !171, !173} 
check:18'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
          312: !169 = !DIDerivedType(tag: DW_TAG_member, name: "0", scope: !167, file: !144, line: 8, baseType: !170, size: 8, align: 8, extraData: i64 0) 
check:18'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            .
            .
>>>>>>
------------------------------------------
```

</details>

2022-11-22 11:48 UTC, oli-obk requested changes

2022-11-22 11:48 UTC, oli-obk commented on compiler/rustc_trait_selection/src/traits/project.rs
> +        let ty = if name == sym::Output { return_ty } else { bug!() };
this should just be an assert or even a debug assert.

2022-11-22 11:48 UTC, oli-obk commented on compiler/rustc_hir/src/lang_items.rs
>      FromGenerator,           sym::from_generator,      from_generator_fn,          Target::Fn,             GenericRequirement::None;
you can remove this lang item now (and the function from libcore, too)

2022-11-22 11:51 UTC, oli-obk commented
> As I was asking on zulip: Do we need this at all, or can we just avoid checking the resume type at all? I’m also wondering why the generator is "capturing" that type at all? It shouldn’t be?

I think we should explore getting rid of `ResumeTy`, but I'd prefer that happen in a follow up PR

2022-11-22 22:28 UTC, Swatinem commented on compiler/rustc_trait_selection/src/traits/select/confirmation.rs
> +        // (1) Feels icky to skip the binder here, but OTOH we know
An `expect` there actually does panic for the `src/test/ui/generator/resume-arg-late-bound.rs` test.

I only moved this code between the files, the same comment and code pattern exists as well for normal closures:

https://github.com/rust-lang/rust/blob/e221616639fb87de9dca21e252ee8a2565ec51d0/compiler/rustc_trait_selection/src/traits/select/mod.rs#L2290

2022-11-22 22:39 UTC, oli-obk commented
@bors try @rust-timer queue

2022-11-22 22:39 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2022-11-22 22:58 UTC, rust-log-analyzer commented
The job **`dist-x86_64-linux`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/3527642313/jobs/5916925030) [(plain)](https://github.com/rust-lang-ci/rust/commit/35d348af1bc3bb2c05441c58bf27235822e5a399/checks/9653174100/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling rustc_transmute v0.1.0 (/checkout/compiler/rustc_transmute)
[RUSTC-TIMING] rustc_parse test:false 26.883
   Compiling rustc_trait_selection v0.0.0 (/checkout/compiler/rustc_trait_selection)
[RUSTC-TIMING] rustc_save_analysis test:false 10.129
error[E0271]: type mismatch resolving `<&[_; 0] as IntoIterator>::Item == rustc_middle::ty::GenericArg<'_>`
    |
    |
329 |         ty::TraitRef { def_id: fn_trait_def_id, substs: tcx.mk_substs_trait(self_ty, &[]) };
    |                                                             ---------------          ^^^ expected struct `rustc_middle::ty::GenericArg`, found reference
    |                                                             required by a bound introduced by this call
    |
    = note: expected struct `rustc_middle::ty::GenericArg<'_>`
            found reference `&_`
            found reference `&_`
note: required by a bound in `rustc_middle::ty::TyCtxt::<'tcx>::mk_substs_trait`
For more information about this error, try `rustc --explain E0271`.
[RUSTC-TIMING] rustc_trait_selection test:false 2.615
error: could not compile `rustc_trait_selection` due to previous error
warning: build failed, waiting for other jobs to finish...
```

</details>

2022-11-23 11:12 UTC, oli-obk commented
ah, you need to keep the `from_generator` lang item there, but hide it behind `#[cfg(bootstrap)]`. Looks like benchmarks use it with the bootstrap compiler

2022-11-23 11:23 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3531391933/jobs/5924508166) [(plain)](https://github.com/rust-lang/rust/commit/5bdc596812f7f7a07adc3fdb06b54187a574bb91/checks/9662989513/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
  --> library/alloc/tests/autotraits.rs:38:29
   |
38 |       require_send_sync(async {
   |  _____________________________^
39 | |         let _v = None::<alloc::collections::btree_map::Iter<'_, &u32, &u32>>;
40 | |         async {}.await;
   | |_____^

error: requires `from_generator` lang_item
   --> library/alloc/tests/autotraits.rs:141:29
   --> library/alloc/tests/autotraits.rs:141:29
    |
141 |       require_send_sync(async {
    |  _____________________________^
142 | |         let _v = None::<alloc::collections::btree_set::BTreeSet<&u32>>;
143 | |         async {}.await;
    | |_____^

error: requires `from_generator` lang_item
   --> library/alloc/tests/autotraits.rs:189:29
   --> library/alloc/tests/autotraits.rs:189:29
    |
189 |       require_send_sync(async {
    |  _____________________________^
190 | |         let _v = None::<alloc::collections::binary_heap::BinaryHeap<&u32>>;
191 | |         async {}.await;
    | |_____^

error: requires `from_generator` lang_item
   --> library/alloc/tests/autotraits.rs:227:29
   --> library/alloc/tests/autotraits.rs:227:29
    |
227 |       require_send_sync(async {
    |  _____________________________^
228 | |         let _v = None::<alloc::collections::linked_list::Cursor<'_, &u32>>;
229 | |         async {}.await;
    | |_____^

error: requires `from_generator` lang_item
   --> library/alloc/tests/autotraits.rs:269:29
   --> library/alloc/tests/autotraits.rs:269:29
    |
269 |       require_send_sync(async {
    |  _____________________________^
270 | |         let _v = None::<alloc::collections::vec_deque::Drain<'_, &u32>>;
271 | |         async {}.await;
    | |_____^

error: could not compile `alloc` due to 5 previous errors
warning: build failed, waiting for other jobs to finish...
warning: build failed, waiting for other jobs to finish...
error: requires `from_generator` lang_item
  --> library/core/tests/future.rs:76:38
   |
76 |     async fn async_fn(_: impl Sized) {}

error: could not compile `core` due to previous error
Build completed unsuccessfully in 0:02:45
```

</details>

2022-11-23 12:15 UTC, Swatinem commented
> ah, you need to keep the `from_generator` lang item there, but hide it behind `#[cfg(bootstrap)]`. Looks like benchmarks use it with the bootstrap compiler

I almost expected something like this 😅 

I do get a `thread 'rustc' panicked at 'no entry found for key', compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:641:9` locally checking `rustc_codegen_cranelift`, though that seems to come from the beta bootstrap compiler, so hopefully not related.

2022-11-23 13:55 UTC, oli-obk commented
> I do get a `thread 'rustc' panicked at 'no entry found for key', compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:641:9` locally checking `rustc_codegen_cranelift`, though that seems to come from the beta bootstrap compiler, so hopefully not related.

this can happen after rebasing. only solution I know is `./x.py clean`

2022-11-23 15:18 UTC, Swatinem commented
Ah yes, I had a similar problem in another place as well that got fixed by `x clean`.

I circled back a bit with my changes and now all the async blocks go through `identity_future`. That also reverts quite a bit of diagnostics changes (also some improvements).

I believe that is sensible thing to do for now, so people using `async {}` blocks manually do not run into the captured lifetime issues that I struggled with for a week.

That can be revisited once the reason for the `identity_future` goes away.

Also fixed up some clippy issues, though I wonder why they did not pop up previously, probably because I did not touch the clippy subtree so CI did not run it?

2022-11-24 09:16 UTC, oli-obk commented
@bors try @rust-timer queue

2022-11-24 11:44 UTC, rust-timer commented
Queued 8b9b290ad9a7726ada535017f72d9d5673852708 with parent fd815a5091eb4d49cd317f8ad272f17b7a5f550d, future [comparison URL](https://perf.rust-lang.org/compare.html?start=fd815a5091eb4d49cd317f8ad272f17b7a5f550d&end=8b9b290ad9a7726ada535017f72d9d5673852708).
<!-- rust-timer: temporary -->

2022-11-24 13:03 UTC, rust-timer commented
Finished benchmarking commit (8b9b290ad9a7726ada535017f72d9d5673852708): [comparison URL](https://perf.rust-lang.org/compare.html?start=fd815a5091eb4d49cd317f8ad272f17b7a5f550d&end=8b9b290ad9a7726ada535017f72d9d5673852708&stat=instructions:u).

### Overall result: ✅ improvements - no action needed


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf -perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=fd815a5091eb4d49cd317f8ad272f17b7a5f550d&end=8b9b290ad9a7726ada535017f72d9d5673852708&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean   | range           | count |
|:----------------------------------:|:------:|:---------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -      | -               | 0     |
| Regressions ❌ <br /> (secondary)  | -      | -               | 0     |
| Improvements ✅ <br /> (primary)   | -0.3%  | [-0.4%, -0.3%]  | 3     |
| Improvements ✅ <br /> (secondary) | -24.7% | [-87.7%, -0.3%] | 25    |
| All ❌✅ (primary)                 | -0.3%  | [-0.4%, -0.3%]  | 3     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=fd815a5091eb4d49cd317f8ad272f17b7a5f550d&end=8b9b290ad9a7726ada535017f72d9d5673852708&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range           | count |
|:----------------------------------:|:-----:|:---------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -               | 0     |
| Regressions ❌ <br /> (secondary)  | 1.4%  | [0.8%, 1.9%]    | 2     |
| Improvements ✅ <br /> (primary)   | -     | -               | 0     |
| Improvements ✅ <br /> (secondary) | -4.8% | [-11.7%, -1.2%] | 7     |
| All ❌✅ (primary)                 | -     | -               | 0     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=fd815a5091eb4d49cd317f8ad272f17b7a5f550d&end=8b9b290ad9a7726ada535017f72d9d5673852708&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean   | range           | count |
|:----------------------------------:|:------:|:---------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -      | -               | 0     |
| Regressions ❌ <br /> (secondary)  | -      | -               | 0     |
| Improvements ✅ <br /> (primary)   | -      | -               | 0     |
| Improvements ✅ <br /> (secondary) | -19.1% | [-78.9%, -2.2%] | 27    |
| All ❌✅ (primary)                 | -      | -               | 0     |
</details>

2022-11-24 13:15 UTC, oli-obk commented
r? @oli-obk 

@bors r+

2022-11-24 13:25 UTC, Swatinem commented on library/core/src/future/mod.rs
> +pub const fn identity_future<O, Fut: Future<Output = O>>(f: Fut) -> Fut {
Here you go: https://github.com/rust-lang/rust/issues/104826

2022-11-24 20:29 UTC, merged

2022-11-24 21:48 UTC, rust-timer commented
Finished benchmarking commit (5dfb4b0afaf6acace0845d00e85a934fb4289d83): [comparison URL](https://perf.rust-lang.org/compare.html?start=1dda298ad39a64e019a3511139c5b13ac0a18e54&end=5dfb4b0afaf6acace0845d00e85a934fb4289d83&stat=instructions:u).

### Overall result: ✅ improvements - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=1dda298ad39a64e019a3511139c5b13ac0a18e54&end=5dfb4b0afaf6acace0845d00e85a934fb4289d83&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean   | range           | count |
|:----------------------------------:|:------:|:---------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -      | -               | 0     |
| Regressions ❌ <br /> (secondary)  | -      | -               | 0     |
| Improvements ✅ <br /> (primary)   | -      | -               | 0     |
| Improvements ✅ <br /> (secondary) | -28.0% | [-87.8%, -1.9%] | 22    |
| All ❌✅ (primary)                 | -      | -               | 0     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=1dda298ad39a64e019a3511139c5b13ac0a18e54&end=5dfb4b0afaf6acace0845d00e85a934fb4289d83&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range           | count |
|:----------------------------------:|:-----:|:---------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -               | 0     |
| Regressions ❌ <br /> (secondary)  | 1.6%  | [1.6%, 1.6%]    | 1     |
| Improvements ✅ <br /> (primary)   | -2.1% | [-2.1%, -2.1%]  | 1     |
| Improvements ✅ <br /> (secondary) | -4.3% | [-11.9%, -2.1%] | 11    |
| All ❌✅ (primary)                 | -2.1% | [-2.1%, -2.1%]  | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=1dda298ad39a64e019a3511139c5b13ac0a18e54&end=5dfb4b0afaf6acace0845d00e85a934fb4289d83&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean   | range           | count |
|:----------------------------------:|:------:|:---------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -      | -               | 0     |
| Regressions ❌ <br /> (secondary)  | 2.6%   | [2.6%, 2.6%]    | 1     |
| Improvements ✅ <br /> (primary)   | -      | -               | 0     |
| Improvements ✅ <br /> (secondary) | -25.0% | [-79.8%, -2.2%] | 20    |
| All ❌✅ (primary)                 | -      | -               | 0     |
</details>

2022-12-04 09:51 UTC, bjorn3 commented
As of this PR cg_clif's CI is [failing](https://github.com/bjorn3/rustc_codegen_cranelift/actions/runs/3612656254/jobs/6087902827) with

```rust
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `&mut std::task::Context<'_>`,
 right: `std::future::ResumeTy`: Can't write value with incompatible type Ref(ReErased, std::task::Context<'_>, Mut) to place with type Adt(std::future::ResumeTy, [])
```

It seems that an `&mut Context<'_>` is passed to poll function expecting `ResumeTy`. Both types are currently abi compatible by accident, but `-Zrandomize-layout` will break this in the future once it starts randomly adding padding to types.

2022-12-04 10:52 UTC, bjorn3 commented
And after a patch to make it ignore this particular mismatch I get:

```
 thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `std::ops::GeneratorState<(), ()>`,
 right: `std::task::Poll<()>`: Can't write value with incompatible type Adt(std::ops::GeneratorState, [(), ()]) to place with type Adt(std::task::Poll, [()])
```

Poking a bit around confirms that `<[async fn body@example/std_example.rs:20:19: 20:21] as std::future::Future>::poll` does indeed accept `ResumeTy` and return `std::ops::GeneratorState<(), ()>` in violation of the `Future::poll` signature.

```
[src/abi/mod.rs:402] &instance = Some(Instance {
    def: Item(WithOptConstParam { did: DefId(0:20 ~ std_example[7fb1]::future::{closure#0}), const_param_did: None }),
    substs: [std::future::ResumeTy, (), (), {}, ()],
})
[src/abi/mod.rs:402] &fn_abi = FnAbi {
    args: [
        ArgAbi {
            layout: TyAndLayout {
                ty: std::pin::Pin<&mut [async fn body@example/std_example.rs:20:19: 20:21]>,
                layout: ...,
            },
            mode: Direct(...),
        },
        ArgAbi {
            layout: TyAndLayout {
                ty: std::future::ResumeTy,
                layout: ...,
            },
            mode: Direct(...),
        },
    ],
    ret: ArgAbi {
        layout: TyAndLayout {
            ty: std::ops::GeneratorState<(), ()>,
            layout: ...,
        },
        mode: Direct(...),
    },
    c_variadic: false,
    fixed_count: 2,
    conv: Rust,
    can_unwind: false,
}
```

A minimal reproducing example is:

```rust
#![feature(pin_macro)]

use std::pin::{pin, Pin};
use std::future::Future;
use std::ptr::null;
use std::task::{Context, Waker, RawWaker, RawWakerVTable};

fn main() {
    let waker = unsafe {
        Waker::from_raw(RawWaker::new(null(), &RawWakerVTable::new(|_| todo!(), |_| todo!(), |_| todo!(), |_| todo!())))
    };
    let mut cx = Context::from_waker(&waker);
    call_future(pin!(future()), &mut cx);
}

fn call_future(fut: Pin<&mut impl Future<Output = ()>>, cx: &mut Context) {
    fut.poll(cx);
}

async fn future() {}
```

2022-12-04 11:10 UTC, oli-obk commented
This is being fixed in https://github.com/rust-lang/rust/pull/105082#issuecomment-1332210907

2022-12-04 11:13 UTC, bjorn3 commented
Thanks for the pointer!