Simplify settings theme choice
rust-lang/rust pull request #104366
Opened 2022-11-13 14:52 UTC by GuillaumeGomez

I removed the storage changes from https://github.com/rust-lang/rust/pull/98765 and only kept the UI changes.

You can test it [here](https://rustdoc.crud.net/imperio/simplify-settings-theme-choice/foo/index.html).

Discussion about this still in progress [on zulip](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/Last.20part.20of.20settings.20simplification).

r? @notriddle

2022-11-13 15:17 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3455735361/jobs/5767964371) [(plain)](https://github.com/rust-lang/rust/commit/ecdb61bd759098c7487c3377dc30b713c245b6ec/checks/9459457976/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
Attempting with retry: make prepare
---
* highest error code: E0790
Found 506 error codes
Found 0 error(s) in error codes
Done!
tidy error: /checkout/src/librustdoc/html/static/js/settings.js:146: trailing whitespace
some tidy checks failed
Build completed unsuccessfully in 0:00:09
```

</details>

2022-11-13 16:03 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3455846415/jobs/5768154226) [(plain)](https://github.com/rust-lang/rust/commit/bb6fc38c75873344c1988c15a84aab02c35135c0/checks/9459680798/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
Attempting with retry: make prepare
---
info: ES-Check: there were no ES version matching errors!  🎉
+ eslint -c ../src/librustdoc/html/static/.eslintrc.js ../src/librustdoc/html/static/js/externs.js ../src/librustdoc/html/static/js/main.js ../src/librustdoc/html/static/js/scrape-examples.js ../src/librustdoc/html/static/js/search.js ../src/librustdoc/html/static/js/settings.js ../src/librustdoc/html/static/js/source-script.js ../src/librustdoc/html/static/js/storage.js

/checkout/src/librustdoc/html/static/js/settings.js
  142:69  error  Unnecessary escape character: \ .  no-useless-escape

✖ 1 problem (1 error, 0 warnings)
```

</details>

2022-11-13 16:14 UTC, Urgau requested changes
LGTM, for the design part.

There is however a bug for people how have old theme settings (and doesn't touch anything in the theme settings).

<details>
<summary>
Screenshot of problem
</summary>

![Capture d’écran du 2022-11-13 16-54-53](https://user-images.githubusercontent.com/3616612/201531812-90d5e81f-ddd8-4501-8c4f-26ff806872cf.png)

</details>

2022-11-13 17:11 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3456114649/jobs/5768621785) [(plain)](https://github.com/rust-lang/rust/commit/0f4e65adec58286bde82a436582eeeb204991861/checks/9460233925/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
Attempting with retry: make prepare
---
info: ES-Check: there were no ES version matching errors!  🎉
+ eslint -c ../src/librustdoc/html/static/.eslintrc.js ../src/librustdoc/html/static/js/externs.js ../src/librustdoc/html/static/js/main.js ../src/librustdoc/html/static/js/scrape-examples.js ../src/librustdoc/html/static/js/search.js ../src/librustdoc/html/static/js/settings.js ../src/librustdoc/html/static/js/source-script.js ../src/librustdoc/html/static/js/storage.js

/checkout/src/librustdoc/html/static/js/settings.js
  63:34  error  Unexpected mix of '||' and '&&'. Use parentheses to clarify the intended order of operations  no-mixed-operators
  63:56  error  Unexpected mix of '||' and '&&'. Use parentheses to clarify the intended order of operations  no-mixed-operators

✖ 2 problems (2 errors, 0 warnings)
```

</details>

2022-11-13 22:59 UTC, Urgau approved these changes

2022-11-16 16:33 UTC, notriddle approved these changes

2022-11-18 13:12 UTC, merged