Remove double spaces after dots in comments
rust-lang/rust pull request #104505
Opened 2022-11-16 20:49 UTC by WaffleLapkin

Most of the comments do not have double spaces, so I assume these are typos.

2022-11-16 20:50 UTC, GuillaumeGomez approved these changes

2022-11-16 20:52 UTC, GuillaumeGomez commented
I wondered why we have some double white space in some places too.

2022-11-16 21:15 UTC, saethlin commented
It wouldn't hurt to have uniformity, but for some people this is a deliberate stylistic choice. I suspect the majority of these are deliberate, not typos.

2022-11-16 21:18 UTC, GuillaumeGomez commented
Interesting. It doesn't have an impact on generated documentation so I guess it's for people reading the source code directly?

2022-11-16 21:25 UTC, WaffleLapkin commented
@saethlin a **lot** of these changes happen in comments with multiple sentences, where only a single double space is present, so I don't think majority is deliberate.

@GuillaumeGomez most of the changes happen in comments, not doc comments, so these are for source code readers anyway :)

2022-11-21 09:58 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3513283281/jobs/5885920267) [(plain)](https://github.com/rust-lang/rust/commit/d2b4eaf34585c5642105e4edea464d0892b1e002/checks/9612332485/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking rustc_mir_build v0.0.0 (/checkout/compiler/rustc_mir_build)
error: expected identifier, found `<<`
  --> compiler/rustc_const_eval/src/transform/validate.rs:71:1
   |
71 | <<<<<<< HEAD
   | ^^ expected identifier
error: could not compile `rustc_const_eval` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `rustc_const_eval` due to previous error
Build completed unsuccessfully in 0:03:31
```

</details>

2022-11-21 17:36 UTC, jackh726 commented
So...I'm inclined to think that we shouldn't merge this.

First, I've learned that some people have been taught to use two spaces between sentences instead of one. So it's very much possible that many of these are intentional.

Second, the difference between one and two spaces visually doesn't make much difference. It also doesn't really hinder the effectiveness of the comments in any way.

Third, given point one that these might be intentional, we don't have any style guides or rules for one space vs two. And moreso, we don't have a way to keep *new* comments from having two spaces between sentences.

Given all the above points and that this is kind of touches a lot of files (and I don't think historically we have really sought pull requests for simple stylistic changes), this doesn't really seem like something worth merging. But I'm curious on others' opinions.

2022-11-22 07:37 UTC, WaffleLapkin commented
> Second, the difference between one and two spaces visually doesn't make much difference.

I don't agree, for me it makes a big difference, that's why I've made this pr in in the first place — my eyes caught on the double spaces every time I saw them.

> And moreso, we don't have a way to keep new comments from having two spaces between sentences.

It was proposed that we can grep for something like `\w\.  \w` in tidy.

----

I do not really have anything to say to other points though. I do think having a stylistic choice here would be nice. But if it's only important for me, then leaving this as is okay.

2022-11-22 14:05 UTC, jackh726 commented
I'll just cc @rust-lang/compiler for other thoughts then

2022-11-22 14:13 UTC, oli-obk commented
As long as tidy checks it, and in a way that submodules are ignored, this seems fine to me

2022-11-28 08:44 UTC, eddyb requested changes

2022-11-28 08:44 UTC, eddyb commented on compiler/rustc_apfloat/src/ieee.rs
> +        // in `dst`. If this is less that src_bits, append the rest, else
Please back out changes to `compiler/rustc_apfloat`, we don't want these to diverge again:
* in-tree: https://github.com/rust-lang/rust/commits/master/compiler/rustc_apfloat
* in-progress extraction: https://github.com/LykenSol/rustc_apfloat-git-history-extraction/commits/main

2022-12-26 20:19 UTC, jackh726 commented
@WaffleLapkin what do you want to do here? Do you want to make a change to tidy?

2022-12-28 14:08 UTC, WaffleLapkin commented
@jackh726 I'm not sure if it's worth it, given the comments above...

But if the tidy check makes sense then I would gladly implement it.

2022-12-28 15:48 UTC, GuillaumeGomez commented
I think writing a tidy check is definitely a good idea.

2023-01-03 20:36 UTC, wesleywiser commented
While I'm very sympathetic to efforts to improve documentation hygiene and style, I don't think we should merge changes to things like formatting that can't be automatically checked by `tidy` as that either shifts the burden of maintaining the correct style onto reviewers or causes an unending stream of "incorrect" PRs and subsequent "fix style of `x`" PRs. 

Therefore, if we want to adopt this style, I feel like it should be `tidy` checkable.

2023-01-12 20:02 UTC, WaffleLapkin commented
I've added a tidy check and removed `rustc_apfloat` changes.

2023-01-13 09:05 UTC, WaffleLapkin commented
@Mark-Simulacrum can you review tidy changes?

2023-01-17 02:41 UTC, jackh726 commented
Can you move the whitespace changes in the tidy commit to the first commit?

After that, r=me.

2023-01-17 08:13 UTC, WaffleLapkin commented
@bors r=jackh726

2023-01-18 00:23 UTC, merged