add instructions on how to use bench along stable rust
rust-lang/rust pull request #104603
Opened 2022-11-19 09:51 UTC by sigmaSd

I personally found this useful, so I thought maybe its interesting to add it here.

criterion can't bench binary crates or do inline bench-marking, so cargo bench still have its own use-cases.

Using cargo-bench in a project built with rust stable is not that obvious, so this PR add an example of how to do it.

2022-11-19 09:53 UTC, GuillaumeGomez commented
r? t-lang

2022-11-19 09:54 UTC, GuillaumeGomez commented
r? rust-lang/libs

2022-11-19 15:09 UTC, Kobzol commented on src/doc/unstable-book/src/library-features/test.md
> +To improve user experience when using `cargo bench` in a porject built with stable rust,
```suggestion
To improve user experience when using `cargo bench` in a project built with stable rust,
```

2022-11-19 15:37 UTC, albertlarsan68 commented on src/doc/unstable-book/src/library-features/test.md
> +you can gate all the benchmarking under a seperate feature that you shoulld only call it
```suggestion
you can gate all the benchmarking under a seperate feature that you should only call it
```

2022-11-29 13:44 UTC, jyn514 requested changes
I don't think this is an accurate description of your change. This is an *unstable* feature; saying "run with nightly and use cfgs so you don't get a compile error on stable" isn't something that should be in the stable docs IMO, and it certainly doesn't belong in docs that are specific to `bench`.

2022-11-29 14:20 UTC, sigmaSd commented
Its called the unstable book though

Anyhow feel free to close this or point me to where it belongs, personally its a neat trick I discovered thought it needs more attention, but its cool either way

2023-05-17 16:53 UTC, closed without merging