Combine `ty::Projection` and `ty::Opaque` into `ty::Alias`
rust-lang/rust pull request #104986
Opened 2022-11-27 17:27 UTC by compiler-errors

The different alias kinds are distinguished with `ty::AliasKind`, conveniently glob-imported into `ty::{Projection, Opaque}`. For example:

```
match ty.kind() {
  ty::Alias(ty::Opaque, _) => {}
  _ => {}
}
```

r? @ghost

2022-11-27 17:51 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3559238068/jobs/5978457860) [(plain)](https://github.com/rust-lang/rust/commit/3c83b501304c95d5a29682d2e9da0d8130437eca/checks/9730959383/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling std v0.0.0 (/checkout/library/std)
   Compiling compiler_builtins v0.1.84
   Compiling unwind v0.0.0 (/checkout/library/unwind)
   Compiling rustc-std-workspace-core v1.99.0 (/checkout/library/rustc-std-workspace-core)
thread 'rustc' panicked at 'invalid enum variant tag while decoding `TyKind`, expected 0..27', /checkout/compiler/rustc_type_ir/src/sty.rs:766:18
stack backtrace:
   0:     0x7eff4b503512 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h76efda83803f7c88
   1:     0x7eff4b571658 - core::fmt::write::h0cd9f5419c66d611
   2:     0x7eff4b4f3fe1 - std::io::Write::write_fmt::h115d78592252bf9d
   3:     0x7eff4b5032d5 - std::sys_common::backtrace::print::hd9ebfd55eb3388eb
   4:     0x7eff4b5065e7 - std::panicking::default_hook::{{closure}}::h98850a6457a8782d
   5:     0x7eff4b506345 - std::panicking::default_hook::hef750a0d73d5e8e9
   6:     0x7eff4bee6f14 - rustc_driver[ab3ba77cd7534cfb]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:     0x7eff4b506ef3 - std::panicking::rust_panic_with_hook::ha62dd9a4e901383e
   8:     0x7eff4b506c27 - std::panicking::begin_panic_handler::{{closure}}::h30577589484d4d4f
   9:     0x7eff4b503abc - std::sys_common::backtrace::__rust_end_short_backtrace::h8641e565b807163f
  10:     0x7eff4b5068f2 - rust_begin_unwind
  11:     0x7eff4b4b8023 - core::panicking::panic_fmt::ha29375e42f9e82fb
  12:     0x7eff4e1cd521 - core[867cfca19013d5a]::panicking::panic_display::<alloc[6d250edaf69a7784]::string::String>
  13:     0x7eff4e1dd7ce - <rustc_middle[4f81a7ac8c79b4c8]::ty::Ty as rustc_serialize[a271f74fabc451c9]::serialize::Decodable<rustc_metadata[48d6e4923091dbdd]::rmeta::decoder::DecodeContext>>::decode
  14:     0x7eff4e2668ef - <rustc_metadata[48d6e4923091dbdd]::rmeta::decoder::DecodeContext as rustc_type_ir[9ccd8fdedb26e56b]::codec::TyDecoder>::cached_ty_for_shorthand::<<rustc_middle[4f81a7ac8c79b4c8]::ty::Ty as rustc_serialize[a271f74fabc451c9]::serialize::Decodable<rustc_metadata[48d6e4923091dbdd]::rmeta::decoder::DecodeContext>>::decode::{closure#0}>
  15:     0x7eff4e1dd380 - <rustc_middle[4f81a7ac8c79b4c8]::ty::Ty as rustc_serialize[a271f74fabc451c9]::serialize::Decodable<rustc_metadata[48d6e4923091dbdd]::rmeta::decoder::DecodeContext>>::decode
  16:     0x7eff4e1ddd0c - <&rustc_middle[4f81a7ac8c79b4c8]::ty::list::List<rustc_middle[4f81a7ac8c79b4c8]::ty::subst::GenericArg> as rustc_serialize[a271f74fabc451c9]::serialize::Decodable<rustc_metadata[48d6e4923091dbdd]::rmeta::decoder::DecodeContext>>::decode
  17:     0x7eff4e1dd5c7 - <rustc_middle[4f81a7ac8c79b4c8]::ty::Ty as rustc_serialize[a271f74fabc451c9]::serialize::Decodable<rustc_metadata[48d6e4923091dbdd]::rmeta::decoder::DecodeContext>>::decode
  18:     0x7eff4e2668ef - <rustc_metadata[48d6e4923091dbdd]::rmeta::decoder::DecodeContext as rustc_type_ir[9ccd8fdedb26e56b]::codec::TyDecoder>::cached_ty_for_shorthand::<<rustc_middle[4f81a7ac8c79b4c8]::ty::Ty as rustc_serialize[a271f74fabc451c9]::serialize::Decodable<rustc_metadata[48d6e4923091dbdd]::rmeta::decoder::DecodeContext>>::decode::{closure#0}>
  19:     0x7eff4e1dd380 - <rustc_middle[4f81a7ac8c79b4c8]::ty::Ty as rustc_serialize[a271f74fabc451c9]::serialize::Decodable<rustc_metadata[48d6e4923091dbdd]::rmeta::decoder::DecodeContext>>::decode
  20:     0x7eff4e205cd3 - <rustc_metadata[48d6e4923091dbdd]::rmeta::LazyValue<rustc_middle[4f81a7ac8c79b4c8]::ty::Ty>>::decode::<(rustc_metadata[48d6e4923091dbdd]::creader::CrateMetadataRef, rustc_middle[4f81a7ac8c79b4c8]::ty::context::TyCtxt)>
  21:     0x7eff4e16024a - rustc_metadata[48d6e4923091dbdd]::rmeta::decoder::cstore_impl::provide_extern::type_of
  22:     0x7eff4dc41715 - rustc_query_system[b7532c72bbf7e115]::query::plumbing::try_execute_query::<rustc_query_impl[b2ca3a4d56ef3bb1]::plumbing::QueryCtxt, rustc_query_system[b7532c72bbf7e115]::query::caches::DefaultCache<rustc_span[84eb59eb28be3601]::def_id::DefId, rustc_middle[4f81a7ac8c79b4c8]::ty::Ty>>
  23:     0x7eff4dd833c8 - rustc_query_system[b7532c72bbf7e115]::query::plumbing::get_query::<rustc_query_impl[b2ca3a4d56ef3bb1]::queries::type_of, rustc_query_impl[b2ca3a4d56ef3bb1]::plumbing::QueryCtxt>
  24:     0x7eff4d903bae - <rustc_query_impl[b2ca3a4d56ef3bb1]::Queries as rustc_middle[4f81a7ac8c79b4c8]::ty::query::QueryEngine>::type_of
  25:     0x7eff4c7c2865 - <dyn rustc_hir_analysis[310abef0984c523]::astconv::AstConv>::ast_path_to_ty
  26:     0x7eff4c7d1c60 - <dyn rustc_hir_analysis[310abef0984c523]::astconv::AstConv>::res_to_ty
  27:     0x7eff4c7e83e3 - <dyn rustc_hir_analysis[310abef0984c523]::astconv::AstConv>::ast_ty_to_ty_inner
  28:     0x7eff4c764733 - <core[867cfca19013d5a]::iter::adapters::map::Map<core[867cfca19013d5a]::iter::adapters::enumerate::Enumerate<core[867cfca19013d5a]::slice::iter::Iter<rustc_hir[3b98b05658f9e115]::hir::Ty>>, <dyn rustc_hir_analysis[310abef0984c523]::astconv::AstConv>::ty_of_fn::{closure#0}::{closure#0}> as core[867cfca19013d5a]::iter::traits::iterator::Iterator>::fold::<(), core[867cfca19013d5a]::iter::traits::iterator::Iterator::for_each::call<rustc_middle[4f81a7ac8c79b4c8]::ty::Ty, <alloc[6d250edaf69a7784]::vec::Vec<rustc_middle[4f81a7ac8c79b4c8]::ty::Ty>>::extend_trusted<core[867cfca19013d5a]::iter::adapters::map::Map<core[867cfca19013d5a]::iter::adapters::enumerate::Enumerate<core[867cfca19013d5a]::slice::iter::Iter<rustc_hir[3b98b05658f9e115]::hir::Ty>>, <dyn rustc_hir_analysis[310abef0984c523]::astconv::AstConv>::ty_of_fn::{closure#0}::{closure#0}>>::{closure#0}>::{closure#0}>
  29:     0x7eff4c7fca53 - <alloc[6d250edaf69a7784]::vec::Vec<rustc_middle[4f81a7ac8c79b4c8]::ty::Ty> as alloc[6d250edaf69a7784]::vec::spec_from_iter::SpecFromIter<rustc_middle[4f81a7ac8c79b4c8]::ty::Ty, core[867cfca19013d5a]::iter::adapters::map::Map<core[867cfca19013d5a]::iter::adapters::enumerate::Enumerate<core[867cfca19013d5a]::slice::iter::Iter<rustc_hir[3b98b05658f9e115]::hir::Ty>>, <dyn rustc_hir_analysis[310abef0984c523]::astconv::AstConv>::ty_of_fn::{closure#0}::{closure#0}>>>::from_iter
  30:     0x7eff4c7e9eea - <dyn rustc_hir_analysis[310abef0984c523]::astconv::AstConv>::ty_of_fn
  31:     0x7eff4c75a5f2 - rustc_hir_analysis[310abef0984c523]::collect::fn_sig
  32:     0x7eff4dc3a950 - rustc_query_system[b7532c72bbf7e115]::query::plumbing::try_execute_query::<rustc_query_impl[b2ca3a4d56ef3bb1]::plumbing::QueryCtxt, rustc_query_system[b7532c72bbf7e115]::query::caches::DefaultCache<rustc_span[84eb59eb28be3601]::def_id::DefId, rustc_middle[4f81a7ac8c79b4c8]::ty::sty::Binder<rustc_middle[4f81a7ac8c79b4c8]::ty::sty::FnSig>>>
  33:     0x7eff4dd82ec5 - rustc_query_system[b7532c72bbf7e115]::query::plumbing::get_query::<rustc_query_impl[b2ca3a4d56ef3bb1]::queries::fn_sig, rustc_query_impl[b2ca3a4d56ef3bb1]::plumbing::QueryCtxt>
  34:     0x7eff4d92138c - <rustc_query_impl[b2ca3a4d56ef3bb1]::Queries as rustc_middle[4f81a7ac8c79b4c8]::ty::query::QueryEngine>::fn_sig
  35:     0x7eff4c60a385 - <rustc_privacy[d80f65a39f38abc1]::DefIdVisitorSkeleton<rustc_privacy[d80f65a39f38abc1]::ReachEverythingInTheInterfaceVisitor> as rustc_middle[4f81a7ac8c79b4c8]::ty::visit::TypeVisitor>::visit_ty
  36:     0x7eff4c60e6e0 - <rustc_privacy[d80f65a39f38abc1]::ReachEverythingInTheInterfaceVisitor>::ty
  37:     0x7eff4c60cb1b - <rustc_privacy[d80f65a39f38abc1]::EmbargoVisitor as rustc_hir[3b98b05658f9e115]::intravisit::Visitor>::visit_item
  38:     0x7eff4c62187d - rustc_hir[3b98b05658f9e115]::intravisit::walk_item::<rustc_privacy[d80f65a39f38abc1]::EmbargoVisitor>
  39:     0x7eff4c60cc5e - <rustc_privacy[d80f65a39f38abc1]::EmbargoVisitor as rustc_hir[3b98b05658f9e115]: [...]

2022-11-27 19:04 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3559435569/jobs/5978784966) [(plain)](https://github.com/rust-lang/rust/commit/ffa42208d838ceae32402419f9b7de8f068fcb44/checks/9731338352/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
failures:

---- [ui] src/test/ui/impl-trait/in-trait/issue-102140.rs stdout ----

error: Error: expected failure status (Some(1)) but received status None.
status: signal: 6 (SIGABRT) (core dumped)
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/impl-trait/in-trait/issue-102140.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-trait/in-trait/issue-102140" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-trait/in-trait/issue-102140/auxiliary"
stdout: none
--- stderr -------------------------------
thread 'rustc' panicked at 'assertion failed: matches!(tcx.def_kind(self.def_id), DefKind :: AssocTy | DefKind ::\n    AssocConst)', compiler/rustc_middle/src/ty/sty.rs:1180:9
stack backtrace:
   0:     0x7f1345233ed5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h991b55da1e83b112
   1:     0x7f13452a3ac8 - core::fmt::write::h3c3d382678756bc2
   2:     0x7f1345225be1 - std::io::Write::write_fmt::hc19b14f8abaf5dce
   3:     0x7f1345233ce1 - std::sys_common::backtrace::print::h73b77c087d488751
   4:     0x7f1345237024 - std::panicking::default_hook::{{closure}}::h9653e6dd75fed7e6
   5:     0x7f1345236cea - std::panicking::default_hook::h3340624c2eb9f3ad
   6:     0x7f1345c7c2d4 - rustc_driver[7326d70ea4e13ad2]::DEFAULT_HOOK::{closure#0}::{closure#0}
   7:     0x7f1345237794 - std::panicking::rust_panic_with_hook::hc59c70e64ca7a24d
   8:     0x7f13452374ba - std::panicking::begin_panic_handler::{{closure}}::h0332451da9847254
   9:     0x7f13452343f4 - std::sys_common::backtrace::__rust_end_short_backtrace::hc7e5242ae85d9405
  10:     0x7f13452371a2 - rust_begin_unwind
  11:     0x7f13451e7ff3 - core::panicking::panic_fmt::ha93918a6663c82a5
  12:     0x7f13451e80cd - core::panicking::panic::h4408147c1050727f
  13:     0x7f1348a91c2e - <rustc_middle[b3ae27b7ab26a79d]::ty::sty::AliasTy>::trait_ref
  14:     0x7f1348705538 - rustc_trait_selection[845b29883bdf4b74]::traits::project::normalize_to_error
  15:     0x7f1348714561 - rustc_trait_selection[845b29883bdf4b74]::traits::project::opt_normalize_projection_type
  16:     0x7f134870b8f6 - rustc_trait_selection[845b29883bdf4b74]::traits::project::project_and_unify_type
  17:     0x7f13485545d0 - <rustc_infer[3374bd96f5bab0b6]::infer::InferCtxt>::commit_if_ok::<rustc_trait_selection[845b29883bdf4b74]::traits::project::ProjectAndUnifyResult, rustc_infer[3374bd96f5bab0b6]::traits::project::MismatchedProjectionTypes, rustc_trait_selection[845b29883bdf4b74]::traits::project::poly_project_and_unify_type::{closure#0}>
  18:     0x7f134870b466 - rustc_trait_selection[845b29883bdf4b74]::traits::project::poly_project_and_unify_type
  19:     0x7f13486cf118 - <rustc_trait_selection[845b29883bdf4b74]::traits::fulfill::FulfillProcessor>::process_projection_obligation
  20:     0x7f13486d4712 - <rustc_trait_selection[845b29883bdf4b74]::traits::fulfill::FulfillProcessor as rustc_data_structures[507443cea05b7bb9]::obligation_forest::ObligationProcessor>::process_obligation
  21:     0x7f13485c752c - <rustc_data_structures[507443cea05b7bb9]::obligation_forest::ObligationForest<rustc_trait_selection[845b29883bdf4b74]::traits::fulfill::PendingPredicateObligation>>::process_obligations::<rustc_trait_selection[845b29883bdf4b74]::traits::fulfill::FulfillProcessor>
  22:     0x7f13486ce8d7 - <rustc_trait_selection[845b29883bdf4b74]::traits::fulfill::FulfillmentContext as rustc_infer[3374bd96f5bab0b6]::traits::engine::TraitEngine>::select_where_possible
  23:     0x7f134619a9b5 - <rustc_hir_typeck[c4b36bdbc3c5ca0d]::fn_ctxt::FnCtxt>::check_argument_types
  24:     0x7f134616d235 - <rustc_hir_typeck[c4b36bdbc3c5ca0d]::fn_ctxt::FnCtxt>::confirm_builtin_call
  25:     0x7f134616a72f - <rustc_hir_typeck[c4b36bdbc3c5ca0d]::fn_ctxt::FnCtxt>::check_call
  26:     0x7f13461ed472 - <rustc_hir_typeck[c4b36bdbc3c5ca0d]::fn_ctxt::FnCtxt>::check_expr_kind
  27:     0x7f13461811d1 - <rustc_hir_typeck[c4b36bdbc3c5ca0d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  28:     0x7f13461ec342 - <rustc_hir_typeck[c4b36bdbc3c5ca0d]::fn_ctxt::FnCtxt>::check_expr_with_expectation
  29:     0x7f13461a29f6 - <rustc_hir_typeck[c4b36bdbc3c5ca0d]::fn_ctxt::FnCtxt>::check_block_with_expected
  30:     0x7f13461ed61d - <rustc_hir_typeck[c4b36bdbc3c5ca0d]::fn_ctxt::FnCtxt>::check_expr_kind
  31:     0x7f13461811d1 - <rustc_hir_typeck[c4b36bdbc3c5ca0d]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  32:     0x7f13461ec342 - <rustc_hir_typeck[c4b36bdbc3c5ca0d]::fn_ctxt::FnCtxt>::check_expr_with_expectation
  33:     0x7f1346182a8b - <rustc_hir_typeck[c4b36bdbc3c5ca0d]::fn_ctxt::FnCtxt>::check_return_expr
  34:     0x7f13462fcf84 - rustc_hir_typeck[c4b36bdbc3c5ca0d]::check::check_fn
  35:     0x7f13462d2e8d - rustc_hir_typeck[c4b36bdbc3c5ca0d]::typeck
  36:     0x7f1347a909f9 - rustc_query_system[7fa521f5ca1ea01c]::query::plumbing::try_execute_query::<rustc_query_impl[fdc87dbd73208a35]::plumbing::QueryCtxt, rustc_query_system[7fa521f5ca1ea01c]::query::caches::VecCache<rustc_span[8688867482b25c8b]::def_id::LocalDefId, &rustc_middle[b3ae27b7ab26a79d]::ty::context::TypeckResults>>
  37:     0x7f1347b7cc86 - rustc_query_system[7fa521f5ca1ea01c]::query::plumbing::get_query::<rustc_query_impl[fdc87dbd73208a35]::queries::typeck, rustc_query_impl[fdc87dbd73208a35]::plumbing::QueryCtxt>
  38:     0x7f134774ee80 - <rustc_query_impl[fdc87dbd73208a35]::Queries as rustc_middle[b3ae27b7ab26a79d]::ty::query::QueryEngine>::typeck
  39:     0x7f1348a2efc0 - <rustc_middle[b3ae27b7ab26a79d]::ty::context::TyCtxt>::typeck_opt_const_arg
  40:     0x7f1346e1de80 - rustc_mir_build[bdf718eeeeaf3718]::thir::cx::thir_body
  41:     0x7f1347b80a7a - rustc_query_system[7fa521f5ca1ea01c]::query::plumbing::get_query::<rustc_query_impl[fdc87dbd73208a35]::queries::thir_body, rustc_query_impl[fdc87dbd73208a35]::plumbing::QueryCtxt>
  42:     0x7f134772cd46 - <rustc_query_impl[fdc87dbd73208a35]::Queries as rustc_middle[b3ae27b7ab26a79d]::ty::query::QueryEngine>::thir_body
  43:     0x7f1346d9aa75 - rustc_mir_build[bdf718eeeeaf3718]::build::mir_built
  44:     0x7f1347a312e8 - rustc_query_system[7fa521f5ca1ea01c]::query::plumbing::try_execute_query::<rustc_query_impl[fdc87dbd73208a35]::plumbing::QueryCtxt, rustc_query_system[7fa521f5ca1ea01c]::query::caches::DefaultCache<rustc_middle[b3ae27b7ab26a79d]::ty::WithOptConstParam<rustc_span[8688867482b25c8b]::def_id::LocalDefId>, &rustc_data_structures[507443cea05b7bb9]::steal::Steal<rustc_middle[b3ae27b7ab26a79d]::mir::Body>>>
  45:     0x7f1347b7ef7c - rustc_query_system[7fa521f5ca1ea01c]::query::plumbing::get_query::<rustc_query_impl[fdc87dbd73208a35]::queries::mir_built, rustc_query_impl[fdc87dbd73208a35]::plumbing::QueryCtxt>
  46:     0x7f134772f2c4 - <rustc_query_impl[fdc87dbd73208a35]::Queries as rustc_middle[b3ae27b7ab26a79d]::ty::query::QueryEngine>::mir_built
  47:     0x7f13468f93b0 - rustc_mir_transform[221009d22664115b]::check_unsafety::unsafety_check_result
  48:     0x7f13468f4d60 - <rustc_mir_transform[221009d22664115b]::check_unsafety::provide::{closure#0} as core[85c1accd9c5665a0]::ops::function::FnOnce<(rustc_middle[b3ae27b7ab26a79d]::ty::context::TyCtxt, rustc_span[8688867482b25c8 [...]

2022-11-27 21:04 UTC, cjgillot reviewed
I wonder what are the next steps. Can this be used to integrate in-trait opaques as a variant of `AliasKind`?

2022-11-28 14:58 UTC, compiler-errors commented on compiler/rustc_traits/src/chalk/lowering.rs
>          chalk_ir::AliasTy::Projection(chalk_ir::ProjectionTy {
Good point. I'll remove this impl.

2022-12-06 03:38 UTC, compiler-errors commented
I think this is ready

r? types

2022-12-06 05:14 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3626247331/jobs/6115062029) [(plain)](https://github.com/rust-lang/rust/commit/c0ab50ee86e92c97e2eee00a12da98aea15ebdee/checks/9906188383/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

---- [ui] src/test/ui-fulldeps/internal-lints/ty_tykind_usage.rs stdout ----
diff of stderr:

- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:13:16
+ error[E0599]: no variant or associated item named `Projection` found for enum `TyKind` in the current scope
+   --> $DIR/ty_tykind_usage.rs:36:17
- LL |     let kind = TyKind::Bool;
- LL |     let kind = TyKind::Bool;
-    |                ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- note: the lint level is defined here
-   --> $DIR/ty_tykind_usage.rs:11:8
-    |
-    |
- LL | #[deny(rustc::usage_of_ty_tykind)]
- 
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:16:9
-    |
- LL |         TyKind::Bool => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:17:9
-    |
- LL |         TyKind::Char => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:18:9
-    |
- LL |         TyKind::Int(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:19:9
-    |
- LL |         TyKind::Uint(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:20:9
-    |
- LL |         TyKind::Float(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:21:9
-    |
- LL |         TyKind::Adt(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:22:9
-    |
- LL |         TyKind::Foreign(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:23:9
-    |
- LL |         TyKind::Str => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:24:9
-    |
- LL |         TyKind::Array(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:25:9
-    |
- LL |         TyKind::Slice(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:26:9
-    |
- LL |         TyKind::RawPtr(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:27:9
-    |
- LL |         TyKind::Ref(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:28:9
-    |
- LL |         TyKind::FnDef(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:29:9
-    |
- LL |         TyKind::FnPtr(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:30:9
-    |
- LL |         TyKind::Dynamic(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:31:9
-    |
- LL |         TyKind::Closure(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:32:9
-    |
- LL |         TyKind::Generator(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:33:9
-    |
- LL |         TyKind::GeneratorWitness(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:34:9
-    |
- LL |         TyKind::Never => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:35:9
-    |
- LL |         TyKind::Tuple(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:36:9
-    |
136 LL |         TyKind::Projection(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
+    |                 ^^^^^^^^^^ variant or associated item not found in `TyKind<TyCtxt<'_>>`
138 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:37:9
+ error[E0599]: no variant or associated item named `Opaque` found for enum `TyKind` in the current scope
+   --> $DIR/ty_tykind_usage.rs:37:17
141    |
142 LL |         TyKind::Opaque(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
+    |                 ^^^^^^ variant or associated item not found in `TyKind<TyCtxt<'_>>`
144 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:38:9
-    |
- LL |         TyKind::Param(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
+ error: aborting due to 2 previous errors
150 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:39:9
-    |
- LL |         TyKind::Bound(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:40:9
-    |
- LL |         TyKind::Placeholder(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:41:9
-    |
- LL |         TyKind::Infer(..) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:42:9
-    |
- LL |         TyKind::Error(_) => (),
-    |         ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:47:12
-    |
- LL |     if let TyKind::Int(int_ty) = kind {}
-    |            ^^^^^^ help: try using `ty::<kind>` directly: `ty`
- error: usage of `ty::TyKind`
-   --> $DIR/ty_tykind_usage.rs:49:24
-    |
-    |
- LL |     fn ty_kind(ty_bad: TyKind<'_>, ty_good: Ty<'_>) {}
-    |
-    = help: try using `Ty` instead
- 
- error: usage of `ty::TyKind`
- error: usage of `ty::TyKind`
-   --> $DIR/ty_tykind_usage.rs:51:37
-    |
- LL |     fn ir_ty_kind<I: Interner>(bad: IrTyKind<I>) -> IrTyKind<I> {
-    |
-    = help: try using `Ty` instead
- 
- error: usage of `ty::TyKind`
- error: usage of `ty::TyKind`
-   --> $DIR/ty_tykind_usage.rs:51:53
-    |
- LL |     fn ir_ty_kind<I: Interner>(bad: IrTyKind<I>) -> IrTyKind<I> {
-    |
-    = help: try using `Ty` instead
- 
- 
- error: usage of `ty::TyKind::<kind>`
-   --> $DIR/ty_tykind_usage.rs:54:9
-    |
- LL |         IrTyKind::Bool
-    |         |
-    |         |
-    |         help: try using `ty::<kind>` directly: `ty`
- error: aborting due to 33 previous errors
- 
+ For more information about this error, try `rustc --explain E0599`.
215 
---
To only update this specific test, also pass `--test-args internal-lints/ty_tykind_usage.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui-fulldep [...]

2022-12-13 15:31 UTC, oli-obk requested changes
r=me with some nits and a clean perf run

2022-12-13 15:31 UTC, oli-obk commented on compiler/rustc_hir_analysis/src/check/mod.rs
> +        where_clauses.push(format!("{} = {}", tcx.def_path_str(p.projection_ty.def_id), p.term,));
```suggestion
        where_clauses.push(format!("{} = {}", tcx.def_path_str(p.projection_ty.def_id), p.term));
```

2022-12-13 15:31 UTC, oli-obk commented on compiler/rustc_middle/src/ty/fast_reject.rs
> +        ty::Alias(ty::Opaque, ..) | ty::Alias(ty::Projection, _) => match treat_params {
```suggestion
        ty::Alias(..) => match treat_params {
```

2022-12-13 15:31 UTC, oli-obk commented on compiler/rustc_middle/src/ty/fast_reject.rs
> +            | ty::Alias(ty::Opaque, ..) => return true,
```suggestion
            | ty::Error(_)
            | ty::Alias(..) => return true,
```

2022-12-13 15:31 UTC, oli-obk commented on compiler/rustc_middle/src/ty/fast_reject.rs
> +            ty::Alias(ty::Projection, _) => true,
```suggestion
            ty::Alias(..) => true,
```

2022-12-13 15:31 UTC, oli-obk commented on compiler/rustc_middle/src/ty/fast_reject.rs
> +            ty::Alias(ty::Opaque, ..) => true,
```suggestion
```

2022-12-13 15:31 UTC, oli-obk commented on compiler/rustc_trait_selection/src/traits/project.rs
> +        }
```suggestion
        ty::Alias(_, ref data) => {
            tcx.bound_item_bounds(data.def_id).subst(tcx, data.substs)
        }
```

2022-12-13 15:31 UTC, oli-obk commented
@bors p=1 bitrotty

2022-12-13 17:58 UTC, compiler-errors commented
@bors try @rust-timer queue

2022-12-13 18:01 UTC, compiler-errors commented
bors is sleeping :zzz:

2022-12-13 18:03 UTC, compiler-errors commented
@bors try @rust-timer queue

2022-12-13 18:03 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2022-12-13 18:06 UTC, compiler-errors commented
@bors ping

2022-12-13 18:06 UTC, compiler-errors commented
@bors try

2022-12-13 18:46 UTC, compiler-errors commented
@bors try

2022-12-13 18:47 UTC, compiler-errors commented
:facepalm: github status page doesn't show anything wrong anymore, ugh.

2022-12-13 21:31 UTC, rust-timer commented
Queued ad35b8e377db9f8fa1364750ed99d283bc52b2f2 with parent aa5b179599427ef233c4e47db8dac6edae22b4f8, future [comparison URL](https://perf.rust-lang.org/compare.html?start=aa5b179599427ef233c4e47db8dac6edae22b4f8&end=ad35b8e377db9f8fa1364750ed99d283bc52b2f2).
<!-- rust-timer: temporary -->

2022-12-13 22:50 UTC, rust-timer commented
Finished benchmarking commit (ad35b8e377db9f8fa1364750ed99d283bc52b2f2): [comparison URL](https://perf.rust-lang.org/compare.html?start=aa5b179599427ef233c4e47db8dac6edae22b4f8&end=ad35b8e377db9f8fa1364750ed99d283bc52b2f2&stat=instructions:u).

### Overall result: ❌ regressions - ACTION NEEDED


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: -S-waiting-on-perf +perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=aa5b179599427ef233c4e47db8dac6edae22b4f8&end=ad35b8e377db9f8fa1364750ed99d283bc52b2f2&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.1% | [1.0%, 1.1%] | 2     |
| Regressions ❌ <br /> (secondary)  | 2.1% | [0.9%, 2.7%] | 7     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 1.1% | [1.0%, 1.1%] | 2     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=aa5b179599427ef233c4e47db8dac6edae22b4f8&end=ad35b8e377db9f8fa1364750ed99d283bc52b2f2&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -2.2% | [-2.2%, -2.2%] | 1     |
| All ❌✅ (primary)                 | -     | -              | 0     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=aa5b179599427ef233c4e47db8dac6edae22b4f8&end=ad35b8e377db9f8fa1364750ed99d283bc52b2f2&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

2022-12-13 22:53 UTC, compiler-errors commented
This looks like the same exact noisy crates that we saw in https://github.com/rust-lang/rust/pull/105350#issuecomment-1348348616

2022-12-13 23:37 UTC, oli-obk commented
@bors r+

2022-12-14 04:00 UTC, merged

2022-12-14 05:18 UTC, rust-timer commented
Finished benchmarking commit (918d0ac38e8c3bcf4fb5ee2241fb14979c73c312): [comparison URL](https://perf.rust-lang.org/compare.html?start=21ee03e0621c70b894e1bfdd8c82ba5aeaabc812&end=918d0ac38e8c3bcf4fb5ee2241fb14979c73c312&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=21ee03e0621c70b894e1bfdd8c82ba5aeaabc812&end=918d0ac38e8c3bcf4fb5ee2241fb14979c73c312&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=21ee03e0621c70b894e1bfdd8c82ba5aeaabc812&end=918d0ac38e8c3bcf4fb5ee2241fb14979c73c312&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 3.6% | [3.3%, 3.9%] | 2     |
| Regressions ❌ <br /> (secondary)  | 1.6% | [1.6%, 1.6%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 3.6% | [3.3%, 3.9%] | 2     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=21ee03e0621c70b894e1bfdd8c82ba5aeaabc812&end=918d0ac38e8c3bcf4fb5ee2241fb14979c73c312&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.