Make `tcx.mk_const` more permissive wrt `kind` argument (`impl Into`)
rust-lang/rust pull request #105012
Opened 2022-11-28 12:41 UTC by WaffleLapkin

r? @oli-obk you've asked for this >:)

2022-11-28 12:58 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/3564858963/jobs/5989320672) [(plain)](https://github.com/rust-lang/rust/commit/45e0b9c98b097fe71a724b810d0a226c2e6417d3/checks/9744381978/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
Attempting with retry: make prepare
---
* highest error code: E0790
Found 506 error codes
Found 0 error(s) in error codes
Done!
tidy error: Dependencies for rustc not explicitly permitted:
* convert_case 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)
* derive_more 0.99.17 (registry+https://github.com/rust-lang/crates.io-index)
some tidy checks failed
Build completed unsuccessfully in 0:00:13
```

</details>

2022-11-28 14:05 UTC, oli-obk requested changes

2022-11-28 14:05 UTC, oli-obk commented on compiler/rustc_middle/src/ty/consts.rs
>      }
this method could also become redundant with an appropriate From impl

2022-11-28 17:50 UTC, oli-obk commented
@bors try @rust-timer queue

2022-11-28 17:50 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2022-11-28 17:51 UTC, oli-obk commented
@bors delegate+

r=me with perf clean and the review comment addressed

2022-11-28 17:51 UTC, oli-obk commented
@bors p=1 bitrotty

2022-11-28 22:50 UTC, oli-obk commented
@rust-timer build 82877d5eeacaaf632388af232976d23d529ca7c2

2022-11-28 22:50 UTC, rust-timer commented
Queued 82877d5eeacaaf632388af232976d23d529ca7c2 with parent 8a09420ac48658cad726e0a6997687ceac4151e3, future [comparison URL](https://perf.rust-lang.org/compare.html?start=8a09420ac48658cad726e0a6997687ceac4151e3&end=82877d5eeacaaf632388af232976d23d529ca7c2).
<!-- rust-timer: temporary -->

2022-11-29 09:34 UTC, rust-timer commented
Finished benchmarking commit (82877d5eeacaaf632388af232976d23d529ca7c2): [comparison URL](https://perf.rust-lang.org/compare.html?start=8a09420ac48658cad726e0a6997687ceac4151e3&end=82877d5eeacaaf632388af232976d23d529ca7c2&stat=instructions:u).

### Overall result: ❌ regressions - no action needed


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf -perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=8a09420ac48658cad726e0a6997687ceac4151e3&end=82877d5eeacaaf632388af232976d23d529ca7c2&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 0.9% | [0.8%, 1.0%] | 6     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=8a09420ac48658cad726e0a6997687ceac4151e3&end=82877d5eeacaaf632388af232976d23d529ca7c2&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | 6.2%  | [5.0%, 7.4%]   | 2     |
| Improvements ✅ <br /> (primary)   | -2.7% | [-2.7%, -2.7%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -2.7% | [-2.7%, -2.7%] | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=8a09420ac48658cad726e0a6997687ceac4151e3&end=82877d5eeacaaf632388af232976d23d529ca7c2&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 2.5% | [2.5%, 2.5%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

2022-11-29 10:18 UTC, WaffleLapkin commented
> regressions
> no action needed

??

Also, the regression itself looks super weird...

2022-11-29 10:28 UTC, oli-obk commented
```
--------------------------------------------------------------------------------
Ir        
--------------------------------------------------------------------------------
6,087,305  PROGRAM TOTALS

--------------------------------------------------------------------------------
Ir          file:function
--------------------------------------------------------------------------------
-2,098,831  ???:<rustc_mir_build::build::Builder>::match_candidates
 2,020,333  ???:<rustc_mir_build::build::Builder>::simplify_candidate
-1,926,791  ???:<rustc_hir_typeck::fn_ctxt::FnCtxt>::require_type_is_sized
 1,720,536  ???:<rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::register_bound
 1,490,315  ???:<rustc_mir_build::build::expr::as_place::PlaceBuilder>::field
 1,231,992  ???:<rustc_mir_build::build::expr::as_place::PlaceBuilder>::try_to_place
  -682,829  ???:<alloc::vec::Vec<rustc_middle::mir::syntax::ProjectionElem<rustc_middle::mir::Local, rustc_middle::ty::Ty>> as alloc::vec::spec_from_iter::SpecFromIter<rustc_middle::mir::syntax::ProjectionElem<rustc_middle::mir::Local, rustc_middle::ty::Ty>, core::iter::adapters::chain::Chain<core::iter::adapters::copied::Copied<core::slice::iter::Iter<rustc_middle::mir::syntax::ProjectionElem<rustc_middle::mir::Local, rustc_middle::ty::Ty>>>, core::array::iter::IntoIter<rustc_middle::mir::syntax::ProjectionElem<rustc_middle::mir::Local, rustc_middle::ty::Ty>, 1>>>>::from_iter
  -659,276  ???:rustc_mir_dataflow::drop_flag_effects::on_all_children_bits::is_terminal_path
   553,290  ???:do_rallocx
   529,097  ???:_rjem_je_arena_ralloc
   501,018  ???:<rustc_middle::ty::FieldDef>::ty
   476,288  ???:<alloc::raw_vec::RawVec<rustc_middle::mir::syntax::ProjectionElem<rustc_middle::mir::Local, rustc_middle::ty::Ty, rustc_middle::ty::Ty>>>::reserve_for_push
   375,478  ???:<rustc_middle::ty::subst::SubstFolder as rustc_middle::ty::fold::FallibleTypeFolder>::try_fold_ty
   353,556  ???:_rjem_je_arena_ralloc_no_move
```

I... have no idea ^^ I remember seeing `field` and `try_to_place` in other regressions on html5ever, so it's likely inliner noise.

2022-11-29 10:34 UTC, oli-obk commented
@bors r+ looking at the graph of the wg-grammar benchmark this seems to be within the regular ups and downs of that benchmark

2022-11-29 16:26 UTC, merged

2022-11-30 00:23 UTC, rust-timer commented
Finished benchmarking commit (e0098a5cc3a87d857e597af824d0ce1ed1ad85e0): [comparison URL](https://perf.rust-lang.org/compare.html?start=c372b1470109547e37dcc29ffd4723ac9f66f15d&end=e0098a5cc3a87d857e597af824d0ce1ed1ad85e0&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=c372b1470109547e37dcc29ffd4723ac9f66f15d&end=e0098a5cc3a87d857e597af824d0ce1ed1ad85e0&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=c372b1470109547e37dcc29ffd4723ac9f66f15d&end=e0098a5cc3a87d857e597af824d0ce1ed1ad85e0&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -1.7% | [-2.8%, -0.6%] | 2     |
| Improvements ✅ <br /> (secondary) | -3.4% | [-3.4%, -3.4%] | 1     |
| All ❌✅ (primary)                 | -1.7% | [-2.8%, -0.6%] | 2     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=c372b1470109547e37dcc29ffd4723ac9f66f15d&end=e0098a5cc3a87d857e597af824d0ce1ed1ad85e0&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 9.0%  | [9.0%, 9.0%]   | 1     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -2.4% | [-2.4%, -2.4%] | 1     |
| All ❌✅ (primary)                 | 9.0%  | [9.0%, 9.0%]   | 1     |
</details>