Test the borrowck behavior of if-let guards
rust-lang/rust pull request #106005
Opened 2022-12-21 15:48 UTC by LeSeulArtichaut

Add some tests to make sure that if-let guards behave the same as if guards with respect to borrow-checking. Most of them are a naive adaptation, replacing an `if` guard with `if let Some(())`.
This includes regression tests for notable issues that arose for if guards (#24535, #27282, #29723, #31287) as suggested in https://github.com/rust-lang/rust/issues/51114#issuecomment-900470419.

cc @pnkfelix are there any other tests that you would want to see?
cc tracking issue #51114

2022-12-21 17:11 UTC, Noratrieb requested changes
Thanks, adding so many tests is great! Looks mostly good except for one place where you forgot to change it.

r=me after fixing that unless Felix wants to add another test or something changed

2022-12-21 17:11 UTC, Nilstrieb commented on src/test/ui/nll/issue-27282-move-match-input-into-guard.rs
> +        _ if { (|| { let bar = b; *bar = false; })();
You forgot to make it a let guard here

2022-12-21 18:26 UTC, LeSeulArtichaut commented
Fixed, thank you very much for the review!

2023-01-03 11:00 UTC, Nilstrieb commented
@bors r+ rollup

2023-01-03 11:01 UTC, Nilstrieb approved these changes

2023-01-03 20:22 UTC, merged