[drop tracking] Visit break expressions
rust-lang/rust pull request #106699
Opened 2023-01-11 01:02 UTC by eholk

This fixes https://github.com/rust-lang/rust/issues/102383 by remembering to visit the expression in `break expr` when building the drop tracking CFG. Missing this step was causing an off-by-one error which meant after a number of awaits we'd be
looking for dropped values at the wrong point in the code.

Additionally, this changes the order of traversal for assignment expressions to visit the rhs and then the lhs. This matches what is done elsewhere.

Finally, this improves some of the debugging output (for example, the CFG visualizer) to make it easier to figure out these sorts of issues.

2023-01-12 17:50 UTC, vincenzopalazzo approved these changes

2023-01-12 18:01 UTC, albertlarsan68 requested changes
Tests have moved from `src/test` to `tests`, please [rebase](https://rustc-dev-guide.rust-lang.org/git.html#rebasing) on top of new `master`.
@rustbot author

2023-01-12 20:16 UTC, eholk commented
> Tests have moved from `src/test` to `tests`, please [rebase](https://rustc-dev-guide.rust-lang.org/git.html#rebasing) on top of new `master`. @rustbot author

Nice to see that change happen! I updated this PR.

2023-01-19 21:50 UTC, wesleywiser approved these changes

2023-01-19 21:50 UTC, wesleywiser commented on compiler/rustc_hir_typeck/src/generator_interior/drop_ranges/cfg_build.rs
> +                self.visit_expr(lhs);
This matches the behavior described in the Rust Reference for assignment expressions (https://doc.rust-lang.org/reference/expressions/operator-expr.html#basic-assignments) 👍

2023-01-19 21:51 UTC, wesleywiser commented
Thanks @eholk; this looks good to me!

@bors r+ rollup

2023-01-20 18:25 UTC, merged