allow negative numeric literals in `concat!`
rust-lang/rust pull request #106844
Opened 2023-01-14 10:03 UTC by Ezrashaw

Fixes #106837

While *technically* negative numeric literals are implemented as unary operations, users can reasonably expect that negative literals are treated the same as positive literals.

2023-01-14 21:11 UTC, compiler-errors commented
The implementation looks fine, but given that this is technically a standard library macro, I think this needs @rust-lang/libs-api weigh-in too.

2023-01-14 21:26 UTC, dtolnay requested changes
Something is screwed up in the following case:

```rust
macro_rules! negative {
    ($literal:literal) => {
        concat!(-$literal)
    };
}

fn main() {
    let string = negative!(1);
    println!("{:?}, {}", string, string.len());

    let string = negative!(-1);
    println!("{:?}, {}", string, string.len());
}
```

```console
"-1", 2
"", 0
```

2023-01-14 23:52 UTC, Ezrashaw commented
@dtolnay Fixed, this issue also occurred for the general case `concat!(--1)`. I've also added this to the UI test.

We're looking for `UnaryOp::Negation(IntegerLiteral)` (which is effectively a negative integer literal). I wasn't correctly handling `UnaryOp::Negation(SomeOtherExpression)` properly.

2023-01-15 00:57 UTC, dtolnay commented
@rfcbot fcp merge

2023-03-03 23:03 UTC, AaronKutch commented
What would be the interaction with `concat!` if https://github.com/rust-lang/rust/issues/108385 were to be fixed? Would only literals supported by normal Rust still work?

2023-03-04 03:02 UTC, Ezrashaw commented
@AaronKutch I'm definitely not an expert with this part of the compiler (I just fixed the bug), so take this with a grain of salt:

Only valid literals are/will be allowed, `concat!` is effectively a proc-macro implemented by the compiler (with the compiler's own unstable interfaces which are different from the stable `proc_macro` crate). This PR doesn't touch the lexer or literal validation at all; it just expands, and fixes a bug, with the input tokens that are allowed.

@dtolnay Maybe you could add on to this? Thanks!

2023-03-04 03:15 UTC, dtolnay commented
Yeah I don't immediately see how that issue is relevant to this PR.

2023-03-10 19:27 UTC, dtolnay approved these changes

2023-03-10 19:27 UTC, dtolnay commented
@bors r+

2023-03-10 20:09 UTC, compiler-errors commented
@Ezrashaw was closing this PR intentional?

2023-03-10 20:10 UTC, Ezrashaw commented
No, <insert swear word here>. Can I reopen it safely?

2023-03-10 20:11 UTC, compiler-errors commented
Yes, though you deleted the branch, so you may need to open a new PR.

2023-03-10 20:11 UTC, Ezrashaw commented
Fingers crossed. It's ok?

2023-03-10 20:11 UTC, compiler-errors commented
@bors r=dtolnay

2023-03-10 20:12 UTC, Ezrashaw commented
Brilliant, thanks for the help.

2023-03-11 21:12 UTC, merged