Preprocess dominator tree to answer queries in O(1)
rust-lang/rust pull request #107157
Opened 2023-01-21 13:22 UTC by tmiasko

r? @ghost

2023-01-22 00:04 UTC, tmiasko commented
@bors try @rust-timer queue

2023-01-22 00:04 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2023-01-22 02:49 UTC, rust-timer commented
Queued 9c8bbf49ba0cc73e86c499b73a28c0b60b2af24c with parent 52372f9c71d8ade4cb815524f179119656f0aa2e, future [comparison URL](https://perf.rust-lang.org/compare.html?start=52372f9c71d8ade4cb815524f179119656f0aa2e&end=9c8bbf49ba0cc73e86c499b73a28c0b60b2af24c).
<!-- rust-timer: temporary -->

2023-01-22 04:38 UTC, rust-timer commented
Finished benchmarking commit (9c8bbf49ba0cc73e86c499b73a28c0b60b2af24c): [comparison URL](https://perf.rust-lang.org/compare.html?start=52372f9c71d8ade4cb815524f179119656f0aa2e&end=9c8bbf49ba0cc73e86c499b73a28c0b60b2af24c&stat=instructions:u).

### Overall result: ❌ regressions - ACTION NEEDED


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: -S-waiting-on-perf +perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=52372f9c71d8ade4cb815524f179119656f0aa2e&end=9c8bbf49ba0cc73e86c499b73a28c0b60b2af24c&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.2% | [0.2%, 0.3%] | 2     |
| Regressions ❌ <br /> (secondary)  | 0.5% | [0.2%, 0.8%] | 4     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 0.2% | [0.2%, 0.3%] | 2     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=52372f9c71d8ade4cb815524f179119656f0aa2e&end=9c8bbf49ba0cc73e86c499b73a28c0b60b2af24c&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 2.4% | [2.4%, 2.4%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=52372f9c71d8ade4cb815524f179119656f0aa2e&end=9c8bbf49ba0cc73e86c499b73a28c0b60b2af24c&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.3% | [0.7%, 1.8%] | 14    |
| Regressions ❌ <br /> (secondary)  | 2.9% | [1.8%, 3.9%] | 18    |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 1.3% | [0.7%, 1.8%] | 14    |
</details>

2023-01-24 21:57 UTC, bryangarza requested changes
I'm not an official reviewer, but wanted to leave some feedback.

Just had one comment in the code itself, other than that, it'd be nice to see a unit test or two for the `dominators` function before merging.

2023-01-24 21:57 UTC, bryangarza commented on compiler/rustc_data_structures/src/graph/dominators/mod.rs
> +    let mut node = IndexVec::from_elem_n(Idx::new(0), m.try_into().unwrap());
if you make the `m` a `usize` from the start, you can avoid the `try_into().unwrap()`

2023-02-23 15:49 UTC, pnkfelix commented
@tmiasko you wrote in a separate comment: https://github.com/rust-lang/rust/pull/107449#issuecomment-1426996371

> FYI: https://github.com/rust-lang/rust/pull/107157 is intended for instrument coverage builds, where the cost of dominance queries often exceeds the cost of initial preprocessing - the opposite of a profile here, where at best it wouldn't be a regression.

I'm trying to connect that statement with the PR here.

Is the preprocessing done here supposed to be conditionally enabled? I haven't yet seen that in this PR, but I only did a quick skim so maybe I overlooked it.

2023-02-24 23:37 UTC, tmiasko commented
> Is the preprocessing done here supposed to be conditionally enabled?

The extra cost seems negligible, so it can be unconditional (one can't quite tell from last perf results alone, since the measurement is biased by a regression in obligation processing, which has unstable codegen for some reason).

This pull request isn't quite ready for review (hence no assigned reviewer). I also wanted to add a new benchmark that demonstrates perf aspect addressed here first.

Closing for now, maybe will return to this later.

2023-02-24 23:37 UTC, closed without merging