Add `clone_from` specializations to `Rc` and `Arc`
rust-lang/rust pull request #107395
Opened 2023-01-28 01:24 UTC by Lucretiel

Add specializations for `clone_from` to `Rc` and `Arc`. These check to see if the pointers already share ownership of the same object and, if so, don't do any additional work.

2023-01-28 03:00 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/4029491506/jobs/6927432142) [(plain)](https://github.com/rust-lang/rust/commit/181799e83468932041ae2dff4d5eddc3b5ca6b32/checks/10942696350/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:ac593985615ec2ede58e132d2e21d2b1cbd6127c)
Download action repository 'rust-lang/simpleinfra@master' (SHA:ece894d15649f0f9d7884f915dc821f00bd0418b)
Complete job name: PR (x86_64-gnu-llvm-13, false, ubuntu-20.04-xl)
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  CI_JOB_NAME: x86_64-gnu-llvm-13
---
   Compiling rustc-demangle v0.1.21
error[E0425]: cannot find value `other` in this scope
    --> library/alloc/src/rc.rs:1635:24
     |
1635 |         if self.ptr != other.ptr {

error[E0425]: cannot find value `other` in this scope
    --> library/alloc/src/rc.rs:2575:24
     |
     |
2575 |         if self.ptr != other.ptr {

error[E0425]: cannot find value `other` in this scope
    --> library/alloc/src/sync.rs:1533:24
     |
     |
1533 |         if self.ptr != other.ptr {

error[E0425]: cannot find value `other` in this scope
    --> library/alloc/src/sync.rs:2347:24
     |
     |
2347 |         if self.ptr != other.ptr {

For more information about this error, try `rustc --explain E0425`.
error: could not compile `alloc` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
```

</details>

2023-01-28 06:21 UTC, eggyal requested changes
Just a typo repeated in each implementation, but otherwise seems sensible to me.

2023-01-28 06:21 UTC, eggyal commented on library/alloc/src/rc.rs
> +        if self.ptr != other.ptr {
```suggestion
        if self.ptr != source.ptr {
```

2023-01-28 06:21 UTC, eggyal commented on library/alloc/src/rc.rs
> +        if self.ptr != other.ptr {
```suggestion
        if self.ptr != source.ptr {
```

2023-01-28 06:21 UTC, eggyal commented on library/alloc/src/sync.rs
> +        if self.ptr != other.ptr {
```suggestion
        if self.ptr != source.ptr {
```

2023-01-28 06:21 UTC, eggyal commented on library/alloc/src/sync.rs
> +        if self.ptr != other.ptr {
```suggestion
        if self.ptr != source.ptr {
```

2023-01-28 07:36 UTC, eggyal approved these changes

2023-01-30 03:43 UTC, mejrs commented
Do you have a benchmark for this?

2023-02-01 18:26 UTC, Lucretiel commented
Not yet; I can write one this weekend. Are there any existing `Arc` benchmarks I can base off of?

2023-02-02 11:33 UTC, mejrs commented
I have no idea, sorry.

2023-03-20 19:16 UTC, the8472 commented
I think there's another case we can optimize. If the refcount of `self` is exactly 1 and `T: Clone` then we can call `self.get_mut().clone_from(source)`

2023-03-21 19:33 UTC, Lucretiel commented
> I think there's another case we can optimize. If the refcount of `self` is exactly 1 and `T: Clone` then we can call `self.get_mut().clone_from(source)`

I'm not sure that's the case; `Rc::clone_from` and `Arc::clone_from` carry with them the requirement that the original object is now shares ownership with the source.

2023-03-21 19:51 UTC, the8472 commented
Ah right, but then I wonder how much this actually helps. It'll only avoid an atomic increment, in a quite narrow scenario.
Benchmarks would help but even then the question is does it occur often enough in the wild that it's worth it?

2023-08-03 11:07 UTC, Dylan-DPC commented
@Lucretiel any updates on this? thanks?

2023-10-15 08:58 UTC, Dylan-DPC commented
Closing this as inactive. Feel free to reöpen this pr or create a new pr if you get the time to work on this. Thanks

2023-10-15 08:58 UTC, closed without merging