remove the usize field from CandidateSource::AliasBound
rust-lang/rust pull request #107401
Opened 2023-01-28 04:55 UTC by lenko-d

Fixes [#107380](https://github.com/rust-lang/rust/issues/107380)

2023-01-28 05:57 UTC, eggyal requested changes

2023-01-28 05:57 UTC, eggyal commented on compiler/rustc_trait_selection/src/solve/assembly.rs
> +    AliasBound(),
Rather than a tuple variant with no fields, it'd be more idiomatic for this to be a plain field-less variant (ie omit the brackets).

2023-01-28 06:01 UTC, eggyal requested changes

2023-01-28 06:01 UTC, eggyal commented on compiler/rustc_trait_selection/src/solve/assembly.rs
>              .enumerate()
Here you can drop the `.enumerate()` in order to iterate over `(assumption, _)` without pairing the (no longer used) index to the iterator.

2023-01-28 15:04 UTC, eggyal approved these changes

2023-01-28 19:09 UTC, compiler-errors commented
r? @compiler-errors @bors r+ rollup

2023-01-29 10:20 UTC, merged

2023-01-30 08:38 UTC, lcnr commented on compiler/rustc_trait_selection/src/solve/assembly.rs
> +    AliasBound,
still referring to "the `n-th` bound in the `item_bounds`" in the doc comment