Handle discriminant in DataflowConstProp
rust-lang/rust pull request #107411
Opened 2023-01-28 11:31 UTC by cjgillot

cc @jachris 
r? @JakobDegen 

This PR attempts to extend the DataflowConstProp pass to handle propagation of discriminants. We handle this by adding 2 new variants to `TrackElem`: `TrackElem::Variant` for enum variants and `TrackElem::Discriminant` for the enum discriminant pseudo-place.

The difficulty is that the enum discriminant and enum variants may alias each another. This is the issue of the `Option<NonZeroUsize>` test, which is the equivalent of https://github.com/rust-lang/unsafe-code-guidelines/issues/84 with a direct write.

To handle that, we generalize the flood process to flood all the potentially aliasing places. In particular:
- any write to `(PLACE as Variant)`, either direct or through a projection, floods `(PLACE as OtherVariant)` for all other variants and `discriminant(PLACE)`;
- `SetDiscriminant(PLACE)` floods `(PLACE as Variant)` for each variant.

This implies that flooding is not hierarchical any more, and that an assignment to a non-tracked place may need to flood a tracked place. This is handled by `for_each_aliasing_place` which generalizes `preorder_invoke`.

As we deaggregate enums by putting `SetDiscriminant` last, this allows to propagate the value of the discriminant.

This refactor will allow to make https://github.com/rust-lang/rust/pull/107009 able to handle discriminants too.

2023-01-28 14:58 UTC, cjgillot commented
r? wg-mir-opt

2023-01-28 16:15 UTC, jachris reviewed
Nice! Great to have propagation of discriminants and through downcasts back again. It seems to me like this here should be sound. And limiting the tracking when creating the map is a much better fallback than what we currently have.

There is now quite some duplication due to all the `_discr` methods, perhaps there is a nice way to unify this.

2023-01-29 22:12 UTC, cjgillot commented on compiler/rustc_mir_dataflow/src/value_analysis.rs
> +    ) {
We need to exit early if `place` is indirect.

2023-01-29 22:14 UTC, cjgillot commented on compiler/rustc_mir_dataflow/src/value_analysis.rs
> +        for elem in elems {
We need to call `f(index)` at each step of the loop, since a field always alias a part of the containing aggregate.

2023-02-01 21:13 UTC, cjgillot commented on compiler/rustc_mir_dataflow/src/value_analysis.rs
> +    /// The target place must have been flooded before calling this method.
Do you have a suggestion for the name? I'm a bit out of inspiration.

2023-02-01 21:25 UTC, jachris commented on compiler/rustc_mir_dataflow/src/value_analysis.rs
> +    /// The target place must have been flooded before calling this method.
Maybe something like `assign_idx_without_flood`. I think a long name is fine, as this is also a dangerous function to call. This also makes it obvious that DataflowConstProp has to flood before using this method when handling the checked binary operator.

2023-02-01 21:30 UTC, jachris commented on compiler/rustc_mir_dataflow/src/value_analysis.rs
> +    /// The target place must have been flooded before calling this method.
You can also consider renaming `assign_place_idx`.

2023-02-04 12:04 UTC, cjgillot commented on compiler/rustc_mir_dataflow/src/value_analysis.rs
> +    /// The target place must have been flooded before calling this method.
I renamed them `insert_*_idx`.
About dangerousness: https://github.com/rust-lang/rust/pull/107009 interprets MIR backwards, so it needs to call these functions *before* flooding.

2023-02-04 18:50 UTC, oli-obk commented
Most of this PR should now be unnecessary now that we don't deaggregate anymore, right?

2023-02-05 10:57 UTC, cjgillot commented
This PR has 2 parts:
1. an extension of the `flood` model to correctly discard aliasing projections when assigning to a variant;
2. the handling of discriminants and variants in the pass.

We do not ban direct assignment to variants, see the `mutate_discriminant` test case. As we do not deaggregate, those direct assignments do not "naturally" appear in MIR any more (except for generators, that this pass does not handle), but may be introduced by other passes.

Remains the question of the semantics of
```rust
a = NonZeroUsize { 0: 0_usize }
b = Option::<NonZeroUsize>::Some(a)
```

Notably:
- under the current implementation of interpret and codegen, discriminant assignment comes last, so `discriminant(b)` is 1;
- but what is `(b as Some).0.0`? ConstProp and codegen would say 1, this pass must decide on 0 or 1.

There are 2 ways to handle this:
a. this PR;
b. we ban direct assignment to *enum* variants, with a check in MIR validation (keeping such assignements for generators).

(b) renders part (1) of this PR unnecessary, as all such assignments will go through pointers, unsupported by this pass. I would also remove the `TrackElem::Variant`, as those would be systematically flooded by the aggregate assignment.

2023-02-13 14:46 UTC, oli-obk requested changes
r=me with typo fixed

2023-02-13 14:46 UTC, oli-obk commented on compiler/rustc_mir_transform/src/dataflow_const_prop.rs
> +    fn eval_disciminant(
```suggestion
    fn eval_discriminant(
```

2023-02-13 17:02 UTC, oli-obk commented
@bors r+

2023-02-15 12:02 UTC, merged