improve panic message for slice windows and chunks
rust-lang/rust pull request #107442
Opened 2023-01-29 13:43 UTC by lukas-code

before:
```text
thread 'main' panicked at 'size is zero', /rustc/1e225413a21fa69570bd3fefea9eb05e33f8b917/library/core/src/slice/mod.rs:809:44
```

after:
```text
thread 'main' panicked at 'windows cannot have a size of zero', src/main.rs:4:22
```

fixes https://github.com/rust-lang/rust/issues/107437

2023-01-29 19:46 UTC, eggyal requested changes

2023-01-29 19:46 UTC, eggyal commented on library/core/src/slice/mod.rs
> +        let size = NonZeroUsize::new(size).expect("windows cannot have a size of zero");
The [recommended message style](https://doc.rust-lang.org/std/result/enum.Result.html#recommended-message-style) is to express what the value *should* be, not what it shouldn't.  Therefore:

```suggestion
        let size = NonZeroUsize::new(size).expect("windows should have a non-zero size");
```

2023-01-29 20:48 UTC, albertlarsan68 commented
Bringing my 2 cents:
I think it should be a diagnostic rather than a panic, but I don't know whether this is feasible.

2023-01-29 21:40 UTC, eggyal commented
@albertlarsan68: there are unstable/nightly-only APIs like [`array_windows`](https://doc.rust-lang.org/std/primitive.slice.html#method.array_windows) that can be enforced at compile-time, but for `windows` etc the window-size is not known until runtime.

2023-01-29 21:49 UTC, lukas-code commented
> like [`array_windows`](https://doc.rust-lang.org/std/primitive.slice.html#method.array_windows) that can be enforced at compile-time

That's https://github.com/rust-lang/rust/pull/99471.

> diagnostic

It's probably possible to create a lint similar to [`unconditional_panic`](https://doc.rust-lang.org/rustc/lints/listing/deny-by-default.html#unconditional-panic), but that's out of scope for this PR.

2023-01-29 22:00 UTC, eggyal commented
> It's probably possible to create a lint similar to unconditional_panic

Sure, but only for situations where the runtime size can be const-folded and evaluated to be 0 at compile-time.

2023-01-30 23:22 UTC, cuviper commented
I think `ArrayChunks::new`'s direct style is better, and a strong "must" is appropriate:
https://github.com/rust-lang/rust/blob/a322848c6b0e037c1f0209387558ecb6ab763714/library/core/src/iter/adapters/array_chunks.rs#L28

It's also clear to say just "chunk size" or "window size", rather than mixing up windows/chunks/rchunks variants.

2023-01-31 20:55 UTC, lukas-code commented
I've updated the wording to "chunk size must be non-zero" everywhere and use `assert!` instead of `assert_ne!` to remove the redundant `0 != 0`.

2023-01-31 22:43 UTC, cuviper reviewed
Windows are different than chunks. :)

2023-01-31 22:43 UTC, cuviper commented on library/core/src/slice/mod.rs
> +        let size = NonZeroUsize::new(size).expect("chunk size must be non-zero");
```suggestion
        let size = NonZeroUsize::new(size).expect("window size must be non-zero");
```

2023-01-31 22:43 UTC, cuviper commented on library/core/src/slice/mod.rs
> +        assert!(N != 0, "chunk size must be non-zero");
```suggestion
        assert!(N != 0, "window size must be non-zero");
```

2023-01-31 22:52 UTC, lukas-code commented
Sorry, I thought that was what you meant by https://github.com/rust-lang/rust/pull/107442#issuecomment-1409511197. I changed window back now.

2023-01-31 23:29 UTC, cuviper commented
Ah, I only meant that "window/chunk size" should be the subject, rather than "windows/chunks" (the methods) as the subject having a size. Anyway, looks good now!

@bors r+

2023-02-01 10:40 UTC, merged