Inline CSS background images directly into the CSS
rust-lang/rust pull request #107531
Opened 2023-01-31 20:26 UTC by GuillaumeGomez

A nice advantage of this is that it removes a few entries in the list of static files.

r? @notriddle

2023-01-31 22:19 UTC, GuillaumeGomez commented on src/librustdoc/html/static/css/rustdoc.css
> +	background-image: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiBpZD0iTGF5ZXJfMSIgd2lkdGg9IjEyOCIgaGVpZ
If we inline it like in #104267, no need to worry about doing the inlining in base64 (unless it's the whole inlining itself that bothers you?).

Also agreed, with content not in base64, backslash looks much better so I'll use it instead.

2023-01-31 22:40 UTC, GuillaumeGomez commented
Updated to keep the svg content as is instead of using base64 and added some backslashes.

2023-01-31 23:04 UTC, notriddle requested changes

2023-02-01 10:38 UTC, GuillaumeGomez commented on src/librustdoc/html/static/css/rustdoc.css
> +	background: url('data:image/svg+xml;utf8,<svg width="17" height="17" \
Good point.

2023-02-01 10:42 UTC, GuillaumeGomez commented on src/librustdoc/html/static/css/rustdoc.css
> +stroke-miterlimit="10" stroke-width="12"/></g></svg>');
Wow that's much smaller. Did you use a software in particular to generate the smaller version?

2023-02-01 10:51 UTC, GuillaumeGomez commented
Updated!

2023-02-01 16:11 UTC, GuillaumeGomez commented on src/librustdoc/html/static/css/rustdoc.css
> +stroke-miterlimit="10" stroke-width="12"/></g></svg>');
The famous `notriddle` software. ;)

2023-02-01 16:19 UTC, notriddle approved these changes

2023-02-01 20:27 UTC, compiler-errors commented
@bors retry CI was broken

2023-02-02 12:01 UTC, merged

2023-02-02 18:14 UTC, rust-log-analyzer commented
A job failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/4068319931/jobs/7006738278) [(plain)](https://github.com/rust-lang-ci/rust/commit/4a77303648d62e07be6ac2b2ba307cba229c6a34/checks/11044372043/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

```

</details>