Copy `bin/*` and `lib/*.dylib` files to `stage0-sysroot`
rust-lang/rust pull request #107956
Opened 2023-02-12 15:34 UTC by KittyBorgX

Fixes #101691

2023-02-12 15:34 UTC, KittyBorgX commented
r? @jyn514

2023-02-12 15:35 UTC, jyn514 commented
I don't have time for reviews right now.

r? @ozkanonur

2023-02-12 16:02 UTC, KittyBorgX commented
@ozkanonur I've fixed the breaking changes. Do I add a new commit or ammend it to the existing one?

2023-02-12 16:03 UTC, ozkanonur commented
> @ozkanonur I've fixed the breaking changes. Do I add a new commit or ammend it to the existing one?

Ammend it please :)

2023-02-12 22:02 UTC, jyn514 commented
@rustbot ready

2023-02-12 22:16 UTC, ozkanonur commented
ref from the issue:
> 2. `x dist --stage 0` doesn't work:
> 
> ```
> thread 'main' panicked at 'could not read dir "/home/dawn/projects/rust/build/x86_64-unknown-linux-gnu/stage0-sysroot/bin": Os { code: 2, kind: NotFound, message: "No such file or directory" }', lib.rs:1573:25
> ```


Still doesn't work

```sh
 remotes/KittyBorgX/master $ ./x dist --stage 0

thread 'main' panicked at 'could not read dir "/home/nimda/devspace/personal/rust2/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends": Os { code: 2, kind: NotFound, message: "No such file or directory" }', lib.rs:1522:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

2023-02-13 01:30 UTC, KittyBorgX commented
I see the issue. The original pr (#101711) broke when `rustc` and `cargo` was set which works fine with my PR. 
Here's a screenshot: 
![image](https://user-images.githubusercontent.com/82328083/218350624-4145750f-b259-4288-8e0b-8f9758a8785d.png)

As to `codegen-backends` which failed in the above comment: 
```
 remotes/KittyBorgX/master $ ./x dist --stage 0
thread 'main' panicked at 'could not read dir "/home/nimda/devspace/personal/rust2/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends": Os { code: 2, kind: NotFound, message: "No such file or directory" }', lib.rs:1522:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I followed : https://rust-lang.zulipchat.com/#narrow/stream/326414-t-infra.2Fbootstrap/topic/Copying.20binaries.20to.20stage0-sysroot/near/326813495

and didn't copy it. I will work on the same and update this pr. 
Sidenote : On like 463, in my current pr, it is `x.starts_with(sysroot_lib_dir.join("rustlib").into_boxed_path())` which passes the ci and passes the test locally but doesn't do the actual job that is intended and fails like how you mentioned in the second half of the above comment. But having `!x.starts_with(sysroot_lib_dir.join("rustlib").into_boxed_path())` does the job of copying correctly but fails the CI and doesn't pass the tests. This has hit me with a roadblock which forces me to use another option and look into it deeply. Can I take some more time to work on this issue, if that's alright?

2023-02-13 08:45 UTC, ozkanonur commented
> I see the issue. The original pr (#101711) broke when `rustc` and `cargo` was set which works fine with my PR. Here's a screenshot: ![image](https://user-images.githubusercontent.com/82328083/218350624-4145750f-b259-4288-8e0b-8f9758a8785d.png)

This doesn't work on `x86_64`. 
```sh
  ~  $ rustc +issue-101691 --v
/home/nimda/.rustup/toolchains/issue-101691/bin/rustc: error while loading shared libraries: librustc_driver-c78d16bcb49dc5d0.so: cannot open shared object file: No such file or directory
```

> Can I take some more time to work on this issue, if that's alright?

Please take your time

2023-02-13 10:52 UTC, KittyBorgX commented
@ozkanonur Can you help me? I've found a fix which works and passes the tests but I pulled the upstream changes and git(hub) added a commit. Is there any way I can delete the commit? Or should I close this PR and open a new one?

2023-02-13 11:14 UTC, KittyBorgX commented
Thank you so much! I've done the necessary changes and pushed it.

2023-02-13 11:16 UTC, ozkanonur commented
> Thank you so much! I've made the necessary changes and pushed it.

Great! I will review it later today or tomorrow.

2023-02-13 11:24 UTC, KittyBorgX commented
Thanks! 
Just a few points: 
- I didn't run tidy and fmt which caused the ci to break :( 
- I forgot to take care of the `codegen-backends` and `./x dist --stage 0` might fail. I have to code ready for it, I'll format it, tidy it and push it asap after the ci is done building.

2023-02-13 12:42 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/4162836854/jobs/7202504895) [(plain)](https://github.com/rust-lang/rust/commit/982ab4dfd446fd812e2b47e5f0e2b16964235a5a/checks/11297120125/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:ac593985615ec2ede58e132d2e21d2b1cbd6127c)
Download action repository 'rust-lang/simpleinfra@master' (SHA:7b992ce41a6506cf6388fd9a3d24a6eaebaa1d31)
Complete job name: PR (mingw-check-tidy, true, ubuntu-20.04-xl)
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  CI_JOB_NAME: mingw-check-tidy
---
Building wheels for collected packages: reuse
  Building wheel for reuse (pyproject.toml): started
  Building wheel for reuse (pyproject.toml): finished with status 'done'
  Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=180117 sha256=a2b5d39c8ff2686626c851b00c3d3ae10157feb2cc6d0d07e414234b479dbb17
  Stored in directory: /tmp/pip-ephem-wheel-cache-vz6rzxko/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
---
Successfully built 6aee4b1db7e3
Successfully tagged rust-ci:latest
Built container sha256:6aee4b1db7e3c5441582f541a7322080354226500bd59813043d7a164b607f9c
Uploading finished image to https://ci-caches.rust-lang.org/docker/f36b5782f7228aca51ac4b42fc8d834a0357048eedd2f8ec11ebf729b3642b4f40d12a04648dc10cace4cb151f5ecc2ac820f64f301d3380602cceb15ce3c48d
upload failed: - to s3://rust-lang-ci-sccache2/docker/f36b5782f7228aca51ac4b42fc8d834a0357048eedd2f8ec11ebf729b3642b4f40d12a04648dc10cace4cb151f5ecc2ac820f64f301d3380602cceb15ce3c48d Unable to locate credentials
[CI_JOB_NAME=mingw-check-tidy]
[CI_JOB_NAME=mingw-check-tidy]
---
   Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
    Finished release [optimized] target(s) in 15.15s
fmt check
skip untracked path cpu-usage.csv during rustfmt invocations
Diff in /checkout/src/bootstrap/compile.rs at line 463:
                 for file in files {
                     let file = t!(file);
                     let path = file.path();
-                    if path.is_file() && is_dylib(&file.file_name().into_string().unwrap()) && !path.starts_with(sysroot_lib_dir.join("rustlib").into_boxed_path()){
+                    if path.is_file()
+                        && is_dylib(&file.file_name().into_string().unwrap())
+                        && !path.starts_with(sysroot_lib_dir.join("rustlib").into_boxed_path())
+                    {
                         builder.copy(&path, &sysroot_lib_dir.join(path.file_name().unwrap()));
                 }
Build completed unsuccessfully in 0:00:17
Build completed unsuccessfully in 0:00:17
Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/src/bootstrap/run.rs" "/checkout/src/bootstrap/install.rs" "/checkout/src/bootstrap/native.rs" "/checkout/src/bootstrap/tool.rs" "/checkout/src/bootstrap/compile.rs" "/checkout/src/bootstrap/builder/tests.rs" "/checkout/src/bootstrap/bolt.rs" "/checkout/src/bootstrap/metrics.rs"` failed.
If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
```

</details>

2023-02-13 15:28 UTC, KittyBorgX commented
@rustbot ready

2023-02-13 16:19 UTC, ozkanonur commented
:(

```sh
~/devspace/personal/rust-dist/compiler  $ ../../rust/x dist --stage 0

thread 'main' panicked at 'generated a symlink in a tarball: /home/nimda/devspace/personal/rust-dist/compiler/build/tmp/tarball/rustc/x86_64-unknown-linux-gnu/rustc-1.69.0-dev-x86_64-unknown-linux-gnu/rustc/bin/rustfmt', tarball.rs:330:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        finished in 34.565 seconds
Build completed unsuccessfully in 0:04:02
```

2023-02-13 16:23 UTC, ozkanonur requested changes

2023-02-13 16:23 UTC, ozkanonur commented on src/bootstrap/compile.rs
> +                .join("lib/rustlib")
```suggestion
            let host_codegen_backends = host_lib_dir
                .join("rustlib")
```

2023-02-13 17:00 UTC, KittyBorgX commented on src/bootstrap/compile.rs
> +            builder.cp_r(&host_codegen_backends, &sysroot_codegen_backends);
I copy pasted to comment and forgot to change it!
Fixed it now.

2023-02-13 17:00 UTC, KittyBorgX commented on src/bootstrap/compile.rs
> +                .join("lib/rustlib")
Done!

2023-02-13 17:05 UTC, KittyBorgX commented
> :(
> 
> ```shell
> ~/devspace/personal/rust-dist/compiler  $ ../../rust/x dist --stage 0
> 
> thread 'main' panicked at 'generated a symlink in a tarball: /home/nimda/devspace/personal/rust-dist/compiler/build/tmp/tarball/rustc/x86_64-unknown-linux-gnu/rustc-1.69.0-dev-x86_64-unknown-linux-gnu/rustc/bin/rustfmt', tarball.rs:330:21
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
>         finished in 34.565 seconds
> Build completed unsuccessfully in 0:04:02
> ```

a- 
im lost on how to debug this but I will get this done in 12 hours ( 8 hours of which is my sleep :) )

2023-02-13 17:11 UTC, KittyBorgX commented
@ozkanonur Im really sorry if this is taking longer than expected, this is my first contribution and im half new to rust and the rust repo :(

2023-02-13 20:55 UTC, ozkanonur commented
> @ozkanonur Im really sorry if this is taking longer than expected, this is my first contribution and im half new to rust and the rust repo :(

It's all fine, don't worry about it :)

You can do the tests and once you see they all working fine, push the changes and wait for CI pipelines to be passed. If everything goes well, ping me here saying "you can do the review" so I know when to review this PR.

You can do the tests with the following instructions:
```sh
## 1st test ##

# make sure this doesn't panic
x dist --stage 0

## 2nd test ##

# build stage 0
x build --stage 0

# then link the stage0-sysroot
rustup toolchain link {toolchain_name} {path_to_stage0-sysroot}

# check if rustc works properly with linked toolchain
rustc +{toolchain_name} --version

# sanity check for rustc, basically create simple rust project and run it with linked toolchain
cargo new hello
cd hello
cargo +{toolchain_name} run
```

2023-02-16 03:19 UTC, KittyBorgX commented
@ozkanonur 
Here's the update: 
I got `x dist --stage 0` to finally build successfully. However as `@jyn514` mentioned, there's a bug in `dist` which causes the submodules to not get checked out automatically. I'm filing an issue for that today. Do I wait for that issue to get resolved or shall I push my changes here? I got it to work by adding some more code and running `git submodule update --init`

PS : Here's the working screenshot: 
![image](https://user-images.githubusercontent.com/82328083/219259697-006fc585-0e08-49d4-9fea-09995375bf9e.png)

2023-02-16 14:54 UTC, KittyBorgX commented
@rustbot ready
@ozkanonur You can review now :) I'm done with all my changes.

2023-02-16 23:44 UTC, ozkanonur approved these changes
this looks good, can you add this empty lines as well?

2023-02-16 23:44 UTC, ozkanonur commented on src/bootstrap/compile.rs
> +        if compiler.stage == 0 {
```suggestion

        if compiler.stage == 0 {
```

2023-02-16 23:44 UTC, ozkanonur commented on src/bootstrap/compile.rs
> +            }
```suggestion
            }

```

2023-02-17 01:05 UTC, KittyBorgX commented
Done 👍

2023-02-17 06:36 UTC, ozkanonur commented
@bors +r rollup

2023-02-17 06:37 UTC, ozkanonur commented
@bors r+ rollup

2023-02-17 07:17 UTC, KittyBorgX commented
@ozkanonur and @jyn514  Tysm for helping me throught the PR! I couldn't have done it without your help :D

2023-02-17 07:54 UTC, ozkanonur commented
congratz your first PR :)

2023-02-17 17:42 UTC, merged

2023-02-20 02:25 UTC, KittyBorgX commented
@bors try @rust-timer queue

2023-02-20 02:25 UTC, rust-timer commented
Insufficient permissions to issue commands to rust-timer.
<!-- rust-timer: temporary -->

2023-02-20 09:26 UTC, albertlarsan68 commented
@rust-timer build 89394208c043edd910fa6c950968ca75fcf349c0

2023-02-20 09:27 UTC, rust-timer commented
Queued 89394208c043edd910fa6c950968ca75fcf349c0 with parent f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3, future [comparison URL](https://perf.rust-lang.org/compare.html?start=f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3&end=89394208c043edd910fa6c950968ca75fcf349c0).
<!-- rust-timer: temporary -->

2023-02-20 11:37 UTC, rust-timer commented
Finished benchmarking commit (89394208c043edd910fa6c950968ca75fcf349c0): [comparison URL](https://perf.rust-lang.org/compare.html?start=f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3&end=89394208c043edd910fa6c950968ca75fcf349c0&stat=instructions:u).

### Overall result: no relevant changes - no action needed


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

@bors rollup=never
@rustbot label: -S-waiting-on-perf -perf-regression



**Warning ⚠**: The following benchmark(s) failed to build:
- rustc


### [Instruction count](https://perf.rust-lang.org/compare.html?start=f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3&end=89394208c043edd910fa6c950968ca75fcf349c0&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3&end=89394208c043edd910fa6c950968ca75fcf349c0&stat=max-rss)
This benchmark run did not return any relevant results for this metric.

### [Cycles](https://perf.rust-lang.org/compare.html?start=f4f5fc3e5cc70b7a43bf7b518c455f3d9bada9e3&end=89394208c043edd910fa6c950968ca75fcf349c0&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -2.2% | [-2.2%, -2.2%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -2.2% | [-2.2%, -2.2%] | 1     |
</details>

2023-02-20 12:59 UTC, albertlarsan68 commented
@KittyBorgX ^
This PR does break rustc benches, but not the bootstrap timings, it has them.

2023-02-20 13:09 UTC, KittyBorgX commented
ah alright. 
@albertlarsan68 thank you so much for running it :)

2023-02-20 20:22 UTC, Kobzol commented
It's the same thing AFAIK, bootstrap timings = building rustc. The timings there are from a previous run, the "B column" is missing.