Add rem_floor and rem_ceil
rust-lang/rust pull request #108193
Opened 2023-02-17 21:44 UTC by clarfonthey

Since `rem_ceil` is awkward for unsigned integers, I've put it under a separate feature flag, although the result is still in the same tracking issue.

I also removed the `rhs > 0` check on the unsigned `div_ceil` since it's not necessary, and can be a bit confusing to readers. (The only alternative would be `rhs = 0`, which would panic before reaching this point.)

2023-02-17 22:59 UTC, jhpratt approved these changes
Setting aside my lack of understanding on the use case, the implementation looks good to me.

2023-02-18 08:24 UTC, leonardo-m commented
> Setting aside my lack of understanding on the use case,

What's a use case of this?

2023-02-18 08:30 UTC, jhpratt commented
I don't know…that's the point. But let's keep discussion of that in #88581.

2023-02-18 08:53 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-14`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/4208417773/jobs/7304409100) [(plain)](https://github.com/rust-lang/rust/commit/1a98814ff42f6d7caac5c3c0fb0f2d62cee5a2fb/checks/11430994468/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:ac593985615ec2ede58e132d2e21d2b1cbd6127c)
Download action repository 'rust-lang/simpleinfra@master' (SHA:75573f9759179a720f4c3af6c9fb518ac0061dca)
Complete job name: PR (x86_64-gnu-llvm-14, false, ubuntu-20.04-xl)
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  CI_JOB_NAME: x86_64-gnu-llvm-14
---
---- [rustdoc-json] tests/rustdoc-json/primitives/use_primitive.rs stdout ----

error: jsondoclint failed!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/jsondoclint" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc-json/primitives/use_primitive/use_primitive.json"
stdout: none
--- stderr -------------------------------
2:28776:33502 not in index or paths, but refered to at '$.index["2:29402:34671"].links["isize::rem_ceil"]'
Error: Errors validating json /checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc-json/primitives/use_primitive/use_primitive.json



failures:
```

</details>

2023-02-18 22:43 UTC, clarfonthey commented
(FWIW I don't understand the docs error: I did define `isize::rem_ceil` so I don't know why it fails to link.)

2023-02-18 22:55 UTC, scottmcm commented
r? joshtriplett 
As a team member and the same person assigned to #94455

2023-03-23 04:07 UTC, clarfonthey commented
(I decided to replace the link with a manual one so that it would pass the tests. No idea why it's failing otherwise.)

2023-08-15 20:06 UTC, scottmcm commented
Pondering: would who wants a consistent div and rem result would pair `div_floor` with `rem_ceil`?

That would look odd to me when reviewing, but it's also correct if `rem_ceil` means `ceil(a % b)`, I think?

Thus maybe it would be nice to have merged versions of these, so you get both the quotient and the remainder in one call, with a consistent rounding direction for both.

2023-08-16 21:56 UTC, clarfonthey commented
I'd be more than happy to write up an ACP for this, although it's worth clarifying that I *did* include use cases in the original tracking issue: https://github.com/rust-lang/rust/issues/88581#issuecomment-1435784658

Ceiling remainder of unsigned integers is the one that I would consider weird and difficult to use, since it's asymmetrical: the remainder of ceiling division is always negative or zero, meaning that you have to return the absolute value of the result instead, or fail on non-exact division.

It's incredibly important and worth repeating: integer division and remainder *always* come in pairs. Yes, there are a lot of cases where you just throw out the remainder because you're wanting to round something, but I feel like the terms "division" and "remainder" gives a lot of clarity into the sorts of operations that would use these for: you're dividing something into a series of pieces, and even if you often toss out the "remainder," there's still the opportunity to make use of it. While we often abstract division as part of other operations (like averaging), it's good to remember what it actually physically represents.

2023-09-16 06:03 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-15`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/6205584866/job/16848913868) [(plain)](https://github.com/rust-lang/rust/commit/5a8ef6e2c69e567dc2676b1028e0a1c1f1895cc5/checks/16848913868/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=clarfonthey
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_befca695-08a3-4fca-9aa0-63a05b80fab5
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=0a176c8d0c899d5c32751f8c14fc5c52866903dd
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_befca695-08a3-4fca-9aa0-63a05b80fab5
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_befca695-08a3-4fca-9aa0-63a05b80fab5
GITHUB_TRIGGERING_ACTOR=clarfonthey
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/108193/merge
GITHUB_WORKFLOW_SHA=0a176c8d0c899d5c32751f8c14fc5c52866903dd
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_18_X64=/opt/hostedtoolcache/go/1.18.10/x64
---
##[group]Building stage0 tool linkchecker (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.12s
##[endgroup]
##[group]Testing stage0 Linkcheck (x86_64-unknown-linux-gnu)
core/arch/x86_64/type.__mmask32.html:732: broken link - `core/arch/x86_64/primitive.i32.html`
core/arch/x86_64/type.__mmask16.html:732: broken link - `core/arch/x86_64/primitive.i16.html`
core/arch/x86_64/type.__mmask8.html:732: broken link - `core/arch/x86_64/primitive.i8.html`
core/arch/x86_64/type.__mmask64.html:732: broken link - `core/arch/x86_64/primitive.i64.html`
core/arch/x86/type.__mmask32.html:732: broken link - `core/arch/x86/primitive.i32.html`
core/arch/x86/type.__mmask16.html:732: broken link - `core/arch/x86/primitive.i16.html`
core/arch/x86/type.__mmask8.html:732: broken link - `core/arch/x86/primitive.i8.html`
core/arch/x86/type.__mmask64.html:732: broken link - `core/arch/x86/primitive.i64.html`
core/ffi/type.c_size_t.html:734: broken link - `core/ffi/primitive.isize.html`
core/ffi/type.c_uint.html:733: broken link - `core/ffi/primitive.i32.html`
core/ffi/type.c_uchar.html:733: broken link - `core/ffi/primitive.i8.html`
core/ffi/type.c_ushort.html:733: broken link - `core/ffi/primitive.i16.html`
core/ffi/type.c_ulonglong.html:733: broken link - `core/ffi/primitive.i64.html`
core/ffi/type.c_ulong.html:733: broken link - `core/ffi/primitive.i64.html`
std/ffi/type.c_uint.html:733: broken link - `std/ffi/primitive.i32.html`
std/ffi/type.c_uchar.html:733: broken link - `std/ffi/primitive.i8.html`
std/ffi/type.c_ushort.html:733: broken link - `std/ffi/primitive.i16.html`
std/ffi/type.c_ulonglong.html:733: broken link - `std/ffi/primitive.i64.html`
std/ffi/type.c_ulong.html:733: broken link - `std/ffi/primitive.i64.html`
std/os/raw/type.c_uint.html:733: broken link - `std/os/raw/primitive.i32.html`
std/os/raw/type.c_uchar.html:733: broken link - `std/os/raw/primitive.i8.html`
std/os/raw/type.c_ushort.html:733: broken link - `std/os/raw/primitive.i16.html`
std/os/raw/type.c_ulonglong.html:733: broken link - `std/os/raw/primitive.i64.html`
std/os/raw/type.c_ulong.html:733: broken link - `std/os/raw/primitive.i64.html`
std/os/windows/raw/type.SOCKET.html:731: broken link - `std/os/windows/raw/primitive.i64.html`
std/os/windows/io/type.RawSocket.html:732: broken link - `std/os/windows/io/primitive.i64.html`
std/os/linux/raw/type.nlink_t.html:731: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.blkcnt_t.html:731: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.blksize_t.html:731: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.pthread_t.html:731: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.off_t.html:731: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.mode_t.html:731: broken link - `std/os/linux/raw/primitive.i32.html`
std/os/linux/raw/type.dev_t.html:731: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.ino_t.html:731: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/unix/raw/type.nlink_t.html:731: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.uid_t.html:731: broken link - `std/os/unix/raw/primitive.i32.html`
std/os/unix/raw/type.blkcnt_t.html:731: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.blksize_t.html:731: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.pthread_t.html:731: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.gid_t.html:731: broken link - `std/os/unix/raw/primitive.i32.html`
std/os/unix/raw/type.off_t.html:731: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.mode_t.html:731: broken link - `std/os/unix/raw/primitive.i32.html`
std/os/unix/raw/type.dev_t.html:731: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.ino_t.html:731: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/thread/type.RawPthread.html:731: broken link - `std/os/unix/thread/primitive.i64.html`
number of HTML files scanned: 34788
number of HTML redirects found: 10546
number of links checked: 3699337
number of links ignored due to external: 93260
```

</details>

2023-09-16 22:32 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-15`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/6209836385/job/16857484060) [(plain)](https://github.com/rust-lang/rust/commit/7f6ac30b46aa362ebafaa8e150ef437ce1e4303b/checks/16857484060/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=clarfonthey
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_108ce29f-d31d-4878-9b85-09fd5f5cc5d2
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=b39bded303be8d7f0b80c32a22e365f59cc34c3b
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_108ce29f-d31d-4878-9b85-09fd5f5cc5d2
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_108ce29f-d31d-4878-9b85-09fd5f5cc5d2
GITHUB_TRIGGERING_ACTOR=clarfonthey
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/108193/merge
GITHUB_WORKFLOW_SHA=b39bded303be8d7f0b80c32a22e365f59cc34c3b
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_18_X64=/opt/hostedtoolcache/go/1.18.10/x64
---
##[group]Building stage0 tool linkchecker (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.10s
##[endgroup]
##[group]Testing stage0 Linkcheck (x86_64-unknown-linux-gnu)
core/arch/x86_64/type.__mmask32.html:732: broken link - `core/arch/x86_64/primitive.i32.html`
core/arch/x86_64/type.__mmask16.html:732: broken link - `core/arch/x86_64/primitive.i16.html`
core/arch/x86_64/type.__mmask8.html:732: broken link - `core/arch/x86_64/primitive.i8.html`
core/arch/x86_64/type.__mmask64.html:732: broken link - `core/arch/x86_64/primitive.i64.html`
core/arch/x86/type.__mmask32.html:732: broken link - `core/arch/x86/primitive.i32.html`
core/arch/x86/type.__mmask16.html:732: broken link - `core/arch/x86/primitive.i16.html`
core/arch/x86/type.__mmask8.html:732: broken link - `core/arch/x86/primitive.i8.html`
core/arch/x86/type.__mmask64.html:732: broken link - `core/arch/x86/primitive.i64.html`
core/ffi/type.c_size_t.html:734: broken link - `core/ffi/primitive.isize.html`
core/ffi/type.c_uint.html:733: broken link - `core/ffi/primitive.i32.html`
core/ffi/type.c_uchar.html:733: broken link - `core/ffi/primitive.i8.html`
core/ffi/type.c_ushort.html:733: broken link - `core/ffi/primitive.i16.html`
core/ffi/type.c_ulonglong.html:733: broken link - `core/ffi/primitive.i64.html`
core/ffi/type.c_ulong.html:733: broken link - `core/ffi/primitive.i64.html`
std/ffi/type.c_uint.html:733: broken link - `std/ffi/primitive.i32.html`
std/ffi/type.c_uchar.html:733: broken link - `std/ffi/primitive.i8.html`
std/ffi/type.c_ushort.html:733: broken link - `std/ffi/primitive.i16.html`
std/ffi/type.c_ulonglong.html:733: broken link - `std/ffi/primitive.i64.html`
std/ffi/type.c_ulong.html:733: broken link - `std/ffi/primitive.i64.html`
std/os/raw/type.c_uint.html:733: broken link - `std/os/raw/primitive.i32.html`
std/os/raw/type.c_uchar.html:733: broken link - `std/os/raw/primitive.i8.html`
std/os/raw/type.c_ushort.html:733: broken link - `std/os/raw/primitive.i16.html`
std/os/raw/type.c_ulonglong.html:733: broken link - `std/os/raw/primitive.i64.html`
std/os/raw/type.c_ulong.html:733: broken link - `std/os/raw/primitive.i64.html`
std/os/windows/raw/type.SOCKET.html:731: broken link - `std/os/windows/raw/primitive.i64.html`
std/os/windows/io/type.RawSocket.html:732: broken link - `std/os/windows/io/primitive.i64.html`
std/os/linux/raw/type.nlink_t.html:731: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.blkcnt_t.html:731: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.blksize_t.html:731: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.pthread_t.html:731: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.off_t.html:731: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.mode_t.html:731: broken link - `std/os/linux/raw/primitive.i32.html`
std/os/linux/raw/type.dev_t.html:731: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.ino_t.html:731: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/unix/raw/type.nlink_t.html:731: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.uid_t.html:731: broken link - `std/os/unix/raw/primitive.i32.html`
std/os/unix/raw/type.blkcnt_t.html:731: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.blksize_t.html:731: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.pthread_t.html:731: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.gid_t.html:731: broken link - `std/os/unix/raw/primitive.i32.html`
std/os/unix/raw/type.off_t.html:731: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.mode_t.html:731: broken link - `std/os/unix/raw/primitive.i32.html`
std/os/unix/raw/type.dev_t.html:731: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.ino_t.html:731: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/thread/type.RawPthread.html:731: broken link - `std/os/unix/thread/primitive.i64.html`
number of HTML files scanned: 34789
number of HTML redirects found: 10546
number of links checked: 3700694
number of links ignored due to external: 93263
```

</details>

2023-10-13 06:43 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-15`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/6504727434/job/17667128350) [(plain)](https://github.com/rust-lang/rust/commit/0da93e63848b8c82abae120c2cf8ac5c2fe20382/checks/17667128350/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=clarfonthey
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_34a7298a-a33b-44e6-9f1e-2237b6b194e5
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=c95defd59677ffe0587715810ad7c7ef5b024a30
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_34a7298a-a33b-44e6-9f1e-2237b6b194e5
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_34a7298a-a33b-44e6-9f1e-2237b6b194e5
GITHUB_TRIGGERING_ACTOR=clarfonthey
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/108193/merge
GITHUB_WORKFLOW_SHA=c95defd59677ffe0587715810ad7c7ef5b024a30
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.13/x64
---
##[group]Building stage0 tool linkchecker (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.11s
##[endgroup]
##[group]Testing stage0 Linkcheck (x86_64-unknown-linux-gnu)
core/arch/x86_64/type.__mmask32.html:835: broken link - `core/arch/x86_64/primitive.i32.html`
core/arch/x86_64/type.__mmask16.html:835: broken link - `core/arch/x86_64/primitive.i16.html`
core/arch/x86_64/type.__mmask8.html:832: broken link - `core/arch/x86_64/primitive.i8.html`
core/arch/x86_64/type.__mmask64.html:835: broken link - `core/arch/x86_64/primitive.i64.html`
core/arch/x86/type.__mmask32.html:835: broken link - `core/arch/x86/primitive.i32.html`
core/arch/x86/type.__mmask16.html:835: broken link - `core/arch/x86/primitive.i16.html`
core/arch/x86/type.__mmask8.html:832: broken link - `core/arch/x86/primitive.i8.html`
core/arch/x86/type.__mmask64.html:835: broken link - `core/arch/x86/primitive.i64.html`
core/ffi/type.c_size_t.html:837: broken link - `core/ffi/primitive.isize.html`
core/ffi/type.c_uint.html:836: broken link - `core/ffi/primitive.i32.html`
core/ffi/type.c_uchar.html:833: broken link - `core/ffi/primitive.i8.html`
core/ffi/type.c_ushort.html:836: broken link - `core/ffi/primitive.i16.html`
core/ffi/type.c_ulonglong.html:836: broken link - `core/ffi/primitive.i64.html`
core/ffi/type.c_ulong.html:836: broken link - `core/ffi/primitive.i64.html`
std/ffi/type.c_uint.html:747: broken link - `std/ffi/primitive.i32.html`
std/ffi/type.c_uchar.html:747: broken link - `std/ffi/primitive.i8.html`
std/ffi/type.c_ushort.html:747: broken link - `std/ffi/primitive.i16.html`
std/ffi/type.c_ulonglong.html:747: broken link - `std/ffi/primitive.i64.html`
std/ffi/type.c_ulong.html:747: broken link - `std/ffi/primitive.i64.html`
std/os/raw/type.c_uint.html:747: broken link - `std/os/raw/primitive.i32.html`
std/os/raw/type.c_uchar.html:747: broken link - `std/os/raw/primitive.i8.html`
std/os/raw/type.c_ushort.html:747: broken link - `std/os/raw/primitive.i16.html`
std/os/raw/type.c_ulonglong.html:747: broken link - `std/os/raw/primitive.i64.html`
std/os/raw/type.c_ulong.html:747: broken link - `std/os/raw/primitive.i64.html`
std/os/windows/raw/type.SOCKET.html:745: broken link - `std/os/windows/raw/primitive.i64.html`
std/os/windows/io/type.RawSocket.html:746: broken link - `std/os/windows/io/primitive.i64.html`
std/os/linux/raw/type.nlink_t.html:745: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.blkcnt_t.html:745: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.blksize_t.html:745: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.pthread_t.html:745: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.off_t.html:745: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.mode_t.html:745: broken link - `std/os/linux/raw/primitive.i32.html`
std/os/linux/raw/type.dev_t.html:745: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/linux/raw/type.ino_t.html:745: broken link - `std/os/linux/raw/primitive.i64.html`
std/os/unix/raw/type.nlink_t.html:745: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.uid_t.html:745: broken link - `std/os/unix/raw/primitive.i32.html`
std/os/unix/raw/type.blkcnt_t.html:745: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.blksize_t.html:745: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.pthread_t.html:745: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.gid_t.html:745: broken link - `std/os/unix/raw/primitive.i32.html`
std/os/unix/raw/type.off_t.html:745: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.mode_t.html:745: broken link - `std/os/unix/raw/primitive.i32.html`
std/os/unix/raw/type.dev_t.html:745: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/raw/type.ino_t.html:745: broken link - `std/os/unix/raw/primitive.i64.html`
std/os/unix/thread/type.RawPthread.html:745: broken link - `std/os/unix/thread/primitive.i64.html`
number of HTML files scanned: 34813
number of HTML redirects found: 10548
number of links checked: 3727287
number of links ignored due to external: 93432
```

</details>

2023-10-19 18:40 UTC, Dylan-DPC commented
@clarfonthey i think you would still need an ACP for this

2023-10-20 18:03 UTC, clarfonthey commented
From previous experience with ACPs, these are only for new features, and adding onto existing features is mostly what tracking issues are for. I would be happy to write up an ACP for `rem_ceil` since, as previously mentioned, it only makes sense for signed integers, but I think that `rem_floor` is reasonable to add for both.

2024-01-07 21:20 UTC, NCGThompson requested changes

2024-01-07 21:20 UTC, NCGThompson commented on library/core/src/num/int_macros.rs
> +        /// On overflow, this function will panic if overflow checks are enabled (default in debug
Signed `%` always panics on overflow (MIN / -1) regardless of the overflow checks compile option. At least this particular method will panic iff the `%` inside it panics. Therefor, the documentation is incorrect. The already merged ceil and floor div functions should be double checked with this in mind.

Once that is fixed I suggest explaining exactly what constitutes an overflow. (The remainder function never *truly* overflows, but it panics whenever the corresponding division would also panic.)

2024-01-08 01:17 UTC, NCGThompson commented on library/core/src/num/int_macros.rs
> +        /// On overflow, this function will panic if overflow checks are enabled (default in debug
> The already merged ceil and floor div functions should be double checked with this in mind.

Submitted a PR for that and some other stuff. #119726

2024-02-11 02:52 UTC, joshtriplett commented
r? libs-api

2024-04-05 05:52 UTC, dtolnay requested changes
Thanks for the PR!

I read most of the comments in #88581.

I am on board with signed `rem_floor` and signed `rem_ceil`, but not unsigned `rem_floor` and unsigned `unsigned_rem_ceil`. Would you like to remove those from this PR and I can merge it, or make one more attempt at synthesizing the rationale in favor of having the entire set?

2024-04-05 10:21 UTC, clarfonthey commented
Is there a particular reason you're against unsigned `rem_floor`? I know that it's equivalent to the default, but we already have unsigned `div_floor`, which is also the default, so, I'm not sure why remainder specifically should be excluded.

In terms of unsigned `rem_ceil`-- yes, I agree that this one is shaky, which is why I put it under a separate flag. I still think that it could be useful, and I'll put an explanation below, but if you'd rather not even do it then, I can remove it.

As I've said (and I sound like a broken record because I do genuinely believe this), a majority of cases that use division have a parallel case where the remainder could also be useful. For example, if you use `div_ceil` to round up a percentage bar, you could use `rem_ceil` when the rounding error makes the bar 100% to alternatively show the number of items remaining. Or, instead of deciding how many tasks are "left over" when dividing tasks among workers using flooring division, you could use ceiling division to get the number of no-op tasks to add to the list so it divides evenly.

Again, I agree that a lot of these fall into "but you could technically do it another way," but the primary goal of offering flooring and ceiling division was to make the intent of algorithms clearer, and I think offering remainders to all the division operators fits that, even if some are just identical to truncating division, and even if `rem_ceil` has to be negated in the unsigned case.

2024-04-05 10:47 UTC, dtolnay commented
> it's equivalent to the default, but we already have unsigned `div_floor`, which is also the default

I am going to be proposing for unsigned `div_floor` to be removed.

2024-04-05 11:07 UTC, clarfonthey commented
I see. I'm not sure I like that approach since it does go against some of the other philosophies from the standard library-- for example, date algorithms are mentioned as a common case for `div_floor`, and switching from a signed timestamp to an unsigned timestamp would mean you have to change all the div calls, and vice/versa. I get if the standard library preferred not having "trivial" methods like these but it does have a lot of them.

2024-07-01 06:09 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/9739041833/job/26873584985) [(plain)](https://github.com/rust-lang/rust/commit/08b59e887c22a1f1e62649b578e93c95cbdc417d/checks/26873584985/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Caused by:
  failed to parse manifest at `/checkout/src/doc/book/packages/mdbook-trpl-listing/Cargo.toml`

Caused by:
  error inheriting `clap` from workspace root manifest's `workspace.dependencies.clap`
Caused by:
  `workspace.dependencies` was not defined
thread 'main' panicked at src/core/metadata.rs:85:31:
command did not execute successfully: RUSTC_BOOTSTRAP="1" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "metadata" "--format-version" "1" "--no-deps" "--manifest-path" "/checkout/Cargo.toml"
---
Caused by:
  failed to parse manifest at `/checkout/src/doc/book/packages/mdbook-trpl-listing/Cargo.toml`

Caused by:
  error inheriting `clap` from workspace root manifest's `workspace.dependencies.clap`
Caused by:
  `workspace.dependencies` was not defined
thread 'main' panicked at src/core/metadata.rs:85:31:
command did not execute successfully: RUSTC_BOOTSTRAP="1" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "metadata" "--format-version" "1" "--no-deps" "--manifest-path" "/checkout/Cargo.toml"
---
Caused by:
  failed to parse manifest at `/checkout/src/doc/book/packages/mdbook-trpl-listing/Cargo.toml`

Caused by:
  error inheriting `clap` from workspace root manifest's `workspace.dependencies.clap`
Caused by:
  `workspace.dependencies` was not defined
thread 'main' panicked at src/core/metadata.rs:85:31:
command did not execute successfully: RUSTC_BOOTSTRAP="1" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "metadata" "--format-version" "1" "--no-deps" "--manifest-path" "/checkout/Cargo.toml"
---
Caused by:
  failed to parse manifest at `/checkout/src/doc/book/packages/mdbook-trpl-listing/Cargo.toml`

Caused by:
  error inheriting `clap` from workspace root manifest's `workspace.dependencies.clap`
Caused by:
  `workspace.dependencies` was not defined
thread 'main' panicked at src/core/metadata.rs:85:31:
command did not execute successfully: RUSTC_BOOTSTRAP="1" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "metadata" "--format-version" "1" "--no-deps" "--manifest-path" "/checkout/Cargo.toml"
---
Caused by:
  failed to parse manifest at `/checkout/src/doc/book/packages/mdbook-trpl-listing/Cargo.toml`

Caused by:
  error inheriting `clap` from workspace root manifest's `workspace.dependencies.clap`
Caused by:
  `workspace.dependencies` was not defined
thread 'main' panicked at src/core/metadata.rs:85:31:
command did not execute successfully: RUSTC_BOOTSTRAP="1" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "metadata" "--format-version" "1" "--no-deps" "--manifest-path" "/checkout/Cargo.toml"
```

</details>

2024-07-01 06:13 UTC, clarfonthey commented
That error is… very weird. I get it locally too, but not when I switch to the master branch, despite… nothing related being changed? I'm hoping it's a weird error that gets fixed and I can rebase on a newer commit that fixes it.

2024-07-01 12:57 UTC, ehuss commented
It looks like you updated all the submodules. You should amend your commit and remove those.

2024-07-01 14:47 UTC, clarfonthey commented
Huh, I had done a `git diff` but for some reason they didn't show up when I checked. I've fixed that.

2024-09-23 18:32 UTC, Dylan-DPC commented
@clarfonthey this still requires an ACP as per https://github.com/rust-lang/rust/pull/108193#issuecomment-1679199867 unless a member has suggested it's fine without one.

2024-10-16 01:45 UTC, clarfonthey commented
(FWIW, I haven't forgotten about that, and will begrudgingly file an ACP for it. I just haven't gotten around to it yet.)

2025-01-28 13:30 UTC, Dylan-DPC commented
@clarfonthey any updates on this acp? thanks

2025-01-29 01:15 UTC, clarfonthey commented
Thank you for the reminder. I think I'm just going to close this PR for now, but I will file the ACP within a few days. The code isn't super difficult to recreate and closing the PR doesn't delete it anyway, but, it would probably be best to open a new PR after ACP anyway.

2025-01-29 01:17 UTC, closed without merging