Add known-bug tests for a few I-unsound issues
rust-lang/rust pull request #108445
Opened 2023-02-25 06:36 UTC by gburgessiv

Just a few commits to push #105107 forward.

r? @jackh726

2023-02-25 17:08 UTC, a-hosani approved these changes

2023-02-25 19:32 UTC, compiler-errors commented
@bors r+ rollup

2023-02-25 20:48 UTC, jackh726 commented
@bors r- 

These tests aren't in the right place, and they should have comments.

2023-02-25 20:52 UTC, jackh726 requested changes
A comment in each test briefly saying these should fail and are currently unsound.

2023-02-25 20:52 UTC, jackh726 commented on tests/ui/specialization/issue-105787.rs
> +// check-pass
This isn't specialization. Maybe typeck?

2023-05-20 08:35 UTC, Dylan-DPC commented
@gburgessiv any updates on this? thanks

2023-10-01 03:57 UTC, JohnCSimon commented
@gburgessiv 

Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you are going to continue please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

2023-10-01 03:57 UTC, closed without merging