Introduce `Rc::into_inner`, as a parallel to `Arc::into_inner`
rust-lang/rust pull request #109026
Opened 2023-03-11 19:20 UTC by joshtriplett

Unlike `Arc`, `Rc` doesn't have the same race condition to avoid, but
maintaining an equivalent API still makes it easier to work with both
`Rc` and `Arc`.

2023-03-11 19:28 UTC, dtolnay requested changes

2023-03-11 19:28 UTC, dtolnay commented on library/alloc/src/rc/tests.rs
> +    assert_eq!(Arc::into_inner(x), Some(5));
```suggestion
    assert_eq!(Rc::into_inner(x), Some(5));
```

2023-03-11 20:46 UTC, joshtriplett commented on library/alloc/src/rc/tests.rs
> +    assert_eq!(Arc::into_inner(x), Some(5));
Argh, good catch, thank you.

2023-03-11 20:50 UTC, dtolnay approved these changes

2023-03-11 20:50 UTC, dtolnay commented
@bors r+

2023-03-12 07:12 UTC, matthiaskrgr commented
@bors r-  please r+ prs where CI is already failing... :upside_down_face:

2023-03-12 15:12 UTC, steffahn commented on library/alloc/src/rc/tests.rs
> +
```suggestion

```
One less newline will make the formatting tidy check happy :-)

2023-03-12 18:35 UTC, joshtriplett commented
@bors r=dtolnay

Thanks for the fix!

2023-03-12 23:27 UTC, merged

2023-03-13 10:37 UTC, steffahn commented
I just noticed that the `Rc::into_inner` defined in this PR introduced its own feature gate “`rc_into_inner`” instead of using “`arc_into_inner`”, too. Was that intentional?

2023-03-14 10:43 UTC, joshtriplett commented
On Mon, Mar 13, 2023 at 03:37:44AM -0700, Frank Steffahn wrote:
> I just noticed that the `Rc::into_inner` defined in this PR introduced its own feature gate “`rc_into_inner`” instead of using “`arc_into_inner`”, too. Was that intentional?

Yes, because I didn't want this PR to precommit to stabilizing
simultaneously.

2023-03-14 10:53 UTC, steffahn commented
Okay. So does that mean the stabilization FCP in the tracking issue is only concerned with `Arc::into_inner` or not? (Because that’s not completely clear to me, reading the statement “I think `Arc::into_inner` makes sense to stabilize at this point. And `Rc::into_inner` is trivial.”.)

And in any case, the tracking issue should perhaps be updated to mention `#![feature(rc_into_inner)]`, too then?

2023-03-14 11:00 UTC, steffahn commented
_(To readers via e-mail: There were some edits in my last response.)_

2023-03-16 04:00 UTC, joshtriplett commented
> maybe the argument is simply that this makes it easier to have the option to stabilize just one of them without needing to re-label the function’s feature flag?

Exactly.