Erase escaping late-bound regions when probing for ambiguous associated types
rust-lang/rust pull request #109102
Opened 2023-03-13 21:38 UTC by compiler-errors

Fixes #109090

2023-03-13 21:39 UTC, compiler-errors commented on compiler/rustc_hir_analysis/src/astconv/mod.rs
> +                                let universe = infcx.create_next_universe();
I guess we don't need to make a universe unless we need it, but also we're on the error path, so it doesn't matter here.

2023-03-16 09:59 UTC, davidtwco approved these changes
LGTM but someone else should take a look.

2023-03-16 10:00 UTC, davidtwco commented
r? rust-lang/types

2023-03-16 15:49 UTC, jackh726 requested changes
r=me with comment

2023-03-17 16:01 UTC, compiler-errors commented
@bors r=jackh726 rollup (diagnostics only)

2023-03-18 06:37 UTC, merged