QNX Neutrino: exponential backoff when fork/spawn needs a retry
rust-lang/rust pull request #109432
Opened 2023-03-21 06:51 UTC by flba-eb

Fixes #108594: When retrying, sleep with an exponential duration. When sleep duration is lower than minimum possible sleeping time, yield instead (this will not be often due to the exponential increase of duration).

Minimum possible sleeping time is determined using `libc::clock_getres` but only when spawn/fork failed the first time in a request. This could also be cached e.g. in a global atomic variable.

CC @gh-tr

r? @workingjubilee
@rustbot label +O-neutrino

2023-05-05 02:12 UTC, workingjubilee requested changes
Sorry about the long turnaround time, April was apparently not great for thinking.

2023-05-05 02:12 UTC, workingjubilee commented on library/std/src/sys/unix/process/process_unix.rs
> +            let mut minimum_delay = None;
Same thought as before, except clearly we should hoist the `static` up to be visible to both of these functions.

2023-05-05 02:12 UTC, workingjubilee commented on library/std/src/sys/unix/process/process_unix.rs
> +                continue;
I would like it if we still bailed for `ErrorKind::WouldBlock` or `ErrorKind::Interrupted` after a while, probably if we're getting up to actual seconds between yields.

2023-05-05 02:12 UTC, workingjubilee commented
@rustbot author

2023-06-02 12:58 UTC, flba-eb commented
Thank you very much @workingjubilee for the good feedback! I'm also a bit busy at the moment and will certainly not be able to work on it next week, but afterwards should be feasible.

2023-06-02 15:54 UTC, flba-eb commented
Requested changes have been implemented but should be tested before merging them. Branch is rebased; requested changes are in a separate commit to make the review easier.

2023-06-02 18:01 UTC, flba-eb commented
r? @workingjubilee
Requested changes are done and tested on QNX Neutrino.

2023-06-02 18:05 UTC, flba-eb commented
@rustbot review

2023-06-02 18:07 UTC, flba-eb commented
@workingjubilee What do you think about giving up after one second? Does it make sense to document this somewhere as QNX Neutrino specific behavior? Where?

2023-06-02 23:00 UTC, workingjubilee commented
Yeah, 1 second as the upper bar seems fine. If you wish to document it in the platform support (for now? maybe we should have a "platform quirks" page somewhere...) page, then go ahead. It's an unlikely circumstance, even under kernel stress, that I think having this surface in Rust programs as an unhandled "glitch" is fine, i.e. real programs usually won't hit this. **However**, I feel I should note that EAGAIN is actually specifically defined as a plausible POSIX error for [posix_spawn](https://pubs.opengroup.org/onlinepubs/007904975/functions/posix_spawn.html) due to it including "all the reasons fork/exec would fail", and [fork can EAGAIN](https://pubs.opengroup.org/onlinepubs/007904975/functions/fork.html).

2023-06-03 07:07 UTC, workingjubilee approved these changes

2023-06-03 07:23 UTC, workingjubilee commented
Given that, it might actually make more sense to document this as a possible error for _all_ platforms? But any changes for documenting spawn's errors for all platforms should be in another PR, and you might want to document it as specifically likely for Neutrino anyways.

r=me with the platform-specific note, or as-is.

@bors delegate=fiba-eb

2023-06-03 07:24 UTC, workingjubilee commented
???

@bors delegate=flba-eb

2023-06-03 08:17 UTC, flba-eb commented
Yes I think this should be documented in another PR. With this patch I wasn't able at all to reproduce the issue anymore (before the `ui` test suit always had 4-10 failures). As soon as we're sleeping the problem basically goes away. After thinking about it, I would not even mention it in [nto-qnx.md](https://github.com/rust-lang/rust/pull/109432/files#diff-ddffe8a46971c69f7101e84fa2f0d6b672da67e2d6b1a501212abd0b09080e2d) anymore. Would you agree?

2023-06-03 08:35 UTC, workingjubilee commented
Sure! Then let's go with this.

@bors r+

2023-06-03 13:00 UTC, merged

2023-06-03 14:16 UTC, rust-timer commented
Finished benchmarking commit (1e17cef9e29961636db63730784caea4b7d47ff5): [comparison URL](https://perf.rust-lang.org/compare.html?start=8177591aecf9c2ab1e96ba7fe2c00753f26a2011&end=1e17cef9e29961636db63730784caea4b7d47ff5&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=8177591aecf9c2ab1e96ba7fe2c00753f26a2011&end=1e17cef9e29961636db63730784caea4b7d47ff5&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=8177591aecf9c2ab1e96ba7fe2c00753f26a2011&end=1e17cef9e29961636db63730784caea4b7d47ff5&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 2.2% | [2.2%, 2.2%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=8177591aecf9c2ab1e96ba7fe2c00753f26a2011&end=1e17cef9e29961636db63730784caea4b7d47ff5&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -3.3% | [-4.3%, -1.3%] | 8     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -3.3% | [-4.3%, -1.3%] | 8     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=8177591aecf9c2ab1e96ba7fe2c00753f26a2011&end=1e17cef9e29961636db63730784caea4b7d47ff5&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 647.289s -> 647.076s (-0.03%)