Don't skip all directories when tidy-checking
rust-lang/rust pull request #109440
Opened 2023-03-21 11:48 UTC by WaffleLapkin

This fixes a regression from https://github.com/rust-lang/rust/pull/108772 which basically made it that tidy style checks only `README.md` and `COMPILER_TESTS.md`.

2023-03-21 13:13 UTC, jyn514 requested changes
Whoops, sorry 😅 good catch.

I don't think we need to pass `is_dir` into *every* check though, that calls `path.metadata` a lot more than it used to. It should be enough to call `path.is_dir` in the style check only.

2023-03-21 14:46 UTC, ozkanonur approved these changes
lgtm

2023-03-23 07:15 UTC, matthiaskrgr commented
@bors r- rollup=iffy
looks like more cleanup is needed now 

```
fmt check
tidy check
tidy: Skipping binary file check, read-only filesystem
Error: tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0080.md:19: line longer than 80 chars
Error: tidy error: /checkout/src/doc/unstable-book/src/compiler-flags/sanitizer.md:216: unexplained "```ignore" doctest; try one:

* make the test actually pass, by adding necessary imports and declarations, or
* use "```text", if the code is not Rust code, or
* use "```compile_fail,Ennnn", if the code is expected to fail at compile time, or
* use "```should_panic", if the code is expected to fail at run time, or
* use "```no_run", if the code should type-check but not necessary linkable/runnable, or
* explain it like "```ignore (cannot-test-this-because-xxxx)", if the annotation cannot be avoided.


Error: tidy error: /checkout/compiler/rustc_mir_build/src/build/expr/as_rvalue.rs:571: \
Use a single space after dots in comments.
Error: tidy error: /checkout/tests/ui/const-generics/generic_const_exprs/typeid-equality-by-subtyping.rs:20: trailing whitespace
```
https://github.com/rust-lang/rust/actions/runs/4497868288/jobs/7913878216#step:26:1777

https://github.com/rust-lang/rust/pull/109513

2023-03-23 11:17 UTC, WaffleLapkin commented
I've blessed tidy, but note that some PRs from #109513 are still not merged and conflict with this...

@bors r=jyn514,ozkanonur

2023-03-24 10:37 UTC, WaffleLapkin commented
This looks like a fluke
```text
[2958/3021] Linking CXX static library lib\libLLVMExegesisAArch64.a
FAILED: lib/libLLVMExegesisAArch64.a 
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E rm -f lib\libLLVMExegesisAArch64.a && C:\a\rust\rust\mingw32\bin\ar.exe qc lib\libLLVMExegesisAArch64.a  tools/llvm-exegesis/lib/AArch64/CMakeFiles/LLVMExegesisAArch64.dir/Target.cpp.obj && C:\a\rust\rust\mingw32\bin\ranlib.exe lib\libLLVMExegesisAArch64.a && cd ."
C:\a\rust\rust\mingw32\bin\ranlib.exe: could not create temporary file whilst writing archive: no more archived files

[2959/3021] Linking CXX static library lib\libLLVMExegesisX86.a
[2960/3021] Linking CXX executable bin\llvm-dwp.exe
lib/libLLVMM68kCodeGen.a(M68kCallLowering.cpp.obj): duplicate section `.rdata$_ZTVN4llvm16FormalArgHandlerE[__ZTVN4llvm16FormalArgHandlerE]' has different size

[2961/3021] Linking CXX executable bin\llvm-dwarfutil.exe
lib/libLLVMM68kCodeGen.a(M68kCallLowering.cpp.obj): duplicate section `.rdata$_ZTVN4llvm16FormalArgHandlerE[__ZTVN4llvm16FormalArgHandlerE]' has different size

ninja: build stopped: subcommand failed.
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1cd66030c949c28d\cmake-0.1.48\src\lib.rs:975:5
```
@bors retry

2023-03-24 11:55 UTC, rust-log-analyzer commented
The job **`x86_64-gnu`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/4509701836/jobs/7939783278) [(plain)](https://github.com/rust-lang-ci/rust/commit/0fa3f2220f21ffb8dce4e24ebc8895fc8ccf8997/checks/12247817865/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
[TIMING] tool::Tidy { compiler: Compiler { stage: 0, host: x86_64-unknown-linux-gnu }, target: x86_64-unknown-linux-gnu } -- 0.000
fmt check
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/compiler/rustc_codegen_ssa/src/back/linker.rs:1624: TODO is deprecated; use FIXME
##[error]tidy error: /checkout/compiler/rustc_mir_build/src/build/expr/as_rvalue.rs:571: \
Use a single space after dots in comments.
##[error]tidy error: /checkout/tests/ui/const-generics/generic_const_exprs/typeid-equality-by-subtyping.rs:20: trailing whitespace
some tidy checks failed
```

</details>

2023-03-24 14:35 UTC, rust-log-analyzer commented
The job **`i686-mingw-1`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/4510098100/jobs/7940655808) [(plain)](https://github.com/rust-lang-ci/rust/commit/c980793f5930fd62ae042db24f3cf7fd51c6964e/checks/12248932841/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
[2955/3021] Linking CXX executable bin\llvm-extract.exe
[2956/3021] Linking CXX executable bin\llvm-dwarfdump.exe
[2957/3021] Copying llvm-locstats into C:/a/rust/rust/build/i686-pc-windows-gnu/llvm/build/./bin
[2958/3021] Linking CXX static library lib\libLLVMExegesisAArch64.a
FAILED: lib/libLLVMExegesisAArch64.a 
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E rm -f lib\libLLVMExegesisAArch64.a && C:\a\rust\rust\mingw32\bin\ar.exe qc lib\libLLVMExegesisAArch64.a  tools/llvm-exegesis/lib/AArch64/CMakeFiles/LLVMExegesisAArch64.dir/Target.cpp.obj && C:\a\rust\rust\mingw32\bin\ranlib.exe lib\libLLVMExegesisAArch64.a && cd ."
C:\a\rust\rust\mingw32\bin\ranlib.exe: could not create temporary file whilst writing archive: no more archived files
[2959/3021] Linking CXX static library lib\libLLVMExegesisX86.a
[2960/3021] Linking CXX executable bin\llvm-dwp.exe
lib/libLLVMM68kCodeGen.a(M68kCallLowering.cpp.obj): duplicate section `.rdata$_ZTVN4llvm16FormalArgHandlerE[__ZTVN4llvm16FormalArgHandlerE]' has different size


[2961/3021] Linking CXX executable bin\llvm-dwarfutil.exe
lib/libLLVMM68kCodeGen.a(M68kCallLowering.cpp.obj): duplicate section `.rdata$_ZTVN4llvm16FormalArgHandlerE[__ZTVN4llvm16FormalArgHandlerE]' has different size

ninja: build stopped: subcommand failed.
command did not execute successfully, got: exit code: 1


build script failed, must exit now', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1cd66030c949c28d\cmake-0.1.48\src\lib.rs:975:5
 finished in 353.033 seconds
Build completed unsuccessfully in 0:08:18
Build completed unsuccessfully in 0:08:18
make: *** [Makefile:78: ci-mingw-subset-1] Error 1
```

</details>

2023-03-24 17:02 UTC, WaffleLapkin commented
@bors retry (tree is closed because of issues with CI, once the tree is reopened we should try merging this again...)

2023-03-24 17:18 UTC, rust-log-analyzer commented
A job failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/4511527390/jobs/7945420744) [(plain)](https://github.com/rust-lang-ci/rust/commit/3c1a388f0bfec010d65de577abd199c3a4cb22a0/checks/12255097102/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

```

</details>

2023-03-25 05:16 UTC, rust-log-analyzer commented
The job **`i686-mingw-1`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/4514200983/jobs/7950008950) [(plain)](https://github.com/rust-lang-ci/rust/commit/15cee581cb6b2078dcd19b8d44330f62e61e929d/checks/12261198190/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
[2557/3021] Building CXX object tools/llvm-ar/CMakeFiles/llvm-ar.dir/llvm-ar-driver.cpp.obj
[2558/3021] Linking CXX static library lib\libLLVMAnalysis.a
[2559/3021] Building CXX object tools/lto/CMakeFiles/LTO.dir/LTODisassembler.cpp.obj
[2560/3021] Linking CXX static library lib\libLLVMTransformUtils.a
FAILED: lib/libLLVMTransformUtils.a 
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E rm -f lib\libLLVMTransformUtils.a && C:\a\rust\rust\mingw32\bin\ar.exe qc lib\libLLVMTransformUtils.a  @CMakeFiles\LLVMTransformUtils.rsp && C:\a\rust\rust\mingw32\bin\ranlib.exe lib\libLLVMTransformUtils.a && cd ."
C:\a\rust\rust\mingw32\bin\ar.exe: could not create temporary file whilst writing archive: no more archived files
[2561/3021] Linking CXX static library lib\libLLVMBitWriter.a
[2562/3021] Building CXX object utils/yaml-bench/CMakeFiles/yaml-bench.dir/YAMLBench.cpp.obj
[2563/3021] Linking CXX executable bin\FileCheck.exe
[2564/3021] Linking CXX executable bin\llvm-PerfectShuffle.exe
[2564/3021] Linking CXX executable bin\llvm-PerfectShuffle.exe
[2565/3021] Building CXX object tools/llvm-config/CMakeFiles/llvm-config.dir/llvm-config.cpp.obj
[2566/3021] Building CXX object tools/lto/CMakeFiles/LTO.dir/lto.cpp.obj
[2567/3021] Building CXX object tools/llvm-ar/CMakeFiles/llvm-ar.dir/llvm-ar.cpp.obj
ninja: build stopped: subcommand failed.
command did not execute successfully, got: exit code: 1


build script failed, must exit now', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1cd66030c949c28d\cmake-0.1.48\src\lib.rs:975:5
 finished in 303.246 seconds
Build completed unsuccessfully in 0:07:27
Build completed unsuccessfully in 0:07:27
make: *** [Makefile:78: ci-mingw-subset-1] Error 1
```

</details>

2023-03-27 12:11 UTC, jyn514 commented
@bors retry

https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Repeated.20failures.20related.20to.20LLVM.20tools.3F

2023-03-27 20:04 UTC, jyn514 commented
@bors r- r+

retry means something different :( not sure why it didn't print the commit it was going to retry

2023-03-28 01:00 UTC, merged