resolve: Preserve reexport chains in `ModChild`ren
rust-lang/rust pull request #109500
Opened 2023-03-22 20:28 UTC by petrochenkov

This may be potentially useful for
- avoiding uses of `hir::ItemKind::Use`
- preserving documentation comments on all reexports, including those from other crates
- preserving and checking stability/deprecation info on reexports
- all kinds of diagnostics

The second comment then migrates some hacky logic from rustdoc to `module_reexports` to make it simpler and more correct.

2023-03-22 20:29 UTC, petrochenkov commented
@bors try @rust-timer queue

2023-03-22 20:29 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2023-03-22 20:29 UTC, petrochenkov commented
cc @GuillaumeGomez

2023-03-22 22:24 UTC, rust-timer commented
Queued 7a2e02ca3818248e22d3a4b9735822679c02374f with parent 439292bc7913399e406d9bb7e8da0f70c6317c6e, future [comparison URL](https://perf.rust-lang.org/compare.html?start=439292bc7913399e406d9bb7e8da0f70c6317c6e&end=7a2e02ca3818248e22d3a4b9735822679c02374f).
<!-- rust-timer: temporary -->

2023-03-22 22:41 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-14`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/4494194763/jobs/7906373178) [(plain)](https://github.com/rust-lang/rust/commit/c3fc1061cc50992cc89e06dc3588a799abc6d576/checks/12204282524/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:24cb9080177205b6e8c946b17badbe402adc938f)
Download action repository 'rust-lang/simpleinfra@master' (SHA:5f3e9487b084c5235556ffd8baa8b183de9eb120)
Complete job name: PR (x86_64-gnu-llvm-14, false, ubuntu-20.04-16core-64gb)
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  CI_JOB_NAME: x86_64-gnu-llvm-14
---
Rustbook (x86_64-unknown-linux-gnu) - edition-guide
Rustbook (x86_64-unknown-linux-gnu) - style-guide
Building tool linkchecker (stage0)
    Finished release [optimized] target(s) in 0.13s
std/hash/struct.BuildHasherDefault.html:7: broken link - `std/collections/struct.HashMap.html`
std/hash/struct.BuildHasherDefault.html:8: broken link - `std/collections/struct.HashSet.html`
std/hash/struct.BuildHasherDefault.html:12: broken link - `std/collections/struct.HashMap.html`
std/hash/trait.BuildHasher.html:13: broken link - `std/collections/struct.HashMap.html`
std/hash/index.html:3: broken link - `std/collections/struct.HashMap.html`
std/hash/index.html:3: broken link - `std/collections/struct.HashSet.html`
std/hash/trait.Hash.html:46: broken link - `std/collections/struct.HashMap.html`
std/hash/trait.Hash.html:46: broken link - `std/collections/struct.HashSet.html`
std/mem/fn.needs_drop.html:18: broken link - `std/collections/struct.HashMap.html`
std/iter/index.html:193: broken link - `std/collections/struct.HashSet.html`
std/borrow/trait.Borrow.html:37: broken link - `std/collections/struct.HashMap.html`
alloc/borrow/trait.Borrow.html:37: broken link - `std/collections/struct.HashMap.html`
core/hash/struct.BuildHasherDefault.html:7: broken link - `std/collections/struct.HashMap.html`
core/hash/struct.BuildHasherDefault.html:8: broken link - `std/collections/struct.HashSet.html`
core/hash/struct.BuildHasherDefault.html:12: broken link - `std/collections/struct.HashMap.html`
core/hash/trait.BuildHasher.html:12: broken link - `std/collections/struct.HashMap.html`
core/hash/index.html:3: broken link - `std/collections/struct.HashMap.html`
core/hash/index.html:3: broken link - `std/collections/struct.HashSet.html`
core/hash/trait.Hash.html:44: broken link - `std/collections/struct.HashMap.html`
core/hash/trait.Hash.html:44: broken link - `std/collections/struct.HashSet.html`
core/mem/fn.needs_drop.html:17: broken link - `std/collections/struct.HashMap.html`
core/iter/index.html:193: broken link - `std/collections/struct.HashSet.html`
core/borrow/trait.Borrow.html:36: broken link - `std/collections/struct.HashMap.html`
number of HTML files scanned: 33508
number of HTML redirects found: 10252
number of links checked: 2959048
number of links ignored due to external: 96936
```

</details>

2023-03-23 10:13 UTC, rust-timer commented
Finished benchmarking commit (7a2e02ca3818248e22d3a4b9735822679c02374f): [comparison URL](https://perf.rust-lang.org/compare.html?start=439292bc7913399e406d9bb7e8da0f70c6317c6e&end=7a2e02ca3818248e22d3a4b9735822679c02374f&stat=instructions:u).

### Overall result: ❌✅ regressions and improvements - ACTION NEEDED


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: -S-waiting-on-perf +perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=439292bc7913399e406d9bb7e8da0f70c6317c6e&end=7a2e02ca3818248e22d3a4b9735822679c02374f&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.9%  | [0.5%, 1.2%]   | 10    |
| Regressions ❌ <br /> (secondary)  | 2.5%  | [0.4%, 5.9%]   | 7     |
| Improvements ✅ <br /> (primary)   | -0.7% | [-0.7%, -0.6%] | 2     |
| Improvements ✅ <br /> (secondary) | -0.4% | [-0.7%, -0.3%] | 4     |
| All ❌✅ (primary)                 | 0.6%  | [-0.7%, 1.2%]  | 12    |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=439292bc7913399e406d9bb7e8da0f70c6317c6e&end=7a2e02ca3818248e22d3a4b9735822679c02374f&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 3.9%  | [3.9%, 3.9%]   | 1     |
| Regressions ❌ <br /> (secondary)  | 2.2%  | [0.5%, 5.4%]   | 17    |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -1.4% | [-1.5%, -1.3%] | 2     |
| All ❌✅ (primary)                 | 3.9%  | [3.9%, 3.9%]   | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=439292bc7913399e406d9bb7e8da0f70c6317c6e&end=7a2e02ca3818248e22d3a4b9735822679c02374f&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 2.5% | [0.9%, 5.4%] | 7     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

2023-03-23 14:42 UTC, petrochenkov commented
The second commit shows some motivation for the first commit, but otherwise they are not related and I can split this PR into two for reviewing by different people if necessary.

2023-03-23 15:49 UTC, petrochenkov commented
@notriddle 
>Can you construct a test case that triggers one of these new warnings?

The warnings are not new, they are existing, they are just heavily using `module_children` for traversing the whole crate tree, and `module_children` just got more expensive due to the new field in `ModChild`.

2023-03-28 12:54 UTC, GuillaumeGomez approved these changes

2023-03-28 12:54 UTC, GuillaumeGomez commented
Looks good to me but still need approval from someone on the compiler team.

2023-04-02 11:21 UTC, oli-obk requested changes

2023-04-02 11:21 UTC, oli-obk commented on compiler/rustc_resolve/src/imports.rs
> +                        reexports: reexport_chain,
maybe name the field `reexport_chain`, while the docs clarify it, the field can just have that name, too

2023-04-02 11:21 UTC, oli-obk commented on src/librustdoc/clean/mod.rs
> +    for child in tcx.module_reexports(tcx.local_parent(import_def_id)).unwrap_or_default() {
side note: `module_reexports` should probably do the unwrap_or_default inside and not return an `Option<&[T]>`, but that's very orthogonal to this PR

2023-04-03 14:06 UTC, petrochenkov commented on compiler/rustc_middle/src/metadata.rs
> +pub enum Reexport {
No!
Those are `DefId`s of the `use` and `extern crate` items themselves, not their targets, that's the point.
So we can query attributes, spans, etc of those import items.
I'll add the docs.

2023-04-07 16:49 UTC, petrochenkov commented
@rustbot ready

2023-04-07 18:17 UTC, notriddle approved these changes

2023-04-09 12:28 UTC, oli-obk approved these changes

2023-04-09 12:32 UTC, oli-obk commented
@bors r+ rollup=never

About perf: This regresses a few test cases because there's a bit more rustdoc metadata in our metadata files and that just needs a bit more time to decode. These changes are needed to fix ICEs in rustdoc, which is why I'm landing it tregardless of the perf regressions. We should evaluate how to avoid regressions from rustdoc-specific metadata in general and not on an individual PR basis.

2023-04-09 15:25 UTC, merged

2023-04-09 17:00 UTC, rust-timer commented
Finished benchmarking commit (7201301df6afe8b68c6a8f5d2abba67bbba435ea): [comparison URL](https://perf.rust-lang.org/compare.html?start=56e0626836d92973cd12cb505179eef9795efc61&end=7201301df6afe8b68c6a8f5d2abba67bbba435ea&stat=instructions:u).

### Overall result: ❌ regressions - ACTION NEEDED


**Next Steps**: If you can justify the regressions found in this perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please open an issue or create a new PR that fixes the regressions, add a comment linking to the newly created issue or PR, and then add the `perf-regression-triaged` label to this PR.

@rustbot label: +perf-regression
cc @rust-lang/wg-compiler-performance



### [Instruction count](https://perf.rust-lang.org/compare.html?start=56e0626836d92973cd12cb505179eef9795efc61&end=7201301df6afe8b68c6a8f5d2abba67bbba435ea&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.7% | [0.4%, 1.0%] | 17    |
| Regressions ❌ <br /> (secondary)  | 1.3% | [0.4%, 5.7%] | 22    |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 0.7% | [0.4%, 1.0%] | 17    |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=56e0626836d92973cd12cb505179eef9795efc61&end=7201301df6afe8b68c6a8f5d2abba67bbba435ea&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | 3.3%  | [1.4%, 7.7%]   | 12    |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -2.5% | [-3.8%, -1.5%] | 6     |
| All ❌✅ (primary)                 | -     | -              | 0     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=56e0626836d92973cd12cb505179eef9795efc61&end=7201301df6afe8b68c6a8f5d2abba67bbba435ea&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 3.1% | [1.0%, 5.1%] | 5     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

2023-04-19 07:48 UTC, rylev commented
There are a few more regressions in the post merge perf run, but they seem to follow the same pattern as the regressions found pre-merge. I think we can just take this as a necessary trade off we need to make for the fixes that landed (as identified by @oli-obk [here](https://github.com/rust-lang/rust/pull/109500#issuecomment-1501119286)).

2023-04-19 12:21 UTC, petrochenkov commented
These perf regressions were partially mitigated by https://github.com/rust-lang/rust/pull/109772.