Give `Span` a niche
rust-lang/rust pull request #109890
Opened 2023-04-03 13:04 UTC by Nilstrieb

2023-04-03 13:05 UTC, Nilstrieb commented
@bors try @rust-timer queue

2023-04-03 13:05 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2023-04-03 15:06 UTC, rust-timer commented
Queued fda869d19d0ff250e63d951f0b7d8fa3aad33384 with parent 932c173ca1b7a79c1005e2d72ddfa505a7bf2cfa, future [comparison URL](https://perf.rust-lang.org/compare.html?start=932c173ca1b7a79c1005e2d72ddfa505a7bf2cfa&end=fda869d19d0ff250e63d951f0b7d8fa3aad33384).
<!-- rust-timer: temporary -->

2023-04-03 18:01 UTC, Nilstrieb commented
Hmm, a little unsure about the regressions. Some are clearly noise like deep-vector, which regressed inside LLVM GVN). But the primary benchmarks look more legit.
`unicode-normalization`
```
1,562,628  ???:rustc_interface::callbacks::track_span_parent
  920,569  ???:<rustc_parse::lexer::StringReader>::next_token
  755,569  ???:<rustc_span::span_encoding::Span as rustc_serialize::serialize::Decodable<rustc_query_impl::on_disk_cache::CacheDecoder>>::decode
  509,229  ???:<[rustc_middle::mir::LocalDecl] as rustc_serialize::serialize::Encodable<rustc_metadata::rmeta::encoder::EncodeContext>>::encode
```
`html5ever`
```
5,880,836  ???:<rustc_expand::mbe::macro_parser::TtParser>::parse_tt::<rustc_expand::mbe::macro_rules::NoopTracker>
 -651,950  ???:<alloc::rc::Rc<alloc::vec::Vec<rustc_ast::tokenstream::TokenTree>> as core::ops::drop::Drop>::drop
  542,201  ???:<rustc_parse::lexer::StringReader>::next_token
  490,341  ???:<alloc::vec::Vec<rustc_ast::tokenstream::TokenTree> as core::ops::drop::Drop>::drop
  242,679  ???:rustc_expand::mbe::transcribe::transcribe
```

All of these functions use `Span::new`. Did that function get significantly slower because of the check. There is only one way to find out whether that really is the problem and whether it may be worth it to investigate this further and making more things use `NonMaxU32` to avoid the check. By... dropping it for a perf run. I don't think any test files have a size of 4GB^^

2023-04-03 18:04 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2023-04-03 20:33 UTC, BoxyUwU requested changes

2023-04-03 20:33 UTC, BoxyUwU commented on compiler/rustc_span/src/span_encoding.rs
>          if len <= MAX_LEN && ctxt2 <= MAX_CTXT {
I think this is unsound, we don't check for the size before creating the nonmaxu32

2023-04-03 23:01 UTC, eholk commented
Marking as awaiting on author while it's a draft.

@rustbot author

2023-04-04 02:41 UTC, rust-timer commented
Finished benchmarking commit (5b79052f755f161b491a70317f80305bec4892da): [comparison URL](https://perf.rust-lang.org/compare.html?start=17675855094906ba90aca2f119be8fb7afc4d456&end=5b79052f755f161b491a70317f80305bec4892da&stat=instructions:u).

### Overall result: ❌✅ regressions and improvements - no action needed


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

@bors rollup=never
@rustbot label: -S-waiting-on-perf -perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=17675855094906ba90aca2f119be8fb7afc4d456&end=5b79052f755f161b491a70317f80305bec4892da&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | 0.4%  | [0.3%, 0.6%]   | 7     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -0.2% | [-0.2%, -0.2%] | 1     |
| All ❌✅ (primary)                 | -     | -              | 0     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=17675855094906ba90aca2f119be8fb7afc4d456&end=5b79052f755f161b491a70317f80305bec4892da&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.4%  | [0.9%, 2.0%]   | 2     |
| Regressions ❌ <br /> (secondary)  | 2.1%  | [1.1%, 3.2%]   | 4     |
| Improvements ✅ <br /> (primary)   | -2.8% | [-2.8%, -2.8%] | 1     |
| Improvements ✅ <br /> (secondary) | -3.5% | [-3.5%, -3.5%] | 1     |
| All ❌✅ (primary)                 | 0.0%  | [-2.8%, 2.0%]  | 3     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=17675855094906ba90aca2f119be8fb7afc4d456&end=5b79052f755f161b491a70317f80305bec4892da&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.0% | [1.0%, 1.0%] | 1     |
| Regressions ❌ <br /> (secondary)  | 2.1% | [0.9%, 3.3%] | 2     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 1.0% | [1.0%, 1.0%] | 1     |
</details>

2023-04-16 14:59 UTC, Nilstrieb commented
this is a regression because of the additional branch needed. we'd need to use a niched type throughout the relevant code to try making it not a regression, which takes a little effort. I'll try to do that at some point, but I'll put this on hold for now.

2024-03-14 13:16 UTC, Dylan-DPC commented
Closing this as inactive. Feel free to reöpen this pr or create a new pr if you get the time to work on this. Thanks

2024-03-14 13:16 UTC, closed without merging