make sysroot finding compatible with multiarch systems
rust-lang/rust pull request #110281
Opened 2023-04-13 11:49 UTC by ozkanonur

resolves #109994

2023-04-14 02:53 UTC, est31 commented
@rustbot label +beta-nominated

2023-04-14 11:16 UTC, est31 requested changes

2023-04-14 11:16 UTC, est31 commented on compiler/rustc_session/src/filesearch.rs
> +                .expect(&format!(
IMO this should be changed to `ok_or_else` and then one can use `?` at the end.

2023-04-14 11:16 UTC, est31 commented on compiler/rustc_session/src/filesearch.rs
> +                .expect(&format!("Could not move to parent path of {}", sysroot_dir.display()));
Same here

2023-04-16 18:52 UTC, jackh726 commented
Any way we can write a test?

2023-04-16 21:30 UTC, ozkanonur commented
> Any way we can write a test?

The best way of testing this is having multiarch linux as CI runner(which I think we should have, just like having windows, mac and bsd runners cc @jyn514) which builds the compiler and runs the tests. Anything other than would be supper annoying hacks.

2023-04-16 21:35 UTC, jyn514 commented
cc https://github.com/rust-lang/rust/issues/102563

2023-04-23 17:01 UTC, jackh726 commented
@bors r+ rollup=never

(Given this doesn't have a test, I'm going to make sure we can bisect easily)

2023-04-23 20:20 UTC, merged

2023-04-23 21:37 UTC, rust-timer commented
Finished benchmarking commit (7f94b314cead7059a71a265a8b64905ef2511796): [comparison URL](https://perf.rust-lang.org/compare.html?start=915aa06700af4a2363639bae70201cd7387470ad&end=7f94b314cead7059a71a265a8b64905ef2511796&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=915aa06700af4a2363639bae70201cd7387470ad&end=7f94b314cead7059a71a265a8b64905ef2511796&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=915aa06700af4a2363639bae70201cd7387470ad&end=7f94b314cead7059a71a265a8b64905ef2511796&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 4.2%  | [4.2%, 4.2%]   | 1     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -1.2% | [-1.2%, -1.2%] | 1     |
| All ❌✅ (primary)                 | 4.2%  | [4.2%, 4.2%]   | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=915aa06700af4a2363639bae70201cd7387470ad&end=7f94b314cead7059a71a265a8b64905ef2511796&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | 2.5%  | [2.0%, 3.1%]   | 2     |
| Improvements ✅ <br /> (primary)   | -2.5% | [-2.5%, -2.5%] | 1     |
| Improvements ✅ <br /> (secondary) | -2.8% | [-2.8%, -2.8%] | 1     |
| All ❌✅ (primary)                 | -2.5% | [-2.5%, -2.5%] | 1     |
</details>

2023-04-27 14:19 UTC, apiraino commented
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-04-27/near/353314738)

@rustbot label +beta-accepted