fix: change curl args from `--retry` to `--retry-all-errors`
rust-lang/rust pull request #110245
Opened 2023-04-12 17:25 UTC by kayagokalp

closes #110178.

2023-04-12 18:55 UTC, ozkanonur requested changes
Thanks for the PR!

`--retry-all-errors` should be an extra argument with keeping `--retry` as it is. Otherwise curl will hang the downloading processes until the timeout.

e.g:
![2023-04-12_21-52](https://user-images.githubusercontent.com/39852038/231556647-40fa964d-552c-4733-980f-aada860d5520.png)

2023-04-12 18:55 UTC, ozkanonur commented
@rustbot author

2023-04-12 20:18 UTC, kayagokalp commented
@rustbot label -S-waiting-on-author +S-waiting-on-review

2023-04-12 21:34 UTC, ozkanonur commented
this lgtm, once you squash your commits, we can merge the PR

2023-04-12 22:23 UTC, kayagokalp commented
@rustbot ready

2023-04-12 23:01 UTC, ozkanonur commented
@bors r+ rollup

2023-04-13 09:20 UTC, matthiaskrgr commented
@bors r- 
failed in a rollup
https://github.com/rust-lang/rust/pull/110271

2023-04-13 09:22 UTC, klensy commented
Looks like `--retry-all-errors` supported from [curl 7.71.0](https://daniel.haxx.se/blog/2020/06/24/curl-7-71-0-blobs-and-retries/) and some runners older than that?

2023-04-13 12:07 UTC, ozkanonur commented
> Looks like `--retry-all-errors` supported from [curl 7.71.0](https://daniel.haxx.se/blog/2020/06/24/curl-7-71-0-blobs-and-retries/) and some runners older than that?
> 
> ubuntu 20.04 image uses curl 7.68 https://packages.ubuntu.com/focal/curl

Yeah seems like `--retry-all-errors` flag shipped very recently.

@kayagokalp Can you replace the `--retry-all-errors` flag with `--retry-connrefused` and update commit message/PR description? `--retry-connrefused` added since v7.52.0, which should work on any CI/local machine.

2023-04-13 12:25 UTC, kayagokalp commented
@rustbot ready

2023-04-13 12:25 UTC, ozkanonur commented on src/bootstrap/bootstrap.py
> +                "--retry", "3", "--retry-connrefused" ,"-Sf", url],
```suggestion
                "--retry", "3", "--retry-connrefused", "-Sf", url],
```

2023-04-14 05:58 UTC, matthiaskrgr commented
@bors r- rollup=iffy still failing

2023-04-14 08:13 UTC, klensy commented
centos 7 image have curl 7.29 :-(. It's easier to download our own version and install/build it.

2023-04-14 11:06 UTC, ozkanonur commented
> centos 7 image have curl 7.29 :-(.

7.52 released in 2016, I was pretty sure that we have more recent version...

"curl version 7.29. 0 was released on February 6 2013." :(

> It's easier to download our own version and install/build it.

Doing custom build or installation just for couple new arguments, it doesn't really seem worth to me.

cc @jyn514

2023-04-14 11:06 UTC, ozkanonur commented
@rustbot blocked

2023-04-14 16:36 UTC, jyn514 commented
> Doing custom build or installation just for couple new arguments, it doesn't really seem worth to me.

i agree. instead we can put the retry logic in Rust (and make sure not to retry if it's a 404).

2023-04-20 20:45 UTC, kayagokalp commented
Going to close this for now, and re ignite once I got some time again if no one beats mo to it!

2023-04-20 20:45 UTC, closed without merging