Strict region folders
rust-lang/rust pull request #110312
Opened 2023-04-14 06:40 UTC by nnethercote

Some region folders expect certain region variants to never occur. Other region folders handle all region variants. I was wondering if we could be stricter. So I tried changing every region folder to not accept any variants, and then gradually allowed variants until the full test suite passed.

The results are less enlightening than I'd hoped. I was expecting to see some common patterns but there aren't any, there is no consistency at all. I'm ambivalent about whether this should be merged, but I figure it's worth showing others. If we do merge it, we should probably do a crater run first to flush out any edge cases not covered by the test suite.

r? @oli-obk

2023-04-14 06:56 UTC, compiler-errors commented
> If we do merge it, we should probably do a crater run first to flush out any edge cases not covered by the test suite.

This is insufficient, IMO. I assume most of these bug cases are going to be triggered not in good-path code, but on subtle combinations of bad-path code.

Anyways, I'll take a look at this tomorrow and try to find ways of triggering some of these bugs, or at least I can leave inline comments for the ones that confidently can remain stronger assertions.

2023-04-14 14:49 UTC, jackh726 commented
> This is insufficient, IMO. I assume most of these bug cases are going to be triggered not in good-path code, but on subtle combinations of bad-path code.

What exactly is the argument here? One argument should be that we gracefully handle "invalid" state, with the expectation that we catch it later. But a counter argument is that we should detect that state *early* (even if we just delay the bug).

2023-04-14 14:59 UTC, compiler-errors commented
@jackh726:

> What exactly is the argument here?

The argument is that I don't think that we should be unnecessarily introducing ICEs into the compiler, even on failed compilation sessions, so I don't think we should land this without more testing than just crater. I just don't want to see "Let's land this now and see what ICEs people file later". For example, a UI-test-guided approach is insufficient because this isn't exercising, e.g., every combination of parser recovery that ends up causing us to generate `ReError` and other region errors.

End users are frustrated when their already messed up code ends up ICEing due to far-too-strict assertions just like this PR is introducing, especially since the PR description above mentions that the changes here aren't even particularly compelling because there aren't general patterns in the choices of lifetimes that each fold method is supposed to support.

2023-04-14 15:02 UTC, compiler-errors commented
> One argument should be that we gracefully handle "invalid" state, with the expectation that we catch it later. But a counter argument is that we should detect that state early (even if we just delay the bug).

A handful of these folders are happening in diagnostics code anyways, so it's not worthwhile delaying an additional bug when we're already constructing a diagnostic.

Also, `ReError` should never bug IMO. It already carries an `ErrorGuaranteed`, and since the compilation session is doomed, it should be handled everywhere. We've already had more than a few ICEs filed by @matthiaskrgr since `ReError` was introduced that have been due to matches that were `bug!()`ing on `ReError`.

2023-04-14 17:34 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/4697119848/jobs/8327846242) [(plain)](https://github.com/rust-lang/rust/commit/043c1dee8e4cfd42c5c5743157d045c355ed6a30/checks/12743372586/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

---- compile_test stdout ----
diff of stderr:

 error: the following explicit lifetimes could be elided: 'a, 'b
   --> $DIR/needless_lifetimes.rs:18:1
    |
 LL | fn distinct_lifetimes<'a, 'b>(_x: &'a u8, _y: &'b u8, _z: u8) {}
    |
    |
    = note: `-D clippy::needless-lifetimes` implied by `-D warnings`
 help: elide the lifetimes
    |
 LL - fn distinct_lifetimes<'a, 'b>(_x: &'a u8, _y: &'b u8, _z: u8) {}
 LL + fn distinct_lifetimes(_x: &u8, _y: &u8, _z: u8) {}
 
 
 error: the following explicit lifetimes could be elided: 'a, 'b
   --> $DIR/needless_lifetimes.rs:20:1
    |
    |
 LL | fn distinct_and_static<'a, 'b>(_x: &'a u8, _y: &'b u8, _z: &'static u8) {}
    |
 help: elide the lifetimes
    |
    |
 LL - fn distinct_and_static<'a, 'b>(_x: &'a u8, _y: &'b u8, _z: &'static u8) {}
 LL + fn distinct_and_static(_x: &u8, _y: &u8, _z: &'static u8) {}
 
 
 error: the following explicit lifetimes could be elided: 'a
   --> $DIR/needless_lifetimes.rs:30:1
    |
 LL | fn in_and_out<'a>(x: &'a u8, _y: u8) -> &'a u8 {
    |
 help: elide the lifetimes
    |
    |
 LL - fn in_and_out<'a>(x: &'a u8, _y: u8) -> &'a u8 {
 LL + fn in_and_out(x: &u8, _y: u8) -> &u8 {
 
 
 error: the following explicit lifetimes could be elided: 'b
   --> $DIR/needless_lifetimes.rs:42:1
    |
 LL | fn multiple_in_and_out_2a<'a, 'b>(x: &'a u8, _y: &'b u8) -> &'a u8 {
    |
 help: elide the lifetimes
    |
    |
 LL - fn multiple_in_and_out_2a<'a, 'b>(x: &'a u8, _y: &'b u8) -> &'a u8 {
 LL + fn multiple_in_and_out_2a<'a>(x: &'a u8, _y: &u8) -> &'a u8 {
 
 
 error: the following explicit lifetimes could be elided: 'a
   --> $DIR/needless_lifetimes.rs:49:1
    |
 LL | fn multiple_in_and_out_2b<'a, 'b>(_x: &'a u8, y: &'b u8) -> &'b u8 {
    |
 help: elide the lifetimes
    |
    |
 LL - fn multiple_in_and_out_2b<'a, 'b>(_x: &'a u8, y: &'b u8) -> &'b u8 {
 LL + fn multiple_in_and_out_2b<'b>(_x: &u8, y: &'b u8) -> &'b u8 {
 
 
 error: the following explicit lifetimes could be elided: 'b
   --> $DIR/needless_lifetimes.rs:66:1
    |
 LL | fn deep_reference_1a<'a, 'b>(x: &'a u8, _y: &'b u8) -> Result<&'a u8, ()> {
    |
 help: elide the lifetimes
    |
    |
 LL - fn deep_reference_1a<'a, 'b>(x: &'a u8, _y: &'b u8) -> Result<&'a u8, ()> {
 LL + fn deep_reference_1a<'a>(x: &'a u8, _y: &u8) -> Result<&'a u8, ()> {
 
 
 error: the following explicit lifetimes could be elided: 'a
   --> $DIR/needless_lifetimes.rs:73:1
    |
 LL | fn deep_reference_1b<'a, 'b>(_x: &'a u8, y: &'b u8) -> Result<&'b u8, ()> {
    |
 help: elide the lifetimes
    |
    |
 LL - fn deep_reference_1b<'a, 'b>(_x: &'a u8, y: &'b u8) -> Result<&'b u8, ()> {
 LL + fn deep_reference_1b<'b>(_x: &u8, y: &'b u8) -> Result<&'b u8, ()> {
 
 
 error: the following explicit lifetimes could be elided: 'a
   --> $DIR/needless_lifetimes.rs:82:1
    |
 LL | fn deep_reference_3<'a>(x: &'a u8, _y: u8) -> Result<&'a u8, ()> {
    |
 help: elide the lifetimes
    |
    |
 LL - fn deep_reference_3<'a>(x: &'a u8, _y: u8) -> Result<&'a u8, ()> {
 LL + fn deep_reference_3(x: &u8, _y: u8) -> Result<&u8, ()> {
 
 
 error: the following explicit lifetimes could be elided: 'a
   --> $DIR/needless_lifetimes.rs:87:1
    |
 LL | fn where_clause_without_lt<'a, T>(x: &'a u8, _y: u8) -> Result<&'a u8, ()>
    |
 help: elide the lifetimes
    |
    |
 LL - fn where_clause_without_lt<'a, T>(x: &'a u8, _y: u8) -> Result<&'a u8, ()>
 LL + fn where_clause_without_lt<T>(x: &u8, _y: u8) -> Result<&u8, ()>
 
 
 error: the following explicit lifetimes could be elided: 'a, 'b
   --> $DIR/needless_lifetimes.rs:99:1
    |
 LL | fn lifetime_param_2<'a, 'b>(_x: Ref<'a>, _y: &'b u8) {}
    |
 help: elide the lifetimes
    |
    |
 LL - fn lifetime_param_2<'a, 'b>(_x: Ref<'a>, _y: &'b u8) {}
 LL + fn lifetime_param_2(_x: Ref<'_>, _y: &u8) {}
 
 
 error: the following explicit lifetimes could be elided: 'a
   --> $DIR/needless_lifetimes.rs:123:1
    |
 LL | fn fn_bound_2<'a, F, I>(_m: Lt<'a, I>, _f: F) -> Lt<'a, I>
    |
 help: elide the lifetimes
    |
    |
 LL - fn fn_bound_2<'a, F, I>(_m: Lt<'a, I>, _f: F) -> Lt<'a, I>
 LL + fn fn_bound_2<F, I>(_m: Lt<'_, I>, _f: F) -> Lt<'_, I>
 
 
 error: the following explicit lifetimes could be elided: 's
   --> $DIR/needless_lifetimes.rs:153:5
    |
 LL |     fn self_and_out<'s>(&'s self) -> &'s u8 {
    |
 help: elide the lifetimes
    |
    |
 LL -     fn self_and_out<'s>(&'s self) -> &'s u8 {
 LL +     fn self_and_out(&self) -> &u8 {
 
 
 error: the following explicit lifetimes could be elided: 't
   --> $DIR/needless_lifetimes.rs:160:5
    |
 LL |     fn self_and_in_out_1<'s, 't>(&'s self, _x: &'t u8) -> &'s u8 {
    |
 help: elide the lifetimes
    |
    |
 LL -     fn self_and_in_out_1<'s, 't>(&'s self, _x: &'t u8) -> &'s u8 {
 LL +     fn self_and_in_out_1<'s>(&'s self, _x: &u8) -> &'s u8 {
 
 
 error: the following explicit lifetimes could be elided: 's
   --> $DIR/needless_lifetimes.rs:167:5
    |
 LL |     fn self_and_in_out_2<'s, 't>(&'s self, x: &'t u8) -> &'t u8 {
    |
 help: elide the lifetimes
    |
    |
 LL -     fn self_and_in_out_2<'s, 't>(&'s self, x: &'t u8) -> &'t u8 {
 LL +     fn self_and_in_out_2<'t>(&self, x: &'t u8) -> &'t u8 {
 
 
 error: the following explicit lifetimes could be elided: 's, 't
   --> $DIR/needless_lifetimes.rs:171:5
    |
 LL |     fn distinct_self_and_in<'s, 't>(&'s self, _x: &'t u8) {}
    |
 help: elide the lifetimes
    |
    |
 LL -     fn distinct_self_and_in<'s, 't>(&'s self, _x: &'t u8) {}
 LL +     fn distinct_self_and_in(&self, _x: &u8) {}
 
 
 error: the following explicit lifetimes could be elided: 'a
   --> $DIR/needless_lifetimes.rs:190:1
    |
 LL | fn struct_with_lt<'a>(_foo: Foo<'a>) -> &'a str {
    |
 help: elide the lifetimes
    |
    |
 LL - fn struct_with_lt<'a>(_foo: Foo<'a>) -> &'a str {
 LL + fn struct_with_lt(_foo: Foo<'_>) -> &str {
 
 
 error: the following explicit lifetimes could be elided: 'b
   --> $DIR/needless_lifetimes.rs:208:1
    |
 LL | fn struct_with_lt4a<'a, 'b>(_foo: &'a Foo<'b>) -> &'a str {
    |
 help: elide the lifetimes
    |
    |
 LL - fn struct_with_lt4a<'a, 'b>(_foo: &'a Foo<'b>) -> &'a str {
 LL + fn struct_with_lt4a<'a>(_foo: &'a Foo<'_>) -> &'a str {
 
 
 error: the following explicit lifetimes could be elided: 'a
   --> $DIR/needless_lifetimes.rs:216:1
    |
 LL | fn struct_with_lt4b<'a, 'b>(_foo: &'a Foo<'b>) -> &'b str {
    |
 help: elide the lifetimes
    |
    |
 LL - fn struct_with_lt4b<'a, 'b>(_foo: &'a Foo<'b>) -> &'b str {
 LL + fn struct_with_lt4b<'b>(_foo: &Foo<'b>) -> &'b str {
 
 
 error: the following explicit lifetimes could be elided: 'a
   --> $DIR/needless_lifetimes.rs:231:1
    |
 LL | fn trait_obj_elided2<'a>(_arg: &'a dyn Drop) -> &'a str {
    |
 help: elide the lifetimes
    |
    |
 LL - fn trait_obj_elided2<'a>(_arg: &'a dyn Drop) -> &'a str {
 LL + fn trait_obj_elided2(_arg: &dyn Drop) -> &str {
 
 
 error: the following explicit lifetimes could be elided: 'a
   --> $DIR/needless_lifetimes.rs:237:1
    |
 LL | fn alias_with_lt<'a>(_foo: FooAlias<'a>) -> &'a str {
    |
 help: elide the lifetimes
    |
    |
 LL - fn alias_with_lt<'a>(_foo: FooAlias<'a>) -> &'a str {
 LL + fn alias_with_lt(_foo: FooAlias<'_>) -> &str {
 
 
 error: the following explicit lifetimes could be elided: 'b
   --> $DIR/needless_lifetimes.rs:255:1
    |
 LL | fn alias_with_lt4a<'a, 'b>(_foo: &'a FooAlias<'b>) -> &'a str {
    |
 help: elide the lifetimes
    |
    |
 LL - fn alias_with_lt4a<'a, 'b>(_foo: &'a FooAlias<'b>) -> &'a str {
 LL + fn alias_with_lt4a<'a>(_foo: &'a FooAlias<'_>) -> &'a str {
 
 
 error: the following explicit lifetimes could be  [...]

2023-04-14 20:00 UTC, compiler-errors requested changes
Left a bunch of examples of ICEs due to the lack of handling of `ReError`. Left some thoughts about some of the other assertions.

I didn't touch borrowck, maybe someone like @aliemjay can leave thoughts on those.

2023-04-14 20:03 UTC, compiler-errors commented on compiler/rustc_ty_utils/src/ty.rs
> +                    ty::ReLateBound(index, bv) => {
Actually, that error is coming from somewhere else.

2023-04-15 06:12 UTC, nnethercote commented on compiler/rustc_traits/src/chalk/lowering.rs
> +            ty::ReLateBound(..) => r.super_fold_with(self),
Good point. #110345 removes them.

2023-04-19 03:11 UTC, compiler-errors commented
Not sure if you want to work on this further or split it out into other PRs, but marking this as waiting-on-author for now. 

@rustbot author

2023-04-19 04:12 UTC, nnethercote commented
> Not sure if you want to work on this further or split it out into other PRs, but marking this as waiting-on-author for now.

One or the other, but I have some other stuff I need to finish in the meantime. I'll get back to this eventually. Thank you for the detailed comments.

2023-04-26 00:46 UTC, nnethercote commented
I just created #110835, which is a massively cut down version of this, including only the changes that @compiler-errors was positive about, which wasn't many. While this was an interesting experiment, making large scale changes doesn't seem like a good idea.

2023-04-26 00:46 UTC, closed without merging