Recommend the `home` crate in env::home_dir()'s deprecation
rust-lang/rust pull request #110665
Opened 2023-04-22 01:33 UTC by utkarshgupta137

The [`home`](crates.io/crates/home) is now maintained by the cargo & rustup teams, so it seems like a no-brainer to recommend it in the standard library.

See also: https://github.com/rust-lang/rust/issues/71684#issuecomment-622651337.

Closes #71684.

@rustbot label +T-libs-api -T-lib

r? @joshtriplett
r? @Dylan-DPC

2023-04-22 02:00 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-14`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/4770208440/jobs/8481279924) [(plain)](https://github.com/rust-lang/rust/commit/6834fc1150792218a6c03015a2d707768bf02865/checks/12939433470/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Rustbook (x86_64-unknown-linux-gnu) - edition-guide
Rustbook (x86_64-unknown-linux-gnu) - style-guide
Building tool linkchecker (stage0)
    Finished release [optimized] target(s) in 0.10s
std/env/fn.home_dir.html:1: broken link - `std/env/crates.io/crates/home`
number of HTML files scanned: 33538
number of HTML redirects found: 10224
number of links checked: 2938559
number of links ignored due to external: 57566
```

</details>

2023-07-14 22:59 UTC, tgross35 requested changes
I don't think that rust typically likes endorsing third-party crates, but maybe it's OK here.

Could you update the deprecation section in the docs to say this same thing?

@rustbot label -T-libs +A-docs

2023-07-15 09:24 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5561516483/jobs/10159246401) [(plain)](https://github.com/rust-lang/rust/commit/5fde081bef5947b57818fdb1d05bf83675d5bbdb/checks/15065030823/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:c85c95e3d7251135ab7dc9ce3241c5835cc595a9)
Download action repository 'actions/upload-artifact@v3' (SHA:0b7f8abb1508181956e8e162db84b466c27e18ce)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
env:
  PR_CI_JOB: 1
  CI_JOB_NAME: mingw-check-tidy
  HEAD_SHA: 5fde081bef5947b57818fdb1d05bf83675d5bbdb
  SCCACHE_BUCKET: rust-lang-ci-sccache2
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  CACHE_DOMAIN: ci-caches.rust-lang.org
---
  lfs: false
  submodules: false
  set-safe-directory: true
env:
  PR_CI_JOB: 1
  CI_JOB_NAME: mingw-check-tidy
  HEAD_SHA: 5fde081bef5947b57818fdb1d05bf83675d5bbdb
  SCCACHE_BUCKET: rust-lang-ci-sccache2
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  CACHE_DOMAIN: ci-caches.rust-lang.org
---
##[group]Run src/ci/scripts/setup-environment.sh
src/ci/scripts/setup-environment.sh
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  PR_CI_JOB: 1
  CI_JOB_NAME: mingw-check-tidy
  HEAD_SHA: 5fde081bef5947b57818fdb1d05bf83675d5bbdb
  SCCACHE_BUCKET: rust-lang-ci-sccache2
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  CACHE_DOMAIN: ci-caches.rust-lang.org
  CACHE_DOMAIN: ci-caches.rust-lang.org
  EXTRA_VARIABLES: {}
##[endgroup]
linux builder detected, using docker to run the build
##[group]Run src/ci/scripts/should-skip-this.sh
src/ci/scripts/should-skip-this.sh
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  PR_CI_JOB: 1
  CI_JOB_NAME: mingw-check-tidy
  HEAD_SHA: 5fde081bef5947b57818fdb1d05bf83675d5bbdb
  SCCACHE_BUCKET: rust-lang-ci-sccache2
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  CACHE_DOMAIN: ci-caches.rust-lang.org
  CACHE_DOMAIN: ci-caches.rust-lang.org
  IMAGE: mingw-check-tidy
##[endgroup]
Executing the job since there is no skip rule preventing the execution
##[group]Run src/ci/scripts/verify-channel.sh
src/ci/scripts/verify-channel.sh
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  PR_CI_JOB: 1
  CI_JOB_NAME: mingw-check-tidy
  HEAD_SHA: 5fde081bef5947b57818fdb1d05bf83675d5bbdb
  SCCACHE_BUCKET: rust-lang-ci-sccache2
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  CACHE_DOMAIN: ci-caches.rust-lang.org
  CACHE_DOMAIN: ci-caches.rust-lang.org
  IMAGE: mingw-check-tidy
##[endgroup]
##[group]Run src/ci/scripts/collect-cpu-stats.sh
src/ci/scripts/collect-cpu-stats.sh
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  PR_CI_JOB: 1
  CI_JOB_NAME: mingw-check-tidy
  HEAD_SHA: 5fde081bef5947b57818fdb1d05bf83675d5bbdb
  SCCACHE_BUCKET: rust-lang-ci-sccache2
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  CACHE_DOMAIN: ci-caches.rust-lang.org
---
##[group]Run src/ci/scripts/install-sccache.sh
src/ci/scripts/install-sccache.sh
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  PR_CI_JOB: 1
  CI_JOB_NAME: mingw-check-tidy
  HEAD_SHA: 5fde081bef5947b57818fdb1d05bf83675d5bbdb
  SCCACHE_BUCKET: rust-lang-ci-sccache2
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  CACHE_DOMAIN: ci-caches.rust-lang.org
  CACHE_DOMAIN: ci-caches.rust-lang.org
  IMAGE: mingw-check-tidy
##[endgroup]
##[group]Run src/ci/scripts/select-xcode.sh
src/ci/scripts/select-xcode.sh
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  PR_CI_JOB: 1
  CI_JOB_NAME: mingw-check-tidy
  HEAD_SHA: 5fde081bef5947b57818fdb1d05bf83675d5bbdb
  SCCACHE_BUCKET: rust-lang-ci-sccache2
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  CACHE_DOMAIN: ci-caches.rust-lang.org
  CACHE_DOMAIN: ci-caches.rust-lang.org
  IMAGE: mingw-check-tidy
##[endgroup]
##[group]Run src/ci/scripts/install-clang.sh
src/ci/scripts/install-clang.sh
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  PR_CI_JOB: 1
  CI_JOB_NAME: mingw-check-tidy
  HEAD_SHA: 5fde081bef5947b57818fdb1d05bf83675d5bbdb
  SCCACHE_BUCKET: rust-lang-ci-sccache2
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  CACHE_DOMAIN: ci-caches.rust-lang.org
  CACHE_DOMAIN: ci-caches.rust-lang.org
  IMAGE: mingw-check-tidy
##[endgroup]
##[group]Run src/ci/scripts/install-wix.sh
src/ci/scripts/install-wix.sh
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  PR_CI_JOB: 1
  CI_JOB_NAME: mingw-check-tidy
  HEAD_SHA: 5fde081bef5947b57818fdb1d05bf83675d5bbdb
  SCCACHE_BUCKET: rust-lang-ci-sccache2
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  CACHE_DOMAIN: ci-caches.rust-lang.org
  CACHE_DOMAIN: ci-caches.rust-lang.org
  IMAGE: mingw-check-tidy
##[endgroup]
##[group]Run src/ci/scripts/disable-git-crlf-conversion.sh
src/ci/scripts/disable-git-crlf-conversion.sh
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  PR_CI_JOB: 1
  CI_JOB_NAME: mingw-check-tidy
  HEAD_SHA: 5fde081bef5947b57818fdb1d05bf83675d5bbdb
  SCCACHE_BUCKET: rust-lang-ci-sccache2
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  CACHE_DOMAIN: ci-caches.rust-lang.org
---
##[group]Run src/ci/scripts/install-msys2.sh
src/ci/scripts/install-msys2.sh
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  PR_CI_JOB: 1
  CI_JOB_NAME: mingw-check-tidy
  HEAD_SHA: 5fde081bef5947b57818fdb1d05bf83675d5bbdb
  SCCACHE_BUCKET: rust-lang-ci-sccache2
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  CACHE_DOMAIN: ci-caches.rust-lang.org
  CACHE_DOMAIN: ci-caches.rust-lang.org
  IMAGE: mingw-check-tidy
##[endgroup]
##[group]Run src/ci/scripts/install-mingw.sh
src/ci/scripts/install-mingw.sh
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  PR_CI_JOB: 1
  CI_JOB_NAME: mingw-check-tidy
  HEAD_SHA: 5fde081bef5947b57818fdb1d05bf83675d5bbdb
  SCCACHE_BUCKET: rust-lang-ci-sccache2
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  CACHE_DOMAIN: ci-caches.rust-lang.org
  CACHE_DOMAIN: ci-caches.rust-lang.org
  IMAGE: mingw-check-tidy
##[endgroup]
##[group]Run src/ci/scripts/install-ninja.sh
src/ci/scripts/install-ninja.sh
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  PR_CI_JOB: 1
  CI_JOB_NAME: mingw-check-tidy
  HEAD_SHA: 5fde081bef5947b57818fdb1d05bf83675d5bbdb
  SCCACHE_BUCKET: rust-lang-ci-sccache2
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  CACHE_DOMAIN: ci-caches.rust-lang.org
  CACHE_DOMAIN: ci-caches.rust-lang.org
  IMAGE: mingw-check-tidy
##[endgroup]
##[group]Run src/ci/scripts/enable-docker-ipv6.sh
src/ci/scripts/enable-docker-ipv6.sh
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  PR_CI_JOB: 1
  CI_JOB_NAME: mingw-check-tidy
  HEAD_SHA: 5fde081bef5947b57818fdb1d05bf83675d5bbdb
  SCCACHE_BUCKET: rust-lang-ci-sccache2
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  CACHE_DOMAIN: ci-caches.rust-lang.org
  CACHE_DOMAIN: ci-caches.rust-lang.org
  IMAGE: mingw-check-tidy
##[endgroup]
{"ipv6":true,"fixed-cidr-v6":"fd9a:8454:6789:13f7::/64"}
##[group]Run src/ci/scripts/disable-git-crlf-conversion.sh
src/ci/scripts/disable-git-crlf-conversion.sh
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  PR_CI_JOB: 1
  CI_JOB_NAME: mingw-check-tidy
  HEAD_SHA: 5fde081bef5947b57818fdb1d05bf83675d5bbdb
  SCCACHE_BUCKET: rust-lang-ci-sccache2
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  CACHE_DOMAIN: ci-caches.rust-lang.org
  CACHE_DOMAIN: ci-cach [...]

2023-07-15 10:32 UTC, ChrisDenton commented
Personally i don't think that the crate being taken under cargo's wing should be construed to imply endorsement. Indeed part of [the reason](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Move.20home.20crate.20into.20rust-lang/near/299633252) for doing so was that "the crate seems somewhat specific to cargo and rustup".

Linking to external crates in the std docs is very unusual nowadays so I think it warrants an fcp.

2023-07-19 02:06 UTC, tgross35 commented
This should be rebased onto the latest master before merge fyi

2023-08-15 16:05 UTC, weihanglo commented
Agree with @joshtriplett. See also a recent issue <https://github.com/rust-lang/cargo/issues/12297>.

2023-10-05 23:15 UTC, workingjubilee commented
I'm afraid that means we should probably reject this PR.

2023-10-05 23:24 UTC, utkarshgupta137 commented
I think it is fair to say that even though the home crate is fairly rustup & cargo specific, it is being used by a lot of major packages: https://crates.io/crates/home/reverse_dependencies
I think the discussion in the linked issue came to the same conclusion. Would it be better to change the wording from a recommendation to a suggestion instead?

2023-10-05 23:26 UTC, workingjubilee commented
The conclusion in that PR, as I read it, is that there should be an ACP for a new version of the deprecated function.

2023-10-05 23:33 UTC, tgross35 commented
With the above in mind, `dirs` may be better to recommend than `home` if anything, since it follows XDG. And is more popular than `home`

2023-10-05 23:39 UTC, utkarshgupta137 commented
> With the above in mind, `dirs` may be better to recommend than `home` if anything, since it follows XDG. And is more popular than `home`

I think the `dirs` crate does much more than this 1 function. AFAIK, the XDG spec doesn't say anything about the home directory, but if that is a consideration, then I don't think `dirs` is the right choice, since it doesn't allow you to follow XDG spec on other platforms, which is very popular on macOS: https://github.com/dirs-dev/directories-rs/issues/47.
If it is important to link to a crate that supports XDG, I'd like to propose [etcetera](https://docs.rs/etcetera/latest/etcetera/) instead (which is maintained by me), which supports XDG on all platforms. But it indirectly uses the `home` crate, so I don't really see the point.

2023-10-05 23:50 UTC, workingjubilee commented
...The fact that there is any discussion at all on this PR about what crate to use suggests strongly that this case is not so open-and-shut as to recommend simply picking a crate.

2024-02-09 05:49 UTC, Dylan-DPC commented
Closing this as there are concerns with this pr , and this probably needs an ACP first

2024-02-09 05:49 UTC, closed without merging