Add new rustdoc book chapter to describe in-doc settings
rust-lang/rust pull request #110641
Opened 2023-04-21 13:04 UTC by GuillaumeGomez

Fixes #55165.

I continue going through old rustdoc issues. This one made a lot of sense so decided to add the missing chapter.

r? @notriddle

2023-04-21 13:11 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/4765192611/jobs/8470633647) [(plain)](https://github.com/rust-lang/rust/commit/5dff651da6986a243200f2a6442cd4b9e72d9bf6/checks/12925550945/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:8e5e7e5ab8b370d6c329ec480221332ada57f0ab)
Download action repository 'rust-lang/simpleinfra@master' (SHA:4d706a8d448f000965ed9e883febfb36661202fe)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  CI_JOB_NAME: mingw-check-tidy
---
Building wheels for collected packages: reuse
  Building wheel for reuse (pyproject.toml): started
  Building wheel for reuse (pyproject.toml): finished with status 'done'
  Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=180119 sha256=9fa76c45f3193f307e02ea67d1a48cfe7ef2b854a074b766938a88e046bc7887
  Stored in directory: /tmp/pip-ephem-wheel-cache-nhs5qju4/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
---
Successfully built 8b9313803e2a
Successfully tagged rust-ci:latest
Built container sha256:8b9313803e2ab6a965eb97b7c7603a282911189ecb16f44e30b987e73db2b557
Uploading finished image to https://ci-caches.rust-lang.org/docker/eee721fc1ad06e35509f22d2087fb4acdb0a4d378bec3a191179769e2503f17c7f8f4292d7013976df3a24502e822c590708d80a62f327ca4849564995e4deb7
upload failed: - to s3://rust-lang-ci-sccache2/docker/eee721fc1ad06e35509f22d2087fb4acdb0a4d378bec3a191179769e2503f17c7f8f4292d7013976df3a24502e822c590708d80a62f327ca4849564995e4deb7 Unable to locate credentials
[CI_JOB_NAME=mingw-check-tidy]
[CI_JOB_NAME=mingw-check-tidy]
---
    Finished release [optimized] target(s) in 13.64s
fmt check
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/src/doc/rustdoc/src/in-doc-settings.md:49: trailing whitespace
##[error]tidy error: /checkout/src/doc/rustdoc/src/in-doc-settings.md:52: trailing whitespace
some tidy checks failed
```

</details>

2023-04-21 15:10 UTC, notriddle requested changes

2023-04-22 12:14 UTC, GuillaumeGomez commented on src/doc/rustdoc/src/in-doc-settings.md
> +Rustdoc provides settings alongside the theme picker to personalize your
Agreed.

2023-04-22 12:26 UTC, GuillaumeGomez commented on src/doc/rustdoc/src/SUMMARY.md
> +- [Rustdoc in-doc settings](in-doc-settings.md)
I don't completely agree with this classification. For example, rustdoc lints aren't really about "writing rustdoc code", just like clippy isn't about "how to write rust code" but more about "how to improve your code".

Might still be worth it to clean up the rustdoc book structure a bit though. For the time being, I'll move this new chapter as a sub-chapter of "reading rustdoc output".

2023-04-22 12:28 UTC, GuillaumeGomez commented on src/doc/rustdoc/src/in-doc-settings.md
> +in the upper right.
I can't add this `<i>` unless we add the whole CSS as well and font as well. Not sure it's worth it just for that.

2023-04-22 12:28 UTC, GuillaumeGomez commented on src/doc/rustdoc/src/in-doc-settings.md
> +Rustdoc provides settings alongside the theme picker to personalize your
I moved the content into the new chapter.

2023-04-22 12:29 UTC, GuillaumeGomez commented
Applied suggestions and made this new chapter a new sub-chapter of "how to read rustdoc output".

2023-04-22 20:56 UTC, GuillaumeGomez commented on src/doc/rustdoc/src/in-doc-settings.md
> +in the upper right.
It does but we don't use fontawesome to display the gear. But it's a good idea to include the image here.

2023-04-22 21:18 UTC, GuillaumeGomez commented on src/doc/rustdoc/src/in-doc-settings.md
> +in the upper right.
I figured out what was going on: `mdbook` is using the `4.7` version and I was looking at the icon in `5.x` version, which obviously didn't work. Fixed it.

2023-04-25 22:23 UTC, notriddle approved these changes

2023-04-26 21:42 UTC, merged