rustdoc: fix position of `default` in method rendering
rust-lang/rust pull request #110765
Opened 2023-04-24 14:19 UTC by wackbyte

With the following code:
```rs
#![feature(specialization)]

pub trait A {
    unsafe fn a();
}

impl A for () {
    default unsafe fn a() {}
}
```
rustdoc would render the `impl` of `a` as
```rs
unsafe default fn a()
```
which is inconsistent with the actual position of `default`.
This PR fixes this issue.

2023-04-28 17:13 UTC, wackbyte commented
@rustbot label +A-rustdoc-ui

2023-06-22 14:10 UTC, fmease requested changes
Thanks! Could you add a test for this though?

2023-06-24 11:34 UTC, fmease commented on tests/rustdoc/default-trait-method.rs
> +    // @!has - '//*[@id="method.baz"]' 'unsafe default fn baz()'
```suggestion
    // @has - '//*[@id="method.baz"]' 'default unsafe fn baz()'
```

The first check is definitely redundant I'd say. I'm not sure how useful the third one is.

2023-06-24 11:36 UTC, fmease approved these changes
One nit, then it's good from my side at least. Thanks for adding the test cases.

2023-06-25 13:03 UTC, fmease approved these changes

2023-07-20 08:08 UTC, GuillaumeGomez approved these changes

2023-07-20 18:45 UTC, merged