Remove repeated definite articles
rust-lang/rust pull request #110804
Opened 2023-04-25 16:02 UTC by cuishuang

2023-04-25 16:39 UTC, lnicola commented on src/tools/rust-analyzer/crates/hir-expand/src/lib.rs
> +                // try unshifting the token id, if unshifting fails, the token resides in the non-item attribute input
Can you please drop this change? It's already fixed upstream.

2023-04-25 16:54 UTC, lnicola commented on src/ci/docker/host-x86_64/dist-mips-linux/patches/glibc/2.23/0002-MIPS-SPARC-more-fixes-to-the-vfork-aliases-in-libpth.patch
> +vfork implementations with the other architectures. That way the
Might be a good idea to leave this alone, since it's someone else's patch from 2016.

2023-04-26 05:32 UTC, jyn514 requested changes

2023-04-26 05:32 UTC, jyn514 commented on src/tools/rustfmt/CHANGELOG.md
> -- Implement stable ordering for impl items with the the following item priority: type, const, macro, then method fa80ddf
Please don't change subtrees in rust-lang/rust unless it's necessary. You can make this PR directly to rust-lang/rustfmt instead.

2023-04-26 05:32 UTC, jyn514 commented on src/tools/rustfmt/Processes.md
> -- Update the the `Configuration.md` file marking the option as stable.
ditto for the rest of the rustfmt changes

2023-04-26 16:57 UTC, jyn514 commented
@bors r+ rollup

2023-04-27 17:16 UTC, merged