rustdoc: render visibility on associated types
rust-lang/rust pull request #110945
Opened 2023-04-28 11:38 UTC by wackbyte

This only affects inherent associated types (#8995).

2023-04-28 11:58 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-14`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/4830176365/jobs/8606071522) [(plain)](https://github.com/rust-lang/rust/commit/46a6844da0cb5cb20aa9f9dc15d5570b3c1bb5e1/checks/13097785199/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
---- [rustdoc] tests/rustdoc/anchors.rs stdout ----

error: htmldocck failed!
status: exit status: 1
command: "/usr/bin/python3" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/anchors" "/checkout/tests/rustdoc/anchors.rs"
--- expected ---


<section id="associatedtype.Y" class="associatedtype"><h4 class="code-header">type <a href="#associatedtype.Y" class="associatedtype">Y</a> = <a class="primitive" href="https://doc.rust-lang.org/nightly/std/primitive.u32.html">u32</a></h4></section>

--- actual ---


<section id="associatedtype.Y" class="associatedtype"><h4 class="code-header">pub type <a href="#associatedtype.Y" class="associatedtype">Y</a> = <a class="primitive" href="https://doc.rust-lang.org/nightly/std/primitive.u32.html">u32</a></h4></section>
--- stderr -------------------------------
--- stderr -------------------------------
text: 'pub type ' != 'type '
children 1 do not match: h4
children 1 do not match: section
43: @snapshot check failed
 Actual snapshot value is different than expected
     // @snapshot no_type_anchor2 - '//*[@id="associatedtype.Y"]'
Encountered 1 errors
------------------------------------------


```

</details>

2023-04-28 16:49 UTC, wackbyte commented
@rustbot label +F-inherent_associated_types

2023-04-28 17:19 UTC, wackbyte commented
@rustbot label +A-rustdoc-ui

2023-04-29 12:56 UTC, fmease requested changes
Thanks for catching and fixing this! I've marked one thing that definitely needs to be addressed.
Apart from that, I think it would be good to add at least one more test (file) that explicitly checks for the new behavior (e.g. with `@has`) instead of relying on this `@snapshot` test that could accidentally `--bless`ed without notice.

2023-04-29 12:56 UTC, fmease commented on tests/rustdoc/anchors.no_type_anchor2.html
> +<section id="associatedtype.Y" class="associatedtype"><h4 class="code-header">pub type <a href="#associatedtype.Y" class="associatedtype">Y</a> = <a class="primitive" href="https://doc.rust-lang.org/
Please keep the channel placeholder

```suggestion
<section id="associatedtype.Y" class="associatedtype"><h4 class="code-header">pub type <a href="#associatedtype.Y" class="associatedtype">Y</a> = <a class="primitive" href="{{channel}}/std/primitive.u32.html">u32</a></h4></section>
```

2023-04-29 20:28 UTC, wackbyte commented
I added the test to the existing `visibility` test with tests for other associated items as well.

2023-05-07 21:38 UTC, fmease approved these changes
Thanks for adding the test :+1:

LGTM (I personally don't have bors rights, so I cannot bors-approve)

2023-06-04 18:56 UTC, jsha commented
Thanks for the fix, @wackbyte! Sorry I took so long to review this. Looks good to me as well - and thanks @fmease for the review.

@bors r+ rollup

2023-06-05 07:48 UTC, merged

2023-06-05 10:11 UTC, rust-timer commented
Finished benchmarking commit (51f714c8c5021fe25442e46798b1cbef2f2249ed): [comparison URL](https://perf.rust-lang.org/compare.html?start=e4106065bf1bb515935d5d024e8d9c86454e2b22&end=51f714c8c5021fe25442e46798b1cbef2f2249ed&stat=instructions:u).

### Overall result: ❌ regressions - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=e4106065bf1bb515935d5d024e8d9c86454e2b22&end=51f714c8c5021fe25442e46798b1cbef2f2249ed&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 1.1% | [1.1%, 1.1%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=e4106065bf1bb515935d5d024e8d9c86454e2b22&end=51f714c8c5021fe25442e46798b1cbef2f2249ed&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -2.3% | [-2.7%, -1.8%] | 4     |
| All ❌✅ (primary)                 | -     | -              | 0     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=e4106065bf1bb515935d5d024e8d9c86454e2b22&end=51f714c8c5021fe25442e46798b1cbef2f2249ed&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | 2.7%  | [2.0%, 4.3%]   | 5     |
| Improvements ✅ <br /> (primary)   | -3.0% | [-3.0%, -3.0%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -3.0% | [-3.0%, -3.0%] | 1     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=e4106065bf1bb515935d5d024e8d9c86454e2b22&end=51f714c8c5021fe25442e46798b1cbef2f2249ed&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 646.537s -> 645.963s (-0.09%)