fix(parse): return unpected when current token is EOF
rust-lang/rust pull request #111181
Opened 2023-05-04 08:36 UTC by bvanjoi

close https://github.com/rust-lang/rust/issues/111148

2023-05-05 17:45 UTC, compiler-errors commented
Can you leave some explanation why this fixes the issue? I think I understand the corner case it's trying to avoid here, but I'm not totally sure.

2023-05-06 07:27 UTC, bvanjoi commented
> Can you leave some explanation why this fixes the issue? I think I understand the corner case it's trying to avoid here, but I'm not totally sure.

I have included a few descriptions in this PR, and I would really appreciate your valuable suggestions and feedback, whether it pertains to the code or the descriptions themselves.

2023-05-12 15:49 UTC, davidtwco requested changes
LGTM with the suggested change

2023-05-12 15:49 UTC, davidtwco commented on compiler/rustc_parse/src/parser/mod.rs
>          } else if self.last_unexpected_token_span == Some(self.token.span) {
```suggestion
        } else if self.token.kind != token::Eof && self.last_unexpected_token_span == Some(self.token.span) {
```

I think this is better, we avoid duplicating the content of the `else` block, which is the behaviour we want.

2023-05-27 14:42 UTC, jyn514 commented
@bors r=davidtwco rollup

2023-05-27 22:47 UTC, merged