Suggest let for possible binding with ty
rust-lang/rust pull request #111120
Opened 2023-05-03 03:51 UTC by chenyukang

Origin from https://github.com/rust-lang/rust/pull/109128#discussion_r1179866137

r? @Nilstrieb

2023-05-07 18:23 UTC, Nilstrieb requested changes
I don't think this is a great place to put it (the error message is very specialized for statements, but the location is pretty generic), I'd prefer it if you found a more specific place. After fixing your ICE locally, this snippet produces the following output:
```rust
struct A {
    : u8 =,
}
```
```
error: expected identifier, found `:`
 --> uwu.rs:6:5
  |
5 | struct A {
  |        - while parsing this struct
6 |     : u8 =,
  |     ^ expected identifier
  |
help: you might have meant to introduce a new binding
  |
5 | struct A let {
  |          +++
```
which, while this snippet is totally nonsensical, is not very good.

2023-05-07 18:23 UTC, Nilstrieb commented on compiler/rustc_parse/src/parser/diagnostics.rs
> +            if self.parse_ty().is_ok() && self.token == token::Eq {
You need to cancel the error here. This ICEs:
```rust
struct A {
    : :u8,
}
```

2023-05-08 08:21 UTC, chenyukang commented
@rustbot ready

2023-05-08 17:44 UTC, Nilstrieb reviewed
That implementation is a lot nicer! r=me after addressing the comment

2023-05-08 17:44 UTC, Nilstrieb commented on compiler/rustc_parse/src/parser/diagnostics.rs
> +                            "you might have meant to introduce a new binding",
could you turn this into a session diagnostic derive?

2023-05-09 03:59 UTC, chenyukang commented
@bors r=Nilstrieb

2023-05-09 11:07 UTC, merged