fix(ty_utils): try normalize earsing regions
rust-lang/rust pull request #111259
Opened 2023-05-05 17:06 UTC by bvanjoi

close https://github.com/rust-lang/rust/issues/110630

2023-05-05 17:21 UTC, compiler-errors requested changes
This PR description really needs more information about:

1. Why it happens
2. Why this fix is correct

2023-05-05 17:21 UTC, compiler-errors commented on compiler/rustc_ty_utils/src/instance.rs
> +            Err(_error) => return Err(ErrorGuaranteed::unchecked_claim_error_was_emitted()),
you should really never be using `ErrorGuaranteed::unchecked_claim_error_was_emitted()`, it's pretty easy to introduce bugs that could affect the compiler's soundness --

From the docs:

> To be used only if you really know what you are doing…

2023-05-05 17:21 UTC, compiler-errors commented on compiler/rustc_ty_utils/src/instance.rs
> +        match tcx.try_normalize_erasing_regions(param_env, substs) {
The normalization needs to be introduced somewhere higher in the call stack, not here. Normalizing on every call to `resolve_instance` is far too general, I think.

2023-05-06 01:58 UTC, bvanjoi commented
> This PR description really needs more information about:
> 
> 1. Why it happens
> 2. Why this fix is correct

Thanks for your advice, I will try to add more descriptions

2023-05-06 11:34 UTC, bvanjoi commented on compiler/rustc_lint/src/internal.rs
> +        let substs = cx.tcx.normalize_erasing_regions(cx.param_env, substs);
for #105561

2023-05-06 11:34 UTC, bvanjoi commented on compiler/rustc_lint/src/internal.rs
> +        let substs = cx.tcx.normalize_erasing_regions(cx.param_env, substs);
for #105561

2023-05-06 11:40 UTC, bvanjoi commented
@bors ready

2023-05-11 22:57 UTC, BoxyUwU commented
generic_const_exprs currently evaluates constants without their where clauses holding, resulting in us attempting to do things like this on not-wf code. I do not think this PR is the correct solution to the linked issue, we really ought to be ensuring that `ConstKind::Unevaluated` is wf before attempting to evaluate it. Replacing infallible stuff with fallible stuff just to mask ICEs caused by this bug doesn't seem desirable to me.

Unfortunately it is not possible right now to "just" check `ConstKind::Unevaluated` is wf before evaluating it so I do not think it is possible to fix the linked issue in a satisfactory way. The bug here is tracked in rust-lang/project-const-generics#37 and there are a fair amount of issues open with the `F-generic_const_exprs` label caused by it.

2023-08-10 15:27 UTC, Dylan-DPC commented
@bvanjoi any updates on this? thanks

2023-08-10 17:54 UTC, bvanjoi commented
Closed this as it is invalid.

2023-08-10 17:54 UTC, closed without merging