[rustdoc][JSON] Use exclusively externally tagged enums in the JSON representation
rust-lang/rust pull request #111427
Opened 2023-05-10 13:42 UTC by LukeMathWalker

See [this Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/.28De.29serialization.20speed.20of.20JSON.20docs) and [this issue](https://github.com/rust-lang/rust/issues/93667) for the relevant context.

2023-05-15 12:14 UTC, aDotInTheVoid commented
This also needs to bump `FORMAT_VERSION`, as it changes the serialized representation of JSON (aside: why didn't rustbot fire on this)

2023-05-19 09:40 UTC, LukeMathWalker commented
Milestone achieved: more than half of the test suite is green now, but many more to go 😭

2023-05-19 09:46 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5022963813/jobs/9007022296) [(plain)](https://github.com/rust-lang/rust/commit/54443e8267ff28d07f87ab4c4e509f2f22d9f971/checks/13605217228/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:8e5e7e5ab8b370d6c329ec480221332ada57f0ab)
Download action repository 'rust-lang/simpleinfra@master' (SHA:af9a3f1b7e12a54c737d8aa371acc8d05cb83a8f)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  CI_JOB_NAME: mingw-check-tidy
---
Building wheels for collected packages: reuse
  Building wheel for reuse (pyproject.toml): started
  Building wheel for reuse (pyproject.toml): finished with status 'done'
  Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=180115 sha256=c3e1cf75e5aea7348ad201d16633573bc9f3aa58c8e29a6ca459f306300d6c9d
  Stored in directory: /tmp/pip-ephem-wheel-cache-angdihvd/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
---
Successfully tagged rust-ci:latest
Built container sha256:27fbe0cf0b2798d97eab6f2da8905346cd58edf4d0535857b48835ab5e20d699
Uploading finished image to https://ci-caches.rust-lang.org/docker/e51156f19850ce886cec818e46dc2a021e0aa7c270d15673e8fe74cd8522fc8ac3995109aebb688ee49ed586735ed4cf5f8c06d44c48298fa09c35ae4b082281

<botocore.awsrequest.AWSRequest object at 0x7ff878f3ba10>
gzip: stdout: Broken pipe
xargs: docker: terminated by signal 13
[CI_JOB_NAME=mingw-check-tidy]
[CI_JOB_NAME=mingw-check-tidy]
---
##[endgroup]
fmt check
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/tests/rustdoc-json/enums/discriminant/num_underscore_and_suffix.rs:13: line longer than 100 chars
##[error]tidy error: /checkout/tests/rustdoc-json/enums/discriminant/only_some_have_discriminant.rs:8: line longer than 100 chars
tidy error: /checkout/tests/rustdoc-json/type/extern.rs: missing trailing newline
##[error]tidy error: /checkout/tests/rustdoc-json/structs/with_primitives.rs:4: line longer than 100 chars
some tidy checks failed
```

</details>

2023-05-21 12:37 UTC, aDotInTheVoid commented on tests/rustdoc-json/nested.rs
> +    // @set l4_use_id = "$.index[*][?(@.inner.import)].id"
Looks like https://github.com/freestrings/jsonpath/issues/91. I'd be fine with adding a `FIXME` here. CC #110406

2023-05-21 12:39 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5037670609/jobs/9034663496) [(plain)](https://github.com/rust-lang/rust/commit/dc9ce689d00756439c75957bd7d6f9c570fb6a76/checks/13639272577/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:8e5e7e5ab8b370d6c329ec480221332ada57f0ab)
Download action repository 'rust-lang/simpleinfra@master' (SHA:af9a3f1b7e12a54c737d8aa371acc8d05cb83a8f)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  CI_JOB_NAME: mingw-check-tidy
---
Building wheels for collected packages: reuse
  Building wheel for reuse (pyproject.toml): started
  Building wheel for reuse (pyproject.toml): finished with status 'done'
  Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=180115 sha256=c3e1cf75e5aea7348ad201d16633573bc9f3aa58c8e29a6ca459f306300d6c9d
  Stored in directory: /tmp/pip-ephem-wheel-cache-a5stsjj_/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
---
Successfully tagged rust-ci:latest
Built container sha256:f856c97139134d0d0c222c30b91f16e053270dbdadbfa9c5d9107e5eba2d1c8f
Uploading finished image to https://ci-caches.rust-lang.org/docker/e51156f19850ce886cec818e46dc2a021e0aa7c270d15673e8fe74cd8522fc8ac3995109aebb688ee49ed586735ed4cf5f8c06d44c48298fa09c35ae4b082281

<botocore.awsrequest.AWSRequest object at 0x7f0712a442d0>
gzip: stdout: Broken pipe
xargs: docker: terminated by signal 13
[CI_JOB_NAME=mingw-check-tidy]
[CI_JOB_NAME=mingw-check-tidy]
---
##[endgroup]
fmt check
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/tests/rustdoc-json/enums/discriminant/num_underscore_and_suffix.rs:13: line longer than 100 chars
##[error]tidy error: /checkout/tests/rustdoc-json/enums/discriminant/only_some_have_discriminant.rs:8: line longer than 100 chars
tidy error: /checkout/tests/rustdoc-json/type/extern.rs: missing trailing newline
##[error]tidy error: /checkout/tests/rustdoc-json/structs/with_primitives.rs:4: line longer than 100 chars
##[error]tidy error: /checkout/tests/rustdoc-json/reexport/private_two_names.rs:16: trailing whitespace
##[error]tidy error: /checkout/tests/rustdoc-json/reexport/private_two_names.rs:21: trailing whitespace
##[error]tidy error: /checkout/tests/rustdoc-json/reexport/doc_inline_external_crate.rs:10: line longer than 100 chars
some tidy checks failed
```

</details>

2023-05-21 21:01 UTC, LukeMathWalker commented on tests/rustdoc-json/nested.rs
> +    // @set l4_use_id = "$.index[*][?(@.inner.import)].id"
Yeah, that's precisely the issue.
I can reword most tests to work around the problem, so it's not a blocker here, but just wanted to confirm the root cause.

2023-05-22 09:06 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5043864064/jobs/9046195464) [(plain)](https://github.com/rust-lang/rust/commit/5834c994d0dcc8930c5cd13b43dd183a2b64fda0/checks/13653216719/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:8e5e7e5ab8b370d6c329ec480221332ada57f0ab)
Download action repository 'rust-lang/simpleinfra@master' (SHA:af9a3f1b7e12a54c737d8aa371acc8d05cb83a8f)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  CI_JOB_NAME: mingw-check-tidy
---
Building wheels for collected packages: reuse
  Building wheel for reuse (pyproject.toml): started
  Building wheel for reuse (pyproject.toml): finished with status 'done'
  Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=180115 sha256=c3e1cf75e5aea7348ad201d16633573bc9f3aa58c8e29a6ca459f306300d6c9d
  Stored in directory: /tmp/pip-ephem-wheel-cache-eab2noym/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
---
Successfully tagged rust-ci:latest
Built container sha256:64c6e5f8b5c1111d138ce58dc622f042b2ea6fae7c676d7e0f721c1328a9e067
Uploading finished image to https://ci-caches.rust-lang.org/docker/e51156f19850ce886cec818e46dc2a021e0aa7c270d15673e8fe74cd8522fc8ac3995109aebb688ee49ed586735ed4cf5f8c06d44c48298fa09c35ae4b082281

<botocore.awsrequest.AWSRequest object at 0x7f82fed83650>
gzip: stdout: Broken pipe
xargs: docker: terminated by signal 13
[CI_JOB_NAME=mingw-check-tidy]
[CI_JOB_NAME=mingw-check-tidy]
---
##[endgroup]
fmt check
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/tests/rustdoc-json/enums/discriminant/num_underscore_and_suffix.rs:13: line longer than 100 chars
##[error]tidy error: /checkout/tests/rustdoc-json/enums/discriminant/only_some_have_discriminant.rs:8: line longer than 100 chars
tidy error: /checkout/tests/rustdoc-json/type/extern.rs: missing trailing newline
##[error]tidy error: /checkout/tests/rustdoc-json/structs/with_primitives.rs:4: line longer than 100 chars
tidy error: /checkout/tests/rustdoc-json/reexport/glob_collision.rs: too many trailing newlines (2)
##[error]tidy error: /checkout/tests/rustdoc-json/reexport/private_two_names.rs:16: trailing whitespace
##[error]tidy error: /checkout/tests/rustdoc-json/reexport/private_two_names.rs:21: trailing whitespace
##[error]tidy error: /checkout/tests/rustdoc-json/reexport/doc_inline_external_crate.rs:10: line longer than 100 chars
some tidy checks failed
```

</details>

2023-05-22 10:07 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5044441067/jobs/9047493916) [(plain)](https://github.com/rust-lang/rust/commit/1a0b5583e65b0f4b9c6e18ee3c65b040f69be4bd/checks/13654864276/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:8e5e7e5ab8b370d6c329ec480221332ada57f0ab)
Download action repository 'rust-lang/simpleinfra@master' (SHA:cdb59432ef9e018dd6db5879e720eccc3289da68)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  CI_JOB_NAME: mingw-check-tidy
---
Building wheels for collected packages: reuse
  Building wheel for reuse (pyproject.toml): started
  Building wheel for reuse (pyproject.toml): finished with status 'done'
  Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=180115 sha256=c3e1cf75e5aea7348ad201d16633573bc9f3aa58c8e29a6ca459f306300d6c9d
  Stored in directory: /tmp/pip-ephem-wheel-cache-ydgu7b8f/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
---
Successfully tagged rust-ci:latest
Built container sha256:02d93c31e3cb28b8a008621b42958a42f7453bfab22639f18116f4ffbf03dd66
Uploading finished image to https://ci-caches.rust-lang.org/docker/e51156f19850ce886cec818e46dc2a021e0aa7c270d15673e8fe74cd8522fc8ac3995109aebb688ee49ed586735ed4cf5f8c06d44c48298fa09c35ae4b082281

<botocore.awsrequest.AWSRequest object at 0x7fda6f014e50>
gzip: stdout: Broken pipe
xargs: docker: terminated by signal 13
[CI_JOB_NAME=mingw-check-tidy]
[CI_JOB_NAME=mingw-check-tidy]
---
##[endgroup]
fmt check
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/tests/rustdoc-json/enums/discriminant/num_underscore_and_suffix.rs:13: line longer than 100 chars
##[error]tidy error: /checkout/tests/rustdoc-json/enums/discriminant/only_some_have_discriminant.rs:8: line longer than 100 chars
tidy error: /checkout/tests/rustdoc-json/type/extern.rs: missing trailing newline
##[error]tidy error: /checkout/tests/rustdoc-json/fn_pointer/qualifiers.rs:6: line longer than 100 chars
##[error]tidy error: /checkout/tests/rustdoc-json/fn_pointer/qualifiers.rs:7: line longer than 100 chars
##[error]tidy error: /checkout/tests/rustdoc-json/fn_pointer/qualifiers.rs:8: line longer than 100 chars
##[error]tidy error: /checkout/tests/rustdoc-json/structs/with_primitives.rs:4: line longer than 100 chars
tidy error: /checkout/tests/rustdoc-json/reexport/glob_collision.rs: too many trailing newlines (2)
##[error]tidy error: /checkout/tests/rustdoc-json/reexport/private_two_names.rs:16: trailing whitespace
##[error]tidy error: /checkout/tests/rustdoc-json/reexport/private_two_names.rs:21: trailing whitespace
##[error]tidy error: /checkout/tests/rustdoc-json/reexport/doc_inline_external_crate.rs:10: line longer than 100 chars
some tidy checks failed
```

</details>

2023-05-22 15:22 UTC, obi1kenobi approved these changes
🔥🚀 Thanks, Luca!

2023-05-22 17:04 UTC, aDotInTheVoid requested changes
This is a heroic effort, thanks so much for doing it.

In addition to the minor things above, could you rebase this to follow the [no merge policy](https://rustc-dev-guide.rust-lang.org/git.html#no-merge-policy), and to squash all the test changes into a single commit

2023-05-22 17:05 UTC, aDotInTheVoid commented
r? @aDotInTheVoid

2023-05-22 17:13 UTC, aDotInTheVoid commented
Also, it's worth adding `bincode` or `postcard` as a dev-dep to rustdoc-json-types, so we can test that the format is (de)serializable with non-self-describing formats, even if we don't plan to ship them in rustdoc itself.

2023-05-22 17:22 UTC, LukeMathWalker commented on tests/rustdoc-json/reexport/rename_private.rs
> -// @!has "$.index[*][?(@.kind=='inner')]"
I was kind of confused here, thanks for clarifying!

2023-05-22 17:22 UTC, LukeMathWalker commented on tests/rustdoc-json/reexport/glob_collision.rs
> +// @is "$.index[*][?(@.name == 'm1')].inner[?(@.module)].module.is_stripped" true
You're right, removed it in all cases in this file.

2023-05-22 17:22 UTC, LukeMathWalker commented on tests/rustdoc-json/enums/use_variant_foreign.rs
> +// @has "$.index[*][?(@.inner.import)].inner.import"
Yeah, I messed up the porting here. Fixed it!

2023-05-22 17:27 UTC, LukeMathWalker commented
I've added `bincode` to the existing roundtrip tests—let me know if that suffices.
All commits have been squashed 👌🏻

2023-05-22 17:43 UTC, aDotInTheVoid commented
r=me when CI passes

2023-05-22 18:06 UTC, aDotInTheVoid commented
@bors r+

2023-05-22 18:09 UTC, obi1kenobi commented
Thank you both for getting this in so quickly! 🙌

2023-05-22 18:12 UTC, aDotInTheVoid commented
Don't celebrate till it gets through bors, you'll jinx it 😅

2023-05-22 18:34 UTC, GuillaumeGomez commented
Just passing through to say: nice job everyone! :)

2023-05-23 21:09 UTC, merged