Add chapter in rustdoc book for re-exports and add a regression test for `#[doc(hidden)]` behaviour
rust-lang/rust pull request #112304
Opened 2023-06-05 09:06 UTC by GuillaumeGomez

Fixes https://github.com/rust-lang/rust/issues/109449.
Fixes https://github.com/rust-lang/rust/issues/53417.

After the discussion in #109697, I made a few PRs to fix a few corner cases:
 * https://github.com/rust-lang/rust/pull/112178
 * https://github.com/rust-lang/rust/pull/112108
 * https://github.com/rust-lang/rust/pull/111997

With this I think I covered all cases. Only thing missing at this point was a chapter covering re-exports in the rustdoc book.

r? @notriddle

2023-06-05 17:34 UTC, notriddle requested changes

2023-06-05 18:13 UTC, GuillaumeGomez commented on src/doc/rustdoc/src/write-documentation/the-doc-attribute.md
> +making it private. For glob-based imports (such as `use module::*`), hidden items are not inlined.
Arf, missed that one.

2023-06-05 18:31 UTC, GuillaumeGomez commented
Improved documentation and fixed the one I missed.

2023-06-14 20:04 UTC, notriddle approved these changes

2023-06-15 19:04 UTC, merged