Lower matches against constant slices into better MIR
rust-lang/rust pull request #112370
Opened 2023-06-07 01:10 UTC by john-h-k

Fixes #110870 (eventually)

The approach I've been trying so far is lowering `PatKind::Array` (when it is a fixed array with only constants in it) to a constant pattern in `mir_build`. Currently there are two issues here:
* I am hitting an assertion around unexpected types for constants
* I don't know how to allocate the `Pat` into the `tcx` to get the lifetimes right (hence the `Box::leak` hack)

I will continue toying around with this but wanted to open the PR to see if this is the wrong way of doing it. Should I be doing it in a different MIR stage/a MIR opt pass?

2023-06-07 01:15 UTC, rust-log-analyzer commented
A job failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5194897019/jobs/9367064948) [(plain)](https://github.com/rust-lang/rust/commit/f75d8423cd2e1382c8bd95523cf69bae4fd3d0df/checks/14059362125/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Attempting with retry: docker build --rm -t rust-ci -f /home/runner/work/rust/rust/src/ci/docker/host-x86_64/mingw-check/Dockerfile /home/runner/work/rust/rust/src/ci/docker
Sending build context to Docker daemon  428.5kB

Step 1/15 : FROM ubuntu:22.04
error parsing HTTP 429 response body: invalid character 'T' looking for beginning of value: "Too Many Requests (HAP429).\n"
Sending build context to Docker daemon  428.5kB

Step 1/15 : FROM ubuntu:22.04
Step 1/15 : FROM ubuntu:22.04
error parsing HTTP 429 response body: invalid character 'T' looking for beginning of value: "Too Many Requests (HAP429).\n"
Sending build context to Docker daemon  428.5kB

Step 1/15 : FROM ubuntu:22.04
Step 1/15 : FROM ubuntu:22.04
error parsing HTTP 429 response body: invalid character 'T' looking for beginning of value: "Too Many Requests (HAP429).\n"
Sending build context to Docker daemon  428.5kB

Step 1/15 : FROM ubuntu:22.04
Step 1/15 : FROM ubuntu:22.04
error parsing HTTP 429 response body: invalid character 'T' looking for beginning of value: "Too Many Requests (HAP429).\n"
Sending build context to Docker daemon  428.5kB

Step 1/15 : FROM ubuntu:22.04
Step 1/15 : FROM ubuntu:22.04
error parsing HTTP 429 response body: invalid character 'T' looking for beginning of value: "Too Many Requests (HAP429).\n"
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2023-06-07 04:50 UTC, john-h-k commented
Okay, it looks like currently `Constant` really means u128 or smaller constants, so it might not be the right type to approach this with

2023-06-07 08:43 UTC, john-h-k commented
Okay, I have somehow managed to get the basic test case for this working with the expected MIR generation. The basic idea is (this still may be the entirely wrong way to do this):
* During THIR -> MIR lowering, `PatKind::Array`s which meet these criteria are recognised and handled as this special case
    * No slice element (not sure what it is called, but as in no `[1, .., 2]`
    * No suffix (as when there is no slice element I am assuming there is no suffix)
    * All elements within `prefix` are `PatKind::Constant`

* The handling for this case is
    * Construct a `ValTree` from the elements of the array,

* Things I still need help with
    * Is this the right way to do it?!
    * How do I allocate the new pattern properly (rather than the `Box::leak` hack I currently have) with the `'tcx' lifetime in compiler/rustc_mir_build/src/build/matches/simplify.rs:316
    * Is the type logic for the pattern (`[<type of the constant in the array>; <count in array>]` correct? Or should it be based on the match type?

2023-06-07 08:52 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-14`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5197816238/jobs/9373141229) [(plain)](https://github.com/rust-lang/rust/commit/b3123e124c106476be14a206b62ece70f7bb0119/checks/14066951281/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
failures:

---- [ui] tests/ui/pattern/usefulness/slice-pattern-const-3.rs stdout ----

error: Error: expected failure status (Some(1)) but received status Some(101).
status: exit status: 101
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/pattern/usefulness/slice-pattern-const-3.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--remap-path-prefix=/checkout/tests/ui=fake-test-src-base" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/pattern/usefulness/slice-pattern-const-3" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/pattern/usefulness/slice-pattern-const-3/auxiliary"
stdout: none
error: unreachable pattern
  --> fake-test-src-base/pattern/usefulness/slice-pattern-const-3.rs:9:9
   |
   |
LL |         ["4", "5", "6", "7"] => (), //~ ERROR unreachable pattern
   |
note: the lint level is defined here
  --> fake-test-src-base/pattern/usefulness/slice-pattern-const-3.rs:1:9
   |
   |
LL | #![deny(unreachable_patterns)]
   |         ^^^^^^^^^^^^^^^^^^^^

error: unreachable pattern
  --> fake-test-src-base/pattern/usefulness/slice-pattern-const-3.rs:15:9
   |
LL |         ["4", "5", "6", "7"] => (), //~ ERROR unreachable pattern

error: unreachable pattern
  --> fake-test-src-base/pattern/usefulness/slice-pattern-const-3.rs:21:9
   |
   |
LL |         MAGIC_TEST => (), //~ ERROR unreachable pattern

error: unreachable pattern
  --> fake-test-src-base/pattern/usefulness/slice-pattern-const-3.rs:28:9
   |
   |
LL |         FOO => (), //~ ERROR unreachable pattern


error: internal compiler error: /checkout/compiler/rustc_middle/src/ty/consts/valtree.rs:47:18: expected leaf, got Branch([Leaf(0x30), Leaf(0x78), Leaf(0x30), Leaf(0x30)])
thread 'rustc' panicked at 'Box<dyn Any>', /checkout/compiler/rustc_errors/src/lib.rs:1650:9
stack backtrace:
   0:     0x7f5cddd69831 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4e4c3122187f4116
   1:     0x7f5cdddd17f8 - core::fmt::write::ha0ca16860c0a32b7
   1:     0x7f5cdddd17f8 - core::fmt::write::ha0ca16860c0a32b7
   2:     0x7f5cddd5dd31 - std::io::Write::write_fmt::hb9d47d3392fb9078
   3:     0x7f5cddd69641 - std::sys_common::backtrace::print::hd68a52820de71206
   4:     0x7f5cddd6c79a - std::panicking::default_hook::{{closure}}::hb8d4e11923547869
   5:     0x7f5cddd6c48c - std::panicking::default_hook::hcfbd247842317d7f
   6:     0x7f5cde84cb4b - rustc_driver_impl[74d70f29a4976b69]::install_ice_hook::{closure#0}
   7:     0x7f5cddd6cede - std::panicking::rust_panic_with_hook::h36a39be0a04104b9
   8:     0x7f5ce1461d13 - std[5d9df998ba8d149a]::panicking::begin_panic::<rustc_errors[bdcf0fd726af0d03]::ExplicitBug>::{closure#0}
   9:     0x7f5ce145de76 - std[5d9df998ba8d149a]::sys_common::backtrace::__rust_end_short_backtrace::<std[5d9df998ba8d149a]::panicking::begin_panic<rustc_errors[bdcf0fd726af0d03]::ExplicitBug>::{closure#0}, !>
  10:     0x7f5cde7de9e6 - std[5d9df998ba8d149a]::panicking::begin_panic::<rustc_errors[bdcf0fd726af0d03]::ExplicitBug>
  11:     0x7f5ce14906e7 - <rustc_errors[bdcf0fd726af0d03]::HandlerInner>::bug::<alloc[98a3611cc08fd344]::string::String>
  12:     0x7f5ce1490549 - <rustc_errors[bdcf0fd726af0d03]::Handler>::bug::<alloc[98a3611cc08fd344]::string::String>
  13:     0x7f5ce15666f7 - rustc_middle[484184425fe9f802]::util::bug::opt_span_bug_fmt::<rustc_span[155e37cf5a966f7f]::span_encoding::Span>::{closure#0}
  14:     0x7f5ce1565c9c - rustc_middle[484184425fe9f802]::ty::context::tls::with_opt::<rustc_middle[484184425fe9f802]::util::bug::opt_span_bug_fmt<rustc_span[155e37cf5a966f7f]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:     0x7f5ce1565c24 - rustc_middle[484184425fe9f802]::ty::context::tls::with_context_opt::<rustc_middle[484184425fe9f802]::ty::context::tls::with_opt<rustc_middle[484184425fe9f802]::util::bug::opt_span_bug_fmt<rustc_span[155e37cf5a966f7f]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:     0x7f5cde7df722 - rustc_middle[484184425fe9f802]::util::bug::bug_fmt
  17:     0x7f5cdfc3803f - <core[e47f74b0dd5276f5]::iter::adapters::map::Map<core[e47f74b0dd5276f5]::slice::iter::Iter<alloc[98a3611cc08fd344]::boxed::Box<rustc_middle[484184425fe9f802]::thir::Pat>>, <rustc_mir_build[2058d432b4b181a9]::build::Builder>::simplify_match_pair::{closure#2}> as core[e47f74b0dd5276f5]::iter::traits::iterator::Iterator>::fold::<(), core[e47f74b0dd5276f5]::iter::traits::iterator::Iterator::for_each::call<rustc_middle[484184425fe9f802]::ty::consts::int::ScalarInt, <alloc[98a3611cc08fd344]::vec::Vec<rustc_middle[484184425fe9f802]::ty::consts::int::ScalarInt>>::extend_trusted<core[e47f74b0dd5276f5]::iter::adapters::map::Map<core[e47f74b0dd5276f5]::slice::iter::Iter<alloc[98a3611cc08fd344]::boxed::Box<rustc_middle[484184425fe9f802]::thir::Pat>>, <rustc_mir_build[2058d432b4b181a9]::build::Builder>::simplify_match_pair::{closure#2}>>::{closure#0}>::{closure#0}>
  18:     0x7f5cdfc585e7 - <alloc[98a3611cc08fd344]::vec::Vec<rustc_middle[484184425fe9f802]::ty::consts::int::ScalarInt> as alloc[98a3611cc08fd344]::vec::spec_from_iter::SpecFromIter<rustc_middle[484184425fe9f802]::ty::consts::int::ScalarInt, core[e47f74b0dd5276f5]::iter::adapters::map::Map<core[e47f74b0dd5276f5]::slice::iter::Iter<alloc[98a3611cc08fd344]::boxed::Box<rustc_middle[484184425fe9f802]::thir::Pat>>, <rustc_mir_build[2058d432b4b181a9]::build::Builder>::simplify_match_pair::{closure#2}>>>::from_iter
  19:     0x7f5cdfb446bd - <rustc_mir_build[2058d432b4b181a9]::build::Builder>::simplify_candidate
  20:     0x7f5cdfb4839c - <rustc_mir_build[2058d432b4b181a9]::build::Builder>::match_candidates
  21:     0x7f5cdfb2b994 - <rustc_mir_build[2058d432b4b181a9]::build::Builder>::lower_match_tree
  22:     0x7f5cdfb45875 - <rustc_mir_build[2058d432b4b181a9]::build::Builder>::match_expr
  23:     0x7f5cdfb409df - <rustc_mir_build[2058d432b4b181a9]::build::Builder>::expr_into_dest
  24:     0x7f5cdfb4a316 - <rustc_mir_build[2058d432b4b181a9]::build::Builder>::in_scope::<<rustc_mir_build[2058d432b4b181a9]::build::Builder>::expr_into_dest::{closure#0}::{closure#0}, ()>
  25:     0x7f5cdfb431d4 - <rustc_mir_build[2058d432b4b181a9]::build::Builder>::expr_into_dest::{closure#0}
  26:     0x7f5cdfb3f794 - <rustc_mir_build[2058d432b4b181a9]::build::Builder>::expr_into_dest
  27:     0x7f5cdfb1d658 - <rustc_mir_build[2058d432b4b181a9]::build::Builder>::ast_block_stmts
  28:     0x7f5cdfb182d5 - <rustc_mir_build[2058d432b4b181a9]::build::Builder>::ast_block
  29:     0x7f5cdfb4004e - <rustc_mir_build[2058d432b4b181a9]::build::Builder>::expr_into_dest
  30:     0x7f5cdfb4a316 - <rustc_mir_build[2058d432b4b181a9]::build::Builder>::in_scope::<<rustc_mir_build[2058d432b4b181a9]::build::Builder>::expr_into_dest::{closure#0}::{closure#0}, ()>
  31:     0x7f5cdfb431d4 - <rustc_mir_build[2058d432b4b181a9]::build::Builder>::expr_into_dest::{closure#0}
  32:     0x7f5cdfb3f794 - <rustc_mir_build[2058d432b4b181a9]::build::Builder>::expr_into_dest
  33:     0x7f5cdfb4a316 - <rustc_mir_build[2058d432b4b181a9]::build::Builder>::in_scope::<<rustc_mir_build[2058d432b4b181a9]::build::Builder> [...]

2023-06-07 09:26 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5198145840/jobs/9373897764) [(plain)](https://github.com/rust-lang/rust/commit/dd3f6ecd8eace03fdda5c0c1dabf7f151cb51992/checks/14067909935/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:8e5e7e5ab8b370d6c329ec480221332ada57f0ab)
Download action repository 'rust-lang/simpleinfra@master' (SHA:43f8ac1f8464b3b055d6ff08e29b114c62ec57f3)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  CI_JOB_NAME: mingw-check-tidy
---
Successfully tagged rust-ci:latest
Built container sha256:4810c6e25855e49483a2232d2fc702ab124376b05270013083529781812f3f56
Uploading finished image to https://ci-caches.rust-lang.org/docker/e51156f19850ce886cec818e46dc2a021e0aa7c270d15673e8fe74cd8522fc8ac3995109aebb688ee49ed586735ed4cf5f8c06d44c48298fa09c35ae4b082281

<botocore.awsrequest.AWSRequest object at 0x7fb8867284d0>
gzip: stdout: Broken pipe
xargs: docker: terminated by signal 13
[CI_JOB_NAME=mingw-check-tidy]
[CI_JOB_NAME=mingw-check-tidy]
---
   Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
    Finished release [optimized] target(s) in 15.69s
##[endgroup]
fmt check
Diff in /checkout/compiler/rustc_mir_build/src/build/matches/simplify.rs at line 19:
 use rustc_hir::RangeEnd;
 use rustc_middle::mir::ConstantKind;
 use rustc_middle::thir::{self, *};
-use rustc_middle::ty::{self, ValTree};
 use rustc_middle::ty::layout::IntegerExt;
+use rustc_middle::ty::{self, ValTree};
 use rustc_target::abi::{Integer, Size};
 use std::mem;
 use std::mem;
Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/compiler/rustc_mir_build/src/build/matches/mod.rs" "/checkout/compiler/rustc_mir_build/src/build/matches/test.rs" "/checkout/compiler/rustc_mir_build/src/build/matches/simplify.rs" "/checkout/compiler/rustc_mir_build/src/build/matches/util.rs" "/checkout/compiler/rustc_mir_build/src/thir/mod.rs" "/checkout/compiler/rustc_mir_build/src/thir/print.rs" "/checkout/compiler/rustc_mir_build/src/thir/constant.rs" "/checkout/compiler/rustc_mir_build/src/build/block.rs"` failed.
If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
```

</details>

2023-06-07 09:53 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5198496284/jobs/9374689376) [(plain)](https://github.com/rust-lang/rust/commit/457b927870463108aa079335455e70888dd1e5c7/checks/14068918647/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling object v0.30.1
   Compiling std_detect v0.1.5 (/checkout/library/stdarch/crates/std_detect)
   Compiling hashbrown v0.13.1
   Compiling addr2line v0.19.0
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in DefId(0:3000 ~ object[2286]::read::macho::section::{impl#5}::parse) (_12 = &(*(_5.0: &[u8]))): bad assignment (&[u8; 6] = &[u8]): NoSolution
   --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/object-0.30.1/src/read/macho/section.rs:220:14
    |
220 |             (b"__TEXT", b"__text") => SectionKind::Text,
    |
    = note: delayed at compiler/rustc_borrowck/src/type_check/mod.rs:1242:21
               0: <rustc_errors::HandlerInner>::emit_diagnostic
               1: <rustc_errors::Handler>::delay_span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
               1: <rustc_errors::Handler>::delay_span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
               2: <rustc_borrowck::type_check::TypeChecker>::typeck_mir
               3: rustc_borrowck::type_check::type_check
               4: rustc_borrowck::nll::compute_regions
               5: rustc_borrowck::do_mir_borrowck
               6: rustc_borrowck::mir_borrowck
               7: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
               8: <rustc_query_impl::query_impl::mir_borrowck::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
               9: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
              10: rustc_query_impl::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
              11: <core::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures::sync::par_for_each_in<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_interface::passes::analysis::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
              12: rustc_data_structures::sync::par_for_each_in::<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_interface::passes::analysis::{closure#1}::{closure#0}>::{closure#0}>
              13: rustc_interface::passes::analysis
              14: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
              15: <rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, ())>>::call_once
              16: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
              17: rustc_query_impl::query_impl::analysis::get_query_non_incr::__rust_end_short_backtrace
              18: <rustc_middle::ty::context::GlobalCtxt>::enter::<rustc_driver_impl::run_compiler::{closure#1}::{closure#2}::{closure#4}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
              20: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
              21: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
              21: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
              22: std::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
              23: <<std::thread::Builder>::spawn_unchecked_<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
              25: <unknown>
              26: <unknown>
            


error: internal compiler error: broken MIR in DefId(0:3000 ~ object[2286]::read::macho::section::{impl#5}::parse) (_16 = &(*(_5.1: &[u8]))): bad assignment (&[u8; 6] = &[u8]): NoSolution
   --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/object-0.30.1/src/read/macho/section.rs:220:25
    |
220 |             (b"__TEXT", b"__text") => SectionKind::Text,
    |
    = note: delayed at compiler/rustc_borrowck/src/type_check/mod.rs:1242:21
               0: <rustc_errors::HandlerInner>::emit_diagnostic
               1: <rustc_errors::Handler>::delay_span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
               1: <rustc_errors::Handler>::delay_span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
               2: <rustc_borrowck::type_check::TypeChecker>::typeck_mir
               3: rustc_borrowck::type_check::type_check
               4: rustc_borrowck::nll::compute_regions
               5: rustc_borrowck::do_mir_borrowck
               6: rustc_borrowck::mir_borrowck
               7: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
               8: <rustc_query_impl::query_impl::mir_borrowck::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
               9: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
              10: rustc_query_impl::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
              11: <core::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures::sync::par_for_each_in<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_interface::passes::analysis::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}> as core::ops::fu [...]

2023-06-07 19:11 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5203766264/jobs/9387083994) [(plain)](https://github.com/rust-lang/rust/commit/f58e3f7ef37c31c795370ec738485d99e010040e/checks/14084982735/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:8e5e7e5ab8b370d6c329ec480221332ada57f0ab)
Download action repository 'rust-lang/simpleinfra@master' (SHA:43f8ac1f8464b3b055d6ff08e29b114c62ec57f3)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  CI_JOB_NAME: mingw-check-tidy
---
Building wheels for collected packages: reuse
  Building wheel for reuse (pyproject.toml): started
  Building wheel for reuse (pyproject.toml): finished with status 'done'
  Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=180116 sha256=351235b2326fb4db7a18e257e13ce7896c5f77339521e2c2612e71e154800a19
  Stored in directory: /tmp/pip-ephem-wheel-cache-l1d3w2r5/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
---
Successfully tagged rust-ci:latest
Built container sha256:f60569db3089e2d33275fe93f35161ec6273b56b38fbfba7f41f2ae8e0ac3e91
Uploading finished image to https://ci-caches.rust-lang.org/docker/e51156f19850ce886cec818e46dc2a021e0aa7c270d15673e8fe74cd8522fc8ac3995109aebb688ee49ed586735ed4cf5f8c06d44c48298fa09c35ae4b082281

<botocore.awsrequest.AWSRequest object at 0x7ff92fd24350>
gzip: stdout: Broken pipe
xargs: docker: terminated by signal 13
[CI_JOB_NAME=mingw-check-tidy]
[CI_JOB_NAME=mingw-check-tidy]
---
##[endgroup]
fmt check
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/compiler/rustc_mir_build/src/build/matches/simplify.rs:309: `dbg!` macro is intended as a debugging tool. It should not be in version control.
##[error]tidy error: /checkout/compiler/rustc_mir_build/src/build/matches/simplify.rs:329: `dbg!` macro is intended as a debugging tool. It should not be in version control.
##[error]tidy error: /checkout/compiler/rustc_mir_build/src/build/matches/simplify.rs:330: `dbg!` macro is intended as a debugging tool. It should not be in version control.
some tidy checks failed
```

</details>

2023-06-08 17:02 UTC, WaffleLapkin commented
r? mir-opt

2023-06-16 09:59 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5288625389/jobs/9570574063) [(plain)](https://github.com/rust-lang/rust/commit/eb7ede9d3944233a6fd50ffb559b0dc99215bf54/checks/14317573454/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

```

</details>

2023-06-16 16:43 UTC, antoyo commented on compiler/rustc_codegen_gcc/src/lib.rs
> +
`tempfile` is used at [line 89](https://github.com/rust-lang/rust/pull/112370/files#diff-e4d3a952d65504b0ae63b6c1da8c89b2b56cbdbbfda77c6e46e1d4f348dbd09fL89) so it should not be removed.

Not sure why there's a warning emitted about this, but removing this line will result in a compilation error.

2023-07-01 11:37 UTC, cjgillot reviewed
This looks like the right place to put this change. Could you add a MIR building test, in the tests/mir-opt/build directory, so we can see the results of this change?

2023-07-01 12:51 UTC, cjgillot commented
cc @oli-obk as you manipulated that code recently.

2023-07-05 09:36 UTC, oli-obk requested changes

2023-07-05 09:36 UTC, oli-obk commented on compiler/rustc_mir_build/src/build/matches/simplify.rs
> +                    }) =>
Please create a function for this to make the pattern simpler

2023-08-15 17:55 UTC, Dylan-DPC commented
@john-h-k any updates on this?

2023-08-31 13:30 UTC, john-h-k commented
> @john-h-k any updates on this?

Sorry have been super busy the last few weeks - I am currently working on this yes

2023-08-31 23:17 UTC, john-h-k commented
@rustbot review

2023-08-31 23:17 UTC, john-h-k commented
@rustbot ready

2023-08-31 23:18 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/6043394616/job/16400323284) [(plain)](https://github.com/rust-lang/rust/commit/8968564c00f1aa4532218a0d77a7cd37c4df89fd/checks/16400323284/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=john-h-k
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_090c54cb-5e09-4aed-8bcd-ba06f3721b1f
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=ad2ea04f3882b03244a6afb7beda4d8dbf7ef1c4
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_090c54cb-5e09-4aed-8bcd-ba06f3721b1f
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_090c54cb-5e09-4aed-8bcd-ba06f3721b1f
GITHUB_TRIGGERING_ACTOR=john-h-k
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/112370/merge
GITHUB_WORKFLOW_SHA=ad2ea04f3882b03244a6afb7beda4d8dbf7ef1c4
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_18_X64=/opt/hostedtoolcache/go/1.18.10/x64
---
   Compiling addr2line v0.21.0
error[E0599]: no method named `formatter` found for struct `BacktraceFmt` in the current scope
   --> library/std/src/sys_common/backtrace.rs:102:36
    |
102 | ...                   bt_fmt.formatter(),
    |                              ^^^^^^^^^ help: there is a method with a similar name: `frame`
   ::: library/std/src/../../backtrace/src/print.rs:17:1
    |
    |
17  | pub struct BacktraceFmt<'a, 'b> {
    | ------------------------------- method `formatter` not found for this struct
error[E0308]: mismatched types
   --> library/std/src/../../backtrace/src/symbolize/gimli.rs:361:16
    |
    |
361 |         if let Ok(mut frames) = cx.dwarf.find_frames(addr as u64) {
    |                ^^^^^^^^^^^^^^   --------------------------------- this expression has type `LookupResult<impl LookupContinuation<Output = core::result::Result<FrameIter<'_, EndianSlice<'_, addr2line::gimli::LittleEndian>>, addr2line::gimli::Error>, Buf = EndianSlice<'_, addr2line::gimli::LittleEndian>>>`
    |                |
    |                expected `LookupResult<impl LookupContinuation<Output = ..., Buf = ...>>`, found `Result<_, _>`
   ::: /cargo/registry/src/index.crates.io-6f17d22bba15001f/addr2line-0.21.0/src/lib.rs:450:23
    |
    |
450 |     ) -> LookupResult<impl LookupContinuation<Output = Result<FrameIter<'_, R>, Error>, Buf = R>>
    |
    |
    = note: expected enum `LookupResult<impl LookupContinuation<Output = Result<FrameIter<'_, EndianSlice<'_, ...>>, ...>, Buf = ...>>`
            the full type name has been written to '/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/std-364bf3678bb6974d.long-type-11459368010837807095.txt'

error[E0308]: mismatched types
   --> library/std/src/../../backtrace/src/symbolize/gimli.rs:377:24
    |
    |
377 |                 if let Ok(mut frames) = object_cx.dwarf.find_frames(object_addr) {
    |                        ^^^^^^^^^^^^^^   ---------------------------------------- this expression has type `LookupResult<impl LookupContinuation<Output = core::result::Result<FrameIter<'_, EndianSlice<'_, addr2line::gimli::LittleEndian>>, addr2line::gimli::Error>, Buf = EndianSlice<'_, addr2line::gimli::LittleEndian>>>`
    |                        |
    |                        expected `LookupResult<impl LookupContinuation<Output = ..., Buf = ...>>`, found `Result<_, _>`
   ::: /cargo/registry/src/index.crates.io-6f17d22bba15001f/addr2line-0.21.0/src/lib.rs:450:23
    |
    |
450 |     ) -> LookupResult<impl LookupContinuation<Output = Result<FrameIter<'_, R>, Error>, Buf = R>>
    |
    |
    = note: expected enum `LookupResult<impl LookupContinuation<Output = Result<FrameIter<'_, EndianSlice<'_, ...>>, ...>, Buf = ...>>`
            the full type name has been written to '/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/std-364bf3678bb6974d.long-type-9201959409461949214.txt'

Some errors have detailed explanations: E0308, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `std` (lib) due to 3 previous errors
```

</details>

2023-09-01 11:12 UTC, WaffleLapkin commented
@john-h-k your PR seems to update submodules, which brakes CI. This is likely due to 8968564 commit, where you've merged master into this branch.

Please remove the merge commit (see https://rustc-dev-guide.rust-lang.org/git.html?highlight=git#i-made-a-merge-commit-by-accident) and then read docs about keeping things up to date properly (https://rustc-dev-guide.rust-lang.org/git.html?highlight=git#keeping-things-up-to-date).

@rustbot author

2023-09-04 14:22 UTC, oli-obk commented on compiler/rustc_middle/src/ty/consts.rs
> +    }
This should probably be its own PR, so we aren't mixing a restructuring with a behaviour change

2023-09-04 19:43 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-15`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/6077093445/job/16486193130) [(plain)](https://github.com/rust-lang/rust/commit/1cdaa59e37190a52fde6e59bff1a5139904314b0/checks/16486193130/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=john-h-k
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_37c6b178-8a8f-481e-b35c-00f8da068ddc
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=9757848080b64590f812d180633c8cde6025f5e8
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_37c6b178-8a8f-481e-b35c-00f8da068ddc
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_37c6b178-8a8f-481e-b35c-00f8da068ddc
GITHUB_TRIGGERING_ACTOR=john-h-k
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/112370/merge
GITHUB_WORKFLOW_SHA=9757848080b64590f812d180633c8cde6025f5e8
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_18_X64=/opt/hostedtoolcache/go/1.18.10/x64
---
   Compiling rustc_borrowck v0.0.0 (/checkout/compiler/rustc_borrowck)
error[E0599]: no method named `mk_imm_ref` found for struct `TyCtxt<'tcx>` in the current scope
   --> compiler/rustc_mir_build/src/build/matches/simplify.rs:321:37
    |
321 | ...                   tcx.mk_imm_ref(tcx.lifetimes.re_erased, tcx.mk_array(el_ty, prefix.len() as u64)),

error[E0599]: no method named `mk_array` found for struct `TyCtxt<'tcx>` in the current scope
   --> compiler/rustc_mir_build/src/build/matches/simplify.rs:321:77
    |
    |
321 | ...                   tcx.mk_imm_ref(tcx.lifetimes.re_erased, tcx.mk_array(el_ty, prefix.len() as u64)),

   Compiling rustc_privacy v0.0.0 (/checkout/compiler/rustc_privacy)
error[E0599]: no method named `mk_imm_ref` found for struct `TyCtxt<'tcx>` in the current scope
   --> compiler/rustc_mir_build/src/build/matches/simplify.rs:322:37
   --> compiler/rustc_mir_build/src/build/matches/simplify.rs:322:37
    |
322 | ...                   tcx.mk_imm_ref(tcx.lifetimes.re_erased, tcx.mk_slice(el_ty))

error[E0599]: no method named `mk_slice` found for struct `TyCtxt<'tcx>` in the current scope
   --> compiler/rustc_mir_build/src/build/matches/simplify.rs:322:77
    |
    |
322 | ...                   tcx.mk_imm_ref(tcx.lifetimes.re_erased, tcx.mk_slice(el_ty))

   Compiling rustc_hir_typeck v0.1.0 (/checkout/compiler/rustc_hir_typeck)
error[E0599]: no method named `mk_array` found for struct `TyCtxt<'tcx>` in the current scope
   --> compiler/rustc_mir_build/src/build/matches/simplify.rs:325:46
   --> compiler/rustc_mir_build/src/build/matches/simplify.rs:325:46
    |
325 | ...                   let arr_ty = tcx.mk_array(el_ty, prefix.len() as u64);

   Compiling rustc_plugin_impl v0.0.0 (/checkout/compiler/rustc_plugin_impl)
error[E0599]: no method named `mk_const` found for struct `TyCtxt<'tcx>` in the current scope
   --> compiler/rustc_mir_build/src/build/matches/simplify.rs:333:36
   --> compiler/rustc_mir_build/src/build/matches/simplify.rs:333:36
    |
333 |                     let cnst = tcx.mk_const(ty::ConstKind::Value(val), cnst_ty);
    |                                    ^^^^^^^^ help: there is a method with a similar name: `mk_const_list`
   Compiling rustc_ty_utils v0.0.0 (/checkout/compiler/rustc_ty_utils)
For more information about this error, try `rustc --explain E0599`.
error: could not compile `rustc_mir_build` (lib) due to 6 previous errors
warning: build failed, waiting for other jobs to finish...
```

</details>

2023-09-04 20:19 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-15`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/6077286372/job/16486721630) [(plain)](https://github.com/rust-lang/rust/commit/89ff2b2731ba4e14c6a61fd10a77b7c3d0d0f411/checks/16486721630/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=john-h-k
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_7648a946-df8a-4804-99d1-a24f6b9fd37a
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=487e738a66c19aea4e41eed20e5cfa61d1b1741a
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_7648a946-df8a-4804-99d1-a24f6b9fd37a
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_7648a946-df8a-4804-99d1-a24f6b9fd37a
GITHUB_TRIGGERING_ACTOR=john-h-k
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/112370/merge
GITHUB_WORKFLOW_SHA=487e738a66c19aea4e41eed20e5cfa61d1b1741a
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_18_X64=/opt/hostedtoolcache/go/1.18.10/x64
---
   Compiling std_detect v0.1.5 (/checkout/library/stdarch/crates/std_detect)
   Compiling hashbrown v0.14.0
   Compiling object v0.32.0
   Compiling addr2line v0.21.0
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in DefId(0:3299 ~ object[297f]::read::macho::section::{impl#5}::parse) (Terminator { source_info: SourceInfo { span: /cargo/registry/src/index.crates.io-6f17d22bba15001f/object-0.32.0/src/read/macho/section.rs:223:14: 223:23 (#0), scope: scope[0] }, kind: _11 = <[u8] as PartialEq>::eq(_5, move _10) -> [return: bb3, unwind: bb72] }): bad arg #0 (&[u8] <- (&[u8], &[u8])): NoSolution
   --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/object-0.32.0/src/read/macho/section.rs:223:14
    |
223 |             (b"__TEXT", b"__text") => SectionKind::Text,
    |
note: delayed at compiler/rustc_borrowck/src/type_check/mod.rs:1582:17
         0: <rustc_errors::HandlerInner>::emit_diagnostic
         1: <rustc_errors::Handler>::delay_span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
         1: <rustc_errors::Handler>::delay_span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
         2: <rustc_borrowck::type_check::TypeChecker>::check_terminator
         3: <rustc_borrowck::type_check::TypeChecker>::typeck_mir
         4: rustc_borrowck::type_check::type_check
         5: rustc_borrowck::nll::compute_regions
         6: rustc_borrowck::do_mir_borrowck
         7: rustc_borrowck::mir_borrowck
         8: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
         9: <rustc_query_impl::query_impl::mir_borrowck::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
        10: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        11: rustc_query_impl::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
        12: <core::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures::sync::par_for_each_in<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_interface::passes::analysis::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
        13: std::panicking::try::<(), core::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures::sync::par_for_each_in<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_interface::passes::analysis::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}>>
        14: rustc_data_structures::sync::par_for_each_in::<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_interface::passes::analysis::{closure#1}::{closure#0}>::{closure#0}>
        16: rustc_interface::passes::analysis
        17: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 1]>>
        18: <rustc_query_impl::query_impl::analysis::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, ())>>::call_once
        19: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::SingleCache<rustc_middle::query::erase::Erased<[u8; 1]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
---
        27: <unknown>
        28: <unknown>
   --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/object-0.32.0/src/read/macho/section.rs:223:14
    |
223 |             (b"__TEXT", b"__text") => SectionKind::Text,


error: internal compiler error: broken MIR in DefId(0:3299 ~ object[297f]::read::macho::section::{impl#5}::parse) (Terminator { source_info: SourceInfo { span: /cargo/registry/src/index.crates.io-6f17d22bba15001f/object-0.32.0/src/read/macho/section.rs:223:25: 223:34 (#0), scope: scope[0] }, kind: _13 = <[u8] as PartialEq>::eq(_5, move _12) -> [return: bb5, unwind: bb72] }): bad arg #0 (&[u8] <- (&[u8], &[u8])): NoSolution
   --> /cargo/registry/src/index.crates.io-6f17d22bba15001f/object-0.32.0/src/read/macho/section.rs:223:25
    |
223 |             (b"__TEXT", b"__text") => SectionKind::Text,
    |
note: delayed at compiler/rustc_borrowck/src/type_check/mod.rs:1582:17
         0: <rustc_errors::HandlerInner>::emit_diagnostic
         1: <rustc_errors::Handler>::delay_span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
         1: <rustc_errors::Handler>::delay_span_bug::<rustc_span::span_encoding::Span, alloc::string::String>
         2: <rustc_borrowck::type_check::TypeChecker>::check_terminator
         3: <rustc_borrowck::type_check::TypeChecker>::typeck_mir
         4: rustc_borrowck::type_check::type_check
         5: rustc_borrowck::nll::compute_regions
         6: rustc_borrowck::do_mir_borrowck
         7: rustc_borrowck::mir_borrowck
         8: rustc_query_impl::plumbing::__rust_begin_short_backtrace::<rustc_query_impl::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
         9: <rustc_query_impl::query_impl::mir_borrowck::dynamic_query::{closure#2} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
        10: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::DynamicConfig<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>, false, false, false>, rustc_query_impl::plumbing::QueryCtxt, false>
        11: rustc_query_impl::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
        12: <core::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures::sync::par_for_each_in<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_interface::passes::analysis::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
        13: std::panicking::try::<(), core::panic::unwind_safe::AssertUnwindSafe<rustc_data_structures::sync::par_for_each_in<&[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par [...]

2023-09-04 20:19 UTC, john-h-k commented
@rustbot review

2023-09-05 07:34 UTC, oli-obk commented on compiler/rustc_middle/src/ty/consts.rs
> +pub struct Const<'tcx>(pub Interned<'tcx, ConstData<'tcx>>);
this has still not been addressed

2023-09-05 07:36 UTC, oli-obk commented
Please add a mir-opt test that shows the bad MIR in a commit before your main commit (which should also get a meaningful commit message). Then your commit will change the MIR of the new test, and thus demonstrate how your PR changes things.

2023-09-05 07:38 UTC, oli-obk commented on compiler/rustc_middle/src/ty/consts/valtree.rs
> +    pub fn from_scalars<'a>(tcx: TyCtxt<'tcx>, scalars: &'a [ScalarInt]) -> Self {
```suggestion
    pub fn from_scalars(tcx: TyCtxt<'tcx>, scalars: impl IntoIter<Item = ScalarInt>) -> Self {
```

then you can avoid `collect` at the call sites to `from_scalars`

2023-09-05 07:40 UTC, oli-obk commented
@rustbot author

2023-11-12 18:41 UTC, JohnCSimon commented
@john-h-k 
ping from triage - can you post your status on this PR? There hasn't been an update in a few months. Thanks!


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

2024-02-11 21:39 UTC, closed without merging