Extend `unused_must_use` to cover block exprs
rust-lang/rust pull request #112529
Opened 2023-06-11 15:52 UTC by jieyouxu

Given code like

```rust
#[must_use]
fn foo() -> i32 {
    42
}

fn warns() {
    {
        bar();
    }
}

fn does_not_warn() {
    {
        bar()
    };
}

fn main() {
    warns();
    does_not_warn();
}
```

### Before This PR

```
warning: unused return value of `foo` that must be used
 --> test.rs:8:9
  |
8 |         foo();
  |         ^^^^^
  |
  = note: `#[warn(unused_must_use)]` on by default
help: use `let _ = ...` to ignore the resulting value
  |
8 |         let _ = foo();
  |         +++++++

warning: 1 warning emitted
```

### After This PR

```
warning: unused return value of `foo` that must be used
 --> test.rs:8:9
  |
8 |         foo();
  |         ^^^^^
  |
  = note: `#[warn(unused_must_use)]` on by default
help: use `let _ = ...` to ignore the resulting value
  |
8 |         let _ = foo();
  |         +++++++

warning: unused return value of `foo` that must be used
  --> test.rs:14:9
   |
14 |         foo()
   |         ^^^^^
   |
help: use `let _ = ...` to ignore the resulting value
   |
14 |         let _ = foo();
   |         +++++++      +

warning: 2 warnings emitted
```

Fixes #104253.

2023-06-11 16:01 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-14`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5236292138/jobs/9453724478) [(plain)](https://github.com/rust-lang/rust/commit/384a962b37bffaa9a1b9bc1cf0b776284d4905c6/checks/14168781895/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling rustc_arena v0.0.0 (/checkout/compiler/rustc_arena)
   Compiling elsa v1.7.1
   Compiling rustc_graphviz v0.0.0 (/checkout/compiler/rustc_graphviz)
   Compiling ppv-lite86 v0.2.8
error: unused return value of `Box::<T>::from_raw` that must be used
  --> compiler/rustc_arena/src/lib.rs:70:18
   |
70 |         unsafe { Box::from_raw(self.storage.as_mut()) };
   |
   |
   = note: call `drop(Box::from_raw(ptr))` if you intend to drop the `Box`
   = note: `-D unused-must-use` implied by `-D warnings`
   |
   |
70 |         unsafe { let _ = Box::from_raw(self.storage.as_mut()); };

error: could not compile `rustc_arena` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
Build completed unsuccessfully in 0:04:46
```

</details>

2023-06-11 16:28 UTC, jieyouxu commented
```
error: unused return value of `Box::<T>::from_raw` that must be used
  --> compiler/rustc_arena/src/lib.rs:70:18
   |
70 |         unsafe { Box::from_raw(self.storage.as_mut()) };
   |
   |
   = note: call `drop(Box::from_raw(ptr))` if you intend to drop the `Box`
   = note: `-D unused-must-use` implied by `-D warnings`
   |
   |
70 |         unsafe { let _ = Box::from_raw(self.storage.as_mut()); };
```

I *think* that's a true positive (can just surround with `drop` right?)?

2023-06-12 01:07 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-14`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5238388139/jobs/9457228898) [(plain)](https://github.com/rust-lang/rust/commit/6c0877427e0b4938b5eb2165758b8751d2c450de/checks/14172926519/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
1 warning: unused closure that must be used
-   --> $DIR/issue-1460.rs:6:5
+   --> $DIR/issue-1460.rs:6:6
3    |
4 LL |     {|i: u32| if 1 == i { }};
+    |      ^^^^^^^^^^^^^^^^^^^^^^
6    |
6    |
7    = note: closures are lazy and do nothing unless called


The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-1460/issue-1460.stderr
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-1460/issue-1460.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args issues/issue-1460.rs`

error: 1 errors occurred comparing output.
status: exit status: 0
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/issues/issue-1460.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "-O" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--remap-path-prefix=/checkout/tests/ui=fake-test-src-base" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-1460/a" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-1460/auxiliary"
stdout: none
warning: unused closure that must be used
  --> fake-test-src-base/issues/issue-1460.rs:6:6
   |
   |
LL |     {|i: u32| if 1 == i { }}; //~ WARN unused closure that must be used
   |
   |
   = note: closures are lazy and do nothing unless called

warning: 1 warning emitted
------------------------------------------

```

</details>

2023-06-12 02:10 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5238681962/jobs/9457809827) [(plain)](https://github.com/rust-lang/rust/commit/a1f27e51829b2759e09a5fca951d175932dca022/checks/14173605081/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
---- compile_test stdout ----

error: failed to compile fixed code
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/clippy-driver" "tests/ui/transmute_ptr_to_ref.fixed" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/test/ui" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/test/ui/transmute_ptr_to_ref.stage-id" "--emit=metadata" "-Dwarnings" "-Zui-testing" "-L" "dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps" "-L" "dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps" "--extern" "futures=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libfutures-6852192f287894c5.rlib" "--extern" "clippy_utils=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libclippy_utils-f526ecdec9f40307.rlib" "--extern" "clippy_lints=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libclippy_lints-8b8fb9fee8fae818.rlib" "--extern" "parking_lot=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libparking_lot-99b4ecdc23ace320.rlib" "--extern" "itertools=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libitertools-fb10fdad47631eb1.rlib" "--extern" "rustc_semver=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/librustc_semver-a56d3589f499fdc9.rlib" "--extern" "quote=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libquote-7a458793eed2881a.rlib" "--extern" "syn=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libsyn-8a4509e3e9b17a38.rlib" "--extern" "regex=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libregex-316eeb295423eac0.rlib" "--extern" "if_chain=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libif_chain-1ee24896911f1da8.rlib" "--extern" "tokio=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libtokio-8ed01b34898266df.rlib" "--extern" "serde=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libserde-9707ce7ca6641907.rlib" "--extern" "serde_derive=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/libserde_derive-f011e477ebb71b20.so" "--extern" "derive_new=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/libderive_new-faf64bbe743eac37.so" "--edition=2021" "--crate-name=fixed" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/test/ui/transmute_ptr_to_ref.stage-id.aux"
------------------------------------------

------------------------------------------
stderr:
stderr:
------------------------------------------
{"message":"unused borrow that must be used","code":{"code":"unused_must_use","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/transmute_ptr_to_ref.fixed","byte_start":917,"byte_end":937,"line_start":41,"line_end":41,"column_start":14,"column_end":34,"is_primary":true,"text":[{"text":"    unsafe { &*(raw as *const u8) };","highlight_start":14,"highlight_end":34}],"label":"the borrow produces a value","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"`-D unused-must-use` implied by `-D warnings`","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"use `let _ = ...` to ignore the resulting value","code":null,"level":"help","spans":[{"file_name":"tests/ui/transmute_ptr_to_ref.fixed","byte_start":917,"byte_end":917,"line_start":41,"line_end":41,"column_start":14,"column_end":14,"is_primary":true,"text":[{"text":"    unsafe { &*(raw as *const u8) };","highlight_start":14,"highlight_end":14}],"label":null,"suggested_replacement":"let _ = ","suggestion_applicability":"MaybeIncorrect","expansion":null},{"file_name":"tests/ui/transmute_ptr_to_ref.fixed","byte_start":937,"byte_end":937,"line_start":41,"line_end":41,"column_start":34,"column_end":34,"is_primary":true,"text":[{"text":"    unsafe { &*(raw as *const u8) };","highlight_start":34,"highlight_end":34}],"label":null,"suggested_replacement":";","suggestion_applicability":"MaybeIncorrect","expansion":null}],"children":[],"rendered":null}],"rendered":"error: unused borrow that must be used\n  --> tests/ui/transmute_ptr_to_ref.fixed:41:14\n   |\nLL |     unsafe { &*(raw as *const u8) };\n   |              ^^^^^^^^^^^^^^^^^^^^ the borrow produces a value\n   |\n   = note: `-D unused-must-use` implied by `-D warnings`\nhelp: use `let _ = ...` to ignore the resulting value\n   |\nLL |     unsafe { let _ = &*(raw as *const u8); };\n   |              +++++++                     +\n\n"}

------------------------------------------

thread 'compile_test' panicked at 'Some tests failed', /cargo/registry/src/index.crates.io-6f17d22bba15001f/compiletest_rs-0.10.0/src/lib.rs:111:22
```

</details>

2023-06-15 07:34 UTC, oli-obk requested changes

2023-06-15 07:34 UTC, oli-obk commented on compiler/rustc_arena/src/lib.rs
> +        unsafe { drop(Box::from_raw(self.storage.as_mut())) };
```suggestion
        unsafe { drop(Box::from_raw(self.storage.as_mut())) }
```

2023-06-15 08:14 UTC, oli-obk commented
@bors r+

2023-06-15 08:17 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5276285408/jobs/9542795215) [(plain)](https://github.com/rust-lang/rust/commit/fc6b5315b2f2e4eedb923dbb25bf6a518e53e02e/checks/14281903237/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
---- compile_test stdout ----

error: failed to compile fixed code
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/clippy-driver" "tests/ui/transmute_ptr_to_ref.fixed" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/test/ui" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/test/ui/transmute_ptr_to_ref.stage-id" "--emit=metadata" "-Dwarnings" "-Zui-testing" "-L" "dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps" "-L" "dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps" "--extern" "rustc_semver=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/librustc_semver-a56d3589f499fdc9.rlib" "--extern" "serde=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libserde-9707ce7ca6641907.rlib" "--extern" "if_chain=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libif_chain-1ee24896911f1da8.rlib" "--extern" "derive_new=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/libderive_new-faf64bbe743eac37.so" "--extern" "parking_lot=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libparking_lot-99b4ecdc23ace320.rlib" "--extern" "clippy_lints=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libclippy_lints-8b8fb9fee8fae818.rlib" "--extern" "serde_derive=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps/libserde_derive-f011e477ebb71b20.so" "--extern" "clippy_utils=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libclippy_utils-f526ecdec9f40307.rlib" "--extern" "futures=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libfutures-6852192f287894c5.rlib" "--extern" "quote=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libquote-7a458793eed2881a.rlib" "--extern" "syn=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libsyn-8a4509e3e9b17a38.rlib" "--extern" "tokio=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libtokio-8ed01b34898266df.rlib" "--extern" "regex=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libregex-316eeb295423eac0.rlib" "--extern" "itertools=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libitertools-fb10fdad47631eb1.rlib" "--edition=2021" "--crate-name=fixed" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/test/ui/transmute_ptr_to_ref.stage-id.aux"
------------------------------------------

------------------------------------------
stderr:
stderr:
------------------------------------------
{"message":"unused borrow that must be used","code":{"code":"unused_must_use","explanation":null},"level":"error","spans":[{"file_name":"tests/ui/transmute_ptr_to_ref.fixed","byte_start":917,"byte_end":937,"line_start":41,"line_end":41,"column_start":14,"column_end":34,"is_primary":true,"text":[{"text":"    unsafe { &*(raw as *const u8) };","highlight_start":14,"highlight_end":34}],"label":"the borrow produces a value","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"`-D unused-must-use` implied by `-D warnings`","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"use `let _ = ...` to ignore the resulting value","code":null,"level":"help","spans":[{"file_name":"tests/ui/transmute_ptr_to_ref.fixed","byte_start":917,"byte_end":917,"line_start":41,"line_end":41,"column_start":14,"column_end":14,"is_primary":true,"text":[{"text":"    unsafe { &*(raw as *const u8) };","highlight_start":14,"highlight_end":14}],"label":null,"suggested_replacement":"let _ = ","suggestion_applicability":"MaybeIncorrect","expansion":null},{"file_name":"tests/ui/transmute_ptr_to_ref.fixed","byte_start":937,"byte_end":937,"line_start":41,"line_end":41,"column_start":34,"column_end":34,"is_primary":true,"text":[{"text":"    unsafe { &*(raw as *const u8) };","highlight_start":34,"highlight_end":34}],"label":null,"suggested_replacement":";","suggestion_applicability":"MaybeIncorrect","expansion":null}],"children":[],"rendered":null}],"rendered":"error: unused borrow that must be used\n  --> tests/ui/transmute_ptr_to_ref.fixed:41:14\n   |\nLL |     unsafe { &*(raw as *const u8) };\n   |              ^^^^^^^^^^^^^^^^^^^^ the borrow produces a value\n   |\n   = note: `-D unused-must-use` implied by `-D warnings`\nhelp: use `let _ = ...` to ignore the resulting value\n   |\nLL |     unsafe { let _ = &*(raw as *const u8); };\n   |              +++++++                     +\n\n"}

------------------------------------------

thread 'compile_test' panicked at 'Some tests failed', /cargo/registry/src/index.crates.io-6f17d22bba15001f/compiletest_rs-0.10.0/src/lib.rs:111:22
```

</details>

2023-06-15 08:18 UTC, oli-obk commented
@bors r-

2023-06-15 08:18 UTC, oli-obk commented
you need to bless the clippy tests: `x test clippy --bless`

2023-06-15 08:39 UTC, klensy commented
Can you fix first message? In your example `foo()` unused.

2023-06-15 08:56 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-14`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5276650700/jobs/9543644076) [(plain)](https://github.com/rust-lang/rust/commit/85cf7137c57393f69467023df504da70f23e6e12/checks/14282974815/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling rand v0.8.5
   Compiling alloc v0.0.0 (/checkout/library/alloc)
   Compiling std v0.0.0 (/checkout/library/std)
   Compiling core v0.0.0 (/checkout/library/core)
error: unused return value of `Box::<T>::from_raw` that must be used
     |
     |
1004 |     unsafe { Box::from_raw(p.pointer().as_ptr()) };
     |
     |
     = note: call `drop(Box::from_raw(ptr))` if you intend to drop the `Box`
     = note: `-D unused-must-use` implied by `-D warnings`
     |
     |
1004 |     unsafe { let _ = Box::from_raw(p.pointer().as_ptr()); };

error: could not compile `core` (test "coretests") due to previous error
warning: build failed, waiting for other jobs to finish...
Build completed unsuccessfully in 0:14:55
```

</details>

2023-06-15 09:37 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5277042442/jobs/9544547901) [(plain)](https://github.com/rust-lang/rust/commit/fc29bfea34c2ede575513b0f0214c6079a45a9b4/checks/14284130882/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
tests/fail/tokio/sleep.rs ... ok
tests/fail/panic/double_panic.rs ... ok

tests/fail/dangling_pointers/storage_dead_dangling.rs FAILED:
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/miri" "--error-format=json" "-Dwarnings" "-Dunused" "-Zui-testing" "--target" "x86_64-unknown-linux-gnu" "--extern" "getrandom=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/libgetrandom-8197e2dce1dfb558.rlib" "--extern" "getrandom=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/libgetrandom-8197e2dce1dfb558.rmeta" "--extern" "getrandom_1=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/libgetrandom-19aeac02a6c0ffc3.rlib" "--extern" "getrandom_1=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/libgetrandom-19aeac02a6c0ffc3.rmeta" "--extern" "libc=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/liblibc-ef2fbe160fcdd653.rlib" "--extern" "libc=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/liblibc-ef2fbe160fcdd653.rmeta" "--extern" "num_cpus=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/libnum_cpus-54bb73fbdf6df9ac.rlib" "--extern" "num_cpus=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/libnum_cpus-54bb73fbdf6df9ac.rmeta" "--extern" "rand=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/librand-0ff886e7eaab9922.rlib" "--extern" "rand=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/librand-0ff886e7eaab9922.rmeta" "--extern" "page_size=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/libpage_size-6a0f79efa3d70627.rlib" "--extern" "page_size=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/libpage_size-6a0f79efa3d70627.rmeta" "--extern" "tokio=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/libtokio-c06a3f45b0e19bd7.rlib" "--extern" "tokio=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/libtokio-c06a3f45b0e19bd7.rmeta" "--extern" "miri_test_deps=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/miri-test-deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/debug/build/lock_api-67529c054bcce400" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/debug/build/tokio-644c63a1da1ce210" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/debug/build/proc-macro2-88560543811a7474" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/debug/build/getrandom-3c088a94c925444e" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/debug/build/quote-059f15a9694b54ae" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/debug/build/parking_lot_core-057742f3b212972a" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/debug/build/log-1ec6f959fa319c8e" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/debug/deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/debug/build/syn-2407d38215cd42b2" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/debug/build/memchr-8c21ca7640ca0068" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/debug/build/libc-117bf3c154c8368e" "tests/fail/dangling_pointers/storage_dead_dangling.rs" "-Zmiri-disable-validation" "-Zmir-opt-level=0" "-Zmiri-permissive-provenance" "--edition" "2021"





actual output differed from expected
--- tests/fail/dangling_pointers/storage_dead_dangling.stderr
+++ <stderr output>
-error: Undefined Behavior: dereferencing pointer failed: $HEX[noalloc] is a dangling pointer (it has no provenance)
   --> $DIR/storage_dead_dangling.rs:LL:CC
    |
    |
 LL |     unsafe { &mut *(LEAK as *mut i32) };
-   |              ^^^^^^^^^^^^^^^^^^^^^^^^ dereferencing pointer failed: $HEX[noalloc] is a dangling pointer (it has no provenance)
    |
-   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
-   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
-   = note: BACKTRACE:
-   = note: BACKTRACE:
-   = note: inside `evil` at $DIR/storage_dead_dangling.rs:LL:CC
-  --> $DIR/storage_dead_dangling.rs:LL:CC
-  --> $DIR/storage_dead_dangling.rs:LL:CC
+   = note: `-D unused-must-use` implied by `-D unused`
    |
    |
-LL |     evil();
-   |     ^^^^^^
+LL |     unsafe { let _ = &mut *(LEAK as *mut i32); };
 
-note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace
-note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace
+error: miri cannot be run on programs that fail compilation
~error: aborting due to 2 previous errors
 
 



substring `is a dangling pointer` not found in stderr output
expected because of pattern here: tests/fail/dangling_pointers/storage_dead_dangling.rs:13

There were 1 unmatched diagnostics that occurred outside the testfile and had no pattern
    Error: miri cannot be run on programs that fail compilation
There were 1 unmatched diagnostics at tests/fail/dangling_pointers/storage_dead_dangling.rs:13
    Error: unused borrow that must be used

full stderr:
full stderr:
error: unused borrow that must be used
  --> tests/fail/dangling_pointers/storage_dead_dangling.rs:13:14
   |
LL |     unsafe { &mut *(LEAK as *mut i32) };
   |
   |
   = note: `-D unused-must-use` implied by `-D unused`
   |
   |
LL |     unsafe { let _ = &mut *(LEAK as *mut i32); };


error: miri cannot be run on programs that fail compilation
error: aborting due to 2 previous errors





tests/fail/intrinsics/uninit_uninhabited_type.rs FAILED:
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/miri" "--error-format=json" "-Dwarnings" "-Dunused" "-Zui-testing" "--target" "x86_64-unknown-linux-gnu" "--extern" "getrandom=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/libgetrandom-8197e2dce1dfb558.rlib" "--extern" "getrandom=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/libgetrandom-8197e2dce1dfb558.rmeta" "--extern" "getrandom_1=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/libgetrandom-19aeac02a6c0ffc3.rlib" "--extern" "getrandom_1=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/libgetrandom-19aeac02a6c0ffc3.rmeta" "--extern" "libc=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/liblibc-ef2fbe160fcdd653.rlib" "--extern" "libc=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/debug/deps/liblibc-ef2fbe160fcdd653.rmeta" "--extern" "num_cpus=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/miri/x86_64-unknown-linux-gnu/de [...]

2023-06-15 10:02 UTC, oli-obk commented
@bors r+

2023-06-15 10:44 UTC, RalfJung commented on src/tools/miri/tests/fail/dangling_pointers/storage_dead_dangling.stderr
> +LL |     let _ = unsafe { &mut *(LEAK as *mut i32) };
FWIW, adding `let _` here is not always obviously the right choice: there are cases where `*y;` is UB but `let _ = *y;` is fine. Using `*y;` as a statement is equivalent to `let _unused = *y;`, not to `let _ = *y;`.

However, only "fail" tests were changed in Miri, so if UB was accidentally removed we would have noticed.

2023-06-16 01:55 UTC, merged