Move WF/ConstEvaluatable goal to clause
rust-lang/rust pull request #112667
Opened 2023-06-15 17:06 UTC by compiler-errors

It can show up in a param-env, so I think it needs to be a clause kind.

r? @lcnr or @oli-obk

2023-06-15 17:09 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5281624070/jobs/9555462131) [(plain)](https://github.com/rust-lang/rust/commit/437eaa0095de4cfc1b46d9387299aa3839b1d9a6/checks/14298229488/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:c85c95e3d7251135ab7dc9ce3241c5835cc595a9)
Download action repository 'rust-lang/simpleinfra@master' (SHA:5aa3313339663c490d58f9face5433f8c68a95e9)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  CI_JOB_NAME: mingw-check-tidy
---
Building wheels for collected packages: reuse
  Building wheel for reuse (pyproject.toml): started
  Building wheel for reuse (pyproject.toml): finished with status 'done'
  Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=180116 sha256=351235b2326fb4db7a18e257e13ce7896c5f77339521e2c2612e71e154800a19
  Stored in directory: /tmp/pip-ephem-wheel-cache-90qqqnq_/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
---
Successfully tagged rust-ci:latest
Built container sha256:a04610695766430472599b0f49ce02acbda41a1384df0d9a8cba2043277c82fb
Uploading finished image to https://ci-caches.rust-lang.org/docker/e51156f19850ce886cec818e46dc2a021e0aa7c270d15673e8fe74cd8522fc8ac3995109aebb688ee49ed586735ed4cf5f8c06d44c48298fa09c35ae4b082281

<botocore.awsrequest.AWSRequest object at 0x7f676fb9fed0>
gzip: stdout: Broken pipe
xargs: docker: terminated by signal 13
[CI_JOB_NAME=mingw-check-tidy]
[CI_JOB_NAME=mingw-check-tidy]
---
##[endgroup]
fmt check
tidy check
tidy: Skipping binary file check, read-only filesystem
tidy error: /checkout/compiler/rustc_hir_analysis/src/astconv/mod.rs: too many lines (3001) (add `// ignore-tidy-filelength` to the file to suppress this error)
some tidy checks failed
```

</details>

2023-06-15 17:15 UTC, compiler-errors commented
astconv is too large :facepalm:

2023-06-16 15:31 UTC, oli-obk requested changes
r=me with tidy happy

2023-06-16 15:31 UTC, oli-obk commented on compiler/rustc_lint/src/builtin.rs
>                      // FIXME(generic_const_exprs): `ConstEvaluatable` can be written
this needs to be moved up, too

2023-06-16 18:25 UTC, compiler-errors commented
Moved some files around astconv to appease tidy, since that file is huge.

r? @oli-obk @bors r=oli-obk

2023-06-17 16:27 UTC, matthiaskrgr commented
@bors r-
maybe needs rebase?  https://github.com/rust-lang/rust/actions/runs/5299075781/jobs/9591818074#step:25:1355

2023-06-17 21:36 UTC, compiler-errors commented
Yeah, conflicted with another pr.

@bors r=lcnr

2023-06-18 12:45 UTC, merged