More codegen cleanups
rust-lang/rust pull request #112830
Opened 2023-06-20 08:28 UTC by nnethercote

Some additional cleanups I found while looking closely at this code, following up from #112827.

r= @oli-obk

2023-06-20 08:39 UTC, oli-obk requested changes
r=me with nit

2023-06-20 08:39 UTC, oli-obk commented on compiler/rustc_interface/src/queries.rs
> +            ongoing_codegen: ongoing_codegen,
This diff is not necessary

2023-06-20 08:40 UTC, oli-obk commented
r? @oli-obk

2023-06-21 01:30 UTC, nnethercote commented on compiler/rustc_interface/src/queries.rs
> +            ongoing_codegen: ongoing_codegen,
:+1:

2023-06-21 01:31 UTC, nnethercote commented
The first commit caused the crash, and I don't understand why. I have removed it, I'll try doing it in a separate PR. The other two commits can be merged here.

@bors r=oli-obk rollup

2023-06-21 10:53 UTC, merged

2023-06-21 23:57 UTC, nnethercote commented
> The first commit caused the crash, and I don't understand why. I have removed it, I'll try doing it in a separate PR.

It was because I changed the type of `__rustc_codegen_backend` but didn't also change its callers. (This isn't caught by the type checker because of the code structure.) I found a simpler way to do it that doesn't change the type in #112913.