Rewrite `UnDerefer`
rust-lang/rust pull request #112882
Opened 2023-06-21 08:37 UTC by DrMeepster

Currently, `UnDerefer` is used by drop elaboration to undo the effects of the `Derefer` pass. However, it just recreates the original places with derefs in the middle of the projection. Because `ProjectionElem::Deref` is intended to be removed completely in the future, this will not work forever.

This PR introduces a `deref_chain` method that returns the places behind `DerefTemp` locals in a place and rewrites the move path code to use this. In the process, `UnDerefer` was merged into `MovePathLookup`. Now that move paths use the same places as in the MIR, the other uses of `UnDerefer` no longer require it.

See #98145 
cc @ouz-a
r? @oli-obk

2023-06-21 09:26 UTC, oli-obk requested changes
wonderful! thank you

r=me with a nit

2023-06-21 09:26 UTC, oli-obk commented on compiler/rustc_mir_dataflow/src/move_paths/mod.rs
> +            .expect(&format!("base local ({local:?}) of deref_chain should not be a deref temp"));
```suggestion
            .unwrap_or_else(|| bug!("base local ({local:?}) of deref_chain should not be a deref temp"));
```

2023-06-21 09:45 UTC, oli-obk commented
@bors delegate+

2023-06-21 20:11 UTC, DrMeepster commented
@bors r=@oli-obk

2023-06-22 14:42 UTC, oli-obk commented
looks like there's an infinite recursion somewhere when building `cargo`. Gonna be a pain to minimize, so I'd be fine with an explanation of the fix even without a test, but if you can reverse engineer a test, all the better.

2023-06-27 05:43 UTC, oli-obk commented
I've seen the sefault elsewhere on MIPS, too, so it's not this PRs fault.

r=me after a rebase

2023-06-30 03:12 UTC, DrMeepster commented
@bors r=oli-obk

2023-06-30 03:14 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5418898772/jobs/9851462656) [(plain)](https://github.com/rust-lang/rust/commit/b4bd2ae8237937ec102622c6fc370c6b9b4a0ed0/checks/14675144446/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:c85c95e3d7251135ab7dc9ce3241c5835cc595a9)
Download action repository 'actions/upload-artifact@v3' (SHA:0b7f8abb1508181956e8e162db84b466c27e18ce)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  CI_JOB_NAME: mingw-check-tidy
---
Building wheels for collected packages: reuse
  Building wheel for reuse (pyproject.toml): started
  Building wheel for reuse (pyproject.toml): finished with status 'done'
  Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=180116 sha256=351235b2326fb4db7a18e257e13ce7896c5f77339521e2c2612e71e154800a19
  Stored in directory: /tmp/pip-ephem-wheel-cache-v31huon4/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
---
Successfully tagged rust-ci:latest
Built container sha256:eb185678bc0ec1f364200d5d81ab09b9c0ab64697b33b7129d4bfb8205cbe854
Uploading finished image to https://ci-caches.rust-lang.org/docker/39289e18f1ac1b1a573d1a3c658528cab0cbfec4029e2def8ed615ecd4b1295e23213ab5b134f4a50a4bd45af0a8a4266b7571ba256dc217696d0f040efcd003

<botocore.awsrequest.AWSRequest object at 0x7ff2fe67afd0>
gzip: stdout: Broken pipe
xargs: docker: terminated by signal 13
[CI_JOB_NAME=mingw-check-tidy]
[CI_JOB_NAME=mingw-check-tidy]
---
   Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
    Finished release [optimized] target(s) in 15.73s
##[endgroup]
fmt check
##[error]Diff in /checkout/compiler/rustc_mir_dataflow/src/move_paths/builder.rs at line 122:
                     ty::Ref(..) | ty::RawPtr(..) => {
                         return Err(MoveError::cannot_move_out_of(
                             self.loc,
-                            BorrowedContent { target_place: place_ref.project_deeper(&[elem], tcx) },
+                            BorrowedContent {
+                                target_place: place_ref.project_deeper(&[elem], tcx),
                         ));
                     }
                     }
                     ty::Adt(adt, _) if adt.has_dtor(tcx) && !adt.is_box() => {
##[error]Diff in /checkout/compiler/rustc_mir_dataflow/src/move_paths/builder.rs at line 157:
 
                 if union_path.is_none() {
                 if union_path.is_none() {
-                    base = self.add_move_path(base, elem, |tcx| place_ref.project_deeper(&[elem], tcx));
+                    base = self
+                        .add_move_path(base, elem, |tcx| place_ref.project_deeper(&[elem], tcx));
             }
         }
         }
Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/compiler/rustc_transmute/src/layout/tree/tests.rs" "/checkout/compiler/rustc_hir_pretty/src/lib.rs" "/checkout/compiler/rustc_mir_dataflow/src/move_paths/abs_domain.rs" "/checkout/compiler/rustc_mir_dataflow/src/move_paths/mod.rs" "/checkout/compiler/rustc_mir_dataflow/src/move_paths/builder.rs" "/checkout/compiler/rustc_mir_dataflow/src/lib.rs" "/checkout/compiler/rustc_mir_dataflow/src/elaborate_drops.rs" "/checkout/compiler/rustc_transmute/src/layout/dfa.rs"` failed.
If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
```

</details>

2023-06-30 05:00 UTC, oli-obk commented
@bors r- needs rustfmt

2023-06-30 05:21 UTC, DrMeepster commented
r+'ing with bad formatting is embarrassing :/

@bors r=oli-obk

2023-07-01 22:43 UTC, rust-log-analyzer commented
A job failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/5432456007/jobs/9881113763) [(plain)](https://github.com/rust-lang-ci/rust/commit/9cd26714f9fba2a576bcea3f534c3f574f8ca1d8/checks/14712041027/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

```

</details>

2023-07-02 06:43 UTC, oli-obk commented
@bors retry apple builder timeout

2023-07-02 18:13 UTC, rust-log-analyzer commented
The job **`dist-mips64el-linux`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/5437811701/jobs/9888611391) [(plain)](https://github.com/rust-lang-ci/rust/commit/274c66334bf54efc3ac3839fc270c447b5890ade/checks/14720793464/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling git2-curl v0.18.0
[RUSTC-TIMING] git2_curl test:false 0.949
[RUSTC-TIMING] git2 test:false 6.819
[RUSTC-TIMING] gix test:false 15.340
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0xd4b163)[0x7fe35190d163]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fe35084d520]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0x1d26691)[0x7fe3528e8691]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0x1d44445)[0x7fe352906445]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0x1d59b19)[0x7fe35291bb19]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0x1c67a9a)[0x7fe352829a9a]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0x1c73c75)[0x7fe352835c75]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0x1c7510f)[0x7fe35283710f]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0x1d6c242)[0x7fe35292e242]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0x1d6f18a)[0x7fe35293118a]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0x1d715c6)[0x7fe3529335c6]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0x389357f)[0x7fe35445557f]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0x1fb3e64)[0x7fe352b75e64]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0x2f97530)[0x7fe353b59530]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0x2f976a4)[0x7fe353b596a4]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0x2f980a4)[0x7fe353b5a0a4]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0xfebd88)[0x7fe351badd88]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0xfa5571)[0x7fe351b67571]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0xfa96d6)[0x7fe351b6b6d6]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0xecd026)[0x7fe351a8f026]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0xf7c06e)[0x7fe351b3e06e]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-dcb6cdc0d7ad0347.so(+0xf54212)[0x7fe351b16212]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/libstd-025e001bd1fa95df.so(rust_metadata_std_ae54db559e22a89e+0xb3225)[0x7fe350ae9225]
/lib/x86_64-linux-gnu/libc.so.6(+0x94b43)[0x7fe35089fb43]
/lib/x86_64-linux-gnu/libc.so.6(+0x126a00)[0x7fe350931a00]
[RUSTC-TIMING] cargo test:false 61.194
rustc exited with signal: 11 (SIGSEGV) (core dumped)

Caused by:
Caused by:
  process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc --crate-name cargo --edition=2021 src/cargo/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 --cfg 'feature="all-static"' --cfg 'feature="openssl"' --cfg 'feature="vendored-openssl"' -Zunstable-options --check-cfg 'values(feature, "all-static", "openssl", "pretty-env-logger", "pretty_env_logger", "vendored-libgit2", "vendored-openssl")' --check-cfg 'names()' --check-cfg 'values()' -C metadata=01ac5483921a6941 -C extra-filename=-01ac5483921a6941 --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps --target mips64el-unknown-linux-gnuabi64 -C linker=mips64el-unknown-linux-gnu-gcc -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/release/deps --extern anyhow=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libanyhow-4451dc31f6485844.rmeta --extern base64=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libbase64-791dbed03c47b9f2.rmeta --extern bytesize=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libbytesize-e571371348097aa3.rmeta --extern cargo_platform=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libcargo_platform-44c95bf774d3996f.rmeta --extern cargo_util=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libcargo_util-c267b5b1d32487ae.rmeta --extern clap=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libclap-f415a32c622a21d1.rmeta --extern crates_io=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libcrates_io-4f42c5e786edef3d.rmeta --extern curl=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libcurl-718f4dbbaf90dee9.rmeta --extern curl_sys=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libcurl_sys-40b1e8a900eabe43.rmeta --extern env_logger=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libenv_logger-b9701cd269b945e5.rmeta --extern filetime=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libfiletime-eb91a35d19847e9f.rmeta --extern flate2=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libflate2-0bdf3497be81c89a.rmeta --extern git2=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libgit2-a61dcfbd4f1f80a1.rmeta --extern git2_curl=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libgit2_curl-bd2a2e551f3d7c4b.rmeta --extern gix=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libgix-3386421a39d2769d.rmeta --extern gix_features_for_configuration_only=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libgix_features-b89c061755ccd5f6.rmeta --extern glob=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libglob-40cb8722a6633475.rmeta --extern hex=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libhex-4113776afd8e4612.rmeta --extern hmac=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libhmac-7c29617bf8d03644.rmeta --extern home=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libhome-697d0e9eff05bc22.rmeta --extern http_auth=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libhttp_auth-54598e3bd1434291.rmeta --extern humantime=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/mips64el-unknown-linux-gnuabi64/release/deps/libhumantime-bb147116dc3ebe9d.rmeta --extern ignore=/checkout/obj/build/x86_64-unknown [...]

2023-07-02 23:48 UTC, DrMeepster commented
@bors retry the mips failure again

2023-07-03 00:25 UTC, workingjubilee commented
@bors p=4

2023-07-03 05:07 UTC, merged

2023-07-03 06:24 UTC, rust-timer commented
Finished benchmarking commit (d5a74249c843e06b502fb097ebea2383b9a5d9b8): [comparison URL](https://perf.rust-lang.org/compare.html?start=571c9fc8a9693bb75822d7b46a8d3bed0388e925&end=d5a74249c843e06b502fb097ebea2383b9a5d9b8&stat=instructions:u).

### Overall result: ❌ regressions - ACTION NEEDED


**Next Steps**: If you can justify the regressions found in this perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please open an issue or create a new PR that fixes the regressions, add a comment linking to the newly created issue or PR, and then add the `perf-regression-triaged` label to this PR.

@rustbot label: +perf-regression
cc @rust-lang/wg-compiler-performance



### [Instruction count](https://perf.rust-lang.org/compare.html?start=571c9fc8a9693bb75822d7b46a8d3bed0388e925&end=d5a74249c843e06b502fb097ebea2383b9a5d9b8&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.7% | [0.3%, 1.5%] | 26    |
| Regressions ❌ <br /> (secondary)  | 1.1% | [0.2%, 1.9%] | 21    |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 0.7% | [0.3%, 1.5%] | 26    |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=571c9fc8a9693bb75822d7b46a8d3bed0388e925&end=d5a74249c843e06b502fb097ebea2383b9a5d9b8&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 3.9%  | [3.9%, 3.9%]   | 1     |
| Regressions ❌ <br /> (secondary)  | 2.0%  | [1.2%, 2.8%]   | 8     |
| Improvements ✅ <br /> (primary)   | -4.0% | [-4.0%, -4.0%] | 1     |
| Improvements ✅ <br /> (secondary) | -2.0% | [-2.0%, -2.0%] | 1     |
| All ❌✅ (primary)                 | -0.1% | [-4.0%, 3.9%]  | 2     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=571c9fc8a9693bb75822d7b46a8d3bed0388e925&end=d5a74249c843e06b502fb097ebea2383b9a5d9b8&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 3.2% | [1.9%, 4.2%] | 10    |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=571c9fc8a9693bb75822d7b46a8d3bed0388e925&end=d5a74249c843e06b502fb097ebea2383b9a5d9b8&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 667.216s -> 669.334s (0.32%)

2023-07-03 06:42 UTC, nnethercote commented
This looks like a genuine perf regression. @DrMeepster, was this expected? Could it be avoided or reduced?

2023-07-04 08:02 UTC, DrMeepster commented
@nnethercote I think one cause is unnecessary allocations. I've opened #113316, which should improve the situation by allocating each deref chain once and storing it, instead of remaking it from the derefer sidetable every time its needed.