Change the wording in `std::fmt::Write::write_str`
rust-lang/rust pull request #112959
Opened 2023-06-23 12:42 UTC by tbu-

Refer to the error instead of expanding its name.

2023-06-26 17:22 UTC, m-ou-se commented
The full path `std::fmt::Error` seems useful to show, to distinguish it from `std::io::Error` (which is used by the very similar `std::io::Write` trait).

2023-06-27 15:22 UTC, tbu- commented
> The full path `std::fmt::Error` seems useful to show, to distinguish it from `std::io::Error` (which is used by the very similar `std::io::Write` trait).

Added the path to the line above.

2023-09-28 05:54 UTC, dtolnay requested changes

2023-09-28 05:54 UTC, dtolnay commented on library/core/src/fmt/mod.rs
> +    /// This function will return an instance of [`std::fmt::Error`] on error.
This should unbreak the doc build.

```suggestion
    /// This function will return an instance of [`std::fmt::Error`][Error] on error.
```

2023-09-28 05:56 UTC, dtolnay approved these changes
Thanks!

2023-09-28 05:56 UTC, dtolnay commented
@bors r+ rollup

2023-09-28 09:58 UTC, merged