Delete architecture-specific memchr code in std::sys
rust-lang/rust pull request #114016
Opened 2023-07-24 14:20 UTC by krtab

Currently all architecture-specific memchr code is only used in `std::io`. Most of the actual `memchr` capacity exposed to the user through the slice API is instead implemented in `core::slice::memchr`.

Hence this commit deletes `memchr` from `std::sys[_common]` and replace calls to it by calls to `core::slice::memchr` functions. This deletes `(r)memchr` from the list of symbols linked to libc.

The interest of putting architecture specific code back in core is linked to the discussion to be had in #113654

2023-12-05 20:05 UTC, workingjubilee commented
Hmm, I'm assuming this isn't going to affect anything but I would like to see the perf queue say "yes" first.

@bors try @rust-timer queue

2023-12-05 20:05 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2023-12-06 00:04 UTC, rust-timer commented
Finished benchmarking commit (3df3b2ce4774fef0dbbc6f02e92cdad8275ee162): [comparison URL](https://perf.rust-lang.org/compare.html?start=ec94480d9877e9c7ccf1255ab592dfc85d07ec50&end=3df3b2ce4774fef0dbbc6f02e92cdad8275ee162&stat=instructions:u).

### Overall result: ❌ regressions - no action needed


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

@bors rollup=never
@rustbot label: -S-waiting-on-perf -perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=ec94480d9877e9c7ccf1255ab592dfc85d07ec50&end=3df3b2ce4774fef0dbbc6f02e92cdad8275ee162&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.5% | [0.5%, 0.5%] | 1     |
| Regressions ❌ <br /> (secondary)  | -    | -            | 0     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 0.5% | [0.5%, 0.5%] | 1     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=ec94480d9877e9c7ccf1255ab592dfc85d07ec50&end=3df3b2ce4774fef0dbbc6f02e92cdad8275ee162&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 6.7%  | [6.7%, 6.7%]   | 1     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -2.8% | [-2.8%, -2.8%] | 1     |
| Improvements ✅ <br /> (secondary) | -2.8% | [-3.2%, -2.5%] | 4     |
| All ❌✅ (primary)                 | 2.0%  | [-2.8%, 6.7%]  | 2     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=ec94480d9877e9c7ccf1255ab592dfc85d07ec50&end=3df3b2ce4774fef0dbbc6f02e92cdad8275ee162&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.0% | [1.0%, 1.0%] | 1     |
| Regressions ❌ <br /> (secondary)  | 2.5% | [2.2%, 2.8%] | 3     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 1.0% | [1.0%, 1.0%] | 1     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=ec94480d9877e9c7ccf1255ab592dfc85d07ec50&end=3df3b2ce4774fef0dbbc6f02e92cdad8275ee162&stat=size:linked_artifact)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.3%  | [0.3%, 0.3%]   | 1     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -0.2% | [-0.3%, -0.1%] | 5     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -0.1% | [-0.3%, 0.3%]  | 6     |
</details>

**Bootstrap**: 675.106s -> 674.558s (-0.08%)
**Artifact size**: 314.16 MiB -> 314.13 MiB (-0.01%)

2023-12-07 04:13 UTC, workingjubilee commented
Hm. Sure. Don't know whether the other changes should be done, but the shocking lack of runtime perf changes feels motivating.

@bors r+

2023-12-07 05:20 UTC, rust-log-analyzer commented
A job failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/7124098905/job/19397821271) [(plain)](https://github.com/rust-lang-ci/rust/commit/86b7b71c8a7468496f19319989e53593241302ce/checks/19397821271/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

```

</details>

2023-12-07 05:28 UTC, workingjubilee commented
uh?
@bors retry

2023-12-07 08:28 UTC, krtab commented
Urgh,
A quick morning glance tells me that this is because WASI is lacking memchr, I'll see if I can add polyfills.

2023-12-09 00:19 UTC, workingjubilee commented
@bors r-

2023-12-14 16:44 UTC, krtab commented
Turns out it was just that the `sys::memchr` import still existed in the wasi target. The diff since you last reviewed is:

```diff
diff --git a/library/std/src/sys/wasi/os.rs b/library/std/src/sys/wasi/os.rs
index d53bddd8e9d..330c0f4717a 100644
--- a/library/std/src/sys/wasi/os.rs
+++ b/library/std/src/sys/wasi/os.rs
@@ -8,9 +8,9 @@
 use crate::ops::Drop;
 use crate::os::wasi::prelude::*;
 use crate::path::{self, PathBuf};
+use crate::slice::memchr;
 use crate::str;
 use crate::sys::common::small_c_string::{run_path_with_cstr, run_with_cstr};
-use crate::sys::memchr;
 use crate::sys::unsupported;
 use crate::vec;
 ```
 
 (I also rebased, sorry if that messes up the review flow)

2023-12-15 21:41 UTC, workingjubilee commented
It's fine, I generally just re-skim the entire thing on every commit.

@bors r+ rollup=iffy

2023-12-15 22:05 UTC, rust-log-analyzer commented
The job **`dist-various-2`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/7227326337/job/19694741546) [(plain)](https://github.com/rust-lang-ci/rust/commit/39af1837f2365d86b5783ffc04b8935df03eda0d/checks/19694741546/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

```

</details>

2023-12-15 22:22 UTC, workingjubilee commented
erm?

2023-12-15 22:22 UTC, workingjubilee commented
damn my lying eyes?

2023-12-15 22:34 UTC, ChrisDenton commented
wasm32, library/std/src/sys/wasi/os.rs:13:5. Unresolved import `crate::sys::memchr`, consider importing this module instead `core::slice::memchr`, etc.

2023-12-15 23:38 UTC, krtab commented
My bad. I had forgotten the actual change and only committed the rebase. My change also turned out to be slightly wrong but it should be fine now (couldn't get `./x.py check --target wasm32-wasi` to fully pass but the error is not memchr related anymore).

2023-12-16 08:04 UTC, workingjubilee commented
Hmm.

@bors r+

2023-12-16 08:50 UTC, rust-log-analyzer commented
The job **`test-various`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/7230750356/job/19703174333) [(plain)](https://github.com/rust-lang-ci/rust/commit/decdc733209ef45344054e6f6fabd876239dac7f/checks/19703174333/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
[RUSTC-TIMING] gimli test:false 3.066
[RUSTC-TIMING] object test:false 3.945
warning: dropping unsupported crate type `dylib` for target `aarch64-unknown-uefi`

error: unused imports: `memchr`, `memrchr`
   |
   |
61 |     pub use core::slice::memchr::{memchr, memrchr};
   |
   = note: `-D unused-imports` implied by `-D warnings`
   = note: `-D unused-imports` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(unused_imports)]`
[RUSTC-TIMING] std test:false 1.979
warning: `std` (lib) generated 1 warning
error: could not compile `std` (lib) due to previous error; 1 warning emitted
Build completed unsuccessfully in 0:00:27
```

</details>

2023-12-16 18:13 UTC, workingjubilee commented
I'm going to just hand-audit this for every supported platform before I approve this again. Might be a few days before I get around to it.

2023-12-16 22:46 UTC, krtab commented
Ok. I'm on break for the next two weeks anyway so no rush.

2024-02-16 08:36 UTC, joboet requested changes
There are still some unresolved imports and missing modules on some targets:
* Hermit (x86_64-unknown-hermit)
* SOLID (aarch64-kmc-solid_asp3)
* TeeOS (aarch64-unknown-teeos)
* UEFI still has a `memchr` module (x86_64-unknown-uefi)
* ZKVM does too (it doesn't currently build anyway)

I'd recommend searching all of `std` for `memchr`, checking each use, and then running `x check library/std --target [TARGET]` for each of the targets above, they should be representative.

2024-02-16 08:36 UTC, joboet commented on library/std/src/sys/pal/hermit/memchr.rs
Hermit's `mod.rs` still includes a reference to this module.

2024-02-16 08:36 UTC, joboet commented on library/std/src/sys/pal/hermit/os.rs
> -use crate::sys::memchr;
This is used in line 100.

2024-02-16 08:36 UTC, joboet commented on library/std/src/sys/pal/solid/mod.rs
`solid/os.rs` has another import.

2024-02-20 21:30 UTC, krtab commented
@rustbot label -T-bootstrap

2024-02-20 21:32 UTC, krtab commented
Thanks @joboet, it should hopefully be good know.
And thanks to @WaffleLapkin on zulip as well.

2024-03-01 00:28 UTC, workingjubilee commented
Thank you everyone! Sorry for not getting back to you on answering your question on Zulip, the answer was a somewhat inane "manually comb through everything and run this code on the machines I have available".

@bors r+

2024-03-01 00:28 UTC, workingjubilee commented
@bors rollup=never

2024-03-01 03:10 UTC, merged

2024-03-01 04:25 UTC, rust-timer commented
Finished benchmarking commit (6f435eb0eb2926cdb6640b3382b9e3e21ef05f07): [comparison URL](https://perf.rust-lang.org/compare.html?start=77be7a3e0df908c5ea9ea4a70d209782a7299b4b&end=6f435eb0eb2926cdb6640b3382b9e3e21ef05f07&stat=instructions:u).

### Overall result: ❌✅ regressions and improvements - ACTION NEEDED


**Next Steps**: If you can justify the regressions found in this perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please open an issue or create a new PR that fixes the regressions, add a comment linking to the newly created issue or PR, and then add the `perf-regression-triaged` label to this PR.

@rustbot label: +perf-regression
cc @rust-lang/wg-compiler-performance



### [Instruction count](https://perf.rust-lang.org/compare.html?start=77be7a3e0df908c5ea9ea4a70d209782a7299b4b&end=6f435eb0eb2926cdb6640b3382b9e3e21ef05f07&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.1%  | [1.1%, 1.1%]   | 1     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -2.7% | [-2.7%, -2.7%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -0.8% | [-2.7%, 1.1%]  | 2     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=77be7a3e0df908c5ea9ea4a70d209782a7299b4b&end=6f435eb0eb2926cdb6640b3382b9e3e21ef05f07&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 15.9% | [15.9%, 15.9%] | 1     |
| Regressions ❌ <br /> (secondary)  | 2.8%  | [0.9%, 6.1%]   | 7     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | 15.9% | [15.9%, 15.9%] | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=77be7a3e0df908c5ea9ea4a70d209782a7299b4b&end=6f435eb0eb2926cdb6640b3382b9e3e21ef05f07&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.0%  | [1.0%, 1.0%]   | 1     |
| Regressions ❌ <br /> (secondary)  | 2.7%  | [2.7%, 2.7%]   | 1     |
| Improvements ✅ <br /> (primary)   | -2.9% | [-2.9%, -2.9%] | 1     |
| Improvements ✅ <br /> (secondary) | -3.0% | [-3.0%, -3.0%] | 1     |
| All ❌✅ (primary)                 | -0.9% | [-2.9%, 1.0%]  | 2     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=77be7a3e0df908c5ea9ea4a70d209782a7299b4b&end=6f435eb0eb2926cdb6640b3382b9e3e21ef05f07&stat=size:linked_artifact)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.3%  | [0.0%, 0.5%]   | 2     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -0.1% | [-0.1%, -0.1%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | 0.2%  | [-0.1%, 0.5%]  | 3     |
</details>

**Bootstrap**: 651.937s -> 650.561s (-0.21%)
**Artifact size**: 311.55 MiB -> 311.48 MiB (-0.02%)

2024-03-01 08:28 UTC, lqd commented
The regression doesn’t look real, syn-opt was somehow less noisy than usual recently, and seems to be back to its usual behavior.