impl Default for ExitCode
rust-lang/rust pull request #114589
Opened 2023-08-07 15:48 UTC by ijackson

As suggested here
  https://github.com/rust-lang/rust/pull/106425#issuecomment-1382952598

Needs FCP since this is an insta-stable impl.

Ideally we would have `impl From<ExitCode> for ExitStatus` and implement the default `ExitStatus` using that.   That is sadly not so easy because of the various strange confusions about `ExitCode` (unix: exit status) vs `ExitStatus` (unix: wait status) in the not-really-unix platforms in `library//src/sys/unix/process`.  I'll try to follow that up.

2023-08-07 23:56 UTC, cuviper commented
@rustbot label -T-libs +T-libs-api
r? libs-api

2023-09-07 20:54 UTC, dtolnay commented
r? dtolnay

2023-09-07 20:54 UTC, dtolnay approved these changes

2023-09-07 20:57 UTC, dtolnay commented
@rust-lang/libs-api:
@rfcbot fcp merge

Already in Rust 1.73 (current beta) we have approved `impl Default for ExitStatus` in https://github.com/rust-lang/rust/pull/106425, producing the success exit status.

Recall that [`ExitStatus`](https://doc.rust-lang.org/std/process/struct.ExitStatus.html) is the thing you get from a subprocess and [`ExitCode`](https://doc.rust-lang.org/std/process/struct.ExitCode.html) is the thing you return from `main`. :sneezing_face:

2023-10-13 14:08 UTC, dtolnay approved these changes

2023-10-13 14:08 UTC, dtolnay commented
@bors r+

2023-10-13 14:55 UTC, rust-log-analyzer commented
The job **`aarch64-gnu`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/6509725324/job/17681855242) [(plain)](https://github.com/rust-lang-ci/rust/commit/d96322459717767f30037d55fb3dfa79e689d04f/checks/17681855242/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling addr2line v0.21.0
[RUSTC-TIMING] addr2line test:false 0.563
[RUSTC-TIMING] gimli test:false 5.078
[RUSTC-TIMING] object test:false 5.551
error[E0711]: feature `process-exitcode-default` is declared stable since 1.73.0-beta.1, but was previously declared stable since 1.73.0
     |
     |
1964 | #[stable(feature = "process-exitcode-default", since = "CURRENT_RUSTC_VERSION")]

For more information about this error, try `rustc --explain E0711`.
[RUSTC-TIMING] std test:false 2.003
error: could not compile `std` (lib) due to previous error
```

</details>

2023-10-13 15:15 UTC, dtolnay requested changes
Looks like a conflict with #114588. They need different `feature` names because they are being stabilized in different Rust versions.

2023-10-15 18:44 UTC, dtolnay commented
@bors r+

2023-10-16 04:04 UTC, merged

2023-10-16 08:58 UTC, rust-timer commented
Finished benchmarking commit (58352c06497ac1cc8f7c49d30d6df967134efbaf): [comparison URL](https://perf.rust-lang.org/compare.html?start=30d310cc1f7056fa9941b9f9c415d60091ed8fec&end=58352c06497ac1cc8f7c49d30d6df967134efbaf&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=30d310cc1f7056fa9941b9f9c415d60091ed8fec&end=58352c06497ac1cc8f7c49d30d6df967134efbaf&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=30d310cc1f7056fa9941b9f9c415d60091ed8fec&end=58352c06497ac1cc8f7c49d30d6df967134efbaf&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 3.4% | [3.4%, 3.4%] | 1     |
| Regressions ❌ <br /> (secondary)  | -    | -            | 0     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 3.4% | [3.4%, 3.4%] | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=30d310cc1f7056fa9941b9f9c415d60091ed8fec&end=58352c06497ac1cc8f7c49d30d6df967134efbaf&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 3.7% | [3.7%, 3.7%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=30d310cc1f7056fa9941b9f9c415d60091ed8fec&end=58352c06497ac1cc8f7c49d30d6df967134efbaf&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 624.787s -> 624.739s (-0.01%)
**Artifact size**: 305.54 MiB -> 305.53 MiB (-0.00%)