Refine error message for thread-safe usage of std::sync::Arc<{Self}>
rust-lang/rust pull request #114842
Opened 2023-08-15 07:43 UTC by reez12g

fixes https://github.com/rust-lang/rust/issues/114687

2023-08-15 07:57 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-15`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5864812448/job/15900535486) [(plain)](https://github.com/rust-lang/rust/commit/9d317d00336bd5f99ec1dcd9e53d7166faded03a/checks/15900535486/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=reez12g
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_717a883b-a792-47e2-b3cf-a0d57c63aa1b
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=a7f71f720e9d7376ea619c64c0da2cf8918e78af
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_717a883b-a792-47e2-b3cf-a0d57c63aa1b
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_717a883b-a792-47e2-b3cf-a0d57c63aa1b
GITHUB_TRIGGERING_ACTOR=reez12g
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/114842/merge
GITHUB_WORKFLOW_SHA=a7f71f720e9d7376ea619c64c0da2cf8918e78af
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_18_X64=/opt/hostedtoolcache/go/1.18.10/x64
---
.................................i.i.............ii.....................................    88/15445
........................................................................................   176/15445
....iiiiiiiiiiiiiii......................i..............................................   264/15445
........................................................................................   352/15445
.............................................F......................................F...   440/15445
........................................................................................   616/15445
........................................................................................   704/15445
..FFF...................................................................................   792/15445
..FFF...................................................................................   792/15445
............F.......................................F..FFF.....FFF....F.................   880/15445
.................................................F.................F....................   968/15445
...........FF..............................i............................................  1056/15445
...................................................F................i...................  1144/15445
........................................................................................  1320/15445
........................................................................................  1408/15445
........................................................................................  1496/15445
........................................................................................  1584/15445
........................................................................................  1584/15445
.i......................................................................................  1672/15445
......................................F....FF...........................................  1760/15445
........................................................................................  1936/15445
.............................................................F..........................  2024/15445
..............................................................................i.........  2112/15445
...i...........ii.......................................................................  2200/15445
---
........................................................................................  4224/15445
.............................................F..........................................  4312/15445
........................................................................................  4400/15445
........................................................................................  4488/15445
............i..........i.F........i...F.................................................  4576/15445
.....................................................................................i..  4752/15445
........................................................................................  4840/15445
..............i.........................................................................  4928/15445
..............i.........................................................................  4928/15445
..................................................FFF......F.........................F.F  5016/15445
......................F..FF..FF.FF...F..F...FF........F.................................  5104/15445
.............................................................................i..........  5280/15445
........................................................................................  5368/15445
........................................................................................  5456/15445
........................................................................................  5544/15445
---
........................................................................................  7392/15445
................................i.......................................................  7480/15445
.........................................................................i..............  7568/15445
..........................................ii.ii........i....i...........................  7656/15445
FFF..F.F....F.......................................................i...................  7744/15445
..............................................................................i....i....  7920/15445
.......................................................................i................  8008/15445
i...............................................................................i.......  8096/15445
........................................................................................  8184/15445
---
........................................................................................ 13640/15445
....................................................F................................... 13728/15445
........................................................................................ 13816/15445
........................................................................................ 13904/15445
.............F..............................F........................................... 13992/15445
.......i...............................................F.....F.......................... 14080/15445
............F........................................................................... 14256/15445
........................................................................................ 14344/15445
........................................................................................ 14432/15445
........................................................................................ 14520/15445
........................................................................................ 14520/15445
........................................................................................ 14608/15445
........................................................................................ 14696/15445
........................................................................................ 14784/15445
..................................................FF..F................................. 14872/15445
........................................................................................ 15048/15445
........................................................................................ 15136/15445
........................................................................................ 15224/15445
............................i................. [...]

2023-08-15 09:18 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-15`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5865458556/job/15902434682) [(plain)](https://github.com/rust-lang/rust/commit/6ff0b90dabeb27e6ee0eb03cad6a0e2ffb111465/checks/15902434682/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=reez12g
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_a3c93df8-905e-4246-baf6-522ed002d896
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=e412504ab4955f61d0e309d86de94afecb6d0615
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_a3c93df8-905e-4246-baf6-522ed002d896
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_a3c93df8-905e-4246-baf6-522ed002d896
GITHUB_TRIGGERING_ACTOR=reez12g
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/114842/merge
GITHUB_WORKFLOW_SHA=e412504ab4955f61d0e309d86de94afecb6d0615
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_18_X64=/opt/hostedtoolcache/go/1.18.10/x64
---
........................................................................................   528/15446
........................................................................................   616/15446
........................................................................................   704/15446
........................................................................................   792/15446
..................................FFF.............F..................FF.F...............   880/15446
..F..FF.................................................................................   968/15446
........F..F...............................i............................................  1056/15446
........................................................................................  1232/15446
........................................................................................  1320/15446
........................................................................................  1408/15446
........................................................................................  1496/15446
........................................................................................  1496/15446
........................................................................................  1584/15446
i.......................................................................................  1672/15446
........................................F...............................................  1760/15446
................................i.......................................................  1848/15446
........................................................................................  1936/15446
...................................................................F.F..................  2024/15446
...i...........ii.......................................................................  2200/15446
........................................................................................  2288/15446
.....................................................................................i..  2376/15446
........................................................................................  2464/15446
---
........................................................................................  4224/15446
........................................................................................  4312/15446
........................................................................................  4400/15446
........................................................................................  4488/15446
.............i..........i..........i..F.................................................  4576/15446
......................................................................................i.  4752/15446
..........................................F.............................................  4840/15446
...............i........................................................................  4928/15446
.....................................................................................F..  5016/15446
.....................................................................................F..  5016/15446
.......................F.F.F............F..FF.........F.................................  5104/15446
..............................................................................i.........  5280/15446
........................................................................................  5368/15446
........................................................................................  5456/15446
........................................................................................  5544/15446
---
........................................................................................  7392/15446
..................................i.....................................................  7480/15446
..........................................................................i.............  7568/15446
...........................................ii.ii........i....i..........................  7656/15446
.....FF.F............................................................i..................  7744/15446
...............................................................................i....i...  7920/15446
........................................................................i...............  8008/15446
..i..............................................................................i......  8096/15446
........................................................................................  8184/15446
---
........................................................................................  9416/15446
........................................................................................  9504/15446
........................................................................................  9592/15446
........................................................................................  9680/15446
............i..iF...FF.............................i...............................ii...  9768/15446
........................................................................................  9944/15446
......................................................................i................. 10032/15446
..........................i............................................................. 10120/15446
.................i...................................................................... 10208/15446
---
........................................................................................ 12584/15446
........................................................................................ 12672/15446
........................................................................................ 12760/15446
........................................................................................ 12848/15446
.................................F..............i.........F............................. 12936/15446
........................................................................................ 13112/15446
........................................................................................ 13200/15446
........................................................................................ 13288/15446
........................................................................................ 13376/15446
---
........................................................................................ 14520/15446
........................................................................................ 14608/15446
...................................... [...]

2023-08-15 10:27 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-15`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5866020659/job/15904048791) [(plain)](https://github.com/rust-lang/rust/commit/cde6313ecafa9cfa7dd8d9d0d76ef549bd30a3a7/checks/15904048791/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=reez12g
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_d97f3799-11c6-4d37-b719-848747079f35
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=0bf2804f842fcc14726672798a7551d0f649f8fa
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_d97f3799-11c6-4d37-b719-848747079f35
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_d97f3799-11c6-4d37-b719-848747079f35
GITHUB_TRIGGERING_ACTOR=reez12g
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/114842/merge
GITHUB_WORKFLOW_SHA=0bf2804f842fcc14726672798a7551d0f649f8fa
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_18_X64=/opt/hostedtoolcache/go/1.18.10/x64
---
........................................................................................   704/15446
........................................................................................   792/15446
........................................................................................   880/15446
........................................................................................   968/15446
...........F.F.............................i............................................  1056/15446
........................................................................................  1232/15446
........................................................................................  1320/15446
........................................................................................  1408/15446
........................................................................................  1496/15446
---
........................................................................................  9416/15446
........................................................................................  9504/15446
........................................................................................  9592/15446
........................................................................................  9680/15446
............i..iFF.....F...........................i................................ii..  9768/15446
........................................................................................  9944/15446
......................................................................i................. 10032/15446
..........................i............................................................. 10120/15446
..............i......................................................................... 10208/15446
---
failures:

---- [ui] tests/ui/async-await/partial-drop-partial-reinit.rs#drop_tracking stdout ----

error in revision `drop_tracking`: /checkout/tests/ui/async-await/partial-drop-partial-reinit.rs:9: unexpected note: '9:16: 9:21: consider whether `std::sync::Arc<NotSend>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>'

error in revision `drop_tracking`: /checkout/tests/ui/async-await/partial-drop-partial-reinit.rs:9: expected note not found: consider using `std::sync::Arc<NotSend>`

error in revision `drop_tracking`: 1 unexpected errors found, 1 expected errors not found
status: exit status: 1
command: RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/async-await/partial-drop-partial-reinit.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--cfg" "drop_tracking" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/partial-drop-partial-reinit.drop_tracking" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/partial-drop-partial-reinit.drop_tracking/auxiliary" "--edition=2021" "-Zdrop-tracking=yes"
    Error {
        line_num: 9,
        kind: Some(
            Note,
            Note,
        ),
        msg: "9:16: 9:21: consider whether `std::sync::Arc<NotSend>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>",
]

not found errors (from test file): [
    Error {
    Error {
        line_num: 9,
        kind: Some(
            Note,
        ),
        msg: "consider using `std::sync::Arc<NotSend>`",
]

thread '[ui] tests/ui/async-await/partial-drop-partial-reinit.rs#drop_tracking' panicked at src/tools/compiletest/src/runtest.rs:1747:13:
explicit panic
explicit panic
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- [ui] tests/ui/async-await/partial-drop-partial-reinit.rs#no_drop_tracking stdout ----

error in revision `no_drop_tracking`: /checkout/tests/ui/async-await/partial-drop-partial-reinit.rs:9: unexpected note: '9:16: 9:21: consider whether `std::sync::Arc<NotSend>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>'

error in revision `no_drop_tracking`: /checkout/tests/ui/async-await/partial-drop-partial-reinit.rs:9: expected note not found: consider using `std::sync::Arc<NotSend>`
error in revision `no_drop_tracking`: 1 unexpected errors found, 1 expected errors not found
status: exit status: 1
status: exit status: 1
command: RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/async-await/partial-drop-partial-reinit.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--cfg" "no_drop_tracking" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/partial-drop-partial-reinit.no_drop_tracking" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/partial-drop-partial-reinit.no_drop_tracking/auxiliary" "--edition=2021" "-Zdrop-tracking=no"
    Error {
        line_num: 9,
        kind: Some(
            Note,
            Note,
        ),
        msg: "9:16: 9:21: consider whether `std::sync::Arc<NotSend>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>",
]

not found errors (from test file): [
    Error {
    Error {
        line_num: 9,
        kind: Some(
            Note,
        ),
        msg: "consider using `std::sync::Arc<NotSend>`",
]

thread '[ui] tests/ui/async-await/partial-drop-partial-reinit.rs#no_drop_tracking' panicked at src/tools/compiletest/src/runtest.rs:1747 [...]

2023-08-16 04:24 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-15`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5874544340/job/15929465193) [(plain)](https://github.com/rust-lang/rust/commit/5377ef0fae29cfe9bcb0b0f16bf4cc8b0e58168e/checks/15929465193/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=reez12g
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_d214d0be-20fb-412b-bf51-ad1f20b673a9
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=b9a0e13a51b8c4845dbd8a2ff54e39ca62df1ff9
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_d214d0be-20fb-412b-bf51-ad1f20b673a9
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_d214d0be-20fb-412b-bf51-ad1f20b673a9
GITHUB_TRIGGERING_ACTOR=reez12g
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/114842/merge
GITHUB_WORKFLOW_SHA=b9a0e13a51b8c4845dbd8a2ff54e39ca62df1ff9
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_18_X64=/opt/hostedtoolcache/go/1.18.10/x64
---
##[endgroup]
Built container sha256:9264650ae64c28ada670154c90692f2f6b3685cf71f9cafa053b2254e7c3b294
Uploading finished image to https://ci-caches.rust-lang.org/docker/df62666159455366d7de05f64a0ad1bfc41ab59f49c4c6b0722077d275ff3558b6736b1a26fbb100001e06f5d92ae45f785489e657387ca0f7a124bd497ca7af

<botocore.awsrequest.AWSRequest object at 0x7f90abeddad0>
gzip: stdout: Broken pipe
xargs: docker: terminated by signal 13
[CI_JOB_NAME=x86_64-gnu-llvm-15]
[CI_JOB_NAME=x86_64-gnu-llvm-15]
---
........................................................................................  9416/15455
........................................................................................  9504/15455
........................................................................................  9592/15455
........................................................................................  9680/15455
.................i.FF.i.F...............................i...............................  9768/15455
........................................................................................  9944/15455
...........................................................................i............ 10032/15455
...............................i........................................................ 10120/15455
...................i.................................................................... 10208/15455
---

---- [ui] tests/ui/associated-type-bounds/bad-bounds-on-assoc-in-trait.rs stdout ----
diff of stderr:

30    |                                                                                             ^^^^ `<<Self as Case1>::C as Iterator>::Item` cannot be shared between threads safely
31    |
32    = help: the trait `Sync` is not implemented for `<<Self as Case1>::C as Iterator>::Item`
-    = note: consider using `std::sync::Arc<<<Self as Case1>::C as Iterator>::Item>`; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>
+    = note: consider whether `std::sync::Arc<<<Self as Case1>::C as Iterator>::Item>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>
35    |
35    |
36 LL | trait Case1 where <<Self as Case1>::C as Iterator>::Item: Sync {

The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/associated-type-bounds/bad-bounds-on-assoc-in-trait/bad-bounds-on-assoc-in-trait.stderr
To update references, rerun the tests and pass the `--bless` flag
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args associated-type-bounds/bad-bounds-on-assoc-in-trait.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/associated-type-bounds/bad-bounds-on-assoc-in-trait.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/associated-type-bounds/bad-bounds-on-assoc-in-trait" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/associated-type-bounds/bad-bounds-on-assoc-in-trait/auxiliary"
stdout: none
--- stderr -------------------------------
error[E0277]: `<<Self as Case1>::C as Iterator>::Item` cannot be sent between threads safely
   |
   |
LL |     type C: Clone + Iterator<Item: Send + Iterator<Item: for<'a> Lam<&'a u8, App: Debug>> + Sync>;
   |                                    ^^^^ `<<Self as Case1>::C as Iterator>::Item` cannot be sent between threads safely
   |
   = help: the trait `Send` is not implemented for `<<Self as Case1>::C as Iterator>::Item`
   = note: consider whether `std::sync::Arc<<<Self as Case1>::C as Iterator>::Item>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>
   |
   |
LL | trait Case1 where <<Self as Case1>::C as Iterator>::Item: Send {


error[E0277]: `<<Self as Case1>::C as Iterator>::Item` is not an iterator
   |
   |
LL |     type C: Clone + Iterator<Item: Send + Iterator<Item: for<'a> Lam<&'a u8, App: Debug>> + Sync>;
   |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `<<Self as Case1>::C as Iterator>::Item` is not an iterator
   |
   = help: the trait `Iterator` is not implemented for `<<Self as Case1>::C as Iterator>::Item`
   |
   |
LL | trait Case1 where <<Self as Case1>::C as Iterator>::Item: Iterator {


error[E0277]: `<<Self as Case1>::C as Iterator>::Item` cannot be shared between threads safely
   |
   |
LL |     type C: Clone + Iterator<Item: Send + Iterator<Item: for<'a> Lam<&'a u8, App: Debug>> + Sync>;
   |                                                                                             ^^^^ `<<Self as Case1>::C as Iterator>::Item` cannot be shared between threads safely
   |
   = help: the trait `Sync` is not implemented for `<<Self as Case1>::C as Iterator>::Item`
   = note: consider whether `std::sync::Arc<<<Self as Case1>::C as Iterator>::Item>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>
   |
   |
LL | trait Case1 where <<Self as Case1>::C as Iterator>::Item: Sync {

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0277`.
For more information about this error, try `rustc --explain E0277`.
------------------------------------------


---- [ui] tests/ui/async-await/partial-drop-partial-reinit.rs#drop_tracking stdout ----

error in revision `drop_tracking`: /checkout/tests/ui/async-await/partial-drop-partial-reinit.rs:9: unexpected note: '9:16: 9:21: consider whether `std::sync::Arc<NotSend>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>'

error in revision `drop_tracking`: /checkout/tests/ui/async-await/partial-drop-partial-reinit.rs:9: expected note not found: consider using `std::sync::Arc<NotSend>`

e [...]

2023-08-16 07:32 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-15`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5875840827/job/15932829433) [(plain)](https://github.com/rust-lang/rust/commit/09cc678dcbb849bf1ad89fdd5f205119e219d57c/checks/15932829433/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=reez12g
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_d8691580-92ac-46fc-ab00-3e75c706361a
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=57a11312e3396f30f2cc2f0f14c30f962d170236
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_d8691580-92ac-46fc-ab00-3e75c706361a
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_d8691580-92ac-46fc-ab00-3e75c706361a
GITHUB_TRIGGERING_ACTOR=reez12g
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/114842/merge
GITHUB_WORKFLOW_SHA=57a11312e3396f30f2cc2f0f14c30f962d170236
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_18_X64=/opt/hostedtoolcache/go/1.18.10/x64
---

---- [ui] tests/ui/associated-type-bounds/bad-bounds-on-assoc-in-trait.rs stdout ----
diff of stderr:

30    |                                                                                             ^^^^ `<<Self as Case1>::C as Iterator>::Item` cannot be shared between threads safely
31    |
32    = help: the trait `Sync` is not implemented for `<<Self as Case1>::C as Iterator>::Item`
-    = note: consider using `std::sync::Arc<<<Self as Case1>::C as Iterator>::Item>`; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>
+    = note: consider whether `std::sync::Arc<<<Self as Case1>::C as Iterator>::Item>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>
35    |
35    |
36 LL | trait Case1 where <<Self as Case1>::C as Iterator>::Item: Sync {

The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/associated-type-bounds/bad-bounds-on-assoc-in-trait/bad-bounds-on-assoc-in-trait.stderr
To update references, rerun the tests and pass the `--bless` flag
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args associated-type-bounds/bad-bounds-on-assoc-in-trait.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/associated-type-bounds/bad-bounds-on-assoc-in-trait.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/associated-type-bounds/bad-bounds-on-assoc-in-trait" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/associated-type-bounds/bad-bounds-on-assoc-in-trait/auxiliary"
stdout: none
--- stderr -------------------------------
error[E0277]: `<<Self as Case1>::C as Iterator>::Item` cannot be sent between threads safely
   |
   |
LL |     type C: Clone + Iterator<Item: Send + Iterator<Item: for<'a> Lam<&'a u8, App: Debug>> + Sync>;
   |                                    ^^^^ `<<Self as Case1>::C as Iterator>::Item` cannot be sent between threads safely
   |
   = help: the trait `Send` is not implemented for `<<Self as Case1>::C as Iterator>::Item`
   = note: consider whether `std::sync::Arc<<<Self as Case1>::C as Iterator>::Item>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>
help: consider further restricting the associated type
   |
   |
LL | trait Case1 where <<Self as Case1>::C as Iterator>::Item: Send {


error[E0277]: `<<Self as Case1>::C as Iterator>::Item` is not an iterator
   |
   |
LL |     type C: Clone + Iterator<Item: Send + Iterator<Item: for<'a> Lam<&'a u8, App: Debug>> + Sync>;
   |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `<<Self as Case1>::C as Iterator>::Item` is not an iterator
   |
   = help: the trait `Iterator` is not implemented for `<<Self as Case1>::C as Iterator>::Item`
   |
   |
LL | trait Case1 where <<Self as Case1>::C as Iterator>::Item: Iterator {


error[E0277]: `<<Self as Case1>::C as Iterator>::Item` cannot be shared between threads safely
   |
   |
LL |     type C: Clone + Iterator<Item: Send + Iterator<Item: for<'a> Lam<&'a u8, App: Debug>> + Sync>;
   |                                                                                             ^^^^ `<<Self as Case1>::C as Iterator>::Item` cannot be shared between threads safely
   |
   = help: the trait `Sync` is not implemented for `<<Self as Case1>::C as Iterator>::Item`
   = note: consider whether `std::sync::Arc<<<Self as Case1>::C as Iterator>::Item>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>
   |
   |
LL | trait Case1 where <<Self as Case1>::C as Iterator>::Item: Sync {

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0277`.
For more information about this error, try `rustc --explain E0277`.
------------------------------------------


---- [ui] tests/ui/async-await/partial-drop-partial-reinit.rs#drop_tracking stdout ----

error in revision `drop_tracking`: /checkout/tests/ui/async-await/partial-drop-partial-reinit.rs:9: unexpected note: '9:16: 9:21: consider whether `std::sync::Arc<NotSend>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>'

error in revision `drop_tracking`: /checkout/tests/ui/async-await/partial-drop-partial-reinit.rs:9: expected note not found: consider using `std::sync::Arc<NotSend>`

error in revision `drop_tracking`: 1 unexpected errors found, 1 expected errors not found
status: exit status: 1
command: RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/async-await/partial-drop-partial-reinit.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--cfg" "drop_tracking" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/partial-drop-partial-reinit.drop_tracking" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/partial-drop-partial-reinit.drop_tracking/auxiliary" "--edition=2021" "-Zdrop-tracking=yes"
    Error {
        line_num: 9,
        kind: Some(
            Note,
            Note,
        ),
        msg: "9:16: 9:21: consider whether `std::sync::Arc<NotSend>` could be incorporated to share this  [...]

2023-08-16 08:37 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-15`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5876422045/job/15934545253) [(plain)](https://github.com/rust-lang/rust/commit/e34d08672c7ae3bfce6a99022c4c2dfa55ec2149/checks/15934545253/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=reez12g
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_3b215565-aea4-4b06-acba-57871112b3e4
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=9d24e1bd0b3ccbaa94c97c3e1995d6806d100f85
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_3b215565-aea4-4b06-acba-57871112b3e4
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_3b215565-aea4-4b06-acba-57871112b3e4
GITHUB_TRIGGERING_ACTOR=reez12g
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/114842/merge
GITHUB_WORKFLOW_SHA=9d24e1bd0b3ccbaa94c97c3e1995d6806d100f85
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_18_X64=/opt/hostedtoolcache/go/1.18.10/x64
---
........................................................................................   704/15455
........................................................................................   792/15455
........................................................................................   880/15455
........................................................................................   968/15455
...........F..F............................i............................................  1056/15455
........................................................................................  1232/15455
........................................................................................  1320/15455
........................................................................................  1408/15455
........................................................................................  1496/15455
---
failures:

---- [ui] tests/ui/async-await/partial-drop-partial-reinit.rs#no_drop_tracking stdout ----

error in revision `no_drop_tracking`: /checkout/tests/ui/async-await/partial-drop-partial-reinit.rs:9: unexpected note: '9:16: 9:21: consider whether `std::sync::Arc<NotSend>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>'

error in revision `no_drop_tracking`: /checkout/tests/ui/async-await/partial-drop-partial-reinit.rs:9: expected note not found: consider whether `std::sync::Arc<NotSend>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>"
error in revision `no_drop_tracking`: 1 unexpected errors found, 1 expected errors not found
status: exit status: 1
status: exit status: 1
command: RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/async-await/partial-drop-partial-reinit.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--cfg" "no_drop_tracking" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/partial-drop-partial-reinit.no_drop_tracking" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/partial-drop-partial-reinit.no_drop_tracking/auxiliary" "--edition=2021" "-Zdrop-tracking=no"
    Error {
        line_num: 9,
        kind: Some(
            Note,
            Note,
        ),
        msg: "9:16: 9:21: consider whether `std::sync::Arc<NotSend>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>",
]

not found errors (from test file): [
    Error {
    Error {
        line_num: 9,
        kind: Some(
            Note,
        ),
        msg: "consider whether `std::sync::Arc<NotSend>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>\"",
]

thread '[ui] tests/ui/async-await/partial-drop-partial-reinit.rs#no_drop_tracking' panicked at src/tools/compiletest/src/runtest.rs:1747:13:
explicit panic
explicit panic
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- [ui] tests/ui/async-await/partial-drop-partial-reinit.rs#drop_tracking stdout ----

error in revision `drop_tracking`: /checkout/tests/ui/async-await/partial-drop-partial-reinit.rs:9: unexpected note: '9:16: 9:21: consider whether `std::sync::Arc<NotSend>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>'

error in revision `drop_tracking`: /checkout/tests/ui/async-await/partial-drop-partial-reinit.rs:9: expected note not found: consider whether `std::sync::Arc<NotSend>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>"

error in revision `drop_tracking`: 1 unexpected errors found, 1 expected errors not found
status: exit status: 1
command: RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/async-await/partial-drop-partial-reinit.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--cfg" "drop_tracking" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/partial-drop-partial-reinit.drop_tracking" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/partial-drop-partial-reinit.drop_tracking/auxiliary" "--edition=2021" "-Zdrop-tracking=yes"
    Error {
        line_num: 9,
        kind: Some(
            Note,
            Note,
        ),
        msg: "9:16: 9:21: consider whether `std::sync::Arc<NotSend>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>",
]

not found errors (from test file): [
    Error {
    Error {
        line_num: 9,
        kind: Some(
            Note,
        ),
        msg: "consider whether `std::sync::Arc<NotSend>` could be incorporated to share this value between threads; for more information visit <https://doc.rust-lang.org/book/ch16-03-shared-state.html>\"",
]

thread '[ui] tests/ui/async-await/partial-drop-partial-reinit.rs#drop_tracking' panicked at src/tools/compiletest/src/runtest.rs:1747:13:
explicit panic
```

</details>

2023-08-23 16:39 UTC, estebank commented
We can leave only the link to the book and not mention Arc at all in the !Send case.

2023-08-28 07:27 UTC, thomcc commented
I don't have strong feelings here, so perhaps @m-ou-se should take this review, since she seems to care more than I.

r? @m-ou-se

2023-08-28 10:10 UTC, dtolnay requested changes

2023-08-28 10:10 UTC, dtolnay commented on library/core/src/marker.rs
> +    note = "consider whether `std::sync::Arc<{Self}>` could be incorporated to share this value between threads; for more information visit \
As long as `Arc<{Self}>` continues to be mentioned, this does not fix #114687. That suggestion is *always* wrong.

2023-08-29 06:41 UTC, reez12g commented
Thank you for your reviews. 
Since issue #114687 is now closed, I am going to close this Pull Request as well.

2023-08-29 06:41 UTC, closed without merging