rustdoc: use unicode-aware checks for redundant explicit link fastpath
rust-lang/rust pull request #115070
Opened 2023-08-21 19:12 UTC by notriddle

Fixes #115064
Fixes #115062
Fixes #115116

2023-08-21 20:59 UTC, ChAoSUnItY requested changes

2023-08-21 20:59 UTC, ChAoSUnItY commented on src/librustdoc/passes/lint/redundant_explicit_links.rs
> -                let explicit_len = explicit_link.len();
Same logic in [collect_infra_links.rs](https://github.com/rust-lang/rust/blob/fe5f5912579d02c4e6088c89574493dfa988531a/src/librustdoc/passes/collect_intra_doc_links.rs#L1435) should be replaced with new logic.

2023-08-21 21:24 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/5931583834/job/16083722184) [(plain)](https://github.com/rust-lang/rust/commit/0164c06c67252b5fe8709a69e67aa257e3fb3791/checks/16083722184/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:c85c95e3d7251135ab7dc9ce3241c5835cc595a9)
Download action repository 'actions/upload-artifact@v3' (SHA:0b7f8abb1508181956e8e162db84b466c27e18ce)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
---
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=notriddle
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_4d98ae22-d6a7-4ee2-9aac-944279b1e7db
GITHUB_EVENT_NAME=pull_request
GITHUB_EVENT_NAME=pull_request
GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
GITHUB_GRAPHQL_URL=https://api.github.com/graphql
GITHUB_HEAD_REF=notriddle/utf8-redundant-explicit-links
GITHUB_JOB=pr
GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_4d98ae22-d6a7-4ee2-9aac-944279b1e7db
GITHUB_REF=refs/pull/115070/merge
GITHUB_REF_NAME=115070/merge
GITHUB_REF_PROTECTED=false
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=274d285516574eeaa5186cb598afc76ec4a0bd06
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_4d98ae22-d6a7-4ee2-9aac-944279b1e7db
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_4d98ae22-d6a7-4ee2-9aac-944279b1e7db
GITHUB_TRIGGERING_ACTOR=notriddle
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/115070/merge
GITHUB_WORKFLOW_SHA=274d285516574eeaa5186cb598afc76ec4a0bd06
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_18_X64=/opt/hostedtoolcache/go/1.18.10/x64
---
Removing intermediate container 2574c953ffad
 ---> fd5cb0b90aaa
Step 6/10 : COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
 ---> ea644dbcf3e8
Step 7/10 : RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt     && pip3 install virtualenv
Collecting binaryornot==0.4.4
  Downloading binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
Collecting boolean-py==4.0
  Downloading boolean.py-4.0-py3-none-any.whl (25 kB)
---
Building wheels for collected packages: reuse
  Building wheel for reuse (pyproject.toml): started
  Building wheel for reuse (pyproject.toml): finished with status 'done'
  Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=180117 sha256=2196c9034bf565528bbb1ee6dad4f753eb813f58822363e6b768f09c73e4d4ff
  Stored in directory: /tmp/pip-ephem-wheel-cache-s2k6xgph/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'setuptools'. No files were found to uninstall.
Successfully installed binaryornot-0.4.4 boolean-py-4.0 chardet-5.1.0 jinja2-3.1.2 license-expression-30.0.0 markupsafe-2.1.1 python-debian-0.1.49 reuse-1.1.0 setuptools-66.0.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting virtualenv
  Downloading virtualenv-20.24.3-py3-none-any.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 19.8 MB/s eta 0:00:00
Collecting platformdirs<4,>=3.9.1
  Downloading platformdirs-3.10.0-py3-none-any.whl (17 kB)
Collecting distlib<1,>=0.3.7
  Downloading distlib-0.3.7-py2.py3-none-any.whl (468 kB)
Collecting filelock<4,>=3.12.2
  Downloading filelock-3.12.2-py3-none-any.whl (10 kB)
  Downloading filelock-3.12.2-py3-none-any.whl (10 kB)
Installing collected packages: distlib, platformdirs, filelock, virtualenv
Successfully installed distlib-0.3.7 filelock-3.12.2 platformdirs-3.10.0 virtualenv-20.24.3
Removing intermediate container b40898073d7a
 ---> 851bb359d9f4
Step 8/10 : COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
 ---> 5c613300b6b1
 ---> 5c613300b6b1
Step 9/10 : COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/
 ---> 81e4e3d056ce
Step 10/10 : ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
Removing intermediate container 55ded71f7643
 ---> 1f3bec6a5ee4
Successfully built 1f3bec6a5ee4
Successfully tagged rust-ci:latest
Successfully tagged rust-ci:latest
##[endgroup]
Built container sha256:1f3bec6a5ee42dd2bd4ea7fa3903bf50fd182b0e6158f28718c2f3a0eabc3d55
Uploading finished image to https://ci-caches.rust-lang.org/docker/f76604104d6a6f4aa068dca8679411c51198f6c5562033174b89cf3ceb2f9ecc175231f1257b18e00fa57bb3eed5f53dbcc121e55de0452dda3db18894e27ea0

<botocore.awsrequest.AWSRequest object at 0x7fc998acdf50>
gzip: stdout: Broken pipe
xargs: docker: terminated by signal 13
[CI_JOB_NAME=mingw-check-tidy]
[CI_JOB_NAME=mingw-check-tidy]
---
DirectMap4k:      200640 kB
DirectMap2M:     8187904 kB
DirectMap1G:    10485760 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
    Finished dev [unoptimized] target(s) in 0.03s
##[endgroup]
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/fe5f5912579d02c4e6088c89574493dfa988531a/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/llvm-fe5f5912579d02c4e6088c89574493dfa988531a-true/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm
---
   Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
    Finished release [optimized] target(s) in 25.54s
##[endgroup]
fmt check
##[error]Diff in /checkout/src/librustdoc/passes/collect_intra_doc_links.rs at line 1438:
         }
 
 
-        if explicit_link.ends_with(&display_text[..]) || display_text.ends_with(&explicit_link[..]) {
+        if explicit_link.ends_with(&display_text[..]) || display_text.ends_with(&explicit_link[..])
             self.resolve_with_disambiguator_cached(
                 display_res_info,
                 display_res_info,
                 diag_info.clone(), // this struct should really be Copy, but Range is not :(
##[error]Diff in /checkout/src/librustdoc/passes/lint/redundant_explicit_links.rs at line 99:
                 let explicit_link = dest.to_string();
                 let display_link = link_data.resolvable_link.clone()?;
 
-                if explicit_link.ends_with(&display_link) || display_link.ends_with(&explicit_link) {
+                if explicit_link.ends_with(&display_link) || display_link.ends_with(&explicit_link)
                     match link_type {
                     match link_type {
                         LinkType::Inline | LinkType::ReferenceUnknown => {
                             check_inline_or_reference_unknown_redundancy(
Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/src/librustdoc/html/render/write_shared.rs" "/checkout/src/librustdoc/passes/mod.rs" "/checkout/src/librustdoc/html/mod.rs" "/checkout/src/librustdoc/html/render [...]

2023-08-22 05:47 UTC, ChAoSUnItY approved these changes

2023-08-22 05:52 UTC, fmease commented
This should also fix #115062, right?

2023-08-22 19:58 UTC, GuillaumeGomez approved these changes

2023-08-22 19:58 UTC, GuillaumeGomez commented
Nice thanks!

@bors r=GuillaumeGomez,ChAoSUnItY

2023-08-23 01:56 UTC, merged

2023-08-23 04:36 UTC, rust-timer commented
Finished benchmarking commit (c6f5495591f1688b7d47a3c4085d84bd7dedde4c): [comparison URL](https://perf.rust-lang.org/compare.html?start=c469197b19d53a6c45378568f73c00986b20a5a5&end=c6f5495591f1688b7d47a3c4085d84bd7dedde4c&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=c469197b19d53a6c45378568f73c00986b20a5a5&end=c6f5495591f1688b7d47a3c4085d84bd7dedde4c&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=c469197b19d53a6c45378568f73c00986b20a5a5&end=c6f5495591f1688b7d47a3c4085d84bd7dedde4c&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.1% | [1.1%, 1.1%] | 1     |
| Regressions ❌ <br /> (secondary)  | 2.0% | [1.5%, 3.0%] | 7     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 1.1% | [1.1%, 1.1%] | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=c469197b19d53a6c45378568f73c00986b20a5a5&end=c6f5495591f1688b7d47a3c4085d84bd7dedde4c&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=c469197b19d53a6c45378568f73c00986b20a5a5&end=c6f5495591f1688b7d47a3c4085d84bd7dedde4c&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 634.642s -> 635.573s (0.15%)
**Artifact size**: 347.07 MiB -> 347.08 MiB (0.00%)

2023-09-01 09:21 UTC, apiraino commented
Beta backport approved

@rustbot label +beta-accepted