Remove incorrect mutability help suggestion
rust-lang/rust pull request #115648
Opened 2023-09-07 15:51 UTC by jmintb

This is a draft PR for #113767. It introduces a new test case and a mitigation which seems to work. I am submitting this now to get feedback before refining it further. I am pretty sure I am not covering all cases yet and I need to cleanup the rather insane destructuring haha.

The idea is to check for cases where the original value of a binding is immutable and then avoid suggesting that the type be specified in those cases. As that would not help.

To do this we first find the initial expression's kind HIR ID from the information in [`local.init.kind`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/hir/struct.Local.html), then use a map of HIR IDs to find a `Node`. Finally we determine it's mutability by destructing the `Node` to find it's type information.

I have a few questions:

1. Does this approach seem reasonable to you?
2. There are a lot of cases to cover here, should this be moved to a separate function/utility for determining binding mutability? or is there already something that does this perhaps?

This change causes three existing tests to fail `tests/ui/borrowck/borrowck-borrow-mut-base-ptr-in-aliasable-loc.rs`, `tests/ui/issues/issue-51515.rs` and  `tests/ui/process/nofile-limit.rs`, As far as I can tell the code is working correctly and the test needs to be updated.

We might be able to provide a better suggestion instead of just removing the existing one. Like "consider changing the mutability of the function/value used to initaliase your variable". Formulated more elegantly :sweat_smile:

2023-09-07 15:56 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/6111986799/job/16588452884) [(plain)](https://github.com/rust-lang/rust/commit/db4945ba3151e7257b1b26391518b82d5ebb8d20/checks/16588452884/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

error: unused import: `FnHeader`
 --> compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:5:48
  |
5 |     BindingAnnotation, Expr, ExprKind, FnDecl, FnHeader, FnRetTy, FnSig, Item, ItemKind, Pat,

error: unused import: `rustc_span::def_id::DefIdMap`
  --> compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:18:5
   |
---
   |
20 | use rustc_span::sym::anonymous_lifetime_in_impl_trait;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: the item `Expr` is imported redundantly
   --> compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:792:25
    |
5   |     BindingAnnotation, Expr, ExprKind, FnDecl, FnHeader, FnRetTy, FnSig, Item, ItemKind, Pat,
    |                        ---- the item `Expr` is already imported here
792 |             BorrowKind, Expr,
    |                         ^^^^

    Checking rustc_mir_transform v0.0.0 (/checkout/compiler/rustc_mir_transform)
    Checking rustc_mir_transform v0.0.0 (/checkout/compiler/rustc_mir_transform)
    Checking rustc_ty_utils v0.0.0 (/checkout/compiler/rustc_ty_utils)
error: unused variable: `local_type`
   --> compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:973:13
    |
973 |         let local_type = &self.local_names[local];
    |             ^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_local_type`
    = note: `-D unused-variables` implied by `-D warnings`

error: unused variable: `ty`
    --> compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:1120:71
    --> compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:1120:71
     |
1120 |                         Some(hir::ExprKind::Path(hir::QPath::Resolved(ty, hir::Path{res: Res::Local(id), ..} ))) => hir_map.find(*id),
     |                                                                       ^^ help: if this is intentional, prefix it with an underscore: `_ty`
error: unused variable: `byref`
    --> compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:1135:66
     |
     |
1135 |                         kind: PatKind::Binding(BindingAnnotation(byref, muta), ..),
     |                                                                  ^^^^^ help: if this is intentional, prefix it with an underscore: `_byref`
error: unused variable: `lf`
    --> compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:1146:71
     |
     |
1146 | ...                   kind: TyKind::Ref(lf, mu),
     |                                         ^^ help: if this is intentional, prefix it with an underscore: `_lf`
error: could not compile `rustc_borrowck` (lib) due to 9 previous errors
warning: build failed, waiting for other jobs to finish...
Build completed unsuccessfully in 0:01:31
  local time: Thu Sep  7 15:56:08 UTC 2023
```

</details>

2023-09-07 17:14 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/6112747009/job/16590857019) [(plain)](https://github.com/rust-lang/rust/commit/0eaa4c9d06b19ffd1cf09ebae66e45815012d3c4/checks/16590857019/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
Download action repository 'actions/upload-artifact@v3' (SHA:a8a3f3ad30e3422c9c7b888a15615d19a852ae32)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
---
Removing intermediate container 358abf9c2454
 ---> d48eab9f39ba
Step 6/10 : COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
 ---> 4c206d3a1a88
Step 7/10 : RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt     && pip3 install virtualenv
Collecting binaryornot==0.4.4
  Downloading binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
Collecting boolean-py==4.0
  Downloading boolean.py-4.0-py3-none-any.whl (25 kB)
---
Building wheels for collected packages: reuse
  Building wheel for reuse (pyproject.toml): started
  Building wheel for reuse (pyproject.toml): finished with status 'done'
  Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=180117 sha256=2196c9034bf565528bbb1ee6dad4f753eb813f58822363e6b768f09c73e4d4ff
  Stored in directory: /tmp/pip-ephem-wheel-cache-lly13tbq/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
---
  Downloading virtualenv-20.24.4-py3-none-any.whl (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 21.8 MB/s eta 0:00:00
Collecting filelock<4,>=3.12.2
  Downloading filelock-3.12.3-py3-none-any.whl (11 kB)
Collecting distlib<1,>=0.3.7
  Downloading distlib-0.3.7-py2.py3-none-any.whl (468 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 KB 49.2 MB/s eta 0:00:00
Collecting platformdirs<4,>=3.9.1
  Downloading platformdirs-3.10.0-py3-none-any.whl (17 kB)
Collecting typing-extensions>=4.7.1
  Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Installing collected packages: distlib, typing-extensions, platformdirs, filelock, virtualenv
Successfully installed distlib-0.3.7 filelock-3.12.3 platformdirs-3.10.0 typing-extensions-4.7.1 virtualenv-20.24.4
Removing intermediate container 4153ba78988a
 ---> 426054193350
Step 8/10 : COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
 ---> a54aa5056fa7
 ---> a54aa5056fa7
Step 9/10 : COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/
 ---> 741c386b7c41
Step 10/10 : ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
Removing intermediate container 553a1f3859d9
 ---> 9aae6cf5381a
Successfully built 9aae6cf5381a
Successfully tagged rust-ci:latest
Successfully tagged rust-ci:latest
##[endgroup]
Built container sha256:9aae6cf5381a1b2082fca7ba25bd0b8838e9dffdf01ee796924577d0117da2b7
Uploading finished image sha256:9aae6cf5381a1b2082fca7ba25bd0b8838e9dffdf01ee796924577d0117da2b7 to https://ci-caches.rust-lang.org/docker/31024a61e3c099341c4151411b61536c5a15e77991c1c58c8adf475bd61d8568f58aad59ac3149cca672919d01d664a203adb87f86665b006743ece22accf3f1
IMAGE          CREATED              CREATED BY                                      SIZE      COMMENT
9aae6cf5381a   1 second ago         /bin/sh -c #(nop)  ENV SCRIPT=TIDY_PRINT_DIF…   0B        
a54aa5056fa7   2 seconds ago        /bin/sh -c #(nop) COPY file:078ea1d11e7b7cda…   367B      
426054193350   3 seconds ago        |1 DEBIAN_FRONTEND=noninteractive /bin/sh -c…   24.1MB    
4c206d3a1a88   10 seconds ago       /bin/sh -c #(nop) COPY file:ac591dd6bc5afa66…   5.33kB    
d48eab9f39ba   12 seconds ago       |1 DEBIAN_FRONTEND=noninteractive /bin/sh -c…   23.1MB    
---
<missing>      3 weeks ago          /bin/sh -c #(nop)  LABEL org.opencontainers.…   0B        
<missing>      3 weeks ago          /bin/sh -c #(nop)  ARG LAUNCHPAD_BUILD_ARCH     0B        
<missing>      3 weeks ago          /bin/sh -c #(nop)  ARG RELEASE                  0B        

<botocore.awsrequest.AWSRequest object at 0x7faf99c65a90>
gzip: stdout: Broken pipe
xargs: docker: terminated by signal 13
https://ci-caches.rust-lang.org/docker/31024a61e3c099341c4151411b61536c5a15e77991c1c58c8adf475bd61d8568f58aad59ac3149cca672919d01d664a203adb87f86665b006743ece22accf3f1
sha256:9aae6cf5381a1b2082fca7ba25bd0b8838e9dffdf01ee796924577d0117da2b7
---
DirectMap4k:      174016 kB
DirectMap2M:     7165952 kB
DirectMap1G:    11534336 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
    Finished dev [unoptimized] target(s) in 0.03s
##[endgroup]
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/f06b7c59a383d51eee35470fd9cd1e0e545b5a5e/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/llvm-f06b7c59a383d51eee35470fd9cd1e0e545b5a5e-true/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm
---
    Finished release [optimized] target(s) in 26.03s
##[endgroup]
fmt check
tidy check
tidy error: following path contains more than 865 entries, you should move the test to some relevant subdirectory (current: 867): /checkout/tests/ui
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:1151: TODO is used for tasks that should be done before merging a PR; If you want to leave a message in the codebase use FIXME
##[error]tidy error: /checkout/compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:1154: trailing whitespace
##[error]tidy error: /checkout/compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:1156: TODO is used for tasks that should be done before merging a PR; If you want to leave a message in the codebase use FIXME
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (23.2.1)
Collecting black==23.3.0 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 7))
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 15.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 15.0 MB/s eta 0:00:00
Collecting click==8.1.3 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 34))
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
Collecting importlib-metadata==6.7.0 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 38))
  Downloading importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
  Downloading importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
Collecting mypy-extensions==1.0.0 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 42))
  Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Collecting packaging==23.1 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 46))
  Downloading packaging-23.1-py3-none-any.whl (48 kB)
Collecting pathspec==0.11.1 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 50))
  Downloading pathspec-0.11.1-py3-none-any.whl (29 kB)
  Downloading pathspec-0.11.1-py3-none-any.whl (29 kB)
Collecting platformdirs==3.6.0 (from -r /checkout/src/tools/tidy [...]

2023-09-12 05:45 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/6155369682/job/16702135701) [(plain)](https://github.com/rust-lang/rust/commit/0212c2002cdb51a5932c612a57a7db581cc8644c/checks/16702135701/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
Download action repository 'actions/upload-artifact@v3' (SHA:a8a3f3ad30e3422c9c7b888a15615d19a852ae32)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
---
Removing intermediate container 9f99108c992a
 ---> 319ce8931466
Step 6/10 : COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
 ---> 364711e6311c
Step 7/10 : RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt     && pip3 install virtualenv
Collecting binaryornot==0.4.4
  Downloading binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
Collecting boolean-py==4.0
  Downloading boolean.py-4.0-py3-none-any.whl (25 kB)
---
Building wheels for collected packages: reuse
  Building wheel for reuse (pyproject.toml): started
  Building wheel for reuse (pyproject.toml): finished with status 'done'
  Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=180117 sha256=2196c9034bf565528bbb1ee6dad4f753eb813f58822363e6b768f09c73e4d4ff
  Stored in directory: /tmp/pip-ephem-wheel-cache-85uoh2cm/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.6.0
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
---
  Downloading virtualenv-20.24.5-py3-none-any.whl (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 78.4 MB/s eta 0:00:00
Collecting filelock<4,>=3.12.2
  Downloading filelock-3.12.3-py3-none-any.whl (11 kB)
Collecting platformdirs<4,>=3.9.1
  Downloading platformdirs-3.10.0-py3-none-any.whl (17 kB)
Collecting distlib<1,>=0.3.7
  Downloading distlib-0.3.7-py2.py3-none-any.whl (468 kB)
Collecting typing-extensions>=4.7.1
  Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
  Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Installing collected packages: distlib, typing-extensions, platformdirs, filelock, virtualenv
Successfully installed distlib-0.3.7 filelock-3.12.3 platformdirs-3.10.0 typing-extensions-4.7.1 virtualenv-20.24.5
Removing intermediate container 7175bcefb48f
 ---> fe96c384541d
Step 8/10 : COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
 ---> 129acdd5f09f
 ---> 129acdd5f09f
Step 9/10 : COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/
 ---> 8ab35508b5a1
Step 10/10 : ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
Removing intermediate container bff53372c447
 ---> c6178bffe0f4
Successfully built c6178bffe0f4
Successfully tagged rust-ci:latest
Successfully tagged rust-ci:latest
##[endgroup]
Built container sha256:c6178bffe0f43ddea2717e82e691411ab9fa2800fd7a74df8bc359c619bc7549
Uploading finished image sha256:c6178bffe0f43ddea2717e82e691411ab9fa2800fd7a74df8bc359c619bc7549 to https://ci-caches.rust-lang.org/docker/31024a61e3c099341c4151411b61536c5a15e77991c1c58c8adf475bd61d8568f58aad59ac3149cca672919d01d664a203adb87f86665b006743ece22accf3f1
IMAGE          CREATED          CREATED BY                                      SIZE      COMMENT
c6178bffe0f4   1 second ago     /bin/sh -c #(nop)  ENV SCRIPT=TIDY_PRINT_DIF…   0B        
129acdd5f09f   2 seconds ago    /bin/sh -c #(nop) COPY file:078ea1d11e7b7cda…   367B      
fe96c384541d   3 seconds ago    |1 DEBIAN_FRONTEND=noninteractive /bin/sh -c…   24.1MB    
364711e6311c   9 seconds ago    /bin/sh -c #(nop) COPY file:ac591dd6bc5afa66…   5.33kB    
319ce8931466   10 seconds ago   |1 DEBIAN_FRONTEND=noninteractive /bin/sh -c…   23.1MB    
---
<missing>      3 weeks ago      /bin/sh -c #(nop)  LABEL org.opencontainers.…   0B        
<missing>      3 weeks ago      /bin/sh -c #(nop)  ARG LAUNCHPAD_BUILD_ARCH     0B        
<missing>      3 weeks ago      /bin/sh -c #(nop)  ARG RELEASE                  0B        

<botocore.awsrequest.AWSRequest object at 0x7fd136c19d50>
gzip: stdout: Broken pipe
xargs: docker: terminated by signal 13
https://ci-caches.rust-lang.org/docker/31024a61e3c099341c4151411b61536c5a15e77991c1c58c8adf475bd61d8568f58aad59ac3149cca672919d01d664a203adb87f86665b006743ece22accf3f1
sha256:c6178bffe0f43ddea2717e82e691411ab9fa2800fd7a74df8bc359c619bc7549
---
DirectMap4k:      182208 kB
DirectMap2M:     7157760 kB
DirectMap1G:    11534336 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
    Finished dev [unoptimized] target(s) in 0.03s
##[endgroup]
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/366dab13f711df90a6891411458544199d159cbc/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/llvm-366dab13f711df90a6891411458544199d159cbc-true/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm
---
    Finished release [optimized] target(s) in 25.75s
##[endgroup]
fmt check
tidy check
tidy error: following path contains more than 865 entries, you should move the test to some relevant subdirectory (current: 867): /checkout/tests/ui
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:1262: TODO is used for tasks that should be done before merging a PR; If you want to leave a message in the codebase use FIXME
##[error]tidy error: /checkout/compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:1265: trailing whitespace
##[error]tidy error: /checkout/compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs:1267: TODO is used for tasks that should be done before merging a PR; If you want to leave a message in the codebase use FIXME
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (23.2.1)
Collecting black==23.3.0 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 7))
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 28.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 28.1 MB/s eta 0:00:00
Collecting click==8.1.3 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 34))
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
Collecting importlib-metadata==6.7.0 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 38))
  Downloading importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
  Downloading importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
Collecting mypy-extensions==1.0.0 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 42))
  Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Collecting packaging==23.1 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 46))
  Downloading packaging-23.1-py3-none-any.whl (48 kB)
Collecting pathspec==0.11.1 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 50))
  Downloading pathspec-0.11.1-py3-none-any.whl (29 kB)
  Downloading pathspec-0.11.1-py3-none-any.whl (29 kB)
Collecting platformdirs==3.6.0 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 54))
  Downloading plat [...]

2023-10-07 16:09 UTC, jackh726 requested changes
It's times like this that I think that actually just "applying" suggested fix and checking if the new code would compile would be super helpful.

I think this is just an improvement, even if not perfect. Please bless the broken tests, address the review comments, and fix formatting. Should move the added test to a proper directory with a useful name - and add a comment on what the test is testing. (Alternatively, could move the test case into an existing test if there's one that fits.

2023-10-07 16:09 UTC, jackh726 commented on compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs
> +                                todo!("What do we do here?")
We *could* have a fallback case that just has a more lax "you may be able to change the mutability here". I'm not sure if the binding info is available cross-crates.

2023-10-07 16:09 UTC, jackh726 commented on compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs
> +                    _ => Mutability::Mut, // TODO: this probably is not correct handling of this case.
Eh, it's okay. Just leave a note that other cases might not be covered.

2023-10-07 16:09 UTC, jackh726 commented on compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs
> +                    // TODO: Could we provide an alternative suggestions around altering the mutability
This is fine to leave as a FIXME, or just remove.

2023-10-07 16:09 UTC, jackh726 commented on compiler/rustc_borrowck/src/diagnostics/mutability_errors.rs
> +                    // FOUND IT
??

2024-02-14 17:13 UTC, Dylan-DPC commented
@jmintb any updates on this

2024-02-19 09:24 UTC, jmintb commented
> @jmintb any updates on this

Sorry I forgot to come back to this. Will get on it soon.

2024-07-31 06:36 UTC, Dylan-DPC commented
@jmintb any updates on this? thanks

2024-09-26 08:44 UTC, Dylan-DPC commented
Closing this as inactive. Feel free to reöpen this pr or create a new pr if you get the time to work on this. Thanks

2024-09-26 08:44 UTC, closed without merging