Split out `lit_to_const_for_patterns`
rust-lang/rust pull request #116251
Opened 2023-09-28 22:23 UTC by compiler-errors

This allows us to delay normalizing const types in adt_const_params, fixing `tests/ui/const-generics/projection-as-arg-const.rs`

r? @BoxyUwU 

Let me know if anything needs more comments, more validation or tests.

2023-09-28 22:53 UTC, compiler-errors commented on compiler/rustc_middle/src/query/mod.rs
> +    ) -> Option<ty::Const<'tcx>> {
this query could alternatively *just* return an (option of) valtree to make it clear what it's doing

2023-09-28 22:54 UTC, compiler-errors commented on compiler/rustc_mir_build/src/thir/constant.rs
>  pub(crate) fn lit_to_const<'tcx>(
naming: we could call this `lit_to_const_eager` or something, to help make it clear that it's trying to eagerly convert lits when possible, but will hold off from doing so if not possible (i.e. we don't have the right type info).

2023-09-28 22:54 UTC, compiler-errors commented on compiler/rustc_mir_build/src/thir/constant.rs
> +        (ast::LitKind::Str(s, _), ty::Ref(_, inner_ty, _)) if inner_ty.is_str() => {
this function could ignore the types in the litkinds that don't actually matter?

2023-10-04 00:53 UTC, BoxyUwU requested changes
Though generally i'm not confident having two queries here is fun lol

2023-10-04 00:53 UTC, BoxyUwU commented on tests/ui/const-generics/projection-as-arg-const.rs
> +// build-pass
imo this should be a revision, we want to keep asserting that aliases dont work as the type of const params without adt_const_param i think

2023-10-04 00:53 UTC, BoxyUwU commented on compiler/rustc_ty_utils/src/consts.rs
> +            match tcx.at(sp).lit_to_const_for_patterns(LitToConstInput {
this is definitely not a pattern xd we'd end up here for things like the `1` in `foo::<{ N + 1 }>();`

2024-01-08 15:20 UTC, compiler-errors commented
don't have the time to bring this back into cache. my understanding is that we should not be so type-dependent in lit_to_const, because we may receive unnormalized typed.

2024-01-08 15:20 UTC, closed without merging