Suggests compiler to update if on older version when using `unstable` feature
rust-lang/rust pull request #117346
Opened 2023-10-29 09:16 UTC by Rajveer100

Part of Issue #117318

Added additional `note` suggesting compiler update in the `.ftl` file when calling `unstable` feature error diagnostic in either case of `Some` or `None`.

Potential addition would be to check the `system time` and compare with the last successful build.

2023-10-29 09:18 UTC, Rajveer100 commented
@rustbot +S-waiting-on-review

2023-10-29 09:23 UTC, Rajveer100 commented
@lcnr
Let me know your thoughts and suggestions.

2023-10-29 10:18 UTC, Nilstrieb requested changes
This is not quite the right place to put it. It's just about unstable trait items, while the note should be for all unstable features, language features an library. For example, it should show up for `let_chains`.

When you get hundreds of test failures, you've done it correctly (and then can `--bless` them).

2023-10-30 14:07 UTC, lcnr commented
r? @Nilstrieb feel free to reassign

2023-11-05 17:42 UTC, Rajveer100 commented
@Nilstrieb 
I am facing this issue which showed up recently:

```
dyld[33699]: Library not loaded: @rpath/libunwind.1.dylib
  Referenced from: <E1638B0C-A3EC-382E-AD9A-5AA346E830F0> /Users/rajveersingh/GitHub-OpenSource/rust-project/rust/build/bootstrap/debug/bootstrap
  Reason: no LC_RPATH's found
```

I did research across places but didn't seem to have found the solution. This exact issue had also occurred in `RustRover IDE` (only in `debug` mode), which I fixed by adding an environment variable this way:

```
DYLD_LIBRARY_PATH=/usr/local/lib
```

2023-11-05 18:39 UTC, Nilstrieb commented
I have no clue as I don't know much about MacOS. Ask on Zulip instead. Maybe delete your build directory and try again?

2023-11-07 11:13 UTC, Rajveer100 commented
I have put a topic on `zulip`, although haven't received any fix yet. Will try figuring it out in the meantime.

2023-11-22 19:07 UTC, Rajveer100 commented
@Nilstrieb 
The issue is now resolved! For people who do encounter this in the future, in my case this was caused due to some issues during `libc++` `trunk` installation for `llvm`, I just deleted all files with `lib*` in `/usr/local/lib` and it's fixed. This was due to system searching for `@rpath/libunwind.1.dylib` in wrong places instead `OS default`.

I will do the changes for next review!

2023-11-23 10:33 UTC, Rajveer100 commented
Regarding `tests`, I currently see over 15000+ which obviously isn't intended, do you have any suggestions to which ones I can target `locally`?

2023-11-24 06:52 UTC, Nilstrieb commented
Running all 15000 is correct, but only a few of them should fail. i means the test was ignored, . Means it passed

2023-11-26 11:28 UTC, Rajveer100 commented
How do I specify the `./x test --bless` to use `lldb` instead of `gdb` as my system is based on `arm` architecture and `gdb` is for `x86`?

2023-11-26 11:42 UTC, Nilstrieb commented
Uh I think there should be a property in config.toml. alternatively just run `x test tests/ui` to only test UI tests, that should be enough and doesn't run the annoying debuginfo tests.

2023-11-27 09:56 UTC, Rajveer100 commented
While `testing`, is there an option to specify an older `version` of rust to test `unstable library features` which are currently stable? Also, regarding few among them like as you pointed about `if let chains`, it's a different diagnostics  and does not have a similar `.ftl` based file, instead I see a `gate_all!` macro which I guess acts as a `print!`. 

I presume there would be a lot more as such and they don't have a `global callers` or `trigger` to detect them at one place, instead of changing every sort of `diagnostic`.

2023-12-18 17:49 UTC, Rajveer100 commented
@Nilstrieb 
I am closing this PR, @George-lewis has opened a [PR](https://github.com/rust-lang/rust/pull/119088) for this issue, and I would be more than happy to learn from that, looking through other issues in the meantime.

2023-12-18 17:49 UTC, closed without merging