Overlapping associated types diagnostics
rust-lang/rust pull request #117642
Opened 2023-11-06 20:42 UTC by TheLazyDutchman

Previously, when you tried to set an associated type that is shadowed by an associated type in a subtrait, like this:
```rust
trait A {
    type X;
}

trait B: A {
    type X; // note: this is legal
}

impl<Y> Clone for Box<dyn B<X=Y, X=Y>> {
    fn clone(&self) -> Self {
        todo!()
    }
}
```
you got a confusing error message, that says nothing about the shadowing:
```rust
error[E0719]: the value of the associated type `X` (from trait `B`) is already specified
 --> test.rs:9:34
  |
9 | impl<Y> Clone for Box<dyn B<X=Y, X=Y>> {
  |                             ---  ^^^ re-bound here
  |                             |
  |                             `X` bound here first

error[E0191]: the value of the associated type `X` (from trait `A`) must be specified
 --> test.rs:9:27
  |
2 |     type X;
  |     ------ `X` defined here
...
9 | impl<Y> Clone for Box<dyn B<X=Y, X=Y>> {
  |                           ^^^^^^^^^^^ help: specify the associated type: `B<X=Y, X=Y, X = Type>`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0191, E0719.
For more information about an error, try `rustc --explain E0191`.
```
Now instead, the error shows that the associated type is shadowed, and suggests renaming as a potential fix.
```rust
error[E0719]: the value of the associated type `X` in trait `B` is already specified
 --> test.rs:9:34
  |
9 | impl<Y> Clone for Box<dyn B<X=Y, X=Y>> {
  |                             ---  ^^^ re-bound here
  |                             |
  |                             `X` bound here first

error[E0191]: the value of the associated type `X` in `A` must be specified
 --> test.rs:9:27
  |
2 |     type X;
  |     ------ `A::X` defined here
...
6 |     type X; // note: this is legal
  |     ------ `A::X` shadowed here
...
9 | impl<Y> Clone for Box<dyn B<X=Y, X=Y>> {
  |                           ^^^^^^^^^^^ associated type `X` must be specified
  |
help: consider renaming this associated type
 --> test.rs:2:5
  |
2 |     type X;
  |     ^^^^^^
help: consider renaming this associated type
 --> test.rs:6:5
  |
6 |     type X; // note: this is legal
  |     ^^^^^^

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0191, E0719.
For more information about an error, try `rustc --explain E0191`.
```

The rename help message is only emitted when the trait is local. This is true both for the supertrait as for the subtrait.

There might be cases where you can use the fully qualified path (for instance, in a where clause), but this PR currently does not deal with that.

2023-11-06 20:43 UTC, TheLazyDutchman commented
fixes #100109

2023-11-06 20:58 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-15`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/6776311102/job/18417514745) [(plain)](https://github.com/rust-lang/rust/commit/e9a900d6c816ebd1bf231ea6a28ad2b2dabdb26d/checks/18417514745/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=TheLazyDutchman
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_66055dfa-671e-4518-873b-b9ebcb3edf6f
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=f4114698dd28d2d5cb2e0871098fc58fd6957c39
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_66055dfa-671e-4518-873b-b9ebcb3edf6f
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_66055dfa-671e-4518-873b-b9ebcb3edf6f
GITHUB_TRIGGERING_ACTOR=TheLazyDutchman
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/117642/merge
GITHUB_WORKFLOW_SHA=f4114698dd28d2d5cb2e0871098fc58fd6957c39
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.13/x64
---
---- [ui] tests/ui/associated-type-bounds/overlaping-bound-suggestion.rs stdout ----
diff of stderr:

6    |             |                  |
7    |             |                  associated types `Item`, `IntoIter` must be specified
8    |             associated types `Item`, `IntoIter` must be specified
+   --> $SRC_DIR/core/src/iter/traits/collect.rs:LL:COL
+    = note: `IntoIterator::Item` shadowed here
+    |
+    = note: `IntoIterator::Item` shadowed here
9 
---
status: exit status: 1
command: RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/associated-type-bounds/overlaping-bound-suggestion.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/associated-type-bounds/overlaping-bound-suggestion" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/associated-type-bounds/overlaping-bound-suggestion/auxiliary"
stdout: none
--- stderr -------------------------------
error[E0191]: the value of the associated types `Item`, `Item`, `IntoIter` and `IntoIter` in `IntoIterator` must be specified
   |
   |
LL |     inner: <IntoIterator<Item: IntoIterator<Item: >>::IntoIterator as Item>::Core,
   |             |                  |
   |             |                  |
   |             |                  associated types `Item`, `IntoIter` must be specified
   |             associated types `Item`, `IntoIter` must be specified
  --> /rustc/FAKE_PREFIX/library/core/src/iter/traits/collect.rs:243:5
   = note: `IntoIterator::Item` shadowed here
   |
   = note: `IntoIterator::Item` shadowed here


error[E0223]: ambiguous associated type
##[error]  --> /checkout/tests/ui/associated-type-bounds/overlaping-bound-suggestion.rs:7:13
Build completed unsuccessfully in 0:12:56
   |
LL |     inner: <IntoIterator<Item: IntoIterator<Item: >>::IntoIterator as Item>::Core,
   |
   |
help: if there were a trait named `Example` with associated type `IntoIterator` implemented for `(dyn IntoIterator + 'static)`, you could use the fully-qualified path
   |
LL |     inner: <<(dyn IntoIterator + 'static) as Example>::IntoIterator as Item>::Core,

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0191, E0223.
```

</details>

2023-11-06 21:01 UTC, compiler-errors commented
Thanks for the contribution! This needs a UI test. 

Also, can you amend the PR title to have some sort of verb? "[Point out] overlapping associated types [when...?]" or something is more conventional title for a PR like this.

Also, can you squash the commits into one?

@rustbot author

2023-11-06 21:09 UTC, compiler-errors requested changes

2023-11-06 21:09 UTC, compiler-errors commented on compiler/rustc_hir_analysis/src/astconv/errors.rs
> +        let bound_names = trait_bounds
Can you explain what this code is doing? Some comments throuhout may be helpful.

2023-11-06 21:09 UTC, compiler-errors commented on compiler/rustc_hir_analysis/src/astconv/errors.rs
> +                    x.args.iter().flat_map(|args| {
Why are you looking at all of the segments in the trait ref? That shouldn't be necessary. Only the final path segment should be interesting here.

2023-11-06 21:09 UTC, compiler-errors commented on compiler/rustc_hir_analysis/src/astconv/errors.rs
> +                    x.args.iter().flat_map(|args| {
Also, please don't `iter()` over an `Option` -- `if let` or `let .. else` should work here more effectively.

2023-11-06 21:09 UTC, compiler-errors commented on compiler/rustc_hir_analysis/src/astconv/errors.rs
> +                                tcx.associated_items(did).filter_by_name_unhygienic(name).next()
We shouldn't be filtering unhygenically. You have an identifier in `binding.ident`.

2023-11-07 09:36 UTC, closed without merging

2023-11-07 10:40 UTC, TheLazyDutchman commented
continues in #117661, because I didn't know renaming the branch would close the PR