When a local binding shadows a fn, point at fn def in call failure
rust-lang/rust pull request #117924
Opened 2023-11-15 01:29 UTC by estebank

When a local binding shadows a function that is then called, this local binding will cause an E0618 error. We now point not only at the binding definition, but also at the locally defined function of the same name.

```
error[E0618]: expected function, found `&str`
  --> $DIR/issue-22468.rs:3:13
   |
LL |     let foo = "bar";
   |         --- `foo` has type `&str`
LL |     let x = foo("baz");
   |             ^^^-------
   |             |
   |             call expression requires function
...
LL | fn foo(file: &str) -> bool {
   | -------------------------- this function of the same name is avalable here, but it shadowed by the local binding of the same name
```

Fix #53841

2023-11-15 06:11 UTC, fmease requested changes

2023-11-15 06:11 UTC, fmease commented on compiler/rustc_hir_typeck/src/callee.rs
> +                        "this function of the same name is available here, but it shadowed by the \
```suggestion
                        "this function of the same name is available here, but it's shadowed by the \
```

2023-11-17 21:20 UTC, petrochenkov commented on compiler/rustc_hir_typeck/src/callee.rs
> +            && path.segments.len() == 1
```suggestion
            && let [seg] = &*path.segments
```

2023-11-17 21:20 UTC, petrochenkov commented on compiler/rustc_hir_typeck/src/callee.rs
> +                    && item.ident.name == name
```suggestion
                    && item.ident.name == seg.ident.name
```
Minor cleanup.

2023-11-17 21:21 UTC, petrochenkov commented
r=me with cleanup.
@rustbot author

2023-11-18 00:40 UTC, estebank commented
@bors r=petrochenkov

2023-11-18 12:44 UTC, merged

2023-11-18 14:06 UTC, rust-timer commented
Finished benchmarking commit (e1e60b6976ed51e9464d15a2888d90c577dda223): [comparison URL](https://perf.rust-lang.org/compare.html?start=6416e2e675504abc924592452e5f6874fdddb0dd&end=e1e60b6976ed51e9464d15a2888d90c577dda223&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=6416e2e675504abc924592452e5f6874fdddb0dd&end=e1e60b6976ed51e9464d15a2888d90c577dda223&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=6416e2e675504abc924592452e5f6874fdddb0dd&end=e1e60b6976ed51e9464d15a2888d90c577dda223&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -0.8% | [-0.8%, -0.8%] | 1     |
| Improvements ✅ <br /> (secondary) | -2.9% | [-4.0%, -2.3%] | 3     |
| All ❌✅ (primary)                 | -0.8% | [-0.8%, -0.8%] | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=6416e2e675504abc924592452e5f6874fdddb0dd&end=e1e60b6976ed51e9464d15a2888d90c577dda223&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -3.6% | [-3.6%, -3.6%] | 1     |
| All ❌✅ (primary)                 | -     | -              | 0     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=6416e2e675504abc924592452e5f6874fdddb0dd&end=e1e60b6976ed51e9464d15a2888d90c577dda223&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 675.683s -> 678.285s (0.39%)
**Artifact size**: 313.83 MiB -> 313.84 MiB (0.00%)