[rustdoc] Fix display of features
rust-lang/rust pull request #118677
Opened 2023-12-06 14:46 UTC by GuillaumeGomez

Fixes https://github.com/rust-lang/rust/issues/118615.

It now looks like this:

![Screenshot from 2023-12-06 15-30-24](https://github.com/rust-lang/rust/assets/3050060/f09b841f-c200-4f96-a92e-c4c1db61b755)

We can't use flex without breaking the flow, meaning we can't vertically align items as we want. Because of that, the `min-height` was problematic as it rendered weirdly and therefore needed to be removed.

r? @notriddle

2023-12-06 15:00 UTC, GuillaumeGomez commented
With `line-height: 36px;`:

![image](https://github.com/rust-lang/rust/assets/3050060/4c064b11-2abd-4e0b-bf61-688a6f7108c9)

2023-12-06 16:07 UTC, GuillaumeGomez commented on src/librustdoc/html/static/css/rustdoc.css
> -	width: fit-content;
It wasn't in use said firefox, so I removed it.

2023-12-06 16:08 UTC, GuillaumeGomez commented
> Right, but the point of me asking is that the ones with the 👎 should be the same height as the ones without any emoji in them, as well as items like this:
> 
> ![image](https://private-user-images.githubusercontent.com/1593513/288469802-ecafe681-f7a3-42f0-a8b9-e9cfc98639aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzkxMjksIm5iZiI6MTcwMTg3ODgyOSwicGF0aCI6Ii8xNTkzNTEzLzI4ODQ2OTgwMi1lY2FmZTY4MS1mN2EzLTQyZjAtYThiOS1lOWNmYzk4NjM5YWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDZUMTYwNzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjk5ZmE1YzI1NjRhYzhiZTRiODM3NmI0Y2QyOGEyNzhhZjZjOWZjNjUyYjMwZjI4MTJlZGU0NjIzMDgwNjQ0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RlRYSSajtpUGKHtIbTaQVnfpTDxTEo7LhpvtifqBe8M)

I explained my reasoning here:

> We can't use flex without breaking the flow, meaning we can't vertically align items as we want. Because of that, the `min-height` was problematic as it rendered weirdly and therefore needed to be removed.

2023-12-06 16:36 UTC, GuillaumeGomez commented on src/librustdoc/html/static/css/rustdoc.css
> -	width: fit-content;
Ah then we know why I changed it. :D

2023-12-06 18:55 UTC, GuillaumeGomez commented on src/librustdoc/html/static/css/rustdoc.css
> -	width: fit-content;
Oh you're right. No I didn't meant to change it. Might be worth doing it though but I'll open another PR for that. Let me revert this change.

2023-12-06 19:00 UTC, GuillaumeGomez commented
I reverted the unwanted width change. I think it's worth considering it but let's do that in another PR.

2023-12-06 19:16 UTC, GuillaumeGomez commented on src/librustdoc/html/static/css/rustdoc.css
> -	width: fit-content;
No don't worry. Just curious about the why. It looks very bad with it. Even more when there are no emoji.

2023-12-06 19:30 UTC, GuillaumeGomez commented on src/librustdoc/html/static/css/rustdoc.css
>  	padding: 3px;
Still looks bad when there is more than one line:

![image](https://github.com/rust-lang/rust/assets/3050060/70f266e2-b940-4076-b71a-60a4c8dd9115)

2023-12-06 23:40 UTC, notriddle requested changes

2023-12-07 09:45 UTC, GuillaumeGomez commented
Updated!

2023-12-08 00:22 UTC, notriddle approved these changes

2023-12-08 09:28 UTC, merged