Fix BinOp `ty()` assertion and `fn_sig()` for closures
rust-lang/rust pull request #118846
Opened 2023-12-12 00:12 UTC by celinval

`BinOp::ty()` was asserting that the argument types were primitives. However, the primitive checks don't include pointers, which can be used in a `BinaryOperation`. Thus extend the arguments to include them.

Since I had to add methods to check for pointers in TyKind, I just went ahead and added a bunch more utility checks that can be handy for our users and fixed the `fn_sig()` method to also include closures.

@compiler-errors just wanted to confirm that today no `BinaryOperation` accept SIMD types. Is that correct?

r? @compiler-errors

2023-12-12 00:27 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7175018562/job/19537578056) [(plain)](https://github.com/rust-lang/rust/commit/2f790af726e69d66952233957129f22c70b98001/checks/19537578056/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=celinval
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_bcc6c65f-f630-44fd-8430-935cfc003967
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=57655e8a0591072a1d0ffd03efb68136f9b448ba
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_bcc6c65f-f630-44fd-8430-935cfc003967
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_bcc6c65f-f630-44fd-8430-935cfc003967
GITHUB_TRIGGERING_ACTOR=celinval
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/118846/merge
GITHUB_WORKFLOW_SHA=57655e8a0591072a1d0ffd03efb68136f9b448ba
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.13/x64
---
 Documenting rustc_graphviz v0.0.0 (/checkout/compiler/rustc_graphviz)
error: unclosed HTML tag `T`
   --> compiler/stable_mir/src/ty.rs:865:13
    |
865 | /// A Binder<T> represents a possibly generic type and its bound vars.
    |
    = note: `-D rustdoc::invalid-html-tags` implied by `-D warnings`
    = note: `-D rustdoc::invalid-html-tags` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(rustdoc::invalid_html_tags)]`
    |
    |
865 | /// A `Binder<T>` represents a possibly generic type and its bound vars.

 Documenting rustc_error_codes v0.0.0 (/checkout/compiler/rustc_error_codes)
error: could not document `stable_mir`


Caused by:
  process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustdoc --edition=2021 --crate-type lib --crate-name stable_mir compiler/stable_mir/src/lib.rs --target x86_64-unknown-linux-gnu -o /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/doc -Zunstable-options --check-cfg 'cfg(feature, values())' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=d9a3640ddc85a8a0 -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps --extern scoped_tls=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libscoped_tls-ed2db062fd97003f.rmeta --extern tracing=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/libtracing-5f701b99da500b8b.rmeta --extern-html-root-url 'scoped_tls=https://docs.rs/scoped-tls/1.0.1/' --extern-html-root-url 'tracing=https://docs.rs/tracing/0.1.37/' -Zunstable-options --cfg=bootstrap --cfg=windows_raw_dylib -Csymbol-mangling-version=v0 -Zunstable-options '--check-cfg=cfg(bootstrap,values())' '--check-cfg=cfg(parallel_compiler,values())' '--check-cfg=cfg(no_btreemap_remove_entry,values())' '--check-cfg=cfg(crossbeam_loom,values())' '--check-cfg=cfg(span_locations,values())' '--check-cfg=cfg(rustix_use_libc,values())' '--check-cfg=cfg(emulate_second_only_system,values())' '--check-cfg=cfg(windows_raw_dylib,values())' --document-private-items --document-hidden-items -Dwarnings '-Wrustdoc::invalid_codeblock_attributes' --crate-version '1.76.0-nightly (57655e8a0 2023-12-12)' --document-private-items '-Arustdoc::private-intra-doc-links' --enable-index-page -Zunstable-options -Znormalize-docs --show-type-layout --generate-link-to-definition '-Zcrate-attr=warn(rust_2018_idioms)' --cfg=parallel_compiler --extern-html-root-url 'ena=https://docs.rs/ena/latest/'` (exit status: 1)
Build completed unsuccessfully in 0:01:17
  local time: Tue Dec 12 00:27:23 UTC 2023
  network time: Tue, 12 Dec 2023 00:27:23 GMT
##[error]Process completed with exit code 1.
```

</details>

2023-12-12 01:08 UTC, compiler-errors requested changes
Some questions.

> just wanted to confirm that today no BinaryOperation accept SIMD types. Is that correct?

I don't think we lower SIMD intrinsics to MIR binops like we do for primitives, I can see it's not happening in `compiler/rustc_mir_transform/src/lower_intrinsics.rs`.

2023-12-12 02:11 UTC, celinval commented on compiler/stable_mir/src/ty.rs
> +    pub fn is_scalar(&self) -> bool {
This is meant to be helper functions for tools developed on the top of StableMIR. In Kani, we use a bunch of these functions today, and while migrating to StableMIR, we have been writing a bunch of them. Like here: https://github.com/model-checking/kani/blob/9090db33a7d98e3ec25ec604d4f4cf9481fd6add/kani-compiler/src/codegen_cprover_gotoc/codegen/place.rs#L784-L790


 That said, I can definitely remove the ones that are not very clear like this one.

2023-12-12 02:12 UTC, compiler-errors commented on compiler/stable_mir/src/ty.rs
> +    pub fn is_scalar(&self) -> bool {
I would remove this one in particular unless there is a particular use for it, or else it needs to have its behavior documented pretty precisely.

2023-12-12 02:18 UTC, celinval commented on compiler/stable_mir/src/mir/body.rs
> +        assert!(lhs_kind.is_primitive() || lhs_kind.is_any_ptr());
```rust
/// Example of a function pointer being using in `BinOp::Eq`.
pub fn test_reify_fn_pointer() {
    assert!(poly::<usize> as fn() == poly::<usize> as fn());
}

fn poly<T>() {}

/// Here is an example of raw pointer being used with `BinOp::Le`:
pub fn check_raw_ptr() {
    let arr = [0, 1];
    let ptr_0 : *const u8 = &arr[0];
    let ptr_1 : *const u8 = &arr[1];
    assert!(ptr_0 < ptr_1);
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=093d1794ee25e921ba3dd819ec7a151b

2023-12-12 02:19 UTC, celinval commented on compiler/stable_mir/src/ty.rs
> +    pub fn is_scalar(&self) -> bool {
Is there any other function that you recommend removing?

2023-12-12 02:20 UTC, compiler-errors commented on compiler/stable_mir/src/ty.rs
> +    pub fn is_scalar(&self) -> bool {
No, just this one

2023-12-12 02:57 UTC, celinval commented on compiler/stable_mir/src/mir/body.rs
> +        assert!(lhs_kind.is_primitive() || lhs_kind.is_any_ptr());
and offset. :smile:

2023-12-12 02:59 UTC, compiler-errors commented on compiler/stable_mir/src/mir/body.rs
> +        assert!(lhs_kind.is_primitive() || lhs_kind.is_any_ptr());
Still could be done then?

2023-12-12 04:00 UTC, celinval commented
@compiler-errors let me know if there's anything else you would like me to change.

2023-12-12 04:12 UTC, compiler-errors approved these changes
r=me

2023-12-12 05:40 UTC, celinval commented
@bors r=@compiler-errors rollup

2023-12-12 08:21 UTC, merged

2023-12-14 01:37 UTC, workingjubilee commented
> I don't think we lower SIMD intrinsics to MIR binops like we do for primitives, I can see it's not happening in `compiler/rustc_mir_transform/src/lower_intrinsics.rs`.

Correct, SIMD operations have their own path because they tend to be expressed as "don't think too hard about what's happening here in the MIR, this is just going to be lowered by the CG backend".