fix: correct the args for `disambiguate the associated function` diagnostic
rust-lang/rust pull request #118911
Opened 2023-12-13 12:05 UTC by Young-Flash

This is somehow silimar to https://github.com/rust-lang/rust/pull/118502, we shouldn't take receiver as first arg all the cases.

close https://github.com/rust-lang/rust/issues/118819

2023-12-13 12:15 UTC, fmease commented on compiler/rustc_hir_typeck/src/method/suggest.rs
> +                && (t.to_string() == "Self" || t == trait_impl_type)
Without having checked if the rest of your implementation makes sense, I'll suggest the following:

```suggestion
                && (t == tcx.types.self_param || t == trait_impl_type)
```

2023-12-13 12:21 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7194925268/job/19596505478) [(plain)](https://github.com/rust-lang/rust/commit/57eed0555840b4827d6ee31dcd8fe792b5f39012/checks/19596505478/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=Young-Flash
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_376f680a-46a4-4be8-84e3-3e3d1b5c1ade
GITHUB_EVENT_NAME=pull_request
GITHUB_EVENT_NAME=pull_request
GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
GITHUB_GRAPHQL_URL=https://api.github.com/graphql
GITHUB_HEAD_REF=fix_issue_118819
GITHUB_JOB=pr
GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_376f680a-46a4-4be8-84e3-3e3d1b5c1ade
GITHUB_REF=refs/pull/118911/merge
GITHUB_REF_NAME=118911/merge
GITHUB_REF_PROTECTED=false
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=76b615cd67c837e0e213c3aa8cf51b516db510cf
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_376f680a-46a4-4be8-84e3-3e3d1b5c1ade
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_376f680a-46a4-4be8-84e3-3e3d1b5c1ade
GITHUB_TRIGGERING_ACTOR=Young-Flash
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/118911/merge
GITHUB_WORKFLOW_SHA=76b615cd67c837e0e213c3aa8cf51b516db510cf
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.13/x64
---
Built container sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Looks like docker image is the same as before, not uploading
https://ci-caches.rust-lang.org/docker/7ebc15c01a233894034d277c8cce4e949f4e7791f66b4727c8fb6e058a0b8171d6152e1441d677cef0653843ceeee469c097b8699b2bb74249e674f6aa1a8813
sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-16]
##[group]Clock drift check
  local time: Wed Dec 13 12:07:11 UTC 2023
  network time: Wed, 13 Dec 2023 12:07:11 GMT
  network time: Wed, 13 Dec 2023 12:07:11 GMT
##[endgroup]
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-16', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-missing-tools', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-16/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: rust.codegen-units-std := 1
---
....ii..................................................................i...............  8888/15950
........................................................................................  8976/15950
........................................................................................  9064/15950
...........ii...........................................................................  9152/15950
...............F.......F.........................................i......................  9240/15950
........................................................................................  9416/15950
..............ii.................i......i..i............................................  9504/15950
...................................i....................................................  9592/15950
........................................................................................  9680/15950
---

20    |         ~~~~~~~~~~~~~~~~~~~~~~~~~~
21 help: disambiguate the method for candidate #2
22    |
- LL |         Add::to_int(&self) + other.to_int()
-    |         ~~~~~~~~~~~~~~~~~~
+ LL |         Add::to_int(&) + other.to_int()
25 
26 error: aborting due to 1 previous error
27 

---
To only update this specific test, also pass `--test-args issues/issue-3702-2.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/issues/issue-3702-2.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-3702-2" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-3702-2/auxiliary"
--- stderr -------------------------------
error[E0034]: multiple applicable items in scope
##[error]  --> /checkout/tests/ui/issues/issue-3702-2.rs:16:14
   |
   |
LL |         self.to_int() + other.to_int() //~ ERROR multiple applicable items in scope
   |              ^^^^^^ multiple `to_int` found
   |
note: candidate #1 is defined in an impl of the trait `ToPrimitive` for the type `isize`
   |
LL |     fn to_int(&self) -> isize { 0 }
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2 is defined in an impl of the trait `Add` for the type `isize`
   |
   |
LL |     fn to_int(&self) -> isize { *self }
help: disambiguate the method for candidate #1
   |
   |
LL |         ToPrimitive::to_int(&self) + other.to_int() //~ ERROR multiple applicable items in scope
help: disambiguate the method for candidate #2
   |
   |
LL |         Add::to_int(&) + other.to_int() //~ ERROR multiple applicable items in scope

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0034`.
---

20    |     ^^^^^^^^
21 help: disambiguate the associated function for candidate #1
22    |
- LL |     <Qux as Foo>::foo(Qux);
-    |     ~~~~~~~~~~~~~~~~~~~~~~
+ LL |     <Qux as Foo>::foo();
25 help: disambiguate the associated function for candidate #2
26    |
26    |
- LL |     <Qux as FooBar>::foo(Qux);
-    |     ~~~~~~~~~~~~~~~~~~~~~~~~~
+ LL |     <Qux as FooBar>::foo();
29 
30 error: aborting due to 1 previous error
31 

---
status: exit status: 1
command: RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/methods/method-ambiguity-no-rcvr.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/methods/method-amb [...]

2023-12-14 14:18 UTC, compiler-errors commented
r? fmease

2023-12-16 03:29 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7229497930/job/19700428486) [(plain)](https://github.com/rust-lang/rust/commit/108c5dd585d775e23311567ef3fad74566547189/checks/19700428486/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=Young-Flash
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_f37558d9-064b-414f-9f88-1554b4164873
GITHUB_EVENT_NAME=pull_request
GITHUB_EVENT_NAME=pull_request
GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
GITHUB_GRAPHQL_URL=https://api.github.com/graphql
GITHUB_HEAD_REF=fix_issue_118819
GITHUB_JOB=pr
GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_f37558d9-064b-414f-9f88-1554b4164873
GITHUB_REF=refs/pull/118911/merge
GITHUB_REF_NAME=118911/merge
GITHUB_REF_PROTECTED=false
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=b6198adcd33ac16b607577940d3cfb2905de526f
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_f37558d9-064b-414f-9f88-1554b4164873
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_f37558d9-064b-414f-9f88-1554b4164873
GITHUB_TRIGGERING_ACTOR=Young-Flash
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/118911/merge
GITHUB_WORKFLOW_SHA=b6198adcd33ac16b607577940d3cfb2905de526f
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.13/x64
---
Built container sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Looks like docker image is the same as before, not uploading
https://ci-caches.rust-lang.org/docker/7ebc15c01a233894034d277c8cce4e949f4e7791f66b4727c8fb6e058a0b8171d6152e1441d677cef0653843ceeee469c097b8699b2bb74249e674f6aa1a8813
sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-16]
##[group]Clock drift check
  local time: Sat Dec 16 03:25:56 UTC 2023
  network time: Sat, 16 Dec 2023 03:25:56 GMT
  network time: Sat, 16 Dec 2023 03:25:56 GMT
##[endgroup]
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-16', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-missing-tools', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-16/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: rust.codegen-units-std := 1
---
   Compiling rustc_privacy v0.0.0 (/checkout/compiler/rustc_privacy)
error[E0599]: no method named `find_by_def_id` found for struct `rustc_middle::hir::map::Map` in the current scope
    --> compiler/rustc_hir_typeck/src/method/suggest.rs:3357:61
     |
3357 |                         Some(local_def_id) => match hir_map.find_by_def_id(local_def_id) {
     |                                                             ^^^^^^^^^^^^^^ method not found in `Map<'_>`
For more information about this error, try `rustc --explain E0599`.
error: could not compile `rustc_hir_typeck` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
Build completed unsuccessfully in 0:02:17
```

</details>

2023-12-16 04:04 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7229633916/job/19700733263) [(plain)](https://github.com/rust-lang/rust/commit/3357d028fd1e9632df73869a53b4b6b2dce78b75/checks/19700733263/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=Young-Flash
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_c7cbda26-8cfb-4e84-a3f5-210989f8f373
GITHUB_EVENT_NAME=pull_request
GITHUB_EVENT_NAME=pull_request
GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
GITHUB_GRAPHQL_URL=https://api.github.com/graphql
GITHUB_HEAD_REF=fix_issue_118819
GITHUB_JOB=pr
GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_c7cbda26-8cfb-4e84-a3f5-210989f8f373
GITHUB_REF=refs/pull/118911/merge
GITHUB_REF_NAME=118911/merge
GITHUB_REF_PROTECTED=false
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=574433f82f8a5a76fe6f9d584a5c1d0574509406
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_c7cbda26-8cfb-4e84-a3f5-210989f8f373
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_c7cbda26-8cfb-4e84-a3f5-210989f8f373
GITHUB_TRIGGERING_ACTOR=Young-Flash
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/118911/merge
GITHUB_WORKFLOW_SHA=574433f82f8a5a76fe6f9d584a5c1d0574509406
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.13/x64
---
Built container sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Looks like docker image is the same as before, not uploading
https://ci-caches.rust-lang.org/docker/7ebc15c01a233894034d277c8cce4e949f4e7791f66b4727c8fb6e058a0b8171d6152e1441d677cef0653843ceeee469c097b8699b2bb74249e674f6aa1a8813
sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-16]
##[group]Clock drift check
  local time: Sat Dec 16 04:01:43 UTC 2023
  network time: Sat, 16 Dec 2023 04:01:43 GMT
  network time: Sat, 16 Dec 2023 04:01:43 GMT
##[endgroup]
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-16', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-missing-tools', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-16/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: rust.codegen-units-std := 1
---
   Compiling rustc_borrowck v0.0.0 (/checkout/compiler/rustc_borrowck)
error[E0599]: no method named `find_by_def_id` found for struct `rustc_middle::hir::map::Map` in the current scope
    --> compiler/rustc_hir_typeck/src/method/suggest.rs:3356:61
     |
3356 |                         Some(local_def_id) => match hir_map.find_by_def_id(local_def_id) {
     |                                                             ^^^^^^^^^^^^^^ method not found in `Map<'_>`
For more information about this error, try `rustc --explain E0599`.
error: could not compile `rustc_hir_typeck` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
Build completed unsuccessfully in 0:02:26
```

</details>

2023-12-16 04:16 UTC, Young-Flash commented
can't figure out why CI failed with the following, but it compile on my local. any hints? @fmease @compiler-errors 
```txt
error[E0599]: no method named `find_by_def_id` found for struct `rustc_middle::hir::map::Map` in the current scope
    --> compiler/rustc_hir_typeck/src/method/suggest.rs:3356:61
     |
3356 |                         Some(local_def_id) => match hir_map.find_by_def_id(local_def_id) {
     |                                                             ^^^^^^^^^^^^^^ method not found in `Map<'_>`
```

2023-12-21 13:13 UTC, fmease requested changes
Sorry for taking so long! I have some style nits and some suggestions. 

This diagnostic generally has quite a few false positives and negatives before and after your changes, so I guess it's not worth making it perfect. I have some suggestions like trying out `can_eq`. If you can't make it work, then that's fine, too.

2023-12-21 13:13 UTC, fmease commented on compiler/rustc_hir_typeck/src/method/suggest.rs
> +                .and_then(|first| Some(first.peel_refs()));
This makes sense but it's prone to errors:

```
trait A { fn f(self); }
trait B { fn f(self); }

#[derive(Clone, Copy)]
struct S;

impl A for S { fn f(self) {} }
impl B for S { fn f(self) {} }

fn main() {
    (&&&S).f(); // Here, we suggest `A::f((&&&S))` but we should suggest `A::f(***S)`
}

```

Doesn't need to be fixed in this PR just making note of it.

2023-12-21 13:13 UTC, fmease commented on compiler/rustc_hir_typeck/src/method/suggest.rs
> +                .and_then(|first| Some(first.peel_refs()));
```suggestion
                .map(|first| first.peel_refs());
```

2023-12-21 13:13 UTC, fmease commented on compiler/rustc_hir_typeck/src/method/suggest.rs
>                  .and_then(|ty| ty.ref_mutability())
The amount of references is not kept in sync between `first_arg_type` and `rcvr_ref` here:

```rs
trait A { fn f(self: &mut &Self); }
trait B { fn f(self: &mut &Self); }

struct S;

impl A for S { fn f(self: &mut &Self) {} }
impl B for S { fn f(self: &mut &Self) {} }

fn main() {
    (&mut &S).f(); // We suggest `A::f(&mut (&mut &S))` but it should be `A::f(&mut &S);`
}

```

2023-12-21 13:13 UTC, fmease commented on compiler/rustc_hir_typeck/src/method/suggest.rs
> +            let first_arg_type = tcx
Could you merge the two statements? Something like `let (first_arg_type, recv_ref) = …`? They share a lot.

2023-12-27 12:06 UTC, Young-Flash commented
sorry for the slow response and thank you for taking the time to review this. I make some modification and leave the rest for future work (so this PR could be focused), LMK if there are somethings can improve

2023-12-29 16:43 UTC, fmease approved these changes
Thanks, for implementing my feedback, it looks good! Further improvements can potentially be made in follow-up PRs.

2023-12-29 16:43 UTC, fmease commented
@bors r+ rollup

2023-12-29 20:37 UTC, merged

2023-12-29 23:39 UTC, rust-timer commented
Finished benchmarking commit (3cdd004e55c869faa2b7b25efd3becf50346e7d6): [comparison URL](https://perf.rust-lang.org/compare.html?start=29abb90bbf4472d8a3bc032a838b20a85f5ed1e7&end=3cdd004e55c869faa2b7b25efd3becf50346e7d6&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=29abb90bbf4472d8a3bc032a838b20a85f5ed1e7&end=3cdd004e55c869faa2b7b25efd3becf50346e7d6&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=29abb90bbf4472d8a3bc032a838b20a85f5ed1e7&end=3cdd004e55c869faa2b7b25efd3becf50346e7d6&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 3.0%  | [2.8%, 3.3%]   | 2     |
| Regressions ❌ <br /> (secondary)  | 2.3%  | [2.3%, 2.3%]   | 1     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -3.5% | [-3.9%, -3.2%] | 2     |
| All ❌✅ (primary)                 | 3.0%  | [2.8%, 3.3%]   | 2     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=29abb90bbf4472d8a3bc032a838b20a85f5ed1e7&end=3cdd004e55c869faa2b7b25efd3becf50346e7d6&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=29abb90bbf4472d8a3bc032a838b20a85f5ed1e7&end=3cdd004e55c869faa2b7b25efd3becf50346e7d6&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 669.249s -> 671.886s (0.39%)
**Artifact size**: 312.02 MiB -> 312.01 MiB (-0.00%)