Check generic params after sigature for main-fn-ty
rust-lang/rust pull request #119047
Opened 2023-12-17 12:20 UTC by mu001999

Fixes #118772

2023-12-17 15:21 UTC, compiler-errors requested changes

2023-12-17 15:21 UTC, compiler-errors commented on compiler/rustc_hir_analysis/src/check/entry.rs
>      );
Can you make `check_function_signature` (or better yet, `Result<(), ErrorGuaranteed>`, and then do an early-return if it had an error? We should only emit one error, ideally.

2023-12-18 14:25 UTC, mu001999 commented
@rustbot ready

2023-12-18 22:38 UTC, wesleywiser approved these changes

2023-12-18 22:38 UTC, wesleywiser commented
Thanks @mu001999!

@bors r+ rollup

2023-12-19 04:47 UTC, merged

2023-12-19 06:38 UTC, rust-timer commented
Finished benchmarking commit (e999d8b6e137c0393470a2d846047ee86c177719): [comparison URL](https://perf.rust-lang.org/compare.html?start=59096cdad0e527ce4d254b55aca58539f726d3d6&end=e999d8b6e137c0393470a2d846047ee86c177719&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=59096cdad0e527ce4d254b55aca58539f726d3d6&end=e999d8b6e137c0393470a2d846047ee86c177719&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=59096cdad0e527ce4d254b55aca58539f726d3d6&end=e999d8b6e137c0393470a2d846047ee86c177719&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -1.1% | [-1.7%, -0.4%] | 3     |
| Improvements ✅ <br /> (secondary) | -3.5% | [-3.5%, -3.5%] | 1     |
| All ❌✅ (primary)                 | -1.1% | [-1.7%, -0.4%] | 3     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=59096cdad0e527ce4d254b55aca58539f726d3d6&end=e999d8b6e137c0393470a2d846047ee86c177719&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -0.7% | [-0.7%, -0.7%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -0.7% | [-0.7%, -0.7%] | 1     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=59096cdad0e527ce4d254b55aca58539f726d3d6&end=e999d8b6e137c0393470a2d846047ee86c177719&stat=size:linked_artifact)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -0.4% | [-0.4%, -0.4%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -0.4% | [-0.4%, -0.4%] | 1     |
</details>

**Bootstrap**: 672.298s -> 672.871s (0.09%)
**Artifact size**: 312.49 MiB -> 312.47 MiB (-0.01%)