fix: improve error messaging for unreachable loop return cases
rust-lang/rust pull request #119178
Opened 2023-12-21 08:38 UTC by yossydev

Check to see if the pattern is single binding, and if so, display a better error message!

ref: https://github.com/rust-lang/rust/issues/116572

2023-12-21 08:43 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7285841049/job/19853453032) [(plain)](https://github.com/rust-lang/rust/commit/369933aa120ee271e4188d42d9768ae4cc269d1a/checks/19853453032/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=yossydev
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_f5d2938c-41aa-41ac-b945-e94d5b6b44d3
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=991bacfae692dd873dfeda5cc943931c8abebfba
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_f5d2938c-41aa-41ac-b945-e94d5b6b44d3
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_f5d2938c-41aa-41ac-b945-e94d5b6b44d3
GITHUB_TRIGGERING_ACTOR=yossydev
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/119178/merge
GITHUB_WORKFLOW_SHA=991bacfae692dd873dfeda5cc943931c8abebfba
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.13/x64
---
    Checking rustc_hir_typeck v0.0.0 (/checkout/compiler/rustc_hir_typeck)
error[E0433]: failed to resolve: could not find `exprkind` in `hir`
    --> compiler/rustc_hir_typeck/src/coercion.rs:1675:25
     |
1675 |             && let hir::exprkind::block(block, _) = hir.body(body_id).value.kind
     |                         |
     |                         could not find `exprkind` in `hir`
     |                         help: an enum with a similar name exists: `ExprKind`


error[E0433]: failed to resolve: could not find `stmtkind` in `hir`
     |
     |
1679 |                 if let hir::stmtkind::local(local) = stmt.kind {
     |                             |
     |                             |
     |                             could not find `stmtkind` in `hir`
     |                             help: an enum with a similar name exists (notice the capitalization): `StmtKind`
error[E0433]: failed to resolve: could not find `patkind` in `hir`
    --> compiler/rustc_hir_typeck/src/coercion.rs:1680:33
     |
     |
1680 |                     if let hir::patkind::binding(_, _, _, none) = local.pat.kind {
     |                                 |
     |                                 could not find `patkind` in `hir`
     |                                 help: an enum with a similar name exists: `PatKind`


error[E0531]: cannot find tuple struct or tuple variant `some` in this scope
    --> compiler/rustc_hir_typeck/src/coercion.rs:1672:16
     |
1672 |         if let some(node) = tcx.opt_hir_node(item.into())
     |                ^^^^ help: a tuple variant with a similar name exists (notice the capitalization): `Some`
    ::: /checkout/library/core/src/option.rs:578:5
     |
578  |     Some(#[stable(feature = "rust1", since = "1.0.0")] T),
     |     ---- similarly named tuple variant `Some` defined here
     |     ---- similarly named tuple variant `Some` defined here

error[E0531]: cannot find tuple struct or tuple variant `some` in this scope
    --> compiler/rustc_hir_typeck/src/coercion.rs:1673:20
     |
1673 |             && let some(body_id) = node.body_id()
     |                    ^^^^ help: a tuple variant with a similar name exists (notice the capitalization): `Some`
    ::: /checkout/library/core/src/option.rs:578:5
     |
578  |     Some(#[stable(feature = "rust1", since = "1.0.0")] T),
     |     ---- similarly named tuple variant `Some` defined here
     |     ---- similarly named tuple variant `Some` defined here

error[E0531]: cannot find tuple struct or tuple variant `some` in this scope
    --> compiler/rustc_hir_typeck/src/coercion.rs:1674:20
     |
1674 |             && let some(sig) = node.fn_sig()
     |                    ^^^^ help: a tuple variant with a similar name exists (notice the capitalization): `Some`
    ::: /checkout/library/core/src/option.rs:578:5
     |
578  |     Some(#[stable(feature = "rust1", since = "1.0.0")] T),
     |     ---- similarly named tuple variant `Some` defined here
     |     ---- similarly named tuple variant `Some` defined here

error[E0425]: cannot find value `loop_span` in this scope
     |
     |
1689 |         let mut span: MultiSpan = vec![loop_span].into();


error[E0425]: cannot find value `loop_span` in this scope
     |
     |
1690 |         span.push_span_label(loop_span, "this might have zero elements to iterate on");

    Checking rustc_ty_utils v0.0.0 (/checkout/compiler/rustc_ty_utils)
Some errors have detailed explanations: E0425, E0433, E0531.
For more information about an error, try `rustc --explain E0425`.
```

</details>

2023-12-21 08:52 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7285918097/job/19853676625) [(plain)](https://github.com/rust-lang/rust/commit/cd4f745f76bef5c0d4f6ae03acf0d63f261ae520/checks/19853676625/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=yossydev
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_81d57f62-6a07-422e-a374-204f405a7364
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=a054eb96aee74de9c04d732862d94816df855e9b
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_81d57f62-6a07-422e-a374-204f405a7364
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_81d57f62-6a07-422e-a374-204f405a7364
GITHUB_TRIGGERING_ACTOR=yossydev
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/119178/merge
GITHUB_WORKFLOW_SHA=a054eb96aee74de9c04d732862d94816df855e9b
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.13/x64
---
    Checking rustc_ty_utils v0.0.0 (/checkout/compiler/rustc_ty_utils)
    Checking rustc_hir_typeck v0.0.0 (/checkout/compiler/rustc_hir_typeck)
    Checking rustc_passes v0.0.0 (/checkout/compiler/rustc_passes)
    Checking rustc_mir_transform v0.0.0 (/checkout/compiler/rustc_mir_transform)
error[E0425]: cannot find value `loop_span` in this scope
     |
     |
1689 |         let mut span: MultiSpan = vec![loop_span].into();


error[E0425]: cannot find value `loop_span` in this scope
     |
     |
1690 |         span.push_span_label(loop_span, "this might have zero elements to iterate on");

For more information about this error, try `rustc --explain E0425`.
error: could not compile `rustc_hir_typeck` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

</details>

2023-12-21 10:26 UTC, yossydev commented
@rustbot review

2024-01-02 08:02 UTC, yossydev commented
@rustbot review

2024-01-26 02:26 UTC, fmease commented
Could you please add a test for this in `tests/ui`?

2024-01-26 02:26 UTC, fmease requested changes
Could you please add a test for this in `tests/ui`?

2024-01-29 05:22 UTC, yossydev commented
> Could you please add a test for this in `tests/ui`?

ok!

2024-02-05 23:50 UTC, fmease commented
r? fmease

2024-02-22 09:42 UTC, yossydev commented
@Dylan-DPC 

> any updates on adding the test? thanks

We are currently making it! Is it possible to wait a little longer...?

2024-02-22 15:07 UTC, Dylan-DPC commented
@yossydev sure take your time, just wanted to check if you were still working on it or if there some issue that we can help resolve. Thanks

2024-04-19 05:28 UTC, fmease commented
@yossydev I'd say enough time has passed, I'll close this PR due to inactivity.

Feel to free to open a new PR once you find the time to work on this again. You can also ping me if and before you'd like to push your changes to this PR since I think I need to reopen it for you (?).

Note that the next time around it would be great if you could some sort of UI test as well as a short explainer how the changes related to issue #116572 (if it works towards fixing it, if it fixes it completely, ...). You can consult the [rustc dev guide](https://rustc-dev-guide.rust-lang.org/) on writing UI tests and other questions.

2024-04-19 05:28 UTC, closed without merging