[rustdoc] Add `is_object_safe` information for traits in JSON output
rust-lang/rust pull request #119246
Opened 2023-12-23 10:45 UTC by GuillaumeGomez

As asked by @obi1kenobi [here](https://github.com/rust-lang/rust/pull/113241#issuecomment-1868213677).

cc @aDotInTheVoid 
r? @notriddle

2023-12-23 10:58 UTC, aDotInTheVoid requested changes
r? @aDotInTheVoid 

r=me with assertions fixed

2023-12-23 11:04 UTC, aDotInTheVoid commented on tests/rustdoc-json/traits/is_object_safe.rs
> +// @has "$.index[*][?(@.name=='FooUnsafe')].inner.trait.is_object_safe" false
```suggestion
// @is "$.index[*][?(@.name=='FooUnsafe')].inner.trait.is_object_safe" false
```

That way you get a better error message from jsondocck, (and also means this test will fail if this ever somehow mathces to `[true, false]`).

The top assert is redundant, but it's fine to keep or remove at your discression,

2023-12-23 18:00 UTC, GuillaumeGomez commented
@notriddle Noted!

@bors r=aDotInTheVoid rollup

2023-12-23 19:41 UTC, aDotInTheVoid commented
I’m not on review rotation, but am happy to review rustdoc-json stuff.

(is their a way to tell high-five to only assign me these PR’s, or should i rely on the ping, and then r ? myself?)

2023-12-23 22:37 UTC, merged

2023-12-24 10:53 UTC, GuillaumeGomez commented
There is a way, but since it's part of rustdoc, I'm not sure it's a good idea to have different handlings for subparts. In any case you're pinged normally so even though it's more of a hassle, you can self-assign when pinged.