Uplift `clippy::invalid_null_ptr_usage` lint
rust-lang/rust pull request #119220
Opened 2023-12-22 15:33 UTC by Urgau

This PR aims at uplifting the `clippy::invalid_null_ptr_usage` lint into rustc, this is similar to the [`clippy::invalid_utf8_in_unchecked` uplifted](https://github.com/rust-lang/rust/pull/111543) a few months ago, in the sense that those two lints lint on invalid parameter(s), here a null-ptr where is unexpected and UB to pass one.

*For context: GitHub Search reveals that just for `slice::from_raw_parts` [12 invalid usages](https://github.com/search?q=lang%3Arust+%2Fslice%3A%3Afrom_raw_parts%5C%28ptr%3A%3Anull%2F+NOT+path%3A%2F%5Eclippy_lints%5C%2Fsrc%5C%2F%2F+NOT+path%3A%2F%5Erust%5C%2Fsrc%5C%2Ftools%5C%2Fclippy%5C%2Fclippy_lints%5C%2Fsrc%5C%2F%2F+NOT+path%3A%2F%5Esrc%5C%2Ftools%5C%2Fclippy%5C%2Fclippy_lints%5C%2Fsrc%5C%2F%2F&type=code) with `ptr::null` and an additional [4 invalid usages](https://github.com/search?q=lang%3Arust+%2Fslice%3A%3Afrom_raw_parts%5C%280%28%5C%29%7C+as%29%2F+NOT+path%3A%2F%5Eclippy_lints%5C%2Fsrc%5C%2F%2F+NOT+path%3A%2F%5Erust%5C%2Fsrc%5C%2Ftools%5C%2Fclippy%5C%2Fclippy_lints%5C%2Fsrc%5C%2F%2F+NOT+path%3A%2F%5Esrc%5C%2Ftools%5C%2Fclippy%5C%2Fclippy_lints%5C%2Fsrc%5C%2F%2F+NOT+path%3A%2F%5Eutils%5C%2Ftinystr%5C%2Fsrc%5C%2F%2F+NOT+path%3A%2F%5Eutils%5C%2Fzerovec%5C%2Fsrc%5C%2F%2F+NOT+path%3A%2F%5Eprovider%5C%2Fcore%5C%2Fsrc%5C%2F%2F&type=code) with `0 as *const ...`-ish casts.*

-----

## `invalid_null_ptr_usages`

(deny-by-default)

The `invalid_null_ptr_usages` lint checks for invalid usage of null pointers.

### Example

```rust
// Undefined behavior
unsafe { std::slice::from_raw_parts(ptr::null(), 0); }
// Not Undefined behavior
unsafe { std::slice::from_raw_parts(NonNull::dangling().as_ptr(), 0); }
```

Produces:
```
error: calling this function with a null pointer is undefined behavior, even if the result of the function is unused, consider using a dangling pointer instead
  --> $DIR/invalid_null_ptr_usages.rs:14:23
   |
LL |     let _: &[usize] = std::slice::from_raw_parts(ptr::null(), 0);
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^-----------^^^^
   |                                                  |
   |                                                  help: use a dangling pointer instead: `core::ptr::NonNull::dangling().as_ptr()`
```

### Explanation

Calling methods who's safety invariants requires non-null pointer with a null pointer is undefined behavior.

-----

The lint use a list of functions to know which functions and arguments to checks, this could be improved in the future with a rustc attribute.

This PR also includes some small refactoring to avoid some ambiguities in naming, those can be done in another PR is desired.

@rustbot label: +I-lang-nominated
r? compiler

2023-12-22 16:04 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7301494558/job/19898239924) [(plain)](https://github.com/rust-lang/rust/commit/c8b6b1ca3f1c03539523a97264189a9028a162a2/checks/19898239924/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=Urgau
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_fe01035f-44c1-476e-b023-7d36df0165f6
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=994b06aa4a6be6197503a4bc54d6219d008be33c
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_fe01035f-44c1-476e-b023-7d36df0165f6
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_fe01035f-44c1-476e-b023-7d36df0165f6
GITHUB_TRIGGERING_ACTOR=Urgau
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/119220/merge
GITHUB_WORKFLOW_SHA=994b06aa4a6be6197503a4bc54d6219d008be33c
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.13/x64
---
Built container sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Looks like docker image is the same as before, not uploading
https://ci-caches.rust-lang.org/docker/7ebc15c01a233894034d277c8cce4e949f4e7791f66b4727c8fb6e058a0b8171d6152e1441d677cef0653843ceeee469c097b8699b2bb74249e674f6aa1a8813
sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-16]
##[group]Clock drift check
  local time: Fri Dec 22 15:35:52 UTC 2023
  network time: Fri, 22 Dec 2023 15:35:52 GMT
  network time: Fri, 22 Dec 2023 15:35:52 GMT
##[endgroup]
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-16', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-missing-tools', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-16/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: rust.codegen-units-std := 1
---
##[endgroup]
Testing GCC stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling y v0.1.0 (/checkout/compiler/rustc_codegen_gcc/build_system)
    Finished release [optimized] target(s) in 1.41s
     Running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-codegen/x86_64-unknown-linux-gnu/release/y test --use-system-gcc --use-backend gcc --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc --release --no-default-features --mini-tests --std-tests`
Using system GCC
Using system GCC
[BUILD] example
[AOT] mini_core_hello_world
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc/mini_core_hello_world
abc
---
---- compiler/rustc_lint/src/ptr_nulls.rs - ptr_nulls::INVALID_NULL_PTR_USAGES (line 41) stdout ----
error[E0433]: failed to resolve: use of undeclared crate or module `ptr`
##[error] --> compiler/rustc_lint/src/ptr_nulls.rs:43:37
  |
4 | unsafe { std::slice::from_raw_parts(ptr::null(), 0); }
  |                                     ^^^ use of undeclared crate or module `ptr`
help: a builtin type with a similar name exists
  |
4 | unsafe { std::slice::from_raw_parts(str::null(), 0); }
  |                                     ~~~
---
    compiler/rustc_lint/src/ptr_nulls.rs - ptr_nulls::INVALID_NULL_PTR_USAGES (line 41)

test result: FAILED. 84 passed; 1 failed; 2 ignored; 0 measured; 0 filtered out; finished in 863.37ms

error: doctest failed, to rerun pass `-p rustc_lint --doc`
  local time: Fri Dec 22 16:04:14 UTC 2023
  network time: Fri, 22 Dec 2023 16:04:14 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2023-12-22 16:38 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7301761363/job/19899091625) [(plain)](https://github.com/rust-lang/rust/commit/730841908e23349af64c2395700aff142eee1d5d/checks/19899091625/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=Urgau
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_d409d87d-5e85-4ed8-85d9-e834183ec85a
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=efae6d65cf4258e83f307f1c865a233b3a21c89e
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_d409d87d-5e85-4ed8-85d9-e834183ec85a
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_d409d87d-5e85-4ed8-85d9-e834183ec85a
GITHUB_TRIGGERING_ACTOR=Urgau
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/119220/merge
GITHUB_WORKFLOW_SHA=efae6d65cf4258e83f307f1c865a233b3a21c89e
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.13/x64
---
Built container sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Looks like docker image is the same as before, not uploading
https://ci-caches.rust-lang.org/docker/7ebc15c01a233894034d277c8cce4e949f4e7791f66b4727c8fb6e058a0b8171d6152e1441d677cef0653843ceeee469c097b8699b2bb74249e674f6aa1a8813
sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-16]
##[group]Clock drift check
  local time: Fri Dec 22 16:10:05 UTC 2023
  network time: Fri, 22 Dec 2023 16:10:05 GMT
  network time: Fri, 22 Dec 2023 16:10:05 GMT
##[endgroup]
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-16', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-missing-tools', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-16/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: rust.codegen-units-std := 1
---
##[endgroup]
Testing GCC stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling y v0.1.0 (/checkout/compiler/rustc_codegen_gcc/build_system)
    Finished release [optimized] target(s) in 1.43s
     Running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-codegen/x86_64-unknown-linux-gnu/release/y test --use-system-gcc --use-backend gcc --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc --release --no-default-features --mini-tests --std-tests`
Using system GCC
Using system GCC
[BUILD] example
[AOT] mini_core_hello_world
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc/mini_core_hello_world
abc
---

failures:

---- compiler/rustc_lint/src/ptr_nulls.rs - ptr_nulls::INVALID_NULL_PTR_USAGES (line 41) stdout ----
error: calling this function with a null pointer is undefined behavior, even if the result of the function is unused, consider using a dangling pointer instead
  |
  |
6 | unsafe { slice::from_raw_parts(ptr::null(), 0) };
  |                                |
  |                                help: use a dangling pointer instead: `core::ptr::NonNull::dangling().as_ptr()`
  |
  = note: `#[deny(invalid_null_ptr_usages)]` on by default
---
    compiler/rustc_lint/src/ptr_nulls.rs - ptr_nulls::INVALID_NULL_PTR_USAGES (line 41)

test result: FAILED. 84 passed; 1 failed; 2 ignored; 0 measured; 0 filtered out; finished in 854.02ms

error: doctest failed, to rerun pass `-p rustc_lint --doc`
  local time: Fri Dec 22 16:38:17 UTC 2023
  network time: Fri, 22 Dec 2023 16:38:17 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2023-12-22 17:13 UTC, Nilstrieb commented
I think @saethlin has also found plenty of code that hits this in the wild, so this seems like a good lint.

2023-12-22 18:21 UTC, saethlin commented
You're probably referring to https://github.com/PyO3/pyo3/pull/2687 and https://github.com/servo/font-kit/pull/197

I don't think either of these would be detected by the lint, but I agree that this is a reasonable lint target.

2024-02-01 13:43 UTC, apiraino commented
I'll flag this as `S-waiting-on-team` to signal that T-lang nomination

2024-06-26 06:52 UTC, Centri3 commented
That feels similar to what flux and verus are doing but at a smaller scale. Unsure about allowing downstream users to access it but it'd be great to make these kinds of checks more prevalent (and not just for ull ptr cases)

2024-06-26 07:44 UTC, Centri3 commented
I do like refinement types. We should discuss this further, I love the idea of rust expanding its sights of correctness to this

2024-06-28 08:19 UTC, Urgau commented
I would if there was an easier way to add those kind of lints. Using the `diagnostics` namespace is also something I alluded in my top comment, and I think that it's something that should probably be pushed forward, the only thing that is a bit weird is that I had the impression that the `diagnostics` attribute would not by it-self create a diagnostic but is only here to accompany one.

> It'd be great if, rather than lang needing to approve stuff, it'd just be `T-libs` PR approving a `#[diagnostics::ub_if(ptr.is_null())]` or something like that.

That would be awesome, I would love if it were this "simple".

I can write something akin to an MCP (for t-lang) but I don't have the time for a full RFC :-)

2024-08-05 06:11 UTC, jieyouxu commented
> It'd be great if, rather than lang needing to approve stuff, it'd just be `T-libs` PR approving a `#[diagnostics::ub_if(ptr.is_null())]` or something like that. And eventually we could stabilize that to let crates use them too, to get built-in lints on stuff without needing rustc or clippy needing to know that the random crates even need to know exist.

> Using the diagnostics namespace is also something I alluded in my top comment, and I think that it's something that should probably be pushed forward

<details>
<summary>
Just a remark: note that there is currently a limitation on the compiler side with attribute handling of "namespaced attributes" and abitrary inner expressions within attributes.
</summary>

In particular, we don't currently have support for arbitrary inner expressions (we can probably teach the compiler about arbitrary inner expressions but would need to be very careful about the grammar):

- we *do* currently have support for arbitrary expressions in the form of `#[name = expr]`
- but not `#[name(expr)]` AFAIK
- we certainly do not currently have support for `#[namespace::name(expr)]` where `expr` is not just a literal or other primitive.

</details>

(Purely FYI, not intended to derail this PR)

2025-03-06 17:48 UTC, traviscross commented
Thanks @Urgau for the ping on this one.  Looking at this now carefully, we should move this one forward.  I propose:

@rfcbot fcp merge

And I think this is probably a clear call for us, so let's collect checkboxes in the next meeting if it's still outstanding:

@rustbot labels +I-lang-easy-decision

2025-03-06 17:49 UTC, traviscross commented
Thanks @Urgau for the ping on this one.  Looking at this now carefully, we should move this one forward.  I propose:

@rfcbot fcp merge

And I think this is probably a clear call for us, so let's collect checkboxes in the next meeting if it's still outstanding:

@rustbot labels +I-lang-easy-decision

2025-03-07 06:59 UTC, traviscross commented
Anyone have a better suggestion for the lint name than `invalid_null_ptr_usages`?  I think it's the word "usages" that I want rid of somehow.

2025-03-07 07:09 UTC, traviscross commented
@rfcbot concern name

We have one existing stable lint that refers to null pointers, and it's named `deref_nullptr`.  So it seems we'd at least either want to change this to `nullptr` rather than `null_ptr` to match, or explicitly discuss and accept the inconsistency for some reason.

Maybe `invalid_nullptr_args`?

2025-03-07 11:52 UTC, joshtriplett commented
We could just write `null` (because `null` is always a pointer, if it weren't a pointer it would be `0`/`zero`). Clippy has only one lint name with `null_ptr` in it, and several lint names that just use `null` (`cmp_null`, `transmute_null_to_fn`, `transmuting_null`).

Also, in rustc lint names, we seem to consistently spell out `argument` (though we're inconsistent about `param` vs `parameter`). We have, for instance, [`invalid_macro_export_arguments`](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#invalid-macro-export-arguments) and [`named_arguments_used_positionally`](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#named-arguments-used-positionally), but nothing with `arg`.

Thus, for consistency, I would propose `invalid_null_argument`.

2025-03-07 18:03 UTC, Urgau commented
Happy to switch to `invalid_null_arguments`[^1].

[^1]: Added an `s` at the end per https://rustc-dev-guide.rust-lang.org/diagnostics.html#lint-naming

2025-03-08 05:10 UTC, traviscross commented
Works for me.  Let's do `invalid_null_arguments`.

@rfcbot resolve name

2025-03-09 20:30 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/13751977818/job/38454090209) [(plain)](https://github.com/rust-lang/rust/commit/087d698f2c6f02ff76b9daf6a3b213ea43f5f3d2/checks/38454090209/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#20 exporting to docker image format
#20 sending tarball 19.9s done
#20 DONE 25.1s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Listening on address 127.0.0.1:4226
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
  Number of decisions:   4447
  longest path:          1159 (code:    152)
  longest backtrack:       66 (code:    428)
Shared 86733 out of 152951 states by creating 14756 new states, saving 71977
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/expmed.cc: In function ‘rtx_def* extract_bit_field_1(rtx, poly_uint64, poly_uint64, int, rtx, machine_mode, machine_mode, bool, bool, rtx_def**)’:
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/expmed.cc:1864:45: warning: ‘*(unsigned int*)((char*)&imode + offsetof(scalar_int_mode, scalar_int_mode::m_mode))’ may be used uninitialized [-Wmaybe-uninitialized]
 1864 |       rtx sub = extract_bit_field_as_subreg (mode1, op0, imode,
 1865 |                                              bitsize, bitnum);
      |                                              ~~~~~~~~~~~~~~~~
      |                                              ~~~~~~~~~~~~~~~~
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/expmed.cc:1824:19: note: ‘*(unsigned int*)((char*)&imode + offsetof(scalar_int_mode, scalar_int_mode::m_mode))’ was declared here
 1824 |   scalar_int_mode imode;
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-everything’ may have been intended to silence earlier diagnostics
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/gimple-range-gori.cc: In member function ‘void range_def_chain::dump(FILE*, basic_block, const char*)’:
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/gimple-range-gori.cc:319:19: warning: format not a string literal and no format arguments [-Wformat-security]
---
      |                         ^
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-everything’ may have been intended to silence earlier diagnostics
In file included from /checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/libgccjit.cc:30:
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/jit-recording.h: In member function ‘virtual bool gcc::jit::recording::type::is_same_type_as(gcc::jit::recording::type*)’:
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/jit-recording.h:640:20: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
      |          ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/libgccjit.cc: In function ‘gcc_jit_type* gcc_jit_context_new_array_type(gcc_jit_context*, gcc_jit_location*, gcc_jit_type*, long unsigned int)’:
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/libgccjit.cc:807:37: warning: comparison of unsigned expression in ‘>= 0’ is always true [-Wtype-limits]
  807 |   RETURN_NULL_IF_FAIL (num_elements >= 0, ctxt, NULL, "negative size");
---
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-everything’ may have been intended to silence earlier diagnostics
In file included from /checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/jit-playback.h:31,
                 from /checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/dummy-frontend.cc:25:
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/jit-recording.h: In member function ‘virtual bool gcc::jit::recording::type::is_same_type_as(gcc::jit::recording::type*)’:
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/jit-recording.h:640:20: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
      |          ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-everything’ may have been intended to silence earlier diagnostics
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/../libgcc/libgcov-util.c: In function ‘gcov_info* gcov_read_profile_dir(const char*, int)’:
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/../libgcc/libgcov-util.c: In function ‘gcov_info* gcov_read_profile_dir(const char*, int)’:
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/../libgcc/libgcov-util.c:456:9: warning: ignoring return value of ‘int chdir(const char*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  456 |   chdir (pwd);
      |   ~~~~~~^~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-everything’ may have been intended to silence earlier diagnostics
In file included from /checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/jit-playback.h:31,
                 from /checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/jit-playback.cc:49:
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/jit-recording.h: In member function ‘virtual bool gcc::jit::recording::type::is_same_type_as(gcc::jit::recording::type*)’:
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/jit-recording.h:640:20: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
      |          ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-everything’ may have been intended to silence earlier diagnostics
In file included from /checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/jit-playback.h:31,
In file included from /checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/jit-playback.h:31,
                 from /checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/jit-builtins.cc:24:
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/jit-recording.h: In member function ‘virtual bool gcc::jit::recording::type::is_same_type_as(gcc::jit::recording::type*)’:
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/jit-recording.h:640:20: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
      |          ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/omp-builtins.def: At global scope:
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/omp-builtins.def: At global scope:
./options.h:6899:37: warning: narrowing conversion of ‘global_options.gcc_options::x_flag_openacc’ from ‘int’ to ‘bool’ [-Wnarrowing]
 6899 | #define flag_openacc global_options.x_flag_openacc
/checkout/obj/build/x86_64-unknown-linux-gnu/gcc/src/gcc/jit/jit-builtins.cc:58:23: note: in definition of macro ‘DEF_BUILTIN’
/ [...]

2025-03-09 22:47 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/13752999128/job/38456359251) [(plain)](https://github.com/rust-lang/rust/commit/b36fb5a1890571a28a60a0f6adf25c4b81d82e06/checks/38456359251/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
tests/pass/float_nan.rs ... ok
tests/pass/0weak_memory_consistency_sc.rs ... ok

FAILED TEST: tests/pass/shims/windows-threadname.rs
command: MIRI_ENV_VAR_TEST="0" MIRI_TEMP="/tmp/miri-uitest-YZHunj" RUST_BACKTRACE="1" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/miri" "--error-format=json" "--sysroot=/checkout/obj/build/x86_64-unknown-linux-gnu/miri-sysroot" "-Dwarnings" "-Dunused" "-Ainternal_features" "-Zui-testing" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/miri_ui/0/tests/pass/shims" "tests/pass/shims/windows-threadname.rs" "--edition" "2021" "--target" "i686-pc-windows-msvc"

error: test got exit status: 1, but expected 0
 = note: compilation failed, but was expected to succeed

error: actual output differed from expected
---

Location:
   /cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ui_test-0.28.0/src/lib.rs:369

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
error: test failed, to rerun pass `--test ui`

Caused by:
  process didn't exit successfully: `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/ui-9d7bd8a6b4242d84 --quiet` (exit status: 1)
Command has failed. Rerun with -v to see more details.
Build completed unsuccessfully in 0:01:15
  local time: Sun Mar  9 22:47:32 UTC 2025
  network time: Sun, 09 Mar 2025 22:47:32 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2025-03-18 05:29 UTC, saethlin commented on compiler/rustc_lint/messages.ftl
> +    .suggestion = consider using a dangling pointer instead
`ptr::null()` returns a dangling pointer, so this wording is ill-formed.

I'm not sure there is a useful suggestion to make, perhaps if you have surveyed sites this current warns and concluded that `ptr::dangling()` would be _correct_ (as opposed to just getting past the type checker), then it would be appropriate to say `ptr::dangling()`.

2025-03-18 05:29 UTC, saethlin commented on compiler/rustc_lint/messages.ftl
> +    .note = null pointer originate from here
```suggestion
    .note = null pointer originates from here
```

2025-03-18 18:48 UTC, Urgau commented on compiler/rustc_lint/messages.ftl
> +    .suggestion = consider using a dangling pointer instead
I looked more closely at the GitHub search and I think you're right, recommending a dangling ptr (from `ptr::dangling()`, not `ptr::null()`) seems ill-advised in many cases.

I've removed the suggestion and redirected users to our documentation on [pointers](https://doc.rust-lang.org/std/ptr/index.html) instead.

2025-03-30 04:10 UTC, fee1-dead requested changes
Sorry for the review being later than I expected.

2025-03-30 04:10 UTC, fee1-dead commented on compiler/rustc_lint/src/ptr_nulls.rs
> +                        // ZST are fine, don't lint on them
Are they though? At least for `slice_from_raw_parts` even ZSTs should be linted. I suppose you can make the match above also return a boolean about ZSTs?

2025-03-30 04:10 UTC, fee1-dead commented on compiler/rustc_lint/src/ptr_nulls.rs
> +                // maybe if we checked for null ptr first, it would be acceptable?
I think it is fine to hardcode the different diagnostic items as a start here, though in the future we might want to do something like `#[rustc_must_be_non_null(data, except_zst = true)]` where `data` is the name of the argument or something. Though I think with all these moving parts it might just be overall better to keep everything hardcoded here

2025-03-30 04:10 UTC, fee1-dead commented on tests/ui/lint/invalid_null_args.rs
> +}
add a case for `slice::from_raw_parts` here

2025-03-30 11:00 UTC, Urgau commented on compiler/rustc_lint/messages.ftl
> +    .doc = for more information, visit <https://doc.rust-lang.org/std/ptr/index.html>
Sure, added.

2025-03-30 11:01 UTC, Urgau commented on compiler/rustc_lint/src/ptr_nulls.rs
> +                        // ZST are fine, don't lint on them
Good call about `slice::from_raw_parts{,_mut}`, I re-checked all of them and I think it's the only one who doesn't accept null ptr and ZST. Fixed

2025-03-30 14:54 UTC, fee1-dead requested changes
nice, I had a few final nits and this should be good to go afterwards

2025-03-30 14:54 UTC, fee1-dead commented on compiler/rustc_lint/src/ptr_nulls.rs
> +                };
Too many lines here ^^' I suggest the following

```suggestion
                let (arg_indices, are_zsts_allowed) = match diag_name {
                    sym::ptr_read
                    | sym::ptr_read_unaligned
                    | sym::ptr_read_volatile
                    | sym::ptr_replace
                    | sym::ptr_write
                    | sym::ptr_write_bytes
                    | sym::ptr_write_unaligned
                    | sym::ptr_write_volatile => ([0], true),
                    sym::slice_from_raw_parts
                    | sym::slice_from_raw_parts_mut => ([0], false),
                    sym::ptr_copy
                    | sym::ptr_copy_nonoverlapping
                    | sym::ptr_swap
                    | sym::ptr_swap_nonoverlapping => ([0, 1], true),
                    _ => return,
                };
```

2025-03-30 14:54 UTC, fee1-dead commented on tests/ui/lint/invalid_null_args.stderr
> +   = help: for more information, visit <https://doc.rust-lang.org/std/ptr/index.html> and <https://doc.rust-lang.org/reference/behavior-considered-undefined.html>
For a diagnostic like this (`null_span = None`), can we still attach an inline label to the specific argument that is null? That should provide more clarity

2025-03-30 14:54 UTC, fee1-dead commented on tests/ui/lint/invalid_null_args.stderr
> +error: calling this function with a null pointer is Undefined Behavior, even if the result of the function is unused
```suggestion
error: it is undefined behavior to call this function with a null pointer, even if the result of the function is unused
```

We already have a diagnostic that says "it is undefined behavior to use this value", so making this follow that format feels nicer to me. Also we don't capitalize UB in diagnostics so we should follow that: https://github.com/search?q=repo%3Arust-lang%2Frust+undefined+behavior+path%3Atests%2Fui&type=code

2025-03-30 14:54 UTC, fee1-dead commented on tests/ui/lint/invalid_null_args.rs
> +    struct A; // zero-sized type
This `A` is confusingly named the same as a non-zst in the test case above. I had some pause reading this test because of that. Cheap to just rename it now.

```suggestion
    struct Zst; // zero-sized type
```

2025-03-30 16:15 UTC, Urgau commented on compiler/rustc_lint/src/ptr_nulls.rs
> +                };
I actually prefer the two distinct `match`, but not strongly changed to your suggested style.

2025-03-30 16:16 UTC, Urgau commented on tests/ui/lint/invalid_null_args.stderr
> +   = help: for more information, visit <https://doc.rust-lang.org/std/ptr/index.html> and <https://doc.rust-lang.org/reference/behavior-considered-undefined.html>
Indeed, having a label in those case is better. Done.

2025-03-30 16:21 UTC, Urgau commented on tests/ui/lint/invalid_null_args.stderr
> +error: calling this function with a null pointer is Undefined Behavior, even if the result of the function is unused
We also [have](https://github.com/rust-lang/rust/blob/45b40a75966b36d3588f173441896fddad01cd80/tests/ui/lint/reference_casting.stderr) [diagnostics](https://github.com/rust-lang/rust/blob/45b40a75966b36d3588f173441896fddad01cd80/tests/ui/lint/invalid_from_utf8.stderr) of the form I used.

As for `Undefined Behavior` being capitalized I took this style from miri in [their diagnostics](https://github.com/search?q=repo%3Arust-lang%2Frust+undefined+behavior+path%3Asrc%2Ftools%2Fmiri%2Ftests&type=code).

2025-03-30 16:48 UTC, fee1-dead commented on tests/ui/lint/invalid_null_args.stderr
> +error: calling this function with a null pointer is Undefined Behavior, even if the result of the function is unused
Keeping the form you used is fine, I'd still want it to not be capitalized. This is a rustc lint so it should follow what rustc uses. (We really should have a large whole-project discussion on this though, just to see if we may find a consensus)

2025-03-30 16:50 UTC, fee1-dead commented
r=me after the diagnostic is recapitalized to `undefined behavior`

2025-03-30 18:44 UTC, Urgau commented
@bors r=@fee1-dead

2025-03-31 01:48 UTC, traviscross commented on tests/ui/lint/invalid_null_args.stderr
> +error: calling this function with a null pointer is Undefined Behavior, even if the result of the function is unused
I think I convinced RalfJ that "undefined behavior" should not be capitalized (just as we don't capitalize "race condition") -- and he later [updated the Reference](https://github.com/rust-lang/reference/pull/1575) accordingly -- but prior to that, he had capitalized it in a lot of places (like Miri), and those haven't all been updated yet.

As a stylistic matter in the Reference, we write "undefined behavior".  I push the text in lang RFCs this direction as well.

2025-03-31 07:23 UTC, merged

2025-03-31 08:40 UTC, rust-timer commented
Finished benchmarking commit (7bfd9529be7f4e10ca12f9eee1f442c12c6ea8ad): [comparison URL](https://perf.rust-lang.org/compare.html?start=3c0f72271b0fcc9ebfed79e1004ea4d5693f1a34&end=7bfd9529be7f4e10ca12f9eee1f442c12c6ea8ad&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=3c0f72271b0fcc9ebfed79e1004ea4d5693f1a34&end=7bfd9529be7f4e10ca12f9eee1f442c12c6ea8ad&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=3c0f72271b0fcc9ebfed79e1004ea4d5693f1a34&end=7bfd9529be7f4e10ca12f9eee1f442c12c6ea8ad&stat=max-rss)
<details>
<summary>Results (secondary 2.1%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 2.1% | [1.2%, 3.1%] | 2     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=3c0f72271b0fcc9ebfed79e1004ea4d5693f1a34&end=7bfd9529be7f4e10ca12f9eee1f442c12c6ea8ad&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=3c0f72271b0fcc9ebfed79e1004ea4d5693f1a34&end=7bfd9529be7f4e10ca12f9eee1f442c12c6ea8ad&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 776.099s -> 776.473s (0.05%)
**Artifact size**: 365.92 MiB -> 365.91 MiB (-0.00%)