Treat `k#ident` keywords as valid tokens
rust-lang/rust pull request #119351
Opened 2023-12-27 16:08 UTC by fee1-dead

We treat `k#ident` as a valid token, since it could be useful in implementing experimental features without introducing too much frontend changes (for example, with deref patterns). However, this PR as is would also make the following code compile:

```rust
macro_rules! a {
    (k#test) => {}
}

fn main() {
    a!(k#test);
}
```

We'd probably want to prevent that from happening, so should we feature gate this specific token?

2023-12-27 16:43 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7339967418/job/19985165317) [(plain)](https://github.com/rust-lang/rust/commit/8d90b43f4f01fdf78e0b11909e95ec2daa956674/checks/19985165317/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Built container sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Looks like docker image is the same as before, not uploading
https://ci-caches.rust-lang.org/docker/7ebc15c01a233894034d277c8cce4e949f4e7791f66b4727c8fb6e058a0b8171d6152e1441d677cef0653843ceeee469c097b8699b2bb74249e674f6aa1a8813
sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-16]
##[group]Clock drift check
  local time: Wed Dec 27 16:10:47 UTC 2023
  network time: Wed, 27 Dec 2023 16:10:47 GMT
  network time: Wed, 27 Dec 2023 16:10:47 GMT
##[endgroup]
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-16', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-missing-tools', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-16/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: rust.codegen-units-std := 1
---
##[endgroup]
Testing GCC stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling y v0.1.0 (/checkout/compiler/rustc_codegen_gcc/build_system)
    Finished release [optimized] target(s) in 1.40s
     Running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-codegen/x86_64-unknown-linux-gnu/release/y test --use-system-gcc --use-backend gcc --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc --release --no-default-features --mini-tests --std-tests`
Using system GCC
Using system GCC
[BUILD] example
[AOT] mini_core_hello_world
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc/mini_core_hello_world
abc
---
   Compiling tracing v0.1.40
   Compiling ra-ap-rustc_abi v0.21.0
   Compiling rustc-dependencies v0.0.0 (/checkout/src/tools/rust-analyzer/crates/rustc-dependencies)
   Compiling parser v0.0.0 (/checkout/src/tools/rust-analyzer/crates/parser)
error[E0599]: no variant or associated item named `KeywordIdent` found for enum `TokenKind` in the current scope
    |
227 |                 rustc_lexer::TokenKind::KeywordIdent => ERROR,
    |                                         ^^^^^^^^^^^^ variant or associated item not found in `TokenKind`

```

</details>

2023-12-27 16:46 UTC, Nilstrieb commented on compiler/rustc_ast/src/token.rs
> +    Keyword(Symbol),
Actual keywords are Ident, so it seems confusing for a "forced keyword" to be special here.

2023-12-27 16:49 UTC, WaffleLapkin requested changes
> We'd probably want to prevent that from happening, so should we feature gate this specific token?

Yes, I think we should feature gate `k#` and stabilize it separately and only if some stable feature would make use of it.

2023-12-28 10:52 UTC, fee1-dead commented
just converted `token::Ident` to use `IdentKind` - feature gating and tests to follow.

2023-12-28 10:59 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7346719281/job/20001942350) [(plain)](https://github.com/rust-lang/rust/commit/58624fc0eccc20f4940c87e4ae1258573ea3614d/checks/20001942350/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Built container sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Looks like docker image is the same as before, not uploading
https://ci-caches.rust-lang.org/docker/7ebc15c01a233894034d277c8cce4e949f4e7791f66b4727c8fb6e058a0b8171d6152e1441d677cef0653843ceeee469c097b8699b2bb74249e674f6aa1a8813
sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-16]
##[group]Clock drift check
  local time: Thu Dec 28 10:27:04 UTC 2023
  network time: Thu, 28 Dec 2023 10:27:04 GMT
  network time: Thu, 28 Dec 2023 10:27:04 GMT
##[endgroup]
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-16', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-missing-tools', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-16/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: rust.codegen-units-std := 1
---
##[endgroup]
Testing GCC stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling y v0.1.0 (/checkout/compiler/rustc_codegen_gcc/build_system)
    Finished release [optimized] target(s) in 1.38s
     Running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-codegen/x86_64-unknown-linux-gnu/release/y test --use-system-gcc --use-backend gcc --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc --release --no-default-features --mini-tests --std-tests`
Using system GCC
Using system GCC
[BUILD] example
[AOT] mini_core_hello_world
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc/mini_core_hello_world
abc
---
   Compiling tracing v0.1.40
   Compiling ra-ap-rustc_abi v0.21.0
   Compiling rustc-dependencies v0.0.0 (/checkout/src/tools/rust-analyzer/crates/rustc-dependencies)
   Compiling parser v0.0.0 (/checkout/src/tools/rust-analyzer/crates/parser)
error[E0599]: no variant or associated item named `KeywordIdent` found for enum `TokenKind` in the current scope
    |
227 |                 rustc_lexer::TokenKind::KeywordIdent => ERROR,
    |                                         ^^^^^^^^^^^^ variant or associated item not found in `TokenKind`

```

</details>

2023-12-29 09:01 UTC, Veykril commented
The CI failure is due to https://github.com/rust-lang/rust/pull/118861

2023-12-30 06:55 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7362654405/job/20041302619) [(plain)](https://github.com/rust-lang/rust/commit/c2de4837e6627542848ba09374435f6a7c07c4a1/checks/20041302619/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Built container sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Looks like docker image is the same as before, not uploading
https://ci-caches.rust-lang.org/docker/7ebc15c01a233894034d277c8cce4e949f4e7791f66b4727c8fb6e058a0b8171d6152e1441d677cef0653843ceeee469c097b8699b2bb74249e674f6aa1a8813
sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-16]
##[group]Clock drift check
  local time: Sat Dec 30 06:53:38 UTC 2023
  network time: Sat, 30 Dec 2023 06:53:38 GMT
  network time: Sat, 30 Dec 2023 06:53:38 GMT
##[endgroup]
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-16', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-16/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: rust.codegen-units-std := 1
---
    |
503 |     macro_rules! gate_all {
    |     --------------------- when calling this macro
...
519 |     gate_all!(forced_keywords, "`k#ident` syntax is experimental",);
    |                                                                   ^ missing tokens in macro arguments
    |
note: while trying to match meta-variable `$help:literal`
    |
    |
511 |         ($gate:ident, $msg:literal, $help:literal) => {

error: could not compile `rustc_ast_passes` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
Build completed unsuccessfully in 0:01:19
```

</details>

2024-01-02 16:24 UTC, fee1-dead commented
closed due to design concerns, there is an alternative - using `builtin #` (with a space) and this isn't really useful.

2024-06-25 10:07 UTC, fee1-dead commented
No energy to revive this PR, so closing

2024-06-25 10:07 UTC, closed without merging