Modify GenericArg to use NonNull ptr
rust-lang/rust pull request #119955
Opened 2024-01-14 05:55 UTC by kamalesh0406

This is the first PR to solve issue #119217 . In this PR, I have modified the GenericArg struct to use the `NonNull` struct as the pointer instead of `NonZeroUsize`. The change were tested by running `./x test compiler/rustc_middle`.

r? @WaffleLapkin

2024-01-14 10:41 UTC, WaffleLapkin requested changes
This generally looks good, but I have a few nitpicks :)

2024-01-14 10:41 UTC, WaffleLapkin commented on compiler/rustc_middle/src/ty/generic_args.rs
> +        let ptr_without_tag = unsafe {
I think the name `ptr` is fine, no need to specify "without tag"

2024-01-14 10:41 UTC, WaffleLapkin commented on compiler/rustc_middle/src/ty/generic_args.rs
> +            self.ptr.map_addr(|addr| NonZeroUsize::new_unchecked(addr.get() & !TAG_MASK)).as_ptr()
```suggestion
            self.ptr.map_addr(|addr| NonZeroUsize::new_unchecked(addr.get() & !TAG_MASK))
```

no need to leave `NonNull` (see below)

2024-01-14 10:41 UTC, WaffleLapkin commented on compiler/rustc_middle/src/ty/generic_args.rs
> +                    &*(ptr_without_tag as *const ty::RegionKind<'tcx>),
```suggestion
                    ptr.cast::<ty::RegionKind<'tcx>>().as_ref(),
```

and similarly for others

2024-01-14 10:42 UTC, WaffleLapkin commented
I've marked this as https://github.com/rust-lang/rust/labels/S-waiting-on-author, once this is ready for review, please use `@rustbot review` ([learn more about rustbot commands](https://forge.rust-lang.org/triagebot/index.html)).

2024-01-14 14:12 UTC, kamalesh0406 commented
@rustbot review

2024-01-15 15:35 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7531008944/job/20498620353) [(plain)](https://github.com/rust-lang/rust/commit/76fcdb31ebcb653fcffd155e87dfdf26e982b96e/checks/20498620353/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v4' (SHA:b4ffde65f46336ab88eb53be808477a3936bae11)
Download action repository 'actions/upload-artifact@v3' (SHA:a8a3f3ad30e3422c9c7b888a15615d19a852ae32)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
---
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=kamalesh0406
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_b51b748a-ccb0-4737-a746-22eaf87f4867
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=4d870772264e463c1dc6e28d9c3b6692b6d833f9
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_b51b748a-ccb0-4737-a746-22eaf87f4867
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_b51b748a-ccb0-4737-a746-22eaf87f4867
GITHUB_TRIGGERING_ACTOR=kamalesh0406
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/119955/merge
GITHUB_WORKFLOW_SHA=4d870772264e463c1dc6e28d9c3b6692b6d833f9
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.13/x64
---
Removing intermediate container 8020c07d77e4
 ---> e488263c07e0
Step 6/10 : COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
 ---> 3c119cf2863e
Step 7/10 : RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt     && pip3 install virtualenv
Collecting binaryornot==0.4.4
  Downloading binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
Collecting boolean-py==4.0
  Downloading boolean.py-4.0-py3-none-any.whl (25 kB)
---
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting virtualenv
  Downloading virtualenv-20.25.0-py3-none-any.whl (3.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 75.6 MB/s eta 0:00:00
Collecting distlib<1,>=0.3.7
  Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
Collecting filelock<4,>=3.12.2
  Downloading filelock-3.13.1-py3-none-any.whl (11 kB)
  Downloading filelock-3.13.1-py3-none-any.whl (11 kB)
Collecting platformdirs<5,>=3.9.1
  Downloading platformdirs-4.1.0-py3-none-any.whl (17 kB)
Installing collected packages: distlib, platformdirs, filelock, virtualenv
Successfully installed distlib-0.3.8 filelock-3.13.1 platformdirs-4.1.0 virtualenv-20.25.0
Removing intermediate container 95ae26caea11
 ---> f1940c794a18
Step 8/10 : COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
 ---> 7e94f3f4603a
 ---> 7e94f3f4603a
Step 9/10 : COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/
 ---> 303b5553a3cd
Step 10/10 : ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
Removing intermediate container afd8b9dabf86
 ---> 707d3d3e781c
Successfully built 707d3d3e781c
Successfully tagged rust-ci:latest
Successfully tagged rust-ci:latest
##[endgroup]
Built container sha256:707d3d3e781c74927c04dbef78dc8aee0fe0d8b119ae6f00d971c43849f970b7
Uploading finished image sha256:707d3d3e781c74927c04dbef78dc8aee0fe0d8b119ae6f00d971c43849f970b7 to https://ci-caches.rust-lang.org/docker/139141a603ff222e98d20ef66f0e4eaedfc4b373e41d302ecff577f90ee0c6cf0cab092d18a8f6a073c88b362b9a680d3b2b6e5c828faaf25d1b853eabb78b1a
IMAGE          CREATED          CREATED BY                                      SIZE      COMMENT
707d3d3e781c   1 second ago     /bin/sh -c #(nop)  ENV SCRIPT=TIDY_PRINT_DIF…   0B        
7e94f3f4603a   2 seconds ago    /bin/sh -c #(nop) COPY file:078ea1d11e7b7cda…   367B      
f1940c794a18   3 seconds ago    |1 DEBIAN_FRONTEND=noninteractive /bin/sh -c…   23.9MB    
3c119cf2863e   9 seconds ago    /bin/sh -c #(nop) COPY file:ac591dd6bc5afa66…   5.33kB    
e488263c07e0   10 seconds ago   |1 DEBIAN_FRONTEND=noninteractive /bin/sh -c…   23.1MB    
---
<missing>      4 weeks ago      /bin/sh -c #(nop)  LABEL org.opencontainers.…   0B        
<missing>      4 weeks ago      /bin/sh -c #(nop)  ARG LAUNCHPAD_BUILD_ARCH     0B        
<missing>      4 weeks ago      /bin/sh -c #(nop)  ARG RELEASE                  0B        

<botocore.awsrequest.AWSRequest object at 0x7f80d404f910>
gzip: stdout: Broken pipe
xargs: docker: terminated by signal 13
https://ci-caches.rust-lang.org/docker/139141a603ff222e98d20ef66f0e4eaedfc4b373e41d302ecff577f90ee0c6cf0cab092d18a8f6a073c88b362b9a680d3b2b6e5c828faaf25d1b853eabb78b1a
sha256:707d3d3e781c74927c04dbef78dc8aee0fe0d8b119ae6f00d971c43849f970b7
---
DirectMap4k:      182208 kB
DirectMap2M:     6109184 kB
DirectMap1G:    12582912 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
    Finished dev [unoptimized] target(s) in 0.03s
##[endgroup]
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/1ead4761e9e2f056385768614c23ffa7acb6a19e/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/llvm-1ead4761e9e2f056385768614c23ffa7acb6a19e-true/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm
---
   Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
    Finished release [optimized] target(s) in 24.99s
##[endgroup]
fmt check
##[error]Diff in /checkout/compiler/rustc_middle/src/ty/generic_args.rs at line 93:
         };
 
 
-        GenericArg { ptr: unsafe { ptr.map_addr(|addr| NonZeroUsize::new_unchecked(addr.get() | tag)) }, marker: PhantomData }
+        GenericArg {
+            ptr: unsafe { ptr.map_addr(|addr| NonZeroUsize::new_unchecked(addr.get() | tag)) },
+            marker: PhantomData,
     }
 }
 
 
##[error]Diff in /checkout/compiler/rustc_middle/src/ty/mod.rs at line 854:
     marker: PhantomData<(Ty<'tcx>, Const<'tcx>)>,
 
 
-unsafe impl<'tcx> DynSend for Term<'tcx> where
-    &'tcx (Ty<'tcx>, Const<'tcx>): DynSend
-}
-}
-unsafe impl<'tcx> DynSync for Term<'tcx> where
-    &'tcx (Ty<'tcx>, Const<'tcx>): DynSync
-}
-}
-unsafe impl<'tcx> Send for Term<'tcx> where
-    &'tcx (Ty<'tcx>, Const<'tcx>): Send
-}
-}
-unsafe impl<'tcx> Sync for Term<'tcx> where
-    &'tcx (Ty<'tcx>, Const<'tcx>): Sync
-}
-}
+unsafe impl<'tcx> DynSend for Term<'tcx> where &'tcx (Ty<'tcx>, Const<'tcx>): DynSend {}
+unsafe impl<'tcx> DynSync for Term<'tcx> where &'tcx (Ty<'tcx>, Const<'tcx>): DynSync {}
+unsafe impl<'tcx> Send for Term<'tcx> where &'tcx (Ty<'tcx>, Const<'tcx>): Send {}
+unsafe impl<'tcx> Sync for Term<'tcx> where &'tcx (Ty<'tcx>, Const<'tcx>): Sync {}
 
 impl Debug for Term<'_> {
     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
##[error]Diff in /checkout/compiler/rustc_middle/src/ty/mod.rs at line 1016:
         };
 
 
-        Term { ptr: unsafe { ptr.map_addr(|addr| NonZeroUsize::new_unchecked(addr.get() | tag)) }, marker: PhantomData }
+        Term {
+            ptr: unsafe { ptr.map_addr(|addr| NonZeroUsize::new_unchecked(addr.get() | tag)) },
+            marker: PhantomData,
     }
 }
 
 
Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/compiler/rustc_middle/src/ty/assoc.rs" "/checkout/compiler/rustc_middle/ [...]

2024-01-15 16:15 UTC, WaffleLapkin requested changes

2024-01-15 16:15 UTC, WaffleLapkin commented on compiler/rustc_middle/src/ty/generic_args.rs
> +            ptr: unsafe { ptr.map_addr(|addr| NonZeroUsize::new_unchecked(addr.get() | tag)) },
There is a `BitOr<usize>` impl for `NonZeroUsize`, so you can just
```suggestion
            ptr: ptr.map_addr(|addr| addr | tag),
```

2024-01-15 16:15 UTC, WaffleLapkin commented on compiler/rustc_middle/src/ty/generic_args.rs
> +                    &*(ptr.cast::<ty::RegionKind<'tcx>>().as_ref()),
I don't think residing here and later is needed
```suggestion
                    ptr.cast::<ty::RegionKind<'tcx>>().as_ref()
```

2024-01-15 16:15 UTC, WaffleLapkin commented on compiler/rustc_middle/src/ty/mod.rs
> +            ptr: unsafe { ptr.map_addr(|addr| NonZeroUsize::new_unchecked(addr.get() | tag)) },
```suggestion
            ptr: ptr.map_addr(|addr| addr | tag),
```

2024-01-15 17:14 UTC, kamalesh0406 commented
@rustbot review

2024-01-17 00:31 UTC, WaffleLapkin approved these changes

2024-01-17 00:32 UTC, WaffleLapkin commented
@bors r+ rollup

2024-01-17 14:34 UTC, compiler-errors commented
This PR failed in a rollup: https://github.com/rust-lang/rust/pull/120041#issuecomment-1894935486

@bors r-

2024-01-17 16:04 UTC, WaffleLapkin commented
Right, my bad. I think the problem is that `DynSend`/`DynSync` impls are not needed. @kamalesh0406 please remove those `Dyn*` impls and check that the compiler compiles.

2024-01-18 00:45 UTC, WaffleLapkin commented
@bors r+ rollup=maybe

2024-01-18 00:45 UTC, kamalesh0406 commented
@rustbot review

2024-01-18 09:33 UTC, matthiaskrgr commented
@bors r- https://github.com/rust-lang/rust/pull/120088#issuecomment-1898112685

2024-01-19 04:04 UTC, kamalesh0406 commented
@rustbot review

2024-01-24 00:20 UTC, WaffleLapkin commented
Let's try again
@bors r+ rollup=never

2024-01-25 09:19 UTC, merged

2024-01-25 10:35 UTC, rust-timer commented
Finished benchmarking commit (d93feccb35183fa66fee77e7a2c9d4bf4d01695c): [comparison URL](https://perf.rust-lang.org/compare.html?start=039d887928361df98ca530471b609378be93983a&end=d93feccb35183fa66fee77e7a2c9d4bf4d01695c&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=039d887928361df98ca530471b609378be93983a&end=d93feccb35183fa66fee77e7a2c9d4bf4d01695c&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=039d887928361df98ca530471b609378be93983a&end=d93feccb35183fa66fee77e7a2c9d4bf4d01695c&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 5.5%  | [5.5%, 5.5%]   | 1     |
| Regressions ❌ <br /> (secondary)  | 3.0%  | [3.0%, 3.0%]   | 1     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -4.6% | [-4.6%, -4.6%] | 1     |
| All ❌✅ (primary)                 | 5.5%  | [5.5%, 5.5%]   | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=039d887928361df98ca530471b609378be93983a&end=d93feccb35183fa66fee77e7a2c9d4bf4d01695c&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=039d887928361df98ca530471b609378be93983a&end=d93feccb35183fa66fee77e7a2c9d4bf4d01695c&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 661.843s -> 662.638s (0.12%)
**Artifact size**: 308.29 MiB -> 308.19 MiB (-0.03%)