improvements
rust-lang/rust pull request #119999
Opened 2024-01-15 17:44 UTC by onur-ozkan

2024-01-15 17:53 UTC, onur-ozkan commented
> First commit increases the supported file size. But I am not sure about its necessity — can we realistically encounter file sizes exceeding 4GB in builds, perhaps through some complicated configurations?

Let me know if this isn't needed (so I can revert).

2024-01-20 20:53 UTC, Mark-Simulacrum commented
I don't think we need to support large files, though I also don't mind supporting them.

That said, if we're touching this code I think rather than manually bit twiddling using https://doc.rust-lang.org/nightly/std/primitive.u32.html#method.to_le_bytes and correspondign from_le_bytes feels much better to me.

2024-01-21 09:14 UTC, onur-ozkan commented
> The second commit adds a sanity check to avoid encountering the error io::copy(&mut file, dst) failed with Connection reset by peer (os error 104) on the remote-test-server side.

Just realized that there is no need for a sanity check on the size anymore since we transmit the size without any conversion.

Updated the manual bit-twiddling part to use `to_be_bytes` on the client side (server side already uses `from_be_bytes`).

@rustbot ready

2024-01-21 14:57 UTC, Mark-Simulacrum requested changes

2024-01-21 14:57 UTC, Mark-Simulacrum commented on src/tools/remote-test-client/src/main.rs
> +        }
`u64::from_be_bytes(header[1..9].try_into().unwrap())`

2024-01-21 15:32 UTC, Mark-Simulacrum commented
@bors r+

2024-01-22 18:22 UTC, merged