`Vec::resize` for bytes should be a single `memset`
rust-lang/rust pull request #120050
Opened 2024-01-17 07:29 UTC by scottmcm

*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/120050)*

Really I just started by trying to see if specializing `iter::repeat_n` would help the perf issue that kept me from removing `Vec::extend_with` last time I tried, but I noticed in the process that a resize for bytes doesn't set all the new space with a single `memset`: <https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=35175ec844b46fcd95e2d0aad526859e>

So using `repeat_n` to implement it -- like `VecDeque` uses, with the specialization for `next` to avoid a branch -- means that the optimizer notices the resize can set all the values with a single memset.

2024-01-17 08:40 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2024-01-17 10:08 UTC, rust-timer commented
Queued 0db48a7c3c2ca5e498da14eae53a7474e16886df with parent f45fe573a587f5d82e9e78cbece64bad4b3709f8, future [comparison URL](https://perf.rust-lang.org/compare.html?start=f45fe573a587f5d82e9e78cbece64bad4b3709f8&end=0db48a7c3c2ca5e498da14eae53a7474e16886df).
There is currently 1 preceding artifact in the [queue](https://perf.rust-lang.org/status.html).
It will probably take at least ~1.7 hours until the benchmark run finishes.
<!-- rust-timer: temporary -->

2024-01-17 11:52 UTC, rust-timer commented
Finished benchmarking commit (0db48a7c3c2ca5e498da14eae53a7474e16886df): [comparison URL](https://perf.rust-lang.org/compare.html?start=f45fe573a587f5d82e9e78cbece64bad4b3709f8&end=0db48a7c3c2ca5e498da14eae53a7474e16886df&stat=instructions:u).

### Overall result: ❌✅ regressions and improvements - ACTION NEEDED


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: -S-waiting-on-perf +perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=f45fe573a587f5d82e9e78cbece64bad4b3709f8&end=0db48a7c3c2ca5e498da14eae53a7474e16886df&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.4%  | [0.2%, 0.5%]   | 15    |
| Regressions ❌ <br /> (secondary)  | 3.3%  | [3.1%, 3.7%]   | 6     |
| Improvements ✅ <br /> (primary)   | -1.5% | [-1.5%, -1.5%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | 0.2%  | [-1.5%, 0.5%]  | 16    |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=f45fe573a587f5d82e9e78cbece64bad4b3709f8&end=0db48a7c3c2ca5e498da14eae53a7474e16886df&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range           | count |
|:----------------------------------:|:-----:|:---------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 2.9%  | [0.3%, 5.5%]    | 2     |
| Regressions ❌ <br /> (secondary)  | -     | -               | 0     |
| Improvements ✅ <br /> (primary)   | -8.3% | [-12.7%, -4.7%] | 4     |
| Improvements ✅ <br /> (secondary) | -4.9% | [-4.9%, -4.9%]  | 1     |
| All ❌✅ (primary)                 | -4.6% | [-12.7%, 5.5%]  | 6     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=f45fe573a587f5d82e9e78cbece64bad4b3709f8&end=0db48a7c3c2ca5e498da14eae53a7474e16886df&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | 20.2% | [18.6%, 22.7%] | 6     |
| Improvements ✅ <br /> (primary)   | -1.5% | [-1.5%, -1.5%] | 1     |
| Improvements ✅ <br /> (secondary) | -2.9% | [-4.3%, -2.3%] | 5     |
| All ❌✅ (primary)                 | -1.5% | [-1.5%, -1.5%] | 1     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=f45fe573a587f5d82e9e78cbece64bad4b3709f8&end=0db48a7c3c2ca5e498da14eae53a7474e16886df&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 665.423s -> 664.993s (-0.06%)
**Artifact size**: 308.34 MiB -> 308.35 MiB (0.01%)

2024-01-17 11:55 UTC, Kobzol commented
Looks like something bad has happened in borrow checking of `wg-grammar` (https://perf.rust-lang.org/detailed-query.html?commit=0db48a7c3c2ca5e498da14eae53a7474e16886df&benchmark=wg-grammar-check&scenario=full&base_commit=f45fe573a587f5d82e9e78cbece64bad4b3709f8.

2024-01-17 22:17 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2024-01-17 23:44 UTC, rust-timer commented
Queued 27371af9b8c50c2f3b165000d3bcd9684c4a0807 with parent 6ae4cfbbb080cafea7f6be48ce47678ee057352c, future [comparison URL](https://perf.rust-lang.org/compare.html?start=6ae4cfbbb080cafea7f6be48ce47678ee057352c&end=27371af9b8c50c2f3b165000d3bcd9684c4a0807).
There is currently 1 preceding artifact in the [queue](https://perf.rust-lang.org/status.html).
It will probably take at least ~2.3 hours until the benchmark run finishes.
<!-- rust-timer: temporary -->

2024-01-18 02:32 UTC, rust-timer commented
Finished benchmarking commit (27371af9b8c50c2f3b165000d3bcd9684c4a0807): [comparison URL](https://perf.rust-lang.org/compare.html?start=6ae4cfbbb080cafea7f6be48ce47678ee057352c&end=27371af9b8c50c2f3b165000d3bcd9684c4a0807&stat=instructions:u).

### Overall result: ❌✅ regressions and improvements - ACTION NEEDED


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: -S-waiting-on-perf +perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=6ae4cfbbb080cafea7f6be48ce47678ee057352c&end=27371af9b8c50c2f3b165000d3bcd9684c4a0807&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.4%  | [0.3%, 0.7%]   | 13    |
| Regressions ❌ <br /> (secondary)  | 2.1%  | [1.9%, 2.3%]   | 6     |
| Improvements ✅ <br /> (primary)   | -0.5% | [-0.9%, -0.3%] | 4     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | 0.2%  | [-0.9%, 0.7%]  | 17    |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=6ae4cfbbb080cafea7f6be48ce47678ee057352c&end=27371af9b8c50c2f3b165000d3bcd9684c4a0807&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 4.3%  | [0.2%, 8.4%]   | 2     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -2.5% | [-3.7%, -1.4%] | 2     |
| Improvements ✅ <br /> (secondary) | -1.2% | [-1.5%, -0.7%] | 3     |
| All ❌✅ (primary)                 | 0.9%  | [-3.7%, 8.4%]  | 4     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=6ae4cfbbb080cafea7f6be48ce47678ee057352c&end=27371af9b8c50c2f3b165000d3bcd9684c4a0807&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.1%  | [1.1%, 1.1%]   | 1     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -1.1% | [-1.1%, -1.1%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | 0.0%  | [-1.1%, 1.1%]  | 2     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=6ae4cfbbb080cafea7f6be48ce47678ee057352c&end=27371af9b8c50c2f3b165000d3bcd9684c4a0807&stat=size:linked_artifact)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.7% | [0.4%, 0.9%] | 29    |
| Regressions ❌ <br /> (secondary)  | -    | -            | 0     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 0.7% | [0.4%, 0.9%] | 29    |
</details>

**Bootstrap**: 663.454s -> 664.862s (0.21%)
**Artifact size**: 308.30 MiB -> 308.31 MiB (0.01%)

2024-07-04 23:16 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/9800749116/job/27063049601) [(plain)](https://github.com/rust-lang/rust/commit/f4bb10b36cd3e1da6d8372b2eb828a61e53ac0aa/checks/27063049601/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling unwind v0.0.0 (/checkout/library/unwind)
error[E0433]: failed to resolve: use of undeclared crate or module `ptr`
  --> library/alloc/src/vec/spec_from_elem.rs:39:13
   |
39 |             ptr::write_bytes(v.as_mut_ptr(), elem as u8, n);
   |             ^^^ use of undeclared crate or module `ptr`
help: a builtin type with a similar name exists
   |
   |
39 |             str::write_bytes(v.as_mut_ptr(), elem as u8, n);
help: consider importing one of these items
   |
1  + use core::ptr;
   |
   |
1  + use crate::vec::ptr;
   |

error[E0433]: failed to resolve: use of undeclared crate or module `ptr`
  --> library/alloc/src/vec/spec_from_elem.rs:54:13
   |
54 |             ptr::write_bytes(v.as_mut_ptr(), elem, n);
   |             ^^^ use of undeclared crate or module `ptr`
help: a builtin type with a similar name exists
   |
   |
54 |             str::write_bytes(v.as_mut_ptr(), elem, n);
help: consider importing one of these items
   |
1  + use core::ptr;
   |
```

</details>

2024-07-04 23:34 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2024-08-05 11:35 UTC, Dylan-DPC commented
@scottmcm the try run didn't get executed so you will have to resolve conflicts and run it again

2024-09-18 05:03 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2024-09-18 06:54 UTC, rust-timer commented
Queued f5c37550f884726ba52e559b2750e8585e7c12da with parent 60c3673456cb5eba4d6ac4ed22be179deebb6dcf, future [comparison URL](https://perf.rust-lang.org/compare.html?start=60c3673456cb5eba4d6ac4ed22be179deebb6dcf&end=f5c37550f884726ba52e559b2750e8585e7c12da).
There are currently 0 preceding artifacts in the [queue](https://perf.rust-lang.org/status.html).
It will probably take at least ~1.2 hours until the benchmark run finishes.
<!-- rust-timer: temporary -->

2024-09-18 08:08 UTC, rust-timer commented
Finished benchmarking commit (f5c37550f884726ba52e559b2750e8585e7c12da): [comparison URL](https://perf.rust-lang.org/compare.html?start=60c3673456cb5eba4d6ac4ed22be179deebb6dcf&end=f5c37550f884726ba52e559b2750e8585e7c12da&stat=instructions:u).

### Overall result: ❌✅ regressions and improvements - ACTION NEEDED


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: -S-waiting-on-perf +perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=60c3673456cb5eba4d6ac4ed22be179deebb6dcf&end=f5c37550f884726ba52e559b2750e8585e7c12da&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.3%  | [0.2%, 0.4%]   | 7     |
| Regressions ❌ <br /> (secondary)  | 0.5%  | [0.2%, 0.8%]   | 11    |
| Improvements ✅ <br /> (primary)   | -0.4% | [-0.4%, -0.4%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | 0.2%  | [-0.4%, 0.4%]  | 8     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=60c3673456cb5eba4d6ac4ed22be179deebb6dcf&end=f5c37550f884726ba52e559b2750e8585e7c12da&stat=max-rss)
<details>
<summary>Results (primary 0.9%, secondary -2.5%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 5.8%  | [3.8%, 7.8%]   | 2     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -2.4% | [-3.5%, -1.4%] | 3     |
| Improvements ✅ <br /> (secondary) | -2.5% | [-2.5%, -2.5%] | 1     |
| All ❌✅ (primary)                 | 0.9%  | [-3.5%, 7.8%]  | 5     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=60c3673456cb5eba4d6ac4ed22be179deebb6dcf&end=f5c37550f884726ba52e559b2750e8585e7c12da&stat=cycles:u)
<details>
<summary>Results (secondary 2.5%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 2.5% | [2.4%, 2.6%] | 2     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=60c3673456cb5eba4d6ac4ed22be179deebb6dcf&end=f5c37550f884726ba52e559b2750e8585e7c12da&stat=size:linked_artifact)
<details>
<summary>Results (primary 0.2%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.3%  | [0.1%, 0.4%]   | 28    |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -0.1% | [-0.2%, -0.0%] | 11    |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | 0.2%  | [-0.2%, 0.4%]  | 39    |
</details>

**Bootstrap**: 768.777s -> 770.588s (0.24%)
**Artifact size**: 341.28 MiB -> 341.28 MiB (-0.00%)

2024-09-18 17:34 UTC, JarvisCraft requested changes

2024-09-19 18:43 UTC, JarvisCraft commented on library/alloc/src/vec/mod.rs
> +            if !T::IS_ZST {
Thanks for tagging me! I've commented below on what I am unsure about, though the optimization really looks promising.

2024-12-02 07:04 UTC, paolobarbolini commented
FYI #130887 + #133662 also happens to fix this

2026-07-11 19:57 UTC, closed without merging