#[cold] on match arms
rust-lang/rust pull request #120193
Opened 2024-01-21 10:12 UTC by x17jiri

### Summary

Adds the possibility to use `#[cold]` attribute on match arms to hint the optimizer that the arm is unlikely to be taken.

### Motivation

These hints are sometimes thought to help branch prediction, but the effect is probably marginal. Modern CPUs don't support hints on conditional branch instructions. They either have the current branch in the BTB (branch prediction buffer), or not, in which case the branch is predicted not to be taken.

These hints are, however, helpful in letting the compiler know what is the fast path, so it can be optimized at the expense of the slow path.

`grep`-ing the LLVM code for BlockFrequencyInfo and BranchProbabilityInfo shows that these hints are used at many places in the optimizer. Such as:
- block placement - improve locality by making the fast path compact and move everything else out of the way
- inlining, loop unrolling - these optimizations can be less aggressive on the cold path therefore reducing code size
- register allocation - preferably keep in registers the data needed on the fast path

### History

RFC 1131 ( https://github.com/rust-lang/rust/issues/26179 ) added `likely` and `unlikely` intrinsics, which get converted to `llvm.expect.i8`. However this LLVM instruction is fragile and may get removed by some optimization passes. The problems with the intrinsics have been reported several times: https://github.com/rust-lang/rust/issues/96276 , https://github.com/rust-lang/rust/issues/96275 , https://github.com/rust-lang/rust/issues/88767

### Other languages

Clang and GCC C++ compilers provide `__builtin_expect`. Since C++20, it is also possible to use `[[likely]]` and `[[unlikely]]` attributes.

Use:
```
if (__builtin_expect(condition, false)) { ... this branch is UNlikely ... }

if (condition) [[likely]] { ... this branch is likely... }
```

Note that while clang provides `__builtin_expect`, it does not convert it to `llvm.expect.i8`. Instead, it looks at the surrounding code and if there is a condition, emits branch weight metadata for conditional branches.

### Design

Implementing `likely`/`unlikely` type of functions properly to emit branch weights would add significant complexity to the compiler. Additionally, these functions are not easy to use with `match` arms.

Replacing the functions with attributes is easier to implement and will also work with `match`.

A question remains whether these attributes should be named `likely`/`unlikely` as in C++, or if we could reuse the already existing `#[cold]` attribute. `#[cold]` has the same meaning as `unlikely`, i.e., marking the slow path, but it can currently only be used on entire functions.

I personally prefer `#[cold]` because it already exists in Rust and is a short word that looks better in code. It has one disadvantage though.
This code:
```
if cond #[likely] { ... }
```
becomes:
```
if cond { ... } #[cold] { ... empty cold branch ... }
```

In this PR, I implemented the possibility to add `#[cold]` attribute on match arms. Use is as follows:
```
match x {
    #[cold] true => { ... } // the true arm is UNlikely
    _ => { ... } // the false arm is likely
}
```

### Limitations
The implementation only works on bool, or integers with single value arm and an otherwise arm. Extending it to other types and to `if` statements should not be too difficult.

2024-01-21 10:18 UTC, x17jiri commented
This should be in T-lang. I'm not sure how I can change it.

There is discussion: https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Allow.20.23.5Bcold.5D.20on.20match.20and.20if.20arms

2024-01-21 10:18 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7600533139/job/20698895306) [(plain)](https://github.com/rust-lang/rust/commit/71b694c17a2cd6df7c7e87470671b6accd4bbd2d/checks/20698895306/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=x17jiri
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_65c7ba5c-388f-4f69-867f-7a56b4830643
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=8d7ab730ed8670a867667241e08472754456b877
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_65c7ba5c-388f-4f69-867f-7a56b4830643
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_65c7ba5c-388f-4f69-867f-7a56b4830643
GITHUB_TRIGGERING_ACTOR=x17jiri
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/120193/merge
GITHUB_WORKFLOW_SHA=8d7ab730ed8670a867667241e08472754456b877
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.13/x64
---
Built container sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Looks like docker image is the same as before, not uploading
https://ci-caches.rust-lang.org/docker/7ebc15c01a233894034d277c8cce4e949f4e7791f66b4727c8fb6e058a0b8171d6152e1441d677cef0653843ceeee469c097b8699b2bb74249e674f6aa1a8813
sha256:9c3c93a371e5aed5c18185b24f130d95d5140dbd72a9b325e7b6b49e521a4faa
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-16]
##[group]Clock drift check
  local time: Sun Jan 21 10:14:41 UTC 2024
  network time: Sun, 21 Jan 2024 10:14:41 GMT
  network time: Sun, 21 Jan 2024 10:14:41 GMT
##[endgroup]
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-16', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'build.optimized-compiler-builtins', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-16/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
   Compiling gccjit_sys v0.0.1 (https://github.com/antoyo/gccjit.rs#6e290f25)
   Compiling gccjit v1.0.0 (https://github.com/antoyo/gccjit.rs#6e290f25)
   Compiling tempfile v3.7.1
   Compiling rustc_codegen_gcc v0.1.0 (/checkout/compiler/rustc_codegen_gcc)
error[E0046]: not all trait items implemented, missing: `cond_br_with_cold_br`
    |
    |
408 | impl<'a, 'gcc, 'tcx> BuilderMethods<'a, 'tcx> for Builder<'a, 'gcc, 'tcx> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `cond_br_with_cold_br` in implementation
    |
    = help: implement the missing item: `fn cond_br_with_cold_br(&mut self, _: <Self as BackendTypes>::Value, _: <Self as BackendTypes>::BasicBlock, _: <Self as BackendTypes>::BasicBlock, _: std::option::Option<bool>) { todo!() }`
For more information about this error, try `rustc --explain E0046`.
error: could not compile `rustc_codegen_gcc` (lib) due to 1 previous error
Build completed unsuccessfully in 0:03:27
  local time: Sun Jan 21 10:18:43 UTC 2024
```

</details>

2024-01-21 11:00 UTC, oli-obk commented
I have opinions on the impl side, so I wanna review the impl once the lang design is complete

2024-01-21 20:14 UTC, traviscross commented
@rustbot labels +I-lang-nominated

Let's nominate so we can discuss this.  @scottmcm has proposed we might want to charter this as an experiment in such a way that we first make this work again in the compiler and then work on syntax.

2024-01-22 13:43 UTC, oli-obk commented
some thoughts:

* You also need to implement the logic for codgen_gcc. It is totally fine to just not support it there and emit normal branches (and leave a FIXME comment for the codegen_gcc authors).
* Is there some reasonable way we can test something here? How are we testing `#[cold]` functions beyond checking that they don't get inlined?
* The `ThinVec` could also just be a single index, stating that all arms after that one are cold
    * this will require shuffling arms around so that the cold ones are at the back
    * may need an additional boolean to decide what to do here
* we'll need to run perf to see if this affects performance when not used at all, because it touches a hot type in the MIR
* I'd prefer if this change weren't so invasive (bubbling it through a bunch of places, needing to add special logic to backends that duplicates some of the existing branching logic, yes I'm aware these two concerns are contradictory). Not sure how to do it much better, I'll give it some more thought

@bors try @rust-timer queue

2024-01-22 13:43 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2024-01-22 15:14 UTC, rust-timer commented
Queued 4d4892d72d55a8d6e12c6c7869c8737c5772ab9a with parent 366d112fa69164d79239ceeaa49e06497df5497f, future [comparison URL](https://perf.rust-lang.org/compare.html?start=366d112fa69164d79239ceeaa49e06497df5497f&end=4d4892d72d55a8d6e12c6c7869c8737c5772ab9a).
There is currently 1 preceding artifact in the [queue](https://perf.rust-lang.org/status.html).
It will probably take at least ~2.3 hours until the benchmark run finishes.
<!-- rust-timer: temporary -->

2024-01-22 17:34 UTC, rust-timer commented
Finished benchmarking commit (4d4892d72d55a8d6e12c6c7869c8737c5772ab9a): [comparison URL](https://perf.rust-lang.org/compare.html?start=366d112fa69164d79239ceeaa49e06497df5497f&end=4d4892d72d55a8d6e12c6c7869c8737c5772ab9a&stat=instructions:u).

### Overall result: no relevant changes - no action needed


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

@bors rollup=never
@rustbot label: -S-waiting-on-perf -perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=366d112fa69164d79239ceeaa49e06497df5497f&end=4d4892d72d55a8d6e12c6c7869c8737c5772ab9a&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=366d112fa69164d79239ceeaa49e06497df5497f&end=4d4892d72d55a8d6e12c6c7869c8737c5772ab9a&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 2.6% | [1.6%, 3.6%] | 2     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=366d112fa69164d79239ceeaa49e06497df5497f&end=4d4892d72d55a8d6e12c6c7869c8737c5772ab9a&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=366d112fa69164d79239ceeaa49e06497df5497f&end=4d4892d72d55a8d6e12c6c7869c8737c5772ab9a&stat=size:linked_artifact)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.1% | [0.0%, 0.1%] | 24    |
| Regressions ❌ <br /> (secondary)  | 0.0% | [0.0%, 0.0%] | 6     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 0.1% | [0.0%, 0.1%] | 24    |
</details>

**Bootstrap**: 663.975s -> 662.782s (-0.18%)
**Artifact size**: 308.39 MiB -> 308.43 MiB (0.01%)

2024-01-22 18:20 UTC, oli-obk commented
> If the performance tests find a regression, is there a way I can run them on my own? I would try to identify what is the bottleneck

https://github.com/rust-lang/rustc-perf/tree/master/collector/benchlib has instructions for building the perf runner. The command to actually run perf is shown in regressions (there are none, but here's an example: https://perf.rust-lang.org/detailed-query.html?commit=4d4892d72d55a8d6e12c6c7869c8737c5772ab9a&benchmark=helloworld-check&scenario=incr-unchanged&base_commit=366d112fa69164d79239ceeaa49e06497df5497f)

2024-01-22 18:21 UTC, oli-obk commented
> Then generate llvm file and it should contain something like

Ah great! We have tests like that in the tests/codegen dir. You can run them with `./x.py test codegen`

2024-01-23 00:39 UTC, cjgillot commented
On the impl side, you'll need to review mir opt passes that modify switches to update the additional information. At least simplify-cfg and unreachable-propagation, probably additional ones. 

Alternate idea to encode this in MIR: in source scope data. This avoids changing the syntax and keeping passes in sync. I have not looked in depth to verify if feasible.

2024-01-23 11:10 UTC, x17jiri commented
@oli-obk 

>     * I'd prefer if this change weren't so invasive (bubbling it through a bunch of places, needing to add special logic to backends that duplicates some of the existing branching logic, yes I'm aware these two concerns are contradictory). Not sure how to do it much better, I'll give it some more thought

I've been thinking about this and you are right that the change is rather invasive. Plus as @cjgillot points out, we may need to update passes to preserve the information.

One of the workarounds I considered initially before starting the implementation was this:
```
#[cold]
fn cold() {}

pub fn test(x: bool) {
	match x {
	true => { hot_function(); }
	false => { cold(); cold_function(); }
	}
}
```
The idea being that if the optimizer notices a call to `cold()` function, it may pessimize the false arm.

Unfortunately, it didn't work.

But if we wanted to go in this direction, the change may be very localized. I could create an optimizer pass that looks for basic blocks that call cold functions, then emits weights for the conditional branches going to the cold basic blocks. If the pass runs sufficiently late in the compilation, we would not need to change any other passes.

2024-01-23 11:19 UTC, x17jiri commented
@scottmcm I will check if this can make `llvm.expect` less fragile. I'm a little worried that it may again stop working silently, because it is not what clang uses.

2024-01-24 11:36 UTC, x17jiri commented
@scottmcm I'll give that some thought.

I looked into why the likely intrinsic is in a separate BB and it is because in MIR, any function call is BB terminator. Some (very few) intrinsics are internally converted to `NonDivergingIntrinsic`, which does not terminate a BB.

2024-01-24 18:14 UTC, x17jiri commented
@oli-obk What is your opinion on this? https://github.com/rust-lang/rust/commit/b24a73e4b2e45b7cdbdb01d0800eabd38a42df1f

- for how it's used, see tests
- I had to update bunch of files again, but only to default initialize the `is_cold` flag. Otherwise the change is very self-contained
- the new function in the backend has default implementation, so it is opt-in for backends
- for most functions, the new pass stops after the 'init' loop, i.e., it only traverses the list of basic blocks once
- if it actually gets to the second part of the algorithm, it usually stops after a few iterations
- I noticed that rust has its own inlining pass. Is it guaranteed that cold functions will not be inlined and that this will not change in the future? It would complicate things if the function got inlined before the pass is executed. But it would still be solvable with new intrinsic

2024-01-24 18:20 UTC, x17jiri commented
@scottmcm In the simple tests I tried, the `likely` is always right before the branch. But does it have to be so? If there were any instructions between the two, can I assume they don't change the probability?

2024-01-25 11:40 UTC, x17jiri commented
@scottmcm I'll implement the change and if it seems reasonably reliable, I'll probably open a new PR for that.

2024-01-25 12:40 UTC, x17jiri commented
@scottmcm Sure. I don't yet have too much experience with the code and sometimes I tend to underestimate the size of a change. So I may push back later :-)

2024-01-29 13:49 UTC, oli-obk requested changes

2024-01-29 13:49 UTC, oli-obk commented on compiler/rustc_mir_build/src/build/matches/mod.rs
> +                    },
This deserves a comment so future readers don't have to figure out the recursive function behaviour again

2024-01-29 13:49 UTC, oli-obk commented on compiler/rustc_mir_build/src/build/matches/mod.rs
> +                            },
comment

2024-01-29 13:49 UTC, oli-obk commented on compiler/rustc_mir_build/src/build/matches/mod.rs
> +                            cold_branch.and_then(|b| Some(!b)),
needs a comment

2024-02-03 09:29 UTC, x17jiri commented
@oli-obk I added the comments. Note that I also opened a second PR to fix likely and unlikely ( https://github.com/rust-lang/rust/pull/120370 ). If it is accepted, I would rebase and reuse the backend change.

2024-02-21 13:49 UTC, Dylan-DPC commented
Marking this as blocked on #120370

2024-11-19 05:06 UTC, x17jiri commented
This should be unblocked now that #120370 is merged.

With how #120370 evolved, the following code  suggested by the current PR:

```rust
match x {
    #[cold] true => { ... }
    _ => { ... }
}
```

can now be written as either:

```rust
match unlikely(x) {
    true => { ... }
    _ => { ... }
}
```

or

```rust
match x {
    true => { cold_path(); ... }
    _ => { ... }
}
```

The question now is whether having attribute brings any additional value or not. If yes, I could reimplement this PR to put `cold_path()` as the first thing in arms marked with `#[cold]`. If not, we can probably close this.

2025-02-01 10:45 UTC, Dylan-DPC commented
@x17jiri this is no longer blocked so you can resolve the conflicts and we can push this forward

2025-02-03 06:44 UTC, x17jiri commented
@Dylan-DPC Sure, I can update this to emit `cold_path()` call as the first thing in `#[cold]` match arms.

There is no decision from the lang team yet regarding this feature, right?

2025-02-03 12:28 UTC, Dylan-DPC commented
Marked this as waiting on team. Till then can you remove the merge commit and rebase instead? thanks

2025-02-09 13:03 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/13225853001/job/36916614978) [(plain)](https://github.com/rust-lang/rust/commit/f1920f42fc94a71623b33545f59eb64964c851f8/checks/36916614978/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
info: removing rustup binaries
info: rustup is uninstalled
##[group]Image checksum input
mingw-check-tidy
# We use the ghcr base image because ghcr doesn't have a rate limit
# and the mingw-check-tidy job doesn't cache docker images in CI.
FROM ghcr.io/rust-lang/ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
  g++ \
  make \
---

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py,cpp
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#12 2.774 Building wheels for collected packages: reuse
#12 2.775   Building wheel for reuse (pyproject.toml): started
#12 2.988   Building wheel for reuse (pyproject.toml): finished with status 'done'
#12 2.989   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132719 sha256=be6760d5849de4a58bbe52b85ca57a55f2b32b518b17029a5ad2e530db0d4303
#12 2.989   Stored in directory: /tmp/pip-ephem-wheel-cache-k7jeamlg/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#12 2.992 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#12 3.395 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#12 3.395 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#12 3.933 Collecting virtualenv
#12 3.933 Collecting virtualenv
#12 3.971   Downloading virtualenv-20.29.1-py3-none-any.whl (4.3 MB)
#12 4.064      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 47.1 MB/s eta 0:00:00
#12 4.120 Collecting platformdirs<5,>=3.9.1
#12 4.123   Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
#12 4.159 Collecting filelock<4,>=3.12.2
#12 4.183 Collecting distlib<1,>=0.3.7
#12 4.186   Downloading distlib-0.3.9-py2.py3-none-any.whl (468 kB)
#12 4.195      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 66.8 MB/s eta 0:00:00
#12 4.195      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 66.8 MB/s eta 0:00:00
#12 4.277 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#12 4.463 Successfully installed distlib-0.3.9 filelock-3.17.0 platformdirs-4.3.6 virtualenv-20.29.1
#12 DONE 4.6s

#13 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#13 DONE 0.0s
---
DirectMap4k:      128960 kB
DirectMap2M:     7211008 kB
DirectMap1G:    11534336 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py,cpp
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py,cpp
    Finished `dev` profile [unoptimized] target(s) in 0.05s
##[endgroup]
WARN: currently no CI rustc builds have rustc debug assertions enabled. Please either set `rust.debug-assertions` to `false` if you want to use download CI rustc or set `rust.download-rustc` to `false`.
downloading https://static.rust-lang.org/dist/2025-01-08/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz
---
fmt check
fmt: checked 5834 files
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/compiler/rustc_mir_build/src/builder/matches/mod.rs:470: TODO is used for tasks that should be done before merging a PR; If you want to leave a message in the codebase use FIXME
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10' and 'venv'
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10' and 'virtualenv'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (24.3.1)
  Downloading pip-25.0-py3-none-any.whl.metadata (3.7 kB)
Downloading pip-25.0-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 40.2 MB/s eta 0:00:00
Installing collected packages: pip
---
All checks passed!
checking python file formatting
28 files already formatted
checking C++ file formatting
some tidy checks failed
Command has failed. Rerun with -v to see more details.
  local time: Sun Feb  9 13:03:18 UTC 2025
  network time: Sun, 09 Feb 2025 13:03:18 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2025-02-09 15:00 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/13226706796/job/36918472508) [(plain)](https://github.com/rust-lang/rust/commit/5ec675000db024b8a45729469fbbe8fa4e856179/checks/36918472508/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#21 exporting to docker image format
#21 sending tarball 28.1s done
#21 DONE 33.4s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
---- [ui] tests/ui/thir-print/thir-tree-match.rs stdout ----
Saved the actual stdout to "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/thir-print/thir-tree-match/thir-tree-match.stdout"
diff of stdout:

143                                                                         lint_level: Explicit(HirId(DefId(0:16 ~ thir_tree_match[fcf8]::has_match).14))
144                                                                         scope: Node(14)
145                                                                         span: $DIR/thir-tree-match.rs:17:9: 17:40 (#0)
+                                                                         is_cold: false
147                                                                     Arm {
148                                                                         pattern: 


195                                                                         lint_level: Explicit(HirId(DefId(0:16 ~ thir_tree_match[fcf8]::has_match).20))
196                                                                         scope: Node(20)
197                                                                         span: $DIR/thir-tree-match.rs:18:9: 18:32 (#0)
+                                                                         is_cold: false
199                                                                     Arm {
200                                                                         pattern: 


239                                                                         lint_level: Explicit(HirId(DefId(0:16 ~ thir_tree_match[fcf8]::has_match).26))
240                                                                         scope: Node(26)
241                                                                         span: $DIR/thir-tree-match.rs:19:9: 19:28 (#0)
+                                                                         is_cold: false
243                                                                 ]
244                                                             }



The actual stdout differed from the expected stdout.
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args thir-print/thir-tree-match.rs`

error: 1 errors occurred comparing output.
status: exit status: 0
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/thir-print/thir-tree-match.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(test,FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/thir-print/thir-tree-match" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-Zunpretty=thir-tree"
--- stdout -------------------------------
DefId(0:16 ~ thir_tree_match[fcf8]::has_match):
params: [
    Param {
        ty: Foo
        ty_span: Some(/checkout/tests/ui/thir-print/thir-tree-match.rs:15:19: 15:22 (#0))
        self_kind: None
        hir_id: Some(HirId(DefId(0:16 ~ thir_tree_match[fcf8]::has_match).1))
        param: Some( 
            Pat: {
                ty: Foo
                span: /checkout/tests/ui/thir-print/thir-tree-match.rs:15:14: 15:17 (#0)
                kind: PatKind {
                        name: "foo"
                        mode: BindingMode(No, Not)
                        mode: BindingMode(No, Not)
                        var: LocalVarId(HirId(DefId(0:16 ~ thir_tree_match[fcf8]::has_match).2))
                        ty: Foo
                        is_primary: true
                        subpattern: None
                }
            }
        )
    }
    }
]
body:
    Expr {
        ty: bool
        temp_lifetime: TempLifetime { temp_lifetime: Some(Node(28)), backwards_incompatible: None }
        span: /checkout/tests/ui/thir-print/thir-tree-match.rs:15:32: 21:2 (#0)
            Scope {
                region_scope: Node(28)
                region_scope: Node(28)
                lint_level: Explicit(HirId(DefId(0:16 ~ thir_tree_match[fcf8]::has_match).28))
                    Expr {
                        ty: bool
                        ty: bool
                        temp_lifetime: TempLifetime { temp_lifetime: Some(Node(28)), backwards_incompatible: None }
                        span: /checkout/tests/ui/thir-print/thir-tree-match.rs:15:32: 21:2 (#0)
                            Block {
                            Block {
                                targeted_by_break: false
                                span: /checkout/tests/ui/thir-print/thir-tree-match.rs:15:32: 21:2 (#0)
                                region_scope: Node(3)
                                safety_mode: Safe
                                stmts: []
                                    Expr {
                                        ty: bool
                                        ty: bool
                                        temp_lifetime: TempLifetime { temp_lifetime: Some(Node(28)), backwards_incompatible: None }
                                        span: /checkout/tests/ui/thir-print/thir-tree-match.rs:16:5: 20:6 (#0)
                                            Scope {
                                                region_scope: Node(4)
                                                region_scope: Node(4)
                                                lint_level: Explicit(HirId(DefId(0:16 ~ thir_tree_match[fcf8]::has_match).4))
                                                    Expr {
                                                        ty: bool
    [...]

2025-02-10 04:27 UTC, safinaskar commented
It seems we need https://github.com/rust-lang/rust/pull/133852 if we actually want `#[cold]` to work

2025-07-23 13:30 UTC, davidtwco reviewed
This seems reasonable to me. It's not clear to me whether this has the t-lang approval or not, will ask in the Zulip thread ([#t-lang > Allow #&#91;cold&#93; on match and if arms @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/213817-t-lang/topic/Allow.20.23.5Bcold.5D.20on.20match.20and.20if.20arms/near/530344905)).

2025-07-24 08:57 UTC, davidtwco commented
See [#t-lang > Allow #&#91;cold&#93; on match and if arms @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/213817-t-lang/topic/Allow.20.23.5Bcold.5D.20on.20match.20and.20if.20arms/near/530434101) for the process for this work to proceed.

2026-02-07 15:20 UTC, closed without merging