Experiment: track usefulness without interior mutability
rust-lang/rust pull request #120324
Opened 2024-01-24 22:46 UTC by Nadrieril

This would remove a potential footgun in r-a. Just wanna see if this kills perf

2024-01-24 22:47 UTC, Nadrieril commented
r? @ghost

2024-01-24 22:47 UTC, Nadrieril commented
@bors try @rust-timer queue

2024-01-24 22:47 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2024-01-25 00:14 UTC, rust-timer commented
Queued 09d4a121c582c90b8bff6f6018482f56ef291895 with parent 7ffc697ce10f19447c0ce338428ae4b9bc0c041c, future [comparison URL](https://perf.rust-lang.org/compare.html?start=7ffc697ce10f19447c0ce338428ae4b9bc0c041c&end=09d4a121c582c90b8bff6f6018482f56ef291895).
There are currently 0 preceding artifacts in the [queue](https://perf.rust-lang.org/status.html).
It will probably take at least ~1.2 hours until the benchmark run finishes.
<!-- rust-timer: temporary -->

2024-01-25 01:30 UTC, rust-timer commented
Finished benchmarking commit (09d4a121c582c90b8bff6f6018482f56ef291895): [comparison URL](https://perf.rust-lang.org/compare.html?start=7ffc697ce10f19447c0ce338428ae4b9bc0c041c&end=09d4a121c582c90b8bff6f6018482f56ef291895&stat=instructions:u).

### Overall result: no relevant changes - no action needed


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

@bors rollup=never
@rustbot label: -S-waiting-on-perf -perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=7ffc697ce10f19447c0ce338428ae4b9bc0c041c&end=09d4a121c582c90b8bff6f6018482f56ef291895&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=7ffc697ce10f19447c0ce338428ae4b9bc0c041c&end=09d4a121c582c90b8bff6f6018482f56ef291895&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | 4.2%  | [4.2%, 4.2%]   | 1     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -2.7% | [-2.8%, -2.7%] | 2     |
| All ❌✅ (primary)                 | -     | -              | 0     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=7ffc697ce10f19447c0ce338428ae4b9bc0c041c&end=09d4a121c582c90b8bff6f6018482f56ef291895&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 2.3% | [2.3%, 2.3%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=7ffc697ce10f19447c0ce338428ae4b9bc0c041c&end=09d4a121c582c90b8bff6f6018482f56ef291895&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 664.789s -> 665.467s (0.10%)
**Artifact size**: 308.40 MiB -> 308.41 MiB (0.00%)

2024-02-03 23:59 UTC, Nadrieril commented
r? @compiler-errors 
@rustbot ready

2024-02-07 15:16 UTC, compiler-errors requested changes
Hmm... I have mixed feelings about using address-based indexing here :|

Is there any way we could give some other kind of unique ID to all the `DeconstructedPat`s for use in tracking this state instead?

2024-02-07 15:43 UTC, Nadrieril commented
We could store a `AtomicUsize`-generated id in `DeconstructedPat`, like I do for `Constructor::Opaque`. Using the spans is tempting but fails in the presence of macros. Would you prefer that?

2024-02-07 15:44 UTC, compiler-errors commented
Yeah, spans are a no-go. They're not unique. I would prefer a real dedicated ID. Why does it need to be atomic? We don't expect it to be modified after the `DeconstructedPat` is created, right?

2024-02-07 15:49 UTC, Nadrieril commented
Oh indeed, I meant storing a `usize`, but made globally unique with a `static AtomicUsize`

2024-02-07 23:11 UTC, Nadrieril commented
@rustbot ready

2024-02-12 15:56 UTC, compiler-errors commented
@bors r+

2024-02-13 00:30 UTC, merged

2024-02-13 02:20 UTC, rust-timer commented
Finished benchmarking commit (74c3f5a146860c94ff4d179fc3bfa34f879adf41): [comparison URL](https://perf.rust-lang.org/compare.html?start=b381d3ab27f788f990551100c4425bb782d26d76&end=74c3f5a146860c94ff4d179fc3bfa34f879adf41&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=b381d3ab27f788f990551100c4425bb782d26d76&end=74c3f5a146860c94ff4d179fc3bfa34f879adf41&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=b381d3ab27f788f990551100c4425bb782d26d76&end=74c3f5a146860c94ff4d179fc3bfa34f879adf41&stat=max-rss)
This benchmark run did not return any relevant results for this metric.

### [Cycles](https://perf.rust-lang.org/compare.html?start=b381d3ab27f788f990551100c4425bb782d26d76&end=74c3f5a146860c94ff4d179fc3bfa34f879adf41&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=b381d3ab27f788f990551100c4425bb782d26d76&end=74c3f5a146860c94ff4d179fc3bfa34f879adf41&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 664.301s -> 664.029s (-0.04%)
**Artifact size**: 308.35 MiB -> 308.34 MiB (-0.01%)