Add `MAX_LEN_UTF8` and `MAX_LEN_UTF16` constants
rust-lang/rust pull request #120580
Opened 2024-02-02 15:32 UTC by HTGAzureX1212

This pull request adds the `MAX_LEN_UTF8` and `MAX_LEN_UTF16` constants as per #45795, gated behind the `char_max_len` feature.

The constants are currently applied in the `alloc`, `core` and `std` libraries.

2024-02-02 19:39 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7758103807/job/21159086843) [(plain)](https://github.com/rust-lang/rust/commit/177bcc3f7050b05b9447b73721fbad26d84ba398/checks/21159086843/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v4' (SHA:b4ffde65f46336ab88eb53be808477a3936bae11)
Download action repository 'actions/upload-artifact@v3' (SHA:a8a3f3ad30e3422c9c7b888a15615d19a852ae32)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
---
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=HTGAzureX1212
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_e71c1b11-0baf-4f5b-9a6c-d95c53b86b68
GITHUB_EVENT_NAME=pull_request
GITHUB_EVENT_NAME=pull_request
GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
GITHUB_GRAPHQL_URL=https://api.github.com/graphql
GITHUB_HEAD_REF=HTGAzureX1212/issue-45795
GITHUB_JOB=pr
GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_e71c1b11-0baf-4f5b-9a6c-d95c53b86b68
GITHUB_REF=refs/pull/120580/merge
GITHUB_REF_NAME=120580/merge
GITHUB_REF_PROTECTED=false
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=56784cc161038173ac34b3a546c232429db6b4bf
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_e71c1b11-0baf-4f5b-9a6c-d95c53b86b68
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_e71c1b11-0baf-4f5b-9a6c-d95c53b86b68
GITHUB_TRIGGERING_ACTOR=HTGAzureX1212
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/120580/merge
GITHUB_WORKFLOW_SHA=56784cc161038173ac34b3a546c232429db6b4bf
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.13/x64
---
COPY scripts/sccache.sh /scripts/
RUN sh /scripts/sccache.sh

COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt \
    && pip3 install virtualenv
COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---

#10 [5/8] COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
#10 DONE 0.0s

#11 [6/8] RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt     && pip3 install virtualenv
#11 0.696   Downloading binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
#11 0.710 Collecting boolean-py==4.0
#11 0.713   Downloading boolean.py-4.0-py3-none-any.whl (25 kB)
#11 0.726 Collecting chardet==5.1.0
---
#11 3.654 Building wheels for collected packages: reuse
#11 3.655   Building wheel for reuse (pyproject.toml): started
#11 3.985   Building wheel for reuse (pyproject.toml): finished with status 'done'
#11 3.986   Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=181117 sha256=f5f58750481f69515c2c0d1d503daf565e2565c370d07fc6aeb95fe3498b4269
#11 3.986   Stored in directory: /tmp/pip-ephem-wheel-cache-7dhz3b_d/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
#11 3.988 Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
#11 4.010   Attempting uninstall: setuptools
#11 4.011     Found existing installation: setuptools 59.6.0
#11 4.012     Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
---
#11 5.212   Downloading virtualenv-20.25.0-py3-none-any.whl (3.8 MB)
#11 5.258      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 84.4 MB/s eta 0:00:00
#11 5.305 Collecting filelock<4,>=3.12.2
#11 5.308   Downloading filelock-3.13.1-py3-none-any.whl (11 kB)
#11 5.325 Collecting distlib<1,>=0.3.7
#11 5.332   Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
#11 5.339      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 KB 89.6 MB/s eta 0:00:00
#11 5.365 Collecting platformdirs<5,>=3.9.1
#11 5.368   Downloading platformdirs-4.2.0-py3-none-any.whl (17 kB)
#11 5.452 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#11 5.612 Successfully installed distlib-0.3.8 filelock-3.13.1 platformdirs-4.2.0 virtualenv-20.25.0
#11 DONE 5.7s

#12 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#12 DONE 0.0s
---
DirectMap4k:      200640 kB
DirectMap2M:     7139328 kB
DirectMap1G:    11534336 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
    Finished dev [unoptimized] target(s) in 0.03s
##[endgroup]
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/bf3c6c5bed498f41ad815641319a1ad9bcecb8e8/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/llvm-bf3c6c5bed498f41ad815641319a1ad9bcecb8e8-true/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm
---
   Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
    Finished release [optimized] target(s) in 24.58s
##[endgroup]
fmt check
##[error]Diff in /checkout/library/alloc/src/string.rs at line 1343:
     #[stable(feature = "rust1", since = "1.0.0")]
     #[stable(feature = "rust1", since = "1.0.0")]
     pub fn push(&mut self, ch: char) {
-
         match ch.len_utf8() {
             1 => self.vec.push(ch as u8),
             _ => self.vec.extend_from_slice(ch.encode_utf8(&mut [0; MAX_LEN_UTF8]).as_bytes()),
Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/library/alloc/src/collections/binary_heap/mod.rs" "/checkout/library/alloc/src/collections/binary_heap/tests.rs" "/checkout/library/alloc/src/alloc.rs" "/checkout/library/alloc/src/rc/tests.rs" "/checkout/library/alloc/src/string.rs" "/checkout/library/alloc/src/sync.rs" "/checkout/library/proc_macro/src/lib.rs" "/checkout/library/alloc/src/collections/vec_deque/drain.rs"` failed.
If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
  local time: Fri Feb  2 19:38:58 UTC 2024
  network time: Fri, 02 Feb 2024 19:38:58 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-02-27 16:42 UTC, joshtriplett commented
In the tracking issue, please include a mention that when stabilizing this we should adjust the documentation of https://doc.rust-lang.org/std/primitive.char.html#method.encode_utf8 to use it.

2024-02-27 16:44 UTC, m-ou-se commented
We briefly discussed this in the libs-api meeting and are happy to add these as unstable. 
Please [open a tracking issue](https://github.com/rust-lang/rust/issues/new?assignees=&labels=C-tracking-issue%2C+T-libs&template=library_tracking_issue.md&title=Tracking+Issue+for+XXX) and use that in the `#[unstable]` attributes. Thanks!

2024-02-28 12:57 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8080232123/job/22076323261) [(plain)](https://github.com/rust-lang/rust/commit/2c3f9d8fd8c42efc2c3d5ecea670801f44a880bc/checks/22076323261/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=HTGAzureX1212
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_7b1f52e0-b7dd-4f17-8e2f-1aa8d43fc485
GITHUB_EVENT_NAME=pull_request
GITHUB_EVENT_NAME=pull_request
GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
GITHUB_GRAPHQL_URL=https://api.github.com/graphql
GITHUB_HEAD_REF=HTGAzureX1212/issue-45795
GITHUB_JOB=pr
GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_7b1f52e0-b7dd-4f17-8e2f-1aa8d43fc485
GITHUB_REF=refs/pull/120580/merge
GITHUB_REF_NAME=120580/merge
GITHUB_REF_PROTECTED=false
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=41760569154824187d5ff645459239ea13460725
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_7b1f52e0-b7dd-4f17-8e2f-1aa8d43fc485
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_7b1f52e0-b7dd-4f17-8e2f-1aa8d43fc485
GITHUB_TRIGGERING_ACTOR=HTGAzureX1212
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/120580/merge
GITHUB_WORKFLOW_SHA=41760569154824187d5ff645459239ea13460725
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.13/x64
---
#12 writing image sha256:4e5729a3c02a4dd6cc03dcddc76df17b7743c687502d854f02e4100fd08edb85 done
#12 naming to docker.io/library/rust-ci done
#12 DONE 10.0s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-16]
##[group]Clock drift check
  local time: Wed Feb 28 12:21:05 UTC 2024
  network time: Wed, 28 Feb 2024 12:21:05 GMT
  network time: Wed, 28 Feb 2024 12:21:05 GMT
##[endgroup]
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-16', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'build.optimized-compiler-builtins', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-16/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
##[endgroup]
Testing GCC stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling y v0.1.0 (/checkout/compiler/rustc_codegen_gcc/build_system)
    Finished release [optimized] target(s) in 1.23s
     Running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-codegen/x86_64-unknown-linux-gnu/release/y test --use-system-gcc --use-backend gcc --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc --release --no-default-features --mini-tests --std-tests`
Using system GCC
Using system GCC
[BUILD] example
[AOT] mini_core_hello_world
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc/mini_core_hello_world
abc
---
---- [run-make] tests/run-make/alloc-no-oom-handling stdout ----

error: make failed
status: exit status: 2
command: cd "/checkout/tests/run-make/alloc-no-oom-handling" && env -u CARGO_MAKEFLAGS -u MAKEFLAGS -u MFLAGS -u RUSTFLAGS AR="ar" CC="cc -ffunction-sections -fdata-sections -fPIC -m64" CXX="c++ -ffunction-sections -fdata-sections -fPIC -m64" HOST_RPATH_DIR="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" LD_LIB_PATH_ENVVAR="LD_LIBRARY_PATH" LLVM_BIN_DIR="/usr/lib/llvm-16/bin" LLVM_COMPONENTS="aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets amdgpu amdgpuasmparser amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgputargetmca amdgpuutils analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter bpf bpfasmparser bpfcodegen bpfdesc bpfdisassembler bpfinfo cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfologicalview debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker dwarflinkerparallel dwp engine executionengine extensions filecheck frontendhlsl frontendopenacc frontendopenmp fuzzercli fuzzmutate globalisel hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interfacestub interpreter ipo irprinter irreader jitlink lanai lanaiasmparser lanaicodegen lanaidesc lanaidisassembler lanaiinfo libdriver lineeditor linker loongarch loongarchasmparser loongarchcodegen loongarchdesc loongarchdisassembler loongarchinfo lto m68k m68kasmparser m68kcodegen m68kdesc m68kdisassembler m68kinfo mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts objcopy object objectyaml option orcjit orcshared orctargetprocess passes perfjitevents powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo riscvtargetmca runtimedyld scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target targetparser textapi transformutils ve veasmparser vecodegen vectorize vedesc vedisassembler veinfo webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo webassemblyutils windowsdriver windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info x86targetmca xcore xcorecodegen xcoredesc xcoredisassembler xcoreinfo xray" LLVM_FILECHECK="/usr/lib/llvm-16/bin/FileCheck" NODE="/usr/bin/node" PYTHON="/usr/bin/python3" RUSTC="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" RUSTDOC="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc" RUST_BUILD_STAGE="stage2-x86_64-unknown-linux-gnu" S="/checkout" TARGET="x86_64-unknown-linux-gnu" TARGET_RPATH_DIR="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" TMPDIR="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/alloc-no-oom-handling/alloc-no-oom-handling" "make"
--- stdout -------------------------------
LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/alloc-no-oom-handling/alloc-no-oom-handling:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" '/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc' --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/alloc-no [...]

2024-05-06 12:14 UTC, HTGAzureX1212 commented
@rustbot ready

2024-06-22 21:59 UTC, clarfonthey commented
Small question: why are these constants in the `char` module instead of being associated constants on the `char` type?

2024-06-23 22:39 UTC, GrigorenkoPV commented
> Small question: why are these constants in the `char` module instead of being associated constants on the `char` type? The initial proposal is from 2017 when presumably this wasn't possible, but now that it is, we should probably make them associated constants instead to avoid having to duplicate across multiple modules.

From what I can tell, in this PR they are added as associated constants on `char`-the-type and then also reexported in `char`-the-module.

2024-06-24 00:58 UTC, clarfonthey commented
Oh, I completely missed that point. I personally wouldn't add module exports since that way there's just one way to access them.

2024-09-01 05:57 UTC, vcfxb approved these changes

2024-11-20 17:09 UTC, joshtriplett commented
Observation: we still don't support importing associated constants in order to use them unqualified, and these seem like the kinds of things people might want to import and use unqualified.

Until we support importing associated constants, I think we should add these as both. We can always deprecate the module constants in the future when we do add that support.

2024-11-26 16:46 UTC, m-ou-se approved these changes
We briefly discussed this in the libs-api meeting. This can be merged after rebasing.

2024-11-26 16:48 UTC, joshtriplett commented
Recording an observation from a discussion in a meeting: I found `MAX_LEN_UTF16` misleading, as I would have expected "number of bytes" rather than "number of 16-bit words".

This isn't a blocking objection, on the basis that anytime I'm using UTF-16 I'm *already* having a bad time, so this doesn't make it that much worse. I just hope that nobody ever uses this to size e.g. a buffer for a `read` call and ends up with the wrong buffer length.

2025-02-03 14:17 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/13115406184/job/36588417399) [(plain)](https://github.com/rust-lang/rust/commit/6a78bb43d9b2c8530a381cdc8127138268e8ea4a/checks/36588417399/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#21 exporting to docker image format
#21 sending tarball 28.8s done
#21 DONE 42.0s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
    |                                       ^^ undeclared lifetime
    |
help: consider introducing lifetime `'a` here
    |
565 |     fn into_searcher<'a>(self, haystack: &'a str) -> Self::Searcher {
help: consider introducing lifetime `'a` here
    |
561 | impl<'a> Pattern for char {
    |     ++++
---
    |
note: associated type defined here, with 1 lifetime parameter: `'a`
   --> library/core/src/str/pattern.rs:102:10
    |
102 |     type Searcher<'a>: Searcher<'a>;
help: add missing lifetime argument
    |
    |
565 |     fn into_searcher(self, haystack: &'a str) -> Self::Searcher<'a> {

Some errors have detailed explanations: E0107, E0252, E0261.
For more information about an error, try `rustc --explain E0107`.
error: could not compile `core` (lib) due to 4 previous errors
```

</details>

2025-02-16 09:09 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/13353534902/job/37293153887) [(plain)](https://github.com/rust-lang/rust/commit/bb0fe4ebe5be3bb6abafbc68a0e93cf2aed36182/checks/37293153887/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling compiler_builtins v0.1.146
error[E0261]: use of undeclared lifetime name `'a`
   --> library/core/src/str/pattern.rs:565:39
    |
565 |     fn into_searcher(self, haystack: &'a str) -> Self::Searcher<'a> {
    |                                       ^^ undeclared lifetime
help: consider introducing lifetime `'a` here
    |
    |
565 |     fn into_searcher<'a>(self, haystack: &'a str) -> Self::Searcher<'a> {
help: consider introducing lifetime `'a` here
    |
    |
561 | impl<'a, 's> Pattern for char {

error[E0261]: use of undeclared lifetime name `'a`
   --> library/core/src/str/pattern.rs:565:65
    |
    |
565 |     fn into_searcher(self, haystack: &'a str) -> Self::Searcher<'a> {
    |                                                                 ^^ undeclared lifetime
help: consider introducing lifetime `'a` here
    |
    |
565 |     fn into_searcher<'a>(self, haystack: &'a str) -> Self::Searcher<'a> {
help: consider introducing lifetime `'a` here
    |
    |
561 | impl<'a, 's> Pattern for char {


error: lifetime parameter `'s` never used
    |
    |
561 | impl<'s> Pattern for char {
    |     -^^- help: elide the unused lifetime
    = note: `-D unused-lifetimes` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(unused_lifetimes)]`

For more information about this error, try `rustc --explain E0261`.
```

</details>

2025-02-16 09:21 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/13353638721/job/37293367138) [(plain)](https://github.com/rust-lang/rust/commit/1ba7050ef1234d70e7e10c39f4052900ae2f96b4/checks/37293367138/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling object v0.36.7
   Compiling std v0.0.0 (/checkout/library/std)
   Compiling cc v1.2.0
   Compiling compiler_builtins v0.1.146
error[E0496]: lifetime name `'a` shadows a lifetime name that is already in scope
    |
561 | impl<'a> Pattern for char {
    |      -- first declared here
    |      -- first declared here
562 |     type Searcher<'a> = CharSearcher<'a>;
    |                   ^^ lifetime `'a` already in scope

error[E0496]: lifetime name `'a` shadows a lifetime name that is already in scope
    |
561 | impl<'a> Pattern for char {
    |      -- first declared here
...
...
604 |     fn is_suffix_of<'a>(self, haystack: &'a str) -> bool
    |                     ^^ lifetime `'a` already in scope

error[E0496]: lifetime name `'a` shadows a lifetime name that is already in scope
    |
561 | impl<'a> Pattern for char {
    |      -- first declared here
...
...
612 |     fn strip_suffix_of<'a>(self, haystack: &'a str) -> Option<&'a str>
    |                        ^^ lifetime `'a` already in scope
error: lifetime parameter `'a` never used
   --> library/core/src/str/pattern.rs:604:21
    |
    |
604 |     fn is_suffix_of<'a>(self, haystack: &'a str) -> bool
    |                    -^^- help: elide the unused lifetime
    = note: `-D unused-lifetimes` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(unused_lifetimes)]`

error: lifetime parameter `'a` never used
error: lifetime parameter `'a` never used
   --> library/core/src/str/pattern.rs:612:24
    |
612 |     fn strip_suffix_of<'a>(self, haystack: &'a str) -> Option<&'a str>
    |                       -^^- help: elide the unused lifetime
error[E0207]: the lifetime parameter `'a` is not constrained by the impl trait, self type, or predicates
   --> library/core/src/str/pattern.rs:561:6
    |
561 | impl<'a> Pattern for char {
561 | impl<'a> Pattern for char {
    |      ^^ unconstrained lifetime parameter

error: implementation of `ReverseSearcher` is not general enough
  --> library/core/src/fmt/builders.rs:37:37
   |
37 |             self.state.on_newline = s.ends_with('\n');
   |                                     ^^^^^^^^^^^^^^^^^ implementation of `ReverseSearcher` is not general enough
   |
   = note: `ReverseSearcher<'0>` would have to be implemented for the type `CharSearcher<'_>`, for any lifetime `'0`...
   = note: ...but `ReverseSearcher<'1>` is actually implemented for the type `CharSearcher<'1>`, for some specific lifetime `'1`
error: implementation of `ReverseSearcher` is not general enough
    --> library/core/src/str/mod.rs:2996:26
     |
     |
2996 |         let Some(line) = line.strip_suffix('\n') else { return line };
     |                          ^^^^^^^^^^^^^^^^^^^^^^^ implementation of `ReverseSearcher` is not general enough
     |
     = note: `ReverseSearcher<'0>` would have to be implemented for the type `CharSearcher<'_>`, for any lifetime `'0`...
     = note: ...but `ReverseSearcher<'1>` is actually implemented for the type `CharSearcher<'1>`, for some specific lifetime `'1`
error: implementation of `ReverseSearcher` is not general enough
    --> library/core/src/str/mod.rs:2997:26
     |
     |
2997 |         let Some(line) = line.strip_suffix('\r') else { return line };
     |                          ^^^^^^^^^^^^^^^^^^^^^^^ implementation of `ReverseSearcher` is not general enough
     |
     = note: `ReverseSearcher<'0>` would have to be implemented for the type `CharSearcher<'_>`, for any lifetime `'0`...
     = note: ...but `ReverseSearcher<'1>` is actually implemented for the type `CharSearcher<'1>`, for some specific lifetime `'1`
Some errors have detailed explanations: E0207, E0496.
For more information about an error, try `rustc --explain E0207`.
error: could not compile `core` (lib) due to 9 previous errors
Build completed unsuccessfully in 0:00:40
```

</details>

2025-02-16 09:34 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/13353710792/job/37293522133) [(plain)](https://github.com/rust-lang/rust/commit/d64d7d4b9e8d11adf66f8d354c93be77846e0ccc/checks/37293522133/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
info: removing rustup binaries
info: rustup is uninstalled
##[group]Image checksum input
mingw-check-tidy
# We use the ghcr base image because ghcr doesn't have a rate limit
# and the mingw-check-tidy job doesn't cache docker images in CI.
FROM ghcr.io/rust-lang/ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
  g++ \
  make \
---

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py,cpp
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#12 2.841 Building wheels for collected packages: reuse
#12 2.842   Building wheel for reuse (pyproject.toml): started
#12 3.055   Building wheel for reuse (pyproject.toml): finished with status 'done'
#12 3.056   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132717 sha256=cf8e90b4c31488819897086c9a177a392752824492f0f754021598cc8dbde519
#12 3.056   Stored in directory: /tmp/pip-ephem-wheel-cache-bqdb5k13/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#12 3.059 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#12 3.471 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#12 3.472 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#12 4.010 Collecting virtualenv
#12 4.010 Collecting virtualenv
#12 4.066   Downloading virtualenv-20.29.2-py3-none-any.whl (4.3 MB)
#12 4.250      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 23.6 MB/s eta 0:00:00
#12 4.309 Collecting platformdirs<5,>=3.9.1
#12 4.321   Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
#12 4.362 Collecting filelock<4,>=3.12.2
#12 4.391 Collecting distlib<1,>=0.3.7
#12 4.398   Downloading distlib-0.3.9-py2.py3-none-any.whl (468 kB)
#12 4.410      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 43.9 MB/s eta 0:00:00
#12 4.410      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 43.9 MB/s eta 0:00:00
#12 4.492 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#12 4.676 Successfully installed distlib-0.3.9 filelock-3.17.0 platformdirs-4.3.6 virtualenv-20.29.2
#12 DONE 4.8s

#13 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#13 DONE 0.0s
---
DirectMap4k:      120768 kB
DirectMap2M:     7219200 kB
DirectMap1G:    11534336 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py,cpp
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py,cpp
    Finished `dev` profile [unoptimized] target(s) in 0.05s
##[endgroup]
WARN: currently no CI rustc builds have rustc debug assertions enabled. Please either set `rust.debug-assertions` to `false` if you want to use download CI rustc or set `rust.download-rustc` to `false`.
downloading https://static.rust-lang.org/dist/2025-02-08/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz
---
Diff in /checkout/library/std/src/sys_common/wtf8.rs:18:
 #[cfg(test)]
 mod tests;
 
-use core::char::{encode_utf16_raw, encode_utf8_raw, MAX_LEN_UTF16, MAX_LEN_UTF8};
+use core::char::{MAX_LEN_UTF8, MAX_LEN_UTF16, encode_utf8_raw, encode_utf16_raw};
 use core::clone::CloneToUninit;
 
fmt: checked 5843 files
Build completed unsuccessfully in 0:01:11
  local time: Sun Feb 16 09:34:42 UTC 2025
```

</details>

2025-02-16 10:23 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/13354035269/job/37294306684) [(plain)](https://github.com/rust-lang/rust/commit/fda9b535f918606c0e3179bcfd3933864f26d6cb/checks/37294306684/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
info: removing rustup binaries
info: rustup is uninstalled
##[group]Image checksum input
mingw-check-tidy
# We use the ghcr base image because ghcr doesn't have a rate limit
# and the mingw-check-tidy job doesn't cache docker images in CI.
FROM ghcr.io/rust-lang/ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
  g++ \
  make \
---

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py,cpp
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#12 3.230 Building wheels for collected packages: reuse
#12 3.231   Building wheel for reuse (pyproject.toml): started
#12 3.445   Building wheel for reuse (pyproject.toml): finished with status 'done'
#12 3.446   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132717 sha256=cf8e90b4c31488819897086c9a177a392752824492f0f754021598cc8dbde519
#12 3.446   Stored in directory: /tmp/pip-ephem-wheel-cache-jikmc9wh/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#12 3.449 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#12 3.861 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#12 3.861 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#12 4.418 Collecting virtualenv
#12 4.418 Collecting virtualenv
#12 4.479   Downloading virtualenv-20.29.2-py3-none-any.whl (4.3 MB)
#12 4.747      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 16.1 MB/s eta 0:00:00
#12 4.813 Collecting platformdirs<5,>=3.9.1
#12 4.823   Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
#12 4.848 Collecting distlib<1,>=0.3.7
#12 4.875      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 31.7 MB/s eta 0:00:00
#12 4.919 Collecting filelock<4,>=3.12.2
#12 4.929   Downloading filelock-3.17.0-py3-none-any.whl (16 kB)
#12 4.929   Downloading filelock-3.17.0-py3-none-any.whl (16 kB)
#12 5.012 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#12 5.194 Successfully installed distlib-0.3.9 filelock-3.17.0 platformdirs-4.3.6 virtualenv-20.29.2
#12 DONE 5.3s

#13 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#13 DONE 0.0s
---
DirectMap4k:      120768 kB
DirectMap2M:     5122048 kB
DirectMap1G:    13631488 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py,cpp
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py,cpp
    Finished `dev` profile [unoptimized] target(s) in 0.05s
##[endgroup]
WARN: currently no CI rustc builds have rustc debug assertions enabled. Please either set `rust.debug-assertions` to `false` if you want to use download CI rustc or set `rust.download-rustc` to `false`.
downloading https://static.rust-lang.org/dist/2025-02-08/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz
---
fmt check
fmt: checked 5843 files
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/library/alloc/src/string.rs:590: trailing whitespace
##[error]tidy error: /checkout/library/coretests/tests/lib.rs:19: line not in alphabetical order
##[error]tidy error: /checkout/library/coretests/tests/lib.rs:21: line not in alphabetical order
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10' and 'venv'
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10' and 'virtualenv'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (25.0.1)
All checks passed!
checking python file formatting
28 files already formatted
checking C++ file formatting
checking C++ file formatting
some tidy checks failed
Command has failed. Rerun with -v to see more details.
  local time: Sun Feb 16 10:23:04 UTC 2025
  network time: Sun, 16 Feb 2025 10:23:05 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2025-02-16 11:08 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/13354344718/job/37294994159) [(plain)](https://github.com/rust-lang/rust/commit/8c1af110451a41c4597c355f33efa324d94eb766/checks/37294994159/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
info: removing rustup binaries
info: rustup is uninstalled
##[group]Image checksum input
mingw-check-tidy
# We use the ghcr base image because ghcr doesn't have a rate limit
# and the mingw-check-tidy job doesn't cache docker images in CI.
FROM ghcr.io/rust-lang/ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
  g++ \
  make \
---

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py,cpp
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#12 3.158 Building wheels for collected packages: reuse
#12 3.159   Building wheel for reuse (pyproject.toml): started
#12 3.371   Building wheel for reuse (pyproject.toml): finished with status 'done'
#12 3.372   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132717 sha256=cf8e90b4c31488819897086c9a177a392752824492f0f754021598cc8dbde519
#12 3.372   Stored in directory: /tmp/pip-ephem-wheel-cache-h9ocymi8/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#12 3.375 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#12 3.779 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#12 3.779 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#12 4.324 Collecting virtualenv
#12 4.324 Collecting virtualenv
#12 4.424   Downloading virtualenv-20.29.2-py3-none-any.whl (4.3 MB)
#12 4.694      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 16.0 MB/s eta 0:00:00
#12 4.758 Collecting platformdirs<5,>=3.9.1
#12 4.769   Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
#12 4.814 Collecting filelock<4,>=3.12.2
#12 4.849 Collecting distlib<1,>=0.3.7
#12 4.859   Downloading distlib-0.3.9-py2.py3-none-any.whl (468 kB)
#12 4.876      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 30.4 MB/s eta 0:00:00
#12 4.876      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 30.4 MB/s eta 0:00:00
#12 4.956 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#12 5.141 Successfully installed distlib-0.3.9 filelock-3.17.0 platformdirs-4.3.6 virtualenv-20.29.2
#12 DONE 5.2s

#13 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#13 DONE 0.0s
---
DirectMap4k:      126912 kB
DirectMap2M:     6164480 kB
DirectMap1G:    12582912 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py,cpp
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py,cpp
    Finished `dev` profile [unoptimized] target(s) in 0.05s
##[endgroup]
WARN: currently no CI rustc builds have rustc debug assertions enabled. Please either set `rust.debug-assertions` to `false` if you want to use download CI rustc or set `rust.download-rustc` to `false`.
downloading https://static.rust-lang.org/dist/2025-02-08/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz
---
fmt check
fmt: checked 5843 files
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/library/coretests/tests/lib.rs:20: line not in alphabetical order
##[error]tidy error: /checkout/library/coretests/tests/lib.rs:21: line not in alphabetical order
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10' and 'venv'
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10' and 'virtualenv'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (25.0.1)
All checks passed!
checking python file formatting
28 files already formatted
checking C++ file formatting
checking C++ file formatting
some tidy checks failed
Command has failed. Rerun with -v to see more details.
  local time: Sun Feb 16 11:08:13 UTC 2025
  network time: Sun, 16 Feb 2025 11:08:13 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2025-02-16 11:23 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/13354472029/job/37295286036) [(plain)](https://github.com/rust-lang/rust/commit/7786d80d0256622be2b8081d6401a479f1cb8250/checks/37295286036/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
info: removing rustup binaries
info: rustup is uninstalled
##[group]Image checksum input
mingw-check-tidy
# We use the ghcr base image because ghcr doesn't have a rate limit
# and the mingw-check-tidy job doesn't cache docker images in CI.
FROM ghcr.io/rust-lang/ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
  g++ \
  make \
---

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py,cpp
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#12 2.656 Building wheels for collected packages: reuse
#12 2.657   Building wheel for reuse (pyproject.toml): started
#12 2.862   Building wheel for reuse (pyproject.toml): finished with status 'done'
#12 2.863   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132717 sha256=cf8e90b4c31488819897086c9a177a392752824492f0f754021598cc8dbde519
#12 2.863   Stored in directory: /tmp/pip-ephem-wheel-cache-daj56g6f/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#12 2.865 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#12 3.254 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#12 3.254 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#12 3.761 Collecting virtualenv
#12 3.761 Collecting virtualenv
#12 3.800   Downloading virtualenv-20.29.2-py3-none-any.whl (4.3 MB)
#12 3.856      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 79.2 MB/s eta 0:00:00
#12 3.911 Collecting platformdirs<5,>=3.9.1
#12 3.915   Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
#12 3.952 Collecting filelock<4,>=3.12.2
#12 3.975 Collecting distlib<1,>=0.3.7
#12 3.979   Downloading distlib-0.3.9-py2.py3-none-any.whl (468 kB)
#12 3.986      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 93.4 MB/s eta 0:00:00
#12 3.986      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 93.4 MB/s eta 0:00:00
#12 4.067 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#12 4.247 Successfully installed distlib-0.3.9 filelock-3.17.0 platformdirs-4.3.6 virtualenv-20.29.2
#12 DONE 4.3s

#13 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#13 DONE 0.0s
---
DirectMap4k:      116672 kB
DirectMap2M:     4077568 kB
DirectMap1G:    14680064 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py,cpp
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py,cpp
    Finished `dev` profile [unoptimized] target(s) in 0.05s
##[endgroup]
WARN: currently no CI rustc builds have rustc debug assertions enabled. Please either set `rust.debug-assertions` to `false` if you want to use download CI rustc or set `rust.download-rustc` to `false`.
downloading https://static.rust-lang.org/dist/2025-02-08/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz
---
fmt check
fmt: checked 5845 files
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/library/coretests/tests/lib.rs:19: line not in alphabetical order
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10' and 'venv'
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10' and 'virtualenv'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (25.0.1)
All checks passed!
checking python file formatting
28 files already formatted
checking C++ file formatting
checking C++ file formatting
some tidy checks failed
Command has failed. Rerun with -v to see more details.
  local time: Sun Feb 16 11:23:21 UTC 2025
  network time: Sun, 16 Feb 2025 11:23:21 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2025-02-16 12:33 UTC, HTGAzureX1212 commented
@rustbot ready

2025-02-16 12:46 UTC, GrigorenkoPV requested changes

2025-02-20 02:38 UTC, merged