Provide suggestions through `rustc_confusables` annotations
rust-lang/rust pull request #120730
Opened 2024-02-07 05:14 UTC by estebank

Help with common API confusion, like asking for `push` when the data structure really has `append`.

```
error[E0599]: no method named `size` found for struct `Vec<{integer}>` in the current scope
  --> $DIR/rustc_confusables_std_cases.rs:17:7
   |
LL |     x.size();
   |       ^^^^
   |
help: you might have meant to use `len`
   |
LL |     x.len();
   |       ~~~
help: there is a method with a similar name
   |
LL |     x.resize();
   |       ~~~~~~
```

Fix #59450 (we can open subsequent tickets for specific cases).

Fix #108437:

```
error[E0599]: `Option<{integer}>` is not an iterator
   --> f101.rs:3:9
    |
3   |     opt.flat_map(|val| Some(val));
    |         ^^^^^^^^ `Option<{integer}>` is not an iterator
    |
   ::: /home/gh-estebank/rust/library/core/src/option.rs:571:1
    |
571 | pub enum Option<T> {
    | ------------------ doesn't satisfy `Option<{integer}>: Iterator`
    |
    = note: the following trait bounds were not satisfied:
            `Option<{integer}>: Iterator`
            which is required by `&mut Option<{integer}>: Iterator`
help: you might have meant to use `and_then`
    |
3   |     opt.and_then(|val| Some(val));
    |         ~~~~~~~~
```

On type error of method call arguments, look at confusables for suggestion. Fix #87212:

```
error[E0308]: mismatched types
    --> f101.rs:8:18
     |
8    |     stuff.append(Thing);
     |           ------ ^^^^^ expected `&mut Vec<Thing>`, found `Thing`
     |           |
     |           arguments to this method are incorrect
     |
     = note: expected mutable reference `&mut Vec<Thing>`
                           found struct `Thing`
note: method defined here
    --> /home/gh-estebank/rust/library/alloc/src/vec/mod.rs:2025:12
     |
2025 |     pub fn append(&mut self, other: &mut Self) {
     |            ^^^^^^
help: you might have meant to use `push`
     |
8    |     stuff.push(Thing);
     |           ~~~~
```

2024-02-10 05:00 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7852395762/job/21430726853) [(plain)](https://github.com/rust-lang/rust/commit/d7868c4114b2b7c145b726e09c4d8406ed272057/checks/21430726853/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#12 writing image sha256:1a66c4b7ef699b76ecf3fbdd586757cb66723387f0f3d81eb0ed357e72479d67 done
#12 naming to docker.io/library/rust-ci done
#12 DONE 10.1s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-16]
##[group]Clock drift check
  local time: Sat Feb 10 03:43:40 UTC 2024
  network time: Sat, 10 Feb 2024 03:43:41 GMT
  network time: Sat, 10 Feb 2024 03:43:41 GMT
##[endgroup]
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-16', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'build.optimized-compiler-builtins', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-16/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
##[endgroup]
Testing GCC stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling y v0.1.0 (/checkout/compiler/rustc_codegen_gcc/build_system)
    Finished release [optimized] target(s) in 1.45s
     Running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-codegen/x86_64-unknown-linux-gnu/release/y test --use-system-gcc --use-backend gcc --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc --release --no-default-features --mini-tests --std-tests`
Using system GCC
Using system GCC
[BUILD] example
[AOT] mini_core_hello_world
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc/mini_core_hello_world
abc
---

---- [ui] tests/ui/atomic-from-mut-not-available.rs stdout ----
diff of stderr:

7 note: if you're trying to build a new `AtomicU64`, consider using `AtomicU64::new` which returns `AtomicU64`
8   --> $SRC_DIR/core/src/sync/atomic.rs:LL:COL
+ help: there is an associated function with a similar name
+    |
+ LL |     core::sync::atomic::AtomicU64::from(&mut 0u64);
+    |                                    ~~~~
---
LL |     core::sync::atomic::AtomicU64::from_mut(&mut 0u64);
Build completed unsuccessfully in 0:03:05
   |                                    ^^^^^^^^ function or associated item not found in `AtomicU64`
   |
note: if you're trying to build a new `AtomicU64`, consider using `AtomicU64::new` which returns `AtomicU64`
  --> /rustc/FAKE_PREFIX/library/core/src/sync/atomic.rs:3137:1
help: there is an associated function with a similar name
   |
LL |     core::sync::atomic::AtomicU64::from(&mut 0u64);
   |                                    ~~~~
```

</details>

2024-02-12 19:22 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7875941877/job/21488950712) [(plain)](https://github.com/rust-lang/rust/commit/149b73eef9fbabbf67149d14a53e409ba5fd8409/checks/21488950712/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#12 writing image sha256:b95adedd6fcd72947b34857e5921b8be24b0cc3037f26a906e9735d47650fcd4 done
#12 naming to docker.io/library/rust-ci done
#12 DONE 10.2s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-16]
##[group]Clock drift check
  local time: Mon Feb 12 18:03:06 UTC 2024
  network time: Mon, 12 Feb 2024 18:03:06 GMT
  network time: Mon, 12 Feb 2024 18:03:06 GMT
##[endgroup]
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-16', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'build.optimized-compiler-builtins', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-16/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
##[endgroup]
Testing GCC stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling y v0.1.0 (/checkout/compiler/rustc_codegen_gcc/build_system)
    Finished release [optimized] target(s) in 1.42s
     Running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-codegen/x86_64-unknown-linux-gnu/release/y test --use-system-gcc --use-backend gcc --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc --release --no-default-features --mini-tests --std-tests`
Using system GCC
Using system GCC
[BUILD] example
[AOT] mini_core_hello_world
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc/mini_core_hello_world
abc
---

---- [ui] tests/ui/atomic-from-mut-not-available.rs stdout ----
diff of stderr:

7 note: if you're trying to build a new `AtomicU64`, consider using `AtomicU64::new` which returns `AtomicU64`
8   --> $SRC_DIR/core/src/sync/atomic.rs:LL:COL
-  help: there is an associated function with a similar name
-     |
-  LL |     core::sync::atomic::AtomicU64::from(&mut 0u64);
-     |                                    ~~~~   
---
   |
LL |     core::sync::atomic::AtomicU64::from_mut(&mut 0u64);
   |                                    ^^^^^^^^ function or associated item not found in `AtomicU64`
   |
note: if you're trying to build a new `AtomicU64`, consider using `AtomicU64::new` which returns `AtomicU64`
  --> /rustc/FAKE_PREFIX/library/core/src/sync/atomic.rs:3150:1
help: there is an associated function with a similar name
   |
LL |     core::sync::atomic::AtomicU64::from(&mut 0u64);
   |                                    ~~~~
```

</details>

2024-02-12 21:15 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/7877178949/job/21492804428) [(plain)](https://github.com/rust-lang/rust/commit/566030039239305abe6d970a6069cbf892bcec5b/checks/21492804428/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#12 writing image sha256:0e2faf8d93475608eafe474daec95e141ffc09f473241f8580f01e0cfac7ba35 done
#12 naming to docker.io/library/rust-ci done
#12 DONE 10.1s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-16]
##[group]Clock drift check
  local time: Mon Feb 12 19:58:56 UTC 2024
  network time: Mon, 12 Feb 2024 19:58:56 GMT
  network time: Mon, 12 Feb 2024 19:58:56 GMT
##[endgroup]
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-16', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'build.optimized-compiler-builtins', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-16/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
##[endgroup]
Testing GCC stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
   Compiling y v0.1.0 (/checkout/compiler/rustc_codegen_gcc/build_system)
    Finished release [optimized] target(s) in 1.40s
     Running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-codegen/x86_64-unknown-linux-gnu/release/y test --use-system-gcc --use-backend gcc --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc --release --no-default-features --mini-tests --std-tests`
Using system GCC
Using system GCC
[BUILD] example
[AOT] mini_core_hello_world
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc/mini_core_hello_world
abc
---

---- [ui] tests/ui/atomic-from-mut-not-available.rs stdout ----
diff of stderr:

7 note: if you're trying to build a new `AtomicU64`, consider using `AtomicU64::new` which returns `AtomicU64`
8   --> $SRC_DIR/core/src/sync/atomic.rs:LL:COL
+ help: there is an associated function with a similar name
+    |
+ LL |     core::sync::atomic::AtomicU64::from(&mut 0u64);
+    |                                    ~~~~
---
LL |     core::sync::atomic::AtomicU64::from_mut(&mut 0u64);
Build completed unsuccessfully in 0:03:05
   |                                    ^^^^^^^^ function or associated item not found in `AtomicU64`
   |
note: if you're trying to build a new `AtomicU64`, consider using `AtomicU64::new` which returns `AtomicU64`
  --> /rustc/FAKE_PREFIX/library/core/src/sync/atomic.rs:3150:1
help: there is an associated function with a similar name
   |
LL |     core::sync::atomic::AtomicU64::from(&mut 0u64);
   |                                    ~~~~
```

</details>

2024-02-13 23:07 UTC, estebank commented
r? @oli-obk

2024-02-14 01:55 UTC, chenyukang commented
Fixes #87212

2024-02-14 02:09 UTC, chenyukang commented
can you also add a annotation for #108437

2024-02-14 16:05 UTC, estebank commented
@chenyukang added :)

2024-02-14 16:24 UTC, oli-obk requested changes
whoops started reviewing this and got distracted. Will do another round tomorrow

2024-02-14 18:41 UTC, oli-obk commented on compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs
> +                return Some(name);
Afaict the return value is never used

2024-02-15 17:22 UTC, oli-obk commented
@bors r+

2024-02-17 00:21 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/7937658973/job/21675262121) [(plain)](https://github.com/rust-lang-ci/rust/commit/f2d94c93329636cdb388b219512b9aea10707711/checks/21675262121/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

---- [ui] tests/ui/impl-trait/where-allowed.rs stdout ----
diff of stderr:

401 LL |     vec![vec![0; 10], vec![12; 7], vec![8; 3]]
402    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `[_]`
403    |
+ help: there is an associated function `to_vec` with a similar name
+   --> $SRC_DIR/alloc/src/slice.rs:LL:COL
404    = note: this error originates in the macro `vec` (in Nightly builds, run with -Z macro-backtrace for more info)
406 error[E0053]: method `in_trait_impl_return` has an incompatible type for trait


The actual stderr differed from the expected stderr.
---
--- stderr -------------------------------
error[E0666]: nested `impl Trait` is not allowed
##[error]  --> /checkout/tests/ui/impl-trait/where-allowed.rs:50:51
   |
LL | fn in_impl_Fn_parameter_in_parameters(_: &impl Fn(impl Debug)) { panic!() }
   |                                           |       |
   |                                           |       nested `impl Trait` here
   |                                           outer `impl Trait`


error[E0666]: nested `impl Trait` is not allowed
##[error]  --> /checkout/tests/ui/impl-trait/where-allowed.rs:59:57
   |
LL | fn in_impl_Fn_parameter_in_return() -> &'static impl Fn(impl Debug) { panic!() }
   |                                                 |       |
   |                                                 |       nested `impl Trait` here
   |                                                 outer `impl Trait`


error[E0658]: `impl Trait` in associated types is unstable
##[error]  --> /checkout/tests/ui/impl-trait/where-allowed.rs:123:16
   |
LL |     type Out = impl Debug;
   |                ^^^^^^^^^^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information
   = help: add `#![feature(impl_trait_in_assoc_type)]` to the crate attributes to enable
   = note: this compiler was built on YYYY-MM-DD; consider upgrading it if it is out of date
error[E0658]: `impl Trait` in type aliases is unstable
##[error]  --> /checkout/tests/ui/impl-trait/where-allowed.rs:160:23
   |
   |
LL | type InTypeAlias<R> = impl Debug;
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information
   = help: add `#![feature(type_alias_impl_trait)]` to the crate attributes to enable
   = help: add `#![feature(type_alias_impl_trait)]` to the crate attributes to enable
   = note: this compiler was built on YYYY-MM-DD; consider upgrading it if it is out of date
error[E0658]: `impl Trait` in type aliases is unstable
##[error]  --> /checkout/tests/ui/impl-trait/where-allowed.rs:163:39
   |
   |
LL | type InReturnInTypeAlias<R> = fn() -> impl Debug;
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information
   = help: add `#![feature(type_alias_impl_trait)]` to the crate attributes to enable
   = help: add `#![feature(type_alias_impl_trait)]` to the crate attributes to enable
   = note: this compiler was built on YYYY-MM-DD; consider upgrading it if it is out of date

error[E0562]: `impl Trait` is not allowed in `fn` pointer parameters
   |
   |
LL | fn in_fn_parameter_in_parameters(_: fn(impl Debug)) { panic!() }
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods


error[E0562]: `impl Trait` is not allowed in `fn` pointer return types
   |
   |
LL | fn in_fn_return_in_parameters(_: fn() -> impl Debug) { panic!() }
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods


error[E0562]: `impl Trait` is not allowed in `fn` pointer parameters
   |
   |
LL | fn in_fn_parameter_in_return() -> fn(impl Debug) { panic!() }
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods


error[E0562]: `impl Trait` is not allowed in `fn` pointer return types
   |
   |
LL | fn in_fn_return_in_return() -> fn() -> impl Debug { panic!() }
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods


error[E0562]: `impl Trait` is not allowed in the parameters of `Fn` trait bounds
   |
   |
LL | fn in_dyn_Fn_parameter_in_parameters(_: &dyn Fn(impl Debug)) { panic!() }
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods


error[E0562]: `impl Trait` is not allowed in the return type of `Fn` trait bounds
   |
   |
LL | fn in_dyn_Fn_return_in_parameters(_: &dyn Fn() -> impl Debug) { panic!() }
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods


error[E0562]: `impl Trait` is not allowed in the parameters of `Fn` trait bounds
   |
   |
LL | fn in_dyn_Fn_parameter_in_return() -> &'static dyn Fn(impl Debug) { panic!() }
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods


error[E0562]: `impl Trait` is not allowed in the parameters of `Fn` trait bounds
   |
   |
LL | fn in_impl_Fn_parameter_in_parameters(_: &impl Fn(impl Debug)) { panic!() }
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods


error[E0562]: `impl Trait` is not allowed in the return type of `Fn` trait bounds
   |
   |
LL | fn in_impl_Fn_return_in_parameters(_: &impl Fn() -> impl Debug) { panic!() }
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods


error[E0562]: `impl Trait` is not allowed in the parameters of `Fn` trait bounds
   |
   |
LL | fn in_impl_Fn_parameter_in_return() -> &'static impl Fn(impl Debug) { panic!() }
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods


error[E0562]: `impl Trait` is not allowed in the parameters of `Fn` trait bounds
   |
   |
LL | fn in_Fn_parameter_in_generics<F: Fn(impl Debug)> (_: F) { panic!() }
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods


error[E0562]: `impl Trait` is not allowed in the return type of `Fn` trait bounds
   |
   |
LL | fn in_Fn_return_in_generics<F: Fn() -> impl Debug> (_: F) { panic!() }
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods

error[E0562]: `impl Trait` is not allowed in field types
error[E0562]: `impl Trait` is not allowed in field types
##[error]  --> /checkout/tests/ui/impl-trait/where-allowed.rs:87:32
   |
LL | struct InBraceStructField { x: impl Debug }
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods

error[E0562]: `impl Trait` is not allowed in field types
error[E0562]: `impl Trait` is not allowed in field types
##[error]  --> /checkout/tests/ui/impl-trait/where-allowed.rs:91:41
   |
LL | struct InAdtInBraceStructField { x: Vec<impl Debug> }
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods

error[E0562]: `impl Trait` is not allowed in field types
error[E0562]: `impl Trait` is not allowed in field types
##[error]  --> /checkout/tests/ui/impl-trait/where-allowed.rs:95:27
   |
LL | struct InTupleStructField(impl Debug);
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and methods

error[E0562]: `impl Trait` is not allowed in field types
error[E0562]: `impl Trait` is not allowed in field types
##[error]  --> /checkout/tests/ui/impl-trait/where-allowed.rs:100:25
   |
LL |     InBraceVariant { x: impl Debug },
   |
   = note: `impl Trait` is only allowed in arguments and return types of functions and m [...]

2024-02-22 18:38 UTC, estebank commented
@bors r=oli-obk

2024-02-23 03:36 UTC, merged

2024-02-23 05:02 UTC, rust-timer commented
Finished benchmarking commit (a28d221a4b31de1bda3debcadd3fa2d9bd988e5b): [comparison URL](https://perf.rust-lang.org/compare.html?start=397937d812852f9bbeb671005cb399dbcb357cde&end=a28d221a4b31de1bda3debcadd3fa2d9bd988e5b&stat=instructions:u).

### Overall result: ❌ regressions - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=397937d812852f9bbeb671005cb399dbcb357cde&end=a28d221a4b31de1bda3debcadd3fa2d9bd988e5b&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 2.9% | [0.2%, 5.6%] | 2     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=397937d812852f9bbeb671005cb399dbcb357cde&end=a28d221a4b31de1bda3debcadd3fa2d9bd988e5b&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 4.4% | [4.4%, 4.4%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=397937d812852f9bbeb671005cb399dbcb357cde&end=a28d221a4b31de1bda3debcadd3fa2d9bd988e5b&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 2.0%  | [1.6%, 2.3%]   | 5     |
| Regressions ❌ <br /> (secondary)  | 2.5%  | [1.8%, 4.2%]   | 14    |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -2.3% | [-2.3%, -2.3%] | 1     |
| All ❌✅ (primary)                 | 2.0%  | [1.6%, 2.3%]   | 5     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=397937d812852f9bbeb671005cb399dbcb357cde&end=a28d221a4b31de1bda3debcadd3fa2d9bd988e5b&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 649.393s -> 651.286s (0.29%)
**Artifact size**: 310.95 MiB -> 310.96 MiB (0.00%)

2024-05-14 21:54 UTC, nnethercote commented
For posterity: this caused a large performance regression in certain cases where errors were being emitted. I had an example involving a refactoring of rustc itself where I had hundreds of errors and each error was taking ~5 seconds to emit(!)  #125100 fixes the problem.