Fix inaccurate documentation of `wait_while` and `wait_timeout_while`
rust-lang/rust pull request #121405
Opened 2024-02-21 17:22 UTC by Jupeyy

fixes #121388

Sometimes code is more clear than documentation, cppreference is doing that:

### quote start
Equivalent to
```cpp
while (!stop_waiting())
{
    wait(lock);
}
```
(https://en.cppreference.com/w/cpp/thread/condition_variable/wait)
### quote end

But the current documentation can be interpreted incorrectly. For example if you wait for a condition that is already false, the current documentation suggests that the current thread will still block.

2024-02-24 14:54 UTC, Mark-Simulacrum requested changes

2024-02-24 19:37 UTC, Mark-Simulacrum commented on library/std/src/sync/condvar.rs
> +    /// then the operation is completed.
I'd be happy to see the same code block as in the implementation (perhaps a bit simplified if needed) put into the documentation to help further clarify exactly what the function does if the current docs aren't clear enough.

2024-05-10 09:27 UTC, your-diary commented
Any updates?

The documentation is inaccurate.

> I feel like the old phrasing was clearer. It's technically true that we evaluate the condition before blocking, but the right mental model for a condition variable is that it blocks until the condition is false.

As far as the documentation is roughly correct, I agree with you in that prioritizing user-friendliness or readability over strictness has sometimes advantages.

However, in this case, the documentation is completely wrong.

## Example

Here's a simple dirty implementation for a channel:

```rust
use std::{
    collections::VecDeque,
    sync::{Condvar, Mutex},
};

struct Channel<T> {
    queue: Mutex<VecDeque<T>>,
    ready: Condvar,
}

impl<T> Channel<T> {
    fn new() -> Self {
        Channel {
            queue: Mutex::new(VecDeque::new()),
            ready: Condvar::new(),
        }
    }

    fn send(&self, message: T) {
        self.queue.lock().unwrap().push_back(message);
        self.ready.notify_one();
    }

    fn receive(&self) -> T {
        let mut queue = self.queue.lock().unwrap();
        if (queue.is_empty()) {
            queue = self.ready.wait_while(queue, |v| v.is_empty()).unwrap();
        }
        queue.pop_front().unwrap()
    }
}

fn main() {
    let channel = Channel::new();
    channel.send(1);
    channel.send(2);
    println!("{}", channel.receive()); //=> 1
}
```

If we believe the current documentation, `if (queue.is_empty())` in

```rust
    fn receive(&self) -> T {
        let mut queue = self.queue.lock().unwrap();
        if (queue.is_empty()) {
            queue = self.ready.wait_while(queue, |v| v.is_empty()).unwrap();
        }
        queue.pop_front().unwrap()
    }
```

is necessary.

However, it is actually redundant; this is enough:

```rust
    fn receive(&self) -> T {
        let mut queue = self.queue.lock().unwrap();
        queue = self.ready.wait_while(queue, |v| v.is_empty()).unwrap();
        queue.pop_front().unwrap()
    }
```

or more simply this:

```rust
    fn receive(&self) -> T {
        let queue = self.queue.lock().unwrap();
        self.ready
            .wait_while(queue, |v| v.is_empty())
            .unwrap()
            .pop_front()
            .unwrap()
    }
```

2024-05-10 15:56 UTC, Jupeyy commented
Tbh I don't know how I should improve the doc except for just doing 1:1 what cppreference is doing. So simplifying the doc to just code. If that is desired, I guess i could take a look into it again. Else I'm ofc also ok if someone else overtakes this pr. Would also be nice to update the docs on `parking_lot` then

2024-08-08 13:42 UTC, Dylan-DPC commented
@Jupeyy any updates on this? thanks

2024-08-08 14:56 UTC, Jupeyy commented
It's not clear to me what the maintainers want. A code block with wrong docs don't seem like the correct solution. My text version is not wanted.
My question if a code block only, similar to cppreference is good was not answered.

I prefer if other people deal with it, thanks.

2024-08-08 14:56 UTC, closed without merging