Resolve region bounds from components of type projection
rust-lang/rust pull request #121602
Opened 2024-02-25 19:58 UTC by dingxiangfei2009

Fix #121601

This will stay in draft so as to resolve potential issue in design and approach, possible conflict with existing work on the type checker.

2024-02-25 20:06 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8040398612/job/21958455472) [(plain)](https://github.com/rust-lang/rust/commit/3e320bc5e20519fec538e3a3f28af3dae5ce0dbc/checks/21958455472/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=dingxiangfei2009
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_a8a3691d-b11b-4606-bff2-0341776cdb7d
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=647d843e843ed8c839f5ae9dcfca061dafdc775f
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_a8a3691d-b11b-4606-bff2-0341776cdb7d
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_a8a3691d-b11b-4606-bff2-0341776cdb7d
GITHUB_TRIGGERING_ACTOR=dingxiangfei2009
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/121602/merge
GITHUB_WORKFLOW_SHA=647d843e843ed8c839f5ae9dcfca061dafdc775f
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.13/x64
---
#12 writing image sha256:f5baa6c2b49a03b32b3c5e04bcebdcb35c1d78280b9b54aa48d629c83b524e80 done
#12 naming to docker.io/library/rust-ci done
#12 DONE 10.1s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-16]
##[group]Clock drift check
  local time: Sun Feb 25 20:00:50 UTC 2024
  network time: Sun, 25 Feb 2024 20:00:50 GMT
  network time: Sun, 25 Feb 2024 20:00:50 GMT
##[endgroup]
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-16', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'build.optimized-compiler-builtins', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-16/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
   Compiling self_cell v1.0.3
   Compiling odht v0.3.1
   Compiling itertools v0.11.0
   Compiling self_cell v0.10.3
error: internal compiler error: compiler/rustc_borrowck/src/universal_regions.rs:880:36: cannot convert `ReErased` to a region vid
thread 'rustc' panicked at compiler/rustc_middle/src/util/bug.rs:35:44:
Box<dyn Any>
stack backtrace:
stack backtrace:
   0:     0x7f7f1c313b59 - <std[3f306e30e1b975b0]::sys_common::backtrace::_print::DisplayBacktrace as core[301f0576711e1b37]::fmt::Display>::fmt
   1:     0x7f7f1c36d2af - core[301f0576711e1b37]::fmt::write
   2:     0x7f7f1c308225 - <std[3f306e30e1b975b0]::sys::pal::unix::stdio::Stderr as std[3f306e30e1b975b0]::io::Write>::write_fmt
   3:     0x7f7f1c313934 - std[3f306e30e1b975b0]::sys_common::backtrace::print
   4:     0x7f7f1c316b3a - std[3f306e30e1b975b0]::panicking::default_hook::{closure#1}
   5:     0x7f7f1c316815 - std[3f306e30e1b975b0]::panicking::default_hook
   6:     0x7f7f1d071ce7 - <alloc[f288f40e4f762a55]::boxed::Box<rustc_driver_impl[2977fc4f9d6fb199]::install_ice_hook::{closure#0}> as core[301f0576711e1b37]::ops::function::Fn<(&dyn for<'a, 'b> core[301f0576711e1b37]::ops::function::Fn<(&'a core[301f0576711e1b37]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[301f0576711e1b37]::marker::Sync + core[301f0576711e1b37]::marker::Send, &core[301f0576711e1b37]::panic::panic_info::PanicInfo)>>::call
   7:     0x7f7f1c317218 - std[3f306e30e1b975b0]::panicking::rust_panic_with_hook
   8:     0x7f7f200c3636 - std[3f306e30e1b975b0]::panicking::begin_panic::<rustc_errors[aaf275789e7def40]::ExplicitBug>::{closure#0}
   9:     0x7f7f200c31a6 - std[3f306e30e1b975b0]::sys_common::backtrace::__rust_end_short_backtrace::<std[3f306e30e1b975b0]::panicking::begin_panic<rustc_errors[aaf275789e7def40]::ExplicitBug>::{closure#0}, !>
  10:     0x7f7f1cfd01f6 - std[3f306e30e1b975b0]::panicking::begin_panic::<rustc_errors[aaf275789e7def40]::ExplicitBug>
  11:     0x7f7f200a1c01 - <rustc_errors[aaf275789e7def40]::diagnostic::BugAbort as rustc_errors[aaf275789e7def40]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7f7f1fed367d - <rustc_errors[aaf275789e7def40]::DiagCtxt>::bug::<alloc[f288f40e4f762a55]::string::String>
  13:     0x7f7f1feef5a9 - rustc_middle[d5de6df028fdf412]::util::bug::opt_span_bug_fmt::<rustc_span[5d19c5ff0331c292]::span_encoding::Span>::{closure#0}
  14:     0x7f7f1feecbea - rustc_middle[d5de6df028fdf412]::ty::context::tls::with_opt::<rustc_middle[d5de6df028fdf412]::util::bug::opt_span_bug_fmt<rustc_span[5d19c5ff0331c292]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  15:     0x7f7f1feecb98 - rustc_middle[d5de6df028fdf412]::ty::context::tls::with_context_opt::<rustc_middle[d5de6df028fdf412]::ty::context::tls::with_opt<rustc_middle[d5de6df028fdf412]::util::bug::opt_span_bug_fmt<rustc_span[5d19c5ff0331c292]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  16:     0x7f7f1cf66182 - rustc_middle[d5de6df028fdf412]::util::bug::bug_fmt
  17:     0x7f7f1e8471bf - <rustc_borrowck[395db2ec876f4d79]::universal_regions::UniversalRegions>::to_region_vid
  18:     0x7f7f1e8a16c2 - <rustc_borrowck[395db2ec876f4d79]::region_infer::RegionInferenceContext>::eval_verify_bound
  19:     0x7f7f1e8a1903 - <rustc_borrowck[395db2ec876f4d79]::region_infer::RegionInferenceContext>::eval_verify_bound
  20:     0x7f7f1e8a18a3 - <rustc_borrowck[395db2ec876f4d79]::region_infer::RegionInferenceContext>::eval_verify_bound
  21:     0x7f7f1e8adade - <rustc_borrowck[395db2ec876f4d79]::region_infer::RegionInferenceContext>::solve
  22:     0x7f7f1e929c54 - rustc_borrowck[395db2ec876f4d79]::nll::compute_regions
  23:     0x7f7f1e6d3803 - rustc_borrowck[395db2ec876f4d79]::do_mir_borrowck
  24:     0x7f7f1e6bd38e - rustc_borrowck[395db2ec876f4d79]::mir_borrowck
  25:     0x7f7f1eab1895 - rustc_query_impl[72e4d18200285063]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[72e4d18200285063]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[d5de6df028fdf412]::query::erase::Erased<[u8; 8usize]>>
  26:     0x7f7f1ec39425 - <rustc_query_impl[72e4d18200285063]::query_impl::mir_borrowck::dynamic_query::{closure#2} as core[301f0576711e1b37]::ops::function::FnOnce<(rustc_middle[d5de6df028fdf412]::ty::context::TyCtxt, rustc_span[5d19c5ff0331c292]::def_id::LocalDefId)>>::call_once
  27:     0x7f7f1eeaa4fb - rustc_query_system[52f97a9008ac12b1]::query::plumbing::try_execute_query::<rustc_query_impl[72e4d18200285063]::DynamicConfig<rustc_query_system[52f97a9008ac12b1]::query::caches::VecCache<rustc_span[5d19c5ff0331c292]::def_id::LocalDefId, rustc_middle[d5de6df028fdf412]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[72e4d18200285063]::plumbing::QueryCtxt, false>
  28:     0x7f7f1ec8be55 - rustc_query_impl[72e4d18200285063]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  29:     0x7f7f1d236db0 - <rustc_middle[d5de6df028fdf412]::hir::map::Map>::par_body_owners::<rustc_interface[55dbb235da08b868]::passes::analysis::{closure#1}::{closu [...]

2024-02-25 20:53 UTC, dingxiangfei2009 commented
:point_up: The existing build failure is a perfect example that I would like quote in a question about the well-formedness clauses which I am wondering about. I am formulating my question to be posted later in Zulip.

2024-02-26 00:40 UTC, compiler-errors commented
This should be assigned to T-types when it exits draft mode

2024-02-26 17:34 UTC, dingxiangfei2009 commented on compiler/rustc_infer/src/infer/outlives/verify.rs
> +                continue;
... so if we are here, we have, for now, `T == for<'a, 'b, ...> <... as ...>::...`.

I guess it is safe to say that `T: 'static`?

2024-02-26 17:46 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8053127543/job/21994784491) [(plain)](https://github.com/rust-lang/rust/commit/d6fdc9dce259c6690a3c01a921737cc74505b114/checks/21994784491/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=dingxiangfei2009
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_30f1233b-77b3-4ea8-8a32-7d7cc2fe76cb
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=5565acae4e7b05dbcbfca7de03a21dc1ac4e04fd
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_30f1233b-77b3-4ea8-8a32-7d7cc2fe76cb
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_30f1233b-77b3-4ea8-8a32-7d7cc2fe76cb
GITHUB_TRIGGERING_ACTOR=dingxiangfei2009
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/121602/merge
GITHUB_WORKFLOW_SHA=5565acae4e7b05dbcbfca7de03a21dc1ac4e04fd
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_19_X64=/opt/hostedtoolcache/go/1.19.13/x64
---
#12 writing image sha256:0df2a3c1615431c493ebd2a11fe303b25de16605edc53d59a30ad94fa62aacb5 done
#12 naming to docker.io/library/rust-ci done
#12 DONE 10.0s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-16]
##[group]Clock drift check
  local time: Mon Feb 26 17:32:38 UTC 2024
  network time: Mon, 26 Feb 2024 17:32:39 GMT
  network time: Mon, 26 Feb 2024 17:32:39 GMT
##[endgroup]
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-16', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'build.optimized-compiler-builtins', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-16/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---

The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/nll/ty-outlives/projection-aliasing-issue-121601/projection-aliasing-issue-121601.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args nll/ty-outlives/projection-aliasing-issue-121601.rs`
error: 1 errors occurred comparing output.
status: exit status: 1
status: exit status: 1
command: RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/nll/ty-outlives/projection-aliasing-issue-121601.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/nll/ty-outlives/projection-aliasing-issue-121601" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/nll/ty-outlives/projection-aliasing-issue-121601/auxiliary"
--- stderr -------------------------------
error[E0601]: `main` function not found in crate `projection_aliasing_issue_121601`
##[error]  --> /checkout/tests/ui/nll/ty-outlives/projection-aliasing-issue-121601.rs:23:2
   |
```

</details>

2024-02-26 22:11 UTC, compiler-errors requested changes
Thanks for the PR, but I'd personally lean towards closing this in favor of first having a discussion about whether we even want to support this at all.

Essentially this PR is a attempt to extend RFC 1214's projection rules (https://github.com/rust-lang/rfcs/blob/master/text/1214-projections-lifetimes-and-wf.md#outlives-for-projections) with a new rule:

```
TypeOutlivesViaBackwardsProjection:
  ∀i. R ⊢ Pi: 'a
  <P0 as Trait<P1..Pn>>::Assoc normalizes-to T
  --------------------------------------------------
  R ⊢ Ty: 'a
```

In order to fix code that looks like:

```rust
trait Foo: Bar {
    fn hello<'a>(&'a self) {}
}

trait Bar {
    type Assoc;
}

// impl<T> Foo for T where T: Bar // WORKS
impl<T, A> Foo for T where T: Bar<Assoc = A> // BROKEN
{
    fn hello<'a>(&'a self) {
        outlives::<'a, Self::Assoc>();
    }
}

fn outlives<'a, T: 'a>() {}
```

This is an attempt to fix a subset of a more general problem with the type system, where normalization only proceeds in one direction, even when considering an unnormalized type may allow us to prove goals that we cannot on the normalized type.

I don't believe this is unsound, as long as we're enforcing the same things that make RFC 1214's `OutlivesProjectionComponents` sound (i.e. projection must not give us unconstrained lifetimes).

However, I'm still generally concerned that this doesn't interact well with higher-ranked projection bounds, and is still quite limited in the exact matching it can do (consider, e.g., a chain of two projection bounds), and I don't know if it's worth the extra maintenance burden to fix this specific case, since I assume it's hit only very rarely and can be worked around.

---

Side-note: It reminds me of another limitation where we do not consider alias bounds when we are able to project to a rigid type, even if that rigid type doesn't have the same assumptions:

```rust
trait Foo {
    type Bar: Qux;
}

trait Qux {
    fn hello();
}

fn doesnt_work<T: Foo<Bar = U>, U>() {
    T::Bar::hello(); // <~ `T::Bar` becomes `U`, for which we know nothing.
}

fn works<T: Foo>() {
    T::Bar::hello();
}
```

2024-02-26 23:03 UTC, estebank commented
r? @compiler-errors

2024-02-28 19:04 UTC, jackh726 commented
I think a good place to prototype this kind of change would be [a-mir-formality](https://github.com/rust-lang/a-mir-formality). I'm not sure if we're *quite* there yet, but that's where the types team wants to get to when thinking about changes that fundamentally interact with type and borrow checking.

2024-03-04 15:42 UTC, dingxiangfei2009 commented on compiler/rustc_infer/src/infer/outlives/verify.rs
> +                continue;
I retract. It is not necessarily.

2024-03-10 18:54 UTC, closed without merging