Windows: Implement mutex using futex
rust-lang/rust pull request #121956
Opened 2024-03-03 22:18 UTC by ChrisDenton

Well, the Windows equivalent: [`WaitOnAddress`,](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-waitonaddress) [`WakeByAddressSingle`](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-wakebyaddresssingle) and [`WakeByAddressAll`](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-wakebyaddressall).

A couple of things to note about Windows flavoured futexes:

- they can be different sizes (1, 2, 4 or 8 bytes)
- they do spin a fair bit themselves, so I wanted to avoid adding more spinning on top

For the mutex implementation, I decided to split it into two separate implementations rather than using `#[cfg]` for the differences. The impl is small enough that it's much easier to read (imho) when separate.

For rwlock, I basically just stubbed out the spin lock. Happy to add it back if people feel strongly but, as per the above, I'd prefer to avoid it.

This also adds a new shim to miri, because of course it does.

Fixes #121949

2024-03-03 22:20 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-16`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8133410425/job/22224950331) [(plain)](https://github.com/rust-lang/rust/commit/8455c0d951ed9d95e18cb084b75c3647cfccbdb3/checks/22224950331/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ACTION=__run_7
GITHUB_ACTIONS=true
GITHUB_ACTION_REF=
GITHUB_ACTION_REPOSITORY=
GITHUB_ACTOR=ChrisDenton
GITHUB_API_URL=https://api.github.com
GITHUB_BASE_REF=master
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_1bc705be-a4e5-45c7-b296-49f5177b8232
GITHUB_EVENT_NAME=pull_request
---
GITHUB_SERVER_URL=https://github.com
GITHUB_SHA=c4efb545e1af6baeb1cd91b1f7a5947b8d30f1cf
GITHUB_STATE=/home/runner/work/_temp/_runner_file_commands/save_state_1bc705be-a4e5-45c7-b296-49f5177b8232
GITHUB_STEP_SUMMARY=/home/runner/work/_temp/_runner_file_commands/step_summary_1bc705be-a4e5-45c7-b296-49f5177b8232
GITHUB_TRIGGERING_ACTOR=ChrisDenton
GITHUB_WORKFLOW_REF=rust-lang/rust/.github/workflows/ci.yml@refs/pull/121956/merge
GITHUB_WORKFLOW_SHA=c4efb545e1af6baeb1cd91b1f7a5947b8d30f1cf
GITHUB_WORKSPACE=/home/runner/work/rust/rust
GOROOT_1_20_X64=/opt/hostedtoolcache/go/1.20.14/x64
---
#12 writing image sha256:2d3f1c9b0c16b1efeaa3930e4a4d8739d68bc4d522b0c7446f73943f011d543b done
#12 naming to docker.io/library/rust-ci done
#12 DONE 10.0s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-16]
##[group]Clock drift check
  local time: Sun Mar  3 22:19:58 UTC 2024
  network time: Sun, 03 Mar 2024 22:19:58 GMT
  network time: Sun, 03 Mar 2024 22:19:58 GMT
##[endgroup]
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-16', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'build.optimized-compiler-builtins', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-16/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
```

</details>

2024-03-04 07:09 UTC, RalfJung reviewed
Miri shim LGTM :)

2024-03-04 16:35 UTC, ChrisDenton commented on library/std/src/sys/locks/mutex/futex.rs
> +            if state != LOCKED || spin == UNLOCKED {
Oops! That was a very silly find/replace error.

2024-03-04 19:38 UTC, Nilstrieb reviewed
Most of the changes look good to me, but I'm not comfortable approving Windows futex.rs because I don't know very much about Windows and/or the futex interface. maybe @joboet is?

2024-03-05 10:54 UTC, joboet requested changes
Sure, I'll take a look!

2024-03-05 10:54 UTC, joboet commented on library/std/src/sys/pal/windows/futex.rs
The API in this module is unsound: 
* For some type, the comparison inside `WaitOnAddress` will accesses padding bytes
* I'm not sure whether it is UB to pass a value other than 1, 2, 4, 8 to `WaitOnAddress`

While it is internal, I'd like to avoid this. I'd solve this using a trait
```rust
unsafe trait Waitable: Self {
    type Atomic;
}
```
(name could be something else), that is then implemented only for the primitives where we need it. This would also allow you to get rid of the same-size assertion.

2024-03-05 10:54 UTC, joboet commented on library/std/src/sys/pal/windows/futex.rs
> +#[inline(always)]
This is not a hot path, and a private-only API, so I think it's better to leave this up to the optimizer:
```suggestion
```

2024-03-05 18:57 UTC, ChrisDenton commented on library/std/src/sys/pal/windows/futex.rs
Done!

It should be fine to pass a value other than 1, 2, 4 or 8. `WaitOnAddress` does validate its arguments and sets the last error to `ERROR_INVALID_PARAMETER` if it's not one of those values.

I couldn't really think of a better name off hand, so I'll save the bikeshedding until it becomes less localized 😆

2024-03-05 20:46 UTC, joboet approved these changes
r=me after fixing the nit, looks great!

2024-03-05 20:46 UTC, joboet commented on library/std/src/sys/pal/windows/futex.rs
> +    assert_eq!(mem::size_of::<W>(), mem::size_of::<W>());
This doesn't check anything 😄.
```suggestion
```

2024-03-05 20:47 UTC, ChrisDenton commented on library/std/src/sys/pal/windows/futex.rs
> +    assert_eq!(mem::size_of::<W>(), mem::size_of::<W>());
Oh, lol! Refactoring is fun.

2024-03-05 20:55 UTC, ChrisDenton commented
Switching sync implementations is a big enough deal that I think this should prefer to avoid being rolled up, if possible.

@bors r=joboet rollup=iffy

2024-03-06 14:50 UTC, merged

2024-03-06 16:25 UTC, rust-timer commented
Finished benchmarking commit (3314d5ce4c209e840c2e4b2c4442f6e031ae0989): [comparison URL](https://perf.rust-lang.org/compare.html?start=09bc67b9158392361780e779d32997f14cc75c39&end=3314d5ce4c209e840c2e4b2c4442f6e031ae0989&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=09bc67b9158392361780e779d32997f14cc75c39&end=3314d5ce4c209e840c2e4b2c4442f6e031ae0989&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=09bc67b9158392361780e779d32997f14cc75c39&end=3314d5ce4c209e840c2e4b2c4442f6e031ae0989&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.0%  | [0.0%, 0.0%]   | 1     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -4.0% | [-8.9%, -1.4%] | 7     |
| Improvements ✅ <br /> (secondary) | -2.9% | [-3.3%, -2.5%] | 9     |
| All ❌✅ (primary)                 | -3.5% | [-8.9%, 0.0%]  | 8     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=09bc67b9158392361780e779d32997f14cc75c39&end=3314d5ce4c209e840c2e4b2c4442f6e031ae0989&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=09bc67b9158392361780e779d32997f14cc75c39&end=3314d5ce4c209e840c2e4b2c4442f6e031ae0989&stat=size:linked_artifact)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.0%  | [0.0%, 0.0%]   | 2     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -0.1% | [-0.1%, -0.0%] | 3     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -0.0% | [-0.1%, 0.0%]  | 5     |
</details>

**Bootstrap**: 646.206s -> 646.923s (0.11%)
**Artifact size**: 175.06 MiB -> 175.06 MiB (-0.00%)