Document overrides of `clone_from()`
rust-lang/rust pull request #122201
Opened 2024-03-08 18:36 UTC by coolreader18

As mentioned in https://github.com/rust-lang/rust/pull/96979#discussion_r1379502413

Specifically, when an override doesn't just forward to an inner type, document the behavior and that it's preferred over simply assigning a clone of source. Also, change instances where the second parameter is "other" to "source".

2024-03-09 09:34 UTC, joboet commented
r? libs-api

2024-03-31 18:53 UTC, dtolnay requested changes
Thank you!

2024-03-31 18:53 UTC, dtolnay commented on library/alloc/src/collections/vec_deque/mod.rs
> +    /// elements as well.
It doesn't do this currently. All existing elements are dropped.

2024-03-31 19:03 UTC, dtolnay commented
@rust-lang/libs-api:

Please take a skim through the added documentation and decide whether these are all commitments we can make.

Some of them are in the form of _"This method is preferred over simply assigning `source.clone()` to `self`, as it avoids reallocation if possible"_, and it's debatable to what extent that constitutes a commitment. It sounds like something that can be changed saying "yeah we decided it wasn't possible after all".

Other ones are stronger commitments.

Deliberate new commitments:

- `Box::<[T], A>::clone_from` (equivalent to the already existing commitment on `Box::<T, A>::clone_from` for `T: Sized`)
- `LinkedList::<T, A>::clone_from`
- `Vec::<T, A>::clone_from`
- `Waker::clone_from` (https://github.com/rust-lang/rust/pull/96979)

"Commitments":

- `BinaryHeap::<T, A>::clone_from`
- `VecDeque::<T, A>::clone_from`
- `String::clone_from`
- `HashSet::<T, S>::clone_from`
- `OsString::clone_from`
- `PathBuf::clone_from`

@rfcbot fcp merge

2024-04-01 18:04 UTC, workingjubilee reviewed
It seems to me "avoids allocations if possible" could also be interpreted to sound like a much more affirmative "we will do this if there is _any possible interpretation_ of our data structure that will avoid allocations here". That may prove to be a bit of a peculiar thing to promise, especially when there's nothing stopping you from using `clone_from` for cloning a larger data structure "into" a smaller one, which will _force_ new allocations.

It is possible that we may wish to say "reduces allocations" instead, as reducing the number of allocations by some N can validly be 0.

I am most concerned about this in the case of the types like BinaryHeap, LinkedList, and the Map/Set types, which have a somewhat more ambiguous internal representation, and in some cases are direly under-loved.

2024-04-05 16:59 UTC, riking commented on library/core/src/cell.rs
>      /// Panics if `other` is currently mutably borrowed.
nit: parameter rename missed in the comment.

2024-04-11 06:28 UTC, coolreader18 commented
I'm unsure of how the FCP interacts with reviews - should I address the nits/review comments while the FCP is active?

2024-04-11 18:36 UTC, dtolnay commented
Please address the review comments at your leisure. It doesn't make a difference whether that happens while the FCP is active or afterward, unless some team member's approval is contingent on seeing the resolution of some concern (usually with "@​rfcbot concern").

2024-04-17 06:15 UTC, dtolnay approved these changes
Thank you! This looks good to me.

I think this wording is all right, but I would be interested to evaluate a followup PR if someone wants to address https://github.com/rust-lang/rust/pull/122201#pullrequestreview-1971822376. The reason I think the current wording in the PR is all right is I don't see "avoids reallocation if possible" being interpreted as "does not allocate if there is any possible interpretation of our data structure that could implement this operation without allocating". It instead just means "avoids those allocations which are possible to avoid per this manifestation of the data structure". The more interesting guarantees being committed to are the ones listed in https://github.com/rust-lang/rust/pull/122201#issuecomment-2028877841.

2024-04-17 06:15 UTC, dtolnay commented
@bors r+

2024-04-17 06:17 UTC, dtolnay commented
@bors ping

2024-04-17 06:20 UTC, dtolnay commented
@bors r+

2024-04-17 18:30 UTC, merged