Add APIs for dealing with titlecase
rust-lang/rust pull request #122668
Opened 2024-03-17 23:50 UTC by Jules-Bertholet

Waiting on ACP: https://github.com/rust-lang/libs-team/issues/354

r? libs-api

@rustbot label T-libs-api S-waiting-on-acp A-unicode

2025-11-24 14:19 UTC, Jules-Bertholet commented
The libs team gave a positive response to the ACP. @rustbot label -S-waiting-on-ACP S-waiting-on-review

2026-03-15 20:41 UTC, Jules-Bertholet commented
@rustbot reroll

2026-03-16 21:20 UTC, Mark-Simulacrum requested changes

2026-03-16 21:20 UTC, Mark-Simulacrum commented on library/core/src/char/methods.rs
> +            _ => unicode::Alphabetic(self),
I think this is from "Extend ASCII fast paths of `char` methods beyond ASCII"...

Can you confirm we continue to have exhaustive coverage in tests? I'm not sure how much the generated tests by the test generator call the public methods vs check that `unicode::Alphabetic` (for example) is accurate.

Also, I imagine that flipping the order of capital A-Z vs. lowercase a-z *might* influence codegen, and lowercase seems more likely to be common. Maybe worth doing something different there?

How did you decide on the particular threshold here (and in other modified functions)? Maybe we can split this out to a separate PR?

2026-03-16 21:20 UTC, Mark-Simulacrum commented on library/core/src/char/mod.rs
> +pub enum CharCase {
nit: also `#[must_use]`, probably.

2026-03-16 21:20 UTC, Mark-Simulacrum commented on library/core/src/char/mod.rs
> +    Upper = 0b11,
Can you add a comment about why these particular discriminants are chosen?

2026-03-16 22:21 UTC, Jules-Bertholet commented on library/core/src/char/mod.rs
> +    Upper = 0b11,
I added a doc comment explaining this.

2026-03-16 22:24 UTC, Jules-Bertholet commented on library/core/src/char/mod.rs
> +pub enum CharCase {
Why? I don't think we usually label types like this `#[must_use]`?

2026-03-16 22:28 UTC, Jules-Bertholet commented on library/core/src/char/methods.rs
> +            _ => unicode::Alphabetic(self),
> Also, I imagine that flipping the order of capital A-Z vs. lowercase a-z _might_ influence codegen, and lowercase seems more likely to be common. Maybe worth doing something different there?

Good point, I fixed it.

> How did you decide on the particular threshold here (and in other modified functions)?

I chose the highest value that would work, using https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp to verify. E.g., for this function, https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%3AAlphabetic%3A%5D&abb=on says that the first non-ASCII alphabetic character is U+AA.

2026-03-17 03:59 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/23177643108/job/67343349114) [(plain enhanced)](https://triage.rust-lang.org/gha-logs/rust-lang/rust/67343349114) [(plain)](https://github.com/rust-lang/rust/commit/2f2532c3c01da983bdb379235e9f5a6237233e7f/checks/67343349114/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
[TIMING:end] compile::Sysroot { compiler: Compiler { stage: 0, host: x86_64-unknown-linux-gnu, forced_compiler: false }, force_recompile: false } -- 0.006
[TIMING:end] builder::Libdir { compiler: Compiler { stage: 0, host: x86_64-unknown-linux-gnu, forced_compiler: false }, target: x86_64-unknown-linux-gnu } -- 0.002
[TIMING:end] compile::StdLink { compiler: Compiler { stage: 0, host: x86_64-unknown-linux-gnu, forced_compiler: false }, target_compiler: Compiler { stage: 0, host: x86_64-unknown-linux-gnu, forced_compiler: false }, target: x86_64-unknown-linux-gnu, crates: [], force_recompile: false } -- 0.002
##[group]Building stage1 compiler artifacts (stage0 -> stage1, x86_64-unknown-linux-gnu)
error: process didn't exit successfully: `sccache /checkout/obj/build/bootstrap/debug/rustc -vV` (exit status: 2)
--- stderr
sccache: error: Timed out waiting for server startup. Maybe the remote service is unreachable?
Run with SCCACHE_LOG=debug SCCACHE_NO_DAEMON=1 to get more information

Bootstrap failed while executing `build --stage 2 compiler rustdoc`
Build completed unsuccessfully in 0:00:38
  local time: Tue Mar 17 03:59:43 UTC 2026
  network time: Tue, 17 Mar 2026 03:59:44 GMT
```

</details>

2026-03-17 04:25 UTC, Jules-Bertholet commented on library/core/src/char/methods.rs
> +            _ => unicode::Alphabetic(self),
> Can you confirm we continue to have exhaustive coverage in tests? I'm not sure how much the generated tests by the test generator call the public methods vs check that `unicode::Alphabetic` (for example) is accurate.

They didn't call the public methods, no. But should now

2026-03-17 04:28 UTC, Jules-Bertholet commented
@rustbot ready

2026-03-21 13:57 UTC, Mark-Simulacrum commented on library/core/src/char/mod.rs
> +pub enum CharCase {
https://std-dev-guide.rust-lang.org/policy/must-use.html

> The #[must_use] attribute can be applied to types or functions when failing to explicitly consider them or their output is almost certainly a bug.

IMO, having and ignoring the result of `char::case()` is almost certainly a bug, right? This can be added later though without any problems if/when someone actually requests it though with a non-theoretical example set of code.

2026-03-21 14:00 UTC, Mark-Simulacrum approved these changes
r=me with tracking issue filed + added

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/122668/3645249d79dfb136b5d8de3ce153d19d6698d92d..7f0cadd0be774f54d833699040b69d4087b7f06f)*

2026-03-21 18:17 UTC, Mark-Simulacrum commented
Can you squash the commits a bit? Not necessarily into one, but I think duplicating the non-ASCII fast path + tracking issue is definitely more than needed.

2026-03-21 18:33 UTC, Jules-Bertholet commented
Squashed

2026-03-21 22:53 UTC, Mark-Simulacrum commented
@bors r+

Thanks!

2026-03-22 02:24 UTC, Zalathar commented
@bors yield (enclosing rollup)

2026-03-22 16:43 UTC, JonathanBrouwer commented
@bors try jobs=x86_64-gnu-aux
Seeing if the hang in this job is maybe real, since it happened 3 times in a row

2026-03-22 16:53 UTC, JonathanBrouwer commented
@bors try jobs=x86_64-gnu-aux
Seeing if the hang in this job is maybe real, since it happened 3 times in a row

2026-03-22 23:18 UTC, JonathanBrouwer commented
Let's see if that's reproducible 
@bors try jobs=x86_64-gnu-aux

2026-03-22 23:18 UTC, JonathanBrouwer commented
........
@bors try jobs=x86_64-gnu-aux

2026-03-23 11:16 UTC, JonathanBrouwer commented
@bors r-
The tests added by this PR seem to be very slow
```

Mon, 23 Mar 2026 00:51:27 GMT   test cell::refcell_replace ... ok
Mon, 23 Mar 2026 00:51:28 GMT   test cell::refcell_replace_borrows ... ok
Mon, 23 Mar 2026 00:51:28 GMT   test cell::refcell_swap ... ok
Mon, 23 Mar 2026 00:51:28 GMT   test cell::refcell_swap_borrows ... ok
Mon, 23 Mar 2026 00:51:28 GMT   test cell::refcell_unsized ... ok
Mon, 23 Mar 2026 00:51:28 GMT   test cell::smoketest_cell ... ok
Mon, 23 Mar 2026 00:51:29 GMT   test cell::smoketest_unsafe_cell ... ok
Mon, 23 Mar 2026 00:51:29 GMT   test cell::unsafe_cell_raw_get ... ok
Mon, 23 Mar 2026 00:51:29 GMT   test cell::unsafe_cell_unsized ... ok
Mon, 23 Mar 2026 02:55:12 GMT   test char::at_most_one_case ... ok
Mon, 23 Mar 2026 02:55:12 GMT   test char::ed_iterator_specializations ... ok
Mon, 23 Mar 2026 02:55:12 GMT   test char::eu_iterator_specializations ... ok
Mon, 23 Mar 2026 02:55:12 GMT   test char::test_as_ascii_invalid ... ok
Mon, 23 Mar 2026 04:55:46 GMT   test char::test_char_case ... ok
Mon, 23 Mar 2026 04:55:46 GMT   test char::test_convert ... ok
Mon, 23 Mar 2026 04:55:46 GMT   test char::test_convert_const ... ok
Mon, 23 Mar 2026 04:55:47 GMT   test char::test_decode_utf16 ... ok
Mon, 23 Mar 2026 04:55:47 GMT   test char::test_decode_utf16_size_hint ... ok
Mon, 23 Mar 2026 04:55:47 GMT   test char::test_encode_utf16 ... ok
Mon, 23 Mar 2026 04:55:47 GMT   test char::test_encode_utf16_raw_buffer_too_small ... ok
Mon, 23 Mar 2026 04:55:47 GMT   test char::test_encode_utf8 ... ok
Mon, 23 Mar 2026 04:55:48 GMT   test char::test_encode_utf8_raw_buffer_too_small ... ok
Mon, 23 Mar 2026 04:55:49 GMT   test char::test_escape_debug ... ok
Mon, 23 Mar 2026 04:55:49 GMT   test char::test_escape_default ... ok
```

Causing hangs in the x86_64-gnu-aux job.

2026-03-23 11:33 UTC, Zalathar commented
Note that the `x86_64-gnu-aux` job runs stdlib tests under miri, making them much slower than when run normally. 

Tests with many inputs/cases typically need to be excluded from miri testing, so that they don’t cause problems in that job.

2026-03-23 12:15 UTC, Jules-Bertholet commented
@rustbot ready

2026-03-23 12:19 UTC, JonathanBrouwer commented
@bors try jobs=x86_64-gnu-aux

2026-03-23 14:49 UTC, JonathanBrouwer commented
@bors r=Mark-Simulacrum

2026-03-24 01:37 UTC, merged

2026-03-27 13:34 UTC, RalfJung commented on library/core/src/char/methods.rs
> +    /// Conceptually, these characters consist of an uppercase portion followed by a lowercase portion.
What does it mean to "have a category"? Something can "have a property" or "be in a category", but the wording used here doesn't seem grammatical to me.

2026-03-27 13:37 UTC, RalfJung commented on library/core/src/char/methods.rs
> +    /// If this `char` does not have an titlecase mapping, the iterator yields the same `char`.
```suggestion
    /// If this `char` does not have a titlecase mapping, the iterator yields the same `char`.
```

2026-03-27 13:50 UTC, Jules-Bertholet commented on library/core/src/char/methods.rs
> +    /// If this `char` does not have an titlecase mapping, the iterator yields the same `char`.
Already fixed: https://github.com/rust-lang/rust/pull/154288

2026-03-27 13:54 UTC, Jules-Bertholet commented on library/core/src/char/methods.rs
> +    /// Conceptually, these characters consist of an uppercase portion followed by a lowercase portion.
"Has the Unicode property assignment `General_Category=Titlecase_Letter`". But yes, "is in the general category" would probably be better