Stop doing expensive work in `opt_suggest_box_span` eagerly
rust-lang/rust pull request #123006
Opened 2024-03-24 16:29 UTC by compiler-errors

This PR defers the `can_coerce` and `predicate_must_hold_modulo_regions` calls in `opt_suggest_box_span`, and instead defers it until error reporting. This requires pulling the logic out of `note_obligation_cause_code` and into coercion, where we have access to the trait solver.

This also allows us to remove `TypeVariableOriginKind::OpaqueTypeInference`.

2024-03-24 16:29 UTC, compiler-errors commented
r? compiler

2024-03-27 10:43 UTC, fee1-dead requested changes
r=me after a small nit

2024-03-27 10:43 UTC, fee1-dead commented on compiler/rustc_hir_typeck/src/_match.rs
> +    // (e.g. we're in the tail of a function body)
would probably make sense to document that the `DefId` return type is of the `AliasTy` for the expectation. A little bit unclear by the name. Maybe it should be renamed to something like `alias_ty_id_from_rpit_expectation`

2024-03-27 14:09 UTC, compiler-errors commented
@bors r=fee1-dead

2024-03-27 17:42 UTC, merged

2024-03-27 22:56 UTC, rust-timer commented
Finished benchmarking commit (d5db7fb537c0352eec3855aa0331c271c48ac4f6): [comparison URL](https://perf.rust-lang.org/compare.html?start=10a7aa14fed9b528b74b0f098c4899c37c09a9c7&end=d5db7fb537c0352eec3855aa0331c271c48ac4f6&stat=instructions:u).

### Overall result: ❌ regressions - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=10a7aa14fed9b528b74b0f098c4899c37c09a9c7&end=d5db7fb537c0352eec3855aa0331c271c48ac4f6&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 0.2% | [0.2%, 0.3%] | 2     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=10a7aa14fed9b528b74b0f098c4899c37c09a9c7&end=d5db7fb537c0352eec3855aa0331c271c48ac4f6&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.9%  | [0.4%, 1.3%]   | 5     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -0.6% | [-0.8%, -0.5%] | 2     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | 0.5%  | [-0.8%, 1.3%]  | 7     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=10a7aa14fed9b528b74b0f098c4899c37c09a9c7&end=d5db7fb537c0352eec3855aa0331c271c48ac4f6&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.6%  | [0.4%, 0.8%]   | 7     |
| Regressions ❌ <br /> (secondary)  | 2.6%  | [2.3%, 2.8%]   | 4     |
| Improvements ✅ <br /> (primary)   | -3.0% | [-3.0%, -3.0%] | 1     |
| Improvements ✅ <br /> (secondary) | -2.2% | [-2.2%, -2.2%] | 1     |
| All ❌✅ (primary)                 | 0.2%  | [-3.0%, 0.8%]  | 8     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=10a7aa14fed9b528b74b0f098c4899c37c09a9c7&end=d5db7fb537c0352eec3855aa0331c271c48ac4f6&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 670.226s -> 670.379s (0.02%)
**Artifact size**: 315.70 MiB -> 315.75 MiB (0.01%)