De-LLVM the unchecked shifts [MCP#693]
rust-lang/rust pull request #123226
Opened 2024-03-30 07:38 UTC by scottmcm

This is just one part of the MCP (https://github.com/rust-lang/compiler-team/issues/693), but it's the one that IMHO removes the most noise from the standard library code.

Seems net simpler this way, since MIR already supported heterogeneous shifts anyway, and thus it's not more work for backends than before.

r? WaffleLapkin

2024-03-30 07:55 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8489293586/job/23259219296) [(plain)](https://github.com/rust-lang/rust/commit/08549917e351b9f5ed30cc88bbdd9e3a54f8ccd6/checks/23259219296/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#17 exporting to docker image format
#17 sending tarball 28.9s done
#17 DONE 34.3s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---

+ error[E0600]: cannot apply unary operator `-` to type `u32`
+   --> $DIR/const-int-unchecked.rs:41:65
+    |
+ LL | const SHL_I8_NEG: i8 = unsafe { intrinsics::unchecked_shl(5_i8, -1) };
+    |                                                                 |
+    |                                                                 cannot apply unary operator `-`
+    |                                                                 cannot apply unary operator `-`
+    |                                                                 help: you may have meant the maximum value of `u32`: `u32::MAX`
+    = note: unsigned values cannot be negated
+ 
+ error[E0600]: cannot apply unary operator `-` to type `u32`
+   --> $DIR/const-int-unchecked.rs:43:67
+   --> $DIR/const-int-unchecked.rs:43:67
+    |
+ LL | const SHL_I16_NEG: i16 = unsafe { intrinsics::unchecked_shl(5_16, -1) };
+    |                                                                   |
+    |                                                                   cannot apply unary operator `-`
+    |                                                                   cannot apply unary operator `-`
+    |                                                                   help: you may have meant the maximum value of `u32`: `u32::MAX`
+    = note: unsigned values cannot be negated
+ 
+ error[E0600]: cannot apply unary operator `-` to type `u32`
+   --> $DIR/const-int-unchecked.rs:45:68
+   --> $DIR/const-int-unchecked.rs:45:68
+    |
+ LL | const SHL_I32_NEG: i32 = unsafe { intrinsics::unchecked_shl(5_i32, -1) };
+    |                                                                    |
+    |                                                                    cannot apply unary operator `-`
+    |                                                                    cannot apply unary operator `-`
+    |                                                                    help: you may have meant the maximum value of `u32`: `u32::MAX`
+    = note: unsigned values cannot be negated
+ 
+ error[E0600]: cannot apply unary operator `-` to type `u32`
+   --> $DIR/const-int-unchecked.rs:47:68
+   --> $DIR/const-int-unchecked.rs:47:68
+    |
+ LL | const SHL_I64_NEG: i64 = unsafe { intrinsics::unchecked_shl(5_i64, -1) };
+    |                                                                    |
+    |                                                                    cannot apply unary operator `-`
+    |                                                                    cannot apply unary operator `-`
+    |                                                                    help: you may have meant the maximum value of `u32`: `u32::MAX`
+    = note: unsigned values cannot be negated
+ 
+ error[E0600]: cannot apply unary operator `-` to type `u32`
+   --> $DIR/const-int-unchecked.rs:49:71
+   --> $DIR/const-int-unchecked.rs:49:71
+    |
+ LL | const SHL_I128_NEG: i128 = unsafe { intrinsics::unchecked_shl(5_i128, -1) };
+    |                                                                       |
+    |                                                                       cannot apply unary operator `-`
+    |                                                                       cannot apply unary operator `-`
+    |                                                                       help: you may have meant the maximum value of `u32`: `u32::MAX`
+    = note: unsigned values cannot be negated
+ 
+ error[E0600]: cannot apply unary operator `-` to type `u32`
+   --> $DIR/const-int-unchecked.rs:55:72
+   --> $DIR/const-int-unchecked.rs:55:72
+    |
+ LL | const SHL_I8_NEG_RANDOM: i8 = unsafe { intrinsics::unchecked_shl(5_i8, -6) };
+    |                                                                        ^^ cannot apply unary operator `-`
+    = note: unsigned values cannot be negated
+ 
+ error[E0600]: cannot apply unary operator `-` to type `u32`
+   --> $DIR/const-int-unchecked.rs:57:74
+   --> $DIR/const-int-unchecked.rs:57:74
+    |
+ LL | const SHL_I16_NEG_RANDOM: i16 = unsafe { intrinsics::unchecked_shl(5_16, -13) };
+    |                                                                          ^^^ cannot apply unary operator `-`
+    = note: unsigned values cannot be negated
+ 
+ error[E0600]: cannot apply unary operator `-` to type `u32`
+   --> $DIR/const-int-unchecked.rs:59:75
+   --> $DIR/const-int-unchecked.rs:59:75
+    |
+ LL | const SHL_I32_NEG_RANDOM: i32 = unsafe { intrinsics::unchecked_shl(5_i32, -25) };
+    |                                                                           ^^^ cannot apply unary operator `-`
+    = note: unsigned values cannot be negated
+ 
+ error[E0600]: cannot apply unary operator `-` to type `u32`
+   --> $DIR/const-int-unchecked.rs:61:75
+   --> $DIR/const-int-unchecked.rs:61:75
+    |
+ LL | const SHL_I64_NEG_RANDOM: i64 = unsafe { intrinsics::unchecked_shl(5_i64, -30) };
+    |                                                                           ^^^ cannot apply unary operator `-`
+    = note: unsigned values cannot be negated
+ 
+ error[E0600]: cannot apply unary operator `-` to type `u32`
+   --> $DIR/const-int-unchecked.rs:63:78
+   --> $DIR/const-int-unchecked.rs:63:78
+    |
+ LL | const SHL_I128_NEG_RANDOM: i128 = unsafe { intrinsics::unchecked_shl(5_i128, -93) };
+    |                                                                              ^^^ cannot apply unary operator `-`
+    = note: unsigned values cannot be negated
+ 
+ error[E0600]: cannot apply unary operator `-` to type `u32`
+   --> $DIR/const-int-unchecked.rs:96:65
+   --> $DIR/const-int-unchecked.rs:96:65
+    |
+ LL | const SHR_I8_NEG: i8 = unsafe { intrinsics::unchecked_shr(5_i8, -1) };
+    |                                                                 |
+    |                                                                 cannot apply unary operator `-`
+    |                                                                 cannot apply unary operator `-`
+    |                                                                 help: you may have meant the maximum value of `u32`: `u32::MAX`
+    = note: unsigned values cannot be negated
+ 
+ error[E0600]: cannot apply unary operator `-`  [...]

2024-03-30 09:52 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8489855854/job/23260367366) [(plain)](https://github.com/rust-lang/rust/commit/c2517c82e1367b0d5c598a82fe6e56393658bf2c/checks/23260367366/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiler: "MIRI_ENV_VAR_TEST"="0" "MIRI_TEMP"="/tmp/miri-uitest-KNWFfo" "RUST_BACKTRACE"="1" /checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/miri "--error-format=json" "-Dwarnings" "-Dunused" "-Ainternal_features" "-Zui-testing" "--target" "x86_64-unknown-linux-gnu" "--out-dir" OUT_DIR


FAILED TEST: tests/fail/intrinsics/unchecked_shl2.rs
command: MIRI_ENV_VAR_TEST="0" MIRI_TEMP="/tmp/miri-uitest-KNWFfo" RUST_BACKTRACE="1" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/miri" "--error-format=json" "-Dwarnings" "-Dunused" "-Ainternal_features" "-Zui-testing" "--target" "x86_64-unknown-linux-gnu" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/ui/tests/fail/intrinsics" "tests/fail/intrinsics/unchecked_shl2.rs" "--edition" "2021"
   0: ui tests in tests/fail for x86_64-unknown-linux-gnu failed
   1: tests failed


Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
error: actual output differed from expected
error: actual output differed from expected
Execute `./miri test --bless` to update `tests/fail/intrinsics/unchecked_shl2.stderr` to the actual output
--- tests/fail/intrinsics/unchecked_shl2.stderr
-error: Undefined Behavior: overflowing shift by -1 in `unchecked_shl`
+error[E0600]: cannot apply unary operator `-` to type `u32`
   --> $DIR/unchecked_shl2.rs:LL:CC
    |
    |
 LL |         let _n = intrinsics::unchecked_shl(1i8, -1);
-   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ overflowing shift by -1 in `unchecked_shl`
    |
-   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
+   = note: unsigned values cannot be negated
 
---

Caused by:
  process didn't exit successfully: `/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/ui-34e0c79da4e404df --quiet` (exit status: 1)

error: `overflowing shift by -1 in `unchecked_shl`` not found in diagnostics on line 6
  |
  |
7 |         //~^ ERROR: overflowing shift by -1 in `unchecked_shl`
  |

error: there were 1 unmatched diagnostics
##[error] --> tests/fail/intrinsics/unchecked_shl2.rs:6:49
##[error] --> tests/fail/intrinsics/unchecked_shl2.rs:6:49
  |
6 |         let _n = intrinsics::unchecked_shl(1i8, -1);
  |                                                 ^^ Error: cannot apply unary operator `-` to type `u32`

full stderr:
error[E0600]: cannot apply unary operator `-` to type `u32`
##[error]  --> tests/fail/intrinsics/unchecked_shl2.rs:6:49
##[error]  --> tests/fail/intrinsics/unchecked_shl2.rs:6:49
   |
LL |         let _n = intrinsics::unchecked_shl(1i8, -1);
   |                                                 |
   |                                                 cannot apply unary operator `-`
   |                                                 cannot apply unary operator `-`
   |                                                 help: you may have meant the maximum value of `u32`: `u32::MAX`
   = note: unsigned values cannot be negated

error: aborting due to 1 previous error

```

</details>

2024-03-30 10:26 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8490106845/job/23260855721) [(plain)](https://github.com/rust-lang/rust/commit/122df8a601834017387a6cee6d48c7c28e71af21/checks/23260855721/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Getting action download info
Download action repository 'msys2/setup-msys2@v2.22.0' (SHA:cc11e9188b693c2b100158c3322424c4cc1dadea)
Download action repository 'actions/checkout@v4' (SHA:b4ffde65f46336ab88eb53be808477a3936bae11)
Download action repository 'actions/upload-artifact@v4' (SHA:5d5d22a31266ced268874388b861e4b58bb5c2f3)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
---
COPY scripts/sccache.sh /scripts/
RUN sh /scripts/sccache.sh

COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt \
    && pip3 install virtualenv
COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---

#12 [5/8] COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
#12 DONE 0.0s

#13 [6/8] RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt     && pip3 install virtualenv
#13 0.431   Downloading binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
#13 0.447 Collecting boolean-py==4.0
#13 0.454   Downloading boolean.py-4.0-py3-none-any.whl (25 kB)
#13 0.472 Collecting chardet==5.1.0
---
#13 3.569 Building wheels for collected packages: reuse
#13 3.570   Building wheel for reuse (pyproject.toml): started
#13 3.897   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 3.898   Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=181117 sha256=f5f58750481f69515c2c0d1d503daf565e2565c370d07fc6aeb95fe3498b4269
#13 3.898   Stored in directory: /tmp/pip-ephem-wheel-cache-ftpou76w/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
#13 3.901 Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
#13 3.922   Attempting uninstall: setuptools
#13 3.923     Found existing installation: setuptools 59.6.0
#13 3.924     Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
#13 3.924     Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
#13 3.925     Can't uninstall 'setuptools'. No files were found to uninstall.
#13 4.598 Successfully installed binaryornot-0.4.4 boolean-py-4.0 chardet-5.1.0 jinja2-3.1.2 license-expression-30.0.0 markupsafe-2.1.1 python-debian-0.1.49 reuse-1.1.0 setuptools-66.0.0
#13 4.599 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 5.113 Collecting virtualenv
#13 5.162   Downloading virtualenv-20.25.1-py3-none-any.whl (3.8 MB)
#13 5.342      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 21.3 MB/s eta 0:00:00
#13 5.393 Collecting platformdirs<5,>=3.9.1
#13 5.400   Downloading platformdirs-4.2.0-py3-none-any.whl (17 kB)
#13 5.420 Collecting distlib<1,>=0.3.7
#13 5.428   Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
#13 5.473 Collecting filelock<4,>=3.12.2
#13 5.480   Downloading filelock-3.13.3-py3-none-any.whl (11 kB)
#13 5.480   Downloading filelock-3.13.3-py3-none-any.whl (11 kB)
#13 5.566 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 5.727 Successfully installed distlib-0.3.8 filelock-3.13.3 platformdirs-4.2.0 virtualenv-20.25.1
#13 DONE 5.8s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      227264 kB
DirectMap2M:     7112704 kB
DirectMap1G:    11534336 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
    Finished `dev` profile [unoptimized] target(s) in 0.04s
##[endgroup]
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/50e3d6296d6e7c1d0f4e85f674139c8463f62934/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/llvm-50e3d6296d6e7c1d0f4e85f674139c8463f62934-true/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm
---
   Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
    Finished `release` profile [optimized] target(s) in 26.53s
##[endgroup]
fmt check
##[error]Diff in /checkout/compiler/rustc_hir_analysis/src/check/intrinsic.rs at line 454:
             sym::unchecked_div | sym::unchecked_rem | sym::exact_div => {
                 (1, 0, vec![param(0), param(0)], param(0))
             }
-            sym::unchecked_shl | sym::unchecked_shr => {
-                (2, 0, vec![param(0), param(1)], param(0))
-            }
+            sym::unchecked_shl | sym::unchecked_shr => (2, 0, vec![param(0), param(1)], param(0)),
             sym::rotate_left | sym::rotate_right => (1, 0, vec![param(0), param(0)], param(0)),
             sym::unchecked_add | sym::unchecked_sub | sym::unchecked_mul => {
                 (1, 0, vec![param(0), param(0)], param(0))
Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/compiler/rustc_hir_analysis/src/variance/xform.rs" "/checkout/compiler/rustc_hir_analysis/src/variance/mod.rs" "/checkout/compiler/rustc_hir_analysis/src/variance/terms.rs" "/checkout/compiler/rustc_hir_analysis/src/variance/constraints.rs" "/checkout/compiler/rustc_hir_analysis/src/variance/solve.rs" "/checkout/compiler/rustc_hir_analysis/src/variance/test.rs" "/checkout/compiler/rustc_hir_analysis/src/check/entry.rs" "/checkout/compiler/rustc_hir_analysis/src/check/errs.rs" "/checkout/compiler/rustc_hir_analysis/src/check/dropck.rs" "/checkout/compiler/rustc_hir_analysis/src/check/intrinsic.rs" "/checkout/compiler/rustc_hir_analysis/src/check/compare_impl_item.rs" "/checkout/compiler/rustc_hir_analysis/src/check/wfcheck.rs" "/checkout/compiler/rustc_hir_analysis/src/check/mod.rs" "/checkout/compiler/rustc_hir_analysis/src/check/check.rs" "/checkout/compiler/rustc_hir_analysis/src/check/intrinsicck.rs" "/checkout/compiler/rustc_hir_analysis/src/check/compare_impl_item/refine.rs" "/checkout/compiler/rustc_hir_analysis/src/check/region.rs" "/checkout/compiler/rustc_hir_analysis/src/collect/item_bounds.rs" "/checkout/compiler/rustc_hir_analysis/src/collect/type_of/opaque.rs" "/checkout/compiler/rustc_hir_analysis/src/collect/type_of.rs" "/checkout/compiler/rustc_hir_analysis/src/collect/predicates_of.rs" "/checkout/compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs" "/checkout/compiler/rustc_hir_analysis/src/collect/generics_of.rs" "/checkout/compiler/rustc_hir_analysis/src/impl_wf_check.rs" "/checkout/compiler/rustc_hir_analysis/src/coherence/unsafety.rs" "/checkout/compiler/rustc_hir_analysis/src/coherence/mod.rs" "/checkout/compiler/rustc_hir_analysis/src/cohe [...]

2024-03-30 10:28 UTC, RalfJung commented on library/core/src/intrinsics/mir.rs
> +//!  - Unchecked binary operations are represented by wrapping the associated binop in [`Unchecked`].
Can you add a test for this?

2024-03-30 10:32 UTC, RalfJung commented
> As far as I can tell, CTFE, Miri, and Codegen all supported mixed unchecked shifts already without me doing anything. So this just gives a way to write tests exercising those.

This comment confusingly disappeared, but for CTFE/Miri it is true. The MIR binops support different types for LHS and RHS (and these intrinsics lower to MIR binops).

2024-03-30 15:09 UTC, WaffleLapkin commented
> but it's the one that IMHO removes the most noise from the standard library code.

I was actually stuck on figuring the shifts out. Since you can have integer shifts with any integer rhs, backends will need to cast, no matter what, so I couldn't figure out how to make everything better for everyone.

I have all the other changes ready (I think), so I'll open a PR once we merge this (I'll try to review soon).

2024-04-02 13:11 UTC, WaffleLapkin requested changes
I have some small nits and am somewhat confused why we want to make intrinsics generic wrt lhs. But LGTM on the general approach of moving things from std to the backend.

This does not particularly help us at my dayjob (we would like `bx.shl` to take rhs which is `u32`, i.e. we would like to have a different `build_shift_expr_rhs`), but I _do_ like this change anyway. 😅

2024-04-02 18:45 UTC, WaffleLapkin commented on library/core/src/intrinsics.rs
> +    pub fn unchecked_shl<T: Copy, U: Copy>(x: T, y: U) -> T;
A bit weird (given that we don't publicly expose this), but given this does not make backend more complex, ig this is fine.

2024-04-02 18:46 UTC, WaffleLapkin approved these changes

2024-04-02 23:24 UTC, merged