Only inspect user-written predicates for privacy concerns
rust-lang/rust pull request #123377
Opened 2024-04-02 17:28 UTC by oli-obk

fixes #123288

2024-04-02 17:45 UTC, compiler-errors requested changes
What predicate ends up mentioning a private type? Specifically, what does `Foo` have to do with `T::Assoc`?

2024-04-02 17:45 UTC, compiler-errors commented on tests/ui/privacy/generic_struct_field_projection.rs
> +//@ check-pass
This test needs to actually explain what it's testing.

2024-04-02 17:46 UTC, compiler-errors commented
> due to adding various bounds on fields

I think it would be helpful if you explained what bounds are being added specifically, and why that's problematic.

2024-04-04 09:41 UTC, oli-obk commented
Explained the test and its problematic bounds.

2024-04-04 14:44 UTC, oli-obk commented
@bors r=compiler-errors

2024-04-04 14:45 UTC, wesleywiser commented
@bors p=1

Fixes P-high issue

2024-04-04 17:41 UTC, merged

2024-04-04 19:02 UTC, rust-timer commented
Finished benchmarking commit (0fd571286ef6df8a6cce06d432013239a8c0665f): [comparison URL](https://perf.rust-lang.org/compare.html?start=96eaf553e547e36003e235a9de26c11460712231&end=0fd571286ef6df8a6cce06d432013239a8c0665f&stat=instructions:u).

### Overall result: ✅ improvements - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=96eaf553e547e36003e235a9de26c11460712231&end=0fd571286ef6df8a6cce06d432013239a8c0665f&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -0.4% | [-0.4%, -0.4%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -0.4% | [-0.4%, -0.4%] | 1     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=96eaf553e547e36003e235a9de26c11460712231&end=0fd571286ef6df8a6cce06d432013239a8c0665f&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -1.1% | [-1.1%, -1.1%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -1.1% | [-1.1%, -1.1%] | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=96eaf553e547e36003e235a9de26c11460712231&end=0fd571286ef6df8a6cce06d432013239a8c0665f&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 0.9% | [0.9%, 0.9%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=96eaf553e547e36003e235a9de26c11460712231&end=0fd571286ef6df8a6cce06d432013239a8c0665f&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 669.066s -> 670.684s (0.24%)
**Artifact size**: 318.07 MiB -> 318.06 MiB (-0.00%)

2024-04-11 14:23 UTC, apiraino commented
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-04-11/near/432715133). A backport PR will be authored by the release team at the end of the current development cycle.

@rustbot label +beta-accepted