[WIP] Rewrite handling of universe-leaking placeholder regions into outlives constraints
rust-lang/rust pull request #123720
Opened 2024-04-10 12:50 UTC by amandasystems

This commit prepares for Polonius by moving handling of leak check/universe errors out of the inference step by rewriting any universe error into an outlives-static constraint.

This variant is a work in progress but seems to pass most tests.

Note that a few debug assertions no longer hold; a few extra eyes on those changes are appreciated!

2024-04-10 12:52 UTC, amandasystems commented
?r nikomatsakis

(it's not 100% ready for review yet probably maybe, but I figured I might as well start the PR now)

2024-04-10 13:08 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8631532657/job/23660151611) [(plain)](https://github.com/rust-lang/rust/commit/6f4ea4006e8739026cb34faedc7b6b013d05f4d4/checks/23660151611/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 exporting to docker image format
#16 sending tarball 32.5s done
#16 DONE 37.7s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---

---- [ui] tests/ui/nll/polonius/location-insensitive-scopes-issue-117146.rs#polonius stdout ----
diff of stderr:

+ error: implementation of `Fn` is not general enough
+    |
+    = note: closure with signature `fn(&'2 ()) -> &()` must implement `Fn<(&'1 (),)>`, for any lifetime `'1`...
+    = note: ...but it actually implements `Fn<(&'2 (),)>`, for some specific lifetime `'2`
1 error[E0597]: `a` does not live long enough
2   --> $DIR/location-insensitive-scopes-issue-117146.rs:10:18
3    |


4 LL |     let b = |_| &a;
-    |             --- -^
-    |             |   ||
-    |             |   |borrowed value does not live long enough
-    |             |   returning this value requires that `a` is borrowed for `'static`
+    |             |    |
+    |             |    borrowed value does not live long enough
+    |             |    borrowed value does not live long enough
+    |             |    requires that `a` is borrowed for `'static`
10 ...
11 LL | }

12    | - `a` dropped here while still borrowed
12    | - `a` dropped here while still borrowed
-    |
- note: due to current limitations in the borrow checker, this implies a `'static` lifetime
-    |
-    |
- LL | fn bad<F: Fn(&()) -> &()>(_: F) {}
- 
- 
- error: implementation of `Fn` is not general enough
-    |
-    |
- LL |     bad(&b);
-    |     ^^^^^^^ implementation of `Fn` is not general enough
-    |
-    = note: closure with signature `fn(&'2 ()) -> &()` must implement `Fn<(&'1 (),)>`, for any lifetime `'1`...
-    = note: ...but it actually implements `Fn<(&'2 (),)>`, for some specific lifetime `'2`
29 error: implementation of `FnOnce` is not general enough
30   --> $DIR/location-insensitive-scopes-issue-117146.rs:13:5



The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/nll/polonius/location-insensitive-scopes-issue-117146.polonius/location-insensitive-scopes-issue-117146.polonius.stderr
To only update this specific test, also pass `--test-args nll/polonius/location-insensitive-scopes-issue-117146.rs`


error in revision `polonius`: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/nll/polonius/location-insensitive-scopes-issue-117146.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--cfg" "polonius" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/nll/polonius/location-insensitive-scopes-issue-117146.polonius" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/nll/polonius/location-insensitive-scopes-issue-117146.polonius/auxiliary" "-Zpolonius=next"
--- stderr -------------------------------
--- stderr -------------------------------
error: implementation of `Fn` is not general enough
   |
   = note: closure with signature `fn(&'2 ()) -> &()` must implement `Fn<(&'1 (),)>`, for any lifetime `'1`...
   = note: ...but it actually implements `Fn<(&'2 (),)>`, for some specific lifetime `'2`
error[E0597]: `a` does not live long enough
##[error]  --> /checkout/tests/ui/nll/polonius/location-insensitive-scopes-issue-117146.rs:10:18
   |
   |
LL |     let b = |_| &a;
   |             |    |
   |             |    borrowed value does not live long enough
   |             |    borrowed value does not live long enough
   |             |    requires that `a` is borrowed for `'static`
...
LL | }
   | - `a` dropped here while still borrowed


error: implementation of `FnOnce` is not general enough
##[error]  --> /checkout/tests/ui/nll/polonius/location-insensitive-scopes-issue-117146.rs:13:5
   |
LL |     bad(&b);
   |     ^^^^^^^ implementation of `FnOnce` is not general enough
   |
   = note: closure with signature `fn(&'2 ()) -> &()` must implement `FnOnce<(&'1 (),)>`, for any lifetime `'1`...
   = note: ...but it actually implements `FnOnce<(&'2 (),)>`, for some specific lifetime `'2`
error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0597`.
------------------------------------------
```

</details>

2024-04-10 14:15 UTC, compiler-errors commented
the syntax is r? nikomatsakis 😆

2024-04-10 16:26 UTC, amandasystems commented
> the syntax is r? nikomatsakis 😆

That’s funny because I tried that first, thought I made a mistake, and went back to “fix” it

2024-04-12 09:19 UTC, amandasystems commented
Update: I had a brainwave during my investigations of the failing UI tests (there's 20-ish of them if you enable the new logic everywhere, depending on whether you count duplicates). I tried adding a new constraint category so that I could easily not blame it (ever, actually), and that reduces the errors down to one, tiny span diff:

```
---- [ui] tests/ui/higher-ranked/trait-bounds/due-to-where-clause.rs stdout ----
diff of stderr:

2         --> $DIR/due-to-where-clause.rs:2:5
3          |
4       LL |     test::<FooS>(&mut 42);
-          |     ^^^^^^^^^^^^ implementation of `Foo` is not general enough
+          |     ^^^^^^^^^^^^^^^^^^^^^ implementation of `Foo` is not general enough
6          |
7          = note: `FooS<'_>` must implement `Foo<'0>`, for any lifetime `'0`...
8          = note: ...but `FooS<'_>` actually implements `Foo<'1>`, for some specific lifetime `'1`
```

2024-04-12 14:19 UTC, nikomatsakis requested changes
Efficiency nit

2024-04-12 14:19 UTC, nikomatsakis commented on compiler/rustc_borrowck/src/constraints/mod.rs
> +        &self,
Efficiency nit: this can be `mut self`...

2024-04-12 14:19 UTC, nikomatsakis commented on compiler/rustc_borrowck/src/constraints/mod.rs
> +        let mut copy = self.clone();
...and then you can remove this clone...

2024-04-12 14:19 UTC, nikomatsakis commented on compiler/rustc_borrowck/src/constraints/mod.rs
> +        &self,
...or just `&mut self`...?

2024-04-12 15:01 UTC, amandasystems commented
I think it's ready for a perf run, @lqd!

2024-04-12 16:04 UTC, lqd commented
@bors try @rust-timer queue

2024-04-12 16:04 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2024-04-12 16:24 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8664071065/job/23759637402) [(plain)](https://github.com/rust-lang/rust/commit/5a1c148ad866212c2b5f290423f596b0d6587062/checks/23759637402/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 exporting to docker image format
#16 sending tarball 29.3s done
#16 DONE 34.5s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
diff of stderr:

2   --> $DIR/due-to-where-clause.rs:2:5
3    |
4 LL |     test::<FooS>(&mut 42);
-    |     ^^^^^^^^^^^^ implementation of `Foo` is not general enough
+    |     ^^^^^^^^^^^^^^^^^^^^^ implementation of `Foo` is not general enough
6    |
7    = note: `FooS<'_>` must implement `Foo<'0>`, for any lifetime `'0`...
8    = note: ...but `FooS<'_>` actually implements `Foo<'1>`, for some specific lifetime `'1`

The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause/due-to-where-clause.stderr
To update references, rerun the tests and pass the `--bless` flag
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args higher-ranked/trait-bounds/due-to-where-clause.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/higher-ranked/trait-bounds/due-to-where-clause.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause/auxiliary"
--- stderr -------------------------------
error: implementation of `Foo` is not general enough
##[error]  --> /checkout/tests/ui/higher-ranked/trait-bounds/due-to-where-clause.rs:2:5
   |
   |
LL |     test::<FooS>(&mut 42); //~ ERROR implementation of `Foo` is not general enough
   |     ^^^^^^^^^^^^^^^^^^^^^ implementation of `Foo` is not general enough
   |
   = note: `FooS<'_>` must implement `Foo<'0>`, for any lifetime `'0`...
   = note: ...but `FooS<'_>` actually implements `Foo<'1>`, for some specific lifetime `'1`
error: aborting due to 1 previous error
------------------------------------------


```

</details>

2024-04-12 18:27 UTC, nikomatsakis requested changes
OK, so, I reviewed and left a (tiny) nit. I don't know that a perf run is really needed, this is pretty clearly grossly inefficient. That's precisely what I expected, of course.

r=me but I'd like to hand this off to somebody else to drive over the finish line

2024-04-12 18:27 UTC, nikomatsakis commented on compiler/rustc_borrowck/src/constraints/mod.rs
> +        let should_be_static:Vec<_> = definitions.indices().filter_map(|rvid| {
```suggestion
        let should_be_static:Vec<_> = definitions.indices().filter(|rvid| {
```

2024-04-12 18:27 UTC, nikomatsakis commented on compiler/rustc_borrowck/src/constraints/mod.rs
> +                    return Some(rvid);
```suggestion
                    return true;
```

2024-04-12 18:27 UTC, nikomatsakis commented on compiler/rustc_borrowck/src/constraints/mod.rs
> +            None
```suggestion
            false
```

2024-04-12 19:15 UTC, rust-timer commented
Queued 1b9e1e65acb35d4d1d734c6461ace5c4e50a9fd0 with parent bd71213cf0a765705e7d72a099151bd4eb465ccb, future [comparison URL](https://perf.rust-lang.org/compare.html?start=bd71213cf0a765705e7d72a099151bd4eb465ccb&end=1b9e1e65acb35d4d1d734c6461ace5c4e50a9fd0).
There is currently 1 preceding artifact in the [queue](https://perf.rust-lang.org/status.html).
It will probably take at least ~1.5 hours until the benchmark run finishes.
<!-- rust-timer: temporary -->

2024-04-13 00:32 UTC, rust-timer commented
Finished benchmarking commit (1b9e1e65acb35d4d1d734c6461ace5c4e50a9fd0): [comparison URL](https://perf.rust-lang.org/compare.html?start=bd71213cf0a765705e7d72a099151bd4eb465ccb&end=1b9e1e65acb35d4d1d734c6461ace5c4e50a9fd0&stat=instructions:u).

### Overall result: ❌ regressions - ACTION NEEDED


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: -S-waiting-on-perf +perf-regression



**Warning ⚠**: The following benchmark(s) failed to build:
- rustc
- wg-grammar
- webrender-2022


### [Instruction count](https://perf.rust-lang.org/compare.html?start=bd71213cf0a765705e7d72a099151bd4eb465ccb&end=1b9e1e65acb35d4d1d734c6461ace5c4e50a9fd0&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean   | range           | count |
|:----------------------------------:|:------:|:---------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 113.9% | [0.3%, 3862.1%] | 236   |
| Regressions ❌ <br /> (secondary)  | 393.2% | [0.1%, 7855.4%] | 184   |
| Improvements ✅ <br /> (primary)   | -      | -               | 0     |
| Improvements ✅ <br /> (secondary) | -      | -               | 0     |
| All ❌✅ (primary)                 | 113.9% | [0.3%, 3862.1%] | 236   |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=bd71213cf0a765705e7d72a099151bd4eb465ccb&end=1b9e1e65acb35d4d1d734c6461ace5c4e50a9fd0&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range           | count |
|:----------------------------------:|:-----:|:---------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -               | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -               | 0     |
| Improvements ✅ <br /> (primary)   | -3.7% | [-10.5%, -0.7%] | 57    |
| Improvements ✅ <br /> (secondary) | -5.6% | [-7.4%, -3.5%]  | 21    |
| All ❌✅ (primary)                 | -3.7% | [-10.5%, -0.7%] | 57    |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=bd71213cf0a765705e7d72a099151bd4eb465ccb&end=1b9e1e65acb35d4d1d734c6461ace5c4e50a9fd0&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean    | range           | count |
|:----------------------------------:|:-------:|:---------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 215.7%  | [0.9%, 3636.4%] | 98    |
| Regressions ❌ <br /> (secondary)  | 1147.6% | [1.0%, 7887.5%] | 61    |
| Improvements ✅ <br /> (primary)   | -       | -               | 0     |
| Improvements ✅ <br /> (secondary) | -       | -               | 0     |
| All ❌✅ (primary)                 | 215.7%  | [0.9%, 3636.4%] | 98    |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=bd71213cf0a765705e7d72a099151bd4eb465ccb&end=1b9e1e65acb35d4d1d734c6461ace5c4e50a9fd0&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: missing data
**Artifact size**: 315.97 MiB -> 305.14 MiB (-3.43%)

2024-04-15 14:50 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8691207038/job/23832898101) [(plain)](https://github.com/rust-lang/rust/commit/d269d50e2f216c903626081bc9657215c33c0305/checks/23832898101/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking rustc_hir_typeck v0.0.0 (/checkout/compiler/rustc_hir_typeck)
error[E0308]: mismatched types
  --> compiler/rustc_borrowck/src/constraints/mod.rs:98:62
   |
98 |             let mut queue: Vec<RegionVid> = outlived_regions(rvid).map(|&r| r).collect();
   |                                             ---------------- ^^^^ expected `RegionVid`, found `&RegionVid`
   |                                             arguments to this function are incorrect
   |
note: closure parameter defined here
  --> compiler/rustc_borrowck/src/constraints/mod.rs:90:33
  --> compiler/rustc_borrowck/src/constraints/mod.rs:90:33
   |
90 |         let outlived_regions = |longer: RegionVid| {
help: consider dereferencing the borrow
   |
   |
98 |             let mut queue: Vec<RegionVid> = outlived_regions(*rvid).map(|&r| r).collect();

    Checking rustc_codegen_llvm v0.0.0 (/checkout/compiler/rustc_codegen_llvm)
error[E0308]: mismatched types
   --> compiler/rustc_borrowck/src/constraints/mod.rs:100:25
   --> compiler/rustc_borrowck/src/constraints/mod.rs:100:25
    |
100 |             seen.insert(rvid);
    |                  ------ ^^^^ expected `RegionVid`, found `&RegionVid`
    |                  arguments to this method are incorrect
    |
note: method defined here
   --> /checkout/library/std/src/collections/hash/set.rs:889:12
   --> /checkout/library/std/src/collections/hash/set.rs:889:12
    |
889 |     pub fn insert(&mut self, value: T) -> bool {
    |            ^^^^^^
help: consider dereferencing the borrow
    |
100 |             seen.insert(*rvid);

error[E0308]: mismatched types
   --> compiler/rustc_borrowck/src/constraints/mod.rs:102:57
    |
    |
102 |             debug!("rvid definition: {:?}", definitions[rvid]);
    |                                                         ^^^^ expected `RegionVid`, found `&RegionVid`
help: consider dereferencing the borrow
    |
    |
102 |             debug!("rvid definition: {:?}", definitions[*rvid]);

error[E0308]: mismatched types
   --> compiler/rustc_borrowck/src/constraints/mod.rs:104:78
    |
    |
104 |                 if is_placeholder(outlived) && universe(outlived) > universe(rvid) {
    |                                                                     -------- ^^^^ expected `RegionVid`, found `&RegionVid`
    |                                                                     arguments to this function are incorrect
    |
note: expected because the closure was earlier called with an argument of type `rustc_middle::ty::RegionVid`
   --> compiler/rustc_borrowck/src/constraints/mod.rs:104:57
   --> compiler/rustc_borrowck/src/constraints/mod.rs:104:57
    |
104 |                 if is_placeholder(outlived) && universe(outlived) > universe(rvid) {
    |                                                -------- ^^^^^^^^ expected because this argument is of type `rustc_middle::ty::RegionVid`
    |                                                in this closure call
note: closure parameter defined here
   --> compiler/rustc_borrowck/src/constraints/mod.rs:74:25
    |
    |
74  |         let universe = |rvid: RegionVid| definitions[rvid].universe;
help: consider dereferencing the borrow
    |
    |
104 |                 if is_placeholder(outlived) && universe(outlived) > universe(*rvid) {

error[E0308]: mismatched types
   --> compiler/rustc_borrowck/src/constraints/mod.rs:108:34
    |
    |
108 |                         universe(rvid)
    |                         -------- ^^^^ expected `RegionVid`, found `&RegionVid`
    |                         arguments to this function are incorrect
    |
note: expected because the closure was earlier called with an argument of type `rustc_middle::ty::RegionVid`
   --> compiler/rustc_borrowck/src/constraints/mod.rs:104:57
   --> compiler/rustc_borrowck/src/constraints/mod.rs:104:57
    |
104 |                 if is_placeholder(outlived) && universe(outlived) > universe(rvid) {
    |                                                -------- ^^^^^^^^ expected because this argument is of type `rustc_middle::ty::RegionVid`
    |                                                in this closure call
note: closure parameter defined here
   --> compiler/rustc_borrowck/src/constraints/mod.rs:74:25
    |
    |
74  |         let universe = |rvid: RegionVid| definitions[rvid].universe;
help: consider dereferencing the borrow
    |
    |
108 |                         universe(*rvid)

    Checking rustc_mir_transform v0.0.0 (/checkout/compiler/rustc_mir_transform)
For more information about this error, try `rustc --explain E0308`.
error: could not compile `rustc_borrowck` (lib) due to 5 previous errors
```

</details>

2024-04-17 13:44 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8722934518/job/23929945293) [(plain)](https://github.com/rust-lang/rust/commit/9674cee3af7cd9bee297fc618e73c8970925797d/checks/23929945293/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling memchr v2.5.0
   Compiling std v0.0.0 (/checkout/library/std)
   Compiling compiler_builtins v0.1.109
thread 'rustc' panicked at compiler/rustc_borrowck/src/region_infer/mod.rs:1519:9:
assertion failed: self.scc_values.placeholders_contained_in(longer_fr_scc).next().is_none()
   0:     0x7ff1c74a657f - <std[b6cc9835fef5897b]::sys_common::backtrace::_print::DisplayBacktrace as core[2e9ba8b09c60eab9]::fmt::Display>::fmt
   1:     0x7ff1c74fd880 - core[2e9ba8b09c60eab9]::fmt::write
   2:     0x7ff1c749b5e9 - <std[b6cc9835fef5897b]::sys::pal::unix::stdio::Stderr as std[b6cc9835fef5897b]::io::Write>::write_fmt
   3:     0x7ff1c74a634e - std[b6cc9835fef5897b]::sys_common::backtrace::print
   3:     0x7ff1c74a634e - std[b6cc9835fef5897b]::sys_common::backtrace::print
   4:     0x7ff1c74a90aa - std[b6cc9835fef5897b]::panicking::default_hook::{closure#1}
   5:     0x7ff1c74a8dc1 - std[b6cc9835fef5897b]::panicking::default_hook
   6:     0x7ff1c81262d8 - <alloc[e9cc6f24807e3585]::boxed::Box<rustc_driver_impl[d73c47798b57e8c1]::install_ice_hook::{closure#0}> as core[2e9ba8b09c60eab9]::ops::function::Fn<(&dyn for<'a, 'b> core[2e9ba8b09c60eab9]::ops::function::Fn<(&'a core[2e9ba8b09c60eab9]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[2e9ba8b09c60eab9]::marker::Sync + core[2e9ba8b09c60eab9]::marker::Send, &core[2e9ba8b09c60eab9]::panic::panic_info::PanicInfo)>>::call
   7:     0x7ff1c74a9735 - std[b6cc9835fef5897b]::panicking::rust_panic_with_hook
   8:     0x7ff1c74a94ad - std[b6cc9835fef5897b]::panicking::begin_panic_handler::{closure#0}
   9:     0x7ff1c74a6b59 - std[b6cc9835fef5897b]::sys_common::backtrace::__rust_end_short_backtrace::<std[b6cc9835fef5897b]::panicking::begin_panic_handler::{closure#0}, !>
  11:     0x7ff1c74637f6 - core[2e9ba8b09c60eab9]::panicking::panic_fmt
  12:     0x7ff1c746389f - core[2e9ba8b09c60eab9]::panicking::panic
  13:     0x7ff1c991ae36 - <rustc_borrowck[e74d3702e58f69c2]::region_infer::RegionInferenceContext>::solve
  13:     0x7ff1c991ae36 - <rustc_borrowck[e74d3702e58f69c2]::region_infer::RegionInferenceContext>::solve
  14:     0x7ff1c99d6b3e - rustc_borrowck[e74d3702e58f69c2]::nll::compute_regions
  15:     0x7ff1c97c62ce - rustc_borrowck[e74d3702e58f69c2]::do_mir_borrowck
  16:     0x7ff1c97af16f - rustc_borrowck[e74d3702e58f69c2]::mir_borrowck
  17:     0x7ff1c9bbc7b5 - rustc_query_impl[c6b598c0f36a9172]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c6b598c0f36a9172]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1d5dfdcbbb4e6614]::query::erase::Erased<[u8; 8usize]>>
  18:     0x7ff1c9ed7295 - <rustc_query_impl[c6b598c0f36a9172]::query_impl::mir_borrowck::dynamic_query::{closure#2} as core[2e9ba8b09c60eab9]::ops::function::FnOnce<(rustc_middle[1d5dfdcbbb4e6614]::ty::context::TyCtxt, rustc_span[a10b0b0cef9c068b]::def_id::LocalDefId)>>::call_once
  19:     0x7ff1ca02d7b7 - rustc_query_system[e74e1ec916c4461c]::query::plumbing::try_execute_query::<rustc_query_impl[c6b598c0f36a9172]::DynamicConfig<rustc_query_system[e74e1ec916c4461c]::query::caches::VecCache<rustc_span[a10b0b0cef9c068b]::def_id::LocalDefId, rustc_middle[1d5dfdcbbb4e6614]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c6b598c0f36a9172]::plumbing::QueryCtxt, false>
  20:     0x7ff1c9db1d84 - rustc_query_impl[c6b598c0f36a9172]::query_impl::mir_borrowck::get_query_non_incr::__rust_end_short_backtrace
  21:     0x7ff1c8afc40c - rustc_middle[1d5dfdcbbb4e6614]::query::plumbing::query_get_at::<rustc_query_system[e74e1ec916c4461c]::query::caches::VecCache<rustc_span[a10b0b0cef9c068b]::def_id::LocalDefId, rustc_middle[1d5dfdcbbb4e6614]::query::erase::Erased<[u8; 8usize]>>>
  22:     0x7ff1c8b13e4b - rustc_hir_analysis[96be6b698472c4e7]::collect::type_of::opaque::find_opaque_ty_constraints_for_rpit
  23:     0x7ff1c9bc084a - rustc_query_impl[c6b598c0f36a9172]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c6b598c0f36a9172]::query_impl::type_of_opaque::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1d5dfdcbbb4e6614]::query::erase::Erased<[u8; 8usize]>>
  24:     0x7ff1c9e85e29 - <rustc_query_impl[c6b598c0f36a9172]::query_impl::type_of_opaque::dynamic_query::{closure#2} as core[2e9ba8b09c60eab9]::ops::function::FnOnce<(rustc_middle[1d5dfdcbbb4e6614]::ty::context::TyCtxt, rustc_span[a10b0b0cef9c068b]::def_id::DefId)>>::call_once
  25:     0x7ff1c9f70634 - rustc_query_system[e74e1ec916c4461c]::query::plumbing::try_execute_query::<rustc_query_impl[c6b598c0f36a9172]::DynamicConfig<rustc_query_system[e74e1ec916c4461c]::query::caches::DefIdCache<rustc_middle[1d5dfdcbbb4e6614]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c6b598c0f36a9172]::plumbing::QueryCtxt, false>
  26:     0x7ff1c9e97a17 - rustc_query_impl[c6b598c0f36a9172]::query_impl::type_of_opaque::get_query_non_incr::__rust_end_short_backtrace
  27:     0x7ff1c8b3677f - rustc_middle[1d5dfdcbbb4e6614]::query::plumbing::query_get_at::<rustc_query_system[e74e1ec916c4461c]::query::caches::DefIdCache<rustc_middle[1d5dfdcbbb4e6614]::query::erase::Erased<[u8; 8usize]>>>
  28:     0x7ff1c8b55de3 - rustc_hir_analysis[96be6b698472c4e7]::collect::type_of::type_of
  29:     0x7ff1c9bdd957 - rustc_query_impl[c6b598c0f36a9172]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c6b598c0f36a9172]::query_impl::type_of::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1d5dfdcbbb4e6614]::query::erase::Erased<[u8; 8usize]>>
  30:     0x7ff1c9e94829 - <rustc_query_impl[c6b598c0f36a9172]::query_impl::type_of::dynamic_query::{closure#2} as core[2e9ba8b09c60eab9]::ops::function::FnOnce<(rustc_middle[1d5dfdcbbb4e6614]::ty::context::TyCtxt, rustc_span[a10b0b0cef9c068b]::def_id::DefId)>>::call_once
  31:     0x7ff1c9f70634 - rustc_query_system[e74e1ec916c4461c]::query::plumbing::try_execute_query::<rustc_query_impl[c6b598c0f36a9172]::DynamicConfig<rustc_query_system[e74e1ec916c4461c]::query::caches::DefIdCache<rustc_middle[1d5dfdcbbb4e6614]::query::erase::Erased<[u8; 8usize]>>, false, false, false>, rustc_query_impl[c6b598c0f36a9172]::plumbing::QueryCtxt, false>
  32:     0x7ff1c9e972e7 - rustc_query_impl[c6b598c0f36a9172]::query_impl::type_of::get_query_non_incr::__rust_end_short_backtrace
  33:     0x7ff1c9474dff - rustc_middle[1d5dfdcbbb4e6614]::query::plumbing::query_get_at::<rustc_query_system[e74e1ec916c4461c]::query::caches::DefIdCache<rustc_middle[1d5dfdcbbb4e6614]::query::erase::Erased<[u8; 8usize]>>>
  34:     0x7ff1c947f3ab - <rustc_privacy[34f0973f123aa874]::ReachEverythingInTheInterfaceVisitor>::ty
  35:     0x7ff1c947d8da - <rustc_privacy[34f0973f123aa874]::EmbargoVisitor as rustc_hir[d01a24601fbeb471]::intravisit::Visitor>::visit_item
  36:     0x7ff1c9496d97 - <rustc_middle[1d5dfdcbbb4e6614]::hir::map::Map>::visit_all_item_likes_in_crate::<rustc_privacy[34f0973f123aa874]::EmbargoVisitor>
  37:     0x7ff1c94837c8 - rustc_privacy[34f0973f123aa874]::effective_visibilities
  38:     0x7ff1c9bd0583 - rustc_query_impl[c6b598c0f36a9172]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[c6b598c0f36a9172]::query_impl::effective_visibilities::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1d5dfdcbbb4e6614]::query::erase::Erased<[u8; 8usize]>>
  39:     0x7ff1c9e8e8d1 - <rustc_query_impl[c6b598c0f36a9172]::query_impl::effective_visibilities::dynamic_query::{closure#2} as core[2e9ba8b09c60eab9]::ops::function::FnOnce<(rustc_middle[1d5dfdcbbb4e6614]::ty::context::TyCtxt, ())>>::call_once
  40:     0x7ff1c9f804bc - rustc_query_system[e74e1ec916c4461c]::query::plumbing::try_execute_query::<rus [...]

2024-04-19 13:27 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8754254975/job/24025611239) [(plain)](https://github.com/rust-lang/rust/commit/a20af64476d7858e453ce7f156f1a1aefa6f70ac/checks/24025611239/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    |
help: `max_reached` is initially defined here
   --> compiler/rustc_data_structures/src/graph/scc/mod.rs:508:17
    |
508 |             let max_reached = std::cmp::max(*max_reached, (self.weight)(node));
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_locals
    = note: `-D clippy::redundant-locals` implied by `-D clippy::correctness`
    = help: to override `-D clippy::correctness` add `#[allow(clippy::redundant_locals)]`

```

</details>

2024-04-25 11:03 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8830249488/job/24242982649) [(plain)](https://github.com/rust-lang/rust/commit/d13cee46fd7c54e9938affe57053adee444bae76/checks/24242982649/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 exporting to docker image format
#16 sending tarball 30.3s done
#16 DONE 34.8s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
diff of stderr:

2   --> $DIR/due-to-where-clause.rs:2:5
3    |
4 LL |     test::<FooS>(&mut 42);
-    |     ^^^^^^^^^^^^ implementation of `Foo` is not general enough
+    |     ^^^^^^^^^^^^^^^^^^^^^ implementation of `Foo` is not general enough
6    |
7    = note: `FooS<'_>` must implement `Foo<'0>`, for any lifetime `'0`...
8    = note: ...but `FooS<'_>` actually implements `Foo<'1>`, for some specific lifetime `'1`

The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause/due-to-where-clause.stderr
To update references, rerun the tests and pass the `--bless` flag
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args higher-ranked/trait-bounds/due-to-where-clause.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/higher-ranked/trait-bounds/due-to-where-clause.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause/auxiliary"
--- stderr -------------------------------
error: implementation of `Foo` is not general enough
##[error]  --> /checkout/tests/ui/higher-ranked/trait-bounds/due-to-where-clause.rs:2:5
   |
   |
LL |     test::<FooS>(&mut 42); //~ ERROR implementation of `Foo` is not general enough
   |     ^^^^^^^^^^^^^^^^^^^^^ implementation of `Foo` is not general enough
   |
   = note: `FooS<'_>` must implement `Foo<'0>`, for any lifetime `'0`...
   = note: ...but `FooS<'_>` actually implements `Foo<'1>`, for some specific lifetime `'1`
error: aborting due to 1 previous error
------------------------------------------


```

</details>

2024-04-26 12:56 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8848368214/job/24298066251) [(plain)](https://github.com/rust-lang/rust/commit/8ebcfbf42c07ba04e6b112baee36f7704cd2986c/checks/24298066251/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#17 exporting to docker image format
#17 sending tarball 30.0s done
#17 DONE 35.0s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
---- [ui] tests/ui/generic-associated-types/bugs/hrtb-implied-1.rs stdout ----

error: ui test compiled successfully!
status: exit status: 0
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/generic-associated-types/bugs/hrtb-implied-1.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/generic-associated-types/bugs/hrtb-implied-1" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/generic-associated-types/bugs/hrtb-implied-1/auxiliary"
stderr: none


---- [ui] tests/ui/generic-associated-types/bugs/hrtb-implied-2.rs stdout ----
---- [ui] tests/ui/generic-associated-types/bugs/hrtb-implied-2.rs stdout ----
diff of stderr:

- error[E0521]: borrowed data escapes outside of function
+ error: `I` does not live long enough
2   --> $DIR/hrtb-implied-2.rs:18:17
3    |
- LL | fn fails<I: LendingIterator, F>(iter: &mut I, f: F) -> bool
-    |                                 ----  - let's call the lifetime of this reference `'1`
-    |                                 `iter` is a reference that is only valid in the function body
- ...
9 LL |     let _next = iter2.next();
10    |                 ^^^^^^^^^^^^
10    |                 ^^^^^^^^^^^^
-    |                 |
-    |                 `iter` escapes the function body here
-    |                 argument requires that `'1` must outlive `'static`
+ error: `I` does not live long enough
+   --> $DIR/hrtb-implied-2.rs:18:17
14    |
14    |
-    = note: requirement occurs because of a mutable reference to `Eat<&mut I, F>`
-    = note: mutable references are invariant over their type parameter
-    = help: see <https://doc.rust-lang.org/nomicon/subtyping.html> for more information about variance
-    = note: due to current limitations in the borrow checker, this implies a `'static` lifetime
+ LL |     let _next = iter2.next();
+    |
+    |
+    = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`
- error: aborting due to 1 previous error
+ error: `I` does not live long enough
+   --> $DIR/hrtb-implied-2.rs:18:17
+    |
+    |
+ LL |     let _next = iter2.next();
+    |
+    |
+    = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`
- For more information about this error, try `rustc --explain E0521`.
+ error: `I` does not live long enough
+   --> $DIR/hrtb-implied-2.rs:18:17
+    |
+    |
+ LL |     let _next = iter2.next();
+    |
+    |
+    = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`
+ error: `I` does not live long enough
+   --> $DIR/hrtb-implied-2.rs:18:17
+    |
+    |
+ LL |     let _next = iter2.next();
+    |
+    |
+    = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`
+ error: `I` does not live long enough
+   --> $DIR/hrtb-implied-2.rs:18:17
+    |
+    |
+ LL |     let _next = iter2.next();
+    |
+    |
+    = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`
+ error: `I` does not live long enough
+   --> $DIR/hrtb-implied-2.rs:18:17
+    |
+    |
+ LL |     let _next = iter2.next();
+    |
+    |
+    = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`
+ error: `I` does not live long enough
+   --> $DIR/hrtb-implied-2.rs:18:17
+    |
+    |
+ LL |     let _next = iter2.next();
+    |
+    |
+    = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`
+ error: aborting due to 8 previous errors
+ 
23 



The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/generic-associated-types/bugs/hrtb-implied-2/hrtb-implied-2.stderr
To only update this specific test, also pass `--test-args generic-associated-types/bugs/hrtb-implied-2.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/generic-associated-types/bugs/hrtb-implied-2.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/generic-associated-types/bugs/hrtb-implied-2" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/generic-associated-types/bugs/hrtb-implied-2/auxiliary"
--- stderr -------------------------------
error: `I` does not live long enough
##[error]  --> /checkout/tests/ui/generic-associated-types/bugs/hrtb-implied-2.rs:18:17
   |
---
   |
LL |     let _next = iter2.next();
   |                 ^^^^^^^^^^^^
   |
   = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`
error: `I` does not live long enough
##[error]  --> /checkout/tests/ui/generic-associated-types/bugs/hrtb-implied-2.rs:18:17
   |
LL |     let _next = iter2.next();
LL |     let _next = iter2.next();
   |     [...]

2024-04-30 14:51 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8896657146/job/24429812599) [(plain)](https://github.com/rust-lang/rust/commit/8575343af8b0d9ab570fadb2f9be32f22f289896/checks/24429812599/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#17 exporting to docker image format
#17 sending tarball 29.9s done
#17 DONE 37.3s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
diff of stderr:

2   --> $DIR/due-to-where-clause.rs:2:5
3    |
4 LL |     test::<FooS>(&mut 42);
-    |     ^^^^^^^^^^^^ implementation of `Foo` is not general enough
+    |     ^^^^^^^^^^^^^^^^^^^^^ implementation of `Foo` is not general enough
6    |
7    = note: `FooS<'_>` must implement `Foo<'0>`, for any lifetime `'0`...
8    = note: ...but `FooS<'_>` actually implements `Foo<'1>`, for some specific lifetime `'1`

The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause/due-to-where-clause.stderr
To update references, rerun the tests and pass the `--bless` flag
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args higher-ranked/trait-bounds/due-to-where-clause.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/higher-ranked/trait-bounds/due-to-where-clause.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause/auxiliary"
--- stderr -------------------------------
error: implementation of `Foo` is not general enough
##[error]  --> /checkout/tests/ui/higher-ranked/trait-bounds/due-to-where-clause.rs:2:5
   |
   |
LL |     test::<FooS>(&mut 42); //~ ERROR implementation of `Foo` is not general enough
   |     ^^^^^^^^^^^^^^^^^^^^^ implementation of `Foo` is not general enough
   |
   = note: `FooS<'_>` must implement `Foo<'0>`, for any lifetime `'0`...
   = note: ...but `FooS<'_>` actually implements `Foo<'1>`, for some specific lifetime `'1`
error: aborting due to 1 previous error
------------------------------------------


```

</details>

2024-05-02 09:17 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8921259483/job/24501015691) [(plain)](https://github.com/rust-lang/rust/commit/388f1918750d84d4cf71c96f947f25671f3d16b4/checks/24501015691/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#17 exporting to docker image format
#17 sending tarball 29.6s done
#17 DONE 33.1s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
diff of stderr:

2   --> $DIR/due-to-where-clause.rs:2:5
3    |
4 LL |     test::<FooS>(&mut 42);
-    |     ^^^^^^^^^^^^ implementation of `Foo` is not general enough
+    |     ^^^^^^^^^^^^^^^^^^^^^ implementation of `Foo` is not general enough
6    |
7    = note: `FooS<'_>` must implement `Foo<'0>`, for any lifetime `'0`...
8    = note: ...but `FooS<'_>` actually implements `Foo<'1>`, for some specific lifetime `'1`

The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause/due-to-where-clause.stderr
To update references, rerun the tests and pass the `--bless` flag
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args higher-ranked/trait-bounds/due-to-where-clause.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/higher-ranked/trait-bounds/due-to-where-clause.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause/auxiliary"
--- stderr -------------------------------
error: implementation of `Foo` is not general enough
##[error]  --> /checkout/tests/ui/higher-ranked/trait-bounds/due-to-where-clause.rs:2:5
   |
   |
LL |     test::<FooS>(&mut 42); //~ ERROR implementation of `Foo` is not general enough
   |     ^^^^^^^^^^^^^^^^^^^^^ implementation of `Foo` is not general enough
   |
   = note: `FooS<'_>` must implement `Foo<'0>`, for any lifetime `'0`...
   = note: ...but `FooS<'_>` actually implements `Foo<'1>`, for some specific lifetime `'1`
error: aborting due to 1 previous error
------------------------------------------


```

</details>

2024-05-02 09:59 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8921792427/job/24502629774) [(plain)](https://github.com/rust-lang/rust/commit/da332850fc39f37bb8f4ad74d852fe6a8ef156b7/checks/24502629774/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 exporting to docker image format
#16 sending tarball 31.1s done
#16 DONE 36.8s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
diff of stderr:

2   --> $DIR/due-to-where-clause.rs:2:5
3    |
4 LL |     test::<FooS>(&mut 42);
-    |     ^^^^^^^^^^^^ implementation of `Foo` is not general enough
+    |     ^^^^^^^^^^^^^^^^^^^^^ implementation of `Foo` is not general enough
6    |
7    = note: `FooS<'_>` must implement `Foo<'0>`, for any lifetime `'0`...
8    = note: ...but `FooS<'_>` actually implements `Foo<'1>`, for some specific lifetime `'1`

The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause/due-to-where-clause.stderr
To update references, rerun the tests and pass the `--bless` flag
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args higher-ranked/trait-bounds/due-to-where-clause.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/higher-ranked/trait-bounds/due-to-where-clause.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause/auxiliary"
--- stderr -------------------------------
error: implementation of `Foo` is not general enough
##[error]  --> /checkout/tests/ui/higher-ranked/trait-bounds/due-to-where-clause.rs:2:5
   |
   |
LL |     test::<FooS>(&mut 42); //~ ERROR implementation of `Foo` is not general enough
   |     ^^^^^^^^^^^^^^^^^^^^^ implementation of `Foo` is not general enough
   |
   = note: `FooS<'_>` must implement `Foo<'0>`, for any lifetime `'0`...
   = note: ...but `FooS<'_>` actually implements `Foo<'1>`, for some specific lifetime `'1`
error: aborting due to 1 previous error
------------------------------------------


```

</details>

2024-05-02 11:02 UTC, lqd commented
@bors try @rust-timer queue

2024-05-02 11:02 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2024-05-02 11:06 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8922623346/job/24505156780) [(plain)](https://github.com/rust-lang/rust/commit/f78dbeb7d13849e634fbd748f674e4a64d219fa2/checks/24505156780/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#17 exporting to docker image format
#17 sending tarball 31.2s done
#17 DONE 36.3s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
diff of stderr:

2   --> $DIR/due-to-where-clause.rs:2:5
3    |
4 LL |     test::<FooS>(&mut 42);
-    |     ^^^^^^^^^^^^ implementation of `Foo` is not general enough
+    |     ^^^^^^^^^^^^^^^^^^^^^ implementation of `Foo` is not general enough
6    |
7    = note: `FooS<'_>` must implement `Foo<'0>`, for any lifetime `'0`...
8    = note: ...but `FooS<'_>` actually implements `Foo<'1>`, for some specific lifetime `'1`

The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause/due-to-where-clause.stderr
To update references, rerun the tests and pass the `--bless` flag
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args higher-ranked/trait-bounds/due-to-where-clause.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/higher-ranked/trait-bounds/due-to-where-clause.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/higher-ranked/trait-bounds/due-to-where-clause/auxiliary"
--- stderr -------------------------------
error: implementation of `Foo` is not general enough
##[error]  --> /checkout/tests/ui/higher-ranked/trait-bounds/due-to-where-clause.rs:2:5
   |
   |
LL |     test::<FooS>(&mut 42); //~ ERROR implementation of `Foo` is not general enough
   |     ^^^^^^^^^^^^^^^^^^^^^ implementation of `Foo` is not general enough
   |
   = note: `FooS<'_>` must implement `Foo<'0>`, for any lifetime `'0`...
   = note: ...but `FooS<'_>` actually implements `Foo<'1>`, for some specific lifetime `'1`
error: aborting due to 1 previous error
------------------------------------------


```

</details>

2024-05-02 12:42 UTC, rust-timer commented
Queued 8cebcbc1a4ffa1f8b7469a6472c9d117d3f26772 with parent fcc06c894b17f4d0c80b8934ea5f27faa894c960, future [comparison URL](https://perf.rust-lang.org/compare.html?start=fcc06c894b17f4d0c80b8934ea5f27faa894c960&end=8cebcbc1a4ffa1f8b7469a6472c9d117d3f26772).
There is currently 1 preceding artifact in the [queue](https://perf.rust-lang.org/status.html).
It will probably take at least ~2.4 hours until the benchmark run finishes.
<!-- rust-timer: temporary -->

2024-05-02 14:53 UTC, rust-timer commented
Finished benchmarking commit (8cebcbc1a4ffa1f8b7469a6472c9d117d3f26772): [comparison URL](https://perf.rust-lang.org/compare.html?start=fcc06c894b17f4d0c80b8934ea5f27faa894c960&end=8cebcbc1a4ffa1f8b7469a6472c9d117d3f26772&stat=instructions:u).

### Overall result: ❌ regressions - ACTION NEEDED


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: -S-waiting-on-perf +perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=fcc06c894b17f4d0c80b8934ea5f27faa894c960&end=8cebcbc1a4ffa1f8b7469a6472c9d117d3f26772&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.9%  | [0.2%, 2.0%]   | 62    |
| Regressions ❌ <br /> (secondary)  | 1.6%  | [0.1%, 5.9%]   | 42    |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -0.7% | [-0.7%, -0.7%] | 1     |
| All ❌✅ (primary)                 | 0.9%  | [0.2%, 2.0%]   | 62    |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=fcc06c894b17f4d0c80b8934ea5f27faa894c960&end=8cebcbc1a4ffa1f8b7469a6472c9d117d3f26772&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -2.4% | [-2.4%, -2.4%] | 1     |
| All ❌✅ (primary)                 | -     | -              | 0     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=fcc06c894b17f4d0c80b8934ea5f27faa894c960&end=8cebcbc1a4ffa1f8b7469a6472c9d117d3f26772&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.9% | [0.5%, 1.3%] | 6     |
| Regressions ❌ <br /> (secondary)  | 2.9% | [2.6%, 3.2%] | 6     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 0.9% | [0.5%, 1.3%] | 6     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=fcc06c894b17f4d0c80b8934ea5f27faa894c960&end=8cebcbc1a4ffa1f8b7469a6472c9d117d3f26772&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 671.059s -> 677.488s (0.96%)
**Artifact size**: 315.99 MiB -> 316.15 MiB (0.05%)

2024-05-11 10:06 UTC, lqd commented
@bors try @rust-timer queue

2024-05-11 10:06 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2024-05-11 11:44 UTC, rust-timer commented
Queued ef1a38581693a4afd3dea2988db05fd31808ffab with parent be7549f82c194c7a5dc8f34ed0541bfebbaf33ea, future [comparison URL](https://perf.rust-lang.org/compare.html?start=be7549f82c194c7a5dc8f34ed0541bfebbaf33ea&end=ef1a38581693a4afd3dea2988db05fd31808ffab).
There is currently 1 preceding artifact in the [queue](https://perf.rust-lang.org/status.html).
It will probably take at least ~1.3 hours until the benchmark run finishes.
<!-- rust-timer: temporary -->

2024-05-11 13:07 UTC, rust-timer commented
Finished benchmarking commit (ef1a38581693a4afd3dea2988db05fd31808ffab): [comparison URL](https://perf.rust-lang.org/compare.html?start=be7549f82c194c7a5dc8f34ed0541bfebbaf33ea&end=ef1a38581693a4afd3dea2988db05fd31808ffab&stat=instructions:u).

### Overall result: ❌ regressions - ACTION NEEDED


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: -S-waiting-on-perf +perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=be7549f82c194c7a5dc8f34ed0541bfebbaf33ea&end=ef1a38581693a4afd3dea2988db05fd31808ffab&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.5% | [0.2%, 1.4%] | 42    |
| Regressions ❌ <br /> (secondary)  | 2.0% | [0.1%, 5.7%] | 26    |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 0.5% | [0.2%, 1.4%] | 42    |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=be7549f82c194c7a5dc8f34ed0541bfebbaf33ea&end=ef1a38581693a4afd3dea2988db05fd31808ffab&stat=max-rss)
This benchmark run did not return any relevant results for this metric.

### [Cycles](https://perf.rust-lang.org/compare.html?start=be7549f82c194c7a5dc8f34ed0541bfebbaf33ea&end=ef1a38581693a4afd3dea2988db05fd31808ffab&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 2.5% | [2.1%, 2.9%] | 6     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=be7549f82c194c7a5dc8f34ed0541bfebbaf33ea&end=ef1a38581693a4afd3dea2988db05fd31808ffab&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 675.209s -> 675.281s (0.01%)
**Artifact size**: 315.95 MiB -> 315.99 MiB (0.01%)

2024-05-20 13:42 UTC, amandasystems commented
Waiting for #125069 to merge!

2024-06-13 14:39 UTC, amandasystems commented
Ready for a perf run to see how the constraint rewriting affects performance!

2024-06-13 14:40 UTC, Kobzol commented
@bors try @rust-timer queue

2024-06-13 14:40 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2024-06-13 15:09 UTC, amandasystems commented
I guess I can also do this

@rustbot ready

2024-06-13 16:19 UTC, rust-timer commented
Queued 5897177e1ce14047ae533270057b6960c87f6955 with parent 9fdbfe1441a82e96e3f99ae199ff5348d8d948ae, future [comparison URL](https://perf.rust-lang.org/compare.html?start=9fdbfe1441a82e96e3f99ae199ff5348d8d948ae&end=5897177e1ce14047ae533270057b6960c87f6955).
There is currently 1 preceding artifact in the [queue](https://perf.rust-lang.org/status.html).
It will probably take at least ~1.5 hours until the benchmark run finishes.
<!-- rust-timer: temporary -->

2024-06-13 16:26 UTC, lqd commented
This looks good to me. (Though I'd still like to have some comments on the reason why we're doing this, so that people reading the code will know. We can workshop it during our next meeting)

2024-06-13 17:50 UTC, rust-timer commented
Finished benchmarking commit (5897177e1ce14047ae533270057b6960c87f6955): [comparison URL](https://perf.rust-lang.org/compare.html?start=9fdbfe1441a82e96e3f99ae199ff5348d8d948ae&end=5897177e1ce14047ae533270057b6960c87f6955&stat=instructions:u).

### Overall result: ❌✅ regressions and improvements - ACTION NEEDED


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: -S-waiting-on-perf +perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=9fdbfe1441a82e96e3f99ae199ff5348d8d948ae&end=5897177e1ce14047ae533270057b6960c87f6955&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | 1.2%  | [0.4%, 1.5%]   | 8     |
| Improvements ✅ <br /> (primary)   | -0.4% | [-0.4%, -0.4%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -0.4% | [-0.4%, -0.4%] | 1     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=9fdbfe1441a82e96e3f99ae199ff5348d8d948ae&end=5897177e1ce14047ae533270057b6960c87f6955&stat=max-rss)
<details>
<summary>Results (primary -2.3%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -2.3% | [-2.3%, -2.3%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -2.3% | [-2.3%, -2.3%] | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=9fdbfe1441a82e96e3f99ae199ff5348d8d948ae&end=5897177e1ce14047ae533270057b6960c87f6955&stat=cycles:u)
<details>
<summary>Results (primary -3.5%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -3.5% | [-7.0%, -1.0%] | 13    |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -3.5% | [-7.0%, -1.0%] | 13    |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=9fdbfe1441a82e96e3f99ae199ff5348d8d948ae&end=5897177e1ce14047ae533270057b6960c87f6955&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 672.787s -> 671.233s (-0.23%)
**Artifact size**: 320.34 MiB -> 320.50 MiB (0.05%)

2024-06-14 08:11 UTC, amandasystems commented
Ping @nikomatsakis ready for review!

2024-06-14 08:59 UTC, lqd commented
BTW do all tests (without maybe the possible fuzzing ICE that you’ve been looking at) still pass with this PR when polonius next is enabled?

2024-06-14 10:39 UTC, amandasystems commented
> BTW do all tests (without maybe the possible fuzzing ICE that you’ve been looking at) still pass with this PR when polonius next is enabled?

I didn't realise you could enable it for the tests without compare-mode (which has a few failures that were there since before. Trying that now!

2024-06-14 14:20 UTC, nikomatsakis approved these changes
r=me with a nit

2024-06-14 14:20 UTC, nikomatsakis commented on compiler/rustc_borrowck/src/region_infer/mod.rs
>          self.universe().cannot_name(self.max_placeholder_universe_reached)
```suggestion
        self.min_universe().cannot_name(self.max_placeholder_universe_reached)
```

This name would have been clearer to me. I was paranoid and had to go find the definition.

2024-06-14 16:36 UTC, lqd commented
@craterbot check

2024-06-18 13:47 UTC, amandasystems commented
This is my first crater run so I'm not sure how to read the logs, but most of those errors look spurious to me, if not all of them.

2024-07-01 09:37 UTC, amandasystems commented
> r=me with a nit

Nit addressed (and I agree, that's just the sort of bad naming I know has confused me before)

2024-07-01 09:54 UTC, amandasystems commented
@nikomatsakis, @lqd: I have added a description for why this was done in commit 9be3a3d761060a047667226bd742346f8c25c6cf. Check if it looks ok to you!

2024-07-02 16:19 UTC, nikomatsakis approved these changes

2024-07-02 16:19 UTC, nikomatsakis commented
@bors r+

2024-07-03 03:42 UTC, merged

2024-07-03 06:07 UTC, rust-timer commented
Finished benchmarking commit (67f0d43890801f50ef2d24cd66de523f89ccb157): [comparison URL](https://perf.rust-lang.org/compare.html?start=6292b2af620dbd771ebb687c3a93c69ba8f97268&end=67f0d43890801f50ef2d24cd66de523f89ccb157&stat=instructions:u).

### Overall result: ❌ regressions - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=6292b2af620dbd771ebb687c3a93c69ba8f97268&end=67f0d43890801f50ef2d24cd66de523f89ccb157&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 1.3% | [1.2%, 1.4%] | 6     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=6292b2af620dbd771ebb687c3a93c69ba8f97268&end=67f0d43890801f50ef2d24cd66de523f89ccb157&stat=max-rss)
This benchmark run did not return any relevant results for this metric.

### [Cycles](https://perf.rust-lang.org/compare.html?start=6292b2af620dbd771ebb687c3a93c69ba8f97268&end=67f0d43890801f50ef2d24cd66de523f89ccb157&stat=cycles:u)
<details>
<summary>Results (primary 2.2%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 2.2% | [2.2%, 2.2%] | 1     |
| Regressions ❌ <br /> (secondary)  | -    | -            | 0     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 2.2% | [2.2%, 2.2%] | 1     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=6292b2af620dbd771ebb687c3a93c69ba8f97268&end=67f0d43890801f50ef2d24cd66de523f89ccb157&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 696.719s -> 695.519s (-0.17%)
**Artifact size**: 327.57 MiB -> 327.72 MiB (0.05%)

2024-07-08 08:37 UTC, lqd commented
> This is my first crater run so I'm not sure how to read the logs, but most of those errors look spurious to me, if not all of them.

Agreed, most of the 12 "regressions" look like crater errors.  Since these crates not tested in the run however, I've checked them all locally: they build with this PR without issues. 

We'll keep an eye out for possible new issues, and beta crater run regressions, that could be bisected to this PR, just in case the "spurious regressed" contains real effects (these can also be crater errors, but also contains OOMs). 

But things look currently fine in my opinion.