Add constants for f16 and f32
rust-lang/rust pull request #123850
Opened 2024-04-12 13:01 UTC by tspiteri

- Commit 1 adds associated constants for `f16`, excluding NaN and infinities as these are implemented using arithmetic for `f32` and `f64`.
- Commit 2 adds associated constants for `f128`, excluding NaN and infinities.
- Commit 3 adds constants in `std::f16::consts`.
- Commit 4 adds constants in `std::f128::consts`.

2024-04-12 13:08 UTC, fmease commented
cc @tgross35

2024-04-12 13:08 UTC, fmease commented on library/core/src/num/f128.rs
> +//! constants for the `f128` quadruple-precision floating point type.
```suggestion
//! Constants for the `f128` quadruple-precision floating point type.
```

2024-04-12 13:10 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8662476407/job/23754494494) [(plain)](https://github.com/rust-lang/rust/commit/8ea9405ddbffc47810fc2c00d8baa9e37a0bc9cd/checks/23754494494/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fbf2298f3eb - std::panicking::default_hook::{{closure}}::h743c1c016c642bf0
  10:     0x7fbf2298f143 - std::panicking::default_hook::h304853134c903f50
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/panicking.rs:292:9
  11:     0x7fbf2582c05d - std[999bdecce25602ed]::panicking::update_hook::<alloc[5d2a9fe8278cb303]::boxed::Box<rustc_driver_impl[e6c4295f52574c92]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fbf2298fb50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h8e05c89c9dfd827c
  13:     0x7fbf2298fb50 - std::panicking::rust_panic_with_hook::h6987b578e7dec23c
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/panicking.rs:783:13
  14:     0x7fbf2298f859 - std::panicking::begin_panic_handler::{{closure}}::h5e61050e5431c199
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/panicking.rs:649:13
---
  22:     0x7fbf25b7c8f6 - <rustc_lint[6313896b7e65eed2]::late::LateContextAndPass<rustc_lint[6313896b7e65eed2]::late::RuntimeCombinedLateLintPass> as rustc_hir[121f359932e59ede]::intravisit::Visitor>::visit_nested_item
  23:     0x7fbf25b7b6dd - <rustc_lint[6313896b7e65eed2]::late::LateContextAndPass<rustc_lint[6313896b7e65eed2]::late::RuntimeCombinedLateLintPass> as rustc_hir[121f359932e59ede]::intravisit::Visitor>::visit_nested_item
  24:     0x7fbf25b7b6dd - <rustc_lint[6313896b7e65eed2]::late::LateContextAndPass<rustc_lint[6313896b7e65eed2]::late::RuntimeCombinedLateLintPass> as rustc_hir[121f359932e59ede]::intravisit::Visitor>::visit_nested_item
  25:     0x7fbf2724ff8a - rustc_lint[6313896b7e65eed2]::late::check_crate
  26:     0x7fbf27255e49 - rustc_interface[2cd87b402a7bbb07]::passes::analysis
  27:     0x7fbf27254f65 - rustc_query_impl[e29825a6f88888a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e29825a6f88888a7]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f6bb74e4dd5a8f75]::query::erase::Erased<[u8; 1usize]>>
  28:     0x7fbf27701ba2 - rustc_query_system[3350c2d9ca0121e2]::query::plumbing::try_execute_query::<rustc_query_impl[e29825a6f88888a7]::DynamicConfig<rustc_query_system[3350c2d9ca0121e2]::query::caches::SingleCache<rustc_middle[f6bb74e4dd5a8f75]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[e29825a6f88888a7]::plumbing::QueryCtxt, false>
  30:     0x7fbf275a5894 - rustc_interface[2cd87b402a7bbb07]::interface::run_compiler::<core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>, rustc_driver_impl[e6c4295f52574c92]::run_compiler::{closure#0}>::{closure#0}
  30:     0x7fbf275a5894 - rustc_interface[2cd87b402a7bbb07]::interface::run_compiler::<core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>, rustc_driver_impl[e6c4295f52574c92]::run_compiler::{closure#0}>::{closure#0}
  31:     0x7fbf278b1b2e - std[999bdecce25602ed]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[2cd87b402a7bbb07]::util::run_in_thread_with_globals<rustc_interface[2cd87b402a7bbb07]::interface::run_compiler<core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>, rustc_driver_impl[e6c4295f52574c92]::run_compiler::{closure#0}>::{closure#0}, core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>>
  32:     0x7fbf278b198a - <<std[999bdecce25602ed]::thread::Builder>::spawn_unchecked_<rustc_interface[2cd87b402a7bbb07]::util::run_in_thread_with_globals<rustc_interface[2cd87b402a7bbb07]::interface::run_compiler<core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>, rustc_driver_impl[e6c4295f52574c92]::run_compiler::{closure#0}>::{closure#0}, core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>>::{closure#1} as core[75bed1c93f3984e1]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  33:     0x7fbf229991e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3b366b3d6b556d67
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/alloc/src/boxed.rs:2020:9
  34:     0x7fbf229991e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49756348eb63eea1
  35:     0x7fbf229991e5 - std::sys::pal::unix::thread::Thread::new::thread_start::hdf802a7c2e3fdf20
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/sys/pal/unix/thread.rs:108:17
  36:     0x7fbf2263cac3 - <unknown>
  37:     0x7fbf226ce850 - <unknown>
  37:     0x7fbf226ce850 - <unknown>
  38:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new?template=ice.yml

warning: the ICE couldn't be written to `/checkout/rustc-ice-2024-04-12T13_10_22-13154.txt`: Read-only file system (os error 30)
note: rustc 1.78.0-beta.1 (efd9d2df1 2024-03-18) running on x86_64-unknown-linux-gnu


note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C codegen-units=1 -C debug-assertions=on -Z unstable-options -C symbol-mangling-version=legacy -Z unstable-options -Z unstable-options -Z force-unstable-if-unmarked -Z macro-backtrace -C split-debuginfo=off -C prefer-dynamic -Z validate-mir -Z mir-opt-level=3 -Z inline-mir -C link-args=-Wl,-z,origin -C link-args=-Wl,-rpath,$ORIGIN/../lib -C force-frame-pointers=yes -Z crate-attr=doc(html_root_url="https://doc.rust-lang.org/nightly/") -Z binary-dep-depinfo -Z force-unstable-if-unmarked
note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
```

</details>

2024-04-12 13:39 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8662881133/job/23755771311) [(plain)](https://github.com/rust-lang/rust/commit/e972a7f3f8efea2c42a0d6e72ff7dac55976f2c0/checks/23755771311/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fe4bf38f3eb - std::panicking::default_hook::{{closure}}::h743c1c016c642bf0
  10:     0x7fe4bf38f143 - std::panicking::default_hook::h304853134c903f50
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/panicking.rs:292:9
  11:     0x7fe4c222c05d - std[999bdecce25602ed]::panicking::update_hook::<alloc[5d2a9fe8278cb303]::boxed::Box<rustc_driver_impl[e6c4295f52574c92]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fe4bf38fb50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h8e05c89c9dfd827c
  13:     0x7fe4bf38fb50 - std::panicking::rust_panic_with_hook::h6987b578e7dec23c
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/panicking.rs:783:13
  14:     0x7fe4bf38f859 - std::panicking::begin_panic_handler::{{closure}}::h5e61050e5431c199
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/panicking.rs:649:13
---
  22:     0x7fe4c257c8f6 - <rustc_lint[6313896b7e65eed2]::late::LateContextAndPass<rustc_lint[6313896b7e65eed2]::late::RuntimeCombinedLateLintPass> as rustc_hir[121f359932e59ede]::intravisit::Visitor>::visit_nested_item
  23:     0x7fe4c257b6dd - <rustc_lint[6313896b7e65eed2]::late::LateContextAndPass<rustc_lint[6313896b7e65eed2]::late::RuntimeCombinedLateLintPass> as rustc_hir[121f359932e59ede]::intravisit::Visitor>::visit_nested_item
  24:     0x7fe4c257b6dd - <rustc_lint[6313896b7e65eed2]::late::LateContextAndPass<rustc_lint[6313896b7e65eed2]::late::RuntimeCombinedLateLintPass> as rustc_hir[121f359932e59ede]::intravisit::Visitor>::visit_nested_item
  25:     0x7fe4c3c4ff8a - rustc_lint[6313896b7e65eed2]::late::check_crate
  26:     0x7fe4c3c55e49 - rustc_interface[2cd87b402a7bbb07]::passes::analysis
  27:     0x7fe4c3c54f65 - rustc_query_impl[e29825a6f88888a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e29825a6f88888a7]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f6bb74e4dd5a8f75]::query::erase::Erased<[u8; 1usize]>>
  28:     0x7fe4c4101ba2 - rustc_query_system[3350c2d9ca0121e2]::query::plumbing::try_execute_query::<rustc_query_impl[e29825a6f88888a7]::DynamicConfig<rustc_query_system[3350c2d9ca0121e2]::query::caches::SingleCache<rustc_middle[f6bb74e4dd5a8f75]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[e29825a6f88888a7]::plumbing::QueryCtxt, false>
  30:     0x7fe4c3fa5894 - rustc_interface[2cd87b402a7bbb07]::interface::run_compiler::<core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>, rustc_driver_impl[e6c4295f52574c92]::run_compiler::{closure#0}>::{closure#0}
  30:     0x7fe4c3fa5894 - rustc_interface[2cd87b402a7bbb07]::interface::run_compiler::<core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>, rustc_driver_impl[e6c4295f52574c92]::run_compiler::{closure#0}>::{closure#0}
  31:     0x7fe4c42b1b2e - std[999bdecce25602ed]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[2cd87b402a7bbb07]::util::run_in_thread_with_globals<rustc_interface[2cd87b402a7bbb07]::interface::run_compiler<core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>, rustc_driver_impl[e6c4295f52574c92]::run_compiler::{closure#0}>::{closure#0}, core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>>
  32:     0x7fe4c42b198a - <<std[999bdecce25602ed]::thread::Builder>::spawn_unchecked_<rustc_interface[2cd87b402a7bbb07]::util::run_in_thread_with_globals<rustc_interface[2cd87b402a7bbb07]::interface::run_compiler<core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>, rustc_driver_impl[e6c4295f52574c92]::run_compiler::{closure#0}>::{closure#0}, core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>>::{closure#1} as core[75bed1c93f3984e1]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  33:     0x7fe4bf3991e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3b366b3d6b556d67
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/alloc/src/boxed.rs:2020:9
  34:     0x7fe4bf3991e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49756348eb63eea1
  35:     0x7fe4bf3991e5 - std::sys::pal::unix::thread::Thread::new::thread_start::hdf802a7c2e3fdf20
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/sys/pal/unix/thread.rs:108:17
  36:     0x7fe4bf05cac3 - <unknown>
  37:     0x7fe4bf0ee850 - <unknown>
  37:     0x7fe4bf0ee850 - <unknown>
  38:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new?template=ice.yml

warning: the ICE couldn't be written to `/checkout/rustc-ice-2024-04-12T13_39_12-13152.txt`: Read-only file system (os error 30)
note: rustc 1.78.0-beta.1 (efd9d2df1 2024-03-18) running on x86_64-unknown-linux-gnu


note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C codegen-units=1 -C debug-assertions=on -Z unstable-options -C symbol-mangling-version=legacy -Z unstable-options -Z unstable-options -Z force-unstable-if-unmarked -Z macro-backtrace -C split-debuginfo=off -C prefer-dynamic -Z validate-mir -Z mir-opt-level=3 -Z inline-mir -C link-args=-Wl,-z,origin -C link-args=-Wl,-rpath,$ORIGIN/../lib -C force-frame-pointers=yes -Z crate-attr=doc(html_root_url="https://doc.rust-lang.org/nightly/") -Z binary-dep-depinfo -Z force-unstable-if-unmarked
note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
```

</details>

2024-04-12 13:48 UTC, tspiteri commented
Note that for constants gated under [`more_float_constants`](https://github.com/rust-lang/rust/issues/103883) for `f32` and `f64`, I used #103883 rather than #116909 as a tracking issue.

2024-04-12 13:49 UTC, tspiteri commented
The test failure seems to be a panic in beta clippy.

```
  thread 'rustc' panicked at src/tools/clippy/clippy_lints/src/float_literal.rs:145:26:
  not implemented: f16_f128
```

2024-04-12 16:39 UTC, tgross35 requested changes
Hey, thank you for the help here!

I was holding off on these until we had the ability to actually run code that involves these types, which unfortunately we won't until I get `compiler_builtins` updated (well, code will run on x86 but nothing else so we can't actually merge anything). I was trying to add as little as possible until we get tests, but don't have any big problem with adding these.

One change needed - the literals we have aren't high enough precision for f128. I have a Julia script to generate longer ones using arbitrary precision math, https://github.com/tgross35/apfloat-consts. You can just copy the consts from output.rs.

2024-04-12 16:42 UTC, tgross35 commented
> The test failure seems to be a panic in beta clippy.
> 
> ```
>   thread 'rustc' panicked at src/tools/clippy/clippy_lints/src/float_literal.rs:145:26:
>   not implemented: f16_f128
> ```

This is the other reason I haven't added too much more, clippy and CTFE both have some `unimplemented!` scattered around that can't be fixed until math is working (compiler_builtins...). You might be able to `#[allow(clippy::all)]` on this module.

@rustbot label +F-f16_and_f128

2024-04-16 10:13 UTC, tspiteri commented
Oops, I used 36 significant digits for `f128` constants. I stumbled because 36 decimal digits is enough for numbers which are representable (such as `EPSILON`, `MIN_POSITIVE`, `MAX`, etc.), but not for numbers that are not, where you may need many more digits especially if the exact decimal number is close to mid-way between two consecutive floating-point numbers.

I changed `f128` constants like `PI` to use 60 decimal significant digits, which is enough for all these constants. (I generated them with MPFR through the Rug crate, with rounding to the nearest just like the constants in the standard library for `f32` and `f64`.) For `f16` I just used the same literals that are used for `f32` and `f64`.

2024-04-16 10:14 UTC, tspiteri commented
For the clippy warning, I think clippy is already fine in nightly, so instead of adding extra clippy allows, I think I might just wait for the next beta to be cut.

2024-04-16 10:18 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8703844498/job/23870895798) [(plain)](https://github.com/rust-lang/rust/commit/3f290347863668bbcc4e7f058d5a7255b528033a/checks/23870895798/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Getting action download info
Download action repository 'msys2/setup-msys2@v2.22.0' (SHA:cc11e9188b693c2b100158c3322424c4cc1dadea)
Download action repository 'actions/checkout@v4' (SHA:b4ffde65f46336ab88eb53be808477a3936bae11)
Download action repository 'actions/upload-artifact@v4' (SHA:5d5d22a31266ced268874388b861e4b58bb5c2f3)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
---
COPY scripts/sccache.sh /scripts/
RUN sh /scripts/sccache.sh

COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt \
    && pip3 install virtualenv
COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---

#12 [5/8] COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
#12 DONE 0.0s

#13 [6/8] RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt     && pip3 install virtualenv
#13 0.433   Downloading binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
#13 0.449 Collecting boolean-py==4.0
#13 0.456   Downloading boolean.py-4.0-py3-none-any.whl (25 kB)
#13 0.473 Collecting chardet==5.1.0
---
#13 3.636 Building wheels for collected packages: reuse
#13 3.637   Building wheel for reuse (pyproject.toml): started
#13 3.963   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 3.963   Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=181117 sha256=f5f58750481f69515c2c0d1d503daf565e2565c370d07fc6aeb95fe3498b4269
#13 3.964   Stored in directory: /tmp/pip-ephem-wheel-cache-ao9wp896/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
#13 3.966 Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
#13 3.989   Attempting uninstall: setuptools
#13 3.990     Found existing installation: setuptools 59.6.0
#13 3.991     Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
#13 3.991     Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
#13 3.992     Can't uninstall 'setuptools'. No files were found to uninstall.
#13 4.668 Successfully installed binaryornot-0.4.4 boolean-py-4.0 chardet-5.1.0 jinja2-3.1.2 license-expression-30.0.0 markupsafe-2.1.1 python-debian-0.1.49 reuse-1.1.0 setuptools-66.0.0
#13 4.668 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 5.192 Collecting virtualenv
#13 5.242   Downloading virtualenv-20.25.1-py3-none-any.whl (3.8 MB)
#13 5.379      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 28.1 MB/s eta 0:00:00
#13 5.431 Collecting platformdirs<5,>=3.9.1
#13 5.439   Downloading platformdirs-4.2.0-py3-none-any.whl (17 kB)
#13 5.461 Collecting distlib<1,>=0.3.7
#13 5.468   Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
#13 5.515 Collecting filelock<4,>=3.12.2
#13 5.523   Downloading filelock-3.13.4-py3-none-any.whl (11 kB)
#13 5.523   Downloading filelock-3.13.4-py3-none-any.whl (11 kB)
#13 5.607 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 5.770 Successfully installed distlib-0.3.8 filelock-3.13.4 platformdirs-4.2.0 virtualenv-20.25.1
#13 DONE 5.8s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      182208 kB
DirectMap2M:     7157760 kB
DirectMap1G:    11534336 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
    Finished `dev` profile [unoptimized] target(s) in 0.03s
##[endgroup]
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/63f70b3d104e20289a1a0df82747066c3d85b9a1/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/llvm-63f70b3d104e20289a1a0df82747066c3d85b9a1-true/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm
---
   Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
    Finished `release` profile [optimized] target(s) in 25.10s
##[endgroup]
fmt check
##[error]Diff in /checkout/library/core/src/num/f128.rs at line 65:
     /// 1/sqrt(π)
     #[unstable(feature = "f128", issue = "116909")]
     // Also, #[unstable(feature = "more_float_constants", issue = "103883")]
-    pub const FRAC_1_SQRT_PI: f128 = 0.564189583547756286948079451560772585844050629328998856844086_f128;
+    pub const FRAC_1_SQRT_PI: f128 =
+        0.564189583547756286948079451560772585844050629328998856844086_f128;
     /// 2/π
     /// 2/π
     #[unstable(feature = "f128", issue = "116909")]
##[error]Diff in /checkout/library/core/src/num/f128.rs at line 73:
 
     /// 2/sqrt(π)
     #[unstable(feature = "f128", issue = "116909")]
-    pub const FRAC_2_SQRT_PI: f128 = 1.12837916709551257389615890312154517168810125865799771368817_f128;
+    pub const FRAC_2_SQRT_PI: f128 =
+        1.12837916709551257389615890312154517168810125865799771368817_f128;
     /// sqrt(2)
     /// sqrt(2)
     #[unstable(feature = "f128", issue = "116909")]
##[error]Diff in /checkout/library/core/src/num/f128.rs at line 81:
 
     /// 1/sqrt(2)
     #[unstable(feature = "f128", issue = "116909")]
-    pub const FRAC_1_SQRT_2: f128 = 0.707106781186547524400844362104849039284835937688474036588340_f128;
+    pub const FRAC_1_SQRT_2: f128 =
+        0.707106781186547524400844362104849039284835937688474036588340_f128;
     /// sqrt(3)
     /// sqrt(3)
     #[unstable(feature = "f128", issue = "116909")]
##[error]Diff in /checkout/library/core/src/num/f128.rs at line 91:
     /// 1/sqrt(3)
     #[unstable(feature = "f128", issue = "116909")]
     // Also, #[unstable(feature = "more_float_constants", issue = "103883")]
-    pub const FRAC_1_SQRT_3: f128 = 0.577350269189625764509148780501957455647601751270126876018602_f128;
+    pub const FRAC_1_SQRT_3: f128 =
+        0.577350269189625764509148780501957455647601751270126876018602_f128;
 
     /// Euler's number (e)
     #[unstable(feature = "f128", issue = "116909")]
Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/library/core/src/option.rs" "/checkout/library/core/src/ascii/ascii_char.rs" "/checkout/library/core/src/pat.rs" "/checkout/library/core/benches/num/flt2dec/strategy/dragon.rs" "/checkout/library/core/benches/num/flt2dec/strategy/grisu.rs" "/checkout/library/core/benches/num/mod.rs" "/checkout/library/core/benches/num/dec2flt/mod.rs" "/checkout/library/core/benches/num/int_pow/mod.rs" "/checkout/library/core/benches/array.rs" "/checkout/library/core/benches/lib.rs [...]

2024-04-16 10:32 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8703988728/job/23871323533) [(plain)](https://github.com/rust-lang/rust/commit/248813887e4de5941ee367f3ffc2503b954cb26b/checks/23871323533/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7f6c93bad3eb - std::panicking::default_hook::{{closure}}::h743c1c016c642bf0
  10:     0x7f6c93bad143 - std::panicking::default_hook::h304853134c903f50
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/panicking.rs:292:9
  11:     0x7f6c90a2c05d - std[999bdecce25602ed]::panicking::update_hook::<alloc[5d2a9fe8278cb303]::boxed::Box<rustc_driver_impl[e6c4295f52574c92]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7f6c93badb50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h8e05c89c9dfd827c
  13:     0x7f6c93badb50 - std::panicking::rust_panic_with_hook::h6987b578e7dec23c
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/panicking.rs:783:13
  14:     0x7f6c93bad859 - std::panicking::begin_panic_handler::{{closure}}::h5e61050e5431c199
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/panicking.rs:649:13
---
  22:     0x7f6c90d7c8f6 - <rustc_lint[6313896b7e65eed2]::late::LateContextAndPass<rustc_lint[6313896b7e65eed2]::late::RuntimeCombinedLateLintPass> as rustc_hir[121f359932e59ede]::intravisit::Visitor>::visit_nested_item
  23:     0x7f6c90d7b6dd - <rustc_lint[6313896b7e65eed2]::late::LateContextAndPass<rustc_lint[6313896b7e65eed2]::late::RuntimeCombinedLateLintPass> as rustc_hir[121f359932e59ede]::intravisit::Visitor>::visit_nested_item
  24:     0x7f6c90d7b6dd - <rustc_lint[6313896b7e65eed2]::late::LateContextAndPass<rustc_lint[6313896b7e65eed2]::late::RuntimeCombinedLateLintPass> as rustc_hir[121f359932e59ede]::intravisit::Visitor>::visit_nested_item
  25:     0x7f6c9244ff8a - rustc_lint[6313896b7e65eed2]::late::check_crate
  26:     0x7f6c92455e49 - rustc_interface[2cd87b402a7bbb07]::passes::analysis
  27:     0x7f6c92454f65 - rustc_query_impl[e29825a6f88888a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e29825a6f88888a7]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f6bb74e4dd5a8f75]::query::erase::Erased<[u8; 1usize]>>
  28:     0x7f6c92901ba2 - rustc_query_system[3350c2d9ca0121e2]::query::plumbing::try_execute_query::<rustc_query_impl[e29825a6f88888a7]::DynamicConfig<rustc_query_system[3350c2d9ca0121e2]::query::caches::SingleCache<rustc_middle[f6bb74e4dd5a8f75]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[e29825a6f88888a7]::plumbing::QueryCtxt, false>
  30:     0x7f6c927a5894 - rustc_interface[2cd87b402a7bbb07]::interface::run_compiler::<core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>, rustc_driver_impl[e6c4295f52574c92]::run_compiler::{closure#0}>::{closure#0}
  30:     0x7f6c927a5894 - rustc_interface[2cd87b402a7bbb07]::interface::run_compiler::<core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>, rustc_driver_impl[e6c4295f52574c92]::run_compiler::{closure#0}>::{closure#0}
  31:     0x7f6c92ab1b2e - std[999bdecce25602ed]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[2cd87b402a7bbb07]::util::run_in_thread_with_globals<rustc_interface[2cd87b402a7bbb07]::interface::run_compiler<core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>, rustc_driver_impl[e6c4295f52574c92]::run_compiler::{closure#0}>::{closure#0}, core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>>
  32:     0x7f6c92ab198a - <<std[999bdecce25602ed]::thread::Builder>::spawn_unchecked_<rustc_interface[2cd87b402a7bbb07]::util::run_in_thread_with_globals<rustc_interface[2cd87b402a7bbb07]::interface::run_compiler<core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>, rustc_driver_impl[e6c4295f52574c92]::run_compiler::{closure#0}>::{closure#0}, core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>>::{closure#1} as core[75bed1c93f3984e1]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  33:     0x7f6c93bb71e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3b366b3d6b556d67
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/alloc/src/boxed.rs:2020:9
  34:     0x7f6c93bb71e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49756348eb63eea1
  35:     0x7f6c93bb71e5 - std::sys::pal::unix::thread::Thread::new::thread_start::hdf802a7c2e3fdf20
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/sys/pal/unix/thread.rs:108:17
  36:     0x7f6c8d984ac3 - <unknown>
  37:     0x7f6c8da16850 - <unknown>
  37:     0x7f6c8da16850 - <unknown>
  38:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new?template=ice.yml

warning: the ICE couldn't be written to `/checkout/rustc-ice-2024-04-16T10_32_14-13487.txt`: Read-only file system (os error 30)
note: rustc 1.78.0-beta.1 (efd9d2df1 2024-03-18) running on x86_64-unknown-linux-gnu


note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C codegen-units=1 -C debug-assertions=on -Z unstable-options -C symbol-mangling-version=legacy -Z unstable-options -Z unstable-options -Z force-unstable-if-unmarked -Z macro-backtrace -C split-debuginfo=off -C prefer-dynamic -Z validate-mir -Z mir-opt-level=3 -Z inline-mir -C link-args=-Wl,-z,origin -C link-args=-Wl,-rpath,$ORIGIN/../lib -C force-frame-pointers=yes -Z crate-attr=doc(html_root_url="https://doc.rust-lang.org/nightly/") -Z binary-dep-depinfo -Z force-unstable-if-unmarked
note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
```

</details>

2024-04-29 08:39 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8875581663/job/24365321313) [(plain)](https://github.com/rust-lang/rust/commit/37bec59ff0a2e6c123756533730236a38b19d11c/checks/24365321313/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x7fd04d78f3eb - std::panicking::default_hook::{{closure}}::h743c1c016c642bf0
  10:     0x7fd04d78f143 - std::panicking::default_hook::h304853134c903f50
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/panicking.rs:292:9
  11:     0x7fd05062c05d - std[999bdecce25602ed]::panicking::update_hook::<alloc[5d2a9fe8278cb303]::boxed::Box<rustc_driver_impl[e6c4295f52574c92]::install_ice_hook::{closure#0}>>::{closure#0}
  12:     0x7fd04d78fb50 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h8e05c89c9dfd827c
  13:     0x7fd04d78fb50 - std::panicking::rust_panic_with_hook::h6987b578e7dec23c
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/panicking.rs:783:13
  14:     0x7fd04d78f859 - std::panicking::begin_panic_handler::{{closure}}::h5e61050e5431c199
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/panicking.rs:649:13
---
  22:     0x7fd05097c8f6 - <rustc_lint[6313896b7e65eed2]::late::LateContextAndPass<rustc_lint[6313896b7e65eed2]::late::RuntimeCombinedLateLintPass> as rustc_hir[121f359932e59ede]::intravisit::Visitor>::visit_nested_item
  23:     0x7fd05097b6dd - <rustc_lint[6313896b7e65eed2]::late::LateContextAndPass<rustc_lint[6313896b7e65eed2]::late::RuntimeCombinedLateLintPass> as rustc_hir[121f359932e59ede]::intravisit::Visitor>::visit_nested_item
  24:     0x7fd05097b6dd - <rustc_lint[6313896b7e65eed2]::late::LateContextAndPass<rustc_lint[6313896b7e65eed2]::late::RuntimeCombinedLateLintPass> as rustc_hir[121f359932e59ede]::intravisit::Visitor>::visit_nested_item
  25:     0x7fd05204ff8a - rustc_lint[6313896b7e65eed2]::late::check_crate
  26:     0x7fd052055e49 - rustc_interface[2cd87b402a7bbb07]::passes::analysis
  27:     0x7fd052054f65 - rustc_query_impl[e29825a6f88888a7]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[e29825a6f88888a7]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[f6bb74e4dd5a8f75]::query::erase::Erased<[u8; 1usize]>>
  28:     0x7fd052501ba2 - rustc_query_system[3350c2d9ca0121e2]::query::plumbing::try_execute_query::<rustc_query_impl[e29825a6f88888a7]::DynamicConfig<rustc_query_system[3350c2d9ca0121e2]::query::caches::SingleCache<rustc_middle[f6bb74e4dd5a8f75]::query::erase::Erased<[u8; 1usize]>>, false, false, false>, rustc_query_impl[e29825a6f88888a7]::plumbing::QueryCtxt, false>
  30:     0x7fd0523a5894 - rustc_interface[2cd87b402a7bbb07]::interface::run_compiler::<core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>, rustc_driver_impl[e6c4295f52574c92]::run_compiler::{closure#0}>::{closure#0}
  30:     0x7fd0523a5894 - rustc_interface[2cd87b402a7bbb07]::interface::run_compiler::<core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>, rustc_driver_impl[e6c4295f52574c92]::run_compiler::{closure#0}>::{closure#0}
  31:     0x7fd0526b1b2e - std[999bdecce25602ed]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[2cd87b402a7bbb07]::util::run_in_thread_with_globals<rustc_interface[2cd87b402a7bbb07]::interface::run_compiler<core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>, rustc_driver_impl[e6c4295f52574c92]::run_compiler::{closure#0}>::{closure#0}, core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>>
  32:     0x7fd0526b198a - <<std[999bdecce25602ed]::thread::Builder>::spawn_unchecked_<rustc_interface[2cd87b402a7bbb07]::util::run_in_thread_with_globals<rustc_interface[2cd87b402a7bbb07]::interface::run_compiler<core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>, rustc_driver_impl[e6c4295f52574c92]::run_compiler::{closure#0}>::{closure#0}, core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[75bed1c93f3984e1]::result::Result<(), rustc_span[ebf54beea9088bcf]::ErrorGuaranteed>>::{closure#1} as core[75bed1c93f3984e1]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  33:     0x7fd04d7991e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3b366b3d6b556d67
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/alloc/src/boxed.rs:2020:9
  34:     0x7fd04d7991e5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49756348eb63eea1
  35:     0x7fd04d7991e5 - std::sys::pal::unix::thread::Thread::new::thread_start::hdf802a7c2e3fdf20
                               at /rustc/efd9d2df12b5e17fac0b4d0fb89f612ecd79f259/library/std/src/sys/pal/unix/thread.rs:108:17
  36:     0x7fd04d45cac3 - <unknown>
  37:     0x7fd04d4ee850 - <unknown>
  37:     0x7fd04d4ee850 - <unknown>
  38:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new?template=ice.yml

warning: the ICE couldn't be written to `/checkout/rustc-ice-2024-04-29T08_39_20-17044.txt`: Read-only file system (os error 30)
note: rustc 1.78.0-beta.1 (efd9d2df1 2024-03-18) running on x86_64-unknown-linux-gnu


note: compiler flags: --crate-type lib -C opt-level=3 -C embed-bitcode=no -C codegen-units=1 -C debug-assertions=on -Z unstable-options -C symbol-mangling-version=legacy -Z unstable-options -Z unstable-options -Z force-unstable-if-unmarked -Z macro-backtrace -C split-debuginfo=off -C prefer-dynamic -Z validate-mir -Z mir-opt-level=3 -Z inline-mir -C link-args=-Wl,-z,origin -C link-args=-Wl,-rpath,$ORIGIN/../lib -C force-frame-pointers=yes -Z crate-attr=doc(html_root_url="https://doc.rust-lang.org/nightly/") -Z binary-dep-depinfo -Z force-unstable-if-unmarked
note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [analysis] running analysis passes on this crate
```

</details>

2024-05-02 14:12 UTC, tspiteri commented
> For the clippy warning, I think clippy is already fine in nightly, so instead of adding extra clippy allows, I think I might just wait for the next beta to be cut.

I rebased now that the clippy tests in mingw-check are using 2024-04-29 instead of 2024-03-19, and the tests now pass.

2024-05-02 15:07 UTC, tgross35 commented
> I changed `f128` constants like `PI` to use 60 decimal significant digits, which is enough for all these constants. (I generated them with MPFR through the Rug crate, with rounding to the nearest just like the constants in the standard library for `f32` and `f64`.) For `f16` I just used the same literals that are used for `f32` and `f64`.

Could you post the code for this so we can reproduce in the future?

2024-05-02 18:17 UTC, tspiteri commented
This is my code below. Should I include the code in a comment in f128.rs?

```rust
use rug::float::Constant;
use rug::{Assign, Float};

fn decimal_string(val: &Float, num_digits: usize) -> String {
    let (sign, mut digits, exp) = val.to_sign_string_exp(10, Some(num_digits));
    if let Some(exp) = exp {
        if exp <= 0 {
            let one_minus_exp = usize::try_from(1 - exp).unwrap();
            digits.insert_str(0, &"0".repeat(one_minus_exp));
            digits.insert(1, '.');
        } else {
            let exp = usize::try_from(exp).unwrap();
            if exp >= num_digits {
                digits.push_str(&"0".repeat(exp - num_digits));
            } else {
                digits.insert(exp, '.');
            }
        }
    }
    if sign {
        digits.insert(0, '-');
    }
    digits
}

fn float<T>(t: T) -> Float
where
    Float: Assign<T>,
{
    Float::with_val(1000, t)
}

fn print(name: &str, f: Float) {
    let s = decimal_string(&f, 60);
    assert_eq!(
        Float::with_val(113, Float::parse(&s).unwrap()),
        Float::with_val(113, &f)
    );
    println!("pub const {name}: f128 = {s}_f128;");
}

fn main() {
    print("PI", float(Constant::Pi));
    print("TAU", float(Constant::Pi) * 2);
    print("PHI", float(1.25).sqrt() + 0.5);
    print("EGAMMA", float(Constant::Euler));
    print("FRAC_PI_2", float(Constant::Pi) / 2);
    print("FRAC_PI_3", float(Constant::Pi) / 3);
    print("FRAC_PI_4", float(Constant::Pi) / 4);
    print("FRAC_PI_6", float(Constant::Pi) / 6);
    print("FRAC_PI_8", float(Constant::Pi) / 8);
    print("FRAC_1_PI", float(Constant::Pi).recip());
    print("FRAC_1_SQRT_PI", float(Constant::Pi).sqrt().recip());
    print("FRAC_2_PI", 2 / float(Constant::Pi));
    print("FRAC_2_SQRT_PI", 2 / float(Constant::Pi).sqrt());
    print("SQRT_2", float(2).sqrt());
    print("FRAC_1_SQRT_2", float(0.5).sqrt());
    print("SQRT_3", float(3).sqrt());
    print("FRAC_1_SQRT_3", float(3).sqrt().recip());
    print("E", float(1).exp());
    print("LOG2_10", float(10).log2());
    print("LOG2_E", float(1).exp().log2());
    print("LOG10_2", float(2).log10());
    print("LOG10_E", float(1).exp().log10());
    print("LN_2", float(2).ln());
    print("LN_10", float(10).ln());
}
```

2024-05-02 20:02 UTC, tgross35 commented
No this is fine, just wanted a reference in case anybody wants to replicate or add more in the future 👍

2024-05-02 20:20 UTC, tgross35 approved these changes
Okay, these all look good to me. I double checked the associated values against http://weitz.de/ieee/ and the math constants against what Julia says https://github.com/tgross35/apfloat-consts/blob/49cb0d131ea2d881205852c31ba87236fdba9749/output.rs.

Honestly it would be better to just generate bit patterns for the `MIN`/`MAX`/`EPSILON`/etc values rather than having a tough to read literal, but that's not something to do now.

I can't r+ so somebody else has to. Thanks for the patch!

2024-05-02 20:20 UTC, tgross35 commented on library/core/src/num/f128.rs
> +    pub const MAX: f128 = 1.18973149535723176508575932662800701e+4932_f128;
Minor style nit, would be good to consistently keep a line between the constant and docs (I know this was just copied from the existing floats)

2024-05-06 14:44 UTC, Amanieu commented
@bors r+

2024-05-06 16:51 UTC, merged

2024-05-07 02:09 UTC, rust-timer commented
Finished benchmarking commit (fc47cf38e51de0d8635128efe5b6ecfb135cf701): [comparison URL](https://perf.rust-lang.org/compare.html?start=25e3949aa1b24b3f62a72c1f713830aa1d1efcd4&end=fc47cf38e51de0d8635128efe5b6ecfb135cf701&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=25e3949aa1b24b3f62a72c1f713830aa1d1efcd4&end=fc47cf38e51de0d8635128efe5b6ecfb135cf701&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=25e3949aa1b24b3f62a72c1f713830aa1d1efcd4&end=fc47cf38e51de0d8635128efe5b6ecfb135cf701&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.8% | [1.8%, 1.8%] | 1     |
| Regressions ❌ <br /> (secondary)  | -    | -            | 0     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 1.8% | [1.8%, 1.8%] | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=25e3949aa1b24b3f62a72c1f713830aa1d1efcd4&end=fc47cf38e51de0d8635128efe5b6ecfb135cf701&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 6.1% | [6.0%, 6.3%] | 2     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=25e3949aa1b24b3f62a72c1f713830aa1d1efcd4&end=fc47cf38e51de0d8635128efe5b6ecfb135cf701&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 676.836s -> 676.942s (0.02%)
**Artifact size**: 315.81 MiB -> 315.88 MiB (0.02%)