Stabilize `Utf8Chunks`
rust-lang/rust pull request #123909
Opened 2024-04-14 05:12 UTC by dtolnay

Pending FCP in https://github.com/rust-lang/rust/issues/99543.

This PR includes the proposed modification in https://github.com/rust-lang/libs-team/issues/190 as agreed in https://github.com/rust-lang/rust/issues/99543#issuecomment-2050406568.

2024-04-15 17:51 UTC, dtolnay commented
@bors try

I'd like to try crater to find out whether anything is using bstr's `Utf8Chunk::incomplete` (https://github.com/rust-lang/rust/issues/99543#issuecomment-2056725555). If it is, this PR would break it by making libcore's `utf8_chunks()` take precedence over bstr's ByteSlice extension trait. If there is widespread breakage, we need to discuss adding `incomplete` before stabilizing this feature, and finding out about so many uses would help justify doing so. If there is no breakage, then it's a signal we do not need to add `incomplete` because nobody has real-world uses for it.

2024-04-15 20:25 UTC, dtolnay commented
@craterbot check

2024-04-19 14:03 UTC, joboet commented
That doesn't look too bad! As far as I can tell, `janetrs` is the only regression, the other ones are spurious or use it as a dependency. I opened https://github.com/GrayJack/janetrs/pull/10 to make it resilient against this.

2024-04-21 20:26 UTC, dtolnay commented
@rustbot ready

2024-04-24 11:59 UTC, joboet requested changes

2024-04-24 22:32 UTC, dtolnay commented on library/core/src/str/lossy.rs
> +    /// }
Done. I added an assert comparing against `stringify!(c"\xFErris the 🦀\u{7}")`, which I think will be more understandable than `"c\"\\xFErris the 🦀\\u{7}\""` or `r#"c"\xFErris the 🦀\u{7}""#`, but let me know what you think.

2024-04-26 11:24 UTC, joboet approved these changes
Looks good!
@bors r+

2024-04-26 11:24 UTC, joboet commented on library/core/src/str/lossy.rs
> +    /// }
Using `stringify` for this hadn't crossed my mind at all, but I think it's neat!

2024-04-26 16:24 UTC, dtolnay commented
@bors r=joboet

2024-04-26 19:43 UTC, merged

2024-04-26 20:59 UTC, rust-timer commented
Finished benchmarking commit (4d570eea025a19564429eb52b34ec34e14659f55): [comparison URL](https://perf.rust-lang.org/compare.html?start=1b3a32958bb54bde45e693217e8f7469459e5865&end=4d570eea025a19564429eb52b34ec34e14659f55&stat=instructions:u).

### Overall result: ❌ regressions - ACTION NEEDED


**Next Steps**: If you can justify the regressions found in this perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please open an issue or create a new PR that fixes the regressions, add a comment linking to the newly created issue or PR, and then add the `perf-regression-triaged` label to this PR.

@rustbot label: +perf-regression
cc @rust-lang/wg-compiler-performance



### [Instruction count](https://perf.rust-lang.org/compare.html?start=1b3a32958bb54bde45e693217e8f7469459e5865&end=4d570eea025a19564429eb52b34ec34e14659f55&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.5% | [0.2%, 1.1%] | 11    |
| Regressions ❌ <br /> (secondary)  | 0.8% | [0.3%, 1.2%] | 19    |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 0.5% | [0.2%, 1.1%] | 11    |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=1b3a32958bb54bde45e693217e8f7469459e5865&end=4d570eea025a19564429eb52b34ec34e14659f55&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 3.3% | [3.3%, 3.3%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=1b3a32958bb54bde45e693217e8f7469459e5865&end=4d570eea025a19564429eb52b34ec34e14659f55&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 2.2% | [2.2%, 2.2%] | 1     |
| Regressions ❌ <br /> (secondary)  | 2.0% | [2.0%, 2.1%] | 3     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 2.2% | [2.2%, 2.2%] | 1     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=1b3a32958bb54bde45e693217e8f7469459e5865&end=4d570eea025a19564429eb52b34ec34e14659f55&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 671.828s -> 673.336s (0.22%)
**Artifact size**: 315.91 MiB -> 315.94 MiB (0.01%)

2024-04-26 22:05 UTC, lqd commented
These are all doc regressions, which seems fine for perf triage purposes imo.

2024-04-29 13:01 UTC, Mark-Simulacrum commented
I'm not so convinced. This *should* be a much more minor change IMO -- it might be exposing some bad performance in rustdoc (maybe some bad behavior with inherent impls?) and could be worth digging into further. Not marking as triaged yet, will try to spend some time here this week.