Improved code with clippy
rust-lang/rust pull request #124287
Opened 2024-04-23 09:54 UTC by 41Leahcim

I haven't used the bootstrapped compiler, but I think I have made some improvements using clippy. I have already made the following changes to the compiler:
Replaced `self.first().is_digit(10)` with `self.first().is_ascii_digit()` on lines 633, 664, and 680 of compiler/rust_lexer/src/lib.rs.

Removed unnecessary cast on line 262 of compiler/rustc_lexer/src/unescape.rs

Replaced ok_or_else with ok_or on line 303 of compiler/rustc_lexer/src/unescape.rs

Replaced `!std::env::var("RUSTC_BOOTSTRAP").is_ok()` with `std::env::var("RUSTC_BOOTSTRAP").is_err()` on line 4 of compiler/rustc_macros/build.rs 

Removed needless borrow for generic argument `env`on line 53 of compiler/rust_llvm/build.rs

2024-04-23 10:15 UTC, 41Leahcim commented
II have also changed some tooling code with clippy. I have made the following changes:
Turned the argument slice to an array on line 33 of src/tools/build_helper/src/ci.rs

Removed question mark operator on line 24 of src/tools/build_helper/src/git.rs

Removed a needless borrow implicitly performed by the compiler on line 147 of src/tools/clippy/declare_clippy_lint/src/lib.rs 

Removed a needless borrow on line 54 of src/tools/miropt-test-tools/src/lib.rs

Replaced match expression with matches! macro on line 54 and 61 of src/tool/rustfmt/config_proc_macro/src/attrs.rs

Removed a needless borrow on lines 78 and 153 of src/tools/rustfmt/config_proc_macro/src/item_enum.rs

Replaced match expression with an equality check on line 16 of src/tools/rustfmt/config_proc_macro/src/utils.rs

Replaced argument slices to arrays on lines 43 and 51 of src/tools/rustfmt/build.rs

2024-04-23 13:09 UTC, ytmimi requested changes
The rustfmt team prefers these kinds of changes be made directly to rustfmt instead of here in the rust-lang/rust repo.

2024-04-23 13:09 UTC, ytmimi commented on src/tools/rustfmt/build.rs
Please revert these changes and open a PR directly to https://github.com/rust-lang/rustfmt for these kinds of changes.

2024-04-23 20:11 UTC, 41Leahcim commented
I have reverted the changes to all tools. Only the changes to the compiler are left. With only 7 lines changed, it's a pretty much worthless pull request. So I would understand it if it won't get merged.

2024-04-23 20:18 UTC, 41Leahcim commented on src/tools/rustfmt/build.rs
Thanks for telling me. I'm pretty new to open source. That's why I'm still making stupid mistakes like this and why my pull request doesn't add anything special.

2024-04-23 23:46 UTC, fmease commented
It's alright. I will approve it once you've squashed the commits into one.
r? fmease

2024-04-23 23:55 UTC, fmease commented
Note that your two long comments describing the changes in prose are now outdated.
Friendly tip: No need to transliterate code changes into prose, paraphrasing and summarizing does the job a lot better.

2024-04-25 06:41 UTC, 41Leahcim commented
I have merged my commits

2024-04-25 06:42 UTC, fmease commented
Thanks!

@bors r+ rollup

2024-04-25 19:16 UTC, merged