CI: remove `master` job
rust-lang/rust pull request #124332
Opened 2024-04-24 13:03 UTC by Kobzol

It only had one job (pun intended), to publish the toolstate. We could probably do that at the end of `auto` builds instead, which is what is done in this PR.

First 6 commits are from https://github.com/rust-lang/rust/pull/124327.

Blocked on: https://github.com/rust-lang/rust/pull/124327

r? @pietroalbini

2024-04-24 13:24 UTC, Kobzol commented
Ok, second attempt. I have moved toolstate publishing to the `auto-success` job, since it is already configured to run when the `auto` job succeeds. This conflicts with the change to unify the success/failure jobs though.

2024-04-24 13:56 UTC, pietroalbini commented
Not sure exactly why git decided to render the diff that way in the second commit :sweat_smile: 

r=me once the other PR is merged

2024-04-24 13:58 UTC, Kobzol commented
Yeah that was super weird :D I moved the steps down from the anchor, but GH (also local git diff) decided to instead move the jobs up.

2024-04-25 08:49 UTC, Kobzol commented
Rebased since https://github.com/rust-lang/rust/pull/124327 has been merged. I also added a new commit, so not approving immediately.

2024-04-25 13:07 UTC, Kobzol commented
@rustbot ready

2024-04-27 09:32 UTC, emilyalbini requested changes

2024-04-27 09:37 UTC, Kobzol commented on .github/workflows/ci.yml
> +          TOOLSTATE_REPO_ACCESS_TOKEN: "${{ secrets.TOOLSTATE_REPO_ACCESS_TOKEN }}"
The Rust code already uses this value as a default, but adding it as a top-level is easy enough. Good catch, thanks! Did that in the latest commit.

2024-04-27 09:39 UTC, pietroalbini approved these changes

2024-04-27 09:40 UTC, pietroalbini commented
@bors r+ rollup=iffy

2024-04-27 13:40 UTC, rust-log-analyzer commented
A job failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/8859514583/job/24330863340) [(plain)](https://github.com/rust-lang-ci/rust/commit/2c94366893e6e339fe024fc057b37c2f442a9fe3/checks/24330863340/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
env:
  TOOLSTATE_REPO: https://github.com/rust-lang-nursery/rust-toolstate
  TOOLSTATE_REPO_ACCESS_TOKEN: ***
##[endgroup]
/home/runner/work/_temp/06fd6a20-5201-4f3f-89ef-e7caa0eaf28b.sh: line 1: src/ci/publish_toolstate.sh: No such file or directory
##[error]Process completed with exit code 127.
```

</details>

2024-04-27 13:48 UTC, Kobzol commented
Added missing checkout step.

2024-04-29 14:02 UTC, pietroalbini commented
@bors r+ rollup=iffy

2024-04-29 18:27 UTC, merged