Make early lints translatable
rust-lang/rust pull request #124417
Opened 2024-04-26 18:39 UTC by Xiretza

Requires https://github.com/projectfluent/fluent-rs/pull/353.

r? diagnostics

2024-04-26 18:58 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8852831566/job/24312307261) [(plain)](https://github.com/rust-lang/rust/commit/362f0643d91dd25bb91dc462d8beb0b27a5864fb/checks/24312307261/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#17 exporting to docker image format
#17 sending tarball 28.8s done
#17 DONE 34.0s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
failures:

---- [ui] tests/ui/lint/unused/unused-macro-rules-compile-error.rs stdout ----

error: Error: expected failure status (Some(1)) but received status None.
status: signal: 6 (SIGABRT) (core dumped)
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/lint/unused/unused-macro-rules-compile-error.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/unused/unused-macro-rules-compile-error" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/unused/unused-macro-rules-compile-error/auxiliary"
--- stderr -------------------------------
thread 'rustc' panicked at compiler/rustc_errors/src/translation.rs:49:84:
called `Result::unwrap()` on an `Err` value: failed while formatting fluent string `lint_macro_rule_never_used`: 
Resolver error: Unknown function: NUMBER()
Resolver error: Unknown function: NUMBER()

stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <&mut <rustc_errors::json::JsonEmitter as rustc_errors::translation::Translate>::translate_messages::{closure#0} as core::ops::function::FnOnce<(&(rustc_error_messages::DiagMessage, rustc_errors::snippet::Style),)>>::call_once
   4: <alloc::string::String as core::iter::traits::collect::FromIterator<alloc::borrow::Cow<str>>>::from_iter::<core::iter::adapters::map::Map<core::slice::iter::Iter<(rustc_error_messages::DiagMessage, rustc_errors::snippet::Style)>, <rustc_errors::json::JsonEmitter as rustc_errors::translation::Translate>::translate_messages::{closure#0}>>
   5: <rustc_errors::json::Diagnostic>::from_errors_diagnostic
   6: <rustc_errors::json::JsonEmitter as rustc_errors::emitter::Emitter>::emit_diagnostic
   7: <rustc_errors::DiagCtxtInner>::emit_diagnostic::{closure#3}
   8: rustc_interface::callbacks::track_diagnostic::<core::option::Option<rustc_span::ErrorGuaranteed>>
   9: <rustc_errors::DiagCtxtInner>::emit_diagnostic
  10: <rustc_errors::DiagCtxt>::emit_diagnostic
  11: <() as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12: rustc_middle::lint::lint_level::lint_level_impl::<rustc_error_messages::DiagMessage>
  13: rustc_middle::lint::lint_level::<rustc_error_messages::DiagMessage, <rustc_lint::context::EarlyContext as rustc_lint::context::LintContext>::emit_span_lint<rustc_error_messages::MultiSpan, rustc_lint::lints::MacroRuleNeverUsed>::{closure#0}>
  14: <rustc_lint::levels::LintLevelsBuilder<rustc_lint::levels::TopDown>>::opt_span_lint::<rustc_error_messages::DiagMessage, <rustc_lint::context::EarlyContext as rustc_lint::context::LintContext>::emit_span_lint<rustc_error_messages::MultiSpan, rustc_lint::lints::MacroRuleNeverUsed>::{closure#0}>
  15: <rustc_lint::context::EarlyContext as rustc_lint::context::LintContext>::emit_span_lint::<rustc_error_messages::MultiSpan, rustc_lint::lints::MacroRuleNeverUsed>
  16: rustc_lint::context::diagnostics::emit_buffered_lint::<rustc_lint::context::EarlyContext>
  17: <rustc_lint::early::EarlyContextAndPass<rustc_lint::BuiltinCombinedEarlyLintPass> as rustc_ast::visit::Visitor>::visit_item
  18: rustc_ast::visit::walk_crate::<rustc_lint::early::EarlyContextAndPass<rustc_lint::BuiltinCombinedEarlyLintPass>>
  19: rustc_lint::early::check_ast_node::<rustc_lint::BuiltinCombinedEarlyLintPass, (&rustc_ast::ast::Crate, &[rustc_ast::ast::Attribute])>
  20: rustc_interface::passes::early_lint_checks
      [... omitted 2 frames ...]
  21: rustc_ast_lowering::lower_to_hir
      [... omitted 2 frames ...]
  22: <rustc_middle::hir::provide::{closure#1} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
      [... omitted 2 frames ...]
  23: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
  24: <rustc_middle::hir::map::Map>::get_module
  25: rustc_middle::hir::map::hir_crate_items
      [... omitted 2 frames ...]
  26: rustc_passes::hir_id_validator::check_crate
  27: rustc_interface::passes::analysis
      [... omitted 2 frames ...]
  29: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
  30: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
  31: rustc_span::create_session_globals_then::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose ba [...]

2024-04-27 18:27 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8861692678/job/24333846008) [(plain)](https://github.com/rust-lang/rust/commit/4edd58f3690382f7deeb95eb5afd1f438d9ab6b7/checks/24333846008/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 exporting to docker image format
#16 sending tarball 29.2s done
#16 DONE 34.4s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
failures:

---- [ui] tests/ui/lint/unused/unused-macro-rules-decl.rs stdout ----

error: Error: expected failure status (Some(1)) but received status None.
status: signal: 6 (SIGABRT) (core dumped)
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/lint/unused/unused-macro-rules-decl.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/unused/unused-macro-rules-decl" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/unused/unused-macro-rules-decl/auxiliary"
--- stderr -------------------------------
thread 'rustc' panicked at compiler/rustc_errors/src/translation.rs:49:84:
called `Result::unwrap()` on an `Err` value: failed while formatting fluent string `lint_macro_rule_never_used`: 
Resolver error: Unknown function: NUMBER()
Resolver error: Unknown function: NUMBER()

stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <&mut <rustc_errors::json::JsonEmitter as rustc_errors::translation::Translate>::translate_messages::{closure#0} as core::ops::function::FnOnce<(&(rustc_error_messages::DiagMessage, rustc_errors::snippet::Style),)>>::call_once
   4: <alloc::string::String as core::iter::traits::collect::FromIterator<alloc::borrow::Cow<str>>>::from_iter::<core::iter::adapters::map::Map<core::slice::iter::Iter<(rustc_error_messages::DiagMessage, rustc_errors::snippet::Style)>, <rustc_errors::json::JsonEmitter as rustc_errors::translation::Translate>::translate_messages::{closure#0}>>
   5: <rustc_errors::json::Diagnostic>::from_errors_diagnostic
   6: <rustc_errors::json::JsonEmitter as rustc_errors::emitter::Emitter>::emit_diagnostic
   7: <rustc_errors::DiagCtxtInner>::emit_diagnostic::{closure#3}
   8: rustc_interface::callbacks::track_diagnostic::<core::option::Option<rustc_span::ErrorGuaranteed>>
   9: <rustc_errors::DiagCtxtInner>::emit_diagnostic
  10: <rustc_errors::DiagCtxt>::emit_diagnostic
  11: <() as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12: rustc_middle::lint::lint_level::lint_level_impl::<rustc_error_messages::DiagMessage>
  13: rustc_middle::lint::lint_level::<rustc_error_messages::DiagMessage, <rustc_lint::context::EarlyContext as rustc_lint::context::LintContext>::emit_span_lint<rustc_error_messages::MultiSpan, rustc_lint::lints::MacroRuleNeverUsed>::{closure#0}>
  14: <rustc_lint::levels::LintLevelsBuilder<rustc_lint::levels::TopDown>>::opt_span_lint::<rustc_error_messages::DiagMessage, <rustc_lint::context::EarlyContext as rustc_lint::context::LintContext>::emit_span_lint<rustc_error_messages::MultiSpan, rustc_lint::lints::MacroRuleNeverUsed>::{closure#0}>
  15: <rustc_lint::context::EarlyContext as rustc_lint::context::LintContext>::emit_span_lint::<rustc_error_messages::MultiSpan, rustc_lint::lints::MacroRuleNeverUsed>
  16: rustc_lint::context::diagnostics::emit_buffered_lint::<rustc_lint::context::EarlyContext>
  17: <rustc_lint::early::EarlyContextAndPass<rustc_lint::BuiltinCombinedEarlyLintPass> as rustc_ast::visit::Visitor>::visit_item
  18: rustc_ast::visit::walk_crate::<rustc_lint::early::EarlyContextAndPass<rustc_lint::BuiltinCombinedEarlyLintPass>>
  19: rustc_lint::early::check_ast_node::<rustc_lint::BuiltinCombinedEarlyLintPass, (&rustc_ast::ast::Crate, &[rustc_ast::ast::Attribute])>
  20: rustc_interface::passes::early_lint_checks
      [... omitted 2 frames ...]
  21: rustc_ast_lowering::lower_to_hir
      [... omitted 2 frames ...]
  22: <rustc_middle::hir::provide::{closure#1} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
      [... omitted 2 frames ...]
  23: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
  24: <rustc_middle::hir::map::Map>::get_module
  25: rustc_middle::hir::map::hir_crate_items
      [... omitted 2 frames ...]
  26: rustc_passes::hir_id_validator::check_crate
  27: rustc_interface::passes::analysis
      [... omitted 2 frames ...]
  29: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
  30: rustc_span::create_session_globals_then::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---
note: please make sure that you have updated to the latest nightly

note: rustc 1.79.0-nightly (84f22538d 2024-04-27) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z threads=1 -Z simulate-remapped-rust-src-base=/rustc/FAKE_PREFIX -Z translate-remapped-path-to-local-path=no -Z ignore-directory-in-diagnostics-source-blocks=/cargo -Z ignore-directory-in-diagnostics-source-blocks=/checkout/vendor -C codegen-units=1 -Z ui-testing -Z deduplicate-diagnostics=no -Z write-long-types-to-disk=no -C strip=debuginfo -C prefer-dynamic -C rpath -C debuginfo=0
qu [...]

2024-05-02 13:56 UTC, oli-obk commented
r? @davidtwco I'm going on vacation for two weeks

2024-05-09 13:34 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/9017878112/job/24777267489) [(plain)](https://github.com/rust-lang/rust/commit/eb5690ab85ce600e2e2611f711dc8ac3f6f9536b/checks/24777267489/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 exporting to docker image format
#16 sending tarball 30.5s done
#16 DONE 35.7s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
failures:

---- [ui] tests/ui/lint/unused/unused-macro-rules-compile-error.rs stdout ----

error: Error: expected failure status (Some(1)) but received status None.
status: signal: 6 (SIGABRT) (core dumped)
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/lint/unused/unused-macro-rules-compile-error.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/unused/unused-macro-rules-compile-error" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/unused/unused-macro-rules-compile-error/auxiliary"
--- stderr -------------------------------
thread 'rustc' panicked at compiler/rustc_errors/src/translation.rs:50:84:
called `Result::unwrap()` on an `Err` value: failed while formatting fluent string `lint_macro_rule_never_used`: 
Resolver error: Unknown function: NUMBER()
Resolver error: Unknown function: NUMBER()

stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <&mut <rustc_errors::json::JsonEmitter as rustc_errors::translation::Translate>::translate_messages::{closure#0} as core::ops::function::FnOnce<(&(rustc_error_messages::DiagMessage, rustc_errors::snippet::Style),)>>::call_once
   4: <alloc::string::String as core::iter::traits::collect::FromIterator<alloc::borrow::Cow<str>>>::from_iter::<core::iter::adapters::map::Map<core::slice::iter::Iter<(rustc_error_messages::DiagMessage, rustc_errors::snippet::Style)>, <rustc_errors::json::JsonEmitter as rustc_errors::translation::Translate>::translate_messages::{closure#0}>>
   5: <rustc_errors::json::Diagnostic>::from_errors_diagnostic
   6: <rustc_errors::json::JsonEmitter as rustc_errors::emitter::Emitter>::emit_diagnostic
   7: <rustc_errors::DiagCtxtInner>::emit_diagnostic::{closure#3}
   8: rustc_interface::callbacks::track_diagnostic::<core::option::Option<rustc_span::ErrorGuaranteed>>
   9: <rustc_errors::DiagCtxtInner>::emit_diagnostic
  10: <rustc_errors::DiagCtxt>::emit_diagnostic
  11: <() as rustc_errors::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12: rustc_middle::lint::lint_level::lint_level_impl::<rustc_error_messages::DiagMessage>
  13: rustc_middle::lint::lint_level::<rustc_error_messages::DiagMessage, <rustc_lint::context::EarlyContext as rustc_lint::context::LintContext>::emit_span_lint<rustc_error_messages::MultiSpan, rustc_lint::lints::MacroRuleNeverUsed>::{closure#0}>
  14: <rustc_lint::levels::LintLevelsBuilder<rustc_lint::levels::TopDown>>::opt_span_lint::<rustc_error_messages::DiagMessage, <rustc_lint::context::EarlyContext as rustc_lint::context::LintContext>::emit_span_lint<rustc_error_messages::MultiSpan, rustc_lint::lints::MacroRuleNeverUsed>::{closure#0}>
  15: <rustc_lint::context::EarlyContext as rustc_lint::context::LintContext>::emit_span_lint::<rustc_error_messages::MultiSpan, rustc_lint::lints::MacroRuleNeverUsed>
  16: rustc_lint::context::diagnostics::emit_buffered_lint::<rustc_lint::context::EarlyContext>
  17: <rustc_lint::early::EarlyContextAndPass<rustc_lint::BuiltinCombinedEarlyLintPass> as rustc_ast::visit::Visitor>::visit_item
  18: rustc_ast::visit::walk_crate::<rustc_lint::early::EarlyContextAndPass<rustc_lint::BuiltinCombinedEarlyLintPass>>
  19: rustc_lint::early::check_ast_node::<rustc_lint::BuiltinCombinedEarlyLintPass, (&rustc_ast::ast::Crate, &[rustc_ast::ast::Attribute])>
  20: rustc_interface::passes::early_lint_checks
      [... omitted 2 frames ...]
  21: rustc_ast_lowering::lower_to_hir
      [... omitted 2 frames ...]
  22: <rustc_middle::hir::provide::{closure#1} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
      [... omitted 2 frames ...]
  23: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::VecCache<rustc_span::def_id::LocalDefId, rustc_middle::query::erase::Erased<[u8; 8]>>>
  24: <rustc_middle::hir::map::Map>::get_module
  25: rustc_middle::hir::map::hir_crate_items
      [... omitted 2 frames ...]
  26: rustc_passes::hir_id_validator::check_crate
  27: rustc_interface::passes::analysis
      [... omitted 2 frames ...]
  29: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
  30: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
  31: rustc_span::create_session_globals_then::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
note: Some details are omitted, run with `RUST_BACKT [...]

2024-05-17 16:54 UTC, fmease commented
Are there any blockers left apart from a rebase?

2024-05-17 18:03 UTC, Xiretza commented
Yep, I can also patch those `NUMBER()` calls out and put a TODO there instead, at the cost of slightly worse diagnostics until the next fluent release.

2024-05-18 13:39 UTC, Xiretza commented
Rebased, and the use case for `NUMBER()` has since disappeared (https://github.com/rust-lang/rust/commit/5134a04eaa32b168cf5998a6ec13199356e2e017), so there are no blockers now.

2024-05-20 13:34 UTC, davidtwco commented
Apologies for the delay in my reviewing, had a busy couple weeks, will let @fmease handle this.

2024-05-20 15:36 UTC, fmease requested changes
Thanks a lot. this is great work!

I've added a lot of review comments for things that are secondary or preexisting even. You don't need to address them in this PR, they can be fixed in follow-up PRs (by you or my me). Basically drive-by commentary.

I g2g rn unfortunately but I'd like to see `emit_buffered_lint` being made non-generic as noted in one of my comments. You should be able to pick out what is relevant and what isn't. In a few hours, I will be back again and can push it into the merge queue with a high priority

2024-05-20 15:37 UTC, fmease commented
@bors p=1 prone to bitrotting

2024-05-20 18:10 UTC, Xiretza reviewed
Still need to address the most pressing concern (making `emit_buffered_lint` not generic), but I got most of the rest done.

2024-05-20 18:10 UTC, Xiretza commented on compiler/rustc_lint/src/context/diagnostics.rs
> +            pluralize!(span_snippets.len()),
Good catch, I think this was potentially wrong previously: the length is used to pluralize the list of `span_snippets`, so it should be `span_snippets.len()` in any case.

2024-05-20 18:10 UTC, Xiretza commented on compiler/rustc_lint_defs/src/lib.rs
>      pub fn buffer_lint_with_diagnostic(
Done.

2024-05-20 18:10 UTC, Xiretza commented on compiler/rustc_session/src/parse.rs
>      pub fn buffer_lint_with_diagnostic(
Done.

2024-05-20 18:10 UTC, Xiretza commented on compiler/rustc_expand/src/base.rs
> +                                    BuiltinLintDiag::ProcMacroBackCompat {
I wasn't sure if other crates might be added here in the future (there were more in the past), so I went for the possibly overkill solution.

2024-05-21 15:01 UTC, fmease approved these changes
Thanks for applying my suggestions! One final rebase necessary, then this is ready to get shipped!

2024-05-21 20:12 UTC, Xiretza commented
Alright, `check_cfg` rebased, and even prettified a bit in the process!

2024-05-21 20:18 UTC, Xiretza commented
Weird, the push hook didn't catch some bad formatting, hopefully that was the last force-push.

2024-05-21 20:19 UTC, fmease commented
> Weird, the push hook didn't catch some bad formatting, hopefully that was the last force-push.

Ah, I've seem some people post about similar experiences on Zulip, no worries.

2024-05-21 20:19 UTC, fmease commented
@bors r+

2024-05-21 23:54 UTC, merged

2024-05-22 01:19 UTC, rust-timer commented
Finished benchmarking commit (791adf759cc065316f054961875052d5bc03e16c): [comparison URL](https://perf.rust-lang.org/compare.html?start=39e02f1bd1e53d009da382654139f7c0639172a8&end=791adf759cc065316f054961875052d5bc03e16c&stat=instructions:u).

### Overall result: ❌✅ regressions and improvements - ACTION NEEDED


**Next Steps**: If you can justify the regressions found in this perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please open an issue or create a new PR that fixes the regressions, add a comment linking to the newly created issue or PR, and then add the `perf-regression-triaged` label to this PR.

@rustbot label: +perf-regression
cc @rust-lang/wg-compiler-performance



### [Instruction count](https://perf.rust-lang.org/compare.html?start=39e02f1bd1e53d009da382654139f7c0639172a8&end=791adf759cc065316f054961875052d5bc03e16c&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.5%  | [0.2%, 6.3%]   | 66    |
| Regressions ❌ <br /> (secondary)  | 0.4%  | [0.3%, 0.5%]   | 7     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -0.7% | [-1.1%, -0.6%] | 12    |
| All ❌✅ (primary)                 | 1.5%  | [0.2%, 6.3%]   | 66    |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=39e02f1bd1e53d009da382654139f7c0639172a8&end=791adf759cc065316f054961875052d5bc03e16c&stat=max-rss)
<details>
<summary>Results (primary 2.4%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 2.4% | [1.1%, 3.1%] | 17    |
| Regressions ❌ <br /> (secondary)  | -    | -            | 0     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 2.4% | [1.1%, 3.1%] | 17    |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=39e02f1bd1e53d009da382654139f7c0639172a8&end=791adf759cc065316f054961875052d5bc03e16c&stat=cycles:u)
<details>
<summary>Results (primary 2.4%, secondary 2.2%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 2.4% | [1.2%, 4.9%] | 23    |
| Regressions ❌ <br /> (secondary)  | 2.2% | [2.2%, 2.2%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 2.4% | [1.2%, 4.9%] | 23    |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=39e02f1bd1e53d009da382654139f7c0639172a8&end=791adf759cc065316f054961875052d5bc03e16c&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 671.076s -> 670.302s (-0.12%)
**Artifact size**: 315.42 MiB -> 316.14 MiB (0.23%)

2024-05-22 06:06 UTC, nnethercote commented
Some sizeable perf regressions. Is that expected?

2024-05-22 06:43 UTC, fmease commented
No, it's not expected. I think I know what's going wrong. Sending a fix shortly.

2024-05-22 06:50 UTC, Xiretza commented
No, not really - would be interesting to know if this is just for lints that are actually emitted or even for ones that get silenced.

2024-05-22 06:55 UTC, fmease commented
@Xiretza We no longer decorate the lint `Diag` lazily inside `span_lint_with_diagnostics` but eagerly in `diagnostics::emit_buffered_lint`.

2024-05-23 02:01 UTC, fmease commented
In #125410 I was able to partially restore the old performance characteristics. See https://github.com/rust-lang/rust/pull/125410#issuecomment-2125971223. Doing some naive calculations in my head, I guess that's not sufficient. Anyways, Xiretza and/or I can conduct some more perf experiments after #125410 has been merged.