fix: break inside async closure has incorrect span for enclosing closure
rust-lang/rust pull request #125078
Opened 2024-05-13 14:46 UTC by linyihai

Fixes #124496

2024-05-13 19:57 UTC, compiler-errors commented on compiler/rustc_passes/src/loops.rs
> +                        let fn_decl_span = match self.cx {
This seems like a bit too specific of a case here. I think we should just fix the `fn_decl_span` for the `hir::Closure` from an async closure.

2024-05-13 19:57 UTC, compiler-errors requested changes
Pls look into fixing this in a more general way

2024-05-14 07:03 UTC, linyihai commented
> Pls look into fixing this in a more general way

Hope my latest submit general enough, I haven't see other code modules, such as the hir: : CoroutineKind: : Desugared

2024-05-16 14:10 UTC, linyihai commented
@rustbot review

2024-05-16 14:11 UTC, linyihai commented
@rustbot ready

2024-05-20 03:51 UTC, compiler-errors requested changes
Sorry, I wasn't clear when I meant that this should be made more general. I think this needs to be fixed when the `hir::Closure` is *constructed*, somewhere in `rustc_ast_lowering`.

See https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_ast_lowering/expr.rs.html#1056-1122 or somewhere nearby.

2024-05-27 03:30 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/9248636886/job/25439246534) [(plain)](https://github.com/rust-lang/rust/commit/0568d1883d8b6f798d2922d0cccd82ebac675c0a/checks/25439246534/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 exporting to docker image format
#16 sending tarball 29.3s done
#16 DONE 32.0s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
diff of stderr:

20    |                           ^^^^^^^^^^ required by this bound in `needs_async_fn`
21 
22 error[E0596]: cannot borrow `x` as mutable, as it is a captured variable in a `Fn` closure
+   --> $DIR/wrong-fn-kind.rs:9:20
24    |
24    |
25 LL |   fn needs_async_fn(_: impl async Fn()) {}
26    |                        --------------- change this to accept `FnMut` instead of `Fn`
27 ...
27 ...
28 LL |       needs_async_fn(async || {
-    |  _____--------------_--------_^
-    | |     |              in this closure
+    |       -------------- ^-------
+    |       |              |
+    |  _____|______________in this closure
+    |  _____|______________in this closure
+    | |     |
32    | |     expects `Fn` instead of `FnMut`
34 LL | |         x += 1;


The actual stderr differed from the expected stderr.
The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-closures/wrong-fn-kind/wrong-fn-kind.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args async-await/async-closures/wrong-fn-kind.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/async-await/async-closures/wrong-fn-kind.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-closures/wrong-fn-kind" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-closures/wrong-fn-kind/auxiliary" "--edition=2021"
--- stderr -------------------------------
--- stderr -------------------------------
error[E0525]: expected a closure that implements the `async Fn` trait, but this closure only implements `async FnOnce`
   |
   |
LL |       needs_async_fn(move || async move {
   |       -------------- -^^^^^^
   |       |              |
   |  _____|______________this closure implements `async FnOnce`, not `async Fn`
   | |     required by a bound introduced by this call
   | |     required by a bound introduced by this call
LL | |         //~^ ERROR expected a closure that implements the `async Fn` trait, but this closure only implements `async FnOnce`
LL | |         println!("{x}");
   | |                    - closure is `async FnOnce` because it moves the variable `x` out of its environment
LL | |     });
   | |_____- the requirement to implement `async Fn` derives from here
note: required by a bound in `needs_async_fn`
  --> /checkout/tests/ui/async-await/async-closures/wrong-fn-kind.rs:5:27
   |
   |
LL | fn needs_async_fn(_: impl async Fn()) {}
   |                           ^^^^^^^^^^ required by this bound in `needs_async_fn`

error[E0596]: cannot borrow `x` as mutable, as it is a captured variable in a `Fn` closure
   |
   |
LL |   fn needs_async_fn(_: impl async Fn()) {}
   |                        --------------- change this to accept `FnMut` instead of `Fn`
...
LL |       needs_async_fn(async || {
   |       -------------- ^-------
   |  _____|______________in this closure
   | |     |
   | |     |
   | |     expects `Fn` instead of `FnMut`
LL | |         //~^ ERROR cannot borrow `x` as mutable, as it is a captured variable in a `Fn` closure
LL | |         x += 1;
   | |         - mutable borrow occurs due to use of `x` in closure
   | |_____^ cannot borrow as mutable

error: aborting due to 2 previous errors

```

</details>

2024-05-27 13:35 UTC, linyihai commented
@rustbot ready

2024-06-05 10:27 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/9382223222/job/25833213186) [(plain)](https://github.com/rust-lang/rust/commit/b8cade7a9145b301e6f3ce287f67da038a9a6aec/checks/25833213186/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 exporting to docker image format
#16 sending tarball 31.0s done
#16 DONE 37.1s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
1 error[E0282]: type annotations needed
-   --> $DIR/ambiguous-arg.rs:9:25
+   --> $DIR/ambiguous-arg.rs:9:5
3    |
- LL |       async |check, a, b| {
-    |  _________________________^
+ LL | /     async |check, a, b| {
6 LL | |
7 LL | |         temp.abs_diff(12);


The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-closures/ambiguous-arg/ambiguous-arg.stderr
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-closures/ambiguous-arg/ambiguous-arg.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args async-await/async-closures/ambiguous-arg.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/async-await/async-closures/ambiguous-arg.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-closures/ambiguous-arg" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-closures/ambiguous-arg/auxiliary" "--edition=2021"
--- stderr -------------------------------
error[E0282]: type annotations needed
##[error]  --> /checkout/tests/ui/async-await/async-closures/ambiguous-arg.rs:9:5
   |
   |
LL | /     async |check, a, b| {
LL | |         //~^ ERROR type annotations needed
LL | |         temp.abs_diff(12);
   | |_____^ cannot infer type

error: aborting due to 1 previous error

---
4 LL |     let x = async || {};
-    |                      -- the expected `async` closure body
+    |             ----------- the expected `async` closure body
6 LL |
7 LL |     let () = x();
8    |         ^^   --- this expression has type `{static main::{closure#0}::{closure#0}<?17t> upvar_tys=?16t witness=?6t}`

The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-closures/def-path/def-path.stderr
To update references, rerun the tests and pass the `--bless` flag
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args async-await/async-closures/def-path.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/async-await/async-closures/def-path.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-closures/def-path" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-closures/def-path/auxiliary" "-Zverbose-internals" "--edition=2021"
--- stderr -------------------------------
error[E0308]: mismatched types
##[error]  --> /checkout/tests/ui/async-await/async-closures/def-path.rs:9:9
   |
   |
LL |     let x = async || {};
   |             ----------- the expected `async` closure body
LL |     //~^ NOTE the expected `async` closure body
LL |     let () = x();
   |         ^^   --- this expression has type `{static main::{closure#0}::{closure#0}<?17t> upvar_tys=?16t witness=?6t}`
   |         expected `async` closure body, found `()`
   |
   |
   = note: expected `async` closure body `{static main::{closure#0}::{closure#0}<?17t> upvar_tys=?16t witness=?6t}`

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0308`.
For more information about this error, try `rustc --explain E0308`.
------------------------------------------


---- [ui] tests/ui/async-await/async-closures/is-not-fn.rs stdout ----
diff of stderr:

- error[E0271]: expected `{async closure@is-not-fn.rs:7:14}` to be a closure that returns `()`, but it returns `{async closure body@$DIR/is-not-fn.rs:7:23: 7:25}`
+ error[E0271]: expected `{async closure@is-not-fn.rs:7:14}` to be a closure that returns `()`, but it returns `{async closure body@$DIR/is-not-fn.rs:7:14: 7:25}`
2   --> $DIR/is-not-fn.rs:7:14
3    |
4 LL |     needs_fn(async || {});
7    |     required by a bound introduced by this call
8    |
9    = note:         expected unit type `()`
9    = note:         expected unit type `()`
-            found `async` closure body `{async closure body@$DIR/is-not-fn.rs:7:23: 7:25}`
+            found `async` closure body `{async closure body@$DIR/is-not-fn.rs:7:14: 7:25}`
11 note: required by a bound in `needs_fn`
12   --> $DIR/is-not-fn.rs:6:25


The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-closures/is-not-fn/is-not-fn.stderr
Actual stderr save [...]

2024-06-05 15:28 UTC, linyihai commented
I think it's ready to review. Would you @compiler-errors  leave some feadback? I will be very appreciate for it

2024-06-18 15:32 UTC, compiler-errors approved these changes

2024-06-18 15:32 UTC, compiler-errors commented
@bors r+

2024-06-19 04:02 UTC, merged