Imporve error message: missing `;` in macro_rules
rust-lang/rust pull request #125180
Opened 2024-05-16 14:37 UTC by mu001999

Fixes #124968

2024-05-16 14:58 UTC, Nilstrieb commented
this code is very perf sensitive, so let's check
@bors try @rust-timer queue
If perf is OK I'd like you to refactor the code a bit to make this `Option<Token>` clearer, but let's check it first.

2024-05-16 14:59 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2024-05-16 16:37 UTC, rust-timer commented
Queued 7af9416f7e94983731941e40d1c092347b074419 with parent 4a78c00e227124ff9d5ece2d493472e7325c87d3, future [comparison URL](https://perf.rust-lang.org/compare.html?start=4a78c00e227124ff9d5ece2d493472e7325c87d3&end=7af9416f7e94983731941e40d1c092347b074419).
There is currently 1 preceding artifact in the [queue](https://perf.rust-lang.org/status.html).
It will probably take at least ~1.6 hours until the benchmark run finishes.
<!-- rust-timer: temporary -->

2024-05-16 19:30 UTC, rust-timer commented
Finished benchmarking commit (7af9416f7e94983731941e40d1c092347b074419): [comparison URL](https://perf.rust-lang.org/compare.html?start=4a78c00e227124ff9d5ece2d493472e7325c87d3&end=7af9416f7e94983731941e40d1c092347b074419&stat=instructions:u).

### Overall result: ❌ regressions - ACTION NEEDED


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: -S-waiting-on-perf +perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=4a78c00e227124ff9d5ece2d493472e7325c87d3&end=7af9416f7e94983731941e40d1c092347b074419&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.7% | [0.2%, 4.4%] | 21    |
| Regressions ❌ <br /> (secondary)  | 1.0% | [0.4%, 1.8%] | 13    |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 1.7% | [0.2%, 4.4%] | 21    |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=4a78c00e227124ff9d5ece2d493472e7325c87d3&end=7af9416f7e94983731941e40d1c092347b074419&stat=max-rss)
<details>
<summary>Results (primary 2.3%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 2.3% | [2.3%, 2.3%] | 1     |
| Regressions ❌ <br /> (secondary)  | -    | -            | 0     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 2.3% | [2.3%, 2.3%] | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=4a78c00e227124ff9d5ece2d493472e7325c87d3&end=7af9416f7e94983731941e40d1c092347b074419&stat=cycles:u)
<details>
<summary>Results (primary 3.6%, secondary 3.3%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 3.6% | [0.8%, 7.6%] | 13    |
| Regressions ❌ <br /> (secondary)  | 3.3% | [2.0%, 4.7%] | 9     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 3.6% | [0.8%, 7.6%] | 13    |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=4a78c00e227124ff9d5ece2d493472e7325c87d3&end=7af9416f7e94983731941e40d1c092347b074419&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 679.603s -> 680.293s (0.10%)
**Artifact size**: 316.12 MiB -> 316.16 MiB (0.01%)

2024-05-16 23:38 UTC, mu001999 commented
@Nilstrieb How about the result? Looks like this change slows down Rustc a bit.

2024-05-17 06:52 UTC, Nilstrieb commented
yeah, that's too much. i very much like the improvement, but you need to try to figure out a faster way. maybe you can make use of the trait abstraction, where you try to avoid all work for the no-op tracker

2024-05-17 06:53 UTC, Nilstrieb commented
I've written that abstraction and logic myself, so if you have questions feel free to ask

2024-05-17 06:58 UTC, mu001999 commented
@Nilstrieb thanks! I will try it ;)

2024-05-17 09:05 UTC, mu001999 commented
I don't know if I have access but
@bors try @rust-timer queue

2024-05-17 09:05 UTC, rust-timer commented
Insufficient permissions to issue commands to rust-timer.
<!-- rust-timer: temporary -->

2024-05-17 10:55 UTC, Nilstrieb commented
@bors try @rust-timer queue

2024-05-17 10:55 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2024-05-17 12:34 UTC, rust-timer commented
Queued 7308417b77b10ac9dcee77ce6b5174c7284cabe4 with parent 1189851eebdf6b69b164bbb7bf9df91188ae03aa, future [comparison URL](https://perf.rust-lang.org/compare.html?start=1189851eebdf6b69b164bbb7bf9df91188ae03aa&end=7308417b77b10ac9dcee77ce6b5174c7284cabe4).
There are currently 0 preceding artifacts in the [queue](https://perf.rust-lang.org/status.html).
It will probably take at least ~1.2 hours until the benchmark run finishes.
<!-- rust-timer: temporary -->

2024-05-17 14:03 UTC, mu001999 commented
@Nilstrieb The new result looks good! How do you think of this new change? Should I refactor the code?

2024-05-17 14:32 UTC, Nilstrieb commented
very cool. I skimmed the code and it looks okay, I will review it later.

2024-05-18 09:47 UTC, fee1-dead requested changes

2024-05-18 09:47 UTC, fee1-dead commented on compiler/rustc_expand/src/mbe/diagnostics.rs
> +pub struct FailureForwarder<'matcher>(Option<&'matcher Token>);
```suggestion
pub struct FailureForwarder<'matcher> {
    expected_token: Option<'matcher Token>,
}
```

2024-05-18 09:47 UTC, fee1-dead commented on compiler/rustc_expand/src/mbe/diagnostics.rs
> +    fn get_expect_tok(&self) -> Option<&'matcher Token> {
A rename would probably be better
```suggestion
    fn set_expected_token(&mut self, tok: &'matcher Token) {
        self.0 = Some(tok);
    }

    fn expected_token(&self) -> Option<&'matcher Token> {
```

2024-05-18 09:47 UTC, fee1-dead commented on compiler/rustc_expand/src/mbe/diagnostics.rs
> +pub(super) fn parse_failure_msg(tok: &Token, expect_tok: Option<&Token>) -> Cow<'static, str> {
```suggestion
pub(super) fn parse_failure_msg(tok: &Token, expected_token: Option<&Token>) -> Cow<'static, str> {
```

2024-05-18 10:45 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/9139207334/job/25131240931) [(plain)](https://github.com/rust-lang/rust/commit/62f509bbe39cfea02d01121837e8d7849e945684/checks/25131240931/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#17 exporting to docker image format
#17 sending tarball 32.2s done
#17 DONE 37.4s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
To only update this specific test, also pass `--test-args macros/missing-semi.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/macros/missing-semi.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/macros/missing-semi" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/macros/missing-semi/auxiliary"
--- stderr -------------------------------
error: expected `;`, found `(`
##[error]  --> /checkout/tests/ui/macros/missing-semi.rs:6:5
   |
```

</details>

2024-05-18 11:23 UTC, fee1-dead approved these changes
LGTM, thanks!

2024-05-18 11:23 UTC, fee1-dead commented
@bors r+

2024-05-18 15:12 UTC, merged

2024-05-18 16:27 UTC, rust-timer commented
Finished benchmarking commit (685a80f7a0935c8e5016d8c9cd491937af155dd0): [comparison URL](https://perf.rust-lang.org/compare.html?start=bb97203e37bbdd4588bd684728002077d0073978&end=685a80f7a0935c8e5016d8c9cd491937af155dd0&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=bb97203e37bbdd4588bd684728002077d0073978&end=685a80f7a0935c8e5016d8c9cd491937af155dd0&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=bb97203e37bbdd4588bd684728002077d0073978&end=685a80f7a0935c8e5016d8c9cd491937af155dd0&stat=max-rss)
This benchmark run did not return any relevant results for this metric.

### [Cycles](https://perf.rust-lang.org/compare.html?start=bb97203e37bbdd4588bd684728002077d0073978&end=685a80f7a0935c8e5016d8c9cd491937af155dd0&stat=cycles:u)
<details>
<summary>Results (primary 4.6%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 4.6% | [4.6%, 4.6%] | 1     |
| Regressions ❌ <br /> (secondary)  | -    | -            | 0     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 4.6% | [4.6%, 4.6%] | 1     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=bb97203e37bbdd4588bd684728002077d0073978&end=685a80f7a0935c8e5016d8c9cd491937af155dd0&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 668.952s -> 669.005s (0.01%)
**Artifact size**: 316.33 MiB -> 316.23 MiB (-0.03%)