Make more of the test suite run on Mac Catalyst
rust-lang/rust pull request #125226
Opened 2024-05-17 20:36 UTC by madsmtm

Combined with https://github.com/rust-lang/rust/pull/125225, the only failing parts of the test suite are in `tests/rustdoc-js`, `tests/rustdoc-js-std` and `tests/debuginfo`. Tested with:
```console
./x test --target=aarch64-apple-ios-macabi library/std
./x test --target=aarch64-apple-ios-macabi --skip=tests/rustdoc-js --skip=tests/rustdoc-js-std --skip=tests/debuginfo tests
```

Will probably put up a PR later to enable _running_ on (not just compiling for) Mac Catalyst in CI, though not sure where exactly I should do so? `src/ci/github-actions/jobs.yml`?

Note that I've deliberately _not_ enabled stack overflow handlers on iOS/tvOS/watchOS/visionOS (see https://github.com/rust-lang/rust/issues/25872), but rather just skipped those tests, as it uses quite a few APIs that I'd be weary about getting rejected by the App Store (note that Swift doesn't do it on those platforms either).

r? @workingjubilee

CC @thomcc

@rustbot label O-ios O-apple

2024-05-18 00:13 UTC, jieyouxu approved these changes
bootstrap, compiletest and `tests/*` changes look good to me. Feel free to r=me for those changes if the libs changes look good.

2024-05-22 00:00 UTC, workingjubilee requested changes
Could you rename the `issues-{N}.rs` tests we're diffing here to include their implied subject first, since we're touching them anyway? Well, the ones you figured out what they're for, at least, and that don't have like 5 other associated files. You don't have to do anything that touches the `ENTRY_LIMIT` numbers, just the Big List Of Badly Named Tests (those are less merge-conflict-y because they're separate lines of text).

2024-05-22 00:13 UTC, workingjubilee commented on library/std/src/sys/pal/unix/stack_overflow.rs
> +// <https://github.com/apple/swift/blob/swift-5.10-RELEASE/stdlib/public/runtime/CrashHandlerMacOS.cpp>
And based on the exclusion notes on the `stack-probes.rs` test, we still emit binaries with `__stack_chk_guard` and such, right? And so do they? So it's less about whether the stack is protected and more about the error message.

2024-05-22 00:14 UTC, workingjubilee commented on tests/ui/abi/stack-probes.rs
> +//@ ignore-visionos Stack probes are enabled, but the SIGSEGV handler isn't
We should probably have a version of this test that doesn't rely on std's stack overflow handler to work.

2024-05-27 13:29 UTC, madsmtm commented
Ended up touching `ENTRY_LIMIT`, it really made sense for the `osx-frameworks.rs` test. Tell me if I should revert that.

2024-05-27 13:29 UTC, madsmtm commented on tests/ui/abi/stack-probes.rs
> +//@ ignore-visionos Stack probes are enabled, but the SIGSEGV handler isn't
Opened in https://github.com/rust-lang/rust/issues/125390

2024-05-27 21:15 UTC, workingjubilee approved these changes
Yay!

2024-05-27 21:15 UTC, workingjubilee commented
@bors r+

2024-05-28 10:33 UTC, madsmtm commented
Fixed the conflict, you're probably right that I shouldn't have touched `ENTRY_LIMIT`...

@rustbot ready

2024-05-28 17:34 UTC, workingjubilee commented
@bors r+

2024-05-29 06:13 UTC, merged