Skip expected_projection if proj_ty is forbidden
rust-lang/rust pull request #125774
Opened 2024-05-30 14:49 UTC by mu001999

Fixes #125757

2024-05-30 15:54 UTC, petrochenkov commented
r? types

2024-05-30 16:29 UTC, compiler-errors commented on compiler/rustc_infer/src/infer/error_reporting/note_and_explain.rs
> +                            // proj ty is forbidden as the type of a const generic parameter, skip it
This comment and the line below it have no obvious connection.

What does `ObligationCauseCode::WhereClause` have to do with "forbidden as the type of a const generic parameter"?

2024-05-30 16:29 UTC, compiler-errors requested changes
I don't believe this is the correct fix for the issue.

2024-05-30 23:30 UTC, mu001999 commented
@compiler-errors how about the new change? I added a boolean to check the type is used as the type of a constant, which is forbidden.

2024-05-30 23:31 UTC, compiler-errors commented
This still seems like not the correct approach. What is wrong with the approach that I suggested in https://github.com/rust-lang/rust/pull/125774#issuecomment-2140177439?

2024-05-30 23:43 UTC, compiler-errors approved these changes

2024-05-31 00:03 UTC, mu001999 commented
@compiler-errors I tried this when I first touched this issue, it works indeed. But after skimming through the call logic, I just think we shouldn't call `expected_projection` if the projection appeared in a forbidden context, then we also don't want the new helps like:
```
   = help: consider constraining the associated type `<i32 as Trait>::Type` to `usize`
```

But I agree that current approach is enough.

2024-05-31 00:23 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/9310657719/job/25628466030) [(plain)](https://github.com/rust-lang/rust/commit/83870cd9c730cff726317df918f58b99866e2401/checks/25628466030/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Root directory input is valid!
Beginning upload of artifact content to blob storage
Uploaded bytes 8388608
Uploaded bytes 12641787
##[error]The server is busy.
RequestId:76d33db9-c01e-00c8-6af0-b2fca5000000
Time:2024-05-31T00:18:51.0220708Z
```

</details>

2024-05-31 00:25 UTC, mu001999 commented
Looks some unexpected fail, how to restart the CI 😂:
![](https://github.com/rust-lang/rust/assets/21022101/9b0d60a6-7b29-41e2-954e-b94f10fce815)

2024-05-31 00:58 UTC, compiler-errors commented
@bors r+ rollup

2024-05-31 10:04 UTC, merged