tests: Add ui/higher-ranked/trait-bounds/normalize-generic-arg.rs
rust-lang/rust pull request #126137
Opened 2024-06-07 19:06 UTC by Enselic

This adds a regression test for an ICE "accidentally" fixed by https://github.com/rust-lang/rust/pull/101947 that does not add a test for this particular case.

Closes #107564.

I have confirmed the added test code fails with `nightly-2023-01-09` (and passes with `nightly-2023-01-10`).

2024-06-07 23:28 UTC, simulified commented
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

2024-06-08 15:15 UTC, compiler-errors requested changes
This probably shouldn't be added as a test, since it's exercising behavior that we may not expect to work on the new trait solver. Type inferfence in higher-ranked associated types is kinda busted.

If you *really* want to add this test, then you should probably add two explicit revisions for the old and new trait solver. Grep the ui test suite for some lines to steal: `//@ revisions: current next`.

Also, this test name is not really complete. It should mention something like higher-ranked. Maybe `rigid-equate-projections-in-higher-ranked-fn-signature`.

2024-06-08 15:52 UTC, Enselic commented
> This probably shouldn't be added as a test, since it's exercising behavior that we may not expect to work on the new trait solver. Type inferfence in higher-ranked associated types is kinda busted.

My main goal is to close #107564. Personally I'm completely fine with closing it with motivation "we don't want a test for this case".

But for now I updated the test.

> If you _really_ want to add this test, then you should probably add two explicit revisions for the old and new trait solver. Grep the ui test suite for some lines to steal: `//@ revisions: current next`.

Done!

> Also, this test name is not really complete. It should mention something like higher-ranked. Maybe `rigid-equate-projections-in-higher-ranked-fn-signature`.

I thought it was sufficient that it was put in a dir called higher-ranked. But your name is much better than mine regardless. Done!

2024-06-08 16:45 UTC, fmease commented on tests/ui/higher-ranked/trait-bounds/rigid-equate-projections-in-higher-ranked-fn-signature.rs
> +/// This triggers an ICE with (and without) `--emit metadata` using the old
(minot) either `//` (preferably) or `//!`. rn, this is "documenting" the trait, not the crate

2024-06-08 18:16 UTC, compiler-errors approved these changes

2024-06-08 18:16 UTC, compiler-errors commented
@bors r+

2024-06-08 18:16 UTC, compiler-errors commented
@bors rollup

2024-06-09 11:44 UTC, merged