Urls to docs in rust_hir
rust-lang/rust pull request #126303
Opened 2024-06-12 06:13 UTC by sancho20021

2024-06-12 11:59 UTC, compiler-errors requested changes
Please squash this into one commit as well.

I also wonder if we should move this comment to `ItemKind` and `ExprKind`. Also it may be useful to note that the reference does not document nightly-only features, and that there may be slight differences in the names and representation of AST nodes between the compiler and the reference.

2024-06-12 11:59 UTC, compiler-errors commented on compiler/rustc_hir/src/hir.rs
> +/// For more details, see the [rust lang reference]
```suggestion
/// For more details, see the [rust lang reference].
```

2024-06-12 11:59 UTC, compiler-errors commented on compiler/rustc_hir/src/hir.rs
> +/// For more details, see the [rust lang reference]
```suggestion
/// For more details, see the [rust lang reference].
```

2024-06-13 01:03 UTC, sancho20021 commented on compiler/rustc_hir/src/hir.rs
> +/// For more details, see the [rust lang reference]
fixed

2024-06-13 01:03 UTC, sancho20021 commented on compiler/rustc_hir/src/hir.rs
> +/// For more details, see the [rust lang reference]
fixed

2024-06-13 01:06 UTC, sancho20021 commented
> I also wonder if we should move this comment to `ItemKind` and `ExprKind`.
Maybe, but I see `Item` and `Expr` as the main entities which the developer operates with in many functions. Just less clicks to find the reference.

> Also it may be useful to note that the reference does not document nightly-only features, and that there may be slight differences in the names and representation of AST nodes between the compiler and the reference.
Left a note

2024-06-13 01:08 UTC, compiler-errors approved these changes

2024-06-13 01:08 UTC, compiler-errors commented
@bors r+ rollup

2024-06-13 07:10 UTC, merged