rustdoc: Add support for `missing_unsafe_on_extern` feature
rust-lang/rust pull request #126761
Opened 2024-06-20 20:25 UTC by GuillaumeGomez

Follow-up of https://github.com/rust-lang/rust/pull/124482.

Not sure if the `safe` keyword is supposed to be displayed or not though? For now I didn't add it in the generated doc, only `unsafe` as usual.

cc @spastorino 
r? @fmease

2024-06-21 17:58 UTC, spastorino commented
Looks good to me in principle but I think we would want ...

```rust
unsafe extern {
    safe fn foo();
}
```

To actually show in rustdoc that the function is "safe" instead of "". Because "" means unsafe inside extern blocks.

2024-06-21 18:01 UTC, spastorino requested changes

2024-06-21 18:01 UTC, spastorino commented on tests/rustdoc/unsafe-extern-blocks.rs
> +    // @has - '//pre[@class="rust item-decl"]' 'pub extern "C" fn foo()'
`pub safe extern "C" fn foo()`

2024-06-21 18:01 UTC, spastorino commented on tests/rustdoc/unsafe-extern-blocks.rs
> +}
I'd also add `pub unsafe fn baz()` and `pub unsafe static BAZ: i32` to tests.

2024-06-21 21:06 UTC, GuillaumeGomez commented
> Looks good to me in principle but I think we would want ...
> 
> ```rust
> unsafe extern {
>     safe fn foo();
> }
> ```
> 
> To actually show in rustdoc that the function is "safe" instead of "". Because "" means unsafe inside extern blocks.

I'm a bit shared about this. The important information here I think is whether the function needs an `unsafe` block to be called, not how it's declared. Therefore, the `safe` keyword doesn't provide additional information to the reader in this case. Or did I misunderstand something?

2024-06-22 18:30 UTC, spastorino commented
You're right, I forgot that `extern fn foo()` is different than `extern { fn foo() }`.

@bors r+

2024-06-22 23:08 UTC, merged

2024-06-23 00:22 UTC, rust-timer commented
Finished benchmarking commit (3cb521a4344f0b556b81c55eec8facddeb1ead83): [comparison URL](https://perf.rust-lang.org/compare.html?start=a0f01c3c1067aecb3d1ad88621bb4d63d0a2d289&end=3cb521a4344f0b556b81c55eec8facddeb1ead83&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=a0f01c3c1067aecb3d1ad88621bb4d63d0a2d289&end=3cb521a4344f0b556b81c55eec8facddeb1ead83&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=a0f01c3c1067aecb3d1ad88621bb4d63d0a2d289&end=3cb521a4344f0b556b81c55eec8facddeb1ead83&stat=max-rss)
<details>
<summary>Results (primary 2.3%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 2.3% | [2.3%, 2.3%] | 1     |
| Regressions ❌ <br /> (secondary)  | -    | -            | 0     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 2.3% | [2.3%, 2.3%] | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=a0f01c3c1067aecb3d1ad88621bb4d63d0a2d289&end=3cb521a4344f0b556b81c55eec8facddeb1ead83&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=a0f01c3c1067aecb3d1ad88621bb4d63d0a2d289&end=3cb521a4344f0b556b81c55eec8facddeb1ead83&stat=size:linked_artifact)
<details>
<summary>Results (secondary 0.0%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 0.0% | [0.0%, 0.0%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

**Bootstrap**: 692.158s -> 691.006s (-0.17%)
**Artifact size**: 326.67 MiB -> 326.81 MiB (0.04%)