Wrap too long type name
rust-lang/rust pull request #127418
Opened 2024-07-06 10:15 UTC by GuillaumeGomez

Fixes https://github.com/rust-lang/rust/issues/120595.

Takeover of #126209.

cc @BradMarr
r? @notriddle

2024-07-06 10:59 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/9818505921/job/27111121129) [(plain)](https://github.com/rust-lang/rust/commit/06b735e7590138c5ee27e86d377742157d0616fd/checks/27111121129/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
.......... (120/124)
...F       (124/124)


/checkout/tests/rustdoc-gui/sidebar-source-code-display.goml sidebar-source-code-display... FAILED
[ERROR] `tests/rustdoc-gui/sidebar-source-code-display.goml` line 145: The following errors happened: [expected `2516` for window property `pageYOffset`, found `2493`]: for command `assert-window-property: {"pageYOffset": |y_offset|}`
[ERROR] `tests/rustdoc-gui/sidebar-source-code-display.goml` line 152: The following errors happened: [expected `2516` for window property `pageYOffset`, found `2493`]: for command `assert-window-property: {"pageYOffset": |y_offset|}`
Error: ()
Build completed unsuccessfully in 0:03:04
  local time: Sat Jul  6 10:58:26 UTC 2024
  network time: Sat, 06 Jul 2024 10:58:26 GMT
```

</details>

2024-07-06 14:54 UTC, GuillaumeGomez commented
Weird, different size locally vs in CI. Oh well...

2024-07-06 16:10 UTC, notriddle requested changes
Okay, it's really, really important to include a screenshot on a change that's this drastic:

Don't like it.

![image](https://github.com/rust-lang/rust/assets/1593513/aee46b00-326a-4bf0-a6dd-c44d000ecb09)

Also:

* If the text is going to be aligned to the right, it should be consistently aligned to the right. Notice, in the above screenshot, `array` is ragged-right, but `slice` is ragged-left.

* Even if it is consistent, that's merely better. It's not actually *good*. Large amounts of English, like these descriptions, should always be written left-to-right.

2024-07-07 10:58 UTC, the8472 commented
https://github.com/rust-lang/rust/issues/120595#issuecomment-2093833131 cites table layout intrinsic width issues.

I'm not sure if that's correct. The issue seems to be that the table columns have different `overflow-wrap` rules. If *both* are set to `anywhere` then it looks mostly fine(-ish). It could use some polish to indicate that wrapping happened, a dash or an indent on.

![image](https://github.com/rust-lang/rust/assets/1065730/08b9ef13-74ff-4b3d-ac6a-79083c28bb63)

2024-07-17 12:35 UTC, GuillaumeGomez commented
Finally took the time to update. I reverted back to the table display but with some small differences: there is now a padding at the bottom to make it easier to spot which item's short doc we're reading and also set the width of the items name fixed (to 50% of the parent) so that whatever their size, the display remains the same. Screenshots:

![Screenshot from 2024-07-17 14-27-33](https://github.com/user-attachments/assets/f2518559-001b-4bf8-96d3-2eb8acf65ca9)
![Screenshot from 2024-07-17 14-27-52](https://github.com/user-attachments/assets/23a77f14-d7a7-415d-8448-b8a0910ca705)
![Screenshot from 2024-07-17 14-29-52](https://github.com/user-attachments/assets/a3f6274e-4139-4a14-b287-9d0af9e11bd6)

2024-07-17 12:35 UTC, GuillaumeGomez commented
I'll add GUI tests once we agree with the UI changes.

@rustbot ready

2024-07-17 13:19 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/9974275301/job/27561430285) [(plain)](https://github.com/rust-lang/rust/commit/35fb71f30a9e4294c7017724ab3c7b2e776a13a6/checks/27561430285/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
.......... (120/124)
...F       (124/124)


/checkout/tests/rustdoc-gui/type-declation-overflow.goml type-declation-overflow... FAILED
[ERROR] `tests/rustdoc-gui/type-declation-overflow.goml` line 19: The following errors happened (for selector `.item-table .struct`): [expected `684` for property `"offsetWidth"`, found `392`]: for command `assert-property: (".item-table .struct", {"offsetWidth": "684"})`
Error: ()
Build completed unsuccessfully in 0:03:07
  local time: Wed Jul 17 13:19:02 UTC 2024
  network time: Wed, 17 Jul 2024 13:19:02 GMT
```

</details>

2024-07-18 12:35 UTC, GuillaumeGomez commented
If one item is super long and the others are "normal", then the rendering is the same. One thing I dislike with the current display is that the position of the short documentation changes depending on the width of the biggest item name. That's why I decided to go for fixed width (with still handling too long name).

2024-07-18 13:49 UTC, GuillaumeGomez commented
That's a good point. Gonna add UI tests to this new size then.

2024-07-18 18:48 UTC, GuillaumeGomez commented
Reduced the width of items name to 33% and added a GUI test.

2024-07-19 04:26 UTC, merged

2024-07-22 01:26 UTC, cynecx commented on src/librustdoc/html/static/css/rustdoc.css
> +		padding-bottom: 5px;
Maybe it's just me but this makes the spacing in the y-axis look so "wasteful" and a bit unnatural. Is this really necessary? Or why can't we keep the old behavior.