as_simd: fix doc comment to be in line with align_to
rust-lang/rust pull request #127422
Opened 2024-07-06 12:01 UTC by greaka

In #121201, the guarantees about `align_offset` and `align_to` were changed. This PR aims to correct the doc comment of `as_simd` to be in line with the new `align_to`.

Tagging #86656 for good measure.

2024-07-11 21:24 UTC, workingjubilee requested changes
Did you run `cargo fmt` or something instead of `./x.py fmt`?  In any case, please back out the formatting changes to unrelated code so I can approve this.

2024-07-11 21:24 UTC, workingjubilee commented on library/core/src/slice/iter.rs
> +                if (self.predicate)(l, r) {
why was this changed?

2024-07-11 21:24 UTC, workingjubilee commented on library/core/src/slice/iter.rs
> +                if (self.predicate)(l, r) {
???

2024-07-11 21:26 UTC, greaka commented
That'd explain it, thanks!

2024-07-11 21:26 UTC, greaka commented
@rustbot review

2024-07-11 22:00 UTC, workingjubilee commented
Great! @bors r+ rollup

2024-07-12 03:21 UTC, workingjubilee approved these changes

2024-07-12 06:01 UTC, merged