More suggestion for transforming `Option<&Vec<T>>` to `Option<&[T]>` or `&[T]`
rust-lang/rust pull request #127596
Opened 2024-07-11 05:24 UTC by tesuji

Please review commit-by-commit.
Fix #127545

2024-07-11 05:32 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/9885974221/job/27304921662) [(plain)](https://github.com/rust-lang/rust/commit/b3964c06cc0632c2b378d2b44e31a79485666961/checks/27304921662/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Getting action download info
Download action repository 'msys2/setup-msys2@v2.22.0' (SHA:cc11e9188b693c2b100158c3322424c4cc1dadea)
Download action repository 'actions/checkout@v4' (SHA:692973e3d937129bcbf40652eb9f2f61becf3332)
Download action repository 'actions/upload-artifact@v4' (SHA:0b2256b8c012f0828dc542b3febcab082c67f72b)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
---
COPY scripts/sccache.sh /scripts/
RUN sh /scripts/sccache.sh

COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt \
    && pip3 install virtualenv
COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---

#12 [5/8] COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
#12 DONE 0.0s

#13 [6/8] RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt     && pip3 install virtualenv
#13 0.434   Downloading binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
#13 0.451 Collecting boolean-py==4.0
#13 0.458   Downloading boolean.py-4.0-py3-none-any.whl (25 kB)
#13 0.474 Collecting chardet==5.1.0
---
#13 3.581 Building wheels for collected packages: reuse
#13 3.582   Building wheel for reuse (pyproject.toml): started
#13 3.905   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 3.906   Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=181117 sha256=f5f58750481f69515c2c0d1d503daf565e2565c370d07fc6aeb95fe3498b4269
#13 3.906   Stored in directory: /tmp/pip-ephem-wheel-cache-fb_zme62/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
#13 3.909 Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
#13 3.931   Attempting uninstall: setuptools
#13 3.932     Found existing installation: setuptools 59.6.0
#13 3.933     Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
#13 3.933     Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
#13 3.933     Can't uninstall 'setuptools'. No files were found to uninstall.
#13 4.617 Successfully installed binaryornot-0.4.4 boolean-py-4.0 chardet-5.1.0 jinja2-3.1.2 license-expression-30.0.0 markupsafe-2.1.1 python-debian-0.1.49 reuse-1.1.0 setuptools-66.0.0
#13 4.618 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 5.129 Collecting virtualenv
#13 5.181   Downloading virtualenv-20.26.3-py3-none-any.whl (5.7 MB)
#13 5.379      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 29.0 MB/s eta 0:00:00
#13 5.432 Collecting platformdirs<5,>=3.9.1
#13 5.439   Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
#13 5.474 Collecting filelock<4,>=3.12.2
#13 5.481   Downloading filelock-3.15.4-py3-none-any.whl (16 kB)
#13 5.500 Collecting distlib<1,>=0.3.7
#13 5.507   Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
#13 5.516      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 KB 69.8 MB/s eta 0:00:00
#13 5.604 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 5.776 Successfully installed distlib-0.3.8 filelock-3.15.4 platformdirs-4.2.2 virtualenv-20.26.3
#13 DONE 5.9s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      227264 kB
DirectMap2M:     8161280 kB
DirectMap1G:    10485760 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.03s
##[endgroup]
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/e1f45a1442bb373429b6b0838e8ef806ddddfeef/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/llvm-e1f45a1442bb373429b6b0838e8ef806ddddfeef-true/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm
---
##[endgroup]
fmt check
fmt: checked 5247 files
tidy check
tidy error: file `tests/ui/mismatched_types/issue-127545-option-of-ref.rs` must begin with a descriptive name, consider `{reason}-issue-127545.rs`
removing old virtual environment
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (24.1)
  Downloading pip-24.1.2-py3-none-any.whl.metadata (3.6 kB)
Downloading pip-24.1.2-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 52.8 MB/s eta 0:00:00
Installing collected packages: pip
---
checking C++ file formatting
some tidy checks failed


Command BootstrapCommand { command: LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" RUSTC="/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/rustc" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/rust-tidy" "/checkout" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "/checkout/obj/build" "4" "--extra-checks=py:lint,cpp:fmt", failure_behavior: DelayFail, stdout: Print, stderr: Print, run_always: false } did not execute successfully.

Build completed unsuccessfully in 0:01:12
  local time: Thu Jul 11 05:32:02 UTC 2024
  network time: Thu, 11 Jul 2024 05:32:02 GMT
```

</details>

2024-07-11 05:40 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/9886075783/job/27305198557) [(plain)](https://github.com/rust-lang/rust/commit/7e719c9e4ba697e064a7fbf21288cdf543e94a33/checks/27305198557/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Getting action download info
Download action repository 'msys2/setup-msys2@v2.22.0' (SHA:cc11e9188b693c2b100158c3322424c4cc1dadea)
Download action repository 'actions/checkout@v4' (SHA:692973e3d937129bcbf40652eb9f2f61becf3332)
Download action repository 'actions/upload-artifact@v4' (SHA:0b2256b8c012f0828dc542b3febcab082c67f72b)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
---
COPY scripts/sccache.sh /scripts/
RUN sh /scripts/sccache.sh

COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt \
    && pip3 install virtualenv
COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---

#12 [5/8] COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
#12 DONE 0.0s

#13 [6/8] RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt     && pip3 install virtualenv
#13 0.415   Downloading binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
#13 0.427 Collecting boolean-py==4.0
#13 0.431   Downloading boolean.py-4.0-py3-none-any.whl (25 kB)
#13 0.441 Collecting chardet==5.1.0
---
#13 3.407 Building wheels for collected packages: reuse
#13 3.408   Building wheel for reuse (pyproject.toml): started
#13 3.727   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 3.728   Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=181117 sha256=f5f58750481f69515c2c0d1d503daf565e2565c370d07fc6aeb95fe3498b4269
#13 3.728   Stored in directory: /tmp/pip-ephem-wheel-cache-ak4j9umd/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
#13 3.731 Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
#13 3.753   Attempting uninstall: setuptools
#13 3.754     Found existing installation: setuptools 59.6.0
#13 3.755     Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
---
#13 4.977   Downloading virtualenv-20.26.3-py3-none-any.whl (5.7 MB)
#13 5.055      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 74.5 MB/s eta 0:00:00
#13 5.109 Collecting filelock<4,>=3.12.2
#13 5.112   Downloading filelock-3.15.4-py3-none-any.whl (16 kB)
#13 5.142 Collecting platformdirs<5,>=3.9.1
#13 5.145   Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
#13 5.161 Collecting distlib<1,>=0.3.7
#13 5.164   Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
#13 5.171      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 KB 106.6 MB/s eta 0:00:00
#13 5.258 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 5.434 Successfully installed distlib-0.3.8 filelock-3.15.4 platformdirs-4.2.2 virtualenv-20.26.3
#13 DONE 5.5s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      219072 kB
DirectMap2M:    10266624 kB
DirectMap1G:     8388608 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.03s
##[endgroup]
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/8c39ac9eccdfaeff11bd3b6107817a81fe0a3a43/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/llvm-8c39ac9eccdfaeff11bd3b6107817a81fe0a3a43-true/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm
---
##[endgroup]
fmt check
fmt: checked 5247 files
tidy check
tidy error: file `tests/ui/mismatched_types/issue-127545-option-of-ref.rs` must begin with a descriptive name, consider `{reason}-issue-127545.rs`
removing old virtual environment
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (24.1)
  Downloading pip-24.1.2-py3-none-any.whl.metadata (3.6 kB)
Downloading pip-24.1.2-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 71.7 MB/s eta 0:00:00
Installing collected packages: pip
---
checking C++ file formatting
some tidy checks failed


Command BootstrapCommand { command: LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" RUSTC="/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/rustc" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/rust-tidy" "/checkout" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "/checkout/obj/build" "4" "--extra-checks=py:lint,cpp:fmt", failure_behavior: DelayFail, stdout: Print, stderr: Print, run_always: false } did not execute successfully.

Build completed unsuccessfully in 0:01:13
  local time: Thu Jul 11 05:40:45 UTC 2024
  network time: Thu, 11 Jul 2024 05:40:45 GMT
```

</details>

2024-07-11 13:25 UTC, compiler-errors requested changes
This PR implements two basically unrelated suggestions. Could you please split it into two PRs?

My opinion about these two suggestions are split. I think the first suggestion is fine and we can land it (8acf2e408dc8afe0ced20808fa7f39acad0e1916), but the second (7e719c9e4ba697e064a7fbf21288cdf543e94a33) seems somewhat invasive and also really specific, to the point that I don't think we should land it. Putting a new suggestion right into the middle of the argument checking logic seems like the wrong thing to do IMO, and I don't know if there's an easier way to do it.

2024-07-11 18:52 UTC, compiler-errors commented
@rustbot author

2024-07-11 22:13 UTC, tesuji commented
Alright, I'll split this PR into 2 parts. 

About:
> the second (https://github.com/rust-lang/rust/commit/7e719c9e4ba697e064a7fbf21288cdf543e94a33) seems somewhat invasive and also really specific, to the point that I don't think we should land it. 

I mean people prefer using `Option::unwrap_or` over manually matching seem to be benefit from this suggest.

> Putting a new suggestion right into the middle of the argument checking logic seems like the wrong thing to do IMO

I don't understand what it means. That change add a new suggestion in `fn report_arg_errors` 
https://github.com/rust-lang/rust/blob/bcf1f6db4594ae6132378b179a30cdb3599a863d/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs#L482
and it is laid after `suggest_ptr_null_mut`, which is also a suggestion:
https://github.com/rust-lang/rust/blob/bcf1f6db4594ae6132378b179a30cdb3599a863d/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs#L944-L949

2024-07-11 22:25 UTC, tesuji commented on compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs
> +            } else if let ty::Ref(_, peeled_found_ty, _) = found_ty_inner.kind()
This change is necessary. Because suggesting `Option<String>.map(|v| v.as_str())` is violating ownership rules.

2024-07-11 22:47 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/9899274480/job/27347881708) [(plain)](https://github.com/rust-lang/rust/commit/a40ade5f30f08dfc053472239b1924262d4702ae/checks/27347881708/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 46)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 49)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 61)
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---

---- [ui] tests/ui/mismatched_types/transforming-option-ref-issue-127545.rs stdout ----
diff of stderr:

13 LL |     arg.map(|v| &**v)
15 
- error: aborting due to 1 previous errors
+ error: aborting due to 1 previous error
17 
---
To only update this specific test, also pass `--test-args mismatched_types/transforming-option-ref-issue-127545.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/mismatched_types/transforming-option-ref-issue-127545.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/mismatched_types/transforming-option-ref-issue-127545" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/mismatched_types/transforming-option-ref-issue-127545/auxiliary"
--- stderr -------------------------------
error[E0308]: mismatched types
##[error]  --> /checkout/tests/ui/mismatched_types/transforming-option-ref-issue-127545.rs:5:5
   |
   |
LL | pub fn foo(arg: Option<&Vec<i32>>) -> Option<&[i32]> {
   |                                       -------------- expected `Option<&[i32]>` because of return type
LL |     arg //~ ERROR 5:5: 5:8: mismatched types [E0308]
   |     ^^^ expected `Option<&[i32]>`, found `Option<&Vec<i32>>`
   |
   = note: expected enum `Option<&[i32]>`
              found enum `Option<&Vec<i32>>`
help: try using `.map(|v| &**v)` to convert `Option<&Vec<i32>>` to `Option<&[i32]>`
   |
LL |     arg.map(|v| &**v) //~ ERROR 5:5: 5:8: mismatched types [E0308]

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0308`.
```

</details>

2024-07-12 00:02 UTC, compiler-errors commented
@bors r+ rollup

2024-07-12 06:01 UTC, merged