Fix doc nits
rust-lang/rust pull request #127765
Opened 2024-07-15 15:05 UTC by bitfield

Many tiny changes to stdlib doc comments to make them consistent (for example "Returns foo", rather than "Return foo"), adding missing periods, paragraph breaks, backticks for monospace style, and other minor nits.

2024-07-15 15:10 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/9941849485/job/27461949275) [(plain)](https://github.com/rust-lang/rust/commit/840170027671291887b4f198de1b90e77c2d052d/checks/27461949275/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Getting action download info
Download action repository 'msys2/setup-msys2@v2.22.0' (SHA:cc11e9188b693c2b100158c3322424c4cc1dadea)
Download action repository 'actions/checkout@v4' (SHA:692973e3d937129bcbf40652eb9f2f61becf3332)
Download action repository 'actions/upload-artifact@v4' (SHA:0b2256b8c012f0828dc542b3febcab082c67f72b)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
---
COPY scripts/sccache.sh /scripts/
RUN sh /scripts/sccache.sh

COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt \
    && pip3 install virtualenv
COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---

#12 [5/8] COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
#12 DONE 0.0s

#13 [6/8] RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt     && pip3 install virtualenv
#13 0.463   Downloading binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
#13 0.478 Collecting boolean-py==4.0
#13 0.485   Downloading boolean.py-4.0-py3-none-any.whl (25 kB)
#13 0.501 Collecting chardet==5.1.0
---
#13 3.814 Building wheels for collected packages: reuse
#13 3.815   Building wheel for reuse (pyproject.toml): started
#13 4.163   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 4.164   Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=181117 sha256=f5f58750481f69515c2c0d1d503daf565e2565c370d07fc6aeb95fe3498b4269
#13 4.164   Stored in directory: /tmp/pip-ephem-wheel-cache-ci8yw14q/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
#13 4.167 Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
#13 4.190   Attempting uninstall: setuptools
#13 4.191     Found existing installation: setuptools 59.6.0
#13 4.192     Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
#13 4.192     Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
#13 4.193     Can't uninstall 'setuptools'. No files were found to uninstall.
#13 4.897 Successfully installed binaryornot-0.4.4 boolean-py-4.0 chardet-5.1.0 jinja2-3.1.2 license-expression-30.0.0 markupsafe-2.1.1 python-debian-0.1.49 reuse-1.1.0 setuptools-66.0.0
#13 4.897 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 5.449 Collecting virtualenv
#13 5.495   Downloading virtualenv-20.26.3-py3-none-any.whl (5.7 MB)
#13 5.701      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 28.0 MB/s eta 0:00:00
#13 5.743 Collecting distlib<1,>=0.3.7
#13 5.750   Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
#13 5.760      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 KB 57.0 MB/s eta 0:00:00
#13 5.791 Collecting platformdirs<5,>=3.9.1
#13 5.797   Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
#13 5.836 Collecting filelock<4,>=3.12.2
#13 5.842   Downloading filelock-3.15.4-py3-none-any.whl (16 kB)
#13 5.933 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 6.121 Successfully installed distlib-0.3.8 filelock-3.15.4 platformdirs-4.2.2 virtualenv-20.26.3
#13 DONE 6.2s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      227264 kB
DirectMap2M:     7112704 kB
DirectMap1G:    11534336 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.04s
##[endgroup]
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/d3dd34a1d4a7e25a92a0d65994bb01a5d17c59ee/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/llvm-d3dd34a1d4a7e25a92a0d65994bb01a5d17c59ee-true/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm
---
   Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
    Finished `release` profile [optimized] target(s) in 28.93s
##[endgroup]
fmt check
##[error]Diff in /checkout/library/alloc/src/collections/btree/map/entry.rs at line 189:
 
 
     /// Ensures a value is in the entry by inserting, if empty, the result of the default function.
+    ///
+    ///
     /// This method allows for generating key-derived values for insertion by providing the default
     /// function a reference to the key that was moved during the `.entry(key)` method call.
     ///
##[error]Diff in /checkout/library/alloc/src/collections/binary_heap/mod.rs at line 965:
 
 
     /// Returns an iterator which retrieves elements in heap order.
+    ///
     /// This method consumes the original heap.
     ///
     /// # Examples
     /// # Examples
##[error]Diff in /checkout/library/core/src/panicking.rs at line 314:
 ///
 /// This is a separate function to avoid the codesize impact of each crate containing the string to
 /// pass to `panic_nounwind`.
-/// 
 /// This function is called directly by the codegen backend, and must not have
 /// any extra arguments (including those synthesized by track_caller).
 /// any extra arguments (including those synthesized by track_caller).
 #[cfg_attr(not(feature = "panic_immediate_abort"), inline(never), cold)]
fmt error: Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/library/std/tests/common/mod.rs" "/checkout/library/std/tests/slice-from-array-issue-113238.rs" "/checkout/library/std/tests/env.rs" "/checkout/library/std/benches/hash/set_ops.rs" "/checkout/library/std/benches/hash/map.rs" "/checkout/library/std/benches/hash/mod.rs" "/checkout/library/std/benches/lib.rs" "/checkout/library/rustc-std-workspace-core/lib.rs" "/checkout/library/rtstartup/rsbegin.rs" "/checkout/library/rtstartup/rsend.rs" "/checkout/library/rustc-std-workspace-std/lib.rs" "/checkout/library/panic_abort/src/android.rs" "/checkout/library/panic_abort/src/lib.rs" "/checkout/library/panic_abort/src/zkvm.rs" "/checkout/library/rustc-std-workspace-alloc/lib.rs" "/checkout/library/alloc/src/ffi/c_str/tests.rs" "/checkout/library/alloc/src/ffi/mod.rs" "/checkout/library/alloc/src/ffi/c_str.rs" "/checkout/library/alloc/src/borrow.rs" "/checkout/library/alloc/src/rc.rs" "/checkout/library/alloc/src/macros.rs" "/checkout/library/alloc/src/collections/linked_list.rs" "/checkout/library/alloc/src/collections/vec_deque/macros.rs" "/checkout/library/alloc/src/collections/vec_deque/iter.rs" "/checkout/library/alloc/src/collections/vec_de [...]

2024-07-16 22:33 UTC, tgross35 commented
This is great, but covers a ton of area. Could you split it up into a separate PR for each crate (or smaller yet) so it is easier to review and get through?

2024-07-18 10:34 UTC, joboet requested changes
In imperative-style programming, which Rust follows, the program is a sequence of instructions to the computer. With the current documentation style, you could replace the function calls with the first line of the documentation and the code would still make sense. Take for example
```rust
std::alloc::alloc(layout);
```
What is it that you tell the computer to do?
```text
Allocate memory with the global allocator.
```

I find this style much cleaner. Of course, this is subjective, but this is what has been established in `std` and thus much of the ecosystem. Feel free to open an issue if you want to make your point, but I will not accept this PR until consensus has been reached that we want this.

There are some very reasonable changes in here as well, feel free to submit a PR only containing those.

2024-07-18 14:48 UTC, bitfield commented
> Of course, this is subjective, but this is what has been established in `std` and thus much of the ecosystem. Feel free to open an issue if you want to make your point, but I will not accept this PR until consensus has been reached that we want this.

Thanks, @joboet. Like you, I can see the arguments for that style of documentation comment—shall we call it the "Allocate" style, as opposed to the alternative "Allocates" style?

I'm personally neutral about this: either style would work for me, but I put a high value on *consistency*: I try to use either one style or the other throughout a particular codebase.

I'll let others weigh in on what they think the right style is for the Rust standard library, but a couple of points that might be worth considering in favour of the "Allocates" style are:

* The [Rust Book](https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html#making-useful-documentation-comments) uses this style in its example doc comments
* The majority—I think, on a casual survey, the *vast* majority—of the stdlib code uses this style too. Indeed, it was not easy to track down many examples of the alternate style to fix in this PR.

For example, here are the first words of each of the doc comments for the current set of macros in `std` (if they start with a verb):

```
Asserts
Asserts
Asserts
Evaluates
Expands
Causes
Concatenates
Prints
Asserts
Asserts
Asserts
Inspects
Prints
Prints
Expands
Creates
Constructs
Parses
Includes
Includes
Expands
Returns
Expands
Panics
Prints
Prints
Stringifies
Declare
Indicates
Unwraps
Indicates
Indicates
Creates
Writes
Write
Concatenates
Concatenates
Prints
Enables
```

I make it 37 for the "Allocates" style, and only 2 for the "Allocate" style—it doesn't seem unreasonable to assume that this 95% — 5% split applies roughly equally across the standard library. To be clear, this PR proposes that the 5% be updated to match the 95%: I think you are suggesting that it should be the other way round. If I've got that wrong, please correct me.

If the consensus is that all the "Allocates" comments should be changed to "Allocate" style, then I'm equally happy to help with that work too, but it would be, of course, a much bigger change and a much bigger job.

2024-07-23 13:30 UTC, joboet commented
Those are from 2014, I'm not sure whether that's still our policy.

@rustbot label +I-libs-api-nominated
or maybe this is a question for T-style?

2024-07-23 15:17 UTC, joshtriplett commented
We reviewed this in today's libs-api meeting. Apparently we have a previously accepted RFC that specifically recommends the other way, and as @bitfield noted, much of the library is consistent with that. See https://github.com/rust-lang/rfcs/blob/master/text/1574-more-api-documentation-conventions.md#appendix-a-full-conventions-text for that convention.

We may want to put those conventions somewhere more visible.

2024-07-25 10:04 UTC, bitfield commented
Thanks @joshtriplett—I had a feeling I'd seen this text somewhere, but couldn't track it down. As you say, maybe there are ways we could make it more visible—a mention in the book, perhaps.

@joboet, if you're satisfied that the RFC establishes a consensus for the main changes in this PR, it's ready for you to take another look at, as soon as you can spare the time. I appreciate your guidance.

2024-07-28 12:20 UTC, dtolnay approved these changes
Thank you! This is terrific.

2024-07-28 12:20 UTC, dtolnay commented
@bors r+

2024-07-28 21:13 UTC, merged