Migrate `static-dylib-by-default`, `sanitizer-dylib-link`, `sanitizer-cdylib-link` and `sanitizer-staticlib-link` `run-make` tests to rmake
rust-lang/rust pull request #128079
Opened 2024-07-22 20:36 UTC by Oneirical

Part of #121876 and the associated [Google Summer of Code project](https://blog.rust-lang.org/2024/05/01/gsoc-2024-selected-projects.html).

Please try:

try-job: x86_64-msvc

2024-07-23 08:03 UTC, jieyouxu commented
@bors delegate+ (for try jobs)

2024-07-23 14:27 UTC, Oneirical commented
@bors try

2024-07-23 16:03 UTC, rust-log-analyzer commented
The job **`x86_64-msvc`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/10060860884/job/27809486360) [(plain)](https://github.com/rust-lang-ci/rust/commit/1caa5b7bbdd048303ee316de9aebe2794dc1e750/checks/27809486360/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Updating files:  98% (47801/48776)
Updating files:  99% (48289/48776)
Updating files: 100% (48776/48776)
Updating files: 100% (48776/48776), done.
branch 'try' set up to track 'origin/try'.
Switched to a new branch 'try'
[command]"C:\Program Files\Git\bin\git.exe" log -1 --format='%H'
'1caa5b7bbdd048303ee316de9aebe2794dc1e750'
##[group]Run src/ci/scripts/setup-environment.sh
src/ci/scripts/setup-environment.sh
---
file:.git/config remote.origin.url=https://github.com/rust-lang-ci/rust
file:.git/config remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config gc.auto=0
file:.git/config http.https://github.com/.extraheader=AUTHORIZATION: basic ***
file:.git/config branch.try.remote=origin
file:.git/config branch.try.merge=refs/heads/try
file:.git/config submodule.library/backtrace.url=https://github.com/rust-lang/backtrace-rs.git
file:.git/config submodule.library/stdarch.active=true
file:.git/config submodule.library/stdarch.url=https://github.com/rust-lang/stdarch.git
file:.git/config submodule.src/doc/book.active=true
---
---- [run-make] tests\run-make\static-dylib-by-default stdout ----

error: rmake recipe failed to complete
status: exit code: 1
command: "C:\\a\\rust\\rust\\build\\x86_64-pc-windows-msvc\\test\\run-make\\static-dylib-by-default\\rmake.exe"
--- stderr -------------------------------
command failed at line 19
command failed at line 19
Command { cmd: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MT" "-Brepro" "main.c" "-Fe:main.exe" "-Fo:main.obj" "bar.dll" "ws2_32.lib" "userenv.lib" "advapi32.lib" "bcrypt.lib" "ntdll.lib" "synchronization.lib", stdin: None, drop_bomb: DropBomb { command: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX64\\x64\\cl.exe", defused: true, armed_location: Location { file: "C:\\a\\rust\\rust\\tests\\run-make\\static-dylib-by-default\\rmake.rs", line: 19, col: 5 } } }
output status: `exit code: 2`
=== STDOUT ===
main.c
bar.dll : fatal error LNK1107: invalid or corrupt file: cannot read at 0x2E8


=== STDERR ===
=== STDERR ===
cl : Command line warning D9024 : unrecognized source file type 'bar.dll', object file assumed



failures:
failures:
    [run-make] tests\run-make\static-dylib-by-default

test result: FAILED. 261 passed; 1 failed; 90 ignored; 0 measured; 0 filtered out; finished in 81.43s

Some tests failed in compiletest suite=run-make mode=run-make host=x86_64-pc-windows-msvc target=x86_64-pc-windows-msvc
Build completed unsuccessfully in 1:28:48
make: *** [Makefile:102: ci-msvc-ps1] Error 1
  network time: Tue, 23 Jul 2024 16:03:28 GMT
##[error]Process completed with exit code 2.
Post job cleanup.
[command]"C:\Program Files\Git\bin\git.exe" version
```

</details>

2024-07-23 17:47 UTC, Oneirical commented
`let dylib = if is_msvc() { "bar.dll.lib" } else { &dynamic_lib_name("bar") };`

Ugly hack, but worth seeing if it works. @bors try

2024-07-23 19:34 UTC, Oneirical commented
@rustbot review

The hack is pretty ugly, but it's what the original test did. Tell me what you think @rustbot review

2024-07-24 18:55 UTC, jieyouxu requested changes

2024-07-26 15:45 UTC, Oneirical commented
All review requests implemented. @rustbot review

2024-07-27 12:45 UTC, jieyouxu approved these changes
Thanks, mostly LGTM now, just a question about whether we need either `--target` or `ignore-cross-compile`.

2024-07-27 12:45 UTC, jieyouxu commented on tests/run-make/sanitizer-cdylib-link/rmake.rs
> +    rustc().arg("-g").arg("-Zsanitizer=address").crate_type("bin").input("program.rs").run();
Question: do we need `--target $TARGET` here as well, or do we need `ignore-cross-compile` because we are running the binary?

2024-07-27 12:45 UTC, jieyouxu commented on tests/run-make/sanitizer-dylib-link/rmake.rs
> +    rustc().arg("-g").arg("-Zsanitizer=address").crate_type("bin").input("program.rs").run();
Question: similarly here with `--target` or `ignore-cross-compile`.

2024-07-27 12:45 UTC, jieyouxu commented on tests/run-make/sanitizer-staticlib-link/rmake.rs
> +    run_fail("program").assert_stderr_contains("stack-buffer-overflow");
Question: and here about cross-compile cases.

2024-07-27 12:47 UTC, jieyouxu commented
To help answer those questions, let's run a couple of try jobs to see if it might be a problem (it might *still* be, even if the edge case is not exercised in current CI jobs).

@bors try

2024-07-27 12:47 UTC, jieyouxu commented
@rustbot author

2024-07-27 16:16 UTC, jieyouxu approved these changes
Thanks

2024-07-27 16:16 UTC, jieyouxu commented
@bors r+ rollup=iffy (sanitizer, linking, msvc specific behaviors, you name it)

2024-07-27 23:34 UTC, rust-log-analyzer commented
The job **`x86_64-msvc-ext`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/10126718581/job/28003706613) [(plain)](https://github.com/rust-lang-ci/rust/commit/7cb87cc05572889f0878865f0d3875ee124c479f/checks/28003706613/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Finished `release` profile [optimized] target(s) in 0.38s
##[endgroup]
[TIMING] core::build_steps::tool::ToolBuild { compiler: Compiler { stage: 1, host: x86_64-pc-windows-msvc }, target: x86_64-pc-windows-msvc, tool: "miri", path: "src/tools/miri", mode: ToolRustc, source_type: InTree, extra_features: [], allow_features: "", cargo_args: [] } -- 0.422
thread 'main' panicked at src/lib.rs:1727:17:
failed to copy `C:\a\rust\rust\build\x86_64-pc-windows-msvc\stage1-tools\x86_64-pc-windows-msvc\release\miri.exe` to `C:\a\rust\rust\build\x86_64-pc-windows-msvc\stage1\bin\miri.exe`: The process cannot access the file because it is being used by another process. (os error 32)
Build completed unsuccessfully in 0:00:09
  local time: Sat, Jul 27, 2024 11:34:16 PM
  network time: Sat, 27 Jul 2024 23:34:16 GMT
##[error]Process completed with exit code 1.
```

</details>

2024-07-27 23:52 UTC, jieyouxu commented
@bors retry (failed to copy `miri.exe`: "The process cannot access the file because it is being used by another process. (os error 32)")

2024-07-28 06:40 UTC, merged

2024-07-28 07:57 UTC, rust-timer commented
Finished benchmarking commit (3148b35f6a6226548929c12da529ab0d1a4b47d5): [comparison URL](https://perf.rust-lang.org/compare.html?start=385a74f50f6743ba60b4ce07283adbbae63f1279&end=3148b35f6a6226548929c12da529ab0d1a4b47d5&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=385a74f50f6743ba60b4ce07283adbbae63f1279&end=3148b35f6a6226548929c12da529ab0d1a4b47d5&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=385a74f50f6743ba60b4ce07283adbbae63f1279&end=3148b35f6a6226548929c12da529ab0d1a4b47d5&stat=max-rss)
<details>
<summary>Results (primary -4.0%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -4.0% | [-4.0%, -4.0%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -4.0% | [-4.0%, -4.0%] | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=385a74f50f6743ba60b4ce07283adbbae63f1279&end=3148b35f6a6226548929c12da529ab0d1a4b47d5&stat=cycles:u)
<details>
<summary>Results (secondary -2.4%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -2.4% | [-2.4%, -2.4%] | 1     |
| All ❌✅ (primary)                 | -     | -              | 0     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=385a74f50f6743ba60b4ce07283adbbae63f1279&end=3148b35f6a6226548929c12da529ab0d1a4b47d5&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 770.543s -> 769.808s (-0.10%)
**Artifact size**: 331.59 MiB -> 331.62 MiB (0.01%)