Point at binding declaration on closure capture note
rust-lang/rust pull request #128121
Opened 2024-07-23 23:34 UTC by estebank

```
error[E0308]: mismatched types
  --> $DIR/closure-no-fn-1.rs:6:29
   |
LL |     let foo: fn(u8) -> u8 = |v: u8| { a += v; a };
   |              ------------   ^^^^^^^^^^^^^^^^^^^^^ expected fn pointer, found closure
   |              |
   |              expected due to this
   |
   = note: expected fn pointer `fn(u8) -> u8`
                 found closure `{closure@$DIR/closure-no-fn-1.rs:6:29: 6:36}`
note: closures can only be coerced to `fn` types if they do not capture any variables
  --> $DIR/closure-no-fn-1.rs:6:39
   |
LL |     let mut a = 0u8;
   |         ----- `a` declared here
LL |     let foo: fn(u8) -> u8 = |v: u8| { a += v; a };
   |                                       ^ `a` captured here
```

"`a` declared here" is new.

r? @compiler-errors

2024-07-23 23:36 UTC, compiler-errors requested changes
I'm having trouble understanding how this is providing useful information for the user, rather than just pointing out more labels which clutters the diagnostic output. The user should be able to gather the right information here already because we point out the name of the variable.

2024-07-23 23:39 UTC, compiler-errors commented
The only case where I expect this to matter is if a local variable were shadowing a const or static (i.e. not captured), but we don't allow local variables to shadow statics, and trying to name a local after a const also doesn't work because of name resolution issues.

I also don't expect this to happen to other named items like functions.

2024-07-24 00:00 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/10067868549/job/27832167138) [(plain)](https://github.com/rust-lang/rust/commit/878d735e61e6496b68fc6539ed72544c946163be/checks/27832167138/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
------
 > importing cache manifest from ghcr.io/rust-lang/rust-ci-cache:3aacb9c90579defe09351ac5e8ee504359f8054da6326ff19038f1b7c90e3cb2aafe33685c6d9b76ee8d2ccbd187ca80c46ab5380485abdd8c0ce7d69cd8d8fd:
------
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---

---- [ui] tests/ui/closures/closure-no-fn-3.rs stdout ----
diff of stderr:

7 note: closures can only be coerced to `fn` types if they do not capture any variables
9    |
+ LL |     let b = 0u8;
+    |         - `b` declared here
+    |         - `b` declared here
10 LL |     let baz: fn() -> u8 = (|| { b }) as fn() -> u8;
11    |                                 ^ `b` captured here


The actual stderr differed from the expected stderr.
The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/closures/closure-no-fn-3/closure-no-fn-3.stderr
To only update this specific test, also pass `--test-args closures/closure-no-fn-3.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/closures/closure-no-fn-3.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/closures/closure-no-fn-3" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/closures/closure-no-fn-3/auxiliary"
--- stderr -------------------------------
--- stderr -------------------------------
error[E0605]: non-primitive cast: `{closure@/checkout/tests/ui/closures/closure-no-fn-3.rs:6:28: 6:30}` as `fn() -> u8`
   |
   |
LL |     let baz: fn() -> u8 = (|| { b }) as fn() -> u8;
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^ invalid cast
   |
note: closures can only be coerced to `fn` types if they do not capture any variables
   |
LL |     let b = 0u8;
   |         - `b` declared here
   |         - `b` declared here
LL |     let baz: fn() -> u8 = (|| { b }) as fn() -> u8;
   |                                 ^ `b` captured here
error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0605`.
------------------------------------------
```

</details>

2024-07-24 17:09 UTC, estebank commented
Fair enough. I do find that pointing at definitions helps *me* to better get a sense of what's happening, but it might be that I lean more on code that shadows local variables than the mean user.

2024-07-24 17:09 UTC, closed without merging