core: use `compare_bytes` for more slice element types
rust-lang/rust pull request #128495
Opened 2024-08-01 12:43 UTC by joboet

`bool`, `NonZero<u8>`, `Option<NonZero<u8>>` and `ascii::Char` can be compared the same way as `u8`.

2024-08-01 13:13 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/10198535782/job/28213645124) [(plain)](https://github.com/rust-lang/rust/commit/88fda58bf5396667a022461f9d7465f24fd3395d/checks/28213645124/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
## Running ui tests in tests/fail for x86_64-unknown-linux-gnu
   Compiler: "MIRI_ENV_VAR_TEST"="0" "MIRI_TEMP"="/tmp/miri-uitest-Ub3bqu" "RUST_BACKTRACE"="1" /checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/miri "--error-format=json" "--sysroot=/checkout/obj/build/x86_64-unknown-linux-gnu/miri-sysroot" "-Dwarnings" "-Dunused" "-Ainternal_features" "-Zui-testing" "--target" "x86_64-unknown-linux-gnu" "--out-dir" OUT_DIR

FAILED TEST: tests/fail/uninit/uninit_alloc_diagnostic.rs
command: MIRI_ENV_VAR_TEST="0" MIRI_TEMP="/tmp/miri-uitest-Ub3bqu" RUST_BACKTRACE="1" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/miri" "--error-format=json" "--sysroot=/checkout/obj/build/x86_64-unknown-linux-gnu/miri-sysroot" "-Dwarnings" "-Dunused" "-Ainternal_features" "-Zui-testing" "--target" "x86_64-unknown-linux-gnu" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui/tests/fail/uninit" "tests/fail/uninit/uninit_alloc_diagnostic.rs" "-Zmiri-disable-validation" "--edition" "2021"
error: actual output differed from expected
Execute `./miri test --bless` to update `tests/fail/uninit/uninit_alloc_diagnostic.stderr` to the actual output
--- tests/fail/uninit/uninit_alloc_diagnostic.stderr
+++ <stderr output>
+++ <stderr output>
 error: Undefined Behavior: reading memory at ALLOC[0x0..0x10], but memory is uninitialized at [0x4..0x10], and this operation requires initialized memory
    |
    |
-LL |         let mut order = unsafe { compare_bytes(left.as_ptr(), right.as_ptr(), len) as isize };
+LL |         let mut order = unsafe { compare_bytes(left, right, len) as isize };
-   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ reading memory at ALLOC[0x0..0x10], but memory is uninitialized at [0x4..0x10], and this operation requires initialized memory
+   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ reading memory at ALLOC[0x0..0x10], but memory is uninitialized at [0x4..0x10], and this operation requires initialized memory
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
... 18 lines skipped ...
 error: aborting due to 1 previous error
 
 


full stderr:
error: Undefined Behavior: reading memory at alloc1092[0x0..0x10], but memory is uninitialized at [0x4..0x10], and this operation requires initialized memory
   |
   |
LL |         let mut order = unsafe { compare_bytes(left, right, len) as isize };
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ reading memory at alloc1092[0x0..0x10], but memory is uninitialized at [0x4..0x10], and this operation requires initialized memory
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
   = note: BACKTRACE:
   = note: BACKTRACE:
   = note: inside `<u8 as core::slice::cmp::SliceOrd>::compare` at /checkout/library/core/src/slice/cmp.rs:210:34: 210:65
   = note: inside `core::slice::cmp::<impl std::cmp::Ord for [u8]>::cmp` at /checkout/library/core/src/slice/cmp.rs:30:9: 30:39
  --> tests/fail/uninit/uninit_alloc_diagnostic.rs:20:14
   |
   |
LL |         drop(slice1.cmp(slice2));


Uninitialized memory occurred at alloc1092[0x4..0x10], in this allocation:
alloc1092 (Rust heap, size: 32, align: 8) {
    0x00 │ 41 42 43 44 __ __ __ __ __ __ __ __ __ __ __ __ │ ABCD░░░░░░░░░░░░
    0x10 │ 00 __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ │ .░░░░░░░░░░░░░░░

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to 1 previous error
error: aborting due to 1 previous error


full stdout:



FAILED TEST: tests/fail/uninit/uninit_alloc_diagnostic_with_provenance.rs
command: MIRI_ENV_VAR_TEST="0" MIRI_TEMP="/tmp/miri-uitest-Ub3bqu" RUST_BACKTRACE="1" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/miri" "--error-format=json" "--sysroot=/checkout/obj/build/x86_64-unknown-linux-gnu/miri-sysroot" "-Dwarnings" "-Dunused" "-Ainternal_features" "-Zui-testing" "--target" "x86_64-unknown-linux-gnu" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui/tests/fail/uninit" "tests/fail/uninit/uninit_alloc_diagnostic_with_provenance.rs" "-Zmiri-disable-validation" "--edition" "2021"
error: actual output differed from expected
Execute `./miri test --bless` to update `tests/fail/uninit/uninit_alloc_diagnostic_with_provenance.stderr` to the actual output
--- tests/fail/uninit/uninit_alloc_diagnostic_with_provenance.stderr
+++ <stderr output>
+++ <stderr output>
 error: Undefined Behavior: reading memory at ALLOC[0x0..0x8], but memory is uninitialized at [0x4..0x8], and this operation requires initialized memory
    |
    |
-LL |         let mut order = unsafe { compare_bytes(left.as_ptr(), right.as_ptr(), len) as isize };
+LL |         let mut order = unsafe { compare_bytes(left, right, len) as isize };
-   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ reading memory at ALLOC[0x0..0x8], but memory is uninitialized at [0x4..0x8], and this operation requires initialized memory
+   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ reading memory at ALLOC[0x0..0x8], but memory is uninitialized at [0x4..0x8], and this operation requires initialized memory
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
... 23 lines skipped ...
 error: aborting due to 1 previous error
 
 


full stderr:
error: Undefined Behavior: reading memory at alloc1098[0x0..0x8], but memory is uninitialized at [0x4..0x8], and this operation requires initialized memory
   |
   |
LL |         let mut order = unsafe { compare_bytes(left, right, len) as isize };
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ reading memory at alloc1098[0x0..0x8], but memory is uninitialized at [0x4..0x8], and this operation requires initialized memory
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
   = note: BACKTRACE:
   = note: BACKTRACE:
   = note: inside `<u8 as core::slice::cmp::SliceOrd>::compare` at /checkout/library/core/src/slice/cmp.rs:210:34: 210:65
   = note: inside `core::slice::cmp::<impl std::cmp::Ord for [u8]>::cmp` at /checkout/library/core/src/slice/cmp.rs:30:9: 30:39
  --> tests/fail/uninit/uninit_alloc_diagnostic_with_provenance.rs:31:14
   |
   |
LL |         drop(slice1.cmp(slice2));


Uninitialized memory occurred at alloc1098[0x4..0x8], in this allocation:
alloc1098 (Rust heap, size: 16, align: 8) {
    ╾42[a71]<2372> (1 ptr byte)╼ 12 13 ╾43[a73]<2410> (1 ptr byte)╼ __ __ __ __ __ __ __ __ __ __ __ __ │ ━..━░░░░░░░░░░░░
}
alloc71 (global (static or const), size: 1, align: 1) {
}
}
alloc73 (global (static or const), size: 1, align: 1) {
}

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

---
Error: 
   0: ui tests in tests/fail for x86_64-unknown-linux-gnu failed
   1: tests failed

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
error: test failed, to rerun pass `--test ui`
Caused by:
  process didn't exit successfully: `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/releas [...]

2024-08-01 14:12 UTC, oli-obk commented
slices of all of these seem fairly rare. Not sure how I feel about adding more specialization stuff for them.

2024-08-01 15:34 UTC, joboet commented
It's mostly "cause I can" but I can imagine that this is really beneficial when comparing ASCII-only strings.

2024-08-02 23:15 UTC, saethlin commented
I wasn't thinking of LLVM specifically, just that it would be better if we could automate the detection of types eligible for this optimization by inspecting their layout, instead of attempting to enumerate all of them.

2024-08-04 14:30 UTC, Mark-Simulacrum commented
r? scottmcm

I tend to agree that a new specialization trait doesn't make me feel enthusiastic about this.

2024-08-08 16:15 UTC, scottmcm requested changes
One small thing above, then I think this is good to go.

I'm less convinced about things like `[bool]`, but being able to get a `[NonZero<u8>]` to the before-the-terminator in a `CString` for example would make sense, and it would be unfortunate if that meant a worse `Ord`.

So once we're doing it for two types, might as well do it for `bool` (and `ascii::Char` and …) as well.

2024-08-12 08:24 UTC, joboet commented
@rustbot ready

2024-08-31 20:01 UTC, scottmcm approved these changes

2024-09-01 06:44 UTC, merged