Add lint for recursive default impls
rust-lang/rust pull request #128737
Opened 2024-08-06 15:16 UTC by mj10021

Fixes #128421, where it was pointed out that recursion in default impls can be confusing and always results in failure.

2024-08-06 15:41 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/10269259434/job/28414310725) [(plain)](https://github.com/rust-lang/rust/commit/60e94f6a9b05b6aa691f54471e10da7a3864bfb5/checks/28414310725/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 2.896 Building wheels for collected packages: reuse
#16 2.897   Building wheel for reuse (pyproject.toml): started
#16 3.142   Building wheel for reuse (pyproject.toml): finished with status 'done'
#16 3.143   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132715 sha256=dfa09868353292d98f811d3efdb0d54d07389e808efc71d68e3b93c514bf8bec
#16 3.143   Stored in directory: /tmp/pip-ephem-wheel-cache-420n1o7b/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#16 3.146 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#16 3.547 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#16 3.547 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#16 DONE 3.6s
---
     |
1707 | /     /// The `recursive_dafault_impl` lint detects functions that cannot
1708 | |     /// return without calling themselves.
1709 | |     ///
1710 | |     /// ### Example
1732 | |     /// default struct for this field. This will always lead to an infinite loop
1733 | |     /// so it is denied.
     | |________________________^
     |
---

error: could not document `rustc_lint_defs`
warning: build failed, waiting for other jobs to finish...

Command cd "/checkout" && env -u MAKEFLAGS -u MFLAGS AR_x86_64_unknown_linux_gnu="ar" CARGO_INCREMENTAL="0" CARGO_PROFILE_RELEASE_DEBUG="0" CARGO_PROFILE_RELEASE_DEBUG_ASSERTIONS="true" CARGO_PROFILE_RELEASE_OVERFLOW_CHECKS="true" CARGO_PROFILE_RELEASE_STRIP="false" CARGO_TARGET_DIR="/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc" CC_x86_64_unknown_linux_gnu="sccache cc" CFG_COMPILER_BUILD_TRIPLE="x86_64-unknown-linux-gnu" CFG_COMPILER_HOST_TRIPLE="x86_64-unknown-linux-gnu" CFG_DEFAULT_CODEGEN_BACKEND="llvm" CFG_LIBDIR_RELATIVE="lib" CFG_RELEASE="1.82.0-nightly" CFG_RELEASE_CHANNEL="nightly" CFG_USE_SELF_CONTAINED_LINKER="1" CFG_VERSION="1.82.0-nightly (0da188245 2024-08-06)" CFG_VER_DATE="2024-08-06" CFG_VER_HASH="0da18824570670d84c01a49a8be4653424793898" CFLAGS_x86_64_unknown_linux_gnu="-ffunction-sections -fdata-sections -fPIC -m64" CXXFLAGS_x86_64_unknown_linux_gnu="-ffunction-sections -fdata-sections -fPIC -m64" CXX_x86_64_unknown_linux_gnu="sccache c++" LIBC_CHECK_CFG="1" LLVM_ASSERTIONS="1" LLVM_CONFIG="/checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm/bin/llvm-config" LLVM_LINK_SHARED="1" LLVM_RUSTLLVM="1" RANLIB_x86_64_unknown_linux_gnu="ar s" REAL_LIBRARY_PATH_VAR="LD_LIBRARY_PATH" RUSTBUILD_NATIVE_DIR="/checkout/obj/build/x86_64-unknown-linux-gnu/native" RUSTC="/checkout/obj/build/bootstrap/debug/rustc" RUSTC_BOOTSTRAP="1" RUSTC_BREAK_ON_ICE="1" RUSTC_ERROR_METADATA_DST="/checkout/obj/build/tmp/extended-error-metadata" RUSTC_FORCE_UNSTABLE="1" RUSTC_HOST_FLAGS="--cfg=bootstrap -Zunstable-options --check-cfg=cfg(bootstrap)" RUSTC_INSTALL_BINDIR="bin" RUSTC_LIBDIR="/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" RUSTC_LINT_FLAGS="-Wrust_2018_idioms -Wunused_lifetimes -Dwarnings" RUSTC_REAL="/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/rustc" RUSTC_SNAPSHOT="/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/rustc" RUSTC_SNAPSHOT_LIBDIR="/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" RUSTC_STAGE="0" RUSTC_SYSROOT="/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-sysroot" RUSTC_TLS_MODEL_INITIAL_EXEC="1" RUSTC_VERBOSE="0" RUSTC_VERIFY_LLVM_IR="1" RUSTC_WRAPPER="/checkout/obj/build/bootstrap/debug/rustc" RUSTDOC="/checkout/obj/build/bootstrap/debug/rustdoc" RUSTDOCFLAGS="--cfg=bootstrap --cfg=windows_raw_dylib -Csymbol-mangling-version=v0 -Zunstable-options --check-cfg=cfg(bootstrap) --check-cfg=cfg(parallel_compiler) --document-private-items --document-hidden-items -Dwarnings -Wrustdoc::invalid_codeblock_attributes --crate-version 1.82.0-nightly\t(0da188245\t2024-08-06) --cfg=parallel_compiler --document-private-items -Arustdoc::private-intra-doc-links --enable-index-page -Zunstable-options -Znormalize-docs --show-type-layout -Zcrate-attr=warn(rust_2018_idioms) --extern-html-root-url ena=https://docs.rs/ena/latest/" RUSTDOC_LIBDIR="/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" RUSTDOC_REAL="/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/rustdoc" RUSTFLAGS="--cfg=bootstrap --cfg=windows_raw_dylib -Csymbol-mangling-version=v0 -Zunstable-options --check-cfg=cfg(bootstrap) --check-cfg=cfg(parallel_compiler) -Zmacro-backtrace -Csplit-debuginfo=off -Zunstable-options -Wrustc::internal -Wkeyword_idents_2024 -Wunsafe_op_in_unsafe_fn -Cprefer-dynamic --cfg=parallel_compiler -Clink-args=-Wl,-z,origin -Clink-args=-Wl,-rpath,$ORIGIN/../lib -Zon-broken-pipe=kill" RUST_TEST_THREADS="4" TERM="xterm" WINAPI_NO_BUNDLED_LIBRARIES="1" __CARGO_DEFAULT_LIB_METADATA="bootstrap" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "doc" "--target" "x86_64-unknown-linux-gnu" "--release" "-Zbinary-dep-depinfo" "-j" "4" "--locked" "--color" "always" "--features" "llvm rustc_use_parallel_compiler" "--manifest-path" "/checkout/compiler/rustc/Cargo.toml" "-Zunstable-options" "-Zskip-rustdoc-fingerprint" "--no-deps" "-Zrustdoc-map" "-p" "rustc-main" "-p" "rustc_abi" "-p" "rustc_arena" "-p" "rustc_ast" "-p" "rustc_ast_ir" "-p" "rustc_ast_lowering" "-p" "rustc_ast_passes" "-p" "rustc_ast_pretty" "-p" "rustc_attr" "-p" "rustc_baked_icu_data" "-p" "rustc_borrowck" "-p" "rustc_builtin_macros" "-p" "rustc_codegen_llvm" "-p" "rustc_codegen_ssa" "-p" "rustc_const_eval" "-p" "rustc_data_structures" "-p" "rustc_driver" "-p" "rustc_driver_impl" "-p" "rustc_error_codes" "-p" "rustc_error_messages" "-p" "rustc_errors" "-p" "rustc_expand" "-p" "rustc_feature" "-p" "rustc_fluent_macro" "-p" "rustc_fs_util" "-p" "rustc_graphviz" "-p" "rustc_hir" "-p" "rustc_hir_analysis" "-p" "rustc_hir_pretty" "-p" "rustc_hir_typeck" "-p" "rustc_incremental" "-p" "rustc_index" "-p" "rustc_index_macros" "-p" "rustc_infer" "-p" "rustc_interface" "-p" "rustc_lexer" "-p" "rustc_lint" "-p" "rustc_lint_defs" "-p" "rustc_llvm" "-p" "rustc_log" "-p" "rustc_macros" "-p" "rustc_metadata" "-p" "rustc_middle" "-p" "rustc_mir_build" "-p" "rustc_mir_dataflow" "-p" "rustc_mir_transform" "-p" "rustc_monomorphize" "-p" "rustc_next_trait_solver" "-p" "rustc_parse" "-p" "rustc_parse_format" "-p" "rustc_passes" "-p" "rustc_pattern_analysis" "-p" "rustc_privacy" "-p" "rustc_query_impl" "-p" "rustc_query_system" "-p" "rustc_resolve" "-p" "rustc_sanitizers" "-p" "rustc_serialize" "-p" "rustc_session" "-p" "rustc_smir" "-p" "rustc_span" "-p" "rustc_symbol_mangling" "-p" "rustc_target" "-p" "rustc_trait_selection" "-p" "rustc_traits" "-p" "rustc_transmute" "-p" "rustc_ty_utils" "-p" "rustc_type_ir" "-p" "rustc_type_ir_macros" "-p" "stable_mir" (failure_mode=Exit) did not execute successfully.
Created at: src/core/builder.rs:1413:33
Executed at: src/core/build_steps/doc.rs:874:26

Build completed unsuccessfully in 0:00:45
```

</details>

2024-08-06 17:01 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/10270457910/job/28418239111) [(plain)](https://github.com/rust-lang/rust/commit/9547a7f6303314577e7c6a0c194efb39d3e678bd/checks/28418239111/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 61)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 45)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 46)
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
failures:

---- [ui] tests/ui/lint/lint-unconditional-recursion.rs stdout ----

error: Error: expected failure status (Some(1)) but received status Some(101).
status: exit status: 101
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/lint/lint-unconditional-recursion.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/lint-unconditional-recursion" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/lint-unconditional-recursion/auxiliary"
--- stderr -------------------------------
error: function cannot return without recursing
##[error]  --> /checkout/tests/ui/lint/lint-unconditional-recursion.rs:4:1
   |
   |
LL | fn foo() { //~ ERROR function cannot return without recursing
   | ^^^^^^^^ cannot return without recursing
LL |     foo();
   |     ----- recursive call site
   |
   = help: a `loop` may express intention better if this is on purpose
  --> /checkout/tests/ui/lint/lint-unconditional-recursion.rs:1:9
   |
LL | #![deny(unconditional_recursion)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^
   |         ^^^^^^^^^^^^^^^^^^^^^^^

error: function cannot return without recursing
##[error]  --> /checkout/tests/ui/lint/lint-unconditional-recursion.rs:14:1
   |
LL | fn baz() { //~ ERROR function cannot return without recursing
   | ^^^^^^^^ cannot return without recursing
LL |         baz()
   |         ----- recursive call site
LL |     } else {
LL |         baz()
LL |         baz()
   |         ----- recursive call site
   |
   = help: a `loop` may express intention better if this is on purpose
error: function cannot return without recursing
##[error]  --> /checkout/tests/ui/lint/lint-unconditional-recursion.rs:26:1
   |
   |
LL | fn quz() -> bool { //~ ERROR function cannot return without recursing
   | ^^^^^^^^^^^^^^^^ cannot return without recursing
LL |         while quz() {}
   |               ----- recursive call site
...
...
LL |         loop { quz(); }
   |                ----- recursive call site
   |
   = help: a `loop` may express intention better if this is on purpose
thread 'rustc' panicked at compiler/rustc_hir_analysis/src/collect.rs:1690:22:
thread 'rustc' panicked at compiler/rustc_hir_analysis/src/collect.rs:1690:22:
$ident: found Item { ident: Foo#0, owner_id: DefId(0:8 ~ lint_unconditional_recursion[a4a8]::Foo), kind: Trait(No, Safe, Generics { params: [], predicates: [], has_where_clause_predicates: false, where_clause_span: /checkout/tests/ui/lint/lint-unconditional-recursion.rs:36:10: 36:10 (#0), span: /checkout/tests/ui/lint/lint-unconditional-recursion.rs:36:10: 36:10 (#0) }, [], [TraitItemRef { id: TraitItemId { owner_id: DefId(0:9 ~ lint_unconditional_recursion[a4a8]::Foo::bar) }, ident: bar#0, kind: Fn { has_self: true }, span: /checkout/tests/ui/lint/lint-unconditional-recursion.rs:37:5: 39:6 (#0) }]), span: /checkout/tests/ui/lint/lint-unconditional-recursion.rs:36:1: 40:2 (#0), vis_span: /checkout/tests/ui/lint/lint-unconditional-recursion.rs:36:1: 36:1 (#0) }
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   1: core::panicking::panic_fmt
   2: rustc_hir::hir::expect_failed::<&rustc_hir::hir::Item>
   3: <rustc_hir::hir::Item>::expect_impl
   4: rustc_hir_analysis::collect::impl_trait_header
      [... omitted 2 frames ...]
   5: rustc_middle::query::plumbing::query_get_at::<rustc_query_system::query::caches::DefIdCache<rustc_middle::query::erase::Erased<[u8; 24]>>>
   7: rustc_mir_build::lints::check
   8: rustc_mir_build::build::mir_build
   9: rustc_mir_transform::mir_built
   9: rustc_mir_transform::mir_built
      [... omitted 2 frames ...]
  10: rustc_mir_build::check_unsafety::check_unsafety
      [... omitted 2 frames ...]
  11: <rustc_middle::hir::map::Map>::par_body_owners::<rustc_interface::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}
  12: <rustc_data_structures::sync::parallel::ParallelGuard>::run::<(), rustc_data_structures::sync::parallel::enabled::par_for_each_in<&rustc_span::def_id::LocalDefId, &[rustc_span::def_id::LocalDefId], <rustc_middle::hir::map::Map>::par_body_owners<rustc_interface::passes::run_required_analyses::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#1}::{closure#0}>
  13: <rustc_session::session::Session>::time::<(), rustc_interface::passes::run_required_analyses::{closure#1}>
  14: rustc_interface::passes::analysis
      [... omitted 2 frames ...]
  16: <rustc_interface::interface::Compiler>::enter::<rustc_driver_impl::run_compiler::{closure#0}::{closure#1}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_span::ErrorGuaranteed>>
  17: rustc_span::create_session_globals_then::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::util::run_in_thread_with_globals<rustc_interface::util::run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_driver_impl::run_compiler::{closure#0}>::{closure#1}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for  [...]

2024-08-06 17:31 UTC, compiler-errors requested changes
I don't think this should be a new lint. We already have a lint for when we detect recursive calls, and we can change the wording for that lint if we detect that it's a recursive `Default` invocation.

2024-08-06 17:31 UTC, compiler-errors commented on compiler/rustc_lint_defs/src/builtin.rs
> +    Deny,
This needs T-lang approval if it's going to be a `Deny` lint.

2024-08-06 19:56 UTC, mj10021 commented
> I don't think this should be a new lint. We already have a lint for when we detect recursive calls, and we can change the wording for that lint if we detect that it's a recursive `Default` invocation.

Do you think that it makes sense for the `Self { ..Default::default() }` case to be denied since it is a guaranteed infinite loop or it is too specific off a case to warrant special treatment?

2024-08-06 20:05 UTC, mj10021 commented
@rustbot label +T-Lang

2024-08-24 02:09 UTC, chenyukang commented
yeah, I think it's better to change the wording for existing lint for this specific scenario.

2024-08-24 02:19 UTC, chenyukang commented
@rustbot author

2024-10-30 12:53 UTC, alex-semenyuk commented
@mj10021
From wg-triage. Do you have update on this PR?

2024-10-31 02:07 UTC, mj10021 commented
> @mj10021 From wg-triage. Do you have update on this PR?

Oops, this got away from me, will update the PR shortly

2024-11-21 04:23 UTC, compiler-errors requested changes

2024-11-22 00:32 UTC, compiler-errors requested changes

2024-11-22 00:32 UTC, compiler-errors commented on compiler/rustc_mir_build/messages.ftl
> +mir_build_recursive_default_impl = calling ..Default::default() in a Default implementation leads to infinite recursion, and cannotbe used to initialize the fields of a struct or enum
```suggestion
mir_build_recursive_default_impl = calling `..Default::default()` in a `Default` implementation leads to infinite recursion, and does not initialize the fields of a struct or enum
```

2024-11-22 00:32 UTC, compiler-errors commented on compiler/rustc_mir_build/src/lints.rs
> +use rustc_span::sym;
put these imports at the top of the file.

2024-11-22 00:54 UTC, compiler-errors commented on compiler/rustc_mir_build/messages.ftl
> +mir_build_recursive_default_impl = calling ..Default::default() in a Default implementation leads to infinite recursion, and cannotbe used to initialize the fields of a struct or enum
why did you not fix the backticks?

2024-11-22 00:54 UTC, mj10021 commented on compiler/rustc_mir_build/messages.ftl
> +mir_build_recursive_default_impl = calling ..Default::default() in a Default implementation leads to infinite recursion, and cannotbe used to initialize the fields of a struct or enum
oops my mistake sorry

2024-11-24 18:31 UTC, mj10021 commented
@rustbot review

2024-12-16 19:30 UTC, compiler-errors requested changes
I don't think that this change carries enough benefit, especially b/c I don't believe we can actually tell we're actually in a FRU to make this note accurate.

2024-12-16 19:30 UTC, compiler-errors commented
r? compiler

2025-03-03 14:27 UTC, mj10021 commented
> @mj10021 any updates on this pr? thanks

Sorry, I thought the PR was rejected, are these changes still wanted?

2025-03-30 04:54 UTC, Dylan-DPC commented
@mj10021 ah i was waiting to see if maybe there is some solution to this. I guess not, so I'm fine with closing it. Thanks for contributing.

2025-03-30 04:54 UTC, closed without merging