Coalesce `dep-info`, `dep-info-spaces` and `dep-info-doesnt-run-much` `run-make` tests into `dep-info` rmake.rs
rust-lang/rust pull request #128787
Opened 2024-08-07 15:25 UTC by Oneirical

Part of #121876 and the associated [Google Summer of Code project](https://blog.rust-lang.org/2024/05/01/gsoc-2024-selected-projects.html).

This is one of the most ancient tests in the `run-make` directory and its Makefile does some unexpected things, like creating and deleting a `done` directory over and over, sleeping at certain times (this is the [PR](https://github.com/rust-lang/rust/pull/13288) that added the `sleep`).

I tried to preserve the intent of the test, which is smoke-testing that `dep-info` works.

Try:

try-job: x86_64-msvc
try-job: dist-x86_64-freebsd

2024-08-11 03:11 UTC, jieyouxu approved these changes

2024-08-11 03:11 UTC, jieyouxu commented on tests/run-make/dep-info/rmake.rs
> +// but msys make seems to fail to recognize such paths, so test fails.
Remark: in msys2, the path might actually be a unix path... so our host (`uname -a`) is

```bash
$ uname -a
MSYS_NT-10.0-22631 Joe 3.5.3.x86_64 2024-06-03 06:22 UTC x86_64 Msys
```
 
<img width="617" alt="Screenshot 2024-08-11 111003" src="https://github.com/user-attachments/assets/7071190e-fd1f-4812-aa74-3cd75400660f">

2024-08-11 03:12 UTC, jieyouxu commented
@bors try

2024-08-11 03:21 UTC, jieyouxu approved these changes
Problem: we might actually need a conditional dependency on some kind of `make` here to preserve what the actual test intends to check: what `rustc --dep-info` outputs some Makefile-compatible file that can be successfully interpreted by some `make`. I'm thinking

```
//@ needs-make
```

or something insane like that...

2024-08-11 03:22 UTC, jieyouxu requested changes
Sorry I clicked wrong button

2024-08-11 03:27 UTC, jieyouxu commented on tests/run-make/dep-info-spaces/Makefile.foo
> --include $(TMPDIR)/lib.d
Actually I stand corrected, this doesn't even check `lib.d` is valid Makefile syntax, so I'm fine with what the test does as-is.

2024-08-12 14:31 UTC, Oneirical commented
I'm not sure if you want me to change something in particular. I removed the ignore statement, since the try job passed. @rustbot review

2024-08-15 03:31 UTC, jieyouxu commented on tests/run-make/dep-info/rmake.rs
> +// information about dependencies in a Makefile-compatible format, as a `.d` file.
Suggestion: we should make it clear that we don't attempt to check the `.d` file is in fact Makefile-compatible in this test.

2024-08-15 03:32 UTC, jieyouxu commented
@bors try

2024-08-15 03:33 UTC, jieyouxu commented
Feel free to r=me after clarifying the comment and if try jobs come back green.
@bors delegate+

2024-08-15 03:33 UTC, jieyouxu commented
@bors rollup=iffy (dep info)

2024-08-15 03:34 UTC, jieyouxu commented on tests/run-make/dep-info/rmake.rs
> +// information about dependencies in a Makefile-compatible format, as a `.d` file.
@rustbot author

2024-08-15 03:47 UTC, jieyouxu commented
bors go home you're drunk

2024-08-15 14:16 UTC, Oneirical commented
@bors r=@jieyouxu

2024-08-16 00:56 UTC, merged

2024-08-16 03:09 UTC, rust-timer commented
Finished benchmarking commit (4b7d074d766d00a32fa8b2e4fa3813dd7d4d64e6): [comparison URL](https://perf.rust-lang.org/compare.html?start=2c93fabd98d2c183bcb3afed1f7d51b2517ac5ed&end=4b7d074d766d00a32fa8b2e4fa3813dd7d4d64e6&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=2c93fabd98d2c183bcb3afed1f7d51b2517ac5ed&end=4b7d074d766d00a32fa8b2e4fa3813dd7d4d64e6&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=2c93fabd98d2c183bcb3afed1f7d51b2517ac5ed&end=4b7d074d766d00a32fa8b2e4fa3813dd7d4d64e6&stat=max-rss)
<details>
<summary>Results (primary 2.1%, secondary -1.1%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 2.1%  | [2.1%, 2.1%]   | 1     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -1.1% | [-1.1%, -1.1%] | 1     |
| All ❌✅ (primary)                 | 2.1%  | [2.1%, 2.1%]   | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=2c93fabd98d2c183bcb3afed1f7d51b2517ac5ed&end=4b7d074d766d00a32fa8b2e4fa3813dd7d4d64e6&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=2c93fabd98d2c183bcb3afed1f7d51b2517ac5ed&end=4b7d074d766d00a32fa8b2e4fa3813dd7d4d64e6&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 751.842s -> 750.562s (-0.17%)
**Artifact size**: 339.16 MiB -> 339.13 MiB (-0.01%)