Shrink `TyKind::FnPtr`.
rust-lang/rust pull request #128812
Opened 2024-08-08 07:20 UTC by nnethercote

By splitting the `FnSig` within `TyKind::FnPtr` into `FnSigTys` and `FnHeader`, which can be packed more efficiently. This reduces the size of the hot `TyKind` type from 32 bytes to 24 bytes on 64-bit platforms. This reduces peak memory usage by a few percent on some benchmarks. It also reduces cache misses and page faults similarly, though this doesn't translate to clear cycles or wall-time improvements on CI.

r? @compiler-errors

2024-08-08 07:35 UTC, nnethercote commented
@bors try @rust-timer queue

2024-08-08 07:35 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2024-08-08 07:45 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/10297855916/job/28501793666) [(plain)](https://github.com/rust-lang/rust/commit/f8ed8f14dca321c3ae5260ba12a9a58ab6f0ece8/checks/28501793666/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#14 3.019 Building wheels for collected packages: reuse
#14 3.020   Building wheel for reuse (pyproject.toml): started
#14 3.269   Building wheel for reuse (pyproject.toml): finished with status 'done'
#14 3.270   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132715 sha256=dfa09868353292d98f811d3efdb0d54d07389e808efc71d68e3b93c514bf8bec
#14 3.270   Stored in directory: /tmp/pip-ephem-wheel-cache-cdwhvfkg/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#14 3.273 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#14 3.665 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#14 3.665 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#14 DONE 3.8s
---
    Checking rustc_codegen_gcc v0.1.0 (/checkout/compiler/rustc_codegen_gcc)
error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
   --> src/type_of.rs:216:27
    |
216 |                 ty::FnPtr(sig) => {
    |
   ::: /checkout/compiler/rustc_type_ir/src/ty_kind.rs:147:11
    |
    |
147 |     FnPtr(ty::Binder<I, FnInsOut<I>>, Csa<I>),
    |
help: use `_` to explicitly ignore each field
    |
    |
216 |                 ty::FnPtr(sig, _) => {

For more information about this error, try `rustc --explain E0023`.
error: could not compile `rustc_codegen_gcc` (lib) due to 1 previous error
Build completed unsuccessfully in 0:02:41
```

</details>

2024-08-08 09:29 UTC, rust-timer commented
Queued 5cf59d66c11c39fb631bbe241ebfe4cf84296da7 with parent 9337f7afa6fda07e60d6aa5ee88e692878446782, future [comparison URL](https://perf.rust-lang.org/compare.html?start=9337f7afa6fda07e60d6aa5ee88e692878446782&end=5cf59d66c11c39fb631bbe241ebfe4cf84296da7).
There are currently 3 preceding artifacts in the [queue](https://perf.rust-lang.org/status.html).
It will probably take at least ~11.3 hours until the benchmark run finishes.
<!-- rust-timer: temporary -->

2024-08-08 15:44 UTC, compiler-errors commented
(premature note given that this is still in testing phase, and you already are likely planning on it, but if i don't note it now i will certainly forget: given that this touches rustc type ir, make sure that either lcnr or i get to review this when it's ready)

2024-08-08 22:17 UTC, rust-timer commented
Finished benchmarking commit (5cf59d66c11c39fb631bbe241ebfe4cf84296da7): [comparison URL](https://perf.rust-lang.org/compare.html?start=9337f7afa6fda07e60d6aa5ee88e692878446782&end=5cf59d66c11c39fb631bbe241ebfe4cf84296da7&stat=instructions:u).

### Overall result: ✅ improvements - no action needed


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

@bors rollup=never
@rustbot label: -S-waiting-on-perf -perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=9337f7afa6fda07e60d6aa5ee88e692878446782&end=5cf59d66c11c39fb631bbe241ebfe4cf84296da7&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -0.5% | [-0.5%, -0.5%] | 1     |
| All ❌✅ (primary)                 | -     | -              | 0     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=9337f7afa6fda07e60d6aa5ee88e692878446782&end=5cf59d66c11c39fb631bbe241ebfe4cf84296da7&stat=max-rss)
<details>
<summary>Results (primary -2.1%, secondary -0.4%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 6.9%  | [6.9%, 6.9%]   | 1     |
| Regressions ❌ <br /> (secondary)  | 4.1%  | [1.9%, 5.6%]   | 5     |
| Improvements ✅ <br /> (primary)   | -3.4% | [-5.9%, -0.5%] | 7     |
| Improvements ✅ <br /> (secondary) | -2.4% | [-3.7%, -1.1%] | 11    |
| All ❌✅ (primary)                 | -2.1% | [-5.9%, 6.9%]  | 8     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=9337f7afa6fda07e60d6aa5ee88e692878446782&end=5cf59d66c11c39fb631bbe241ebfe4cf84296da7&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=9337f7afa6fda07e60d6aa5ee88e692878446782&end=5cf59d66c11c39fb631bbe241ebfe4cf84296da7&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 762.874s -> 762.449s (-0.06%)
**Artifact size**: 337.10 MiB -> 337.11 MiB (0.00%)

2024-08-09 03:41 UTC, nnethercote commented
r? @compiler-errors 

This is a peak memory use win in exchange for strictly worse ergonomics when dealing with `TyKind::FnPtr`. I think it's probably worth it: memory use wins are hard to find, `TyKind` is one of the most often instantiated types in the entire compiler, it has 21 variants and `TyKind::FnPtr` is the biggest one by eight bytes, and it's bigger only because the data it contains has too much padding. With my memory profiling hat on, it's screaming out to be optimized. If you check "Show non-relevant results" in the CI perf results you see it's a 0.4% peak memory reduction when averaged across every single benchmark, which might sound small but is actually pretty big. For several benchmarks the reduction is above 2%. Cache misses and page faults have similar numbers.

Here's the type size data:
```
print-type-size type: `rustc_middle::ty::ty_kind::TyKind<rustc_middle::ty::TyCtxt<'_>>`: 32 bytes, alignment: 8 bytes
print-type-size     discriminant: 1 bytes
print-type-size     variant `FnPtr`: 31 bytes
print-type-size         padding: 7 bytes
print-type-size         field `.0`: 24 bytes, alignment: 8 bytes

print-type-size type: `rustc_middle::infer::canonical::rustc_type_ir::Binder<rustc_middle::ty::TyCtxt<'_>, rustc_middle::ty::ty_kind::FnSig<rustc_middle::ty::TyCtxt<'_>>>`: 24 bytes, alignment: 8 bytes
print-type-size     field `.bound_vars`: 8 bytes
print-type-size     field `.value`: 16 bytes 

print-type-size type: `rustc_middle::ty::ty_kind::FnSig<rustc_middle::ty::TyCtxt<'_>>`: 16 bytes, alignment: 8 bytes
print-type-size     field `.inputs_and_output`: 8 bytes
print-type-size     field `.abi`: 2 bytes
print-type-size     field `.c_variadic`: 1 bytes
print-type-size     field `.safety`: 1 bytes
print-type-size     end padding: 4 bytes
```
The post-discriminant padding in `TyKind` is 7 bytes. When the `FnSig` in broken into two pieces, the compiler moves the four bytes `abi`/`c_variadic`/`safety` data into that 7 bytes.

I previously tried a different tack, interning `FnSig` and then putting a pointer to the interned value in `TyKind::FnPtr`, but the `rustc_type_ir`/`rustc_middle` split made it much uglier and more invasive than this approach.

2024-08-09 03:45 UTC, compiler-errors requested changes

2024-08-09 03:46 UTC, compiler-errors commented on compiler/rustc_type_ir/src/fast_reject.rs
> +                        && obl_csa.safety == impl_csa.safety
Does this type (which I'd rather we call `FnHeader`) not impl `PartialEq`?

2024-08-09 03:49 UTC, nnethercote commented on compiler/rustc_type_ir/src/ty_kind.rs
> +    pub fn separate(self) -> (ty::Binder<I, FnInsOut<I>>, FnCsa<I>) {
I originally called it `split` and it didn't compile exactly because that name was already in use...

2024-08-09 03:52 UTC, compiler-errors commented on compiler/rustc_type_ir/src/ty_kind.rs
> +    pub fn separate(self) -> (ty::Binder<I, FnInsOut<I>>, FnCsa<I>) {
?!

Ah, [`Binder::split`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_infer/infer/canonical/ir/struct.Binder.html#method.split).

2024-08-09 03:53 UTC, compiler-errors commented on compiler/rustc_type_ir/src/ty_kind.rs
> +    pub fn separate(self) -> (ty::Binder<I, FnInsOut<I>>, FnCsa<I>) {
Do we even use that anywhere? I'd rather we repurpose this name for that.

Alternatively, we could call it `split_sig` or something.

2024-08-09 03:55 UTC, nnethercote commented on compiler/rustc_type_ir/src/fast_reject.rs
> +                        && obl_csa.safety == impl_csa.safety
Oh, it does, I overlooked that it could be used here.

2024-08-09 03:56 UTC, nnethercote commented on compiler/rustc_type_ir/src/ty_kind.rs
> +pub struct FnCsa<I: Interner> {
Sure. Is `hdr` ok for variable names?

2024-08-09 03:56 UTC, nnethercote commented on compiler/rustc_type_ir/src/ty_kind.rs
> +pub struct FnInsOut<I: Interner>(pub I::Tys);
Ok. Is `tys` ok for variable names?

2024-08-09 03:58 UTC, compiler-errors commented on compiler/rustc_type_ir/src/ty_kind.rs
> +pub struct FnCsa<I: Interner> {
Sure

2024-08-09 03:58 UTC, compiler-errors commented on compiler/rustc_type_ir/src/fast_reject.rs
> +                        && obl_csa.safety == impl_csa.safety
There's a few other simplifications that I'll point out in review.

2024-08-09 03:59 UTC, compiler-errors commented on compiler/rustc_type_ir/src/ty_kind.rs
> +pub struct FnInsOut<I: Interner>(pub I::Tys);
I'd prefer `sig_tys`, but not particularly strongly I guess.

2024-08-09 04:02 UTC, nnethercote commented on compiler/rustc_type_ir/src/ty_kind.rs
> +    pub fn separate(self) -> (ty::Binder<I, FnInsOut<I>>, FnCsa<I>) {
`Binder::split` is indeed unused. I'll remove it and rename this one.

2024-08-09 04:03 UTC, compiler-errors commented
I'm generally of the opinion that the impact to the usability of `ty::FnPtr` is low enough, if you think from a performance perspective that this perf win is worthwhile. 0.4~2% peak memory reduction does seem pretty small to me lol, but I also don't know what those numbers mean in production.

I'm not certain if you're willing to waste time applying my naming nits *now* given that there's a chance that someone @rust-lang/types might have a differing opinion, given the nature of the change being more invasive than other "change the level of derefs that need to be applied to the type" type changes like interning data. I'd be happy to hold off on unnecessary churn until we can get anyone who wants to speak their mind a chance to do so.

2024-08-09 04:19 UTC, compiler-errors commented
Would be worthwhile also to fill out the PR description summarizing the motivation and effect of this change, for anyone who sees this PR tomorrow.

2024-08-09 04:39 UTC, nnethercote commented
I updated the names. It wasn't hard and your suggestions were a clear improvement on the original version.

2024-08-09 08:56 UTC, lcnr commented
I think this change is acceptable to decrease the type size by 8 bytes :+1:

2024-08-10 00:44 UTC, compiler-errors reviewed
OK one final round of tweaks

2024-08-12 05:40 UTC, nnethercote commented on compiler/rustc_codegen_gcc/src/type_of.rs
> +                    .fn_ptr_backend_type(cx.fn_abi_of_fn_ptr(ins_out.with(csa), ty::List::empty())),
I don't think there's much difference either way. There's no obvious natural order. Having said that, this order (`sig_tys` first, then `hdr`) matches the order I used in the `TyKind::FnPtr` variant, which matches the order in `FnSig`. So I'm inclined to leave it as is.

2024-08-12 05:51 UTC, nnethercote commented on compiler/rustc_middle/src/ty/flags.rs
> +                computation.add_ty(ins_out.output());
I'll make it a named field called `inputs_and_output`.

2024-08-12 06:07 UTC, nnethercote commented
There are four new commits. I made the changes you suggested, except for the `with` case, for the reasons explained above.

2024-08-14 00:22 UTC, compiler-errors reviewed
One more change that I don't think got applied

2024-08-14 00:22 UTC, compiler-errors commented on compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs
> +                if sig_tys.with(hdr).is_fn_trait_compatible() {
`is_fn_trait_compatible` should be implemented as a function on `FnHeader`

2024-08-14 00:29 UTC, compiler-errors commented
@bors r+ rollup=never

2024-08-14 00:29 UTC, compiler-errors commented on compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs
> +                if sig_tys.with(hdr).is_fn_trait_compatible() {
Apparently most callsites either already create a `FnSig` immediately after, or don't have a header (e.g. `FnDef`)

2024-08-14 03:45 UTC, merged

2024-08-14 05:00 UTC, rust-timer commented
Finished benchmarking commit (e9c965df7b75ab5b1ae8f9a2680839ac1a1a3880): [comparison URL](https://perf.rust-lang.org/compare.html?start=e5b3e68abf170556b9d56c6f9028318e53c9f06b&end=e9c965df7b75ab5b1ae8f9a2680839ac1a1a3880&stat=instructions:u).

### Overall result: ✅ improvements - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=e5b3e68abf170556b9d56c6f9028318e53c9f06b&end=e9c965df7b75ab5b1ae8f9a2680839ac1a1a3880&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -0.2% | [-0.6%, -0.1%] | 3     |
| All ❌✅ (primary)                 | -     | -              | 0     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=e5b3e68abf170556b9d56c6f9028318e53c9f06b&end=e9c965df7b75ab5b1ae8f9a2680839ac1a1a3880&stat=max-rss)
<details>
<summary>Results (primary -2.7%, secondary 0.1%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.0%  | [1.0%, 1.0%]   | 1     |
| Regressions ❌ <br /> (secondary)  | 4.1%  | [2.4%, 5.3%]   | 4     |
| Improvements ✅ <br /> (primary)   | -3.6% | [-6.1%, -1.0%] | 4     |
| Improvements ✅ <br /> (secondary) | -2.5% | [-3.3%, -1.4%] | 6     |
| All ❌✅ (primary)                 | -2.7% | [-6.1%, 1.0%]  | 5     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=e5b3e68abf170556b9d56c6f9028318e53c9f06b&end=e9c965df7b75ab5b1ae8f9a2680839ac1a1a3880&stat=cycles:u)
<details>
<summary>Results (secondary 2.1%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 2.1% | [2.1%, 2.1%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=e5b3e68abf170556b9d56c6f9028318e53c9f06b&end=e9c965df7b75ab5b1ae8f9a2680839ac1a1a3880&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 752.981s -> 754.011s (0.14%)
**Artifact size**: 341.50 MiB -> 341.48 MiB (-0.01%)