Remove unneeded return statements
rust-lang/rust pull request #129125
Opened 2024-08-15 14:24 UTC by danik292

Just some clippy warnings fixes.

2024-08-15 18:41 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/10408723698/job/28826769822) [(plain)](https://github.com/rust-lang/rust/commit/b973308c5f96be4c5bcd830ae6fb1d29409097a9/checks/28826769822/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#13 2.730 Building wheels for collected packages: reuse
#13 2.731   Building wheel for reuse (pyproject.toml): started
#13 2.983   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 2.984   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132715 sha256=dfa09868353292d98f811d3efdb0d54d07389e808efc71d68e3b93c514bf8bec
#13 2.985   Stored in directory: /tmp/pip-ephem-wheel-cache-d5g0446u/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#13 2.987 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#13 3.388 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#13 3.388 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 3.919 Collecting virtualenv
#13 3.919 Collecting virtualenv
#13 3.956   Downloading virtualenv-20.26.3-py3-none-any.whl (5.7 MB)
#13 4.030      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 80.3 MB/s eta 0:00:00
#13 4.082 Collecting platformdirs<5,>=3.9.1
#13 4.087   Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
#13 4.105 Collecting distlib<1,>=0.3.7
#13 4.116      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 KB 81.2 MB/s eta 0:00:00
#13 4.149 Collecting filelock<4,>=3.12.2
#13 4.153   Downloading filelock-3.15.4-py3-none-any.whl (16 kB)
#13 4.153   Downloading filelock-3.15.4-py3-none-any.whl (16 kB)
#13 4.233 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 4.419 Successfully installed distlib-0.3.8 filelock-3.15.4 platformdirs-4.2.2 virtualenv-20.26.3
#13 DONE 4.5s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      202688 kB
DirectMap2M:     8185856 kB
DirectMap1G:    10485760 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.04s
##[endgroup]
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/d2b5aa6552c8acf67f38a2ad92062a32ec542f08/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/llvm-d2b5aa6552c8acf67f38a2ad92062a32ec542f08-true/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm
---
##[endgroup]
fmt check
Diff in /checkout/library/core/src/str/pattern.rs:1814:
             }
             mask &= !(1 << trailing);
-         false;
+        false;
     };
 
 
     let test_chunk = |idx| -> u16 {
Diff in /checkout/library/core/src/str/pattern.rs:1830:
         let both = eq_first.bitand(eq_last);
         let mask = both.to_bitmask() as u16;
-         mask;
+        mask;
     };
 
 
     let mut i = 0;
Diff in /checkout/library/core/src/ptr/metadata.rs:187:
         // Consider a reference like `&(i32, dyn Send)`: the vtable will only store the size of the
         // `Send` part!
         // SAFETY: DynMetadata always contains a valid vtable pointer
-         unsafe { crate::intrinsics::vtable_size(self.vtable_ptr() as *const ()) }
+        unsafe { crate::intrinsics::vtable_size(self.vtable_ptr() as *const ()) }
 
     /// Returns the alignment of the type associated with this vtable.
Diff in /checkout/library/core/src/ptr/metadata.rs:194:
     #[inline]
     #[inline]
     pub fn align_of(self) -> usize {
         // SAFETY: DynMetadata always contains a valid vtable pointer
-         unsafe { crate::intrinsics::vtable_align(self.vtable_ptr() as *const ()) }
+        unsafe { crate::intrinsics::vtable_align(self.vtable_ptr() as *const ()) }
 
     /// Returns the size and alignment together as a `Layout`
     /// Returns the size and alignment together as a `Layout`
fmt error: Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/src/tools/coverage-dump/src/covfun.rs" "/checkout/src/tools/coverage-dump/src/prf_names.rs" "/checkout/src/tools/coverage-dump/src/parser.rs" "/checkout/library/core/src/unicode/mod.rs" "/checkout/library/core/src/unicode/printable.rs" "/checkout/library/core/src/unicode/unicode_data.rs" "/checkout/src/tools/rustdoc-themes/main.rs" "/checkout/library/core/src/fmt/float.rs" "/checkout/library/core/src/fmt/mod.rs" "/checkout/library/core/src/fmt/nofloat.rs" "/checkout/library/core/src/fmt/builders.rs" "/checkout/library/core/src/fmt/num.rs" "/checkout/library/core/src/fmt/rt.rs" "/checkout/library/core/src/cell.rs" "/checkout/library/core/src/range.rs" "/checkout/library/core/src/arch.rs" "/checkout/library/core/src/cmp/bytewise.rs" "/checkout/library/core/src/asserting.rs" "/checkout/library/core/src/tuple.rs" "/checkout/library/core/src/pat.rs" "/checkout/library/core/src/panic.rs" "/checkout/src/tools/suggest-tests/src/main.rs" "/checkout/src/tools/suggest-tests/src/static_suggestions.rs" "/checkout/src/tools/suggest-tests/src/dynamic_suggestions.rs" "/checkout/src/tools/suggest-tests/src/lib.rs" "/checkout/src/tools/suggest-tests/src/tests.rs" "/checkout/library/core/src/intrinsics/mir.rs" "/checkout/library/core/src/intrinsics/simd.rs" "/checkout/src/tools/generate-windows-sys/src/main.rs" "/checkout/library/core/src/str/pattern.rs" "/checkout/library/core/src/str/error.rs" "/checkout/library/core/src/str/count.rs" "/checkout/library/core/src/str/traits.rs" "/checkout/library/core/src/str/mod.rs" "/checkout/library/core/src/str/iter.rs" "/checkout/library/core/src/str/lossy.rs" "/checkout/library/core/src/str/converts.rs" "/checkout/library/core/src/str/validations.rs" "/checkout/library/core/src/marker.rs" "/checkout/src/tools/remote-test-client/src/main.rs" "/checkout/library/core/src/mem/manually_drop.rs" "/checkout/library/core/src/mem/transmutability.rs" "/checkout/library/core/src/mem/mod.rs" "/checkout/library/core/src/mem/maybe_uninit.rs" "/checkout/library/core/src/lib.miri.rs" "/checkout/library/core/src/primitive_docs.rs" "/checkout/library/core/src/ub_checks.rs" "/checkout/library/core/src/lib.rs" "/checkout/library/core/src/option.rs" "/checkout/library/core/src/async_iter/mod.rs" "/checkout/library/core/src/async_iter/async_iter.rs" "/checkout/library/core/src/async_iter/from_iter.rs" "/checkout/src/tools/unicode-table-generator/src/main.rs" "/checkout/src/tools/unicode-table-generator/src/case_mapping.rs" "/checkout/src/tools/unicode-table-generator/src/raw_emitter.rs" "/checkout/src/tools/unicode-table-generator/src/unicode_download.rs" "/checkout/src/tools/unicode-table-g [...]

2024-08-15 19:12 UTC, compiler-errors requested changes

2024-08-15 19:12 UTC, compiler-errors commented on library/core/src/str/pattern.rs
> -        return false;
This is not correct, for the record.

2024-08-15 19:16 UTC, compiler-errors commented
Also fix CI (by formatting the code correctly), and it'd probably be best to test the changes first locally.

2024-08-15 20:00 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/10409679658/job/28829842382) [(plain)](https://github.com/rust-lang/rust/commit/76fac4df7c394b3ddc83500adab07551dda9848e/checks/28829842382/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#13 2.692 Building wheels for collected packages: reuse
#13 2.693   Building wheel for reuse (pyproject.toml): started
#13 2.942   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 2.943   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132715 sha256=dfa09868353292d98f811d3efdb0d54d07389e808efc71d68e3b93c514bf8bec
#13 2.943   Stored in directory: /tmp/pip-ephem-wheel-cache-hzdzkfk2/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#13 2.946 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#13 3.339 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#13 3.339 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 3.858 Collecting virtualenv
#13 3.858 Collecting virtualenv
#13 3.894   Downloading virtualenv-20.26.3-py3-none-any.whl (5.7 MB)
#13 3.976      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 71.7 MB/s eta 0:00:00
#13 4.016 Collecting distlib<1,>=0.3.7
#13 4.020   Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
#13 4.027      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 KB 93.9 MB/s eta 0:00:00
#13 4.055 Collecting platformdirs<5,>=3.9.1
#13 4.059   Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
#13 4.091 Collecting filelock<4,>=3.12.2
#13 4.095   Downloading filelock-3.15.4-py3-none-any.whl (16 kB)
#13 4.177 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 4.363 Successfully installed distlib-0.3.8 filelock-3.15.4 platformdirs-4.2.2 virtualenv-20.26.3
#13 DONE 4.4s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      186304 kB
DirectMap2M:     8202240 kB
DirectMap1G:    10485760 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.04s
##[endgroup]
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/d2b5aa6552c8acf67f38a2ad92062a32ec542f08/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/llvm-d2b5aa6552c8acf67f38a2ad92062a32ec542f08-true/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm
---
##[endgroup]
fmt check
Diff in /checkout/library/core/src/str/pattern.rs:1814:
             }
             mask &= !(1 << trailing);
-         false;
+        false;
     };
 
 
     let test_chunk = |idx| -> u16 {
fmt error: Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/library/core/src/iter/sources.rs" "/checkout/library/core/src/clone.rs" "/checkout/library/core/src/cmp.rs" "/checkout/src/tools/lld-wrapper/src/main.rs" "/checkout/library/core/src/panic/panic_info.rs" "/checkout/library/core/src/panic/unwind_safe.rs" "/checkout/library/core/src/panic/location.rs" "/checkout/library/core/src/any.rs" "/checkout/library/core/src/unicode/mod.rs" "/checkout/library/core/src/unicode/printable.rs" "/checkout/library/core/src/unicode/unicode_data.rs" "/checkout/src/tools/generate-copyright/src/main.rs" "/checkout/src/tools/generate-copyright/src/cargo_metadata.rs" "/checkout/library/core/src/fmt/float.rs" "/checkout/library/core/src/fmt/mod.rs" "/checkout/library/core/src/fmt/nofloat.rs" "/checkout/library/core/src/fmt/builders.rs" "/checkout/library/core/src/fmt/num.rs" "/checkout/library/core/src/fmt/rt.rs" "/checkout/library/core/src/cell.rs" "/checkout/library/core/src/range.rs" "/checkout/library/core/src/arch.rs" "/checkout/src/tools/replace-version-placeholder/src/main.rs" "/checkout/library/core/src/cmp/bytewise.rs" "/checkout/library/core/src/asserting.rs" "/checkout/library/core/src/tuple.rs" "/checkout/library/core/src/pat.rs" "/checkout/library/core/src/panic.rs" "/checkout/library/core/src/intrinsics/mir.rs" "/checkout/library/core/src/intrinsics/simd.rs" "/checkout/library/core/src/str/pattern.rs" "/checkout/library/core/src/str/error.rs" "/checkout/library/core/src/str/count.rs" "/checkout/library/core/src/str/traits.rs" "/checkout/library/core/src/str/mod.rs" "/checkout/library/core/src/str/iter.rs" "/checkout/library/core/src/str/lossy.rs" "/checkout/library/core/src/str/converts.rs" "/checkout/library/core/src/str/validations.rs" "/checkout/library/core/src/marker.rs" "/checkout/library/core/src/mem/manually_drop.rs" "/checkout/library/core/src/mem/transmutability.rs" "/checkout/library/core/src/mem/mod.rs" "/checkout/library/core/src/mem/maybe_uninit.rs" "/checkout/src/tools/compiletest/src/main.rs" "/checkout/library/core/src/lib.miri.rs" "/checkout/library/core/src/primitive_docs.rs" "/checkout/library/core/src/ub_checks.rs" "/checkout/library/core/src/lib.rs" "/checkout/library/core/src/option.rs" "/checkout/src/tools/compiletest/src/errors/tests.rs" "/checkout/src/tools/compiletest/src/errors.rs" "/checkout/src/tools/compiletest/src/command-list.rs" "/checkout/src/tools/compiletest/src/runtest.rs" "/checkout/library/core/src/async_iter/mod.rs" "/checkout/library/core/src/async_iter/async_iter.rs" "/checkout/library/core/src/async_iter/from_iter.rs" "/checkout/src/tools/compiletest/src/util/tests.rs" "/checkout/src/tools/compiletest/src/common.rs" "/checkout/library/core/src/convert/mod.rs" "/checkout/library/core/src/convert/num.rs" "/checkout/src/tools/compiletest/src/read2/tests.rs" "/checkout/library/core/src/prelude/mod.rs" "/checkout/library/core/src/iter/traits/unchecked_iterator.rs"` failed.
If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
  local time: Thu Aug 15 20:00:32 UTC 2024
  network time: Thu, 15 Aug 2024 20:00:32 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-08-15 20:04 UTC, workingjubilee commented
Have you read the contributing instructions? You seem to be manually fixing things that should be fixed via commands like `./x.py fmt`, and you mentioned "cargo", but cargo doesn't really work in this repo. Not in the usual way, anyways.

See https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html

2024-08-16 08:03 UTC, danik292 commented on library/core/src/str/pattern.rs
> -        return false;
Its now good?

2024-08-16 08:54 UTC, danik292 commented
@rustbot review

2024-08-16 09:23 UTC, joboet commented
Thank you! I'm surprised actually that rustc doesn't lint this...

@bors r+ rollup

2024-08-16 10:36 UTC, compiler-errors commented
@bors r-

Please squash this!

2024-08-16 10:38 UTC, compiler-errors commented
@joboet please make sure that changes like this are squashed in the future especially if they're cleanup prs like 7 lines long 😄

2024-08-16 17:05 UTC, danik292 commented
> @bors r-
> 
> Please squash this! You can use:
> 
> ```
> git reset HEAD~4
> git add library/
> git commit -m "commit message"
> ```

dont bors squash it automaticly?

2024-08-16 17:15 UTC, compiler-errors commented
Nope

2024-08-16 17:18 UTC, danik292 commented
If I try to do what you suggest It dont work.

2024-08-16 17:35 UTC, joboet commented
I mostly do
```sh
git rebase -i HEAD~4
```
and replace all `pick`s except the first one with `f` (fixup), which melds them into the previous commits.

2024-08-16 18:09 UTC, danik292 commented
what do you think by firs one?

The first or last one from chronological order?

2024-08-16 18:18 UTC, workingjubilee commented
> what do you think by firs one?
> 
> The first or last one from chronological order?

if you run `git rebase -i HEAD~4` then git will run whatever you have set as your `EDITOR` environment variable and you will see the list of commits.

It will show you something like this:
```
pick 76b195675ea Update the unstable book
pick 65a9090aa3b Exclude just `std` from rustc deps
pick 1c6bffff9df Keep rustc's std copy
```
This is roughly chronological order.

You will want to change it so that it looks like this:
```
pick 76b195675ea Update the unstable book
squash 65a9090aa3b Exclude just `std` from rustc deps
squash 1c6bffff9df Keep rustc's std copy
```

2024-08-16 18:23 UTC, workingjubilee commented
Anyway:
> If I try to do what you suggest It dont work.

You will probably need to provide, like, a *lot* more context than "it doesn't work".

2024-08-16 18:38 UTC, tgross35 commented
> You will want to change it so that it looks like this:
> 
> ```
> pick 76b195675ea Update the unstable book
> squash 65a9090aa3b Exclude just `std` from rustc deps
> squash 1c6bffff9df Keep rustc's std copy
> ```

(probably `f`/`fixup` rather than `s`/`squash` in this case, since the commits are just things like "fix test failures")

@danik292 just for reference, `s` appends the commit message to the previous commit's message, `f` just gets rid of the message. For things that fix up your own work, i.e. aren't relevant for the repo's history, use `f`.

2024-08-16 18:38 UTC, danik292 commented
I must add something that dont diserupt check-tidy and dont chenge code to code because git is rejecting my rebase because contained chenges is there.

sigh

Any idea what to do??

2024-08-16 18:41 UTC, tgross35 commented
> I must add something that dont diserupt check-tidy and dont chenge code to code because git is rejecting my rebase because contained chenges is there.
> 
> sigh
> 
> Any idea what to do??

Squashing shouldn't ever break tidy if it was already passing. Can you clarify what you are doing and what gets rejected? As in, actual commands / errors.

(you can also do `git rebase -i $(get merge-base master)` if you have pulled `master` again locally, for squashing without actually changing the base)

2024-08-16 18:58 UTC, workingjubilee commented
> I must add something that dont diserupt check-tidy and dont chenge code to code because git is rejecting my rebase because contained chenges is there.

do you mean when you `git push`?

because that's intentional.
we're asking you to `git push --force` the squashed 4-into-1 commits

2024-08-16 20:00 UTC, danik292 commented
git push --force
Username for 'https://github.com': danik292
Password for 'https://danik292@github.com': 
Running pre-push script /home/daniel/rust/x test tidy
Building bootstrap
    Finished `dev` profile [unoptimized] target(s) in 0.04s
Building stage0 tool tidy (x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized] target(s) in 0.14s
fmt check
fmt warning: Something went wrong running git commands:
fmt warning: rust-lang/rust remote not found
fmt warning: Falling back to formatting all files.
fmt: checked 5485 modified files
tidy check
x.py completions check
Build completed successfully in 0:00:05
Everything up-to-date






this is output of git push --force

2024-08-16 20:01 UTC, danik292 commented
I will close it as chenges dont worth stressing.

2024-08-16 20:01 UTC, closed without merging

2024-08-16 20:56 UTC, tgross35 commented
Try pushing with `--no-verify` to skip local tidy and let CI handle it (you need to reopen before you push, otherwise GitHub complains)