Add platform docs for FreeBSD.
rust-lang/rust pull request #129220
Opened 2024-08-17 23:38 UTC by asomers

2024-08-17 23:39 UTC, asomers commented
cc @tgross35 .  Also, perhaps @MikaelUrankar would like to sign up as a second target maintainer?

2024-08-18 00:27 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/10436040465/job/28900615492) [(plain)](https://github.com/rust-lang/rust/commit/2d5ddb620f4c21d9312d6aea84da54234b3ecf01/checks/28900615492/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
------
 > importing cache manifest from ghcr.io/rust-lang/rust-ci-cache:20d3b4d4a2629cbf7865cdbf92fe47512a7c96658c24253a045ff38e8075cd7fb37ca6fcadfa6e6d093333943ad24f6fc4f163ec5b74fd940de9d5bb03eb4d3b:
------
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
  Downloaded boml v0.3.1
   Compiling boml v0.3.1
   Compiling y v0.1.0 (/checkout/compiler/rustc_codegen_gcc/build_system)
    Finished `release` profile [optimized] target(s) in 3.70s
     Running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-codegen/x86_64-unknown-linux-gnu/release/y test --use-system-gcc --use-backend gcc --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc --release --mini-tests --std-tests`
Using system GCC
[BUILD] example
[AOT] mini_core_hello_world
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc/mini_core_hello_world
abc
---
##[group]Building stage0 tool linkchecker (x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized] target(s) in 0.13s
##[endgroup]
##[group]Testing stage0 Linkcheck (x86_64-unknown-linux-gnu)
rustc/platform-support.html:263: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:323: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:402: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:420: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:426: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:483: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:484: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:485: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9610: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9670: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9749: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9767: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9773: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9830: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9831: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9832: broken link - `rustc/platform-support/freebsd.html`
number of HTML files scanned: 43614
number of HTML redirects found: 13713
number of links checked: 3202748
number of links ignored due to external: 78509
number of links ignored due to external: 78509
number of links ignored due to exceptions: 17
number of intra doc links ignored: 8
errors found: 16
found some broken links
Command has failed. Rerun with -v to see more details.
  local time: Sun Aug 18 00:27:17 UTC 2024
  network time: Sun, 18 Aug 2024 00:27:17 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-08-18 00:33 UTC, ehuss commented
r? ehuss

Looks like we have two PRs updating the same thing over at #128546.

Can we combine them? Or I can merge #128546 now, until this is ready?

2024-08-18 01:28 UTC, workingjubilee requested changes
In the platform support docs, please note that [FreeBSD's ports patches i686-unknown-freebsd](https://github.com/freebsd/freebsd-ports/blob/a35c8865a6883be6ecdcec286b7c2a620f69d3e6/lang/rust/files/patch-compiler_rustc__target_src_spec_targets_i686__unknown__freebsd.rs) in a way that [introduces incorrect compilations](https://github.com/rust-lang/rust/issues/114479), thus people must use the upstream toolchain instead of a FreeBSD-built toolchain for building for i686-unknown-freebsd without introducing incorrect compilations.

Unless this changes, of course.

2024-08-18 12:11 UTC, MikaelUrankar commented
> cc @tgross35 . Also, perhaps @MikaelUrankar would like to sign up as a second target maintainer?

Yes, you can put me as a 2nd target maintainer.

2024-08-20 23:13 UTC, asomers commented
@workingjubilee @beetrees the decision to build lang/rust without SSE support was made in 2017, before any of the linked LLVM issues.  I'll start a discussion about revisiting it.  I'll inquire about the ELFv1/ELFv2 issue too.

2024-08-21 00:01 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/10480549229/job/29028411134) [(plain)](https://github.com/rust-lang/rust/commit/f73c7bed5a9bfaefa221890a73a321c69b861249/checks/29028411134/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
------
 > importing cache manifest from ghcr.io/rust-lang/rust-ci-cache:20d3b4d4a2629cbf7865cdbf92fe47512a7c96658c24253a045ff38e8075cd7fb37ca6fcadfa6e6d093333943ad24f6fc4f163ec5b74fd940de9d5bb03eb4d3b:
------
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.thin-lto-import-instr-limit := 10
configure: change-id            := 99999999
---
  Downloaded boml v0.3.1
   Compiling boml v0.3.1
   Compiling y v0.1.0 (/checkout/compiler/rustc_codegen_gcc/build_system)
    Finished `release` profile [optimized] target(s) in 3.83s
     Running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-codegen/x86_64-unknown-linux-gnu/release/y test --use-system-gcc --use-backend gcc --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc --release --mini-tests --std-tests`
Using system GCC
[BUILD] example
[AOT] mini_core_hello_world
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc/mini_core_hello_world
abc
---
##[group]Building stage0 tool linkchecker (x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized] target(s) in 0.13s
##[endgroup]
##[group]Testing stage0 Linkcheck (x86_64-unknown-linux-gnu)
rustc/platform-support.html:263: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:324: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:403: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:421: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:427: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:484: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:485: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:486: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9606: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9667: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9746: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9764: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9770: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9827: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9828: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9829: broken link - `rustc/platform-support/freebsd.html`
number of HTML files scanned: 43611
number of HTML redirects found: 13713
number of links checked: 3198524
number of links ignored due to external: 78499
number of links ignored due to external: 78499
number of links ignored due to exceptions: 17
number of intra doc links ignored: 8
errors found: 16
found some broken links
Command has failed. Rerun with -v to see more details.
  local time: Wed Aug 21 00:01:01 UTC 2024
  network time: Wed, 21 Aug 2024 00:01:01 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-08-23 02:28 UTC, workingjubilee commented
> Ideally (since FreeBSD wants to support pre-SSE2 CPUs)

I am not entirely sure they do? I have been informed contrariwise, i.e. that FreeBSD is only interested in Pentium 4 or later equivalents. Naturally, _that_ might have been decided many years after the 2017 decision!

Of course, if two targets settles the matter for FreeBSD, that is fine by me, and if a documentation change is preferred, that is also fine by me. I do not mean to be obstructive, I merely want the matter to be clear for everyone involved.

2024-10-20 03:20 UTC, emaste commented on src/doc/rustc/src/platform-support/freebsd.md
> +The Rust test suite can be run natively. It can also be run from the ports tree
maybe "the FreeBSD ports tree"

2024-10-21 14:49 UTC, ehuss commented
Just FYI, you'll need to add the link to SUMMARY.md. Also, I'd suggest fixing the target definitions in 
`compiler/rustc_target/src/spec/targets` if those are indeed incorrect. See #128546 for examples of these changes.

2024-10-21 21:14 UTC, workingjubilee commented
@ehuss I would rather not deliberately introduce miscompilations into existing tier 2 targets that currently have none, whether or not `ports` has decided to make their target unsound.

2024-10-21 22:12 UTC, ehuss commented
@workingjubilee Sorry, I'm not following. Are you asking that the change [requested above](https://github.com/rust-lang/rust/pull/129220#pullrequestreview-2244183862) be resolved? I'm not the author, so I wouldn't be the one making that change. As the reviewer, I won't merge until it is resolved.

Or maybe you intended to tag one of the other commenters here? Sorry, I'm confused. 😕

2024-10-21 22:21 UTC, workingjubilee commented
@ehuss I am saying that the resolution can include `ports` fixing its target definition to not make Rust code unsound.

2024-10-21 22:50 UTC, asomers commented
A change is underway to reenable SSE on i386 by default: https://reviews.freebsd.org/D47227

2024-10-23 17:53 UTC, ehuss commented
@rustbot author

2024-11-07 17:06 UTC, Dylan-DPC commented
@asomers any updates on this? thanks

2024-11-08 15:07 UTC, asomers commented
> @asomers any updates on this? thanks

I expect to merge that change, reenabling SSE2 on i386, but EoD on Saturday.

2024-12-09 00:02 UTC, tgross35 commented
Is the SSE note accurate since the push 3 weeks ago?

If not, I think it would be okay to drop that section for now and merge the rest of the docs so we at least have something.

2024-12-09 01:05 UTC, asomers commented
> Is the SSE note accurate since the push 3 weeks ago?
> 
> If not, I think it would be okay to drop that section for now and merge the rest of the docs so we at least have something.

Yes, the SSE note is accurate.  I committed that change on 9-Nov.  https://reviews.freebsd.org/R11:b039f2e46b15c1ff5cbaf41e642993d982294da3

2024-12-09 01:54 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12227049807/job/34103225748) [(plain)](https://github.com/rust-lang/rust/commit/fe6356f9fa10e14ae110fd45df23500c1c4d5d21/checks/34103225748/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#17 exporting to docker image format
#17 sending tarball 28.8s done
#17 DONE 34.2s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
  Downloaded boml v0.3.1
   Compiling boml v0.3.1
   Compiling y v0.1.0 (/checkout/compiler/rustc_codegen_gcc/build_system)
    Finished `release` profile [optimized] target(s) in 4.01s
     Running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-codegen/x86_64-unknown-linux-gnu/release/y test --use-system-gcc --use-backend gcc --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc --release --mini-tests --std-tests`
Using system GCC
[BUILD] example
[AOT] mini_core_hello_world
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc/mini_core_hello_world
abc
---
##[group]Building stage0 tool linkchecker (x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized] target(s) in 0.14s
##[endgroup]
##[group]Testing stage0 Linkcheck (x86_64-unknown-linux-gnu)
rustc/platform-support.html:242: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:302: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:383: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:402: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:409: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:468: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:469: broken link - `rustc/platform-support/freebsd.html`
rustc/platform-support.html:470: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9901: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:9961: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:10042: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:10061: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:10068: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:10127: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:10128: broken link - `rustc/platform-support/freebsd.html`
rustc/print.html:10129: broken link - `rustc/platform-support/freebsd.html`
number of HTML files scanned: 44028
number of HTML redirects found: 13779
number of links checked: 2646328
number of links ignored due to external: 84031
number of links ignored due to external: 84031
number of links ignored due to exceptions: 17
number of intra doc links ignored: 8
errors found: 16
found some broken links
NOTE: if you are adding or renaming a markdown file in a mdBook, don't forget to register the page in SUMMARY.md
Command has failed. Rerun with -v to see more details.
  local time: Mon Dec  9 01:54:27 UTC 2024
  network time: Mon, 09 Dec 2024 01:54:27 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-12-12 06:01 UTC, tgross35 approved these changes
This needs an entry in SUMMARY.md and a squash, but with https://github.com/freebsd/freebsd-ports/commit/b039f2e46b15c1ff5cbaf41e642993d982294da3 I don't think there is anything that this would be waiting on.

2024-12-22 20:03 UTC, tgross35 commented
@asomers could you rebase and squash? I'll merge this, if any small changes are needed they can come as a followup.

2024-12-22 20:57 UTC, asomers commented
> @asomers could you rebase and squash? I'll merge this, if any small changes are needed they can come as a followup.

done

2024-12-22 21:24 UTC, tgross35 commented
@bors r+ rollup

2024-12-23 12:17 UTC, merged