Add a missing compatibility note in the 1.80.0 release notes
rust-lang/rust pull request #129263
Opened 2024-08-19 10:45 UTC by apiraino

#99969 missed being included in the release notes. As discussed [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/.2399969.20missed.20the.20release.20notes/near/463002451).

(the discussion about the _a posteriori_ breakage the ecosystem is experiencing is another topic)

Thanks

r? @rust-lang/release

2024-08-19 13:51 UTC, workingjubilee commented on RELEASES.md
> +- [alloc: implement FromIterator for Box<str>](https://github.com/rust-lang/rust/pull/99969/)
0.3.36

2024-08-19 13:52 UTC, workingjubilee requested changes

2024-08-19 13:52 UTC, workingjubilee commented on RELEASES.md
> +  Notably this breaks versions of the `time` crate before 0.3.55, due to no longer inferring the right impl.
```suggestion
  Notably this breaks versions of the `time` crate before 0.3.36, due to no longer inferring the right impl.
```

2024-08-20 06:06 UTC, workingjubilee approved these changes

2024-08-22 00:33 UTC, estebank commented
CC https://github.com/rust-lang/rust/issues/127343.

2024-08-22 01:30 UTC, cuviper commented on RELEASES.md
> +  Notably this breaks versions of the `time` crate before 0.3.36, due to no longer inferring the right impl.
Further tweaks, and also 0.3.35 has the fix.

```suggestion
- [Type inference will fail in some cases due to new implementations of `FromIterator for Box<str>`.](https://github.com/rust-lang/rust/pull/99969/)
  Notably, this breaks versions of the `time` crate before 0.3.35, due to no longer inferring the implementation for `Box<[_]>`.
```

2024-08-22 16:45 UTC, cuviper commented
@bors r+ rollup

2024-08-23 13:23 UTC, merged