Implement ACP 429: add `LazyCell/Lock::get[_mut]()`, `DerefMut` and `force_mut()`
rust-lang/rust pull request #129334
Opened 2024-08-20 21:11 UTC by ChayimFriedman2

In the implementation of `force_mut()`, I choose performance over safety. For `LazyLock` this isn't really a choice; the code has to be unsafe. But for `LazyCell`, we can have a full-safe implementation, but it will be a bit less performant, so I went with the unsafe approach.

`DerefMut` is instantly stable, as a trait impl; as such, I decided to also instantly stabilize `force_mut()`, since it makes little sense to have one but not the other. That means this needs an FCP.

@rustbot label +needs-fcp

2024-08-20 21:22 UTC, ChayimFriedman2 commented
r​? libs-api

2024-08-21 13:02 UTC, joboet commented
Weird, rustbot seems to be sleeping...
r? libs-api

2024-08-23 15:32 UTC, joboet approved these changes
The implementation looks good to me, r=me with the nit resolved after the FCP completes.

2024-08-23 15:32 UTC, joboet commented on library/std/src/sys/sync/once/queue.rs
> +            });
The `with_addr` confused me, there is no reason to carry over the provenance.
```suggestion
        *self.state_and_queue.get_mut() = match new_state {
            ExclusiveState::Incomplete => ptr::without_provenance_mut(INCOMPLETE),
            ExclusiveState::Poisoned => ptr::without_provenance_mut(POISONED),
            ExclusiveState::Complete => ptr::without_provenance_mut(COMPLETE),
        };
```

2024-09-11 08:57 UTC, SteveLauC commented
Gentle ping on this PR, would love this to be merged soon:)

2024-09-11 10:21 UTC, ChayimFriedman2 commented
@SteveLauC This depends on a T-libs-api member starting a FCP.

2024-09-14 18:13 UTC, BurntSushi requested changes
New APIs need to land as unstable. And an FCP isn't needed for that. There should also be a tracking issue. And the ACP should be linked.

2024-09-14 19:00 UTC, ChayimFriedman2 commented
@BurntSushi @scottmcm This PR needs FCP for `DerefMut` and `force_mut()`, which, as I said in the OP, I decided to make instantly stable because it makes little sense to separate it from `DerefMut`.

For `get_mut()`, I already opened a tracking issue: https://github.com/rust-lang/rust/issues/129333. I can split the PR though.

2024-09-14 20:54 UTC, workingjubilee commented
> DerefMut is instantly stable, as a trait impl; as such, I decided to also instantly stabilize `force_mut()`, since it makes little sense to have one but not the other. That means this needs an FCP.

so you're saying we could land `force_mut()` on nightly as unstable and then decide to stabilize `DerefMut` with it?

2024-09-14 21:05 UTC, ChayimFriedman2 commented
> > DerefMut is instantly stable, as a trait impl; as such, I decided to also instantly stabilize `force_mut()`, since it makes little sense to have one but not the other. That means this needs an FCP.
> 
> so you're saying we could land `force_mut()` on nightly as unstable and then decide to stabilize `DerefMut` with it?

That's an option, but that's not what I'm doing in this PR. Instead, I instantly stabilize both.

2024-11-16 20:25 UTC, ChayimFriedman2 commented
@rustbot ready

I modified this to only add (immediately stable) `DerefMut`, after the other methods has been added unstably in #130476. This is now ready for FCP.

Although, libs-api may not want to include this until `force_mut()` stabilizes, or people may resort to this as a workaround (although I expect `DerefMut` to be used more often anyway, just like `Deref` vs. `force()`).

2025-01-28 13:45 UTC, Maurdekye commented
Any updates on this? Would love a `DerefMut` implementation to be merged into nightly.

2025-04-27 01:13 UTC, tgross35 commented
Getting this old request on the radar:

@rustbot label +I-libs-api-nominated

If this is accepted then it likely makes sense to stabilize `force_mut` at the same time, since `DerefMut` exposes that behavior (above discussion is outdated, this method now exists as unstable).

```rust
impl<T, F: FnOnce() -> T> DerefMut for LazyCell<T, F> { /* ... */ }
impl<T, F: FnOnce() -> T> DerefMut for LazyLock<T, F> { /* ... */ }

impl<T, F> core::cell::LazyCell<T, F> {
    pub fn force_mut(this: &mut Self) -> &mut T;
}
impl<T, F> std::sync::LazyLock<T, F> {
    pub fn force_mut(this: &mut Self) -> &mut T;
}
```

`force_mut`'s tracking issue at https://github.com/rust-lang/rust/issues/129333 has a couple of other methods.

2025-04-29 15:16 UTC, Amanieu commented
FCP to stabilize DerefMut directly. `force_mut` remains unstable tracked under #129333.

@rfcbot merge

2025-05-09 22:34 UTC, Amanieu commented
@bors r+

2025-05-10 20:40 UTC, merged