Partially initialize `feature(new_uninit)`
rust-lang/rust pull request #129401
Opened 2024-08-22 06:56 UTC by workingjubilee

Finished comment period: https://github.com/rust-lang/rust/issues/63291#issuecomment-2183022955

The following API has been stabilized from https://github.com/rust-lang/rust/issues/63291

```rust
impl<T> Box<T> { pub fn new_uninit() -> Box<MaybeUninit<T>> {…} }
impl<T> Box<MaybeUninit<T>> { pub unsafe fn assume_init(self) -> Box<T> {…} }
impl<T> Box<[T]> { pub fn new_uninit_slice(len: usize) -> Box<[MaybeUninit<T>]> {…} }
impl<T> Box<[MaybeUninit<T>]> { pub unsafe fn assume_init(self) -> Box<[T]> {…} }

impl<T> Rc<T> { pub fn new_uninit() -> Rc<MaybeUninit<T>> {…} }
impl<T> Rc<MaybeUninit<T>> { pub unsafe fn assume_init(self) -> Rc<T> {…} }
impl<T> Rc<[T]> { pub fn new_uninit_slice(len: usize) -> Rc<[MaybeUninit<T>]> {…} }
impl<T> Rc<[MaybeUninit<T>]> { pub unsafe fn assume_init(self) -> Rc<[T]> {…} }

impl<T> Arc<T> { pub fn new_uninit() -> Arc<MaybeUninit<T>> {…} }
impl<T> Arc<MaybeUninit<T>> { pub unsafe fn assume_init(self) -> Arc<T> {…} }
impl<T> Arc<[T]> { pub fn new_uninit_slice(len: usize) -> Arc<[MaybeUninit<T>]> {…} }
impl<T> Arc<[MaybeUninit<T>]> { pub unsafe fn assume_init(self) -> Arc<[T]> {…} }
```

The remaining API is split between new issues
- `new_zeroed_alloc`: https://github.com/rust-lang/rust/issues/129396
- `box_uninit_write`: https://github.com/rust-lang/rust/issues/129397

All relevant code is thus either stabilized or split out of that issue, so this closes #63291 as, with the FCP concluded, that issue has served its purpose.

2024-08-22 07:46 UTC, workingjubilee commented
This goes into the relnotes because:
- ...it's new API.

2024-08-22 13:09 UTC, joboet commented
@rust-lang/libs-api I have a question before I merge this: Is there a reason these functions aren't named `uninit`/`uninit_slice`? I find that to be just as clear and a bit more concise, and `MaybeUninit::uninit` isn't called `new_uninit` either.

2024-08-22 14:57 UTC, dtolnay requested changes

2024-08-22 14:57 UTC, dtolnay commented on library/alloc/src/boxed.rs
> +    /// As with [`MaybeUninit::assume_init`],uninit_alloc_w
```suggestion
    /// As with [`MaybeUninit::assume_init`],
```

2024-08-26 04:54 UTC, workingjubilee commented
@bors try

2024-08-27 15:32 UTC, dtolnay approved these changes

2024-08-27 15:32 UTC, dtolnay commented
@bors r+

2024-08-27 17:11 UTC, workingjubilee commented
I need to bless the Miri tests, I guess...?

2024-08-27 17:17 UTC, workingjubilee commented
Oh, no, new tests that use this feature, I see.

2024-08-27 17:20 UTC, workingjubilee commented
@bors r=dtolnay,joboet

2024-08-29 05:08 UTC, merged

2024-09-24 16:45 UTC, RalfJung commented
@rust-lang/release shouldn't there be a relnotes tracking issue for this? I can't find one.

2024-09-24 17:09 UTC, workingjubilee commented
Fixed.