Stabilize `Pin::as_deref_mut()`
rust-lang/rust pull request #129424
Opened 2024-08-22 19:53 UTC by coolreader18

Tracking issue: 86918

I know that an FCP has not been started yet, but this isn't a very complex stabilization, and I'm hoping this can motivate an FCP to *get* started - this has been pending for a while and it's a very useful function when writing Future impls.

I've moved the function def into the same impl block as `Pin::as_mut` as suggested in https://github.com/rust-lang/rust/issues/86918#issuecomment-2189367582, though that seems to assume that `Pin::as_ref` and `Pin::as_mut` are in the same block, which isn't actually the case - though regardless, just moving it in with `as_mut` accomplishes the same goals.

r? @jonhoo

2024-08-22 19:53 UTC, coolreader18 commented
r? @dtolnay

2024-08-22 21:17 UTC, dtolnay requested changes
Thanks for the PR!

I think doing the signature change plus stabilization in the same PR may be too hasty in this case. We do that in other cases that are known to be inconsequential, like tweaking the name of a method, but it's not clear to me this is one of those. I would prefer if the new signature could be landed independently before proposing a stabilization.

2024-08-23 05:02 UTC, coolreader18 commented
Makes sense. I'll close this for now, and reopen once the signature has been resolved.

2024-10-08 19:55 UTC, coolreader18 commented
ping @dtolnay? FCP merged

2024-10-08 21:14 UTC, dtolnay approved these changes
Thanks!

2024-10-08 21:15 UTC, dtolnay commented
@bors r+

2024-10-09 11:06 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/11252736881/job/31286544298) [(plain)](https://github.com/rust-lang-ci/rust/commit/8a116954710980c1a86d92d8120e71c55c0622ca/checks/31286544298/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
##[group]Building stage1 library artifacts (x86_64-unknown-linux-gnu)
##[endgroup]
##[group]Building tool rustdoc (stage0 -> stage1, x86_64-unknown-linux-gnu)
##[endgroup]
thread 'core::builder::tests::ci_rustc_if_unchanged_logic' panicked at src/core/builder/tests.rs:260:5:
assertion failed: has_changes == config.download_rustc_commit.is_none()
   0: rust_begin_unwind
             at /rustc/8c27a2ba6b21f3406a51118643080f0591949827/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/8c27a2ba6b21f3406a51118643080f0591949827/library/core/src/panicking.rs:74:14
```

</details>

2024-10-09 11:07 UTC, dtolnay commented
@bors retry

2024-10-09 12:19 UTC, rust-log-analyzer commented
A job failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/11254682656/job/31292658875) [(plain)](https://github.com/rust-lang-ci/rust/commit/0031040f3312a2765dd9dbec763664ef27220747/checks/31292658875/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

```

</details>

2024-10-13 05:07 UTC, coolreader18 commented
@bors retry

2024-10-13 05:07 UTC, coolreader18 commented
fair enough

2024-10-14 07:02 UTC, dtolnay commented
@bors retry

2024-10-14 19:24 UTC, merged