Add new_cyclic_in for Rc and Arc
rust-lang/rust pull request #129674
Opened 2024-08-28 01:10 UTC by matthewpipie

WIP; will update once more features exist.

TODO:
* document new_cyclic_in for Rc
* figure out how to not have insane copy-paste between new_cyclic and new_cyclic_in
* fix formatting
* do it all for Arc too

2024-08-28 01:10 UTC, matthewpipie commented
@rustbot author
for now, need to do a bit more before someone looks at it

2024-08-28 01:16 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/10588373997/job/29340786168) [(plain)](https://github.com/rust-lang/rust/commit/13e36cf8870a88ab0ac5651d9513b13085baa8cc/checks/29340786168/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#13 2.737 Building wheels for collected packages: reuse
#13 2.738   Building wheel for reuse (pyproject.toml): started
#13 2.989   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 2.990   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132715 sha256=dfa09868353292d98f811d3efdb0d54d07389e808efc71d68e3b93c514bf8bec
#13 2.990   Stored in directory: /tmp/pip-ephem-wheel-cache-ps2byme7/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#13 2.993 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#13 3.394 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#13 3.394 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 3.931 Collecting virtualenv
#13 3.931 Collecting virtualenv
#13 3.971   Downloading virtualenv-20.26.3-py3-none-any.whl (5.7 MB)
#13 4.044      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 80.7 MB/s eta 0:00:00
#13 4.084 Collecting distlib<1,>=0.3.7
#13 4.089   Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
#13 4.098      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 KB 70.4 MB/s eta 0:00:00
#13 4.129 Collecting platformdirs<5,>=3.9.1
#13 4.133   Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
#13 4.168 Collecting filelock<4,>=3.12.2
#13 4.172   Downloading filelock-3.15.4-py3-none-any.whl (16 kB)
#13 4.256 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 4.443 Successfully installed distlib-0.3.8 filelock-3.15.4 platformdirs-4.2.2 virtualenv-20.26.3
#13 DONE 4.5s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      204736 kB
DirectMap2M:     6086656 kB
DirectMap1G:    12582912 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.04s
##[endgroup]
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/1f12b9b0fdbe735968ac002792a720f0ba4faca6/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/llvm-1f12b9b0fdbe735968ac002792a720f0ba4faca6-true/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm
---
##[endgroup]
fmt check
Diff in /checkout/library/alloc/src/rc.rs:1710:
     #[inline]
     #[stable(feature = "rc_unique", since = "1.4.0")]
     pub fn get_mut(this: &mut Self) -> Option<&mut T> {
-        if Rc::is_unique(this) {
-            unsafe { Some(Rc::get_mut_unchecked(this)) }
-            None
-        }
-        }
+        if Rc::is_unique(this) { unsafe { Some(Rc::get_mut_unchecked(this)) } } else { None }
 
     /// Returns a mutable reference into the given `Rc`,
Diff in /checkout/library/alloc/src/rc.rs:3291:
     #[must_use]
     #[must_use]
     #[stable(feature = "weak_counts", since = "1.41.0")]
     pub fn strong_count(&self) -> usize {
-        if let Some(inner) = self.inner() {
-            inner.strong()
-        } else {
-            0
-        }
+        if let Some(inner) = self.inner() { inner.strong() } else { 0 }
 
 
     /// Gets the number of `Weak` pointers pointing to this allocation.
fmt error: Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/src/librustdoc/clean/render_macro_matchers.rs" "/checkout/src/librustdoc/clean/utils.rs" "/checkout/src/librustdoc/clean/utils/tests.rs" "/checkout/src/librustdoc/clean/blanket_impl.rs" "/checkout/src/librustdoc/clean/mod.rs" "/checkout/src/librustdoc/clean/types.rs" "/checkout/src/librustdoc/clean/auto_trait.rs" "/checkout/src/librustdoc/clean/simplify.rs" "/checkout/src/librustdoc/clean/inline.rs" "/checkout/src/librustdoc/clean/cfg/tests.rs" "/checkout/src/librustdoc/clean/types/tests.rs" "/checkout/src/librustdoc/clean/cfg.rs" "/checkout/src/librustdoc/scrape_examples.rs" "/checkout/library/alloc/src/macros.rs" "/checkout/library/alloc/src/alloc/tests.rs" "/checkout/library/alloc/src/sync/tests.rs" "/checkout/library/alloc/src/slice/tests.rs" "/checkout/library/alloc/src/rc.rs" "/checkout/src/librustdoc/html/length_limit.rs" "/checkout/src/librustdoc/html/toc.rs" "/checkout/src/librustdoc/html/highlight.rs" "/checkout/src/librustdoc/html/layout.rs" "/checkout/src/librustdoc/html/length_limit/tests.rs" "/checkout/src/librustdoc/html/toc/tests.rs" "/checkout/src/librustdoc/html/mod.rs" "/checkout/library/alloc/src/vec/spec_from_iter.rs" "/checkout/library/alloc/src/vec/splice.rs" "/checkout/library/alloc/src/vec/in_place_collect.rs" "/checkout/library/alloc/src/vec/mod.rs" "/checkout/library/alloc/src/vec/partial_eq.rs" "/checkout/library/alloc/src/vec/extract_if.rs" "/checkout/library/alloc/src/vec/set_len_on_drop.rs" "/checkout/library/alloc/src/vec/spec_extend.rs" "/checkout/library/alloc/src/vec/in_place_drop.rs" "/checkout/library/alloc/src/vec/drain.rs" "/checkout/library/alloc/src/vec/cow.rs" "/checkout/library/alloc/src/vec/is_zero.rs" "/checkout/library/alloc/src/vec/spec_from_iter_nested.rs" "/checkout/library/alloc/src/vec/into_iter.rs" "/checkout/library/alloc/src/vec/spec_from_elem.rs" "/checkout/library/alloc/src/raw_vec.rs" "/checkout/library/alloc/src/sync.rs" "/checkout/library/alloc/src/lib.miri.rs" "/checkout/library/alloc/src/lib.rs" "/checkout/library/alloc/src/alloc.rs" "/checkout/library/alloc/src/boxed.rs" "/checkout/src/librustdoc/html/escape/tests.rs" "/checkout/src/librustdoc/html/url_parts_builder/tests.rs" "/checkout/src/librustdoc/html/markdown.rs" "/checkout/src/librustdoc/html/markdown/tests.rs" "/checkout/src/librustdoc/html/static_files.rs" "/checkout/src/librustdoc/html/highlight/fixtures/sample.rs" "/checkout/src/librustdoc/html/highlight/fixtures/union.rs" "/checkout/src/librustdoc/html/highlight/tests.rs" "/checkout/src/librustdoc/html/url_parts_builder.rs" "/checkout/library/alloc/src/collections/btree/fix.rs" "/checkout/library/alloc/src/collections/btree/set/tests.rs" "/checkout/library/alloc/src/collections/btree/map.rs" "/checkout/library/alloc/src/collections/btree/set.rs" "/checkout/library/alloc/src/collections/btree/mod.rs" "/checkout/library/alloc/src/collections/btree/node/tests.rs" "/checkout/library/alloc/src/collections/btree/set_val.rs" "/checkout/library/alloc/src/collections/btree/append.rs" "/checkout/library/alloc/benches/binary_heap.rs"` failed.
If you're running `tidy`, try again with `--bless`.  [...]

2024-09-05 03:55 UTC, matthewpipie commented
@rustbot review

2024-09-06 08:53 UTC, zakarumych commented
> * Is requiring Allocator to be Clone OK?

You can avoid `Clone` bound here. As you can destructure `Weak` and take it out.

2024-09-06 08:55 UTC, zakarumych commented
Maybe change `new_cyclic` to use `new_cyclic_in`?

2024-09-06 21:28 UTC, matthewpipie commented
> > * Is requiring Allocator to be Clone OK?
> 
> You can avoid `Clone` bound here. As you can destructure `Weak` and take it out. `Clone` is not supertrait of `Allocator`, so I would prefer not having this bound unless you have to clone.

Thank you! Fixed this in the latest commit. Destructuring the weak was a fantastic idea.


> Maybe change `new_cyclic` to use `new_cyclic_in`?

Is it then possible to turn the returned Arc<T, Global> into a regular Arc<T>?

2024-09-13 01:40 UTC, workingjubilee commented
r? libs-api

2024-09-14 18:42 UTC, dtolnay approved these changes
Thank you!

If you care about having these commits credited to your GitHub account in https://github.com/rust-lang/rust/graphs/contributors, you'll need to add your school email to https://github.com/settings/emails.

2024-09-14 18:43 UTC, dtolnay commented
@bors r+

2024-09-14 18:46 UTC, dtolnay commented
@bors r-

2024-09-14 18:46 UTC, dtolnay requested changes

2024-09-14 18:46 UTC, dtolnay commented on library/alloc/src/sync.rs
> +    #[stable(feature = "arc_new_cyclic", since = "1.60.0")]
This cannot be stabilized right away.

```suggestion
    #[unstable(feature = "allocator_api", issue = "32838")]
```

2024-09-17 01:05 UTC, matthewpipie commented on library/alloc/src/sync.rs
> +    #[stable(feature = "arc_new_cyclic", since = "1.60.0")]
great catch!

2024-09-17 01:21 UTC, dtolnay approved these changes

2024-09-17 01:21 UTC, dtolnay commented
@bors r+

2024-09-17 16:47 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-stable`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/10905877530/job/30265840491) [(plain)](https://github.com/rust-lang-ci/rust/commit/24f9f92ef0e2be04b43c77f20c1c4665d5962f57/checks/30265840491/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
[RUSTC-TIMING] proc_macro_test test:false 0.051
[RUSTC-TIMING] syntax test:false 21.838
[RUSTC-TIMING] proc_macro_api test:false 7.444
[RUSTC-TIMING] intern test:false 30.926
rustc: /checkout/src/llvm-project/llvm/include/llvm/ADT/DenseMap.h:667: bool llvm::DenseMapBase<llvm::DenseMap<unsigned int, unsigned int>, unsigned int, unsigned int, llvm::DenseMapInfo<unsigned int>, llvm::detail::DenseMapPair<unsigned int, unsigned int>>::LookupBucketFor(const LookupKeyT &, const BucketT *&) const [DerivedT = llvm::DenseMap<unsigned int, unsigned int>, KeyT = unsigned int, ValueT = unsigned int, KeyInfoT = llvm::DenseMapInfo<unsigned int>, BucketT = llvm::detail::DenseMapPair<unsigned int, unsigned int>, LookupKeyT = unsigned int]: Assertion `!KeyInfoT::isEqual(Val, EmptyKey) && !KeyInfoT::isEqual(Val, TombstoneKey) && "Empty/Tombstone value shouldn't be inserted into map!"' failed.
[RUSTC-TIMING] proc_macro_srv test:true 4.958
rustc exited with signal: 6 (SIGABRT) (core dumped)
error: could not compile `proc-macro-srv` (lib test)
Caused by:
Caused by:
  process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc /checkout/obj/build/bootstrap/debug/rustc --crate-name proc_macro_srv --edition=2021 crates/proc-macro-srv/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no '--warn=clippy::suspicious' '--warn=clippy::style' '--allow=clippy::restriction' '--deny=clippy::perf' '--deny=clippy::correctness' '--warn=clippy::complexity' '--allow=clippy::wrong_self_convention' '--allow=clippy::useless_asref' --warn=unused_lifetimes --warn=unused_extern_crates --warn=unsafe_op_in_unsafe_fn --warn=unreachable_pub '--allow=clippy::type_complexity' '--allow=clippy::too_many_arguments' '--warn=clippy::todo' '--warn=clippy::str_to_string' '--allow=clippy::single_match' '--allow=clippy::result_unit_err' '--warn=clippy::rc_buffer' '--warn=clippy::print_stdout' '--warn=clippy::print_stderr' '--allow=clippy::new_ret_no_self' '--allow=clippy::len_without_is_empty' --warn=explicit_outlives_requirements '--allow=clippy::enum_variant_names' --warn=elided_lifetimes_in_paths '--warn=clippy::dbg_macro' '--allow=clippy::assigning_clones' -C debug-assertions=on --test --cfg 'feature="in-rust-tree"' --cfg 'feature="sysroot-abi"' --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values("in-rust-tree", "sysroot-abi"))' -C metadata=17ac3bc260b4fcb2 -C extra-filename=-17ac3bc260b4fcb2 --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps --extern base_db=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libbase_db-c74df67c7fe4e229.rlib --extern expect_test=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libexpect_test-b8b556645eaa0682.rlib --extern intern=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libintern-5aa6c33258df0e99.rlib --extern libloading=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/liblibloading-b1774a0bd397ee05.rlib --extern memmap2=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libmemmap2-6db9560b7144855c.rlib --extern object=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libobject-0672272775bf5d02.rlib --extern paths=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libpaths-2128799b31e32b59.rlib --extern proc_macro_api=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libproc_macro_api-6fd109ca9e198ff2.rlib --extern proc_macro_test=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libproc_macro_test-3aa1679e78526f83.rlib --extern ra_ap_rustc_lexer=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libra_ap_rustc_lexer-c38095f01d647de9.rlib --extern snap=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libsnap-571fada0016afc93.rlib --extern span=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libspan-90a2950322b35d85.rlib --extern stdx=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libstdx-3f4d84bb1de9fdc9.rlib --extern syntax_bridge=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libsyntax_bridge-3d703117740a5ba2.rlib --extern tt=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libtt-845d10747f34c4d9.rlib --cfg=windows_raw_dylib -Csymbol-mangling-version=v0 -Zunstable-options '--check-cfg=cfg(bootstrap)' '--check-cfg=cfg(llvm_enzyme)' '--check-cfg=cfg(parallel_compiler)' '--check-cfg=cfg(rust_analyzer)' -Zmacro-backtrace -Csplit-debuginfo=off -Clink-args=-Wl,-z,origin '-Clink-args=-Wl,-rpath,$ORIGIN/../lib' -Zunstable-options -Zon-broken-pipe=kill -Z binary-dep-depinfo --check-cfg 'cfg(rust_analyzer)'` (exit status: 254)
  local time: Tue Sep 17 16:46:39 UTC 2024
  network time: Tue, 17 Sep 2024 16:46:39 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-09-17 18:24 UTC, dtolnay commented
_"Empty/Tombstone value shouldn't be inserted into map!"_ &mdash; I've seen the same LLVM crash previously in https://github.com/rust-lang/rust/pull/123436#issuecomment-2352165764, and it succeeded after retry....

@bors retry

2024-09-17 22:08 UTC, merged