Remove `#[macro_use] extern crate tracing` from `rustc_codegen_gcc`.
rust-lang/rust pull request #129768
Opened 2024-08-30 00:49 UTC by nnethercote

So that `tracing` is treated more like `smallvec` and `tempfile`, i.e. explicitly mentioned in the `Cargo.toml` file.

r? @antoyo

2024-08-30 00:50 UTC, nnethercote commented
Background: I have been removing `extern crate tracing` for all `rustc_*` crates, e.g. see #129767. I think it's reasonable to do the same for `rustc_codegen_gcc`. But I know it's a bit different to other crates (e.g. has its own `Cargo.{toml,lock}` files) so I'm not 100% sure about it.

2024-08-30 09:20 UTC, GuillaumeGomez approved these changes

2024-08-30 09:21 UTC, GuillaumeGomez commented
Looks good to me. I'll just wait for @antoyo to confirm before approving it.

2024-08-30 12:01 UTC, antoyo requested changes
I am against this change as this brings a number of unneeded dependencies.
If there's a way to not bring any new dependency, I would be OK with this.

2024-08-30 22:16 UTC, nnethercote commented
There is something going on that I don't understand here.

I tried making a trivial crate with this `Cargo.toml`:
```toml
[package]
name = "tracing-test"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
```
and this `src/main.rs`:
```rust
#[macro_use]
extern crate tracing;

fn main() {
    info!("Hello, world!");
}
```
and the `Cargo.lock` file gets all those dependencies like `tracing`, `pin-project-lite`, `quote`, etc. If I remove `tracing` from the `Cargo.toml` it doesn't compile, unsurprisingly.

How does the `#[macro_use] extern crate tracing` work in the `rustc_codegen_gcc` case? How does it let `tracing` macros be used seemingly without introducing dependencies on `tracing` and its dependent crates?

2024-08-30 22:38 UTC, antoyo commented
Maybe this crate is provided the same way as the other rustc crates like `rustc_apfloat`?
I don't know how this work, though.

2024-09-02 05:44 UTC, nnethercote commented
I [asked](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/extern.20crate.20tracing) on Zulip, it comes from the sysroot. Any crate used elsewhere in rustc can be used via `extern crate`. Which means we can actually use `extern crate` with more crates and shrink `Cargo.lock`. I filed #129876 to do this.

2024-09-02 05:48 UTC, closed without merging