chore: Fix hundreds of typos in 200+ files.
rust-lang/rust pull request #129867
Opened 2024-09-01 20:29 UTC by Sajjon

Fix hundreds of typos in 200+ files using [`typos` (Rust) cli tool](https://crates.io/crates/typos-cli) + 2 hours of manual work removing false positives.

**There might be some false positives left**.

I've not run any tests yet | which I ofc will do, I'm reading [dev guide about testing now](https://rustc-dev-guide.rust-lang.org/tests/running.html).

But I wanted to get feedback from Rust Community if you want me to break this PR up in many PRs? [I've recently done similar typos (fixing typos is a hobby of mine) in SwiftLang, where I split the work in 14 PRs](https://github.com/swiftlang/swift/issues/75022)- maybe something similar would be appriciated?

2024-09-01 20:35 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/10657131282/job/29536601200) [(plain)](https://github.com/rust-lang/rust/commit/905d1a4d155c8673897a835f91d7527872e692c0/checks/29536601200/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#13 2.699 Building wheels for collected packages: reuse
#13 2.700   Building wheel for reuse (pyproject.toml): started
#13 2.947   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 2.949   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132715 sha256=dfa09868353292d98f811d3efdb0d54d07389e808efc71d68e3b93c514bf8bec
#13 2.949   Stored in directory: /tmp/pip-ephem-wheel-cache-yvzcx5xp/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#13 2.951 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#13 3.359 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#13 3.359 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 3.885 Collecting virtualenv
#13 3.885 Collecting virtualenv
#13 3.921   Downloading virtualenv-20.26.3-py3-none-any.whl (5.7 MB)
#13 3.995      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 79.0 MB/s eta 0:00:00
#13 4.048 Collecting platformdirs<5,>=3.9.1
#13 4.051   Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
#13 4.086 Collecting filelock<4,>=3.12.2
#13 4.105 Collecting distlib<1,>=0.3.7
#13 4.109   Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
#13 4.116      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 KB 92.4 MB/s eta 0:00:00
#13 4.116      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 KB 92.4 MB/s eta 0:00:00
#13 4.195 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 4.385 Successfully installed distlib-0.3.8 filelock-3.15.4 platformdirs-4.2.2 virtualenv-20.26.3
#13 DONE 4.5s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      229312 kB
DirectMap2M:     8159232 kB
DirectMap1G:    10485760 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.04s
##[endgroup]
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/a48861a6279b386ad2b9c3518490181d238fe727/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/llvm-a48861a6279b386ad2b9c3518490181d238fe727-true/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm
---
##[endgroup]
fmt check
fmt: checked 5525 files
tidy check
tidy error: /checkout/compiler/rustc_resolve/messages.ftl: message `resolve_anonymous_lifetime_non_gat_report_error` is not used
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/tests/codegen/vec-in-place.rs:76: line longer than 100 chars
##[error]tidy error: /checkout/tests/codegen/vec-in-place.rs:89: line longer than 100 chars
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (24.1)
  Downloading pip-24.2-py3-none-any.whl.metadata (3.6 kB)
Downloading pip-24.2-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 11.0 MB/s eta 0:00:00
Installing collected packages: pip
---
Successfully installed pip-24.2
linting python files
All checks passed!
checking C++ file formatting
some tidy checks failed
Command has failed. Rerun with -v to see more details.
  local time: Sun Sep  1 20:35:18 UTC 2024
  network time: Sun, 01 Sep 2024 20:35:18 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-09-01 20:46 UTC, workingjubilee reviewed
This is a "typo-fixing" PR that will probably have effects on the compiler's behavior. I found at least one case. This is why T-compiler passed this decision: https://github.com/rust-lang/rust/issues/58619

I will leave it to them to decide what to do with this, but the problem is that this change does not come with automation to verify we don't add more typos.

2024-09-01 20:46 UTC, workingjubilee commented on compiler/rustc_resolve/messages.ftl
> +resolve_anonymous_lifetime_non_gat_report_error =
This one will change diagnostics.

2024-09-01 20:46 UTC, workingjubilee commented on library/core/src/array/mod.rs
> +/// Creating multiple copies of a `String`:
Note that despite my comments about altering compiler behavior, I would be happy to review and approve a PR which only touched the code in the library directory.

2024-09-01 20:47 UTC, workingjubilee commented on compiler/rustc_resolve/messages.ftl
> +resolve_anonymous_lifetime_non_gat_report_error =
Oh, actually it just fails to compile, heh.

2024-09-01 21:48 UTC, saethlin commented on tests/ui/mir/issue-29227.rs
> +            '\u{0041}', '\u{0042}', '\u{0043}', '\u{0044}', '\u{0045}', '\u{0046}', '\u{0047}', '\u{0048}', '\u{0049}', '\u{004A}', '\u{004B}', '\u{004C}', '\u{004D}', '\u{004E}', '\u{004F}', '\u{005
This and the other changes in this file are false positives

2024-09-01 21:54 UTC, saethlin commented
> But I wanted to get feedback from Rust Community if you want me to break this PR up in many PRs?

Yes. Different parts of the directory tree are owned by different groups of reviewers; you can tell by the mass of labels that was applied to this PR that it touches many separate areas.

In addition to what Jubilee said, I'd be happy to review:
* a PR of only comment fixes in `compiler/` except `compiler/rustc_codegen_gcc`
* a PR of any fixes to `src/tools/miri`
* a PR of any fixes to `tests/`

2024-09-01 22:17 UTC, matthiaskrgr commented
> fixing typos is a hobby of mine

have you considered writing a program that introduces subtle typos into a given document (switching letters or deleting random chracters etc)? This way you could fulfill you hobby of fixing typos as much as you would like without having to rely on other peoples time and review capacity. :slightly_smiling_face:

2024-09-01 22:41 UTC, saethlin commented
@matthiaskrgr Nobody is asking for your time. Please try to be kind.

2024-09-02 04:13 UTC, compiler-errors requested changes
Please do not fix typos in any tests. I'm sorry if that wasn't clear, but we do not typically accept typo fixes for tests since they're really just churn and they may affect test output in the worst case. I very much do not want to see any unnecessary churn in test files unless a typo is gravely affecting the ability to understand the test, which I don't believe is true here.

As for the logistics, this should be *at least* split into different PRs for `compiler/`, `library/`, and all the tools within `src/*`.

As for the typos in the files under `compiler/`, which I would probably be personally able to review:

I would also appreciate if you did your own self-review of this again, and remove anything that you're not *certain* is a typo. For example, you changed `optin_builtin_traits` to `option_builtin_traits` -- I understand that this requires context, but this is *not* a typo. If you don't have the context, I suggest just leaving it alone. I would appreciate if you reverted most of the actual variable name changes. For example, variables are typically not typo'd, compared to comments which seem like they often are. An example is `inh_mut` (inh stands for inherited, not a typo of "in").

2024-09-02 04:29 UTC, fee1-dead commented
> I would also appreciate if you did your own self-review of this again

You're referring to a different typo-fixing-person, I think.

2024-09-02 04:30 UTC, compiler-errors commented
@fee1-dead: No, I'm referring to the "+ 2 hours of manual work removing false positives".

2024-09-02 04:35 UTC, fee1-dead commented
I'd be happy to review this if the changes are only to `compiler/` and each PR is split to ~30 or more files each. Note that potential typos in `*.ftl` (like the `resolve_anonymous_livetime_non_gat_report_error`) need their corresponding identifiers in another file using it to also be changed `#[diag(resolve_anonymous_livetime_non_gat_report_error)]` or similar

2024-09-02 05:39 UTC, Sajjon commented
> I'd be happy to review this if the changes are only to `compiler/` and each PR is split to ~40 or more files each. Note that potential typos in `*.ftl` (like the `resolve_anonymous_livetime_non_gat_report_error`) need their corresponding identifiers in the Rust file using it to also be changed `#[diag(resolve_anonymous_livetime_non_gat_report_error)]` or similar

Perfect, thank you very much! I've done this, and made an issue to track progress across the three PRs - https://github.com/rust-lang/rust/issues/129874. I'm closing this PR in favour of using that tracking issue.

2024-09-02 05:39 UTC, closed without merging