uefi: process: Add args support
rust-lang/rust pull request #129838
Opened 2024-08-31 22:54 UTC by Ayush1325

- Wrap all args with quotes.
- Escape ^ and " inside quotes using ^.
- Doing reverse of arg parsing: https://github.com/rust-lang/rust/blob/d571ae851d93541bef826c3c48c1e9ad99da77d6/library/std/src/sys/pal/uefi/args.rs#L81

 r​? joboet

2024-08-31 22:55 UTC, Ayush1325 commented
r? @joboet

2024-08-31 22:57 UTC, Ayush1325 commented
Well, any new reviewer might want to look at: https://github.com/rust-lang/rust/pull/123196 for more context about uefi process.

2024-10-08 06:42 UTC, Ayush1325 commented
ping @Amanieu

2024-10-10 09:43 UTC, joboet requested changes

2024-10-10 09:43 UTC, joboet commented on library/std/src/sys/pal/uefi/process.rs
> +            crate::mem::forget(args);
This invalidates `ptr` as it moves the `Box`. Use `Box::into_raw` instead:
```suggestion
            let ptr = Box::into_raw(args).as_mut_ptr();
```

2024-10-10 09:43 UTC, joboet commented on library/std/src/sys/pal/uefi/process.rs
> +            let args_size = (crate::mem::size_of::<u16>() * len) as u32;
This can truncate the length if more than $2^31$ arguments are used. I'd use `size_of_val` on `args` together with `TryInto` instead.

2024-10-10 09:43 UTC, joboet commented on library/std/src/sys/pal/uefi/process.rs
> +                let _ = unsafe { Box::from_raw(crate::slice::from_raw_parts_mut(ptr, len)) };
I *think* this is correct, but I'd still prefer not to create a reference here:
```suggestion
                let _ = unsafe { Box::from_raw(ptr::slice_from_raw_parts_mut(ptr, len)) };
```

2024-10-10 09:43 UTC, joboet commented on library/std/src/sys/pal/uefi/process.rs
> +        let mut res = Vec::new();
Just a small optimization to reduce reallocation:
```suggestion
        // This is the lower bound on the final length under the assumption that
        // the arguments only contain ASCII characters.
        let mut res = Vec::with_capacity(args.iter().map(|arg| arg.len() + 3).sum());
```

2024-11-20 17:24 UTC, Amanieu commented
r? @joboet

2024-11-20 17:30 UTC, joboet approved these changes

2024-11-20 17:30 UTC, joboet commented
Looks good!
@bors r+

2024-11-20 17:31 UTC, joboet commented
*bors is asleep again, hang on*

2024-11-20 17:31 UTC, joboet commented
@bors r+

2024-11-21 01:04 UTC, merged