rustc_skip_during_method_dispatch: decouple receiver & edition
rust-lang/rust pull request #129871
Opened 2024-09-02 00:34 UTC by GrigorenkoPV

- Removes the implicit assumption that arrays are gated behind edition 2021, and boxed slices behind 2024.
- Addresses `// FIXME: We could probably do way better attribute validation here.`
- Abstracts `array` and `boxed_slice` away to a `GatedReceiver` enum, offering a more convenient extension point for when we run into the "add this impl now, but gate the method call syntax behind an edition" situation again.
- Instead of having a bool field for each possible receiver store a vec[^hash] of all `Receiver` + `Edition` pairs.
- Stable MIR now has a `#[non_exhaustive]` enum for Editions.

Would be cool if this attribute could be applied inside of an impl instead of to the entire trait declaration. This would eliminate the need for the `receiver` in the first place. But that's either something that had already been tried and failed, or a story for another day.

[^hash]: An alternative would be to use a HashMap from receivers to editions, but 99.999% of the time it would be empty (currently `IntoIterator` is the only trait in existence to have this attribute) and the remaining 0.001% it has like two elements, so any asymptotic improvements would probably be crushed by the constant multiplier. Also `ThinVec` is just 1 pointer wide, while `FxHashMap` is 4, IIRC. A bit wasteful.

2024-09-02 00:40 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/10658699259/job/29540184038) [(plain)](https://github.com/rust-lang/rust/commit/51788be39d9774849457da9fb8adfa1281e323d0/checks/29540184038/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#13 2.722 Building wheels for collected packages: reuse
#13 2.723   Building wheel for reuse (pyproject.toml): started
#13 2.965   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 2.966   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132715 sha256=dfa09868353292d98f811d3efdb0d54d07389e808efc71d68e3b93c514bf8bec
#13 2.966   Stored in directory: /tmp/pip-ephem-wheel-cache-t1k9h72c/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#13 2.969 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#13 3.367 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#13 3.367 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 3.890 Collecting virtualenv
#13 3.890 Collecting virtualenv
#13 3.949   Downloading virtualenv-20.26.3-py3-none-any.whl (5.7 MB)
#13 4.150      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 28.7 MB/s eta 0:00:00
#13 4.207 Collecting platformdirs<5,>=3.9.1
#13 4.216   Downloading platformdirs-4.2.2-py3-none-any.whl (18 kB)
#13 4.240 Collecting distlib<1,>=0.3.7
#13 4.260      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 KB 49.6 MB/s eta 0:00:00
#13 4.298 Collecting filelock<4,>=3.12.2
#13 4.306   Downloading filelock-3.15.4-py3-none-any.whl (16 kB)
#13 4.306   Downloading filelock-3.15.4-py3-none-any.whl (16 kB)
#13 4.386 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 4.575 Successfully installed distlib-0.3.8 filelock-3.15.4 platformdirs-4.2.2 virtualenv-20.26.3
#13 DONE 4.6s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      196544 kB
DirectMap2M:     6094848 kB
DirectMap1G:    12582912 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.04s
##[endgroup]
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/94885bc699512cfee8560e73c2a01ee6b4b76563/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/llvm-94885bc699512cfee8560e73c2a01ee6b4b76563-true/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm
---
fmt check
fmt: checked 5525 files
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/compiler/rustc_middle/src/ty/trait_def.rs:19: TODO is used for tasks that should be done before merging a PR; If you want to leave a message in the codebase use FIXME
##[error]tidy error: /checkout/compiler/rustc_middle/src/ty/trait_def.rs:28: TODO is used for tasks that should be done before merging a PR; If you want to leave a message in the codebase use FIXME
##[error]tidy error: /checkout/compiler/rustc_middle/src/ty/trait_def.rs:95: TODO is used for tasks that should be done before merging a PR; If you want to leave a message in the codebase use FIXME
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (24.1)
  Downloading pip-24.2-py3-none-any.whl.metadata (3.6 kB)
Downloading pip-24.2-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 63.4 MB/s eta 0:00:00
Installing collected packages: pip
---
Successfully installed pip-24.2
linting python files
All checks passed!
checking C++ file formatting
some tidy checks failed
Command has failed. Rerun with -v to see more details.
  local time: Mon Sep  2 00:40:25 UTC 2024
  network time: Mon, 02 Sep 2024 00:40:25 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-09-02 04:29 UTC, compiler-errors requested changes
Thanks for putting in the effort for generalizing this attribute, but given its inherently hacky nature, I personally don't believe it warrants generalization at the moment. I think the right point at which to decide is when we add another hack implementation in edition 2027, since there's no guarantee that this change is actually well suited for whatever receiver/trait pair we'd need to apply this to *next*, and the current design is suitable for the two existing implementations at moment.

2024-09-02 18:10 UTC, GrigorenkoPV commented
Sounds reasonable.

I will look into whether it is possible to move this from trait declarations to implementations, as this might reduce the "hackiness". But it is probably very not trivial, because otherwise it would've likely already been done. But until then,

2024-10-04 17:54 UTC, pnkfelix commented
since this is now in draft status, i'll move it back to waiting-on-author

@rustbot author

2024-11-17 15:13 UTC, Dylan-DPC commented
@GrigorenkoPV any updates of this?

2024-11-17 16:32 UTC, GrigorenkoPV commented
> @GrigorenkoPV any updates of this?

I initially created this as a step forward to #129872, which, similarly to `IntoIter for [T; N]` would have to gate method calls behind an edition, in this case, the 2027 edition (or whatever it will be called), which is different from the currently hardcoded 2021 edition for arrays.

However, #129872 should probably go through an ACP first, which I am yet to write.

2024-11-18 16:00 UTC, closed without merging