Add `NonNull` convenience methods to `Box` and `Vec`
rust-lang/rust pull request #130061
Opened 2024-09-07 08:37 UTC by theemathas

Implements the ACP: https://github.com/rust-lang/libs-team/issues/418.

The docs for the added methods are mostly copied from the existing methods that use raw pointers instead of `NonNull`.

I'm new to this "contributing to rustc" thing, so I'm sorry if I did something wrong. In particular, I don't know what the process is for creating a new unstable feature. Please advise me if I should do something.

2024-09-07 09:04 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/10750060875/job/29815752748) [(plain)](https://github.com/rust-lang/rust/commit/8230a90c494dcc7d8013a0a15719cc9f2f9a8263/checks/29815752748/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
------
 > importing cache manifest from ghcr.io/rust-lang/rust-ci-cache:fb97a1d6377f6cf2227825318ca4bbde3889e0c420746f5a03ba46a07e9a862725c26a09b9fc49a0d129ebd75935d3f6cd19acf41cc4267a6846fd4aa574b12c:
------
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
---- [ui] tests/ui/privacy/suggest-box-new.rs stdout ----
diff of stderr:

44    |                      ~~~~~~~~~~~~~~
45 LL |         wtf: Some(Box::new_in(_, _)),
-      and 10 other candidates
+      and 12 other candidates
48 help: consider using the `Default` trait
49    |
49    |
50 LL |         wtf: Some(<Box as std::default::Default>::default()),
89    |                ~~~~~~~~~~~~~~
90 LL |     let _ = Box::new_in(_, _);
91    |                ~~~~~~~~~~~~~~
-      and 10 other candidates
---
To only update this specific test, also pass `--test-args privacy/suggest-box-new.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/privacy/suggest-box-new.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/privacy/suggest-box-new" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/privacy/suggest-box-new/auxiliary"
--- stderr -------------------------------
error[E0423]: expected function, tuple struct or tuple variant, found struct `std::collections::HashMap`
##[error]  --> /checkout/tests/ui/privacy/suggest-box-new.rs:14:13
   |
---
LL |     let _ = std::collections::HashMap::with_capacity(_);
   |                                      ~~~~~~~~~~~~~~~~~~
LL |     let _ = std::collections::HashMap::with_hasher(_);
   |                                      ~~~~~~~~~~~~~~~~
LL |     let _ = std::collections::HashMap::with_capacity_and_hasher(_, _);
help: consider using the `Default` trait
   |
LL |     let _ = <std::collections::HashMap as std::default::Default>::default();
   |             +                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   |             +                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error[E0423]: cannot initialize a tuple struct which contains private fields
##[error]  --> /checkout/tests/ui/privacy/suggest-box-new.rs:8:19
   |
LL |         wtf: Some(Box(U { //~ ERROR cannot initialize a tuple struct which contains private fields
   |
note: constructor is not visible here due to private fields
  --> /rustc/FAKE_PREFIX/library/alloc/src/boxed.rs:236:14
   |
   |
   = note: private field
   |
   = note: private field
help: you might have meant to use an associated function to build this type
   |
LL |         wtf: Some(Box::new(_)),
   |                      ~~~~~~~~
LL |         wtf: Some(Box::new_uninit()),
   |                      ~~~~~~~~~~~~~~
LL |         wtf: Some(Box::new_zeroed()),
   |                      ~~~~~~~~~~~~~~
LL |         wtf: Some(Box::new_in(_, _)),
     and 12 other candidates
help: consider using the `Default` trait
   |
   |
LL |         wtf: Some(<Box as std::default::Default>::default()),

error: cannot construct `HashMap<_, _, _>` with struct literal syntax due to private fields
##[error]  --> /checkout/tests/ui/privacy/suggest-box-new.rs:16:13
   |
---
LL |     let _ = std::collections::HashMap::with_capacity(_);
   |                                      ~~~~~~~~~~~~~~~~~~
LL |     let _ = std::collections::HashMap::with_hasher(_);
   |                                      ~~~~~~~~~~~~~~~~
LL |     let _ = std::collections::HashMap::with_capacity_and_hasher(_, _);
help: consider using the `Default` trait
   |
LL |     let _ = <std::collections::HashMap as std::default::Default>::default();
   |             +                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   |             +                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error: cannot construct `Box<_, _>` with struct literal syntax due to private fields
##[error]  --> /checkout/tests/ui/privacy/suggest-box-new.rs:18:13
   |
LL |     let _ = Box {}; //~ ERROR cannot construct `Box<_, _>` with struct literal syntax due to private fields
   |
   = note: private fields `0` and `1` that were not provided
help: you might have meant to use an associated function to build this type
   |
   |
LL |     let _ = Box::new(_); //~ ERROR cannot construct `Box<_, _>` with struct literal syntax due to private fields
   |                ~~~~~~~~
LL |     let _ = Box::new_uninit(); //~ ERROR cannot construct `Box<_, _>` with struct literal syntax due to private fields
   |                ~~~~~~~~~~~~~~
LL |     let _ = Box::new_zeroed(); //~ ERROR cannot construct `Box<_, _>` with struct literal syntax due to private fields
   |                ~~~~~~~~~~~~~~
LL |     let _ = Box::new_in(_, _); //~ ERROR cannot construct `Box<_, _>` with struct literal syntax due to private fields
     and 12 other candidates
help: consider using the `Default` trait
   |
   |
LL |     let _ = <Box as std::default::Default>::default(); //~ ERROR cannot construct `Box<_, _>` with struct literal syntax due to private fields

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0423`.
---
To only update this specific test, also pass `--test-args suggestions/deref-path-method.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/suggestions/deref-path-method.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztransla [...]

2024-09-14 16:31 UTC, Mark-Simulacrum commented
This looks good to me. Thanks!

@bors r+

2024-09-14 17:43 UTC, workingjubilee commented
Needs a tracking issue and to reference that issue in its stability annotations.

@bors r-

2024-09-14 17:44 UTC, workingjubilee requested changes

2024-09-14 17:44 UTC, workingjubilee commented on library/alloc/src/boxed.rs
> +    #[unstable(feature = "box_vec_non_null", reason = "new API", issue = "none")]
here.

2024-09-14 17:44 UTC, workingjubilee commented on library/alloc/src/boxed.rs
> +    #[unstable(feature = "box_vec_non_null", reason = "new API", issue = "none")]
here.

2024-09-14 17:44 UTC, workingjubilee commented on library/alloc/src/vec/mod.rs
> +    #[unstable(feature = "box_vec_non_null", reason = "new API", issue = "none")]
here.

2024-09-14 17:47 UTC, workingjubilee commented
> I'm new to this "contributing to rustc" thing, so I'm sorry if I did something wrong. In particular, I don't know what the process is for creating a new unstable feature.

Before merging this API, it should have a tracking issue, that's all. It literally doesn't matter how nice you make the tracking issue (though the [library tracking issue template](https://github.com/rust-lang/rust/issues/new?assignees=&labels=C-tracking-issue%2C+T-libs-api&projects=&template=library_tracking_issue.md&title=Tracking+Issue+for+XXX) is a good start...), what matters is that when this lands, there is an issue number to point back to. Then it can be cleaned up if necessary.

2024-09-14 18:16 UTC, theemathas commented
@rustbot ready

2024-09-14 18:40 UTC, workingjubilee commented
cool, thanks.

@bors r=MarkSimulacrum,workingjubilee

2024-09-15 07:35 UTC, merged

2024-09-15 07:44 UTC, workingjubilee commented
chill, bors.
@bors r-