Report the `note` when specified in `diagnostic::on_unimplemented`
rust-lang/rust pull request #130123
Opened 2024-09-08 23:37 UTC by FedericoBruzzone

Before this PR the `note` field was completely ignored for some reason, now it is shown (I think) correctly during the hir typechecking phase.

1. Report the `note` when specified in `diagnostic::on_unimplemented`
2. Added a test for unimplemented trait diagnostic
3. Added a test for custom unimplemented trait diagnostic

Close #130084

P.S. This is my first PR. I am very excited to contribute, for any mistakes I will be happy to edit or add anything.

2024-09-08 23:45 UTC, FedericoBruzzone commented
@rustbot label +S-waiting-on-author +S-waiting-on-review

2024-09-09 00:05 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-17`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/10763996087/job/29846175557) [(plain)](https://github.com/rust-lang/rust/commit/7ffb12d5219ee3fbefda228ca7af31640b62af78/checks/29846175557/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
------
 > importing cache manifest from ghcr.io/rust-lang/rust-ci-cache:fb97a1d6377f6cf2227825318ca4bbde3889e0c420746f5a03ba46a07e9a862725c26a09b9fc49a0d129ebd75935d3f6cd19acf41cc4267a6846fd4aa574b12c:
------
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-17]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-17', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-17/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
---- [ui] tests/ui/methods/suggest-convert-ptr-to-ref.rs stdout ----
diff of stderr:

11    = note: the following trait bounds were not satisfied:
12            `*const u8: std::fmt::Display`
13            which is required by `*const u8: ToString`
+ note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
+    |
+    |
+ LL |     println!("{}", z.to_string());
14 
14 
15 error[E0599]: `*mut u8` doesn't implement `std::fmt::Display`

25    = note: the following trait bounds were not satisfied:
25    = note: the following trait bounds were not satisfied:
26            `*mut u8: std::fmt::Display`
27            which is required by `*mut u8: ToString`
+ note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
+    |
+    |
+ LL |     println!("{}", t.to_string());
28 
28 
29 error[E0599]: no method named `make_ascii_lowercase` found for raw pointer `*mut u8` in the current scope


The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/methods/suggest-convert-ptr-to-ref/suggest-convert-ptr-to-ref.stderr
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/methods/suggest-convert-ptr-to-ref/suggest-convert-ptr-to-ref.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args methods/suggest-convert-ptr-to-ref.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/methods/suggest-convert-ptr-to-ref.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/methods/suggest-convert-ptr-to-ref" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/methods/suggest-convert-ptr-to-ref/auxiliary"
--- stderr -------------------------------
--- stderr -------------------------------
error[E0599]: `*const u8` doesn't implement `std::fmt::Display`
   |
   |
LL |     println!("{}", z.to_string()); //~ ERROR E0599
   |                      ^^^^^^^^^ `*const u8` cannot be formatted with the default formatter
note: the method `to_string` exists on the type `&u8`
  --> /rustc/FAKE_PREFIX/library/alloc/src/string.rs:2544:5
  --> /rustc/FAKE_PREFIX/library/alloc/src/string.rs:2544:5
   = note: you might want to use the unsafe method `<*const T>::as_ref` to get an optional reference to the value behind the pointer
   = note: read the documentation for `<*const T>::as_ref` and ensure you satisfy its safety preconditions before calling it to avoid undefined behavior: https://doc.rust-lang.org/std/primitive.pointer.html#method.as_ref
   = note: the following trait bounds were not satisfied:
           `*const u8: std::fmt::Display`
           which is required by `*const u8: ToString`
  --> /checkout/tests/ui/methods/suggest-convert-ptr-to-ref.rs:5:22
   |
   |
LL |     println!("{}", z.to_string()); //~ ERROR E0599


error[E0599]: `*mut u8` doesn't implement `std::fmt::Display`
   |
   |
LL |     println!("{}", t.to_string()); //~ ERROR E0599
   |                      ^^^^^^^^^ `*mut u8` cannot be formatted with the default formatter
note: the method `to_string` exists on the type `&&mut u8`
  --> /rustc/FAKE_PREFIX/library/alloc/src/string.rs:2544:5
  --> /rustc/FAKE_PREFIX/library/alloc/src/string.rs:2544:5
   = note: you might want to use the unsafe method `<*mut T>::as_ref` to get an optional reference to the value behind the pointer
   = note: read the documentation for `<*mut T>::as_ref` and ensure you satisfy its safety preconditions before calling it to avoid undefined behavior: https://doc.rust-lang.org/std/primitive.pointer.html#method.as_ref-1
   = note: the following trait bounds were not satisfied:
           `*mut u8: std::fmt::Display`
           which is required by `*mut u8: ToString`
  --> /checkout/tests/ui/methods/suggest-convert-ptr-to-ref.rs:8:22
   |
   |
LL |     println!("{}", t.to_string()); //~ ERROR E0599


error[E0599]: no method named `make_ascii_lowercase` found for raw pointer `*mut u8` in the current scope
   |
   |
LL |     t.make_ascii_lowercase(); //~ ERROR E0599
   |       ^^^^^^^^^^^^^^^^^^^^ method not found in `*mut u8`
note: the method `make_ascii_lowercase` exists on the type `&mut u8`
  --> /rustc/FAKE_PREFIX/library/core/src/num/mod.rs:643:5
  --> /rustc/FAKE_PREFIX/library/core/src/num/mod.rs:643:5
   = note: you might want to use the unsafe method `<*mut T>::as_mut` to get an optional reference to the value behind the pointer
   = note: read the documentation for `<*mut T>::as_mut` and ensure you satisfy its safety preconditions before calling it to avoid undefined behavior: https://doc.rust-lang.org/std/primitive.pointer.html#method.as_mut

error[E0599]: no method named `as_mut_ref` found for raw pointer `*mut u8` in the current scope
   |
   |
LL |     let _ = t.as_mut_ref(); //~ ERROR E0599
   |
help: there is a method `as_mut` with a similar name
   |
   |
LL |     let _ = t.as_mut(); //~ ERROR E0599


error[E0599]: no method named `as_ref_mut` found for raw pointer `*mut u8` in the current scope
   |
   |
LL |     let _ = t.as_ref_mut(); //~ ERROR E0599
   |
help: there is a method `as_mut` with a similar name
   |
   |
LL |     le [...]

2024-09-09 12:57 UTC, compiler-errors requested changes

2024-09-09 12:57 UTC, compiler-errors commented on tests/ui/traits/on-unimplemented-diagnostic.rs
> +pub trait ProviderLt {}
This test doesn't really exercise anything. Could you please delete it?

2024-09-09 12:57 UTC, compiler-errors commented on compiler/rustc_hir_typeck/src/method/suggest.rs
> +                }
```suggestion
                for note in notes {
                    err.note(note);
                }
```

First, this was written a bit obtusely -- we can just use a for loop 😄. Second, you should use `.note` to be consistent with how trait errors are presented.

2024-09-09 12:58 UTC, compiler-errors commented on tests/ui/traits/custom-on-unimplemented-diagnostic.rs
> +    B.request(); //~ ERROR 15:7: 15:14: my message [E0599]
```suggestion
    B.request(); 
    //~^ ERROR my message
    //~| LABEL my label
    //~| NOTE my note
```

2024-09-10 20:53 UTC, compiler-errors commented on compiler/rustc_hir_typeck/src/method/suggest.rs
> +                    debug!("FCB {}", note);
FCB? can you remove?

2024-09-10 20:54 UTC, compiler-errors commented on tests/ui/traits/on-unimplemented-diagnostic.rs
> +pub trait ProviderLt {}
ping :)

2024-09-10 20:56 UTC, FedericoBruzzone commented on compiler/rustc_hir_typeck/src/method/suggest.rs
> +                    debug!("FCB {}", note);
I beg your pardon, I had forgotten :'D

2024-09-10 20:57 UTC, FedericoBruzzone commented on tests/ui/traits/custom-on-unimplemented-diagnostic.rs
> +//~| my note
Thank you. This is my first contribution, from the next I will learn best practices.

2024-09-10 21:00 UTC, FedericoBruzzone commented
@compiler-errors  Thank you for your review. 

It should be okay now, let me know

2024-09-10 21:01 UTC, compiler-errors commented
You still didn't delete the test file I asked to be deleted

2024-09-10 22:59 UTC, compiler-errors commented
@bors r+ rollup

2024-09-11 22:13 UTC, merged