distinguish overflow and unimplemented in Step::steps_between
rust-lang/rust pull request #130867
Opened 2024-09-26 01:40 UTC by michirakara

This PR implemented enhancement of `Step::steps_between` in #42168 , with hint-like return type, returning `(usize, Option<usize>)`.

When `&a <= &b` and steps between `a` and `b` is less than or equal to `usize::MAX`, `steps_between(&a, &b) == (n, Some(n))`.

When `&a <= &b` and steps between `a` and `b` is greater than `usize::MAX`, `steps_between(&a, &b) == (usize::MAX, None)`.

When `&a > &b` , `steps_between(&a, &b) == (0, None)`.

2024-09-26 02:01 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/11044002238/job/30679207542) [(plain)](https://github.com/rust-lang/rust/commit/0cdca2c0db116dee4ba46883601cd0b0938fac1c/checks/30679207542/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 3.020 Building wheels for collected packages: reuse
#16 3.021   Building wheel for reuse (pyproject.toml): started
#16 3.288   Building wheel for reuse (pyproject.toml): finished with status 'done'
#16 3.289   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132715 sha256=dfa09868353292d98f811d3efdb0d54d07389e808efc71d68e3b93c514bf8bec
#16 3.290   Stored in directory: /tmp/pip-ephem-wheel-cache-b0sukawl/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#16 3.292 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#16 3.723 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#16 3.724 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#16 DONE 3.8s
```

</details>

2024-09-26 02:22 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/11044340074/job/30680120337) [(plain)](https://github.com/rust-lang/rust/commit/7b3dc6209e893ee267f2792ef58f19c772566fb4/checks/30680120337/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 2.825 Building wheels for collected packages: reuse
#16 2.826   Building wheel for reuse (pyproject.toml): started
#16 3.080   Building wheel for reuse (pyproject.toml): finished with status 'done'
#16 3.081   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132715 sha256=dfa09868353292d98f811d3efdb0d54d07389e808efc71d68e3b93c514bf8bec
#16 3.081   Stored in directory: /tmp/pip-ephem-wheel-cache-wi0t52yh/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#16 3.084 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#16 3.493 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#16 3.494 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#16 DONE 3.6s
---
   Compiling std v0.0.0 (/checkout/library/std)
error[E0308]: mismatched types
   --> core/src/iter/range.rs:852:34
    |
852 |           if self.start < self.end {
853 | |             (0, Some(0));
    | |                         - help: remove this semicolon to return this value
854 | |         } else {
854 | |         } else {
    | |_________^ expected `(usize, Option<usize>)`, found `()`
    = note:  expected tuple `(usize, Option<usize>)`
            found unit type `()`

For more information about this error, try `rustc --explain E0308`.
```

</details>

2024-09-26 02:45 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/11044499444/job/30680533468) [(plain)](https://github.com/rust-lang/rust/commit/4ab4aa89daf303f095f8e382c1a70de224356181/checks/30680533468/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling llvm-bitcode-linker v0.0.1 (/checkout/src/tools/llvm-bitcode-linker)
    Finished `release` profile [optimized] target(s) in 5.92s
##[endgroup]
##[group]Building stage1 library artifacts (x86_64-unknown-linux-gnu)
error: process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc /checkout/obj/build/bootstrap/debug/rustc -vV` (exit status: 254)
error: rustc interrupted by SIGSEGV, printing backtrace


/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-a1b8689b027a25d5.so(+0xb500c3)[0x7f7bd73820c3]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f7bd64e1520]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-a1b8689b027a25d5.so(+0xb97590)[0x7f7bd73c9590]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-a1b8689b027a25d5.so(+0xab6501)[0x7f7bd72e8501]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-a1b8689b027a25d5.so(_RNvCskxAl5tAjtnG_17rustc_driver_impl14handle_options+0xf7)[0x7f7bd73693d7]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-a1b8689b027a25d5.so(+0xb2c12e)[0x7f7bd735e12e]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-a1b8689b027a25d5.so(_RNvCskxAl5tAjtnG_17rustc_driver_impl4main+0x30e)[0x7f7bd736b64e]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/rustc(+0x1167)[0x55ea71829167]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/rustc(+0x1133)[0x55ea71829133]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/rustc(+0x1149)[0x55ea71829149]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/libstd-0c7268aa146b0081.so(_RNvNtCsaxe4SnUHES6_3std2rt19lang_start_internal+0x4af)[0x7f7bd674440f]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/rustc(+0x1198)[0x55ea71829198]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7f7bd64c8d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7f7bd64c8e40]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/rustc(+0x1065)[0x55ea71829065]
note: we would appreciate a report at https://github.com/rust-lang/rust
help: you can increase rustc's stack size by setting RUST_MIN_STACK=16777216
help: you can increase rustc's stack size by setting RUST_MIN_STACK=16777216
rustc exited with signal: 11 (SIGSEGV) (core dumped)
Build completed unsuccessfully in 0:05:02
  local time: Thu Sep 26 02:45:41 UTC 2024
  network time: Thu, 26 Sep 2024 02:45:41 GMT
##[error]Process completed with exit code 1.
```

</details>

2024-10-01 10:24 UTC, joboet commented
r? libs-api

2024-11-03 22:04 UTC, dtolnay requested changes

2024-11-03 22:04 UTC, dtolnay commented on library/core/src/iter/range.rs
>              (0, Some(0))
This change is not correct. start\<end does not mean a range contains 0 items.

2024-11-03 22:04 UTC, dtolnay commented on library/core/src/iter/range.rs
>  pub trait Step: Clone + PartialOrd + Sized {
As you can see in https://github.com/rust-lang/rust/pull/130867#issuecomment-2375673871 something in this PR is causing a stack overflow in the compiler. It might be the bug I pointed out in one of my other comments, or something different.

2024-11-07 17:04 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/11727535206/job/32668853264) [(plain)](https://github.com/rust-lang/rust/commit/67492b92aecca6a025235bf28a0d787bb571db43/checks/32668853264/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling llvm-bitcode-linker v0.0.1 (/checkout/src/tools/llvm-bitcode-linker)
    Finished `release` profile [optimized] target(s) in 5.96s
##[endgroup]
##[group]Building stage1 library artifacts (x86_64-unknown-linux-gnu)
error: process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc /checkout/obj/build/bootstrap/debug/rustc -vV` (exit status: 254)
error: rustc interrupted by SIGSEGV, printing backtrace


/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-b3cdde1209f63c64.so(+0xbf9746)[0x7f12730f6746]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f1272312520]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-b3cdde1209f63c64.so(+0xca34c6)[0x7f12731a04c6]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-b3cdde1209f63c64.so(+0xb81431)[0x7f127307e431]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-b3cdde1209f63c64.so(_RNvCshxWDYVvKGJm_17rustc_driver_impl14handle_options+0xf7)[0x7f12731273c7]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-b3cdde1209f63c64.so(+0xc1e680)[0x7f127311b680]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-b3cdde1209f63c64.so(_RNvCshxWDYVvKGJm_17rustc_driver_impl4main+0x348)[0x7f12731296d8]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/rustc(+0x1167)[0x56290d6bc167]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/rustc(+0x1133)[0x56290d6bc133]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/rustc(+0x1149)[0x56290d6bc149]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-b3cdde1209f63c64.so(_RNvNtCsjxJ21FBN6L1_3std2rt19lang_start_internal+0x559)[0x7f12779ad1d9]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/rustc(+0x1198)[0x56290d6bc198]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7f12722f9d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7f12722f9e40]
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/rustc(+0x1065)[0x56290d6bc065]
note: we would appreciate a report at https://github.com/rust-lang/rust
help: you can increase rustc's stack size by setting RUST_MIN_STACK=16777216
help: you can increase rustc's stack size by setting RUST_MIN_STACK=16777216
rustc exited with signal: 11 (SIGSEGV) (core dumped)
Build completed unsuccessfully in 0:05:04
  local time: Thu Nov  7 17:03:59 UTC 2024
  network time: Thu, 07 Nov 2024 17:04:00 GMT
##[error]Process completed with exit code 1.
```

</details>

2024-11-07 17:57 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/11728467174/job/32671944030) [(plain)](https://github.com/rust-lang/rust/commit/45ff5d19c23c25e9e55cc39ecf56583c659005d3/checks/32671944030/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 2.838 Building wheels for collected packages: reuse
#16 2.840   Building wheel for reuse (pyproject.toml): started
#16 3.084   Building wheel for reuse (pyproject.toml): finished with status 'done'
#16 3.085   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132720 sha256=026f3bb0f1aa8090b861fd0a0939cb1a782396d84c8aab7875096557d637a0f6
#16 3.085   Stored in directory: /tmp/pip-ephem-wheel-cache-l4sllnr9/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#16 3.088 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#16 3.472 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#16 3.473 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#16 DONE 3.6s
---
    Checking core v0.0.0 (/checkout/library/core)
   Compiling libc v0.2.161
   Compiling memchr v2.5.0
   Compiling std v0.0.0 (/checkout/library/std)
error: expected `;`, found `}`
    |
247 | / macro_rules! step_integer_impls {
248 | |     {
249 | |         narrower than or same width as usize:
249 | |         narrower than or same width as usize:
250 | |             $( [ $u_narrower:ident $i_narrower:ident ] ),+;
266 | |                         (steps, Some(steps))
    | |                                             ^ help: add `;` here
267 | |                     } else {
    | |                     - unexpected token
    | |                     - unexpected token
...   |
422 | |     };
423 | | }
    | |_- in this expansion of `step_integer_impls!`
...
426 | / step_integer_impls! {
427 | |     narrower than or same width as usize: [u8 i8], [u16 i16], [u32 i32], [u64 i64], [usize isize];
428 | |     wider than usize: [u128 i128];
    | |_- in this macro invocation

error[E0412]: cannot find type `steps` in this scope
   --> core/src/iter/range.rs:266:26
   --> core/src/iter/range.rs:266:26
    |
247 | / macro_rules! step_integer_impls {
248 | |     {
249 | |         narrower than or same width as usize:
250 | |             $( [ $u_narrower:ident $i_narrower:ident ] ),+;
266 | |                         (steps, Some(steps))
    | |                          ^^^^^ not found in this scope
...   |
422 | |     };
422 | |     };
423 | | }
    | |_- in this expansion of `step_integer_impls!`
...
426 | / step_integer_impls! {
427 | |     narrower than or same width as usize: [u8 i8], [u16 i16], [u32 i32], [u64 i64], [usize isize];
428 | |     wider than usize: [u128 i128];
    | |_- in this macro invocation

error[E0573]: expected type, found variant `Some`
   --> core/src/iter/range.rs:266:33
   --> core/src/iter/range.rs:266:33
    |
247 | / macro_rules! step_integer_impls {
248 | |     {
249 | |         narrower than or same width as usize:
250 | |             $( [ $u_narrower:ident $i_narrower:ident ] ),+;
266 | |                         (steps, Some(steps))
    | |                                 ^^^^^^^^^^^
    | |                                 |
    | |                                 not a type
    | |                                 not a type
    | |                                 help: try using the variant's enum: `crate::option::Option`
...   |
422 | |     };
423 | | }
    | |_- in this expansion of `step_integer_impls!`
...
426 | / step_integer_impls! {
427 | |     narrower than or same width as usize: [u8 i8], [u16 i16], [u32 i32], [u64 i64], [usize isize];
428 | |     wider than usize: [u128 i128];
    | |_- in this macro invocation

error[E0412]: cannot find type `steps` in this scope
   --> core/src/iter/range.rs:266:38
   --> core/src/iter/range.rs:266:38
    |
247 | / macro_rules! step_integer_impls {
248 | |     {
249 | |         narrower than or same width as usize:
250 | |             $( [ $u_narrower:ident $i_narrower:ident ] ),+;
266 | |                         (steps, Some(steps))
    | |                                      ^^^^^ not found in this scope
...   |
422 | |     };
422 | |     };
423 | | }
    | |_- in this expansion of `step_integer_impls!`
...
426 | / step_integer_impls! {
427 | |     narrower than or same width as usize: [u8 i8], [u16 i16], [u32 i32], [u64 i64], [usize isize];
428 | |     wider than usize: [u128 i128];
    | |_- in this macro invocation

error[E0425]: cannot find value `step` in this scope
   --> core/src/iter/range.rs:791:43
   --> core/src/iter/range.rs:791:43
    |
791 |         let available = steps.1.unwrap_or(step.0);
    |                                           ^^^^ help: a local variable with a similar name exists: `steps`
error[E0214]: parenthesized type parameters may only be used with a `Fn` trait
   --> core/src/iter/range.rs:265:56
    |
247 | /  macro_rules! step_integer_impls {
247 | /  macro_rules! step_integer_impls {
248 | |      {
249 | |          narrower than or same width as usize:
250 | |              $( [ $u_narrower:ident $i_narrower:ident ] ),+;
...   |
265 | |                          let steps = (*end - *start) as usize
    | | ________________________________________________________^
266 | ||                         (steps, Some(steps))
    | ||____________________________________________^ only `Fn` traits may use parentheses
422 | |      };
423 | |  }
    | |__- in this expansion of `step_integer_impls!`
...
...
426 |  / step_integer_impls! {
427 |  |     narrower than or same width as usize: [u8 i8], [u16 i16], [u32 i32], [u64 i64], [usize isize];
428 |  |     wider than usize: [u128 i128];
    |  |_- in this macro invocation
    |
help: use angle brackets instead
    |
    |
266 |                         <steps, Some(steps)>

error[E0109]: type arguments are not allowed on builtin type `usize`
   --> core/src/iter/range.rs:266:26
    |
    |
247 | / macro_rules! step_integer_impls {
248 | |     {
249 | |         narrower than or same width as usize:
250 | |             $( [ $u_narrower:ident $i_narrower:ident ] ),+;
...   |
265 | |                         let steps = (*end - *start) as usize
    | |                                                        ----- not allowed on builtin type `usize`
266 | |                         (steps, Some(steps))
...   |
422 | |     };
423 | | }
    | |_- in this expansion of `step_integer_impls!`
    | |_- in this expansion of `step_integer_impls!`
...
426 | / step_integer_impls! {
427 | |     narrower than or same width as usize: [u8 i8], [u16 i16], [u32 i32], [u64 i64], [usize isize];
428 | |     wider than usize: [u128 i128];
    | |_- in this macro invocation
    |
help: primitive type `usize` doesn't have generic parameters
    |
    |
265 -                         let steps = (*end - *start) as usize
266 -                         (steps, Some(steps))
265 +                         let steps = (*end - *start) as usize

error[E0308]: mismatched types
   --> core/src/iter/range.rs:263:39
    |
    |
247 | /  macro_rules! step_integer_impls {
248 | |      {
249 | |          narrower than or same width as usize:
250 | |              $( [ $u_narrower:ident $i_narrower:ident ] ),+;
...   |
263 | |                      if *start <= *end {
    | | _______________________________________^
264 | ||                         // This relies on $u_narrower <= usize
265 | ||                         let steps = (*end - *start) as usize
266 | ||                         (steps, [...]

2024-11-07 18:13 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/11728696401/job/32672718450) [(plain)](https://github.com/rust-lang/rust/commit/48ec542c4f7093d675b1d9633fb8a48941b4c514/checks/32672718450/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#13 2.957 Building wheels for collected packages: reuse
#13 2.958   Building wheel for reuse (pyproject.toml): started
#13 3.214   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 3.215   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132720 sha256=026f3bb0f1aa8090b861fd0a0939cb1a782396d84c8aab7875096557d637a0f6
#13 3.215   Stored in directory: /tmp/pip-ephem-wheel-cache-a7nzksbe/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#13 3.218 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#13 3.639 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#13 3.639 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 4.217 Collecting virtualenv
#13 4.217 Collecting virtualenv
#13 4.278   Downloading virtualenv-20.27.1-py3-none-any.whl (3.1 MB)
#13 4.407      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 24.6 MB/s eta 0:00:00
#13 4.469 Collecting filelock<4,>=3.12.2
#13 4.477   Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
#13 4.502 Collecting distlib<1,>=0.3.7
#13 4.513   Downloading distlib-0.3.9-py2.py3-none-any.whl (468 kB)
#13 4.527      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 41.1 MB/s eta 0:00:00
#13 4.567 Collecting platformdirs<5,>=3.9.1
#13 4.575   Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
#13 4.659 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 4.841 Successfully installed distlib-0.3.9 filelock-3.16.1 platformdirs-4.3.6 virtualenv-20.27.1
#13 DONE 4.9s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      311232 kB
DirectMap2M:     7028736 kB
DirectMap1G:    11534336 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.04s
##[endgroup]
downloading https://static.rust-lang.org/dist/2024-10-16/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/2024-10-16/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt
---
fmt check
fmt: checked 5651 files
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/compiler/rustc_mir_build/src/check_unsafety.rs:120: TODO is used for tasks that should be done before merging a PR; If you want to leave a message in the codebase use FIXME
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (24.3.1)
All checks passed!
checking C++ file formatting
some tidy checks failed
some tidy checks failed
Command has failed. Rerun with -v to see more details.
  local time: Thu Nov  7 18:13:48 UTC 2024
  network time: Thu, 07 Nov 2024 18:13:48 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-11-07 18:19 UTC, calebcartwright commented
The most recent changes look like they contain a large diff related to some formatting version conflicts (the rustc repo uses a pinned, slightly older version of rustfmt), perhaps it's related to the merge commit or running rustfmt manually/editor as opposed to `./x fmt`?

2024-11-08 01:51 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/11734513224/job/32690675885) [(plain)](https://github.com/rust-lang/rust/commit/a5adf913f9d1f3281527562d0563ec2d7b210a05/checks/32690675885/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#13 2.962 Building wheels for collected packages: reuse
#13 2.963   Building wheel for reuse (pyproject.toml): started
#13 3.214   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 3.215   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132720 sha256=026f3bb0f1aa8090b861fd0a0939cb1a782396d84c8aab7875096557d637a0f6
#13 3.215   Stored in directory: /tmp/pip-ephem-wheel-cache-bg00dvtu/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#13 3.218 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#13 3.623 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#13 3.624 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 4.179 Collecting virtualenv
#13 4.179 Collecting virtualenv
#13 4.229   Downloading virtualenv-20.27.1-py3-none-any.whl (3.1 MB)
#13 4.361      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 24.1 MB/s eta 0:00:00
#13 4.420 Collecting platformdirs<5,>=3.9.1
#13 4.429   Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
#13 4.454 Collecting distlib<1,>=0.3.7
#13 4.475      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 41.1 MB/s eta 0:00:00
#13 4.516 Collecting filelock<4,>=3.12.2
#13 4.524   Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
#13 4.524   Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
#13 4.607 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 4.785 Successfully installed distlib-0.3.9 filelock-3.16.1 platformdirs-4.3.6 virtualenv-20.27.1
#13 DONE 4.9s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      300992 kB
DirectMap2M:     5990400 kB
DirectMap1G:    12582912 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.04s
##[endgroup]
downloading https://static.rust-lang.org/dist/2024-10-16/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/2024-10-16/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt
---
fmt check
fmt: checked 5654 files
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/compiler/rustc_mir_build/src/check_unsafety.rs:120: TODO is used for tasks that should be done before merging a PR; If you want to leave a message in the codebase use FIXME
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (24.3.1)
All checks passed!
checking C++ file formatting
some tidy checks failed
some tidy checks failed
Command has failed. Rerun with -v to see more details.
  local time: Fri Nov  8 01:51:43 UTC 2024
  network time: Fri, 08 Nov 2024 01:51:44 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-11-08 03:37 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/11735344959/job/32692887743) [(plain)](https://github.com/rust-lang/rust/commit/f63f5f399227ae4e683d95c6541943e6ed14b7e8/checks/32692887743/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
------
 > importing cache manifest from ghcr.io/rust-lang/rust-ci-cache:c32c805632780b5c1de330e3f44561b336c2efe163bc0990acb392390157a8e1d9f855d75914a239aa40c49d77f4a837247d05d2f8d46f554b98e1f46712a3e3:
------
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
---- [ui] tests/ui/impl-trait/example-calendar.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/impl-trait/example-calendar.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "-O" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-trait/example-calendar/a" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers"
--- stderr -------------------------------
error[E0053]: method `steps_between` has an incompatible type for trait
##[error]  --> /checkout/tests/ui/impl-trait/example-calendar.rs:159:45
   |
   |
LL |     fn steps_between(_: &Self, _: &Self) -> Option<usize> {
   |                                             ^^^^^^^^^^^^^ expected `(usize, Option<usize>)`, found `Option<usize>`
   |
   = note: expected signature `fn(&NaiveDate, &NaiveDate) -> (usize, Option<usize>)`
              found signature `fn(&NaiveDate, &NaiveDate) -> Option<usize>`
   |
   |
LL |     fn steps_between(_: &Self, _: &Self) -> (usize, Option<usize>) {

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0053`.
For more information about this error, try `rustc --explain E0053`.
------------------------------------------


---- [ui] tests/ui/issues/issue-48006.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/issues/issue-48006.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "-O" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-48006/a" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers"
--- stderr -------------------------------
error[E0599]: no method named `is_some` found for tuple `(usize, Option<usize>)` in the current scope
##[error]  --> /checkout/tests/ui/issues/issue-48006.rs:14:51
   |
   |
LL |     assert!(Step::steps_between(&0u32, &u32::MAX).is_some());
   |                                                   ^^^^^^^ method not found in `(usize, Option<usize>)`
error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0599`.
------------------------------------------
```

</details>

2024-11-21 23:56 UTC, dtolnay commented
I squashed these 7 commits into one:

- 0cdca2c0db116dee4ba46883601cd0b0938fac1c distinguish overflow and unimplemented in Step::steps_between
- 7b3dc6209e893ee267f2792ef58f19c772566fb4 Fixed bug
- 4ab4aa89daf303f095f8e382c1a70de224356181 actually fixed bug
- 7e3d4c3b3e735ebf1d245af142acbd51cad9c94d fixed format
- f63f5f399227ae4e683d95c6541943e6ed14b7e8 fixed the link of docs
- 67b05607e484443503529dbba484762385e05597 fixed tests
- 921451de2af15601687a4ff65459ce2d88c52e5a fixed format manually since x.py fmt did not work

There is one other piece of formatting I'll fix in the next push.

2024-11-21 23:57 UTC, dtolnay approved these changes
Thank you!

2024-11-21 23:57 UTC, dtolnay commented
@bors r+

2024-11-22 13:34 UTC, merged

2024-11-22 14:52 UTC, rust-timer commented
Finished benchmarking commit (f1e07524047cbc46501a429134e80505a7cd73c0): [comparison URL](https://perf.rust-lang.org/compare.html?start=2cf7908998e5010ffdedede39f88fa2590e9c830&end=f1e07524047cbc46501a429134e80505a7cd73c0&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=2cf7908998e5010ffdedede39f88fa2590e9c830&end=f1e07524047cbc46501a429134e80505a7cd73c0&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=2cf7908998e5010ffdedede39f88fa2590e9c830&end=f1e07524047cbc46501a429134e80505a7cd73c0&stat=max-rss)
<details>
<summary>Results (primary -2.0%, secondary -3.2%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 2.2%  | [2.2%, 2.2%]   | 1     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -3.4% | [-4.6%, -2.5%] | 3     |
| Improvements ✅ <br /> (secondary) | -3.2% | [-3.2%, -3.2%] | 1     |
| All ❌✅ (primary)                 | -2.0% | [-4.6%, 2.2%]  | 4     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=2cf7908998e5010ffdedede39f88fa2590e9c830&end=f1e07524047cbc46501a429134e80505a7cd73c0&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=2cf7908998e5010ffdedede39f88fa2590e9c830&end=f1e07524047cbc46501a429134e80505a7cd73c0&stat=size:linked_artifact)
<details>
<summary>Results (primary 0.0%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.1%  | [0.0%, 0.1%]   | 6     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -0.0% | [-0.0%, -0.0%] | 4     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | 0.0%  | [-0.0%, 0.1%]  | 10    |
</details>

**Bootstrap**: 796.948s -> 794.896s (-0.26%)
**Artifact size**: 335.99 MiB -> 336.03 MiB (0.01%)