Fix the misleading diagnostic for `let_underscore_drop` on type without `Drop` implementation
rust-lang/rust pull request #130833
Opened 2024-09-25 13:32 UTC by makai410

Closes: #130430 
r? rust-lang/diagnostics

2024-09-25 14:28 UTC, compiler-errors approved these changes

2024-09-25 14:28 UTC, compiler-errors requested changes

2024-09-25 14:28 UTC, compiler-errors commented on src/tools/rust-analyzer/crates/ide-db/src/generated/lints.rs
> +        description: r##"non-binding let on a type that has a destructor"##,
Actually: please revert this change; afaict it's auto-generated, and rust-analyzer will deal with it on their own.

2024-09-26 01:13 UTC, fee1-dead commented
@bors r+ rollup

2024-09-26 01:15 UTC, fee1-dead commented
@bors r=fee1-dead,compiler-errors

2024-09-26 01:20 UTC, compiler-errors commented
@bors r-

Please rebase this into one commit; none of this PR's history should need to be synced next time that rust-analyzer does a subtree sync.

2024-09-26 01:22 UTC, compiler-errors commented
Or you can do (making sure you're on this branch):

```
git reset HEAD~2
git commit -am "Fix the misleading diagnostic for let_underscore_drop on type without Drop implementation"
# then push with `--force-with-lease`
```

2024-09-26 02:42 UTC, fee1-dead commented
> Please rebase this into one commit;

Oops, thanks for catching this! Wasn't looking at the commits log when I reviewed..

2024-09-26 02:48 UTC, compiler-errors commented
@bors r=compiler-errors,fee1-dead

2024-09-27 01:12 UTC, merged