100% safe implementation of RepeatN
rust-lang/rust pull request #130887
Opened 2024-09-26 16:31 UTC by Soveu

I've seen the "Use MaybeUninit for RepeatN" commit while reading This Week In Rust and immediately thought about something I've written some time ago - https://github.com/Soveu/repeat_finite/blob/master/src/lib.rs.

Using the fact, that `Option` will find niche in `(T, NonZeroUsize)`, we can construct something that has the same size as `(T, usize)` while completely getting rid of `MaybeUninit`.
This leaves only `unsafe` on `TrustedLen`, which is pretty neat.

2024-09-26 17:00 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/11056430353/job/30717966206) [(plain)](https://github.com/rust-lang/rust/commit/464f771c865aa06fc8bc0843d8f1daf2f5ebb2c1/checks/30717966206/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
------
 > importing cache manifest from ghcr.io/rust-lang/rust-ci-cache:30ca74372d8b771363f68f939a58b017a592fae4f69398600dc51145997160f03e9652051f957840c41898984a88855e9757fa23464703a5a4ba21316ddebb04:
------
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'change-id=99999999', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
failures:

---- [codegen] tests/codegen/iter-repeat-n-trivial-drop.rs stdout ----

error: verification with 'FileCheck' failed
status: exit status: 1
command: "/usr/lib/llvm-18/bin/FileCheck" "--input-file" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll" "/checkout/tests/codegen/iter-repeat-n-trivial-drop.rs" "--check-prefix=CHECK" "--check-prefix" "NONMSVC" "--allow-unused-prefixes" "--dump-input-context" "100"
--- stderr -------------------------------
--- stderr -------------------------------
/checkout/tests/codegen/iter-repeat-n-trivial-drop.rs:29:17: error: CHECK-NEXT: is not on the line after the previous match
 // CHECK-NEXT: store i64 %[[DEC]]
                ^
/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll:21:2: note: 'next' match was here
 store i64 %_10.0.i, ptr %it, align 8, !alias.scope !3
 ^
/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll:16:27: note: previous match ended here
 %_10.0.i = add i64 %0, -1
                          ^
/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll:17:1: note: non-matching line after previous match is here
 %2 = icmp eq i64 %_10.0.i, 0

Input file: /checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll
Check file: /checkout/tests/codegen/iter-repeat-n-trivial-drop.rs


-dump-input=help explains the following input dump.
Input was:
<<<<<<
<<<<<<
         1: ; ModuleID = 'iter_repeat_n_trivial_drop.80fa96dad9145ebd-cgu.0' 
         2: source_filename = "iter_repeat_n_trivial_drop.80fa96dad9145ebd-cgu.0" 
         3: target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128" 
         4: target triple = "x86_64-unknown-linux-gnu" 
         5:  
         6: @__rust_no_alloc_shim_is_unstable = external global i8 
         7:  
         8: ; Function Attrs: mustprogress nofree norecurse nosync nounwind nonlazybind willreturn memory(argmem: readwrite) uwtable 
         9: define { i16, i16 } @iter_repeat_n_next(ptr noalias nocapture noundef align 8 dereferenceable(16) %it) unnamed_addr #0 { 
        10: start: 
        11:  %0 = load i64, ptr %it, align 8, !alias.scope !3, !noundef !6 
        12:  %1 = icmp eq i64 %0, 0 
        13:  br i1 %1, label %"_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17hd614a6386f3f6a14E.exit", label %bb8.i 
        14:  
        15: bb8.i: ; preds = %start 
        16:  %_10.0.i = add i64 %0, -1 
        17:  %2 = icmp eq i64 %_10.0.i, 0 
        18:  br i1 %2, label %bb5.i, label %bb3.i 
        19:  
        20: bb3.i: ; preds = %bb8.i 
        21:  store i64 %_10.0.i, ptr %it, align 8, !alias.scope !3 
next:29      !~~~~~~~~~~~~~~~~~                                     error: match on wrong line
        22:  %_14.i = getelementptr inbounds i8, ptr %it, i64 8 
        23:  %_14.val.i = load i16, ptr %_14.i, align 8, !alias.scope !3, !noundef !6 
        24:  br label %"_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17hd614a6386f3f6a14E.exit" 
        25:  
        26: bb5.i: ; preds = %bb8.i 
        27:  %3 = getelementptr inbounds i8, ptr %it, i64 8 
        28:  %4 = load i16, ptr %3, align 8, !alias.scope !7 
        29:  store i64 0, ptr %it, align 8, !alias.scope !7 
        30:  br label %"_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17hd614a6386f3f6a14E.exit" 
        31:  
        32: "_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17hd614a6386f3f6a14E.exit": ; preds = %start, %bb3.i, %bb5.i 
        33:  %_0.sroa.5.0.i = phi i16 [ %4, %bb5.i ], [ %_14.val.i, %bb3.i ], [ undef, %start ] 
        34:  %_0.sroa.0.0.i = phi i16 [ 1, %bb5.i ], [ 1, %bb3.i ], [ 0, %start ] 
        35:  %5 = insertvalue { i16, i16 } poison, i16 %_0.sroa.0.0.i, 0 
        36:  %6 = insertvalue { i16, i16 } %5, i16 %_0.sroa.5.0.i, 1 
        37:  ret { i16, i16 } %6 
        38: } 
        39:  
        40: ; Function Attrs: nonlazybind uwtable 
        41: define void @vec_extend_via_iter_repeat_n(ptr dead_on_unwind noalias nocapture noundef writable writeonly sret([24 x i8]) align 8 dereferenceable(24) %_0) unnamed_addr #1 personality ptr @rust_eh_personality { 
        42: start: 
        43:  %0 = load volatile i8, ptr @__rust_no_alloc_shim_is_unstable, align 1, !noalias !10 
        44:  %_0.i.i.i.i.i = tail call noalias noundef dereferenceable_or_null(1234) ptr @__rust_alloc(i64 noundef 1234, i64 noundef 1) #7, !noalias !10 
        45:  %.not.i = icmp eq ptr %_0.i.i.i.i.i, null 
        46:  br i1 %.not.i, label %bb3.i, label %"_ZN5alloc7raw_vec20RawVecInner$LT$A$GT$16with_capacity_in17hc84b3681aea48da3E.exit" 
        47:  
        48: bb3.i: ; preds = %start 
        49: ; call alloc::raw_vec::handle_error 
        50:  tail call void @_RNvNtCskKY2y5SXpvL_5alloc7raw_vec12handle_error(i64 1234, i64 noundef 1) #8 
        51:  unreachable 
        52:  
        53: "_ZN5alloc7raw_vec20RawVecInner$LT$A$GT$16with_capacity_in17hc84b3681aea48da3E.exit": ; preds = %start 
        54:  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 1 dereferenceable(1234) %_0.i.i.i.i.i, i8 42, i64 1234, i1 false), !noalias !13 
        55:  store i64 1234, ptr %_0, align 8 
        56:  %v.sroa.4.0._0.sroa_idx = getelementptr inbounds i8, ptr %_0, i64 8 
        57:  store ptr %_0.i.i.i.i.i, ptr %v.sroa.4.0._0.sroa_idx, align 8 
        58:  %v.sroa.5.0._0.sroa_idx = getelementptr inbounds i8, ptr %_0, i64 16 
        59:  store i64 1234, ptr %v.sroa.5.0._0.sroa_idx, align 8 
        60:  ret void 
        61: } 
        62:  
        63: ; Function Attrs: mustprogress nofree norecurse [...]

2024-09-26 17:34 UTC, Soveu commented
huh, I'm no llvm expert, buuut...

```
          8: ; Function Attrs: mustprogress nofree norecurse nosync nounwind nonlazybind willreturn memory(argmem: readwrite) uwtable 
           9: define { i16, i16 } @iter_repeat_n_next(ptr noalias nocapture noundef align 8 dereferenceable(16) %it) unnamed_addr #0 { 
          10: start: 
          11:  %0 = load i64, ptr %it, align 8, !alias.scope !3, !noundef !6 
          12:  %1 = icmp eq i64 %0, 0 
          13:  br i1 %1, label %"_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17hd614a6386f3f6a14E.exit", label %bb8.i 
          14:  
          15: bb8.i: ; preds = %start 
          16:  %_10.0.i = add i64 %0, -1 
          17:  %2 = icmp eq i64 %_10.0.i, 0 
          18:  br i1 %2, label %bb5.i, label %bb3.i 
          19:  
          20: bb3.i: ; preds = %bb8.i 
          21:  store i64 %_10.0.i, ptr %it, align 8, !alias.scope !3 
  next:29      !~~~~~~~~~~~~~~~~~                                     error: match on wrong line
          22:  %_14.i = getelementptr inbounds i8, ptr %it, i64 8 
          23:  %_14.val.i = load i16, ptr %_14.i, align 8, !alias.scope !3, !noundef !6 
          24:  br label %"_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17hd614a6386f3f6a14E.exit" 
          25:  
          26: bb5.i: ; preds = %bb8.i 
          27:  %3 = getelementptr inbounds i8, ptr %it, i64 8 
          28:  %4 = load i16, ptr %3, align 8, !alias.scope !7 
          29:  store i64 0, ptr %it, align 8, !alias.scope !7 
          30:  br label %"_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17hd614a6386f3f6a14E.exit" 
          31:  
          32: "_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17hd614a6386f3f6a14E.exit": ; preds = %start, %bb3.i, %bb5.i 
          33:  %_0.sroa.5.0.i = phi i16 [ %4, %bb5.i ], [ %_14.val.i, %bb3.i ], [ undef, %start ] 
          34:  %_0.sroa.0.0.i = phi i16 [ 1, %bb5.i ], [ 1, %bb3.i ], [ 0, %start ] 
          35:  %5 = insertvalue { i16, i16 } poison, i16 %_0.sroa.0.0.i, 0 
          36:  %6 = insertvalue { i16, i16 } %5, i16 %_0.sroa.5.0.i, 1 
          37:  ret { i16, i16 } %6 
          38: } 
```
`bb3.i` and `bb5.i` if not for the `store i64` they would look identical.

The other functions (`vec_extend_via_repeat_n` and `array_repeat_not_copy`) look ok.

2024-11-28 15:16 UTC, Dylan-DPC commented
@Soveu any updates on the failed test? thanks

2024-11-29 17:37 UTC, Soveu commented
> @Soveu any updates on the failed test? thanks

I guess we don't want to introduce additional branches in the generated code, so for "production" code this implementation would be unfit. @scottmcm could comment on that.

2024-11-29 21:47 UTC, Soveu commented
I have tried some things when first writing this code, with no effect, but the idea with `mem::needs_drop` made me try again. I was able to make the branches very similar, making LLVM merge them :) Technically there is still a case, where clone is more expensive than move, but the type does not have `drop()`. Probably it doesn't happen often, but might need consideration.

```rust
    fn next(&mut self) -> Option<A> {
        let inner = self.inner.as_mut()?;
        let count = inner.count.get();

        if let Some(new_count) = NonZero::<usize>::new(count - 1) {
            let tmp = inner.element.clone();
            inner.count = new_count;
            return Some(tmp);
        }

        return if core::mem::needs_drop::<A>() {
            self.take_element()
        } else {
            let tmp = inner.element.clone();
            self.inner = None;
            Some(tmp)
        };
    }
```

Godbolt: https://rust.godbolt.org/z/Kr198x635

LLVM output:
```
define { i16, i16 } @iter_repeat_n_next(ptr noalias nocapture noundef align 8 dereferenceable(16) %it) unnamed_addr personality ptr @rust_eh_personality {
start:
  %0 = getelementptr inbounds i8, ptr %it, i64 8
  %1 = load i64, ptr %0, align 8
  %2 = icmp eq i64 %1, 0
  br i1 %2, label %"_ZN84_$LT$example..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17hbed8c0f5d41a7103E.exit", label %bb13.i

bb13.i:
  %count.i = add i64 %1, -1
  %3 = load i16, ptr %it, align 8
  store i64 %count.i, ptr %0, align 8
  br label %"_ZN84_$LT$example..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17hbed8c0f5d41a7103E.exit"

"_ZN84_$LT$example..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17hbed8c0f5d41a7103E.exit":
  %_0.sroa.6.0.i = phi i16 [ undef, %start ], [ %3, %bb13.i ]
  %_0.sroa.0.0.i = phi i16 [ 0, %start ], [ 1, %bb13.i ]
  %4 = insertvalue { i16, i16 } poison, i16 %_0.sroa.0.0.i, 0
  %5 = insertvalue { i16, i16 } %4, i16 %_0.sroa.6.0.i, 1
  ret { i16, i16 } %5
}

declare noundef range(i32 0, 10) i32 @rust_eh_personality(i32 noundef, i32 noundef range(i32 1, 17), i64 noundef, ptr noundef, ptr noundef) unnamed_addr #1
```

LLVM output for the current std implementation:
```
define { i16, i16 } @iter_repeat_n_next(ptr noalias nocapture noundef align 8 dereferenceable(16) %it) unnamed_addr {
start:
  %_3 = load i64, ptr %it, align 8
  %_2.not = icmp eq i64 %_3, 0
  br i1 %_2.not, label %bb4, label %bb1

bb1:
  %_2.i = add i64 %_3, -1
  store i64 %_2.i, ptr %it, align 8
  %0 = getelementptr inbounds i8, ptr %it, i64 8
  %result.i = load i16, ptr %0, align 8
  br label %bb4

bb4:
  %_0.sroa.3.0 = phi i16 [ %result.i, %bb1 ], [ undef, %start ]
  %_0.sroa.0.0 = phi i16 [ 1, %bb1 ], [ 0, %start ]
  %1 = insertvalue { i16, i16 } poison, i16 %_0.sroa.0.0, 0
  %2 = insertvalue { i16, i16 } %1, i16 %_0.sroa.3.0, 1
  ret { i16, i16 } %2
}
```
From what I see, `%0 = getelementptr inbounds i8, ptr %it, i64 8` gets moved to the top

2024-11-29 21:59 UTC, Soveu commented
That is interesting, just switching variables made it work :thinking: 
```rust
    fn next(&mut self) -> Option<A> {
        let inner = self.inner.as_mut()?;
        let count = inner.count.get();

        if let Some(new_count) = NonZero::<usize>::new(count - 1) {
            // This must be in this order!
            let tmp = inner.element.clone();
            inner.count = new_count;
            return Some(tmp);
        }

        return self.take_element();
    }
```

2024-11-29 22:31 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12091067533/job/33718997290) [(plain)](https://github.com/rust-lang/rust/commit/ff05378339e5185f5d45b491ae367c9c2127c1f8/checks/33718997290/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 exporting to docker image format
#16 sending tarball 28.2s done
#16 DONE 34.3s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
failures:

---- [codegen] tests/codegen/iter-repeat-n-trivial-drop.rs stdout ----

error: verification with 'FileCheck' failed
status: exit status: 1
command: "/usr/lib/llvm-18/bin/FileCheck" "--input-file" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll" "/checkout/tests/codegen/iter-repeat-n-trivial-drop.rs" "--check-prefix=CHECK" "--check-prefix" "NONMSVC" "--allow-unused-prefixes" "--dump-input-context" "100"
--- stderr -------------------------------
--- stderr -------------------------------
/checkout/tests/codegen/iter-repeat-n-trivial-drop.rs:29:17: error: CHECK-NEXT: is not on the line after the previous match
 // CHECK-NEXT: store i64 %[[DEC]]
                ^
/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll:21:2: note: 'next' match was here
 store i64 %_10.0.i, ptr %it, align 8, !alias.scope !3
 ^
/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll:18:27: note: previous match ended here
 %_10.0.i = add i64 %0, -1
                          ^
/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll:19:1: note: non-matching line after previous match is here
 %2 = getelementptr inbounds i8, ptr %it, i64 8

Input file: /checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll
Check file: /checkout/tests/codegen/iter-repeat-n-trivial-drop.rs


-dump-input=help explains the following input dump.
Input was:
<<<<<<
<<<<<<
         1: ; ModuleID = 'iter_repeat_n_trivial_drop.80fa96dad9145ebd-cgu.0' 
         2: source_filename = "iter_repeat_n_trivial_drop.80fa96dad9145ebd-cgu.0" 
         3: target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128" 
         4: target triple = "x86_64-unknown-linux-gnu" 
         5:  
         6: @__rust_no_alloc_shim_is_unstable = external global i8 
         7: @alloc_3e3222eab6a509f29fa54d8acd188f56 = private unnamed_addr constant <{ [53 x i8] }> <{ [53 x i8] c"/checkout/tests/codegen/iter-repeat-n-trivial-drop.rs" }>, align 1 
         8: @alloc_c9b9d5d510259832d9dc24c4ff1ee7cf = private unnamed_addr constant <{ ptr, [16 x i8] }> <{ ptr @alloc_3e3222eab6a509f29fa54d8acd188f56, [16 x i8] c"5\00\00\00\00\00\00\006\00\00\00\11\00\00\00" }>, align 8 
         9:  
        10: ; Function Attrs: mustprogress nofree norecurse nosync nounwind nonlazybind willreturn memory(argmem: readwrite) uwtable 
        11: define { i16, i16 } @iter_repeat_n_next(ptr noalias nocapture noundef align 8 dereferenceable(16) %it) unnamed_addr #0 { 
        12: start: 
        13:  %0 = load i64, ptr %it, align 8, !alias.scope !3, !noundef !6 
        14:  %1 = icmp eq i64 %0, 0 
        15:  br i1 %1, label %"_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17ha8404e90608405dcE.exit", label %bb8.i 
        16:  
        17: bb8.i: ; preds = %start 
        18:  %_10.0.i = add i64 %0, -1 
        19:  %2 = getelementptr inbounds i8, ptr %it, i64 8 
        20:  %3 = load i16, ptr %2, align 8, !alias.scope !3 
        21:  store i64 %_10.0.i, ptr %it, align 8, !alias.scope !3 
next:29      !~~~~~~~~~~~~~~~~~                                     error: match on wrong line
        22:  br label %"_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17ha8404e90608405dcE.exit" 
        23:  
        24: "_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17ha8404e90608405dcE.exit": ; preds = %start, %bb8.i 
        25:  %_0.sroa.5.0.i = phi i16 [ undef, %start ], [ %3, %bb8.i ] 
        26:  %_0.sroa.0.0.i = phi i16 [ 0, %start ], [ 1, %bb8.i ] 
        27:  %4 = insertvalue { i16, i16 } poison, i16 %_0.sroa.0.0.i, 0 
        28:  %5 = insertvalue { i16, i16 } %4, i16 %_0.sroa.5.0.i, 1 
        29:  ret { i16, i16 } %5 
        30: } 
        31:  
        32: ; Function Attrs: nonlazybind uwtable 
        33: define void @vec_extend_via_iter_repeat_n(ptr dead_on_unwind noalias nocapture noundef writable writeonly sret([24 x i8]) align 8 dereferenceable(24) %_0) unnamed_addr #1 personality ptr @rust_eh_personality { 
        34: start: 
        35:  %0 = load volatile i8, ptr @__rust_no_alloc_shim_is_unstable, align 1, !noalias !7 
        36:  %_0.i.i.i.i.i = tail call noalias noundef dereferenceable_or_null(1234) ptr @__rust_alloc(i64 noundef 1234, i64 noundef 1) #7, !noalias !7 
        37:  %.not.i = icmp eq ptr %_0.i.i.i.i.i, null 
        38:  br i1 %.not.i, label %bb3.i, label %bb4 
        39:  
        40: bb3.i: ; preds = %start 
        41: ; call alloc::raw_vec::handle_error 
        42:  tail call void @_RNvNtCscRjjaTpji5P_5alloc7raw_vec12handle_error(i64 noundef 1, i64 1234, ptr noalias noundef nonnull readonly align 8 dereferenceable(24) @alloc_c9b9d5d510259832d9dc24c4ff1ee7cf) #8 
        43:  unreachable 
        44:  
        45: bb4: ; preds = %start 
        46:  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 1 dereferenceable(1234) %_0.i.i.i.i.i, i8 42, i64 1234, i1 false), !noalias !10 
        47:  store i64 1234, ptr %_0, align 8 
        48:  %v.sroa.5.0._0.sroa_idx = getelementptr inbounds i8, ptr %_0, i64 8 
        49:  store ptr %_0.i.i.i.i.i, ptr %v.sroa.5.0._0.sroa_idx, align 8 
        50:  %v.sroa.6.0._0.sroa_idx = getelementptr inbounds i8, ptr %_0, i64 16 
        51:  store i64 1234, ptr %v.sroa.6.0._0.sroa_idx, align 8 
        52:  ret void 
        53: } 
        54:  
        55: ; Function Attrs: mustprogress nofree norecurse nosync nounwind nonlazybind willreturn memory(argmem: write) uwtable 
        56: define void @array_repeat_not_copy(ptr dead_on_unwind noalias nocapture noundef writable writeonly sret([16 x i8]) align 2 dereferenceable(16) %_0, i16 noundef %item) unnamed_addr #2 personality ptr @rust_eh_personality { 
        57: start: 
        58:  %0 = insertelement <8  [...]

2024-11-30 23:12 UTC, Soveu commented
@scottmcm @Amanieu its ready

2024-11-30 23:15 UTC, Soveu commented
@rustbot label +S-waiting-on-review -S-waiting-on-author

2024-12-01 11:38 UTC, paolobarbolini commented
FYI we're also playing around with this change at #133662 since Compiler Explorer showed that the two MRs combined made `Vec::resize` slightly better. We'll see how the perf run goes.

2024-12-01 17:12 UTC, Folyd commented
Nice, this reminds me of my article on Rust Magazine:  [VecDeque::resize() optimization
](https://rustmagazine.org/issue-1/vecdeque-resize-optimization/#alternative?).

2025-03-22 13:38 UTC, paolobarbolini commented
Any news? Also #138833 may create a merge conflict with this.

2025-05-03 19:42 UTC, Amanieu commented
r? @scottmcm

2025-05-16 02:41 UTC, scottmcm requested changes
This looks basically good to me, though I did see one thing that I put above.

Can you please rebase to resolve the merge conflict, then mark this ready again?

@rustbot author

2025-05-16 20:52 UTC, Soveu commented
@rustbot ready
@scottmcm

2025-05-16 21:34 UTC, scottmcm approved these changes

2025-05-16 23:37 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-distcheck`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/15078737040/job/42391641800) [(plain)](https://github.com/rust-lang-ci/rust/commit/1c48265d684a5d8ded244b637cc160ce6a91446c/checks/42391641800/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
failures:

---- [codegen] tests/codegen/iter-repeat-n-trivial-drop.rs stdout ----

error: verification with 'FileCheck' failed
status: exit status: 1
command: "/checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/llvm/build/bin/FileCheck" "--input-file" "/checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll" "/checkout/tests/codegen/iter-repeat-n-trivial-drop.rs" "--check-prefix=CHECK" "--allow-unused-prefixes" "--dump-input-context" "100"
stdout: none
--- stderr -------------------------------
/checkout/tests/codegen/iter-repeat-n-trivial-drop.rs:29:17: error: CHECK-NEXT: is not on the line after the previous match
 // CHECK-NEXT: %[[DEC:.+]] = add i64 %[[COUNT]], -1
                ^
/checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll:19:2: note: 'next' match was here
 %2 = add i64 %0, -1
 ^
/checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll:17:7: note: previous match ended here
bb8.i: ; preds = %start
      ^
/checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll:18:1: note: non-matching line after previous match is here
 %1 = getelementptr inbounds nuw i8, ptr %it, i64 8
^

Input file: /checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll
Check file: /checkout/tests/codegen/iter-repeat-n-trivial-drop.rs

-dump-input=help explains the following input dump.

Input was:
<<<<<<
         1: ; ModuleID = 'iter_repeat_n_trivial_drop.80fa96dad9145ebd-cgu.0' 
         2: source_filename = "iter_repeat_n_trivial_drop.80fa96dad9145ebd-cgu.0" 
         3: target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128" 
         4: target triple = "x86_64-unknown-linux-gnu" 
         5:  
         6: @__rust_no_alloc_shim_is_unstable = external global i8 
         7: @alloc_3e3222eab6a509f29fa54d8acd188f56 = private unnamed_addr constant [53 x i8] c"/checkout/tests/codegen/iter-repeat-n-trivial-drop.rs", align 1 
         8: @alloc_8e75433513d2c9e77591417f09572823 = private unnamed_addr constant <{ ptr, [16 x i8] }> <{ ptr @alloc_3e3222eab6a509f29fa54d8acd188f56, [16 x i8] c"5\00\00\00\00\00\00\007\00\00\00\11\00\00\00" }>, align 8 
         9:  
        10: ; Function Attrs: mustprogress nofree norecurse nosync nounwind nonlazybind willreturn memory(argmem: readwrite) uwtable 
        11: define { i16, i16 } @iter_repeat_n_next(ptr noalias nocapture noundef align 8 dereferenceable(16) %it) unnamed_addr #0 { 
        12: start: 
        13:  %0 = load i64, ptr %it, align 8, !alias.scope !3, !noundef !6 
        14:  %.not.i = icmp eq i64 %0, 0 
        15:  br i1 %.not.i, label %"_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17h8ab06ec64b70bf55E.exit", label %bb8.i 
        16:  
        17: bb8.i: ; preds = %start 
        18:  %1 = getelementptr inbounds nuw i8, ptr %it, i64 8 
        19:  %2 = add i64 %0, -1 
next:29      !~~~~~~~~~~~~~~~~~~  error: match on wrong line
        20:  %3 = load i16, ptr %1, align 8, !alias.scope !3 
        21:  store i64 %2, ptr %it, align 8, !alias.scope !3 
        22:  br label %"_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17h8ab06ec64b70bf55E.exit" 
        23:  
        24: "_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17h8ab06ec64b70bf55E.exit": ; preds = %start, %bb8.i 
        25:  %_0.sroa.5.0.i = phi i16 [ undef, %start ], [ %3, %bb8.i ] 
        26:  %_0.sroa.0.0.i = phi i16 [ 0, %start ], [ 1, %bb8.i ] 
        27:  %4 = insertvalue { i16, i16 } poison, i16 %_0.sroa.0.0.i, 0 
        28:  %5 = insertvalue { i16, i16 } %4, i16 %_0.sroa.5.0.i, 1 
        29:  ret { i16, i16 } %5 
        30: } 
        31:  
        32: ; Function Attrs: nonlazybind uwtable 
        33: define void @vec_extend_via_iter_repeat_n(ptr dead_on_unwind noalias nocapture noundef writable writeonly sret([24 x i8]) align 8 dereferenceable(24) %_0) unnamed_addr #1 personality ptr @rust_eh_personality { 
        34: start: 
        35:  %0 = load volatile i8, ptr @__rust_no_alloc_shim_is_unstable, align 1, !noalias !7 
        36: ; call __rustc::__rust_alloc 
        37:  %_0.i.i.i.i.i = tail call noalias noundef dereferenceable_or_null(1234) ptr @_RNvCsbxRaPc9pbXp_7___rustc12___rust_alloc(i64 noundef range(i64 1, 0) 1234, i64 noundef range(i64 1, -9223372036854775807) 1) #7, !noalias !7 
        38:  %1 = icmp eq ptr %_0.i.i.i.i.i, null 
        39:  br i1 %1, label %bb3.i, label %"_ZN5alloc7raw_vec20RawVecInner$LT$A$GT$16with_capacity_in17h1cad46dddf16691bE.exit", !prof !10 
        40:  
        41: bb3.i: ; preds = %start 
        42: ; call alloc::raw_vec::handle_error 
        43:  tail call void @_ZN5alloc7raw_vec12handle_error17h544adfcf785f3fbdE(i64 noundef 1, i64 1234, ptr noalias noundef nonnull readonly align 8 dereferenceable(24) @alloc_8e75433513d2c9e77591417f09572823) #8 
        44:  unreachable 
        45:  
        46: "_ZN5alloc7raw_vec20RawVecInner$LT$A$GT$16with_capacity_in17h1cad46dddf16691bE.exit": ; preds = %start 
        47:  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 1 dereferenceable(1234) %_0.i.i.i.i.i, i8 42, i64 1234, i1 false), !noalias !11 
        48:  store i64 1234, ptr %_0, align 8 
        49:  %v.sroa.4.0._0.sroa_idx = getelementptr inbounds nuw i8, ptr %_0, i64 8 
        50:  store ptr %_0.i.i.i.i.i, ptr %v.sroa.4.0._0.sroa_idx, align 8 
        51:  %v.sroa.5.0._0.sroa_idx = getelementptr inbounds nuw i8, ptr %_0, i64 16 
        52:  store i64 1234, ptr %v.sroa.5.0._0.sroa_idx, align 8 
        53:  ret void 
        54: } 
        55:  
        56: ; Function Attrs: mustprogress nofree norecurse nosync nounwind nonlazybind willreturn memory(argmem: write) uwtable 
        57: define void @array_repeat_not_copy(ptr dead_on_unwind noalias nocapture noundef writable writeonly sret([16 x i8]) align 2 dereferenceable(16) initializes((0, 16)) %_0, i16 noundef %item) unnamed_addr #2 personality ptr @rust_eh_personality { 
        58: start: 
        59:  %0 = insertelement <8 x i16> poison, i16 %item, i64 0 
        60:  %1 = shufflevector <8 x i16> %0, <8 x i16> poison, <8 x i32> zeroinitializer 
        61:  store <8 x i16> %1, ptr %_0, align 2, !alias.scope !22 
        62:  ret void 
        63: } 
        64:  
        65: ; Function Attrs: nounwind nonlazybind uwtable 
        66: declare noundef range(i32 0, 10) i32 @rust_eh_personality(i32 noundef, i32 noundef, i64 noundef, ptr noundef, ptr noundef) unnamed_addr #3 
        67:  
        68: ; Function Attrs: mustprogress nocallback nofree nounwind willreturn memory(argmem: write) 
        69: declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg) #4 
        70:  
        71: ; __rustc::__rust_alloc 
        72: ; Function Attrs: nounwind nonlazybind allockind("alloc,uninitialized,aligned") allocsize(0) uwtable 
        73: declare noalias noundef ptr @_RNvCsbxRaPc9pbXp_7___rustc12___rust_alloc(i64 noundef, i64 allocalign noundef) unnamed_addr #5 
        74:  
        75: ; alloc::raw_vec::handle_error 
        76: ; Function Attrs: cold minsize noreturn no [...]

2025-05-17 09:44 UTC, Soveu commented
@scottmcm sorry, I did not notice, that codegen does not run on stage 0 tests... but on the good side, it was only a reorder of one instruction.

2025-05-18 20:52 UTC, fmease commented
Failed in rollup: https://github.com/rust-lang/rust/pull/141233#issuecomment-2889199641
@bors r-

2025-05-18 21:38 UTC, fmease commented
(x86_64-gnu-distcheck) @bors try

2025-05-18 22:28 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-distcheck`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/actions/runs/15100318550/job/42440363003) [(plain)](https://github.com/rust-lang-ci/rust/commit/e3450c66373dce0811d3e6c0b25ee2c06bee5c97/checks/42440363003/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
file:.git/config remote.origin.url=https://github.com/rust-lang-ci/rust
file:.git/config remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config gc.auto=0
file:.git/config http.https://github.com/.extraheader=AUTHORIZATION: basic ***
file:.git/config branch.try.remote=origin
file:.git/config branch.try.merge=refs/heads/try
file:.git/config submodule.library/backtrace.active=true
file:.git/config submodule.library/backtrace.url=https://github.com/rust-lang/backtrace-rs.git
file:.git/config submodule.library/stdarch.active=true
file:.git/config submodule.library/stdarch.url=https://github.com/rust-lang/stdarch.git
file:.git/config submodule.src/doc/book.active=true
---
failures:

---- [codegen] tests/codegen/iter-repeat-n-trivial-drop.rs stdout ----

error: verification with 'FileCheck' failed
status: exit status: 1
command: "/checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/llvm/build/bin/FileCheck" "--input-file" "/checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll" "/checkout/tests/codegen/iter-repeat-n-trivial-drop.rs" "--check-prefix=CHECK" "--allow-unused-prefixes" "--dump-input-context" "100"
stdout: none
--- stderr -------------------------------
/checkout/tests/codegen/iter-repeat-n-trivial-drop.rs:29:17: error: CHECK-NEXT: is not on the line after the previous match
 // CHECK-NEXT: %[[DEC:.+]] = add i64 %[[COUNT]], -1
                ^
/checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll:19:2: note: 'next' match was here
 %2 = add i64 %0, -1
 ^
/checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll:17:7: note: previous match ended here
bb8.i: ; preds = %start
      ^
/checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll:18:1: note: non-matching line after previous match is here
 %1 = getelementptr inbounds nuw i8, ptr %it, i64 8
^

Input file: /checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/test/codegen/iter-repeat-n-trivial-drop/iter-repeat-n-trivial-drop.ll
Check file: /checkout/tests/codegen/iter-repeat-n-trivial-drop.rs

-dump-input=help explains the following input dump.

Input was:
<<<<<<
         1: ; ModuleID = 'iter_repeat_n_trivial_drop.80fa96dad9145ebd-cgu.0' 
         2: source_filename = "iter_repeat_n_trivial_drop.80fa96dad9145ebd-cgu.0" 
         3: target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128" 
         4: target triple = "x86_64-unknown-linux-gnu" 
         5:  
         6: @__rust_no_alloc_shim_is_unstable = external global i8 
         7: @alloc_3e3222eab6a509f29fa54d8acd188f56 = private unnamed_addr constant [53 x i8] c"/checkout/tests/codegen/iter-repeat-n-trivial-drop.rs", align 1 
         8: @alloc_8e75433513d2c9e77591417f09572823 = private unnamed_addr constant <{ ptr, [16 x i8] }> <{ ptr @alloc_3e3222eab6a509f29fa54d8acd188f56, [16 x i8] c"5\00\00\00\00\00\00\007\00\00\00\11\00\00\00" }>, align 8 
         9:  
        10: ; Function Attrs: mustprogress nofree norecurse nosync nounwind nonlazybind willreturn memory(argmem: readwrite) uwtable 
        11: define { i16, i16 } @iter_repeat_n_next(ptr noalias nocapture noundef align 8 dereferenceable(16) %it) unnamed_addr #0 { 
        12: start: 
        13:  %0 = load i64, ptr %it, align 8, !alias.scope !3, !noundef !6 
        14:  %.not.i = icmp eq i64 %0, 0 
        15:  br i1 %.not.i, label %"_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17heba7fa00778d1756E.exit", label %bb8.i 
        16:  
        17: bb8.i: ; preds = %start 
        18:  %1 = getelementptr inbounds nuw i8, ptr %it, i64 8 
        19:  %2 = add i64 %0, -1 
next:29      !~~~~~~~~~~~~~~~~~~  error: match on wrong line
        20:  %3 = load i16, ptr %1, align 8, !alias.scope !3 
        21:  store i64 %2, ptr %it, align 8, !alias.scope !3 
        22:  br label %"_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17heba7fa00778d1756E.exit" 
        23:  
        24: "_ZN106_$LT$core..iter..sources..repeat_n..RepeatN$LT$A$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17heba7fa00778d1756E.exit": ; preds = %start, %bb8.i 
        25:  %_0.sroa.5.0.i = phi i16 [ undef, %start ], [ %3, %bb8.i ] 
        26:  %_0.sroa.0.0.i = phi i16 [ 0, %start ], [ 1, %bb8.i ] 
        27:  %4 = insertvalue { i16, i16 } poison, i16 %_0.sroa.0.0.i, 0 
        28:  %5 = insertvalue { i16, i16 } %4, i16 %_0.sroa.5.0.i, 1 
        29:  ret { i16, i16 } %5 
        30: } 
        31:  
        32: ; Function Attrs: nonlazybind uwtable 
        33: define void @vec_extend_via_iter_repeat_n(ptr dead_on_unwind noalias nocapture noundef writable writeonly sret([24 x i8]) align 8 dereferenceable(24) %_0) unnamed_addr #1 personality ptr @rust_eh_personality { 
        34: start: 
        35:  %0 = load volatile i8, ptr @__rust_no_alloc_shim_is_unstable, align 1, !noalias !7 
        36: ; call __rustc::__rust_alloc 
        37:  %_0.i.i.i.i.i = tail call noalias noundef dereferenceable_or_null(1234) ptr @_RNvCsjo78DlXnSdE_7___rustc12___rust_alloc(i64 noundef range(i64 1, 0) 1234, i64 noundef range(i64 1, -9223372036854775807) 1) #7, !noalias !7 
        38:  %1 = icmp eq ptr %_0.i.i.i.i.i, null 
        39:  br i1 %1, label %bb3.i, label %"_ZN5alloc7raw_vec20RawVecInner$LT$A$GT$16with_capacity_in17h498ad11235a8f418E.exit", !prof !10 
        40:  
        41: bb3.i: ; preds = %start 
        42: ; call alloc::raw_vec::handle_error 
        43:  tail call void @_ZN5alloc7raw_vec12handle_error17hd59783746b703129E(i64 noundef 1, i64 1234, ptr noalias noundef nonnull readonly align 8 dereferenceable(24) @alloc_8e75433513d2c9e77591417f09572823) #8 
        44:  unreachable 
        45:  
        46: "_ZN5alloc7raw_vec20RawVecInner$LT$A$GT$16with_capacity_in17h498ad11235a8f418E.exit": ; preds = %start 
        47:  tail call void @llvm.memset.p0.i64(ptr noundef nonnull align 1 dereferenceable(1234) %_0.i.i.i.i.i, i8 42, i64 1234, i1 false), !noalias !11 
        48:  store i64 1234, ptr %_0, align 8 
        49:  %v.sroa.4.0._0.sroa_idx = getelementptr inbounds nuw i8, ptr %_0, i64 8 
        50:  store ptr %_0.i.i.i.i.i, ptr %v.sroa.4.0._0.sroa_idx, align 8 
        51:  %v.sroa.5.0._0.sroa_idx = getelementptr inbounds nuw i8, ptr %_0, i64 16 
        52:  store i64 1234, ptr %v.sroa.5.0._0.sroa_idx, align 8 
        53:  ret void 
        54: } 
        55:  
        56: ; Function Attrs: mustprogress nofree norecurse nosync nounwind nonlazybind willreturn memory(argmem: write) uwtable 
        57: define void @array_repeat_not_copy(ptr dead_on_unwind noalias nocapture noundef writable writeonly sret([16 x i8]) align 2 dereferenceable(16) initializes((0, 16)) %_0, i16 noundef %item) unnamed_addr #2 personality ptr @rust_eh_personality { 
        58: start: 
        59:  %0 = insertelement <8 x i16> poison, i16 %item, i64 0 
        60:  %1 = shufflevector <8 x i16> %0, <8 x i16> poison, <8 x i32> zeroinitializer 
        61:  store <8 x i16> %1, ptr %_0, align 2, !alias.scope !22 
        62:  ret void 
        63: } 
        64:  
        65: ; Function Attrs: nounwind nonlazybind uwtable 
        66: declare noundef range(i32 0, 10) i32 @rust_eh_personality(i32 noundef, i32 [...]

2025-05-19 16:39 UTC, Soveu commented
@scottmcm are you sure the attribute for stable representation works? Seems like I can reproduce this error by swapping `count` and `element` in `RepeatNInner

2025-05-19 16:50 UTC, Soveu commented
Seems like depending on which field is first, `getelementptr` either gets emitted right at the beginning of the function or right after `NOT_EMPTY` branch

2025-05-26 21:14 UTC, Soveu commented
@rustbot ready

2025-06-06 09:36 UTC, paolobarbolini commented
Is there anything we can do to get this over the finish line @scottmcm?

2025-06-08 04:55 UTC, scottmcm commented
@bors r+

2025-06-08 05:32 UTC, scottmcm commented
This failed the run-make tests?!?  That's weird...

@bors retry

2025-06-08 05:47 UTC, Soveu commented
hmm, yeah, it some weird errors in `test-various` - `can't find crate for std/core`

2025-06-08 10:01 UTC, Soveu commented
> 💔 Test failed - [checks-actions](https://github.com/rust-lang/rust/actions/runs/15516990290/job/43685604145)

same issue as above :thinking:

2025-06-08 22:41 UTC, scottmcm commented
Re-running CI, out of curiosity...

2025-06-09 17:30 UTC, fmease commented
The failures you're seeing possibly have the same root cause as https://rust-lang.zulipchat.com/#narrow/channel/326414-t-infra.2Fbootstrap/topic/aarch64-apple.20try.20job.20doesn.27t.20work/with/522659759 but I could be wrong (different target I think (I don't remember where `test-various` runs)). The symptom looks similar (wrong version of `std`, likely the stage0 beta `std`).

We should wait for https://github.com/rust-lang/rust/pull/142241 to get merged and then we can retry.

2025-06-09 18:22 UTC, fmease commented
@bors2 try jobs=test-various parent=00b526212bbdd68872d6f964fcc9a14a66c36fd8

2025-06-09 19:49 UTC, fmease commented
@Soveu It looks like we now have a true failure, could you look at the failure, fix it if truly true and rebase, then we can try again? Thanks!

2025-06-09 21:29 UTC, Soveu commented
uhh, another codegen failure...

2025-06-09 21:33 UTC, Soveu commented
looks like load and store changed order, I'll fix it tommorow

2025-06-13 20:34 UTC, Soveu commented
@bors2 try jobs=test-various

2025-06-13 20:41 UTC, Soveu commented
@rustbot ready

2025-06-13 20:44 UTC, fmease commented
@bors2 try jobs=test-various

2025-06-14 06:29 UTC, Soveu commented
@scottmcm LGTM

2025-06-18 02:49 UTC, scottmcm commented
Sure, let's try it again...
@bors r+

2025-06-18 06:17 UTC, merged

2025-06-18 16:13 UTC, rust-timer commented
Finished benchmarking commit (27733d46d79f4eb92e240fbba502c43022665735): [comparison URL](https://perf.rust-lang.org/compare.html?start=77ec48f5642ee1aa451d270f11f308c297f55f76&end=27733d46d79f4eb92e240fbba502c43022665735&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=77ec48f5642ee1aa451d270f11f308c297f55f76&end=27733d46d79f4eb92e240fbba502c43022665735&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=77ec48f5642ee1aa451d270f11f308c297f55f76&end=27733d46d79f4eb92e240fbba502c43022665735&stat=max-rss)
<details>
<summary>Results (primary -0.7%, secondary 1.5%)</summary>

A less reliable metric. May be of interest, but not used to determine the overall result above.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.9%  | [0.9%, 0.9%]   | 1     |
| Regressions ❌ <br /> (secondary)  | 1.5%  | [1.5%, 1.5%]   | 1     |
| Improvements ✅ <br /> (primary)   | -2.3% | [-2.3%, -2.3%] | 1     |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -0.7% | [-2.3%, 0.9%]  | 2     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=77ec48f5642ee1aa451d270f11f308c297f55f76&end=27733d46d79f4eb92e240fbba502c43022665735&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=77ec48f5642ee1aa451d270f11f308c297f55f76&end=27733d46d79f4eb92e240fbba502c43022665735&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 692.662s -> 693.071s (0.06%)
**Artifact size**: 372.09 MiB -> 372.10 MiB (0.00%)