Allow multiple suggestions for malformed crate_type attribute
rust-lang/rust pull request #130923
Opened 2024-09-27 08:30 UTC by Blindspot22

Solves these #61288

2024-09-27 08:32 UTC, lnicola commented
I think you got the wrong file, #61288 points to [rust/src/libsyntax/feature_gate.rs](https://github.com/rust-lang/rust/blob/a6ce9b312354cadb046be40398b7e28b616bad28/src/libsyntax/feature_gate.rs#L873-L877).

2024-09-27 10:27 UTC, Blindspot22 commented
> I think you got the wrong file, #61288 points to [rust/src/libsyntax/feature_gate.rs](https://github.com/rust-lang/rust/blob/a6ce9b312354cadb046be40398b7e28b616bad28/src/libsyntax/feature_gate.rs#L873-L877).

I think since the last time this issue was made, refactors have been made and the `libsyntax` folder doesn't exist or if isn't found under the `src` directory and 

> I think you got the wrong file, #61288 points to [rust/src/libsyntax/feature_gate.rs](https://github.com/rust-lang/rust/blob/a6ce9b312354cadb046be40398b7e28b616bad28/src/libsyntax/feature_gate.rs#L873-L877).

Hello @lnicola to begin with, I think that the path isn't valid again cause a lot of changes have been made since the creation of these issue. 

The must have been some refactor cause the `libsyntax` directory doesn't seem to exit again and the `feature_gate.rs` file is now found in this path [`rust/compiler/rustc_ast_passes/src/feature_gate.rs`](https://github.com/rust-lang/rust/blob/master/compiler/rustc_ast_passes/src/feature_gate.rs) rather.

Moreover if you look into that `feature_gate.rs` file you will see that the `pub struct AttributeTemplate` implementation was removed from it.

2024-09-27 10:28 UTC, Blindspot22 commented
After a couple of diggings i found the `pub struct AttributeTemplate` implementation in the [`inert_attr_macro.rs`](https://github.com/rust-lang/rust/blob/master/src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs) file 

![Screenshot from 2024-09-27 11-23-01](https://github.com/user-attachments/assets/ed0468aa-99bd-4342-af79-1584e9a44fce)


And if you look carefully as from line 21 to 28 you will see it was done by  Lukas Wirth   3 years ago same as done here [src/libsyntax/feature_gate.rs](https://github.com/rust-lang/rust/blob/a6ce9b312354cadb046be40398b7e28b616bad28/src/libsyntax/feature_gate.rs#L873-L877)

2024-09-27 10:29 UTC, lnicola commented
@Blindspot22 rust-analyzer is in most part a reimplementation of the compiler, so you should never need to modify r-a to fix a compiler issue.

2024-09-27 10:33 UTC, Blindspot22 commented
> @Blindspot22 rust-analyzer is in most part a reimplementation of the compiler, so you should never need to modify r-a to fix a compiler issue.

Okay thanks for that info :+1:

2024-09-27 10:51 UTC, jieyouxu commented
@Blindspot22 you can find where this diagnostic is emitted in rustc with [`-Ztreat-err-as-bug=1`]

```
gh-jieyouxu@dev-desktop-eu-1:~$ rustc +stage1 test.rs -Ztreat-err-as-bug=1
error: internal compiler error: malformed `crate_type` attribute input
 --> test.rs:1:1
  |
1 | #![crate_type]
  | ^^^^^^^^^^^^^^ help: must be of the form: `#![crate_type = "bin|lib|..."]`

thread 'rustc' panicked at compiler/rustc_errors/src/lib.rs:1763:17:
aborting due to `-Z treat-err-as-bug=1`
stack backtrace:
[irrelevant lines trimmed]
  30:     0xf95c0a21e72c - rustc_parse[4ae35f3312fdabf2]::validate_attr::emit_malformed_attribute
                               at /home/gh-jieyouxu/rust/compiler/rustc_parse/src/validate_attr.rs:272:9
```

2024-09-27 11:00 UTC, jieyouxu commented
Might be able to massage https://github.com/rust-lang/rust/blob/b9dc4a30e116c6bd1b873fa79379ea70e102c47b/compiler/rustc_parse/src/validate_attr.rs#L237

to produce extra help by matching on `rustc_session::CrateType` if the attribute under check is `sym::crate_type`.

2024-09-27 11:57 UTC, Dylan-DPC commented
@bors try

2024-11-12 12:06 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/11796468671/job/32858394370) [(plain)](https://github.com/rust-lang/rust/commit/32d564ba34e0a6f1d1be7201515456658c12448a/checks/32858394370/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 47)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 50)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 63)
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
- LL | #![crate_type = "bin"]
-    |
- LL | #![crate_type = "lib"]
-    | 
- LL | #![crate_type = "..."]
+    | ^^^^^^^^^^^^^^ help: must be of the form: `#![crate_type = "bin|lib|..."]`
14 error: aborting due to 1 previous error
+ 
+ 



The actual stderr differed from the expected stderr.
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args no_crate_type.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/no_crate_type.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/no_crate_type" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers"
--- stderr -------------------------------
error: malformed `crate_type` attribute input
##[error]  --> /checkout/tests/ui/no_crate_type.rs:2:1
   |
   |
LL | #![crate_type]  //~ ERROR malformed `crate_type` attribute
   | ^^^^^^^^^^^^^^ help: must be of the form: `#![crate_type = "bin|lib|..."]`
error: aborting due to 1 previous error
------------------------------------------


```

</details>

2024-12-14 17:12 UTC, alex-semenyuk commented
@Blindspot22
From wg-triage. Any updates on this PR?

2024-12-16 10:21 UTC, Blindspot22 commented
> @Blindspot22 From wg-triage. Any updates on this PR?

Hello @alex-semenyuk. Sorry I have been kind of busy lately, working on this right away :+1:

2024-12-16 11:28 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12351334275/job/34466102946) [(plain)](https://github.com/rust-lang/rust/commit/7d0e441e2bcdfaa2651aff5e2549e1183a26a17a/checks/34466102946/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 exporting to docker image format
#16 sending tarball 29.9s done
#16 DONE 42.8s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
- LL | #![crate_type = "bin"]
-    |
- LL | #![crate_type = "lib"]
-    | 
- LL | #![crate_type = "..."]
+    | ^^^^^^^^^^^^^^ help: must be of the form: `#![crate_type = "bin|lib|..."]`
14 error: aborting due to 1 previous error
+ 
+ 



The actual stderr differed from the expected stderr.
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args no_crate_type.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/no_crate_type.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/no_crate_type" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers"
--- stderr -------------------------------
error: malformed `crate_type` attribute input
##[error]  --> /checkout/tests/ui/no_crate_type.rs:2:1
   |
   |
LL | #![crate_type]  //~ ERROR malformed `crate_type` attribute
   | ^^^^^^^^^^^^^^ help: must be of the form: `#![crate_type = "bin|lib|..."]`
error: aborting due to 1 previous error
------------------------------------------


```

</details>

2024-12-16 11:31 UTC, Blindspot22 commented
Hey @jieyouxu I'm having this issue. Meanwhile we're intentionally testing a malformed attribute.
![Screenshot from 2024-12-16 11-51-35](https://github.com/user-attachments/assets/6564a71c-bfb2-4bd1-8e36-d5a18534a7a1)

We actually want that each time someone uses `#![crate_type]`. The person should specify if its either "bin" or "lib" they wanna attribute to it with.

2024-12-16 11:35 UTC, Blindspot22 commented
It obviously needs to be a failing test with a .stderr
![Screenshot from 2024-12-16 12-03-33](https://github.com/user-attachments/assets/878063bc-ef37-4cb9-8e71-06d96155c968)
Which i further enhanced for easy understanding and clearer for users to correct their code. But the above CI :roll_eyes: keeps failing

2024-12-16 14:17 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12354256301/job/34475213876) [(plain)](https://github.com/rust-lang/rust/commit/abe0241de8dc01c57c1901f2253bbd23a3075050/checks/34475213876/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking hir-expand v0.0.0 (/checkout/src/tools/rust-analyzer/crates/hir-expand)
error[E0308]: mismatched types
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:118:43
    |
50  |     (List: $descr: expr) => { template!(@ false, Some($descr), None) };
...
...
118 |     ungated!(cfg, Normal, template!(List: "predicate"), DuplicatesOk),
    |                                           ^^^^^^^^^^^ expected `&[&str]`, found `&str`
    |
    = note: expected reference `&[&str]`
help: the type constructed contains `&'static str` due to the type of the argument passed
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:50:50
    |
48  | / macro_rules! template {
48  | / macro_rules! template {
49  | |     (Word) => { template!(@ true, None, None) };
50  | |     (List: $descr: expr) => { template!(@ false, Some($descr), None) };
    | |                                                  ^^^^^^^^^^^^
51  | |     (NameValueStr: $descr: expr) => { template!(@ false, None, Some($descr)) };
64  | |     };
65  | | }
    | |_- in this expansion of `template!`
...
...
118 |       ungated!(cfg, Normal, template!(List: "predicate"), DuplicatesOk),
    |                             |               |
    |                             |               this argument influences the type of `Some`
    |                             in this macro invocation
note: tuple variant defined here
---

error[E0308]: mismatched types
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:119:48
    |
50  |     (List: $descr: expr) => { template!(@ false, Some($descr), None) };
...
...
119 |     ungated!(cfg_attr, Normal, template!(List: "predicate, attr1, attr2, ..."), DuplicatesOk),
    |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&[&str]`, found `&str`
    |
    = note: expected reference `&[&str]`
help: the type constructed contains `&'static str` due to the type of the argument passed
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:50:50
    |
48  | / macro_rules! template {
48  | / macro_rules! template {
49  | |     (Word) => { template!(@ true, None, None) };
50  | |     (List: $descr: expr) => { template!(@ false, Some($descr), None) };
    | |                                                  ^^^^^^^^^^^^
51  | |     (NameValueStr: $descr: expr) => { template!(@ false, None, Some($descr)) };
64  | |     };
65  | | }
    | |_- in this expansion of `template!`
...
...
119 |       ungated!(cfg_attr, Normal, template!(List: "predicate, attr1, attr2, ..."), DuplicatesOk),
    |                                  |               |
    |                                  |               this argument influences the type of `Some`
    |                                  in this macro invocation
note: tuple variant defined here
---

error[E0308]: mismatched types
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:125:31
    |
58  |         template!(@ true, Some($descr1), Some($descr2))
...
...
125 |         template!(Word, List: r#"expected = "reason""#, NameValueStr: "reason"), FutureWarnFollowing,
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^ expected `&[&str]`, found `&str`
    |
    = note: expected reference `&[&str]`
help: the type constructed contains `&'static str` due to the type of the argument passed
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:58:27
    |
48  | / macro_rules! template {
48  | / macro_rules! template {
49  | |     (Word) => { template!(@ true, None, None) };
50  | |     (List: $descr: expr) => { template!(@ false, Some($descr), None) };
51  | |     (NameValueStr: $descr: expr) => { template!(@ false, None, Some($descr)) };
...   |
58  | |         template!(@ true, Some($descr1), Some($descr2))
...   |
64  | |     };
65  | | }
    | |_- in this expansion of `template!`
    | |_- in this expansion of `template!`
...
125 |           template!(Word, List: r#"expected = "reason""#, NameValueStr: "reason"), FutureWarnFollowing,
    |           |                     |
    |           |                     this argument influences the type of `Some`
    |           in this macro invocation
note: tuple variant defined here
---

error[E0308]: mismatched types
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:132:55
    |
52  |     (Word, List: $descr: expr) => { template!(@ true, Some($descr), None) };
...
...
132 |     ungated!(macro_use, Normal, template!(Word, List: "name1, name2, ..."), WarnFollowingWordOnly),
    |                                                       ^^^^^^^^^^^^^^^^^^^ expected `&[&str]`, found `&str`
    |
    = note: expected reference `&[&str]`
help: the type constructed contains `&'static str` due to the type of the argument passed
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:52:55
    |
48  | / macro_rules! template {
48  | / macro_rules! template {
49  | |     (Word) => { template!(@ true, None, None) };
50  | |     (List: $descr: expr) => { template!(@ false, Some($descr), None) };
51  | |     (NameValueStr: $descr: expr) => { template!(@ false, None, Some($descr)) };
52  | |     (Word, List: $descr: expr) => { template!(@ true, Some($descr), None) };
...   |
64  | |     };
65  | | }
    | |_- in this expansion of `template!`
    | |_- in this expansion of `template!`
...
132 |       ungated!(macro_use, Normal, template!(Word, List: "name1, name2, ..."), WarnFollowingWordOnly),
    |                                   |                     |
    |                                   |                     this argument influences the type of `Some`
    |                                   in this macro invocation
note: tuple variant defined here
---

error[E0308]: mismatched types
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:134:58
    |
52  |     (Word, List: $descr: expr) => { template!(@ true, Some($descr), None) };
...
...
134 |     ungated!(macro_export, Normal, template!(Word, List: "local_inner_macros"), WarnFollowing),
    |                                                          ^^^^^^^^^^^^^^^^^^^^ expected `&[&str]`, found `&str`
    |
    = note: expected reference `&[&str]`
help: the type constructed contains `&'static str` due to the type of the argument passed
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:52:55
    |
48  | / macro_rules! template {
48  | / macro_rules! template {
49  | |     (Word) => { template!(@ true, None, None) };
50  | |     (List: $descr: expr) => { template!(@ false, Some($descr), None) };
51  | |     (NameValueStr: $descr: expr) => { template!(@ false, None, Some($descr)) };
52  | |     (Word, List: $descr: expr) => { template!(@ true, Some($descr), None) };
...   |
64  | |     };
65  | | }
    | |_- in this expansion of `template!`
    | |_- in this expansion of `template!`
...
134 |       ungated!(macro_export, Normal, template!(Word, List: "local_inner_macros"), WarnFollowing),
    |                                      |                     |
    |                                      |                     this argument influences the type of `Some`
    |                                      in this macro invocation
note: tuple variant defined here
---

error[E0308]: mismatched types
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:138:25
    |
50  |     (List: $descr: expr) => { template!(@ false, Some($descr), None) };
...
...
138 |         template!(List: "TraitName, /*opt*/ attributes(name1, name2, ...)") [...]

2024-12-17 03:21 UTC, nnethercote commented
@Blindspot22: You have modified the `AttributeTemplate` type, which is a good start. You also need to change all the places that use `AttributeTemplate` type. That's what the compile errors in the most recent CI run are about. Once that's working it makes sense to update the `.stderr` file with the expected test output.

Also, you should squash the commits into a single commit, because they don't make sense individually.

And the `tests/ui/no_crate_type.stderr` has somehow had its final newline removed. Might be a text editor issue?

2024-12-17 07:08 UTC, Blindspot22 commented
> @Blindspot22: You have modified the `AttributeTemplate` type, which is a good start. You also need to change all the places that use `AttributeTemplate` type. That's what the compile errors in the most recent CI run are about. Once that's working it makes sense to update the `.stderr` file with the expected test output.
> 
> Also, you should squash the commits into a single commit, because they don't make sense individually.
> 
> And the `tests/ui/no_crate_type.stderr` has somehow had its final newline removed. Might be a text editor issue?

2024-12-17 07:21 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12368071747/job/34517431481) [(plain)](https://github.com/rust-lang/rust/commit/abe0241de8dc01c57c1901f2253bbd23a3075050/checks/34517431481/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking pulldown-cmark v0.9.6
error[E0308]: mismatched types
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:118:43
    |
50  |     (List: $descr: expr) => { template!(@ false, Some($descr), None) };
...
...
118 |     ungated!(cfg, Normal, template!(List: "predicate"), DuplicatesOk),
    |                                           ^^^^^^^^^^^ expected `&[&str]`, found `&str`
    |
    = note: expected reference `&[&str]`
help: the type constructed contains `&'static str` due to the type of the argument passed
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:50:50
    |
48  | / macro_rules! template {
48  | / macro_rules! template {
49  | |     (Word) => { template!(@ true, None, None) };
50  | |     (List: $descr: expr) => { template!(@ false, Some($descr), None) };
    | |                                                  ^^^^^^^^^^^^
51  | |     (NameValueStr: $descr: expr) => { template!(@ false, None, Some($descr)) };
64  | |     };
65  | | }
    | |_- in this expansion of `template!`
...
...
118 |       ungated!(cfg, Normal, template!(List: "predicate"), DuplicatesOk),
    |                             |               |
    |                             |               this argument influences the type of `Some`
    |                             in this macro invocation
note: tuple variant defined here
---

error[E0308]: mismatched types
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:119:48
    |
50  |     (List: $descr: expr) => { template!(@ false, Some($descr), None) };
...
...
119 |     ungated!(cfg_attr, Normal, template!(List: "predicate, attr1, attr2, ..."), DuplicatesOk),
    |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&[&str]`, found `&str`
    |
    = note: expected reference `&[&str]`
help: the type constructed contains `&'static str` due to the type of the argument passed
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:50:50
    |
48  | / macro_rules! template {
48  | / macro_rules! template {
49  | |     (Word) => { template!(@ true, None, None) };
50  | |     (List: $descr: expr) => { template!(@ false, Some($descr), None) };
    | |                                                  ^^^^^^^^^^^^
51  | |     (NameValueStr: $descr: expr) => { template!(@ false, None, Some($descr)) };
64  | |     };
65  | | }
    | |_- in this expansion of `template!`
...
...
119 |       ungated!(cfg_attr, Normal, template!(List: "predicate, attr1, attr2, ..."), DuplicatesOk),
    |                                  |               |
    |                                  |               this argument influences the type of `Some`
    |                                  in this macro invocation
note: tuple variant defined here
---

error[E0308]: mismatched types
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:125:31
    |
58  |         template!(@ true, Some($descr1), Some($descr2))
...
...
125 |         template!(Word, List: r#"expected = "reason""#, NameValueStr: "reason"), FutureWarnFollowing,
    |                               ^^^^^^^^^^^^^^^^^^^^^^^^ expected `&[&str]`, found `&str`
    |
    = note: expected reference `&[&str]`
help: the type constructed contains `&'static str` due to the type of the argument passed
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:58:27
    |
48  | / macro_rules! template {
48  | / macro_rules! template {
49  | |     (Word) => { template!(@ true, None, None) };
50  | |     (List: $descr: expr) => { template!(@ false, Some($descr), None) };
51  | |     (NameValueStr: $descr: expr) => { template!(@ false, None, Some($descr)) };
...   |
58  | |         template!(@ true, Some($descr1), Some($descr2))
...   |
64  | |     };
65  | | }
    | |_- in this expansion of `template!`
    | |_- in this expansion of `template!`
...
125 |           template!(Word, List: r#"expected = "reason""#, NameValueStr: "reason"), FutureWarnFollowing,
    |           |                     |
    |           |                     this argument influences the type of `Some`
    |           in this macro invocation
note: tuple variant defined here
---

error[E0308]: mismatched types
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:132:55
    |
52  |     (Word, List: $descr: expr) => { template!(@ true, Some($descr), None) };
...
...
132 |     ungated!(macro_use, Normal, template!(Word, List: "name1, name2, ..."), WarnFollowingWordOnly),
    |                                                       ^^^^^^^^^^^^^^^^^^^ expected `&[&str]`, found `&str`
    |
    = note: expected reference `&[&str]`
help: the type constructed contains `&'static str` due to the type of the argument passed
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:52:55
    |
48  | / macro_rules! template {
48  | / macro_rules! template {
49  | |     (Word) => { template!(@ true, None, None) };
50  | |     (List: $descr: expr) => { template!(@ false, Some($descr), None) };
51  | |     (NameValueStr: $descr: expr) => { template!(@ false, None, Some($descr)) };
52  | |     (Word, List: $descr: expr) => { template!(@ true, Some($descr), None) };
...   |
64  | |     };
65  | | }
    | |_- in this expansion of `template!`
    | |_- in this expansion of `template!`
...
132 |       ungated!(macro_use, Normal, template!(Word, List: "name1, name2, ..."), WarnFollowingWordOnly),
    |                                   |                     |
    |                                   |                     this argument influences the type of `Some`
    |                                   in this macro invocation
note: tuple variant defined here
---

error[E0308]: mismatched types
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:134:58
    |
52  |     (Word, List: $descr: expr) => { template!(@ true, Some($descr), None) };
...
...
134 |     ungated!(macro_export, Normal, template!(Word, List: "local_inner_macros"), WarnFollowing),
    |                                                          ^^^^^^^^^^^^^^^^^^^^ expected `&[&str]`, found `&str`
    |
    = note: expected reference `&[&str]`
help: the type constructed contains `&'static str` due to the type of the argument passed
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:52:55
    |
48  | / macro_rules! template {
48  | / macro_rules! template {
49  | |     (Word) => { template!(@ true, None, None) };
50  | |     (List: $descr: expr) => { template!(@ false, Some($descr), None) };
51  | |     (NameValueStr: $descr: expr) => { template!(@ false, None, Some($descr)) };
52  | |     (Word, List: $descr: expr) => { template!(@ true, Some($descr), None) };
...   |
64  | |     };
65  | | }
    | |_- in this expansion of `template!`
    | |_- in this expansion of `template!`
...
134 |       ungated!(macro_export, Normal, template!(Word, List: "local_inner_macros"), WarnFollowing),
    |                                      |                     |
    |                                      |                     this argument influences the type of `Some`
    |                                      in this macro invocation
note: tuple variant defined here
---

error[E0308]: mismatched types
   --> src/tools/rust-analyzer/crates/hir-expand/src/inert_attr_macro.rs:138:25
    |
50  |     (List: $descr: expr) => { template!(@ false, Some($descr), None) };
...
...
138 |         template!(List: "TraitName, /*opt*/ attributes(name1, name2, ...)"), ErrorFollowing,
    |                         ^^ [...]

2025-01-24 10:09 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12947429010/job/36114001850) [(plain)](https://github.com/rust-lang/rust/commit/9fae9f4ed9de6b2a31b675b72bf5ab694892b052/checks/36114001850/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#21 exporting to docker image format
#21 sending tarball 28.8s done
#21 DONE 35.0s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
    |
note: while trying to match `,`
   --> compiler/rustc_feature/src/builtin_attrs.rs:236:17
    |
236 |     ($attr:ident, $typ:expr, $tpl:expr, $duplicates:expr, $encode_cross_crate:expr, $gate:ident, $msg:expr $(,)?) => {

error: expected expression, found keyword `in`
   --> compiler/rustc_feature/src/builtin_attrs.rs:922:34
    |
    |
276 |     ($attr:ident, $typ:expr, $tpl:expr, $duplicates:expr, $encode_cross_crate:expr, $msg:expr $(,)?) => {
    |                              --------- while parsing argument for this `expr` macro fragment
922 |         Support-more-suggestions-in-template-for-bad-attribute-use-#61288
    |                                  ^^ expected expression

error[E0308]: mismatched types
error[E0308]: mismatched types
   --> compiler/rustc_feature/src/builtin_attrs.rs:637:61
    |
172 |     (List: $descr: expr) => { template!(@ false, Some($descr), &[], None) };
...
...
637 |         rustc_deprecated_safe_2024, Normal, template!(List: r#"audit_that = "...""#),
    |                                                             ^^^^^^^^^^^^^^^^^^^^^^^ expected `&[&str]`, found `&str`
    |
    = note: expected reference `&[&str]`
help: the type constructed contains `&'static str` due to the type of the argument passed
   --> compiler/rustc_feature/src/builtin_attrs.rs:172:50
    |
170 | / macro_rules! template {
170 | / macro_rules! template {
171 | |     (Word) => { template!(@ true, None, &[], None) };
172 | |     (List: $descr: expr) => { template!(@ false, Some($descr), &[], None) };
    | |                                                  ^^^^^^^^^^^^
173 | |     (OneOf: $one_of: expr) => { template!(@ false, None, $one_of, None) };
185 | |     } };
186 | | }
    | |_- in this expansion of `template!`
...
...
637 |           rustc_deprecated_safe_2024, Normal, template!(List: r#"audit_that = "...""#),
    |                                               |               |
    |                                               |               this argument influences the type of `Some`
    |                                               in this macro invocation
note: tuple variant defined here
---

error[E0308]: mismatched types
   --> compiler/rustc_feature/src/builtin_attrs.rs:756:31
    |
175 |     (Word, List: $descr: expr) => { template!(@ true, Some($descr), &[], None) };
...
...
756 |         template!(Word, List: r#""...""#), DuplicatesOk,
    |                               ^^^^^^^^^^ expected `&[&str]`, found `&str`
    |
    = note: expected reference `&[&str]`
help: the type constructed contains `&'static str` due to the type of the argument passed
   --> compiler/rustc_feature/src/builtin_attrs.rs:175:55
    |
170 | / macro_rules! template {
170 | / macro_rules! template {
171 | |     (Word) => { template!(@ true, None, &[], None) };
172 | |     (List: $descr: expr) => { template!(@ false, Some($descr), &[], None) };
173 | |     (OneOf: $one_of: expr) => { template!(@ false, None, $one_of, None) };
174 | |     (NameValueStr: $descr: expr) => { template!(@ false, None, &[], Some($descr)) };
175 | |     (Word, List: $descr: expr) => { template!(@ true, Some($descr), &[], None) };
...   |
185 | |     } };
186 | | }
    | |_- in this expansion of `template!`
    | |_- in this expansion of `template!`
...
756 |           template!(Word, List: r#""...""#), DuplicatesOk,
    |           |                     |
    |           |                     this argument influences the type of `Some`
    |           in this macro invocation
note: tuple variant defined here
---

error[E0308]: mismatched types
   --> compiler/rustc_feature/src/builtin_attrs.rs:852:31
    |
175 |     (Word, List: $descr: expr) => { template!(@ true, Some($descr), &[], None) };
...
...
852 |         template!(Word, List: "feat1, feat2, ..."), DuplicatesOk, EncodeCrossCrate::No,
    |                               ^^^^^^^^^^^^^^^^^^^ expected `&[&str]`, found `&str`
    |
    = note: expected reference `&[&str]`
help: the type constructed contains `&'static str` due to the type of the argument passed
   --> compiler/rustc_feature/src/builtin_attrs.rs:175:55
    |
170 | / macro_rules! template {
170 | / macro_rules! template {
171 | |     (Word) => { template!(@ true, None, &[], None) };
172 | |     (List: $descr: expr) => { template!(@ false, Some($descr), &[], None) };
173 | |     (OneOf: $one_of: expr) => { template!(@ false, None, $one_of, None) };
174 | |     (NameValueStr: $descr: expr) => { template!(@ false, None, &[], Some($descr)) };
175 | |     (Word, List: $descr: expr) => { template!(@ true, Some($descr), &[], None) };
...   |
185 | |     } };
186 | | }
    | |_- in this expansion of `template!`
    | |_- in this expansion of `template!`
...
852 |           template!(Word, List: "feat1, feat2, ..."), DuplicatesOk, EncodeCrossCrate::No,
    |           |                     |
    |           |                     this argument influences the type of `Some`
    |           in this macro invocation
note: tuple variant defined here
```

</details>

2025-01-24 11:22 UTC, Blindspot22 commented
Hey @jieyouxu, a small look in on this might help :)

2025-01-26 22:34 UTC, nnethercote requested changes
This is getting closer, but there are still some problems.
- There is a merge commit, which isn't acceptable, as explained [here](https://github.com/rust-lang/rust/pull/130923#issuecomment-2612132083).
- Something weird has happened with the merge commit, which is causing the compile errors.
- The change to `rust/src/test/ui/no_crate_type.stderr` present in an earlier commit has been reverted in a later commit. This change is the motivation for this whole PR.
- The multiple commits still need to be squashed.
- Plus the various comments I have made below.

Please make sure these are fixed. If any of them are unclear, feel free to ask for clarification here or on Zulip.

2025-01-26 22:34 UTC, nnethercote commented on compiler/rustc_feature/src/builtin_attrs.rs
> -    ungated!(cfg, Normal, template!(List: "predicate"), DuplicatesOk, EncodeCrossCrate::Yes),
It would be nice if the macro inserted the `&[` and `]` for you, so you could just write `template!(List: "a", "b", "c")`. This shouldn't be hard to do.

2025-01-26 22:34 UTC, nnethercote commented on compiler/rustc_feature/src/builtin_attrs.rs
> +        template!(Word, List: &["expected = \"reason\""], NameValueStr: "reason"), FutureWarnFollowing,
It makes sense to keep the raw string here, i.e. `List: &[r#"expected = "reason""#]`.

2025-01-26 22:34 UTC, nnethercote commented on compiler/rustc_feature/src/builtin_attrs.rs
> +        macro_use, Normal, template!(Word, List: &["name1, name2, ..."]), WarnFollowingWordOnly,
Break this string into multiple strings, i.e. `"name1", "name2", "..."`.

Likewise for a lot of other cases below.

2025-01-26 22:34 UTC, nnethercote commented on compiler/rustc_feature/src/builtin_attrs.rs
> +        warn, Normal, template!(List: &["lint1", "lint2", "...", "/*opt*/ reason = \"...\""]),
Again, a raw string is reasonable for the `reason` string. And likewise for numerous examples below.

2025-01-26 22:34 UTC, nnethercote commented on compiler/rustc_feature/src/builtin_attrs.rs
> +    ),
Why is this added?

2025-01-26 22:34 UTC, nnethercote commented on compiler/rustc_feature/src/builtin_attrs.rs
> +
I don't understand this change. Is it intentional?

2025-01-26 22:34 UTC, nnethercote commented on tests/ui/malformed/malformed-regressions.stderr
> +error: valid forms for the attribute are `#[doc(hidden, inline, ...)]` and `#[doc = "string"]`
IMO this change makes the error message less clear. The old `|` char indicated that `hidden` and `inline` were alternatives, the `,` is less clear.

2025-01-27 08:39 UTC, Blindspot22 commented on compiler/rustc_feature/src/builtin_attrs.rs
> +    ),
Sorry this was a mistake. Just adjusted that

2025-01-27 08:41 UTC, Blindspot22 commented on compiler/rustc_feature/src/builtin_attrs.rs
> +
Same here. I think it was a mistake which occurred when i was resolving former conflicts

2025-01-27 08:44 UTC, Blindspot22 commented on compiler/rustc_feature/src/builtin_attrs.rs
> -    ungated!(cfg, Normal, template!(List: "predicate"), DuplicatesOk, EncodeCrossCrate::Yes),
Done

2025-01-27 08:45 UTC, Blindspot22 commented on compiler/rustc_feature/src/builtin_attrs.rs
> +        macro_use, Normal, template!(Word, List: &["name1, name2, ..."]), WarnFollowingWordOnly,
good

2025-01-27 08:46 UTC, Blindspot22 commented on tests/ui/malformed/malformed-regressions.stderr
> +error: valid forms for the attribute are `#[doc(hidden, inline, ...)]` and `#[doc = "string"]`
done

2025-01-27 08:46 UTC, Blindspot22 commented on compiler/rustc_feature/src/builtin_attrs.rs
> +        warn, Normal, template!(List: &["lint1", "lint2", "...", "/*opt*/ reason = \"...\""]),
ok

2025-01-27 08:46 UTC, Blindspot22 commented on compiler/rustc_feature/src/builtin_attrs.rs
> +        template!(Word, List: &["expected = \"reason\""], NameValueStr: "reason"), FutureWarnFollowing,
Kk

2025-01-27 08:49 UTC, Blindspot22 commented
> This is getting closer, but there are still some problems.
> 
>     * There is a merge commit, which isn't acceptable, as explained [here](https://github.com/rust-lang/rust/pull/130923#issuecomment-2612132083).
> 
>     * Something weird has happened with the merge commit, which is causing the compile errors.
> 
>     * The change to `rust/src/test/ui/no_crate_type.stderr` present in an earlier commit has been reverted in a later commit. This change is the motivation for this whole PR.
> 
>     * The multiple commits still need to be squashed.
> 
>     * Plus the various comments I have made below.
> 
> 
> Please make sure these are fixed. If any of them are unclear, feel free to ask for clarification here or on Zulip.

Hello @nnethercote thanks. I'm presently working on the changes, almost done. As for the `squash` i was thinking of doing that after all the changes are good and ready for merge, such that i have just 1 squash

2025-01-27 11:39 UTC, Blindspot22 commented
> There are merge commits (commits with multiple parents) in your changes. We have a [no merge policy](https://rustc-dev-guide.rust-lang.org/git.html#no-merge-policy) so these commits will need to be removed for this pull request to be merged.
> 
> You can start a rebase with the following commands:
> 
> ```
> $ # rebase
> $ git pull --rebase https://github.com/rust-lang/rust.git master
> $ git push --force-with-lease
> ```
> 
> The following commits are merge commits:
> 
>     * [9fae9f4](https://github.com/rust-lang/rust/commit/9fae9f4ed9de6b2a31b675b72bf5ab694892b052)

To solve the [no merge policy](https://rustc-dev-guide.rust-lang.org/git.html#no-merge-policy) and squash issue i created a new branch with reference to this 
[here]( #136125)

2025-01-27 21:34 UTC, nnethercote commented
It would have been possible to remove the merge commit in this PR, but given that #136125 has been opened I will close this.

2025-01-27 21:34 UTC, closed without merging