Handle `rustc_middle` cases of `rustc::potential_query_instability` lint
rust-lang/rust pull request #131160
Opened 2024-10-02 16:16 UTC by ismailarilik

This PR removes `#![allow(rustc::potential_query_instability)]` line from [`compiler/rustc_middle/src/lib.rs`](https://github.com/rust-lang/rust/blob/master/compiler/rustc_middle/src/lib.rs#L29) and converts `FxHash{Map,Set}` types into `FxIndex{Map,Set}` to suppress lint errors.

A somewhat tracking issue: https://github.com/rust-lang/rust/issues/84447

r? @compiler-errors

2024-10-02 16:44 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/11147573455/job/30982238994) [(plain)](https://github.com/rust-lang/rust/commit/da9a8fddd0758227a6533ef4f40e5c88c4402ee9/checks/30982238994/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    assertion `left == right` failed: NOP unsize vtable changed principal trait ref: for<'a> Fn(&'a i32) -> &i32 -> Fn(&i32) -> &i32
      left: Some(Binder { value: std::ops::Fn<(&i32,)>, bound_vars: [Region(BrAnon)] })
     right: Some(Binder { value: std::ops::Fn<(&i32,)>, bound_vars: [] })
    stack backtrace:
       0:     0x7f877da02701 - <<std[6bd2165dbf83ad70]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[14dfe1138574bf49]::fmt::Display>::fmt
       1:     0x7f877da5ee64 - core[14dfe1138574bf49]::fmt::write
       2:     0x7f877d9f58a9 - <std[6bd2165dbf83ad70]::sys::pal::unix::stdio::Stderr as std[6bd2165dbf83ad70]::io::Write>::write_fmt
       3:     0x7f877da025a2 - <std[6bd2165dbf83ad70]::sys::backtrace::BacktraceLock>::print
       4:     0x7f877da0502a - std[6bd2165dbf83ad70]::panicking::default_hook::{closure#1}
       5:     0x7f877da04dbd - std[6bd2165dbf83ad70]::panicking::default_hook
       6:     0x7f87791f0b02 - <alloc[c6d409a8d6ca508]::boxed::Box<rustc_driver_impl[fb9567fff64d141c]::install_ice_hook::{closure#0}> as core[14dfe1138574bf49]::ops::function::Fn<(&dyn for<'a, 'b> core[14dfe1138574bf49]::ops::function::Fn<(&'a std[6bd2165dbf83ad70]::panic::PanicHookInfo<'b>,), Output = ()> + core[14dfe1138574bf49]::marker::Sync + core[14dfe1138574bf49]::marker::Send, &std[6bd2165dbf83ad70]::panic::PanicHookInfo)>>::call
       7:     0x7f877da05908 - std[6bd2165dbf83ad70]::panicking::rust_panic_with_hook
       8:     0x7f877da0562e - std[6bd2165dbf83ad70]::panicking::begin_panic_handler::{closure#0}
       9:     0x7f877da02d59 - std[6bd2165dbf83ad70]::sys::backtrace::__rust_end_short_backtrace::<std[6bd2165dbf83ad70]::panicking::begin_panic_handler::{closure#0}, !>
      11:     0x7f877da5ace0 - core[14dfe1138574bf49]::panicking::panic_fmt
      12:     0x7f877da5b236 - core[14dfe1138574bf49]::panicking::assert_failed_inner
      12:     0x7f877da5b236 - core[14dfe1138574bf49]::panicking::assert_failed_inner
      13:     0x7f877988e46f - core[14dfe1138574bf49]::panicking::assert_failed::<core[14dfe1138574bf49]::option::Option<rustc_type_ir[7525ffd998158169]::binder::Binder<rustc_middle[3de944b6c1e72bbd]::ty::context::TyCtxt, rustc_type_ir[7525ffd998158169]::predicate::ExistentialTraitRef<rustc_middle[3de944b6c1e72bbd]::ty::context::TyCtxt>>>, core[14dfe1138574bf49]::option::Option<rustc_type_ir[7525ffd998158169]::binder::Binder<rustc_middle[3de944b6c1e72bbd]::ty::context::TyCtxt, rustc_type_ir[7525ffd998158169]::predicate::ExistentialTraitRef<rustc_middle[3de944b6c1e72bbd]::ty::context::TyCtxt>>>>
      14:     0x7f87796be5e1 - rustc_codegen_ssa[618b7a7f1838614a]::base::unsized_info::<rustc_codegen_llvm[f245f1c021a00db8]::builder::Builder>
      15:     0x7f87796bdd67 - rustc_codegen_ssa[618b7a7f1838614a]::base::unsize_ptr::<rustc_codegen_llvm[f245f1c021a00db8]::builder::Builder>
      16:     0x7f87797fe3b9 - <rustc_codegen_ssa[618b7a7f1838614a]::mir::FunctionCx<rustc_codegen_llvm[f245f1c021a00db8]::builder::Builder>>::codegen_rvalue_operand
      17:     0x7f87797f3800 - rustc_codegen_ssa[618b7a7f1838614a]::mir::codegen_mir::<rustc_codegen_llvm[f245f1c021a00db8]::builder::Builder>
      18:     0x7f87796c0034 - rustc_codegen_ssa[618b7a7f1838614a]::base::codegen_instance::<rustc_codegen_llvm[f245f1c021a00db8]::builder::Builder>
      19:     0x7f8779744a32 - <rustc_middle[3de944b6c1e72bbd]::mir::mono::MonoItem as rustc_codegen_ssa[618b7a7f1838614a]::mono_item::MonoItemExt>::define::<rustc_codegen_llvm[f245f1c021a00db8]::builder::Builder>
      20:     0x7f87797cda86 - rustc_codegen_llvm[f245f1c021a00db8]::base::compile_codegen_unit::module_codegen
      21:     0x7f87797d0f1f - <rustc_codegen_llvm[f245f1c021a00db8]::LlvmCodegenBackend as rustc_codegen_ssa[618b7a7f1838614a]::traits::backend::ExtraBackendMethods>::compile_codegen_unit
      22:     0x7f87796bf49d - rustc_codegen_ssa[618b7a7f1838614a]::base::codegen_crate::<rustc_codegen_llvm[f245f1c021a00db8]::LlvmCodegenBackend>
      23:     0x7f87797d4729 - <rustc_codegen_llvm[f245f1c021a00db8]::LlvmCodegenBackend as rustc_codegen_ssa[618b7a7f1838614a]::traits::backend::CodegenBackend>::codegen_crate
      24:     0x7f8779478ad7 - <rustc_session[ccc6ba088a6ae1ec]::session::Session>::time::<alloc[c6d409a8d6ca508]::boxed::Box<dyn core[14dfe1138574bf49]::any::Any>, rustc_interface[baec07d74f6bf86e]::passes::start_codegen::{closure#0}>
      25:     0x7f87795a3db7 - rustc_interface[baec07d74f6bf86e]::passes::start_codegen
      26:     0x7f87794ae482 - <rustc_interface[baec07d74f6bf86e]::queries::Linker>::codegen_and_build_linker
      27:     0x7f87792188ed - <rustc_middle[3de944b6c1e72bbd]::ty::context::GlobalCtxt>::enter::<rustc_driver_impl[fb9567fff64d141c]::run_compiler::{closure#0}::{closure#1}::{closure#6}, core[14dfe1138574bf49]::result::Result<core[14dfe1138574bf49]::option::Option<rustc_interface[baec07d74f6bf86e]::queries::Linker>, rustc_span[b3c9c6a2efb6bb00]::ErrorGuaranteed>>
      28:     0x7f87791f3e2a - <rustc_interface[baec07d74f6bf86e]::interface::Compiler>::enter::<rustc_driver_impl[fb9567fff64d141c]::run_compiler::{closure#0}::{closure#1}, core[14dfe1138574bf49]::result::Result<core[14dfe1138574bf49]::option::Option<rustc_interface[baec07d74f6bf86e]::queries::Linker>, rustc_span[b3c9c6a2efb6bb00]::ErrorGuaranteed>>
      29:     0x7f8779271474 - <scoped_tls[9bbbc380100b9321]::ScopedKey<rustc_span[b3c9c6a2efb6bb00]::SessionGlobals>>::set::<rustc_interface[baec07d74f6bf86e]::util::run_in_thread_with_globals<rustc_interface[baec07d74f6bf86e]::util::run_in_thread_pool_with_globals<rustc_interface[baec07d74f6bf86e]::interface::run_compiler<core[14dfe1138574bf49]::result::Result<(), rustc_span[b3c9c6a2efb6bb00]::ErrorGuaranteed>, rustc_driver_impl[fb9567fff64d141c]::run_compiler::{closure#0}>::{closure#1}, core[14dfe1138574bf49]::result::Result<(), rustc_span[b3c9c6a2efb6bb00]::ErrorGuaranteed>>::{closure#0}, core[14dfe1138574bf49]::result::Result<(), rustc_span[b3c9c6a2efb6bb00]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}, core[14dfe1138574bf49]::result::Result<(), rustc_span[b3c9c6a2efb6bb00]::ErrorGuaranteed>>
      30:     0x7f877924555c - rustc_span[b3c9c6a2efb6bb00]::create_session_globals_then::<core[14dfe1138574bf49]::result::Result<(), rustc_span[b3c9c6a2efb6bb00]::ErrorGuaranteed>, rustc_interface[baec07d74f6bf86e]::util::run_in_thread_with_globals<rustc_interface[baec07d74f6bf86e]::util::run_in_thread_pool_with_globals<rustc_interface[baec07d74f6bf86e]::interface::run_compiler<core[14dfe1138574bf49]::result::Result<(), rustc_span[b3c9c6a2efb6bb00]::ErrorGuaranteed>, rustc_driver_impl[fb9567fff64d141c]::run_compiler::{closure#0}>::{closure#1}, core[14dfe1138574bf49]::result::Result<(), rustc_span[b3c9c6a2efb6bb00]::ErrorGuaranteed>>::{closure#0}, core[14dfe1138574bf49]::result::Result<(), rustc_span[b3c9c6a2efb6bb00]::ErrorGuaranteed>>::{closure#0}::{closure#0}::{closure#0}>
      31:     0x7f877922e6f2 - std[6bd2165dbf83ad70]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[baec07d74f6bf86e]::util::run_in_thread_with_globals<rustc_interface[baec07d74f6bf86e]::util::run_in_thread_pool_with_globals<rustc_interface[baec07d74f6bf86e]::interface::run_compiler<core[14dfe1138574bf49]::result::Result<(), rustc_span[b3c9c6a2efb6bb00]::ErrorGuaranteed>, rustc_driver_impl[fb9567fff64d141c]::run_compiler::{closure#0}>::{closure#1}, core[14dfe1138574bf49]::result::Result<(), rustc_span[b3c9c6a2efb6bb00]::ErrorGuaranteed>>::{closure#0}, core[14dfe1138574bf49]::result::Result<(), rustc_span[b3c9c6a2efb6bb00]::ErrorGuaranteed>>::{closure#0}::{closure#0 [...]

2025-01-23 18:06 UTC, compiler-errors commented
I'm gonna re-roll this so this PR gets more attention, sorry for my inactivity.

r? compiler

But also reassigning to author sicne I think this PR still needs updating.

@rustbot author

2025-01-26 00:47 UTC, SparrowLii commented
@ismailarilik Can you rebase the PR today? I'm in holiday tomorrow so I"d like to have a review before that :)

2025-01-26 07:07 UTC, SparrowLii commented
r? compiler cause I'm going to the holidays in the next few days.

And I suggest to run a rustc perf when it's ready since this PR change the cache struct

2025-02-25 18:51 UTC, Dylan-DPC commented
@ismailarilik any updates on this? thanks

2025-03-02 05:23 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/13612225803/job/38050862251) [(plain)](https://github.com/rust-lang/rust/commit/b2dd7bd0d15f098c8d112c4e881a47dd489234cb/checks/38050862251/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
+++ <fixed output>
 //@edition:2015
 
... 14 lines skipped ...
 use crate::mod_mod::inner_mod;
 //~^ wildcard_imports
-use crate::multi_fn_mod::{multi_bar, multi_foo, multi_inner_mod};
+use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
 //~^ wildcard_imports
... 5 lines skipped ...
 use wildcard_imports_helper::inner::inner_for_self_import::inner_extern_bar;
 //~^ wildcard_imports
 //~^ wildcard_imports
-use wildcard_imports_helper::{ExternA, extern_foo};
+use wildcard_imports_helper::{extern_foo, ExternA};
 //~^ wildcard_imports
... 107 lines skipped ...
         use wildcard_imports_helper::inner::inner_for_self_import::{self, inner_extern_foo};
         //~^ wildcard_imports
         //~^ wildcard_imports
-        use wildcard_imports_helper::{ExternA, extern_foo};
+        use wildcard_imports_helper::{extern_foo, ExternA};
         //~^ wildcard_imports
... 17 lines skipped ...
 
     fn test_extern_reexported() {
     fn test_extern_reexported() {
-        use wildcard_imports_helper::{ExternExportedEnum, ExternExportedStruct, extern_exported};
+        use wildcard_imports_helper::{extern_exported, ExternExportedStruct, ExternExportedEnum};
         //~^ wildcard_imports
... 25 lines skipped ...
 
 fn test_reexported() {
 fn test_reexported() {
-    use crate::in_fn_test::{ExportedEnum, ExportedStruct, exported};
+    use crate::in_fn_test::{exported, ExportedStruct, ExportedEnum};
     //~^ wildcard_imports
... 102 lines skipped ...
     }
 }

---

error: actual output differed from expected
Execute `cargo uibless` to update `tests/ui/wildcard_imports_2021.edition2018.fixed` to the actual output
--- tests/ui/wildcard_imports_2021.edition2018.fixed
+++ <fixed output>
 //@revisions: edition2018 edition2021
 //@[edition2018] edition:2018
... 12 lines skipped ...
 use crate::mod_mod::inner_mod;
 //~^ wildcard_imports
-use crate::multi_fn_mod::{multi_bar, multi_foo, multi_inner_mod};
+use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
 //~^ wildcard_imports
 use crate::struct_mod::{A, inner_struct_mod};
 //~^ wildcard_imports
 use wildcard_imports_helper::prelude::v1::*;
 use wildcard_imports_helper::prelude::v1::*;
-use wildcard_imports_helper::{ExternA, extern_foo};
+use wildcard_imports_helper::{extern_foo, ExternA};
 //~^ wildcard_imports
... 104 lines skipped ...
         use wildcard_imports_helper::inner::inner_for_self_import::{self, inner_extern_foo};
         //~^ wildcard_imports
         //~^ wildcard_imports
-        use wildcard_imports_helper::{ExternA, extern_foo};
+        use wildcard_imports_helper::{extern_foo, ExternA};
         //~^ wildcard_imports
... 17 lines skipped ...
 
     fn test_extern_reexported() {
     fn test_extern_reexported() {
-        use wildcard_imports_helper::{ExternExportedEnum, ExternExportedStruct, extern_exported};
+        use wildcard_imports_helper::{extern_exported, ExternExportedStruct, ExternExportedEnum};
         //~^ wildcard_imports
... 25 lines skipped ...
 
 fn test_reexported() {
 fn test_reexported() {
-    use crate::in_fn_test::{ExportedEnum, ExportedStruct, exported};
+    use crate::in_fn_test::{exported, ExportedStruct, ExportedEnum};
     //~^ wildcard_imports
... 102 lines skipped ...
     }
 }

---

error: actual output differed from expected
Execute `cargo uibless` to update `tests/ui/wildcard_imports_2021.edition2021.fixed` to the actual output
--- tests/ui/wildcard_imports_2021.edition2021.fixed
+++ <fixed output>
 //@revisions: edition2018 edition2021
 //@[edition2018] edition:2018
... 12 lines skipped ...
 use crate::mod_mod::inner_mod;
 //~^ wildcard_imports
-use crate::multi_fn_mod::{multi_bar, multi_foo, multi_inner_mod};
+use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
 //~^ wildcard_imports
 use crate::struct_mod::{A, inner_struct_mod};
 //~^ wildcard_imports
 use wildcard_imports_helper::prelude::v1::*;
 use wildcard_imports_helper::prelude::v1::*;
-use wildcard_imports_helper::{ExternA, extern_foo};
+use wildcard_imports_helper::{extern_foo, ExternA};
 //~^ wildcard_imports
... 104 lines skipped ...
         use wildcard_imports_helper::inner::inner_for_self_import::{self, inner_extern_foo};
         //~^ wildcard_imports
         //~^ wildcard_imports
-        use wildcard_imports_helper::{ExternA, extern_foo};
+        use wildcard_imports_helper::{extern_foo, ExternA};
         //~^ wildcard_imports
... 17 lines skipped ...
 
     fn test_extern_reexported() {
     fn test_extern_reexported() {
-        use wildcard_imports_helper::{ExternExportedEnum, ExternExportedStruct, extern_exported};
+        use wildcard_imports_helper::{extern_exported, ExternExportedStruct, ExternExportedEnum};
         //~^ wildcard_imports
... 25 lines skipped ...
 
 fn test_reexported() {
 fn test_reexported() {
-    use crate::in_fn_test::{ExportedEnum, ExportedStruct, exported};
+    use crate::in_fn_test::{exported, ExportedStruct, ExportedEnum};
     //~^ wildcard_imports
... 102 lines skipped ...
     }
 }

```

</details>

2025-03-03 07:24 UTC, ismailarilik commented
Could you update the outputs and then rebase? Nowadays I don't have access
neither Git nor Rust.

2 Mar 2025 Paz 08:23 tarihinde Rust Log Analyzer ***@***.***>
şunu yazdı:

> The job *x86_64-gnu-tools* failed! Check out the build log: (web)
> <https://github.com/rust-lang/rust/actions/runs/13612225803/job/38050862251>
> (plain)
> <https://github.com/rust-lang/rust/commit/b2dd7bd0d15f098c8d112c4e881a47dd489234cb/checks/38050862251/logs>
> *Click to see the possible cause of the failure (guessed by this bot)*
>
> +++ <fixed output>
>  ***@***.***:2015
>
> ... 14 lines skipped ...
>  use crate::mod_mod::inner_mod;
>  //~^ wildcard_imports
> -use crate::multi_fn_mod::{multi_bar, multi_foo, multi_inner_mod};
> +use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
>  //~^ wildcard_imports
> ... 5 lines skipped ...
>  use wildcard_imports_helper::inner::inner_for_self_import::inner_extern_bar;
>  //~^ wildcard_imports
>  //~^ wildcard_imports
> -use wildcard_imports_helper::{ExternA, extern_foo};
> +use wildcard_imports_helper::{extern_foo, ExternA};
>  //~^ wildcard_imports
> ... 107 lines skipped ...
>          use wildcard_imports_helper::inner::inner_for_self_import::{self, inner_extern_foo};
>          //~^ wildcard_imports
>          //~^ wildcard_imports
> -        use wildcard_imports_helper::{ExternA, extern_foo};
> +        use wildcard_imports_helper::{extern_foo, ExternA};
>          //~^ wildcard_imports
> ... 17 lines skipped ...
>
>      fn test_extern_reexported() {
>      fn test_extern_reexported() {
> -        use wildcard_imports_helper::{ExternExportedEnum, ExternExportedStruct, extern_exported};
> +        use wildcard_imports_helper::{extern_exported, ExternExportedStruct, ExternExportedEnum};
>          //~^ wildcard_imports
> ... 25 lines skipped ...
>
>  fn test_reexported() {
>  fn test_reexported() {
> -    use crate::in_fn_test::{ExportedEnum, ExportedStruct, exported};
> +    use crate::in_fn_test::{exported, ExportedStruct, ExportedEnum};
>      //~^ wildcard_imports
> ... 102 lines skipped ...
>      }
>  }
>
> ---
>
> error: actual output differed from expected
> Execute `cargo uibless` to update `tests/ui/wildcard_imports_2021.edition2018.fixed` to the actual output
> --- tests/ui/wildcard_imports_2021.edition2018.fixed
> +++ <fixed output>
>  ***@***.***: edition2018 edition2021
>  ***@***.*** edition:2018
> ... 12 lines skipped ...
>  use crate::mod_mod::inner_mod;
>  //~^ wildcard_imports
> -use crate::multi_fn_mod::{multi_bar, multi_foo, multi_inner_mod};
> +use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
>  //~^ wildcard_imports
>  use crate::struct_mod::{A, inner_struct_mod};
>  //~^ wildcard_imports
>  use wildcard_imports_helper::prelude::v1::*;
>  use wildcard_imports_helper::prelude::v1::*;
> -use wildcard_imports_helper::{ExternA, extern_foo};
> +use wildcard_imports_helper::{extern_foo, ExternA};
>  //~^ wildcard_imports
> ... 104 lines skipped ...
>          use wildcard_imports_helper::inner::inner_for_self_import::{self, inner_extern_foo};
>          //~^ wildcard_imports
>          //~^ wildcard_imports
> -        use wildcard_imports_helper::{ExternA, extern_foo};
> +        use wildcard_imports_helper::{extern_foo, ExternA};
>          //~^ wildcard_imports
> ... 17 lines skipped ...
>
>      fn test_extern_reexported() {
>      fn test_extern_reexported() {
> -        use wildcard_imports_helper::{ExternExportedEnum, ExternExportedStruct, extern_exported};
> +        use wildcard_imports_helper::{extern_exported, ExternExportedStruct, ExternExportedEnum};
>          //~^ wildcard_imports
> ... 25 lines skipped ...
>
>  fn test_reexported() {
>  fn test_reexported() {
> -    use crate::in_fn_test::{ExportedEnum, ExportedStruct, exported};
> +    use crate::in_fn_test::{exported, ExportedStruct, ExportedEnum};
>      //~^ wildcard_imports
> ... 102 lines skipped ...
>      }
>  }
>
> ---
>
> error: actual output differed from expected
> Execute `cargo uibless` to update `tests/ui/wildcard_imports_2021.edition2021.fixed` to the actual output
> --- tests/ui/wildcard_imports_2021.edition2021.fixed
> +++ <fixed output>
>  ***@***.***: edition2018 edition2021
>  ***@***.*** edition:2018
> ... 12 lines skipped ...
>  use crate::mod_mod::inner_mod;
>  //~^ wildcard_imports
> -use crate::multi_fn_mod::{multi_bar, multi_foo, multi_inner_mod};
> +use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
>  //~^ wildcard_imports
>  use crate::struct_mod::{A, inner_struct_mod};
>  //~^ wildcard_imports
>  use wildcard_imports_helper::prelude::v1::*;
>  use wildcard_imports_helper::prelude::v1::*;
> -use wildcard_imports_helper::{ExternA, extern_foo};
> +use wildcard_imports_helper::{extern_foo, ExternA};
>  //~^ wildcard_imports
> ... 104 lines skipped ...
>          use wildcard_imports_helper::inner::inner_for_self_import::{self, inner_extern_foo};
>          //~^ wildcard_imports
>          //~^ wildcard_imports
> -        use wildcard_imports_helper::{ExternA, extern_foo};
> +        use wildcard_imports_helper::{extern_foo, ExternA};
>          //~^ wildcard_imports
> ... 17 lines skipped ...
>
>      fn test_extern_reexported() {
>      fn test_extern_reexported() {
> -        use wildcard_imports_helper::{ExternExportedEnum, ExternExportedStruct, extern_exported};
> +        use wildcard_imports_helper::{extern_exported, ExternExportedStruct, ExternExportedEnum};
>          //~^ wildcard_imports
> ... 25 lines skipped ...
>
>  fn test_reexported() {
>  fn test_reexported() {
> -    use crate::in_fn_test::{ExportedEnum, ExportedStruct, exported};
> +    use crate::in_fn_test::{exported, ExportedStruct, ExportedEnum};
>      //~^ wildcard_imports
> ... 102 lines skipped ...
>      }
>  }
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/131160#issuecomment-2692564890>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEGFHYPVGPHC2QPC4PMXSBD2SKIWRAVCNFSM6AAAAABPIAPP7WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMOJSGU3DIOBZGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
> [image: rust-log-analyzer]*rust-log-analyzer* left a comment
> (rust-lang/rust#131160)
> <https://github.com/rust-lang/rust/pull/131160#issuecomment-2692564890>
>
> The job *x86_64-gnu-tools* failed! Check out the build log: (web)
> <https://github.com/rust-lang/rust/actions/runs/13612225803/job/38050862251>
> (plain)
> <https://github.com/rust-lang/rust/commit/b2dd7bd0d15f098c8d112c4e881a47dd489234cb/checks/38050862251/logs>
> *Click to see the possible cause of the failure (guessed by this bot)*
>
> +++ <fixed output>
>  ***@***.***:2015
>
> ... 14 lines skipped ...
>  use crate::mod_mod::inner_mod;
>  //~^ wildcard_imports
> -use crate::multi_fn_mod::{multi_bar, multi_foo, multi_inner_mod};
> +use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
>  //~^ wildcard_imports
> ... 5 lines skipped ...
>  use wildcard_imports_helper::inner::inner_for_self_import::inner_extern_bar;
>  //~^ wildcard_imports
>  //~^ wildcard_imports
> -use wildcard_imports_helper::{ExternA, extern_foo};
> +use wildcard_imports_helper::{extern_foo, ExternA};
>  //~^ wildcard_imports
> ... 107 lines skipped ...
>          use wildcard_imports_helper::inner::inner_for_self_import::{self, inner_extern_foo};
>          //~^ wildcard_imports
>          //~^ wildcard_imports
> -        use wildcard_imports_helper::{ExternA, extern_foo};
> +        use wildcard_imports_helper::{extern_foo, ExternA};
>          //~^ wildcard_imports
> ... 17 lines skipped ...
>
>      fn test_extern_reexported() {
>      fn test_extern_reexported() {
> -        use wildcard_imports_helper::{ExternExportedEnum, ExternExportedStruct, extern_exported};
> +        use wildcard_imports_helper::{extern_exported, ExternExportedStruct, ExternExportedEnum};
>          //~^ wildcard_imports
> ... 25 lines skipped ...
>
>  fn test_reexported() {
>   [...]

2025-03-13 07:25 UTC, ismailarilik commented
Could you inform me when you are ready to look at this issue? Then I will resolve conflicts. It is more efficient than resolving them everytime IMHO.

2025-04-05 07:34 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/14279571402/job/40027441762) [(plain)](https://github.com/rust-lang/rust/commit/095de4aa2e5fd049ed2e5879263ef9fefa14bc45/checks/40027441762/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
+++ <fixed output>
 //@edition:2015
 
... 14 lines skipped ...
 use crate::mod_mod::inner_mod;
 //~^ wildcard_imports
-use crate::multi_fn_mod::{multi_bar, multi_foo, multi_inner_mod};
+use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
 //~^ wildcard_imports
 #[macro_use]
... 5 lines skipped ...
 use wildcard_imports_helper::inner::inner_for_self_import::inner_extern_bar;
 //~^ wildcard_imports
-use wildcard_imports_helper::{ExternA, extern_foo};
+use wildcard_imports_helper::{extern_foo, ExternA};
 //~^ wildcard_imports
 
... 107 lines skipped ...
         use wildcard_imports_helper::inner::inner_for_self_import::{self, inner_extern_foo};
         //~^ wildcard_imports
-        use wildcard_imports_helper::{ExternA, extern_foo};
+        use wildcard_imports_helper::{extern_foo, ExternA};
         //~^ wildcard_imports
 
... 17 lines skipped ...
 
     fn test_extern_reexported() {
-        use wildcard_imports_helper::{ExternExportedEnum, ExternExportedStruct, extern_exported};
+        use wildcard_imports_helper::{extern_exported, ExternExportedStruct, ExternExportedEnum};
         //~^ wildcard_imports
 
... 25 lines skipped ...
 
 fn test_reexported() {
-    use crate::in_fn_test::{ExportedEnum, ExportedStruct, exported};
+    use crate::in_fn_test::{exported, ExportedStruct, ExportedEnum};
     //~^ wildcard_imports
 
... 102 lines skipped ...
     }
 }

Full unnormalized output:
//@edition:2015

//@aux-build:wildcard_imports_helper.rs

// the 2015 edition here is needed because edition 2018 changed the module system
// (see https://doc.rust-lang.org/edition-guide/rust-2018/path-changes.html) which means the lint
// no longer detects some of the cases starting with Rust 2018.

#![warn(clippy::wildcard_imports)]
#![allow(unused, clippy::unnecessary_wraps, clippy::let_unit_value)]
#![warn(unused_imports)]

extern crate wildcard_imports_helper;

use crate::fn_mod::foo;
//~^ wildcard_imports
use crate::mod_mod::inner_mod;
//~^ wildcard_imports
use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
//~^ wildcard_imports
#[macro_use]
use crate::struct_mod::{A, inner_struct_mod};
//~^ wildcard_imports

#[allow(unused_imports)]
use wildcard_imports_helper::inner::inner_for_self_import;
use wildcard_imports_helper::inner::inner_for_self_import::inner_extern_bar;
//~^ wildcard_imports
use wildcard_imports_helper::{extern_foo, ExternA};
//~^ wildcard_imports

use std::io::prelude::*;
use wildcard_imports_helper::extern_prelude::v1::*;
use wildcard_imports_helper::prelude::v1::*;

struct ReadFoo;

impl Read for ReadFoo {
    fn read(&mut self, _buf: &mut [u8]) -> std::io::Result<usize> {
        Ok(0)
    }
}

mod fn_mod {
    pub fn foo() {}
---
        pub fn foo() {}
    }
}

mod multi_fn_mod {
    pub fn multi_foo() {}
    pub fn multi_bar() {}
    pub fn multi_baz() {}
    pub mod multi_inner_mod {
        pub fn foo() {}
    }
}

mod struct_mod {
---
mod underscore_mod {
    // allow use of `deref` so that `clippy --fix` includes `Deref`.
    #![allow(noop_method_call)]

    mod exports_underscore {
        pub use std::ops::Deref as _;
        pub fn dummy() {}
    }

    mod exports_underscore_ish {
        pub use std::ops::Deref as _Deref;
        pub fn dummy() {}
    }

    fn does_not_lint() {
        use self::exports_underscore::*;
        let _ = (&0).deref();
        dummy();
    }

    fn does_lint() {
        use self::exports_underscore_ish::{_Deref, dummy};
        //~^ wildcard_imports
        let _ = (&0).deref();
        dummy();
    }
}

fn main() {
    foo();
    multi_foo();
    multi_bar();
    multi_inner_mod::foo();
    inner_mod::foo();
    extern_foo();
    inner_extern_bar();

    let _ = A;
    let _ = inner_struct_mod::C;
    let _ = ExternA;
    let _ = PreludeModAnywhere;
    let _ = ExternPreludeModAnywhere;

    double_struct_import_test!();
    double_struct_import_test!();
}

---

        foo();
    }

    fn test_extern() {
        use wildcard_imports_helper::inner::inner_for_self_import::{self, inner_extern_foo};
        //~^ wildcard_imports
        use wildcard_imports_helper::{extern_foo, ExternA};
        //~^ wildcard_imports

        inner_for_self_import::inner_extern_foo();
        inner_extern_foo();

        extern_foo();

        let _ = ExternA;
    }

    fn test_inner_nested() {
        #[rustfmt::skip]
        use self::{inner::inner_foo, inner2::inner_bar};
        //~^ wildcard_imports
        //~| wildcard_imports

        inner_foo();
        inner_bar();
    }

    fn test_extern_reexported() {
        use wildcard_imports_helper::{extern_exported, ExternExportedStruct, ExternExportedEnum};
        //~^ wildcard_imports

        extern_exported();
        let _ = ExternExportedStruct;
        let _ = ExternExportedEnum::A;
    }
---
    }
}

fn test_reexported() {
    use crate::in_fn_test::{exported, ExportedStruct, ExportedEnum};
    //~^ wildcard_imports

    exported();
    let _ = ExportedStruct;
    let _ = ExportedEnum::A;
}

#[rustfmt::skip]
fn test_weird_formatting() {
    use crate:: in_fn_test::exported;
    //~^ wildcard_imports
    use crate:: fn_mod::foo;

    exported();
    foo();
}

---

error: actual output differed from expected
Execute `cargo uibless` to update `tests/ui/wildcard_imports_2021.edition2018.fixed` to the actual output
--- tests/ui/wildcard_imports_2021.edition2018.fixed
+++ <fixed output>
 //@revisions: edition2018 edition2021
 //@[edition2018] edition:2018
... 12 lines skipped ...
 use crate::mod_mod::inner_mod;
 //~^ wildcard_imports
-use crate::multi_fn_mod::{multi_bar, multi_foo, multi_inner_mod};
+use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
 //~^ wildcard_imports
 use crate::struct_mod::{A, inner_struct_mod};
... 4 lines skipped ...
 //~^ wildcard_imports
 use wildcard_imports_helper::prelude::v1::*;
-use wildcard_imports_helper::{ExternA, extern_foo};
+use wildcard_imports_helper::{extern_foo, ExternA};
 //~^ wildcard_imports
 
... 104 lines skipped ...
         use wildcard_imports_helper::inner::inner_for_self_import::{self, inner_extern_foo};
         //~^ wildcard_imports
-        use wildcard_imports_helper::{ExternA, extern_foo};
+        use wildcard_imports_helper::{extern_foo, ExternA};
         //~^ wildcard_imports
 
... 17 lines skipped ...
 
     fn test_extern_reexported() {
-        use wildcard_imports_helper::{ExternExportedEnum, ExternExportedStruct, extern_exported};
+        use wildcard_imports_helper::{extern_exported, ExternExportedStruct, ExternExportedEnum};
         //~^ wildcard_imports
 
... 25 lines skipped ...
 
 fn test_reexported() {
-    use crate::in_fn_test::{ExportedEnum, ExportedStruct, exported};
+    use crate::in_fn_test::{exported, ExportedStruct, ExportedEnum};
     //~^ wildcard_imports
 
... 102 lines skipped ...
     }
 }

Full unnormalized output:
//@revisions: edition2018 edition2021
//@[edition2018] edition:2018
//@[edition2021] edition:2021

//@aux-build:wildcard_imports_helper.rs

#![warn(clippy::wildcard_imports)]
#![allow(unused, clippy::unnecessary_wraps, clippy::let_unit_value)]
#![warn(unused_imports)]

extern crate wildcard_imports_helper;

use crate::fn_mod::foo;
//~^ wildcard_imports
use crate::mod_mod::inner_mod;
//~^ wildcard_imports
use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
//~^ wildcard_imports
use crate::struct_mod::{A, inner_struct_mod};
//~^ wildcard_imports

#[allow(unused_imports)]
use wildcard_imports_helper::inner::inner_for_self_import::inner_extern_bar;
//~^ wildcard_imports
use wildcard_imports_helper::prelude::v1::*;
use wildcard_impo [...]

2025-04-05 08:02 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/14279910495/job/40028162306) [(plain)](https://github.com/rust-lang/rust/commit/ccae5e30abb9886bfced721b9eb173a41607e7a8/checks/40028162306/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#19 exporting to docker image format
#19 sending tarball 19.8s done
#19 DONE 33.3s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Listening on address 127.0.0.1:4226
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'build.print-step-timings', '--enable-verbose-tests', '--set', 'build.metrics', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: build.build          := x86_64-unknown-linux-gnu
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
```

</details>

2025-04-05 09:42 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/14280500125/job/40029491016) [(plain)](https://github.com/rust-lang/rust/commit/095de4aa2e5fd049ed2e5879263ef9fefa14bc45/checks/40029491016/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
+++ <fixed output>
 //@edition:2015
 
... 14 lines skipped ...
 use crate::mod_mod::inner_mod;
 //~^ wildcard_imports
-use crate::multi_fn_mod::{multi_bar, multi_foo, multi_inner_mod};
+use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
 //~^ wildcard_imports
 #[macro_use]
... 5 lines skipped ...
 use wildcard_imports_helper::inner::inner_for_self_import::inner_extern_bar;
 //~^ wildcard_imports
-use wildcard_imports_helper::{ExternA, extern_foo};
+use wildcard_imports_helper::{extern_foo, ExternA};
 //~^ wildcard_imports
 
... 107 lines skipped ...
         use wildcard_imports_helper::inner::inner_for_self_import::{self, inner_extern_foo};
         //~^ wildcard_imports
-        use wildcard_imports_helper::{ExternA, extern_foo};
+        use wildcard_imports_helper::{extern_foo, ExternA};
         //~^ wildcard_imports
 
... 17 lines skipped ...
 
     fn test_extern_reexported() {
-        use wildcard_imports_helper::{ExternExportedEnum, ExternExportedStruct, extern_exported};
+        use wildcard_imports_helper::{extern_exported, ExternExportedStruct, ExternExportedEnum};
         //~^ wildcard_imports
 
... 25 lines skipped ...
 
 fn test_reexported() {
-    use crate::in_fn_test::{ExportedEnum, ExportedStruct, exported};
+    use crate::in_fn_test::{exported, ExportedStruct, ExportedEnum};
     //~^ wildcard_imports
 
... 102 lines skipped ...
     }
 }

Full unnormalized output:
//@edition:2015

//@aux-build:wildcard_imports_helper.rs

// the 2015 edition here is needed because edition 2018 changed the module system
// (see https://doc.rust-lang.org/edition-guide/rust-2018/path-changes.html) which means the lint
// no longer detects some of the cases starting with Rust 2018.

#![warn(clippy::wildcard_imports)]
#![allow(unused, clippy::unnecessary_wraps, clippy::let_unit_value)]
#![warn(unused_imports)]

extern crate wildcard_imports_helper;

use crate::fn_mod::foo;
//~^ wildcard_imports
use crate::mod_mod::inner_mod;
//~^ wildcard_imports
use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
//~^ wildcard_imports
#[macro_use]
use crate::struct_mod::{A, inner_struct_mod};
//~^ wildcard_imports

#[allow(unused_imports)]
use wildcard_imports_helper::inner::inner_for_self_import;
use wildcard_imports_helper::inner::inner_for_self_import::inner_extern_bar;
//~^ wildcard_imports
use wildcard_imports_helper::{extern_foo, ExternA};
//~^ wildcard_imports

use std::io::prelude::*;
use wildcard_imports_helper::extern_prelude::v1::*;
use wildcard_imports_helper::prelude::v1::*;

struct ReadFoo;

impl Read for ReadFoo {
    fn read(&mut self, _buf: &mut [u8]) -> std::io::Result<usize> {
        Ok(0)
    }
}

mod fn_mod {
    pub fn foo() {}
---
        pub fn foo() {}
    }
}

mod multi_fn_mod {
    pub fn multi_foo() {}
    pub fn multi_bar() {}
    pub fn multi_baz() {}
    pub mod multi_inner_mod {
        pub fn foo() {}
    }
}

mod struct_mod {
---
mod underscore_mod {
    // allow use of `deref` so that `clippy --fix` includes `Deref`.
    #![allow(noop_method_call)]

    mod exports_underscore {
        pub use std::ops::Deref as _;
        pub fn dummy() {}
    }

    mod exports_underscore_ish {
        pub use std::ops::Deref as _Deref;
        pub fn dummy() {}
    }

    fn does_not_lint() {
        use self::exports_underscore::*;
        let _ = (&0).deref();
        dummy();
    }

    fn does_lint() {
        use self::exports_underscore_ish::{_Deref, dummy};
        //~^ wildcard_imports
        let _ = (&0).deref();
        dummy();
    }
}

fn main() {
    foo();
    multi_foo();
    multi_bar();
    multi_inner_mod::foo();
    inner_mod::foo();
    extern_foo();
    inner_extern_bar();

    let _ = A;
    let _ = inner_struct_mod::C;
    let _ = ExternA;
    let _ = PreludeModAnywhere;
    let _ = ExternPreludeModAnywhere;

    double_struct_import_test!();
    double_struct_import_test!();
}

---

        foo();
    }

    fn test_extern() {
        use wildcard_imports_helper::inner::inner_for_self_import::{self, inner_extern_foo};
        //~^ wildcard_imports
        use wildcard_imports_helper::{extern_foo, ExternA};
        //~^ wildcard_imports

        inner_for_self_import::inner_extern_foo();
        inner_extern_foo();

        extern_foo();

        let _ = ExternA;
    }

    fn test_inner_nested() {
        #[rustfmt::skip]
        use self::{inner::inner_foo, inner2::inner_bar};
        //~^ wildcard_imports
        //~| wildcard_imports

        inner_foo();
        inner_bar();
    }

    fn test_extern_reexported() {
        use wildcard_imports_helper::{extern_exported, ExternExportedStruct, ExternExportedEnum};
        //~^ wildcard_imports

        extern_exported();
        let _ = ExternExportedStruct;
        let _ = ExternExportedEnum::A;
    }
---
    }
}

fn test_reexported() {
    use crate::in_fn_test::{exported, ExportedStruct, ExportedEnum};
    //~^ wildcard_imports

    exported();
    let _ = ExportedStruct;
    let _ = ExportedEnum::A;
}

#[rustfmt::skip]
fn test_weird_formatting() {
    use crate:: in_fn_test::exported;
    //~^ wildcard_imports
    use crate:: fn_mod::foo;

    exported();
    foo();
}

---

error: actual output differed from expected
Execute `cargo uibless` to update `tests/ui/wildcard_imports_2021.edition2018.fixed` to the actual output
--- tests/ui/wildcard_imports_2021.edition2018.fixed
+++ <fixed output>
 //@revisions: edition2018 edition2021
 //@[edition2018] edition:2018
... 12 lines skipped ...
 use crate::mod_mod::inner_mod;
 //~^ wildcard_imports
-use crate::multi_fn_mod::{multi_bar, multi_foo, multi_inner_mod};
+use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
 //~^ wildcard_imports
 use crate::struct_mod::{A, inner_struct_mod};
... 4 lines skipped ...
 //~^ wildcard_imports
 use wildcard_imports_helper::prelude::v1::*;
-use wildcard_imports_helper::{ExternA, extern_foo};
+use wildcard_imports_helper::{extern_foo, ExternA};
 //~^ wildcard_imports
 
... 104 lines skipped ...
         use wildcard_imports_helper::inner::inner_for_self_import::{self, inner_extern_foo};
         //~^ wildcard_imports
-        use wildcard_imports_helper::{ExternA, extern_foo};
+        use wildcard_imports_helper::{extern_foo, ExternA};
         //~^ wildcard_imports
 
... 17 lines skipped ...
 
     fn test_extern_reexported() {
-        use wildcard_imports_helper::{ExternExportedEnum, ExternExportedStruct, extern_exported};
+        use wildcard_imports_helper::{extern_exported, ExternExportedStruct, ExternExportedEnum};
         //~^ wildcard_imports
 
... 25 lines skipped ...
 
 fn test_reexported() {
-    use crate::in_fn_test::{ExportedEnum, ExportedStruct, exported};
+    use crate::in_fn_test::{exported, ExportedStruct, ExportedEnum};
     //~^ wildcard_imports
 
... 102 lines skipped ...
     }
 }

Full unnormalized output:
//@revisions: edition2018 edition2021
//@[edition2018] edition:2018
//@[edition2021] edition:2021

//@aux-build:wildcard_imports_helper.rs

#![warn(clippy::wildcard_imports)]
#![allow(unused, clippy::unnecessary_wraps, clippy::let_unit_value)]
#![warn(unused_imports)]

extern crate wildcard_imports_helper;

use crate::fn_mod::foo;
//~^ wildcard_imports
use crate::mod_mod::inner_mod;
//~^ wildcard_imports
use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
//~^ wildcard_imports
use crate::struct_mod::{A, inner_struct_mod};
//~^ wildcard_imports

#[allow(unused_imports)]
use wildcard_imports_helper::inner::inner_for_self_import::inner_extern_bar;
//~^ wildcard_imports
use wildcard_imports_helper::prelude::v1::*;
use wildcard_impo [...]

2025-04-05 10:30 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/14280835660/job/40030211397) [(plain)](https://github.com/rust-lang/rust/commit/6d87d32f40077691a0c147721b70a6e1bb07ecb9/checks/40030211397/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
+++ <fixed output>
 //@edition:2015
 
... 14 lines skipped ...
 use crate::mod_mod::inner_mod;
 //~^ wildcard_imports
-use crate::multi_fn_mod::{multi_bar, multi_foo, multi_inner_mod};
+use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
 //~^ wildcard_imports
 #[macro_use]
... 5 lines skipped ...
 use wildcard_imports_helper::inner::inner_for_self_import::inner_extern_bar;
 //~^ wildcard_imports
-use wildcard_imports_helper::{ExternA, extern_foo};
+use wildcard_imports_helper::{extern_foo, ExternA};
 //~^ wildcard_imports
 
... 107 lines skipped ...
         use wildcard_imports_helper::inner::inner_for_self_import::{self, inner_extern_foo};
         //~^ wildcard_imports
-        use wildcard_imports_helper::{ExternA, extern_foo};
+        use wildcard_imports_helper::{extern_foo, ExternA};
         //~^ wildcard_imports
 
... 17 lines skipped ...
 
     fn test_extern_reexported() {
-        use wildcard_imports_helper::{ExternExportedEnum, ExternExportedStruct, extern_exported};
+        use wildcard_imports_helper::{extern_exported, ExternExportedStruct, ExternExportedEnum};
         //~^ wildcard_imports
 
... 25 lines skipped ...
 
 fn test_reexported() {
-    use crate::in_fn_test::{ExportedEnum, ExportedStruct, exported};
+    use crate::in_fn_test::{exported, ExportedStruct, ExportedEnum};
     //~^ wildcard_imports
 
... 102 lines skipped ...
     }
 }

Full unnormalized output:
//@edition:2015

//@aux-build:wildcard_imports_helper.rs

// the 2015 edition here is needed because edition 2018 changed the module system
// (see https://doc.rust-lang.org/edition-guide/rust-2018/path-changes.html) which means the lint
// no longer detects some of the cases starting with Rust 2018.

#![warn(clippy::wildcard_imports)]
#![allow(unused, clippy::unnecessary_wraps, clippy::let_unit_value)]
#![warn(unused_imports)]

extern crate wildcard_imports_helper;

use crate::fn_mod::foo;
//~^ wildcard_imports
use crate::mod_mod::inner_mod;
//~^ wildcard_imports
use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
//~^ wildcard_imports
#[macro_use]
use crate::struct_mod::{A, inner_struct_mod};
//~^ wildcard_imports

#[allow(unused_imports)]
use wildcard_imports_helper::inner::inner_for_self_import;
use wildcard_imports_helper::inner::inner_for_self_import::inner_extern_bar;
//~^ wildcard_imports
use wildcard_imports_helper::{extern_foo, ExternA};
//~^ wildcard_imports

use std::io::prelude::*;
use wildcard_imports_helper::extern_prelude::v1::*;
use wildcard_imports_helper::prelude::v1::*;

struct ReadFoo;

impl Read for ReadFoo {
    fn read(&mut self, _buf: &mut [u8]) -> std::io::Result<usize> {
        Ok(0)
    }
}

mod fn_mod {
    pub fn foo() {}
---
        pub fn foo() {}
    }
}

mod multi_fn_mod {
    pub fn multi_foo() {}
    pub fn multi_bar() {}
    pub fn multi_baz() {}
    pub mod multi_inner_mod {
        pub fn foo() {}
    }
}

mod struct_mod {
---
mod underscore_mod {
    // allow use of `deref` so that `clippy --fix` includes `Deref`.
    #![allow(noop_method_call)]

    mod exports_underscore {
        pub use std::ops::Deref as _;
        pub fn dummy() {}
    }

    mod exports_underscore_ish {
        pub use std::ops::Deref as _Deref;
        pub fn dummy() {}
    }

    fn does_not_lint() {
        use self::exports_underscore::*;
        let _ = (&0).deref();
        dummy();
    }

    fn does_lint() {
        use self::exports_underscore_ish::{_Deref, dummy};
        //~^ wildcard_imports
        let _ = (&0).deref();
        dummy();
    }
}

fn main() {
    foo();
    multi_foo();
    multi_bar();
    multi_inner_mod::foo();
    inner_mod::foo();
    extern_foo();
    inner_extern_bar();

    let _ = A;
    let _ = inner_struct_mod::C;
    let _ = ExternA;
    let _ = PreludeModAnywhere;
    let _ = ExternPreludeModAnywhere;

    double_struct_import_test!();
    double_struct_import_test!();
}

---

        foo();
    }

    fn test_extern() {
        use wildcard_imports_helper::inner::inner_for_self_import::{self, inner_extern_foo};
        //~^ wildcard_imports
        use wildcard_imports_helper::{extern_foo, ExternA};
        //~^ wildcard_imports

        inner_for_self_import::inner_extern_foo();
        inner_extern_foo();

        extern_foo();

        let _ = ExternA;
    }

    fn test_inner_nested() {
        #[rustfmt::skip]
        use self::{inner::inner_foo, inner2::inner_bar};
        //~^ wildcard_imports
        //~| wildcard_imports

        inner_foo();
        inner_bar();
    }

    fn test_extern_reexported() {
        use wildcard_imports_helper::{extern_exported, ExternExportedStruct, ExternExportedEnum};
        //~^ wildcard_imports

        extern_exported();
        let _ = ExternExportedStruct;
        let _ = ExternExportedEnum::A;
    }
---
    }
}

fn test_reexported() {
    use crate::in_fn_test::{exported, ExportedStruct, ExportedEnum};
    //~^ wildcard_imports

    exported();
    let _ = ExportedStruct;
    let _ = ExportedEnum::A;
}

#[rustfmt::skip]
fn test_weird_formatting() {
    use crate:: in_fn_test::exported;
    //~^ wildcard_imports
    use crate:: fn_mod::foo;

    exported();
    foo();
}

---

error: actual output differed from expected
Execute `cargo uibless` to update `tests/ui/wildcard_imports_2021.edition2018.fixed` to the actual output
--- tests/ui/wildcard_imports_2021.edition2018.fixed
+++ <fixed output>
 //@revisions: edition2018 edition2021
 //@[edition2018] edition:2018
... 12 lines skipped ...
 use crate::mod_mod::inner_mod;
 //~^ wildcard_imports
-use crate::multi_fn_mod::{multi_bar, multi_foo, multi_inner_mod};
+use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
 //~^ wildcard_imports
 use crate::struct_mod::{A, inner_struct_mod};
... 4 lines skipped ...
 //~^ wildcard_imports
 use wildcard_imports_helper::prelude::v1::*;
-use wildcard_imports_helper::{ExternA, extern_foo};
+use wildcard_imports_helper::{extern_foo, ExternA};
 //~^ wildcard_imports
 
... 104 lines skipped ...
         use wildcard_imports_helper::inner::inner_for_self_import::{self, inner_extern_foo};
         //~^ wildcard_imports
-        use wildcard_imports_helper::{ExternA, extern_foo};
+        use wildcard_imports_helper::{extern_foo, ExternA};
         //~^ wildcard_imports
 
... 17 lines skipped ...
 
     fn test_extern_reexported() {
-        use wildcard_imports_helper::{ExternExportedEnum, ExternExportedStruct, extern_exported};
+        use wildcard_imports_helper::{extern_exported, ExternExportedStruct, ExternExportedEnum};
         //~^ wildcard_imports
 
... 25 lines skipped ...
 
 fn test_reexported() {
-    use crate::in_fn_test::{ExportedEnum, ExportedStruct, exported};
+    use crate::in_fn_test::{exported, ExportedStruct, ExportedEnum};
     //~^ wildcard_imports
 
... 102 lines skipped ...
     }
 }

Full unnormalized output:
//@revisions: edition2018 edition2021
//@[edition2018] edition:2018
//@[edition2021] edition:2021

//@aux-build:wildcard_imports_helper.rs

#![warn(clippy::wildcard_imports)]
#![allow(unused, clippy::unnecessary_wraps, clippy::let_unit_value)]
#![warn(unused_imports)]

extern crate wildcard_imports_helper;

use crate::fn_mod::foo;
//~^ wildcard_imports
use crate::mod_mod::inner_mod;
//~^ wildcard_imports
use crate::multi_fn_mod::{multi_foo, multi_bar, multi_inner_mod};
//~^ wildcard_imports
use crate::struct_mod::{A, inner_struct_mod};
//~^ wildcard_imports

#[allow(unused_imports)]
use wildcard_imports_helper::inner::inner_for_self_import::inner_extern_bar;
//~^ wildcard_imports
use wildcard_imports_helper::prelude::v1::*;
use wildcard_impo [...]

2025-04-06 08:46 UTC, ismailarilik commented
How can I update "*.fixed" files? `./x test tests/ui --bless` is not producing any change.

2025-04-29 17:25 UTC, jieyouxu commented
> How can I update "*.fixed" files? `./x test tests/ui --bless` is not producing any change.

I believe the failing tests are clippy tests, not rustc/compiletest tests. You may need to rebless clippy tests via something like

```bash
$ ./x test clippy --bless
```

2025-05-01 14:45 UTC, jieyouxu commented
r? query-system

2025-05-01 15:54 UTC, oli-obk commented
@bors try @rust-timer queue

2025-05-01 15:54 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2025-05-01 18:02 UTC, rust-timer commented
Queued 9d711dcae3bcbeb0efda0beffb8e957488893e63 with parent 0e517d38ad0e72f93c734b14fabd4bb9b7441de6, future [comparison URL](https://perf.rust-lang.org/compare.html?start=0e517d38ad0e72f93c734b14fabd4bb9b7441de6&end=9d711dcae3bcbeb0efda0beffb8e957488893e63).
There is currently 1 preceding artifact in the [queue](https://perf.rust-lang.org/status.html).
It will probably take at least ~1.8 hours until the benchmark run finishes.
<!-- rust-timer: temporary -->

2025-05-01 19:51 UTC, rust-timer commented
Finished benchmarking commit (9d711dcae3bcbeb0efda0beffb8e957488893e63): [comparison URL](https://perf.rust-lang.org/compare.html?start=0e517d38ad0e72f93c734b14fabd4bb9b7441de6&end=9d711dcae3bcbeb0efda0beffb8e957488893e63&stat=instructions:u).

### Overall result: ❌✅ regressions and improvements - no action needed


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

@bors rollup=never
@rustbot label: -S-waiting-on-perf -perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=0e517d38ad0e72f93c734b14fabd4bb9b7441de6&end=9d711dcae3bcbeb0efda0beffb8e957488893e63&stat=instructions:u)
This is the most reliable metric that we have; it was used to determine the overall result at the top of this comment. However, even this metric can sometimes exhibit noise.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | 0.6%  | [0.4%, 0.7%]   | 2     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -0.1% | [-0.1%, -0.1%] | 1     |
| All ❌✅ (primary)                 | -     | -              | 0     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=0e517d38ad0e72f93c734b14fabd4bb9b7441de6&end=9d711dcae3bcbeb0efda0beffb8e957488893e63&stat=max-rss)
<details>
<summary>Results (primary -0.1%, secondary -0.8%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.8%  | [0.4%, 1.4%]   | 10    |
| Regressions ❌ <br /> (secondary)  | 2.2%  | [2.2%, 2.2%]   | 1     |
| Improvements ✅ <br /> (primary)   | -0.9% | [-1.9%, -0.4%] | 12    |
| Improvements ✅ <br /> (secondary) | -3.7% | [-3.7%, -3.7%] | 1     |
| All ❌✅ (primary)                 | -0.1% | [-1.9%, 1.4%]  | 22    |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=0e517d38ad0e72f93c734b14fabd4bb9b7441de6&end=9d711dcae3bcbeb0efda0beffb8e957488893e63&stat=cycles:u)
<details>
<summary>Results (primary -0.2%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.6%  | [0.4%, 0.9%]   | 6     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -0.5% | [-1.0%, -0.4%] | 14    |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -0.2% | [-1.0%, 0.9%]  | 20    |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=0e517d38ad0e72f93c734b14fabd4bb9b7441de6&end=9d711dcae3bcbeb0efda0beffb8e957488893e63&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 768.358s -> 769.173s (0.11%)
**Artifact size**: 365.48 MiB -> 365.43 MiB (-0.01%)

2025-05-02 14:37 UTC, oli-obk requested changes

2025-05-02 14:37 UTC, oli-obk commented on compiler/rustc_middle/src/ty/print/pretty.rs
> +    // Precatious is taken below in the loop so we can allow this lint here.
```suggestion
    // Precautions are taken below in the loop so we can allow this lint here.
```

2025-05-02 14:37 UTC, oli-obk commented on compiler/rustc_middle/src/ty/print/pretty.rs
> +    // Precatious is taken below in the loop so we can allow this lint here.
Tho this is only used in diagnostics, right? we could just use an IndexMap for `unique_symbols_rev`, too?

2025-05-05 13:36 UTC, ismailarilik commented on compiler/rustc_middle/src/ty/print/pretty.rs
> +    // Precatious is taken below in the loop so we can allow this lint here.
Done.

2025-05-05 13:51 UTC, oli-obk approved these changes

2025-05-05 13:52 UTC, oli-obk commented
@bors r+

2025-05-06 04:45 UTC, merged

2025-05-06 06:20 UTC, rust-timer commented
Finished benchmarking commit (7295b08a17d1107155acd4b552069e3705b0ab1f): [comparison URL](https://perf.rust-lang.org/compare.html?start=4a0969e06dbeaaa43914d2d00b2e843d49aa3886&end=7295b08a17d1107155acd4b552069e3705b0ab1f&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=4a0969e06dbeaaa43914d2d00b2e843d49aa3886&end=7295b08a17d1107155acd4b552069e3705b0ab1f&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=4a0969e06dbeaaa43914d2d00b2e843d49aa3886&end=7295b08a17d1107155acd4b552069e3705b0ab1f&stat=max-rss)
<details>
<summary>Results (primary -0.2%, secondary 2.4%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 2.0%  | [1.2%, 3.4%]   | 3     |
| Regressions ❌ <br /> (secondary)  | 2.4%  | [2.4%, 2.4%]   | 1     |
| Improvements ✅ <br /> (primary)   | -0.7% | [-1.4%, -0.4%] | 15    |
| Improvements ✅ <br /> (secondary) | -     | -              | 0     |
| All ❌✅ (primary)                 | -0.2% | [-1.4%, 3.4%]  | 18    |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=4a0969e06dbeaaa43914d2d00b2e843d49aa3886&end=7295b08a17d1107155acd4b552069e3705b0ab1f&stat=cycles:u)
<details>
<summary>Results (primary -0.6%, secondary -2.2%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.6%  | [0.4%, 1.1%]   | 16    |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -1.7% | [-6.8%, -0.4%] | 16    |
| Improvements ✅ <br /> (secondary) | -2.2% | [-2.9%, -1.5%] | 2     |
| All ❌✅ (primary)                 | -0.6% | [-6.8%, 1.1%]  | 32    |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=4a0969e06dbeaaa43914d2d00b2e843d49aa3886&end=7295b08a17d1107155acd4b552069e3705b0ab1f&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 770.615s -> 771.005s (0.05%)
**Artifact size**: 365.41 MiB -> 365.42 MiB (0.00%)