Implement split_pattern on slices
rust-lang/rust pull request #131340
Opened 2024-10-06 22:19 UTC by eduardorittner

From #49036, adds a `split_pattern` method on slices which takes a second slice and splits using that one.
I was unsure about where to add additional tests, specifically to test reverse iteration using the `next_back` method, my guess would be in library/core/tests/slice.rs, however when looking at the tests I saw no test for unstable features, so I was unsure if I should add them somewhere else.

2024-10-06 22:30 UTC, fmease requested changes

2024-10-06 22:30 UTC, fmease commented on compiler/rustc_feature/src/unstable.rs
> +    (unstable, split_pattern, "CURRENT_RUSTC_VERSION", Some(49036)),
```suggestion
```

Library features shouldn't (and don't need to) be declared inside the compiler.

2024-10-06 22:30 UTC, fmease commented on compiler/rustc_span/src/symbol.rs
> +        split_pattern,
```suggestion
```

(see above)

2024-10-06 22:30 UTC, fmease commented on tests/ui/feature-gates/feature-gate-split-pattern.rs
This UI test should be removed. It's only required to exist right now by tidy because you declared a library feature as a compiler feature, too. The doctest should be sufficient.

2024-10-06 22:46 UTC, tgross35 commented
This should get proposed via an ACP, which is one of the issue templates at https://github.com/rust-lang/libs-team/issues. That gives the libs-api team a chance to figure out if the new API makes sense before you put too much effort into the implementation.

> I was unsure about where to add additional tests, specifically to test reverse iteration using the `next_back` method, my guess would be in library/core/tests/slice.rs, however when looking at the tests I saw no test for unstable features, so I was unsure if I should add them somewhere else.

As fmease mentioned, library features don't really need to touch anything outside of `library/`, no compiler changes are needed. `library/core/tests/iter` would be a reasonable place to test this.

2024-10-06 22:56 UTC, eduardorittner commented on tests/ui/feature-gates/feature-gate-split-pattern.rs
Done! I was following the rustc-dev-guide and thought that all unstable features should be declared in the compiler, thanks for clarifying!

2024-10-07 01:11 UTC, eduardorittner commented
Thank you so much for your help I issued an APC at https://github.com/rust-lang/libs-team/issues/457 and will be going from there

2024-10-07 01:24 UTC, eduardorittner commented
Thank you so much for your help I issued an APC at https://github.com/rust-lang/libs-team/issues/457 and will be going from there

2026-09-22 01:58 UTC, clarfonthey commented
Since this has merge conflicts, is pretty old and simple, and I'm not 100% sure when the ACP will be accepted, I'm just going to close this for now. I think that the idea is pretty promising but might want a bit more thorough design, and since the code will still be preserved here on the PR, I'd rather just close this for now to clean up the backlog.

Please do feel free to comment more on the ACP if you have had more thoughts on this in the last two years; we are going to need to go back through some of the older ACPs at some point, and this seems like one that people might want to look at. I just don't think it is reasonable to leave this PR open in the meantime.

2026-09-22 01:58 UTC, closed without merging