Delay ambiguous intra-doc link resolution after Cache has been populated
rust-lang/rust pull request #131691
Opened 2024-10-14 16:00 UTC by GuillaumeGomez

Fixes https://github.com/rust-lang/rust/issues/130233.

I was getting nowhere with #130278. I took a wrong turn at some point and ended making way too many changes so instead I started again back from 0 and this time it worked out as expected.

r? @notriddle

2024-10-14 23:22 UTC, notriddle requested changes

2024-10-14 23:53 UTC, GuillaumeGomez commented on src/librustdoc/passes/collect_intra_doc_links.rs
> +    disambiguator: Option<Disambiguator>,
One word: reexports. :)

2024-10-14 23:55 UTC, GuillaumeGomez commented on src/librustdoc/passes/collect_intra_doc_links.rs
> +    /// inferring them (if possible).
Can be done as a follow-up but if you have ideas for improvements, it's very welcome!

2024-10-14 23:56 UTC, GuillaumeGomez commented on src/librustdoc/passes/collect_intra_doc_links.rs
> +        return true;
Good idea!

2024-10-14 23:58 UTC, GuillaumeGomez commented on src/librustdoc/passes/collect_intra_doc_links.rs
> +        return true;
Ah actually not really: we need the `kinds` variable that is computed at the beginning...

2024-10-14 23:58 UTC, GuillaumeGomez commented
Updated!

2024-10-15 00:06 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/11336748375/job/31527188296) [(plain)](https://github.com/rust-lang/rust/commit/e0fb0dcfbc8f4078fb7d829b1cfb071b30ac6a9f/checks/31527188296/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#13 2.916 Building wheels for collected packages: reuse
#13 2.917   Building wheel for reuse (pyproject.toml): started
#13 3.164   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 3.165   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132720 sha256=026f3bb0f1aa8090b861fd0a0939cb1a782396d84c8aab7875096557d637a0f6
#13 3.165   Stored in directory: /tmp/pip-ephem-wheel-cache-d90k1du8/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#13 3.168 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#13 3.556 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#13 3.557 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 4.090 Collecting virtualenv
#13 4.090 Collecting virtualenv
#13 4.143   Downloading virtualenv-20.26.6-py3-none-any.whl (6.0 MB)
#13 4.375      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 26.1 MB/s eta 0:00:00
#13 4.434 Collecting platformdirs<5,>=3.9.1
#13 4.442   Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
#13 4.464 Collecting distlib<1,>=0.3.7
#13 4.483      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 53.0 MB/s eta 0:00:00
#13 4.521 Collecting filelock<4,>=3.12.2
#13 4.529   Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
#13 4.529   Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
#13 4.610 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 4.799 Successfully installed distlib-0.3.9 filelock-3.16.1 platformdirs-4.3.6 virtualenv-20.26.6
#13 DONE 4.9s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      237504 kB
DirectMap2M:     9199616 kB
DirectMap1G:     9437184 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.04s
##[endgroup]
WARNING: `rust.download-rustc` is enabled. The `rust.channel` option will be overridden by the CI rustc's channel.
downloading https://static.rust-lang.org/dist/2024-09-22/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz
---
                         report_diagnostic(
                             self.cx.tcx,
                             BROKEN_INTRA_DOC_LINKS,
-                            format!(
-                                "all items matching `{path_str}` are private or doc(hidden)"
-                            ),
+                            format!("all items matching `{path_str}` are private or doc(hidden)"),
                             &diag_info,
                             |diag, sp, _| {
                                 if let Some(sp) = sp {
fmt error: Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/src/librustdoc/passes/strip_priv_imports.rs" "/checkout/tests/run-make/print-cfg/rmake.rs" "/checkout/tests/run-make/rustdoc-with-output-option/rmake.rs" "/checkout/tests/run-make/rustdoc-with-output-option/src/lib.rs" "/checkout/src/librustdoc/passes/lint/unescaped_backticks.rs" "/checkout/src/librustdoc/passes/lint/html_tags.rs" "/checkout/src/librustdoc/passes/lint/check_code_block_syntax.rs" "/checkout/src/librustdoc/passes/lint/redundant_explicit_links.rs" "/checkout/src/librustdoc/passes/lint/bare_urls.rs" "/checkout/src/librustdoc/passes/lint/unportable_markdown.rs" "/checkout/src/librustdoc/passes/propagate_stability.rs" "/checkout/tests/run-make/wasm-custom-section/rmake.rs" "/checkout/tests/run-make/wasm-custom-section/foo.rs" "/checkout/tests/run-make/wasm-custom-section/bar.rs" "/checkout/src/librustdoc/passes/propagate_doc_cfg.rs" "/checkout/src/librustdoc/passes/collect_trait_impls.rs" "/checkout/src/librustdoc/passes/strip_private.rs" "/checkout/src/librustdoc/passes/lint.rs" "/checkout/src/librustdoc/passes/check_doc_test_visibility.rs" "/checkout/src/librustdoc/passes/strip_aliased_non_local.rs" "/checkout/src/librustdoc/passes/collect_intra_doc_links.rs" "/checkout/src/librustdoc/passes/strip_hidden.rs" "/checkout/src/librustdoc/passes/calculate_doc_coverage.rs" "/checkout/src/librustdoc/passes/stripper.rs" "/checkout/src/librustdoc/passes/mod.rs" "/checkout/tests/run-make/rustdoc-cfgspec-parsing/rmake.rs" "/checkout/tests/run-make/rustdoc-cfgspec-parsing/foo.rs" "/checkout/tests/run-make/raw-dylib-alt-calling-convention/driver.rs" "/checkout/tests/run-make/raw-dylib-alt-calling-convention/rmake.rs" "/checkout/tests/run-make/raw-dylib-alt-calling-convention/lib.rs" "/checkout/src/librustdoc/clean/cfg.rs" "/checkout/src/librustdoc/clean/types.rs" "/checkout/src/librustdoc/clean/inline.rs" "/checkout/tests/run-make/c-unwind-abi-catch-panic/main.rs" "/checkout/tests/run-make/c-unwind-abi-catch-panic/rmake.rs" "/checkout/src/librustdoc/clean/utils/tests.rs" "/checkout/src/librustdoc/clean/blanket_impl.rs" "/checkout/src/librustdoc/clean/simplify.rs" "/checkout/tests/run-make/cross-lang-lto-riscv-abi/rmake.rs" "/checkout/tests/run-make/cross-lang-lto-riscv-abi/riscv-xlto.rs" "/checkout/src/librustdoc/clean/types/tests.rs" "/checkout/src/librustdoc/clean/render_macro_matchers.rs" "/checkout/src/librustdoc/clean/auto_trait.rs" "/checkout/src/librustdoc/clean/utils.rs" "/checkout/tests/run-make/naked-symbol-visibility/rmake.rs" "/checkout/tests/run-make/naked-symbol-visibility/a_rust_dylib.rs" "/checkout/src/librustdoc/clean/cfg/tests.rs" "/checkout/src/librustdoc/clean/mod.rs" "/checkout/src/librustdoc/markdown.rs" "/checkout/tests/run-make/extern-fn-slice-no-ice/rmake.rs" "/checkout/tests/run-make/extern-fn-slice-no-ice/test.rs" "/checkout/src/librustdoc/json/import_finder.rs" "/checkout/src/librustdoc/json/conversions.rs" "/checkout/src/librustdoc/json/mod.rs" "/checkout/src/librustdoc/doctest.rs" "/checkout/src/librustdoc/scrape_examples.rs" "/checkout/src/librustdoc/docfs.rs" "/checkout/src/librustdoc/fold.rs" "/checkout/src/librustdoc/config.rs" "/checkout/src/librustdoc/core.rs" "/checkout/src/librustdoc/externalfiles.rs" "/checkout/src/librustdoc/theme.rs" "/checkout/src/librustdoc/visit.rs" "/checkout/tests/run-make/lto-no-link-whole-rlib/lib2.rs"` failed.
If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
  local time: Tue Oct 15 00:05:56 UTC 2024
  network time: Tue, 15 Oct 2024 00:05:56 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-10-15 13:30 UTC, GuillaumeGomez commented on src/librustdoc/passes/collect_intra_doc_links.rs
> +    disambiguator: Option<Disambiguator>,
So with:

```rust
//! [struct@X]

mod a {
    pub struct X;
}

mod b {
    pub struct X;
}

pub use a::*;
pub use b::*;
```

We get:

```
warning: public documentation for `bar` links to private item `X`
 --> bar.rs:1:6
  |
1 | //! [struct@X]
  |      ^^^^^^^^ this item is private
  |
  = note: this link will resolve properly if you pass `--document-private-items`
  = note: `#[warn(rustdoc::private_intra_doc_links)]` on by default
```

I think it's a bug but for now, let's simply remove this `disambiguator` as it doesn't seem to work.

2024-10-15 13:44 UTC, GuillaumeGomez commented
Updated!

2024-10-15 15:47 UTC, GuillaumeGomez commented
@bors ready

2024-10-16 23:14 UTC, merged