Add support for wasm exception handling to Emscripten target
rust-lang/rust pull request #131830
Opened 2024-10-17 12:05 UTC by hoodmane

This is a draft because we need some additional setting for the Emscripten target to select between the old exception handling and the new exception handling. I don't know how to add a setting like that, would appreciate advice from Rust folks. We could maybe choose to use the new exception handling if `Ctarget-feature=+exception-handling` is passed? I tried this but I get errors from llvm so I'm not doing it right.

cc @kleisauke @kripken @workingjubilee @alexcrichton

2024-10-18 23:51 UTC, workingjubilee commented
> This is a draft because we need some additional setting for the Emscripten target to select between the old exception handling and the new exception handling.

Hm. I feel a little out-of-context here. Could you explain
1. what makes the "old" exception-handling old?
1. what makes the "new" exception-handling new?
1. what parts of an emscripten program must agree on which exception handling we're using?
  - in the minimal case: linkage of a Rust main.rs, std, and Emscripten?
  - in other configurations of linkage that Emscripten supports?
1. why we must have a toggle for this?

Is "new" meaning the wasm exception-handling proposal with `exnref` and wasm-level `try` blocks?

2024-10-21 09:00 UTC, hoodmane commented
To make matters worse, [the new exception handling support was changed in October of 2023](https://github.com/WebAssembly/exception-handling/issues/281) so there are now two new exception handling variants:

* the old new exception handling, which is universally supported but also deprecated, and
* the new new exception handling, which is currently only supported in the most recent release of Firefox.

I think there is no difference in the IR the frontend generates between the old new and new new variants, though the lowering pass will change, the object file format is different, and so the new variant will require a different setting code generation time. I think it's a fairly simple transform to adjust an old object file to support the new variant, so maybe there will be support to link the old objects to new binaries by transparently fixing them up. @sbc100?

So we may end up with three ABIs.

2024-10-21 16:57 UTC, sbc100 commented
> I think there is no difference in the IR the frontend generates between the old new and new new variants

That is true today but the plan is to make llvm support the new variant natively ASAP.  However at the at point I imagine there will be a lowering pass added to binaryen to support the previous version, so you should still only need a single object file format / libc build.

2024-10-21 17:00 UTC, sbc100 commented
> Unfortunately, Emscripten has tons of different ABIs.

While its true emscripten supports a lot of different options almost all of them are link-time only settings and don't effect the object file ABI.     There are only subset of settings that effect the object format (i.e. that are vaslid at compile time): https://github.com/emscripten-core/emscripten/blob/10cb9d46cdd17e7a96de68137c9649d9a630fbc7/tools/settings.py#L81-L112.  Note that WASM_BIGINT is not one of them.

2024-10-21 19:43 UTC, sbc100 commented
> Are `MAIN_MODULE`/`SIDE_MODULE` really compile time settings? I only pass them in LDFLAGS...

Only in the sense that they enable `-fPIC`.. you can use `-fPIC` itself instead if you prefer.

2024-10-21 21:44 UTC, workingjubilee commented
In general, "`more_compiler_abi_flags == more_compatibility`" is actually "`more_compiler_flags == incompatibility`", because you now have to have even more flags set to the correct values to compile code correctly.

So I would prefer that we not expose, nor even pretend that we wish to offer compatibility with, "tons of different ABIs". We already have quite enough problems with ABI-affecting flags. It does not really take many booleans to be able to count to a million, and a few million untested variants of Rust is not a thing we should be trying to support.

**Having said that**, supporting the new ABI behind an *unstable* flag that will then be ditched at some point has precedent, especially for wasm targets, see https://github.com/rust-lang/rust/pull/117919

2024-10-21 22:01 UTC, workingjubilee commented
If a `-Z` flag for such a transition period is acceptable, @hoodmane, then opening an MCP, like so, would be the next step: https://github.com/rust-lang/compiler-team/issues/703

While we Just Merged the soundness-fixing change of https://github.com/rust-lang/rust/pull/131533 we usually do MCPs for Significant Changes To Preexisting Targets, especially ones that require this... shindig. A transition period and involvement of rustc's CLI.

They're usually sensible enough that it's a bit of a formality, so don't overthink it, the answers to my questions are more-or-less what you would paste in there, with a bit of additional stitching up to explain why e.g. Pyodide needs a flag for this transition and we don't want to do just a hard cut over.

2024-10-22 12:16 UTC, hoodmane commented
> do MCPs

Sounds good. Thanks again @workingjubilee for all of your help. I really appreciate it.

> It does not really take many booleans to be able to count to a million, and a few million untested variants of Rust is not a thing we should be trying to support.

Yeah this is why I'm raising this as a concern. It seems clearly out of scope to support all of them. It's important to have a solution to this in mind ahead of time. I would prefer that Rust only supports the 2 configurations I care about and has real test coverage for them, but different projects will standardize on different options. It's a thorny issue coordination problem. It would be nice if Emscripten could formalize specific triples...

2024-10-22 12:17 UTC, hoodmane commented
I think the fact that the ABIs can be nearly linearly sorted by runtime support date is helpful. Instead of having 20 different booleans ==> 2^20 different options. But if you assign a date to each of the 20 booleans and only choose which date you want, then there are 21 options. Then if you only support:

* the most recent date with a `-Z` flag
* some option that you think is "old enough to be universally available"

maybe it's good enough. Having all the in between steps available as `-Z` flags would be helpful for debugging the target.

2024-10-31 14:33 UTC, hoodmane commented
Okay I opened a MCP:
https://github.com/rust-lang/compiler-team/issues/801

2024-12-03 10:55 UTC, RalfJung commented
> >  what parts of an emscripten program must agree on which exception handling we're using?
>
> We need different IR, different object files, and different linker arguments. But it's transparent to Rust/C++/C code.

This does not answer the question: what happens when I link together crates that were compiled with different values for this flag?

If the answer is Undefined Behavior, that must at least be very clearly documented as part pf the flag docs, and that is a blocker for stabilizing this flag.

2024-12-03 11:01 UTC, hoodmane commented
I just signed up for Zulip. Thanks @RalfJung.

2024-12-17 19:07 UTC, workingjubilee commented
@hoodmane Remember to tag this with rustbot review when you update it.

2025-01-02 14:42 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12583831941/job/35072226178) [(plain)](https://github.com/rust-lang/rust/commit/ad37cc8a3e26031e69973301e54177f02c862121/checks/35072226178/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#22 exporting to docker image format
#22 sending tarball 30.4s done
#22 DONE 36.0s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
failures:

---- [codegen] tests/codegen/emcripten-catch-unwind.rs stdout ----

error: verification with 'FileCheck' failed
status: exit status: 1
command: "/usr/lib/llvm-18/bin/FileCheck" "--input-file" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/emcripten-catch-unwind/emcripten-catch-unwind.ll" "/checkout/tests/codegen/emcripten-catch-unwind.rs" "--check-prefix=CHECK" "--allow-unused-prefixes" "--dump-input-context" "100"
--- stderr -------------------------------
/checkout/tests/codegen/emcripten-catch-unwind.rs:49:12: error: CHECK: expected string not found in input
/checkout/tests/codegen/emcripten-catch-unwind.rs:49:12: error: CHECK: expected string not found in input
 // CHECK: [[ALLOCA:%.*]] = alloca
           ^
/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/emcripten-catch-unwind/emcripten-catch-unwind.ll:14:7: note: scanning from here
      ^
      ^
/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/emcripten-catch-unwind/emcripten-catch-unwind.ll:22:10: note: possible intended match here
 %catchpad2.i = catchpad within %catchswitch1.i [ptr null]

Input file: /checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/emcripten-catch-unwind/emcripten-catch-unwind.ll
Check file: /checkout/tests/codegen/emcripten-catch-unwind.rs


-dump-input=help explains the following input dump.
Input was:
<<<<<<
<<<<<<
            1: ; ModuleID = 'emcripten_catch_unwind.df8ae0c697b5edf5-cgu.0' 
            2: source_filename = "emcripten_catch_unwind.df8ae0c697b5edf5-cgu.0" 
            3: target datalayout = "e-m:e-p:32:32-p10:8:8-p20:8:8-i64:64-f128:64-n32:64-S128-ni:1:10:20" 
            4: target triple = "wasm32-unknown-emscripten" 
            5:  
            6: ; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none) uwtable 
            7: define noundef i32 @ptr_size() unnamed_addr #0 { 
            9:  ret i32 4 
           10: } 
           11:  
           12: ; Function Attrs: uwtable 
           12: ; Function Attrs: uwtable 
           13: define noundef i32 @test_catch_unwind(ptr nocapture noundef nonnull readonly %try_fn, ptr noundef %data, ptr nocapture noundef nonnull readonly %catch_fn) unnamed_addr #1 personality ptr @__gxx_wasm_personality_v0 { 
           14: start: 
check:49'0           X error: no match found
           15:  invoke void %try_fn(ptr %data) 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           16:  to label %__rust_try.exit unwind label %catchswitch.i 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:49'0     ~
check:49'0     ~
           18: catchswitch.i: ; preds = %start 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           19:  %catchswitch1.i = catchswitch within none [label %catchpad.i] unwind to caller 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:49'0     ~
check:49'0     ~
           21: catchpad.i: ; preds = %catchswitch.i 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           22:  %catchpad2.i = catchpad within %catchswitch1.i [ptr null] 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:49'1              ?                                                  possible intended match
           23:  %0 = tail call ptr @llvm.wasm.get.exception(token %catchpad2.i) 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           24:  %1 = tail call i32 @llvm.wasm.get.ehselector(token %catchpad2.i) 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           25:  call void %catch_fn(ptr %data, ptr %0) [ "funclet"(token %catchpad2.i) ] 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           26:  catchret from %catchpad2.i to label %__rust_try.exit 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:49'0     ~
check:49'0     ~
           28: __rust_try.exit: ; preds = %start, %catchpad.i 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           29:  %common.ret.op.i = phi i32 [ 0, %start ], [ 1, %catchpad.i ] 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           30:  ret i32 %common.ret.op.i 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~
           31: } 
check:49'0     ~~
check:49'0     ~
check:49'0     ~
           33: declare i32 @__gxx_wasm_personality_v0(...) unnamed_addr #2 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:49'0     ~
check:49'0     ~
           35: ; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           36: declare ptr @llvm.wasm.get.exception(token) #3 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:49'0     ~
check:49'0     ~
           38: ; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           39: declare i32 @llvm.wasm.get.ehselector(token) #3 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:49'0     ~
check:49'0     ~
           41: attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(none) uwtable "target-cpu"="generic" "target-features"="+exception-handling" } 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           42: attributes #1 = { uwtable "target-cpu"="generic" "target-features"="+exception-handling" } 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           43: attributes #2 = { "target-cpu"="generic" } 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           44: attributes #3 = { mustprogress nocallback nofree nosync nounwind willreturn } 
check:49'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
check:49'0     ~
check:49'0     ~
           46: !llv [...]

2025-01-02 16:08 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12585168147/job/35076369269) [(plain)](https://github.com/rust-lang/rust/commit/6e9ff3f3f36c6d05436659c3b8ba1b059d70eb23/checks/35076369269/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling rustc_codegen_ssa v0.0.0 (/checkout/compiler/rustc_codegen_ssa)
error: unnecessary parentheses around `if` condition
    --> compiler/rustc_codegen_ssa/src/back/link.rs:2471:19
     |
2471 |         } else if (sess.unstable_options.emscripten_wasm_eh) {
     |
     = note: `-D unused-parens` implied by `-D warnings`
     = help: to override `-D warnings` add `#[allow(unused_parens)]`
help: remove these parentheses
help: remove these parentheses
     |
2471 -         } else if (sess.unstable_options.emscripten_wasm_eh) {
2471 +         } else if sess.unstable_options.emscripten_wasm_eh {

error[E0615]: attempted to take value of method `unstable_options` on type `&rustc_session::Session`
    --> compiler/rustc_codegen_ssa/src/back/link.rs:2471:25
     |
     |
2471 |         } else if (sess.unstable_options.emscripten_wasm_eh) {
     |
help: use parentheses to call the method
     |
     |
2471 |         } else if (sess.unstable_options().emscripten_wasm_eh) {

error[E0615]: attempted to take value of method `unstable_options` on type `&rustc_session::Session`
   --> compiler/rustc_codegen_ssa/src/base.rs:392:52
    |
    |
392 |         && (sess.target.os != "emscripten" || sess.unstable_options.emscripten_wasm_eh)
    |
help: use parentheses to call the method
    |
    |
392 |         && (sess.target.os != "emscripten" || sess.unstable_options().emscripten_wasm_eh)

   Compiling rustc_privacy v0.0.0 (/checkout/compiler/rustc_privacy)
   Compiling rustc_hir_analysis v0.0.0 (/checkout/compiler/rustc_hir_analysis)
For more information about this error, try `rustc --explain E0615`.
```

</details>

2025-01-02 16:13 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12585281020/job/35076727594) [(plain)](https://github.com/rust-lang/rust/commit/6ca00923e7dfca72c61b5f722ed06b845306f96e/checks/35076727594/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#21 exporting to docker image format
#21 sending tarball 27.6s done
#21 DONE 33.0s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
   Compiling memchr v2.7.4
   Compiling adler v1.0.2
   Compiling rustc-demangle v0.1.24
   Compiling unwind v0.0.0 (/checkout/library/unwind)
error: unexpected `cfg` condition name: `emscripten_wasm_eh`
  |
  |
7 |     all(target_family = "wasm", any(not(target_os = "emscripten"), emscripten_wasm_eh)),
  |
  |
  = help: expected names are: `bootstrap`, `clippy`, `debug_assertions`, `doc`, `docsrs`, `doctest`, `feature`, `fmt_debug`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `test`, `ub_checks`, `unix`, and `windows`
  = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
           [lints.rust]
           [lints.rust]
           unexpected_cfgs = { level = "warn", check-cfg = ['cfg(emscripten_wasm_eh)'] }
  = help: or consider adding `println!("cargo::rustc-check-cfg=cfg(emscripten_wasm_eh)");` to the top of the `build.rs`
  = note: `-D unexpected-cfgs` implied by `-D warnings`
  = help: to override `-D warnings` add `#[allow(unexpected_cfgs)]`

error: could not compile `unwind` (lib) due to 1 previous error
```

</details>

2025-01-02 16:32 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12585442141/job/35077241801) [(plain)](https://github.com/rust-lang/rust/commit/a4fde11c37766dea80f8f83faab732c00d56336a/checks/35077241801/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    |
745 |     macro_rules! tracked {
    |     -------------------- when calling this macro
...
785 |     tracked!(emscripten_wasm_eh);
    |                                ^ missing tokens in macro arguments
note: while trying to match `,`
   --> compiler/rustc_interface/src/tests.rs:746:22
    |
    |
746 |         ($name: ident, $non_default_value: expr) => {

    Checking rustc_driver_impl v0.0.0 (/checkout/compiler/rustc_driver_impl)
error: could not compile `rustc_interface` (lib test) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

</details>

2025-01-02 19:38 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12587545255/job/35083618178) [(plain)](https://github.com/rust-lang/rust/commit/242188625fea90d39018f971fab8d11ccc613651/checks/35083618178/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#22 exporting to docker image format
#22 sending tarball 26.6s done
#22 DONE 32.1s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---

4 LL | #[cfg(FALSE)]
5    |       ^^^^^
6    |
-    = help: expected names are: `clippy`, `debug_assertions`, `doc`, `doctest`, `fmt_debug`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `test`, `ub_checks`, `unix`, and `windows`
+    = help: expected names are: `clippy`, `debug_assertions`, `doc`, `doctest`, `emscripten_wasm_eh`, `fmt_debug`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `test`, `ub_checks`, `unix`, and `windows`
8    = help: to expect this configuration use `--check-cfg=cfg(FALSE)`
9    = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg.html> for more information about checking conditional configuration


The actual stderr differed from the expected stderr.
To update references, rerun the tests and pass the `--bless` flag
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args check-cfg/allow-same-level.rs`

error: 1 errors occurred comparing output.
status: exit status: 0
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/check-cfg/allow-same-level.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/check-cfg/allow-same-level" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--check-cfg=cfg()"
--- stderr -------------------------------
warning: unexpected `cfg` condition name: `FALSE`
##[warning]  --> /checkout/tests/ui/check-cfg/allow-same-level.rs:8:7
   |
   |
LL | #[cfg(FALSE)]
   |       ^^^^^
   |
   = help: expected names are: `clippy`, `debug_assertions`, `doc`, `doctest`, `emscripten_wasm_eh`, `fmt_debug`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `test`, `ub_checks`, `unix`, and `windows`
   = help: to expect this configuration use `--check-cfg=cfg(FALSE)`
   = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg.html> for more information about checking conditional configuration

warning: 1 warning emitted
------------------------------------------



---- [ui] tests/ui/check-cfg/cargo-build-script.rs stdout ----
Saved the actual stderr to "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/check-cfg/cargo-build-script/cargo-build-script.stderr"
diff of stderr:

4 LL | #[cfg(has_foo)]
6    |
6    |
-    = help: expected names are: `clippy`, `debug_assertions`, `doc`, `doctest`, `fmt_debug`, `has_bar`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `test`, `ub_checks`, `unix`, and `windows`
+    = help: expected names are: `clippy`, `debug_assertions`, `doc`, `doctest`, `emscripten_wasm_eh`, `fmt_debug`, `has_bar`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `test`, `ub_checks`, `unix`, and `windows`
9    = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
10             [lints.rust]



The actual stderr differed from the expected stderr.
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args check-cfg/cargo-build-script.rs`

error: 1 errors occurred comparing output.
status: exit status: 0
command: env -u RUSTC_LOG_COLOR CARGO_CRATE_NAME="build_script_build" RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/check-cfg/cargo-build-script.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_ [...]

2025-01-03 10:58 UTC, hoodmane commented on tests/ui/check-cfg/allow-same-level.stderr
> +   = help: expected names are: `clippy`, `debug_assertions`, `doc`, `doctest`, `emscripten_wasm_eh`, `fmt_debug`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `san
The `emscripten_wasm_eh` cfg name is needed as an implementation detail for `panic_unwind` and `unwind`. If there is some way to expose it only in the standard library and keep it out of the help messages that might be preferable but I didn't see any way to do that.

2025-01-03 10:59 UTC, hoodmane commented on tests/codegen/emscripten-catch-unwind.rs
Added missing s: em**s**cripten

2025-01-03 11:50 UTC, Urgau commented on tests/ui/check-cfg/allow-same-level.stderr
> +   = help: expected names are: `clippy`, `debug_assertions`, `doc`, `doctest`, `emscripten_wasm_eh`, `fmt_debug`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `san
No implementation detail should leak onto user-facing diagnostics, you need to remove the `ins!(sym::emscripten_wasm_eh, no_values);` from the `CheckCfg::fill_well_known` and instead "manually" add the cfg to the check-cfg section of the `Cargo.toml` of [`panic_unwind`](https://github.com/rust-lang/rust/blob/ac00fe89a121e9ca5e59c093c7c02aa296e55ece/library/panic_unwind/Cargo.toml#L26) and [`unwind`](https://github.com/rust-lang/rust/blob/ac00fe89a121e9ca5e59c093c7c02aa296e55ece/library/unwind/Cargo.toml#L40).

Something like this:
```diff
- check-cfg = []
+ check-cfg = ['cfg(emscripten_wasm_eh)']
```

2025-01-03 11:54 UTC, hoodmane commented on tests/ui/check-cfg/allow-same-level.stderr
> +   = help: expected names are: `clippy`, `debug_assertions`, `doc`, `doctest`, `emscripten_wasm_eh`, `fmt_debug`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `san
Thanks!

2025-01-03 11:59 UTC, Urgau commented on compiler/rustc_session/src/config/cfg.rs
> +    if sess.opts.unstable_opts.emscripten_wasm_eh {
Furthermore setting should only be set behind nightly. 
```suggestion
    // Nightly-only implementation detail for the `panic_unwind` and `unwind` crate.
    if sess.is_nightly_build() && sess.opts.unstable_opts.emscripten_wasm_eh {
```

2025-01-03 11:59 UTC, Urgau commented on compiler/rustc_session/src/config/cfg.rs
> +        ins!(sym::emscripten_wasm_eh, no_values);
```suggestion
```

2025-01-03 11:59 UTC, Urgau commented on library/unwind/src/lib.rs
> +    all(target_family = "wasm", any(not(target_os = "emscripten"), emscripten_wasm_eh)),
The cfg must also be gated behind a feature gate, please create one in https://github.com/rust-lang/rust/blob/f55a5d2e067629c7939a7d8373e19dc673552934/compiler/rustc_feature/src/unstable.rs#L183 and add it in https://github.com/rust-lang/rust/blob/f55a5d2e067629c7939a7d8373e19dc673552934/compiler/rustc_feature/src/builtin_attrs.rs#L18
and then add the feature gate where necessary.

2025-01-03 11:59 UTC, Urgau commented on library/unwind/src/lib.rs
> +#![cfg_attr(bootstrap, allow(unexpected_cfgs))]
No longer necessary. No crate should ever have `allow(unexpected_cfgs)` anyway.

2025-01-03 11:59 UTC, Urgau commented on compiler/rustc_session/src/config/cfg.rs
> +            (sym::emscripten_wasm_eh, None | Some(_)) => disallow(cfg, "-Z emscripten_wasm_eh"),
Please add a test for the cfg in https://github.com/rust-lang/rust/blob/f55a5d2e067629c7939a7d8373e19dc673552934/tests/ui/cfg/disallowed-cli-cfgs.rs

2025-01-03 11:59 UTC, Urgau commented on library/panic_unwind/src/lib.rs
> +#![cfg_attr(bootstrap, allow(unexpected_cfgs))]
```suggestion
```

2025-01-03 12:05 UTC, hoodmane commented on compiler/rustc_session/src/config/cfg.rs
> +    if sess.opts.unstable_opts.emscripten_wasm_eh {
Isn't this check redundant? The only way for `sess.opts.unstable_opts.emscripten_wasm_eh` to be set is if the user passed `-Z emscripten-wasm-eh` to the cli and the cli parser will error out if any `-Z` flags are passed and it's not a nightly build?

2025-01-03 12:16 UTC, Urgau commented on compiler/rustc_session/src/config/cfg.rs
> +    if sess.opts.unstable_opts.emscripten_wasm_eh {
Currently yes, but only because `-Zemscripten_wasm_eh` default to `false`, if it's default is changed in the future the cfg will be set in stable which is not what we want. Better be explicit than sorry.

2025-01-03 12:31 UTC, hoodmane commented on compiler/rustc_session/src/config/cfg.rs
> +    if sess.opts.unstable_opts.emscripten_wasm_eh {
Well if we did set `sess.opts.unstable_opts.emscripten_wasm_eh` to `true` but don't emit this `cfg` we'll get crashes in the backend when building the unwind libraries. I suppose that would remind us to come remove this condition?

2025-01-03 13:04 UTC, Urgau commented on compiler/rustc_session/src/config/cfg.rs
> +    if sess.opts.unstable_opts.emscripten_wasm_eh {
Well, that shouldn't happen, `panic_unwind` and `unwind` are nightly-only and this cfg is internal, it should therefore always at-least be gated under nightly.

2025-01-03 13:27 UTC, hoodmane commented on compiler/rustc_session/src/config/cfg.rs
> +    if sess.opts.unstable_opts.emscripten_wasm_eh {
Okay, I made this change.

2025-01-03 13:28 UTC, hoodmane commented on library/unwind/src/lib.rs
> +    all(target_family = "wasm", any(not(target_os = "emscripten"), emscripten_wasm_eh)),
I think I did the right stuff to add the feature, please let me know if anything is missing.

2025-01-03 13:39 UTC, hoodmane commented on library/panic_unwind/src/lib.rs
> +#![cfg_attr(not(bootstrap), feature(cfg_emscripten_wasm_eh))]
@Urgau How do I allow using this feature in the stage0 build? This `not(bootstrap)` makes the stage0 stdlib build work, but once this commit is merged the stage0 build will be broken.

2025-01-03 13:39 UTC, hoodmane commented
@rustbot label -S-waiting-on-author +S-waiting-on-review

2025-01-03 13:50 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12598438562/job/35113296612) [(plain)](https://github.com/rust-lang/rust/commit/610794e229f308116894c0eaacbffb8dbbf88067/checks/35113296612/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#21 exporting to docker image format
#21 sending tarball 26.2s done
#21 DONE 39.2s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
.......................................i................................................  1936/18209
........................................................................................  2024/18209
........i...............................................................................  2112/18209
............i..............
[ui] tests/ui/cfg/disallowed-cli-cfgs.rs#emscripten_wasm_eh_ ... F
........................................................................................  2288/18209
........................................................................................  2376/18209
........................................................................................  2464/18209
........................................................................................  2552/18209
---
.................................................................................

failures:

---- [ui] tests/ui/cfg/disallowed-cli-cfgs.rs#emscripten_wasm_eh_ stdout ----
Saved the actual stderr to "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/cfg/disallowed-cli-cfgs.emscripten_wasm_eh_/disallowed-cli-cfgs.emscripten_wasm_eh_.stderr"
normalized stderr:
error: unexpected `--cfg emscripten_wasm_eh` flag
   |
   = note: config `emscripten_wasm_eh` is only supposed to be controlled by `-Z emscripten_wasm_eh`
   = note: manually setting a built-in cfg can and does create incoherent behaviors
   = note: `#[deny(explicit_builtin_cfgs_in_flags)]` on by default
error: aborting due to 1 previous error





The actual stderr differed from the expected stderr.
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args cfg/disallowed-cli-cfgs.rs`

error in revision `emscripten_wasm_eh_`: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/cfg/disallowed-cli-cfgs.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--cfg" "emscripten_wasm_eh_" "--check-cfg" "cfg(test,FALSE,overflow_checks_,debug_assertions_,ub_checks_,sanitize_,sanitizer_cfi_generalize_pointers_,sanitizer_cfi_normalize_integers_,proc_macro_,panic_,target_feature_,unix_,windows_,target_abi_,target_arch_,target_endian_,target_env_,target_family_,target_os_,target_pointer_width_,target_vendor_,target_has_atomic_,target_has_atomic_equal_alignment_,target_has_atomic_load_store_,target_thread_local_,relocation_model_,fmt_debug_,emscripten_wasm_eh_)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/cfg/disallowed-cli-cfgs.emscripten_wasm_eh_" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--cfg" "emscripten_wasm_eh"
--- stderr -------------------------------
--- stderr -------------------------------
error: unexpected `--cfg emscripten_wasm_eh` flag
   |
   = note: config `emscripten_wasm_eh` is only supposed to be controlled by `-Z emscripten_wasm_eh`
   = note: manually setting a built-in cfg can and does create incoherent behaviors
   = note: `#[deny(explicit_builtin_cfgs_in_flags)]` on by default
error: aborting due to 1 previous error
------------------------------------------




failures:
    [ui] tests/ui/cfg/disallowed-cli-cfgs.rs#emscripten_wasm_eh_
test result: FAILED. 18026 passed; 1 failed; 182 ignored; 0 measured; 0 filtered out; finished in 178.20s

Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
Build completed unsuccessfully in 0:17:58
```

</details>

2025-01-03 14:02 UTC, Urgau commented on library/panic_unwind/src/lib.rs
> +#![cfg_attr(not(bootstrap), feature(cfg_emscripten_wasm_eh))]
You don't need to allow using the feature in `stage0` as `stage0` is the beta compiler and it doesn't know about the feature.

When `stage0` will be updated the `#[cfg_attr]` condition will be removed leaving only `#![feature(cfg_emscripten_wasm_eh)]`, which will be known at that point by `stage0`.

2025-01-03 14:09 UTC, hoodmane commented on library/panic_unwind/src/lib.rs
> +#![cfg_attr(not(bootstrap), feature(cfg_emscripten_wasm_eh))]
Thanks for the explanation.

2025-01-04 16:41 UTC, workingjubilee requested changes
can you squash the first four commits? 242188625fea90d39018f971fab8d11ccc613651 is the first one that actually builds.

2025-01-04 16:41 UTC, workingjubilee commented on tests/codegen/emscripten-catch-unwind-new-eh.rs
-> tests/codegen/emscripten/catch-unwind-wasm-eh.rs

2025-01-04 16:41 UTC, workingjubilee commented on tests/codegen/emscripten-catch-unwind.rs
-> tests/codegen/emscripten/catch-unwind-js-eh.rs

(the old EH is the JS-based EH, right?)

2025-01-06 09:31 UTC, hoodmane commented
Okay, I just squashed everything since there weren't really any commits that I feel are super worth preserving.
@rustbot label -S-waiting-on-author +S-waiting-on-review

2025-01-06 18:34 UTC, workingjubilee commented
also fine!

@bors r+ rollup

2025-01-07 07:20 UTC, merged

2025-01-08 23:09 UTC, hoodmane commented
There seems to be a problem that if you try to build a crate with `panic=abort` with this flag it says:
```
error: the crate `panic_abort` does not have the panic strategy `abort`
```

2025-01-08 23:11 UTC, hoodmane commented
I see emscripten mentioned in panic_abort so probably that's related.

2025-01-09 02:01 UTC, workingjubilee commented
huh, weird.

2025-01-13 16:39 UTC, hoodmane commented
Seems to be related to this issue:
https://github.com/rust-lang/wg-cargo-std-aware/issues/29