Add a Few Codegen Tests
rust-lang/rust pull request #132170
Opened 2024-10-26 04:11 UTC by veera-sivarajan

Closes #86109, #64219

Those issues somehow got fixed over time. 

So, this PR adds a couple of codegen tests to ensure we don't regress in the future.

2024-10-26 06:06 UTC, jieyouxu requested changes
The tests themselves look good, and the comments are good, but please also:

1. Give the tests meaningful names (not just issue-xxxxx). E.g. `fn-ptr-never-ret-ty-has-noreturn-attr.rs`.
2. Please move them into meaningful subdirectories instead of `issues/`.

Other than that, LGTM.

2024-10-26 06:06 UTC, jieyouxu commented on tests/codegen/issues/issue-86109.rs
> +//! ensuring there is no call (to panic) instruction.
Remark: that the division by zero was present in 1.69 but disappeared in 1.70.

2024-10-26 06:20 UTC, jieyouxu commented
@rustbot author

2024-10-26 16:55 UTC, veera-sivarajan commented
Thank you for the feedback.

I've renamed the tests and added the remark. But I cannot find a more appropriate directory for these tests than `codegen/issues`.

2024-10-26 17:02 UTC, jieyouxu commented
That's fine. I'll r+ after PR CI is green.

2024-10-27 01:03 UTC, workingjubilee commented
@bors r=jieyouxu

2024-10-27 04:57 UTC, workingjubilee commented
did not pass: https://github.com/rust-lang/rust/pull/132211#issuecomment-2439822384

@bors r-

2024-10-27 05:31 UTC, jieyouxu commented
Yeah, that matched on a `tail call` on aarc64 apple

2024-11-02 07:28 UTC, jieyouxu commented
Thanks!
@bors r+ rollup=iffy

2024-11-02 11:07 UTC, merged