Provide placeholder generics for traits in "no method found for type parameter" suggestions
rust-lang/rust pull request #132487
Opened 2024-11-02 03:34 UTC by dianne

In the diagnostics for the error ``no method named `method` found for type parameter `T` in the current scope [E0599]``, the compiler will suggest adding bounds on `T` for traits that define a method named `method`. However, these suggestions didn't include any generic arguments, so applying them would result in a `missing generics for trait` or `missing lifetime specifier` error. This PR adds placeholder arguments to the suggestion in such cases. Specifically, I tried to base the placeholders off of what's done in suggestions for when generics are missing or too few are provided:
- The placeholder for a lifetime parameter is `'_`.
- The placeholder for a type or const parameter without a default is the name of the parameter.
- Placeholders are not provided for parameters with defaults.

The applicability of the suggestion is downgraded to `Applicability::HasPlaceholders` if any placeholders are provided.

Fixes #132407

2024-11-02 06:05 UTC, fmease requested changes
Could you surround the placeholder arguments with `/*` and `*/` to highlight the fact that they are placeholders? E.g., `Trait2</* '_, A, B */>`. Otherwise users may take them literally and wonder whether the suggestion is wrong if it leads to more errors. It's not a hypothetical btw, people have reported such suggestions as bugs.

This would also be consistent with the diagnostic suggestion for E0220 (associated type not found). See https://github.com/rust-lang/rust/pull/126575/commits/02a2f0272736c65b51996b0c6e7cbd991ac21d5c were I impl'ed that.

2024-11-02 06:05 UTC, fmease commented on compiler/rustc_hir_typeck/src/method/suggest.rs
> +                                    use ty::GenericParamDefKind::{Const, Lifetime, Type};
You should be able to simplify this by using `identity_for_item` over `generics_of`. Compare:

https://github.com/rust-lang/rust/blob/ef972a346668ed4234d1a43ed4ad7ca4e9c58d51/compiler/rustc_hir_analysis/src/hir_ty_lowering/errors.rs#L253-L263

2024-11-02 06:11 UTC, fmease commented on compiler/rustc_hir_typeck/src/method/suggest.rs
> +                                    use ty::GenericParamDefKind::{Const, Lifetime, Type};
Ah, disregard, that wouldn't consider generic parameter defaults.

2024-11-02 06:36 UTC, dianne commented
The placeholders should now be surrounded by `/*` and `*/`. I'll open a PR to do that for E0107 too, if that's alright. That's what I was using as a reference, and it looks easy to fix.

2024-11-11 16:42 UTC, fmease approved these changes
Thanks! Sorry for the slight delay. I was just dumbfounded that we don't have an API for that already somewhere. I guess one could use `GenericArgs::identity_for_item` plus `Generics::own_args_no_defaults` but er, that would perform much worse in this case.

I have small stylistic suggestions but nothing major. Lastly, could you squash your commits into one?

2024-11-11 20:38 UTC, dianne commented
Done. Thanks!
@rustbot ready

2024-11-11 21:45 UTC, fmease commented
@bors r+ rollup (diagnostics)

2024-11-12 08:14 UTC, merged