Yeet the `effects` feature, move it onto `const_trait_impl`
rust-lang/rust pull request #132479
Opened 2024-11-01 23:16 UTC by compiler-errors

This PR merges the `effects` feature into the `const_trait_impl` feature. There's really no need to have two feature gates for one feature.

After this PR, if `const_trait_impl` **is** enabled:
* Users can use and define const traits
* `HostEffect` const conditions will be enforced on the HIR
* We re-check the predicates in MIR just to make sure that we don't "leak" anything during MIR lowering

And if `const_trait_impl` **is not** enabled:
* Users cannot use nor define const traits
* `HostEffect` const conditions are not enforced on the HIR
* We will raise a const validation error if we call a function that has any const conditions (i.e. const traits and functions with any `~const` in their where clasues)

This should be the last step for us to be able to enable const traits in the standard library. We still need to re-constify `Drop` and `Destruct` and stuff for const traits to be particularly *useful* for some cases, but this is a good step :D

r? fee1-dead
cc @rust-lang/project-const-traits

2024-11-01 23:16 UTC, compiler-errors commented
Lots of files changed, but most of it is just removing `feature(effects)` from the ui tests, and renaming `FIXME(effects)` to `FIXME(const_trait_impl)` ✨

2024-11-01 23:51 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/11637667663/job/32411244963) [(plain)](https://github.com/rust-lang/rust/commit/e86e5aa6e7c9d64ed7e860e80f22ee524d9d217a/checks/32411244963/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
------
 > importing cache manifest from ghcr.io/rust-lang/rust-ci-cache:c32c805632780b5c1de330e3f44561b336c2efe163bc0990acb392390157a8e1d9f855d75914a239aa40c49d77f4a837247d05d2f8d46f554b98e1f46712a3e3:
------
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
  Downloaded boml v0.3.1
   Compiling boml v0.3.1
   Compiling y v0.1.0 (/checkout/compiler/rustc_codegen_gcc/build_system)
    Finished `release` profile [optimized] target(s) in 3.93s
     Running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-codegen/x86_64-unknown-linux-gnu/release/y test --use-system-gcc --use-backend gcc --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc --release --mini-tests --std-tests`
Using system GCC
[BUILD] example
[AOT] mini_core_hello_world
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc/mini_core_hello_world
abc
---
---- [rustdoc] tests/rustdoc/const-effect-param.rs stdout ----

error: rustdoc failed!
status: exit status: 1
command: cd "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/const-effect-param" && env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/const-effect-param/auxiliary" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/const-effect-param" "--deny" "warnings" "/checkout/tests/rustdoc/const-effect-param.rs" "-A" "internal_features"
--- stderr -------------------------------
error[E0557]: feature has been removed
##[error] --> /checkout/tests/rustdoc/const-effect-param.rs:4:12
  |
---
---- [rustdoc] tests/rustdoc/const-fn-effects.rs stdout ----

error: rustdoc failed!
status: exit status: 1
command: cd "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/const-fn-effects" && env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/const-fn-effects/auxiliary" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/const-fn-effects" "--deny" "warnings" "/checkout/tests/rustdoc/const-fn-effects.rs" "-A" "internal_features"
--- stderr -------------------------------
error[E0557]: feature has been removed
##[error] --> /checkout/tests/rustdoc/const-fn-effects.rs:2:12
  |
---
---- [rustdoc] tests/rustdoc/inline_cross/const-effect-param.rs stdout ----

error: auxiliary build of "/checkout/tests/rustdoc/inline_cross/auxiliary/const-effect-param.rs" failed to compile: 
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/rustdoc/inline_cross/auxiliary/const-effect-param.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "-O" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/inline_cross/const-effect-param/auxiliary" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-Znext-solver" "--crate-type" "dylib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/inline_cross/const-effect-param/auxiliary"
--- stderr -------------------------------
error[E0557]: feature has been removed
##[error] --> /checkout/tests/rustdoc/inline_cross/auxiliary/const-effect-param.rs:2:12
  |
---
---- [rustdoc] tests/rustdoc/rfc-2632-const-trait-impl.rs stdout ----

error: rustdoc failed!
status: exit status: 1
command: cd "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/rfc-2632-const-trait-impl" && env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/rfc-2632-const-trait-impl/auxiliary" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/rfc-2632-const-trait-impl" "--deny" "warnings" "/checkout/tests/rustdoc/rfc-2632-const-trait-impl.rs" "-A" "internal_features"
--- stderr -------------------------------
error[E0557]: feature has been removed
##[error]  --> /checkout/tests/rustdoc/rfc-2632-const-trait-impl.rs:12:30
   |
```

</details>

2024-11-03 04:33 UTC, fee1-dead requested changes
r=me after nits and rebases that become necessary

2024-11-03 04:33 UTC, fee1-dead commented on tests/rustdoc/rfc-2632-const-trait-impl.rs
>  #![allow(incomplete_features)]
```suggestion
```

2024-11-03 04:33 UTC, fee1-dead commented on tests/ui/consts/auxiliary/closure-in-foreign-crate.rs
>  #![allow(incomplete_features)]
```suggestion
```

2024-11-03 04:33 UTC, fee1-dead commented on tests/ui/consts/const-try.rs
>  #![allow(incomplete_features)]
```suggestion
```

2024-11-03 04:33 UTC, fee1-dead commented on tests/ui/consts/const_cmp_type_id.rs
>  #![allow(incomplete_features)]
```suggestion
```

2024-11-03 04:33 UTC, fee1-dead commented on tests/ui/consts/rustc-impl-const-stability.rs
>  #![allow(incomplete_features)]
```suggestion
```

2024-11-03 04:33 UTC, fee1-dead commented on tests/ui/delegation/unsupported.rs
>  #![allow(incomplete_features)]
```suggestion
```

2024-11-03 04:33 UTC, fee1-dead commented on tests/ui/intrinsics/safe-intrinsic-mismatch.rs
>  #![allow(incomplete_features)]
```suggestion
```

2024-11-03 04:33 UTC, fee1-dead commented on tests/ui/traits/const-traits/call.rs
>  #![allow(incomplete_features)]
```suggestion
```

2024-11-03 04:33 UTC, fee1-dead commented on tests/ui/traits/const-traits/cross-crate.rs
>  #![allow(incomplete_features)]
```suggestion
```

2024-11-03 04:33 UTC, fee1-dead commented on tests/ui/traits/const-traits/do-not-const-check-override.rs
>  #![allow(incomplete_features)]
```suggestion
```

2024-11-03 04:33 UTC, fee1-dead commented on tests/ui/traits/const-traits/effects/const_closure-const_trait_impl-ice-113381.rs
>  #![allow(incomplete_features)]
```suggestion
```

2024-11-03 04:33 UTC, fee1-dead commented on tests/ui/traits/const-traits/ice-119717-constant-lifetime.rs
>  #![allow(incomplete_features)]
```suggestion
```

2024-11-03 04:33 UTC, fee1-dead commented on tests/ui/traits/const-traits/ice-126148-failed-to-normalize.rs
>  #![allow(incomplete_features)]
```suggestion
```

2024-11-03 19:34 UTC, compiler-errors commented
The `const_closure` and some other feature gates remain incomplete, so there are still a *few* effects tests that still need `allow(incomplete_features)`. I tried to remove the rest though.

@bors r=fee1-dead

2024-11-03 22:18 UTC, merged

2024-11-04 00:09 UTC, rust-timer commented
Finished benchmarking commit (b8c8287a229cd79604aa84c25e1235fc78cd5f2e): [comparison URL](https://perf.rust-lang.org/compare.html?start=e3a918ece026cec748fc64af5b4983095b46097e&end=b8c8287a229cd79604aa84c25e1235fc78cd5f2e&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=e3a918ece026cec748fc64af5b4983095b46097e&end=b8c8287a229cd79604aa84c25e1235fc78cd5f2e&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=e3a918ece026cec748fc64af5b4983095b46097e&end=b8c8287a229cd79604aa84c25e1235fc78cd5f2e&stat=max-rss)
<details>
<summary>Results (primary 1.8%, secondary 4.5%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.8% | [1.8%, 1.8%] | 1     |
| Regressions ❌ <br /> (secondary)  | 4.5% | [4.5%, 4.5%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 1.8% | [1.8%, 1.8%] | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=e3a918ece026cec748fc64af5b4983095b46097e&end=b8c8287a229cd79604aa84c25e1235fc78cd5f2e&stat=cycles:u)
<details>
<summary>Results (primary 3.7%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 3.7% | [3.7%, 3.7%] | 1     |
| Regressions ❌ <br /> (secondary)  | -    | -            | 0     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 3.7% | [3.7%, 3.7%] | 1     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=e3a918ece026cec748fc64af5b4983095b46097e&end=b8c8287a229cd79604aa84c25e1235fc78cd5f2e&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 780.261s -> 780.466s (0.03%)
**Artifact size**: 335.33 MiB -> 335.33 MiB (0.00%)

2024-11-04 07:01 UTC, RalfJung commented
> This should be the last step for us to be able to enable const traits in the standard library. 

Do we have checks ensuring that const trait fns cannot be called from stable const fns? I don't think so (just some leftovers in check.rs you said you were not happy with).

IMO that is a blocker for enabling the feature in the standard library.

2024-11-04 12:47 UTC, RalfJung commented on compiler/rustc_const_eval/src/check_consts/check.rs
> +                    if tcx.features().const_trait_impl() && trait_is_const {
The `effects` feature name still appears a few lines down in this file

https://github.com/rust-lang/rust/blob/6b96103bf3b0746e443f9bb86b532be2c536113a/compiler/rustc_const_eval/src/check_consts/check.rs#L680-L684

2024-11-04 12:53 UTC, RalfJung commented
> Do we have checks ensuring that const trait fns cannot be called from stable const fns? I don't think so (just some leftovers in check.rs you said you were not happy with, and I don't know if we can trust them).

So specifically, I am concerned about this line

https://github.com/rust-lang/rust/blob/6b96103bf3b0746e443f9bb86b532be2c536113a/compiler/rustc_const_eval/src/check_consts/check.rs#L662

This does not take into account whether the current function must be recursively const-stable.

So I think what the logic here should do is more like
```rust
if let Some(trait_did) = tcx.trait_of_item(callee) {
  if !trait_is_const {
    // Trigger `ops::FnCallNonConst`.
    // ...
    return;
  }

  // Ensure we have `const_trait_impl` and are allowed to use it in this function.
  self.check_op(ops::ConstTraitCall);

  // We don't know which function is being called here, so we can't run the checks below.
  // FIXME: apply more fine-grained per-trait const stability checks
  // (see https://github.com/rust-lang/project-const-traits/issues/5).
  return;
}
```

Also it seems a bit odd that `const_trait_impl` guards *calling* const trait functions. Maybe `const_trait` would make more sense as the name for this feature?

2024-11-15 10:01 UTC, fee1-dead commented
> Do we have checks ensuring that const trait fns cannot be called from stable const fns? I don't think so (just some leftovers in check.rs you said you were not happy with, and I don't know if we can trust them).

noting here for completeness, that was done in #132823.