Add illumos target documentation
rust-lang/rust pull request #132477
Opened 2024-11-01 20:47 UTC by Noratrieb

Fixes https://github.com/rust-lang/rust/pull/130132#issuecomment-2339055221

@jclulow @pfmooney I'm adding you as requested.

The page is very barebones (as I do not know illumos well) and could use some improvements (for example in the "Cross-compilation toolchains and C code" section).
Feel free to suggest improvements (or rewrite it from scratch) if you find something.

2024-11-01 20:50 UTC, workingjubilee commented on src/doc/rustc/src/platform-support/illumos.md
> +Rust ships pre-compiled artifacts for the `x86_64-unknown-netbsd` target.
```suggestion
Rust ships pre-compiled artifacts for the `x86_64-unknown-illumos` target.
```

2024-11-01 20:57 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/11636128422/job/32406919510) [(plain)](https://github.com/rust-lang/rust/commit/29b8439cc633bf7d393d38835b69c35cb546376b/checks/32406919510/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#13 2.945 Building wheels for collected packages: reuse
#13 2.946   Building wheel for reuse (pyproject.toml): started
#13 3.194   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 3.195   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132720 sha256=026f3bb0f1aa8090b861fd0a0939cb1a782396d84c8aab7875096557d637a0f6
#13 3.196   Stored in directory: /tmp/pip-ephem-wheel-cache-l1tnw_dy/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#13 3.199 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#13 3.610 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#13 3.610 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 4.174 Collecting virtualenv
#13 4.174 Collecting virtualenv
#13 4.225   Downloading virtualenv-20.27.1-py3-none-any.whl (3.1 MB)
#13 4.358      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 23.9 MB/s eta 0:00:00
#13 4.404 Collecting distlib<1,>=0.3.7
#13 4.412   Downloading distlib-0.3.9-py2.py3-none-any.whl (468 kB)
#13 4.426      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 40.6 MB/s eta 0:00:00
#13 4.463 Collecting platformdirs<5,>=3.9.1
#13 4.474   Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
#13 4.514 Collecting filelock<4,>=3.12.2
#13 4.525   Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
#13 4.608 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 4.789 Successfully installed distlib-0.3.9 filelock-3.16.1 platformdirs-4.3.6 virtualenv-20.27.1
#13 DONE 4.9s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      178112 kB
DirectMap2M:     8210432 kB
DirectMap1G:    10485760 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.04s
##[endgroup]
WARNING: `rust.download-rustc` is enabled. The `rust.channel` option will be overridden by the CI rustc's channel.
downloading https://static.rust-lang.org/dist/2024-10-16/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz
---
fmt check
fmt: checked 5645 files
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/src/doc/rustc/src/platform-support/illumos.md:6: trailing whitespace
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (24.3.1)
All checks passed!
checking C++ file formatting
some tidy checks failed
some tidy checks failed
Command has failed. Rerun with -v to see more details.
  local time: Fri Nov  1 20:57:04 UTC 2024
  network time: Fri, 01 Nov 2024 20:57:04 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-11-01 21:02 UTC, jclulow requested changes
Thanks for getting this started, with my apologies for not having had a chance to do it myself!

2024-11-01 21:02 UTC, jclulow commented on src/doc/rustc/src/platform-support/illumos.md
> +The target supports C code.
```suggestion
The target supports C code.

The illumos project makes available [prebuilt sysroot artefacts](https://github.com/illumos/sysroot) which can be used for cross compilation.  The official Rust binaries are cross-compiled using these artefacts.
```

2024-12-29 17:25 UTC, Noratrieb commented
That took a while, I sort of forgot about this PR, but I finally addressed your feedback and it should be good to go now!

2024-12-29 21:39 UTC, jclulow commented
Thanks!

2024-12-29 21:39 UTC, jclulow approved these changes

2024-12-30 01:59 UTC, workingjubilee commented
Cool!

@bors r+ rollup

2024-12-30 02:00 UTC, tgross35 commented
Doesn't this need SUMMARY.md updated and links added?

2024-12-30 02:09 UTC, workingjubilee commented
I guess so!

@bors r-

2024-12-30 11:14 UTC, Noratrieb commented
💀

2024-12-30 15:26 UTC, Noratrieb commented
OK, fixed it and verified that it works locally.
@bors r=workingjubilee

2024-12-30 23:45 UTC, merged