Convert disallowed macros to an early pass lint
rust-lang/rust pull request #132645
Opened 2024-11-05 16:03 UTC by jdonszelmann

r? @xFrednet 

I forgot one yesterday, but this one also needs to be early pass. I use AttrStorage in a similar way as FormatArgs does. It's not actually very wasteful, there aren't *that* many attributes, and every attribute used to store its own span, which outside clippy will soon not be necessary anymore.

There's one more that needs refactoring, which @GuillaumeGomez is doing

2024-11-05 16:08 UTC, GuillaumeGomez commented on src/tools/clippy/clippy_lints/src/disallowed_macros.rs
> +
nit :)

2024-11-05 16:08 UTC, GuillaumeGomez commented on src/tools/clippy/clippy_lints/src/disallowed_macros.rs
> +
Extra line here too.

2024-11-05 16:09 UTC, GuillaumeGomez commented
I think `fmt` check will be unhappy but otherwise code looks good to me. Thanks!

2024-11-05 16:11 UTC, jdonszelmann commented
actually I don't think so, I ran tidy on it haha

2024-11-05 16:14 UTC, jdonszelmann commented
![image](https://github.com/user-attachments/assets/d33326c3-a41e-434c-bf01-284bf5c91053)
yup, but I'll force push over it fixing your comments

2024-11-05 16:31 UTC, flip1995 requested changes
This only modifies Clippy. Please open this PR towards the Clippy repo.

To do this easily you can do

```
git diff HEAD~1 --patch -- src/tools/clippy | sed "s|src/tools/clippy/||" > clippy.patch
```

and then in the Clippy repo clone 

```
git apply /path/to/clippy.patch
```

2024-11-05 16:33 UTC, GuillaumeGomez commented
Oh good catch. Didn't even notice it was the wrong repository...

2024-11-05 16:38 UTC, flip1995 commented
Also the other PR should have been done to the Clippy repo.

To give an explanation for that policy: The Clippy repo runs more tests on Clippy than in the Rust repo. It also uses slightly different formatting rules. Those need to be fixed during syncing the Clippy and the Rust repo. The more changes were done between syncs to Clippy in the Rust repo, the more conflicts there are and the longer the sync takes.

The most important check that is done in Clippy for changes like this: Clippy does a mini-crater run on every PR to see the effect of changes. I have the feeling that a change like this (or rather the ones in the previous PR) can have unexpected effects. Those we (meaning I) would need to catch during the next sync.

2024-11-05 18:19 UTC, jdonszelmann commented
Oh alright, that makes sense. I'll refile it.

2024-11-05 19:46 UTC, jdonszelmann commented
closed in favor of https://github.com/rust-lang/rust-clippy/pull/13657

2024-11-05 19:47 UTC, closed without merging

2024-11-06 11:01 UTC, flip1995 commented
Thank you. I will do the sync tomorrow, as it is already delayed by 1 week because of other changes that blocked it, that needed to be fixed.

So you only have to wait until tomorrow evening :)