Provide more context on `Fn` closure modifying binding
rust-lang/rust pull request #133149
Opened 2024-11-17 23:35 UTC by estebank

When modifying a binding from inside of an `Fn` closure, point at the binding definition and suggest using an `std::sync` type that would allow the code to compile.

```
error[E0594]: cannot assign to `counter`, as it is a captured variable in a `Fn` closure
 --> f703.rs:6:9
  |
4 |     let mut counter = 0;
  |         ----------- `counter` declared here, outside the closure
5 |     let x: Box<dyn Fn()> = Box::new(|| {
  |                                     -- in this closure
6 |         counter += 1;
  |         ^^^^^^^^^^^^ cannot assign
  |
  = help: consider using `std::sync::atomic::AtomicI32` instead, which allows for multiple threads to access and modify the value
```

This provides more context on where the binding being modified was declared, and more importantly, guides newcomers towards `std::sync` when encountering cases like these.

When the requirement comes from an argument of a local function, we already tell the user that they might want to change from `Fn` to `FnMut`:

```
error[E0594]: cannot assign to `x`, as it is a captured variable in a `Fn` closure
  --> $DIR/borrow-immutable-upvar-mutation.rs:21:27
   |
LL | fn to_fn<A: std::marker::Tuple, F: Fn<A>>(f: F) -> F {
   |                                              - change this to accept `FnMut` instead of `Fn`
...
LL |         let mut x = 0;
   |             ----- `x` declared here, outside the closure
LL |         let _f = to_fn(|| x = 42);
   |                  ----- -- ^^^^^^ cannot assign
   |                  |     |
   |                  |     in this closure
   |                  expects `Fn` instead of `FnMut`
   |
   = help: consider using `std::sync::atomic::AtomicI32` instead, which allows for multiple threads to access and modify the value
```

We might want to avoid the `help` in this case.

_Inspired by a [part of Niko's keynote at RustNation UK 2024](https://youtu.be/04gTQmLETFI?si=dgJL2OJRtuShkxdD&t=600)._

2024-11-18 16:05 UTC, compiler-errors requested changes
I'm somewhat worried that this will lead to users trying to mutate state through APIs that are designed to be immutable. Taking an `impl Fn()` can have a lot of different intentions from an API designer perspective, and there's not much context we can glean by simply just seeing a mutate-within-`Fn` error in borrowck. Mentioning threading and atomics unprompted seems a bit strange, even though it could fix some people's errors, and even if it does, it's possibly not the right solution compared to using a different API or approaching a problem differently.

I'd prefer if this help message were elaborated to mention that the function expects a `Fn` and to tell the user pay attention to *why* this is the case, and then advising the user that if mutation is *intended* then it can be done concurrently through an atomic since it does not require exclusive access.

I fear that if we provide just the information in this help message, we're at risk of misleading users further by turning *borrowck* errors into logical or design errors that they cannot so easily debug or catch.

2024-11-18 18:48 UTC, estebank commented
@compiler-errors what do you think if instead of specifying the type they can use we instead linked at [the book section on shared state](https://doc.rust-lang.org/stable/book/ch16-03-shared-state.html)? I did not make it a structured suggestion to introduce a bit of friction to people blindly following this, but your point stands.

2025-06-16 14:11 UTC, Dylan-DPC commented
@compiler-errors this is stalled on a question the author has asked.

2025-08-11 00:03 UTC, estebank commented
Removed the `help` mentioning atomics, lets at least point at the binding that was closed over.

2025-08-11 00:19 UTC, compiler-errors commented
r? compiler

2025-08-21 14:33 UTC, wesleywiser commented
r? wesleywiser

2025-10-23 16:04 UTC, wesleywiser approved these changes
r=me after squash unless you really want to keep the commit history around for some reason 🙂 

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/133149/46c219bd24862c0a87f0299570bb37f2d5ecf6ce..f7ddba088fa3d360130ced2d25f30eea2b2411b9)*

2025-11-03 22:07 UTC, estebank commented
@bors r=wesleywiser

2025-11-04 02:22 UTC, Zalathar commented
Yielding to enclosing rollup.

@bors retry

2025-11-04 02:45 UTC, Zalathar commented
Yielding to enclosing rollup (again).

@bors retry

2025-11-04 06:37 UTC, merged