Reword resolve errors caused by likely missing crate in dep tree
rust-lang/rust pull request #133154
Opened 2024-11-18 04:27 UTC by estebank

Reword label and add `help`:

```
error[E0432]: unresolved import `some_novel_crate`
 --> f704.rs:1:5
  |
1 | use some_novel_crate::Type;
  |     ^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `some_novel_crate`
  |
  = help: if you wanted to use a crate named `some_novel_crate`, use `cargo add some_novel_crate` to add it to your `Cargo.toml`
```

Fix #133137.

2024-11-18 04:49 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/11885785343/job/33115995716) [(plain)](https://github.com/rust-lang/rust/commit/3aefa86a86adb4aaff1866d3ac422a036ed8cd74/checks/33115995716/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 exporting to docker image format
#16 sending tarball 27.8s done
#16 DONE 33.8s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
failures:

---- [ui] tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs stdout ----

error: /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:58: unexpected error: '58:8: 58:9: failed to resolve: you might be missing crate `core` [E0433]'

error: /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:802: unexpected error: '802:23: 802:26: failed to resolve: you might be missing crate `core` [E0433]'

error: /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:811: unexpected error: '811:25: 811:26: failed to resolve: you might be missing crate `core` [E0433]'
error: /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:58: expected error not found: failed to resolve: use of unresolved module or unlinked crate `core`

error: /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:802: expected error not found: failed to resolve: use of unresolved module or unlinked crate `core`


error: /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:811: expected error not found: failed to resolve: use of unresolved module or unlinked crate `core`

error: 3 unexpected errors found, 3 expected errors not found
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/session-diagnostic/diagnostic-derive" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers"
--- unexpected errors (from JSON output) ---
--- unexpected errors (from JSON output) ---
ERROR     line  58: 58:8: 58:9: failed to resolve: you might be missing crate `core` [E0433]
ERROR     line 802: 802:23: 802:26: failed to resolve: you might be missing crate `core` [E0433]
ERROR     line 811: 811:25: 811:26: failed to resolve: you might be missing crate `core` [E0433]
--- not found errors (from test file) ---
ERROR     line  58: failed to resolve: use of unresolved module or unlinked crate `core`
ERROR     line 802: failed to resolve: use of unresolved module or unlinked crate `core`
ERROR     line 811: failed to resolve: use of unresolved module or unlinked crate `core`
---
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- [ui] tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs stdout ----

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:96: unexpected error: '96:9: 96:14: failed to resolve: you might be missing crate `core` [E0433]'

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:96: unexpected note: 'you might be missing crate `core`'

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:312: unexpected error: '312:1: 312:6: failed to resolve: you might be missing crate `core` [E0433]'

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:312: unexpected note: 'you might be missing crate `core`'

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:582: unexpected error: '582:27: 582:28: failed to resolve: you might be missing crate `core` [E0433]'

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:582: unexpected note: 'you might be missing crate `core`'

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:675: unexpected error: '675:28: 675:33: failed to resolve: you might be missing crate `core` [E0433]'

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:675: unexpected note: 'you might be missing crate `core`'

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:686: unexpected error: '686:28: 686:33: failed to resolve: you might be missing crate `core` [E0433]'

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:686: unexpected note: 'you might be missing crate `core`'

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:697: unexpected error: '697:28: 697:29: failed to resolve: you might be missing crate `core` [E0433]'

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:697: unexpected note: 'you might be missing crate `core`'

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:720: unexpected error: '720:30: 720:31: failed to resolve: you might be missing crate `core` [E0433]'

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:720: unexpected note: 'you might be missing crate `core`'

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:812: unexpected error: '812:48: 812:49: failed to resolve: you might be missing crate `core` [E0433]'

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:812: unexpected note: 'you might be missing crate `core`'
error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:96: expected error not found: failed to resolve: use of unresolved module or unlinked crate `core`

error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:96: expected note not found: use of unresolved module or unlinked crate `core`

---
error: /checkout/tests/ui-fulldeps/session-diagnostic/subdiagnostic-derive.rs:812: expected note not found: use of unresolved module or unlinked crate `core`

error: 16 unexpected errors found, [...]

2024-11-18 04:50 UTC, fmease requested changes
Please only suggest Cargo-specific stuff if `rustc_session::utils::was_invoked_from_cargo()`

2024-11-18 12:19 UTC, jieyouxu commented
> Please only suggest Cargo-specific stuff if `rustc_session::utils::was_invoked_from_cargo()`

Apparently that detection uses `CARGO_CRATE_NAME` and tests have been using

```rs
//@ revisions: only-rustc cargo-invoked
//@[only-rustc] unset-rustc-env:CARGO_CRATE_NAME
//@[cargo-invoked] rustc-env:CARGO_CRATE_NAME=foo
```

which is... *clever*, almost too clever.

2024-12-20 19:00 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12436854149/job/34725538734) [(plain)](https://github.com/rust-lang/rust/commit/6ad26a1072ad794ec95eb4400588ebc7395732a3/checks/34725538734/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#13 3.000 Building wheels for collected packages: reuse
#13 3.001   Building wheel for reuse (pyproject.toml): started
#13 3.252   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 3.252   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132720 sha256=026f3bb0f1aa8090b861fd0a0939cb1a782396d84c8aab7875096557d637a0f6
#13 3.253   Stored in directory: /tmp/pip-ephem-wheel-cache-fwhbf90n/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#13 3.255 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#13 3.661 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#13 3.662 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 4.202 Collecting virtualenv
#13 4.202 Collecting virtualenv
#13 4.330   Downloading virtualenv-20.28.0-py3-none-any.whl (4.3 MB)
#13 4.562      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 18.9 MB/s eta 0:00:00
#13 4.603 Collecting distlib<1,>=0.3.7
#13 4.638   Downloading distlib-0.3.9-py2.py3-none-any.whl (468 kB)
#13 4.646      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 79.0 MB/s eta 0:00:00
#13 4.679 Collecting platformdirs<5,>=3.9.1
#13 4.713   Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
#13 4.749 Collecting filelock<4,>=3.12.2
#13 4.783   Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
#13 4.866 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 5.052 Successfully installed distlib-0.3.9 filelock-3.16.1 platformdirs-4.3.6 virtualenv-20.28.0
#13 DONE 5.2s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      139200 kB
DirectMap2M:     7200768 kB
DirectMap1G:    11534336 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.04s
##[endgroup]
WARN: currently no CI rustc builds have rustc debug assertions enabled. Please either set `rust.debug-assertions` to `false` if you want to use download CI rustc or set `rust.download-rustc` to `false`.
downloading https://static.rust-lang.org/dist/2024-11-27/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz
---
fmt check
fmt: checked 5736 files
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:59: trailing whitespace
##[error]tidy error: /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:804: trailing whitespace
##[error]tidy error: /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:812: trailing whitespace
##[error]tidy error: /checkout/tests/ui/typeck/path-to-method-sugg-unresolved-expr.rs:8: line longer than 100 chars
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (24.3.1)
All checks passed!
checking C++ file formatting
some tidy checks failed
some tidy checks failed
Command has failed. Rerun with -v to see more details.
  local time: Fri Dec 20 19:00:32 UTC 2024
  network time: Fri, 20 Dec 2024 19:00:32 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-12-21 01:39 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12440956259/job/34737190984) [(plain)](https://github.com/rust-lang/rust/commit/54856b5420ba683c6b8a58ff0e0253413de142d5/checks/34737190984/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#13 3.212 Building wheels for collected packages: reuse
#13 3.213   Building wheel for reuse (pyproject.toml): started
#13 3.459   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 3.460   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132720 sha256=026f3bb0f1aa8090b861fd0a0939cb1a782396d84c8aab7875096557d637a0f6
#13 3.460   Stored in directory: /tmp/pip-ephem-wheel-cache-tdzj7wlm/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#13 3.463 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#13 3.868 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#13 3.868 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 4.398 Collecting virtualenv
#13 4.398 Collecting virtualenv
#13 4.436   Downloading virtualenv-20.28.0-py3-none-any.whl (4.3 MB)
#13 4.519      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 52.7 MB/s eta 0:00:00
#13 4.577 Collecting filelock<4,>=3.12.2
#13 4.581   Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
#13 4.615 Collecting platformdirs<5,>=3.9.1
#13 4.618   Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
#13 4.636 Collecting distlib<1,>=0.3.7
#13 4.648      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 83.8 MB/s eta 0:00:00
#13 4.648      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 83.8 MB/s eta 0:00:00
#13 4.729 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 4.909 Successfully installed distlib-0.3.9 filelock-3.16.1 platformdirs-4.3.6 virtualenv-20.28.0
#13 DONE 5.0s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      120768 kB
DirectMap2M:     6170624 kB
DirectMap1G:    12582912 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.04s
##[endgroup]
WARN: currently no CI rustc builds have rustc debug assertions enabled. Please either set `rust.debug-assertions` to `false` if you want to use download CI rustc or set `rust.download-rustc` to `false`.
downloading https://static.rust-lang.org/dist/2024-11-27/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz
---
fmt check
fmt: checked 5736 files
tidy check
tidy: Skipping binary file check, read-only filesystem
##[error]tidy error: /checkout/tests/ui/typeck/path-to-method-sugg-unresolved-expr.rs:8: line longer than 100 chars
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (24.3.1)
All checks passed!
checking C++ file formatting
some tidy checks failed
some tidy checks failed
Command has failed. Rerun with -v to see more details.
  local time: Sat Dec 21 01:39:29 UTC 2024
  network time: Sat, 21 Dec 2024 01:39:29 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-12-21 03:48 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12441732298/job/34739024910) [(plain)](https://github.com/rust-lang/rust/commit/6a27b7f8e6baad31d22722587c4fd43979ebef4c/checks/34739024910/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
tests/fail/function_calls/exported_symbol_bad_unwind2.rs (revision `definition`) ... ok
tests/fail/function_calls/exported_symbol_bad_unwind2.rs (revision `both`) ... ok

FAILED TEST: tests/fail/rustc-error2.rs
command: MIRI_ENV_VAR_TEST="0" MIRI_TEMP="/tmp/miri-uitest-PijlMU" RUST_BACKTRACE="1" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/miri" "--error-format=json" "--sysroot=/checkout/obj/build/x86_64-unknown-linux-gnu/miri-sysroot" "-Dwarnings" "-Dunused" "-Ainternal_features" "-Zui-testing" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/miri_ui/tests/fail" "tests/fail/rustc-error2.rs" "--edition" "2021"
error: actual output differed from expected
Execute `./miri test --bless` to update `tests/fail/rustc-error2.stderr` to the actual output
--- tests/fail/rustc-error2.stderr
+++ <stderr output>
+++ <stderr output>
-error[E0433]: failed to resolve: use of undeclared crate or module `assert_mem_uninitialized_valid`
+error[E0433]: failed to resolve: use of unresolved module or unlinked crate `assert_mem_uninitialized_valid`
   --> tests/fail/rustc-error2.rs:LL:CC
    |
 LL |     fn deref(&self) -> &assert_mem_uninitialized_valid::Target {
-   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `assert_mem_uninitialized_valid`
+   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of unresolved module or unlinked crate `assert_mem_uninitialized_valid`
 error: aborting due to 1 previous error
 
 For more information about this error, try `rustc --explain E0433`.

---

error: there were 1 unmatched diagnostics
##[error] --> tests/fail/rustc-error2.rs:6:25
  |
6 |     fn deref(&self) -> &assert_mem_uninitialized_valid::Target {
  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error[E0433]: failed to resolve: use of unresolved module or unlinked crate `assert_mem_uninitialized_valid`

FAILURES:
    tests/fail/rustc-error2.rs

---

Location:
   /cargo/registry/src/index.crates.io-6f17d22bba15001f/ui_test-0.26.5/src/lib.rs:357

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
error: test failed, to rerun pass `--test ui`
Caused by:
  process didn't exit successfully: `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/ui-ce59f49d38f29107 --quiet` (exit status: 1)
  process didn't exit successfully: `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/ui-ce59f49d38f29107 --quiet` (exit status: 1)
Command has failed. Rerun with -v to see more details.
  local time: Sat Dec 21 03:48:24 UTC 2024
  network time: Sat, 21 Dec 2024 03:48:24 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2025-01-21 02:59 UTC, wesleywiser approved these changes
lgtm although you may want to clean up the commit history a bit

r=me when you've rebased

2025-01-22 00:50 UTC, estebank commented
@bors r=wesleywiser

2025-01-22 19:35 UTC, matthiaskrgr commented
@bors r- 
https://github.com/rust-lang/rust/pull/135891#issuecomment-2608097837

2025-01-22 20:27 UTC, estebank commented
@bors r=wesleywiser

2025-01-22 22:54 UTC, matthiaskrgr commented
compiler/rustc_error_codes/src/error_codes/E0433.md:22:// error: failed to resolve: use of undeclared crate or module `ferris_wheel`

should this be updated as well?

2025-01-24 01:20 UTC, estebank commented
These rewording PRs are always a pain :-/

2025-01-24 16:50 UTC, estebank commented
@bors r=wesleywiser

2025-01-25 14:21 UTC, merged

2025-01-25 16:41 UTC, rust-timer commented
Finished benchmarking commit (203e6c127c50c499be53731a39fe36d24f544502): [comparison URL](https://perf.rust-lang.org/compare.html?start=f94018810c6c0f59df013c9c418e994b94cf1805&end=203e6c127c50c499be53731a39fe36d24f544502&stat=instructions:u).

### Overall result: ❌✅ regressions and improvements - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=f94018810c6c0f59df013c9c418e994b94cf1805&end=203e6c127c50c499be53731a39fe36d24f544502&stat=instructions:u)
This is the most reliable metric that we have; it was used to determine the overall result at the top of this comment. However, even this metric can sometimes exhibit noise.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | 0.2%  | [0.2%, 0.2%]   | 2     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -0.2% | [-0.2%, -0.2%] | 1     |
| All ❌✅ (primary)                 | -     | -              | 0     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=f94018810c6c0f59df013c9c418e994b94cf1805&end=203e6c127c50c499be53731a39fe36d24f544502&stat=max-rss)
<details>
<summary>Results (primary 2.9%, secondary -0.5%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 2.9%  | [2.9%, 2.9%]   | 1     |
| Regressions ❌ <br /> (secondary)  | 2.3%  | [2.3%, 2.3%]   | 1     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -3.4% | [-3.4%, -3.4%] | 1     |
| All ❌✅ (primary)                 | 2.9%  | [2.9%, 2.9%]   | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=f94018810c6c0f59df013c9c418e994b94cf1805&end=203e6c127c50c499be53731a39fe36d24f544502&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=f94018810c6c0f59df013c9c418e994b94cf1805&end=203e6c127c50c499be53731a39fe36d24f544502&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 771.063s -> 770.579s (-0.06%)
**Artifact size**: 325.77 MiB -> 325.79 MiB (0.00%)