`suggest_borrow_generic_arg`: erase region variables from `moved_arg_ty` sooner
rust-lang/rust pull request #133130
Opened 2024-11-17 08:52 UTC by dianne

`suggest_borrow_generic_arg` would ICE if its `moved_arg_ty` argument contained any instances of `ReVar(_)`. This erases them preemptively to keep `EarlyBinder::instantiate` from panicking.

There shouldn't be any change in behavior other than fixing the ICE. For simplicity, the suggestion doesn't take regions into account when determining if it should fire, so it'd be erased or ignored anyway.

Fixes #133118

2024-11-17 20:37 UTC, compiler-errors reviewed
I'm not certain that this is the right fix. If we're instantiating/substituting the wrong set of region variables into a type, then this is bound to happen with a generic type or const as well, right? Those cannot be erased.

I'd at least like to see an explanation for why this issue was happening before this fix; this feels like it's just masking the underlying issue which is that this code is handling generics kinda strangely in general.

2024-11-17 20:47 UTC, compiler-errors requested changes
The real bug is that in `clause_for_ref`, you're substituting it once with the self type (`ref_ty`), then you're substituting it again in the call to `predicate_must_hold_modulo_regions`.

I don't think this really makes sense -- substituting it once should be sufficient, since you've already set up the generic args to have the right self type (`new_args`).

2024-11-17 20:47 UTC, compiler-errors commented
I hope that's enough info to guide you towards the right solution -- @rustbot author

2024-11-18 02:26 UTC, compiler-errors commented
This approach looks correct. Please update the description and title, then I can approve

2024-11-18 02:32 UTC, dianne commented
Done. Thank you! That helped. I think it reads much nicer now too.
@rustbot ready

2024-11-18 02:47 UTC, compiler-errors commented
@bors r+ rollup

2024-11-18 07:23 UTC, merged