[AIX] Add option -X32_64 to the "strip" command
rust-lang/rust pull request #133217
Opened 2024-11-19 19:51 UTC by xingxue-ibm

The AIX `strip` utility requires option `-X` to specify the object mode. This patch adds the `-X32_64` option to the `strip` command so that it can handle both 32-bit and 64-bit objects. The parameter `option` of function `strip_symbols_with_external_utility`, previously a single string, has been changed to `options`, a vector of strings, to accommodate multiple `strip` options.

2024-11-19 20:03 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/11920653831/job/33223085383) [(plain)](https://github.com/rust-lang/rust/commit/d98b13910d981c7fcff6263eca9fc59f121a53c8/checks/33223085383/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#13 2.880 Building wheels for collected packages: reuse
#13 2.881   Building wheel for reuse (pyproject.toml): started
#13 3.138   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 3.139   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132720 sha256=026f3bb0f1aa8090b861fd0a0939cb1a782396d84c8aab7875096557d637a0f6
#13 3.139   Stored in directory: /tmp/pip-ephem-wheel-cache-5rur4sy8/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#13 3.142 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#13 3.567 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#13 3.567 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 4.124 Collecting virtualenv
#13 4.124 Collecting virtualenv
#13 4.163   Downloading virtualenv-20.27.1-py3-none-any.whl (3.1 MB)
#13 4.226      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 51.6 MB/s eta 0:00:00
#13 4.267 Collecting distlib<1,>=0.3.7
#13 4.270   Downloading distlib-0.3.9-py2.py3-none-any.whl (468 kB)
#13 4.279      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 73.5 MB/s eta 0:00:00
#13 4.314 Collecting platformdirs<5,>=3.9.1
#13 4.326   Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
#13 4.436 Collecting filelock<4,>=3.12.2
#13 4.441   Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
#13 4.527 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 4.711 Successfully installed distlib-0.3.9 filelock-3.16.1 platformdirs-4.3.6 virtualenv-20.27.1
#13 DONE 4.8s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      317376 kB
DirectMap2M:     8071168 kB
DirectMap1G:    10485760 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.04s
##[endgroup]
downloading https://static.rust-lang.org/dist/2024-10-16/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/2024-10-16/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt
---
   Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
    Finished `release` profile [optimized] target(s) in 32.30s
##[endgroup]
fmt check
Diff in /checkout/compiler/rustc_codegen_ssa/src/back/link.rs:1108:
         match (strip, crate_type) {
             (Strip::Debuginfo, _) => {
                 let strip_options = vec!["-S".to_string()];
-                strip_symbols_with_external_utility(sess, stripcmd, out_filename, Some(&strip_options))
+                    sess,
+                    stripcmd,
+                    out_filename,
+                    Some(&strip_options),
+                    Some(&strip_options),
+                )
             }
             // Per the manpage, `-x` is the maximum safe strip level for dynamic libraries. (#93988)
             (Strip::Symbols, CrateType::Dylib | CrateType::Cdylib | CrateType::ProcMacro) => {
Diff in /checkout/compiler/rustc_codegen_ssa/src/back/link.rs:1115:
                 let strip_options = vec!["-x".to_string()];
-                strip_symbols_with_external_utility(sess, stripcmd, out_filename, Some(&strip_options))
+                    sess,
+                    stripcmd,
+                    out_filename,
+                    Some(&strip_options),
+                    Some(&strip_options),
+                )
             }
             (Strip::Symbols, _) => {
                 strip_symbols_with_external_utility(sess, stripcmd, out_filename, None)
Diff in /checkout/compiler/rustc_codegen_ssa/src/back/link.rs:1134:
             // Always preserve the symbol table (-x).
             Strip::Debuginfo => {
                 let strip_options = vec!["-x".to_string()];
-                strip_symbols_with_external_utility(sess, stripcmd, out_filename, Some(&strip_options))
+                    sess,
+                    stripcmd,
+                    out_filename,
+                    Some(&strip_options),
+                    Some(&strip_options),
+                )
             }
             // Strip::Symbols is handled via the --strip-all linker option.
             Strip::Symbols => {}
Diff in /checkout/compiler/rustc_codegen_ssa/src/back/link.rs:1153:
             Strip::Debuginfo => {
                 // FIXME: AIX's strip utility only offers option to strip line number information.
                 strip_options.push("-l".to_string());
-                strip_symbols_with_external_utility(sess, stripcmd, out_filename, Some(&strip_options))
+                    sess,
+                    stripcmd,
+                    out_filename,
+                    Some(&strip_options),
+                    Some(&strip_options),
+                )
             }
             Strip::Symbols => {
                 // Must be noted this option might remove symbol __aix_rust_metadata and thus removes .info section which contains metadata.
Diff in /checkout/compiler/rustc_codegen_ssa/src/back/link.rs:1160:
                 strip_options.push("-r".to_string());
-                strip_symbols_with_external_utility(sess, stripcmd, out_filename, Some(&strip_options))
+                    sess,
+                    stripcmd,
+                    out_filename,
+                    Some(&strip_options),
+                    Some(&strip_options),
+                )
             }
             Strip::None => {}
         }
fmt error: Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/compiler/rustc_query_system/src/query/caches.rs" "/checkout/compiler/rustc_codegen_ssa/src/back/linker.rs" "/checkout/compiler/rustc_codegen_ssa/src/back/symbol_export.rs" "/checkout/compiler/rustc_query_system/src/query/job.rs" "/checkout/compiler/rustc_codegen_ssa/src/back/write.rs" "/checkout/compiler/rustc_query_system/src/query/mod.rs" "/checkout/compiler/rustc_codegen_ssa/src/back/rpath.rs" "/checkout/compiler/rustc_codegen_ssa/src/back/lto.rs" "/checkout/compiler/rustc_query_system/src/error.rs" "/checkout/compiler/rustc_codegen_ssa/src/back/rpath/tests.rs" "/checkout/compiler/rustc_codegen_ssa/src/back/apple/tests.rs" "/checkout/compiler/rustc_codegen_ssa/src/back/metadata.rs" "/checkout/compiler/rustc_codegen_ssa/src/back/archive.rs" "/checkout/compiler/rustc_codegen_ssa/src/back/command.rs" "/checkou [...]

2024-11-19 20:50 UTC, mustartt reviewed
nit: consider changing `Option<&[String]>` to maybe `&[&str]` so we don't need to use `to_string`.

2024-11-19 22:38 UTC, xingxue-ibm commented
> nit: consider changing `Option<&[String]>` to maybe `&[&str]` so we don't need to use `to_string`.

Good point, thanks!

2024-11-20 06:54 UTC, lqd commented
Similarly you don't need the vec.

2024-11-20 12:45 UTC, xingxue-ibm commented
> Similarly you don't need the vec.

Thanks for pointing this out, @lqd! This makes the code much better!

2024-11-20 13:08 UTC, lqd commented
Sure, no problem.

Also, from a quick read:
- you probably don't need the Option, and could use empty slices for no options
- can likely use https://doc.rust-lang.org/nightly/nightly-rustc/rustc_codegen_ssa/back/command/struct.Command.html#method.args in `strip_symbols_with_external_utility`
- (also, it'd be better to squash the commits)

2024-11-21 04:24 UTC, compiler-errors requested changes

2024-11-21 04:24 UTC, compiler-errors commented on compiler/rustc_codegen_ssa/src/back/link.rs
> +                strip_symbols_with_external_utility(sess, stripcmd, out_filename, &[""])
Shouldn't this be `&[]`?

2024-11-21 17:19 UTC, xingxue-ibm commented on compiler/rustc_codegen_ssa/src/back/link.rs
> +                strip_symbols_with_external_utility(sess, stripcmd, out_filename, &[""])
Fixed, thanks!

2024-11-23 23:25 UTC, merged

2024-11-26 02:31 UTC, mustartt commented
This fixes a lot of test cases on AIX and allows the strip to function properly without `OBJECT_MODE=64`.

@rustbot label beta-nominate

2024-11-26 02:35 UTC, mustartt commented
@rustbot label beta-nominated

2024-11-28 15:09 UTC, apiraino commented
Beta backport declined as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-11-28/near/484940082). As far as we can see this is not fixing a regression, so we think it can wait the next release cycle

@rustbot label -beta-nominated