Suggest considering casting fn item as fn pointer in more cases
rust-lang/rust pull request #133382
Opened 2024-11-23 16:05 UTC by mu001999

Fixes #132648

2024-11-23 16:15 UTC, compiler-errors requested changes
Thanks for the contribution, but I think this logic is a bit too ad-hoc to land.

As an alternative approach, could you find the logic that ends up producing this note:

> for that trait implementation, expected `fn()` found `fn() {foo}`

And instead try to add a note *there*? That logic should be responsible for peeling off all the types until the type mismatch, which should make it much simpler and not require us to reimplement a new kind of method to peel off ADTs to discover fn type mismatches.

2024-11-23 16:53 UTC, mu001999 commented
@compiler-errors Just checking the found ty and expected ty at [fulfillment_errors.rs](https://github.com/rust-lang/rust/pull/133382/files#diff-041bd2d240b83e63aec8b30dee0eba73a7e4bfaf681309d129b06f8538f1d46cR1972) will work, but it only handles the cases that we know both tys are fns.

I want to suggest in more cases, just like the second statement in the test, e.g., `let _: Vec<fn()> = Vec::from([foo]);`. We got expected `Vec<fn()>`, and found `Vec<fn() {foo}>`, so I add the logic to help do this.

Do you think just adding a help for the simple case is enough? If so I can open another PR which will do less ;)

2024-11-23 23:48 UTC, compiler-errors commented
@mu001999: What I'm saying is that this logic largely replicates, and I don't think I can see why this needs to be reimplemented in a particularly verbose way.

When we have a type mismatch like `Vec<fn()>` and `Vec<fn() {foo}>`, we return something called `TypeError::Sorts` that should contain the `fn` pointers themselves.

I think that working backwards to understand the function and trying to generalize the existing `suggest_function_pointers` function and also make sure it has enough information to understand situations like this is better than adding more logic to the compiler which will likely need to eventually be deduplicated in the future.

2024-11-24 05:45 UTC, mu001999 commented
r? @compiler-errors

2025-01-23 18:08 UTC, compiler-errors commented
Sorry, don't have the context to get back into this PR.

r? compiler

2025-01-28 11:36 UTC, lcnr commented on compiler/rustc_trait_selection/src/error_reporting/infer/suggest.rs
> +            self.suggest_function_pointers_impl(None, &exp_found, diag);
why not always provide the span here?

2025-01-28 11:38 UTC, lcnr commented on tests/ui/did_you_mean/casting-fn-item-to-fn-pointer.rs
> +//@ edition: 2021
why does this test rely on an edition?

2025-01-28 11:54 UTC, mu001999 commented on compiler/rustc_trait_selection/src/error_reporting/infer/suggest.rs
> +            self.suggest_function_pointers_impl(None, &exp_found, diag);
because the span may not match the final exp_found

2025-01-28 12:22 UTC, mu001999 commented on tests/ui/did_you_mean/casting-fn-item-to-fn-pointer.rs
> +//@ edition: 2021
for the original case in the issue, we cannot get the same TypeError in edition 2018, but I found the two cases in the test can get same TypeError in different editions.

I have updated the test with the original case, which cannot pass in edition 2018

2025-01-28 14:10 UTC, lcnr commented on compiler/rustc_trait_selection/src/error_reporting/infer/suggest.rs
> +            self.suggest_function_pointers_impl(None, &exp_found, diag);
I would expect the exp_found to still "contained" by that span, shouldn't it? as in, what's the impact on the diagnostic when always passing in the span?

2025-01-28 15:45 UTC, mu001999 commented on compiler/rustc_trait_selection/src/error_reporting/infer/suggest.rs
> +            self.suggest_function_pointers_impl(None, &exp_found, diag);
for the third case in the test, passing span would lead to:
```
help: consider casting to a fn pointer
   |
LL |     let _: Vec<fn()> = foo as fn();
   |                        ~~~~~~~~~~~
```

2025-01-29 08:49 UTC, lcnr commented
@bors r+ rollup

2025-01-29 19:15 UTC, merged