add `-Zmin-function-alignment`
rust-lang/rust pull request #134030
Opened 2024-12-08 10:56 UTC by folkertdev

tracking issue: https://github.com/rust-lang/rust/issues/82232

This PR adds the `-Zmin-function-alignment=<align>` flag, that specifies a minimum alignment for all* functions.

### Motivation

This feature is requested by RfL [here](https://github.com/rust-lang/rust/issues/128830):

> i.e. the equivalents of `-fmin-function-alignment` ([GCC](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-fmin-function-alignment_003dn), Clang does not support it) / `-falign-functions` ([GCC](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-falign-functions), [Clang](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang1-falign-functions)).
> 
> For the Linux kernel, the behavior wanted is that of GCC's `-fmin-function-alignment` and Clang's `-falign-functions`, i.e. align all functions, including cold functions.
> 
> There is [`feature(fn_align)`](https://github.com/rust-lang/rust/issues/82232), but we need to do it globally.

### Behavior

The `fn_align` feature does not have an RFC. It was decided at the time that it would not be necessary, but maybe we feel differently about that now? In any case, here are the semantics of this flag:

- `-Zmin-function-alignment=<align>` specifies the minimum alignment of all* functions 
- the `#[repr(align(<align>))]` attribute can be used to override the function alignment on a per-function basis: when `-Zmin-function-alignment` is specified, the attribute's value is only used when it is higher than the value passed to `-Zmin-function-alignment`. 
- the target may decide to use a higher value (e.g. on x86_64 the minimum that LLVM generates is 16)
- The highest supported alignment in rust is `2^29`: I checked a bunch of targets, and they all emit the `.p2align        29` directive for targets that align functions at all (some GPU stuff does not have function alignment).

*: Only with `build-std` would the minimum alignment also be applied to `std` functions. 

---

cc @ojeda 

r? @workingjubilee you were active on the tracking issue

2024-12-08 22:18 UTC, workingjubilee commented
Yes, the 2^29 alignment is a limit imposed by LLVM.

2024-12-13 14:33 UTC, folkertdev commented
Yeah what I can't quite figure out is when targets actually support that (e.g. on embedded targets, you probably don't have enough space for `.p2align 29`). Anyway I guess we're doing the best we can here, and you could already use `repr(align(1 << 29))` on these targets and get a broken program.

Also I just added support for `#[naked]` functions. They emit their own `.balign` directive directly and therefore need custom logic and testing.

2024-12-16 02:57 UTC, workingjubilee commented
Yeah, I don't think we need to worry about that. Using broken alignments on targets without virtual memory mapping is already deeply incorrect.

2024-12-16 14:02 UTC, folkertdev commented
So, then, is there anything else that needs to happen here?

2025-01-05 00:52 UTC, workingjubilee requested changes
Mostly for me to have more bandwidth for doing reviews, apparently!

I suppose this should be added to the "unstable book"? src/doc/unstable-book

2025-01-08 19:50 UTC, folkertdev commented
@rustbot ready

2025-01-10 19:50 UTC, workingjubilee requested changes
The documentation seems to be incorrect.

I'd also just like to see something higher than 16 and 32 for a test (or test revision). Let's get sillier. Have one of the values be outside the range of a u8, say.

2025-01-10 19:50 UTC, workingjubilee commented on src/doc/unstable-book/src/compiler-flags/min-function-alignment.md
> +The `align` value is interpreted as a power of 2: `-Zmin-function-alignment=5` aligns functions to 32 bytes.
This seems to be suggesting that we will take the argument of `-Zmin-function-alignment` and perform `2.pow(arg)`? That or it is trying to say 5 rounds up to 8.

2025-01-10 19:50 UTC, workingjubilee commented on tests/codegen/min-function-alignment.rs
> +//@ compile-flags: -C no-prepopulate-passes -Z mir-opt-level=0 -Zmin-function-alignment=16
here we set `-Zmin-function-alignment=16`, which if `16` is interpreted as the argument to `2.pow(arg)`, would mean the alignment should be 65536? so the earlier documentation can't be correct.

2025-01-10 21:34 UTC, folkertdev commented on src/doc/unstable-book/src/compiler-flags/min-function-alignment.md
> +The `align` value is interpreted as a power of 2: `-Zmin-function-alignment=5` aligns functions to 32 bytes.
right, I got things mixed up and this is incorrect, I'll fix that.

The implementation uses `Align::from_bytes` to parse the value. That function rejects any value that is not a power of 2. The GCC and Clang flags also take the value as a number of bytes, but perform a `arg.next_power_of_2()`, so that e.g. `31` is equivalent to `32`. We could of course do that too, but the stricter argument parsing seems right for rust.

2025-01-10 21:36 UTC, workingjubilee commented on src/doc/unstable-book/src/compiler-flags/min-function-alignment.md
> +The `align` value is interpreted as a power of 2: `-Zmin-function-alignment=5` aligns functions to 32 bytes.
If we wish to reject inputs like `-Zmin-function-alignment=31` then that seems best to test.

2025-01-10 22:00 UTC, folkertdev commented
@rustbot ready

- fixed the docs
- we're now also testing for an alignment of 1024 bytes (well what we're testing is that we pass that on to llvm correctly, and we trust that it generates the right things).
- we now also test that `min-function-alignment` overrides a `repr(align)` if the value passed to the flag is higher than the one provided by the attribute.

2025-01-11 05:39 UTC, workingjubilee approved these changes
Much better!

2025-01-11 05:39 UTC, workingjubilee commented
@bors r+

2025-01-11 18:07 UTC, RalfJung commented
To be clear, there's no problem linking two crates that use different values for this? The compiler will not *assume* that all function pointers it sees are sufficiently aligned; it will merely decide to align the functions emitted in this particular session in the described way?

2025-01-11 18:29 UTC, folkertdev commented
Yes that's right. You can think of this flag as annotating all functions for which code is generated with  

```rust
#[repr(align<value>))]
```

No assumptions are made about code from other crates, `extern fn`s or anything like that.

2025-01-11 20:44 UTC, merged