Implement `IntoIterator` for `[&[mut]] Box<[T; N], A>`
rust-lang/rust pull request #134021
Opened 2024-12-08 05:07 UTC by WaffleLapkin

Revival of #124108

I copied the `<[T; N] as IntoIterator>::Iter`'s impl, but this does not seem satisfying:
1. I had to make `IndexRange` public
2. this duplicates a lot of code
3. it's unclear if the copied unsafe and spec code is worth it

r? @scottmcm
maybe you have better implementation ideas.

2024-12-08 05:29 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12219050103/job/34085257408) [(plain)](https://github.com/rust-lang/rust/commit/f1ca4a5b941a2c46470effe367f3f74bc38569fd/checks/34085257408/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 exporting to docker image format
#16 sending tarball 28.2s done
#16 DONE 33.5s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
---- [ui] tests/ui/iterators/into-iter-on-arrays-2018.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/iterators/into-iter-on-arrays-2018.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/iterators/into-iter-on-arrays-2018" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--edition=2018"
--- stderr -------------------------------
error[E0308]: mismatched types
##[error]  --> /checkout/tests/ui/iterators/into-iter-on-arrays-2018.rs:18:28
   |
   |
LL |     let _: Iter<'_, i32> = Box::new(array).into_iter();
   |            -------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Iter<'_, i32>`, found `BoxedArrayIntoIter<i32, 10, Global>`
   |            expected due to this
   |
   = note: expected struct `std::slice::Iter<'_, i32>`
              found struct `boxed::iter::BoxedArrayIntoIter<i32, 10, std::alloc::Global>`
---
---- [ui] tests/ui/iterators/into-iter-on-arrays-2021.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/iterators/into-iter-on-arrays-2021.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/iterators/into-iter-on-arrays-2021" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--edition=2021"
--- stderr -------------------------------
error[E0308]: mismatched types
##[error]  --> /checkout/tests/ui/iterators/into-iter-on-arrays-2021.rs:13:32
   |
   |
LL |     let _: IntoIter<i32, 10> = Box::new(array).into_iter();
   |            -----------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `IntoIter<i32, 10>`, found `BoxedArrayIntoIter<i32, 10, Global>`
   |            expected due to this
   |
   = note: expected struct `std::array::IntoIter<i32, 10>`
              found struct `boxed::iter::BoxedArrayIntoIter<i32, 10, std::alloc::Global>`
---

67 LL |     IntoIterator::into_iter([0u8; 33]);
68    |     ++++++++++++++++++++++++         ~
69 
- warning: this method call resolves to `<&[T; N] as IntoIterator>::into_iter` (due to backwards compatibility), but will resolve to `<[T; N] as IntoIterator>::into_iter` in Rust 2021
-    |
-    |
- LL |     Box::new(small).into_iter();
-    |                     ^^^^^^^^^ help: use `.iter()` instead of `.into_iter()` to avoid ambiguity: `iter`
-    = warning: this changes meaning in Rust 2021
-    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/IntoIterator-for-arrays.html>
- 
- 
- warning: this method call resolves to `<&[T; N] as IntoIterator>::into_iter` (due to backwards compatibility), but will resolve to `<[T; N] as IntoIterator>::into_iter` in Rust 2021
-    |
-    |
- LL |     Box::new([1, 2]).into_iter();
-    |                      ^^^^^^^^^ help: use `.iter()` instead of `.into_iter()` to avoid ambiguity: `iter`
-    = warning: this changes meaning in Rust 2021
-    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/IntoIterator-for-arrays.html>
- 
- 
- warning: this method call resolves to `<&[T; N] as IntoIterator>::into_iter` (due to backwards compatibility), but will resolve to `<[T; N] as IntoIterator>::into_iter` in Rust 2021
-    |
-    |
- LL |     Box::new(big).into_iter();
-    |                   ^^^^^^^^^ help: use `.iter()` instead of `.into_iter()` to avoid ambiguity: `iter`
-    = warning: this changes meaning in Rust 2021
-    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/IntoIterator-for-arrays.html>
- 
- 
- warning: this method call resolves to `<&[T; N] as IntoIterator>::into_iter` (due to backwards compatibility), but will resolve to `<[T; N] as IntoIterator>::into_iter` in Rust 2021
-    |
-    |
- LL |     Box::new([0u8; 33]).into_iter();
-    |                         ^^^^^^^^^ help: use `.iter()` instead of `.into_iter()` to avoid ambiguity: `iter`
-    = warning: this changes meaning in Rust 2021
-    = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/IntoIterator-for-arrays.html>
- 
- 
- warning: this method call resolves to `<&[T; N] as IntoIterator>::into_iter` (due to backwards compatibility), but will resolve to `<[T; N] as IntoIterator>::into_iter` in Rust 2021
-    |
-    |
- LL |     Box::new(Box::new(small)).into_iter();
-    |                               ^^^^^^^^^ help: use `.iter()` instead of `.into_iter()` to avoid ambiguity: `iter`
-    = warning: this changes meaning in Rust 2021
-    = note: for more information, see <https://doc.rust-lang.org/nig [...]

2024-12-08 20:45 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12224805263/job/34098020239) [(plain)](https://github.com/rust-lang/rust/commit/6f3a44bd750e4f346ba657ff14c813a9dadb97d2/checks/34098020239/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 exporting to docker image format
#16 sending tarball 28.4s done
#16 DONE 34.1s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
  Downloaded boml v0.3.1
   Compiling boml v0.3.1
   Compiling y v0.1.0 (/checkout/compiler/rustc_codegen_gcc/build_system)
    Finished `release` profile [optimized] target(s) in 4.04s
     Running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-codegen/x86_64-unknown-linux-gnu/release/y test --use-system-gcc --use-backend gcc --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc --release --mini-tests --std-tests`
Using system GCC
[BUILD] example
[AOT] mini_core_hello_world
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc/mini_core_hello_world
abc
---
##[group]Building stage0 tool linkchecker (x86_64-unknown-linux-gnu)
    Finished `release` profile [optimized] target(s) in 0.14s
##[endgroup]
##[group]Testing stage0 Linkcheck (x86_64-unknown-linux-gnu)
alloc/fmt/trait.Debug.html:117: broken link - `core/ops/index_range/struct.IndexRange.html`
number of HTML files scanned: 44031
number of HTML redirects found: 13780
number of links checked: 2650443
number of links ignored due to external: 84081
number of links ignored due to external: 84081
number of links ignored due to exceptions: 17
number of intra doc links ignored: 8
errors found: 1
found some broken links
NOTE: if you are adding or renaming a markdown file in a mdBook, don't forget to register the page in SUMMARY.md
Command has failed. Rerun with -v to see more details.
  local time: Sun Dec  8 20:45:03 UTC 2024
  network time: Sun, 08 Dec 2024 20:45:03 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-12-10 01:59 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12247317463/job/34164933310) [(plain)](https://github.com/rust-lang/rust/commit/576e7045a935e1c065693c487e1ab0aca76b83ff/checks/34164933310/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 exporting to docker image format
#16 sending tarball 28.6s done
#16 DONE 34.1s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
  Downloaded boml v0.3.1
   Compiling boml v0.3.1
   Compiling y v0.1.0 (/checkout/compiler/rustc_codegen_gcc/build_system)
    Finished `release` profile [optimized] target(s) in 3.96s
     Running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-codegen/x86_64-unknown-linux-gnu/release/y test --use-system-gcc --use-backend gcc --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc --release --mini-tests --std-tests`
Using system GCC
[BUILD] example
[AOT] mini_core_hello_world
/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc/mini_core_hello_world
abc
---
---- [run-make] tests/run-make/alloc-no-oom-handling stdout ----

error: rmake recipe failed to complete
status: exit status: 1
command: cd "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/alloc-no-oom-handling/rmake_out" && env -u RUSTFLAGS AR="ar" CARGO="/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools-bin/cargo" CC="cc" CC_DEFAULT_FLAGS="-ffunction-sections -fdata-sections -fPIC -m64" CXX="c++" CXX_DEFAULT_FLAGS="-ffunction-sections -fdata-sections -fPIC -m64" HOST_RPATH_DIR="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools-bin:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" LD_LIB_PATH_ENVVAR="LD_LIBRARY_PATH" LLVM_BIN_DIR="/usr/lib/llvm-18/bin" LLVM_COMPONENTS="aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets amdgpu amdgpuasmparser amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgputargetmca amdgpuutils analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter bpf bpfasmparser bpfcodegen bpfdesc bpfdisassembler bpfinfo cfguard codegen codegentypes core coroutines coverage debuginfobtf debuginfocodeview debuginfodwarf debuginfogsym debuginfologicalview debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker dwarflinkerclassic dwarflinkerparallel dwp engine executionengine extensions filecheck frontenddriver frontendhlsl frontendoffloading frontendopenacc frontendopenmp fuzzercli fuzzmutate globalisel hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo hipstdpar instcombine instrumentation interfacestub interpreter ipo irprinter irreader jitlink lanai lanaiasmparser lanaicodegen lanaidesc lanaidisassembler lanaiinfo libdriver lineeditor linker loongarch loongarchasmparser loongarchcodegen loongarchdesc loongarchdisassembler loongarchinfo lto m68k m68kasmparser m68kcodegen m68kdesc m68kdisassembler m68kinfo mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts objcopy object objectyaml option orcdebugging orcjit orcshared orctargetprocess passes perfjitevents powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo riscvtargetmca runtimedyld scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target targetparser textapi textapibinaryreader transformutils ve veasmparser vecodegen vectorize vedesc vedisassembler veinfo webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo webassemblyutils windowsdriver windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info x86targetmca xcore xcorecodegen xcoredesc xcoredisassembler xcoreinfo xray xtensa xtensaasmparser xtensacodegen xtensadesc xtensadisassembler xtensainfo" LLVM_FILECHECK="/usr/lib/llvm-18/bin/FileCheck" NODE="/usr/bin/node" PYTHON="/usr/bin/python3" RUSTC="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" RUSTDOC="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc" SOURCE_ROOT="/checkout" TARGET="x86_64-unknown-linux-gnu" TARGET_RPATH_DIR="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" TARGET_RPATH_ENV="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/alloc-no-oom-handling/rmake_out:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/alloc-no-oom-handling/rmake"
--- stderr -------------------------------
command failed at line 14
command failed at line 14
Command { cmd: LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/alloc-no-oom-handling/rmake_out:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools-bin:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/alloc-no-oom-handling/rmake_out" "--edition" "2021" "-Dwarnings" "--crate-type" "rlib" "/checkout/library/alloc/src/lib.rs" "--cfg" "no_global_oom_handling", stdin_buf: None, stdin: None, stdout: None, stderr: None, drop_bomb: DropBomb { command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc", defused: true, armed_location: Location { file: "/checkout/tests/run-make/alloc-no-oom-handling/rmake.rs", line: 8, col: 5 } }, already_executed: true }
output status: `exit status: 1`
=== STDO [...]

2025-04-14 10:36 UTC, WaffleLapkin commented on library/alloc/src/boxed/iter.rs
> +pub struct BoxedArrayIntoIter<T, const N: usize, A: Allocator = Global> {
Thinking about it again, I think we should merge this as-is. We can always make an abstraction like you suggest later. @rustbot review

2025-12-08 14:17 UTC, WaffleLapkin commented
@scottmcm anything I can do to move this forward?

2026-02-08 18:23 UTC, scottmcm commented
@rustbot reroll

2026-02-14 18:19 UTC, Mark-Simulacrum requested changes
I guess this also needs rebasing + FCP, maybe starting with the FCP makes sense since it's not obvious to me this is worth it (especially if it needs an edition change...)

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/134021/6b3ae3f6e45a33c2d95fa0362c9b2593e567fd34..6bcd9c3d5627d839253bf06428304b9e6157c1b9)*

2026-02-14 18:19 UTC, Mark-Simulacrum commented on library/alloc/src/boxed/iter.rs
> +// always decremented by 1 in those methods, but only if `Some(_)` is returned.
"It is always decremented[...], but only if" seems like odd phrasing. I think we can just delete this sentence?

2026-02-14 18:19 UTC, Mark-Simulacrum commented on library/alloc/src/boxed/iter.rs
> +                [const { MaybeUninit::uninit() }; N],
nit: should this use the uninit constructors to avoid the memcpy given large N?

2026-02-14 18:19 UTC, Mark-Simulacrum commented on library/alloc/src/boxed/iter.rs
> +unsafe impl<T, const N: usize, A: Allocator> TrustedRandomAccessNoCoerce
I think it'd be good for this to have a SAFETY comment.

2026-02-14 18:19 UTC, Mark-Simulacrum commented on tests/ui/iterators/into-iter-on-arrays-lint.stderr
Should this get the same treatment as array IntoIterator did? Maybe starting with edition next (~2026/2027)?

2026-03-10 12:43 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-gcc`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/22901087653/job/66447592455) [(plain enhanced)](https://triage.rust-lang.org/gha-logs/rust-lang/rust/66447592455) [(plain)](https://github.com/rust-lang/rust/commit/366152cd5fba983ad438f1d176b9ca53af2aba9b/checks/66447592455/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
/dev/sda15      105M  6.2M   99M   6% /boot/efi
tmpfs           1.6G   12K  1.6G   1% /run/user/1001
================================================================================

Sufficient disk space available (95909292KB >= 52428800KB). Skipping cleanup.
##[group]Run echo "[CI_PR_NUMBER=$num]"
echo "[CI_PR_NUMBER=$num]"
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
---
[RUSTC-TIMING] profiler_builtins test:false 0.029
   Compiling rustc-std-workspace-core v1.99.0 (/checkout/library/rustc-std-workspace-core)
   Compiling alloc v0.0.0 (/checkout/library/alloc)
[RUSTC-TIMING] rustc_std_workspace_core test:false 0.041
error[E0277]: `[MaybeUninit<T>; N]` is not an iterator
   --> library/alloc/src/boxed/iter.rs:430:59
    |
430 |         for (src, dst) in iter::zip(self.as_slice(), &mut new.data) {
    |                           ---------                       ^^^^^^^^ `[MaybeUninit<T>; N]` is not an iterator
    |                           |
    |                           required by a bound introduced by this call
    |
    = help: the trait `Iterator` is not implemented for `[MaybeUninit<T>; N]`
help: the following other types implement trait `IntoIterator`
   --> library/alloc/src/boxed/iter.rs:117:1
    |
117 | impl<I, A: Allocator> IntoIterator for Box<[I], A> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `Box<[I], A>`
...
126 | impl<'a, I, A: Allocator> IntoIterator for &'a Box<[I], A> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `&Box<[I], A>`
...
135 | impl<'a, I, A: Allocator> IntoIterator for &'a mut Box<[I], A> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `&mut Box<[I], A>`
...
452 | impl<T, const N: usize, A: Allocator> IntoIterator for Box<[T; N], A> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `Box<[T; N], A>`
note: required for `Box<[MaybeUninit<T>; N], A>` to implement `Iterator`
   --> library/alloc/src/boxed/iter.rs:21:42
    |
 21 | impl<I: Iterator + ?Sized, A: Allocator> Iterator for Box<I, A> {
    |         --------                         ^^^^^^^^     ^^^^^^^^^
    |         |
    |         unsatisfied trait bound introduced here
    = note: 1 redundant requirement hidden
    = note: required for `&mut Box<[MaybeUninit<T>; N], A>` to implement `Iterator`
    = note: required for `&mut Box<[MaybeUninit<T>; N], A>` to implement `IntoIterator`
note: required by a bound in `core::iter::zip`
   --> library/core/src/iter/adapters/zip.rs:70:8
    |
 67 | pub fn zip<A, B>(a: A, b: B) -> Zip<A::IntoIter, B::IntoIter>
    |        --- required by a bound in this function
...
 70 |     B: IntoIterator,
    |        ^^^^^^^^^^^^ required by this bound in `zip`

error[E0277]: `[MaybeUninit<T>; N]` is not an iterator
   --> library/alloc/src/boxed/iter.rs:430:27
    |
430 |         for (src, dst) in iter::zip(self.as_slice(), &mut new.data) {
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `[MaybeUninit<T>; N]` is not an iterator
    |
    = help: the trait `Iterator` is not implemented for `[MaybeUninit<T>; N]`
note: required for `Box<[MaybeUninit<T>; N], A>` to implement `Iterator`
   --> library/alloc/src/boxed/iter.rs:21:42
    |
 21 | impl<I: Iterator + ?Sized, A: Allocator> Iterator for Box<I, A> {
    |         --------                         ^^^^^^^^     ^^^^^^^^^
    |         |
    |         unsatisfied trait bound introduced here
    = note: 2 redundant requirements hidden
    = note: required for `Zip<core::slice::Iter<'_, T>, &mut Box<[MaybeUninit<T>; N], A>>` to implement `Iterator`
    = note: required for `Zip<core::slice::Iter<'_, T>, &mut Box<[MaybeUninit<T>; N], A>>` to implement `IntoIterator`

error[E0277]: `[MaybeUninit<T>; N]` is not an iterator
   --> library/alloc/src/boxed/iter.rs:430:27
    |
430 |         for (src, dst) in iter::zip(self.as_slice(), &mut new.data) {
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `[MaybeUninit<T>; N]` is not an iterator
    |
    = help: the trait `Iterator` is not implemented for `[MaybeUninit<T>; N]`
help: the following other types implement trait `IntoIterator`
   --> library/alloc/src/boxed/iter.rs:117:1
    |
117 | impl<I, A: Allocator> IntoIterator for Box<[I], A> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `Box<[I], A>`
...
126 | impl<'a, I, A: Allocator> IntoIterator for &'a Box<[I], A> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `&Box<[I], A>`
...
135 | impl<'a, I, A: Allocator> IntoIterator for &'a mut Box<[I], A> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `&mut Box<[I], A>`
...
452 | impl<T, const N: usize, A: Allocator> IntoIterator for Box<[T; N], A> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `Box<[T; N], A>`
note: required for `Box<[MaybeUninit<T>; N], A>` to implement `Iterator`
   --> library/alloc/src/boxed/iter.rs:21:42
    |
 21 | impl<I: Iterator + ?Sized, A: Allocator> Iterator for Box<I, A> {
    |         --------                         ^^^^^^^^     ^^^^^^^^^
    |         |
    |         unsatisfied trait bound introduced here
    = note: 1 redundant requirement hidden
    = note: required for `&mut Box<[MaybeUninit<T>; N], A>` to implement `Iterator`
    = note: required for `&mut Box<[MaybeUninit<T>; N], A>` to implement `IntoIterator`

[RUSTC-TIMING] libc test:false 1.789
   Compiling unwind v0.0.0 (/checkout/library/unwind)
[RUSTC-TIMING] unwind test:false 0.069
   Compiling memchr v2.7.6
```

</details>

For more information how to resolve CI failures of this job, visit this [link](https://rustc-dev-guide.rust-lang.org/tests/codegen-backend-tests/cg_gcc.html).

2026-03-10 15:13 UTC, WaffleLapkin commented
@Mark-Simulacrum I don't think this requires edition handling or FCP, as per the FCP on the previous attempt at doing this:
- https://github.com/rust-lang/rust/pull/124108#issuecomment-2072899815
- https://github.com/rust-lang/rust/pull/124108#issuecomment-2072923867


@rustbot review

2026-03-10 15:17 UTC, WaffleLapkin commented
I've also removed the complicated unsafe impl for now, making the `BoxedArrayIntoIter` a wrapper around `vec::IntoIter`. I'll add back the more complicated impl in a follow-up.

2026-03-10 16:27 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-gcc`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/22909767566/job/66478812299) [(plain enhanced)](https://triage.rust-lang.org/gha-logs/rust-lang/rust/66478812299) [(plain)](https://github.com/rust-lang/rust/commit/91e8eb2080d5a2e0dab7f4fc77e6697fba54a05c/checks/66478812299/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
/dev/sda15      105M  6.2M   99M   6% /boot/efi
tmpfs           1.6G   12K  1.6G   1% /run/user/1001
================================================================================

Sufficient disk space available (95909308KB >= 52428800KB). Skipping cleanup.
##[group]Run echo "[CI_PR_NUMBER=$num]"
echo "[CI_PR_NUMBER=$num]"
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
---
---- [run-make] tests/run-make/alloc-no-oom-handling stdout ----

error: rmake recipe failed to complete
status: exit status: 1
command: cd "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/alloc-no-oom-handling/rmake_out" && env -u RUSTFLAGS -u __RUSTC_DEBUG_ASSERTIONS_ENABLED -u __STD_DEBUG_ASSERTIONS_ENABLED -u __STD_REMAP_DEBUGINFO_ENABLED AR="ar" BUILD_ROOT="/checkout/obj/build/x86_64-unknown-linux-gnu" CC="cc" CC_DEFAULT_FLAGS="-ffunction-sections -fdata-sections -fPIC -m64" CXX="c++" CXX_DEFAULT_FLAGS="-ffunction-sections -fdata-sections -fPIC -m64" HOST_RUSTC_DYLIB_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" LD_LIB_PATH_ENVVAR="LD_LIBRARY_PATH" LLVM_BIN_DIR="/checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm/bin" LLVM_COMPONENTS="aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils abi aggressiveinstcombine all all-targets amdgpu amdgpuasmparser amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgputargetmca amdgpuutils analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter bpf bpfasmparser bpfcodegen bpfdesc bpfdisassembler bpfinfo cas cfguard cgdata codegen codegentypes core coroutines coverage csky cskyasmparser cskycodegen cskydesc cskydisassembler cskyinfo debuginfobtf debuginfocodeview debuginfodwarf debuginfodwarflowlevel debuginfogsym debuginfologicalview debuginfomsf debuginfopdb demangle dlltooldriver dtlto dwarfcfichecker dwarflinker dwarflinkerclassic dwarflinkerparallel dwp engine executionengine extensions filecheck frontendatomic frontenddirective frontenddriver frontendhlsl frontendoffloading frontendopenacc frontendopenmp fuzzercli fuzzmutate globalisel hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo hipstdpar instcombine instrumentation interfacestub interpreter ipo irprinter irreader jitlink libdriver lineeditor linker loongarch loongarchasmparser loongarchcodegen loongarchdesc loongarchdisassembler loongarchinfo lto m68k m68kasmparser m68kcodegen m68kdesc m68kdisassembler m68kinfo mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts objcopy object objectyaml option orcdebugging orcjit orcshared orctargetprocess passes plugins powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo riscvtargetmca runtimedyld sandboxir scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support supportlsp symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target targetparser telemetry textapi textapibinaryreader transformutils vectorize webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo webassemblyutils windowsdriver windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info x86targetmca xray xtensa xtensaasmparser xtensacodegen xtensadesc xtensadisassembler xtensainfo" LLVM_FILECHECK="/checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm/bin/FileCheck" PYTHON="/usr/bin/python3" RUSTC="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" RUSTDOC="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc" SOURCE_ROOT="/checkout" TARGET="x86_64-unknown-linux-gnu" TARGET_EXE_DYLIB_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" __BOOTSTRAP_JOBS="4" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/alloc-no-oom-handling/rmake"
stdout: none
--- stderr -------------------------------
command failed at line 14
Command { cmd: LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/alloc-no-oom-handling/rmake_out:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make/alloc-no-oom-handling/rmake_out" "--edition" "2024" "-Dwarnings" "--crate-type" "rlib" "/checkout/library/alloc/src/lib.rs" "--cfg" "no_global_oom_handling" "--target=x86_64-unknown-linux-gnu", stdin_buf: None, stdin: None, stdout: None, stderr: None, drop_bomb: DropBomb { command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc", defused: true, armed_location: Location { file: "/checkout/tests/run-make/alloc-no-oom-handling/rmake.rs", line: 8, column: 5 } }, already_executed: true, context: "" }
output status: `exit status: 1`
=== STDOUT ===



=== STDERR ===
error[E0599]: no method named `clone` found for struct `into_iter::IntoIter<T, A>` in the current scope
---
   ::: /checkout/library/alloc/src/vec/into_iter.rs:45:1
    |
 45 | / pub struct IntoIter<
 46 | |     T,
 47 | |     #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator = Global,
 48 | | > {
    | |_- method `clone` not found for this struct
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `clone`, perhaps you need to implement it:
            candidate #1: `Clone`
help: there is a method `cloned` with a similar name
```

</details>

For more information how to resolve CI failures of this job, visit this [link](https://rustc-dev-guide.rust-lang.org/tests/codegen-backend-tests/cg_gcc.html).

2026-03-16 21:29 UTC, Mark-Simulacrum reviewed
> I don't think this requires edition handling or FCP, as per the FCP on the previous attempt at doing this:

I think we do need FCP or at least libs-api meeting nomination to re-confirm that the >1 year old FCP from 2024 is still valid. Maybe a Crater run. This is a breaking change and there was some post-initial-FCP discussion on whether we should do the unsizing impl (https://github.com/rust-lang/rust/pull/124108#issuecomment-2078523714). Making two breaking changes here feels unfortunate so we should decide upfront which we want, even if we think the change is otherwise reasonable.

I guess the current version of this PR proposes neither option and instead has a dedicated new iterator type (BoxedArrayIntoIter). I think that's entirely net-new surface area, right? It also means we're missing a chunk of impls (e.g., DoubleEndedIterator) that we'd get 'for free' with vec::IntoIter.





*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/134021/0c68443b0a0469e4211acca7e7b06e14f256ada8..f65b35f2b18d1f243f988a1dfa2a68f344ae5f43)*

2026-03-17 14:54 UTC, WaffleLapkin commented
(for the libs-api nomination)

# API changes

## Negative impls

This PR adds the following negative impls (we promise that those types will never implement `Iterator`, this shouldn't be controversial) (this is required for the `IntoIterator` impls added, more below):

```rust
impl<T, const N: usize> !Iterator for [T; N] {}
impl<I, const N: usize, A: Allocator> !Iterator for Box<[I; N], A> {}
impl<'a, const N: usize, I, A: Allocator> !Iterator for &'a Box<[I; N], A> {}
impl<'a, const N: usize, I, A: Allocator> !Iterator for &'a mut Box<[I; N], A> {}
```

## `IntoIterator` impls

It also adds the following `IntoIterator` impls:

```rust
impl<'a, T, const N: usize, A: Allocator> IntoIterator for &'a Box<[T; N], A> {
    type IntoIter = slice::Iter<'a, T>;
    type Item = &'a T;
}

impl<'a, T, const N: usize, A: Allocator> IntoIterator for &'a mut Box<[T; N], A> {
    type IntoIter = slice::IterMut<'a, T>;
    type Item = &'a mut T;
}

impl<T, const N: usize, A: Allocator> IntoIterator for Box<[T; N], A> {
    type IntoIter = BoxedArrayIntoIter<T, N, A>;
    type Item = T;
}
```

## `BoxedArrayIntoIter`

And the following type with its impls (note: everything is insta-stable):

```rust
/// A by-value `Box<[T; N]>` iterator.
pub struct BoxedArrayIntoIter<T, const N: usize, A: Allocator = Global> { ... }

impl<T, const N: usize, A: Allocator> BoxedArrayIntoIter<T, N, A> {
    /// Returns an immutable slice of all elements that have not been yielded
    /// yet.
    pub fn as_slice(&self) -> &[T] { ... }

    /// Returns a mutable slice of all elements that have not been yielded yet.
    pub fn as_mut_slice(&mut self) -> &mut [T] { ... }
}

impl<T, const N: usize, A: Allocator> Iterator for BoxedArrayIntoIter<T, N, A> {
    type Item = T;
    ...
}

impl<T, const N: usize, A: Allocator> DoubleEndedIterator for BoxedArrayIntoIter<T, N, A> { ... }

impl<T, const N: usize, A: Allocator> ExactSizeIterator for BoxedArrayIntoIter<T, N, A> { ... }

impl<T, const N: usize, A: Allocator> FusedIterator for BoxedArrayIntoIter<T, N, A> {}

unsafe impl<T, const N: usize, A: Allocator> TrustedLen for BoxedArrayIntoIter<T, N, A> {}

impl<T: Clone, const N: usize, A: Clone + Allocator> Clone for BoxedArrayIntoIter<T, N, A> { ... }

impl<T: fmt::Debug, const N: usize, A: Allocator> fmt::Debug for BoxedArrayIntoIter<T, N, A> { ... }
```

# Breakage analysis

|                                  | `Box<[T; N]>`                                        | `&Box<[T; N]>`                                 | `&mut Box<[T; N]>`                                    |
|----------------------------------|------------------------------------------------------|------------------------------------------------|-------------------------------------------------------|
| `for` loop                       | ✅ compile error -> `T`                               | ✅ compile error -> `&T`                        | ✅ compile error -> `&mut T`                           |
| `.into_iter()` (edition >= 2021) | ⚠️ `array::IntoIter`->`BoxedArrayIntoIter` (`T`->`T`) | ☢️ `array::IntoIter`->`slice::Iter` (`T`->`&T`) | ☢️ `array::IntoIter`->`slice::IterMut` (`T`->`&mut T`) |
| `.into_iter()` (edition < 2021)  | ☢️ `slice::Iter`->`BoxedArrayIntoIter` (`&T`->`T`)    | ✅ `slice::Iter` (`Item = &T`) (unchanged)      | ☢️ `slice::Iter`->`slice::IterMut` (`&T`->`&mut T`)    |

Notes: 
- `for` loop / `<_>::into_iter(box)` used to be a compilation error; no breakage here
- on `edition >= 2021`, `.into_iter()` used to be extremely inefficient, as it would move out the whole array and put it unto the stack
  - on `edition >= 2021`, `.into_iter()` on a reference to a box requires `T: Copy`
- The emoji I used: ✅ - no breakage, ⚠️ - only iterator type changes, not the item (very unlikely to break something), ☢️ - both change

2026-03-17 14:56 UTC, WaffleLapkin commented
If the `.into_iter()` changes seem like a problem we can
1. Run crater on this PR to check if there is any actual breakage
2. Add a hack similarly to the one we added when implementing `IntoIterator` for arrays -- make `.into_iter()` resolve to the old thing before the next edition

2026-03-17 15:02 UTC, WaffleLapkin commented
> I guess the current version of this PR proposes neither option and instead has a dedicated new iterator type (`BoxedArrayIntoIter`). I think that's entirely net-new surface area, right? It also means we're missing a chunk of impls (e.g., `DoubleEndedIterator`) that we'd get 'for free' with `vec::IntoIter`.

No, we aren't missing any impls, since I added all of them :)

Also, this PR is compatible with the unsizing idea, with that you would have:
```rust
struct AllocatedContinuousIntoIter<T: ?Sized, A: Allocator = Global> { ... } // name bikeshedable

type vec::IntoIter<T, A: Allocator> = AllocatedContinuousIntoIter<[T], A>;
type box::BoxedArrayIntoIter<T, const N: usize, A: Allocator> = AllocatedContinuousIntoIter<[T; N], A>;
```

Note that `vec::IntoIter` and `box::BoxedArrayIntoIter` still normalize to different types, just like in this PR. So we will be able to do this in a follow up.

I.e. one of two follow ups is possible:
1. Making `BoxedArrayIntoIter`  use custom iterator impls, rather than wrapping `vec::IntoIter` as it does in this PR
2. Making `vec::IntoIter` more generic, so it can support both use cases (unsizing idea)

2026-03-17 15:22 UTC, Amanieu commented
@rfcbot merge libs-api

2026-03-21 14:46 UTC, Mark-Simulacrum approved these changes
r=me with FCP done

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/134021/0c68443b0a0469e4211acca7e7b06e14f256ada8..f65b35f2b18d1f243f988a1dfa2a68f344ae5f43)*

2026-03-21 14:46 UTC, Mark-Simulacrum commented on library/alloc/src/boxed/iter.rs
> +    }
It looks like we're missing overrides for `next_chunk`, `try_fold`, and probably `__iterator_get_unchecked`? Those are 'just' perf optimizations though.

I think the best way to fix this long-term is the change to have a common iterator type rather than duplicating all the surface area.

2026-04-21 10:36 UTC, programmerjake commented on library/alloc/src/boxed/iter.rs
> +pub struct BoxedArrayIntoIter<T, const N: usize, A: Allocator = Global> {
can you add `Default for BoxedArrayIntoIter<...>` that gives an empty iterator just like `vec::IntoIter` and `array::IntoIter`?

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/134021/4c4205163abcbd08948b3efab796c543ba1ea687..5d3dba6c35848d5031066369e1301db3fa99cc2e)*

2026-04-21 10:52 UTC, WaffleLapkin commented on library/alloc/src/boxed/iter.rs
> +pub struct BoxedArrayIntoIter<T, const N: usize, A: Allocator = Global> {
I don't want to change what the FCP is about, so maybe this should be left as a follow up?

2026-06-09 01:28 UTC, BurntSushi commented
Given the potential for breaking changes here, it seems prudent to do a crater run. I don't see that one has been done. Thoughts on doing so?

@rfcbot concern crater

2026-06-09 12:42 UTC, WaffleLapkin commented
@BurntSushi doing a crater run seems reasonable to me. I'll start it once the try build completes.

@bors try

2026-06-09 13:40 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/27206532106/job/80323842832) [(plain enhanced)](https://triage.rust-lang.org/gha-logs/rust-lang/rust/80323842832) [(plain)](https://github.com/rust-lang/rust/commit/6bf1d9312d391bfcacf137f57dca643ffcbcce57/checks/80323842832/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
...............................F.................. (50/144)
.................................................. (100/144)
............................................       (144/144)

======== tests/rustdoc-gui/go-to-collapsed-elem.goml ========

[ERROR] line 40
    at `tests/rustdoc-gui/go-to-collapsed-elem.goml` line 21: Error: Node is detached from document: for command `click: "//*[@id='search']//a[@href='../test_docs/struct.Foo.html#method.must_use']"`
    at <file:///checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc-gui/doc/test_docs/struct.Foo.html?search=t_use>


<= doc-ui tests done: 143 succeeded, 1 failed, 0 filtered out

Error: ()
```

</details>

2026-06-09 17:23 UTC, WaffleLapkin commented
@craterbot check

2026-06-12 16:30 UTC, theemathas commented
@craterbot cancel

See #157814

2026-06-16 09:23 UTC, theemathas commented
@craterbot check p=1 crates=https://crater-reports.s3.amazonaws.com/pr-157814-crater-rollup/retry-regressed-list.txt

2026-06-19 17:10 UTC, theemathas commented
Crater appears to be stuck doing nothing. Requeueing the run.

@craterbot cancel

2026-06-19 17:11 UTC, theemathas commented
@craterbot check p=2 crates=https://crater-reports.s3.amazonaws.com/pr-157814-crater-rollup/retry-regressed-list.txt

2026-06-19 23:52 UTC, theemathas commented
The crater run seems to be stuck again. Cancelling the run until we figure out what's going on. See https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/Crater.20maybe.20stuck.3F/near/604902260

@craterbot cancel

2026-06-20 19:20 UTC, Mark-Simulacrum commented
@craterbot check p=1 crates=https://crater-reports.s3.amazonaws.com/pr-157814-crater-rollup/retry-regressed-list.txt

2026-06-20 19:24 UTC, Mark-Simulacrum commented
@craterbot abort

2026-06-20 19:30 UTC, Mark-Simulacrum commented
@bors try

Figured out crater issue - see [#t-infra > Crater maybe stuck? @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/Crater.20maybe.20stuck.3F/near/605209994) - will fix that separately but for now we'll want a new try job and new crater.

2026-06-20 21:40 UTC, Mark-Simulacrum commented
@craterbot check

2026-06-20 23:33 UTC, theemathas commented
@Mark-Simulacrum Using the crate list from another PR was intentional.

@craterbot cancel

2026-06-20 23:33 UTC, theemathas commented
@craterbot check p=1 crates=https://crater-reports.s3.amazonaws.com/pr-157814-crater-rollup/retry-regressed-list.txt

2026-06-22 17:08 UTC, programmerjake commented
it looks like static-array 0.5 (the latest version) regressed because [`boxed_array.into_iter()`'s type changed](https://docs.rs/static-array/0.5.0/src/static_array/lib.rs.html#197), all the others look like experimental code so are less significant.

2026-06-23 10:56 UTC, WaffleLapkin commented
I don't think `static-array` is used much if at all, so I ~~don't~~ think this can be merged as-is.

(I did submit a PR fixing the issue though: https://github.com/WhyAreAllTheseTaken/static-array/pull/1)

2026-06-23 11:16 UTC, BurntSushi commented
@WaffleLapkin I assume you mean it _can_ be merged as-is?

I agree it isn't used much. It does have [one dependent](https://github.com/WhyAreAllTheseTaken/surface-grid) though that seems to be active. So I think we should be cautious here.

cc @WhyAreAllTheseTaken see https://github.com/WhyAreAllTheseTaken/static-array/pull/1

2026-06-23 14:50 UTC, WhyAreAllTheseTaken commented
> @WaffleLapkin I assume you mean it _can_ be merged as-is?
> 
> I agree it isn't used much. It does have [one dependent](https://github.com/WhyAreAllTheseTaken/surface-grid) though that seems to be active. So I think we should be cautious here.
> 
> cc @WhyAreAllTheseTaken see [WhyAreAllTheseTaken/static-array#1](https://github.com/WhyAreAllTheseTaken/static-array/pull/1)

I have published a new release to crates.io (0.5.1) with the pull request merged that should resolve the issue.

2026-06-23 15:11 UTC, BurntSushi commented
@rfcbot resolve crater

2026-06-23 16:11 UTC, programmerjake commented
> > @WaffleLapkin I assume you mean it _can_ be merged as-is?
> > I agree it isn't used much. It does have [one dependent](https://github.com/WhyAreAllTheseTaken/surface-grid) though that seems to be active. So I think we should be cautious here.
> > cc @WhyAreAllTheseTaken see [WhyAreAllTheseTaken/static-array#1](https://github.com/WhyAreAllTheseTaken/static-array/pull/1)
> 
> I have published a new release to crates.io (0.5.1) with the pull request merged that should resolve the issue.

unfortunately that was an incomplete fix: https://github.com/WhyAreAllTheseTaken/static-array/pull/1/changes#r3461196266
the PR missed at least one other `a_boxed_array.into_iter()` call.

2026-06-24 14:03 UTC, WaffleLapkin commented
> @WaffleLapkin I assume you mean it *can* be merged as-is?

@BurntSushi yes, that is what I meant 🤦🏻

2026-06-25 11:31 UTC, WhyAreAllTheseTaken commented
> > > @WaffleLapkin I assume you mean it _can_ be merged as-is?
> > > I agree it isn't used much. It does have [one dependent](https://github.com/WhyAreAllTheseTaken/surface-grid) though that seems to be active. So I think we should be cautious here.
> > > cc @WhyAreAllTheseTaken see [WhyAreAllTheseTaken/static-array#1](https://github.com/WhyAreAllTheseTaken/static-array/pull/1)
> > 
> > 
> > I have published a new release to crates.io (0.5.1) with the pull request merged that should resolve the issue.
> 
> unfortunately that was an incomplete fix: https://github.com/WhyAreAllTheseTaken/static-array/pull/1/changes#r3461196266 the PR missed at least one other `a_boxed_array.into_iter()` call.

static-array 0.5.2 is now released which includes https://github.com/WhyAreAllTheseTaken/static-array/pull/3 which should fix the issue.

2026-06-27 11:03 UTC, stepancheg commented on library/alloc/src/boxed/iter.rs
> +        f.debug_tuple("IntoIter").field(&self.as_slice()).finish()
BoxedArrayIntoIter?

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/134021/057ed8ba87418a77d5758f2d5e13f84b89b197e9..6bf1d9312d391bfcacf137f57dca643ffcbcce57)*

2026-06-28 16:04 UTC, Mark-Simulacrum commented on library/alloc/src/boxed/iter.rs
> +        f.debug_tuple("IntoIter").field(&self.as_slice()).finish()
```suggestion
        f.debug_tuple("BoxedArrayIntoIter").field(&self.as_slice()).finish()
```

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/134021/057ed8ba87418a77d5758f2d5e13f84b89b197e9..6bf1d9312d391bfcacf137f57dca643ffcbcce57)*

2026-06-28 16:15 UTC, Mark-Simulacrum commented
@bors squash msg="Implement `IntoIterator` for `[&[mut]] Box<[T; N], A>`"

2026-06-28 19:05 UTC, programmerjake commented
squashing gave a broken commit message, so I think you'll want to manually `git commit --amend` it.

(reported the bug [here](https://github.com/rust-lang/bors/issues/773))

2026-06-28 19:50 UTC, Mark-Simulacrum commented
@bors r+ rollup=iffy

2026-06-28 19:53 UTC, Mark-Simulacrum commented
Ah, I guess not quite ready, but r=me once the FCP elapses in ~5 days.

2026-07-03 15:46 UTC, Mark-Simulacrum commented
@bors r+

2026-07-05 23:50 UTC, merged

2026-08-28 11:18 UTC, theemathas commented
The [1.99 beta crater run](https://github.com/rust-lang/rust/issues/161326) found one more crate that regressed as a result of this. I'm going to assume that this is acceptable.

* https://crater-reports.s3.amazonaws.com/beta-1.99-4/1.99.0-beta.1/gh/blueguytr78.benim_rep_2/log.txt