Run TLS destructors at process exit on all platforms
rust-lang/rust pull request #134085
Opened 2024-12-09 17:19 UTC by surban

This calls TLS destructors for the thread that initiates a process exit. This is done by registering a process-wide
exit callback.

Previously UNIX platforms other than Linux and Apple did not destruct TLS variables on the thread that initiated the process exit (either by returning from `main` or calling `std::process::exit`).

This also adds a test to verify this behavior.

@joboet Can we run CI tests for all available platforms for this?

r? joboet

2025-01-03 18:19 UTC, joboet requested changes
Sorry for the delay, I've been quite busy recently.

At a first glance, the changes look mostly good. There is a problem with the TLS destructor registration however: the TLS key can be used as soon as it is initialized, so it is possible that another thread completes before the destructor is registered. Always registering the destructor is not an option either, since that might lead to cycles in the destructor list. Windows uses `INIT_ONCE` synchronization to resolve this issue, but replicating that might prove difficult on platforms without a native `Once`-like interface (`Once` itself cannot be used in the TLS code since it needs TLS itself). I think this is best solved by keeping a thread-local destructor list similar to the one used on platforms with native TLS, but using the keys (or perhaps references to the `LazyKey`s) instead of pointers to values. Or perhaps you can think of another way?

2025-01-13 21:12 UTC, surban commented
> There is a problem with the TLS destructor registration however: the TLS key can be used as soon as it is initialized, so it is possible that another thread completes before the destructor is registered. 

You are right.

> I think this is best solved by keeping a thread-local destructor list similar to the one used on platforms with native TLS, but using the keys (or perhaps references to the `LazyKey`s) instead of pointers to values.

I implemented it using references to `LazyKeys`.

2025-01-13 21:39 UTC, surban commented
I now have the problem that I need to register the `LazyKey` with the thread local list of destructors for *every* thread that uses it. Thus I need to call the `register_dtor` function once per thread that calls `LazyKey::force`. 

Do you have an idea how I could achieve that without registering a second TLS key per `LazyKey` that keeps track whether it has been added to the destructors list? An option might be to store a sentinel value (for example 1 or 2) as the TLS value to indicate that the `LazyKey` been registered. However, I am unsure if this is acceptable practice. What do you think?

2025-01-14 13:09 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12768171476/job/35588005655) [(plain)](https://github.com/rust-lang/rust/commit/ddec4b4af05912f5826b2e8687063dd4fad4fd8f/checks/35588005655/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking addr2line v0.24.2
error[E0599]: no method named `register_process_dtor` found for struct `LazyKey` in the current scope
  --> library/std/src/sys/thread_local/os.rs:84:26
   |
84 |                 self.key.register_process_dtor();
   |                          ^^^^^^^^^^^^^^^^^^^^^ method not found in `LazyKey`
  ::: library/std/src/sys/thread_local/key/windows.rs:37:1
   |
37 | pub struct LazyKey {
   | ------------------ method `register_process_dtor` not found for this struct
```

</details>

2025-01-14 13:39 UTC, surban commented
> I now have the problem that I need to register the `LazyKey` with the thread local list of destructors for _every_ thread that uses it. Thus I need to call the `register_dtor` function once per thread that calls `LazyKey::force`.

I solved this by modifying `os::Storage::get` so that it checks if the value is being initialized for a particular thread. If so, it calls a function to add the TLS key to the thread-local destructor list. I hope this approach is okay.

This should be ready for review now.

2025-01-14 13:56 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12768787503/job/35589922138) [(plain)](https://github.com/rust-lang/rust/commit/8b19670ced51e507697b760975d01022b968b3e6/checks/35589922138/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#22 exporting to docker image format
#22 sending tarball 29.1s done
#22 DONE 35.2s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---


failures:

---- [ui] tests/ui/thread-local/spawned-thread-dtor.rs stdout ----
Saved the actual run.stdout to "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/thread-local/spawned-thread-dtor/spawned-thread-dtor.run.stdout"
Foo dtor




The actual run.stdout differed from the expected run.stdout.

error: 1 errors occurred comparing run output.
status: exit status: 0
command: cd "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/thread-local/spawned-thread-dtor" && RUSTC="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" RUST_TEST_THREADS="16" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/thread-local/spawned-thread-dtor/a"
Foo dtor
------------------------------------------
stderr: none

```

</details>

2025-01-14 14:33 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12769418094/job/35591971914) [(plain)](https://github.com/rust-lang/rust/commit/58220d7249224838a131431072207328d8167bf4/checks/35591971914/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#21 exporting to docker image format
#21 sending tarball 27.6s done
#21 DONE 30.8s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---


failures:

---- [ui] tests/ui/thread-local/spawned-thread-dtor.rs stdout ----
Saved the actual run.stdout to "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/thread-local/spawned-thread-dtor/spawned-thread-dtor.run.stdout"
Foo dtor




The actual run.stdout differed from the expected run.stdout.

error: 1 errors occurred comparing run output.
status: exit status: 0
command: cd "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/thread-local/spawned-thread-dtor" && RUSTC="/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" RUST_TEST_THREADS="16" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/thread-local/spawned-thread-dtor/a"
Foo dtor
------------------------------------------
stderr: none

```

</details>

2025-01-27 08:11 UTC, surban commented
> `atexit` doesn't just get run when main exits, but also when `exit` is called, which might be a bit unexpected.

Note that this is the same behavior as on currently stable Rust on Linux.

```rust
struct Foo;

impl Drop for Foo {
    fn drop(&mut self) {
        println!("wut");
    }
}

thread_local!(static FOO: Foo = Foo);

fn main() {
    FOO.with(|_| {});
    unsafe { libc::exit(0) };
}
```

The program above will print `wut` on `rustc 1.84.0 (9fc6b4312 2025-01-07)` on `x86_64-unknown-linux-gnu` with glibc 2.35.

2025-02-05 17:13 UTC, m-ou-se commented
We briefly discussed this in the libs meeting. We'd like to understand the motivation better. Is this just for consistency? Or are there concrete bugs that are solved by this PR?

2025-02-10 14:12 UTC, surban commented
There are several reasons for this:

- **Consistency**:  
  Currently, TLS destruction on process exit is highly inconsistent—not only across different platforms but even between different glibc versions on Linux. See [this comment](https://github.com/rust-lang/rust/issues/28129#issuecomment-2211739709). This inconsistency complicates testing and may introduce subtle bugs due to unexpected platform differences.

- **Memory Leak Checking**:  
  Some tools report unfreed TLS memory as possibly lost (see [issue #135608](https://github.com/rust-lang/rust/issues/135608)). While this is not a problem for the process itself since it is exiting anyway, it adds noise when debugging memory leaks—especially in scenarios involving unsafe code or linked C libraries. Avoiding such noise would improve the effectiveness of memory leak detection tools.

- **Cross-Platform Exit Handlers**:  
  If TLS destructors were reliably executed on process exit, user code could use them as exit notifications, effectively enabling `atexit`-style callbacks without requiring unsafe or platform-specific code. This would benefit crates like [`tempfile`](https://crates.io/crates/tempfile), allowing them to perform cleanup even when local destructors are not executed (e.g., when `std::process::exit` is called).

## Alternative: Never Run TLS Destructors

An alternative approach would be to *never* run TLS destructors on process exit. While this is not my preferred solution due to the reasons mentioned above, it would at least provide consistency and be easy to implement. This approach would also align with the behavior of `static` items.

2025-02-10 14:13 UTC, surban commented
@rustbot ready

2025-02-12 21:29 UTC, the8472 commented
We discussed this again during today's libs meeting. Opinions were mixed, leaning towards close. The following issues were raised during the discussion:

- using TLS destructors as an exit handler is misguided because they would only run for the thread calling exit, other threads wouldn't get the desired cleanup behavior. So they should use `atexit` instead.
- consistency may become a burden, e.g. on platforms where atexit does not work reliably or causes other issues

Leak checking wasn't discussed, but from previous issues I have the impression that only limited effort is spent on making leak-checkers happy. Genuine leaks need to be fixed, false positives (quasi-static things) are better handled through exceptions in the leak checker.

@rfcbot fcp close

2025-02-21 07:12 UTC, RalfJung commented on library/std/src/sys/thread_local/exit/unix.rs
> +    // Miri does not support atexit.
Could you file an issue for this in the Miri repo? If std starts using this, we should consider supporting it.

2025-02-21 07:12 UTC, RalfJung commented on library/std/src/sys/thread_local/guard/key.rs
This could use a few more comments, explaining what enable_thread / enable_process are doing. It sounds like they enable a thread/process but that's not quite right I think.

2025-02-21 07:12 UTC, RalfJung commented on library/std/src/sys/thread_local/guard/key.rs
> +/// POSIX systems do not run TLS destructors at process exit.
Are they guaranteed to not run? Or are they just not guaranteed to run? Does the implementation deal gracefully with implementations that run them anyway?

2025-02-21 07:13 UTC, RalfJung commented
Oh never mind, I saw this in the FCP list but the list didn't say that this is "FCP close".

2025-02-23 13:45 UTC, closed without merging