[`generic_assert`] Avoid constant environments
rust-lang/rust pull request #134126
Opened 2024-12-10 13:03 UTC by c410-f3r

cc #44838

This PR is a work in progress. Requesting an early perf run to evaluate possible impacts.

The `generic_assert` feature captures variables for printing purposes.

```rust
fn foo() {
  let elem = 1i32;
  assert!(&elem);
}

# Expansion
fn foo() {
  let elem = 1i32;
  {
    use ::core::asserting::{TryCaptureGeneric, TryCapturePrintable};
    let mut __capture0 = ::core::asserting::Capture::new();
    let __local_bind0 = &elem;
    if (!&*__local_bind0) {
        (&::core::asserting::Wrapper(__local_bind0)).try_capture(&mut __capture0);
        {
          ::std::rt::panic_fmt(format_args!("Assertion failed: &elem\nWith captures:\n  elem = {0:?}\n", __capture0));
        }
      }
  };
}
```

The problem is that such a thing is complicated in constant environments. At the current time only strings are allowed and a full support parity with non-constant environments is not, as far as I can tell, in the foreseen future.

```rust
fn foo() {
  // !!! ERROR !!!
  const {
    let elem = 1i32;
    assert!(&elem);
  }
}
```

Therefore, `generic_assert` will not be triggered in constant environment through an `is_in_const_env` variable flag created in the `rustc_parse` crate.

2024-12-10 13:03 UTC, clubby789 commented
@bors try @rust-timer queue

2024-12-10 13:03 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2024-12-10 13:25 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12256680478/job/34192489380) [(plain)](https://github.com/rust-lang/rust/commit/01b8e1bfe90357f7d6ec83798827f715ee7970f3/checks/34192489380/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 exporting to docker image format
#16 sending tarball 27.9s done
#16 DONE 40.6s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
##[endgroup]
##[group]Testing stage2 compiletest suite=crashes mode=crashes (x86_64-unknown-linux-gnu)

running 203 tests
....................................................................................2024-12-10T13:25:31.318339Z ERROR compiletest::runtest: fatal error, panic: "crashtest no longer crashes/triggers ICE, horray! Please give it a meaningful name, add a doc-comment to the start of the test explaining why it exists and move it to tests/ui or wherever you see fit. Adding 'Fixes #<issueNr>' to your PR description ensures that the corresponding ticket is auto-closed upon merge. If you want to see verbose output, set `COMPILETEST_VERBOSE_CRASHES=1`."
[crashes] tests/crashes/123629.rs ... F
...  88/203
........................................................................................ 176/203
..........................Some tests failed in compiletest suite=crashes mode=crashes host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
..........................Some tests failed in compiletest suite=crashes mode=crashes host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
.

failures:

---- [crashes] tests/crashes/123629.rs stdout ----

error: crashtest no longer crashes/triggers ICE, horray! Please give it a meaningful name, add a doc-comment to the start of the test explaining why it exists and move it to tests/ui or wherever you see fit. Adding 'Fixes #<issueNr>' to your PR description ensures that the corresponding ticket is auto-closed upon merge. If you want to see verbose output, set `COMPILETEST_VERBOSE_CRASHES=1`.
thread '[crashes] tests/crashes/123629.rs' panicked at src/tools/compiletest/src/runtest/crashes.rs:17:18:
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
```

</details>

2024-12-10 14:16 UTC, fmease requested changes

2024-12-10 14:16 UTC, fmease commented on compiler/rustc_parse/src/parser/mod.rs
I'm pretty sure this doesn't account for nested non-const items. For example:

```rs
// false positive: `assert!(…)` is actually NOT in a const context 
const F: fn() = || { let x = true; assert!(!x); };
fn main() { F() }

// false postive: `assert!(…)` is actually NOT in a const context
const F: fn() = { fn f() { let x = true; assert!(!x); } f };
fn main() { F() }

// false positive: `assert!(…)` is actually NOT in a const context
const fn f() -> fn() { fn g() { let x = true; assert!(!x); } g }
fn main() { f()() }

// false positive (low priority, not "exploitable" atm): `assert!(…)` is actually NOT in a const context
struct Ty<const N: u8>;
fn main() { _ = Ty::<{ fn _f() { let x = true; assert!(!x) } 0 }>; }
```

Other issues:

```rs
// false negative (you missed `parse_static_item`, trivial): `assert!(…)` is actually in a const context
static X: () = { let x = true; assert!(!x) };
```

2024-12-10 14:23 UTC, fmease commented on compiler/rustc_parse/src/parser/mod.rs
I don't think the parser is the right place for this.

For example, you would never be able to catch this in the parser I believe:

```rs
#![feature(const_trait_impl)]
#[cfg_attr(SOME_CFG_SPEC, const_trait)]
trait Trait { fn f() { let x = true; assert!(!x); } }
```

2024-12-10 14:27 UTC, fmease commented on compiler/rustc_parse/src/parser/mod.rs
Does your current approach catch this (it might actually, I'm not sure rn)?

```rs
macro_rules! constify { ($expr:expr) => { const { $expr } } }

fn main() {
    constify! {{ let x = false; assert!(!x); }}
}
```

2024-12-10 22:12 UTC, c410-f3r commented on compiler/rustc_parse/src/parser/mod.rs
Thank you for the review, @fmease.

I also share your concerns about uncovered use-cases as well as possible edge-cases. If somehow it were possible to call something like the `is_inside_const_context` method defined in HIR things would be much easier.

The feeling of thinking that the parser is probably not the right place is also shared, unfortunately, I am not aware of any other alternative.

So the plan is to cover as many cases as possible (your snippets certainly help in that direction), do a crater run and hope for the best. Without a plan to avoid constant environments, I think `generic_assert` will remain unstable for a long time.

2024-12-11 13:06 UTC, fmease commented
Swallowed by the force push

@bors try @rust-timer queue

2024-12-11 13:06 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

<!-- rust-timer: temporary -->

2024-12-11 14:52 UTC, rust-timer commented
Queued 31287601fc50a566bb7663710d746c26b2fb00e5 with parent 5a6036a1802262f8cf02192b02026688d396f1d7, future [comparison URL](https://perf.rust-lang.org/compare.html?start=5a6036a1802262f8cf02192b02026688d396f1d7&end=31287601fc50a566bb7663710d746c26b2fb00e5).
There is currently 1 preceding artifact in the [queue](https://perf.rust-lang.org/status.html).
It will probably take at least ~1.4 hours until the benchmark run finishes.
<!-- rust-timer: temporary -->

2024-12-11 16:16 UTC, rust-timer commented
Finished benchmarking commit (31287601fc50a566bb7663710d746c26b2fb00e5): [comparison URL](https://perf.rust-lang.org/compare.html?start=5a6036a1802262f8cf02192b02026688d396f1d7&end=31287601fc50a566bb7663710d746c26b2fb00e5&stat=instructions:u).

### Overall result: ❌ regressions - no action needed


Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

@bors rollup=never
@rustbot label: -S-waiting-on-perf -perf-regression


### [Instruction count](https://perf.rust-lang.org/compare.html?start=5a6036a1802262f8cf02192b02026688d396f1d7&end=31287601fc50a566bb7663710d746c26b2fb00e5&stat=instructions:u)
This is the most reliable metric that we have; it was used to determine the overall result at the top of this comment. However, even this metric can sometimes exhibit noise.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 0.3% | [0.3%, 0.3%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=5a6036a1802262f8cf02192b02026688d396f1d7&end=31287601fc50a566bb7663710d746c26b2fb00e5&stat=max-rss)
<details>
<summary>Results (primary 2.4%, secondary -0.1%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 2.4%  | [1.7%, 3.4%]   | 3     |
| Regressions ❌ <br /> (secondary)  | 3.2%  | [1.9%, 4.4%]   | 2     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -3.4% | [-4.7%, -2.0%] | 2     |
| All ❌✅ (primary)                 | 2.4%  | [1.7%, 3.4%]   | 3     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=5a6036a1802262f8cf02192b02026688d396f1d7&end=31287601fc50a566bb7663710d746c26b2fb00e5&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=5a6036a1802262f8cf02192b02026688d396f1d7&end=31287601fc50a566bb7663710d746c26b2fb00e5&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 767.862s -> 767.206s (-0.09%)
**Artifact size**: 331.04 MiB -> 330.97 MiB (-0.02%)

2024-12-11 16:30 UTC, c410-f3r commented
Thank you @fmease. Looks like the additional size of the `Parse` structure didn't create a significant performance impact

2024-12-11 17:27 UTC, c410-f3r commented
I will hopefully come back with a reasonable set of tests

2024-12-11 17:27 UTC, closed without merging