remove weird countervariant
rust-lang/rust pull request #134237
Opened 2024-12-12 22:00 UTC by dev-ardi

I'm not sure what purpose this `PhantomData<fn(&I)>` has, it looks like it wants a countervariant for some reason but... why? It's confusing, does it have any purpose? If it does not let's just remove it.

2024-12-12 22:54 UTC, compiler-errors requested changes
Did you actually try looking at the PR that introduced it? You tried to change this a year ago with no justification, and there's still no justification other than you not understanding why it's there: https://github.com/rust-lang/rust/pull/119800/commits/1bf3aee3811b92d5833154fd35b98159a233b938#r1447618595

I'm fairly certain that changing `PhantomData<fn(&I)>` to `PhantomData<I>` changes the implications of the type w.r.t. drop, and obviously changes the variance of the `I` parameter.

I don't believe that this should be changed for literally no reason.

2024-12-12 23:16 UTC, dev-ardi commented
> Did you actually try looking at the PR that introduced it?

do you mean this one? https://github.com/rust-lang/rust/pull/34149 I don't see anywhere explained why they went with that.

> You tried to change this a year ago with no justification, and there's still no justification other than you not understanding why it's there
> I'm fairly certain that changing PhantomData<fn(&I)> to PhantomData<I> changes the implications of the type w.r.t. drop

I did not understand it then, I don't understand it now that I know more and it's been somewhere in the back of my mind since.
Yes, that subtlety implies that it wants a difference in those aspects, what or why is unknown to me, or what invariant about the type it's asserting. Its existance implies that it must exist for some reason.
At least it should be documented since it's kinda weird.

2024-12-12 23:45 UTC, fmease commented
It's a pretty common pattern to make map-like type constructors contravariant in the key type parameter. Apart from being conventional (across all languages that feature contravariance), it can be convenient at times (it probably tends towards the rarer side in practice).

The "academic" answer: Maps of type `HashMap`, `BTreeMap`, `IndexVec`, etc. are conceptually functions of type `fn(&K) -> V`, functions mapping keys to values. Since function type constructors are contravariant in their argument types (arguments are *consumed*, not *produced*), it only makes sense that other map-likes follow suit.

In more "practical" terms, it permits you to for example treat `IndexVec<&'a str, V>` for all lifetimes `'a` as `IndexVec<&'static str, V>`. You can "lifetime-extend" the key type. I couldn't come up with a more concrete use-case for this, sorry. It's more of a "when you need/want it, you need/have it" situation.

2024-12-12 23:48 UTC, fmease commented
Regarding, `PhantomData<fn(I)>` vs `PhantomData<fn(&I)>` the answer is indeed *dropck*. However, I'm not actually sure if it still has an effect. CC https://doc.rust-lang.org/nomicon/phantom-data.html#generic-parameters-and-drop-checking

2024-12-13 04:53 UTC, jieyouxu commented
idk so i guess r? compiler-errors

2024-12-16 18:47 UTC, dev-ardi commented
I suggest the following:
- If this is actually needed for something let's add a comment explaining it
- If not let's simplify it.

2025-01-23 15:57 UTC, BoxyUwU commented
I'm going to close this, it's been explained why preferring `PhantomData<fn(&I)>` over `PhantomData<I>` makes sense. If you would like to document this rationale then feel free to update this PR otherwise I don't think there's any value keeping this open as I do not believe anyone in this thread as expressed a desire to merge this as-is

2025-01-23 15:57 UTC, closed without merging