more concrete source url of std docs [V2]
rust-lang/rust pull request #134241
Opened 2024-12-13 03:56 UTC by liigo

r? jhpratt
since you have reivewed https://github.com/rust-lang/rust/pull/134193

> If someone is looking to contribute, they will want the repository as a whole, not the lib.rs for std.

Now the repository url is reserved, I just add another concrete url as an example, to help people finding target page more quickly&easily.

2024-12-13 06:01 UTC, jhpratt commented
Genuine question — what's the goal here? I don't find the existing link confusing at all.

2024-12-13 08:48 UTC, liigo commented
to help people finding target page more quickly & easily.

2024-12-13 09:05 UTC, jhpratt commented
I find it's quite obvious, as it's in the top-level `library` directory followed by whatever crate you are working with. However, I've also been contributing for years. I don't personally feel inclined to have _any_ change here, but I'll leave the final decision to someone else.

r? libs-api

2024-12-26 23:49 UTC, dtolnay requested changes

2024-12-26 23:49 UTC, dtolnay commented on library/std/src/lib.rs
> +//！(e.g. [here](https://github.com/rust-lang/rust/blob/master/library/std/src/lib.rs)).
The character that you put here is a Unicode "Fullwidth Exclamation Mark", which is not an ASCII exclamation mark. So this line would not be treated as documentation by rustdoc. It is just a comment.

https://www.compart.com/en/unicode/U+FF01

![image](https://github.com/user-attachments/assets/37c64868-9d99-42d6-b16d-cd57b8a0ffed)

![image](https://github.com/user-attachments/assets/1bae725d-d8f3-41c4-b64c-0864d673b31c)

2024-12-26 23:52 UTC, dtolnay commented
IMO the original wording and link are fine as is.

I would accept something like: *The source for this documentation can be found on [GitHub](https://github.com/rust-lang/rust) in the 'library/std/' directory.*

2025-01-02 14:32 UTC, liigo commented
r? dtolnay

2025-01-02 14:35 UTC, liigo commented
@dtolnay 
> I would accept something like: _The source for this documentation can be found on [GitHub](https://github.com/rust-lang/rust) in the 'library/std/' directory._

Done.

2025-01-02 21:15 UTC, dtolnay approved these changes
Thanks!

2025-01-02 21:15 UTC, dtolnay commented
@bors r+ rollup

2025-01-03 12:17 UTC, merged