Fix logical error with what text is considered whitespace.
rust-lang/rust pull request #134366
Opened 2024-12-16 02:37 UTC by harrisonkaiser

There is a logical issue around what counts as leading white-space. There is code which does a subtraction assuming that no errors will be reported inside the leading whitespace. However we compute the length of that whitespace with std::char::is_whitespace and not rustc_lexer::is_whitespace. The former will include a no-break space while later will excluded it. We can only safely make the assumption that no errors will be reported  in whitespace if it is all "Rust Standard" whitespace. Indeed an error does occur in unicode whitespace if it contains a no-break space.

2024-12-16 02:37 UTC, harrisonkaiser commented
Addresses: https://github.com/rust-lang/rust/issues/132918#issuecomment-2544413808

2024-12-16 09:50 UTC, jieyouxu requested changes
Thanks for the PR. We'll need to add a regression test for #132918 to prevent it from happening again in the future. Note that the test probably will need to be marked with

```
//@ needs-rustc-debug-assertions
```

to catch the overflow assertion that only happens if rustc was built with debug assertions.

Might also need to artificially constrain diagnostics width with something like

```
//@ compile-flags: --diagnostics-width=80
```

to prevent terminal size from interfering with test outcome. I'm not super familiar with what the logic here is intended to do, so I'm going to reroll a WG-diagnostics reviewer.

2024-12-16 09:50 UTC, jieyouxu commented on compiler/rustc_errors/src/emitter.rs
> +                        if source_string.chars().any(|c| rustc_lexer::is_whitespace(c)) {
Question: doesn't this flip the logic?

2024-12-16 09:51 UTC, jieyouxu commented
r? diagnostics

2024-12-17 03:07 UTC, harrisonkaiser commented on compiler/rustc_errors/src/emitter.rs
> +                        if source_string.chars().any(|c| rustc_lexer::is_whitespace(c)) {
Yes. This is a typo.

2024-12-17 04:38 UTC, harrisonkaiser commented
Thank you for the prompt response and guidance on adding a compilation tests.

I've fixed the typo and added a test case and confirmed that it doesn't pass on master and does pass on this branch.

2024-12-17 05:06 UTC, harrisonkaiser commented
> There are merge commits (commits with multiple parents) in your changes. We have a [no merge policy](https://rustc-dev-guide.rust-lang.org/git.html#no-merge-policy) so these commits will need to be removed for this pull request to be merged.
> 
> You can start a rebase with the following commands:
> 
> ```
> $ # rebase
> $ git pull --rebase https://github.com/rust-lang/rust.git master
> $ git push --force-with-lease
> ```
> 
> The following commits are merge commits:
> 
>     * [2d0fc53](https://github.com/rust-lang/rust/commit/2d0fc531141a6f1f4e395db464a81e5d06ec215f)

Whoops, fixed.

2024-12-17 07:37 UTC, harrisonkaiser commented
I noticed also that `is_whitespace` is also called here: (https://github.com/rust-lang/rust/blob/1e33dd17115ca948c6e5ebf319695ed64490b2bf/compiler/rustc_errors/src/emitter.rs#L789), and I'm don't know if that should also be `rustc_lexer::is_whitespace`. I figured I'd stick to the failure case I could re-produce.

2024-12-18 20:58 UTC, harrisonkaiser commented
@rustbot review

2024-12-20 11:32 UTC, davidtwco approved these changes

2024-12-20 11:34 UTC, davidtwco commented
> I noticed also that `is_whitespace` is also called here: (
> 
> https://github.com/rust-lang/rust/blob/1e33dd17115ca948c6e5ebf319695ed64490b2bf/compiler/rustc_errors/src/emitter.rs#L789
> 
> ), and I'm don't know if that should also be `rustc_lexer::is_whitespace`. I figured I'd stick to the failure case I could re-produce.

I'd be happy to see this changed to `rustc_lexer::is_whitespace`, it's probably better to be consistent. But that can be a follow-up so this can land quicker.

@bors r+ rollup

2024-12-20 17:58 UTC, merged