Split up attribute parsing code and move data types to `rustc_attr_data_structures`
rust-lang/rust pull request #134381
Opened 2024-12-16 11:27 UTC by jdonszelmann

This change renames `rustc_attr` to `rustc_attr_parsing`, and splits up the parsing code. At the same time, all the data types used move to `rustc_attr_data_structures`. This is in preparation of also having a third crate: `rustc_attr_validation`

I initially envisioned this as two separate PRs, but I think doing it in one go reduces the number of ways others would have to rebase their changes on this. However, I can still split them.

r? @oli-obk (we already discussed how this is a first step in a larger plan)

For a more detailed plan on how attributes are going to change, see https://github.com/rust-lang/rust/issues/131229

2024-12-16 11:29 UTC, jdonszelmann commented
@rustbot label +A-attributes

For the rustdoc changes, I only made that code depend on `rustc_attr_parsing` instead of `rustc_attr`. No actual logic changed.

2024-12-16 11:37 UTC, jdonszelmann commented
well, my last rebase had no conflicts, but clearly it didn't work very well anyway...

2024-12-16 11:54 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12351930221/job/34467911660) [(plain)](https://github.com/rust-lang/rust/commit/ff646ad78e6c1491f5fc403abe59811d5e655992/checks/34467911660/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#13 2.788 Building wheels for collected packages: reuse
#13 2.789   Building wheel for reuse (pyproject.toml): started
#13 3.041   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 3.042   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132720 sha256=026f3bb0f1aa8090b861fd0a0939cb1a782396d84c8aab7875096557d637a0f6
#13 3.042   Stored in directory: /tmp/pip-ephem-wheel-cache-1qk6ruya/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#13 3.045 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#13 3.449 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#13 3.449 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 3.981 Collecting virtualenv
#13 3.981 Collecting virtualenv
#13 4.022   Downloading virtualenv-20.28.0-py3-none-any.whl (4.3 MB)
#13 4.095      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 60.6 MB/s eta 0:00:00
#13 4.134 Collecting distlib<1,>=0.3.7
#13 4.137   Downloading distlib-0.3.9-py2.py3-none-any.whl (468 kB)
#13 4.146      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 67.5 MB/s eta 0:00:00
#13 4.183 Collecting filelock<4,>=3.12.2
#13 4.186   Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
#13 4.219 Collecting platformdirs<5,>=3.9.1
#13 4.223   Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
#13 4.307 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 4.503 Successfully installed distlib-0.3.9 filelock-3.16.1 platformdirs-4.3.6 virtualenv-20.28.0
#13 DONE 4.6s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      323520 kB
DirectMap2M:     7016448 kB
DirectMap1G:    11534336 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.05s
##[endgroup]
WARN: currently no CI rustc builds have rustc debug assertions enabled. Please either set `rust.debug-assertions` to `false` if you want to use download CI rustc or set `rust.download-rustc` to `false`.
downloading https://static.rust-lang.org/dist/2024-11-27/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz
---
##[endgroup]
fmt check
Diff in /checkout/compiler/rustc_attr_data_structures/src/lib.rs:1:
-
 // tidy-alphabetical-start
 #![allow(internal_features)]
 #![doc(rust_logo)]
fmt error: Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/compiler/rustc_attr_data_structures/src/attributes.rs" "/checkout/compiler/rustc_attr_data_structures/src/version.rs" "/checkout/compiler/rustc_attr_data_structures/src/lib.rs" "/checkout/tests/run-make/remove-dir-all-race/rmake.rs" "/checkout/tests/run-make/rustdoc-error-lines/input.rs" "/checkout/tests/run-make/rustdoc-error-lines/rmake.rs" "/checkout/compiler/rustc_serialize/tests/leb128.rs" "/checkout/compiler/rustc_serialize/tests/opaque.rs" "/checkout/compiler/rustc_serialize/src/leb128.rs" "/checkout/compiler/rustc_serialize/src/opaque.rs" "/checkout/compiler/rustc_serialize/src/int_overflow.rs" "/checkout/compiler/rustc_serialize/src/serialize.rs" "/checkout/compiler/rustc_serialize/src/lib.rs" "/checkout/tests/run-make/mte-ffi/foo_string.rs" "/checkout/tests/run-make/mte-ffi/foo_float.rs" "/checkout/tests/run-make/mte-ffi/rmake.rs" "/checkout/tests/run-make/mte-ffi/foo_int.rs" "/checkout/tests/run-make/mte-ffi/foo_function.rs" "/checkout/tests/run-make/archive-duplicate-names/foo.rs" "/checkout/tests/run-make/archive-duplicate-names/bar.rs" "/checkout/tests/run-make/archive-duplicate-names/rmake.rs" "/checkout/tests/run-make/include-bytes-deps/main.rs" "/checkout/tests/run-make/include-bytes-deps/rmake.rs" "/checkout/tests/run-make/native-lib-alt-naming/rust.rs" "/checkout/tests/run-make/native-lib-alt-naming/rmake.rs" "/checkout/tests/run-make/native-lib-alt-naming/native.rs" "/checkout/tests/run-make/macos-fat-archive/rmake.rs" "/checkout/tests/run-make/macos-fat-archive/lib.rs" "/checkout/compiler/rustc_parse/src/parser/mut_visit/tests.rs" "/checkout/compiler/rustc_parse/src/parser/nonterminal.rs" "/checkout/compiler/rustc_parse/src/parser/pat.rs" "/checkout/compiler/rustc_parse/src/parser/item.rs" "/checkout/compiler/rustc_parse/src/parser/stmt.rs" "/checkout/compiler/rustc_parse/src/parser/generics.rs" "/checkout/compiler/rustc_parse/src/parser/diagnostics.rs" "/checkout/compiler/rustc_parse/src/parser/ty.rs" "/checkout/compiler/rustc_parse/src/parser/attr_wrapper.rs" "/checkout/compiler/rustc_parse/src/parser/tokenstream/tests.rs" "/checkout/compiler/rustc_parse/src/parser/tests.rs" "/checkout/compiler/rustc_parse/src/parser/path.rs" "/checkout/compiler/rustc_parse/src/parser/mod.rs" "/checkout/compiler/rustc_parse/src/parser/expr.rs" "/checkout/compiler/rustc_parse/src/parser/attr.rs" "/checkout/tests/run-make/emit-to-stdout/test.rs" "/checkout/tests/run-make/emit-to-stdout/rmake.rs" "/checkout/tests/run-make/rust-lld-by-default-nightly/main.rs" "/checkout/tests/run-make/rust-lld-by-default-nightly/rmake.rs" "/checkout/compiler/rustc_parse/src/lexer/unicode_chars.rs" "/checkout/compiler/rustc_parse/src/lexer/unescape_error_reporting.rs" "/checkout/compiler/rustc_parse/src/lexer/diagnostics.rs" "/checkout/compiler/rustc_parse/src/lexer/tokentrees.rs" "/checkout/compiler/rustc_parse/src/lexer/mod.rs" "/checkout/compiler/rustc_parse/src/errors.rs" "/checkout/compiler/rustc_parse/src/validate_attr.rs" "/checkout/compiler/rustc_parse/src/lib.rs" "/checkout/tests/run-make/optimization-remarks-dir/foo.rs" "/checkout/tests/run-make/optimization-remarks-dir/rmake.rs" "/checkout/compiler/rustc_error_messages/src/lib.rs" "/checkout/tests/run-make/rustdoc-scrape-examples-test/rmake.rs" "/checkout/tests/run-make/rustdoc-scrape-examples-test/src/lib.rs" "/checkout/tests/run-make/rustdoc-scrape-examples-test/examples/ex.rs" "/checkout/tests/run-make/rustc-help/rmake.rs" "/checkout/tests/run-make/ice-static-mir/foo.rs" "/checkout/compiler/rustc_attr_data_structures/src/stability.rs"` failed.
If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
  local time: Mon Dec 16 11:53:49 UTC 2024
  network time: Mon, 16 Dec 2024 11:53:49 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-12-16 16:12 UTC, oli-obk requested changes

2024-12-16 16:12 UTC, oli-obk commented on a.out
accidentally committed a test file

2024-12-16 16:12 UTC, oli-obk commented on a.out
(even though it was removed in the second commit)

2024-12-16 16:13 UTC, oli-obk commented
I reviewed some changes and the overall change. I'm just gonna assume all the individual parts have been moved correctly (as no tests have been touched, and the downstream usages are all just import changes, this appears so)

@bors delegate+

r=me with the nit for a clean history

2024-12-16 18:06 UTC, jdonszelmann commented on a.out
oops, yea I noticed but should've removed it from the first one haha

2024-12-16 19:31 UTC, jdonszelmann commented
@bors r=@oli-obk

2024-12-17 16:01 UTC, jieyouxu commented
@bors p=6 (conflict-prone)

2024-12-17 16:02 UTC, jieyouxu commented
(conflict-check)

2024-12-17 16:03 UTC, jieyouxu commented
@bors r=@oli-obk

2024-12-17 20:08 UTC, jdonszelmann commented
(I'll see if the next few can be less conflict prone lol)

2024-12-17 21:32 UTC, merged

2024-12-17 23:54 UTC, rust-timer commented
Finished benchmarking commit (a4cb3c831823d9baa56c3d90514b75b2660116fa): [comparison URL](https://perf.rust-lang.org/compare.html?start=1d35638dc38dbfbf1cc2a9823135dfcf3c650169&end=a4cb3c831823d9baa56c3d90514b75b2660116fa&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=1d35638dc38dbfbf1cc2a9823135dfcf3c650169&end=a4cb3c831823d9baa56c3d90514b75b2660116fa&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=1d35638dc38dbfbf1cc2a9823135dfcf3c650169&end=a4cb3c831823d9baa56c3d90514b75b2660116fa&stat=max-rss)
This benchmark run did not return any relevant results for this metric.

### [Cycles](https://perf.rust-lang.org/compare.html?start=1d35638dc38dbfbf1cc2a9823135dfcf3c650169&end=a4cb3c831823d9baa56c3d90514b75b2660116fa&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=1d35638dc38dbfbf1cc2a9823135dfcf3c650169&end=a4cb3c831823d9baa56c3d90514b75b2660116fa&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 770.505s -> 769.242s (-0.16%)
**Artifact size**: 330.30 MiB -> 330.31 MiB (0.00%)