lint / ImproperCTypes: better handling of indirections, take 2
rust-lang/rust pull request #134697
Opened 2024-12-23 17:59 UTC by niacdoial

This PR tries to re-add the changes in #131669 (which were reverted in #134064 after one (1) nightly),
and adds better coverage of ty_kinds:
- in the take-1-added TypeSizedness enum and its construction
- in a new test file

The changes in the original PR aim to make ImproperCTypes/ImproperCTypesDefinitions produce better warnings when dealing with indirections (Box<T>, &T, *T), especially for those to DSTs.

r? workingjubilee (because you reviewed the first attempt)

2024-12-23 18:03 UTC, niacdoial commented
(
  hi Jubilee, I'm back at this again!
  I know this is not the best time of year to add PRs, so I'm fine with postponing this if you don't feel like tackling it these upcoming weeks.
  In any case, have some nice end-of-year festivities, if you celebrate any!
)

2024-12-23 18:08 UTC, niacdoial commented
ah, and before I forget: a small part of the new test file is commented out because it hits ICE #134587, but there should be more than decent coverage anyway

2024-12-24 09:16 UTC, workingjubilee commented
unfortunately the lint needs to be gutted and rewritten.

2024-12-24 09:18 UTC, workingjubilee commented
Also while I was possibly having a mild case of [get-there-itis](https://en.wiktionary.org/wiki/get-there-itis) and thus mostly tried to just make sure things were coherent, I would prefer all new code be in `rustc_lint/src/types/improper_ctypes.rs`.

2025-01-04 18:24 UTC, workingjubilee commented
The version cut happened so there will be less time pressure now.

2025-01-05 00:29 UTC, niacdoial commented
I have a first version for `compiler/rustc_lint/src/types/improper_ctypes.rs` if you want.
it's less of a from-the-ground-up rewrite as it is scrapping the original for parts, if the analogy makes sense.

you probably have things to say about its architecture, even if the whole thing still have a bunch of TODO comments
the progress so far looks like this:

- [X] completely separate the type-checking and reporting systems
- [ ] (part of the way there) remove some of the special cases and integrate them to the "main logic"
  - check_for_opaque_types is still a "special case" part of the checking logic
  - Cstr and Cstring are also somewhat special-cased because the advice for them depends on the type around them, if any
  - the unit type is handled in multiple places, see if this can be fixed
- [ ] (almost complete) compile, pass existing tests
  - only failed tests are for Cstring, due to different error messages
  - one unrelated test had to have a second "#[allow(improper_ctypes)]" added, but it makes more sense for it to need that anyway
- [X] better separation of the different checks in different `visit_*` methods of `ImproperCTypesVisitor`
- [X] better tracking of how the currently-checked type is used (static, function argument, function return's inner type, etc...)
  - raises questions about the separation of improper_ctypes and improper_ctypes_definitions versus declared/defined functions, especially when FnPtr:s are involved
- [ ] allow single argument check to emit multiple errors (for fnptr:s, structures with multiple FFI-unsafe fields, etc)
- [ ] review what is considered FFI-safe or not (once everything else is complete)

If you want to take a look in this state, should I just commit it here? (possibly put the PR in draft mode while I'm at it?)
or send you the files in a different way?

2025-01-18 20:20 UTC, niacdoial commented
aaaand I think I have something that's "first draft" material!
There's still a bunch of ~~TODOs~~ (...well, they were changed to FIXMEs to be pushed here) for questions I didn't manage to answer (and a bunch of failing tests because I don't know if the error should be here), but yeah.


here's a list of some of my remaining questions and concerns:
- visit_numeric seems too x86_64-specific
- should we revisit the distinction between ImproperCTypes and ImproperCTypesDefinitions?
  - part 1: the output ("external fn" or vs "external block" vs other possibilities)
  - part 2: handling opaque types (there's a high correlation between ImproperCTypesDefinitions and places where we allow FFI-opaque types to be fully specified. do we want this correlation to be 1?)

- more on FFI-opaque types: how do we handle that in the context of the "context switch" between functions and possible FnPtr arguments? The answer that seems correct currently prevents a stage1 compiler from being built
    - should we introduce a `std::ffi::FfiOpaquePtr` type? (which would be a *const c_void and some phantomdata, on first approximation)
- for indirections whose values may be supplied by non-rust code: do we only allow pointers (and Option<std::ptr::NonNull>), or do we also allow `Option<&T>` and `Option<Box<T>>`?
- not sure if the new error messages are intelligible in all cases (especially if there's a type param like `Self` or `<Self as ::std::ops::Add<Self>>::Output` that gets resolved in the error message).
- it feels like the current handling of `CStr`/`Cstring` and Option-like enums uses special casing, since those are tested for in multiple places.
- if we deny references and boxes in defined functions, what of `&self` in methods? We don't allow `*const Self`, last I checked.

2025-01-18 20:30 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12847139851/job/35823114550) [(plain)](https://github.com/rust-lang/rust/commit/6c19cffc4a9c78029aafaec26370051fd71ff303/checks/35823114550/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling time-core v0.1.2
   Compiling time-macros v0.2.19
   Compiling deranged v0.3.11
   Compiling rustc-main v0.0.0 (/checkout/compiler/rustc)
error: `extern` fn uses type `&RustString`, which is not FFI-safe
   |
68 |     buf: &RustString,
   |          ^^^^^^^^^^^ not FFI-safe
   |
```

</details>

2025-01-28 23:44 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/13021541943/job/36323060019) [(plain)](https://github.com/rust-lang/rust/commit/13720e7eec5188631618ab15aac8144ae2cf3a8a/checks/36323060019/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling num-conv v0.1.0
   Compiling powerfmt v0.2.0
   Compiling time-core v0.1.2
   Compiling nu-ansi-term v0.50.1
error: `extern` fn uses type `&RustString`, which is not FFI-safe
   |
68 |     buf: &RustString,
   |          ^^^^^^^^^^^ not FFI-safe
   |
```

</details>

2025-01-31 05:14 UTC, workingjubilee commented
hmm.

2025-01-31 05:15 UTC, workingjubilee commented
> aaaand I think I have something that's "first draft" material! (should I put this pull in the "draft" state?)

Yes, it's a good marker for "I don't want this merged yet, even if it looks done".

2025-02-20 21:50 UTC, workingjubilee reviewed
some initial nits on a first pass

2025-02-20 21:50 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        }
The following compiles:
```suggestion
        match (self, other) {
            (Self::FfiUnsafe(_), _) => {
                // nothing to do
            }
            (myself, other @ Self::FfiUnsafe(_)) => {
                *myself = other;
            }
            (Self::FfiPhantom(ref ty1), Self::FfiPhantom(ty2)) => {
                println!("whoops, both FfiPhantom: self({:?}) += other({:?})", ty1, ty2);
            }
            (myself @ Self::FfiSafe, other @ Self::FfiPhantom(_)) => {
                *myself = other;
            }
            (_, Self::FfiSafe) => {
                // nothing to do
            }
        }
```

2025-02-20 21:50 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    /// wether the type is used (directly or not) in a static variable
```suggestion
    /// whether the type is used (directly or not) in a static variable
```

2025-02-20 21:50 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    /// wether the type is used (directly or not) in a function, in return position
```suggestion
    /// whether the type is used (directly or not) in a function, in return position
```

2025-02-20 21:50 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    /// in other words, wether or not we allow non-FFI-safe types behind a C pointer,
```suggestion
    /// whether the type is used (directly or not) in a defined function
    /// in other words, whether or not we allow non-FFI-safe types behind a C pointer,
```

2025-02-20 21:50 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    /// wether the value for that type might come from the non-rust side of a FFI boundary
```suggestion
    /// whether the value for that type might come from the non-rust side of a FFI boundary
```

2025-02-20 21:50 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +                        // `type Foo = extern "C" fn(::std::ffi::CStr);`
1. Because unsized function *parameters* are something we may want to support.
2. The code may not be well-formed: as you may have noticed at some point, you get warnings even if you get errors (usually), and this is because we lint even on "bad" code. This is because rustc didn't use to, once upon a time, and it was a bad debugging experience.

2025-02-20 21:50 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +                    // so there's no need to allow Option<pattern_type!(u32 in 1..)>.
oh, I should fix that probably

2025-02-20 21:50 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +/// for a given `extern "ABI"`, tell wether that ABI is *not* considered a FFI boundary
```suggestion
/// for a given `extern "ABI"`, tell whether that ABI is *not* considered a FFI boundary
```

2025-02-20 21:50 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +/// Determine if a type is sized or not, and wether it affects references/pointers/boxes to it
```suggestion
/// Determine if a type is sized or not, and whether it affects references/pointers/boxes to it
```

2025-02-21 07:35 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        ((self as u8) & 0b0010) != 0
```suggestion
        ((self as u8) & (Self::StaticTy as u8) != 0
```

2025-02-21 07:35 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        let ret = ((self as u8) & 0b0100) != 0;
```suggestion
        let ret = ((self as u8) & (Self::ReturnTyInDeclaration as u8)) != 0;
```

2025-02-21 07:35 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        let ret = ((self as u8) & 0b1000) != 0;
etc... please encase the magic numbers.

2025-02-21 07:35 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    /// Checks wether an `extern "ABI" fn` function pointer is indeed FFI-safe to call
```suggestion
    /// Checks whether an `extern "ABI" fn` function pointer is indeed FFI-safe to call
```

2025-02-21 07:35 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +                // wether they are FFI-safe or not does not depend on the indirections involved (&Self, &T, Box<impl Trait>),
Simpler spellcheckers cannot catch this because "wether" is in fact a word (though definitely not the one you meant), and more complex ones are infuriating because they are never quite smart enough to understand when you meant to use a word that way.
```suggestion
                // whether they are FFI-safe or not does not depend on the indirections involved (&Self, &T, Box<impl Trait>),
```

2025-02-21 07:35 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        }
`!` is never a valid argument, but it is a valid return value.

2025-02-27 22:12 UTC, niacdoial commented
alright, sorry for taking a while!

I'm currently planning what changes I'll do in terms of splitting the lint(s)
my current idea is to separate based on the nature of the thing being (presumably) propped up against a FFI boundary
- improper_ctypes: what's definitely an interface to an outside library (extern statics, extern function declarations)
- improper_ctypes_fn_definitions: functions written in rust intended to be exported
- improper_ctypes_callbacks: FnPtr arguments, no matter in what function they are being used
- improper_ctypes_ty_definitions: `repr(C)` structs/enums(/unions)?




> > more on FFI-opaque types: how do we handle that in the context of the "context switch" between functions and possible FnPtr arguments? The answer that seems correct currently prevents a stage1 compiler from being built

> I'm not sure what you mean?

well, this is more or less answered in what I said before that, but my question was about how to deal with "switching" from checking arguments for, say, a function definition, to checking the arguments of a FnPtr argument?
1. should the nature of the lint change?
  (temptative answer: yes)
2. how should FFI-Safe-pointers-to-FFI-Unsafe-pointees work in FnPtr arguments? Should it be the rules for `extern fn` declarations? (throw the lint because one should use `*const c_void`, an extern type declaration, etc...) or the rules for `extern fn` definitions? (allow that, the function's body needs the full type even if it's opaque to the other side of the FFI boundary)
  (temptative answer: it should be the former, but parts of the rustc codebase doesn't follow this rule, so I can't get a stage1 compiler if I make that the rule)

---

> > // you would think that int-range pattern types that exclude 0 would have Option layout optimisation
> > // they don't (see tests/ui/type/pattern_types/range_patterns.stderr)
> > // so there's no need to allow Option<pattern_type!(u32 in 1..)>.

> oh, I should fix that probably

I... maybe? I can't for the life of me find the link to that again but I think I saw a discussion about that and type covariance/contravariance,
where `i32 is 1..` is a subtype of `i32` (well that was under consideration), meaning `fn(Option<i32>)` is a type of `fn(Option<i32 is 1..>)` and it might have impacts on whether there should be an optimisation because of transmutation?

Though you'll definitely know more than me on all the moving parts.
Especially assuming you might have looked at this more in the past week.

---

As for the rest of your advice, I already took all this in!
thanks for shedding light on my code, one nit at a time!

2025-03-02 08:01 UTC, workingjubilee commented
honestly, I think that initially we might be better off just cutting out linting on thin pointers based on their pointees, and then rethinking the justification, and rewriting the lint for, that case, and having it be specifically `improper_ctype_pointees`.

2025-03-02 14:02 UTC, niacdoial commented
this sounds like we might have combinatorics on our hands with that.  (one lint for repr(C) structures, one for pointees within, one for extern function definitions, one for pointees in their arguments, etc.)
still, OK for leaving this for later.

2025-03-03 00:49 UTC, workingjubilee commented
Hm... I *think* it's possible to have a case where a lint fires only when **two** lints are enabled.

2025-03-03 00:52 UTC, workingjubilee commented
...Regardless, I think any reworking should start with scaling as far as possible back to "this is definitely inappropriate" versus "this is trying to catch a pattern that can be used correctly but usually isn't".

And I think that anything that assumes that a C-ABI-compatible pointer with an ABI-incompatible pointee is not merely being used opaquely is an example of the latter, of course.

2025-05-06 23:34 UTC, niacdoial commented
it has been. two months.
er... here, it's what I currently have. it still needs to be rebased on top of the main branch, but if for some reason you wanted to review it early (or if you wanted proof that I didn't just give up), here it is.

I think I made quite a few decisions, but here are the most important ones I remember:
- `repr(C)` on a struct/union/enum is now seen as enough of a signal for the lint to look closer
- the "this type's value can come from the other side of the FFI boundary and might break the nonzero assumption" part is deactivated when linting on FnPtrs (I'm banking on the warning showing up in another place anyway, eventhough there's a specific case where it might not)
- uninhabited types are now linted against in argument position and static variables, and only `!` and empty enums are allowed as uninhabited return types.
- `&self` in methods will be considered just as unsafe as other un-Option'd references, eventhough last I checked `self: Option<&Self>` is not something that compiles

2025-05-10 22:38 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/14949691600/job/41997487847) [(plain)](https://github.com/rust-lang/rust/commit/0e7277ee16823c31b15e4569243e1c664c0e0a4e/checks/41997487847/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling tracing-log v0.2.0
[RUSTC-TIMING] sharded_slab test:false 2.230
   Compiling nu-ansi-term v0.50.1
[RUSTC-TIMING] nu_ansi_term test:false 1.133
error: `extern` fn uses type `&RustString`, which is not FFI-safe
  --> compiler/rustc_llvm/src/lib.rs:67:10
   |
67 |     buf: &RustString,
   |          ^^^^^^^^^^^ not FFI-safe
   |
```

</details>

2025-05-14 20:33 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/15030291996/job/42241049797) [(plain)](https://github.com/rust-lang/rust/commit/466fe486a4067019aea50b68674f3b5f9956a45c/checks/42241049797/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
[RUSTC-TIMING] thorin test:false 4.540
[RUSTC-TIMING] tracing_subscriber test:false 10.235
   Compiling rustc_baked_icu_data v0.0.0 (/checkout/compiler/rustc_baked_icu_data)
[RUSTC-TIMING] rustc_log test:false 1.887
error: `repr(C)` type uses type `DefIndex`, which is not FFI-safe
   --> compiler/rustc_span/src/def_id.rs:229:1
    |
229 | / pub struct DefId {
...   |
237 | |     pub index: DefIndex,
238 | | }
    | |_^ not FFI-safe
    |
    = help: consider adding a `#[repr(C)]` (not `#[repr(C,packed)]`) or `#[repr(transparent)]` attribute to `DefIndex`
    = note: `DefIndex` has unspecified layout
note: the type is defined here
   --> compiler/rustc_span/src/def_id.rs:206:1
    |
206 | // rustc_index::newtype_index! {
207 | ||     /// A DefIndex is an index into the hir-map for a crate, identifying a
208 | ||     /// particular definition. It should really be considered an interned
209 | ||     /// shorthand for a particular DefPath.
210 | ||     #[orderable]
211 | ||     #[debug_format = "DefIndex({})"]
212 | ||     pub struct DefIndex {
    | ||_______________________^
...   |
217 | |  }
    | |__- in this macro invocation
---
    |    ------------------------------------------------------- in this expansion of `rustc_index::newtype_index!`
    = note: `-D improper-ctype-definitions` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(improper_ctype_definitions)]`

error: `repr(C)` type uses type `def_id::CrateNum`, which is not FFI-safe
   --> compiler/rustc_span/src/def_id.rs:229:1
    |
229 | / pub struct DefId {
...   |
237 | |     pub index: DefIndex,
238 | | }
    | |_^ not FFI-safe
    |
    = help: consider adding a `#[repr(C)]` (not `#[repr(C,packed)]`) or `#[repr(transparent)]` attribute to `def_id::CrateNum`
    = note: `def_id::CrateNum` has unspecified layout
note: the type is defined here
   --> compiler/rustc_span/src/def_id.rs:18:1
    |
18  | // rustc_index::newtype_index! {
19  | ||     #[orderable]
20  | ||     #[debug_format = "crate{}"]
21  | ||     pub struct CrateNum {}
    | ||_______________________^
22  | |  }
    | |__- in this macro invocation
    |
   ::: /checkout/compiler/rustc_index_macros/src/lib.rs:38:1
```

</details>

2025-05-20 22:57 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/15149318034/job/42592332862) [(plain)](https://github.com/rust-lang/rust/commit/347d62b96cce660073b5a1648e42543896cf0aab/checks/42592332862/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
[RUSTC-TIMING] rustc_privacy test:false 9.644
[RUSTC-TIMING] rustc_ty_utils test:false 25.640
   Compiling rustc_codegen_llvm v0.0.0 (/checkout/compiler/rustc_codegen_llvm)
   Compiling rustc_mir_transform v0.0.0 (/checkout/compiler/rustc_mir_transform)
error: `extern` block uses type `&llvm::ffi::Value`, which is not FFI-safe
    --> compiler/rustc_codegen_llvm/src/llvm/ffi.rs:1113:10
     |
1113 |     ) -> &'ll Value;
     |          ^^^^^^^^^^ not FFI-safe
     |
```

</details>

2025-05-21 23:10 UTC, niacdoial commented
alright, now the latest commit does (locally) pass tests and build stage2.
(it also did yesterday before that impromptu rebase)
I'll check the previous commits weren't degraded tomorrow, and then I'll make a summary of what is done and what still needs to be done

2025-05-21 23:27 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/15174328229/job/42671514746) [(plain)](https://github.com/rust-lang/rust/commit/80db7434f307e8072cb59e585bf1322a0991e896/checks/42671514746/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#16 2.930 Building wheels for collected packages: reuse
#16 2.931   Building wheel for reuse (pyproject.toml): started
#16 3.148   Building wheel for reuse (pyproject.toml): finished with status 'done'
#16 3.149   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132719 sha256=d2a2565e7037ad3883fb9337653f2e25bbb588534fbef3697286cbc26d1bf634
#16 3.149   Stored in directory: /tmp/pip-ephem-wheel-cache-1icaauqr/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#16 3.151 Successfully built reuse
#16 3.152 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#16 3.554 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#16 3.554 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#16 DONE 3.6s
---
    Checking rustc_mir_transform v0.0.0 (/checkout/compiler/rustc_mir_transform)
error: mutable borrow from immutable input(s)
    --> compiler/rustc_codegen_llvm/src/llvm/ffi.rs:1309:68
     |
1309 |     |wrap pub(crate) fn LLVMCreateBuilderInContext(C: &Context) -> &mut Builder<'_>;
     |                                                                    ^^^^^^^^^^^^^^^^
     |
note: immutable borrow here
    --> compiler/rustc_codegen_llvm/src/llvm/ffi.rs:1309:55
     |
1309 |     |wrap pub(crate) fn LLVMCreateBuilderInContext(C: &Context) -> &mut Builder<'_>;
     |                                                       ^^^^^^^^
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mut_from_ref
     = note: `-D clippy::mut-from-ref` implied by `-D clippy::correctness`
     = help: to override `-D clippy::correctness` add `#[allow(clippy::mut_from_ref)]`

error: mutable borrow from immutable input(s)
    --> compiler/rustc_codegen_llvm/src/llvm/ffi.rs:2569:69
     |
2569 |     |wrap pub(crate) fn LLVMRustArchiveIteratorNew(AR: &Archive) -> &mut ArchiveIterator<'_>;
     |                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^
     |
note: immutable borrow here
    --> compiler/rustc_codegen_llvm/src/llvm/ffi.rs:2569:56
     |
2569 |     |wrap pub(crate) fn LLVMRustArchiveIteratorNew(AR: &Archive) -> &mut ArchiveIterator<'_>;
     |                                                        ^^^^^^^^
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mut_from_ref

error: mutable borrow from immutable input(s)
    --> compiler/rustc_codegen_llvm/src/llvm/ffi.rs:2690:58
     |
2690 |     |wrap pub(crate) fn LLVMRustLinkerNew(M: &Module) -> &mut Linker<'_>;
     |                                                          ^^^^^^^^^^^^^^^
     |
note: immutable borrow here
    --> compiler/rustc_codegen_llvm/src/llvm/ffi.rs:2690:46
     |
2690 |     |wrap pub(crate) fn LLVMRustLinkerNew(M: &Module) -> &mut Linker<'_>;
     |                                              ^^^^^^^
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#mut_from_ref

[RUSTC-TIMING] rustc_codegen_llvm test:false 5.433
error: could not compile `rustc_codegen_llvm` (lib) due to 3 previous errors
```

</details>

2025-05-22 21:41 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-19`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/15196973356/job/42743360506) [(plain)](https://github.com/rust-lang/rust/commit/d4c54dc9614f6b7d2d5c9f0fd1fa5095d728c466/checks/42743360506/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#18 exporting to docker image format
#18 sending tarball 20.4s done
#18 DONE 28.6s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-19]
[CI_JOB_NAME=x86_64-gnu-llvm-19]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Listening on address 127.0.0.1:4226
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-19', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'build.print-step-timings', '--enable-verbose-tests', '--set', 'build.metrics', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--set', 'gcc.download-ci-gcc=true', '--enable-new-symbol-mangling']
configure: build.build          := x86_64-unknown-linux-gnu
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-19/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
test [crashes] tests/crashes/130346.rs ... ok
test [crashes] tests/crashes/130395.rs ... ok
test [crashes] tests/crashes/130524.rs ... ok
test [crashes] tests/crashes/130411.rs ... ok
2025-05-22T21:40:13.124989Z ERROR compiletest::runtest: fatal error, panic: "crashtest no longer crashes/triggers ICE, hooray! Please give it a meaningful name, add a doc-comment to the start of the test explaining why it exists and move it to tests/ui or wherever you see fit. Adding 'Fixes #<issueNr>' to your PR description ensures that the corresponding ticket is auto-closed upon merge. If you want to see verbose output, set `COMPILETEST_VERBOSE_CRASHES=1`."
test [crashes] tests/crashes/130310.rs ... FAILED
test [crashes] tests/crashes/130797.rs ... ok
test [crashes] tests/crashes/130970.rs ... ok
test [crashes] tests/crashes/131292.rs ... ok
test [crashes] tests/crashes/131048.rs ... ok
---
failures:

---- [crashes] tests/crashes/130310.rs stdout ----

error: crashtest no longer crashes/triggers ICE, hooray! Please give it a meaningful name, add a doc-comment to the start of the test explaining why it exists and move it to tests/ui or wherever you see fit. Adding 'Fixes #<issueNr>' to your PR description ensures that the corresponding ticket is auto-closed upon merge. If you want to see verbose output, set `COMPILETEST_VERBOSE_CRASHES=1`.

thread '[crashes] tests/crashes/130310.rs' panicked at src/tools/compiletest/src/runtest/crashes.rs:17:18:
fatal error
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

</details>

2025-05-24 19:11 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/15229972357/job/42836665429) [(plain)](https://github.com/rust-lang/rust/commit/5c27e88aa14baf8698bd61a0ce92d8e103e85593/checks/42836665429/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
tests/ui/ref_option/ref_option.all.fixed ... ok
tests/ui/non_std_lazy_static/non_std_lazy_static_fixable.fixed ... ok

FAILED TEST: tests/ui/boxed_local.rs
command: CLIPPY_CONF_DIR="tests" RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/clippy-driver" "--error-format=json" "--emit=metadata" "-Aunused" "-Ainternal_features" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Dwarnings" "-Ldependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps" "--extern=clippy_config=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/libclippy_config-ed51451f318df95b.rlib" "--extern=clippy_lints=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/libclippy_lints-b7cb526cfdda36e3.rlib" "--extern=clippy_utils=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/libclippy_utils-c2c4ea31f913b142.rlib" "--extern=futures=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/libfutures-5a7156af45221746.rlib" "--extern=if_chain=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/libif_chain-d11c9c2ffe481e38.rlib" "--extern=itertools=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/libitertools-3e76c5e4cf3f0bdf.rlib" "--extern=parking_lot=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/libparking_lot-e095505c7235a9a3.rlib" "--extern=quote=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/libquote-c8178baeef41ae19.rlib" "--extern=regex=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/libregex-cb003e5d2ad3f3b6.rlib" "--extern=serde=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/libserde-a43a28edafb16747.rlib" "--extern=serde_derive=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libserde_derive-9780bbb027e4cda0.so" "--extern=syn=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/libsyn-e6d09ab535c31563.rlib" "--extern=tokio=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/libtokio-51bd107334be98ff.rlib" "-Ldependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/release/deps" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/tests/ui" "tests/ui/boxed_local.rs" "--edition" "2024"

error: actual output differed from expected
Execute `./x test src/tools/clippy --bless` to update `tests/ui/boxed_local.stderr` to the actual output
--- tests/ui/boxed_local.stderr
+++ <stderr output>
 error: local variable doesn't need to be boxed here
   --> tests/ui/boxed_local.rs:40:13
... 23 lines skipped ...
    |                ^
 
-error: aborting due to 4 previous errors
+error: `extern` fn uses type `std::boxed::Box<std::string::String>`, which is not FFI-safe
+  --> tests/ui/boxed_local.rs:174:46
+   |
+LL | pub extern "C" fn do_not_warn_me(_c_pointer: Box<String>) -> () {}
+   |                                              ^^^^^^^^^^^ not FFI-safe
+   |
+   = help: consider using a raw pointer, or wrapping `std::boxed::Box<std::string::String>` in an `Option<_>`
+   = note: boxes, references, and function pointers are assumed to be valid (non-null, non-dangling, aligned) pointers,
+           which cannot be garanteed if their values are produced by non-rust code
+   = note: `-D improper-c-fn-definitions` implied by `-D warnings`
+   = help: to override `-D warnings` add `#[allow(improper_c_fn_definitions)]`
 
+error: `extern` fn uses type `std::boxed::Box<std::string::String>`, which is not FFI-safe
+  --> tests/ui/boxed_local.rs:178:49
+   |
+LL | pub extern fn do_not_warn_me_no_abi(_c_pointer: Box<String>) -> () {}
+   |                                                 ^^^^^^^^^^^ not FFI-safe
+   |
+   = help: consider using a raw pointer, or wrapping `std::boxed::Box<std::string::String>` in an `Option<_>`
+   = note: boxes, references, and function pointers are assumed to be valid (non-null, non-dangling, aligned) pointers,
+           which cannot be garanteed if their values are produced by non-rust code
+
+error: aborting due to 6 previous errors
+

Full unnormalized output:
error: local variable doesn't need to be boxed here
##[error]  --> tests/ui/boxed_local.rs:40:13
   |
LL | fn warn_arg(x: Box<A>) {
   |             ^
   |
   = note: `-D clippy::boxed-local` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::boxed_local)]`

error: local variable doesn't need to be boxed here
##[error]  --> tests/ui/boxed_local.rs:123:12
   |
LL | pub fn new(_needs_name: Box<PeekableSeekable<&()>>) -> () {}
   |            ^^^^^^^^^^^

error: local variable doesn't need to be boxed here
##[error]  --> tests/ui/boxed_local.rs:189:44
   |
LL |         fn default_impl_x(self: Box<Self>, x: Box<u32>) -> u32 {
   |                                            ^

error: local variable doesn't need to be boxed here
##[error]  --> tests/ui/boxed_local.rs:198:16
   |
LL |         fn foo(x: Box<u32>) {}
   |                ^

error: `extern` fn uses type `std::boxed::Box<std::string::String>`, which is not FFI-safe
##[error]  --> tests/ui/boxed_local.rs:174:46
   |
LL | pub extern "C" fn do_not_warn_me(_c_pointer: Box<String>) -> () {}
   |                                              ^^^^^^^^^^^ not FFI-safe
   |
   = help: consider using a raw pointer, or wrapping `std::boxed::Box<std::string::String>` in an `Option<_>`
   = note: boxes, references, and function pointers are assumed to be valid (non-null, non-dangling, aligned) pointers,
           which cannot be garanteed if their values are produced by non-rust code
   = note: `-D improper-c-fn-definitions` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(improper_c_fn_definitions)]`

error: `extern` fn uses type `std::boxed::Box<std::string::String>`, which is not FFI-safe
##[error]  --> tests/ui/boxed_local.rs:178:49
   |
LL | pub extern fn do_not_warn_me_no_abi(_c_pointer: Box<String>) -> () {}
   |                                                 ^^^^^^^^^^^ not FFI-safe
   |
   = help: consider using a raw pointer, or wrapping `std::boxed::Box<std::string::String>` in an `Option<_>`
   = note: boxes, references, and function pointers are assumed to be valid (non-null, non-dangling, aligned) pointers,
           which cannot be garanteed if their values are produced by non-rust code

error: aborting due to 6 previous errors



error: there were 1 unmatched diagnostics
##[error]   --> tests/ui/boxed_local.rs:174:46
    |
174 | pub extern "C" fn do_not_warn_me(_c_pointer: Box<String>) -> () {}
    |                                              ^^^^^^^^^^^ Error[improper_c_fn_definitions]: `extern` fn uses type `std::boxed::Box<std::string::String>`, which is not FFI-safe
    |

error: there were 1 unmatched diagnostics
##[error]   --> tests/ui/boxed_local.rs:178:49
    |
178 | pub extern fn do_not_warn_me_no_abi(_c_pointer: Box<String>) -> () {}
    |                                                 ^^^^^^^^^^^ Error[improper_c_fn_definitions]: `extern` fn uses type `std::boxed::Box<std::string::String>`, which is not FFI-safe
    |

full stderr:
error: local variable doesn't need to be boxed he [...]

2025-05-24 20:43 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/15230564024/job/42837939755) [(plain)](https://github.com/rust-lang/rust/commit/858bf4792d2cea7a1b0281f2499b45b761bb7e4b/checks/42837939755/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
tests/fail/function_calls/exported_symbol_bad_unwind2.rs (revision `definition`) ... ok
tests/fail/function_calls/exported_symbol_bad_unwind2.rs (revision `both`) ... ok

FAILED TEST: tests/fail/function_calls/exported_symbol_wrong_type.rs
command: MIRI_ENV_VAR_TEST="0" MIRI_TEMP="/tmp/miri-uitest-SJqFHV" RUST_BACKTRACE="1" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/miri" "--error-format=json" "--sysroot=/checkout/obj/build/x86_64-unknown-linux-gnu/miri-sysroot" "-Dwarnings" "-Dunused" "-Ainternal_features" "-Zui-testing" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/tmp/miri_ui/0/tests/fail/function_calls" "tests/fail/function_calls/exported_symbol_wrong_type.rs" "--edition" "2021"

error: actual output differed from expected
Execute `./miri test --bless` to update `tests/fail/function_calls/exported_symbol_wrong_type.stderr` to the actual output
--- tests/fail/function_calls/exported_symbol_wrong_type.stderr
+++ <stderr output>
---

error: `attempt to call an exported symbol that is not defined as a function` not found in diagnostics on line 8
##[error] --> tests/fail/function_calls/exported_symbol_wrong_type.rs:8:33
  |
8 |     unsafe { FOO() } //~ ERROR: attempt to call an exported symbol that is not defined as a function
  |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected because of this pattern
  |

error: there were 1 unmatched diagnostics that occurred outside the testfile and had no pattern
    Error: miri cannot be run on programs that fail compilation

error: there were 1 unmatched diagnostics
##[error] --> tests/fail/function_calls/exported_symbol_wrong_type.rs:2:13
  |
2 | static FOO: () = ();
  |             ^^ Error[improper_c_var_definitions]: foreign-code-reachable static uses type `()`, which is not FFI-safe
  |

full stderr:
error: foreign-code-reachable static uses type `()`, which is not FFI-safe
##[error]  --> tests/fail/function_calls/exported_symbol_wrong_type.rs:2:13
---

Location:
   /cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ui_test-0.29.2/src/lib.rs:369

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
error: test failed, to rerun pass `--test ui`

Caused by:
  process didn't exit successfully: `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/deps/ui-5a4f22761d8182b7` (exit status: 1)
Command has failed. Rerun with -v to see more details.
Build completed unsuccessfully in 0:04:27
  local time: Sat May 24 20:43:03 UTC 2025
  network time: Sat, 24 May 2025 20:43:03 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2025-05-25 00:27 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-19`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/15231967918/job/42840817169) [(plain)](https://github.com/rust-lang/rust/commit/002a06644fcf1f418deff4d6a0ed281f3d5aa28b/checks/42840817169/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#18 exporting to docker image format
#18 sending tarball 20.7s done
#18 DONE 27.8s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-19]
[CI_JOB_NAME=x86_64-gnu-llvm-19]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Listening on address 127.0.0.1:4226
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-19', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'build.print-step-timings', '--enable-verbose-tests', '--set', 'build.metrics', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--set', 'gcc.download-ci-gcc=true', '--enable-new-symbol-mangling']
configure: build.build          := x86_64-unknown-linux-gnu
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-19/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
[RUSTC-TIMING] proc_macro test:false 5.396
[RUSTC-TIMING] test test:false 9.096
    Finished `release` profile [optimized] target(s) in 1m 18s
##[endgroup]
[TIMING] core::build_steps::compile::Std { target: x86_64-unknown-linux-gnu, compiler: Compiler { stage: 1, host: x86_64-unknown-linux-gnu, forced_compiler: true }, crates: [], force_recompile: false, extra_rust_args: ["-Csymbol-mangling-version=v0", "-Cpanic=abort"], is_for_mir_opt_tests: false } -- 78.894
Testing GCC stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
 Downloading crates ...
  Downloaded boml v0.3.1
   Compiling boml v0.3.1
[RUSTC-TIMING] boml test:false 0.786
   Compiling y v0.1.0 (/checkout/compiler/rustc_codegen_gcc/build_system)
[RUSTC-TIMING] y test:false 2.939
    Finished `release` profile [optimized] target(s) in 4.23s
     Running `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-codegen/x86_64-unknown-linux-gnu/release/y test --use-backend gcc --gcc-path /checkout/obj/build/x86_64-unknown-linux-gnu/ci-gcc/lib --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/cg_gcc --release --mini-tests --std-tests`
`--gcc-path` was provided, ignoring config file. Using `/checkout/obj/build/x86_64-unknown-linux-gnu/ci-gcc/lib` as path for libgccjit
[BUILD] mini_core
[RUSTC-TIMING] mini_core test:false 0.204
[BUILD] example
[AOT] mini_core_hello_world
[RUSTC-TIMING] mini_core_hello_world test:false 0.181
---
---- [ui] tests/ui/lint/improper_ctypes/lint-pattern-types.rs stdout ----
Saved the actual stderr to `/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/improper_ctypes/lint-pattern-types/lint-pattern-types.stderr`
diff of stderr:

112    = help: consider using the base type instead, or wrapping `(usize) is 1..` in an `Option<_>`
113    = note: integer-pattern types with one disallowed value and no `Option` wrapping cannot have their value be provided by non-rust code
114 
- error: `extern` fn uses type `(usize) is 0..=18446744073709551613`, which is not FFI-safe
+ error: `extern` fn uses type `(usize) is 0..=4294967293`, which is not FFI-safe
116   --> $DIR/lint-pattern-types.rs:59:9
117    |
118 LL |     h2: pattern_type!(usize is ..USZM1),

121    = help: consider using the base type instead
122    = note: integer-pattern types with more than one disallowed value cannot have their value be provided by non-rust code
123 
- error: `extern` fn uses type `(isize) is -9223372036854775807..`, which is not FFI-safe
+ error: `extern` fn uses type `(isize) is -2147483647..`, which is not FFI-safe
125   --> $DIR/lint-pattern-types.rs:61:9
126    |
127 LL |     h4: pattern_type!(isize is ISZP1..),

128    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not FFI-safe
129    |
-    = help: consider using the base type instead, or wrapping `(isize) is -9223372036854775807..` in an `Option<_>`
+    = help: consider using the base type instead, or wrapping `(isize) is -2147483647..` in an `Option<_>`
131    = note: integer-pattern types with one disallowed value and no `Option` wrapping cannot have their value be provided by non-rust code
132 
133 error: `extern` fn uses type `char`, which is not FFI-safe


The actual stderr differed from the expected stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args lint/improper_ctypes/lint-pattern-types.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/lint/improper_ctypes/lint-pattern-types.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=i686-unknown-linux-gnu" "--check-cfg" "cfg(test,FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/improper_ctypes/lint-pattern-types" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/i686-unknown-linux-gnu/native/rust-test-helpers" "-Clinker=x86_64-linux-gnu-gcc"
stdout: none
--- stderr -------------------------------
error: `extern` fn uses type `Option<(u32) is 0..>`, which is not FFI-safe
##[error]  --> /checkout/tests/ui/lint/improper_ctypes/lint-pattern-types.rs:21:9
   |
LL |     ao: Option<pattern_type!(u32 is 0..)>, //~ ERROR: not FFI-safe
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not FFI-safe
   |
   = help: consider adding a `#[repr(C)]`, `#[repr(transparent)]`, or integer `#[repr(...)]` attribute to this enum
   = note: enum has no representation hint
note: the lint level is defined here
  --> /checkout/tests/ui/lint/improper_ctypes/lint-pattern-types.rs:4:9
   |
LL | #![deny(improper_c_fn_definitions)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^

error: `extern` fn uses type `(u32) is 1..`, which is not FFI-safe
##[error]  --> /checkout/tests/ui/lint/improper_ctypes/lint-pattern-types.rs:22:8
   |
LL |     b: pattern_type!(u32 is 1..),  //~ ERROR: not FFI-safe
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^ not FFI-safe
   |
   = help: consider using the base type instead, or wrapping `(u32) is 1..` in an `Option<_>`
   = note: integer-pattern types with one disallowed value and no `Option` wrapping cannot have their value be provided by non-rust code

error: `extern` fn uses type `(u32) is 2..`, which is not FFI-safe
##[error]  --> /checkout/tests/ui/lint/improper_ctypes/lint-pattern-types.rs:24:8
   |
LL |     c: pattern_type!(u32 is 2..),  //~ ERROR: not FFI-safe
   |        ^^^^^^^^^^^^^^^^^^^ [...]

2025-05-25 12:50 UTC, niacdoial commented
Alright, I think this is good enough for a new review.
Let me try to summarise the state of things, and the major decisions I took:

### Decisions:
- ~~repr(C) on a struct/union/enum is now seen as enough of a signal for the lint to look closer~~ (edit: no, it looks like `repr(C)` is also often used to specify the order of fields. decision undone)
- Static variables with `no_mangle` or `export_name` are now seen as FFI boundaries
- The "valid type, possibly invalid value" part of the checks (used for e.g. references in defined-function arguments) does not apply when linting on FnPtrs.
  (in most cases, these warnings would show up somewhere else. the one case that remains is when an arbitrary non-rust callback is given to a rust function, which later executes it)
- Uninhabited types are now deemed unsafe in function arguments and static variables. For function returns, only ! and empty enums are allowed. (e.g. structs with uninhabited fields are not)
- `&self` in methods will be considered just as unsafe as other un-Option'd references, eventhough last I checked `self: Option<&Self>` is not something that compiles
### Things to maybe do that are relegated to a future PR:
- Make a specific lint for "invalid pointee type" (currently unchecked)
  - There would need to be discussions as to how to deal with types considered opaque on the non-rust side of the FFI boundary
  - Ideally the underlying errors/warnings would vanish if /either/ of `improper_c_pointee` and `improper_ctypes` is allowed
- Same thing for a "possible invalid value for type" lint (currently checked)
  - The only reason here is to be able to allow this without allowing any other part of these lints
- Finally, reintroduce `improper_c_type_definitions` to `#[allow()]` struct/enum/union definitions, even if they are not FFI-safe
### Other points of note:
- I had to add a piece of macro_rules! to `rustc_codegen_llvm::llvm::ffi` to wrap all returned references in options. This is sort of ugly, but I think this is the best solution for this
- This whole PR already fixes #130310 for the wrong reasons, so I had to retroactively add a change that fixes it for the right reasons. (Though I think I'll change my approach on that, I fear I just opened a door to DOS attacks that use a slight modification of that issue's MWE.)

2025-05-30 11:09 UTC, rust-log-analyzer commented
The job **`aarch64-gnu-llvm-19-1`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/15344992857/job/43179233782) [(plain)](https://github.com/rust-lang/rust/commit/6cab7b5c7563428df9352c6af31e5a62815d960a/checks/43179233782/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
diff of stderr:

66    |                                                     ^ help: if this is intentional, prefix it with an underscore: `_b`
67 
68 warning: `extern` fn uses type `&Self`, which is not FFI-safe
-   --> $DIR/naked-functions-unused.rs:11:32
+   --> $DIR/naked-functions-unused.rs:10:32
70    |
71 LL |     extern "C" fn trait_method(&self, a: usize, b: usize) -> usize;
72    |                                ^^^^^ not FFI-safe

77    = note: `#[warn(improper_c_fn_definitions)]` on by default
78 
79 warning: `extern` fn uses type `&normal::Normal`, which is not FFI-safe
-   --> $DIR/naked-functions-unused.rs:37:34
+   --> $DIR/naked-functions-unused.rs:36:34
81    |
82 LL |         pub extern "C" fn method(&self, a: usize, b: usize) -> usize {
83    |                                  ^^^^^ not FFI-safe

87            which cannot be garanteed if their values are produced by non-rust code
88 
89 warning: `extern` fn uses type `&normal::Normal`, which is not FFI-safe
-   --> $DIR/naked-functions-unused.rs:56:36
+   --> $DIR/naked-functions-unused.rs:55:36
91    |
92 LL |         extern "C" fn trait_method(&self, a: usize, b: usize) -> usize {
93    |                                    ^^^^^ not FFI-safe

97            which cannot be garanteed if their values are produced by non-rust code
98 
99 warning: `extern` fn uses type `&Naked`, which is not FFI-safe
-   --> $DIR/naked-functions-unused.rs:88:34
+   --> $DIR/naked-functions-unused.rs:83:34
101    |
102 LL |         pub extern "C" fn method(&self, a: usize, b: usize) -> usize {
103    |                                  ^^^^^ not FFI-safe

107            which cannot be garanteed if their values are produced by non-rust code
108 
109 warning: `extern` fn uses type `&Naked`, which is not FFI-safe
-   --> $DIR/naked-functions-unused.rs:105:36
+   --> $DIR/naked-functions-unused.rs:96:36
111    |
112 LL |         extern "C" fn trait_method(&self, a: usize, b: usize) -> usize {
113    |                                    ^^^^^ not FFI-safe

117            which cannot be garanteed if their values are produced by non-rust code
118 
119 error: aborting due to 10 previous errors; 5 warnings emitted
+ 
---
To only update this specific test, also pass `--test-args asm/naked-functions-unused.rs`

error in revision `aarch64`: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/aarch64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/asm/naked-functions-unused.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/aarch64-unknown-linux-gnu/stage2" "--target=aarch64-unknown-linux-gnu" "--cfg" "aarch64" "--check-cfg" "cfg(test,FALSE,x86_64,aarch64)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/aarch64-unknown-linux-gnu/test/ui/asm/naked-functions-unused.aarch64" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/aarch64-unknown-linux-gnu/native/rust-test-helpers"
stdout: none
--- stderr -------------------------------
error: unused variable: `a`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:17:32
   |
LL |     pub extern "C" fn function(a: usize, b: usize) -> usize {
   |                                ^ help: if this is intentional, prefix it with an underscore: `_a`
   |
note: the lint level is defined here
  --> /checkout/tests/ui/asm/naked-functions-unused.rs:5:9
   |
LL | #![deny(unused)]
   |         ^^^^^^
   = note: `#[deny(unused_variables)]` implied by `#[deny(unused)]`

error: unused variable: `b`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:17:42
   |
LL |     pub extern "C" fn function(a: usize, b: usize) -> usize {
   |                                          ^ help: if this is intentional, prefix it with an underscore: `_b`

error: unused variable: `a`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:28:38
   |
LL |         pub extern "C" fn associated(a: usize, b: usize) -> usize {
   |                                      ^ help: if this is intentional, prefix it with an underscore: `_a`

error: unused variable: `b`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:28:48
   |
LL |         pub extern "C" fn associated(a: usize, b: usize) -> usize {
   |                                                ^ help: if this is intentional, prefix it with an underscore: `_b`

error: unused variable: `a`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:36:41
   |
LL |         pub extern "C" fn method(&self, a: usize, b: usize) -> usize {
   |                                         ^ help: if this is intentional, prefix it with an underscore: `_a`

error: unused variable: `b`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:36:51
   |
LL |         pub extern "C" fn method(&self, a: usize, b: usize) -> usize {
   |                                                   ^ help: if this is intentional, prefix it with an underscore: `_b`

error: unused variable: `a`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:47:40
   |
LL |         extern "C" fn trait_associated(a: usize, b: usize) -> usize {
   |                                        ^ help: if this is intentional, prefix it with an underscore: `_a`

error: unused variable: `b`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:47:50
   |
LL |         extern "C" fn trait_associated(a: usize, b: usize) -> usize {
   |                                                  ^ help: if this is intentional, prefix it with an underscore: `_b`

error: unused variable: `a`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:55:43
   |
LL |         extern "C" fn trait_method(&self, a: usize, b: usize) -> usize {
   |                                           ^ help: if this is intentional, prefix it with an underscore: `_a`

error: unused variable: `b`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:55:53
   |
LL |         extern "C" fn trait_method(&self, a: usize, b: usize) -> usize {
   |                                                     ^ help: if this is intentional, prefix it with an underscore: `_b`

warning: `extern` fn uses type `&Self`, which is not FFI-safe
##[warning]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:10:32
   |
LL |     extern "C" fn trait_method(&self, a: usize, b: usize) -> usize;
   |                                ^^^^^ not FFI-safe
   |
   = help: consider using a raw pointer, or wrapping `&Self` in an `Option<_>`
   = note: boxes, references, and function pointers are assumed to be valid (non-null, non-dangling, aligned) pointers,
           which cannot be garanteed if their values are produced by non-rust code
   = note: `#[warn(improper_c_fn_definitions)]` on by default

warning: `extern` fn uses type `&normal::Normal`, which is not FFI-safe
##[warning]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:36:34
   |
LL |         pub extern "C" fn method(&self, a: usize, b: usize) -> usize {
   |                                  ^^^^^ not FFI-safe
   |
   = help: consider using a raw pointer, or wrapping `&normal::Normal` in  [...]

2025-05-30 11:49 UTC, rust-log-analyzer commented
The job **`aarch64-gnu-llvm-19-1`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/15345655859/job/43181227267) [(plain)](https://github.com/rust-lang/rust/commit/a32c27b405afe102d58b0fd5e4ead15b7569c37c/checks/43181227267/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
To only update this specific test, also pass `--test-args asm/naked-functions-unused.rs`

error in revision `aarch64`: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/aarch64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/asm/naked-functions-unused.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/aarch64-unknown-linux-gnu/stage2" "--target=aarch64-unknown-linux-gnu" "--cfg" "aarch64" "--check-cfg" "cfg(test,FALSE,x86_64,aarch64)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/aarch64-unknown-linux-gnu/test/ui/asm/naked-functions-unused.aarch64" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/aarch64-unknown-linux-gnu/native/rust-test-helpers"
stdout: none
--- stderr -------------------------------
error: unused variable: `a`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:17:32
   |
LL |     pub extern "C" fn function(a: usize, b: usize) -> usize {
   |                                ^ help: if this is intentional, prefix it with an underscore: `_a`
   |
note: the lint level is defined here
  --> /checkout/tests/ui/asm/naked-functions-unused.rs:5:9
   |
LL | #![deny(unused)]
   |         ^^^^^^
   = note: `#[deny(unused_variables)]` implied by `#[deny(unused)]`

error: unused variable: `b`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:17:42
   |
LL |     pub extern "C" fn function(a: usize, b: usize) -> usize {
   |                                          ^ help: if this is intentional, prefix it with an underscore: `_b`

error: unused variable: `a`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:28:38
   |
LL |         pub extern "C" fn associated(a: usize, b: usize) -> usize {
   |                                      ^ help: if this is intentional, prefix it with an underscore: `_a`

error: unused variable: `b`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:28:48
   |
LL |         pub extern "C" fn associated(a: usize, b: usize) -> usize {
   |                                                ^ help: if this is intentional, prefix it with an underscore: `_b`

error: unused variable: `a`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:36:41
   |
LL |         pub extern "C" fn method(&self, a: usize, b: usize) -> usize {
   |                                         ^ help: if this is intentional, prefix it with an underscore: `_a`

error: unused variable: `b`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:36:51
   |
LL |         pub extern "C" fn method(&self, a: usize, b: usize) -> usize {
   |                                                   ^ help: if this is intentional, prefix it with an underscore: `_b`

error: unused variable: `a`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:47:40
   |
LL |         extern "C" fn trait_associated(a: usize, b: usize) -> usize {
   |                                        ^ help: if this is intentional, prefix it with an underscore: `_a`

error: unused variable: `b`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:47:50
   |
LL |         extern "C" fn trait_associated(a: usize, b: usize) -> usize {
   |                                                  ^ help: if this is intentional, prefix it with an underscore: `_b`

error: unused variable: `a`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:55:43
   |
LL |         extern "C" fn trait_method(&self, a: usize, b: usize) -> usize {
   |                                           ^ help: if this is intentional, prefix it with an underscore: `_a`

error: unused variable: `b`
##[error]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:55:53
   |
LL |         extern "C" fn trait_method(&self, a: usize, b: usize) -> usize {
   |                                                     ^ help: if this is intentional, prefix it with an underscore: `_b`

warning: `extern` fn uses type `&Self`, which is not FFI-safe
##[warning]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:10:32
   |
LL |     extern "C" fn trait_method(&self, a: usize, b: usize) -> usize;
   |                                ^^^^^ not FFI-safe
   |
   = help: consider using a raw pointer, or wrapping `&Self` in an `Option<_>`
   = note: boxes, references, and function pointers are assumed to be valid (non-null, non-dangling, aligned) pointers,
           which cannot be garanteed if their values are produced by non-rust code
   = note: `#[warn(improper_c_fn_definitions)]` on by default

warning: `extern` fn uses type `&normal::Normal`, which is not FFI-safe
##[warning]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:36:34
   |
LL |         pub extern "C" fn method(&self, a: usize, b: usize) -> usize {
   |                                  ^^^^^ not FFI-safe
   |
   = help: consider using a raw pointer, or wrapping `&normal::Normal` in an `Option<_>`
   = note: boxes, references, and function pointers are assumed to be valid (non-null, non-dangling, aligned) pointers,
           which cannot be garanteed if their values are produced by non-rust code

warning: `extern` fn uses type `&normal::Normal`, which is not FFI-safe
##[warning]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:55:36
   |
LL |         extern "C" fn trait_method(&self, a: usize, b: usize) -> usize {
   |                                    ^^^^^ not FFI-safe
   |
   = help: consider using a raw pointer, or wrapping `&normal::Normal` in an `Option<_>`
   = note: boxes, references, and function pointers are assumed to be valid (non-null, non-dangling, aligned) pointers,
           which cannot be garanteed if their values are produced by non-rust code

warning: `extern` fn uses type `&Naked`, which is not FFI-safe
##[warning]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:83:34
   |
LL |         pub extern "C" fn method(&self, a: usize, b: usize) -> usize {
   |                                  ^^^^^ not FFI-safe
   |
   = help: consider using a raw pointer, or wrapping `&Naked` in an `Option<_>`
   = note: boxes, references, and function pointers are assumed to be valid (non-null, non-dangling, aligned) pointers,
           which cannot be garanteed if their values are produced by non-rust code

warning: `extern` fn uses type `&Naked`, which is not FFI-safe
##[warning]  --> /checkout/tests/ui/asm/naked-functions-unused.rs:96:36
   |
LL |         extern "C" fn trait_method(&self, a: usize, b: usize) -> usize {
   |                                    ^^^^^ not FFI-safe
   |
   = help: consider using a raw pointer, or wrapping `&Naked` in an `Option<_>`
   = note: boxes, references, and function pointers are assumed to be valid (non-null, non-dangling, aligned) pointers,
           which cannot be garanteed if their values are produced by non-rust code

```

</details>

2025-05-30 23:39 UTC, niacdoial commented
...ok that's what I get for clicking a button at 1h30 am. I'll fix all this new stuff tomorrow

2025-05-31 15:40 UTC, niacdoial commented
as an answer to those automated warnings:

### things that might need further changes

> clippy, rust-analyzer, miri:

mostly changes to add the new lints to the documentation, and some expected lint reshuffling in the tests
though, the fact that they are in subtrees could cause a problem.
Should I still move that piece of the PR on the individual repos, with some `#[allow(unknown_lints)]` trickery to ensure stuff doesn't break when they are merged prior to this?

### things with no further changes needed IMO

> This PR modifies tests/auxiliary/minicore.rs.

yes. I was removing `#[allow(improper_ctypes_definitions)]` to change to one of the new lints, but it turns out there is not need to `#[allow()]` anything

> file in tests/crashes

done

> Cargo.lock

the only change is an added dependency of `rustc_lint` on `rustc_type_ir`

>  `compiler/rustc_codegen_llvm/src/llvm/enzyme_ffi.rs` (and `rustc_codegen_llvm` in general)

the changes are basically to wrap the `extern "C" { fn(_) -> &ReturnType }` functions' return types into options, then actually `.unwrap()` this option, in order to change UB into proper panics

2025-05-31 22:09 UTC, niacdoial commented
at this point I think I'll deal with this (merge conflicts) when reviews have occurred. Probably the same amount of human work on my side, but it prevents changes of code mid-review, and will save a bunch of compute time running all tests every two days

2025-06-04 00:36 UTC, workingjubilee commented
Sorry, had taken a bit to claw through review backlog accumulated during RustWeek!

2025-06-04 01:06 UTC, workingjubilee commented
> Uninhabited types are now deemed unsafe in function arguments and static variables. For function returns, only ! and empty enums are allowed. (e.g. structs with uninhabited fields are not)

So, an odd thing happened: We discovered that "a struct with uninhabited fields" is actually how we model the ABI of functions that are marked `[[noreturn]]`. Specifically, an uninhabited 1ZST field is paired with a type in the return. So uninhabitedness should probably just be allowed, without linting, if the rest of the type is C-compatible? We can dial in from there.

Specifically
> Currently, `#[repr(transparent)]` types containing uninhabited 1-ZSTs as the non-transparent-wrapped field do not uphold the ABI-compatibility guarantee implied by `#[repr(transparent)]`.

2025-06-04 01:15 UTC, workingjubilee commented on compiler/rustc_codegen_llvm/src/llvm/ffi.rs
> +macro_rules! wrap_returns_in_options {
hm. sadly, that we need this feels like a warning that the current changeset is a bit too ambitious and will require too sudden and sharp a migration.

2025-06-04 01:17 UTC, workingjubilee commented on compiler/rustc_codegen_llvm/src/llvm/ffi.rs
> +macro_rules! wrap_returns_in_options {
Eugh. I hope I am not suddenly changing my mind on you.

It's a questionable thing obviously, but I'm not sure if we can in good conscience extend the warning so widely here.

2025-06-04 01:25 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    }
We probably can rip out the power alignment lint, it is just papering over https://github.com/llvm/llvm-project/issues/133599

2025-06-04 08:07 UTC, niacdoial commented on compiler/rustc_codegen_llvm/src/llvm/ffi.rs
> +macro_rules! wrap_returns_in_options {
yeah...
I think this can be postponed to a later PR and a separate (sub)lint, like for checking the types of pointees (if the pointers themselves are good)

I'll just add a commit that reverts this part, so it can be un-reverted easily later.
how much should I remove from this? Do I make the smallest amount of changes relative to the current state of this PR, or do I remove as much as possible to reduce the size of the PR as a whole?
(also, this huge `macro_rules!` item and its uses will go away, but should I also remove the changes to `rustc_codegen_llvm::back::write` and `library::proc_macro::bridge::{buffer,closure}`?)

<sub>also also, for what is worth, this part of the lint was indeed your suggestion to begin with, :P [(here)](https://github.com/rust-lang/rust/pull/131669#issuecomment-2466946690). don't worry though, it was one of the easier things to take into account</sub>

2025-06-04 08:29 UTC, niacdoial commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    }
ok?
I feel out of my depth here, given that linked issue is still open. (and if I read the comments on it correctly, it's up to the compilers that use LLVM to make sure they get the alignment right? has rust implemented this somewhere already?)

so, let me ask another way: do you *want* me to remove this lint during this PR? If so, no problem.

2025-06-04 09:50 UTC, niacdoial commented
> [...] So uninhabitedness should probably just be allowed, without linting, if the rest of the type is C-compatible? We can dial in from there.
> 
> Specifically, we fixed "`#[repr(transparent)]` types containing uninhabited 1-ZSTs as the non-transparent-wrapped field" so that they uphold the ABI-compatibily guarantee implied by `#[repr(transparent)]`.

so... option 1 (all uninhabited returns allowed) for now, and later restrict this to option 2 (only `!`, `EmptyEnum` and `#[repr(transparent)]` structs with one of those as one of its `1-ZST`s)?

> Sorry, had taken a bit to claw through review backlog accumulated during RustWeek!

oh, right I should have anticipated this. still, no problem! I kinda expected you to have a lot of other things taking your time (especially if some are more critical than a lint revamp)

2025-06-04 14:43 UTC, niacdoial commented
Adding [this pull that just landed and causes a few merge conflicts](https://github.com/rust-lang/rust/pull/137306) as required reading for myself, eventhough I started reading parts of it.

(I should have seen this while it was in RFC... at least this gives me a slight clarification about the PowerAlignment lint thing)
I guess I forgot about `visit_numeric`'s x86_64-centricity in my summary comment. At least removing the u128/i128 lint altogether will make this a clean slate if/when it gets revisited to be architecture-dependant in the future.
(RalfJung, if you see this, I'm mostly sure the ImproperCTypes lints do in fact look into dependencies, so it should be fine to add something architecture-dependant. In any case, I'll double-check that statement if I do something about it)

2025-06-04 20:54 UTC, workingjubilee commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    }
Sorry. No not necessarily, I'll take care of that.

2025-06-04 20:54 UTC, workingjubilee commented on compiler/rustc_codegen_llvm/src/llvm/ffi.rs
> +macro_rules! wrap_returns_in_options {
ugh @ @workingjubilee

2025-06-04 20:57 UTC, niacdoial commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    }
ok, thanks!
also, nothing to be sorry about, I think?

2025-06-05 21:00 UTC, niacdoial commented on compiler/rustc_codegen_llvm/src/llvm/ffi.rs
> +macro_rules! wrap_returns_in_options {
I'm going with the "reduce the size of the PR as a whole" angle, but I realised there are still a bunch of now-unneeded `#[allow(improper_c_something)]`s in the tests now.
I think I'll leave the added `Option<_>`s though

2025-06-06 02:46 UTC, workingjubilee commented on compiler/rustc_codegen_llvm/src/llvm/ffi.rs
> +macro_rules! wrap_returns_in_options {
Oh, sorry, yes, reducing the size is best.

2025-06-06 09:59 UTC, bjorn3 commented on library/panic_abort/src/lib.rs
>  pub unsafe extern "C" fn __rust_panic_cleanup(_: *mut u8) -> *mut (dyn Any + Send + 'static) {
We should be able to use `extern "Rust"` I would think (both here and on the caller side).

2025-06-06 10:00 UTC, bjorn3 commented on library/panic_abort/src/lib.rs
> +#[allow(unknown_lints, renamed_and_removed_lints, improper_ctypes_definitions)] // FIXME delete line once improper_c_fn_definitions exists upstream
Should be possible to remove this now that the stage0 rework has been done: https://blog.rust-lang.org/inside-rust/2025/05/29/redesigning-the-initial-bootstrap-sequence/

2025-06-06 10:03 UTC, bjorn3 commented on compiler/rustc_codegen_llvm/src/back/write.rs
> +unsafe extern "C" fn diagnostic_handler(info: Option<&DiagnosticInfo>, user: *mut c_void) {
I disagree with having to wrap all references in `Option`. You have the invariant that the reference is valid (if not NULL) either way. It is very much reasonable to expect the C side not to pass NULL, in which case the argument will never be `None`.

2025-06-10 20:01 UTC, workingjubilee commented
I opened https://github.com/rust-lang/rust/pull/142310 to handle the power alignment lint problem.

2025-06-10 22:22 UTC, niacdoial commented on library/panic_abort/src/lib.rs
>  pub unsafe extern "C" fn __rust_panic_cleanup(_: *mut u8) -> *mut (dyn Any + Send + 'static) {
OK!
I assume this is also due to something like the stage0 rework (something along the lines of "we now know caller and callee are compiled by the same compiler")?
Let's just see if it passes the tests then.

2025-06-10 22:23 UTC, niacdoial commented on library/panic_abort/src/lib.rs
> +#[allow(unknown_lints, renamed_and_removed_lints, improper_ctypes_definitions)] // FIXME delete line once improper_c_fn_definitions exists upstream
done, let's see if it passes the tests (will resolve the conversation when it does)

2025-06-10 22:44 UTC, niacdoial commented on compiler/rustc_codegen_llvm/src/back/write.rs
> +unsafe extern "C" fn diagnostic_handler(info: Option<&DiagnosticInfo>, user: *mut c_void) {
ok!
I'll assume you have the same to say about the changes in `compiler/rustc_llvm/src/lib.rs`, `library/proc_macro/src/bridge/{buffer,closure}.rs`, and `src/tools/clippy/tests/ui/boxed_local.rs`, so I'll be also removing the new `Option<_>`s there as well.

2025-06-23 06:14 UTC, niacdoial commented
question, @workingjubilee:
Do I rebase this branch now?
I have no idea if you (or someone else) is in the middle of a review, and I would rather avoid changing the code while you're looking at it.
But at the same time, you might be waiting for me to rebase to do another round of review so... yeah.

2025-07-30 21:40 UTC, niacdoial commented
@workingjubilee ...?
I think I'll end up rebasing anyway if you don't tell me to wait.
(sorry if this seems too insistent or something)

2025-08-06 23:06 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/16789771817/job/47549009803) [(plain enhanced)](https://triage.rust-lang.org/gha-logs/rust-lang/rust/47549009803) [(plain)](https://github.com/rust-lang/rust/commit/f19f4da6c285dab7bffbe76f1bb61409cd52747a/checks/47549009803/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
tests/ui/size_of_in_element_count/functions.rs ... ok
tests/ui/crashes/third-party/conf_allowlisted.rs ... ok

FAILED TEST: tests/ui/ptr_arg.rs
command: CLIPPY_CONF_DIR="tests" RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/clippy-driver" "--error-format=json" "--emit=metadata" "-Aunused" "-Ainternal_features" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Dwarnings" "-Ldependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/release/deps" "--sysroot=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/tests/ui" "tests/ui/ptr_arg.rs" "--extern" "futures=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libfutures-45fbd1b9e4dad26b.rlib" "--extern" "futures=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libfutures-45fbd1b9e4dad26b.rmeta" "--extern" "if_chain=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libif_chain-300689d41d78e45f.rlib" "--extern" "if_chain=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libif_chain-300689d41d78e45f.rmeta" "--extern" "itertools=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libitertools-54c334f52b2a6a90.rlib" "--extern" "itertools=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libitertools-54c334f52b2a6a90.rmeta" "--extern" "libc=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/liblibc-d7d65b59566ca2ca.rlib" "--extern" "libc=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/liblibc-d7d65b59566ca2ca.rmeta" "--extern" "parking_lot=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libparking_lot-6811f6561eb9b997.rlib" "--extern" "parking_lot=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libparking_lot-6811f6561eb9b997.rmeta" "--extern" "quote=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libquote-e71f5a1f4570f066.rlib" "--extern" "quote=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libquote-e71f5a1f4570f066.rmeta" "--extern" "regex=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libregex-0e611a3f1f597ae0.rlib" "--extern" "regex=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libregex-0e611a3f1f597ae0.rmeta" "--extern" "serde=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libserde-f5ef936707521d75.rlib" "--extern" "serde=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libserde-f5ef936707521d75.rmeta" "--extern" "syn=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libsyn-1f6dc7b1eaa04e5b.rlib" "--extern" "syn=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libsyn-1f6dc7b1eaa04e5b.rmeta" "--extern" "tokio=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libtokio-db31a244cf4a101e.rlib" "--extern" "tokio=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libtokio-db31a244cf4a101e.rmeta" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/debug/deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps" "--edition" "2024"

error: actual output differed from expected
Execute `./x test src/tools/clippy --bless` to update `tests/ui/ptr_arg.stderr` to the actual output
--- tests/ui/ptr_arg.stderr
+++ <stderr output>
 error: writing `&Vec` instead of `&[_]` involves a new object where a slice will do
   --> tests/ui/ptr_arg.rs:13:14
... 218 lines skipped ...
 
 error: writing `&String` instead of `&str` involves a new object where a slice will do
-  --> tests/ui/ptr_arg.rs:348:17
+  --> tests/ui/ptr_arg.rs:347:17
    |
 LL |     fn good(v1: &String, v2: &String) {
    |                 ^^^^^^^ help: change this to: `&str`
 
 error: writing `&String` instead of `&str` involves a new object where a slice will do
-  --> tests/ui/ptr_arg.rs:348:30
+  --> tests/ui/ptr_arg.rs:347:30
    |
 LL |     fn good(v1: &String, v2: &String) {
... 55 lines skipped ...
 error: aborting due to 33 previous errors
 

Full unnormalized output:
error: writing `&Vec` instead of `&[_]` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:13:14
   |
LL | fn do_vec(x: &Vec<i64>) {
   |              ^^^^^^^^^ help: change this to: `&[i64]`
   |
   = note: `-D clippy::ptr-arg` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::ptr_arg)]`

error: writing `&mut Vec` instead of `&mut [_]` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:19:18
   |
LL | fn do_vec_mut(x: &mut Vec<i64>) {
   |                  ^^^^^^^^^^^^^ help: change this to: `&mut [i64]`

error: writing `&mut Vec` instead of `&mut [_]` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:25:19
   |
LL | fn do_vec_mut2(x: &mut Vec<i64>) {
   |                   ^^^^^^^^^^^^^ help: change this to: `&mut [i64]`

error: writing `&String` instead of `&str` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:32:14
   |
LL | fn do_str(x: &String) {
---

error: writing `&PathBuf` instead of `&Path` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:44:15
   |
LL | fn do_path(x: &PathBuf) {
   |               ^^^^^^^^ help: change this to: `&Path`

error: writing `&mut PathBuf` instead of `&mut Path` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:50:19
   |
LL | fn do_path_mut(x: &mut PathBuf) {
   |                   ^^^^^^^^^^^^ help: change this to: `&mut Path`

error: writing `&Vec` instead of `&[_]` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:60:18
   |
LL |     fn do_vec(x: &Vec<i64>);
   |                  ^^^^^^^^^ help: change this to: `&[i64]`

error: writing `&Vec` instead of `&[_]` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:75:14
   |
LL | fn cloned(x: &Vec<u8>) -> Vec<u8> {
   |              ^^^^^^^^
   |
help: change this to
   |
LL ~ fn cloned(x: &[u8]) -> Vec<u8> {
LL |
LL |
LL ~     let e = x.to_owned();
LL |     let f = e.clone(); // OK
LL |     let g = x;
LL ~     let h = g.to_owned();
LL |     let i = (e).clone();
LL ~     x.to_owned()
   |

error: writing `&String` instead of `&str` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:86:18
   |
LL | fn str_cloned(x: &String) -> String {
   |                  ^^^^^^^
   |
help: change this to
   |
LL ~ fn str_cloned(x: &str) -> String {
LL |
LL |
LL ~     let a = x.to_owned();
LL ~     let b = x.to_owned();
LL |     let c = b.clone();
LL |     let d = a.cl [...]

2025-08-07 09:47 UTC, niacdoial commented
re: not making changes in compiler-builtins:
I'll be able to ensure that once https://github.com/rust-lang/compiler-builtins/pull/1006 lands
(thanks @/tgross35 for handling it before I could try to!)

2025-08-07 17:19 UTC, tgross35 commented
> re: not making changes in compiler-builtins: I'll be able to ensure that once [rust-lang/compiler-builtins#1006](https://github.com/rust-lang/compiler-builtins/pull/1006) lands (thanks @/tgross35 for handling it before I could try to!)

For future reference, it's fine for small changes like this to go through rust-lang/rust. I just was curious about the results since i128 got removed from improper_ctypes a while ago, and wanted a CI run in that repo.

2025-08-07 20:56 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/16814469239/job/47627716933) [(plain enhanced)](https://triage.rust-lang.org/gha-logs/rust-lang/rust/47627716933) [(plain)](https://github.com/rust-lang/rust/commit/c414d4183c4e68185ac6da71dd86625790f4ae80/checks/47627716933/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
tests/ui/size_of_in_element_count/functions.rs ... ok
tests/ui/crashes/third-party/conf_allowlisted.rs ... ok

FAILED TEST: tests/ui/ptr_arg.rs
command: CLIPPY_CONF_DIR="tests" RUSTC_ICE="0" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/clippy-driver" "--error-format=json" "--emit=metadata" "-Aunused" "-Ainternal_features" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Dwarnings" "-Ldependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/release/deps" "--sysroot=/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/tests/ui" "tests/ui/ptr_arg.rs" "--extern" "futures=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libfutures-45fbd1b9e4dad26b.rlib" "--extern" "futures=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libfutures-45fbd1b9e4dad26b.rmeta" "--extern" "if_chain=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libif_chain-300689d41d78e45f.rlib" "--extern" "if_chain=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libif_chain-300689d41d78e45f.rmeta" "--extern" "itertools=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libitertools-54c334f52b2a6a90.rlib" "--extern" "itertools=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libitertools-54c334f52b2a6a90.rmeta" "--extern" "libc=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/liblibc-d7d65b59566ca2ca.rlib" "--extern" "libc=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/liblibc-d7d65b59566ca2ca.rmeta" "--extern" "parking_lot=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libparking_lot-6811f6561eb9b997.rlib" "--extern" "parking_lot=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libparking_lot-6811f6561eb9b997.rmeta" "--extern" "quote=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libquote-e71f5a1f4570f066.rlib" "--extern" "quote=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libquote-e71f5a1f4570f066.rmeta" "--extern" "regex=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libregex-0e611a3f1f597ae0.rlib" "--extern" "regex=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libregex-0e611a3f1f597ae0.rmeta" "--extern" "serde=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libserde-f5ef936707521d75.rlib" "--extern" "serde=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libserde-f5ef936707521d75.rmeta" "--extern" "syn=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libsyn-1f6dc7b1eaa04e5b.rlib" "--extern" "syn=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libsyn-1f6dc7b1eaa04e5b.rmeta" "--extern" "tokio=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libtokio-db31a244cf4a101e.rlib" "--extern" "tokio=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps/libtokio-db31a244cf4a101e.rmeta" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/debug/deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools/ui_test/0/x86_64-unknown-linux-gnu/debug/deps" "--edition" "2024"

error: actual output differed from expected
Execute `./x test src/tools/clippy --bless` to update `tests/ui/ptr_arg.stderr` to the actual output
--- tests/ui/ptr_arg.stderr
+++ <stderr output>

thread 'main' (50229) panicked at src/tools/clippy/tests/compile-test.rs:247:6:
called `Result::unwrap()` on an `Err` value: tests failed

Location:
    /cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ui_test-0.30.2/src/lib.rs:365:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 error: writing `&Vec` instead of `&[_]` involves a new object where a slice will do
   --> tests/ui/ptr_arg.rs:13:14
... 283 lines skipped ...
 
 error: aborting due to 33 previous errors
+

Full unnormalized output:
error: writing `&Vec` instead of `&[_]` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:13:14
   |
LL | fn do_vec(x: &Vec<i64>) {
   |              ^^^^^^^^^ help: change this to: `&[i64]`
   |
   = note: `-D clippy::ptr-arg` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::ptr_arg)]`

error: writing `&mut Vec` instead of `&mut [_]` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:19:18
   |
LL | fn do_vec_mut(x: &mut Vec<i64>) {
   |                  ^^^^^^^^^^^^^ help: change this to: `&mut [i64]`

error: writing `&mut Vec` instead of `&mut [_]` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:25:19
   |
LL | fn do_vec_mut2(x: &mut Vec<i64>) {
   |                   ^^^^^^^^^^^^^ help: change this to: `&mut [i64]`

error: writing `&String` instead of `&str` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:32:14
   |
LL | fn do_str(x: &String) {
---

error: writing `&PathBuf` instead of `&Path` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:44:15
   |
LL | fn do_path(x: &PathBuf) {
   |               ^^^^^^^^ help: change this to: `&Path`

error: writing `&mut PathBuf` instead of `&mut Path` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:50:19
   |
LL | fn do_path_mut(x: &mut PathBuf) {
   |                   ^^^^^^^^^^^^ help: change this to: `&mut Path`

error: writing `&Vec` instead of `&[_]` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:60:18
   |
LL |     fn do_vec(x: &Vec<i64>);
   |                  ^^^^^^^^^ help: change this to: `&[i64]`

error: writing `&Vec` instead of `&[_]` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:75:14
   |
LL | fn cloned(x: &Vec<u8>) -> Vec<u8> {
   |              ^^^^^^^^
   |
help: change this to
   |
LL ~ fn cloned(x: &[u8]) -> Vec<u8> {
LL |
LL |
LL ~     let e = x.to_owned();
LL |     let f = e.clone(); // OK
LL |     let g = x;
LL ~     let h = g.to_owned();
LL |     let i = (e).clone();
LL ~     x.to_owned()
   |

error: writing `&String` instead of `&str` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:86:18
   |
LL | fn str_cloned(x: &String) -> String {
   |                  ^^^^^^^
   |
help: change this to
   |
LL ~ fn str_cloned(x: &str) -> String {
LL |
LL |
LL ~     let a = x.to_owned();
LL ~     let b = x.to_owned();
LL |     let c = b.clone();
LL |     let d = a.clone().clone().clone();
LL ~     x.to_owned()
   |

error: writing `&PathBuf` instead of `&Path` involves a new object where a slice will do
##[error]  --> tests/ui/ptr_arg.rs:96:19
    [...]

2025-08-14 21:05 UTC, tgross35 reviewed
A meta question that may be somewhere in this discussion: could the current names be kept around as groups? E.g. make `improper_ctypes_definitions` a group for `improper_c_fn_definitions` and `improper_c_callbacks`, to help avoid the ecosystem churn.

It would be very helpful if you could update the PR message to summarize the user-visible changes from this, mentioning the specific lint names and maybe tiny examples.

Also, does this happen to fix https://github.com/rust-lang/rust/issues/132699? I think it might but didn't see a test or `Fixes:` tag.

> question, @workingjubilee: Do I rebase this branch now? I have no idea if you (or someone else) is in the middle of a review, and I would rather avoid changing the code while you're looking at it. But at the same time, you might be waiting for me to rebase to do another round of review so... yeah.

Yeah that triagebot warning is far too noisy. I don't really think there's much need to rebase unless there are conflicts (not really tests) or if something about the code you're working on has changed.

However, you may want to re-split your commits / squash some so they each only contains active code. I started doing a breeze through review and since this is huge started to do it by commit, only to find out that a lot of the code from the first commits is completely gone 🙃

2025-08-14 21:05 UTC, tgross35 commented on compiler/rustc_codegen_llvm/src/llvm/ffi.rs
What's going on with this change (two args named LHS)?

2025-08-14 21:05 UTC, tgross35 commented on library/std/src/panicking.rs
>  }
Changing the ABI here is orthogonal to the lint change, could you drop this part?

2025-08-14 21:05 UTC, tgross35 commented on src/tools/rust-analyzer/crates/ide-db/src/generated/lints.rs
AIUI, you don't need to do changes to this file by hand since they get autogenerated at sync time

2025-08-14 21:05 UTC, tgross35 commented on tests/ui/extern/extern-C-non-FFI-safe-arg-ice-52334.rs
> +    // ^ FIXME: the error isn't seen here but at least it's reported elsewhere
Nit: Always using something like `FIXME(ctypes)` makes it much easier to find related changes among the thousands of FIXMEs

2025-08-14 21:05 UTC, tgross35 commented on tests/ui/lint/improper_ctypes/allow_improper_ctypes.rs
> +extern crate outer_crate_types as outer;
`extern_crate_types` maybe?

2025-08-14 21:05 UTC, tgross35 commented on tests/ui/lint/improper_ctypes/lint-94223.rs
We're trying to get away from tests named by numbers, so make sure any new files get a descriptive name (f not also a one line description in the file). An `// Issue: https://github.com/rust-lang/rust/issues/94223` comment is the loose convention for keeping things linked.

2025-08-14 21:05 UTC, tgross35 commented on tests/ui/lint/improper_ctypes/lint-tykind-fuzz.rs
> +}
Nit: run rustfmt on this file, looks like indentation is mixed

2025-08-14 21:05 UTC, tgross35 commented on tests/ui/rfcs/rfc-2008-non-exhaustive/improper_ctypes/same_crate_proper.rs
> +//pub struct UnitStruct;
Why was this commented?

2025-08-14 21:23 UTC, tgross35 commented
This adds more visitors so it should get a perf run at some point (requires a conflict-free merge to master)

2025-08-15 21:18 UTC, niacdoial commented on compiler/rustc_codegen_llvm/src/llvm/ffi.rs
oh dear, something went wrong in my ...I don't know how many rebases, I think.
(I could have sworn I *fixed* this on my own branch, but since the current pull *unfixes* it instead... bleh.)
I'll need to re-review my own changes, I think.

2025-08-15 21:19 UTC, niacdoial commented on library/std/src/panicking.rs
>  }
sure!

2025-08-15 21:22 UTC, niacdoial commented on tests/ui/rfcs/rfc-2008-non-exhaustive/improper_ctypes/same_crate_proper.rs
> +//pub struct UnitStruct;
not sure anymore either, probably something that (1) shouldn't have made it in the PR and (2) not useful anymore anyway. I'll undo it.

2025-08-15 21:50 UTC, niacdoial commented
Thanks for the review!
I didn't reply to most of your comments, because otherwise you would get spammed by a bunch of "sure!" notifications.

I'll get to all of this soon (including checking if the old lints can be neatly split into the new lints, make groups with these names, and look into #132699), though it might take a few days to start.

One exception I would like to add to the "every commit only contains active code" thing, if you don't mind: I would like to keep the "remove unchecked-value-assumptions lints" commit, so that it could be easily reverted in the future. (ideally, I would like to have separate allow-by-default (maybe) lints both this and C-compatible-pointer-to-improper-pointee, set up in such a way that the warnings/errors only appear if two lints are set to warn/deny)

I'll try to get you some local rustc-perf numbers by the next rebase, too.

2025-08-15 21:51 UTC, niacdoial commented on src/tools/rust-analyzer/crates/ide-db/src/generated/lints.rs
hm... I'll try without them, but I wouldn't be surprised if some tests fail without this. though that might be a moot point if the old lint names are kept as lint groups

2025-08-15 22:33 UTC, tgross35 commented
> One exception I would like to add to the "every commit only contains active code" thing, if you don't mind: I would like to keep the "remove unchecked-value-assumptions lints" commit, so that it could be easily reverted in the future. (ideally, I would like to have separate allow-by-default (maybe) lints both this and C-compatible-pointer-to-improper-pointee, set up in such a way that the warnings/errors only appear if two lints are set to warn/deny)

I haven't looked but that sounds fine. Doing refactoring to improve the next step and then eventually deleting everything that got refactored is quite alright if it helps make the transition smoother, as is adding something new and removing something old in separate commits (ideally `./x` still checks on both sides, given you mentioned revertability). The thing to avoid is adding something new that gets completely blown away without helping the migration path (mostly experimentation / past implementations).

> I'll try to get you some local rustc-perf numbers by the next rebase, too.

No need to bother, significantly easier to run perfbot on the CI here once you update :)

2025-08-29 22:07 UTC, rust-log-analyzer commented
The job **`tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/17335107416/job/49219762503) [(plain enhanced)](https://triage.rust-lang.org/gha-logs/rust-lang/rust/49219762503) [(plain)](https://github.com/rust-lang/rust/commit/f614086e08e7a1da5c2dcaa67e0f15b28bb4506f/checks/49219762503/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
finished building tool typos
error: `curent` should be `current`
##[error]  --> compiler/rustc_lint/src/types.rs:1063:35
     |
1063 |                     // update the curent-highest-range-end, if the current range has a higher end
     |                                   ^^^^^^
     |
error: `arguement` should be `argument`
##[error]  --> compiler/rustc_lint/src/types/improper_ctypes.rs:127:88
    |
127 |     /// (e.g.: even if the lint goes into detail as to why a struct used as a function arguement
    |                                                                                        ^^^^^^^^^
    |
error: `otherwide` should be `otherwise`
##[error]  --> compiler/rustc_lint/src/types/improper_ctypes.rs:809:12
    |
809 |         // otherwide, having all fields be phantoms
    |            ^^^^^^^^^
    |
error: `implicitely` should be `implicitly`
##[error]  --> compiler/rustc_lint/src/types/improper_ctypes.rs:959:32
    |
959 |             // Empty enums are implicitely handled as the never type:
    |                                ^^^^^^^^^^^
    |
error: `occured` should be `occurred`
##[error]  --> compiler/rustc_lint/src/types/improper_ctypes.rs:1234:50
     |
1234 |                     // normalisation has already occured
     |                                                  ^^^^^^^
     |
tidy error: checks with external tool 'typos' failed
some tidy checks failed
Command `/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-tools-bin/rust-tidy /checkout /checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo /checkout/obj/build 4 /node/bin/npm --extra-checks=py,cpp,js,spellcheck` failed with exit code 1
Created at: src/bootstrap/src/core/build_steps/tool.rs:1583:23
Executed at: src/bootstrap/src/core/build_steps/test.rs:1225:29

Command has failed. Rerun with -v to see more details.
Bootstrap failed while executing `test --stage 0 src/tools/tidy tidyselftest --extra-checks=py,cpp,js,spellcheck`
Build completed unsuccessfully in 0:02:32
  local time: Fri Aug 29 22:07:45 UTC 2025
  network time: Fri, 29 Aug 2025 22:07:45 GMT
##[error]Process completed with exit code 1.
```

</details>

2025-08-30 00:18 UTC, tgross35 reviewed
Thank you for the history cleanup; looking at the first few commits, things seem to make a lot more sense. I did a quick breeze through the first ~8 patches and left some comments.

One general request to help reviewability: could you try to add some more detail to the commit messages? To say what the motivation is and what the changes are, or if it's just a refactoring with no visible changes. E.g. "change X linting" and the "change handling of X" commits, what do they actually change - just the diagnostic wording? catch something new? fix a false positive? fix something broken? move to a different group? refactoring? etc. Basically a mini PR description :)

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/134697/fe55364329579d361b1ab565728bc033a7dba07e..22b00d01b8edae4999213205b43c759e0e1bdf10)*

2025-08-30 00:18 UTC, tgross35 commented on tests/ui/lint/improper_ctypes/lint-113436-1.rs
Nit for commit 1 "move code and tests into proper directories": the directory should be `improper-ctypes` (underscores usually turn into hyphens for prose, and we use that form for tests)

2025-08-30 00:18 UTC, tgross35 commented on compiler/rustc_lint/src/foreign_modules.rs
Nit for commit 2 "more pre-emptive cleanup": this looks good to me, but could you update the commit description to say what this cleanup does / why it does it? Specifically why we don't need the `&& matches!(mode, CItemKind::Definition) ` bit.

2025-08-30 00:18 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +mod CTypesVisitorStateFlags {
From commit 4 "redo state tracking"

[`bitflags`](https://docs.rs/bitflags/latest/bitflags/) is in the graph already so you may as well use it here. Since it's a workspace dep, `bitflags.workspace = true` in `compiler/rustc_lint/Cargo.toml` should work. I don't think the separate enum and flags is needed in that case, you'll e.g .be able to `impl CTypesVisitorState { const ARG_TY_IN_DEFINITION: Self = Self::FUNC | Self::DEFINED }`.

If this is kept as a module, it would be preferable to keep the snake case convention (`use CTypesVisitorStateFlags::*` looks unusual). Or just put these in an `impl CTypesVisitorState` block.

2025-08-30 00:18 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    fn is_in_fnptr(self) -> bool {
Nit: doc comments are prose, with capital letters and periods at the end of sentences (applies quite a few places in this commit and across others). Obviously this isn't critical.

2025-08-30 00:18 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +#[allow(unused)] // TODO
Nit: prefer `expect(unused)` to enforce that they get removed once actually used

2025-08-30 00:18 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +mod CTypesVisitorStateFlags {
Also if you're looking to shorten the name up a bit, `VisitorState` is probably sufficient for the flag type since we're already in the `ctypes` module.

2025-08-30 00:18 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +            };
This is repeated in a number of places. Maybe add a function `CTypesVisitorState::from_fn_mode`?

2025-08-30 00:18 UTC, tgross35 commented on tests/ui/lint/improper_ctypes/allow_improper_ctypes.rs
Nit on one of the last commits "add tests": it would be awesome to move this commit to the beginning, basically with a bunch of FIXMEs where the behavior is wrong, then update the test output after each commit so we can see how the behavior changes. That can be tricky though, so don't worry too much if this isn't easily doable.

I think you did do this for a handful of the other tests.

2025-08-30 00:18 UTC, tgross35 commented on tests/ui/lint/improper_ctypes/allow_improper_ctypes.rs
> +#[allow(improper_c_callbacks)]
Use `expect` rather than `allow` so we know for sure when the lint is being fired

2025-08-30 00:18 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
On commit "add recursion limit": is it possible to move this commit up by one, before "splitting definitions in two"? Or is this not needed until the splitting commit?

The reason I am asking is that I think it may be reasonable to split the first 5-6 commits to a separate PR to help slim this one down, since they don't include any user-visible changes (don't do that just yet). It would be nice to have the recursion fix able to stand alone from the rest as well.

2025-08-30 19:51 UTC, niacdoial commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    fn is_in_fnptr(self) -> bool {
Not sure I got all of them, but I did change that

2025-08-30 19:53 UTC, niacdoial commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +mod CTypesVisitorStateFlags {
Did this, the only issue is that I had to work around the `bitwise_or` operator (for this type) not being available in const contexts.

2025-08-30 20:00 UTC, niacdoial commented on tests/ui/lint/improper_ctypes/allow_improper_ctypes.rs
the three tests there don't really add anything interesting to see the evolution of, IMHO.
- one is to see where `#[allow(improper_c*)]` is effective (it's not that great but usable)
- one is to enshrine that other issue I fixed without meaning to
- and the last is a more extensive version of the test put in place after #134064, making sure all ty_kinds are covered behind indirections.

2025-08-30 20:06 UTC, niacdoial commented on tests/ui/lint/improper_ctypes/lint-113436-1.rs
fixed this near the end of the commit chain
(for some reason jj-vcs doesn't know how to propagate "rename this directory" across a commit's descendants, so fixing every commit downstream looked to be too tedious)

2025-09-03 17:32 UTC, tgross35 reviewed
It will take me a little while to get through everything, but here's feedback on the first ~4 commits

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/134697/0f506968010fa987b0d134034d0ccab9eecd9120..59de843f52624b7a6f4169e54521f982bdf9e9e6)*

2025-09-03 17:32 UTC, tgross35 commented on tests/ui/lint/improper_ctypes/lint-113436-1.rs
Oh hey, jj is the perfect tool for big PRs like this :)

Maybe worth asking on the discord? https://discord.gg/wgp7xptM

2025-09-03 17:32 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +declare_lint! {
_Commit "ImproperCTypes: move code and tests into proper directories"_: Nit, looks like the lint declarations got moved to the bottom of the file under everything for support? Usually lints are the other way around so you see the list as soon as you open the file (same usually for modules where there's one important/core type. I know this is a bit reversed from C)

2025-09-03 17:32 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        const ReturnTyInFnPtr = 0b010110; //Self::FUNC | Self::THEORETICAL | Self::FN_RETURN
_Commit "ImproperCTypes: redo state tracking":_ It's a bit clunky but you can do:

```rust
impl Foo {
    const ARG_TY_IN_DEF: Self = Self::from_bits(Self::FUNC.bits() | Self::DEFINED.bits()).unwrap();
}
```

https://docs.rs/bitflags/latest/bitflags/#multi-bit-flags does say that as-is should be okay though, so that bit is up to you (I'd have a mild preference to use `.bits()`/`from_bits()` to reduce the chance for mistakes as this gets updated). But some of these are only used in one location so it would be fine to inline them directly there.

In either case please change consts to the conventional upper snake case :)

2025-09-03 17:32 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        const ReturnTyInFnPtr = 0b010110; //Self::FUNC | Self::THEORETICAL | Self::FN_RETURN
Also for `None`, `VisitorState::empty()` can be used (it's `const`)

2025-09-03 17:32 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        }
```rust
        if ret {
            debug_assert!(self.is_in_function());
        }
```

Slightly simpler

2025-09-03 17:32 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        ret
Did this mean to be `debug_assert!` as well? (Probably doesn't really matter)

2025-09-03 17:32 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +            assert!((self & Self::STATIC) == Self::None);
Bitflags gives you some convenience methods to avoid the bitwise ops: these could be `self.contains(Self::FOO)` and `!self.contains(Self::STATIC)`.

Same for a handful of places below.

2025-09-03 17:32 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +                }
I think this could be eliminated or replaced with a comment since `visit_numeric` has the same `bug!`

2025-09-03 17:37 UTC, tgross35 commented on tests/ui/lint/improper_ctypes/lint-113436-1.rs
[`jj absorb`](https://jj-vcs.github.io/jj/latest/cli-reference/#jj-absorb) might be worth a try too. Though I don't know if it would be able to move all renames back to the original commit

2025-09-03 18:57 UTC, niacdoial commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +declare_lint! {
ok!
Should I also move, say, the ImproperCTypesLint struct/impl before the visitor class and other helper classes?
Or in general put the more important stuff (and/or the stuff that's connected to the outside code) near the start of the file?

2025-09-03 18:58 UTC, niacdoial commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        const ReturnTyInFnPtr = 0b010110; //Self::FUNC | Self::THEORETICAL | Self::FN_RETURN
...ok I should have spent more time in that crate's docs. thanks!

2025-09-03 18:59 UTC, niacdoial commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        }
...fair, the condition itself is probably optimised out when debug_assertions are off.

2025-09-03 19:09 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +declare_lint! {
In general, yeah I think helper structs/functions tend to go toward the end of the file in Rust so you get the bigger pictures first as you read from the top down. But don't bother changing any other than `declare_lint!`, no need to cause yourself a bunch of conflicts (and even moving declare_lint is 🤷‍♂️ if it's not easy to do).

Languages that require declaration before use tend to do this the other way around, but they also don't really have the choice (unless you forward declare absolutely everything). Took me a little while to get used to the reverse :)

2025-09-03 19:09 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        const ReturnTyInFnPtr = 0b010110; //Self::FUNC | Self::THEORETICAL | Self::FN_RETURN
To be fair, I think the docs could be a bit better - took me some trial and error to figure that out 😆

2025-09-03 19:16 UTC, niacdoial commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        ret
my reasoning was:
the main difference is that there is a value assigned that is neither STATIC nor FUNCTION (`None`, which will be assigned in a later commit)
so, the `debug_assert!` only needs to ensure that non of the `VisitorState` values are broken, while the `assert!` acts as a `bug!` to guard that `None` from getting in the wrong piece of logic.

2025-09-03 19:17 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        }
If you're curious, dead blocks are usually pruned at any nonzero optimization level by the first CSE (common sub-expression) pass https://rust.godbolt.org/z/GPbY9zEbj

2025-09-03 19:19 UTC, niacdoial commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +                }
fair!
one, sort of unrelated question. Should I fix-and-push what you point out as soon as possible, or should I wait you to tell me the review is complete?

2025-09-03 19:25 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        ret
In that case, it's somewhat preferred to use `bug!` directly since they show nicer ICE messages (a bit more about that at https://github.com/rust-lang/rust/blob/fd75a9c32d643f39c8c61df770d2cff60b3fefd5/compiler/rustc_middle/src/macros.rs#L1-L13)

```rust
if is_ret && self.contains(Self::STATIC) {
    bug!(...)
}
```

2025-09-03 19:31 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +                }
I'd suggest amending the history as you fix things (thanks `jj` for making this a bit easier) and push whenever you're at a reasonable chunk point. That gives me a chance to mark some of these discussion items as resolved and check off more commits in my list at the top post before I'm 100% through everything. Also less review churn since the later commits will be closer to their final form.

2025-09-05 05:10 UTC, tgross35 requested changes
Review for commit "ImproperCTypes: re-separate linting and checking"

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/134697/0f506968010fa987b0d134034d0ccab9eecd9120..59de843f52624b7a6f4169e54521f982bdf9e9e6)*

2025-09-05 05:10 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
>      }
_Commit "re-separate linting and checking"_: This pattern doesn't seem quite right; the type not being an array of course doesn't mean the type is FFI-safe. Could this and similar functions instead return an `Option<FfiResult>`? And only return `Some(FfiResult::FfiSafe)` when it is known to be safe.

Maybe good to document this with an alias:

```rust
/// The result when a type has been checked but perhaps not completely. `None` indicates that
/// FFI safety/unsafety has not yet been determined, `Some(res)` indicates that the safety/unsafety
/// in the `FfiResult` is final.
type PartialFfiResult<'tcx> = Option<FfiResult<'tcx>>;
```

An alternative is to add an `FfiResult::Unknown` variant and return that, but I don't think that's worth propagating.

2025-09-05 05:10 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    fn visit_for_opaque_ty(&mut self, ty: Ty<'tcx>) -> FfiResult<'tcx> {
Commit "re-separate linting and checking": Similar here, I think this could return `None` rather than `FfiSafe`

2025-09-05 05:10 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    ) -> FfiResult<'tcx> {
Commit "re-separate linting and checking": could you add a doc comment for this function? Also if it's only checking a single type, `check_type` is probably a better name.

I think this is where it makes sense to return `FfiResult<'tcx>` (as you have), where something is known to either be FFI-safe or unsafe.

2025-09-05 05:10 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    /// that need to be checked for ffi-safety.
`For a function that doesn't need to be "ffi-safe"` -> `For a function that may not need to be "ffi-safe"` since this is used for all functions right?

2025-09-05 05:10 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    fn check_arg_for_power_alignment(&mut self, ty: Ty<'tcx>) -> bool {
Could you add a doc comment?

2025-09-05 05:10 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    fn check_type_for_external_abi_fnptr(
Is this doc comment accurate? It looks like there is no return type here, and that it checks/emits them rather than returning the inner type

2025-09-05 05:10 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        });
Nit: flip to `for (fn_ptr_ty, span) in all_types` rather than `for_each` (makes it easier to spot loops)

2025-09-05 05:26 UTC, tgross35 commented
Once you address the comments here, could you add a bookmark/branch at the fourth commit "redo state tracking" and put that into a separate PR? I think up to that point should be fine to merge now, which cuts down on the rest here. Request me for review once you do so.

Since you're using jj and it's easy to have multiple bookmarks, I think "split type visiting into subfunctions" and "add recursion limit" would also be good revs to put into separate PRs to merge before the rest (just mark them as draft)

2025-09-05 22:36 UTC, niacdoial commented on compiler/rustc_lint/src/types/improper_ctypes.rs
>      }
hm... actually, it probably shouldn't be a new function at all (your call), since it's going to go away eventually (I... somehow blindly reproduced this from how stuff actually changed overtime, since I didn't consider it "an experiment that was rolled back")

2025-09-05 22:52 UTC, niacdoial commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +    /// that need to be checked for ffi-safety.
not yet, but it will in a later commit in this chain.
I'm using a different phrasing:
`Regardless of a function's need to be "ffi-safe", `

2025-09-05 23:15 UTC, niacdoial commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +        ret
turns out I misremembered something, so er...
both get debug_assert now.

2025-09-06 12:21 UTC, niacdoial commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +                    });
oh, I might be too eager on this, but I wonder if I actually found a bug in rustc's internals, or if I'm holding this API wrong.
the commented-out code used to work 4 months ago

2025-09-06 12:42 UTC, rust-log-analyzer commented
The job **`tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/17514581736/job/49750504085) [(plain enhanced)](https://triage.rust-lang.org/gha-logs/rust-lang/rust/49750504085) [(plain)](https://github.com/rust-lang/rust/commit/63702ef0cc07bf29437a52a24075709b666d3dca/checks/49750504085/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Caused by:
  failed to parse manifest at `/checkout/compiler/rustc_lint/Cargo.toml`

Caused by:
  error inheriting `bitflags` from workspace root manifest's `workspace.dependencies.bitflags`

Caused by:
  `workspace.dependencies` was not defined
Command `/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo metadata --format-version 1 --no-deps --manifest-path /checkout/Cargo.toml` failed with exit code 101
Created at: src/bootstrap/src/core/metadata.rs:80:25
Executed at: src/bootstrap/src/core/metadata.rs:91:54

--- STDOUT vvv


Command has failed. Rerun with -v to see more details.
Bootstrap failed while executing `build --stage 2 --dry-run`
Build completed unsuccessfully in 0:00:36
make: *** [Makefile:99: prepare] Error 1
Command failed. Attempt 2/5:
##[group]Building bootstrap
---
Caused by:
  failed to parse manifest at `/checkout/compiler/rustc_lint/Cargo.toml`

Caused by:
  error inheriting `bitflags` from workspace root manifest's `workspace.dependencies.bitflags`

Caused by:
  `workspace.dependencies` was not defined
Command `/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo metadata --format-version 1 --no-deps --manifest-path /checkout/Cargo.toml` failed with exit code 101
Created at: src/bootstrap/src/core/metadata.rs:80:25
Executed at: src/bootstrap/src/core/metadata.rs:91:54

--- STDOUT vvv


Command has failed. Rerun with -v to see more details.
Bootstrap failed while executing `build --stage 2 --dry-run`
Build completed unsuccessfully in 0:00:00
make: *** [Makefile:99: prepare] Error 1
Command failed. Attempt 3/5:
##[group]Building bootstrap
---
Caused by:
  failed to parse manifest at `/checkout/compiler/rustc_lint/Cargo.toml`

Caused by:
  error inheriting `bitflags` from workspace root manifest's `workspace.dependencies.bitflags`

Caused by:
  `workspace.dependencies` was not defined
Bootstrap failed while executing `build --stage 2 --dry-run`
Command `/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo metadata --format-version 1 --no-deps --manifest-path /checkout/Cargo.toml` failed with exit code 101
Created at: src/bootstrap/src/core/metadata.rs:80:25
Executed at: src/bootstrap/src/core/metadata.rs:91:54

--- STDOUT vvv


Command has failed. Rerun with -v to see more details.
Build completed unsuccessfully in 0:00:00
make: *** [Makefile:99: prepare] Error 1
Command failed. Attempt 4/5:
##[group]Building bootstrap
    Finished `dev` profile [unoptimized] target(s) in 0.05s
---
Caused by:
  failed to parse manifest at `/checkout/compiler/rustc_lint/Cargo.toml`

Caused by:
  error inheriting `bitflags` from workspace root manifest's `workspace.dependencies.bitflags`

Caused by:
  `workspace.dependencies` was not defined
Bootstrap failed while executing `build --stage 2 --dry-run`
Command `/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo metadata --format-version 1 --no-deps --manifest-path /checkout/Cargo.toml` failed with exit code 101
Created at: src/bootstrap/src/core/metadata.rs:80:25
Executed at: src/bootstrap/src/core/metadata.rs:91:54

--- STDOUT vvv


Command has failed. Rerun with -v to see more details.
Build completed unsuccessfully in 0:00:00
make: *** [Makefile:99: prepare] Error 1
Command failed. Attempt 5/5:
##[group]Building bootstrap
    Finished `dev` profile [unoptimized] target(s) in 0.04s
---
Caused by:
  failed to parse manifest at `/checkout/compiler/rustc_lint/Cargo.toml`

Caused by:
  error inheriting `bitflags` from workspace root manifest's `workspace.dependencies.bitflags`

Caused by:
  `workspace.dependencies` was not defined
Bootstrap failed while executing `build --stage 2 --dry-run`
Command `/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo metadata --format-version 1 --no-deps --manifest-path /checkout/Cargo.toml` failed with exit code 101
Created at: src/bootstrap/src/core/metadata.rs:80:25
Executed at: src/bootstrap/src/core/metadata.rs:91:54

--- STDOUT vvv


Command has failed. Rerun with -v to see more details.
Build completed unsuccessfully in 0:00:00
make: *** [Makefile:99: prepare] Error 1
The command has failed after 5 attempts.
  local time: Sat Sep  6 12:42:00 UTC 2025
  network time: Sat, 06 Sep 2025 12:42:00 GMT
```

</details>

2025-09-06 15:41 UTC, niacdoial commented
Also also, if some of these intermediate pull requests will be merges individually, there's a change I might or might not want to make, but I'ld like to discuss it (or at least give you the "why" of it) outside of a publically-readable place? If that's not a problem to do that.

2025-09-06 18:00 UTC, tgross35 commented
> Also also, if some of these intermediate pull requests will be merges individually, there's a change I might or might not want to make, but I'ld like to discuss it (or at least give you the "why" of it) outside of a publically-readable place? If that's not a problem to do that.

If you mean just doing some designing/architecting outside of this PR thread, the t-compiler channel at https://rust-lang.zulipchat.com/ is the place to do it. If you actually have trade secrets that you can't reveal to the public, I guess you can DM me there too? 😄

2025-09-07 07:07 UTC, tgross35 reviewed
Commit "splitting definitions lint into two": I see the effects from the docs, but what exactly is the motivation here?

Adding/removing lints and groups is a pretty big change and more people need to get involved with the decision (e.g. the Lang team). I could kind of see users wanting to allow callbacks that aren't C-safe without enabling the rest of `improper_ctypes_definitions`, but this seems pretty niche.

If you feel strongly that the lint groups should be split, my recommendation would be to discuss it on Zulip first, then put up a PR doing the change separate from all the fixes. Dropping it from this patchset means the very useful fixes here won't be blocked on a team decision.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/134697/0d0f4eac8b98133e5da6d3604d86a8f3b5a67844..6868634d75ea2f585e28a8fc0d035d7c1e033adc)*

2025-09-07 07:55 UTC, tgross35 reviewed
Review for "change cstr linting"

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/134697/0d0f4eac8b98133e5da6d3604d86a8f3b5a67844..6868634d75ea2f585e28a8fc0d035d7c1e033adc)*

2025-09-07 07:55 UTC, tgross35 commented on compiler/rustc_lint/messages.ftl
> +    and use (depending on the use case) `CStr::as_ptr()`, `CString::into_raw()` then `CString::from_raw()`, or a dedicated buffer
This is a bit too much info for diagnostics. Recommendations:

1. Saying "... instead, and converting to a `{cstr_or_cstring}` as needed` is sufficient. There is no need to spell out as_ptr/into_raw/from_raw/etc, the users have to read the API docs anyway.
2. Drop "or a dedicated buffer"; we're just giving a hint, there are of course alternatives
3. Drop the comment about `libc::free`. We cover that in `CString::{from,into}_raw` docs
4. "consider passing a `*const std::ffi::c_char` or `*mut std::ffi::c_char` instead" -> "consider passing a `*mut std::ffi::c_char` instead". We just need to make a best guess, the user can adapt if they don't need the mutability

2025-09-07 07:55 UTC, tgross35 commented on compiler/rustc_lint/messages.ftl
> +    and use (depending on the use case) `CStr::as_ptr()`, `CString::into_raw()` then `CString::from_raw()`, or a dedicated buffer
Second review for this bit: use parameters so the whole string doesn't need to be duplicated, e.g. the four variants here can be covered by filling in `mut`/`const`/`CStr`/`CString`

```fluent
lint_improper_ctypes_cstr_help = consider passing a `*{mut_or_const} std::ffi::c_char` instead, and converting to a `{cstr_or_cstring}` as needed
```

Ideally, do this by adding a new enum to  `lints.rs` to help keep the diagnostics more structured. This should make the rest easier too.

```rust
pub(crate) struct ImproperCTypes<'a> {
    // ...
    pub help_enum: Option<ImproperCTypesHelp>,
    // ...
}

enum ImproperCTypesHelp {
    CStrings {
        mut_or_const: &'static str,
        cstr_or_cstring: &'static str,
    }
}

impl<'a> LintDiagnostic<'a, ()> for ImproperCTypes<'_> {
    fn decorate_lint<'b>(self, diag: &'b mut Diag<'a, ()>) {
        // ...
        if let Some(help) = self.help_enum {
            debug_assert!(self.help.is_none(), "if enum help is provided, the help string isn't used");
            match help {
                CStrings { /* ... */ } => {
                    diag.help(fluent::lint_improper_ctypes_cstr_help);
                    // set `diag.arg(...)` for the mut & cstr strings
                }
            }
        }
    }
}
```

2025-09-07 07:55 UTC, tgross35 commented on compiler/rustc_lint/messages.ftl
> +lint_improper_ctypes_unsized_ref = this reference to an unsized type contains metadata, which makes it incompatible with a C pointer
These could probably be combined to a single message like: "pointer types are only FFI-compatible if their pointee is `Sized`".

Also since these are for a note field, include `_note` in the fluent name

2025-09-07 08:14 UTC, tgross35 commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +fn get_type_sizedness<'tcx, 'a>(cx: &'a LateContext<'tcx>, ty: Ty<'tcx>) -> TypeSizedness {
Commit "change handling of indirections": Does the [`adt_sizedness_constraint` query](https://github.com/rust-lang/rust/blob/ebdf2abea4b46fcbba959eee1207c979c77dc95c/compiler/rustc_middle/src/query/mod.rs#L930-L934) give you what is needed here? The logic exists somewhere in the compiler, I think it should be possible to avoid reimplementing here. Probably worth a question at [#t-compiler/help](https://rust-lang.zulipchat.com/#narrow/channel/182449-t-compiler.2Fhelp).

Since https://github.com/rust-lang/rust/pull/137944 and https://github.com/rust-lang/rfcs/pull/3729 for a sketch of what that query detects.

2025-09-21 15:47 UTC, niacdoial commented on compiler/rustc_lint/src/types/improper_ctypes.rs
> +fn get_type_sizedness<'tcx, 'a>(cx: &'a LateContext<'tcx>, ty: Ty<'tcx>) -> TypeSizedness {
I just looked and...
- I can and will definitely use this query to shorten/accelerate/make `get_type_sizedness` more robust[?].
- It would be more useful if `rustc_ty_utils/src/ty.rs` exposed `sizedness_constraint_for_ty()`. As it stands, that query can only be called for structs (not even all ADTs, as the name would suggest).
- Even then, I would have to add some processing of my own, to distinguish `UnsizedWithExternType` (that RFC's `Pointee` types) and `NotYetKnown`.

2026-08-02 21:48 UTC, niacdoial commented
...right.
Now that all the "refactoring" half of this PR has been split off and merged, I'll be closing this and opening a new PR to remove clutter.

2026-08-02 21:48 UTC, closed without merging