Add mips-zkm-zkvm-elf triple
rust-lang/rust pull request #134721
Opened 2024-12-24 10:41 UTC by eigmax

2024-12-24 10:50 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12480624328/job/34831758889) [(plain)](https://github.com/rust-lang/rust/commit/459d1cf0f68d1fb729eee6ab17146c8f22ba515a/checks/34831758889/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#13 2.796 Building wheels for collected packages: reuse
#13 2.797   Building wheel for reuse (pyproject.toml): started
#13 3.045   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 3.046   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132720 sha256=026f3bb0f1aa8090b861fd0a0939cb1a782396d84c8aab7875096557d637a0f6
#13 3.046   Stored in directory: /tmp/pip-ephem-wheel-cache-3203c8zj/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#13 3.049 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#13 3.482 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#13 3.482 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 4.047 Collecting virtualenv
#13 4.047 Collecting virtualenv
#13 4.087   Downloading virtualenv-20.28.0-py3-none-any.whl (4.3 MB)
#13 4.173      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 51.2 MB/s eta 0:00:00
#13 4.227 Collecting platformdirs<5,>=3.9.1
#13 4.232   Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
#13 4.250 Collecting distlib<1,>=0.3.7
#13 4.263      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 74.5 MB/s eta 0:00:00
#13 4.299 Collecting filelock<4,>=3.12.2
#13 4.304   Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
#13 4.304   Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
#13 4.385 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 4.572 Successfully installed distlib-0.3.9 filelock-3.16.1 platformdirs-4.3.6 virtualenv-20.28.0
#13 DONE 4.7s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      120768 kB
DirectMap2M:     6170624 kB
DirectMap1G:    12582912 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.04s
##[endgroup]
WARN: currently no CI rustc builds have rustc debug assertions enabled. Please either set `rust.debug-assertions` to `false` if you want to use download CI rustc or set `rust.download-rustc` to `false`.
downloading https://static.rust-lang.org/dist/2024-11-27/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz
---
##[endgroup]
fmt check
fmt: checked 5743 files
tidy check
tidy error: tests/assembly/targets/: missing assembly test for mips_zkm_zkvm_elf
removing old virtual environment
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (24.3.1)
All checks passed!
checking C++ file formatting
some tidy checks failed
some tidy checks failed
Command has failed. Rerun with -v to see more details.
  local time: Tue Dec 24 10:50:43 UTC 2024
  network time: Tue, 24 Dec 2024 10:50:43 GMT
##[error]Process completed with exit code 1.
Post job cleanup.
```

</details>

2024-12-24 11:15 UTC, taiki-e commented on compiler/rustc_target/src/spec/targets/mips_zkm_zkvm_elf.rs
> +            // atomics if the target name is not in a hardcoded list.
Btw, as for crossbeam, this issue was already resolved over a year ago. https://github.com/crossbeam-rs/crossbeam/issues/1033

2024-12-24 14:08 UTC, jieyouxu commented
Hi @eigmax, thanks for the PR. Note that this PR (adding a new Tier 3 target) may take a bit of time (at least until the holiday is over), as many T-compiler team members will be on holiday and won't have an opportunity to register any concerns if they would have any.

Additionally, I am going to request that you open an [MCP](https://forge.rust-lang.org/compiler/mcp.html) at https://github.com/rust-lang/compiler-team/issues for adding this as a Tier 3 target (due to holiday + this will need clarifications on the platform support docs and conformance with [Target Tier Policy](https://doc.rust-lang.org/rustc/target-tier-policy.html) anyway). You can take a look at e.g.:

- https://github.com/rust-lang/rust/pull/130750
- https://github.com/rust-lang/rust/pull/131487

2024-12-24 14:38 UTC, jieyouxu requested changes
Thanks for the PR. Before this target can be accepted, this PR will need two things:

1. Can you please also add [platform support docs](https://doc.rust-lang.org/rustc/platform-support/TEMPLATE.html) for this Tier 3 target?
    - You can take a look at e.g. https://github.com/rust-lang/rust/pull/130750/files#diff-bc17631f04294210bbf39b6bcac37f5158feeba4e2efcfb59de8be96a1a572a6.
2. Please also confirm that the target conforms with the Tier 3 target policy, as described in [Adding a new target](https://doc.rust-lang.org/rustc/target-tier-policy.html#adding-a-new-target).
    - For example, see https://github.com/rust-lang/rust/pull/130614#issue-2538835974.

2024-12-24 15:18 UTC, saethlin commented
> EDIT: nevermind, I thought we didn't have any zKVM-related targets, but we apparently do.

It is not at all clear to me (as a compiler maintainer who just tried to use Google to learn about zkvm) that these two uses of the term "zkvm" are referring to the same thing. It would be rather bad if they are not, so I would like some step taken to prevent/clarify problems here.

2024-12-24 15:37 UTC, eigmax commented
@saethlin there is one already. https://doc.rust-lang.org/rustc/platform-support/riscv32im-risc0-zkvm-elf.html 

@jieyouxu thanks! I will follow the instruction and add the docs.

2024-12-24 16:12 UTC, eigmax commented
> I have read that. It is not clear to me, based on the terminology and authorship of this PR that these two things called "zkvm" are affiliated with each other, or are referring to a generic concept that they both agree they do not own.

Good question. you are right, zkVM is a general concept that representing it can generate the validity proof (I would use this instead of zero knowledge proof for easier understanding) for some instruction set.  For RISC0, it builds a zkVM for RV32, and for zkMIPS, we build a zkVM for MIPS32R2.  More generally speaking, there is some other impls, like zkWASM, or custom instruction set, like [Miden](https://github.com/0xPolygonMiden/miden-vm). 

For your concern,  should dev be aware of different zkVMs? I think we should due to:
1) It's obvious that different apps may be built for different architecture, like MIPS or RV,  and the validity proof should constrain the specific function and logic on specific architecture.  
2) The original idea we build the zkMIPS is that MIPS is already used to build the [Fraud Proof VM](https://docs.optimism.io/stack/fault-proofs/mips) by some blockchain projects, like Optimism.  And zkMIPS can help those projects to solve their [long finality time issue](https://www.metis.io/blog/introducing-hybrid-rollups).

2024-12-25 02:44 UTC, workingjubilee commented
@eigmax Does "zkvm" actually have a specific meaning with regards to these targets that they all uniformly share, or are they allowed to have entirely different ZK proof implementations? Do they share a syscall standard or some other abstract interface? Why does "zkvm" matter for the target's name?

To put it another way, if tomorrow Apple decided to make their entire Darwin OS run on a ZKVM, would we want to rename all the Apple targets to `-zkvm-`, or would this fact be largely unimportant from the perspective of merely compiling software for the target?

2024-12-25 02:51 UTC, workingjubilee commented
cc @flaub @jbruestle @SchmErik Can you explain your perspective on the matter of using "zkvm" as an "OS" for two targets that don't seem to obviously share an OS interface?

2024-12-25 02:56 UTC, workingjubilee commented on tests/assembly/targets/targets-elf.rs
> +//@ [mips_unknown_linux_uclibc] needs-llvm-components: mips
You copied the revision name, this is incorrect.

2024-12-25 13:39 UTC, qethu commented
> @eigmax Does "zkvm" actually have a specific meaning with regards to these targets that they all uniformly share, or are they allowed to have entirely different ZK proof implementations? Do they share a syscall standard or some other abstract interface? Why does "zkvm" matter for the target's name?
> 
> To put it another way, if tomorrow Apple decided to make their entire Darwin OS run on a ZKVM, would we want to rename all the Apple targets to `{arch}-apple-darwin-zkvm` and so on, or would this fact be largely unimportant from the perspective of merely compiling software for the target?

I suspect that the OS section is useful here, is that the ZK may be some different with BareMetal embedded software developing.
Such as it can set main as the entrance of the ELF file.

2024-12-25 13:44 UTC, qethu commented
> cc @flaub @jbruestle @SchmErik Can you explain your perspective on the matter of using `target_os = "zkvm"` for two targets that don't seem to obviously share an OS interface?

I guess that there may be a case that, a same app can be useful for both baremetal embedded hardware and zKVM emulator.
The 2 platform may be quite different, such as the code to initialize the hardware is not needed by zKVM;
and the entrance can be `main` (or other pure Rust code) on zKVM.

2024-12-25 18:54 UTC, workingjubilee commented
Would that mean `cfg(target_os = "zkvm")` would be useless in terms of selecting the correct behavior, because there would be no consistent handling between these two "OS"?

I do not think it is appropriate to introduce future possibilities about "what if we make `fn main()` work on this bare metal target?" right now. The more important future possibility is what if one of these targets _does_ and the other one _doesn't_, for _any_ given behavior?

2024-12-25 19:03 UTC, workingjubilee commented
In general, code compiled for "bare metal" targets does not necessarily have code to initialize hardware. Case in point: `wasm32v1-none` is *also* a bare metal target and *also* is a VM.

2024-12-26 12:16 UTC, eigmax commented
> Would that mean `cfg(target_os = "zkvm")` would be useless in terms of selecting the correct behavior, because there would be no consistent handling between these two "OS"?
> 
> I do not think it is appropriate to introduce future possibilities about "what if we make `fn main()` work on this bare metal target?" right now. The more important future possibility is what if one of these targets _does_ and the other one _doesn't_, for _any_ given behavior?

The cfg is useful. When it runs on zkVM, the IO and some libraries it can use are different (like Math), it requires `no_std` basically.  if it runs on non-zkVM(host mode), there is no limitation.  When we generate a proof, we first run it on host mode to calculate its output,  and then run it on guest mode with program's input and output via a special IO channel, where the output is to check the correctness of the result.

2024-12-27 02:14 UTC, workingjubilee commented
@eigmax 
> The cfg is useful. When it runs on zkVM, the IO and some libraries it can use are different (like Math), it requires no_std basically. if it runs on non-zkVM(host mode), there is no limitation. When we generate a proof, we first run it on host mode to calculate its output, and then run it on guest mode with program's input and output via a special IO channel, where the output is to check the correctness of the result.

Will the IO and libraries between mis-zkm-zkvm-elf be the same as the ones of riscv32im-risc0-zkvm-elf, or are they allowed to be different?

2024-12-27 02:39 UTC, eigmax commented
It's not same, we used different syscall(RV vs MIPS) to read and write data stream between the host and guest program, for the libraries, it's can be same, but not now. When saying a zkVM, it's basically an OS with a proof system. The proof systems are totally different from each others.

2024-12-27 03:55 UTC, saethlin commented
Just so we are all crystal clear, the existing zkvm target has these syscalls, which it uses yolo linkage to pick up: 
https://github.com/rust-lang/rust/blob/917bfa78478cbcc77406e5ea37b24c3eedefacf4/library/std/src/sys/pal/zkvm/abi.rs#L21
And it helpfully documents
```
    // Wrappers around syscalls provided by risc0-zkvm-platform:
```

If you want to say you are target_os=zkvm, you are agreeing that these are your syscalls too. Which I am completely confident they are not, because not only did you just say they are not, the existing risc0 zkvm target says they are specific to the risc0 zkvm.

It is my opinion that this PR should be rejected, and I would prefer that we delete the existing risc0 zkvm target. Both of these zkvms are just bare-metal runtimes. The std implementation that the risc0 zkvm target has is incomplete and panicky with no path to being a complete std implementation. Just like the much-hated/regretted wasm32-unknown-unknown.

2024-12-27 08:31 UTC, workingjubilee commented
@eigmax So at this point the main question I think we have is: Why shouldn't we just have a MIPS bare metal target? I mean, we might need another such target. But then you can build programs for that, and supply the API calls needed via a library, and we can talk if your target grows complicated enough that it actually supplies half of the stdlib.

2024-12-28 02:16 UTC, eigmax commented
@workingjubilee  yes, at least we need a mips target here, like `mips-mti-none-elf`.  

I believe it's not the time to import the a new zkVM OS, since there is not standard ABI.  I was confused by the merge of risc0's target.

2024-12-28 02:42 UTC, saethlin commented
> I was confused by the merge of risc0's target.

I am too. We'll sort this all out and keep you informed. It will take some time.

2024-12-28 05:58 UTC, workingjubilee commented
It looks like we have a mipsel-unknown-none target but not a mips-unknown-none target? I assume you want a big endian bare metal MIPS target, right, @eigmax? Yeah, that sounds fine.

2024-12-28 17:02 UTC, eigmax commented
> It looks like we have a mipsel-unknown-none target but not a mips-unknown-none target? I assume you want a big endian bare metal MIPS target, right, @eigmax? Yeah, that sounds fine.

Yes, that's the point.  Thanks!

2025-01-01 03:46 UTC, closed without merging

2025-01-08 23:08 UTC, SchmErik commented
> cc [@flaub](https://github.com/flaub) [@jbruestle](https://github.com/jbruestle) [@SchmErik](https://github.com/SchmErik) Can you explain your perspective on the matter of using 
> target_os = "zkvm" for two targets that don't seem to obviously share an OS interface?

Hi @workingjubilee  and @saethlin,

We were away for the holidays but now we are back. We’ve read the conversation on this thread and wanted to respond.

There have been zkVM’s before risc0’s but they have used a custom ISA. We are one of the first zkVMs to use an existing ISA and as we have gained more traction, many other implementations have popped up.

The whole intention of using `target_os = “zkvm”` is to be able to use this as `cfg` to modify the behavior of existing crates to use our accelerators. For instance, we have a sha256 accelerator in the risc0 zkvm that takes the cost of doing a SHA2 compression from several million cycles down to 73 cycles. In order to do this, we fork the sha2 crate and patch it using the `cfg` in order to call into our accelerators.

In hindsight, using `target_os = "zkvm"` was probably not the best option for the target triple because now it appears that we’re squatting on this `target_os` and that’s not fair or appropriate for other zkvm projects. Are there suggestions you have on making this better? Would using `target_vendor` be more appropriate here?

Having `std` support is important to us because it allows developers to use crates outside of `no_std`. This has enabled many others to use our target much more easily with existing crates. If our `std` implementation is imposing unnecessary hardship in maintenance, we’d love to work on solving these issues. We have in the past and will continue to address feedback when tagged on PR’s, report any issues we find, and to be good citizens of the ecosystem.

Thanks,
- Erik

cc @flaub and @jbruestle

2025-01-11 20:10 UTC, Noratrieb commented
I have created #135376 to summarize the discussion on RISC0 and nominated that instead to get the discussion out of this closed PR.