Look at proc-macro attributes when encountering unknown attribute
rust-lang/rust pull request #134841
Opened 2024-12-28 03:17 UTC by estebank

```
error: cannot find attribute `sede` in this scope
  --> $DIR/missing-derive-2.rs:22:7
   |
LL |     #[sede(untagged)]
   |       ^^^^
   |
help: the derive macros `Serialize` and `Deserialize` accept the similarly named `serde` attribute
   |
LL |     #[serde(untagged)]
   |       ~~~~~

error: cannot find attribute `serde` in this scope
  --> $DIR/missing-derive-2.rs:16:7
   |
LL |     #[serde(untagged)]
   |       ^^^^^
   |
note: `serde` is imported here, but it is a crate, not an attribute
  --> $DIR/missing-derive-2.rs:5:1
   |
LL | extern crate serde;
   | ^^^^^^^^^^^^^^^^^^^
help: `serde` is an attribute that can be used by the derive macros `Serialize` and `Deserialize`, you might be missing a `derive` attribute
   |
LL + #[derive(Serialize, Deserialize)]
LL | enum B {
   |
```

Partially address #47608.

2024-12-28 03:41 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12523296295/job/34932685877) [(plain)](https://github.com/rust-lang/rust/commit/3c8c8a81f5aa858476191cad6cae74c254a8fafd/checks/34932685877/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#21 exporting to docker image format
#21 sending tarball 29.2s done
#21 DONE 34.7s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---

586    |
587 help: `multipart_suggestion` is an attribute that can be used by the derive macro `Subdiagnostic`, you might be missing a `derive` attribute
588    |
- LL | #[derive(Subdiagnostic)]
+ LL + #[derive(Subdiagnostic)]
+ LL | struct MultipartSuggestion {
591 
592 error: cannot find attribute `multipart_suggestion` in this scope

597    |
597    |
598 help: `multipart_suggestion` is an attribute that can be used by the derive macro `Subdiagnostic`, you might be missing a `derive` attribute
599    |
- LL | #[derive(Subdiagnostic)]
+ LL + #[derive(Subdiagnostic)]
+ LL | struct MultipartSuggestion {
602 
603 error: cannot find attribute `multipart_suggestion` in this scope



The actual stderr differed from the expected stderr.
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args session-diagnostic/diagnostic-derive.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/session-diagnostic/diagnostic-derive" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers"
--- stderr -------------------------------
--- stderr -------------------------------
error: derive(Diagnostic): unsupported type attribute for diagnostic derive enum
   |
LL | #[diag(no_crate_example, code = E0123)]
   | ^


error: derive(Diagnostic): diagnostic slug not specified
   |
LL |     Foo,
   |     ^^^
   |
   |
   = help: specify the slug as the first argument to the `#[diag(...)]` attribute, such as `#[diag(hir_analysis_example_error)]`

error: derive(Diagnostic): diagnostic slug not specified
   |
LL |     Bar,
   |     ^^^
   |
   |
   = help: specify the slug as the first argument to the `#[diag(...)]` attribute, such as `#[diag(hir_analysis_example_error)]`

error: derive(Diagnostic): `#[nonsense(...)]` is not a valid attribute
   |
   |
LL | #[nonsense(no_crate_example, code = E0123)]


error: derive(Diagnostic): diagnostic slug not specified
   |
   |
LL | #[nonsense(no_crate_example, code = E0123)]
   |
   |
   = help: specify the slug as the first argument to the `#[diag(...)]` attribute, such as `#[diag(hir_analysis_example_error)]`

error: derive(Diagnostic): diagnostic slug not specified
   |
LL | #[diag(code = E0123)]
   | ^
   |
   |
   = help: specify the slug as the first argument to the `#[diag(...)]` attribute, such as `#[diag(hir_analysis_example_error)]`

error: derive(Diagnostic): diagnostic slug must be the first argument
   |
   |
LL | #[diag(nonsense("foo"), code = E0123, slug = "foo")]


error: derive(Diagnostic): diagnostic slug not specified
   |
   |
LL | #[diag(nonsense("foo"), code = E0123, slug = "foo")]
   |
   |
   = help: specify the slug as the first argument to the `#[diag(...)]` attribute, such as `#[diag(hir_analysis_example_error)]`
error: derive(Diagnostic): unknown argument
##[error]  --> /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:86:8
   |
   |
LL | #[diag(nonsense = "...", code = E0123, slug = "foo")]
   |
   = note: only the `code` parameter is valid after the slug


error: derive(Diagnostic): diagnostic slug not specified
   |
   |
LL | #[diag(nonsense = "...", code = E0123, slug = "foo")]
   |
   |
   = help: specify the slug as the first argument to the `#[diag(...)]` attribute, such as `#[diag(hir_analysis_example_error)]`
error: derive(Diagnostic): unknown argument
##[error]  --> /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:92:8
   |
   |
LL | #[diag(nonsense = 4, code = E0123, slug = "foo")]
   |
   = note: only the `code` parameter is valid after the slug


error: derive(Diagnostic): diagnostic slug not specified
   |
   |
LL | #[diag(nonsense = 4, code = E0123, slug = "foo")]
   |
   |
   = help: specify the slug as the first argument to the `#[diag(...)]` attribute, such as `#[diag(hir_analysis_example_error)]`
error: derive(Diagnostic): unknown argument
##[error]  --> /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:98:40
   |
   |
LL | #[diag(no_crate_example, code = E0123, slug = "foo")]
   |
   = note: only the `code` parameter is valid after the slug


error: derive(Diagnostic): `#[suggestion = ...]` is not a valid attribute
   |
   |
LL |     #[suggestion = "bar"]

error: derive(Diagnostic): attribute specified multiple times
##[error]  --> /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:112:8
   |
---

error: derive(Diagnostic): attribute specified multiple times
##[error]  --> /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:118:40
   |
LL | #[diag(no_crate_example, code = E0123, code = E0456)]
   |
note: previously specified here
  --> /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:118:26
   |
   |
LL | #[diag(no_crate_example, code = E0123, code = E0456)]


error: derive(Diagnostic): diagnostic slug must be the first argument
   |
LL | #[diag(no_crate_example, no_crate::example, code = E0123)]
   |                                           ^


error: derive(Diagnostic): diagnostic slug not specified
   |
   |
LL | struct KindNotProvided {} //~ ERROR diagnostic slug not specified
   |
   |
   = help: specify the slug as the first argument to the `#[diag(...)]` attribute, such as `#[diag(hir_analysis_exampl [...]

2024-12-28 05:02 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-18`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12523785986/job/34933678092) [(plain)](https://github.com/rust-lang/rust/commit/f88709b14ab3d7793f5864d57fe2c19a22658727/checks/34933678092/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#21 exporting to docker image format
#21 sending tarball 28.3s done
#21 DONE 33.8s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-18]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Starting the server...
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-18', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--enable-new-symbol-mangling']
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-18/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
diff of stderr:

587 help: `multipart_suggestion` is an attribute that can be used by the derive macro `Subdiagnostic`, you might be missing a `derive` attribute
588    |
589 LL + #[derive(Subdiagnostic)]
-    | struct MultipartSuggestion {
+ LL | struct MultipartSuggestion {
592 
593 error: cannot find attribute `multipart_suggestion` in this scope

599 help: `multipart_suggestion` is an attribute that can be used by the derive macro `Subdiagnostic`, you might be missing a `derive` attribute
599 help: `multipart_suggestion` is an attribute that can be used by the derive macro `Subdiagnostic`, you might be missing a `derive` attribute
600    |
601 LL + #[derive(Subdiagnostic)]
-    | struct MultipartSuggestion {
+ LL | struct MultipartSuggestion {
604 
605 error: cannot find attribute `multipart_suggestion` in this scope



The actual stderr differed from the expected stderr.
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args session-diagnostic/diagnostic-derive.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=x86_64-unknown-linux-gnu" "--check-cfg" "cfg(FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/session-diagnostic/diagnostic-derive" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers"
--- stderr -------------------------------
--- stderr -------------------------------
error: derive(Diagnostic): unsupported type attribute for diagnostic derive enum
   |
LL | #[diag(no_crate_example, code = E0123)]
   | ^


error: derive(Diagnostic): diagnostic slug not specified
   |
LL |     Foo,
   |     ^^^
   |
   |
   = help: specify the slug as the first argument to the `#[diag(...)]` attribute, such as `#[diag(hir_analysis_example_error)]`

error: derive(Diagnostic): diagnostic slug not specified
   |
LL |     Bar,
   |     ^^^
   |
   |
   = help: specify the slug as the first argument to the `#[diag(...)]` attribute, such as `#[diag(hir_analysis_example_error)]`

error: derive(Diagnostic): `#[nonsense(...)]` is not a valid attribute
   |
   |
LL | #[nonsense(no_crate_example, code = E0123)]


error: derive(Diagnostic): diagnostic slug not specified
   |
   |
LL | #[nonsense(no_crate_example, code = E0123)]
   |
   |
   = help: specify the slug as the first argument to the `#[diag(...)]` attribute, such as `#[diag(hir_analysis_example_error)]`

error: derive(Diagnostic): diagnostic slug not specified
   |
LL | #[diag(code = E0123)]
   | ^
   |
   |
   = help: specify the slug as the first argument to the `#[diag(...)]` attribute, such as `#[diag(hir_analysis_example_error)]`

error: derive(Diagnostic): diagnostic slug must be the first argument
   |
   |
LL | #[diag(nonsense("foo"), code = E0123, slug = "foo")]


error: derive(Diagnostic): diagnostic slug not specified
   |
   |
LL | #[diag(nonsense("foo"), code = E0123, slug = "foo")]
   |
   |
   = help: specify the slug as the first argument to the `#[diag(...)]` attribute, such as `#[diag(hir_analysis_example_error)]`
error: derive(Diagnostic): unknown argument
##[error]  --> /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:86:8
   |
   |
LL | #[diag(nonsense = "...", code = E0123, slug = "foo")]
   |
   = note: only the `code` parameter is valid after the slug


error: derive(Diagnostic): diagnostic slug not specified
   |
   |
LL | #[diag(nonsense = "...", code = E0123, slug = "foo")]
   |
   |
   = help: specify the slug as the first argument to the `#[diag(...)]` attribute, such as `#[diag(hir_analysis_example_error)]`
error: derive(Diagnostic): unknown argument
##[error]  --> /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:92:8
   |
   |
LL | #[diag(nonsense = 4, code = E0123, slug = "foo")]
   |
   = note: only the `code` parameter is valid after the slug


error: derive(Diagnostic): diagnostic slug not specified
   |
   |
LL | #[diag(nonsense = 4, code = E0123, slug = "foo")]
   |
   |
   = help: specify the slug as the first argument to the `#[diag(...)]` attribute, such as `#[diag(hir_analysis_example_error)]`
error: derive(Diagnostic): unknown argument
##[error]  --> /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:98:40
   |
   |
LL | #[diag(no_crate_example, code = E0123, slug = "foo")]
   |
   = note: only the `code` parameter is valid after the slug


error: derive(Diagnostic): `#[suggestion = ...]` is not a valid attribute
   |
   |
LL |     #[suggestion = "bar"]

error: derive(Diagnostic): attribute specified multiple times
##[error]  --> /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:112:8
   |
---

error: derive(Diagnostic): attribute specified multiple times
##[error]  --> /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:118:40
   |
LL | #[diag(no_crate_example, code = E0123, code = E0456)]
   |
note: previously specified here
  --> /checkout/tests/ui-fulldeps/session-diagnostic/diagnostic-derive.rs:118:26
   |
   |
LL | #[diag(no_crate_example, code = E0123, code = E0456)]


error: derive(Diagnostic): diagnostic slug must be the first argument
   |
LL | #[diag(no_crate_example, no_crate::example, code = E0123)]
   |                                           ^


error: derive(Diagnostic): diagnostic slug not specified
   |
   |
LL | struct KindNotProvided {} //~ ERROR diagnostic s [...]

2025-06-06 14:50 UTC, wesleywiser approved these changes

2025-06-06 14:50 UTC, wesleywiser commented on compiler/rustc_resolve/src/diagnostics.rs
> +            // We didn't find an exact match. Look for close matches. If any, suggest fixing typo.
Could you add a test for this case?

2025-06-06 15:11 UTC, estebank commented on compiler/rustc_resolve/src/diagnostics.rs
> +            // We didn't find an exact match. Look for close matches. If any, suggest fixing typo.
Isn't that tested by `tests/ui/macros/missing-derive-2.rs:22`?

2025-06-09 15:34 UTC, wesleywiser commented on compiler/rustc_resolve/src/diagnostics.rs
> +            // We didn't find an exact match. Look for close matches. If any, suggest fixing typo.
Missed the third test case there. Thanks!

2025-06-09 15:34 UTC, wesleywiser approved these changes

2025-06-09 15:34 UTC, wesleywiser commented
@bors r+ rollup

2025-06-09 19:31 UTC, estebank commented
@bors r=wesleywiser

2025-06-10 14:51 UTC, fmease commented
Failed in rollup: https://github.com/rust-lang/rust/pull/142290#issuecomment-2959558493
@bors r-

2025-06-10 14:53 UTC, fmease commented
I've only briefly looked at the failure but I see a list of something changing order depending on the target (failure here is on dist-i586-gnu-i586-i686-musl), so this is likely *query instability*, e.g., iterating over a HashMap.

2025-06-10 15:02 UTC, fmease requested changes

2025-06-10 15:02 UTC, fmease commented on compiler/rustc_resolve/src/diagnostics.rs
> +            all_attr_names.sort();
This doesn't do what you think it does and thus does actually result in query instability: The `Ord` impl for `Symbol` sorts by interning ID (which seems to be unstable). You instead want to sort by the string contents of the Symbol:

```suggestion
            all_attr_names.sort_by(|a, b| a.as_str().cmp(b.as_str()));
```

(pretty sure `sort_by_key` wouldn't work because the key wouldn't live long enough)

2025-06-10 15:03 UTC, fmease commented on compiler/rustc_resolve/src/diagnostics.rs
> +            all_attr_names.sort();
I don't actually know why we still have `Ord` impls for `Symbol`. IMO, we should have `impl !Ord for Symbol {} impl !PartialOrd for Symbol {}` but idk, maybe the query system or metadata encoding actually needs it to be Ord...

2025-06-10 15:08 UTC, fmease commented on compiler/rustc_resolve/src/diagnostics.rs
> +        let mut all_attrs: FxHashMap<Symbol, Vec<_>> = FxHashMap::default();
Tip: You could use `UnordMap` here to make it clear that you will never iterate over this list. `UnordMap` is literally just a wrapper around `FxHashMap` that prevents you from iterating over it.

2025-06-10 19:20 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-19`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/15568205176/job/43837496506) [(plain)](https://github.com/rust-lang/rust/commit/2e51aa6be18244c5fc98262a94013c88a2c751c6/checks/43837496506/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
#19 exporting to docker image format
#19 sending tarball 28.3s done
#19 DONE 32.7s
##[endgroup]
Setting extra environment values for docker:  --env ENABLE_GCC_CODEGEN=1 --env GCC_EXEC_PREFIX=/usr/lib/gcc/
[CI_JOB_NAME=x86_64-gnu-llvm-19]
[CI_JOB_NAME=x86_64-gnu-llvm-19]
debug: `DISABLE_CI_RUSTC_IF_INCOMPATIBLE` configured.
---
sccache: Listening on address 127.0.0.1:4226
##[group]Configure the build
configure: processing command line
configure: 
configure: build.configure-args := ['--build=x86_64-unknown-linux-gnu', '--llvm-root=/usr/lib/llvm-19', '--enable-llvm-link-shared', '--set', 'rust.randomize-layout=true', '--set', 'rust.thin-lto-import-instr-limit=10', '--set', 'build.print-step-timings', '--enable-verbose-tests', '--set', 'build.metrics', '--enable-verbose-configure', '--enable-sccache', '--disable-manage-submodules', '--enable-locked-deps', '--enable-cargo-native-static', '--set', 'rust.codegen-units-std=1', '--set', 'dist.compression-profile=balanced', '--dist-compression-formats=xz', '--set', 'rust.lld=false', '--disable-dist-src', '--release-channel=nightly', '--enable-debug-assertions', '--enable-overflow-checks', '--enable-llvm-assertions', '--set', 'rust.verify-llvm-ir', '--set', 'rust.codegen-backends=llvm,cranelift,gcc', '--set', 'llvm.static-libstdcpp', '--set', 'gcc.download-ci-gcc=true', '--enable-new-symbol-mangling']
configure: build.build          := x86_64-unknown-linux-gnu
configure: target.x86_64-unknown-linux-gnu.llvm-config := /usr/lib/llvm-19/bin/llvm-config
configure: llvm.link-shared     := True
configure: rust.randomize-layout := True
configure: rust.thin-lto-import-instr-limit := 10
---
   Compiling rustc-main v0.0.0 (/checkout/compiler/rustc)
error[E0308]: mismatched types
    --> compiler/rustc_resolve/src/diagnostics.rs:1671:55
     |
1671 |         let mut all_attrs: UnordMap<Symbol, Vec<_>> = FxHashMap::default();
     |                            ------------------------   ^^^^^^^^^^^^^^^^^^^^ expected `UnordMap<Symbol, Vec<_>>`, found `HashMap<_, _, FxBuildHasher>`
     |                            |
     |                            expected due to this
     |
     = note: expected struct `UnordMap<rustc_span::Symbol, Vec<_>>`
                found struct `HashMap<_, _, rustc_hash::FxBuildHasher>`

error[E0277]: the trait bound `Vec<Symbol>: From<UnordItems<Symbol, impl Iterator<Item = Symbol>>>` is not satisfied
    --> compiler/rustc_resolve/src/diagnostics.rs:1737:77
     |
1737 |             let mut all_attr_names: Vec<Symbol> = all_attrs.keys().cloned().collect();
     |                                                                             ^^^^^^^ unsatisfied trait bound
     |
     = help: the trait `From<UnordItems<rustc_span::Symbol, impl std::iter::Iterator<Item = rustc_span::Symbol>>>` is not implemented for `Vec<rustc_span::Symbol>`
     = help: the following other types implement trait `From<T>`:
               `Vec<T, A>` implements `From<BinaryHeap<T, A>>`
               `Vec<T, A>` implements `From<VecDeque<T, A>>`
               `Vec<T, A>` implements `From<std::boxed::Box<[T], A>>`
               `Vec<T>` implements `From<&[T; N]>`
               `Vec<T>` implements `From<&[T]>`
               `Vec<T>` implements `From<&mut [T; N]>`
               `Vec<T>` implements `From<&mut [T]>`
               `Vec<T>` implements `From<Cow<'_, [T]>>`
             and 6 others
note: required by a bound in `UnordItems::<T, I>::collect`
    --> /checkout/compiler/rustc_data_structures/src/unord.rs:109:23
     |
109  |     pub fn collect<C: From<UnordItems<T, I>>>(self) -> C {
     |                       ^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `UnordItems::<T, I>::collect`
     = note: the full name for the type has been written to '/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/rustc_resolve-ed0f5900a1f3f992.long-type-13901347189982689668.txt'
     = note: consider using `--verbose` to print the full type name to the console

Some errors have detailed explanations: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
[RUSTC-TIMING] rustc_resolve test:false 3.270
```

</details>

2025-06-10 23:47 UTC, estebank commented
@bors r=wesleywiser

2025-06-11 08:26 UTC, workingjubilee commented
seems it still has problems?

@bors r-

2025-06-11 08:26 UTC, workingjubilee commented
https://github.com/rust-lang/rust/pull/142333#issuecomment-2961586262

2025-06-11 08:46 UTC, workingjubilee commented
@bors rollup=iffy

2025-06-11 16:41 UTC, estebank commented
> seems it still has problems?

I think there's another `Vec<Symbol>::sort()` that needs to be `Vec<Symbol>::sort_by_key(|s| s.as_str())` in a different message :(

2025-06-11 19:07 UTC, estebank commented
@bors r=wesleywiser

2025-06-11 21:59 UTC, rust-log-analyzer commented
The job **`dist-i586-gnu-i586-i686-musl`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/15595424309/job/43924688452) [(plain)](https://github.com/rust-lang/rust/commit/b84566d02be02d27dc3bfe639fbbc82951a31f98/checks/43924688452/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
---- [ui] tests/ui/macros/missing-derive-1.rs stdout ----
Saved the actual stderr to `/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/macros/missing-derive-1/missing-derive-1.stderr`
diff of stderr:

38 LL |     #[sede(untagged)]
39    |       ^^^^
40    |
- help: the derive macros `Deserialize` and `Serialize` accept the similarly named `serde` attribute
+ help: the derive macros `Serialize` and `Deserialize` accept the similarly named `serde` attribute
42    |
---
To only update this specific test, also pass `--test-args macros/missing-derive-1.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/macros/missing-derive-1.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=i686-unknown-linux-musl" "--check-cfg" "cfg(test,FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/macros/missing-derive-1" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/i686-unknown-linux-musl/native/rust-test-helpers" "-Clinker=/musl-i686/bin/musl-gcc" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/macros/missing-derive-1/auxiliary"
stdout: none
--- stderr -------------------------------
error: cannot find attribute `serde` in this scope
##[error]  --> /checkout/tests/ui/macros/missing-derive-1.rs:8:3
   |
LL | #[serde(untagged)] //~ ERROR cannot find attribute `serde`
   |   ^^^^^
   |
note: `serde` is imported here, but it is a crate, not an attribute
  --> /checkout/tests/ui/macros/missing-derive-1.rs:5:1
   |
LL | extern crate serde;
   | ^^^^^^^^^^^^^^^^^^^
help: `serde` is an attribute that can be used by the derive macros `Deserialize` and `Serialize`, you might be missing a `derive` attribute
   |
LL + #[derive(Deserialize, Serialize)]
LL | enum A { //~ HELP `serde` is an attribute that can be used by the derive macros `Deserialize` and `Serialize`
   |

error: cannot find attribute `serde` in this scope
##[error]  --> /checkout/tests/ui/macros/missing-derive-1.rs:16:7
   |
LL |     #[serde(untagged)] //~ ERROR cannot find attribute `serde`
   |       ^^^^^
   |
note: `serde` is imported here, but it is a crate, not an attribute
  --> /checkout/tests/ui/macros/missing-derive-1.rs:5:1
   |
LL | extern crate serde;
   | ^^^^^^^^^^^^^^^^^^^
help: `serde` is an attribute that can be used by the derive macros `Deserialize` and `Serialize`, you might be missing a `derive` attribute
   |
LL + #[derive(Deserialize, Serialize)]
LL | enum B { //~ HELP `serde` is an attribute that can be used by the derive macros `Deserialize` and `Serialize`
   |

error: cannot find attribute `sede` in this scope
##[error]  --> /checkout/tests/ui/macros/missing-derive-1.rs:22:7
   |
LL |     #[sede(untagged)] //~ ERROR cannot find attribute `sede`
   |       ^^^^
   |
help: the derive macros `Serialize` and `Deserialize` accept the similarly named `serde` attribute
   |
LL |     #[serde(untagged)] //~ ERROR cannot find attribute `sede`
   |         +

error: aborting due to 3 previous errors
------------------------------------------


---- [ui] tests/ui/macros/missing-derive-2.rs stdout ----
Saved the actual stderr to `/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/macros/missing-derive-2/missing-derive-2.stderr`
diff of stderr:

4 LL |     #[sede(untagged)]
5    |       ^^^^
6    |
- help: the derive macros `Deserialize` and `Serialize` accept the similarly named `serde` attribute
+ help: the derive macros `Serialize` and `Deserialize` accept the similarly named `serde` attribute
8    |
---
To only update this specific test, also pass `--test-args macros/missing-derive-2.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: env -u RUSTC_LOG_COLOR RUSTC_ICE="0" RUST_BACKTRACE="short" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/tests/ui/macros/missing-derive-2.rs" "-Zthreads=1" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Z" "ignore-directory-in-diagnostics-source-blocks=/cargo" "-Z" "ignore-directory-in-diagnostics-source-blocks=/checkout/vendor" "--sysroot" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2" "--target=i686-unknown-linux-musl" "--check-cfg" "cfg(test,FALSE)" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zwrite-long-types-to-disk=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/macros/missing-derive-2" "-A" "unused" "-A" "internal_features" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/i686-unknown-linux-musl/native/rust-test-helpers" "-Clinker=/musl-i686/bin/musl-gcc" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/macros/missing-derive-2/auxiliary"
stdout: none
--- stderr -------------------------------
error: cannot find attribute `sede` in this scope
##[error]  --> /checkout/tests/ui/macros/missing-derive-2.rs:22:7
   |
LL |     #[sede(untagged)] //~ ERROR cannot find attribute `sede`
   |       ^^^^
   |
help: the derive macros `Serialize` and `Deserialize` accept the similarly named `serde` attribute
   |
LL |     #[serde(untagged)] //~ ERROR cannot find attribute `sede`
   |         +

error: cannot find attribute `serde` in this scope
##[error]  --> /checkout/tests/ui/macros/missing-derive-2.rs:16:7
   |
LL |     #[serde(untagged)] //~ ERROR cannot find attribute `serde`
   |       ^^^^^
   |
note: `serde` is imported here, but it is a crate, not an attribute
  --> /checkout/tests/ui/macros/missing-derive-2.rs:5:1
   |
LL | extern crate serde;
   | ^^^^^^^^^^^^^^^^^^^
help: `serde` is an attribute that can be used by the derive macros `Deserialize` and `Serialize`, you might be missing a `derive` attribute
   |
LL + #[derive(Deserialize, Serialize)]
LL | enum B { //~ HELP `serde` is an attribute that can be used by the derive macros `Deserialize` and `Serialize`
   |

error: cannot find attribute `serde` in this scope
##[error]  --> /checkout/tests/ui/macros/missing-derive-2.rs:8:3
   |
LL | #[serde(untagged)] //~ ERROR cannot find attribute `serde`
   |   ^^^^^
   |
note: `serde` is imported here, but it is a crate, not an attribute
  --> /checkout/tests/ui/macros/missing-derive-2.rs:5:1
   |
LL | extern crate serde;
   | ^^^^^^^^^^^^^^^^^^^
help: `serde` is an attribute that can be used by the derive macros `Deserialize` and `Serialize`, you might be missing a `derive` attribute
   |
LL + #[derive(Deserialize, Serialize)]
LL | enum A { //~ HELP `serde` is an attribute that can be used by the derive macros `Deserialize` and `Serialize`
   |

error: aborting due to 3 previous errors
------------------------------------------

```

</details>

2025-06-12 22:46 UTC, estebank commented
@bors r=wesleywiser

2025-06-14 01:58 UTC, merged

2025-06-14 03:47 UTC, rust-timer commented
Finished benchmarking commit (d087f112b7d1323446c7b39a8b616aee7fa56b3d): [comparison URL](https://perf.rust-lang.org/compare.html?start=8da623945f83933dd38644d5745532ee032e855b&end=d087f112b7d1323446c7b39a8b616aee7fa56b3d&stat=instructions:u).

### Overall result: ❌ regressions - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=8da623945f83933dd38644d5745532ee032e855b&end=d087f112b7d1323446c7b39a8b616aee7fa56b3d&stat=instructions:u)
Our most reliable metric. Used to determine the overall result above. However, even this metric can be noisy.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -    | -            | 0     |
| Regressions ❌ <br /> (secondary)  | 0.2% | [0.1%, 0.3%] | 3     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | -    | -            | 0     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=8da623945f83933dd38644d5745532ee032e855b&end=d087f112b7d1323446c7b39a8b616aee7fa56b3d&stat=max-rss)
<details>
<summary>Results (primary 2.1%, secondary 0.4%)</summary>

A less reliable metric. May be of interest, but not used to determine the overall result above.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 2.1%  | [2.1%, 2.1%]   | 1     |
| Regressions ❌ <br /> (secondary)  | 2.8%  | [2.4%, 3.3%]   | 4     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -2.7% | [-3.2%, -2.1%] | 3     |
| All ❌✅ (primary)                 | 2.1%  | [2.1%, 2.1%]   | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=8da623945f83933dd38644d5745532ee032e855b&end=d087f112b7d1323446c7b39a8b616aee7fa56b3d&stat=cycles:u)
<details>
<summary>Results (secondary -6.7%)</summary>

A less reliable metric. May be of interest, but not used to determine the overall result above.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | -     | -              | 0     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -     | -              | 0     |
| Improvements ✅ <br /> (secondary) | -6.7% | [-6.8%, -6.6%] | 3     |
| All ❌✅ (primary)                 | -     | -              | 0     |
</details>

### [Binary size](https://perf.rust-lang.org/compare.html?start=8da623945f83933dd38644d5745532ee032e855b&end=d087f112b7d1323446c7b39a8b616aee7fa56b3d&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 756.284s -> 757.156s (0.12%)
**Artifact size**: 372.34 MiB -> 372.29 MiB (-0.01%)