deny usage of FileCheck prefixes as revision names
rust-lang/rust pull request #134925
Opened 2024-12-30 16:31 UTC by DavisRayM

Adds a check that ensures special FileCheck prefixes are not used as revision names.

Fix #130982

2024-12-30 22:44 UTC, jieyouxu requested changes
Thanks for the PR. I left some initial feedback.

2024-12-30 22:44 UTC, jieyouxu commented on src/tools/compiletest/src/header.rs
> +                } else if FORBIDDEN_REVISION_NAMES.contains(&revision.as_str()) {
Problem [LIMITED 1/2]: this should limit the rejection scope only for test suites that use `FileCheck`-based annotations. Notably, this includes assembly, codegen and mir-opt. We should not be rejecting this for test suites that don't use `FileCheck`.

I.e. this check needs to be guarded with something like `matches!(self.mode, Mode::Assembly | Mode::Codegen | Mode::MirOpt)`.

2024-12-30 22:44 UTC, jieyouxu commented on src/tools/compiletest/src/header.rs
> +                        "invalid revision: `{}` in line `{}`: {}",
Suggestion: this is very uninformative, we should say something like (line break as suitable, probably)

```
revision name `{revision}` is not permitted in a test suite that uses `FileCheck` annotations as it is confusing when used as custom `FileCheck` prefix: `{revision}` in line `{}`:  {}
```

2024-12-30 22:44 UTC, jieyouxu commented on src/tools/compiletest/src/header/tests.rs
> +#[test]
Suggestion: just `#[should_panic]` here instead of trying to catch the panic.

2024-12-30 22:44 UTC, jieyouxu commented on src/tools/compiletest/src/header/tests.rs
> +    let config: Config = cfg().build();
Problem [LIMITED 2/2]: so this here should also iter through the 3 test suites that support `FileCheck` annotations to check that it should panic, but that it passes for non-`FileCheck` test suites.

2024-12-30 22:44 UTC, jieyouxu commented
r? jieyouxu

2024-12-30 22:44 UTC, jieyouxu commented
@rustbot author

2025-01-03 02:31 UTC, DavisRayM commented on src/tools/compiletest/src/header/tests.rs
> +    let config: Config = cfg().build();
I've limited the directories checked and added additional checks to ensure modes that support revisions but are not `FileCheck` test suites are also checked.

_Related to https://github.com/rust-lang/rust/pull/134925#discussion_r1899829612:_ Got a bit stumped trying to switch to _#[should_panic]_ I'd like all panics to be verified for each `FileMode` AFAIK `#[should_panic]` would succeed after the first panic ? _Perhaps, a gap in my knowledge_

2025-01-03 02:33 UTC, DavisRayM commented on src/tools/compiletest/src/header/tests.rs
> +#[test]
Got a bit stumped trying to switch to _#[should_panic]_ I'd like all panics to be verified for each `FileMode` AFAIK `#[should_panic]` would succeed after the first panic ? _Perhaps, a gap in my knowledge_

2025-01-03 02:42 UTC, DavisRayM commented on src/tools/compiletest/src/header/tests.rs
> +#[test]
Changed in the latest [commit](https://github.com/rust-lang/rust/pull/134925/commits/4a5e76a70e3d33b0eb4a233f60de5578b22bfba5). _I had to select a specific revision name for this `CHECK`, I'm not currently aware of a way to test all of them without manually catching the panic... Any tips on this will be greatly appreciated_

2025-01-03 02:43 UTC, DavisRayM commented on src/tools/compiletest/src/header.rs
> +                        "invalid revision: `{}` in line `{}`: {}",
Changed in the latest [commit](https://github.com/rust-lang/rust/pull/134925/commits/4a5e76a70e3d33b0eb4a233f60de5578b22bfba5)

2025-01-03 02:43 UTC, DavisRayM commented on src/tools/compiletest/src/header.rs
> +                } else if FORBIDDEN_REVISION_NAMES.contains(&revision.as_str()) {
Changed in the latest [commit](https://github.com/rust-lang/rust/pull/134925/commits/4a5e76a70e3d33b0eb4a233f60de5578b22bfba5)

2025-01-03 04:27 UTC, DavisRayM commented
@rustbot ready

2025-01-04 16:43 UTC, jieyouxu commented on src/tools/compiletest/src/header/tests.rs
> +#[test]
In the long run compiletest shouldn't be using randomly placed panics as an error handling strategy (really, the lack thereof), but in the short run this is reasonable.

2025-01-04 16:44 UTC, jieyouxu approved these changes
Thanks!

2025-01-04 16:45 UTC, jieyouxu commented
@bors r+ rollup

2025-01-05 06:21 UTC, merged

2025-01-09 00:39 UTC, jieyouxu commented
@bors retry r-