Improve `select_nth_unstable` documentation clarity
rust-lang/rust pull request #134976
Opened 2024-12-31 17:15 UTC by mgsloan

* Instead uses `before` and `after` variable names in the example
where `greater` and `lesser` are flipped.

* Uses `<=` and `>=` instead of "less than or equal to" and "greater
than or equal to" to make the docs more concise.

* General attempt to remove unnecessary words and be more precise. For
example it seems slightly wrong to say "its final sorted position",
since this implies there is only one sorted position for this element.

2024-12-31 17:25 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/12562188117/job/35022288955) [(plain)](https://github.com/rust-lang/rust/commit/dc9e8045acc8c6a3d76a89d62eeee81e27bcf453/checks/35022288955/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---
#13 2.917 Building wheels for collected packages: reuse
#13 2.918   Building wheel for reuse (pyproject.toml): started
#13 3.165   Building wheel for reuse (pyproject.toml): finished with status 'done'
#13 3.166   Created wheel for reuse: filename=reuse-4.0.3-cp310-cp310-manylinux_2_35_x86_64.whl size=132720 sha256=026f3bb0f1aa8090b861fd0a0939cb1a782396d84c8aab7875096557d637a0f6
#13 3.166   Stored in directory: /tmp/pip-ephem-wheel-cache-yjirn3my/wheels/3d/8d/0a/e0fc6aba4494b28a967ab5eaf951c121d9c677958714e34532
#13 3.169 Installing collected packages: boolean-py, binaryornot, tomlkit, reuse, python-debian, markupsafe, license-expression, jinja2, chardet, attrs
#13 3.570 Successfully installed attrs-23.2.0 binaryornot-0.4.4 boolean-py-4.0 chardet-5.2.0 jinja2-3.1.4 license-expression-30.3.0 markupsafe-2.1.5 python-debian-0.1.49 reuse-4.0.3 tomlkit-0.13.0
#13 3.570 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 4.107 Collecting virtualenv
#13 4.107 Collecting virtualenv
#13 4.157   Downloading virtualenv-20.28.0-py3-none-any.whl (4.3 MB)
#13 4.357      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 21.7 MB/s eta 0:00:00
#13 4.416 Collecting platformdirs<5,>=3.9.1
#13 4.423   Downloading platformdirs-4.3.6-py3-none-any.whl (18 kB)
#13 4.463 Collecting filelock<4,>=3.12.2
#13 4.493 Collecting distlib<1,>=0.3.7
#13 4.500   Downloading distlib-0.3.9-py2.py3-none-any.whl (468 kB)
#13 4.514      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 39.0 MB/s eta 0:00:00
#13 4.514      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 39.0 MB/s eta 0:00:00
#13 4.596 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#13 4.780 Successfully installed distlib-0.3.9 filelock-3.16.1 platformdirs-4.3.6 virtualenv-20.28.0
#13 DONE 4.9s

#14 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#14 DONE 0.0s
---
DirectMap4k:      118720 kB
DirectMap2M:     6172672 kB
DirectMap1G:    12582912 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint,cpp:fmt
    Finished `dev` profile [unoptimized] target(s) in 0.04s
##[endgroup]
WARN: currently no CI rustc builds have rustc debug assertions enabled. Please either set `rust.debug-assertions` to `false` if you want to use download CI rustc or set `rust.download-rustc` to `false`.
downloading https://static.rust-lang.org/dist/2024-11-27/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.xz
---
   Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
    Finished `release` profile [optimized] target(s) in 31.77s
##[endgroup]
fmt check
Diff in /checkout/library/core/src/slice/mod.rs:3193:
         sort::select::partition_at_index(self, index, |a: &T, b: &T| compare(a, b) == Less)
 
-
     /// Reorders the slice with a key extraction function such that the element at `index` is at a
     /// Reorders the slice with a key extraction function such that the element at `index` is at a
     /// sort-order position. All elements before `index` will have keys `<=` the key at `index`, and
     /// all elements after will have keys `>=`.
fmt error: Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/rustfmt/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/library/core/src/panic/panic_info.rs" "/checkout/library/core/src/panic/location.rs" "/checkout/library/core/src/panic.rs" "/checkout/library/core/src/option.rs" "/checkout/tests/run-make/alloc-no-rc/rmake.rs" "/checkout/library/core/src/sync/atomic.rs" "/checkout/library/core/src/sync/exclusive.rs" "/checkout/library/core/src/sync/mod.rs" "/checkout/library/core/src/ascii.rs" "/checkout/library/core/src/asserting.rs" "/checkout/library/core/src/primitive_docs.rs" "/checkout/tests/run-make/wasm-spurious-import/rmake.rs" "/checkout/tests/run-make/wasm-spurious-import/main.rs" "/checkout/library/core/src/prelude/common.rs" "/checkout/library/core/src/prelude/mod.rs" "/checkout/library/core/src/lib.miri.rs" "/checkout/library/core/src/pat.rs" "/checkout/library/core/src/unsafe_binder.rs" "/checkout/library/core/src/cell.rs" "/checkout/tests/run-make/c-static-dylib/foo.rs" "/checkout/tests/run-make/c-static-dylib/bar.rs" "/checkout/tests/run-make/c-static-dylib/rmake.rs" "/checkout/tests/run-make/separate-link-fail/foo.rs" "/checkout/tests/run-make/separate-link-fail/rmake.rs" "/checkout/library/core/src/slice/iter/macros.rs" "/checkout/library/core/src/slice/rotate.rs" "/checkout/library/core/src/slice/ascii.rs" "/checkout/library/core/src/slice/index.rs" "/checkout/tests/run-make/rustdoc-scrape-examples-test/rmake.rs" "/checkout/library/core/src/slice/raw.rs" "/checkout/tests/run-make/rustdoc-scrape-examples-test/src/lib.rs" "/checkout/tests/run-make/rustdoc-scrape-examples-test/examples/ex.rs" "/checkout/library/core/src/slice/sort/unstable/quicksort.rs" "/checkout/library/core/src/slice/sort/unstable/heapsort.rs" "/checkout/library/core/src/slice/sort/unstable/mod.rs" "/checkout/library/core/src/slice/sort/shared/pivot.rs" "/checkout/library/core/src/slice/sort/shared/smallsort.rs" "/checkout/library/core/src/slice/sort/shared/mod.rs" "/checkout/library/core/src/slice/sort/mod.rs" "/checkout/tests/run-make/mixing-formats/foo.rs" "/checkout/tests/run-make/mixing-formats/bar2.rs" "/checkout/tests/run-make/mixing-formats/baz2.rs" "/checkout/tests/run-make/mixing-formats/rmake.rs" "/checkout/tests/run-make/mixing-formats/bar1.rs" "/checkout/tests/run-make/mixing-formats/baz.rs" "/checkout/library/core/src/slice/sort/stable/tiny.rs" "/checkout/library/core/src/slice/sort/stable/quicksort.rs" "/checkout/library/core/src/slice/sort/stable/merge.rs" "/checkout/library/core/src/slice/sort/stable/drift.rs" "/checkout/library/core/src/slice/sort/stable/mod.rs" "/checkout/library/core/src/slice/sort/select.rs" "/checkout/library/core/src/slice/mod.rs" "/checkout/library/core/src/slice/memchr.rs" "/checkout/library/core/src/slice/iter.rs" "/checkout/tests/run-make/extern-multiple-copies2/bar.rs" "/checkout/library/core/src/slice/cmp.rs" "/checkout/tests/run-make/extern-multiple-copies2/foo1.rs" "/checkout/library/core/src/slice/specialize.rs" "/checkout/tests/run-make/extern-multiple-copies2/rmake.rs" "/checkout/tests/run-make/extern-multiple-copies2/foo2.rs" "/checkout/tests/run-make/invalid-symlink-search-path/rmake.rs" "/checkout/library/core/src/char/decode.rs" "/checkout/library/core/src/char/methods.rs" "/checkout/tests/run-make/print-target-cpus-native/rmake.rs"` failed.
If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
  local time: Tue Dec 31 17:25:34 UTC 2024
  network time: Tue, 31 Dec 2024 17:25 [...]

2025-01-06 02:30 UTC, mgsloan commented
?r Noratrieb

2025-01-16 06:00 UTC, ibraheemdev commented on library/core/src/slice/mod.rs
> +    /// elements before `index` will then be `<=` this value, and all elements after will be `>=`.
This (and the other occurrences) read a little awkwardly to me. Maybe "will be `<=` *to* this value"?

2025-01-18 21:54 UTC, mgsloan commented on library/core/src/slice/mod.rs
> +    /// elements before `index` will then be `<=` this value, and all elements after will be `>=`.
Good catch!  Pushed a commit addressing this.

2025-01-18 23:12 UTC, ibraheemdev commented on library/core/src/slice/mod.rs
> +    /// elements before `index` will then be `<=` this value, and all elements after will be `>=`.
Sorry, I think you misunderstood what I meant (though that's also a good catch). I was highlighting the missing "to":
```diff
- will be `<=` this value
+ will be `<=` to this value
```
Maybe it is just me, but the sentence flows a little oddly without it. I guess I am just reading the symbols in my head instead of "greater than or equal to". Similarly,
```diff
- all elements after will be `>=`
+ all elements after will be `>=` to it.
```

2025-01-18 23:25 UTC, ibraheemdev requested changes
I like the idea of this PR, but I left a few small formatting nits.

2025-01-18 23:25 UTC, ibraheemdev commented on library/core/src/slice/mod.rs
> +    /// * The unsorted subslice after `index` (elements all pass `f(x) >= f(self[index])`)
```suggestion
    /// * The unsorted subslice before `index`, whose elements all satisfy `f(x) <= f(self[index])`.
    /// * The element at `index`.
    /// * The unsorted subslice after `index`, whose elements all satisfy `f(x) >= f(self[index])`.
```

2025-01-18 23:25 UTC, ibraheemdev commented on library/core/src/slice/mod.rs
> +    /// all elements after will have keys `>=`.
```suggestion
    /// Reorders the slice with a key extraction function such that the element at `index` is at a
    /// sort-order position. All elements before `index` will have keys `<=` to the key at `index`, and
    /// all elements after will have keys `>=` to it.
```

2025-01-18 23:25 UTC, ibraheemdev commented on library/core/src/slice/mod.rs
> +    /// // comparator.
```suggestion
    /// // Find the items `>=` to the median, the median itself, and the items `<=` to it, by using
    /// // a reversed comparator.
```

2025-01-18 23:25 UTC, ibraheemdev commented on library/core/src/slice/mod.rs
> +    /// * The unsorted subslice after `index` (elements all pass `compare(x, self[index]).is_ge()`)
```suggestion
    /// * The unsorted subslice before `index`, whose elements all satisfy `compare(x, self[index]).is_le()`.
    /// * The element at `index`.
    /// * The unsorted subslice after `index`, whose elements all satisfy `compare(x, self[index]).is_ge()`.
```

2025-01-18 23:25 UTC, ibraheemdev commented on library/core/src/slice/mod.rs
> +    /// // absolute value.
```suggestion
    /// // Find the items `<=` to the absolute median, the absolute median itself, and the items `>=` to it.
```

2025-01-18 23:25 UTC, ibraheemdev commented on library/core/src/slice/mod.rs
> +    /// Returns a triple partitioning the reordered slice:
```suggestion
    /// Returns a triple that partitions the reordered slice:
```

2025-01-18 23:25 UTC, ibraheemdev commented on library/core/src/slice/mod.rs
> +    /// Returns a triple partitioning the reordered slice:
```suggestion
    /// Returns a triple that partitions the reordered slice:
```

2025-01-18 23:25 UTC, ibraheemdev commented on library/core/src/slice/mod.rs
> +    /// after will be `>=` according to the comparator function.
```suggestion
    /// Reorders the slice with a comparator function such that the element at `index` is at a
    /// sort-order position. All elements before `index` will be `<=` to this value, and all elements
    /// after will be `>=` to it, according to the comparator function.
```

2025-01-18 23:25 UTC, ibraheemdev commented on library/core/src/slice/mod.rs
> +    /// // Find the items `<=` the median, the median, and `>=` the median.
```suggestion
    /// // Find the items `<=` to the median, the median itself, and the items `>=` to it.
```

2025-01-18 23:25 UTC, ibraheemdev commented on library/core/src/slice/mod.rs
> +    /// * The unsorted subslice after `index` (elements all pass `x >= self[index]`)
```suggestion
    /// * The unsorted subslice before `index`, whose elements all satisfy `x <= self[index]`.
    /// * The element at `index`.
    /// * The unsorted subslice after `index`, whose elements all satisfy `x >= self[index]`.
```

2025-01-18 23:25 UTC, ibraheemdev commented on library/core/src/slice/mod.rs
> +    /// Returns a triple partitioning the reordered slice:
```suggestion
    /// Returns a triple that partitions the reordered slice:
```

2025-01-18 23:25 UTC, ibraheemdev commented on library/core/src/slice/mod.rs
> +    /// elements before `index` will be `<=` this value, and all elements after will be `>=`.
```suggestion
    /// Reorders the slice such that the element at `index` is at a sort-order position. All
    /// elements before `index` will be `<=` to this value, and all elements after will be `>=` to it.
```

2025-01-19 01:41 UTC, mgsloan commented
Thanks for the thorough review and the suggestions!  Definitely an improvement.  I've added a commit rewrapping the text after those chnages

2025-01-19 06:45 UTC, ibraheemdev commented
Looks good now, thanks for following up! @bors r+

2025-01-19 11:37 UTC, merged

2025-01-19 12:52 UTC, rust-timer commented
Finished benchmarking commit (678e669cc4aab51e3c3fff0660d45362fb830ebd): [comparison URL](https://perf.rust-lang.org/compare.html?start=c62b732724b6beb50a5c73be26d0c5f668504059&end=678e669cc4aab51e3c3fff0660d45362fb830ebd&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=c62b732724b6beb50a5c73be26d0c5f668504059&end=678e669cc4aab51e3c3fff0660d45362fb830ebd&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=c62b732724b6beb50a5c73be26d0c5f668504059&end=678e669cc4aab51e3c3fff0660d45362fb830ebd&stat=max-rss)
<details>
<summary>Results (primary 1.2%)</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.2% | [1.2%, 1.2%] | 1     |
| Regressions ❌ <br /> (secondary)  | -    | -            | 0     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 1.2% | [1.2%, 1.2%] | 1     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=c62b732724b6beb50a5c73be26d0c5f668504059&end=678e669cc4aab51e3c3fff0660d45362fb830ebd&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

### [Binary size](https://perf.rust-lang.org/compare.html?start=c62b732724b6beb50a5c73be26d0c5f668504059&end=678e669cc4aab51e3c3fff0660d45362fb830ebd&stat=size:linked_artifact)
This benchmark run did not return any relevant results for this metric.

**Bootstrap**: 765.96s -> 763.781s (-0.28%)
**Artifact size**: 325.96 MiB -> 325.98 MiB (0.00%)

2025-01-19 16:53 UTC, RalfJung commented
In the future, please avoid merging PRs that contain 10 commits each fixing a single-line typo with a non-descript commit message.

2025-01-19 20:19 UTC, ibraheemdev commented
Ah sorry, I assumed it was squashed for some reason.

2025-01-19 20:55 UTC, mgsloan commented
Sorry, I'm used to the squash PRs setting we're using on https://github.com/zed-industries/zed.  Wish GitHub's suggestion thing had an "Accept all as one commit" thing too

2025-01-19 21:05 UTC, RalfJung commented
> Wish GitHub's suggestion thing had an "Accept all as one commit" thing too

It doesn't have that as a one-click button, but you can commit multiple suggestions in one commit by going to the "diff" tab.