exclusive range patterns
rust-lang/rust pull request #35712
Opened 2016-08-16 11:14 UTC by oli-obk

2016-08-16 11:14 UTC, rust-highfive commented
r? @arielb1

(rust_highfive has picked a reviewer for you, use r? to override)

2016-08-17 22:49 UTC, petrochenkov commented on src/librustc/hir/mod.rs
> +    ExclusiveRange(P<Expr>, P<Expr>),
In most cases inclusive and exclusive ranges behave identically, it's probably more convenient to merge them into one variant `Range(P<Expr>, P<Expr>, RangeKind)`.

2016-08-18 11:09 UTC, oli-obk commented on src/librustc/hir/mod.rs
> +    ExclusiveRange(P<Expr>, P<Expr>),
I changed this, it's much less and more readable code now :+1:

2016-09-06 15:08 UTC, oli-obk commented
rebased

2016-09-23 08:01 UTC, oli-obk commented
I'll bump the error code once this is deemed ready.

2016-10-27 08:41 UTC, petrochenkov commented on src/libsyntax/parse/parser.rs
> +                    tok @ token::DotDotDot | tok @ token::DotDot => {
You also need to add `token::DotDot` to this condition above:
```
                       self.look_ahead(1, |t| match *t {
                           token::OpenDelim(token::Paren) | token::OpenDelim(token::Brace) |
                           token::DotDotDot | token::ModSep | token::Not => false,
```
=>
```
                       self.look_ahead(1, |t| match *t {
                           token::OpenDelim(token::Paren) | token::OpenDelim(token::Brace) |
                           token::DotDotDot | token::DotDot | token::ModSep | token::Not => false,
```

2016-11-09 01:32 UTC, brson commented
This PR seems to have gone under the radar for a long time. Can somebody review?

Is this an implementation of an RFC. Is there a tracking issue?

2016-11-09 01:32 UTC, brson commented
cc @rust-lang/compiler

2016-11-09 08:11 UTC, oli-obk commented
No rfc or tracking issue, I thought it was just an oversight. But I can write an RFC...

2016-11-17 21:14 UTC, nikomatsakis commented
There was an RFC, iirc, but @aturon has been having second thoughts on the syntax here, and wanting something more general.

2016-11-17 22:31 UTC, nikomatsakis commented
My mistake: I thought this was adding `...` expressions, not `..` patterns.

2016-11-17 22:33 UTC, aturon commented
Note: this was not covered by https://github.com/rust-lang/rfcs/pull/1192

2016-11-17 22:34 UTC, eddyb commented
Any thoughts on `a..` or `..b`?

2016-11-17 22:34 UTC, nikomatsakis commented
Discussed in the @rust-lang/lang meeting:

- This needs a tracking issue and feature-gate.
- We feel OK landing this for now, as long as it is gated, because it seems that in any possible world this is desirable, **but:**
    - we would be unlikely to stabilize until the question of how to handle `...` is resolved
        - my preference is `..=` (which generalizes to `<..<`, `<..=` and so forth)

2016-11-18 11:34 UTC, oli-obk commented
added tracking issue, the feature gate was already there.

2016-11-18 11:52 UTC, bluss commented
I'll put in my pedantic note that these are "exclusive-end" ranges.

2016-12-20 20:01 UTC, oli-obk commented
Rebased. This is ready for r+

2016-12-20 21:12 UTC, aturon commented
cc @rust-lang/compiler this PR is ready to go, but needs an active reviewer.

2016-12-30 17:16 UTC, nikomatsakis commented
r? @nikomatsakis

2017-01-03 18:45 UTC, nikomatsakis requested changes

2017-01-03 18:45 UTC, nikomatsakis commented on src/libsyntax/parse/parser.rs
> +            token::DotDot => None,
Why is `DotDot` different from `DotDotDot` here?

2017-01-03 18:46 UTC, nikomatsakis commented
Oh, I forgot to ask: can you add some tests targeting the exhaustiveness algorithm? Does it require any changes here?

2017-01-03 19:41 UTC, nikomatsakis commented
cc @Manishearth -- are we still grouping changes to the AST together?

2017-01-03 21:34 UTC, Manishearth commented
Not at the moment, experimenting with it. ccign some of the folks and landing should be enough

cc @dtolnay @erickt 


feel free to land whenever

2017-01-03 21:54 UTC, dtolnay commented
:+1: I always appreciate a cc but no need to batch things like this anymore. Long live macros 1.1!

2017-01-04 07:10 UTC, petrochenkov commented on src/libsyntax/parse/parser.rs
> +            token::DotDot => None,
[Syntactic conflict](https://github.com/rust-lang/rust/issues/23121#issuecomment-154138818) between subslice patterns and exclusive range patterns is finally revealing itself.

2017-01-07 12:47 UTC, nikomatsakis commented
@oli-obk at minimum, needs a rebase, but I'd also like to see some tests targeting the exhaustiveness algorithm (I don't think there were any, right?)

2017-01-07 13:33 UTC, oli-obk commented
I'll write the tests, it's sensible to have many tests around the various cases here. I just was on vacation and thus didn't get around to answering

2017-01-09 23:01 UTC, nikomatsakis commented
@oli-obk no worries. thanks!

2017-01-10 21:13 UTC, oli-obk commented
I'm confused... We don't have exhaustiveness checks for integers?

The following doesn't work on the playground:

```rust
    match 42_u8 {
        0...255 => {}
    }
```

I'm not sure how to test exhaustiveness for integers.

2017-01-10 22:09 UTC, nikomatsakis commented
@oli-obk yeah I was thinking that later, that maybe this doesn't intersect exhaustiveness because we're not smart enough there yet. I guess this is only usable for integers?

2017-01-11 06:45 UTC, oli-obk commented
It also works for floats, there's a test for them, too. Especially for floats this is an important change, as you could not write the same code with an inclusive match

2017-01-11 06:45 UTC, oli-obk commented
Travis has passed

2017-01-12 16:16 UTC, nikomatsakis approved these changes

2017-01-12 16:19 UTC, nikomatsakis requested changes
One more thing: can we have some tests regarding the syntactic conflict between exclusive range patterns and slice patterns?

@petrochenkov maybe you can supply a few pertinent examples and what you expect as the outcome? :)

2017-01-12 16:22 UTC, nikomatsakis commented on src/libsyntax/parse/parser.rs
> +            token::DotDot => None,
It *does* feel like we should change the slice pattern syntax here. However, could we address with simply having a bit more lookahead? In particular, we don't support patterns like `0..`, do we? (Though...I think we probably should... and I don't know what to use for slices instead just now >:/)

2017-01-16 12:19 UTC, est31 commented on src/test/compile-fail/pat-range-bad-dots.rs
>  // except according to those terms.
Note: with #38914 merged in the meantime, you'll either have to rename this test to "feature-gate-exclusive-range-pattern.rs" or add a comment `// gate-test exclusive_range_pattern`. See also [COMPILER_TESTS.md](https://github.com/rust-lang/rust/blob/master/COMPILER_TESTS.md#summary-of-header-commands). Just saying as changing beforehad will prevent a failed bors run and maybe contribute to getting this merged faster.

2017-01-19 14:15 UTC, oli-obk commented
Added tests with exclusive range patterns inside slice patterns. For now this works, but if we ever get half open range patterns we'd get collisions.

2017-01-23 21:46 UTC, nikomatsakis approved these changes

2017-01-23 21:46 UTC, nikomatsakis commented
@bors r+

2017-01-23 21:48 UTC, nikomatsakis commented
@oli-obk where is the tracking issue here?

2017-01-23 21:48 UTC, nikomatsakis commented
Ah, https://github.com/rust-lang/rust/issues/37854 -- didn't come up in search for some reason

2017-01-24 01:18 UTC, alexcrichton commented
@bors: retry

* that seems like a bug in travis?

2017-01-24 03:45 UTC, alexcrichton commented
@bors: retry

* bug in travis?

2017-01-24 07:49 UTC, alexcrichton commented
@bors: retry

* sccache wedged https://github.com/rust-lang/rust/issues/39003

On Mon, Jan 23, 2017 at 10:56 PM, bors <notifications@github.com> wrote:

> 💔 Test failed - status-travis
> <https://travis-ci.org/rust-lang/rust/builds/194718710>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/35712#issuecomment-274724876>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAD95NYGVCGs3H_Q68LGpUEaBChBAvZFks5rVaCtgaJpZM4JlR3b>
> .
>

2017-01-24 16:52 UTC, alexcrichton commented
@bors: retry

* weird travis bug?

On Tue, Jan 24, 2017 at 1:28 AM, bors <notifications@github.com> wrote:

> 💔 Test failed - status-travis
> <https://travis-ci.org/rust-lang/rust/builds/194753248>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/35712#issuecomment-274752129>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAD95ElWSl051uN0F4JzhigI6ZHjLy9mks5rVcRAgaJpZM4JlR3b>
> .
>

2017-01-24 21:39 UTC, alexcrichton commented
@bors: retry

* osx linker segfault https://github.com/rust-lang/rust/issues/38878

On Tue, Jan 24, 2017 at 12:42 PM, bors <notifications@github.com> wrote:

> 💔 Test failed - status-travis
> <https://travis-ci.org/rust-lang/rust/builds/194905800>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/35712#issuecomment-274932173>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAD95OXfrMTEVICR-T084bSmMvm9IG-aks5rVmIjgaJpZM4JlR3b>
> .
>

2017-01-24 22:23 UTC, steveklabnik commented
@bors: retry p=1

2017-01-24 23:47 UTC, alexcrichton commented
@bors: retry

* osx linker segfaulted https://github.com/rust-lang/rust/issues/38878

On Tue, Jan 24, 2017 at 3:33 PM, bors <notifications@github.com> wrote:

> 💔 Test failed - status-travis
> <https://travis-ci.org/rust-lang/rust/builds/194986552>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/35712#issuecomment-274973883>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAD95KIgyJq_J0WodQVBuMsO6oY0UMoJks5rVopdgaJpZM4JlR3b>
> .
>

2017-01-25 04:36 UTC, merged

2023-11-19 19:40 UTC, LU15W1R7H commented
I just came to this issue, because I wanted to write the code you see below.
```rs
match idx {
  0..LOCAL_BOARD_SIZE => LineType::XAxis(idx as u8),
  LOCAL_BOARD_SIZE..2 * LOCAL_BOARD_SIZE => LineType::YAxis((idx - LOCAL_BOARD_SIZE) as u8),
  2 * LOCAL_BOARD_SIZE => LineType::MainDiagonal,
  2 * LOCAL_BOARD_SIZE + 1 => LineType::AntiDiagonal,
  _ => unreachable!(),
}
```

I'm shocked by how many people are against this feature and are concerned with it's introduction, because of potentially wrong usage. I really don't get this. There are perfectly valid places for using this, as my example shows.

I think this is very much related to computer science being 0-indexed instead of 1-indexed, which I consider one of the best decisions. [^1]

In a 0-indexed world, the number of things isn't equal to the last index, it's one more. But it's still useful to think about the number of things. This is why for loops are written as `for i in 0..10`, because we are 0-indexed but we want 10 iterations. So this is useful! This is why we allow for open ranges in for loops. The same applies to matching, this is no different! If we want to match 10 (number of things) elements, this means we want the elements with the indices 0 to (and including 9), so `0..=9`, but this is cumbersome if you are just thinking about the number of things, so `0..10` is a lot better!
In order to match a certain number of things (instead of the indices) we must allow for exclusive end ranges in matches!

[^1]: I actually believe that humanity should have opted for 0-indexing everywhere, also in mathematics, maybe even day-to-day life? But unfortunately history didn't play out this way.