Changed error message E0408 to new format
rust-lang/rust pull request #36307
Opened 2016-09-06 21:04 UTC by faebser

Followed your text and was able to change the ouput to the new format.
I did not encounter any broken test therefore this is a really small commit.

Thanks for letting me hack on the compiler :)

r? @jonathandturner

2016-09-06 21:04 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @jonathandturner (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-09-06 21:06 UTC, faebser commented
Part of #35233
Fixes #35698

2016-09-07 10:07 UTC, GuillaumeGomez commented
Thanks for your PR!

You also need to update the corresponding test(s) to reflect your changes. They are located in `src/test/compile_fail/`.

2016-09-08 15:44 UTC, jonathandturner commented
@faebser - as @GuillaumeGomez mentions, the test infrastructure has some quirks.  One is that the labels aren't tested until you add your first NOTE.  You can read about this in the Extra Credit part of the [blog post](http://www.jonathanturner.org/2016/08/helping-out-with-rust-errors.html)

2016-09-09 15:06 UTC, faebser commented
@jonathandturner thanks for the heads up. I will work on the test as soon I have time.

2016-09-09 18:02 UTC, GuillaumeGomez commented
@faebser: Don't worry, we're not in a hurry. Just comment here once done.

2016-09-22 22:27 UTC, faebser commented
@jonathandturner I don't really get where I have to add the note?
If i try to add a note to https://github.com/rust-lang/rust/blob/master/src/test/compile-fail/E0408.rs (which I think is the original test case that you refer to in your blog post) I just get an unexpected note error if i run the test.

2016-09-23 14:36 UTC, jonathandturner commented
@faebser - can you add your changes to this PR so we can take a look?

2016-09-25 21:25 UTC, faebser commented
@jonathandturner I added my try as a commit to the PR.
Running ```python src/bootstrap/bootstrap.py --step check-cfail --stage 1``` gives the following errors:

```rust
failures:

---- [compile-fail] compile-fail/E0408.rs stdout ----
	
error: /home/faebser/workspace/rust/src/test/compile-fail/E0408.rs:15: unexpected "error": '15:19: 15:23: variable `y` from pattern #1 is not bound in pattern #2 [E0408]'

error: /home/faebser/workspace/rust/src/test/compile-fail/E0408.rs:15: unexpected "note": 'pattern doesn't bind `y`'

error: /home/faebser/workspace/rust/src/test/compile-fail/E0408.rs:14: expected error not found: variable `y` from pattern #2 is not bound in pattern #1

error: /home/faebser/workspace/rust/src/test/compile-fail/E0408.rs:14: expected note not found: pattern doesn't bind `y`

error: 2 unexpected errors found, 2 expected errors not found
status: exit code: 101
```

2016-09-25 22:00 UTC, GuillaumeGomez commented
Then fix them? I don't know what to add actually. :-/

2016-09-26 10:35 UTC, faebser commented
@GuillaumeGomez: I am sorry but I am a bit lost and I don't really understand how to fix this error. I added them to this PR because @jonathandturner asked me to.

2016-09-26 15:56 UTC, GuillaumeGomez commented
The "errors" you see come from `src/test/compile-fail/E0408.rs`. So, you added annotations (like `//~ ERROR E0408' but some of them aren't matched with the current rustc output (that you updated).

So let's see the first one:

```
E0408.rs:15: unexpected "error": '15:19: 15:23: variable `y` from pattern #1 is not bound in pattern #2 [E0408]'
```

It says that an annotation was not found. So let's look to your file:

```
//~^ ERROR variable `y` from pattern #2 is not bound in pattern #1
```

It means you expect an error to be thrown by the line before this one (the "^" says it). Better like this?

2016-09-26 22:15 UTC, faebser commented
@GuillaumeGomez: thanks for your comment. I also realised that **#1** and **#2** were the wrong way around thus generating the error.
I added one more test and will try to find the remaining ones tomorrow.

2016-09-27 09:00 UTC, GuillaumeGomez requested changes
Once these fixed, please squash your commits. If you don't know how to do it, take a look [here](https://blog.guillaume-gomez.fr/Git-tips/1/2).

2016-09-27 09:00 UTC, GuillaumeGomez commented on src/test/compile-fail/E0408.rs
> +        _ => () //~^ NOTE pattern doesn't bind `y`
Generally, we use "//~|" and not "//~^" when it's on the same line. I mean that the note is thrown by the same line than the error, so it's the "same" issue. With this way to write it, we have the feeling that it's two different errors.

Also, can you align "//~^ NOTE pattern doesn't bind `y`" with "//~ ERROR variable `y` from pattern #1 is not bound in pattern #2" please?

2016-09-27 09:00 UTC, GuillaumeGomez commented on src/test/compile-fail/issue-2848.rs
> +      charlie => {} //~^ NOTE pattern doesn't bind `beta`
Same as above.

2016-09-27 22:18 UTC, faebser commented
@GuillaumeGomez can you please review the third test too? thanks

2016-09-28 12:02 UTC, GuillaumeGomez commented
All good for me. Please squash your commits now.

2016-10-12 17:33 UTC, KiChjang commented
This looks like it only requires squashing, what's blocking this for 2 weeks?

2016-10-12 20:10 UTC, GuillaumeGomez commented
No clue. :-/

2016-10-12 22:15 UTC, faebser commented
Sorry for the delay, I thought that the squash was okay but after having another look today I saw that it did not work. I am working on fixing it right now.

2016-10-12 22:19 UTC, faebser commented
@GuillaumeGomez: squash is okay now

2016-10-13 13:11 UTC, GuillaumeGomez commented
Thanks!

@bors: r+ rollup

2016-10-13 16:39 UTC, arielb1 commented
@bors retry

2016-10-13 20:23 UTC, alexcrichton commented
@bors: retry

2016-10-15 02:33 UTC, merged