fix stack overflow by enum and cont
rust-lang/rust pull request #36458
Opened 2016-09-13 20:10 UTC by mikhail-m1

fixes #36163

2016-09-13 20:10 UTC, rust-highfive commented
r? @arielb1

(rust_highfive has picked a reviewer for you, use r? to override)

2016-09-14 18:27 UTC, mikhail-m1 commented
I'll fix it

2016-09-22 18:30 UTC, mikhail-m1 commented
@arielb1 Could you look at my PR or may be suggest other review? I'll fix conflicts ASAP

2016-09-24 10:57 UTC, arielb1 requested changes
Your PR looks great, however:
- There are a few issues with the coding style. You should fix them.
- Your PR comment should mention the issue fixed - that some paths were skipped while checking for recursion.

2016-10-04 19:56 UTC, mikhail-m1 commented
@arielb1 Than you for review and sorry for long delay and rustfmt, I forgot run it after last fix. 
I've fixed all nits, except two lifetime ('a and 'b). One need for session, maps, .. and another for detected_recursive_ids field from CheckCrateVisitor. Current version of CheckItemRecursionVisitor get descriminant_map as RefCell but I think two life time is better thand RefCell. May be I miss something. I am going to remove RefCell from descriminant_map too, but should it be separate PR?

2016-10-05 21:50 UTC, arielb1 commented
- Timeout

@bors retry

2016-10-05 23:20 UTC, alexcrichton commented
@bors: retry force clean

* looks like a new builder was forgotten by accident now

2016-10-06 01:56 UTC, alexcrichton commented
@bors: retry

On Wednesday, October 5, 2016, bors <notifications@github.com> wrote:

> 💔 Test failed - auto-win-msvc-64-cargotest
> <https://buildbot.rust-lang.org/builders/auto-win-msvc-64-cargotest/builds/2004>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/36458#issuecomment-251842689>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAD95Ab5dWc9RkSQgy0cR8m_dgYFYSUWks5qxEqMgaJpZM4J8F00>
> .
>

2016-10-06 16:42 UTC, alexcrichton commented
@bors: retry

On Wed, Oct 5, 2016 at 10:43 PM, bors <notifications@github.com> wrote:

> 💔 Test failed - auto-win-msvc-64-cargotest
> <https://buildbot.rust-lang.org/builders/auto-win-msvc-64-cargotest/builds/2006>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/36458#issuecomment-251872048>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAD95PPe22eVUXsKECTT4lEwIINQ8cuhks5qxIpzgaJpZM4J8F00>
> .
>

2016-10-06 17:22 UTC, alexcrichton commented
@bors: r-

er wait, this seems legitimate!

2016-10-06 20:32 UTC, mikhail-m1 commented
@alexcrichton How can I reproduce it locally?

2016-10-06 20:53 UTC, alexcrichton commented
@mikhail-m1 

I believe this should work:

```rust
./configure --enable-rustbuild
make check-cargotest
```

2016-10-07 21:15 UTC, mikhail-m1 commented
@alexcrichton I rebuild it locally after pull and rebase and all tests passed successfully but on x86_64-unknown-linux-gnu

2016-10-11 11:19 UTC, mikhail-m1 commented
What should be my next step?

2016-10-11 14:50 UTC, alexcrichton commented
How long did the build take? It looks like something is becoming perhaps pathologically slow although it may still complete (e.g. the build failed as it lacked output for awhile)

2016-10-11 15:53 UTC, mikhail-m1 commented
@alexcrichton step with url crate (I think it's cargotest) takes several seconds, may be some way to get some information from CI build? I can rebuild it again collect and share output.

2016-10-14 19:58 UTC, mikhail-m1 commented
testing https://github.com/iron/iron
...
    Finished debug [unoptimized + debuginfo] target(s) in 258.97 secs
testing https://github.com/rust-lang/cargo
...
    Finished debug [unoptimized + debuginfo] target(s) in 743.97 secs
but some tests failed, but my PR cannot affect it

full log: https://www.dropbox.com/s/wbi7esu7a9mapxx/build2.log?dl=0

2016-10-14 20:59 UTC, mikhail-m1 commented
testing https://github.com/iron/iron
...
    Finished debug [unoptimized + debuginfo] target(s) in 258.97 secs
testing https://github.com/rust-lang/cargo
...
    Finished debug [unoptimized + debuginfo] target(s) in 743.97 secs
but some tests failed, but my PR cannot affect it

full log: https://www.dropbox.com/s/wbi7esu7a9mapxx/build2.log?dl=0

2016-10-31 20:43 UTC, alexcrichton commented
Closing due to inactivity but feel free to resubmit with tests fixed!

2016-10-31 20:43 UTC, closed without merging