Remove data structure specialization for .zip() iterator
rust-lang/rust pull request #36490
Opened 2016-09-15 08:10 UTC by bluss

Go back on half the specialization, the part that changed the Zip
struct's fields themselves depending on the types of the iterators.

Previous PR: #33090

This means that the Zip iterator will always carry two usize fields,
which are unused. If a whole for loop using a .zip() iterator is
inlined, these are simply removed and have no effect.

The same improvement for Zip of for example slice iterators remain, and
they still optimize well. However, like when the specialization of zip
was merged, the compiler is still very sensistive to the exact context.

For example this code only autovectorizes if the function is used, not
if the code in zip_sum_i32 is inserted inline it was called:

```
fn zip_sum_i32(xs: &[i32], ys: &[i32]) -> i32 {
    let mut s = 0;
    for (&x, &y) in xs.iter().zip(ys) {
        s += x * y;
    }
    s
}

fn zipdot_i32_default_zip(b: &mut test::Bencher)
{
    let xs = vec![1; 1024];
    let ys = vec![1; 1024];

    b.iter(|| {
        zip_sum_i32(&xs, &ys)
    })
}
```

Include a test that checks that Zip<T, U> is covariant w.r.t. T and U.

Fixes #35727

2016-09-15 08:11 UTC, rust-highfive commented
r? @alexcrichton

(rust_highfive has picked a reviewer for you, use r? to override)

2016-09-15 10:43 UTC, pnkfelix commented on src/libcore/iter/mod.rs
> +    index: usize,
could you add a comment here pointing out that these fields are only used for specialized instantiations of `A` and `B` (and point to #35727 in the comment for further explanation)

2016-09-15 10:45 UTC, pnkfelix approved these changes

2016-09-15 10:46 UTC, pnkfelix commented
(hmm, these new github UI changes run risk of bypassing bors. good thing I don't have authority to merge...)

2016-09-15 11:00 UTC, bluss commented on src/libcore/iter/mod.rs
> +    index: usize,
Done with an amend. Thanks

2016-09-15 12:36 UTC, nagisa commented on src/test/run-pass/variance-iterators-in-libcore.rs
> +// Copyright 2015 The Rust Project Developers. See the COPYRIGHT
NIT: Name for this test is weirdly general for what it tests. Linked list iterator covariance is tested in libcollections itself for example. Perhaps we could test for zip covariance in libcoretest too?

2016-09-15 12:37 UTC, nagisa requested changes

2016-09-15 12:38 UTC, nagisa commented
@pnkfelix the only thing that actually merges anything is clicking the “merge pull request” thing AFAICT.

2016-09-15 12:44 UTC, bluss commented on src/test/run-pass/variance-iterators-in-libcore.rs
> +// Copyright 2015 The Rust Project Developers. See the COPYRIGHT
It's a place to put more iterator tests, for now just this one.

2016-09-15 13:02 UTC, nagisa commented on src/test/run-pass/variance-iterators-in-libcore.rs
> +// Copyright 2015 The Rust Project Developers. See the COPYRIGHT
@bluss my experience suggests that people rarely reuse/update tests and instead just add new ones. The only exception I can think of is when some area belongs to one person and they do all the work in it.

2016-09-15 13:38 UTC, bluss commented on src/test/run-pass/variance-iterators-in-libcore.rs
> +// Copyright 2015 The Rust Project Developers. See the COPYRIGHT
I think it has happened before in the various run-pass/sync-send-*.rs files

2016-09-15 13:47 UTC, bluss commented
We need to get to grips with the iterator optimization stumbling blocks later. What I understand it's still due to spurious null checks being inserted.

The iterator element is `Option<(&T, &T)>`, so a null in the first half is equal to None and the end of the iteration. It seems even when the expression is explicitly `Some(a, b)`, the null check is even inserted there, which is nonsensical from a Rust perspective -- `Some(a, b)` is never `None`.

2016-09-15 13:51 UTC, bluss commented
Another sidenote, it's really true that iterators of non-references don't have that problem. `a.iter().cloned().zip(b.iter().cloned())` has no problem if a, b are slices -- and if the specialization trait is added on Clone, oops.

2016-09-16 00:30 UTC, brson commented
Nominated since it's a regression fix. Might be better to get it out faster.

2016-09-16 08:17 UTC, alexcrichton commented
@bors: r+ af1a3ffbebef27f3dc267e66c15325596d1a2cff

2016-09-17 19:02 UTC, merged