librustc_mir: Remove `&*x` when `x` has a reference type.
rust-lang/rust pull request #36504
Opened 2016-09-15 20:57 UTC by pcwalton

This introduces a new `InstCombine` pass for us to place such peephole
optimizations.

r? @eddyb

2016-09-15 20:57 UTC, pcwalton commented
This should open up some new copy prop opportunities.

2016-09-15 21:01 UTC, cbreeden commented
Does this include `*&` as well?  Something like how `Deref` is implemented on `&'a T`?

2016-09-15 21:05 UTC, eddyb commented
@cbreeden No, that's somewhat more complex because it's not self-contained within a statement.

2016-09-15 23:34 UTC, pcwalton commented
How's this?
r? @eddyb

2016-09-15 23:36 UTC, eddyb commented on src/librustc_mir/transform/instcombine.rs
> +    and_stars: HashSet<Location>,
Should use `FnvHashSet` (from `rustc::utils::nodemap`) in the compiler.

2016-09-15 23:37 UTC, eddyb commented on src/librustc_mir/transform/instcombine.rs
> +    fn new() -> OptimizationList {
This can be done via `#[derive(Default)]`.

2016-09-15 23:39 UTC, eddyb commented on src/librustc_mir/transform/instcombine.rs
> +        if self.optimizations.and_stars.contains(&location) {
Can use `remove` instead of `contains` to do both at once.

2016-09-15 23:40 UTC, eddyb commented on src/librustc_mir/transform/instcombine.rs
> +                    mem::replace(&mut projection.base, Lvalue::ReturnPointer)
Heh, nice placeholder hack.

2016-09-15 23:40 UTC, eddyb commented on src/librustc_mir/transform/instcombine.rs
> +                _ => panic!("Detected `&*` but didn't find `&*`!"),
Should use `bug!` in the compiler.

2016-09-15 23:43 UTC, eddyb requested changes
r=me with comments addressed. It might be good to also explain (in a comment?) why the optimizations are collected ahead of time instead of done in-place.

2016-09-16 00:06 UTC, pcwalton commented
Updated. r? @eddyb

2016-09-16 00:07 UTC, eddyb approved these changes
@bors r+

2016-09-16 00:08 UTC, eddyb commented
@bors r+

2016-09-16 10:44 UTC, arielb1 commented
@bors r-

This will cause drop elaboration to crash and burn, because the newly-created code moves behind `&mut` references.

2016-09-16 11:34 UTC, eddyb commented
Ah, right, my bad, I forgot that it had to go after drop elaboration. We need more comments in the pass list.

2016-09-16 13:23 UTC, arielb1 commented
I would like to have more understanding on what properties MIR must have at every step before we start doing destructive optimizations.

2016-09-16 16:26 UTC, pcwalton commented
@arielb1 Right now we are generating very bad code. I think it would be unwise to gate needed optimizations on "understanding of what properties MIR must have at every step". As long as it works, we can do that later.

2016-09-16 16:29 UTC, eddyb commented on src/librustc_driver/driver.rs
>          passes.push_pass(box borrowck::ElaborateDrops);
You only need to reorder the pass to go after this line, which should be separated and commented.
This is the point where moves stop existing and you only have raw semantic-less copies.

2016-09-16 16:29 UTC, eddyb requested changes
r=me with the pass reordered.

2016-09-16 16:32 UTC, pcwalton commented
@bors-servo: r=eddyb

2016-09-16 16:34 UTC, eddyb approved these changes

2016-09-18 03:57 UTC, merged