Reword error when data-less enum variant called as function
rust-lang/rust pull request #36520
Opened 2016-09-16 01:49 UTC by estebank

Given a file like:

```rust
enum Test {
    Variant,
    Variant2 {a: u32},
}

fn main(){
    let x = Test::Variant("Hello");
    let y = Test::Variant2("World");
}
```

Both errors now look similar:

```bash
error[E0423]: `Test::Variant2` is the name of a struct or struct variant, but this expression uses it like a function name
  --> file3.rs:10:13
   |
10 |     let y = Test::Variant2("Hello");
   |             ^^^^^^^^^^^^^^ struct called like a function
   |
   = help: did you mean to write: `Test::Variant2 { /* fields */ }`?

error: `Test::Variant` is the name of a data-less enum, but this expression uses it like a function name
 --> file3.rs:9:13
  |
9 |     let x = Test::Variant("World");
  |             ^^^^^^^^^^^^^^^^^^^^^^ data-less enum called like a function
  |
  = help: did you mean to write: `Test::Variant`?
note: defined here
 --> file3.rs:2:5
  |
2 |     Variant,
  |     ^^^^^^^

error: aborting due to previous error
```

Re: #28533

2016-09-16 01:49 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @pnkfelix (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-09-16 10:03 UTC, pnkfelix commented
My initial reaction: I don't think I've seen the phrase "data-less enum" before, and I'd prefer to try to use a phrase consistent with our docs, if possible.

However, I do see "variant with no data" in the [book](https://doc.rust-lang.org/book/enums.html). The book also uses "unit-like" elsewhere (in the context of "unit-like struct"), which I also see at [rust-by-example](http://rustbyexample.com/custom_types/enum.html)

cc  @rust-lang/docs

2016-09-16 10:15 UTC, GuillaumeGomez commented
First time I see "data-less enum" expression as well. Sounds really strange.

@jonathandturner: Has it been added in the update to the new error format maybe?

2016-09-16 10:31 UTC, petrochenkov commented
It's called "unit variant"/"unit struct" in other resolution-related error messages.

FWIW, I don't think all this extra cruft is an improvement.
"expected function, found `E`" => "expected function, found unit variant `E::Empty4`" would be enough.

2016-09-16 15:30 UTC, jonathandturner commented
Yeah, we have one for E0423 (https://github.com/rust-lang/rust/issues/35796), though I'm happy to update if we have better wording.

We've been trying to not use any technical terminology unless it's a part of the language (eg mutable is fine because of `mut`), so I'm reluctant to go with "unit variant".  I think "empty struct" or "empty enum" gets the idea across, with the exception that we may want to say "empty enum variant".

2016-09-16 16:50 UTC, estebank commented
I used the terminology from the original ticket, but I agree the error message as is isn't great.

I see some value in the errors for the different alternatives to have similar wording and format. The current error is a bit ambiguous, naming the enum's name, and a pointer to the variant's definition:

```bash
error: expected function, found `Test`
 --> file.rs:7:13
  |
7 |     let x = Test::Variant(1);
  |             ^^^^^^^^^^^^^^^^
  |
note: defined here
 --> file.rs:2:5
  |
2 |     Variant,
  |     ^^^^^^^
```

This gives you enough information to fix the issue, but I feel it is confusing for newcomers (as evidenced by #28533).

A compromise might be doing:

```bash
error: expected function, found `Test`
 --> file.rs:7:13
  |
7 |     let x = Test::Variant(1);
  |             ^^^^^^^^^^^^^^^^ empty enum variant called like a function
  |
  = help: did you mean to write: `Test::Variant`?
note: defined here
 --> file.rs:2:5
  |
2 |     Variant,
  |     ^^^^^^^
```

Also, I just tried using a struct variant as a unit variant, and there's no specialization in that error either, claiming it was called like a function:

```bash
error[E0423]: `Test::Variant2` is the name of a struct or struct variant, but this expression uses it like a function name
 --> file.rs:8:13
  |
8 |     let y = Test::Variant2;
  |             ^^^^^^^^^^^^^^ struct called like a function
  |
  = help: did you mean to write: `Test::Variant2 { /* fields */ }`?
```

2016-09-16 17:13 UTC, petrochenkov commented
>We've been trying to not use any technical terminology unless it's a part of the language (eg mutable is fine because of mut), so I'm reluctant to go with "unit variant".

It's in the [book](https://doc.rust-lang.org/book/structs.html#unit-like-structs), in the [reference](https://doc.rust-lang.org/reference.html#struct-expressions), in [other docs](https://github.com/rust-lang/rfcs/blob/master/text/1506-adt-kinds.md).
Also, the error is about unit variants specifically, not empty variants in general. I'd prefer to establish some terminology and use it consistently.

2016-09-16 17:17 UTC, jonathandturner commented
@petrochenkov - we're updating the book to follow a similar scheme, where we only use terminology that will be necessary to understand the language as we go.  Since we don't know the level of experience of the user when giving them an error message, it's better to err on the side of using language that more people can understand.

It's totally okay for the reference and RFCs to be more technical, I think.

2016-09-16 18:18 UTC, petrochenkov commented
@jonathandturner 
At least *some* part of diagnostics should be on the "technical side" and tell precisely what's wrong and give keywords to lookup in the glossary or reference. The primary error message is good candidate.
Error explanations, labels, notes, help - they can go into more novice friendly territory, give examples, etc.

2016-09-16 22:05 UTC, GuillaumeGomez commented
I agree with @petrochenkov here: people are using rust after all. If they don't know what a terminology is, it just means that they still need to learn it. Having a difference between "technical side" and any other side will bring more problems than solutions.

2016-09-16 22:10 UTC, jonathandturner commented
@GuillaumeGomez - that's a fair point for terminology that's already established terms.  I did a quick google through Google Scholar and didn't see either "unit struct" and "unit variant" mentioned, so I suspect these are terms we made up and there are easier ways to say those things.

2016-09-17 11:10 UTC, GuillaumeGomez commented
I'm pretty sure to already have saw them when I did ocaml, but maybe I'm wrong... Anyway, if there is another "official" terminology, we should fully switch to it (but I'm still pretty sure to have already saw them before...).

2016-09-17 19:36 UTC, estebank commented
New output

```bash
error[E0423]: `Test::Variant2` is the name of a struct or struct variant, but this expression uses it like a function name
 --> unit.rs:8:13
  |
8 |     let y = Test::Variant2("World");
  |             ^^^^^^^^^^^^^^ struct called like a function
  |
  = help: did you mean to write: `Test::Variant2 { /* fields */ }`?

error: expected function, found unit variant `Test::Variant`
 --> unit.rs:7:13
  |
7 |     let x = Test::Variant("Hello");
  |             ^^^^^^^^^^^^^^^^^^^^^^ unit enum variant called like a function
  |
  = help: did you mean to write: `Test::Variant`?
note: defined here
 --> unit.rs:2:5
  |
2 |     Variant,
  |     ^^^^^^^

error: aborting due to previous error
```

I defer the final wording to the team, but would like to know if the underlying code is sound.

2016-09-17 22:48 UTC, nikomatsakis commented
FWIW I have never liked the term "unit" (unit type, unit struct, etc). I know its origins in type theory and all but it doesn't really convey (to me) a strong sense of what it is and I don't think it's a term in widespread use. That said, I also don't like "data-less". It just doesn't...have a natural ring for me. "Empty enum variant" might be my favorite of the bunch, but maybe we can reword to avoid an adjective or in some other way?

Some thoughts:

- `Test::Variant2` is being called, but it is not a function
- `Test::Variant2` is being called, but it is an enum variant defined without arguments
  - Hint: Just write `Test::Variant2`, not `Test::Variant2()`

I see the value in sharing terminology between the book and the error messages -- but I think we should try to adopt terminology that is readily understood without having to go look it up. Basically I think avoiding "jargon" should be a high priority for us, so long as we are not introducing imprecision and confusion.

2016-09-22 12:03 UTC, pnkfelix commented
@nikomatsakis Any chance we could revise teminology in book and messaging to rename "unit enum variant" to "tag" ? Or is that already used to talk about the discriminant in general?

2016-09-27 21:10 UTC, nikomatsakis commented
@pnkfelix I'm not aware of us saying "tag" much, I guess people sometimes say "tagged union"?

2016-09-30 03:15 UTC, estebank commented
Rebased to fix the merge conflict and reworded the message slightly:

<img width="877" alt="screen shot 2016-09-29 at 19 52 52" src="https://cloud.githubusercontent.com/assets/1606434/18979463/f6e80226-867f-11e6-9728-3c57ae0f1364.png">

2016-09-30 09:44 UTC, GuillaumeGomez requested changes

2016-09-30 09:44 UTC, GuillaumeGomez commented on src/librustc_typeck/check/callee.rs
> +                } else { None };
Uuuuuuuurgh.

2016-09-30 09:44 UTC, GuillaumeGomez commented on src/librustc_typeck/check/callee.rs
> +                        } else { None }
Uuuuuuuurgh.

2016-09-30 09:44 UTC, GuillaumeGomez commented on src/librustc_typeck/check/callee.rs
> +                    } else { None }
Uuuuuuuurgh.

2016-09-30 09:44 UTC, GuillaumeGomez commented on src/librustc_typeck/check/callee.rs
> +                        if let hir::ExprCall(ref expr, _) = call_expr.node {
Create a `None` variable and remove all else cases.

2016-09-30 19:12 UTC, GuillaumeGomez approved these changes
All good for me.

2016-10-22 18:38 UTC, estebank commented
Rebased to fix merge conflict and squash history.

2016-10-25 16:04 UTC, estebank commented
r? @pnkfelix

2016-11-09 02:00 UTC, brson commented
@bors r+

Thanks @estebank and sorry for the delay!

2016-11-09 19:58 UTC, merged