Docs: Update to "Getting Started" section
rust-lang/rust pull request #36563
Opened 2016-09-18 12:24 UTC by vanjacosic

I came across #34523 and wanted to suggest a solution. See commit for details.

It seemed like a good place to start contributing, let me know if I did anything wrong 😇

2016-09-18 12:24 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @steveklabnik (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-09-25 12:13 UTC, GuillaumeGomez commented on src/doc/book/getting-started.md
> +We need to create a source file for our Rust program. Rust files always end
Extra whitespace at the end of the line.

2016-09-25 12:13 UTC, GuillaumeGomez requested changes
Just a little nit to fix and then I r+.

2016-09-26 19:22 UTC, steveklabnik commented
@bors: r+ rollup

thank you!

2016-09-27 11:05 UTC, merged