Add changelog for 1.12
rust-lang/rust pull request #36609
Opened 2016-09-21 01:43 UTC by brson

2016-09-21 01:43 UTC, rust-highfive commented
r? @aturon

(rust_highfive has picked a reviewer for you, use r? to override)

2016-09-21 02:19 UTC, retep998 commented on RELEASES.md
> +* [`FileType implements `Debug`]
Missing backtick

2016-09-21 02:21 UTC, retep998 requested changes

2016-09-21 03:37 UTC, WiSaGaN commented on RELEASES.md
> +* [The compiler can new be built against LLVM 3.9]
s/new/now

2016-09-21 07:25 UTC, killercup commented on RELEASES.md
> +* [`macro_rules!` invocations can be made within `macro_rules! invocations]
Missing backtick after second macro_rules

2016-09-21 16:12 UTC, japaric commented on RELEASES.md
> +* [`rustc` supports three new MUSL targets on ARM: `arm-unknown-linux-musleabi`,
perhaps should mention that these targets produce *statically* linked binaries.

2016-09-21 17:35 UTC, brson commented
Updated. Thanks for the feedback.

2016-09-21 17:52 UTC, sfackler commented on RELEASES.md
> +* [`RwLock` panics of the reader count overflows]
"if"

2016-09-22 16:08 UTC, arielb1 commented on RELEASES.md
> +* [`rustc` produces more compact code by more precisely identifying the live
That's only for MIR, and no improvement over pre-MIR.

2016-09-22 16:08 UTC, arielb1 requested changes

2016-09-23 03:00 UTC, liigo commented on RELEASES.md
> +  `--print-target-list`]
`--print    target-list`

2016-09-27 14:57 UTC, wesleywiser commented on RELEASES.md
> +  insider non-braces invocations]
I think this should be "inside" instead of "insider"

2016-09-27 17:31 UTC, brson commented
Updated.

2016-09-27 17:35 UTC, alexcrichton commented
@bors: r+

2016-09-27 19:21 UTC, brson commented
Now this needs to be backported to the _1.13_ beta as well.

2016-09-27 21:11 UTC, merged