Update Arc docs to match new Rc docs
rust-lang/rust pull request #36665
Opened 2016-09-23 02:26 UTC by kmcallister

`Rc` docs were updated in #36571. This applies similar changes to `Arc` docs.

r? @GuillaumeGomez

2016-09-23 03:29 UTC, frewsxcv commented on src/liballoc/arc.rs
> +// unhappy of a thread outlives the main thread and then exits at the same time
`s/of/if/`

2016-09-23 03:32 UTC, frewsxcv approved these changes

2016-09-23 10:32 UTC, GuillaumeGomez commented on src/liballoc/arc.rs
> -//! `Weak<T>` is a weak reference to the `Arc<T>` box, and it is created by
Why removing these lines? We generally have an example at the module level as well. I don't mind changing it but I don't like it to get completely removed.

2016-09-23 14:55 UTC, kmcallister commented on src/liballoc/arc.rs
> -//! `Weak<T>` is a weak reference to the `Arc<T>` box, and it is created by
It seems redundant. Isn't a link to the `Arc` docs good enough? Besides, the module-level docs are only visible if you're looking at the `alloc` crate directly and not `std`.

2016-09-25 12:00 UTC, GuillaumeGomez commented
Before r+, what do you think of this @steveklabnik?

2016-09-26 19:29 UTC, steveklabnik commented on src/liballoc/arc.rs
> -//! `Weak<T>` is a weak reference to the `Arc<T>` box, and it is created by
So, it's true that duplication isn't great. Usually, module-level docs should have an overview of the whole module, but with modules like these, it's just a container for Arc/Weak, and nothing else. As such, I think I'm fine with removing this in this instance. Especially given the `alloc/std` split as you mentioned.

2016-09-26 19:29 UTC, steveklabnik approved these changes

2016-09-26 19:29 UTC, steveklabnik commented on src/liballoc/arc.rs
> +// unhappy of a thread outlives the main thread and then exits at the same time
This still needs to be addressed.

2016-09-26 19:30 UTC, steveklabnik commented on src/liballoc/arc.rs
> +// Copyright 2012-2016 The Rust Project Developers. See the COPYRIGHT
uuuuuuuuuuuugh these headings.

2016-09-26 19:30 UTC, steveklabnik commented on src/liballoc/arc.rs
> +/// allocated in the heap. Invoking [`clone`][clone] on `Arc` produces
these links can be changed to drop the `[clone]`...

2016-09-26 19:31 UTC, steveklabnik commented on src/liballoc/arc.rs
> +/// [clone]: ../../std/clone/trait.Clone.html#tymethod.clone
.. and then put 

    [`clone`]

here.

2016-09-26 19:31 UTC, steveklabnik commented on src/liballoc/arc.rs
> +/// Shared pointers in Rust disallow mutation by default, and `Arc` is no
"references" is the proper term.

2016-09-26 19:32 UTC, steveklabnik commented on src/liballoc/arc.rs
> +/// # use std::sync::Arc;
I'm a bit torn here. Showing the imports is a bit better, I think: it's less confusing for newer users, and makes it copy/paste able.

2016-09-26 19:33 UTC, steveklabnik requested changes
Thanks so much for this! This PR is great, but I have a few nits.

2016-09-27 09:01 UTC, GuillaumeGomez commented on src/liballoc/arc.rs
> +/// # use std::sync::Arc;
I agree.

2016-09-27 19:33 UTC, kmcallister commented on src/liballoc/arc.rs
> +// Copyright 2012-2016 The Rust Project Developers. See the COPYRIGHT
Yeah... do you want me to leave it alone?

2016-09-27 19:34 UTC, kmcallister commented on src/liballoc/arc.rs
> +/// allocated in the heap. Invoking [`clone`][clone] on `Arc` produces
Is that so? I would have to change the link at the bottom to be `[\`clone\`]`, right? And that bugs me personally, although I agree it doesn't really matter.

2016-09-27 19:35 UTC, kmcallister commented on src/liballoc/arc.rs
> +/// Shared pointers in Rust disallow mutation by default, and `Arc` is no
Fixed.

2016-09-27 19:35 UTC, kmcallister commented on src/liballoc/arc.rs
> +/// # use std::sync::Arc;
Fixed.

2016-09-27 19:37 UTC, frewsxcv commented on src/liballoc/arc.rs
> +// Copyright 2012-2016 The Rust Project Developers. See the COPYRIGHT
https://github.com/rust-lang/rust/issues/9070#issuecomment-72514411

2016-09-27 21:37 UTC, kmcallister commented on src/liballoc/arc.rs
> +// unhappy of a thread outlives the main thread and then exits at the same time
Fixed.

2016-09-27 22:46 UTC, kmcallister commented
I updated the PR. Let me know what you think, and if it's good, I will squash the `Arc` changes.

2016-10-04 17:49 UTC, kmcallister commented
Rebased, and added one more link in `Rc` docs.

2016-10-06 17:11 UTC, steveklabnik approved these changes

2016-10-06 17:12 UTC, steveklabnik commented
@bors: r+ rollup

Thanks for your patience here @kmcallister

2016-10-07 00:49 UTC, kmcallister commented
Thanks @steveklabnik! A lot of the delay was on my side, anyway.

2016-10-07 14:58 UTC, merged