Improve documention troubleshooting missing linker. Fix #32208.
rust-lang/rust pull request #36672
Opened 2016-09-23 15:42 UTC by pmatos

@steveklabnik is this in the direction on how you want to see #32208 fixed?

2016-09-23 15:42 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @manishearth (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-09-23 15:48 UTC, steveklabnik commented
@pmatos yes, looks great to me, thank you!

@bors: r+ rollup

2016-09-23 19:11 UTC, retep998 commented on src/doc/book/getting-started.md
> +tools in `%PATH%`, namely `linker.exe`. However, if you have your
`link.exe`. Also it doesn't need to be in `PATH` because rustc can find msvc itself.

2016-09-23 19:14 UTC, steveklabnik commented
@bors: r-

gah, read that one wrong, sorry

2016-09-23 19:14 UTC, sfackler commented
@bors r-

Pending @retep998's link.exe comment.

2016-09-24 08:09 UTC, pmatos commented
@retep998 thanks, preparing new pull request.

2016-09-24 08:19 UTC, pmatos commented
@retep998 I tried with the new pull request to take your comments into consideration but if there's something else that can be improved, please let me know.

2016-09-26 19:34 UTC, steveklabnik commented on src/doc/book/getting-started.md
> +`windows-msvc` (Rust built on windows with Microsoft Visual Studio),
Windows, not windows.

2016-09-26 19:35 UTC, steveklabnik requested changes
One tiny nit, and then if @retep998 is happy, I'm happy.

2016-09-26 20:34 UTC, retep998 commented on src/doc/book/getting-started.md
> +this depends on having [Microsoft Visual Build Tools][msvbt]
Microsoft Visual ___C++___ Build Tools

2016-09-27 06:50 UTC, pmatos commented
@steveklabnik Done. @retep998 Done. 
The last two commits should have fixed the concerns you had. Thanks for the help on getting this pull request complete.

2016-09-27 14:06 UTC, steveklabnik commented
Great! Thanks so much for your patience here too.

One last question before I merge: it seems that the commit authorship is different than your github account. Is that what you intended? If so, it's fine, but otherwise, you might want to fix that before we merge :smile:

2016-09-27 14:07 UTC, steveklabnik approved these changes

2016-09-27 18:11 UTC, pmatos commented
You're right. Let me fix authorship. Sorry for this.

2016-09-27 18:19 UTC, steveklabnik commented
It's no worries! :)

2016-09-27 18:43 UTC, pmatos commented
@steveklabnik I have rewritten history on my end in order to change commit authorship which worked but now github falsely shows branch conflicts. Would you be ok with accepting this or do you want me to restart a brand new pull request on this?

2016-09-27 19:26 UTC, steveklabnik commented
Re-writing the history is totally fine :)

2016-09-27 19:27 UTC, steveklabnik commented
(the message in the bot is meant to be talking about _during review_, not administrative stuff like this at the end :smile: )

2016-09-27 19:34 UTC, pmatos commented
Great! So we are good to go. Happy to contribute. Anything else you have in mind that I could tackle next? 

On 27 September 2016 21:27:49 CEST, Steve Klabnik <notifications@github.com> wrote:
>(the message in the bot is meant to be talking about _during review_,
>not administrative stuff like this at the end :smile: )
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rust-lang/rust/pull/36672#issuecomment-249971613

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

2016-09-27 19:44 UTC, steveklabnik commented
(You have to force push, it didn't actually update the PR)

Thanks! We have the `A-docs` tag for doc stuff, and not all of them are super difficult: https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AA-docs

https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AA-docs+label%3AE-easy are specifically the ones tagged easy. Lots to do!

2016-09-27 19:44 UTC, steveklabnik commented
Oh, it's not that you didn't force push, it's that when you did, it somehow got on the wrong base. Try to rebase things and force push again.

2016-09-27 20:06 UTC, pmatos commented
@steveklabnik Is this ok now?

2016-09-27 20:13 UTC, steveklabnik commented
Hm, it still says 250+ commits :eyes: 

If you want some help, I can do it: I'd just need you to follow the second half here: https://github.com/blog/2247-improving-collaboration-with-forks

2016-09-27 20:18 UTC, pmatos commented
@steveklabnik The checkbox to allow edits from maintainers is enabled. Thanks for your help. I have no idea at the moment what kind of weird games git/github is playing with me.

2016-09-27 20:50 UTC, steveklabnik commented
Whew! @pmatos , I don't know what happened, but something was very wrong. Trying to deal with this made my git go a bit... intense.

![2016-09-27-163436_706x57_scrot](https://cloud.githubusercontent.com/assets/27786/18891210/3f7984f6-84d2-11e6-9c5b-6b297e9ef288.png)

However, I managed to make it work. Here's what I did:

1. `git rebase -i` to squash the four commits into one.
2. `git remote add upstream https://github.com/rust-lang/rust/`
3. `git fetch upstream`
4. `git reset --hard upstream/master`
5. `git cherry-pick cb3b03c`
6. `git push origin master -f`

Specifically step 4 says "make this branch equal to master" and then the cherry-pick lets you apply a random commit on top. Whew!

Can you verify that this commit is what you wanted to send in? It looks okay with me, but since I just re-wrote your history, it's important that you read it before we merge, since it's in your name :smile:

2016-09-27 20:56 UTC, pmatos commented
@steveklabnik many thanks for your time. roll it up. :) see in the next pull request.

2016-09-27 20:58 UTC, steveklabnik commented
Great! I think one of the problems might have been that it was on `master` instead of a branch, so maybe make a branch per PR next time? :smile:

2016-09-27 20:58 UTC, steveklabnik commented
@bors: r+ rollup

2016-09-28 06:39 UTC, pmatos commented
@steveklabnik I will use a branch per PR next time. Thanks.

2016-09-29 01:31 UTC, merged