Document init of HashSet/HashMap from vector
rust-lang/rust pull request #36740
Opened 2016-09-26 11:44 UTC by frehberg

2016-09-26 11:45 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @aturon (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-09-26 11:47 UTC, petrochenkov commented on src/libstd/collections/hash/map.rs
> +///       .iter().map(|&x| x).collect();
`.cloned()` can be used instead of `.map(|&x| x)`

2016-09-26 14:04 UTC, frehberg commented on src/libstd/collections/hash/map.rs
> +///       .iter().map(|&x| x).collect();
comment merged in

2016-09-26 15:54 UTC, jonas-schievink commented on src/libstd/collections/hash/map.rs
> +/// A HashMap with fixed list of elements can be initialized from vector:
"from an array"

2016-09-26 15:55 UTC, jonas-schievink commented on src/libstd/collections/hash/set.rs
> +/// HashSet with fixed list of elements can be initialized from vector:
"from an array"

2016-09-26 16:49 UTC, frehberg commented on src/libstd/collections/hash/map.rs
> +/// A HashMap with fixed list of elements can be initialized from vector:
comments have been merged in

2016-09-26 19:42 UTC, steveklabnik commented on src/libstd/collections/hash/map.rs
> +///     [ ("Norway", 100),
the space between `[(` should go away

2016-09-26 19:42 UTC, steveklabnik commented on src/libstd/collections/hash/map.rs
> +///       ("Iceland", 10) ]
same here

2016-09-26 19:42 UTC, steveklabnik commented on src/libstd/collections/hash/map.rs
> +///       .iter().cloned().collect();
does into_iter work here, rather than iter.cloned()?

2016-09-26 19:42 UTC, steveklabnik commented on src/libstd/collections/hash/set.rs
> +/// HashSet with fixed list of elements can be initialized from an array:
can you put a newline above and below this line, please?

2016-09-26 19:43 UTC, steveklabnik commented on src/libstd/collections/hash/map.rs
> +/// A HashMap with fixed list of elements can be initialized from an array:
can you put a newline before and after this line please?

2016-09-26 19:43 UTC, steveklabnik requested changes
Some small nits!

2016-09-27 08:30 UTC, frehberg commented on src/libstd/collections/hash/map.rs
> +///       .iter().cloned().collect();
no, I tried

2016-09-27 08:32 UTC, frehberg commented on src/libstd/collections/hash/map.rs
> +/// A HashMap with fixed list of elements can be initialized from an array:
done

2016-09-27 08:32 UTC, frehberg commented on src/libstd/collections/hash/map.rs
> +///     [ ("Norway", 100),
done

2016-09-27 14:01 UTC, frehberg commented
all comments merged in

2016-09-27 14:05 UTC, steveklabnik approved these changes

2016-09-27 14:05 UTC, steveklabnik commented
@bors: r+ rollup

thank you!

2016-09-28 07:24 UTC, frehberg commented
Sadly I don't have permissions to merge :( Will anybody merge this in now?

2016-09-28 15:37 UTC, steveklabnik commented
@frehberg @bors will do it automatically, you just have to wait. :) once we say `r+`, it's in the queue: https://buildbot.rust-lang.org/homu/queue/rust

2016-09-29 01:31 UTC, merged