[WIP] Move MIR towards a single kind of local
rust-lang/rust pull request #36752
Opened 2016-09-26 18:49 UTC by jonas-schievink

This PR modifies MIR to handle function arguments (`Arg`), user-defined variable bindings (`Var`), compiler-generated temporaries (`Tmp`), as well as the return value pointer equally. All of them are replaced with a single `Local` type, a few functions for iterating over different kinds of locals, and a way to get the kind of local we're dealing with (mainly used in the constant qualification/propagation passes).

I haven't managed to fix one remaining issue: A `StorageDead` not getting emitted for a variable (see the `TODO` in the test). If that's fixed, this is basically good to go.

r? @eddyb for changes to constant qualification and propagation I'm not quite sure about

2016-09-26 20:07 UTC, eddyb commented on src/librustc_mir/def_use.rs
> +        if let Lvalue::Local(local) = *lvalue {
Sweet! I'm sorry @pcwalton had to write this in the first place, but, this is all in hindsight.

2016-09-26 20:10 UTC, eddyb commented on src/librustc_mir/transform/promote_consts.rs
> +        self.assign(Lvalue::Local(RETURN_POINTER), rvalue, span);
Might be able to change `assign` to take a `Local`.

2016-09-26 20:13 UTC, eddyb commented on src/librustc_trans/mir/mod.rs
> +            .chain(mir.var_and_temp_iter().map(&mut allocate_local))
Why not move `allocate_local` into the `map` call?

2016-09-26 20:13 UTC, eddyb commented on src/test/mir-opt/deaggregator_test.rs
> +//     local0 = Baz { x: local3, y: const F32(0), z: const false }; // scope ...
Losing the names is unfortunate, do you think we could recover them?

2016-09-26 20:15 UTC, eddyb requested changes
LGTM modulo nits. cc @rust-lang/compiler In case anyone has anything to say against it.

2016-09-26 20:54 UTC, jonas-schievink commented on src/librustc_trans/mir/mod.rs
> +            .chain(mir.var_and_temp_iter().map(&mut allocate_local))
This has gone through a refactoring, I'll remove the `&mut`.

2016-09-26 20:59 UTC, jonas-schievink commented on src/test/mir-opt/deaggregator_test.rs
> +//     local0 = Baz { x: local3, y: const F32(0), z: const false }; // scope ...
Do you mean what kind of local each one is? We could recover that, but the full MIR dump already contains variable names so you can differentiate temps and variables. The full dump also has a comment on `local0` explaining that it's the return pointer.

2016-09-26 21:40 UTC, eddyb commented on src/test/mir-opt/deaggregator_test.rs
> +//     local0 = Baz { x: local3, y: const F32(0), z: const false }; // scope ...
It's harder to read though. Maybe if it was `%5` like in LLVM or `_5`, it'd be easier. But still.
I guess there's no easy way to recover that information due to how it's printed.

2016-09-26 22:29 UTC, eddyb commented on src/librustc/mir/repr.rs
> +    pub fn vars_and_temps_iter<'a>(&'a self) -> impl Iterator<Item=Local> + 'a {
This also doesn't need `'a`.

2016-09-26 22:53 UTC, eddyb commented on src/librustc_trans/mir/mod.rs
> +            if local == spread_local {
You can write this as `if Some(local) == mir.spread_arg`.

2016-09-26 23:00 UTC, eddyb requested changes

2016-09-28 21:24 UTC, solson commented
LGTM, but the loss of names in the MIR is somewhat annoying. If we can't easily recover the original names, then since all locals are now printed the same, I'd prefer to make the prefix short, like @eddyb's `_5` suggestion.

2016-09-28 22:12 UTC, jonas-schievink commented
We could recover the local kind (by threading a `&Mir` through the printer), but I actually like this way better. I also don't know how we should print this information without confusing the reader. Just replacing `local` with `arg` etc. doesn't seem appropriate since it suggests that arguments, variables and temps are still different things. Adding it to the comment might be worth a shot, but comments aren't placed on arguments.

For the record, here's a "full" MIR dump for a small test program after this patch:

```
fn testroutine(local1: u8, local2: u8) -> u8 {
    let mut local0: u8;                  // return pointer
    scope 1 {
        let local3: u8;                  // "start" in scope 1 at test.rs:1:16: 1:21
        let local4: u8;                  // "end" in scope 1 at test.rs:1:27: 1:30
    }
    let mut local5: std::iter::Map<std::ops::Range<u8>, [closure@test.rs:2:24: 2:33]>;
    let mut local6: std::ops::Range<u8>;
    let mut local7: u8;
    let mut local8: u8;
    let mut local9: u8;
    let mut local10: u8;
    let mut local11: (u8, bool);
    let mut local12: [closure@test.rs:2:24: 2:33];

    bb0: {
        StorageLive(local3);             // scope 0 at test.rs:1:16: 1:21
        local3 = local1;                 // scope 0 at test.rs:1:16: 1:21
        StorageLive(local4);             // scope 0 at test.rs:1:27: 1:30
        local4 = local2;                 // scope 0 at test.rs:1:27: 1:30
        StorageLive(local5);             // scope 1 at test.rs:2:5: 2:34
        StorageLive(local6);             // scope 1 at test.rs:2:5: 2:19
        StorageLive(local7);             // scope 1 at test.rs:2:6: 2:11
        StorageLive(local8);             // scope 1 at test.rs:2:6: 2:11
        local8 = local3;                 // scope 1 at test.rs:2:6: 2:11
        local7 = local8;                 // scope 1 at test.rs:2:6: 2:11
        StorageLive(local9);             // scope 1 at test.rs:2:13: 2:18
        StorageLive(local10);            // scope 1 at test.rs:2:13: 2:16
        local10 = local4;                // scope 1 at test.rs:2:13: 2:16
        local11 = CheckedAdd(local10, const 1u8); // scope 1 at test.rs:2:13: 2:18
        assert(!(local11.1: bool), "attempt to add with overflow") -> bb1; // scope 1 at test.rs:2:13: 2:18
    }

    bb1: {
        local9 = (local11.0: u8);        // scope 1 at test.rs:2:13: 2:18
        local6 = std::ops::Range::<u8> { start: local7, end: local9 }; // scope 1 at test.rs:2:6: 2:18
        StorageLive(local12);            // scope 1 at test.rs:2:24: 2:33
        local12 = [closure@test.rs:2:24: 2:33]; // scope 1 at test.rs:2:24: 2:33
        local5 = <std::ops::Range<u8> as std::iter::Iterator>::map::<u8, [closure@test.rs:2:24: 2:33]>(local6, local12) -> bb2; // scope 1 at test.rs:2:5: 2:34
    }

    bb2: {
        local0 = <std::iter::Map<std::ops::Range<u8>, [closure@test.rs:2:24: 2:33]> as std::iter::Iterator>::sum::<u8>(local5) -> bb3; // scope 1 at test.rs:2:5: 2:40
    }

    bb3: {
        StorageDead(local5);             // scope 1 at test.rs:2:5: 2:34
        StorageDead(local12);            // scope 1 at test.rs:2:24: 2:33
        StorageDead(local6);             // scope 1 at test.rs:2:5: 2:19
        StorageDead(local9);             // scope 1 at test.rs:2:13: 2:18
        StorageDead(local10);            // scope 1 at test.rs:2:13: 2:16
        StorageDead(local7);             // scope 1 at test.rs:2:6: 2:11
        StorageDead(local8);             // scope 1 at test.rs:2:6: 2:11
        StorageDead(local4);             // scope 0 at test.rs:1:27: 1:30
        StorageDead(local3);             // scope 0 at test.rs:1:16: 1:21
        return;                          // scope 1 at test.rs:1:1: 3:2
    }
}

fn testroutine::{{closure}}(local1: &mut [closure@test.rs:2:24: 2:33], local2: u8) -> u8 {
    let mut local0: u8;                  // return pointer
    scope 1 {
        let local3: u8;                  // "i" in scope 1 at test.rs:2:25: 2:26
    }
    let mut local4: u8;
    let mut local5: u8;
    let mut local6: (u8, bool);

    bb0: {
        StorageLive(local3);             // scope 0 at test.rs:2:25: 2:26
        local3 = local2;                 // scope 0 at test.rs:2:25: 2:26
        StorageLive(local4);             // scope 1 at test.rs:2:28: 2:29
        local4 = local3;                 // scope 1 at test.rs:2:28: 2:29
        StorageLive(local5);             // scope 1 at test.rs:2:32: 2:33
        local5 = local3;                 // scope 1 at test.rs:2:32: 2:33
        local6 = CheckedMul(local4, local5); // scope 1 at test.rs:2:28: 2:33
        assert(!(local6.1: bool), "attempt to multiply with overflow") -> bb1; // scope 1 at test.rs:2:28: 2:33
    }

    bb1: {
        local0 = (local6.0: u8);         // scope 1 at test.rs:2:28: 2:33
        StorageDead(local5);             // scope 1 at test.rs:2:32: 2:33
        StorageDead(local4);             // scope 1 at test.rs:2:28: 2:29
        StorageDead(local3);             // scope 0 at test.rs:2:25: 2:26
        return;                          // scope 1 at test.rs:2:24: 2:33
    }
}
```

```rust
fn testroutine(start: u8, end: u8) -> u8 {
    (start..end+1).map(|i| i * i).sum()
}
```

2016-09-28 22:13 UTC, jonas-schievink commented
We could possibly annotate each `localN` with the local kind, so you'd end up with `local0{return}`, `local1{arg0}`, `local3{var0 "start"}` and `local7{tmp3}` or something like that.

2016-09-28 23:25 UTC, eddyb commented
@bors r+

2016-09-29 18:20 UTC, merged