Test Case for Incr. Comp. Hash for enums #36674.
rust-lang/rust pull request #36840
Opened 2016-09-29 22:04 UTC by eulerdisk

Fixes #36674
Part of #36350

r? @michaelwoerister

2016-09-29 22:04 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @michaelwoerister (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-09-30 13:47 UTC, michaelwoerister requested changes
This is excellent, thank you so much, @eulerdisk! 
I've left two comments on things that should be fixed. After that this is good to merge :+1:

2016-09-30 13:47 UTC, michaelwoerister commented on src/test/incremental/hashes/enum_defs.rs
> +    Variant1 { b: u32, a: u32 },
`b` should be `f32`

2016-09-30 13:47 UTC, michaelwoerister commented on src/test/incremental/hashes/enum_defs.rs
> +// the same between rev2 and rev3.
The comment paragraph above still says 'struct' instead of 'enum'.

2016-09-30 15:14 UTC, michaelwoerister commented
@bors r+

Thanks @eulerdisk! 
(FYI: I used GH's new editing feature to make another "struct" -> "enum" correction in a comment)

2016-09-30 15:28 UTC, eulerdisk commented
@michaelwoerister Maybe there's another "struct" to change in line 21

2016-09-30 15:33 UTC, michaelwoerister commented
Yes, you're right, I'll fix it.

2016-09-30 15:33 UTC, michaelwoerister commented
@bors r-

2016-09-30 15:35 UTC, michaelwoerister commented
@bors r+

2016-10-02 06:53 UTC, merged

2016-10-02 20:58 UTC, michaelwoerister commented
:tada: