Avoid introducing `run` twice in the Rust book
rust-lang/rust pull request #36878
Opened 2016-09-30 23:47 UTC by BlueSpaceCanary

As it stands, getting-started.md and guessing-game.md both introduce `run` as a new command. I switched it so that the 2nd refers back to the first introduction, rather than re-introducing the command.

(First ever FOSS PR, sorry if I screwed up anything obvious :) )

r? @steveklabnik

2016-09-30 23:48 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @steveklabnik (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-10-01 11:11 UTC, GuillaumeGomez requested changes
All good except for the nit. Update, squash and then I r+.

2016-10-01 11:11 UTC, GuillaumeGomez commented on src/doc/book/getting-started.md
> +The `run` command comes in handy when you need to rapidly iterate on a
Missing an empty line before this one.

2016-10-02 22:35 UTC, BlueSpaceCanary commented on src/doc/book/getting-started.md
> +The `run` command comes in handy when you need to rapidly iterate on a
Fixed!

2016-10-03 09:08 UTC, GuillaumeGomez commented
Thanks!

@bors: r+ rollup

2016-10-04 15:29 UTC, merged