Speed up `plug_leaks`
rust-lang/rust pull request #36917
Opened 2016-10-03 01:18 UTC by nnethercote

Profiling shows that `plug_leaks` and the functions it calls are hot on some benchmarks. It's very common that `skol_map` is empty in this function, and we can specialize `plug_leaks` in that case for some big speed-ups.

The PR has two commits. I'm fairly confident that the first one is correct -- I traced through the code to confirm that the `fold_regions` and `pop_skolemized` calls are no-ops when `skol_map` is empty, and I also temporarily added an assertion to check that `result` ends up having the same value as `value` in that case. This commit is responsible for most of the improvement.

I'm less confident about the second commit. The call to `resolve_type_vars_is_possible` can change `value` when `skol_map` is empty... but testing suggests that it doesn't matter if the call is
omitted.

So, please check both patches carefully, especially the second one!

Here are the speed-ups for the first commit alone.

stage1 compiler (built with old rustc, using glibc malloc), doing debug builds:
```
futures-rs-test  4.710s vs  4.538s --> 1.038x faster (variance: 1.009x, 1.005x)
issue-32062-equ  0.415s vs  0.368s --> 1.129x faster (variance: 1.009x, 1.010x)
issue-32278-big  1.884s vs  1.808s --> 1.042x faster (variance: 1.020x, 1.017x)
jld-day15-parse  1.907s vs  1.668s --> 1.143x faster (variance: 1.011x, 1.007x)
piston-image-0. 13.024s vs 12.421s --> 1.049x faster (variance: 1.004x, 1.012x)
rust-encoding-0  3.335s vs  3.276s --> 1.018x faster (variance: 1.021x, 1.028x)
```
stage2 compiler (built with new rustc, using jemalloc), doing debug builds:
```
futures-rs-test  4.167s vs  4.065s --> 1.025x faster (variance: 1.006x, 1.018x)
issue-32062-equ  0.383s vs  0.343s --> 1.118x faster (variance: 1.012x, 1.016x)
issue-32278-big  1.680s vs  1.621s --> 1.036x faster (variance: 1.007x, 1.007x)
jld-day15-parse  1.671s vs  1.478s --> 1.131x faster (variance: 1.016x, 1.004x)
piston-image-0. 11.336s vs 10.852s --> 1.045x faster (variance: 1.003x, 1.006x)
rust-encoding-0  3.036s vs  2.971s --> 1.022x faster (variance: 1.030x, 1.032x)
```
I've omitted the benchmarks for which the change was negligible.

And here are the speed-ups for the first and second commit in combination.

stage1 compiler (built with old rustc, using glibc malloc), doing debug
builds:
```
futures-rs-test  4.684s vs  4.498s --> 1.041x faster (variance: 1.012x, 1.012x)
issue-32062-equ  0.413s vs  0.355s --> 1.162x faster (variance: 1.019x, 1.006x)
issue-32278-big  1.869s vs  1.763s --> 1.060x faster (variance: 1.013x, 1.018x)
jld-day15-parse  1.900s vs  1.602s --> 1.186x faster (variance: 1.010x, 1.003x)
piston-image-0. 12.907s vs 12.352s --> 1.045x faster (variance: 1.005x, 1.006x)
rust-encoding-0  3.254s vs  3.248s --> 1.002x faster (variance: 1.063x, 1.045x)
```
stage2 compiler (built with new rustc, using jemalloc), doing debug builds:
```
futures-rs-test  4.183s vs  4.046s --> 1.034x faster (variance: 1.007x, 1.004x)
issue-32062-equ  0.380s vs  0.340s --> 1.117x faster (variance: 1.020x, 1.003x)
issue-32278-big  1.671s vs  1.616s --> 1.034x faster (variance: 1.031x, 1.012x)
jld-day15-parse  1.661s vs  1.417s --> 1.172x faster (variance: 1.013x, 1.005x)
piston-image-0. 11.347s vs 10.841s --> 1.047x faster (variance: 1.007x, 1.010x)
rust-encoding-0  3.050s vs  3.000s --> 1.017x faster (variance: 1.016x, 1.012x)
```
@eddyb: `git blame` suggests that you should review this. Thanks!

2016-10-03 01:18 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2016-10-03 01:19 UTC, nnethercote commented
BTW, I used Valgrind's "DHAT" profilter to find this. It told me that lots of malloc calls were happening in and beneath `plug_leaks`.

2016-10-03 01:22 UTC, nnethercote commented
r? @eddyb

2016-10-03 02:17 UTC, eddyb requested changes

2016-10-03 02:17 UTC, eddyb commented on src/librustc/infer/higher_ranked/mod.rs
> +            result = value;
I think you can use early return to avoid indenting the entire function to the right.

2016-10-03 02:42 UTC, eddyb approved these changes

2016-10-03 02:43 UTC, eddyb commented
@bors r+

2016-10-03 12:01 UTC, arielb1 commented
We should also be doing this for `leak_check`.

2016-10-03 22:33 UTC, nnethercote commented
> We should also be doing this for leak_check.

`leak_check` doesn't show up nearly as high as `plug_leaks` in profiles, but it does show up. I'll do it in a follow-up. Thank you for the suggestion.

2016-10-04 08:35 UTC, arielb1 commented
leak-check done by #36931.

2016-10-04 09:45 UTC, nnethercote commented
> leak-check done by #36931.

Huh. I have a local patch to add an early return to `leak_check`. It produces a measurable speed-up of a couple of percent on some of the rustc-benchmarks, but it doesn't look anything like the commits in #36931.

2016-10-04 11:50 UTC, arielb1 commented
> Huh. I have a local patch to add an early return to `leak_check`. It produces a measurable speed-up of a couple of percent on some of the rustc-benchmarks, but it doesn't look anything like the commits in #36931.

How do you run the rustc benchmarks? I've been measuring bootstrap times. My patch short-cuts the fast path to `leak_check` at the callsites.

2016-10-04 15:29 UTC, merged

2016-10-04 22:24 UTC, nnethercote commented
@arielb1: I updated my local repo to get #36931 and the speed-ups from my local patch have now evaporated, so I guess its effect overlapped with the effect of your commit. My patch was simpler, though, adding just a `if skol_map.is_empty() { return Ok(()); }` near the start of `leak_check`. I don't know the code well enough to tell if that's functionally equivalent to your commit.

As for running the benchmarks, I compared two stage1 compilers that were both configured with `--enable-optimize --enable-debuginfo`. I used the `compare.py` script for this, see https://internals.rust-lang.org/t/recent-rustc-benchmarks-improvements/4153 for instructions.

2016-10-04 22:25 UTC, arielb1 commented
It should be functionally equivalent. Is it performance-equivalent?

2016-10-04 23:00 UTC, arielb1 commented
The `leak_check` patch *seems* to be slower. Will investigate more tomorrow.

2016-10-08 21:19 UTC, nnethercote commented
Good news -- the improvement for jld-day15-parser showed up clearly on perf.rust-lang.org.
![plug_leaks](https://cloud.githubusercontent.com/assets/1940286/19215948/fd415de6-8df7-11e6-8291-aa9ca7ce037e.png)
It's the big drop on the RHS on Oct 4. The time dropped from 1.402 to 1.199, which is a 1.169x speed-up (a.k.a a 14.5% reduction in execution time).

The other benchmarks mentioned in the first comment also saw speedups similar to what I measured locally, which is good.