rustc: Try again to disable NEON on armv7 linux
rust-lang/rust pull request #36933
Opened 2016-10-03 17:12 UTC by alexcrichton

This is a follow-up to #35814 which apparently didn't disable it hard enough. It
looks like LLVM's default armv7 target enables NEON so we'd otherwise have to
pass `-neon`, but we're already enabling armv7 with `+v7` supposedly, so let's
try just telling LLVM that the armv7 target is arm and then enable features
selectively.

Closes #36913

2016-10-03 17:12 UTC, rust-highfive commented
r? @eddyb

(rust_highfive has picked a reviewer for you, use r? to override)

2016-10-03 19:31 UTC, eddyb commented
@bors r+

2016-10-04 10:09 UTC, parched commented on src/librustc_back/target/armv7_unknown_linux_gnueabihf.rs
> +        llvm_target: "arm-unknown-linux-gnueabihf".to_string(),
Not sure if it matters, but you lose the `Tag_CPU_arch_profile: Application` attribute this way, but you could add it back with `+aclass`.
IMO `armv7-unknown-linux-gnueabihf` with `-neon,+vfp3,+d16` is all that is needed here.

2016-10-04 10:19 UTC, parched requested changes

2016-10-04 10:19 UTC, parched commented on src/librustc_back/target/armv7_unknown_linux_gnueabihf.rs
> +        llvm_target: "arm-unknown-linux-gnueabihf".to_string(),
You also lose `+dsp`.

2016-10-04 15:17 UTC, alexcrichton commented
@bors: r-

Ah thanks for the info @parched! I'll update.

2016-10-04 16:27 UTC, alexcrichton commented
@bors: r=eddyb

2016-10-04 16:36 UTC, parched reviewed
Fwiw the v7 and thumb2 are redundant when using the armv7 triple.

2016-10-04 23:30 UTC, merged