Optimize ObligationForest's NodeState handling.
rust-lang/rust pull request #36993
Opened 2016-10-06 03:59 UTC by nnethercote

This commit does the following.

- Changes `NodeState` from an enum to a `bitflags`. This makes it
  possible to check against multiple possible values in a single bitwise
  operation.

- Replaces all the hot `match`es involving `NodeState` with `if`/`else`
  chains that ensure that cases are handled in the order of frequency.

- Partially inlines two functions, `find_cycles_from_node` and
  `mark_as_waiting_from`, at two call sites in order to avoid function
  unnecessary function calls on hot paths.

- Fully inlines and removes `is_popped`.

These changes speeds up rustc-benchmarks/inflate-0.1.0 by about 7% when
doing debug builds with a stage1 compiler.

r? @arielb1

2016-10-07 19:51 UTC, arielb1 commented
That sounds like Totally The Wrong Way to handle an O(n^2) algorithm.

2016-10-07 20:02 UTC, arielb1 commented
For example, you should be able to get a better perf improvement by skipping over the entire middle "GC" steps if all obligations hit the `Ok(None)` case.

2016-10-07 22:04 UTC, nnethercote commented
> That sounds like Totally The Wrong Way to handle an O(n^2) algorithm.

I found this comment to be curt and unhelpful. It made me feel angry and bad. It probably wasn't your intent, but that is the effect it had. Please think about how you express yourself when criticizing other people's code.

2016-10-07 22:52 UTC, nnethercote commented
> For example, you should be able to get a better perf improvement by skipping over the entire middle "GC" steps if all obligations hit the Ok(None) case.

Can you elaborate more? Are you talking about `process_obligations`?

2016-10-08 09:31 UTC, arielb1 commented
> I found this comment to be curt and unhelpful. It made me feel angry and bad. It probably wasn't your intent, but that is the effect it had. Please think about how you express yourself when criticizing other people's code.

I'm sorry. 

I just think that the best way to deal with an O(n^2) case is to well, make it stop being O(n^2), rather than adding low-level optimizations to the specific O(n^2) part.

The main entry point of the obligation forest is `process_obligations`, and it is basically updates all obligations and then performs a "mark-and-sweep GC", where the running of the "finalizers" advances type inference. The mark-and-sweep GC takes O(n) time.

If nothing changes in the `process_obligation` loop, we can skip GCing altogether. Also, because cycles are rare (and shouldn't be present in the `inflate` example), we may want to use some hybrid of garbage collection and reference counting.

2016-10-10 02:42 UTC, nnethercote commented
> I just think that the best way to deal with an O(n^2) case is to well, make it stop being O(n^2), rather than adding low-level optimizations to the specific O(n^2) part.

To be clear: this is a reasonable opinion. The problem was not that you criticized my code, the problem was the way you criticized it. I suggest you avoid using the phrase "Totally The Wrong Way" in future reviews. Also, when suggesting alternative approaches, please describe them in reasonable detail. (Your follow-up comment about GCing was much better in this regard.)

2016-10-15 16:40 UTC, zatherz commented
@nnethercote You're right, he should've said "That's a shitty fucking way to handle a O(n^2) algorithm".

2016-10-15 21:48 UTC, zatherz commented
I noticed two "thumbs down emoji" reactions on my comment. I think it's disrespectful that such a thing exist - people who see a comment with a lot of "thumbs down emoji" reactions will immediately think negatively of the author before even reading the content of the comment. @rkruppe and @withoutboats, please consider removing them from my comment. I am surprised that GitHub, an entity that calls itself progressive and diverse still lets people insult and harass others like this.

2016-10-15 22:21 UTC, withoutboats commented
@rust-lang/core ^

2016-10-15 22:37 UTC, eddyb commented
@withoutboats You probably want @rust-lang/moderation as well.

2016-10-16 03:45 UTC, Manishearth commented
**Mod note:** As Nick said, please be constructive and nice in your criticism.

2016-10-16 12:21 UTC, zatherz commented
Why have my constructive and nice comments been removed? I'm very well acquainted with Rust's code of conduct and I consider @nnethercote's reply could very well be considered harassment. He tried to make @arielb1 feel bad for his reply. We shouldn't reply to harassment with harassment. I am so angry that I'm considering writing a Medium blog post about it and posting it to HackerNews.

2016-10-16 16:29 UTC, arielb1 commented
@zatherz 

Please don't defend me.

2016-10-17 11:20 UTC, Manishearth commented
**Mod note**: @zatherz Your comment was deleted for containing profanity and blatantly violating the code of conduct. If you have further questions about moderation or the code of conduct, please ask rust-mods@rust-lang.org or on one of the forums. This is not the place for such discussion.

2016-10-17 11:36 UTC, aturon commented
cc @nikomatsakis

2016-10-19 15:51 UTC, zatherz commented
How did my comment contain profanity when it was a carbon copy of @nnethercote's? And the last comment was satire.

2016-10-19 16:10 UTC, BurntSushi commented
**Moderator note**: As @Manishearth said, if you have a specific question or objection with our moderation, then please ask rust-mods@rust-lang.org. This isn't the place for it.

2016-10-21 21:06 UTC, nikomatsakis commented
Adding myself as another assigneee. Sorry I haven't taken a look yet. My initial reaction was somewhat similar to @arielb1 (i.e., I'd rather solve this from the top), but on the other hand the speed improvements that @nnethercote showed are promising! I'd like to give this a closer read. Will try to do ASAP! Apologies for the delay @nnethercote!

2016-10-21 21:29 UTC, nnethercote commented
> Adding myself as another assigneee

Oh, please wait a bit! #37231 landed recently and that changed the profiles significantly, so I've started reworking this PR but it's not ready yet.

2016-10-24 21:57 UTC, nikomatsakis commented
@nnethercote ok ping me

2016-10-24 22:33 UTC, nnethercote commented
I've updated. The commit no longer converts `NodeState` to bitflags, which was probably the most controversial part of the change. Due to #37231 this is now only a 2% win.

r? @nikomatsakis

It feels like there is still plenty of room for improvement in this benchmark, though I'm struggling to find those improvements myself. Here's Cachegrind's summary of the hottest functions (measurements are instruction counts).
```
1,743,729,697  src/librustc/traits/fulfill.rs:<rustc::traits::fulfill::FulfillProcessor<'a, 'b, 'gcx, 'tcx> as rustc_data_structures::obligation_forest::ObligationProcessor>::process_obligat
ion
1,470,943,055  src/librustc_data_structures/unify/mod.rs:<rustc_data_structures::unify::UnificationTable<K>>::get
1,291,117,019  src/librustc_data_structures/obligation_forest/mod.rs:<rustc_data_structures::obligation_forest::ObligationForest<O>>::process_obligations
1,098,926,283  src/librustc/infer/mod.rs:rustc::infer::InferCtxt::shallow_resolve
  982,723,014  src/libcore/result.rs:<rustc::traits::fulfill::FulfillProcessor<'a, 'b, 'gcx, 'tcx> as rustc_data_structures::obligation_forest::ObligationProcessor>::process_obligation
  819,129,999  src/libcore/iter/iterator.rs:<rustc::traits::fulfill::FulfillProcessor<'a, 'b, 'gcx, 'tcx> as rustc_data_structures::obligation_forest::ObligationProcessor>::process_obligatio
n
  608,066,958  src/librustc_data_structures/obligation_forest/mod.rs:<rustc_data_structures::obligation_forest::ObligationForest<O>>::compress
  465,370,000  /build/glibc-GKVZIf/glibc-2.23/string/::/sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:__memcpy_avx_unaligned
  446,992,304  /build/glibc-GKVZIf/glibc-2.23/malloc/malloc.c:_int_malloc
  433,218,885  src/librustc_data_structures/unify/mod.rs:<rustc_data_structures::unify::UnificationTable<K>>::get
  397,811,572  src/libcore/iter/range.rs:<rustc_data_structures::obligation_forest::ObligationForest<O>>::process_obligations
  397,030,502  ???:???
  368,654,892  src/libcore/option.rs:rustc::infer::InferCtxt::shallow_resolve
  321,693,196  src/libcore/iter/range.rs:<rustc_data_structures::obligation_forest::ObligationForest<O>>::compress
```
You have to squint a bit when interpreting them due to inlining but they give you a good idea. In particular, this call chain is very hot:
```
process_obligations -> process_obligation -> process_predicate -> shallow_resolve -> UnificationTable::probe -> UnificationTable::get
```
Any changes that can speed up any of those functions or reduce the number of calls in this chain are likely to help.

2016-10-31 15:35 UTC, nikomatsakis requested changes
r=me with the helper extracted (maybe tagged `#[inline]`?)

2016-10-31 15:35 UTC, nikomatsakis commented on src/librustc_data_structures/obligation_forest/mod.rs
> +                }
rather than making two copies of this code, maybe pull out a helper like `mark_neighbors_as_waiting_from(node)`?

2016-11-02 02:38 UTC, nnethercote commented on src/librustc_data_structures/obligation_forest/mod.rs
> +                }
Done.

2016-11-02 02:38 UTC, nnethercote commented
Comments addressed.

2016-11-02 04:33 UTC, aturon commented
@bors r=nikomatsakis

2016-11-02 21:02 UTC, nikomatsakis approved these changes

2016-11-02 21:02 UTC, nikomatsakis commented
@bors r+

2016-11-02 21:02 UTC, nikomatsakis commented
Not sure why @bors wasn't listening to @aturon. =)

2016-11-03 05:58 UTC, merged