Deprecate no_debug and custom_derive
rust-lang/rust pull request #37128
Opened 2016-10-12 21:12 UTC by nrc

r? @nikomatsakis

2016-10-12 21:13 UTC, nrc commented
cc #29721 and #29644

2016-10-17 17:37 UTC, nikomatsakis requested changes
Looks good; left a few suggestions for improvement.

2016-10-17 17:37 UTC, nikomatsakis commented on src/librustc_lint/builtin.rs
> +                                 &format!("use of deprecated attribute: {}", name));
Nit: probably we want:

```rust
"use of deprecated attribute: `{}`"
                   //         ^  ^ note ticks
```

right?

2016-10-17 17:37 UTC, nikomatsakis commented on src/librustc_lint/builtin.rs
> +                if let &feature_gate::AttributeGate::Gated(feature_gate::Stability::Deprecated,
Nit: this seems mega-inefficient...but probably it doesn't matter as there aren't that many attributes, and that table ain't that long, I guess?

2016-10-17 17:37 UTC, nikomatsakis commented on src/librustc_lint/builtin.rs
> +                if let &feature_gate::AttributeGate::Gated(feature_gate::Stability::Deprecated,
At minimum we could filter out the list of deprecations once rather than per attribute =)

2016-10-17 17:37 UTC, nikomatsakis commented on src/libsyntax/feature_gate.rs
> +            Gated(_, ref name, ref expl, _) => write!(fmt, "Gated({}, {})", name, expl),
why exclude `Stability` from the `Debug` printout?

2016-10-17 17:37 UTC, nikomatsakis commented on src/librustc_lint/builtin.rs
> +                                 &format!("use of deprecated attribute: {}", name));
Also, let's link the deprecation to a tracking issue

2016-10-18 04:43 UTC, nrc commented on src/librustc_lint/builtin.rs
> +                                 &format!("use of deprecated attribute: {}", name));
This follows the format for deprecated items. That probably should have back ticks too (added), but we don't have the tracking issue number anywhere so we can't link to it very easily.

2016-10-18 05:08 UTC, nrc commented
@nikomatsakis changes made

2016-10-18 17:38 UTC, nikomatsakis commented on src/librustc_lint/builtin.rs
> +                                 &format!("use of deprecated attribute: {}", name));
Well for deprecated items we give a reason, right? I imagined adding the issue number (or maybe just a string) to the `Deprecated` variant of `Stability`, in any case.

2016-10-18 19:55 UTC, nrc commented
More changes for review

2016-10-19 18:56 UTC, nrc commented
rebased

2016-10-19 19:51 UTC, nikomatsakis commented
tidy errors:

```
/build/src/libsyntax/feature_gate.rs:672: line longer than 100 chars
```

2016-10-19 19:51 UTC, nikomatsakis approved these changes

2016-10-19 19:51 UTC, nikomatsakis commented
r=me once tidy is fixed; thanks

2016-10-19 21:36 UTC, nrc commented
@bors: r=nikomatsakis

2016-10-24 21:53 UTC, nikomatsakis commented
@nrc

```
---- [compile-fail] compile-fail\feature-gate-no-debug-2.rs stdout ----
	
error: C:/bot/slave/auto-win-gnu-32-opt-rustbuild/build/src/test/compile-fail/feature-gate-no-debug-2.rs:14: unexpected "error": '14:1: 14:12: use of deprecated attribute `no_debug`: the `#[no_debug]` attribute is an experimental feature. See https://github.com/rust-lang/rust/issues/29721'

error: C:/bot/slave/auto-win-gnu-32-opt-rustbuild/build/src/test/compile-fail/feature-gate-no-debug-2.rs:14: expected error not found: use of deprecated attribute: no_debug

error: 1 unexpected errors found, 1 expected errors not found
status: exit code: 101
command: PATH="C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\obj\build\i686-pc-windows-gnu\stage2\bin;C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\obj\build\i686-pc-windows-gnu\stage2-tools\i686-pc-windows-gnu\release\deps;C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\obj\build\i686-pc-windows-gnu\stage2-rustc\i686-pc-windows-gnu\release\deps;C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\obj\build\i686-pc-windows-gnu\stage2-test\i686-pc-windows-gnu\release\deps;C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\obj\build\i686-pc-windows-gnu\stage2-std\i686-pc-windows-gnu\release\deps;C:\mingw-w64\i686-4.9.1-win32-dwarf-rt_v3-rev1\mingw32\bin;C:\Python27;C:\msys64\mingw32\bin;C:\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\msys64\usr\bin;C:\python27;C:\python27\scripts;C:\program files (x86)\inno setup 5;C:\program files (x86)\CMake\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0;C:\Program Files\CMake\bin" C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\obj\build\i686-pc-windows-gnu\stage2\bin\rustc.exe C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src/test\compile-fail\feature-gate-no-debug-2.rs -L C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\obj\build\i686-pc-windows-gnu\test\compile-fail --target=i686-pc-windows-gnu --error-format json -L C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\obj\build\i686-pc-windows-gnu\test\compile-fail\feature-gate-no-debug-2.stage2-i686-pc-windows-gnu.compile-fail.libaux -C prefer-dynamic -o C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\obj\build\i686-pc-windows-gnu\test\compile-fail\feature-gate-no-debug-2.stage2-i686-pc-windows-gnu.exe -Crpath -O -Lnative=C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\obj\build\i686-pc-windows-gnu\rust-test-helpers
unexpected errors (from JSON output): [
    Error {
        line_num: 14,
        kind: Some(
            Error
        ),
        msg: "14:1: 14:12: use of deprecated attribute `no_debug`: the `#[no_debug]` attribute is an experimental feature. See https://github.com/rust-lang/rust/issues/29721"
    }
]

not found errors (from test file): [
    Error {
        line_num: 14,
        kind: Some(
            Error
        ),
        msg: "use of deprecated attribute: no_debug"
    }
]

thread '[compile-fail] compile-fail\feature-gate-no-debug-2.rs' panicked at 'explicit panic', C:\bot\slave\auto-win-gnu-32-opt-rustbuild\build\src\tools\compiletest\src\runtest.rs:1097
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [compile-fail] compile-fail\feature-gate-no-debug-2.rs
```

2016-10-25 01:02 UTC, nrc commented
@bors: r=@nikomatsakis

2016-10-25 06:38 UTC, alexcrichton commented
Ok that failure [corresponds to](https://github.com/rust-lang/rust/blob/7a208648daa5ed2697527e0c6b79c0697f3950d8/src/liballoc_system/lib.rs#L233) a *failure to free* on Windows. That's terrifying!

@bors: retry

* #37292 37395

2016-10-25 16:06 UTC, alexcrichton commented
@bors: retry

2016-10-25 17:23 UTC, nikomatsakis commented
I'm inclined not to backport at this point. Not because it's harmful per se but just because we can just push deprecation back one cycle, so why not? What do you think @nrc?

2016-10-25 17:53 UTC, nrc commented
@nikomatsakis yeah, it is getting kind of late into the cycle for a backport.

2016-10-25 20:05 UTC, nikomatsakis commented
Removed beta-nominated tag: decided against backport.

2016-10-26 12:43 UTC, alexcrichton commented
Hm that's two segfaults at the same location on two different platforms, maybe a legitimate segfault?

2016-10-26 22:37 UTC, nrc commented
Dammit, Rust is not meant to segfault

2016-10-27 04:29 UTC, nrc commented
@bors: r=@alexcrichton

2016-10-27 11:06 UTC, merged

2016-10-27 19:52 UTC, nrc commented
FTR r was nikomatsakis, not alexcrichton

2016-12-11 06:47 UTC, SergioBenitez commented
I'd like to request that this deprecation be reverted, and I plan on submitting a PR to do so. This deprecation penalizes developers that write multiple types of syntax extensions instead of only custom derives, and it seems unnecessary while macros 2.0 are still some time away.

At present, it is possible to have a single `codegen` crate that implements custom attributes, custom derives, and procedural macros. All of these syntax extensions can be imported into a project with:

```rust
#![feature(plugin, custom_derive)]
#![plugin(codegen_crate)]
```

With this deprecation, however, this is no longer possible.

The alternative, of course, is to use macros 1.1. But custom derives via macros 1.1 must be implemented in a separate crate of type `proc-macro`. As a result, a _second_ crate must be created. This means that a project using custom derives _and_ custom attributes or procedural macros must implement syntax extensions in two different crates, and users using that project must depend on both crates and import the syntax extensions in two different ways:

```rust
#![feature(plugin)]
#![plugin(codegen_crate)]

#[macro_use] extern crate derive_crate;
```

I believe this will lead to user confusion: syntax extensions are now coming from two different crates, and they must be imported via completely different mechanisms. While before a single declaration brought in all syntax extensions, now two different declarations are used to bring in syntax extensions.

This is also significantly more unergonomic for the developer. This is because it is no longer feasible to easily share code between custom derives and other syntax extensions. The work-arounds are to have one create depend on the other, pushing logic to one "master" crate, or to create a _third_ crate that contains the shared logic. Clearly, neither are as ergonomic as the existing implementation.

All of this issues will likely be ameliorated by the unification macros 2.0 promises to bring. But macros 2.0 won't land in a nightly release any time soon, and they won't be stabilized until quite some time after that. So why deprecate this unnecessarily early? It penalizes developers that write multiple types of syntax extensions. We should keep this around until macros 2.0 are within reach of stabilization.