Mark enums with non-zero discriminant as non-zero
rust-lang/rust pull request #37224
Opened 2016-10-16 22:50 UTC by petrochenkov

cc https://github.com/rust-lang/rfcs/issues/1230
r? @eddyb

2016-10-16 23:04 UTC, eddyb requested changes
LGTM although I believe it could be simpler.

2016-10-16 23:04 UTC, eddyb commented on src/librustc/ty/layout.rs
> +        non_zero: bool,
You already have the range (see `rustc_trans::adt` for a way to determine if a value is in the range), why would this additional field be needed?

2016-10-16 23:04 UTC, eddyb commented on src/librustc/ty/layout.rs
> +                                        value: Int(value)
Maybe make this `match` produce the `Primitive` type and do the return after the `match`?

2016-10-16 23:04 UTC, eddyb commented on src/tools/compiletest/src/main.rs
> +#![cfg_attr(stage0, feature(question_mark))]
A few people hit this, I guess it got removed by accident. Thanks!

2016-10-16 23:10 UTC, petrochenkov commented on src/tools/compiletest/src/main.rs
> +#![cfg_attr(stage0, feature(question_mark))]
https://github.com/rust-lang/rust/pull/37202 contains it too :D
The sooner it lands the better.

2016-10-16 23:14 UTC, petrochenkov commented on src/librustc/ty/layout.rs
> +        non_zero: bool,
```
enum E {
    A = -1,
    B = 1,
}
```
`0` is in the range, but the enum is still non-zero.
(Also, `non_zero: bool` fits into previous padding so it doesn't increase the size of `Layout`)

2016-10-16 23:20 UTC, eddyb commented on src/librustc/ty/layout.rs
> +        non_zero: bool,
That's annoying. What I expect to eventually have would use `2` there, that's why I don't like `non_zero`: it's a special-case that makes sense mostly on pointers.
If you want to discuss the full niche optimization, I'd be down for it (IRC?).
If you don't want to change this implementation I'll r+ and take out this later (and/or switch to multi-ranges - LLVM actually supports them for `!range`).

2016-10-16 23:40 UTC, eddyb commented
@bors r+

2016-10-19 09:53 UTC, merged

2016-11-08 05:27 UTC, Manishearth commented
Btw, this caused some rather tricky issues in Servo (https://github.com/servo/rust-bindgen/issues/225).

IMO when changing reprs for things which may come from FFI (e.g. an enum) we should be more careful and have a cycle of warnings or a compiler note or something. Not sure how it would be implemented. (I agree that it's non ideal for C++ to abuse enums as bitflags but apparently it's a common pattern)

The only reason we could figure this out was because I knew how Rust's encoded enum debuginfo works, and I also knew that this PR had happened -- which is a rather high bar for being able to debug things like this. It's otherwise quite an opaque and nonsensical bug that feels like a compiler bug (in this case, setting `foo = Some(thing)` made it stay `None`)

cc @eddyb @nikomatsakis

2016-11-08 20:29 UTC, nikomatsakis commented
Hmm. @Manishearth I've not read this PR, but I assume that the enums in question were not marked as `#[repr(C)]` or any such thing?

2016-11-08 21:04 UTC, Manishearth commented
They were marked as `repr(u8)` which IIRC is equivalent?

2016-11-08 21:18 UTC, eddyb commented
That's just setting the size of the enum, it's still UB to have a value other than the assigned ones.