Fix a few links in the docs
rust-lang/rust pull request #37316
Opened 2016-10-20 23:55 UTC by ollie27

r? @steveklabnik

2016-10-21 12:26 UTC, GuillaumeGomez requested changes

2016-10-21 12:26 UTC, GuillaumeGomez commented on src/libcore/marker.rs
> +/// [E0204]: ../../error-index.html#E0204
I don't think this is a good idea. If you build docs locally, you'' have troubles.

2016-10-21 12:26 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +    /// [E0040]: ../../error-index.html#E0040
Same comment.

2016-10-21 12:27 UTC, GuillaumeGomez commented on src/libstd/path.rs
> +/// [`Deref`]: ../ops/trait.Deref.html
Nice catch!

2016-10-21 12:27 UTC, GuillaumeGomez commented
Thanks for your PR. Just a few things to fix and it should be good!

2016-10-21 15:15 UTC, ollie27 commented on src/libcore/marker.rs
> +/// [E0204]: ../../error-index.html#E0204
What do you mean? The error index is part of the local docs so this is no different to linking to the book like this.

2016-10-23 13:57 UTC, GuillaumeGomez commented on src/libcore/marker.rs
> +/// [E0204]: ../../error-index.html#E0204
If you run `make docs` (or any equivalent) then yes, but what if you just build libstd docs?

2016-10-31 13:40 UTC, GuillaumeGomez commented on src/libcore/marker.rs
> +/// [E0204]: ../../error-index.html#E0204
Hum, I see your point. I guess it's okay then.

2016-10-31 13:42 UTC, GuillaumeGomez approved these changes

2016-10-31 13:42 UTC, GuillaumeGomez commented
@bors: r+ rollup

2016-11-02 06:50 UTC, merged