Add documentation for Read, Write impls for slices and Vec
rust-lang/rust pull request #37343
Opened 2016-10-22 10:53 UTC by bluss

The Read for &[u8] and Vec<u8> are quite different, and we need this to
be reflected in the docs.

These documentation comments will be visible on the respective type's
page in the trait impls section.

2016-10-22 10:54 UTC, rust-highfive commented
r? @brson

(rust_highfive has picked a reviewer for you, use r? to override)

2016-10-27 09:38 UTC, GuillaumeGomez requested changes

2016-10-27 09:38 UTC, GuillaumeGomez commented on src/libstd/io/impls.rs
> +/// Note that each read from the slice updates the slice itself so that after
This sentence is too long and it makes it difficult to read.

2016-10-27 09:38 UTC, GuillaumeGomez commented on src/libstd/io/impls.rs
> +/// empty when end of file is reached.
"when the end of the input"?

2016-10-27 09:38 UTC, GuillaumeGomez commented on src/libstd/io/impls.rs
> +/// Note that each write to the slice updates the slice itself so that after
Same, the sentence is too long.

2016-10-27 12:07 UTC, bluss commented
Updated

2016-10-27 12:08 UTC, bluss commented on src/libstd/io/impls.rs
> +/// empty when end of file is reached.
The `Read` trait calls this situation "end of file" (with quotes) and/or EOF. So I want to keep that terminology. Using either EOF or "end of file" should be good?

2016-10-27 12:40 UTC, GuillaumeGomez commented on src/libstd/io/impls.rs
> +/// Note that reading updates the slice to point to just the yet unread part.
"Note that reading updates the slice to point to the yet unread part."? (I removed "just")

2016-10-27 12:40 UTC, GuillaumeGomez commented on src/libstd/io/impls.rs
> +/// Note that writing updates the slice to point to just the yet unwritten part.
Same as above.

2016-10-27 13:00 UTC, bluss commented on src/libstd/io/impls.rs
> +/// Note that reading updates the slice to point to just the yet unread part.
done!

2016-10-27 13:22 UTC, GuillaumeGomez commented
Thanks! Now please squash your commits and it's all good. :)

2016-10-27 13:22 UTC, GuillaumeGomez approved these changes

2016-10-27 16:39 UTC, bluss commented
Updated with the squash. Thanks for the help.

2016-10-28 09:23 UTC, GuillaumeGomez commented
@bluss: thanks to you!

@bors: r+ rollup

2016-10-28 20:42 UTC, merged