Show multiline spans in full if short enough
rust-lang/rust pull request #37369
Opened 2016-10-24 00:43 UTC by estebank

When dealing with multiline spans that span few lines, show the complete
span instead of restricting to the first character of the first line.

For example, instead of:

```
% ./rustc file2.rs
error[E0277]: the trait bound `{integer}: std::ops::Add<()>` is not satisfied
  --> file2.rs:13:9
   |
13 |        foo(1 + bar(x,
   |            ^ trait `{integer}: std::ops::Add<()>` not satisfied
   |
```

show

```
% ./rustc file2.rs
error[E0277]: the trait bound `{integer}: std::ops::Add<()>` is not satisfied
  --> file2.rs:13:9
   |
13 |        foo(1 + bar(x,
   |    ________^ starting here...
14 |   |            y),
   |   |_____________^ ...ending here: trait `{integer}: std::ops::Add<()>` not satisfied
   |
```

The [proposal in internals](https://internals.rust-lang.org/t/proposal-for-multiline-span-comments/4242/6) outlines the reasoning behind this.

2016-10-24 00:43 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @arielb1 (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-10-24 00:49 UTC, estebank commented on src/librustc_errors/emitter.rs
> +                let max_multiline_span_length = 20;
This will need to be much lower. I propose a value between 5 and 10.

2016-10-24 00:49 UTC, estebank commented on src/librustc_errors/snippet.rs
> +impl AnnotationType {
Some of this code could be removed as it's only used once, from inside of `impl Annotation`.

2016-10-24 16:24 UTC, dawirstejeck commented
Hi there! I think this is nice work! Couldn't you use the box-drawing characters for the lines? Like this
```
error[E0277]: the trait bound `{integer}: std::ops::Add<()>` is not satisfied
  --> file2.rs:13:9
   |
13 |      foo(1 + bar(x,
   | ┌────────┘ starting here...
14 | │            y),
   | └─────────────┘ ...ending here: trait `{integer}: std::ops::Add<()>` not satisfied
   |
```

2016-10-24 17:26 UTC, estebank commented
@dawirstejeck as per @nikomatsakis [in the original PR](https://github.com/rust-lang/rust/pull/36371#issuecomment-253504370):

>  I am avoiding unicode because many terminals can't handle it, so in the past we've tried to stick to ASCII.

I think it'd be neat if there were a way to [probe for unicode awareness](http://unix.stackexchange.com/questions/184345/detect-how-much-of-unicode-my-terminal-supports-even-through-screen) and use ascii safe characters or unicode accordingly, but that's beyond the scope of _this_ PR :)

2016-11-10 21:18 UTC, alexcrichton commented
r? @nikomatsakis 

Carrying over reviewer from the [original PR](https://github.com/rust-lang/rust/pull/36371). Looks like the [conclusion there](https://github.com/rust-lang/rust/pull/36371#issuecomment-254930275) was to close in favor of an [internals thread](https://internals.rust-lang.org/t/proposal-for-multiline-span-comments/4242) and open up a new one upon reaching consensus.

With my reading of the internals thread it looks like we haven't quite reached consensus yet, but @nikomatsakis seems to have been following more closely than I and may know more! @jonathandturner you were also interested in the first PR so you're likely to be interested in this one :)

2016-11-11 05:24 UTC, brson commented
Neat feature!

2016-11-11 15:26 UTC, nikomatsakis reviewed
Hmm, so I see that the `#[test]` infrastructure for testing snippet highlighting has been removed and move to UI tests. That's a bit unfortunate here, as it would have been really easy to make a bunch of tests for edge cases. I'm trying to think now if there is an easy way to reproduce it. Perhaps just adding back the `#[test]` stuff, but as @jonathandturner pointed out, it IS kind of a pain. 

Let me poke around a bit. I'd love to land this PR and don't want to block it on extensive work to build up a nice unit-testing infrastructure -- on the other hand, I'd feel a lot more comfortable if we could just write down tests for various edge cases (even if they don't occur in rustc...yet). The code seems pretty clean but oveall this formatting logic is easier to verify as a block-box, frankly.

2016-11-11 15:26 UTC, nikomatsakis commented on src/librustc_errors/emitter.rs
> +        for item in multiline_annotations.clone() {
This code confuses me a bit -- why doesn't it have to consider lines at all?

What if the input was like

```rust
X0
...
X1
Y0
...
Y1
```

With two multi-line spans stretching from X0..X1 and Y0..Y1... wouldn't that cause it to indent the Y case even though they do not in fact overlap?

I think I would expect this indentation to be done on the basis not of `start_col` and `end_col` but rather a (line, col) pair, or something like that.

2016-11-11 15:26 UTC, nikomatsakis commented on src/librustc_errors/emitter.rs
> +            if let AnnotationType::Multiline {line_start, line_end, depth} = ann.annotation_type {
all the annotations in this vector should be multiline, right? If so, can you add `else { panic!("non-multiline annotation in `multiline_annotations`!"); }` to make this clearer?

2016-11-14 23:37 UTC, nikomatsakis commented
Bah, I didn't get time to finish implementing that test harness. =(

The basic idea was just going to be adding some `#[test]` functions to librustc_errors which would gin up a file map etc.

2016-11-15 14:39 UTC, nikomatsakis commented
OK, so, I'm sorry I've been letting the perfect be the enemy of the good here. Let's land this PR and hack on a test harness separately. I've been toying with some stuff locally but the setup is kind of a pain so I don't want to block things on it. 

@bors r+

2016-11-15 14:40 UTC, nikomatsakis commented
@bors r-

Actually, I'd still like to know the answer to [this question](https://github.com/rust-lang/rust/pull/37369#discussion_r87601511) and have [this nit](https://github.com/rust-lang/rust/pull/37369#discussion_r87602242) addressed.

@estebank, you around?

2016-11-15 16:19 UTC, estebank commented
@nikomatsakis sure thing. I'll update the PR this afternoon.

2016-11-15 16:19 UTC, estebank commented on src/librustc_errors/emitter.rs
> +        for item in multiline_annotations.clone() {
Only the line needs to be taken into account. I probably just made a mistake here that, as I didn't have any overlapping example to test against, I didn't catch.

2016-11-15 16:20 UTC, estebank commented
> I've been toying with some stuff locally but the setup is kind of a pain so I don't want to block things on it.

If you publish branch I can use as a base to help, please let me know.

2016-11-15 18:42 UTC, nikomatsakis commented
@estebank ok I got something working in this branch:

https://github.com/nikomatsakis/rust/tree/multiline-span

In particular, you can just cherry-pick this commit:

https://github.com/nikomatsakis/rust/commit/0166ce0eea34f867988a1f4b778345225f18b4b7

The tests are all calls to this `test_harness()` function. You give it the input along with some spans and labels, specified as a string to search for (it takes the Nth match). Then you put in the expected output. You can see that the nested cases look a bit odd.

To run the tests, do `make check-stage0-syntax` (presuming you are using makefiles; I'm not sure of the `x.py` way to do this). The only annoying thing is that building libsyntax does take a while: on the other hand, you don't have to build the rest of the compiler if you make changes.

2016-11-15 19:42 UTC, estebank commented
> In particular, you can just cherry-pick this commit

Awesome!
> Then you put in the expected output. You can see that the nested cases look a bit odd.

It actually looks exactly how I expected it to look, as in, failing in the exact ways I expected it to be failing :)
```
--> test.rs:3:3
  |
3 |      X0 Y0
  |  _______- starting here...
  |      |
  |      starting here...
4 | ||   X1 Y1
  | |________- ...ending here: `Y` is a good letter too
  |       |
  |       ...ending here: `X` is a good letter
```

I would like to arrive with you to what the appropriate output for this case would be, where the multispans start (or end) both on the same line. I'm thinking something along the lines of:

```
--> test.rs:3:3
  |
3 |      X0 Y0
  |  _______- starting here...
  | | ___|
  | ||   starting here...
4 | ||   X1 Y1
  | |+_______- ...ending here: `Y` is a good letter too
  |  |____|
  |       ...ending here: `X` is a good letter
```
or

```
--> test.rs:3:3
  |
3 |      X0 Y0
  |  ____-__- starting here...
  | ||   |
  | ||   starting here...
4 | ||   X1 Y1
  | |⊥___-___- ...ending here: `Y` is a good letter too
  |       |
  |       ...ending here: `X` is a good letter
```

Both cases seem a bit messy, to honest.

This might be not as accurate but more composable:
```
--> test.rs:3:3
  |
3 |      X0 Y0
  | ++   -  - starting here...
  | ||   |
  | ||   starting here...
4 | ||   X1 Y1
  | ++   -   - ...ending here: `Y` is a good letter too
  |       |
  |       ...ending here: `X` is a good letter
```

2016-11-15 20:54 UTC, nikomatsakis commented
@estebank 

> Both cases seem a bit messy, to honest.

Yes, but this is an extreme case. I mostly want us to do "something sensible". I wonder if we can provide a bit of extra info, though, to help people disambiguate, like a number. Something like this (riffing on my preferred variant):

```
--> test.rs:3:3
  |
3 |      X0 Y0
  |  _______- starting here... [1]
  | | ___|
  | ||   starting here... [2]
4 | ||   X1 Y1
  | |+_______- ...ending here [2]: `Y` is a good letter too
  |  |____|
  |       ...ending here [1]: `X` is a good letter
```

Maybe we only show these if things overlap?

2016-11-15 20:55 UTC, nikomatsakis commented
Oh, and I removed the `+` in favor of just drawing a `|`, which I think reads a bit better.

2016-11-15 20:56 UTC, nikomatsakis commented
Another thought. I feel like having the label under a `|` is a bit confusing. I wonder if just having multiple `-` would be ok? Or just putting it next to the `|`?

```
--> test.rs:3:3
  |
3 |      X0 Y0
  |  _______- starting here... [1]
  | | ___- starting here... [2]
4 | ||   X1 Y1
  | ||_______- ...ending here [2]: `Y` is a good letter too
  |  |____|
  |       ...ending here [1]: `X` is a good letter
```

Anyway, it doesn't have to be perfect. As I said, this is an edge case.

2016-11-19 23:34 UTC, estebank commented
@nikomatsakis I modified the placing algorithm in order to get the look and feel exactly like I wanted, but if you look at [`test_snippet.rs` (thanks for setting it up in the first place)](https://github.com/rust-lang/rust/pull/37369/files#diff-61130b3d82e199cd5a6fecb64ab88cb5) the output for overlapping multiline spans is reasonable:

```nocode
--> test.rs:3:3
  |
3 |       X0 Y0 Z0
  |  _____^__-__- starting here...
  | | ____|__|
  | || ___|  starting here...
  | |||   starting here...
4 | |||   X1 Y1 Z1
5 | |||   X2 Y2 Z2
  | |||____^__-__- ...ending here: `Z` label
  |  ||____|__|
  |   |____|  ...ending here: `Y` is a good letter too
  |        ...ending here: `X` is a good letter
```

I didn't add support for the differentiating numbers yet, but if you think it is necessary, I can do it today.

2016-11-20 02:52 UTC, estebank commented on src/librustc_errors/emitter.rs
> +        for item in multiline_annotations.clone() {
Fixed.

2016-11-20 02:52 UTC, estebank commented on src/librustc_errors/emitter.rs
> +            if let AnnotationType::Multiline {line_start, line_end, depth} = ann.annotation_type {
Added.

2016-11-22 01:46 UTC, nikomatsakis commented
@estebank sounds awesome!

2016-11-22 01:47 UTC, nikomatsakis commented
I wouldn't worry about the numbers.

2016-11-22 22:37 UTC, nikomatsakis requested changes
Left one suggestion. One other thing I'd like: can you give a test with two disjoint ranges (touching distinct lines)?

I confess I didn't read the actual code in detail, but your comments gave me confidence that I **could** read it if ever I had to. =) The tests seem quite good though.

Basically r=me modulo the suggested refactoring and test (and feel free to tell me if you think my suggestion is not a good one).

2016-11-22 22:37 UTC, nikomatsakis commented on src/librustc_errors/emitter.rs
> +        //
❤️ loving the comments! ❤️

2016-11-23 23:20 UTC, estebank commented
>Left one suggestion. One other thing I'd like: can you give a test with two disjoint ranges (touching distinct lines)?

[Added (last two tests)](https://github.com/rust-lang/rust/pull/37369/files#diff-61130b3d82e199cd5a6fecb64ab88cb5R448).

>this code might be cleaner if you made a struct for MultilineAnnotation, and then adjusted the enum to wrap the struct. Something like:

There's [some duplication of fields](https://github.com/rust-lang/rust/pull/37369/files#diff-ef5750d4adc18cc358e6394c4ad36a36R46) now for this to work, but I don't think it'll make the code any harder to follow.

>feel free to tell me if you think my suggestion is not a good one

Other than the issue mentioned above, the suggestion makes sense.

2016-11-29 16:23 UTC, nikomatsakis approved these changes

2016-11-29 16:23 UTC, nikomatsakis commented
@bors r+

Very nice.

2016-11-29 22:03 UTC, merged