Update testing.md to reflect changes to cargo new
rust-lang/rust pull request #37368
Opened 2016-10-23 22:15 UTC by trotter

`cargo new` now creates a `src/lib.rs` with a `tests` module by default. I've updated the earlier examples in this doc to reflect this. However, I don't know how we want to approach the "introduction" to idiomatic testing that follows in "the tests module" section. I _think_ it should be broken apart, with the module concept being introduced early on, and the `super` concept being addressed when we hit the `add_two` example. I'd like to get agreement on that being the right approach before I do it though.

I _also_ removed the `#fn main() {}` hidden at the beginning of each example, as these cause Rust Playground to not treat the file as a set of tests that it can run. Removing it _should_ cause Rust Playground to display a "Test >" button in the top left when a user runs the code, which will allow them to see the test runner output.

2016-10-23 22:15 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @steveklabnik (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-10-23 23:24 UTC, steveklabnik commented
I recently confronted this for the new book's testing chapter: https://github.com/rust-lang/book/pull/288

maybe a similar approach would be good? I think I did what you did, but it's late and I'm tired; will re-read this PR tomorrow.

> I also removed the #fn main() {} hidden at the beginning of each example, as these cause Rust Playground to not treat the file as a set of tests that it can run. Removing it should cause Rust Playground to display a "Test >" button in the top left when a user runs the code, which will allow them to see the test runner output.

:+1: IIRC this was due to a limitation of long-ago Rust.

2016-10-24 04:04 UTC, ollie27 commented
The `# fn main() {}` is to stop rustdoc from surrounding all of the code in a `fn main` block. See #31249. Removing it will generate links like [this](https://play.rust-lang.org/?code=fn%20main()%20%7B%0Apub%20fn%20add_two(a%3A%20i32)%20-%3E%20i32%20%7B%0A%20%20%20%20a%20%2B%202%0A%7D%0A%0A%23%5Bcfg(test)%5D%0Amod%20tests%20%7B%0A%20%20%20%20use%20super%3A%3Aadd_two%3B%0A%0A%20%20%20%20%23%5Btest%5D%0A%20%20%20%20fn%20it_works()%20%7B%0A%20%20%20%20%20%20%20%20assert_eq!(4%2C%20add_two(2))%3B%0A%20%20%20%20%7D%0A%7D%0A%7D) which still doesn't work. One (still hacky) solution would be to change it to somthing like `# // fn main` which will generate links like [this](https://play.rust-lang.org/?code=%2F%2F%20fn%20main%0Apub%20fn%20add_two(a%3A%20i32)%20-%3E%20i32%20%7B%0A%20%20%20%20a%20%2B%202%0A%7D%0A%0A%23%5Bcfg(test)%5D%0Amod%20tests%20%7B%0A%20%20%20%20use%20super%3A%3Aadd_two%3B%0A%0A%20%20%20%20%23%5Btest%5D%0A%20%20%20%20fn%20it_works()%20%7B%0A%20%20%20%20%20%20%20%20assert_eq!(4%2C%20add_two(2))%3B%0A%20%20%20%20%7D%0A%7D%0A) instead.

2016-10-24 20:36 UTC, steveklabnik commented
Ah, interesting.

@rust-lang/docs what do you think we should do here?

2016-10-24 20:57 UTC, trotter commented
Ahh cool. I didn't realize there was a new book underway. I'm happy to take a look at that and use it as an example for making the existing docs reflect the current state of `cargo new`.

Once we have clarity on what to do around `# fn main() {}`, I'm happy to go implement :smile:

2016-11-02 10:47 UTC, GuillaumeGomez requested changes

2016-11-02 10:47 UTC, GuillaumeGomez commented on src/doc/book/testing.md
> +   }
bad indent

2016-11-02 10:48 UTC, GuillaumeGomez commented
@steveklabnik: I like these changes so 👍 for me.

2016-11-03 10:47 UTC, steveklabnik commented
@trotter I would like to merge this, can you rebase and fix that spacing issue @GuillaumeGomez pointed out?

2016-11-08 15:30 UTC, trotter commented
@steveklabnik Updated, but I want ensure that I didn't muck things up with the removal of `# fn main() {}` before you merge.

2016-11-08 18:54 UTC, steveklabnik commented on src/doc/book/testing.md
> -# fn main() {}
so, testing this, i still get a link like

    https://play.rust-lang.org/?code=fn%20main()%20%7B%7D%0A%23%5Btest%5D%0Afn%20it_works()%20%7B%0A%7D%0A

which has the main, not wrapping the example.

2016-11-08 18:55 UTC, steveklabnik commented
@ollie27 i'm not seeing the behavior you're talking about, am i missing something?

2016-11-08 20:43 UTC, ollie27 commented
```rust
# fn main() {}
#[test]
fn it_works() {}
```

produces: https://play.rust-lang.org/?code=fn%20main()%20%7B%7D%0A%23%5Btest%5D%0Afn%20it_works()%20%7B%7D%0A

```rust
#[test]
fn it_works() {}
```

produces: https://play.rust-lang.org/?code=fn%20main()%20%7B%0A%23%5Btest%5D%0Afn%20it_works()%20%7B%7D%0A%7D

```rust
# // please don't add fn main
#[test]
fn it_works() {}
```

produces: https://play.rust-lang.org/?code=%2F%2F%20please%20don%27t%20add%20fn%20main%0A%23%5Btest%5D%0Afn%20it_works()%20%7B%7D%0A

Only the third one shows the "Test ▶" button in the playground. Just removing `# fn main() {}` causes the whole thing to be surrounded in a `fn main` block like the second example.

2016-11-08 20:53 UTC, steveklabnik commented
Oh, the isuse is the *test button* not being valid.

@trotter can you take away the `# main()` stuff?

2016-11-09 02:39 UTC, trotter commented
@steveklabnik Yep! That's what I'm planning on getting fixed before saying we're done :smile:

2016-11-10 16:00 UTC, trotter commented
@steveklabnik This should be good to merge now. I've fixed the examples such that play.rust-lang.org will correctly run the code as tests. I also removed my earlier additions of `mod tests` in favor of the approach you took in rust-lang/book#288. Let me know if anything else needs changing.

2016-11-10 16:50 UTC, GuillaumeGomez commented
Well, still remain a good big squash. :p

2016-11-10 17:46 UTC, steveklabnik commented
Whoah, it just looks for `fn main()` and not something syntactically valid? interesting...

2016-11-10 18:43 UTC, trotter commented
Fun. I had been running `make docs`, but apparently missed these tests that are now failing. I'll investigate tonight most likely.

2016-11-10 19:09 UTC, trotter commented
I went ahead and took a quick look. It appears that the doc tests are attempting to run the code and are failing because it has no main function. I see two quick ways to making it happy:

1. remove the comments from `# // fn main` and turn it into `# fn main() {}`. I don't like this though, as it results in not having the 'test' button in play.rust-lang.org. 
2. add `,ignore` to the markdown language indicator, which will cause the test runner to ignore these ones. This _seems_ good, as it results in things displaying happily to person reading the documentation and the tests pass. It also _seems_ bad though, in that this code _isn't_ getting exercised by the test runner. This means that any typos that show up later will only be found by sad users telling us that the code didn't run when they ran it on play.rust-lang.org.

My preference is to go with number 2 for now, but I'd also love to know if anyone has thoughts on how to get `make check-docs` to run these code examples without having an `fn main() {}` around the whole thing.

2016-11-10 21:55 UTC, steveklabnik commented
I am also leaning towards `ignore`. @rust-lang/docs

2016-11-11 06:01 UTC, trotter commented
@steveklabnik OK, I pushed up the changes with `ignore`. Assuming @rust-lang/docs is cool with it, this should be good to go.

2016-11-11 11:16 UTC, GuillaumeGomez approved these changes

2016-11-11 11:17 UTC, GuillaumeGomez commented
Considering the current situation, I think it's ok. Thanks for all your work here @trotter!

2016-11-11 16:46 UTC, steveklabnik commented
@bors: r+ rollup

Yup, let's merge. If anyone else has an issue, please let me know 😄

2016-11-12 12:15 UTC, merged