improve docs for Index and IndexMut
rust-lang/rust pull request #37438
Opened 2016-10-27 23:51 UTC by Cobrand

This mainly changes the boring example of Foo/Bar of `IndexMut` into a better one.

Also added explanations about syntactic sugar for `v[index]`.

Closes #36329

2016-10-27 23:51 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @sfackler (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-10-28 04:21 UTC, sfackler commented
r? @steveklabnik

2016-10-28 14:03 UTC, GuillaumeGomez requested changes
Excellent work! Just a few typos and should be good to go!

2016-10-28 14:03 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +/// `let value = v[index]` if `value` implements `Copy`.
Missing `Copy` trait url.

2016-10-28 14:03 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +/// `IndexMut` is used instead. This allows nice things such as
Missing url for `IndexMut`.

2016-10-28 14:03 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +/// an immutable value is requested, the `Index` trait is used instead. This
Missing url for `Index`.

2016-10-28 14:03 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +/// allows nice things such as `v[index] = value` if `value` implements `Copy`.
Missing url for `Copy`.

2016-10-28 14:03 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +/// A very simple implementation of a Balance struct that has two sides, where
"of a `Balance` struct"

2016-10-28 14:03 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +///     pub right:Weight
Missing comma at the end of the line.

2016-10-28 14:03 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +///     Pound(f32)
Missing comma at the end of the line.

2016-10-28 14:03 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +///     Right
Missing comma at the end of the line.

2016-10-28 14:03 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +///             Side::Right => &self.right
Missing comma at the end of the line.

2016-10-28 14:03 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +///     fn index<'a>(&'a self, index: Side) -> &'a Weight {
Please put an empty line before this one. It helps for the reading.

2016-10-28 14:03 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +///             Side::Right => &mut self.right
Missing comma at the end of the line.

2016-10-28 14:03 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +///     // in this case balance[Side::Right] is sugar for
"in" -> "In"

2016-10-28 14:03 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +///     // however in this case balance[Side::Left] is sugar for
"however" -> "However"

2016-10-28 14:03 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +///
Please remove this empty line.

2016-10-28 15:21 UTC, Cobrand commented
Thanks for the comments, I fixed what you said and it should be fine now.

2016-10-28 17:25 UTC, GuillaumeGomez approved these changes

2016-10-28 17:26 UTC, GuillaumeGomez commented
Thanks!

@bors: r+ rollup

2016-10-31 17:41 UTC, merged