Fix ICE on printing closure types(?).
rust-lang/rust pull request #37459
Opened 2016-10-28 22:28 UTC by Mark-Simulacrum

I'm not quite sure what this is doing, so let me know and I can update the commit and all.

Fixes #36622.

r? @eddyb or @arielb1

2016-10-28 23:11 UTC, eddyb requested changes
r=me with nits fixed.

2016-10-28 23:11 UTC, eddyb commented on src/librustc/mir/repr.rs
> +                                             &[])?;
Can this fit on a single line?

2016-10-28 23:11 UTC, eddyb commented on src/librustc/util/ppaux.rs
> +        // parent that DOES have an entry.
This talks about item types but we care only about generics

2016-10-28 23:32 UTC, eddyb commented
@bors r+

2016-10-28 23:55 UTC, eddyb commented
@bors r+

2016-10-29 21:19 UTC, eddyb commented
@bors r- (Travis failed)

2016-10-29 22:02 UTC, eddyb commented
@bors r+

2016-10-30 14:13 UTC, Mark-Simulacrum commented
@eddyb Rebased; Re-r+?

2016-10-30 14:24 UTC, petrochenkov commented
@bors r=eddyb

2016-10-31 00:01 UTC, merged

2016-10-31 01:20 UTC, eddyb commented
Sadly this is incomplete (it can cause a call of `item_name` on a closure which won't work).

2016-11-03 01:17 UTC, brson commented
Nominating because this is required for https://github.com/rust-lang/rust/pull/37491.

2016-11-03 17:42 UTC, nikomatsakis commented
Approved for backport because @eddyb said so. =)

cc @rust-lang/compiler