Fix terminfo database search path
rust-lang/rust pull request #37469
Opened 2016-10-29 20:29 UTC by meh

This is more consistent with what every other program does, I happened to have `TERMINFO` set as `/usr/share/terminfo` but had the actual database in `~/.terminfo`, regardless of that every other terminfo/ncurses based software picked up the one in the home correctly.

This just puts the path in `TERMINFO` at the top of the search paths, and moves the home checking to the default search paths section.

2016-10-29 20:30 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @alexcrichton (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-11-06 09:02 UTC, sugar700 requested changes

2016-11-06 09:02 UTC, xfix commented on src/libterm/terminfo/searcher.rs
> +    if let Ok(dirs) = match env::var("TERMINFO_DIRS") {
`match` here is an error.

2016-11-10 21:30 UTC, alexcrichton commented
@bors: r+

Thanks @meh, sorry for the delay! Feel free to ping PRs if you feel like they're getting stale, they fall through the cracks occasionally by accident!

2016-11-11 22:39 UTC, alexcrichton commented
@bors: retry force clean

2016-11-12 08:10 UTC, merged