Add E0532 error explanation
rust-lang/rust pull request #37475
Opened 2016-10-29 23:34 UTC by AndiDog

This resolves one of the error list in https://github.com/rust-lang/rust/issues/35347 - just because I stumbled over it today.

I assumed the error code should be removed from `register_diagnostics!` because it's now defined above.

Since that is my first code contribution, please check that all is in order. It would be helpful to know how to run the test for the `compile_fail,E0532` part. I did `make check-stage1-cfail NO_REBUILD=1` but that doesn't test the inlined example.

r? @GuillaumeGomez

2016-10-29 23:35 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @GuillaumeGomez (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-10-30 10:49 UTC, GuillaumeGomez requested changes

2016-10-30 10:49 UTC, GuillaumeGomez commented on src/librustc_resolve/diagnostics.rs
> +
Please remove this empty line.

2016-10-30 10:49 UTC, GuillaumeGomez commented on src/librustc_resolve/diagnostics.rs
> +    Failed(String), // error message
I'm not sure this comment helps. It could actually mislead readers.

2016-10-30 10:49 UTC, GuillaumeGomez commented on src/librustc_resolve/diagnostics.rs
> +    Failed(String), // error message
Same.

2016-10-30 10:49 UTC, GuillaumeGomez commented on src/librustc_resolve/diagnostics.rs
> +
Same.

2016-10-31 00:55 UTC, AndiDog commented
Changes made as requested

2016-10-31 10:24 UTC, GuillaumeGomez approved these changes

2016-10-31 10:25 UTC, GuillaumeGomez commented
Thanks!

@bors: r+ rollup

2016-10-31 17:41 UTC, merged