Do't provide hint to add lifetime on impl items
rust-lang/rust pull request #37481
Opened 2016-10-30 06:01 UTC by estebank

```rust
use std::str::FromStr;

pub struct Foo<'a> {
    field: &'a str,
}

impl<'a> FromStr for Foo<'a> {
    type Err = ();
    fn from_str(path: &str) -> Result<Self, ()> {
        Ok(Foo { field: path })
    }
}
```

would give the following hint:

```nocode
help: consider using an explicit lifetime parameter as shown: fn from_str(path: &'a str) -> Result<Self, ()>
  --> <anon>:9:5
   |
9  |     fn from_str(path: &str) -> Result<Self, ()> {
   |     ^
```

which is never correct, since then there will be a lifetime mismatch
between the impl and the trait.

Remove this hint for all impl items.

Re: #37363.

2016-10-30 06:01 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @eddyb (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-10-30 06:34 UTC, eddyb requested changes

2016-10-30 06:34 UTC, eddyb commented on src/librustc/infer/error_reporting.rs
> +                            (true, Some((&sig.decl,
I think you can just add an early return here and that might be enough. Also this should only be done if the `impl` is for a trait, not inherent.

2016-11-10 01:53 UTC, estebank commented on src/librustc/infer/error_reporting.rs
> +                            (true, Some((&sig.decl,
* Changed to early return
* Check that impl if for a trait
* Add unittest

2016-11-10 02:07 UTC, eddyb approved these changes

2016-11-10 02:08 UTC, eddyb commented
@bors r+

2016-11-10 21:31 UTC, alexcrichton commented
@estebank looks like the travis failures are legit?

2016-11-10 22:14 UTC, estebank commented
@alexcrichton Yes. I'll fix tonight. I need a new r+ after pushing a fix, right?

2016-11-10 22:15 UTC, alexcrichton commented
@estebank indeed!

2016-11-11 19:22 UTC, estebank commented
@alexcrichton @eddyb fixed the test error.

2016-11-11 19:25 UTC, alexcrichton commented
@bors: r=eddyb

2016-11-12 12:15 UTC, merged