Support `#[macro_reexport]`ing custom derives
rust-lang/rust pull request #37542
Opened 2016-11-02 22:14 UTC by jseyfried

*Pending #37463.*

Requires `#![feature(macro_reexport)]` and `#![feature(proc_macro)]`.
r? @nrc

2016-11-02 22:20 UTC, jseyfried commented
cc #37542 #35900
cc @alexcrichton

2016-11-03 16:05 UTC, alexcrichton commented
Nice!

2016-11-07 02:19 UTC, nrc requested changes
I'm not clear on what is going on here - why do we want macro_reexport and custom derive to work together? I would like macro_reexport to disappear entirely and I don't know of any motivation for it to work with custom derive. I assume this is a step towards something else, but I'm not sure what

2016-11-07 02:19 UTC, nrc commented on src/test/compile-fail-fulldeps/proc-macro/cannot-link.rs
> -fn main() {}
This test should still be valid, no?

2016-11-07 02:19 UTC, nrc commented on src/test/compile-fail-fulldeps/proc-macro/shadow.rs
>  fn main() {}
Should we have a test that uses macro_reexport with a custom derive?

2016-11-07 02:19 UTC, nrc commented on src/librustdoc/visit_ast.rs
> +                        LoadedMacro::ProcMacro(..) => continue, // FIXME
This FIXME needs more explanation

2016-11-07 02:41 UTC, jseyfried commented on src/test/compile-fail-fulldeps/proc-macro/cannot-link.rs
> -fn main() {}
Is there a good reason to disallow it? For example, we will want to support:
```rust
extern crate derive_a;
use derive_a::A;
#[derive(A)] struct Foo;
```

2016-11-07 02:44 UTC, jseyfried commented on src/librustdoc/visit_ast.rs
> +                        LoadedMacro::ProcMacro(..) => continue, // FIXME
Will do (the FIXME is that `rustdoc` should document custom derives)

2016-11-07 02:49 UTC, jseyfried commented
@nrc The main purpose of this PR is to change the metadata to support reexporting custom derives.
Once we support this, I see no reason to specifically *disallow* reexporting custom derives (it would actually be a couple of extra lines).

`#[macro_reexport]` is feature gated and I think we should deprecate it once we can `pub use` macros behind a feature gate (writing that PR now). Until `#[macro_reexport]` is removed, though, think it should behave as consistently as possible on different kinds of macros.

2016-11-07 03:35 UTC, nrc commented on src/test/compile-fail-fulldeps/proc-macro/cannot-link.rs
> -fn main() {}
I would like to maintain a strict phase distinction between macro and non-macro crates (we intend to relax this eventually, but I don't want it to creep in). I don't want the macro_use to be optional, and until we actually support `use`ing derives, it seems that we should require it.

2016-11-07 03:35 UTC, nrc commented
> Until #[macro_reexport] is removed, though, think it should behave as consistently as possible on different kinds of macros.

OK, that makes sense.

2016-11-07 03:40 UTC, jseyfried commented on src/test/compile-fail-fulldeps/proc-macro/cannot-link.rs
> -fn main() {}
There is still a phase distinction -- only the macros are available from `extern crate derive_a` and `derive_a` is not linked.

> until we actually support `use`ing derives

I was going to support this behind a feature gate in a PR tomorrow...

> I don't want the macro_use to be optional

Why not? `#[macro_use]` or the ability to `use` derives, `extern crate derive_a;` just defines an empty module `derive_a`. Maybe a warning would be appropriate, but I don't see a reason to disallow it.

2016-11-07 03:41 UTC, jseyfried commented on src/test/compile-fail-fulldeps/proc-macro/cannot-link.rs
> -fn main() {}
There is still a phase distinction -- only the macros are available from `extern crate derive_a` and `derive_a` is not linked.

> until we actually support `use`ing derives

I was going to support this behind a feature gate in a PR tomorrow...

> I don't want the macro_use to be optional

Why not? Without `#[macro_use]` or the ability to `use` derives, `extern crate derive_a;` just defines an empty module `derive_a`. Maybe a warning would be appropriate, but I don't see a reason to disallow it.

2016-11-07 03:47 UTC, nrc commented on src/test/compile-fail-fulldeps/proc-macro/cannot-link.rs
> -fn main() {}
OK, if `use`ing derives will work soon, then lets allow it. As long as the non-macro_use case has sensible semantics, then I see no reason to block it.

2016-11-07 03:48 UTC, jseyfried commented on src/test/compile-fail-fulldeps/proc-macro/cannot-link.rs
> -fn main() {}
Actually, it's already an "unused extern crate" warning.

2016-11-07 23:54 UTC, jseyfried commented on src/librustdoc/visit_ast.rs
> +                        LoadedMacro::ProcMacro(..) => continue, // FIXME
Done.

2016-11-07 23:54 UTC, jseyfried commented on src/test/compile-fail-fulldeps/proc-macro/shadow.rs
>  fn main() {}
Yeah, I added a test.

2016-11-08 01:28 UTC, nrc commented
r = me, but a test seems to be broken

2016-11-08 01:28 UTC, nrc approved these changes

2016-11-08 01:41 UTC, jseyfried commented
Travis is broken.

2016-11-08 06:56 UTC, jseyfried commented
@bors r=nrc

2016-11-08 23:45 UTC, jseyfried commented
@bors r=nrc

2016-11-10 12:35 UTC, jseyfried commented
@bors r=nrc

2016-11-10 16:18 UTC, merged