Ref suggestion
rust-lang/rust pull request #37658
Opened 2016-11-08 21:58 UTC by GuillaumeGomez

2016-11-08 21:58 UTC, rust-highfive commented
r? @Aatch

(rust_highfive has picked a reviewer for you, use r? to override)

2016-11-08 22:16 UTC, GuillaumeGomez commented
r? @nikomatsakis 
cc @eddyb

Sub part of #37388.

2016-11-08 23:29 UTC, Mark-Simulacrum commented
Will this suggest `&mut foo` where `foo` is not mutable? If yes, perhaps we should phrase the suggestion differently in that case.

2016-11-09 00:04 UTC, eddyb commented
@Mark-Simulacrum To me getting the suggestion then, after making that change, an error about the variable not being mutable (with a suggestion to add `mut` to the `let` in that error) seems excellent.

2016-11-09 08:34 UTC, oli-obk commented on src/test/compile-fail/coercion-slice.rs
> -    //~| found type `[{integer}; 1]`
isn't this a regression in error reporting?

2016-11-09 08:34 UTC, oli-obk commented on src/librustc_typeck/check/demand.rs
> +                err.help(&suggestions);
why not report a `suggestion` instead of a `help`?

2016-11-09 10:52 UTC, GuillaumeGomez commented on src/test/compile-fail/coercion-slice.rs
> -    //~| found type `[{integer}; 1]`
I have absolutely no clue from where this change comes since my code just added suggestion.

2016-11-09 10:53 UTC, GuillaumeGomez commented on src/librustc_typeck/check/demand.rs
> +                err.help(&suggestions);
Indeed!

2016-11-09 15:00 UTC, eddyb commented on src/test/compile-fail/coercion-slice.rs
> -    //~| found type `[{integer}; 1]`
It's probably a stray side-effect? Try wrapping in `probe` if you haven't already. In fact, you probably want a version of `try_coerce` with no side-effects (call it `probe_coerce`).

2016-11-09 23:07 UTC, GuillaumeGomez commented on src/librustc_typeck/check/demand.rs
> +                err.help(&suggestions);
Apparently, such a thing doesn't exist. (Or at least I didn't find it...).

2016-11-10 00:07 UTC, GuillaumeGomez commented
@nikomatsakis: So, with the current code, it panics it certain cases. Here is the stack trace: https://gist.github.com/GuillaumeGomez/097fec3b6ac4257419fdf100115535f8

@eddyb: proposed a few things:

> so instead of this https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/coercion.rs#L372
>
> or rather, in addition to
>
> you'd have to do something like https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/coercion.rs#L493 and rename unsizing_obligations to obligations

However he said to consult you first. Any opinion/direction to give me? :-/

2016-11-10 07:36 UTC, oli-obk commented on src/librustc_typeck/check/demand.rs
> +                err.help(&suggestions);
It's called `span_suggestion`: http://manishearth.github.io/rust-internals-docs/rustc/?search=fn%3A%20suggestion

2016-11-10 10:31 UTC, GuillaumeGomez commented on src/librustc_typeck/check/demand.rs
> +                err.help(&suggestions);
I was looking for .suggest... You bet I didn't find it haha.

2016-11-10 17:45 UTC, nikomatsakis requested changes
@GuillaumeGomez sorry for the delayed review, thanks for breaking this out into a separate PR! I'd say it's close, but for a few concerns:
1. Can you change to use `span_suggestion`?
2. Also, can you create `ui` tests instead of `compile-fail` tests for those cases where you are showing off what your error message does?
3. I'd like to get to the bottom of the unexpected changes as well; I think that coercion may be registering trait obligations or something like that? (But this is supposed to result in assertion failures, I thought.) 

Do you want me to dig into that last point, @GuillaumeGomez?

2016-11-10 17:45 UTC, nikomatsakis commented on src/librustc_typeck/check/demand.rs
> +                err.help(&suggestions);
There is a `span_suggestion` method on `DiagnosticBuilder`:

```rust
    /// Prints out a message with a suggested edit of the code.
    ///
    /// See `diagnostic::RenderSpan::Suggestion` for more information.
    pub fn span_suggestion<S: Into<MultiSpan>>(&mut self,
                                               sp: S,
                                               msg: &str,
                                               suggestion: String)
                                               -> &mut Self {
```

I think the idea is that you replace the given span with the text `suggestion`, and also display the help message `msg`. Something like:

```
err.span_suggestion(span, "consider using the `&` operator", format!("&{}", span_to_string(span))
```

2016-11-10 17:45 UTC, nikomatsakis commented
Oh, @GuillaumeGomez, just saw your comment, let me process it.

2016-11-10 17:50 UTC, nikomatsakis commented
Yes, ok, those panics are sort of what I expected. =) I'm not sure what is the most elegant fix here. We've been dancing around this problem for a bit.

In this particular case, I wonder if we should just add a way to clone the fulfillment context in its entirety, and then just restore it. After all, this is the error path, so performance isn't especially important. This would be like a poor man's persistent data structure.

2016-11-10 18:05 UTC, GuillaumeGomez commented
Well, performance is important even in case of failure when are a lot of them (just imagine a code with more than 100 errors in it, it'd be a shame if it took a few seconds to run).

Also, considering my very poor background on the rust's internals, I'll need more explanation.

2016-11-10 18:57 UTC, eddyb commented
@nikomatsakis But most of the laziness is already there, shouldn't we do a bit a plumbing instead?
Coercions already have to deal with obligations from unsizing.
Or am I misunderstanding how far lazy normalization goes?

2016-11-12 01:31 UTC, nikomatsakis commented
@GuillaumeGomez 

sorry, didn't get a chance to try out my sample patch today, will do monday

@eddyb 

> But most of the laziness is already there, shouldn't we do a bit a plumbing instead?

I'm not quite sure what you are thinking here...

2016-11-12 08:11 UTC, eddyb commented
I mean that autoderef already has an obligations list registered late and so does coercion (burt only for unsizing). By combining the two we might not even *need* the ability to register obligations inside a snapshot!

2016-11-15 00:09 UTC, nikomatsakis commented
@eddyb perhaps; I'll have to look into the code in a bit more detail to see what you mean.

2016-11-16 01:36 UTC, brson commented on src/test/compile-fail/dst-bad-coercions.rs
> +                   //~^ ERROR the trait bound `*mut S: T` is not satisfied
These test cases also don't seem to be reflected by the content of the patch, which doesn't add these errors.

2016-11-16 01:38 UTC, brson commented
It's not even obvious what this patch is attempting to do. When adding features, consider explaining in the PR what the feature is and why it is important.

2016-11-16 10:39 UTC, GuillaumeGomez commented
@brson: I'll, but first I need to remove side-effects and need @nikomatsakis' help. :)

2016-11-22 15:15 UTC, nikomatsakis commented
OK, so, I just pushed a (hacky) commit that removes the side-effects. I'm not sure yet if I'm comfortable landing this or not =) @eddyb, did suggest he thought a cleaner path might be easy to get, and naturally I'd prefer that -- but this seems...not *too* terrible, for a focused hack.

Though it raises the question of how much value these suggestions have in the first place.

2016-11-22 15:16 UTC, eddyb commented
@nikomatsakis r- on the hack, it does *too much* for me to be comfortable with it.

2016-11-22 22:31 UTC, nikomatsakis commented
ok, yeah, so on IRC @eddyb elaborated a touch more on what he was thinking (propagating obligations up in a nicer way). Maybe one of us can find time to tinker with it soon.

2016-11-23 10:32 UTC, GuillaumeGomez commented
Let me know if I can help in any way.

2016-12-04 21:52 UTC, GuillaumeGomez commented
Updated to last master, still get ICEs in:

* compile-fail/dst-bad-coercions.rs
* compile-fail/cross-borrow-trait.rs
* compile-fail/issue-11374.rs

2016-12-30 22:24 UTC, GuillaumeGomez commented
Updated, still ICE. :'(

2017-01-02 20:05 UTC, nikomatsakis commented
@GuillaumeGomez sorry, haven't made time to dig into the alternate solution yet, will try to do so soon though

2017-01-02 20:25 UTC, GuillaumeGomez commented
@nikomatsakis: I'll make a rebase meanwhile to make your work easier.

2017-01-02 23:21 UTC, GuillaumeGomez commented
And done. Waiting to see your idea in motion @nikomatsakis! :)

2017-01-04 14:45 UTC, pnkfelix commented on src/librustc_typeck/check/demand.rs
> +                                                                        checked_ty,
nit: what's going on with the indentation here?

2017-01-04 14:48 UTC, GuillaumeGomez commented on src/librustc_typeck/check/demand.rs
> +                                                                        checked_ty,
Wo, well saw!

2017-01-19 23:24 UTC, GuillaumeGomez commented
@nikomatsakis: Thanks for fixing the rebase! (And sorry about that... 🤕 )

2017-02-23 20:06 UTC, nikomatsakis commented
Sorry @GuillaumeGomez. I know this PR has been open forever. =) It's just been crazy hectic. I talked a bit to @eddyb so I kind of get what he thinks we ought to do, at least...but I haven't had much time for coding lately, always just barely managing to keep up w/ notifications and writing tasks.

2017-02-23 21:57 UTC, GuillaumeGomez commented
@nikomatsakis: No problem. This isn't a high priority. Just try not forgetting it! ;)

2017-03-09 03:33 UTC, eddyb commented
@nikomatsakis @GuillaumeGomez I've had to make the change for #40319 anyway (I haven't pushed yet, but if tests pass, I will).

2017-03-09 17:55 UTC, GuillaumeGomez commented
I'll test with your change then. Thanks!

2017-03-09 20:14 UTC, GuillaumeGomez commented
@eddyb: There is still an ICE in `src/test/compile-fail/issue-11374.rs`:

```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'assertion failed: !self.obligations_in_snapshot.get()', src/librustc/infer/mod.rs:917
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rustc::infer::InferCtxt::rollback_to
   1: rustc_typeck::check::coercion::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::can_coerce
   2: rustc_typeck::check::demand::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::demand_coerce
   3: rustc_typeck::check::FnCtxt::check_argument_types
   4: rustc_typeck::check::FnCtxt::check_method_argument_types
   5: rustc_typeck::check::FnCtxt::check_expr_kind
   6: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref
   7: rustc_typeck::check::FnCtxt::check_stmt
   8: rustc_typeck::check::FnCtxt::check_block_with_expected
   9: rustc_typeck::check::FnCtxt::check_expr_kind
  10: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref
  11: rustc_typeck::check::check_fn
  12: rustc_typeck::check::typeck_tables
  13: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables<'tcx>>::try_get
  14: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables<'tcx>>::get
  15: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::item_tables
  16: rustc_typeck::check::check_item_bodies
  17: rustc_typeck::check_crate
  18: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  19: rustc_driver::driver::phase_3_run_analysis_passes
  20: rustc_driver::driver::compile_input
  21: rustc_driver::run_compiler
  22: std::panicking::try::do_call
  23: __rust_maybe_catch_panic
  24: <F as alloc::boxed::FnBox<A>>::call_box
  25: std::sys::imp::thread::Thread::new::thread_start
  26: _pthread_body
  27: _pthread_start
```

2017-03-09 20:54 UTC, eddyb commented
@GuillaumeGomez This PR doesn't have my changes, so of course it doesn't work?

2017-03-11 15:07 UTC, GuillaumeGomez commented
@eddyb: Ah damn, I thought your PR has been merged already. So sorry for the confusion...

2017-03-13 12:29 UTC, GuillaumeGomez commented
@eddyb: So after your update, still the same ICE.

2017-03-13 12:49 UTC, eddyb commented on src/librustc_typeck/check/coercion.rs
> +        let source = self.resolve_type_vars_with_obligations(expr_ty);
You don't want to swap out the fulfillment context but either way should be fine.

2017-03-28 03:20 UTC, mrhota commented
@GuillaumeGomez @eddyb any news here?

2017-03-28 15:32 UTC, GuillaumeGomez commented
@mrhota: I'm still waiting for the ICE to be fixed unfortunately. :-/

2017-04-01 22:52 UTC, alexcrichton commented
Should this be closed for now if it's waiting on a compiler fix?

2017-04-02 17:17 UTC, GuillaumeGomez commented
@alexcrichton: Let's keep it open if you don't mind. It's easier for me to keep a track of it.

2017-04-06 18:27 UTC, eddyb commented
@GuillaumeGomez I'm really not sure what the problem is, I thought I fixed the underlying design flaw once and for all 😕.

2017-04-07 18:40 UTC, GuillaumeGomez commented
So the actual ICE is:

```
RUST_BACKTRACE=1 ./build/x86_64-apple-darwin/stage1/bin/rustc /Users/imperio/rust/rust/src/test/compile-fail/issue-11374.rs
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: run with `RUST_BACKTRACE=1` for a backtrace

thread 'rustc' panicked at 'assertion failed: !self.obligations_in_snapshot.get()', src/librustc/infer/mod.rs:917
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rustc::infer::InferCtxt::rollback_to
   1: rustc_typeck::check::coercion::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::can_coerce
   2: rustc_typeck::check::demand::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::demand_coerce
   3: rustc_typeck::check::FnCtxt::check_argument_types
   4: rustc_typeck::check::FnCtxt::check_method_argument_types
   5: rustc_typeck::check::FnCtxt::check_expr_kind
   6: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref
   7: rustc_typeck::check::FnCtxt::check_stmt
   8: rustc_typeck::check::FnCtxt::check_block_with_expected::{{closure}}
   9: rustc_typeck::check::FnCtxt::check_block_with_expected
  10: rustc_typeck::check::FnCtxt::check_expr_kind
  11: rustc_typeck::check::FnCtxt::check_expr_with_expectation_and_lvalue_pref
  12: rustc_typeck::check::FnCtxt::check_return_expr
  13: rustc_typeck::check::check_fn
  14: rustc_typeck::check::typeck_tables
  15: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables<'tcx>>::try_get
  16: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables<'tcx>>::get
  17: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::item_tables
  18: rustc_typeck::check::typeck_item_bodies
  19: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_item_bodies<'tcx>>::try_get
  20: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_item_bodies<'tcx>>::get
  21: rustc_typeck::check_crate
  22: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  23: rustc_driver::driver::phase_3_run_analysis_passes
  24: rustc_driver::driver::compile_input
  25: rustc_driver::run_compiler
  26: std::panicking::try::do_call
  27: __rust_maybe_catch_panic
  28: <F as alloc::boxed::FnBox<A>>::call_box
  29: std::sys::imp::thread::Thread::new::thread_start
  30: _pthread_body
  31: _pthread_start
```

2017-04-08 13:46 UTC, GuillaumeGomez commented
Waiting for another fix from @eddyb (thanks a lot!).

2017-04-08 17:16 UTC, eddyb commented
I've looked again at this, and I have to make `lookup_method_in_trait_adjusted` lazy (in terms of obligations) which is possible, but blocked on #18653 (@nikomatsakis appears to be working on that).

2017-04-14 17:22 UTC, GuillaumeGomez commented
Current output:

```
thread 'rustc' panicked at 'assertion failed: !infcx.is_there_snapshot.get()', src/librustc/traits/fulfill.rs:174
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rustc::traits::fulfill::FulfillmentContext::register_predicate_obligation
   1: rustc_typeck::check::FnCtxt::register_predicate
   2: rustc_typeck::check::FnCtxt::register_predicates
   3: rustc_typeck::check::coercion::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::try_coerce
   4: rustc_typeck::check::demand::<impl rustc_typeck::check::FnCtxt<'a, 'gcx, 'tcx>>::demand_coerce
   5: rustc_typeck::check::typeck_tables
   6: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables<'tcx>>::try_get
   7: rustc::ty::maps::<impl rustc::ty::maps::queries::typeck_tables<'tcx>>::get
   8: rustc::ty::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::item_tables
   9: rustc_typeck::check::check_item_type
  10: rustc_typeck::check::check_item_types
  11: rustc_typeck::check_crate
  12: rustc_driver::driver::phase_3_run_analysis_passes::{{closure}}
  13: rustc_driver::driver::phase_3_run_analysis_passes
  14: rustc_driver::driver::compile_input
  15: rustc_driver::run_compiler
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
  18: <F as alloc::boxed::FnBox<A>>::call_box
  19: std::sys::imp::thread::Thread::new::thread_start
  20: _pthread_body
  21: _pthread_start
```

2017-04-14 17:24 UTC, eddyb commented
Will get soon to it.

2017-04-14 19:47 UTC, nikomatsakis commented
#18653 should be fixed now

2017-04-15 21:51 UTC, GuillaumeGomez commented
When rebased on #41325, everything works. We're finally seeing the end of the tunnel! \o/

2017-04-20 22:45 UTC, GuillaumeGomez commented
Ok, now I need to fix ui tests. But otherwise seems all good.

2017-04-20 22:48 UTC, eddyb commented on src/librustc_typeck/check/coercion.rs
> +use rustc::traits::{self, /*FulfillmentContext,*/ ObligationCause, ObligationCauseCode};
Comment still here.

2017-04-20 22:48 UTC, eddyb commented on src/librustc_typeck/check/coercion.rs
> +                FulfillmentContext::new());*/
Same here. Also not a hack right now.

2017-04-21 13:07 UTC, GuillaumeGomez commented
Tests passed! \o/

cc @eddyb @nikomatsakis

2017-04-21 13:12 UTC, eddyb commented
@GuillaumeGomez You have comments to remove and a rebase fixup commit to squash.

2017-04-21 20:52 UTC, GuillaumeGomez commented
Updated.

2017-04-21 20:53 UTC, eddyb commented on src/librustc_typeck/check/coercion.rs
> +use rustc::infer::type_variable::{TypeVariableOrigin};
Heh, leftover edit.

2017-04-21 20:53 UTC, eddyb commented on src/librustc_typeck/check/coercion.rs
> +                      -> bool {
Doesn't this signature fit on one line?

2017-04-21 20:54 UTC, eddyb commented on src/librustc_typeck/check/coercion.rs
> +        result
Can just have `self.probe(...)` as the returned expression.

2017-04-21 20:59 UTC, GuillaumeGomez commented
@bors: r=nikomatsakis,eddyb

2017-04-22 06:12 UTC, merged