Improved punctuation, capitalization, and sentence structure of code snippet comments
rust-lang/rust pull request #37755
Opened 2016-11-13 18:41 UTC by polo-language

r? @GuillaumeGomez

2016-11-13 18:42 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @GuillaumeGomez (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-11-13 23:36 UTC, GuillaumeGomez requested changes

2016-11-13 23:36 UTC, GuillaumeGomez commented on src/doc/book/associated-types.md
> +    // Etc.
Well, since et cetera means there are other things, let's write "Etc..." instead of just "Etc." ;)

2016-11-13 23:36 UTC, GuillaumeGomez commented on src/doc/book/associated-types.md
> +    // Etc.
Same.

2016-11-13 23:36 UTC, GuillaumeGomez commented on src/doc/book/box-syntax-and-patterns.md
> +    // Etc.
Same.

2016-11-13 23:36 UTC, GuillaumeGomez commented on src/doc/book/box-syntax-and-patterns.md
> +    // Etc.
Same.

2016-11-13 23:36 UTC, GuillaumeGomez commented
Thanks a lot for all this!

Just a little change needed and we're good to go.

2016-11-14 01:43 UTC, frewsxcv commented on src/doc/book/associated-types.md
> +    // Etc.
"etc." and "..." both indicate a continuation of a list, so it seems redundant to have both.

2016-11-14 09:56 UTC, GuillaumeGomez commented on src/doc/book/associated-types.md
> +    // Etc.
Ok, then fine by me.

2016-11-14 09:56 UTC, GuillaumeGomez approved these changes

2016-11-14 09:57 UTC, GuillaumeGomez commented
Thanks!

@bors: r+ rollup

2016-11-14 17:23 UTC, merged