rustdoc: add cli argument `--playground-url`
rust-lang/rust pull request #37763
Opened 2016-11-14 06:11 UTC by liigo

Add a new cli argument `--playground-url` for rustdoc:

`rustdoc lib.rs --playground-url="https://play.rust-lang.org/"`

`rustdoc book.md --playground-url="https://play.rust-lang.org/"`

This makes it possible for tools like https://docs.rs to generate crate docs that can submit samples code to run at https://play.rust-lang.org, even if the crate's author *forgot* putting `#![doc(html_playground_url = "https://play.rust-lang.org/")]` to crate root. By the way, I'd like to say, many crate authors are not aware of existing of `#![doc(html_playground_url = "https://play.rust-lang.org/")]`.

`--playground-url` may be reset by `--markdown-playground-url` or `#![doc(html_playground_url=...)]`, so it's backward compatible.

@alexcrichton since you implemented playground-url related features.

2016-11-14 06:11 UTC, rust-highfive commented
r? @steveklabnik

(rust_highfive has picked a reviewer for you, use r? to override)

2016-11-15 03:55 UTC, brson commented
Seems like a reasonable feature to me.

2016-11-16 20:42 UTC, alexcrichton commented
@bors: r+

2016-11-16 21:22 UTC, ollie27 requested changes
Do we really need two command line options which do the same thing for Markdown rendering?

I can envision having a `--html-playground-url` as an alternative to `#![doc(html_playground_url)]` but it's not clear to me what should happen if both are set. What's proposed here is one option but for the use case of websites like docs.rs surely you would want to override whatever was set by `#![doc(html_playground_url)]`.

Shouldn't we be a bit more careful before adding new stable command line options to rustdoc?

Either way this could do with tests.

2016-11-16 21:22 UTC, ollie27 commented on src/librustdoc/lib.rs
> +        html::markdown::PLAYGROUND.with(|s| { *s.borrow_mut() = Some((None, playground)); });
When doing HTML rendering the crate name needs to be set so the correct `extern crate` can be added to the code. The first item in the tuple is the crate name.

2016-11-17 06:37 UTC, liigo commented
> Do we really need two command line options which do the same thing for Markdown rendering?

existing `--markdown-playground-url` may be deprecated in the future. `--playground-url` is reasonable for both Html and Markdown rendering.

> surely you would want to override whatever was set by #![doc(html_playground_url)]

That'd be a breaking change.

2016-11-17 06:43 UTC, liigo commented on src/librustdoc/lib.rs
> +        html::markdown::PLAYGROUND.with(|s| { *s.borrow_mut() = Some((None, playground)); });
will do that in follow up PR, thanks @ollie27 !

2016-11-18 13:03 UTC, merged