Support `?Sized` in where clauses
rust-lang/rust pull request #37791
Opened 2016-11-16 00:33 UTC by petrochenkov

Implemented as described in https://github.com/rust-lang/rust/issues/20503#issuecomment-258677026 - `?Trait` bounds are moved on type parameter definitions when possible, reported as errors otherwise.
(It'd be nice to unify bounds and where clauses in HIR, but this is mostly blocked by rustdoc now - it needs to render bounds in pleasant way and the best way to do it so far is to mirror what was written in source code.)

Fixes https://github.com/rust-lang/rust/issues/20503
r? @nikomatsakis

2016-11-16 14:42 UTC, petrochenkov commented on src/librustc/hir/lowering.rs
> +                                        break 'next_bound;
s/break/continue/

2016-11-16 19:33 UTC, arielb1 commented on src/librustc/hir/lowering.rs
> +                                    // Don't bother looking up the definition,
Can't macros make a mess of this in their evil macro-ey ways? Better look up the definition to avoid the question.

2016-11-16 20:17 UTC, arielb1 commented on src/librustc/hir/lowering.rs
> +                                    // Don't bother looking up the definition,
Sure. Randomly implementing unhygienic lookup is a sure way to cause bugs in the future.

2016-11-16 23:43 UTC, nikomatsakis commented
@petrochenkov do you have an alternate, more hygiene-friendly impl in mind?

2016-11-16 23:48 UTC, petrochenkov commented
@nikomatsakis 
Yes, sure, all definitions are recorded in def map when AST->HIR lowering happens and can be compared instead of names.

2016-11-17 19:27 UTC, nikomatsakis commented
@petrochenkov ok seems better

2016-11-17 20:34 UTC, petrochenkov commented
Updated.

2016-11-22 11:19 UTC, thepowersgang commented
I am against this because I believe that being sized is such an important part of the type that the annotation removing it should be in a prominent location, not hidden among the where clauses.

2016-11-22 12:58 UTC, KalitaAlexey commented
@thepowersgang I like to place all constraints after `where`.

2016-11-22 22:28 UTC, nikomatsakis requested changes
Code looks good, I just think we can tweak the error message.

2016-11-22 22:28 UTC, nikomatsakis commented on src/librustc/hir/lowering.rs
> +                                "`?Trait` bounds are permitted only on fresh type parameters");
Nit: maybe "only permitted at the point where a type parameter is declared"?

2016-11-22 22:28 UTC, nikomatsakis commented on src/test/compile-fail/maybe-bounds-where.rs
> +struct S5<T>(*const T) where T: ?Trait<'static> + ?Sized;
what on earth is `?Trait<'static>`? we permit that??

2016-11-22 22:28 UTC, nikomatsakis commented on src/test/compile-fail/maybe-bounds-where.rs
> +struct S5<T>(*const T) where T: ?Trait<'static> + ?Sized;
huh, apparently. I would have thought it'd be an error. Oh well, obviously pre-existing.

2016-11-22 22:30 UTC, nikomatsakis commented
@rfcbot fcp merge

Strictly speaking, this is an "insta-stable" lang change. We could use a stability period, not sure if it is necessary in this case. I propose we merge, as this feels more like a bugfix to me, but am amenable to a stability period as well. But let's FCP it.

OK @rust-lang/lang, what do you think? The change is to permit `fn foo<T>() where T: ?Sized` and not require that it be declared like `fn foo<T: ?Sized>()` (i.e., allow `T: ?Sized` to be moved into a where-clause on the item where `T` is declared.

2016-11-22 22:56 UTC, withoutboats commented
@rfcbot reviewed

Seems like a bug fix to me. It should always be possible to transpose bounds from the parameter introduction clause to the where clause.

2016-11-28 21:04 UTC, nikomatsakis commented
@bors r+

2016-11-29 01:54 UTC, merged