Update the bootstrap compiler
rust-lang/rust pull request #37800
Opened 2016-11-16 17:20 UTC by alexcrichton

Now that we've got a beta build, let's use it!

2016-11-17 00:06 UTC, brson commented
This is still waiting on a beta that contains a cargo fix for https://github.com/rust-lang/cargo/pull/3280. Next beta after https://github.com/rust-lang/rust-packaging/pull/66 should have it.

2016-11-17 00:08 UTC, brson commented
Subsumes https://github.com/rust-lang/rust/pull/37635/files

2016-11-17 00:30 UTC, alexcrichton commented
Updated the Cargo date, should be good to go

2016-11-22 17:29 UTC, alexcrichton commented
r? @brson

2016-11-30 06:44 UTC, alexcrichton commented
r? @eddyb

2016-11-30 15:28 UTC, eddyb requested changes
r=me with comments addressed.

2016-11-30 15:28 UTC, eddyb commented on src/librustc_llvm/lib.rs
> -#![feature(staged_api)]
This can't/shouldn't be removed - Travis failed on this.

2016-11-30 15:28 UTC, eddyb commented on src/tools/compiletest/Cargo.toml
> -# this is removed and it gets past the bots, sounds good to me.
This comment should be preserved, or `opt-level = 2` be removed otherwise at the top-level.

2016-11-30 18:38 UTC, alexcrichton commented
@bors: r=eddyb

2016-11-30 23:35 UTC, merged