fix `extern "aapcs" fn`
rust-lang/rust pull request #37814
Opened 2016-11-16 22:39 UTC by japaric

to actually use the AAPCS calling convention

closes #37810 

---

r? @alexcrichton We are going this `extern "aapcs" fn` thing to implement some intrinsics (floatundidf) for the eabihf targets in order to comply with LLVM's calling convention of intrinsics.

Disclaimer: Not tested, still compiling my stage1 rustc.

Oh, and the value of the enum came from [here](http://llvm.org/docs/doxygen/html/namespacellvm_1_1CallingConv.html).

cc @TimNN @parched

2016-11-16 22:39 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @alexcrichton (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-11-16 22:46 UTC, parched requested changes

2016-11-16 22:46 UTC, parched commented on src/librustc_trans/abi.rs
> +            Aapcs => llvm::AapcsCallConv,
this doesn't match `ffi.rs` it's missing `Arm`

2016-11-16 22:59 UTC, parched approved these changes

2016-11-16 23:01 UTC, japaric commented
It works:

``` rust
#[no_mangle]
pub extern "aapcs" fn foo(x: f64) -> f64 {
    x
}

#[no_mangle]
pub extern "C" fn bar(x: f64) -> f64 {
    x
}
```

``` asm
00000000 <foo>:
   0:   e24dd008        sub     sp, sp, #8
   4:   ec410b10        vmov    d0, r0, r1
   8:   ed8d0b00        vstr    d0, [sp]
   c:   eaffffff        b       10 <foo+0x10>
  10:   ed9d0b00        vldr    d0, [sp]
  14:   ec510b10        vmov    r0, r1, d0
  18:   e28dd008        add     sp, sp, #8
  1c:   e12fff1e        bx      lr

Disassembly of section .text.bar:

00000000 <bar>:
   0:   e24dd008        sub     sp, sp, #8
   4:   ed8d0b00        vstr    d0, [sp]
   8:   eaffffff        b       c <bar+0xc>
   c:   ed9d0b00        vldr    d0, [sp]
  10:   e28dd008        add     sp, sp, #8
  14:   e12fff1e        bx      lr
```

2016-11-16 23:12 UTC, TimNN commented
Maybe we should add a note about this (`aapcs` is now always soft float) to the `aapcs` entry in [`reference.md`](https://github.com/rust-lang/rust/blob/master/src/doc/reference.md)?

I'm not sure about the exact policy here, however technically this is a breaking change so should probably tagged as such (`[breaking-change]`).

2016-11-16 23:29 UTC, alexcrichton commented
Strictly speaking yeah it's a breaking change but in practice I imagine this will fix more code than it breaks (if it breaks anything...).

@japaric want to edit the commit message and I'll r+?

also cc @rust-lang/compiler, just to be aware

2016-11-16 23:49 UTC, japaric commented
> want to edit the commit message and I'll r+?

Done.

2016-11-17 01:51 UTC, alexcrichton commented
@bors: r+

2016-11-19 16:08 UTC, merged