WIP: Add a method for setting permissions directly on an open file.
rust-lang/rust pull request #37886
Opened 2016-11-19 21:55 UTC by Stebalien

On unix like systems, the underlying file corresponding to any given path may
change at any time. This function makes it possible to set the permissions of
the a file corresponding to a `File` object even if its path changes.

@retep998, what's the best way to do this on Windows? I looked into
`SetFileInformationByHandle` but couldn't find a way to do it atomically risking
clobbering access time information.

This is a first step towards fixing #37885. This function doesn't *have* to be
public but this is useful functionality that should probably be exposed.

2016-11-19 21:55 UTC, rust-highfive commented
r? @aturon

(rust_highfive has picked a reviewer for you, use r? to override)

2016-11-19 21:58 UTC, Stebalien commented
r? @alexcrichton

2016-11-20 05:45 UTC, retep998 commented
>I looked into SetFileInformationByHandle but couldn't find a way to do it atomically risking clobbering access time information.

Just set the file times to 0. That way they won't update and you'll only modify the file attributes.

2016-11-20 15:54 UTC, Stebalien commented
Is that documented anywhere? I couldn't find that information on MSDN.

2016-11-20 16:03 UTC, retep998 commented
I couldn't find any documentation about it myself, but I'm pretty sure it is a feature. Even `SetFileAttributes` relies on that behavior. I actually discovered it by looking at `SetFileAttributes`'s implementation where it calls `NtSetInformationFile` (the syscall behind `SetFileInformationByHandle`) and passes a `FILE_BASIC_INFORMATION` with the filetimes set to 0.

2016-11-20 16:14 UTC, Stebalien commented
Grumble... undocumented APIs... anti-trust settlement... *sigh*.

2016-11-20 16:18 UTC, retep998 requested changes

2016-11-20 16:18 UTC, retep998 commented on src/libstd/sys/windows/fs.rs
> +        let mut info = c::FILE_END_OF_FILE_INFO {
Wrong struct name.

2016-11-20 16:18 UTC, retep998 commented on src/libstd/sys/windows/fs.rs
> +            LastWriteTime: 0,
This field isn't listed in your `FILE_BASIC_INFO` definition.

2016-11-20 16:25 UTC, Stebalien commented on src/libstd/sys/windows/fs.rs
> +        let mut info = c::FILE_END_OF_FILE_INFO {
Thanks.

2016-11-20 16:25 UTC, Stebalien commented on src/libstd/sys/windows/fs.rs
> +            LastWriteTime: 0,
Thanks.

2016-11-21 00:27 UTC, Stebalien commented
So, the question is, does this need an RFC (it's a new public API but it mirrors methods like `fs::metadata`)?

2016-11-21 01:03 UTC, retep998 commented
This is small enough that it shouldn't need an RFC, although it might still go through the rfcbot merge process with the libs subteam.

2016-11-21 15:48 UTC, alexcrichton commented
Looks good to me, thanks @Stebalien! Yeah it's ok to not have an RFC for this. Could you file a tracking issue for this, though, and fill that out? I'll tag it afterwards and then r+ so we can land.

2016-11-21 17:20 UTC, Stebalien commented
Done.

2016-11-21 17:22 UTC, Stebalien commented on src/libstd/fs.rs
> +/// [`File::set_permissions`]: struct.File.html#method.set_permissions
Before you merge, would you like me to keep this note or wait till `File::set_permissions` stabilizes.

2016-11-21 21:26 UTC, alexcrichton commented on src/libstd/fs.rs
> +/// [`File::set_permissions`]: struct.File.html#method.set_permissions
Ah let's leave this out until the method stabilizes

2016-11-21 21:51 UTC, Stebalien commented on src/libstd/fs.rs
> +/// [`File::set_permissions`]: struct.File.html#method.set_permissions
Done.

2016-11-21 23:38 UTC, alexcrichton commented
@bors: r+

2016-11-23 02:57 UTC, Stebalien commented
(should be fixed, sorry).

2016-11-23 05:05 UTC, alexcrichton commented
@bors: r+

2016-11-23 10:31 UTC, merged