rustc: always suggests #[macro_use] for undefined macros
rust-lang/rust pull request #37910
Opened 2016-11-21 08:35 UTC by liigo

If people forget adding `#[macro_use]` (or even don't know about it), give them a suggestion.

```rust
// missing `#[macro_use]`
extern crate log;
fn main() {
    info!("hello");
}
```
play link: https://is.gd/nwB6ty

2016-11-21 08:35 UTC, rust-highfive commented
r? @arielb1

(rust_highfive has picked a reviewer for you, use r? to override)

2017-01-03 16:35 UTC, steveklabnik commented
it looks like @arielb1 never reviewed. Maybe someone else from @rust-lang/compiler ?

2017-01-03 17:18 UTC, eddyb commented
r? @jseyfried

2017-01-04 08:28 UTC, jseyfried requested changes
@liigo Thanks for the PR!

Let me know here or on IRC if you have any questions about my comments.

2017-01-04 08:28 UTC, jseyfried commented on src/librustc_resolve/macros.rs
> -                err.help(&format!("have you added the `#[macro_use]` on the module/import?"));
I think we should keep this here, but it should just say "have you added the `#[macro_use]` on the module?".

2017-01-04 08:28 UTC, jseyfried commented on src/librustc_resolve/macros.rs
> +        err.help(&format!("have you added the `#[macro_use]` on the module/import?"));
I think this should say "have you added the `#[macro_use]` on the `extern crate`", but only if there is a macro with that name in an extern crate.

You should be able to use `resolver.lookup_import_candidates()` (in `librustc_resolve/lib.rs`) with a `filter_fn` checks for `Def::Macro`s to check if there are any relevant macros in `extern crate`s that the user might want to `#[macro_use]`.

2017-01-04 14:39 UTC, pnkfelix commented
Hmm, with this change, if I write:

```rust
#[macro_use]
extern crate log;
fn main() {
    infq!("hello");
}
```

won't the compiler now suggest I put in a `#[macro_use]` even though that's not at all what is needed?

2017-01-08 07:56 UTC, liigo commented
I'll try to work on according to review suggestions. Please don't merge util I'm done.

2017-02-04 21:51 UTC, alexcrichton commented
Closing due to inactivity, but feel free to resubmit with comments addressed!

2017-02-04 21:51 UTC, closed without merging