Document RFC 1623: static lifetime elision.
rust-lang/rust pull request #37928
Opened 2016-11-22 01:21 UTC by chriskrycho

This should be the last item required for stabilizing (#35897).

2016-11-22 01:21 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @steveklabnik (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-11-22 02:04 UTC, frewsxcv commented on src/doc/reference.md
> +address will have the `static` lifetime. (See below on [static lifetime elision](#static-lifetime-elision).) The compiler is, however, still at liberty to
Can you wrap this line to match the indentation of the surrounding lines?

2016-11-22 02:25 UTC, chriskrycho commented
Gah, yes. I’m annoyed I missed that.

2016-11-22 17:27 UTC, steveklabnik commented
So, @rust-lang/docs , this raises a question. How do we make the distinction between stable and unstable stuff here?

2016-11-22 17:30 UTC, chriskrycho commented
I think at some point, we are going to need to build infrastructure for versioning. That is going to be some work, but I do not see how we can handle these kinds of cases long-term without it. I can open an issue to that effect if you like. And maybe ping some of the Ember people who worked on their infrastructure that way.

2016-11-22 20:13 UTC, GuillaumeGomez commented
It should have an unstable version. I don't have much better idea. :-/

2016-11-23 01:40 UTC, chriskrycho commented
I just noted that all the code samples in reference.md get tested. Neat! I'll update the sample accordingly in the morning.

2016-11-23 16:44 UTC, frewsxcv commented
I don't have any great ideas either, other than explicitly mentioning that it's unstable and adding in the `#[feature(whatever_feature_name)]` in the code example. At least we'll get a warning when it stabilizes.

2016-12-12 19:06 UTC, steveklabnik commented
Putting this on this week's doc team agenda.

2016-12-14 18:04 UTC, llogiq commented
We could change the feature implementation to my first commit, thus stabilizing the feature and removing the extra code adding the feature gate that makes it unstable in the first place. I presume this should make the doc tests pass.

2016-12-14 22:44 UTC, steveklabnik commented
So, we talked about this at the docs meeting today.

What it really boils down to is this: it'd be a shame to block this based on figuring out the broader story here. However, once we know that the rest of the feature will be stable, we can just land this, then land the stabilization of the feature. @aturon [just put the feature into FCP](https://github.com/rust-lang/rust/issues/35897#issuecomment-267177618), so let's see how that goes before we merge.

And in the meantime, let's figure out the broader docs story. I'm going to open an issue on the RFCs repo about this.

2016-12-14 22:45 UTC, chriskrycho commented
Related: I'll have time Friday or Saturday to update the not-the-feature-gate bits of the test that are broken here—there's one piece that needs to be tweaked independent of the stabilization/feature flag issue.

2016-12-30 22:29 UTC, chriskrycho commented
Kept spacing this; came back to it via other issues. I'll update the non-feature-gate related parts tonight or tomorrow!

2017-01-03 21:41 UTC, llogiq commented
@chriskrycho do you need any help?

2017-01-03 21:44 UTC, chriskrycho commented
@llogiq gah. Slipped my mind. The only thing that needs tweaking is setting `ignore` on [this example](https://github.com/rust-lang/rust/pull/37928/files#diff-070c91ddb3b61fa408b94f592961734aR1364). It's re-using items from earlier in the reference, but they're not in scope for that specific example.

2017-01-03 23:24 UTC, chriskrycho commented
I just pushed a fixed version of the commit which just includes all the required pieces. We'll see what Travis says…

2017-01-04 00:04 UTC, chriskrycho commented
UGH. I pushed the rebase, but *not the fix*.

This is how my whole first day back at work has been. 🤦‍♂️

2017-01-23 21:33 UTC, steveklabnik commented
@chriskrycho travis is still failing: https://travis-ci.org/rust-lang/rust/jobs/188704796#L1662

2017-01-23 21:36 UTC, chriskrycho commented
🤔 Grr. I will follow up Wednesday evening. Family commitments till then.

2017-01-23 22:43 UTC, steveklabnik commented
No worries!

2017-01-28 19:14 UTC, llogiq reviewed
Actually this is full elision with a `'static` default. This means that if the types contains `fn`s, the usual elision rules will apply, only choosing `'static` if no elision rule applies.

2017-01-30 22:52 UTC, chriskrycho commented
@llogiq can you elaborate?

@steveklabnik I seem to have failed in pacifying [Travis](https://travis-ci.org/rust-lang/rust/jobs/196180998#L5822) and the feature gate. Can you take a gander and indicate what I did wrong?

2017-01-31 07:07 UTC, llogiq commented
This means if you have a `static FOO : &Fn(&Bar) -> &Baz`, you actually have a `static FOO : &'static Fn<'a>(&'a Bar) -> &'a Baz` for some unnamed `'a`.

2017-01-31 13:46 UTC, est31 commented
> I seem to have failed in pacifying Travis and the feature gate. 

I think you can fix it by adding `# #![feature(...)]` to the doc test. It won't show up in the output then due to the leading `#`, while fixing the issue. See also [the book](https://doc.rust-lang.org/book/documentation.html#documentation-as-tests) and [the asm documentation](https://github.com/rust-lang/rust/tree/master/src/doc/book/inline-assembly.md), it uses this as well.

2017-01-31 13:47 UTC, chriskrycho commented
@est31 ah, it's the extra `#`. Got it.

@llogiq do you have a suggested change to the write-up here?

2017-01-31 20:27 UTC, clarcharr commented on src/doc/reference.md
> +#[feature(static_in_const)]
this should be `#![feature(static_in_const)]`; you forgot the exclamation point.

2017-01-31 20:28 UTC, chriskrycho commented on src/doc/reference.md
> +#[feature(static_in_const)]
YOU ARE MY HERO

2017-01-31 20:39 UTC, llogiq commented
I think I *could* improve it, but I need to find the time first.

2017-02-02 16:44 UTC, llogiq requested changes
Also after the example, add a paragraph to explain the elision:

In case the static or constant items contain function references or closures, and those work with references, the compiler will try the usual elision rules (link to elision). Failing that, it will default the lifetimes to `'static`. This is best explained by an example:

```rust
const FUN : fn(&str) -> &str = ..
// per rule #1, this is fn<'a>(&'a str) -> &'a str

const FUNNY : Fn(&Foo, &Bar, &Baz) -> usize = ..
// per rule #2, this is Fn<'a, 'b, 'c>(&'a Foo, &'b Bar, &'c Baz) -> usize

const UNFUNNY : Fn(&Foo, &Bar) -> &Baz = ..
// neither rule applies, so all `&`s are `'static`
```

2017-02-02 16:44 UTC, llogiq commented on src/doc/reference.md
> +address will have the `static` lifetime. (See below on [static lifetime
How about "will have elided lifetimes where applicable, otherwise – in most cases – defaulting to the `'static` lifetime.

2017-02-05 17:17 UTC, est31 commented
Now that beta branched, I would like to ask for beta backport nomination, so that already 1.16 would have it stabilized.

2017-02-05 19:07 UTC, llogiq commented
Good idea.

2017-02-07 19:10 UTC, steveklabnik commented
@chriskrycho ping! any interest in keeping this going? this is still blocking stabilization.

@est31 I would be strongly against this; stabilization backports are incredibly rare.

2017-02-08 00:52 UTC, chriskrycho commented
@steveklabnik yeah, should be able to allocate an hour to it tomorrow. I'll pull in @llogiq's comments, as well as fix the build issue, then.

2017-02-08 02:53 UTC, llogiq commented
We may also want to show embedded lifetimes, e.g. `Fn(&'a Foo) -> Bar<'a>` can be shortened to `Fn(&Foo) -> Bar`.

2017-02-08 19:22 UTC, chriskrycho commented
@llogiq regarding your last comment: did that change with this RFC/implementation? If not, I'd prefer to note it as something to add in a separate commit/PR. I think we actually need a dedicated section for lifetime elision in general; right now it appears to be documented in detail only in the nomicon.

2017-02-08 19:32 UTC, chriskrycho commented
Updated with everything other than the *embedded lifetimes* scenario, and it passed `rustup run nightly rustdoc --test ./doc/reference.md` so we should finally be good to go. 🤞

2017-02-08 22:06 UTC, steveklabnik commented
Travis passed!

@bors: r+ rollup

thanks a ton @chriskrycho

2017-02-08 22:07 UTC, chriskrycho commented
YESSSSSSSSSSS. FINALLLYYYYYYYY.

Sorry for the many delays on this, everyone! Glad it's finally in. So it'll land in, what, 1.17?

2017-02-09 01:24 UTC, est31 commented
@chriskrycho 

> So it'll land in, what, 1.17?

yes.

2017-02-09 08:54 UTC, merged

2017-02-21 19:55 UTC, alexcrichton commented
Removing beta nomination as sentiment seems to be to not backport (also see #35897)