Improve and fix mpsc documentation
rust-lang/rust pull request #37941
Opened 2016-11-22 21:00 UTC by Cobrand

Closes #37915

This commit enhances documentation with several links and
fixes an error in the `sync_channel` documentation as well:
`send` doesn't panic when the senders are all disconnected

r? @steveklabnik

2016-11-25 04:23 UTC, mfarrugi commented
Are the references to 'runtime' also outdated? eg. L235

2016-11-25 09:10 UTC, Cobrand commented
@mfarrugi I don't really get what you mean ... could you explain more in detail ?

2016-11-25 15:44 UTC, mfarrugi commented
I'm not clear on what runtime refers to in 
`// A major goal of these channels is to work seamlessly on and off the runtime.`
But I think it refers to the [old rust runtime](https://doc.rust-lang.org/0.12.0/guide-runtime.html)

2016-11-25 15:56 UTC, Cobrand commented
Indeed it looks like the mention of the runtime is part of the old documentation that was kept here.

A quick git blame told me that most the the comments in this file were from 2013 or 2014, so definitely way before the first release of Rust.

That might need another PR though ?

2016-12-06 21:48 UTC, Cobrand commented
This has been opened for several days but I don't see any issue, I guess I'll try my luck with someone else ?
r? @GuillaumeGomez

2016-12-07 02:17 UTC, GuillaumeGomez requested changes

2016-12-07 02:17 UTC, GuillaumeGomez commented on src/libstd/sync/mpsc/mod.rs
> +/// If the [`Receiver`] is disconnected while trying to [`send`] with the
All functions/methods name should have `()` at the end.

2016-12-07 02:17 UTC, GuillaumeGomez commented on src/libstd/sync/mpsc/mod.rs
> +/// is valid, in which case this becomes  "rendezvous channel" where each [`send`]
Extra whitespace before "rendezvous". By the way, shouldn't it be rendez-vous? French in english is so strange haha.

2016-12-07 02:17 UTC, GuillaumeGomez commented on src/libstd/sync/mpsc/mod.rs
> +/// is valid, in which case this becomes  "rendezvous channel" where each [`send`]
Oh and same comment for `send` in here.

2016-12-07 02:17 UTC, GuillaumeGomez commented on src/libstd/sync/mpsc/mod.rs
> +/// to [`send`] with the [`SyncSender`], the [`send`] method will return an
Same comment for `send`.

2016-12-07 17:53 UTC, Cobrand commented on src/libstd/sync/mpsc/mod.rs
> +/// is valid, in which case this becomes  "rendezvous channel" where each [`send`]
Being french myself I had my doubts about that but in English it's definitely rendezvous : 

https://fr.wikipedia.org/wiki/Rendez-vous
https://en.wikipedia.org/wiki/Rendezvous

For some unknown and I guess historical reasons the translators dropped the dash

2016-12-07 17:58 UTC, Cobrand commented on src/libstd/sync/mpsc/mod.rs
> +/// If the [`Receiver`] is disconnected while trying to [`send`] with the
Done

2016-12-07 18:48 UTC, GuillaumeGomez approved these changes

2016-12-07 18:48 UTC, GuillaumeGomez commented
All good, thanks!

@bors: r+ rollup

2016-12-13 06:24 UTC, merged