Refactor TraitObject to Slice<ExistentialPredicate>
rust-lang/rust pull request #37965
Opened 2016-11-23 18:34 UTC by Mark-Simulacrum

More detailed PR description once I have some time to sit down and type it out, but for now wanted to get this out here for an initial round of review. `./x.py test --stage 2` passes locally.

r? @eddyb

2016-11-23 20:28 UTC, eddyb requested changes
LGTM modulo comments. cc @nikomatsakis about `Binder` discipline.

2016-11-23 20:28 UTC, eddyb commented on src/librustc_trans/base.rs
> +            let trait_ref = data.principal().unwrap().with_self_ty(ccx.tcx(), source);
Use `map` here and change `meth::get_vtable` to take an `Option`.

2016-11-23 20:28 UTC, eddyb commented on src/librustc_typeck/check/cast.rs
> +                Some(UnsizeKind::Vtable(tty.principal().unwrap().def_id())),
Should use `map` and put an `Option<DefId>` in `UnsizeKind::Vtable`.

2016-11-23 20:28 UTC, eddyb commented on src/librustc_typeck/check/closure.rs
> +                    self.tcx.lang_items.fn_trait_kind(object_type.principal().unwrap().def_id());
This should use `and_then`.

2016-11-23 20:28 UTC, eddyb commented on src/librustc_typeck/check/method/probe.rs
> +                self.assemble_inherent_impl_candidates_for_type(data.principal().unwrap().def_id());
This should not `.unwrap()` (but do nothing if `None`).

2016-11-23 20:28 UTC, eddyb commented on src/librustc_typeck/check/method/suggest.rs
> +                                                          p.def_id().is_local()).unwrap_or(false),
`map_or` works.

2016-11-23 20:28 UTC, eddyb commented on src/librustc_typeck/check/regionck.rs
> +            /*To:  */  &ty::TyDynamic(.., ref reg)) => {
Same odd `reg`.

2016-11-23 20:28 UTC, eddyb commented on src/librustc_typeck/coherence/overlap.rs
> +                        !self.tcx.is_object_safe(data.principal().unwrap().def_id()) {
This can be written using `map_or`.

2016-11-23 20:28 UTC, eddyb commented on src/librustc_typeck/collect.rs
> +        auto_traits: auto_traits,
I'm not sure this partitioning should even exist until a `TyDynamic` is created.

2016-11-23 20:28 UTC, eddyb commented on src/librustc_typeck/variance/constraints.rs
>                  self.add_constraints_from_trait_ref(generics, poly_trait_ref.0, variance);
This can be wrapped in an `if let Some` instead of using `.unwrap()`.

2016-11-23 20:28 UTC, eddyb commented on src/librustc/ty/sty.rs
> +                v.extend(obj.principal().unwrap().skip_binder().substs.regions());
This shouldn't `.unwrap()`.

2016-11-24 16:00 UTC, Mark-Simulacrum commented on src/librustc/ty/walk.rs
> +            }).collect::<Vec<_>>().into_iter().rev()); // FIXME: Don't allocate a vec for reversal.
I'm confused what you mean by `flat_map` over an iterator of `ExistentialPredicate`. Are you suggesting that we extend from a `filter_map` of `ExistentialPredicate` for the Projection and Trait cases?

(And switch places, so push projection bounds first and then the principal)?

2016-11-24 16:02 UTC, eddyb commented on src/librustc/ty/walk.rs
> +            }).collect::<Vec<_>>().into_iter().rev()); // FIXME: Don't allocate a vec for reversal.
`flat_map` because there's multiple types per each predicate.

2016-11-25 22:31 UTC, Mark-Simulacrum commented
@eddyb Ready for the crater run, I think, but might want to review before?

2016-11-26 04:39 UTC, Mark-Simulacrum commented on src/librustc_trans/trans_item.rs
> +                        &trait_data.projection_bounds().collect::<Vec<_>>()[..],
Shouldn't allocate.

2016-11-26 04:39 UTC, Mark-Simulacrum commented on src/librustc_typeck/check/wfcheck.rs
> +                            .unwrap_or_else(|msg| fcx.tcx.sess.fatal(&msg[..])),
Replace with `require_lang_item`.

2016-11-26 04:39 UTC, Mark-Simulacrum commented on src/librustc_typeck/variance/constraints.rs
> +            ty::TyDynamic(ref data, ref reg) => {
`reg`

2016-11-26 13:19 UTC, Mark-Simulacrum commented
Expanded the description with discussion and elaboration on what this PR does.

@eddyb Let me know what parts of that should be transferred into documentation comments in the code.

2016-11-27 17:07 UTC, Mark-Simulacrum commented
Squashed the remaining fix commits. r? @eddyb

2016-11-27 22:01 UTC, eddyb commented
Started crater run.

2016-11-28 01:39 UTC, eddyb requested changes

2016-11-28 01:39 UTC, eddyb commented on src/librustc/ty/error.rs
> +                write!(f, "conflicting existentials: `{}` and `{}`",
Use `report_maybe_different`. Also, don't leak the term "existential" (or "dynamic") to user.

2016-11-28 01:39 UTC, eddyb commented on src/librustc/ty/flags.rs
> +                        _ => {}
Explicitly match on `AutoTrait` to make this exhaustive.

2016-11-28 01:39 UTC, eddyb commented on src/librustc/ty/relate.rs
> +            }
Shouldn't this check be in the slice impl below?

2016-11-28 01:39 UTC, eddyb commented on src/librustc/ty/sty.rs
> +        self.0.projection_bounds().map(|b| Binder(b))
Here and above you could pass `Binder` to `map`.

2016-11-28 01:39 UTC, eddyb commented on src/librustc/ty/sty.rs
> +        self.0.iter().cloned().map(|x| Binder(x))
All of these methods should use `.skip_binder()` instead of `.0`.

2016-11-28 01:39 UTC, eddyb commented on src/librustc/ty/sty.rs
> +        self.0.len()
Can this be avoided?

2016-11-28 01:39 UTC, eddyb commented on src/librustc/ty/sty.rs
> +        Binder(self.0.with_self_ty(tcx, self_ty))
Use `map_bound` (here and elsewhere possible).

2016-11-28 01:39 UTC, eddyb commented on src/librustc/ty/sty.rs
> +        self.0.sort_key(tcx)
`.skip_binder()` here and above.

2016-11-28 01:39 UTC, eddyb commented on src/librustc/ty/util.rs
> +                              &param_env.is_copy_cache, span) });
This should be `is_sized_cache` not `is_copy_cache` (I'm surprised this doesn't break anything).

2016-11-28 01:39 UTC, eddyb commented on src/librustc/ty/walk.rs
> +                };
This `match` can produce `(substs, opt_ty)` which would be cleaner.

2016-11-28 01:39 UTC, eddyb commented on src/librustc/ty/walk.rs
> +                types.rev()
This is reversing the already reversed types, it should be just the chained iterator, no extra `.rev()`.

2016-11-28 01:39 UTC, eddyb commented on src/librustc/ty/wf.rs
> +                        data.auto_traits().chain(data.principal().map(|ref p| p.def_id()));
Unnecessary `ref`.

2016-11-28 01:39 UTC, eddyb commented on src/librustc/ty/wf.rs
> +                ty::TyDynamic(ref data, r) => {
Unnecessary `ref`.

2016-11-28 01:39 UTC, eddyb commented on src/librustc_trans/context.rs
> +    vtables: RefCell<FxHashMap<(ty::Ty<'tcx>, Option<ty::PolyTraitRef<'tcx>>), ValueRef>>,
`PolyExistentialTraitRef`, to keep the `Self` orthogonal.

2016-11-28 01:39 UTC, eddyb commented on src/librustc_typeck/astconv.rs
>              let r = explicit_region_bounds[0];
If you want to rewrite this you can use `if let Some(&r) = explicit_region_bounds.get(0)`.

2016-11-28 01:39 UTC, eddyb commented on src/librustc_typeck/astconv.rs
> +                def_id: tcx.lang_items.sized_trait().unwrap(),
Use `if let Some` here.

2016-11-28 01:39 UTC, eddyb commented on src/librustc_typeck/check/wfcheck.rs
> +                if trait_ref.def_id != sync_trait && trait_ref.def_id != send_trait {
Is this check necessary anymore? AFAIK `trait_has_default_impl` returns true for `Send` and `Sync`.

2016-11-28 01:39 UTC, eddyb commented on src/librustc_typeck/collect.rs
> +                unbound = Some(ptr.trait_ref.ref_id.clone());
No need to `.clone()`.

2016-11-28 01:39 UTC, eddyb commented on src/librustc_typeck/collect.rs
> +        Some(ref ref_id) => {
Unnecessary `ref`.

2016-11-28 01:39 UTC, eddyb commented on src/librustc_typeck/diagnostics.rs
> +one non-builtin type, plus either or both of Send and Sync. For example, the
s/type/trait

2016-11-28 01:59 UTC, eddyb commented
[Crater report](https://gist.github.com/eddyb/45fd0639dbc0dc0c0e9e3f0d27077f4c) contains no legitimate regressions (ignoring uses of `TyTrait` in lints).

2016-11-28 14:11 UTC, Mark-Simulacrum commented
@eddyb Rebased, but haven't run tests--started those locally (and Travis will test too, of course).

2016-11-28 19:44 UTC, eddyb commented on src/librustc/traits/mod.rs
>                                                          ty: Ty<'tcx>,
There's a few indentation aberrations, here and in a few other places. Let me know if you want a list.

2016-11-28 19:52 UTC, eddyb commented on src/librustc_typeck/astconv.rs
> +                   .map(|x| ty::ExistentialPredicate::Projection(x.0)))
At least use `.skip_binder()` instead of `.0`.

2016-11-29 02:28 UTC, Mark-Simulacrum commented
Fixed review comments.

r? @eddyb

2016-11-29 04:58 UTC, eddyb approved these changes

2016-11-29 04:59 UTC, eddyb commented
@bors r+

2016-11-30 06:29 UTC, merged

2017-04-23 13:13 UTC, tschottdorf commented
@Mark-Simulacrum: Very late to the party, but I just ran into the the sort order while spelunking for https://github.com/rust-lang/rust/issues/41444, and I'm curious about:

> The sort order is asserted to be correct during interning, but the slices are not sorted at that point.

What does "correct" mean? I can see from the code that the only time the assertion runs is when it is passed something that has previously been sorted using the same `cmp`. But I'm not sure what the point of this ordering is.

> ExistentialPredicate::Trait are defined as always equal; This may be wrong; should we be comparing them and sorting them in some way?

Why not just tie-break by `DefId`? Or rather, why does it not matter which way two `Trait`s compare? For interning, it seems to matter because when you have the "same" slice interned twice but the order differs, to my untrained eye it seems easy enough to introduce subtle bugs when doing pointer-comparisons, etc.

2017-04-24 18:05 UTC, Mark-Simulacrum commented
> What does "correct" mean? I can see from the code that the only time the assertion runs is when it is passed something that has previously been sorted using the same cmp. But I'm not sure what the point of this ordering is.

Since we now represent `TraitObject` as a slice of `ExistentialPredicate`s, we need an efficient method to access the parts, which means that we sort into a particular order. As long as the `ExistentialPredicate` variants are in the correct order, we don't care about the specific order of the variants within each "set."

I think I answered the second question as well. You do make a good point about possibly more efficient interning if we sorted with tie-breaking by `DefId`; that sounds like a potential optimization, though I don't know how good the wins (if any) will be.

Let me know if you have any more questions!

2017-04-24 18:07 UTC, eddyb commented
You simply can't have more than one `Trait` right now, so ignoring `DefId` *is* an optimization.

2017-04-27 01:12 UTC, tschottdorf commented
@Mark-Simulacrum: Thanks for the explanation. I have one follow-up question on the following (and it's not really a question about this code in particular any more):

> Since we now represent TraitObject as a slice of ExistentialPredicates, we need an efficient method to access the parts, which means that we sort into a particular order. As long as the ExistentialPredicate variants are in the correct order, we don't care about the specific order of the variants within each "set."

The comment on `Slice` explains:

> /// A wrapper for slices with the additional invariant
/// that the slice is interned and no other slice with
/// the same contents can exist in the same context.
/// This means we can use pointer + length for both
/// equality comparisons and hashing.

I guess it depends on what is meant by "same contents", but it would seem to me that at this point you could wind up interning both of the slices `&[a,b]` and `&[b,a]`. And, I assume you're fine with that in your use case, but in general if pointer+length is used for equality and you consider things "equal" under certain permutations, isn't there something weird that can happen (afaict, if there's only ever one `Trait(_)`, it seems such permutations can't happen for yo in practice, but still)?

2017-04-27 01:16 UTC, Mark-Simulacrum commented
Slices can be compared by pointer and length because they're always interned, which means that `&[a,b]` and `&[b,a]` will not compare equally, which is "correct"; arguably if and when we add multiple `Trait`s in the `ExistentialPredicate` list we should probably sort them. I'm not sure, though. @eddyb might be able to explain more clearly....