Document how lock 'guard' structures are created.
rust-lang/rust pull request #38010
Opened 2016-11-25 22:50 UTC by frewsxcv

2016-11-25 22:50 UTC, frewsxcv commented
r? @GuillaumeGomez

2016-11-25 22:50 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @sfackler (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-11-25 23:40 UTC, GuillaumeGomez commented on src/libstd/sync/mutex.rs
>  /// `Deref` and `DerefMut` implementations
Not PR-bound but shouldn't be a dot present a the end of this sentence?

2016-11-25 23:41 UTC, GuillaumeGomez requested changes
Just a small nit and it's good.

2016-11-25 23:41 UTC, GuillaumeGomez commented on src/libstd/sync/rwlock.rs
> +/// This structure is created by the [`read()`]  and [`try_read()`] methods on
Extra whitespace in "[`read()`]  and".

2016-11-25 23:58 UTC, frewsxcv commented
Comments have been addressed.

2016-11-26 00:03 UTC, GuillaumeGomez commented
Now squash time! \o/ (just the last commit)

2016-11-26 00:10 UTC, GuillaumeGomez approved these changes

2016-11-26 00:10 UTC, GuillaumeGomez commented
Thanks!

@bors: r+ rollup

2016-11-26 18:32 UTC, merged