Display better error messages for E0282
rust-lang/rust pull request #38057
Opened 2016-11-28 19:56 UTC by KiChjang

Fixes #36554.

2016-11-28 19:56 UTC, rust-highfive commented
r? @nrc

(rust_highfive has picked a reviewer for you, use r? to override)

2016-11-29 19:53 UTC, frewsxcv commented
FYI, Travis found some issues.

2016-11-29 21:27 UTC, KiChjang commented
r? @nikomatsakis

2016-11-30 19:34 UTC, nikomatsakis requested changes
Looks good! I just left one minor suggestion. The other thing that I'm missing is some kind of dedicated test where we show off a nice error. Maybe a UI test for this case?

```rust
fn foo<X>() { }
fn bar() {
    foo();
}
```

2016-11-30 19:34 UTC, nikomatsakis commented on src/librustc/infer/lattice.rs
> +            let v = infcx.next_diverging_ty_var(TypeVariableOrigin::LatticeVariable);
We can give more information about lattice variables -- at minimum, we can give a span. The `this` variable is always of a type (either `Lub` or `Glb`) that has access to a `CombineFields` (`self.fields`, in each case). `CombineFields` has a field `trace` of type `TypeTrace`, and hiding in there is a field `cause` of type `ObligationCause`. This is basically "why we are computing the common-supertype or common-subtype of these types". At minimum though it'd be nice to add a method `fn cause(&self) -> &OlbligationCause<'tcx>` to `LatticeDir` that returns `&self.fields.cause`. Then we can create give a span here like `LatticeVariable(this.cause().span)`.

2016-11-30 19:34 UTC, nikomatsakis commented on src/librustc/infer/type_variable.rs
> +    LatticeVariable,
...if we give `LatticeVariable` a span, then every variant will have one.

2016-11-30 20:00 UTC, KiChjang commented
@nikomatsakis There is actually a UI test that demonstrates this and it's at `src/test/ui/codemap_tests/repair_span_std_macros.rs`. Would that suffice or do you think it's still better to create a new one specifically for this?

2016-11-30 23:45 UTC, KiChjang commented on src/librustc/infer/lattice.rs
> +            let v = infcx.next_diverging_ty_var(TypeVariableOrigin::LatticeVariable);
Ack, the complication here is that `self.fields.cause` is an `Option<ObligationCause>`. How should I ensure that there must always be an `ObligationCause`?

2016-12-01 00:09 UTC, KiChjang commented on src/librustc/infer/lattice.rs
> +            let v = infcx.next_diverging_ty_var(TypeVariableOrigin::LatticeVariable);
Found it, `self.trace.cause` may work.

2016-12-09 14:33 UTC, nikomatsakis commented
@KiChjang 

> There is actually a UI test that demonstrates this and it's at src/test/ui/codemap_tests/repair_span_std_macros.rs. Would that suffice or do you think it's still better to create a new one specifically for this?

I think it's better to have a targeted test. For one thing, when doing refactorings, it is often hard to tell if a change to the test's output is acceptable or not; but if there is a focused test that is aimed at this particular feature, it will be more obvious. Another thing that happens from time to time is that when we are doing refactorings some test is hard to port to the new system and winds up getting deleted, thereby inadvertendly removing the only test for *this* feature. So I think it's best to have simple tests that specifically target your change (in addition to the ones which accidentally do so).

Plus, the scenario in that UI test was not quite the one I suggested, right?

```
fn foo<X>() { }
fn bar() {
    foo();
}
```

2016-12-09 14:33 UTC, nikomatsakis commented
(Sorry for the delay.)

2016-12-09 21:28 UTC, KiChjang commented
UI test added.

2016-12-10 01:26 UTC, nikomatsakis commented
@KiChjang 

tidy error: `/checkout/src/test/ui/missing-items/missing-type-parameter.rs: incorrect license`

2016-12-10 01:26 UTC, nikomatsakis approved these changes

2016-12-10 02:27 UTC, KiChjang commented
Dumb vim. Fixed license now.

2016-12-10 07:42 UTC, KiChjang commented
Huh... I'm not sure what the error in Travis CI is about this time.

2016-12-11 22:27 UTC, eddyb commented
@bors r=nikomatsakis

2016-12-12 03:35 UTC, merged