note individual lint name in messages set via lint group attribute
rust-lang/rust pull request #38103
Opened 2016-12-01 06:11 UTC by zackmdavis

![lint_errors_resulting_from_lint_groups_obscure](https://cloud.githubusercontent.com/assets/1076988/20783614/c107d5c8-b749-11e6-85de-eada7f67c986.png)

Resolves #36846.

r? @jonathandturner

2016-12-14 02:16 UTC, zackmdavis commented
@jonathandturner are you interested in reviewing (the reason I r?'d you is because you [seemed to express interest](https://github.com/rust-lang/rust/issues/36846#issuecomment-264069631) in the issue comments), or should we tag someone else (perhaps @brson, the issue filer)?

2016-12-14 02:21 UTC, jonathandturner commented
@zackmdavis - sorry for the delay.  I'm currently on vacation so I haven't been doing much reviewing.

Just taking a glance, I'd move that new message to a note (without a span) possibly.  Cool that it's there now, though.

2016-12-15 02:29 UTC, zackmdavis commented
> I'm currently on vacation so

Oh, sorry to bother you! (I can only hope that my [bad luck of accidentally bothering people on vacation](https://github.com/rust-lang/rust/pull/34084#issuecomment-228793518) does not become a trend.)

> I'd move that new message to a note (without a span)

And presumably also the `#[{}({})] on by default` message on which it is based. Yes, I can do that (on the timescale of some days; I unfortunately don't have a development environment handy right now).

2016-12-17 05:01 UTC, zackmdavis commented
Updated:
* 9603a5f moves the `#[level(individual_lint)] on by default` and `#[level(lint_group)] implies #[level(individual_lint)]` into a span-less note, rather than being part of the main lint message, as Jonathan suggests.
* bb685b5 slightly broadens the scope of this pull request, but to a degree that I argue is entirely appropriate: it differentiates between an individual lint _vs._ a lint group having been set on the command line (analogously to the case of lints set via attributes, which inspired this endeavor)

2016-12-17 16:56 UTC, zackmdavis commented
* and 7ba8b4d to update the UI tests because somehow `make check` weren't running them for me earlier (?!) although `./x.py test src/test/ui/` works

2016-12-17 18:14 UTC, zackmdavis commented
r? @brson

2016-12-29 21:50 UTC, aturon commented
cc @nikomatsakis

2016-12-30 19:18 UTC, nikomatsakis commented
I don't mind reviewing this. 

@zackmdavis -- I would rather expect these clarifications to appear on the "lint level defined here" note, rather than in the main heading. What do you think?

2016-12-30 19:18 UTC, nikomatsakis commented
r? @nikomatsakis

2016-12-30 19:19 UTC, nikomatsakis commented
oh, I missed the updated pics.

2017-01-03 18:59 UTC, nikomatsakis requested changes
This looks pretty good! It does seem like there are a few scenarios not tested though. Can you add UI tests for these cases:

- using command-line flags (`-W` etc) that affect a lint indirectly (and hence trigger the "implies" message)
- using each of the various settings (-W etc)

You can customize a test to include compilation flags by putting a `// compile-flags: ...` annotation in the test (ripgrep around for examples).

Thanks!

2017-01-03 18:59 UTC, nikomatsakis commented on src/test/compile-fail/lint-group-style.rs
> +        //~| NOTE #[warn(bad_style)] implies #[warn(non_camel_case_types)]
I think these tests should be made into "ui" tests -- see https://github.com/rust-lang/rust/blob/master/src/test/ui/README.md for some tips on how to work with those.

2017-01-05 17:12 UTC, zackmdavis commented
@nikomatsakis moved make-lint-group-style.rs to be a UI test rather than a compile fail test as [you suggested](https://github.com/rust-lang/rust/pull/38103#discussion_r94460982) (b4e7128), added UI tests for command-line -A/-W/-D/-F with a lint group (fc692f5), had to merge in master to get Travis to pass (babce29, 7e50b02)

2017-01-05 20:32 UTC, nikomatsakis requested changes
Looking really good. =) I have a few more suggestions, curious as to your opinion.

Oh, and one other thing: can you rebase atop rust-lang/master (and squash, probably), rather than merging master into your branch? Just keeps the history a little cleaner. Thanks.

2017-01-05 20:32 UTC, nikomatsakis commented on src/test/ui/span/multispan-import-lint.stderr
> +   = note: #[warn(unused_imports)] on by default
I'm very happy to see this moved into an auxiliary note. I've always been annoyed by having it on the main message line :)

2017-01-05 20:32 UTC, nikomatsakis commented on src/test/ui/span/issue-24690.stderr
> +   = note: #[deny(warnings)] implies #[deny(unused_variables)]
it feels like this should be attached to the message below (`lint level defined here`), and also that it should only appear when that message appears (meaning only once), what do you think?

2017-01-05 20:32 UTC, nikomatsakis commented on src/test/ui/lint/command-line-lint-group-forbid.stderr
> +   = note: `-F bad-style` implies `-F non-snake-case`
I keep being surprised by the ordering here. What do you think about saying "`-F non-snake-case` implied by `-F bad-style` or something?

2017-01-06 03:45 UTC, zackmdavis commented on src/test/ui/span/issue-24690.stderr
> +   = note: #[deny(warnings)] implies #[deny(unused_variables)]
I agree that this is desirable, but doing it properly will involve addressing [the `FIXME`](https://github.com/rust-lang/rust/blob/164619a8cf/src/librustc/session/mod.rs#L322-L325) about generalizing one-time diagnostics beyond `span_note`, which looks sufficiently complicated that I'd prefer to do it in a separate PR.

(The most obvious thing to do would be to extract [the body of what is now](https://github.com/rust-lang/rust/blob/164619a8cf/src/librustc/session/mod.rs#L329-L342) `diag_span_note_once` into a more general `diag_once` that takes an enum argument to decide which method to call (`span_note` or `note` or `warn` or _&c._) on the diagnostic builder ... or are macros the way to go here? I think this is out-of-scope for this PR.)

2017-01-06 05:05 UTC, zackmdavis commented
@nikomatsakis 

rebased and squashed previous work into 3 commits (down from 8); "implies" _vs._ "implied by" comment addressed in 5bceb47; [prefer to defer](https://github.com/rust-lang/rust/pull/38103#discussion_r94896191) the work to make implied-by-lint-group notes one-time

2017-01-06 20:05 UTC, nikomatsakis approved these changes

2017-01-06 20:05 UTC, nikomatsakis commented
@bors r+

2017-01-06 20:05 UTC, nikomatsakis commented
@zackmdavis great! :)

2017-01-07 16:44 UTC, zackmdavis commented
The Appveyor CI [failure](https://ci.appveyor.com/project/rust-lang/rust/build/1.0.1440/job/excc4936s1j0kiae) seems to be [in the Cargo repo](https://github.com/rust-lang/cargo/blob/40a4ce61b/tests/build.rs#L2404), not something I can fix in this pull request. Does @bors know how to "test this Rust branch against this Cargo branch, and merge them both on success", or would we have to force this and fix the Cargo test expectation immediately after?

2017-01-08 00:54 UTC, zackmdavis commented
@nikomatsakis ^^ rust-lang/cargo#3513 should fix the Cargo test failure

2017-01-09 23:02 UTC, nikomatsakis commented
@zackmdavis ok, I suppose we have to wait for that to land?

2017-01-12 19:00 UTC, zackmdavis commented
Yes, but unfortunately there are [currently some yaks in the way](https://github.com/rust-lang/cargo/pull/3513#issuecomment-272097256); to be continued next week

2017-01-19 07:47 UTC, nikomatsakis commented
@zackmdavis very good, I'll keep checking in :)

2017-01-26 20:36 UTC, nikomatsakis commented
@zackmdavis still blocked?

2017-01-26 23:39 UTC, zackmdavis commented
Unfortunately, I've been too distracted with other projects to attempt to extend Cargo's test infrastructure to let us weaken the test expectation to not depend on the exact compiler JSON output, while still checking the JSON that Cargo itself is responsible for. I'd be happy if there's any way to [accept my commit](https://github.com/rust-lang/cargo/pull/3513#issuecomment-271784125) to just check JSON validity in order to unblock this PR, and then leave an issue to re-strengthen the test expectation afterwards, but if that's not an option, I can try to set aside some time Saturday to look at JSON wildcarding

2017-01-27 15:31 UTC, nikomatsakis commented
@zackmdavis hmm ok I don't know much about that other PR (which I gather is for cargo, not rust).

2017-02-03 07:15 UTC, zackmdavis commented
(force-pushed) @nikomatsakis Ready!! :running_woman: :checkered_flag: :sparkling_heart:

2017-02-03 15:28 UTC, zackmdavis commented
I almost want to ask if this can get p=1 just because it's been so long, but that's probably not fair

2017-02-03 20:50 UTC, nikomatsakis commented
@zackmdavis older PRs already get priority =)

2017-02-03 20:51 UTC, nikomatsakis commented
@bors r+

2017-02-03 22:12 UTC, zackmdavis commented
:eyes: *glances at [queue](https://buildbot2.rust-lang.org/homu/queue/rust)*

auuugh 82e42d5 is going to collide with #36320's b7f1d7a4

:crying_cat_face: :sob: :skull: *sobs in existential despair*

2017-02-04 21:52 UTC, alexcrichton commented
@bors: r=nikomatsakis

2017-02-05 04:00 UTC, merged