Add error explanation for E0328.
rust-lang/rust pull request #38108
Opened 2016-12-01 15:08 UTC by linclark

This PR adds an explanation for an error in the list in #32777.

I haven't used this feature myself, so I was piecing it together from the docs. Please let me know if any changes in wording should be made.

One problem: When I followed the instructions in CONTRIBUTING.md, it said to run `make check-stage1` before posting the PR. This reported failures, but they seemed to be intermittent. I got different numbers of failures on each run. Here's the output for the last run

```
failures:

---- [run-make] run-make/rustc-macro-dep-files stdout ----

error: make failed
status: exit code: 2
command: "make"
stdout:
------------------------------------------
DYLD_LIBRARY_PATH="/Users/lclark/Repos/rust/x86_64-apple-darwin/test/run-make/rustc-macro-dep-files.stage1-x86_64-apple-darwin:/Users/lclark/Repos/rust/x86_64-apple-darwin/stage1/lib:" '/Users/lclark/Repos/rust/x86_64-apple-darwin/stage1/bin/rustc' --out-dir /Users/lclark/Repos/rust/x86_64-apple-darwin/test/run-make/rustc-macro-dep-files.stage1-x86_64-apple-darwin -L /Users/lclark/Repos/rust/x86_64-apple-darwin/test/run-make/rustc-macro-dep-files.stage1-x86_64-apple-darwin  foo.rs
DYLD_LIBRARY_PATH="/Users/lclark/Repos/rust/x86_64-apple-darwin/test/run-make/rustc-macro-dep-files.stage1-x86_64-apple-darwin:/Users/lclark/Repos/rust/x86_64-apple-darwin/stage1/lib:" '/Users/lclark/Repos/rust/x86_64-apple-darwin/stage1/bin/rustc' --out-dir /Users/lclark/Repos/rust/x86_64-apple-darwin/test/run-make/rustc-macro-dep-files.stage1-x86_64-apple-darwin -L /Users/lclark/Repos/rust/x86_64-apple-darwin/test/run-make/rustc-macro-dep-files.stage1-x86_64-apple-darwin  bar.rs --emit dep-info

------------------------------------------
stderr:
------------------------------------------
dyld: lazy symbol binding failed: Symbol not found: __ZN4core3fmt5write17h2f7663117dd4fb40E
  Referenced from: /Users/lclark/Repos/rust/x86_64-apple-darwin/test/run-make/rustc-macro-dep-files.stage1-x86_64-apple-darwin/libfoo.dylib
  Expected in: /Users/lclark/Repos/rust/x86_64-apple-darwin/stage1/lib/libstd-fdb5dc8c.dylib

dyld: Symbol not found: __ZN4core3fmt5write17h2f7663117dd4fb40E
  Referenced from: /Users/lclark/Repos/rust/x86_64-apple-darwin/test/run-make/rustc-macro-dep-files.stage1-x86_64-apple-darwin/libfoo.dylib
  Expected in: /Users/lclark/Repos/rust/x86_64-apple-darwin/stage1/lib/libstd-fdb5dc8c.dylib

make[1]: *** [all] Trace/BPT trap: 5

------------------------------------------

thread '[run-make] run-make/rustc-macro-dep-files' panicked at 'explicit panic', /Users/lclark/Repos/rust/src/tools/compiletest/src/runtest.rs:2407
note: Run with `RUST_BACKTRACE=1` for a backtrace.

failures:
    [run-make] run-make/rustc-macro-dep-files

test result: FAILED. 136 passed; 1 failed; 0 ignored; 0 measured

thread 'main' panicked at 'Some tests failed', /Users/lclark/Repos/rust/src/tools/compiletest/src/main.rs:302
make: *** [tmp/check-stage1-T-x86_64-apple-darwin-H-x86_64-apple-darwin-rmake.ok] Error 101
```

r? @GuillaumeGomez

2016-12-01 15:08 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @GuillaumeGomez (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-12-01 16:31 UTC, GuillaumeGomez requested changes

2016-12-01 16:31 UTC, GuillaumeGomez commented on src/librustc_typeck/diagnostics.rs
> +Here's an example of this error:
Please replace with "Erroneous code example". We try to keep a standard.

2016-12-01 16:31 UTC, GuillaumeGomez commented on src/librustc_typeck/diagnostics.rs
> +instead.
From what you said, it *seems* possible to do it. Could you add an example showing how please?

2016-12-01 16:31 UTC, GuillaumeGomez commented
Don't worry for the build. Travis said it's okay so don't bother with it (even if you're failure is strange :-/ ).

2016-12-18 10:33 UTC, GuillaumeGomez commented
@linclark: Are you still working on it?

2016-12-19 23:07 UTC, linclark commented
Sorry for the delay, I had to travel for work and am just getting things back in order from that. I will make the changes in the next couple of days.

2016-12-21 16:41 UTC, GuillaumeGomez commented
No problem, take your time. It was just to check if it wasn't a dead PR.

2017-01-05 20:03 UTC, linclark commented
@GuillaumeGomez Ok, this has been updated with an example of how to fix it. Note, I tested that this compiles, but I've never implemented `CoerceUnsized` in a real project. Because I haven't worked with it before, there's a chance this example isn't idiomatic.

2017-01-06 10:05 UTC, GuillaumeGomez commented
Hum... Your example doesn't show much but I'm afraid that demonstrating it might take a lot of place. So I wonder if we should just keep the current example or make it bigger and more complete...

What do you think about it @rust-lang/docs?

2017-01-15 10:16 UTC, GuillaumeGomez commented
cc @rust-lang/docs

2017-01-22 10:32 UTC, GuillaumeGomez commented
Ok, since no one seems interested, I'll r+ it and it'll updated in the future if needed. Thanks for your work!

@bors: r+ rollup

2017-01-22 10:32 UTC, GuillaumeGomez approved these changes

2017-01-22 12:35 UTC, GuillaumeGomez commented
@bors: retry

2017-01-22 16:54 UTC, merged