Add From<[u16; 8]> to Ipv6Addr
rust-lang/rust pull request #38131
Opened 2016-12-02 17:22 UTC by clarcharr

Not really sure that this requires an RFC, but I figured that I'd offer a pull request and see what people think. It seems like a reasonable addition.

2016-12-02 17:22 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @sfackler (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2016-12-02 17:26 UTC, sfackler commented
We've had the analagous `impl From<[u8; 4]> for Ipv4Addr` since 1.9, so this seems reasonable to me!

@rfcbot fcp merge

2016-12-02 17:26 UTC, sfackler commented on src/libstd/net/ip.rs
> +#[unstable(feature = "ipv6_from_segments", issue = "0")]
I believe we'll want to mark this stable, since the compiler can't track stability of impls at the moment.

2016-12-02 19:59 UTC, mattico commented on src/libstd/net/ip.rs
> +#[stable(feature = "ipv6_from_segments", issue = "1.15.0")]
I believe this should be **since**= "1.15.0"

2016-12-06 10:12 UTC, achanda requested changes

2016-12-06 10:12 UTC, achanda commented on src/libstd/net/ip.rs
> +#[stable(feature = "ipv6_from_segments", since = "1.15.0")]
Should this be stable?

2016-12-06 10:12 UTC, achanda commented on src/libstd/net/ip.rs
> +
This should have a test like it's v4 counterpart

2016-12-06 17:39 UTC, sfackler commented on src/libstd/net/ip.rs
> +        let [a, b, c, d, e, f, g, h] = segments;
How is this allocating anything?

2016-12-06 17:49 UTC, sfackler commented on src/libstd/net/ip.rs
> +        let [a, b, c, d, e, f, g, h] = segments;
I don't know if allocation is the right way to describe that. The compiler can and will significantly transform data manipulations.

2016-12-06 17:52 UTC, clarcharr commented on src/libstd/net/ip.rs
> +        let [a, b, c, d, e, f, g, h] = segments;
I was under the impression that this is just providing aliases for each of the indexed variables, but I could be wrong. I assumed that bound variables and registers/stack slots was not a 1-1 mapping.

2016-12-06 17:59 UTC, clarcharr commented on src/libstd/net/ip.rs
> +
I agree! I added some.

2016-12-06 18:02 UTC, achanda commented on src/libstd/net/ip.rs
> +        let [a, b, c, d, e, f, g, h] = segments;
Makes sense then, thanks!

2016-12-06 18:11 UTC, achanda commented on src/libstd/net/ip.rs
> +        let [a, b, c, d, e, f, g, h] = segments;
ok, thanks for explaining that

2016-12-07 00:31 UTC, sfackler commented
ping @BurntSushi @brson

2016-12-12 21:49 UTC, clarcharr commented
ping @brson again

2016-12-19 04:10 UTC, clarcharr commented
Squashed the commits and updated to master.

2016-12-20 00:20 UTC, alexcrichton commented
@bors: r+

Thanks for the patience @clarcharr!

2016-12-20 17:45 UTC, alexcrichton commented
@bors: retry

On Mon, Dec 19, 2016 at 6:08 PM, bors <notifications@github.com> wrote:

> 💔 Test failed - auto-win-msvc-64-opt
> <https://buildbot.rust-lang.org/builders/auto-win-msvc-64-opt/builds/6471>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/38131#issuecomment-268134270>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAD95KBKkwBDEtfVaYkry3vfkiktLDxNks5rJzingaJpZM4LCyhV>
> .
>

2016-12-21 02:48 UTC, merged