Fix associated types in copy implementations
rust-lang/rust pull request #38152
Opened 2016-12-04 00:05 UTC by arielb1

Fixes an ICE and an error in checking copy implementations.

r? @nikomatsakis

2016-12-04 22:02 UTC, mrhota commented on src/librustc_typeck/coherence/builtin.rs
> +    tcx: TyCtxt<'a, 'tcx, 'tcx>, impl_did: DefId,
nit: maybe separate each arg on its own line?

2016-12-04 22:13 UTC, mrhota commented
curiously, the test will ICE immediately with Stable rustc on play.rust-lang.org, but will timeout with beta and nightly.

2016-12-09 15:44 UTC, nikomatsakis requested changes

2016-12-09 15:44 UTC, nikomatsakis commented on src/librustc/ty/util.rs
> +                                return Err(CopyImplementationError::InfrigingVariant(
Pre-existing, but it seems like it would be nice to give both the variant name *and* the field name -- can we do that instead?

2016-12-09 15:44 UTC, nikomatsakis commented on src/librustc_typeck/coherence/builtin.rs
> +    tcx: TyCtxt<'a, 'tcx, 'tcx>, impl_did: DefId,
I'd say just rustfmt this new file and be done with it.

2016-12-09 15:44 UTC, nikomatsakis commented on src/librustc_typeck/coherence/builtin.rs
> +    let self_type = tcx.item_type(impl_did);
Is this file all code collected from other places, or did you make changes to it? I couldn't tell.

2016-12-09 16:55 UTC, arielb1 commented on src/librustc_typeck/coherence/builtin.rs
> +    let self_type = tcx.item_type(impl_did);
Code moved from `coherence::mod`.

2016-12-09 16:55 UTC, arielb1 commented
How do you rustfmt?

2016-12-10 01:24 UTC, nikomatsakis commented
@arielb1 `cargo install rustfmt`, then run it on the file I think

2016-12-27 22:22 UTC, nikomatsakis commented
@arielb1 if you don't feel like running rustfmt, no biggy, but let's rebase :)

2017-01-03 19:00 UTC, nikomatsakis approved these changes

2017-01-03 19:00 UTC, nikomatsakis commented
@bors r+

2017-01-03 19:50 UTC, arielb1 commented
I was just going to rustfmt the new file and add better error reporting.

@bors r-

2017-01-03 21:59 UTC, nikomatsakis commented on src/test/compile-fail/E0204.rs
> +    Baz,
can we make this a `ui` test? I'd like to see precisely where the span is, since it's critical to the message

2017-01-03 22:07 UTC, nikomatsakis commented on src/test/ui/span/E0204.stderr
> +   |           ----------- this field does not implement `Copy`
looks great :)

2017-01-03 22:07 UTC, nikomatsakis commented
@bors r+

2017-01-04 09:56 UTC, arielb1 commented
@bors r=nikomatsakis

2017-01-04 15:47 UTC, arielb1 commented
- #31657

@bors retry

2017-01-04 17:39 UTC, bluss commented
@bors retry

2017-01-04 23:14 UTC, arielb1 commented
- #38618 

@bors retry

2017-01-05 12:18 UTC, arielb1 commented
```
The command "if [ "$ALLOW_PR" = "" ] && [ "$TRAVIS_BRANCH" != "auto" ]; then
    echo skipping, not a full build;
elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
    git submodule update --init &&
    src/ci/run.sh;
else
    git submodule update --init &&
    src/ci/docker/run.sh $IMAGE;
fi
" exited with 129.
```

cc @alexcrichton 

@bors retry

2017-01-05 15:05 UTC, merged