Improvements to `BTreeSet` documentation.
rust-lang/rust pull request #38208
Opened 2016-12-07 01:48 UTC by frewsxcv

2016-12-07 01:51 UTC, frewsxcv commented
r? @GuillaumeGomez @Ms2ger

2016-12-07 02:24 UTC, GuillaumeGomez requested changes
Just a few nits and should be good to go!

2016-12-07 02:24 UTC, GuillaumeGomez commented on src/libcollections/btree/set.rs
> +/// An iterator over a `BTreeSet`'s items.
a `BTreeSet`'s item**S**?

EDIT: Actually, it can be understood differently. Well, leaving this comment here anyway.

2016-12-07 02:24 UTC, GuillaumeGomez commented on src/libcollections/btree/set.rs
> +/// This structure is created by the [`iter`] method on [`BTreeSet`].
"iter()".

2016-12-07 02:24 UTC, GuillaumeGomez commented on src/libcollections/btree/set.rs
> +/// This structure is created by the [`into_iter`] method on [`BTreeSet`]
"into_iter()"

2016-12-07 02:24 UTC, GuillaumeGomez commented on src/libcollections/btree/set.rs
> +/// This structure is created by the [`range`] method on [`BTreeSet`].
"range()"

2016-12-07 02:24 UTC, GuillaumeGomez commented on src/libcollections/btree/set.rs
> +/// This structure is created by the [`difference`] method on [`BTreeSet`].
"difference()"

2016-12-07 02:24 UTC, GuillaumeGomez commented on src/libcollections/btree/set.rs
> +/// This structure is created by the [`symmetric_difference`] method on
"symmetric_difference()"

2016-12-07 02:24 UTC, GuillaumeGomez commented on src/libcollections/btree/set.rs
> +/// This structure is created by the [`intersection`] method on [`BTreeSet`].
"intersection()"

2016-12-07 02:24 UTC, GuillaumeGomez commented on src/libcollections/btree/set.rs
> +/// This structure is created by the [`union`] method on [`BTreeSet`].
"union()"

2016-12-07 03:04 UTC, frewsxcv commented
Comments have been addressed.

2016-12-07 08:21 UTC, GuillaumeGomez commented
Thanks! I think one commit would have been more than enough here, but whatever! :p

@bors: r+ rollup

2016-12-07 08:23 UTC, GuillaumeGomez approved these changes

2016-12-07 16:48 UTC, frewsxcv commented
@bors r-

Looks like there are link errors

2016-12-07 16:52 UTC, frewsxcv commented
I think I fixed the links. Will wait for Travis.

2016-12-07 18:42 UTC, GuillaumeGomez commented
Seems not. ;)

2016-12-07 18:53 UTC, frewsxcv commented
@GuillaumeGomez Can you find the error in the logs? I can't seem to find it. Maybe I'll force push.

2016-12-07 23:10 UTC, GuillaumeGomez commented
Didn't find it either. I restarted the build.

2016-12-08 07:20 UTC, goffrie commented on src/libcollections/btree/set.rs
> +/// [`BTreeSet`] (provided by the [`IntoIterator`] trait).
Am I misunderstanding the syntax or are there two `BTreeSet`s in a row here?

2016-12-08 07:23 UTC, frewsxcv commented on src/libcollections/btree/set.rs
> +/// [`BTreeSet`] (provided by the [`IntoIterator`] trait).
If one writes:

    ```rust
    [`BTreeSet`] (hello world)

    [`BTreeSet`]: https://google.com
    ```

rustdoc will treat this as a link to the url "https://hello world" which is not what we want. Instead, we have to write

    ```rust
    [`BTreeSet`][`BTreeSet`] (hello world)

    [`BTreeSet`]: https://google.com
    ```

which will link to https://google.com

2016-12-09 07:31 UTC, frewsxcv commented
I don't see any errors, so I'm going to consider the links to be fixed.

@bors r=GuillaumeGomez rollup

2016-12-12 17:28 UTC, frewsxcv commented
@bors r-

```
Linkcheck stage2 (x86_64-pc-windows-msvc)
collections\btree_set\struct.IntoIter.html:53: broken link - iter\trait.IntoIterator.html
collections\btree_set\struct.IntoIter.html:53: broken link - iter\trait.IntoIterator.html
```

2016-12-15 21:23 UTC, frewsxcv commented
Travis is green now.

@bors r=GuillaumeGomez

2016-12-16 15:47 UTC, GuillaumeGomez commented
You broke the CI again. :p

```
failures:

---- hash::BuildHasherDefault_0 stdout ----
	error[E0412]: type name `SomeHasher` is undefined or not in scope
  --> <anon>:22:41
   |
22 | type MyBuildHasher = BuildHasherDefault<SomeHasher>;
   |                                         ^^^^^^^^^^ undefined or not in scope
   |
   = help: no candidates by the name of `SomeHasher` found in your project; maybe you misspelled the name or forgot to import an external crate?

error[E0412]: type name `SomeBuidHasher` is undefined or not in scope
  --> <anon>:24:36
   |
24 | let hash_map = HashMap::<u32, u32, SomeBuidHasher>::default();
   |                                    ^^^^^^^^^^^^^^ undefined or not in scope
   |
   = help: no candidates by the name of `SomeBuidHasher` found in your project; maybe you misspelled the name or forgot to import an external crate?

error: aborting due to previous error(s)

thread 'hash::BuildHasherDefault_0' panicked at 'Box<Any>', C:\bot\slave\auto-win-msvc-32-opt\build\src\librustc\session/mod.rs:201
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    hash::BuildHasherDefault_0

test result: FAILED. 1074 passed; 1 failed; 12 ignored; 0 measured
```

2016-12-19 08:01 UTC, frewsxcv commented
@bors retry

2016-12-19 08:01 UTC, frewsxcv commented
@bors r=GuillaumeGomez

2016-12-19 08:01 UTC, frewsxcv commented
@GuillaumeGomez The error you pasted isn't for my latest commit.

2016-12-20 18:41 UTC, alexcrichton commented
@bors: r=GuillaumeGomez

2016-12-20 18:42 UTC, alexcrichton commented
Hm bors doesn't seem to want to move this out of the failed state. I'm going to close and reopen to see if that works.

2016-12-20 18:42 UTC, alexcrichton commented
@bors: r+

2016-12-20 18:43 UTC, alexcrichton commented
@frewsxcv looks like bors is getting confused here unfortunately. Want to `commit --amend` and force push the most recent commit to generate a new commit sha? I think that'll kick bors into seeing something different and re-approving.

2016-12-20 18:45 UTC, frewsxcv commented
Done.

2016-12-20 18:45 UTC, alexcrichton commented
@bors: r+

2016-12-20 18:46 UTC, alexcrichton commented
Looks like that did the trick!

2016-12-21 02:48 UTC, merged