incr.comp.: Avoid creating an edge to DepNode::Krate when generating debuginfo namespaces.
rust-lang/rust pull request #38243
Opened 2016-12-08 18:14 UTC by michaelwoerister

r? @nikomatsakis

2016-12-09 15:20 UTC, nikomatsakis requested changes

2016-12-09 15:20 UTC, nikomatsakis commented on src/librustc_trans/debuginfo/namespace.rs
> +            (ccx.tcx().crate_name(def_id.krate).as_str(), DUMMY_SP)
Hmm. I guess you decided that doing the refactoring to break out the `span` was too difficult? Seems like we could add a `ccx.tcx().map.crate_span()` helper that just ignores the read-edge easily enough as well, no?

2016-12-09 23:01 UTC, nikomatsakis commented on src/librustc_trans/debuginfo/namespace.rs
> +            (ccx.tcx().crate_name(def_id.krate).as_str(), DUMMY_SP)
Well I would point it at `DepNode::Hir(CRATE_DEF_ID)`, I think.

Note that DepNode::Krate and the Hir node for the crate def-id are distinct nodes.

2016-12-12 17:21 UTC, nikomatsakis commented
@bors r+

2016-12-12 17:23 UTC, michaelwoerister commented
Pushed a cleaner fix for this. Reading a the crate's span or attribute will now add an edge to `DepNode::Hir(CRATE_DEF_INDEX)` instead of to the all encompassing `DepNode::Krate`.

2016-12-12 20:25 UTC, merged