Advertise Vec in LinkedList docs
rust-lang/rust pull request #38297
Opened 2016-12-11 11:26 UTC by matklad

r? @steveklabnik 

Hi! We already [advise](https://doc.rust-lang.org/std/collections/#use-a-linkedlist-when) to use `Vec` instead of `LinkedList` in the top-level collections documentation. But I think it may be missed by someone who just directly finds `LinkedList`.

What do you feel about advertising `Vec` directly in `LinkedList` docs as well?

2016-12-11 19:03 UTC, matklad commented
Question: how should I cross-link the docs? Relative paths won't work for `LinkedList` structure, because it is visible as both `collections::LinkedList` and `collections::linked_list::LinkedList`.

2016-12-12 19:11 UTC, steveklabnik commented
> Question: how should I cross-link the docs?

This is one area where we can't 😦

2016-12-13 11:21 UTC, ollie27 commented
You've hit #32130. The options are to leave the links out for now or add more exceptions to linkchecker [here](https://github.com/rust-lang/rust/blob/b1a2ab86dbd73b3bae979d4472b04ae3655f6b21/src/tools/linkchecker/main.rs#L125-L131).

2016-12-13 13:13 UTC, GuillaumeGomez requested changes

2016-12-13 13:13 UTC, GuillaumeGomez commented on src/libcollections/linked_list.rs
> +//! [`VecDeque`](./vec_deque/struct.VecDeque.html) instead of `LinkedList`.
Since this is a module-level doc comment, I guess `LinkedList` should have an url.

2016-12-13 13:13 UTC, GuillaumeGomez commented on src/libcollections/linked_list.rs
> +/// Almost always it is better to use [`Vec`](../vec/struct.Vec.html) or
We don't use this linking syntax, we use:

```
text long text etc [link] blabla
blablabla

[link]: url
```

2016-12-13 13:13 UTC, GuillaumeGomez commented on src/libcollections/linked_list.rs
> +/// [`VecDeque`](./vec_deque/struct.VecDeque.html) instead of `LinkedList`.
Same comment.

2016-12-13 13:13 UTC, GuillaumeGomez commented on src/libcollections/linked_list.rs
> +//! [`VecDeque`](./vec_deque/struct.VecDeque.html) instead of `LinkedList`.
Same comment.

2016-12-13 13:13 UTC, GuillaumeGomez commented on src/libcollections/linked_list.rs
> +//! Almost always it is better to use [`Vec`](../vec/struct.Vec.html) or
Same comment.

2016-12-14 12:27 UTC, matklad commented
So let's use links in the module docs, because they always work, and let's avoid links on the struct directly, because it is reexported.

2016-12-14 17:02 UTC, GuillaumeGomez commented
```
std/collections/linked_list/index.html:57: broken link - std/collections/linked_list/struct.LinkedList
collections/linked_list/index.html:56: broken link - vec/struct.Vec.html
collections/linked_list/index.html:57: broken link - collections/linked_list/struct.LinkedList
```

2016-12-16 20:10 UTC, matklad commented
Linking to `Vec` is also impossible, because there are `collections` and `std::collections`. Should be good now?

2016-12-16 21:57 UTC, GuillaumeGomez commented on src/libcollections/linked_list.rs
> +/// Almost always it is better to use `Vec` or `VecDeque` instead of
Why not linking to VecDeque here? You did it just above.

2016-12-20 10:26 UTC, matklad commented
@GuillaumeGomez anything else to clean up here?

2016-12-21 16:41 UTC, GuillaumeGomez approved these changes

2016-12-21 16:41 UTC, GuillaumeGomez commented
Nothing, thanks!

@bors: r+ rollup

2016-12-22 21:39 UTC, steveklabnik commented
@bors: retry

2016-12-25 00:36 UTC, merged