Remove build.rs from trans
rust-lang/rust pull request #38302
Opened 2016-12-11 17:42 UTC by Mark-Simulacrum

As a drive-by fix, this makes `drop_in_place` run other destructors in the same function, which it didn't before.

Potentially fixes #35566, but I don't have a windows machine to test it on. (cc @petrochenkov)

We make debuginfo location tracking local, instead of global. There is now only one API in trans which builds LLVM IR, which is the functions on Builder.

This also made a few details about debug info more obvious, but these are out of scope for this PR:
 - `CustomScope` from cleanup always has `debug_loc = DebugLoc::None`
 - `debuginfo/source_loc::set_source_location`:
   - `FunctionDebugContext.source_location_override` is always false.
   - It's possible the code in general in this area can be cleaned up....

r? @eddyb

2016-12-11 18:14 UTC, arielb1 commented
Nice! You don't have to wait for my shim-MIR PR - I can handle that.

2016-12-11 19:09 UTC, rkruppe commented on src/librustc_trans/adt.rs
> +    trans_field_ptr_builder(bcx, t, val, discr, ix)
IIUC this function is redundant now. Is cleaning that up in scope for this PR?

2016-12-11 19:10 UTC, nagisa commented
I will want to look over the PR later.

2016-12-11 19:11 UTC, eddyb requested changes
Great work! Most of changes I have in mind are further cleanup (fully removing the global builder and its debuginfo machinery, `_builder` fn variants, `Block` etc.).

2016-12-11 19:11 UTC, eddyb commented on src/librustc_trans/mir/block.rs
> +                    let ptr =  self.trans_operand(&bcx, &args[0]);
Extraneous space after `=`.

2016-12-11 19:11 UTC, eddyb commented on src/librustc_trans/mir/operand.rs
> +                                bcx: &BlockAndBuilder<'bcx, 'tcx>,
Rename this function to `store_operand`.

2016-12-11 19:11 UTC, eddyb commented on src/librustc_trans/mir/rvalue.rs
> +                let val = base::malloc_raw_dyn(&bcx, llty_ptr, box_ty, llsize, llalign);
Is this the only call? Because then you could inline it.

2016-12-11 19:11 UTC, eddyb commented on src/librustc_trans/tvec.rs
> +    // closure doesn't compile due to body_bcx still being borrowed when dropped.
Is this due to over-zealous inference 😞?

2016-12-11 19:12 UTC, eddyb commented on src/librustc_trans/adt.rs
> +    trans_field_ptr_builder(bcx, t, val, discr, ix)
Yeah, I also commented on it, there's a bunch like this.

2016-12-11 19:37 UTC, est31 commented
Let me test whether this fixes issue `35566`...

2016-12-11 20:11 UTC, est31 commented
Nope, #35566 is still not fixed.

2016-12-11 20:29 UTC, eddyb commented
Update: looks like @est31 was hitting the bug at stage0, which ofc is not fixed. I've suggested a manual way to test that the bug is indeed fixed at stage1 and later.

2016-12-11 22:16 UTC, est31 commented
Now it fails when compiling stage1 std artifacts:

```
Basic Block in function '_ZN4core3num7flt2dec15to_shortest_str17hd586f26308963365E' does not have terminator!
label %bb1
LLVM ERROR: Broken function found, compilation aborted!
Build failed, waiting for other jobs to finish...
error: Could not compile `core`.

To learn more, run the command again with --verbose.
```

2016-12-11 22:24 UTC, bluss commented on src/librustc/middle/lang_items.rs
> +    // on `malloc_raw_dyn` in librustc_trans/base.rs.
Good to put this into liballoc. Is this a new requirement, or just a new comment? Since we know the discussion about panic on oom will come back.

2016-12-12 16:15 UTC, bluss commented
About the drop_in_place change, is this an example of a program that changes behaviour? Just to understand. Current stable/beta/nightly doesn't run the "B" drop after the panic of "A".

[playground](https://is.gd/lTDoCC)
```rust
struct PrintDrop(&'static str);

impl Drop for PrintDrop {
    fn drop(&mut self) {
        println!("Dropping {}", self.0);
        if self.0 == "A" {
            panic!();
        }
    }
}

use std::mem::forget;
use std::ptr::drop_in_place;

fn main() {
    let mut x = (PrintDrop("A"), PrintDrop("B"));
    unsafe {
        drop_in_place(&mut x);
        forget(x);
    }
}
```

2016-12-12 16:45 UTC, Mark-Simulacrum commented
The example @eddyb gave me for the `drop_in_place` change: https://is.gd/i42PKb vs https://is.gd/UfTJjA. The first one panics only once because it uses drop_in_place, while the second panics twice, since it doesn't utilize drop_in_place. I believe your example is equivalent to this, though.

2016-12-12 19:40 UTC, nagisa commented on src/librustc/middle/lang_items.rs
> +    // on `malloc_raw_dyn` in librustc_trans/base.rs.
You can simply change how MIR for allocation is generated. No need to fiddle in trans, unless there’s some old cruft in old trans that still generates calls to this itself… in which case you’ll have a hard and bad time fixing this :)

2016-12-16 17:36 UTC, eddyb requested changes

2016-12-16 17:36 UTC, eddyb commented on src/librustc_trans/common.rs
> +    owned_builder: OwnedBuilder<'a, 'tcx>,
You should probably name this `alloca_builder`.

2016-12-16 17:36 UTC, eddyb commented on src/librustc_trans/common.rs
>      pub funclet_arena: TypedArena<Funclet>,
Still need to kill this.

2016-12-16 17:36 UTC, eddyb commented on src/librustc_trans/common.rs
> +            llvm::LLVMGetFirstInstruction(entry_bcx.llbb())
I don't think the `LLVMGetFirstInstruction` call is needed and you can just the result of the `.load(...)`.

2016-12-16 17:36 UTC, eddyb commented on src/librustc_trans/common.rs
> +        if !self.fn_ty.ret.is_ignore() && !skip_retptr {
Oh this is weird, I wonder if this should maybe be inlined.

2016-12-16 17:36 UTC, eddyb commented on src/librustc_trans/common.rs
> +                self.alloca(llty, "sret_slot")
`llty` can be computed on this branch alone. Which IMO should not exist anymore.

2016-12-16 17:36 UTC, eddyb commented on src/librustc_trans/common.rs
> +        self.owned_builder.builder.alloca(ty, name)
Should rename the method on `Builder` to `dynamic_alloca` or something.

2016-12-16 17:36 UTC, eddyb commented on src/librustc_trans/context.rs
>          self.local().builder.b
Looks like the underlying builder is not exactly gone.

2016-12-16 17:36 UTC, eddyb commented on src/librustc_trans/common.rs
> +            param_env: ccx.tcx().empty_parameter_environment(),
Is this used at all anymore?

2016-12-16 17:36 UTC, eddyb commented on src/librustc_trans/common.rs
> +            span: None,
... or this?

2016-12-16 17:37 UTC, eddyb commented on src/librustc_trans/context.rs
>          self.local().builder.b
Also `OwnedBuilder` should be the only `Builder`, i.e. the latter should not be a distinct type.

2016-12-16 20:38 UTC, Mark-Simulacrum commented on src/librustc_trans/common.rs
> +            llvm::LLVMGetFirstInstruction(entry_bcx.llbb())
The load returns the `ValueRef` for the first instruction?

2016-12-16 23:51 UTC, eddyb commented on src/librustc_trans/common.rs
> +        fcx.alloca_insert_pt = Some(val);
Can you avoid having two variables named `val`, i.e. can you move this up a bit more? Maybe rename it to `dummy`.

2016-12-17 19:25 UTC, eddyb commented on src/librustc_trans/debuginfo/create_scope_map.rs
> +    mir: Ref<'tcx, Mir<'tcx>>,
Can this be a regular reference?

2016-12-17 19:28 UTC, eddyb commented on src/librustc_trans/mir/mod.rs
> +    mir: Ref<'tcx, Mir<'tcx>>
Can *this* get away with being a reference?

2016-12-18 03:10 UTC, eddyb commented on src/librustc_trans/mir/block.rs
> +                            bcx.set_source_location(scope, debug_span);
Needs to be `ret_bcx.set_source_location(...)`.

2016-12-18 03:10 UTC, eddyb commented on src/librustc_trans/mir/block.rs
> +        let bcx = self.build_block(bb);
This function can probably just iterate over `cleanup_kinds` to produce `funclets`, without the RPO visit order (as `CleanupKind::Internal` doesn't need to reference a different `functlets` entry).

2016-12-18 03:10 UTC, eddyb commented on src/librustc_trans/mir/mod.rs
>      for (bb, _) in rpo.by_ref() {
This is what I mean, the order is irrelevant here now.

2016-12-18 03:10 UTC, eddyb commented on src/librustc_trans/tvec.rs
> +    body_bcx.add_incoming_to_phi(current, next, body_bcx.llbb());
This is mildly confusing, heh, it'd make more sense as `header_bcx.add_incoming_to_phi(...)`.

2016-12-18 17:24 UTC, Mark-Simulacrum commented on src/librustc_trans/debuginfo/mod.rs
>      FunctionWithoutDebugInfo,
It is possible, because of https://github.com/rust-lang/rust/issues/29721, which hasn't yet been removed, though it is deprecated.

2016-12-19 03:01 UTC, eddyb commented on src/librustc_trans/debuginfo/source_loc.rs
> +    set_debug_location(mir.ccx(), builder, dbg_loc);
FWIW, here and a few times above, `builder` has a `ccx` of its own. `trans::debuginfo` should maybe take just `debug_context`, not the whole `mir` context.

2016-12-19 03:05 UTC, eddyb commented on src/librustc_trans/mir/mod.rs
> +    pub debug_context: debuginfo::FunctionDebugContext,
Yeah I'd rather these not be made public.

2016-12-19 03:07 UTC, eddyb commented on src/librustc_trans/mir/mod.rs
> +        fcx.ccx.sess().cstore.item_attrs(def_id).iter().any(|item| item.check_name("no_debug"))
This is silly, `tcx` has a method to get attributes which should work regardless of local/non-local. I think.

2016-12-19 03:07 UTC, eddyb commented on src/librustc_trans/mir/mod.rs
> +        debuginfo::create_function_debug_context(fcx.ccx, instance, sig, abi, fcx.llfn, mir)
That attribute check should actually almost surely be done inside this function.

2016-12-19 03:10 UTC, eddyb commented on src/librustc_trans/context.rs
> +            param_env: tcx.empty_parameter_environment(),
This should be named `empty_param_env`.

2016-12-19 03:11 UTC, eddyb commented on src/librustc_trans/mir/analyze.rs
>      bcx: &'mir BlockAndBuilder<'a, 'tcx>,
Please rename `mir` to `cx` - as for `bcx`, is it even needed anymore?

2016-12-19 03:13 UTC, eddyb commented on src/librustc_trans/common.rs
>          fcx.alloca_insert_pt = Some(val);
The block dance above this isn't really needed.

2016-12-19 20:35 UTC, eddyb commented on src/librustc_trans/mir/statement.rs
> +        debuginfo::set_source_location(&self.debug_context, &bcx, scope, span);
Maybe this pair should be combined into `self.set_debug_loc(&bcx, statement.source_info);`?

2016-12-19 20:39 UTC, eddyb commented on src/librustc_trans/mir/mod.rs
> +                bcx.set_personality_fn(fcx.eh_personality());
We discussed that this is unnecessary given that it happens for a `Funclet` and an `Internal` depends on a `Funclet` existing. Also, that we should always call `set_personality_fn` for `CleanupKind::Funclet`, even on non-MSVC (allowing the removal of all other `set_personality_fn` calls from MIR trans).

2016-12-19 20:40 UTC, eddyb commented on src/librustc_trans/mir/mod.rs
> +                Funclet::msvc(bcx.cleanup_pad(None, &[]))
Maybe the `gnu` vs `msvc` constructors for `Funclet` should be abolished, `Some`/`None` is more readable IMO.

2016-12-19 20:50 UTC, Mark-Simulacrum commented on src/librustc_trans/mir/statement.rs
> +        debuginfo::set_source_location(&self.debug_context, &bcx, scope, span);
We use `debug_loc` in `mir/block.rs` and use the returned span for other purposes (namely, passing to `trans_intrinsic_call`) than setting debug location, so this won't quite work.

2016-12-19 20:52 UTC, eddyb commented on src/librustc_trans/mir/statement.rs
> +        debuginfo::set_source_location(&self.debug_context, &bcx, scope, span);
The span is `terminator.source_info.span` FWIW.

2016-12-19 21:13 UTC, Mark-Simulacrum commented
It's hard for me to tell where we can remove set_personality_fn, but here's a list of the current places. Feel free to point out which ones can be removed:
```
cleanup.rs:170:21:            pad_bcx.set_personality_fn(llpersonality);
intrinsic.rs:721:13:        bcx.set_personality_fn(bcx.fcx().eh_personality());
mir/mod.rs:309:21:                bcx.set_personality_fn(fcx.eh_personality());
```

2016-12-19 22:09 UTC, eddyb commented on src/librustc_trans/mir/mod.rs
> +            let bcx = mircx.build_block(bb);
This should be inside the `if`, also, where did the `set_personality_fn` go?

2016-12-19 22:55 UTC, eddyb commented on src/librustc_trans/base.rs
> +            let retval = if llty == Type::i1(fcx.ccx) {
This still needs to be removed. Also, I wonder if `abi::ArgTy` has any method to do this sort of thing to get you the value that you can pass to `bcx.ret` (`fn_ty.ret_ty` is an `ArgTy`).

2016-12-19 23:11 UTC, eddyb commented on src/librustc_trans/callee.rs
> +    let first_llarg = if fn_ty.ret.is_indirect() && !fcx.fn_ty.ret.is_ignore() {
This applies to other such calls elsewhere AFAIK.

2016-12-19 23:12 UTC, eddyb commented on src/librustc_trans/callee.rs
> +        .collect::<Vec<_>>();
You should have mutated `llargs` above like you do in other shims.

2016-12-19 23:17 UTC, eddyb commented on src/librustc_trans/callee.rs
> +    if fn_ty.ret.is_indirect() || fcx.fn_ty.ret.is_ignore() {
Same `fn_ty` syntactical mismatch (I'm almost certain `fcx.fn_ty` need not even be computed). Also the unreachable thing above.

2016-12-19 23:28 UTC, eddyb commented on src/librustc_trans/cleanup.rs
> +    fn branch(&self, bcx: &BlockAndBuilder, to_llbb: BasicBlockRef) {
Can this be inlined?

2016-12-19 23:28 UTC, eddyb commented on src/librustc_trans/cleanup.rs
> +            (UnwindKind::CleanupPad(..), UnwindKind::CleanupPad(..)) => true,
This is a weird implementation, is it ever used?

2016-12-19 23:29 UTC, eddyb commented on src/librustc_trans/cleanup.rs
> +                Some(CleanupScope::get_landing_pad(fcx, &drop_val))
`get_landing_pad` should be a method on `DropValue`.

2016-12-19 23:31 UTC, eddyb commented on src/librustc_trans/cleanup.rs
> +        return pad_bcx.llbb();
Explicit `return`.

2016-12-19 23:33 UTC, eddyb commented on src/librustc_trans/common.rs
> +        self.fcx.ccx.sess()
All of these should probably use `self.ccx` anyway and `fn ccx` above can be removed.

2016-12-19 23:43 UTC, eddyb commented on src/librustc_trans/glue.rs
> +    assert!(!fn_ty.ret.is_indirect() && fn_ty.ret.cast.is_none());
This is unnecessary, we know the signature.

2016-12-20 00:07 UTC, eddyb commented on src/librustc_trans/mir/mod.rs
> +    // If false, all funclets should be None (which is the default)
Comment is irrelevant anymore AFAICT.

2016-12-20 00:52 UTC, eddyb commented on src/librustc_trans/mir/rvalue.rs
> +                    self.store_operand(&bcx, llslot, tr_elem);
Shouldn't this receive a reference to the `bcx`? Or require returning it, if it's by-value.

2016-12-20 02:53 UTC, eddyb commented on src/librustc_trans/context.rs
> +                    return llpersonality
Shouldn't this cache wrap around the whole function?

2016-12-20 05:02 UTC, eddyb approved these changes

2016-12-20 05:02 UTC, eddyb commented
@bors r+

2016-12-20 05:25 UTC, est31 commented
I confirm that commit 60d3df3d32c13e8cdd900885c3a586131fde157a fixes issue  #35566 . Thanks!

2016-12-20 20:57 UTC, alexcrichton commented
When testing a [rollup](https://github.com/rust-lang/rust/pull/38499) I ended up getting this during a 64-bit MSVC compile in stage1:

```
CleanupPadInst not the first non-PHI instruction in the block.
  %cleanuppad1 = cleanuppad within none []
LLVM ERROR: Broken function found, compilation aborted!
Build failed, waiting for other jobs to finish...
error: Could not compile `alloc`.
```

@Mark-Simulacrum do you know if perhaps that's this PR? I'm just guessing, but this seemed likely at least.

2016-12-20 21:16 UTC, eddyb commented
@bors r+

2016-12-21 03:37 UTC, Mark-Simulacrum commented
Rebased.

2016-12-21 03:38 UTC, eddyb commented
@bors r+

2016-12-21 13:59 UTC, merged