Rustdoc: disambiguate Implementors when the type name is not unique
rust-lang/rust pull request #38414
Opened 2016-12-16 20:05 UTC by estebank

Presentation [goes from](https://doc.rust-lang.org/stable/std/iter/trait.ExactSizeIterator.html#implementors):

<img width="492" alt="" src="https://cloud.githubusercontent.com/assets/1606434/21276752/b2b50474-c387-11e6-96e1-9766851da269.png">

to:

<img width="787" alt="" src="https://cloud.githubusercontent.com/assets/1606434/21276763/bb37f6b0-c387-11e6-8596-9163cb254674.png">

on cases where there're multiple implementors with the same name.

Fixes #37762.

2016-12-16 20:05 UTC, rust-highfive commented
r? @steveklabnik

(rust_highfive has picked a reviewer for you, use r? to override)

2016-12-16 23:10 UTC, bluss commented
Ignore-whitespace diff: https://github.com/rust-lang/rust/pull/38414/files?w=1

2016-12-16 23:20 UTC, bluss commented on src/librustdoc/html/render.rs
> +                }
Is is quadratic (complexity) in the number of implementors, I don't think we can afford that. A trait like Clone only lists ~480 impls, but still.

2016-12-16 23:30 UTC, bluss commented on src/librustdoc/html/render.rs
> +                }
Unless I'm missing something, you can change `last_name()` to return `&str` and create a `BtreeMap<&str, usize>` or something to count everything's duplicitly here.

2016-12-19 22:13 UTC, bluss commented
Can you apply this diff? Then it uses &str instead, and counts the right implementors. I wrote this up to make sure that it was possible (to not make suggestions that can't be).

```diff
diff --git a/src/librustdoc/clean/mod.rs b/src/librustdoc/clean/mod.rs
index 28ca92f..a99d4dd 100644
--- a/src/librustdoc/clean/mod.rs
+++ b/src/librustdoc/clean/mod.rs
@@ -2205,8 +2205,8 @@ impl Path {
         }
     }
 
-    pub fn last_name(&self) -> String {
-        self.segments.last().unwrap().name.clone()
+    pub fn last_name(&self) -> &str {
+        &self.segments.last().unwrap().name
     }
 }
 
diff --git a/src/librustdoc/html/render.rs b/src/librustdoc/html/render.rs
index 846c072..5839c46 100644
--- a/src/librustdoc/html/render.rs
+++ b/src/librustdoc/html/render.rs
@@ -2110,23 +2110,22 @@ fn item_trait(w: &mut fmt::Formatter, cx: &Context, it: &clean::Item,
         <h2 id='implementors'>Implementors</h2>
         <ul class='item-list' id='implementors-list'>
     ")?;
-    let mut implementor_count: FxHashMap<String, usize> = FxHashMap();
-    for (_, implementors) in cache.implementors.iter() {
+    if let Some(implementors) = cache.implementors.get(&it.def_id) {
+        let mut implementor_count: FxHashMap<&str, usize> = FxHashMap();
         for implementor in implementors {
             if let clean::Type::ResolvedPath {ref path, ..} = implementor.impl_.for_ {
                 *implementor_count.entry(path.last_name()).or_insert(0) += 1;
             }
         }
-    }
-    if let Some(implementors) = cache.implementors.get(&it.def_id) {
-        for implementor in implementors.iter() {
+
+        for implementor in implementors {
             write!(w, "<li><code>")?;
             // If there's already another implementor that has the same abbridged name, use the
             // full path, for example in `std::iter::ExactSizeIterator`
             let dissambiguate = if let clean::Type::ResolvedPath {
                 ref path, ..
             } = implementor.impl_.for_ {
-                *implementor_count.get(&path.last_name()).unwrap_or(&0) > 1
+                implementor_count[path.last_name()] > 1
             } else {
                 false
             };

```

2016-12-22 08:35 UTC, estebank commented
@bluss applied 👍

2016-12-22 11:08 UTC, bluss requested changes
Thanks, we can integrate, let's just clean up that bool parameter's name to be consistent across the patch.

2016-12-22 11:08 UTC, bluss commented on src/librustdoc/html/format.rs
> +                 print_all: bool, use_absolute: bool) -> fmt::Result {
Can you go through the patch and use the same name for this parameter everywhere (the `use_absolute` here)? That's one step that makes a bool parameter more bearable.

2016-12-22 11:08 UTC, bluss commented on src/librustdoc/html/format.rs
> +fn fmt_type(t: &clean::Type, f: &mut fmt::Formatter, full_path: bool) -> fmt::Result {
This parameter is the same (`full_path`), so this and in other places.

2016-12-22 11:08 UTC, bluss commented on src/librustdoc/html/render.rs
> +            let dissambiguate = if let clean::Type::ResolvedPath {
Extra `s` in the spelling here. It's another of the ones that should have the same name across the patch, though.

2016-12-22 21:41 UTC, steveklabnik commented
/cc @rust-lang/tools

2016-12-23 11:35 UTC, bluss approved these changes

2017-01-03 16:17 UTC, steveklabnik commented
@bors: r+

thanks!

2017-01-04 16:03 UTC, GuillaumeGomez commented
Excellent, thanks a lot for this!

2017-01-04 16:22 UTC, japaric commented
@bors r=steveklabnik

2017-01-04 16:24 UTC, bluss commented
@bors r=steveklabnik

2017-01-04 19:26 UTC, merged