Replace 'stupid' with 'nonsensical' in nomicon.
rust-lang/rust pull request #38782
Opened 2017-01-02 20:50 UTC by clarcharr

Originally: "So it's perfectly "fine" for a Safe Rust program to get deadlocked or do something incredibly stupid with incorrect synchronization."

Changed to: "So it's perfectly "fine" for a Safe Rust program to get deadlocked or do something nonsensical with incorrect synchronization."

2017-01-02 20:50 UTC, rust-highfive commented
r? @steveklabnik

(rust_highfive has picked a reviewer for you, use r? to override)

2017-01-02 21:17 UTC, steveklabnik requested changes
Happy to r+ this but the vendored changes need backed out, thanks!

2017-01-02 21:17 UTC, steveklabnik commented on src/vendor/libc/ci/README.md
> +over all the capabilities QEMU has and the various flavors in which we use it!
this change can't work; this is a vendored copy of the https://github.com/rust-lang/libc crate, and would need to be fixed there, that's why CI is failing.

2017-01-02 21:17 UTC, steveklabnik commented on src/vendor/libc/ci/run.sh
> +  # syntex_syntax in QEMU would time out basically everywhere.
same here

2017-01-02 21:29 UTC, clarcharr commented
Ah, I tried to avoid searching through the submodules and I guess that I missed some. Removed the vendor changes and rebased.

2017-01-02 22:51 UTC, clarcharr commented on src/vendor/libc/ci/run.sh
> +  # syntex_syntax in QEMU would time out basically everywhere.
fixed!

2017-01-02 22:51 UTC, clarcharr commented on src/vendor/libc/ci/README.md
> +over all the capabilities QEMU has and the various flavors in which we use it!
also fixed!

2017-01-02 23:10 UTC, GuillaumeGomez commented
Thanks!

@bors: r+ rollup

2017-01-03 00:28 UTC, nagisa commented
Failure is irrelevant.

2017-01-03 02:20 UTC, steveklabnik commented
@bors: retry

2017-01-03 04:23 UTC, merged