Make tidy check for lang gate tests
rust-lang/rust pull request #38914
Opened 2017-01-08 03:09 UTC by est31

Add gate tests to the checks that tidy performs. Excerpt from the commit message of the main commit:

    Require compile-fail tests for new lang features

    Its non trivial to test lang feature gates, and people
    forget to add such tests. So we extend the features lint
    of the tidy tool to ensure that all new lang features
    contain a new compile-fail test.
    
    Of course, one could drop this requirement and just
    grep all tests in run-pass for #![feature(abc)] and
    then run this test again, removing the mention,
    requiring that it fails.
    
    But this only tests for the existence of a compilation
    failure. Manual tests ensure that also the correct lines
    spawn the error, and also test the actual error message.
    
    For library features, it makes no sense to require such
    a test, as here code is used that is generic for all
    library features.

To give an example for usage, I have included a commit that adds "gate-test-" lines to four tests in the compile-fail suite. If/once the general approach of this PR gets positive feedback, I offer to extend this commit to a full list of already existing gate tests.

Right now, the commit adds a number of expected features that don't have a test yet.
The idea is that this number should only be made smaller during later changes and one day, once its zero, we can closethe issue: #22820. (space omitted in previous sentence to prevent github from closing it prematurely).

cc @brson , @pnkfelix (they both discussed about this in the issue linked above).

2017-01-08 03:09 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2017-01-10 18:23 UTC, nikomatsakis approved these changes

2017-01-10 18:23 UTC, nikomatsakis commented on src/tools/tidy/src/features.rs
> +    let gate_untested_expected = 94;
Maybe we can open up a follow-up issue with a list of each of these tests and try to distribute the work.

2017-01-10 18:23 UTC, nikomatsakis commented
@bors r+

2017-01-10 18:24 UTC, nikomatsakis commented
@bors r-

2017-01-10 18:25 UTC, nikomatsakis commented
Actually, one thing -- I think we should edit [COMPILER_TESTS.md](https://github.com/rust-lang/rust/blob/master/COMPILER_TESTS.md) to document what is expected. It'd be nice if the error message also directed the user at some instructions on how to fix (or directly gave those instructions).

2017-01-10 18:26 UTC, nikomatsakis commented on src/tools/tidy/src/features.rs
> +            println!("Did you forget to add a gate test for your new feature?");
Also, I think we should make the "expected" list be a hash set or something. This way we can actually print out the  *names* of the features here, along with some directions like "make a test with a `// gate-test-foo` comment"

2017-01-10 18:26 UTC, nikomatsakis requested changes
I think the idea is very good but I feel like the experience of getting a tidy error here will be kind of annoying. With a bit more effort we can help direct people as to what they have to do.

2017-01-10 20:30 UTC, est31 commented on src/tools/tidy/src/features.rs
> +    let gate_untested_expected = 94;
Sure, good idea! Most of the features already have gate tests (see issue #22820 for an outdated list). If the general direction of this issue is agreed upon, I volunteer to add `// gate-test-` comments to the already existing tests (that I can find), and for the small remaining number we can open a tracking issue. Probably a good thing to ask contributions for from first time contributors (like the error message refactoring).

2017-01-10 20:31 UTC, est31 commented on src/tools/tidy/src/features.rs
> +            println!("Did you forget to add a gate test for your new feature?");
This is not the aspired end state. I'm sure most features already have gate tests, there should only be very few without one. And once we have all features gate tested, so `gate_untested_expected` is zero, we can change this code to print the ungated features in the error message.

2017-01-10 20:33 UTC, est31 commented
> I feel like the experience of getting a tidy error here will be kind of annoying

See my reply above. The tidy error will be improved once the list is complete.

2017-01-10 22:06 UTC, nikomatsakis commented
@est31 

> The tidy error will/can be improved once the list is complete.

Hmm. That seems potentially OK, but I am concerned we will stall in this interim state for some time. =)

2017-01-11 01:37 UTC, est31 commented
Okay, updated, and docs added.

I've now added a whitelist of currently 20 features for which I couldn't find gate tests.

They either don't have a test, or are already removed, but feature_gate.rs didn't get updated,
or other issues. Once the PR is merged I'd like to open a tracking issue with the different categories the tests fall into.

Thanks to the whitelist, we can now fail with messages like:

```
Expected a gate test for the feature 'type_ascription'.
Hint: create a file named 'feature-gate-type_ascription.rs' in the compile-fail
      test suite, with its failures due to missing usage of
      #![feature(type_ascription)].
Hint: If you already have such a test and don't want to rename it,
      you can also add a // gate-test-type_ascription line to the test file.
Found 1 features without a gate test.
```

2017-01-11 01:38 UTC, est31 commented
r? @nikomatsakis

2017-01-11 01:52 UTC, est31 commented
Oh sorry, forgot to push. Now it should be okay. r? @nikomatsakis

2017-01-11 03:02 UTC, est31 commented
Updated PR description.

2017-01-11 16:47 UTC, nikomatsakis commented on src/tools/tidy/src/features.rs
> +                                .filter(|&(n, _)| !whitelist.contains(&n.as_str()))
I'm happy to land it as is, but I have a mild concern that people will add tests for something in the whitelist, but forget to remove it from the whitelist. Either we have to be vigilant, or we could tweak this code such that if it is in the whitelist, we error out if it is found to be tested.

2017-01-11 16:47 UTC, nikomatsakis approved these changes

2017-01-11 16:47 UTC, nikomatsakis commented
@bors r+

2017-01-11 16:48 UTC, nikomatsakis commented
I'll enqueue it for now, can always submit a follow-up PR if you think it's worth tweaking it.

2017-01-12 22:56 UTC, est31 commented
As #38814 got merged, I had to rebase and mark the test it added. re-r? @nikomatsakis

2017-01-13 17:42 UTC, nikomatsakis commented
@bors r+

2017-01-14 08:48 UTC, merged