Improve safety warning on ptr::swap
rust-lang/rust pull request #38910
Opened 2017-01-07 18:41 UTC by steveklabnik

r? @eddby @bluss , who I asked about this on IRC

2017-01-07 18:46 UTC, GuillaumeGomez requested changes

2017-01-07 18:46 UTC, GuillaumeGomez commented on src/libcore/ptr.rs
> +/// as arguments, which means they will be dereferenced.
I don't think the warning is clear enough. I'd state something like:

"If the pointer is null or points to invalid data, the program will crash or have an undefined behaviour."

It seems very important to me to indicate the consequences.

2017-01-07 18:46 UTC, steveklabnik commented on src/libcore/ptr.rs
> +/// as arguments, which means they will be dereferenced.
This is already defined at the language level; repeating it here feels extraneous.

2017-01-07 19:17 UTC, bluss commented on src/libcore/ptr.rs
> +/// as arguments, which means they will be dereferenced.
To say that it reads and writes through the raw pointers should be enough.

2017-01-07 19:35 UTC, steveklabnik commented
@bluss updated

2017-01-07 20:41 UTC, eddyb approved these changes
LGTM. r=me if @bluss is satisfied.

2017-01-07 20:42 UTC, bluss commented
@bors r=eddyb

2017-01-08 09:51 UTC, GuillaumeGomez approved these changes

2017-01-09 04:57 UTC, merged