Add missing links and examples for path modules and structs
rust-lang/rust pull request #38946
Opened 2017-01-09 21:43 UTC by GuillaumeGomez

r? @frewsxcv

2017-01-09 21:48 UTC, frewsxcv commented
Looks great! Thanks!

@bors r+ rollup

2017-01-10 11:15 UTC, sanxiyn requested changes

2017-01-10 11:15 UTC, sanxiyn commented on src/libstd/path.rs
> +//! This module provides two types, [`PathBuf`] and [`Path`] (akin to [`String`] and
`[Path] (akin to...)` seems to be interpreted as a Markdown link, causing Travis failure in linkcheck.

2017-01-10 11:16 UTC, sanxiyn commented
@bors r-

2017-01-10 12:56 UTC, GuillaumeGomez commented on src/libstd/path.rs
> +//! This module provides two types, [`PathBuf`] and [`Path`] (akin to [`String`] and
Well found!

2017-01-10 12:58 UTC, GuillaumeGomez commented
Updated.

2017-01-10 13:41 UTC, frewsxcv requested changes

2017-01-10 13:41 UTC, frewsxcv commented on src/libstd/path.rs
> +    /// use std::path::{Path, PathBuf};
Unused import: `PathBuf`

2017-01-10 13:41 UTC, frewsxcv commented on src/libstd/path.rs
> +    /// use std::path::{Path, PathBuf};
Unused import: `PathBuf`

2017-01-11 10:14 UTC, GuillaumeGomez commented
Updated.

2017-01-11 14:58 UTC, frewsxcv commented on src/libstd/path.rs
> +    /// assert_eq!(path.canonicalize().unwrap(), PathBuf::from("/foo/test/bar.rs"));
Missing import `PathBuf`

2017-01-11 19:08 UTC, GuillaumeGomez commented on src/libstd/path.rs
> +    /// assert_eq!(path.canonicalize().unwrap(), PathBuf::from("/foo/test/bar.rs"));
Oh damn, we'll never end it haha.

2017-01-11 22:27 UTC, GuillaumeGomez commented on src/libstd/path.rs
> +    /// use std::path::{Path, PathBuf};
It is used.

2017-01-11 22:27 UTC, GuillaumeGomez commented on src/libstd/path.rs
> +    /// use std::path::{Path, PathBuf};
(certainly github bug actually)

2017-01-11 22:28 UTC, GuillaumeGomez commented
Updated.

2017-01-12 01:21 UTC, frewsxcv commented
@bors r+ rollup

2017-01-12 02:51 UTC, sanxiyn approved these changes

2017-01-14 02:02 UTC, merged