[WIP] Add peek APIs to std::net::UdpSocket
rust-lang/rust pull request #38983
Opened 2017-01-11 03:26 UTC by APTy

### peek

TODO:
- use `MSG_PEEK` const from libc where possible
- more tests
- do we actually need definitions in `sys::redox` and `sys::unix::ext`?

Part 1 for #38980

2017-01-11 03:26 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @aturon (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-01-11 18:31 UTC, aturon commented
cc @rust-lang/libs, new proposed unstable APIs for UDP.

2017-01-11 23:44 UTC, alexcrichton reviewed
For consistency should we also be sure to add this to the TCP streams as well?

2017-01-11 23:44 UTC, alexcrichton commented on src/libstd/sys/windows/net.rs
> +const MSG_PEEK: c_int = 0x2;
Can this be added to the the `c` module with other windows bindings?

2017-01-11 23:44 UTC, alexcrichton commented on src/libstd/sys_common/net.rs
> +const MSG_PEEK: c_int = 0x2;
This seems duplicated with the Windows definition? If this is the unix definition can it be pulled from libc?

2017-01-11 23:44 UTC, alexcrichton commented on src/libstd/sys/windows/net.rs
> +        recv_with_flags(buf, 0)
This may need to be `self.recv_with_flags`

2017-01-11 23:44 UTC, alexcrichton commented on src/libstd/sys/unix/ext/net.rs
> +const MSG_PEEK: libc::c_int = 0x2;
Can this be pulled from the libc crate?

2017-01-11 23:44 UTC, alexcrichton commented on src/libstd/net/udp.rs
> +    /// whence the data came.
Could this documentation also elaborate on how this relates to `MSG_PEEK`?

2017-01-11 23:59 UTC, sfackler commented
Unix sockets as well.

2017-01-12 01:32 UTC, APTy commented on src/libstd/sys/windows/net.rs
> +const MSG_PEEK: c_int = 0x2;
yes, agree

2017-01-12 01:37 UTC, APTy commented on src/libstd/sys_common/net.rs
> +const MSG_PEEK: c_int = 0x2;
Yes, let's use libc if possible. I've added the flag only very recently in https://github.com/rust-lang/libc/pull/492. How is best to make this transition? Should we hold off on this PR until the next libc release?

2017-01-12 17:47 UTC, alexcrichton commented on src/libstd/sys_common/net.rs
> +const MSG_PEEK: c_int = 0x2;
Oh you can just update the submodule in the repository

2017-01-13 06:06 UTC, APTy commented
Removed the `sys/unix/ext` and `sys/redox` partial implementations, since they seem unnecessary at the moment, but let me know if you feel otherwise.

2017-01-31 16:48 UTC, aturon commented
Looks like a submodule update to liblibc got committed by accident.

2017-01-31 16:59 UTC, aturon requested changes
Just a few nits about docs and tests; otherwise LGTM. Sorry for the long delay in reviewing!

2017-01-31 16:59 UTC, aturon commented on src/libstd/net/tcp.rs
> +    /// Receives data on the socket from the remote adress to which it is
It'd be good to document the return value as well.

2017-01-31 16:59 UTC, aturon commented on src/libstd/net/tcp.rs
> +    /// assert_eq!(len, 10);
I'm confused by this assertion -- I'd expect there to be no bytes for peeking?

2017-01-31 16:59 UTC, aturon commented on src/libstd/net/tcp.rs
> +            assert_eq!(c.read(&mut b).unwrap(), 1);
It'd be good to test a peek after this call to `read`.

2017-01-31 16:59 UTC, aturon commented on src/libstd/net/udp.rs
> +    /// The `connect` method will connect this socket to a remote address. This
This bit about `connect` should maybe move to a dedicated "Errors" section. I'd also suggest swapping the order of sentences here.

2017-01-31 16:59 UTC, aturon commented on src/libstd/net/udp.rs
> +    /// Receives data on the socket from the remote adress to which it is
Docs should include info about the return value.

2017-01-31 23:09 UTC, APTy commented
@aturon thanks! The `liblibc` update is to take advantage of the `MSG_PEEK` flag platform bindings recently added. Will update tests/docs shortly!

2017-02-01 06:15 UTC, APTy commented on src/libstd/net/tcp.rs
> +    /// assert_eq!(len, 10);
ah yeah, this probably needs some tweaking

2017-02-03 01:30 UTC, sfackler commented
Is this good to go?

2017-02-03 16:55 UTC, aturon commented
@sfackler Not yet, one of the assertions in the doc comment needs fixing still.

2017-02-03 17:08 UTC, APTy commented
@aturon I simply removed the assertion, I don't think it added much value to the documentation anyway

2017-02-03 17:13 UTC, aturon approved these changes

2017-02-03 17:13 UTC, aturon commented
Thanks! Let's send it to bors.

@bors: r+

2017-02-04 19:30 UTC, alexcrichton commented
@APTy looks like the tests may be failing on Travis? Also, could you squash down the commits as well?

2017-02-04 19:36 UTC, APTy commented
:+1: Looking into the failure, will squash as well

2017-02-04 22:09 UTC, alexcrichton commented
@bors: r=aturon

2017-02-05 16:56 UTC, merged