Fix some typos in Nomicon
rust-lang/rust pull request #38994
Opened 2017-01-11 15:31 UTC by BenWiederhake

I waited a bit before creating this PR in case I find more typos – I didn't.

I've read `CONTRIBUTING.md` but didn't `make check`, and `make doc` takes incredibly long. (Among other things, `make doc` builds llvm from scratch.  Not sure if that's intentional.)

2017-01-11 15:31 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @steveklabnik (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-01-11 16:52 UTC, sanxiyn requested changes

2017-01-11 16:52 UTC, sanxiyn commented on src/doc/nomicon/unbounded-lifetimes.md
> +bind an unbounded lifetime as quickly as possible, especially across function
I think `bound` is correct here. cf. "If an output lifetime is elided, then it must be bounded by an input lifetime." below.

2017-01-11 17:14 UTC, BenWiederhake commented
Thanks, my fault, apparently I misread it three times >_<

I acknowledge that "squashing it in the end" is usually preferred, according to `#rust-beginners`, but here amending was more meaningful.  Yell if I'm wrong.

2017-01-11 18:20 UTC, BenWiederhake commented
Apparently this didn't trigger a new review request.  Anyway:  @sanxiyn: is this good?

2017-01-12 02:37 UTC, sanxiyn approved these changes

2017-01-12 02:38 UTC, sanxiyn commented
@bors r+ rollup

2017-01-14 02:02 UTC, merged