process trait/impl items directly from the visitor callback
rust-lang/rust pull request #39000
Opened 2017-01-11 20:50 UTC by nikomatsakis

The current setup processes impl/trait items while visiting
the impl/trait. This means we basically have this setup:

    <Lots> -> TypeckItemBody(Impl) -> Tables(ImplItem{0,1,2,3})

But this was largely an artifact of the older code. By moving the
processing of items into method dedicated for their use, we produce this
setup:

    <Little> -> TypeckItemBody(ImplItem0) -> Tables(ImplItem0)
    ...
    <Little> -> TypeckItemBody(ImplItem3) -> Tables(ImplItem3)

r? @michaelwoerister 

Also, we might consider removing the `TypeckItemBody` node altogether and just using `Tables` as the task. `Tables` is its primary output, I imagine? That would reduce size of dep-graph somewhat.

cc @eddyb -- perhaps this pattern applies elsewhere?

2017-01-11 21:04 UTC, eddyb commented
LGTM. I agree with `Tables`, that was my intent.

2017-01-12 16:45 UTC, nikomatsakis commented
Not as an argument against eliminating `TypeckItemBody` exactly, but it's worth noting that type-checking the item body produces *primarily* a `Tables` but also a `TypeckItemSignature` for the various closures in the body.

2017-01-12 17:02 UTC, eddyb commented
The whole closure situation is a bit troublesome. It'd be better to actually compute (copy, really) that information from the surrounding function's `Tables` (and I believe I should've just done that instead of what it is now).

2017-01-12 23:54 UTC, eddyb requested changes
LGTM except one doc nit.

2017-01-12 23:54 UTC, eddyb commented on src/librustc/dep_graph/README.md
> +`tcx.map.is_inlined_node_id()` to test.
None of this happens anymore, inlined bodies don't get their own local `NodeId`s or `DefId`s.

2017-01-13 03:27 UTC, michaelwoerister commented on src/librustc/dep_graph/README.md
> +`tcx.map.is_inlined_node_id()` to test.
Agreed.

2017-01-13 14:20 UTC, michaelwoerister commented
Looks good to me! One nit: "Tables" is a rather generic name for the dep-node that says little about what it represents. If you can think of a more descriptive name, now would be the time to change it, I guess.
Not a priority though. r=me with @eddyb's comment addressed.

2017-01-13 14:35 UTC, eddyb commented
`TypedHirTables` is maybe the most descriptive sequence of 3 words I can come up with.

2017-01-25 22:56 UTC, michaelwoerister commented
@bors r+

2017-01-25 22:57 UTC, eddyb approved these changes

2017-01-26 06:51 UTC, merged