Add doc examples & description in `std::os::unix::ffi`.
rust-lang/rust pull request #39065
Opened 2017-01-14 17:42 UTC by frewsxcv

2017-01-14 17:49 UTC, frewsxcv commented
r? @GuillaumeGomez

2017-01-15 00:11 UTC, GuillaumeGomez commented
```
failures:

---- sys::imp::ext::ffi::OsStrExt::as_bytes_0 stdout ----
	error[E0432]: unresolved import `std::os::ffi::OsStrExt`
 --> <anon>:5:5
  |
5 | use std::os::ffi::OsStrExt;
  |     ^^^^^^^^^^^^^^^^^^^^^^ Could not find `ffi` in `os`

error: no method named `as_bytes` found for type `&std::ffi::OsStr` in the current scope
 --> <anon>:8:20
  |
8 | let bytes = os_str.as_bytes();
  |                    ^^^^^^^^
  |
  = help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
  = help: candidate #1: `use std::os::ext::ffi::OsStrExt;`

error: aborting due to previous error(s)

thread 'sys::imp::ext::ffi::OsStrExt::as_bytes_0' panicked at 'Box<Any>', /checkout/src/librustc/session/mod.rs:203
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- sys::imp::ext::ffi::OsStrExt::from_bytes_0 stdout ----
	error[E0432]: unresolved import `std::os::ffi::OsStrExt`
 --> <anon>:5:5
  |
5 | use std::os::ffi::OsStrExt;
  |     ^^^^^^^^^^^^^^^^^^^^^^ Could not find `ffi` in `os`

error: no associated item named `from_bytes` found for type `std::ffi::OsStr` in the current scope
 --> <anon>:8:14
  |
8 | let os_str = OsStr::from_bytes(bytes);
  |              ^^^^^^^^^^^^^^^^^
  |
  = help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
  = help: candidate #1: `use std::os::ext::ffi::OsStrExt;`

error: aborting due to previous error(s)

thread 'sys::imp::ext::ffi::OsStrExt::from_bytes_0' panicked at 'Box<Any>', /checkout/src/librustc/session/mod.rs:203

---- sys::imp::ext::ffi::OsStringExt::from_vec_0 stdout ----
	error[E0432]: unresolved import `std::os::ffi::OsStringExt`
 --> <anon>:5:5
  |
5 | use std::os::ffi::OsStringExt;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `ffi` in `os`

error: no associated item named `from_vec` found for type `std::ffi::OsString` in the current scope
 --> <anon>:8:17
  |
8 | let os_string = OsString::from_vec(bytes);
  |                 ^^^^^^^^^^^^^^^^^^
  |
  = help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
  = help: candidate #1: `use std::os::ext::ffi::OsStringExt;`

error: aborting due to previous error(s)

thread 'sys::imp::ext::ffi::OsStringExt::from_vec_0' panicked at 'Box<Any>', /checkout/src/librustc/session/mod.rs:203

---- sys::imp::ext::ffi::OsStringExt::into_vec_0 stdout ----
	error[E0432]: unresolved import `std::os::ffi::OsStringExt`
 --> <anon>:5:5
  |
5 | use std::os::ffi::OsStringExt;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `ffi` in `os`

error: no method named `into_vec` found for type `std::ffi::OsString` in the current scope
 --> <anon>:9:23
  |
9 | let bytes = os_string.into_vec();
  |                       ^^^^^^^^
  |
  = help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
  = help: candidate #1: `use std::os::ext::ffi::OsStringExt;`

error: aborting due to previous error(s)
```

2017-01-15 00:11 UTC, GuillaumeGomez requested changes
Just a few little things missing.

2017-01-15 00:11 UTC, GuillaumeGomez commented on src/libstd/sys/unix/ext/ffi.rs
> +    /// Creates an `OsStr` from a byte slice.
Missing url.

2017-01-15 00:11 UTC, GuillaumeGomez commented on src/libstd/sys/unix/ext/ffi.rs
>      /// Gets the underlying byte view of the `OsStr` slice.
Could you add the missing url here as well please?

2017-01-15 00:11 UTC, GuillaumeGomez commented on src/libstd/sys/unix/ext/ffi.rs
>      /// Yields the underlying byte vector of this `OsString`.
Could you add the missing url here as well please?

2017-01-15 00:11 UTC, GuillaumeGomez commented on src/libstd/sys/unix/ext/ffi.rs
>      /// Creates an `OsString` from a byte vector.
Could you add the missing url here as well please?

2017-01-15 15:14 UTC, frewsxcv commented
Comments have been addressed. Tests pass on Travis.

2017-01-15 17:39 UTC, GuillaumeGomez approved these changes

2017-01-15 17:39 UTC, GuillaumeGomez commented
Thanks!

@bors: r+ rollup

2017-01-16 18:10 UTC, alexcrichton commented
@bors: retry

* netbsd network failure #39097

On Mon, Jan 16, 2017 at 8:06 AM, bors <notifications@github.com> wrote:

> 💔 Test failed - status-travis
> <https://travis-ci.org/rust-lang/rust/builds/192401713>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/39065#issuecomment-272901669>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAD95OOMjL6JZyBB9dtMZyNp99KVkU2Uks5rS5WegaJpZM4LjsKP>
> .
>

2017-01-17 00:50 UTC, merged