crater check commit for issue #36082
rust-lang/rust pull request #39066
Opened 2017-01-14 18:00 UTC by arielb1

this errors when destructor lifetime would change.

cc @nikomatsakis

2017-01-14 18:00 UTC, rust-highfive commented
r? @eddyb

(rust_highfive has picked a reviewer for you, use r? to override)

2017-01-17 19:38 UTC, nikomatsakis commented
Started a crater run from 27b9e6d450590751fca863312a8cf10f289cf1f2 to edb3baaa6c0e14481e4a4fa771d57f67f21d5a14.

2017-01-20 00:30 UTC, brson commented
Crater doesn't seem to be done. I asked it to test the crates for those two commits.

2017-01-20 00:33 UTC, brson commented
Hm, actually I don't see a working toolchain, so I asked crater to build those too:

```
$ target/debug/crater-cli.exe custom-build https://github.com/arielb1/rust 27b9e6d450590751fca863312a8cf10f289cf1f2
created task for https://github.com/arielb1/rust
inspector link: https://tools.taskcluster.net/task-inspector/#ISvWJ_uHQ6-a7JqkzPao7g

$ target/debug/crater-cli.exe custom-build https://github.com/arielb1/rust edb3baaa6c0e14481e4a4fa771d57f67f21d5a14
created task for https://github.com/arielb1/rust
inspector link: https://tools.taskcluster.net/task-inspector/#7hHpwaOwTB2Oeni5xdSV3g
```

2017-01-20 05:59 UTC, nikomatsakis commented
@brson yeah I was getting null results for some reason, not sure what went wrong :(

2017-01-20 20:08 UTC, brson commented
Ok, there was a bug in crater. The message broker shutdown at some point and crater never recovered. After starting back up it received the toolchain build complete messages, and I've started the crate builds.

2017-01-23 21:16 UTC, brson commented
[Crater says](https://gist.github.com/anonymous/e11b3e13f5fa92b808b83d3e49cf63d1).  Only 2 false positives.

2017-01-23 22:12 UTC, arielb1 commented
No positives yay! We should just merge this.

@nikomatsakis - since there is nothing on Crater, do you think we can go without a warning?

2017-01-23 22:55 UTC, nikomatsakis commented
@arielb1 Hmm, interesting! I'm not sure. Can we land it but also include some of this code, so that if you *do* get an error, we give a nice error message directing you to a tracking issue? How hard would that be?

2017-01-23 22:55 UTC, nikomatsakis commented
@arielb1 (after all we don't have 100% coverage, crater is still linux only I think, but also outside of crates.io)

2017-01-24 14:30 UTC, arielb1 commented
Added some warnings in a commit - the case that causes new lifetime errors is quite pathological (I added a test), but it exists.

2017-01-24 21:31 UTC, nikomatsakis commented
r? @nikomatsakis

2017-01-24 21:33 UTC, nikomatsakis requested changes

2017-01-24 21:33 UTC, nikomatsakis commented on src/librustc_mir/build/expr/as_temp.rs
> +                "this expression used to live longer due to #36082");
we should make a proper tracking issue with an explanation of how to rewrite code to be unambiguous, but this seems good otherwise

2017-01-24 21:33 UTC, nikomatsakis commented on src/test/compile-fail/issue-36082.rs
> +    let a: &_ = *&&0;
what is this test ... testing?

2017-01-25 00:49 UTC, arielb1 commented
Ready for review.

r? @nikomatsakis

2017-01-25 16:16 UTC, nikomatsakis approved these changes

2017-01-25 16:16 UTC, nikomatsakis commented on src/librustc_borrowck/borrowck/mod.rs
> +(https://github.com/rust-lang/rust/issues/39283)");
nice, thanks for writing that up

2017-01-25 16:16 UTC, nikomatsakis commented
@bors r+

2017-01-26 12:34 UTC, arielb1 commented
Strange error on the dist bot - cc @alexcrichton 

@bors retry

2017-01-26 20:33 UTC, merged