Better tokentree pretty printer
rust-lang/rust pull request #39079
Opened 2017-01-15 16:37 UTC by bjorn3

The example at the homepage now print like this when parsed as tokentrees:
```rust
fn main()
{
    let program = "+ + * - /";
    let mut accumulator = 0;
    . .. ...;
    a.b;
    .. .a;
    a. ..;
    for token in program.chars()
    {
        match token {
                        '+' => accumulator += 1 , '-' => accumulator -= 1 , '*' => accumulator *= 2 , '/' => accumulator /= 2 , _ => {}

                    }

    }

    println !("The program \"{}\" calculates the value {}" , program , accumulator );
}
```

2017-01-15 16:37 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @pnkfelix (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-01-15 18:35 UTC, bjorn3 commented on src/libsyntax/print/pprust.rs
> +        self.print_tts(unsafe{::std::slice::from_raw_parts(tt as *const _, 1)}); // Unsafe block to convert ref to single item slice ref without cloning
Is this allowed and is there a other way to do this?

2017-01-16 17:28 UTC, bjorn3 commented on src/libsyntax/print/pprust.rs
> +        self.print_tts(unsafe{::std::slice::from_raw_parts(tt as *const _, 1)}); // Unsafe block to convert ref to single item slice ref without cloning
Is this allowed and is there a other way to do this?

2017-01-17 15:11 UTC, bjorn3 commented
What is going on here while compiling stage1?

```
Compiling fmt_macros v0.0.0 (file:///checkout/src/libfmt_macros) error: no rules expected the token `static` --> /checkout/src/liblog/lib.rs:215:5 | 215 | static LOCAL_LOGGER: RefCell<Option<Box<Logger + Send>>> = { | ^^^^^^
```

2017-01-17 15:29 UTC, steveklabnik commented
/cc @nrc @rust-lang/compiler

2017-01-17 16:35 UTC, pnkfelix commented on src/libsyntax/print/pprust.rs
> +                                                                            // ^^^---
I'm pretty sure this comment is not what you wanted...

2017-01-17 16:37 UTC, pnkfelix reviewed
I'm ... pretty sure we don't approve PR's with merge commits in them. So you probably need to clean up your revision history; it may suffice to just rebase.

2017-01-17 16:38 UTC, pnkfelix commented
Also, I'm not yet sure what this is doing, because I don't remember what the token-tree printer was, what it used to look like, whether it was good/bad, et cetera. 

I say this mostly as a way of saying "I'm giving feedback on relatively minor points, but you should not interpret that as giving *any* indication about my feelings on the PR as a whole."

2017-01-17 16:43 UTC, bjorn3 commented on src/libsyntax/print/pprust.rs
> +                                                                            // ^^^---
Forgot to fix indentation :(

2017-01-17 16:46 UTC, bjorn3 commented
It is used in error mesages when for example a proc macro outputs `fn a+b(){}` which doesnt parse as far as i known. Will rebase soon.

2017-01-17 16:52 UTC, nikomatsakis commented
Pre-existing, but it seems like it'd be good to have some tests of this, no?

2017-01-17 17:02 UTC, bjorn3 commented
Will add them when i rebase.

2017-01-17 18:37 UTC, bjorn3 commented
Messed up a bit with rebasing. will have to do the fix build cycle from before again :(

2017-01-17 19:37 UTC, bjorn3 reviewed
Few questions

2017-01-17 19:37 UTC, bjorn3 commented on src/libsyntax/print/pprust.rs
> +                        '+' => accumulator += 1 , '-' => accumulator -= 1 , '*' => accumulator *= 2 , '/' => accumulator /= 2 , _ => {}
What should I do here to fix the tidy error? Can't put a newline because I would have another string then.

2017-01-17 19:37 UTC, bjorn3 commented on src/libsyntax/print/pprust.rs
> +        self.print_tts(unsafe{::std::slice::from_raw_parts(tt as *const _, 1)})
Is this allowed and is there a other way to do this?

2017-01-17 19:52 UTC, bjorn3 commented on src/libsyntax/print/pprust.rs
> +                        '+' => accumulator += 1 , '-' => accumulator -= 1 , '*' => accumulator *= 2 , '/' => accumulator /= 2 , _ => {}
Ignored it

2017-01-17 20:30 UTC, jseyfried commented on src/libsyntax/print/pprust.rs
> +        self.print_tts(unsafe{::std::slice::from_raw_parts(tt as *const _, 1)})
I don't think this is worth using `unsafe`.
I would just clone the token tree (i.e. `self.print_tts(&[tt.clone()])`) -- it isn't a deep clone, just a copy plus an `Rc` ref-count update. You could also refactor `print_tts` to take an `Iterator<Item=&TokenTree>`.

2017-01-17 20:31 UTC, jseyfried commented
cc @nrc

2017-01-17 20:48 UTC, bjorn3 commented
Build fails due to bug in this tt pretty printer.

2017-01-19 19:13 UTC, bjorn3 commented
I had a break which I meant to break out of the match not the loop 🤦. This meant skipping a great part of the [thread_local](https://doc.rust-lang.org/stable/src/std/up/src/libstd/thread/local.rs.html#124-151) macro.

2017-01-19 19:47 UTC, bjorn3 commented
Accidentally added a nul byte.

2017-01-19 20:51 UTC, bjorn3 commented
Why does the build fail?

2017-01-20 17:19 UTC, bjorn3 commented
Rebased

2017-01-20 22:23 UTC, eddyb commented on src/libsyntax/print/pprust.rs
> +                        word(&mut self.s, &token_to_string(tk))?;
Is there no way to print a single token? I guess the same is a problem above.

2017-01-20 22:24 UTC, eddyb commented on src/libsyntax/print/pprust.rs
> +                        word(&mut self.s, &token_to_string(token))?;
Sad. I guess it's pre-existing, though.

2017-01-20 22:31 UTC, eddyb commented
I have no suggestions about the bug other than "comment out the special cases and see if that still fails".
If this is not a very weird bug, it might reproduce with `./x.py test --stage 1 src/test/codegen`.

2017-01-22 08:50 UTC, bjorn3 commented
@eddyb I can't reproduce the travis error on local mac osx. Only run-fail/assert-macro-explicit.rs fails due to a added space.

2017-01-22 09:09 UTC, bjorn3 commented
Are the location of stringify! spaces and newlines (semi)guaranteed. If so this is a **breaking change**.

2017-01-22 13:00 UTC, eddyb commented
@bjorn3 Alright, you can still sort of abuse Travis to test it for you. I'd suggest pushing a single commit that comments out all the special cases *but leaves your own code for the default ones*.
If that works, you can then bisect which special case breaks. If it doesn't... You can bisect to the original.

2017-01-24 18:18 UTC, bjorn3 commented
Some thing weird with https://travis-ci.org/rust-lang/rust/builds/194891536: travis gives green while the build task gave a error.

2017-01-27 05:53 UTC, bjorn3 commented
@eddyb @pnkfelix ready for review.

2017-01-27 10:46 UTC, eddyb requested changes
LGTM, except one case I noticed.

2017-01-27 10:46 UTC, eddyb commented on src/test/run-make/trace-macros-flag/hello.trace
> +print! { concat !("Hello, World!" , "\n") }
Identifier (not keyword) followed by `!` should not have a space in between.

2017-01-27 10:47 UTC, eddyb commented
Oh and tyou should squash your fix commits.

2017-01-27 14:27 UTC, bjorn3 commented
Will squash when i am home.

2017-01-27 14:49 UTC, eddyb approved these changes

2017-01-27 16:36 UTC, bjorn3 commented
Squashed

2017-01-27 16:56 UTC, eddyb commented
@pnkfelix I think this is ready to go, assuming Travis will pass.

2017-01-28 00:59 UTC, pnkfelix commented
@bors r+

2017-01-28 02:50 UTC, alexcrichton commented
@bors: retry

* prioritizing rollup

2017-01-29 09:34 UTC, bjorn3 commented
@pnkfelix test passes.

2017-01-29 11:03 UTC, bjorn3 commented
Squashed

2017-01-30 12:19 UTC, pnkfelix commented
@bors r+

2017-01-30 15:36 UTC, bjorn3 commented
I think i will make a script to update the failing pretty print tests:
```
test result: FAILED. 2462 passed; 122 failed; 27 ignored; 0 measured
```

2017-02-01 13:56 UTC, pnkfelix commented
@bjorn3 travis says tidy checks are failling.

2017-02-04 19:50 UTC, eddyb commented on src/libsyntax/print/pprust.rs
> +            \'+\' => accumulator += 1 , \'-\' => accumulator -= 1 , \'*\' => accumulator *= 2 , \'/\' => accumulator /= 2 , _ => {}
Two interesting things here:
* `{` should never start a new line *before* it, always *after*
 * it gets trickier sometimes thought (`}` and `;` come to be mind)
 * the whole reason there's a `pp.rs` is for automating breaks
 * but I'm not sure the algorithm is appropriate for Rust or bug-free
* `,` should never have a space *before* it, always *after*

2017-02-04 20:19 UTC, bjorn3 commented on src/libsyntax/print/pprust.rs
> +            \'+\' => accumulator += 1 , \'-\' => accumulator -= 1 , \'*\' => accumulator *= 2 , \'/\' => accumulator /= 2 , _ => {}
I dont really understand print::pp to be honest. Documentation would be really appreciated.

2017-02-04 20:26 UTC, eddyb commented on src/libsyntax/print/pprust.rs
> +            \'+\' => accumulator += 1 , \'-\' => accumulator -= 1 , \'*\' => accumulator *= 2 , \'/\' => accumulator /= 2 , _ => {}
Who does? *shrug*

2017-02-05 08:50 UTC, bjorn3 commented on src/libsyntax/print/pprust.rs
> +            \'+\' => accumulator += 1 , \'-\' => accumulator -= 1 , \'*\' => accumulator *= 2 , \'/\' => accumulator /= 2 , _ => {}
Found docs at the Printer struct. Opened #39557 with a few doc improvements.

2017-03-20 10:08 UTC, pnkfelix commented
@bjorn3 are you going to be able to address the problems on this PR? (From what I can tell, Travis was never satisfied with it...?) Or should I close it to clean up the queue?

2017-03-20 15:09 UTC, bjorn3 commented
If I want to retry this in the future I will make a new pr.

2017-03-20 15:09 UTC, closed without merging