Add error explanation for E0491
rust-lang/rust pull request #39091
Opened 2017-01-16 09:11 UTC by richard-imaoka

Refs #32777

Please let me know if any question or anything doesn't look right about this.

2017-01-16 09:11 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @pnkfelix (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-01-16 21:46 UTC, GuillaumeGomez requested changes
Excellent work! Just some little nits, nothing to say about the content itself.

2017-01-16 21:46 UTC, GuillaumeGomez commented on src/librustc/diagnostics.rs
> +//struct containing a reference requires a lifetime parameter,
Please add a whitespace after the '//'.

2017-01-16 21:46 UTC, GuillaumeGomez commented on src/librustc/diagnostics.rs
> +    ref_i32: &'a i32
Please add a comma at the end of the line.

2017-01-16 21:46 UTC, GuillaumeGomez commented on src/librustc/diagnostics.rs
> +//However, a nested struct like this, the signature itself does not tell
Same.

2017-01-16 21:46 UTC, GuillaumeGomez commented on src/librustc/diagnostics.rs
> +    ref_struct: &'b Struct<'a> //compile error E0491!
Same (and same).

2017-01-16 21:46 UTC, GuillaumeGomez commented on src/librustc/diagnostics.rs
> +
Why so much empty lines?

2017-01-16 21:46 UTC, GuillaumeGomez commented on src/librustc/diagnostics.rs
> +    ref_struct: &'b Struct<'a>
Same.

2017-01-16 21:46 UTC, GuillaumeGomez commented on src/librustc/diagnostics.rs
> +//'a: 'b means 'a outlives 'b
Same.

2017-01-17 12:51 UTC, GuillaumeGomez requested changes
Just two nits remaining!

2017-01-17 12:51 UTC, GuillaumeGomez commented on src/librustc/diagnostics.rs
> +    ref_struct: &'b Struct<'a>, //compile error E0491!
Still missing a whitespace after '//'.

2017-01-17 12:51 UTC, GuillaumeGomez commented on src/librustc/diagnostics.rs
> +    ref_struct: &'b Struct<'a>, //compile error E0491!
Oh and the '!' isn't needed. ;)

2017-01-17 13:05 UTC, richard-imaoka commented on src/librustc/diagnostics.rs
> +    ref_struct: &'b Struct<'a>, //compile error E0491!
ah sorry, fixing this now...

2017-01-17 13:09 UTC, richard-imaoka commented
@GuillaumeGomez thank you very much for quick reviews. I think all your comments are reflected now.

2017-01-17 13:12 UTC, GuillaumeGomez commented
Thanks! Now please [squash](https://blog.guillaume-gomez.fr/Git-tips/1/2) your commits and it'll be good to go!

2017-01-17 13:12 UTC, GuillaumeGomez approved these changes

2017-01-17 13:13 UTC, GuillaumeGomez requested changes

2017-01-17 13:13 UTC, GuillaumeGomez commented on src/librustc/diagnostics.rs
> +}F
Missed this one: Why is there an 'F' here?

2017-01-17 13:14 UTC, richard-imaoka commented on src/librustc/diagnostics.rs
> +}F
oops sorry, :| will delete this F and squash my commits

2017-01-17 13:19 UTC, richard-imaoka commented
Squashed into a single commit and removed the unnecessary 'F' as advised.

2017-01-17 15:19 UTC, GuillaumeGomez commented
Thanks!

@bors: r+ rollup

2017-01-17 23:16 UTC, richard-imaoka commented
Is this still in change requested state?

2017-01-17 23:33 UTC, GuillaumeGomez approved these changes

2017-01-17 23:34 UTC, GuillaumeGomez commented
Reviews status are just an indication, nothing to worry. I have put your PR in the bot's queue. It'll handle the tests and the merge for us.

2017-01-19 18:31 UTC, merged