Change unreachable pattern ICEs to warnings
rust-lang/rust pull request #39127
Opened 2017-01-17 13:34 UTC by canndrew

Allow code with unreachable `?` and `for` patterns to compile.
Add some tests.

2017-01-17 13:34 UTC, rust-highfive commented
r? @arielb1

(rust_highfive has picked a reviewer for you, use r? to override)

2017-01-17 13:50 UTC, canndrew commented
Ugh, bloody make tidy. Every single time.

2017-01-17 13:54 UTC, canndrew commented
So to summarise: An unreachable pattern in a `ForLoopDesugar` is now a warning instead of a `span_bug!`. An unreachable pattern in a `TryDesugar` is nothing, not even a warning (because it should be fine to `?` a `Result<!, T>`). `?` now desguars to a match expression which has `#[allow(unreachable_patterns)]` and `#[allow(unreachable_code)]` on it.

2017-01-17 14:17 UTC, eddyb commented
cc @rust-lang/compiler

2017-01-17 18:42 UTC, nikomatsakis approved these changes

2017-01-17 19:30 UTC, nikomatsakis commented on src/librustc/hir/lowering.rs
> +                    // #[allow(unreachable_patterns)]
Hmm, so, this `#[allow(unreachable_patterns)]` annotation presumably affects the `<expr>`, right? That seems unfortunate.  i.e., if I do `(match { ... })?`, do we still see warnings from the inner `match`?

2017-01-17 19:30 UTC, nikomatsakis commented
r? @nikomatsakis (I'm assuming @arielb1 doesn't have time)

2017-01-17 19:32 UTC, durka commented
Wait, do expr-level `#[allow]` annotations work? [Last I checked, they have no effect.](https://is.gd/ivYz2N)

2017-01-18 07:02 UTC, canndrew commented on src/librustc/hir/lowering.rs
> +                    // #[allow(unreachable_patterns)]
Good point, I'll need to look into this :/

2017-01-18 08:34 UTC, arielb1 commented
I do have time.

2017-01-18 08:44 UTC, arielb1 commented on src/librustc/hir/lowering.rs
> +                    // #[allow(unreachable_patterns)]
Can't you key things directly on the `MatchSource`?

2017-01-18 08:53 UTC, canndrew commented on src/librustc/hir/lowering.rs
> +                    // #[allow(unreachable_patterns)]
I still seem to get warnings without these. At least the `unreachable_code` attribute seems to have an effect. I was thinking I'll change the code to this:

```rust
match Carrier::translate(<expr>) {
    #[allow(unused)]
    Ok(val) => val,
    #[allow(unused)]
    Err(err) => return Carrier::from_error(From::from(err)),
}
```

2017-01-18 12:02 UTC, arielb1 commented on src/librustc/hir/lowering.rs
> +                    // #[allow(unreachable_patterns)]
The `unreachable_code` attribute is indeed fine - no user-defined code exists under it. It's the `unreachable_patterns` attribute that is the problem - could you check why is it needed?

2017-01-19 07:30 UTC, nikomatsakis commented
@arielb1 ok :) either way. In any case, I think we both agree that we should try to avoid having warnings get squelched in user code *somehow*. I agree with the suggestion of using the `MatchSource` to squelch the lints, does that not work?

2017-01-19 07:46 UTC, nikomatsakis commented
@canndrew I just want to clarify something. Given https://github.com/rust-lang/rust/pull/39151, is this PR necessary for backwards compatibility? I'm trying to assess the priority of landing it with respect to the release timeline.

2017-01-19 14:57 UTC, arielb1 commented
@nikomatsakis

The PR is required. #39151 just gates the uninhabitableness of references, it does not revert the changes for matching `Result<X, Void>`.

2017-01-19 14:59 UTC, arielb1 commented on src/librustc/hir/lowering.rs
> +                        let val_block = P(self.block_expr(val_expr));
Do we need the `block_expr`/`expr_block` pair?

2017-01-20 15:28 UTC, canndrew commented on src/librustc/hir/lowering.rs
> +                        let val_block = P(self.block_expr(val_expr));
No.. for some reason I thought we did.

2017-01-20 16:09 UTC, canndrew commented
Sorry for spamming travis.

I've now changed the try desugaring to this:

```rust
match Carrier::translate(<expr>) {
    Ok(val) => #[allow(unreachable_code)] val,
    Err(err) => #[allow(unreachable_code)] return Carrier::from_error(From::from(err)),
}
```

That seems to be all we need to crush the warnings.

2017-01-20 22:58 UTC, arielb1 commented on src/librustc/hir/lowering.rs
>                      //     Err(err) => return Carrier::from_error(From::from(err))
nit: update the comment here

2017-01-20 22:59 UTC, arielb1 commented on src/librustc/hir/lowering.rs
> +                                                                    From::from(attrs.clone())));
I prefer `ThinVec::from`, but whatever you want.

2017-01-20 23:01 UTC, arielb1 commented on src/librustc_const_eval/check_match.rs
> +                        hir::MatchSource::TryDesugar => {}
A comment would be nice, for example:
```Rust
// unreachable patterns in a try expression occur when one of the arms
// is of an uninhabited type, which is OK.
```

2017-01-20 23:02 UTC, arielb1 requested changes
nice modulo comment nits.

2017-01-22 08:18 UTC, arielb1 commented
@bors r+

2017-01-22 11:14 UTC, merged