Bounds parsing refactoring 2
rust-lang/rust pull request #39158
Opened 2017-01-18 17:09 UTC by petrochenkov

See https://github.com/rust-lang/rust/pull/37511 for previous discussion.
cc @matklad

Relaxed parsing rules:
 - zero bounds after `:` are allowed in all contexts.
 - zero predicates are allowed after `where`.
- trailing separator `,` is allowed after predicates in `where` clauses not followed by `{`.

Stricter parsing rules:
 - trailing separator `+` is disallowed in all bound lists.

Code is also cleaned up and tests added.

I haven't touched parsing of trait object types yet, I'll do it later.

2017-01-18 17:09 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2017-01-18 18:01 UTC, durka commented
Why disallow trailing `+` when trailing `,` is allowed? Does it create an ambiguity?

2017-01-18 18:28 UTC, petrochenkov commented
@durka 
No ambiguity, it's a [lang team decision](https://github.com/rust-lang/rust/pull/37511#issuecomment-264312414).

(I'd personally keep it though, because 1) uniformity (other trailing separators are allowed), 2) it was accepted since 1.0 until now, 3) it's "naturally" allowed and you have to add extra code to the parser to prohibit it)

2017-01-18 18:31 UTC, petrochenkov commented
@durka 
Do you have an example of trailing `+` being useful in macros?

2017-01-18 18:32 UTC, durka commented
Yeah, those three reasons make sense to me. This should be cratered then,
WRT #2.

On Wed, Jan 18, 2017 at 1:29 PM, Vadim Petrochenkov <
notifications@github.com> wrote:

> @durka <https://github.com/durka>
> No ambiguity, it's a lang team decision
> <https://github.com/rust-lang/rust/pull/37511#issuecomment-264312414>.
>
> (I'd personally keep it though, because 1) uniformity (other trailing
> separators are allowed), 2) it was accepted since 1.0 until now, 3) it's
> "naturally" allowed and you have to add extra code to the parser to
> prohibit it)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/39158#issuecomment-273558998>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAC3n5mUeuO3uFj1On8BN5wcj7OzoCK4ks5rTlnsgaJpZM4LnJLp>
> .
>

2017-01-18 18:32 UTC, durka commented
I don't think it's useful in macros, because you can just do `$($bounds)++`
and it's no problem. I was thinking of consistency between various types of
separators. But then again you don't want "1 + 1 +" to be a valid
arithmetic expression.

On Wed, Jan 18, 2017 at 1:31 PM, Vadim Petrochenkov <
notifications@github.com> wrote:

> @durka <https://github.com/durka>
> Do you have an example of trailing + being useful in macros?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/39158#issuecomment-273559693>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAC3n9kaqguUTZiZyDI3GUOpgy_ahvJiks5rTlqHgaJpZM4LnJLp>
> .
>

2017-01-18 18:44 UTC, petrochenkov commented
>But then again you don't want "1 + 1 +" to be a valid
arithmetic expression.

Expression `+` and type `+` are actually different! :slightly_smiling_face: 
Expression `+` is a binary operator and lists like `1 + 1 + 1 + 1` are desugared into several operator applications `((1 + 1) + 1) + 1`.
Type `+` is not a binary operator and summands in lists like `Trait + Trait + Trait` can't be grouped. `(Trait + Trait) + Trait` and `ArbitraryType + Trait` in general are not valid.

2017-01-19 07:25 UTC, nikomatsakis commented
@petrochenkov I feel like I would keep it too -- which is probably why it's parsed in the first place. I wonder if it's worth revisiting this. I found your three points convincing, and I'm not sure that we focus on the backwards compatibility point in the meeting.

cc @rust-lang/lang -- we had [previously decided](https://github.com/rust-lang/rust/pull/37511#issuecomment-264312414) to not accept `T: Foo + Bar +` (where `+` acts as a trailing separator) because it "looks weird" (which is indisputably true). However, @petrochenkov points out that it [is accepted today](https://is.gd/th9sfI) (also indisputably true). "Looking weird" doesn't feel like reason enough to break backwards compatibility to me, particularly since accepting trailing separators is known to be useful for macros. So I think I'd like to revisit this decision. What do people think?

2017-01-19 08:40 UTC, withoutboats commented
I think when we agreed on that we thought we were talking about expanding what is accepted to include trailing `+`. I agree we shouldn't break the language.

2017-01-19 19:53 UTC, joshtriplett commented
@nikomatsakis If we accept this today, we should continue doing so, and document it for potential use by macros.  Not worth breaking backward compatibility over.

2017-01-21 12:59 UTC, aturon commented
@nikomatsakis I agree with your reasoning; let's keep it.

2017-01-23 20:51 UTC, nikomatsakis commented
@petrochenkov care to update the PR to accept trailing `+`?

@nrc you were the main one who objected, I think, so I'd like to get your input in particular

(Does anyone feel we need to use rfcbot here?)

2017-01-23 21:06 UTC, nrc commented
@nikomatsakis yeah, I agree its not worth breaking for.

2017-01-24 20:41 UTC, petrochenkov commented
Updated with trailing `+`s permitted.

2017-01-25 17:21 UTC, nikomatsakis commented
@bors r+

Thanks @petrochenkov !

2017-01-25 17:22 UTC, nikomatsakis commented
@bors r-

2017-01-25 17:22 UTC, nikomatsakis commented
Oops :) had one thing I wanted to ask

2017-01-25 17:22 UTC, nikomatsakis requested changes

2017-01-25 17:22 UTC, nikomatsakis commented on src/librustc_passes/ast_validation.rs
> +            if let WherePredicate::EqPredicate(ref predicate) = *predicate {
to be clear, not as part of this PR =)

2017-01-25 17:35 UTC, petrochenkov commented on src/librustc_passes/ast_validation.rs
> +            if let WherePredicate::EqPredicate(ref predicate) = *predicate {
There are no plans to implement this?
Then https://github.com/rust-lang/rust/issues/20041 should be officially closed or something before removing `WherePredicate::EqPredicate`.

2017-01-25 17:43 UTC, petrochenkov commented on src/libsyntax/parse/parser.rs
> +            // FIXME plus priority
`+` still has high priority in some cases.

The first case is when trait object type starts with `for`:
```
trait Tr<'a> {}
fn f(arg: &for<'a> Tr<'a> + Send){} // Parsed as &(for<'a> Tr<'a> + Send)
```
I'm going to fix this in upcoming PR so I didn't create an issue.

The second case is `impl Trait1 + Trait2` and it seems to be [known](https://github.com/rust-lang/rust/issues/34511#issue-162545419).

2017-01-26 14:43 UTC, petrochenkov commented on src/libsyntax/parse/parser.rs
> +            // FIXME plus priority
Updated with better comments for FIXMEs.

2017-01-26 20:23 UTC, nikomatsakis commented on src/librustc_passes/ast_validation.rs
> +            if let WherePredicate::EqPredicate(ref predicate) = *predicate {
Well, eventually perhaps, but at the moment there are some theoretical limitations that I do not yet know how to overcome. I would say "we may implement it eventually, but in that case we can add that stuff back in to the compiler".

2017-01-26 20:23 UTC, nikomatsakis approved these changes

2017-01-26 20:23 UTC, nikomatsakis commented
@bors r+

2017-01-26 23:35 UTC, alexcrichton commented
@bors: retry

* android emulator wedged? Haven't seen that before...

On Thu, Jan 26, 2017 at 3:26 PM, bors <notifications@github.com> wrote:

> 💔 Test failed - status-travis
> <https://travis-ci.org/rust-lang/rust/builds/195685787>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/39158#issuecomment-275546308>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAD95Aq3XBj-ktJQQjbFe66c8DYzA6Y0ks5rWSuigaJpZM4LnJLp>
> .
>

2017-01-27 01:26 UTC, alexcrichton commented
@bors: retry

* fiddling with homu

2017-01-27 04:17 UTC, merged