In std:rc, clarify the lack of mutability inside an Rc
rust-lang/rust pull request #39299
Opened 2017-01-25 19:14 UTC by federicomenaquintero

Also, point to the example in Cell's docs for how to do it.

2017-01-25 19:15 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @BurntSushi (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-01-31 11:18 UTC, GuillaumeGomez requested changes
Few nits.

2017-01-31 11:18 UTC, GuillaumeGomez commented on src/liballoc/rc.rs
> +//! something inside an `Rc`.  If you need mutability, put a [`Cell`]
Extra whitespace before "if you need mutability".

2017-01-31 11:18 UTC, GuillaumeGomez commented on src/liballoc/rc.rs
> +//! Shared references in Rust disallow mutation by default, and `Rc`
`Rc` should be [`Rc`].

2017-01-31 11:18 UTC, GuillaumeGomez commented on src/liballoc/rc.rs
> +//! something inside an `Rc`.  If you need mutability, put a [`Cell`]
`Rc` should be [`Rc`].

2017-01-31 11:18 UTC, GuillaumeGomez commented
Just a few nits and it'll be good!

2017-01-31 15:16 UTC, federicomenaquintero commented
Pushed an extra commit to de-nitify.

2017-01-31 16:40 UTC, GuillaumeGomez commented on src/liballoc/rc.rs
> +//! [introducing-mutability]: ../../std/cell/index.html#introducing-mutability-inside-of-something-immutable
This line is longer than 100 characters so tidy fails.

2017-01-31 16:40 UTC, GuillaumeGomez approved these changes

2017-01-31 16:41 UTC, GuillaumeGomez commented
Once your tidy issue has been fixed, please squash your commits.

2017-02-01 00:04 UTC, federicomenaquintero commented
I've pushed a squashed version.  This also has a shortened link name so the line in the references doesn't exceed 100 chars :-P

2017-02-01 10:52 UTC, GuillaumeGomez commented
Thanks!

@bors: r+ rollup

2017-02-03 00:47 UTC, merged