Ipv6Addr <-> u128
rust-lang/rust pull request #39324
Opened 2017-01-26 21:12 UTC by clarcharr

Because we have `u128` now, it makes sense to add a conversion between `Ipv6Addr` and `u128` in addition to the existing one between `Ipv4Addr` and `u32`.

2017-01-26 21:12 UTC, rust-highfive commented
r? @alexcrichton

(rust_highfive has picked a reviewer for you, use r? to override)

2017-01-26 22:36 UTC, alexcrichton commented
Sounds reasonable to me!

2017-01-26 22:37 UTC, alexcrichton commented
I think to fix the errors on Travis we'll want to tag these with `#[cfg(not(stage0))]` perhaps?

@rfcbot fcp merge

2017-01-27 00:31 UTC, brson commented
Aren't 128-bit ints cfg'd in some target-specific way? These are defined unconditionally.

2017-01-27 01:30 UTC, clarcharr commented
@brson are there any tier 1 platforms where this happens? Because if that's the case, bors will catch that

2017-01-27 04:16 UTC, alexcrichton commented
@brson that's a good point, actually. I'm not sure what we should consider the status of u128/i128 in terms of portability. I believe that all current platforms Rust targets supports the types but that doesn't necessarily mean that all future platforms will.

2017-01-27 04:29 UTC, clarcharr commented
@alexchrichton I personally think that a catch-all `cfg(has_i128)` or something along those lines would be a better fix than the current `cfg(not(stage0))`

2017-01-27 04:36 UTC, sfackler commented
I'm not sure I understand the portability issues with u/i128. How are those different than e.g. u/i64?

2017-01-27 05:13 UTC, clarcharr commented
@brson I'd check @nagisa's comment on the tracking issue for 128-bit issue regarding that. @sfackler is right

2017-01-27 12:16 UTC, ollie27 requested changes

2017-01-27 16:02 UTC, clarcharr commented on src/libstd/net/ip.rs
> +#[stable(feature = "ipv6_u128", since = "1.17.0")]
Impls can't be unstable so I made it stable.

2017-01-27 16:02 UTC, clarcharr commented on src/libstd/net/ip.rs
> +        assert_eq!(u128::from(a), 0xffffffffffffffff0080000000000001u128);
I agree with you there. I'll update the IPv4 test too.

2017-01-27 16:03 UTC, clarcharr commented on src/libstd/net/ip.rs
> +        ((ip[0] as u128) << 104) + ((ip[1] as u128) << 96) + ((ip[2] as u128) << 80) +
I mostly copy-pasted the one from IPv4; is the difference worthwhile?

2017-01-27 16:09 UTC, ollie27 commented on src/libstd/net/ip.rs
> +#[stable(feature = "ipv6_u128", since = "1.17.0")]
You're correct but rustdoc will display the version number on impls that are marked stable and 1.17.0 is clearly wrong for these.

2017-01-27 16:11 UTC, ollie27 commented on src/libstd/net/ip.rs
> +        ((ip[0] as u128) << 104) + ((ip[1] as u128) << 96) + ((ip[2] as u128) << 80) +
Not really, either way works fine.

2017-01-27 18:14 UTC, clarcharr commented
The latest travis errors seem to be an error in parsing the integer literals.

2017-01-27 19:42 UTC, nagisa commented
> The latest travis errors seem to be an error in parsing the integer literals.

Most likely a staging issue of some sort; these literals work just fine on a proper nightly compiler.

2017-01-27 23:59 UTC, brson commented
Further comments [here](https://github.com/rust-lang/rust/issues/35118#issuecomment-275806576).

2017-01-31 01:16 UTC, alexcrichton commented
ping @brson @BurntSushi  (checkboxes)

2017-01-31 01:16 UTC, alexcrichton commented
Also @clarcharr it looks like there's still failing tests on travis?

2017-01-31 01:23 UTC, clarcharr commented
Yeah, I'm not particularly sure how to fix it myself. It seems to be accepting u128 as a type but not the integer literal, which indicates that it's probably not a staging issue.

2017-02-04 22:19 UTC, alexcrichton commented
This was discussed at the libs triage a little while ago, and the conclusion was that we'll merge this for now but consider the portability of i128/u128 in the tracking issue (and before stabilizing).

@clarcharr want to rebase and remove the stage0 annotations? With a new stage0 I think they may not be necessary any more.

2017-02-06 01:28 UTC, clarcharr commented
@alexcrichton I removed the stage0 cfgs and Travis is passing now.

2017-02-06 01:50 UTC, alexcrichton commented
Thanks!

ping @brson (checkbox)

2017-02-07 19:09 UTC, alexcrichton commented
@bors: r+

2017-02-07 22:13 UTC, alexcrichton commented
@bors: retry

* sccache wedged #39003

On Tue, Feb 7, 2017 at 2:12 PM, bors <notifications@github.com> wrote:

> 💔 Test failed - status-travis
> <https://travis-ci.org/rust-lang/rust/builds/199377916>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/39324#issuecomment-278158657>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAD95FiodMpcLi8XL5TIQB4olH2iXSpHks5raOw4gaJpZM4LvJRu>
> .
>

2017-02-08 00:03 UTC, alexcrichton commented
@bors: retry

* osx linker segfault #38878

On Tue, Feb 7, 2017 at 3:56 PM, bors <notifications@github.com> wrote:

> 💔 Test failed - status-travis
> <https://travis-ci.org/rust-lang/rust/builds/199403284>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/39324#issuecomment-278184216>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAD95Nqayxvk1y82HmWmN9IIxQY8Q428ks5raQSWgaJpZM4LvJRu>
> .
>

2017-02-08 02:49 UTC, merged