Path::is_empty
rust-lang/rust pull request #39334
Opened 2017-01-27 04:27 UTC by clarcharr

While an empty path may not necessarily have semantic significance, because `PathBuf::new` returns an empty path, I feel that having this method is necessary.

I left out `len` because it could easily be confused for the number of components in the path. However, `is_empty` seems useful and unambiguous.

2017-01-27 04:27 UTC, rust-highfive commented
r? @aturon

(rust_highfive has picked a reviewer for you, use r? to override)

2017-01-27 08:37 UTC, KalitaAlexey requested changes

2017-01-27 08:37 UTC, KalitaAlexey commented on src/libstd/path.rs
> +    /// assert!(path.is_empty())
Add `;` to the end of the line.

2017-01-27 08:37 UTC, KalitaAlexey commented on src/libstd/path.rs
> +    /// assert!(!path.is_empty())
Add `;` to the end of the line.

2017-01-27 08:37 UTC, KalitaAlexey commented on src/libstd/path.rs
> +    /// assert!(path.is_empty())
This is reason why it failed.

2017-01-27 13:26 UTC, frewsxcv commented
This was attempted before, for the record: https://github.com/rust-lang/rust/pull/31877

2017-01-29 18:30 UTC, clarcharr commented
@frewsxcv Noted. I'll just close this, then.

2017-01-29 18:30 UTC, closed without merging