Conversions between CStr, CString, and Box<CStr>
rust-lang/rust pull request #39594
Opened 2017-02-06 20:25 UTC by clarcharr

This relies on #39438.

This closes a bit of the inconsistencies between `CStr` and `str`, allowing people to create a `Box<CStr>`.

2017-02-06 20:25 UTC, rust-highfive commented
r? @aturon

(rust_highfive has picked a reviewer for you, use r? to override)

2017-02-07 15:03 UTC, bjorn3 requested changes

2017-02-07 15:03 UTC, bjorn3 commented on src/libstd/ffi/c_str.rs
> +#[stable(feature = "box_from_slice", since = "1.17.0")]
I think this should be unstable.

2017-02-07 18:27 UTC, clarcharr commented on src/libstd/ffi/c_str.rs
> +#[stable(feature = "box_from_slice", since = "1.17.0")]
Trait implementations are inherently stable, so, that's not an option.

2017-02-07 20:49 UTC, alexcrichton commented
I [requested](https://github.com/rust-lang/rust/pull/39438#issuecomment-277783450) that this be split off #39438 (thanks @clarcharr!) because we don't have a lot of precedent for this in the standard library with other DSTs like `Path`, `OsStr`, etc. These seem reasonable to me, however, and I'd be fine adding all of them all at once as well.

2017-02-07 22:20 UTC, clarcharr commented
I will add this for `OsStr` soon, although I need to find out a proper way to reconcile how the platform-specific types should be laid out. `Path` will come easily after that.

2017-02-08 04:10 UTC, clarcharr commented
I've added versions for `OsStr` and `Path`, and it'd be nice if someone took a quick glance over the code to make sure everything looks right. Because AppVeyor doesn't automatically do PRs at the moment, there might be a bug in the Windows code that won't be caught until bors tries to merge it.

2017-02-08 04:12 UTC, clarcharr commented
@aturon/@alexcrichton, I'll open up a tracking issue for the `into_boxed_*` methods once I get a nod that those methods are desired. This will be a bit of an odd change because the `From` impls will be immediately stable but the `into_*` methods will not be. If it makes more sense to open an RFC for this I can do that.

2017-02-08 18:24 UTC, alexcrichton commented
Nah yeah we can deal with the tracking issue just before merging, and these impls shouldn't require an RFC. Thanks for the updates!

2017-02-10 06:18 UTC, clarcharr commented
Currently waiting on #39438 which, even though it said it was merged before, was not actually merged.

2017-02-11 00:25 UTC, clarcharr commented
I accidentally forgot to do a git pull before merging, so, I'll have to grab dec1e6423fd96fdf5409cbb53da6634913b148de from my other machine before we merge this.

2017-02-12 22:14 UTC, clarcharr commented
Waiting on CI, but I've implemented everything necessary for this and made a full list in the OP of what was implemented.

2017-02-13 05:56 UTC, clarcharr commented
Ping @aturon

2017-02-13 16:31 UTC, aturon commented
@clarcharr Thanks! This looks good to me.

@rust-lang/libs: This PR involves some instantly-stable trait implementations. However, everything being implemented here is filling out our inter-conversion story to match other types in `std`, which should make things more consistent and predictable. I will likely r+ soon, so if you have objections or want time to consider further, please speak up!

2017-02-13 16:37 UTC, aturon commented
@clarcharr One thing that makes me a bit uncomfortable about the implementation here is the pervasive use of `mem::transmute`. I wonder if we can at least factor out some common conversions into some free-standing functions that can be re-used? Each transmute is basically making an assertion about the relative representations, and it'd be good to consolidate those if we can.

2017-02-13 16:39 UTC, BurntSushi commented
I think I'm fine with this.

In the implementation there are a lot of `transmute`s. Are they all necessary or is there anyway to get rid of some of them?

2017-02-13 16:39 UTC, BurntSushi commented
@aturon Haha. Beat me to it. :P

2017-02-13 17:33 UTC, alexcrichton commented
Looks good to me! I think we could annotate the input/output types in the transmutes, but otherwise I think they may unfortunately be required

2017-02-13 18:02 UTC, clarcharr commented
The main issue with the transmutes is that there's no other way of converting newtype DSTs. I decided to do one type at a time which is why there are so many, because each transmute adds one more layer of newtypes.

It's most complicated in the instance of Path on Windows, which is [u8] -> Wtf8 -> Slice -> OsStr -> Path.

I *could* just coerce an empty u8 slice to a path, but that makes it harder to understand the conversion that's actually happening.

2017-02-13 22:43 UTC, aturon commented
Alright, given that the `transmute`s appear necessary, let's go ahead and land this!

@bor: r+

2017-02-13 22:45 UTC, aturon commented
@bors: r+

2017-02-14 04:34 UTC, frewsxcv commented
@bors r-

This fails to compile on Windows: https://ci.appveyor.com/project/rust-lang/rust/build/1.0.1944/job/cu5i3oo7m5dq2hbg

2017-02-14 19:19 UTC, clarcharr commented
Should be working now.

2017-02-14 20:33 UTC, alexcrichton commented
@bors: r=aturon

2017-02-15 13:01 UTC, merged

2017-03-04 04:34 UTC, jonhoo commented
Out of curiosity, why is `into_boxed_c_str` behind a feature flag for now?

2017-03-04 05:19 UTC, clarcharr commented
@jonhoo, by protocol a tracking issue is opened for every new feature. So you'll have to wait until this goes stable for that to happen.

2017-03-04 05:20 UTC, clarcharr commented
I also realised that I never made a tracking issue for this, so, feel free to open a PR to add one in so that this can be nominated faster.