[MIR] Implement Inlining
rust-lang/rust pull request #39648
Opened 2017-02-08 17:35 UTC by Aatch

Fairly basic implementation of inlining for MIR. Uses conservative
heuristics for inlining.

Doesn't handle a number of cases, but can be extended later. This is basically the same as the previous inlining PR, but without the span-related changes (as the bugs it was dealing with have since been fixed).

/cc @rust-lang/compiler

2017-02-08 17:35 UTC, rust-highfive commented
r? @pnkfelix

(rust_highfive has picked a reviewer for you, use r? to override)

2017-02-08 18:05 UTC, nagisa commented on src/librustc/ty/util.rs
>          tcx.layout_depth.set(depth+1);
Perhaps it would make sense to have some sort of guard for this instead?

2017-02-08 18:20 UTC, eddyb commented on src/librustc/ty/util.rs
>          tcx.layout_depth.set(depth+1);
Eh.

2017-02-16 09:40 UTC, Aatch commented on src/librustc/mir/mod.rs
> +#[derive(Clone, RustcEncodable, RustcDecodable, Debug)]
It's required for the `TypeFoldable` impl.

2017-02-16 09:41 UTC, Aatch commented on src/librustc/ty/mod.rs
> +    pub fn maybe_item_mir(self, did: DefId) -> Option<Ref<'gcx, Mir<'gcx>>> {
Not all functions have a MIR available and `item_mir` panics if there isn't a MIR available for that def_id.

2017-02-16 09:48 UTC, Aatch commented on src/librustc_mir/transform/inline.rs
> +                if let Some(mir) = self.tcx.maybe_item_mir(def_id) {
Being a local doesn't mean a MIR is available. The obvious case is intrinsics, since you can define those locally.

2017-02-16 09:51 UTC, Aatch commented on src/librustc_mir/transform/inline.rs
> +            let id = if let Some(id) = self.tcx.hir.as_local_node_id(def_id) {
I need the node id anyway, this combines that check.

2017-02-16 19:13 UTC, nikomatsakis commented on src/librustc/mir/mod.rs
> +            SetDiscriminant { ref lvalue, .. } |
+1

2017-02-21 02:12 UTC, mrhota reviewed
Several comments from the original PR should probably be addressed here, like [these.](https://github.com/rust-lang/rust/pull/36593#issuecomment-249870813)

The code lacks descriptions of approach or rationale. I get the impression (from the previous PR) that you intend for this code to be a kind of first strike at this problem. There are lots of details here, and it's hard to work out what's going on when there's not even a high-level description of how this pass works (or should work).

Moreover, it'd be nice to have tests verifying the efficacy of this new pass. Performance comparisons would be nice, too, since you mentioned improvements in the previous PR.

2017-02-21 21:00 UTC, eddyb requested changes
r=me with comments addressed (mine and others')

2017-02-21 21:00 UTC, eddyb commented on src/librustc_driver/driver.rs
> +        passes.push_pass(box mir::transform::inline::Inline);
That comment is about line 1031, i.e. nothing below the comment can invalidate it.

2017-02-21 21:00 UTC, eddyb commented on src/librustc_mir/callgraph.rs
> +        for def_id in def_ids {
Need to filter by `.is_local()`, cross-crate MIR should always be inspected on-demand (and not by accident).

2017-02-21 21:00 UTC, eddyb commented on src/librustc_mir/transform/inline.rs
> +const UNKNOWN_SIZE_COST : usize = 10;
Pretty sure the accepted style doesn't have a space before `:`.

2017-02-21 21:00 UTC, eddyb commented on src/librustc_mir/transform/inline.rs
> +                TerminatorKind::DropAndReplace { ref location, target, unwind, .. } => {
You shouldn't be seeing `DropAndReplace` anymore at this point.

2017-02-21 21:00 UTC, eddyb commented on src/librustc_mir/transform/inline.rs
> +            TerminatorKind::SwitchInt { ref mut targets, .. } => {
Need to rebase I suppose.

2017-02-21 21:00 UTC, eddyb commented on src/librustc_mir/transform/inline.rs
> +            TerminatorKind::DropAndReplace { ref mut target, ref mut unwind, .. } => {
Again, `DropAndReplace` shouldn't show up anymore at this point.

2017-02-21 21:38 UTC, nikomatsakis commented
@mrhota 

> The code lacks descriptions of approach or rationale. 

I agree this would make the code stronger. At the same time, I don't want to raise the bar too high for this patch -- I'm afraid it will bitrot like last time, and I think I'd rather have something in-tree with which we can iterate than nothing (particularly since it is not enabled by default). It feels like we need to get a series of quality benchmarks and start tuning these MIR optimizations, and documenting the results of that tuning. Trying to divine rules in advance without benchmarks feels risky.

2017-02-21 22:00 UTC, mrhota commented on src/librustc_driver/driver.rs
> +        passes.push_pass(box mir::transform::inline::Inline);
ok, I thought it might refer to what is now line 1035

2017-03-01 19:56 UTC, mrhota commented
@Aatch ping?

2017-03-01 20:30 UTC, arielb1 commented on src/librustc_mir/transform/inline.rs
> +                // borrow of the lvalue and pass the destination as `*temp` instead.
I thought the semantics was that any such `*i` is "borrow-locked" for the duration of the call, so any unexpected assignments during function call evaluation result in UB (certainly, MIR construction always copies indexes to a temporary).

2017-03-02 18:13 UTC, nikomatsakis commented
**Somebody** ought to rebase this =)

2017-03-09 02:36 UTC, mrhota commented
@Aatch ping again... 😦

2017-03-10 02:09 UTC, eddyb commented
@bors r+

2017-03-10 03:22 UTC, eddyb approved these changes

2017-03-10 10:48 UTC, eddyb commented
@bors retry
* appveyor llvm build failed

2017-03-10 13:43 UTC, eddyb commented
@bors retry
* linking LLVM failed

2017-03-10 15:43 UTC, alexcrichton commented
@bors: retry

(prioritizing rollup)

2017-03-10 15:50 UTC, alexcrichton commented
@bors: retry 

(prioritizing rollup)

2017-03-11 10:29 UTC, merged