Rust Book: Generics: Resolving ambiguities
rust-lang/rust pull request #39748
Opened 2017-02-11 22:06 UTC by Rufflewind

- Add a small section to generics.md to explain how ambiguities in type inference can be resolved using the `::<>` syntax.
- Add links from syntax-index.md and iterators.md.
- Minor edits to iterators.md and structs.md.

2017-02-11 22:07 UTC, rust-highfive commented
r? @steveklabnik

(rust_highfive has picked a reviewer for you, use r? to override)

2017-02-12 03:11 UTC, steveklabnik commented
Hey @Rufflewind , thanks for this! I am not going to have time to review this PR until Monday; sorry about that! I also wanted to make you aware of https://github.com/rust-lang/rust/pull/39633; if it lands, your PR may have to be rebased, but luckily, the only changes are moving the files into a `src` directory, so it shouldn't be too tough.

Maybe someone else will be able to review in the meantime, but if not, you'll hear from me in a few days 😄

2017-02-12 03:58 UTC, Rufflewind commented
Alright, thanks for the heads up!

2017-02-20 02:10 UTC, steveklabnik requested changes
Hey there! I'm so sorry that this took me a _lot_ longer than expected. I have one issue here about the tests failing, but other than that, this looks good to go, thank you!

2017-02-20 02:10 UTC, steveklabnik commented on src/doc/book/src/generics.md
> +```rust
https://travis-ci.org/rust-lang/rust/jobs/201806410#L2417

this line needs an `,ignore` after the `rust`.

2017-02-20 03:25 UTC, Rufflewind commented
Updated.

2017-02-20 15:05 UTC, steveklabnik approved these changes

2017-02-20 15:06 UTC, steveklabnik commented
@bors: r+ rollup

thanks! Sorry again about the delay.

2017-02-20 17:32 UTC, merged