Release notes for 1.16
rust-lang/rust pull request #39835
Opened 2017-02-15 02:54 UTC by brson

[Rendered](https://github.com/brson/rust/blob/relnotes/RELEASES.md)

2017-02-15 02:54 UTC, rust-highfive commented
r? @aturon

(rust_highfive has picked a reviewer for you, use r? to override)

2017-02-15 03:02 UTC, sanxiyn requested changes

2017-02-15 03:02 UTC, sanxiyn commented on RELEASES.md
> +[38274]: https://github.com/rust-lang/rust/pull/
Mistake here?

2017-02-15 03:46 UTC, seppo0010 commented on RELEASES.md
> +* [`IpAddr` implements `From<Ipv4Adder>` and `From<Ipv6Addr>`][38327]
`Ipv4Addr`?

2017-02-15 06:02 UTC, petrochenkov commented on RELEASES.md
> +* Lifetimes in statics ad consts default to `'static`. [RFC 1623]
typo ad -> and

2017-02-15 06:17 UTC, petrochenkov commented on RELEASES.md
> +* [Candidates for type suggestions draw from more sources][38927]
This is an underestimation :)
It's not only type suggestions, Levenshtein based typo suggestions now work in most places, while previously they worked only for fields and *sometimes* for local variables. Together the overhaul of "no resolution"/"unexpected resolution" errors (https://github.com/rust-lang/rust/pull/38154) they result in large and systematic improvement in resolution diagnostics.

2017-02-15 07:30 UTC, KalitaAlexey commented on RELEASES.md
> +* [Document all workspace members with `document --all`][cargo/3515]
It should be `doc --all`

2017-02-15 15:46 UTC, alexcrichton commented on RELEASES.md
> +* [`Add `--dep-info` flag to output build dependencies compatible with
Stray leading backtick here I believe

2017-02-15 15:47 UTC, alexcrichton commented on RELEASES.md
> +* [`Add `--dep-info` flag to output build dependencies compatible with
Oh actually and this isn't a flag to cargo (despite the PR title), it happens automatically for all compilations now.

2017-02-15 15:48 UTC, alexcrichton commented
r=me with typos and such fixed

2017-02-15 15:59 UTC, wesleywiser commented on RELEASES.md
> +* [crates.io will display categories listen in Cargo.toml][cargo/3301]
listen -> listed in?

2017-02-15 19:45 UTC, brson commented on RELEASES.md
> +* [Candidates for type suggestions draw from more sources][38927]
Oh, oops I meant to say __"typo"__ suggestions. But I'll use your text. Thanks.

2017-02-15 19:48 UTC, brson commented on RELEASES.md
> +* [crates.io will display categories listen in Cargo.toml][cargo/3301]
lol wow. thanks for the review

2017-02-15 20:00 UTC, brson commented
Updated.

2017-02-15 20:05 UTC, eddyb commented on RELEASES.md
> +  metadata-only builds.
Isn't the most notable user `cargo check`, which can use `--emit=metadata` to check several crates quickly?

2017-02-15 22:28 UTC, killercup commented on RELEASES.md
> +* [The `armv7-linux-androideabi` target no lenger enables NEON
s/lenger/longer

2017-02-15 22:43 UTC, brson commented on RELEASES.md
> +  metadata-only builds.
hm, is this the first release with `cargo check`?

2017-02-15 22:48 UTC, brson commented on RELEASES.md
> +* [crates.io will display categories listed in in Cargo.toml][cargo/3301]
"in in"

2017-02-15 22:54 UTC, eddyb commented on RELEASES.md
> +  metadata-only builds.
cc @nrc

2017-02-15 23:04 UTC, alexcrichton commented on RELEASES.md
> +  metadata-only builds.
Yeah, Rust 1.16.0 is the first release with `cargo check`

2017-02-21 02:30 UTC, sanxiyn approved these changes

2017-02-22 17:49 UTC, brson commented
Still needs to be updated for feedback.

2017-02-27 13:55 UTC, ishitatsuyuki commented
No performance improvements? :o

2017-03-09 21:27 UTC, brson commented
@ishitatsuyuki Sadly I didn't see anything of note, and the benchmarking service is down, so there's no data to draw from.

2017-03-09 21:36 UTC, brson commented
@bors r+

2017-03-10 10:11 UTC, merged

2017-03-10 22:31 UTC, golddranks commented
Did omitting `'static` in statics land, though? I got the impression from https://github.com/rust-lang/rust/issues/35897#issuecomment-281460966 that it wasn't backported in the end!

2017-03-12 21:24 UTC, Aaronepower commented
Also this mentions `writeln!, like println!, now accepts a form with no string or formatting arguments, to just print a newline`, however this is currently available in latest stable.

2017-03-13 22:58 UTC, llogiq commented
It wasn't.