Add Documentation for Custom Attributes and Error Reporting in Procedural Macros
rust-lang/rust pull request #39845
Opened 2017-02-15 12:03 UTC by JDemler

This fixes #39821 .

I'm not sure if the process of how to access custom attributes should be documented as well.
But I feel, that this should rather be documented in `syn`

2017-02-15 12:03 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @steveklabnik (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-02-15 18:28 UTC, steveklabnik requested changes
I have some small formatting comments, but looks good to me!

2017-02-15 18:28 UTC, steveklabnik commented on src/doc/book/src/procedural-macros.md
> +In some cases it might make sense to allow users some kind of configuration.
could you put a newline above this line, please?

2017-02-15 18:28 UTC, steveklabnik commented on src/doc/book/src/procedural-macros.md
> +Let's assume that we do not want to accept `Enums` as input to our custom derive method.
can you add a newline above this line?

2017-02-15 18:28 UTC, steveklabnik commented on src/doc/book/src/procedural-macros.md
> +
could you delete one of these newlines?

2017-02-16 12:26 UTC, JDemler commented on src/doc/book/src/procedural-macros.md
> +
Do you mean the newline before the heading or after the code block?

2017-02-16 20:01 UTC, steveklabnik commented on src/doc/book/src/procedural-macros.md
> +
there should only be one newline, like this:

```
Multiple attributes can be specified that way.

## Raising Errors
```

2017-02-16 20:01 UTC, steveklabnik commented on src/doc/book/src/procedural-macros.md
> +
(that is, before the heading)

2017-02-16 20:09 UTC, JDemler commented on src/doc/book/src/procedural-macros.md
> +
So the `fixed whitespace issues`-commit fixed this issue, correct?

2017-02-17 07:40 UTC, xen0n reviewed
Some minor nits, but the snippets are LGTM.

2017-02-17 07:40 UTC, xen0n commented on src/doc/book/src/procedural-macros.md
> +But how to we tell the user, that we do not accept `Enums`.
* `how to` -> `how do`
* trailing `.` -> `?`

2017-02-17 07:40 UTC, xen0n commented on src/doc/book/src/procedural-macros.md
> +The idiomatic was to report errors in procedural macros is to panic:
`was` -> `way`

2017-02-17 07:40 UTC, xen0n commented on src/doc/book/src/procedural-macros.md
> +The compiler needs to know that we handle this attribute and to not respond with an error.
`we handle` -> `we're handling`

2017-02-17 07:40 UTC, xen0n commented on src/doc/book/src/procedural-macros.md
> -We've done it!
Removing this for the next section seems to make the previous section truncated, IMO removal is not needed.

2017-02-17 07:40 UTC, xen0n commented on src/doc/book/src/procedural-macros.md
> +For our example the user might want to overwrite the name that is printed in the `hello_world()` method.
`For example, ...` is enough for introducing the example.

2017-02-17 07:40 UTC, xen0n commented on src/doc/book/src/procedural-macros.md
> +This is done in the `hello-world-derive`-crate by adding `attributes` to the `proc_macro_derive` attribute:
The hyphen before `crate` should be replaced by a space.

2017-02-17 07:40 UTC, xen0n commented on src/doc/book/src/procedural-macros.md
> +Let's assume that we do not want to accept `Enums` as input to our custom derive method.
The use of `Enums` is over-emphasis, IMO just `enums` or `enumerations` without the inline code block is enough.

2017-02-19 17:17 UTC, JDemler commented
Thanks for the nits. They should be resolved now.

2017-02-24 04:00 UTC, steveklabnik approved these changes

2017-02-24 04:00 UTC, steveklabnik commented
@bors: r+ rollup

thank you!

2017-02-25 03:10 UTC, merged

2018-04-10 21:58 UTC, gilescope commented
Hoping feedback is always welcome: A paragraph pointing to syn with a little example of how to access HelloWorldName = "the best Pancakes" would be really _really_ appreciated on that page. Its not clear from the TokenStream input type - I looked here https://doc.rust-lang.org/proc_macro/struct.TokenStream.html and find no mention of attributes.

2018-07-24 15:32 UTC, trsh commented
It's still not written how to read `HelloWorldName` in macro fn