[12/12] On-demand type-checking, const-evaluation, MIR building & const-qualification.
rust-lang/rust pull request #40008
Opened 2017-02-21 18:31 UTC by eddyb

_This is the last of a series ([prev](https://github.com/rust-lang/rust/pull/38813)) of patches designed to rework rustc into an out-of-order on-demand pipeline model for both better feature support (e.g. [MIR-based](https://github.com/solson/miri) early constant evaluation) and incremental execution of compiler passes (e.g. type-checking), with beneficial consequences to IDE support as well.
If any motivation is unclear, please ask for additional PR description clarifications or code comments._

<hr>

As this contains all of the changes that didn't fit neatly into other PRs, I'll be elaborating a bit:

### User-facing changes
* when determining whether an `impl Trait` type implements an auto-trait (e.g. `Send` or `Sync`), the function the `impl Trait` came from has to be inferred and type-checking, disallowing cycles
  * this results from not having an obvious place to put the "deferred obligation" in on-demand atm
  * while we could model side-effects like that and "post-processing passes" better, it's still more limiting than being able to know the result in the original function (e.g. specialization) *and* there are serious problems around region-checking (if a `Send` impl required `'static`, that wasn't enforced)
* early const-eval requires type-checking and const-qualification to be performed first, which means:
  * you get the intended errors before (if any) constant evaluation error that is simply fallout
  * associated consts should always work now, and `const fn` type parameters are properly tracked
    * don't get too excited, array lengths still can't depend on type parameters
* #38864 works as intended now, with `Self` being allowed in `impl` bounds
* #32205 is largely improved, with associated types being limited to "exact match" `impl`s (as opposed to traversing the specialization graph to resolve unspecified type parameters to their defaults in another `impl` or in the `trait`) *while* checking for overlaps building the specialization graph for that trait - once all the trait impls' have been checked for coherence (including ahead-of-time/on-demand), it's uniform
* [crater report](https://gist.github.com/eddyb/bbb869072468c7e08d6d808e75938051) looks clean (aside from `clippy` which broke due to `rustc` internal changes)

### Compiler-internal changes
* `ty::Generics`
  * no longer contains the actual type parameter defaults, instead they're associated with the type parameter's `DefId`, like associated types in a trait definition
    * this allows computing `ty::Generics` as a leaf (reading only its own HIR)
  * holds a mapping from `DefIndex` of type parameters to their indices
* `ty::AdtDef`
  * only tracks `#[repr(simd)]` in its `ReprOptions` `repr` field
  * doesn't contain `enum` discriminant values, but instead each variant either refers to either an explicit value for its discriminant, or the distance from the last explicit discriminant, if any
    * the `.discriminants(tcx)` method produces an iterator of `ConstInt` values, looking up explicit discriminants in a separate map, if necessary
    * this allows computing `ty::AdtDef` as a leaf (reading only its own HIR)
* Small note: the two above (`Generics`, `AdtDef`), `TraitDef` and `AssociatedItem` should probably end up as part of the HIR, eventually, as they're trivially constructed from it
* `ty::FnSig`
  * now also holds ABI and unsafety, alongside argument types, return type and C variadicity
  * `&ty::BareFnTy` and `ty::ClosureTy` have been replaced with `PolyFnSig = Binder<FnSig>`
    * `BareFnTy` was interned and `ClosureTy` was treated as non-trivial to `Clone` because they had a `PolyFnSig` and so used to contain a `Vec<Ty>` (now `&[Ty]`)
* `ty::maps`
  * all the `DepTrackingMap`s have been grouped in a structure available at `tcx.maps`
  * when creating the `tcx`, a set of `Providers` (one `fn` pointer per map) is required for the local crate, and one for all other crates (i.e. metadata loading), `librustc_driver` plugging the various crates (e.g. `librustc_metadata`, `librustc_typeck`, `librustc_mir`) into it
  * when a map is queried and the value is missing, the appropriate `fn` pointer from the `Providers` of that crate is called with the `TyCtxt` and the key being queried, to produce the value on-demand
* `rustc_const_eval`
  * demands both `typeck_tables` and `mir_const_qualif` (in preparation for miri)
  * tracks `Substs` in `ConstVal::Function` for `const fn` calls
  * returns `TypeckError` if type-checking has failed (or cases that can only be reached if it had)
    * this error kind is never reported, resulting in less noisy/redundant diagnostics 
* on-demand has so far been hooked up to:
  * `rustc_metadata::cstore_impl`: `ty`, `generics`, `predicates`, `super_predicates`, `trait_def`, `adt_def`, `variances`, `associated_item_def_ids`, `associated_item`, `impl_trait_ref`, `custom_coerce_unsized_kind`, `mir`, `mir_const_qualif`, `typeck_tables`, `closure_kind`, `closure_type`
  * `rustc_typeck::collect`: `ty`, `generics`, `predicates`, `super_predicates`, `type_param_predicates`, `trait_def`, `adt_def`, `impl_trait_ref`
  * `rustc_typeck::coherence`: `coherent_trait`, `coherent_inherent_impls`
  * `rustc_typeck::check`: `typeck_tables`, `closure_type`, `closure_kind`
  * `rustc_mir::mir_map`: `mir`
  * `rustc_mir::transform::qualify_consts`: `mir_const_qualif`

2017-02-21 18:31 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2017-02-22 21:43 UTC, nikomatsakis requested changes
This looks amazing as usual. My concern is mainly about the dependency graph management. The handling here is definitely dubious, but maybe we want to address it in follow-up PRs.

2017-02-22 21:43 UTC, nikomatsakis commented on src/librustc_mir/transform/qualify_consts.rs
> +        let def_ids = tcx.maps.mir.borrow().keys();
it is pretty dubious to iterate over keys -- seems like we should talk over this -- but it may make sense to land the PR and then do a follow-up

2017-02-22 23:32 UTC, eddyb commented on src/librustc/ty/mod.rs
> +        if self.flags.get().intersects(AdtFlags::IS_DTOR_VALID) {
This is pre-existing though. The correct solution IMO is to query the trait system but fixing all the users is a bit tricky.

2017-02-22 23:33 UTC, eddyb commented on src/librustc_mir/transform/qualify_consts.rs
> +        let def_ids = tcx.maps.mir.borrow().keys();
Yeah things like this should probably be switched to iterate over bodies instead.

2017-02-23 16:34 UTC, nikomatsakis commented on src/librustc/ty/mod.rs
> +        if self.flags.get().intersects(AdtFlags::IS_DTOR_VALID) {
ah, it's pre-existing? ok, I guess we can live with it then. I thought I closed up the cells in there, but I guess not.

2017-02-23 19:56 UTC, nikomatsakis commented
@eddyb you seen the travis failures?

2017-02-23 20:44 UTC, nikomatsakis commented
@eddyb ok, so to summarize what we said on IRC (and "for the record"):

- The wacky dep-graph stuff is pre-existing, I'll try to prioritize fixing it.
- The `Default` trait seems me as risky, but for now we'll bias towards "keep going with compilation, even if you get weird derived errors". We can either patch problems one by one, or try to remove the `Default` trait impl and then make the default cases abort if we don't have a good recovery for them.

So -- yeah, r=me, let's just land this thing already.

2017-02-24 07:25 UTC, eddyb commented
@bors r=nikomatsakis

2017-02-25 09:44 UTC, eddyb commented
@bors r=nikomatsakis

2017-02-25 15:07 UTC, eddyb commented
Note to self: never use the GitHub conflict resolution UI, it makes merge commits.

2017-02-25 15:11 UTC, eddyb commented
@bors r=nikomatsakis

2017-02-25 15:50 UTC, eddyb commented
@bors r=nikomatsakis

2017-02-25 16:09 UTC, eddyb commented
@bors r=nikomatsakis

2017-02-25 16:10 UTC, eddyb commented
@bors p=1 (this will rot real fast once other PRs start merging again)

2017-02-25 16:10 UTC, eddyb commented
@bors force

2017-02-25 16:37 UTC, eddyb commented
@bors r=nikomatsakis

2017-02-25 19:44 UTC, eddyb commented
> The job exceeded the maximum time limit for jobs, and has been terminated.

😞 Is this my fault, making `rustc` too slow?

2017-02-25 20:29 UTC, eddyb commented
@bors retry
* maybe the timeout was spurious

2017-02-25 20:41 UTC, eddyb commented
@bors retry
* OSX... something. network error?

2017-02-25 21:47 UTC, frewsxcv commented
@bors p=20

2017-02-26 00:55 UTC, eddyb commented
Welp, it was me: I compared the log with a previous build and it went from `2:22:27` to `2:51:53`.
Worst of it AFAICT is `compile-fail`: `201.065` seconds to `661.318` seconds.

2017-02-26 07:15 UTC, eddyb commented
I can't reproduce a slowdown locally, so I'm still confused.

2017-02-26 08:00 UTC, eddyb commented
@bors retry
* it must be spurious, *riiight?*

2017-02-27 12:20 UTC, eddyb commented
FWIW, investigation is ongoing in #40114.

2017-02-28 06:40 UTC, eddyb commented
@bors r=nikomatsakis

Indeed, it appears those filemaps were adding `3MB` to `libstd`'s `3.5MB` - that's a lot of them!

As to what this PR does differently: when doing *any* request without an explicit `Span` (so all of the `tcx` methods, e.g. `tcx.item_generics(def_id)`, `tcx.item_type(def_id)`, etc.), the `Span` of the `DefId` was being computed for the "on-demand cycle-check stack", which would also happen for cross-crate `DefId`s.

Now, that may seem expensive, but *it's empirically unmeasurable* (except maybe this PR would speed other things up so what I'm seeing is speedup + slowdown => neutral), *unless* those cross-crate `Span`s require reading all the cross-crate filemaps *and* there were *a lot* of them (from save-analysis).

2017-02-28 10:00 UTC, merged