Implement non-capturing closure to fn coercion
rust-lang/rust pull request #40025
Opened 2017-02-22 02:20 UTC by est31

Still WIP

Implements non capturing closure coercion ([RFC 1558](https://github.com/rust-lang/rfcs/blob/master/text/1558-closure-to-fn-coercion.md)).

cc tracking issue #39817

TODO:

* more tests
* feature gating

2017-02-22 02:20 UTC, rust-highfive commented
r? @pnkfelix

(rust_highfive has picked a reviewer for you, use r? to override)

2017-02-22 02:20 UTC, est31 commented
r? @eddyb

2017-02-23 21:32 UTC, est31 commented
@eddyb Its ready for review!

2017-02-23 22:31 UTC, eddyb requested changes

2017-02-23 22:31 UTC, eddyb commented on src/librustc_trans/mir/constant.rs
> +                                let substs = Substs::for_item(tcx,
You can just make `Substs` by doing `tcx.mk_substs([operand.ty, input.skip_binder()].iter().cloned())` IIRC.

2017-02-23 22:31 UTC, eddyb commented on src/librustc_trans/mir/rvalue.rs
> +                                let substs = Substs::for_item(bcx.tcx(),
Same here.

2017-02-23 22:31 UTC, eddyb commented on src/librustc_typeck/check/coercion.rs
> +        let node_id_a :NodeId = self.tcx.hir.as_local_node_id(def_id_a).unwrap();
Type annotations shouldn't be needed.

2017-02-23 22:31 UTC, eddyb commented on src/librustc_typeck/check/coercion.rs
> +                        TypeVariants::TyTuple(params, _) => {
`ty::TyTuple`

2017-02-23 22:31 UTC, eddyb commented on src/librustc_typeck/check/coercion.rs
> +                let converted_sig = sig.input(0).map_bound(|v| {
I meant `sig.map_bound`. Because that lets you avoid `skip_binder` on output too.

2017-02-23 22:31 UTC, eddyb commented on src/test/compile-fail/closure-no-fn.rs
> +    let foo :fn(u8) -> u8 = |v: u8| { a += v; a };
`let x :T` is unidiomatic, should be `let x: T`.

2017-02-23 22:31 UTC, eddyb commented on src/test/run-pass/closure-to-fn-coercion.rs
> +    assert_eq!({BAR[4](&mut a); a }, 10);
`{` should be followed by a space just like `}` should be preceded by one.

2017-02-24 00:08 UTC, eddyb commented
@bors r+

2017-02-25 10:08 UTC, eddyb approved these changes

2017-02-25 15:00 UTC, merged