Issue #39688 - Help people find String::as_bytes() for UTF-8
rust-lang/rust pull request #40226
Opened 2017-03-03 06:29 UTC by jdhorwitz

Added in links for the inverse functions so people will know that as_bytes() is the inverse of from_utf8() and vice versa.
?r @steveklabnik

2017-03-03 06:29 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @brson (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-03-03 13:53 UTC, steveklabnik requested changes

2017-03-03 13:53 UTC, steveklabnik commented on src/libcollections/string.rs
> +            .expect("a Display implementation return an error unexpectedly");
this change is unrelated, but it's also good; you should probably remove it since it has nothing to do with this issue.

2017-03-03 13:54 UTC, steveklabnik commented
This looks great @jdhorwitz ! Two things:

1. you haven't set up your git info to connect with your github account; you probably will want to do that. You can tell because it has the generic avatar instead of your github avatar.
2. there was an extra little change in there
3. When you fix that, could you squash the commits together?

Thanks! And as before, if you need help with any of this, just ping me on IRC 😄

2017-03-03 17:04 UTC, steveklabnik approved these changes

2017-03-03 17:04 UTC, steveklabnik commented
@bors: r+ rollup

thank you!

2017-03-04 23:39 UTC, steveklabnik commented
@bors: r+ rollup

2017-03-05 02:18 UTC, steveklabnik commented
@bors: retry

2017-03-05 12:48 UTC, GuillaumeGomez commented
@bors: r-

2017-03-05 12:49 UTC, GuillaumeGomez requested changes

2017-03-05 12:49 UTC, GuillaumeGomez commented on src/libcollections/string.rs
> +    /// The inverse of this method is [`as_bytes`](#method.as_bytes).
Please don't use this link syntax. Move the url below and just keep `[as_bytes]` here.

2017-03-05 12:49 UTC, GuillaumeGomez commented on src/libcollections/string.rs
> +    /// The inverse of this method is [`from_utf8`](#method.from_utf8).
Same comment.

2017-03-05 15:15 UTC, steveklabnik commented on src/libcollections/string.rs
> +    /// The inverse of this method is [`as_bytes`](#method.as_bytes).
Ah yeah, good call!

2017-03-05 16:16 UTC, jdhorwitz commented
Changes pushed, thank you for the feedback!

2017-03-06 01:04 UTC, frewsxcv commented
@bors r+ rollup

2017-03-06 03:06 UTC, steveklabnik commented
@bors: retry

looks spurious

On Sun, Mar 5, 2017 at 9:42 PM, bors <notifications@github.com> wrote:

> 💔 Test failed - status-travis
> <https://travis-ci.org/rust-lang/rust/builds/208053034>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/40226#issuecomment-284289412>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AABsitKFTs2yhgVzFtG08ZgxyZMhXr_Eks5ri3J_gaJpZM4MR6PC>
> .
>

2017-03-06 16:50 UTC, alexcrichton commented
@bors: retry

* presumed sccache failure https://github.com/rust-lang/rust/issues/40240

2017-03-09 10:41 UTC, merged