Improve the style of the sidebar in rustdoc output
rust-lang/rust pull request #40265
Opened 2017-03-04 18:59 UTC by wesleywiser

Makes the sidebar a light grey and highlights the currently viewed item in the sidebar more prominently. 

All visual design credit goes to @johnwhelchel (#37856)

Sample screenshots:

![screen shot 2017-03-04 at 12 29 48 pm](https://cloud.githubusercontent.com/assets/831192/23580829/db6c26c2-00d6-11e7-8d89-822e25ba79f0.png)

![screen shot 2017-03-04 at 12 30 10 pm](https://cloud.githubusercontent.com/assets/831192/23580828/db69eeca-00d6-11e7-9f89-1e06fd3bf098.png)

![screen shot 2017-03-04 at 12 30 31 pm](https://cloud.githubusercontent.com/assets/831192/23580830/db6d00ce-00d6-11e7-89ca-cd03e148a121.png)

2017-03-04 18:59 UTC, rust-highfive commented
r? @steveklabnik

(rust_highfive has picked a reviewer for you, use r? to override)

2017-03-05 00:09 UTC, steveklabnik commented
@bors: r+ rollup

thanks!

2017-03-05 01:46 UTC, wesleywiser commented
@steveklabnik rebased

2017-03-05 04:20 UTC, frewsxcv commented
As far as I can tell, the build orchestration tool (powering bors) is currently broken, which is causing everything to be incorrectly errored as a merge conflict. We'll need to wait for that to get fixed before approving it again.

2017-03-05 04:22 UTC, wesleywiser commented
Thanks! I was a little confused why my local repo didn't report a merge
conflict.

On Sat, Mar 4, 2017, 11:20 PM Corey Farwell <notifications@github.com>
wrote:

> As far as I can tell, the build orchestration tool (powering bors) is
> currently broken, which is causing everything to be incorrectly errored as
> a merge conflict. We'll need to wait for that to get fixed before approving
> it again.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/40265#issuecomment-284204391>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAyu2LlKvHJRE0C0ZockUxaXwp9YsLg7ks5rijgdgaJpZM4MTLZI>
> .
>

2017-03-05 12:47 UTC, GuillaumeGomez requested changes

2017-03-05 12:47 UTC, GuillaumeGomez commented on src/librustdoc/html/static/rustdoc.css
> + 	background-color: #F1F1F1;
color changes shouldn't be in this file but in `src/librustdoc/html/static/styles/main.css`.

2017-03-05 12:47 UTC, GuillaumeGomez commented on src/librustdoc/html/static/rustdoc.css
> +	background-color: white;
Same for this one.

2017-03-05 12:47 UTC, GuillaumeGomez commented on src/librustdoc/html/static/rustdoc.css
> +	border: black 1px solid;
Same for this one.

2017-03-05 12:47 UTC, GuillaumeGomez commented on src/librustdoc/html/static/styles/main.css
> +    background-color: #fff;
Good!

2017-03-06 02:00 UTC, wesleywiser commented
@GuillaumeGomez Fixed

2017-03-06 11:29 UTC, GuillaumeGomez requested changes
Just one last change and it's good!

2017-03-06 11:29 UTC, GuillaumeGomez commented on src/librustdoc/html/static/rustdoc.css
> +	border-width: 1px;
Could be just:

```css
border: 1px solid;
```

Instead of:

```css
border-width: 1px;
border-style: solid;
```

2017-03-06 23:23 UTC, wesleywiser commented on src/librustdoc/html/static/rustdoc.css
> +	border-width: 1px;
Thanks! I didn't even know you could do that.

2017-03-06 23:24 UTC, wesleywiser commented
@GuillaumeGomez Fixed

2017-03-07 15:09 UTC, GuillaumeGomez approved these changes

2017-03-07 15:09 UTC, GuillaumeGomez commented
Thanks!

@bors: r+ rollup

2017-03-09 10:41 UTC, merged