Papercut
rust-lang/rust pull request #40312
Opened 2017-03-07 05:10 UTC by jdhorwitz

r? @steveklabnik

2017-03-07 05:10 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @steveklabnik (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-03-07 14:42 UTC, steveklabnik commented
Hey @jdhorwitz ! This looks like a start, but you have the commit from your other PR in here as well. Ping me on IRC if you need help sorting that out!

Also, `rustfmt` has betrayed you again 😄

2017-03-08 03:59 UTC, steveklabnik requested changes

2017-03-08 03:59 UTC, steveklabnik commented on src/libstd/process.rs
> +    /// So instead of:
this shouldn't be on a newline, just put it after the previous sentence

2017-03-08 03:59 UTC, steveklabnik commented on src/libstd/process.rs
> +    /// usage would be:
an extra `///` above this would be good, so there's space below just like the space above

2017-03-08 04:07 UTC, jdhorwitz commented on src/libstd/process.rs
> +    /// So instead of:
Good catch, fixed!

2017-03-08 04:07 UTC, jdhorwitz commented on src/libstd/process.rs
> +    /// usage would be:
Fixed!

2017-03-08 04:18 UTC, jdhorwitz commented
r? @steveklabnik

2017-03-08 14:29 UTC, steveklabnik approved these changes

2017-03-08 14:29 UTC, steveklabnik commented
@bors: r+ rollup

2017-03-08 14:30 UTC, steveklabnik commented
@bors: r-

whoops, travis failure is legit for once.

@jdhorwitz you need to use

    ```ignore

on those examples, as they don't compile on their own

2017-03-08 23:25 UTC, jdhorwitz commented
r? @steveklabnik

2017-03-08 23:26 UTC, jdhorwitz commented
Fixed!, Thanks @steveklabnik

2017-03-08 23:42 UTC, steveklabnik commented
Looks great! Thanks again 😄 

@bors: r+ rollup

2017-03-09 11:26 UTC, arielb1 commented
@bors retry

2017-03-09 15:05 UTC, alexcrichton commented
@bors: retry

2017-03-09 16:50 UTC, pooyapeyravi commented
hi
thanks for help

2017-03-09 17:15 UTC, pooyapeyravi commented
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } 


Gmail p

On پنجشنبه, مارس 9, 2017, 14:56, Ariel Ben-Yehuda <notifications@github.com> wrote:


@bors retry

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub, or mute the thread.

2017-03-20 15:23 UTC, steveklabnik commented
@bors: r+ rollup

2017-03-21 19:34 UTC, merged