Document why `str.to_{lower,upper}case` return `String`
rust-lang/rust pull request #40335
Opened 2017-03-07 22:51 UTC by tbu-

Fixes #39201.

2017-03-07 22:51 UTC, rust-highfive commented
r? @sfackler

(rust_highfive has picked a reviewer for you, use r? to override)

2017-03-07 22:51 UTC, tbu- commented
CC @Havvy

2017-03-07 22:53 UTC, sfackler commented
r? @steveklabnik

2017-03-07 23:03 UTC, Havvy requested changes

2017-03-07 23:03 UTC, Havvy commented on src/libcollections/str.rs
> +    /// Since some characters can expand into multiple when changing the case,
I would say "multiple characters" instead of "multiple".

2017-03-07 23:03 UTC, Havvy commented on src/libcollections/str.rs
> +    /// Since some characters can expand into multiple when changing the case,
Likewise here.

2017-03-07 23:06 UTC, tbu- commented on src/libcollections/str.rs
> +    /// Since some characters can expand into multiple when changing the case,
Fixed.

2017-03-08 02:53 UTC, steveklabnik commented
@bors: r+ rollup

thanks!

2017-03-09 10:41 UTC, merged