Forbid conflicts between macros 1.0 exports and macros 2.0 exports
rust-lang/rust pull request #40509
Opened 2017-03-14 07:16 UTC by jseyfried

This PR forbids for conflicts between `#[macro_export]`/`#[macro_reexport]` macro exports and `pub use` macro exports. For example,
```rust
// crate A:
pub use macros::foo;
#[macro_export] macro_rules! foo { () => {} }
//^ This is allowed today, will be forbidden by this PR.

// crate B:
extern crate A; // This triggers a confusing error today.
use A::foo; // This could refer to refer to either macro export in crate A.
```

r? @nrc

2017-03-14 07:16 UTC, jseyfried commented
cc #35896 
cc @Sergio

2017-03-15 21:55 UTC, nrc requested changes
r=me either way

2017-03-15 21:55 UTC, nrc commented on src/librustc_resolve/lib.rs
> +    macro_exports: Vec<(Export, Span)>,
Could the span be added to Export?

2017-03-16 01:26 UTC, jseyfried commented on src/librustc_resolve/lib.rs
> +    macro_exports: Vec<(Export, Span)>,
Sure.

2017-03-16 03:09 UTC, jseyfried commented
@bors r=nrc

2017-03-21 21:03 UTC, bstrie commented
@bors r=nrc

2017-03-22 14:41 UTC, alexcrichton commented
@bors: retry

* failed to compile openssl -- https://github.com/rust-lang/rust/issues/40417

2017-03-23 02:30 UTC, merged