Represent function pointers in mir-constants as a Value instead of Item
rust-lang/rust pull request #40602
Opened 2017-03-17 15:17 UTC by oli-obk

r? @eddyb

2017-03-17 16:21 UTC, eddyb requested changes
LGTM except the hacks can be removed now!

2017-03-17 16:21 UTC, eddyb commented on src/librustc_trans/mir/constant.rs
> +                        // which would not work with MirConstContext.
I think this means it's a function-specific hack that can be removed.

2017-03-17 16:21 UTC, eddyb commented on src/librustc_trans/mir/constant.rs
> +                // Shortcut for zero-sized types
Same here.

2017-03-17 16:47 UTC, oli-obk commented
Gotta run, so I can't test the changes locally. let's see what travis says.

2017-03-17 17:02 UTC, eddyb approved these changes

2017-03-17 18:05 UTC, eddyb commented
@bors r+

2017-03-21 08:30 UTC, eddyb commented
You have a merge commit, please rebase properly.

2017-03-21 11:20 UTC, oli-obk commented
since the MIR-shim changes I can't figure out how to make this work.

2017-03-24 15:20 UTC, oli-obk commented
I applied the fixes as discussed in IRC. It works now.

2017-03-24 16:41 UTC, eddyb commented
@bors r+

2017-03-25 02:06 UTC, merged