Add helpful hint in io docs about how ? is not allowed in main()
rust-lang/rust pull request #40763
Opened 2017-03-23 17:23 UTC by pirate

This is my effort to help alleviate the confusion caused by the error message:
```rust
error[E0277]: the trait bound `(): std::ops::Carrier` is not satisfied
  --> hello_world.rs:72:5
   |
72 |     io::stdin().read_line(&mut d_input)?;
   |     ------------------------------------
   |     |
   |     the trait `std::ops::Carrier` is not implemented for `()`
   |     in this macro invocation
   |
   = note: required by `std::ops::Carrier::from_error`

error: aborting due to previous error
```
This has been discussed at length in https://github.com/rust-lang/rust/issues/35946, but I figured it would be helpful to mention in the docs.
Reading user input is one of the first things beginners will look up in the docs, so my thinking was they'd see this warning here and not have to deal with the tricky error message.

If you think this isn't the right place to put this in the docs, that's understandable, I'm open to suggestions for putting it elsewhere or removing it entirely.

2017-03-23 17:23 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @sfackler (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-03-23 17:26 UTC, sfackler commented
r? @steveklabnik

2017-03-23 17:40 UTC, steveklabnik requested changes
I have some small stylistic tweaks here, but adding this here makes sense to me, thanks :)

/cc @rust-lang/docs

2017-03-23 17:40 UTC, steveklabnik commented on src/libstd/io/mod.rs
> +//! Note that you cannot use the `?` operator in functions that do not return a `Result` (e.g. `main()`).
could you add a new `//!` line above this to give it some room to breathe?

also, this should be `main`, not `main()`, and `Result<T, E>` not `Result`

2017-03-23 17:40 UTC, steveklabnik commented on src/libstd/io/mod.rs
> +//! match io::stdin().read_line(&mut input) {
could you add a `//!` line above this one?

2017-03-23 17:44 UTC, pirate commented
Changes made 👍 thanks.

2017-03-23 18:03 UTC, pirate commented
This may not be worth adding now, considering the `?` in `main` issue may soon be fixed: https://github.com/rust-lang/rfcs/pull/1937 & https://internals.rust-lang.org/t/rfc-mentoring-opportunity-permit-in-main/4600.

2017-03-27 14:00 UTC, steveklabnik commented
Still has some tidy issues: https://travis-ci.org/rust-lang/rust/jobs/214345350#L566-L568


I'm still okay with landing it even if the other stuff is going to get better

2017-03-28 17:06 UTC, pirate commented
Hmm no trailing whitespace and lines are <= 80 char, not sure why the build is failing still.  The log is too long to display in the browser, so I couldn't see any error messages.

2017-03-28 17:17 UTC, frewsxcv commented
Looks like you'll need to add in the import.

```
[01:06:36] failures:
[01:06:36] 
[01:06:36] ---- io/mod.rs - io (line 157) stdout ----
[01:06:36] 	error[E0433]: failed to resolve. Use of undeclared type or module `io`
[01:06:36]  --> <anon>:6:1
[01:06:36]   |
[01:06:36] 6 | io::stdin().read_line(&mut input).unwrap();
[01:06:36]   | ^^^^^^^^^ Use of undeclared type or module `io`
[01:06:36] 
[01:06:36] error: aborting due to previous error(s)
[01:06:36] 
[01:06:36] thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc/session/mod.rs:203
[01:06:36] note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

2017-03-28 17:17 UTC, frewsxcv commented
> The log is too long to display in the browser, so I couldn't see any error messages.

For the record, you can press the 'Raw log' button in Travis CI to see the full log.

2017-03-28 17:29 UTC, pirate commented
Wow, I've never seen a linter run on doc example code before.  Didn't realize that **all** code snippets even in the docs must be complete and independently runnable.

2017-03-28 17:30 UTC, steveklabnik commented
Yup! You can control this with annotations, see here: https://doc.rust-lang.org/stable/book/documentation.html#documentation-as-tests

2017-03-31 18:29 UTC, steveklabnik approved these changes

2017-03-31 18:29 UTC, steveklabnik commented
@bors: r+ rollup

2017-04-01 03:37 UTC, merged