Update `Child` docs to not have a note section
rust-lang/rust pull request #40812
Opened 2017-03-25 03:31 UTC by mgattozzi

In #29370 it's noted that for "the Note shouldn't be one, and should come before
the examples." This commit changes the positioning of the section and removes
wording that said take note in order for it to flow better with the surrounding
text and it's new position.

2017-03-25 03:31 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @BurntSushi (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-03-25 03:31 UTC, mgattozzi commented
r? @steveklabnik

2017-03-25 13:56 UTC, steveklabnik requested changes
A very small nit, and then this is good to go. Thanks a ton!

2017-03-25 13:56 UTC, steveklabnik commented on src/libstd/process.rs
> +/// Calling [`wait`][`wait`] (or other functions that wrap around it) will make
You don't need to duplicate [`wait`] here, you can drop it, just like [`Drop`] above.

2017-03-25 20:14 UTC, mgattozzi commented on src/libstd/process.rs
> +/// Calling [`wait`][`wait`] (or other functions that wrap around it) will make
This was already here when I moved it so I had just kept it. I'll drop it.

2017-03-25 20:19 UTC, steveklabnik commented
@bors: r+ rollup

thanks! I totally hear you about keeping it the same, might as well fix it while you're here 😄

2017-03-25 21:14 UTC, mgattozzi commented
Hahaha yeah I'm not opposed to fixing it, I just wasn't sure if that was some weird markdown thing from before. I figured it'd be better not to touch it.

2017-03-25 22:21 UTC, GuillaumeGomez submitted a review, later dismissed

2017-03-25 22:21 UTC, GuillaumeGomez commented on src/libstd/process.rs
> +/// Calling [`wait`] (or other functions that wrap around it) will make
I'm not sure it'll work. Better write: "[`wait `][ `wait `]"

2017-03-25 22:21 UTC, GuillaumeGomez commented
While waiting for others' confirmation, I'll put this PR on wait. Sorry for the bothering.

@bors: r-

2017-03-27 13:49 UTC, steveklabnik commented on src/libstd/process.rs
> +/// Calling [`wait`] (or other functions that wrap around it) will make
Ah, yes, the space. @mgattozzi did you happen to build this locally? It _should_ work, but it might not.

2017-03-29 03:12 UTC, mgattozzi commented on src/libstd/process.rs
> +/// Calling [`wait`] (or other functions that wrap around it) will make
Yeah not a problem. Sorry was a bit busy this week let me quickly edit this

2017-03-29 23:44 UTC, mgattozzi commented
This did break the link. Working on the fix now.

2017-03-31 18:29 UTC, steveklabnik commented
@mgattozzi let me know when you have this one updated!

2017-03-31 18:36 UTC, mgattozzi commented
[ wait ][ wait ] didn't work either. I think we just need to revert the changes. Thoughts @steveklabnik?

2017-03-31 19:01 UTC, steveklabnik commented
That's... odd. Given that was the way it was defined below.

2017-03-31 20:28 UTC, mgattozzi commented
Hmmm. Looking at it again I had it as  "[ wait ][ wait ]" based off the above comments from @GuillaumeGomez let me retry it without the "" and see if that does it.

2017-04-01 01:47 UTC, GuillaumeGomez commented
Yes sure. We're not in a hurry.

2017-04-04 01:03 UTC, mgattozzi commented
Yeah that definitely didn't do it. It worked as was before the change I think it might be best if we leave it that way.

2017-04-07 08:32 UTC, nagisa commented
```
[`wait`]

[`wait`]: URL
```

Should work just fine if we're following common mark spec properly.

2017-04-07 10:16 UTC, GuillaumeGomez commented
@nagisa: Indeed.

2017-04-10 22:02 UTC, mgattozzi commented
Alright I'll do that then and see if it works out properly

2017-04-17 12:23 UTC, carols10cents commented
Friendly ping to keep this on your radar @mgattozzi!

2017-04-20 15:55 UTC, steveklabnik approved these changes

2017-04-20 15:55 UTC, steveklabnik commented
@bors: r+ rollup

thank you!

2017-04-20 20:37 UTC, merged

2017-04-21 13:34 UTC, mgattozzi commented
Thanks @carols10cents for the ping. I was a bit busy recently so it was good to get this in.