Update ChildStderr docs to be clearer
rust-lang/rust pull request #40829
Opened 2017-03-25 21:24 UTC by mgattozzi

Before the docs only had a line about where it was found and that it was
a handle to stderr. This commit changes it so that the summary second line is
removed and that it's a bit clearer about what can be done with it. Part of
#29370

2017-03-25 21:24 UTC, mgattozzi commented
r? @steveklabnik

2017-03-25 21:24 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @BurntSushi (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-03-25 21:26 UTC, mgattozzi commented
@steveklabnik I'm not sure if this is what you meant by expanding upon the docs in https://github.com/rust-lang/rust/issues/29370. If it is great because I have two PRs ready to go for ChildStdin and ChildStdout, but I figured it best to get a sense for what you wanted this to be expanded too here before opening those two.

2017-03-25 22:18 UTC, GuillaumeGomez requested changes

2017-03-25 22:18 UTC, GuillaumeGomez commented on src/libstd/process.rs
> +/// A handle to a child process's stderr. It can be used to
Please keep "This struct is used in the [`stderr`] field on [`Child`]."

2017-03-27 13:59 UTC, steveklabnik commented on src/libstd/process.rs
> +/// A handle to a child process's stderr. It can be used to
I'm not saying to remove it, I'm saying that there needs to be whitespace between.

2017-03-27 13:59 UTC, steveklabnik commented
wow thanks github, dunno how that got duplicated...

2017-03-28 02:53 UTC, GuillaumeGomez commented on src/libstd/process.rs
> +/// A handle to a child process's stderr. It can be used to
I'd prefer to have it this way as well.

2017-03-29 03:17 UTC, mgattozzi commented on src/libstd/process.rs
> +/// A handle to a child process's stderr. It can be used to
Okay will do. That makes more sense.

2017-03-29 03:17 UTC, mgattozzi commented on src/libstd/process.rs
> +/// A handle to a child process's stderr. It can be used to
Ahhhh okay got it.

2017-03-29 03:18 UTC, mgattozzi commented
I see what your wording in the issue means now. After my other PR is done building locally I can move on to this one.

2017-04-04 20:25 UTC, mgattozzi commented
@GuillaumeGomez and @steveklabnik  I've updated the docs to have the newlines and changed it back to the original wording as requested!

2017-04-09 14:03 UTC, steveklabnik commented
@bors: r+ rollup

2017-04-09 17:51 UTC, merged

2017-04-09 20:40 UTC, mgattozzi commented
Awesome! I'll get the other two in soon so that we can knock them off the process list.