change string references in asciiext r? @steveklabnik
rust-lang/rust pull request #40837
Opened 2017-03-26 12:07 UTC by alanstoate

#40714  Updated AsciiExt docs and some examples

2017-03-26 12:07 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @alexcrichton (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-03-26 16:22 UTC, asgs reviewed
Minor comment: change "it's" to its

2017-03-26 16:44 UTC, frewsxcv requested changes
Looks great, thanks! Just need to fix a couple typos then this should be good to go!

2017-03-26 16:44 UTC, frewsxcv commented on src/libstd/ascii.rs
> +    /// Makes a copy of the value in it's ASCII upper case equivalent.
"it's" → "its"

http://www.its-not-its.info/

2017-03-26 16:44 UTC, frewsxcv commented on src/libstd/ascii.rs
> +    /// Makes a copy of the value in it's ASCII lower case equivalent.
ditto about "it's"

2017-03-26 21:17 UTC, alanstoate commented on src/libstd/ascii.rs
> +    /// Makes a copy of the value in it's ASCII upper case equivalent.
Oops, well that's embarrassing. Fixed now :)

2017-03-27 14:06 UTC, steveklabnik commented
@bors: r+ rollup

thanks a ton! ❤️

2017-03-27 14:27 UTC, alexcrichton commented
r? @steveklabnik

2017-03-29 00:09 UTC, merged