Adding links for Atomics docs #29377
rust-lang/rust pull request #40871
Opened 2017-03-28 04:00 UTC by projektir

r? @steveklabnik

2017-03-28 04:00 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @steveklabnik (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-03-28 13:26 UTC, steveklabnik requested changes
Thank you so much! I have some small nits to make the formatting fall in line with some of our conventions, and one bugfix. 🎊

2017-03-28 13:26 UTC, steveklabnik commented on src/libcore/sync/atomic.rs
> +//! [arc]: ../struct.Arc.html
https://travis-ci.org/rust-lang/rust/jobs/215789767#L8942 (It says this link is broken.)

The reason for this is that these docs _also_ get rendered for `libcore`, not just `libstd`. So can you change it to `../../../std/sync/struct.Arc.html`? Tricky!

2017-03-28 13:26 UTC, steveklabnik commented on src/libcore/sync/atomic.rs
> +    /// [1]: http://llvm.org/docs/Atomics.html#monotonic
While you're here, would you mind helping with a minor formatting issue as well? This should look like this:

```rust
     /// No ordering constraints, only atomic operations.
     ///
     /// Corresponds to LLVM's [`Monotonic`] ordering.
     ///
     /// [`Monotonic`]: http://llvm.org/docs/Atomics.html#monotonic
```

Thanks 😄

2017-03-28 13:26 UTC, steveklabnik commented on src/libcore/sync/atomic.rs
> +    /// [1]: http://llvm.org/docs/Atomics.html#acquire
Similar here, could this be

```rust
    /// to the other threads that perform a load with [`Acquire`] ordering
    /// on the same value.
    ///
    /// [`Aquire`]: http://llvm.org/docs/Atomics.html#acquire
```

2017-03-28 13:26 UTC, steveklabnik commented on src/libcore/sync/atomic.rs
> +    /// [1]: http://llvm.org/docs/Atomics.html#release
same here

2017-03-28 13:26 UTC, steveklabnik commented on src/libcore/sync/atomic.rs
> +    /// [2]: http://llvm.org/docs/Atomics.html#release
and here:

```rust
    /// When coupled with a load, uses [`Acquire`] ordering, and with a store
    /// [`Release`] ordering.
    /// 
    /// [`Acquire`]: http://llvm.org/docs/Atomics.html#acquire
    /// [`Release`]: http://llvm.org/docs/Atomics.html#release
```

2017-03-28 13:26 UTC, steveklabnik commented on src/libcore/sync/atomic.rs
> +/// [`AtomicBool`]: struct.AtomicBool.html
an extra `///` between these two lines, please!

2017-03-28 13:26 UTC, steveklabnik commented on src/libcore/sync/atomic.rs
> +    /// `load()` takes an [`Ordering`] argument which describes the memory ordering
we don't include the `()` in function names; some of our docs do, but we decided against that style.

2017-03-28 13:26 UTC, steveklabnik commented on src/libcore/sync/atomic.rs
> +    /// `store()` takes an [`Ordering`] argument which describes the memory ordering
same here

2017-03-28 13:26 UTC, steveklabnik commented on src/libcore/sync/atomic.rs
> +    /// [`AcqRel`]: enum.Ordering.html#variant.AcqRel
nice catch! 😓

2017-03-28 13:26 UTC, steveklabnik commented on src/libcore/sync/atomic.rs
> +    /// `swap()` takes an [`Ordering`] argument which describes the memory ordering
same here

2017-03-28 13:26 UTC, steveklabnik commented on src/libcore/sync/atomic.rs
> +    /// `compare_and_swap()` also takes an [`Ordering`] argument which describes the memory
and here (I'll stop now, but all the others too)

2017-03-28 13:26 UTC, steveklabnik commented on src/libcore/sync/atomic.rs
> +    /// [`compare_exchange()`]: #method.compare_exchange
when removing the `()`s this one will have to go too

2017-03-28 13:26 UTC, steveklabnik commented on src/libcore/sync/atomic.rs
> +            ///
could you remove this extra line please?

2017-03-28 21:47 UTC, projektir commented on src/libcore/sync/atomic.rs
> +//! [arc]: ../struct.Arc.html
Yeah, I had some issues with this one. I wasn't sure if a longer path was better for this to get linked in both place correctly. I'll play around it some more.

2017-03-28 21:48 UTC, projektir commented on src/libcore/sync/atomic.rs
> +    /// `load()` takes an [`Ordering`] argument which describes the memory ordering
Good to know! I'll be sure to fix this up in the Once PR, as well.

2017-03-28 21:56 UTC, steveklabnik commented on src/libcore/sync/atomic.rs
> +//! [arc]: ../struct.Arc.html
For now it is, yeah. Someday...

2017-03-29 22:58 UTC, projektir commented
@steveklabnik I've pushed a new commit for the formatting changes.

2017-03-31 18:30 UTC, steveklabnik approved these changes
@bors: r+ rollup

thanks so much!

2017-03-31 18:31 UTC, steveklabnik commented
Oops, looks like @bors doesn't see review comments.

@bors: r+ rollup

2017-04-01 03:37 UTC, merged