Add example to std::process::abort
rust-lang/rust pull request #40904
Opened 2017-03-29 14:05 UTC by rap2hpoutre

This is a first step in order to complete this issue: https://github.com/rust-lang/rust/issues/29370
I submitted this PR with the help of @steveklabnik More info here: https://github.com/rust-lang/rust/issues/29370#issuecomment-290089330

It's my first PR on Rust, I'm learning how to contribute: Should I ping someone? I will post another PR with a more complicated example soon, I prefer send it separately (cause maybe I made some mistakes).

2017-03-29 14:05 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @brson (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-03-29 14:09 UTC, steveklabnik commented
> Should I ping someone?

Nope, as you can see, @rust-highfive has your back 😄 that said, let's assign this to me, not brian:

r? @steveklabnik

> I will post another PR with a more complicated example soon, I prefer send it separately (cause maybe I made some mistakes).

💯

2017-03-29 14:11 UTC, steveklabnik requested changes
one tiny thing, and then this is good to go! 🎊

2017-03-29 14:11 UTC, steveklabnik commented on src/libstd/process.rs
> +/// ```
could you add another `///` above this line, please?

2017-03-29 14:19 UTC, rap2hpoutre commented on src/libstd/process.rs
> +/// ```
Ok I updated

2017-03-29 14:20 UTC, rap2hpoutre commented on src/libstd/process.rs
> +/// ```
Thanks for all the time you spent to help me!

2017-03-29 14:21 UTC, steveklabnik approved these changes

2017-03-29 14:21 UTC, steveklabnik commented
Looks great, thanks! Travis found an issue though:

https://travis-ci.org/rust-lang/rust/jobs/216364459#L564-L566

these three lines have trailing whitespace. Can you remove them?

2017-03-29 14:22 UTC, steveklabnik commented on src/libstd/process.rs
> +/// ```
No problem! Very glad to do so.

2017-03-29 16:10 UTC, rap2hpoutre commented
@steveklabnik It fails again but I don't know why... Reading the log does not help me: https://api.travis-ci.org/jobs/216373325/log.txt?deansi=true

2017-03-29 19:10 UTC, steveklabnik commented
Looks like a spurious failure; I'm going to retry it.

2017-03-30 07:54 UTC, ollie27 commented on src/libstd/process.rs
> +/// ```
This needs to be changed to ` ```no_run ` so it doesn't try to run this code as a test.

2017-03-30 07:56 UTC, rap2hpoutre commented on src/libstd/process.rs
> +/// ```
Ok thanks, done!

2017-03-30 09:42 UTC, rap2hpoutre commented
@steveklabnik  It passes now :)

2017-03-30 13:52 UTC, steveklabnik commented
@bors: r+ rollup

wonderful, thank you so much!

2017-03-30 14:05 UTC, rap2hpoutre commented
Thanks to you I learned a lot with this (really small) PR! I'm ready for better PR now.

2017-03-30 15:07 UTC, steveklabnik commented
Awesome :D

2017-03-31 18:40 UTC, merged