Str boilerplate docs
rust-lang/rust pull request #40935
Opened 2017-03-30 20:39 UTC by donniebishop

References #29375. Modified descriptions of multiple structs to be more in line with structs found under [`std::iter`](https://doc.rust-lang.org/std/iter/#structs), such as [`Chain`](https://doc.rust-lang.org/std/iter/struct.Chain.html) and [`Enumerate`](https://doc.rust-lang.org/std/iter/struct.Enumerate.html)

2017-03-30 20:40 UTC, rust-highfive commented
r? @alexcrichton

(rust_highfive has picked a reviewer for you, use r? to override)

2017-03-30 22:22 UTC, steveklabnik requested changes
one tiny thing and then this is good to go!

2017-03-30 22:22 UTC, steveklabnik commented on src/libcollections/str.rs
> +/// This struct is created by the [`encode_utf16()`] method on [`str`].
we don't include the `()`s when referencing methods; could you change that everywhere please?

2017-03-30 22:31 UTC, donniebishop commented on src/libcollections/str.rs
> +/// This struct is created by the [`encode_utf16()`] method on [`str`].
Can diddly do

2017-03-31 15:56 UTC, alexcrichton commented
r? @steveklabnik

2017-03-31 18:32 UTC, steveklabnik approved these changes

2017-03-31 18:32 UTC, steveklabnik commented
@bors: r+ rollup

2017-04-01 03:37 UTC, merged