Add links to std::sync::mpsc docs
rust-lang/rust pull request #40981
Opened 2017-04-01 00:23 UTC by Technius

Addresses part of #29377
?r @steveklabnik 

I took a stab at adding links to the `std::sync::mpsc` docs, and I also wrote a few examples.

2017-04-01 00:23 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @alexcrichton (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-04-01 01:04 UTC, alexcrichton commented
r? @steveklabnik

2017-04-01 04:49 UTC, frewsxcv commented
Travis found some errors

https://gist.github.com/frewsxcv/d968eb5970f2d7530fc6c86c723c95a5

2017-04-03 15:50 UTC, steveklabnik requested changes
Thank you so much! This is great, I just have a few minor style nits. We don't use `()`s for function names, and some extra whitespace will make these examples more readable. Thank you!

2017-04-03 15:50 UTC, steveklabnik commented on src/libstd/sync/mpsc/mod.rs
> +//! 2. A synchronous, bounded channel. The [`sync_channel()`] function will
same here

2017-04-03 15:50 UTC, steveklabnik commented on src/libstd/sync/mpsc/mod.rs
> +//! [`sync_channel()`]: ../../../std/sync/mpsc/fn.sync_channel.html
and both of these lines to match

2017-04-03 15:50 UTC, steveklabnik commented on src/libstd/sync/mpsc/mod.rs
> +//! will continue to [`unwrap()`] the results returned from this module,
and here

2017-04-03 15:50 UTC, steveklabnik commented on src/libstd/sync/mpsc/mod.rs
> +//! [`unwrap()`]: ../../../std/result/enum.Result.html#method.unwrap
and here

2017-04-03 15:50 UTC, steveklabnik commented on src/libstd/sync/mpsc/mod.rs
> +/// let (send, recv) = channel();
could you add a blank line above and below this one? just the `///`s

2017-04-03 15:50 UTC, steveklabnik commented on src/libstd/sync/mpsc/mod.rs
> +/// println!("{}", recv.recv().unwrap()); // Received immediately
same here, only one above please!

2017-04-03 15:50 UTC, steveklabnik commented on src/libstd/sync/mpsc/mod.rs
> +/// let (sender, receiver) = channel();
can you put a blank line above this one...

2017-04-03 15:50 UTC, steveklabnik commented on src/libstd/sync/mpsc/mod.rs
> +/// let sender2 = sender.clone();
and below this one?

2017-04-03 15:50 UTC, steveklabnik commented on src/libstd/sync/mpsc/mod.rs
> +/// // Second thread owns sender2
and one above here

2017-04-03 15:50 UTC, steveklabnik commented on src/libstd/sync/mpsc/mod.rs
> +/// let msg = receiver.recv().unwrap();
and one above here

2017-04-03 15:50 UTC, steveklabnik commented on src/libstd/sync/mpsc/mod.rs
> +/// assert_eq!(3, msg + msg2);
and one above here, please!

2017-04-03 15:50 UTC, steveklabnik commented on src/libstd/sync/mpsc/mod.rs
> +    /// let (send, recv) = channel();
one blank line above and below this line, please!

2017-04-03 15:50 UTC, steveklabnik commented on src/libstd/sync/mpsc/mod.rs
> +    /// for x in recv.iter() {
and one above here

2017-04-04 13:22 UTC, steveklabnik approved these changes

2017-04-04 13:22 UTC, steveklabnik commented
@bors: r+ rollup

Thanks!

2017-04-05 19:47 UTC, merged