Improve option API docs
rust-lang/rust pull request #40999
Opened 2017-04-01 16:53 UTC by irfanhudda

Associated Issue: #29366 

Improve `option` API docs for
* `IntoIter` struct
* `Iter` struct
* `IterMut` struct

r? @steveklabnik

2017-04-01 16:53 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @steveklabnik (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-04-01 21:22 UTC, steveklabnik requested changes
some nits!

2017-04-01 21:22 UTC, steveklabnik commented on src/libcore/option.rs
> +/// This `struct` is created by [`Option::iter`] function.
"by the", please :)

2017-04-01 21:22 UTC, steveklabnik commented on src/libcore/option.rs
> +/// The iterator yields one value if the [`Option`] is a [`Some`] variant, otherwise none.
can you remove "variant" here, it sounds more natural without it to me.

2017-04-01 21:22 UTC, steveklabnik commented on src/libcore/option.rs
> +/// This `struct` is created by [`Option::iter_mut`] function.
same two comments here

2017-04-01 21:22 UTC, steveklabnik commented on src/libcore/option.rs
> +/// This `struct` is created by [`Option::into_iter`] function.
and here

2017-04-02 00:43 UTC, irfanhudda commented
@steveklabnik Thanks for the review. I've made some changes here.

2017-04-02 15:34 UTC, steveklabnik approved these changes

2017-04-02 15:34 UTC, steveklabnik commented
@bors: r+ rollup

thank you!

2017-04-05 19:47 UTC, merged