syntax: Support parentheses around trait bounds
rust-lang/rust pull request #41077
Opened 2017-04-04 23:43 UTC by petrochenkov

An implementation for https://github.com/rust-lang/rust/issues/39318#issuecomment-290956826

r? @nikomatsakis

2017-04-05 08:22 UTC, petrochenkov commented on src/libsyntax/parse/parser.rs
> +                    TyKind::TraitObject(ref bounds) if maybe_bounds && bounds.len() == 1 => {
FIXME: Need to reject `(Trait +) + Trait`.

2017-04-06 19:50 UTC, petrochenkov commented on src/libsyntax/parse/parser.rs
> +    // TY_BOUND_NOPAREN = [?] [for<LT_PARAM_DEFS>] SIMPLE_PATH (e.g. `?for<'a: 'b> m::Trait<'a>`)
@nikomatsakis 
You [wanted a grammar](https://github.com/rust-lang/rust/issues/39318#issuecomment-292216147), here it is.

2017-04-08 08:36 UTC, nikomatsakis commented on src/libsyntax/parse/parser.rs
> +    // TY_BOUND_NOPAREN = [?] [for<LT_PARAM_DEFS>] SIMPLE_PATH (e.g. `?for<'a: 'b> m::Trait<'a>`)
Thanks. Sorry for my high lag, traveling this week.

2017-04-12 17:09 UTC, nikomatsakis commented
OK, so, I'm not sure I'm 100% happy with these rules around parens, but honestly I'm ready to stop thinking about it. =) And besides if anything I would want to accept more, so it seems ok to accept *less* for now.

2017-04-17 14:16 UTC, carols10cents commented
Soooo do i hear an r, @nikomatsakis? What are the next steps here?

2017-04-18 14:08 UTC, nikomatsakis commented
@carols10cents heh, thanks for keeping me on my toes. Got distracted before deciding what the next step was -- in particular, whether to consult with @rust-lang/lang or what. I think I'm inclined to r+ regardless, let me do another quick review though, since I think that this can only be a subset of the behavior we would eventually want. (And maybe it's fine to just stop here for now.)

2017-04-18 14:29 UTC, nikomatsakis requested changes
Left a few comments.

2017-04-18 14:29 UTC, nikomatsakis commented on src/libsyntax/parse/parser.rs
> +                    TyKind::TraitObject(ref bounds)
What is an example where this case gets hit?

2017-04-18 14:29 UTC, nikomatsakis commented on src/libsyntax/parse/parser.rs
> +                    TyKind::TraitObject(ref bounds)
I guess it occurs with `(for<'a> Foo)`?

2017-04-18 14:29 UTC, nikomatsakis commented on src/libsyntax/parse/parser.rs
>                  break
So, we consumed an open-paren at the start of the loop, don't we want to consume the close paren here somewhere?

2017-04-18 14:29 UTC, nikomatsakis commented on src/libsyntax/parse/parser.rs
>                  break
(In general the handling of parens here feels complex.)

2017-04-19 21:51 UTC, petrochenkov commented on src/libsyntax/parse/parser.rs
> +                    TyKind::TraitObject(ref bounds)
>I guess it occurs with `(for<'a> Foo)`?

Exactly

2017-04-19 22:02 UTC, petrochenkov commented on src/libsyntax/parse/parser.rs
>                  break
This `breaks` happens only if the code is already syntactically incorrect, something like 
```rust
(Trait) + (Trait) + ($*&^#&*%%a;ch
```
so there may be no closing paren.
I can move `expect(closing_paren)` below `else { ... }` though, it should look a bit nicer.

2017-04-20 18:55 UTC, nikomatsakis commented on src/libsyntax/parse/parser.rs
>                  break
@petrochenkov can you add some comments about this, at minimum? moving the `expect(closing_patern)` also sounds good.

2017-04-20 20:13 UTC, petrochenkov commented on src/libsyntax/parse/parser.rs
>                  break
Oh wait, the `break` is actually wrong in presence of `(` or `?`.
`fn f<T: ?>(){}` in particular compiles on all Rust versions since 1.0 😆

2017-04-20 20:14 UTC, petrochenkov commented on src/libsyntax/parse/parser.rs
>                  break
I'll fix this too.

2017-04-20 21:36 UTC, petrochenkov commented
Updated.

2017-04-22 10:08 UTC, nikomatsakis approved these changes

2017-04-22 10:08 UTC, nikomatsakis commented
@bors r+

2017-04-22 16:46 UTC, merged