Add example to std::process::abort
rust-lang/rust pull request #41090
Opened 2017-04-05 18:41 UTC by rap2hpoutre

This is a second (2/3?) step in order to complete this issue: https://github.com/rust-lang/rust/issues/29370
I submitted this PR with the help of @steveklabnik again. Thanks to him! More info here: https://github.com/rust-lang/rust/issues/29370#issuecomment-290653877

2017-04-05 18:41 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @aturon (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-04-05 18:42 UTC, rap2hpoutre commented
r? @steveklabnik

2017-04-05 18:55 UTC, steveklabnik approved these changes

2017-04-05 18:56 UTC, steveklabnik requested changes
This is fantastic! One tiny, tiny thing though, then this is good to go

2017-04-05 18:56 UTC, steveklabnik commented on src/libstd/process.rs
> +///
could you remove this line, please?

2017-04-05 19:27 UTC, steveklabnik requested changes

2017-04-05 19:27 UTC, steveklabnik commented on src/libstd/process.rs
> +/// The abort function terminates the process, so the destructor will not get
oh and could this link to abort please?

2017-04-06 03:30 UTC, frewsxcv commented on src/libstd/process.rs
> +/// The abort function terminates the process, so the destructor will not get
There's also whitespace at the end of this line the tidy checker doesn't like.

2017-04-06 08:18 UTC, rap2hpoutre commented on src/libstd/process.rs
> +///
Ok done!

2017-04-06 08:19 UTC, rap2hpoutre commented on src/libstd/process.rs
> +/// The abort function terminates the process, so the destructor will not get
Ok for both comments! Thanks!

2017-04-06 12:03 UTC, rap2hpoutre commented
@steveklabnik Ok, everything seems fine now. Thank you again!

2017-04-06 14:11 UTC, steveklabnik approved these changes

2017-04-06 14:11 UTC, steveklabnik commented
@bors: r+ rollup

💯 ❤️ ✨ thank you!!!

2017-04-07 01:27 UTC, merged