document some existing unstable features
rust-lang/rust pull request #41135
Opened 2017-04-07 06:06 UTC by japaric

"msp430-interrupt", "ptx-kernel" and #![compiler_builtins_lib]

r? @steveklabnik

2017-04-07 06:06 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @steveklabnik (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-04-07 14:26 UTC, steveklabnik requested changes
one teeny tiny formatting nit, and then r=me. Thanks so much!

2017-04-07 14:26 UTC, steveklabnik commented on src/doc/unstable-book/src/abi-ptx.md
> +is: [38788](https://github.com/rust-lang/rust/issues/38788)
we have a standard form for this stuff, like this: https://github.com/rust-lang/rust/pull/41135/files#diff-d6ab7d3e772d67c4944af27d29e229cdR3

mind changing this to be identical? Thanks 😄

2017-04-07 14:44 UTC, japaric commented on src/doc/unstable-book/src/abi-ptx.md
> +is: [38788](https://github.com/rust-lang/rust/issues/38788)
Sure thing. 😄

2017-04-07 14:48 UTC, japaric commented
@bors r=steveklabnik

2017-04-07 19:07 UTC, TimNN commented
@bors retry

* appveyor already failed (unrelated to this, fix in #41147)

2017-04-07 19:19 UTC, TimNN commented
@bors retry

2017-04-07 21:02 UTC, TimNN commented
@bors retry

* #41147

2017-04-08 06:53 UTC, TimNN commented
@bors retry

* #41147

2017-04-08 09:23 UTC, merged