Adding links and examples for various mspc pages #29377
rust-lang/rust pull request #41438
Opened 2017-04-21 03:55 UTC by projektir

Adding links and copying examples for the various Iterators; adding some extra stuff to `Sender`/`SyncSender`/`Receiver`.

2017-04-21 03:55 UTC, rust-highfive commented
r? @brson

(rust_highfive has picked a reviewer for you, use r? to override)

2017-04-21 14:09 UTC, shepmaster commented
Thanks for the pull request @projektir! We'll make sure that @brson or another reviewer take a look at this in a reasonable amount of time.

2017-04-21 15:53 UTC, alexcrichton commented
@projektir looks like the travis tests may be failing? Other than that looks good to me!

2017-04-21 18:50 UTC, chordowl requested changes
Some small nits, but this looks good to me overall! Thanks @projektir :grin: 

Edit: oops, didn't add all the comments...

2017-04-21 18:50 UTC, lukaramu commented on src/libstd/sync/mpsc/mod.rs
> +/// assert_eq!(1, msg);
This line is failing the test because there is a race condition.

2017-04-21 18:52 UTC, lukaramu commented on src/libstd/sync/mpsc/mod.rs
> +/// This iterator will block whenever [`next`] is called,
Can you put a newline after the first sentence? The summary is quite long otherwise.

2017-04-21 18:52 UTC, lukaramu commented on src/libstd/sync/mpsc/mod.rs
> +/// created by [`try_iter`]. [`None`] will be returned when there
Same as above

2017-04-21 18:52 UTC, lukaramu commented on src/libstd/sync/mpsc/mod.rs
> +/// created by **Receiver::into_iter**. This iterator will block whenever [`next`]
Same as above. Can you also make `into_iter` into a link and format it the same way as you did for the summaries for `Iter` and `TryIter`?

2017-04-22 17:01 UTC, projektir commented
@lukaramu this should be good for another review now.

2017-04-22 18:48 UTC, chordowl approved these changes
Looks good to me now! :ok_hand:

2017-04-24 15:06 UTC, alexcrichton commented
@bors: r+

2017-04-25 00:57 UTC, frewsxcv commented on src/libstd/sync/mpsc/mod.rs
> +    /// sent to the corresponding [`Sender`] (or [`SyncSender`]), then this
https://travis-ci.org/rust-lang/rust/jobs/225404572

this line causes a failure on travis.

this is considered a markdown link:

```
[foo] (bar.html)
```

for the same reason this is:

```
[`Sender`] (or [`SyncSender`])
```

to get around this, do something like this:

```
[`Sender`][`Sender`] (or [`SyncSender`])
```

2017-04-25 00:57 UTC, frewsxcv commented
@bors r-

2017-04-25 01:21 UTC, projektir commented on src/libstd/sync/mpsc/mod.rs
> +    /// sent to the corresponding [`Sender`] (or [`SyncSender`]), then this
Hmm, how did Travis not pick it up last time. :confused: Or the tests I ran, for that matter.

2017-04-27 07:10 UTC, projektir commented
...I want to say it should be good to merge now?

2017-04-27 09:45 UTC, steveklabnik commented
Lookin' good!

@bors: r+ rollup

2017-04-28 03:18 UTC, merged