Closure args
rust-lang/rust pull request #41488
Opened 2017-04-23 22:39 UTC by estebank

```rust
error[E0593]: closure takes 1 parameter but 2 parameters are required here
  --> ../../src/test/ui/mismatched_types/closure-arg-count.rs:13:15
   |
13 |     [1, 2, 3].sort_by(|(tuple, tuple2)| panic!());
   |               ^^^^^^^ -------------------------- takes 1 parameter
   |               |
   |               expected closure that takes 2 parameters
```

instead of

```rust
error[E0281]: type mismatch: the type `[closure@../../src/test/ui/mismatched_types/closure-arg-count.rs:13:23: 13:49]` implements the trait `for<'r> std::ops::FnMut<(&'r {integer},)>`, but the trait `for<'r, 'r> std::ops::FnMut<(&'r {integer}, &'r {integer})>` is required (expected a tuple with 2 elements, found one with 1 elements)
  --> ../../src/test/ui/mismatched_types/closure-arg-count.rs:13:15
   |
13 |     [1, 2, 3].sort_by(|(tuple, tuple2)| panic!());
   |               ^^^^^^^
```

Fix #21857, re #24680.

2017-04-23 22:39 UTC, rust-highfive commented
r? @eddyb

(rust_highfive has picked a reviewer for you, use r? to override)

2017-04-24 03:25 UTC, eddyb commented
r? @jonathandturner

2017-04-24 08:52 UTC, arielb1 requested changes

2017-04-24 08:52 UTC, arielb1 commented on src/librustc/traits/error_reporting.rs
> +                    if let &TypeError::TupleSize(ref expected_found) = e {
Shouldn't you match on `expected_trait_ref` & `actual_trait_ref`, to avoid `Fn(X<()>)` vs. `Fn(X<(Foo, Bar)>)` etc.

2017-04-24 09:10 UTC, leonardo-m commented
This code:

```
#![allow(unused_variables)]
fn main() {
    [1, 2, 3].sort_by(|(x, y)| panic!());
}
```

Currently gives me lot of error output:

```
error[E0308]: mismatched types
 --> ...\test.rs:3:24
  |
3 |     [1, 2, 3].sort_by(|(x, y)| panic!());
  |                        ^^^^^^ expected &{integer}, found tuple
  |
  = note: expected type `&{integer}`
             found type `(_, _)`

error[E0281]: type mismatch: the type `[closure@...\test.rs:3:23: 3:40]` implements the trait `for<'r> std::ops::FnMut<(&'r {integer},)>`, but the trait `for<'r, 'r> std::ops::FnMut<(&'r {integer}, &'r {integer})>` is required (expected a tuple with 2 elements, found one with 1 elements)
 --> ...\test.rs:3:15
  |
3 |     [1, 2, 3].sort_by(|(x, y)| panic!());
  |               ^^^^^^^

error[E0281]: type mismatch: the type `[closure@...\test.rs:3:23: 3:40]` implements the trait `for<'r> std::ops::FnOnce<(&'r {integer},)>`, but the trait `for<'r, 'r> std::ops::FnOnce<(&'r {integer}, &'r {integer})>` is required (expected a tuple with 2 elements, found one with 1 elements)
 --> ...\test.rs:3:15
  |
3 |     [1, 2, 3].sort_by(|(x, y)| panic!());
  |               ^^^^^^^

error: aborting due to 3 previous errors
```

A better error output could be:

```
error[E0593]: ../../src/test/ui/mismatched_types/closure-arg-count.rs:13:15
   |
13 |     [1, 2, 3].sort_by(|(x, y)| panic!());
   |                        ^^^^^^ -------- 1 argument given
   |                        |
   |                        expected closure that takes 2 arguments
```

2017-04-24 20:50 UTC, nagisa commented
Nit on wording. In definitions/declarations it is “arguments”, not “parameters”. “parameters” is for expressions that get passed into the function call.

2017-04-25 01:57 UTC, estebank commented
@nagisa @arielb1 done.

2017-04-25 19:12 UTC, jonathandturner commented
@leonardo-m - did the error message get worse or stay the same?  If it's the same, we could take this PR and then tackle your example as a separate issue.

2017-04-25 19:15 UTC, jonathandturner commented on src/test/compile-fail/E0281.rs
> +    //~^ ERROR E0281
Can we move this to a `ui` test?

2017-04-25 19:15 UTC, jonathandturner commented on src/test/compile-fail/fn-variance-1.rs
> -    //~^ ERROR (types differ in mutability)
same

2017-04-25 19:15 UTC, jonathandturner commented on src/test/compile-fail/issue-36053-2.rs
> +    //~| NOTE expected &str, found str
same

2017-04-25 19:15 UTC, jonathandturner commented on src/test/compile-fail/unboxed-closures-vtable-mismatch.rs
> +    //~| NOTE expected isize, found usize
same

2017-04-25 19:15 UTC, jonathandturner commented on src/test/ui/mismatched_types/closure-mismatch.stderr
> +   = note: required because of the requirements on the impl of `Foo` for `[closure@$DIR/closure-mismatch.rs:18:9: 18:15]`
These two notes don't seem helplful.  Are they what is there currently, rather than being added by this PR?

2017-04-26 00:08 UTC, estebank commented on src/test/ui/mismatched_types/closure-mismatch.stderr
> +   = note: required because of the requirements on the impl of `Foo` for `[closure@$DIR/closure-mismatch.rs:18:9: 18:15]`
That's already part of [the current output](https://is.gd/bY9gG9). I would prefer to remove them in a separate (smaller) PR.

2017-04-26 01:33 UTC, jonathandturner commented on src/test/ui/mismatched_types/closure-mismatch.stderr
> +   = note: required because of the requirements on the impl of `Foo` for `[closure@$DIR/closure-mismatch.rs:18:9: 18:15]`
Sure, that's fine

2017-04-26 01:35 UTC, jonathandturner commented
Yeah, that looks pretty good.  👍 from me.

2017-04-26 09:12 UTC, arielb1 commented on src/librustc/traits/error_reporting.rs
> +            // Avoid multiple errors saying the same thing for closures
Is this targeted at something specific?

2017-04-26 09:48 UTC, leonardo-m commented
@jonathandturner: >did the error message get worse or stay the same?

I don't fully understand your question. Given this code:

```
#![allow(unused_variables)]
fn main() {
    [1, 2, 3].sort_by(|(x, y)| panic!());
}

```
This is how its error messages have evolved:

```
--------------------------------
1.0:

<source>:3:24: 3:30 error: mismatched types:
 expected `&_`,
    found `(_, _)`
(expected &-ptr,
    found tuple) [E0308]
<source>:3     [1, 2, 3].sort_by(|(x, y)| panic!());
                                                                                              ^~~~~~
<source>:3:15: 3:41 error: type mismatch: the type `[closure /tmp/compiler-explorer-compiler117326-8-ixlnde.do96qrggb9/example.rs:3:23: 3:40]` implements the trait `for<'r> core::ops::FnMut<(&'r _,)>`, but the trait `for<'r,'r> core::ops::FnMut<(&'r _, &'r _)>` is required (expected a tuple with 2 elements, found one with 1 elements) [E0281]
<source>:3     [1, 2, 3].sort_by(|(x, y)| panic!());
                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:3:15: 3:41 error: type mismatch: the type `[closure /tmp/compiler-explorer-compiler117326-8-ixlnde.do96qrggb9/example.rs:3:23: 3:40]` implements the trait `for<'r> core::ops::FnOnce<(&'r _,)>`, but the trait `for<'r,'r> core::ops::FnOnce<(&'r _, &'r _)>` is required (expected a tuple with 2 elements, found one with 1 elements) [E0281]
<source>:3     [1, 2, 3].sort_by(|(x, y)| panic!());
                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 3 previous errors
Compiler exited with result code 101

--------------------------------
1.11:

<source>:3:24: 3:30 error: mismatched types [E0308]
<source>:3     [1, 2, 3].sort_by(|(x, y)| panic!());
                                                                                               ^~~~~~
<source>:3:24: 3:30 help: run `rustc --explain E0308` to see a detailed explanation
<source>:3:24: 3:30 note: expected type `&_`
<source>:3:24: 3:30 note:    found type `(_, _)`
<source>:3:15: 3:22 error: type mismatch: the type `[closure@/tmp/compiler-explorer-compiler117326-8-1ggak45.5sng6wdn29/example.rs:3:23: 3:40]` implements the trait `for<'r> std::ops::FnMut<(&'r _,)>`, but the trait `for<'r, 'r> std::ops::FnMut<(&'r _, &'r _)>` is required (expected a tuple with 2 elements, found one with 1 elements) [E0281]
<source>:3     [1, 2, 3].sort_by(|(x, y)| panic!());
                                                                                      ^~~~~~~
<source>:3:15: 3:22 help: run `rustc --explain E0281` to see a detailed explanation
<source>:3:15: 3:22 error: type mismatch: the type `[closure@/tmp/compiler-explorer-compiler117326-8-1ggak45.5sng6wdn29/example.rs:3:23: 3:40]` implements the trait `for<'r> std::ops::FnOnce<(&'r _,)>`, but the trait `for<'r, 'r> std::ops::FnOnce<(&'r _, &'r _)>` is required (expected a tuple with 2 elements, found one with 1 elements) [E0281]
<source>:3     [1, 2, 3].sort_by(|(x, y)| panic!());
                                                                                      ^~~~~~~
<source>:3:15: 3:22 help: run `rustc --explain E0281` to see a detailed explanation
error: aborting due to 3 previous errors
Compiler exited with result code 101

--------------------------------
1.12 - 1.18nightly:

error[E0308]: mismatched types
 --> <source>:3:24
  |
3 |     [1, 2, 3].sort_by(|(x, y)| panic!());
  |                        ^^^^^^ expected &{integer}, found tuple
  |
  = note: expected type `&{integer}`
  = note:    found type `(_, _)`
error[E0281]: type mismatch: the type `[closure@<source>:3:23: 3:40]` implements the trait `for<'r> std::ops::FnMut<(&'r {integer},)>`, but the trait `for<'r, 'r> std::ops::FnMut<(&'r {integer}, &'r {integer})>` is required (expected a tuple with 2 elements, found one with 1 elements)
 --> <source>:3:15
  |
3 |     [1, 2, 3].sort_by(|(x, y)| panic!());
  |               ^^^^^^^
error[E0281]: type mismatch: the type `[closure@<source>:3:23: 3:40]` implements the trait `for<'r> std::ops::FnOnce<(&'r {integer},)>`, but the trait `for<'r, 'r> std::ops::FnOnce<(&'r {integer}, &'r {integer})>` is required (expected a tuple with 2 elements, found one with 1 elements)
 --> <source>:3:15
  |
3 |     [1, 2, 3].sort_by(|(x, y)| panic!());
  |               ^^^^^^^
error: aborting due to 3 previous errors
Compiler exited with result code 101

--------------------------------
```

So the error messages are essentially the same. And I think they could use an improvement (the first improvement is to generate only one error message).

2017-04-26 15:59 UTC, estebank commented on src/librustc/traits/error_reporting.rs
> +            // Avoid multiple errors saying the same thing for closures
You can see the effect of this in [the stderr output](https://github.com/rust-lang/rust/pull/41488/commits/d3f64a636e0fd6d72a533ada73f5bb2716048c9e#diff-efb255e33f30b3be4691c53a0d69e155), right now for closure type mismatch errors we output two (may be three in some cases?, haven't seen that yet) after the compiler tries to coerce to `Fn`, `FnMut` and `FnOnce`. This change was hacky and want to fix it properly somewhere closer to the source but this is as close as I got to the culprit last night. We can either remove this hack now and merge the PR with the duplicated errors, or merge this as is and I send a follow up PR fully addressing this.

2017-04-26 16:01 UTC, estebank commented
@leonardo-m the output for that file with the changes on this PR is:

```rust

error[E0308]: mismatched types
  --> $DIR/closure-arg-count.rs:3:24
   |
 3 |     [1, 2, 3].sort_by(|(tuple, tuple2)| panic!());
   |                        ^^^^^^^^^^^^^^^ expected &{integer}, found tuple
   |
   = note: expected type `&{integer}`
              found type `(_, _)`

error[E0593]: closure takes 1 argument but 2 arguments are required
  --> $DIR/closure-arg-count.rs:3:15
   |
 3 |     [1, 2, 3].sort_by(|(tuple, tuple2)| panic!());
   |               ^^^^^^^ -------------------------- takes 1 argument
   |               |
   |               expected closure that takes 2 arguments


error: aborting due to 2 previous errors
```

2017-04-26 16:58 UTC, leonardo-m commented
It's it too much to tell me five times what's the problem? Telling me once or twice should suffice.

2017-04-26 17:08 UTC, estebank commented on src/test/compile-fail/unboxed-closures-vtable-mismatch.rs
> +    //~| NOTE expected isize, found usize
Done for all.

2017-04-26 17:17 UTC, estebank commented
@leonardo-m I think there might have been a misunderstanding. I believe you were pointing out the output for this error over time, since 1.0 to current nightly, where there were 3 different, but equally unspecific, outputs, as well as suggesting a possible new output. I was pointing out what the new output with this code would be like. Your proposal to point out at only the tuple arg of the closure is not trivial at the moment because I only have the full closure's span to point at, but could be done with some more work. Apologies if you felt I was talking down to you in any way.

> So the error messages are essentially the same. And I think they could use an improvement (the first improvement is to generate only one error message).

This [PR does that (as pointed out in a prior comment)](https://github.com/rust-lang/rust/pull/41488#issuecomment-297458968), other than the mismatched types error, which I'll try to remove in a clean way in a follow up PR.

2017-04-26 19:19 UTC, jonathandturner commented
@leonardo-m - yeah sorry, I wasn't clear either.  I think you're pointing out a way it can be improved even further.  Can you file an issue with your example so we don't forget and can improve your example also?

I was just trying to make sure we weren't making your example worse with this PR, but it looks like we just have more work to do after this PR.

2017-04-26 19:50 UTC, leonardo-m commented
Thank you for the work.

> Can you file an issue with your example so we don't forget and can improve your example also?

I think it's better to wait for this PR to be merged and inside one Nightly, then I'll take a look at the error message it gives and we can open a new enhancement request.

2017-04-28 18:44 UTC, estebank commented
Ping @arielb1, @jonathandturner [already 👍'd](https://github.com/rust-lang/rust/pull/41488#issuecomment-297212424), I think the only thing left is to make a decision on wether we can leave [the last commit's deduplication logic as is](https://github.com/rust-lang/rust/pull/41488#discussion_r113493249) until I submit a cleaner follow up PR for that part or we land this PR without that code.

2017-05-01 10:02 UTC, arielb1 commented
@estebank 

The last commit's deduplication is a hack.

2017-05-02 00:09 UTC, estebank commented
@arielb1 removed the hacky commit.

2017-05-02 09:07 UTC, arielb1 commented
@bors r+

2017-05-02 12:11 UTC, merged