Added generic example of std::ops::Add in doc comments
rust-lang/rust pull request #41612
Opened 2017-04-28 18:20 UTC by mandeep

We discussed on IRC how the std::ops examples were potentially missing examples using generics. This PR adds an example to std::ops::Add that shows the use of a generic type T. I'm not sure this is ready for merge as I think the two examples now make the documentation a bit verbose, but I think it's a good starting point. I'd love to hear others thoughts on this. This is in relation to the last item in issue #29365.

2017-04-28 18:20 UTC, rust-highfive commented
r? @brson

(rust_highfive has picked a reviewer for you, use r? to override)

2017-05-01 03:01 UTC, frewsxcv commented
It seems like this example is being added to teach people how generic types work, which seems like a topic better suited for the book. That said, I imagine that using generic types when implementing `Add` could be a common scenario, so I'm alright with having this added.

@rust-lang/docs anyone else have opinions?

2017-05-01 03:28 UTC, mandeep commented
@frewsxcv I agree, in fact the first edition of the book contains an example similar to the one in this PR. Rather than having to rummage through the book, I was thinking that something like this example should be able to be found in the API docs. What do you think?

2017-05-01 08:52 UTC, GuillaumeGomez commented
Well, for me it's fine. It's just the trait `Add` which gets more examples.

2017-05-01 08:53 UTC, GuillaumeGomez requested changes
Just little nits. Also, some comments in the code might help users.

2017-05-01 08:53 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +///
Extra empty line.

2017-05-01 08:53 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +/// ```
Should be followed by an empty line.

2017-05-05 03:13 UTC, mandeep commented on src/libcore/ops.rs
> +///
Added the empty lines and comment regarding Output=T. Let me know if you'd like to see anything else.

2017-05-07 19:31 UTC, mandeep commented
Thinking about this some more. Maybe this example is best left in the book instead of the std lib docs. Later on I imagine something like this could go into a cookbook as well.

2017-05-08 12:01 UTC, GuillaumeGomez commented
I think it's a good thing to have it in multiple places. Can you just squash your commits please? Once done, I'll r+.

2017-05-08 13:30 UTC, mandeep commented
Thanks!

2017-05-08 14:34 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +///
We now have two extra lines. :p

2017-05-08 14:35 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +/// #[derive(Debug)]
I don't see any usage of the debug in the following code. Did you forget to remove it?

2017-05-08 15:08 UTC, mandeep commented on src/libcore/ops.rs
> +/// #[derive(Debug)]
The other examples derived Debug, so I followed the same path. Do you want me to remove Debug in this example and the other examples in std::Ops?

2017-05-09 11:05 UTC, GuillaumeGomez commented on src/libcore/ops.rs
> +/// #[derive(Debug)]
Yes please (strange we kept them).

2017-05-09 14:14 UTC, steveklabnik commented
@GuillaumeGomez looks like this was updated

2017-05-09 14:42 UTC, GuillaumeGomez commented
@steveklabnik: I commented on my previous review.

2017-05-11 03:34 UTC, mandeep commented
Looks like Debug was needed on a couple of the tests? How should we move forward?

2017-05-11 08:36 UTC, GuillaumeGomez commented
Put it where needed. My goal wasn't to force you to remove the `Debug` implementations but to remove the useless ones. If both of them are needed, we keep them of course.

2017-05-11 13:46 UTC, mandeep commented
My fault, I should have checked to see if Debug was needed.

2017-05-11 16:11 UTC, GuillaumeGomez commented
Ok, all good. Please squash and then I merge.

2017-05-13 21:44 UTC, frewsxcv commented
bors r=GuillaumeGomez,frewsxcv rollup

2017-05-13 21:44 UTC, frewsxcv commented
@bors r=GuillaumeGomez,frewsxcv rollup

2017-05-14 05:57 UTC, merged