Improve docs in os::windows::ffi and os::windows::fs
rust-lang/rust pull request #41870
Opened 2017-05-10 02:30 UTC by excaliburHisSheath

Part of #29367

This PR makes changes to the documentation in `os::windows::ffi` and `os::windows::fs` with the goal of fleshing them out and bringing them in line with Rust's quality standards.

r? @steveklabnik

2017-05-10 02:30 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @steveklabnik (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-05-10 21:08 UTC, TimNN commented
Hi @excaliburHisSheath and thanks for the PR! We'll periodically check in on it to make sure that @steveklabnik or someone else from the team reviews it soon.

2017-05-14 16:05 UTC, Mark-Simulacrum commented
@steveklabnik Just a reminder that this is still looking for a review from you.

cc @frewsxcv

2017-05-14 21:00 UTC, frewsxcv requested changes
this is great, thanks so much! a couple small comments, and this is good to go

2017-05-14 21:00 UTC, frewsxcv commented on src/libstd/sys/windows/ext/ffi.rs
> +    /// This is lossless: calling [`OsString::from_wide()`] and then
very minor, but can you remove all the `()` parens attached to method/function names in these docs? for the time being, the current policy is to remove them in documentation. see also https://github.com/rust-lang/rust/pull/40456

2017-05-14 21:00 UTC, frewsxcv commented on src/libstd/sys/windows/ext/mod.rs
> +//! `std` types and idioms with Windows in a way that the noraml
typo: 'noraml'

2017-05-14 21:10 UTC, frewsxcv commented on src/libstd/sys/windows/ext/fs.rs
> +    /// ```ignore
this example (and potentially other examples) could be `no_run` instead of `ignore` so they get compiled, but not run

2017-05-14 21:24 UTC, excaliburHisSheath commented on src/libstd/sys/windows/ext/fs.rs
> +    /// ```ignore
Cool, I wasn't aware of the distinction. Is there a general guideline to when examples should be `no_run` vs `ignore` vs tested normally?

2017-05-14 21:24 UTC, excaliburHisSheath commented on src/libstd/sys/windows/ext/ffi.rs
> +    /// This is lossless: calling [`OsString::from_wide()`] and then
Ah, I was under the impression that the `()` parens were the desired style, thanks for clarifying that this isn't the case (I can update documentation for my own crates as well).

2017-05-14 21:36 UTC, excaliburHisSheath commented on src/libstd/sys/windows/ext/ffi.rs
> +    /// This is lossless: calling [`OsString::from_wide()`] and then
For my own curiosity, is there some discussion around why the decision was made to remove the `()` parens when referencing function in documentation? Personally I liked that style, so I'm curious as to why the change was made.

2017-05-14 21:36 UTC, frewsxcv commented on src/libstd/sys/windows/ext/fs.rs
> +    /// ```ignore
https://doc.rust-lang.org/book/documentation.html#running-documentation-tests

2017-05-15 13:22 UTC, steveklabnik commented on src/libstd/sys/windows/ext/ffi.rs
> +    /// This is lossless: calling [`OsString::from_wide()`] and then
It wasn't that a change was made; it was that while proposing https://github.com/rust-lang/rfcs/blob/master/text/1574-more-api-documentation-conventions.md, we suggested that style, but it didn't make it through the process.

(I really like the `()`s so I was just adding them in before we had an actual convention)

2017-05-15 13:22 UTC, steveklabnik commented on src/libstd/sys/windows/ext/fs.rs
> +    /// ```ignore
the short answer is, if it doesn't compile, `ignore`, and if it compiles but you don't want it to run (say for example, a network test), then `no_run`.

2017-05-15 13:25 UTC, steveklabnik approved these changes
This is great, thank you! Sorry for the delay here; I took two days at the end of last week off, so I'm a bit behind on reviews.

I agree with @frewsxcv 's comments, but have no other ones of my own. r=me after they're fixed 😄

2017-05-19 02:15 UTC, excaliburHisSheath commented
@frewsxcv I believe I've addressed your concerns. I've left a number of tests `no_run` since they'll create a file `foo.txt` and it seems like bad practice to have tests create random files on disk. If it's preferred that we run the tests anyway I can change them, I think the tests still pass when run.

I've also made some changes to make the code style for the various `OpenOptionsExt` examples more consistent.

2017-05-19 03:06 UTC, frewsxcv commented
Looks great, thanks!

@bors r+ rollup

2017-05-19 03:07 UTC, frewsxcv approved these changes

2017-05-19 14:19 UTC, excaliburHisSheath commented
@frewsxcv Heads up, I pushed another commit after you approved because I noticed a doc test was failing. It doesn't look like the automated tests have caught the failure yet, though. I don't know if you need to do anything to make sure the new commit gets included in the merge.

2017-05-19 14:56 UTC, frewsxcv commented
@bors r+ rollup

2017-05-19 23:38 UTC, merged