doc: break into 2 sentences
rust-lang/rust pull request #41896
Opened 2017-05-10 20:51 UTC by tshepang

2017-05-10 20:51 UTC, rust-highfive commented
r? @brson

(rust_highfive has picked a reviewer for you, use r? to override)

2017-05-10 21:00 UTC, steveklabnik requested changes
r=me with this reflowed properly

2017-05-10 21:00 UTC, steveklabnik commented on src/libstd/thread/mod.rs
> +    /// If it is not specified either, a sensible default will be set
could you re-flow this? I agree splitting the sentences makes a lot of sense, but now it's got weird newlines.

2017-05-11 04:28 UTC, tshepang commented
is done

2017-05-11 14:53 UTC, steveklabnik commented
@bors: r+ rollup

thank you ❤️

2017-05-13 13:59 UTC, merged