rustc: simpler ParameterEnvironment and free regions.
rust-lang/rust pull request #41914
Opened 2017-05-11 15:36 UTC by eddyb

The commits describe the slow transformation but the highlights are:
* `ReEarlyBound` is considered free, with a scope based on the item that defined the lifetime parameter, and the root body of the `RegionMaps` in use, removing the need for `free_substs`
* `liberate_late_bound_regions` and `implicit_region_bound` moved to typeck
* `CodeExtent` not interned at all now - ideally it would be 2 `u32` but it's small anyway

Future work building up on this could include:
* `ParameterEnvironment` becoming just the result of `predicates_of`
  * interning makes my "parent chain" scheme unnecessary
* `implicit_region_bound` could be retrieved from `RegionMaps`
* renaming `CodeExtent` to `Scope`
  * generalizing "call site" to "use site" or something better to include constants
* renaming `RegionMaps` to `ScopeTree` and its API to talk about "parents" explicitly

2017-05-11 15:36 UTC, rust-highfive commented
r? @pnkfelix

(rust_highfive has picked a reviewer for you, use r? to override)

2017-05-11 16:55 UTC, nikomatsakis commented
r? @nikomatsakis

2017-05-11 18:18 UTC, nikomatsakis requested changes
OK, this looks pretty nice. I left two small nits.

2017-05-11 18:18 UTC, nikomatsakis commented on src/librustc/infer/region_inference/mod.rs
> +    early_bound_givens: RefCell<FxHashSet<(ty::EarlyBoundRegion, ty::RegionVid)>>,
maybe combine these by changing the type to `RefCell<FxHashSet<(ty::Region<'tcx>, ty::RegionVid)>>`, where the region is either an early-bound or free?

2017-05-11 18:23 UTC, nikomatsakis commented
I see that the `librustc_driver` unit tests are failing. I do hate those. I've been wanting to refactor them in such a way that we can encode the same scenarios in `.rs` files, but it's kind of difficult. I'm tempted to just tell you to delete them -- I'm not sure to what extent we have complete coverage of those scenarios elsewhere though (specifically some of the LUB tests).

2017-05-11 19:20 UTC, eddyb commented on src/librustc/middle/region.rs
> +            let root = tcx.hir.as_local_node_id(fr.scope).unwrap();
This is explained on `root_parent` but do note this is not the final version of that function.
Let me know on the final functions where it seems unclear.

2017-05-11 19:20 UTC, eddyb commented on src/librustc/infer/region_inference/mod.rs
> +    early_bound_givens: RefCell<FxHashSet<(ty::EarlyBoundRegion, ty::RegionVid)>>,
I was wondering if that would be more expensive but I doubt it now. Will do.

2017-05-11 19:28 UTC, arielb1 commented
`CodeExtent` was interned as a u32 once upon a time. Not sure why that changed.

2017-05-11 19:36 UTC, arielb1 commented on src/librustc/middle/region.rs
> +        assert_eq!(param_owner, fr.scope);
Why can't you use `fr.scope` directly?

2017-05-11 19:59 UTC, eddyb commented on src/librustc/middle/region.rs
> +        assert_eq!(param_owner, fr.scope);
I wanted to have no regressions from lifetime parameters not defined on the scope leaking into e.g. the signature of a closure.

2017-05-11 20:01 UTC, nikomatsakis commented
@arielb1 

> `CodeExtent` was interned as a u32 once upon a time. Not sure why that changed.

I changed that to a pointer because there were various contexts that needed to be able to access the data without having enough context to get a region-maps (note that there is now more than one region-maps). But passing by value is probably even better. (Also, in the meantime, we've started to intern Regions, so I don't think that the size matters so much anymore anyway.)

2017-05-12 13:47 UTC, nikomatsakis commented on src/librustc/middle/region.rs
> +            // The lifetime was defined on node that doesn't own a body,
:+1: nice comment

2017-05-12 13:52 UTC, nikomatsakis approved these changes

2017-05-12 13:52 UTC, nikomatsakis commented
@bors r+

2017-05-13 14:43 UTC, eddyb commented
@bors r=nikomatsakis

2017-05-13 17:04 UTC, eddyb commented
@bors p=1000 (separate for perf. I wish we had a guaranteed to keep PRs out of rollups)

2017-05-13 20:19 UTC, merged