Fix anchor invalid redirection to search
rust-lang/rust pull request #41950
Opened 2017-05-12 13:33 UTC by GuillaumeGomez

Fixes #41933.

r? @rust-lang/docs

2017-05-12 15:12 UTC, ollie27 requested changes

2017-05-12 15:12 UTC, ollie27 commented on src/librustdoc/html/static/main.js
> +                        document.getElementsByClassName('search-input')[0].value = params.search;
If `params.search` is `undefined` this should set the value to `""` not `"undefined"` like it currently does.

2017-05-12 15:12 UTC, ollie27 commented on src/librustdoc/html/static/main.js
> +                    if (location.href.indexOf(".html?search=") !== -1) {
This would break clearing the search results so should be removed.

2017-05-12 20:11 UTC, GuillaumeGomez commented on src/librustdoc/html/static/main.js
> +                    if (location.href.indexOf(".html?search=") !== -1) {
It seems it's still working. So not sure if I tested what you had in mind.

2017-05-12 20:11 UTC, GuillaumeGomez commented on src/librustdoc/html/static/main.js
> +                            }
Excellent point!

2017-05-12 20:11 UTC, GuillaumeGomez commented on src/librustdoc/html/static/main.js
> +                        document.getElementsByClassName('search-input')[0].value = params.search;
👍

2017-05-12 20:15 UTC, GuillaumeGomez commented on src/librustdoc/html/static/main.js
> +                    if (location.href.indexOf(".html?search=") !== -1) {
Oh my bad, I need to test on a non local path.

2017-05-12 21:10 UTC, GuillaumeGomez commented on src/librustdoc/html/static/main.js
> +                            }
This was the issue actually. I thought the variable was limited to the scope, big mistake!

2017-05-12 21:10 UTC, GuillaumeGomez commented
Updated.

2017-05-12 23:13 UTC, ollie27 approved these changes

2017-05-13 16:15 UTC, frewsxcv approved these changes

2017-05-13 16:15 UTC, frewsxcv commented
@bors r+ rollup

2017-05-14 05:57 UTC, merged