add thiscall calling convention support
rust-lang/rust pull request #42058
Opened 2017-05-17 13:49 UTC by froydnj

This support is needed for bindgen to work well on 32-bit Windows, and also enables people to begin experimenting with C++ FFI support on that platform.

Fixes #42044.

2017-05-17 13:49 UTC, rust-highfive commented
r? @pnkfelix

(rust_highfive has picked a reviewer for you, use r? to override)

2017-05-18 00:00 UTC, aidanhs commented
Thanks for the PR @froydnj, we'll make sure it gets reviewed by @pnkfelix or another reviewer soon!

2017-05-22 16:43 UTC, carols10cents commented
ping @pnkfelix, pinging you on irc too!

2017-05-23 22:43 UTC, arielb1 commented
r? @japaric 

Actually, I might go and review this myself tomorrow.

2017-05-24 00:08 UTC, nikomatsakis requested changes
r=me with some text in the unstable book, bonus points for opening an issue, but I can do that later

2017-05-24 00:08 UTC, nikomatsakis commented on src/doc/unstable-book/src/language-features/abi-thiscall.md
> +The tracking issue for this feature is: none.
Can we create a tracking issue for this? I think it'd be fine to have one tracking issue covering all the various unstable ABIs. It'd also be nice to actually put a few words in there about what the purpose of this ABI is. If we're going to have a book we might as well write something in it. =)

2017-05-24 21:03 UTC, froydnj commented
Thanks for the review!  Added a bit of text to the book, along with a link to the tracking issue.

r? @nikomatsakis

2017-05-25 08:34 UTC, nikomatsakis approved these changes

2017-05-25 08:34 UTC, nikomatsakis commented
@bors r+

2017-05-25 19:09 UTC, alexcrichton commented
@bors: retry

* https://github.com/rust-lang/rust/pull/42220

2017-05-26 10:18 UTC, merged