Clarify docs on implementing Into.
rust-lang/rust pull request #42126
Opened 2017-05-20 19:26 UTC by clarcharr

This was suggested by @dtolnay in #40380.

This explicitly clarifies in what circumstances you should implement `Into` instead of `From`.

2017-05-20 19:26 UTC, rust-highfive commented
r? @alexcrichton

(rust_highfive has picked a reviewer for you, use r? to override)

2017-05-20 19:32 UTC, dtolnay commented
This works when I tried it. https://play.rust-lang.org/?gist=29711851d1acb274cd4ba9fd3e05d781

```rust
struct Wrapper(String);

impl From<Wrapper> for String {
    fn from(w: Wrapper) -> String {
        w.0
    }
}

fn main() {}
```

2017-05-20 23:04 UTC, Mark-Simulacrum commented
Travis failed:

```
[01:13:49] failures:
[01:13:49]
[01:13:49] ---- convert.rs - convert::Into (line 178) stdout ----
[01:13:49]  thread 'rustc' panicked at 'test compiled while it wasn't supposed to', /checkout/src/librustdoc/test.rs:263
[01:13:49] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:13:49]
[01:13:49] ---- convert.rs - convert::Into (line 194) stdout ----
[01:13:49]  error[E0425]: cannot find value `w` in this scope
[01:13:49]  --> <anon>:7:9
[01:13:49]   |
[01:13:49] 7 |         w.0
[01:13:49]   |         ^ not found in this scope
[01:13:49]
[01:13:49] error[E0053]: method `into` has an incompatible type for trait
[01:13:49]  --> <anon>:6:5
[01:13:49]   |
[01:13:49] 6 | /     fn into(self) -> Wrapper {
[01:13:49] 7 | |         w.0
[01:13:49] 8 | |     }
[01:13:49]   | |_____^ expected struct `std::string::String`, found struct `main::Wrapper`
[01:13:49]   |
[01:13:49]   = note: expected type `fn(main::Wrapper) -> std::string::String`
[01:13:49]              found type `fn(main::Wrapper) -> main::Wrapper`
[01:13:49]
[01:13:49] error: aborting due to previous error(s)
[01:13:49]
[01:13:49] thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc/session/mod.rs:214
[01:13:49] failures:
[01:13:49]     convert.rs - convert::Into (line 178)
[01:13:49]     convert.rs - convert::Into (line 194)
[01:13:49]
[01:13:49] test result: FAILED. 1200 passed; 2 failed; 12 ignored; 0 measured; 0 filtered out
```

2017-05-22 14:38 UTC, steveklabnik requested changes

2017-05-22 14:38 UTC, steveklabnik commented on src/libcore/convert.rs
> +/// ```{.compile_fail}
no need for the `{}`s

2017-05-22 20:32 UTC, dtolnay requested changes
The compile_fail code block actually compiles fine.

2017-05-27 02:24 UTC, shepmaster commented
@clarcharr a gentle reminder that this PR is awaiting your deft hand to fix the failures and respond to review feedback.

2017-05-27 20:06 UTC, clarcharr commented
@shepmaster my deft hand has responded.

2017-05-28 03:44 UTC, Mark-Simulacrum commented
Looks like this still needs a few more updates to get Travis passing.

```
[01:04:37] failures:
[01:04:37] 
[01:04:37] ---- convert.rs - convert::Into (line 191) stdout ----
[01:04:37] 	error[E0053]: method `into` has an incompatible type for trait
[01:04:37]  --> <anon>:6:5
[01:04:37]   |
[01:04:37] 6 | /     fn into(self) -> Wrapper<T> {
[01:04:37] 7 | |         self.0
[01:04:37] 8 | |     }
[01:04:37]   | |_____^ expected struct `std::vec::Vec`, found struct `main::Wrapper`
[01:04:37]   |
[01:04:37]   = note: expected type `fn(main::Wrapper<T>) -> std::vec::Vec<T>`
[01:04:37]              found type `fn(main::Wrapper<T>) -> main::Wrapper<T>`
[01:04:37] 
[01:04:37] error: aborting due to previous error(s)
[01:04:37] 
[01:04:37] thread 'rustc' panicked at 'Box<Any>', /checkout/src/librustc/session/mod.rs:214
[01:04:37] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:04:37] 
[01:04:37] 
[01:04:37] failures:
[01:04:37]     convert.rs - convert::Into (line 191)
[01:04:37] 
[01:04:37] test result: FAILED. 1203 passed; 1 failed; 13 ignored; 0 measured; 0 filtered out
```

2017-05-28 03:51 UTC, clarcharr commented
My deft hand failed me once again :(

(fixed the error)

2017-05-28 12:57 UTC, Mark-Simulacrum commented on src/libcore/convert.rs
> +/// ```.compile_fail
No need for the `.` here.

2017-05-28 20:18 UTC, clarcharr commented on src/libcore/convert.rs
> +/// ```.compile_fail
Fixed

2017-05-28 20:18 UTC, clarcharr commented on src/libcore/convert.rs
> +/// ```{.compile_fail}
I fixed this

2017-05-28 20:18 UTC, clarcharr commented
Rebased and made the changes.

2017-05-28 20:25 UTC, Mark-Simulacrum approved these changes

2017-05-28 20:26 UTC, Mark-Simulacrum commented
r? @steveklabnik

2017-05-30 13:46 UTC, steveklabnik approved these changes

2017-05-30 13:46 UTC, steveklabnik commented
@bors: r+ rollup

thanks!

2017-05-31 23:53 UTC, merged