Decompose Adjustment into smaller steps and remove the method map.
rust-lang/rust pull request #42281
Opened 2017-05-28 13:48 UTC by eddyb

The method map held method callee information for:
* actual method calls (`x.f(...)`)
* overloaded unary, binary, indexing and call operators
* *every overloaded deref adjustment* (many can exist for each expression)

That last one was a historical ~~accident~~ hack, and part of the motivation for this PR, along with:
* a desire to compose adjustments more freely
* containing the autoderef logic better to avoid mutation within an inference snapshot
* not creating `TyFnDef` types which are incompatible with the original one
  * i.e. we used to take a`TyFnDef`'s `for<'a> &'a T -> &'a U` signature and instantiate `'a` using a region inference variable, *then* package the resulting `&'b T -> &'b U` signature in another `TyFnDef`, while keeping *the same* `DefId` and `Substs` from the original
* to fix #3548 by explicitly writing autorefs for the RHS of comparison operators

Individual commits tell their own story, of "atomic" changes avoiding breaking semantics.

Future work based on this PR could include:
* removing the signature from `TyFnDef`, now that it's always "canonical"
  * some questions of variance remain, as subtyping *still* treats the signature differently
* moving part of the typeck logic for methods, autoderef and coercion into `rustc::traits`
* allowing LUB coercions (joining multiple expressions) to "stack up" many adjustments
* transitive coercions (e.g. reify or unsize after multiple steps of autoderef)

r? @nikomatsakis

2017-05-28 16:16 UTC, eddyb commented
Started crater run.

2017-05-28 17:37 UTC, eddyb commented
The current Travis failures are in UI tests due to error output changed (intentionally), e.g.:
```diff
 error[E0277]: the trait bound `{integer}: std::ops::Mul<()>` is not satisfied
-  --> $DIR/binops.rs:14:5
+  --> $DIR/binops.rs:14:7
    |
 14 |     3 * ();
-   |     ^^^^^^ no implementation for `{integer} * ()`
+   |       ^ no implementation for `{integer} * ()`
    |
    = help: the trait `std::ops::Mul<()>` is not implemented for `{integer}`
```

cc @rust-lang/docs @nikomatsakis @jonathandturner Is this is an improvement?

2017-05-28 17:58 UTC, GuillaumeGomez commented
@eddyb: I don't think it is. It should still underline the whole expression.

2017-05-28 18:31 UTC, Mark-Simulacrum commented
I personally consider it an improvement, as it points at the thing that isn't implemented. The operands aren't really part of the problem; making the span as small as possible seems better.

2017-05-28 20:48 UTC, eddyb commented
[Crater report](https://gist.github.com/eddyb/626d1fd2b229c28ea96184b3950f12de) is clean (modulo the usual network errors and lint plugins).

2017-05-28 20:59 UTC, QuietMisdreavus commented
I'm with @Mark-Simulacrum here. The error text still says which specific kind of multiplication isn't implemented, and pointing directly at the operator can save some confusion if it were part of a larger/more complicated expression.

2017-05-29 01:46 UTC, jonathandturner commented
@eddyb - yes, pointing at the offending operator looks like an improvement to me.  As @QuietMisdreavus points out, this becomes more important with larger expressions, but even small ones seem to be a little clearer

2017-05-29 11:59 UTC, eddyb commented
Thanks everyone! I pushed an update to the UI tests.

2017-05-30 22:59 UTC, nikomatsakis requested changes
a few nits, but r=me. Very cool!

2017-05-30 22:59 UTC, nikomatsakis commented on src/librustc/ty/adjustment.rs
> +/// 1. Apply a step of `Adjust` (see its variants for details).
this should say "apply the base transformation described by `kind`", right?

2017-05-30 22:59 UTC, nikomatsakis commented on src/librustc/ty/context.rs
> +        self.expr_adjustments(expr).last()
Nit: I'd find this easier to read if each step in the chain (i.e., `.last()`, `.map()`, and `.or_else()` were on their own line). Or at least `.map()` and `.or_else()`.

2017-05-30 22:59 UTC, nikomatsakis commented on src/libcollections/tests/binary_heap.rs
> +    assert!(**heap.peek().unwrap() == 9);
what's happening here? some lints firing?

2017-05-30 22:59 UTC, nikomatsakis commented on src/test/ui/impl-trait/equality.stderr
> +   |           ^ no implementation for `u32 + impl Foo`
nice

2017-05-30 23:00 UTC, nikomatsakis commented
Regarding the new spans -- yes, I consider it an improvement. I believe this is what clang does. Part of the reason I think this is better: mutil-line spans are terrible, and this avoids that.

2017-05-30 23:00 UTC, nikomatsakis commented
>  some questions of variance remain, as subtyping still treats the signature differently

I was wondering what happened there.

2017-05-30 23:16 UTC, eddyb commented on src/libcollections/tests/binary_heap.rs
> +    assert!(**heap.peek().unwrap() == 9);
Yupp! Comparison operators are now understood by the "unnecessary allocation" lint.

2017-05-30 23:17 UTC, eddyb commented
@nikomatsakis I actually rebased those on top of this branch today, but tried to keep this PR separate.

2017-05-30 23:19 UTC, eddyb commented on src/librustc/ty/adjustment.rs
> +/// 1. Apply a step of `Adjust` (see its variants for details).
What do you mean by "base"? But yeah I could use `kind` and then refer to "variants of `Adjust`".

2017-05-31 08:13 UTC, eddyb commented on src/librustc/ty/adjustment.rs
> +/// 1. Apply a step of `Adjust` (see its variants for details).
Oh look at the latest version of this comment, that was transient.

2017-05-31 08:18 UTC, eddyb commented
@bors r=nikomatsakis

2017-06-01 06:00 UTC, eddyb commented
@bors r=nikomatsakis

2017-06-01 14:03 UTC, merged