Fix signature by adding parens when needed
rust-lang/rust pull request #42318
Opened 2017-05-30 21:02 UTC by GuillaumeGomez

Fixes #42299.

2017-05-30 21:02 UTC, rust-highfive commented
r? @frewsxcv

(rust_highfive has picked a reviewer for you, use r? to override)

2017-05-30 22:08 UTC, QuietMisdreavus commented
Looks good, though I think you'll wind up racing #42286 to the merge since you both mess with the signature of `fmt_type`.

2017-05-30 22:11 UTC, QuietMisdreavus approved these changes

2017-05-30 23:13 UTC, frewsxcv commented
@bors delegate=QuietMisdreavus

2017-05-30 23:30 UTC, QuietMisdreavus commented
@bors r+

2017-05-31 08:07 UTC, GuillaumeGomez commented
I'll improve the priority a bit then.

@bors: p=1

2017-05-31 08:21 UTC, ollie27 requested changes

2017-05-31 08:21 UTC, ollie27 commented on src/librustdoc/html/format.rs
>                  _ => {
I think it would be better to add a case for `ResolvedPath` here to render the parenthesis rather than passing bool parameters everywhere.

2017-05-31 08:21 UTC, ollie27 commented on src/librustdoc/html/format.rs
> +            write!(w, "{}{}{}", if need_paren { "(" } else { "" }, path, last.params)?;
This is missing the `print_all` and `w.alternate()` cases above although that won't be an issue if you render the parenthesis in `fmt_type` itself like I suggest.

2017-05-31 16:08 UTC, merged

2017-05-31 16:14 UTC, GuillaumeGomez commented on src/librustdoc/html/format.rs
>                  _ => {
I'm not sure it'd be better. But don't hesitate to do it if you think it can be improved.