The Rustdoc book
rust-lang/rust pull request #42378
Opened 2017-06-02 12:59 UTC by steveklabnik

A work-in-progress start for docs for rustdoc.

This doesn't actually build yet; I wanted to open this PR to get feedback on this approach, the chapters headings themselves, and to see if anyone wanted to help fill in the ones that aren't done yet.

Start of #42322.

/cc @rust-lang/dev-tools

2017-06-02 12:59 UTC, rust-highfive commented
r? @frewsxcv

(rust_highfive has picked a reviewer for you, use r? to override)

2017-06-02 14:03 UTC, killercup reviewed
Good start. Left a few comments.

FTR, I'd really like the passes chapter to contain the needed args to render all items, even private ones. (I'm pretty sure `cargo doc -- --no-defaults --passes collapse-docs --passes unindent-comments` worked once)

2017-06-02 14:03 UTC, killercup commented on src/doc/rustdoc/src/command-line-arguments.md
> +rustdoc 1.y.0 (hash date)
`hash date`? Never heard of her. (I wouldn't try to make the output generic but give concrete, current outputs. People can easily see the pattern themselves.)

2017-06-02 14:03 UTC, killercup commented on src/doc/rustdoc/src/command-line-arguments.md
> +$ rustdoc --version -v
That looks weird. Either `-v -V` or `--verbose --version`

2017-06-02 14:03 UTC, killercup commented on src/doc/rustdoc/src/command-line-arguments.md
> +Here's the list of arguments you can pass to `rustdoc`:
Maybe add a warning that these **do not** work with `cargo doc`

2017-06-02 14:03 UTC, killercup commented on src/doc/rustdoc/src/what-is-rustdoc.md
> +Internally, this calls out to `rustdoc` like this:
Internally*

\* you can see this with `cargo doc --verbose`

2017-06-02 17:02 UTC, steveklabnik commented
> FTR, I'd really like the passes chapter to contain the needed args to render all items, even private ones. (I'm pretty sure cargo doc -- --no-defaults --passes collapse-docs --passes unindent-comments worked once)

Yup, agreed

2017-06-03 21:26 UTC, frewsxcv approved these changes

2017-06-03 21:38 UTC, frewsxcv requested changes
looking forward to this!

ignore my previous approval, that was an accident

2017-06-03 21:38 UTC, frewsxcv commented on src/doc/rustdoc/src/command-line-arguments.md
> +stable(optmulti("L", "library-path", "directory to add to crate search path",
what's this doing?

2017-06-03 21:38 UTC, frewsxcv commented on src/doc/rustdoc/src/command-line-arguments.md
> +stable(optmulti("L", "library-path", "directory to add to crate search path",
also looks like these `stable(...)` things are used elsewhere in this file

2017-06-03 21:38 UTC, frewsxcv commented on src/doc/rustdoc/src/documentation-tests.md
> +Coming soon!
intending to ship this with the "Coming soon!" test?

2017-06-03 21:38 UTC, frewsxcv commented on src/doc/rustdoc/src/what-is-rustdoc.md
> +The standard Rust distribution ships with a tool called `rustdoc`. It's job is
`s/It's/Its`

2017-06-03 21:38 UTC, frewsxcv commented on src/doc/rustdoc/src/what-is-rustdoc.md
> +$ cargo new docs -- lib
is this supposed to be `--lib`? isn't this the default for `cargo new`?

2017-06-03 21:38 UTC, frewsxcv commented on src/doc/rustdoc/src/what-is-rustdoc.md
> +a function" we put inside the documentation comment in our crate.
could also maybe `rustdoc --open` here, but not mandatory by any means

2017-06-03 21:39 UTC, matthewjasper commented on src/doc/rustdoc/src/what-is-rustdoc.md
> +fn foo() {}
Is this supposed to be `pub fn`?

2017-06-05 14:50 UTC, steveklabnik commented on src/doc/rustdoc/src/command-line-arguments.md
> +stable(optmulti("L", "library-path", "directory to add to crate search path",
i made this page by copy/pasting the source, and must have forgotten to remove these lines 😓

2017-06-05 14:50 UTC, steveklabnik commented on src/doc/rustdoc/src/documentation-tests.md
> +Coming soon!
I am happy shipping this at whatever point, this chapter should be easy to knock out though

2017-06-05 14:51 UTC, steveklabnik commented on src/doc/rustdoc/src/what-is-rustdoc.md
> +fn foo() {}
yes 😓

2017-06-05 17:05 UTC, steveklabnik commented on src/doc/rustdoc/src/command-line-arguments.md
> +Here's the list of arguments you can pass to `rustdoc`:
they dont?

2017-06-05 17:09 UTC, steveklabnik commented
I've pushed up a commit that should address all rustdoc feedback so far.

2017-06-05 17:11 UTC, steveklabnik commented
I think I would like to ship this as-is, and fill out the rest later, but if everyone else wants me to finish it before merging, that's fine as well.

2017-06-05 17:27 UTC, killercup commented on src/doc/rustdoc/src/command-line-arguments.md
> +Here's the list of arguments you can pass to `rustdoc`:
Nope:

```bash
$cargo doc --passes strip-priv-imports
error: Unknown flag: '--passes
…
```

I think it was once possible to do `cargo doc -- args…` but with latest stable:

```bash
$ cargo doc -- --passes strip-priv-imports
error: Invalid arguments.
```

2017-06-05 17:30 UTC, QuietMisdreavus commented on src/doc/rustdoc/src/command-line-arguments.md
> +Here's the list of arguments you can pass to `rustdoc`:
Right, you'd have to use RUSTDOCFLAGS for this, much like RUSTFLAGS for arguments to rustc.

2017-06-05 17:30 UTC, steveklabnik commented on src/doc/rustdoc/src/command-line-arguments.md
> +Here's the list of arguments you can pass to `rustdoc`:
@rust-lang/cargo , is this something that's expected, or a bug? I'm kinda surprised, but I'm sure there's a good reason.

2017-06-07 02:38 UTC, frewsxcv approved these changes
r=me unless you have more changes

2017-06-07 14:54 UTC, steveklabnik commented
@bors: r=frewsxcv 

nope; at least not for now.

2017-06-07 18:12 UTC, merged