Explicate what "Rc" and "Arc" stand for.
rust-lang/rust pull request #42419
Opened 2017-06-04 04:43 UTC by ucarion

A person on the weekly "Easy Questions" Reddit thread [was mystified by what `Arc`/`Rc` means](https://www.reddit.com/r/rust/comments/6dyud9/hey_rustaceans_got_an_easy_question_ask_here/did87ds/). Though this is explained in various places, it's not mentioned in the documentation directly.

This PR adds an explanation of the `Rc`/`Arc` acronyms to their respective documentations. There are two things I'm not sure of:

* Does "Rc" mean "Reference Count**er**" or "Reference Count**ed**"? I went with the former.
* Should this information be spelled out elsewhere, such as in the docs for the `rc` module?

2017-06-04 04:43 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @sfackler (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-06-04 04:44 UTC, sfackler commented on src/liballoc/rc.rs
> +//! Single-threaded reference-counting pointers. "Rc" stands for "Reference
I think of Rc as "reference counted", not "reference counter" personally, and Arc as "atomically reference counted".

2017-06-04 04:44 UTC, sfackler commented
@rust-lang/docs

2017-06-04 04:46 UTC, ucarion commented on src/liballoc/rc.rs
> +//! Single-threaded reference-counting pointers. "Rc" stands for "Reference
After reflection, I was reaching the same conclusion. I'll fix the PR.

2017-06-04 15:23 UTC, abrugh commented
Hey There. Thanks @ucarion for creating a change request for me. Just commenting to add context. [Here's](https://www.reddit.com/r/rust/comments/6dyud9/hey_rustaceans_got_an_easy_question_ask_here/difmp6f/?context=3 ) the comment in question from reddit.

2017-06-05 14:19 UTC, nodakai commented on src/liballoc/rc.rs
> +//! Single-threaded reference-counting pointers. "Rc" stands for "Reference
When I compare "atomically reference-counted" with "atomic reference counter," the tech-jargon-ness of the former seems a bit stronger than that of the latter. Just my personal impression.

2017-06-05 14:53 UTC, steveklabnik commented
> Does "Rc" mean "Reference Counter" or "Reference Counted"? I went with the former. Edit: I've changed this to use the latter alternative.

Yes, the latter is correct.

> Should this information be spelled out elsewhere, such as in the docs for the rc module?

That might be a good idea, yes 😄

2017-06-05 14:54 UTC, steveklabnik requested changes

2017-06-05 14:54 UTC, steveklabnik commented on src/liballoc/arc.rs
> +/// A thread-safe reference-counting pointer. "Arc" stands for "Atomically
Both of these should be single quotes

2017-06-05 19:21 UTC, ucarion commented
>>Should this information be spelled out elsewhere, such as in the docs for the rc module?

>That might be a good idea, yes 😄

@steveklabnik I misspoke -- I had added those docs to the `rc` module all along. With the latest commit, I also added docs to the `Rc` struct as well. (I also switched to single quotes)

2017-06-12 04:08 UTC, frewsxcv commented
This looks great, thanks!

@bors r+ rollup

2017-06-12 06:19 UTC, merged