Add dedicated docstrings to Sum/Product impl of Result
rust-lang/rust pull request #42570
Opened 2017-06-09 20:34 UTC by birkenfeld

(and fix a minor grammar typo below)

2017-06-09 20:34 UTC, rust-highfive commented
r? @alexcrichton

(rust_highfive has picked a reviewer for you, use r? to override)

2017-06-11 15:58 UTC, Mark-Simulacrum commented
r? @frewsxcv -- documentation PR

2017-06-11 16:31 UTC, frewsxcv requested changes

2017-06-11 16:31 UTC, frewsxcv commented on src/libcore/iter/traits.rs
> +    /// Here is an example which sums up every integer in a vector,
As per https://github.com/rust-lang/rfcs/pull/1574, there should be an `# Examples` line before this line

2017-06-11 16:31 UTC, frewsxcv commented on src/libcore/iter/traits.rs
> +    /// assert!(res == Ok(3));
`assert_eq!`

2017-06-11 16:31 UTC, frewsxcv commented on src/libcore/iter/traits.rs
> +    ///     else { Ok(x) }
Your change from https://github.com/rust-lang/rust/pull/42569/files could be copied here

2017-06-12 07:26 UTC, birkenfeld commented on src/libcore/iter/traits.rs
> +    /// Here is an example which sums up every integer in a vector,
Ok.

2017-06-12 07:27 UTC, birkenfeld commented on src/libcore/iter/traits.rs
> +    ///     else { Ok(x) }
Hm, it's not so easy to apply here. Suggestion?

2017-06-12 07:27 UTC, birkenfeld commented on src/libcore/iter/traits.rs
> +    /// assert!(res == Ok(3));
Sure.

2017-06-12 13:54 UTC, frewsxcv commented on src/libcore/iter/traits.rs
> +    ///     else { Ok(x) }
Ah you're right, nevermind

2017-06-12 13:54 UTC, frewsxcv commented
@bors r+ rollup

Thanks!

2017-06-12 16:37 UTC, merged