Avoid allocations in Display for OsStr and Path
rust-lang/rust pull request #42613
Opened 2017-06-12 20:43 UTC by stepancheg

#38879

2017-06-12 20:44 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2017-06-12 21:38 UTC, nikomatsakis requested changes
This looks nice! The main thing seems to be that we should add some targeted unit tests for the new iterator-- I presume, perhaps wrongly, that there are existing tests for the `Display` code in paths...

2017-06-12 21:38 UTC, nikomatsakis commented on src/libstd/path.rs
> +        fmt::Debug::fmt(&self.inner, formatter)
is this just general cleanup, or was this required for some reason?

2017-06-12 21:38 UTC, nikomatsakis commented on src/libstd_unicode/lossy.rs
> +pub struct Utf8LossyIter<'a> {
can we write some more unit tests for this? it seems like quite a big chunk of code, and one for which it'd be easy to write some targeted unit tests...

2017-06-13 10:43 UTC, stepancheg commented on src/libstd/path.rs
> +        fmt::Debug::fmt(&self.inner, formatter)
I've made several similar changes for these reasons:

* it is easier to visually check that correct trait is called (`Debug` or `Display`)
* to make sure code on Windows and Redox (e. g. `os_str::Slice`) works correctly. I do not have access to Windows machine, so it's easier to write code uniformly (single `fmt` import and explicit trait names) than wait for build system job completion
* and after all to unify all implementations in stack `os_str`, `OsStr`, `Path`

2017-06-13 12:11 UTC, arthurprs commented on src/libcollections/string.rs
> +        let mut res = String::with_capacity(v.len());
We know it'll be larget than v.len right? Maybe reserve some extra, maybe v.len() * 3 / 2?

2017-06-13 12:26 UTC, stepancheg commented on src/libcollections/string.rs
> +        let mut res = String::with_capacity(v.len());
Probably. If yes, this should be done in separate PR. I've just kept this part as it was before my patch.

2017-06-13 12:32 UTC, stepancheg commented
I've added tests (copied from `String::from_utf8_lossy` tests).

2017-06-13 14:55 UTC, stepancheg commented
Some tests broken, wait a bit...

2017-06-13 20:35 UTC, stepancheg commented
There's a tidy check error:

```
tidy error: /Users/yozh/devel/left/rust/src/libstd/ffi/os_str.rs:321: different `since` than before
tidy error: /Users/yozh/devel/left/rust/src/libstd/ffi/os_str.rs:685: different `since` than before
```

There were no `Display` for `OsStr` and `OsString` which are need to implement `Display` for `Path` and which I've added. What should I do?

I've added

```
#[stable(feature = "rust1", since = "1.20.0")]
```

which is apparently incorrect.

2017-06-14 19:23 UTC, nikomatsakis approved these changes

2017-06-14 19:30 UTC, nikomatsakis commented
Going to pass the buck here. I'm not that familiar with the attributes that need to be set.

r? @alexcrichton

2017-06-14 19:53 UTC, alexcrichton commented on src/libstd/ffi/os_str.rs
> +impl fmt::Display for OsString {
This did not exist before and is a new stable feature being added in this PR, is that intentional? It was the libs team intention that this impl did *not* exist.

2017-06-14 19:58 UTC, alexcrichton commented on src/libcore/fmt/mod.rs
> +pub fn escape_str(s: &str, f: &mut Formatter) -> Result {
Can this avoid being exposed? It seems like a reasonable amount that's not too bad to just copy directly into the new iterator.

2017-06-15 07:28 UTC, stepancheg commented on src/libstd/ffi/os_str.rs
> +impl fmt::Display for OsString {
`Display` for `OsString` seems to be perfectly reasonable for me. You may need to "display" an OS string like you "display" the usual string.

Anywhay, if it should exist, how should I mute `tidy`?

If it shouldn't exist, how should I keep an implementation, but hide it from public API? `#[doc(hidden)]` and `#[unstable(feature = "str_internals", issue = "0")]`?

2017-06-15 14:19 UTC, alexcrichton commented on src/libstd/ffi/os_str.rs
> +impl fmt::Display for OsString {
Whether or not it's reasonable it is intentionally excluded and should not be added in this PR. If you'd like to add it then that should be done through a separate PR or an RFC.

This shouldn't exist, which means it should be deleted (along with most other `Display` impls added here)

2017-06-15 19:42 UTC, stepancheg commented
Updated the PR.

* Removed public `Display` implementations (kept implementations for private types in `os_str`)
* Copied implementation of `Debug` for `str` to `Debug` for `Utf8Lossy` instead of extraction of `escape_str` function

2017-06-16 14:46 UTC, alexcrichton commented
@bors: r+

2017-06-17 04:36 UTC, merged