New error codes
rust-lang/rust pull request #42614
Opened 2017-06-12 21:54 UTC by GuillaumeGomez

Part of #42229.

cc @Susurrus @frewsxcv @QuietMisdreavus

2017-06-12 21:54 UTC, rust-highfive commented
r? @pnkfelix

(rust_highfive has picked a reviewer for you, use r? to override)

2017-06-12 22:07 UTC, Susurrus requested changes

2017-06-12 22:07 UTC, Susurrus commented on src/librustc_typeck/diagnostics.rs
> +If a tuple/tuple-struct type has x fields, you can only try to access these x
I'd suggest using "n" here instead of "x" as "n" is commonly used for referring to integer values.

2017-06-12 22:07 UTC, Susurrus commented on src/librustc_typeck/diagnostics.rs
> +If you want to index an array, use `[]` instead:
Instead "If you want to index **into** an array, use `[]` instead:"

2017-06-12 22:07 UTC, Susurrus commented on src/librustc_typeck/diagnostics.rs
> +Attempted to dereference a variable which cannot be.
Reads awkwardly, instead: "Attempted to dereference a variable which cannot be dereferenced."

2017-06-12 22:07 UTC, Susurrus commented on src/librustc_typeck/diagnostics.rs
> +Only types implementing `std::ops::Deref` can be dereferenced (such as `&T` for
"such as" and "for examples" are redundant. I suggest doing just "(such as `&T`)"

2017-06-12 22:07 UTC, Susurrus commented on src/librustc_typeck/diagnostics.rs
> +However, if you wanted to access a field, of the struct, check if you didn't
Too many commas and incorrect conjugation. Instead "However, if you wanted to access a field of a struct check that the field name is spelled correctly."

2017-06-12 22:07 UTC, Susurrus commented on src/librustc_typeck/diagnostics.rs
> +Attempted to access to a private field on a struct.
Instead "Attempted to access a private field on a struct."

2017-06-12 22:07 UTC, Susurrus commented on src/librustc_typeck/diagnostics.rs
> +First one: set the field public:
Instead: "1) Set the field public:"

I don't like the double-colons on this line.

2017-06-12 22:07 UTC, Susurrus commented on src/librustc_typeck/diagnostics.rs
> +Second one: add a getter function:
Instead "2) Add a getter function:"

2017-06-12 22:07 UTC, Susurrus commented on src/librustc_typeck/check/mod.rs
> +                               "attempted tuple index `{}` on type `{}`, but the type was not a \
I suggest instead: "attempted **to access** tuple index `{}` on type `{}`, but the type **is** not a tuple or tuple struct"

2017-06-12 22:30 UTC, GuillaumeGomez commented
@Susurrus: Thanks a lot for this review! Updated. :)

2017-06-13 04:07 UTC, frewsxcv reviewed
Travis found some errors

2017-06-13 04:07 UTC, frewsxcv commented on src/librustc_typeck/diagnostics.rs
> +If you want to index into an array, use `[]` instead:
> index into a slice

would this be more accurate?

2017-06-13 04:07 UTC, frewsxcv commented on src/librustc_typeck/diagnostics.rs
> +If you want to access a field of a struct, check the field's name wasn't
> If you want to access a field of a struct, ensure the field's name is spelled correctly

this sounds better to me, but i don't feel strongly

2017-06-13 18:05 UTC, GuillaumeGomez commented on src/librustc_typeck/diagnostics.rs
> +If you want to index into an array, use `[]` instead:
I wanted to include both Vec and slices.

2017-06-15 08:32 UTC, GuillaumeGomez commented
Rebased.

2017-06-15 17:10 UTC, QuietMisdreavus commented
Would it be worth combining E0611 (private field access, tuple struct) and E0616 (private field access, traditional struct)? From the user's perspective, it's the same error, just in different situations.

2017-06-22 14:42 UTC, alexcrichton commented
ping @pnkfelix, I think this is ready for a re-review

2017-06-22 20:11 UTC, pnkfelix commented on src/librustc_typeck/diagnostics.rs
> +If you want to index into an array, use `[]` instead:
In the context of Rust, when I see the term "array" I often think of fixed-length arrays `[T; n]`. But I don't have a better term on hand that covers the cases here, so this is fine with me.

2017-06-22 20:14 UTC, pnkfelix commented
@bors r+

2017-06-23 00:25 UTC, merged