incr.comp.: Make DepNode's std::fmt::Debug implementation useful again.
rust-lang/rust pull request #42625
Opened 2017-06-13 10:28 UTC by michaelwoerister

With #42537 a regular `DepNode` only contains an opaque hash as its identifier. In most cases, this hash is actually a `DefPathHash` and we can reconstruct the `DefId` it came from via a table lookup --- and then use that to print something intelligible for debug outputs. For cases where we cannot reconstruct information from the DepNode's hash, this PR will cache a string representation of the `DepNode` in a side-table. This string is later used for debug outputs.

r? @nikomatsakis

2017-06-13 15:06 UTC, nikomatsakis approved these changes

2017-06-13 15:06 UTC, nikomatsakis commented
@bors r+

2017-06-13 15:07 UTC, nikomatsakis commented
@bors r-

2017-06-13 15:07 UTC, nikomatsakis requested changes

2017-06-13 15:07 UTC, nikomatsakis commented on src/librustc/dep_graph/dep_node.rs
> +        let def_path_hash_1 = tcx.def_path_hash(def_id_1);
it'd be good to add a comment clarifying that this is a micro-opt, and the generic impl also suffices

2017-06-13 15:12 UTC, nikomatsakis approved these changes

2017-06-13 15:12 UTC, nikomatsakis commented
@bors r+

2017-06-14 09:45 UTC, michaelwoerister commented
@bors retry

(looks like a time-out)

2017-06-14 20:56 UTC, Mark-Simulacrum commented
@bors retry
 - timeout

2017-06-14 21:42 UTC, alexcrichton commented
Hm so the [timed out build](https://travis-ci.org/rust-lang/rust/jobs/242913446) compared to the [previous successful build](https://travis-ci.org/rust-lang/rust/jobs/242787492) shows that  stage0-rustc jumped from 1000s to 2600s and stage1-rustc jumped from 1300s to 3500s.

This PR doesn't seem particularly at fault, I'm messaging Travis to hopefully clarify

2017-06-15 09:11 UTC, merged