Add ‘#[serial]’ tests (v2)
rust-lang/rust pull request #42684
Opened 2017-06-15 19:52 UTC by shivjm

(Fixed version of #42626; sorry for the noise.)

This PR adds a `#[serial]` attribute that marks tests that should be executed one-by-one rather than concurrently (per #33519).

I’ve confirmed that the libtest and tidy tests pass. I wasn’t able to run the full suite as a lot of the run_make tests seem to fail on my Windows system, but everything passed up to that point.

Rust (and PR!) newbie here, so please do let me know if I’m doing something poorly or incorrectly!

2017-06-15 19:52 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @brson (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-06-15 20:26 UTC, leonardo-m commented
Perhaps a name like `#[serial_test]` is better?

2017-06-15 20:32 UTC, Mark-Simulacrum commented
I think `#[serial]` is fine given that `#[test]` will also be there, but I could see an argument being made that serial is too generic a name. I do think this needs a feature gate though, which I believe hasn't yet been implemented. I could be wrong though.

2017-06-15 21:51 UTC, shivjm commented
Ah, I didn’t understand how the feature gates work and the example I followed (#42219) is apparently a WIP. Looking at #42088, I need to gate this by:

1. Adding an entry to the `declare_features` block in feature_gate.rs with a feature name, a version, and an issue number:
 ```rust
(active, serial_tests, "1.19.0", Some(42684))
```
2. Specifying `AttributeGate::Gated` for the `serial` attribute in `BUILTIN_ATTRIBUTES` (same file), which needs a feature name, an explanation, and a function to check its configuration (auto-generated using `cfg_fn`):
 ```rust
("serial", Normal, Gated(Stability::Unstable, "serial_tests", "the `#[serial]` attribute is an experimental feature", cfg_fn!(serial_tests))
```
3. Adding a new document under `unstable-book/src/language-features/` that points to this PR.
4. Adding an entry under `unstable-book/src/SUMMARY.md` that points to that document.

Is this correct? Have I missed anything? I’ll try to get it done pronto, but if not, it will be about a week.

Re: the name of the attribute itself, I can change that if `serial` is too generic.

2017-06-20 12:14 UTC, bjorn3 requested changes
Few minor things. Overal code looks good to me.

2017-06-20 12:14 UTC, bjorn3 commented on src/libsyntax/test.rs
> +    serial: bool
Please end the line with a comma, so there is less noise when new fields get added.

2017-06-20 12:14 UTC, bjorn3 commented on src/libsyntax/test.rs
> +                        serial: is_serial(&i)
Same here

2017-06-20 12:14 UTC, bjorn3 commented on src/libtest/lib.rs
> +                    serial: true
Same here

2017-06-20 12:14 UTC, bjorn3 commented on src/libtest/lib.rs
> +                    serial: true
Same here

2017-06-20 12:14 UTC, bjorn3 commented on src/libtest/lib.rs
> +                    panic!("result not okay"),
Please print the result too. Eg
```rust
panic!("result not okay: {:?}", result),
```

2017-06-20 12:14 UTC, bjorn3 commented on src/libtest/lib.rs
> +                    panic!("result not okay"),
Same printing thing here.

2017-06-25 00:45 UTC, Mark-Simulacrum commented
@shivjm I believe this is waiting on some changes from you and a rebase. Let us know if we can help in any way! Feel free to ping me on IRC (simulacrum).

2017-06-25 18:38 UTC, shivjm commented
Sorry, been out of town and then busy catching up! I’ve rebased the PR and (I hope) fixed the issues @bjorn3 pointed out. Next up, need to implement the feature gate. I’ll ping you on IRC.

2017-06-25 20:34 UTC, shivjm commented
I’ve added the `serial_tests` feature gate. @est31, does this need an entry under `unstable-book` as well?

2017-06-26 06:11 UTC, est31 commented
> does this need an entry under unstable-book as well?

The requirement for an entry has been removed. You can add one (with meaningful content) if you want to, if not, a stub will be generated automatically.

2017-06-26 06:15 UTC, bjorn3 requested changes
Lgtm when the trailing newline is added.

2017-06-26 06:15 UTC, bjorn3 commented on src/test/compile-fail/feature-gate-serial_tests.rs
> +}
Please add a trailing newline.

2017-06-26 06:19 UTC, shivjm commented
Done, thanks!

2017-06-26 06:20 UTC, bjorn3 approved these changes

2017-06-27 21:47 UTC, brson commented
Thanks for the patch.

This probably needs more discussion before landing. This is a thing that we've declined to do for many years.

2017-06-27 23:00 UTC, brson commented
cc @nrc

2017-07-03 12:00 UTC, Aankhen commented
Is there anything I can do to help?

2017-07-03 12:02 UTC, shivjm commented
Is there anything I can do to help?

2017-07-10 05:41 UTC, nrc commented
@brson do you have links to previous discussion or could you summarise here please? My opinion (uninformed by previous discussion) is that this is something I've wanted personally and I don't see why we should not support it (as long as it is feature gated etc.) being its own attribute feels kind of wrong (I'd prefer to attach it to `#[test]`, but I suppose that `#[should_panic]` is a precedent?)

2017-07-10 20:20 UTC, nrc commented
Discussed at the dev-tools meeting today, this problem can be solved today using a mutex (I filed https://github.com/rust-lang/rust/issues/43155 to document that). Given that this solution feels somewhat ad hoc and there is workaround, we would prefer to punt on adding this in favour of custom test runners or some other long-term solution.

Thanks for the PR @shivjm and sorry to close it out after your work.

2017-07-10 20:20 UTC, closed without merging

2017-07-11 09:46 UTC, shivjm commented
Alright. Thanks for letting me know.

2018-02-21 13:38 UTC, yshui commented
@nrc I don't see why this should be implemented in the test framework. The mutex work around seems to have some catches, and is non-trivial to get right.

2019-04-05 10:12 UTC, DevQps commented
For everyone getting to this point: This solution is also implemented in a separate crate now: [`serial_test`](https://crates.io/crates/serial_test)