Add docs for Debug* structs. #29355
rust-lang/rust pull request #42836
Opened 2017-06-22 19:53 UTC by rthomas

This adds docs for the Debug* structs as well as examples from the
Formatter::debug_* methods, so that a user knows how to construct them.

I added these examples as the builders module is not public and hence
the debug_*_new() functions are not available to a user.

r? @steveklabnik

2017-06-22 19:53 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @steveklabnik (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-06-27 21:34 UTC, GuillaumeGomez commented on src/libcore/fmt/builders.rs
> +/// `Debug::fmt` implementation.
Missing the url to the corresponding struct.

2017-06-27 21:35 UTC, GuillaumeGomez commented on src/libcore/fmt/builders.rs
> +/// This can be constructed by the `Formatter::debug_struct` method.
Missing the url to the corresponding struct.

2017-06-27 21:35 UTC, GuillaumeGomez commented on src/libcore/fmt/builders.rs
> +///             .field("bar", &self.bar)
Indent is a bit off: should be aligned to ".debug_struct".

2017-06-27 21:35 UTC, GuillaumeGomez commented on src/libcore/fmt/builders.rs
> +/// `Debug::fmt` implementation.
Missing the url to the corresponding struct.

2017-06-27 21:35 UTC, GuillaumeGomez commented on src/libcore/fmt/builders.rs
> +/// This can be constructed by the `Formatter::debug_tuple` method.
Missing the url to the corresponding method.

2017-06-27 21:36 UTC, GuillaumeGomez commented on src/libcore/fmt/builders.rs
> +/// of your `Debug::fmt` implementation.
Missing the url to the corresponding struct.

2017-06-27 21:36 UTC, GuillaumeGomez commented on src/libcore/fmt/builders.rs
> +/// This can be constructed by the `Formatter::debug_set` method.
Missing the url to the corresponding method.

2017-06-27 21:36 UTC, GuillaumeGomez commented on src/libcore/fmt/builders.rs
> +/// of your `Debug::fmt` implementation.
Missing the url to the corresponding struct.

2017-06-27 21:36 UTC, GuillaumeGomez commented on src/libcore/fmt/builders.rs
> +/// This can be constructed by the `Formatter::debug_list` method.
Missing the url to the corresponding method.

2017-06-27 21:36 UTC, GuillaumeGomez commented on src/libcore/fmt/builders.rs
> +/// `Debug::fmt` implementation.
Missing the url to the corresponding struct.

2017-06-27 21:36 UTC, GuillaumeGomez commented on src/libcore/fmt/builders.rs
> +/// This can be constructed by the `Formatter::debug_map` method.
Missing the url to the corresponding method.

2017-07-01 17:30 UTC, rthomas commented
Thanks, I've addressed all of the comments.

2017-07-02 16:14 UTC, GuillaumeGomez requested changes
Just one last nit and it should be good!

2017-07-02 16:14 UTC, GuillaumeGomez commented on src/libcore/fmt/builders.rs
> +/// ```rust
No need to add `rust` tag. By default, every code block is a rust one.

2017-07-02 16:14 UTC, GuillaumeGomez commented on src/libcore/fmt/builders.rs
> +/// ```rust
Same.

2017-07-02 16:14 UTC, GuillaumeGomez commented on src/libcore/fmt/builders.rs
> +/// ```rust
Same.

2017-07-02 16:14 UTC, GuillaumeGomez commented on src/libcore/fmt/builders.rs
> +/// ```rust
Same.

2017-07-02 16:14 UTC, GuillaumeGomez commented on src/libcore/fmt/builders.rs
> +/// ```rust
Same.

2017-07-02 16:15 UTC, GuillaumeGomez commented
Also, once updated, can you [squash your commits](https://blog.guillaume-gomez.fr/Git-tips/1/2) to only have one please?

2017-07-02 16:43 UTC, rthomas commented
Fixed the rust tags on code blocks and squashed the commits.

2017-07-03 09:32 UTC, GuillaumeGomez commented
Thanks!

@bors: r+ rollup

2017-07-03 12:10 UTC, rthomas commented
I'm unsure why this docs change is failing, coudl the test be flakey?

This is from the build logs:

```
[00:59:34] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "-j" "4" "--target" "x86_64-unknown-linux-musl" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "--features" "panic-unwind jemalloc backtrace" "-p" "std:0.0.0" "-p" "rustc_lsan:0.0.0" "-p" "std_unicode:0.0.0" "-p" "collections:0.0.0" "-p" "unwind:0.0.0" "-p" "alloc:0.0.0" "-p" "rustc_tsan:0.0.0" "-p" "compiler_builtins:0.0.0" "-p" "libc:0.0.0" "-p" "panic_abort:0.0.0" "-p" "rand:0.0.0" "-p" "core:0.0.0" "-p" "rustc_msan:0.0.0" "-p" "rustc_asan:0.0.0" "-p" "alloc_system:0.0.0" "--"
[00:59:34] expected success, got: exit code: 101
[00:59:34] 
[00:59:34] 
[00:59:34] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test --target x86_64-unknown-linux-musl
[00:59:34] Build completed unsuccessfully in 0:58:11
```

2017-07-03 13:10 UTC, GuillaumeGomez commented
Hum, strange...

2017-07-03 13:10 UTC, GuillaumeGomez approved these changes

2017-07-03 17:30 UTC, alexcrichton commented
@bors: retry

2017-07-04 18:26 UTC, merged