Implement const fn {size,align}_of.
rust-lang/rust pull request #42859
Opened 2017-06-23 14:52 UTC by eddyb

Fixes #34078.

r? @nikomatsakis

2017-06-27 19:37 UTC, nikomatsakis requested changes
One nit, one question I just wanted to clarify.

2017-06-27 19:37 UTC, nikomatsakis commented on src/libcore/mem.rs
> +pub const fn size_of<T>() -> usize {
Not that I necessarily object to this, but this would be an "insta-stable" change, right?

2017-06-27 19:37 UTC, nikomatsakis commented on src/librustc_mir/transform/qualify_consts.rs
> +                            _ => {}
maybe add `assert!(!self.tcx.is_const_fn(def_id))`?

2017-06-27 19:38 UTC, nikomatsakis commented
This is pretty simple. =)

2017-06-27 19:43 UTC, SimonSapin commented on src/libcore/mem.rs
> +pub const fn size_of<T>() -> usize {
This change itself yes, but calling any function in a const context still requires `#[feature(const_fn)]`.

2017-06-27 19:48 UTC, eddyb commented
@nikomatsakis Yeah, this could've been done months ago...

2017-06-27 21:16 UTC, nikomatsakis commented
on IRC, @eddyb noted that we ought to have some tests. Indeed! 

I'm basically happy here. @rust-lang/lang -- everybody happy with making `size_of` and `align_of` "const fns"?

2017-06-27 21:17 UTC, nikomatsakis commented on src/libcore/mem.rs
> +pub const fn size_of<T>() -> usize {
Oh, does it? I thought we enabled calls, but not declarations, of const fns.

2017-06-27 21:17 UTC, nikomatsakis commented on src/libcore/mem.rs
> +pub const fn size_of<T>() -> usize {
Or at least I couldn't remember which it is.

2017-06-27 21:17 UTC, nikomatsakis commented
r=me with tests, presuming that it still takes a feature gate to call a const fn

2017-06-27 21:27 UTC, whitequark commented
Can we unreserve `sizeof` and `alignof` now? :D Presumably `offsetof` actually has to be a keyword, at least I don't see an elegant way to implement it with `const fn`s alone. Could be a builtin macro though.

2017-06-27 21:34 UTC, eddyb commented
@whitequark I would wait until you can use these functions from constants in stable.
I'm surprised we even bothered to reserve them! I only really want a keyword for `typeof` 😇.

2017-06-27 21:38 UTC, whitequark commented
> I only really want a keyword for typeof .

What about `offsetof`? The uses are pretty marginal but when you need them, you do need them...

2017-06-27 21:41 UTC, SimonSapin commented on src/libcore/mem.rs
> +pub const fn size_of<T>() -> usize {
There’s discussion of doing this, but it hasn’t happened yet as far as https://github.com/rust-lang/rust/issues/24111 says.

2017-06-27 21:47 UTC, eddyb commented
@whitequark I'd just use a macro for that. Or have some sort of static reflection capabilities that allow e.g. "indexing by a field" to access the value, *safely* etc.

2017-06-27 21:53 UTC, retep998 commented
I *really* want `offsetof` because it would make working with unsized structs for FFI *so* much easier.

2017-06-27 22:04 UTC, whitequark commented
> I really want offsetof because it would make working with unsized structs for FFI so much easier.

I think it shouldn't be a lot of work to implement... I wish I had more time to work on rustc.

2017-06-28 20:18 UTC, alevy commented
This rocks so hard!

2017-07-03 02:37 UTC, durka commented on src/libcore/mem.rs
> +pub const fn size_of<T>() -> usize {
#43017

2017-07-03 15:52 UTC, aturon commented
@nikomatsakis sounds great to me!

2017-07-05 04:52 UTC, durka commented
```
[00:10:31] error[E0061]: this function takes 1 parameter but 0 parameters were supplied
[00:10:31]    --> /checkout/src/librustc_const_eval/eval.rs:344:34
[00:10:31]     |
[00:10:31] 344 |           if tcx.type_of(def_id).fn_sig().abi() == Abi::RustIntrinsic {
[00:10:31]     |                                  ^^^^^^ expected 1 parameter
[00:10:31]
[00:10:32] error: aborting due to previous error(s)
[00:10:32]
[00:10:32] error: Could not compile `rustc_const_eval`.
```

2017-07-06 21:26 UTC, nikomatsakis approved these changes

2017-07-06 22:03 UTC, eddyb commented
@nikomatsakis There are still no testcases FWIW.

2017-07-07 16:13 UTC, nikomatsakis commented
@eddyb 

> There are still no testcases FWIW.

Oh, my bad. Well, merge conflict anyway. ;)

2017-07-17 10:13 UTC, nikomatsakis commented
Still waiting on tests. =)

2017-07-19 11:49 UTC, eddyb commented
@bors r=nikomatsakis

2017-07-19 11:58 UTC, retep998 commented
Macs are having some issues on travis
```
The command "curl -fo /usr/local/bin/sccache https://s3.amazonaws.com/rust-lang-ci/rust-ci-mirror/2017-05-12-sccache-x86_64-apple-darwin" failed 3 times.
```
```
The command "brew update" failed 3 times.
```

2017-07-19 12:21 UTC, kennytm commented
@retep998 https://www.traviscistatus.com/incidents/74lc35kpxs0y

>  Due to a regression, some OSX builds have briefly been routed to Linux images. This has change been reverted. We are closely monitoring the situation. Restarting a affected jobs should run the build on the right infrastructure. We apologize for the inconveniences caused.

2017-07-19 12:26 UTC, Mark-Simulacrum commented
@bors retry

2017-07-19 12:33 UTC, retep998 commented
I wonder which revocation server is offline and who is responsible for keeping it online?
```
  [35] SSL connect error (schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.)
```

2017-07-19 12:36 UTC, kennytm commented
@retep998 Probably related https://appveyor.statuspage.io/incidents/m2vdvw39kdk8

> The issue is a "broken" route between Rackspace data center and US-based CDN edge server for api.nuget.org. Unfortunately, there is no ETA yet. We continue working with nuget team to resolve the issue as soon as possible.

2017-07-19 14:12 UTC, alexcrichton commented
@bors: retry

On Wed, Jul 19, 2017 at 7:36 AM, kennytm <notifications@github.com> wrote:

> @retep998 <https://github.com/retep998> Probably related
> https://appveyor.statuspage.io/incidents/m2vdvw39kdk8
>
> The issue is a "broken" route between Rackspace data center and US-based
> CDN edge server for api.nuget.org. Unfortunately, there is no ETA yet. We
> continue working with nuget team to resolve the issue as soon as possible.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/42859#issuecomment-316371754>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAD95IA6tLAJQ2VF5zisqDTO26V5BFK2ks5sPfhDgaJpZM4ODqxq>
> .
>

2017-07-19 14:18 UTC, Mark-Simulacrum commented
@bors retry -- appveyor revocation certs, appears to be fixed once https://github.com/rust-lang/rust/pull/43333 lands.

2017-07-19 20:12 UTC, merged