Document possible `io::ErrorKind`s of `fs::open`
rust-lang/rust pull request #42925
Opened 2017-06-27 10:10 UTC by tbu-

Try to make clear that this isn't an API guarantee for now, as we likely
want to refine these errors in the future, e.g. `ENOSPC` "No space left
on device".

CC #40322

2017-06-27 10:14 UTC, tbu- commented
I'd also try the other `fs` function if this format is OK.

2017-06-27 21:50 UTC, arielb1 commented
r? @GuillaumeGomez

2017-06-28 02:14 UTC, frewsxcv commented on src/libstd/fs.rs
> +    ///   `create_new` is set,
This should end in a period

2017-06-28 09:05 UTC, GuillaumeGomez commented on src/libstd/fs.rs
> +    /// with their [`ErrorKind`]. The mapping to `ErrorKind`s is not part of
Missing link to the second `ErrorKind`.

2017-06-28 09:06 UTC, GuillaumeGomez requested changes
For every type/enum variant, could you add the corresponding url please?

2017-06-28 11:47 UTC, tbu- commented
Added the URLs.

I had to look at the HTML source in order to find the right links, should I open a rustdoc bug about that?

2017-06-28 13:04 UTC, GuillaumeGomez commented
There is a RFC incoming in order to make links easier to write.

2017-06-28 13:04 UTC, GuillaumeGomez approved these changes

2017-06-28 13:04 UTC, GuillaumeGomez commented
Thanks!

@bors: r+ rollup

2017-07-01 00:34 UTC, merged