Fold E0612, E0613 into E0609
rust-lang/rust pull request #42996
Opened 2017-06-30 21:24 UTC by Boreeas

As discussed in #42945, with PR 1506 tuple indices are no longer considered a separate case from normal field. This PR folds E06012 ("tuple index out of bounds") and E0613 ("type is not a tuple") into E0609 ("type does not have field with that name")

Resolves #42945

2017-06-30 21:24 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @pnkfelix (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-06-30 22:59 UTC, Boreeas commented
My apologies, I forgot to run the full test suite and apparently missed something.

2017-07-01 12:08 UTC, Boreeas commented
All tests pass now on my end

2017-07-02 00:32 UTC, Mark-Simulacrum commented
Thanks for the pull request! We'll get @pnkfelix or someone else from the compiler team to review this soon.

cc @GuillaumeGomez -- perhaps you'd like to take a look since I believe you created some of these in the first place?

2017-07-02 11:13 UTC, GuillaumeGomez commented on src/librustc_typeck/check/mod.rs
> -            type_error_struct!(self.tcx().sess, expr.span, expr_t, E0612,
I feel like this error is a bit different than the others. Not sure if this is a good idea to merge it as well...

2017-07-02 11:17 UTC, GuillaumeGomez requested changes
I really think we should keep E0612 on its own and not merge it with others.

2017-07-02 11:17 UTC, GuillaumeGomez commented on src/librustc_typeck/check/mod.rs
> +
Extra empty line.

2017-07-02 11:17 UTC, GuillaumeGomez commented on src/librustc_typeck/diagnostics.rs
> +// E0612: Removed (merged with E0609)
Please put them into the error code list at the bottom.

2017-07-02 11:17 UTC, GuillaumeGomez commented on src/test/compile-fail/issue-19244-1.rs
> +    //~^ ERROR no field `1` on type `(usize,)`
This error is clearly less good from my point of view. Before it was very clear but now, seems more confusing.

2017-07-02 21:47 UTC, Boreeas commented
@GuillaumeGomez Alright, reverted the changes to E0612

2017-07-03 09:33 UTC, GuillaumeGomez approved these changes

2017-07-03 09:34 UTC, GuillaumeGomez commented
Thanks! Please [squash](https://blog.guillaume-gomez.fr/Git-tips/1/2) your commits and then it's good for me.

2017-07-06 14:41 UTC, alexcrichton commented
ping @GuillaumeGomez, looks like this has been updated and is ready for a re-review?

2017-07-06 20:08 UTC, GuillaumeGomez commented
The review was done, I was waiting for the squash. Since it's done, we can r+. Thanks @Boreeas!

@bors: r+

2017-07-06 20:41 UTC, Boreeas commented
No problem! My apologies for not sending a notice that I squashed

2017-07-07 21:44 UTC, Boreeas commented
Rebased the PR

2017-07-08 15:11 UTC, GuillaumeGomez commented
Then here we go again!

@bors: r+

2017-07-08 17:30 UTC, merged