Clean up some code
rust-lang/rust pull request #43006
Opened 2017-07-01 13:42 UTC by GuillaumeGomez

From #42669.

r? @nikomatsakis

2017-07-05 19:12 UTC, GuillaumeGomez commented
ping @nikomatsakis 

Or if anyone else wants to review it?

2017-07-05 22:08 UTC, aidanhs commented
I pinged @nikomatsakis on IRC for review a bit earlier.

2017-07-07 17:08 UTC, nikomatsakis requested changes
What do you think of [this as an alternate long explanation](https://gist.github.com/nikomatsakis/ca5c028851749bd4e871cefbdd2a4e4e)? In your version, there were some grammatical errors, and I've tried to keep the overall flow of the explanation, while respecting the overall "error code template" laid out in RFC 1567.

2017-07-07 22:57 UTC, GuillaumeGomez commented
Well, it seems good to me so I'll take yours. Thanks for the review!

2017-07-07 23:04 UTC, GuillaumeGomez commented
Ok updated.

2017-07-10 17:45 UTC, nikomatsakis approved these changes

2017-07-10 17:45 UTC, nikomatsakis commented
@bors r+

2017-07-11 08:31 UTC, GuillaumeGomez commented
@bors: r=nikomatsakis

2017-07-11 12:36 UTC, merged