Add inline annotations and avoid 128-bit where it's not needed in TryFrom
rust-lang/rust pull request #43194
Opened 2017-07-12 20:54 UTC by oyvindln

This should make the output in #43064 slightly cleaner, and hopefully help fix #43124 when combined with #43127. I think the main issue was the lack of inline annotations for `try_from` (and not the use of 128-bit values as I first thought). Additionally, the implementations of try_from called min/max_value through the FromStrRadixHelper trait, which weren't marked inline either. I would have thought LLVM would be smart enough to inline this anyway, but it seems it isn't. While there has been talk about [moving to a `Cast`]( #42456) trait for number types, it looks like it will take a while before that can happen, so this should help a bit in the meantime.

I didn't do any pointer width specific implementations for now. 

This change also makes the assumption that i/usize is not larger than 64 bits wide to simplify things a little. Is that a safe assumption to make for now?

All the tests passed, but it's still possible I could have missed some parts.

This PR:
Avoids using i/u128 except for converting between 128-bit types.
   Use the smallest type able to represent the maximum value instead for most types (except u/isize), and i/u64 otherwise.

Add sinline annotations to try_from implementations.
   Before doing this the functions did not get inlined.

Avoids using the FromStrRadixHelper trait in the try_from implementations, as the trait wasn't actually needed for anything.

Add some simpler implementations for conversions that don't need as many checks. In release mode the checks will be optimized out when they're not needed anyhow, but this should at least result in very slightly less code non-optimized builds and very slightly less work for LLVM.

2017-07-12 20:54 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @aturon (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-07-13 00:30 UTC, aidanhs commented
Thanks for the PR @oyvindln, we'll check in now and again to make sure @aturon or another reviewer gets to this soon!

2017-07-13 15:56 UTC, nagisa requested changes

2017-07-13 16:15 UTC, oyvindln commented on src/libcore/num/mod.rs
> +trivial_try_from_impl!(usize, u64);
Ah, simply an oversight, you're right it should be together with the other unsigned ones.

2017-07-13 16:16 UTC, oyvindln commented on src/libcore/num/mod.rs
> +// The current implementations assume that usize/isize <= 64 bits wide.
Makes sense.

2017-07-13 16:22 UTC, oyvindln commented on src/libcore/num/mod.rs
> +same_sign_try_from_int_impl!(u64, usize, u64, u32, u16);
I initially decided to leave that for later as it seemed a bit complex to fully test, but I suppose I can try to do it properly.

2017-07-13 16:22 UTC, oyvindln commented
Thanks for the feedback. I will see if I can sort out the issues pointed out.

2017-07-13 20:42 UTC, oyvindln commented
Okay, I think I sorted the requested changes.

I'm a bit unsure about the "compile_error" macro call after checking for an unknown bit width. I didn't enable the compile_error feature, as that would require me to add it to lib.rs, and add a statement to ignore the warning about unused feature. Though, at least it won't compile if the condition is hit, even though it won't give the proper compile_error message.

I didn't manage to compile for the 16-bit target (I got an missing specification error for the msp430_none_elf target which I don't know how to solve.), so that part is untested still.

I also couldn't find any tests for the usize and u128 types for TryFrom. Maybe that's something that ought to be added.

2017-07-13 22:42 UTC, SimonSapin commented
> I didn't manage to compile for the 16-bit target (I got an missing specification error for the msp430_none_elf target which I don't know how to solve.), so that part is untested still.

(Perhaps https://github.com/rust-lang/rust/pull/43099 has not reached stage 0 yet? Before https://github.com/rust-lang-nursery/rust-forge/pull/80 the platform support page linked to https://github.com/pftbest/rust_on_msp/blob/master/msp430.json.)

2017-07-13 22:50 UTC, oyvindln commented
Yup, that seems to be the issue. I'm trying to build with rustc set to the latest nightly (which does have msp430 support) in config.toml now.

2017-07-14 11:22 UTC, nagisa commented
#[cfg_attr(any(target_poin...), feature(compile_error))] should work for the conditional feature.

2017-07-14 16:28 UTC, nagisa commented
@oyvindln do you want to add the conversion tests for usize & u128? If not, I’ll review it as is.

2017-07-14 16:44 UTC, oyvindln commented
@nagisa You can review it as is for now.

2017-07-14 17:30 UTC, nagisa commented on src/libcore/num/mod.rs
> +same_sign_try_from_wider_impl!(isize, u128);
Shouldn’t this be `isize, i128`?

2017-07-14 17:35 UTC, nagisa commented on src/libcore/num/mod.rs
> +        same_sign_try_from_wider_impl!(isize, u64);
A cross-sign conversion again.

I think this code would be easier follow if it was only split into blocks for each target_pointer_width.

Something like:

```
#[cfg(target_pointer_width = "16")] { 
     trivial_try_from_impl!(usize, u16, u32);
     trivial_try_from_impl!(isize, i16, i32);
     same_sign_try_from_wider_impl!(usize, u32, u64);
     same_sign_try_from_wider_impl!(isize, i32, i64);
}

// and so forth.
```

2017-07-14 17:37 UTC, nagisa commented on src/libcore/num/mod.rs
> +        same_sign_try_from_wider_impl!(isize, u64);
Also, I believe the argument order is swapped for `same_sign_try_from_wider_impl` here and in the block above?

2017-07-14 17:57 UTC, oyvindln commented on src/libcore/num/mod.rs
> +same_sign_try_from_wider_impl!(isize, u128);
Indeed

2017-07-14 18:09 UTC, oyvindln commented on src/libcore/num/mod.rs
> +        same_sign_try_from_wider_impl!(isize, u64);
It make make it more readable yeah.

2017-07-15 16:23 UTC, oyvindln commented
I borrowed the idea of using from/into as a separator in the macros from the try_from crate. Hopefully that makes it a bit easier to follow.

Also there is a new PR  #43248 that does something similar to this PR. The approach used there may be a bit cleaner.

2017-07-16 11:54 UTC, nagisa commented
I’m personally fine with either approach (they both look fairly similar to me). @llogiq needs to at least add tests and the `#[inline]` annotations -- something your PR has and their doesn’t.

If you feel that their implementation is better, I would suggest @llogiq to simply take your tests and merge that.

/me shrugs

2017-07-16 12:40 UTC, oyvindln commented
If you think this one is fine, feel free to review/merge.

2017-07-16 17:29 UTC, llogiq commented
@oyvindln are you OK with me cherry-picking your PR?

2017-07-16 17:37 UTC, oyvindln commented
@llogiq Yup, that's fine by me.

2017-07-17 22:44 UTC, aturon commented
r? @nagisa

2017-07-20 18:39 UTC, alexcrichton commented
ping r? @nagisa

2017-07-24 15:30 UTC, carols10cents commented
ping @nagisa @rust-lang/libs, it seems like this is ready for rereview!

2017-07-24 16:55 UTC, nagisa commented
See [this](https://github.com/rust-lang/rust/pull/43248#issuecomment-317484644).

2017-07-24 16:57 UTC, oyvindln commented
I think #43248 will be used instead. (Though I can fix up this to add the modules and avoid storage types if you don't feel like waiting for the other PR to be finished.)

2017-07-24 20:47 UTC, oyvindln commented
Looks like #43248 is ready now, so I'm closing this in favour of that.

2017-07-24 20:47 UTC, closed without merging