Document default values for primitive types
rust-lang/rust pull request #43252
Opened 2017-07-15 13:44 UTC by vbrandl

All primitive types implement the `Default` trait but the documentation just says `Returns the "default value" for a type.` and doesn't give a hint about the actual default value. I think it would be good to document the default values in a proper way.
I changed the `default_impl` macro to accept a doc string as a third parameter and use this string to overwrite the documentation of `default()` for each primitive type.
The generated documentation now looks like this:
![Documentation of default() on the bool primitive](https://i.imgur.com/nK6TApo.png)

2017-07-15 14:18 UTC, retep998 commented
Bikeshedding alternative phrasing:
`Returns the default value of 0`

2017-07-16 09:31 UTC, vbrandl commented
Shouldn't @rust-highfive assign a reviewer to this PR? Or do I have to do it manually or just wait?

2017-07-16 10:20 UTC, GuillaumeGomez requested changes
A light rewording would be better I think.

2017-07-16 10:20 UTC, GuillaumeGomez commented on src/libcore/default.rs
> +default_impl! { char, '\x00', "Returns the default value of `\\x00`" }
Shouldn't it be "Returns the default value of `char` which is `\\x00`?"

2017-07-16 10:20 UTC, GuillaumeGomez commented on src/libcore/default.rs
> +default_impl! { bool, false, "Returns the default value of `false`" }
Shouldn't it be "Returns the default value of`bool` which is `false`?"

2017-07-16 10:21 UTC, GuillaumeGomez commented
Hum, actually I think it's good as is. The wording is lighter. I'll go for this one then. Thanks!

@bors: r+ rollup

2017-07-16 10:21 UTC, GuillaumeGomez approved these changes

2017-07-16 12:43 UTC, merged