field does not exist error: note fields if Levenshtein suggestion fails
rust-lang/rust pull request #43442
Opened 2017-07-23 21:47 UTC by zackmdavis

When trying to access or initialize a nonexistent field, if we can't infer what
field was meant (by virtue of the purported field in the source being a small
Levenshtein distance away from an actual field, suggestive of a typo), issue a
note listing all the available fields. To reduce terminal clutter, we don't
issue the note when we have a `find_best_match_for_name` Levenshtein
suggestion: the suggestion is probably right.

The third argument of the call to `find_best_match_for_name` is changed to
`None`, accepting the default maximum Levenshtein distance of one-third of the
identifier supplied for correction. The previous value of `Some(name.len())`
was overzealous, inappropriately very Levenshtein-distant suggestions when the
attempted field access could not plausibly be a mere typo. For example, if a
struct has fields `mule` and `phone`, but I type `.donkey`, I'd rather the
error have a note listing that the available fields are, in fact, `mule` and
`phone` (which is the behavior induced by this patch) rather than the error
asking "did you mean `phone`?" (which is the behavior on master). The "only
find fits with at least one matching letter" comment was accurate when it was
first introduced in 09d992471 (January 2015), but is a vicious lie in its
present context before a call to `find_best_match_for_name` and must be
destroyed (replacing every letter is a Levenshtein distance of name.len()).

The present author claims that this suffices to resolve #42599.

2017-07-23 21:47 UTC, rust-highfive commented
r? @eddyb

(rust_highfive has picked a reviewer for you, use r? to override)

2017-07-24 03:53 UTC, eddyb commented
Is there any way to get @rust-highfive to try randomly assigning again?

r? @nikomatsakis

2017-07-25 19:50 UTC, nikomatsakis requested changes
This looks great! I hate silly suggestions. But there are some stylistic nits.

2017-07-25 19:50 UTC, nikomatsakis commented on src/librustc_typeck/check/mod.rs
> +                    err.note(&format!("available fields are: {}",
same here, of course

2017-07-25 19:50 UTC, nikomatsakis commented on src/librustc_typeck/check/mod.rs
> +                                                  available_field_names.join(", ")));
hmm; ideally we would put backticks around these field names. But, more importantly, we generally have a rule that we only list out things exhaustively up to a certain limit (typically 5), and then after that we will say "...and others" or something. See e.g. this code [in method suggestions](https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/method/suggest.rs#L88).

2017-08-01 03:15 UTC, zackmdavis commented
2dbfa39 adds the backticks, "... and _n_ others" truncation, and declines to issue the note if we can't actually see any fields

2017-08-04 06:55 UTC, nikomatsakis approved these changes
Looks great, thanks!

2017-08-04 06:55 UTC, nikomatsakis commented
@bors r+

2017-08-04 12:44 UTC, merged