Fix the spans of catch blocks to include the `do`
rust-lang/rust pull request #43463
Opened 2017-07-24 23:40 UTC by nrc

2017-07-24 23:40 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2017-07-25 00:06 UTC, petrochenkov commented
@bors r+ rollup

2017-07-25 03:29 UTC, topecongiro commented on src/libsyntax/parse/parser.rs
> +                    let lo = self.span;
Shouldn't this come after `self.eat_keyword(keywords::Do)` instead of before?

2017-07-25 04:58 UTC, nrc commented on src/libsyntax/parse/parser.rs
> +                    let lo = self.span;
I changed from using `prev_span` to `span`, so we can move it before the eat(Do) expression

2017-07-25 06:11 UTC, topecongiro commented on src/libsyntax/parse/parser.rs
> +                    let lo = self.span;
Sorry, I missed the change. Thank you for your reply, and sorry for the noise.

2017-07-25 17:20 UTC, nikomatsakis requested changes
r=me with a test; the most straightforward thing would be to add a `src/test/ui` test that has incorrect highlighting with the current span.

2017-07-26 23:40 UTC, merged