a couple more error explanations for posterity
rust-lang/rust pull request #43519
Opened 2017-07-28 05:40 UTC by zackmdavis

E0436, E0595, and moving E0569 to where it belongs in the file rather than being bizarrely out of numerical order

r? @GuillaumeGomez

2017-07-28 07:28 UTC, GuillaumeGomez requested changes

2017-07-28 07:28 UTC, GuillaumeGomez commented on src/librustc_borrowck/diagnostics.rs
> +Closures cannot mutate immutable captured variables. Erroneous code example:
Please put "Erroneous code example:" on its own line.

2017-07-28 07:28 UTC, GuillaumeGomez commented on src/librustc_typeck/diagnostics.rs
> +
Please add "Erroneous code example:".

2017-07-28 07:28 UTC, GuillaumeGomez commented on src/librustc_typeck/diagnostics.rs
> +that impl must be declared as an `unsafe impl. For example:
Please remove "For example:" and add "Erroneous code example:".

2017-07-28 07:42 UTC, kennytm commented on src/librustc_typeck/diagnostics.rs
> +            annual_special: true, ..c // error: functional record update syntax requires a struct
This line is too long.

```
[00:11:18] error: description for error code E0436 contains a line longer than 80 characters.
[00:11:18] if you're inserting a long URL use the footnote style to bypass this check.
[00:11:18]     --> /checkout/src/librustc_typeck/diagnostics.rs:13:1
[00:11:18]      |
[00:11:18] 13   | / register_long_diagnostics! {
[00:11:18] 14   | |
[00:11:18] 15   | | E0023: r##"
[00:11:18] 16   | | A pattern used to match against an enum variant must provide a sub-pattern for
[00:11:18] ...    |
[00:11:18] 4637 | |
[00:11:18] 4638 | | }
[00:11:18]      | |_^
[00:11:18]      |
[00:11:18]      = note: this error originates in a macro outside of the current crate
```

2017-07-30 19:21 UTC, zackmdavis commented
(force-pushed)

2017-07-30 20:23 UTC, GuillaumeGomez approved these changes

2017-07-30 20:24 UTC, GuillaumeGomez commented
Ok, sounds good to me. Thanks!

@bors: r+ rollup

2017-07-31 03:16 UTC, merged