Use explicit wrapping_add …
rust-lang/rust pull request #43588
Opened 2017-08-01 14:28 UTC by dns2utf8

… to prevent potential unexpected behavior on debug builds.

2017-08-01 14:28 UTC, rust-highfive commented
r? @sfackler

(rust_highfive has picked a reviewer for you, use r? to override)

2017-08-01 14:36 UTC, TimNN requested changes

2017-08-01 14:36 UTC, TimNN commented on src/libstd/sync/barrier.rs
> +        lock.count.wrapping_add(1);
You need `lock.count = lock.count.wrapping_add(1)` (`wrapping_add` returns the new value instead of modifying in-place).

2017-08-01 15:31 UTC, sfackler commented on src/libstd/sync/barrier.rs
> +        lock.count.wrapping_add(1);
How can this ever overflow? Wouldn't that require more than `usize::MAX_VALUE` threads?

2017-08-08 10:27 UTC, arielb1 commented
Hi @dns2utf8. This PR needs fixing - are you still working on it? Just a friendly ping to keep this on your radar.

Also, could you provide an example in which an overflow can happen, to make sure it is handled correctly?

2017-08-08 20:58 UTC, dns2utf8 commented on src/libstd/sync/barrier.rs
> +        lock.count.wrapping_add(1);
You are both right. This can not overflow and the syntax was wrong. Thank you

2017-08-08 21:00 UTC, dns2utf8 commented
Thank you for the ping.

The example I would like to prevent is when reusing a barrier the generation could trigger an overflow panic at some point.

2017-08-09 04:49 UTC, sfackler commented
@bors r+

2017-08-09 09:44 UTC, kennytm commented
@bors retry #43535

2017-08-09 13:33 UTC, merged

2017-08-09 16:35 UTC, dns2utf8 commented
Cool! Thank you 😄