E05XX odyssey
rust-lang/rust pull request #43726
Opened 2017-08-07 22:55 UTC by zackmdavis

chipping away at the surface exposed by #43709

r? @GuillaumeGomez

2017-08-08 07:56 UTC, GuillaumeGomez requested changes
A few things to change but globally it's good.

2017-08-08 07:56 UTC, GuillaumeGomez commented on src/librustc_passes/diagnostics.rs
> +The `break` statement can take an argument (which will be the value of the loop
A long error explanation is supposed to start by a short summary of the error. The error explanation comes just after the erroneous code example and just before the fix.

2017-08-08 07:56 UTC, GuillaumeGomez commented on src/libsyntax/diagnostic_list.rs
> +You can use a `repr` attribute to tell the compiler how you want a struct or
The explanation is supposed to be after the erroneous code example.

2017-08-08 07:56 UTC, GuillaumeGomez commented on src/libsyntax/diagnostic_list.rs
> +```ignore (depends on release channel)
Just `ignore` please.

2017-08-08 07:56 UTC, GuillaumeGomez commented on src/libsyntax/diagnostic_list.rs
> +A feature attribute for a removed feature was used.
Seems a bit complicated when formulated this way.

2017-08-08 07:56 UTC, GuillaumeGomez commented on src/libsyntax/feature_gate.rs
> +                          "#![feature] may not be used on the {} release channel",
Why this change?

2017-08-08 08:10 UTC, kennytm commented on src/libsyntax/diagnostic_list.rs
> +```ignore (depends on release channel)
@GuillaumeGomez  Just writing `ignore` without explanation will cause `tidy` failure. `--explain` will strip them out though.

2017-08-09 07:48 UTC, GuillaumeGomez commented on src/libsyntax/diagnostic_list.rs
> +```ignore (depends on release channel)
Oh that's strange.

2017-08-09 08:35 UTC, zackmdavis commented
(updated)

2017-08-09 08:36 UTC, zackmdavis commented on src/libsyntax/feature_gate.rs
> +                          "#![feature] may not be used on the {} release channel",
See [the commit message](https://github.com/rust-lang/rust/commit/6fa140b8).

2017-08-09 10:01 UTC, GuillaumeGomez approved these changes

2017-08-09 10:01 UTC, GuillaumeGomez commented
Thanks!

@bors: r+

2017-08-09 16:14 UTC, merged