Implement CompilerDesugaringKind enum
rust-lang/rust pull request #43832
Opened 2017-08-13 00:53 UTC by huntiep

This is the first step outlined in #35946. I think that the variants of `CompilerDesugaringKind` should be changed, I didn't know what the official names for `...` and `<-` are.

I'm not to sure how tests for the compiler work, but I would imagine that tests should be added such that
`Symbol::intern(s) == CompilerDesugaringKind::from(s).as_symbol()` for valid `s`.

2017-08-13 00:53 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @nikomatsakis (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-08-14 05:51 UTC, oli-obk commented on src/librustc/hir/lowering.rs
>      fn allow_internal_unstable(&self, reason: &'static str, mut span: Span) -> Span {
Wouldn't it make sense to directly pass the enum as an argument here?

2017-08-14 12:23 UTC, carols10cents commented
Hi! Thanks for the pull request! We'll be checking in periodically to make sure @nikomatsakis or someone else reviews this.

2017-08-16 21:20 UTC, nikomatsakis requested changes
This is in the right direction, but not quite what I had in mind. Please do let me know if my suggestion doesn't make sense or needs clarification!

2017-08-16 21:20 UTC, nikomatsakis commented on src/libsyntax_pos/hygiene.rs
> +impl<'a> From<&'a str> for CompilerDesugaringKind {
Somewhat along the lines of what @oli-obk was suggesting, I didn't expect to have `CompiledDesugaringKind::from`, but rather replace all places in the compiler where we use constant strings with direct references to the enum variants, and instead invoke `as_symbol()` anywhere that we need to print things out.

2017-08-16 21:21 UTC, nikomatsakis commented
Also, I apologize for delay, I was on vacation!

2017-08-16 23:48 UTC, huntiep commented
It's not a problem, I was also on vacation until recently.

2017-08-17 19:05 UTC, nikomatsakis approved these changes

2017-08-17 19:05 UTC, nikomatsakis commented
@bors r+ -- looks good!

2017-08-17 22:05 UTC, kennytm commented
@bors retry #43283 (`arm-android`)

This seems to become more frequent recently 🤔

2017-08-18 03:15 UTC, merged