add comparison operators to must-use lint (under `fn_must_use` feature)
rust-lang/rust pull request #44103
Opened 2017-08-26 19:11 UTC by zackmdavis

Although RFC 1940 is about annotating functions with `#[must_use]`, a
key part of the motivation was linting unused equality operators.

(See
https://github.com/rust-lang/rfcs/pull/1812#issuecomment-265695898—it
seems to have not been clear to discussants at the time that marking the
comparison methods as `must_use` would not give us the lints on
comparison operators, at least in (what the present author understood
as) the most straightforward implementation, as landed in #43728
(3645b062).)

To rectify the situation, we here lint unused comparison operators as
part of the unused-must-use lint (feature gated by the `fn_must_use`
feature flag, which now arguably becomes a slight (tolerable in the
opinion of the present author) misnomer).

This is in the matter of #43302.

cc @crumblingstatue

2017-08-26 19:12 UTC, rust-highfive commented
r? @pnkfelix

(rust_highfive has picked a reviewer for you, use r? to override)

2017-08-30 06:39 UTC, oli-obk requested changes

2017-08-30 06:39 UTC, oli-obk commented on src/librustc_lint/unused.rs
> +                    hir::BiEq | hir::BiLt | hir::BiLe | hir::BiNe | hir::BiGe | hir::BiGt => {
I think it would be less surprising, if instead of whitelisting operators, we'd check whether the corresponding operator method has the attribute.

2017-08-30 06:39 UTC, oli-obk commented on src/test/ui/lint/fn_must_use.stderr
> +49 |     2 == 3;
The result of the comparison is unused. The span should be including the rhs and lhs of the operation

2017-09-01 10:14 UTC, pnkfelix commented
r=pnkfelix once @oli-obk 's points are addressed.

2017-09-05 18:14 UTC, arielb1 commented
Hi @zackmdavis. Looks like you just need to make a few changes to get this over to ship. Just a friendly ping to keep this on your radar.

2017-09-06 05:04 UTC, zackmdavis commented
@arielb1 Yes, thanks: I spent a couple hours last week trying to figure out how to look up the method definition given the binary-operator HIR node, and couldn't figure out how to make it work; I want to take another look sometime this week before I stoop to the indignity of begging for mentoring.

2017-09-06 07:34 UTC, oli-obk commented
You can get the `DefId` and `Substs` of the correct method via `cx.tables().type_dependent_defs()[expr.hir_id].def_id()` and `cx.tables().node_substs(expr.hir_id)`.

To obtain the attributes, you can check if `cx.tcx.item_attrs(def_id)` contains everything you need.

2017-09-13 22:04 UTC, aidanhs commented
Hi @zackmdavis, just wanted to check in to make sure this PR is still on your radar! Please do reach out for a hand via the methods @oli-obk mentioned if it'd help at all.

2017-09-14 04:31 UTC, zackmdavis commented
Regret the delay; I'll set aside some time Friday. ([I swear I tried `type_dependent_defs`](https://github.com/zackmdavis/rust/commit/f14e7916e539#diff-d85eb66bc4756598e30d93a5d07d3d7fR176) the other week before oli recommended it, and it didn't work because the table was empty; I fear that the emotional scars of that profoundly frustrating debugging session may have contributed to my tardiness.)

2017-09-16 02:01 UTC, zackmdavis commented
I see—[if both operands are scalars, we don't fill `type_dependent_defs`](https://github.com/rust-lang/rust/blob/fd4bef54ab/src/librustc_typeck/check/writeback.rs#L126-L128). (And if the operands are custom structs with a `PartialEq` implementation, looking at `type_dependenent_defs` and finding the `must_use` attribute on `PartialEq::eq` _does_ work.) Given this, it's not clear to me that we _can_ do better than whitelisting the HIR binary operators, as the existing revision of this PR does. @oli-obk thoughts?

(Existing PR revision will collide with #44620, which I expect to be rolled up.)

2017-09-16 02:03 UTC, zackmdavis commented
> I'm horrified we present the image that any form of mentoring requires begging or is indignified

We don't; please construe that somewhat tongue-in-cheek remark as reflecting my _personal_ (and, one could argue, neurotic and maladaptive) pride in my ability to RTFM.

2017-09-16 09:24 UTC, oli-obk commented
Hmm... I can't figure out why we remove scalars from the map... not even sure who to ping. That code is older than two years

2017-09-16 16:20 UTC, zackmdavis commented
> I can't figure out why we remove scalars from the map... not even sure who to ping.

Looks like d649292e. The [pull request](https://github.com/rust-lang/rust/pull/23673) (by @nikomatsakis) says:

> There is one semi-hacky bit in that during writeback, for builtin operators, if the types resolve to scalars (i32 etc) then we clear the method override. This is because we know what the semantics are and it is more efficient to generate the code directly. It also ensures that we can use these overloaded operators in constants and so forth.

2017-09-17 09:18 UTC, arielb1 commented
Ah yeah that. I myself don't see a problem with keeping an hard list of binary operators.

2017-09-17 09:20 UTC, arielb1 commented
If you wanted to avoid the hardcoding, you could move this part of `lookup_op_method` to rustc:

https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/op.rs#L362-L421

and then call it on the binary operator to get the defid of the op method.

2017-09-22 23:04 UTC, zackmdavis commented
(rebased) fixed comparison expression span, conflict with master

2017-09-22 23:15 UTC, zackmdavis commented
> I myself don't see a problem with keeping an hard list of binary operators.

Anyone else have an opinion? My disposition is to merge the most recent revision that I just pushed that leaves the hardcoding (with a comment noting the judgement call).

@arielb1's idea of pulling code out of `rustc_typecheck` (and putting it onto, say, `TyCtxt`) would work, but it seems like an unnatural refactoring for no actual gain in functionality. (Looking up the `must_use` attribute on the trait method _would_ be more graceful æsthetically, but it doesn't come for free, and if we already _know_ that we want to lint comparisons, the dynamicity isn't necessary.)

2017-09-23 10:18 UTC, oli-obk commented
I'm fine with hardcoding, as long as there are sufficient comments explaining the haedcoding. And as long as it works for nonprimitives with the trait attribute check.

2017-09-24 09:20 UTC, arielb1 commented
Nice!

@bors r+

2017-09-24 15:41 UTC, merged