Allow replacing HashMap entries
rust-lang/rust pull request #44278
Opened 2017-09-02 21:57 UTC by Binero

This is an obvious API hole. At the moment the only way to retrieve an entry from a `HashMap` is to get an entry to it, remove it, and then insert a new entry. This PR allows entries to be replaced.

2017-09-02 21:57 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @BurntSushi (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-09-03 09:38 UTC, kennytm commented on src/libstd/collections/hash/map.rs
> +    pub fn replace(mut self, value: V) -> (K, V) {
This new API should be `#[unstable]`.

2017-09-03 09:40 UTC, kennytm commented
Why not apply this to `BTreeMap` too?

2017-09-03 13:36 UTC, Binero commented
It is non-trivial to implement it for `BTreeMap`. `BTreeMap`'s entry does not have ownership of the key. Giving it ownership would break `BTreeMap::replace`.

Not sure how to implement recovery of a `BTreeMap`'s entry without breaking the existing APIs. Both of these map APIs are littered with methods that take by ownership, use a borrow and then throw away the value they took ownership of.

2017-09-03 14:06 UTC, Binero commented
I am quite inexperienced with the std, and I am unsure how such an unstable attribute would look. 

Adding `#[unstable(feature = "rust1", issue = "44286")]` gives a compile error during tests: 

> error: use of unstable library feature 'rust1' (see issue #44286)

2017-09-03 14:25 UTC, kennytm commented
@Binero You would first need to pick a name of the feature, say `entry_replace`. When nightly user tries to use your API, they will need to add `#![feature(entry_replace)]`.

The syntax of `#[unstable]` attribute is:

```rust
#[unstable(feature = "entry_replace", reason = "recently added", issue = "44286")]
```

The doctest examples will need to be modified to include `#![feature(entry_replace)]`:

```rust
    /// # Examples
    ///
    /// ```
    /// #![feature(entry_replace)]
    /// # fn main() {
    /// use std::collections::HashMap;
    /// use std::collections::hash_map::Entry; 
    /// // ...
    /// # }
    /// ```
```

2017-09-07 16:40 UTC, Binero commented
Not sure why this is waiting on author?

2017-09-11 15:10 UTC, carols10cents commented
@Binero I'm not sure either. Maybe because of the test failure? It looks like an osx worker had a network failure though; I've restarted that job.

I think this is ready for review again @BurntSushi !

2017-09-11 21:31 UTC, BurntSushi reviewed
I left a few nits, and mechanically, this looks fine to me.

Is this something we definitely want though? Do you have a use case in mind where this method is useful?

2017-09-11 21:31 UTC, BurntSushi commented on src/libstd/collections/hash/map.rs
> +    /// # #![feature(map_entry_replace)]
I think we include the feature toggle in the docs so that end users know that it is necessary. So I'd remove the `# ` prefix here.

2017-09-11 21:31 UTC, BurntSushi commented on src/libstd/collections/hash/map.rs
> +    ///
Remove blank line?

2017-09-11 21:31 UTC, BurntSushi commented on src/libstd/collections/hash/map.rs
> +    /// map.insert(String::from("poneyland"), 15);
I think we use `"poneyland".to_string()`?

2017-09-11 21:31 UTC, BurntSushi commented on src/libstd/collections/hash/map.rs
> +    /// if let Entry::Occupied(entry) = map.entry(String::from("poneyland")) {
Same as above, use `to_string`.

2017-09-12 13:38 UTC, Binero commented
@BurntSushi The Entry-API serves as a temporary result, to prevent having to lookup entries in the HashMap multiple times. 

Right now, to get a key out of a `HashMap`, you have to do the following:

1. Create an entry to the key-value pair you want to remove. (lookup)
2. Remove it. (shifts elements following the removed entry to the left)
3. Insert a new entry. (lookup + shifts those same elements back to the right)

With this addition, the process is simplified to the following:


1. Create an entry to the key-value pair you want to remove. (lookup)
2. Replace it. (O(1))

2017-09-20 17:19 UTC, arthurprs requested changes

2017-09-20 17:19 UTC, arthurprs commented on src/libstd/collections/hash/map.rs
> +        let old_key = mem::replace(old_key, self.key.unwrap());
One can take the key out of the entry using `take_key` before `replace`, so this `key.unwrap()` can fail. It needs a custom message at least.

2017-09-20 17:24 UTC, arthurprs commented
I think this (*sort of*) already possible using `occupied.take_key()` and `replace(occupied.get_mut(), new_value)`.

The difference is that `take_key` will return the key passed to `entry()` instead of the one inside the hashmap.

2017-09-23 12:04 UTC, Binero commented
@arthurprs `take_key` is only called internally, and the entry is always consumed after usage. Furthermore, `take_key` returns the key the entry was created with, which doesn't address the issue at all. If one wanted to have the new key, one wouldn't create an `Entry`. The point of the `replace` function is to recover the old key.

2017-09-23 15:48 UTC, arthurprs commented
Indeed, thanks for clarifying.

2017-09-23 15:49 UTC, arthurprs reviewed
Looks good.

2017-09-25 21:20 UTC, BurntSushi commented
@Binero That's good enough for me! Thanks for clarifying. Should this get an entry in the unstable book before merging?

2017-09-28 14:23 UTC, alexcrichton commented
@BurntSushi oh we typically don't have an entry per unstable library API as the docs here typically suffice for that, in which case I'll..

@bors: r=BurntSushi

Thanks for the PR @Binero!

2017-09-28 22:53 UTC, merged