Minor documentation improvements for StmtKind
rust-lang/rust pull request #44296
Opened 2017-09-03 19:28 UTC by zmanian

Documentation for Semi and Marco StmtKinds.

Wasn't obvious to me what these were when writing a lint recently.

2017-09-03 19:28 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @pnkfelix (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-09-05 16:00 UTC, steveklabnik requested changes
after fixing the whitespace issue, r=me. Thank you!

2017-09-05 16:00 UTC, steveklabnik commented on src/libsyntax/ast.rs
> +    /// Macro.
this has a trailing space, ✂️

2017-09-06 21:51 UTC, petrochenkov commented
@bors=steveklabnik rollup
Thanks!

2017-09-07 04:07 UTC, merged