Add Duration::from_micros
rust-lang/rust pull request #44436
Opened 2017-09-08 21:04 UTC by MicroJoe

This fixes #44400 that explains why it could be useful for embedded designs timing.

2017-09-08 21:04 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @sfackler (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-09-08 21:20 UTC, mattico commented
This'll need a feature gate (right?).

You'll need to:

- Create a tracking issue (or just use #44400)
- Add a feature to `src/libsyntax/feature_gate.rs`
- Add an entry to the unstable book `src/doc/unstable-book`
- Add an `#[unstable(feature = "", issue = "")]` annotation to the function.

2017-09-08 21:28 UTC, sfackler commented
`src/libsyntax/feature_gate.rs` is only used for language features, not library features. I don't think the unstable book needs to be modified anymore either.

2017-09-09 09:11 UTC, SergioBenitez commented on src/libstd/time/duration.rs
> +        Duration {
This should be inlined for consistency.

2017-09-09 16:03 UTC, MicroJoe commented
I have commited some changed according to your feedbacks, please let me know if it needs anything else.

2017-09-09 17:13 UTC, kennytm requested changes

2017-09-09 17:13 UTC, kennytm commented on src/libstd/time/duration.rs
> +
You missed a `}` here.

2017-09-09 22:27 UTC, MicroJoe commented
Thanks @kennytm, fixed!

2017-09-10 06:25 UTC, kennytm commented on src/libstd/time/duration.rs
> +        let nanos = ((micros % MICROS_PER_SEC) as u32) * NANOS_PER_MICRO;
Typo. Also, the `issue` must be a number.

```rust
[00:02:49] error[E0425]: cannot find value `NANOS_PER_MICRO` in this scope
[00:02:49]    --> /checkout/src/libstd/time/duration.rs:137:58
[00:02:49]     |
[00:02:49] 137 |         let nanos = ((micros % MICROS_PER_SEC) as u32) * NANOS_PER_MICRO;
[00:02:49]     |                                                          ^^^^^^^^^^^^^^^ did you mean `NANOS_PER_MICROS`?
[00:02:49] 
[00:02:49] error[E0545]: incorrect 'issue'
[00:02:49]    --> /checkout/src/libstd/time/duration.rs:133:5
[00:02:49]     |
[00:02:49] 133 |     #[unstable(feature = "", issue = "")]
[00:02:49]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[00:02:49] 
[00:02:51] error: aborting due to 2 previous errors
[00:02:51] 
[00:02:51] error: Could not compile `std`.
```

2017-09-11 21:17 UTC, sfackler commented on src/libstd/time/duration.rs
> +    #[unstable(feature = "", issue = "44400")]
The feature can be called whatever you want `duration_from_micros` is probably fine.

2017-09-11 21:17 UTC, sfackler commented on src/libstd/time/duration.rs
> +    /// ```
This test will need to enable that feature to build properly.

2017-09-11 21:18 UTC, sfackler commented
Seems like a straightforward/reasonable addition!

@rfcbot fcp merge

2017-09-13 11:21 UTC, MicroJoe commented
Thanks for the review @sfackler, I have added a feature name as you suggested and used it in the test.

2017-09-23 21:59 UTC, alexcrichton commented
@bors: r+

2017-09-24 01:51 UTC, merged