use param_env on the trait_cache key
rust-lang/rust pull request #44741
Opened 2017-09-21 14:48 UTC by qmx

We bailed from making trans_fulfill_obligation return `Option` or `Result`, just made it less prone to crashing outside trans

r? @nikomatsakis

2017-09-21 15:02 UTC, arielb1 commented
@bors r+

2017-09-21 15:17 UTC, nikomatsakis requested changes
Just a nit.

2017-09-21 15:17 UTC, nikomatsakis commented on src/librustc/traits/trans/mod.rs
>      /// obligations *could be* resolved if we wanted to.
Nit: Can we extend this comment to say "/// Assumes that this is run after the entire crate has been successfully type-checked."

2017-09-21 16:39 UTC, alexcrichton commented
@bors: r=nikomatsakis

2017-09-23 13:31 UTC, kennytm commented
Needs to submit a PR to miri, and set miri's [toolstate](https://github.com/rust-lang/rust/blob/master/src/tools/toolstate.toml) to "Broken". (cc @oli-obk @RalfJung @eddyb)

```
[00:47:34] error[E0061]: this function takes 3 parameters but 2 parameters were supplied
[00:47:34]     --> /checkout/src/tools/miri/src/librustc_mir/interpret/eval_context.rs:2419:45
[00:47:34]      |
[00:47:34] 2419 |     let vtbl = tcx.trans_fulfill_obligation(DUMMY_SP, ty::Binder(trait_ref));
[00:47:34]      |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 3 parameters
[00:47:34] 
[00:47:35] error: aborting due to previous error
[00:47:35] 
[00:47:35] error: Could not compile `rustc_miri`.
```

2017-09-25 13:52 UTC, nikomatsakis commented
@bors r+

2017-09-25 19:42 UTC, nikomatsakis approved these changes

2017-09-26 22:26 UTC, merged