macros: fix bug in collecting trait and impl items with derives.
rust-lang/rust pull request #44757
Opened 2017-09-21 19:59 UTC by jseyfried

Fixes #43023.
r? @nrc

2017-09-21 20:06 UTC, nikomatsakis commented
Nominating for backport because fixes a stable-to-beta regression (https://github.com/rust-lang/rust/issues/43023).

2017-09-21 20:14 UTC, arielb1 commented
```
[00:03:56] tidy error: /checkout/src/libsyntax/ext/expand.rs:755: line longer than 100 chars
```

@bors r-

2017-09-21 22:07 UTC, nrc commented
@bors: r+

2017-09-23 18:02 UTC, kennytm requested changes

2017-09-23 18:02 UTC, kennytm commented on src/test/compile-fail/issue-43023.rs
> +    #[derive(Debug)] //~ ERROR `derive` can be only be applied to items
Please update the error messages.

```
[00:55:08] ---- [compile-fail] compile-fail/issue-43023.rs stdout ----
[00:55:08] 	
[00:55:08] error: /checkout/src/test/compile-fail/issue-43023.rs:14: unexpected "error": '14:5: 14:21: `derive` may only be applied to structs, enums and unions'
[00:55:08] 
[00:55:08] error: /checkout/src/test/compile-fail/issue-43023.rs:21: unexpected "error": '21:5: 21:21: `derive` may only be applied to structs, enums and unions'
[00:55:08] 
[00:55:08] error: /checkout/src/test/compile-fail/issue-43023.rs:26: unexpected "error": '26:5: 26:21: `derive` may only be applied to structs, enums and unions'
[00:55:08] 
[00:55:08] error: 3 unexpected errors found, 0 expected errors not found
```

2017-09-26 01:22 UTC, jseyfried commented
@bors r=nrc

2017-09-26 22:24 UTC, alexcrichton commented
@bors: p=1

fixing a regression and beta-accepted

2017-09-27 01:23 UTC, merged

2017-09-28 18:56 UTC, nikomatsakis commented
Backporting to beta.