#44493 add structure for inferred_outlives_of
rust-lang/rust pull request #44857
Opened 2017-09-26 04:50 UTC by toidiu

#44493 

- add placeholder for the final implementation of inferred_outlives_of
- add some placeholder tests

2017-09-26 04:51 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @pnkfelix (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-09-29 22:22 UTC, toidiu commented
@nikomatsakis I am getting a cryptic error that I dont know how to address. 
error: failed to read `/checkout/src/tools/rls/test_data/unicødë/Cargo.toml`

Could provide some assistance please:

2017-10-03 14:18 UTC, nikomatsakis commented
r? @nikomatsakis

2017-10-03 14:23 UTC, nikomatsakis requested changes
See if those changes work?

2017-10-03 14:23 UTC, nikomatsakis commented on src/librustc_typeck/lib.rs
> +    tcx.sess.track_errors(|| {
This can be moved up, I think, to occur right after "type collecting"

2017-10-03 14:23 UTC, nikomatsakis commented on src/test/compile-fail/outlives-associated-types.rs
> +    field: &'a T //~ ERROR generic reference may outlive the data it points to
I think the problem is that we are running the test too late in the compiler, and hence we get other unrelated errors being reported.

2017-10-08 20:15 UTC, toidiu commented
@nikomatsakis I [fixed](https://github.com/rust-lang/rust/pull/44857/commits/1a4cb46e0cf7dd003f0ed951813c343f10ce086b) my error and am getting a failure from other files. Please advise.

```
failures:
[compile-fail] compile-fail/dep-graph-assoc-type-trans.rs
[compile-fail] compile-fail/dep-graph-caller-callee.rs
[compile-fail] compile-fail/dep-graph-struct-signature.rs
[compile-fail] compile-fail/dep-graph-trait-impl-two-traits-same-method.rs
[compile-fail] compile-fail/dep-graph-trait-impl-two-traits.rs
[compile-fail] compile-fail/dep-graph-trait-impl.rs
[compile-fail] compile-fail/dep-graph-type-alias.rs
[compile-fail] compile-fail/dep-graph-variance-alias.rs
[compile-fail] compile-fail/dep_graph_crosscontaminate_tables.rs
[compile-fail] compile-fail/incr_comp_with_macro_export.rs
```

2017-10-09 14:05 UTC, nikomatsakis approved these changes

2017-10-09 15:00 UTC, nikomatsakis requested changes

2017-10-09 15:00 UTC, nikomatsakis commented on src/librustc/ty/maps/mod.rs
> +    [] fn inferred_outlives_of: PredicatesOfItem(DefId) -> Vec<ty::Predicate<'tcx>>,
I think your problem is that you are re-using this `PredicatesOfItem` dep-node. We need to make an `InferredOutlivesOf` dep-node. This process is not well documented -- it has been actively changing in the last few days! But roughly speaking you need to [add a `DepNode` variant here](https://github.com/rust-lang/rust/blob/d7acd29ad5a49f6123185502d8ca92822c477f55/src/librustc/dep_graph/dep_node.rs#L478) and then add [a line to this big macro here](https://github.com/rust-lang/rust/blob/d7acd29ad5a49f6123185502d8ca92822c477f55/src/librustc/ty/maps/plumbing.rs#L742), essentially copying the model of `PredicatesOfItem`.

2017-10-11 13:34 UTC, nikomatsakis commented
@toidiu seems like it doesn't [quite build yet](https://travis-ci.org/rust-lang/rust/builds/286332085#L1762), I guess you need to write `inferred_outlives_of` not `outlives_of`:

```rust
DepKind::InferredOutlivesOf => { force!(inferred_outlives_of, def_id!()); }
```

2017-10-11 17:44 UTC, toidiu commented
That seemed to have fixed it. I was wondering how you figured out that bug with the Dep Nodes. I couldnt find anything in the previous error logs.

2017-10-16 18:15 UTC, nikomatsakis commented
@toidiu argh, can you rebase?

2017-10-16 18:53 UTC, nikomatsakis commented
@bors r+

2017-10-17 00:34 UTC, merged