code suggestions for non-shorthand field pattern, no-mangle lints
rust-lang/rust pull request #45232
Opened 2017-10-12 07:50 UTC by zackmdavis

continuing in the spirit of #44942

![moar_lint_suggestions](https://user-images.githubusercontent.com/1076988/31485011-3b20cc80-aee7-11e7-993d-81267ab77732.png)

r? @estebank

2017-10-12 08:24 UTC, oli-obk requested changes

2017-10-12 08:24 UTC, oli-obk commented on src/librustc_lint/builtin.rs
> +                       err.span_suggestion(insertion_span, "try making public", "pub ".to_owned());
nit: "try making it public"

2017-10-12 08:24 UTC, oli-obk commented on src/librustc_lint/builtin.rs
>                          let msg = format!("function {} is marked #[no_mangle], but not exported",
drive by fix: can you remove the function names? Most diagnostics pointing to a definition don't mention the name again.

2017-10-12 08:24 UTC, oli-obk commented on src/librustc_lint/builtin.rs
> +                       let msg = format!("static {} is marked #[no_mangle], but not exported",
same here (wrt name repetition in diagnostics)

2017-10-12 08:24 UTC, oli-obk commented on src/librustc_lint/builtin.rs
> +                       let insertion_span = it.span.with_hi(BytePos(it.span.lo().0));
this should be `it.span.with_hi(it.span.lo())`

2017-10-16 01:28 UTC, zackmdavis commented
(force-push addresses @oli-obk's comments)

2017-10-16 04:17 UTC, zackmdavis commented
(and the ensuing compile-fail failures reported by our mutual friend Travis)

2017-10-16 08:12 UTC, estebank commented
R=me once the merge conflict is fixed

2017-10-16 19:16 UTC, zackmdavis commented
(and @bors's treachery)

2017-10-17 09:50 UTC, estebank commented
@bors r+

2017-10-17 12:21 UTC, oli-obk commented
Unrelated and spurious?

```
[00:17:26] [ 98%] Building CXX object tools/obj2yaml/CMakeFiles/obj2yaml.dir/coff2yaml.cpp.o
[00:17:26] clang: error: unable to execute command: Segmentation fault: 11
[00:17:26] clang: error: linker command failed due to signal (use -v to see invocation)
```

Segfault looks bad though

2017-10-17 13:23 UTC, kennytm commented
@bors retry #38878

<details>

```
[00:17:25] Scanning dependencies of target obj2yaml
[00:17:25] [ 98%] Building CXX object tools/obj2yaml/CMakeFiles/obj2yaml.dir/obj2yaml.cpp.o
[00:17:26] [ 98%] Linking CXX executable ../../bin/llvm-symbolizer
[00:17:26] [ 98%] Building CXX object tools/obj2yaml/CMakeFiles/obj2yaml.dir/coff2yaml.cpp.o
[00:17:26] clang: error: unable to execute command: Segmentation fault: 11
[00:17:26] clang: error: linker command failed due to signal (use -v to see invocation)
[00:17:26] make[3]: *** [bin/llvm-symbolizer] Error 254
[00:17:26] make[2]: *** [tools/llvm-symbolizer/CMakeFiles/llvm-symbolizer.dir/all] Error 2
[00:17:26] make[2]: *** Waiting for unfinished jobs....
[00:17:26] [ 98%] Building CXX object tools/obj2yaml/CMakeFiles/obj2yaml.dir/dwarf2yaml.cpp.o
[00:17:26] [ 98%] Building CXX object tools/obj2yaml/CMakeFiles/obj2yaml.dir/elf2yaml.cpp.o
[00:17:26] [ 98%] Building CXX object tools/obj2yaml/CMakeFiles/obj2yaml.dir/macho2yaml.cpp.o
[00:17:26] [ 98%] Building CXX object tools/obj2yaml/CMakeFiles/obj2yaml.dir/Error.cpp.o
[00:17:27] [ 98%] Linking CXX executable ../../bin/obj2yaml
[00:17:27] [ 98%] Built target obj2yaml
[00:17:27] make[1]: *** [all] Error 2
[00:17:27] thread 'main' panicked at '
[00:17:27] command did not execute successfully, got: exit code: 2
[00:17:27] 
[00:17:27] build script failed, must exit now', /Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.26/src/lib.rs:599:4
[00:17:27] note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

</details>

2017-10-18 12:04 UTC, kennytm commented
@bors retry blame Travis.

2017-10-19 04:02 UTC, zackmdavis commented
goddamit @bors I _really_ wanted that [T-shirt](https://hacktoberfest.digitalocean.com/)

2017-10-19 06:55 UTC, kennytm commented
@bors retry 

* The macs 6.5-hour timed out. Still Travis's issue.

2017-10-19 14:38 UTC, estebank commented
It looks to me that travis/mac will timeout again :-/

2017-10-19 15:04 UTC, merged