Bring back slice::ref_slice.
rust-lang/rust pull request #45306
Opened 2017-10-15 13:31 UTC by whitequark

These functions were deprecated and removed in 1.5, but such simple
functionality shouldn't require using unsafe code, and it isn't
cluttering libstd too much.

The original removal was quite contentious (see #27774), since then
we've had precedent for including such nuggets of functionality (see rust-lang/rfcs#1789),
and @nikomatsakis has provided a lot of use cases in https://github.com/rust-lang/rfcs/pull/1789#issuecomment-314640034. Hence this PR.

I'm not too sure what to do with stability, feel free to correct me.
It seems pointless to go through stabilization for these functions though.

cc @aturon

2017-10-15 13:32 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @sfackler (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2017-10-15 13:33 UTC, whitequark commented
I didn't do anything to bring back `Option::as_slice` and `Result::as_slice` because `x.map_or(&[], ref_slice)` is almost as short and just as easy to understand.

2017-10-15 15:09 UTC, stjepang commented
Maybe it's just me, but, looking at the name alone, it's hard to tell what `slice::ref_slice` actually does.
Perhaps `slice::from_ref` would sound better? Or `slice::single_ref`? 🚲

2017-10-18 03:17 UTC, sfackler commented
I'm not particularly opposed to bringing this back, but I do agree with @stjepang's naming concern. We may want to land these as unstable initially, though I don't really know what good that would do in this specific case.

@rfcbot fcp merge

2017-10-18 03:26 UTC, Mark-Simulacrum commented
I've added the waiting-on-crater label for now so that if we decide to go ahead with this we do a crater run -- I think it's worth doing that just in case others have implemented ref_slice (which could play into the naming bikeshed, too, so probably best after fcp).

2017-10-18 03:30 UTC, sfackler commented
These are free functions, so I don't think there's as much of a concern with collisions as you'd have with new methods.

2017-10-18 09:08 UTC, scottmcm commented
Since the naming is uncertain and insta-stable is proposed anyway, could they just be
```rust
impl<'a, T> From<&'a T> for &'a [T] { ... }
impl<'a, T> From<&'a mut T> for &'a mut [T] { ... }
```

2017-10-18 10:09 UTC, whitequark commented
Personally, I think `slice::from_ref` is an obviously better name than `slice::ref_slice`. If I thought about naming at all (I did not, I just copied them from old rustc sources) then I would have chosen that too.

A `From` impl seems more disruptive to me.

2017-10-18 14:02 UTC, alexcrichton commented
I'd personally prefer to initially add these as unstable (but perhaps push on stabilization soon after landing), and I agree with @whitequark that a name like `from_ref` may be a bit nicer!

2017-10-23 22:47 UTC, Ixrec commented
Also strongly agree with `from_ref`. My first guess as to what `slice::ref_slice` would do was take a slice of Ts and convert it to a slice of refs of T.

2017-10-23 22:54 UTC, whitequark commented
Already renamed it, just not reflected in the PR.

2017-10-30 16:36 UTC, carols10cents commented
ping @BurntSushi waiting for your ticky box [here](https://github.com/rust-lang/rust/pull/45306#issuecomment-337450327)!

2017-10-30 17:26 UTC, steveklabnik commented
My crate that provides these functions also provides an `Option` variant: https://github.com/steveklabnik/ref_slice/blob/master/src/lib.rs

I'm not sure if they're worth bringing in too, figured I'd bring it up.

2017-10-30 17:34 UTC, whitequark commented
@steveklabnik https://github.com/rust-lang/rust/pull/45306#issuecomment-336711884

2017-10-31 22:13 UTC, alexcrichton commented
I'm going to go ahead and check @BurntSushi's checkbox as this is just unstable anyway.

2017-10-31 22:13 UTC, alexcrichton commented
@bors: r+

2017-11-01 05:16 UTC, kennytm requested changes

2017-11-01 05:16 UTC, kennytm commented on src/libcore/slice/mod.rs
> +#[stable(feature = "from_ref", since = "1.22.0")]
I don't think we intend to insta-stable these?

2017-11-01 05:17 UTC, kennytm commented
@bors r-

If the final FCP checkbox expects "this is just unstable anyway" the current code certainly isn't unstable.

2017-11-01 13:50 UTC, alexcrichton commented
Oops sorry, thanks for catching that @kennytm!

2017-11-01 21:41 UTC, whitequark commented
Can you please guide me on the stability markers here?

2017-11-01 21:49 UTC, kennytm commented
@whitequark 

1. File a [tracking issue](https://forge.rust-lang.org/feature-guide.html#tracking-issue)
2. Replace those `#[stable]` attributes with

      ```rust
      #[unstable(feature = "from_ref", issue = "45678")]
      ```

3. Write an unstable-book entry in `src/doc/unstable-book/src/library-features/from-ref.md` if you like.

2017-11-01 21:55 UTC, whitequark commented
Tracking issue filed as https://github.com/rust-lang/rust/issues/45703, no unstable book entry since it seems far too trivial.

2017-11-01 21:57 UTC, whitequark commented
Stability annotation updated.

2017-11-01 22:15 UTC, kennytm approved these changes

2017-11-01 22:18 UTC, kennytm commented
Thanks! It should be ready to go after fixing the build failure.

```
[00:02:34] error: use of unstable library feature 'from_ref' (see issue #45703)
[00:02:34]    --> /checkout/src/liballoc/slice.rs:123:23
[00:02:34]     |
[00:02:34] 123 | pub use core::slice::{from_ref, from_ref_mut};
[00:02:34]     |                       ^^^^^^^^
[00:02:34]     |
[00:02:34]     = help: add #![feature(from_ref)] to the crate attributes to enable
[00:02:34] 
[00:02:34] error: use of unstable library feature 'from_ref' (see issue #45703)
[00:02:34]    --> /checkout/src/liballoc/slice.rs:123:33
[00:02:34]     |
[00:02:34] 123 | pub use core::slice::{from_ref, from_ref_mut};
[00:02:34]     |                                 ^^^^^^^^^^^^
[00:02:34]     |
[00:02:34]     = help: add #![feature(from_ref)] to the crate attributes to enable
```

2017-11-01 22:21 UTC, whitequark commented
Updated.

2017-11-01 22:48 UTC, steveklabnik commented
Library stuff doesn't need an unstable book entry as the api docs are docs;
the unstable book pages get generated automatically.

On Wed, Nov 1, 2017 at 6:22 PM, whitequark <notifications@github.com> wrote:

> Updated.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/rust-lang/rust/pull/45306#issuecomment-341260874>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AABsikXJgsaCpcQfEEdjztR6V-nnUeB7ks5syO8KgaJpZM4P5v2u>
> .
>

2017-11-01 23:43 UTC, kennytm commented
@bors r=alexcrichton

2017-11-02 03:36 UTC, merged