add graphvis DOT files to dump mir directory
rust-lang/rust pull request #45497
Opened 2017-10-24 16:37 UTC by mikhail-m1

r? @nikomatsakis

2017-10-25 12:44 UTC, nikomatsakis requested changes

2017-10-25 12:44 UTC, nikomatsakis commented on src/librustc/session/config.rs
> +          "additionally to MIR create graphviz DOT files"),
Maybe: when dumping MIR, also create graphviz-style `.dot` files

2017-10-25 12:44 UTC, nikomatsakis commented
Looks good! Left a small comment.

2017-10-27 16:54 UTC, kennytm commented
@nikomatsakis The current wording is 

> additionally to `.mir` files, create graphviz `.dot` files

is it good enough for an r=?

2017-10-30 14:22 UTC, nikomatsakis approved these changes

2017-10-30 14:23 UTC, nikomatsakis commented
@bors r+

2017-10-30 20:01 UTC, kennytm commented
@bors retry 

* Travis incident causing Linux job not starting. https://www.traviscistatus.com/incidents/4vdl52d28hz3

2017-10-31 00:53 UTC, merged