Return 0 as an exit status when no subcommand is given to bootstrap
rust-lang/rust pull request #45535
Opened 2017-10-25 21:24 UTC by topecongiro

Running `./x.py` emits usage and error messages when no subcommand is given:
```
Usage: x.py <subcommand> [options] [<paths>...]

Subcommands:
    build       Compile either the compiler or libraries
    test        Build and run some test suites
    bench       Build and run some benchmarks
    doc         Build documentation
    clean       Clean out build directories
    dist        Build distribution artifacts
    install     Install distribution artifacts

To learn more about a subcommand, run `./x.py <subcommand> -h`

failed to run: /home/topecongiro/rust/build/bootstrap/debug/bootstrap
```
IMHO the last line is unnecessary. This PR removes it by changing the return code of `bootstrap` to 0 when no sub command is given.

2017-10-25 21:24 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2017-10-26 06:19 UTC, kennytm commented
The error code was explicitly changed from 0 to 1 in #44134. Could you ensure `./x.py nonsense` still returns nonzero?

2017-10-26 06:20 UTC, kennytm requested changes
The error code was explicitly changed from 0 to 1 in #44134. Could you ensure `./x.py nonsense` still returns nonzero?

2017-10-26 06:47 UTC, topecongiro commented
@kennytm Thank you for the review! I updated the PR so that `./x.py` returns 0 and `./x.py nonsense` returns 1.

2017-10-26 06:49 UTC, kennytm approved these changes

2017-10-26 09:38 UTC, kennytm approved these changes
Minor nit. r=me after this is fixed.

2017-10-26 09:38 UTC, kennytm commented on src/bootstrap/flags.rs
> +                // No or an invlaid subcommand -- show the general usage and subcommand help
Typo: `invlaid` ↦ `invalid`.

2017-10-27 00:28 UTC, topecongiro commented
@kennytm Thanks again, fixed a typo and rebased.

2017-10-27 08:22 UTC, kennytm commented
@bors r+ rollup

Thanks!

2017-10-28 12:15 UTC, merged