WIP: Playing with adding thread safety to GlobalCtxt
rust-lang/rust pull request #45912
Opened 2017-11-10 13:19 UTC by Zoxc

2017-11-10 13:20 UTC, Zoxc commented
@bors try

2017-11-10 14:54 UTC, shepmaster commented
@bors try

2017-11-10 14:55 UTC, shepmaster commented
Assigning to...

r? @pnkfelix

2017-11-10 21:53 UTC, Zoxc commented
What is everyone opinion on introducing locks and `Arc`s in rustc in an effort to make GlobalCtxt thread safe? We could redirect these types to `RefCell`, `Rc`, etc. in production builds to avoid paying the overhead for these thread safe types.

cc @rust-lang/compiler

2017-11-10 22:05 UTC, eddyb commented
I would rather not introduce `#[cfg]`s into `rustc` like that, FWIW.

2017-11-10 22:17 UTC, Zoxc commented
I'd like the ability to turn on and off thread safety so we can easily measure the overhead of it. That is going to require some `#[cfg]`s at least.

2017-11-13 10:36 UTC, michaelwoerister commented
If the `#[cfg]`s are very localized and they are clearly experimental, I'm not strictly against adding some. However, in such a case the effort of keeping such a patch around locally would not be too big either.

2017-11-14 14:02 UTC, Zoxc commented
@bors try

2017-11-14 15:14 UTC, Zoxc commented
@Mark-Simulacrum Can I get a perf run when bors completes?

2017-11-14 16:02 UTC, kennytm commented
@Zoxc please break every tool in `src/tools/toolstate.toml` and try again.

2017-11-14 16:16 UTC, bjorn3 requested changes

2017-11-14 16:16 UTC, bjorn3 commented on src/libarena/Cargo.toml
> +rustc_data_structures = { path = "../librustc_data_structures" }
Missing newline

2017-11-14 16:16 UTC, bjorn3 commented on src/librustc_data_structures/Cargo.toml
> +features = ["nightly", "owning_ref"]
Missing newline

2017-11-14 16:16 UTC, bjorn3 commented on src/librustc_data_structures/lock.rs
> +}
Missing newline

2017-11-19 10:42 UTC, kennytm commented
@bors try

2017-11-20 17:44 UTC, Zoxc commented
@bors try

2017-11-20 19:36 UTC, Zoxc commented
Currently there's some cfg's related to adding `Send` and `Sync` on trait objects. I expect these changes to go away when the next beta is used to build rustc. Please ignore them for now. Also see the initial comments for a overview of the changes.

r? @arielb1

2017-11-20 19:38 UTC, Zoxc commented
@Mark-Simulacrum Can I get a perf run on the try build which just completed?

2017-11-22 01:13 UTC, Mark-Simulacrum commented
I've started perf on the try commit, it should be live in ~30 minutes or so. The comparison page should just work.

2017-11-22 18:16 UTC, kennytm commented
The comparison page FYI. http://perf.rust-lang.org/compare.html?start=e06138338f78cd2695f857855e685e9e50a2486b&end=90ded1e1ad7c914726b74b2fa8afbd0794f47709&stat=instructions%3Au. Basically red in every metric.

2017-11-22 20:31 UTC, arielb1 commented
@kennytm 

This PR is just adding locks, so of course it would regress performance.

2017-11-22 20:38 UTC, Zoxc commented
The result for `regex-opt.0.1.30` is strange. It should spend more time in LLVM relative to `regex.0.1.30` so the overhead of the locking should decrease. Yet it has almost 3x the overhead.

2017-11-22 20:59 UTC, Zoxc commented
@Mark-Simulacrum Could you also run perf on the `699cd27b9c19fa921732aa45644e3f1295066ab9` try build?

2017-11-23 05:26 UTC, Mark-Simulacrum commented
Started; same as previously expect ~30 minute delay.

2017-11-23 12:46 UTC, Zoxc commented
[Here are the results](http://perf.rust-lang.org/compare.html?start=c5c70ef72369b00870d9fc67b99853b0681e17e2&end=699cd27b9c19fa921732aa45644e3f1295066ab9&stat=instructions%3Au). This build has all the thread safety disabled, so all the tests should be close to 0%, yet only a few are.

2017-12-01 18:35 UTC, shepmaster commented
Ping from triage @Zoxc — we haven't heard from you in a few days! Will you be able to address your conflicts?

2017-12-02 11:21 UTC, Zoxc commented
Since the new bootstrap compiler landed, all the cfg's are now inside the `sync` module :)

I don't know what to do with the `owning_ref` fork though. Do we have a policy of what to do with upstream crate forks?

2017-12-17 16:56 UTC, Zoxc commented
This is being split into smaller PRs.

2017-12-17 16:56 UTC, closed without merging