rustbuild: distribute cargo-fmt alongside rustfmt
rust-lang/rust pull request #46031
Opened 2017-11-16 09:59 UTC by Keruspe

Not sure whether we want that nor if it's the right way to do so, but it feels quite weird to have rustfmt without cargo-fmt. Or are there other plans wrt that?

What do you think @nrc ?

2017-11-18 09:46 UTC, kennytm commented
r? @nrc

2017-11-20 02:17 UTC, nrc commented
Thanks! Seems good to me, but r? @Mark-Simulacrum for the build system changes.

2017-11-20 02:58 UTC, Mark-Simulacrum requested changes
Looks pretty good. I'm not too happy with the macro, but I think it's okay for now at least. We do similar things elsewhere, and until we come up with a better solution this should work.

Please fix the one comment and r=me afterwards.

2017-11-20 02:58 UTC, Mark-Simulacrum commented on src/bootstrap/dist.rs
> +        }).expect("Rustfmt to build: toolstate is testing");
Please change the expect statement here to "cargofmt" or something like that.

2017-11-20 09:05 UTC, Keruspe commented
r= @Mark-Simulacrum

2017-11-20 09:07 UTC, Keruspe commented
@bors: r=Mark-Simulacrum

2017-11-20 09:08 UTC, Keruspe commented
(I kind of expected that indeed, would have been surprised otherwise)

2017-11-20 14:03 UTC, Keruspe commented
@kennytm not waiting on bors yet, fwiw (wrt tags)

2017-11-20 14:09 UTC, Mark-Simulacrum commented
@bors r+

2017-11-20 15:03 UTC, oli-obk commented
`cargo fmt` could be implemented as a stable `cargo install`able tool, which would not require distributing it, since it would never break.

2017-11-21 20:05 UTC, merged