Rename C-like enum to Field-less enum
rust-lang/rust pull request #46187
Opened 2017-11-22 17:55 UTC by notriddle

There is no need to reference the C programming language to explain this concept.

2017-11-22 17:56 UTC, rust-highfive commented
r? @alexcrichton

(rust_highfive has picked a reviewer for you, use r? to override)

2017-11-22 18:04 UTC, kennytm commented
Context: https://internals.rust-lang.org/t/proposal-bikeshed-rename-c-like-enumeration/6209

Randomly reassigning to someone in the docs team… r? @frewsxcv

2017-11-22 19:28 UTC, steveklabnik commented
Until the decisions is made, we can't accept this PR.

2017-11-28 21:42 UTC, QuietMisdreavus commented
Pending discussion on https://github.com/rust-lang/rust/issues/46348 from lang team, i'm reopening this PR.

2017-12-06 12:49 UTC, kennytm commented
Randomly reassigning to member on the lang team… r? @cramertj

2017-12-06 17:47 UTC, QuietMisdreavus requested changes
The lang team (via @withoutboats) has given a quiet assent for this change, so i'll take it over from a docs perspective.

2017-12-06 17:47 UTC, QuietMisdreavus commented on src/librustc/diagnostics.rs
>  `enum Color {Red, Blue, Green}`), effectively setting the size of the enum to
You took out the opening parenthesis, but left the closing one here (after "`enum Color`").

2017-12-06 17:47 UTC, QuietMisdreavus commented on src/librustc/diagnostics.rs
> +Only field-less enums can be cast to numerical primitives, so this attribute will
This line is longer than 80 characters, which caused the build to fail on travis.

2017-12-06 17:55 UTC, notriddle commented
Fixed both.

2017-12-06 22:30 UTC, QuietMisdreavus approved these changes

2017-12-06 22:31 UTC, QuietMisdreavus commented
Excellent! Thanks so much!

@bors r+ rollup

2017-12-07 09:47 UTC, merged