Lint against single-use lifetime names WIP
rust-lang/rust pull request #46441
Opened 2017-12-02 07:51 UTC by gaurikholkar

This is a fix for #44752 

TO-DO
*  change lint message
*  add ui tests 

r? @nikomatsakis

2017-12-02 09:11 UTC, oli-obk commented on src/librustc/lint/builtin.rs
> -            UNUSED_IMPORTS,
Unrelated reformatting.

2017-12-02 09:11 UTC, oli-obk commented on src/librustc/middle/resolve_lifetime.rs
> +    EarlyBound(/* index */
Please move the formatting changes into their own commit or undo them. It's very hard to see the non-formatting changes among them

2017-12-02 10:44 UTC, nikomatsakis commented
Regarding the formatting changes, what I usually find helpful is to have the first commit just rustfmt's the whole file, and then start from there. Then when you rebase, if you get conflicts in this commit, you can just take the "master" version of the code indiscriminately and then re-run rustfmt afterwards. (This...mostly works. Sometimes I find code gets duplicated.)

2017-12-02 11:00 UTC, gaurikholkar commented
I guess most of it is undone. Will take care of the rest in a separate commit

2017-12-02 11:38 UTC, gaurikholkar commented on src/librustc/lint/builtin.rs
> -            UNUSED_IMPORTS,
fixed formatting changes @oli-obk

2017-12-03 12:10 UTC, gaurikholkar commented
@nikomatsakis @oli-obk I get this error
```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.24.0-dev running on x86_64-apple-darwin

thread 'rustc' panicked at 'assertion failed: def_id.is_local()', src/librustc/hir/map/mod.rs:309:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: Could not compile `alloc`.

Caused by:
  process didn't exit successfully: `/Users/gkholkar/Desktop/or/rust/build/bootstrap/debug/rustc --crate-name alloc src/liballoc/lib.rs --error-format json --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=22e63b537c61a4f8 -C extra-filename=-22e63b537c61a4f8 --out-dir /Users/gkholkar/Desktop/or/rust/build/x86_64-apple-darwin/stage1-std/x86_64-apple-darwin/release/deps --target x86_64-apple-darwin -L dependency=/Users/gkholkar/Desktop/or/rust/build/x86_64-apple-darwin/stage1-std/x86_64-apple-darwin/release/deps -L dependency=/Users/gkholkar/Desktop/or/rust/build/x86_64-apple-darwin/stage1-std/release/deps --extern core=/Users/gkholkar/Desktop/or/rust/build/x86_64-apple-darwin/stage1-std/x86_64-apple-darwin/release/deps/libcore-a1b407ed3953731d.rlib --extern std_unicode=/Users/gkholkar/Desktop/or/rust/build/x86_64-apple-darwin/stage1-std/x86_64-apple-darwin/release/deps/libstd_unicode-aa82a4fba39f1481.rlib` (exit code: 101)
thread 'main' panicked at 'command did not execute successfully: "/Users/gkholkar/Desktop/or/rust/build/x86_64-apple-darwin/stage0/bin/cargo" "build" "--target" "x86_64-apple-darwin" "-j" "4" "--release" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/Users/gkholkar/Desktop/or/rust/src/libstd/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101', src/bootstrap/compile.rs:882:8
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: /Users/gkholkar/Desktop/or/rust/build/bootstrap/debug/bootstrap build --stage 1 src/libsyntax
Build completed unsuccessfully in 0:18:18
```

2017-12-04 07:12 UTC, gaurikholkar commented
Will fix the ui tests

2017-12-04 07:13 UTC, oli-obk commented
They are failing with an ICE: `unelided lifetime in signature`. Can you get a backtrace for such a failure?

2017-12-04 07:26 UTC, gaurikholkar commented
Afk for a while. Will check as asap

2017-12-05 05:58 UTC, gaurikholkar-zz reviewed
How do I write both the errors occuring on the same line on the .rs files for this test?

2017-12-05 08:19 UTC, oli-obk commented
You can write `//~^ ERROR foo` in the line below. If you have even more messages per line, start adding `//~| ERROR bar` below a line with the `^`

2017-12-08 21:05 UTC, nikomatsakis commented
So I feel like the new code is generating unexpected errors. I'm going to poke around a bit.

2017-12-08 21:23 UTC, nikomatsakis commented
I'm going to open a PR with just the resolve-lifetimes query work, so we can isolate what is effecting what.

2017-12-11 15:08 UTC, nikomatsakis commented
Blocked on https://github.com/rust-lang/rust/pull/46657

2017-12-12 11:19 UTC, nikomatsakis commented
OK #46657 landed -- @gaurikholkar, can you rebase atop that?

2017-12-12 11:42 UTC, gaurikholkar commented
@nikomatsakis at it

2017-12-14 16:07 UTC, gaurikholkar commented
@nikomatsakis build passed :)

2017-12-18 20:48 UTC, nikomatsakis requested changes
This is looking pretty good. I think we need a few more tests. It's probably not quite working right, but I'd be happy to get something landed and try to refine later.

2017-12-19 09:13 UTC, nikomatsakis commented
Oh, in my review, I realize I wasn't clear. The "Nit: formatting" bits was just meant to say that these changes weren't *necessary*, though also not harmful. Ideally they would be isolated into a separate commit (or else pulled out).

2017-12-19 17:55 UTC, nikomatsakis approved these changes

2017-12-19 19:23 UTC, nikomatsakis commented
@bors r+

2017-12-20 03:58 UTC, merged