Stablize RefCell::{replace, swap}
rust-lang/rust pull request #46517
Opened 2017-12-05 16:07 UTC by notriddle

RefCell::replace_with is not stablized in this PR, since it wasn't part of the RFC.

CC #43570

2017-12-05 16:07 UTC, rust-highfive commented
r? @aidanhs

(rust_highfive has picked a reviewer for you, use r? to override)

2017-12-05 16:45 UTC, aidanhs commented
r? @BurntSushi

2017-12-05 16:54 UTC, BurntSushi commented
@rfcbot fcp merge

2017-12-05 18:58 UTC, Mark-Simulacrum commented
```
[00:03:57] tidy error: /checkout/src/libcore/cell.rs:619: mismatches to previous in: ["stability level", "since", "tracking issue"]
[00:03:57] tidy error: /checkout/src/libcore/cell.rs:646: mismatches to previous in: ["stability level", "since", "tracking issue"]
```

2017-12-05 20:11 UTC, dtolnay requested changes
I think when we stabilize *part* of a library feature, we pick a new name for the stabilized part and keep the old feature name for the remaining unstable part. This minimizes nightly breakage for code that is currently calling `replace_with`.

2017-12-13 09:28 UTC, kennytm commented
Ping @aturon for ticky boxes [here](https://github.com/rust-lang/rust/pull/46517#issuecomment-349367449)!

2017-12-19 21:10 UTC, notriddle commented
@dtolnay I fixed the feature flags to work the way you asked.

2017-12-19 22:12 UTC, alexcrichton commented
@bors: r=BurntSushi

2017-12-20 17:34 UTC, merged