Generate code for unused const- and inline-fns if -Clink-dead-code is specified.
rust-lang/rust pull request #46916
Opened 2017-12-21 16:59 UTC by michaelwoerister

Fixes https://github.com/rust-lang/rust/issues/46467.

r? @alexcrichton

2017-12-21 17:04 UTC, alexcrichton commented
@bors: r+

Nice!

2017-12-21 21:05 UTC, kennytm requested changes

2017-12-21 21:05 UTC, kennytm commented on src/test/codegen/link-dead-code.rs
> +const fn const_fn() -> usize { 1 }
Please change the `usize` to some more portable type. This test is failing on 32-bit platforms.

```
[00:52:46] ---- [codegen] codegen/link-dead-code.rs stdout ----
[00:52:46] 	
[00:52:46] error: verification with 'FileCheck' failed
[00:52:46] status: exit code: 1
[00:52:46] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/llvm/build/bin/FileCheck" "--input-file" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/link-dead-code.ll" "/checkout/src/test/codegen/link-dead-code.rs"
[00:52:46] stdout:
[00:52:46] ------------------------------------------
[00:52:46] 
[00:52:46] ------------------------------------------
[00:52:46] stderr:
[00:52:46] ------------------------------------------
[00:52:46] /checkout/src/test/codegen/link-dead-code.rs:19:17: error: expected string not found in input
[00:52:46] // CHECK-LABEL: define hidden i64 @_ZN14link_dead_code8const_fn
[00:52:46]                 ^
[00:52:46] /checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/link-dead-code.ll:1:1: note: scanning from here
[00:52:46] ; ModuleID = 'link_dead_code0-8787f43e282added376259c1adb08b80.rs'
[00:52:46] ^
[00:52:46] /checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/link-dead-code.ll:8:1: note: possible intended match here
[00:52:46] define hidden i32 @_ZN14link_dead_code8const_fn17h307759a84b38b8b4E() unnamed_addr #0 {
[00:52:46] ^
[00:52:46] 
[00:52:46] ------------------------------------------
[00:52:46] 
[00:52:46] thread '[codegen] codegen/link-dead-code.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2776:8
[00:52:46] note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

2017-12-29 21:23 UTC, pnkfelix commented
@michaelwoerister are you going to be able to address the problem pointed out by kennytm?

Times getting very tight to backport this into beta...

2018-01-04 09:09 UTC, michaelwoerister commented
Whoops, sorry, didn't see this because of PTO.

2018-01-04 10:42 UTC, kennytm approved these changes

2018-01-04 10:59 UTC, michaelwoerister commented
@bors r=alexcrichton

2018-01-04 17:02 UTC, merged

2018-01-10 15:47 UTC, alexcrichton commented
Accepting for backport as it fixes a regression https://github.com/rust-lang/rust/issues/46467