Implement AsRef<Path> for Component
rust-lang/rust pull request #46985
Opened 2017-12-24 17:41 UTC by Diggsey

Fixes #41866

2017-12-24 17:41 UTC, rust-highfive commented
r? @BurntSushi

(rust_highfive has picked a reviewer for you, use r? to override)

2017-12-28 12:55 UTC, BurntSushi requested changes

2017-12-28 12:55 UTC, BurntSushi commented on src/libstd/path.rs
> +#[unstable(feature = "path_component_asref", issue = "41866")]
Trait impls are insta-stable. Please change this to a `stable` attribute.

2017-12-28 12:56 UTC, BurntSushi commented
This seems reasonable to me. @rfcbot fcp merge

2017-12-28 13:29 UTC, Diggsey commented
@BurntSushi is that correct? Is there any documentation about stability attributes?

2017-12-28 13:32 UTC, kennytm commented
(@BurntSushi The `@rfcbot fcp merge` should be on its own line)

2017-12-28 13:34 UTC, BurntSushi commented
@rfcbot fcp merge

2017-12-28 13:35 UTC, BurntSushi commented
@Diggsey 

> is that correct? Is there any documentation about stability attributes?

cc @rust-lang/libs

2018-01-04 18:52 UTC, sfackler commented
Yeah, that stability attribute looks right.

2018-01-10 13:38 UTC, kennytm commented
Ping @aturon, ticky box for you! https://github.com/rust-lang/rust/pull/46985#issuecomment-354289123

2018-01-12 05:15 UTC, alexcrichton commented
@bors: r+

2018-01-12 23:28 UTC, merged

2018-03-06 16:12 UTC, vitiral commented
I'm a little confused why adding an `AsRef` caused crates to stop compiling. Could there be a brief triage of why that is (and why rust is going forward with breaking changes)?

2018-03-06 16:17 UTC, BurntSushi commented
@vitiral It's well covered ground, but I actually don't know of any central resource on the matter. AFAIK, if your use of `AsRef` breaks then it's generally because it is being misused, and in general, it's not feasible to never add new trait impls.

2018-03-06 16:17 UTC, BurntSushi commented
(From a technicality perspective, we're empowered to make changes like this via the [API evolution RFC](https://github.com/nox/rust-rfcs/blob/master/text/1105-api-evolution.md), but pragmatism rules the day.)

2018-03-06 16:19 UTC, Diggsey commented
Here is the specific relevant section: https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md#minor-change-implementing-any-non-fundamental-trait