Add NLL tests for #46557 and #38899
rust-lang/rust pull request #47368
Opened 2018-01-11 23:14 UTC by chrisvittal

This adapts the sample code from the two issues as test code.

Closes #47366 

r? @nikomatsakis

2018-01-11 23:16 UTC, chrisvittal commented
The mentoring instructions were unclear here. It seems that we want these tests to fail compilation as they both unsoundly passed AST borrowck.

2018-01-12 12:03 UTC, pnkfelix commented
@chrisvittal When you said the instructions were unclear, were you referring to the step that said that the tests should include the comment `// must-compile-successfully` ? (Because I agree: the two cases that @nikomatsakis listed are ones where the whole point is that they start *failing* to compile under `#![feature(nll)]`

2018-01-12 12:05 UTC, pnkfelix commented
Also I think the intention is that this PR should be closing  #46557  and #38899 . I don't know if it is premature to close #47366 as well, though I guess we can always reopen it if we find other MIR issues...

2018-01-12 15:24 UTC, nikomatsakis commented
That was a mistake on my part. We *expect* errors!

2018-01-12 15:25 UTC, nikomatsakis requested changes
(also remove flags from other test)

2018-01-12 15:25 UTC, nikomatsakis commented on src/test/ui/nll/borrowed-referent-issue-38899.rs
> +// compile-flags:-Znll -Zborrowck=mir -Zverbose
can we remove the `compile-flags`? They should not be necessary. `feature(nll)` should suffice.

2018-01-12 18:59 UTC, nikomatsakis approved these changes

2018-01-12 18:59 UTC, nikomatsakis commented
@bors r+

2018-01-15 15:37 UTC, merged