Fix overflow when performing drop check calculations in NLL
rust-lang/rust pull request #47920
Opened 2018-02-01 03:15 UTC by Aaron1011

Clearing out the infcx's region constraints after processing each type
ends up interacting badly with normalizing associated types. This commit
keeps all region constraints intact until the end of
TypeLivenessGenerator.add_drop_live_constraint, ensuring that normalized
types are able to re-use existing inference variables.

Fixes #47589

2018-02-01 03:15 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @pnkfelix (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2018-02-01 18:45 UTC, nikomatsakis approved these changes

2018-02-01 18:45 UTC, nikomatsakis commented
@bors r+ -- this may be a perf win as well

2018-02-01 20:30 UTC, nikomatsakis commented
r? @nikomatsakis

2018-02-02 18:25 UTC, Mark-Simulacrum requested changes

2018-02-02 18:25 UTC, Mark-Simulacrum commented on src/librustc_mir/borrow_check/nll/type_check/liveness.rs
> +//use rustc::ty::subst::Kind;
nit: should be removed

2018-02-02 18:25 UTC, Mark-Simulacrum commented
@bors r-

2018-02-02 19:59 UTC, Aaron1011 commented
@Mark-Simulacrum: Fixed

2018-02-02 22:58 UTC, pnkfelix commented
@bors r+

2018-02-05 12:05 UTC, merged