add transform for uniform array move out
rust-lang/rust pull request #47926
Opened 2018-02-01 09:29 UTC by mikhail-m1

reworked second step for fix #34708
previous try #46686
r? @nikomatsakis

2018-02-01 22:01 UTC, arielb1 commented
This looks like the KISS approach that might just enable us to stabilize slice patterns.

2018-02-05 18:28 UTC, nikomatsakis requested changes
Very nice! Left various style nits and also some testing suggestions.

2018-02-05 18:28 UTC, nikomatsakis commented on src/librustc_mir/transform/uniform_array_move_out.rs
> +// drops for array without additional work.
I think that, to document this sort of thing, it is best if we can start with a comment that includes some kind of "before/after" -- e.g., show the MIR that we are starting with, and the MIR that we are ending with. Then, in the actual code, we can leave comments that reference this running example.

2018-02-05 18:28 UTC, nikomatsakis commented on src/librustc_mir/transform/uniform_array_move_out.rs
> +                                let _temp = patch.new_temp(_t, mir.source_info(location).span);
Nit: there should never be a use of a variable named with `_t` -- the leading `_` is a signal that you *don't* use the variable... can we give it some other name? (Same with `_temp`)

2018-02-05 18:28 UTC, nikomatsakis commented on src/librustc_mir/transform/uniform_array_move_out.rs
> +                            let mut temps = vec![];
Nit: doesn't matter, but I would personally write this with an iterator

```
let temps: Vec<_> =
    (from..to)
    .map(|i| {
       let temp = patch.new_temp(...);
       ...
       temp
    })
    .collect();
```

2018-02-05 18:28 UTC, nikomatsakis commented on src/librustc_mir/transform/uniform_array_move_out.rs
> +                                                                 offset: _i,
Nit: Name this `i`, not `_i`

2018-02-05 18:28 UTC, nikomatsakis commented on src/librustc_mir/transform/uniform_array_move_out.rs
> +                        ProjectionElem::Subslice{from, to} => {
Example comment:

---

Before we have:

```
X = move Y[3..5]
```

we want to transform to the following patch:

```
- X = move Y[3..5]
+ tmp0 = move Y[3];
+ tmp1 = move Y[4];
+ X = [tmp0, tmp1];
```

2018-02-05 18:28 UTC, nikomatsakis commented on src/librustc_mir/transform/uniform_array_move_out.rs
> +                        ProjectionElem::ConstantIndex{offset, min_length: _, from_end: true} => {
Some kind of comment would be good here. Probably:

---

Normalize "from-end" indices to operate from the start.

2018-02-05 18:28 UTC, nikomatsakis commented on src/test/compile-fail/borrowck/borrowck-move-out-from-array.rs
> +}
I think this transformation should have a `src/test/mir-opt` test that shows the before/after for various interesting cases. Can you add that?

2018-02-12 11:09 UTC, pietroalbini commented
@nikomatsakis the author seems to have fixed your concerns, could you review this again?

2018-02-12 19:50 UTC, nikomatsakis approved these changes

2018-02-12 19:50 UTC, nikomatsakis commented
@bors r+

Very cool

2018-02-17 11:32 UTC, merged