Do not run the default panic hook inside procedural macros. Fixes #47812
rust-lang/rust pull request #47933
Opened 2018-02-01 17:11 UTC by Zoxc

r? @nikomatsakis

2018-02-01 17:31 UTC, nikomatsakis requested changes
clearly we need to fix that test you mentioned -- or maybe we can do a UI test? Seems like we ought to be able to, no?

2018-02-02 15:36 UTC, Zoxc commented
I don't know why the test does not work. It is already an UI test which tests stderr.

2018-02-05 20:50 UTC, nikomatsakis commented
@Zoxc I'd like to understand that :/

2018-02-10 02:40 UTC, Zoxc commented
I probably should move the panic handler to librustc. I want to sneak in some printing of the query stack on panic too.

2018-02-12 19:41 UTC, nikomatsakis commented
@Zoxc I did some investigating, not sure if I mentioned it here; I was not able to reproduce the problem except for on nightly builds. Any clue why that might be?

2018-02-12 19:42 UTC, nikomatsakis commented
I guess we can land in the meantime, but it's vexing.

2018-02-13 02:37 UTC, Zoxc commented
I don't have any ideas about why the test failed.

2018-02-13 03:41 UTC, Mark-Simulacrum commented
This is the reason for the test failure: https://github.com/rust-lang/rust/blob/master/src/tools/compiletest/src/json.rs#L88. Specifically, non-JSON lines in the output are simply ignored by compiletest, which means that any UI test will fail to test this behavior.

I think the most straightforward fix here would be to change this to a run-make test.

@Zoxc Is there a chance you could make that change?

2018-02-13 03:54 UTC, Zoxc commented
@Mark-Simulacrum So does compiletest ask for JSON output and then convert that into what the stderr output would be? Could we make it also emit the non-JSON lines to this output?

2018-02-13 04:02 UTC, Mark-Simulacrum commented
Actually, now that I do some deeper investigation, it looks like if we put `// compile-flags:--error-format human` everything will work. We detect this in compiletest and if we see any format of error-format in the compile args we'll bail out of the JSON parsing and just check the raw outputs.

So looks like the fix is even simpler than I thought!

2018-02-13 17:01 UTC, nikomatsakis commented
@Mark-Simulacrum thanks for that!

2018-02-13 21:01 UTC, nikomatsakis commented
@bors r+

2018-02-15 17:22 UTC, nikomatsakis approved these changes

2018-02-19 16:58 UTC, nikomatsakis commented
@Zoxc needs rebase :(

2018-02-20 21:06 UTC, Zoxc commented
@bors r=nikomatsakis

2018-02-24 10:30 UTC, merged