Better document the implementors of Clone and Copy
rust-lang/rust pull request #48171
Opened 2018-02-12 22:10 UTC by FraGag

There are two parts to this change. The first part is a change to the compiler and to the standard library (specifically, libcore) to allow implementations of `Clone` and `Copy` to be written for a subset of builtin types. This is a [breaking-change] for users of `#![no_core]`, because they will now have to supply their own copy of the implementations of `Clone` and `Copy` that were added in libcore.

The second part is purely a documentation change to document the other implementors of `Clone` and `Copy` that cannot be described in Rust code (yet) and are thus provided by the compiler.

Fixes #25893

2018-02-12 22:10 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @JoshTriplett (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2018-02-16 19:25 UTC, joshtriplett commented
Sorry for the delayed response.

This looks plausible to me, and I like the idea of moving this out of compiler magic and into the library itself.

I'd like to get at least one other reviewer to check this.

r? @nikomatsakis

2018-02-16 21:11 UTC, shepmaster commented
> This is a [breaking-change] for users of #![no_core]

Should we solicit opinions of people who might be affected by this?

2018-02-16 21:31 UTC, rkruppe commented
I believe there are practically no legitimate use cases of no_core other than compiler developers trying to minimize a problem occurring in libcore. Using it is inherently very deeply entangled with compiler internals. Many routine changes can already break no_core usage, such as changing anything about any lang item (including adding or removing them), or even just changing something about the compiler such that compiling your code requires a lang item that previously wasn't required. Basically, using no_core out of tree is not supported.

2018-02-16 21:36 UTC, shepmaster commented
> I believe there are practically no legitimate use cases of no_core other than compiler developers trying to minimize a problem occurring in libcore.

I know that [I've needed to use it when attempting to get AVR-Rust off the ground](https://github.com/shepmaster/rust-arduino-blink-led-no-core-with-cargo/blob/master/blink/src/main.rs), I kind of assumed that other embedded folk have needed to do the same.

2018-02-16 21:38 UTC, joshtriplett commented
Probably couldn't hurt to raise attention on this via TWiR and/or an internals thread.

2018-02-16 21:43 UTC, rkruppe commented
@shepmaster Good point, I forgot about AVR-Rust, sorry! I have reason to suspect AVR-Rust is pretty unique in this regard, though. Most embedded stuff is happening with more mature LLVM backends which have no problem (or not nearly as big a problem, e.g., they may just be missing support for some obscure intrinsics) getting libcore to compile. For example, MPS430 seems to have working libcore .

2018-02-16 21:50 UTC, rkruppe commented
And to be clear, "getting a new target off the ground" is a totally legitimate use of no_core (I've even used it for that myself), but I count that under "usage by compiler developers" and it should usually be very temporary (AVR apparently being an exception). Since there are few compiler developers and even fewer targets being added, I don't think it's particularly likely that this PR will land after someone copied something from libcore, yet before they scrapped that copy and started compiling libcore as-is.

2018-02-16 22:04 UTC, shepmaster commented
To be clear, **I** don't have a problem with this change affecting AVR-Rust, it's simply the only reason I know about `no_core`.

> I have reason to suspect AVR-Rust is pretty unique in this regard, though
>
> And to be clear, "getting a new target off the ground" is a totally legitimate use of no_core

I think this is where AVR-Rust is at as well; it's just taking longer because the LLVM support is being worked on in parallel.

> I forgot about AVR-Rust, sorry

Not to worry; it's not anywhere near feature complete ;-)

2018-02-20 21:46 UTC, nikomatsakis commented
@FraGag 

> The first part is a change to the compiler and to the standard library (specifically, libcore) to allow implementations of Clone and Copy to be written for a subset of builtin types.

Can you say a bit more about the motivation here? Is it rustdoc or something else?

2018-02-20 21:51 UTC, shepmaster commented
@nikomatsakis several comments on [the original issue](https://github.com/rust-lang/rust/issues/25893) stem from Stack Overflow question-askers not knowing that e.g. `i32` is `Copy`. I'd say that documenting these would be a net win, but I'm not sure if there's more.

2018-02-20 21:52 UTC, nikomatsakis requested changes
Left a few nits but I think overall this is ok. I wonder if it will affect performance.

2018-02-20 21:52 UTC, nikomatsakis commented on src/librustc_typeck/diagnostics.rs
> +examples will fail, because neither `fn() -> i32` nor `&'static mut Bar`
I don't think we should include `fn() -> i32` as a sample type. `&'static mut Bar` is ok I guess.

2018-02-20 21:52 UTC, nikomatsakis commented on src/librustc_typeck/diagnostics.rs
> +examples will fail, because neither `fn() -> i32` nor `&'static mut Bar`
What about `[u8; 256]`?

2018-02-20 21:52 UTC, nikomatsakis commented on src/librustc_typeck/diagnostics.rs
> +examples will fail, because neither `fn() -> i32` nor `&'static mut Bar`
Also, can you add a new test for what happens when we *do* implement for `u32` (outside of libcore)? I guess we get a standard overlap failure, huh? Seems ok.

2018-02-24 23:56 UTC, FraGag commented
@nikomatsakis Addressed nits. I'll squashed and rebase when it's approved.

2018-02-27 17:55 UTC, nikomatsakis approved these changes

2018-02-27 17:55 UTC, nikomatsakis commented
@FraGag looks good =)

2018-03-01 04:10 UTC, FraGag commented
@nikomatsakis Squashed and rebased. The merge conflicts were just line numbers in `.stderr` files being anonymized by #48449.

2018-03-01 19:11 UTC, nikomatsakis reviewed
Can you change the 1.0.0 -- but to what...

2018-03-01 19:11 UTC, nikomatsakis commented on src/libcore/marker.rs
> +    #[stable(feature = "rust1", since = "1.0.0")]
I guess it doesn't matter, but `!` has not been present since `1.0.0`. In fact, the type itself isn't even stable yet!

2018-03-01 19:19 UTC, nikomatsakis commented
OK, I updated to 1.25.0

2018-03-01 19:19 UTC, nikomatsakis commented
@bors r+

2018-03-01 23:22 UTC, FraGag commented
@nikomatsakis You had changed the version on `impl Clone for !` but not on `impl Copy for !`... I amended the commit to also change the latter. r?

2018-03-02 17:27 UTC, nikomatsakis commented
@FraGag 

Sounds good, but travis is kind of unhappy:

https://travis-ci.org/rust-lang/rust/builds/348015686#L1092

Maybe something wrong with my change after all =)

2018-03-02 17:28 UTC, nikomatsakis commented
I don't really know what error is about

2018-03-02 17:34 UTC, ollie27 commented
The stability attributes for the impls for `!` should be `#[unstable(feature = "never_type", issue = "35121")]` like the other impls for `!`.

2018-03-03 05:20 UTC, FraGag commented
Oops, I forgot to `git add` before amending last time. Anyway, now both impls are marked unstable (squashed in the first commit).

@nikomatsakis r?

2018-03-11 01:06 UTC, FraGag commented
I reproduced the test failure locally. The problem is that `iter::repeat` uses `Clone`, and I didn't put `#[inline]` on the implementations of `Clone::clone` that I added, so the compiler emitted calls to the `clone` method and this inhibited the optimization. I pushed a commit to add the missing `#[inline]` attributes (they really ought to be `#[inline]`!)

Why did this only fail on one platform though? I looked at the generated LLVM IR and I noticed that on `x86_64-unknown-linux-gnu`, even when the optimization didn't kick in, the IR still contained a call to `llvm.memset` to zero-initialize the `RawVec` in the `Vec`, which made the test pass erroneously. On `i686-pc-windows-gnu` though, the `RawVec` is zero-initialized with two `store` instructions instead, so there are indeed no occurrences of `llvm.memset`. I've updated the test to check for specific argument values on the `llvm.memset` call, and verified that it fails on `x86_64-unknown-linux-gnu` when the `#[inline]` attributes are missing.

@nikomatsakis r?

2018-03-12 16:04 UTC, nikomatsakis commented
@FraGag nice digging!

2018-03-12 16:04 UTC, nikomatsakis commented
@bors r+

2018-03-12 16:04 UTC, nikomatsakis commented
Also, score one for tests.

2018-03-13 09:37 UTC, kennytm commented
Cannot document `liblibc`. This crate is `#![cfg_attr(dox, no_core)]`.

```
[01:34:22] [m[m[32m[1m   Compiling[m compiler_builtins v0.0.0 (file:///checkout/src/rustc/compiler_builtins_shim)
[01:34:22] error[E0204]: the trait `Copy` may not be implemented for this type
[01:34:22]    --> rustc/libc_shim/../../liblibc/src/macros.rs:44:14
[01:34:22]     |
[01:34:22] 44  |           impl ::dox::Copy for $i {}
[01:34:22]     |                ^^^^^^^^^^^
[01:34:22]     | 
[01:34:22]    ::: rustc/libc_shim/../../liblibc/src/unix/mod.rs:19:1
[01:34:22]     |
[01:34:22] 19  | / s! {
[01:34:22] 20  | |     pub struct group {
[01:34:22] 21  | |         pub gr_name: *mut ::c_char,
[01:34:22]     | |         -------------------------- this field does not implement `Copy`
[01:34:22] 22  | |         pub gr_passwd: *mut ::c_char,
[01:34:22] ...   |
[01:34:22] 186 | |     }
[01:34:22] 187 | | }
[01:34:22]     | |_- in this macro invocation
```

2018-03-18 15:18 UTC, shepmaster commented
Ping from triage, @FraGag ! Will you have time to address the issues soon?

2018-03-18 16:00 UTC, FraGag commented
@shepmaster Yes, I'm working on it.

2018-03-26 11:10 UTC, pietroalbini commented
@FraGag weekly ping from the triage team! What's the status on this?

2018-03-27 04:36 UTC, FraGag commented
Now that https://github.com/rust-lang/libc/pull/951 has been merged and libc 0.2.40 published, I can progress.

I just rebased and tweaked my branch to account for the changes made in https://github.com/rust-lang/rust/pull/49299, which made some changes to the documentation for `Clone` and `Copy`, to avoid redundancy with the changes I had made previously and to remove now broken links to the unstable book (thanks to the linkchecker tool for catching these!).

@nikomatsakis r?

2018-03-30 19:41 UTC, shepmaster commented
Ping from triage, @nikomatsakis !

2018-04-04 17:19 UTC, nikomatsakis approved these changes

2018-04-04 21:12 UTC, merged