Start moving to the rustc guide!
rust-lang/rust pull request #48479
Opened 2018-02-23 19:29 UTC by mark-i-m

r? @nikomatsakis 

cc #48478

2018-02-23 22:21 UTC, nikomatsakis requested changes
r=me after that one nit

2018-02-23 22:21 UTC, nikomatsakis commented on src/librustc/README.md
> -An informal guide to reading and working on the rustc compiler.
Can you replace this with a README -- or maybe doc-comment on the crate -- that says to see the rustc guide? I know it's in other places, but I want to make it as visible as possible.

2018-02-23 22:22 UTC, nikomatsakis commented
Oh, one other thing. I think there may be references to those deleted READMEs in doc-comments and things. Could you maybe redirect those to the appropriate URL in the rustc guide?

Examples:

https://github.com/rust-lang/rust/blob/063deba92e44809125a433ca6e6c1ad0993313bf/src/librustc/lib.rs#L14

https://github.com/rust-lang/rust/blob/063deba92e44809125a433ca6e6c1ad0993313bf/src/librustc/lib.rs#L32

2018-02-23 22:23 UTC, nikomatsakis commented
I found those by doing `rg README.md | grep '.rs'`

2018-02-25 21:30 UTC, mark-i-m commented
@nikomatsakis I think it should be fixed now... I also updated the list in rust-lang-nursery/rustc-guide#2... I think a lot of those will be closed by your latest PR, but it can't hurt to list them...

2018-02-27 17:44 UTC, nikomatsakis commented
@bors r+ rollup

2018-02-28 14:22 UTC, merged