Replace iterator structurese with `impl Trait`.
rust-lang/rust pull request #48699
Opened 2018-03-03 15:26 UTC by frewsxcv

Two commits:

* Replace iterator structures with `impl Trait`.
* Run rustfmt on `src/librustc_data_structures/graph/mod.rs`.

2018-03-03 15:27 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2018-03-06 17:23 UTC, nikomatsakis requested changes
Nice cleanup! Let's go ahead and do the other cases, too!

2018-03-06 17:23 UTC, nikomatsakis commented on src/librustc_data_structures/graph/mod.rs
>      pub fn each_node<'a, F>(&'a self, mut f: F) -> bool
This can use impl trait too -- `mut f: impl FnMut(NodeIndex, &'a Node<N>) -> bool`

2018-03-06 17:23 UTC, nikomatsakis commented on src/librustc_data_structures/graph/mod.rs
>      pub fn each_edge<'a, F>(&'a self, mut f: F) -> bool
same

2018-03-07 01:50 UTC, frewsxcv commented
@nikomatsakis comments have been addressed!

2018-03-07 19:00 UTC, nikomatsakis commented
@frewsxcv 

there are [travis errors here](https://travis-ci.org/rust-lang/rust/builds/350115466#L1860), I think because we need to remove a now unused type parameter (which was migrated to an `impl Trait` usage) -- at least that would be my guess

2018-03-07 19:00 UTC, nikomatsakis submitted a review, later dismissed

2018-03-07 19:00 UTC, nikomatsakis commented on src/librustc_data_structures/graph/mod.rs
> +    pub fn each_node<'a, F>(&'a self, mut f: impl FnMut(NodeIndex, &'a Node<N>) -> bool) -> bool {
F is not used

2018-03-07 19:00 UTC, nikomatsakis commented on src/librustc_data_structures/graph/mod.rs
> +    pub fn each_edge<'a, F>(&'a self, mut f: impl FnMut(EdgeIndex, &'a Edge<E>) -> bool) -> bool {
same

2018-03-09 00:59 UTC, merged