Add crate name to "main function not found" error message.
rust-lang/rust pull request #48706
Opened 2018-03-03 20:31 UTC by ehuss

Fixes #44798 and rust-lang/cargo#4948.

I was wondering if it might be cleaner to update the ui tests to add a simple `fn main() {}` for the unrelated tests.  Let me know if you would prefer that.

2018-03-03 20:31 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @estebank (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2018-03-03 21:28 UTC, estebank commented
In general, yes, I prefer to add an empty `main` instead.

As for the change, I think there'd be value in having the path of the file we're looking for the method in a note as well, but don't know how hard that'd be to add. What do you think @ehuss?

2018-03-03 22:45 UTC, ehuss commented
I'm not entirely certain which situations `local_crate_source_file` is None.  What do you think about something like this:

```diff
--- a/src/librustc/middle/entry.rs
+++ b/src/librustc/middle/entry.rs
@@ -178,6 +178,9 @@ fn configure_main(this: &mut EntryContext, crate_name: &str) {
             err.emit();
             this.session.abort_if_errors();
         } else {
+            if let Some(ref filename) = this.session.local_crate_source_file {
+                err.note(&format!("consider adding a main function to {}", filename.display()));
+            }
             if this.session.teach(&err.get_code().unwrap()) {
                 err.note("If you don't know the basics of Rust, you can go look to the Rust Book \
                           to get started: https://doc.rust-lang.org/book/");
```

which would render as:

```
error[E0601]: main function not found in crate bin_no_main
  |
  = note: consider adding a main function to main-not-found/src/bin/bin_no_main.rs

error: aborting due to previous error

If you want more information on this error, try using "rustc --explain E0601"
```

2018-03-12 10:47 UTC, pietroalbini commented
Ping from triage! Can @estebank or someone from @rust-lang/compiler reply to @ehuss comment?

2018-03-12 18:35 UTC, estebank commented
@ehuss that seems like what I had in mind. Go ahead and add it to the PR. r=me once it's done.

2018-03-13 01:09 UTC, ehuss commented
Thanks @estebank, I have updated it with the new text, updated the tests as discussed, and added a specific test for E0601.

2018-03-13 15:38 UTC, nikomatsakis requested changes

2018-03-13 15:38 UTC, nikomatsakis commented on src/librustc/middle/entry.rs
> +                err.note(&format!("consider adding a main function to {}", filename.display()));
Nit: can this be using backticks? e.g., 

```
`main` function to `{}`
```

2018-03-13 15:38 UTC, nikomatsakis commented on src/librustc/middle/entry.rs
> +            "main function not found in crate {}", crate_name);
Nit: backticks please :)

```
`main` function not found in crate `{}`
```

2018-03-13 15:38 UTC, nikomatsakis commented
@ehuss nice PR =) left a few nits of my own

2018-03-13 20:09 UTC, ehuss commented
Updated, thanks @nikomatsakis!

2018-03-13 20:18 UTC, estebank commented
@bors r+ rollup

2018-03-14 20:07 UTC, estebank commented
@bors r+

2018-03-16 02:46 UTC, merged