Add functionality for gating feature flags on epochs
rust-lang/rust pull request #48801
Opened 2018-03-07 00:18 UTC by Manishearth

fixes #48794

r? @nikomatsakis

2018-03-08 02:17 UTC, nikomatsakis requested changes
Looks nice!

2018-03-08 17:36 UTC, Manishearth commented
Added test.

Oh, also, I'm going to make bare_trait_object and unreachable_pub not be epoch lints -- I'll keep epoch lints to be actual breaking changes like tyvar_rptr and the keywords, and these lints can go ungrouped for now (we can group them later if we wish?)

2018-03-08 23:17 UTC, nikomatsakis approved these changes

2018-03-08 23:17 UTC, nikomatsakis commented on src/test/run-pass/epoch-gate-feature.rs
> +fn foo(x: &dyn Foo) {}
<3

2018-03-08 23:18 UTC, nikomatsakis commented
@bors r+

2018-03-09 01:10 UTC, Manishearth commented
@bors r=nikomatsakis

2018-03-09 06:29 UTC, merged