traits: Implement interning for Goal and Clause
rust-lang/rust pull request #49800
Opened 2018-04-09 07:41 UTC by ishitatsuyuki

r? @nikomatsakis 

Close #49054

This should be mostly good, although I'm not sure with the naming of `Goal::from_poly_domain_goal`.

2018-04-09 07:49 UTC, TimNN commented
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/363995865) ([raw log](https://api.travis-ci.org/v3/job/363995865/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Resolving deltas: 100% (612819/612819), completed with 4858 local objects.
---
[00:00:43] configure: rust.quiet-tests     := True
---
[00:04:37] tidy error: /checkout/src/librustc_traits/lowering.rs:168: line longer than 100 chars
[00:04:38] tidy error: /checkout/src/librustc/traits/mod.rs:293: line longer than 100 chars
---
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
ls: cannot access /home/travis/Library/Logs/DiagnosticReports/: No such file or directory
travis_time:end:197a917b:start=1523260137824011439,finish=1523260137830230222,duration=6218783
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:0b2fe99f
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:cras
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-04-09 18:45 UTC, nikomatsakis commented
@ishitatsuyuki nice! I added a note about this PR to [the WG-traits planning meeting document](https://paper.dropbox.com/doc/WG-Traits-Planning-Meeting-oDfr6ct8xx63HSAOOmIZX#:uid=463067912981955114240329&h2=2018.04.09), btw

2018-04-10 16:17 UTC, nikomatsakis requested changes
Looks great! One change though -- foldable looks not right to me.

2018-04-10 16:17 UTC, nikomatsakis commented on src/librustc/traits/mod.rs
> +#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug)]
Woohoo, copy types FTW 🐻

2018-04-10 16:17 UTC, nikomatsakis commented on src/librustc/traits/mod.rs
> +    pub hypotheses: &'tcx Slice<Goal<'tcx>>,
Maybe worth a type alias? `Goals<'tcx>`? Or, maybe not. Meh.

2018-04-10 16:17 UTC, nikomatsakis commented on src/librustc/traits/structural_impls.rs
> +        false
Wait. *This* doesn't look right.  I expect something more like the impl for `Slice`. That is, `super_fold_with` should do something like:

```rust
 fn super_fold_with<'gcx: 'tcx, F: TypeFolder<'gcx, 'tcx>>(&self, _folder: &mut F) -> Self {
    let goal: Goal<'tcx> = (*self).fold_with(folder);
    self.tcx().mk_goal(goal)
}
```

and `visit_with`:

```rust
fn super_visit_with(...) {
    (*self).visit_with(visitor)
}
```

2018-04-10 16:17 UTC, nikomatsakis commented on src/librustc/traits/structural_impls.rs
> +}
Do we want an impl for `&'tcx Clause<'tcx>`? Probably, though maybe we don't need it *yet*.

2018-04-10 16:17 UTC, nikomatsakis commented on src/librustc/traits/structural_impls.rs
> +        folder.tcx().intern_clauses(&v)
At some point we should think about making a macro for these "intern-wrapping impls"... but not, I suppose, in this PR.

2018-04-10 16:17 UTC, nikomatsakis commented on src/librustc/ty/context.rs
> +        &self.mk_goals(iter::once(goal))[0]
this *is* clever...

2018-04-12 13:50 UTC, nikomatsakis approved these changes

2018-04-12 13:51 UTC, nikomatsakis commented
@bors r+

2018-04-13 12:35 UTC, kennytm commented
@bors p=9

2018-04-13 15:54 UTC, merged