Add limit of 255 hashes for raw string literal escapes
rust-lang/rust pull request #50296
Opened 2018-04-28 06:06 UTC by cmdd

Fixes #50111.

2018-04-28 07:52 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-3.9` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/372334377) ([raw log](https://api.travis-ci.org/v3/job/372334377/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:44:53] ....................................................................................................
[00:44:59] ....................................................................................................
[00:45:05] ....................................................................................................
[00:45:12] ..................................i.................................................................
[00:45:17] ..........i.........................................F...............................................
[00:45:30] ....................................................................................................
##############################################################################################################################################################################################################################
[00:45:35] 5    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[00:45:35] 
[00:45:35] 
[00:45:35] 
[00:45:35] The actual stderr differed from the expected stderr.
[00:45:35] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/raw_string_hash_count.stderr
[00:45:35] To update references, run this command from build directory:
[00:45:35] /checkout/src/test/ui/update-references.sh '/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui' 'raw_string_hash_count.rs'
[00:45:35] error: 1 errors occurred comparing output.
[00:45:35] status: exit code: 101
[00:45:35] status: exit code: 101
[00:45:35] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/raw_string_hash_count.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/raw_string_hash_count.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/raw_string_hash_count.stage2-x86_64-unkn#################################################\"test\"################################################################################################################################################################################################################################################################\n   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n"}
[00:45:35] {"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to previous error\n\n"}
[00:45:35] ------------------------------------------
[00:45:35] 
[00:45:35] thread '[ui] ui/raw_string_hash_count.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:2965:9
[00:45:35] note: Run with `RUST_BACKTRACE=1` for a backtrace.
---
[00:45:35] 
[00:45:35] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:488:22
[00:45:35] 
[00:45:35] 
[00:45:35] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/./obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/incremental
111308 ./obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release
107424 ./obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps
102820 ./obj/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends
102808 ./obj/build/bootstrap/debug/incremental/bootstrap-2wettvttcntnm
102808 ./obj/build/bootstrap/debug/incremental/bootstrap-2wettvttcntnm
102804 ./obj/build/bootstrap/debug/incremental/bootstrap-2wettvttcntnm/s-f0j68ebhzh-17j24r9-v7hez0f2m5v0
90648 ./obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/incremental/core-31lccp6wy7orz
90648 ./obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/incremental/core-31lccp6wy7orz
90644 ./obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/incremental/core-31lccp6wy7orz/s-f0j65upgpu-17ogum3-8jol7z8wxzfn
89732 ./obj/build/x86_64-unknown-linux-gnu/stage1/lib
89684 ./src/llvm/test/CodeGen
86660 ./obj/build/x86_64-unknown-linux-gnu/doc/core
84396 ./obj/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-04-28 10:09 UTC, varkor requested changes
It's looking good to me! I just left a few very minor comments.

The test is currently failing because the offset in the line/column number is wrong (after you added the line to ignore tidy), but once you tweak the range/text you can just regenerate it.

2018-04-28 10:09 UTC, varkor commented on src/test/ui/raw_string_hash_count.rs
> +    let x = r##########################################################################################################################################################################################
For simplicity, you can eliminate the variable as well, and just have the raw string as a standalone statement.

2018-04-28 10:09 UTC, varkor commented on src/libsyntax/parse/lexer/mod.rs
> +                                    "too many `#` characters surrounding a raw string; \
Maybe clarify to "raw byte string". It's probably fine to only test one of them, though, as it's a minor error. Also, the indentation here is off.

2018-04-28 10:09 UTC, varkor commented on src/libsyntax/parse/lexer/mod.rs
> +                                         "too many `#` characters surrounding a raw string; \
The wording could be a little more concise here. Maybe:
```
too many `#` symbols: raw strings may be delimited by up to 255 `#` symbols
```
(and same for byte strings).

2018-04-29 07:49 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-3.9` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/372611540) ([raw log](https://api.travis-ci.org/v3/job/372611540/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:46:25] ....................................................................................................
[00:46:31] ....................................................................................................
[00:46:37] ....................................................................................................
[00:46:44] ...................................i................................................................
[00:46:49] ...........i..........................................F.............................................
[00:47:02] ....................................................................................................
[00:47:08] .........i....................................................................
[00:47:08] failures:
[00:47:08] 
[00:47:08] 
[00:47:08] ---- [ui] ui/raw_string_hash_count.rs stdout ----
[00:47:08]  diff of stderr:
[00:47:08] 
[00:47:08] 1 error: too many `#` symbols: raw strings may be delimited by up to 255 `#` symbols
[00:47:08] +   --> $DIR/raw_string_hash_count.rs:14:5
[00:47:08] 3    |
[00:47:08] 3    |
[00:47:08] 4 LL |     r################################################################################################################################################################################################################################################################"test"###############################################
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-04-29 21:34 UTC, varkor commented on src/test/ui/raw_string_hash_count.stderr
> +  --> src/test/ui/raw_string_hash_count.rs:14:5
You need to replace `src/test/ui` with `$DIR`.

2018-04-30 07:03 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-3.9` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/372897115) ([raw log](https://api.travis-ci.org/v3/job/372897115/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:44:42] ....................................................................................................
[00:44:49] ....................................................................................................
[00:44:55] ....................................................................................................
[00:45:03] ....................................i...............................................................
[00:45:09] ............i.........................................F.............................................
[00:45:23] ....................................................................................................
[00:45:30] ...........i....................................................................
[00:45:30] failures:
[00:45:30] 
[00:45:30] 
[00:45:30] ---- [ui] ui/raw_string_hash_count.rs stdout ----
[00:45:30]  
[00:45:30] error: /checkout/src/test/ui/raw_string_hash_count.rs:14: unexpected error: '14:5: 14:262: too many `#` symbols: raw strings may be delimited by up to 255 `#` symbols'
[00:45:30] 
[00:45:30] error: /checkout/src/test/ui/raw_string_hash_count.rs:14: expected error not found: too many `#` characters
[00:45:30] 
[00:45:30] error: 1 unexpected errors found, 1 expected errors not found
[00:45:30] status: exit code: 101
[00:45:30] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/raw_string_hash_count.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/raw_string_hash_count.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/raw_string_hash_count.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[00:45:30] unexpected errors (from JSON output): [
[00:45:30]     Error {
[00:45:30]         line_num: 14,
[00:45:30]         kind: Some(
[00:45:30]             Error
[00:45:30]         ),
[00:45:30]         msg: "14:5: 14:262: too many `#` symbols: raw strings may be delimited by up to 255 `#` symbols"
[00:45:30] ]
[00:45:30] 
[00:45:30] not found errors (from test file): [
[00:45:30]     Error {
[00:45:30]     Error {
[00:45:30]         line_num: 14,
[00:45:30]         kind: Some(
[00:45:30]             Error
[00:45:30]         ),
[00:45:30]         msg: "too many `#` characters"
[00:45:30] ]
[00:45:30] 
[00:45:30] thread '[ui] ui/raw_string_hash_count.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:1278:13
[00:45:30] note: Run with `RUST_BACKTRACE=1` for a backtrace.
---
[00:45:30] 
[00:45:30] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:488:22
[00:45:30] 
[00:45:30] 
[00:45:30] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[00:45:30] 
[00:45:30] 
[00:45:30] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[00:45:30] Build completed unsuccessfully in 0:02:45
[00:45:30] Build completed unsuccessfully in 0:02:45
[00:45:30] Makefile:58: recipe for target 'check' failed
[00:45:30] make: *** [check] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:044c0ffa
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-04-30 09:37 UTC, varkor commented on src/test/ui/raw_string_hash_count.rs
> +    //~^ ERROR too many `#` characters
This needs to be updated to use `symbols` instead of `characters`.

2018-04-30 13:41 UTC, nagisa commented
Probably for better diagnostics? We either introduce some limit or make the number of hashes technically unlimited by counting them into u64 or larger.

2018-04-30 17:12 UTC, nikomatsakis commented
I feel ok about going to `u8` for now. [Searching through crates.io with a simple regex, it seems pretty clear that this will not break anything.][s]

[s]: https://sourcegraph.com/search?q=repogroup:crates+max:200+%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23%5C%23

2018-04-30 17:15 UTC, eddyb commented
@nikomatsakis I don't thinks this helps anything. @nnethercote changed it to `u16` for a size win, but going to `u8` doesn't reduce that size any further.

2018-05-01 03:40 UTC, estebank commented
@cmdd could you squash your commits?

2018-05-01 06:45 UTC, eddyb commented
I'm nominating this PR for discussion, on the topic of what limits can an implementation reasonably have (rustc currently uses `u32` in a bunch of places where `usize` would be impossible to overflow).

2018-05-10 19:33 UTC, joshtriplett commented
We discussed this in the lang team meeting, and we all agreed that we can safely limit this to 255 without concern.

2018-05-11 14:00 UTC, nikomatsakis commented
I wasn't at the meeting. But I think @eddyb feels like in general `u8` is a rather small limit just *on principle*. I agree that it sounds like something you would expect in the 1970s, though I also agree that it ought be enough. =) If it brings no impl benefit over `u16`, let's just do that and call it a day.

2018-05-11 18:33 UTC, kennytm commented
I do not want a 128 KB test case if `u16` is chosen  😄

2018-05-11 21:16 UTC, nnethercote commented
I suggest 255. It's more than anyone will need in practice, but it's also small enough to test reasonably.

2018-05-21 11:04 UTC, pietroalbini commented
Ping from triage @eddyb! Can we reach a consensus here?

2018-05-21 11:26 UTC, eddyb commented
We don't test other limits (other than the ones imposed by LLVM), why should this be an exception?

2018-05-25 17:59 UTC, kennytm commented
Ping again from not-a-triage @eddyb (reviewer) @cmdd (author) @rust-lang/lang (team), this PR is stuck. Does everybody agree with eddyb's [comment](https://github.com/rust-lang/rust/pull/50296#issuecomment-388528799) above? That is,

* We keep the type to be `u16` (almost reverts everything in this PR)
* Still add the check when the number of `#` reaches 65535 (similar to the implementation in this PR: https://github.com/rust-lang/rust/pull/50296/files#diff-d06ad31c547d2d94c8b8770006977767)
* *Do not* add any test cases

(Nominating again, feel free to untag and change to `S-waiting-on-author` when a decision is made.)

2018-05-25 19:07 UTC, varkor commented
@kennytm: I think @eddyb was pushing not to handle this at all, in which case the PR should just be closed.

@cmdd: I'd be happy to mentor a less contentious issue if that's the case. Most of the [E-needstest](https://github.com/rust-lang/rust/labels/E-needstest) issues should be straightforward, as you just need to add a new test confirming that the original issue no longer occurs. Feel free to mention me on any if you'd like guidance.

2018-05-28 07:02 UTC, cmdd commented
I think it makes sense to have an error message which covers the "too many hashes" case even if the number of hashes is defined as a u16, since it doesn't impede any behavior but provides a useful diagnostic for an (admittedly extreme) edge-case. If the final decision is to close the PR & the issue as "won't fix," please let me know; otherwise, I'll hopefully get this implemented soon and discussion can continue from there.

@varkor: Thanks for the mentoring help! Hopefully adding a test case won't result in such controversy :)

2018-05-31 06:16 UTC, cmdd commented
I've kerjiggled with my branch so that the only change this PR makes is adding an error message when using 2^16 or more hashes to delimit a raw (byte) string. Hopefully this change is agreeable for everyone!

2018-05-31 07:01 UTC, eddyb commented
r? @nikomatsakis

2018-06-04 10:51 UTC, pietroalbini commented
Ping from triage @nikomatsakis! This PR needs your review.

2018-06-05 17:26 UTC, nikomatsakis requested changes
Can we get a test ?

2018-06-05 17:27 UTC, nikomatsakis commented
@cmdd I imagine adding a test into the `src/test/parse-fail` directory would make sense. You can read more about tests [in the rustc-guide](https://rust-lang-nursery.github.io/rustc-guide/tests/intro.html)

2018-06-05 17:34 UTC, kennytm commented
@nikomatsakis But https://github.com/rust-lang/rust/pull/50296#issuecomment-388528799 doesn't want any tests 😕

2018-06-06 20:51 UTC, nikomatsakis commented
I realize that -- I guess the thought is that 128k is a lot? didn't strike me as a lot. but fine, if @eddyb doesn't want tests, it's on their head. 😛 

@bors r+

2018-06-08 15:01 UTC, nikomatsakis approved these changes

2018-06-08 15:02 UTC, nikomatsakis commented
@cmdd merge conflict :(

2018-06-08 16:10 UTC, pietroalbini commented
@cmdd you should rebase on master, even if you don't see any conflict at first glance.

2018-06-08 22:42 UTC, cmdd commented
Sorry for the delay! I've rebased onto master.

2018-06-15 13:50 UTC, nikomatsakis commented
@bors r+

2018-06-15 15:02 UTC, pietroalbini commented
@bors retry #51565

2018-06-15 21:13 UTC, merged