Remove vestigial diverging !-coercion
rust-lang/rust pull request #50351
Opened 2018-04-30 21:44 UTC by varkor

Such conversions are no longer permitted. Fixes #50350.

r? @nikomatsakis

2018-04-30 22:43 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-3.9` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/373240847) ([raw log](https://api.travis-ci.org/v3/job/373240847/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:52:31] running 2310 tests
[00:52:37] ....................................................................................................
[00:52:43] ....................................................................................................
[00:52:49] ....................................................................................................
[00:52:56] ............................................F.......................................................
[00:53:09] ....................................................................................................
[00:53:16] .........i..............................i...........................................................
[00:53:22] ....................................................................................................
[00:53:28] ...........i........................................................................................
---
[00:55:28] 
[00:55:28] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:488:22
[00:55:28] 
[00:55:28] 
[00:55:28] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/compile-fail" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "compile-fail" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[00:55:28] 
[00:55:28] 
[00:55:28] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[00:55:28] Build completed unsuccessfully in 0:16:13
[00:55:28] Build completed unsuccessfully in 0:16:13
[00:55:28] make: *** [check] Error 1
[00:55:28] Makefile:58: recipe for target 'check' failed

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:25f526e0
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-04-30 23:25 UTC, varkor commented
r? @nikomatsakis

2018-05-01 16:26 UTC, nikomatsakis requested changes
One nit.

2018-05-01 16:26 UTC, nikomatsakis commented on src/librustc_typeck/check/_match.rs
> +                coercion.coerce(self, &cause, &arm.body, arm_ty);
👍 -- the fact that this parameter was still needed should have been a warning sign. sigh.

2018-05-01 16:26 UTC, nikomatsakis commented on src/test/compile-fail/coerce-to-bang.rs
> +    // Accepted: return is coerced to `!` just fine, but `22` cannot be.
Nit: This is no longer "accepted"

2018-05-01 16:27 UTC, nikomatsakis approved these changes

2018-05-01 16:28 UTC, nikomatsakis commented
@bors try

2018-05-01 16:36 UTC, nikomatsakis commented
cc @rust-lang/infra -- this could use a "check-only" crater run.

2018-05-05 12:25 UTC, aidanhs commented
Crater run started

2018-05-11 20:08 UTC, kennytm commented
We're still uploading to http://cargobomb-reports.s3.amazonaws.com/pr-50351/index.html, but there's only a single regression with `yamlette-0.0.4` (not sure if legit or spurious yet).

2018-05-12 18:06 UTC, aidanhs commented
Upload complete at http://cargobomb-reports.s3.amazonaws.com/pr-50351/index.html

(sorry for the delay, uploading hit a bug in crater that I had to debug and fix)

2018-05-13 13:35 UTC, aidanhs commented
Reuploaded, the report generation was buggy too (so both logs were identical). Regarding the timeout - seems like normal variance, looking at the two logs it appears the one that passed squeaked by with just a few seconds under 300.

2018-05-14 16:43 UTC, nikomatsakis commented
@bors r+

2018-05-15 13:14 UTC, merged