Misc changes related to Miri allocations
rust-lang/rust pull request #50520
Opened 2018-05-07 21:45 UTC by Zoxc

This builds on top of https://github.com/rust-lang/rust/pull/50249

r? @oli-obk

2018-05-07 22:10 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-3.9` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/376103077) ([raw log](https://api.travis-ci.org/v3/job/376103077/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:21:03]    Compiling rustc_lsan v0.0.0 (file:///checkout/src/librustc_lsan)
[00:21:03]    Compiling rustc_asan v0.0.0 (file:///checkout/src/librustc_asan)
[00:21:04]    Compiling rustc_msan v0.0.0 (file:///checkout/src/librustc_msan)
[00:21:04]    Compiling rustc_tsan v0.0.0 (file:///checkout/src/librustc_tsan)
[00:21:44] thread 'main' panicked at 'already borrowed: BorrowMutError', libcore/result.rs:945:5
[00:21:44] 
[00:21:44] error: internal compiler error: unexpected panic
[00:21:44] 
[00:21:44] 
[00:21:44] note: the compiler unexpectedly panicked. this is a bug.
[00:21:44] 
[00:21:44] note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
[00:21:44] note: rustc 1.27.0-dev running on x86_64-unknown-linux-gnu
[00:21:44] 
[00:21:44] 
[00:21:44] note: compiler flags: -Z force-unstable-if-unmarked -C opt-level=3 -C prefer-dynamic -C debug-assertions=y -C link-args=-Wl,-rpath,$ORIGIN/../lib --crate-type lib
[00:21:44] 
[00:21:44] note: some of the compiler flags provided by cargo are hidden
[00:21:44] error: Could not compile `core`.
[00:21:44] 
[00:21:44] Caused by:
[00:21:44]   process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc --crate-name core libcore/lib.rs --color always --error-format json --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=07c899b6c3d44697 -C extra-filename=-07c899b6c3d44697 --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/release/deps` (exit code: 101)
[00:21:44]   process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc --crate-name core libcore/lib.rs --color always --error-format json --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=07c899b6c3d44697 -C extra-filename=-07c899b6c3d44697 --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-std/release/deps` (exit code: 101)
[00:21:44] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "--message-format" "json"
[00:21:44] expected success, got: exit code: 101
[00:21:44] thread 'main' panicked at 'cargo must succeed', bootstrap/compile.rs:1091:9
[00:21:44] travis_fold:end:stage1-std

[00:21:44] travis_time:end:stage1-std:start=1525730947458649905,finish=1525731000868459000,duration=53409809095


[00:21:44] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap build
[00:21:44] Build completed unsuccessfully in 0:16:56
[00:21:44] make: *** [all] Error 1
[00:21:44] Makefile:28: recipe for target 'all' failed

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:03a7d0d4
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-05-08 16:02 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-3.9` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/376402870) ([raw log](https://api.travis-ci.org/v3/job/376402870/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[01:01:52] ..........i..............................i..........................................................
[01:01:59] ....................................................................................................
[01:02:05] ............i.......................................................................................
[01:02:13] ....................................................................................................
[01:02:22] .....................................................F..............................................
[01:02:41] ....................................................................................................
[01:02:53] ....................................................................................................
[01:03:02] .....i..............................................................................................
[01:03:10] ....i..ii...........................................................................................
---
[01:04:14] 
[01:04:14] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:492:22
[01:04:14] 
[01:04:14] 
[01:04:14] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/compile-fail" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "compile-fail" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "3.9.1\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[01:04:14] 
[01:04:14] 
[01:04:14] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:04:14] Build complet
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-05-21 11:11 UTC, pietroalbini commented
Ping from triage @oli-obk! This PR needs your review.
@Zoxc there are some merge conflicts.

2018-05-21 15:20 UTC, oli-obk requested changes
As discussed on IRC I am very unsure about the last commit. We had a scheme like that when miri was merged, and we kept running into various edge cases with the decoding order. Even creating MCVEs for the panics we were getting was hard, because small changes in the code would change the order of evaluation.

cc @michaelwoerister

2018-05-21 23:08 UTC, Zoxc commented on src/librustc/ich/impls_ty.rs
> +impl<'a, 'gcx, M: HashStable<StableHashingContext<'a>>> HashStable<StableHashingContext<'a>>
I don't think we have a macro which works for enums with lifetimes.

2018-05-22 02:19 UTC, Zoxc commented
I've split the last commit into a separate PR.

2018-05-22 05:35 UTC, oli-obk commented on src/bootstrap/lib.rs
> -            if !self.config.ninja && self.config.build.contains("msvc") {
Please put this in a separate PR, I have no idea what this does or why it's here

2018-05-22 05:36 UTC, oli-obk approved these changes

2018-05-22 08:45 UTC, oli-obk commented
@bors r+

2018-05-22 12:57 UTC, merged

2018-05-31 19:44 UTC, alexcrichton commented
FWIW this hurt the max-rss usage on a [few benchmarks](https://perf.rust-lang.org/compare.html?start=1bbae5f38677e823ba6e23f1e0e105ceee4c6f8a&end=ff8fa5cc69db5567b32ceca1ee4ac0dcfa3a81bc&stat=max-rss) (but not by huge amounts)