Add Option::xor method
rust-lang/rust pull request #50553
Opened 2018-05-09 01:30 UTC by clarcharr

Implements the method requested in #50512.

2018-05-09 01:30 UTC, rust-highfive commented
r? @sfackler

(rust_highfive has picked a reviewer for you, use r? to override)

2018-05-09 02:46 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-3.9` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/376637660) ([raw log](https://api.travis-ci.org/v3/job/376637660/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[01:13:15] 
[01:13:15] error: test failed, to rerun pass '--doc'
[01:13:15] 
[01:13:15] 
[01:13:15] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "-p" "core" "--" "--quiet"
[01:13:15] 
[01:13:15] 
[01:13:15] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:13:15] Build completed unsuccessfully in 0:32:19
[01:13:15] Build completed unsuccessfully in 0:32:19
[01:13:15] Makefile:58: recipe for target 'check' failed
[01:13:15] make: *** [check] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:2a402f21
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-05-09 03:01 UTC, ishitatsuyuki commented
Please go over the RFC process before implementing a new library function.

2018-05-09 03:13 UTC, Mark-Simulacrum commented
The RFC process is not generally necessary for adding unstable library features; approval from the libs team is sufficient.

2018-05-09 06:33 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-3.9` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/376679014) ([raw log](https://api.travis-ci.org/v3/job/376679014/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[01:18:51] ....................................................................................................
[01:19:10] ..........................i.................................................................
[01:19:10] failures:
[01:19:10] 
[01:19:10] ---- option.rs - option::Option<T>::xor (line 715) stdout ----
[01:19:10]  thread 'option.rs - option::Option<T>::xor (line 715)' panicked at 'test executable failed:
[01:19:10] thread 'main' panicked at 'assertion failed: `(left == right)`
[01:19:10] thread 'main' panicked at 'assertion failed: `(left == right)`
[01:19:10]   left: `Some(2)`,
[01:19:10]  right: `None`', option.rs:12:1
[01:19:10] 
[01:19:10] ', librustdoc/test.rs:356:17
[01:19:10] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:19:10] 
---
[01:19:10] 
[01:19:10] error: test failed, to rerun pass '--doc'
[01:19:10] 
[01:19:10] 
[01:19:10] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "-p" "core" "--" "--quiet"
[01:19:10] 
[01:19:10] 
[01:19:10] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:19:10] Build completed unsuccessfully in 0:34:32
[01:19:10] Build completed unsuccessfully in 0:34:32
[01:19:10] Makefile:58: recipe for target 'check' failed
[01:19:10] make: *** [check] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:00a83011
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
Wed May  9 06:33:51 UTC 2018
0 ./obj/build/bootstrap/debug/incremental/bootstrap-1wl4zjaz72e5d/s-f0v6lhbkmm-7mne91-3a8ftmql7i7fg
113068 ./obj/build/x86_64-unknown-linux-gnu/test/mir-opt
112640 ./obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu
112636 ./obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release
108644 ./obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps
108644 ./obj/build/x86_64-unknown-linux-gnu/stage0-tools/x86_64-unknown-linux-gnu/release/deps
103488 ./obj/build/bootstrap/debug/incremental/bootstrap-2wettvttcntnm
103484 ./obj/build/bootstrap/debug/incremental/bootstrap-2wettvttcntnm/s-f0v7s1ubrs-9bdn3m-2ysq90q36kyjn
98488 ./obj/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/incremental
93316 ./obj/build/x86_64-unknown-linux-gnu/stage1
93292 ./obj/build/x86_64-unknown-linux-gnu/stage1/lib
90808 ./obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/incremental/core-31lccp6wy7orz
90808 ./obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/incremental/core-31lccp6wy7orz
90804 ./obj/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/incremental/core-31lccp6wy7orz/s-f0v7ppoiyy-rt72ks-dwv0lu6ptg5j
86672 ./obj/build/x86_64-unknown-linux-gnu/doc/core
81220 ./obj/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release/deps
80928 ./obj/build/x86_64-unknown-linux-gnu/doc/std
79032 ./obj/build/x86_64-unknown-linux-gnu/stage0-sysroot
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-05-11 15:00 UTC, andre-vm requested changes

2018-05-15 16:48 UTC, clarcharr commented on src/libcore/option.rs
> +    /// assert_eq!(x.xor(y), None);
Oops, fixed.

2018-05-17 02:17 UTC, sfackler commented
Seems plausible for me.

cc @rust-lang/libs 

@bors r+

2018-05-18 05:23 UTC, merged