typeck: Fix ICE with struct update syntax
rust-lang/rust pull request #50643
Opened 2018-05-11 04:19 UTC by dlrobertson

If check_expr_struct_fields fails, do not continue to record update.
If we continue to record update, the struct may cause us to ICE later
on indexing a field that may or may not exist.

Fixes: #50618

2018-05-11 05:27 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-3.9` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/377572207) ([raw log](https://api.travis-ci.org/v3/job/377572207/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Check compiletest suite=compile-fail mode=compile-fail (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:00:21] 
[01:00:21] running 2311 tests
[01:00:26] ....................................................................................................
[01:00:32] ................................................................F...................................
[01:00:38] .......................................F..............F.............................................
[01:00:51] ....................i............................................................ii.iii.............
[01:00:58] ....................................................................................................
[01:01:05] ..........i..............................i..........................................................
[01:01:11] ....................................................................................................
---
[01:03:20] failures:
[01:03:20] 
[01:03:20] ---- [compile-fail] compile-fail/borrowck/borrowck-field-sensitivity.rs stdout ----
[01:03:20]  
[01:03:20] error: /checkout/src/test/compile-fail/borrowck/borrowck-field-sensitivity.rs:24: expected error not found: use of moved value: `*x.b`
[01:03:20] 
[01:03:20] error: /checkout/src/test/compile-fail/borrowck/borrowck-field-sensitivity.rs:37: expected error not found: use of moved value: `x.b`
[01:03:20] 
[01:03:20] error: /checkout/src/test/compile-fail/borrowck/borrowck-field-sensitivity.rs:51: expected error not found: cannot move out of `x.b` because it is borrowed
[01:03:20] 
[01:03:20] error: /checkout/src/test/compile-fail/borrowck/borrowck-field-sensitivity.rs:72: expected error not found: use of moved value: `x.b`
[01:03:20] 
[01:03:20] error: /checkout/src/test/compile-fail/borrowck/borrowck-field-sensitivity.rs:78: expected error not found: use of moved value: `x.b`
[01:03:20] 
[01:03:20] error: /checkout/src/test/compile-fail/borrowck/borrowck-field-sensitivity.rs:84: expected error not found: use of moved value: `x.b`
[01:03:20] 
[01:03:20] error: 0 unexpected errors found, 6 expected errors not found
[01:03:20] status: exit code: 101
[01:03:20] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/borrowck/borrowck-field-sensitivity.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--error-forma "use of moved value: `x.b`"
[01:03:20]     Error {
[01:03:20]         line_num: 84,
[01:03:20]         kind: Some(
[01:03:20]             Error
[01:03:20]             Error
[01:03:20]         ),
[01:03:20]         msg: "use of moved value: `x.b`"
[01:03:20] ]
[01:03:20] 
[01:03:20] thread '[compile-fail] compile-fail/borrowck/borrowck-field-sensitivity.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:1312:13
[01:03:20] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:03:20] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:03:20] 
[01:03:20] ---- [compile-fail] compile-fail/borrowck/borrowck-struct-update-with-dtor.rs stdout ----
[01:03:20]  
[01:03:20] error in revision `ast`: /checkout/src/test/compile-fail/borrowck/borrowck-struct-update-with-dtor.rs:31: expected error not found: cannot move out of type `T`, which implements the `Drop` trait
[01:03:20] 
[01:03:20] error in revision `ast`: 0 unexpected errors found, 1 expected errors not found
[01:03:20] status: exit code: 101
[01:03:20] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/borrowck/borrowck-struct-update-with-dtor.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--cfg" "ast" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/borrowck/borrowck-struct-update-with-dtor.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/borrowck/borrowck-struct-update-with-dtor.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[01:03:20] not found errors (from test file): [
[01:03:20]     Error {
[01:03:20]         line_num: 31,
[01:03:20]         kind: Some(
[01:03:20]         ),
[01:03:20]         ),
[01:03:20]         msg: "cannot move out of type `T`, which implements the `Drop` trait"
[01:03:20] ]
[01:03:20] 
[01:03:20] thread '[compile-fail] compile-fail/borrowck/borrowck-struct-update-with-dtor.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:1312:13
[01:03:20] 
[01:03:20] 
[01:03:20] ---- [compile-fail] compile-fail/borrowck/borrowck-use-mut-borrow.rs stdout ----
[01:03:20]  
[01:03:20] error: /checkout/src/test/compile-fail/borrowck/borrowck-use-mut-borrow.rs:49: expected error not found: cannot use `x.a` because it was mutably borrowed
[01:03:20] 
[01:03:20] error: /checkout/src/test/compile-fail/borrowck/borrowck-use-mut-borrow.rs:57: expected error not found: cannot use `x.a` because it was mutably borrowed
[01:03:20] 
[01:03:20] error: 0 unexpected errors found, 2 expected errors not found
[01:03:20] status: exit code: 101
[01:03:20] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/compile-fail/borrowck/borrowck-use-mut-borrow.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/borrowck/borrowck-use-mut-borrow.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail/borrowck/borrowck-use-mut-borrow.stage2-x86_64-unknown-linux-gnu.aux" "-A" "unused"
[01:03:20] not found errors (from test file): [
[01:03:20]     Error {
[01:03:20]         line_num: 49,
[01:03:20]         kind: Some(
[01:03:20]         ),
[01:03:20]         ),
[01:03:20]         msg: "cannot use `x.a` because it was mutably borrowed"
[01:03:20]     Error {
[01:03:20]         line_num: 57,
[01:03:20]         kind: Some(
[01:03:20]             Error
[01:03:20]             Error
[01:03:20]         ),
[01:03:20]         msg: "cannot use `x.a` because it was mutably borrowed"
[01:03:20] ]
[01:03:20] 
[01:03:20] thread '[compile-fail] compile-fail/borrowck/borrowck-use-mut-borrow.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:1312:13
[01:03:20] 
---
[01:03:20] test result: FAILED. 2293 passed; 3 failed; 15 ignored; 0 measured; 0 filtered out
[01:03:20] 
[01:03:20] 
[01:03:20] 
[01:03:20] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/compile-fail" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/compile-fail" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "compile-fail" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-3.9/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zunstable-options " "--target-rustcflags" "-Crpath  [...]

2018-05-11 09:11 UTC, pietroalbini commented
Nominating for beta, this fixes a regression.

2018-05-11 09:18 UTC, oli-obk requested changes
Please add the test case from the issue as a `ui` test with a `// compile-pass` comment to ensure that we don't regress this in the future

2018-05-12 02:15 UTC, dlrobertson commented
@oli-obk I should have commented on the PR as well. I posted on the issue that after looking at this again, I'm not sure that this is the correct approach. I think the real problem is [here](https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/check/mod.rs#L3483-L3495). Which is the reason why the example only hits the ICE if struct update syntax is used. I think a better fix would be to only use the `base_expr` if `check_expr_struct_fields` doesn't hit an error.

> Please add the test case from the issue as a ui test with a // compile-pass comment to ensure that we don't regress this in the future

Will do.

2018-05-12 02:16 UTC, dlrobertson commented
I have a working example of this that doesn't hit the ICE. I'm just running some tests to make sure I didn't break anything else :smile:

2018-05-12 02:58 UTC, dlrobertson commented
Updated to fix the problem in `typeck` and added a test

2018-05-12 08:13 UTC, oli-obk approved these changes

2018-05-12 08:14 UTC, oli-obk commented
Nice! The new fix is much cleaner, I agree

@bors r+

2018-05-13 08:16 UTC, kennytm commented
@bors p=3

2018-05-13 11:32 UTC, merged