Make NonNull::dangling a const fn.
rust-lang/rust pull request #50743
Opened 2018-05-14 13:33 UTC by lachlansneff

As far as I can tell, there no reason why `NonNull::dangling` isn't a `const fn`. This pr adds that keyword.

2018-05-14 13:33 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @aidanhs (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2018-05-14 13:40 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-3.9` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/378723630) ([raw log](https://api.travis-ci.org/v3/job/378723630/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:03:19]    Compiling rustc_lsan v0.0.0 (file:///checkout/src/librustc_lsan)
[00:03:19]    Compiling rustc_asan v0.0.0 (file:///checkout/src/librustc_asan)
[00:03:21]    Compiling rustc_msan v0.0.0 (file:///checkout/src/librustc_msan)
[00:03:21]    Compiling rustc_tsan v0.0.0 (file:///checkout/src/librustc_tsan)
[00:03:25] error[E0016]: blocks in constant functions are limited to items and tail expressions
[00:03:25]     --> libcore/ptr.rs:2690:23
[00:03:25]      |
[00:03:25] 2690 |             let ptr = mem::align_of::<T>() as *mut T;
[00:03:25] 
[00:03:26] error: aborting due to previous error
[00:03:26] 
[00:03:26] For more information about this error, try `rustc --explain E0016`.
[00:03:26] For more information about this error, try `rustc --explain E0016`.
[00:03:26] error: Could not compile `core`.
[00:03:26] 
[00:03:26] Caused by:
[00:03:26]   process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc --crate-name core libcore/lib.rs --color always --error-format json --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=fb1e36473ec4786e -C extra-filename=-fb1e36473ec4786e --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/release/deps` (exit code: 101)
[00:03:26] warning: build failed, waiting for other jobs to finish...
[00:03:33] error: build failed
[00:03:33] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "--message-format" "json"
[00:03:33] expected success, got: exit code: 101
[00:03:33] thread 'main' panicked at 'cargo must succeed', bootstrap/compile.rs:1091:9
[00:03:33] travis_fold:end:stage0-std

[00:03:33] travis_time:end:stage0-std:start=1526305113470499331,finish=1526305141511264064,duration=28040764733


[00:03:33] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:03:33] Build completed unsuccessfully in 0:00:29
[00:03:33] make: *** [tidy] Error 1
[00:03:33] Makefile:79: recipe for target 'tidy' failed

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:12069520
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-05-14 16:09 UTC, oli-obk requested changes
Can you also add some tests that show a few use cases in constants?

2018-05-14 16:09 UTC, oli-obk commented on src/libcore/ptr.rs
>              let ptr = mem::align_of::<T>() as *mut T;
locals in const fn don't work yet, you need to make the body a single expression

2018-05-14 16:09 UTC, oli-obk commented on src/libcore/ptr.rs
> +    pub const fn dangling() -> Self {
Please make the constness unstable by adding the `#[rustc_const_unstable]` attribute

2018-05-20 07:06 UTC, kennytm commented
r? @oli-obk

2018-05-28 08:32 UTC, pietroalbini commented
Ping from triage @lachlansneff! The reviewer left some comments, will you have time to address them soon?

2018-06-04 10:23 UTC, closed without merging