Add doc comment to hiding portions of code example
rust-lang/rust pull request #50852
Opened 2018-05-18 04:18 UTC by mandeep

fixes #50816 

Not sure if this is all that's needed, but I think it's a good start. One thing to note is that the code block is a text block where it could possibly be a rust block.

2018-05-18 08:40 UTC, GuillaumeGomez commented on src/doc/rustdoc/src/documentation-tests.md
> +/// println!("Hello, World!");
Why is there a `println!`?

2018-05-18 13:55 UTC, steveklabnik requested changes

2018-05-18 13:55 UTC, steveklabnik commented on src/doc/rustdoc/src/documentation-tests.md
> +/// println!("Hello, World!");
yes, r=me with this line removed :)

2018-05-18 14:57 UTC, mandeep commented
The foo function is there to show how to hide code. I wanted to add the println to show how normal code would look like in addition to hidden code.

2018-05-18 15:02 UTC, GuillaumeGomez commented
Then you definitely need to update the next code example as well. But that seems really strange. Why would you put a doc comment on a hidden function? Doesn't make sense to me...

2018-05-18 15:13 UTC, mandeep commented
The PR attempts to show users that one needs doc comments on all of their example code so that they don't write something like the following:

```rust
/// # Examples
/// Some documentation
# fn foo()
/// println("Hi");
```

2018-05-18 16:05 UTC, steveklabnik commented
@mandeep that makes sense, but I'd prefer the examples to have actual syntax, then. You need curlies, for example.

2018-05-18 16:11 UTC, mandeep commented
@steveklabnik Are curly braces needed somewhere besides the foo function?

2018-05-20 15:11 UTC, mandeep commented
I discussed this on IRC and there may have been confusion with my example in my comment that contains code. I've updated the example to match the commit of the PR.

2018-05-28 08:55 UTC, pietroalbini commented
Ping from triage! What's the status on this?

2018-06-03 17:59 UTC, mandeep commented
@GuillaumeGomez maybe an example will help:

```rust
/// Find the barycentric coordinates of the given point with respect to the given triangle
///
/// # Examples
///
/// ```
/// let points =  vec![Vector3::new(0, 0, 0), Vector3::new(2, 2, 2), Vector3::new(0, 2, 2)]
/// let point = Point3::new(1.0, 1.0, 0.0);
/// let barycentric_coordinates: Point3<f64> = find_barycentric(&points, &point);
/// ```
///
fn find_barycentric(points: &Vec<Point3<f64>>, point: &Point3<f64>) -> Point3<f64> {
    let u = Vector3::new(points[2].x - points[0].x, points[1].x - points[0].x, points[0].x - point.x);
    let v = Vector3::new(points[2].y - points[0].y, points[1].y - points[0].y, points[0].y - point.y);

    let w = u.cross(&v);

    if (w.z).abs() < 1.0 {
        return Point3::new(-1.0, 1.0, 1.0);
    } else {
        return Point3::new(1.0 - (w.x + w.y) as f64 / w.z as f64, w.y as f64 / w.z as f64, w.x as f64 / w.z as f64);
    }

}
```

2018-06-03 22:08 UTC, GuillaumeGomez commented
I still don't get it. :-/

2018-06-05 02:05 UTC, mandeep commented
The use case is not immediately apparent, but since this omission is causing problems I think we need to add this commit. If you think more information is needed, let me know and I'd be happy to add more.

2018-06-05 08:18 UTC, GuillaumeGomez commented
Ok, then let's just move forward.

@bors: r+ rollup

2018-06-05 18:19 UTC, merged

2018-06-06 00:16 UTC, jamesray1 commented
LGTM!

2018-06-06 00:18 UTC, jamesray1 commented on src/doc/rustdoc/src/documentation-tests.md
> +/// println!("Hello, World!");
LGTM!