Revert "Set opt-level to 3"
rust-lang/rust pull request #51165
Opened 2018-05-29 12:52 UTC by SimonSapin

This reverts commit aad9840ad49c56830384e87bc8bd87fd0199dc44.

Level 3 (possibly indirectly, the underlying bug might be in XCode’s linker) causes unit tests to sefault when compiled with some versions of XCode: https://github.com/rust-lang/rust/issues/50867

It also appears to cause some segfaults on Windows: https://github.com/rust-lang/rust/pull/50329#issuecomment-386853473, and regressions in some rustc performance benchmarks: https://github.com/rust-lang/rust/pull/50329#issuecomment-388084894

2018-05-29 12:53 UTC, rust-highfive commented
r? @alexcrichton

(rust_highfive has picked a reviewer for you, use r? to override)

2018-05-29 12:53 UTC, SimonSapin commented
r? @alexcrichton, CC @Zoxc

2018-05-29 12:54 UTC, SimonSapin commented
Unfortunately, adding a test so that #50867 doesn’t regress again is tricky since the Travis-CI config uses newer XCode than versions that are affected according to https://github.com/rust-lang/rust/issues/50867#issuecomment-390435849.

2018-05-29 12:55 UTC, SimonSapin commented
@bors p=1, #50867 blocks upgrading Nightly in Servo.

2018-05-29 14:31 UTC, kennytm requested changes

2018-05-29 15:39 UTC, SimonSapin commented on src/Cargo.toml
> +# But hey if this is removed and it gets past the bots, sounds good to me.
Done.

2018-05-29 15:45 UTC, kennytm approved these changes

2018-05-29 15:57 UTC, alexcrichton commented
@bors: r+

2018-05-29 19:29 UTC, merged

2018-06-04 06:00 UTC, nnethercote commented
This regressed perf significantly, unfortunately:
http://perf.rust-lang.org/compare.html?start=59c0f5913ddc2f66c1ff8ab612f7027e38c85a6d&end=524ad9b9e03656f3fdeb03ed82fe78db3916e566&stat=instructions:u