Store scalar pair bools as i8 in memory
rust-lang/rust pull request #51583
Opened 2018-06-15 23:08 UTC by cuviper

We represent `bool` as `i1` in a `ScalarPair`, unlike other aggregates,
to optimize IR for checked operators and the like.  With this patch, we
still do so when the pair is an immediate value, but we use the `i8`
memory type when the value is loaded or stored as an LLVM aggregate.

So `(bool, bool)` looks like an `{ i1, i1 }` immediate, but `{ i8, i8 }`
in memory.  When a pair is a direct function argument, `PassMode::Pair`,
it is still passed using the immediate `i1` type, but as a return value
it will use the `i8` memory type.  Also, `bool`-like` enum tags will now
use scalar pairs when possible, where they were previously excluded due
to optimization issues.

Fixes #51516.
Closes #51566.

r? @eddyb
cc @nox

2018-06-16 06:37 UTC, eddyb requested changes

2018-06-16 06:37 UTC, eddyb commented on src/librustc_codegen_llvm/mir/place.rs
> +                    assert_eq!(val_ty(llptr), Type::i8p(bx.cx));
You can just remove this check and the comment above it.

2018-06-16 06:37 UTC, eddyb commented on src/librustc_codegen_llvm/type_of.rs
> +        // effectively represented as `{i8, i8}` in memory and `{i1, i1}` as an
The type `{i1, i1}` is never created, so maybe say "two `i1`s" instead?

2018-06-16 06:37 UTC, eddyb commented on src/test/codegen/scalar-pair-bool.rs
> +// CHECK: define { i8, i8 } @pair_and_or(i1 zeroext %arg0.0, i1 zeroext %arg0.1)
Oh, this is another unfortunate consequence, I forgot about return values. I wonder if they should be using the pair "passing mode" that arguments do, and create a LLVM aggregate type on the fly, using the immediate types for the pair components. That way we'd get `{i1, i1}` for returns, but everything else would see `{i8, i8}`.

Not sure it's worth the complexity though. When inlining, LLVM should collapse the zext followed by trunc, just like it gets rid of packing into a pair and unpacking it.

2018-06-16 06:38 UTC, eddyb commented on src/test/codegen/scalar-pair-bool.rs
> +    (a && b, a || b)
Would be cool to see this with branches, since they only ever take `i1`.

2018-07-03 17:10 UTC, TimNN commented
Ping from triage, @cuviper: It looks like there are some comments on your PR, do you think you'll be able to address those?

2018-07-03 17:16 UTC, cuviper commented
Sorry I forgot about this.  Yes, I'll update for those comments.

2018-07-09 11:24 UTC, pietroalbini commented
Ping from triage @eddyb! This PR needs your review.

2018-07-10 01:20 UTC, cuviper commented
OK, filed #52198.  Not sure if I have bors access, but let's try:

@bors r=eddyb

2018-07-10 01:36 UTC, Mark-Simulacrum commented
@bors r+ p=5 (rollup fairness)

2018-07-10 05:15 UTC, merged