NLL: Walk the MIR only once for the "unused mut" lint
rust-lang/rust pull request #51660
Opened 2018-06-20 16:14 UTC by lqd

Turns the quadratic loop gathering local variable assignments into a single MIR walk, and brings down the number of `super_mir` calls generated from `do_mir_borrowck` to the expected levels seen in `nll::replace_regions_in_mir` and `nll::compute_regions`, i.e. on clap: 1883 `super_mir` calls instead of 8011.

The limited perf numbers I could gather on my machines look to be what we expected: `clap-check` seems to be gaining back a lot of the 7% we previously saw in `visit_mir`.

Fixes #51641.

r? @nikomatsakis

2018-06-20 17:00 UTC, Mark-Simulacrum commented
@bors try

2018-06-20 18:00 UTC, nikomatsakis requested changes

2018-06-20 18:00 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/used_muts.rs
> +            PlaceContext::Store | PlaceContext::Call => {
I wonder if we should factor this out to share code with the `find_assignments`

2018-06-20 18:00 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/used_muts.rs
> +            PlaceContext::Store | PlaceContext::Call => {
basically just make a fn that returns a `bool`

2018-06-20 19:07 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/used_muts.rs
> +            PlaceContext::Store | PlaceContext::Call => {
maybe share code with this function?

https://github.com/rust-lang/rust/blob/637fd2e0487281adac99000602f5e74c3bf151a8/src/librustc_mir/util/liveness.rs#L229-L229

2018-06-21 09:12 UTC, kennytm commented
Perf is ready. http://perf.rust-lang.org/compare.html?start=637fd2e0487281adac99000602f5e74c3bf151a8&end=737c5cc95040e9efce65cb13a51a0df0f842cef4&stat=instructions%3Au

2018-06-21 12:37 UTC, nikomatsakis commented
@bors r+

2018-06-22 06:36 UTC, rust-highfive commented
The job `dist-x86_64-freebsd` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/395329591) ([raw log](https://api.travis-ci.org/v3/job/395329591/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
  0     0    0     0    0     0      0      0 --:--:--  0:00:51 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:52 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:53 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:54 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:55 --:--:--     0curl: (6) Could not resolve host: s3-us-west-1.amazonaws.com
[01:06:53] thread 'main' panicked at 'failed to download openssl source: exit code: 6', bootstrap/native.rs:589:17
[01:06:53] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap dist --host x86_64-unknown-freebsd --target x86_64-unknown-freebsd
[01:06:53] Build completed unsuccessfully in 1:03:59
travis_time:end:153cd66e:start=1529645263675370664,finish=1529649277373324761,duration=4013697954097

---
travis_time:end:056c4936:start=1529649277799708439,finish=1529649277805154379,duration=5445940
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0db27cd8
$ head -30 ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
head: cannot open ‘./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers’ for reading: No such file or directory
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:04eedbe2
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-06-22 06:36 UTC, rust-highfive commented
The job `dist-x86_64-freebsd` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/395329591) ([raw log](https://api.travis-ci.org/v3/job/395329591/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
  0     0    0     0    0     0      0      0 --:--:--  0:00:51 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:52 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:53 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:54 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:55 --:--:--     0curl: (6) Could not resolve host: s3-us-west-1.amazonaws.com
[01:06:53] thread 'main' panicked at 'failed to download openssl source: exit code: 6', bootstrap/native.rs:589:17
[01:06:53] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap dist --host x86_64-unknown-freebsd --target x86_64-unknown-freebsd
[01:06:53] Build completed unsuccessfully in 1:03:59
travis_time:end:153cd66e:start=1529645263675370664,finish=1529649277373324761,duration=4013697954097

---
travis_time:end:056c4936:start=1529649277799708439,finish=1529649277805154379,duration=5445940
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0db27cd8
$ head -30 ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
head: cannot open ‘./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers’ for reading: No such file or directory
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:04eedbe2
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-06-22 07:08 UTC, lqd commented
@kennytm the failures look like CI network issues right ?

2018-06-22 08:01 UTC, kennytm commented
@bors retry travis-ci#9696

2018-06-22 10:33 UTC, merged