Many `From` implementations are undocumented #51430
rust-lang/rust pull request #51738
Opened 2018-06-23 17:03 UTC by ormrepo

Hi, @skade This is my first pull request (Please be gentle with me....). I have followed your instructions, there could be a few mistakes. Let me know what they are and I will improve upon them.

2018-06-23 17:03 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @bluss (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2018-06-23 17:09 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-3.9` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/395878338) ([raw log](https://api.travis-ci.org/v3/job/395878338/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:03:28]    Compiling rustc_msan v0.0.0 (file:///checkout/src/librustc_msan)
[00:03:41]    Compiling libc v0.0.0 (file:///checkout/src/rustc/libc_shim)
[00:03:41]    Compiling alloc v0.0.0 (file:///checkout/src/liballoc)
[00:03:41]    Compiling std_unicode v0.0.0 (file:///checkout/src/libstd_unicode)
[00:03:41] error: expected one of `const`, `crate`, `default`, `extern`, `fn`, `pub`, `type`, or `unsafe`, found `}`
[00:03:41]    --> liballoc/boxed.rs:431:1
[00:03:41]     |
[00:03:41] 429 |     /// This conversion is more expensive because the <T> is not already on the heap.
[00:03:41]     |                                                                                      - expected one of 8 possible tokens here
[00:03:41] 431 | }
[00:03:41] 431 | }
[00:03:41]     | ^ unexpected token
[00:03:41] 
[00:03:41] error: expected one of `const`, `crate`, `default`, `extern`, `fn`, `pub`, `type`, or `unsafe`, found `}`
[00:03:41]    --> liballoc/boxed.rs:448:1
[00:03:41]     |
[00:03:41] 446 |     /// and the pointer moves along
[00:03:41]     |                                    - expected one of 8 possible tokens here
[00:03:41] 448 | }
[00:03:41] 448 | }
[00:03:41]     | ^ unexpected token
[00:03:41] 
[00:03:41] error: expected one of `const`, `crate`, `default`, `extern`, `fn`, `pub`, `type`, or `unsafe`, found `}`
[00:03:41]    --> liballoc/boxed.rs:466:1
[00:03:41] 463 |     /// on the heap.
[00:03:41] 463 |     /// on the heap.
[00:03:41]     |                     - expected one of 8 possible tokens here
[00:03:41] 466 | }
[00:03:41] 466 | }
[00:03:41]     | ^ unexpected token
[00:03:41] 
[00:03:41] error: expected one of `const`, `crate`, `default`, `extern`, `fn`, `pub`, `type`, or `unsafe`, found `}`
[00:03:41]    --> liballoc/boxed.rs:482:1
[00:03:41]     |
[00:03:41] 481 |     /// This function is unsafe. Data can't be moved from this reference.
[00:03:41]     |                                                                          - expected one of 8 possible tokens here
[00:03:41] 482 | }
[00:03:41]     | ^ unexpected token
[00:03:41] 
[00:03:41] error: expected one of `const`, `crate`, `default`, `extern`, `fn`, `pub`, `type`, or `unsafe`, found `}`
[00:03:41]    --> liballoc/boxed.rs:904:1
[00:03:41] 903 |     /// heap.
[00:03:41] 903 |     /// heap.
[00:03:41]     |              - expected one of 8 possible tokens here
[00:03:41] 904 | }
[00:03:41]     | ^ unexpected token
[00:03:41] 
[00:03:41] error: expected one of `const`, `crate`, `default`, `extern`, `fn`, `pub`, `type`, or `unsafe`, found `}`
[00:03:41]    --> liballoc/boxed.rs:916:1
[00:03:41] 915 |     /// heap.
[00:03:41] 915 |     /// heap.
[00:03:41]     |              - expected one of 8 possible tokens here
[00:03:41] 916 | }
[00:03:41]     | ^ unexpected token
[00:03:41] 
[00:03:41] error: expected one of `const`, `crate`, `default`, `extern`, `fn`, `pub`, `type`, or `unsafe`, found `}`
[00:03:41]     --> liballoc/boxed.rs:1012:1
[00:03:41]      |
[00:03:41] 1010 |     /// This conversion is cheaper because the PinBox is already on the heap.
[00:03:41]      |                                                                              - expected one of 8 possible tokens here
[00:03:41] 1012 | }
[00:03:41] 1012 | }
[00:03:41]      | ^ unexpected token
[00:03:41] 
[00:03:41] error: expected one of `const`, `crate`, `default`, `extern`, `fn`, `pub`, `type`, or `unsafe`, found `}`
[00:03:41]     --> liballoc/boxed.rs:1024:1
[00:03:41]      |
[00:03:41] 1022 |     /// This conversion is cheaper because the Box is already on the heap.
[00:03:41]      |                                                                           - expected one of 8 possible tokens here
[00:03:41] 1024 | }
[00:03:41] 1024 | }
[00:03:41]      | ^ unexpected token
[00:03:42]    Compiling alloc_system v0.0.0 (file:///checkout/src/liballoc_system)
[00:03:42]    Compiling panic_abort v0.0.0 (file:///checkout/src/libpanic_abort)
[00:03:43] error: aborting due to 8 previous errors
[00:03:43] 
[00:03:43] 
[00:03:43] error: Could not compile `alloc`.
[00:03:43] 
[00:03:43] Caused by:
[00:03:43]   process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc --crate-name alloc liballoc/lib.rs --color always --error-format json --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=d6cd5f8b78fddf12 -C extra-filename=-d6cd5f8b78fddf12 --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/release/deps --extern core=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libcore-e9cdce497aae9e81.rlib --extern compiler_builtins=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libcompiler_builtins-90a13cda2e54742f.rlib -L native=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/build/compiler_builtins-ffd422941bf53e42/out` (exit code: 101)
[00:03:43] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "--message-format" "json"
[00:03:43] expected success, got: exit code: 101
[00:03:43] thread 'main' panicked at 'cargo must succeed', bootstrap/compile.rs:1091:9
[00:03:43] travis_fold:end:stage0-std

[00:03:43] travis_time:end:stage0-std:start=1529773670313722367,finish=1529773700848827912,duration=30535105545


[00:03:43] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:03:43] Build completed unsuccessfully in 0:00:31
[00:03:43] Makefile:79: recipe for target 'tidy' failed
[00:03:43] make: *** [tidy] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:0db9de90
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:00124c06:start=1529773701354458889,finish=1529773701362190494,duration=7731605
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:003dbd86
$ head -30 ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
head: cannot open ‘./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers’ for reading: No such file or directory
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:089aadc4
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-06-23 23:53 UTC, clarcharr commented
I appreciate the effort to document these conversions! I think that right now the way rustdoc works, it's kind of hard to actually see the documentation for these. The docs for `From` are [extremely long](https://doc.rust-lang.org/nightly/std/convert/trait.From.html) and most of the impls are drowned out by the conversions between integers.

I think that adding docs on the impls themselves is a good thing, although maybe it might be better for some of these to put them elsewhere so they're also seen. For example, the impl for `Future` could go in the docs for `Future`, and the docs for converting between `&str` and `Box<str>` could go on `str`'s docs. Some of these end up just calling existing methods and could go alongside the docs for those methods.

Actually figuring out how to make these docs easy to find is a difficult problem, so, I think that modifying what you've got so far is definitely fine for now. Congrats on your first request. :)

2018-06-24 11:08 UTC, skade commented
Hi @clarcharr, I think https://github.com/rust-lang/rust/issues/51430 is the better place for that kind of feedback.

Rustdoc drowning From implementations is an issue but IMHO not in scope for this.

2018-07-09 10:55 UTC, pietroalbini commented
Thanks for this PR @ormrepo! The build is failing, and there are conflicts that needs to be solved. Do you have time to fix those?

2018-07-09 11:49 UTC, ormrepo commented
Hi Pietro,

Sorry to hear about that. I submitted this a few weeks ago and I was hoping
that @skade <https://github.com/skade> would have responded to this by now.
Unfortunately he has disappeared for some unknown reason.

As this was my first PR I was hoping that my mentor @skade
<https://github.com/skade> would have assisted with this he may be away on
holiday or something.

Sorry about this.

Sehinde


On 9 July 2018 at 11:55:40, Pietro Albini (notifications@github.com) wrote:

Thanks for this PR @ormrepo <https://github.com/ormrepo>! The build is
failing, and there are conflicts that needs to be solved. Do you have time
to fix those?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rust-lang/rust/pull/51738#issuecomment-403440016>, or mute
the thread
<https://github.com/notifications/unsubscribe-auth/AF64cERaZfx29CDnkUhhBDuocYehA8g8ks5uEzasgaJpZM4U03Iv>
.

2018-07-09 11:52 UTC, pietroalbini commented
@ormrepo don't worry, I'm just checking in to make sure PRs are not abandoned `:)`

2018-07-17 17:42 UTC, TimNN commented
Ping from triage, @skade! This PR is waiting for your review! Also cc @rust-lang/docs in case @skade is unavailable in the near future.

2018-07-23 11:47 UTC, pietroalbini commented
Ping from triage @skade @rust-lang/docs, this PR needs your review.

2018-07-30 17:12 UTC, pietroalbini commented
Ping from triage! This PR needs a review, can @skade or someone else from @rust-lang/docs review this?

2018-07-31 03:59 UTC, alercah commented
Won't the conversions also show up on the types with the `From` impls, and not only on the trait page?

2018-07-31 05:54 UTC, alercah requested changes

2018-07-31 13:16 UTC, steveklabnik commented on src/liballoc/boxed.rs
> +/// First From
Agreed

2018-07-31 13:16 UTC, steveklabnik commented on src/liballoc/boxed.rs
> +    /// The result is allocated on the heap
Agreed.

2018-07-31 13:41 UTC, sehinde-gb reviewed
Thanks Steve for the clarification. And I agree with you. I don't have permission to approve these changes. I am a newbie here. Can someone please approve these changes and close down the PR request ? Or is this PR request owned by @skade I haven't heard from him in nearly 6 weeks.......

2018-07-31 14:59 UTC, Mark-Simulacrum commented
I'm assigning @steveklabnik as the reviewer here. I believe the next step is to rebase and fix the comments left by @alercah and @steveklabnik.

r? @steveklabnik

2018-08-14 16:32 UTC, TimNN commented
Ping from triage, @ormrepo. It looks like some changes have been requested to your PR.

2018-08-15 09:00 UTC, ormrepo commented
Hi Triage or Tim,

I agree with @steveklabnik

I don’t have write access to approve this PR and I have been waiting on
@skade to approve the PR.
I have tried on multiple occasions to contact @skade and I have been
unsuccessful.

I am new to PR’s what is the process for assigning a PR if that person
refuses to respond ?

Regards
Sehinde


On 14 August 2018 at 17:32:49, Tim Neumann (notifications@github.com) wrote:

Ping from triage, @ormrepo <https://github.com/ormrepo>. It looks like some
changes have been requested to your PR.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rust-lang/rust/pull/51738#issuecomment-412934504>, or mute
the thread
<https://github.com/notifications/unsubscribe-auth/AF64cMFadFnJng1U7eX85U-DMX6CVHRSks5uQvuwgaJpZM4U03Iv>
.

2018-08-15 09:12 UTC, TimNN commented
Thank you for contributing to the Rust project, @ormrepo. Please note that this Pull Request cannot be approved right now. Reviewers have requested some changes, which you need to make before approval can be granted. (Note that `@skade` does not necessarily have to be involved in the process if they are unreachable at the moment. Others, like `@steveklabnik`, can also approve this PR once the requested changes have been made).

---

To make the requested changes, you'll have to go to your local checkout of the `boxrs_edits` branch, make the requested changes, and then finally commit and push them to GitHub.

2018-08-15 11:11 UTC, ormrepo commented
Hi Tim,

I have made the changes on my branch and I am having some problems pushing
them up. I don't have an upstream branch specified, this means that I can’t
pull down the latest updates in order to rebase. I am at a loss right now
on how to move on. Do you have any ideas ?



Regards
Sehinde


On 15 August 2018 at 10:13:17, Tim Neumann (notifications@github.com) wrote:

Thank you for contributing to the Rust project, @ormrepo
<https://github.com/ormrepo>. Please note that this Pull Request cannot be
approved right now. Reviewers have requested some changes, which you need
to make before approval can be granted. (Note that @skade does not
necessarily have to be involved in the process if they are unreachable at
the moment. Others, like @steveklabnik, can also approve this PR once the
requested changes have been made).
------------------------------

To make the requested changes, you'll have to go to your local checkout of
the boxrs_edits branch, make the requested changes, and then finally commit
and push them to GitHub.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rust-lang/rust/pull/51738#issuecomment-413140272>, or mute
the thread
<https://github.com/notifications/unsubscribe-auth/AF64cCDs7pamMpIA_syKA0wJEJvyfI_Bks5uQ-YtgaJpZM4U03Iv>
.

2018-08-27 15:18 UTC, pietroalbini commented
Ping from triage @ormrepo! It's been a while since we heard from you, will you have time to work on this again?

2018-09-04 17:25 UTC, closed without merging