[WIP] fix for issue #8636
rust-lang/rust pull request #51894
Opened 2018-06-29 08:52 UTC by mikhail-m1

r? @nikomatsakis 

I found that I can also math with Subslice:
```
if let [_, ref subslice...] = slice {
    if let [ref a, ref b, ref c, ...] = subslice { ... }
}
```
it's not covered my tests yet, and may be better use `ui` tests for fix error output.

2018-06-29 09:07 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-3.9` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/398151103) ([raw log](https://api.travis-ci.org/v3/job/398151103/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain

[00:04:45] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:04:45] tidy error: /checkout/src/test/compile-fail/borrowck/borrowck-slice-pattern-element-loan.rs:28: line longer than 100 chars
[00:04:45] tidy error: /checkout/src/test/compile-fail/borrowck/borrowck-slice-pattern-element-loan.rs:44: line longer than 100 chars
[00:04:45] tidy error: /checkout/src/test/compile-fail/borrowck/borrowck-slice-pattern-element-loan.rs:61: line longer than 100 chars
[00:04:45] tidy error: /checkout/src/test/compile-fail/borrowck/borrowck-slice-pattern-element-loan.rs:79: line longer than 100 chars
[00:04:45] tidy error: /checkout/src/test/compile-fail/borrowck/borrowck-slice-pattern-element-loan.rs:88: line longer than 100 chars
[00:04:45] tidy error: /checkout/src/librustc_mir/borrow_check/path_utils.rs:406: line longer than 100 chars
[00:04:45] tidy error: /checkout/src/librustc_mir/borrow_check/path_utils.rs:407: line longer than 100 chars
[00:04:45] tidy error: /checkout/src/librustc_mir/borrow_check/path_utils.rs:408: line longer than 100 chars
[00:04:45] tidy error: /checkout/src/librustc_mir/borrow_check/path_utils.rs:409: line longer than 100 chars
[00:04:45] tidy error: /checkout/src/librustc_mir/borrow_check/path_utils.rs:426: line longer than 100 chars
[00:04:45] tidy error: /checkout/src/librustc_mir/borrow_check/path_utils.rs:439: line longer than 100 chars
[00:04:47] some tidy checks failed
[00:04:47] 
[00:04:47] 
[00:04:47] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:47] 
[00:04:47] 
[00:04:47] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:47] Build completed unsuccessfully in 0:01:43
[00:04:47] Build completed unsuccessfully in 0:01:43
[00:04:47] make: *** [tidy] Error 1
[00:04:47] Makefile:79: recipe for target 'tidy' failed

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:04c53c49
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:04f91e01:start=1530262771455773539,finish=1530262771462433506,duration=6659967
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:029ac4eb
$ head -30 ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
head: cannot open ‘./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers’ for reading: No such file or directory
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:11b1563b
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-07-02 16:31 UTC, mikhail-m1 commented
considering 
```
if let [_, ref subslice...] = slice {
    if let [ref a, ref b, ref c, ...] = subslice { ... }
}
```
I don't think additional tests are needed because `subslice` is still alive. Also `[a,[b,c]..]` syntax gives same MIR as `[a,b,c, ..].

2018-07-02 17:29 UTC, nikomatsakis requested changes
This looks basically right and the tests are good. I'm having trouble following the logic but this mostly suggests to me we need some comments. =)

2018-07-02 17:29 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/path_utils.rs
> +                    if o1 == o2 {
Seems right =)

2018-07-02 17:29 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/path_utils.rs
> +                    let length = max(min_length1, min_length2);
Comment (this is my attempt):

---

Logic: we are matching a slice with *some* length dynamically; if both of these patterns matched, it must be at least the greater of the two.

2018-07-02 17:29 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/path_utils.rs
> +                    if length <= offset_from_end || *offset_from_begin >= length - offset_from_end {
OK I must be confused about something here. =) Or else this logic is wrong. My money is on my being wrong, not the code. But in any case what would be nice I think are some comments and examples showing some interesting cases. Here is my attempt at an example, but it seems to suggest the code is wrong, so probably I am misunderstanding something:

---

- `[a, ..]` vs `[.., b]` -- here, for a list of length 1, `a` and `b` could both be the same element
  - `length` would be 1 (as min length in both cases is 1)
  - `offset_from_begin` and `offset_from_end` would be 0
  - but then we would return Disjoint?
    - `length <= offset_from_end` -- `1 <= 0`, false
    - `offset_from_begin >= length - offset_from_end` -- `0 >= 1 - 0`, false

---

What am I missing here?

2018-07-02 17:29 UTC, nikomatsakis commented on src/test/compile-fail/borrowck/borrowck-slice-pattern-element-loan.rs
> +            nop(&[first, second, third, fourth]);
👍

2018-07-02 17:29 UTC, nikomatsakis commented on src/test/compile-fail/borrowck/borrowck-slice-pattern-element-loan.rs
> +        if let [_, ref mut  second2, ref mut third, ..] = *s { //~ ERROR cannot borrow `s[..]` as mutable because it is also borrowed as immutable
👍

2018-07-02 17:29 UTC, nikomatsakis commented on src/test/compile-fail/borrowck/borrowck-slice-pattern-element-loan.rs
> +        if let [.., ref mut second, _] = *s {
👍

2018-07-02 17:29 UTC, nikomatsakis commented on src/test/compile-fail/borrowck/borrowck-slice-pattern-element-loan.rs
> +        if let [.., ref mut third2, _, _] = *s { //~ ERROR cannot borrow `s[..]` as mutable because it is also borrowed as immutable
👍

2018-07-02 17:29 UTC, nikomatsakis commented on src/test/compile-fail/borrowck/borrowck-slice-pattern-element-loan.rs
> +        if let [_, _, ref mut tail..] = *s {
👍

2018-07-02 17:29 UTC, nikomatsakis commented on src/test/compile-fail/borrowck/borrowck-slice-pattern-element-loan.rs
> +        if let [_, ref mut tail..] = *s { //~ ERROR cannot borrow `s[..]` as mutable because it is also borrowed as immutable
👍

2018-07-02 17:29 UTC, nikomatsakis commented on src/test/compile-fail/borrowck/borrowck-slice-pattern-element-loan.rs
> +        if let [ref mut tail.., _, _] = *s {
👍

2018-07-02 17:29 UTC, nikomatsakis commented on src/test/compile-fail/borrowck/borrowck-slice-pattern-element-loan.rs
> +        if let [ref mut tail.., _] = *s { //~ ERROR cannot borrow `s[..]` as mutable because it is also borrowed as immutable
👍

2018-07-02 17:29 UTC, nikomatsakis commented on src/test/compile-fail/borrowck/borrowck-slice-pattern-element-loan.rs
> +        if let [ref mut s2.., _, _, _] = *s { //~ ERROR cannot borrow `s[..]` as mutable because it is also borrowed as immutable
👍

2018-07-02 17:29 UTC, nikomatsakis commented on src/test/compile-fail/borrowck/borrowck-slice-pattern-element-loan.rs
> +        if let [ref mut s2.., _, _, _] = *s { //~ ERROR cannot borrow `s[..]` as mutable because it is also borrowed as immutable
(maybe we want a test like `[_, _, _, ref s1...]` vs `[ref mut s2.., _, _]` as well?)

2018-07-06 10:32 UTC, nikomatsakis approved these changes

2018-07-06 10:32 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/places_conflict.rs
> +                    // offset_from_end can be in range [1..min_length], -1 for last and min_length
Nit: it is not *-1* but rather just *1*...right?

2018-07-06 10:33 UTC, nikomatsakis commented
@bors r+

This is awesome! 💯

2018-07-06 10:34 UTC, nikomatsakis commented
@bors r+

This is awesome! 💯

2018-07-06 14:56 UTC, merged