Share buffer for liveness::simulate_block
rust-lang/rust pull request #52007
Opened 2018-07-02 22:21 UTC by spastorino

Closes #51818

r? @nikomatsakis

2018-07-02 22:22 UTC, nikomatsakis commented
@bors try

2018-07-02 22:34 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-3.9` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/399343297) ([raw log](https://api.travis-ci.org/v3/job/399343297/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://files.pythonhosted.org/packages/30/78/3ee2d1d05aadd79884402193c4d2967d042f29c941586ce450ce86fdc609/awscli-1.15.50-py2.py3-none-any.whl (1.3MB)
    0% |▎                               | 10kB 8.0MB/s eta 0:00:01
    1% |▌                               | 20kB 1.2MB/s eta 0:00:02
    2% |▊                               | 30kB 1.5MB/s eta 0:00:01
    3% |█                               | 40kB 1.3MB/s eta 0:00:01
---
Requirement already satisfied: PyYAML<=3.12,>=3.10 in /usr/lib/python2.7/dist-packages (from awscli)
Collecting botocore==1.10.49 (from awscli)
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://files.pythonhosted.org/packages/8d/10/488051d15156c325fec7347559dd4a54edc903d4cda9158f310a3e26e311/botocore-1.10.49-py2.py3-none-any.whl (4.4MB)
    0% |                                | 10kB 44.1MB/s eta 0:00:01
    0% |▏                               | 20kB 15.5MB/s eta 0:00:01
    0% |▎                               | 30kB 20.4MB/s eta 0:00:01
    0% |▎                               | 40kB 13.9MB/s eta 0:00:01
---

[00:04:31] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:04:32] tidy error: /checkout/src/librustc_mir/util/liveness.rs:169: line longer than 100 chars
[00:04:33] some tidy checks failed
[00:04:33] 
[00:04:33] 
[00:04:33] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:33] 
[00:04:33] 
[00:04:33] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:33] Build completed unsuccessfully in 0:01:30
[00:04:33] Build completed unsuccessfully in 0:01:30
[00:04:33] Makefile:79: recipe for target 'tidy' failed
[00:04:33] make: *** [tidy] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:015d62d8
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:0ba1ed34:start=1530570430001485672,finish=1530570430010641337,duration=9155665
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:1236bf13
$ head -30 ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
head: cannot open ‘./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers’ for reading: No such file or directory
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:0dcd5ff2
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-07-03 14:32 UTC, nikomatsakis commented
@bors try

2018-07-03 20:02 UTC, Mark-Simulacrum commented
Perf queued but it'll be .. a while.

2018-07-04 17:23 UTC, nikomatsakis commented
Perf URL: http://perf.rust-lang.org/compare.html?start=860d169474acabdc53b9a698f8ce02eba7e0daeb&end=00bcc44fb92c28465c727881355c3235a56a4045&stat=instructions%3Au

Results still not available :'(

2018-07-04 17:24 UTC, nikomatsakis commented
r=me presuming perf results are good (will need a rebase though)

2018-07-04 18:38 UTC, nikomatsakis requested changes

2018-07-04 18:38 UTC, nikomatsakis commented on src/librustc_mir/util/liveness.rs
> +    pub fn make_simulate_buffer<'tcx>(&self, mir: &Mir<'tcx>) -> LocalSet {
can you add a comment here about how this buffer is held across invokes of `simulate_block` for performance reasons?

2018-07-05 13:37 UTC, nikomatsakis commented
Looking at [the perf results](https://perf.rust-lang.org/compare.html?start=860d169474acabdc53b9a698f8ce02eba7e0daeb&end=00bcc44fb92c28465c727881355c3235a56a4045&stat=instructions%3Au), @spastorino and I decided that this PR isn't really helping, and it seems to make the code mildly messier, so we're gonna close it.

2018-07-05 13:37 UTC, closed without merging