NLL Liveness: Skip regionless types when visiting free regions
rust-lang/rust pull request #52037
Opened 2018-07-03 22:32 UTC by lqd

The tuple-stress benchmark exercises the liveness constraint generation code for types which do not have regions

Closes #52027

2018-07-03 22:32 UTC, rust-highfive commented
r? @petrochenkov

(rust_highfive has picked a reviewer for you, use r? to override)

2018-07-04 00:05 UTC, lqd commented
r? @nikomatsakis

2018-07-04 00:46 UTC, nikomatsakis commented
@bors try

2018-07-04 00:48 UTC, nikomatsakis requested changes

2018-07-04 00:48 UTC, nikomatsakis commented on src/librustc/ty/fold.rs
> +        self.super_ty(t)
oh, my bad, I should have written `super_visit_with` I suppose. Let's revert this part of the diff and just have the code below invoke `super_visit_with` — although I do prefer (these days) to make matching `super_ty` methods and so forth, it doesn't seem to be the standard in `TypeVisitor`.

2018-07-04 00:48 UTC, nikomatsakis commented
@bors try-

Actually, we can probably just land this and see the perf afterwards. It can't be *worse*

2018-07-04 09:04 UTC, nikomatsakis commented
@bors r+

2018-07-07 09:09 UTC, merged

2018-07-07 13:39 UTC, ljedrz commented
Looks like a nice improvement!

16,241.58% > 2,243.30 (over 7 times less) for tuple-stress