Rollup of bare_trait_objects PRs
rust-lang/rust pull request #52336
Opened 2018-07-13 05:58 UTC by ishitatsuyuki

All deny attributes were moved into bootstrap so they can be disabled with a line of config.

Warnings for external tools are disabled and it's up to the tool's maintainer to keep it warnings free.

r? @Mark-Simulacrum 
cc @ljedrz @kennytm

2018-07-13 06:13 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/403420695) ([raw log](https://api.travis-ci.org/v3/job/403420695/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:03:02]    Compiling syn v0.14.4
[00:03:14]    Compiling serde_json v1.0.22
[00:03:15]    Compiling serde_derive v1.0.69
[00:03:36]    Compiling tidy v0.1.0 (file:///checkout/src/tools/tidy)
[00:03:36] error: trait objects without an explicit `dyn` are deprecated
[00:03:36]    --> tools/tidy/src/features.rs:337:30
[00:03:36]     |
[00:03:36] 337 |                     mf: &mut FnMut(Result<(&str, Feature), &str>, &Path, usize)) {
[00:03:36]     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn FnMut(Result<(&str, Feature), &str>, &Path, usize)`
[00:03:36]     |
[00:03:36]     = note: requested on the command line with `-D bare-trait-objects`
[00:03:36] 
[00:03:36] error: trait objects without an explicit `dyn` are deprecated
[00:03:36]   --> tools/tidy/src/lib.rs:84:42
[00:03:36]    |
[00:03:36] 84 | fn walk_many(paths: &[&Path], skip: &mut FnMut(&Path) -> bool, f: &mut FnMut(&Path)) {
[00:03:36]    |                                          ^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn FnMut(&Path) -> bool`
[00:03:36] 
[00:03:36] error: trait objects without an explicit `dyn` are deprecated
[00:03:36]   --> tools/tidy/src/lib.rs:84:72
[00:03:36]    |
[00:03:36] 84 | fn walk_many(paths: &[&Path], skip: &mut FnMut(&Path) -> bool, f: &mut FnMut(&Path)) {
[00:03:36]    |                                                                        ^^^^^^^^^^^^ help: use `dyn`: `dyn FnMut(&Path)`
[00:03:36] 
[00:03:36] error: trait objects without an explicit `dyn` are deprecated
[00:03:36]   --> tools/tidy/src/lib.rs:90:33
[00:03:36]    |
[00:03:36] 90 | fn walk(path: &Path, skip: &mut FnMut(&Path) -> bool, f: &mut FnMut(&Path)) {
[00:03:36]    |                                 ^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn FnMut(&Path) -> bool`
[00:03:36] 
[00:03:36] error: trait objects without an explicit `dyn` are deprecated
[00:03:36]   --> tools/tidy/src/lib.rs:90:63
[00:03:36]    |
[00:03:36] 90 | fn walk(path: &Path, skip: &mut FnMut(&Path) -> bool, f: &mut FnMut(&Path)) {
[00:03:36]    |                                                               ^^^^^^^^^^^^ help: use `dyn`: `dyn FnMut(&Path)`
[00:03:36] error: aborting due to 5 previous errors
[00:03:36] 
[00:03:36] 
[00:03:36] error: Could not compile `tidy`.
[00:03:36] Caused by:
[00:03:36] Caused by:
[00:03:36]   process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc --crate-name tidy tools/tidy/src/lib.rs --color always --error-format json --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=9eb1600fedccd8e0 -C extra-filename=-9eb1600fedccd8e0 --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/release/deps --extern serde=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/libserde-df8ef05a77663569.rlib --extern serde_derive=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/release/deps/libserde_derive-af6fb9239c0d1b55.so --extern serde_json=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/libserde_json-075a641e614564a8.rlib` (exit code: 101)
[00:03:36] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/tools/tidy/Cargo.toml" "--features" "" "--message-format" "json"
[00:03:36] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:03:36] Build completed unsuccessfully in 0:00:41
[00:03:36] Build completed unsuccessfully in 0:00:41
[00:03:36] Makefile:79: recipe for target 'tidy' failed
[00:03:36] make: *** [tidy] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:023857b5
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:2ae6e1e0:start=1531461876108154850,finish=1531461876116575518,duration=8420668
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0808a7a8
$ head -30 ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
head: cannot open ‘./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers’ for reading: No such file or directory
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:1a22047d
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-07-13 09:18 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/403458338) ([raw log](https://api.travis-ci.org/v3/job/403458338/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:44:09] Documenting error index (x86_64-unknown-linux-gnu)
[00:44:09] travis_fold:start:stage2-error_index_generator
travis_time:start:stage2-error_index_generator
Building stage2 tool error_index_generator (x86_64-unknown-linux-gnu)
                        ^^^^^ help: use `dyn`: `dyn Error`
[00:44:09] 
[00:44:09] error: trait objects without an explicit `dyn` are deprecated
[00:44:09]    |
[00:44:09]    |
[00:44:09] 58 |     fn header(&self, output: &mut Write) -> Result<(), Box<Error>> {
[00:44:09]    |                                   ^^^^^ help: use `dyn`: `dyn Write`
[00:44:09] 
[00:44:09] error: trait objects without an explicit `dyn` are deprecated
[00:44:09]    |
[00:44:09]    |
[00:44:09] 58 |     fn header(&self, output: &mut Write) -> Result<(), Box<Error>> {
[00:44:09]    |                                                            ^^^^^ help: use `dyn`: `dyn Error`
[00:44:09] 
[00:44:09] error: trait objects without an explicit `dyn` are deprecated
[00:44:09]    |
[00:44:09]    |
[00:44:09] 78 |     fn title(&self, output: &mut Write) -> Result<(), Box<Error>> {
[00:44:09]    |                                  ^^^^^ help: use `dyn`: `dyn Write`
[00:44:09] 
[00:44:09] error: trait objects without an explicit `dyn` are deprecated
[00:44:09]    |
[00:44:09]    |
[00:44:09] 78 |     fn title(&self, output: &mut Write) -> Result<(), Box<Error>> {
[00:44:09]    |                                                           ^^^^^ help: use `dyn`: `dyn Error`
[00:44:09] 
[00:44:09] error: trait objects without an explicit `dyn` are deprecated
[00:44:09]    |
[00:44:09]    |
[00:44:09] 83 |     fn error_code_block(&self, output: &mut Write, info: &ErrorMetadata,
[00:44:09]    |                                             ^^^^^ help: use `dyn`: `dyn Write`
[00:44:09] 
[00:44:09] error: trait objects without an explicit `dyn` are deprecated
[00:44:09]   --> tools/error_index_generator/main.rs:error_index_generator/main.rs:201:73
[00:44:09]     |
[00:44:09] 201 | fn load_all_errors(metadata_dir: &Path) -> Result<ErrorMetadataMap, Box<Error>> {
[00:44:09]     |                                                                         ^^^^^ help: use `dyn`: `dyn Error`
[00:44:09] 
[00:44:09] error: trait objects without an explicit `dyn` are deprecated
[00:44:09]     |
[00:44:09]     |
[00:44:09] 222 |                                    formatter: T) -> Result<(), Box<Error>> {
[00:44:09]     |                                                                    ^^^^^ help: use `dyn`: `dyn Error`
[00:44:09] 
[00:44:09] error: trait objects without an explicit `dyn` are deprecated
[00:44:09]     |
[00:44:09]     |
[00:44:09] 235 | fn main_with_result(format: OutputFormat, dst: &Path) -> Result<(), Box<Error>> {
[00:44:09]     |                                                                         ^^^^^ help: use `dyn`: `dyn Error`
3603504 .
2255964 ./obj
2255932 ./obj/build
1663032 ./obj/build/x86_64-unknown-linux-gnu
---
143656 ./obj/build/x86_64-unknown-linux-gnu/stage1-std
133584 ./obj/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu
133580 ./obj/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release
130368 ./obj/build/bootstrap/debug/incremental/bootstrap-2evv84e4ca5z
130364 ./obj/build/bootstrap/debug/incremental/bootstrap-2evv84e4ca5z/s-f2v01dy705-1g9hlhr-k20otd68iazr
118664 ./obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu
118660 ./obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release
111744 ./obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps
107604 ./src/llvm/test/CodeGen
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-07-13 10:32 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/403482753) ([raw log](https://api.travis-ci.org/v3/job/403482753/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:43:21]    Compiling failure_derive v0.1.1
[00:43:25]    Compiling failure v0.1.1
[00:43:25]    Compiling rustfix v0.3.1
[00:43:27]    Compiling compiletest v0.0.0 (file:///checkout/src/tools/compiletest)
[00:43:27] error: trait objects without an explicit `dyn` are deprecated
[00:43:27]    --> tools/compiletest/src/header.rs:413:61
[00:43:27]     |
[00:43:27] 413 | fn iter_header(testfile: &Path, cfg: Option<&str>, it: &mut FnMut(&str)) {
[00:43:27]     |                                                             ^^^^^^^^^^^ help: use `dyn`: `dyn FnMut(&str)`
[00:43:27]     |
[00:43:27]     = note: requested on the command line with `-D bare-trait-objects`
[00:43:27] 
[00:43:27] error: trait objects without an explicit `dyn` are deprecated
[00:43:27]   --> tools/compiletest/src/read2.rs:48:20
[00:43:27]    |
[00:43:27] 48 |         data: &mut FnMut(bool, &mut Vec<u8>, bool),
[00:43:27]    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn FnMut(bool, &mut Vec<u8>, bool)`
[00:43:28] error: aborting due to 2 previous errors
[00:43:28] 
[00:43:28] error: Could not compile `compiletest`.
[00:43:28] 
[00:43:28] 
[00:43:28] Caused by:
[00:43:28]   process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc --crate-name compiletest tools/compiletest/src/main.rs --color always --error-format json --crate-type bin --emit=dep-info,link -C opt-level=2 -C metadata=e61127a869a0112d -C extra-filename=-e61127a869a0112d --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/release/deps --extern diff=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/libdiff-dc42cc1fc85d825b.rlib --extern env_logger=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/libenv_logger-cd53db7d36bd9ba4.rlib --extern filetime=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/libfiletime-be37fe52ca647811.rlib --extern getopts=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/libgetopts-84ce83e489b7e5a5.rlib --extern libc=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/liblibc-ed5e56cb6a1a6a91.rlib --extern log=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/liblog-49caa0603b85251c.rlib --extern regex=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/libregex-4e38f3f16fc8f863.rlib --extern rustfix=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/librustfix-91ca9ba11d59b0f8.rlib --extern serde=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/libserde-df8ef05a77663569.rlib --extern serde_derive=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/release/deps/libserde_derive-af6fb9239c0d1b55.so --extern serde_json=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/libserde_json-075a641e614564a8.rlib -L native=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/build/backtrace-sys-e7051d4409bf3a37/out` (exit code: 101)
[00:43:28] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/tools/compiletest/Cargo.toml" "--features" "" "--message-format" "json"
[00:43:28] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[00:43:28] Build completed unsuccessfully in 0:00:22
[00:43:28] Build completed unsuccessfully in 0:00:22
[00:43:28] make: *** [check] Error 1
[00:43:28] Makefile:58: recipe for target 'check' failed

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:0bef9ecf
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-07-13 11:53 UTC, Mark-Simulacrum requested changes

2018-07-13 11:53 UTC, Mark-Simulacrum commented on src/bootstrap/test.rs
> +                                                 false);
Why isn't rustfmt an extended tool?

2018-07-13 11:53 UTC, Mark-Simulacrum commented on src/build_helper/lib.rs
> +
Stray additional line.

2018-07-13 11:53 UTC, Mark-Simulacrum commented on src/libfmt_macros/lib.rs
> +
Please remove these stray lines.

2018-07-13 11:53 UTC, Mark-Simulacrum commented on src/tools/compiletest/src/read2.rs
> +        mut data: impl FnMut(bool, &mut Vec<u8>, bool),
Please don't make semantic changes in this PR. (Easier to review).

2018-07-13 11:53 UTC, Mark-Simulacrum commented on src/tools/tidy/src/features.rs
> +                    mf: &mut impl FnMut(Result<(&str, Feature), &str>, &Path, usize)) {
This is a semantic change.

2018-07-13 11:53 UTC, Mark-Simulacrum commented on src/tools/tidy/src/lib.rs
> +fn walk(path: &Path, skip: &mut impl FnMut(&Path) -> bool, f: &mut impl FnMut(&Path)) {
Additional semantic changes.

2018-07-13 12:10 UTC, ishitatsuyuki commented on src/bootstrap/test.rs
> +                                                 false);
Oops, my mistake.

2018-07-13 12:14 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/403508356) ([raw log](https://api.travis-ci.org/v3/job/403508356/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Testing alloc stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:01:33]    Compiling libc v0.2.42
[01:01:34]    Compiling rand v0.4.2
[01:01:37]    Compiling alloc v0.0.0 (file:///checkout/src/liballoc)
[01:01:38] error: trait objects without an explicit `dyn` are deprecated
[01:01:38]   --> liballoc/../liballoc/tests/arc.rs:21:21
[01:01:38]    |
[01:01:38] 21 |     let mut a: Weak<Any> = a;  // Unsizing
[01:01:38]    |                     ^^^ help: use `dyn`: `dyn Any`
[01:01:38]    |
[01:01:38]    = note: requested on the command line with `-D bare-trait-objects`
[01:01:38] 
[01:01:38] error: trait objects without an explicit `dyn` are deprecated
[01:01:38]   --> liballoc/../liballoc/tests/arc.rs:42:16
[01:01:38]    |
[01:01:38] 42 |     let a: Arc<Any> = a;  // Unsizing
[01:01:38]    |                ^^^ help: use `dyn`: `dyn Any`
[01:01:38] 
[01:01:38] error: trait objects without an explicit `dyn` are deprecated
[01:01:38]   --> liballoc/../liballoc/tests/arc.rs:52:21
[01:01:38]    |
[01:01:38] 52 |     let mut b: Weak<Any> = b;  // Unsizing
[01:01:38]    |                     ^^^ help: use `dyn`: `dyn Any`
[01:01:38] 
[01:01:38] error: trait objects without an explicit `dyn` are deprecated
[01:01:38]   --> liballoc/../liballoc/tests/btree/set.rs:43:58
[01:01:38]    |
[01:01:38] 43 |     where F: FnOnce(&BTreeSet<i32>, &BTreeSet<i32>, &mut FnMut(&i32) -> bool) -> bool
[01:01:38]    |                                                          ^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn FnMut(&i32) -> bool`
[01:01:38] 
[01:01:38] error: trait objects without an explicit `dyn` are deprecated
[01:01:38]   --> liballoc/../liballoc/tests/rc.rs:21:21
[01:01:38]    |
[01:01:38] 21 |     let mut a: Weak<Any> = a;  // Unsizing
[01:01:38]    |                     ^^^ help: use `dyn`: `dyn Any`
[01:01:38] 
[01:01:38] error: trait objects without an explicit `dyn` are deprecated
[01:01:38]   --> liballoc/../liballoc/tests/rc.rs:42:15
[01:01:38]    |
[01:01:38] 42 |     let a: Rc<Any> = a;  // Unsizing
[01:01:38]    |               ^^^ help: use `dyn`: `dyn Any`
[01:01:38] 
[01:01:38] error: trait objects without an explicit `dyn` are deprecated
[01:01:38]   --> liballoc/../liballoc/tests/rc.rs:52:21
[01:01:38]    |
[01:01:38] 52 |     let mut b: Weak<Any> = b;  // Unsizing
[01:01:38]    |                     ^^^ help: use `dyn`: `dyn Any`
[01:01:38] 
[01:01:38] error: trait objects without an explicit `dyn` are deprecated
[01:01:38]   --> liballoc/../liballoc/tests/lib.rs:66:62
[01:01:38]    |
[01:01:38] 66 |     let mut hasher_2 = Box::new(DefaultHasher::new()) as Box<Hasher>;
[01:01:38]    |                                                              ^^^^^^ help: use `dyn`: `dyn Hasher`
[01:01:44] error: aborting due to 8 previous errors
[01:01:44] 
[01:01:44] error: Could not compile `alloc`.
[01:01:44] warning: build failed, waiting for other jobs to finish...
[01:01:44] warning: build failed, waiting for other jobs to finish...
[01:01:47] error: build failed
[01:01:47] 
[01:01:47] 
[01:01:47] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--features" "panic-unwind jemalloc backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "-p" "alloc" "--" "--quiet"
[01:01:47] 
[01:01:47] 
[01:01:47] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:01:47] Build completed unsuccessfully in 0:16:50
[01:01:47] Build completed unsuccessfully in 0:16:50
[01:01:47] make: *** [check] Error 1
[01:01:47] Makefile:58: recipe for target 'check' failed

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:1cb1cbf0
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:1b605448:start=1531484051280120099,finish=1531484051285410859,duration=5290760
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:02b46c28
$ head -30 ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
head: cannot open ‘./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers’ for reading: No such file or directory
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:0a697203
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-07-14 04:38 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/403814140) ([raw log](https://api.travis-ci.org/v3/job/403814140/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:59:17] travis_fold:start:test_stage1-core
travis_time:start:test_stage1-core
Testing core stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[00:59:17]    Compiling core v0.0.0 (file:///checkout/src/libcore)
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]   --> libcore/../libcore/tests/any.rs:20:29
[00:59:20]    |
[00:59:20] 20 |     let (a, b, c) = (&5 as &Any, &TEST as &Any, &Test as &Any);
[00:59:20]    |                             ^^^ help: use `dyn`: `dyn Any`
[00:59:20]    |
[00:59:20]    = note: requested on the command line with `-D bare-trait-objects`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]   --> libcore/../libcore/tests/any.rs:20:44
[00:59:20]    |
[00:59:20] 20 |     let (a, b, c) = (&5 as &Any, &TEST as &Any, &Test as &Any);
[00:59:20]    |                                            ^^^ help: use `dyn`: `dyn Any`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]   --> libcore/../libcore/tests/any.rs:20:59
[00:59:20]    |
[00:59:20] 20 |     let (a, b, c) = (&5 as &Any, &TEST as &Any, &Test as &Any);
[00:59:20]    |                                                           ^^^ help: use `dyn`: `dyn Any`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]   --> libcore/../libcore/tests/any.rs:37:41
[00:59:20]    |
[00:59:20] 37 |     let (a, b, c) = (box 5_usize as Box<Any>, box TEST as Box<Any>, box Test as Box<Any>);
[00:59:20]    |                                         ^^^ help: use `dyn`: `dyn Any`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]   --> libcore/../libcore/tests/any.rs:37:63
[00:59:20]    |
[00:59:20] 37 |     let (a, b, c) = (box 5_usize as Box<Any>, box TEST as Box<Any>, box Test as Box<Any>);
[00:59:20]    |                                                               ^^^ help: use `dyn`: `dyn Any`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]   --> libcore/../libcore/tests/any.rs:37:85
[00:59:20]    |
[00:59:20] 37 |     let (a, b, c) = (box 5_usize as Box<Any>, box TEST as Box<Any>, box Test as Box<Any>);
[00:59:20]    |                                                                                     ^^^ help: use `dyn`: `dyn Any`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]   --> libcore/../libcore/tests/any.rs:54:26
[00:59:20]    |
[00:59:20] 54 |     let a = &5_usize as &Any;
[00:59:20]    |                          ^^^ help: use `dyn`: `dyn Any`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]   --> libcore/../libcore/tests/any.rs:72:30
[00:59:20]    |
[00:59:20] 72 |     let a_r = &mut a as &mut Any;
[00:59:20]    |                              ^^^ help: use `dyn`: `dyn Any`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]   --> libcore/../libcore/tests/any.rs:74:27
[00:59:20]    |
[00:59:20] 74 |     let b_r = tmp as &mut Any;
[00:59:20]    |                           ^^^ help: use `dyn`: `dyn Any`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]    --> libcore/../libcore/tests/any.rs:116:26
[00:59:20]     |
[00:59:20] 116 |     let test = &test as &Any;
[00:59:20]     |                          ^^^ help: use `dyn`: `dyn Any`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]     |
[00:59:20]     |
[00:59:20] 131 |         let mut indirect_hasher: &mut Hasher = &mut hasher;
[00:59:20]     |                                       ^^^^^^ help: use `dyn`: `dyn Hasher`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]    |
[00:59:20]    |
[00:59:20] 25 |     struct X(str); struct Y(Z + 'static);
[00:59:20]    |                             ^^^^^^^^^^^ help: use `dyn`: `dyn Z + 'static`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]    --> libcore/../libcore/tests/mem.rs:112:33
[00:59:20]     |
[00:59:20] 112 |     let a = box 100isize as Box<Foo>;
[00:59:20]     |                                 ^^^ help: use `dyn`: `dyn Foo`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]    --> libcore/../libcore/tests/mem.rs:116:21
[00:59:20]     |
[00:59:20] 116 |         let _x: Box<Foo> = transmute(x);
[00:59:20]     |                     ^^^ help: use `dyn`: `dyn Foo`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]     |
[00:59:20]     |
[00:59:20] 243 |     let mut functions: [Box<Fn() -> Option<()>>; 3] =
[00:59:20]     |                             ^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn Fn() -> Option<()>`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]   --> libcore/../libcore/tests/ptr.rs:87:20
[00:59:20]    |
[00:59:20] 87 |     let ci: *const ToString = &3;
[00:59:20]    |                    ^^^^^^^^ help: use `dyn`: `dyn ToString`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]   --> libcore/../libcore/tests/ptr.rs:90:18
[00:59:20]    |
[00:59:20] 90 |     let mi: *mut ToString = &mut 3;
[00:59:20]    |                  ^^^^^^^^ help: use `dyn`: `dyn ToString`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]   --> libcore/../libcore/tests/ptr.rs:93:21
[00:59:20]    |
[00:59:20] 93 |     let nci: *const ToString = null::<isize>();
[00:59:20]    |                     ^^^^^^^^ help: use `dyn`: `dyn ToString`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]   --> libcore/../libcore/tests/ptr.rs:96:19
[00:59:20]    |
[00:59:20] 96 |     let nmi: *mut ToString = null_mut::<isize>();
[00:59:20]    |                   ^^^^^^^^ help: use `dyn`: `dyn ToString`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]    --> libcore/../libcore/tests/ptr.rs:143:24
[00:59:20]     |
[00:59:20] 143 |         let ci: *const ToString = &3;
[00:59:20]     |                        ^^^^^^^^ help: use `dyn`: `dyn ToString`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]    --> libcore/../libcore/tests/ptr.rs:146:22
[00:59:20]     |
[00:59:20] 146 |         let mi: *mut ToString = &mut 3;
[00:59:20]     |                      ^^^^^^^^ help: use `dyn`: `dyn ToString`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]    --> libcore/../libcore/tests/ptr.rs:149:25
[00:59:20]     |
[00:59:20] 149 |         let nci: *const ToString = null::<isize>();
[00:59:20]     |                         ^^^^^^^^ help: use `dyn`: `dyn ToString`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]    --> libcore/../libcore/tests/ptr.rs:152:23
[00:59:20]     |
[00:59:20] 152 |         let nmi: *mut ToString = null_mut::<isize>();
[00:59:20]     |                       ^^^^^^^^ help: use `dyn`: `dyn ToString`
[00:59:20] 
[00:59:20] error: trait objects without an explicit `dyn` are deprecated
[00:59:20]    --> libcore/../libcore/tests/ptr.rs:185:22
[00:59:20]     |
[00:59:20] 185 |         let mi: *mut ToString = &mut 3;
[00:59:20]     |                      ^^^^^^^^ help: use `dyn`: `dyn ToString`
[00:59:20] 
[00 [...]

2018-07-14 09:11 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/403846967) ([raw log](https://api.travis-ci.org/v3/job/403846967/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[01:03:50] travis_fold:start:test_stage1-core
travis_time:start:test_stage1-core
Testing core stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:03:50]    Compiling core v0.0.0 (file:///checkout/src/libcore)
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]   --> libcore/../libcore/tests/any.rs:20:29
[01:03:53]    |
[01:03:53] 20 |     let (a, b, c) = (&5 as &Any, &TEST as &Any, &Test as &Any);
[01:03:53]    |                             ^^^ help: use `dyn`: `dyn Any`
[01:03:53]    |
[01:03:53]    = note: `-D bare-trait-objects` implied by `-D warnings`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]   --> libcore/../libcore/tests/any.rs:20:44
[01:03:53]    |
[01:03:53] 20 |     let (a, b, c) = (&5 as &Any, &TEST as &Any, &Test as &Any);
[01:03:53]    |                                            ^^^ help: use `dyn`: `dyn Any`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]   --> libcore/../libcore/tests/any.rs:20:59
[01:03:53]    |
[01:03:53] 20 |     let (a, b, c) = (&5 as &Any, &TEST as &Any, &Test as &Any);
[01:03:53]    |                                                           ^^^ help: use `dyn`: `dyn Any`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]   --> libcore/../libcore/tests/any.rs:37:41
[01:03:53]    |
[01:03:53] 37 |     let (a, b, c) = (box 5_usize as Box<Any>, box TEST as Box<Any>, box Test as Box<Any>);
[01:03:53]    |                                         ^^^ help: use `dyn`: `dyn Any`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]   --> libcore/../libcore/tests/any.rs:37:63
[01:03:53]    |
[01:03:53] 37 |     let (a, b, c) = (box 5_usize as Box<Any>, box TEST as Box<Any>, box Test as Box<Any>);
[01:03:53]    |                                                               ^^^ help: use `dyn`: `dyn Any`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]   --> libcore/../libcore/tests/any.rs:37:85
[01:03:53]    |
[01:03:53] 37 |     let (a, b, c) = (box 5_usize as Box<Any>, box TEST as Box<Any>, box Test as Box<Any>);
[01:03:53]    |                                                                                     ^^^ help: use `dyn`: `dyn Any`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]   --> libcore/../libcore/tests/any.rs:54:26
[01:03:53]    |
[01:03:53] 54 |     let a = &5_usize as &Any;
[01:03:53]    |                          ^^^ help: use `dyn`: `dyn Any`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]   --> libcore/../libcore/tests/any.rs:72:30
[01:03:53]    |
[01:03:53] 72 |     let a_r = &mut a as &mut Any;
[01:03:53]    |                              ^^^ help: use `dyn`: `dyn Any`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]   --> libcore/../libcore/tests/any.rs:74:27
[01:03:53]    |
[01:03:53] 74 |     let b_r = tmp as &mut Any;
[01:03:53]    |                           ^^^ help: use `dyn`: `dyn Any`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]    --> libcore/../libcore/tests/any.rs:116:26
[01:03:53]     |
[01:03:53] 116 |     let test = &test as &Any;
[01:03:53]     |                          ^^^ help: use `dyn`: `dyn Any`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]     |
[01:03:53]     |
[01:03:53] 131 |         let mut indirect_hasher: &mut Hasher = &mut hasher;
[01:03:53]     |                                       ^^^^^^ help: use `dyn`: `dyn Hasher`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]    |
[01:03:53]    |
[01:03:53] 25 |     struct X(str); struct Y(Z + 'static);
[01:03:53]    |                             ^^^^^^^^^^^ help: use `dyn`: `dyn Z + 'static`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]    --> libcore/../libcore/tests/mem.rs:112:33
[01:03:53]     |
[01:03:53] 112 |     let a = box 100isize as Box<Foo>;
[01:03:53]     |                                 ^^^ help: use `dyn`: `dyn Foo`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]    --> libcore/../libcore/tests/mem.rs:116:21
[01:03:53]     |
[01:03:53] 116 |         let _x: Box<Foo> = transmute(x);
[01:03:53]     |                     ^^^ help: use `dyn`: `dyn Foo`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]     |
[01:03:53]     |
[01:03:53] 243 |     let mut functions: [Box<Fn() -> Option<()>>; 3] =
[01:03:53]     |                             ^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn Fn() -> Option<()>`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]   --> libcore/../libcore/tests/ptr.rs:87:20
[01:03:53]    |
[01:03:53] 87 |     let ci: *const ToString = &3;
[01:03:53]    |                    ^^^^^^^^ help: use `dyn`: `dyn ToString`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]   --> libcore/../libcore/tests/ptr.rs:90:18
[01:03:53]    |
[01:03:53] 90 |     let mi: *mut ToString = &mut 3;
[01:03:53]    |                  ^^^^^^^^ help: use `dyn`: `dyn ToString`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]   --> libcore/../libcore/tests/ptr.rs:93:21
[01:03:53]    |
[01:03:53] 93 |     let nci: *const ToString = null::<isize>();
[01:03:53]    |                     ^^^^^^^^ help: use `dyn`: `dyn ToString`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]   --> libcore/../libcore/tests/ptr.rs:96:19
[01:03:53]    |
[01:03:53] 96 |     let nmi: *mut ToString = null_mut::<isize>();
[01:03:53]    |                   ^^^^^^^^ help: use `dyn`: `dyn ToString`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]    --> libcore/../libcore/tests/ptr.rs:143:24
[01:03:53]     |
[01:03:53] 143 |         let ci: *const ToString = &3;
[01:03:53]     |                        ^^^^^^^^ help: use `dyn`: `dyn ToString`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]    --> libcore/../libcore/tests/ptr.rs:146:22
[01:03:53]     |
[01:03:53] 146 |         let mi: *mut ToString = &mut 3;
[01:03:53]     |                      ^^^^^^^^ help: use `dyn`: `dyn ToString`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]    --> libcore/../libcore/tests/ptr.rs:149:25
[01:03:53]     |
[01:03:53] 149 |         let nci: *const ToString = null::<isize>();
[01:03:53]     |                         ^^^^^^^^ help: use `dyn`: `dyn ToString`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]    --> libcore/../libcore/tests/ptr.rs:152:23
[01:03:53]     |
[01:03:53] 152 |         let nmi: *mut ToString = null_mut::<isize>();
[01:03:53]     |                       ^^^^^^^^ help: use `dyn`: `dyn ToString`
[01:03:53] 
[01:03:53] error: trait objects without an explicit `dyn` are deprecated
[01:03:53]    --> libcore/../libcore/tests/ptr.rs:185:22
[01:03:53]     |
[01:03:53] 185 |         let mi: *mut ToString = &mut 3;
[01:03:53]     |                      ^^^^^^^^ help: use `dyn`: `dyn ToString`
[01:03:53] 
[01:03:53] er [...]

2018-07-15 13:59 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/404132159) ([raw log](https://api.travis-ci.org/v3/job/404132159/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain

[00:03:59] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:04:00] tidy error: /checkout/src/libcore/tests/any.rs:37: line longer than 100 chars
[00:04:01] some tidy checks failed
[00:04:01] 
[00:04:01] 
[00:04:01] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:01] 
[00:04:01] 
[00:04:01] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:01] Build completed unsuccessfully in 0:00:50
[00:04:01] Build completed unsuccessfully in 0:00:50
[00:04:01] Makefile:79: recipe for target 'tidy' failed
[00:04:01] make: *** [tidy] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:261e5b30
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:11b20c42:start=1531662733199518595,finish=1531662733209470564,duration=9951969
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:15d56108
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:358bd968
travis_time:start:358bd968
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:03b2ae48
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-07-16 06:15 UTC, ishitatsuyuki commented
r? @Mark-Simulacrum

2018-07-16 13:17 UTC, Mark-Simulacrum commented
r=me after squashing commits (probably into rustbuild changes + everything else).

2018-07-16 13:17 UTC, Mark-Simulacrum approved these changes

2018-07-18 02:01 UTC, ishitatsuyuki commented
ping @Mark-Simulacrum @kennytm

2018-07-18 02:14 UTC, Mark-Simulacrum commented
Can you squash the remaining non-rustbuild change commits into one?

2018-07-18 02:19 UTC, ishitatsuyuki commented
@Mark-Simulacrum They are merge commits, so I can't. (It's possible to turn them into a squashed merge, but given that there's already different PR's open it will cause conflict plus not automatically getting closed by GitHub.)

2018-07-18 02:32 UTC, Mark-Simulacrum commented
Yes, they are merged commits, but I imagine you can ask/work with @ljedrz to have two commits in this PR: one applying the `Trait` to `dyn Trait` change across the codebase and another that makes rustbuild pass the -D flag to rustc invocations. These changes should be all that's needed; we don't *need* a merge commit here.

(I'm *okay* merging this, but it seems considerably better to put in the extra work to make this PR and the overall commit history be a little cleaner).

2018-07-18 03:19 UTC, kennytm commented
Given that only #52221, #52222 and #52296 remain (the rest are all merged), perhaps it's better we exclude @ljedrz's contributions from this PR and focus on the bootstrap modification.

2018-07-18 03:33 UTC, ishitatsuyuki commented
I don't think rolling up hurts? Anyway that's how I remove `#[deny(bare_trait_objects)]` from his PR.

I think the current state is the best to merge.

2018-07-18 03:46 UTC, kennytm commented
The current state is not a good state to merge, it still contains old commits named "Deny bare trait objects in librustc_driver" etc.

2018-07-18 03:50 UTC, ishitatsuyuki commented
@kennytm Merging a same branch twice doesn't result in duplicate commits. It's just how GitHub shows them.

2018-07-21 05:52 UTC, ishitatsuyuki commented
@kennytm @Mark-Simulacrum What's your stance on merging this?

2018-07-21 07:47 UTC, kennytm commented
Please rebase on the latest master (use `git rebase -p master` to keep the merge commits) to get rid of the already-merged PRs.

2018-07-21 07:58 UTC, ishitatsuyuki commented
r? @kennytm

2018-07-21 08:57 UTC, kennytm commented
Why 4bd3e0469d9cd04c76f6b46899a6984f1cdc9a2b still exists? It should be merged in  #52286.

2018-07-21 09:20 UTC, kennytm commented
Or perhaps create a "true rollup" like this:

```sh
git checkout master
git checkout -b dyn-rollup

# rollup the libstd PR 
git fetch origin +refs/pull/52221/merge: &&
git merge --no-ff FETCH_HEAD^2

# rollup the libcore PR 
git fetch origin +refs/pull/52222/merge: &&
git merge --no-ff FETCH_HEAD^2

# rollup the libterm PR 
git fetch origin +refs/pull/52296/merge: &&
git merge --no-ff FETCH_HEAD^2

# ...
# apply additional changes 
# ...

git push self dyn-rollup --force-with-lease
```

2018-07-21 13:02 UTC, ishitatsuyuki commented
r? @kennytm

2018-07-21 19:54 UTC, kennytm commented
@bors r+

2018-07-22 04:58 UTC, rust-highfive commented
The job `x86_64-gnu-distcheck` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/406743445) ([raw log](https://api.travis-ci.org/v3/job/406743445/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:07:53]    Compiling xz2 v0.1.5
[00:07:54] [RUSTC-TIMING] xz2 test:false 0.533
[00:07:54] [RUSTC-TIMING] clap test:false 31.506
[00:07:54]    Compiling installer v0.0.0 (file:///checkout/src/tools/rust-installer)
[00:07:54] error: trait objects without an explicit `dyn` are deprecated
[00:07:54]   --> tools/rust-installer/src/lib.rs:27:5
[00:07:54] 27 | /     error_chain!{
[00:07:54] 28 | |         foreign_links {
[00:07:54] 28 | |         foreign_links {
[00:07:54] 29 | |             Io(::std::io::Error);
[00:07:54] 30 | |             StripPrefix(::std::path::StripPrefixError);
[00:07:54] 31 | |             WalkDir(::walkdir::Error);
[00:07:54] 33 | |     }
[00:07:54] 33 | |     }
[00:07:54]    | |_____^ help: use `dyn`: `dyn :: std :: error :: Error + Send + 'static`
[00:07:54]    |
[00:07:54]    = note: requested on the command line with `-D bare-trait-objects`
[00:07:54] 
[00:07:54] 
[00:07:54] error: trait objects without an explicit `dyn` are deprecated
[00:07:54]   --> tools/rust-installer/src/lib.rs:27:5
[00:07:54] 27 | /     error_chain!{
[00:07:54] 28 | |         foreign_links {
[00:07:54] 28 | |         foreign_links {
[00:07:54] 29 | |             Io(::std::io::Error);
[00:07:54] 30 | |             StripPrefix(::std::path::StripPrefixError);
[00:07:54] 31 | |             WalkDir(::walkdir::Error);
[00:07:54] 33 | |     }
[00:07:54] 33 | |     }
[00:07:54]    | |_____^ help: use `dyn`: `dyn :: std :: error :: Error + Send`
[00:07:54]    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
[00:07:54] 
[00:07:54] 
[00:07:54] error: trait objects without an explicit `dyn` are deprecated
[00:07:54]   --> tools/rust-installer/src/lib.rs:27:5
[00:07:54] 27 | /     error_chain!{
[00:07:54] 28 | |         foreign_links {
[00:07:54] 28 | |         foreign_links {
[00:07:54] 29 | |             Io(::std::io::Error);
[00:07:54] 30 | |             StripPrefix(::std::path::StripPrefixError);
[00:07:54] 31 | |             WalkDir(::walkdir::Error);
[00:07:54] 33 | |     }
[00:07:54] 33 | |     }
[00:07:54]    | |_____^ help: use `dyn`: `dyn (:: std :: error :: Error)`
[00:07:54]    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
[00:07:54] 
[00:07:55] error: aborting due to 3 previous errors
[00:07:55] 
[00:07:55] 
[00:07:55] [RUSTC-TIMING] installer test:false 0.314
[00:07:55] error: Could not compile `installer`.
[00:07:55] 
[00:07:55] Caused by:
[00:07:55]   process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc --crate-name installer tools/rust-installer/src/lib.rs --color always --error-format json --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=2cd4cd204e007c60 -C extra-filename=-2cd4cd204e007c60 --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/release/deps --extern clap=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/libclap-901738dea5f72eda.rlib --extern error_chain=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/liberror_chain-16f6fc613f26e16e.rlib --extern flate2=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/libflate2-2b513184d9d612c2.rlib --extern rayon=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/librayon-c921d099f6467eb0.rlib --extern tar=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/libtar-d33b2f7548394009.rlib --extern walkdir=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/libwalkdir-ade8f658253ac77b.rlib --extern xz2=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps/libxz2-ff8dc798a2f4c9b7.rlib -L native=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/build/backtrace-sys-7205e6adb9d66e6b/out -L native=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/build/miniz-sys-27571ee36438df44/out -L /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/build/lzma-sys-e7849bb6ccad13a2/out/lib` (exit code: 101)
[00:07:55] expected success, got: exit code: 101
[00:07:55] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test distcheck
[00:07:55] Build completed unsuccessfully in 0:05:19
travis_time:end:01d713d2:start=1532234953028800212,finish=1532235428393824661,duration=475365024449
---
travis_time:end:0a1e20ea:start=1532235428889116170,finish=1532235428897794974,duration=8678804
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0b29d7f0
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:1756d988
travis_time:start:1756d988
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:00dc63b2
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-07-23 08:31 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/407036584) ([raw log](https://api.travis-ci.org/v3/job/407036584/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain

[00:03:33] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:03:34] tidy error: /checkout/src/bootstrap/bin/rustc.rs:299: line longer than 100 chars
[00:03:34] tidy error: /checkout/src/bootstrap/tool.rs:290: trailing whitespace
[00:03:34] tidy error: /checkout/src/bootstrap/tool.rs:291: line longer than 100 chars
[00:03:34] tidy error: /checkout/src/bootstrap/tool.rs:388: line longer than 100 chars
[00:03:35] some tidy checks failed
[00:03:35] 
[00:03:35] 
[00:03:35] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:03:35] 
[00:03:35] 
[00:03:35] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:03:35] Build completed unsuccessfully in 0:00:45
[00:03:35] Build completed unsuccessfully in 0:00:45
[00:03:35] make: *** [tidy] Error 1
[00:03:35] Makefile:79: recipe for target 'tidy' failed

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:2bec248a
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:29f909b5:start=1532334251077851541,finish=1532334251084483779,duration=6632238
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:00042c2c
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:18d15fec
travis_time:start:18d15fec
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:04edcab8
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-07-23 09:03 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/407046154) ([raw log](https://api.travis-ci.org/v3/job/407046154/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain

[00:03:44] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:03:44] tidy error: /checkout/src/bootstrap/tool.rs:290: trailing whitespace
[00:03:45] some tidy checks failed
[00:03:45] 
[00:03:45] 
[00:03:45] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:03:45] 
[00:03:45] 
[00:03:45] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:03:45] Build completed unsuccessfully in 0:00:50
[00:03:45] Build completed unsuccessfully in 0:00:50
[00:03:45] Makefile:79: recipe for target 'tidy' failed
[00:03:45] make: *** [tidy] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:16982f44
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:02742192:start=1532336130182300927,finish=1532336130189494089,duration=7193162
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0c1bddfe
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:21cae33a
travis_time:start:21cae33a
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:2382e9a8
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-07-23 11:05 UTC, ishitatsuyuki commented
r? @kennytm

I added line breaks in macros due to the length limit. Hope that's fine?

2018-07-23 14:22 UTC, kennytm commented
Fine. 

BTW GitHub said there's merge conflict in ` src/librustdoc/visit_ast.rs `, maybe needs another rebase?

2018-07-24 03:42 UTC, ishitatsuyuki commented
r? @kennytm

2018-07-24 04:20 UTC, kennytm commented
@bors r=Mark-Simulacrum,kennytm

2018-07-24 06:46 UTC, rust-highfive commented
The job `armhf-gnu` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/407463717) ([raw log](https://api.travis-ci.org/v3/job/407463717/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:47:27] travis_fold:start:stage0-remote-test-server
travis_time:start:stage0-remote-test-server
Building stage0 tool remote-test-server (arm-unknown-linux-gnueabihf)
[00:47:27]    Compiling remote-test-server v0.1.0 (file:///checkout/src/tools/remote-test-server)
[00:47:27] error: trait objects without an explicit `dyn` are deprecated
[00:47:27]    --> tools/remote-test-server/src/main.rs:273:22
[00:47:27]     |
[00:47:27] 273 | fn my_copy(src: &mut Read, which: u8, dst: &Mutex<Write>) {
[00:47:27]     |                      ^^^^ help: use `dyn`: `dyn Read`
[00:47:27]     |
[00:47:27]     = note: requested on the command line with `-D bare-trait-objects`
[00:47:27] 
[00:47:27] error: trait objects without an explicit `dyn` are deprecated
[00:47:27]    --> tools/remote-test-server/src/main.rs:273:51
[00:47:27]     |
[00:47:27] 273 | fn my_copy(src: &mut Read, which: u8, dst: &Mutex<Write>) {
[00:47:27]     |                                                   ^^^^^ help: use `dyn`: `dyn Write`
[00:47:27] 
[00:47:27] error: trait objects without an explicit `dyn` are deprecated
[00:47:27]    --> tools/remote-test-server/src/main.rs:293:21
[00:47:27]     |
[00:47:27] 293 | fn read_u32(r: &mut Read) -> u32 {
[00:47:27]     |                     ^^^^ help: use `dyn`: `dyn Read`
[00:47:27] error: aborting due to 3 previous errors
[00:47:27] 
[00:47:27] [RUSTC-TIMING] remote_test_server test:false 0.231
[00:47:27] error: Could not compile `remote-test-server`.
[00:47:27] error: Could not compile `remote-test-server`.
[00:47:27] 
[00:47:27] Caused by:
[00:47:27]   process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustc --crate-name remote_test_server tools/remote-test-server/src/main.rs --color always --error-format json --crate-type bin --emit=dep-info,link -C opt-level=2 -C metadata=7849ff27262ec12d -C extra-filename=-7849ff27262ec12d --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools/arm-unknown-linux-gnueabihf/release/deps --target arm-unknown-linux-gnueabihf -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools/arm-unknown-linux-gnueabihf/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools/release/deps` (exit code: 101)
[00:47:27] expected success, got: exit code: 101
[00:47:27] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test --target arm-unknown-linux-gnueabihf
[00:47:27] Build completed unsuccessfully in 0:44:31
travis_time:end:1eacfb60:start=1532411871651226396,finish=1532414719655088999,duration=2848003862603
---
travis_time:end:0c1f9071:start=1532414720165002242,finish=1532414720173432849,duration=8430607
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0124cf5f
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:066ee9d6
travis_time:start:066ee9d6
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:23613363
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-07-25 01:47 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/407872128) ([raw log](https://api.travis-ci.org/v3/job/407872128/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://files.pythonhosted.org/packages/cc/1a/bb0bc699b37a766736b0c07a7344b1b985deb16870e9d14c75110ae74256/awscli-1.15.64-py2.py3-none-any.whl (1.3MB)
    0% |▎                               | 10kB 11.7MB/s eta 0:00:01
    1% |▌                               | 20kB 1.8MB/s eta 0:00:01
    2% |▊                               | 30kB 2.1MB/s eta 0:00:01
    3% |█                               | 40kB 1.9MB/s eta 0:00:01
---
[00:18:12]    Compiling unwind v0.0.0 (file:///checkout/src/libunwind)
[00:18:17]    Compiling compiler_builtins v0.0.0 (file:///checkout/src/rustc/compiler_builtins_shim)
[00:18:17]    Compiling cmake v0.1.31
[00:18:17]    Compiling alloc_jemalloc v0.0.0 (file:///checkout/src/liballoc_jemalloc)
[00:18:18] error[E0433]: failed to resolve. Did you mean `coresimd::simd`?
[00:18:18]    --> libcore/../stdsimd/coresimd/ppsv/api/from_bits.rs:8:20
[00:18:18]     |
[00:18:18] 8   |               impl ::simd::FromBits<$from> for $to {
[00:18:18]     |                      ^^^^ Did you mean `coresimd::simd`?
[00:18:18]     | 
[00:18:18]    ::: libcore/../stdsimd/coresimd/ppsv/v128.rs:179:1
[00:18:18] 179 | / impl_from_bits!(
[00:18:18] 180 | |     u64x2: u64,
[00:18:18] 181 | |     u64x2_from_bits,
[00:18:18] 181 | |     u64x2_from_bits,
[00:18:18] 182 | |     test_v128 | i64x2,
[00:18:18] 194 | |     m8x16
[00:18:18] 195 | | );
[00:18:18]     | |__- in this macro invocation
[00:18:18] 
[00:18:18] 
[00:18:19] error[E0433]: failed to resolve. Did you mean `coresimd::simd`?
[00:18:19]    --> libcore/../stdsimd/coresimd/ppsv/api/from_bits.rs:8:20
[00:18:19]     |
[00:18:19] 8   |             impl ::simd::FromBits<$from> for $to {
[00:18:19]     |                    ^^^^ Did you mean `coresimd::simd`?
[00:18:19]     | 
[00:18:19]    ::: libcore/../stdsimd/coresimd/ppsv/v128.rs:196:1
[00:18:19]     |
[00:18:19] 196 | from_bits_x86!(u64x2, u64, u64x2_from_bits_x86);
[00:18:19]     | ------------------------------------------------ in this macro invocation
[00:18:19] 
[00:18:19] error[E0433]: failed to resolve. Did you mean `coresimd::simd`?
[00:18:19]    --> libcore/../stdsimd/coresimd/ppsv/api/from_bits.rs:8:20
[00:18:19]     |
[00:18:19] 8   |               impl ::simd::FromBits<$from> for $to {
[00:18:19]     |                      ^^^^ Did you mean `coresimd::simd`?
[00:18:19]     | 
[00:18:19]    ::: libcore/../stdsimd/coresimd/ppsv/v128.rs:199:1
[00:18:19] 199 | / impl_from_bits!(
[00:18:19] 199 | / impl_from_bits!(
[00:18:19] 200 | |     i64x2: i64,
[00:18:19] 201 | |     i64x2_from_bits,
[00:18:19] 202 | |     test_v128 | u64x2,
[00:18:19] 214 | |     m8x16
[00:18:19] 215 | | );
[00:18:19]     | |__- in this macro invocation
[00:18:19] 
[00:18:19] 
[00:18:19] error[E0433]: failed to resolve. Did you mean `coresimd::simd`?
[00:18:19]    --> libcore/../stdsimd/coresimd/ppsv/api/from_bits.rs:8:20
[00:18:19]     |
[00:18:19] 8   |             impl ::simd::FromBits<$from> for $to {
[00:18:19]     |                    ^^^^ Did you mean `coresimd::simd`?
[00:18:19]     | 
[00:18:19]    ::: libcore/../stdsimd/coresimd/ppsv/v128.rs:216:1
[00:18:19]     |
[00:18:19] 216 | from_bits_x86!(i64x2, i64, i64x2_from_bits_x86);
[00:18:19]     | ------------------------------------------------ in this macro invocation
[00:18:19] 
[00:18:19] error[E0433]: failed to resolve. Did you mean `coresimd::simd`?
[00:18:19]    --> libcore/../stdsimd/coresimd/ppsv/api/from_bits.rs:8:20
[00:18:19]     |
[00:18:19] 8   |               impl ::simd::FromBits<$from> for $to {
[00:18:19]     |                      ^^^^ Did you mean `coresimd::simd`?
[00:18:19]     | 
[00:18:19]    ::: libcore/../stdsimd/coresimd/ppsv/v128.rs:219:1
[00:18:19] 219 | / impl_from_bits!(
[00:18:19] 219 | / impl_from_bits!(
[00:18:19] 220 | |     f64x2: f64,
[00:18:19] 221 | |     f64x2_from_bits,
[00:18:19] 222 | |     test_v128 | i64x2,
[00:18:19] 234 | |     m8x16
[00:18:19] 235 | | );
[00:18:19]     | |__- in this macro invocation
[00:18:19] 
[00:18:19] 
[00:18:20] error[E0433]: failed to resolve. Did you mean `coresimd::simd`?
[00:18:20]    --> libcore/../stdsimd/coresimd/ppsv/api/from_bits.rs:8:20
[00:18:20]     |
[00:18:20] 8   |             impl ::simd::FromBits<$from> for $to {
[00:18:20]     |                    ^^^^ Did you mean `coresimd::simd`?
[00:18:20]     | 
[00:18:20]    ::: libcore/../stdsimd/coresimd/ppsv/v128.rs:236:1
[00:18:20]     |
[00:18:20] 236 | from_bits_x86!(f64x2, f64, f64x2_from_bits_x86);
[00:18:20]     | ------------------------------------------------ in this macro invocation
[00:18:20] 
[00:18:20] error[E0433]: failed to resolve. Did you mean `coresimd::simd`?
[00:18:20]    --> libcore/../stdsimd/coresimd/ppsv/api/from_bits.rs:8:20
[00:18:20]     |
[00:18:20] 8   |               impl ::simd::FromBits<$from> for $to {
[00:18:20]     |                      ^^^^ Did you mean `coresimd::simd`?
[00:18:20]     | 
[00:18:20]    ::: libcore/../stdsimd/coresimd/ppsv/v128.rs:239:1
[00:18:20] 239 | / impl_from_bits!(
[00:18:20] 240 | |     u32x4: u32,
[00:18:20] 241 | |     u32x4_from_bits,
[00:18:20] 241 | |     u32x4_from_bits,
[00:18:20] 242 | |     test_v128 | u64x2,
[00:18:20] 254 | |     m8x16
[00:18:20] 255 | | );
[00:18:20]     | |__- in this macro invocation
[00:18:20] 
[00:18:20] 
[00:18:20] error[E0433]: failed to resolve. Did you mean `coresimd::simd`?
[00:18:20]    --> libcore/../stdsimd/coresimd/ppsv/api/from_bits.rs:8:20
[00:18:20]     |
[00:18:20] 8   |             impl ::simd::FromBits<$from> for $to {
[00:18:20]     |                    ^^^^ Did you mean `coresimd::simd`?
[00:18:20]     | 
[00:18:20]    ::: libcore/../stdsimd/coresimd/ppsv/v128.rs:256:1
[00:18:20]     |
[00:18:20] 256 | from_bits_x86!(u32x4, u32, u32x4_from_bits_x86);
[00:18:20]     | ------------------------------------------------ in this macro invocation
[00:18:20] 
[00:18:20] error[E0433]: failed to resolve. Did you mean `coresimd::simd`?
[00:18:20]    --> libcore/../stdsimd/coresimd/ppsv/api/from_bits.rs:8:20
[00:18:20]     |
[00:18:20] 8   |               impl ::simd::FromBits<$from> for $to {
[00:18:20]     |                      ^^^^ Did you mean `coresimd::simd`?
[00:18:20]     | 
[00:18:20]    ::: libcore/../stdsimd/coresimd/ppsv/v128.rs:259:1
[00:18:20] 259 | / impl_from_bits!(
[00:18:20] 259 | / impl_from_bits!(
[00:18:20] 260 | |     i32x4: i32,
[00:18:20] 261 | |     i32x4_from_bits,
[00:18:20] 262 | |     test_v128 | u64x2,
[00:18:20] 274 | |     m8x16
[00:18:20] 275 | | );
[00:18:20]     | |__- in this macro invocation
[00:18:20] 
[00:18:20] 
[00:18:21]    Compiling std v0.0.0 (file:///checkout/src/libstd)
[00:18:21]    Compiling rustc_msan v0.0.0 (file:///checkout/src/librustc_msan)
[00: [...]

2018-07-25 03:17 UTC, ishitatsuyuki commented
r? @kennytm

2018-07-25 03:22 UTC, kennytm commented
@bors r=Mark-Simulacrum,kennytm

2018-07-25 04:52 UTC, kennytm commented
`cargo` is external too.

2018-07-25 05:49 UTC, ishitatsuyuki commented
r? @kennytm

2018-07-26 01:18 UTC, ishitatsuyuki commented on src/bootstrap/tool.rs
> +    is_external_tool: bool,
Hmm, having an enum just representing a bool sounds like tautology. Should I just add a doc comment instead?

2018-07-26 02:36 UTC, Mark-Simulacrum commented on src/bootstrap/tool.rs
> +    is_external_tool: bool,
Enums representing bools are a common an excellent design pattern; the doc comment wouldn't help because the problem is at call sites, not here.

2018-07-26 02:55 UTC, kennytm commented on src/bootstrap/tool.rs
> +    is_external_tool: bool,
If you dislike `Yes, No` you could make it `enum Tool { Normal, External, OptionalExternal }`

2018-07-26 03:37 UTC, ishitatsuyuki commented
r? @Mark-Simulacrum

2018-07-26 14:47 UTC, Mark-Simulacrum commented
Can you rebase this such as to squash 560d8079ec26f2a45ecb80e95d24917025e02104, b29a6fbabcb425f6e238a00946fb1c9869f657e9, 1915cd1dc2d5ea66d322d52958271b8072ec4c97, 7407a788149402039ffbb56aed50de2023652d46, 72e2c00af48ac0c59f5dcae819a6842e8e2029cf, 8646a1714306473011e79e1c1a213928bfa6025f, 66c4dc9769b7ae456fe2960dc5a1e037b2432184, c6d28442e869fa8188314cbb0083cc00b250961e together? Those are all commits just adding `dyn ` and there's no reason for them to be separate, especially as some of them are just fixes to others.

Also, if you can squash the tool-related fixes to rustbuild together that would be good too.

2018-07-27 09:55 UTC, ishitatsuyuki commented
@Mark-Simulacrum These are commits from the PR that I roll up merged. Squashing them will make it lose track of author and the ability to auto close the corresponding PR. See previous discussion.

I'm on a trip until next Tuesday; will not be able to push until then.

2018-07-27 11:48 UTC, Mark-Simulacrum commented
@bors r+

Let's just get this landed.

2018-07-27 16:32 UTC, pietroalbini commented
@bors p=1 (high chance of code rot)

2018-07-27 22:31 UTC, merged