improve diagnostics for tests with custom return values
rust-lang/rust pull request #52453
Opened 2018-07-17 11:04 UTC by srijs

This is an attempt at getting the ball rolling to improve the diagnostics for test functions that return custom `impl Termination` values (see #52436).

An alternative could be to use `eprintln!`, but including this in the panic message felt nicely consistent with how failing test assertions would be reported.

Let me know what you think!

2018-07-17 11:04 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @TimNN (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2018-07-21 12:24 UTC, TimNN requested changes
Thanks for your PR @srijs and sorry for the delay in reviewing this.

I have two minor comments (see inline review), but otherwise this looks good.

2018-07-30 16:51 UTC, pietroalbini commented
Ping from triage @srijs! It's been a while since we heard from you, will you have time to work on this again?

2018-08-03 14:38 UTC, TimNN requested changes
Thanks a lot! Two more style nits, otherwise this is good to go!

2018-08-03 14:38 UTC, TimNN commented on src/libtest/lib.rs
> +        "the test returned a termination value with a non-zero status code ({})\
nit: missing space before the `\`

2018-08-03 14:38 UTC, TimNN commented on src/libtest/lib.rs
> +    assert_eq!(code, 0,
nit (formatting): I believe the official style recommendation would be this:

```rust
assert_eq!(
    code, 0,
    "msg \
     ....",
    code
);

2018-08-11 04:38 UTC, srijs commented
Feedback addressed!

2018-08-14 16:03 UTC, TimNN commented
@bors r+ rollup

2018-08-14 16:03 UTC, TimNN approved these changes

2018-08-15 22:01 UTC, merged