[WIP] Disable landing pads within compiler crates
rust-lang/rust pull request #52471
Opened 2018-07-17 21:16 UTC by Mark-Simulacrum

Generally speaking if the compiler panics we should just emit the ICE
message; since that can be done inside a panic handler there's no real
problem with aborting the process when such a panic occurs in general.

Instead of compiling the world with -Cpanic=abort however we use
-Zno-landing-pads to remain compatible with -Cpanic=unwind crates (e.g.,
proc macros) which want to be linked with unwinding because they use
panics for error handling. It's unclear whether this is simply a
limitation of the panic implementation strategy.

This nets wins of 3-6% on most benchmarks.

I don't think this PR is sufficient to land as-is because there's a few cases where we have `catch_unwind`, notably to print the ICE message and inside libsyntax. I've not attempted to fix/change those places. Primarily posting this so the general idea can be shot down if it's fundamentally not going to work for some reason (though I've not yet determine what that reason could be).

cc @nnethercote 
r? @alexcrichton

2018-07-17 23:38 UTC, nnethercote commented
@Mark-Simulacrum: Nice improvements! What prompted you to try this?

Also, should the code have some comments explaining why these settings were chosen?

2018-07-18 12:48 UTC, Mark-Simulacrum commented
Working on [another project](https://github.com/Mark-Simulacrum/ecap-rs) of mine I was thinking about panic handling so decided to try this -- thought it might net some wins. Initially tried panic=abort but that (which is possibly better than this solution) doesn't quite work today I think, though I didn't investigate in detail.

2018-07-18 18:20 UTC, bjorn3 requested changes

2018-07-18 18:47 UTC, Mark-Simulacrum commented on src/bootstrap/compile.rs
> +    cargo.env("RUSTC_PANIC", "abort");
Ah, I think I forgot it after changing the env var in the other file. I'll run this through official perf just to make sure though.

2018-07-18 18:47 UTC, Mark-Simulacrum commented
@bors try

2018-07-18 21:12 UTC, alexcrichton commented
@rust-timer build 4c9951f5c153fe4ce033b18371beeb6a48e6a728

2018-07-18 21:12 UTC, rust-timer commented
Success: Queued 4c9951f5c153fe4ce033b18371beeb6a48e6a728 with parent 12ed235adc62e63b16bb4f715b143c37a5efa00d, [comparison URL](https://perf.rust-lang.org/compare.html?start=12ed235adc62e63b16bb4f715b143c37a5efa00d&end=4c9951f5c153fe4ce033b18371beeb6a48e6a728).

2018-07-18 21:47 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/405488904) ([raw log](https://api.travis-ci.org/v3/job/405488904/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:start:test_ui
Check compiletest suite=ui mode=ui (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[00:37:46] 
[00:37:46] running 2117 tests
[00:38:03] FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFF.FFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFiF
[00:38:50] FFFF.FFFFFFFFFFFFFFFFFFFFF.FF......FFF..FF.FFF.....F.F.FFFFF.FFFiFFF..F.FFFFFFFFFFFFFFFFFFFFFFFFFFFF
[00:39:48] FFFFFFFFFFFFFFFFFFFFFFFFFFF.F.FFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[00:40:48] FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[00:41:44] FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFF
[00:42:31] FFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FF
[00:43:17] FFFFFFFFFFFFFFFFF.FFFFFFFFFF.FFFFFFFFFFFFFFFFF.F.FFFF.FFFFFFFFFF.FFFFF.FFFFFFFFFFF.F..FFFFFFFFFFFFFF
[00:44:01] FFFFFFFFF.F..FFFFFFFFFFFF..FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[00:44:48] FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFiFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[00:45:31] FFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[00:46:17] FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[00:47:04] FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[00:47:55] FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[00:48:35] FFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF..FFFFFFFFFFF..FFFFFFFFFFFF..F.FFFFFFFFFFFFFF.F..F.F
[00:49:19] F.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.
[00:50:02] FF.FF.....FF..FFFFF...F..FFFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFiFFFFFFF.
[00:50:14] FFFFFFFFFFFFFFFFF.FFFFFF.F.FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFiFFFFFFFFFFFFFFFFFF
[00:50:14] FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[00:50:14] FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[00:50:14] FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[00:50:14] FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFiFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
[00:50:15] FFFFFFFFFFFFiFFFF
[00:50:15] 
[00:50:15] ---- [ui] ui/E0661.rs stdout ----
[00:50:15] 
[00:50:15] 
[00:50:15] error: Error: expected failure status (Some(101)) but received status None.
[00:50:15] status: signal: 6
[00:50:15] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/E0661.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/E0661/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/E0661/auxiliary" "-A" "unused"
[00:50:15] ------------------------------------------
[00:50:15] 
[00:50:15] ------------------------------------------
[00:50:15] stderr:
[00:50:15] stderr:
[00:50:15] ------------------------------------------
[00:50:15] {"message":"output operand constraint lacks '=' or '+'","code":{"code":"E0661","explanation":null},"level":"error","spans":[{"file_name":"/checkout/src/test/ui/E0661.rs","byte_start":543,"byte_end":546,"line_start":17,"line_end":17,"column_start":18,"column_end":21,"is_primary":true,"text":[{"text":"    asm!(\"nop\" : \"r\"(a));","highlight_start":18,"highlight_end":21}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error[E0661]: output operand constraint lacks '=' or '+'\n  --> /checkout/src/test/ui/E0661.rs:17:18\n   |\nLL |     asm!(\"nop\" : \"r\"(a));\n   |                  ^^^\n\n"}
[00:50:15] fatal runtime error: failed to initiate panic, error 5
[00:50:15] ------------------------------------------
[00:50:15] 
[00:50:15] thread '[ui] ui/E0661.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:3139:9
[00:50:15] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:50:15] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:50:15] 
[00:50:15] ---- [ui] ui/E0662.rs stdout ----
[00:50:15] 
[00:50:15] error: Error: expected failure status (Some(101)) but received status None.
[00:50:15] status: signal: 6
[00:50:15] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/E0662.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/E0662/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/E0662/auxiliary" "-A" "unused"
[00:50:15] ------------------------------------------
[00:50:15] 
[00:50:15] ------------------------------------------
[00:50:15] stderr:
[00:50:15] stderr:
[00:50:15] ------------------------------------------
[00:50:15] {"message":"input operand constraint contains '='","code":{"code":"E0662","explanation":null},"level":"error","spans":[{"file_name":"/checkout/src/test/ui/E0662.rs","byte_start":563,"byte_end":570,"line_start":18,"line_end":18,"column_start":12,"column_end":19,"is_primary":true,"text":[{"text":"         : \"=test\"(\"a\") //~ ERROR E0662","highlight_start":12,"highlight_end":19}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error[E0662]: input operand constraint contains '='\n  --> /checkout/src/test/ui/E0662.rs:18:12\n   |\nLL |          : \"=test\"(\"a\") //~ ERROR E0662\n   |            ^^^^^^^\n\n"}
[00:50:15] fatal runtime error: failed to initiate panic, error 5
[00:50:15] ------------------------------------------
[00:50:15] 
[00:50:15] thread '[ui] ui/E0662.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:3139:9
[00:50:15] 
[00:50:15] 
[00:50:15] ---- [ui] ui/E0660.rs stdout ----
[00:50:15] 
[00:50:15] error: Error: expected failure status (Some(101)) but received status None.
[00:50:15] status: signal: 6
[00:50:15] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/E0660.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/E0660/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/E0660/auxiliary" "-A" "unused"
[00:50:15] ------------------------------------------
[00:50:15] 
[00:50:15] ------------------------------------------
[00:50:15] stderr:
[00:50:15] stderr:
[00:50:15] ------------------------------------------
[00:50:15] {"message":"malformed inline assembly","code":{"code":"E0660","explanation":null},"level":"error","spans":[{"file_name":"/checkout/src/test/ui/E0660.rs","byte_start":530,"byte_end":548,"line_start":17,"line_end":17,"column_start":5,"column_end":23,"is_primary":true,"text":[{"text":"    asm!(\"nop\" \"nop\");","highlight_start":5,"highlight_end":23}],"label":null,"suggested_replacement":null,"suggestion_appl [...]

2018-07-19 03:32 UTC, Mark-Simulacrum commented
Hm, official perf is less impressive than my local results (only 3% wins).

I've not investigated the UI failures yet, I'd like to get signoff from relevant folks (perhaps we should FCP compiler team?) before putting much more time into this.

2018-07-19 03:42 UTC, nnethercote commented
> Hm, official perf is less impressive than my local results (only 3% wins).

The breadth of the improvements is impressive, though.

2018-07-19 14:41 UTC, alexcrichton commented
The test failures here are an example of why I think it may be technically infeasible to land this strategy at this time, with the corrected patch now is it still sure that failing rustdoc tests, procedural macros, and compile errors in general all still work?

2018-07-19 15:12 UTC, nikomatsakis commented
I personally think this sounds like a fine thing to do, though I'd prefer if we could do it with `-Cpanic=abort`, but I guess that'd be a lot more work. That said, I'm not sure if it's worth investing a lot of time into it at this point (vs filing an issue and revisiting later), given the relatively minor gains and the sheer number of things in flight due to the Edition.

2018-07-26 14:44 UTC, Mark-Simulacrum commented
I agree that holding off until after the edition and looking at properly doing this via -Cpanic=abort is the best approach here; closing this for the time being.

2018-07-26 14:44 UTC, closed without merging