WIP: Implement try block expressions
rust-lang/rust pull request #52602
Opened 2018-07-22 01:50 UTC by scottmcm

I noticed that `try` wasn't a keyword yet in Rust 2018, so...

This is very much not done yet, but I want travis to help catch my mistakes :slightly_smiling_face: 

cc https://github.com/rust-lang/rust/issues/31436 https://github.com/rust-lang/rust/issues/50412

2018-07-22 01:50 UTC, rust-highfive commented
r? @michaelwoerister

(rust_highfive has picked a reviewer for you, use r? to override)

2018-07-22 06:03 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/406742819) ([raw log](https://api.travis-ci.org/v3/job/406742819/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain

```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-07-22 06:39 UTC, scottmcm commented
Ok, I think this is in good enough shape to get reviewed.  I've never touched most of these parts of the compiler before, so I suspect there are opportunities for improvement in how I did things :upside_down_face:

2018-07-22 11:06 UTC, petrochenkov commented on src/libsyntax_pos/symbol.rs
> +    (51, Try,                "try") // >= 2018 Edition Only
Nit: Keywords are not normally moved into the "used" category until the feature is stable (e.g. `macro`/`yield`/`async` are all "reserved for future use").

2018-07-23 04:47 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/406983277) ([raw log](https://api.travis-ci.org/v3/job/406983277/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:50:33] ....................................................................................................
[00:50:35] ....................................................................................................
[00:50:38] .................................i..................................................................
[00:50:41] ....................................................................................................
[00:50:44] ...........................F..F.....................................................................
[00:50:49] .....................................................................................
[00:50:49] failures:
[00:50:49] 
[00:50:49] ---- [compile-fail] compile-fail/try-block-in-match.rs stdout ----
[00:50:49] ---- [compile-fail] compile-fail/try-block-in-match.rs stdout ----
[00:50:49] 
[00:50:49] error: /checkout/src/test/compile-fail/try-block-in-match.rs:16: unexpected error: '16:11: 16:14: expected expression, found reserved keyword `try`'
[00:50:49] 
[00:50:49] error: /checkout/src/test/compile-fail/try-block-in-match.rs:16: expected error not found: expected expression, found keyword `try`
[00:50:49] error: 1 unexpected errors found, 1 expected errors not found
[00:50:49] status: exit code: 1
[00:50:49] command: "/checkout/obj/build/x86_64-unknown
travis_time:end:12afcad0:start=1532318203408422412,finish=1532321252747076876,duration=3049338654464
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-07-24 00:34 UTC, Centril commented on src/doc/unstable-book/src/language-features/catch-expr.md
> +The `catch_expr` feature adds support for `try` blocks. A `try`
Should probably rename this to `try_expr`?

2018-07-24 12:34 UTC, michaelwoerister commented
r? @nikomatsakis for re-assignment. I don't think I'm the right person to review this.

2018-07-24 20:28 UTC, nikomatsakis approved these changes
Very nice!

2018-07-24 20:45 UTC, nikomatsakis commented
@bors r-

2018-07-24 20:45 UTC, nikomatsakis commented
One question: do we want to provide a kind of smoother path for people using `do catch` today? e.g., a nice error message?

2018-07-24 20:46 UTC, nikomatsakis commented
Or do we just not care :)

2018-07-24 20:49 UTC, Centril commented
@nikomatsakis Here's a sourcegraph query for it, https://sourcegraph.com/search?q=repogroup:crates+case:yes++%5Cbdo%5Cs%2Bcatch%5Cb+max:400

Most of these occurrences are irrelevant and so I think we should not care.

2018-07-24 20:50 UTC, Centril commented
Also; having the feature called `catch_expr` for a `try { .. }` block will be confusing, so let's change that bit  :)

2018-07-25 02:22 UTC, scottmcm commented
@nikomatsakis Well, it was easy, so I just [did it](https://github.com/rust-lang/rust/pull/52602/files#diff-3a305731b50fbd0843e86a9395740eceR16).

@Centril Agreed; switched to `try_blocks`. (The compiler seems to [use `Try` for `?`](https://doc.rust-lang.org/nightly/nightly-rustc/syntax/ast/enum.ExprKind.html#variant.Try) in some places, so I decided for something more explicit than `try_expr`.)

2018-07-25 14:44 UTC, nikomatsakis commented
@bors r+

2018-07-26 22:18 UTC, kennytm commented
@bors r-

Merge conflict with `src/librustc/lib.rs`.

2018-07-27 15:54 UTC, RalfJung commented
@bors r=nikomatsakis

2018-07-28 21:54 UTC, scottmcm commented
[Updated a few tests](https://github.com/rust-lang/rust/pull/52602/commits/d6ae6c4e1ac10584d9e20628dd16c4562972f5df) to work with NLL and the new error messages; please double-check and re-r+.

2018-08-06 19:13 UTC, nikomatsakis requested changes

2018-08-06 19:13 UTC, nikomatsakis commented on src/test/compile-fail/try-block-bad-lifetime.rs
> +        do_something_with(result);
seems fine; I usually just use `drop(result)` for this purpose :)

2018-08-06 19:13 UTC, nikomatsakis commented on src/test/compile-fail/try-block-maybe-bad-lifetime.rs
>  // This test checks that borrows made and returned inside try blocks are properly constrained
really we should make these UI tests, not compile-fail

2018-08-06 19:13 UTC, nikomatsakis commented on src/test/compile-fail/try-block-maybe-bad-lifetime.rs
>  // This test checks that borrows made and returned inside try blocks are properly constrained
feel up for that? Also, I'd prefer a directory named something like `src/test/ui/rfc123-try-block`

2018-08-06 19:13 UTC, nikomatsakis commented on src/test/compile-fail/try-block-maybe-bad-lifetime.rs
>  // This test checks that borrows made and returned inside try blocks are properly constrained
or just `try-block`

2018-08-06 20:03 UTC, Centril commented
It also seems important to this PR to decide what to do with `try!(expr)` in 2018. The question is currently unresolved in #50412. Presumably we should add some tests to ensure the expected behavior once we do decide what we want.

2018-08-06 20:34 UTC, scottmcm commented
@Centril There's definitely more work to do -- such as prohibiting a following `catch` -- but I don't think it needs to be this PR specifically.  This one is pretty well contained to just being a rename right now, and I'd like to keep it that way to separate out the work.

Perhaps it would be worth a separate issue for "`try`-related things that need decisions and/or implementing before the edition", so that it can go in one of the milestones?

2018-08-06 20:40 UTC, Centril commented
@scottmcm  Ah; that's fair enough.

Note to self: On the issue of a following `catch`, I'd also like to make a following `match`, `else`, and `finally` token forbidden. (we could make any following keyword + `finally` + `catch` verboten to be extra-extra-safe).

I think we can track `try`-related-things on #50412. :)

2018-08-06 20:47 UTC, scottmcm commented
Ah, right; I forgot you'd already made a separate issue for it. :+1:

2018-08-09 20:37 UTC, nikomatsakis commented
Well @scottmcm you wanted to wait until EP2 or something, right?

2018-08-09 21:14 UTC, scottmcm commented
@nikomatsakis Yeah, this isn't edition-critical and I suspect it will break toolstate.  I'll make the suggested changes, but not soon -- I'm getting on a plane in a few hours.

2018-08-13 03:53 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/415272826) ([raw log](https://api.travis-ci.org/v3/job/415272826/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:45:49] ....................i...............................................................................
[00:45:52] ...............................i....................................................................
[00:45:55] ....................................................................................................
[00:45:59] ....................................................................................................
 error[E0271]: type mismatch resolving `<std::result::Result<i32, i32> as std::ops::Try>::Ok == &str`
[00:46:05] 
[00:46:05] The actual stderr differed from the expected stderr.
[00:46:05] The actual stderr differed from the expected stderr.
[00:46:05] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/try-block/try-block-bad-type/try-block-bad-type.stderr
[00:46:05] To update references, rerun the tests and pass the `--bless` flag
[00:46:05] To only update this specific test, also pass `--test-args try-block/try-block-bad-type.rs`
[00:46:05] error: 1 errors occurred comparing output.
[00:46:05] status: exit code: 1
[00:46:05] status: exit code: 1
[00:46:05] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/try-block/try-block-bad-type.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/try-block/try-block-bad-type/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--edition" "2018" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/try-block/try-block-bad-type/auxiliary" "-A" "unused"
[00:46:05] ------------------------------------------
[00:46:05] 
[00:46:05] ------------------------------------------
[00:46:05] stderr:
[00:46:05] stderr:
[00:46:05] ------------------------------------------
[00:46:05] {"message":"the trait bound `i32: std::convert::From<&str>` is not satisfied","code":{"code":"E0277","explanation":"\nYou tried to use a type which doesn't implement some trait in a place which\nexpected that trait. Erroneous cthe input type to types that implement Debug.\nfn some_func<T: fmt::Debug>(foo: T) {\n    println!(\"{:?}\", foo);\n}\n\nfn main() {\n    // Calling the method is still fine, as i32 implements Debug.\n    some_func(5i32);\n\n    // This would fail to compile now:\n    // struct WithoutDebug;\n    // some_func(WithoutDebug);\n}\n```\n\nRust only looks at the signature of the called function, as such it must\nalready specify all requirements that will be used for every type parameter.\n"},"level":"error","spans":[{"file_name":"/checkout/src/test/ui/try-block/try-block-bad-type.rs","byte_start":588,"byte_end":596,"line_start":17,"line_end":17,"column_start":9,"column_end":17,"is_primary":true,"text":[{"text":"        Err(\"\")?; //~ ERROR the trait bound `i32: std::convert::From<&str>` is not satisfied","highlight_start":9,"highlight_end":17}],"label":"the trait `std::convert::From<&str>` is not implemented for `i32`","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"the following implementations were found:\n  <i32 as std::convert::From<u8>>\n  <i32 as std::convert::From<i8>>\n  <i32 as std::convert::From<u16>>\n  <i32 as std::convert::From<i16>>\n  <i32 as std::convert::From<bool>>","code":null,"level":"help","spans":[],"children":[],"rendered":null},{"message":"required by `std::convert::From::from`","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":"error[E0277]: the trait bound `i32: std::convert::From<&str>` is not satisfied\n  --> /checkout/src/test/ui/try-block/try-block-bad-type.rs:17:9\n   |\nLL |         Err(\"\")?; //~ ERROR the traitime:start:008683ec
Mon Aug 13 03:53:40 UTC 2018
Mon, 13 Aug 2018 03:53:40 GMT
travis_time:end:008683ec:start=1534132420669870386,finish=1534132420729455432,duration=59585046


The command "date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
" exited with 0.
travis_fold:start:after_failure.1
travis_time:start:0bd6348f
$ sudo tail -n 500 /var/log/syslog
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    0.000000] BRK [0x02213000, 0x02213fff] PGTABLE
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    0.000000] RAMDISK: [mem 0x35614000-0x36b01fff]
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    0.000000] ACPI: Early table checksum verification disabled
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    0.000000] ACPI: RSDP 0x00000000000F27C0 000014 (v00 Google)
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    0.000000] ACPI: RSDT 0x00000000BFFF3430 000038 (v01 Google GOOGRSDT 00000001 GOOG 00000001)
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    0.000000] ACPI: FACP 0x00000000BFFFCF60 0000F4 (v02 Google GOOGFACP 00000001 GOOG 00000001)
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    0.000000] ACPI: DSDT 0x00000000BFFF3470 0017B2 (v01 Google GOOGDSDT 00000001 GOOG 00000001)
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    0.000000] ACPI: FACS 0x092852-ca80-4587-a90a-11a955b512a8 kernel: [    1.140858] SCSI subsystem initialized
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 rsyslogd-2039: Could no open output pipe '/dev/xconsole': No such file or directory [try http://www.rsyslog.com/e/2039 ]
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    1.142615] libata version 3.00 loaded.
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    1.142643] ACPI: bus type USB registered
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    1.143887] usbcore: registered new interface driver usbfs
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    1.145656] usbcore: registered new interface driver hub
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    1.147675] usbcore: registered new device driver usb
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    1.149886] ioremap error for 0xbfffd000-0xc0000000, requested 0x2, got 0x0
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    1.152595] dmi: Firmware registration failed.
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    1.154153] PCI: Using ACPI for IRQ routing
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    1.155885] PCI: pci_cache_line_size set to 64 bytes
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    1.156011] e820: reserve RAM buffer [mem 0x0009fc00-0x0009ffff]
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    1.156013travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    3.376421] hw unit of domain package 2^-0 Joules
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    3.377101] hw unit of domain dram 2^-0 Joules
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    3.377952] Scanning for low memory corruption every 60 seconds
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    3.379781] audit: initializing netlink subsys (disabled)
Aug 13 03:06:33 travis-job-5e892852-ca80-4587-a90a-11a955b512a8 kernel: [    3.381227] audit: type=2000 audit(1534129584.872:1): initialized
Aug 13  [...]

2018-08-19 23:56 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/418024133) ([raw log](https://api.travis-ci.org/v3/job/418024133/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
tidy check
[00:04:40] * 555 error codes
[00:04:40] * highest error code: E0712
[00:04:40] * 222 features
[00:04:41] Stray file with UI testing output: "/checkout/src/test/ui/catch/catch-in-match.stderr"
[00:04:41] Stray file with UI testing output: "/checkout/src/test/ui/catch/catch-maybe-bad-lifetime.stderr"
[00:04:41] Stray file with UI testing output: "/checkout/src/test/ui/catch/catch-in-while.stderr"
[00:04:41] Stray file with UI testing output: "/checkout/src/test/ui/catch/catch-bad-lifetime.nll.stderr"
[00:04:41] Stray file with UI testing output: "/checkout/src/test/ui/catch/catch-opt-init.stderr"
[00:04:41] Stray file with UI testing output: "/checkout/src/test/ui/catch/catch-bad-lifetime.stderr"
[00:04:41] Stray file with UI testing output: "/checkout/src/test/ui/catch/catch-bad-type.stderr"
[00:04:41] Stray file with UI testing output: "/checkout/src/test/ui/catch/catch-opt-init.nll.stderr"
[00:04:41] Stray file with UI testing output: "/checkout/src/test/ui/catch/catch-maybe-bad-lifetime.nll.stderr"
[00:04:41] some tidy checks failed
[00:04:41] 
[00:04:41] 
[00:04:41] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:41] 
[00:04:41] 
[00:04:41] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:41] Build completed unsuccessfully in 0:00:53
[00:04:41] Build completed unsuccessfully in 0:00:53
[00:04:41] make: *** [tidy] Error 1
[00:04:41] Makefile:79: recipe for target 'tidy' failed

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:18f85126
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:02761ba0:start=1534722499155130025,finish=1534722499160892107,duration=5762082
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0a40488b
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:132c4674
travis_time:start:132c4674
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:1150b804
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-08-20 00:34 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/418028626) ([raw log](https://api.travis-ci.org/v3/job/418028626/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:22:46]    Compiling rustc_data_structures v0.0.0 (file:///checkout/src/librustc_data_structures)
[00:22:50]    Compiling arena v0.0.0 (file:///checkout/src/libarena)
[00:22:50]    Compiling syntax_pos v0.0.0 (file:///checkout/src/libsyntax_pos)
[00:22:54]    Compiling rustc_errors v0.0.0 (file:///checkout/src/librustc_errors)
[00:23:01] error: found removed `do catch` syntax
[00:23:01]      |
[00:23:01]      |
[00:23:01] 1761 |             let pat_arg: PResult<'a, _> = do catch {
[00:23:01]      |
[00:23:01]      |
[00:23:01]      = help: Following RFC #2388, the new non-placeholder syntax is `try`
[00:23:01] 
[00:23:02] error: unused import: `DiagnosticId`
[00:23:02]    |
[00:23:02]    |
[00:23:02] 47 | use errors::{self, Applicability, DiagnosticBuilder, DiagnosticId};
[00:23:02]    |
[00:23:02]    = note: `-D unused-imports` implied by `-D warnings`
[00:23:02] 
4-unknown-linux-gnu/stage1
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-08-20 02:17 UTC, scottmcm commented
@nikomatsakis Ok, that was a more complex rebase than expected, but things should be good now.

2018-08-22 18:39 UTC, nikomatsakis approved these changes

2018-08-22 18:39 UTC, nikomatsakis commented
@bors r+

2018-08-23 02:08 UTC, rust-highfive commented
Your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/419455559) ([raw log](https://api.travis-ci.org/v3/job/419455559/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain

```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-08-23 03:09 UTC, kennytm commented
@bors retry 

```
An error occurred while generating the build script.
```

2018-08-23 06:34 UTC, rust-highfive commented
The job `x86_64-gnu-aux` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/419489535) ([raw log](https://api.travis-ci.org/v3/job/419489535/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[01:31:26] 
[01:31:26] testing https://github.com/servo/servo
[01:31:26] Initialized empty Git repository in /checkout/obj/build/ct/servo/.git/
[01:31:26] fatal: Could not parse object '17e97b9320fdb7cdb33bbc5f4d0fde0653bbf2e4'.
[01:31:46] fatal: unable to access 'https://github.com/servo/servo/': Could not resolve host: github.com
[01:31:46] thread 'main' panicked at 'assertion failed: status.success()', tools/cargotest/main.rs:128:13
[01:31:46] 
[01:31:46] 
[01:31:46] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/cargotest" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "/checkout/obj/build/ct"
[01:31:46] expected success, got: exit code: 101
[01:31:46] expected success, got: exit code: 101
[01:31:46] 
[01:31:46] 
[01:31:46] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/test/pretty src/test/run-pass/pretty src/test/run-fail/pretty src/test/run-pass-valgrind/pretty src/test/run-pass-fulldeps/pretty src/test/run-fail-fulldeps/pretty src/tools/cargo src/tools/cargotest
[01:31:46] Build completed unsuccessfully in 0:35:04
[01:31:46] make: *** [check-aux] Error 1
[01:31:46] Makefile:60: recipe for target 'check-aux' failed

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:1aac925a
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:156fb9f1:start=1535005949727505251,finish=1535005949733912231,duration=6406980
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0255de5b
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:00dd4bfc
travis_time:start:00dd4bfc
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:0252de30
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-08-23 06:36 UTC, scottmcm commented
I'm cursed today:

> [01:31:46] fatal: unable to access 'https://github.com/servo/servo/': Could not resolve host: github.com

https://api.travis-ci.org/v3/job/419489535/log.txt

2018-08-23 10:58 UTC, varkor commented
@bors retry

2018-08-23 13:53 UTC, merged

2018-08-24 21:37 UTC, alexcrichton commented
As a heads up, we've got a pretty serious issue which may be a bit of a roadblock for this. Currently the compiler doesn't actually warn about usages of the `try` identifier on the 2015 edition, but that's tracked by https://github.com/rust-lang/rust/issues/53077 and fix for it is at https://github.com/rust-lang/rust/pull/53685. Unfortunately though the primary use of the `try` keyword, the `try!` macro in the standard library, suffers from https://github.com/rust-lang/rust/issues/53686.

For the edition we'll need to have at least some warning for users of the `try!` macro to rustfix into `r#try` or suggest `?`, but currently no warnings are emitted which can make for a difficult edition transition experience. Some eyes and/or thoughts on https://github.com/rust-lang/rust/issues/53686 would be greatly appreciated!