Tweak the raw_identifiers lints in 2018
rust-lang/rust pull request #52722
Opened 2018-07-26 00:36 UTC by alexcrichton

* Enable the `raw_identifiers` feature automatically in the 2018 preview
* Only emit lint warnings if the `raw_identifiers` feature is activated

cc rust-lang/cargo#5783

2018-07-26 00:36 UTC, rust-highfive commented
r? @estebank

(rust_highfive has picked a reviewer for you, use r? to override)

2018-07-26 00:36 UTC, alexcrichton commented
r? @oli-obk

2018-07-26 08:08 UTC, oli-obk requested changes
Do we need a test for this behaviour?

2018-07-26 08:08 UTC, oli-obk commented on src/librustc_lint/builtin.rs
> +            return
We can still lint, we should just not have a suggestion in that case, but simply a note about choosing a different name.

2018-07-26 21:14 UTC, alexcrichton commented
Updated!

2018-07-30 08:16 UTC, oli-obk approved these changes

2018-07-30 08:17 UTC, oli-obk commented
@bors r+

2018-07-30 10:19 UTC, merged