expand the documentation on the `Unpin` trait
rust-lang/rust pull request #53104
Opened 2018-08-06 08:18 UTC by nivkner

provides an overview of the Pin API which the trait is for,
and show how it can be used in making self referencial structs

part of #49150

2018-08-06 08:19 UTC, rust-highfive commented
r? @Mark-Simulacrum

(rust_highfive has picked a reviewer for you, use r? to override)

2018-08-06 10:14 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/412551030) ([raw log](https://api.travis-ci.org/v3/job/412551030/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:43:26] ....................................................................................................
[00:43:28] ....................................................................................................
[00:43:31] ....................................................................................................
[00:43:33] ....................................................................................................
[00:43:36] iiiiiiiii...........................................................................................
[00:43:42] ....................................................................................................
[00:43:45] .....i..............................................................................................
[00:43:48] ..............i.....................................................................................
[00:43:51] ....................................................................................................
---
[01:09:29] travis_fold:end:stage0-linkchecker

[01:09:29] travis_time:end:stage0-linkchecker:start=1533550472595478625,finish=1533550474910704309,duration=2315225684

[01:09:30] std/marker/trait.Unpin.html:22: broken link - alloc/boxed/struct.PinMut.html
[01:09:38] core/marker/trait.Unpin.html:22: broken link - alloc/boxed/struct.PinMut.html
2920804 ./obj
2811796 ./obj/build
2205056 ./obj/build/x86_64-unknown-linux-gnu
792660 ./src
---
147700 ./obj/build/bootstrap/debug/incremental
145140 ./obj/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu
145136 ./obj/build/x86_64-unknown-linux-gnu/stage1-rustc/x86_64-unknown-linux-gnu/release
133276 ./obj/build/bootstrap/debug/incremental/bootstrap-jdsuci5s9dha
133272 ./obj/build/bootstrap/debug/incremental/bootstrap-jdsuci5s9dha/s-f3lhifvg0m-1jpurfj-1zjq8g928qpl7
132792 ./obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-08-06 12:28 UTC, Mark-Simulacrum commented
r? @RalfJung

2018-08-06 15:26 UTC, steveklabnik commented on src/libcore/marker.rs
> +/// A trait that indicates that it is safe to move an object of a type implementing it.
Rustdoc docs really like

```rust
/// A single sentence summary
///
/// Real docs start here...
```

The old code was in this style, this patch throws it out.

2018-08-06 15:28 UTC, steveklabnik requested changes
formatting/capitalization/punctuation nits

Thanks for this!

2018-08-06 15:28 UTC, steveklabnik commented on src/libcore/marker.rs
> +/// # example
This should be `/// # Examples`

2018-08-06 15:28 UTC, steveklabnik commented on src/libcore/marker.rs
> +/// // this is a self referencial struct since the slice field points to the data field.
This

2018-08-06 15:28 UTC, steveklabnik commented on src/libcore/marker.rs
> +/// // we cannot inform the compiler about that with a normal reference,
We

2018-08-06 15:28 UTC, steveklabnik commented on src/libcore/marker.rs
> +/// // instead we use a raw pointer, though one which is known to not be null,
Instead

2018-08-06 15:28 UTC, steveklabnik commented on src/libcore/marker.rs
> +/// // since we know its pointing at the string.
it's

2018-08-06 15:28 UTC, steveklabnik commented on src/libcore/marker.rs
> +///     // to ensure the data doesn't move when the function returns,
To

2018-08-06 15:28 UTC, steveklabnik commented on src/libcore/marker.rs
> +///     // and the only way to access it would be through a pointer to it
needs a period at the end

2018-08-06 15:28 UTC, steveklabnik commented on src/libcore/marker.rs
> +/// // the pointer should point to the correct location,
The

2018-08-06 15:28 UTC, steveklabnik commented on src/libcore/marker.rs
> +/// // meanwhile, we are free to move the pointer around
Meanwhile, and a period at the end

2018-08-06 15:28 UTC, steveklabnik commented on src/libcore/marker.rs
> +/// // now the only way to access to data (safely) is immutably,
Now

2018-08-07 11:55 UTC, RalfJung commented
I disagree with the changed introduction: `Unpin` is *not* about moving (in general). That's why it is called `Unpin`, not `Move`. Rust still does not have truly "immovable types": if you have `x: T`, you can still do `let y = Box::new(x)` to move `x` around, for any `T`. In this sense (which is the only sense the compiler knows about), all types are safe to move, always.
`Unpin` is about *moving after being pinned*. It cannot be explained without explaining pinning. The proposed documentation first creates the wrong frame of mind and then later has to correct for this: "[`Unpin` does not] change the behavior of the compiler around moves".


However, I think the example is very useful. :) Just the high-level structure needs some changes. And probably `Unpin` is not the best place to start. The plan in https://github.com/rust-lang/rust/issues/49150 was to have a `std::pin` module and explain the gist of pinning there; `Unpin` can then build on top of that. Your example would probably fit better with that module-level documentation.

If you want to help push pinning over the stabilization line, I think that a good place to start: Having a central location (the `std::pin` module) where pinning is described, and then connect that with `Unpin`, `PinMut` and `PinBox`, respectively. However, I am not sure if @withoutboats or someone else already plans to do that, so I suggest you coordinate in https://github.com/rust-lang/rust/issues/49150.

2018-08-13 19:08 UTC, RalfJung commented on src/libcore/marker.rs
> +/// by controlling the behavior of special pointers types like [`PinMut`],
"pointer types" (spurious "s")

2018-08-13 19:09 UTC, RalfJung commented on src/libcore/marker.rs
> +/// which "pin" the type in place by wrapping it in a type which can only be dereferenced immutably.
Does the "by ..." part help? It doesn't really explain anything, does it?

Maybe just link to the PinMut docs. Or maybe say something along the lines of "by not allowing it to be moved out e.g. through mutable references (unless `T: Unpin`)".

2018-08-13 19:10 UTC, RalfJung commented on src/libcore/marker.rs
> +/// which then allows it to move out of said pointers with functions such as [`swap`].
The remark to `swap` is a bit mysterious. Maybe add an example?

2018-08-13 19:10 UTC, RalfJung commented
LGTM! Just some minor comments.

2018-08-17 16:29 UTC, RalfJung commented on src/libcore/marker.rs
> +/// which "pin" the type in place by not allowing it to be moved out via mutable references.
I would remove the "via" prat or make it a "for example" -- after all, `PinMut` prevents *all ways* to move something out. It doesn't *just* prevent moving out via `&mut`.

2018-08-17 16:30 UTC, RalfJung commented on src/libcore/marker.rs
> +/// replace(&mut *pinned_string, "other".to_string());
I'd add a comment in the code here saying that the `&mut *` is where we make use of the `Unpin`

2018-08-21 09:36 UTC, RalfJung commented
Awesome, thanks!

@bors r+

2018-08-21 09:37 UTC, RalfJung commented
@bors p=rollup

2018-08-21 09:38 UTC, RalfJung commented
@bors r+ rollup

2018-08-21 09:41 UTC, kennytm commented
@bors rollup

2018-08-21 18:16 UTC, merged