Updated core/macros.rs to note it works in a no_std environment.
rust-lang/rust pull request #53299
Opened 2018-08-13 01:00 UTC by MagnumOpus21

Fixes #45797 
This PR updates the documentation of `write!` to note it works in a `no_std` environment, and adds an
example to showcase this. In a `no_std` environment, the author of the code is responsible for the
implementation of the `Write` trait. This example will work out of the box with `no_std`, but the
implementation of `Write` is expected to be provided by the user.

r? @steveklabnik

2018-08-13 01:00 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @steveklabnik (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2018-08-13 01:15 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/415250849) ([raw log](https://api.travis-ci.org/v3/job/415250849/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain

[00:04:03] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:04:03] tidy error: /checkout/src/libcore/macros.rs:353: trailing whitespace
[00:04:03] tidy error: /checkout/src/libcore/macros.rs: missing trailing newline
[00:04:04] some tidy checks failed
[00:04:04] 
[00:04:04] 
[00:04:04] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:04] 
[00:04:04] 
[00:04:04] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:04] Build completed unsuccessfully in 0:00:50
[00:04:04] Build completed unsuccessfully in 0:00:50
[00:04:04] Makefile:79: recipe for target 'tidy' failed
[00:04:04] make: *** [tidy] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:201a0834
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
The command "date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
" exited with 0.
travis_fold:start:after_failure.1
travis_time:start:00fdff1b
$ sudo tail -n 500 /var/log/syslog
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] BRK [0x02213000, 0x02213fff] PGTABLE
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] RAMDISK: [mem 0x35614000-0x36b01fff]
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] ACPI: Early table checksum verification disabled
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] ACPI: RSDP 0x00000000000F27C0 000014 (v00 Google)
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] ACPI: RSDT 0x00000000BFFF3430 000038 (v01 Google GOOGRSDT 00000001 GOOG 00000001)
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] ACPI: FACP 0x00000000BFFFCF60 0000F4 (v02 Google GOOGFACP 00000001 GOOG 00000001)
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] ACPI: DSDT 0x00000000BFFF3470 0017B2 (v01 Google GOOGDSDT 00000001 GOOG 00000001)
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] ACPI: FACS 0x00000000BFFFCF00 000040
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] ACPI: FACS 0x00000000BFFFCF00 000040
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] ACPI: SSDT 0x00000000BFFF65F0 00690D (v01 Google GOOGSSDT 00000001 GOOG 00000001)
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] ACPI: APIC 0x00000000BFFF5D10 000086 (v01 Google GOOGAPIC 00000001 GOOG 00000001)
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] ACPI: WAET 0x00000000BFFF5CE0 000028 (v01 Google GOOGWAET 00000001 GOOG 00000001)
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] ACPI: SRAT 0x00000000BFFF4C30 0000E8 (v01 Google GOOGSRAT 00000001 GOOG 00000001)
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] ACPI: Local APIC address 0xfee00000
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] SRAT: PXM 0 -> APIC 0x00 -> Node 0
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] SRAT: PXM 0 -> APIC 0x01 -> Node 0
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] SRAT: PXM 0 -> APIC 0x02 -> Node 0
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] SRAT: PXM 0 -> APIC 0x03 -> Node 0
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] SRAT: Node 0 PXM 0 [mem 0x00000000-0x0009ffff]
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] SRAT: Node 0 PXM 0 [mem 0x00100000-0xbfffffff]
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] SRAT: Node 0 PXM 0 [mem 0x100000000-0x3ffffffff]
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] NUMA: Node 0 [mem 0x00000000-0x0009ffff] + [mem 0x00100000-0xbfffffff] -> [mem 0x00000000-0xbfffffff]
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] NUMA: Node 0 [mem 0x00000000-0xbfffffff] + [mem 0x100000000-0x3ffffffff] -> [mem 0x00000000-0x3ffffffff]
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] NODE_DATA(0) allocated [mem 0x3ffff9000-0x3ffffdfff]
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] kvm-clock: Using msrs 4b564d01 and 4b564d00
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] kvm-clock: cpu 0, msr 3:ffff1001, primary cpu clock
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] kvm-clock: using sched offset of 1732469395 cycles
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] clocksource: kvm-clock: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] Zone ranges:
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000]   DMA      [mem 0x0000000000001000-0x0000000000ffffff]
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000]   DMA32    [mem 0x0000000001000000-0x00000000ffffffff]
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000]   Normal   [mem 0x0000000100000000-0x00000003ffffffff]
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000]   Device   empty
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] Movable zone start for each node
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] Early memory node ranges
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000]   node   0: [mem 0x0000000000001000-0x000000000009efff]
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000]   node   0: [mem 0x0000000000100000-0x00000000bfff2fff]
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000]   node   0: [mem 0x0000000100000000-0x00000003ffffffff]
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] Initmem setup node 0 [mem 0x0000000000001000-0x00000003ffffffff]
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000] On node 0 totalpages: 3932049
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000]   DMA zone: 64 pages used for memmap
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000]   DMA zone: 21 pages reserved
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000]   DMA zone: 3998 pages, LIFO batch:0
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000]   DMA32 zone: 12224 pages used for memmap
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000]   DMA32 zone: 782323 pages, LIFO batch:31
Aug 13 01:00:56 travis-job-4d7490df-67b1-4ee4-a477-1e31260c3f1c kernel: [    0.000000]   Normal zone: 49152 pages used for memmap
Au [...]

2018-08-13 02:02 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/415259208) ([raw log](https://api.travis-ci.org/v3/job/415259208/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain

[00:04:00] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:04:00] tidy error: /checkout/src/libcore/macros.rs: missing trailing newline
[00:04:02] some tidy checks failed
[00:04:02] 
[00:04:02] 
[00:04:02] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:02] 
[00:04:02] 
[00:04:02] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:02] Build completed unsuccessfully in 0:00:52
[00:04:02] Build completed unsuccessfully in 0:00:52
[00:04:02] Makefile:79: recipe for target 'tidy' failed
[00:04:02] make: *** [tidy] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:061d0e29
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
The command "date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
" exited with 0.
travis_fold:start:after_failure.1
travis_time:start:264b347e
$ sudo tail -n 500 /var/log/syslog
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] BRK [0x02213000, 0x02213fff] PGTABLE
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] RAMDISK: [mem 0x35614000-0x36b01fff]
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] ACPI: Early table checksum verification disabled
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] ACPI: RSDP 0x00000000000F27C0 000014 (v00 Google)
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] ACPI: RSDT 0x00000000BFFF3430 000038 (v01 Google GOOGRSDT 00000001 GOOG 00000001)
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] ACPI: FACP 0x00000000BFFFCF60 0000F4 (v02 Google GOOGFACP 00000001 GOOG 00000001)
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] ACPI: DSDT 0x00000000BFFF3470 0017B2 (v01 Google GOOGDSDT 00000001 GOOG 00000001)
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] ACPI: FACS 0x00000000BFFFCF00 000040
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] ACPI: FACS 0x00000000BFFFCF00 000040
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] ACPI: SSDT 0x00000000BFFF65F0 00690D (v01 Google GOOGSSDT 00000001 GOOG 00000001)
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] ACPI: APIC 0x00000000BFFF5D10 000086 (v01 Google GOOGAPIC 00000001 GOOG 00000001)
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] ACPI: WAET 0x00000000BFFF5CE0 000028 (v01 Google GOOGWAET 00000001 GOOG 00000001)
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] ACPI: SRAT 0x00000000BFFF4C30 0000E8 (v01 Google GOOGSRAT 00000001 GOOG 00000001)
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] ACPI: Local APIC address 0xfee00000
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] SRAT: PXM 0 -> APIC 0x00 -> Node 0
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] SRAT: PXM 0 -> APIC 0x01 -> Node 0
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] SRAT: PXM 0 -> APIC 0x02 -> Node 0
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] SRAT: PXM 0 -> APIC 0x03 -> Node 0
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] SRAT: Node 0 PXM 0 [mem 0x00000000-0x0009ffff]
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] SRAT: Node 0 PXM 0 [mem 0x00100000-0xbfffffff]
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] SRAT: Node 0 PXM 0 [mem 0x100000000-0x3ffffffff]
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] NUMA: Node 0 [mem 0x00000000-0x0009ffff] + [mem 0x00100000-0xbfffffff] -> [mem 0x00000000-0xbfffffff]
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] NUMA: Node 0 [mem 0x00000000-0xbfffffff] + [mem 0x100000000-0x3ffffffff] -> [mem 0x00000000-0x3ffffffff]
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] NODE_DATA(0) allocated [mem 0x3ffff9000-0x3ffffdfff]
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] kvm-clock: Using msrs 4b564d01 and 4b564d00
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] kvm-clock: cpu 0, msr 3:ffff1001, primary cpu clock
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] kvm-clock: using sched offset of 1774955375 cycles
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] clocksource: kvm-clock: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] Zone ranges:
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000]   DMA      [mem 0x0000000000001000-0x0000000000ffffff]
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000]   DMA32    [mem 0x0000000001000000-0x00000000ffffffff]
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000]   Normal   [mem 0x0000000100000000-0x00000003ffffffff]
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000]   Device   empty
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] Movable zone start for each node
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] Early memory node ranges
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000]   node   0: [mem 0x0000000000001000-0x000000000009efff]
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000]   node   0: [mem 0x0000000000100000-0x00000000bfff2fff]
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000]   node   0: [mem 0x0000000100000000-0x00000003ffffffff]
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] Initmem setup node 0 [mem 0x0000000000001000-0x00000003ffffffff]
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000] On node 0 totalpages: 3932049
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000]   DMA zone: 64 pages used for memmap
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000]   DMA zone: 21 pages reserved
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000]   DMA zone: 3998 pages, LIFO batch:0
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000]   DMA32 zone: 12224 pages used for memmap
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000]   DMA32 zone: 782323 pages, LIFO batch:31
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000000]   Normal zone: 49152 pages used for memmap
Aug 13 01:48:43 travis-job-bbac92d9-b320-42dd-9e86-ed0781424c22 kernel: [    0.000 [...]

2018-08-13 03:40 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/415264719) ([raw log](https://api.travis-ci.org/v3/job/415264719/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:59:00] ....................................................................................................
[00:59:02] ....................................................................................................
[00:59:05] ....................................................................................................
[00:59:08] ....................................................................................................
[00:59:11] ...............iiiiiiiii............................................................................
[00:59:17] ....................................................................................................
[00:59:21] .....................i..............................................................................
[00:59:24] ................................i...................................................................
[00:59:27] ....................................................................................................
---
[01:16:03] running 2121 tests
[01:16:11] ....................................................................................................
[01:16:20] ....................................................................................................
[01:16:30] ....................................................................................................
[01:16:39] ...................................i.......................................................F........
[01:16:54] ....................................................................................................
[01:17:02] ....................................................................................................
[01:17:10] ....................................................................................................
[01:17:17] ....................................................................................................
---
The command "date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
" exited with 0.
travis_fold:start:after_failure.1
travis_time:start:005d8782
$ sudo tail -n 500 /var/log/syslog
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] Scanning 1 areas for low memory corruption
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] Base memory trampoline at [ffff880000099000] 99000 size 24576
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] Using GB pages for direct mapping
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] BRK [0x02211000, 0x02211fff] PGTABLE
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] BRK [0x02212000, 0x02212fff] PGTABLE
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] BRK [0x02213000, 0x02213fff] PGTABLE
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] RAMDISK: [mem 0x35614000-0x36b01fff]
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-aOOG 00000001)
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] ACPI: Local APIC address 0xfee00000
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] SRAT: PXM 0 -> APIC 0x00 -> Node 0
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] SRAT: PXM 0 -> APIC 0x01 -> Node 0
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] SRAT: PXM 0 -> APIC 0x02 -> Node 0
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] SRAT: PXM 0 -> APIC 0x03 -> Node 0
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] SRAT: Node 0 PXM 0 [mem 0x00000000-0x0009ffff]
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] SRAT: Node 0 PXM 0 [mem 0x00100000-0xbfffffff]
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] SRAT: Node 0 PXM 0 [mem 0x100000000-0x3ffffffff]
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] NUMA: Node 0 [mem 0x00000000-0x0009ffff] + [mem 0x00100000-0xbfffffff] -> [mem 0x00000000-0xbfffffff]
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] NUMA: Node 0 [mem 0x00000000-0xbfffffff] + [mem 0x100000000-0x3ffffffff] -> [mem 0x00000000-0x3ffffffff]
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] NODE_DATA(0) allocated [mem 0x3ffff9000-0x3ffffdfff]
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] kvm-ACPI: LAPIC_NMI (acpi_id[0xff] dfl dfl lint[0x1])
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] IOAPIC[0]: apic_id 0, version 17, address 0xfec00000, GSI 0-23
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 5 global_irq 5 high level)
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 9 global_irq 9 high level)
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 10 global_irq 10 high level)
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 11 global_irq 11 high level)
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] ACPI: IRQ5 used by override.
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] ACPI: IRQ9 used by override.
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] ACPI: IRQ10 used by override.
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] ACPI: IRQ11 used by override.
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] Using ACPI (MADT) for SMP configuration information
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] smpboot: Allowing 4 CPUs, 0 hotplug CPUs
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] PM: Registered nosave memory: [mem 0x00000000-0x00000fff]
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] PM: Registered nosave memory: [mem 0x0009f000-0x0009ffff]
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] PM: Registered nosave memory: [mem 0x000a0000-0x000effff]
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] PM: Registered nosave memory: [mem 0x000f0000-0x000fffff]
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] PM: Registered nosave memory: [mem 0xbfff3000-0xbfffffff]
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] PM: Registered nosave memory: [mem 0xc0000000-0xfffbbfff]
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] PM: Registered nosave memory: [mem 0xfffbc000-0xffffffff]
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] e820: [mem 0xc0000000-0xfffbbfff] available for PCI devices
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kernel: [    0.000000] Booting paravirtualized kernel on KVM
Aug 13 02:18:22 travis-job-01b43bce-0dec-431e-a479-4f2457a10e2c kerne [...]

2018-08-20 19:45 UTC, steveklabnik requested changes
This is great! Just one small change. Sorry that it took me a while to get back to you; rustconf made everything tough for a bit.

2018-08-20 19:45 UTC, steveklabnik commented on src/libcore/macros.rs
> +/// Note : This macro can be used in no_std setups as well
can you remove the space before the `:` please?

and `no_std` needs backticks, here and on the next line

2018-08-20 19:57 UTC, MagnumOpus21 commented
Hey, no problem. Guessed as much, with regards to your absence. I was following Rustconf too. It was amazing. Will finish the requested changes by tomorrow.

2018-08-24 12:41 UTC, MagnumOpus21 commented
@steveklabnik Does the PR look okay to you now?

2018-08-28 17:10 UTC, TimNN commented
Ping from triage @steveklabnik  / @rust-lang/docs: This PR requires your review.

2018-08-28 18:34 UTC, GuillaumeGomez commented on src/libcore/macros.rs
> +///  write!(&mut m, "Hello World").expect("Not written");
Please remove the extra whitespace at the beginning of all your code examples (1 is enough).

2018-08-28 18:34 UTC, GuillaumeGomez commented on src/libcore/macros.rs
> +///  struct Example{
Why not just `struct Example;`?

2018-08-28 18:34 UTC, GuillaumeGomez commented on src/libcore/macros.rs
> +///  impl Write for Example{
Please add a whitespace before `{`.

2018-09-04 18:15 UTC, TimNN commented
Ping from triage @MagnumOpus21: Some changes have been requested to your PR.

2018-09-04 19:35 UTC, MagnumOpus21 commented
@TimNN Give me a day to push the changes

2018-09-05 15:53 UTC, steveklabnik approved these changes
Thanks!

2018-09-05 15:53 UTC, steveklabnik commented
@bors: r+ rollup

2018-09-07 15:14 UTC, merged