Add doc examples for std::alloc::{alloc,alloc_zeroed}.
rust-lang/rust pull request #53344
Opened 2018-08-14 12:37 UTC by frewsxcv

2018-08-14 12:38 UTC, frewsxcv commented
r? @rust-lang/docs

2018-08-14 12:46 UTC, GuillaumeGomez commented
Thanks!

r=me once CI is ok.

2018-08-14 13:33 UTC, ollie27 requested changes

2018-08-14 13:33 UTC, ollie27 commented on src/liballoc/alloc.rs
> +///     let layout = Layout::from_size_align(2, 1).unwrap();
`u16` generally has an alignment of 2 not 1. Using `Layout::new::<u16>()` would be better here though.

2018-08-14 13:33 UTC, ollie27 commented on src/liballoc/alloc.rs
> +///     let layout = Layout::from_size_align(2, 1).unwrap();
Again, this should be `Layout::new::<u16>()`.

2018-08-14 13:33 UTC, ollie27 commented on src/liballoc/alloc.rs
> +///     println!("Pointer {:p} has data: {:b}", ptr, *(ptr as *mut u16));
This is reading uninitialised memory which is Undefined Behaviour. I suggest writing a value to it first and then reading that value back.

2018-08-15 01:40 UTC, frewsxcv commented
@ollie27 Thanks for the feedback! Comments addressed in the latest force push

2018-08-15 17:17 UTC, ollie27 commented
Looks good now.

@bors r+ rollup

2018-08-15 22:02 UTC, merged