resolve: Some macro resolution refactoring
rust-lang/rust pull request #53471
Opened 2018-08-18 12:28 UTC by petrochenkov

The last commit also fixes https://github.com/rust-lang/rust/issues/53269 by not using `def_id()` on `Def::Err`.

2018-08-18 12:28 UTC, rust-highfive commented
r? @oli-obk

(rust_highfive has picked a reviewer for you, use r? to override)

2018-08-20 08:28 UTC, oli-obk requested changes

2018-08-20 08:28 UTC, oli-obk commented on src/test/ui/imports/issue-53269.stderr
> +error[E0601]: `main` function not found in crate `issue_53269`
Please remove the noise by adding a `main` function

2018-08-20 08:28 UTC, oli-obk commented on src/test/ui/imports/shadow_builtin_macros.stderr
> +note: `panic` could also refer to the macro imported here
This refers to "here", but there's nothing shown

2018-08-20 08:28 UTC, oli-obk commented on src/librustc_resolve/macros.rs
> +    crate fn resolve_lexical_macro_path_segment(&mut self,
change to block indent to reduce future churn and return type breakup

2018-08-20 22:47 UTC, petrochenkov commented
Updated.

2018-08-21 08:38 UTC, oli-obk approved these changes

2018-08-21 08:39 UTC, oli-obk commented
@bors r+

2018-08-21 22:48 UTC, merged