[WIP] Fix evaluation overflow
rust-lang/rust pull request #53687
Opened 2018-08-24 22:36 UTC by GuillaumeGomez

Fixes #52873.

Currently, it fails to evaluate [this code](https://docs.rs/typenum/1.10.0/src/typenum/uint.rs.html#1023-1031). By replacing this line, instead of a bug we get a nice infinite recursion:

```
error[E0275]: overflow evaluating the requirement `_: core::marker::Sized`
  |
  = help: consider adding a `#![recursion_limit="128"]` attribute to your crate
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<_, _>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<uint::UInt<_, _>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>, bit::B0>>` for `uint::UTerm`
  = note: required because of the requirements on the impl of `private::PrivatePow<uint::UInt<uint::UTerm, bit::B1>, uint::UInt<uint::UInt<uint: [...]

2018-08-24 22:37 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2018-08-25 21:42 UTC, GuillaumeGomez commented
@nikomatsakis I'll need your help on this one (@eddyb said you were the one to ask for)

2018-08-27 20:13 UTC, nikomatsakis requested changes

2018-08-27 20:13 UTC, nikomatsakis commented on src/librustc/traits/structural_impls.rs
> -            super::Overflow => bug!(), // FIXME: ape ConstEvalFailure?
Hmm, I'm .. not entirely sure why this was `bug!` to begin with. It seems like it could just be `Some(super::Overflow)`, instead?

2018-08-28 22:17 UTC, GuillaumeGomez commented
@nikomatsakis I made the replacement, and as expected: it still fails at the same place but with the following error message:

```
Overflow should be caught earlier in standard query mode: OverflowError
```

2018-08-29 20:42 UTC, nikomatsakis commented
hmm.

2018-09-04 08:48 UTC, pietroalbini commented
Ping @nikomatsakis @GuillaumeGomez! 1.29 is going to be released in a bit more than a week!

2018-09-06 14:43 UTC, nikomatsakis commented
@GuillaumeGomez I was waiting on you to minimize a test case =)

2018-09-06 14:44 UTC, nikomatsakis commented
Seems like we miscommunicated!

2018-09-06 18:49 UTC, GuillaumeGomez commented
Woups, indeed, sorry about that!

2018-09-06 22:13 UTC, GuillaumeGomez commented
@nikomatsakis After a long try, it seems that it comes more from the number of possibilities than anything specific. With this small sample of code, it works as expected:

```rust
use std::marker::PhantomData;

pub trait Unsigned {}

pub trait PrivatePow<Y, N> {
    type Output;
}

pub type PrivatePowOut<A, Y, N> = <A as PrivatePow<Y, N>>::Output;

pub trait Pow<N> {
    type Output;

    fn powi(self, x: N) -> Self::Output;
}

pub struct UTerm;
pub struct B1;
pub struct UInt<U, B> {
    _marker: PhantomData<(U, B)>,
}

pub type U1 = UInt<UTerm, B1>;

impl<X: Unsigned, N: Unsigned> Pow<N> for X
where
    X: PrivatePow<U1, N>,
{
        type Output = PrivatePowOut<X, U1, N>;
        fn powi(self, _: N) -> Self::Output {
            unsafe { ::core::mem::uninitialized() }
        }
}
```

Adding a few more types matching the blanket impl will certainly allow to get the ICE again but couldn't find how much exactly...

2018-09-07 14:44 UTC, pietroalbini commented
FYI, beta->stable promotion should happen on Monday, so if we want to get the regression fixed we need to ideally get this landed on master and approved for backport by Sunday.

2018-09-10 01:33 UTC, Mark-Simulacrum commented
@nikomatsakis @GuillaumeGomez @rust-lang/rustdoc This is highly likely to slip into the 1.29 release at this point unless we can get an implementation and review in the next ~12-15 hours. Is that acceptable? I'm not sure how serious this issue is.

2018-09-10 02:08 UTC, QuietMisdreavus commented
If the bug is happening while evaluating blanket impls, the solution for beta is to disable blanket impls. That buys us another release to get this sorted properly.

2018-09-10 02:16 UTC, QuietMisdreavus commented
I will likely go to sleep before my build can finish, so if someone wants to beat me to it, blanket impls can be disabled on beta by commenting/removing [this line](https://github.com/rust-lang/rust/blob/edfc72bc740c09c01019e4afccf0d145be702460/src/librustdoc/clean/auto_trait.rs#L265) (and possibly the related `get_blanket_impls` function if it complains about dead code). Then make sure the ICE doesn't occur when documenting `typenum`.

2018-09-13 14:30 UTC, pietroalbini commented
This was already backported in https://github.com/rust-lang/rust/pull/54104, FYI.

2018-09-13 14:34 UTC, QuietMisdreavus commented
@pietroalbini called it, I wrote the "quick and dirty" patch for beta and it was able to get it merged in before it was promoted to today's release.

2018-09-13 14:45 UTC, eddyb commented
To be clear, what was backported is *not* a tentative fix, but rather disabling the feature that *still* needs to be fixed, so people don't get ICEs, the feature is just "delayed" for another release cycle?

2018-09-13 14:52 UTC, QuietMisdreavus commented
@eddyb Correct. As the feature had not landed on stable yet, i "delayed its introduction" by removing it from the beta branch as it was being promoted to stable.

2018-09-13 19:59 UTC, nikomatsakis commented
Closing in favor of https://github.com/rust-lang/rust/pull/54199

2018-09-13 19:59 UTC, closed without merging