Add regression test for issue #52060
rust-lang/rust pull request #53790
Opened 2018-08-29 16:14 UTC by zilbuz

Fix #52060

2018-08-29 16:15 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2018-08-29 16:15 UTC, zilbuz commented
I put the test in `compile-fail`, let me know if I should move it to another folder.

2018-08-29 16:29 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/422148506) ([raw log](https://api.travis-ci.org/v3/job/422148506/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:04:28] tidy error: /checkout/src/test/compile-fail/issue-52060.rs:4: trailing whitespace
[00:04:29] some tidy checks failed
[00:04:29] 
[00:04:29] 
[00:04:29] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:29] 
[00:04:29] 
[00:04:29] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:29] Build completed unsuccessfully in 0:00:50
[00:04:29] Build completed unsuccessfully in 0:00:50
[00:04:29] make: *** [tidy] Error 1
[00:04:29] Makefile:79: recipe for target 'tidy' failed

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:35d28668
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:1dd7032b:start=1535559650028197900,finish=1535559650037190454,duration=8992554
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:051126de
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:22185110
travis_time:start:22185110
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:1313d41a
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-08-29 20:01 UTC, nikomatsakis requested changes
=)

2018-08-29 20:01 UTC, nikomatsakis commented on src/test/compile-fail/issue-52060.rs
> +// Regression test for https://github.com/rust-lang/rust/issues/52060
Great! Can you move this to `src/test/ui/issues`, though? We're not really using `compile-fail` anymore (though we haven't fully killed it yet)

2018-08-30 18:43 UTC, nikomatsakis commented
@bors r+ rollup

2018-09-01 18:08 UTC, merged