Remove OneVector, increase related SmallVec capacities
rust-lang/rust pull request #53824
Opened 2018-08-30 14:34 UTC by ljedrz

Removes the `OneVector` type alias (equivalent to `SmallVec<[T; 1]>`); it is used in scenarios where the capacity of 1 is often exceeded, which might be nullifying the performance wins (due to spilling to the heap) expected when using `SmallVec` instead of `Vec`.

The numbers I used in this PR are very rough estimates - it would probably be a good idea to adjust some/all of them, which is what this proposal is all about.

It might be a good idea to additionally create some local type aliases for the `SmallVec`s in the `Folder` trait, as they are repeated in quite a few spots; I'd be happy to apply this sort of adjustments.

2018-08-30 14:34 UTC, rust-highfive commented
r? @eddyb

(rust_highfive has picked a reviewer for you, use r? to override)

2018-08-30 15:36 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/422589248) ([raw log](https://api.travis-ci.org/v3/job/422589248/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:48:07] ....................................................................................................
[00:48:10] ....................................................................................................
[00:48:13] ...........i........................................................................................
[00:48:16] ....................................................................................................
[00:48:18] ............................................................iiiiiiiii...............................
[00:48:24] ....................................................................................................
[00:48:28] ....................................................................................................
[00:48:30] ........................................i...........................................................
[00:48:33] ..........................................................................................i.i..ii...
---
travis_time:start:test_run-pass-fulldeps
Check compiletest suite=run-pass-fulldeps mode=run-pass (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[00:56:21] 
[00:56:21] running 96 tests
[00:58:08] .................F...............................................test [run-pass] run-pass-fulldeps/myriad-closures.rs has been running for over 60 seconds
[00:59:32] failures:
[00:59:32] 
[00:59:32] ---- [run-pass] run-pass-fulldeps/issue-16723.rs stdout ----
[00:59:32] 
[00:59:32] 
[00:59:32] error: auxiliary build of "/checkout/src/test/run-pass-fulldeps/auxiliary/issue-16723.rs" failed to compile: 
[00:59:32] status: exit code: 1
[00:59:32] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/run-pass-fulldeps/auxiliary/issue-16723.rs" "--target=x86_64-unknown-linux-gnu" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass-fulldeps/issue-16723/auxiliary" "-Crpath" "-O" "-Zunstable-options" "--crate-type" "dylib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass-fulldeps/issue-16723/auxiliary"
[00:59:32] ------------------------------------------
[00:59:32] 
[00:59:32] ------------------------------------------
[00:59:32] stderr:
[00:59:32] stderr:
[00:59:32] ------------------------------------------
[00:59:32] error: incorrect close delimiter: `)`
[00:59:32]   --> /checkout/src/test/run-pass-fulldeps/auxiliary/issue-16723.rs:37:7
[00:59:32]    |
[00:59:32] 33 |           -> Box<MacResult+'static> {
[00:59:32]    |                                     - unclosed delimiter
[00:59:32] 37 |     ]))
[00:59:32]    |       ^ incorrect close delimiter
[00:59:32] 
[00:59:32] 
[00:59:32] error: unexpected close delimiter: `}`
[00:59:32]   --> /checkout/src/test/run-pass-fulldeps/auxiliary/issue-16723.rs:38:1
[00:59:32] 38 | }
[00:59:32] 38 | }
[00:59:32]    | ^ unexpected close delimiter
[00:59:32] error: aborting due to 2 previous errors
[00:59:32] 
[00:59:32] 
[00:59:32] ------------------------------------------
---
[00:59:32] 
[00:59:32] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:497:22
[00:59:32] 
[00:59:32] 
[00:59:32] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/run-pass-fulldeps" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass-fulldeps" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "run-pass" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-5.0/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zunstable-options " "--target-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "5.0.0\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[00:59:32] 
[00:59:32] 
[00:59:32] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[00:59:32] Build completed unsuccessfully in 0:15:29
[00:59:32] Build completed unsuccessfully in 0:15:29
[00:59:32] make: *** [check] Error 1
[00:59:32] Makefile:58: recipe for target 'check' failed

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:00e872cb
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:06038492:start=1535643405697723459,finish=1535643405817954976,duration=120231517
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:062df2a6
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:05d8cfd4
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-08-30 18:32 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/422665413) ([raw log](https://api.travis-ci.org/v3/job/422665413/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:49:11] ....................................................................................................
[00:49:15] ....................................................................................................
[00:49:17] ...........i........................................................................................
[00:49:21] ....................................................................................................
[00:49:23] ............................................................iiiiiiiii...............................
[00:49:29] ....................................................................................................
[00:49:33] ....................................................................................................
[00:49:36] .........................................i..........................................................
[00:49:39] ..........................................................................................i.i..ii...
---
[01:13:31]    Compiling rustc_data_structures v0.0.0 (file:///checkout/src/librustc_data_structures)
[01:13:31] error: unused `#[macro_use]` import
[01:13:31]   --> librustc_data_structures/lib.rs:54:18
[01:13:31]    |
[01:13:31] 54 | #[cfg_attr(test, macro_use)]
[01:13:31]    |
[01:13:31]    = note: `-D unused-imports` implied by `-D warnings`
[01:13:31] 
[01:13:34] error: aborting due to previous error
[01:13:34] error: aborting due to previous error
[01:13:34] 
[01:13:34] error: Could not compile `rustc_data_structures`.
[01:13:34] 
[01:13:34] To learn more, run the command again with --verbose.
[01:13:34] 
[01:13:34] 
[01:13:34] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--features" " jemalloc" "--manifest-path" "/checkout/src/rustc/Cargo.toml" "-p" "rustc_data_structures" "--" "--quiet"
[01:13:34] 
[01:13:34] 
[01:13:34] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:13:34] Build completed unsuccessfully in 0:28:34
[01:13:34] Build completed unsuccessfully in 0:28:34
[01:13:34] Makefile:58: recipe for target 'check' failed
[01:13:34] make: *** [check] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:139628b0
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:242cd07c:start=1535653938444373942,finish=1535653938539826331,duration=95452389
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:16d087a0
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:262dd939
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-08-31 10:50 UTC, llogiq commented
FYI: I''ve started writing a [smallvectune](https://github.com/llogiq/smallvectune) crate that can wrap `SmallVec` and  log capacity information by internal array size over the course of the various constructors, resizings and deallocations. There are still some things to do, but once it's working, we could use this to help us gauge optimal internal array sizes for some workloads.

2018-09-11 19:53 UTC, eddyb commented
r? @nnethercote cc @nikomatsakis @michaelwoerister

2018-09-11 23:48 UTC, nnethercote commented
This PR currently makes two changes:
- remove the `OneVector` type alias (and `ExpectOne`);
- expand almost all of the formerly `OneVector` small vecs from 1 inline entry to 4 (and one in `transcribe.rs` to 8).

The first change seems fine. I agree that `OneVector` is not a particularly good name. You also mention the possibility of adding new type aliases. `SmallVec1`, `SmallVec4`, etc., would be clearer, but I'm not sure if they are necessary.

I'm less satisfied by the second change. The description above says "it is used in scenarios where the capacity of 1 is often exceeded, which might be nullifying the performance wins" -- do you have any measurements showing this? My general approach is profile-driven: I assume the existing code is reasonable, and only change such things when I have measurements showing it helps. I'm not comfortable with a blanket approach of changing every `OneVector` to have 4 inline entries without measurements. Avoiding heap allocation is good in general, but `SmallVec` can cause extra `memcpy` calls and I have seen cases where the cost of the additional copying exceeding the savings from the avoided heap allocations. It could also increase memory usage.

To move forward I would suggest removing `OneVector` and changing all its uses to `SmallVector<[T; 1]>` is fine. Beyond that, I think it's only worth changing `SmallVec` lengths when measurements show it helps. @llogiq's `smallvectune` crate could be very useful for that.

2018-09-11 23:50 UTC, nnethercote requested changes
(Changes requested are above.)

2018-09-11 23:52 UTC, nnethercote requested changes

2018-09-11 23:52 UTC, nnethercote commented on src/libsyntax/ext/tt/transcribe.rs
> +    let mut stack: SmallVec<[Frame; 8]> = smallvec![Frame::new(src)];
This is the one that is changed to 8, BTW.

2018-09-12 11:15 UTC, ljedrz commented
@nnethercote Thanks for the review! I wasn't aware these values were profiled and I now understand that changing them in an ad-hoc manner could be just as bad as spilling to the heap.

I agree that waiting for a more precise solution is the right choice. The adjusted PR should make this future change easier.

2018-09-12 22:03 UTC, nnethercote commented
> I wasn't aware these values were profiled and I now understand that changing them in an ad-hoc manner could be just as bad as spilling to the heap.

Well, it's possible they are profiled, I don't know for sure. You could work it out with `git blame` if you really wanted. It's also possible that the exact size doesn't matter for a lot of them. But in the absence of measurements, I think it's best to leave things as they are. This is basically [Chesterton's Fence](https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence) in action:

> There exists in such a case a certain institution or law; let us say, for the sake of simplicity, a fence or gate erected across a road. The more modern type of reformer goes gaily up to it and says, "I don't see the use of this; let us clear it away." To which the more intelligent type of reformer will do well to answer: "If you don't see the use of it, I certainly won't let you clear it away. Go away and think. Then, when you can come back and tell me that you do see the use of it, I may allow you to destroy it."

In this case measurements are the equivalent of the "Go away and think" part.

2018-09-13 06:32 UTC, llogiq commented
[smallvectune](https.//crates.io/crates/smallvectune) has reached its first milestone: The data collector should work now, and uses an MPSC to collect the traces, so it's all thread-safe and shouldn't be too much of a performance burden (that said, I haven't benchmarked it...).

2018-09-13 06:45 UTC, llogiq commented
[smallvectune](https.//crates.io/crates/smallvectune) has reached its first milestone: The data collector should work now, and uses an MPSC to collect the traces, so it's all thread-safe and shouldn't be too much of a performance burden (that said, I haven't benchmarked it...).

2018-09-25 17:37 UTC, TimNN commented
Ping from triage! @nnethercote / @ljedrz: Could you confirm the status of this PR? IIUC, it now only removes a type alias and uses a SmallVec implementation from an external crate.

2018-09-25 20:29 UTC, nnethercote commented
As per https://github.com/rust-lang/rust/pull/53824#issuecomment-420464001, I suggest that @ljedrz changes this PR to just be about removing `OneVector`, and then does size tuning in a follow-up.

2018-09-26 07:56 UTC, ljedrz commented
@nnethercote actually I already did that. I'll rebase it, this change should make future size tuning easier.

2018-09-26 08:45 UTC, ljedrz commented
Rebased.

2018-09-26 09:03 UTC, michaelwoerister commented
Looking good!
@bors r+

2018-09-26 12:39 UTC, merged

2018-09-26 12:40 UTC, rust-highfive commented
📣 Toolstate changed by rust-lang/rust#53824!

Tested on commit rust-lang/rust@c3a1a0d3400bbbcac194efb6ef2b14eef9be5149.
Direct link to PR: <https://github.com/rust-lang/rust/pull/53824>

💔 clippy-driver on windows: test-pass → build-fail (cc @Manishearth @llogiq @mcarton @oli-obk, @rust-lang/infra).
💔 clippy-driver on linux: test-pass → build-fail (cc @Manishearth @llogiq @mcarton @oli-obk, @rust-lang/infra).
💔 rls on windows: test-pass → build-fail (cc @nrc, @rust-lang/infra).
💔 rls on linux: test-pass → build-fail (cc @nrc, @rust-lang/infra).

2018-10-02 09:47 UTC, gnzlbg commented
This broke interpolate idents.