Optimize miri checking of integer array/slices
rust-lang/rust pull request #53903
Opened 2018-09-02 14:39 UTC by GabrielMajeri

This pull request implements the `E-easy` optimizations described in #53845. Instead of checking every element of an integral array, we can check the whole memory range at once.

There are is still an issue left (which is making two UI tests to fail):
the previous code was able to report the index of the first element which was out-of-bounds, but I don't know how to determine that now that we use `read_bytes`.
Perhaps someone who understands miri better can comment on that.

r? @RalfJung

2018-09-02 15:29 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/423621664) ([raw log](https://api.travis-ci.org/v3/job/423621664/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:46:01] ....................................................................................................
[00:46:04] ....................................................................................................
[00:46:07] ....................................................................................................
[00:46:11] ........i...........................................................................................
[00:46:15] .......................................................................F............................
[00:46:22] .......................ii..iii......................................................................
[00:46:25] ....................................................................................................
[00:46:27] ....................................................................................................
[00:46:30] ....................................................................................................
---
[00:48:01] 
[00:48:01] ---- [ui] ui/consts/const-eval/union-ice.rs stdout ----
[00:48:01] diff of stderr:
[00:48:01] 
[00:48:01] 15 LL | | };
[00:48:01] 16    | |__^ attempted to read undefined bytes
[00:48:01] 17 
[00:48:01] - error[E0080]: this constant likely exhibits undefined behavior
[00:48:01] -    |
[00:48:01] -    |
[00:48:01] - LL | / const FIELD_PATH2: Struct2 = Struct2 { //~ ERROR this constant likely exhibits undefined behavior
[00:48:01] - LL | |     b: [
[00:48:01] - LL | |         nd":28,"column_start":1,"column_end":3,"is_primary":true,"text":[{"text":"const FIELD_PATH: Struct = Struct { //~ ERROR this constant cannot be used","highlight_start":1,"highlight_end":75},{"text":"    a: 42,","highlight_start":1,"highlight_end":11},{"text":"    b: unsafe { UNION.field3 },","highlight_start":1,"highlight_end":32},{"text":"};","highlight_start":1,"highlight_end":3}],"label":"attempted to read undefined bytes","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: this constant cannot be used\n  --> /checkout/src/test/ui/consts/const-eval/union-ice.rs:25:1\n   |\nLL | / const FIELD_PATH: Struct = Struct { //~ ERROR this constant cannot be used\nLL | |     a: 42,\nLL | |     b: unsafe { UNION.field3 },\nLL | | };\n   | |__^ attempted to read undefined bytes\n\n"}
[00:48:01] {"message":"aborting due to 2 previous errors","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to 2 previous errors\n\n"}
[00:48:01] ------------------------------------------
[00:48:01] 
[00:48:01] thread '[ui] ui/consts/const-eval/union-ice.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:3196:9
[00:48:01] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:48:01] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:48:01] 
[00:48:01] ---- [ui] ui/union-ub-fat-ptr.rs stdout ----
[00:48:01] diff of stderr:
[00:48:01] 
[00:48:01] 26   --> $DIR/union-ub-fat-ptr.rs:99:1
[00:48:01] 27    |
[00:48:01] 28 LL | const B2: &[u8] = unsafe { SliceTransmute { repr: SliceRepr { ptr: &42, len: 999 } }.slice};
[00:48:01] -    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^the FFI section of the Reference for more information about using a custom\ninteger type:\n\nhttps://doc.rust-lang.org/reference.html#ffi-attributes\n"},"level":"error","spans":[{"file_name":"/checkout/src/test/ui/union-ub-fat-ptr.rs","byte_start":2182,"byte_end":2277,"line_start":93,"line_end":93,"column_start":1,"column_end":96,"is_primary":true,"text":[{"text":"const C2: &MyStr = unsafe { SliceTransmute { bad: BadSliceRepr { ptr: &42, len: &3 } }.my_str};","highlight_start":1,"highlight_end":96}],"label":"type validation failed: encountered non-integer slice length in fat pointer","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rust compiler repository if you believe it should not be considered undefined behavior","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":"error[E0080]: this constant likely exhibits undefined behavior\n  --> /checkout/src/test/ui/union-ub-fat-ptr.rs:93:1\n   |\nLL | const C2: &MyStr = unsafe { SliceTransmute { bad: BadSliceRepr { ptr: &42, len: &3 } }.my_str};\n   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type validation failed: encountered non-integer slice length in fat pointer\n   |\n   = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rust compiler repository if you believe it should not be considered undefined behavior\n\n"}
[00:48:01] {"message":"this constant likely exhibits undefined behavior","code":{"code":"E0080","explanation":"\nThis error indicates that the compiler was unable to sensibly evaluate an\nconstant expression that had to be evaluated. Attempting to divide by 0\nor causing integer overflow are two ways to induce this error. For example:\n\n```compile_fail,E0080\nenum Enum {\n    X = (1 << 500),\n    Y = (1 / 0)\n}\n```\n\nEnsure that the expressions given can be evaluated as the desired integer type.\nSee the FFI section of the Reference for more information about using a custom\ninteger type:\n\nhttps://doc.rust-lang.org/reference.html#ffi-attributes\n"},"level":"error","spans":[{"file_name":"/checkout/src/test/ui/union-ub-fat-ptr.rs","byte_start":2449,"byte_end":2541,"line_start":99,"line_end":99,"column_start":1,"column_end":93,"is_primary":true,"text":[{"text":"const B2: &[u8] = unsafe { SliceTransmute { repr: SliceRepr { ptr: &42, len: 999 } }.slice};","highlight_start":1,"highlight_end":93}],"label":"type validation failed: encountered uninitialized or out-of-bounds memory at .<deref>","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rust compiler repository if you believe it should not be considered undefined behavior","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":"error[E0080]: this constant likely exhibits undefined behavior\n  --> /checkout/src/test/ui/union-ub-fat-ptr.rs:99:1\n   |\nLL | const B2: &[u8] = unsafe { SliceTransmll}],"children":[{"message":"The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rust compiler repository if you believe it should not be considered undefined behavior","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":"error[E0080]: this constant likely exhibits undefined behavior\n  --> /checkout/src/test/ui/union-ub-fat-ptr.rs:102:1\n   |\nLL | const C3: &[u8] = unsafe { SliceTransmute { bad: BadSliceRepr { ptr: &42, len: &3 } }.slice};\n   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type validation failed: encountered non-integer slice length in fat pointer\n   |\n   = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rust compiler repository if you believe it should not be considered undefined behavior\n\n"}
[00:48:01] {"message":"this constant likely exhibits undefined behavior","code":{"code":"E0080","explanation":"\nThis error indicates that the compile [...]

2018-09-04 11:15 UTC, GabrielMajeri commented
@oli-obk I've tried to implement what you suggested, but I've run into a bigger issue:
the test `union-ice.rs` fails, and it seems `read_bytes` doesn't catch some undefined behavior.

The field in question is `b`, an array of `i64`s:
```
b: [
    21,
    unsafe { UNION.field3 },
    23,
    24,
],
```
Before this optimization, we would've caught the usage of `UNION.field3`, but now `read_bytes` returns `Ok` like nothing happened.

2018-09-04 11:36 UTC, GabrielMajeri commented on src/librustc_mir/interpret/validity.rs
> +                        match self.memory.read_bytes(dest.ptr, Size::from_bytes(len)) {
From what I can tell from the [source](https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_mir/interpret/place.rs.html#141-157), it's the `count` of elements in the array (or of the slice).

2018-09-04 11:56 UTC, oli-obk commented on src/librustc_mir/interpret/validity.rs
> +                        match self.memory.read_bytes(dest.ptr, Size::from_bytes(len)) {
then that's the source of your test failure. You're only testing the first 4 bytes, instead of all the 4 elements's bytes

2018-09-04 19:08 UTC, GabrielMajeri commented
@oli-obk Should be fixed now. Thanks for your help & patience.

@RalfJung This is now ready for review. All tests should pass. Let me know if any changes are needed.

2018-09-04 19:23 UTC, oli-obk requested changes
Are the diagnostics now exactly like the old ones? Or why are there no test changes?

If so, that's great!

2018-09-05 04:58 UTC, GabrielMajeri commented on src/librustc_mir/interpret/memory.rs
> +        if !self.is_defined(ptr, size).is_ok() {
Missed that, thanks

2018-09-05 04:58 UTC, GabrielMajeri commented on src/librustc_mir/interpret/memory.rs
>      fn check_defined(&self, ptr: Pointer, size: Size) -> EvalResult<'tcx> {
Alright. And I assume this new `check_defined` (the old `is_defined`) will _not_ be inline, because it's bigger than the previous one.

2018-09-05 04:59 UTC, GabrielMajeri commented
r? oli-obk

2018-09-05 05:01 UTC, GabrielMajeri commented
> Are the diagnostics now exactly like the old ones? 

I did my best and I *think* they should match the old ones. At least for the unit tests they match. Otherwise, they should still be pretty relevant.

r? @oli-obk

2018-09-05 08:36 UTC, oli-obk approved these changes

2018-09-05 08:36 UTC, oli-obk commented
let's give it a perf run

@bors try

2018-09-05 11:04 UTC, oli-obk commented
@rust-timer build

2018-09-05 11:04 UTC, rust-timer commented
Insufficient permissions to issue commands to rust-timer.

2018-09-05 11:29 UTC, michaelwoerister commented
@rust-timer build c4f54ce2096dd4d5263978b4dddea0637839f447

2018-09-05 11:29 UTC, rust-timer commented
Success: Queued c4f54ce2096dd4d5263978b4dddea0637839f447 with parent 0be2c303692cab31390e52701007cfa87867bf74, [comparison URL](https://perf.rust-lang.org/compare.html?start=0be2c303692cab31390e52701007cfa87867bf74&end=c4f54ce2096dd4d5263978b4dddea0637839f447).

2018-09-06 18:13 UTC, mati865 commented
Perf results are available: https://perf.rust-lang.org/compare.html?start=0be2c303692cab31390e52701007cfa87867bf74&end=c4f54ce2096dd4d5263978b4dddea0637839f447

2018-09-06 19:34 UTC, oli-obk commented
We actually lost performance. Can you do a local perf run and see whether it improves if you inline the function?

2018-09-07 11:07 UTC, GabrielMajeri commented
@oli-obk I've managed to get rustc-perf to work locally.

Inlining the function seems to have had some effect on my computer, but I don't know if it's enough to regain the loss:
```
compare | 2018-09-07 (no-inlin) | 2018-09-07 (inlining)

ctfe-stress-opt	        avg: -0.1%?	min: -0.9%?	max: 0.5%?
ctfe-stress-check	avg: -0.3%?	min: -0.7%?	max: -0.0%?
ctfe-stress-debug	avg: 0.1%?	min: -0.0%?	max: 0.2%?
```
Any other optimization ideas?

2018-09-07 11:20 UTC, oli-obk commented
very weird. I would have assumed we'd get enormous benefits from not recomputing each field. Do we actually have perf tests for large arrays of integers? And is your code actually hit by those?

2018-09-07 16:03 UTC, GabrielMajeri commented
@oli-obk I have no clue why there's worse performance.

I've experimented around a bit with the code, and the only way to get about the same performance as `master`, or just *slightly* (~0.30%) better performance, is if I remove all the nice error messages and revert all the changes to `ReadUndefBytes` and `check_defined`.

> Do we actually have perf tests for large arrays of integers

I've checked out the source behind `ctfe-stress`, couldn't find a test for big integral arrays. There's `UNSIZE_SLICE` which generates a lot of small arrays.

2018-09-07 16:37 UTC, oli-obk commented
I guess there's our problem. we're not perf testing the sanity checks. can you just locally perf `mir_heavy_promoted.rs` and see if it improves compared to master? we can add such a test to the perf suite separately from this PR in order to not muddy the benchmarks.

2018-09-07 16:46 UTC, GabrielMajeri commented
@oli-obk Wow, you were right! It did make a huge difference.

Compilation time with latest nightly:
```sh
Benchmark #1: rustc ./src/test/run-pass/mir_heavy_promoted.rs

  Time (mean ± σ):     10.361 s ±  0.110 s    [User: 10.149 s, System: 0.217 s]

  Range (min … max):   10.276 s … 10.596 s
```

Compilation time with this PR:
```sh
Benchmark #1: ./build/x86_64-unknown-linux-gnu/stage2/bin/rustc ./src/test/run-pass/mir_heavy_promoted.rs

  Time (mean ± σ):      2.538 s ±  0.053 s    [User: 2.358 s, System: 0.187 s]

  Range (min … max):    2.477 s …  2.617 s
```

2.5s vs 10.3s... that's 4x improvement!

2018-09-07 16:50 UTC, oli-obk commented on src/librustc/mir/interpret/mod.rs
> +    pub fn is_range_defined(&self, start: Size, end: Size) -> Result<(), Size> {
Have you tried inlining this, too?

2018-09-07 16:51 UTC, oli-obk commented
I'll accept the 1% regression and take the 4x speedup.

Can you just do a quick check whether more inlining in this code can help?

2018-09-07 16:53 UTC, GabrielMajeri commented
@oli-obk yep, checking right now. I assume you're interested in the results on `mir_heavy_promoted`, or also on the `ctfe` suite?

2018-09-07 17:29 UTC, GabrielMajeri commented
@oli-obk perf results are in after inlining that function:

It seems the perf hit with the stress test is lower compared to `master`:
```
ctfe-stress-debug	avg: 0.3%?	min: 0.0%?	max: 0.5%?
ctfe-stress-check	avg: -0.0%?	min: -0.4%?	max: 0.4%?
ctfe-stress-opt	        avg: 0.2%?	min: -0.0%?	max: 0.3%?
```

The mir_heavy test is now at 2.658 seconds, a 5% regression. Pretty good overall.

2018-09-08 07:32 UTC, oli-obk commented
Wonderful!

@bors r+

2018-09-08 19:57 UTC, merged