Doc total order requirement of sort(_unstable)_by
rust-lang/rust pull request #53918
Opened 2018-09-03 05:29 UTC by Havvy

I took the definition of what a total order is from the Ord trait
docs. I specifically put "elements of the slice" because if you
have a slice of f64s, but know none are NaN, then sorting by
partial ord is total in this case. I'm not sure if I should give
such an example in the docs or not.

r? @GuillaumeGomez

2018-09-03 07:52 UTC, GuillaumeGomez commented
Examples are always a big plus so please add them. :)

2018-09-03 09:00 UTC, Havvy commented
Alright. I'll write them tomorrow. Sleep beckons.

2018-09-10 05:12 UTC, Havvy commented
Tomorrow turned into a week. Whoops.

2018-09-10 08:28 UTC, GuillaumeGomez requested changes

2018-09-10 08:28 UTC, GuillaumeGomez commented on src/liballoc/slice.rs
> +    /// For example, while `f64` doesn't implement `Ord` because `NaN != NaN`, we can use
Please add urls to types.

2018-09-10 08:28 UTC, GuillaumeGomez commented on src/libcore/slice/mod.rs
> +    /// For example, while `f64` doesn't implement `Ord` because `NaN != NaN`, we can use
Same

2018-09-25 21:18 UTC, Havvy commented
ping @GuillaumeGomez

2018-09-26 23:14 UTC, GuillaumeGomez commented on src/liballoc/slice.rs
> +    /// `partial_cmp` as our sort function when we know the slice doesn't contain a `NaN`.
Can you link to `partial_cmp` please?

2018-09-26 23:14 UTC, GuillaumeGomez commented on src/libcore/slice/mod.rs
> +    /// `partial_cmp` as our sort function when we know the slice doesn't contain a `NaN`.
Same.

2018-09-26 23:15 UTC, GuillaumeGomez commented
Once the links added, it's good for me.

cc @rust-lang/docs (in case someone would like to double check).

2018-10-04 22:06 UTC, QuietMisdreavus commented
+1. Can you add the links @GuillaumeGomez requested?

2018-10-07 06:38 UTC, Havvy commented
Links added and rebased against master.

2018-10-07 08:15 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/438191209) ([raw log](https://api.travis-ci.org/v3/job/438191209/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:53:06] ................................................................................................i... 2200/4563
[00:53:10] .................................................................................................... 2300/4563
[00:53:14] .................................................................................................... 2400/4563
[00:53:18] .................................................................................................... 2500/4563
[00:53:21] ........iiiiiiiii................................................................................... 2600/4563
[00:53:27] .................................................................................................... 2800/4563
[00:53:31] .................................................................................................... 2900/4563
[00:53:34] ............................i....................................................................... 3000/4563
[00:53:37] ........................................................................................i.i..ii..... 3100/4563
---
[01:31:53] travis_fold:end:stage0-linkchecker

[01:31:53] travis_time:end:stage0-linkchecker:start=1538899941792582952,finish=1538899944042187862,duration=2249604910

[01:33:50] std/vec/struct.Vec.html:1350: broken link - std/std/cmp/trait.PartialOrd.html
[01:33:50] std/vec/struct.Vec.html:1700: broken link - std/std/cmp/trait.PartialOrd.html
[01:34:45] thread 'main' panicked at 'found some broken links', tools/linkchecker/main.rs:49:9
[01:34:45] 
[01:34:45] 
[01:34:45] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/linkchecker" "/checkout/obj/build/x86_64-unknown-linux-gnu/doc"
[01:34:45] expected success, got: exit code: 101
[01:34:45] expected success, got: exit code: 101
[01:34:45] 
[01:34:45] 
[01:34:45] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:34:45] Build completed unsuccessfully in 0:46:26
[01:34:45] Makefile:58: recipe for target 'check' failed
[01:34:45] make: *** [check] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:2bf6801e
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:183b6354:start=1538900124460003233,finish=1538900124591751604,duration=131748371
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:0d48c286
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:0a02c396
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-10-07 09:11 UTC, Havvy commented
I'm confused. Those links worked locally. I'll just add the "../" to make linkchecker happy though, and perhaps I misread what happened on my end?

2018-10-07 10:40 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/438212174) ([raw log](https://api.travis-ci.org/v3/job/438212174/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:47:37] ................................................................................................i... 2200/4563
[00:47:41] .................................................................................................... 2300/4563
[00:47:44] .................................................................................................... 2400/4563
[00:47:48] .................................................................................................... 2500/4563
[00:47:51] ........iiiiiiiii................................................................................... 2600/4563
[00:47:57] .................................................................................................... 2800/4563
[00:48:01] .................................................................................................... 2900/4563
[00:48:03] ............................i....................................................................... 3000/4563
[00:48:06] ........................................................................................i.i..ii..... 3100/4563
---
[01:22:53] travis_fold:end:stage0-linkchecker

[01:22:53] travis_time:end:stage0-linkchecker:start=1538908626887235069,finish=1538908629074560159,duration=2187325090

[01:22:53] std/primitive.slice.html:633: broken link - /checkout/obj/build/x86_64-unknown-linux-gnu/std/cmp/trait.PartialOrd.html
[01:22:53] std/primitive.slice.html:983: broken link - /checkout/obj/build/x86_64-unknown-linux-gnu/std/cmp/trait.PartialOrd.html
[01:26:02] thread 'main' panicked at 'found some broken links', tools/linkchecker/main.rs:49:9
[01:26:02] 
[01:26:02] 
[01:26:02] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/linkchecker" "/checkout/obj/build/x86_64-unknown-linux-gnu/doc"
[01:26:02] expected success, got: exit code: 101
[01:26:02] expected success, got: exit code: 101
[01:26:02] 
[01:26:02] 
[01:26:02] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:26:02] Build completed unsuccessfully in 0:43:05
[01:26:02] make: *** [check] Error 1
[01:26:02] Makefile:58: recipe for target 'check' failed

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:03952c38
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-10-07 12:33 UTC, GuillaumeGomez commented on src/liballoc/slice.rs
> +    /// [`partial_cmp`]: ../../std/cmp/trait.PartialOrd.html#tymethod.partial_cmp
Just remove this.

2018-10-07 12:34 UTC, GuillaumeGomez commented on src/libcore/slice/mod.rs
> +    /// [`partial_cmp`]: ../../std/cmp/trait.PartialOrd.html#tymethod.partial_cmp
And remove this one too.

2018-10-08 04:38 UTC, Havvy commented on src/liballoc/slice.rs
> +    /// [`partial_cmp`]: ../../std/cmp/trait.PartialOrd.html#tymethod.partial_cmp
That causes the rustdoc output to say:

```
222 |     /// [`partial_cmp`] as our sort function when we know the slice doesn't contain a `NaN`.                                                                                                                   
    |          ^^^^^^^^^^^^^ cannot be resolved, ignoring 
```

2018-10-09 14:05 UTC, QuietMisdreavus commented
That `partial_ord` cannot be linked to, either from directly linking to the file or via intra-doc links.

* The core issue with linking directly to the file is that these docs appear in two places: directly on slices (`std/primitive.slice.html`) and on Vec when documented in std (`std/vec/struct.Vec.html` - they're not in alloc because the slice docs aren't available there). You can't use different amounts of `../` to appease both places.
* You could try to use intra-doc links like @GuillaumeGomez suggests, but you need to link to the libcore version of `PartialOrd`, which may cause the eventual docs to link to core instead of std like we prefer. If you want to try it, link to the method via the full declaration of the `PartialOrd` trait - so `core::cmp::PartialOrd::partial_cmp` (`cmp::PartialOrd::partial_cmp` for the location in libcore) - then see whether the docs in std link to core or std. I have a feeling they'll link to core, but i haven't looked closely enough at the relevant code to know for sure.

2018-10-30 17:33 UTC, TimNN commented
ping from triage @Havvy: it looks like some changes have been requested to this PR.

2018-11-13 18:14 UTC, TimNN commented
Ping from triage @GuillaumeGomez: it looks like this PR is ready for another review.

2018-11-20 20:20 UTC, TimNN commented
Ping from triage @GuillaumeGomez / @rust-lang/docs: This PR requires your review.

2018-11-21 09:19 UTC, GuillaumeGomez commented
Then it's all good as is. Thanks!

@bors: r+

2018-11-22 10:04 UTC, merged