[Work in progress] First shot at rust-lang/rust/issues/54015
rust-lang/rust pull request #54343
Opened 2018-09-19 04:54 UTC by blitzerr

2018-09-19 04:55 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2018-09-19 05:13 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/430375519) ([raw log](https://api.travis-ci.org/v3/job/430375519/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:15:32]    Compiling rustc_metadata_utils v0.0.0 (file:///checkout/src/librustc_metadata_utils)
[00:15:32]    Compiling rustc_mir v0.0.0 (file:///checkout/src/librustc_mir)
[00:15:32]    Compiling rustc_typeck v0.0.0 (file:///checkout/src/librustc_typeck)
[00:15:33]    Compiling rustc_allocator v0.0.0 (file:///checkout/src/librustc_allocator)
[00:15:34] error[E0425]: cannot find value `mois` in this scope
[00:15:34]   --> librustc_mir/borrow_check/error_reporting.rs:89:78
[00:15:34]    |
[00:15:34] 89 |             if let Some((reported_place, _)) = self.move_error_reported.get(&mois) {
[00:15:34] 
[00:15:34] 
[00:15:34] error[E0425]: cannot find value `mois` in this scope
[00:15:34]   --> librustc_mir/borrow_check/error_reporting.rs:92:40
[00:15:34]    |
[00:15:34] 92 |                            mois={:?}", mois);
[00:15:34] 
[00:15:34] 
[00:15:34] error[E0425]: cannot find value `mois` in this scope
[00:15:34]    --> librustc_mir/borrow_check/error_reporting.rs:185:17
[00:15:34] 185 |                 mois,
[00:15:34]     |                 ^^^^ not found in this scope
[00:15:34] 
[00:15:47] error: aborting due to 3 previous errors
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-09-19 19:13 UTC, nikomatsakis requested changes

2018-09-19 19:13 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/error_reporting.rs
> +            for (moi, _is_back_edge) in &mois_is_back_edge_pair {
Nit: no need for `_` in the name here =)

2018-09-19 19:13 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/error_reporting.rs
> +        let mois_is_back_edge_pair = self.get_moved_indexes(context, mpi);
Nit: I think I'd call this just something like `move_sites` or something

2018-09-19 19:13 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/error_reporting.rs
> +        Vec<(MoveOutIndex, bool)> {
Nit: maybe we should introduce a

```rust
struct MoveSite {
    /// Index of the "move out" that we found. The `MoveData` can
    /// then tell us where the move occurred and so forth.
    moi: MoveOutIndex,

    /// True if we traversed a back edge while walking from the point
    /// of error to the move site.
    traversed_back_edge: bool,
}
```

2018-09-19 19:13 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/error_reporting.rs
> +                     (predecessor, context.loc.dominates(predecessor, &self.dominators))}));
Nit: I'd make a variable here to make this more self-documenting.

```rust
let is_back_edge = context.loc.dominates(predecessor, &self.dominators);
(predecessor,  is_back_edge)
```

2018-09-19 19:13 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/error_reporting.rs
> +                         (predecessor, l.dominates(predecessor, &self.dominators))
The problem is that we want this boolean to be true if we traversed a back edge **at any point along the path**.  So something like this:

```rust
let is_back_edge = context.loc.dominates(predecessor, &self.dominators);
(predecessor,  l.1 || is_back_edge)
```

2018-09-21 06:15 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/431340287) ([raw log](https://api.travis-ci.org/v3/job/431340287/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:46:59] ....................................................................................................
[00:47:03] ....................................................................................................
[00:47:06] ....................................................................................................
[00:47:09] ....................................................................................................
[00:47:12] .................................................F...................................i..............
[00:47:18] ........................................i.i..ii.....................................................
[00:47:22] ....................................................................................................
[00:47:24] ........................................................i...........................................
[00:47:28] ....................................................................................................
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-09-21 19:36 UTC, nikomatsakis requested changes
Updates look good. It'd be nice, if you're up for it, to separate the "rustfmt run" into its own commit (I usually do this by rebasing and "inserting" a rustfmt commit before the "meat"). 

The main concern though is that the output looks wrong; but then I see there's a travis failure, maybe it just needs to be updated?

2018-09-21 19:36 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/error_reporting.rs
> +    traversed_back_edge: bool,
Nice.

2018-09-21 19:36 UTC, nikomatsakis commented on src/test/ui/liveness/liveness-move-in-while.stderr
> +   |                        ^ value moved here in previous iteration of loop
Huh, interesting. This doesn't quite look right, since this location is not a move.

2018-09-21 19:36 UTC, nikomatsakis commented on src/test/ui/liveness/liveness-move-in-while.stderr
> +   |                        ^ value moved here in previous iteration of loop
Is this the current output?

2018-09-21 19:37 UTC, nikomatsakis commented
Ah, no, the travis failure is that the `//~ ERROR` annotations in the test are out of date:

```
[00:52:23] ---- [ui] ui/liveness/liveness-move-in-while.rs stdout ----
[00:52:23] 
[00:52:23] error: /checkout/src/test/ui/liveness/liveness-move-in-while.rs:18: unexpected error: '18:24: 18:25: borrow of moved value: `y` [E0382]'
[00:52:23] 
[00:52:23] error: /checkout/src/test/ui/liveness/liveness-move-in-while.rs:18: expected error not found: use of moved value: `y`
[00:52:23] 
[00:52:23] error: /checkout/src/test/ui/liveness/liveness-move-in-while.rs:19: expected error not found: use of moved value: `y`
```

2018-09-21 19:37 UTC, nikomatsakis commented on src/test/ui/liveness/liveness-move-in-while.stderr
> +   |                        ^ value moved here in previous iteration of loop
I expect to see "value used here after move", and the "value moved here..." annotation somewhere else.

2018-09-22 01:00 UTC, blitzerr commented
joydeep$ rustc +stage2 src/test/ui/liveness/liveness-move-in-while.rs
error[E0382]: borrow of moved value: `y`
  --> src/test/ui/liveness/liveness-move-in-while.rs:18:24
   |
18 |         println!("{}", y); //~ ERROR borrow of moved value: `y`
   |                        ^ value moved here in previous iteration of loop
   |
   = note: move occurs because `y` has type `std::boxed::Box<isize>`, which does not implement the `Copy` trait

error: aborting due to previous error

For more information about this error, try `rustc --explain E0382`.

2018-09-22 01:00 UTC, blitzerr commented
That is the current error when we compile the file.

2018-09-26 04:00 UTC, blitzerr commented
```rust
         let move_site_vec = self.get_moved_indexes(context, mpi);
         debug!(
-            "report_use_of_moved_or_uninitialized: mois={:?}",
+            "report_use_of_moved_or_uninitialized: vec<mois,back_edge>={:?}",
             move_site_vec
         );

-        let mois = move_site_vec.clone().into_iter().map(|x| x.moi).collect();
+        let mois = move_site_vec
+            .clone()
+            .into_iter()
+            .map(|x| {
+                let location = self.move_data.moves[x.moi].source;
+                let span = self.mir.source_info(location).span;
+                debug!("moi {:?}: {:?}", x.moi, span);
+                x.moi
+            })
+            .collect();
         if move_site_vec.is_empty() {
             let root_place = self.prefixes(&place, PrefixSet::All).last().unwrap();

@@ -137,12 +146,19 @@ impl<'cx, 'gcx, 'tcx> MirBorrowckCtxt<'cx, 'gcx, 'tcx> {
                     ""
                 };

-                if move_site.traversed_back_edge {
+                // if move_site.traversed_back_edge {
+                //     is_loop_move = true;
+                //     err.span_label(
+                //         span,
+                //         format!("value moved{} here in previous iteration of loop", move_msg),
+                //     );
+                // }
+                if span == move_span {
+                    is_loop_move = true;
                     err.span_label(
                         span,
                         format!("value moved{} here in previous iteration of loop", move_msg),
                     );
-                    is_loop_move = true;
                 } else {
                     err.span_label(move_span, format!("value moved{} here", move_msg));
                     move_spans.var_span_label(&mut err, "variable moved due to use in closure");
```

2018-09-26 04:05 UTC, blitzerr commented
@nikomatsakis 

This change is basically the same error reporting with the back-edge calculation done (but not used).
Compiled with stage 2 this is the output
```shell
>$ rustc +stage2 ./src/test/ui/liveness/liveness-move-in-while.rs
error[E0382]: borrow of moved value: `y`
  --> ./src/test/ui/liveness/liveness-move-in-while.rs:18:24
   |
18 |         println!("{}", y); //~ ERROR borrow of moved value: `y`
   |                        ^ value moved here in previous iteration of loop
   |
   = note: move occurs because `y` has type `std::boxed::Box<isize>`, which does not implement the `Copy` trait

error: aborting due to previous error

For more information about this error, try `rustc --explain E0382`.
```
Compiled with stage 1, this is the output:
```shell
>$ rustc +stage1 ./src/test/ui/liveness/liveness-move-in-while.rs
error[E0382]: borrow of moved value: `y`
  --> ./src/test/ui/liveness/liveness-move-in-while.rs:18:24
   |
18 |         println!("{}", y); //~ ERROR borrow of moved value: `y`
   |                        ^ value borrowed here after move
19 |         while true { while true { while true { x = y; x.clone(); } } }
   |                                                    - value moved here
   |
   = note: move occurs because `y` has type `std::boxed::Box<isize>`, which does not implement the `Copy` trait

error: aborting due to previous error

For more information about this error, try `rustc --explain E0382`.
```

2018-09-28 06:12 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/434458989) ([raw log](https://api.travis-ci.org/v3/job/434458989/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:45:43] 
[00:45:43] running 4308 tests
[00:45:46] ....................................................................................................
[00:45:49] ....................................................................................................
[00:45:51] ........F...................................F...F.......................F...........................
[00:45:54] ....FF.....................................F................F.......................................
[00:45:57] .........................F..........................................................................
[00:46:05] ....................................................................................................
[00:46:10] ................................i...........i.......................................................
[00:46:13] ...................................................iiiii............................................
[00:46:16] ....................................................................................................
---
[00:46:34] ....................................................................................................
[00:46:36] ...................................................................................................i
[00:46:39] ....................................................................................................
[00:46:42] ....................................................................................................
[00:46:45] ................................F..........................................F........................
[00:46:51] ....................................................................................................
[00:46:54] ....................................................................................................
[00:46:57] ....................................................................................................
[00:47:00] ....................................................................................................
[00:47:00] ....................................................................................................
[00:47:03] ................................................................................................i...
[00:47:06] ....................................................................................................
[00:47:09] ........................................................i.i..ii.....................F...............
[00:47:13] .....................F.F.......................F............................F.........F.............
[00:47:16] ......F...................................................................................i.........
[00:47:22] ....................................................................................................
[00:47:24] ....................................................................................................
[00:47:27] ....................................................................................................
[00:47:31] ...............................i....................................................................
[00:47:31] ...............................i....................................................................
[00:47:35] ....................................................................................................
[00:47:38] ....................................................................................................
[00:47:42] .............................................................................................i......
[00:47:45] ...........................................................................................F...F....
[00:47:48] ....................................................................................................
ing::from(\"hello\");\n\n    let len = calculate_length(&s1);\n\n    println!(\"The length of '{}' is {}.\", s1, len);\n}\n\nfn calculate_length(s: &String) -> usize {\n    s.len()\n}\n```\n\nA mutable reference can be created with `&mut`.\n\nSometimes we don't want a reference, but a duplicate. All types marked `Clone`\ncan be duplicated by calling `.clone()`. Subsequent changes to a clone do not\naffect the original variable.\n\nMost types in the standard library are marked `Clone`. The example below\ndemonstrates using `clone()` on a string. `s1` is first set to \"many\", and then\ncopied to `s2`. Then the first character of `s1` is removed, without affecting\n`s2`. \"any many\" is printed to the console.\n\n```\nfn main() {\n    let mut s1 = String::from(\"many\");\n    let s2 = s1.clone();\n    s1.remove(0);\n    println!(\"{} {}\", s1, s2);\n}\n```\n\nIf we control the definition of a type, we can implement `Clone` on it ourselves\nwith `#[derive(Clone)]`.\n\nSome types have no ownership semantics at all and are trivial to duplicate. An\nexample is `i32` and the other number types. We don't have to call `.clone()` to\nclone them, because they are marked `Copy` in addition to `Clone`.  Implicit\ncloning is more convenient in this case. We can mark our own types `Copy` if\nall their members also are marked `Copy`.\n\nIn the example below, we implement a `Point` type. Because it only stores two\nintegers, we opt-out of ownership semantics with `Copy`. Then we can\n`let p2 = p1` without `p1` being moved.\n\n```\n#[derive(Copy, Clone)]\nstruct Point { x: i32, y: i32 }\n\nfn main() {\n    let mut p1 = Point{ x: -1, y: 2 };\n 53] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:47:53] ---- [ui] ui/borrowck/borrowck-drop-from-guard.rs stdout ----
[00:47:53] diff of stderr:
[00:47:53] 
[00:47:53] 2   --> $DIR/borrowck-drop-from-guard.rs:22:23
[00:47:53] 2   --> $DIR/borrowck-drop-from-guard.rs:22:23
[00:47:53] 3    |
[00:47:53] 4 LL |         Some(_) if { drop(my_str); false } => {}
[00:47:53] -    |                           ------ value moved here
[00:47:53] +    |                           ------ value moved here 
[00:47:53] 6 LL |         Some(_) => {}
[00:47:53] 7 LL |         None => { foo(my_str); } //~ ERROR [E0382]
[00:47:53] 8    |                       ^^^^^^ value used here after move
[00:47:53] 
[00:47:53] The actual stderr differed from the expected stderr.
[00:47:53] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/borrowck/borrowck-drop-from-guard/borrowck-drop-from-guard.stderr
[00:47:53] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/borrowck/borrowck-drop-from-guard/borrowck-drop-from-guard.stderr
[00:47:53] To update references, rerun the tests and pass the `--bless` flag
[00:47:53] To only update this specific test, also pass `--test-args borrowck/borrowck-drop-from-guard.rs`
[00:47:53] error: 1 errors occurred comparing output.
[00:47:53] status: exit code: 1
[00:47:53] status: exit code: 1
[00:47:53] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/borrowck/borrowck-drop-from-guard.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/borrowck/borrowck-drop-from-guard/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-Z" "borrowck=mir" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/borrowck/borrowck-drop-from-guard/auxiliary" "-A" "unused"
[00:47:53] ------------------------------------------
[00:47:53] 
[00:47:53] ------------------------------------------
[00:47:53] stderr:
[00:47:53 [...]

2018-09-28 09:07 UTC, davidtwco reviewed
This looks really great! Just a couple small things I noticed when taking a look at this.

2018-09-28 09:10 UTC, davidtwco commented
I couldn't this to the above review below since you didn't change these lines, but could you change the error message in the below snippet to have a comma so all of the "iteration of loop" messages are consistent? (I'm pretty sure this still makes sense gramatically)

ie. `borrow captured here by closure in later iteration of loop` becomes `borrow captured here by closure, in later iteration of loop` 

https://github.com/rust-lang/rust/blob/c222479c6feb036e5e5198e068aa9824d855ffa4/src/librustc_mir/borrow_check/nll/explain_borrow/mod.rs#L48-L52

2018-09-28 11:27 UTC, blitzerr commented on src/librustc_mir/borrow_check/error_reporting.rs
> +                location
Thank you. That is a good point.

2018-09-28 11:27 UTC, blitzerr commented on src/librustc_mir/borrow_check/error_reporting.rs
> +        stack.extend(mir.predecessor_locations(context.loc).map(|predcessor| {
My lack of attention, no other reason :)

2018-09-28 11:29 UTC, blitzerr commented on src/librustc_mir/borrow_check/error_reporting.rs
>                          format!("value moved{} here in previous iteration of loop", move_msg),
sure

2018-09-28 12:37 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/434577633) ([raw log](https://api.travis-ci.org/v3/job/434577633/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:46:32] running 4308 tests
[00:46:35] ....................................................................................................
[00:46:38] ....................................................................................................
[00:46:41] ....................................................................................................
[00:46:44] ....................F......................................................................F........
[00:46:50] .......................i............................................................................
[00:46:55] ....................................................................................................
[00:47:00] ................................i...........i.......................................................
[00:47:03] ...................................................iiiii............................................
---
[00:47:50] ....................................................................................................
[00:47:54] ................................................................................................i...
[00:47:57] ....................................................................................................
[00:48:00] ........................................................i.i..ii.....................................
[00:48:03] ..............................................F.....................................................
[00:48:10] ....................................................................................................
[00:48:13] ....................................................................................................
[00:48:15] ....................................................................................................
[00:48:18] ....................................................................................................
---
[00:48:45] 
[00:48:45] ---- [ui] ui/borrowck/borrowck-mut-borrow-linear-errors.rs#mir stdout ----
[00:48:45] diff of stderr:
[00:48:45] 
[00:48:45] 4 LL |             1 => { addr.push(&mut x); } //[ast]~ ERROR [E0499]
[00:48:45] 5    |                    ----      ^^^^^^ second mutable borrow occurs here
[00:48:45] -    |                    borrow used here in later iteration of loop
[00:48:45] -    |                    borrow used here in later iteration of loop
[00:48:45] +    |                    borrow used here, in later iteration of loop
[00:48:45] 8 ...
[00:48:45] 9 LL |             _ => { addr.push(&mut x); } //[ast]~ ERROR [E0499]
[00:48:45] 10    |                              ------ first mutable borrow occurs here
[00:48:45] 13   --> $DIR/borrowck-mut-borrow-linear-errors.rs:25:30
[00:48:45] 14    |
[00:48:45] 14    |
[00:48:45] 15 LL |             1 => { addr.push(&mut x); } //[ast]~ ERROR [E0499]
[00:48:45] -    |                    ---- borrow used here in later iteration of loop
[00:48:45] +    |                    ---- borrow used here, in later iteration of loop
[00:48:45] 17 LL |             //[mir]~^ ERROR [E0499]
[00:48:45] 18 LL |             2 => { addr.push(&mut x); } //[ast]~ ERROR [E0499]
[00:48:45] 19    |                              ^^^^^^ second mutable borrow occurs here
[00:48:45] 
[00:48:45] The actual stderr differed from the expected stderr.
[00:48:45] The actual stderr differed from the expected stderr.
[00:48:45] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/borrowck/borrowck-mut-borrow-linear-errors.mir/bome\n```\n\nPlease note that in rust, you can either have many immutable references, or one\nmutable reference. Take a look at\nhttps://doc.rust-lang.org/stable/book/references-and-borrowing.html for more\ninformation. Example:\n\n\n```\nlet mut i = 0;\nlet mut x = &mut i; // ok!\n\n// or:\nlet mut i = 0;\nlet a = &i; // ok!\nlet b = &i; // still ok!\nlet c = &i; // still ok!\n```\n"},"level":"error","spans":[{"file_name":"/checkout/src/test/ui/borrowck/borrowck-mut-borrow-linear-errors.rs","byte_start":1066,"byte_end":1072,"line_start":27,"line_end":27,"column_start":30,"column_end":36,"is_primary":false,"text":[{"text":"            _ => { addr.push(&mut x); } //[ast]~ ERROR [E0499]","highlight_start":30,"highlight_end":36}],"label":"first mutable borrow occurs here","suggested_replacement":null,"suggestion_applicability":null,"expansion":null},{"file_name":"/checkout/src/test/ui/borrowck/borrowck-mut-borrow-linear-errors.rs","byte_start":868,"byte_end":874,"line_start":23,"line_end":23,"column_start":30,"column_end":36,"is_primary":true,"text":[{"text":"            1 => { addr.push(&mut x); } //[ast]~ ERROR [E0499]","highlight_start":30,"highlight_end":36}],"label":"second mutable borrow occurs here","suggested_replacement":null,"suggestion_applicability":null,"expansion":null},{"file_name":"/checkout/src/test/ui/borrowck/borrowck-mut-borrow-linear-errors.rs","byte_start":858,"byte_end":862,"line_start":23,"line_end":23,"column_start":20,"column_end":24,"is_primary":false,"text":[{"text":"            1 => { addr.push(&mut x); } //[ast]~ ERROR [E0499]","highlight_start":20,"highlight_end":24}],"label":"borrow used here, in la        _ => { addr.push(&mut x); } //[ast]~ ERROR [E0499]","highlight_start":30,"highlight_end":36}],"label":"first mutable borrow occurs here","suggested_replacement":null,"suggestion_applicability":null,"expansion":null},{"file_name":"/checkout/src/test/ui/borrowck/borrowck-mut-borrow-linear-errors.rs","byte_start":967,"byte_end":973,"line_start":25,"line_end":25,"column_start":30,"column_end":36,"is_primary":true,"text":[{"text":"            2 => { addr.push(&mut x); } //[ast]~ ERROR [E0499]","highlight_start":30,"highlight_end":36}],"label":"second mutable borrow occurs here","suggested_replacement":null,"suggestion_applicability":null,"expansion":null},{"file_name":"/checkout/src/test/ui/borrowck/borrowck-mut-borrow-linear-errors.rs","byte_start":858,"byte_end":862,"line_start":23,"line_end":23,"column_start":20,"column_end":24,"is_primary":false,"text":[{"text":"            1 => { addr.push(&mut x); } //[ast]~ ERROR [E0499]","highlight_start":20,"highlight_end":24}],"label":"borrow used here, in later iteration of loop","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error[E0499]: cannot borrow `x` as mutable more than once at a time\n  --> /checkout/src/test/ui/borrowck/borrowck-mut-borrow-linear-errors.rs:25:30\n   |\nLL |             1 => { addr.push(&mut x); } //[ast]~ ERROR [E0499]\n   |                    ---- borrow used here, in later iteration of loop\nLL |             //[mir]~^ ERROR [E0499]\nLL |             2 => { addr.push(&mut x); } //[ast]~ ERROR [E0499]\n   |                              ^^^^^^ second mutable borrow occurs here\nLL |                                       ^^^^^^ mutable borrow starts here in previous iteration of loop\n\n"}
[00:48:45] {"message":"aborting due to 3 previous errors","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to 3 previous errors\n\n"}
[00:48:45] {"message":"For more information about this error, try `rustc --explain E0499`.","code":null,"level":"","spans":[],"children":[],"rendered":"For more information about this error, try `rustc --explain E0499`.\n"}
[00:48:45] ------------------------------------------
[00:48:45] 
[00:48:45] thread '[ui] ui/borrowck/borrowck-mut-borrow-linear-errors.rs#mir' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:3258:9
[00:48:45] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:48: [...]

2018-10-02 19:40 UTC, nikomatsakis commented
@bors r

2018-10-02 19:40 UTC, nikomatsakis approved these changes

2018-10-02 19:40 UTC, nikomatsakis commented
@bors r+

2018-10-02 23:30 UTC, merged