Fix variable does not need to be mutable warning
rust-lang/rust pull request #54621
Opened 2018-09-27 21:11 UTC by spastorino

Fixes #54499

r? @nikomatsakis

2018-09-27 21:17 UTC, nikomatsakis requested changes

2018-09-27 21:17 UTC, nikomatsakis commented on src/test/ui/nll/issue-54499.rs
> +// parameter `x` -- since `'b` cannot be expressed in the caller's
This comment seems totally wrong :)

2018-09-27 21:17 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/mod.rs
> +                is_local_mutation_allowed: _,
Can we just remove this field altogether now?

2018-09-27 21:20 UTC, spastorino commented on src/test/ui/nll/issue-54499.rs
> +// parameter `x` -- since `'b` cannot be expressed in the caller's
Doh, wrong copy & paste

2018-09-27 22:27 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/434332965) ([raw log](https://api.travis-ci.org/v3/job/434332965/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://files.pythonhosted.org/packages/f3/43/c345035af7ca97094721b98573ea23f74d899b86bd02c70928cd5ded1666/awscli-1.16.23-py2.py3-none-any.whl (1.4MB)
    0% |▎                               | 10kB 12.6MB/s eta 0:00:01
    1% |▌                               | 20kB 1.9MB/s eta 0:00:01
    2% |▊                               | 30kB 2.2MB/s eta 0:00:01
    3% |█                               | 40kB 2.0MB/s eta 0:00:01
---
[00:58:03] ....................................................................................................
[00:58:06] ....................................................................................................
[00:58:09] ....................................................................................................
[00:58:12] ....................................................................................................
[00:58:16] ...........................F....................................................................i...
[00:58:22] ........................................................i.i..ii.....................................
[00:58:22] ........................................................i.i..ii.....................................
[00:58:25] ....................F...............................................................................
[00:58:29] .....................................................F....................................i.........
[00:58:35] ....................................................................................................
[00:58:38] ....................................................................................................
[00:58:41] ....................................................................................................
[00:58:44] ...............................i....................................................................
---
[01:03:28] ....................................................................................................
[01:03:32] ...............................i....................................................................
[01:03:36] ....................................................................................................
[01:03:39] ....................................................................................................
ut b = 3; //[lexical]~ ERROR: variable does not need to be mutable
[01:03:43] -    |         |
[01:03:43] -    |         help: remove this `mut`
[01:03:43] - 
[01:03:43] - error: variable does not need to be mutable
[01:03:43] - error: variable does not need to be mutable
[01:03:43] -   --> $DIR/lint-unused-mut-variables.rs:30:9
[01:03:43] -    |
[01:03:43] - LL |     let mut a = vec![3]; //[lexical]~ ERROR: variable does not need to be mutable
[01:03:43] -    |         |
[01:03:43] -    |         help: remove this `mut`
[01:03:43] - 
[01:03:43] - error: variable does not need to be mutable
[01:03:43] - error: variable does not need to be mutable
[01:03:43] -   --> $DIR/lint-unused-mut-variables.rs:32:10
[01:03:43] -    |
[01:03:43] - LL |     let (mut a, b) = (1, 2); //[lexical]~ ERROR: variable does not need to be mutable
[01:03:43] -    |          |
[01:03:43] -    |          help: remove this `mut`
[01:03:43] - 
[01:03:43] - error: variable does not need to be mutable
[01:03:43] - error: variable does not need to be mutable
[01:03:43] -   --> $DIR/lint-unused-mut-variables.rs:34:9
[01:03:43] -    |
[01:03:43] - LL |     let mut a; //[lexical]~ ERROR: variable does not need to be mutable
[01:03:43] -    |         |
[01:03:43] -    |         help: remove this `mut`
[01:03:43] - 
[01:03:43] - error: variable does not need to be mutable
[01:03:43] - error: variable does not need to be mutable
[01:03:43] -   --> $DIR/lint-unused-mut-variables.rs:38:9
[01:03:43] -    |
[01:03:43] - LL |     let mut b; //[lexical]~ ERROR: variable does not need to be mutable
[01:03:43] -    |         |
[01:03:43] -    |         help: remove this `mut`
[01:03:43] - 
[01:03:43 need to be mutable
[01:03:43 need to be mutable
[01:03:43] -    |         ----^
[01:03:43] -    |         |
[01:03:43] -    |         help: remove this `mut`
[01:03:43] - 
[01:03:43] - error: variable does not need to be mutable
[01:03:43] -   --> $DIR/lint-unused-mut-variables.rs:84:9
[01:03:43] -    |
[01:03:43] - LL |     let mut v : &mut Vec<()> = &mut vec![]; //[lexical]~ ERROR: variable does not need to be mutable
[01:03:43] -    |         |
[01:03:43] -    |         help: remove this `mut`
[01:03:43] - 
[01:03:43] - error: variable does not need to be mutable
[01:03:43] - error: variable does not need to be mutable
[01:03:43] 120   --> $DIR/lint-unused-mut-variables.rs:61:13
[01:03:43] 121    |
[01:03:43] 122 LL |     fn what(mut foo: isize) {} //[lexical]~ ERROR: variable does not need to be mutable
[01:03:43] 124    |             |
[01:03:43] 125    |             help: remove this `mut`
[01:03:43] 126 
[01:03:43] - error: variable does not need to be mutable
[01:03:43] - error: variable does not need to be mutable
[01:03:43] -   --> $DIR/lint-unused-mut-variables.rs:79:20
[01:03:43] -    |
[01:03:43] - LL |     fn mut_ref_arg(mut arg : &mut [u8]) -> &mut [u8] {
[01:03:43] -    |                    |
[01:03:43] -    |                    help: remove this `mut`
[01:03:43] - 
[01:03:43] - error: variable does not need to be mutable
[01:03:43] - error: variable does not need to be mutable
[01:03:43] -   --> $DIR/lint-unused-mut-variables.rs:143:9
[01:03:43] -    |
[01:03:43] - LL |     let mut b = vec![2]; //[lexical]~ ERROR: variable does not need to be mutable
[01:03:43] -    |         |
[01:03:43] -    |         help: remove this `mut`
[01:03:43] -    |
[01:03:43] -    |
[01:src/test/ui/lint/lint-unused-mut-variables.rs:61:13\n   |\nLL |     fn what(mut foo: isize) {} //[lexical]~ ERROR: variable does not need to be mutable\n   |             ----^^^\n   |             |\n   |             help: remove this `mut`\n\n"}
[01:03:43] {"message":"aborting due to 2 previous errors","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to 2 previous errors\n\n"}
[01:03:43] ------------------------------------------
[01:03:43] 
[01:03:43] thread '[ui] ui/lint/lint-unused-mut-variables.rs#nll' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:3258:9
[01:03:43] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:03:43] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[01:03:43] 
[01:03:43] ---- [ui] ui/nll/capture-mut-ref.rs stdout ----
[01:03:43] 
[01:03:43] error: ui test compiled successfully!
[01:03:43] status: exit code: 0
[01:03:43] command: "/checkout/obj/build/x86_64-unknow [...]

2018-09-28 19:22 UTC, nikomatsakis requested changes

2018-10-02 20:05 UTC, nikomatsakis commented
Left more detailed notes [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll/subject/.2354499.20Invalid.20.22variable.20does.20not.20need.20to.20be.20mutable.22/near/135060186)

2018-10-03 19:29 UTC, nikomatsakis approved these changes

2018-10-03 19:29 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/mod.rs
> +                    // FIXME(#21232)
Probably we want a comment here, but seems good.

2018-10-08 22:24 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/438867081) ([raw log](https://api.travis-ci.org/v3/job/438867081/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain

[00:04:21] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:04:22] tidy error: duplicate error code: 717
[00:04:22] tidy error: /checkout/src/librustc_mir/diagnostics.rs:2347:     E0717,
[00:04:22] tidy error: /checkout/src/libsyntax/diagnostic_list.rs:416:     E0717, // rustc_promotable without stability attribute
[00:04:23] some tidy checks failed
[00:04:23] 
[00:04:23] 
[00:04:23] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:23] 
[00:04:23] 
[00:04:23] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:23] Build completed unsuccessfully in 0:00:52
[00:04:23] Build completed unsuccessfully in 0:00:52
[00:04:23] make: *** [tidy] Error 1
[00:04:23] Makefile:79: recipe for target 'tidy' failed

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:000e8230
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:10e4c018:start=1539036922404182378,finish=1539036922408327091,duration=4144713
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0b549904
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:2d3c95be
travis_time:start:2d3c95be
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:05e20fa2
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-10-09 02:34 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/438929937) ([raw log](https://api.travis-ci.org/v3/job/438929937/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:47:45] .................................................................................................... 2700/4573
[00:47:48] .................................................................................................... 2800/4573
[00:47:52] .................................................................................................... 2900/4573
[00:47:55] ....................................i............................................................... 3000/4573
[00:47:58] ................................................................................................i.i. 3100/4573
[00:48:01] .ii................................................................................................. 3200/4573
[00:48:05] .....................................F.............................................................. 3300/4573
[00:48:11] .................................................................................................... 3500/4573
[00:48:14] .................................................................................................... 3600/4573
[00:48:17] .................................................................................................... 3700/4573
[00:48:20] ......................................................................................i............. 3800/4573
---
none            5.0M     0  5.0M   0% /run/lock
none            7.4G     0  7.4G   0% /run/shm
none            100M     0  100M   0% /run/user
none            768M     0  768M   0% /var/ramfs
=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:171373d8
travis_time:start:171373d8
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:07141410
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-10-09 19:18 UTC, nikomatsakis requested changes
Great! Left some nits

2018-10-09 19:18 UTC, nikomatsakis commented on src/librustc/mir/mod.rs
> +    pub fn base_local(&self) -> Option<Local> {
Doc comment: 

---


Returns the local variable at the "base" of this place, if any.  e.g., for a place like `a.b.c`, returns `Some(a)`. For a place based in a static or constant, returns `None`.

2018-10-09 19:18 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/mod.rs
> +        if let &Place::Projection(_) = place {
Comment:

---

FIXME(#21232). For now, error if assigning to a projection from an uninitialized local variable -- so e.g. doing `a.b = 22` when `a` is not yet initialized is simply an error. In the future, we could sometimes support this.

2018-10-09 19:18 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/mod.rs
> +                    self.used_mut.insert(local);
Comment: 

Pre-emptively insert local into the `used_mut` set to avoid any warnings related to whether the `mut` declaration is used.

2018-10-09 19:18 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/mod.rs
> +                    self.used_mut.insert(local);
We may want to check whether `local` is actually *declared* as mut, something like

```rust
if let Mutability::Mut = self.mir.local_decls[local].mutability {
    self.used_mut.insert(local);
}
```

2018-10-09 19:54 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/439295081) ([raw log](https://api.travis-ci.org/v3/job/439295081/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
travis_fold:end:system_info

Network availability confirmed.
Setting APT mirror in /etc/apt/sources.list: http://us-east-1.ec2.archive.ubuntu.com/ubuntu/
Installing APT Packages
travis_time:start:06101ab4
$ travis_apt_get_update
travis_time:end:06101ab4:start=1539111913081988385,finish=1539111918688508009,duration=5606519624
---
  gdb
0 upgraded, 1 newly installed, 0 to remove and 190 not upgraded.
Need to get 2,199 kB of archives.
After this operation, 6,474 kB of additional disk space will be used.
Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu trusty-updates/main amd64 gdb amd64 7.7.1-0ubuntu5~14.04.3 [2,199 kB]
Selecting previously unselected package gdb.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
---
[00:46:07] 
[00:46:07] running 4577 tests
[00:46:10] .................................................................................................... 100/4577
[00:46:13] .................................................................................................... 200/4577
[00:46:15] ........................................................................F........................... 300/4577
[00:46:18] ...............................................................F.........F.......................... 400/4577
[00:46:24] .......................i............................................................................ 600/4577
[00:46:29] .................................................................................................... 700/4577
[00:46:34] ................................i...........i....................................................... 800/4577
[00:46:37] ...................................................iiiii............................................ 900/4577
---
[00:48:33] 
[00:48:33] ---- [ui] ui/borrowck/borrowck-issue-48962.rs stdout ----
[00:48:33] diff of stderr:
[00:48:33] 
[00:48:33] + error[E0718]: cannot assign to `src.next` when `src` is not initialized
[00:48:33] +   --> $DIR/borrowck-issue-48962.rs:26:5
[00:48:33] +    |
[00:48:33] + LL |     src.next = None; //~ ERROR use of moved value: `src` [E0382]
[00:48:33] + 
[00:48:33] + 
[00:48:33] 1 error[E0382]: use of moved value: `src`
[00:48:33] 3    |
[00:48:33] 
[00:48:33] 8    |
[00:48:33] 8    |
[00:48:33] 9    = note: mriable after its contents\nhave been moved elsewhere. For example:\n\n```compile_fail,E0382\nstruct MyStruct { s: u32 }\n\nfn main() {\n    let mut x = MyStruct{ s: 5u32 };\n    let y = x;\n    x.s = 6;\n    println!(\"{}\", x.s);\n}\n```\n\nSince `MyStruct` is a type that is not marked `Copy`, the data gets moved out\nof `x` when we set `y`. This is fundamental to Rust's ownership system: outside\nof workarounds like `Rc`, a value cannot be owned by more than one variable.\n\nSometimes we don't need to move the value. Using a reference, we can let another\nfunction borrow the value without changing its ownership. In the example below,\nwe don't actually have to move our string to `calculate_length`, we can give it\na reference to it with `&` instead.\n\n```\nfn main() {\n    let s1 = String::from(\"hello\");\n\n    let len = calculate_length(&s1);\n\n    println!(\"The length of '{}' is {}.\", s1, len);\n}\n\nfn calculate_length(s: &String) -> usize {\n    s.len()\n}\n```\n\nA mutable reference can be created with `&mut`.\n\nSometimes we don't want a reference, but a duplicate. All types marked `Clone`\ncan be duplicated by calling `.clone()`. Subsequent changes to a clone do not\naffect the original variable.\n\nMost types in the standard library are marked `Clone`. The example below\ndemonstrates using `clone()` on a string. `s1` is first set to \"many\", and then\ncopied to `s2`. Then the first character of `s1` is removed, without affecting\n`s2`. \"any many\" is printed to the console.\n\n```\nfn main() {\n    let mut s1 = String::from(\"many\");\n    let s2 = s1.clone();\n    s1.remove(0);\n    println!(\"{} {}\", s1, s2);\n}\n```\n\nIf we control the definition of a type, we can implement `Clone` on it ourselves\nwith `#[derive(Clone)]`.\n\nSome types have no ownership semantics at all and are trivial to duplicate. An\nexample is `i32` and the other number types. We don't have to call `.clone()` to\nclone them, because they are marked `Copy` in addition to `Clone`.  Implicit\ncloning is more convenient in this case. We can mark our own types `Copy` if\nall their members also are marked `Copy`.\n\nIn the example below, we implement a `Point` type. Because it only stores two\nintegers, we opt-out of ownership semantics with `Copy`. Then we can\n`let p2 = p1` without `p1` being moved.\n\n```\n#[derive(Copy, Clone)]\nstruct Point { x: i32, y: i32 }\n\nfn main() {\n    let mut p1 = Point{ x: -1, y: 2 };\n    let p2 = p1;\n    p1.x = 1;\n    println!(\"p1: {}, {}\", p1.x, p1.y);\n    println!(\"p2: {}, {}\", p2.x, p2.y);\n}\n```\n\nAlternatively, if we don't control the struct's definition, or mutable shared\nownership is truly required, we can use `Rc` and `RefCell`:\n\n```\nuse std::cell::RefCell;\nuse std::rc::Rc;\n\nstruct MyStruct { s: u32 }\n\nfn main() {\n    let mut x = Rc::new(RefCell::new(MyStruct{ s: 5u32 }));\n    let y = x.clone();\n    x.borrow_mut().s = 6;\n    println!(\"{}\", x.borrow().s);\n}\n```\n\nWith this approach, x and y share ownership of the data via the `Rc` (reference\ncount type). `RefCell` essentially performs runtime borrow checking: ensuring\nthat at most one writer or multiple readers can access the data at any one time.\n\nIf you wish to learn more about ownership in Rust, start with the chapter in the\nBook:\3] 17    |              ^^^^ use of possibly uninitialized `**x`
[00:48:33] 18 
[00:48:33] + error[E0718]: cannot assign to `a.x` when `a` is not initialized
[00:48:33] +   --> $DIR/borrowck-uninit-ref-chain.rs:34:5
[00:48:33] +    |
[00:48:33] + LL |     a.x = 0;
[00:48:33] + 
[00:48:33] + 
[00:48:33] + error[E0718]: cannot assign to `a.x` when `a` is not initialized
[00:48:33] +   --> $DIR/borrowck-uninit-ref-chain.rs:39:5
[00:48:33] +    |
[00:48:33] + LL |     a.x = &&0;
[00:48:33] + 
[00:48:33] + 
[00:48:33] + error[E0718]: cannot assign to `a.x` when `a` is not initialized
[00:48:33] +   --> $DIR/borrowck-uninit-ref-chain.rs:45:5
[00:48:33] +    |
[00:48:33] + LL |     a.x = 0;
[00:48:33] + 
[00:48:33] + 
[00:48:33] 19 error[E0381]: borrow of possibly uninitialized variable: `a.y`
[00:48:33] 21    |
[00:48:33] 
[00:48:33] 
[00:48:33] 22 LL |     let _b = &a.y; //[ast]~ ERROR use of possibly uninitialized variable: `a.y` [E0381]
[00:48:33] 23    |              ^^^^ use of possibly uninitialized `a.y`
[00:48:33] 24 
[00:48:33] + error[E0718]: cannot assign to `a.x` when `a` is not initialized
[00:48:33] +   --> $DIR/borrowck-uninit-ref-chain.rs:50:5
[00:48:33] +    |
[00:48:33] + LL |     a.x = &&0;
[00:48:33] + 
[00:48:33] + 
[00:48:33] 25 error[E0381]: borrow of possibly uninitialized variable: `**a.y`
[00:48:33] 27    |
[00:48:33] 
[00:48:33] 
[00:48:33] 28 LL |     let _b = &**a.y; //[ast]~ ERROR use of possibly uninitialized variable: `**a.y` [E0381]
[00:48:33] 29    |              ^^^^^^ use of possibly uninitialized `**a.y`
[00:48:33] - error: aborting due to 5 previous errors
[00:48:33] + error: aborting due to 9 previous errors
[00:48:33] 32 
[00:48:33] - For more information about this error, try `rustc --explain E0381`.
[00:48:33] - For more information about this error, try `rustc --explain E0381`.
[00:48:33] + Some errors occurred: E0381, E0718.
[00:48:33] + For more information about an error, try `rustc --e [...]

2018-10-09 21:07 UTC, nikomatsakis requested changes
One last nit

2018-10-09 21:07 UTC, nikomatsakis commented on src/test/ui/nll/issue-54499.rs
> +    let mut s: (i32, i32);
I would make another copy of this test (or just add a second fn to this test) where you have `let s: (i32, i32);` and no `let mut s`

2018-10-09 21:53 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/439349909) ([raw log](https://api.travis-ci.org/v3/job/439349909/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:49:17] 
[00:49:17] running 4579 tests
[00:49:20] .................................................................................................... 100/4579
[00:49:23] .................................................................................................... 200/4579
[00:49:26] ........................................................................F........................... 300/4579
[00:49:29] ...............................................................F.........F.......................... 400/4579
[00:49:35] .......................i............................................................................ 600/4579
[00:49:40] .................................................................................................... 700/4579
[00:49:45] ...................................i...........i.................................................... 800/4579
[00:49:48] ......................................................iiiii......................................... 900/4579
---
[00:51:45] .................................................................................................... 4400/4579
[00:51:48] .................................................................................................... 4500/4579
the `Copy` trait
[00:51:50] 10 
[00:51:50] + error[E0718]: cannot assign to `src.0` when `src` is not initialized
[00:51:50] +   --> $DIR/borrowck-issue-48962.rs:32:5
[00:51:50] +    |
[00:51:50] + LL |     src.0 = 66; //~ ERROR use of moved value: `src` [E0382]
[00:51:50] + 
[00:51:50] + 
[00:51:50] 11 error[E0382]: use of moved value: `src`
[00:51:50] 13    |
[00:51:50] 
[00:51:50] 18    |
[00:51:50] 18    |
[00:51:50] 19    = note: move occurs because `src` has type `&mut (i32, i32)`, which does not implement the `Copy` trait
[00:51:50] - error: aborting due to 2 previous errors
[00:51:50] + error: aborting due to 4 previous errors
[00:51:50] 22 
[00:51:50] - For more information about this error, try `rustc --explain E0382`.
[00:51:50] - For more information about this error, try `rustc --explain E0382`.
[00:51:50] + Some errors occurred: E0382, E0718.
[00:51:50] + For more information about an error, try `rustc --explain E0382`.
[00:51:50] 24 
[00:51:50] 
[00:51:50] 
[00:51:50] The actual stderr differed from the expected stderr.
[00:51:50] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/borrowck/borrowck-issue-48962/borrowck-issue-48962.stderr
[00:51:50] To update references, rerun the tests and pass the `--bless` flag
[00:51:50] To only update this specific test, also pass `--test-args borrowck/borrowck-issue-48962.rs`
[00:51:50] error: 1 errors occurred comparing output.
[00:51:50] status: exit code: 1
[00:51:50] status: exit code: 1
[00:51:50] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/borrowck/borrowck-issue-48962.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/borrowck/borrowck-issue-48962/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/borrowck/borrowck-issue-48962/auxiliary" "-A" "unused"
[00:51:50] ------------------------------------------
[00:51:50] 
[00:51:50] ------------------------------------------
[00:51:50] stderr:
[00:51:50] stderr:
[00:51:50] ------------------------------------------
[00:51:50] {"message":"cannot assign to `src.next` when `src` is not initialized","code":{"code":"E0718","explanation":null},"level":"error","spans":[{"file_name":"/checkout/src/test/ui/borrowck/borrowck-issue-48962.rs","byte_start":670,"byte_end":678,"line_start":26,"line_end":26,"column_start":5,"column_end":13,"is_primary":true,"text":[{"text":"    src.next = None; //~ ERROR use of moved value: `src` [E0382]","highlight_start":5,"highlight_end":13}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error[E0718]: cannot assign to `src.next` when `src` is not initialized\n  --> /checkout/src/test/ui/borrowck/borrowck-issue-48962.rs:26:5\n   |\nLL |     src.next = None; //~ ERROR use of moved value: `src` [E0382]\n   |     ^^^^^^^^\n\n"}
[00:51:50] {"message":"use of moved value: `src`","code":{"code":"E0382","explanation":"\nThis error occurs when an attempt is made to use a variable after its contents\nhave been moved elsewhere. For example:\n\n``ement the `Copy` trait","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":"error[E0382]: use of moved value: `src`\n  --> /checkout/src/test/ui/borrowck/borrowck-issue-48962.rs:32:5\n   |\nLL |     {src};\n   |      --- value moved here\nLL |     src.0 = 66; //~ ERROR use of moved value: `src` [E0382]\n   |     ^^^^^^^^^^ value used here after move\n   |\n   = note: move occurs because `src` has type `&mut (i32, i32)`, which does not implement the `Copy` trait\n\n"}
[00:51:50] thread 'main' panicked at 'Some tests failed', tools/compiletest/src/main.rs:499:22
[00:51:50] {"message":"aborting due to 4 previous errors","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to 4 previous errors\n\n"}
[00:51:50] {"message":"Some errors occurred: E0382, E0718.","code":null,"level":"","spans":[],"children":[],"rendered":"Some errors occurred: E0382, E0718.\n"}
[00:51:50] {"message":"For more information about an error, try `rustc --explain E0382`.","code":null,"level":"","spans":[],"children":[],"rendered":"For more information about an error, try `rustc --explain E0382`.\n"}
[00:51:50] ------------------------------------------
[00:51:50] 
[00:51:50] thread '[ui] ui/borrowck/borrowck-issue-48962.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:3267:9
[00:51:50] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:51:50] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:51:50] 
[00:51:50] ---- [ui] ui/borrowck/borrowck-uninit-ref-chain.rs#mir stdout ----
[00:51:50] diff of stderr:
[00:51:50] 
[00:51:50] 16 LL |     let _y = &**x; //[ast]~ ERROR use of possibly uninitialized variable:use of possibly uninitialized variable: `**a.y` [E0381]
[00:51:50] 29    |              ^^^^^^ use of possibly uninitialized `**a.y`
[00:51:50] - error: aborting due to 5 previous errors
[00:51:50] + error: aborting due to 9 previous errors
[00:51:50] 32 
[00:51:50] - For more information about this error, try `rustc --explain E0381`.
[00:51:50] - For more information about this error, try `rustc --explain E0381`.
[00:51:50] + Some errors occurred: E0381, E0718.
[00:51:50] + For more information about an error, try `rustc --explain E0381`.
[00:51:50] 34 
[00:51:50] 
[00:51:50] 
[00:51:50] The actual stderr differed from the expected stderr.
[00:51:50] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/borrowck/borrowck-uninit-ref-chain.mir/borrowck-uninit-ref-chain.mir.stderr
[00:51:50] To update references, rerun the tests and pass the `--bless` flag
[00:51:50] To only update this specific test, also pass `--test-args borrowck/borrowck-uninit-ref-chain.rs`
[00:51:50] 
[00:51:50] error in revision `mir`: 1 errors occurred comparing output.
[00:51:50] status: exit code: 1
[00:51:50] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/borrowck/borrowck-uninit-ref-chain.rs" "--target=x86_64-unknown-linux-gnu" "--cfg" "mir" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" [...]

2018-10-09 23:02 UTC, spastorino commented
@nikomatsakis we don't want these kind of errors https://github.com/rust-lang/rust/pull/54621/commits/56011eb2e3bf8450caaf54fb90050a3e0100398f#diff-27087a37a3701eb55da69c6420fb0fa8R1 Need to figure out how to get rid of the error when there's already a move error.

2018-10-09 23:13 UTC, pnkfelix commented on src/test/ui/borrowck/borrowck-issue-48962.stderr
> +LL |     src.next = None; //~ ERROR use of moved value: `src` [E0382]
(I've already chatted with @spastorino about this; we can avoid this (IMO redundant/unnecessary) error if we revise the strategy slightly.  PR #54941 has some hidden suggestions )

2018-10-10 00:08 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/439392566) ([raw log](https://api.travis-ci.org/v3/job/439392566/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:50:55] 
[00:50:55] running 4579 tests
[00:50:58] .................................................................................................... 100/4579
[00:51:01] .................................................................................................... 200/4579
[00:51:04] ........................................................................F........................... 300/4579
[00:51:07] ...............................................................F.........F.......................... 400/4579
[00:51:14] .......................i............................................................................ 600/4579
[00:51:20] .................................................................................................... 700/4579
[00:51:26] ...................................i...........i.................................................... 800/4579
[00:51:29] ......................................................iiiii......................................... 900/4579
---
[00:53:24] .................................................................................................... 4100/4579
[00:53:28] ................................................................i................................... 4200/4579
[00:53:32] .................................................................................................... 4300/4579
[00:53:35] .................................................................................................... 4400/4579
wck/borrowck-uninit-ref-chain.rs:39: unexpected error: '39:5: 39:14: cannot assign to `a.x` when `a` is not initialized [E0718]'
[00:53:41] 
[00:53:41] error in revision `mir`: /checkout/src/test/ui/borrowck/borrowck-uninit-ref-chain.rs:45: unexpected error: '45:5: 45:12: cannot assign to `a.x` when `a` is not initialized [E0718]'
[00:53:41] 
[00:53:41] error in revision `mir`: /checkout/src/test/ui/borrowck/borrowck-uninit-ref-chain.rs:50: unexpected error: '50:5: 50:14: cannot assign to `a.x` when `a` is not initialized [E0718]'
[00:53:41] 
[00:53:41] error in revision `mir`: 4 unexpected errors found, 0 expected errors not found
[00:53:41] status: exit code: 1
[00:53:41] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/borrowck/borrowck-uninit-ref-chain.rs" "--target=x86_64-unknown-linux-gnu" "--cfg" "mir" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/borrowck/borrowck-uninit-ref-chain.mir/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-Z" "borrowck=mir" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/borrowck/borrowck-uninit-ref-chain.mir/auxiliary" "-A" "unused"
[00:53:41]     Error {
[00:53:41]         line_num: 34,
[00:53:41]         kind: Some(
[00:53:41]             Error
[00:53:41]             Error
[00:53:41]         ),
[00:53:41]         msg: "34:5: 34:12: cannot assign to `a.x` when `a` is not initialized [E0718]"
[00:53:41]     Error {
[00:53:41]     Error {
[00:53:41]       eckout/src/test/ui/borrowck/borrowck-use-in-index-lvalue.rs" "--target=x86_64-unknown-linux-gnu" "--cfg" "mir" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/borrowck/borrowck-use-in-index-lvalue.mir/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-Z" "borrowck=mir" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/borrowck/borrowck-use-in-index-lvalue.mir/auxiliary" "-A" "unused"
[00:53:41]     Error {
[00:53:41]         line_num: 16,
[00:53:41]         kind: Some(
[00:53:41]             Error
[00:53:41]             Error
[00:53:41]         ),
[00:53:41]         msg: "16:5: 16:13: cannot assign to `w[..]` when `w` is not initialized [E0718]"
[00:53:41]     Error {
[00:53:41]         line_num: 20,
[00:53:41]         kind: Some(
[00:53:41]             Error
[00:53:41]             Error
[00:53:41]         ),
[00:53:41]         msg: "20:5: 20:13: cannot assign to `w[..]` when `w` is not initialized [E0718]"
[00:53:41] ]
[00:53:41] 
[00:53:41] thread '[ui] ui/borrowck/borrowck-use-in-index-lvalue.rs#mir' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:1341:13
[00:53:41] 
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-10-12 15:28 UTC, spastorino commented
I'm closing this given @pnkfelix is taking care of this now.

2018-10-12 15:28 UTC, closed without merging