Move collect_and_partition_mono_items to rustc_mir
rust-lang/rust pull request #55349
Opened 2018-10-25 15:53 UTC by bjorn3

Most of the logic of it is inside rustc_mir anyway.

Also removes the single function crate rustc_metadata_utils. Based on #55225

2018-10-25 15:53 UTC, rust-highfive commented
r? @oli-obk

(rust_highfive has picked a reviewer for you, use r? to override)

2018-10-25 15:59 UTC, oli-obk requested changes
r=me with nit fixed

2018-10-25 15:59 UTC, oli-obk commented on src/librustc_mir/monomorphize/partitioning.rs
> +assert_eq!(cnum, LOCAL_CRATE);
wrongly indented assertion

2018-10-25 16:04 UTC, bjorn3 commented on src/librustc_mir/monomorphize/partitioning.rs
> +assert_eq!(cnum, LOCAL_CRATE);
Oops

2018-10-25 16:08 UTC, oli-obk approved these changes

2018-10-25 16:09 UTC, oli-obk commented
@bors r+

2018-10-25 16:09 UTC, bjorn3 commented
Should I close #55225?

2018-10-25 16:12 UTC, oli-obk commented
idk what the rules are. These PRs are probably going to get rolled up anyway

2018-10-25 16:15 UTC, bjorn3 commented
Will close it, so that the first commit doesn't get included twice (that commit is a rebase of the other pr)

2018-11-03 13:32 UTC, bjorn3 commented
Rebased

2018-11-03 13:42 UTC, oli-obk commented on src/librustc_mir/monomorphize/partitioning.rs
> +assert_eq!(cnum, LOCAL_CRATE);
this is still/again there

```suggestion
    assert_eq!(cnum, LOCAL_CRATE);
```

2018-11-03 13:45 UTC, bjorn3 commented on src/librustc_mir/monomorphize/partitioning.rs
> +assert_eq!(cnum, LOCAL_CRATE);
Oops

2018-11-04 15:06 UTC, merged