Slight copy-editing for `std::cell::Cell` docs
rust-lang/rust pull request #55377
Opened 2018-10-26 08:23 UTC by goffrie

Hopefully this is a bit more precise and also more correct English.

2018-10-26 08:44 UTC, joshtriplett requested changes

2018-10-26 08:44 UTC, joshtriplett commented on src/libcore/cell.rs
> -/// // WORKS, although `my_struct` is immutable, field `special_field` is mutable because it is Cell
Here, the old version is clearer because it explicitly says "is mutable because". (Cleaning up the grammar would be helpful, though.)

2018-10-26 08:44 UTC, joshtriplett commented on src/libcore/cell.rs
> +/// // ERROR: my_struct is immutable
I don't think this is clearer.

2018-10-26 08:44 UTC, joshtriplett commented on src/libcore/cell.rs
> +/// immutable struct. In other words, it enables interior mutability.
This seems like an improvement, except that you should still keep the explicit quoting on `'interior mutability'` to make it clear that it defines this new term.

2018-11-06 18:55 UTC, TimNN commented
Ping from triage @joshtriplett: It looks like this PR is ready for your review again.

2018-11-06 23:05 UTC, joshtriplett commented
@bors r+ rollup

2018-11-07 20:13 UTC, merged