Rename `Value` to `Immediate` for miri
rust-lang/rust pull request #55393
Opened 2018-10-26 16:14 UTC by oli-obk

r? @RalfJung

2018-10-26 16:33 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/446769516) ([raw log](https://api.travis-ci.org/v3/job/446769516/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:017e6e30:start=1540570823977288348,finish=1540570825139795096,duration=1162506748
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
---

[00:04:24] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:04:24] tidy error: /checkout/src/librustc_mir/interpret/cast.rs:331: line longer than 100 chars
[00:04:25] some tidy checks failed
[00:04:25] 
[00:04:25] 
[00:04:25] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:25] 
[00:04:25] 
[00:04:25] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:25] Build completed unsuccessfully in 0:00:47
[00:04:25] Build completed unsuccessfully in 0:00:47
[00:04:25] make: *** [tidy] Error 1
[00:04:25] Makefile:79: recipe for target 'tidy' failed

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:08d0bab0
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:13f80944:start=1540571102830118877,finish=1540571102835656336,duration=5537459
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:06b409c0
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:01f53b8c
travis_time:start:01f53b8c
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:09cacd09
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-10-29 12:38 UTC, RalfJung requested changes
r=me with the nit fixed.

Thanks!

2018-10-29 12:38 UTC, RalfJung commented on src/librustc_mir/interpret/operand.rs
>  /// In particular, thanks to `ScalarPair`, arithmetic operations and casts can be entirely
The doc comment still refers to the old name.

2018-10-31 16:02 UTC, RalfJung commented on src/librustc_mir/interpret/operand.rs
>  /// defined on `Value`, and do not have to work with a `Place`.
```suggestion
/// defined on `Immediate`, and do not have to work with a `Place`.
```

2018-11-02 11:54 UTC, RalfJung commented
LGTM. :) Needs a rebase though.

2018-11-02 12:17 UTC, oli-obk commented
done

2018-11-02 12:19 UTC, RalfJung commented
@bors r+

2018-11-04 17:55 UTC, merged