rustc_codegen_llvm: traitification of LLVM-specific CodegenCx and Builder methods
rust-lang/rust pull request #55627
Opened 2018-11-02 19:40 UTC by sunfishcode

This PR is the continuation of #54012 and earlier PRs, in the grand plan of #45274 to allow for multiple codegen backends.

High-level summary: interpose a set of traits between Rust's codegen logic and the LLVM APIs, allowing another backend to implement the traits and share most of the codegen logic. These traits are currently somewhat LLVM-specific, but once this refactoring is in place, they can evolve to be more general.

See [this README](https://github.com/denismerigoux/rust/blob/cg-llvm-gen/src/librustc_codegen_ssa/README.md) for a writeup on the current trait organization.

2018-11-02 19:40 UTC, rust-highfive commented
r? @pnkfelix

(rust_highfive has picked a reviewer for you, use r? to override)

2018-11-02 22:48 UTC, sunfishcode commented
r? @eddyb

2018-11-03 08:53 UTC, denismerigoux commented
Thanks for fixing the bug ! It was a silly mistake from my part...

2018-11-04 22:11 UTC, eddyb requested changes
First batch of comments (my browser hates me already!)

2018-11-04 22:11 UTC, eddyb commented on src/librustc_codegen_llvm/builder.rs
> +    fn load_ref(
This should be named `load_operand`. I guess the metadata is gnarly enough to merit moving this here. But maybe this should be in a separate `Methods` trait?

2018-11-04 22:11 UTC, eddyb commented on src/librustc_codegen_llvm/builder.rs
> +    fn range_metadata(&mut self, load: &'ll Value, range: Range<u128>) {
I don't think we should expose this like this, but maybe as an optional argument to `load`?

2018-11-04 22:11 UTC, eddyb commented on src/librustc_codegen_llvm/builder.rs
> +    fn nonnull_metadata(&mut self, load: &'ll Value) {
Similar here - in fact, we can do this in one place - the LLVM `!nonnull` is just `!range` but for pointers, and only when the range excludes `0` (which is what the caller checks).

2018-11-04 22:11 UTC, eddyb commented on src/librustc_codegen_llvm/builder.rs
> +                        order: rustc_codegen_ssa::common::AtomicOrdering, align: Align) {
Indentation seems weird here.

2018-11-04 22:11 UTC, eddyb commented on src/librustc_codegen_llvm/builder.rs
> +    fn inbounds_gep(&mut self, ptr: &'ll Value, indices: &[&'ll Value]) -> &'ll Value {
The GEPs should be abstracted over with `PlaceRef` APIs - but we could leave this for later, I guess.

2018-11-04 22:11 UTC, eddyb commented on src/librustc_codegen_llvm/builder.rs
> +                       dia: syntax::ast::AsmDialect) -> Option<&'ll Value> {
Can this be moved to `asm.rs`? Actually, nothing in the trait interfaces should use raw pointers!

2018-11-04 22:11 UTC, eddyb commented on src/librustc_codegen_llvm/builder.rs
> +    fn inline_asm_call(&mut self, asm: *const c_char, cons: *const c_char,
For this to be a safe Rust function, btw, `*const c_char` needs to be replaced with `&CStr`.

2018-11-04 22:11 UTC, eddyb commented on src/librustc_codegen_llvm/builder.rs
> +                AtomicOrdering::from_generic(failure_order),
This makes me think `From` should be implemented instead. Then, the LLVM-specific `AtomicOrdering` do not need to be imported, removing `rustc_codegen_ssa::common::` noise in the signature *and* we can just do `order.into()` and whatnot.

2018-11-04 22:11 UTC, eddyb commented on src/librustc_codegen_llvm/builder.rs
> +    fn call_lifetime_intrinsic(&mut self, intrinsic: &str, ptr: &'ll Value, size: Size) {
This probably needs to be generalized to `storage_{live,dead}` (which is what the MIR contains).

2018-11-04 22:11 UTC, eddyb commented on src/librustc_codegen_llvm/builder.rs
> +    fn delete_basic_block(&mut self, bb: &'ll BasicBlock) {
This is **unsafe**! The trait method should be marked as such. Maybe we can find a way to avoid doing it at all.

2018-11-04 22:11 UTC, eddyb commented on src/librustc_codegen_llvm/builder.rs
> +        llvm::Attribute::NoInline.apply_callsite(llvm::AttributePlace::Function, llret);
Applying attributes via the return value is a LLVM-ism, we should clean it up.

2018-11-04 23:08 UTC, eddyb requested changes
Second round of comments, got through `rustc_codegen_llvm` and `rustc_codegen_ssa::back`, things seems pretty good so far!

2018-11-04 23:08 UTC, eddyb commented on src/librustc_codegen_ssa/back/write.rs
> +pub struct CodegenContext<B : WriteBackendMethods> {
This reminds me the name `Codegen` in the context of the "back" module, is suboptimal.
Including in "optimize_and_codegen". I think we could call this step "emitting machine code/a binary", so maybe `optimize_and_emit`? `OptimizeAndEmitContext` is not great, but more descriptive.

cc @michaelwoerister @rkruppe @alexcrichton 

Also, ` : ` should be `: `.

2018-11-04 23:08 UTC, eddyb commented on src/librustc_codegen_ssa/back/write.rs
> +                            sess.opts.debugging_opts.embed_bitcode;
Not sure what to do about all of these LLVM-specific options.

2018-11-04 23:08 UTC, eddyb commented on src/librustc_codegen_ssa/back/write.rs
> +                            sess.opts.debugging_opts.embed_bitcode;
Maybe rename `bitcode` to `ir`, to generalize? or `llvm_bc`, to make it clear it's LLVM-specific.

2018-11-04 23:08 UTC, eddyb commented on src/librustc_codegen_ssa/back/write.rs
> +
Maybe someone should search for `llvm` (case-insensitive) in `rustc_codegen_ssa`.

2018-11-04 23:11 UTC, eddyb commented
There's a general issue, that `rustc_codegen_ssa` should perhaps not have all of that `back` stuff in it. Would it make sense to move it to `rustc_codegen_link` or something similar?
Maybe `rustc_post_codegen`. Name ideas welcome!

2018-11-05 08:24 UTC, eddyb requested changes
Third batch, and that's all the comments for now! Let me know if I can help resolve everything.

2018-11-06 10:33 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/451298944) ([raw log](https://api.travis-ci.org/v3/job/451298944/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:381eeeba:start=1541499549548654605,finish=1541499551832758207,duration=2284103602
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-5.0
---

[00:04:16] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:04:16] tidy error: /checkout/src/librustc_codegen_ssa/callee.rs:31: line longer than 100 chars
[00:04:18] some tidy checks failed
[00:04:18] 
[00:04:18] 
[00:04:18] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:18] 
[00:04:18] 
[00:04:18] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:18] Build completed unsuccessfully in 0:00:51
[00:04:18] Build completed unsuccessfully in 0:00:51
[00:04:18] Makefile:79: recipe for target 'tidy' failed
[00:04:18] make: *** [tidy] Error 1

The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:05016710
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
---
travis_time:end:1b67f44c:start=1541499820877229265,finish=1541499820881839828,duration=4610563
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0246a805
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:06e9a240
travis_time:start:06e9a240
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:04d4854c
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-11-15 18:40 UTC, Mark-Simulacrum commented
@sunfishcode Can you take a look at fixing the merge conflicts and resolving the CI failure here?

2018-11-15 18:44 UTC, eddyb commented
@Mark-Simulacrum I'm rebasing it and getting close to finishing.

2018-11-16 13:13 UTC, eddyb approved these changes
@rust-lang/compiler I've rebased the PR myself, and applied a few of the changes I had suggested (in separate commits where possible).

Most of my nits were about "LLVM-isms" that aren't worth even leaving comments all over the place about - we'll have to do a general sweep, but I'd rather this not bitrot any further.

Anyone willing to do a quick review? Or at least read [this `README.md`](https://github.com/rust-lang/rust/blob/756f84d7cef90b7364ae88ca707e59670dde4c92/src/librustc_codegen_ssa/README.md) written by @denismerigoux and look through the APIs in [`src/librustc_codegen_ssa/traits`](https://github.com/rust-lang/rust/blob/756f84d7cef90b7364ae88ca707e59670dde4c92/src/librustc_codegen_ssa/traits).

2018-11-16 13:16 UTC, eddyb commented
@bors try p=123 (preempting bitrot if it gets approved)

2018-11-16 14:31 UTC, nikomatsakis commented
r? @nikomatsakis -- will try to review today

2018-11-16 15:57 UTC, eddyb commented
@rust-timer build dd5853b62b2c9372272a3f8343dd81d5f586121a

2018-11-16 15:57 UTC, rust-timer commented
Success: Queued dd5853b62b2c9372272a3f8343dd81d5f586121a with parent 6b9b97bd9b704f85f0184f7a213cc4d62bd9654c, [comparison URL](https://perf.rust-lang.org/compare.html?start=6b9b97bd9b704f85f0184f7a213cc4d62bd9654c&end=dd5853b62b2c9372272a3f8343dd81d5f586121a).

2018-11-16 16:00 UTC, oli-obk commented on src/librustc_codegen_ssa/README.md
> +## State of the code before the refactoring
I think it would be best in the PR description, since that's where one will end when jumping back in history to see where something came from

2018-11-16 17:49 UTC, rust-timer commented
Finished benchmarking try commit dd5853b62b2c9372272a3f8343dd81d5f586121a

2018-11-16 21:05 UTC, nikomatsakis approved these changes
Looks like everything I found wound up getting moot later. r=me.

2018-11-16 21:05 UTC, nikomatsakis commented on src/librustc_codegen_llvm/back/write.rs
> +    phantom: PhantomData<&'ll ()>
This seems *ok* but I usually find these sorts of things to indicate some other "mis-alignment". This `'ll` lifetime -- what does it logically represent here? Is there some resource we could take a reference to instead? Should it maybe be moved to the `Backend` trait?

Anyway, not a blocking concern, but I do feel like the "semantic meaning" of this lifetime is unclear to me.

2018-11-16 21:18 UTC, nikomatsakis commented
@bors r+

2018-11-17 02:06 UTC, eddyb commented
@alexcrichton @retep998 Is this spurious, or a real failure?

@bors retry (just in case)

2018-11-17 07:10 UTC, merged