Add escape-to-raw MIR statement
rust-lang/rust pull request #55716
Opened 2018-11-06 12:04 UTC by RalfJung

Add a new MIR "ghost state statement": Escaping a ptr to permit raw accesses.

This includes #55549, [click here](https://github.com/RalfJung/rust/compare/miri-visitor...RalfJung:escape-to-raw) for just the new commits.

2018-11-06 12:04 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2018-11-06 12:32 UTC, oli-obk commented on src/librustc_mir/transform/add_retag.rs
>                  ProjectionElem::Subslice { .. } |
If `Deref` can change what it points to, so can `ConstantIndex`. Or I'm fundamentally misunderstanding something here. `Deref` is essentially `ConstantIndex { index: 0, .. }`

2018-11-06 12:59 UTC, RalfJung commented on src/librustc_mir/transform/add_retag.rs
>                  ProjectionElem::Subslice { .. } |
`ConstantIndex` is just a constant offset on the pointer.

`Deref` *accesses memory*.

How is that the same...?

2018-11-06 13:04 UTC, oli-obk commented on src/librustc_mir/transform/add_retag.rs
>                  ProjectionElem::Subslice { .. } |
So will `ConstantIndex` if you don't immediately ref the value again. But that is true for `Deref`, too.

2018-11-06 13:14 UTC, RalfJung commented on src/librustc_mir/transform/add_retag.rs
>                  ProjectionElem::Subslice { .. } |
I am looking at miri's implementation of `ConstantIndex` right now. It boils down to `mplace_field`. That operation does NOT depend on memory.

Are we talking about the same thing...?

2018-11-06 13:28 UTC, oli-obk commented on src/librustc_mir/transform/add_retag.rs
>                  ProjectionElem::Subslice { .. } |
If you start out with an `Mplace`, yes. If you have an `Immediate::Scalar(Scalar::Ptr(_))` then you don't access memory. Miri just delays this to the last possible moment. This optimization probably does not represent the MIR semantics correctly.

The same goes for the `Index` projection, it accesses a temporary local, which is guaranteed immutable after assignment, because noone can access it. So you can assume that an `Index` projection is stable.

2018-11-06 15:33 UTC, RalfJung commented on src/librustc_mir/transform/add_retag.rs
>                  ProjectionElem::Subslice { .. } |
This is about places, `Immediate` is an operand, so I do not see how that is at all relevant.  I also do not see any way in which miri is not faithful.  Basically everything you are saying is a complete mystery to me. :)

`Index` is  subtle: If we are looking at an assignment statement, `place = operand;`, I agree it could be considered stable.  But we also do this for function calls, `place = foo(args)` (a terminator, but still it has a destination place). It is conceivable that we have `array[local] = foo(rawptr)` where `rawptr = &mut local as *mut _`. So I do not want to bet on its stability.

2018-11-06 15:35 UTC, RalfJung commented on src/librustc_mir/transform/add_retag.rs
>                  ProjectionElem::Subslice { .. } |
Basically the property this part of `is_stable` (the part about projections) cares about is: Is this projection just a constant offset onto the base place?  This is true for `Field`, because a struct field's offset is a constant.  (We assume vtables to not change.)  It is NOT true for `Deref` because that's just not an offset operation at all.  It is NOT true for `Index` because the offset is not a constant, it is a run-time-changeable value. However, it is true for the remaining projections.

2018-11-06 16:04 UTC, oli-obk commented on src/librustc_mir/transform/add_retag.rs
>                  ProjectionElem::Subslice { .. } |
> Index is subtle: If we are looking at an assignment statement, place = operand;, I agree it could be considered stable. But we also do this for function calls, place = foo(args) (a terminator, but still it has a destination place). It is conceivable that we have array[local] = foo(rawptr) where rawptr = &mut local as *mut _. So I do not want to bet on its stability.

That is indeed mutating the index: https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=69c1aab0dfa283dd32284aea3a3049c9 but not the local that we pass to the `Index` projection (a copy into a temp is made just before the index operation)

The question is how long does this value have to be stable? The actual local the MIR sees in the projection is guaranteed stable until after the MIR statement that the projection is used in.

I mixed up a few things, so I see that `Deref` definitely is the one that's different here, but I don't understand the scope of the `is_stable` guarantee. Does this have to be stable across multiple statements? arbitrary statements?

2018-11-06 16:07 UTC, RalfJung commented on src/librustc_mir/transform/add_retag.rs
>                  ProjectionElem::Subslice { .. } |
For statements is fine.

A function call is a terminator though. The place expression is once evaluated before the call (to use compute the place value used for storing the return value), and then the same place expression is used again after the call (for retagging).

2018-11-06 16:09 UTC, RalfJung commented on src/librustc_mir/transform/add_retag.rs
>                  ProjectionElem::Subslice { .. } |
> a copy into a temp is made just before the index operation

I'd rather not rely on MIR building always doing that.

We could, in principle, have an analysis that considers `Index` stable if the local in question never had its address taken. But we eventually need code that introduces a temporary anyway for `Deref`.

2018-11-06 16:26 UTC, oli-obk commented on src/librustc_mir/transform/add_retag.rs
>                  ProjectionElem::Subslice { .. } |
> I'd rather not rely on MIR building always doing that.

1. you can add a regression test for that
2. you can add a comment in https://github.com/rust-lang/rust/blob/bdfeace114d989f58614bbc255ac08306fbf18ef/src/librustc_mir/build/expr/as_place.rs#L89 stating that this is necessary for safety^TM

2018-11-06 16:49 UTC, RalfJung commented on src/librustc_mir/transform/add_retag.rs
>                  ProjectionElem::Subslice { .. } |
It's not really safety. It's an arbitrary limitation of this pass.

But sure, if you say it is a reasonable assumption to assume that we'll always have fresh locals for this, I can exploit that.

2018-11-06 16:57 UTC, RalfJung commented on src/librustc_mir/transform/add_retag.rs
>                  ProjectionElem::Subslice { .. } |
In your example, it anyway executes the function before evaluating the place... that is curious.

2018-11-06 17:10 UTC, RalfJung commented
I declared array index accesses stable places, and added a test.

2018-11-06 21:33 UTC, RalfJung commented
Ah, I need to change a bit how I emit `EscapeToRaw` so that we operate on the original reference before it gets casted, not on the raw ptr after it got casted.

2018-11-07 14:25 UTC, oli-obk requested changes

2018-11-07 14:31 UTC, RalfJung commented on src/librustc_mir/shim.rs
> +        let dropee_ptr = Place::Local(Local::new(1+0));
But I have no idea.^^

I guess this is because 0 is the return value, so 1+x is the x-th argument.

2018-11-07 14:36 UTC, RalfJung commented on src/librustc_mir/interpret/validity.rs
> +                    let place = self.ecx.ref_to_mplace(value)?;
In the last PR? Yes. `deref_operand` is a deref from the model perspective, but `ref_to_mplace` is a way to do ref-to-place conversion without triggering the model. I need that to make escape-to-raw work "after the fact": To let you transmute a ref to a raw, and then escape-to-raw.  Drops do that.

2018-11-07 14:36 UTC, RalfJung commented on src/librustc_mir/shim.rs
> +        let dropee_ptr = Place::Local(Local::new(1+0));
I added a  comment.

2018-11-07 14:41 UTC, RalfJung commented on src/librustc_mir/interpret/validity.rs
> +                    let place = self.ecx.ref_to_mplace(value)?;
Actually I do not know what you mean by "only actual change". There's also a new MIR statement and no more hook for taking a reference.

2018-11-07 14:48 UTC, oli-obk commented on src/librustc_mir/interpret/validity.rs
> +                    let place = self.ecx.ref_to_mplace(value)?;
I meant in this commit. every other callsite was changed to deref_operand

2018-11-07 14:48 UTC, oli-obk approved these changes

2018-11-07 16:51 UTC, RalfJung commented
The base PR landed. I take @oli-obk's green checkmark as an "r=me".

@bors r=oli-obk

2018-11-15 04:00 UTC, merged