Don't inline virtual calls (take 2)
rust-lang/rust pull request #55802
Opened 2018-11-09 00:30 UTC by wesleywiser

When I fixed the previous mis-optimizations, I didn't realize there were
actually two different places where we mutate `callsites` and both of
them should have the same behavior.

As a result, if a function was inlined and that function contained
virtual function calls, they were incorrectly being inlined. I also
added a test case which covers this.

2018-11-09 00:31 UTC, rust-highfive commented
r? @michaelwoerister

(rust_highfive has picked a reviewer for you, use r? to override)

2018-11-09 09:40 UTC, michaelwoerister commented
Thanks for the PR, @wesleywiser!

@rust-lang/compiler, who is best suited for reviewing MIR inlining changes?

2018-11-09 09:49 UTC, oli-obk requested changes
Just some nits

2018-11-09 09:49 UTC, oli-obk commented on src/librustc_mir/transform/inline.rs
> +                            true
Since this is now its own function, you can get rid of `is_virtual` and just return `None` here.

2018-11-09 09:49 UTC, oli-obk commented on src/librustc_mir/transform/inline.rs
> +                if let Some(instance) = Instance::resolve(self.tcx,
This can now just be `let instance = Instance::resolve(....)?;`

2018-11-10 03:13 UTC, wesleywiser commented
Good ideas @oli-obk!

2018-11-10 18:28 UTC, nagisa commented
@bors r+

2018-11-11 09:07 UTC, merged