Add Armv8-M Mainline targets
rust-lang/rust pull request #56000
Opened 2018-11-16 11:24 UTC by hug-dev

This commit enables the Armv8-M Mainline architecture profile.
It adds two targets:
  - `thumbv8m.main-none-eabi`
  - `thumbv8m.main-none-eabihf`

The second one uses the Floating Point Unit for floating point
operations. It mainly targets the Cortex-M33 processor, which
can have the optional Floating Point Unit extension.

It follows #55041 which does it for Baseline. I will rebase this branch on top of it when it is merged to not create conflicts as we have some files in common. To make it work, it still relies on the Cargo change to be merged (accepting "." in target names, rust-lang/cargo#6255).

The goal would also be to add this target in the CI so that the `core` library is available for everybody. To do this, some changes will be needed to compile successfully the needed libraries:

* `cc-rs` needs to be updated to allow compiling C code for Armv8-M architectures profiles. It is only a few lines to add [here](https://github.com/alexcrichton/cc-rs/blob/a76611ad9836fa8c44fa8220a1d2a96dd3b7d4b6/src/lib.rs#L1299). 
* Some assembly files in `builtins` in `compiler-rt` were not assembling for Armv8-M Mainline. I sent changes [upstream](https://reviews.llvm.org/D51854) to that project to fix that. The Rust version of `compiler-rt` will have to be updated to contain [that commit](https://github.com/llvm-mirror/compiler-rt/commit/a34cdf8bb498dc2f5dd415542f8e83261d2eeb88).

I tested it using the [Musca-A Test Chip board](https://developer.arm.com/products/system-design/development-boards/iot-test-chips-and-boards/musca-a-test-chip-board) but more intensively on the [Armv8-M FVP](https://developer.arm.com/products/system-design/fixed-virtual-platforms) (emulation platform). I am going to try to release my test code soon, once I tidy it up :+1:

2018-11-16 11:30 UTC, jamesmunns commented
CC https://github.com/rust-lang/rust/pull/55041 - which I think does the same

2018-11-16 11:30 UTC, jamesmunns commented
Ah sorry, now I've read the text, I missed the distinction between baseline and mainline :)

2018-11-17 13:47 UTC, parched requested changes

2018-11-17 13:47 UTC, parched commented on src/librustc_target/spec/thumbv8m_main_none_eabihf.rs
> +        llvm_target: "thumbv8m.main-none-eabi".to_string(),
Just noticed this one should be eabi*hf*.

2018-11-18 07:58 UTC, alexcrichton commented
I think it's best to hold off on merging until https://github.com/rust-lang/cargo/pull/6255 is sorted out (and https://github.com/rust-lang/rust/pull/55041), but can get back to this after those!

2018-12-02 21:42 UTC, nagisa commented
Cargo PR has been merged.

2018-12-03 10:40 UTC, hug-dev commented
I will rebase on top of #55041 when it is merged, including the change pointed by @parched

2018-12-06 14:09 UTC, hug-dev commented
@alexcrichton This one is now ready to be reviewed, if you have time

2018-12-07 11:05 UTC, merged