Implement the Re-rebalance coherence RFC
rust-lang/rust pull request #56145
Opened 2018-11-21 21:47 UTC by weiznich

This is the first time I touch anything in the compiler so just tell me if I got something wrong.

Big thanks to @sgrif for the pointers where to look for those things.
cc #55437

2018-11-21 21:47 UTC, rust-highfive commented
r? @varkor

(rust_highfive has picked a reviewer for you, use r? to override)

2018-11-21 22:14 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/458154908) ([raw log](https://api.travis-ci.org/v3/job/458154908/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:086f3864:start=1542837703580203705,finish=1542837757045396633,duration=53465192928
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-5.0
---
476 ./src/test/ui-fulldeps
472 ./src/libstd/sys/unix
468 ./src/test/ui/resolve
448 ./src/test/ui/traits
448 ./src/test/ui/re_rebalance_coherence
440 ./src/doc/unstable-book
436 ./src/test/ui/privacy
432 ./src/librustc_resolve
432 ./src/doc/unstable-book/src
---

[00:03:41] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:03:42] tidy error: /checkout/src/librustc/traits/coherence.rs:378: line longer than 100 chars
[00:03:43] some tidy checks failed
[00:03:43] 
[00:03:43] 
[00:03:43] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:03:43] 
[00:03:43] 
[00:03:43] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:03:43] Build completed unsuccessfully in 0:00:54
[00:03:43] Build completed unsuccessfully in 0:00:54
[00:03:43] Makefile:79: recipe for target 'tidy' failed
[00:03:43] make: *** [tidy] Error 1
The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:001d674e
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
Wed Nov 21 22:06:28 UTC 2018
---
travis_time:end:00464829:start=1542837989389297703,finish=1542837989393934802,duration=4637099
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:16908eb3
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:08ca4cd1
travis_time:start:08ca4cd1
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:0150aba8
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-11-22 21:21 UTC, varkor requested changes
I haven't checked over the tests yet, but the code looks good. I'll try to look at the tests soon.

2018-11-22 22:01 UTC, weiznich commented on src/doc/unstable-book/src/language-features/re-rebalance-coherence.md
> +Given `impl<P1..=Pn> Trait<T1..=Tn> for T0`, an impl is valid only if at
That's directly copied from the RFC. I think it should be "if and only if" but's not written there. (cc @sgrif who has written that thing)

2018-11-27 20:44 UTC, weiznich commented
@varkor I've addressed your review comments.

2018-12-03 21:53 UTC, weiznich commented
@varkor I've rebased the PR.

2018-12-05 22:29 UTC, varkor commented on src/libsyntax/feature_gate.rs
> +    // Use `?` as the Kleene "at most one" operator
You seem to have accidentally pulled in some extra changes with the rebase.

2018-12-05 22:37 UTC, varkor commented
At the moment, the fact that all the coherence tests have been duplicated under the new feature flag seems a little excessive. I'm not quite sure what the correct approach here is though: we do want to make sure we don't break anything. I wonder if it would be appropriate to run the tests in two modes, a bit like NLL does at the moment. Alternatively, we could have a few tests that cover a representative sample of existing cases, under the assumption that the algorithm is mostly the same anyway and when stabilised, the existing tests are going to come into effect anyway.

Could you point out which tests are new (and demonstrate the new behaviour), so I can check those in particular?

I think @nikomatsakis will have better ideas about the right solution re. tests, so I'm going to reassign. The actual change looks good to me, though.

r? @nikomatsakis

2018-12-06 10:09 UTC, weiznich commented
> Could you point out which tests are new (and demonstrate the new behaviour), so I can check those in particular?

[This one](https://github.com/rust-lang/rust/pull/56145/files#diff-5aaa46e5eb05735e9d603b98a850ee14) and [this one](https://github.com/rust-lang/rust/pull/56145/files#diff-6b1f9dd40f86d9d6559fddc781f2ec13) is new. All other tests are just a copied version of the old coherence tests with the `re_rebalance` feature enabled.

> At the moment, the fact that all the coherence tests have been duplicated under the new feature flag seems a little excessive. I'm not quite sure what the correct approach here is though: we do want to make sure we don't break anything. I wonder if it would be appropriate to run the tests in two modes, a bit like NLL does at the moment. Alternatively, we could have a few tests that cover a representative sample of existing cases, under the assumption that the algorithm is mostly the same anyway and when stabilised, the existing tests are going to come into effect anyway.

I'm not sure what would be a representative sample of the existing test cases here, nor I'm knowing what needs to be changed to run the existing tests using two modes. Would be great to get some more input here.

2018-12-06 12:30 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/464289057) ([raw log](https://api.travis-ci.org/v3/job/464289057/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:0ad13af8:start=1544096341158726535,finish=1544096344133678538,duration=2974952003
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-5.0
---
472 ./src/libstd/sys/unix
468 ./src/test/ui/resolve
460 ./src/test/ui/rust-2018
448 ./src/test/ui/traits
448 ./src/test/ui/re_rebalance_coherence
444 ./src/test/ui/privacy
440 ./src/librustc_resolve
424 ./src/doc/unstable-book
416 ./src/test/ui/associated-types
---
[00:48:59] .................................................................................................... 1100/5166
[00:49:01] .................................................................................................... 1200/5166
[00:49:03] .................................................................................................... 1300/5166
[00:49:06] .................................................................................................... 1400/5166
[00:49:08] ..............................................................................F..................... 1500/5166
[00:49:15] .................................................................................................... 1700/5166
[00:49:18] .................................................................................................... 1800/5166
[00:49:21] .................................................................................................... 1900/5166
[00:49:24] ...................................i................................................................ 2000/5166
---
[00:50:24] ...........................................i........................................................ 3700/5166
[00:50:25] ..................................................................................................i. 3800/5166
[00:50:26] .................................................................................................... 3900/5166
[00:50:32] .................................................................................................... 4000/5166
[00:50:37] ........................................................................F........................... 4100/5166
[00:50:43] .................................................................................................... 4300/5166
[00:50:47] ...............................................i.................................................... 4400/5166
[00:50:53] .................................................................................................... 4500/5166
[00:50:56] .................................................................................................... 4600/5166
---
[00:51:12] .................................................................................................... 5100/5166
[00:51:14] .....i............................................................
[00:51:14] failures:
[00:51:14] 
[00:51:14] ---- [ui] ui/feature-gates/feature-gate-re-rebalance-coherence.rs stdout ----
[00:51:14] 
[00:51:14] error: /checkout/src/test/ui/feature-gates/feature-gate-re-rebalance-coherence.rs:10: unexpected error: '10:1: 10:70: type parameter `T` must be used as the type parameter for some local type (e.g. `MyStruct<T>`) [E0210]'
[00:51:14] error: 1 unexpected errors found, 0 expected errors not found
[00:51:14] status: exit code: 1
[00:51:14] status: exit code: 1
[00:51:14] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/feature-gates/feature-gate-re-rebalance-coherence.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/feature-gates/feature-gate-re-rebalance-coherence/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/feature-gates/feature-gate-re-rebalance-coherence/auxiliary" "-A" "unused"
[00:51:14]     Error {
[00:51:14]         line_num: 10,
[00:51:14]         kind: Some(
[00:51:14]             Error
[00:51:14]             Error
[00:51:14]         ),
[00:51:14]         msg: "10:1: 10:70: type parameter `T` must be used as the type parameter for some local type (e.g. `MyStruct<T>`) [E0210]"
[00:51:14] ]
[00:51:14] 
[00:51:14] 
[00:51:14] thread '[ui] ui/feature-gates/feature-gate-re-rebalance-coherence.rs' panicked at 'explicit panic', src/tools/compiletest/src/runtest.rs:1358:13
[00:51:14] 
[00:51:14] 
[00:51:14] ---- [ui] ui/re_rebalance_coherence/coherence-pair-covered-uncovered-1.rs stdout ----
[00:51:14] 
[00:51:14] error: /checkout/src/test/ui/re_rebalance_coherence/coherence-pair-covered-uncovered-1.rs:23: unexpected error: '23:1: 23:46: only traits defined in the current crate can be implemented for arbitrary types [E0117]'
[00:51:14] error: 1 unexpected errors found, 0 expected errors not found
[00:51:14] status: exit code: 1
[00:51:14] status: exit code: 1
[00:51:14] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/re_rebalance_coherence/coherence-pair-covered-uncovered-1.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/re_rebalance_coherence/coherence-pair-covered-uncovered-1/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/re_rebalance_coherence/coherence-pair-covered-uncovered-1/auxiliary" "-A" "unused"
[00:51:14]     Error {
[00:51:14]         line_num: 23,
[00:51:14]         kind: Some(
[00:51:14]             Error
[00:51:14]             Error
[00:51:14]         ),
[00:51:14]         msg: "23:1: 23:46: only traits defined in the current crate can be implemented for arbitrary types [E0117]"
[00:51:14] ]
[00:51:14] 
[00:51:14] 
[00:51:14] thread '[ui] ui/re_rebalance_coherence/coherence-pair-covered-uncovered-1.rs' panicked at 'explicit panic', src/tools/compiletest/src/runtest.rs:1358:13
[00:51:14] 
[00:51:14] failures:
[00:51:14] failures:
[00:51:14]     [ui] ui/feature-gates/feature-gate-re-rebalance-coherence.rs
[00:51:14]     [ui] ui/re_rebalance_coherence/coherence-pair-covered-uncovered-1.rs
[00:51:14] test result: FAILED. 5140 passed; 2 failed; 24 ignored; 0 measured; 0 filtered out
[00:51:14] 
[00:51:14] thread 'main' panicked at 'Some tests failed', src/tools/compiletest/src/main.rs:503:22
[00:51:14] 
[00:51:14] 
[00:51:14] 
[00:51:14] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-5.0/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zunstable-options  -Ln [...]

2018-12-06 22:09 UTC, weiznich commented
I'm not sure why those 2 tests fail. The corresponding `.stderr` files containing exactly those error messages...

2018-12-06 22:59 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/464683522) ([raw log](https://api.travis-ci.org/v3/job/464683522/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:0479004c:start=1544134215075933908,finish=1544134217485299789,duration=2409365881
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-5.0
---
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://files.pythonhosted.org/packages/ff/94/838f88e12e6d3aadb427955e657f3fe3c763ee1ad9290d4601a287fed7d1/awscli-1.16.71-py2.py3-none-any.whl (1.4MB)
    0% |▎                               | 10kB 40.5MB/s eta 0:00:01
    1% |▌                               | 20kB 2.1MB/s eta 0:00:01
    2% |▊                               | 30kB 3.1MB/s eta 0:00:01
    2% |█                               | 40kB 2.0MB/s eta 0:00:01
---
472 ./src/libstd/sys/unix
468 ./src/test/ui/resolve
460 ./src/test/ui/rust-2018
448 ./src/test/ui/traits
448 ./src/test/ui/re_rebalance_coherence
444 ./src/test/ui/privacy
444 ./src/librustc_resolve
424 ./src/doc/unstable-book
416 ./src/test/ui/associated-types
---
[00:47:15] .................................................................................................... 1100/5183
[00:47:17] .................................................................................................... 1200/5183
[00:47:19] .................................................................................................... 1300/5183
[00:47:22] .................................................................................................... 1400/5183
[00:47:24] .................................................................................F.................. 1500/5183
[00:47:27] .............................i....................................................................i. 1600/5183
[00:47:34] .................................................................................................... 1800/5183
[00:47:37] .................................................................................................... 1900/5183
[00:47:41] .......................................i............................................................ 2000/5183
[00:47:45] .................................................................................................... 2100/5183
---
[00:48:38] ................................................i................................................... 3700/5183
[00:48:40] .................................................................................................... 3800/5183
[00:48:41] ...i................................................................................................ 3900/5183
[00:48:46] .................................................................................................... 4000/5183
[00:48:51] ...............................................................................F.................... 4100/5183
[00:48:57] .................................................................................................... 4300/5183
[00:49:01] ......................................................i............................................. 4400/5183
[00:49:06] .................................................................................................... 4500/5183
[00:49:09] .................................................................................................... 4600/5183
---
[00:49:24] .................................................................................................... 5100/5183
[00:49:26] ......................i............................................................
[00:49:26] failures:
[00:49:26] 
[00:49:26] ---- [ui] ui/feature-gates/feature-gate-re-rebalance-coherence.rs stdout ----
[00:49:26] 
[00:49:26] error: /checkout/src/test/ui/feature-gates/feature-gate-re-rebalance-coherence.rs:10: unexpected error: '10:1: 10:70: type parameter `T` must be used as the type parameter for some local type (e.g. `MyStruct<T>`) [E0210]'
[00:49:26] error: 1 unexpected errors found, 0 expected errors not found
[00:49:26] status: exit code: 1
[00:49:26] status: exit code: 1
[00:49:26] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/feature-gates/feature-gate-re-rebalance-coher_rebalance_coherence/coherence-pair-covered-uncovered-1.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/re_rebalance_coherence/coherence-pair-covered-uncovered-1/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/re_rebalance_coherence/coherence-pair-covered-uncovered-1/auxiliary" "-A" "unused"
[00:49:26]     Error {
[00:49:26]         line_num: 23,
[00:49:26]         kind: Some(
[00:49:26]             Error
[00:49:26]             Error
[00:49:26]         ),
[00:49:26]         msg: "23:1: 23:46: only traits defined in the current crate can be implemented for arbitrary types [E0117]"
[00:49:26] ]
[00:49:26] 
[00:49:26] 
[00:49:26] thread '[ui] ui/re_rebalance_coherence/coherence-pair-covered-uncovered-1.rs' panicked at 'explicit panic', src/tools/compiletest/src/runtest.rs:1358:13
[00:49:26] 
[00:49:26] failures:
[00:49:26] failures:
[00:49:26]     [ui] ui/feature-gates/feature-gate-re-rebalance-coherence.rs
[00:49:26]     [ui] ui/re_rebalance_coherence/coherence-pair-covered-uncovered-1.rs
[00:49:26] test result: FAILED. 5157 passed; 2 failed; 24 ignored; 0 measured; 0 filtered out
[00:49:26] 
[00:49:26] thread 'main' panicked at 'Some tests failed', src/tools/compiletest/src/main.rs:503:22
[00:49:26] 
[00:49:26] 
[00:49:26] 
[00:49:26] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-5.0/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--t [...]

2018-12-11 09:15 UTC, weiznich commented
@varkor @nikomatsakis Any news here?

2018-12-13 22:04 UTC, nikomatsakis approved these changes
Seems great! I would like before r+'ing though to spend a bit more time checking over the tests.

2018-12-14 12:07 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/467951070) ([raw log](https://api.travis-ci.org/v3/job/467951070/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:0e6e87c0:start=1544786423331187056,finish=1544786477558750623,duration=54227563567
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-5.0
---
472 ./src/libstd/sys/unix
468 ./src/test/ui/resolve
460 ./src/test/ui/rust-2018
448 ./src/test/ui/traits
448 ./src/test/ui/re_rebalance_coherence
444 ./src/test/ui/privacy
436 ./src/librustc_resolve
420 ./src/doc/unstable-book
416 ./src/test/ui/associated-types
---
[00:43:45] .................................................................................................... 1100/5225
[00:43:47] .................................................................................................... 1200/5225
[00:43:49] .................................................................................................... 1300/5225
[00:43:52] .................................................................................................... 1400/5225
[00:43:54] ................................................................................F................... 1500/5225
[00:43:57] ............................i....................................................................i.. 1600/5225
[00:44:03] .................................................................................................... 1800/5225
[00:44:06] .................................................................................................... 1900/5225
[00:44:09] ........................................i........................................................... 2000/5225
[00:44:13] .................................................................................................... 2100/5225
---
[00:45:06] ...................................................i................................................ 3700/5225
[00:45:07] .................................................................................................... 3800/5225
[00:45:09] ........i........................................................................................... 3900/5225
[00:45:13] .................................................................................................... 4000/5225
[00:45:21] .......................................................................................FF........F.. 4100/5225
[00:45:25] ..........F......................................................................................... 4200/5225
[00:45:31] ..............................................................................................i..... 4400/5225
[00:45:36] .................................................................................................... 4500/5225
[00:45:40] .................................................................................................... 4600/5225
[00:45:43] .................................................................................................... 4700/5225
[00:45:43] .................................................................................................... 4700/5225
[00:45:47] ................................................................................i................... 4800/5225
[00:45:50] .................................................................................................... 4900/5225
[00:45:53] .................................................................................................... 5000/5225
[00:45:56] .................................................................................................... 5100/5225
[00:45:58] ................................................................i................................... 5200/5225
86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/feature-gates/feature-gate-re-rebalance-coherence/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/feature-gates/feature-gate-re-rebalance-coherence/auxiliary" "-A" "unused"
[00:45:59] ------------------------------------------
[00:45:59] 
[00:45:59] ------------------------------------------
[00:45:59] stderr:
[00:45:59] stderr:
[00:45:59] ------------------------------------------
[00:45:59] {"message":"type parameter `T` must be used as the type parameter for some local type (e.g., `MyStruct<T>`)","code":{"code":"E0210","explanation":"\nThis error indicates a violation of one of Rust's orphan rules for trait\nimplementations. The rule concerns the use of type parameters in an\nimplementation of a foreign trait (a trait defined in another crate), and\nstates that type parameters must be \"covered\" by a local type. To understand\nwhat this means, it is perhaps easiest to consider a few examples.\n\nIf `ForeignTrait` is a trait defined in some external crate `foo`, then the\nfollowing trait `impl` is an error:\n\n```compile_fail,E0210\n# #[cfg(for_demonstration_only)]\nextern crate foo;\n# #[cfg(for_demonstration_only)]\nuse foo::ForeignTrait;\n# use std::panic::UnwindSafe as ForeignTrait;\n\nimpl<T> ForeignTrait for T { } // error\n# fn main() {}\n```\n\nTo work around this, it can be covered with a local type, `MyType`:\n\n```\n# use std::panic::on the design of the orphan rules, see [RFC 1023].\n\n[RFC 1023]: https://github.com/rust-lang/rfcs/blob/master/text/1023-rebalancing-coherence.md\n"},"level":"error","spans":[{"file_name":"/checkout/src/test/ui/feature-gates/feature-gate-re-rebalance-coherence.rs","byte_start":226,"byte_end":295,"line_start":10,"line_end":10,"column_start":1,"column_end":70,"is_primary":true,"text":[{"text":"impl<'a, T:'a, Tab> QueryFragment<Oracle> for BatchInsert<'a, T, Tab> {}","highlight_start":1,"highlight_end":70}],"label":"type parameter `T` must be used as the type parameter for some local type","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"only traits defined in the current crate can be implemented for a type parameter","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":"error[E0210]: type parameter `T` must be used as the type parameter for some local type (e.g., `MyStruct<T>`)\n  --> /checkout/src/test/ui/feature-gates/feature-gate-re-rebalance-coherence.rs:10:1\n   |\nLL | impl<'a, T:'a, Tab> QueryFragment<Oracle> for BatchInsert<'a, T, Tab> {}\n   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type parameter `T` must be used as the type parameter for some local type\n   |\n   = note: only traits defined in the current crate can be implemented for a type parameter\n\n"}
[00:45:59] {"message":"aborting due to previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"error: aborting due to previous error\n\n"}
[00:45:59] {"message":"For more information about this error, try `rustc --explain E0210`.","code":null,"level":"","spans":[],"children":[],"rendered":"For more information about this error, try `rustc --explain E0210`.\n"}
[00:45:59] ------------------------------------------
[00:45:59] 
[00:45:59] 
[00:45:59] thread '[ui] ui/feature-gates/feature-gate-re-rebalance-coherence.rs' panicked at 'explicit panic', src/tools/compiletest/src/runtest.rs:3252:9
[00:45:59] 
[00:45:59]  [...]

2018-12-19 17:07 UTC, nikomatsakis commented
I forgot about this question that @varkor raised:

> At the moment, the fact that all the coherence tests have been duplicated under the new feature flag seems a little excessive.

One option here is to rewrite the duplicated tests using `revisions`. The idea is to include a comment like:

```
// revisions: old new
```

This will cause the same test to be built twice, once with `#[cfg(old)]` and once with `#[cfg(new)]` in scope.

You can then do things like:

```rust
#![cfg_attr(new, feature(new_algorithm))]
```

@weiznich -- do you want to take a shot at collapsing the tests this way?

2018-12-19 22:42 UTC, weiznich commented
@nikomatsakis I will try that. What's the right strategy [here](https://github.com/rust-lang/rust/pull/56145/files#diff-cee15537dc425f257a8d9061279cd500R13)? In that case there are already revisions.

2018-12-20 19:21 UTC, nikomatsakis commented on src/test/ui/re_rebalance_coherence/coherence-cow.rs
> +// revisions: a b c
Well, in this case you would have to add another set of three revisions, I suppose. e.g., a, re_a, b, re_b, c, re_c

2019-01-02 18:05 UTC, nikomatsakis commented
@bors r+

2019-01-03 11:38 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/474790428) ([raw log](https://api.travis-ci.org/v3/job/474790428/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:03:44] * rc_raw                           lib      stable       1.17.0  
[00:03:44] * rc_unique                        lib      stable       1.4.0   
[00:03:44] * rc_weak                          lib      stable       1.4.0   
[00:03:44] * rchunks                          lib      stable       1.31.0  
[00:03:44] * re_rebalance_coherence           lang     unstable     1.32.0  
[00:03:44] * read_initializer                 lib      unstable     None    
[00:03:44] * receiver_into_iter               lib      stable       1.1.0   
[00:03:44] * receiver_trait                   lib      unstable     None    
[00:03:44] * receiver_try_iter                lib      stable       1.15.0  
---
[00:54:54] * rc_raw                           lib      stable       1.17.0  
[00:54:54] * rc_unique                        lib      stable       1.4.0   
[00:54:54] * rc_weak                          lib      stable       1.4.0   
[00:54:54] * rchunks                          lib      stable       1.31.0  
[00:54:54] * re_rebalance_coherence           lang     unstable     1.32.0  
[00:54:54] * read_initializer                 lib      unstable     None    
[00:54:54] * receiver_into_iter               lib      stable       1.1.0   
[00:54:54] * receiver_trait                   lib      unstable     None    
[00:54:54] * receiver_try_iter                lib      stable       1.15.0  
---
[01:02:49] test [run-pass] run-pass/ranges-precedence.rs ... ok
[01:02:49] test [run-pass] run-pass/raw-str.rs ... ok
[01:02:50] test [run-pass] run-pass/rcvr-borrowed-to-region.rs ... ok
[01:02:50] test [run-pass] run-pass/range_inclusive.rs ... ok
[01:02:50] test [run-pass] run-pass/re_rebalance_coherence/coherence-bigint-int.rs ... ok
[01:02:50] test [run-pass] run-pass/re_rebalance_coherence/coherence-bigint-vecint.rs ... ok
[01:02:50] test [run-pass] run-pass/re_rebalance_coherence/coherence-blanket.rs ... ok
[01:02:50] test [run-pass] run-pass/re_rebalance_coherence/coherence-impl-in-fn.rs ... ok
[01:02:50] test [run-pass] run-pass/re_rebalance_coherence/coherence-covered-type-parameter.rs ... ok
[01:02:51] test [run-pass] run-pass/raw-fat-ptr.rs ... ok
[01:02:51] test [run-pass] run-pass/re_rebalance_coherence/coherence-multidispatch-tuple.rs ... ok
[01:02:51] test [run-pass] run-pass/re_rebalance_coherence/coherence-negative-impls-safe.rs ... ok
[01:02:51] test [run-pass] run-pass/re_rebalance_coherence/coherence-iterator-vec-any-elem.rs ... ok
[01:02:51] test [run-pass] run-pass/re_rebalance_coherence/coherence-iterator-vec.rs ... ok
[01:02:51] test [run-pass] run-pass/re_rebalance_coherence/coherence-subtyping.rs ... ok
[01:02:51] test [run-pass] run-pass/re_rebalance_coherence/coherence-rfc447-constrained.rs ... ok
[01:02:51] test [run-pass] run-pass/re_rebalance_coherence/coherence-where-clause.rs ... ok
[01:02:51] test [run-pass] run-pass/re_rebalance_coherence/coherence_copy_like.rs ... ok
[01:02:51] test [run-pass] run-pass/reachable-unnameable-type-alias.rs ... ok
[01:02:51] test [run-pass] run-pass/re_rebalance_coherence/re-rebalance-coherence.rs ... FAILED
[01:02:52] test [run-pass] run-pass/reexport-star.rs ... ok
[01:02:52] test [run-pass] run-pass/reexport-should-still-link.rs ... ok
[01:02:52] test [run-pass] run-pass/reachable-unnameable-items.rs ... ok
[01:02:52] test [run-pass] run-pass/reexport-test-harness-main.rs ... ok
---
[01:04:37] test [run-pass] run-pass/zero-sized/zero-sized-vec-deque-push.rs ... ok
[01:04:37] 
[01:04:37] failures:
[01:04:37] 
[01:04:37] ---- [run-pass] run-pass/re_rebalance_coherence/re-rebalance-coherence.rs stdout ----
[01:04:37] normalized stderr:
[01:04:37] warning: struct is never constructed: `Oracle`
[01:04:37]   --> $DIR/re-rebalance-coherence.rs:9:1
[01:04:37] LL | struct Oracle;
[01:04:37]    | ^^^^^^^^^^^^^^
[01:04:37]    |
[01:04:37]    = note: #[warn(dead_code)] on by default
[01:04:37]    = note: #[warn(dead_code)] on by default
[01:04:37] 
[01:04:37] 
[01:04:37] 
[01:04:37] 
[01:04:37] The actual stderr differed from the expected stderr.
[01:04:37] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/re_rebalance_coherence/re-rebalance-coherence/re-rebalance-coherence.stderr
[01:04:37] To update references, rerun the tests and pass the `--bless` flag
[01:04:37] To only update this specific test, also pass `--test-args re_rebalance_coherence/re-rebalance-coherence.rs`
[01:04:37] error: 1 errors occurred comparing output.
[01:04:37] status: exit code: 0
[01:04:37] status: exit code: 0
[01:04:37] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/run-pass/re_rebalance_coherence/re-rebalance-coherence.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/re_rebalance_coherence/re-rebalance-coherence/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/re_rebalance_coherence/re-rebalance-coherence/auxiliary"
[01:04:37] ------------------------------------------
[01:04:37] 
[01:04:37] ------------------------------------------
[01:04:37] stderr:
[01:04:37] stderr:
[01:04:37] ------------------------------------------
[01:04:37] {"message":"struct is never constructed: `Oracle`","code":{"code":"dead_code","explanation":null},"level":"warning","spans":[{"file_name":"/checkout/src/test/run-pass/re_rebalance_coherence/re-rebalance-coherence.rs","byte_start":154,"byte_end":168,"line_start":9,"line_end":9,"column_start":1,"column_end":15,"is_primary":true,"text":[{"text":"struct Oracle;","highlight_start":1,"highlight_end":15}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[{"message":"#[warn(dead_code)] on by default","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":"warning: struct is never constructed: `Oracle`\n  --> /checkout/src/test/run-pass/re_rebalance_coherence/re-rebalance-coherence.rs:9:1\n   |\nLL | struct Oracle;\n   | ^^^^^^^^^^^^^^\n   |\n   = note: #[warn(dead_code)] on by default\n\n"}
[01:04:37] ------------------------------------------
[01:04:37] 
[01:04:37] 
[01:04:37] thread '[run-pass] run-pass/re_rebalance_coherence/re-rebalance-coherence.rs' panicked at 'explicit panic', src/tools/compiletest/src/runtest.rs:3245:9
[01:04:37] 
[01:04:37] 
[01:04:37] failures:
[01:04:37] failures:
[01:04:37]     [run-pass] run-pass/re_rebalance_coherence/re-rebalance-coherence.rs
[01:04:37] test result: FAILED. 2942 passed; 1 failed; 7 ignored; 0 measured; 0 filtered out
[01:04:37] 
[01:04:37] thread 'main' panicked at 'Some tests failed', src/tools/compiletest/src/main.rs:495:22
[01:04:37] 
[01:04:37] 
[01:04:37] 
[01:04:37] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/run-pass" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "run-pass" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-6.0/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zunstable [...]

2019-01-03 17:51 UTC, nikomatsakis commented
@bors r+

2019-01-04 23:05 UTC, cramertj commented
@bors r=nikomatsakis

2019-01-05 03:36 UTC, merged