Implement chalk unification routines
rust-lang/rust pull request #56214
Opened 2018-11-25 15:48 UTC by scalexm

`ResolventOps` and `AggregateOps` are mostly straightforwardly translated from chalk. I had caught a few bugs already in my `chalk` branch and backported fixes to this branch, but there may be other ones left.

Fixes #54935.

r? @nikomatsakis

2018-11-29 19:13 UTC, nikomatsakis requested changes
Everything seems fine except for the question of unifying two existential inference variables...

2018-11-29 19:13 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/nll/type_check/relate_tys.rs
> +        // No-op
Maybe `panic!("should never be invoked with eager normalization")`?

2018-11-29 19:16 UTC, scalexm commented on src/librustc/infer/nll_relate/mod.rs
> +                                return Err(TypeError::Mismatch);
yes that's definitely a mistake

2018-11-29 19:18 UTC, scalexm commented on src/librustc/infer/nll_relate/mod.rs
> +//! free ones. This is ok because:
no "bound type vars", so e.g. no `for<T> ...`

2018-11-29 19:53 UTC, scalexm commented on src/librustc/infer/nll_relate/mod.rs
> +//! free ones. This is ok because:
I replaced with "no bound types at all" (I dropped "vars")

2018-11-29 20:02 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/461451429) ([raw log](https://api.travis-ci.org/v3/job/461451429/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:1b7891b0:start=1543521223457964898,finish=1543521288000296381,duration=64542331483
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-5.0
---
[00:05:01]    Compiling syntax_pos v0.0.0 (/checkout/src/libsyntax_pos)
[00:05:06]    Compiling rustc_errors v0.0.0 (/checkout/src/librustc_errors)
[00:06:24]    Compiling proc_macro v0.0.0 (/checkout/src/libproc_macro)
[00:06:33]    Compiling syntax_ext v0.0.0 (/checkout/src/libsyntax_ext)
[00:06:53] error[E0026]: variant `infer::type_variable::TypeVariableValue::Unknown` does not have a field named `_universe`
[00:06:53]    --> src/librustc/infer/nll_relate/mod.rs:763:54
[00:06:53]     |
[00:06:53] 763 |                         TypeVariableValue::Unknown { _universe } => {
[00:06:53]     |                                                      |
[00:06:53]     |                                                      |
[00:06:53]     |                                                      variant `infer::type_variable::TypeVariableValue::Unknown` does not have this field
[00:06:53]     |                                                      help: did you mean: `universe`
travis_time:end:15ff275a:start=1543521296609365783,finish=1543521721649467152,duration=425040101369
The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:000ecf04
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-11-29 20:52 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/461467065) ([raw log](https://api.travis-ci.org/v3/job/461467065/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:03844152:start=1543523452625873901,finish=1543523521934382457,duration=69308508556
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-5.0
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-11-29 21:22 UTC, nikomatsakis commented
@bors r+

2018-11-29 21:43 UTC, scalexm commented
@bors p=1
(I'm setting a priority because I'd like this to land quickly, as I'll be less available starting in December, if anybody has an issue with that please contact me)

2018-11-30 06:44 UTC, rust-highfive commented
The job `dist-x86_64-linux-alt` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/461619503) ([raw log](https://api.travis-ci.org/v3/job/461619503/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[01:50:08]     Finished dev [unoptimized + debuginfo] target(s) in 2m 59s
[01:50:08]   Installing /cargo/bin/cargo-vendor
[01:50:08] warning: be sure to add `/cargo/bin` to your PATH to be able to run the installed binaries
[01:50:12]  Downloading openssl-src v111.0.1+1.1.1
[01:50:52] warning: spurious network error (2 tries remaining): failed to download from `https://crates.io/api/v1/crates/openssl-src/111.0.1+1.1.1/download`
[01:51:32] warning: spurious network error (1 tries remaining): failed to download from `https://crates.io/api/v1/crates/openssl-src/111.0.1+1.1.1/download`
[01:52:18]  Downloading openssl-src v111.0.1+1.1.1
[01:52:58] warning: spurious network error (2 tries remaining): failed to download from `https://crates.io/api/v1/crates/openssl-src/111.0.1+1.1.1/download`
[01:53:38] warning: spurious network error (1 tries remaining): failed to download from `https://crates.io/api/v1/crates/openssl-src/111.0.1+1.1.1/download`
[01:54:18] 
[01:54:18] Caused by:
[01:54:18]   failed to fetch package
[01:54:18] 
[01:54:18] 
[01:54:18] Caused by:
[01:54:18]   unable to get packages from source
[01:54:18] 
[01:54:18] Caused by:
[01:54:18]   failed to download from `https://crates.io/api/v1/crates/openssl-src/111.0.1+1.1.1/download`
[01:54:18] Caused by:
[01:54:18]   [28] Timeout was reached
[01:54:18] 
[01:54:18] 
---
travis_time:end:06dbf69a:start=1543560158822313955,finish=1543560158832006520,duration=9692565
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:00da24a3
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:0195f6a4
travis_time:start:0195f6a4
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:05b8591e
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-11-30 08:44 UTC, scalexm commented
@bors retry

2018-11-30 11:50 UTC, rust-highfive commented
The job `x86_64-apple` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/461695358) ([raw log](https://api.travis-ci.org/v3/job/461695358/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[02:05:31] 
[02:05:31] ---- /Users/travis/build/rust-lang/rust/src/doc/unstable-book/src/language-features/generators.md - generators::_::Generators_as_state_machines (line 166) stdout ----
[02:05:31] error: linking with `cc` failed: signal: 4
[02:05:31]   |
[02:05:31]   = note: "cc" "-m64" "-L" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib" "/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/rustdoctestB4fTwe/rust_out.rust_out.7rcbfp3g-cgu.0.rcgu.o" "/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/rustdoctestB4fTwe/rust_out.rust_out.7rcbfp3g-cgu.1.rcgu.o" "/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/rustdoctestB4fTwe/rust_out.rust_out.7rcbfp3g-cgu.2.rcgu.o" "/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/rustdoctestB4fTwe/rust_out.rust_out.7rcbfp3g-cgu.3.rcgu.o" "/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/rustdoctestB4fTwe/rust_out.rust_out.7rcbfp3g-cgu.4.rcgu.o" "-o" "/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/rustdoctestB4fTwe/rust_out" "/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/rustdoctestB4fTwe/rust_out.33dyzt1ekirinwy8.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/libstd-ae69a760be8b7053.rlib" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-e4468e88cc678cc0.rlib" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/libunwind-d4351380f83add85.rlib" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/liblibc-e14d637badce231e.rlib" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/liballoc-85796c6312c279e8.rlib" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/libcore-879924ea8a001728.rlib" "/Users/travis/build/rust-lang/rust/build/x86_64-apple-darwin/stage2/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-5d6e0e7618d0f2e8.rlib" "-lSystem" "-lresolv" "-lc" "-lm"
[02:05:32] 
[02:05:32] thread '/Users/travis/build/rust-lang/rust/src/doc/unstable-book/src/language-features/generators.md - generators::_::Generators_as_state_machines (line 166)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:323:13
[02:05:32] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[02:05:32] 
[02:05:32] 
[02:05:32] 
[02:05:32] failures:
[02:05:32]     /Users/travis/build/rust-lang/rust/src/doc/unstable-book/src/language-features/generators.md - generators::_::Generators_as_state_machines (line 166)
[02:05:32] 
[02:05:32] test result: FAILED. 5 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
[02:05:32] 
[02:05:32] make: *** [check] Error 1
[02:05:32] 
[02:05:32] command did not execute successfully: "/Users/travis/build/rust-lang/rust/build/bootstrap/debug/rustdoc" "--test" "/Users/travis/build/rust-lang/rust/src/doc/unstable-book/src/language-features/generators.md" "--test-args" ""
[02:05:32] expected success, got: exit code: 101
[02:05:32] 
---
travis_fold:start:after_failure.2
travis_time:start:1cf1d584
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
total 1352
drwx------  28 travis  staff    952 Nov 30 11:48 .
-rw-------@  1 travis  staff  13746 Nov 30 11:48 overflow_2018-11-30-114821_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff   1428 Nov 30 11:47 foo_2018-11-30-114755_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff   1418 Nov 30 11:47 m4_2018-11-30-114723_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff   1432 Nov 30 11:47 bar_2018-11-30-114713_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  10661 Nov 30 11:47 b_2018-11-30-114712_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff   1444 Nov 30 11:47 bar_2018-11-30-114712_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  62244 Nov 30 11:06 a_2018-11-30-110617_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  37481 Nov 30 11:06 a_2018-11-30-110614_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  60386 Nov 30 11:06 a_2018-11-30-110608-1_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  37237 Nov 30 11:06 a_2018-11-30-110608_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  10142 Nov 30 11:06 a_2018-11-30-110604_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff   9873 Nov 30 11:05 a_2018-11-30-110559_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff   9876 Nov 30 11:05 a_2018-11-30-110552-1_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff   9795 Nov 30 11:05 a_2018-11-30-110552_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  10034 Nov 30 11:05 a_2018-11-30-110518_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  63125 Nov 30 11:05 a_2018-11-30-110509_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  65090 Nov 30 11:05 a_2018-11-30-110506-2_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  63914 Nov 30 11:05 a_2018-11-30-110506-1_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  64247 Nov 30 11:05 a_2018-11-30-110506_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  11730 Nov 30 11:02 a_2018-11-30-110255_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff   9897 Nov 30 11:02 a_2018-11-30-110209_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  10304 Nov 30 11:00 a_2018-11-30-110057_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  10486 Nov 30 10:59 a_2018-11-30-105958-1_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  10486 Nov 30 10:59 a_2018-11-30-105958_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  10214 Nov 30 10:59 a_2018-11-30-105926_Traviss-Mac-1044.crash
-rw-------@  1 travis  staff  37481 Nov 30 10:57 a_2018-11-30-105740_Traviss-Mac-1044.crash
drwx------+ 15 travis  staff    510 Jan 25  2018 ..
travis_fold:end:after_failure.2
travis_fold:start:after_failure.3
travis_time:start:0586105e
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
$ find $HOME/Library/Logs/DiagnosticReports -type f -name '*.crash' -not -name '*.stage2-*.crash' -not -name 'com.apple.CoreSimulator.CoreSimulatorService-*.crash' -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \; -exec head -750 {} \; -exec echo travis_fold":"end:crashlog \; || true
travis_fold:start:crashlog
/Users/travis/Library/Logs/DiagnosticReports/a_2018-11-30-105740_Traviss-Mac-1044.crash
Process:               a [58484]
Path:                  /Users/USER/*/a
Identifier:            a
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [58479]
Responsible:           a [58484]
User ID:               501
Date/Time:             2018-11-30 10:57:39.522 +0000
OS Version:            Mac OS X 10.13.3 (17D47)
Anonymous UUID:        A91A3A70-3ADA-D7A9-5891-C1A67A5778E7
Anonymous UUID:        A91A3A70-3ADA-D7A9-5891-C1A67A5778E7
Time Awake Since Boot: 4600 seconds
System Integrity Protection: enabled
Crashed Thread:        1
Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x0000700008233e50
Exception Note:        EXC_CORPSE_NOTIFY
VM Regions Near 0x700008233e50:
    __LINKEDIT             000000011499a000-00000001149b5000 [  108K] r--/rwx SM=COW  /usr/lib/dyld
--> Stack Gua [...]

2018-11-30 12:37 UTC, scalexm commented
cc @rust-lang/infra any idea whether the above error is spurious? I can't reproduce locally on a mac.

2018-11-30 12:44 UTC, scalexm commented
@bors retry
I see a similar error in https://github.com/rust-lang/rust/pull/55767#issuecomment-441182619

2018-11-30 15:48 UTC, scalexm commented
@bors retry

> ---- net::tcp::tests::connect_timeout_unbound stdout ----
28706thread 'net::tcp::tests::connect_timeout_unbound' panicked at 'called `Result::unwrap_err()` on an `Ok` value: TcpStream { addr: V4(127.0.0.1:3856), peer: V4(127.0.0.1:3856), socket: 800 }', src\libcore\result.rs:1009:5

It seems like this PR will never land!

2018-11-30 16:15 UTC, scalexm commented
@bors p=0
In case it fails again, I’m giving back the priority to other PRs.

2018-11-30 17:56 UTC, scalexm commented
Same failure as in 
https://github.com/rust-lang/rust/pull/55011#issuecomment-443215660

2018-11-30 18:18 UTC, kennytm commented
@bors retry

2018-11-30 22:01 UTC, merged