Stabilize feature `macro_at_most_once_rep`
rust-lang/rust pull request #56245
Opened 2018-11-26 17:04 UTC by mark-i-m

a.k.a. `?` Kleene operator :tada: 

cc #48075 

r? @Centril

2018-11-26 17:14 UTC, Centril requested changes
Pending tests, everything except a comment looks good. :)

2018-11-26 17:14 UTC, Centril commented on src/libsyntax/ext/tt/quoted.rs
>          // #1 is a `?` (needs feature gate)
```suggestion
         // #1 is a `?`
```

2018-11-26 17:16 UTC, Centril approved these changes

2018-11-26 17:16 UTC, mark-i-m commented
Woah, you're fast.

Thanks!

2018-11-26 19:14 UTC, mark-i-m commented
Travis is passing, so i guess we just wait for FCP in 4 days?

2018-11-26 19:34 UTC, Centril commented
@mark-i-m I don't have r+ myself so maybe @petrochenkov or @eddyb could r+; we could also wait those 4 days but I wouldn't mind just merging now. ^.^

2018-11-26 20:15 UTC, mark-i-m commented
Oh, it's interesting that rust-highfive bot didn't complain.

r? @petrochenkov

2018-11-26 23:06 UTC, petrochenkov commented
@bors r+

2018-11-27 20:13 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/460418253) ([raw log](https://api.travis-ci.org/v3/job/460418253/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:1eff35cd:start=1543346745266454500,finish=1543346747630103427,duration=2363648927
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-5.0
---
[00:46:23] .................................................................................................... 2700/5062
[00:46:26] .................................................................................................... 2800/5062
[00:46:29] .................................................................................................... 2900/5062
[00:46:32] .................................................................................................... 3000/5062
[00:46:36] ............................................................F.......i............................... 3100/5062
[00:46:42] ...............................ii..i..ii............................................................ 3300/5062
[00:46:46] .................................................................................................... 3400/5062
[00:46:49] .................................................................................................... 3500/5062
[00:46:52] ............ii...................................................................................... 3600/5062
---
[00:47:34] 43 error: unexpected end of macro invocation
[00:47:34] -   --> $DIR/macro-at-most-once-rep-2018.rs:41:15
[00:47:34] +   --> $DIR/macro-at-most-once-rep-2018.rs:39:15
[00:47:34] 45    |
[00:47:34] 46 LL | macro_rules! barplus {
[00:47:34] 47    | -------------------- when calling this macro
[00:47:34] 77    |     ^^^^^^^^^^^ missing tokens in macro arguments
[00:47:34] 78 
[00:47:34] 79 error: unexpected end of macro invocation
[00:47:34] -   --> $DIR/macro-at-most-once-rep-2018.rs:46:14
[00:47:34] -   --> $DIR/macro-at-most-once-rep-2018.rs:46:14
[00:47:34] +   --> $DIR/macro-at-most-once-rep-2018.rs:46:15
[00:47:34] 81    |
[00:47:34] 82 LL | macro_rules! barstar {
[00:47:34] 83    | -------------------- when calling this macro
[00:47:34] 
[00:47:34] The actual stderr differed from the expected stderr.
[00:47:34] The actual stderr differed from the expected stderr.
[00:47:34] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/macros/macro-at-most-once-rep-2018/macro-at-most-once-rep-2018.stderr
[00:47:34] To update references, rerun the tests and pass the `--bless` flag
[00:47:34] To only update this specific test, also pass `--test-args macros/macro-at-most-once-rep-2018.rs`
[00:47:34] error: 1 errors occurred comparing output.
[00:47:34] status: exit code: 1
[00:47:34] status: exit code: 1
[00:47:34] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/macros/macro-at-most-once-rep-2018.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/macros/macro-at-most-once-rep-2018/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--edition=2018" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/macros/macro-at-most-once-rep-2018/auxiliary" "-A" "unused"
[00:47:34] ------------------------------------------
[00:47:34] 
[00:47:34] ------------------------------------------
[00:47:34] stderr:
[00:47:34] stderr:
[00:47:34] ------------------------------------------
[00:47:34] {"message":"the `?` macro repetition operator does not take a separator","code":null,"level":"error","spans":[{"file_name":"/checkout/src/test/ui/macros/macro-at-most-once-rep-2018.rs","byte_start":634,"byte_end":635,"line_start":20,"line_end":20,"column_start":10,"column_end":11,"is_primary":true,"text":[{"text":"    ($(a),?) => {}; //~ERROR the `?` macro repetition operator","highlight_start":10,"highlight_end":11}],"label":null,"suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: the `?` macro repetition operator does not take a separator\n  --> /checkout/src/test/ui/macros/macro-at-most-once-rep-2018.rs:20:10\n   |\nLL |     ($(a),?) => {}; //~ERROR the `?` macro repetition operator\n   |          ^\n\n"}
[00:47:34] {"message":"no rules expected the token `?`","code":null,"level":"error","spans":[{"file_name":"/checkout/src/test/ui/macros/macro-at-most-once-rep-2018.rs","byte_start":890,"byte_end":891,"line_start":34,"line_end":34,"column_start":11,"column_end":12,"is_primary":true,"text":[{"text":"    foo!(a?); //~ ERROR no rules expected the token `?`","highlight_start":11,"highlight_end":12}],"label":"no rules expected this token in macro call","suggested_replacement":null,"suggestion_applicability":null,"expansion":null},{"file_name":"/checkout/src/test/ui/macros/macro-at-most-once-rep-2018.rs","byte_start":565,"byte_end":581,"line_start":15,"line_end":15,"column_start":1,"column_end":17,"is_primary":false,"text":[{"text":"macro_rules! foo {","highlight_start":1,"highlight_end":17}],"label":"when calling this macro","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: no rules expected the token `?`\n  --> /checkout/src/test/ui/macros/macro-at-most-once-rep-2018.rs:34:11\n   |\nLL | macro_rules! foo {\n   | ---------------- when lumn_start":11,"column_end":12,"is_primary":true,"text":[{"text":"    foo!(a?a?a); //~ ERROR no rules expected the token `?`","highlight_start":11,"highlight_end":12}],"label":"no rules expected this token in macro call","suggested_replacement":null,"suggestion_applicability":null,"expansion":null},{"file_name":"/checkout/src/test/ui/macros/macro-at-most-once-rep-2018.rs","byte_start":565,"byte_end":581,"line_start":15,"line_end":15,"column_start":1,"column_end":17,"is_primary":false,"text":[{"text":"macro_rules! foo {","highlight_start":1,"highlight_end":17}],"label":"when calling this macro","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"error: no rules expected the token `?`\n  --> /checkout/src/test/ui/macros/macro-at-most-once-rep-2018.rs:36:11\n   |\nLL | macro_rules! foo {\n   | ---------------- when calling this macro\n...\nLL |     foo!(a?a?a); //~ ERROR no rules expected the token `?`\n   |           ^ no rules expected this token in macro call\n\n"}
[00:47:34] {"message":"unexpected end of macro invocation","code":null,"level":"error","spans":[{"file_name":"/checkout/src/test/ui/macros/macro-at-most-once-rep-2018.rs","byte_start":1057,"byte_end":1068,"line_start":38,"line_end":38,"column_start":5,"column_end":16,"is_primary":true,"text":[{"text":"    barplus!(); //~ERROR unexpected end of macro invocation","highlight_start":5,"highlight_end":16}],"label":"missing tokens in macro arguments","suggested_replacement":null,"suggestion_applicability":null,"expansion":null},{"file_name":"/checkout/src/test/ui/macros/macro-at-most-once-rep-2018.rs","byte_start":691,"byte_end":711,"line_start":23,"line_end":23,"column_start":1,"column_end":21,"is_primary":false,"text":[{"text":"macro_rules! barplus {","highlight_start":1,"highlight_end":21}],"label":"when calling this macro","suggested_replacement":null,"suggestion_applicability":null,"expansion":null}],"children":[],"rendered":"erro [...]

2018-11-28 00:52 UTC, Mark-Simulacrum commented
@bors r+ p=1 to avoid rebasing

2018-11-28 20:08 UTC, alexcrichton commented
@bors: r+

2018-11-28 20:48 UTC, pietroalbini commented
@bors retry

Yielding priority to https://github.com/rust-lang/rust/pull/56313, which fixes a bad nightly regression.

2018-11-29 09:36 UTC, merged

2018-11-29 21:37 UTC, mark-i-m commented
@Centril Should this have had the `relnotes` tag?

2018-11-29 22:33 UTC, Centril commented
@mark-i-m oh weird; I thought I added the `relnotes` tag... :P