Initial addition of the Embedded Rust Book
rust-lang/rust pull request #56291
Opened 2018-11-27 18:35 UTC by jamesmunns

This PR adds the Embedded Rust Book to the bookshelf as a submodule, and adds text for the bookshelf page. I have added a new section after "Master Rust" called "Specialize Rust", with the plan that future domain WG books can also reside here. This now extends the titles down to H3, where formerly only H1 and H2 were used.

The added submodule tracks the master branch of the Embedded WG repo.

If there are additional steps necessary to make this work in CI (perhaps adding this to `src/ci/docker/x86_64-gnu-tools/checktools.sh:32` or so?), please let me know.

CC @steveklabnik @japaric 

Also CC issue https://github.com/rust-embedded/wg/issues/257

2018-11-27 18:35 UTC, rust-highfive commented
r? @GuillaumeGomez

(rust_highfive has picked a reviewer for you, use r? to override)

2018-11-27 18:35 UTC, rust-highfive commented
:warning: **Warning** :warning:

* These commits modify **submodules**.

2018-11-27 18:48 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/460401438) ([raw log](https://api.travis-ci.org/v3/job/460401438/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:159d8f90:start=1543343823544017395,finish=1543343825315236869,duration=1771219474
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-5.0
---
[00:00:00] Cleared directory 'src/tools/rls'
[00:00:00] Cleared directory 'src/tools/rust-installer'
[00:00:00] Cleared directory 'src/tools/rustfmt'
[00:00:00] Submodule 'src/dlmalloc' (https://github.com/alexcrichton/dlmalloc-rs.git) registered for path 'src/dlmalloc'
[00:00:00] Submodule 'src/doc/embedded-book' (https://github.com/rust-embedded/book.git) registered for path 'src/doc/embedded-book'
[00:00:00] Submodule 'src/doc/reference' (https://github.com/rust-lang-nursery/reference.git) registered for path 'src/doc/reference'
[00:00:00] Submodule 'src/libbacktrace' (https://github.com/rust-lang-nursery/libbacktrace.git) registered for path 'src/libbacktrace'
[00:00:00] Submodule 'src/libcompiler_builtins' (https://github.com/rust-lang-nursery/compiler-builtins.git) registered for path 'src/libcompiler_builtins'
[00:00:00] Submodule 'src/liblibc' (https://github.com/rust-lang/libc.git) registered for path 'src/liblibc'
---

[00:02:57] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:02:57] tidy error: /checkout/src/doc/embedded-book/ci/install.sh:4: line longer than 100 chars
[00:02:59] some tidy checks failed
[00:02:59] 
[00:02:59] 
[00:02:59] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:02:59] 
[00:02:59] 
[00:02:59] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:02:59] Build completed unsuccessfully in 0:00:55
[00:02:59] Build completed unsuccessfully in 0:00:55
[00:02:59] Makefile:79: recipe for target 'tidy' failed
[00:02:59] make: *** [tidy] Error 1
The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:011c118c
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
Tue Nov 27 18:40:13 UTC 2018
---
travis_time:end:122f4312:start=1543344013496758017,finish=1543344013502017681,duration=5259664
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:00ee2938
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:01b3f5d0
travis_time:start:01b3f5d0
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:0a578208
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-11-27 18:55 UTC, jamesmunns commented
One of our CI scripts was exactly one line too long. Moving to a WIP branch to resolve any issues. Please do not merge until I have moved the submodule back to tracking "master".

2018-11-27 19:46 UTC, steveklabnik commented
This looks great!

> If there are additional steps necessary to make this work in CI (perhaps adding this to src/ci/docker/x86_64-gnu-tools/checktools.sh:32 or so?), please let me know.

Yes, you'll need to modify rustbuild as well. It *should* be as easy as adding a line in here https://github.com/rust-lang/rust/blob/master/src/bootstrap/doc.rs#L70-L76

2018-11-27 20:31 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/460408393) ([raw log](https://api.travis-ci.org/v3/job/460408393/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:1480349b:start=1543344821282012911,finish=1543344822353429122,duration=1071416211
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-5.0
---
[00:00:00] Cleared directory 'src/tools/rls'
[00:00:00] Cleared directory 'src/tools/rust-installer'
[00:00:00] Cleared directory 'src/tools/rustfmt'
[00:00:00] Submodule 'src/dlmalloc' (https://github.com/alexcrichton/dlmalloc-rs.git) registered for path 'src/dlmalloc'
[00:00:00] Submodule 'src/doc/embedded-book' (https://github.com/rust-embedded/book.git) registered for path 'src/doc/embedded-book'
[00:00:00] Submodule 'src/doc/reference' (https://github.com/rust-lang-nursery/reference.git) registered for path 'src/doc/reference'
[00:00:00] Submodule 'src/libbacktrace' (https://github.com/rust-lang-nursery/libbacktrace.git) registered for path 'src/libbacktrace'
[00:00:00] Submodule 'src/libcompiler_builtins' (https://github.com/rust-lang-nursery/compiler-builtins.git) registered for path 'src/libcompiler_builtins'
[00:00:00] Submodule 'src/liblibc' (https://github.com/rust-lang/libc.git) registered for path 'src/liblibc'
---
[00:50:01] .................................................................................................... 100/5064
[00:50:04] .................................................................................................... 200/5064
[00:50:07] .............................ii............................................ii...................ii.. 300/5064
[00:50:09] ..............................................................................................iii... 400/5064
[00:50:12] .....iiiiiiii.iii............................iii...........................................i........ 500/5064
[00:50:19] .................................................................................................... 700/5064
[00:50:24] ................................................................................................i... 800/5064
[00:50:28] ........i........................................................................................... 900/5064
[00:50:31] ...............iiiii..................ii.iiii....................................................... 1000/5064
---
[00:51:10] .................................................................................................... 2300/5064
[00:51:14] .................................................................................................... 2400/5064
[00:51:18] .................................................................................................... 2500/5064
[00:51:21] .................................................................................................... 2600/5064
[00:51:25] .......iiiiiiiii.................................................................................... 2700/5064
[00:51:31] .................................................................................................... 2900/5064
[00:51:34] .................................................................................................... 3000/5064
[00:51:38] ......................................................................i............................. 3100/5064
[00:51:41] .................................................................................................... 3200/5064
---
travis_time:start:test_codegen
Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:05:22] 
[01:05:22] running 117 tests
[01:05:25] i..ii...iii..iiii.....i...i.........i..iii...........i.....i.....ii...i..i.ii..............i...ii..i 100/117
[01:05:25] i.i.....iiii.....
[01:05:25] 
[01:05:25]  finished in 3.424
[01:05:25] travis_fold:end:test_codegen

---
travis_time:start:test_debuginfo
Check compiletest suite=debuginfo mode=debuginfo-both (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:05:39] 
[01:05:39] running 118 tests
[01:06:03] .iiiii...i.....i..i...i..i.i..i.i..i.....i..i....i..........iiii.........i.i....i...i.......ii.i.i.i 100/118
[01:06:07] ......iii.i.....ii
[01:06:07] 
[01:06:07]  finished in 27.857
[01:06:07] travis_fold:end:test_debuginfo

---
[01:34:15] travis_fold:end:stage0-linkchecker

[01:34:15] travis_time:end:stage0-linkchecker:start=1543350484457610554,finish=1543350486851739619,duration=2394129065

[01:34:15] index.html:103: broken link - embedded-book/index.html
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            7.4G     0  7.4G   0% /run/shm
none            100M     0  100M   0% /run/user
none            100M     0  100M   0% /run/user
none            768M     0  768M   0% /var/ramfs
60 ./obj/build/bootstrap/debug/incremental/bootstrap-1plb86h2refwc
134656 ./obj/build/bootstrap/debug/incremental/bootstrap-1plb86h2refwc/s-f72ivlhz8s-d8n60a-18zp7vy2v2s65
129168 ./.git/modules/src
123696 ./obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps
115736 ./obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/release
115352 ./src/llvm/test/CodeGen
---
36560 ./.git/modules/src/libcompiler_builtins/modules
36044 ./.git/modules/src/libcompiler_builtins/modules/compiler-rt
35640 ./src/tools/clang/lib
35580 ./.git/modules/src/libcompiler_builtins/modules/compiler-rt/objects
35572 ./.git/modules/src/libcompiler_builtins/modules/compileores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-11-28 14:29 UTC, steveklabnik commented
I thought that mdbook always put the first page of the book as index.html; maybe I'm wrong...

2018-11-28 14:32 UTC, jamesmunns commented
Hmm, you seem to be right @steveklabnik:

```
➜  book git:(master) rm -rf ./book
➜  book git:(master) mdbook build
2018-11-28 15:30:59 [INFO] (mdbook::book): Book building has started
2018-11-28 15:30:59 [INFO] (mdbook::book): Running the html backend
➜  book git:(master) ls -hal ./book/index.html
-rw-r--r-- 1 james james 19K Nov 28 15:30 ./book/index.html
```

I guess this means I have some investigating to do, support would be appreciated, otherwise I'll look once I have a chance.

2018-11-28 14:37 UTC, steveklabnik commented
[01:35:28] index.html:103: broken link - embedded-book/index.html

This means that `index.html` is linking to `embedded-book/index.html`. are you sure that this doesn't mean that *your* index isn't trying to link to a page deeper than itself?

2018-11-28 15:04 UTC, steveklabnik commented
I cannot get this to build due to a really strange error

```
running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MT"
"/O2" "/Zl" "/D__func__=__FUNCTION__" "/FoC:\\Users\\steve\\src\\rust\\build\\x86_64-pc-windows-msvc\\stage0-std\\x86_64-pc-windows-msvc\\release\\bui
ld\\compiler_builtins-5994e1b3add468a9\\out\\../../libcompiler_builtins\\compiler-rt/lib/builtins\\absvdi2.o" "/c" "../../libcompiler_builtins\\compil
er-rt/lib/builtins\\absvdi2.c"
absvdi2.c
c1: fatal error C1083: Cannot open source file: '../../libcompiler_builtins\compiler-rt/lib/builtins\absvdi2.c': No such file or directory
exit code: 2
```

2018-11-30 18:07 UTC, steveklabnik requested changes
Sooooooooooooo @jamesmunns , I forgot a crucial step:

```diff
diff --git a/src/bootstrap/builder.rs b/src/bootstrap/builder.rs
index 079fdee7e8..97d3ecba04 100644
--- a/src/bootstrap/builder.rs
+++ b/src/bootstrap/builder.rs
@@ -442,7 +442,8 @@ impl<'a> Builder<'a> {
                 doc::RustdocBook,
                 doc::RustByExample,
                 doc::RustcBook,
-                doc::CargoBook
+                doc::CargoBook,
+                doc::EmbeddedBook
             ),
             Kind::Dist => describe!(
                 dist::Docs,
```

the changes you have *define* the build, but don't actually do the building.

after that, we get this report:

```text
embedded-book\intro\install\linux.html:237: broken link - embedded-book\verify.md
embedded-book\intro\install\macos.html:147: broken link - embedded-book\verify.md
embedded-book\intro\install\verify.html:170: broken link - hardware.md
embedded-book\intro\install\verify.html:177: broken link - hardware.md
embedded-book\intro\install\verify.html:180: broken link - embedded-book\linux.md
embedded-book\intro\install\windows.html:161: broken link - embedded-book\verify.md
embedded-book\intro\install.html:160: broken link - embedded-book\install\linux.md
embedded-book\intro\install.html:161: broken link - embedded-book\install\windows.md
embedded-book\intro\install.html:162: broken link - embedded-book\install\macos.md
embedded-book\print.html:374: broken link - embedded-book\install\linux.md
embedded-book\print.html:375: broken link - embedded-book\install\windows.md
embedded-book\print.html:376: broken link - embedded-book\install\macos.md
embedded-book\print.html:479: broken link - embedded-book\verify.md
embedded-book\print.html:491: broken link - embedded-book\verify.md
embedded-book\print.html:517: broken link - embedded-book\verify.md
embedded-book\print.html:552: broken link - hardware.md
embedded-book\print.html:559: broken link - hardware.md
embedded-book\print.html:562: broken link - embedded-book\linux.md
embedded-book\print.html:628: broken link - embedded-book\hardware.md
embedded-book\print.html:1107: broken link - embedded-book\qemu.md
embedded-book\print.html:1151: broken link - intro\install\verify.md
embedded-book\print.html:1173: broken link - intro\install\verify.md
embedded-book\print.html:1329: broken link - portability\index.md
embedded-book\print.html:1352: broken link - peripherals\index.md
embedded-book\start\hardware.html:177: broken link - embedded-book\qemu.md
embedded-book\start\hardware.html:221: broken link - intro\install\verify.md
embedded-book\start\hardware.html:243: broken link - intro\install\verify.md
embedded-book\start\index.html:146: broken link - embedded-book\hardware.md
embedded-book\start\registers.html:142: broken link - portability\index.md
embedded-book\start\registers.html:165: broken link - peripherals\index.md
```

all of the `print` ones are duplicates of the regular pages, so this list is only half as long.

make sense?

2018-11-30 18:11 UTC, jamesmunns commented
I'll take a look tomorrow, I've got some time on the train. I'll see what I can get together :)

2018-12-10 10:03 UTC, Dylan-DPC commented
ping from triage @jamesmunns you need to update this with the changes requested.

2018-12-10 10:11 UTC, jamesmunns commented
Thanks @dylan-dpc, I still intend to finish this as soon as I can.

2018-12-10 20:18 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/466139547) ([raw log](https://api.travis-ci.org/v3/job/466139547/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:03ce1320:start=1544468232109732892,finish=1544468233350606338,duration=1240873446
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-5.0
---
[00:00:00] Attempting with retry: sh -c rm -f download-src-tools-lld.tar.gz &&         curl -sSL -o download-src-tools-lld.tar.gz https://github.com/rust-lang/lld/archive/1928c5eeb613a4c6d232fc47ae91914bbfd92a79.tar.gz
[00:00:00] rm 'src/tools/lldb'
[00:00:00] Attempting with retry: sh -c rm -f download-src-tools-lldb.tar.gz &&         curl -sSL -o download-src-tools-lldb.tar.gz https://github.com/rust-lang-nursery/lldb/archive/8ad0817ce45b0eef9d374691b23f2bd69c164254.tar.gz
[00:00:00] rm 'src/tools/clang'
[00:00:00] Attempting with retry: sh -c git submodule deinit -f  src/tools/rust-installer src/liblibc src/doc/nomicon src/tools/cargo src/doc/reference src/tools/rls src/libcompiler_builtins src/tools/clippy src/tools/rustfmt src/tools/miri src/dlmalloc src/stdsimd src/libbacktrace src/doc/rustc-guide src/doc/edition-guide src/rust-sgx src/doc/embedded-book &&     git submodule sync &&     git submodule update -j 16 --init --recursive  src/tools/rust-installer src/liblibc src/doc/nomicon src/tools/cargo src/doc/reference src/tools/rls src/libcompiler_builtins src/tools/clippy src/tools/rustfmt src/tools/miri src/dlmalloc src/stdsimd src/libbacktrace src/doc/rustc-guide src/doc/edition-guide src/rust-sgx src/doc/embedded-book
[00:00:00] Cleared directory 'src/dlmalloc'
[00:00:00] Cleared directory 'src/doc/edition-guide'
[00:00:00] Cleared directory 'src/doc/embedded-book'
[00:00:00] Cleared directory 'src/doc/nomicon'
---
[00:00:00] Cleared directory 'src/tools/rust-installer'
[00:00:00] Cleared directory 'src/tools/rustfmt'
[00:00:00] Submodule 'src/dlmalloc' (https://github.com/alexcrichton/dlmalloc-rs.git) registered for path 'src/dlmalloc'
[00:00:00] Submodule 'src/doc/edition-guide' (https://github.com/rust-lang-nursery/edition-guide) registered for path 'src/doc/edition-guide'
[00:00:00] Submodule 'src/doc/embedded-book' (https://github.com/rust-embedded/book.git) registered for path 'src/doc/embedded-book'
[00:00:00] Submodule 'src/doc/reference' (https://github.com/rust-lang-nursery/reference.git) registered for path 'src/doc/reference'
[00:00:00] Submodule 'src/doc/rustc-guide' (https://github.com/rust-lang/rustc-guide.git) registered for path 'src/doc/rustc-guide'
[00:00:00] Submodule 'src/libbacktrace' (https://github.com/rust-lang-nursery/libbacktrace.git) registered for path 'src/libbacktrace'
[00:00:00] Submodule 'src/libcompiler_builtins' (https://github.com/rust-lang-nursery/compiler-builtins.git) registered for path 'src/libcompiler_builtins'
---
travis_time:start:test_codegen
Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[00:55:35] 
[00:55:35] running 120 tests
[00:55:38] i..ii...iii..iiii.....i...i..........i..iii.............i.....i.....ii...i..i.ii..............i...ii 100/120
[00:55:38] ..ii.i.....iiii.....
[00:55:38] 
[00:55:38]  finished in 3.450
[00:55:38] travis_fold:end:test_codegen

---
travis_time:start:test_debuginfo
Check compiletest suite=debuginfo mode=debuginfo-both (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[00:55:53] 
[00:55:53] running 118 tests
[00:56:16] .iiiii...i.....i..i...i..i.i..i.i..i.....i..i....i..........iiii.........i.i....i...i.......ii.i.i.i 100/118
[00:56:20] ......iii.i.....ii
[00:56:20] 
[00:56:20]  finished in 27.178
[00:56:20] travis_fold:end:test_debuginfo

---
[01:21:06] travis_fold:end:stage0-linkchecker

[01:21:06] travis_time:end:stage0-linkchecker:start=1544473105736719694,finish=1544473108036872422,duration=2300152728

[01:21:06] index.html:106: broken link - embedded-book/index.html
[01:21:12] thread 'main' panicked at 'found some broken links', src/tools/linkchecker/main.rs:49:9
[01:21:12] 
[01:21:12] 
[01:21:12] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/linkchecker" "/checkout/obj/build/x86_64-unknown-linux-gnu/doc"
[01:21:12] expected success, got: exit code: 101
[01:21:12] expected success, got: exit code: 101
[01:21:12] 
[01:21:12] 
[01:21:12] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:21:12] Build completed unsuccessfully in 0:36:08
[01:21:12] make: *** [check] Error 1
[01:21:12] Makefile:58: recipe for target 'check' failed
The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:0d52d498
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
Mon Dec 10 20:18:34 UTC 2018
---
travis_time:end:25ccfe1e:start=1544473116457021205,finish=1544473116547228790,duration=90207585
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:087ce538
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:047a9a46
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-12-10 20:49 UTC, jamesmunns commented
@steveklabnik I think I know what the issue is, the main rust repo uses an older version of `mdbook` than the embedded wg (`0.1.7` vs `0.2.2`). We rely on using links to relative `md` files within the pre-rendered markdown, and newer versions of `mdbook` automatically render this to `.html` links.

In [this change](https://github.com/rust-lang/rust/pull/56291/commits/b115a5535c8b7a270a4ee2e0ce93810874ddf773#diff-612b38fc566f4724cd224c7b21349ab5R11), I update the dependency to `0.2.2`. After updating, `x.py dist` still seems to complete successfully.

Let's see how the CI goes.

2018-12-10 21:12 UTC, steveklabnik commented
Updating to 0.2 is going to take a massive effort across all books. I plan on trying to tackle it soon, but it’s tough.

> On Dec 10, 2018, at 3:49 PM, James Munns <notifications@github.com> wrote:
> 
> @steveklabnik I think I know what the issue is, the main rust repo uses an older version of mdbook than the embedded wg (0.1.7 vs 0.2.2). We rely on using links to relative md files within the pre-rendered markdown, and newer versions of mdbook automatically render this to .html links.
> 
> In this change, I update the dependency to 0.2.2. After updating, x.py dist still seems to complete successfully.
> 
> Let's see how the CI goes.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-12-10 22:07 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/466189658) ([raw log](https://api.travis-ci.org/v3/job/466189658/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:00e77a37:start=1544474800582637503,finish=1544474802829172747,duration=2246535244
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-5.0
---
[00:00:00] rm 'src/tools/lldb'
[00:00:00] Attempting with retry: sh -c rm -f download-src-tools-lldb.tar.gz &&         curl -sSL -o download-src-tools-lldb.tar.gz https://github.com/rust-lang-nursery/lldb/archive/8ad0817ce45b0eef9d374691b23f2bd69c164254.tar.gz
[00:00:00] rm 'src/tools/clang'
[00:00:00] Attempting with retry: sh -c rm -f download-src-tools-clang.tar.gz &&         curl -sSL -o download-src-tools-clang.tar.gz https://github.com/rust-lang-nursery/clang/archive/032312dd0140a7074c9b89d305fe44eb0e44e407.tar.gz
[00:00:00] Attempting with retry: sh -c git submodule deinit -f  src/tools/rust-installer src/liblibc src/doc/nomicon src/tools/cargo src/doc/reference src/tools/rls src/libcompiler_builtins src/tools/clippy src/tools/rustfmt src/tools/miri src/dlmalloc src/stdsimd src/libbacktrace src/doc/rustc-guide src/doc/edition-guide src/rust-sgx src/doc/embedded-book &&     git submodule sync &&     git submodule update -j 16 --init --recursive  src/tools/rust-installer src/liblibc src/doc/nomicon src/tools/cargo src/doc/reference src/tools/rls src/libcompiler_builtins src/tools/clippy src/tools/rustfmt src/tools/miri src/dlmalloc src/stdsimd src/libbacktrace src/doc/rustc-guide src/doc/edition-guide src/rust-sgx src/doc/embedded-book
[00:00:00] Cleared directory 'src/doc/edition-guide'
[00:00:00] Cleared directory 'src/doc/embedded-book'
[00:00:00] Cleared directory 'src/doc/nomicon'
[00:00:00] Cleared directory 'src/doc/reference'
---
[00:00:00] Cleared directory 'src/tools/rust-installer'
[00:00:00] Cleared directory 'src/tools/rustfmt'
[00:00:00] Submodule 'src/dlmalloc' (https://github.com/alexcrichton/dlmalloc-rs.git) registered for path 'src/dlmalloc'
[00:00:00] Submodule 'src/doc/edition-guide' (https://github.com/rust-lang-nursery/edition-guide) registered for path 'src/doc/edition-guide'
[00:00:00] Submodule 'src/doc/embedded-book' (https://github.com/rust-embedded/book.git) registered for path 'src/doc/embedded-book'
[00:00:00] Submodule 'src/doc/reference' (https://github.com/rust-lang-nursery/reference.git) registered for path 'src/doc/reference'
[00:00:00] Submodule 'src/doc/rustc-guide' (https://github.com/rust-lang/rustc-guide.git) registered for path 'src/doc/rustc-guide'
[00:00:00] Submodule 'src/libbacktrace' (https://github.com/rust-lang-nursery/libbacktrace.git) registered for path 'src/libbacktrace'
[00:00:00] Submodule 'src/libcompiler_builtins' (https://github.com/rust-lang-nursery/compiler-builtins.git) registered for path 'src/libcompiler_builtins'
---
travis_time:start:test_codegen
Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[00:54:07] 
[00:54:07] running 120 tests
[00:54:10] i..ii...iii..iiii.....i...i..........i..iii.............i.....i.....ii...i..i.ii..............i...ii 100/120
[00:54:10] ..ii.i.....iiii.....
[00:54:10] 
[00:54:10]  finished in 3.231
[00:54:10] travis_fold:end:test_codegen

---
travis_time:start:test_debuginfo
Check compiletest suite=debuginfo mode=debuginfo-both (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[00:54:24] 
[00:54:24] running 118 tests
[00:54:47] .iiiii...i.....i..i...i..i.i..i.i..i.....i..i....i..........iiii.........i.i....i...i.......ii.i.i.i 100/118
[00:54:51] ......iii.i.....ii
[00:54:51] 
[00:54:51]  finished in 26.904
[00:54:51] travis_fold:end:test_debuginfo

---
[01:20:02] travis_fold:end:stage0-linkchecker

[01:20:02] travis_time:end:stage0-linkchecker:start=1544479613327137280,finish=1544479615444019918,duration=2116882638

[01:20:02] cargo/appendix/glossary.html:150: broken link - cargo/appendix/reference/manifest.html
[01:20:02] cargo/appendix/glossary.html:154: broken link - cargo/appendix/reference/manifest.html
[01:20:02] cargo/appendix/glossary.html:167: broken link - cargo/appendix/guide/cargo-toml-vs-cargo-lock.html
[01:20:02] cargo/appendix/glossary.html:169: broken link - cargo/appendix/reference/manifest.html
[01:20:02] cargo/appendix/glossary.html:171: broken link - cargo/appendix/reference/manifest.html
[01:20:02] cargo/appendix/glossary.html:182: broken link - cargo/appendix/reference/pkgid-spec.html
[01:20:02] cargo/appendix/glossary.html:198: broken link - cargo/appendix/reference/source-replacement.html
[01:20:02] cargo/appendix/glossary.html:200: broken link - cargo/appendix/reference/source-replacement.html
[01:20:02] cargo/appendix/glossary.html:202: broken link - cargo/appendix/reference/specifying-dependencies.html
[01:20:02] cargo/appendix/glossary.html:202: broken link - cargo/appendix/reference/specifying-dependencies.html
[01:20:02] cargo/appendix/glossary.html:203: broken link - cargo/appendix/reference/specifying-dependencies.html
[01:20:02] cargo/appendix/glossary.html:204: broken link - cargo/appendix/reference/source-replacement.html
[01:20:02] cargo/appendix/glossary.html:206: broken link - cargo/appendix/reference/source-replacement.html
[01:20:02] cargo/appendix/glossary.html:214: broken link - cargo/appendix/reference/manifest.html
[01:20:02] cargo/appendix/glossary.html:215: broken link - cargo/appendix/reference/manifest.html
[01:20:02] cargo/appendix/glossary.html:224: broken link - cargo/appendix/reference/config.html
[01:20:02] cargo/appendix/glossary.html:229: broken link - cargo/appendix/reference/environment-variables.html
[01:20:02] cargo/appendix/glossary.html:230: broken link - cargo/appendix/reference/config.html
[01:20:02] cargo/appendix/glossary.html:240: broken link - cargo/appendix/reference/manifest.html
[01:20:02] cargo/appendix/glossary.html:243: broken link - cargo/appendix/reference/manifest.html
[01:20:02] cargo/appendix/glossary.html:248: broken link - cargo/appendix/reference/manifest.html
[01:20:02] cargo/appendix/glossary.html:251: broken link - cargo/appendix/reference/manifest.html
[01:20:02] cargo/guide/project-layout.html:169: broken link - cargo/guide/reference/manifest.html
[01:20:02] cargo/guide/cargo-toml-vs-cargo-lock.html:151: broken link - cargo/guide/faq.html
[01:20:02] cargo/guide/cargo-toml-vs-cargo-lock.html:218: broken link - cargo/guide/reference/pkgid-spec.html
[01:20:02] cargo/guide/index.html:143: broken link - cargo/guide/guide/why-cargo-exists.html
[01:20:02] cargo/guide/index.html:144: broken link - cargo/guide/guide/creating-a-new-project.html
[01:20:02] cargo/guide/index.html:145: broken link - cargo/guide/guide/working-on-an-existing-project.html
[01:20:02] cargo/guide/index.html:146: broken link - cargo/guide/guide/dependencies.html
[01:20:02] cargo/guide/index.html:147: broken link - cargo/guide/guide/project-layout.html
[01:20:02] cargo/guide/index.html:148: broken link - cargo/guide/guide/cargo-toml-vs-cargo-lock.html
[01:20:02] cargo/guide/index.html:149: broken link - cargo/guide/guide/tests.html
[01:20:02] cargo/guide/index.html:150: broken link - cargo/guide/guide/continuous-integration.html
[01:20:02] cargo/guide/index.html:151: broken link - cargo/guide/guide/build-cache.html
[01:20:02] cargo/guide/dependencies.html:151: broken link - cargo/guide/reference/specifying-dependencies.html
[01:20:02] cargo/getting-started/index.html:142: broken link - cargo/getting-s [...]

2018-12-10 23:59 UTC, jamesmunns commented
Oh. That's unfortunate. Let me ask the folks at the next embedded meeting whether we are okay with breaking convention on how relative links should be formatted.

@steveklabnik how would I run exactly the same test that CI is running for this check? I don't get the same errors when I just run `x.py dist` or `x.py doc`, I think it's missing the linkcheck step?

I might be interested in chipping away at the mdbook 0.2 changes, if they are mostly mechanical.

2018-12-11 02:49 UTC, steveklabnik commented
python x.py test src/tools/linkchecker

It’s mostly about the re-basing of relative URLs, as you mentioned. The book, the reference, the nomicon, RBE... they’ll all need to be updated.

> On Dec 10, 2018, at 6:59 PM, James Munns <notifications@github.com> wrote:
> 
> Oh. That's unfortunate. Let me ask the folks at the next embedded meeting whether we are okay with breaking convention on how relative links should be formatted.
> 
> @steveklabnik how would I run exactly the same test that CI is running for this check? I don't get the same errors when I just run x.py dist or x.py doc, I think it's missing the linkcheck step?
> 
> I might be interested in chipping away at the mdbook 0.2 changes, if they are mostly mechanical.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-12-11 12:10 UTC, jamesmunns commented
Okay, let me take a pass at this, and see how much damage I can do.

https://github.com/rust-embedded/book/issues/55 is relevant, it's where the embedded wg decided on a canonical link format (using mdbook 0.2).

2018-12-11 13:34 UTC, jamesmunns commented
Hey @steveklabnik, I had a bit of an idea. Would you be up for supporting multiple versions of mdbook at the same time? I think this could solve our problem today, and it could make it easier to incrementally port books between versions.

Take a look at [this commit](https://github.com/rust-lang/rust/pull/56291/commits/6c60e3a026540e381fa5ace6edec6a760568b0ff), particularly:

* [Cargo.toml trickery](https://github.com/rust-lang/rust/blob/6c60e3a026540e381fa5ace6edec6a760568b0ff/src/tools/rustbook/Cargo.toml#L13-L23),
* [Handling two render steps](https://github.com/rust-lang/rust/blob/6c60e3a026540e381fa5ace6edec6a760568b0ff/src/tools/rustbook/src/main.rs#L48-L69)
* [Describing the version to be used](https://github.com/rust-lang/rust/blob/6c60e3a026540e381fa5ace6edec6a760568b0ff/src/bootstrap/doc.rs#L72-L80)

There are definitely some cleanups to be made, and the `print` links are still failing for some reason, but I wanted to check with you to see if this is a route you would be willing to take.

2018-12-11 14:15 UTC, jamesmunns commented
Oh, it looks like fixing `print.html` might be difficult, we currently [skip linkchecking print.html](https://github.com/rust-embedded/discovery/pull/142/files) in the embedded book, as mdbook does not render these links as expected.

@steveklabnik is the contents of `print.html` important in this context? If so, fixing this upstream in mdbook might be required.

2018-12-11 14:53 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/466511506) ([raw log](https://api.travis-ci.org/v3/job/466511506/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:0263f7ab:start=1544535081973781003,finish=1544535203572342663,duration=121598561660
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-5.0
---
[00:00:00] Attempting with retry: sh -c rm -f download-src-tools-lld.tar.gz &&         curl -sSL -o download-src-tools-lld.tar.gz https://github.com/rust-lang/lld/archive/1928c5eeb613a4c6d232fc47ae91914bbfd92a79.tar.gz
[00:00:00] rm 'src/tools/lldb'
[00:00:00] Attempting with retry: sh -c rm -f download-src-tools-lldb.tar.gz &&         curl -sSL -o download-src-tools-lldb.tar.gz https://github.com/rust-lang-nursery/lldb/archive/8ad0817ce45b0eef9d374691b23f2bd69c164254.tar.gz
[00:00:00] rm 'src/tools/clang'
[00:00:00] Attempting with retry: sh -c git submodule deinit -f  src/tools/rust-installer src/liblibc src/doc/nomicon src/tools/cargo src/doc/reference src/tools/rls src/libcompiler_builtins src/tools/clippy src/tools/rustfmt src/tools/miri src/dlmalloc src/stdsimd src/libbacktrace src/doc/rustc-guide src/doc/edition-guide src/rust-sgx src/doc/embedded-book &&     git submodule sync &&     git submodule update -j 16 --init --recursive  src/tools/rust-installer src/liblibc src/doc/nomicon src/tools/cargo src/doc/reference src/tools/rls src/libcompiler_builtins src/tools/clippy src/tools/rustfmt src/tools/miri src/dlmalloc src/stdsimd src/libbacktrace src/doc/rustc-guide src/doc/edition-guide src/rust-sgx src/doc/embedded-book
[00:00:00] Cleared directory 'src/dlmalloc'
[00:00:00] Cleared directory 'src/doc/edition-guide'
[00:00:00] Cleared directory 'src/doc/embedded-book'
[00:00:00] Cleared directory 'src/doc/nomicon'
---
[00:00:00] Cleared directory 'src/tools/rust-installer'
[00:00:00] Cleared directory 'src/tools/rustfmt'
[00:00:00] Submodule 'src/dlmalloc' (https://github.com/alexcrichton/dlmalloc-rs.git) registered for path 'src/dlmalloc'
[00:00:00] Submodule 'src/doc/edition-guide' (https://github.com/rust-lang-nursery/edition-guide) registered for path 'src/doc/edition-guide'
[00:00:00] Submodule 'src/doc/embedded-book' (https://github.com/rust-embedded/book.git) registered for path 'src/doc/embedded-book'
[00:00:00] Submodule 'src/doc/reference' (https://github.com/rust-lang-nursery/reference.git) registered for path 'src/doc/reference'
[00:00:00] Submodule 'src/doc/rustc-guide' (https://github.com/rust-lang/rustc-guide.git) registered for path 'src/doc/rustc-guide'
[00:00:00] Submodule 'src/libbacktrace' (https://github.com/rust-lang-nursery/libbacktrace.git) registered for path 'src/libbacktrace'
[00:00:00] Submodule 'src/libcompiler_builtins' (https://github.com/rust-lang-nursery/compiler-builtins.git) registered for path 'src/libcompiler_builtins'
---
travis_time:start:test_codegen
Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[00:54:35] 
[00:54:35] running 120 tests
[00:54:38] i..ii...iii..iiii.....i...i..........i...iii............i.....i.....ii...i..i.ii..............i...ii 100/120
[00:54:38] ..ii.i.....iiii.....
[00:54:38] 
[00:54:38]  finished in 3.345
[00:54:38] travis_fold:end:test_codegen

---
travis_time:start:test_debuginfo
Check compiletest suite=debuginfo mode=debuginfo-both (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[00:54:52] 
[00:54:52] running 118 tests
[00:55:14] .iiiii...i.....i..i...i..i.i..i.i..i.....i..i....i..........iiii.........i.i....i...i.......ii.i.i.i 100/118
[00:55:18] ......iii.i.....ii
[00:55:18] 
[00:55:18]  finished in 26.444
[00:55:18] travis_fold:end:test_debuginfo

---
[01:19:26] travis_fold:end:stage0-linkchecker

[01:19:26] travis_time:end:stage0-linkchecker:start=1544539976208694202,finish=1544539978550606666,duration=2341912464

[01:19:26] embedded-book/print.html:377: broken link - embedded-book/install/linux.html
[01:19:26] embedded-book/print.html:378: broken link - embedded-book/install/windows.html
[01:19:26] embedded-book/print.html:379: broken link - embedded-book/install/macos.html
[01:19:26] embedded-book/print.html:482: broken link - embedded-book/verify.html
[01:19:26] embedded-book/print.html:494: broken link - embedded-book/verify.html
[01:19:26] embedded-book/print.html:520: broken link - embedded-book/verify.html
[01:19:26] embedded-book/print.html:555: broken link - hardware.html
[01:19:26] embedded-book/print.html:562: broken link - hardware.html
[01:19:26] embedded-book/print.html:565: broken link - embedded-book/linux.html
[01:19:26] embedded-book/print.html:631: broken link - embedded-book/hardware.html
[01:19:26] embedded-book/print.html:1110: broken link - embedded-book/qemu.html
[01:19:26] embedded-book/print.html:1154: broken link - intro/install/verify.html
[01:19:26] embedded-book/print.html:1176: broken link - intro/install/verify.html
[01:19:26] embedded-book/print.html:1332: broken link - portability/index.html
[01:19:26] embedded-book/print.html:1355: broken link - peripherals/index.html
[01:19:31] thread 'main' panicked at 'found some broken links', src/tools/linkchecker/main.rs:49:9
[01:19:31] 
[01:19:31] 
[01:19:31] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/linkchecker" "/checkout/obj/build/x86_64-unknown-linux-gnu/doc"
[01:19:31] expected success, got: exit code: 101
[01:19:31] expected success, got: exit code: 101
[01:19:31] 
[01:19:31] 
[01:19:31] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:19:31] Build completed unsuccessfully in 0:35:09
[01:19:31] Makefile:58: recipe for target 'check' failed
[01:19:31] make: *** [check] Error 1
3128556 ./obj
3113272 ./obj/build
2458616 ./obj/build/x86_64-unknown-linux-gnu
1168224 ./src
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-12-11 15:30 UTC, steveklabnik commented
> Would you be up for supporting multiple versions of mdbook at the same time? I think this could solve our problem today, and it could make it easier to incrementally port books between versions.

I *think* this might be really helpful. I am not sure if @rust-lang/infra is happy with it though. If they are, I am! This would be super useful to make the ports incremental, and then we can revert to a single version once it's done.

> @steveklabnik is the contents of print.html important in this context? If so, fixing this upstream in mdbook might be required.

Yes; people print these to PDF and expect links to work and stuff. We should fix whatever the `print.html` issue is, for sure.

2019-01-10 16:16 UTC, steveklabnik commented
ping @jamesmunns ! Is there anything I can do to help you get across the finish line here?

2019-01-10 19:13 UTC, jamesmunns commented
Comments in https://github.com/rust-lang-nursery/edition-guide/pull/134#issuecomment-453204579 !

2019-01-10 19:34 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/169608171) ([raw log](https://api.travis-ci.com/v3/job/169608171/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_fold:start:worker_info
Worker information
hostname: ea13048e-f0a1-49df-881f-ba4229c4a60b@1.production-1-worker-com-gce-dxrb
version: v6.2.0 https://github.com/travis-ci/worker/tree/5e5476e01646095f48eec13196fdb3faf8f5cbf7
startup: 6.805925044s
travis_fold:end:worker_info
travis_fold:start:system_info
Build system information
---
travis_time:end:02041380:start=1547148621984321746,finish=1547148693875201035,duration=71890879289
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-6.0
---
[00:00:00] Cleared directory 'src/tools/rls'
[00:00:00] Cleared directory 'src/tools/rust-installer'
[00:00:00] Cleared directory 'src/tools/rustfmt'
[00:00:00] Submodule 'src/doc/edition-guide' (https://github.com/rust-lang-nursery/edition-guide) registered for path 'src/doc/edition-guide'
[00:00:00] Submodule 'src/doc/embedded-book' (https://github.com/rust-embedded/book.git) registered for path 'src/doc/embedded-book'
[00:00:00] Submodule 'src/doc/reference' (https://github.com/rust-lang-nursery/reference.git) registered for path 'src/doc/reference'
[00:00:00] Submodule 'src/doc/rustc-guide' (https://github.com/rust-lang/rustc-guide.git) registered for path 'src/doc/rustc-guide'
[00:00:00] Submodule 'src/stdsimd' (https://github.com/rust-lang-nursery/stdsimd.git) registered for path 'src/stdsimd'
[00:00:00] Submodule 'src/tools/cargo' (https://github.com/rust-lang/cargo.git) registered for path 'src/tools/cargo'
---
[00:01:26] downloading https://static.rust-lang.org/dist/2019-01-04/cargo-beta-x86_64-unknown-linux-gnu.tar.gz
[00:01:26] 
######################################################################## 100.0%
[00:01:27] extracting /checkout/obj/build/cache/2019-01-04/cargo-beta-x86_64-unknown-linux-gnu.tar.gz
[00:01:27] warning: /checkout/src/tools/rustbook/Cargo.toml: the cargo feature `rename-dependency` is now stable and is no longer necessary to be listed in the manifest
[00:01:27]     Updating crates.io index
[00:01:39] error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
[00:01:39] Build completed unsuccessfully in 0:00:25
[00:01:39] Makefile:71: recipe for target 'prepare' failed
[00:01:39] make: *** [prepare] Error 1
[00:01:40] Command failed. Attempt 2/5:
[00:01:40] Command failed. Attempt 2/5:
[00:01:40] warning: /checkout/src/tools/rustbook/Cargo.toml: the cargo feature `rename-dependency` is now stable and is no longer necessary to be listed in the manifest
[00:01:40] error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
[00:01:40] Build completed unsuccessfully in 0:00:00
[00:01:40] make: *** [prepare] Error 1
[00:01:40] Makefile:71: recipe for target 'prepare' failed
[00:01:42] Command failed. Attempt 3/5:
[00:01:42] Command failed. Attempt 3/5:
[00:01:42] warning: /checkout/src/tools/rustbook/Cargo.toml: the cargo feature `rename-dependency` is now stable and is no longer necessary to be listed in the manifest
[00:01:42] error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
[00:01:42] Build completed unsuccessfully in 0:00:00
[00:01:42] make: *** [prepare] Error 1
[00:01:42] Makefile:71: recipe for target 'prepare' failed
[00:01:45] Command failed. Attempt 4/5:
[00:01:45] Command failed. Attempt 4/5:
[00:01:45] warning: /checkout/src/tools/rustbook/Cargo.toml: the cargo feature `rename-dependency` is now stable and is no longer necessary to be listed in the manifest
[00:01:46] error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
[00:01:46] Build completed unsuccessfully in 0:00:00
[00:01:46] make: *** [prepare] Error 1
[00:01:46] Makefile:71: recipe for target 'prepare' failed
[00:01:50] Command failed. Attempt 5/5:
[00:01:50] Command failed. Attempt 5/5:
[00:01:50] warning: /checkout/src/tools/rustbook/Cargo.toml: the cargo feature `rename-dependency` is now stable and is no longer necessary to be listed in the manifest
[00:01:50] error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
[00:01:50] Build completed unsuccessfully in 0:00:00
[00:01:50] make: *** [prepare] Error 1
[00:01:50] Makefile:71: recipe for target 'prepare' failed
[00:01:50] The command has failed after 5 attempts.
---
travis_time:end:0c265dd6:start=1547148816395155806,finish=1547148816399842723,duration=4686917
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0b748870
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:16f671fc
travis_time:start:16f671fc
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:20a23170
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-01-19 03:58 UTC, jamesmunns commented
Hard/manual rebased on https://github.com/rust-lang/rust/pull/57495. Also still blocked by https://github.com/rust-embedded/book/pull/94.

2019-01-22 13:00 UTC, jamesmunns commented
@steveklabnik this is okay to `r+` after #57495 lands IMO! I don't think a rebase should be necessary, but happy to do if preferred.

2019-01-22 14:04 UTC, steveklabnik commented
yes, r=me after that lands :)

2019-02-01 03:46 UTC, jamesmunns commented
Pinging @steveklabnik, have I got a book for you.

2019-02-01 12:13 UTC, jamesmunns commented
@steveklabnik ready for the `r+`!

2019-02-04 10:21 UTC, steveklabnik approved these changes

2019-02-04 10:21 UTC, steveklabnik commented
I've rebased and squashed this; let's make sure travis passes, and then this looks good to go to me. @jamesmunns maybe triple check this?

2019-02-04 10:36 UTC, jamesmunns commented
@steveklabnik it looks like the submodule rolled back in versions, updated with the current master branch. Otherwise LGTM!

2019-02-04 13:07 UTC, steveklabnik commented
@bors: r+

Woo!

2019-02-04 17:14 UTC, steveklabnik commented
@bors: retry

seems spurious and not related?

2019-02-04 17:45 UTC, pietroalbini commented
Yep, it's spurious, we're trying to track it.

2019-02-05 04:32 UTC, merged