Fix const_fn ICE with non-const function pointer
rust-lang/rust pull request #56337
Opened 2018-11-29 08:10 UTC by phansch

r? @oli_obk

Fixes #56164

2018-11-29 08:11 UTC, phansch commented
r? @oli-obk

2018-11-29 08:15 UTC, oli-obk requested changes

2018-11-29 08:15 UTC, oli-obk commented on src/librustc_mir/transform/qualify_consts.rs
> +                                        | "min_align_of"
what happened to the indent here?

2018-11-29 08:15 UTC, oli-obk commented on src/librustc_mir/transform/qualify_consts.rs
> +                    span_bug!(self.span, "this is not allowed in const fn");
I think it would be strictly less ICEy if we just called `not_const` here and early returned

2018-11-30 07:51 UTC, phansch commented
I had to rebase from master which was rather complicated, so I opted to re-do this because that was quicker. I added an additional test for `const fn foo() { (||{})() }` and it's now using `self.not_const()` instead of a custom message.

2018-11-30 08:30 UTC, oli-obk commented
@bors r+

thanks

2018-11-30 08:30 UTC, oli-obk approved these changes

2018-11-30 22:01 UTC, merged