Contexually dependent error message for E0424 when value is assigned to "self"
rust-lang/rust pull request #56572
Opened 2018-12-06 20:25 UTC by kevgrasso

This is an improvement for pull request #54495 referencing issue #54369. If the "self" keyword is assigned a value as though it were a valid identifier, it will now report:
```
let self = "self";
    ^^^^ `self` value is a keyword and may not be bound to variables or shadowed
```
instead of
```
let self = "self";
    ^^^^ `self` value is a keyword only available in methods with `self` parameter
```
If anyone has a better idea for what the error should be I'd be happy to modify it appropriately.

2018-12-07 02:46 UTC, estebank requested changes
Fix indentation of the new code.

It seems like you might have had some rebasing issues. Can you rebase your changes as a single commit against latest master?

After fixing that, r=me.

2018-12-07 02:47 UTC, estebank commented
r? @estebank

2018-12-09 01:10 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-5.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/465483762) ([raw log](https://api.travis-ci.org/v3/job/465483762/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:17d98bb9:start=1544317390948378159,finish=1544317445314993435,duration=54366615276
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-5.0
---

[00:03:09] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:03:09] tidy error: /checkout/src/librustc_resolve/lib.rs:3199: trailing whitespace
[00:03:09] tidy error: /checkout/src/librustc_resolve/lib.rs:3205: trailing whitespace
[00:03:09] tidy error: /checkout/src/librustc_resolve/lib.rs:3206: line longer than 100 chars
[00:03:09] tidy error: /checkout/src/librustc_resolve/lib.rs:3207: line longer than 100 chars
[00:03:09] tidy error: /checkout/src/librustc_resolve/lib.rs:3208: line longer than 100 chars
[00:03:09] tidy error: /checkout/src/librustc_resolve/lib.rs:3209: line longer than 100 chars
[00:03:09] tidy error: /checkout/src/librustc_resolve/lib.rs:3210: trailing whitespace
[00:03:11] some tidy checks failed
[00:03:11] 
[00:03:11] 
[00:03:11] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:03:11] 
[00:03:11] 
[00:03:11] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:03:11] Build completed unsuccessfully in 0:00:53
[00:03:11] Build completed unsuccessfully in 0:00:53
[00:03:11] make: *** [tidy] Error 1
[00:03:11] Makefile:79: recipe for target 'tidy' failed
The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:1035f456
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
Sun Dec  9 01:07:25 UTC 2018
---
travis_time:end:181121f4:start=1544317645780872921,finish=1544317645785414302,duration=4541381
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:1c873459
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:178c3167
travis_time:start:178c3167
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:00257db2
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-12-10 17:59 UTC, estebank commented
Hi @kevgrasso! You still seem to have so clean up your commit history.

2018-12-10 18:43 UTC, kevgrasso commented
r= @estebank

I think I got it done. My teachers didn't know how do this so I had some trouble figuring it out.

2018-12-10 19:09 UTC, estebank commented
I think you still might have to remove three commits (adbf5dc, 51fd050 and 209e625). You can do that by doing `git rebase -I HEAD^^^^` (interactive rebase 4 commits back) and then on the editor that will open [remove those three and only leave yours](https://stackoverflow.com/a/1338758/34813) (it should be the last one). After doing that you _can_ (but don't need to) do `git checkout master && git pull` (get the latest changes from rust in your master branch) `git checkout let_self_err_dev` (get back on your branch) and finally `git rebase master` (replay the changes in your local branch _on top_ of master).

Also, https://git-scm.com/book/en/v2/Git-Branching-Rebasing and https://sethrobertson.github.io/GitFixUm/fixup.html are good resources (even though a bit more convoluted than I'd like).

2018-12-10 19:42 UTC, kevgrasso commented
r= @estebank 
Okay I'm pretty sure this is good now. Thank you for the help.

2018-12-11 03:22 UTC, estebank approved these changes

2018-12-13 11:58 UTC, pietroalbini commented
@bors r-

Please remove the clippy submodule update.

2018-12-13 11:58 UTC, pietroalbini commented
@bors rollup-

2018-12-14 01:20 UTC, kevgrasso commented
Whoops, sorry about that. I dunno how that got in there. I think that's fixed now.

2018-12-14 01:49 UTC, estebank commented
@bors r+

2018-12-14 23:03 UTC, merged