Stabilize `Rc`, `Arc` and `Pin` as method receivers
rust-lang/rust pull request #56805
Opened 2018-12-14 06:05 UTC by mikeyhew

Replaces #55880
Closes  #55786 
r? @nikomatsakis 
cc @withoutboats @cramertj

This lets you write methods using `self: Rc<Self>`, `self: Arc<Self>`, `self: Pin<&mut Self>`, `self: Pin<Box<Self>`, and other combinations involving `Pin` and another stdlib receiver type, without needing the `arbitrary_self_types`. Other user-created receiver types can be used, but they still require the feature flag to use.

This is implemented by introducing a new trait, `Receiver`, which the method receiver's type must implement if the `arbitrary_self_types` feature is not enabled. To keep composed receiver types such as `&Arc<Self>` unstable, the receiver type is also required to implement `Deref<Target=Self>` when the feature flag is not enabled.

This lets you use `self: Rc<Self>` and `self: Arc<Self>` in stable Rust, which was not allowed previously. It was agreed that they would be stabilized in #55786. `self: Pin<&Self>` and other pinned receiver types do not require the `arbitrary_self_types` feature, but they cannot be used on stable because `Pin` still requires the `pin` feature.

2018-12-14 21:34 UTC, nikomatsakis requested changes
Looks good to me. One nit, then r=me.

2018-12-14 21:34 UTC, nikomatsakis commented on src/librustc_typeck/check/wfcheck.rs
> +        let deref_trait_def_id = match fcx.tcx.lang_items().deref_trait() {
It'd be nice to have some comments here, to document what we are requiring and *why* (basically what's in your PR comment).

2018-12-14 21:34 UTC, nikomatsakis commented on src/librustc_typeck/check/wfcheck.rs
> +        let deref_trait_def_id = match fcx.tcx.lang_items().deref_trait() {
This can reference the doc comment on the fn itself I guess.

2018-12-16 09:08 UTC, bluss commented
Since Pin is unstable, does this keep `fn foo(self: Pin<Box<Self>>)` or similar as unstable to use?

2018-12-18 22:51 UTC, mikeyhew commented
@nikomatsakis assuming this passes CI, it should be good to go

2018-12-18 23:33 UTC, cramertj commented
@bors r=nikomatsakis

2018-12-20 06:41 UTC, mikeyhew commented
This is good to go again.

2018-12-20 19:02 UTC, rust-highfive commented
The job `x86_64-gnu-distcheck` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/470651924) ([raw log](https://api.travis-ci.org/v3/job/470651924/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
[00:03:47]    Compiling cargo v0.32.0
[00:03:54] error[E0308]: mismatched types
[00:03:54]  --> /cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.32.0/src/cargo/util/sha256.rs:9:34
[00:03:54]   |
[00:03:54] 9 |         let hasher = Hasher::new(Algorithm::SHA256);
[00:03:54]   |                                  |
[00:03:54]   |                                  |
[00:03:54]   |                                  expected reference, found enum `util::sha256::crypto_hash::Algorithm`
[00:03:54]   |                                  help: consider borrowing here: `&Algorithm::SHA256`
[00:03:54]   |
[00:03:54]   = note: expected type `&util::sha256::crypto_hash::Algorithm`
[00:03:54]              found type `util::sha256::crypto_hash::Algorithm`
[00:03:54] error: aborting due to previous error
[00:03:54] 
[00:03:54] For more information about this error, try `rustc --explain E0308`.
[00:03:54] For more information about this error, try `rustc --explain E0308`.
[00:03:54] error: failed to compile `cargo-vendor v0.1.22`, intermediate artifacts can be found at `/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools`
[00:03:54] Caused by:
[00:03:54]   Could not compile `cargo`.
[00:03:54] 
[00:03:54] To learn more, run the command again with --verbose.
[00:03:54] To learn more, run the command again with --verbose.
[00:03:54] 
[00:03:54] 
[00:03:54] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "install" "-j" "4" "--locked" "--color" "always" "--force" "--debug" "--vers" "0.1.22" "cargo-vendor"
[00:03:54] 
[00:03:54] 
[00:03:54] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test distcheck
[00:03:54] Build completed unsuccessfully in 0:01:35
---
travis_time:end:14329584:start=1545332461225148456,finish=1545332461233051499,duration=7903043
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:24badd88
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:0662e327
travis_time:start:0662e327
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:0462256e
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2018-12-20 19:30 UTC, alexcrichton commented
@bors: retry

* https://github.com/malept/crypto-hash/issues/6

2018-12-21 17:02 UTC, cramertj commented
@bors retry

```
[02:58:21] [ 46%] Building CXX object lib/IR/CMakeFiles/LLVMCore.dir/Instruction.cpp.o
[02:58:32] [ 46%] Building CXX object lib/CodeGen/CMakeFiles/LLVMCodeGen.dir/DeadMachineInstructionElim.cpp.o
[02:58:42] [ 46%] Building CXX object lib/CodeGen/AsmPrinter/CMakeFiles/LLVMAsmPrinter.dir/DebugLocStream.cpp.o

Broadcast message from root@travis-job-3fdf3aa9-85be-4ce0-8bb9-67e639ddc737
 (unknown) at 9:25 ...
The system is going down for power off NOW!
```
:(

2018-12-22 04:21 UTC, merged