Don't render const keyword on stable
rust-lang/rust pull request #56845
Opened 2018-12-15 12:28 UTC by GuillaumeGomez

Fixes #55246.

Continuation of #55327.

r? @oli-obk

2018-12-18 15:22 UTC, oli-obk commented
So I think I found the issue. The `visit_fn` function just takes the plain `FnHeader` from the `HIR`, which contains `Constness` irrelevant of stability.

Etiher the `visit_fn` method or the `Clean` impl for `doctree::Function` need to access the `tcx` to filter out the constness instead of just passing it down.

2018-12-19 07:15 UTC, oli-obk requested changes
r=me with nix fixed

2018-12-19 07:15 UTC, oli-obk commented on src/librustdoc/clean/mod.rs
> +                header: hir::FnHeader {
you can use struct update syntax for this: `hir::FnHeader { constness, ..self.header }`

2018-12-20 09:30 UTC, GuillaumeGomez commented
Updated.

2018-12-20 09:44 UTC, oli-obk approved these changes

2018-12-20 09:44 UTC, oli-obk commented
@bors r+

2018-12-20 22:04 UTC, merged