suggest `|` when `,` founds in invalid match arms
rust-lang/rust pull request #57008
Opened 2018-12-20 14:06 UTC by Knium

Issue #54807 
I get stuck on (what | how) I should implement...

2018-12-20 14:06 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @petrochenkov (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2018-12-20 23:55 UTC, petrochenkov commented
The current behavior is intentional and has reasons, like it was mentioned in https://github.com/rust-lang/rust/issues/54807.
In some very popular languages like Python tuples can be written without parentheses `(A, B)` <=> `A, B`, so it's reasonable to expect that the user actually meant `(A, B)` while writing `A, B`.

2018-12-21 09:08 UTC, oli-obk commented
As I mentioned in https://github.com/rust-lang/rust/issues/54807#issuecomment-426960202, I believe it would be cool to suggest *both* `(A, B)` and `A | B`. Do you think doing so will complicate the parser more than it's worth it for such a small suggestion?

2018-12-21 11:12 UTC, petrochenkov commented
Suggesting both would be ok, then change will need to be done in `fn parse_top_level_pat` then.
It will give some false positives like recommending `let A | B = expr;`, but that doesn't matter much, it will become legal soon, at least in the parser.

2018-12-26 07:48 UTC, Knium commented
Hi, thanks for reviewing! I need solid blocks of time to understand what you mean and implement. So just a moment pls :)

2019-01-13 06:20 UTC, Knium commented
@Aaronepower Hi, thank you for reminding! Sorry, I'm busier than I thought... If this issue has hurry deadline or there is anyone who want to solve, I approve that someone takes my place. If no one else, I'm still eager to challenge this.

2019-01-22 18:46 UTC, TimNN commented
Ping from triage @Knium:

> Sorry, I'm busier than I thought... If this issue has hurry deadline or there is anyone who want to solve, I approve that someone takes my place.

Don't worry, there is no deadline :). We just like to check in on PRs ~regularly so that we don't have dozens of PRs open that are not being worked on. If you are interested, you can find more information here: https://forge.rust-lang.org/triage-procedure.html

2019-01-29 02:50 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/173622409) ([raw log](https://api.travis-ci.com/v3/job/173622409/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:039f6390:start=1548729784311420653,finish=1548729856791538645,duration=72480117992
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-6.0
---
[00:06:05] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--features" "" "--manifest-path" "/checkout/src/rustc/Cargo.toml" "--message-format" "json"
[00:06:05] expected success, got: exit code: 101
[00:06:05] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap build
[00:06:05] Build completed unsuccessfully in 0:02:30
[00:06:06] Makefile:18: recipe for target 'all' failed
[00:06:06] make: *** [all] Error 1
The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:01ee6049
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
Tue Jan 29 02:50:31 UTC 2019
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-01-29 10:23 UTC, oli-obk requested changes
just a nit, then it lgtm

2019-01-29 10:23 UTC, oli-obk commented on src/libsyntax/parse/parser.rs
> +                    format!("{}", seq_snippet.replace(",", " | ")),
```suggestion
                    format!("{}", seq_snippet.replace(",", " |")),
```

This adds one additional space that already correctly formatted code would not need

2019-01-29 23:40 UTC, petrochenkov commented on src/libsyntax/parse/parser.rs
> +                    "try adding parentheses..",
```suggestion
                    "try adding parentheses to match on a tuple..",
```

2019-01-29 23:41 UTC, petrochenkov commented on src/libsyntax/parse/parser.rs
> +                    "..or a vertical bar",
```suggestion
                    "..or a vertical bar to match on multiple alternatives",
```

2019-01-29 23:41 UTC, petrochenkov commented on src/libsyntax/parse/parser.rs
> +                    "..or a vertical bar",
(Or some similar wording.)

2019-01-30 09:00 UTC, oli-obk approved these changes

2019-01-30 09:01 UTC, oli-obk commented
@bors r+ rollup

Thanks!

2019-01-31 06:31 UTC, merged