Stabilize extern_crate_self
rust-lang/rust pull request #57407
Opened 2019-01-07 16:09 UTC by mehcode

Fixes #56409

2019-01-07 16:09 UTC, rust-highfive commented
r? @pnkfelix

(rust_highfive has picked a reviewer for you, use r? to override)

2019-01-09 03:33 UTC, Centril requested changes
Looks good; the version needs to be adjusted tho.

2019-01-09 03:33 UTC, Centril commented on src/libsyntax/feature_gate.rs
> +    (accepted, extern_crate_self, "1.33.0", Some(56409), None),
```suggestion
    (accepted, extern_crate_self, "1.34.0", Some(56409), None),
```
This won't make it to 1.33.

2019-01-09 04:19 UTC, Centril commented
# Stabilization report

r? @Centril 

**I propose that we stabilize `#[feature(extern_crate_self)]` with 1.34 as the earliest stable version.**

@rfcbot merge

+ Proposed in: https://github.com/rust-lang/rust/pull/55275 and accepted by fcp-merge https://github.com/rust-lang/rust/pull/55275#issuecomment-435574377.
+ Implementation PR: https://github.com/rust-lang/rust/pull/55275 (reviewed by: @eddyb)
+ Days since in nightly: 39 (~5.57 weeks)
+ Tracking issue: https://github.com/rust-lang/rust/issues/56409
+ [Feature gate test being removed](https://github.com/rust-lang/rust/blob/789a15a4221acbbbd2ec1352a0a5ce9f497a4425/src/test/ui/feature-gates/feature-gate-extern_crate_self.rs)
+ Documentation issue in reference: https://github.com/rust-lang-nursery/reference/issues/501

## Motivation

To resolve https://github.com/rust-lang/rust/issues/54647. Also see https://github.com/rust-lang/rust/issues/56409#issuecomment-451776791.

As noted in https://github.com/rust-lang/rust/pull/55275#issue-224835313, this solution doesn't introduce any new syntax and has minimal maintenance cost.

## What is stabilized

Suppose that we have the following item in the current crate:

```rust
fn the_answer() -> usize { 42 }
```

It now becomes *semantically* possible ([test](https://github.com/rust-lang/rust/blob/f79eeaa02d6c4fa5f21f69b30aed5e7ccbd21ad7/src/test/ui/imports/extern-crate-self-pass.rs)) (it *already* was *syntactically* possible) to write `extern crate self as ALIAS` where `ALIAS` is an identifier. The semantics of `extern crate self as ALIAS` is `ALIAS` is added to the extern prelude and will refer to the current crate. Since `ALIAS` is now in the extern prelude you may now write `::ALIAS::the_answer` and `ALIAS::the_answer` under the rules due to https://github.com/rust-lang/rust/pull/54658.

Since `ALIAS` is any identifier, you may now for example write: `extern crate self as serde;` and then refer to `the_answer` by `serde::the_answer`.

You may also write:

+ ```rust
  macro_rules! alias_self {
      ($alias:ident) => { extern crate self as $alias; }
  }
  
  alias_self!(the_alias);
  
  fn main() {
      assert_eq!(the_alias::the_answer(), 42);
  }
  ```

+ ```rust
  macro_rules! extern_something {
      ($alias:ident) => { extern crate self as the_alias; }
  }
   
  extern_something!(self);
   
  fn main() {
      assert_eq!(the_alias::hello(), 42);
  }
  ```

  (@mehcode: please extend the set of tests to include both as `// run-pass` tests..)

## What is not stabilized:

+ `extern crate self;` is semantically rejected ([test](https://github.com/rust-lang/rust/blob/f79eeaa02d6c4fa5f21f69b30aed5e7ccbd21ad7/src/test/ui/imports/extern-crate-self-fail.rs)) since it would add `self` to the extern prelude thus coming into conflict with `self::`.

  However, it is already syntactically valid and will remain so.
  For example:

  ```rust
  macro_rules! accept_item { ($x:item) => {} }

  accept_item! {
      extern crate self;
  }
  ```

  (@mehcode: please extend the set of tests to include this as a `// compile-pass` test..)

2019-01-15 06:36 UTC, Centril approved these changes

2019-01-15 06:44 UTC, Centril requested changes

2019-01-15 06:44 UTC, Centril commented on src/test/ui/imports/extern-crate-self-macro-item.rs
> +macro_rules! accept_item { ($x:item) => {} }
This should be a compile-pass test, the default for UI is compile-fail.

Also add a comment above...

2019-01-15 06:44 UTC, Centril commented on src/test/run-pass/imports/extern-crate-self-macro-1.rs
> +fn the_answer() -> usize { 42 }
Add a comment above explaining the purpose of the test.

2019-01-15 06:44 UTC, Centril commented on src/test/run-pass/imports/extern-crate-self-macro-2.rs
> +fn the_answer() -> usize { 42 }
Add a comment above explaining the purpose of the test.

2019-01-15 06:44 UTC, Centril commented on src/test/run-pass/imports/extern-crate-self-macro-1.rs
> +fn the_answer() -> usize { 42 }
Move this file to `ui/imports/` and explicitly write `// run-pass` on the first line.

If you can put all the test files related to `extern crate self` into `imports/extern-crate-self` that would be nice.

2019-01-15 06:44 UTC, Centril commented on src/test/run-pass/imports/extern-crate-self-macro-2.rs
> +fn the_answer() -> usize { 42 }
Also move this file to ui...

2019-01-15 06:56 UTC, mehcode commented
Thanks for walking me through this @Centril.

2019-01-15 06:59 UTC, Centril requested changes
Some minor style nits; it looks great otherwise.

2019-01-15 06:59 UTC, Centril commented on src/test/ui/imports/extern-crate-self/extern-crate-self-macro-alias.rs
> +// in an `extern crate self as ALIAS` statement
```suggestion
// in an `extern crate self as ALIAS` item.
```

2019-01-15 06:59 UTC, Centril commented on src/test/ui/imports/extern-crate-self/extern-crate-self-macro-item.rs
> +// syntactically as an item for use in a macro
```suggestion
// syntactically as an item for use in a macro.
```

2019-01-15 06:59 UTC, Centril commented on src/test/ui/imports/extern-crate-self/extern-crate-self-macro-self.rs
> +// an `extern crate self as ALIAS` statement
```suggestion
// an `extern crate self as ALIAS` item.
```

2019-01-15 10:55 UTC, Centril approved these changes

2019-01-24 08:11 UTC, mehcode commented
@Centril What's the next step here?

2019-01-24 08:40 UTC, Centril commented
@mehcode Waiting ~two days; after that I'll r+ :)

2019-01-24 08:45 UTC, mehcode commented
Thanks for the clarification. Read somewhere FCP was 7 days so I was confused.

2019-01-24 08:45 UTC, Centril commented
Hehe ;) It's 10 days.

2019-01-26 15:37 UTC, Centril commented
@bors r+

2019-01-26 17:06 UTC, scottmcm commented
@mehcode you're not the only one: https://github.com/rust-lang/rfcs/pull/1981

2019-01-26 20:58 UTC, merged