Stabilize cfg_target_vendor
rust-lang/rust pull request #57465
Opened 2019-01-09 08:34 UTC by jethrogb

This stabilizes the use of `cfg(target_vendor = "...")` and removes the corresponding `cfg_target_vendor` feature. Other unstable cfgs remain behind their existing feature gates.

This functionality was added back in 2015 in #28612 to complete the coverage of target tuples (`<arch><sub>-<vendor>-<os>-<env>`). [RFC 131](https://github.com/rust-lang/rfcs/blob/master/text/0131-target-specification.md) governs the target specification, not including `target_vendor` seems to have just been an oversight. `target_os`, `target_family`, and `target_arch` are stable as of 1.0.0. `target_env` was also not mentioned in RFC 131, was added in #24777, never behind a feature_gate, and insta-stable at 1.1.0.

The functionality is tested in [test/run-pass/cfg/cfg-target-vendor.rs](https://github.com/rust-lang/rust/blob/master/src/test/run-pass/cfg/cfg-target-vendor.rs).

2019-01-09 08:34 UTC, rust-highfive commented
r? @GuillaumeGomez

(rust_highfive has picked a reviewer for you, use r? to override)

2019-01-09 08:41 UTC, Centril requested changes

2019-01-09 08:41 UTC, Centril commented on src/libsyntax/feature_gate.rs
> +    (accepted, cfg_target_vendor, "1.33.0", Some(29718), None),
```suggestion
    (accepted, cfg_target_vendor, "1.34.0", Some(29718), None),
```
This will miss master=>beta promotion on the 15th of January.

2019-01-09 08:44 UTC, Centril commented
r? @joshtriplett

2019-01-09 08:46 UTC, Centril commented
@jethrogb Please file a documentation issue against the https://github.com/rust-lang-nursery/reference/ and link to this PR. Also, if you can help with adjusting the reference that would be good.

2019-01-09 08:48 UTC, jethrogb commented
@Centril this is [already documented](https://doc.rust-lang.org/stable/reference/conditional-compilation.html).

2019-01-09 08:59 UTC, Centril commented
@jethrogb OK; but the possible values are outdated and will need to be updated.

2019-01-09 09:02 UTC, jethrogb commented
I've filed https://github.com/rust-lang-nursery/reference/pull/502 but I think it's entirely orthogonal to this PR.

2019-01-09 14:18 UTC, joshtriplett commented
@bors r+

2019-01-09 14:35 UTC, joshtriplett commented
On second thought, let's make sure people have a chance to confirm that this should be stabilized. I'll r+ if this goes through.

@bors r-
@rfcbot merge

2019-01-10 21:48 UTC, Centril approved these changes

2019-01-14 07:07 UTC, scottmcm commented
To anyone else on lang wondering why,

> Users will be needing this to distinguish between the in-tree `x86_64-fortanix-unknown-sgx` target and other `all(target_arch = "x86_64", target_env = "sgx") targets`, see #57231. Can this be moved to FCP for stabilization? ~ https://github.com/rust-lang/rust/issues/29718#issuecomment-450708554

@rfcbot reviewed

2019-01-14 08:56 UTC, Centril commented
@jethrogb Now that we're in FCP, per Josh's comment, https://github.com/rust-lang/rust/pull/57465#issuecomment-452717509, I think we can ship this. Can you rebase first tho?

2019-01-14 08:57 UTC, jethrogb commented
@Centril are you planning to merge this today for 1.33?

2019-01-14 08:59 UTC, Centril commented
@jethrogb Yes, hopefully at least; we have 1 day to master=>beta promotion, so it should be sufficient time to merge this PR.

@bors p=1

2019-01-14 09:03 UTC, jethrogb commented
Ok cool, wasn't sure if you wanted to wait for FCP or not. Rebased.

2019-01-14 09:07 UTC, Centril commented
@bors r=joshtriplett,Centril

2019-01-14 15:46 UTC, merged