Add signed num::NonZeroI* types
rust-lang/rust pull request #57475
Opened 2019-01-09 18:48 UTC by SimonSapin

Multiple people have asked for them in https://github.com/rust-lang/rust/issues/49137. Given that the unsigned ones already exist, they are very easy to add and not an additional maintenance burden.

2019-01-09 18:48 UTC, rust-highfive commented
r? @aidanhs

(rust_highfive has picked a reviewer for you, use r? to override)

2019-01-09 18:54 UTC, SimonSapin commented
The new types are stable in this PR, so let’s get team sign-off:

@rfcbot fcp merge

They don’t really need to be. But they are very similar to the existing unsigned non-zero integer types, so it seems to me that having them as unstable for a period of time is very unlikely to bring new information. Also, making the signed and unsigned type behave differently (beyond signedness) or have different API seems like it would be unfortunate, and the latter are already stable.

2019-01-09 19:57 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.org/rust-lang/rust/jobs/477483270) ([raw log](https://api.travis-ci.org/v3/job/477483270/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:1ab20504:start=1547059796556912748,finish=1547059797474349550,duration=917436802
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-6.0
---
[00:04:38] 71  |                           Some(unsafe { $Ty(n) })
[00:04:38]     |                                ^^^^^^ unnecessary `unsafe` block
[00:04:38] ...
[00:04:38] 100 | / nonzero_integers! {
[00:04:38] 101 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU8(u8);
[00:04:38] 102 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU16(u16);
[00:04:38] 103 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU32(u32);
[00:04:38] ...   |
[00:04:38] 112 | |     #[stable(feature = "signed_nonzero", since = "1.33.0")] NonZeroIsize(isize);
[00:04:38]     | |_- in this macro invocation
[00:04:38]     |
[00:04:38]     = note: #[warn(unused_unsafe)] on by default
[00:04:38] 
[00:04:38] 
[00:04:38] warning: unnecessary `unsafe` block
[00:04:38]    --> src/libcore/num/mod.rs:71:30
[00:04:38]     |
[00:04:38] 71  |                           Some(unsafe { $Ty(n) })
[00:04:38]     |                                ^^^^^^ unnecessary `unsafe` block
[00:04:38] ...
[00:04:38] 100 | / nonzero_integers! {
[00:04:38] 101 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU8(u8);
[00:04:38] 102 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU16(u16);
[00:04:38] 103 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU32(u32);
[00:04:38] ...   |
[00:04:38] 112 | |     #[stable(feature = "signed_nonzero", since = "1.33.0")] NonZeroIsize(isize);
[00:04:38]     | |_- in this macro invocation
[00:04:38] 
[00:04:38] warning: unnecessary `unsafe` block
[00:04:38]     --> src/libcore/ptr.rs:2785:18
---
[00:04:38] 50  |                   #[rustc_layout_scalar_valid_range_start(1)]
[00:04:38]     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[00:04:38] ...
[00:04:38] 100 | / nonzero_integers! {
[00:04:38] 101 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU8(u8);
[00:04:38] 102 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU16(u16);
[00:04:38] 103 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU32(u32);
[00:04:38] ...   |
[00:04:38] 112 | |     #[stable(feature = "signed_nonzero", since = "1.33.0")] NonZeroIsize(isize);
[00:04:38]     | |_- in this macro invocation
[00:04:38]     |
[00:04:38]     = note: #[warn(unused_attributes)] on by default
[00:04:38] 
[00:04:38] 
[00:04:38] warning: unused attribute
[00:04:38]    --> src/libcore/num/mod.rs:50:17
[00:04:38]     |
[00:04:38] 50  |                   #[rustc_layout_scalar_valid_range_start(1)]
[00:04:38]     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[00:04:38] ...
[00:04:38] 100 | / nonzero_integers! {
[00:04:38] 101 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU8(u8);
[00:04:38] 102 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU16(u16);
[00:04:38] 103 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU32(u32);
[00:04:38] ...   |
[00:04:38] 112 | |     #[stable(feature = "signed_nonzero", since = "1.33.0")] NonZeroIsize(isize);
[00:04:38]     | |_- in this macro invocation
[00:04:38] 
[00:04:38] warning: unused attribute
[00:04:38]     --> src/libcore/ptr.rs:2720:1
---
[01:07:11] .................................................................................................... 4600/5298
[01:07:15] .................................................................................................... 4700/5298
[01:07:18] .................................................................................................... 4800/5298
[01:07:23] .................................................................................................... 4900/5298
[01:07:27] ..............................................F..................................................... 5000/5298
[01:07:33] .................................................................................................... 5200/5298
[01:07:36] .....................................i............................................................
[01:07:36] failures:
[01:07:36] 
[01:07:36] 
[01:07:36] ---- [ui] ui/try-block/try-block-bad-type.rs stdout ----
[01:07:36] diff of stderr:
[01:07:36] 
[01:07:36] 5    |         ^^^^^^^^ the trait `std::convert::From<&str>` is not implemented for `i32`
[01:07:36] 7    = help: the following implementations were found:
[01:07:36] 7    = help: the following implementations were found:
[01:07:36] -              <i32 as std::convert::From<bool>>
[01:07:36] +              <i32 as std::convert::From<core::num::NonZeroI32>>
[01:07:36] 9              <i32 as std::convert::From<i16>>
[01:07:36] 10              <i32 as std::convert::From<i8>>
[01:07:36] -              <i32 as std::convert::From<u16>>
[01:07:36] 12              <i32 as std::convert::From<u8>>
[01:07:36] 13    = note: required by `std::convert::From::from`
[01:07:36] 14 
[01:07:36] 14 
[01:07:36] 15 error[E0271]: type mismatch resolving `<std::result::Result<i32, i32> as std::ops::Try>::Ok == &str`
[01:07:36] 
[01:07:36] The actual stderr differed from the expected stderr.
[01:07:36] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/try-block/try-block-bad-type/try-block-bad-type.stderr
[01:07:36] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/try-block/try-block-bad-type/try-block-bad-type.stderr
[01:07:36] To update references, rerun the tests and pass the `--bless` flag
[01:07:36] To only update this specific test, also pass `--test-args try-block/try-block-bad-type.rs`
[01:07:36] error: 1 errors occurred comparing output.
[01:07:36] status: exit code: 1
[01:07:36] status: exit code: 1
[01:07:36] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/try-block/try-block-bad-type.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/try-block/try-block-bad-type/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--edition" "2018" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/try-block/try-block-bad-type/auxiliary" "-A" "unused"
[01:07:36] ------------------------------------------
[01:07:36] 
[01:07:36] ------------------------------------------
[01:07:36] stderr:
[01:07:36] stderr:
[01:07:36] ------------------------------------------
[01:07:36] {"message":"the trait bound `i32: std::convert::From<&str>` is not satisfied","code":{"code":"E0277","explanation":"\nYou tried to use a type which doesn't implement some trait in a place which\nexpected that trait. Erroneous code example:\n\n```compile_fail,E0277\n// here we declare the Foo trait with a bar method\ntrait Foo {\n    fn bar(&self);\n}\n\n// we now declare a function which takes an object implementing the Foo trait\nfn some_func<T: Foo>(foo: T) {\n    foo.bar();\n}\n\nfn main() {\n    // we now call the method with the i32 type, which doesn't implement\n    // the Foo trait\n    some_func(5i32); // error: the trait bound `i32 : Foo` is not satisfied\n}\n```\n\nIn order  [...]

2019-01-10 01:43 UTC, Amanieu commented
I'm in favor of this since it would make `NonZero*` consistent with `Atomic*`, which has both signed and unsigned variants even though you could get away with just one.

2019-01-10 07:04 UTC, xfix commented
I think it would make sense to have some tests for `NonZeroI*` types.

2019-01-10 07:05 UTC, sugar700 requested changes
I think it would make sense to have some tests for NonZeroI* types. Check whether they can store negative values without causing undefined behaviour, and so on.

2019-01-10 15:51 UTC, Xaeroxe commented
Thank you for this! [This is the happiest I've ever been to deprecate my own code.](https://github.com/Xaeroxe/nonzero_signed/pull/1)

2019-01-10 17:32 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/169556907) ([raw log](https://api.travis-ci.com/v3/job/169556907/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_fold:start:worker_info
Worker information
hostname: 2b5a4b35-2d7e-4056-a526-a3b927f0331d@1.production-2-worker-com-gce-btlt
version: v6.2.0 https://github.com/travis-ci/worker/tree/5e5476e01646095f48eec13196fdb3faf8f5cbf7
startup: 6.815506732s
travis_fold:end:worker_info
travis_fold:start:system_info
Build system information
---
travis_time:end:2865d998:start=1547137555748345823,finish=1547137556625158916,duration=876813093
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-6.0
---
[00:04:36] 71  |                           Some(unsafe { $Ty(n) })
[00:04:36]     |                                ^^^^^^ unnecessary `unsafe` block
[00:04:36] ...
[00:04:36] 100 | / nonzero_integers! {
[00:04:36] 101 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU8(u8);
[00:04:36] 102 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU16(u16);
[00:04:36] 103 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU32(u32);
[00:04:36] ...   |
[00:04:36] 112 | |     #[stable(feature = "signed_nonzero", since = "1.33.0")] NonZeroIsize(isize);
[00:04:36]     | |_- in this macro invocation
[00:04:36]     |
[00:04:36]     = note: #[warn(unused_unsafe)] on by default
[00:04:36] 
[00:04:36] 
[00:04:36] warning: unnecessary `unsafe` block
[00:04:36]    --> src/libcore/num/mod.rs:71:30
[00:04:36]     |
[00:04:36] 71  |                           Some(unsafe { $Ty(n) })
[00:04:36]     |                                ^^^^^^ unnecessary `unsafe` block
[00:04:36] ...
[00:04:36] 100 | / nonzero_integers! {
[00:04:36] 101 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU8(u8);
[00:04:36] 102 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU16(u16);
[00:04:36] 103 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU32(u32);
[00:04:36] ...   |
[00:04:36] 112 | |     #[stable(feature = "signed_nonzero", since = "1.33.0")] NonZeroIsize(isize);
[00:04:36]     | |_- in this macro invocation
[00:04:36] 
[00:04:36] warning: unnecessary `unsafe` block
[00:04:36]     --> src/libcore/ptr.rs:2785:18
---
[00:04:36] 50  |                   #[rustc_layout_scalar_valid_range_start(1)]
[00:04:36]     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[00:04:36] ...
[00:04:36] 100 | / nonzero_integers! {
[00:04:36] 101 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU8(u8);
[00:04:36] 102 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU16(u16);
[00:04:36] 103 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU32(u32);
[00:04:36] ...   |
[00:04:36] 112 | |     #[stable(feature = "signed_nonzero", since = "1.33.0")] NonZeroIsize(isize);
[00:04:36]     | |_- in this macro invocation
[00:04:36]     |
[00:04:36]     = note: #[warn(unused_attributes)] on by default
[00:04:36] 
[00:04:36] 
[00:04:36] warning: unused attribute
[00:04:36]    --> src/libcore/num/mod.rs:50:17
[00:04:36]     |
[00:04:36] 50  |                   #[rustc_layout_scalar_valid_range_start(1)]
[00:04:36]     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[00:04:36] ...
[00:04:36] 100 | / nonzero_integers! {
[00:04:36] 101 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU8(u8);
[00:04:36] 102 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU16(u16);
[00:04:36] 103 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU32(u32);
[00:04:36] ...   |
[00:04:36] 112 | |     #[stable(feature = "signed_nonzero", since = "1.33.0")] NonZeroIsize(isize);
[00:04:36]     | |_- in this macro invocation
[00:04:36] 
[00:04:36] warning: unused attribute
[00:04:36]     --> src/libcore/ptr.rs:2720:1
---
[01:05:29] .................................................................................................... 4600/5298
[01:05:32] .................................................................................................... 4700/5298
[01:05:35] .................................................................................................... 4800/5298
[01:05:39] .................................................................................................... 4900/5298
[01:05:43] ..............................................F..................................................... 5000/5298
[01:05:49] .................................................................................................... 5200/5298
[01:05:51] .....................................i............................................................
[01:05:51] failures:
[01:05:51] 
[01:05:51] 
[01:05:51] ---- [ui] ui/try-block/try-block-bad-type.rs stdout ----
[01:05:51] diff of stderr:
[01:05:51] 
[01:05:51] 5    |         ^^^^^^^^ the trait `std::convert::From<&str>` is not implemented for `i32`
[01:05:51] 7    = help: the following implementations were found:
[01:05:51] 7    = help: the following implementations were found:
[01:05:51] -              <i32 as std::convert::From<bool>>
[01:05:51] +              <i32 as std::convert::From<core::num::NonZer--------
[01:05:51] {"message":"the trait bound `i32: std::convert::From<&str>` is not satisfied","code":{"code":"E0277","explanation":"\nYou tried to use a type which doesn't implement some trait in a place which\nexpected that trait. Erroneous code example:\n\n```compile_fail,E0277\n// here we declare the Foo trait with a bar method\ntrait Foo {\n    fn bar(&self);\n}\n\n// we now declare a function which takes an object implementing the Foo trait\nfn some_func<T: Foo>(foo: T) {\n    foo.bar();\n}\n\nfn main() {\n    // we now call the method with the i32 type, which doesn't implement\n    // the Foo trait\n    some_func(5i32); // error: the trait bound `i32 : Foo` is not satisfied\n}\n```\n\nIn order to fix this error, verify that the type you're using does implement\nthe trait. Example:\n\n```\ntrait Foo {\n    fn bar(&self);\n}\n\nfn some_func<T: Foo>(foo: T) {\n    foo.bar(); // we can now use this method since i32 implements the\n               // Foo trait\n}\n\n// we implement the trait on the i32 type\nimpl Foo for i32 {\n    fn bar(&self) {}\n}\n\nfn main() {\n    some_func(5i32); // ok!\n}\n```\n\nOr in a generic context, an erroneous code example would look like:\n\n```compile_fail,E0277\nfn some_func<T>(foo: T) {\n    println!(\"{:?}\", foo); // error: the trait `core::fmt::Debug` is not\n                           //        implemented for the type `T`\n}\n\nfn main() {\n    // We now call the method with the i32 type,\n    // which *does* implement the Debug trait.\n    some_func(5i32);\n}\n```\n\nNote that the error here is in the definition of the generic function: Although\nwe only call it with a parameter that does implement `Debug`, the compiler\nstill rejects the function: It must work with all possible input types. In\norder to make this example compile, we need to restrict the generic type we're\naccepting:\n\n```\nuse std::fmt;\n\n// Restrict the input type to types that implement Debug.\nfn some_func<T: fmt::Debug>(foo: T) {\n    println!(\"{:?}\", foo);\n}\n\nfn main() {\n    // Calling the method is still fine, as i32 implements Debug.\n    some_func(5i32);\n\n    // This would fail to compile now:\n    // struct WithoutDebug;\n    // some_func(WithoutDebug);\n}\n```\n\nRust only looks at the sign [...]

2019-01-10 23:04 UTC, SimonSapin commented
I’d appreciate some help. Maybe @alexcrichton?

I’m getting errors like

```rust
---- num/mod.rs - num::NonZeroI16 (line 33) stdout ----
error[E0412]: cannot find type `NonZeroI16` in module `std::num`
 --> num/mod.rs:35:39
  |
5 | assert_eq!(size_of::<Option<std::num::NonZeroI16>>(), size_of::<i16>());
  |                                       ^^^^^^^^^^ did you mean `NonZeroU16`?

thread 'num/mod.rs - num::NonZeroI16 (line 33)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13
```

It looks like a newly-added type cannot be found *in the doctests of that very type*.

Later in the output:

```
command did not execute successfully: "/home/simon/rust3/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "-j" "8" "--release" "--features" "panic-unwind backtrace" "--manifest-path" "/home/simon/rust3/src/libstd/Cargo.toml" "-p" "core" "--" "--quiet"
expected success, got: exit code: 101
```

… which includes `stage0`. The error would make some sense if the bootstrap compiler’s libcore is used to run the new libcore’s doctests, but why would that be the case when running simply `./x.py test`?

2019-01-11 00:06 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/169662277) ([raw log](https://api.travis-ci.com/v3/job/169662277/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:0fe5c89c:start=1547161308643622142,finish=1547161310979617799,duration=2335995657
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-6.0
---
    97% |███████████████████████████████▍| 532kB 84.1MB/s eta 0:00:01
    99% |████████████████████████████████| 542kB 83.9MB/s eta 0:00:01
    100% |████████████████████████████████| 552kB 29.6MB/s 
Collecting botocore==1.12.77 (from awscli)
  Downloading https://files.pythonhosted.org/packages/f3/cd/f58bacbfb28d92716bfb7af2a8c5d5230663335b6a5e4d78d8ccdfab469d/botocore-1.12.77-py2.py3-none-any.whl (5.2MB)
    0% |▏                               | 20kB 29.5MB/s eta 0:00:01
    0% |▏                               | 30kB 35.6MB/s eta 0:00:01
    0% |▎                               | 40kB 40.3MB/s eta 0:00:01
    0% |▎                               | 51kB 43.3MB/s eta 0:00:01
---
[00:04:02] 71  |                           Some(unsafe { $Ty(n) })
[00:04:02]     |                                ^^^^^^ unnecessary `unsafe` block
[00:04:02] ...
[00:04:02] 100 | / nonzero_integers! {
[00:04:02] 101 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU8(u8);
[00:04:02] 102 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU16(u16);
[00:04:02] 103 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU32(u32);
[00:04:02] ...   |
[00:04:02] 112 | |     #[stable(feature = "signed_nonzero", since = "1.33.0")] NonZeroIsize(isize);
[00:04:02]     | |_- in this macro invocation
[00:04:02]     |
[00:04:02]     = note: #[warn(unused_unsafe)] on by default
[00:04:02] 
[00:04:02] 
[00:04:02] warning: unnecessary `unsafe` block
[00:04:02]    --> src/libcore/num/mod.rs:71:30
[00:04:02]     |
[00:04:02] 71  |                           Some(unsafe { $Ty(n) })
[00:04:02]     |                                ^^^^^^ unnecessary `unsafe` block
[00:04:02] ...
[00:04:02] 100 | / nonzero_integers! {
[00:04:02] 101 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU8(u8);
[00:04:02] 102 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU16(u16);
[00:04:02] 103 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU32(u32);
[00:04:02] ...   |
[00:04:02] 112 | |     #[stable(feature = "signed_nonzero", since = "1.33.0")] NonZeroIsize(isize);
[00:04:02]     | |_- in this macro invocation
[00:04:02] 
[00:04:02] warning: unnecessary `unsafe` block
[00:04:02]     --> src/libcore/ptr.rs:2785:18
---
[00:04:02] 50  |                   #[rustc_layout_scalar_valid_range_start(1)]
[00:04:02]     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[00:04:02] ...
[00:04:02] 100 | / nonzero_integers! {
[00:04:02] 101 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU8(u8);
[00:04:02] 102 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU16(u16);
[00:04:02] 103 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU32(u32);
[00:04:02] ...   |
[00:04:02] 112 | |     #[stable(feature = "signed_nonzero", since = "1.33.0")] NonZeroIsize(isize);
[00:04:02]     | |_- in this macro invocation
[00:04:02]     |
[00:04:02]     = note: #[warn(unused_attributes)] on by default
[00:04:02] 
[00:04:02] 
[00:04:02] warning: unused attribute
[00:04:02]    --> src/libcore/num/mod.rs:50:17
[00:04:02]     |
[00:04:02] 50  |                   #[rustc_layout_scalar_valid_range_start(1)]
[00:04:02]     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[00:04:02] ...
[00:04:02] 100 | / nonzero_integers! {
[00:04:02] 101 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU8(u8);
[00:04:02] 102 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU16(u16);
[00:04:02] 103 | |     #[stable(feature = "nonzero", since = "1.28.0")] NonZeroU32(u32);
[00:04:02] ...   |
[00:04:02] 112 | |     #[stable(feature = "signed_nonzero", since = "1.33.0")] NonZeroIsize(isize);
[00:04:02]     | |_- in this macro invocation
[00:04:02] 
[00:04:02] warning: unused attribute
[00:04:02]     --> src/libcore/ptr.rs:2720:1
---
[01:03:37] .................................................................................................... 4600/5298
[01:03:40] .................................................................................................... 4700/5298
[01:03:43] .................................................................................................... 4800/5298
[01:03:47] .................................................................................................... 4900/5298
[01:03:51] ..............................................F..................................................... 5000/5298
[01:03:58] .................................................................................................... 5200/5298
[01:04:01] .....................................i............................................................
[01:04:01] failures:
[01:04:01] 
[01:04:01] 
[01:04:01] ---- [ui] ui/try-block/try-block-bad-type.rs stdout ----
[01:04:01] diff of stderr:
[01:04:01] 
[01:04:01] 5    |         ^^^^^^^^ the trait `std::convert::From<&str>` is not implemented for `i32`
[01:04:01] 7    = help: the following implementations were found:
[01:04:01] 7    = help: the following implementations were found:
[01:04:01] -              <i32 as std::convert::From<bool>>
[01:04:01] +              <i32 as std::convert::From<core::num::NonZeroI32>>
[01:04:01] 9              <i32 as std::convert::From<i16>>
[01:04:01] -              <i32 as std::convert::From<u16>>
[01:04:01] +              <i32 as std::convert::From<i8>>
[01:04:01] 11              <i32 as std::convert::From<u8>>
[01:04:01] 13    = note: required by `std::convert::From::from`
[01:04:01] 
[01:04:01] 
[01:04:01] The actual stderr differed from the expected stderr.
[01:04:01] The actual stderr differed from the expected stderr.
[01:04:01] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/try-block/try-block-bad-type/try-block-bad-type.stderr
[01:04:01] To update references, rerun the tests and pass the `--bless` flag
[01:04:01] To only update this specific test, also pass `--test-args try-block/try-block-bad-type.rs`
[01:04:01] error: 1 errors occurred comparing output.
[01:04:01] status: exit code: 1
[01:04:01] status: exit code: 1
[01:04:01] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/try-block/try-block-bad-type.rs" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/try-block/try-block-bad-type/a" "-Crpath" "-O" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--edition" "2018" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/try-block/try-block-bad-type/auxiliary" "-A" "unused"
[01:04:01] ------------------------------------------
[01:04:01] 
[01:04:01] ------------------------------------------
[01:04:01] stderr:
[01:04:01] stderr:
[01:04:01] ------------------------------------------
[01:04:01] {"message":"the trait bound `i32: std::convert::From<&str>` is not satisfied","code":{"code":"E0277","explanation":"\nYou tried to use a type which doesn't implement some trait in a place which\nexpected that trait. Er [...]

2019-01-11 14:01 UTC, SimonSapin commented
Also, `./x.py test --test-args try-block/try-block-bad-type.rs` succeeds on my machine, even after a rebase on `master`, while the same test fails on Travis :/

2019-01-11 17:33 UTC, alexcrichton commented
@SimonSapin hm something looks seriously wrong here! I wonder if this is a preexisting compiler bug you're running into. Can you reproduce the travis failure with `./src/ci/docker/run.sh x86_64-gnu-llvm-6.0`?

2019-01-11 19:18 UTC, sugar700 approved these changes

2019-01-11 23:38 UTC, SimonSapin commented
@alexcrichton Yes, that command on my machine gives the same output as on Travis.

2019-01-12 00:00 UTC, SimonSapin commented
eIf I tweak `src/test/ui/try-block/try-block-bad-type.stderr` to get past that error, I can get to the same error as https://github.com/rust-lang/rust/pull/57475#issuecomment-453291779 in Docker (and presumably on Travis). But then it is `./x.py test` on by Ubuntu 18.04 environment that fails `try-block-bad-type`.

2019-01-17 11:02 UTC, SimonSapin commented
@oli-obk (CC https://github.com/rust-lang/rust/pull/54032), is the valid range for the purpose of `#[rustc_layout_scalar_valid_range_start(1)]` based on the "unsigned view" of some memory bits, or on the actual semantics of the type? Specifically, does it only exclude zero when used on a wrapper of a signed integer type like `i32`, or also negative values?

2019-01-17 12:20 UTC, oli-obk commented
It works on the unsigned view. It uses the same representation as our compiler internal layout definition.

2019-01-17 14:08 UTC, SimonSapin commented
> It looks like a newly-added type cannot be found in the doctests of that very type.

When running `./x.py test -vv`, I see (newlines added):

```
rustdoc command:
"/home/simon/rust3/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc"
"--test"
"/home/simon/rust3/src/libcore/lib.rs"
"--crate-name"
"core"
"-L"
"dependency=/home/simon/rust3/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps"
"-L"
"dependency=/home/simon/rust3/build/x86_64-unknown-linux-gnu/stage1-std/release/deps"
"--test-args"
"NonZero"
"--test-args"
"--quiet"
"--extern"
"core=/home/simon/rust3/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/libcore-852c25e755af0d0c.rlib"
"--extern"
"rand=/home/simon/rust3/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/librand-5423a3ce52cd7271.rlib"
"--cfg"
"stage1"
"--cfg"
"dox"
"--sysroot"
"/home/simon/rust3/build/x86_64-unknown-linux-gnu/stage1"
"-Z"
"force-unstable-if-unmarked"
"-Z"
"unstable-options"
"--crate-version"
"1.33.0-dev"
```

Note the presence of `--extern core=…`, but nothing similar for `std`. Changing `std::num` to `core::num` in the doctest seems to work around this issue.

Is it possible that doctests are using libcore compiled from the repository, but libstd from the bootstrap / stage0 compiler?

2019-01-17 16:31 UTC, oli-obk commented on src/libcore/num/mod.rs
> +use mem;9e448348b9
accidental paste

2019-01-17 16:32 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/171180139) ([raw log](https://api.travis-ci.com/v3/job/171180139/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:02f3ffb8:start=1547742535837093475,finish=1547742537073951128,duration=1236857653
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-6.0
---
[00:03:30] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--features" "panic-unwind backtrace" "--manifest-path" "/checkout/src/libstd/Cargo.toml" "--message-format" "json"
[00:03:30] expected success, got: exit code: 101
[00:03:30] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap build
[00:03:30] Build completed unsuccessfully in 0:00:06
[00:03:30] make: *** [all] Error 1
[00:03:30] Makefile:18: recipe for target 'all' failed
The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:07e3fb53
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
Thu Jan 17 16:32:39 UTC 2019
Thu Jan 17 16:32:39 UTC 2019
|| true
travis_time:end:01d67b88:start=1547742759827842676,finish=1547742759834120533,duration=6277857
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:3e320ce4
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:1c2e68b9
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-01-17 16:33 UTC, SimonSapin commented on src/libcore/num/mod.rs
> +use mem;9e448348b9
Good catch, thanks.

2019-01-17 16:43 UTC, alexcrichton commented
@bors: r+

2019-01-18 11:36 UTC, Centril commented
Failed in rollup, https://github.com/rust-lang/rust/pull/57727#issuecomment-455517221.

@bors r-

2019-01-18 11:44 UTC, SimonSapin commented
The set of impls printed (or at least their order) in the `error[E0277]` diagnostic varies between environments. The diff below would (likely) fix the `mingw-check` CI job like in https://github.com/rust-lang/rust/pull/57727#issuecomment-455517221, but break `x86_64-gnu-llvm-6.0` like in https://github.com/rust-lang/rust/pull/57475#issuecomment-453183765.

Any idea what’s going on?

```diff
diff --git a/src/test/ui/try-block/try-block-bad-type.stderr b/src/test/ui/try-block/try-block-bad-type.stderr
index c2f9e9b52b..4e964f4b83 100644
--- a/src/test/ui/try-block/try-block-bad-type.stderr
+++ b/src/test/ui/try-block/try-block-bad-type.stderr
@@ -5,9 +5,9 @@ LL |         Err("")?; //~ ERROR the trait bound `i32: std::convert::From<&str>`
    |         ^^^^^^^^ the trait `std::convert::From<&str>` is not implemented for `i32`
    |
    = help: the following implementations were found:
-             <i32 as std::convert::From<core::num::NonZeroI32>>
+             <i32 as std::convert::From<bool>>
              <i32 as std::convert::From<i16>>
-             <i32 as std::convert::From<i8>>
+             <i32 as std::convert::From<u16>>
              <i32 as std::convert::From<u8>>
            and 2 others
    = note: required by `std::convert::From::from`

2019-01-21 17:45 UTC, SimonSapin commented
I pushed a commit that I hope will fix this by removing some non-determinism.

@estebank, could you have a look? Can `impl_candidates` in `report_similar_impl_candidates` be very large? With this commit we’re doing some work (`normalize` and `sort`) on all of it, not just the first 4 or 5 impls.

2019-01-21 18:11 UTC, estebank commented
@SimonSapin it is _potentially_ huge, but in practice I would only imagine this being problematic in the case of generated code. But there are two things: 1) this is only relevant for failing code, so the cost only needs to be "human-speed", we're unlikely to hit problems there in any realistic scenario and 2) we might get away with changing `fn all_impls(self, def_id: DefId) -> Vec<DefId>` to return an `Iterator`. That wouldn't be a huge code change, nor performance change, but we're doing `iter` -> `collect` -> `iter` -> `filter_map` -> `collect` a few times on the same data :-|

I would go ahead with it, maybe adding a debug statement before and after to be able to check after the fact with a pathological case what the time is.

2019-01-21 20:18 UTC, xfix commented
Sorting can be optimized by using heap sort instead of whatever sorting algorithm uses, but considering this is an error case, it's likely not worth doing.

2019-01-22 08:25 UTC, merged