Rustodc remove old style files
rust-lang/rust pull request #57929
Opened 2019-01-26 23:46 UTC by GuillaumeGomez

Reopening of #56577 (which I can't seem to reopen...).

I made the flag unstable so with this change, what was blocking the PR is now gone I assume.

r? @QuietMisdreavus

2019-01-27 16:21 UTC, ollie27 commented on src/bootstrap/doc.rs
> +        .arg("--generate-redirect-pages");
This doesn't do anything because this code is only used for markdown files in `src/doc/book/redirects`.

2019-01-27 16:21 UTC, ollie27 commented on src/bootstrap/doc.rs
> +                 .arg("--generate-redirect-pages")
This will only apply to `core`, `alloc` and `std`. Presumably we'll want the redirects for `test` and `proc_macro` as well.

2019-01-27 16:21 UTC, ollie27 commented on src/librustdoc/html/render.rs
> +                    if item_type == ItemType::Macro {
The macro redirects have nothing to do with the redirects used by RLS so it doesn't make any sense for them to be controlled by the same command line argument.

2019-01-30 11:51 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/174020233) ([raw log](https://api.travis-ci.com/v3/job/174020233/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:3b4135de:start=1548845451376193878,finish=1548845520945359157,duration=69569165279
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-6.0
---
[00:59:13]     Checking rustc_tsan v0.0.0 (/checkout/src/librustc_tsan)
[00:59:14]  Documenting std v0.0.0 (/checkout/src/libstd)
[00:59:26]     Finished release [optimized] target(s) in 17.60s
[00:59:26] Documenting stage2 test (x86_64-unknown-linux-gnu)
[00:59:26] error: Found argument '--generate-redirect-pages' which wasn't expected, or isn't valid in this context
[00:59:26] USAGE:
[00:59:26] USAGE:
[00:59:26]     cargo doc --color <WHEN> --jobs <N> --locked --manifest-path <PATH> --release --target <TRIPLE> -Z <FLAG>...
[00:59:26] For more information try --help
[00:59:26] 
[00:59:26] 
[00:59:26] 
[00:59:26] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "doc" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/libtest/Cargo.toml" "-Z" "unstable-options" "--generate-redirect-pages" "--no-deps" "-p" "test"
[00:59:26] 
[00:59:26] 
[00:59:26] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap doc
[00:59:26] Build completed unsuccessfully in 0:05:22
[00:59:26] Build completed unsuccessfully in 0:05:22
[00:59:26] Makefile:18: recipe for target 'all' failed
[00:59:26] make: *** [all] Error 1
The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:17d70a82
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
Wed Jan 30 11:51:36 UTC 2019
---
travis_time:end:08cc3890:start=1548849097982276465,finish=1548849097988551762,duration=6275297
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:31a25563
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:0cfa673c
travis_time:start:0cfa673c
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:072e2380
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-01-30 22:58 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/174224286) ([raw log](https://api.travis-ci.com/v3/job/174224286/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:1dff12b8:start=1548888795561254379,finish=1548888878808506257,duration=83247251878
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-6.0
---
[00:01:45]    Compiling serde_derive v1.0.81
[00:01:46]    Compiling toml v0.4.10
[00:01:46]    Compiling serde_json v1.0.33
[00:01:54]    Compiling bootstrap v0.0.0 (/checkout/src/bootstrap)
[00:01:57] error[E0599]: no method named `qrg` found for type `&mut std::process::Command` in the current scope
[00:01:57]     |
[00:01:57]     |
[00:01:57] 590 |              .qrg("--")
[00:01:57]     |
[00:01:57]     = help: did you mean `arg`?
[00:01:57] 
[00:01:58] error: aborting due to previous error
---
[00:01:58] make: *** [prepare] Error 1
[00:01:58] Makefile:70: recipe for target 'prepare' failed
[00:01:59] Command failed. Attempt 2/5:
[00:01:59]    Compiling bootstrap v0.0.0 (/checkout/src/bootstrap)
[00:02:03] error[E0599]: no method named `qrg` found for type `&mut std::process::Command` in the current scope
[00:02:03]     |
[00:02:03]     |
[00:02:03] 590 |              .qrg("--")
[00:02:03]     |
[00:02:03]     = help: did you mean `arg`?
[00:02:03] 
[00:02:03] error: aborting due to previous error
---
[00:02:03] make: *** [prepare] Error 1
[00:02:03] Makefile:70: recipe for target 'prepare' failed
[00:02:05] Command failed. Attempt 3/5:
[00:02:05]    Compiling bootstrap v0.0.0 (/checkout/src/bootstrap)
[00:02:09] error[E0599]: no method named `qrg` found for type `&mut std::process::Command` in the current scope
[00:02:09]     |
[00:02:09]     |
[00:02:09] 590 |              .qrg("--")
[00:02:09]     |
[00:02:09]     = help: did you mean `arg`?
[00:02:09] 
[00:02:09] error: aborting due to previous error
---
[00:02:09] Makefile:70: recipe for target 'prepare' failed
[00:02:09] make: *** [prepare] Error 1
[00:02:12] Command failed. Attempt 4/5:
[00:02:13]    Compiling bootstrap v0.0.0 (/checkout/src/bootstrap)
[00:02:16] error[E0599]: no method named `qrg` found for type `&mut std::process::Command` in the current scope
[00:02:16]     |
[00:02:16]     |
[00:02:16] 590 |              .qrg("--")
[00:02:16]     |
[00:02:16]     = help: did you mean `arg`?
[00:02:16] 
[00:02:17] error: aborting due to previous error
---
[00:02:17] make: *** [prepare] Error 1
[00:02:17] Makefile:70: recipe for target 'prepare' failed
[00:02:21] Command failed. Attempt 5/5:
[00:02:21]    Compiling bootstrap v0.0.0 (/checkout/src/bootstrap)
[00:02:24] error[E0599]: no method named `qrg` found for type `&mut std::process::Command` in the current scope
[00:02:24]     |
[00:02:24]     |
[00:02:24] 590 |              .qrg("--")
[00:02:24]     |
[00:02:24]     = help: did you mean `arg`?
[00:02:24] 
[00:02:25] error: aborting due to previous error
---
travis_time:end:2a18b2e2:start=1548889034154737382,finish=1548889034160053687,duration=5316305
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:2163ad71
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:25d6b605
travis_time:start:25d6b605
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:1730613e
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-01-31 00:03 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/174227711) ([raw log](https://api.travis-ci.com/v3/job/174227711/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:00f1e9e9:start=1548889410316757606,finish=1548889480512194772,duration=70195437166
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-6.0
---
[00:58:10]     Checking rustc_lsan v0.0.0 (/checkout/src/librustc_lsan)
[00:58:10]  Documenting std v0.0.0 (/checkout/src/libstd)
[00:58:21]     Finished release [optimized] target(s) in 16.74s
[00:58:21] Documenting stage2 test (x86_64-unknown-linux-gnu)
[00:58:21] error: Found argument '--no-deps' which wasn't expected, or isn't valid in this context
[00:58:21]  Did you mean --no-default-features?
[00:58:21] USAGE:
[00:58:21] USAGE:
[00:58:21]     cargo rustdoc --color <WHEN> --jobs <N> --locked --manifest-path <PATH> --no-default-features --release --target <TRIPLE>
[00:58:21] For more information try --help
[00:58:21] 
[00:58:21] 
[00:58:21] 
[00:58:21] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "rustdoc" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/libtest/Cargo.toml" "--no-deps" "-p" "test" "--" "-Z" "unstable-options" "--generate-redirect-pages"
[00:58:21] 
[00:58:21] 
[00:58:21] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap doc
[00:58:21] Build completed unsuccessfully in 0:05:53
[00:58:21] Build completed unsuccessfully in 0:05:53
[00:58:21] Makefile:18: recipe for target 'all' failed
[00:58:21] make: *** [all] Error 1
The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:000c11ba
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
Thu Jan 31 00:03:11 UTC 2019
---
travis_time:end:0618df37:start=1548892992660187458,finish=1548892992665774158,duration=5586700
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:10e47f39
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:03279194
travis_time:start:03279194
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:00740f05
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-01-31 10:15 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/174327230) ([raw log](https://api.travis-ci.com/v3/job/174327230/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:0ab05926:start=1548929256641362155,finish=1548929369322863662,duration=112681501507
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-6.0
---
[00:02:12]    Compiling bootstrap v0.0.0 (/checkout/src/bootstrap)
[00:02:12] error: expected item, found `*`
[00:02:12]  --> src/bootstrap/doc.rs:1:1
[00:02:12]   |
[00:02:12] 1 | *1;2802;0c//! Documentation generation for rustbuilder.
[00:02:12]   | ^ expected item
[00:02:12] error: aborting due to previous error
[00:02:12] 
[00:02:12] error: Could not compile `bootstrap`.
[00:02:12] 
---
[00:02:14]    Compiling bootstrap v0.0.0 (/checkout/src/bootstrap)
[00:02:14] error: expected item, found `*`
[00:02:14]  --> src/bootstrap/doc.rs:1:1
[00:02:14]   |
[00:02:14] 1 | *1;2802;0c//! Documentation generation for rustbuilder.
[00:02:14]   | ^ expected item
[00:02:14] error: aborting due to previous error
[00:02:14] 
[00:02:14] error: Could not compile `bootstrap`.
[00:02:14] 
---
[00:02:16]    Compiling bootstrap v0.0.0 (/checkout/src/bootstrap)
[00:02:16] error: expected item, found `*`
[00:02:16]  --> src/bootstrap/doc.rs:1:1
[00:02:16]   |
[00:02:16] 1 | *1;2802;0c//! Documentation generation for rustbuilder.
[00:02:16]   | ^ expected item
[00:02:16] error: aborting due to previous error
[00:02:16] 
[00:02:16] error: Could not compile `bootstrap`.
[00:02:16] 
---
[00:02:20]    Compiling bootstrap v0.0.0 (/checkout/src/bootstrap)
[00:02:20] error: expected item, found `*`
[00:02:20]  --> src/bootstrap/doc.rs:1:1
[00:02:20]   |
[00:02:20] 1 | *1;2802;0c//! Documentation generation for rustbuilder.
[00:02:20]   | ^ expected item
[00:02:20] error: aborting due to previous error
[00:02:20] 
[00:02:20] error: Could not compile `bootstrap`.
[00:02:20] 
---
[00:02:24]    Compiling bootstrap v0.0.0 (/checkout/src/bootstrap)
[00:02:24] error: expected item, found `*`
[00:02:24]  --> src/bootstrap/doc.rs:1:1
[00:02:24]   |
[00:02:24] 1 | *1;2802;0c//! Documentation generation for rustbuilder.
[00:02:24]   | ^ expected item
[00:02:24] error: aborting due to previous error
[00:02:24] 
[00:02:24] error: Could not compile `bootstrap`.
[00:02:24] 
---
travis_time:end:03fd7dfa:start=1548929524379909908,finish=1548929524385903908,duration=5994000
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:24091668
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:24f76470
travis_time:start:24f76470
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:0077981e
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-01-31 11:56 UTC, GuillaumeGomez commented on src/bootstrap/doc.rs
> +        let mut cargo = builder.cargo(compiler, Mode::Test, target, "rustdoc");
I didn't know that. Thanks a lot for the info!

2019-01-31 12:41 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/174358405) ([raw log](https://api.travis-ci.com/v3/job/174358405/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:19743168:start=1548937996145548201,finish=1548938106431457840,duration=110285909639
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-6.0
---
[00:05:44]   --> src/bootstrap/bin/rustdoc.rs:5:9
[00:05:44]    |
[00:05:44] 5  | #![deny(warnings)]
[00:05:44]    |         ^^^^^^^^
[00:05:44]    = note: #[deny(unused_assignments)] implied by #[deny(warnings)]
[00:05:44]    = help: maybe it is overwritten before being read?
[00:05:44] error: aborting due to previous error
[00:05:44] 
[00:05:44] error: Could not compile `bootstrap`.
[00:05:44] warning: build failed, waiting for other jobs to finish...
---
[00:05:48]   --> src/bootstrap/bin/rustdoc.rs:5:9
[00:05:48]    |
[00:05:48] 5  | #![deny(warnings)]
[00:05:48]    |         ^^^^^^^^
[00:05:48]    = note: #[deny(unused_assignments)] implied by #[deny(warnings)]
[00:05:48]    = help: maybe it is overwritten before being read?
[00:05:48] error: aborting due to previous error
[00:05:48] 
[00:05:48] error: Could not compile `bootstrap`.
[00:05:48] warning: build failed, waiting for other jobs to finish...
---
[00:05:53]   --> src/bootstrap/bin/rustdoc.rs:5:9
[00:05:53]    |
[00:05:53] 5  | #![deny(warnings)]
[00:05:53]    |         ^^^^^^^^
[00:05:53]    = note: #[deny(unused_assignments)] implied by #[deny(warnings)]
[00:05:53]    = help: maybe it is overwritten before being read?
[00:05:53] error: aborting due to previous error
[00:05:53] 
[00:05:53] error: Could not compile `bootstrap`.
[00:05:53] 
---
[00:05:57]   --> src/bootstrap/bin/rustdoc.rs:5:9
[00:05:57]    |
[00:05:57] 5  | #![deny(warnings)]
[00:05:57]    |         ^^^^^^^^
[00:05:57]    = note: #[deny(unused_assignments)] implied by #[deny(warnings)]
[00:05:57]    = help: maybe it is overwritten before being read?
[00:05:57] error: aborting due to previous error
[00:05:57] 
[00:05:57] error: Could not compile `bootstrap`.
[00:05:57] 
---
[00:06:01]   --> src/bootstrap/bin/rustdoc.rs:5:9
[00:06:01]    |
[00:06:01] 5  | #![deny(warnings)]
[00:06:01]    |         ^^^^^^^^
[00:06:01]    = note: #[deny(unused_assignments)] implied by #[deny(warnings)]
[00:06:01]    = help: maybe it is overwritten before being read?
[00:06:01] error: aborting due to previous error
[00:06:01] 
[00:06:01] error: Could not compile `bootstrap`.
[00:06:01] 
---
travis_fold:end:after_failure.1
travis_fold:start:after_failure.2
travis_time:start:038e7382
$ ls -lat $HOME/Library/Logs/DiagnosticReports/
/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:15ce429a
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-01-31 15:45 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/174401881) ([raw log](https://api.travis-ci.com/v3/job/174401881/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:1a843158:start=1548948680019938579,finish=1548948829808766440,duration=149788827861
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-6.0
---
[00:03:37]   --> src/bootstrap/bin/rustdoc.rs:5:9
[00:03:37]    |
[00:03:37] 5  | #![deny(warnings)]
[00:03:37]    |         ^^^^^^^^
[00:03:37]    = note: #[deny(unused_assignments)] implied by #[deny(warnings)]
[00:03:37]    = help: maybe it is overwritten before being read?
[00:03:37] error: aborting due to previous error
[00:03:37] 
[00:03:37] error: Could not compile `bootstrap`.
[00:03:37] warning: build failed, waiting for other jobs to finish...
---
[00:03:42]   --> src/bootstrap/bin/rustdoc.rs:5:9
[00:03:42]    |
[00:03:42] 5  | #![deny(warnings)]
[00:03:42]    |         ^^^^^^^^
[00:03:42]    = note: #[deny(unused_assignments)] implied by #[deny(warnings)]
[00:03:42]    = help: maybe it is overwritten before being read?
[00:03:42] error: aborting due to previous error
[00:03:42] 
[00:03:42] error: Could not compile `bootstrap`.
[00:03:42] warning: build failed, waiting for other jobs to finish...
---
[00:03:47]   --> src/bootstrap/bin/rustdoc.rs:5:9
[00:03:47]    |
[00:03:47] 5  | #![deny(warnings)]
[00:03:47]    |         ^^^^^^^^
[00:03:47]    = note: #[deny(unused_assignments)] implied by #[deny(warnings)]
[00:03:47]    = help: maybe it is overwritten before being read?
[00:03:47] error: aborting due to previous error
[00:03:47] 
[00:03:47] error: Could not compile `bootstrap`.
[00:03:47] 
---
[00:03:50]   --> src/bootstrap/bin/rustdoc.rs:5:9
[00:03:50]    |
[00:03:50] 5  | #![deny(warnings)]
[00:03:50]    |         ^^^^^^^^
[00:03:50]    = note: #[deny(unused_assignments)] implied by #[deny(warnings)]
[00:03:50]    = help: maybe it is overwritten before being read?
[00:03:50] error: aborting due to previous error
[00:03:50] 
[00:03:51] error: Could not compile `bootstrap`.
[00:03:51] 
---
[00:03:55]   --> src/bootstrap/bin/rustdoc.rs:5:9
[00:03:55]    |
[00:03:55] 5  | #![deny(warnings)]
[00:03:55]    |         ^^^^^^^^
[00:03:55]    = note: #[deny(unused_assignments)] implied by #[deny(warnings)]
[00:03:55]    = help: maybe it is overwritten before being read?
[00:03:55] error: aborting due to previous error
[00:03:55] 
[00:03:55] error: Could not compile `bootstrap`.
[00:03:55] 
---
travis_time:end:332c628d:start=1548949077156308382,finish=1548949077162488668,duration=6180286
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:1cbc46e0
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:027e24e8
travis_time:start:027e24e8
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:050f6bda
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-01-31 17:18 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/174423961) ([raw log](https://api.travis-ci.com/v3/job/174423961/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:000797a0:start=1548950965202139877,finish=1548951137597882785,duration=172395742908
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-6.0
---
[01:05:43] 
[01:05:43] error: Could not document `test`.
[01:05:43] 
[01:05:43] Caused by:
[01:05:43]   process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustdoc --crate-name test src/libtest/lib.rs --target x86_64-unknown-linux-gnu -o /checkout/obj/build/x86_64-unknown-linux-gnu/stage1-test/x86_64-unknown-linux-gnu/doc -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-test/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-test/release/deps --extern getopts=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-test/x86_64-unknown-linux-gnu/release/deps/libgetopts-2cd31f015e79e3a8.rmeta --extern proc_macro=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-test/x86_64-unknown-linux-gnu/release/deps/libproc_macro-9b2503eb72968b11.rmeta --extern term=/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-test/x86_64-unknown-linux-gnu/release/deps/libterm-0bd89f567a02c34d.rmeta` (exit code: 1)
[01:05:43] 
[01:05:43] 
[01:05:43] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "doc" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/libtest/Cargo.toml" "--no-deps" "-p" "test"
[01:05:43] 
[01:05:43] 
[01:05:43] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap doc
[01:05:43] Build completed unsuccessfully in 0:06:08
[01:05:43] Build completed unsuccessfully in 0:06:08
[01:05:43] make: *** [all] Error 1
[01:05:43] Makefile:18: recipe for target 'all' failed
2390004 ./obj
2389964 ./obj/build
1722116 ./obj/build/x86_64-unknown-linux-gnu
1345024 ./src
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-02-01 09:13 UTC, GuillaumeGomez commented
Finally successful!

2019-02-07 11:12 UTC, QuietMisdreavus commented
r? @ollie27

2019-02-08 18:20 UTC, ollie27 requested changes
Apart from the removal of the macro redirects this looks good.

2019-02-08 23:29 UTC, GuillaumeGomez commented on src/librustdoc/html/render.rs
> -                if item_type == ItemType::Macro {
My bad, understood it the other way for some reason. Fixing it!

2019-02-09 00:13 UTC, GuillaumeGomez commented
Updated.

2019-02-09 01:32 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/176497158) ([raw log](https://api.travis-ci.com/v3/job/176497158/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:2a79020a:start=1549671204548580455,finish=1549671304498115103,duration=99949534648
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-6.0
---
travis_time:start:test_debuginfo
Check compiletest suite=debuginfo mode=debuginfo-both (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:09:38] 
[01:09:38] running 119 tests
[01:10:02] .iiiii...i.....i..i...i..i.i..i.ii...i.....i..i....i..........iiii..........i...ii...i.......ii.i.i. 100/119
[01:10:06] i......iii.i.....ii
[01:10:06] 
[01:10:06]  finished in 28.888
[01:10:06] travis_fold:end:test_debuginfo

---
[01:16:45] failures:
[01:16:45] 
[01:16:45] ---- [rustdoc] rustdoc/without-redirect.rs stdout ----
[01:16:45] 
[01:16:45] error: htmldocck failed!
[01:16:45] status: exit code: 1
[01:16:45] command: "/usr/bin/python2.7" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/without-redirect" "/checkout/src/test/rustdoc/without-redirect.rs"
[01:16:45] ------------------------------------------
[01:16:45] 
[01:16:45] ------------------------------------------
[01:16:45] stderr:
[01:16:45] stderr:
[01:16:45] ------------------------------------------
[01:16:45] 4: @!has check failed
[01:16:45]  // @!has foo/macro.bar!.html
[01:16:45] Encountered 1 errors
[01:16:45] 
[01:16:45] ------------------------------------------
[01:16:45] 
---
[01:16:45] 
[01:16:45] thread 'main' panicked at 'Some tests failed', src/tools/compiletest/src/main.rs:502:22
[01:16:45] 
[01:16:45] 
[01:16:45] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--rustdoc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc" "--src-base" "/checkout/src/test/rustdoc" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "rustdoc" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-6.0/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "6.0.0\n" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--llvm-components" "" "--llvm-cxxflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always"
[01:16:45] 
[01:16:45] 
[01:16:45] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:16:45] Build completed unsuccessfully in 0:18:39
[01:16:45] Build completed unsuccessfully in 0:18:39
[01:16:45] make: *** [check] Error 1
[01:16:45] Makefile:48: recipe for target 'check' failed
The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:34fbdff8
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
Sat Feb  9 01:31:58 UTC 2019
---
travis_time:end:002aa29c:start=1549675920537299506,finish=1549675920542180779,duration=4881273
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:014df626
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:02035740
travis_time:start:02035740
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:2055300c
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-02-09 20:04 UTC, GuillaumeGomez commented
Fixed CI as well.

2019-02-13 21:39 UTC, GuillaumeGomez commented
Ping @ollie27

2019-02-14 16:16 UTC, ollie27 commented
@bors r+

2019-02-15 19:24 UTC, rust-highfive commented
Your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/178190194) ([raw log](https://api.travis-ci.com/v3/job/178190194/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain

```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-02-15 20:22 UTC, pietroalbini commented
@bors retry -- apparently we can't clone the repo anymore on macOS

2019-02-15 22:01 UTC, GuillaumeGomez commented
Funny times I guess for the infra team. :p

2019-02-17 10:14 UTC, merged