Add specific feature gate error for const-unstable features
rust-lang/rust pull request #58196
Opened 2019-02-05 20:29 UTC by varkor

Before:
```
error: `impl Trait` in const fn is unstable
 --> src/lib.rs:7:19
  |
7 | const fn foo() -> impl T {
  |                   ^^^^^^

error: aborting due to previous error
```

After:
```
error[E0723]: `impl Trait` in const fn is unstable (see issue #57563)
 --> src/lib.rs:7:19
  |
7 | const fn foo() -> impl T {
  |                   ^^^^^^
  = help: add #![feature(const_fn)] to the crate attributes to enable

error: aborting due to previous error
```

This improves the situation with https://github.com/rust-lang/rust/issues/57563. Fixes https://github.com/rust-lang/rust/issues/57544. Fixes https://github.com/rust-lang/rust/issues/54469.

r? @oli-obk

2019-02-05 20:58 UTC, oli-obk requested changes
r=me with a documentation nit

2019-02-05 20:58 UTC, oli-obk commented on src/librustc_mir/diagnostics.rs
> +const fn foo() -> impl T { // error: `impl Trait` in const fn is unstable
```suggestion
const fn foo() -> impl T {
```

2019-02-05 21:03 UTC, varkor commented
@bors r=oli-obk

2019-02-05 22:44 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/175537913) ([raw log](https://api.travis-ci.com/v3/job/175537913/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:2ccbb0e1:start=1549400790641426547,finish=1549400791511527207,duration=870100660
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
Setting environment variables from .travis.yml
$ export IMAGE=x86_64-gnu-llvm-6.0
---
travis_time:start:test_debuginfo
Check compiletest suite=debuginfo mode=debuginfo-both (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:12:25] 
[01:12:25] running 119 tests
[01:12:50] .iiiii...i.....i..i...i..i.i..i.ii...i.....i..i....i..........iiii..........i...ii...i.......ii.i.i. 100/119
[01:12:54] i......iii.i.....ii
[01:12:54] 
[01:12:54]  finished in 29.036
[01:12:54] travis_fold:end:test_debuginfo

---
[01:37:55] 
[01:37:55] failures:
[01:37:55] 
[01:37:55] ---- /checkout/obj/build/x86_64-unknown-linux-gnu/test/error-index.md - Rust_Compiler_Error_Index::E0723 (line 11531) stdout ----
[01:37:55] thread '/checkout/obj/build/x86_64-unknown-linux-gnu/test/error-index.md - Rust_Compiler_Error_Index::E0723 (line 11531)' panicked at 'test compiled while it wasn't supposed to', src/librustdoc/test.rs:344:13
[01:37:55] 
[01:37:55] 
[01:37:55] failures:
[01:37:55]     /checkout/obj/build/x86_64-unknown-linux-gnu/test/error-index.md - Rust_Compiler_Error_Index::E0723 (line 11531)
---
[01:37:55] 
[01:37:55] 
[01:37:55] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:37:55] Build completed unsuccessfully in 0:36:45
[01:37:55] make: *** [check] Error 1
[01:37:55] Makefile:48: recipe for target 'check' failed
The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:1649cbfa
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
Tue Feb  5 22:44:38 UTC 2019
---
travis_time:end:020e8a84:start=1549406679593073818,finish=1549406679642674369,duration=49600551
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:109671ec
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:165b1336
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-02-06 08:23 UTC, oli-obk approved these changes

2019-02-07 14:39 UTC, kennytm commented
@bors r=oli-obk

Please tell bors about the re-approval after a force-push.

2019-02-13 03:34 UTC, Centril commented
Failed in rollup (https://github.com/rust-lang/rust/pull/58413#issuecomment-463042559), @bors r- ; to fix the issue, try `--bless --compare-mode=nll`.

2019-02-13 03:34 UTC, Centril commented
@bors r-

2019-02-14 15:47 UTC, varkor commented
@bors r=oli-obk

2019-02-17 10:14 UTC, merged