[WIP] librustc_mir => 2018
rust-lang/rust pull request #58265
Opened 2019-02-07 12:24 UTC by taiki-e

Transitions `librustc_mir` to Rust 2018; cc #58099

TODO: elided_lifetimes_in_paths

r? @Centril

2019-02-07 14:16 UTC, matthewjasper commented
r? @matthewjasper

2019-02-08 10:14 UTC, scottmcm commented on src/librustc_mir/lib.rs
>  // replace this with real try blocks.
I'm excited to use real `try` blocks now that you've done this; if you'd like to remove this macro as part of this change that'd be awesome.  (Definitely doesn't need to be part of this, though, so feel free not to do it if you'd rather.)

2019-02-08 10:34 UTC, matthewjasper requested changes
One nit and then I think that this is good to go.

2019-02-08 10:34 UTC, matthewjasper commented on src/librustc_mir/lib.rs
> -#![feature(nll)]
Can this be kept, it gives better error messages in some cases and ensures that we can't ignore future compatibility warnings.

2019-02-08 11:15 UTC, scottmcm commented on src/librustc_mir/borrow_check/nll/mod.rs
>      };
:tada:

2019-02-08 11:16 UTC, taiki-e commented on src/librustc_mir/transform/qualify_consts.rs
> +bitflags::bitflags! {
`bitflags!` is only used here.

2019-02-08 11:37 UTC, matthewjasper approved these changes

2019-02-08 11:37 UTC, matthewjasper commented
@bors r+

2019-02-09 03:55 UTC, merged