Fix doc for rustc "-g" flag
rust-lang/rust pull request #58544
Opened 2019-02-17 18:15 UTC by TheBiggerGuy

The rustc `-g` CLI flag was miss documented to be a synonym of `-C debug-level=2` and not `-C debuglevel=2`. Also add links to the codegen docs for each synonym.

I am unsure of this will conflict with work on #52938

2019-02-17 18:16 UTC, rust-highfive commented
Some changes occurred in HTML/CSS.

cc @GuillaumeGomez

2019-02-17 18:16 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @TimNN (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2019-02-17 19:25 UTC, TimNN requested changes
One nit, otherwise LGTM.

2019-02-17 19:25 UTC, TimNN commented on src/doc/rustc/src/command-line-arguments.md
> +A synonym for `-C debuglevel=2`, for more see [here](codegen-options/index.html#debuginfo).
Looking at the output of `rustc +stable -C help`, it looks like this should actually be `debuginfo`.

2019-02-17 21:23 UTC, GuillaumeGomez commented
I don't get why I was cced in here since there are no changes in HTML/CSS/JS but whatever... Looks good to me, thanks!

@bors: r=TimNN

2019-02-17 21:30 UTC, TheBiggerGuy commented
Sorry for the first version not having the correct arg. A bit of a fail trying to fix a typo with another one.

I have just ran the full set of tests and check the doc links work locally.

The only question I have is if ```debug-level``` or ```debuglevel``` where ever correct? If so maybe a sentence in the doc letting people know of the rename.

2019-02-17 23:49 UTC, TheBiggerGuy commented
My quick check of the code found that LLVM uses `debug-level` and rustc uses `debuginfo`:

rustc
------
https://github.com/rust-lang/rust/blob/f47ec2ad5b6887b3d400aee49e2294bd27733d18/src/librustc/session/config.rs#L1684-L1685

llvm
-----
https://github.com/rust-lang/llvm-project/blame/73a75d35b9776d56160fa3200aca4a970ae49b60/llvm/docs/CommandLine.rst#L420-L421

2019-02-18 23:57 UTC, Mark-Simulacrum commented
@bors rollup

2019-02-20 13:00 UTC, merged