Prevent cache issues on version updates
rust-lang/rust pull request #58848
Opened 2019-03-01 16:04 UTC by GuillaumeGomez

Fixes #58827.

cc @rust-lang/infra

2019-03-01 16:04 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2019-03-04 19:36 UTC, petrochenkov commented
r? @Mark-Simulacrum

2019-03-04 21:17 UTC, Mark-Simulacrum commented
I presume you'll want to beta backport as well, but I'll leave that to the rustdoc and/or docs team to decide.

@bors r+

2019-03-06 20:23 UTC, QuietMisdreavus commented
Beta-nominating since this fixes an issue we've had with docs version upgrades on the site for ages. @rust-lang/docs, would anyone like to approve the backport?

2019-03-11 17:49 UTC, ollie27 commented
@bors r-

This caused #59081 to fail because rustdoc-js is still looking for `main.js` but now it's named something like `main1.35.0.js`.

2019-03-12 06:49 UTC, GuillaumeGomez commented
It needs to be merged after #58330.

2019-03-12 20:30 UTC, GuillaumeGomez commented
#58330 has been merged, therefore this one should work now.

@bors: r=MarkSimulacrum

2019-03-12 21:39 UTC, ollie27 requested changes
`--resource-suffix` needs to be passed to rustdoc when building the `test` and `proc_macro` crates as well.

2019-03-12 21:39 UTC, ollie27 commented on src/bootstrap/doc.rs
> +        .arg("--resource-suffix").arg(crate::channel::CFG_RELEASE_NUM)
`--resource-suffix` doesn't do anything for stand-alone markdown files.

2019-03-12 21:39 UTC, ollie27 commented on src/bootstrap/doc.rs
> +               .arg("--resource-suffix").arg(crate::channel::CFG_RELEASE_NUM)
Again, `--resource-suffix` doesn't do anything for stand-alone markdown files.

2019-03-12 23:21 UTC, GuillaumeGomez commented
@bors: r-

2019-03-12 23:32 UTC, GuillaumeGomez commented
Updated.

r? @ollie27

2019-03-13 16:00 UTC, ollie27 commented on src/bootstrap/doc.rs
> +             .env("RUSTDOC_RESOURCE_SUFFIX", crate::channel::CFG_RELEASE_NUM)
`src/bootstrap/bin/rustdoc.rs` also needs to read this environment variable.

2019-03-25 12:35 UTC, Dylan-DPC commented
ping from triage @GuillaumeGomez any updates?

2019-03-25 20:16 UTC, GuillaumeGomez commented
I need to apply @ollie27's comments.

2019-03-25 21:01 UTC, GuillaumeGomez commented
And updated!

2019-03-25 22:54 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/187624653) ([raw log](https://api.travis-ci.com/v3/job/187624653/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:1b72875c:start=1553547769377239303,finish=1553547868635908936,duration=99258669633
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
Setting environment variables from .travis.yml
---
travis_time:start:test_assembly
Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:21:58] 
[01:21:58] running 9 tests
[01:21:58] iiiiiiiii
[01:21:58] 
[01:21:58]  finished in 0.163
[01:21:58] travis_fold:end:test_assembly

---
travis_time:start:test_debuginfo
Check compiletest suite=debuginfo mode=debuginfo-both (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:22:15] 
[01:22:15] running 120 tests
[01:22:43] .iiiii...i.....i..i...i..i.i...i.ii...i.....i..i....i..........iiii..........i...ii...i.......ii.i.i 100/120
[01:22:48] .i......iii.i.....ii
[01:22:48] 
[01:22:48]  finished in 33.724
[01:22:48] travis_fold:end:test_debuginfo

---
[01:49:19] travis_fold:end:stage0-linkchecker

[01:49:19] travis_time:end:stage0-linkchecker:start=1553554435560428855,finish=1553554437808548858,duration=2248120003

[01:49:31] error-index.html:7: broken link - light.css
[01:49:31] thread 'main' panicked at 'found some broken links', src/tools/linkchecker/main.rs:41:9
[01:49:31] 
[01:49:31] 
[01:49:31] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/linkchecker" "/checkout/obj/build/x86_64-unknown-linux-gnu/doc"
[01:49:31] expected success, got: exit code: 101
[01:49:31] expected success, got: exit code: 101
[01:49:31] 
[01:49:31] 
[01:49:31] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:49:31] Build completed unsuccessfully in 0:40:11
[01:49:31] make: *** [check] Error 1
[01:49:31] Makefile:48: recipe for target 'check' failed
The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:114df461
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
Mon Mar 25 22:54:09 UTC 2019
---
travis_time:end:01421079:start=1553554452314884963,finish=1553554452320145188,duration=5260225
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0cdf8e94
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:004590ea
travis_time:start:004590ea
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:24edb5d0
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-03-25 23:59 UTC, Mark-Simulacrum commented
@bors r+

2019-03-26 00:00 UTC, Mark-Simulacrum commented
Er, just saw that Travis is failing.

@bors r-

2019-03-26 09:00 UTC, GuillaumeGomez commented
Yep, an issue with a theme file apparently? I'll check this evening.

2019-03-27 20:25 UTC, GuillaumeGomez commented
Ok, it was the index generator generation which failed because the theme files didn't receive the suffix. Fixed now that we can move on!

@bors: r=Mark-Simulacrum,ollie27

2019-03-28 12:12 UTC, merged

2019-04-05 15:50 UTC, pietroalbini commented
Ping @rust-lang/docs @rust-lang/rustdoc this needs to be approved for beta backport.

2019-04-05 18:38 UTC, GuillaumeGomez commented
I approve for it. cc @QuietMisdreavus

2019-04-07 20:42 UTC, pietroalbini commented
This was removed from the backport since it caused a build failure.

2019-04-07 22:23 UTC, ollie27 commented
This will need at least 37ab3dc5b3560792ae4eab0521e0c08bbbdd95d8 to be backported as well. That commit got attached to the wrong PR: #58330.