Standardize `Range*` documentation
rust-lang/rust pull request #59057
Opened 2019-03-10 06:05 UTC by czipperz

This updates the final example in the documentation for the types
`Range`, `RangeFrom`, `RangeFull`, `RangeInclusive`, `RangeTo`,
`RangeToInclusive`.

2019-03-10 06:05 UTC, rust-highfive commented
r? @shepmaster

(rust_highfive has picked a reviewer for you, use r? to override)

2019-03-11 18:13 UTC, shepmaster requested changes

2019-03-11 18:13 UTC, shepmaster commented on src/libcore/ops/range.rs
> +/// assert_eq!(arr[1..=3], [  1,2,3  ]);  // Range
This is not `Range`.

2019-03-12 04:08 UTC, czipperz commented
@shepmaster Fixed that.  Thanks for the catch

2019-03-13 00:35 UTC, shepmaster commented
@bors r+ rollup

2019-03-13 00:35 UTC, shepmaster commented
Thanks!

2019-03-13 00:35 UTC, shepmaster approved these changes

2019-03-13 06:19 UTC, merged