Make `ptr::eq` documentation mention smart-pointer behavior
rust-lang/rust pull request #59390
Opened 2019-03-24 01:27 UTC by czipperz

Resolves #59214

2019-03-24 01:27 UTC, rust-highfive commented
r? @kimundi

(rust_highfive has picked a reviewer for you, use r? to override)

2019-03-25 11:44 UTC, CryZe commented
I'm pretty sure this is incorrect. The difference is that *fat* pointers (not smart pointers) compare their metadata in addition to the pointer address.

2019-03-25 14:18 UTC, steveklabnik commented
Yes, I agree with @cryze

2019-03-25 17:44 UTC, czipperz commented
What do you mean by a fat pointer?  Why is smart pointer wrong?

The three example smart pointers I listed compare by value. They use compare by address only as an optimization when the type implements Eq according to reading the source code.

2019-03-25 17:55 UTC, czipperz commented
Googled fat pointers:

* slices with length
* traits with vtables

2019-03-25 17:56 UTC, czipperz commented
KK so the issue is wrong. I'll fix this. Thanks guys

2019-03-25 21:23 UTC, czipperz commented
Should we be adding a method that compares pointers by purely memory address without comparing metadata?

2019-03-26 19:54 UTC, czipperz commented
@steveklabnik

2019-03-27 13:47 UTC, steveklabnik commented
@bors: r+ rollup

thank you!

2019-03-27 13:55 UTC, Centril requested changes
We shouldn't be using `Trait` instead of `dyn Trait` anymore in the standard library.

2019-03-27 13:55 UTC, Centril commented on src/libcore/ptr.rs
> +///     // Pointers are equal address
```suggestion
///     // Pointers have equal addresses.
```

2019-03-27 13:55 UTC, Centril commented on src/libcore/ptr.rs
> +///     // Objects have equal addresses, but `Trait` has different implementations
```suggestion
///     // Objects have equal addresses, but `Trait` has different implementations.
```

2019-03-27 13:55 UTC, Centril commented on src/libcore/ptr.rs
> +///     // Converting the reference to a `*const u8` compares by address
```suggestion
///     // Converting the reference to a `*const u8` compares by address.
```

2019-03-27 13:55 UTC, Centril commented on src/libcore/ptr.rs
> +///         &wrapper as &Trait,
```suggestion
///         &wrapper as &dyn Trait,
```

2019-03-27 13:55 UTC, Centril commented on src/libcore/ptr.rs
> +///         &wrapper.member as &Trait,
```suggestion
///         &wrapper.member as &dyn Trait,
```

2019-03-27 13:55 UTC, Centril commented on src/libcore/ptr.rs
> +///         &wrapper as &Trait as *const Trait,
```suggestion
///         &wrapper as &dyn Trait as *const dyn Trait,
```

2019-03-27 13:55 UTC, Centril commented on src/libcore/ptr.rs
> +///         &wrapper.member as &Trait as *const Trait,
```suggestion
///         &wrapper.member as &dyn Trait as *const dyn Trait,
```

2019-03-27 13:55 UTC, Centril commented on src/libcore/ptr.rs
> +///         &wrapper as &Trait as *const Trait as *const u8,
```suggestion
///         &wrapper as &dyn Trait as *const dyn Trait as *const u8,
```

2019-03-27 13:55 UTC, Centril commented on src/libcore/ptr.rs
> +///         &wrapper.member as &Trait as *const Trait as *const u8,
```suggestion
///         &wrapper.member as &dyn Trait as *const dyn Trait as *const u8,
```

2019-03-27 13:55 UTC, Centril commented
@bors r-

2019-03-27 13:55 UTC, Centril commented
r? @steveklabnik

2019-03-27 15:43 UTC, czipperz commented
KK @Centril  done

2019-03-27 15:50 UTC, Centril approved these changes

2019-03-27 15:51 UTC, Centril commented
r=me,steveklabnik with green travis

2019-03-27 20:44 UTC, czipperz commented
@Centril @steveklabnik

2019-03-27 20:47 UTC, Centril commented
@bors r=Centril,steveklabnik rollup

2019-03-28 05:44 UTC, merged