Don't generate minification variables if not needed
rust-lang/rust pull request #59400
Opened 2019-03-24 16:21 UTC by GuillaumeGomez

Follow up of #59158 and #59157.

r? @QuietMisdreavus 

cc @jdm

2019-03-26 14:35 UTC, QuietMisdreavus commented
I wonder if we can make a test for this. Can we use `rustdoc` tests to look at the search index javascript? Since the initial minification variables are always going to have the same line to initialize them, we could look for something like that. I think we can also use an `auxiliary` crate to test what happens when a dependency has minified the search index but a downstream crate has disabled it - [from what i can tell](https://github.com/rust-lang/rust/blob/54479c624cc24bb852291d83e11cc19389dcb21b/src/tools/compiletest/src/runtest.rs#L1432-L1434), auxiliary doc builds use the properties from the aux file itself instead of the main test.

2019-03-26 21:25 UTC, GuillaumeGomez commented
I could write a test which would simply load the searchIndex file and if an error occurs, it means the generation failed. However, this would require a new test-suite since we need to build using `--disable-minification`.

2019-03-27 13:53 UTC, QuietMisdreavus commented
I was thinking something even simpler, doing a substring search using a `@has` rule in a regular rustdoc test. We can pass the `--disable-minification` flag in those just fine - a `compile-flags:--disable-minification -Z unstable-options` rule in the test should suffice.

2019-03-27 15:27 UTC, GuillaumeGomez commented
Such a test would completely fail to trigger when a minification would appear. :-/

2019-04-09 19:37 UTC, ollie27 commented
Is this added complexity worth it to save a few bytes in the none minified `search-index.js`?

2019-04-10 07:59 UTC, GuillaumeGomez commented
This is a simple change which generates less things. For me, it's totally worth it, although we can't really test it (or we'll need to create a whole new test suite, which I'd prefer to avoid).

2019-05-18 14:13 UTC, Mark-Simulacrum commented
@QuietMisdreavus Could we get a review/decision here either way?

I'm personally also somewhat inclined to say that we shouldn't do this as the 10-20 bytes we're saving aren't really worth the complexity introduced here in my opinion.

2019-05-18 22:37 UTC, GuillaumeGomez commented
Easy to say when you're not the one debugging the minified JS. :p

2019-05-18 22:40 UTC, GuillaumeGomez commented
Oh also, it fixes a bug currently present in the code, it doesn't add a new feature. Therefore it seems pretty worth it (but my opinion is completely biased in here since I use this feature quite heavily).

2019-05-18 23:13 UTC, Mark-Simulacrum commented
Ah, I was not aware that this fixes a bug -- I presumed that the variables don't hurt if they're unused, but I guess that's not true.

2019-05-19 08:58 UTC, GuillaumeGomez commented
By default, people don't have this bug since it needs a nightly-only option to be enabled. So indeed, it doesn't hurt to have unused variables if they're really not used. However, in here in some cases, the code references to them.

2019-06-03 12:50 UTC, Dylan-DPC commented
@bors: r+

2019-06-03 16:56 UTC, ollie27 requested changes

2019-06-03 16:56 UTC, ollie27 commented on src/librustdoc/html/render.rs
> +                    is_minified = true;
This is dead code. The above:

```rust
if !line.starts_with(key) || line.starts_with(&format!(r#"{}["{}"]"#, key, krate)) {
    continue;
}
```

means that `line.starts_with(MINIFIED_VARIABLES)` can never be true. This means that the minification variables are missing if the last call to rustdoc used `--disable-minification` but previous ones didn't.

2019-06-03 16:58 UTC, ollie27 commented
@bors r-

Again I don't think this added complexity is worth it. Especially when it doesn't even work and has no tests.

2019-07-22 12:00 UTC, joelpalmer commented
Hi @GuillaumeGomez this is a ping from Triage. Please post an update on this PR at your earliest convenience.

2019-07-23 21:08 UTC, GuillaumeGomez commented
@ollie27 is against it so I guess I'll just close it...

2019-07-23 21:08 UTC, closed without merging