rustc_target: factor out common fields of non-Single Variants.
rust-lang/rust pull request #59519
Opened 2019-03-29 07:37 UTC by eddyb

@tmandry and I were discussing ways to generalize the current variants/discriminant layout to allow more fields in the "`enum`" (or another multi-variant types, such as potentially generator state, in the future), shared by all variants, than just the tag/niche discriminant.

This refactor should make it easier to extend multi-variant layouts, as nothing is duplicating anymore between "tagged enums" and "niche-filling enums".

r? @oli-obk

2019-03-29 09:12 UTC, oli-obk requested changes
r=me with `tag` access deduplicated

2019-03-29 19:21 UTC, eddyb commented on src/librustc_codegen_llvm/debuginfo/metadata.rs
> +        (&layout::Abi::Scalar(_), &layout::Variants::Multiple {
I disagree, these are orthogonal. I didn't want to rewrite too much code, but arguably everything should match on `Variants` and then match on `DiscriminantKind` inside the `Multiple` case.

That way, code common to both niches and tags can be reused. Adding a `.tag()` method runs counter to that.

2019-03-31 09:28 UTC, oli-obk commented on src/librustc_codegen_llvm/debuginfo/metadata.rs
> +        (&layout::Abi::Scalar(_), &layout::Variants::Multiple {
I get that, but the three cases that I saw here all are very "tagged" special and can't share code with the niche part. Or do you see any additional refactorings that can be done here in the future?

2019-03-31 15:35 UTC, eddyb commented on src/librustc_codegen_llvm/debuginfo/metadata.rs
> +        (&layout::Abi::Scalar(_), &layout::Variants::Multiple {
Ah this is the special case for C-like enums. Either way, I don't see a point in catering to this pattern, but I'll leave comments regarding the possibility of refactoring on the other 2 cases.

2019-03-31 15:36 UTC, eddyb commented on src/librustc_codegen_llvm/debuginfo/metadata.rs
> +            layout::Variants::Multiple {
This is in `if use_enum_fallback(cx)` and will eventually be removed when we stop supporting LLVM versions that predate the addition of variant debuginfo.

2019-03-31 15:37 UTC, eddyb commented on src/librustc/ty/layout.rs
> +                    DiscriminantKind::Tag => Some(discr.value.size(self)),
This whole thing needs to be rewritten to pretty-print layouts losslessly (or we can just use `{:#?}`, heh).

2019-03-31 15:42 UTC, oli-obk commented
@bors r+

2019-03-31 20:27 UTC, merged