Updated RELEASES.md for 1.34.0
rust-lang/rust pull request #59599
Opened 2019-04-01 08:54 UTC by XAMPPRocky

[Rendered](https://github.com/XAMPPRocky/rust/blob/master/RELEASES.md)

This also corrects an omission in the previous 1.33.0 release.

r? @Mark-Simulacrum

cc @rust-lang/release

2019-04-01 09:06 UTC, Centril requested changes
Looks good overall.

2019-04-01 09:06 UTC, Centril commented on RELEASES.md
> +  but had no effect.
```suggestion
```

2019-04-01 09:06 UTC, Centril commented on RELEASES.md
> +- [You can now write `extern crate self as foo;`][57407] to import the your
```suggestion
- [You can now write `extern crate self as foo;`][57407] to import your
```

2019-04-01 09:06 UTC, Centril commented on RELEASES.md
> +- [Relax Ord trait bounds have been removed on some of `BinaryHeap<T>`'s basic
```suggestion
- [`Ord` trait bounds have been removed on some of `BinaryHeap<T>`'s basic
```

2019-04-01 09:06 UTC, Centril commented on RELEASES.md
> +- [You can now publish crates which require a feature flag to compile with
```suggestion
- [You can now publish crates that require a feature flag to compile with
```

2019-04-01 09:17 UTC, Centril reviewed
Note to @steveklabnik & et. al -- I think these should be our headline items in order of importance (0. being most important) in the blog post.

2019-04-01 09:17 UTC, Centril commented on RELEASES.md
> +- [You can now use alternatives registries to crates.io.][cargo/6654]
0.

2019-04-01 09:17 UTC, Centril commented on RELEASES.md
> +  unsafe method `Command::pre_exec`.][58059]
1.

2019-04-01 09:17 UTC, Centril commented on RELEASES.md
> +- [You can now use the `?` operator in your documentation tests without manually
2.

2019-04-01 09:17 UTC, Centril commented on RELEASES.md
> +- [You can now accept token streams in `#[attr()]`,`#[attr[]]`, and
3.

2019-04-01 09:31 UTC, jonas-schievink commented on RELEASES.md
> +  `#[deprecation(note = "reason")]`. This was previously allowed as a syntax bug
Could also just say "This was previously allowed by mistake but had no effect"

2019-04-01 09:48 UTC, lzutao commented on RELEASES.md
> +Version v1.34.0 (2019-04-11)
Non consistent with 1.33.

2019-04-01 16:31 UTC, cuviper commented on RELEASES.md
> +  `#[deprecation(note = "reason")]`. This was previously allowed as a syntax bug
Also, I believe the attribute is `deprecated`, not `deprecation`.

2019-04-01 16:41 UTC, tormol commented on RELEASES.md
> +  `#[deprecation(note = "reason")]`. This was previously allowed as a syntax bug
The attribute is `deprecated`, not `deprecation`.

2019-04-01 16:42 UTC, tormol commented on RELEASES.md
> +* [`iter::successors`]
When rendered the `iter::successors` link points to the `iter::Successors` struct even though the URL below is correct.
Github's markdown renderer must be case insensitive.

2019-04-04 07:04 UTC, crlf0710 commented
Out-of-topic: Speaking of targets, i think https://forge.rust-lang.org/platform-support.html has been out of date for quite a while... targets such as uefi have never been labeled a tier, and added to the table :(

2019-04-05 15:55 UTC, pietroalbini commented
Can we get this finished up for the release?

2019-04-05 20:04 UTC, Mark-Simulacrum commented
@bors r+

Not giving priority as it landing on beta is more important -- master can wait.

2019-04-06 01:36 UTC, merged