[WIP] rust case insensitive fs support
rust-lang/rust pull request #59785
Opened 2019-04-07 22:29 UTC by GuillaumeGomez

This PR aims the support for case insensitive file systems in such cases:

```rust
pub struct FoO;
pub struct Foo;
```

I now need people to take a look and look for bugs that I'd have missed (windows' users would be very cool!).

I plan on adding the code sample above as a test but that seems a bit limited compared to the amount of code there is...

r? @QuietMisdreavus

2019-04-07 23:56 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/190998315) ([raw log](https://api.travis-ci.com/v3/job/190998315/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:1873e6f3:start=1554676253351537609,finish=1554676329159014459,duration=75807476850
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
Setting environment variables from .travis.yml
---
travis_time:start:test_assembly
Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:15:50] 
[01:15:50] running 9 tests
[01:15:50] iiiiiiiii
[01:15:50] 
[01:15:50]  finished in 0.154
[01:15:50] travis_fold:end:test_assembly

---
travis_time:start:test_debuginfo
Check compiletest suite=debuginfo mode=debuginfo-both (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:16:06] 
[01:16:06] running 121 tests
[01:16:32] .iiiii...i.....i..i...i..i.i.i..i.ii...i.....i..i....i..........iiii..........i...ii...i.......ii.i. 100/121
[01:16:37] i.i......iii.i.....ii
[01:16:37] 
[01:16:37]  finished in 30.790
[01:16:37] travis_fold:end:test_debuginfo

---
travis_time:start:test_rustdoc
Check compiletest suite=rustdoc mode=rustdoc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:20:31] 
[01:20:31] running 302 tests
[01:21:45] FFFFFFF.F.F..FF..F.FF...FF.FiFFFF..FFF...FFFFF.FFF.FFF...FFFFF.FFF.F..FFF.F.FFFFFF.F...FF.F.FF..FFF. 100/302
[01:22:47] ...F...FF.........FFFFFFFFFFFFF.F.......Fi.F.FFF.FF.F...FF.FFF.FF..F..FFF..FFF......FFF..F..F......F 200/302
[01:23:52] F..FFF.F.FF....FFF..F..FFF.......F...F.FFF....FF..FF....FFF..FFFF.FFFFFFFFFFF....FFFFFF.FF.FF..F...F 300/302
[01:23:53] F.
[01:23:53] 
[01:23:53] ---- [rustdoc] rustdoc/all.rs stdout ----
[01:23:53] 
[01:23:53] 
[01:23:53] error: htmldocck failed!
[01:23:53] status: exit code: 1
[01:23:53] command: "/usr/bin/python2.7" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/all" "/checkout/src/test/rustdoc/all.rs"
[01:23:53] ------------------------------------------
[01:23:53] 
[01:23:53] ------------------------------------------
[01:23:53] stderr:
[01:23:53] stderr:
[01:23:53] ------------------------------------------
[01:23:53] 3: @has check failed
[01:23:53]  `XPATH PATTERN` did not match
[01:23:53]  // @has foo/all.html '//a[@href="struct.Struct.html"]' 'Struct'
[01:23:53] 4: @has check failed
[01:23:53]  `XPATH PATTERN` did not match
[01:23:53]  // @has foo/all.html '//a[@href="enum.Enum.html"]' 'Enum'
[01:23:53] 5: @has check failed
[01:23:53]  `XPATH PATTERN` did not match
[01:23:53]  // @has foo/all.html '//a[@href="union.Union.html"]' 'Union'
[01:23:53] 6: @has check failed
[01:23:53]  `XPATH PATTERN` did not match
[01:23:53]  // @has foo/all.html '//a[@href="constant.CONST.html"]' 'CONST'
[01:23:53] 7: @has check failed
[01:23:53]  `XPATH PATTERN` did not match
[01:23:53]  // @has foo/all.html '//a[@href="static.STATIC.html"]' 'STATIC'
[01:23:53] 8: @has check failed
[01:23:53]  `XPATH PATTERN` did not match
[01:23:53]  // @has foo/all.html '//a[@href="fn.function.html"]' 'function'
[01:23:53] 26: @has check failed
[01:23:53]  `XPATH PATTERN` did not match
[01:23:53]  // @has foo/all.html '//a[@href="struct.ReexportedStruct.html"]' 'ReexportedStruct'
[01:23:53] Encountered 7 errors
[01:23:53] 
[01:23:53] ------------------------------------------
[01:23:53] 
[01:23:53] 
[01:23:53] thread '[rustdoc] rustdoc/all.rs' panicked at 'explicit panic', src/tools/compiletest/src/runtest.rs:3425:9
[01:23:53] note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[01:23:53] 
[01:23:53] ---- [rustdoc] rustdoc/assoc-consts-version.rs stdout ----
[01:23:53] 
[01:23:53] error: htmldocck failed!
[01:23:53] status: exit code: 1
[01:23:53] command: "/usr/bin/python2.7" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/assoc-consts-version" "/checkout/src/test/rustdoc/assoc-consts-version.rs"
[01:23:53] ------------------------------------------
[01:23:53] 
[01:23:53] ------------------------------------------
[01:23:53] stderr:
[01:23:53] stderr:
[01:23:53] ------------------------------------------
[01:23:53] 13: @has check failed
[01:23:53]  File does not exist 'foo/struct.SomeStruct.html'
[01:23:53]      // @has 'foo/struct.SomeStruct.html' '//*[@id="associatedconstant.SOME_CONST"]//div[@class="since"]' '1.1.2'
[01:23:53] Encountered 1 errors
[01:23:53] 
[01:23:53] ------------------------------------------
[01:23:53] 
[01:23:53] 
[01:23:53] thread '[rustdoc] rustdoc/assoc-consts-version.rs' panicked at 'explicit panic', src/tools/compiletest/src/runtest.rs:3425:9
[01:23:53] 
[01:23:53] ---- [rustdoc] rustdoc/assoc-item-cast.rs stdout ----
[01:23:53] 
[01:23:53] error: htmldocck failed!
[01:23:53] status: exit code: 1
[01:23:53] command: "/usr/bin/python2.7" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/assoc-item-cast" "/checkout/src/test/rustdoc/assoc-item-cast.rs"
[01:23:53] ------------------------------------------
[01:23:53] 
[01:23:53] ------------------------------------------
[01:23:53] stderr:
[01:23:53] stderr:
[01:23:53] ------------------------------------------
[01:23:53] 14: @has check failed
[01:23:53]  File does not exist 'foo/type.AsExprOf.html'
[01:23:53]  // @has foo/type.AsExprOf.html
[01:23:53] 15: @has check failed
[01:23:53]  File does not exist 'foo/type.AsExprOf.html'
[01:23:53]  // @has - '//*[@class="rust typedef"]' 'type AsExprOf<Item, Type> = <Item as AsExpression<Type>>::Expression;'
[01:23:53] Encountered 2 errors
[01:23:53] 
[01:23:53] ------------------------------------------
[01:23:53] 
[01:23:53] 
[01:23:53] thread '[rustdoc] rustdoc/assoc-item-cast.rs' panicked at 'explicit panic', src/tools/compiletest/src/runtest.rs:3425:9
[01:23:53] 
[01:23:53] ---- [rustdoc] rustdoc/assoc-consts.rs stdout ----
[01:23:53] 
[01:23:53] error: htmldocck failed!
[01:23:53] status: exit code: 1
[01:23:53] command: "/usr/bin/python2.7" "/checkout/src/etc/htmldocck.py" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/rustdoc/assoc-consts" "/checkout/src/test/rustdoc/assoc-consts.rs"
[01:23:53] ------------------------------------------
[01:23:53] 
[01:23:53] ------------------------------------------
[01:23:53] stderr:
[01:23:53] stderr:
[01:23:53] ------------------------------------------
[01:23:53] 2: @has check failed
[01:23:53]  File does not exist 'assoc_consts/trait.Foo.html'
[01:23:53]      // @has assoc_consts/trait.Foo.html '//*[@class="rust trait"]' 'const FOO: usize;'
[01:23:53] 4: @has check failed
[01:23:53]  File does not exist 'assoc_consts/trait.Foo.html'
[01:23:53]      // @has - '//*[@id="associatedconstant.FOO"]' 'const FOO: usize'
[01:23:53] 6: @has check failed
[01:23:53]  File does not exist 'assoc_consts/trait.Foo.html'
[01:23:53]      // @has - '//*[@id="associatedconstant.FOO_NO_DEFAULT"]' 'const FOO_NO_DEFAULT: bool'
[01:23:53] 8: @!has check failed
[01:23:53]  File does not exist 'assoc_consts/trait.Foo.html'
[01:23:53]      // @!has - FOO_HIDDEN
[01:23:53] 16: @has check failed
[01:23:53]  File does not exist 'assoc_consts/struct.Bar.html'
[01:23:53]      // @has assoc_consts/struct.Bar.html '//code' 'impl Foo for Bar'
[01:23:53] 17: @has check failed
[01:23:53]  File does not exist 'assoc_consts/struct.Bar.html'
[01:23:53]      // @has - '//*[@id="associatedconstant.FOO"]' 'const FOO: usize'
[01:23:53] 19: @has check failed
[01:23:53]  File does not exist 'assoc_consts/struct.Bar.html'
[0 [...]

2019-04-08 01:29 UTC, retep998 commented
At some point this will be changed to be enabled by default for Windows users?

2019-04-08 08:10 UTC, GuillaumeGomez commented
I hope so? I'd prefer something to detect the filesystem. But for now, there is still some work to be done in here.

2019-04-11 16:51 UTC, QuietMisdreavus requested changes
I'm having a hard time reading through this. What does it actually do when it encounters a name conflict? Where is that tracked? Right now i'm having to sift through a bunch of unrelated changes to even see what's going on.

2019-04-14 15:59 UTC, ollie27 commented
cc #25879

2019-04-14 22:20 UTC, GuillaumeGomez commented on src/librustdoc/html/render.rs
> +        /*if !self.shared.case_insensitive {
The point was to test it when generating std without having to change `boostrap`, I'll remove it once this PR is done.

2019-04-14 22:21 UTC, GuillaumeGomez commented on src/librustdoc/html/render.rs
> +    pub fn maybe_collapsed_doc_value<'b>(&self, item: &'b clean::Item) -> Option<Cow<'b, str>> {
At some point I added a parameter with a lifetime to `SharedContext`, making necessary to make this change. It's completely useless now.

2019-04-14 22:21 UTC, GuillaumeGomez commented on src/librustdoc/html/render.rs
> +fn url_to_path(url: &str, start_path: &str) -> Option<String> {
Sure!

2019-04-14 22:22 UTC, GuillaumeGomez commented on src/librustdoc/html/render.rs
> +fn render_sources<'a>(
Absolutely!

2019-04-14 22:22 UTC, GuillaumeGomez commented on src/librustdoc/html/render.rs
> +    fn item<F>(&mut self, item: clean::Item, all: &mut AllTypes, mut f: F,
Yes sorry, I was just going down and back between two functions and this one was in the middle so I moved it. Just like the rest, I'll put it "back" once done.

2019-04-14 22:23 UTC, GuillaumeGomez commented on src/librustdoc/html/render.rs
> +               self.item.type_(), self.item.name.as_ref().expect("name is unavailable 4"))?;
Simply because I had a failure and I couldn't find from where so to track it down, I replaced most `unwrap` calls with `expect`.

2019-04-14 22:23 UTC, GuillaumeGomez commented on src/librustdoc/html/render.rs
> +               it.name.as_ref().expect("name unavailable 10"),
Good catch!

2019-04-14 22:24 UTC, GuillaumeGomez commented on src/librustdoc/html/render.rs
> +fn render_assoc_items(
The function changed a few times following my needs and this is the result, nothing magical behind that. ;)

2019-04-14 22:25 UTC, GuillaumeGomez commented
@QuietMisdreavus: But more globally, do you think this is the correct way to do this? Or should I try to put it into the `Cache` somehow (not sure if that's possible nor wanted) or in another part of the code?

2019-05-06 19:11 UTC, Dylan-DPC commented
ping from triage @QuietMisdreavus @GuillaumeGomez  any updates on this?

2019-05-07 08:14 UTC, GuillaumeGomez commented
Still waiting for @QuietMisdreavus feedback. :)

2019-06-05 20:52 UTC, QuietMisdreavus commented
Does this also work for the redirect files, since those are grouped by namespace instead of just kind?

```rust
pub struct Foo;

pub enum FoO {}
```

@GuillaumeGomez The basic approach - generating a mapping of item paths to filename stems in case of conflict - is fine. However, my complaints about the PR being difficult to review still stand. The changes are sprawling, divided into commits that cannot be viewed on their own, offer no explanation of the overall approach or specific implementation details, and grouped in with unrelated (and in many cases unnecessary) changes. I can't offer comments on your approach if it takes all my energy to just pick apart what your PR is doing in the first place.

2019-06-06 08:24 UTC, GuillaumeGomez commented
Ok, I'll try to clean it up but considering the amount of changes, I think it'll be complicated in any case. I'll add comments though and write down a global explanation of what I have in mind.

2019-07-09 18:47 UTC, Mark-Simulacrum commented
I'm going to close this PR for the time being, it can be reopened once @GuillaumeGomez finishes rebasing and reworking the PR into a more reviewable state.

2019-07-09 18:47 UTC, closed without merging

2019-09-19 02:40 UTC, avborhanian commented
Hey, would it be kosher for me to try to make the necessary changes to make it reviewable and open a new pull request with said changes?

2019-09-19 10:52 UTC, Mark-Simulacrum commented
I think so, yes, though I myself am currently uncertain as to the approach in general :)