Do not mention missing `PartialOrd` impl when involving uncalled fns
rust-lang/rust pull request #60051
Opened 2019-04-17 21:38 UTC by estebank

2019-04-17 21:38 UTC, rust-highfive commented
r? @pnkfelix

(rust_highfive has picked a reviewer for you, use r? to override)

2019-04-17 21:38 UTC, estebank commented
r? @davidtwco

2019-04-17 22:01 UTC, davidtwco requested changes
LGTM, one minor comment.

2019-04-17 23:43 UTC, estebank commented on src/librustc_typeck/check/op.rs
> +    ) -> bool {
Done

2019-04-18 02:51 UTC, estebank commented
@bors r=davidtwco

2019-04-18 02:52 UTC, estebank commented
@bors rollup

2019-04-18 06:00 UTC, merged