add Miri error variant for process exit
rust-lang/rust pull request #60116
Opened 2019-04-19 16:48 UTC by RalfJung

This is to support https://github.com/rust-lang/miri/pull/702

r? @oli-obk

2019-04-19 16:50 UTC, bjorn3 approved these changes

2019-04-20 14:04 UTC, oli-obk requested changes
r=me with doc nits

2019-04-20 14:04 UTC, oli-obk commented on src/librustc/mir/interpret/error.rs
> +    /// Not actually an interprer error -- used to signal that execution has exited
```suggestion
    /// Not actually an interpreter error -- used to signal that execution has exited
```

2019-04-20 14:04 UTC, oli-obk commented on src/librustc/mir/interpret/error.rs
> +    /// with the given status code.
Mention that this is a miri thing and not a const eval thing.

2019-04-20 16:39 UTC, RalfJung commented
@bors r=oli-obk rollup

2019-04-21 05:25 UTC, merged