Optimize HIR map
rust-lang/rust pull request #60246
Opened 2019-04-24 19:47 UTC by Zoxc

Builds on https://github.com/rust-lang/rust/pull/59042

cc @ljedrz
r? @eddyb

2019-04-24 20:01 UTC, Zoxc commented
@bors try

2019-04-24 21:46 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/195379635) ([raw log](https://api.travis-ci.com/v3/job/195379635/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:001763f4:start=1556135562249149308,finish=1556135563013292812,duration=764143504
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---
travis_time:start:test_assembly
Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:22:24] 
[01:22:24] running 9 tests
[01:22:24] iiiiiiiii
[01:22:24] 
[01:22:24]  finished in 0.151
[01:22:24] travis_fold:end:test_assembly

---
travis_time:start:test_debuginfo
Check compiletest suite=debuginfo mode=debuginfo-both (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:22:40] 
[01:22:40] running 121 tests
[01:23:06] .iiiii...i.....i..i...i..i.i.i..i.ii...i.....i..i....i..........iiii..........i...ii...i.......ii.i. 100/121
[01:23:10] i.i......iii.i.....ii
[01:23:10] 
[01:23:10]  finished in 30.681
[01:23:10] travis_fold:end:test_debuginfo

---
Check compiletest suite=run-make-fulldeps mode=run-make (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:52:08] 
[01:52:08] running 197 tests
[01:52:37] ..................i...i................................................................i............ 100/197
[01:53:23] ...................................F.................i......................................i....
[01:53:23] failures:
[01:53:23] note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[01:53:23] 
[01:53:23] ---- [run-make] run-make-fulldeps/pretty-print-path-suffix stdout ----
[01:53:23] ---- [run-make] run-make-fulldeps/pretty-print-path-suffix stdout ----
[01:53:23] 
[01:53:23] error: make failed
[01:53:23] status: exit code: 2
[01:53:23] command: "make"
[01:53:23] stdout:
[01:53:23] ------------------------------------------
[01:53:23] make[1]: Entering directory '/checkout/src/test/run-make-fulldeps/pretty-print-path-suffix'
[01:53:23] LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/pretty-print-path-suffix/pretty-print-path-suffix:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" '/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc' --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/pretty-print-path-suffix/pretty-print-path-suffix -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/pretty-print-path-suffix/pretty-print-path-suffix  -o /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/pretty-print-path-suffix/pretty-print-path-suffix/foo.out -Z unpretty=hir=foo input.rs
[01:53:23] LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/pretty-print-path-suffix/pretty-print-path-suffix:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" '/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc' --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/pretty-print-path-suffix/pretty-print-path-suffix -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/pretty-print-path-suffix/pretty-print-path-suffix  -o /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/pretty-print-path-suffix/pretty-print-path-suffix/nest_foo.out -Z unpretty=hir=nest::foo input.rs
[01:53:23] LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/pretty-print-path-suffix/pretty-print-path-suffix:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" '/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc' --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/pretty-print-path-suffix/pretty-print-path-suffix -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/pretty-print-path-suffix/pretty-print-path-suffix  -o /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/pretty-print-path-suffix/pretty-print-path-suffix/foo_method.out -Z unpretty=hir=foo_method input.rs
[01:53:23] diff -u /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/pretty-print-path-suffix/pretty-print-path-suffix/foo.out foo.pp
[01:53:23] --- /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/pretty-print-path-suffix/pretty-print-path-suffix/foo.out 2019-04-24 21:45:41.689211650 +0000
[01:53:23] +++ foo.pp 2019-04-24 19:52:41.805211650 +0000
[01:53:23] @@ -0,0 +1,5 @@
[01:53:23] +
[01:53:23] +pub fn foo() -> i32 { 45 } /* foo */
[01:53:23] +
[01:53:23] +
[01:53:23] +pub fn foo() -> &'static str { "i am a foo." } /* nest::foo */
[01:53:23] Makefile:4: recipe for target 'all' failed
[01:53:23] make[1]: Leaving directory '/checkout/src/test/run-make-fulldeps/pretty-print-path-suffix'
[01:53:23] ------------------------------------------
[01:53:23] stderr:
[01:53:23] ------------------------------------------
[01:53:23] ------------------------------------------
[01:53:23] warning: ignoring --out-dir flag due to -o flag
[01:53:23] 
[01:53:23] warning: ignoring --out-dir flag due to -o flag
[01:53:23] 
[01:53:23] warning: ignoring --out-dir flag due to -o flag
[01:53:23] 
[01:53:23] make[1]: *** [all] Error 1
[01:53:23] ------------------------------------------
[01:53:23] 
[01:53:23] 
[01:53:23] 
[01:53:23] 
[01:53:23] failures:
[01:53:23]     [run-make] run-make-fulldeps/pretty-print-path-suffix
[01:53:23] 
[01:53:23] test result: FAILED. 191 passed; 1 failed; 5 ignored; 0 measured; 0 filtered out
[01:53:23] 
[01:53:23] 
[01:53:23] 
[01:53:23] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--rustdoc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc" "--src-base" "/checkout/src/test/run-make-fulldeps" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "run-make" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-6.0/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -O -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "6.0.0\n" "--system-llvm" "--cc" "cc" "--cxx" "c++" "--cflags" "-ffunction-sections -fdata-sections -fPIC -m64" "--llvm-components" "aarch64 aarch64asmparser aarch64asmprinter aarch64codegen aarch64desc aarch64disassembler aarch64info aa [...]

2019-04-24 22:52 UTC, Xanewok commented
@rust-timer build 890cc87d1001f65c608c711d7a4d0d48129a43c1

2019-04-24 22:52 UTC, rust-timer commented
Success: Queued 890cc87d1001f65c608c711d7a4d0d48129a43c1 with parent e305df1846a6d985315917ae0c81b74af8b4e641, [comparison URL](https://perf.rust-lang.org/compare.html?start=e305df1846a6d985315917ae0c81b74af8b4e641&end=890cc87d1001f65c608c711d7a4d0d48129a43c1).

2019-04-25 03:07 UTC, rust-timer commented
Finished benchmarking try commit 890cc87d1001f65c608c711d7a4d0d48129a43c1

2019-04-25 03:59 UTC, Zoxc commented
Seems like this approach works well. There's still some slight memory regressions though.

2019-04-25 18:36 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/195670845) ([raw log](https://api.travis-ci.com/v3/job/195670845/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:005982c6:start=1556216519294202627,finish=1556216521438908215,duration=2144705588
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---

[00:04:18] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:04:19] tidy error: /checkout/src/librustc/hir/map/mod.rs:1215: trailing whitespace
[00:04:20] some tidy checks failed
[00:04:20] 
[00:04:20] 
[00:04:20] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:20] 
[00:04:20] 
[00:04:20] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:20] Build completed unsuccessfully in 0:00:45
[00:04:20] Build completed unsuccessfully in 0:00:45
[00:04:20] make: *** [tidy] Error 1
[00:04:20] Makefile:67: recipe for target 'tidy' failed
The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:0ec45cf8
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
Thu Apr 25 18:26:33 UTC 2019
---
travis_time:end:0d80e979:start=1556216793919279285,finish=1556216793924162685,duration=4883400
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0d377e70
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:10837696
travis_time:start:10837696
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:1634df17
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-05-01 09:43 UTC, Xanewok reviewed
IIUC this fixes a regression introduced in https://github.com/rust-lang/rust/pull/59042 and doesn't look like a *very* invasive change (limited only to one data structure) - should we not land it?

2019-05-01 09:43 UTC, Xanewok commented on src/librustc/hir/map/mod.rs
> +pub(super) type HirMap<'hir> = [Vec<Option<IndexVec<ItemLocalId, Option<Entry<'hir>>>>>; 2];
It takes a while to decipher what the structure looks like and why it looks this way - it'd be great if we could add a doc-comment here with an explanation

2019-05-01 09:43 UTC, Xanewok commented on src/librustc/hir/map/mod.rs
> +        spaces.flat_map(move |space| {
It'd be great to also add a comment here and/or rustfmt the function body

2019-05-06 17:46 UTC, eddyb commented on src/librustc/hir/map/mod.rs
> +pub(super) type HirMap<'hir> = [Vec<Option<IndexVec<ItemLocalId, Option<Entry<'hir>>>>>; 2];
`hir::map::Map` *is* the HIR map. Can you rename this type alias to `HirEntryMap` or something?

2019-05-06 17:47 UTC, eddyb requested changes
This looks great, r=me modulo nits!

2019-05-08 15:24 UTC, merged

2019-05-08 16:08 UTC, bjorn3 commented on src/librustc/hir/map/mod.rs
> +    fn matces_suffix(&self, hir: HirId) -> bool {
*matches

2019-05-08 16:08 UTC, bjorn3 commented on src/librustc/hir/map/mod.rs
> +        self.all_ids().filter(move |hir| nodes.matces_suffix(*hir)).map(move |hir| {
*matches

2019-05-08 16:12 UTC, bjorn3 commented
I am a little confused about the order of comments on this PR: bors merges (1h ago) -> me reviewing it (few min ago) -> Zoxc gives r+ (3h ago).

2019-05-08 16:41 UTC, Zoxc commented
@bjorn3 It's github new feature, time-travelling comments.

2019-05-08 16:52 UTC, bjorn3 commented
When looking at my notifications list, it said bors was the last commenter :)

2019-05-08 16:58 UTC, Zoxc commented
You can see that I will post my comment in 3 hours. Github simply sorts comments by time!

2019-05-08 17:27 UTC, bjorn3 commented
On mobile it says 2 hours ago though.

2019-05-14 18:33 UTC, Zoxc commented
Perf result: https://perf.rust-lang.org/compare.html?start=b92d360c6cf029bd98c154cb510ec9e11b39bad6&end=d7f4a864e13dc88d7a28c0b742da844af4e3abc4&stat=wall-time