Add custom nth_back for Zip
rust-lang/rust pull request #60574
Opened 2019-05-06 07:36 UTC by mdnight

Implementation of nth_back for Zip.
Part of #54054
r? @scottmcm

2019-05-06 07:36 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @scottmcm (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2019-05-06 12:20 UTC, timvermeulen commented
Since the underlying iterators may have side-effects, I don't think we can return early when `min_len < n`.

2019-05-06 22:55 UTC, koalatux commented
@timvermeulen, returning early might be ok, especially if you are leveraging the underlaying nth_back. The forward next also does short-circuiting, its documentation sais: "If the first iterator returns None, zip will short-circuit and next will not be called on the second iterator." Maybe we can use a similar behaviour here.

2019-05-07 12:46 UTC, timvermeulen commented
@koalatux That guarantee is specific to `Zip`, whereas custom implementations of `nth` and `nth_back` are required by the `Iterator` trait to have the same behavior in regards to side effects as the default implementations (i.e. repeated calls to `next`/`next_back`).

So short-circuiting `Zip::nth_back` by forwarding to `nth_back` on the inner iterators is indeed fine, if done carefully, but short-circuiting based on the simple check `min_len < n` is not.

2019-05-20 15:53 UTC, Dylan-DPC commented
ping from triage @scottmcm waiting for your review on this

2019-05-29 05:22 UTC, scottmcm requested changes

2019-05-29 05:22 UTC, scottmcm commented on src/libcore/iter/adapters/zip.rs
> +        while let Some(x) = ZipImpl::next_back(self) {
The default implementation of `nth_back` calls `Iterator::next_back` in a loop, which seems like it'd be just as good as this one?  It looks like `ZipImpl::nth` exists, so I'd have expected the change here to add `ZipImpl::nth_back` and specialize it the same way.

2019-06-18 15:57 UTC, jonas-schievink commented
Ping from triage @mdnight, can you address the review comment?

2019-07-20 00:55 UTC, JohnCSimon commented
Ping from triage @mdnight  please address the review comment

2019-07-27 01:44 UTC, JohnCSimon commented
@scottmcm  Triage: Thanks for the PR but I'm going to close this due to lack of movement.

2019-07-27 01:44 UTC, closed without merging