Expand dynamic drop tests for cases in #47949
rust-lang/rust pull request #60729
Opened 2019-05-11 10:23 UTC by matthewjasper

Adds test cases for #47949

2019-05-11 10:23 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2019-05-11 14:01 UTC, jonas-schievink commented on src/test/run-pass/drop/dynamic-drop.rs
> +    // `rustc_mir::builc::Builder::into`.
```suggestion
    // `rustc_mir::build::Builder::into`.
```

2019-05-11 14:01 UTC, jonas-schievink commented on src/test/run-pass/drop/dynamic-drop.rs
> +    // the `failing_op` is in the list of exception.
```suggestion
    // `failing_op` is in the list of exception.
```

2019-05-17 20:31 UTC, nikomatsakis requested changes
Looks good, r=me, but can we tweak the comments?

2019-05-17 20:31 UTC, nikomatsakis commented on src/test/run-pass/drop/dynamic-drop.rs
> +        break a.alloc_leaked(exceptions);
I'd prefer to have a FIXME here too -- something like

---

```
// FIXME(#XXX) we should not be leaking this, but we are
```

2019-05-17 20:31 UTC, nikomatsakis commented on src/test/run-pass/drop/dynamic-drop.rs
> +    // FIXME (#47949) We shouldn't need this, but we are sometimes leaking
For some reason, I found this kind of confusing. Maybe something like this:

```
FIXME(#47949) -- Each use of this indicates a bug: basically, a value that winds up getting leaked but shouldn't be.
```

2019-05-30 18:36 UTC, nikomatsakis commented
r=me -- @matthewjasper did you want to "FIXUP" that commit, thogh?

2019-05-31 06:27 UTC, matthewjasper commented
@bors r=nikomatsakis

2019-06-01 09:27 UTC, merged