Show the message in case of `should_panic` failure
rust-lang/rust pull request #61068
Opened 2019-05-23 02:40 UTC by chansuke

This PR fixes a problem in #60790.

2019-05-23 02:40 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @Mark-Simulacrum (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2019-05-23 04:11 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/202376759) ([raw log](https://api.travis-ci.com/v3/job/202376759/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:15d7adb4:start=1558579290528273813,finish=1558579379765715640,duration=89237441827
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---
travis_time:start:test_codegen
Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:20:12] 
[01:20:12] running 143 tests
[01:20:15] i..iii.....iii..iiii.....i......................i..i.................i.....i..........ii.i..i..i.ii. 100/143
[01:20:16] test result: ok. 113 passed; 0 failed; 30 ignored; 0 measured; 0 filtered out
[01:20:16] 
[01:20:16]  finished in 4.671
[01:20:16] travis_fold:end:test_codegen
---
travis_time:start:test_assembly
Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:20:19] 
[01:20:19] running 9 tests
[01:20:19] iiiiiiiii
[01:20:19] 
[01:20:19]  finished in 0.155
[01:20:19] travis_fold:end:test_assembly

---
travis_time:start:test_debuginfo
Check compiletest suite=debuginfo mode=debuginfo-both (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:20:35] 
[01:20:35] running 122 tests
[01:21:00] .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....i..........iiii..........i...ii...i.......ii.i 100/122
[01:21:05] .i.i......iii.i.....ii
[01:21:05] 
[01:21:05]  finished in 30.508
[01:21:05] travis_fold:end:test_debuginfo

---
[01:28:40] travis_fold:start:test_stage1-test
travis_time:start:test_stage1-test
Testing test stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:28:40]    Compiling test v0.0.0 (/checkout/src/libtest)
[01:28:40] error: unused import: `TrFailed`
[01:28:40]      |
[01:28:40]      |
[01:28:40] 1781 |         ShouldPanic, StaticTestName, TestDesc, TestDescAndFn, TestOpts, TrFailed, TrFailedMsg,
[01:28:40]      |
[01:28:40]      = note: `-D unused-imports` implied by `-D warnings`
[01:28:40] 
[01:28:40] error[E0308]: mismatched types
[01:28:40] error[E0308]: mismatched types
[01:28:40]     --> src/libtest/lib.rs:1926:36
[01:28:40]      |
[01:28:40] 1926 |         assert!(res == TrFailedMsg("test did not panic as expected"));
[01:28:40]      |                                    |
[01:28:40]      |                                    expected struct `std::string::String`, found reference
[01:28:40]      |                                    expected struct `std::string::String`, found reference
[01:28:40]      |                                    help: try using a conversion method: `"test did not panic as expected".to_string()`
[01:28:40]      = note: expected type `std::string::String`
[01:28:40]                 found type `&'static str`
[01:28:40] 
[01:28:41] error: aborting due to 2 previous errors
[01:28:41] error: aborting due to 2 previous errors
[01:28:41] 
[01:28:41] For more information about this error, try `rustc --explain E0308`.
[01:28:41] error: Could not compile `test`.
[01:28:41] 
[01:28:41] To learn more, run the command again with --verbose.
[01:28:41] 
[01:28:41] 
[01:28:41] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/libtest/Cargo.toml" "-p" "test" "--" "--quiet"
[01:28:41] 
[01:28:41] 
[01:28:41] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:28:41] Build completed unsuccessfully in 0:20:14
[01:28:41] Build completed unsuccessfully in 0:20:14
[01:28:41] Makefile:48: recipe for target 'check' failed
[01:28:41] make: *** [check] Error 1
The command "stamp sh -x -c "$RUN_SCRIPT"" exited with 2.
travis_time:start:011dc570
$ date && (curl -fs --head https://google.com | grep ^Date: | sed 's/Date: //g' || true)
Thu May 23 04:11:50 UTC 2019
---
travis_time:end:001c7dd0:start=1558584711828073782,finish=1558584711832593293,duration=4519511
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0fc9e31a
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:1ee30c94
travis_time:start:1ee30c94
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:0e1b5ba5
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-05-23 06:56 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/202408014) ([raw log](https://api.travis-ci.com/v3/job/202408014/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:03269e96:start=1558594131965403944,finish=1558594220356508478,duration=88391104534
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---
[00:05:28]    Compiling test v0.0.0 (/checkout/src/libtest)
[00:05:28] error[E0308]: mismatched types
[00:05:28]     --> src/libtest/lib.rs:1546:26
[00:05:28]      |
[00:05:28] 1546 |         _ => TrFailedMsg("test did not panic as expected"),
[00:05:28]      |                          |
[00:05:28]      |                          expected struct `std::string::String`, found reference
[00:05:28]      |                          expected struct `std::string::String`, found reference
[00:05:28]      |                          help: try using a conversion method: `"test did not panic as expected".to_string()`
[00:05:28]      = note: expected type `std::string::String`
[00:05:28]                 found type `&'static str`
[00:05:28] 
[00:05:29] error: aborting due to previous error
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-05-23 07:39 UTC, Centril commented
r? @varkor @bors rollup

2019-05-30 20:55 UTC, varkor commented
Sorry, I completely missed this! Thanks for the fix!

@bors r+

2019-05-30 20:59 UTC, Centril commented
@varkor travis doesn't seem to pass?

@bors rollup-

2019-05-30 21:00 UTC, varkor requested changes
Looks good after fixing the string issues. You can use `./x.py check` to make sure everything type checks.

2019-05-30 21:00 UTC, varkor commented
@bors r-

Sorry, I didn't even spot that this wasn't passing.

2019-06-15 10:44 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/208313582) ([raw log](https://api.travis-ci.com/v3/job/208313582/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:2acebe48:start=1560590512425132338,finish=1560590601400697818,duration=88975565480
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---
travis_time:start:test_assembly
Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:08:16] 
[01:08:16] running 9 tests
[01:08:16] iiiiiiiii
[01:08:16] 
[01:08:16]  finished in 0.159
[01:08:16] travis_fold:end:test_assembly

---
travis_time:start:test_debuginfo
Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:08:33] 
[01:08:33] running 122 tests
[01:08:59] .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....i..........iiii..........i...ii...i.......ii.i 100/122
[01:09:04] .i.i......iii.i.....ii
[01:09:04] 
[01:09:04]  finished in 31.376
[01:09:04] travis_fold:end:test_debuginfo

---
[01:21:15] travis_fold:start:test_stage1-test
travis_time:start:test_stage1-test
Testing test stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:21:16]    Compiling test v0.0.0 (/checkout/src/libtest)
[01:21:16] error: unused import: `TrFailed`
[01:21:16]      |
[01:21:16]      |
[01:21:16] 1779 |         ShouldPanic, StaticTestName, TestDesc, TestDescAndFn, TestOpts, TrFailed, TrFailedMsg,
[01:21:16]      |
[01:21:16]      = note: `-D unused-imports` implied by `-D warnings`
[01:21:16] 
[01:21:16] error: aborting due to previous error
[01:21:16] error: aborting due to previous error
[01:21:16] 
[01:21:16] error: Could not compile `test`.
[01:21:16] 
[01:21:16] To learn more, run the command again with --verbose.
[01:21:16] 
[01:21:16] 
[01:21:16] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "--release" "--locked" "--color" "always" "--manifest-path" "/checkout/src/libtest/Cargo.toml" "-p" "test" "--" "--quiet"
[01:21:16] 
[01:21:16] 
[01:21:16] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test
[01:21:16] Build completed unsuccessfully in 1:17:10
---
travis_time:end:083106a0:start=1560595489238358081,finish=1560595489244827888,duration=6469807
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:03c5ee84
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-06-16 03:50 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/208371896) ([raw log](https://api.travis-ci.com/v3/job/208371896/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:07c7d58e:start=1560650776542290752,finish=1560650862017134525,duration=85474843773
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---
travis_time:start:test_assembly
Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:03:56] 
[01:03:56] running 9 tests
[01:03:56] iiiiiiiii
[01:03:56] 
[01:03:56]  finished in 0.153
[01:03:56] travis_fold:end:test_assembly

---
travis_time:start:test_debuginfo
Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:04:12] 
[01:04:12] running 122 tests
[01:04:36] .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....i..........iiii..........i...ii...i.......ii.i 100/122
[01:04:41] .i.i......iii.i.....ii
[01:04:41] 
[01:04:41]  finished in 29.787
[01:04:41] travis_fold:end:test_debuginfo

---
travis_time:start:test_run-make-fulldeps
Check compiletest suite=run-make-fulldeps mode=run-make (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:41:38] 
[01:41:38] running 200 tests
[01:42:04] ..................i...ii................................................................i....F...... 100/200
[01:42:48] ............................iiii........i..........iiii.iii....................................i.... 200/200
[01:42:48] failures:
[01:42:48] thread 'main' panicked at 'Some tests failed', src/tools/compiletest/src/main.rs:521:22
[01:42:48] note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[01:42:48] 
[01:42:48] 
[01:42:48] ---- [run-make] run-make-fulldeps/libtest-json stdout ----
[01:42:48] 
[01:42:48] error: make failed
[01:42:48] status: exit code: 2
[01:42:48] command: "make"
[01:42:48] stdout:
[01:42:48] ------------------------------------------
[01:42:48] LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" '/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc' --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json  --test f.rs
[01:42:48] RUST_BACKTRACE=0 LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json/f -Z unstable-options --test-threads=1 --format=json > /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json/libtest-json-output.json || true
[01:42:48] cat /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json/libtest-json-output.json | "/usr/bin/python2.7" validate_json.py
[01:42:48] # Compare to output file
[01:42:48] diff output.json /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json/libtest-json-output.json
[01:42:48] 5c5
[01:42:48] < { "type": "test", "name": "b", "event": "failed", "stdout": "thread 'main' panicked at 'assertion failed: false', f.rs:8:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\n" }
[01:42:48] ---
[01:42:48] > { "type": "test", "name": "b", "event": "failed", "message": "test did not panic as expected" }
[01:42:48] Makefile:8: recipe for target 'all' failed
[01:42:48] ------------------------------------------
[01:42:48] stderr:
[01:42:48] ------------------------------------------
[01:42:48] make: *** [all] Error 1
---
[01:42:48] test result: FAILED. 182 passed; 1 failed; 17 ignored; 0 measured; 0 filtered out
[01:42:48] 
[01:42:48] 
[01:42:48] 
[01:42:48] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--rustdoc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc" "--src-base" "/checkout/src/test/run-make-fulldeps" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "run-make" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-6.0/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Cdebuginfo=0 -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -O -Cdebuginfo=0 -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "6.0.0\n" "--system-llvm" "--cc" "cc" "--cxx" "c++" "--cflags" "-ffunction-sections -fdata-sections -fPIC -m64" "--llvm-components" "aarch64 aarch64asmparser aarch64asmprinter aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils all all-targets amdgpu amdgpuasmparser amdgpuasmprinter amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgpuutils analysis arm armasmparser armasmprinter armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter binaryformat bitreader bitwriter bpf bpfasmparser bpfasmprinter bpfcodegen bpfdesc bpfdisassembler bpfinfo codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfomsf debuginfopdb demangle dlltooldriver engine executionengine fuzzmutate globalisel hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interpreter ipo irreader lanai lanaiasmparser lanaiasmprinter lanaicodegen lanaidesc lanaidisassembler lanaiinfo libdriver lineeditor linker lto mc mcdisassembler mcjit mcparser mips mipsasmparser mipsasmprinter mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmprinter msp430codegen msp430desc msp430info native nativecodegen nvptx nvptxasmprinter nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcjit passes powerpc powerpcasmparser powerpcasmprinter powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata runtimedyld scalaropts selectiondag sparc sparcasmparser sparcasmprinter sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzasmprinter systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target transformutils vectorize windowsmanifest x86 x86asmparser x86asmprinter x86codegen x86desc x86disassembler x86info x86utils xcore xcoreasmprinter xcorecodegen xcoredesc xcoredisassembler xcoreinfo" "--llvm-cxxflags" "-I/ [...]

2019-06-17 10:05 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/208539118) ([raw log](https://api.travis-ci.com/v3/job/208539118/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:2b074837:start=1560764936350035813,finish=1560765022076523274,duration=85726487461
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---

[00:03:47] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:03:48] tidy error: /checkout/src/libtest/lib.rs: missing trailing newline
[00:03:52] some tidy checks failed
[00:03:52] 
[00:03:52] 
[00:03:52] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:03:52] 
[00:03:52] 
[00:03:52] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:03:52] Build completed unsuccessfully in 0:01:12
---
travis_time:end:0d066d94:start=1560765264626776592,finish=1560765264631424944,duration=4648352
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:06d5868a
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:02c49ec7
travis_time:start:02c49ec7
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:057de4fc
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-06-18 16:45 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/209003666) ([raw log](https://api.travis-ci.com/v3/job/209003666/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:0335a315:start=1560875161431680230,finish=1560875253292074969,duration=91860394739
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---
[00:14:29]    Compiling rustc_mir v0.0.0 (/checkout/src/librustc_mir)
[00:14:31] error[E0425]: cannot find function `make_target_blocks` in this scope
[00:14:31]    --> src/librustc_mir/build/matches/test.rs:182:37
[00:14:31]     |
[00:14:31] 182 |                 let target_blocks = make_target_blocks(self);
[00:14:31]     |                                     ^^^^^^^^^^^^^^^^^^ help: a local variable with a similar name exists: `target_blocks`
[00:14:31] error[E0425]: cannot find function `make_target_blocks` in this scope
[00:14:31]    --> src/librustc_mir/build/matches/test.rs:283:37
[00:14:31]     |
[00:14:31]     |
[00:14:31] 283 |                 let target_blocks = make_target_blocks(self);
[00:14:31]     |                                     ^^^^^^^^^^^^^^^^^^ help: a local variable with a similar name exists: `target_blocks`
[00:14:44] error: aborting due to 2 previous errors
[00:14:44] 
[00:14:44] For more information about this error, try `rustc --explain E0425`.
[00:14:44] error: Could not compile `rustc_mir`.
---
travis_time:end:2287ea92:start=1560876308080639675,finish=1560876308085644017,duration=5004342
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:2ab71b3e
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:0433086f
travis_time:start:0433086f
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:0712dce8
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-06-19 06:25 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/209159795) ([raw log](https://api.travis-ci.com/v3/job/209159795/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:0dd2647c:start=1560919067740992777,finish=1560919068521340474,duration=780347697
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---
travis_time:start:test_assembly
Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:07:45] 
[01:07:45] running 9 tests
[01:07:45] iiiiiiiii
[01:07:45] 
[01:07:45]  finished in 0.152
[01:07:45] travis_fold:end:test_assembly

---
travis_time:start:test_debuginfo
Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:08:01] 
[01:08:01] running 122 tests
[01:08:27] .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....i..........iiii..........i...ii...i.......ii.i 100/122
[01:08:32] .i.i......iii.i.....ii
[01:08:32] 
[01:08:32]  finished in 31.146
[01:08:32] travis_fold:end:test_debuginfo

---
travis_time:start:test_run-make-fulldeps
Check compiletest suite=run-make-fulldeps mode=run-make (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[01:46:16] 
[01:46:16] running 200 tests
[01:46:42] ..................i...ii................................................................i....F...... 100/200
[01:47:28] ............................iiii........i..........iiii.iii....................................i.... 200/200
[01:47:28] failures:
[01:47:28] thread 'main' panicked at 'Some tests failed', src/tools/compiletest/src/main.rs:521:22
[01:47:28] 
[01:47:28] note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[01:47:28] note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
[01:47:28] ---- [run-make] run-make-fulldeps/libtest-json stdout ----
[01:47:28] 
[01:47:28] error: make failed
[01:47:28] status: exit code: 2
[01:47:28] command: "make"
[01:47:28] stdout:
[01:47:28] ------------------------------------------
[01:47:28] LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" '/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc' --out-dir /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json -L /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json  --test f.rs
[01:47:28] RUST_BACKTRACE=0 LD_LIBRARY_PATH="/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json:/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps:/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/lib" /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json/f -Z unstable-options --test-threads=1 --format=json > /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json/libtest-json-output.json || true
[01:47:28] cat /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json/libtest-json-output.json | "/usr/bin/python2.7" validate_json.py
[01:47:28] # Compare to output file
[01:47:28] diff output.json /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json/libtest-json-output.json
[01:47:28] 5c5
[01:47:28] < { "type": "test", "name": "b", "event": "failed", "stdout": "thread 'main' panicked at 'assertion failed: false', f.rs:8:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\n" }
[01:47:28] ---
[01:47:28] > { "type": "test", "name": "b", "event": "failed", "message": "test did not panic as expected" }
[01:47:28] Makefile:8: recipe for target 'all' failed
[01:47:28] ------------------------------------------
[01:47:28] stderr:
[01:47:28] ------------------------------------------
[01:47:28] make: *** [all] Error 1
---
[01:47:28] test result: FAILED. 182 passed; 1 failed; 17 ignored; 0 measured; 0 filtered out
[01:47:28] 
[01:47:28] 
[01:47:28] 
[01:47:28] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--rustdoc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc" "--src-base" "/checkout/src/test/run-make-fulldeps" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--mode" "run-make" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-6.0/bin/FileCheck" "--host-rustcflags" "-Crpath -O -Cdebuginfo=0 -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -O -Cdebuginfo=0 -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python2.7" "--lldb-python" "/usr/bin/python2.7" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "6.0.0\n" "--system-llvm" "--cc" "cc" "--cxx" "c++" "--cflags" "-ffunction-sections -fdata-sections -fPIC -m64" "--llvm-components" "aarch64 aarch64asmparser aarch64asmprinter aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils all all-targets amdgpu amdgpuasmparser amdgpuasmprinter amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgpuutils analysis arm armasmparser armasmprinter armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter binaryformat bitreader bitwriter bpf bpfasmparser bpfasmprinter bpfcodegen bpfdesc bpfdisassembler bpfinfo codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfomsf debuginfopdb demangle dlltooldriver engine executionengine fuzzmutate globalisel hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interpreter ipo irreader lanai lanaiasmparser lanaiasmprinter lanaicodegen lanaidesc lanaidisassembler lanaiinfo libdriver lineeditor linker lto mc mcdisassembler mcjit mcparser mips mipsasmparser mipsasmprinter mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmprinter msp430codegen msp430desc msp430info native nativecodegen nvptx nvptxasmprinter nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcjit passes powerpc powerpcasmparser powerpcasmprinter powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata runtimedyld scalaropts selectiondag sparc sparcasmparser sparcasmprinter sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzasmprinter systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target transformutils vectorize windowsmanifest x86 x86asmparser x86asmprinter x86codegen x86desc x86disassembler x86info x86utils xcore xcoreasmprinte [...]

2019-06-23 18:10 UTC, varkor commented
@chansuke: looks like a test is still failing?

2019-07-15 04:52 UTC, chansuke commented
@varkor Thank you for your comment. I'm trying to reproduce in my local environment(macOS Mojave) but only returns error below.
https://github.com/rust-lang/rust/issues/59998
How can I debug this kind of error?

2019-07-22 20:49 UTC, varkor commented on src/libtest/lib.rs
> +        _ => TrFailedMsg("test did not panic as expected".to_string()),
Sorry, I didn't check carefully enough. This should be:
```
(&ShouldPanic::Yes, Ok(())) => TrFailedMsg("test did not panic as expected".to_string()),
_ => TrFailed,
```

2019-07-22 20:50 UTC, varkor commented on src/libtest/tests.rs
> +    assert!(res == TrFailedMsg("test did not panic as expected".to_string()));
```suggestion
    assert_eq!(res, TrFailedMsg("test did not panic as expected".to_string()));
```

2019-07-22 20:52 UTC, varkor commented
> How can I debug this kind of error?

If you look at the error in Travis, you'll see it says:
```
[01:47:28] diff output.json /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-make-fulldeps/libtest-json/libtest-json/libtest-json-output.json
[01:47:28] 5c5
[01:47:28] < { "type": "test", "name": "b", "event": "failed", "stdout": "thread 'main' panicked at 'assertion failed: false', f.rs:8:5\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\n" }
[01:47:28] ---
[01:47:28] > { "type": "test", "name": "b", "event": "failed", "message": "test did not panic as expected" }
```
If you then look at the file `src/test/run-make-fulldeps/libtest-json/f.rs`, you'll see that this message should not have changed, because it's not `#[should_panic]`. So something was wrong with our change. In this case, the answer is clear once we look at the definition of `ShouldPanic`, which includes a `ShouldPanic::Yes` variant, which we weren't checking.

2019-07-30 17:04 UTC, gagan0723 commented
Ping from triage @chansuke any update on this? All checks all failing at the moment. Thanks

2019-07-31 12:54 UTC, chansuke commented
@gagan0723 Sorry for the late response, I will fix that now.

2019-08-01 15:49 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=4900&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4900/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-08-01T14:25:18.2005778Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-08-01T14:25:18.2179929Z ##[command]git config gc.auto 0
2019-08-01T14:25:18.9779140Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-08-01T14:25:18.9785373Z ##[command]git config --get-all http.proxy
2019-08-01T14:25:18.9792428Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/61068/merge:refs/remotes/pull/61068/merge
---
2019-08-01T14:25:53.6251257Z do so (now or later) by using -b with the checkout command again. Example:
2019-08-01T14:25:53.6251289Z 
2019-08-01T14:25:53.6251495Z   git checkout -b <new-branch-name>
2019-08-01T14:25:53.6251525Z 
2019-08-01T14:25:53.6251590Z HEAD is now at 21bc2fb36 Merge 5dfe71efc4a42af6014e8157d491333be31824ad into a17951c4f80eb5208030f91fdb4ae93919fa6b12
2019-08-01T14:25:53.6401269Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-08-01T14:25:53.6404155Z ==============================================================================
2019-08-01T14:25:53.6404359Z Task         : Bash
2019-08-01T14:25:53.6404407Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-08-01T15:26:34.1102277Z .................................................................................................... 1400/8819
2019-08-01T15:26:40.0596707Z .................................................................................................... 1500/8819
2019-08-01T15:26:52.7262945Z .................................................................i...............i.................. 1600/8819
2019-08-01T15:27:00.2975158Z .................................................................................................... 1700/8819
2019-08-01T15:27:15.1631530Z ...................................................iiiii............................................ 1800/8819
2019-08-01T15:27:26.4023498Z .................................................................................................... 2000/8819
2019-08-01T15:27:28.9929869Z .................................................................................................... 2100/8819
2019-08-01T15:27:32.6652576Z .................................................................................................... 2200/8819
2019-08-01T15:27:39.2724421Z .................................................................................................... 2300/8819
---
2019-08-01T15:31:35.7999804Z .................................................................................................... 5300/8819
2019-08-01T15:31:43.3710698Z ..............i..................................................................................... 5400/8819
2019-08-01T15:31:48.9318146Z .................................................................................................... 5500/8819
2019-08-01T15:32:01.4330861Z .................................................................................................... 5600/8819
2019-08-01T15:32:14.8868192Z ........ii...i..ii...........i...................................................................... 5700/8819
2019-08-01T15:32:31.6304636Z .................................................................................................... 5900/8819
2019-08-01T15:32:36.4861048Z .................................................................................................... 6000/8819
2019-08-01T15:32:36.4861048Z .................................................................................................... 6000/8819
2019-08-01T15:32:50.3347186Z ........i..ii....................................................................................... 6100/8819
2019-08-01T15:33:09.6384457Z ...................................................i................................................ 6300/8819
2019-08-01T15:33:11.8402164Z .................................................................................................... 6400/8819
2019-08-01T15:33:14.3377073Z .....................i.............................................................................. 6500/8819
2019-08-01T15:33:18.9077269Z .................................................................................................... 6600/8819
---
2019-08-01T15:37:59.0528651Z  finished in 22.969
2019-08-01T15:37:59.0704438Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-01T15:37:59.2492102Z 
2019-08-01T15:37:59.2493259Z running 146 tests
2019-08-01T15:38:02.5782789Z i....iii.......iii.iiii....i............................i..i................i....i.........ii.i.i..i 100/146
2019-08-01T15:38:04.4574925Z iii..............i.........iii.i......ii......
2019-08-01T15:38:04.4575535Z 
2019-08-01T15:38:04.4575607Z  finished in 5.386
2019-08-01T15:38:04.4768705Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-01T15:38:04.6302397Z 
---
2019-08-01T15:38:06.7509430Z  finished in 2.274
2019-08-01T15:38:06.7695093Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-01T15:38:06.9250995Z 
2019-08-01T15:38:06.9253810Z running 9 tests
2019-08-01T15:38:06.9254667Z iiiiiiiii
2019-08-01T15:38:06.9270420Z 
2019-08-01T15:38:06.9270510Z  finished in 0.156
2019-08-01T15:38:06.9466382Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-01T15:38:07.1060522Z 
---
2019-08-01T15:38:25.4068558Z  finished in 18.460
2019-08-01T15:38:25.4296415Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-01T15:38:25.5928261Z 
2019-08-01T15:38:25.5928566Z running 122 tests
2019-08-01T15:38:49.9891484Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....i..........iiii..........i...ii...i.......ii.i 100/122
2019-08-01T15:38:54.7453037Z .i.i......iii.i.....ii
2019-08-01T15:38:54.7454363Z 
2019-08-01T15:38:54.7459526Z  finished in 29.316
2019-08-01T15:38:54.7467813Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-01T15:38:54.7468197Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-08-01T15:48:44.5733788Z running 39 tests
2019-08-01T15:48:49.6721540Z ....................................F..
2019-08-01T15:48:49.6722135Z failures:
2019-08-01T15:48:49.6722283Z 
2019-08-01T15:48:49.6723215Z ---- tests::test_should_panic_but_succeeds stdout ----
2019-08-01T15:48:49.6723793Z thread 'tests::test_should_panic_but_succeeds' panicked at 'assertion failed: res == TrFailed', src/libtest/tests.rs:149:5
2019-08-01T15:48:49.6724028Z note: test did not panic as expected
2019-08-01T15:48:49.6724302Z failures:
2019-08-01T15:48:49.6724439Z     tests::test_should_panic_but_succeeds
2019-08-01T15:48:49.6724695Z 
2019-08-01T15:48:49.6724822Z test result: FAILED. 38 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
2019-08-01T15:48:49.6724822Z test result: FAILED. 38 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
2019-08-01T15:48:49.6724925Z 
2019-08-01T15:48:49.6735894Z error: test failed, to rerun pass '-p test --lib'
2019-08-01T15:48:49.6761466Z 
2019-08-01T15:48:49.6761466Z 
2019-08-01T15:48:49.6762682 [...]

2019-08-02 03:46 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=4949&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4949/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-08-02T02:23:55.0568260Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-08-02T02:23:55.0777280Z ##[command]git config gc.auto 0
2019-08-02T02:23:55.0856821Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-08-02T02:23:55.0981497Z ##[command]git config --get-all http.proxy
2019-08-02T02:23:55.8021545Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/61068/merge:refs/remotes/pull/61068/merge
---
2019-08-02T02:24:30.8499630Z do so (now or later) by using -b with the checkout command again. Example:
2019-08-02T02:24:30.8500344Z 
2019-08-02T02:24:30.8501169Z   git checkout -b <new-branch-name>
2019-08-02T02:24:30.8501542Z 
2019-08-02T02:24:30.8501786Z HEAD is now at 87b0bc6ad Merge e7339446a2771966920a8a80afb485c91ee5c739 into 435236b8877cdb98c82eaebfb7887782277265c5
2019-08-02T02:24:30.8669817Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-08-02T02:24:30.8673112Z ==============================================================================
2019-08-02T02:24:30.8673192Z Task         : Bash
2019-08-02T02:24:30.8673239Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-08-02T03:24:45.8014476Z .................................................................................................... 1400/8821
2019-08-02T03:24:51.5963770Z .................................................................................................... 1500/8821
2019-08-02T03:25:04.0209433Z .................................................................i...............i.................. 1600/8821
2019-08-02T03:25:11.3435321Z .................................................................................................... 1700/8821
2019-08-02T03:25:26.2141254Z ...................................................iiiii............................................ 1800/8821
2019-08-02T03:25:37.2207607Z .................................................................................................... 2000/8821
2019-08-02T03:25:39.7053903Z .................................................................................................... 2100/8821
2019-08-02T03:25:43.2823187Z .................................................................................................... 2200/8821
2019-08-02T03:25:49.7488614Z .................................................................................................... 2300/8821
---
2019-08-02T03:29:40.7585514Z .................................................................................................... 5300/8821
2019-08-02T03:29:48.2964108Z ...............i.................................................................................... 5400/8821
2019-08-02T03:29:53.8343832Z .................................................................................................... 5500/8821
2019-08-02T03:30:06.1459941Z .................................................................................................... 5600/8821
2019-08-02T03:30:19.3623598Z .........ii...i..ii...........i..................................................................... 5700/8821
2019-08-02T03:30:35.6712228Z .................................................................................................... 5900/8821
2019-08-02T03:30:40.4992854Z .................................................................................................... 6000/8821
2019-08-02T03:30:40.4992854Z .................................................................................................... 6000/8821
2019-08-02T03:30:54.3377128Z .........i..ii...................................................................................... 6100/8821
2019-08-02T03:31:13.1562723Z ....................................................i............................................... 6300/8821
2019-08-02T03:31:15.2566739Z .................................................................................................... 6400/8821
2019-08-02T03:31:17.6567664Z .......................i............................................................................ 6500/8821
2019-08-02T03:31:22.0542028Z .................................................................................................... 6600/8821
---
2019-08-02T03:35:56.6124612Z  finished in 22.074
2019-08-02T03:35:56.6303142Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-02T03:35:56.7919741Z 
2019-08-02T03:35:56.7920026Z running 146 tests
2019-08-02T03:36:00.0219949Z i....iii......iii..iiii....i............................i..i................i....i.........ii.i.i..i 100/146
2019-08-02T03:36:01.8585358Z iii..............i.........iii.i......ii......
2019-08-02T03:36:01.8586102Z 
2019-08-02T03:36:01.8590969Z  finished in 5.227
2019-08-02T03:36:01.8769561Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-02T03:36:02.0401764Z 
---
2019-08-02T03:36:04.0079153Z  finished in 2.131
2019-08-02T03:36:04.0259324Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-02T03:36:04.1869319Z 
2019-08-02T03:36:04.1869635Z running 9 tests
2019-08-02T03:36:04.1870935Z iiiiiiiii
2019-08-02T03:36:04.1871703Z 
2019-08-02T03:36:04.1877484Z  finished in 0.161
2019-08-02T03:36:04.2074313Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-02T03:36:04.3701775Z 
---
2019-08-02T03:36:22.4990673Z  finished in 18.291
2019-08-02T03:36:22.5206379Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-02T03:36:22.6854243Z 
2019-08-02T03:36:22.6854567Z running 122 tests
2019-08-02T03:36:47.2395079Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....i..........iiii..........i...ii...i.......ii.i 100/122
2019-08-02T03:36:51.9552834Z .i.i......iii.i.....ii
2019-08-02T03:36:52.4831144Z 
2019-08-02T03:36:52.4831442Z  finished in 29.435
2019-08-02T03:36:52.4831931Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-02T03:36:52.4832721Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-08-02T03:46:32.6226483Z    |
2019-08-02T03:46:32.6227336Z 73 | fn test_should_panic() {
2019-08-02T03:46:32.6228206Z    |                        - close delimiter possibly meant for this
2019-08-02T03:46:32.6228518Z ...
2019-08-02T03:46:32.6228843Z 89 |     assert!(res == TrFailedMsg("test did not panic as expected".to_string());
2019-08-02T03:46:32.6229511Z    |            - un-closed delimiter
2019-08-02T03:46:32.6230082Z    | ^ incorrect close delimiter
2019-08-02T03:46:32.6230122Z 
2019-08-02T03:46:32.6650613Z warning: macro requires an expression as an argument
2019-08-02T03:46:32.6651509Z   --> src/libtest/tests.rs:89:5
2019-08-02T03:46:32.6651509Z   --> src/libtest/tests.rs:89:5
2019-08-02T03:46:32.6651904Z    |
2019-08-02T03:46:32.6652386Z 89 |       assert!(res == TrFailedMsg("test did not panic as expected".to_string());
2019-08-02T03:46:32.6652915Z    |       ^                                                                       - help: try removing semicolon
2019-08-02T03:46:32.6653707Z    | |
2019-08-02T03 [...]

2019-08-09 01:32 UTC, hdhoang commented
ping from triage @chansuke, any update on this PR? thanks for your effort!

2019-08-10 17:43 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=5569&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/5569/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-08-10T16:13:59.4257046Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-08-10T16:13:59.4446514Z ##[command]git config gc.auto 0
2019-08-10T16:13:59.4524744Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-08-10T16:13:59.4590995Z ##[command]git config --get-all http.proxy
2019-08-10T16:13:59.4724899Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/61068/merge:refs/remotes/pull/61068/merge
---
2019-08-10T16:14:34.1606487Z do so (now or later) by using -b with the checkout command again. Example:
2019-08-10T16:14:34.1608479Z 
2019-08-10T16:14:34.1610530Z   git checkout -b <new-branch-name>
2019-08-10T16:14:34.1612285Z 
2019-08-10T16:14:34.1614429Z HEAD is now at d64457af3 Merge 333644a410eed975edb1641bd313444e6e476af3 into 6f70adcb18e5dc8df0672898a8404fd05a9c32cb
2019-08-10T16:14:34.1770836Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-08-10T16:14:34.1774216Z ==============================================================================
2019-08-10T16:14:34.1774278Z Task         : Bash
2019-08-10T16:14:34.1774323Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-08-10T17:19:22.0312813Z .................................................................................................... 1300/8868
2019-08-10T17:19:28.9083846Z .................................................................................................... 1400/8868
2019-08-10T17:19:35.4715689Z .................................................................................................... 1500/8868
2019-08-10T17:19:46.6149401Z ....................................................................................i............... 1600/8868
2019-08-10T17:19:54.7132068Z i................................................................................................... 1700/8868
2019-08-10T17:20:01.7619674Z ...........................................................................iiiii.................... 1800/8868
2019-08-10T17:20:25.0609253Z .................................................................................................... 2000/8868
2019-08-10T17:20:27.6678251Z .................................................................................................... 2100/8868
2019-08-10T17:20:30.5595665Z .................................................................................................... 2200/8868
2019-08-10T17:20:38.7741851Z .................................................................................................... 2300/8868
---
2019-08-10T17:24:35.0875872Z .................................................................................................... 5200/8868
2019-08-10T17:24:46.3524173Z .................................................................................................... 5300/8868
2019-08-10T17:24:54.1064543Z ....i............................................................................................... 5400/8868
2019-08-10T17:24:59.4982393Z .................................................................................................... 5500/8868
2019-08-10T17:25:12.5767664Z ...................................................................................................i 5600/8868
2019-08-10T17:25:27.6772497Z i...i..ii...........i............................................................................... 5700/8868
2019-08-10T17:25:44.7843974Z .................................................................................................... 5900/8868
2019-08-10T17:25:49.8285522Z .................................................................................................... 6000/8868
2019-08-10T17:25:49.8285522Z .................................................................................................... 6000/8868
2019-08-10T17:26:04.7970789Z i..ii............................................................................................... 6100/8868
2019-08-10T17:26:24.6505587Z ...........................................i........................................................ 6300/8868
2019-08-10T17:26:26.8914310Z .................................................................................................... 6400/8868
2019-08-10T17:26:29.5045585Z ...............i.................................................................................... 6500/8868
2019-08-10T17:26:34.2386994Z .................................................................................................... 6600/8868
---
2019-08-10T17:31:33.8365721Z  finished in 23.835
2019-08-10T17:31:33.8555592Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-10T17:31:34.0540985Z 
2019-08-10T17:31:34.0541801Z running 146 tests
2019-08-10T17:31:37.4871426Z i....iii......iii..iiii....i............................i..i................i....i.........ii.i.i..i 100/146
2019-08-10T17:31:39.4612555Z iii..............i.........iii.i......ii......
2019-08-10T17:31:39.4613159Z 
2019-08-10T17:31:39.4617965Z  finished in 5.606
2019-08-10T17:31:39.4815637Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-10T17:31:40.1568351Z 
---
2019-08-10T17:31:41.8488310Z  finished in 2.367
2019-08-10T17:31:41.8666230Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-10T17:31:42.0346797Z 
2019-08-10T17:31:42.0348014Z running 9 tests
2019-08-10T17:31:42.0350739Z iiiiiiiii
2019-08-10T17:31:42.0352790Z 
2019-08-10T17:31:42.0353700Z  finished in 0.168
2019-08-10T17:31:42.0539387Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-10T17:31:42.6615433Z 
---
2019-08-10T17:32:01.4534923Z  finished in 19.399
2019-08-10T17:32:01.4734813Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-10T17:32:01.6518121Z 
2019-08-10T17:32:01.6518878Z running 122 tests
2019-08-10T17:32:27.4125118Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....i..........iiii..........i...ii...i.......ii.i 100/122
2019-08-10T17:32:32.4165552Z .i.i......iii.i.....ii
2019-08-10T17:32:32.4167287Z 
2019-08-10T17:32:32.4172339Z  finished in 30.943
2019-08-10T17:32:32.4180538Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-10T17:32:32.4181174Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-08-10T17:43:16.4401765Z running 39 tests
2019-08-10T17:43:21.5216221Z ....................................F..
2019-08-10T17:43:21.5216726Z failures:
2019-08-10T17:43:21.5216932Z 
2019-08-10T17:43:21.5217716Z ---- tests::test_should_panic_but_succeeds stdout ----
2019-08-10T17:43:21.5218347Z thread 'tests::test_should_panic_but_succeeds' panicked at 'assertion failed: res == TrFailed', src/libtest/tests.rs:169:5
2019-08-10T17:43:21.5218705Z 
2019-08-10T17:43:21.5218841Z failures:
2019-08-10T17:43:21.5218997Z     tests::test_should_panic_but_succeeds
2019-08-10T17:43:21.5219119Z 
2019-08-10T17:43:21.5219119Z 
2019-08-10T17:43:21.5219261Z test result: FAILED. 38 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
2019-08-10T17:43:21.5219381Z 
2 [...]

2019-08-11 22:40 UTC, varkor commented
@chansuke: I think you just need to add back in the change for the test (as suggested [here](https://github.com/rust-lang/rust/pull/61068#discussion_r306026619)) and everything should work.

2019-08-17 06:15 UTC, JohnCSimon commented
Pinging again from triage 
@chansuke 
please see the comment from @varkor 
Thank you!

2019-08-30 17:16 UTC, ProgrammaticNajel commented
Closing due to inactivity. Thank you @chansuke for your work on this PR. Please reopen this PR when you have a chance to make necessary changes, and be warned that pushing to this PR while it is closed prevents it from being reopened.

2019-08-30 17:16 UTC, closed without merging