Add missing error code explanation for E0183
rust-lang/rust pull request #61225
Opened 2019-05-27 04:38 UTC by ewk

This is part of the ongoing work for #61137

2019-05-27 04:38 UTC, rust-highfive commented
Some changes occurred in diagnostic error codes

cc @GuillaumeGomez

2019-05-27 04:38 UTC, rust-highfive commented
r? @eddyb

(rust_highfive has picked a reviewer for you, use r? to override)

2019-05-27 08:09 UTC, GuillaumeGomez commented on src/librustc_typeck/error_codes.rs
> +Functions must have exactly one (non self) argument, a tuple representing
Please add a failing code example.

2019-05-27 08:09 UTC, GuillaumeGomez commented on src/librustc_typeck/error_codes.rs
> +#![feature(unboxed_closures)]
Please show a complete fixed code example.

2019-05-27 08:09 UTC, GuillaumeGomez requested changes
Please follow the same "template" the other long error explanations are using too please.

2019-07-16 08:34 UTC, chocol4te commented
Ping from triage @ewk, waiting on changes.

2019-07-26 08:22 UTC, ProgrammaticNajel commented
Ping from triage. @ewk any updates on this?

2019-07-26 13:40 UTC, Karrq commented
I'll get it done tonight, if that's not a problem

2019-07-26 13:43 UTC, Dylan-DPC commented
Closing this as @Karrq will work on it in a separate PR

2019-07-26 13:43 UTC, closed without merging