Update all s3 URLs used on CI with subdomains
rust-lang/rust pull request #61284
Opened 2019-05-28 20:24 UTC by alexcrichton

Ensure that they're all forwards-compatible with AWS updates happening
next year by ensuring the bucket name shows up in the domain name.

Closes #61168

2019-05-28 20:24 UTC, rust-highfive commented
r? @pietroalbini

(rust_highfive has picked a reviewer for you, use r? to override)

2019-05-28 20:55 UTC, emilyalbini requested changes
These files still contain old-style URLs:

* `src/ci/docker/scripts/emscripten.sh`
* `appveyor.yml`

2019-05-29 14:04 UTC, alexcrichton commented
Updated!

2019-05-29 14:14 UTC, emilyalbini approved these changes

2019-05-29 14:14 UTC, pietroalbini commented
@bors r+ rollup

Thanks!

2019-05-30 14:56 UTC, merged