Prevent panic when sysroot cannot be computed
rust-lang/rust pull request #61459
Opened 2019-06-02 12:54 UTC by GuillaumeGomez

Fixes #61377.

cc @rotty @rust-lang/rustdoc 

r? @Manishearth

2019-06-02 14:35 UTC, ollie27 requested changes

2019-06-02 14:35 UTC, ollie27 commented on src/librustdoc/test.rs
> +        }),
This should just be `maybe_sysroot: options.maybe_sysroot.clone(),` which will let rustc find the sysroot if it wasn't passed as a command line attribute. Unless there's some reason rustdoc needs to call `current_exe` itself but I can't see any.

2019-06-02 14:35 UTC, ollie27 commented on src/librustdoc/test.rs
> +        }),
Again, this can just be `maybe_sysroot,`.

2019-06-09 21:57 UTC, GuillaumeGomez commented
Updated!

2019-06-10 07:06 UTC, bjorn3 commented on src/librustdoc/test.rs
> +        maybe_sysroot: maybe_sysroot,
```suggestion
        maybe_sysroot,
```

2019-06-10 09:04 UTC, GuillaumeGomez commented
Updated.

2019-06-14 16:09 UTC, QuietMisdreavus approved these changes
LGTM! Looks like passing `None` all the way down to rustc lets it use the proper calculations on OpenBSD.

I did some archaeology to see the history of the sysroot parameter. It looks like the `current_exe` logic was taken out of `core.rs` way back in https://github.com/rust-lang/rust/pull/19161, but that PR didn't touch `test.rs`, and the logic was carried through during the various IO refactorings over time. This brings the doctest functionality in-line with the rest of rustdoc, and the rest of rustc.

We don't have OpenBSD builders, do we? I'm wondering if there's a way we can test for this. 😕

2019-06-15 10:02 UTC, GuillaumeGomez commented
@rust-lang/infra Can we check on OpenBSD one way or another?

2019-06-29 20:29 UTC, GuillaumeGomez commented
Well, meanwhile, this PR is ready to go.

@bors: r=ollie27,bjorn3,QuietMisdreavus

2019-06-29 20:31 UTC, GuillaumeGomez commented
Maybe it'll work this time?

@bors: r=ollie27,bjorn3,QuietMisdreavus

2019-06-30 05:22 UTC, merged

2019-06-30 07:32 UTC, bjorn3 commented
@GuillaumeGomez Why did you include me in the `r=` list? Every other time I commented on a PR, I didnt get included.

2019-06-30 15:10 UTC, GuillaumeGomez commented
Well, you reviewed it so it seemed ok for me to include you.