Coherence test when a generic type param has a default value from an associated type
rust-lang/rust pull request #61535
Opened 2019-06-05 07:15 UTC by ohadravid

A followup on #61400.
Before `re_rebalance_coherence`, this fails to compile (even though it should be accepted).
`re_rebalance_coherence` had no direct test for this, and I wanted to (a) make sure it doesn't regress in the future and (b) get it on record that this is actually the intended behavior.

r? jonas-schievink

2019-06-05 07:15 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @alexcrichton (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2019-06-05 09:20 UTC, ohadravid commented
r? @jonas-schievink

2019-06-05 09:26 UTC, jonas-schievink commented
r? @nikomatsakis

2019-06-05 09:27 UTC, jonas-schievink approved these changes
Looks good to me, but I'll let Niko take a look as well since I don't really know much about this feature

2019-07-01 12:34 UTC, Dylan-DPC commented
ping from triage @nikomatsakis @jonas-schievink any updates on this?

2019-07-01 20:53 UTC, nikomatsakis requested changes

2019-07-01 20:53 UTC, nikomatsakis commented on src/test/run-pass/coherence/re-rebalance-coherence-default-generic-associated-type.rs
> +impl PartialEq<MyString> for LibCow<MyString> {
This test doesn't really *check* what the default works out to be, right? Should we do that?

2019-07-01 20:53 UTC, nikomatsakis commented on src/test/run-pass/coherence/re-rebalance-coherence-default-generic-associated-type.rs
> +// run-pass
Can we leave a comment elaborating what this test is trying to test?

2019-07-09 15:38 UTC, ohadravid commented
Hi @nikomatsakis!
Thanks for looking at this. I added a comment about what we are testing here.
I also added a check that we really get the expected type.

2019-07-11 17:03 UTC, nikomatsakis approved these changes

2019-07-11 17:03 UTC, nikomatsakis commented
@bors r+ rollup

2019-07-12 11:06 UTC, nikomatsakis commented
@bors r+

2019-07-12 18:38 UTC, lqd commented
@bors r=nikomatsakis rollup

2019-07-13 03:12 UTC, merged