libcore/pin: Minor grammar corrections for module documentation
rust-lang/rust pull request #61599
Opened 2019-06-06 19:40 UTC by laumann

This is by no means exhaustive, but I noticed a few grammatical errors
when reading the documentation, and decided just to push these.

Some standard rules/guidelines I followed:

 * Do not split infinitives, ie "not to move" instead of "to not move"

 * Do not use "since" when you want to say "because" or "as" - the word
   "since" has a temporal meaning

In addition:

 * Fix a small typo: "Similarily" should be "Similarly"

 * Delete double-spaces after full stop

2019-06-06 19:40 UTC, rust-highfive commented
r? @Mark-Simulacrum

(rust_highfive has picked a reviewer for you, use r? to override)

2019-06-06 19:42 UTC, Mark-Simulacrum commented
I don't feel comfortable reviewing this one way or another... randomly reassigning to r? @Centril

2019-06-06 20:15 UTC, Centril requested changes
Thanks! r=me rollup with changes below.

2019-06-06 20:15 UTC, Centril commented on src/libcore/pin.rs
> +//! [`DerefMut`] not to move out of their self parameter, and only ever to
```suggestion
//! [`DerefMut`] not to move out of their `self` parameter, and only ever to
```

2019-06-06 20:15 UTC, Centril commented on src/libcore/pin.rs
> +//! `bool`, `i32`, references) as well as types consisting solely of these
```suggestion
//! `bool`, `i32`, and references) as well as types consisting solely of these
```

2019-06-06 20:15 UTC, Centril commented on src/libcore/pin.rs
>  //! // Instead we use a raw pointer, though one which is known to not be null,
```suggestion
//! // Instead we use a raw pointer, though one which is known not to be null,
```

2019-06-07 07:55 UTC, laumann commented on src/libcore/pin.rs
>  //! // Instead we use a raw pointer, though one which is known to not be null,
Oh, I missed one :-) Thanks!

2019-06-07 07:57 UTC, laumann commented
@Centril My Github foo is not that strong, I have never used suggestions, if I use the UI to accept them, does that mean four individual commits? Would it then be better just to push you suggestions as one commit?

2019-06-07 08:44 UTC, Centril commented
@laumann GitHub has a "Add suggestion to batch" functionality if you want to do a single commit; otherwise doing it manually is fine also. Up to you. :)

2019-06-07 08:58 UTC, laumann commented
OK, will do, thanks!

2019-06-07 09:00 UTC, laumann commented on src/libcore/pin.rs
> +//! [`DerefMut`] not to move out of their self parameter, and only ever to
Fixed

2019-06-07 09:00 UTC, laumann commented on src/libcore/pin.rs
> +//! `bool`, `i32`, references) as well as types consisting solely of these
Fixed.

2019-06-07 09:00 UTC, laumann commented on src/libcore/pin.rs
>  //! // Instead we use a raw pointer, though one which is known to not be null,
Fixed.

2019-06-07 09:02 UTC, Centril approved these changes

2019-06-07 09:03 UTC, Centril commented
@bors r+ rollup

2019-06-07 17:44 UTC, merged