Support `impl Trait` in inlined documentation
rust-lang/rust pull request #61613
Opened 2019-06-07 08:05 UTC by sinkuu

`impl Trait` in argument position was not properly rendered when inlined from other crates. ([a live example on docs.rs](https://docs.rs/libp2p/0.8.1/libp2p/floodsub/struct.Floodsub.html#method.unsubscribe))

![old](https://user-images.githubusercontent.com/7091080/59089838-14ba9900-8946-11e9-830b-53b317bdecb4.png)
↓
![new](https://user-images.githubusercontent.com/7091080/59089844-16845c80-8946-11e9-9fe3-8998af9d73ce.png)

2019-06-07 08:26 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/206240477) ([raw log](https://api.travis-ci.com/v3/job/206240477/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:0efa6ae3:start=1559894987881585530,finish=1559894988615283313,duration=733697783
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---

[00:04:17] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:04:18] tidy error: /checkout/src/librustdoc/clean/mod.rs:1702: line longer than 100 chars
[00:04:22] some tidy checks failed
[00:04:22] 
[00:04:22] 
[00:04:22] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:22] 
[00:04:22] 
[00:04:22] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:22] Build completed unsuccessfully in 0:01:11
---
travis_time:end:01252620:start=1559895263298385339,finish=1559895263303144686,duration=4759347
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0af192c8
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:10f347cc
travis_time:start:10f347cc
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:0019eb18
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-07-06 17:25 UTC, ollie27 requested changes
Sorry for the late review.

Even with the `(i as u32)` -> `param.index` change I suggested there is still a problem with things like `pub fn h(_x: impl Iterator<Item = u8>) {}`, they render as:
![image](https://user-images.githubusercontent.com/7189418/60758962-5dcd3e00-a015-11e9-8336-4d94f795de23.png)
The issue is that rustdoc uses `simplify::where_clauses` to convert the equality predicates into type bindings so that needs to be run before moving where predicates that are actually part of impl traits into `cx.impl_trait_bounds`. We could leave fixing this to a follow up PR though.

2019-07-08 21:05 UTC, ollie27 commented
Looks good, thanks!

@bors r+

2019-07-09 02:47 UTC, Centril commented
Failed in https://github.com/rust-lang/rust/pull/62509#issuecomment-509465263, @bors r-

2019-07-09 02:50 UTC, Centril commented
@bors retry

2019-07-09 08:07 UTC, sinkuu commented
I guess test failure on one platform was caused by indeterminism of `HashMap` iteration, so I changed it to use `BTreeMap`.
Also a drive-by fix for ICE with `impl Trait` in type bounds.

2019-07-16 08:55 UTC, sinkuu commented
@ollie27 Could you re-approve?

2019-08-17 06:06 UTC, JohnCSimon commented
Ping from triage 
@sinkuu  - can you please fix the merge conflict so that @ollie27 can re-review? 
Thank you.

2019-08-19 11:10 UTC, sinkuu commented
Rebased.

2019-08-25 17:02 UTC, ollie27 commented
Let's give this another go.

@bors r+

2019-08-25 23:01 UTC, merged