librustc_errors: Add some more documentation
rust-lang/rust pull request #61686
Opened 2019-06-09 10:06 UTC by phansch

r? @estebank

2019-06-09 16:18 UTC, Centril requested changes
Mostly proof reading :)

2019-06-09 16:18 UTC, Centril commented on src/librustc_errors/lib.rs
> +//! Diagnostics creation and emission for rustc
```suggestion
//! Diagnostics creation and emission for `rustc`.
```

2019-06-09 16:18 UTC, Centril commented on src/librustc_errors/diagnostic_builder.rs
> +    pub(crate) fn new_with_code(handler: &'a Handler,
```suggestion
    crate fn new_with_code(handler: &'a Handler,
```

2019-06-09 16:18 UTC, Centril commented on src/librustc/session/config.rs
> +/// The type of diagnostics output to generate
```suggestion
/// The type of diagnostics output to generate.
```

2019-06-09 16:18 UTC, Centril commented on src/librustc/session/config.rs
> +        /// Render the JSON in a human readable way (with indents and newlines)
```suggestion
        /// Render the JSON in a human readable way (with indents and newlines).
```

2019-06-10 05:34 UTC, estebank commented
R=me with the comments addressed

2019-06-10 09:12 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/206688038) ([raw log](https://api.travis-ci.com/v3/job/206688038/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:21ad94c6:start=1560157429923116981,finish=1560157518466111594,duration=88542994613
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---
[00:06:24]    Compiling synstructure v0.10.2
[00:06:37]    Compiling rustc_macros v0.1.0 (/checkout/src/librustc_macros)
[00:06:44]    Compiling syntax_pos v0.0.0 (/checkout/src/libsyntax_pos)
[00:06:48]    Compiling rustc_errors v0.0.0 (/checkout/src/librustc_errors)
[00:06:48] error[E0658]: `crate` visibility modifier is experimental
[00:06:48]     |
[00:06:48]     |
[00:06:48] 351 |     crate fn new_with_code(handler: &'a Handler,
[00:06:48]     |
[00:06:48]     = note: for more information, see https://github.com/rust-lang/rust/issues/53120
[00:06:48]     = note: for more information, see https://github.com/rust-lang/rust/issues/53120
[00:06:48]     = help: add #![feature(crate_visibility_modifier)] to the crate attributes to enable
[00:06:48] error: aborting due to previous error
[00:06:48] 
[00:06:48] For more information about this error, try `rustc --explain E0658`.
[00:06:48] error: Could not compile `rustc_errors`.
---
travis_time:end:00415a31:start=1560157949288741887,finish=1560157949293517436,duration=4775549
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:00034b17
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:08bbe3f3
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/a
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-06-10 11:39 UTC, phansch commented
@bors r=estebank

2019-06-10 13:44 UTC, Centril commented
@bors r=estebank

2019-06-12 02:13 UTC, merged