suggest tuple struct syntax
rust-lang/rust pull request #61782
Opened 2019-06-12 19:11 UTC by Electron-libre

refs #57242

2019-06-12 19:11 UTC, rust-highfive commented
r? @petrochenkov

(rust_highfive has picked a reviewer for you, use r? to override)

2019-06-14 17:26 UTC, petrochenkov commented on src/librustc_typeck/check/mod.rs
> +                    format!("`{adt}` is a tuple struct, use the appropriate syntax: `{adt}()`",
```suggestion
                    format!("`{adt}` is a tuple {kind_name}, use the appropriate syntax: `{adt}(/* fields */)`",
```

2019-06-14 17:28 UTC, petrochenkov commented
LGTM.
r? @estebank on whether `/* fields */` is good enough or should be replaced with an actual fields list.

2019-06-17 12:28 UTC, Electron-libre commented
IMHO providing the constructor signature would be a better hint.
Eg: 
```use function constructor MyFoo(u32, String)```

Since only type and order matter for "tuple" syntax.

2019-06-17 14:06 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/208608997) ([raw log](https://api.travis-ci.com/v3/job/208608997/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:129dad93:start=1560780075259020834,finish=1560780077811468223,duration=2552447389
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---
####################                                                      28.2%
######################################################################## 100.0%
[00:03:37] extracting /checkout/obj/build/cache/2019-05-23/cargo-beta-x86_64-unknown-linux-gnu.tar.gz
[00:03:37]     Updating crates.io index
[00:04:34] error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
[00:04:34] Build completed unsuccessfully in 0:01:10
[00:04:34] Makefile:69: recipe for target 'prepare' failed
[00:04:34] make: *** [prepare] Error 1
[00:04:35] Command failed. Attempt 2/5:
[00:04:35] Command failed. Attempt 2/5:
[00:04:35]     Updating crates.io index
[00:04:38] error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
[00:04:38] Build completed unsuccessfully in 0:00:02
[00:04:38] make: *** [prepare] Error 1
[00:04:38] Makefile:69: recipe for target 'prepare' failed
[00:04:40] Command failed. Attempt 3/5:
[00:04:40] Command failed. Attempt 3/5:
[00:04:40]     Updating crates.io index
[00:04:41] error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
[00:04:41] Build completed unsuccessfully in 0:00:00
[00:04:41] make: *** [prepare] Error 1
[00:04:41] Makefile:69: recipe for target 'prepare' failed
[00:04:44] Command failed. Attempt 4/5:
[00:04:44] Command failed. Attempt 4/5:
[00:04:44]     Updating crates.io index
[00:04:44] error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
[00:04:44] Build completed unsuccessfully in 0:00:00
[00:04:44] Makefile:69: recipe for target 'prepare' failed
[00:04:44] make: *** [prepare] Error 1
[00:04:48] Command failed. Attempt 5/5:
[00:04:48] Command failed. Attempt 5/5:
[00:04:48]     Updating crates.io index
[00:04:49] error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
[00:04:49] Build completed unsuccessfully in 0:00:00
[00:04:49] make: *** [prepare] Error 1
[00:04:49] Makefile:69: recipe for target 'prepare' failed
[00:04:49] The command has failed after 5 attempts.
---
travis_time:end:03f52c23:start=1560780379890391000,finish=1560780379896687946,duration=6296946
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:1543e950
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:272db648
travis_time:start:272db648
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:306fe304
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-06-17 15:17 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/208632264) ([raw log](https://api.travis-ci.com/v3/job/208632264/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:02588a40:start=1560783880388921204,finish=1560783882818259564,duration=2429338360
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---

[00:07:48] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:07:49] tidy error: /checkout/src/librustc_typeck/check/mod.rs:3653: line longer than 100 chars
[00:07:53] some tidy checks failed
[00:07:53] 
[00:07:53] 
[00:07:53] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:07:53] 
[00:07:53] 
[00:07:53] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:07:53] Build completed unsuccessfully in 0:01:15
---
travis_time:end:097e3d8b:start=1560784369278083903,finish=1560784369283211201,duration=5127298
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0481c130
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:0abe7ae4
travis_time:start:0abe7ae4
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:01f7c820
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-06-17 16:54 UTC, estebank commented
The force push included  src/tools/miri and src/tools/clippy. (It shouldn't.)

2019-06-17 17:52 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/208668073) ([raw log](https://api.travis-ci.com/v3/job/208668073/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:2bdbdaa6:start=1560790498964597622,finish=1560790499813618207,duration=849020585
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---
[00:55:04] .................................................................................................... 2500/5680
[00:55:08] .................................................................................................... 2600/5680
[00:55:12] .................................................................................................... 2700/5680
[00:55:16] .................................................................................................... 2800/5680
[00:55:20] ....................................................................................F............... 2900/5680
[00:55:28] .................................................................................................... 3100/5680
[00:55:30] .................................................................................................... 3200/5680
[00:55:34] .................................................................................................... 3300/5680
[00:55:38] .........................................................................................i.......... 3400/5680
[00:55:38] .........................................................................................i.......... 3400/5680
[00:55:41] .................................................................................................... 3500/5680
[00:55:44] ...............................................................ii...i..ii........................... 3600/5680
[00:55:48] .................................................................................................... 3700/5680
[00:55:52] .................................................................................................... 3800/5680
[00:55:55] .........................................................................ii...................F..... 3900/5680
[00:56:00] .................................................................................................... 4100/5680
[00:56:02] ..........................................................i......................................... 4200/5680
[00:56:04] .................................................................................................... 4300/5680
[00:56:13] .................................................................................................... 4400/5680
---
[00:57:05] diff of stderr:
[00:57:05] 
[00:57:05] 2   --> $DIR/issue-4736.rs:4:26
[00:57:05] 3    |
[00:57:05] 4 LL |     let z = NonCopyable{ p: () };
[00:57:05] -    |                          |
[00:57:05] -    |                          field does not exist
[00:57:05] -    |                          field does not exist
[00:57:05] -    |                          `NonCopyable` is a tuple struct, use the appropriate syntax: `NonCopyable(/* fields */)`
[00:57:05] +    |                          ^ help: a field with a similar name exists: `0`
[00:57:05] 10 error: aborting due to previous error
[00:57:05] 11 
[00:57:05] 
[00:57:05] 
[00:57:05] 
[00:57:05] The actual stderr differed from the expected stderr.
[00:57:05] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-4736/issue-4736.stderr
[00:57:05] To update references, rerun the tests and pass the `--bless` flag
[00:57:05] To only update this specific test, also pass `--test-args issues/issue-4736.rs`
[00:57:05] error: 1 errors occurred comparing output.
[00:57:05] status: exit code: 1
[00:57:05] status: exit code: 1
[00:57:05] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/issues/issue-4736.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-4736" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-4736/auxiliary" "-A" "unused"
[00:57:05] ------------------------------------------
[00:57:05] 
[00:57:05] ------------------------------------------
[00:57:05] stderr:
[00:57:05] stderr:
[00:57:05] ------------------------------------------
[00:57:05] error[E0560]: struct `NonCopyable` has no field named `p`
[00:57:05]   --> /checkout/src/test/ui/issues/issue-4736.rs:4:26
[00:57:05]    |
[00:57:05] LL |     let z = NonCopyable{ p: () }; //~ ERROR struct `NonCopyable` has no field named `p`
[00:57:05]    |                          ^ help: a field with a similar name exists: `0`
[00:57:05] error: aborting due to previous error
[00:57:05] 
[00:57:05] For more information about this error, try `rustc --explain E0560`.
[00:57:05] 
---
[00:57:05] diff of stderr:
[00:57:05] 
[00:57:05] 2   --> $DIR/numeric-fields.rs:4:15
[00:57:05] 3    |
[00:57:05] 4 LL |     let s = S{0b1: 10, 0: 11};
[00:57:05] -    |               |
[00:57:05] -    |               field does not exist
[00:57:05] -    |               field does not exist
[00:57:05] -    |               `S` is a tuple struct, use the appropriate syntax: `S(/* fields */)`
[00:57:05] +    |               ^^^ `S` does not have this field
[00:57:05] +    = note: available fields are: `0`, `1`
[00:57:05] 9 
[00:57:05] 10 error[E0026]: struct `S` does not have a field named `0x1`
[00:57:05] 11   --> $DIR/numeric-fields.rs:7:17
[00:57:05] 11   --> $DIR/numeric-fields.rs:7:17
[00:57:05] 
[00:57:05] 
[00:57:05] The actual stderr differed from the expected stderr.
[00:57:05] Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/numeric/numeric-fields/numeric-fields.stderr
[00:57:05] To update references, rerun the tests and pass the `--bless` flag
[00:57:05] To only update this specific test, also pass `--test-args numeric/numeric-fields.rs`
[00:57:05] error: 1 errors occurred comparing output.
[00:57:05] status: exit code: 1
[00:57:05] status: exit code: 1
[00:57:05] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/numeric/numeric-fields.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/numeric/numeric-fields" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/numeric/numeric-fields/auxiliary" "-A" "unused"
[00:57:05] ------------------------------------------
[00:57:05] 
[00:57:05] ------------------------------------------
[00:57:05] stderr:
[00:57:05] stderr:
[00:57:05] ------------------------------------------
[00:57:05] error[E0560]: struct `S` has no field named `0b1`
[00:57:05]   --> /checkout/src/test/ui/numeric/numeric-fields.rs:4:15
[00:57:05]    |
[00:57:05] LL |     let s = S{0b1: 10, 0: 11};
[00:57:05]    |               ^^^ `S` does not have this field
[00:57:05]    = note: available fields are: `0`, `1`
[00:57:05] 
[00:57:05] error[E0026]: struct `S` does not have a field named `0x1`
[00:57:05]   --> /c [...]

2019-06-17 18:24 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/208690631) ([raw log](https://api.travis-ci.com/v3/job/208690631/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:2d0b9c94:start=1560794780794013296,finish=1560794783072827066,duration=2278813770
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---

[00:05:16] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:05:16] tidy error: /checkout/src/librustc_typeck/check/expr.rs:1223: line longer than 100 chars
[00:05:21] some tidy checks failed
[00:05:21] 
[00:05:21] 
[00:05:21] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:05:21] 
[00:05:21] 
[00:05:21] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:05:21] Build completed unsuccessfully in 0:01:13
---
travis_time:end:00094500:start=1560795116247773805,finish=1560795116252577897,duration=4804092
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:0007b520
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:125ec88a
travis_time:start:125ec88a
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:00a9b543
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-06-17 18:49 UTC, estebank commented
```
src/librustc_typeck/check/expr.rs:1223: line longer than 100 chars
```

2019-06-17 19:04 UTC, estebank requested changes
Ideally we would try to use a structured suggestion that gives out the _correct_ code (which is why @petrochenkov was asking for my input), but I think this is a good first pass at a solution which can be improved upon down the line.

Left some nitpicks inline that shouldn't be too hard to address.

2019-06-17 19:08 UTC, estebank commented
> IMHO providing the constructor signature would be a better hint.

In order to do so you would need to modify this code [to not emit one error per field](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=dc3d624c29ac4594978de5dda36dedda), but rather per invocation, and only once you figure out you have the correct amount of fields (and the correct types for them!) you can emit one error with the structured suggestion. I don't want _perfect_ be enemy of the _good enough that will make things materially better_ :)

2019-06-18 20:37 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/209067440) ([raw log](https://api.travis-ci.com/v3/job/209067440/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:10e81a0e:start=1560888453995759055,finish=1560888546741518936,duration=92745759881
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---

[00:03:54] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:03:54] tidy error: /checkout/src/librustc_typeck/check/expr.rs:1222: line longer than 100 chars
[00:03:59] some tidy checks failed
[00:03:59] 
[00:03:59] 
[00:03:59] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:03:59] 
[00:03:59] 
[00:03:59] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:03:59] Build completed unsuccessfully in 0:01:15
---
travis_time:end:0005a18c:start=1560888797492332905,finish=1560888797497269631,duration=4936726
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:1a6d32c8
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:036ae97d
travis_time:start:036ae97d
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:0e7ba4bf
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-06-19 08:29 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/209198508) ([raw log](https://api.travis-ci.com/v3/job/209198508/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:0bd2e350:start=1560931762015198910,finish=1560931854193627669,duration=92178428759
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---

[00:03:56] travis_fold:start:tidy
travis_time:start:tidy
tidy check
[00:03:57] tidy error: /checkout/src/librustc_typeck/check/expr.rs:1223: line longer than 100 chars
[00:04:01] some tidy checks failed
[00:04:01] 
[00:04:01] 
[00:04:01] command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor" "--quiet"
[00:04:01] 
[00:04:01] 
[00:04:01] failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
[00:04:01] Build completed unsuccessfully in 0:01:13
---
travis_time:end:00dc648c:start=1560932105448609953,finish=1560932105453281272,duration=4671319
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:088e74ee
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:08fe840e
travis_time:start:08fe840e
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:0c21b74c
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-06-19 09:11 UTC, Electron-libre commented on src/librustc_typeck/check/expr.rs
> +                    format!("`{adt}` is a tuple {kind_name}, use the appropriate syntax: `{adt}(/* fields */)`", adt=ty, kind_name=kind_name)
done

2019-06-19 09:11 UTC, Electron-libre commented on src/librustc_typeck/check/expr.rs
> +                                                                   skip_fields.collect()) {
done

2019-06-19 09:11 UTC, Electron-libre commented on src/librustc_typeck/check/expr.rs
> +                                                       ty, variant.ident));
done

2019-06-19 09:11 UTC, Electron-libre commented on src/test/ui/numeric/numeric-fields.stderr
> +   |               `S` is a tuple struct, use the appropriate syntax: `S(/* fields */)`
done

2019-06-19 15:17 UTC, estebank approved these changes
R=me once the nitpicks have been addressed.

2019-06-19 15:17 UTC, estebank commented on src/librustc_typeck/check/expr.rs
> +                        "`{adt}` is a tuple {kind_name},\
There's a space missing after the comma. You can see it more clearly in the street output.

2019-06-19 15:17 UTC, estebank commented on src/librustc_typeck/check/expr.rs
> +            err.emit();
Indent `err.emit()` aligned to the scope it is in.

2019-06-19 17:52 UTC, Electron-libre commented
@bors r=estebank

2019-06-19 21:38 UTC, estebank commented
@bors r+ rollup

2019-06-20 10:40 UTC, merged