Use a sharded dep node to dep node index map
rust-lang/rust pull request #61845
Opened 2019-06-14 18:39 UTC by Zoxc

This reduces lock contention a bit for incremental compilation. https://github.com/rust-lang/rust/pull/60035 gets rid of the locks, but is much larger and probably won't land until @michaelwoerister returns. This reduces clean incremental times for `winapi` from 18.37s to 16.43s on 16 threads / 8 cores.

Based on https://github.com/rust-lang/rust/pull/61779.

r? @eddyb

2019-06-14 18:54 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/208216832) ([raw log](https://api.travis-ci.com/v3/job/208216832/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:0559caac:start=1560537662320006111,finish=1560537824015264745,duration=161695258634
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---
[00:07:21]    Compiling syntax_pos v0.0.0 (/checkout/src/libsyntax_pos)
[00:07:25]    Compiling rustc_errors v0.0.0 (/checkout/src/librustc_errors)
[00:07:25]    Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
[00:08:35]    Compiling syntax_ext v0.0.0 (/checkout/src/libsyntax_ext)
[00:08:49] error[E0599]: no method named `borrow` found for type `dep_graph::graph::CurrentDepGraph` in the current scope
[00:08:49]    --> src/librustc/dep_graph/graph.rs:636:33
[00:08:49] 636 |                                .borrow()
[00:08:49]     |                                 ^^^^^^
[00:08:49] ...
[00:08:49] ...
[00:08:49] 965 | pub(super) struct CurrentDepGraph {
[00:08:49]     | --------------------------------- method `borrow` not found for this
[00:08:49]     = help: items from traits can only be used if the trait is in scope
[00:08:49]     = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
[00:08:49]             `use std::borrow::Borrow;`
[00:08:49] 
[00:08:49] 
[00:08:49] error[E0599]: no method named `lock` found for type `rustc_data_structures::sharded::Sharded<std::vec::Vec<dep_graph::graph::DepNodeData>>` in the current scope
[00:08:49]     --> src/librustc/dep_graph/graph.rs:1159:58
[00:08:49]      |
[00:08:49] 1159 |                             let data = self.current.data.lock();
[00:08:49] 
[00:09:07] error: aborting due to 2 previous errors
[00:09:07] 
[00:09:07] For more information about this error, try `rustc --explain E0599`.
---
travis_time:end:179f1c10:start=1560538381243750175,finish=1560538381248333700,duration=4583525
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:018330ae
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:065d8e3e
travis_time:start:065d8e3e
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:1a556485
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-06-14 19:36 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed on Travis](https://travis-ci.com/rust-lang/rust/jobs/208227264) ([raw log](https://api.travis-ci.com/v3/job/208227264/log.txt)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
travis_time:end:02b22433:start=1560540217176911629,finish=1560540218140250375,duration=963338746
$ git checkout -qf FETCH_HEAD
travis_fold:end:git.checkout

Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
$ export SCCACHE_BUCKET=rust-lang-ci-sccache2
$ export SCCACHE_REGION=us-west-1
$ export GCP_CACHE_BUCKET=rust-lang-ci-cache
$ export AWS_ACCESS_KEY_ID=AKIA46X5W6CZEJZ6XT55
---
[00:07:19]    Compiling syntax_pos v0.0.0 (/checkout/src/libsyntax_pos)
[00:07:23]    Compiling rustc_errors v0.0.0 (/checkout/src/librustc_errors)
[00:07:23]    Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
[00:08:35]    Compiling syntax_ext v0.0.0 (/checkout/src/libsyntax_ext)
[00:08:49] error[E0599]: no method named `lock` found for type `rustc_data_structures::sharded::Sharded<std::vec::Vec<dep_graph::graph::DepNodeData>>` in the current scope
[00:08:49]     --> src/librustc/dep_graph/graph.rs:1159:58
[00:08:49]      |
[00:08:49] 1159 |                             let data = self.current.data.lock();
[00:08:49] 
[00:09:07] error: aborting due to previous error
[00:09:07] 
[00:09:07] For more information about this error, try `rustc --explain E0599`.
---
travis_time:end:01306e58:start=1560540777840848403,finish=1560540777845541415,duration=4693012
travis_fold:end:after_failure.3
travis_fold:start:after_failure.4
travis_time:start:07302b98
$ ln -s . checkout && for CORE in obj/cores/core.*; do EXE=$(echo $CORE | sed 's|obj/cores/core\.[0-9]*\.!checkout!\(.*\)|\1|;y|!|/|'); if [ -f "$EXE" ]; then printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" "$CORE"; gdb --batch -q -c "$CORE" "$EXE" -iex 'set auto-load off' -iex 'dir src/' -iex 'set sysroot .' -ex bt -ex q; echo travis_fold":"end:crashlog; fi; done || true
travis_fold:end:after_failure.4
travis_fold:start:after_failure.5
travis_time:start:0344e214
travis_time:start:0344e214
$ cat ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers || true
cat: ./obj/build/x86_64-unknown-linux-gnu/native/asan/build/lib/asan/clang_rt.asan-dynamic-i386.vers: No such file or directory
travis_fold:end:after_failure.5
travis_fold:start:after_failure.6
travis_time:start:2a913724
$ dmesg | grep -i kill
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-06-21 02:30 UTC, Zoxc commented on src/librustc/dep_graph/graph.rs
> +            node_count: AtomicU64::new(0),
This should use the node count from the previous graph.

2019-06-22 20:27 UTC, Zoxc commented
@bors try

2019-06-22 22:57 UTC, Zoxc commented
@rust-timer build 0375265c8567d1c4486ee7705d209471ab694578

2019-06-22 22:57 UTC, rust-timer commented
Success: Queued 0375265c8567d1c4486ee7705d209471ab694578 with parent 4a365a29d64bec75d107214319a129ba68fc12a3, [comparison URL](https://perf.rust-lang.org/compare.html?start=4a365a29d64bec75d107214319a129ba68fc12a3&end=0375265c8567d1c4486ee7705d209471ab694578).

2019-06-23 07:01 UTC, rust-timer commented
Finished benchmarking try commit 0375265c8567d1c4486ee7705d209471ab694578, [comparison URL](https://perf.rust-lang.org/compare.html?start=4a365a29d64bec75d107214319a129ba68fc12a3&end=0375265c8567d1c4486ee7705d209471ab694578).

2019-07-11 13:01 UTC, eddyb commented
r? @Gankro or @stjepang

2019-07-11 13:03 UTC, eddyb commented
Oh, @aturon might want to take this (https://github.com/rust-lang/rust/pull/61873#issuecomment-509334053).

2019-07-11 19:13 UTC, Gankro commented
Also not interested in reviewing any more of these.

2019-07-12 08:25 UTC, eddyb commented
r? @aturon then

2019-07-25 05:39 UTC, rust-highfive commented
The job `mingw-check` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=4206&view=logs&jobId=4f922444-fdfe-5dcf-b824-02f86439ef14) ([raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4206/logs/45)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-07-25T05:26:35.4271226Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-07-25T05:26:35.4489042Z ##[command]git config gc.auto 0
2019-07-25T05:26:35.4553778Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-07-25T05:26:36.2061320Z ##[command]git config --get-all http.proxy
2019-07-25T05:26:36.2064485Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/61845/merge:refs/remotes/pull/61845/merge
---
2019-07-25T05:27:09.5690867Z do so (now or later) by using -b with the checkout command again. Example:
2019-07-25T05:27:09.5690896Z 
2019-07-25T05:27:09.5691116Z   git checkout -b <new-branch-name>
2019-07-25T05:27:09.5691145Z 
2019-07-25T05:27:09.5691193Z HEAD is now at aab8eb087 Merge e0264ab811e4435a9b83db46886b6b8bc11c194b into 03f19f7ff128a3b01eeab3f87f04cce22883f006
2019-07-25T05:27:09.5827478Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-07-25T05:27:09.5830468Z ==============================================================================
2019-07-25T05:27:09.5830546Z Task         : Bash
2019-07-25T05:27:09.5830594Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-07-25T05:34:13.5354437Z     Checking rustc_errors v0.0.0 (/checkout/src/librustc_errors)
2019-07-25T05:34:14.6401157Z     Checking fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2019-07-25T05:34:26.0080128Z     Checking syntax_ext v0.0.0 (/checkout/src/libsyntax_ext)
2019-07-25T05:34:33.9531396Z error[E0308]: mismatched types
2019-07-25T05:34:33.9532530Z     --> src/librustc/dep_graph/graph.rs:1031:40
2019-07-25T05:34:33.9533239Z      |
2019-07-25T05:34:33.9533741Z 1031 |             node_count: AtomicU64::new(prev_graph_node_count),
2019-07-25T05:34:33.9534317Z      |                                        ^^^^^^^^^^^^^^^^^^^^^ expected u64, found usize
2019-07-25T05:34:33.9534813Z help: you can convert an `usize` to `u64` and panic if the converted value wouldn't fit
2019-07-25T05:34:33.9535234Z      |
2019-07-25T05:34:33.9535744Z 1031 |             node_count: AtomicU64::new(prev_graph_node_count.try_into().unwrap()),
2019-07-25T05:34:33.9537032Z 
2019-07-25T05:34:47.8986309Z error: aborting due to previous error
2019-07-25T05:34:47.8986561Z 
2019-07-25T05:34:47.8987133Z For more information about this error, try `rustc --explain E0308`.
2019-07-25T05:34:47.8987133Z For more information about this error, try `rustc --explain E0308`.
2019-07-25T05:34:48.0701845Z error: Could not compile `rustc`.
2019-07-25T05:34:48.0701951Z 
2019-07-25T05:34:48.0702412Z To learn more, run the command again with --verbose.
2019-07-25T05:34:48.0725470Z command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "check" "--target" "x86_64-unknown-linux-gnu" "-j" "2" "--release" "--color" "always" "--features" "" "--manifest-path" "/checkout/src/rustc/Cargo.toml" "--message-format" "json"
2019-07-25T05:34:48.0741538Z failed to run: /checkout/obj/build/bootstrap/debug/bootstrap check
2019-07-25T05:34:48.0741606Z Build completed unsuccessfully in 0:04:36
2019-07-25T05:34:48.0741606Z Build completed unsuccessfully in 0:04:36
2019-07-25T05:34:48.7510405Z ##[error]Bash exited with code '1'.
2019-07-25T05:34:48.7542328Z ##[section]Starting: Checkout
2019-07-25T05:34:48.7544535Z ==============================================================================
2019-07-25T05:34:48.7544614Z Task         : Get sources
2019-07-25T05:34:48.7544663Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-07-25 07:27 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=4213&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4213/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-07-25T06:13:33.7899502Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-07-25T06:13:33.8096082Z ##[command]git config gc.auto 0
2019-07-25T06:13:33.8158736Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-07-25T06:13:33.8215066Z ##[command]git config --get-all http.proxy
2019-07-25T06:13:33.8356581Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/61845/merge:refs/remotes/pull/61845/merge
---
2019-07-25T06:14:07.9861684Z do so (now or later) by using -b with the checkout command again. Example:
2019-07-25T06:14:07.9861714Z 
2019-07-25T06:14:07.9862081Z   git checkout -b <new-branch-name>
2019-07-25T06:14:07.9862127Z 
2019-07-25T06:14:07.9862172Z HEAD is now at fec211d64 Merge 9e4488d524eb0caff22b578ff8928e89136d3f7e into 185b9acb66438894596f3c40d2ae4c6f7deeb8ab
2019-07-25T06:14:08.0003858Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-07-25T06:14:08.0007109Z ==============================================================================
2019-07-25T06:14:08.0007161Z Task         : Bash
2019-07-25T06:14:08.0007202Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-07-25T07:14:05.3742669Z .................................................................................................... 200/5856
2019-07-25T07:14:09.5324265Z .................................................................................................... 300/5856
2019-07-25T07:14:13.1935834Z .................................................................................................... 400/5856
2019-07-25T07:14:16.8884371Z .................................................................................................... 500/5856
2019-07-25T07:14:20.6887015Z ........................................................................i........................... 600/5856
2019-07-25T07:14:29.5323264Z .................................................................................................... 800/5856
2019-07-25T07:14:35.0581985Z .................................................................................................... 900/5856
2019-07-25T07:14:40.0116315Z ...................................................................................................i 1000/5856
2019-07-25T07:14:40.0116315Z ...................................................................................................i 1000/5856
2019-07-25T07:14:45.5662024Z ...........i........................................................................................ 1100/5856
2019-07-25T07:14:49.5681563Z .............................iiiii.................................................................. 1200/5856
2019-07-25T07:14:55.4942642Z .................................................................................................... 1400/5856
2019-07-25T07:14:58.1916973Z .................................................................................................... 1500/5856
2019-07-25T07:15:01.9460061Z .................................................................................................... 1600/5856
2019-07-25T07:15:04.6279437Z .................................................................................................... 1700/5856
2019-07-25T07:15:04.6279437Z .................................................................................................... 1700/5856
2019-07-25T07:15:08.0703268Z .....................................................................i.............................. 1800/5856
2019-07-25T07:15:16.5206098Z .................................................................................................... 2000/5856
2019-07-25T07:15:20.7511659Z .................................................................................................... 2100/5856
2019-07-25T07:15:24.4607624Z .................................................................................................... 2200/5856
2019-07-25T07:15:24.4607624Z .................................................................................................... 2200/5856
2019-07-25T07:15:28.3120926Z .....................................................i.............................................. 2300/5856
2019-07-25T07:15:38.0340973Z .................................................................................................... 2500/5856
2019-07-25T07:15:42.1128567Z .................................................................................................... 2600/5856
2019-07-25T07:15:47.1569461Z .................................................................................................... 2700/5856
2019-07-25T07:15:51.0323972Z .................................................................................................... 2800/5856
2019-07-25T07:15:51.0323972Z .................................................................................................... 2800/5856
2019-07-25T07:15:56.2181948Z .................................................................................................... 2900/5856
2019-07-25T07:16:00.7176942Z .................................................................................................... 3000/5856
2019-07-25T07:16:05.3025657Z .................................................................................................... 3100/5856
2019-07-25T07:16:10.6106449Z .................................................................................................... 3200/5856
2019-07-25T07:16:14.1599919Z .................................................................................................... 3300/5856
2019-07-25T07:16:17.8882014Z .................................................................................................... 3400/5856
2019-07-25T07:16:23.0297651Z .................................................................................................... 3500/5856
2019-07-25T07:16:26.7387553Z .....................i.............................................................................. 3600/5856
2019-07-25T07:16:30.8203721Z ..............................................................................................ii...i 3700/5856
2019-07-25T07:16:34.6230073Z ..ii................................................................................................ 3800/5856
2019-07-25T07:16:43.4033628Z .................................................................................................... 4000/5856
2019-07-25T07:16:43.4033628Z .................................................................................................... 4000/5856
2019-07-25T07:16:47.2585204Z .............ii..................................................................................... 4100/5856
2019-07-25T07:16:49.2426370Z ..................................i................................................................. 4200/5856
2019-07-25T07:16:51.4290706Z .................................................................................................... 4300/5856
2019-07-25T07:16:53.7800492Z .i.................................................................................................. 4400/5856
2019-07-25T07:17:15.7361163Z .................................................................................................... 4600/5856
2019-07-25T07:17:19.3398227Z .. [...]

2019-08-02 19:59 UTC, ProgrammaticNajel commented
Ping from triage. @aturon any updates on this?

2019-08-10 08:17 UTC, Dylan-DPC commented
Can anyone from @rust-lang/compiler review this?

2019-08-10 08:25 UTC, eddyb commented
r? @stjepang

2019-08-17 07:04 UTC, JohnCSimon commented
Ping from triage 
@Zoxc This PR now has a conflict, but it should be ready for review after that.

Thanks.

2019-08-20 20:33 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=6403&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/6403/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-08-20T19:17:10.9322297Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-08-20T19:17:10.9505458Z ##[command]git config gc.auto 0
2019-08-20T19:17:10.9590177Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-08-20T19:17:10.9646735Z ##[command]git config --get-all http.proxy
2019-08-20T19:17:10.9776026Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/61845/merge:refs/remotes/pull/61845/merge
---
2019-08-20T19:17:45.0874095Z do so (now or later) by using -b with the checkout command again. Example:
2019-08-20T19:17:45.0874143Z 
2019-08-20T19:17:45.0874349Z   git checkout -b <new-branch-name>
2019-08-20T19:17:45.0874379Z 
2019-08-20T19:17:45.0874443Z HEAD is now at 30dd50369 Merge 92e65d020012d49ae8e5645650f4e071785a869e into 5a56e05abd34e1936df74625c1f40cb6fee0cd4a
2019-08-20T19:17:45.1049880Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-08-20T19:17:45.1052703Z ==============================================================================
2019-08-20T19:17:45.1052778Z Task         : Bash
2019-08-20T19:17:45.1052823Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-08-20T20:21:26.6200843Z .................................................................................................... 1500/8943
2019-08-20T20:21:32.3092467Z .................................................................................................... 1600/8943
2019-08-20T20:21:45.5922109Z .......................................i...............i............................................ 1700/8943
2019-08-20T20:21:53.9337292Z .................................................................................................... 1800/8943
2019-08-20T20:22:08.6248851Z ...............................iiiii................................................................ 1900/8943
2019-08-20T20:22:19.5497359Z .................................................................................................... 2100/8943
2019-08-20T20:22:22.2125451Z .................................................................................................... 2200/8943
2019-08-20T20:22:27.0158447Z .................................................................................................... 2300/8943
2019-08-20T20:22:34.2099726Z .................................................................................................... 2400/8943
---
2019-08-20T20:25:37.6496204Z ...................i...............i................................................................ 4700/8943
2019-08-20T20:25:49.4777826Z .................................................................................................... 4800/8943
2019-08-20T20:25:55.9101756Z .................................................................................................... 4900/8943
2019-08-20T20:26:07.2032812Z .................................................................................................... 5000/8943
2019-08-20T20:26:12.4576608Z ii.ii............................................................................................... 5100/8943
2019-08-20T20:26:27.3633338Z .................................................................................................... 5300/8943
2019-08-20T20:26:34.4323112Z ........................................................i........................................... 5400/8943
2019-08-20T20:26:41.5657976Z .................................................................................................... 5500/8943
2019-08-20T20:26:51.2874115Z .................................................................................................... 5600/8943
2019-08-20T20:26:51.2874115Z .................................................................................................... 5600/8943
2019-08-20T20:27:00.7943801Z .................................................ii...i..ii...........i............................. 5700/8943
2019-08-20T20:27:23.6956546Z .................................................................................................... 5900/8943
2019-08-20T20:27:28.6945815Z .................................................................................................... 6000/8943
2019-08-20T20:27:28.6945815Z .................................................................................................... 6000/8943
2019-08-20T20:27:39.9151671Z ..................................................i..ii............................................. 6100/8943
2019-08-20T20:28:03.8439469Z ................................................................................................i... 6300/8943
2019-08-20T20:28:06.1258736Z .................................................................................................... 6400/8943
2019-08-20T20:28:08.4279931Z ....................................................................i............................... 6500/8943
2019-08-20T20:28:11.3911743Z .................................................................................................... 6600/8943
---
2019-08-20T20:32:58.4142441Z  finished in 21.839
2019-08-20T20:32:58.4346199Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-20T20:32:58.6033549Z 
2019-08-20T20:32:58.6033857Z running 148 tests
2019-08-20T20:33:01.9319396Z i....iii......iii..iiii....i............................i..i..................i....i.........ii.i.i. 100/148
2019-08-20T20:33:03.9228603Z .iiii..............i.........iii.i......ii......
2019-08-20T20:33:03.9232234Z 
2019-08-20T20:33:03.9233178Z  finished in 5.488
2019-08-20T20:33:03.9412115Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-20T20:33:04.1042599Z 
---
2019-08-20T20:33:06.2015285Z  finished in 2.259
2019-08-20T20:33:06.2208077Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-20T20:33:06.3813765Z 
2019-08-20T20:33:06.3813960Z running 9 tests
2019-08-20T20:33:06.3815195Z iiiiiiiii
2019-08-20T20:33:06.3815555Z 
2019-08-20T20:33:06.3815596Z  finished in 0.160
2019-08-20T20:33:06.3993351Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-08-20T20:33:06.5653941Z 
2019-08-20T20:33:06.5653941Z 
2019-08-20T20:33:06.5654185Z running 104 tests
2019-08-20T20:33:23.7044268Z .....F.........F....F.FFFFFFFFFFFFFFFFFFFFFFFFF...F.......F.F..........F.F...F....................F. 100/104
2019-08-20T20:33:24.2992183Z F.FF
2019-08-20T20:33:24.3002891Z 
2019-08-20T20:33:24.3003389Z ---- [incremental] incremental/change_name_of_static_in_fn.rs stdout ----
2019-08-20T20:33:24.3003451Z 
2019-08-20T20:33:24.3003451Z 
2019-08-20T20:33:24.3003532Z error in revision `rpass3`: compilation failed!
2019-08-20T20:33:24.3003580Z status: exit code: 101
2019-08-20T20:33:24.3004576Z command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/incremental/change_name_of_static_in_fn.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--cfg" "rpass3" "-C" "incremental=/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental/change_name_of_static_in_fn/change_name_of_static_in_fn.inc" "-Z" "incremental-verify-ich" "-Z" "incremental-q [...]

2019-08-28 16:40 UTC, Alexendoo commented
Ping from triage, looks like the earlier `r?` didn't work, but have you had a chance to look at this @stjepang?

2019-09-07 16:22 UTC, JohnCSimon commented
Ping from triage
@Zoxc @aturon @stjepang 
Hi! 
This has sat idle for over a week. What else needs to happen for this pr?

Thanks

2019-09-22 11:25 UTC, JohnTitor commented
Ping from triage: @aturon @stjepang @Zoxc any updates on this?

2019-09-30 11:33 UTC, joelpalmer commented
Ping from Triage: Closing due to inactivity. This can be reopened when there are updates from the author or a reviewer can be found offline.

2019-10-19 16:25 UTC, Zoxc commented
r? @nikomatsakis

2019-10-19 16:30 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=11195&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11195/logs/49), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11195/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-19T15:11:25.3057587Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-19T15:11:25.3276482Z ##[command]git config gc.auto 0
2019-10-19T15:11:25.3375403Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-19T15:11:25.3457500Z ##[command]git config --get-all http.proxy
2019-10-19T15:11:25.3622563Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/61845/merge:refs/remotes/pull/61845/merge
---
2019-10-19T16:17:15.1795416Z .................................................................................................... 1600/9200
2019-10-19T16:17:20.9716938Z .................................................................................................... 1700/9200
2019-10-19T16:17:34.9086250Z ...............................i...............i.................................................... 1800/9200
2019-10-19T16:17:42.8324983Z .................................................................................................... 1900/9200
2019-10-19T16:17:57.7744625Z .....................iiiii.......................................................................... 2000/9200
2019-10-19T16:18:08.8825033Z .................................................................................................... 2200/9200
2019-10-19T16:18:11.6236000Z .................................................................................................... 2300/9200
2019-10-19T16:18:17.1030022Z .................................................................................................... 2400/9200
2019-10-19T16:18:40.3201938Z .................................................................................................... 2500/9200
---
2019-10-19T16:21:46.9940352Z ........................i...............i........................................................... 4800/9200
2019-10-19T16:21:59.6725172Z .................................................................................................... 4900/9200
2019-10-19T16:22:06.2653358Z .................................................................................................... 5000/9200
2019-10-19T16:22:16.1773971Z .................................................................................................... 5100/9200
2019-10-19T16:22:23.8645397Z ........................ii.ii....................................................................... 5200/9200
2019-10-19T16:22:34.7206992Z .................................................................................................... 5400/9200
2019-10-19T16:22:45.3365828Z ..........................................................................................i......... 5500/9200
2019-10-19T16:22:53.9966177Z .................................................................................................... 5600/9200
2019-10-19T16:22:59.1920830Z .................................................................................................... 5700/9200
2019-10-19T16:22:59.1920830Z .................................................................................................... 5700/9200
2019-10-19T16:23:10.5161910Z .......................................................................................ii...i..ii... 5800/9200
2019-10-19T16:23:38.0312322Z .................................................................................................... 6000/9200
2019-10-19T16:23:47.9547921Z .................................................................................................... 6100/9200
2019-10-19T16:23:55.0875367Z .................................................................................................... 6200/9200
2019-10-19T16:23:55.0875367Z .................................................................................................... 6200/9200
2019-10-19T16:24:09.5864565Z .........i..ii...................................................................................... 6300/9200
2019-10-19T16:24:30.5954637Z .....................................................................i.............................. 6500/9200
2019-10-19T16:24:32.9408714Z .................................................................................................... 6600/9200
2019-10-19T16:24:35.6204130Z ............................................i....................................................... 6700/9200
2019-10-19T16:24:39.5199814Z .................................................................................................... 6800/9200
---
2019-10-19T16:29:25.6374075Z  finished in 6.190
2019-10-19T16:29:25.6606702Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-19T16:29:25.8346053Z 
2019-10-19T16:29:25.8346295Z running 153 tests
2019-10-19T16:29:29.1717073Z i....iii......iii..iiii...i.............................i..i..................i....i...........ii.i. 100/153
2019-10-19T16:29:31.6757527Z i..iiii..............i.........iii.i.........ii......
2019-10-19T16:29:31.6766360Z 
2019-10-19T16:29:31.6766409Z  finished in 5.581
2019-10-19T16:29:31.6766749Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-19T16:29:31.6766789Z 
---
2019-10-19T16:29:33.6069710Z  finished in 2.345
2019-10-19T16:29:33.6293601Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-19T16:29:34.6766158Z 
2019-10-19T16:29:34.6766420Z running 9 tests
2019-10-19T16:29:34.6767343Z iiiiiiiii
2019-10-19T16:29:34.6767901Z 
2019-10-19T16:29:34.6768482Z  finished in 0.170
2019-10-19T16:29:34.6769646Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-19T16:29:34.6770203Z 
2019-10-19T16:29:34.6770203Z 
2019-10-19T16:29:34.6770642Z running 104 tests
2019-10-19T16:29:51.7093696Z .....F.........F.....FFFFFFFFFFFFFFFFFFFFFFFFFF...F.......F.F..........F.F...F....................F. 100/104
2019-10-19T16:29:52.3481991Z F.FF
2019-10-19T16:29:52.3509294Z 
2019-10-19T16:29:52.3509868Z ---- [incremental] incremental/change_name_of_static_in_fn.rs stdout ----
2019-10-19T16:29:52.3509966Z 
2019-10-19T16:29:52.3509966Z 
2019-10-19T16:29:52.3510017Z error in revision `rpass3`: compilation failed!
2019-10-19T16:29:52.3510077Z status: exit code: 101
2019-10-19T16:29:52.3511067Z command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/incremental/change_name_of_static_in_fn.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--cfg" "rpass3" "-C" "incremental=/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental/change_name_of_static_in_fn/change_name_of_static_in_fn.inc" "-Z" "incremental-verify-ich" "-Z" "incremental-queries" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental/change_name_of_static_in_fn/a" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental/change_name_of_static_in_fn/auxili [...]

2019-10-22 19:29 UTC, nikomatsakis commented
@Zoxc why is this marked as `[WIP]`?

2019-10-22 20:24 UTC, nikomatsakis commented
Also, I feel like I already reviewed this =)

I guess I'm thinking of https://github.com/rust-lang/rust/pull/65472 -- does that PR subsume this one?

2019-10-22 20:49 UTC, Zoxc commented
This PR is included in https://github.com/rust-lang/rust/pull/62038, which is probably where you saw it.

It's marked `[WIP]` because the tests fail. It's probably an off by one error somewhere, but I haven't tracked it down yet. The errors are gone in https://github.com/rust-lang/rust/pull/62038, but that doesn't help much since that touches a lot of code.

2019-10-22 21:01 UTC, nikomatsakis requested changes
OK. It took me a while to figure out what was going on in this PR but I get it now. Maybe we can edit the title to something more suggestive? It seems like the big thing that's happening here is that:

* we are sharing the data vector (not the "dep-node to dep-node-index map", as the PR title suggests)
* we are tweaking how we do locks so that we release the lock on the dep-node-to-dep-node-index map faster, and the locks don't overlap

I left some suggestions, mostly to add comments, but they include one API change. What do you think, @Zoxc?

2019-10-22 21:02 UTC, Mark-Simulacrum commented on src/librustc/dep_graph/graph.rs
> +    /// `data` and `node_to_node_index` field below.
I _think_ it might be worth adding something like: "This is semantically the length of the data vector at any given point" if that's accurate?

2019-10-22 21:10 UTC, nikomatsakis commented on src/librustc/dep_graph/graph.rs
> +        if inserted {
(Update: I wrote this comment before I understood that the vector *itself* was sharded, so the text is a bit off...)

2019-10-22 21:10 UTC, nikomatsakis commented
@Zoxc OK -- well, I'm r+ on the general concept, though I'd like to take one more look after the nits / API suggestions above are made. I'm definitely 👍 on breaking out these changes into smaller PRs than #62038! =) Much more approachable. 

One thing I did wonder:

The scheme where we release the index-map lock before acquiring the lock on the particular shard seems potentially more complex than necessary. Is the main reason to do that performance? Obviously, it would allow multiple threads to insert nodes into their respective shards in parallel, which seems good, but it's also kind of complex. I'm wondering what the overall evidence is for the impact of this patch in terms of performance.

2019-10-26 02:25 UTC, JohnCSimon commented
Ping from triage: this has sat idle for the last few days 
@zoxc can you please address the comments from @nikomatsakis 
thanks!

2019-10-29 21:30 UTC, nikomatsakis commented on src/librustc/dep_graph/graph.rs
> +    /// `data` and `node_to_node_index` field below.
Seems good, yes (including the parenthetical note at the end)

2019-10-29 21:31 UTC, nikomatsakis commented on src/librustc/dep_graph/graph.rs
> +    /// `data` and `node_to_node_index` field below.
```suggestion
    /// `data` and `node_to_node_index` field below.
    /// 
    /// NB. This is the "logical" length of the complete data vector at any point.
    /// In practice, though, the "logical" data vector is sharded across many vectors,
    /// which will of course be of smaller lengths.
```

2019-10-29 21:31 UTC, nikomatsakis reviewed
(github requires me to post a comment for some reason before I can respond to people's threads)

2019-11-06 18:09 UTC, Alexendoo commented
Ping from triage, any updates? @Zoxc

2019-11-11 18:12 UTC, joelpalmer commented
Ping from triage, any updates? @Zoxc

2019-11-18 11:52 UTC, joelpalmer commented
Ping from Triage: @Zoxc closing due to inactivity. Please re-open with any updates.

2019-11-25 00:26 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=14354&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/14354/logs/66), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/14354/logs/66)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-11-24T23:18:19.7250249Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-11-24T23:18:19.7308908Z ##[command]git config gc.auto 0
2019-11-24T23:18:19.7311527Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-11-24T23:18:19.7313622Z ##[command]git config --get-all http.proxy
2019-11-24T23:18:19.7316423Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/61845/merge:refs/remotes/pull/61845/merge
---
2019-11-25T00:14:28.9819355Z .................................................................................................... 1600/9283
2019-11-25T00:14:33.6158995Z .................................................................................................... 1700/9283
2019-11-25T00:14:46.1354674Z .............................i...................................................................... 1800/9283
2019-11-25T00:14:52.5126289Z .................................................................................................... 1900/9283
2019-11-25T00:15:05.9290592Z ..............iiiii................................................................................. 2000/9283
2019-11-25T00:15:15.3719708Z .................................................................................................... 2200/9283
2019-11-25T00:15:17.7800302Z .................................................................................................... 2300/9283
2019-11-25T00:15:22.6099036Z .................................................................................................... 2400/9283
2019-11-25T00:15:42.6579690Z .................................................................................................... 2500/9283
---
2019-11-25T00:18:17.7572411Z ..............i...............i..................................................................... 4800/9283
2019-11-25T00:18:27.9985418Z .................................................................................................... 4900/9283
2019-11-25T00:18:33.6489728Z .................................................................................................... 5000/9283
2019-11-25T00:18:43.3473753Z .................................................................................................... 5100/9283
2019-11-25T00:18:49.5998676Z ...................ii.ii...........i................................................................ 5200/9283
2019-11-25T00:18:58.4913098Z .................................................................................................... 5400/9283
2019-11-25T00:19:09.2136567Z .................................................................................................... 5500/9283
2019-11-25T00:19:16.7683016Z .i.................................................................................................. 5600/9283
2019-11-25T00:19:22.0791219Z .................................................................................................... 5700/9283
2019-11-25T00:19:22.0791219Z .................................................................................................... 5700/9283
2019-11-25T00:19:32.2093572Z .......................................................................................ii...i..ii... 5800/9283
2019-11-25T00:19:53.9535725Z .................................................................................................... 6000/9283
2019-11-25T00:20:01.2744143Z .................................................................................................... 6100/9283
2019-11-25T00:20:05.1651805Z .................................................................................................... 6200/9283
2019-11-25T00:20:05.1651805Z .................................................................................................... 6200/9283
2019-11-25T00:20:18.2913622Z ..........i..ii..................................................................................... 6300/9283
2019-11-25T00:20:36.6865292Z ..............................................................................i..................... 6500/9283
2019-11-25T00:20:39.0122141Z .................................................................................................... 6600/9283
2019-11-25T00:20:41.1886296Z .....................................................................i.............................. 6700/9283
2019-11-25T00:20:44.0473066Z .................................................................................................... 6800/9283
---
2019-11-25T00:25:36.5916591Z  finished in 5.731
2019-11-25T00:25:36.6126481Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-11-25T00:25:36.7630933Z 
2019-11-25T00:25:36.7631040Z running 157 tests
2019-11-25T00:25:39.4733196Z iiii....iii......iii..iiii...i.............................i..i..................i....i...........ii 100/157
2019-11-25T00:25:41.4399454Z .i.i..iiii..............i.........iii.i..........ii......
2019-11-25T00:25:41.4403510Z 
2019-11-25T00:25:41.4403571Z  finished in 4.827
2019-11-25T00:25:41.4582282Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-11-25T00:25:42.1633553Z 
---
2019-11-25T00:25:43.6112527Z  finished in 2.153
2019-11-25T00:25:43.6291037Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-11-25T00:25:43.7757916Z 
2019-11-25T00:25:43.7758671Z running 9 tests
2019-11-25T00:25:43.7759760Z iiiiiiiii
2019-11-25T00:25:43.7761120Z 
2019-11-25T00:25:43.7761370Z  finished in 0.146
2019-11-25T00:25:43.7944630Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-11-25T00:25:44.6585612Z 
2019-11-25T00:25:44.6585612Z 
2019-11-25T00:25:44.6639522Z running 110 tests
2019-11-25T00:26:00.9558428Z ......F..............F....F.FFFFFFFFFFFFFFFFFFFFFFFFF...F.......FF...........F.F...F................ 100/110
2019-11-25T00:26:02.3849475Z .....FF.FF
2019-11-25T00:26:02.3904737Z 
2019-11-25T00:26:02.3905566Z ---- [incremental] incremental/change_name_of_static_in_fn.rs stdout ----
2019-11-25T00:26:02.3905618Z 
2019-11-25T00:26:02.3905618Z 
2019-11-25T00:26:02.3905674Z error in revision `rpass3`: compilation failed!
2019-11-25T00:26:02.3905746Z status: exit code: 101
2019-11-25T00:26:02.3907048Z command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/incremental/change_name_of_static_in_fn.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--cfg" "rpass3" "-C" "incremental=/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental/change_name_of_static_in_fn/change_name_of_static_in_fn.inc" "-Z" "incremental-verify-ich" "-Z" "incremental-queries" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental/change_name_of_static_in_fn/a" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental/change_name_of_static_in [...]

2019-12-07 06:25 UTC, JohnCSimon commented
Ping from triage - 
@Zoxc can you please address the build failures and mark the comment from nikomatsakis as complete if you've already addressed it, so can be reviewed and merged?

2019-12-29 12:20 UTC, closed without merging