Use ecx for const-prop local storage
rust-lang/rust pull request #62012
Opened 2019-06-21 01:13 UTC by wesleywiser

r? @oli-obk

2019-06-21 01:59 UTC, Centril commented on src/librustc_mir/transform/const_prop.rs
> +        // steal some data we need from `body`
```suggestion
        // Steal some data we need from `body`.
```

2019-06-21 01:59 UTC, Centril commented on src/librustc_mir/transform/const_prop.rs
> +        if l.value == LocalValue::Uninitialized || l.value == LocalValue::Dead {
```suggestion
        if let LocalValue::Uninitialized | LocalValue::Dead = l.value {
```

2019-06-21 07:07 UTC, oli-obk requested changes
r=me with @Centril's and my nits addressed

2019-06-21 07:07 UTC, oli-obk commented on src/librustc_mir/transform/const_prop.rs
> +        (ClearCrossCrate<IndexVec<SourceScope, SourceScopeLocalData>>,
Rustfmt says

```rust
    fn release_stolen_data(
        self,
    ) -> (
        ClearCrossCrate<IndexVec<SourceScope, SourceScopeLocalData>>,
        IndexVec<Promoted, Body<'tcx>>,
    ) {
        (self.source_scope_local_data, self.promoted)
    }
```

2019-06-21 07:07 UTC, oli-obk commented on src/librustc_mir/transform/const_prop.rs
> +        if l.value == LocalValue::Uninitialized || l.value == LocalValue::Dead {
Why do we need this early abort? Leave a comment

2019-06-21 07:07 UTC, oli-obk commented on src/librustc_mir/transform/const_prop.rs
> +    fn set_const(&mut self, local: Local, c: Option<Const<'tcx>>) {
create two functions instead of switching behaviour on an `Option`

2019-06-21 07:07 UTC, oli-obk commented on src/librustc_mir/transform/const_prop.rs
> +                    layout: Cell::new(Some(op_ty.layout)),
add a `debug_assert_eq` to check that the layout didn't change if the local already had one

2019-06-21 11:39 UTC, oli-obk commented on src/librustc_mir/transform/const_prop.rs
> +        // If the local is `Unitialized` or `Dead1 then we haven't propagated a value into it.
```suggestion
        // If the local is `Unitialized` or `Dead` then we haven't propagated a value into it.
```

2019-06-21 11:46 UTC, wesleywiser commented on src/librustc_mir/transform/const_prop.rs
> +        // If the local is `Unitialized` or `Dead1 then we haven't propagated a value into it.
🤦‍♂

2019-06-21 12:01 UTC, oli-obk commented
@bors try

let's see how this impacts perf

2019-06-21 12:37 UTC, oli-obk commented
@rust-timer build dcd84aacc5c7ce6f4bec6d55ee5ff095ff6646de

2019-06-21 12:37 UTC, rust-timer commented
Success: Queued dcd84aacc5c7ce6f4bec6d55ee5ff095ff6646de with parent 56a12b2ad058f22f1ef090713df15598525ba4a4, [comparison URL](https://perf.rust-lang.org/compare.html?start=56a12b2ad058f22f1ef090713df15598525ba4a4&end=dcd84aacc5c7ce6f4bec6d55ee5ff095ff6646de).

2019-06-21 16:48 UTC, rust-timer commented
Finished benchmarking try commit dcd84aacc5c7ce6f4bec6d55ee5ff095ff6646de, [comparison URL](https://perf.rust-lang.org/compare.html?start=56a12b2ad058f22f1ef090713df15598525ba4a4&end=dcd84aacc5c7ce6f4bec6d55ee5ff095ff6646de).

2019-06-22 16:56 UTC, wesleywiser commented
@bors try

2019-06-22 16:58 UTC, wesleywiser commented
@rust-timer build b9376e62aea7c07ac50bf6929abf4931611b10a9

2019-06-22 16:58 UTC, rust-timer commented
Success: Queued b9376e62aea7c07ac50bf6929abf4931611b10a9 with parent d4d5d67c1c20b9599c812ab4d926ab4fa9fe6935, [comparison URL](https://perf.rust-lang.org/compare.html?start=d4d5d67c1c20b9599c812ab4d926ab4fa9fe6935&end=b9376e62aea7c07ac50bf6929abf4931611b10a9).

2019-06-22 21:41 UTC, rust-timer commented
Finished benchmarking try commit b9376e62aea7c07ac50bf6929abf4931611b10a9, [comparison URL](https://perf.rust-lang.org/compare.html?start=d4d5d67c1c20b9599c812ab4d926ab4fa9fe6935&end=b9376e62aea7c07ac50bf6929abf4931611b10a9).

2019-06-23 04:11 UTC, wesleywiser commented
That didn't really help. I'm reverting that.

2019-06-23 16:16 UTC, wesleywiser commented
@oli-obk Are you ok with the performance?

2019-06-24 06:49 UTC, oli-obk commented
Yes, I believe now that we can start reusing const eval logic, we can improve the readability of the const propagator enough to warrant the perf regression. I also think that some of these reuse-changes will improve perf or at least expose perf problems in const eval that we can then address.

@bors r+

2019-06-24 10:52 UTC, merged