Fix miri error in into_inner() of CString
rust-lang/rust pull request #62610
Opened 2019-07-12 07:36 UTC by Stargateur

Fix #62553

I choice to not transmute because I think it's more unsafe and in case the structure change this code should always work.

r? @RalfJung

2019-07-12 07:36 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @RalfJung (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2019-07-12 07:41 UTC, hellow554 requested changes

2019-07-12 07:41 UTC, hellow554 commented on src/libstd/ffi/c_str.rs
> +        // so we use ManuallyDrop to unsure `self` is not drop
ensure

2019-07-12 07:41 UTC, hellow554 commented on src/libstd/ffi/c_str.rs
> +        // and then we can return the box directly without invalid it.
invalidating

2019-07-12 07:41 UTC, hellow554 commented on src/libstd/ffi/c_str.rs
> +        // Rational: `mem::forget(self);` invalid a previous call to `ptr::read(&self.inner)`
invalidates the

2019-07-12 08:13 UTC, Stargateur commented
I would like to add a test but I don't know how.

2019-07-13 08:29 UTC, RalfJung commented on src/libstd/ffi/c_str.rs
> +        // so we use ManuallyDrop to ensure `self` is not drop
```suggestion
        // so we use ManuallyDrop to ensure `self` is not dropped.
```

2019-07-13 08:29 UTC, RalfJung commented on src/libstd/ffi/c_str.rs
> +        // and then we can return the box directly without invalidating it.
```suggestion
        // Then we can return the box directly without invalidating it.
```

2019-07-13 08:30 UTC, RalfJung commented on src/libstd/ffi/c_str.rs
> +        // see https://github.com/rust-lang/rust/issues/62553
```suggestion
        // See https://github.com/rust-lang/rust/issues/62553.
```

2019-07-13 08:30 UTC, RalfJung commented on src/libstd/ffi/c_str.rs
> +        // Rational: `mem::forget(self);` invalidates the previous call to `ptr::read(&self.inner)`
```suggestion
        // Rationale: `mem::forget(self)` invalidates the previous call to `ptr::read(&self.inner)`
```

2019-07-13 08:31 UTC, RalfJung commented
> I would like to add a test but I don't know how.

You mean a test that this does not error in Miri any more? For that, please make a PR at I would like to add a test but I don't know how..

2019-07-14 11:30 UTC, RalfJung commented
This looks great! When you force-push and want a new review, please leave a note saying so; GitHub unfortunately does not send email notifications for force-pushes.

@bors r+

Do you want to try to add a Miri test case as well? Do you need mentoring for that?

2019-07-14 17:30 UTC, merged