Make "see issue" consistent
rust-lang/rust pull request #63008
Opened 2019-07-26 12:31 UTC by eupn

Fixes #62976. h/t to @punitkoura for initial patterns search.

?r @shepmaster @varkor

2019-07-26 13:55 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=4359&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4359/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-07-26T12:39:36.9073318Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-07-26T12:39:36.9272311Z ##[command]git config gc.auto 0
2019-07-26T12:39:36.9376620Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-07-26T12:39:36.9452394Z ##[command]git config --get-all http.proxy
2019-07-26T12:39:36.9595336Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/63008/merge:refs/remotes/pull/63008/merge
---
2019-07-26T12:40:11.8874211Z do so (now or later) by using -b with the checkout command again. Example:
2019-07-26T12:40:11.8874395Z 
2019-07-26T12:40:11.8874783Z   git checkout -b <new-branch-name>
2019-07-26T12:40:11.8875200Z 
2019-07-26T12:40:11.8875381Z HEAD is now at 296179e14 Merge 0ba3bff8923d9bc31e8a5e917c11a2a53036ccdf into 4268e7ee22935f086b856ef0063a9e22b49aeddb
2019-07-26T12:40:11.9005455Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-07-26T12:40:11.9008397Z ==============================================================================
2019-07-26T12:40:11.9008458Z Task         : Bash
2019-07-26T12:40:11.9008527Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-07-26T13:40:52.8811476Z .................................................................................................... 200/5862
2019-07-26T13:40:57.2782500Z .................................................................................................... 300/5862
2019-07-26T13:41:01.2081619Z .................................................................................................... 400/5862
2019-07-26T13:41:05.1601215Z .................................................................................................... 500/5862
2019-07-26T13:41:09.1771683Z ........................................................................i........................... 600/5862
2019-07-26T13:41:18.4670994Z .................................................................................................... 800/5862
2019-07-26T13:41:24.3441610Z .................................................................................................... 900/5862
2019-07-26T13:41:29.5900537Z .................................................................................................... 1000/5862
2019-07-26T13:41:29.5900537Z .................................................................................................... 1000/5862
2019-07-26T13:41:35.3830533Z i...........i....................................................................................... 1100/5862
2019-07-26T13:41:39.4898762Z ..............................iiiii................................................................. 1200/5862
2019-07-26T13:41:45.8028525Z .................................................................................................... 1400/5862
2019-07-26T13:41:48.6132659Z .................................................................................................... 1500/5862
2019-07-26T13:41:52.3551086Z .................................................................................................... 1600/5862
2019-07-26T13:41:55.0718305Z .................................................................................................... 1700/5862
2019-07-26T13:41:55.0718305Z .................................................................................................... 1700/5862
2019-07-26T13:41:58.5409456Z ......................................................................i............................. 1800/5862
2019-07-26T13:42:07.2460466Z .................................................................................................... 2000/5862
2019-07-26T13:42:11.6525738Z .................................................................................................... 2100/5862
2019-07-26T13:42:15.5276616Z .................................................................................................... 2200/5862
2019-07-26T13:42:15.5276616Z .................................................................................................... 2200/5862
2019-07-26T13:42:19.5851021Z ......................................................i............................................. 2300/5862
2019-07-26T13:42:29.8702179Z .................................................................................................... 2500/5862
2019-07-26T13:42:34.2370935Z .................................................................................................... 2600/5862
2019-07-26T13:42:39.7189906Z .................................................................................................... 2700/5862
2019-07-26T13:42:43.7644672Z .................................................................................................... 2800/5862
2019-07-26T13:42:43.7644672Z .................................................................................................... 2800/5862
2019-07-26T13:42:48.4162565Z .................................................................................................... 2900/5862
2019-07-26T13:42:54.0230791Z .................................................................................................... 3000/5862
2019-07-26T13:42:58.6391164Z .................................................................................................... 3100/5862
2019-07-26T13:43:04.2037337Z .................................................................................................... 3200/5862
2019-07-26T13:43:07.9011353Z .................................................................................................... 3300/5862
2019-07-26T13:43:11.7991120Z .................................................................................................... 3400/5862
2019-07-26T13:43:17.1227526Z .................................................................................................... 3500/5862
2019-07-26T13:43:21.0488700Z .....................i.............................................................................. 3600/5862
2019-07-26T13:43:25.5116915Z .................................................................................................ii. 3700/5862
2019-07-26T13:43:29.4504289Z ..i..ii............................................................................................. 3800/5862
2019-07-26T13:43:38.5800957Z .................................................................................................... 4000/5862
2019-07-26T13:43:38.5800957Z .................................................................................................... 4000/5862
2019-07-26T13:43:42.7130538Z ................ii.................................................................................. 4100/5862
2019-07-26T13:43:44.9233757Z .....................................i.............................................................. 4200/5862
2019-07-26T13:43:47.1386553Z .................................................................................................... 4300/5862
2019-07-26T13:43:49.5626952Z ......i............................................................................................. 4400/5862
2019-07-26T13:44:12.3209228Z .................................................................................................... 4600/5862
2019-07-26T13:44:16.2092893Z .. [...]

2019-07-26 18:11 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=4381&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4381/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-07-26T16:12:49.2943166Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-07-26T16:12:49.3178535Z ##[command]git config gc.auto 0
2019-07-26T16:12:49.3278010Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-07-26T16:12:49.3340826Z ##[command]git config --get-all http.proxy
2019-07-26T16:12:50.3372281Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/63008/merge:refs/remotes/pull/63008/merge
---
2019-07-26T16:13:23.1511699Z do so (now or later) by using -b with the checkout command again. Example:
2019-07-26T16:13:23.1511729Z 
2019-07-26T16:13:23.1511931Z   git checkout -b <new-branch-name>
2019-07-26T16:13:23.1511961Z 
2019-07-26T16:13:23.1512031Z HEAD is now at 7bd43f4a5 Merge ae8e6d86cd28e80ad56d70b84640046faaba0ba1 into 1a563362865e6051d4c350544131228e8eff5138
2019-07-26T16:13:23.1654585Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-07-26T16:13:23.1657339Z ==============================================================================
2019-07-26T16:13:23.1657401Z Task         : Bash
2019-07-26T16:13:23.1657450Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-07-26T17:13:07.5983194Z .................................................................................................... 200/5862
2019-07-26T17:13:11.7586031Z .................................................................................................... 300/5862
2019-07-26T17:13:15.4286323Z .................................................................................................... 400/5862
2019-07-26T17:13:19.1545682Z .................................................................................................... 500/5862
2019-07-26T17:13:22.9190731Z ........................................................................i........................... 600/5862
2019-07-26T17:13:31.8466480Z .................................................................................................... 800/5862
2019-07-26T17:13:37.4105691Z .................................................................................................... 900/5862
2019-07-26T17:13:42.3401570Z .................................................................................................... 1000/5862
2019-07-26T17:13:42.3401570Z .................................................................................................... 1000/5862
2019-07-26T17:13:47.7616591Z i...........i....................................................................................... 1100/5862
2019-07-26T17:13:51.6035284Z ..............................iiiii................................................................. 1200/5862
2019-07-26T17:13:57.5659553Z .................................................................................................... 1400/5862
2019-07-26T17:14:00.2165851Z .................................................................................................... 1500/5862
2019-07-26T17:14:03.9048253Z .................................................................................................... 1600/5862
2019-07-26T17:14:06.5200145Z .................................................................................................... 1700/5862
2019-07-26T17:14:06.5200145Z .................................................................................................... 1700/5862
2019-07-26T17:14:09.9314751Z ......................................................................i............................. 1800/5862
2019-07-26T17:14:18.4129138Z .................................................................................................... 2000/5862
2019-07-26T17:14:22.6993990Z .................................................................................................... 2100/5862
2019-07-26T17:14:26.3577734Z .................................................................................................... 2200/5862
2019-07-26T17:14:26.3577734Z .................................................................................................... 2200/5862
2019-07-26T17:14:30.2128482Z ......................................................i............................................. 2300/5862
2019-07-26T17:14:39.8537271Z .................................................................................................... 2500/5862
2019-07-26T17:14:43.9151847Z .................................................................................................... 2600/5862
2019-07-26T17:14:49.0635800Z .................................................................................................... 2700/5862
2019-07-26T17:14:52.8138440Z .................................................................................................... 2800/5862
2019-07-26T17:14:52.8138440Z .................................................................................................... 2800/5862
2019-07-26T17:14:57.1214816Z .................................................................................................... 2900/5862
2019-07-26T17:15:02.3545963Z .................................................................................................... 3000/5862
2019-07-26T17:15:06.6152181Z .................................................................................................... 3100/5862
2019-07-26T17:15:11.7527267Z .................................................................................................... 3200/5862
2019-07-26T17:15:15.1772005Z .................................................................................................... 3300/5862
2019-07-26T17:15:18.7232795Z .................................................................................................... 3400/5862
2019-07-26T17:15:23.7248724Z .................................................................................................... 3500/5862
2019-07-26T17:15:27.4019264Z .....................i.............................................................................. 3600/5862
2019-07-26T17:15:31.5096315Z .................................................................................................ii. 3700/5862
2019-07-26T17:15:35.0860045Z ..i..ii............................................................................................. 3800/5862
2019-07-26T17:15:43.3671183Z .................................................................................................... 4000/5862
2019-07-26T17:15:43.3671183Z .................................................................................................... 4000/5862
2019-07-26T17:15:47.1543215Z ................ii.................................................................................. 4100/5862
2019-07-26T17:15:49.1464861Z .....................................i.............................................................. 4200/5862
2019-07-26T17:15:51.2712732Z .................................................................................................... 4300/5862
2019-07-26T17:15:53.5657828Z ......i............................................................................................. 4400/5862
2019-07-26T17:16:15.1084529Z .................................................................................................... 4600/5862
2019-07-26T17:16:18.7662289Z .. [...]

2019-07-28 13:27 UTC, ghost requested changes
there are some more inconsistencies that should be fixed (at least some of them): 
>See issue #49146 \<https://github.com/rust-lang/rust/issues/49146> \\
**for more information**.", kind),

>**for more information**, see issue \\
 #57563 \<https://github.com/rust-lang/rust/issues/57563>");

>see issue #43162 \<https://github.com/rust-lang/rust/issues/43162#issuecomment-320764675>"

>**please** see issue #44136 \<https://github.com/rust-lang/rust/issues/44136>

>**for more context**, see issue #60210 \<https://github.com/rust-lang/rust/issues/60210>

>see issue #46062 \<https://github.com/rust-lang/rust/issues/46062> **for more details**

I think, the order should be consistent, as well as the inclusion of "for more information/details"

2019-07-28 14:59 UTC, eupn commented
@BO41
> there are some more inconsistencies that should be fixed (at least some of them):
> 
> > See issue #49146 <[https://github.com/rust-lang/rust/issues/49146>](https://github.com/rust-lang/rust/issues/49146%3E) \
> > **for more information**.", kind),
> 
> > **for more information**, see issue \
> > #57563 <[https://github.com/rust-lang/rust/issues/57563>](https://github.com/rust-lang/rust/issues/57563%3E)");
> 
> > see issue #43162 <[https://github.com/rust-lang/rust/issues/43162#issuecomment-320764675>](https://github.com/rust-lang/rust/issues/43162#issuecomment-320764675%3E)"
> 
> > **please** see issue #44136 <[https://github.com/rust-lang/rust/issues/44136>](https://github.com/rust-lang/rust/issues/44136%3E)
> 
> > **for more context**, see issue #60210 <[https://github.com/rust-lang/rust/issues/60210>](https://github.com/rust-lang/rust/issues/60210%3E)
> 
> > see issue #46062 <[https://github.com/rust-lang/rust/issues/46062>](https://github.com/rust-lang/rust/issues/46062%3E) **for more details**
> 
> I think, the order should be consistent, as well as the inclusion of "for more information/details"

I should've made this consistent as well. In this PR, I was only concerned about the consistency of Github links to the issues.

2019-07-28 16:42 UTC, ghost approved these changes

2019-07-28 17:07 UTC, shepmaster commented
r? @varkor

2019-07-28 19:52 UTC, varkor commented
I'll review this soon. However, I feel slightly uncomfortable, because @punitkoura had asked to take this issue. It would be a shame to waste this effort, though.

If @punitkoura is happy with it, perhaps we could go with this pull request, but  @punitkoura can be added as a [co-author](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors) for doing the initial work? Then I can direct @punitkoura to another easy starter issue.

2019-07-29 05:44 UTC, punitkoura commented
Hi @varkor, these changes look good to me. I was also working on the same, but then saw this PR and therefore didn't raise another PR. It'd be really nice if I could be added as a co-author though :)

2019-07-29 08:04 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=4607&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4607/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-07-29T06:50:07.7542262Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-07-29T06:50:07.7744975Z ##[command]git config gc.auto 0
2019-07-29T06:50:07.7812282Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-07-29T06:50:07.7872177Z ##[command]git config --get-all http.proxy
2019-07-29T06:50:07.8014157Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/63008/merge:refs/remotes/pull/63008/merge
---
2019-07-29T06:50:41.1333511Z do so (now or later) by using -b with the checkout command again. Example:
2019-07-29T06:50:41.1333542Z 
2019-07-29T06:50:41.1333784Z   git checkout -b <new-branch-name>
2019-07-29T06:50:41.1333814Z 
2019-07-29T06:50:41.1333862Z HEAD is now at fea0d021b Merge 93666a47cd6d45be96cb56ecfa58c9383c528759 into 8b94e9e9188b65df38a5f1ae723617dc2dfb3155
2019-07-29T06:50:41.1462832Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-07-29T06:50:41.1465644Z ==============================================================================
2019-07-29T06:50:41.1465722Z Task         : Bash
2019-07-29T06:50:41.1465771Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-07-29T07:53:21.9131427Z .................................................................................................... 1400/8804
2019-07-29T07:53:27.9882229Z .................................................................................................... 1500/8804
2019-07-29T07:53:40.6191990Z ................................................................i...............i................... 1600/8804
2019-07-29T07:53:48.4195652Z .................................................................................................... 1700/8804
2019-07-29T07:54:03.5714613Z ..................................................iiiii............................................. 1800/8804
2019-07-29T07:54:15.0471064Z .................................................................................................... 2000/8804
2019-07-29T07:54:17.6816851Z .................................................................................................... 2100/8804
2019-07-29T07:54:21.7162997Z .................................................................................................... 2200/8804
2019-07-29T07:54:28.3163754Z .................................................................................................... 2300/8804
---
2019-07-29T07:58:18.2155740Z .................................................................................................... 5200/8804
2019-07-29T07:58:29.1367787Z .................................................................................................... 5300/8804
2019-07-29T07:58:36.8959977Z ..i................................................................................................. 5400/8804
2019-07-29T07:58:42.3318897Z .................................................................................................... 5500/8804
2019-07-29T07:58:54.5743298Z ................................................................................................ii.. 5600/8804
2019-07-29T07:59:09.3897312Z .i..ii...........i.................................................................................. 5700/8804
2019-07-29T07:59:25.7620652Z .................................................................................................... 5900/8804
2019-07-29T07:59:30.6084741Z ................................................................................................i..i 6000/8804
2019-07-29T07:59:45.1412275Z i................................................................................................... 6100/8804
2019-07-29T08:00:01.7412339Z .................................................................................................... 6200/8804
---
2019-07-29T08:04:13.6429413Z 
2019-07-29T08:04:13.6429942Z ---- [ui] ui/parser/match-vec-invalid.rs stdout ----
2019-07-29T08:04:13.6430003Z diff of stderr:
2019-07-29T08:04:13.6430033Z 
2019-07-29T08:04:13.6430080Z 10 LL |         [1, tail @ .., tail @ ..] => {},
2019-07-29T08:04:13.6430228Z 12    |
2019-07-29T08:04:13.6430228Z 12    |
2019-07-29T08:04:13.6430616Z -    = note: for more information, see ***/issues/62254
2019-07-29T08:04:13.6430956Z +    = note: for more information, see issue #62254 <***/issues/62254>
2019-07-29T08:04:13.6431018Z 14    = help: add `#![feature(slice_patterns)]` to the crate attributes to enable
2019-07-29T08:04:13.6431127Z 16 error[E0658]: subslice patterns are unstable
2019-07-29T08:04:13.6431157Z 
2019-07-29T08:04:13.6431157Z 
2019-07-29T08:04:13.6431203Z 19 LL |         [1, tail @ .., tail @ ..] => {},
2019-07-29T08:04:13.6431309Z 21    |
2019-07-29T08:04:13.6431309Z 21    |
2019-07-29T08:04:13.6431593Z -    = note: for more information, see ***/issues/62254
2019-07-29T08:04:13.6431953Z +    = note: for more information, see issue #62254 <***/issues/62254>
2019-07-29T08:04:13.6432016Z 23    = help: add `#![feature(slice_patterns)]` to the crate attributes to enable
2019-07-29T08:04:13.6432082Z 24 
2019-07-29T08:04:13.6432313Z 25 error: `..` can only be used once per slice pattern
2019-07-29T08:04:13.6432479Z 
2019-07-29T08:04:13.6432672Z The actual stderr differed from the expected stderr.
2019-07-29T08:04:13.6433500Z Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/parser/match-vec-invalid/match-vec-invalid.stderr
2019-07-29T08:04:13.6433500Z Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/parser/match-vec-invalid/match-vec-invalid.stderr
2019-07-29T08:04:13.6434095Z To update references, rerun the tests and pass the `--bless` flag
2019-07-29T08:04:13.6434388Z To only update this specific test, also pass `--test-args parser/match-vec-invalid.rs`
2019-07-29T08:04:13.6434471Z error: 1 errors occurred comparing output.
2019-07-29T08:04:13.6434517Z status: exit code: 1
2019-07-29T08:04:13.6434517Z status: exit code: 1
2019-07-29T08:04:13.6435264Z command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/parser/match-vec-invalid.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/parser/match-vec-invalid" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/parser/match-vec-invalid/auxiliary" "-A" "unused"
2019-07-29T08:04:13.6435599Z ------------------------------------------
2019-07-29T08:04:13.6435634Z 
2019-07-29T08:04:13.6435845Z ------------------------------------------
2019-07-29T08:04:13.6435906Z stderr:
2019-07-29T08:04:13.6435906Z stderr:
2019-07-29T08:04:13.6436697Z ------------------------------------------
2019-07-29T08:04:13.6436756Z error[E0416]: identifier `tail` is bound more than once in the same pattern
2019-07-29T08:04:13.6437073Z    |
2019-07-29T08:04:13.6437073Z    |
2019-07-29T08:04:13.6437119Z LL |         [1, tail @ .., tail @ ..] => {},
2019-07-29T08:04:13.6437188Z    |                        ^^^^ used in a pattern more than once
2019-07-29T08:04:13.6437283Z error[E0658]: subslice patterns are unstable
2019-07-29T08:04:13.6437522Z   --> /ch [...]

2019-07-29 20:42 UTC, varkor commented
It'd be nice to normalise the following strings that appear:
- "for more context, see [...]"
- "for more information, see [...]"
- "See [...] for details"
- "see [...] for more details"
- "see [...] for more information"

I personally prefer "see [...] for more information", as it has the link early on.

Apart from that, this looks good. If you could squash the `--bless`/rebase/tidy commits and add @punitkoura as a co-author, I'll approve it.

2019-07-29 20:42 UTC, varkor commented on src/librustc/session/mod.rs
>          sess.err("Profile-guided optimization does not yet work in conjunction \
```suggestion
        sess.err("profile-guided optimization does not yet work in conjunction \
```
Let's make this quick drive-by fix while we're at it.

2019-07-29 20:42 UTC, varkor commented on src/librustdoc/core.rs
> +                msg.warn("please see issue \
```suggestion
                msg.warn("see issue \
```

2019-07-29 20:42 UTC, varkor commented on src/librustdoc/config.rs
> +            err.warn("please see issue #44136 <https://github.com/rust-lang/rust/issues/44136>");
```suggestion
            err.warn("see issue #44136 <https://github.com/rust-lang/rust/issues/44136>");
```

2019-07-30 06:37 UTC, eupn commented
> It'd be nice to normalise the following strings that appear:
> 
>     * "for more context, see [...]"
> 
>     * "for more information, see [...]"
> 
>     * "See [...] for details"
> 
>     * "see [...] for more details"
> 
>     * "see [...] for more information"
> 
> 
> I personally prefer "see [...] for more information", as it has the link early on.
> 
> Apart from that, this looks good. If you could squash the `--bless`/rebase/tidy commits and add @punitkoura as a co-author, I'll approve it.

@punitkoura don't you mind if I'll use your email `pkoura@andrew.cmu.edu` as `Co-authored-by` for commits?

2019-07-30 11:01 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=4716&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4716/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-07-30T09:50:35.3380662Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-07-30T09:50:35.3553822Z ##[command]git config gc.auto 0
2019-07-30T09:50:35.3626461Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-07-30T09:50:35.3678134Z ##[command]git config --get-all http.proxy
2019-07-30T09:50:35.3811543Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/63008/merge:refs/remotes/pull/63008/merge
---
2019-07-30T09:51:09.2529702Z do so (now or later) by using -b with the checkout command again. Example:
2019-07-30T09:51:09.2529727Z 
2019-07-30T09:51:09.2529891Z   git checkout -b <new-branch-name>
2019-07-30T09:51:09.2529914Z 
2019-07-30T09:51:09.2529952Z HEAD is now at 350964d60 Merge f1d1ba5646c9a774e049d20dad3b18c66e1ae3bc into 4eeaaa722d6ac6d24de6e4d3faefb7c44e674b37
2019-07-30T09:51:09.2667118Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-07-30T09:51:09.2669623Z ==============================================================================
2019-07-30T09:51:09.2669669Z Task         : Bash
2019-07-30T09:51:09.2669707Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-07-30T10:49:05.8072150Z .................................................................................................... 1400/8813
2019-07-30T10:49:11.1687084Z .................................................................................................... 1500/8813
2019-07-30T10:49:22.7442881Z ................................................................i...............i................... 1600/8813
2019-07-30T10:49:29.7601262Z .................................................................................................... 1700/8813
2019-07-30T10:49:43.1703845Z ..................................................iiiii............................................. 1800/8813
2019-07-30T10:49:53.4827053Z .................................................................................................... 2000/8813
2019-07-30T10:49:55.8357892Z .................................................................................................... 2100/8813
2019-07-30T10:49:59.0141445Z .................................................................................................... 2200/8813
2019-07-30T10:50:05.1032492Z .................................................................................................... 2300/8813
---
2019-07-30T10:53:41.8199509Z .................................................................................................... 5300/8813
2019-07-30T10:53:48.3887208Z ........i........................................................................................... 5400/8813
2019-07-30T10:53:53.4615810Z .................................................................................................... 5500/8813
2019-07-30T10:54:05.0971074Z .................................................................................................... 5600/8813
2019-07-30T10:54:18.0103539Z ..ii...i..ii...........i............................................................................ 5700/8813
2019-07-30T10:54:31.1785456Z .................................................................................................... 5900/8813
2019-07-30T10:54:35.4802979Z .................................................................................................... 6000/8813
2019-07-30T10:54:35.4802979Z .................................................................................................... 6000/8813
2019-07-30T10:54:48.7432821Z ..i..ii............................................................................................. 6100/8813
2019-07-30T10:55:06.0155549Z .............................................i...................................................... 6300/8813
2019-07-30T10:55:07.9962249Z .................................................................................................... 6400/8813
2019-07-30T10:55:10.3392386Z ...............i.................................................................................... 6500/8813
2019-07-30T10:55:14.4307528Z .................................................................................................... 6600/8813
---
2019-07-30T10:59:30.3293345Z  finished in 19.104
2019-07-30T10:59:30.3443806Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-07-30T10:59:30.4866468Z 
2019-07-30T10:59:30.4866900Z running 146 tests
2019-07-30T10:59:33.4667607Z i....iii......iii..iiii....i............................i..i................i....i.........ii.i.i..i 100/146
2019-07-30T10:59:35.2207571Z iii..............i.........iii.i......ii......
2019-07-30T10:59:35.2208212Z 
2019-07-30T10:59:35.2209979Z  finished in 4.876
2019-07-30T10:59:35.2386688Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-07-30T10:59:35.3829060Z 
---
2019-07-30T10:59:37.2788987Z  finished in 2.040
2019-07-30T10:59:37.2948745Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-07-30T10:59:37.4298130Z 
2019-07-30T10:59:37.4298272Z running 9 tests
2019-07-30T10:59:37.4298885Z iiiiiiiii
2019-07-30T10:59:37.4299266Z 
2019-07-30T10:59:37.4303201Z  finished in 0.135
2019-07-30T10:59:37.4462661Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-07-30T10:59:37.5962034Z 
---
2019-07-30T10:59:54.7576474Z  finished in 16.865
2019-07-30T10:59:54.7576704Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-07-30T10:59:54.7576764Z 
2019-07-30T10:59:54.7576803Z running 122 tests
2019-07-30T11:00:16.0595880Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....i..........iiii..........i...ii...i.......ii.i 100/122
2019-07-30T11:00:20.1947657Z .i.i......iii.i.....ii
2019-07-30T11:00:20.1949154Z 
2019-07-30T11:00:20.1950518Z  finished in 25.866
2019-07-30T11:00:20.1953152Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-07-30T11:00:20.1953637Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-07-30T11:01:14.7159404Z 
2019-07-30T11:01:14.7159442Z 8 LL | extern crate rustc_data_structures;
2019-07-30T11:01:14.7159479Z 9    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2019-07-30T11:01:14.7159513Z 10    |
2019-07-30T11:01:14.7160237Z -    = note: for more information, see issue #27812 <***/issues/27812>
2019-07-30T11:01:14.7160540Z +    = note: see issue #27812 <***/issues/27812> for more information
2019-07-30T11:01:14.7160612Z 12    = help: add `#![feature(rustc_private)]` to the crate attributes to enable
2019-07-30T11:01:14.7160650Z 13 
2019-07-30T11:01:14.7160960Z 14 error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead?
2019-07-30T11:01:14.7161054Z 17 LL | extern crate rustc;
2019-07-30T11:01:14.7161097Z 18    | ^^^^^^^^^^^^^^^^^^^
2019-07-30T11:01:14.7161147Z 19    |
2019-07-30T11:01:14.7161147Z 19    |
2019-07-30T11:01:14.7161385Z -    = note: for more information,  [...]

2019-07-30 14:15 UTC, punitkoura commented
@eupn, yes, that email id works
Name - Punit Singh Koura
Email - pkoura@andrew.cmu.edu

2019-07-31 09:48 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=4780&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4780/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-07-31T08:35:45.9334016Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-07-31T08:35:45.9542264Z ##[command]git config gc.auto 0
2019-07-31T08:35:45.9608845Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-07-31T08:35:45.9678991Z ##[command]git config --get-all http.proxy
2019-07-31T08:35:45.9824288Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/63008/merge:refs/remotes/pull/63008/merge
---
2019-07-31T08:36:21.2742319Z do so (now or later) by using -b with the checkout command again. Example:
2019-07-31T08:36:21.2742359Z 
2019-07-31T08:36:21.2742583Z   git checkout -b <new-branch-name>
2019-07-31T08:36:21.2742610Z 
2019-07-31T08:36:21.2742673Z HEAD is now at 937722a64 Merge 955d629abe965f62fa6a44f1de8263a0758c17d7 into 4a18848e05b0957474fdb5be162502742b5eb9fd
2019-07-31T08:36:21.2915244Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-07-31T08:36:21.2919393Z ==============================================================================
2019-07-31T08:36:21.2919454Z Task         : Bash
2019-07-31T08:36:21.2919501Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-07-31T09:37:16.3889867Z .................................................................................................... 1400/8819
2019-07-31T09:37:22.4528314Z .................................................................................................... 1500/8819
2019-07-31T09:37:35.8142898Z .................................................................i...............i.................. 1600/8819
2019-07-31T09:37:43.7375942Z .................................................................................................... 1700/8819
2019-07-31T09:37:59.3907449Z ...................................................iiiii............................................ 1800/8819
2019-07-31T09:38:11.4124689Z .................................................................................................... 2000/8819
2019-07-31T09:38:14.1611316Z .................................................................................................... 2100/8819
2019-07-31T09:38:18.0769549Z .................................................................................................... 2200/8819
2019-07-31T09:38:25.0390746Z .................................................................................................... 2300/8819
---
2019-07-31T09:42:31.0361382Z .................................................................................................... 5300/8819
2019-07-31T09:42:38.8660790Z ..............i..................................................................................... 5400/8819
2019-07-31T09:42:44.6760299Z .................................................................................................... 5500/8819
2019-07-31T09:42:57.0824609Z .................................................................................................... 5600/8819
2019-07-31T09:43:10.7733745Z ........ii...i..ii...........i...................................................................... 5700/8819
2019-07-31T09:43:27.0395727Z .................................................................................................... 5900/8819
2019-07-31T09:43:32.1205050Z .................................................................................................... 6000/8819
2019-07-31T09:43:32.1205050Z .................................................................................................... 6000/8819
2019-07-31T09:43:46.2664220Z ........i..ii....................................................................................... 6100/8819
2019-07-31T09:44:05.5927054Z ...................................................i................................................ 6300/8819
2019-07-31T09:44:07.8777528Z .................................................................................................... 6400/8819
2019-07-31T09:44:10.4096232Z .....................i.............................................................................. 6500/8819
2019-07-31T09:44:15.1330429Z .................................................................................................... 6600/8819
---
2019-07-31T09:48:18.8068826Z 
2019-07-31T09:48:18.8069380Z ---- [ui] ui/async-await/await-keyword/2015-edition-error-various-positions.rs stdout ----
2019-07-31T09:48:18.8069457Z diff of stderr:
2019-07-31T09:48:18.8069487Z 
2019-07-31T09:48:18.8069539Z 73    |     ^^^^^ help: you can use a raw identifier to stay compatible: `r#await`
2019-07-31T09:48:18.8069588Z 74    |
2019-07-31T09:48:18.8069664Z 75    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in the 2018 edition!
2019-07-31T09:48:18.8070086Z -    = note: for more information, see issue #49716 <***/issues/49716>
2019-07-31T09:48:18.8070614Z +    = note: see issue #49716 <***/issues/49716> for more information
2019-07-31T09:48:18.8070693Z 77 
2019-07-31T09:48:18.8070740Z 78 error: `await` is a keyword in the 2018 edition
2019-07-31T09:48:18.8071044Z 79   --> $DIR/2015-edition-error-various-positions.rs:35:11
2019-07-31T09:48:18.8071105Z 
2019-07-31T09:48:18.8071152Z The actual stderr differed from the expected stderr.
2019-07-31T09:48:18.8071534Z Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/await-keyword/2015-edition-error-various-positions/2015-edition-error-various-positions.stderr
2019-07-31T09:48:18.8071534Z Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/await-keyword/2015-edition-error-various-positions/2015-edition-error-various-positions.stderr
2019-07-31T09:48:18.8071785Z To update references, rerun the tests and pass the `--bless` flag
2019-07-31T09:48:18.8072086Z To only update this specific test, also pass `--test-args async-await/await-keyword/2015-edition-error-various-positions.rs`
2019-07-31T09:48:18.8072187Z error: 1 errors occurred comparing output.
2019-07-31T09:48:18.8072232Z status: exit code: 1
2019-07-31T09:48:18.8072232Z status: exit code: 1
2019-07-31T09:48:18.8073114Z command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/async-await/await-keyword/2015-edition-error-various-positions.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/await-keyword/2015-edition-error-various-positions" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/await-keyword/2015-edition-error-various-positions/auxiliary" "-A" "unused"
2019-07-31T09:48:18.8073466Z ------------------------------------------
2019-07-31T09:48:18.8073500Z 
2019-07-31T09:48:18.8073714Z ------------------------------------------
2019-07-31T09:48:18.8073888Z stderr:
2019-07-31T09:48:18.8073888Z stderr:
2019-07-31T09:48:18.8074102Z ------------------------------------------
2019-07-31T09:48:18.8074281Z error: `await` is a keyword in the 2018 edition
2019-07-31T09:48:18.8075015Z    |
2019-07-31T09:48:18.8075015Z    |
2019-07-31T09:48:18.8 [...]

2019-07-31 15:42 UTC, eupn commented
@varkor

2019-07-31 20:59 UTC, varkor commented
Thanks!

@bors r+

2019-08-01 00:59 UTC, Centril commented
Failed in https://github.com/rust-lang/rust/pull/63176#issuecomment-517075965, @bors r-

Please `--bless --compare-mode=nll` to fix the issues.

2019-08-01 22:01 UTC, eupn commented
@Centril

2019-08-01 22:03 UTC, Centril commented
@bors r+

2019-08-08 15:16 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=5387&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/5387/logs/45)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-08-08T14:57:09.7998733Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-08-08T14:57:09.8183853Z ##[command]git config gc.auto 0
2019-08-08T14:57:09.8250106Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-08-08T14:57:09.8303105Z ##[command]git config --get-all http.proxy
2019-08-08T14:57:09.8437893Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/63008/merge:refs/remotes/pull/63008/merge
---
2019-08-08T14:57:44.3532239Z do so (now or later) by using -b with the checkout command again. Example:
2019-08-08T14:57:44.3533600Z 
2019-08-08T14:57:44.3535584Z   git checkout -b <new-branch-name>
2019-08-08T14:57:44.3536215Z 
2019-08-08T14:57:44.3536743Z HEAD is now at 59290648e Merge b2f919985b365c912aafdbe37dce920e25f38cd6 into 2628f579f6246df385acf9203bf2ffb6aedf5ccc
2019-08-08T14:57:44.3657989Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-08-08T14:57:44.3660819Z ==============================================================================
2019-08-08T14:57:44.3660880Z Task         : Bash
2019-08-08T14:57:44.3660946Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-08-08T15:03:43.3011301Z    Compiling serde_json v1.0.40
2019-08-08T15:03:47.5124052Z    Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
2019-08-08T15:03:55.9110832Z     Finished release [optimized] target(s) in 1m 27s
2019-08-08T15:03:55.9174980Z tidy check
2019-08-08T15:03:56.1193234Z tidy error: /checkout/src/test/ui/consts/const-eval/match-test-ptr-null.rs:6: trailing whitespace
2019-08-08T15:03:57.7467810Z some tidy checks failed
2019-08-08T15:03:57.7468336Z 
2019-08-08T15:03:57.7468336Z 
2019-08-08T15:03:57.7469585Z command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor"
2019-08-08T15:03:57.7469728Z 
2019-08-08T15:03:57.7469754Z 
2019-08-08T15:03:57.7469825Z failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
2019-08-08T15:03:57.7469878Z Build completed unsuccessfully in 0:01:30
2019-08-08T15:03:57.7469878Z Build completed unsuccessfully in 0:01:30
2019-08-08T15:03:59.0351150Z ##[error]Bash exited with code '1'.
2019-08-08T15:03:59.0383050Z ##[section]Starting: Checkout
2019-08-08T15:03:59.0384751Z ==============================================================================
2019-08-08T15:03:59.0384820Z Task         : Get sources
2019-08-08T15:03:59.0384864Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-08-09 08:10 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=5455&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/5455/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-08-09T06:55:48.8790476Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-08-09T06:55:48.8971896Z ##[command]git config gc.auto 0
2019-08-09T06:55:48.9061969Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-08-09T06:55:48.9120498Z ##[command]git config --get-all http.proxy
2019-08-09T06:55:48.9279920Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/63008/merge:refs/remotes/pull/63008/merge
---
2019-08-09T06:56:25.4243647Z do so (now or later) by using -b with the checkout command again. Example:
2019-08-09T06:56:25.4243821Z 
2019-08-09T06:56:25.4244242Z   git checkout -b <new-branch-name>
2019-08-09T06:56:25.4244403Z 
2019-08-09T06:56:25.4244571Z HEAD is now at de4d95214 Merge 8307000cabb34c98ef5bbfcf93ec4b72099419c0 into 5aa3d9a7b5d3a46a7f158e8881146331a6bc9243
2019-08-09T06:56:25.4393822Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-08-09T06:56:25.4396518Z ==============================================================================
2019-08-09T06:56:25.4396576Z Task         : Bash
2019-08-09T06:56:25.4396621Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-08-09T07:58:56.9816040Z .................................................................................................... 1300/8853
2019-08-09T07:59:03.5246867Z ..........................................F......................................................... 1400/8853
2019-08-09T07:59:09.8433831Z .................................................................................................... 1500/8853
2019-08-09T07:59:20.6118015Z ....................................................................................i............... 1600/8853
2019-08-09T07:59:28.3105186Z i................................................................................................... 1700/8853
2019-08-09T07:59:35.4046536Z ......................................................................iiiii......................... 1800/8853
2019-08-09T07:59:57.4429661Z .................................................................................................... 2000/8853
2019-08-09T07:59:59.9570429Z .................................................................................................... 2100/8853
2019-08-09T08:00:02.9082913Z .................................................................................................... 2200/8853
2019-08-09T08:00:10.8335906Z .................................................................................................... 2300/8853
---
2019-08-09T08:04:00.2558651Z .................................................................................................... 5200/8853
2019-08-09T08:04:11.9145866Z ..............................................................................................i..... 5300/8853
2019-08-09T08:04:19.9196517Z .................................................................................................... 5400/8853
2019-08-09T08:04:24.7997237Z .................................................................................................... 5500/8853
2019-08-09T08:04:36.4317899Z ........................................................................................ii...i..ii.. 5600/8853
2019-08-09T08:05:00.9596698Z .................................................................................................... 5800/8853
2019-08-09T08:05:06.4558651Z .................................................................................................... 5900/8853
2019-08-09T08:05:06.4558651Z .................................................................................................... 5900/8853
2019-08-09T08:05:11.1698122Z .........................................................................................i..ii...... 6000/8853
2019-08-09T08:05:42.4151733Z .................................................................................................... 6200/8853
2019-08-09T08:05:44.5400301Z ................................i................................................................... 6300/8853
2019-08-09T08:05:46.7825191Z .................................................................................................... 6400/8853
2019-08-09T08:05:49.4950995Z ....i............................................................................................... 6500/8853
---
2019-08-09T08:09:56.7030070Z 
2019-08-09T08:09:56.7030252Z 1 error[E0658]: casting pointers to integers in constants is unstable
2019-08-09T08:09:56.7030681Z 2   --> $DIR/match-test-ptr-null.rs:6:15
2019-08-09T08:09:56.7030872Z 3    |
2019-08-09T08:09:56.7031735Z - LL |         match &1 as *const i32 as usize { 
2019-08-09T08:09:56.7032397Z + LL |         match &1 as *const i32 as usize {
2019-08-09T08:09:56.7032749Z 6    |
2019-08-09T08:09:56.7032749Z 6    |
2019-08-09T08:09:56.7033755Z 7    = note: see issue #51910 <***/issues/51910> for more information
2019-08-09T08:09:56.7034184Z 10 error[E0019]: constant contains unimplemented expression type
2019-08-09T08:09:56.7034616Z 11   --> $DIR/match-test-ptr-null.rs:6:15
2019-08-09T08:09:56.7034828Z 12    |
2019-08-09T08:09:56.7034828Z 12    |
2019-08-09T08:09:56.7035200Z - LL |         match &1 as *const i32 as usize { 
2019-08-09T08:09:56.7035389Z + LL |         match &1 as *const i32 as usize {
2019-08-09T08:09:56.7035719Z 15 
2019-08-09T08:09:56.7035882Z 16 error[E0019]: constant contains unimplemented expression type
2019-08-09T08:09:56.7036011Z 
2019-08-09T08:09:56.7036156Z 22 error[E0080]: evaluation of constant value failed
2019-08-09T08:09:56.7036156Z 22 error[E0080]: evaluation of constant value failed
2019-08-09T08:09:56.7036526Z 23   --> $DIR/match-test-ptr-null.rs:6:15
2019-08-09T08:09:56.7036724Z 24    |
2019-08-09T08:09:56.7037110Z - LL |         match &1 as *const i32 as usize { 
2019-08-09T08:09:56.7037311Z + LL |         match &1 as *const i32 as usize {
2019-08-09T08:09:56.7037747Z 26    |               ^^^^^^^^^^^^^^^^^^^^^^^^^ "pointer-to-integer cast" needs an rfc before being allowed inside constants
2019-08-09T08:09:56.7038104Z 28 error: aborting due to 4 previous errors
2019-08-09T08:09:56.7038228Z 
2019-08-09T08:09:56.7038346Z 
2019-08-09T08:09:56.7038502Z The actual stderr differed from the expected stderr.
2019-08-09T08:09:56.7038502Z The actual stderr differed from the expected stderr.
2019-08-09T08:09:56.7039147Z Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/const-eval/match-test-ptr-null/match-test-ptr-null.stderr
2019-08-09T08:09:56.7039649Z To update references, rerun the tests and pass the `--bless` flag
2019-08-09T08:09:56.7040126Z To only update this specific test, also pass `--test-args consts/const-eval/match-test-ptr-null.rs`
2019-08-09T08:09:56.7040432Z error: 1 errors occurred comparing output.
2019-08-09T08:09:56.7040615Z status: exit code: 1
2019-08-09T08:09:56.7040615Z status: exit code: 1
2019-08-09T08:09:56.7041537Z command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/consts/const-eval/match-test-ptr-null.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/const-eval/match-test-ptr-null" "-Crpath" " [...]

2019-08-10 16:41 UTC, Mark-Simulacrum commented
@bors p=1

since this is pretty conflict-prone

2019-08-11 22:44 UTC, varkor commented
@eupn: there have been more merge conflicts, so you'll need to rebase and force push again.

2019-08-23 16:37 UTC, ProgrammaticNajel commented
Ping from triage. @eupn any updates on this? Thanks.

2019-08-23 16:40 UTC, eupn commented
I’ll rebase it soon!

2019-09-01 08:32 UTC, JohnTitor commented
Ping from triage: @eupn any updates on this?

2019-09-08 02:25 UTC, JohnTitor commented
Ping from triage: @eupn any updates on this?

2019-09-16 10:31 UTC, joelpalmer commented
Ping from Triage: closing due to inactivity. Thanks for the PR @eupn! If you do rebase and have updates, please re-open.

2019-09-16 10:31 UTC, closed without merging