HIR: introduce a HirId to DefId map in Definitions
rust-lang/rust pull request #63849
Opened 2019-08-24 14:05 UTC by ljedrz

Split out from https://github.com/rust-lang/rust/pull/62975.

Introduce a `HirId` to `DefIndex` map in `map::Definitions`; this introduces a little bit of extra complexity, but could result in a performance win. I'd do a perf run to check if it's worth it.

2019-08-24 14:05 UTC, rust-highfive commented
r? @cramertj

(rust_highfive has picked a reviewer for you, use r? to override)

2019-08-24 14:07 UTC, ljedrz commented
@bors try

2019-09-01 13:02 UTC, bjorn3 commented
This should get a perf run, isn't it?

2019-09-01 19:56 UTC, ljedrz commented
Yeah, I'd suggest doing that; I don't have perf creds, though.

2019-09-01 19:57 UTC, Mark-Simulacrum commented
@rust-timer build 8a50d3d384210ef535686e4c3804884fede9a4de

Feel free to ping me if you need a perf run

2019-09-01 19:57 UTC, rust-timer commented
Success: Queued 8a50d3d384210ef535686e4c3804884fede9a4de with parent 478464570e60523adc6d303577d1782229ca1f93, [comparison URL](https://perf.rust-lang.org/compare.html?start=478464570e60523adc6d303577d1782229ca1f93&end=8a50d3d384210ef535686e4c3804884fede9a4de).

2019-09-02 00:15 UTC, rust-timer commented
Finished benchmarking try commit 8a50d3d384210ef535686e4c3804884fede9a4de, [comparison URL](https://perf.rust-lang.org/compare.html?start=478464570e60523adc6d303577d1782229ca1f93&end=8a50d3d384210ef535686e4c3804884fede9a4de).

2019-09-02 07:47 UTC, ljedrz commented
Not too shabby; @Zoxc you said you'd recommend someone else to review this specific change - can you suggest someone?

2019-09-09 10:10 UTC, joelpalmer commented
Ping from Triage: Hi @Zoxc - can we get an update on the review or the hunt for a reviewer? Also will cc @varkor since they are being suggested as a reviewer. Possibly they can help.

2019-09-18 19:39 UTC, Alexendoo commented
Triage: Requesting a review from @rust-lang/compiler

2019-09-18 20:01 UTC, nikomatsakis commented
r? @nikomatsakis

2019-09-18 20:01 UTC, nikomatsakis commented
Hmm, my read of the performance results is that this is basically neutral. It looked like almost everything was 0% except for one 1%, and that was for a known unreliable case. Am I mis-reading?

If not, I'd be inclined to leave things as they are, as @ljedrz noted that this change increased the complexity of the code.

2019-09-19 09:21 UTC, ljedrz commented
This is a necessary step for the deprecation of `NodeId`s after HIR lowering (that is nearly complete), though - otherwise we still need to rely on `definitions::opt_def_index,opt_local_def_id`. Do you have any suggestions on how to do it in a more elegant manner?

2019-09-19 21:15 UTC, nikomatsakis commented
@ljedrz ah sorry, I misunderstood the motivation. I thought this was a performance optimization.

2019-09-23 17:20 UTC, nikomatsakis requested changes
@ljedrz -- the code here looks good! But one thing I was missing is a bit of context. Maybe you can add a comment that helps to clarify *why* the HirId-DefId mapping for these cases is different?

Clearly, it has to do with defs that are "synthesized" during lowering, but if you could say a bit more I think it'd be helpful for future readers. :)

2019-09-23 17:20 UTC, nikomatsakis commented on src/librustc/hir/map/definitions.rs
> +    /// mapping after the lowering
Can you elaborate slightly on this comment? Why can't the mapping be done immediately? 

(Another alternative might be to create a larger comment, or extend one if one exists, explaining how the overall mapping is created in the first place.)

2019-09-23 17:20 UTC, nikomatsakis commented on src/librustc/hir/map/definitions.rs
> +    /// DefCollector::create_def can't be assigned to HirIds at that stage yet)
(Perhaps reference the explanation I requested earlier from this comment)

2019-09-29 10:13 UTC, ljedrz commented
@nikomatsakis I rebased and expanded on the previous comments.

2019-10-01 12:38 UTC, eddyb commented
I don't know where I last suggested it but IMO it would probably be nicer to have every node with a `DefId` be a `HirId` root, making this map unnecessary (as you can get the `DefId` from the `HirId`).

2019-10-01 21:26 UTC, nikomatsakis commented
@eddyb that does indeed sound pretty clean, but it seems like a larger scale refactoring -- how hard do you think it would be?

2019-10-01 23:18 UTC, eddyb commented
It shouldn't be that hard, I think there a "whitelist" of `HirId` owners somewhere that would need to be relaxed, but other than that most things don't rely on the current stratification at all.

The main exception is `ty::TypeckTables` which would need nested tables of itself for closures, since it's optimized by having its maps be keyed by intra-`HirId`-owner IDs.

2019-10-02 08:07 UTC, michaelwoerister commented
What are the interactions with incremental compilation. That's why we introduced `HirId` in the first place and I expect that at least some of the code relies on `HirId-owner == item-like`. To be clear: I don't object, I just don't expect the change to be entirely straight forward.

2019-10-03 13:07 UTC, nikomatsakis commented
@eddyb is there a canonical list of "things that have def-ids"? To be honest I might be a little out of date on the current status here.

(This actually feels like a case where I'd have appreciated a design meeting, or at least some up-front docs on what the plans are -- @ljedrz I'm kind of assuming those don't exist? (Don't feel bad, it's not standard practice.))

2019-10-03 13:28 UTC, ljedrz commented
@nikomatsakis I don't mind at all ^^.

Nah, they don't exist - at least none that I know of. I'm just continuing the ancient `NodeId` bashing crusade (AKA the `HirId`ification initiative), so that we can ditch `NodeId`s in favor of `HirId`s after the AST > HIR lowering (for uniformity and incremental gains).

I don't mind how it is done; the concept outlined by @eddyb is a bit foreign to me, but I wouldn't mind doing it that way with a little bit of mentoring.

2019-10-03 13:36 UTC, eddyb commented
@nikomatsakis Mostly whatever happens to get a `DefId` assigned to it in https://github.com/rust-lang/rust/blob/master/src/librustc/hir/map/def_collector.rs.

`DefKind` lists a subset of those cases (most notably missing `impl`s): https://github.com/rust-lang/rust/blob/0221e265621a5fcc68ca62bdcdeabad1882a0e9a/src/librustc/hir/def.rs#L50-L83

IMO "item-likes" is an outdated concept, but my preferred solution (i.e. consolidating a notion of "def" beyond just `DefId` and `DefKind`) requires more design and planning, which I'm less sure lately I can allocate time for (compared to what I was hopping to get done over the summer).

2019-10-12 04:49 UTC, JohnCSimon commented
Ping from triage
@nikomatsakis this appears to still be waiting on review. 
Thanks.

2019-10-18 21:36 UTC, ProgrammaticNajel commented
Ping from triage. @nikomatsakis any updates on this? Thanks.

2019-10-22 21:37 UTC, nikomatsakis commented
Yeah, sorry to @ljedrz for not providing more feedback here! I've been wanting to block out some time that I can try to better understand what @eddyb is saying =)

2019-10-23 14:57 UTC, eddyb commented
All I'm saying is reduce the "item-like" distinction further and make all things with a `DefId` more similar, in terms of being `HirId` roots, nothing more.

It's not a complex plan, and the only complications would be things that assume too much about `HirId`'s current situation, such as `TypeckTables` wrt closures.

2019-10-25 20:55 UTC, nikomatsakis commented
OK, @ljedrz -- so I talked some to @eddyb about this a few days back. I asked them if they'd be willing to mentor you through their preferred approach. They said yes, but they'd have to do a bit of exploratory refactoring first. The idea was that they would create a PR that points the direction and hand if off to you to fill in the details. I think they had the impression that this would be relatively quick but then again I think they're still working on it. =)

I think my preferred outcome would be:

* close this PR
* you + @eddyb communicate a bit and discuss a revised plan
* through some combination of PRs, we execute that plan

As I think I wrote somewhere, I would also like to see that plan written out as documentation -- it seems like we should be discussing how `HirId`, `DefId`, and friends relate to one another! This is pretty fundamental stuff. But at this point my primary concern is getting you + @eddyb on same page.

2019-10-26 07:29 UTC, ljedrz commented
I'm ok with this 👍.

2019-10-26 07:29 UTC, closed without merging