Refactor feature gates
rust-lang/rust pull request #63855
Opened 2019-08-24 15:54 UTC by killercup

After #63824, this goes a few steps further by

- parsing doc comments in the macros to extract descriptions for feature gates, and
- introducing a common `Feature` type to replace the tuples used previously to improve readability.

The descriptions are not yet used, but I felt like this PR is a useful enough refactoring on its own.

r? @Centril

2019-08-24 16:13 UTC, Centril requested changes
Thanks! r=me with comments below addressed. :)

2019-08-24 16:13 UTC, Centril commented on src/libsyntax/feature_gate/check.rs
> +            if edition <= crate_edition {
This `if let .. { if ... {` could be turned into `ACTIVE_FEATURES.filter(...)`

2019-08-24 16:13 UTC, Centril commented on src/libsyntax/feature_gate/check.rs
>                          if f_edition <= *edition {
...Same here, except `crate_edition` substituted for `edition`. Could use a function for these, e.g. `fn active_features_until_edition(edition: ...)`.

2019-08-24 16:13 UTC, Centril commented on src/libsyntax/feature_gate/check.rs
> +                match state {
This...

2019-08-24 16:13 UTC, Centril commented on src/libsyntax/feature_gate/check.rs
> +                            match state {
...is repeated here and could be refactored?

2019-08-24 16:13 UTC, Centril commented on src/libsyntax/feature_gate/check.rs
> +                match state {
```suggestion
                if let FeatureState::Removed { reason } | FeatureState::Stabilized { reason } = state {
```

2019-08-24 16:13 UTC, Centril commented on src/libsyntax/feature_gate/check.rs
> +                match state {
...repeated 3rd time here.

2019-08-24 16:53 UTC, killercup commented
Thanks for the review, @Centril! I've changed most of the loops you mentioned, so it'd be good to have a second look before I blindly r+ this :)

2019-08-24 17:35 UTC, Centril approved these changes

2019-08-24 17:37 UTC, Centril commented
@bors r+

2019-08-24 18:46 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=6641&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/6641/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-08-24T17:34:28.1553650Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-08-24T17:34:28.1752260Z ##[command]git config gc.auto 0
2019-08-24T17:34:28.6986811Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-08-24T17:34:28.6993040Z ##[command]git config --get-all http.proxy
2019-08-24T17:34:28.7000168Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/63855/merge:refs/remotes/pull/63855/merge
---
2019-08-24T17:35:02.6410439Z do so (now or later) by using -b with the checkout command again. Example:
2019-08-24T17:35:02.6410627Z 
2019-08-24T17:35:02.6410896Z   git checkout -b <new-branch-name>
2019-08-24T17:35:02.6410953Z 
2019-08-24T17:35:02.6411043Z HEAD is now at fd7bf489d Merge 6ffc834dee1423d02613794406241280af10719c into 478464570e60523adc6d303577d1782229ca1f93
2019-08-24T17:35:02.6566663Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-08-24T17:35:02.6569143Z ==============================================================================
2019-08-24T17:35:02.6569212Z Task         : Bash
2019-08-24T17:35:02.6569250Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-08-24T18:35:34.4803134Z .................................................................................................... 1500/8950
2019-08-24T18:35:40.0546749Z .................................................................................................... 1600/8950
2019-08-24T18:35:52.9644933Z ...........................................i...............i........................................ 1700/8950
2019-08-24T18:36:01.1742862Z .................................................................................................... 1800/8950
2019-08-24T18:36:15.7678238Z ...................................iiiii............................................................ 1900/8950
2019-08-24T18:36:23.9855422Z ...........................................F......................................................F. 2000/8950
2019-08-24T18:36:29.1811040Z .................................................................................................... 2200/8950
2019-08-24T18:36:33.7155150Z ..................................................F................................................. 2300/8950
2019-08-24T18:36:40.9648050Z .................................................................................................... 2400/8950
2019-08-24T18:36:43.6342885Z .................................................................................................... 2500/8950
---
2019-08-24T18:39:37.6322950Z .......................i...............i............................................................ 4700/8950
2019-08-24T18:39:49.5029411Z .................................................................................................... 4800/8950
2019-08-24T18:39:55.3689633Z .................................................................................................... 4900/8950
2019-08-24T18:40:06.0353027Z .................................................................................................... 5000/8950
2019-08-24T18:40:11.0959170Z ....ii.ii........................................................................................... 5100/8950
2019-08-24T18:40:25.1343429Z .................................................................................................... 5300/8950
2019-08-24T18:40:31.5062375Z ............................................................i....................................... 5400/8950
2019-08-24T18:40:38.0646081Z .................................................................................................... 5500/8950
2019-08-24T18:40:45.5074131Z .................................................................................................... 5600/8950
2019-08-24T18:40:45.5074131Z .................................................................................................... 5600/8950
2019-08-24T18:40:55.5886605Z ......................................................ii...i..ii...........i........................ 5700/8950
2019-08-24T18:41:15.4780695Z .................................................................................................... 5900/8950
2019-08-24T18:41:20.0314679Z .................................................................................................... 6000/8950
2019-08-24T18:41:20.0314679Z .................................................................................................... 6000/8950
2019-08-24T18:41:27.1075973Z .......................................................i..ii........................................ 6100/8950
2019-08-24T18:41:52.6850098Z .................................................................................................... 6300/8950
2019-08-24T18:41:54.7033211Z .i.................................................................................................. 6400/8950
2019-08-24T18:41:56.7638144Z .........................................................................i.......................... 6500/8950
2019-08-24T18:41:59.5435900Z .................................................................................................... 6600/8950
2019-08-24T18:41:59.5435900Z .................................................................................................... 6600/8950
2019-08-24T18:42:05.2390535Z .................................................................................................... 6700/8950
2019-08-24T18:42:29.3663888Z ................F................................................................................... 6800/8950
2019-08-24T18:42:40.8896800Z .................................................................................................... 6900/8950
2019-08-24T18:42:45.8373187Z .................................................................................................... 7000/8950
2019-08-24T18:42:50.9056811Z .................................................................................................... 7100/8950
2019-08-24T18:42:55.6916568Z .................................................................................................... 7200/8950
2019-08-24T18:43:01.6461362Z .................................................................................................... 7300/8950
2019-08-24T18:43:10.6980720Z ..................................................F..FF..F.F.FF.FFF......F.F........................ 7400/8950
2019-08-24T18:43:26.9892719Z .....................ii......i...................................................................... 7600/8950
2019-08-24T18:43:32.1611270Z .................................................................................................... 7700/8950
2019-08-24T18:43:44.9136818Z .................................................................................................... 7800/8950
2019-08-24T18:43:55.0628465Z .................................................................................................... 7900/8950
---
2019-08-24T18:45:42.3378509Z failures:
2019-08-24T18:45:42.3436457Z 
2019-08-24T18:45:42.3440682Z ---- [ui] ui/editions/edition-feature-ok.rs stdout ----
2019-08-24T18:45:42.3440767Z normalized stderr:
2019-08-24T18:45:42.3440844Z warning[E0705]: the feature `rust_2018_preview` is included in th [...]

2019-08-24 18:59 UTC, Centril commented
That's odd; I don't see anything that would cause this... @bors r-

2019-08-25 13:21 UTC, killercup commented
Let's try this again! Tests pass locally but I'll wait for CI before sending it off to bors.

2019-08-25 14:35 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=6707&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/6707/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-08-25T13:20:33.8282869Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-08-25T13:20:33.8487858Z ##[command]git config gc.auto 0
2019-08-25T13:20:33.8579537Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-08-25T13:20:33.8625844Z ##[command]git config --get-all http.proxy
2019-08-25T13:20:34.6059518Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/63855/merge:refs/remotes/pull/63855/merge
---
2019-08-25T13:21:08.1891758Z do so (now or later) by using -b with the checkout command again. Example:
2019-08-25T13:21:08.1893478Z 
2019-08-25T13:21:08.1917690Z   git checkout -b <new-branch-name>
2019-08-25T13:21:08.1918130Z 
2019-08-25T13:21:08.1918968Z HEAD is now at 10172b49c Merge 1e6d3e2df492a61e02ccd5484f2c855294a05ef8 into d760df5aea483aae041c9a241e7acacf48f75035
2019-08-25T13:21:08.2014902Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-08-25T13:21:08.2018022Z ==============================================================================
2019-08-25T13:21:08.2018107Z Task         : Bash
2019-08-25T13:21:08.2018160Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-08-25T14:24:45.3746853Z .................................................................................................... 1500/8953
2019-08-25T14:24:51.2353248Z .................................................................................................... 1600/8953
2019-08-25T14:25:04.4028572Z .............................................i...............i...................................... 1700/8953
2019-08-25T14:25:12.8089078Z .................................................................................................... 1800/8953
2019-08-25T14:25:27.5737542Z .....................................iiiii.......................................................... 1900/8953
2019-08-25T14:25:38.7067486Z F................................................................................................... 2100/8953
2019-08-25T14:25:41.4284825Z .................................................................................................... 2200/8953
2019-08-25T14:25:45.9780715Z ....................................................F............................................... 2300/8953
2019-08-25T14:25:53.5391821Z .................................................................................................... 2400/8953
---
2019-08-25T14:28:58.7662769Z .........................i...............i.......................................................... 4700/8953
2019-08-25T14:29:10.7322598Z .................................................................................................... 4800/8953
2019-08-25T14:29:17.0880193Z .................................................................................................... 4900/8953
2019-08-25T14:29:28.2842713Z .................................................................................................... 5000/8953
2019-08-25T14:29:33.9039288Z ......ii.ii......................................................................................... 5100/8953
2019-08-25T14:29:48.5553544Z .................................................................................................... 5300/8953
2019-08-25T14:29:55.7748869Z ..............................................................i..................................... 5400/8953
2019-08-25T14:30:03.1150467Z .................................................................................................... 5500/8953
2019-08-25T14:30:11.1280091Z .................................................................................................... 5600/8953
2019-08-25T14:30:11.1280091Z .................................................................................................... 5600/8953
2019-08-25T14:30:22.1965355Z ........................................................ii...i..ii...........i...................... 5700/8953
2019-08-25T14:30:45.3355227Z .................................................................................................... 5900/8953
2019-08-25T14:30:50.5217731Z .................................................................................................... 6000/8953
2019-08-25T14:30:50.5217731Z .................................................................................................... 6000/8953
2019-08-25T14:30:57.8983064Z .........................................................i..ii...................................... 6100/8953
2019-08-25T14:31:26.3921819Z .................................................................................................... 6300/8953
2019-08-25T14:31:28.7192848Z ...i................................................................................................ 6400/8953
2019-08-25T14:31:31.1243267Z ...........................................................................i........................ 6500/8953
2019-08-25T14:31:34.0520565Z .................................................................................................... 6600/8953
2019-08-25T14:31:34.0520565Z .................................................................................................... 6600/8953
2019-08-25T14:31:40.2444957Z .................................................................................................... 6700/8953
2019-08-25T14:32:07.4607393Z ....................F............................................................................... 6800/8953
2019-08-25T14:32:20.0869134Z .................................................................................................... 6900/8953
2019-08-25T14:32:25.5092126Z .................................................................................................... 7000/8953
2019-08-25T14:32:31.1169121Z .................................................................................................... 7100/8953
2019-08-25T14:32:36.3702254Z .................................................................................................... 7200/8953
2019-08-25T14:32:43.0788270Z .................................................................................................... 7300/8953
2019-08-25T14:32:52.9250878Z ....................................................F..FF..F.F.FF.FFF......F.F...................... 7400/8953
2019-08-25T14:33:10.6391117Z .......................ii......i.................................................................... 7600/8953
2019-08-25T14:33:16.3371363Z .................................................................................................... 7700/8953
2019-08-25T14:33:29.7786822Z .................................................................................................... 7800/8953
2019-08-25T14:33:41.3326335Z .................................................................................................... 7900/8953
---
2019-08-25T14:35:38.1301334Z failures:
2019-08-25T14:35:38.1374937Z 
2019-08-25T14:35:38.1375428Z ---- [ui] ui/editions/edition-feature-ok.rs stdout ----
2019-08-25T14:35:38.1375517Z normalized stderr:
2019-08-25T14:35:38.1375576Z warning[E0705]: the feature `rust_2018_preview` is included in the Rust 2018 edition
2019-08-25T14:35:38.1376391Z    |
2019-08-25T14:35:38.1376391Z    |
2019-08-25T14:35:38.1376436Z LL | #![feature(rust_20 [...]

2019-08-25 21:46 UTC, killercup commented
@bors r=Centril rollup

2019-08-27 03:50 UTC, merged