Propagate `types.err` in locals further to avoid spurious knock-down errors
rust-lang/rust pull request #64674
Opened 2019-09-21 23:31 UTC by estebank

Fix #33575.

2019-09-21 23:31 UTC, rust-highfive commented
r? @petrochenkov

(rust_highfive has picked a reviewer for you, use r? to override)

2019-09-21 23:32 UTC, estebank commented
cc @eddyb

2019-09-21 23:45 UTC, Centril requested changes

2019-09-21 23:45 UTC, Centril commented on src/librustc_typeck/check/mod.rs
>          if pat_ty.references_error() {
De-duplicate this please with a new method (including the `if`) (also to reduce diagnostic logic in happy path).

2019-09-21 23:45 UTC, Centril commented on src/librustc_typeck/check/mod.rs
> +            self.locals.borrow_mut().insert(local.pat.hir_id, LocalTy {
Also de-dup the `LocalTy`. :)

2019-09-21 23:45 UTC, Centril commented on src/librustc_typeck/check/coercion.rs
> +        if expr_ty.references_error() {
```suggestion
        Ok(if expr_ty.references_error() {
```

2019-09-21 23:45 UTC, Centril commented on src/test/ui/issues/issue-33575.rs
> +    <i32 as std::str::FromStr>::from_str(&baz); // No complains about `str` being unsized
```suggestion
    <i32 as std::str::FromStr>::from_str(&baz); // No complaints about `str` being unsized.
```

2019-09-21 23:45 UTC, Centril commented
r=me with comments addressed (if you want).

2019-09-22 00:28 UTC, estebank commented
@bors r=Centril

2019-09-22 00:42 UTC, Centril commented
r? @Centril

2019-09-23 06:38 UTC, merged