[rustdoc] add sub settings
rust-lang/rust pull request #64696
Opened 2019-09-22 22:51 UTC by GuillaumeGomez

This PR is to give a finer control over what types are automatically expanded or not as well as the possibility to add sub-settings in the settings page.

![Screenshot from 2019-09-23 00-46-14](https://user-images.githubusercontent.com/3050060/65395521-15aff300-dd9c-11e9-9437-429ca347d455.png)

r? @Mark-Simulacrum

2019-09-23 06:34 UTC, fbstj commented
is this just a reopening of #60778 ?

2019-09-23 08:49 UTC, GuillaumeGomez commented
No, I made some changes. For instance, there is no more global checkbox, just a title for sub-settings.

2019-09-23 19:13 UTC, Mark-Simulacrum commented
So to be clear, this PR changes the current "Auto-hide item declarations." into a set of preferences for each item type?

Can you update the top-level comment with an answer to this question?
 * How does this work when the previously loaded version of the page had auto-hide item declaration checked (and unchecked)? What about the reverse (i.e., going from the new version to the old)?
 * Why were these particular defaults chosen?

Personally, I never really found it all that useful to have a global hide setting for item declarations here so I would not want this feature -- I do generally work on at least a 15" screen though so in that sense I have relatively large screen real estate. Is this feature wanted by folks? And in the "yes I'd use this" not the "well, why not" sense?

2019-09-25 09:22 UTC, GuillaumeGomez commented
> How does this work when the previously loaded version of the page had auto-hide item declaration checked (and unchecked)? What about the reverse (i.e., going from the new version to the old)?

No back compatibility if this is your question.

> Why were these particular defaults chosen?

Debated on the previously opened PR.

> Personally, I never really found it all that useful to have a global hide setting for item declarations here so I would not want this feature -- I do generally work on at least a 15" screen though so in that sense I have relatively large screen real estate. Is this feature wanted by folks? And in the "yes I'd use this" not the "well, why not" sense?

I've been asked to do this a lot of times actually (IRL and IRC). I personally don't care much about this feature but people seems to want to have a better control over the types declaration view.

2019-09-25 12:34 UTC, Mark-Simulacrum commented
> No back compatibility if this is your question.

But, uh, what happens? Presumably we don't just error out and not run at all...

> Debated on the previously opened PR.

Do you have a link? I don't see any such discussion on https://github.com/rust-lang/rust/pull/60778...

> I've been asked to do this a lot of times actually (IRL and IRC). I personally don't care much about this feature but people seems to want to have a better control over the types declaration view.

I would personally echo @QuietMisdreavus's concerns on https://github.com/rust-lang/rust/pull/60778 that this does not seem to really carry it's weight. However, if there is indeed lots of demand, it also seems like a 'not bad' idea.

2019-09-25 19:36 UTC, GuillaumeGomez commented
> But, uh, what happens? Presumably we don't just error out and not run at all...

It doesn't take it into account. That's pretty much it.

> Do you have a link? I don't see any such discussion on #60778...

Seems like it wasn't there... Multi-channels communications are bad...

> I would personally echo @QuietMisdreavus's concerns on #60778 that this does not seem to really carry it's weight. However, if there is indeed lots of demand, it also seems like a 'not bad' idea.

Like I said, I didn't do it just because. People asked me for it and at some point I just said ok and did it.

2019-10-04 14:19 UTC, Mark-Simulacrum commented
I'm going to r? @QuietMisdreavus here as a rustdoc team member, I don't personally feel comfortable driving this

2019-10-12 03:25 UTC, JohnCSimon commented
Ping from triage -
@QuietMisdreavus  this seems to be waiting on a review
Thanks.

2019-10-18 21:37 UTC, ProgrammaticNajel commented
Ping from triage. @QuietMisdreavus any updates on this? Thanks.

2019-10-26 03:21 UTC, JohnCSimon commented
Pinging from triage:
 @QuietMisdreavus can you please review this PR?
Also @GuillaumeGomez can you please resolve the merge conflict?
Thank you!

2019-10-27 10:40 UTC, GuillaumeGomez commented
Rebased.

2019-10-27 12:31 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=12013&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/12013/logs/49), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/12013/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-27T10:41:02.2601391Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-27T10:41:02.2791415Z ##[command]git config gc.auto 0
2019-10-27T10:41:02.2884701Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-27T10:41:02.2951364Z ##[command]git config --get-all http.proxy
2019-10-27T10:41:02.3101569Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/64696/merge:refs/remotes/pull/64696/merge
---
2019-10-27T11:42:04.6635209Z .................................................................................................... 1600/9253
2019-10-27T11:42:09.9489440Z .................................................................................................... 1700/9253
2019-10-27T11:42:22.5485565Z ..........................................................i...............i......................... 1800/9253
2019-10-27T11:42:30.2777574Z .................................................................................................... 1900/9253
2019-10-27T11:42:45.0778488Z ................................................iiiii............................................... 2000/9253
2019-10-27T11:42:56.1147102Z .................................................................................................... 2200/9253
2019-10-27T11:42:58.8471846Z .................................................................................................... 2300/9253
2019-10-27T11:43:02.6509388Z .................................................................................................... 2400/9253
2019-10-27T11:43:26.5810051Z .................................................................................................... 2500/9253
---
2019-10-27T11:46:22.5353046Z ...................................................i...............i................................ 4800/9253
2019-10-27T11:46:31.4941713Z .................................................................................................... 4900/9253
2019-10-27T11:46:40.3045559Z .................................................................................................... 5000/9253
2019-10-27T11:46:46.4994760Z .................................................................................................... 5100/9253
2019-10-27T11:46:57.3082763Z ....................................................ii.ii...........i............................... 5200/9253
2019-10-27T11:47:07.1237941Z .................................................................................................... 5400/9253
2019-10-27T11:47:16.5227520Z .................................................................................................... 5500/9253
2019-10-27T11:47:24.1816395Z ......................i............................................................................. 5600/9253
2019-10-27T11:47:30.1110608Z .................................................................................................... 5700/9253
2019-10-27T11:47:30.1110608Z .................................................................................................... 5700/9253
2019-10-27T11:47:42.3412246Z .................................................................................................... 5800/9253
2019-10-27T11:47:53.5408480Z ...................ii...i..ii...........i........................................................... 5900/9253
2019-10-27T11:48:15.3206058Z .................................................................................................... 6100/9253
2019-10-27T11:48:22.4065016Z .................................................................................................... 6200/9253
2019-10-27T11:48:22.4065016Z .................................................................................................... 6200/9253
2019-10-27T11:48:35.0077005Z ..........................................i..ii..................................................... 6300/9253
2019-10-27T11:48:57.7331834Z .................................................................................................... 6500/9253
2019-10-27T11:48:59.9899314Z ........i........................................................................................... 6600/9253
2019-10-27T11:49:02.3155042Z ...................................................................................i................ 6700/9253
2019-10-27T11:49:05.0276357Z .................................................................................................... 6800/9253
---
2019-10-27T11:53:39.8208641Z  finished in 5.691
2019-10-27T11:53:39.8383340Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-27T11:53:40.0183826Z 
2019-10-27T11:53:40.0184823Z running 153 tests
2019-10-27T11:53:43.2475674Z i....iii......iii..iiii...i.............................i..i..................i....i...........ii.i. 100/153
2019-10-27T11:53:45.2716671Z i..iiii..............i.........iii.i.........ii......
2019-10-27T11:53:45.8558804Z 
2019-10-27T11:53:45.8559151Z  finished in 5.433
2019-10-27T11:53:45.8559742Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-27T11:53:45.8560022Z 
---
2019-10-27T11:53:47.4996676Z  finished in 2.207
2019-10-27T11:53:47.5191634Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-27T11:53:47.6741260Z 
2019-10-27T11:53:47.6742366Z running 9 tests
2019-10-27T11:53:47.6743244Z iiiiiiiii
2019-10-27T11:53:47.6744091Z 
2019-10-27T11:53:47.6747224Z  finished in 0.155
2019-10-27T11:53:47.6939188Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-27T11:53:48.3600543Z 
---
2019-10-27T11:54:06.2542236Z  finished in 18.560
2019-10-27T11:54:06.2743775Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-27T11:54:06.4373723Z 
2019-10-27T11:54:06.4374043Z running 123 tests
2019-10-27T11:54:31.0487295Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....ii..........iiii..........i...ii...i.......ii. 100/123
2019-10-27T11:54:35.9177455Z i.i.i......iii.i.....ii
2019-10-27T11:54:35.9179163Z 
2019-10-27T11:54:35.9182777Z  finished in 29.644
2019-10-27T11:54:35.9192270Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-27T11:54:35.9194338Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-10-27T12:07:18.8570815Z 
2019-10-27T12:07:18.8577017Z    Doc-tests core
2019-10-27T12:07:24.3491881Z 
2019-10-27T12:07:24.3492829Z running 2408 tests
2019-10-27T12:07:36.0619514Z ......iiiii......................................................................................... 100/2408
2019-10-27T12:07:47.3846661Z ................................................................................ii.................. 200/2408
2019-10-27T12:08:13.2682921Z ..i................................................................................................. 400/2408
2019-10-27T12:08:13.2682921Z [...]

2019-10-29 12:54 UTC, GuillaumeGomez commented
Fixed the issue.

cc @QuietMisdreavus

2019-11-02 04:05 UTC, JohnCSimon commented
Ping from triage 
@QuietMisdreavus can you please review this PR?
Thanks

2019-11-02 13:27 UTC, GuillaumeGomez commented
r? @kinnison

2019-11-03 17:00 UTC, kinnison requested changes
In addition to the pluralisation comment I have some concerns that we are not testing the generation of this content at all.

It would probably behoove us to ensure there's at least a basic test checking for the presence of the settings in the generated output.

2019-11-03 17:00 UTC, kinnison commented on src/librustdoc/html/static/settings.css
> +.setting-line > .sub-setting {
To match the change to `sub-settings` you'd need:
```suggestion
.setting-line > .sub-settings {
```

2019-11-04 09:49 UTC, GuillaumeGomez commented
We have a UI server but the integration with highfive is buggy and needs to be fixed. (Maybe when @pietroalbini has some time, we could take a look to understand what's going on)

2019-11-04 10:39 UTC, GuillaumeGomez commented
Updated.

2019-11-04 13:50 UTC, kinnison approved these changes
LGTM :+1:

2019-11-04 13:51 UTC, kinnison commented
Regarding some basic regression testing, could we do a basic rustdoc-ui test using `htmldocck.py` ?

2019-11-05 09:36 UTC, GuillaumeGomez commented
It allows to check the DOM, so it depends what you want to check?

2019-11-06 14:50 UTC, kinnison commented
I was just thinking that a basic check demonstrating that the settings have made it out in a form we were expecting -- that way if the shape is changed in the future, there's a regression test reminding people to re-check it and update the test if it's good.  I wouldn't block a merge on that but you were saying you wanted more tests :D

2019-11-06 17:02 UTC, GuillaumeGomez commented
It's more UI tests then. It's scheduled but I need to have highfive fully working on this so we don't have bad surprises.

2019-11-06 19:24 UTC, kinnison commented
Okay, if you want to make a note (issue?) for the need for the test, and merge the fix in the meantime, I'm good with that.

2019-11-07 09:23 UTC, GuillaumeGomez commented
Done [here](https://github.com/rust-lang/rust/issues/66181). Thanks for your review!

@bors: r=kinnison

2019-11-08 01:15 UTC, merged