Fix most remaining Polonius
rust-lang/rust pull request #64749
Opened 2019-09-24 21:11 UTC by matthewjasper

This fixes most of the Polonius test differences and also avoids overflow in issue-38591.rs.

r? @nikomatsakis

2019-09-24 21:11 UTC, matthewjasper commented
This shouldn't be merged until the last commit has been reverted.

2019-09-24 21:51 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=8953&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/8953/logs/49), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/8953/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-09-24T21:12:07.1854886Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-09-24T21:12:07.2094534Z ##[command]git config gc.auto 0
2019-09-24T21:12:07.2194518Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-09-24T21:12:07.2232140Z ##[command]git config --get-all http.proxy
2019-09-24T21:12:07.2419111Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/64749/merge:refs/remotes/pull/64749/merge
---
2019-09-24T21:17:46.5809076Z  ---> 5a9c4155b013
2019-09-24T21:17:46.5856808Z Successfully built 5a9c4155b013
2019-09-24T21:17:46.6923270Z Successfully tagged rust-ci:latest
2019-09-24T21:17:46.8072642Z Built container sha256:5a9c4155b01378641558d1b5ccac3f8603bfb435b79e65afffd9d532e91397cd
2019-09-24T21:17:46.8096663Z Uploading finished image to https://rust-lang-ci-sccache2.s3.amazonaws.com/docker/d75f4159e94a655bec830f29c217435ec5e0ac916ddc4020533e7b87fe06a0623bf7377f6d5cd1ca2fd627e09081e1dfacce244379f5b5e14a8d0757d0290bdc
2019-09-24T21:18:50.3500241Z upload failed: - to s3://rust-lang-ci-sccache2/docker/d75f4159e94a655bec830f29c217435ec5e0ac916ddc4020533e7b87fe06a0623bf7377f6d5cd1ca2fd627e09081e1dfacce244379f5b5e14a8d0757d0290bdc An error occurred (InvalidAccessKeyId) when calling the CreateMultipartUpload operation: The AWS Access Key Id you provided does not exist in our records.
2019-09-24T21:18:51.8368295Z [CI_JOB_NAME=x86_64-gnu-llvm-6.0]
2019-09-24T21:18:51.8398324Z == clock drift check ==
2019-09-24T21:18:51.8409057Z   local time: Tue Sep 24 21:18:51 UTC 2019
2019-09-24T21:18:52.0020551Z   network time: Tue, 24 Sep 2019 21:18:51 GMT
---
2019-09-24T21:51:31.0118114Z    Compiling tempfile v3.1.0
2019-09-24T21:51:33.2300113Z    Compiling rustc_macros v0.1.0 (/checkout/src/librustc_macros)
2019-09-24T21:51:34.6162289Z    Compiling arena v0.0.0 (/checkout/src/libarena)
2019-09-24T21:51:45.1567748Z    Compiling syntax_pos v0.0.0 (/checkout/src/libsyntax_pos)
2019-09-24T21:51:46.1810241Z thread 'rustc' panicked at 'assertion failed: elem.index() < self.domain_size', src/librustc_data_structures/bit_set.rs:369:9
2019-09-24T21:51:46.1810516Z 
2019-09-24T21:51:46.1810567Z error: internal compiler error: unexpected panic
2019-09-24T21:51:46.1810599Z 
2019-09-24T21:51:46.1810667Z note: the compiler unexpectedly panicked. this is a bug.
2019-09-24T21:51:46.1810667Z note: the compiler unexpectedly panicked. this is a bug.
2019-09-24T21:51:46.1810700Z 
2019-09-24T21:51:46.1811331Z note: we would appreciate a bug report: ***/blob/master/CONTRIBUTING.md#bug-reports
2019-09-24T21:51:46.1811672Z note: rustc 1.39.0-dev running on x86_64-unknown-linux-gnu
2019-09-24T21:51:46.1811705Z 
2019-09-24T21:51:46.1811705Z 
2019-09-24T21:51:46.1812123Z note: compiler flags: -Z external-macro-backtrace -Z unstable-options -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=2 -C debuginfo=0 -C link-args=-Wl,-rpath,$ORIGIN/../lib -C prefer-dynamic -C debug-assertions=n --crate-type lib
2019-09-24T21:51:46.1812239Z note: some of the compiler flags provided by cargo are hidden
2019-09-24T21:51:46.1812272Z 
2019-09-24T21:51:46.2089431Z error: Could not compile `syntax_pos`.
2019-09-24T21:51:46.2089572Z 
---
2019-09-24T21:51:46.2200580Z == clock drift check ==
2019-09-24T21:51:46.2200654Z   local time: Tue Sep 24 21:51:46 UTC 2019
2019-09-24T21:51:46.3698524Z   network time: Tue, 24 Sep 2019 21:51:46 GMT
2019-09-24T21:51:46.3701672Z == end clock drift check ==
2019-09-24T21:51:47.6917034Z ##[error]Bash exited with code '1'.
2019-09-24T21:51:47.6958134Z ##[section]Starting: Checkout
2019-09-24T21:51:47.6961632Z ==============================================================================
2019-09-24T21:51:47.6961691Z Task         : Get sources
2019-09-24T21:51:47.6961737Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-09-25 21:27 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=9040&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/9040/logs/45), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/9040/logs/45)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-09-25T21:07:21.3680197Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-09-25T21:07:21.3905429Z ##[command]git config gc.auto 0
2019-09-25T21:07:21.3968747Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-09-25T21:07:21.4030294Z ##[command]git config --get-all http.proxy
2019-09-25T21:07:21.4191195Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/64749/merge:refs/remotes/pull/64749/merge
---
2019-09-25T21:12:55.2646486Z  ---> 85b05e3bb556
2019-09-25T21:12:55.2689694Z Successfully built 85b05e3bb556
2019-09-25T21:12:55.4783468Z Successfully tagged rust-ci:latest
2019-09-25T21:12:55.5283128Z Built container sha256:85b05e3bb5563f9a4bbf8035c089b5ad123879637385e48e9f5e4b7a47a706cb
2019-09-25T21:12:55.5301803Z Uploading finished image to https://rust-lang-ci-sccache2.s3.amazonaws.com/docker/d75f4159e94a655bec830f29c217435ec5e0ac916ddc4020533e7b87fe06a0623bf7377f6d5cd1ca2fd627e09081e1dfacce244379f5b5e14a8d0757d0290bdc
2019-09-25T21:13:55.4626335Z upload failed: - to s3://rust-lang-ci-sccache2/docker/d75f4159e94a655bec830f29c217435ec5e0ac916ddc4020533e7b87fe06a0623bf7377f6d5cd1ca2fd627e09081e1dfacce244379f5b5e14a8d0757d0290bdc An error occurred (InvalidAccessKeyId) when calling the CreateMultipartUpload operation: The AWS Access Key Id you provided does not exist in our records.
2019-09-25T21:13:56.9023660Z [CI_JOB_NAME=x86_64-gnu-llvm-6.0]
2019-09-25T21:13:56.9060771Z == clock drift check ==
2019-09-25T21:13:56.9071480Z   local time: Wed Sep 25 21:13:56 UTC 2019
2019-09-25T21:13:57.0589597Z   network time: Wed, 25 Sep 2019 21:13:57 GMT
---
2019-09-25T21:17:38.1899928Z    Compiling serde_json v1.0.40
2019-09-25T21:17:39.9179861Z    Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
2019-09-25T21:17:50.9652158Z     Finished release [optimized] target(s) in 1m 29s
2019-09-25T21:17:50.9742977Z tidy check
2019-09-25T21:17:51.2795158Z tidy error: /checkout/src/test/ui/nll/promoted-liveness.rs: too many trailing newlines (2)
2019-09-25T21:17:52.9259320Z some tidy checks failed
2019-09-25T21:17:52.9261252Z 
2019-09-25T21:17:52.9261252Z 
2019-09-25T21:17:52.9262281Z command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor"
2019-09-25T21:17:52.9262532Z 
2019-09-25T21:17:52.9262551Z 
2019-09-25T21:17:52.9269265Z failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
2019-09-25T21:17:52.9318749Z Build completed unsuccessfully in 0:01:32
2019-09-25T21:17:52.9318749Z Build completed unsuccessfully in 0:01:32
2019-09-25T21:17:52.9327183Z == clock drift check ==
2019-09-25T21:17:52.9342814Z   local time: Wed Sep 25 21:17:52 UTC 2019
2019-09-25T21:17:53.0846227Z   network time: Wed, 25 Sep 2019 21:17:53 GMT
2019-09-25T21:17:53.0851013Z == end clock drift check ==
2019-09-25T21:17:54.4245233Z ##[error]Bash exited with code '1'.
2019-09-25T21:17:54.4283041Z ##[section]Starting: Checkout
2019-09-25T21:17:54.4285933Z ==============================================================================
2019-09-25T21:17:54.4285988Z Task         : Get sources
2019-09-25T21:17:54.4286022Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-10-01 20:54 UTC, nikomatsakis requested changes
r=me with nit addressed in some way

2019-10-01 20:54 UTC, nikomatsakis commented on src/librustc_mir/borrow_check/nll/type_check/liveness/trace.rs
> +    drop_used: Vec<(Local, Location)>,
I found this pretty confusing. I finally realized that this is empty when not in polonius mode, but that was pretty non-obvious. Maybe we can rename this to like `polonius_drop_used_facts` and make it an `Option`?

2019-10-02 21:23 UTC, matthewjasper commented
@bors r=nikomatsakis

2019-10-02 22:40 UTC, Manishearth commented
@bors force

2019-10-02 22:40 UTC, Manishearth commented
@bors retry

2019-10-02 23:52 UTC, rust-highfive commented
Your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=9781&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/9781/logs/74), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/9781/logs/74)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-02T23:50:06.0840546Z Version      : 1.0.0
2019-10-02T23:50:06.0840644Z Author       : Microsoft
2019-10-02T23:50:06.0840711Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
2019-10-02T23:50:06.0840826Z ==============================================================================
2019-10-02T23:50:06.5013192Z System.NullReferenceException: Object reference not set to an instance of an object.
2019-10-02T23:50:06.5014792Z    at Newtonsoft.Json.JsonReader.get_Path()
2019-10-02T23:50:06.5016014Z    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2019-10-02T23:50:06.5017101Z    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2019-10-02T23:50:06.5017610Z    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
2019-10-02T23:50:06.5017893Z    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
2019-10-02T23:50:06.5018153Z    at Agent.PluginHost.Program.Main(String[] args)
2019-10-02T23:50:06.5300003Z ##[error]Exit code 1 returned from process: file name '/home/vsts/agents/2.158.0/bin/Agent.PluginHost', arguments 'task "Agent.Plugins.Repository.CheckoutTask, Agent.Plugins"'.
2019-10-02T23:50:06.5748686Z ##[section]Starting: Upload CPU usage statistics
2019-10-02T23:50:06.5751779Z ==============================================================================
2019-10-02T23:50:06.5751859Z Task         : Bash
2019-10-02T23:50:06.5751929Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-10-02T23:50:06.7172498Z aws s3 cp --acl public-read cpu-usage.csv s3://$DEPLOY_BUCKET/rustc-builds/$BUILD_SOURCEVERSION/cpu-$CI_JOB_NAME.csv
2019-10-02T23:50:06.7194249Z ========================== Starting Command Output ===========================
2019-10-02T23:50:06.7217431Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/39a33c5e-bc43-4692-b5dc-d87366e7d299.sh
2019-10-02T23:50:10.4129418Z 
2019-10-02T23:50:10.4131251Z The user-provided path cpu-usage.csv does not exist.
2019-10-02T23:50:10.4568255Z ##[error]Bash exited with code '255'.
2019-10-02T23:50:10.4581390Z ##[section]Starting: Checkout
2019-10-02T23:50:10.4583104Z ==============================================================================
2019-10-02T23:50:10.4583237Z Task         : Get sources
2019-10-02T23:50:10.4583304Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-10-03 06:52 UTC, matthewjasper commented
@bors retry

2019-10-04 11:20 UTC, merged