WIP Add a shim for functions annotated with `#[track_caller]` (RFC 2091 #2/N)
rust-lang/rust pull request #65082
Opened 2019-10-04 02:16 UTC by anp

Depends on: https://github.com/rust-lang/rust/pull/65037
Tracking issue: https://github.com/rust-lang/rust/issues/47809
[RFC text](https://github.com/rust-lang/rfcs/blob/master/text/2091-inline-semantic.md)

TODO:

* [x] add a `ReifyShim` that is similar to `VirtualShim` in behavior (see #54183)
* [ ] split `ty::Instance::resolve` to `ty::Instance::resolve_direct` and `ty::Instance::resolve_indirect` (leave `ty::Instance::resolve_vtable` alone)
* [ ] `resolve_indirect` returns the shim if calling a `#[track_caller]` function

2019-10-04 02:16 UTC, rust-highfive commented
Some changes occurred in diagnostic error codes

cc @GuillaumeGomez

2019-10-04 02:16 UTC, rust-highfive commented
r? @matthewjasper

(rust_highfive has picked a reviewer for you, use r? to override)

2019-10-04 12:41 UTC, GuillaumeGomez requested changes
Just for precision: I ask for failing examples not only for consistency but also to be **sure** that the error code will still be used by the compiler.

2019-10-04 12:41 UTC, GuillaumeGomez commented on src/librustc/error_codes.rs
> +#[track_caller] and #[naked] cannot be applied to the same function.
Please add a failing example like in the other long error explanation please.

2019-10-04 12:41 UTC, GuillaumeGomez commented on src/librustc/hir/check_attr.rs
> +                E0739,
Why not `E0738`?

2019-10-04 12:41 UTC, GuillaumeGomez commented on src/librustc/hir/check_attr.rs
> +                E0739,
Oh nevermind. Just saw it below.

2019-10-04 12:41 UTC, GuillaumeGomez commented on src/librustc_typeck/error_codes.rs
> +[RFC 2091]: https://github.com/rust-lang/rfcs/blob/master/text/2091-inline-semantic.md
Please add a failing code example.

2019-10-04 12:41 UTC, GuillaumeGomez commented on src/librustc_typeck/error_codes.rs
> +[RFC 2091]: https://github.com/rust-lang/rfcs/blob/master/text/2091-inline-semantic.md
Please add a failing code example.

2019-10-04 14:28 UTC, anp commented
> also to be sure that the error code will still be used by the compiler.

Do you mean this as a test? There are some UI tests that do this.

Also minor nit: the diffs you reviewed are from https://github.com/rust-lang/rust/pull/65037.

2019-10-04 14:38 UTC, GuillaumeGomez commented
@anp Consider this as a backup. It'll at least force the one removing the error code to update the long error explanation.

2019-10-04 23:27 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=9966&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/9966/logs/49), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/9966/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-04T21:40:44.0641462Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-04T21:40:44.0860347Z ##[command]git config gc.auto 0
2019-10-04T21:40:44.0915981Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-04T21:40:44.0999860Z ##[command]git config --get-all http.proxy
2019-10-04T21:40:44.1156938Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65082/merge:refs/remotes/pull/65082/merge
---
2019-10-04T22:40:37.4488678Z .................................................................................................... 1500/9111
2019-10-04T22:40:44.3477161Z .................................................................................................... 1600/9111
2019-10-04T22:40:53.0972768Z .................................................................................................... 1700/9111
2019-10-04T22:41:02.2316637Z .......i...............i............................................................................ 1800/9111
2019-10-04T22:41:09.2458255Z ..................................................................................................ii 1900/9111
2019-10-04T22:41:25.1253319Z iii................................................................................................. 2000/9111
2019-10-04T22:41:33.7725042Z .................................................................................................... 2200/9111
2019-10-04T22:41:36.3746988Z .................................................................................................... 2300/9111
2019-10-04T22:41:42.5468104Z .................................................................................................... 2400/9111
2019-10-04T22:41:47.9395570Z .................................................................................................... 2500/9111
---
2019-10-04T22:44:42.2136023Z ........................................................................................i........... 4700/9111
2019-10-04T22:44:50.1083238Z ....i............................................................................................... 4800/9111
2019-10-04T22:45:00.6864942Z .................................................................................................... 4900/9111
2019-10-04T22:45:06.3538776Z .................................................................................................... 5000/9111
2019-10-04T22:45:18.6378672Z .................................................................................ii.ii.............. 5100/9111
2019-10-04T22:45:28.0852948Z .................................................................................................... 5300/9111
2019-10-04T22:45:38.1528945Z .................................................................................................... 5400/9111
2019-10-04T22:45:45.0836933Z ...............................................i.................................................... 5500/9111
2019-10-04T22:45:51.9040481Z .................................................................................................... 5600/9111
2019-10-04T22:45:51.9040481Z .................................................................................................... 5600/9111
2019-10-04T22:46:02.3586560Z .................................................................................................... 5700/9111
2019-10-04T22:46:10.1101139Z ............................................ii...i..ii...........i.................................. 5800/9111
2019-10-04T22:46:35.8050044Z .................................................................................................... 6000/9111
2019-10-04T22:46:44.1237280Z .................................................................................................... 6100/9111
2019-10-04T22:46:44.1237280Z .................................................................................................... 6100/9111
2019-10-04T22:46:54.9541671Z ..................................................i..ii............................................. 6200/9111
2019-10-04T22:47:18.8240179Z .................................................................................................... 6400/9111
2019-10-04T22:47:20.9803526Z ..........i......................................................................................... 6500/9111
2019-10-04T22:47:23.1728607Z ..................................................................................i................. 6600/9111
2019-10-04T22:47:25.8446650Z .................................................................................................... 6700/9111
---
2019-10-04T22:51:56.2615820Z  finished in 5.642
2019-10-04T22:51:56.2808957Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-04T22:51:56.4475858Z 
2019-10-04T22:51:56.4476171Z running 150 tests
2019-10-04T22:51:59.6850494Z i....iii......iii..iiii....i.............................i..i..................i....i.........ii.i.i 100/150
2019-10-04T22:52:01.6788308Z ..iiii..............i.........iii.i.......ii......
2019-10-04T22:52:01.6789623Z 
2019-10-04T22:52:01.6792947Z  finished in 5.398
2019-10-04T22:52:01.6969527Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-04T22:52:02.5270112Z 
---
2019-10-04T22:52:03.9744377Z  finished in 2.277
2019-10-04T22:52:03.9939856Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-04T22:52:04.1562019Z 
2019-10-04T22:52:04.1562258Z running 9 tests
2019-10-04T22:52:04.1563193Z iiiiiiiii
2019-10-04T22:52:04.1563611Z 
2019-10-04T22:52:04.1563681Z  finished in 0.162
2019-10-04T22:52:04.1749100Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-04T22:52:05.0228154Z 
---
2019-10-04T22:52:22.1976537Z  finished in 18.022
2019-10-04T22:52:22.2162908Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-04T22:52:22.3791620Z 
2019-10-04T22:52:22.3792538Z running 123 tests
2019-10-04T22:52:45.8762618Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....ii..........iiii..........i...ii...i.......ii. 100/123
2019-10-04T22:52:50.4850790Z i.i.i......iii.i.....ii
2019-10-04T22:52:50.4852377Z 
2019-10-04T22:52:50.4856345Z  finished in 28.269
2019-10-04T22:52:50.4866566Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-04T22:52:50.4867290Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-10-04T23:04:57.6936923Z 
2019-10-04T23:04:57.6938696Z    Doc-tests core
2019-10-04T23:05:02.2916573Z 
2019-10-04T23:05:02.2917962Z running 2405 tests
2019-10-04T23:05:12.8163224Z ......iiiii......................................................................................... 100/2405
2019-10-04T23:05:23.2443683Z ...............................................................................ii................... 200/2405
2019-10-04T23:05:46.8863100Z .i.. [...]

2019-10-05 18:01 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=10001&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10001/logs/49), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10001/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-05T16:04:06.0582768Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-05T16:04:06.0807250Z ##[command]git config gc.auto 0
2019-10-05T16:04:06.0893673Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-05T16:04:06.0955840Z ##[command]git config --get-all http.proxy
2019-10-05T16:04:06.1116677Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65082/merge:refs/remotes/pull/65082/merge
---
2019-10-05T17:08:44.6624095Z .................................................................................................... 1500/9113
2019-10-05T17:08:51.9727384Z .................................................................................................... 1600/9113
2019-10-05T17:09:01.4949456Z .................................................................................................... 1700/9113
2019-10-05T17:09:11.4079366Z .......i...............i............................................................................ 1800/9113
2019-10-05T17:09:18.9987154Z ..................................................................................................ii 1900/9113
2019-10-05T17:09:36.6749341Z iii................................................................................................. 2000/9113
2019-10-05T17:09:46.0562335Z .................................................................................................... 2200/9113
2019-10-05T17:09:48.8595543Z .................................................................................................... 2300/9113
2019-10-05T17:09:55.4763384Z .................................................................................................... 2400/9113
2019-10-05T17:10:01.4996916Z .................................................................................................... 2500/9113
---
2019-10-05T17:13:04.7378625Z ........................................................................................i........... 4700/9113
2019-10-05T17:13:12.9975780Z ....i............................................................................................... 4800/9113
2019-10-05T17:13:24.1829956Z .................................................................................................... 4900/9113
2019-10-05T17:13:30.2263379Z .................................................................................................... 5000/9113
2019-10-05T17:13:43.1612027Z .................................................................................ii.ii.............. 5100/9113
2019-10-05T17:13:53.1205431Z .................................................................................................... 5300/9113
2019-10-05T17:14:03.7085890Z .................................................................................................... 5400/9113
2019-10-05T17:14:10.9569340Z ...............................................i.................................................... 5500/9113
2019-10-05T17:14:18.3108163Z .................................................................................................... 5600/9113
2019-10-05T17:14:18.3108163Z .................................................................................................... 5600/9113
2019-10-05T17:14:29.3466259Z .................................................................................................... 5700/9113
2019-10-05T17:14:37.4339625Z ............................................ii...i..ii...........i.................................. 5800/9113
2019-10-05T17:15:04.4334625Z .................................................................................................... 6000/9113
2019-10-05T17:15:14.2376322Z .................................................................................................... 6100/9113
2019-10-05T17:15:14.2376322Z .................................................................................................... 6100/9113
2019-10-05T17:15:28.8322139Z ..................................................i..ii............................................. 6200/9113
2019-10-05T17:15:54.1817428Z .................................................................................................... 6400/9113
2019-10-05T17:15:56.4520298Z ..........i......................................................................................... 6500/9113
2019-10-05T17:15:58.8633361Z ..................................................................................i................. 6600/9113
2019-10-05T17:16:01.7485008Z .................................................................................................... 6700/9113
---
2019-10-05T17:20:53.3436808Z  finished in 5.767
2019-10-05T17:20:53.3641183Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-05T17:20:53.5626718Z 
2019-10-05T17:20:53.5626953Z running 150 tests
2019-10-05T17:20:56.9537688Z i....iii......iii..iiii....i.............................i..i..................i....i.........ii.i.i 100/150
2019-10-05T17:20:59.1099817Z ..iiii..............i.........iii.i.......ii......
2019-10-05T17:20:59.1101933Z 
2019-10-05T17:20:59.1105216Z  finished in 5.746
2019-10-05T17:20:59.1302374Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-05T17:20:59.3034882Z 
---
2019-10-05T17:21:01.5046421Z  finished in 2.374
2019-10-05T17:21:01.5249684Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-05T17:21:01.6935013Z 
2019-10-05T17:21:01.6935237Z running 9 tests
2019-10-05T17:21:01.6936162Z iiiiiiiii
2019-10-05T17:21:01.6936582Z 
2019-10-05T17:21:01.6936635Z  finished in 0.168
2019-10-05T17:21:01.7151390Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-05T17:21:01.9064121Z 
---
2019-10-05T17:21:21.0786959Z  finished in 19.363
2019-10-05T17:21:21.1010440Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-05T17:21:21.2853993Z 
2019-10-05T17:21:21.2854191Z running 123 tests
2019-10-05T17:21:47.0345836Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....ii..........iiii..........i...ii...i.......ii. 100/123
2019-10-05T17:21:52.0071756Z i.i.i......iii.i.....ii
2019-10-05T17:21:52.0074054Z 
2019-10-05T17:21:52.0079339Z  finished in 30.907
2019-10-05T17:21:52.0090732Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-05T17:21:52.0091188Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-10-05T17:35:35.8987336Z 
2019-10-05T17:35:35.9012704Z    Doc-tests core
2019-10-05T17:35:40.9973649Z 
2019-10-05T17:35:40.9974590Z running 2405 tests
2019-10-05T17:35:53.1855995Z ......iiiii......................................................................................... 100/2405
2019-10-05T17:36:05.2898015Z ...............................................................................ii................... 200/2405
2019-10-05T17:36:33.0654300Z . [...]

2019-10-06 00:43 UTC, rust-highfive commented
The job `mingw-check` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=10026&view=logs&jobId=4f922444-fdfe-5dcf-b824-02f86439ef14) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10026/logs/45), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10026/logs/45)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-06T00:31:36.9881678Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-06T00:31:37.0118604Z ##[command]git config gc.auto 0
2019-10-06T00:31:37.0202136Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-06T00:31:37.0273569Z ##[command]git config --get-all http.proxy
2019-10-06T00:31:37.0422394Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65082/merge:refs/remotes/pull/65082/merge
---
2019-10-06T00:39:29.9609852Z     Checking syntax_pos v0.0.0 (/checkout/src/libsyntax_pos)
2019-10-06T00:39:31.4397033Z     Checking rustc_errors v0.0.0 (/checkout/src/librustc_errors)
2019-10-06T00:39:32.6915192Z     Checking fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2019-10-06T00:39:45.1769093Z     Checking syntax_ext v0.0.0 (/checkout/src/libsyntax_ext)
2019-10-06T00:39:48.7275906Z error[E0425]: cannot find value `is_reify_shim` in this scope
2019-10-06T00:39:48.7277443Z    --> src/librustc/ty/instance.rs:311:12
2019-10-06T00:39:48.7278419Z 311 |         if is_reify_shim {
2019-10-06T00:39:48.7279135Z     |            ^^^^^^^^^^^^^ not found in this scope
2019-10-06T00:39:48.7279379Z 
2019-10-06T00:40:09.9384321Z error: aborting due to previous error
---
2019-10-06T00:40:10.1237428Z == clock drift check ==
2019-10-06T00:40:10.1255978Z   local time: Sun Oct  6 00:40:10 UTC 2019
2019-10-06T00:40:10.2664912Z   network time: Sun, 06 Oct 2019 00:40:10 GMT
2019-10-06T00:40:10.2669930Z == end clock drift check ==
2019-10-06T00:40:11.0935435Z ##[error]Bash exited with code '1'.
2019-10-06T00:40:11.0967494Z ##[section]Starting: Checkout
2019-10-06T00:40:11.0969078Z ==============================================================================
2019-10-06T00:40:11.0969517Z Task         : Get sources
2019-10-06T00:40:11.0969573Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-10-07 15:16 UTC, anp commented
I had some fun with git history and opened a new PR: https://github.com/rust-lang/rust/pull/65182

2019-10-07 15:16 UTC, closed without merging