Add Cow::is_borrowed and Cow::is_owned
rust-lang/rust pull request #65144
Opened 2019-10-05 22:24 UTC by clarfon

Implements #65143.

2019-10-05 22:24 UTC, rust-highfive commented
r? @TimNN

(rust_highfive has picked a reviewer for you, use r? to override)

2019-10-06 01:57 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=10029&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10029/logs/49), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10029/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-06T00:33:31.2282905Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-06T00:33:31.2473514Z ##[command]git config gc.auto 0
2019-10-06T00:33:31.2562829Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-06T00:33:31.2620722Z ##[command]git config --get-all http.proxy
2019-10-06T00:33:31.2768461Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65144/merge:refs/remotes/pull/65144/merge
---
2019-10-06T01:33:36.4265364Z .................................................................................................... 1500/9104
2019-10-06T01:33:43.1074537Z .................................................................................................... 1600/9104
2019-10-06T01:33:51.9619148Z .................................................................................................... 1700/9104
2019-10-06T01:34:01.0618481Z .......i...............i............................................................................ 1800/9104
2019-10-06T01:34:08.0720700Z ..................................................................................................ii 1900/9104
2019-10-06T01:34:23.7950031Z iii................................................................................................. 2000/9104
2019-10-06T01:34:32.3942185Z .................................................................................................... 2200/9104
2019-10-06T01:34:34.9116551Z .................................................................................................... 2300/9104
2019-10-06T01:34:40.9033884Z .................................................................................................... 2400/9104
2019-10-06T01:34:46.2088307Z .................................................................................................... 2500/9104
---
2019-10-06T01:37:35.0289565Z .......................................................................................i............ 4700/9104
2019-10-06T01:37:42.5119629Z ...i................................................................................................ 4800/9104
2019-10-06T01:37:52.7875171Z .................................................................................................... 4900/9104
2019-10-06T01:37:58.3294195Z .................................................................................................... 5000/9104
2019-10-06T01:38:10.0470435Z ................................................................................ii.ii............... 5100/9104
2019-10-06T01:38:19.2620072Z .................................................................................................... 5300/9104
2019-10-06T01:38:28.9313218Z .................................................................................................... 5400/9104
2019-10-06T01:38:35.7658156Z ...............................................i.................................................... 5500/9104
2019-10-06T01:38:42.7710582Z .................................................................................................... 5600/9104
2019-10-06T01:38:42.7710582Z .................................................................................................... 5600/9104
2019-10-06T01:38:53.3836277Z .................................................................................................... 5700/9104
2019-10-06T01:39:00.6740314Z ...........................................ii...i..ii...........i................................... 5800/9104
2019-10-06T01:39:26.2131900Z .................................................................................................... 6000/9104
2019-10-06T01:39:34.9581164Z .................................................................................................... 6100/9104
2019-10-06T01:39:34.9581164Z .................................................................................................... 6100/9104
2019-10-06T01:39:47.3633558Z .................................................i..ii.............................................. 6200/9104
2019-10-06T01:40:10.3853354Z .................................................................................................... 6400/9104
2019-10-06T01:40:12.6147557Z .........i.......................................................................................... 6500/9104
2019-10-06T01:40:14.7360826Z .................................................................................i.................. 6600/9104
2019-10-06T01:40:17.3119975Z .................................................................................................... 6700/9104
---
2019-10-06T01:44:45.1529432Z  finished in 5.588
2019-10-06T01:44:45.1668389Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T01:44:45.3258705Z 
2019-10-06T01:44:45.3259121Z running 150 tests
2019-10-06T01:44:48.6388513Z i....iii......iii..iiii....i.............................i..i..................i....i.........ii.i.i 100/150
2019-10-06T01:44:50.6553879Z ..iiii..............i.........iii.i.......ii......
2019-10-06T01:44:50.6554534Z 
2019-10-06T01:44:50.6560141Z  finished in 5.488
2019-10-06T01:44:50.6779118Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T01:44:50.8565711Z 
---
2019-10-06T01:44:53.0053182Z  finished in 2.327
2019-10-06T01:44:53.0229298Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T01:44:53.1874358Z 
2019-10-06T01:44:53.1874659Z running 9 tests
2019-10-06T01:44:53.1876757Z iiiiiiiii
2019-10-06T01:44:53.1877238Z 
2019-10-06T01:44:53.1877299Z  finished in 0.164
2019-10-06T01:44:53.2065332Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T01:44:53.3779350Z 
---
2019-10-06T01:45:11.6060080Z  finished in 18.399
2019-10-06T01:45:11.6249098Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T01:45:11.7840912Z 
2019-10-06T01:45:11.7841233Z running 123 tests
2019-10-06T01:45:35.6097913Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....ii..........iiii..........i...ii...i.......ii. 100/123
2019-10-06T01:45:40.2016923Z i.i.i......iii.i.....ii
2019-10-06T01:45:40.2017548Z 
2019-10-06T01:45:40.2064277Z  finished in 28.577
2019-10-06T01:45:40.2064870Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T01:45:40.2065182Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-10-06T01:57:19.4488135Z .................................................................................................... 400/461
2019-10-06T01:57:27.5191424Z .............................................................
2019-10-06T01:57:27.5192332Z failures:
2019-10-06T01:57:27.5192541Z 
2019-10-06T01:57:27.5194353Z ---- borrow.rs - borrow::Cow::is_borrowed (line 214) stdout ----
2019-10-06T01:57:27.5195017Z error[E0658]: use of unstable library feat [...]

2019-10-06 02:00 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=10030&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10030/logs/49), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10030/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-06T00:33:32.7788485Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-06T00:33:32.8097676Z ##[command]git config gc.auto 0
2019-10-06T00:33:32.8180362Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-06T00:33:32.8241102Z ##[command]git config --get-all http.proxy
2019-10-06T00:33:32.8407093Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65144/merge:refs/remotes/pull/65144/merge
---
2019-10-06T01:35:26.1979670Z .................................................................................................... 1500/9104
2019-10-06T01:35:33.4911177Z .................................................................................................... 1600/9104
2019-10-06T01:35:42.6903967Z .................................................................................................... 1700/9104
2019-10-06T01:35:52.1667198Z .......i...............i............................................................................ 1800/9104
2019-10-06T01:35:59.8415364Z ..................................................................................................ii 1900/9104
2019-10-06T01:36:16.8885280Z iii................................................................................................. 2000/9104
2019-10-06T01:36:26.2056796Z .................................................................................................... 2200/9104
2019-10-06T01:36:28.9994155Z .................................................................................................... 2300/9104
2019-10-06T01:36:35.7230312Z .................................................................................................... 2400/9104
2019-10-06T01:36:41.5532791Z .................................................................................................... 2500/9104
---
2019-10-06T01:39:43.1648192Z .......................................................................................i............ 4700/9104
2019-10-06T01:39:51.2088856Z ...i................................................................................................ 4800/9104
2019-10-06T01:40:01.8784675Z .................................................................................................... 4900/9104
2019-10-06T01:40:07.5386888Z .................................................................................................... 5000/9104
2019-10-06T01:40:19.9780026Z ................................................................................ii.ii............... 5100/9104
2019-10-06T01:40:29.9585469Z .................................................................................................... 5300/9104
2019-10-06T01:40:40.3552941Z .................................................................................................... 5400/9104
2019-10-06T01:40:47.5044056Z ..............................................i..................................................... 5500/9104
2019-10-06T01:40:54.8615266Z .................................................................................................... 5600/9104
2019-10-06T01:40:54.8615266Z .................................................................................................... 5600/9104
2019-10-06T01:41:05.9861857Z .................................................................................................... 5700/9104
2019-10-06T01:41:14.0698294Z ...........................................ii...i..ii...........i................................... 5800/9104
2019-10-06T01:41:40.8697938Z .................................................................................................... 6000/9104
2019-10-06T01:41:50.3550737Z .................................................................................................... 6100/9104
2019-10-06T01:41:50.3550737Z .................................................................................................... 6100/9104
2019-10-06T01:42:02.0349382Z .................................................i..ii.............................................. 6200/9104
2019-10-06T01:42:26.7377733Z .................................................................................................... 6400/9104
2019-10-06T01:42:29.0099570Z .........i.......................................................................................... 6500/9104
2019-10-06T01:42:31.3582683Z .................................................................................i.................. 6600/9104
2019-10-06T01:42:34.1866645Z .................................................................................................... 6700/9104
---
2019-10-06T01:47:19.8560616Z  finished in 5.652
2019-10-06T01:47:19.8748444Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T01:47:20.0349932Z 
2019-10-06T01:47:20.0350040Z running 150 tests
2019-10-06T01:47:23.3070552Z i....iii......iii..iiii....i.............................i..i..................i....i.........ii.i.i 100/150
2019-10-06T01:47:25.3366432Z ..iiii..............i.........iii.i.......ii......
2019-10-06T01:47:25.3368988Z 
2019-10-06T01:47:25.3376348Z  finished in 5.462
2019-10-06T01:47:25.3560659Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T01:47:26.3357364Z 
---
2019-10-06T01:47:27.6918504Z  finished in 2.335
2019-10-06T01:47:27.7125919Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T01:47:27.8779586Z 
2019-10-06T01:47:27.8779843Z running 9 tests
2019-10-06T01:47:27.8780651Z iiiiiiiii
2019-10-06T01:47:27.8780898Z 
2019-10-06T01:47:27.8786916Z  finished in 0.166
2019-10-06T01:47:27.8976372Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T01:47:28.8366697Z 
---
2019-10-06T01:47:46.9457002Z  finished in 19.048
2019-10-06T01:47:46.9666970Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T01:47:47.1426425Z 
2019-10-06T01:47:47.1426877Z running 123 tests
2019-10-06T01:48:13.0683541Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....ii..........iiii..........i...ii...i.......ii. 100/123
2019-10-06T01:48:18.0644039Z i.i.i......iii.i.....ii
2019-10-06T01:48:18.0645502Z 
2019-10-06T01:48:18.0649166Z  finished in 31.098
2019-10-06T01:48:18.0658753Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T01:48:18.0661642Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-10-06T02:00:16.5419895Z .................................................................................................... 400/461
2019-10-06T02:00:24.8730264Z .............................................................
2019-10-06T02:00:24.8731298Z failures:
2019-10-06T02:00:24.8735089Z 
2019-10-06T02:00:24.8736664Z ---- borrow.rs - borrow::Cow::is_borrowed (line 214) stdout ----
2019-10-06T02:00:24.8737459Z error[E0658]: use of unstable library feat [...]

2019-10-06 05:36 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=10040&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10040/logs/49), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10040/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-06T04:07:52.5265142Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-06T04:07:52.5446906Z ##[command]git config gc.auto 0
2019-10-06T04:07:52.5522577Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-06T04:07:52.5577249Z ##[command]git config --get-all http.proxy
2019-10-06T04:07:52.5745486Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65144/merge:refs/remotes/pull/65144/merge
---
2019-10-06T05:11:14.5699755Z .................................................................................................... 1500/9104
2019-10-06T05:11:21.7400695Z .................................................................................................... 1600/9104
2019-10-06T05:11:31.0746203Z .................................................................................................... 1700/9104
2019-10-06T05:11:40.7690723Z .......i...............i............................................................................ 1800/9104
2019-10-06T05:11:48.2796156Z ..................................................................................................ii 1900/9104
2019-10-06T05:12:05.1645949Z iii................................................................................................. 2000/9104
2019-10-06T05:12:14.0639652Z .................................................................................................... 2200/9104
2019-10-06T05:12:16.7672923Z .................................................................................................... 2300/9104
2019-10-06T05:12:23.1948431Z .................................................................................................... 2400/9104
2019-10-06T05:12:28.9074261Z .................................................................................................... 2500/9104
---
2019-10-06T05:15:31.1430641Z .......................................................................................i............ 4700/9104
2019-10-06T05:15:39.3133279Z ...i................................................................................................ 4800/9104
2019-10-06T05:15:50.4515056Z .................................................................................................... 4900/9104
2019-10-06T05:15:56.2824306Z .................................................................................................... 5000/9104
2019-10-06T05:16:08.9014216Z ................................................................................ii.ii............... 5100/9104
2019-10-06T05:16:18.6252382Z .................................................................................................... 5300/9104
2019-10-06T05:16:28.8504915Z .................................................................................................... 5400/9104
2019-10-06T05:16:36.0107111Z ..............................................i..................................................... 5500/9104
2019-10-06T05:16:43.1832156Z .................................................................................................... 5600/9104
2019-10-06T05:16:43.1832156Z .................................................................................................... 5600/9104
2019-10-06T05:16:54.1231568Z .................................................................................................... 5700/9104
2019-10-06T05:17:02.2351369Z ...........................................ii...i..ii...........i................................... 5800/9104
2019-10-06T05:17:28.7491128Z .................................................................................................... 6000/9104
2019-10-06T05:17:38.1562699Z .................................................................................................... 6100/9104
2019-10-06T05:17:38.1562699Z .................................................................................................... 6100/9104
2019-10-06T05:17:51.0287350Z .................................................i..ii.............................................. 6200/9104
2019-10-06T05:18:15.9414444Z .................................................................................................... 6400/9104
2019-10-06T05:18:18.1355318Z .........i.......................................................................................... 6500/9104
2019-10-06T05:18:20.4035779Z .................................................................................i.................. 6600/9104
2019-10-06T05:18:23.2102202Z .................................................................................................... 6700/9104
---
2019-10-06T05:23:08.2245601Z  finished in 5.695
2019-10-06T05:23:08.2455230Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T05:23:08.4176122Z 
2019-10-06T05:23:08.4177026Z running 150 tests
2019-10-06T05:23:11.7245930Z i....iii......iii..iiii....i.............................i..i..................i....i.........ii.i.i 100/150
2019-10-06T05:23:13.8424332Z ..iiii..............i.........iii.i.......ii......
2019-10-06T05:23:13.8424897Z 
2019-10-06T05:23:13.8424955Z  finished in 5.597
2019-10-06T05:23:13.8610125Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T05:23:14.0340462Z 
---
2019-10-06T05:23:16.1896782Z  finished in 2.328
2019-10-06T05:23:16.2092827Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T05:23:16.3758303Z 
2019-10-06T05:23:16.3758636Z running 9 tests
2019-10-06T05:23:16.3759557Z iiiiiiiii
2019-10-06T05:23:16.3760192Z 
2019-10-06T05:23:16.3760266Z  finished in 0.166
2019-10-06T05:23:16.3949477Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T05:23:16.5679932Z 
---
2019-10-06T05:23:35.6197422Z  finished in 19.225
2019-10-06T05:23:35.6403211Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T05:23:35.8154825Z 
2019-10-06T05:23:35.8155548Z running 123 tests
2019-10-06T05:24:01.4705042Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....ii..........iiii..........i...ii...i.......ii. 100/123
2019-10-06T05:24:06.3341735Z i.i.i......iii.i.....ii
2019-10-06T05:24:06.3345376Z 
2019-10-06T05:24:06.3345807Z  finished in 30.694
2019-10-06T05:24:06.3353074Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-06T05:24:06.3353782Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-10-06T05:36:23.2689705Z ---- borrow.rs - borrow::Cow::is_owned (line 236) stdout ----
2019-10-06T05:36:23.2689756Z error[E0282]: type annotations needed
2019-10-06T05:36:23.2689970Z  --> borrow.rs:241:13
2019-10-06T05:36:23.2690014Z   |
2019-10-06T05:36:23.2690054Z 8 | assert!(cow.is_owned());
2019-10-06T05:36:23.2690159Z   |
2019-10-06T05:36:23.2690199Z   = note: type must be known at this point
2019-10-06T05:36:23.2690227Z 
2019-10-06T05:36:23.2690497Z [...]

2019-10-07 02:47 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=10102&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10102/logs/49), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10102/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-07T01:18:21.8943794Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-07T01:18:21.9156232Z ##[command]git config gc.auto 0
2019-10-07T01:18:21.9218504Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-07T01:18:21.9270515Z ##[command]git config --get-all http.proxy
2019-10-07T01:18:22.6036399Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65144/merge:refs/remotes/pull/65144/merge
---
2019-10-07T02:21:32.6853103Z .................................................................................................... 1600/9111
2019-10-07T02:21:42.0383833Z .................................................................................................... 1700/9111
2019-10-07T02:21:52.2387072Z .........i...............i.......................................................................... 1800/9111
2019-10-07T02:21:59.9845417Z .................................................................................................... 1900/9111
2019-10-07T02:22:16.8876300Z iiiii............................................................................................... 2000/9111
2019-10-07T02:22:26.4759973Z .................................................................................................... 2200/9111
2019-10-07T02:22:29.2450857Z .................................................................................................... 2300/9111
2019-10-07T02:22:35.7210938Z .................................................................................................... 2400/9111
2019-10-07T02:22:41.6000600Z .................................................................................................... 2500/9111
---
2019-10-07T02:25:43.3779891Z .........................................................................................i.......... 4700/9111
2019-10-07T02:25:51.4690150Z .....i.............................................................................................. 4800/9111
2019-10-07T02:26:02.8894034Z .................................................................................................... 4900/9111
2019-10-07T02:26:08.5941142Z .................................................................................................... 5000/9111
2019-10-07T02:26:21.3494960Z ...................................................................................ii.ii............ 5100/9111
2019-10-07T02:26:31.3588188Z .................................................................................................... 5300/9111
2019-10-07T02:26:42.0726223Z .................................................................................................... 5400/9111
2019-10-07T02:26:49.1253860Z .................................................i.................................................. 5500/9111
2019-10-07T02:26:56.4255351Z .................................................................................................... 5600/9111
2019-10-07T02:26:56.4255351Z .................................................................................................... 5600/9111
2019-10-07T02:27:07.2510436Z .................................................................................................... 5700/9111
2019-10-07T02:27:15.9472710Z ..............................................ii...i..ii...........i................................ 5800/9111
2019-10-07T02:27:42.8028640Z .................................................................................................... 6000/9111
2019-10-07T02:27:52.7882440Z .................................................................................................... 6100/9111
2019-10-07T02:27:52.7882440Z .................................................................................................... 6100/9111
2019-10-07T02:28:05.1762259Z ....................................................i..ii........................................... 6200/9111
2019-10-07T02:28:33.8052804Z .................................................................................................... 6400/9111
2019-10-07T02:28:36.0478061Z ............i....................................................................................... 6500/9111
2019-10-07T02:28:38.4030930Z .....................................................................................i.............. 6600/9111
2019-10-07T02:28:41.3019244Z .................................................................................................... 6700/9111
---
2019-10-07T02:33:33.1382893Z  finished in 5.861
2019-10-07T02:33:33.1587282Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-07T02:33:33.3318953Z 
2019-10-07T02:33:33.3319482Z running 150 tests
2019-10-07T02:33:36.8035976Z i....iii......iii..iiii....i.............................i..i..................i....i.........ii.i.i 100/150
2019-10-07T02:33:38.9091150Z ..iiii..............i.........iii.i.......ii......
2019-10-07T02:33:38.9095601Z 
2019-10-07T02:33:38.9097896Z  finished in 5.751
2019-10-07T02:33:38.9326193Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-07T02:33:39.1052220Z 
---
2019-10-07T02:33:41.2972447Z  finished in 2.365
2019-10-07T02:33:41.3175536Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-07T02:33:41.4838138Z 
2019-10-07T02:33:41.4840027Z running 9 tests
2019-10-07T02:33:41.4841398Z iiiiiiiii
2019-10-07T02:33:41.4841819Z 
2019-10-07T02:33:41.4851468Z  finished in 0.166
2019-10-07T02:33:41.5045664Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-07T02:33:41.7022739Z 
---
2019-10-07T02:34:01.0325573Z  finished in 19.528
2019-10-07T02:34:01.0545005Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-07T02:34:01.2266334Z 
2019-10-07T02:34:01.2267294Z running 123 tests
2019-10-07T02:34:27.4171558Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....ii..........iiii..........i...ii...i.......ii. 100/123
2019-10-07T02:34:32.5254902Z i.i.i......iii.i.....ii
2019-10-07T02:34:32.5260089Z 
2019-10-07T02:34:32.5267016Z  finished in 31.472
2019-10-07T02:34:32.5277326Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-07T02:34:32.5278230Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-10-07T02:47:21.8715654Z ---- borrow.rs - borrow::Cow::is_borrowed (line 214) stdout ----
2019-10-07T02:47:21.8715733Z error: variable does not need to be mutable
2019-10-07T02:47:21.8715964Z  --> borrow.rs:218:5
2019-10-07T02:47:21.8716009Z   |
2019-10-07T02:47:21.8716071Z 7 | let mut cow = Cow::Borrowed("moo");
2019-10-07T02:47:21.8716535Z   |     |
2019-10-07T02:47:21.8716576Z   |     help: remove this `mut`
2019-10-07T02:47:21.8716632Z   |
2019-10-07T02:47:21.8716671Z note: lint level defined here
2019-10-07T02:47:21.8716671Z note: lint level defined here
2019-10-07T02:47:21.8716868Z  --> [...]

2019-10-07 07:13 UTC, hellow554 commented
You can run the tests locally i.e. with `./x.py test --stage 1` so you don't have to wait for azure to report the errors to you

2019-10-07 07:23 UTC, hellow554 requested changes

2019-10-07 07:23 UTC, hellow554 commented on src/liballoc/borrow.rs
> +    /// let mut cow = Cow::Borrowed("moo");
`let cow = Cow::Borrowed("moo");`

2019-10-07 07:23 UTC, hellow554 commented on src/liballoc/borrow.rs
> +    /// let mut bull: Cow<'_, str> = Cow::Owned("...moo?".to_string());
`let bull: Cow<str> = Cow::Owned("...moo?".to_string());`

2019-10-07 07:23 UTC, hellow554 commented on src/liballoc/borrow.rs
> +        }
Why not: `!self.is_borrowed()`? (see [`is_some`/`is_none`](https://github.com/rust-lang/rust/blob/4ac4809ccf5f77083ae7155dcc83e921341c2614/src/libcore/option.rs#L184-L210), [`is_ok`/`is_err`](https://github.com/rust-lang/rust/blob/4ac4809ccf5f77083ae7155dcc83e921341c2614/src/libcore/result.rs#L283-L310))

2019-10-07 07:23 UTC, hellow554 commented on src/liballoc/borrow.rs
> +    /// let mut cow: Cow<'_, str> = Cow::Owned("moo".to_string());
`let cow: Cow<str> = Cow::Owned("moo".to_string());`

2019-10-07 07:23 UTC, hellow554 commented on src/liballoc/borrow.rs
> +    /// let mut bull = Cow::Borrowed("...moo?".to_string());
`let bull = Cow::Borrowed("...moo?");`

same as above, but if you want to use a `String` instead do:

`let bull: Cow<str> = Cow::Borrowed("...moo?".to_string());`

2019-10-08 23:06 UTC, clarfon commented
> You can run the tests locally i.e. with ./x.py test --stage 1 so you don't have to wait for azure to report the errors to you

That would make too much sense

2019-10-09 01:04 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=10253&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10253/logs/49), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10253/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-08T23:07:15.7294305Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-08T23:07:15.7517100Z ##[command]git config gc.auto 0
2019-10-08T23:07:15.7613414Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-08T23:07:15.7698181Z ##[command]git config --get-all http.proxy
2019-10-08T23:07:15.7871469Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65144/merge:refs/remotes/pull/65144/merge
---
2019-10-09T00:12:55.2357537Z .................................................................................................... 1600/9127
2019-10-09T00:13:03.5259004Z .................................................................................................... 1700/9127
2019-10-09T00:13:15.2887012Z ................i...............i................................................................... 1800/9127
2019-10-09T00:13:23.0083890Z .................................................................................................... 1900/9127
2019-10-09T00:13:40.8012726Z .......iiiii........................................................................................ 2000/9127
2019-10-09T00:13:51.3393278Z .................................................................................................... 2200/9127
2019-10-09T00:13:54.1764301Z .................................................................................................... 2300/9127
2019-10-09T00:14:00.3523370Z .................................................................................................... 2400/9127
2019-10-09T00:14:06.9472951Z .................................................................................................... 2500/9127
---
2019-10-09T00:17:12.7218680Z ................................................................................................i... 4700/9127
2019-10-09T00:17:20.5261005Z ............i....................................................................................... 4800/9127
2019-10-09T00:17:32.4309346Z .................................................................................................... 4900/9127
2019-10-09T00:17:38.4900630Z .................................................................................................... 5000/9127
2019-10-09T00:17:51.1908269Z ..........................................................................................ii.ii..... 5100/9127
2019-10-09T00:18:01.7158147Z .................................................................................................... 5300/9127
2019-10-09T00:18:12.0837575Z .................................................................................................... 5400/9127
2019-10-09T00:18:19.7187233Z ........................................................i........................................... 5500/9127
2019-10-09T00:18:27.3442446Z .................................................................................................... 5600/9127
2019-10-09T00:18:27.3442446Z .................................................................................................... 5600/9127
2019-10-09T00:18:36.0557354Z .................................................................................................... 5700/9127
2019-10-09T00:18:47.7983363Z .....................................................ii...i..ii...........i......................... 5800/9127
2019-10-09T00:19:15.2295243Z .................................................................................................... 6000/9127
2019-10-09T00:19:25.0252107Z .................................................................................................... 6100/9127
2019-10-09T00:19:25.0252107Z .................................................................................................... 6100/9127
2019-10-09T00:19:36.2929129Z ...........................................................i..ii.................................... 6200/9127
2019-10-09T00:20:05.6316099Z .................................................................................................... 6400/9127
2019-10-09T00:20:07.8936438Z ...................i................................................................................ 6500/9127
2019-10-09T00:20:10.2725729Z ............................................................................................i....... 6600/9127
2019-10-09T00:20:13.2472168Z .................................................................................................... 6700/9127
---
2019-10-09T00:25:06.8526980Z  finished in 5.816
2019-10-09T00:25:06.8730720Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-09T00:25:07.0419510Z 
2019-10-09T00:25:07.0419777Z running 150 tests
2019-10-09T00:25:10.5720998Z i....iii......iii..iiii....i.............................i..i..................i....i.........ii.i.i 100/150
2019-10-09T00:25:12.6907119Z ..iiii..............i.........iii.i.......ii......
2019-10-09T00:25:12.6907585Z 
2019-10-09T00:25:12.6911923Z  finished in 5.818
2019-10-09T00:25:12.7105780Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-09T00:25:12.8748287Z 
---
2019-10-09T00:25:15.0601803Z  finished in 2.349
2019-10-09T00:25:15.0785253Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-09T00:25:15.2406808Z 
2019-10-09T00:25:15.2407095Z running 9 tests
2019-10-09T00:25:15.2408061Z iiiiiiiii
2019-10-09T00:25:15.2408471Z 
2019-10-09T00:25:15.2414677Z  finished in 0.163
2019-10-09T00:25:15.2627352Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-09T00:25:15.4340768Z 
---
2019-10-09T00:25:34.6835357Z  finished in 19.420
2019-10-09T00:25:34.7060890Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-09T00:25:34.8684828Z 
2019-10-09T00:25:34.8685621Z running 123 tests
2019-10-09T00:26:01.6469646Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....ii..........iiii..........i...ii...i.......ii. 100/123
2019-10-09T00:26:06.7931908Z i.i.i......iii.i.....ii
2019-10-09T00:26:06.7933997Z 
2019-10-09T00:26:06.7938814Z  finished in 32.088
2019-10-09T00:26:06.7948794Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-09T00:26:06.7952277Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-10-09T00:40:17.7038180Z 
2019-10-09T00:40:17.7039215Z    Doc-tests core
2019-10-09T00:40:23.1798882Z 
2019-10-09T00:40:23.1804273Z running 2405 tests
2019-10-09T00:40:35.5166381Z ......iiiii......................................................................................... 100/2405
2019-10-09T00:40:47.4008865Z ...............................................................................ii................... 200/2405
2019-10-09T00:41:15.6235946Z .i.................................................................................................. 400/2405
2019-10-09T00:41:15.6235946Z .i [...]

2019-10-09 06:16 UTC, hellow554 commented
@clarfon you don't like the suggestion: `let cow: Cow<str> = Cow::Owned("moo".to_string());`? It's okay, just wanted to make sure, that you skipped it ;)

you need to add `#![feature(cow_is_borrowed)]` to https://github.com/rust-lang/rust/blob/b5bd31ec6db6a249311888a93fc176f06dcb6aa6/src/liballoc/lib.rs#L125

2019-10-11 01:36 UTC, clarfon commented
Thank you for the comment about the feature flag. I was just convinced that intra-doc links were broken again ><

2019-10-11 03:30 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=10438&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10438/logs/49), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10438/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-11T01:37:31.8691866Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-11T01:37:31.8781292Z ##[command]git config gc.auto 0
2019-10-11T01:37:31.8866278Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-11T01:37:31.8928903Z ##[command]git config --get-all http.proxy
2019-10-11T01:37:31.9079461Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65144/merge:refs/remotes/pull/65144/merge
---
2019-10-11T02:40:16.7482987Z .................................................................................................... 1600/9146
2019-10-11T02:40:24.6635592Z .................................................................................................... 1700/9146
2019-10-11T02:40:37.0849153Z .................i...............i.................................................................. 1800/9146
2019-10-11T02:40:44.6967352Z .................................................................................................... 1900/9146
2019-10-11T02:41:00.8123242Z ........iiiii....................................................................................... 2000/9146
2019-10-11T02:41:11.4582519Z .................................................................................................... 2200/9146
2019-10-11T02:41:14.2753097Z .................................................................................................... 2300/9146
2019-10-11T02:41:20.4317874Z .................................................................................................... 2400/9146
2019-10-11T02:41:27.1446367Z .................................................................................................... 2500/9146
---
2019-10-11T02:44:34.6634434Z .................................................................................................... 4700/9146
2019-10-11T02:44:42.4898668Z .i...............i.................................................................................. 4800/9146
2019-10-11T02:44:54.2224919Z .................................................................................................... 4900/9146
2019-10-11T02:45:00.1847671Z .................................................................................................... 5000/9146
2019-10-11T02:45:12.1998076Z ...............................................................................................ii.ii 5100/9146
2019-10-11T02:45:23.4733424Z .................................................................................................... 5300/9146
2019-10-11T02:45:33.8953570Z .................................................................................................... 5400/9146
2019-10-11T02:45:41.1430938Z .............................................................i...................................... 5500/9146
2019-10-11T02:45:48.9501391Z .................................................................................................... 5600/9146
2019-10-11T02:45:48.9501391Z .................................................................................................... 5600/9146
2019-10-11T02:45:56.8210191Z .................................................................................................... 5700/9146
2019-10-11T02:46:07.6655421Z ..........................................................ii...i..ii...........i.................... 5800/9146
2019-10-11T02:46:34.7703631Z .................................................................................................... 6000/9146
2019-10-11T02:46:44.5269053Z .................................................................................................... 6100/9146
2019-10-11T02:46:44.5269053Z .................................................................................................... 6100/9146
2019-10-11T02:46:54.3475928Z ................................................................i..ii............................... 6200/9146
2019-10-11T02:47:25.0387682Z .................................................................................................... 6400/9146
2019-10-11T02:47:27.3413783Z ........................i........................................................................... 6500/9146
2019-10-11T02:47:29.7523384Z .................................................................................................i.. 6600/9146
2019-10-11T02:47:32.7039471Z .................................................................................................... 6700/9146
---
2019-10-11T02:52:27.9974044Z  finished in 5.853
2019-10-11T02:52:28.0172053Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-11T02:52:28.1888487Z 
2019-10-11T02:52:28.1888941Z running 153 tests
2019-10-11T02:52:31.7276139Z i....iii......iii..iiii....i.............................i..i..................i....i............ii. 100/153
2019-10-11T02:52:33.8514011Z i.i..iiii..............i.........iii.i.......ii......
2019-10-11T02:52:33.8514500Z 
2019-10-11T02:52:33.8514630Z  finished in 5.834
2019-10-11T02:52:33.8713623Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-11T02:52:34.0344771Z 
---
2019-10-11T02:52:36.3100753Z  finished in 2.438
2019-10-11T02:52:36.3319298Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-11T02:52:36.5134859Z 
2019-10-11T02:52:36.5135097Z running 9 tests
2019-10-11T02:52:36.5136100Z iiiiiiiii
2019-10-11T02:52:36.5136766Z 
2019-10-11T02:52:36.5136808Z  finished in 0.181
2019-10-11T02:52:36.5351477Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-11T02:52:36.7085403Z 
---
2019-10-11T02:52:55.9683412Z  finished in 19.433
2019-10-11T02:52:55.9909757Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-11T02:52:56.1656375Z 
2019-10-11T02:52:56.1657810Z running 123 tests
2019-10-11T02:53:22.1390465Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....ii..........iiii..........i...ii...i.......ii. 100/123
2019-10-11T02:53:27.1587236Z i.i.i......iii.i.....ii
2019-10-11T02:53:27.1590653Z 
2019-10-11T02:53:27.1591906Z  finished in 31.168
2019-10-11T02:53:27.1599335Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-11T02:53:27.1600563Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-10-11T03:07:10.1521003Z 
2019-10-11T03:07:10.1531403Z    Doc-tests core
2019-10-11T03:07:15.5054515Z 
2019-10-11T03:07:15.5055700Z running 2405 tests
2019-10-11T03:07:27.9463475Z ......iiiii......................................................................................... 100/2405
2019-10-11T03:07:40.2634134Z ...............................................................................ii................... 200/2405
2019-10-11T03:08:08.5675902Z .i.................................................................................................. 400/2405
2019-10-11T03:08:08.5675902Z [...]

2019-10-18 21:06 UTC, ProgrammaticNajel commented
Ping from triage. @TimNN can you please review this PR? Thanks.

2019-10-22 23:57 UTC, clarfon commented
Removed the links on `to_mut` because the rest of the module doesn't seem to use them. Will resolve the warnings.

2019-10-23 06:12 UTC, hellow554 commented
@ProgrammaticNajel TimNN seems to be not available. Can you reassign it please?

2019-10-23 06:19 UTC, lzutao commented
r? @sfackler

2019-10-23 11:15 UTC, sfackler commented
@bors r+

2019-10-24 07:16 UTC, merged