Add ?Sized bound to a supertrait listing in E0038 error documentation
rust-lang/rust pull request #65200
Opened 2019-10-08 10:19 UTC by xfix

This example failed to compile because of implicit `Sized` bound for `A` parameter that wasn't required by `Trait`.

2019-10-08 10:19 UTC, rust-highfive commented
Some changes occurred in diagnostic error codes

cc @GuillaumeGomez

2019-10-08 10:19 UTC, rust-highfive commented
r? @davidtwco

(rust_highfive has picked a reviewer for you, use r? to override)

2019-10-08 11:19 UTC, davidtwco requested changes
I'm not sure that this is an improvement, but my understanding of what this example is intended to demonstrate might be incorrect.

I think this example is intended to demonstrate a failing example for this case - this is what the previous cases do, so changing this to a passing example might be not desirable.

As I understand it, this example attempts to demonstrate why a trait is no longer object-safe when it uses `Self` in a supertrait listing: 

When a trait `Foo` has a supertrait `Super<Self>` then that can make `Foo` non-object-safe even if `Super<T>` is object-safe. Suppose `Super<T>` contains a method returning `T` - and `Super<T>` is still object-safe if it does - then when used as a supertrait (`Super<Self>`), the subtrait would be not be object-safe as it would have a method returning a unknown type (this is the "Method references the `Self` type in its parameters or return type" case from above).

I think the error's example is better suited to explaining that if it remains as a failing example than as a passing example, as in this PR.

That said, the next paragraph might be slightly incorrect as it references a "trait Foo" even though the example names the trait "Trait", so if you want to modify this PR to correct that instead, then that would be appreciated.

2019-10-08 14:34 UTC, GuillaumeGomez commented
The first example is supposed to fail and is checked as such.

2019-10-08 22:14 UTC, xfix commented
@davidtwco @GuillaumeGomez 

Is this how the example is supposed to fail?

```rust
trait Super<A> {}

trait Trait: Super<Self> {}
```

Gives the following error:

```
error[E0277]: the size for values of type `Self` cannot be known at compilation time
 --> src/lib.rs:3:1
  |
3 | trait Trait: Super<Self> {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `Self`
  = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
  = help: consider adding a `where Self: std::marker::Sized` bound
note: required by `Super`
 --> src/lib.rs:1:1
  |
1 | trait Super<A> {}
  | ^^^^^^^^^^^^^^
```

Note that the error is **not** E0038, but rather E0277. The issue is that with `trait Trait: Super<Self> {}`, `Self` doesn't have `Sized` bound, which is required by `A` parameter in `Super<A>` (due to implicit `Sized` bound on generic parameters).

There are two ways to fix that, one is to put `Sized` bound on `Trait`, but that would essentially make this `Self: Sized` requirement (nothing special about that one), so I picked the other way of putting a `T: ?Sized` bound so that `Self` would be used as a type parameter in the supertrait listing.

2019-10-08 22:59 UTC, xfix commented
But yeah, now that I'm checking there is something weird with the description. Where did "trait `Foo`" come from?

2019-10-09 08:55 UTC, davidtwco commented
> @davidtwco @GuillaumeGomez Is this how the example is supposed to fail?

I think it would probably be desirable for the example to error with the code that it is describing (that said, I don't maintain the error codes and the intent might just have been to have as simple an example as possible that explains the case).

> 
> Note that the error is **not** E0038, but rather E0277. The issue is that with `trait Trait: Super<Self> {}`, `Self` doesn't have `Sized` bound, which is required by `A` parameter in `Super<A>` (due to implicit `Sized` bound on generic parameters).

I think that [this slightly modified version of the example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fdd17fe1782d44c0f203923391b00756) is probably what we're after. It shows that `Trait` is not object-safe only because of the `Super<Self>` (it's otherwise empty).

2019-10-09 10:31 UTC, xfix commented
Yeah, I can add `main` function, no problem :).

2019-10-10 09:39 UTC, GuillaumeGomez approved these changes

2019-10-12 10:05 UTC, merged