Add long error explanation for E0575
rust-lang/rust pull request #65334
Opened 2019-10-12 12:49 UTC by GuillaumeGomez

Part of #61137.

2019-10-12 12:49 UTC, rust-highfive commented
Some changes occurred in diagnostic error codes

cc @GuillaumeGomez

2019-10-12 12:49 UTC, rust-highfive commented
r? @zackmdavis

(rust_highfive has picked a reviewer for you, use r? to override)

2019-10-16 09:09 UTC, GuillaumeGomez commented
r? @kinnison

2019-10-16 09:17 UTC, kinnison requested changes
Two possible language tweaks, otherwise good IMO.

2019-10-16 09:17 UTC, kinnison commented on src/librustc_resolve/error_codes.rs
> +Something else than a type or an associated type was given.
I think 'other' rather than 'else' would be better:

> Something other than a type or an associated type was given.

2019-10-16 09:17 UTC, kinnison commented on src/librustc_resolve/error_codes.rs
> +In both cases, we're declaring a variable (called `_` in both cases) and we're
I feel the repetition of 'in both cases' is clumsy.  Perhaps:

> In both cases we're declaring a variable (called `_`) and we're
> stating what we believe to be a type.  However, .......

?

2019-10-16 11:55 UTC, GuillaumeGomez commented
Updated.

2019-10-16 12:59 UTC, kinnison approved these changes

2019-10-16 15:09 UTC, GuillaumeGomez commented
@bors: r=kinnison

2019-10-17 09:34 UTC, GuillaumeGomez commented
And here we go again!

@bors: r=kinnison

2019-10-19 04:54 UTC, merged