Create new error E0740 and add long error explanation
rust-lang/rust pull request #65405
Opened 2019-10-14 12:08 UTC by GuillaumeGomez

Part of #61137.

Creates E0740 error code and add its long error explanation.

2019-10-14 12:08 UTC, rust-highfive commented
Some changes occurred in diagnostic error codes

cc @GuillaumeGomez

2019-10-14 12:08 UTC, rust-highfive commented
r? @eddyb

(rust_highfive has picked a reviewer for you, use r? to override)

2019-10-14 14:00 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=10701&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10701/logs/49), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10701/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-14T12:09:13.8439848Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-14T12:09:13.8453664Z ##[command]git config gc.auto 0
2019-10-14T12:09:13.8457386Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-14T12:09:13.8462822Z ##[command]git config --get-all http.proxy
2019-10-14T12:09:13.8469134Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65405/merge:refs/remotes/pull/65405/merge
---
2019-10-14T13:10:39.1912316Z .................................................................................................... 1600/9173
2019-10-14T13:10:45.6176845Z .................................................................................................... 1700/9173
2019-10-14T13:10:57.8408651Z ......................i...............i............................................................. 1800/9173
2019-10-14T13:11:04.9320049Z .................................................................................................... 1900/9173
2019-10-14T13:11:19.6362445Z .............iiiii.................................................................................. 2000/9173
2019-10-14T13:11:29.9645036Z .................................................................................................... 2200/9173
2019-10-14T13:11:32.5224413Z .................................................................................................... 2300/9173
2019-10-14T13:11:37.9879018Z .................................................................................................... 2400/9173
2019-10-14T13:11:59.9811025Z .................................................................................................... 2500/9173
---
2019-10-14T13:14:56.0575101Z ....................i...............i............................................................... 4800/9173
2019-10-14T13:15:07.7308350Z .................................................................................................... 4900/9173
2019-10-14T13:15:14.1853374Z .................................................................................................... 5000/9173
2019-10-14T13:15:24.9542177Z .................................................................................................... 5100/9173
2019-10-14T13:15:31.3021488Z ....................ii.ii........................................................................... 5200/9173
2019-10-14T13:15:41.9446393Z .................................................................................................... 5400/9173
2019-10-14T13:15:52.1198827Z ......................................................................................i............. 5500/9173
2019-10-14T13:16:00.1647563Z .................................................................................................... 5600/9173
2019-10-14T13:16:05.6280681Z .................................................................................................... 5700/9173
2019-10-14T13:16:05.6280681Z .................................................................................................... 5700/9173
2019-10-14T13:16:16.2839100Z ...................................................................................ii...i..ii....... 5800/9173
2019-10-14T13:16:41.8042496Z .................................................................................................... 6000/9173
2019-10-14T13:16:51.5745418Z .................................................................................................... 6100/9173
2019-10-14T13:16:51.5745418Z .................................................................................................... 6100/9173
2019-10-14T13:16:57.1103548Z ..........................................................................................i..ii..... 6200/9173
2019-10-14T13:17:25.8516209Z .................................................................................................... 6400/9173
2019-10-14T13:17:31.0292937Z ...................................................i................................................ 6500/9173
2019-10-14T13:17:33.2097425Z .................................................................................................... 6600/9173
2019-10-14T13:17:35.5932299Z ........................i........................................................................... 6700/9173
---
2019-10-14T13:22:12.5198145Z  finished in 5.448
2019-10-14T13:22:12.5198498Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-14T13:22:12.5198536Z 
2019-10-14T13:22:12.5198579Z running 153 tests
2019-10-14T13:22:16.5144413Z i....iii......iii..iiii...i.............................i..i..................i....i...........ii.i. 100/153
2019-10-14T13:22:17.6307514Z i..iiii..............i.........iii.i.........ii......
2019-10-14T13:22:17.6308110Z 
2019-10-14T13:22:17.6310995Z  finished in 5.369
2019-10-14T13:22:17.6507054Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-14T13:22:17.8101385Z 
---
2019-10-14T13:22:20.0150569Z  finished in 2.186
2019-10-14T13:22:20.0150826Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-14T13:22:20.0150860Z 
2019-10-14T13:22:20.0151090Z running 9 tests
2019-10-14T13:22:20.0151494Z iiiiiiiii
2019-10-14T13:22:20.0151768Z 
2019-10-14T13:22:20.0151803Z  finished in 0.156
2019-10-14T13:22:20.0298580Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-14T13:22:20.1982049Z 
---
2019-10-14T13:22:38.1346642Z  finished in 18.104
2019-10-14T13:22:38.1547849Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-14T13:22:38.3153252Z 
2019-10-14T13:22:38.3154726Z running 123 tests
2019-10-14T13:23:02.5566834Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....ii..........iiii..........i...ii...i.......ii. 100/123
2019-10-14T13:23:07.1952400Z i.i.i......iii.i.....ii
2019-10-14T13:23:07.1953585Z 
2019-10-14T13:23:07.1954948Z  finished in 29.040
2019-10-14T13:23:07.1965398Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-14T13:23:07.1966958Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-10-14T13:36:10.6514862Z 
2019-10-14T13:36:10.6520455Z    Doc-tests core
2019-10-14T13:36:15.7122848Z 
2019-10-14T13:36:15.7142423Z running 2405 tests
2019-10-14T13:36:26.9265253Z ......iiiii......................................................................................... 100/2405
2019-10-14T13:36:37.6466632Z ...............................................................................ii................... 200/2405
2019-10-14T13:37:03.4737339Z .i.................................................................................................. 400/2405
2019-10-14T13:37:03.4737339Z .i.................................................................................................. 400/2405
2019-10-14T13:37:14.0208327Z  [...]

2019-10-18 14:41 UTC, Dylan-DPC commented
r? @Dylan-DPC

2019-10-18 21:50 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=11102&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11102/logs/49), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11102/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-18T20:02:55.9864557Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-18T20:02:56.0097022Z ##[command]git config gc.auto 0
2019-10-18T20:02:56.0150663Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-18T20:02:56.0200398Z ##[command]git config --get-all http.proxy
2019-10-18T20:02:56.0337046Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65405/merge:refs/remotes/pull/65405/merge
---
2019-10-18T20:08:44.0993292Z Successfully built 9c2ed63ed05c
2019-10-18T20:08:44.1784329Z Successfully tagged rust-ci:latest
2019-10-18T20:08:44.2835876Z Built container sha256:9c2ed63ed05c1131a8a3a7f34bc1f654183148bee2d68ccc31dc894644107dc6
2019-10-18T20:08:44.2857779Z Uploading finished image to https://rust-lang-ci-sccache2.s3.amazonaws.com/docker/590c864a5f2335de0a8287407f9a96030510ec86a676b9b48333a6a037ff1c9ca74007b9ad184866d613750a3d2a1a88c9ad4e657c82d0b1a088ee62c541c4ca
2019-10-18T20:09:42.3622390Z upload failed: - to s3://rust-lang-ci-sccache2/docker/590c864a5f2335de0a8287407f9a96030510ec86a676b9b48333a6a037ff1c9ca74007b9ad184866d613750a3d2a1a88c9ad4e657c82d0b1a088ee62c541c4ca An error occurred (InvalidAccessKeyId) when calling the CreateMultipartUpload operation: The AWS Access Key Id you provided does not exist in our records.
2019-10-18T20:09:43.4343513Z [CI_JOB_NAME=x86_64-gnu-llvm-6.0]
2019-10-18T20:09:43.4379095Z == clock drift check ==
2019-10-18T20:09:43.4388344Z   local time: Fri Oct 18 20:09:43 UTC 2019
2019-10-18T20:09:43.5874894Z   network time: Fri, 18 Oct 2019 20:09:43 GMT
---
2019-10-18T21:04:16.8343136Z .................................................................................................... 1600/9196
2019-10-18T21:04:21.6514823Z .................................................................................................... 1700/9196
2019-10-18T21:04:34.2448537Z .............................i...............i...................................................... 1800/9196
2019-10-18T21:04:41.2981196Z .................................................................................................... 1900/9196
2019-10-18T21:04:54.6364223Z ...................iiiii............................................................................ 2000/9196
2019-10-18T21:05:04.7362918Z .................................................................................................... 2200/9196
2019-10-18T21:05:07.2680129Z .................................................................................................... 2300/9196
2019-10-18T21:05:12.5940862Z .................................................................................................... 2400/9196
2019-10-18T21:05:33.1552530Z .................................................................................................... 2500/9196
---
2019-10-18T21:08:16.3964650Z ......................i...............i............................................................. 4800/9196
2019-10-18T21:08:27.4515695Z .................................................................................................... 4900/9196
2019-10-18T21:08:33.3139864Z .................................................................................................... 5000/9196
2019-10-18T21:08:42.9434627Z .................................................................................................... 5100/9196
2019-10-18T21:08:48.7935016Z ......................ii.ii......................................................................... 5200/9196
2019-10-18T21:08:58.3469112Z .................................................................................................... 5400/9196
2019-10-18T21:09:08.1647556Z ........................................................................................i........... 5500/9196
2019-10-18T21:09:15.7222491Z .................................................................................................... 5600/9196
2019-10-18T21:09:20.3440179Z .................................................................................................... 5700/9196
2019-10-18T21:09:20.3440179Z .................................................................................................... 5700/9196
2019-10-18T21:09:30.3903593Z .....................................................................................ii...i..ii..... 5800/9196
2019-10-18T21:09:54.7131332Z .................................................................................................... 6000/9196
2019-10-18T21:10:04.1297774Z .................................................................................................... 6100/9196
2019-10-18T21:10:10.7763711Z .................................................................................................... 6200/9196
2019-10-18T21:10:10.7763711Z .................................................................................................... 6200/9196
2019-10-18T21:10:25.0370457Z .......i..ii........................................................................................ 6300/9196
2019-10-18T21:10:44.9269620Z ...................................................................i................................ 6500/9196
2019-10-18T21:10:47.1198771Z .................................................................................................... 6600/9196
2019-10-18T21:10:49.6193137Z .........................................i.......................................................... 6700/9196
2019-10-18T21:10:53.5806427Z .................................................................................................... 6800/9196
---
2019-10-18T21:15:13.0329107Z  finished in 5.789
2019-10-18T21:15:13.0533280Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-18T21:15:13.2354833Z 
2019-10-18T21:15:13.2355126Z running 153 tests
2019-10-18T21:15:16.2977879Z i....iii......iii..iiii...i.............................i..i..................i....i...........ii.i. 100/153
2019-10-18T21:15:18.7125570Z i..iiii..............i.........iii.i.........ii......
2019-10-18T21:15:18.7127330Z 
2019-10-18T21:15:18.7185756Z  finished in 5.110
2019-10-18T21:15:18.7186660Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-18T21:15:18.7186913Z 
---
2019-10-18T21:15:20.2676523Z  finished in 2.087
2019-10-18T21:15:20.2842140Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-18T21:15:20.4328379Z 
2019-10-18T21:15:20.4328604Z running 9 tests
2019-10-18T21:15:20.4330697Z iiiiiiiii
2019-10-18T21:15:20.4330994Z 
2019-10-18T21:15:20.4331491Z  finished in 0.148
2019-10-18T21:15:20.4497913Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-18T21:15:21.2170696Z 
---
2019-10-18T21:15:37.7959655Z  finished in 17.346
2019-10-18T21:15:37.8149113Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-18T21:15:37.9850548Z 
2019-10-18T21:15:37.9850869Z running 123 tests
2019-10-1 [...]

2019-10-21 18:51 UTC, GuillaumeGomez commented
cc @Dylan-DPC :)

2019-10-22 16:26 UTC, Dylan-DPC-zz requested changes

2019-10-22 16:26 UTC, Dylan-DPC commented on src/librustc_resolve/error_codes.rs
> +A visibility has been restricted to a module which isn't an ancestor of the
```suggestion
Visibility is restricted to a module which isn't an ancestor of the
```

2019-10-23 09:07 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=11538&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11538/logs/45), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11538/logs/45)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-23T08:48:26.2997671Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-23T08:48:26.3242118Z ##[command]git config gc.auto 0
2019-10-23T08:48:26.3325912Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-23T08:48:26.3382004Z ##[command]git config --get-all http.proxy
2019-10-23T08:48:26.3541441Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65405/merge:refs/remotes/pull/65405/merge
---
2019-10-23T08:54:50.0276431Z    Compiling serde_json v1.0.40
2019-10-23T08:54:51.9274902Z    Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
2019-10-23T08:55:04.2346186Z     Finished release [optimized] target(s) in 1m 34s
2019-10-23T08:55:04.2435676Z tidy check
2019-10-23T08:55:05.4915209Z tidy error: duplicate error code: 740
2019-10-23T08:55:05.4916183Z tidy error: /checkout/src/librustc_resolve/error_codes.rs:1909: E0740: r##"
2019-10-23T08:55:05.4916476Z tidy error: /checkout/src/librustc_typeck/error_codes.rs:4866: E0740: r##"
2019-10-23T08:55:06.8853889Z Found 483 error codes
2019-10-23T08:55:06.8854021Z Found 0 error codes with no tests
2019-10-23T08:55:06.8854199Z Done!
2019-10-23T08:55:06.8859619Z some tidy checks failed
2019-10-23T08:55:06.8859619Z some tidy checks failed
2019-10-23T08:55:06.8860394Z 
2019-10-23T08:55:06.8866021Z 
2019-10-23T08:55:06.8867236Z command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor"
2019-10-23T08:55:06.8867910Z 
2019-10-23T08:55:06.8868100Z 
2019-10-23T08:55:06.8868366Z failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
2019-10-23T08:55:06.8868534Z Build completed unsuccessfully in 0:01:38
2019-10-23T08:55:06.8868534Z Build completed unsuccessfully in 0:01:38
2019-10-23T08:55:06.8925742Z == clock drift check ==
2019-10-23T08:55:06.8958716Z   local time: Wed Oct 23 08:55:06 UTC 2019
2019-10-23T08:55:07.1740317Z   network time: Wed, 23 Oct 2019 08:55:07 GMT
2019-10-23T08:55:07.1743489Z == end clock drift check ==
2019-10-23T08:55:09.1765666Z 
2019-10-23T08:55:09.1880875Z ##[error]Bash exited with code '1'.
2019-10-23T08:55:09.1914069Z ##[section]Starting: Checkout
2019-10-23T08:55:09.1916150Z ==============================================================================
2019-10-23T08:55:09.1916222Z Task         : Get sources
2019-10-23T08:55:09.1916285Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-10-23 10:53 UTC, GuillaumeGomez commented
I changed the error code to fix tests.

2019-10-24 13:00 UTC, Dylan-DPC commented
@bors: r+ rollup

2019-10-24 18:15 UTC, Centril commented
Failed in https://github.com/rust-lang/rust/pull/65769, @bors r-

2019-10-24 20:55 UTC, GuillaumeGomez commented
Erf, someone already created E0741... :'(

2019-10-25 14:16 UTC, Dylan-DPC commented
We need Mutex<Error Codes> ;)

2019-10-29 12:56 UTC, GuillaumeGomez commented
Indeed haha!

2019-10-29 13:01 UTC, GuillaumeGomez commented
@bors: r=Dylan-DPC

2019-10-29 13:01 UTC, GuillaumeGomez commented
And to avoid having to update the error code once again:

@bors: p=1

2019-10-29 22:27 UTC, merged