Add long error explanation for E0578
rust-lang/rust pull request #65471
Opened 2019-10-16 11:31 UTC by GuillaumeGomez

Part of #64903 

r? @kinnison

2019-10-16 12:57 UTC, kinnison requested changes
A comma comment, otherwise :+1:

2019-10-16 12:57 UTC, kinnison commented on src/librustc_resolve/error_codes.rs
> +A module cannot be found and therefore, the visibility cannot be determined.
The comma here is odd.  Either 'therefore' is an optional part of the sentence in which case it needs a comma before as well as after, or it's not optional and the comma is unnecessary.

e.g.

> A module cannot be found and, therefore, the visibility cannot be determined.

vs.

> A module cannot be found and therefore the visibility cannot be determined.

2019-10-16 13:26 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=10911&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10911/logs/49), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/10911/logs/49)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-16T11:31:50.0468546Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-16T11:31:50.0643794Z ##[command]git config gc.auto 0
2019-10-16T11:31:50.0727084Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-16T11:31:50.0776362Z ##[command]git config --get-all http.proxy
2019-10-16T11:31:50.0941759Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65471/merge:refs/remotes/pull/65471/merge
---
2019-10-16T12:34:52.6003637Z .................................................................................................... 1600/9196
2019-10-16T12:34:58.0176154Z .................................................................................................... 1700/9196
2019-10-16T12:35:11.4378370Z .............................i...............i...................................................... 1800/9196
2019-10-16T12:35:19.1766083Z .................................................................................................... 1900/9196
2019-10-16T12:35:34.0767542Z ...................iiiii............................................................................ 2000/9196
2019-10-16T12:35:44.8408025Z .................................................................................................... 2200/9196
2019-10-16T12:35:48.0253452Z .................................................................................................... 2300/9196
2019-10-16T12:35:53.1921692Z .................................................................................................... 2400/9196
2019-10-16T12:36:15.7501126Z .................................................................................................... 2500/9196
---
2019-10-16T12:39:18.7482928Z ......................i...............i............................................................. 4800/9196
2019-10-16T12:39:30.8303684Z .................................................................................................... 4900/9196
2019-10-16T12:39:37.4843771Z .................................................................................................... 5000/9196
2019-10-16T12:39:48.4820555Z .................................................................................................... 5100/9196
2019-10-16T12:39:54.9940720Z ......................ii.ii......................................................................... 5200/9196
2019-10-16T12:40:05.9293698Z .................................................................................................... 5400/9196
2019-10-16T12:40:16.2918018Z ........................................................................................i........... 5500/9196
2019-10-16T12:40:24.8252012Z .................................................................................................... 5600/9196
2019-10-16T12:40:30.0528507Z .................................................................................................... 5700/9196
2019-10-16T12:40:30.0528507Z .................................................................................................... 5700/9196
2019-10-16T12:40:41.2796290Z .....................................................................................ii...i..ii..... 5800/9196
2019-10-16T12:41:08.7465416Z .................................................................................................... 6000/9196
2019-10-16T12:41:16.7227741Z .................................................................................................... 6100/9196
2019-10-16T12:41:21.6534149Z .................................................................................................... 6200/9196
2019-10-16T12:41:21.6534149Z .................................................................................................... 6200/9196
2019-10-16T12:41:36.1916697Z .......i..ii........................................................................................ 6300/9196
2019-10-16T12:41:56.4927766Z ...................................................................i................................ 6500/9196
2019-10-16T12:41:58.7779730Z .................................................................................................... 6600/9196
2019-10-16T12:42:01.4443017Z .........................................i.......................................................... 6700/9196
2019-10-16T12:42:05.5472452Z .................................................................................................... 6800/9196
---
2019-10-16T12:46:46.0027268Z  finished in 5.484
2019-10-16T12:46:46.0236616Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-16T12:46:46.1986089Z 
2019-10-16T12:46:46.2015099Z running 153 tests
2019-10-16T12:46:49.5627119Z i....iii......iii..iiii...i.............................i..i..................i....i...........ii.i. 100/153
2019-10-16T12:46:51.6218968Z i..iiii..............i.........iii.i.........ii......
2019-10-16T12:46:51.6219627Z 
2019-10-16T12:46:51.6219685Z  finished in 5.598
2019-10-16T12:46:51.6400252Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-16T12:46:51.8033246Z 
---
2019-10-16T12:46:53.9390552Z  finished in 2.299
2019-10-16T12:46:53.9603073Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-16T12:46:54.1190284Z 
2019-10-16T12:46:54.1193027Z running 9 tests
2019-10-16T12:46:54.1193800Z iiiiiiiii
2019-10-16T12:46:54.1194156Z 
2019-10-16T12:46:54.1196956Z  finished in 0.159
2019-10-16T12:46:54.1398978Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-16T12:46:54.3040825Z 
---
2019-10-16T12:47:12.7743410Z  finished in 18.634
2019-10-16T12:47:12.7953922Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-16T12:47:12.9606385Z 
2019-10-16T12:47:12.9606906Z running 123 tests
2019-10-16T12:47:39.0355280Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....ii..........iiii..........i...ii...i.......ii. 100/123
2019-10-16T12:47:44.0599651Z i.i.i......iii.i.....ii
2019-10-16T12:47:44.0602800Z 
2019-10-16T12:47:44.0603173Z  finished in 31.264
2019-10-16T12:47:44.0615011Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-16T12:47:44.0615549Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-10-16T13:01:12.6464817Z 
2019-10-16T13:01:12.6466299Z    Doc-tests core
2019-10-16T13:01:17.8152367Z 
2019-10-16T13:01:17.8153576Z running 2405 tests
2019-10-16T13:01:29.4843158Z ......iiiii......................................................................................... 100/2405
2019-10-16T13:01:40.6630061Z ...............................................................................ii................... 200/2405
2019-10-16T13:02:07.4670909Z .i.................................................................................................. 400/2405
2019-10-16T13:02:07.4670909Z [...]

2019-10-17 14:58 UTC, Dylan-DPC-zz approved these changes

2019-10-17 15:13 UTC, kinnison approved these changes
:+1:

2019-10-17 15:26 UTC, GuillaumeGomez commented
@bors: r=kinnison,Dylan-DPC

2019-10-21 11:36 UTC, Dylan-DPC commented
r? @Dylan-DPC

2019-10-23 11:03 UTC, GuillaumeGomez commented
Rebased.

2019-10-27 12:15 UTC, jonas-schievink commented
> Part of #64903

That looks like the wrong issue

2019-10-29 12:48 UTC, GuillaumeGomez commented
@jonas-schievink Indeed, and that's not the first time even though it seemed like I entered the link correctly. This is rather strange... Anyway, updated the link.

2019-10-29 12:50 UTC, GuillaumeGomez commented
Rebased.

2019-10-31 13:27 UTC, GuillaumeGomez commented
Rebased (and let's hope it's the last time ><).

2019-10-31 15:44 UTC, Dylan-DPC commented
@bors: r+ rollup

2019-11-01 21:43 UTC, merged