Fix test style in unused parentheses lint test
rust-lang/rust pull request #65507
Opened 2019-10-17 18:05 UTC by polyedre

I think this fixes #63237 
I'm not sure if I had to add text after the `//~ ERROR` comments.
This is my first pull request, so I'm open to feedback.
This issues already received one pull request [here](https://github.com/rust-lang/rust/pull/63257) but it was marked as closed for inactivity.

r?  @nikomatsakis

2019-10-17 18:05 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @nikomatsakis (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2019-10-17 22:19 UTC, nikomatsakis requested changes
This looks great! I left one nit.

2019-10-18 11:23 UTC, polyedre commented on src/test/ui/lint/unused_parens_json_suggestion.rs
> +    let _a = (1 / (2 + 3)); //~ERROR
It should be fixed by https://github.com/rust-lang/rust/pull/65507/commits/95d98af806f78d9cbe3975b633d5341394a155ad

2019-10-19 13:49 UTC, polyedre commented
r? @nikomatsakis

2019-10-22 18:45 UTC, nikomatsakis commented
@bors r+ rollup

Thanks @polyedre

2019-10-22 18:46 UTC, nikomatsakis approved these changes

2019-10-23 13:34 UTC, merged