workaround msys2 bug
rust-lang/rust pull request #65762
Opened 2019-10-24 14:49 UTC by mati865

Not sure if it's gonna work

2019-10-24 14:49 UTC, rust-highfive commented
r? @Mark-Simulacrum

(rust_highfive has picked a reviewer for you, use r? to override)

2019-10-24 14:50 UTC, mati865 commented
The worst thing that can happen is different error, so...

2019-10-24 14:51 UTC, Mark-Simulacrum commented
@bors r+ p=2000

2019-10-24 14:58 UTC, rust-highfive commented
Your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=11656&view=logs&jobId=5ac1211a-cbe7-52be-dcc2-57e3991fd20c) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11656/logs/746), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11656/logs/746)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-24T14:52:53.0377665Z do so (now or later) by using -b with the checkout command again. Example:
2019-10-24T14:52:53.0378310Z 
2019-10-24T14:52:53.0379018Z   git checkout -b <new-branch-name>
2019-10-24T14:52:53.0380723Z 
2019-10-24T14:52:53.0381312Z HEAD is now at 7d35376b6 Auto merge of #65762 - mati865:msys2-bug, r=Mark-Simulacrum
2019-10-24T14:52:53.0746730Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-10-24T14:52:53.0856093Z ==============================================================================
2019-10-24T14:52:53.0856387Z Task         : Bash
2019-10-24T14:52:53.0856502Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-10-24T14:57:21.8110282Z 
2019-10-24T14:57:21.8110660Z ========================== Starting Command Output ===========================
2019-10-24T14:57:21.8130233Z [command]D:\a\msys2\usr\bin\bash.exe --noprofile --norc /d/a/_temp/81eeeedb-7d35-49b5-ae61-1ad255f9269e.sh
2019-10-24T14:57:21.8130443Z 
2019-10-24T14:57:21.8192198Z ##[error]Bash exited with code '1'.
2019-10-24T14:57:21.8323717Z ##[section]Starting: Upload CPU usage statistics
2019-10-24T14:57:21.8428634Z ==============================================================================
2019-10-24T14:57:21.8428761Z Task         : Bash
2019-10-24T14:57:21.8428854Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-10-24T14:57:22.1830121Z ========================== Starting Command Output ===========================
2019-10-24T14:57:22.1831259Z [command]D:\a\msys2\usr\bin\bash.exe --noprofile --norc /d/a/_temp/db3099aa-0cc0-4228-9afe-1c3001d41380.sh
2019-10-24T14:57:22.1831480Z /d/a/_temp/db3099aa-0cc0-4228-9afe-1c3001d41380.sh: line 1: aws: command not found
2019-10-24T14:57:22.1831614Z 
2019-10-24T14:57:22.1832621Z ##[error]Bash exited with code '127'.
2019-10-24T14:57:22.1854152Z ##[section]Starting: Checkout
2019-10-24T14:57:22.1958057Z ==============================================================================
2019-10-24T14:57:22.1958167Z Task         : Get sources
2019-10-24T14:57:22.1958283Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-10-24 15:09 UTC, pietroalbini commented
@bors delegate+

2019-10-24 15:26 UTC, emilyalbini requested changes

2019-10-24 15:26 UTC, pietroalbini commented on src/ci/azure-pipelines/steps/run.yml
> +repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-ca-certificates-20180409-1-any.pkg.tar.xz
What are those two links?

2019-10-24 15:26 UTC, pietroalbini commented on src/ci/azure-pipelines/steps/install-windows-build-deps.yml
> +    curl repo.msys2.org/mingw/i686/mingw-w64-i686-ca-certificates-20180409-1-any.pkg.tar.xz -O
```suggestion
    curl https://repo.msys2.org/mingw/i686/mingw-w64-i686-ca-certificates-20180409-1-any.pkg.tar.xz -O
```

2019-10-24 15:26 UTC, pietroalbini commented on src/ci/azure-pipelines/steps/install-windows-build-deps.yml
> +    curl repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-ca-certificates-20180409-1-any.pkg.tar.xz -O
```suggestion
    curl https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-ca-certificates-20180409-1-any.pkg.tar.xz -O
```

2019-10-24 15:28 UTC, mati865 commented on src/ci/azure-pipelines/steps/run.yml
> +repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-ca-certificates-20180409-1-any.pkg.tar.xz
Oh I hate notepad

2019-10-24 15:32 UTC, mati865 commented
@bors r-

2019-10-24 15:32 UTC, rust-highfive commented
Your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=11669&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11669/logs/25), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11669/logs/25)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-24T15:31:33.4566466Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-24T15:31:34.2238605Z ##[command]git config gc.auto 0
2019-10-24T15:31:34.2247984Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-24T15:31:34.2250682Z ##[command]git config --get-all http.proxy
2019-10-24T15:31:34.2253936Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65762/merge:refs/remotes/pull/65762/merge
---
2019-10-24T15:32:10.6418730Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2019-10-24T15:32:10.6419517Z                                  Dload  Upload   Total   Spent    Left  Speed
2019-10-24T15:32:10.6419895Z 
2019-10-24T15:32:10.7641599Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2019-10-24T15:32:10.7882288Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to repo.msys2.org port 443: Connection refused
2019-10-24T15:32:10.7959051Z                                  Dload  Upload   Total   Spent    Left  Speed
2019-10-24T15:32:10.7959798Z 
2019-10-24T15:32:10.7959798Z 
2019-10-24T15:32:10.8237584Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to repo.msys2.org port 443: Connection refused
2019-10-24T15:32:10.8281312Z 
2019-10-24T15:32:10.8399663Z ##[error]Bash exited with code '7'.
2019-10-24T15:32:10.8579303Z ##[section]Starting: Checkout
2019-10-24T15:32:10.8581845Z ==============================================================================
2019-10-24T15:32:10.8581914Z Task         : Get sources
2019-10-24T15:32:10.8581969Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-10-24 15:34 UTC, rust-highfive commented
Your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=11670&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11670/logs/446), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11670/logs/446)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-24T15:33:05.0356120Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/fd953504-a5d7-4952-875b-b18088978e48.sh
2019-10-24T15:33:05.0701660Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2019-10-24T15:33:05.0702783Z                                  Dload  Upload   Total   Spent    Left  Speed
2019-10-24T15:33:05.0702969Z 
2019-10-24T15:33:05.2166968Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to repo.msys2.org port 443: Connection refused
2019-10-24T15:33:05.2233487Z                                  Dload  Upload   Total   Spent    Left  Speed
2019-10-24T15:33:05.2233576Z 
2019-10-24T15:33:05.2233576Z 
2019-10-24T15:33:05.2480866Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to repo.msys2.org port 443: Connection refused
2019-10-24T15:33:05.2514174Z 
2019-10-24T15:33:05.2610724Z ##[error]Bash exited with code '7'.
2019-10-24T15:33:05.2784360Z ##[section]Starting: Upload CPU usage statistics
2019-10-24T15:33:05.2787769Z ==============================================================================
2019-10-24T15:33:05.2788074Z Task         : Bash
2019-10-24T15:33:05.2788153Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-10-24T15:33:05.4258496Z Script contents:
2019-10-24T15:33:05.4259035Z aws s3 cp --acl public-read cpu-usage.csv s3://$DEPLOY_BUCKET/rustc-builds/$BUILD_SOURCEVERSION/cpu-$CI_JOB_NAME.csv
2019-10-24T15:33:05.4277954Z ========================== Starting Command Output ===========================
2019-10-24T15:33:05.4297401Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/4eb54fa2-d6bb-4679-bd54-8fd5453b7451.sh
2019-10-24T15:33:09.5772058Z Completed 164 Bytes/164 Bytes (210 Bytes/s) with 1 file(s) remaining
2019-10-24T15:33:09.5773556Z upload: ./cpu-usage.csv to s3://rust-lang-ci2/rustc-builds/40b4897916b2493165b41781219a8904ebbfe40e/cpu-.csv
2019-10-24T15:33:09.6391122Z ##[section]Finishing: Upload CPU usage statistics
2019-10-24T15:33:09.6408671Z ##[section]Starting: Checkout
2019-10-24T15:33:09.6410821Z ==============================================================================
2019-10-24T15:33:09.6410937Z Task         : Get sources
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-10-24 15:36 UTC, rust-highfive commented
Your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=11671&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11671/logs/37), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11671/logs/37)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-24T15:35:21.7153602Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-24T15:35:21.7401966Z ##[command]git config gc.auto 0
2019-10-24T15:35:21.7478661Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-24T15:35:21.7536464Z ##[command]git config --get-all http.proxy
2019-10-24T15:35:21.7684512Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65762/merge:refs/remotes/pull/65762/merge
---
2019-10-24T15:36:00.1089065Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/daef462e-aaae-4d8a-9de5-bb5ec652fc66.sh
2019-10-24T15:36:00.1435249Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2019-10-24T15:36:00.1436928Z                                  Dload  Upload   Total   Spent    Left  Speed
2019-10-24T15:36:00.1437447Z 
2019-10-24T15:36:00.2898357Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to repo.msys2.org port 443: Connection refused
2019-10-24T15:36:00.2966398Z                                  Dload  Upload   Total   Spent    Left  Speed
2019-10-24T15:36:00.2966482Z 
2019-10-24T15:36:00.2966482Z 
2019-10-24T15:36:00.3202483Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to repo.msys2.org port 443: Connection refused
2019-10-24T15:36:00.3239784Z 
2019-10-24T15:36:00.3361870Z ##[error]Bash exited with code '7'.
2019-10-24T15:36:00.3503258Z ##[section]Starting: Checkout
2019-10-24T15:36:00.3505062Z ==============================================================================
2019-10-24T15:36:00.3505163Z Task         : Get sources
2019-10-24T15:36:00.3505204Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-10-24 15:40 UTC, pietroalbini commented
You also forgot the `condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))` on both task.

2019-10-24 15:42 UTC, rust-highfive commented
Your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=11672&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11672/logs/30), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11672/logs/30)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-24T15:41:15.5283966Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-24T15:41:15.5497097Z ##[command]git config gc.auto 0
2019-10-24T15:41:15.5588937Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-24T15:41:15.5643144Z ##[command]git config --get-all http.proxy
2019-10-24T15:41:15.5788082Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65762/merge:refs/remotes/pull/65762/merge
---
2019-10-24T15:41:55.7293404Z Generating script.
2019-10-24T15:41:55.7321781Z ========================== Starting Command Output ===========================
2019-10-24T15:41:55.7344281Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/42a1072a-e118-43b6-bea2-55354ed5d484.sh
2019-10-24T15:41:55.7452527Z 
2019-10-24T15:41:55.7454116Z /home/vsts/work/_temp/42a1072a-e118-43b6-bea2-55354ed5d484.sh: line 1: pacman: command not found
2019-10-24T15:41:55.7454460Z /home/vsts/work/_temp/42a1072a-e118-43b6-bea2-55354ed5d484.sh: line 3: pacman: command not found
2019-10-24T15:41:55.7454840Z rm: cannot remove 'mingw-w64-x86_64-ca-certificates-20180409-1-any.pkg.tar.xz': No such file or directory
2019-10-24T15:41:55.7554186Z ##[error]Bash exited with code '1'.
2019-10-24T15:41:55.7660620Z ##[section]Starting: Checkout
2019-10-24T15:41:55.7663242Z ==============================================================================
2019-10-24T15:41:55.7663304Z Task         : Get sources
2019-10-24T15:41:55.7663390Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-10-24 15:43 UTC, mati865 commented
@bors r=pietroalbini

2019-10-24 15:47 UTC, mati865 commented
I'm bad at it...

@bors r=pietroalbini

2019-10-24 15:54 UTC, rust-highfive commented
Your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=11677&view=logs&jobId=b1e7928f-7d26-57cb-a49e-81353e6c69ce) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11677/logs/741), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11677/logs/741)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-24T15:49:19.7952981Z do so (now or later) by using -b with the checkout command again. Example:
2019-10-24T15:49:19.7953039Z 
2019-10-24T15:49:19.7953131Z   git checkout -b <new-branch-name>
2019-10-24T15:49:19.7953182Z 
2019-10-24T15:49:19.7953285Z HEAD is now at bc8d760ee Auto merge of #65762 - mati865:msys2-bug, r=pietroalbini
2019-10-24T15:49:19.8356088Z ##[section]Starting: Collect CPU-usage statistics in the background
2019-10-24T15:49:19.8463820Z ==============================================================================
2019-10-24T15:49:19.8463945Z Task         : Bash
2019-10-24T15:49:19.8464031Z Description  : Run a Bash script on macOS, Linux, or Windows
---
2019-10-24T15:53:45.8332470Z installing mingw-w64-i686-libiconv...
2019-10-24T15:53:45.9142091Z installing mingw-w64-i686-gettext...
2019-10-24T15:53:48.6938642Z installing mingw-w64-i686-p11-kit...
2019-10-24T15:53:48.7482442Z installing mingw-w64-i686-ca-certificates...
2019-10-24T15:53:50.2015481Z error: 'mingw-w64-x86_64-ca-certificates-20180409-1-any.pkg.tar.xz': could not find or read package
2019-10-24T15:53:50.2160799Z loading packages...
2019-10-24T15:53:50.2301382Z rm: cannot remove 'mingw-w64-x86_64-ca-certificates-20180409-1-any.pkg.tar.xz': No such file or directory
2019-10-24T15:53:50.2311968Z 
2019-10-24T15:53:50.2421010Z ##[error]Bash exited with code '1'.
2019-10-24T15:53:50.2463057Z ##[section]Finishing: Download working ca-certificates for msys
2019-10-24T15:53:50.2693832Z ==============================================================================
2019-10-24T15:53:50.2693941Z Task         : Bash
2019-10-24T15:53:50.2694032Z Description  : Run a Bash script on macOS, Linux, or Windows
2019-10-24T15:53:50.2694110Z Version      : 3.159.3
---
2019-10-24T15:53:50.5466014Z ========================== Starting Command Output ===========================
2019-10-24T15:53:50.5470175Z [command]D:\a\msys2\usr\bin\bash.exe --noprofile --norc /d/a/_temp/3a2dacf4-f7a1-4a82-827e-ebcb2fbf2b6b.sh
2019-10-24T15:53:50.5819076Z /d/a/_temp/3a2dacf4-f7a1-4a82-827e-ebcb2fbf2b6b.sh: line 1: aws: command not found
2019-10-24T15:53:50.5826473Z 
2019-10-24T15:53:50.5854968Z ##[error]Bash exited with code '127'.
2019-10-24T15:53:50.5926258Z ##[section]Starting: Checkout
2019-10-24T15:53:50.6019253Z ==============================================================================
2019-10-24T15:53:50.6019330Z Task         : Get sources
2019-10-24T15:53:50.6019413Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-10-24 15:59 UTC, pietroalbini commented
@bors r+ p=2000

2019-10-24 19:41 UTC, merged

2019-10-24 19:46 UTC, mati865 commented
Probably won't work for me

@bors treeclosed-

2019-10-24 20:00 UTC, alexcrichton commented
@bors: treeclosed-

2019-10-25 16:51 UTC, Mark-Simulacrum commented
I've included this into beta in https://github.com/rust-lang/rust/pull/65708 but nominated for infra just to check in that that's fine (the beta rollup will hopefully have landed by then). It's a pure CI change that shouldn't affect distributed code so I'm not too concerned.