syntax: move stuff around
rust-lang/rust pull request #65916
Opened 2019-10-29 01:15 UTC by Centril

Part of https://github.com/rust-lang/rust/pull/65324.

r? @davidtwco
cc @estebank @petrochenkov

2019-10-29 02:59 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=12201&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/12201/logs/66), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/12201/logs/66)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-10-29T01:50:40.0843795Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-10-29T01:50:40.1070986Z ##[command]git config gc.auto 0
2019-10-29T01:50:40.1140590Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-10-29T01:50:40.1188193Z ##[command]git config --get-all http.proxy
2019-10-29T01:50:40.1319621Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/65916/merge:refs/remotes/pull/65916/merge
---
2019-10-29T02:47:25.8407437Z .................................................................................................... 1600/9259
2019-10-29T02:47:31.1532227Z .................................................................................................... 1700/9259
2019-10-29T02:47:42.2039156Z ..........................................................i...............i......................... 1800/9259
2019-10-29T02:47:49.1238661Z .................................................................................................... 1900/9259
2019-10-29T02:48:02.2325605Z ................................................iiiii............................................... 2000/9259
2019-10-29T02:48:11.9654192Z .................................................................................................... 2200/9259
2019-10-29T02:48:14.3859806Z .................................................................................................... 2300/9259
2019-10-29T02:48:17.8998184Z .................................................................................................... 2400/9259
2019-10-29T02:48:39.0838280Z .................................................................................................... 2500/9259
---
2019-10-29T02:51:20.6803191Z .................................................i...............i.................................. 4800/9259
2019-10-29T02:51:29.0831709Z .................................................................................................... 4900/9259
2019-10-29T02:51:36.7173137Z .................................................................................................... 5000/9259
2019-10-29T02:51:42.4639399Z .................................................................................................... 5100/9259
2019-10-29T02:51:51.8015120Z ..................................................ii.ii...........i................................. 5200/9259
2019-10-29T02:52:00.8163006Z .................................................................................................... 5400/9259
2019-10-29T02:52:09.2405475Z .................................................................................................... 5500/9259
2019-10-29T02:52:16.4960186Z ....................i............................................................................... 5600/9259
2019-10-29T02:52:21.9851259Z .................................................................................................... 5700/9259
2019-10-29T02:52:21.9851259Z .................................................................................................... 5700/9259
2019-10-29T02:52:32.8007097Z .................................................................................................... 5800/9259
2019-10-29T02:52:44.1199036Z .....ii...i..ii...........i......................................................................... 5900/9259
2019-10-29T02:53:04.0677061Z .................................................................................................... 6100/9259
2019-10-29T02:53:10.1798587Z .................................................................................................... 6200/9259
2019-10-29T02:53:10.1798587Z .................................................................................................... 6200/9259
2019-10-29T02:53:22.9406777Z ........................i..ii....................................................................... 6300/9259
2019-10-29T02:53:41.1109579Z ..........................................................................................i......... 6500/9259
2019-10-29T02:53:43.2680349Z .................................................................................................... 6600/9259
2019-10-29T02:53:45.4668483Z .................................................................i.................................. 6700/9259
2019-10-29T02:53:48.1894047Z .................................................................................................... 6800/9259
---
2019-10-29T02:57:57.7289868Z  finished in 5.166
2019-10-29T02:57:57.7454197Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-29T02:57:57.8967630Z 
2019-10-29T02:57:57.8968224Z running 153 tests
2019-10-29T02:58:00.8367785Z i....iii......iii..iiii...i.............................i..i..................i....i...........ii.i. 100/153
2019-10-29T02:58:02.5991320Z i..iiii..............i.........iii.i.........ii......
2019-10-29T02:58:02.5992388Z 
2019-10-29T02:58:02.6001488Z  finished in 4.854
2019-10-29T02:58:02.6159362Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-29T02:58:02.7554617Z 
---
2019-10-29T02:58:04.5262496Z  finished in 1.910
2019-10-29T02:58:04.5407352Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-29T02:58:04.6685763Z 
2019-10-29T02:58:04.6686568Z running 9 tests
2019-10-29T02:58:04.6687535Z iiiiiiiii
2019-10-29T02:58:04.6687920Z 
2019-10-29T02:58:04.6689411Z  finished in 0.127
2019-10-29T02:58:04.6838177Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-29T02:58:04.8256955Z 
---
2019-10-29T02:58:21.6783286Z  finished in 16.994
2019-10-29T02:58:21.6996835Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-29T02:58:21.8492279Z 
2019-10-29T02:58:21.8493379Z running 123 tests
2019-10-29T02:58:44.2388430Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....ii..........iiii..........i...ii...i.......ii. 100/123
2019-10-29T02:58:47.5210184Z i.i.i......iii.i.....ii
2019-10-29T02:58:47.5211296Z 
2019-10-29T02:58:47.5217588Z  finished in 25.822
2019-10-29T02:58:47.5228517Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-10-29T02:58:47.5252986Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-10-29T02:59:41.2716860Z thread 'main' panicked at 'Some tests failed', src/tools/compiletest/src/main.rs:537:22
2019-10-29T02:59:41.2717266Z note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
2019-10-29T02:59:41.2719138Z ---- [ui] ui-fulldeps/roman-numerals-macro.rs stdout ----
2019-10-29T02:59:41.2719541Z 
2019-10-29T02:59:41.2720040Z error: auxiliary build of "/checkout/src/test/ui-fulldeps/auxiliary/roman-numerals.rs" failed to compile: 
2019-10-29T02:59:41.2720458Z status: exit code: 1
2019-10-29T02:59:41.2721797Z command: "/checkout/obj/build/x86_64-unknow [...]

2019-10-29 08:24 UTC, davidtwco requested changes
I'd like to see the last commit's changes squashed into the relevant commits that introduced the issues, but otherwise, r=me.

2019-10-30 13:21 UTC, Centril commented
Squashed -- was easier than I feared. :)

@bors r=davidtwco

2019-10-30 18:54 UTC, Centril commented
I'm not even going to try getting this through CI now that the toolstate week is in effect. :)

@bors r-

2019-11-06 06:29 UTC, Centril commented
Toolstate should be breakable again, @bors r=davidtwco

2019-11-06 10:02 UTC, Centril commented
@bors r=davidtwco

2019-11-07 04:20 UTC, Centril commented
@bors r=davidtwco

2019-11-07 13:00 UTC, Centril commented
@bors r=davidtwco

2019-11-08 01:15 UTC, merged