Adding docs for keyword match, move
rust-lang/rust pull request #66904
Opened 2019-11-30 14:06 UTC by DevinR528

Partial fix of issue #34601.

2019-11-30 14:06 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @shepmaster (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2019-11-30 14:24 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=14838&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/14838/logs/65), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/14838/logs/65)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-11-30T14:07:14.0801174Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-11-30T14:07:14.9860057Z ##[command]git config gc.auto 0
2019-11-30T14:07:14.9862532Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-11-30T14:07:14.9864014Z ##[command]git config --get-all http.proxy
2019-11-30T14:07:14.9866590Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/66904/merge:refs/remotes/pull/66904/merge
---
2019-11-30T14:12:41.1400072Z Done!
2019-11-30T14:12:41.1400106Z some tidy checks failed
2019-11-30T14:12:41.1400152Z 
2019-11-30T14:12:41.1400174Z 
2019-11-30T14:12:41.1400965Z command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor"
2019-11-30T14:12:41.1401069Z 
2019-11-30T14:12:41.1401092Z 
2019-11-30T14:12:41.1404289Z failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
2019-11-30T14:12:41.1404624Z Build completed unsuccessfully in 0:01:17
2019-11-30T14:12:41.1404624Z Build completed unsuccessfully in 0:01:17
2019-11-30T14:12:41.1439390Z == clock drift check ==
2019-11-30T14:12:41.1447087Z   local time: Sat Nov 30 14:12:41 UTC 2019
2019-11-30T14:12:41.4332978Z   network time: Sat, 30 Nov 2019 14:12:41 GMT
2019-11-30T14:12:41.4334536Z == end clock drift check ==
2019-11-30T14:12:42.8309409Z 
2019-11-30T14:12:42.8411755Z ##[error]Bash exited with code '1'.
2019-11-30T14:12:42.8433344Z ##[section]Starting: Checkout
2019-11-30T14:12:42.8434734Z ==============================================================================
2019-11-30T14:12:42.8434777Z Task         : Get sources
2019-11-30T14:12:42.8434813Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-11-30 17:03 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-6.0` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=14841&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/14841/logs/69), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/14841/logs/69)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-11-30T15:25:10.1939922Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-11-30T15:25:10.7658988Z ##[command]git config gc.auto 0
2019-11-30T15:25:10.7662406Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-11-30T15:25:10.7666743Z ##[command]git config --get-all http.proxy
2019-11-30T15:25:10.7672415Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/66904/merge:refs/remotes/pull/66904/merge
---
2019-11-30T16:28:32.3559068Z .................................................................................................... 1600/9312
2019-11-30T16:28:37.1611686Z .................................................................................................... 1700/9312
2019-11-30T16:28:50.4217490Z ........................................i........................................................... 1800/9312
2019-11-30T16:28:58.6121625Z .................................................................................................... 1900/9312
2019-11-30T16:29:13.3136229Z .........................iiiii...................................................................... 2000/9312
2019-11-30T16:29:23.8521530Z .................................................................................................... 2200/9312
2019-11-30T16:29:26.5301730Z .................................................................................................... 2300/9312
2019-11-30T16:29:31.2775343Z .................................................................................................... 2400/9312
2019-11-30T16:29:54.2630229Z .................................................................................................... 2500/9312
---
2019-11-30T16:32:47.1400844Z ...........................i...............i........................................................ 4800/9312
2019-11-30T16:32:58.5046910Z .................................................................................................... 4900/9312
2019-11-30T16:33:05.6065198Z .................................................................................................... 5000/9312
2019-11-30T16:33:14.7361527Z .................................................................................................... 5100/9312
2019-11-30T16:33:23.0336863Z ................................ii.ii...........i................................................... 5200/9312
2019-11-30T16:33:33.3864621Z .................................................................................................... 5400/9312
2019-11-30T16:33:44.3997299Z .................................................................................................... 5500/9312
2019-11-30T16:33:51.9429649Z ..............i..................................................................................... 5600/9312
2019-11-30T16:33:58.8062715Z .................................................................................................... 5700/9312
2019-11-30T16:33:58.8062715Z .................................................................................................... 5700/9312
2019-11-30T16:34:10.9137367Z .................................................................................................... 5800/9312
2019-11-30T16:34:23.9872300Z ii...i..ii...........i.............................................................................. 5900/9312
2019-11-30T16:34:43.7607155Z .................................................................................................... 6100/9312
2019-11-30T16:34:50.3451826Z .................................................................................................... 6200/9312
2019-11-30T16:34:50.3451826Z .................................................................................................... 6200/9312
2019-11-30T16:35:05.4426918Z .......................i..ii........................................................................ 6300/9312
2019-11-30T16:35:28.0046233Z ...........................................................................................i........ 6500/9312
2019-11-30T16:35:29.6124738Z .................................................................................................... 6600/9312
2019-11-30T16:35:32.0937991Z ..................................................................................i................. 6700/9312
2019-11-30T16:35:35.0012703Z .................................................................................................... 6800/9312
---
2019-11-30T16:41:16.5627600Z  finished in 6.608
2019-11-30T16:41:16.5841962Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-11-30T16:41:16.7815704Z 
2019-11-30T16:41:16.7816971Z running 164 tests
2019-11-30T16:41:19.9158093Z iiii....iii......iii..iiii...i.............................i..i..................i....i...........ii 100/164
2019-11-30T16:41:22.1763497Z .i.i..iiii..iiiiiii............i.........iii..i.........ii......
2019-11-30T16:41:22.1766409Z 
2019-11-30T16:41:22.1774993Z  finished in 5.593
2019-11-30T16:41:22.2003952Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-11-30T16:41:22.3785575Z 
---
2019-11-30T16:41:24.5323368Z  finished in 2.332
2019-11-30T16:41:24.5533701Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-11-30T16:41:24.7282595Z 
2019-11-30T16:41:24.7285703Z running 9 tests
2019-11-30T16:41:24.7286628Z iiiiiiiii
2019-11-30T16:41:24.7287415Z 
2019-11-30T16:41:24.7299806Z  finished in 0.175
2019-11-30T16:41:24.7495498Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-11-30T16:41:24.9394931Z 
---
2019-11-30T16:41:45.8580651Z  finished in 21.108
2019-11-30T16:41:45.8824941Z Check compiletest suite=debuginfo mode=debuginfo-gdb+lldb (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-11-30T16:41:46.1038467Z 
2019-11-30T16:41:46.1038787Z running 124 tests
2019-11-30T16:42:14.1202288Z .iiiii...i.....i..i...i..i.i.i..i.ii..i.i.....i..i....ii..........iiii..........i....ii...i.......ii 100/124
2019-11-30T16:42:18.8626931Z .i.i.i......iii.i.....ii
2019-11-30T16:42:18.8627776Z 
2019-11-30T16:42:18.8628410Z  finished in 32.980
2019-11-30T16:42:18.8639229Z Uplifting stage1 rustc (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2019-11-30T16:42:18.8639989Z Copying stage2 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
---
2019-11-30T16:55:20.2293821Z 
2019-11-30T16:55:20.2294595Z    Doc-tests core
2019-11-30T16:55:25.8951613Z 
2019-11-30T16:55:25.8951849Z running 2421 tests
2019-11-30T16:55:37.4539187Z ......iiiii......................................................................................... 100/2421
2019-11-30T16:56:01.6771401Z .................................................................................................... 300/2421
2019-11-30T16:56:15.1750688Z ..i................................................................................................. 400/2421
2019-11-30T16:56 [...]

2019-11-30 20:15 UTC, Dylan-DPC commented
r? @Dylan-DPC

2019-11-30 22:58 UTC, DevinR528 commented
Sorry about cluttering everything up I'm still getting used to everything. That should be it I ran the tidy script on my end first.

2019-12-01 14:37 UTC, Dylan-DPC-zz requested changes

2019-12-01 14:37 UTC, Dylan-DPC commented on src/libstd/keyword_docs.rs
> +/// `_` in the `match`. Since `match` is an expression values can also be
```suggestion
/// `_` in the `match`. Since `match` is an expression, values can also be
```

2019-12-01 14:37 UTC, Dylan-DPC commented on src/libstd/keyword_docs.rs
> +/// variables, when `move` is used the closures is represented by the `FnOnce` trait.
```suggestion
/// variables, when `move` is used, the closures is represented by the `FnOnce` trait.
```

2019-12-02 00:48 UTC, DevinR528 commented
Thanks for the feed back I made the changes. If I want to do more of these keyword docs should I do as many as I can in one PR or one per PR. First Rust PR!!

2019-12-02 10:05 UTC, Dylan-DPC commented
@bors r+ rollup

2019-12-03 16:27 UTC, merged