Stabilise vec::remove_item
rust-lang/rust pull request #67727
Opened 2019-12-30 11:52 UTC by Dylan-DPC

Closes #40062

r? @alexcrichton

2019-12-30 11:52 UTC, rust-highfive commented
:warning: **Warning** :warning:

* These commits modify **submodules**.

2019-12-30 11:55 UTC, Dylan-DPC commented
uggh some git mess up.. let me fix it :D

2019-12-30 11:56 UTC, rust-highfive commented
The job `x86_64-gnu-tools` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=17142&view=logs&jobId=e50ab380-190b-535c-8a18-25c988f7577b) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/17142/logs/78), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/17142/logs/78)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-12-30T11:52:57.3794755Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-12-30T11:52:57.9798645Z ##[command]git config gc.auto 0
2019-12-30T11:52:57.9806083Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-12-30T11:52:57.9810360Z ##[command]git config --get-all http.proxy
2019-12-30T11:52:57.9813549Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/67727/merge:refs/remotes/pull/67727/merge
---
2019-12-30T11:56:06.6577270Z warning: /checkout/src/tools/miri/Cargo.toml: the cargo feature `default-run` is now stable and is no longer necessary to be listed in the manifest
2019-12-30T11:56:06.6864413Z error: failed to resolve patches for `https://github.com/rust-lang/cargo`
2019-12-30T11:56:06.6864547Z 
2019-12-30T11:56:06.6864904Z Caused by:
2019-12-30T11:56:06.6865655Z   patch for `cargo` in `https://github.com/rust-lang/cargo` did not resolve to any crates. If this is unexpected, you may wish to consult: https://github.com/rust-lang/cargo/issues/4678
2019-12-30T11:56:06.6878552Z Build completed unsuccessfully in 0:00:16
2019-12-30T11:56:06.6940106Z Makefile:67: recipe for target 'prepare' failed
2019-12-30T11:56:06.6940281Z make: *** [prepare] Error 1
2019-12-30T11:56:07.6958444Z Command failed. Attempt 2/5:
2019-12-30T11:56:07.6958444Z Command failed. Attempt 2/5:
2019-12-30T11:56:07.7881745Z warning: /checkout/src/tools/miri/Cargo.toml: the cargo feature `default-run` is now stable and is no longer necessary to be listed in the manifest
2019-12-30T11:56:07.8177745Z error: failed to resolve patches for `https://github.com/rust-lang/cargo`
2019-12-30T11:56:07.8178422Z 
2019-12-30T11:56:07.8178756Z Caused by:
2019-12-30T11:56:07.8179597Z   patch for `cargo` in `https://github.com/rust-lang/cargo` did not resolve to any crates. If this is unexpected, you may wish to consult: https://github.com/rust-lang/cargo/issues/4678
2019-12-30T11:56:07.8190647Z Build completed unsuccessfully in 0:00:00
2019-12-30T11:56:07.8242731Z Makefile:67: recipe for target 'prepare' failed
2019-12-30T11:56:07.8242847Z make: *** [prepare] Error 1
2019-12-30T11:56:09.8261624Z Command failed. Attempt 3/5:
2019-12-30T11:56:09.8261624Z Command failed. Attempt 3/5:
2019-12-30T11:56:09.9173682Z warning: /checkout/src/tools/miri/Cargo.toml: the cargo feature `default-run` is now stable and is no longer necessary to be listed in the manifest
2019-12-30T11:56:09.9464899Z error: failed to resolve patches for `https://github.com/rust-lang/cargo`
2019-12-30T11:56:09.9464976Z 
2019-12-30T11:56:09.9465041Z Caused by:
2019-12-30T11:56:09.9465896Z   patch for `cargo` in `https://github.com/rust-lang/cargo` did not resolve to any crates. If this is unexpected, you may wish to consult: https://github.com/rust-lang/cargo/issues/4678
2019-12-30T11:56:09.9474402Z Build completed unsuccessfully in 0:00:00
2019-12-30T11:56:09.9522089Z Makefile:67: recipe for target 'prepare' failed
2019-12-30T11:56:09.9522208Z make: *** [prepare] Error 1
2019-12-30T11:56:12.9545471Z Command failed. Attempt 4/5:
2019-12-30T11:56:12.9545471Z Command failed. Attempt 4/5:
2019-12-30T11:56:13.0469125Z warning: /checkout/src/tools/miri/Cargo.toml: the cargo feature `default-run` is now stable and is no longer necessary to be listed in the manifest
2019-12-30T11:56:13.0758046Z error: failed to resolve patches for `https://github.com/rust-lang/cargo`
2019-12-30T11:56:13.0758121Z 
2019-12-30T11:56:13.0758176Z Caused by:
2019-12-30T11:56:13.0758662Z   patch for `cargo` in `https://github.com/rust-lang/cargo` did not resolve to any crates. If this is unexpected, you may wish to consult: https://github.com/rust-lang/cargo/issues/4678
2019-12-30T11:56:13.0765989Z Build completed unsuccessfully in 0:00:00
2019-12-30T11:56:13.0814502Z Makefile:67: recipe for target 'prepare' failed
2019-12-30T11:56:13.0814590Z make: *** [prepare] Error 1
2019-12-30T11:56:17.0828603Z Command failed. Attempt 5/5:
2019-12-30T11:56:17.0828603Z Command failed. Attempt 5/5:
2019-12-30T11:56:17.1781843Z warning: /checkout/src/tools/miri/Cargo.toml: the cargo feature `default-run` is now stable and is no longer necessary to be listed in the manifest
2019-12-30T11:56:17.2083677Z error: failed to resolve patches for `https://github.com/rust-lang/cargo`
2019-12-30T11:56:17.2083763Z 
2019-12-30T11:56:17.2083857Z Caused by:
2019-12-30T11:56:17.2084483Z   patch for `cargo` in `https://github.com/rust-lang/cargo` did not resolve to any crates. If this is unexpected, you may wish to consult: https://github.com/rust-lang/cargo/issues/4678
2019-12-30T11:56:17.2094793Z Build completed unsuccessfully in 0:00:00
2019-12-30T11:56:17.2141632Z Makefile:67: recipe for target 'prepare' failed
2019-12-30T11:56:17.2141754Z make: *** [prepare] Error 1
2019-12-30T11:56:17.2149440Z The command has failed after 5 attempts.
2019-12-30T11:56:17.2149440Z The command has failed after 5 attempts.
2019-12-30T11:56:17.2149577Z == clock drift check ==
2019-12-30T11:56:17.2160483Z   local time: Mon Dec 30 11:56:17 UTC 2019
2019-12-30T11:56:17.2443381Z   network time: Mon, 30 Dec 2019 11:56:17 GMT
2019-12-30T11:56:17.2443568Z == end clock drift check ==
2019-12-30T11:56:28.4335215Z 
2019-12-30T11:56:28.4449135Z ##[error]Bash exited with code '1'.
2019-12-30T11:56:28.4481621Z ##[section]Starting: Checkout
2019-12-30T11:56:28.4483444Z ==============================================================================
2019-12-30T11:56:28.4483504Z Task         : Get sources
2019-12-30T11:56:28.4483553Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-12-30 13:09 UTC, jfrimmel requested changes
I'm pretty sure, that the new test doesn't work in the current form :smile:

2019-12-30 13:09 UTC, jfrimmel commented on src/liballoc/tests/vec.rs
> +    assert_eq!(v.len(2));
```suggestion
    assert_eq!(v.len(), 2);
```

2019-12-30 13:09 UTC, jfrimmel commented on src/liballoc/tests/vec.rs
> +    assert_eq!(v, [1,3]);
Shouldn't this be `assert_eq!(v, [2, 3])`?

2019-12-30 13:09 UTC, jfrimmel commented on src/liballoc/tests/vec.rs
> +    let mut y = vec![1,2,3];
```suggestion
    let mut v = vec![1,2,3];
```

2019-12-30 13:09 UTC, jfrimmel commented on src/liballoc/tests/vec.rs
> +    assert_eq!(v.len(3));
```suggestion
    assert_eq!(w.len(), 3);
```

2019-12-31 07:04 UTC, Dylan-DPC commented
@jfrimmel ye you right :D had a gcc issue so just went with the tests _in blind form_ waiting for the CI to tell me what's wrong :P fixed everything now. Thanks for the review

2019-12-31 07:12 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=17213&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/17213/logs/65), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/17213/logs/65)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2019-12-31T06:52:12.8216044Z ##[command]git remote add origin https://github.com/rust-lang/rust
2019-12-31T06:52:12.8397746Z ##[command]git config gc.auto 0
2019-12-31T06:52:12.8469638Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2019-12-31T06:52:12.8524814Z ##[command]git config --get-all http.proxy
2019-12-31T06:52:12.8658826Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/67727/merge:refs/remotes/pull/67727/merge
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2019-12-31 08:55 UTC, Dylan-DPC commented
spurious... 

@bors retry

2019-12-31 10:54 UTC, Dylan-DPC commented
@bors try

2020-01-03 18:40 UTC, timvermeulen commented
Many people suggested in the tracking issue to have this method take a `&U` with `T: PartialEq<U>` instead of a `&T`, shouldn't this be implemented before we stabilize this? In particular, this doesn't compile at the moment:
```rust
let mut vec = vec![String::from("foo")];
vec.remove_item("foo");
//              ^^^^^ expected struct `std::string::String`, found `str`
```

2020-01-04 18:18 UTC, Dylan-DPC commented
Created a new PR that made that change. Blocked on #67873

2020-01-06 15:11 UTC, Dylan-DPC commented
r? @Amanieu

2020-01-06 15:40 UTC, alexcrichton commented
Looks like FCP has finished on https://github.com/rust-lang/rust/issues/40062 and while there's been discussion since it doesn't seem ground-shaking, so I'm going to approve. 

@bors: r+

2020-01-06 16:27 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=17679&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/17679/logs/69), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/17679/logs/69)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-01-06T15:09:16.3887441Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-01-06T15:09:16.4089777Z ##[command]git config gc.auto 0
2020-01-06T15:09:16.4165842Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-01-06T15:09:16.4224476Z ##[command]git config --get-all http.proxy
2020-01-06T15:09:16.4386734Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/67727/merge:refs/remotes/pull/67727/merge
---
2020-01-06T16:03:47.9903483Z .................................................................................................... 1500/9477
2020-01-06T16:03:53.8423549Z .................................................................................................... 1600/9477
2020-01-06T16:03:58.7239245Z .................................................................................................... 1700/9477
2020-01-06T16:04:08.0724491Z .................................................................................................... 1800/9477
2020-01-06T16:04:16.2894378Z .i.................................................................................................. 1900/9477
2020-01-06T16:04:22.9996130Z .........................................................................................iiiii...... 2000/9477
2020-01-06T16:04:45.1315284Z .................................................................................................... 2200/9477
2020-01-06T16:04:47.5066117Z .................................................................................................... 2300/9477
2020-01-06T16:04:49.9167588Z .................................................................................................... 2400/9477
2020-01-06T16:04:55.8792120Z .................................................................................................... 2500/9477
---
2020-01-06T16:07:54.6626609Z .....................i...............i.............................................................. 4900/9477
2020-01-06T16:08:04.3762681Z .................................................................................................... 5000/9477
2020-01-06T16:08:10.3836770Z ..................................................................i................................. 5100/9477
2020-01-06T16:08:18.3516155Z .................................................................................................... 5200/9477
2020-01-06T16:08:26.0114108Z .................................ii.ii...........i.................................................. 5300/9477
2020-01-06T16:08:35.3921262Z .................................................................................................... 5500/9477
2020-01-06T16:08:45.2430103Z .................................................................................................... 5600/9477
2020-01-06T16:08:52.7261967Z .................i.................................................................................. 5700/9477
2020-01-06T16:08:59.1248214Z .................................................................................................... 5800/9477
2020-01-06T16:08:59.1248214Z .................................................................................................... 5800/9477
2020-01-06T16:09:11.1488143Z .................................................................................................... 5900/9477
2020-01-06T16:09:23.0418440Z .......ii...i..ii...........i....................................................................... 6000/9477
2020-01-06T16:09:40.7638902Z .................................................................................................... 6200/9477
2020-01-06T16:09:48.5356576Z .................................................................................................... 6300/9477
2020-01-06T16:09:48.5356576Z .................................................................................................... 6300/9477
2020-01-06T16:10:02.6514263Z ..................................i..ii............................................................. 6400/9477
2020-01-06T16:10:23.8052838Z .................................................................................................... 6600/9477
2020-01-06T16:10:25.9740637Z .........i.......................................................................................... 6700/9477
2020-01-06T16:10:28.4240401Z .................................................................................................... 6800/9477
2020-01-06T16:10:31.0829847Z .........i.......................................................................................... 6900/9477
---
2020-01-06T16:12:08.9567430Z .................................................................................................... 7500/9477
2020-01-06T16:12:13.0601849Z .................................................................................................... 7600/9477
2020-01-06T16:12:18.2396419Z .................................................................................................... 7700/9477
2020-01-06T16:12:28.8536409Z .................................................................................................... 7800/9477
2020-01-06T16:12:37.2361113Z .............................................iiii................................................... 7900/9477
2020-01-06T16:12:52.0672397Z .................................................................................................... 8100/9477
2020-01-06T16:12:58.6182976Z .................................................................................................... 8200/9477
2020-01-06T16:13:14.0010464Z .................................................................................................... 8300/9477
2020-01-06T16:13:21.6208889Z .................................................................................................... 8400/9477
---
2020-01-06T16:15:44.5857093Z  finished in 6.667
2020-01-06T16:15:44.6035963Z Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2020-01-06T16:15:44.7589020Z 
2020-01-06T16:15:44.7589272Z running 166 tests
2020-01-06T16:15:47.9903679Z iiii......i........ii..iiii...i....i...........i............i..i..................i....i............ 100/166
2020-01-06T16:15:50.2034806Z i.i.i...iii..iiiiiii.......................iii............ii......
2020-01-06T16:15:50.2035583Z 
2020-01-06T16:15:50.2042033Z  finished in 5.600
2020-01-06T16:15:50.2222774Z Check compiletest suite=codegen-units mode=codegen-units (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2020-01-06T16:15:50.3808490Z 
---
2020-01-06T16:15:52.3161564Z  finished in 2.094
2020-01-06T16:15:52.3334349Z Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2020-01-06T16:15:52.4862711Z 
2020-01-06T16:15:52.4862963Z running 9 tests
2020-01-06T16:15:52.4863735Z iiiiiiiii
2020-01-06T16:15:52.4864126Z 
2020-01-06T16:15:52.4868798Z  finished in 0.153
2020-01-06T16:15:52.5039040Z Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
2020-01-06T1 [...]

2020-01-06 17:56 UTC, alexcrichton commented
@bors: r-

(CI failures)

2020-01-06 17:57 UTC, Dylan-DPC commented
ye forgot to remove 1 feature gate.. pushing it now :)

2020-01-06 18:24 UTC, alexcrichton commented
@bors: r+

2020-01-07 08:11 UTC, merged

2020-01-07 12:51 UTC, kornelski commented
Please don't stabilise it without fixing the name!

Please don't call it just `remove_item`, as this is the same name as in other languages that _can_ remove item from an array by presenting an item from the same array. Rust's version can't do that due to borrow checker and it's a trap for users.