Clean up err codes
rust-lang/rust pull request #67837
Opened 2020-01-03 16:43 UTC by GuillaumeGomez

r? @Dylan-DPC

2020-01-03 17:59 UTC, Dylan-DPC-zz requested changes

2020-01-03 17:59 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0136.md
> +rename one.
```suggestion
rename one of them.
```

2020-01-03 17:59 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0161.md
> +A value was moved while size was not known at compile time.
```suggestion
A value was moved whose size was not known at compile time.
```

2020-01-03 17:59 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0164.md
> +Something which isn't a tuple struct nor a tuple variant was used as a pattern.
```suggestion
Something which is neither a tuple struct nor a tuple variant was used as a pattern.
```

2020-01-03 17:59 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0164.md
> +This error means that an attempt was made to match something which isn't a tuple
```suggestion
This error means that an attempt was made to match something which is neither
```

2020-01-03 17:59 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0164.md
> +struct nor a tuple variant. Only those two elements are allowed as pattern:
```suggestion
a tuple struct nor a tuple variant. Only these two elements are allowed as pattern:
```

2020-01-03 23:33 UTC, GuillaumeGomez commented
Updated! Thanks for the review @Dylan-DPC ! :)

2020-01-04 09:20 UTC, Dylan-DPC commented
@bors r+ rollup

2020-01-04 15:34 UTC, merged