clean up E0185 explanation
rust-lang/rust pull request #68070
Opened 2020-01-09 21:26 UTC by GuillaumeGomez

r? @Dylan-DPC

2020-01-10 06:19 UTC, Dylan-DPC-zz requested changes

2020-01-10 06:19 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0185.md
> +signature. So in this case, since `Foo::foo` doesn't take argument and doesn't
```suggestion
signature. So in this case, since `Foo::foo` doesn't take any arguments or 
```

2020-01-10 06:19 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0185.md
> +return anything, its implementation on `Bar` should the same:
```suggestion
return anything, its implementation on `Bar` should be the same:
```

2020-01-10 09:05 UTC, GuillaumeGomez commented
Updated!

2020-01-11 05:32 UTC, Dylan-DPC commented
@bors r+ rollup

2020-01-11 14:46 UTC, merged