Suggest to shorten temporary lifetime during method call
rust-lang/rust pull request #68212
Opened 2020-01-14 13:26 UTC by csmoe

Closes https://github.com/rust-lang/rust/issues/67376
r? @estebank 
cc @tmandry @nikomatsakis

2020-01-14 13:48 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=18403&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/18403/logs/66), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/18403/logs/66)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-01-14T13:27:00.1317442Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-01-14T13:27:00.1346766Z ##[command]git config gc.auto 0
2020-01-14T13:27:00.1349250Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-01-14T13:27:00.1351267Z ##[command]git config --get-all http.proxy
2020-01-14T13:27:00.1353661Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/68212/merge:refs/remotes/pull/68212/merge
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2020-01-14 15:22 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=18408&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/18408/logs/66), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/18408/logs/66)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-01-14T15:01:23.6866987Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-01-14T15:01:23.6877772Z ##[command]git config gc.auto 0
2020-01-14T15:01:23.6915524Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-01-14T15:01:23.6993860Z ##[command]git config --get-all http.proxy
2020-01-14T15:01:23.7191359Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/68212/merge:refs/remotes/pull/68212/merge
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2020-01-14 20:27 UTC, nikomatsakis requested changes

2020-01-14 20:27 UTC, nikomatsakis commented on src/librustc/traits/error_reporting.rs
> +            }
this looks like roughly what I expected to see =) seems good, from a quick glance!

2020-01-14 20:27 UTC, nikomatsakis commented on src/librustc/ty/context.rs
> +    pub generator_interior_types: Vec<(GeneratorInteriorTypeCause<'tcx>, Option<hir::HirId>)>,
er, wait, maybe we should move this `Option<hir::HirId>` into the `GeneratorInteriorTypeCause` structure?

2020-01-14 23:01 UTC, estebank commented
After applying niko's suggestion, r=me.

2020-01-15 11:58 UTC, csmoe commented
r=@estebank

2020-01-15 15:54 UTC, estebank commented
@bors r+

2020-01-15 22:39 UTC, merged