Clean up E0205 explanation
rust-lang/rust pull request #68383
Opened 2020-01-20 12:34 UTC by GuillaumeGomez

r? @Dylan-DPC

2020-01-20 12:50 UTC, Dylan-DPC-zz requested changes

2020-01-20 12:50 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0206.md
> +The `Copy` trait was implemented on a type which isn't a struct or an enum.
```suggestion
The `Copy` trait was implemented on a type which is neither a struct nor an enum.
```

2020-01-20 12:50 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0206.md
> +You can only implement `Copy` for a struct or enum. Both of the previous
```suggestion
You can only implement `Copy` for a struct or an enum. Both of the previous
```

2020-01-21 09:44 UTC, GuillaumeGomez commented
Updated!

2020-01-27 16:17 UTC, Dylan-DPC commented
@bors r+ rollup

2020-01-28 05:31 UTC, merged