clean up error codes explanation
rust-lang/rust pull request #68482
Opened 2020-01-23 12:29 UTC by GuillaumeGomez

r? @Dylan-DPC

2020-01-23 13:12 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0220.md
> +A used associated type wasn't defined in the trait.
```suggestion
An associated type was used which was not defined in the trait.
```

2020-01-24 11:34 UTC, GuillaumeGomez commented on src/librustc_error_codes/error_codes/E0220.md
> +A used associated type wasn't defined in the trait.
This sentence makes no sentence. :p

2020-01-24 23:03 UTC, Dylan-DPC-zz requested changes

2020-01-24 23:03 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0220.md
> +A used associated type wasn't defined in the trait.
```suggestion
The associated type used was not defined in the trait.
```

2020-01-27 15:06 UTC, GuillaumeGomez commented
Updated!

2020-01-27 15:14 UTC, Dylan-DPC commented
@bors r+ rollup

2020-01-28 05:31 UTC, merged