clean up E0275 explanation
rust-lang/rust pull request #68897
Opened 2020-02-06 16:53 UTC by GuillaumeGomez

r? @Dylan-DPC

2020-02-06 17:03 UTC, Dylan-DPC-zz requested changes

2020-02-06 17:03 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0275.md
> +A requirement evaluation overflowed.
```suggestion
An evaluation of a trait requirement overflowed.
```

2020-02-06 17:03 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0275.md
> +before it could be evaluated. Often this means that there is unbounded
```suggestion
before it could be evaluated. This often means that there is an unbounded
```

2020-02-10 12:26 UTC, GuillaumeGomez commented
Updated!

2020-02-10 16:23 UTC, Dylan-DPC commented
@bors r+ rollup

2020-02-11 02:00 UTC, merged