Stabilize assoc_int_consts associated int/float constants
rust-lang/rust pull request #68952
Opened 2020-02-08 12:05 UTC by faern

The next step in RFC https://github.com/rust-lang/rfcs/pull/2700 (tracking issue #68490). Stabilizing the associated constants that were added in #68325.

* Stabilize all constants under the `assoc_int_consts` feature flag.
* Update documentation on old constants to say they are soft-deprecated and the new ones should be preferred.
* Update documentation examples to use new constants.
* Remove `uint_macro` and use `int_macro` for all integer types since the macros were identical anyway.

r? @LukasKalbertodt

2020-02-09 10:53 UTC, LukasKalbertodt approved these changes
Great work, thanks! 

(If you are comfortable with git rebase/squash/fixup you could improve the git history a bit by squashing your three "Fix ..." commits with the respective commits that is being fixed. That makes it a bit easier for commit-by-commit reviewing. However, that's really not important.)

2020-02-09 10:54 UTC, LukasKalbertodt commented
The code changes are good. However, as I mentioned in chat, I am not really a fan of stabilizing these constants only a few weeks after they have been added. @Mark-Simulacrum disagreed. To get another opinion and since I can't start FCP merges anyway, reassigning:

r? @dtolnay

2020-02-09 12:07 UTC, faern commented
Git history fixed :) I usually do that, but must have been lazy this time. Thanks.

With regards to when to stabilize. My two cents is that things sit around as unstable because we are evaluating if the naming is good, the API has a usable/ergonomic design, it's properly implemented, people actually seem to use/want this etc. But we basically already know all those things for this feature. It just moves an existing feature.

For reference, the `SystemTime::UNIX_EPOCH` assoc const took two months from unstable to stable. But that included the RFC process, since it was added as unstable before any RFC was even posted. So not a fair comparison. These constants here have already been debated for nine months already :)

2020-02-10 01:25 UTC, dtolnay requested changes
Thanks, I think it's pretty clear that we want these so I am on board with moving forward.

I think the deprecation notice on the integer modules is too aggressive for now.

> <img src="https://user-images.githubusercontent.com/1940490/74114576-c1958780-4b5f-11ea-9d26-2592bb2d05a5.png" width="60%">

Could you remove the bold second sentences? I think this is not among the most important information to feature in the module index, especially not with emphasis. I think the links inside the module showing what to use instead are sufficient.

> <img src="https://user-images.githubusercontent.com/1940490/74114577-c5290e80-4b5f-11ea-8614-1aac53bce0d7.png" width="70%">

Could you also restore the "*See also the i16 primitive type.*" links exactly how it existed before? Anyone who lands on the module's documentation is much more likely looking for the type and its methods, not the associated constants. So the way you've put the type link at the end of a paragraph about deprecation warnings and associated constants is not as good.

2020-02-10 10:23 UTC, faern commented
> Could you remove the bold second sentences?

Sure. Add it to a new line so it ends up in the module docs, but not in the first-line summary like now? Or remove `This module is soft-deprecated` completely and just keep the paragraph on how using these constants won't cause compilation warnings (for now) but new users should prefer the associated constants?

> Could you also restore the "See also the i16 primitive type."

Will do.

2020-02-10 19:14 UTC, faern commented
Done.

2020-02-10 19:23 UTC, dtolnay approved these changes

2020-02-10 19:23 UTC, dtolnay commented
@rfcbot fcp merge

@rust-lang/libs: This stabilizes associated constants on the primitive integer and float types to make e.g. i64::MAX work the way we've always liked for them to work, without importing std::i64.

The constants involved are:

- On all the integers: MIN and MAX
- On the floats: RADIX, MANTISSA_DIGITS, DIGITS, EPSILON, MIN, MIN_POSITIVE, MAX, MIN_EXP, MAX_EXP, MIN_10_EXP, MAX_10_EXP, NAN, INFINITY, NEG_INFINITY

The existing module-level constants' documentation will now link to the associated constants, but we don't trigger any new deprecation warnings. We can navigate deprecation at some (far) later time.

2020-03-04 05:26 UTC, dtolnay approved these changes
:tada:

2020-03-04 05:26 UTC, dtolnay commented
@bors r+

2020-03-04 10:45 UTC, merged