Clean up E0283 explanation
rust-lang/rust pull request #69007
Opened 2020-02-09 22:12 UTC by GuillaumeGomez

r? @Dylan-DPC

2020-02-09 22:24 UTC, Dylan-DPC-zz requested changes

2020-02-09 22:24 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0283.md
> +An implementation cannot be chose unambiguously because of the lack of
```suggestion
An implementation cannot be chosen unambiguously because of lack of
```

2020-02-09 22:24 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0283.md
> +This error can be solved by adding type annotations to give the missing
```suggestion
This error can be solved by adding type annotations that provide the missing
```

2020-02-09 22:24 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0283.md
> +information to the compier. In this case, the solution is to use a concrete
```suggestion
information to the compiler. In this case, the solution is to use a concrete
```

2020-02-10 12:24 UTC, GuillaumeGomez commented
Updated!

2020-02-10 14:29 UTC, Dylan-DPC commented
@bors r+ rollup

2020-02-11 02:00 UTC, merged