Remove backtrace header text
rust-lang/rust pull request #69042
Opened 2020-02-10 21:24 UTC by yaahc

Fixes point 3 from https://github.com/rust-lang/rust/issues/65280

This should probably be double checked by someone who works on fuschia because theres some extra fuschia specific output in `add_context` that is also removed by this change.

2020-02-10 21:24 UTC, rust-highfive commented
r? @alexcrichton

(rust_highfive has picked a reviewer for you, use r? to override)

2020-02-10 21:49 UTC, dtolnay commented
r? @dtolnay

2020-02-10 21:52 UTC, dtolnay requested changes
I think we want to keep the add_context call. BacktraceFmt::add_context is documented as:

> This is required on some platforms for backtraces to be fully symbolicated later, and otherwise this should just be the first method you call after creating a `BacktraceFmt`.

That sounds like a behavior that we want to keep.

I think all we want for this item in #65280 is to remove the "stack backtrace:" printed by add_context.

2020-02-10 21:58 UTC, yaahc commented
> I think we want to keep the add_context call. BacktraceFmt::add_context is documented as:
> 
> > This is required on some platforms for backtraces to be fully symbolicated later, and otherwise this should just be the first method you call after creating a `BacktraceFmt`.
> 
> That sounds like a behavior that we want to keep.
> 
> I think all we want for this item in #65280 is to remove the "stack backtrace:" printed by add_context.

Okay, I figured I'd try this first because @alexcrichton doesn't want to change the format of `backtrace_rs::Backtrace` and straight up removing the call in the upstream would do so, I'm guessing the symbolification that this does is the fuschia stuff I mentioned earlier.

Do you think it would be sufficient to add a new `add_context` fn to std that only does the following bit from backtrace-rs's `add_context`?

```rust
        #[cfg(target_os = "fuchsia")]
        fuchsia::print_dso_context(self.fmt)?;
        Ok(())
```

2020-02-10 22:09 UTC, dtolnay commented
Do you have a link to that discussion with Alex? I haven't seen that and I am not sure what all the constraints are. In any case, we don't need to change the Display or Debug behavior of the external backtrace::Backtrace, just std::backtrace::Backtrace -- inside the backtrace crate we can move the "stack backtrace:" header from add_context out to the Debug impl.

In the worst case it would also be reasonable to have std instantiate BacktraceFmt with a Formatter that discards "stack backtrace:" if it's the first thing printed.

2020-02-10 22:13 UTC, alexcrichton commented
Oh sorry for the confusion, but to clarify, I intened that the general format of the current output shouldn't change in the `backtrace` crate to change the current `Debug` to what the standard library will want to use for `Debug` (braces, commas, lists, etc). Minor formatting differences like `stack backtrace:\n` are fine to remove by me! I'd agree with @dtolnay that the best way to fix this would be to remove the printing of this in the `backtrace` crate, and I'd also agree that libstd still needs to call this so fuchsia backtraces work correctly on panics.

2020-02-10 22:15 UTC, yaahc commented
> inside the backtrace crate we can move the "stack backtrace:" header from add_context out to the Debug impl.

After I started working on this I realized that, so that will be pushed shortly along with a PR for backtrace-rs to add that and bump the version.

> I'd agree with @dtolnay that the best way to fix this would be to remove the printing of this in the backtrace crate, and I'd also agree that libstd still needs to call this so fuchsia backtraces work correctly on panics.

Okay, I'll just remove it in backtrace-rs rather than moving it and then reduce this change to just bumping the dependency version once that is done.

2020-02-10 22:24 UTC, rust-highfive commented
The job `mingw-check` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=20647&view=logs&jobId=74054d28-c774-5fab-ecc2-352fe71b230e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/20647/logs/66), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/20647/logs/66)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-02-10T22:21:20.3979443Z ========================== Starting Command Output ===========================
2020-02-10T22:21:20.3980768Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/4b4806fb-b198-4868-a2cb-b39f09cf0681.sh
2020-02-10T22:21:20.3980836Z 
2020-02-10T22:21:20.3983801Z ##[section]Finishing: Disable git automatic line ending conversion
2020-02-10T22:21:20.3991202Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/69042/merge to s
2020-02-10T22:21:20.3992910Z Task         : Get sources
2020-02-10T22:21:20.3992983Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-02-10T22:21:20.3993019Z Version      : 1.0.0
2020-02-10T22:21:20.3993049Z Author       : Microsoft
---
2020-02-10T22:21:21.1471504Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-02-10T22:21:21.1541616Z ##[command]git config gc.auto 0
2020-02-10T22:21:21.1611743Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-02-10T22:21:21.1662744Z ##[command]git config --get-all http.proxy
2020-02-10T22:21:21.1797741Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/69042/merge:refs/remotes/pull/69042/merge
---
2020-02-10T22:23:47.3118640Z #########################################################                 80.5%
2020-02-10T22:23:47.3118848Z ######################################################################## 100.0%
2020-02-10T22:23:47.5593561Z extracting /checkout/obj/build/cache/2020-01-31/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.gz
2020-02-10T22:23:47.6321772Z     Updating crates.io index
2020-02-10T22:24:00.9539316Z error: failed to select a version for the requirement `backtrace = "^0.3.44"`
2020-02-10T22:24:00.9541423Z   candidate versions found which didn't match: 0.3.43, 0.3.41, 0.3.40, ...
2020-02-10T22:24:00.9542189Z   location searched: crates.io index
2020-02-10T22:24:00.9542584Z required by package `std v0.0.0 (/checkout/src/libstd)`
2020-02-10T22:24:00.9564291Z Build completed unsuccessfully in 0:00:25
2020-02-10T22:24:00.9611298Z == clock drift check ==
2020-02-10T22:24:00.9621262Z   local time: Mon Feb 10 22:24:00 UTC 2020
2020-02-10T22:24:01.2461295Z   network time: Mon, 10 Feb 2020 22:24:01 GMT
2020-02-10T22:24:01.2461295Z   network time: Mon, 10 Feb 2020 22:24:01 GMT
2020-02-10T22:24:01.2464229Z == end clock drift check ==
2020-02-10T22:24:08.9195044Z 
2020-02-10T22:24:08.9277927Z ##[error]Bash exited with code '1'.
2020-02-10T22:24:08.9293347Z ##[section]Finishing: Run build
2020-02-10T22:24:08.9312646Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/69042/merge to s
2020-02-10T22:24:08.9315778Z Task         : Get sources
2020-02-10T22:24:08.9315825Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-02-10T22:24:08.9315887Z Version      : 1.0.0
2020-02-10T22:24:08.9315929Z Author       : Microsoft
2020-02-10T22:24:08.9315929Z Author       : Microsoft
2020-02-10T22:24:08.9315976Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
2020-02-10T22:24:08.9316065Z ==============================================================================
2020-02-10T22:24:09.2805701Z Cleaning any cached credential from repository: rust-lang/rust (GitHub)
2020-02-10T22:24:09.2845864Z ##[section]Finishing: Checkout rust-lang/rust@refs/pull/69042/merge to s
2020-02-10T22:24:09.2940407Z Cleaning up task key
2020-02-10T22:24:09.2941278Z Start cleaning up orphan processes.
2020-02-10T22:24:09.3031443Z Terminate orphan process: pid (3997) (python)
2020-02-10T22:24:09.3188399Z ##[section]Finishing: Finalize Job
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2020-02-11 13:48 UTC, Dylan-DPC commented
@bors try

2020-02-11 13:53 UTC, rust-highfive commented
The job `dist-x86_64-linux-alt` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=20715&view=logs&jobId=396dc680-0b3a-5910-2395-0c692e01f85b) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/20715/logs/59), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/20715/logs/59)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-02-11T13:52:48.9759970Z #                                                                          2.0%
2020-02-11T13:52:48.9760493Z ######################################################################## 100.0%
2020-02-11T13:52:49.2810653Z extracting /checkout/obj/build/cache/2020-01-31/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.gz
2020-02-11T13:52:49.4183576Z     Updating crates.io index
2020-02-11T13:53:04.6538732Z error: failed to select a version for the requirement `backtrace = "^0.3.44"`
2020-02-11T13:53:04.6539872Z   candidate versions found which didn't match: 0.3.43, 0.3.41, 0.3.40, ...
2020-02-11T13:53:04.6540141Z   location searched: crates.io index
2020-02-11T13:53:04.6547065Z required by package `std v0.0.0 (/checkout/src/libstd)`
2020-02-11T13:53:04.6547867Z Build completed unsuccessfully in 0:00:29
2020-02-11T13:53:04.6548160Z make: *** [prepare] Error 1
2020-02-11T13:53:05.1414794Z Command failed. Attempt 2/5:
2020-02-11T13:53:05.2821668Z     Updating crates.io index
2020-02-11T13:53:05.2821668Z     Updating crates.io index
2020-02-11T13:53:05.5238703Z error: failed to select a version for the requirement `backtrace = "^0.3.44"`
2020-02-11T13:53:05.5239819Z   candidate versions found which didn't match: 0.3.43, 0.3.41, 0.3.40, ...
2020-02-11T13:53:05.5239930Z   location searched: crates.io index
2020-02-11T13:53:05.5240002Z required by package `std v0.0.0 (/checkout/src/libstd)`
2020-02-11T13:53:05.5257312Z Build completed unsuccessfully in 0:00:00
2020-02-11T13:53:05.5300513Z make: *** [prepare] Error 1
2020-02-11T13:53:07.5318219Z Command failed. Attempt 3/5:
2020-02-11T13:53:07.6614729Z     Updating crates.io index
2020-02-11T13:53:07.6614729Z     Updating crates.io index
2020-02-11T13:53:07.8606305Z error: failed to select a version for the requirement `backtrace = "^0.3.44"`
2020-02-11T13:53:07.8607737Z   candidate versions found which didn't match: 0.3.43, 0.3.41, 0.3.40, ...
2020-02-11T13:53:07.8608028Z   location searched: crates.io index
2020-02-11T13:53:07.8608157Z required by package `std v0.0.0 (/checkout/src/libstd)`
2020-02-11T13:53:07.8626884Z Build completed unsuccessfully in 0:00:00
2020-02-11T13:53:07.8670380Z make: *** [prepare] Error 1
2020-02-11T13:53:10.8691898Z Command failed. Attempt 4/5:
2020-02-11T13:53:11.0086180Z     Updating crates.io index
2020-02-11T13:53:11.0086180Z     Updating crates.io index
2020-02-11T13:53:11.2482372Z error: failed to select a version for the requirement `backtrace = "^0.3.44"`
2020-02-11T13:53:11.2483492Z   candidate versions found which didn't match: 0.3.43, 0.3.41, 0.3.40, ...
2020-02-11T13:53:11.2483612Z   location searched: crates.io index
2020-02-11T13:53:11.2483684Z required by package `std v0.0.0 (/checkout/src/libstd)`
2020-02-11T13:53:11.2507174Z Build completed unsuccessfully in 0:00:00
2020-02-11T13:53:11.2549065Z make: *** [prepare] Error 1
2020-02-11T13:53:15.2563674Z Command failed. Attempt 5/5:
2020-02-11T13:53:15.4012415Z     Updating crates.io index
2020-02-11T13:53:15.4012415Z     Updating crates.io index
2020-02-11T13:53:15.6245583Z error: failed to select a version for the requirement `backtrace = "^0.3.44"`
2020-02-11T13:53:15.6246539Z   candidate versions found which didn't match: 0.3.43, 0.3.41, 0.3.40, ...
2020-02-11T13:53:15.6246651Z   location searched: crates.io index
2020-02-11T13:53:15.6246748Z required by package `std v0.0.0 (/checkout/src/libstd)`
2020-02-11T13:53:15.6264840Z Build completed unsuccessfully in 0:00:00
2020-02-11T13:53:15.6311245Z make: *** [prepare] Error 1
2020-02-11T13:53:15.6313818Z The command has failed after 5 attempts.
2020-02-11T13:53:15.6316892Z == clock drift check ==
2020-02-11T13:53:15.6316892Z == clock drift check ==
2020-02-11T13:53:15.6331195Z   local time: Tue Feb 11 13:53:15 UTC 2020
2020-02-11T13:53:15.9049420Z   network time: Tue, 11 Feb 2020 13:53:15 GMT
2020-02-11T13:53:15.9055318Z == end clock drift check ==
2020-02-11T13:53:22.7830534Z 
2020-02-11T13:53:22.7925467Z ##[error]Bash exited with code '1'.
2020-02-11T13:53:22.7966033Z ##[section]Starting: Checkout rust-lang/rust@try to s
2020-02-11T13:53:22.7968234Z ==============================================================================
2020-02-11T13:53:22.7968326Z Task         : Get sources
2020-02-11T13:53:22.7968427Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2020-02-11 16:41 UTC, yaahc commented
@Dylan-DPC this wont work until the PR to backtrace-rs is merged.

2020-02-11 16:42 UTC, yaahc commented
https://github.com/rust-lang/backtrace-rs/pull/286 is the PR in question

2020-02-11 18:09 UTC, Dylan-DPC commented
It is merged now 

@bors try

2020-02-11 18:15 UTC, rust-highfive commented
The job `dist-x86_64-linux-alt` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=20728&view=logs&jobId=396dc680-0b3a-5910-2395-0c692e01f85b) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/20728/logs/55), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/20728/logs/55)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-02-11T18:14:42.6122796Z ##                                                                         3.8%
2020-02-11T18:14:42.6123013Z ######################################################################## 100.0%
2020-02-11T18:14:42.8811340Z extracting /checkout/obj/build/cache/2020-01-31/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.gz
2020-02-11T18:14:42.9982740Z     Updating crates.io index
2020-02-11T18:14:56.4386448Z error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
2020-02-11T18:14:56.4387582Z If you want to try to generate the lock file without accessing the network, use the --offline flag.
2020-02-11T18:14:56.4426687Z Build completed unsuccessfully in 0:00:25
2020-02-11T18:14:56.4470248Z make: *** [prepare] Error 1
2020-02-11T18:14:57.4494256Z Command failed. Attempt 2/5:
2020-02-11T18:14:57.5785632Z     Updating crates.io index
2020-02-11T18:14:57.5785632Z     Updating crates.io index
2020-02-11T18:14:57.9634967Z error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
2020-02-11T18:14:57.9636070Z If you want to try to generate the lock file without accessing the network, use the --offline flag.
2020-02-11T18:14:57.9676797Z Build completed unsuccessfully in 0:00:00
2020-02-11T18:14:57.9704223Z make: *** [prepare] Error 1
2020-02-11T18:14:59.9736804Z Command failed. Attempt 3/5:
2020-02-11T18:15:00.0976767Z     Updating crates.io index
2020-02-11T18:15:00.0976767Z     Updating crates.io index
2020-02-11T18:15:00.5174322Z error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
2020-02-11T18:15:00.5175417Z If you want to try to generate the lock file without accessing the network, use the --offline flag.
2020-02-11T18:15:00.5200634Z Build completed unsuccessfully in 0:00:00
2020-02-11T18:15:00.5249202Z make: *** [prepare] Error 1
2020-02-11T18:15:03.5273002Z Command failed. Attempt 4/5:
2020-02-11T18:15:03.6632426Z     Updating crates.io index
2020-02-11T18:15:03.6632426Z     Updating crates.io index
2020-02-11T18:15:04.0079251Z error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
2020-02-11T18:15:04.0080205Z If you want to try to generate the lock file without accessing the network, use the --offline flag.
2020-02-11T18:15:04.0109249Z Build completed unsuccessfully in 0:00:00
2020-02-11T18:15:04.0156953Z make: *** [prepare] Error 1
2020-02-11T18:15:08.0173361Z Command failed. Attempt 5/5:
2020-02-11T18:15:08.1367501Z     Updating crates.io index
2020-02-11T18:15:08.1367501Z     Updating crates.io index
2020-02-11T18:15:08.6703026Z error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
2020-02-11T18:15:08.6704337Z If you want to try to generate the lock file without accessing the network, use the --offline flag.
2020-02-11T18:15:08.6730868Z Build completed unsuccessfully in 0:00:00
2020-02-11T18:15:08.6788130Z make: *** [prepare] Error 1
2020-02-11T18:15:08.6790961Z The command has failed after 5 attempts.
2020-02-11T18:15:08.6791289Z == clock drift check ==
2020-02-11T18:15:08.6791289Z == clock drift check ==
2020-02-11T18:15:08.6809650Z   local time: Tue Feb 11 18:15:08 UTC 2020
2020-02-11T18:15:09.1406256Z   network time: Tue, 11 Feb 2020 18:15:09 GMT
2020-02-11T18:15:09.1408300Z == end clock drift check ==
2020-02-11T18:15:13.9133608Z 
2020-02-11T18:15:13.9213510Z ##[error]Bash exited with code '1'.
2020-02-11T18:15:13.9248569Z ##[section]Starting: Checkout rust-lang/rust@try to s
2020-02-11T18:15:13.9250221Z ==============================================================================
2020-02-11T18:15:13.9250324Z Task         : Get sources
2020-02-11T18:15:13.9250403Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2020-02-11 19:39 UTC, dtolnay requested changes
Failure seems legit.

```console
error: the lock file /checkout/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, use the --offline flag.
Build completed unsuccessfully in 0:00:25
make: *** [prepare] Error 1
```

Needs a Cargo.lock update.

2020-02-11 21:02 UTC, dtolnay commented
@bors r+

2020-02-11 22:08 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=20744&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/20744/logs/70), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/20744/logs/70)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-02-11T20:52:11.3332551Z ========================== Starting Command Output ===========================
2020-02-11T20:52:11.3333965Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/56c1d556-4b87-4683-83dc-87ac2340e74e.sh
2020-02-11T20:52:11.3333994Z 
2020-02-11T20:52:11.3337115Z ##[section]Finishing: Disable git automatic line ending conversion
2020-02-11T20:52:11.3343235Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/69042/merge to s
2020-02-11T20:52:11.3345004Z Task         : Get sources
2020-02-11T20:52:11.3345078Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-02-11T20:52:11.3345104Z Version      : 1.0.0
2020-02-11T20:52:11.3345130Z Author       : Microsoft
---
2020-02-11T20:52:12.3364752Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-02-11T20:52:12.3376630Z ##[command]git config gc.auto 0
2020-02-11T20:52:12.3398550Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-02-11T20:52:12.3400703Z ##[command]git config --get-all http.proxy
2020-02-11T20:52:12.3407862Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/69042/merge:refs/remotes/pull/69042/merge
---
2020-02-11T21:55:41.1506357Z .................................................................................................... 1700/9627
2020-02-11T21:55:46.7117410Z .................................................................................................... 1800/9627
2020-02-11T21:55:59.8541497Z ..............................i..................................................................... 1900/9627
2020-02-11T21:56:08.4463723Z .................................................................................................... 2000/9627
2020-02-11T21:56:24.4820143Z ....................iiiii........................................................................... 2100/9627
2020-02-11T21:56:35.2613634Z .................................................................................................... 2300/9627
2020-02-11T21:56:37.9362569Z .................................................................................................... 2400/9627
2020-02-11T21:56:43.1475242Z .................................................................................................... 2500/9627
2020-02-11T21:57:05.8590952Z .................................................................................................... 2600/9627
---
2020-02-11T22:00:00.3112577Z .......................................................................i...............i............ 4900/9627
2020-02-11T22:00:08.9156464Z .................................................................................................... 5000/9627
2020-02-11T22:00:17.7023619Z .................................................................................................... 5100/9627
2020-02-11T22:00:22.8196277Z .............i...................................................................................... 5200/9627
2020-02-11T22:00:35.2020610Z .......................................................................................ii.ii........ 5300/9627
2020-02-11T22:00:39.4880130Z i...i............................................................................................... 5400/9627
2020-02-11T22:00:52.7123330Z .................................................................................................... 5600/9627
2020-02-11T22:01:01.7306211Z ...........................................................................i........................ 5700/9627
2020-02-11T22:01:09.8458338Z .................................................................................................... 5800/9627
2020-02-11T22:01:16.9125331Z .................................................................................................... 5900/9627
2020-02-11T22:01:16.9125331Z .................................................................................................... 5900/9627
2020-02-11T22:01:28.1918301Z ...................................................................ii...i..ii...........i........... 6000/9627
2020-02-11T22:01:52.3031275Z .................................................................................................... 6200/9627
2020-02-11T22:02:00.8293031Z .................................................................................................... 6300/9627
2020-02-11T22:02:09.7821646Z ...............................................................................................i..ii 6400/9627
2020-02-11T22:02:28.8739352Z .................................................................................................... 6500/9627
---
2020-02-11T22:04:45.2960967Z .................................................................................................... 7600/9627
2020-02-11T22:04:50.0706888Z .................................................................................................... 7700/9627
2020-02-11T22:04:56.5788851Z .................................................................................................... 7800/9627
2020-02-11T22:05:05.9952018Z .................................................................................................... 7900/9627
2020-02-11T22:05:16.0686129Z .....................................................................iiiiiii.i...................... 8000/9627
2020-02-11T22:05:33.9881312Z .........i......i................................................................................... 8200/9627
2020-02-11T22:05:40.0638105Z .................................................................................................... 8300/9627
2020-02-11T22:05:54.9802114Z ..................................F................................................................. 8400/9627
2020-02-11T22:06:05.5975243Z .................................................................................................... 8500/9627
---
2020-02-11T22:08:15.7037880Z 
2020-02-11T22:08:15.7038255Z ------------------------------------------
2020-02-11T22:08:15.7038456Z stderr:
2020-02-11T22:08:15.7038826Z ------------------------------------------
2020-02-11T22:08:15.7039342Z thread 'main' panicked at 'bad output: thread 'main' panicked at 'explicit panic', /checkout/src/test/ui/backtrace.rs:18:9
2020-02-11T22:08:15.7039567Z    0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
2020-02-11T22:08:15.7039875Z    2: std::io::Write::write_fmt
2020-02-11T22:08:15.7040041Z    3: std::panicking::default_hook::{{closure}}
2020-02-11T22:08:15.7040188Z    4: std::panicking::default_hook
2020-02-11T22:08:15.7040336Z    5: std::panicking::rust_panic_with_hook
---
2020-02-11T22:08:15.7042197Z   12: std::rt::lang_start_internal
2020-02-11T22:08:15.7042363Z   13: main
2020-02-11T22:08:15.7042497Z   14: __libc_start_main
2020-02-11T22:08:15.7042631Z   15: _start
2020-02-11T22:08:15.7042796Z note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2020-02-11T22:08:15.7043174Z ', /checkout/src/test/ui/backtrace.rs:68:5
2020-02-11T22:08:15.7043517Z 
2020-02-11T22:08:15.7044078Z ---------- [...]

2020-02-12 00:59 UTC, yaahc commented
the ui tests for backtraces were failing so I decided to fix them in two ways

- Add back `stack backtrace\n` output for backtraces from panics
- Add `stack backtrace\n` to the print before rendering the std backtrace in std backtrace's ui test

2020-02-12 00:59 UTC, dtolnay commented
@bors r+

2020-02-12 19:32 UTC, merged