clean up E0308 explanation
rust-lang/rust pull request #69139
Opened 2020-02-13 17:42 UTC by GuillaumeGomez

r? @Dylan-DPC

2020-02-13 18:59 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=20911&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/20911/logs/70), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/20911/logs/70)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-02-13T17:42:51.4842231Z ========================== Starting Command Output ===========================
2020-02-13T17:42:51.4845618Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/3093e74e-b0c2-45c5-899b-8352e16c1c64.sh
2020-02-13T17:42:51.4845821Z 
2020-02-13T17:42:51.4888197Z ##[section]Finishing: Disable git automatic line ending conversion
2020-02-13T17:42:51.4895248Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/69139/merge to s
2020-02-13T17:42:51.4897645Z Task         : Get sources
2020-02-13T17:42:51.4897685Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-02-13T17:42:51.4897718Z Version      : 1.0.0
2020-02-13T17:42:51.4897750Z Author       : Microsoft
---
2020-02-13T17:42:52.5264533Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-02-13T17:42:52.5275645Z ##[command]git config gc.auto 0
2020-02-13T17:42:52.5278406Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-02-13T17:42:52.5280348Z ##[command]git config --get-all http.proxy
2020-02-13T17:42:52.5287112Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/69139/merge:refs/remotes/pull/69139/merge
---
2020-02-13T18:46:10.2756261Z .................................................................................................... 1700/9636
2020-02-13T18:46:15.6995860Z .................................................................................................... 1800/9636
2020-02-13T18:46:28.5123586Z ..............................i..................................................................... 1900/9636
2020-02-13T18:46:36.7895901Z .................................................................................................... 2000/9636
2020-02-13T18:46:52.4723668Z ....................iiiii........................................................................... 2100/9636
2020-02-13T18:47:03.2498895Z .................................................................................................... 2300/9636
2020-02-13T18:47:05.9162502Z .................................................................................................... 2400/9636
2020-02-13T18:47:11.1886454Z .................................................................................................... 2500/9636
2020-02-13T18:47:33.8945029Z .................................................................................................... 2600/9636
---
2020-02-13T18:50:23.5069223Z ........................................................................i...............i........... 4900/9636
2020-02-13T18:50:31.8905078Z .................................................................................................... 5000/9636
2020-02-13T18:50:40.7954259Z .................................................................................................... 5100/9636
2020-02-13T18:50:45.8682231Z ..............i..................................................................................... 5200/9636
2020-02-13T18:50:57.9270099Z ........................................................................................ii.ii....... 5300/9636
2020-02-13T18:51:02.2287006Z .i...i.F..F......................................................................................... 5400/9636
2020-02-13T18:51:13.3859896Z .................................................................................................... 5600/9636
2020-02-13T18:51:24.2253711Z .............................................................................i...................... 5700/9636
2020-02-13T18:51:32.3716217Z .................................................................................................... 5800/9636
2020-02-13T18:51:39.0802908Z ...........................................................................i........................ 5900/9636
2020-02-13T18:51:39.0802908Z ...........................................................................i........................ 5900/9636
2020-02-13T18:51:49.4222784Z .....................................................................ii...i..ii...........i......... 6000/9636
2020-02-13T18:52:12.1708892Z .................................................................................................... 6200/9636
2020-02-13T18:52:20.1734990Z .................................................................................................... 6300/9636
2020-02-13T18:52:28.8403943Z .................................................................................................i.. 6400/9636
2020-02-13T18:52:28.8403943Z .................................................................................................i.. 6400/9636
2020-02-13T18:52:51.3523569Z ii.................................................test [ui] ui/mpsc_stress.rs has been running for over 60 seconds
2020-02-13T18:53:04.0391405Z .................................................................................................... 6600/9636
2020-02-13T18:53:15.2562320Z ....................................................................................i............... 6700/9636
2020-02-13T18:53:17.6110208Z .................................................................................................... 6800/9636
2020-02-13T18:53:19.9790850Z .............................................................................................i...... 6900/9636
---
2020-02-13T18:55:09.0903520Z .................................................................................................... 7600/9636
2020-02-13T18:55:13.8896182Z .................................................................................................... 7700/9636
2020-02-13T18:55:20.4405655Z .................................................................................................... 7800/9636
2020-02-13T18:55:29.0404499Z .................................................................................................... 7900/9636
2020-02-13T18:55:38.5572252Z ...........................................................................iiiiiii.i................ 8000/9636
2020-02-13T18:55:56.0107844Z ...............i......i............................................................................. 8200/9636
2020-02-13T18:56:01.9715529Z .................................................................................................... 8300/9636
2020-02-13T18:56:16.1788873Z .................................................................................................... 8400/9636
2020-02-13T18:56:26.7286810Z .................................................................................................... 8500/9636
---
2020-02-13T18:58:36.0551917Z - variable. It can occur for several cases, the most common of which is a
2020-02-13T18:58:36.0552403Z - mismatch in the expected type that the compiler inferred for a variable's
2020-02-13T18:58:36.0552845Z - initializing expression, and the actual type explicitly assigned to the
2020-02-13T18:58:36.0553239Z - variable.
2020-02-13T18:58:36.0553747Z + {"message":"mismatched types","code":{"code":"E0308","explanation":"Expected type didn't match the received type.
2020-02-13T18 [...]

2020-02-13 20:03 UTC, Dylan-DPC-zz requested changes

2020-02-14 16:44 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=20970&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/20970/logs/70), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/20970/logs/70)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-02-14T15:35:30.2657848Z ========================== Starting Command Output ===========================
2020-02-14T15:35:30.2659099Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/ffa19e80-30a6-4fd7-8946-45cb1f14f84b.sh
2020-02-14T15:35:30.2659139Z 
2020-02-14T15:35:30.2662154Z ##[section]Finishing: Disable git automatic line ending conversion
2020-02-14T15:35:30.2668362Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/69139/merge to s
2020-02-14T15:35:30.2670188Z Task         : Get sources
2020-02-14T15:35:30.2670218Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-02-14T15:35:30.2670245Z Version      : 1.0.0
2020-02-14T15:35:30.2670271Z Author       : Microsoft
---
2020-02-14T15:35:31.2623975Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-02-14T15:35:31.2635194Z ##[command]git config gc.auto 0
2020-02-14T15:35:31.2639084Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-02-14T15:35:31.2642874Z ##[command]git config --get-all http.proxy
2020-02-14T15:35:31.2650621Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/69139/merge:refs/remotes/pull/69139/merge
---
2020-02-14T16:33:22.3670250Z .................................................................................................... 1700/9637
2020-02-14T16:33:27.0633876Z .................................................................................................... 1800/9637
2020-02-14T16:33:38.6505640Z ..............................i..................................................................... 1900/9637
2020-02-14T16:33:46.0232993Z .................................................................................................... 2000/9637
2020-02-14T16:33:59.5867216Z ....................iiiii........................................................................... 2100/9637
2020-02-14T16:34:08.9916875Z .................................................................................................... 2300/9637
2020-02-14T16:34:11.2512036Z .................................................................................................... 2400/9637
2020-02-14T16:34:15.7438349Z .................................................................................................... 2500/9637
2020-02-14T16:34:35.3749948Z .................................................................................................... 2600/9637
---
2020-02-14T16:37:02.3248398Z ........................................................................i...............i........... 4900/9637
2020-02-14T16:37:10.1509986Z .................................................................................................... 5000/9637
2020-02-14T16:37:17.4060314Z .................................................................................................... 5100/9637
2020-02-14T16:37:22.4631266Z ..............i..................................................................................... 5200/9637
2020-02-14T16:37:32.7583076Z ........................................................................................ii.ii....... 5300/9637
2020-02-14T16:37:36.6996133Z .i...i.F...F........................................................................................ 5400/9637
2020-02-14T16:37:46.4979552Z .................................................................................................... 5600/9637
2020-02-14T16:37:56.1034986Z .............................................................................i...................... 5700/9637
2020-02-14T16:38:03.3839342Z .................................................................................................... 5800/9637
2020-02-14T16:38:09.2062242Z ...........................................................................i........................ 5900/9637
2020-02-14T16:38:09.2062242Z ...........................................................................i........................ 5900/9637
2020-02-14T16:38:18.3342771Z .....................................................................ii...i..ii...........i......... 6000/9637
2020-02-14T16:38:38.5741676Z .................................................................................................... 6200/9637
2020-02-14T16:38:45.7321409Z .................................................................................................... 6300/9637
2020-02-14T16:38:52.1656953Z .................................................................................................i.. 6400/9637
2020-02-14T16:39:04.9418762Z ii.................................................................................................. 6500/9637
---
2020-02-14T16:41:02.1368139Z .................................................................................................... 7600/9637
2020-02-14T16:41:06.1777271Z .................................................................................................... 7700/9637
2020-02-14T16:41:11.9249143Z .................................................................................................... 7800/9637
2020-02-14T16:41:19.4533336Z .................................................................................................... 7900/9637
2020-02-14T16:41:28.2459443Z ............................................................................iiiiiii.i............... 8000/9637
2020-02-14T16:41:44.4854664Z ................i......i............................................................................ 8200/9637
2020-02-14T16:41:50.0755799Z .................................................................................................... 8300/9637
2020-02-14T16:42:02.4983628Z .................................................................................................... 8400/9637
2020-02-14T16:42:11.7940264Z .................................................................................................... 8500/9637
---
2020-02-14T16:44:13.4486101Z - variable. It can occur for several cases, the most common of which is a
2020-02-14T16:44:13.4487759Z - mismatch in the expected type that the compiler inferred for a variable's
2020-02-14T16:44:13.4488742Z - initializing expression, and the actual type explicitly assigned to the
2020-02-14T16:44:13.4489364Z - variable.
2020-02-14T16:44:13.4489842Z + {"message":"mismatched types","code":{"code":"E0308","explanation":"Expected type did not match the received type.
2020-02-14T16:44:13.4490690Z - For example:
2020-02-14T16:44:13.4490991Z + Erroneous code example:
2020-02-14T16:44:13.4491203Z 8 
2020-02-14T16:44:13.4491410Z 9 ```compile_fail,E0308
2020-02-14T16:44:13.4491410Z 9 ```compile_fail,E0308
2020-02-14T16:44:13.4491664Z 10 let x: i32 = \"I am not a number!\";
2020-02-14T16:44:13.4492061Z 15 //      |
2020-02-14T16:44:13.4492294Z 16 //    type `i32` assigned to variable `x`
2020-02-14T16:44:13.4492511Z 17 ```
2020-02-14T16:44:13.4492511Z 17 ```
2020-02-14T16:44:13.4494464Z - "},"level":"error","spans":[{"file_name":"$DIR/json-bom-plus-crlf-multifile-aux.rs","byte_start":621,"byte_end":622,"line_start":17,"line_end":17,"column_start":22,"column_end":23,"is_primary" [...]

2020-02-21 23:48 UTC, JohnTitor commented
Ping from triage: @GuillaumeGomez You need to bless tests :)

2020-02-22 13:20 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=21534&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/21534/logs/71), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/21534/logs/71)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-02-22T12:15:59.5140091Z ========================== Starting Command Output ===========================
2020-02-22T12:15:59.5156503Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/f62f89ae-9428-4e00-b644-a3da2a27138f.sh
2020-02-22T12:15:59.7559924Z 
2020-02-22T12:15:59.7621314Z ##[section]Finishing: Disable git automatic line ending conversion
2020-02-22T12:15:59.7656639Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/69139/merge to s
2020-02-22T12:15:59.7701757Z Task         : Get sources
2020-02-22T12:15:59.7702235Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-02-22T12:15:59.7702972Z Version      : 1.0.0
2020-02-22T12:15:59.7703264Z Author       : Microsoft
---
2020-02-22T12:16:02.1154491Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-02-22T12:16:02.1328204Z ##[command]git config gc.auto 0
2020-02-22T12:16:02.1359986Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-02-22T12:16:02.1396683Z ##[command]git config --get-all http.proxy
2020-02-22T12:16:02.1493158Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/69139/merge:refs/remotes/pull/69139/merge
---
2020-02-22T13:10:02.8630198Z .................................................................................................... 1700/9695
2020-02-22T13:10:06.5390480Z .................................................................................................... 1800/9695
2020-02-22T13:10:15.9029155Z ..........................................i......................................................... 1900/9695
2020-02-22T13:10:22.4518745Z .................................................................................................... 2000/9695
2020-02-22T13:10:34.0713616Z ................................iiii.i.............................................................. 2100/9695
2020-02-22T13:10:42.0128293Z .................................................................................................... 2300/9695
2020-02-22T13:10:43.9246363Z .................................................................................................... 2400/9695
2020-02-22T13:10:47.4830098Z .................................................................................................... 2500/9695
2020-02-22T13:11:04.3697083Z .................................................................................................... 2600/9695
---
2020-02-22T13:13:23.5218279Z ........i........................................................................................... 5000/9695
2020-02-22T13:13:32.0064654Z .................................................................................................... 5100/9695
2020-02-22T13:13:36.2391783Z ...................................i................................................................ 5200/9695
2020-02-22T13:13:45.5703662Z .................................................................................................... 5300/9695
2020-02-22T13:13:51.4253471Z ...........ii.ii........i...iF...F.................................................................. 5400/9695
2020-02-22T13:13:59.7550924Z .................................................................................................... 5600/9695
2020-02-22T13:14:10.0699630Z .................................................................................................... 5700/9695
2020-02-22T13:14:17.1441488Z ..i................................................................................................. 5800/9695
2020-02-22T13:14:22.3982919Z .................................................................................................... 5900/9695
2020-02-22T13:14:22.3982919Z .................................................................................................... 5900/9695
2020-02-22T13:14:31.6849157Z .............................................................................................ii...i. 6000/9695
2020-02-22T13:14:42.9085155Z .ii...........i..................................................................................... 6100/9695
2020-02-22T13:14:58.7999540Z .................................................................................................... 6300/9695
2020-02-22T13:15:05.2644185Z .................................................................................................... 6400/9695
2020-02-22T13:15:05.2644185Z .................................................................................................... 6400/9695
2020-02-22T13:15:19.9250819Z ........................i..ii....................................................................... 6500/9695
2020-02-22T13:15:39.1525171Z .................................................................................................... 6700/9695
2020-02-22T13:15:41.2904643Z ................i................................................................................... 6800/9695
2020-02-22T13:15:43.3654213Z .................................................................................................... 6900/9695
2020-02-22T13:15:45.6503438Z ......................................i............................................................. 7000/9695
---
2020-02-22T13:17:19.4401600Z .................................................................................................... 7700/9695
2020-02-22T13:17:24.1923334Z .................................................................................................... 7800/9695
2020-02-22T13:17:30.0382455Z ..................................................................................i................. 7900/9695
2020-02-22T13:17:38.4127423Z .................................................................................................... 8000/9695
2020-02-22T13:17:44.8044997Z ...............................iiiiiii.i............................................................ 8100/9695
2020-02-22T13:17:58.1809634Z .................................................................................................... 8300/9695
2020-02-22T13:18:06.2687786Z .................................................................................................... 8400/9695
2020-02-22T13:18:18.6058858Z .................................................................................................... 8500/9695
2020-02-22T13:18:24.9316083Z .................................................................................................... 8600/9695
---
2020-02-22T13:20:11.1200965Z - variable. It can occur for several cases, the most common of which is a
2020-02-22T13:20:11.1201441Z - mismatch in the expected type that the compiler inferred for a variable's
2020-02-22T13:20:11.1202078Z - initializing expression, and the actual type explicitly assigned to the
2020-02-22T13:20:11.1202418Z - variable.
2020-02-22T13:20:11.1202721Z + {"message":"mismatched types","code":{"code":"E0308","explanation":"Expected type did not match the received type.
2020-02-22T13:20:11.1203392Z - For example:
2020-02-22T13:20:11.1203535Z + Erroneous code example:
2020-02-22T13:20:11.1203673Z 8 
2020-02-22T13:20:11.120381 [...]

2020-03-07 17:57 UTC, JohnTitor commented
@GuillaumeGomez Two tests ([json-bom-plus-crlf.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui/json-bom-plus-crlf.stderr) and [json-bom-plus-crlf-multifile.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui/json-bom-plus-crlf-multifile.stderr)) contain E0308 explanation as json, like:

https://github.com/rust-lang/rust/blob/823ff8cf1397a5772b1f6954b60576202bf91836/src/test/ui/json-bom-plus-crlf.stderr#L1-L17

So you should also update these stderrs.

2020-03-17 20:26 UTC, Dylan-DPC commented
@bors r+ rollup

2020-03-19 03:34 UTC, merged