Updates links in various Compiler Error Index entries
rust-lang/rust pull request #69372
Opened 2020-02-22 11:55 UTC by yawpitch

Currently many of the links in the online https://doc.rust-lang.org/error-index.html are not clickable, and many of them don't resolve correctly as they point to older versions of rustbyexample and the reference.

2020-02-22 11:55 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @varkor (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2020-02-22 12:16 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=21531&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/21531/logs/67), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/21531/logs/67)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-02-22T11:55:46.8239993Z ========================== Starting Command Output ===========================
2020-02-22T11:55:46.8244765Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/89ce69e5-f1f9-4faa-b75d-e875c813694f.sh
2020-02-22T11:55:46.8245289Z 
2020-02-22T11:55:46.8250165Z ##[section]Finishing: Disable git automatic line ending conversion
2020-02-22T11:55:46.8272236Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/69372/merge to s
2020-02-22T11:55:46.8276413Z Task         : Get sources
2020-02-22T11:55:46.8276645Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-02-22T11:55:46.8276924Z Version      : 1.0.0
2020-02-22T11:55:46.8277076Z Author       : Microsoft
---
2020-02-22T11:55:49.4501304Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-02-22T11:55:49.4650113Z ##[command]git config gc.auto 0
2020-02-22T11:55:49.4692230Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-02-22T11:55:49.4732383Z ##[command]git config --get-all http.proxy
2020-02-22T11:55:49.4828837Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/69372/merge:refs/remotes/pull/69372/merge
---
2020-02-22T12:02:58.5557131Z    Compiling serde_json v1.0.40
2020-02-22T12:03:00.1652037Z    Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
2020-02-22T12:03:10.3002607Z     Finished release [optimized] target(s) in 1m 29s
2020-02-22T12:03:10.3092777Z tidy check
2020-02-22T12:03:10.5243979Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0364.md:29: trailing whitespace
2020-02-22T12:03:10.5250790Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0364.md:32: line longer than 80 chars
2020-02-22T12:03:10.5251314Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0303.md: too many trailing newlines (2)
2020-02-22T12:03:10.5251857Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0601.md:11: trailing whitespace
2020-02-22T12:03:10.5259306Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0535.md:30: line longer than 80 chars
2020-02-22T12:03:10.5259827Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0382.md:107: trailing whitespace
2020-02-22T12:03:10.5260348Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0382.md:110: line longer than 80 chars
2020-02-22T12:03:10.5277780Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0503.md:51: trailing whitespace
2020-02-22T12:03:10.5278312Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0503.md:54: line longer than 80 chars
2020-02-22T12:03:10.5278802Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0507.md:130: trailing whitespace
2020-02-22T12:03:10.5279295Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0507.md:133: line longer than 80 chars
2020-02-22T12:03:10.5286908Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0502.md:28: trailing whitespace
2020-02-22T12:03:10.5287414Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0502.md:31: line longer than 80 chars
2020-02-22T12:03:10.5299592Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0455.md:21: line longer than 80 chars
2020-02-22T12:03:10.5306298Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0154.md:30: trailing whitespace
2020-02-22T12:03:10.5306989Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0154.md:31: trailing whitespace
2020-02-22T12:03:10.5307539Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0154.md:34: line longer than 80 chars
2020-02-22T12:03:10.5311000Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0505.md:84: trailing whitespace
2020-02-22T12:03:10.5311501Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0505.md:87: line longer than 80 chars
2020-02-22T12:03:10.5312196Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0080.md:22: line longer than 80 chars
2020-02-22T12:03:10.5312710Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0080.md:23: line longer than 80 chars
2020-02-22T12:03:10.5313318Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0260.md:31: trailing whitespace
2020-02-22T12:03:10.5317660Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0260.md:32: trailing whitespace
2020-02-22T12:03:10.5318158Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0260.md:35: line longer than 80 chars
2020-02-22T12:03:10.5318644Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0661.md:10: trailing whitespace
2020-02-22T12:03:10.5319138Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0662.md:12: trailing whitespace
2020-02-22T12:03:10.5322667Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0499.md:17: line longer than 80 chars
2020-02-22T12:03:10.5323227Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0663.md:12: trailing whitespace
2020-02-22T12:03:10.5323744Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0534.md:37: line longer than 80 chars
2020-02-22T12:03:10.5329888Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0525.md:39: trailing whitespace
2020-02-22T12:03:10.5336636Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0660.md:9: trailing whitespace
2020-02-22T12:03:10.5337119Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0501.md:9: line longer than 80 chars
2020-02-22T12:03:10.5352812Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0365.md:29: trailing whitespace
2020-02-22T12:03:10.5353330Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0365.md:32: line longer than 80 chars
2020-02-22T12:03:10.5358460Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0536.md:21: trailing whitespace
2020-02-22T12:03:10.5358988Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0536.md:24: line longer than 80 chars
2020-02-22T12:03:10.5359525Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0537.md:27: trailing whitespace
2020-02-22T12:03:10.5360014Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0537.md:30: line longer than 80 chars
2020-02-22T12:03:10.5363634Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0664.md:13: trailing whitespace
2020-02-22T12:03:12.9789555Z Found 487 error codes
2020-02-22T12:03:12.9789848Z Found 0 error codes with no tests
2020-02-22T12:03:12.9790084Z Done!
2020-02-22T12:03:12.9790257Z some tidy checks failed
2020-02-22T12:03:12.9790257Z some tidy checks failed
2020-02-22T12:03:12.9790405Z 
2020-02-22T12:03:12.9790508Z 
2020-02-22T12:03:12.9791866Z command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor"
2020-02-22T12:03:12.9792661Z 
2020-02-22T12:03:12.9792812Z 
2020-02-22T12:03:12.9797244Z failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
2020-02-22T12:03:12.9797987Z Build completed unsuccessfully in 0:01:39
2020-02-22T12:03:12.9797987Z Build completed unsuccessfully in 0:01:39
2020-02-22T12:03:12.9843607Z  [...]

2020-02-22 14:34 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=21539&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/21539/logs/71), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/21539/logs/71)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-02-22T13:18:11.9892491Z ========================== Starting Command Output ===========================
2020-02-22T13:18:11.9895406Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/825810b8-2e44-4289-824a-e3ed6dc86f0b.sh
2020-02-22T13:18:11.9895694Z 
2020-02-22T13:18:11.9899384Z ##[section]Finishing: Disable git automatic line ending conversion
2020-02-22T13:18:11.9919349Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/69372/merge to s
2020-02-22T13:18:11.9922837Z Task         : Get sources
2020-02-22T13:18:11.9923161Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-02-22T13:18:11.9923490Z Version      : 1.0.0
2020-02-22T13:18:11.9923702Z Author       : Microsoft
---
2020-02-22T13:18:13.1748510Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-02-22T13:18:13.1759159Z ##[command]git config gc.auto 0
2020-02-22T13:18:13.1767707Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-02-22T13:18:13.1771887Z ##[command]git config --get-all http.proxy
2020-02-22T13:18:13.1781614Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/69372/merge:refs/remotes/pull/69372/merge
---
2020-02-22T14:23:09.8496138Z .................................................................................................... 1700/9695
2020-02-22T14:23:14.3065167Z .................................................................................................... 1800/9695
2020-02-22T14:23:25.6704456Z ..........................................i......................................................... 1900/9695
2020-02-22T14:23:33.3243533Z .................................................................................................... 2000/9695
2020-02-22T14:23:47.2629733Z ................................iiiii............................................................... 2100/9695
2020-02-22T14:23:57.2228919Z .................................................................................................... 2300/9695
2020-02-22T14:23:59.6672932Z .................................................................................................... 2400/9695
2020-02-22T14:24:04.0600730Z .................................................................................................... 2500/9695
2020-02-22T14:24:24.9146622Z .................................................................................................... 2600/9695
---
2020-02-22T14:27:08.7230531Z ........i........................................................................................... 5000/9695
2020-02-22T14:27:17.2912757Z .................................................................................................... 5100/9695
2020-02-22T14:27:22.3260669Z ...................................i................................................................ 5200/9695
2020-02-22T14:27:32.7468387Z .................................................................................................... 5300/9695
2020-02-22T14:27:38.8160722Z ...........ii.ii........i...i......F................................................................ 5400/9695
2020-02-22T14:27:47.8423971Z .................................................................................................... 5600/9695
2020-02-22T14:27:58.9113749Z .................................................................................................... 5700/9695
2020-02-22T14:28:06.3766478Z ..i................................................................................................. 5800/9695
2020-02-22T14:28:12.0670838Z .................................................................................................... 5900/9695
2020-02-22T14:28:12.0670838Z .................................................................................................... 5900/9695
2020-02-22T14:28:21.9809807Z .............................................................................................ii...i. 6000/9695
2020-02-22T14:28:33.7904771Z .ii...........i..................................................................................... 6100/9695
2020-02-22T14:28:50.5450226Z .................................................................................................... 6300/9695
2020-02-22T14:28:57.1700390Z .................................................................................................... 6400/9695
2020-02-22T14:28:57.1700390Z .................................................................................................... 6400/9695
2020-02-22T14:29:12.6381424Z ........................i..ii....................................................................... 6500/9695
2020-02-22T14:29:33.7540945Z .................................................................................................... 6700/9695
2020-02-22T14:29:36.1594832Z ................i................................................................................... 6800/9695
2020-02-22T14:29:38.5948264Z .................................................................................................... 6900/9695
2020-02-22T14:29:41.2835835Z ......................................i............................................................. 7000/9695
---
2020-02-22T14:31:24.2557285Z .................................................................................................... 7700/9695
2020-02-22T14:31:29.5723263Z .................................................................................................... 7800/9695
2020-02-22T14:31:36.1655430Z ...................................................................................i................ 7900/9695
2020-02-22T14:31:45.5207716Z .................................................................................................... 8000/9695
2020-02-22T14:31:52.6957100Z ...............................iiiiiii.i............................................................ 8100/9695
2020-02-22T14:32:07.7679859Z .................................................................................................... 8300/9695
2020-02-22T14:32:16.8494554Z .................................................................................................... 8400/9695
2020-02-22T14:32:30.8055546Z .................................................................................................... 8500/9695
2020-02-22T14:32:37.8308922Z .................................................................................................... 8600/9695
---
2020-02-22T14:34:33.7100789Z 
2020-02-22T14:34:33.7101187Z 8 }
2020-02-22T14:34:33.7101595Z 9 ```
2020-02-22T14:34:33.7101984Z 10 
2020-02-22T14:34:33.7102865Z - If you don't know the basics of Rust, you can go look to the Rust Book to get
2020-02-22T14:34:33.7105083Z - started: https://doc.rust-lang.org/book/
2020-02-22T14:34:33.7106117Z + If you don't know the basics of Rust, you can look to the
2020-02-22T14:34:33.7106896Z + [Rust Book][rust-book] to get started.
2020-02-22T14:34:33.7108447Z + [rust-book]: https://doc.rust-lang.org/book/
2020-02-22T14:34:33.7108447Z + [rust-book]: https://doc.rust-lang.org/book/
2020-02-22T14:34:33.7111518Z 13  [...]

2020-02-23 01:44 UTC, varkor requested changes
Could you please squash your commits into one? Thanks!

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0080.md
> +See the [Custom Discriminants][custom-discriminants] section the Reference for
```suggestion
See the [Custom Discriminants][custom-discriminants] section of the Reference for
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0080.md
> +more information about setting custom integer types on field-less Enums using
```suggestion
more information about setting custom integer types on fieldless enums using
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0080.md
> +more information about setting custom integer types on field-less Enums using
I see the original article has the other spelling, but I think this is the wrong choice. I've opened https://github.com/rust-lang/reference/pull/768 in the meantime.

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0080.md
> +the [repr attribute][repr-attribute].
```suggestion
the [`repr` attribute][repr-attribute].
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0154.md
> +[declaration-statements]: https://doc.rust-lang.org/reference/statements.html?highlight=statements#declaration-statements
```suggestion
[declaration-statements]: https://doc.rust-lang.org/reference/statements.html#declaration-statements
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0154.md
> +reference for more information about what constitutes an Item declaration
```suggestion
reference for more information about what constitutes an item declaration
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0260.md
> +reference for more information about what constitutes an Item declaration
```suggestion
reference for more information about what constitutes an item declaration
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0154.md
> +and what does not:
```suggestion
and what does not.
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0260.md
> +and what does not:
```suggestion
and what does not.
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0260.md
> +[declaration-statements]: https://doc.rust-lang.org/reference/statements.html?highlight=statements#declaration-statements
```suggestion
[declaration-statements]: https://doc.rust-lang.org/reference/statements.html#declaration-statements
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0364.md
> +more information on this topic:
```suggestion
more information on this topic.
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0365.md
> +more information on this topic:
```suggestion
more information on this topic.
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0502.md
> +[references & borrowing][references-and-borrowing] section of the Book.
```suggestion
[References & Borrowing][references-and-borrowing] section of the Book.
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0503.md
> +[references & borrowing][references-and-borrowing] section of the Book.
```suggestion
[References & Borrowing][references-and-borrowing] section of the Book.
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0505.md
> +[references & borrowing][references-and-borrowing] section of the Book.
```suggestion
[References & Borrowing][references-and-borrowing] section of the Book.
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0507.md
> +[references & borrowing][references-and-borrowing] section of the Book.
```suggestion
[References & Borrowing][references-and-borrowing] section of the Book.
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0534.md
> +For more information see the [Inline Attribute][inline-attribute] section
```suggestion
For more information see the [`inline` attribute][inline-attribute] section
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0535.md
> +For more information see the [Inline Attribute][inline-attribute] section
```suggestion
For more information see the [`inline` Attribute][inline-attribute] section
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0536.md
> +For more information about the cfg attribute, read the section on
```suggestion
For more information about the `cfg` attribute, read the section on
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0537.md
> +For more information about the cfg attribute, read the section on
```suggestion
For more information about the `cfg` attribute, read the section on
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0601.md
> +If you don't know the basics of Rust, you can look to the
```suggestion
If you don't know the basics of Rust, you can look at the
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0610.md
> +For more information about [primitives] and [structs], take a look at The Book.
```suggestion
For more information about [primitives] and [structs], take a look at the Book.
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0660.md
> +take a look at the [asm] chapter of the Unstable book:
```suggestion
take a look at the [`asm`] chapter of the Unstable book:
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0661.md
> +take a look at the [asm] chapter of the Unstable book:
```suggestion
take a look at the [`asm`] chapter of the Unstable book:
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0662.md
> +take a look at the [asm] chapter of the Unstable book:
```suggestion
take a look at the [`asm`] chapter of the Unstable book:
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0663.md
> +take a look at the [asm] chapter of the Unstable book:
```suggestion
take a look at the [`asm`] chapter of the Unstable book:
```

2020-02-23 01:44 UTC, varkor commented on src/librustc_error_codes/error_codes/E0664.md
> +take a look at the [asm] chapter of the Unstable book:
```suggestion
take a look at the [`asm`] chapter of the Unstable book:
```

2020-02-23 01:44 UTC, varkor commented on src/test/ui/json-short.stderr
> +If you don't know the basics of Rust, you can look to the
```suggestion
If you don't know the basics of Rust, you can look at the
```

2020-02-23 11:46 UTC, yawpitch commented
> Could you please squash your commits into one? Thanks!

All your suggestions committed and everything squashed.

2020-02-23 12:06 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=21617&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/21617/logs/67), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/21617/logs/67)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-02-23T11:45:45.2400749Z ========================== Starting Command Output ===========================
2020-02-23T11:45:45.2404025Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/1694fa09-d538-4a15-8894-db7f73615112.sh
2020-02-23T11:45:45.2404402Z 
2020-02-23T11:45:45.2408189Z ##[section]Finishing: Disable git automatic line ending conversion
2020-02-23T11:45:45.2428129Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/69372/merge to s
2020-02-23T11:45:45.2431241Z Task         : Get sources
2020-02-23T11:45:45.2431472Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-02-23T11:45:45.2431696Z Version      : 1.0.0
2020-02-23T11:45:45.2431895Z Author       : Microsoft
---
2020-02-23T11:45:46.2628391Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-02-23T11:45:46.2633731Z ##[command]git config gc.auto 0
2020-02-23T11:45:46.2637950Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-02-23T11:45:46.2641228Z ##[command]git config --get-all http.proxy
2020-02-23T11:45:46.2647800Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/69372/merge:refs/remotes/pull/69372/merge
---
2020-02-23T11:51:31.6969101Z    Compiling serde_json v1.0.40
2020-02-23T11:51:33.2800610Z    Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
2020-02-23T11:51:43.3172542Z     Finished release [optimized] target(s) in 1m 25s
2020-02-23T11:51:43.3173312Z tidy check
2020-02-23T11:51:43.3173894Z tidy error: /checkout/src/librustc_error_codes/error_codes/E0080.md:18: line longer than 80 chars
2020-02-23T11:51:44.9456834Z some tidy checks failed
2020-02-23T11:51:44.9457334Z Found 487 error codes
2020-02-23T11:51:44.9458072Z Found 0 error codes with no tests
2020-02-23T11:51:44.9458788Z Done!
2020-02-23T11:51:44.9458788Z Done!
2020-02-23T11:51:44.9458902Z 
2020-02-23T11:51:44.9461254Z 
2020-02-23T11:51:44.9463103Z command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "--no-vendor"
2020-02-23T11:51:44.9464626Z 
2020-02-23T11:51:44.9464754Z 
2020-02-23T11:51:44.9474696Z failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
2020-02-23T11:51:44.9475044Z Build completed unsuccessfully in 0:01:34
2020-02-23T11:51:44.9475044Z Build completed unsuccessfully in 0:01:34
2020-02-23T11:51:44.9523502Z == clock drift check ==
2020-02-23T11:51:44.9532258Z   local time: Sun Feb 23 11:51:44 UTC 2020
2020-02-23T11:51:45.4993264Z   network time: Sun, 23 Feb 2020 11:51:45 GMT
2020-02-23T11:51:45.4996801Z == end clock drift check ==
2020-02-23T11:51:46.3692743Z 
2020-02-23T11:51:46.3776617Z ##[error]Bash exited with code '1'.
2020-02-23T11:51:46.3789237Z ##[section]Finishing: Run build
2020-02-23T11:51:46.3838485Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/69372/merge to s
2020-02-23T11:51:46.3842703Z Task         : Get sources
2020-02-23T11:51:46.3842999Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-02-23T11:51:46.3843304Z Version      : 1.0.0
2020-02-23T11:51:46.3843495Z Author       : Microsoft
2020-02-23T11:51:46.3843495Z Author       : Microsoft
2020-02-23T11:51:46.3843796Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
2020-02-23T11:51:46.3844172Z ==============================================================================
2020-02-23T11:51:46.6991952Z Cleaning any cached credential from repository: rust-lang/rust (GitHub)
2020-02-23T11:51:46.7034519Z ##[section]Finishing: Checkout rust-lang/rust@refs/pull/69372/merge to s
2020-02-23T11:51:46.7135835Z Cleaning up task key
2020-02-23T11:51:46.7137811Z Start cleaning up orphan processes.
2020-02-23T11:51:46.7446559Z Terminate orphan process: pid (3912) (python)
2020-02-23T11:51:46.7481898Z ##[section]Finishing: Finalize Job
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2020-02-23 17:56 UTC, varkor commented
@yawpitch: thanks!

@bors r+ rollup

2020-02-24 14:54 UTC, merged