use char instead of &str for single char patterns
rust-lang/rust pull request #69481
Opened 2020-02-26 12:13 UTC by matthiaskrgr

2020-02-26 20:06 UTC, ecstatic-morse requested changes
r=me after removing unnecessary escapes.

2020-02-26 20:06 UTC, ecstatic-morse commented on src/librustc_builtin_macros/format.rs
> +        Ok(s) => (s.starts_with('\"') || s.starts_with("r#"), Some(s)),
No need to escape this.
```suggestion
        Ok(s) => (s.starts_with('"') || s.starts_with("r#"), Some(s)),
```

2020-02-26 20:06 UTC, ecstatic-morse commented on src/librustc_typeck/check/demand.rs
> +                            if src.starts_with('\"') {
Same as above.

2020-02-26 20:42 UTC, matthiaskrgr commented
diff: https://github.com/rust-lang/rust/compare/b974a814870359c5957c554be18291b71f7758f2..8ceb9096ac72bab8b5566f22645c16e84634603f

r? @ecstatic-morse

2020-02-26 20:44 UTC, ecstatic-morse approved these changes

2020-02-26 20:45 UTC, ecstatic-morse commented
@bors r+ rollup=always

2020-02-26 23:05 UTC, Dylan-DPC commented
failed in rollup 
@bors r-

2020-02-27 06:31 UTC, petrochenkov commented
https://github.com/rust-lang/rust/issues/41993 was fixed, but I still think this replacement is ideologically wrong.
All these places don't care about unicode code points, they do substring search, it's just the substring happens to be pretty short.
`char` is a pretty rare data type that shouldn't be used unless you want unicode code points specifically.

2020-02-27 09:08 UTC, matthiaskrgr commented
When running these benchmarks that I found via the discussion you linked
````rust
#![feature(test)]

extern crate test;
use crate::test::black_box;
use crate::test::Bencher;

fn main() {
    println!("Hello, world!");
}

#[bench]
fn starts_with_char(b: &mut Bencher) {
    let text = black_box("kdjsfhlakfhlsghlkvcnljknfqiunvcijqenwodind");
    b.iter(|| {
        for _ in 0..1024 {
            black_box(text.starts_with('k'));
        }
    })
}

#[bench]
fn starts_with_str(b: &mut Bencher) {
    let text = black_box("kdjsfhlakfhlsghlkvcnljknfqiunvcijqenwodind");
    b.iter(|| {
        for _ in 0..1024 {
            black_box(text.starts_with("k"));
        }
    })
}

#[bench]
fn ends_with_char(b: &mut Bencher) {
    let text = black_box("kdjsfhlakfhlsghlkvcnljknfqiunvcijqenwodind");
    b.iter(|| {
        for _ in 0..1024 {
            black_box(text.ends_with('k'));
        }
    })
}

#[bench]
fn ends_with_str(b: &mut Bencher) {
    let text = black_box("kdjsfhlakfhlsghlkvcnljknfqiunvcijqenwodind");
    b.iter(|| {
        for _ in 0..1024 {
            black_box(text.ends_with("k"));
        }
    })
}
````
, char is consistently faster for me with default optimization levels:

````
running 4 tests
test ends_with_char   ... bench:         465 ns/iter (+/- 31)
test ends_with_str    ... bench:         544 ns/iter (+/- 79)
test starts_with_char ... bench:         356 ns/iter (+/- 38)
test starts_with_str  ... bench:         691 ns/iter (+/- 10)
````

````
running 4 tests
test ends_with_char   ... bench:         464 ns/iter (+/- 10)
test ends_with_str    ... bench:         544 ns/iter (+/- 15)
test starts_with_char ... bench:         355 ns/iter (+/- 11)
test starts_with_str  ... bench:         692 ns/iter (+/- 11)
````

````
running 4 tests
test ends_with_char   ... bench:         448 ns/iter (+/- 11)
test ends_with_str    ... bench:         527 ns/iter (+/- 2)
test starts_with_char ... bench:         340 ns/iter (+/- 33)
test starts_with_str  ... bench:         670 ns/iter (+/- 8)
````

2020-02-27 10:51 UTC, petrochenkov commented
If this is a perf improvement now, rather than just a stylistic change, then it should be ok.

2020-02-27 13:57 UTC, matthiaskrgr commented
rebased

2020-02-28 11:56 UTC, matthiaskrgr commented
r? @petrochenkov or @ecstatic-morse

2020-02-28 11:57 UTC, Dylan-DPC commented
@bors r=ecstatic-morse

2020-02-28 21:14 UTC, merged