Cleanup e0374
rust-lang/rust pull request #69554
Opened 2020-02-28 15:07 UTC by GuillaumeGomez

r? @Dylan-DPC

2020-02-29 01:13 UTC, Dylan-DPC-zz requested changes

2020-02-29 01:13 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0374.md
> +An [unsized type][1] is any type that the compiler doesn't know the length or
```suggestion
An [unsized type][1] is any type where the compiler does not know the length or
```

2020-02-29 11:14 UTC, GuillaumeGomez commented
Updated!

2020-03-01 16:21 UTC, Dylan-DPC commented
@bors r+ rollup

2020-03-01 20:53 UTC, merged