Clarify explanation of Vec<T> 'fn resize'
rust-lang/rust pull request #69568
Opened 2020-02-29 00:32 UTC by JOE1994

1. Clarified on what should implement `Clone` trait.
2. Minor grammar fix:
to be able clone => to be able **to** clone

2020-02-29 00:32 UTC, rust-highfive commented
r? @JoshTriplett

(rust_highfive has picked a reviewer for you, use r? to override)

2020-02-29 00:35 UTC, jonas-schievink requested changes

2020-02-29 00:35 UTC, jonas-schievink commented on src/liballoc/vec.rs
> +    /// This method requires `value` to implement [`Clone`],
```suggestion
    /// This method requires `T` to implement [`Clone`], 
```

2020-02-29 00:51 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=22029&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/22029/logs/67), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/22029/logs/67)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-02-29T00:32:43.1266641Z ========================== Starting Command Output ===========================
2020-02-29T00:32:43.1269383Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/ff26a12e-5fce-4f96-96a2-451c7e91a7a7.sh
2020-02-29T00:32:43.1269606Z 
2020-02-29T00:32:43.1274299Z ##[section]Finishing: Disable git automatic line ending conversion
2020-02-29T00:32:43.1293375Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/69568/merge to s
2020-02-29T00:32:43.1296585Z Task         : Get sources
2020-02-29T00:32:43.1296816Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-02-29T00:32:43.1297041Z Version      : 1.0.0
2020-02-29T00:32:43.1297237Z Author       : Microsoft
---
2020-02-29T00:32:44.4032408Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-02-29T00:32:44.4038415Z ##[command]git config gc.auto 0
2020-02-29T00:32:44.4041927Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-02-29T00:32:44.4044771Z ##[command]git config --get-all http.proxy
2020-02-29T00:32:44.4050849Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/69568/merge:refs/remotes/pull/69568/merge
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@TimNN`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2020-03-01 16:17 UTC, Dylan-DPC commented
@bors r+ rollup

2020-03-01 16:17 UTC, Dylan-DPC commented
@bors r-

2020-03-01 16:18 UTC, Dylan-DPC commented
sorry, it is fine :D 

@bors r+ rollup

2020-03-01 20:53 UTC, merged