constify mem::forget
rust-lang/rust pull request #69617
Opened 2020-03-01 19:44 UTC by DutchGhost

implements https://github.com/rust-lang/rust/issues/69616

2020-03-01 19:44 UTC, rust-highfive commented
r? @LukasKalbertodt

(rust_highfive has picked a reviewer for you, use r? to override)

2020-03-02 00:27 UTC, LukasKalbertodt requested changes

2020-03-02 00:27 UTC, LukasKalbertodt commented on src/libcore/mem/mod.rs
>  pub fn forget<T>(t: T) {
You still need to add a `const` here: `pub const fn`.

2020-03-02 12:20 UTC, LukasKalbertodt commented
@bors r+ rollup

2020-03-02 16:05 UTC, merged

2020-03-02 19:02 UTC, ecstatic-morse commented
No test for this?

2020-03-02 19:37 UTC, DutchGhost commented
> 
> 
> No test for this?

Im writing them now!

2020-03-16 09:34 UTC, RalfJung commented
Constification PRs should always Cc @rust-lang/wg-const-eval

2020-03-16 10:14 UTC, LukasKalbertodt commented
@RalfJung Sorry, will do in the future!

2020-06-30 09:22 UTC, RalfJung commented
Next time someone adds a const-intrinsic, please make sure to also remove the (then obsolete) implementation in Miri once it lands.

2020-06-30 09:23 UTC, RalfJung commented
Oh wait, this does not even use the intrinsic... *oops* sorry.^^