Implement From<&mut str> for String
rust-lang/rust pull request #69661
Opened 2020-03-03 05:20 UTC by lopopolo

I ran into this missing impl when trying to do `String::from` on the result returned from this API in the `uuid` crate:

https://docs.rs/uuid/0.8.1/uuid/adapter/struct.Hyphenated.html#method.encode_lower

I wasn't sure what to put in the stability annotation. I'd appreciate some help with that :)

2020-03-03 05:20 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @shepmaster (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2020-03-04 16:03 UTC, Aaron1011 commented
I'm not sure if it's a good idea to hide an allocation behind a `From` impl. Is there a situtation where you can't just call `str.to_owned()` directly?

2020-03-04 19:06 UTC, LeSeulArtichaut commented
@Aaron1011 There already are some `From` implementations that allocate. Even `From<&str> for String`:
https://github.com/rust-lang/rust/blob/2b0cfa5b4c5099f45ca540ee1c7d8c1ecd5267d2/src/liballoc/string.rs#L2221-L2226

@lopopolo As Aaron1011 pointed out above, to avoid your current problem, you could call `.to_string()` or `to_owned()` on the `&mut str` instead of using `String::from()`, which does just the same thing.

2020-03-04 19:42 UTC, lopopolo commented
I know that `to_owned` does the same thing as the `From` impl I added in this PR (I authored the PR after all). However I _already_ use `String::from` everywhere in my codebase to turn `&str` into `String`. It seems arbitrary that I cannot do the same for `&mut str`

2020-03-04 19:53 UTC, LeSeulArtichaut commented
By the way, does any conventions exist on which one to preferably use?

2020-03-05 01:10 UTC, shepmaster commented
In general, this change makes sense to me because we *already* have the equivalent for `&str`. However, it's modifying public API, so I'm going to kick it to the libs team...

r? @cramertj

2020-03-05 02:13 UTC, Aaron1011 commented
I didn't realize that we already had `impl From<&str> for String`. I withdraw my previous concern.

2020-03-05 07:36 UTC, LeSeulArtichaut commented on src/liballoc/string.rs
> +    #[inline]
Maybe add documentation for this? Please read https://github.com/rust-lang/rust/issues/51430#issuecomment-398322434 to know what to document.

2020-03-05 12:53 UTC, tspiteri commented
While `From<&str> for String` is quite useful for, for example, `String::from("hello")`, I'm not quite sure that means there should be `From<&mut str>`; you could always use `String::from(&*str_mut)`.

Somehow equivalently, lots of arithmetic operations are implemented for `&i32` etc. such that you can add `&a + &b`, but you cannot add `&mut a + &mut b`.

2020-03-06 17:12 UTC, cramertj commented
> However, it's modifying public API, so I'm going to kick it to the libs team...
r? @cramertj

Forwarding this to a libs team member ;)

r? @sfackler

2020-03-10 10:51 UTC, Centril commented
Seems like highfive didn't listen, r? @LukasKalbertodt

2020-03-10 20:41 UTC, LukasKalbertodt requested changes
While I'm not particularly fond of adding impls like that for mutable references, I think this one is fine to add. Not only is `From<&str> for String` implemented, but more importantly, there is also this impl:

```rust
impl<'_, T: Clone> From<&'_ mut [T]> for Vec<T>
```

So I'd be fine with starting an FCP to merge this after my line comment is dealt with and you added some docs (as @LeSeulArtichaut suggested).

2020-03-10 20:41 UTC, LukasKalbertodt commented on src/liballoc/string.rs
> +#[stable(feature = "???", since = "1.43.0")]
Just chose a somewhat reasonable name, for example `from_mut_str_for_string`. I also believe you have to update the Rust version to `1.44` by now.

2020-03-11 01:49 UTC, lopopolo commented
@LukasKalbertodt thanks for the review. I've pushed some additional commits that address the feedback.

2020-03-11 07:13 UTC, LukasKalbertodt approved these changes
Great, thanks!

2020-03-11 07:13 UTC, LukasKalbertodt commented
As I said, I am in favor of this change. But I can't start FCP merges, so I have to reassign: 
r? @Amanieu

2020-03-12 00:55 UTC, sfackler commented
@rfcbot fcp merge

2020-03-15 12:43 UTC, sfackler commented
@bors r+ rollup

2020-03-15 20:40 UTC, merged