Make Point `Copy` in arithmetic documentation
rust-lang/rust pull request #69766
Opened 2020-03-06 09:43 UTC by skade

Small composite types like `Point { x: i32, y: i32}` are plain
old data and we should encourage users to derive `Copy` on them.

This changes the semantics of the edited examples slightly: instead
of consuming the operands during addition, it will copy them. This
is desired behaviour.

2020-03-06 09:43 UTC, rust-highfive commented
r? @shepmaster

(rust_highfive has picked a reviewer for you, use r? to override)

2020-03-07 19:11 UTC, shepmaster requested changes
I'd prefer the common order of these traits that I have seen.

2020-03-07 19:11 UTC, shepmaster commented on src/libcore/ops/arith.rs
> +/// #[derive(Debug, PartialEq, Clone, Copy)]
```suggestion
/// #[derive(Debug, Copy, Clone, PartialEq)]
```

2020-03-07 19:11 UTC, shepmaster commented on src/libcore/ops/arith.rs
> +/// #[derive(Debug, PartialEq, Clone, Copy)]
```suggestion
/// #[derive(Debug, Copy, Clone, PartialEq)]
```

2020-03-07 19:11 UTC, shepmaster commented on src/libcore/ops/arith.rs
> +/// #[derive(Debug, PartialEq, Clone, Copy)]
```suggestion
/// #[derive(Debug, Copy, Clone, PartialEq)]
```

2020-03-07 19:11 UTC, shepmaster commented on src/libcore/ops/arith.rs
> +/// #[derive(Debug, PartialEq, Clone, Copy)]
```suggestion
/// #[derive(Debug, Copy, Clone, PartialEq)]
```

2020-03-07 19:11 UTC, shepmaster commented on src/libcore/ops/arith.rs
> +/// #[derive(Debug, PartialEq, Clone, Copy)]
```suggestion
/// #[derive(Debug, Copy, Clone, PartialEq)]
```

2020-03-07 19:11 UTC, shepmaster commented on src/libcore/ops/mod.rs
> +//! #[derive(Debug, PartialEq, Clone, Copy)]
```suggestion
/// #[derive(Debug, Copy, Clone, PartialEq)]
```

2020-03-07 19:13 UTC, shepmaster commented
> This changes the semantics of the edited examples slightly: instead
> of consuming the operands during addition, it will copy them. This
> is desired behaviour.

It's pure pedantry, but since the operands don't appear to be used after the operation (and they couldn't have been because they weren't `Copy` or `Clone`), there's no reason for them to be copied. They will still be moved into the method.

It comes down to the typical sci-fi dilemma: which of the two values is the copy and which is the original?

2020-03-10 11:05 UTC, rust-highfive commented
The job `mingw-check` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=22820&view=logs&jobId=74054d28-c774-5fab-ecc2-352fe71b230e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/22820/logs/71), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/22820/logs/71)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-03-10T10:59:33.6375270Z ========================== Starting Command Output ===========================
2020-03-10T10:59:33.6380701Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/c04e70a7-0679-4035-bbec-3a3d41c60c5d.sh
2020-03-10T10:59:33.6381249Z 
2020-03-10T10:59:33.6385433Z ##[section]Finishing: Disable git automatic line ending conversion
2020-03-10T10:59:33.6407636Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/69766/merge to s
2020-03-10T10:59:33.6412928Z Task         : Get sources
2020-03-10T10:59:33.6413542Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-03-10T10:59:33.6413840Z Version      : 1.0.0
2020-03-10T10:59:33.6414033Z Author       : Microsoft
---
2020-03-10T10:59:36.4868952Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-03-10T10:59:36.4880706Z ##[command]git config gc.auto 0
2020-03-10T10:59:36.4889138Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-03-10T10:59:36.4896673Z ##[command]git config --get-all http.proxy
2020-03-10T10:59:36.4908383Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/69766/merge:refs/remotes/pull/69766/merge
---
2020-03-10T11:05:19.9528620Z    |
2020-03-10T11:05:19.9529184Z 46 | //! struct Point {
2020-03-10T11:05:19.9529812Z    | ^^^^^^^^^^^^^^^^^^
2020-03-10T11:05:19.9530286Z    |
2020-03-10T11:05:19.9531027Z    = note: inner doc comments like this (starting with `//!` or `/*!`) can only appear before items
2020-03-10T11:05:19.9537359Z error: aborting due to previous error
2020-03-10T11:05:19.9537613Z 
2020-03-10T11:05:19.9566643Z error: could not compile `core`.
2020-03-10T11:05:19.9575137Z warning: build failed, waiting for other jobs to finish...
---
2020-03-10T11:05:24.6932218Z   local time: Tue Mar 10 11:05:24 UTC 2020
2020-03-10T11:05:24.7851730Z   network time: Tue, 10 Mar 2020 11:05:24 GMT
2020-03-10T11:05:24.7852150Z == end clock drift check ==
2020-03-10T11:05:33.1545602Z 
2020-03-10T11:05:33.1630347Z ##[error]Bash exited with code '1'.
2020-03-10T11:05:33.1648617Z ##[section]Finishing: Run build
2020-03-10T11:05:33.1697408Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/69766/merge to s
2020-03-10T11:05:33.1702686Z Task         : Get sources
2020-03-10T11:05:33.1703095Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-03-10T11:05:33.1703480Z Version      : 1.0.0
2020-03-10T11:05:33.1703734Z Author       : Microsoft
2020-03-10T11:05:33.1703734Z Author       : Microsoft
2020-03-10T11:05:33.1704149Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
2020-03-10T11:05:33.1704647Z ==============================================================================
2020-03-10T11:05:33.5001438Z Cleaning any cached credential from repository: rust-lang/rust (GitHub)
2020-03-10T11:05:33.5050303Z ##[section]Finishing: Checkout rust-lang/rust@refs/pull/69766/merge to s
2020-03-10T11:05:33.5146396Z Cleaning up task key
2020-03-10T11:05:33.5147918Z Start cleaning up orphan processes.
2020-03-10T11:05:33.5344480Z Terminate orphan process: pid (4362) (python)
2020-03-10T11:05:33.5515276Z ##[section]Finishing: Finalize Job
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@rust-lang/infra`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2020-03-10 11:28 UTC, skade commented on src/libcore/ops/mod.rs
> +/// #[derive(Debug, Copy, Clone, PartialEq)]
```suggestion
//! #[derive(Debug, Copy, Clone, PartialEq)]
```

2020-03-10 11:28 UTC, skade commented on src/libcore/ops/mod.rs
> +/// #[derive(Debug, Copy, Clone, PartialEq)]
Fix misapplied suggestion.

2020-03-10 12:02 UTC, skade commented
@shepmaster Interesting, I couldn't find a reference to that order somewhere. Most codebases I use put Clone before Copy. (prerequisite in front)

In any case, your order reads well and puts the Copy more upfront.

2020-03-10 12:36 UTC, shepmaster commented
Looks good to me; squash things together and we will merge!

2020-03-10 17:17 UTC, skade commented
@shepmaster thank you!

2020-03-10 18:20 UTC, shepmaster commented
@bors r+ rollup

2020-03-11 12:49 UTC, merged