Cleanup E0391 explanation
rust-lang/rust pull request #69807
Opened 2020-03-07 17:43 UTC by GuillaumeGomez

r? @Dylan-DPC

2020-03-07 19:07 UTC, Dylan-DPC-zz requested changes

2020-03-07 19:07 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0391.md
> +A type dependencies cycle has been encountered.
```suggestion
A type dependency cycle has been encountered.
```

2020-03-08 09:45 UTC, GuillaumeGomez commented
Updated!

2020-03-08 17:29 UTC, Dylan-DPC commented
@bors r+ rollup

2020-03-09 00:05 UTC, merged