Add long error explanation for E0628
rust-lang/rust pull request #69867
Opened 2020-03-09 20:37 UTC by ayushmishra2005

Add long explanation for the E0628 error code
Part of #61137

r? @GuillaumeGomez

2020-03-10 02:21 UTC, ayushmishra2005 commented
r? @davidtwco

2020-03-11 16:04 UTC, ayushmishra2005 commented
r? @Dylan-DPC

2020-03-13 02:09 UTC, Dylan-DPC-zz requested changes

2020-03-13 02:09 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0628.md
> +parameter for a generator.This can be fixed by using only
```suggestion
parameter for a generator.This can be fixed by using
```

2020-03-13 02:09 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0628.md
> +0 or 1 parameter for generator. So, for example, we might resolve
```suggestion
at most 1 parameter for the generator. For example, we might resolve
```

2020-03-14 08:22 UTC, ayushmishra2005 commented
Hi @Dylan-DPC I have addressed all PR comments. Could you please review the changes? Thanks in advance.

2020-03-14 19:58 UTC, Dylan-DPC commented
@bors r+ rollup

2020-03-16 16:31 UTC, merged