clean up E0404 explanation
rust-lang/rust pull request #69887
Opened 2020-03-10 11:54 UTC by GuillaumeGomez

r? @Dylan-DPC

2020-03-10 17:53 UTC, Dylan-DPC-zz requested changes

2020-03-10 17:53 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0404.md
> +Something which is not a trait was used in a trait position, such as a bound
```suggestion
A type that is not a trait was used in a trait position, such as a bound
```

2020-03-10 17:53 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0404.md
> +Please verify that the trait's name was not misspelled or othrewise that the
```suggestion
Please verify that the trait's name was not misspelled or that the 
```

2020-03-27 14:04 UTC, Dylan-DPC commented
@bors r+ rollup

2020-03-27 19:22 UTC, merged