Cleanup E0412 and E0422
rust-lang/rust pull request #69917
Opened 2020-03-11 12:08 UTC by GuillaumeGomez

r? @Dylan-DPC

2020-03-11 13:17 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=22917&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/22917/logs/71), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/22917/logs/71)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-03-11T12:08:42.7112643Z ========================== Starting Command Output ===========================
2020-03-11T12:08:42.7114820Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/2bdea09a-409a-436c-891b-17ae92833346.sh
2020-03-11T12:08:42.7115513Z 
2020-03-11T12:08:42.7119369Z ##[section]Finishing: Disable git automatic line ending conversion
2020-03-11T12:08:42.7137243Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/69917/merge to s
2020-03-11T12:08:42.7141061Z Task         : Get sources
2020-03-11T12:08:42.7141314Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-03-11T12:08:42.7141612Z Version      : 1.0.0
2020-03-11T12:08:42.7141780Z Author       : Microsoft
---
2020-03-11T12:08:43.9581213Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-03-11T12:08:43.9589089Z ##[command]git config gc.auto 0
2020-03-11T12:08:43.9592139Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-03-11T12:08:43.9594814Z ##[command]git config --get-all http.proxy
2020-03-11T12:08:43.9602387Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/69917/merge:refs/remotes/pull/69917/merge
---
2020-03-11T13:06:05.9659321Z .................................................................................................... 1700/9755
2020-03-11T13:06:10.6691435Z .................................................................................................... 1800/9755
2020-03-11T13:06:22.5186117Z .............................................................i...................................... 1900/9755
2020-03-11T13:06:30.1192310Z .................................................................................................... 2000/9755
2020-03-11T13:06:45.1630615Z ...................................................iiiii............................................ 2100/9755
2020-03-11T13:06:55.4470010Z .................................................................................................... 2300/9755
2020-03-11T13:06:57.6813508Z .................................................................................................... 2400/9755
2020-03-11T13:07:00.9199387Z .................................................................................................... 2500/9755
2020-03-11T13:07:22.9677014Z .................................................................................................... 2600/9755
---
2020-03-11T13:10:04.1056255Z .....................i...............i.............................................................. 5000/9755
2020-03-11T13:10:13.8844961Z .................................................................................................... 5100/9755
2020-03-11T13:10:19.5175864Z ................................................................i................................... 5200/9755
2020-03-11T13:10:25.9014492Z .................................................................................................... 5300/9755
2020-03-11T13:10:35.1996927Z .............................................ii.ii........i...i..................................... 5400/9755
2020-03-11T13:10:43.2431876Z .................................................................................................... 5600/9755
2020-03-11T13:10:52.9843250Z ..................F................................................................................. 5700/9755
2020-03-11T13:10:59.7296425Z ....................................i............................................................... 5800/9755
2020-03-11T13:11:05.6221183Z .................................................................................................... 5900/9755
2020-03-11T13:11:05.6221183Z .................................................................................................... 5900/9755
2020-03-11T13:11:16.2903534Z .................................................................................................... 6000/9755
2020-03-11T13:11:25.6264980Z .............................ii...i..ii...........i................................................. 6100/9755
2020-03-11T13:11:43.1049960Z .................................................................................................... 6300/9755
2020-03-11T13:11:50.0626208Z .................................................................................................... 6400/9755
2020-03-11T13:11:50.0626208Z .................................................................................................... 6400/9755
2020-03-11T13:11:56.6108434Z ............................................................i..ii................................... 6500/9755
2020-03-11T13:12:22.7592414Z .................................................................................................... 6700/9755
2020-03-11T13:12:26.5324698Z ......................................................i............................................. 6800/9755
2020-03-11T13:12:28.5180286Z .................................................................................................... 6900/9755
2020-03-11T13:12:30.5466901Z .....................................................................................i.............. 7000/9755
---
2020-03-11T13:14:10.5427959Z .................................................................................................... 7700/9755
2020-03-11T13:14:14.6096783Z .................................................................................................... 7800/9755
2020-03-11T13:14:20.5751804Z .................................................................................................... 7900/9755
2020-03-11T13:14:27.6502731Z ...................................i................................................................ 8000/9755
2020-03-11T13:14:36.6367238Z ....................................................................................iiiiiiiiii.i.... 8100/9755
2020-03-11T13:14:52.6555543Z ............................i......i................................................................ 8300/9755
2020-03-11T13:14:57.4629710Z .................................................................................................... 8400/9755
2020-03-11T13:15:08.9275453Z .................................................................................................... 8500/9755
2020-03-11T13:15:20.9643414Z .................................................................................................... 8600/9755
---
2020-03-11T13:17:18.2044929Z 8 
2020-03-11T13:17:18.2045047Z 
2020-03-11T13:17:18.2045138Z 
2020-03-11T13:17:18.2045348Z The actual stderr differed from the expected stderr.
2020-03-11T13:17:18.2046011Z Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/use_suggestion_json/use_suggestion_json.stderr
2020-03-11T13:17:18.2046631Z To update references, rerun the tests and pass the `--bless` flag
2020-03-11T13:17:18.2047176Z To only update this specific test, also pass `--test-args lint/use_suggestion_json.rs`
2020-03-11T13:17:18.2047612Z error: 1 errors occurred comparing output.
2020-03-11T13:17:18.2047896Z failed to de [...]

2020-03-12 00:46 UTC, Dylan-DPC-zz requested changes

2020-03-12 00:46 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0422.md
> +An identifier that is either undefined or not a struct was used.
```suggestion
An identifier that is neither undefined nor a struct was used.
```

2020-03-13 13:48 UTC, Dylan-DPC commented
@bors r+ rollup

2020-03-13 16:16 UTC, pietroalbini commented
Had to kill the PR build to get CI back up and running, sorry for the trouble.

2020-03-13 16:20 UTC, Dylan-DPC commented
No worries :)

2020-03-13 18:59 UTC, JohnTitor commented
Failed in https://github.com/rust-lang/rust/pull/69979#issuecomment-598860236
You should bless `ui/lint/use_suggestion_json.rs` test, it includes E0412 description.

@bors r-

2020-03-15 18:34 UTC, Dylan-DPC commented
@bors r+ rollup

2020-03-16 06:22 UTC, merged