Add long error explanation for E0634
rust-lang/rust pull request #69998
Opened 2020-03-14 10:32 UTC by ayushmishra2005

Add long explanation for the E0634 error code
Part of #61137

r? @GuillaumeGomez

2020-03-14 10:32 UTC, rust-highfive commented
Some changes occurred in diagnostic error codes

cc @GuillaumeGomez

2020-03-14 10:32 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @GuillaumeGomez (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2020-03-14 18:11 UTC, Dylan-DPC-zz requested changes

2020-03-14 18:11 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0634.md
> +A type has conflicting `packed` representation hint.
```suggestion
A type has conflicting `packed` representation hints.
```

2020-03-14 18:11 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0634.md
> +You cannot use conflicting `packed` hint on a same type. If you want to pack a
```suggestion
You cannot use conflicting `packed` hints on a same type. If you want to pack a
```

2020-03-14 20:53 UTC, GuillaumeGomez approved these changes
Looks good to me (minus the corrections @Dylan-DPC asked for)!

2020-03-15 13:44 UTC, GuillaumeGomez commented
Thanks!

@bors: r=Dylan-DPC,GuillaumeGomez rollup

2020-03-16 06:22 UTC, merged