Implement Chain with Fuses, and Fuse with Option
rust-lang/rust pull request #70332
Opened 2020-03-23 20:02 UTC by cuviper

These two changes were inspired by the [proposal](https://internals.rust-lang.org/t/proposal-implement-iter-chain-using-fuse/12006) on the internals forum.

By implementing `Chain` with `Fuse`s, it no longer has to juggle the exhaustion state of each of its iterators, greatly simplifying the implementation. However, there was some concern that nested chains could wastefully recurse into exhausted sides when `FusedIterator` specialization is involved, so that possibility is hidden by a simple `Defuse` wrapper.

By implementing `Fuse` with `Option` instead of a separate `bool` flag, we can reduce the possibility of accidentally calling an iterator that should be `done`, as it will be overwritten as `None`. This does have an observable effect of dropping the exhausted iterator sooner. The use of `Option` also allows niche layouts, so the `Fuse` might be smaller overall.

r? @scottmcm

2020-03-23 20:56 UTC, Centril commented
@bors try @rust-timer queue

2020-03-23 20:56 UTC, rust-timer commented
Awaiting bors try build completion

2020-03-23 23:29 UTC, RustyYato requested changes
`nth` and `nth_back` can be improved by avoiding the for loop

2020-03-23 23:29 UTC, KrishnaSannasi commented on src/libcore/iter/adapters/chain.rs
>      }
```suggestion
    #[inline]
    fn nth(&mut self, n: usize) -> Option<Self::Item> {
        let result_of_a = self.a.try_fold(n, |n, x| n.checked_sub(1).ok_or(x));
        match result_of_a {
            Ok(n) => self.b.nth(n),
            Err(item) => Some(item)
        }
    }
```

2020-03-23 23:29 UTC, KrishnaSannasi commented on src/libcore/iter/adapters/chain.rs
>          }
```suggestion
    fn nth(&mut self, n: usize) -> Option<Self::Item> {
        let result_of_b = self.b.try_rfold(n, |n, x| n.checked_sub(1).ok_or(x));
        match result_of_b {
            Ok(n) => self.a.nth_back(n),
            Err(item) => Some(item)
        }
    }
```

2020-03-23 23:29 UTC, rust-timer commented
Queued 6f956ef5779fcbc05aaf93da3972715167a03291 with parent 55299b2ba99432d10f925cd28ff52fe397577371, future [comparison URL](https://perf.rust-lang.org/compare.html?start=55299b2ba99432d10f925cd28ff52fe397577371&end=6f956ef5779fcbc05aaf93da3972715167a03291).

2020-03-23 23:50 UTC, cuviper commented
@KrishnaSannasi 
> `nth` and `nth_back` can be improved by avoiding the for loop

I agree that's a good idea, but maybe it should be a followup PR? For the moment, I've kept mostly the same style of computation, apart from the direct simplification in state tracking.

FWIW, the internal `LoopState` might be a better type for your implementation. I also try to avoid closures in iterator implementations (#62429), but that one would be an easy generic function, no captured values needed.

2020-03-24 00:44 UTC, KrishnaSannasi commented
@cuviper That sounds like a good idea, can I make a PR after if this one is merged?

2020-03-24 01:29 UTC, cuviper commented
Sure, it's all yours.

2020-03-24 16:59 UTC, cuviper commented
1188.7% change in deeply-nested-opt!?!

2020-03-24 18:48 UTC, scottmcm commented
Oh, that benchmark is this:
```rust
    Box::new(empty()
        .chain(empty())
        .chain(empty())
        .chain(empty())
        .chain(empty())
        .chain(empty())
        .chain(empty())
        .chain(empty())
        .chain(empty())
        .chain(empty())
        .chain(empty()) // 10th .chain(empty())
        .chain(empty())
        .chain(empty())
        .chain(empty())
        .chain(empty())
        .chain(empty())
        .chain(empty()) // 16th .chain(empty())
    )
```

I guess it makes sense that if this change is going to impact anything, it'd be that 😕

2020-03-24 18:56 UTC, scottmcm commented
@cuviper I suppose this _is_ making two changes at once.  Your idea to do `Fuse` with `Option` seems clearly-good and separable from this; want to make a PR (either this one or a new one) with just that part?  That might help make it easier to isolate what's going on in perf.

2020-03-24 19:26 UTC, cuviper commented
I was extra confused for a bit that it looks like that benchmark only tests construction, but it returns a `Box<Iterator>`, so it will have to codegen the entire `Iterator` vtable...

2020-04-03 17:28 UTC, cuviper commented
That perf test is _evil_, but I'm a little inclined to accept the loss here. The performance here is not as bad as the original issue #38528, and I found alternate cases that are much worse on the current compiler, but OK with this PR.

The original performance problem was up to Rust 1.25, where I get 11.37s for `build --release`. With the fix #48296 in Rust 1.26, I get 0.24s, and on `1.44.0-nightly (537ccdf3a 2020-04-02)` I get 0.20s. With this `Chain` PR I get 1.37s -- definitely worse, but not a full regression.

However, `Box<Iterator<Item = ()>>` is pretty useless, and your comment about ZSTs made me think to try other `Item` types (still with `Empty`). With `bool`, nightly gets 0.26s and this PR gets 1.43s. With `NonZeroU32`, nightly gets 0.24s and this PR gets 1.40s. With `u32`, nightly **did not finish** (burned 200% CPU for 5 minutes before I killed it), yet this PR gets 1.43s.

I'll file a new issue for that -- something in the compiler needs to be fixed regardless of whether we change `Chain`.

---

The rest of the perf report still showed some slowdowns, though not as drastic, so I'll also explore if there are any other tweaks I can make here.

2020-04-03 21:45 UTC, cuviper commented
> The original performance problem was up to Rust 1.25, where I get 11.37s for `build --release`. With the fix #48296 in Rust 1.26, I get 0.24s, and on `1.44.0-nightly (537ccdf3a 2020-04-02)` I get 0.20s. With this `Chain` PR I get 1.37s -- definitely worse, but not a full regression.

When rebased onto #70750, this PR is down to 0.45s compiling deeply-nested. So the added iterator layers still slow us down, but maybe it's close enough to write off for this pathological test.

> With `u32`, nightly **did not finish** (burned 200% CPU for 5 minutes before I killed it), yet this PR gets 1.43s.

See issue #70749 for the hang. With #70750, this PR gets down to 0.54s.

2020-04-06 19:32 UTC, cuviper commented
Let's measure again now that #70750 has landed.

@bors try @rust-timer queue

2020-04-06 19:32 UTC, rust-timer commented
Awaiting bors try build completion

2020-04-06 22:30 UTC, rust-timer commented
Queued 601c05538b7638fb0937bd659aab41fdfb41444d with parent 40158901d5c7e65b2fb5adc6ce186bc308274954, future [comparison URL](https://perf.rust-lang.org/compare.html?start=40158901d5c7e65b2fb5adc6ce186bc308274954&end=601c05538b7638fb0937bd659aab41fdfb41444d).

2020-04-07 02:17 UTC, rust-timer commented
Finished benchmarking try commit 601c05538b7638fb0937bd659aab41fdfb41444d, [comparison URL](https://perf.rust-lang.org/compare.html?start=40158901d5c7e65b2fb5adc6ce186bc308274954&end=601c05538b7638fb0937bd659aab41fdfb41444d).

2020-04-07 02:47 UTC, CAD97 commented
- deeply-nested-opt: 124.7%
- deeply-nested-debug: 28.3%
- otherwise, close to noise (but trending slower)

2020-04-07 18:30 UTC, cuviper commented
I've posted an alternate in #70896 -- the code is not as pretty as the free `Fuse` would get us here, but it seems to perform a lot better.

2020-04-09 19:31 UTC, cuviper commented
#70896 has merged, so I'm closing this.

2020-04-09 19:31 UTC, closed without merging