Add long error explanation for E0708 #61137
rust-lang/rust pull request #70611
Opened 2020-03-31 13:16 UTC by bishtpawan

Add long explanation for the E0708 error code
Part of #61137

r? @GuillaumeGomez

2020-03-31 13:16 UTC, rust-highfive commented
Some changes occurred in diagnostic error codes

cc @GuillaumeGomez

2020-03-31 14:21 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=24943&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/24943/logs/71), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/24943/logs/71)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-03-31T13:17:31.3804286Z ========================== Starting Command Output ===========================
2020-03-31T13:17:31.3806701Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/86a7b800-8623-4170-95b2-6d9e92fbe25d.sh
2020-03-31T13:17:31.3806969Z 
2020-03-31T13:17:31.3810679Z ##[section]Finishing: Disable git automatic line ending conversion
2020-03-31T13:17:31.3829938Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/70611/merge to s
2020-03-31T13:17:31.3833164Z Task         : Get sources
2020-03-31T13:17:31.3833470Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-03-31T13:17:31.3833786Z Version      : 1.0.0
2020-03-31T13:17:31.3833988Z Author       : Microsoft
---
2020-03-31T13:17:32.3734470Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-03-31T13:17:32.3740713Z ##[command]git config gc.auto 0
2020-03-31T13:17:32.3745534Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-03-31T13:17:32.3750280Z ##[command]git config --get-all http.proxy
2020-03-31T13:17:32.3757917Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/70611/merge:refs/remotes/pull/70611/merge
---
2020-03-31T13:24:18.9588445Z    Compiling rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-03-31T13:24:20.3396364Z    Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-03-31T13:24:21.8645887Z    Compiling rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-03-31T13:24:22.0482952Z    Compiling rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-03-31T13:24:31.3050127Z    Compiling rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-03-31T13:24:32.8504098Z    Compiling rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-03-31T13:24:37.0177767Z    Compiling rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-03-31T13:24:40.9284860Z    Compiling rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-03-31T13:24:50.3541468Z    Compiling rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-03-31T13:45:55.1181131Z    Compiling rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-03-31T13:45:56.7968909Z    Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-03-31T13:45:58.7645692Z    Compiling rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-03-31T13:45:59.5086469Z    Compiling rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-03-31T13:46:10.5191617Z    Compiling rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-03-31T13:46:12.4998292Z    Compiling rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-03-31T13:46:17.6352012Z    Compiling rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-03-31T13:46:22.9039926Z    Compiling rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-03-31T13:46:34.3989751Z    Compiling rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-03-31T14:11:01.9849144Z .................................................................................................... 1700/9856
2020-03-31T14:11:06.0709968Z .................................................................................................... 1800/9856
2020-03-31T14:11:16.0362834Z ..........................................................................................i......... 1900/9856
2020-03-31T14:11:22.7283679Z .................................................................................................... 2000/9856
2020-03-31T14:11:29.0440377Z ................................................................................iiiii............... 2100/9856
2020-03-31T14:11:49.5385230Z .................................................................................................... 2300/9856
2020-03-31T14:11:51.6951696Z .................................................................................................... 2400/9856
2020-03-31T14:11:54.0665389Z .................................................................................................... 2500/9856
2020-03-31T14:12:00.5365411Z .................................................................................................... 2600/9856
---
2020-03-31T14:14:45.3756974Z ......................................................i...............i............................. 5000/9856
2020-03-31T14:14:52.8896445Z .................................................................................................... 5100/9856
2020-03-31T14:14:59.9029665Z ...................................................................................................i 5200/9856
2020-03-31T14:15:04.7297947Z .................................................................................................... 5300/9856
2020-03-31T14:15:15.0289164Z .....................................................................................ii.ii........i. 5400/9856
2020-03-31T14:15:18.5067796Z ..i................................................................................................. 5500/9856
2020-03-31T14:15:27.2555774Z ..............................i..................................................................... 5700/9856
2020-03-31T14:15:36.6867089Z ................................................ii....................................i............. 5800/9856
2020-03-31T14:15:43.8178427Z .................................................................................................... 5900/9856
2020-03-31T14:15:48.6617050Z .................................................................................................... 6000/9856
2020-03-31T14:15:48.6617050Z .................................................................................................... 6000/9856
2020-03-31T14:15:57.5459984Z ................................................................................ii...i..ii.......... 6100/9856
2020-03-31T14:16:09.4055444Z .i.................................................................................................. 6200/9856
2020-03-31T14:16:21.4260608Z .................................................................................................... 6400/9856
2020-03-31T14:16:24.8147428Z .................................................................................................... 6500/9856
2020-03-31T14:16:24.8147428Z .................................................................................................... 6500/9856
2020-03-31T14:16:36.5736770Z ..........i..ii..................................................................................... 6600/9856
2020-03-31T14:16:55.9728435Z .................................................................................................... 6800/9856
2020-03-31T14:16:58.0139553Z ..........i......................................................................................... 6900/9856
2020-03-31T14:17:00.0599281Z .................................................................................................... 7000/9856
2020-03-31T14:17:02.1865100Z ...............................................i.................................................... 7100/9856
---
2020-03-31T14:18:39.0890230 [...]

2020-03-31 16:19 UTC, Dylan-DPC-zz requested changes

2020-03-31 16:19 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0708.md
> +`async` non-`move` closures with parameters are not currently supported.
```suggestion
`async` non-`move` closures with parameters are currently not supported.
```

2020-03-31 16:19 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0708.md
> +`async` with non-move currently not supported with the current
```suggestion
`async` with non-move is currently not supported with the 
```

2020-04-01 05:51 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=25049&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/25049/logs/71), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/25049/logs/71)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-04-01T04:48:37.9909334Z ========================== Starting Command Output ===========================
2020-04-01T04:48:37.9914212Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/87e490c3-58e3-486b-bd0a-501aa5bf94d2.sh
2020-04-01T04:48:37.9914563Z 
2020-04-01T04:48:37.9918866Z ##[section]Finishing: Disable git automatic line ending conversion
2020-04-01T04:48:37.9936235Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/70611/merge to s
2020-04-01T04:48:37.9940097Z Task         : Get sources
2020-04-01T04:48:37.9940323Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-04-01T04:48:37.9940578Z Version      : 1.0.0
2020-04-01T04:48:37.9940725Z Author       : Microsoft
---
2020-04-01T04:48:39.2943424Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-04-01T04:48:39.2951884Z ##[command]git config gc.auto 0
2020-04-01T04:48:39.2962139Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-04-01T04:48:39.2975835Z ##[command]git config --get-all http.proxy
2020-04-01T04:48:39.2984772Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/70611/merge:refs/remotes/pull/70611/merge
---
2020-04-01T04:50:53.8288819Z Looks like docker image is the same as before, not uploading
2020-04-01T04:51:00.6323998Z [CI_JOB_NAME=x86_64-gnu-llvm-7]
2020-04-01T04:51:00.6594604Z [CI_JOB_NAME=x86_64-gnu-llvm-7]
2020-04-01T04:51:00.6614417Z == clock drift check ==
2020-04-01T04:51:00.6618598Z   local time: Wed Apr  1 04:51:00 UTC 2020
2020-04-01T04:51:01.1858779Z   network time: Wed, 01 Apr 2020 04:51:01 GMT
2020-04-01T04:51:01.1883043Z Starting sccache server...
2020-04-01T04:51:01.2660775Z configure: processing command line
2020-04-01T04:51:01.2661812Z configure: 
2020-04-01T04:51:01.2662912Z configure: rust.dist-src        := False
---
2020-04-01T04:55:52.9269468Z    Compiling rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-04-01T04:55:54.3501879Z    Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-04-01T04:55:55.7708005Z    Compiling rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-04-01T04:55:57.3558562Z    Compiling rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-04-01T04:56:05.2374082Z    Compiling rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-04-01T04:56:08.2487569Z    Compiling rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-04-01T04:56:12.3387247Z    Compiling rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-04-01T04:56:16.2580653Z    Compiling rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-04-01T04:56:24.3186875Z    Compiling rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-04-01T05:17:05.6313949Z    Compiling rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-04-01T05:17:07.4056538Z    Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-04-01T05:17:09.2488113Z    Compiling rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-04-01T05:17:11.2779789Z    Compiling rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-04-01T05:17:20.7781966Z    Compiling rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-04-01T05:17:24.3935281Z    Compiling rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-04-01T05:17:29.3120500Z    Compiling rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-04-01T05:17:34.4292776Z    Compiling rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-04-01T05:17:43.7203705Z    Compiling rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-04-01T05:41:02.3793169Z .................................................................................................... 1700/9865
2020-04-01T05:41:06.0022584Z .................................................................................................... 1800/9865
2020-04-01T05:41:14.0490725Z ...............................................................................................i.... 1900/9865
2020-04-01T05:41:21.1206410Z .................................................................................................... 2000/9865
2020-04-01T05:41:26.8247546Z .....................................................................................iiiii.......... 2100/9865
2020-04-01T05:41:45.5698674Z .................................................................................................... 2300/9865
2020-04-01T05:41:47.5574083Z .................................................................................................... 2400/9865
2020-04-01T05:41:49.5642827Z .................................................................................................... 2500/9865
2020-04-01T05:41:54.9818808Z .................................................................................................... 2600/9865
---
2020-04-01T05:44:30.0771347Z ...........................................................i...............i........................ 5000/9865
2020-04-01T05:44:36.9974758Z .................................................................................................... 5100/9865
2020-04-01T05:44:43.8989460Z .................................................................................................... 5200/9865
2020-04-01T05:44:48.2941530Z ....i............................................................................................... 5300/9865
2020-04-01T05:44:57.6126415Z ..........................................................................................ii.ii..... 5400/9865
2020-04-01T05:45:01.3042726Z ...i...i............................................................................................ 5500/9865
2020-04-01T05:45:09.1364860Z ...................................i................................................................ 5700/9865
2020-04-01T05:45:18.0271247Z .......................................................ii....................................i...... 5800/9865
2020-04-01T05:45:24.8502436Z .................................................................................................... 5900/9865
2020-04-01T05:45:29.1875144Z .................................................................................................... 6000/9865
2020-04-01T05:45:29.1875144Z .................................................................................................... 6000/9865
2020-04-01T05:45:37.2192746Z .......................................................................................ii...i...ii.. 6100/9865
2020-04-01T05:45:55.8258401Z .................................................................................................... 6300/9865
2020-04-01T05:46:02.2911639Z .................................................................................................... 6400/9865
2020-04-01T05:46:08.5586738Z .................................................................................................... 6500/9865
2020-04-01T05:46:08.5586738Z .................................................................................................... 6500/9865
2020-04-01T05:46:20.2299121Z .................i..ii................................. [...]

2020-04-01 09:10 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=25055&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/25055/logs/71), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/25055/logs/71)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-04-01T07:34:49.4917560Z ========================== Starting Command Output ===========================
2020-04-01T07:34:49.4919970Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/36d6a385-1cbc-4371-9ed9-00e341db993e.sh
2020-04-01T07:34:49.4920229Z 
2020-04-01T07:34:49.4923612Z ##[section]Finishing: Disable git automatic line ending conversion
2020-04-01T07:34:49.4941560Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/70611/merge to s
2020-04-01T07:34:49.4944915Z Task         : Get sources
2020-04-01T07:34:49.4945224Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-04-01T07:34:49.4945526Z Version      : 1.0.0
2020-04-01T07:34:49.4945726Z Author       : Microsoft
---
2020-04-01T07:34:50.5044555Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-04-01T07:34:50.5050094Z ##[command]git config gc.auto 0
2020-04-01T07:34:50.5053879Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-04-01T07:34:50.5058480Z ##[command]git config --get-all http.proxy
2020-04-01T07:34:50.5066097Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/70611/merge:refs/remotes/pull/70611/merge
---
2020-04-01T07:37:01.4573384Z Looks like docker image is the same as before, not uploading
2020-04-01T07:37:06.1022498Z [CI_JOB_NAME=x86_64-gnu-llvm-7]
2020-04-01T07:37:06.1353424Z [CI_JOB_NAME=x86_64-gnu-llvm-7]
2020-04-01T07:37:06.1378750Z == clock drift check ==
2020-04-01T07:37:06.1387156Z   local time: Wed Apr  1 07:37:06 UTC 2020
2020-04-01T07:37:06.2010924Z   network time: Wed, 01 Apr 2020 07:37:06 GMT
2020-04-01T07:37:06.2044465Z Starting sccache server...
2020-04-01T07:37:06.2805414Z configure: processing command line
2020-04-01T07:37:06.2805990Z configure: 
2020-04-01T07:37:06.2806801Z configure: rust.dist-src        := False
---
2020-04-01T07:41:36.1156101Z    Compiling rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-04-01T07:41:37.3714271Z    Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-04-01T07:41:38.7520284Z    Compiling rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-04-01T07:41:39.2075164Z    Compiling rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-04-01T07:41:47.3930703Z    Compiling rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-04-01T07:41:48.9101359Z    Compiling rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-04-01T07:41:52.8271660Z    Compiling rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-04-01T07:41:56.5059334Z    Compiling rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-04-01T07:42:05.1461236Z    Compiling rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-04-01T08:01:44.8855290Z    Compiling rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-04-01T08:01:46.5053233Z    Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-04-01T08:01:48.3082475Z    Compiling rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-04-01T08:01:48.9896799Z    Compiling rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-04-01T08:01:59.4013735Z    Compiling rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-04-01T08:02:01.3507129Z    Compiling rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-04-01T08:02:06.1474677Z    Compiling rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-04-01T08:02:11.0143807Z    Compiling rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-04-01T08:02:21.3013633Z    Compiling rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-04-01T08:25:20.8257232Z .................................................................................................... 1700/9865
2020-04-01T08:25:24.6349690Z .................................................................................................... 1800/9865
2020-04-01T08:25:32.8960008Z ...............................................................................................i.... 1900/9865
2020-04-01T08:25:40.1580675Z .................................................................................................... 2000/9865
2020-04-01T08:25:46.1278611Z .....................................................................................iiiii.......... 2100/9865
2020-04-01T08:26:05.6028019Z .................................................................................................... 2300/9865
2020-04-01T08:26:07.6093809Z .................................................................................................... 2400/9865
2020-04-01T08:26:09.7507884Z .................................................................................................... 2500/9865
2020-04-01T08:26:15.3646185Z .................................................................................................... 2600/9865
---
2020-04-01T08:28:54.5926567Z ...........................................................i...............i........................ 5000/9865
2020-04-01T08:29:02.0323430Z .................................................................................................... 5100/9865
2020-04-01T08:29:09.3462944Z .................................................................................................... 5200/9865
2020-04-01T08:29:14.1708610Z ....i............................................................................................... 5300/9865
2020-04-01T08:29:24.1793138Z ..........................................................................................ii.ii..... 5400/9865
2020-04-01T08:29:28.2639258Z ...i...i............................................................................................ 5500/9865
2020-04-01T08:29:36.7611810Z ...................................i................................................................ 5700/9865
2020-04-01T08:29:45.9869995Z .......................................................ii....................................i...... 5800/9865
2020-04-01T08:29:53.1039471Z .................................................................................................... 5900/9865
2020-04-01T08:29:57.7059020Z .................................................................................................... 6000/9865
2020-04-01T08:29:57.7059020Z .................................................................................................... 6000/9865
2020-04-01T08:30:06.2643151Z .......................................................................................ii...i..ii... 6100/9865
2020-04-01T08:30:25.7479610Z .................................................................................................... 6300/9865
2020-04-01T08:30:30.0591262Z .................................................................................................... 6400/9865
2020-04-01T08:30:32.8440312Z .................................................................................................... 6500/9865
2020-04-01T08:30:32.8440312Z .................................................................................................... 6500/9865
2020-04-01T08:30:44.3655619Z .................i..ii................................. [...]

2020-04-01 09:38 UTC, GuillaumeGomez commented on src/librustc_error_codes/error_codes/E0708.md
> +```compile_fail,E0708
````suggestion
```compile_fail,E0708,edition2018
````

2020-04-01 09:38 UTC, GuillaumeGomez commented on src/librustc_error_codes/error_codes/E0708.md
> +```
````suggestion
```edition2018
````

2020-04-03 05:27 UTC, bishtpawan commented
r? @GuillaumeGomez

2020-04-10 15:31 UTC, GuillaumeGomez commented
Now please squash your commits then r=me. :)

2020-04-12 11:55 UTC, bishtpawan commented
r= @GuillaumeGomez

2020-04-16 14:56 UTC, GuillaumeGomez commented
Thanks!

@bors: r+ rollup

2020-04-17 00:44 UTC, merged