Replace thread_local with generator resume arguments in box_region.
rust-lang/rust pull request #70622
Opened 2020-03-31 16:55 UTC by gizmondo

Fixes #68922.

r? @ghost

2020-03-31 18:48 UTC, gizmondo commented
This is a plain replacement. @jonas-schievink, did you have something more comprehensive in mind?

2020-03-31 18:53 UTC, jonas-schievink commented
Seems like a good start, but to be honest, I have no idea what this code is supposed to do (other than that it can now use resume arguments to do it).

r? @Zoxc

2020-03-31 19:01 UTC, gizmondo commented on src/librustc_interface/passes.rs
> +        let _ = action;
that's just to suppress the warning, probably should be a better way...

2020-04-01 14:53 UTC, jonas-schievink commented
@bors try @rust-timer queue

2020-04-01 14:53 UTC, rust-timer commented
Awaiting bors try build completion

2020-04-01 16:21 UTC, bjorn3 commented
`box_region` is only used in `librustc_interface`, so it is not performance critical. https://github.com/rust-lang/rust/blob/75ff3110ac6d8a0259023b83fd20d7ab295f8dd6/src/librustc_interface/passes.rs#L88-L92

2020-04-01 17:23 UTC, rust-timer commented
Queued eeebed0947b040d9b65683d52071a94d926a398b with parent 99009bf31992fb9257b84550dbf7cb509f987952, future [comparison URL](https://perf.rust-lang.org/compare.html?start=99009bf31992fb9257b84550dbf7cb509f987952&end=eeebed0947b040d9b65683d52071a94d926a398b).

2020-04-01 20:36 UTC, rust-timer commented
Finished benchmarking try commit eeebed0947b040d9b65683d52071a94d926a398b, [comparison URL](https://perf.rust-lang.org/compare.html?start=99009bf31992fb9257b84550dbf7cb509f987952&end=eeebed0947b040d9b65683d52071a94d926a398b).

2020-04-03 19:50 UTC, gizmondo commented
Btw there was a [discussion](https://internals.rust-lang.org/t/making-the-compiler-interface-on-demand-driven/9099/5) that resume arguments can allow to get rid of unsafety in this module. 
But I haven't figured out a way to do it. I think for that to be possible _resume_ should be able to borrow its arguments for the duration of a single call. I.e. something like that should work:
```rust    
let mut gen = Box::pin(static move |mut arg: &mut i32| {
    loop {
        *arg += 1;
        arg = yield;
    }
});
let mut a = 1;
Pin::new(&mut gen).resume(&mut a);
```

Currently it doesn't compile. I'm not sure if I'm doing something wrong or it's just not supported yet.

2020-04-03 20:03 UTC, petrochenkov commented
Since you are working on this, could you perhaps add some docs explaining what the "box region" does and why is it necessary? Right now it's entirely unclear.

2020-04-03 20:18 UTC, gizmondo commented
I'll try.

2020-04-03 20:49 UTC, jonas-schievink commented
@gizmondo for that to work you'd need https://github.com/rust-lang/rust/issues/68923, which is unfortunately very hard to solve

2020-04-10 17:41 UTC, nikomatsakis commented
r? @jonas-schievink

2020-04-10 17:56 UTC, jonas-schievink requested changes
Okay, looks basically good to me @gizmondo!

If you want to add some more comments to this module, feel free. Otherwise r=me with the more detailed panic message below.

2020-04-10 17:56 UTC, jonas-schievink commented on src/librustc_data_structures/box_region.rs
> +                $crate::box_region::Action::Initial => panic!(),
```suggestion
                $crate::box_region::Action::Initial => bug!("unexpected box_region action: {:?}", $action),
```

2020-04-21 09:04 UTC, joelpalmer commented
Ping from Triage: Closed due to inactivity. Please re-open with updates. Thanks for the PR! @gizmondo

2020-04-21 09:04 UTC, closed without merging