Consistent rounding rules for float display with fixed precision
rust-lang/rust pull request #70751
Opened 2020-04-03 22:02 UTC by ayushmishra2005

#70336

2020-04-03 22:02 UTC, rust-highfive commented
r? @cramertj

(rust_highfive has picked a reviewer for you, use r? to override)

2020-04-03 23:24 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=25325&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/25325/logs/71), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/25325/logs/71)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-04-03T22:20:45.0624535Z ========================== Starting Command Output ===========================
2020-04-03T22:20:45.0627448Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/5f76bc42-66a8-4178-a34f-d85d03e68185.sh
2020-04-03T22:20:45.0627738Z 
2020-04-03T22:20:45.0631974Z ##[section]Finishing: Disable git automatic line ending conversion
2020-04-03T22:20:45.0663672Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/70751/merge to s
2020-04-03T22:20:45.0666887Z Task         : Get sources
2020-04-03T22:20:45.0667199Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-04-03T22:20:45.0667496Z Version      : 1.0.0
2020-04-03T22:20:45.0667698Z Author       : Microsoft
---
2020-04-03T22:20:46.0705447Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-04-03T22:20:46.0712371Z ##[command]git config gc.auto 0
2020-04-03T22:20:46.0716002Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-04-03T22:20:46.0719190Z ##[command]git config --get-all http.proxy
2020-04-03T22:20:46.0725159Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/70751/merge:refs/remotes/pull/70751/merge
---
2020-04-03T22:22:53.2621525Z Looks like docker image is the same as before, not uploading
2020-04-03T22:23:01.2628260Z [CI_JOB_NAME=x86_64-gnu-llvm-7]
2020-04-03T22:23:01.2916574Z [CI_JOB_NAME=x86_64-gnu-llvm-7]
2020-04-03T22:23:01.2935011Z == clock drift check ==
2020-04-03T22:23:01.2944104Z   local time: Fri Apr  3 22:23:01 UTC 2020
2020-04-03T22:23:01.3630041Z   network time: Fri, 03 Apr 2020 22:23:01 GMT
2020-04-03T22:23:01.3654945Z Starting sccache server...
2020-04-03T22:23:01.4476908Z configure: processing command line
2020-04-03T22:23:01.4477181Z configure: 
2020-04-03T22:23:01.4478092Z configure: rust.dist-src        := False
---
2020-04-03T22:27:58.8053473Z    Compiling rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-04-03T22:28:00.1794475Z    Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-04-03T22:28:01.6724312Z    Compiling rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-04-03T22:28:02.6009998Z    Compiling rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-04-03T22:28:11.2007860Z    Compiling rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-04-03T22:28:13.0067572Z    Compiling rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-04-03T22:28:17.1106541Z    Compiling rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-04-03T22:28:20.9971720Z    Compiling rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-04-03T22:28:30.2931801Z    Compiling rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-04-03T22:49:13.5056852Z    Compiling rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-04-03T22:49:15.1867602Z    Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-04-03T22:49:17.1188538Z    Compiling rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-04-03T22:49:18.2845069Z    Compiling rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-04-03T22:49:28.8948030Z    Compiling rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-04-03T22:49:30.8756978Z    Compiling rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-04-03T22:49:35.8725090Z    Compiling rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-04-03T22:49:41.0399218Z    Compiling rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-04-03T22:49:51.9030441Z    Compiling rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-04-03T23:14:13.1008391Z .................................................................................................... 1700/9872
2020-04-03T23:14:17.1158637Z .................................................................................................... 1800/9872
2020-04-03T23:14:26.0462879Z ...............................................................................................i.... 1900/9872
2020-04-03T23:14:33.8622832Z .................................................................................................... 2000/9872
2020-04-03T23:14:40.1902158Z .....................................................................................iiiii.......... 2100/9872
2020-04-03T23:15:00.3625695Z .................................................................................................... 2300/9872
2020-04-03T23:15:02.4164251Z .................................................................................................... 2400/9872
2020-04-03T23:15:04.6128770Z .................................................................................................... 2500/9872
2020-04-03T23:15:10.5459618Z .................................................................................................... 2600/9872
---
2020-04-03T23:17:57.8995630Z ...........................................................i...............i........................ 5000/9872
2020-04-03T23:18:04.9558786Z .................................................................................................... 5100/9872
2020-04-03T23:18:12.2442579Z .................................................................................................... 5200/9872
2020-04-03T23:18:17.1449193Z ....i............................................................................................... 5300/9872
2020-04-03T23:18:26.8145469Z ............................................................................................ii.ii... 5400/9872
2020-04-03T23:18:31.2357733Z .....i...i.......................................................................................... 5500/9872
2020-04-03T23:18:39.7279733Z .....................................i.............................................................. 5700/9872
2020-04-03T23:18:49.5048761Z .........................................................ii.....................................i... 5800/9872
2020-04-03T23:18:57.2120785Z .................................................................................................... 5900/9872
2020-04-03T23:19:01.9914614Z .................................................................................................... 6000/9872
2020-04-03T23:19:01.9914614Z .................................................................................................... 6000/9872
2020-04-03T23:19:11.4505673Z .........................................................................................ii...i..ii. 6100/9872
2020-04-03T23:19:31.6548364Z .................................................................................................... 6300/9872
2020-04-03T23:19:38.6668285Z .................................................................................................... 6400/9872
2020-04-03T23:19:41.6769890Z .................................................................................................... 6500/9872
2020-04-03T23:19:41.6769890Z .................................................................................................... 6500/9872
2020-04-03T23:19:53.7877088Z ...................i..ii............................... [...]

2020-04-14 14:00 UTC, Dylan-DPC commented
r? @dtolnay

2020-04-16 00:50 UTC, dtolnay requested changes
I haven't gotten a chance to review the implementation yet but it looks like there is some test code commented out in flt2dec/mod.rs that probably shouldn't be. Is that on purpose? What's the deal with those tests?

2020-04-16 00:56 UTC, dtolnay commented on src/test/ui/ifmt.rs
> +    t!(format!("{:+10.3e}", -1.2345e6f64), "  -1.235e6");
It looks to me like these were correct before. Round-to-even on 1234.5 should go to 1234, not 1235.

2020-04-24 11:13 UTC, crlf0710 commented
@ayushmishra2005 Ping from triage, would you mind addressing the review comments above? thanks

2020-04-24 11:38 UTC, ayushmishra2005 commented
@crlf0710   I am closing this pull request for now because I don't have the bandwidth to address them. I will raise new PR after addressing the above comments.

2020-04-24 11:38 UTC, closed without merging