Linear interpolation (lerp) implementation
rust-lang/rust pull request #71016
Opened 2020-04-11 01:11 UTC by vertexclique

Implements lerp with feature flag: #71015

2020-04-11 01:11 UTC, rust-highfive commented
r? @cramertj

(rust_highfive has picked a reviewer for you, use r? to override)

2020-04-11 02:34 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=25986&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/25986/logs/71), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/25986/logs/71)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-04-11T01:12:26.5486902Z ========================== Starting Command Output ===========================
2020-04-11T01:12:26.5489404Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/ce3250cf-fd03-4a30-bf16-1cff52bc938d.sh
2020-04-11T01:12:26.5489677Z 
2020-04-11T01:12:26.5493163Z ##[section]Finishing: Disable git automatic line ending conversion
2020-04-11T01:12:26.5512338Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/71016/merge to s
2020-04-11T01:12:26.5515594Z Task         : Get sources
2020-04-11T01:12:26.5515912Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-04-11T01:12:26.5516234Z Version      : 1.0.0
2020-04-11T01:12:26.5516440Z Author       : Microsoft
---
2020-04-11T01:12:27.5454619Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-04-11T01:12:27.5460564Z ##[command]git config gc.auto 0
2020-04-11T01:12:27.5465286Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-04-11T01:12:27.5469641Z ##[command]git config --get-all http.proxy
2020-04-11T01:12:27.5479981Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/71016/merge:refs/remotes/pull/71016/merge
---
2020-04-11T01:14:24.0449736Z Looks like docker image is the same as before, not uploading
2020-04-11T01:14:31.9682452Z [CI_JOB_NAME=x86_64-gnu-llvm-7]
2020-04-11T01:14:31.9948296Z [CI_JOB_NAME=x86_64-gnu-llvm-7]
2020-04-11T01:14:31.9975246Z == clock drift check ==
2020-04-11T01:14:31.9984586Z   local time: Sat Apr 11 01:14:31 UTC 2020
2020-04-11T01:14:32.1791434Z   network time: Sat, 11 Apr 2020 01:14:32 GMT
2020-04-11T01:14:32.1818542Z Starting sccache server...
2020-04-11T01:14:32.2685160Z configure: processing command line
2020-04-11T01:14:32.2686263Z configure: 
2020-04-11T01:14:32.2697452Z configure: rust.dist-src        := False
---
2020-04-11T01:19:22.8045502Z    Compiling rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-04-11T01:19:24.0817849Z    Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-04-11T01:19:25.5095983Z    Compiling rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-04-11T01:19:26.4261407Z    Compiling rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-04-11T01:19:34.4038462Z    Compiling rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-04-11T01:19:36.5927302Z    Compiling rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-04-11T01:19:40.6505333Z    Compiling rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-04-11T01:19:44.3647720Z    Compiling rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-04-11T01:19:52.8318663Z    Compiling rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-04-11T01:40:37.6042862Z    Compiling rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-04-11T01:40:39.3125775Z    Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-04-11T01:40:41.2575185Z    Compiling rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-04-11T01:40:42.3138252Z    Compiling rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-04-11T01:40:53.2297213Z    Compiling rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-04-11T01:40:55.4023844Z    Compiling rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-04-11T01:41:00.5644795Z    Compiling rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-04-11T01:41:05.8322110Z    Compiling rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-04-11T01:41:17.0785214Z    Compiling rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-04-11T02:05:13.6670892Z .................................................................................................... 1600/9884
2020-04-11T02:05:19.5806063Z .................................................................................................... 1700/9884
2020-04-11T02:05:23.9478785Z .................................................................................................... 1800/9884
2020-04-11T02:05:32.8510127Z .................................................................................................... 1900/9884
2020-04-11T02:05:40.9561371Z ..i................................................................................................. 2000/9884
2020-04-11T02:05:47.3260454Z ............................................................................................iiiii... 2100/9884
2020-04-11T02:06:07.6334643Z .................................................................................................... 2300/9884
2020-04-11T02:06:09.7448434Z .................................................................................................... 2400/9884
2020-04-11T02:06:11.9496677Z .................................................................................................... 2500/9884
2020-04-11T02:06:17.6257344Z .................................................................................................... 2600/9884
---
2020-04-11T02:09:11.1462381Z .................................................................................................... 5100/9884
2020-04-11T02:09:18.4624957Z .................................................................................................... 5200/9884
2020-04-11T02:09:23.2989316Z ...........i........................................................................................ 5300/9884
2020-04-11T02:09:32.8975630Z .................................................................................................... 5400/9884
2020-04-11T02:09:37.4929002Z ii.ii........i...i.................................................................................. 5500/9884
2020-04-11T02:09:44.8965537Z .............................................i...................................................... 5700/9884
2020-04-11T02:09:54.6397592Z .................................................................ii................................. 5800/9884
2020-04-11T02:10:00.8910263Z ....i............................................................................................... 5900/9884
2020-04-11T02:10:06.1000254Z .................................................................................................... 6000/9884
2020-04-11T02:10:06.1000254Z .................................................................................................... 6000/9884
2020-04-11T02:10:15.4378241Z ..................................................................................................ii 6100/9884
2020-04-11T02:10:26.2066930Z ...i..ii...........i................................................................................ 6200/9884
2020-04-11T02:10:38.3940772Z .................................................................................................... 6400/9884
2020-04-11T02:10:41.4961332Z .................................................................................................... 6500/9884
2020-04-11T02:10:41.4961332Z .................................................................................................... 6500/9884
2020-04-11T02:10:53.1326979Z ............................i..ii...................... [...]

2020-04-11 15:40 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-7` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=26036&view=logs&jobId=0230d20d-e0df-5b62-a6ec-fad0f9c3c3d5) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/26036/logs/71), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/26036/logs/71)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-04-11T14:10:26.8582197Z ========================== Starting Command Output ===========================
2020-04-11T14:10:26.8584651Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/1b887fbe-4f0f-4175-ac1e-1cdd0a2fc378.sh
2020-04-11T14:10:26.8584865Z 
2020-04-11T14:10:26.8587922Z ##[section]Finishing: Disable git automatic line ending conversion
2020-04-11T14:10:26.8606378Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/71016/merge to s
2020-04-11T14:10:26.8609273Z Task         : Get sources
2020-04-11T14:10:26.8609506Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-04-11T14:10:26.8609732Z Version      : 1.0.0
2020-04-11T14:10:26.8609934Z Author       : Microsoft
---
2020-04-11T14:10:28.0763131Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-04-11T14:10:28.0768309Z ##[command]git config gc.auto 0
2020-04-11T14:10:28.0771407Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-04-11T14:10:28.0774484Z ##[command]git config --get-all http.proxy
2020-04-11T14:10:28.0780788Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/71016/merge:refs/remotes/pull/71016/merge
---
2020-04-11T14:12:40.8536641Z Looks like docker image is the same as before, not uploading
2020-04-11T14:12:48.4854889Z [CI_JOB_NAME=x86_64-gnu-llvm-7]
2020-04-11T14:12:48.5184789Z [CI_JOB_NAME=x86_64-gnu-llvm-7]
2020-04-11T14:12:48.5211613Z == clock drift check ==
2020-04-11T14:12:48.5221538Z   local time: Sat Apr 11 14:12:48 UTC 2020
2020-04-11T14:12:48.5420541Z   network time: Sat, 11 Apr 2020 14:12:48 GMT
2020-04-11T14:12:48.5443602Z Starting sccache server...
2020-04-11T14:12:48.6231813Z configure: processing command line
2020-04-11T14:12:48.6232540Z configure: 
2020-04-11T14:12:48.6233653Z configure: rust.dist-src        := False
---
2020-04-11T14:18:01.8396946Z    Compiling rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-04-11T14:18:03.3626671Z    Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-04-11T14:18:05.0591399Z    Compiling rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-04-11T14:18:07.4512524Z    Compiling rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-04-11T14:18:15.3577319Z    Compiling rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-04-11T14:18:19.5014556Z    Compiling rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-04-11T14:18:24.1813511Z    Compiling rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-04-11T14:18:28.4321030Z    Compiling rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-04-11T14:18:36.5568665Z    Compiling rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-04-11T14:41:43.7867271Z    Compiling rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-04-11T14:41:45.6261550Z    Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-04-11T14:41:47.6650449Z    Compiling rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-04-11T14:41:49.7695414Z    Compiling rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-04-11T14:41:59.9556346Z    Compiling rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-04-11T14:42:03.6720550Z    Compiling rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-04-11T14:42:08.9745555Z    Compiling rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-04-11T14:42:14.5988793Z    Compiling rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-04-11T14:42:24.8699062Z    Compiling rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-04-11T15:08:17.9648325Z .................................................................................................... 1700/9886
2020-04-11T15:08:22.2200996Z .................................................................................................... 1800/9886
2020-04-11T15:08:30.7996106Z .................................................................................................... 1900/9886
2020-04-11T15:08:39.0763362Z .....i.............................................................................................. 2000/9886
2020-04-11T15:08:45.4517460Z ..............................................................................................iiiii. 2100/9886
2020-04-11T15:09:07.1127310Z .................................................................................................... 2300/9886
2020-04-11T15:09:09.2975199Z .................................................................................................... 2400/9886
2020-04-11T15:09:11.5194376Z .................................................................................................... 2500/9886
2020-04-11T15:09:17.2019038Z .................................................................................................... 2600/9886
---
2020-04-11T15:12:19.4534685Z .................................................................................................... 5100/9886
2020-04-11T15:12:27.2134377Z .................................................................................................... 5200/9886
2020-04-11T15:12:32.4338836Z .............i...................................................................................... 5300/9886
2020-04-11T15:12:42.5198896Z .................................................................................................... 5400/9886
2020-04-11T15:12:47.7400076Z ..ii.ii........i...i................................................................................ 5500/9886
2020-04-11T15:12:55.4980787Z ...............................................i.................................................... 5700/9886
2020-04-11T15:13:05.9366048Z ...................................................................ii............................... 5800/9886
2020-04-11T15:13:12.3964228Z ......i............................................................................................. 5900/9886
2020-04-11T15:13:18.2510745Z .................................................................................................... 6000/9886
2020-04-11T15:13:18.2510745Z .................................................................................................... 6000/9886
2020-04-11T15:13:28.1874179Z .................................................................................................... 6100/9886
2020-04-11T15:13:39.6692187Z ii...i..ii...........i.............................................................................. 6200/9886
2020-04-11T15:13:55.1778028Z .................................................................................................... 6400/9886
2020-04-11T15:14:01.6076114Z .................................................................................................... 6500/9886
2020-04-11T15:14:01.6076114Z .................................................................................................... 6500/9886
2020-04-11T15:14:14.0052259Z ..............................i..ii................................................................. 6600/9886
2020-04-11T15:14:35.2384735Z ....................................................... [...]

2020-04-12 12:16 UTC, ebarnard commented
The `(1 - t) * a + t * b` form of linear interpolation is only guarenteed to be monotonic if `a * b < 0`.

I've used the implementation from http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0811r2.html#linear-interpolation elsewhere, but this has the drawback that it is quite branch heavy.

2020-04-12 12:54 UTC, hanna-kruppe commented
I find it hard to believe that the C++ version would see much use, given that it's much slower than the simpler alternatives and monotonicity does not seem useful for the most common uses of `lerp` that I'm familiar with.

I'd like to hear about applications where monotonicity matters, but regardless of whether a monotonic lerp is useful, I think it's valuable to have the fast and numerically stable `(1 - t) a + t b` readily available to non-experts. When people keep copying and pasting their own implementations for performance, some percentage of them will probably use the unstable `a + t (b - a)` instead.

I'm already worried that the proposed implementation might be eschewed by performance-minded users because it does not use FMA operations where available (which, to be fair, is currently difficult to do in libstd).

2020-04-12 15:23 UTC, ebarnard commented
I agree that there are probably a limited number of stiuations that require strict monotinicity. However, there are undoubtedly some that do (I have seen a case where I *think* it mattered, and chaging to a monotonic implementation seemed to help fix the issue I was seeing).

Given that is the case, it seems odd for the standard library to include *this* implementation of `lerp` when there isn't a clear best implementation, and when choosing between implementations depends what the application is.

I would expect a game engine to use the `(1 - t) * a + t * b` form, while a mathematical library might use something more similar to the implementation I linked above.

2020-04-12 16:38 UTC, hanna-kruppe commented
You could argue that the standard library should not include any `lerp` implementation, I don't feel strongly about that either way. But I think if it's going to be added at all, then the fast and reasonably-well-behaved variant is going to be more helpful to more people.

2020-04-14 14:33 UTC, XAMPPRocky commented
> Given that is the case, it seems odd for the standard library to include this implementation of lerp when there isn't a clear best implementation, and when choosing between implementations depends what the application is.

The standard library often doesn't have the "best" implementation of a particular problem. There's usually always some trade-off. That being said, the guarantee should probably be mentioned in the documentation so that people are aware of the trade-offs being made.

2020-04-14 14:54 UTC, ebarnard commented
Maybe my wording wasn't very good - by best I mean an implementation that is both correct and as fast as possible. Elsewhere, the standard library seems to favour correctness over speed (e.g. HashMap using SipHash by default). It would be odd for it not to do so here.

2020-04-14 15:08 UTC, ebarnard commented
For reference [here](https://github.com/llvm-mirror/libcxx/blob/cae4caafdebfc30a35833e20f17e4d67668004b3/include/cmath#L616) is the implementation used in LLVM's libcxx. It is very similar to the one from [P0811R3].

Whatever implementation is decided on it ought to [pass the same tests](https://github.com/llvm-mirror/libcxx/blob/e84fd85b88bb1cc2c49179eeba6447c90829bf54/test/std/numerics/c.math/c.math.lerp/c.math.lerp.pass.cpp) as libcxx's.

[P0811R3]: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0811r3.html

2020-04-14 16:14 UTC, hanna-kruppe commented
Reality is a lot more complicated than a "correctness over speed" slogan suggests. Just one example thematically related to this PR: `Iterator::sum` with float elements performs naive serial summation, not anything more numerically robust such as compensated summation.

Furthermore, your arguments are based on a relatively arbitrary and contestable definition of correctness. For example, why does it matter if results are monotonic in `t` but it doesn't matter if results are correctly rounded? Why do the trade-offs w.r.t. numeric stability not factor into the conditions included in the C++ standard, other than the (literal, in the canonical implementation) special case of requiring `lerp(a, b, 1) == b`? There is a value judgement and trade-off underlying the decision to enshrine one property and disregard the others. Sometimes the right thing is to defer to experts or prior art on such decisions, but the C++ standard is not exactly an unimpeachable authority on numerics and std::lerp in particular has been highly controversial.

Finally, once again: if the end result is that libstd provides a function that most prospective users avoid over performance concerns, then little of value is gained. So in my view, your comments at most provide reasons to not provide `lerp` at all.

2020-04-24 10:01 UTC, crlf0710 commented
Let me reassign this to T-libs to make the decision here.
r? @Amanieu

2020-04-24 22:23 UTC, Amanieu commented
I feel that if we do decide to include `lerp` in the standard library then we should use the "correct but slow" version of the function and have a separate `fast_lerp` for the fast but less precise version.

I have concerns regarding the argument order however: `a.lerp(b, t)` breaks the symmetry between the two values being interpolated over. I feel that `t.lerp(a, b)` would make much more sense. Alternatively we could also remove the method syntax and force all arguments to be specified: `lerp(a, b, t)`.

2020-04-24 23:18 UTC, ranma42 commented
Would it make sense to have `lerp` as a method on `Range<f32>` (or `RangeInclusive<f32>`)?

2020-04-27 16:45 UTC, cramertj commented
r? @Amanieu

2020-04-27 17:01 UTC, vertexclique commented
@cramertj Oh sorry I forgot to update you all. This is not ready for review yet, I need to refactor a couple of things. This version won't compile to the expected intrinsic in every rust project. So will use suboptimal non-fma ops. I will ping again. Thanks :)

2020-05-10 18:12 UTC, jdahlstrom commented
It would make sense to me for `lerp` to mirror [`clamp`](https://github.com/rust-lang/rust/issues/44095), which is to say, `t.lerp(a, b)`. The asymmetry of `a.lerp(b, t)` does not feel right to me.

2020-05-28 04:59 UTC, dtolnay requested changes

2020-05-28 04:59 UTC, dtolnay commented on src/libstd/lib.rs
>  #![feature(concat_idents)]
This needs to be put in sorted order per the NB at the top and bottom of this feature list.
<img alt="abcdefghijklmnopqrstuvwxyz" width="60%" src="https://user-images.githubusercontent.com/1940490/83100408-c295ea80-a064-11ea-8cde-42230086445f.png">

2020-05-28 04:59 UTC, dtolnay commented on src/libstd/f32.rs
> +    /// Computes `self + step(upper - pol)` the linear interpolation between
Not sure what `step` refers to but this description doesn't look like it matches the implementation. In particular `pol` is [dimensionless](https://en.wikipedia.org/wiki/Dimensionless_quantity) and `upper` is not so `upper - pol` is not an expression that would make sense.

2020-07-17 21:36 UTC, Dylan-DPC commented
@vertexclique any updates?

2020-07-31 11:16 UTC, vertexclique commented
Ok, I have no disk space left for compiling the compiler. I will carry on when I have a good machine at handy.

2020-08-01 14:07 UTC, closed without merging