[draft] Raw_dylib codegen
rust-lang/rust pull request #71497
Opened 2020-04-24 05:29 UTC by tinaun

for #58713 

i don't quite know if this is how i should structure the code, but it seems to work

2020-04-24 05:29 UTC, rust-highfive commented
r? @estebank

(rust_highfive has picked a reviewer for you, use r? to override)

2020-04-24 07:10 UTC, rust-highfive commented
Your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=27309&view=logs&jobId=74054d28-c774-5fab-ecc2-352fe71b230e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/27309/logs/67), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/27309/logs/67)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-04-24T05:29:41.1803168Z ========================== Starting Command Output ===========================
2020-04-24T05:29:41.1805371Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/ec2e9418-fba9-4fc5-b63c-7aaaf5efcffa.sh
2020-04-24T05:29:41.1805613Z 
2020-04-24T05:29:41.1809248Z ##[section]Finishing: Disable git automatic line ending conversion
2020-04-24T05:29:41.1827979Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/71497/merge to s
2020-04-24T05:29:41.1830733Z Task         : Get sources
2020-04-24T05:29:41.1831008Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-04-24T05:29:41.1831212Z Version      : 1.0.0
2020-04-24T05:29:41.1831352Z Author       : Microsoft
---
2020-04-24T05:29:42.1926479Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-04-24T05:29:42.1930464Z ##[command]git config gc.auto 0
2020-04-24T05:29:42.1933117Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-04-24T05:29:42.1935527Z ##[command]git config --get-all http.proxy
2020-04-24T05:29:42.1940205Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/71497/merge:refs/remotes/pull/71497/merge
---
2020-04-24T05:31:58.3868765Z  ---> f7353ccad5b1
2020-04-24T05:31:58.3869113Z Step 6/7 : ENV RUN_CHECK_WITH_PARALLEL_QUERIES 1
2020-04-24T05:31:58.3869608Z  ---> Using cache
2020-04-24T05:31:58.3870012Z  ---> ed38efbaa060
2020-04-24T05:31:58.3872659Z Step 7/7 : ENV SCRIPT python3 ../x.py test src/tools/expand-yaml-anchors &&            python3 ../x.py check --target=i686-pc-windows-gnu --host=i686-pc-windows-gnu &&            python3 ../x.py build --stage 0 src/tools/build-manifest &&            python3 ../x.py test --stage 0 src/tools/compiletest &&            python3 ../x.py test src/tools/tidy &&            /scripts/validate-toolstate.sh
2020-04-24T05:31:58.3874559Z  ---> c5008ef7ae8e
2020-04-24T05:31:58.3931415Z Successfully built c5008ef7ae8e
2020-04-24T05:31:58.3959823Z Successfully tagged rust-ci:latest
2020-04-24T05:31:58.4218112Z Built container sha256:c5008ef7ae8e94d7ef502e3cef26e61208e14ebdb36913f3a8bb86291bd6430b
2020-04-24T05:31:58.4218112Z Built container sha256:c5008ef7ae8e94d7ef502e3cef26e61208e14ebdb36913f3a8bb86291bd6430b
2020-04-24T05:31:58.4233917Z Looks like docker image is the same as before, not uploading
2020-04-24T05:32:06.7871115Z [CI_JOB_NAME=mingw-check]
2020-04-24T05:32:06.8068557Z [CI_JOB_NAME=mingw-check]
2020-04-24T05:32:06.8092521Z == clock drift check ==
2020-04-24T05:32:06.8100496Z   local time: Fri Apr 24 05:32:06 UTC 2020
2020-04-24T05:32:07.0972528Z   network time: Fri, 24 Apr 2020 05:32:07 GMT
2020-04-24T05:32:07.0995646Z Starting sccache server...
2020-04-24T05:32:07.1997397Z configure: processing command line
2020-04-24T05:32:07.1997606Z configure: 
2020-04-24T05:32:07.1998774Z configure: rust.parallel-compiler := True
---
2020-04-24T05:35:36.9568354Z     Checking rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-04-24T05:35:37.0904055Z     Checking fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-04-24T05:35:37.2678580Z     Checking rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-04-24T05:35:37.3172666Z     Checking rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-04-24T05:35:37.8294932Z     Checking rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-04-24T05:35:40.0865032Z     Checking rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-04-24T05:35:40.5392225Z     Checking rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-04-24T05:35:42.4119155Z     Checking rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-04-24T05:35:42.8077836Z     Checking rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-04-24T05:37:18.9590346Z configure: rust.dist-src        := False
2020-04-24T05:37:18.9590836Z configure: build.locked-deps    := True
2020-04-24T05:37:18.9591333Z configure: rust.debug-assertions := True
2020-04-24T05:37:18.9591853Z configure: build.cargo-native-static := True
2020-04-24T05:37:18.9592441Z configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
2020-04-24T05:37:18.9593081Z configure: writing `config.toml` in current directory
2020-04-24T05:37:18.9593511Z configure: 
2020-04-24T05:37:18.9593925Z configure: run `python /checkout/x.py --help`
2020-04-24T05:37:18.9594632Z configure: 
---
2020-04-24T05:38:39.1584402Z Hugepagesize:       2048 kB
2020-04-24T05:38:39.1584604Z DirectMap4k:      131008 kB
2020-04-24T05:38:39.1584789Z DirectMap2M:     4063232 kB
2020-04-24T05:38:39.1584974Z DirectMap1G:     5242880 kB
2020-04-24T05:38:39.1636348Z + python3 ../x.py test src/tools/expand-yaml-anchors
2020-04-24T05:38:40.3621330Z Ensuring the YAML anchors in the GitHub Actions config were expanded
2020-04-24T05:38:40.3621330Z Ensuring the YAML anchors in the GitHub Actions config were expanded
2020-04-24T05:38:40.3675616Z Building stage0 tool expand-yaml-anchors (x86_64-unknown-linux-gnu)
2020-04-24T05:38:40.5436109Z    Compiling unicode-xid v0.2.0
2020-04-24T05:38:40.6576568Z    Compiling syn v1.0.11
2020-04-24T05:38:41.4026288Z    Compiling linked-hash-map v0.5.2
2020-04-24T05:38:41.4885045Z    Compiling lazy_static v1.4.0
2020-04-24T05:38:41.4885045Z    Compiling lazy_static v1.4.0
2020-04-24T05:38:41.6134414Z    Compiling yaml-rust v0.4.3
2020-04-24T05:38:45.6080030Z    Compiling quote v1.0.2
2020-04-24T05:38:58.9697911Z    Compiling thiserror-impl v1.0.5
2020-04-24T05:39:03.2229062Z    Compiling thiserror v1.0.5
2020-04-24T05:39:03.2723298Z    Compiling yaml-merge-keys v0.4.0
2020-04-24T05:39:04.3603345Z    Compiling expand-yaml-anchors v0.1.0 (/checkout/src/tools/expand-yaml-anchors)
2020-04-24T05:39:08.4210495Z Build completed successfully in 0:00:29
2020-04-24T05:39:08.4293730Z + python3 ../x.py check --target=i686-pc-windows-gnu --host=i686-pc-windows-gnu
2020-04-24T05:39:08.6796480Z     Finished dev [unoptimized] target(s) in 0.16s
2020-04-24T05:39:09.6656846Z Checking rustdoc artifacts (x86_64-unknown-linux-gnu -> i686-pc-windows-gnu)
---
2020-04-24T05:41:04.2099642Z     Checking rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-04-24T05:41:04.2223733Z     Checking fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-04-24T05:41:04.3982702Z     Checking rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-04-24T05:41:04.5916347Z     Checking rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-04-24T05:41:04.9636244Z     Checking rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-04-24T05:41:07.1039610Z     Checking rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-04-24T05:41:07.5419769Z     Checking rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-04-24T05:41:09.4401023Z     Checking rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-04-24T05:41:09.8529721Z     Checking rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-04-24T05:44:26.6011129Z    Compiling cargo_metadata v0.9.1
2020-04-24T05:44:29.8348480Z    Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
2020-04-24T05:44:39.8405568Z     Finished release [optimized] target(s) in 22.21s
2020-04-24T05:44:39.8 [...]

2020-04-24 09:43 UTC, rust-highfive commented
Your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=27317&view=logs&jobId=74054d28-c774-5fab-ecc2-352fe71b230e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/27317/logs/67), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/27317/logs/67)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-04-24T07:45:59.4272836Z ========================== Starting Command Output ===========================
2020-04-24T07:45:59.4277101Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/6bcc49c5-3e25-4b00-a9ef-1964e946e014.sh
2020-04-24T07:45:59.4277547Z 
2020-04-24T07:45:59.4281940Z ##[section]Finishing: Disable git automatic line ending conversion
2020-04-24T07:45:59.4299795Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/71497/merge to s
2020-04-24T07:45:59.4302913Z Task         : Get sources
2020-04-24T07:45:59.4303287Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-04-24T07:45:59.4303556Z Version      : 1.0.0
2020-04-24T07:45:59.4303733Z Author       : Microsoft
---
2020-04-24T07:46:00.6413139Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-04-24T07:46:00.6422511Z ##[command]git config gc.auto 0
2020-04-24T07:46:00.6429038Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-04-24T07:46:00.6433843Z ##[command]git config --get-all http.proxy
2020-04-24T07:46:00.6444488Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/71497/merge:refs/remotes/pull/71497/merge
---
2020-04-24T07:48:27.8971704Z  ---> f7353ccad5b1
2020-04-24T07:48:27.8972151Z Step 6/7 : ENV RUN_CHECK_WITH_PARALLEL_QUERIES 1
2020-04-24T07:48:27.8972580Z  ---> Using cache
2020-04-24T07:48:27.8972914Z  ---> ed38efbaa060
2020-04-24T07:48:27.8975671Z Step 7/7 : ENV SCRIPT python3 ../x.py test src/tools/expand-yaml-anchors &&            python3 ../x.py check --target=i686-pc-windows-gnu --host=i686-pc-windows-gnu &&            python3 ../x.py build --stage 0 src/tools/build-manifest &&            python3 ../x.py test --stage 0 src/tools/compiletest &&            python3 ../x.py test src/tools/tidy &&            /scripts/validate-toolstate.sh
2020-04-24T07:48:27.8977398Z  ---> c5008ef7ae8e
2020-04-24T07:48:27.9004831Z Successfully built c5008ef7ae8e
2020-04-24T07:48:27.9080382Z Successfully tagged rust-ci:latest
2020-04-24T07:48:28.0435332Z Built container sha256:c5008ef7ae8e94d7ef502e3cef26e61208e14ebdb36913f3a8bb86291bd6430b
2020-04-24T07:48:28.0435332Z Built container sha256:c5008ef7ae8e94d7ef502e3cef26e61208e14ebdb36913f3a8bb86291bd6430b
2020-04-24T07:48:28.0452464Z Looks like docker image is the same as before, not uploading
2020-04-24T07:48:36.0107160Z [CI_JOB_NAME=mingw-check]
2020-04-24T07:48:36.0346544Z [CI_JOB_NAME=mingw-check]
2020-04-24T07:48:36.0380691Z == clock drift check ==
2020-04-24T07:48:36.0391517Z   local time: Fri Apr 24 07:48:36 UTC 2020
2020-04-24T07:48:36.1761292Z   network time: Fri, 24 Apr 2020 07:48:36 GMT
2020-04-24T07:48:36.1792091Z Starting sccache server...
2020-04-24T07:48:36.2924506Z configure: processing command line
2020-04-24T07:48:36.2926131Z configure: 
2020-04-24T07:48:36.2927143Z configure: rust.parallel-compiler := True
---
2020-04-24T07:52:42.6588749Z     Checking rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-04-24T07:52:42.7463552Z     Checking fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-04-24T07:52:42.9547817Z     Checking rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-04-24T07:52:43.1025122Z     Checking rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-04-24T07:52:43.6138730Z     Checking rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-04-24T07:52:46.0276067Z     Checking rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-04-24T07:52:46.5476334Z     Checking rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-04-24T07:52:48.7579630Z     Checking rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-04-24T07:52:49.2283912Z     Checking rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-04-24T07:54:46.3455514Z configure: rust.verify-llvm-ir  := True
2020-04-24T07:54:46.3455951Z configure: rust.channel         := nightly
2020-04-24T07:54:46.3456456Z configure: llvm.ccache          := sccache
2020-04-24T07:54:46.3456856Z configure: build.submodules     := False
2020-04-24T07:54:46.3457588Z configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
2020-04-24T07:54:46.3458387Z configure: writing `config.toml` in current directory
2020-04-24T07:54:46.3458720Z configure: 
2020-04-24T07:54:46.3459294Z configure: run `python /checkout/x.py --help`
2020-04-24T07:54:46.3459663Z configure: 
---
2020-04-24T07:56:25.6026205Z Hugepagesize:       2048 kB
2020-04-24T07:56:25.6026404Z DirectMap4k:      114624 kB
2020-04-24T07:56:25.6026618Z DirectMap2M:     4079616 kB
2020-04-24T07:56:25.6026816Z DirectMap1G:     5242880 kB
2020-04-24T07:56:25.6056071Z + python3 ../x.py test src/tools/expand-yaml-anchors
2020-04-24T07:56:27.1191479Z Ensuring the YAML anchors in the GitHub Actions config were expanded
2020-04-24T07:56:27.1191479Z Ensuring the YAML anchors in the GitHub Actions config were expanded
2020-04-24T07:56:27.1201876Z Building stage0 tool expand-yaml-anchors (x86_64-unknown-linux-gnu)
2020-04-24T07:56:27.3774190Z    Compiling unicode-xid v0.2.0
2020-04-24T07:56:27.5214202Z    Compiling syn v1.0.11
2020-04-24T07:56:28.4476017Z    Compiling linked-hash-map v0.5.2
2020-04-24T07:56:28.4575805Z    Compiling lazy_static v1.4.0
2020-04-24T07:56:28.4575805Z    Compiling lazy_static v1.4.0
2020-04-24T07:56:28.6953959Z    Compiling yaml-rust v0.4.3
2020-04-24T07:56:33.2941370Z    Compiling quote v1.0.2
2020-04-24T07:56:48.8792090Z    Compiling thiserror-impl v1.0.5
2020-04-24T07:56:53.9646933Z    Compiling thiserror v1.0.5
2020-04-24T07:56:54.0344741Z    Compiling yaml-merge-keys v0.4.0
2020-04-24T07:56:55.2937701Z    Compiling expand-yaml-anchors v0.1.0 (/checkout/src/tools/expand-yaml-anchors)
2020-04-24T07:56:57.3909644Z Build completed successfully in 0:00:31
2020-04-24T07:56:57.4053560Z + python3 ../x.py check --target=i686-pc-windows-gnu --host=i686-pc-windows-gnu
2020-04-24T07:56:57.6876973Z     Finished dev [unoptimized] target(s) in 0.18s
2020-04-24T07:56:58.8495419Z Checking rustdoc artifacts (x86_64-unknown-linux-gnu -> i686-pc-windows-gnu)
---
2020-04-24T07:59:15.3961010Z     Checking rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-04-24T07:59:15.5840828Z     Checking fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-04-24T07:59:15.7966786Z     Checking rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-04-24T07:59:15.8591561Z     Checking rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-04-24T07:59:16.4703198Z     Checking rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-04-24T07:59:18.9240536Z     Checking rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-04-24T07:59:19.4894481Z     Checking rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-04-24T07:59:21.7173442Z     Checking rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-04-24T07:59:22.1956942Z     Checking rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-04-24T08:03:17.6465392Z    Compiling cargo_metadata v0.9.1
2020-04-24T08:03:21.5552726Z    Compiling tidy v0.1.0 (/checkout/src/tools/tidy)
2020-04-24T08:03:33.3430605Z     Finished release [optimized] target(s) in 26.75s
2020-04-24T08:03:33.3 [...]

2020-04-24 13:25 UTC, est31 requested changes
Some smaller nits

2020-04-24 13:25 UTC, est31 commented on src/librustc_codegen_llvm/base.rs
> +                        let global_name = CString::new(global_name.as_str()).unwrap();
The `as_str` here isn't required.

2020-04-24 13:25 UTC, est31 commented on src/librustc_codegen_llvm/base.rs
> +        debug!("linking raw dylib - {:?}", raw_dylib);
It's not actually doing any linking here. Maybe rather call it "creating raw dylib idata section"?

2020-04-24 13:25 UTC, est31 commented on src/librustc_codegen_ssa/base.rs
> +        match lib.kind {
Using an if here would save an indentation level.

2020-04-25 18:41 UTC, rust-highfive commented
Your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=27453&view=logs&jobId=74054d28-c774-5fab-ecc2-352fe71b230e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/27453/logs/67), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/27453/logs/67)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
2020-04-25T16:54:02.9522104Z ========================== Starting Command Output ===========================
2020-04-25T16:54:02.9525067Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/ed633d74-3c9b-4005-a091-a0a23b8cc160.sh
2020-04-25T16:54:02.9525374Z 
2020-04-25T16:54:02.9529705Z ##[section]Finishing: Disable git automatic line ending conversion
2020-04-25T16:54:02.9563295Z ##[section]Starting: Checkout rust-lang/rust@refs/pull/71497/merge to s
2020-04-25T16:54:02.9567902Z Task         : Get sources
2020-04-25T16:54:02.9568261Z Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
2020-04-25T16:54:02.9568632Z Version      : 1.0.0
2020-04-25T16:54:02.9568866Z Author       : Microsoft
---
2020-04-25T16:54:05.1910643Z ##[command]git remote add origin https://github.com/rust-lang/rust
2020-04-25T16:54:05.2092176Z ##[command]git config gc.auto 0
2020-04-25T16:54:05.2138662Z ##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
2020-04-25T16:54:05.2160271Z ##[command]git config --get-all http.proxy
2020-04-25T16:54:05.2249790Z ##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/71497/merge:refs/remotes/pull/71497/merge
---
2020-04-25T16:57:50.8182188Z  ---> f7353ccad5b1
2020-04-25T16:57:50.8187702Z Step 6/7 : ENV RUN_CHECK_WITH_PARALLEL_QUERIES 1
2020-04-25T16:57:50.8189442Z  ---> Using cache
2020-04-25T16:57:50.8190189Z  ---> ed38efbaa060
2020-04-25T16:57:50.8191945Z Step 7/7 : ENV SCRIPT python3 ../x.py test src/tools/expand-yaml-anchors &&            python3 ../x.py check --target=i686-pc-windows-gnu --host=i686-pc-windows-gnu &&            python3 ../x.py build --stage 0 src/tools/build-manifest &&            python3 ../x.py test --stage 0 src/tools/compiletest &&            python3 ../x.py test src/tools/tidy &&            /scripts/validate-toolstate.sh
2020-04-25T16:57:50.8194616Z  ---> c5008ef7ae8e
2020-04-25T16:57:50.8227298Z Successfully built c5008ef7ae8e
2020-04-25T16:57:50.8271571Z Successfully tagged rust-ci:latest
2020-04-25T16:57:50.8569436Z Built container sha256:c5008ef7ae8e94d7ef502e3cef26e61208e14ebdb36913f3a8bb86291bd6430b
2020-04-25T16:57:50.8569436Z Built container sha256:c5008ef7ae8e94d7ef502e3cef26e61208e14ebdb36913f3a8bb86291bd6430b
2020-04-25T16:57:50.8587140Z Looks like docker image is the same as before, not uploading
2020-04-25T16:57:59.6234890Z [CI_JOB_NAME=mingw-check]
2020-04-25T16:57:59.6533749Z [CI_JOB_NAME=mingw-check]
2020-04-25T16:57:59.6572473Z == clock drift check ==
2020-04-25T16:57:59.6583511Z   local time: Sat Apr 25 16:57:59 UTC 2020
2020-04-25T16:57:59.9392190Z   network time: Sat, 25 Apr 2020 16:57:59 GMT
2020-04-25T16:57:59.9419191Z Starting sccache server...
2020-04-25T16:58:00.0649717Z configure: processing command line
2020-04-25T16:58:00.0649972Z configure: 
2020-04-25T16:58:00.0650881Z configure: rust.parallel-compiler := True
---
2020-04-25T17:02:15.4907186Z     Checking rustc_span v0.0.0 (/checkout/src/librustc_span)
2020-04-25T17:02:20.4040634Z     Checking rustc_errors v0.0.0 (/checkout/src/librustc_errors)
2020-04-25T17:02:21.7753364Z     Checking rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-04-25T17:02:21.8994448Z     Checking fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-04-25T17:02:22.1088730Z     Checking rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-04-25T17:02:22.9190792Z     Checking rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-04-25T17:02:23.0776602Z     Checking rustc_session v0.0.0 (/checkout/src/librustc_session)
2020-04-25T17:02:24.7400715Z     Checking rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-04-25T17:02:25.2861314Z     Checking rustc_parse v0.0.0 (/checkout/src/librustc_parse)
---
2020-04-25T17:04:32.3310021Z configure: llvm.ccache          := sccache
2020-04-25T17:04:32.3310531Z configure: rust.dist-src        := False
2020-04-25T17:04:32.3310836Z configure: llvm.assertions      := True
2020-04-25T17:04:32.3311134Z configure: build.submodules     := False
2020-04-25T17:04:32.3311777Z configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
2020-04-25T17:04:32.3312349Z configure: writing `config.toml` in current directory
2020-04-25T17:04:32.3312802Z configure: 
2020-04-25T17:04:32.3313289Z configure: run `python /checkout/x.py --help`
2020-04-25T17:04:32.3313526Z configure: 
---
2020-04-25T17:06:15.1641748Z Hugepagesize:       2048 kB
2020-04-25T17:06:15.1641952Z DirectMap4k:      147392 kB
2020-04-25T17:06:15.1642158Z DirectMap2M:     4046848 kB
2020-04-25T17:06:15.1642380Z DirectMap1G:     5242880 kB
2020-04-25T17:06:15.1657425Z + python3 ../x.py test src/tools/expand-yaml-anchors
2020-04-25T17:06:16.7097495Z Ensuring the YAML anchors in the GitHub Actions config were expanded
2020-04-25T17:06:16.7097495Z Ensuring the YAML anchors in the GitHub Actions config were expanded
2020-04-25T17:06:16.7111343Z Building stage0 tool expand-yaml-anchors (x86_64-unknown-linux-gnu)
2020-04-25T17:06:16.9776408Z    Compiling unicode-xid v0.2.0
2020-04-25T17:06:17.1118103Z    Compiling syn v1.0.11
2020-04-25T17:06:18.0716447Z    Compiling linked-hash-map v0.5.2
2020-04-25T17:06:18.0939196Z    Compiling lazy_static v1.4.0
2020-04-25T17:06:18.0939196Z    Compiling lazy_static v1.4.0
2020-04-25T17:06:18.3307472Z    Compiling yaml-rust v0.4.3
2020-04-25T17:06:23.2530326Z    Compiling quote v1.0.2
2020-04-25T17:06:39.9546682Z    Compiling thiserror-impl v1.0.5
2020-04-25T17:06:45.3609343Z    Compiling thiserror v1.0.5
2020-04-25T17:06:45.4252229Z    Compiling yaml-merge-keys v0.4.0
2020-04-25T17:06:46.7186417Z    Compiling expand-yaml-anchors v0.1.0 (/checkout/src/tools/expand-yaml-anchors)
2020-04-25T17:06:48.5367645Z Build completed successfully in 0:00:33
2020-04-25T17:06:48.5467686Z + python3 ../x.py check --target=i686-pc-windows-gnu --host=i686-pc-windows-gnu
2020-04-25T17:06:48.8699269Z     Finished dev [unoptimized] target(s) in 0.21s
2020-04-25T17:06:50.1573384Z Checking rustdoc artifacts (x86_64-unknown-linux-gnu -> i686-pc-windows-gnu)
---
2020-04-25T17:09:12.4867358Z     Checking rustc_feature v0.0.0 (/checkout/src/librustc_feature)
2020-04-25T17:09:12.7638989Z     Checking fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
2020-04-25T17:09:12.9725024Z     Checking rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
2020-04-25T17:09:12.9969275Z     Checking rustc_hir v0.0.0 (/checkout/src/librustc_hir)
2020-04-25T17:09:13.6762405Z     Checking rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
2020-04-25T17:09:16.2453963Z     Checking rustc_attr v0.0.0 (/checkout/src/librustc_attr)
2020-04-25T17:09:16.7937977Z     Checking rustc_parse v0.0.0 (/checkout/src/librustc_parse)
2020-04-25T17:09:19.0884084Z     Checking rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
2020-04-25T17:09:19.5869375Z     Checking rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
2020-04-25T17:13:52.0551679Z Diff in /checkout/src/librustc_codegen_llvm/base.rs at line 23:
2020-04-25T17:13:52.0555834Z  use crate::metadata;
2020-04-25T17:13:52.0559755Z  use crate::value::Value;
2020-04-25T17:13:52.0563563Z  
2020-04-25T17:13:52.0571078Z +use log::debug;
2020 [...]

2020-05-11 21:42 UTC, est31 commented
>  stub function generation

Is this actually needed? AFAIK it will just select the functions by name?

> every pointer type here should be a 32 bit RVA - need to get base address

See stack overflow question about it [here](https://stackoverflow.com/a/29581270). You need to declare a specially named constant and then do some computation in IR code. It's also inside the example of #30027. I don't think the computation can be done in the backend as when the IR code is being emitted the info is not available yet, but not an expert.

>  im running into a few llvm assertions

No idea, I'm sorry.

> need examples / test cases

@ZerothLaw has offered help with this. Optimally, the test would create two dll files (written in Rust, using cdylib), both defining and exporting the same function returning a different i32 constant each. Then you'd specify one of the dlls in the test case and assert that the result matches the dll you named.

2020-05-11 21:50 UTC, retep998 commented
Test case:
```Rust
mod foo1 {
    #[link(kind="raw_dylib", name="foo1.dll")]
    extern {
        fn foo() -> i32;
    }
}
mod foo2 {
    #[link(kind="raw_dylib", name="foo2.dll")]
    extern {
        fn foo() -> i32;
    }
}
fn main() {
    unsafe {
        assert_eq!(foo1::foo(), 100);
        assert_eq!(foo2::foo(), 200);
    }
}
```
Variations include mixing `raw_dylib` with other kinds like `dylib` `static` and `static-nobundle`.

2020-05-11 21:54 UTC, tinaun commented
i was under the assumption that examples like the one that @retep998 just posted cannot work unless we generate the stub that calls the correct dll as a mangled rust function

2020-05-11 22:09 UTC, est31 commented
@retep998 how will that be possible? I can't find hints for it to work either in LLVM IR nor in the PE format, but likely I'm missing something.

What would the wrappers contain? How would they be able to differ between foo from foo1.dll and foo from foo2.dll? I can't find a method to link a function to the idata tables, thought they'd be linked by name only.

2020-05-11 22:21 UTC, retep998 commented
I was under the impression that an idata entry could provide a mapping from a mangled name to an external name. There's already some of this going on for things like stdcall and cdecl on 32-bit where `_foo` or `_foo@8` maps to `foo` in a specific dll. Therefore I imagined it would be possible to map from the rust mangled version of foo to `foo` in a specific dll.

2020-05-12 02:05 UTC, est31 commented
Actually you might be right. The import address table contains the needed data during runtime: the addresses of the loaded symbols. I have no idea how to reference it in the wrapper though.

I wonder if [EntryPoint](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute.entrypoint?view=netcore-3.1) of C#'s `DllImport` works similarly.

2020-05-12 04:47 UTC, est31 commented
>  im running into a few llvm assertions (wrong type in array element initializer)

I'm wondering: are you maybe compiling for 64 bit? Because currently the implementation only supports 32 bit...

2020-05-12 20:56 UTC, tinaun commented
rvas are always 32 bit, regardless of platform

2020-05-12 21:57 UTC, est31 commented
Point. The import lookup table has 64 bit entries on 64 bit but even there the RVAs are 31 bit. Also your code doesn't emit it yet so it can't be the cause of the assertion errors.

2020-05-26 15:02 UTC, rust-highfive commented
The job `mingw-check` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=30240&view=logs&jobId=74054d28-c774-5fab-ecc2-352fe71b230e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/30240/logs/67), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/30240/logs/67)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
##[section]Starting: Linux mingw-check
##[section]Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az578'
Current agent version: '2.169.0'
##[group]Operating System
16.04.6
LTS
LTS
##[endgroup]
##[group]Virtual Environment
Environment: ubuntu-16.04
Version: 20200517.1
Included Software: https://github.com/actions/virtual-environments/blob/ubuntu16/20200517.1/images/linux/Ubuntu1604-README.md
##[endgroup]
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.
Download all required tasks.
Downloading task: Bash (3.163.2)
Checking job knob settings.
   Knob: AgentToolsDirectory = /opt/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = /home/vsts/perflog Source: ${VSTS_AGENT_PERFLOG} 
Start tracking orphan processes.
##[section]Finishing: Initialize job
##[section]Starting: Configure Job Name
==============================================================================
---
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/39e8fbf9-3055-4023-b7e5-88ca4e6c7882.sh

##[section]Finishing: Disable git automatic line ending conversion
##[section]Starting: Checkout rust-lang/rust@refs/pull/71497/merge to s
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
---
##[command]git remote add origin https://github.com/rust-lang/rust
##[command]git config gc.auto 0
##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
##[command]git config --get-all http.proxy
##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/71497/merge:refs/remotes/pull/71497/merge
---
 ---> 3adb0605cc65
Step 6/7 : ENV RUN_CHECK_WITH_PARALLEL_QUERIES 1
 ---> Using cache
 ---> 28dbc326cb7f
Step 7/7 : ENV SCRIPT python3 ../x.py test src/tools/expand-yaml-anchors &&            python3 ../x.py check --target=i686-pc-windows-gnu --host=i686-pc-windows-gnu &&            python3 ../x.py build --stage 0 src/tools/build-manifest &&            python3 ../x.py test --stage 0 src/tools/compiletest &&            python3 ../x.py test src/tools/tidy &&            python3 ../x.py doc --stage 0 src/libstd &&            /scripts/validate-toolstate.sh
 ---> 537a01811900
Successfully built 537a01811900
Successfully tagged rust-ci:latest
Built container sha256:537a018119009dc218456238dec90b5530050db1e2a1e166550c218003f6159d
---
    Checking rustc_feature v0.0.0 (/checkout/src/librustc_feature)
    Checking fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
    Checking rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
    Checking rustc_hir v0.0.0 (/checkout/src/librustc_hir)
    Checking rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
    Checking chalk-rust-ir v0.10.0
    Checking rustc_parse v0.0.0 (/checkout/src/librustc_parse)
    Checking rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
    Checking rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
---
    Checking rustc_infer v0.0.0 (/checkout/src/librustc_infer)
    Checking rustc_symbol_mangling v0.0.0 (/checkout/src/librustc_symbol_mangling)
    Checking rustc_save_analysis v0.0.0 (/checkout/src/librustc_save_analysis)
    Checking rustc_trait_selection v0.0.0 (/checkout/src/librustc_trait_selection)
error[E0433]: failed to resolve: could not find `NativeLibraryKind` in `cstore`
   --> src/librustc_codegen_ssa/base.rs:606:32
    |
606 |         if lib.kind == cstore::NativeLibraryKind::NativeRawDylib {
    |                                ^^^^^^^^^^^^^^^^^ could not find `NativeLibraryKind` in `cstore`
error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: could not compile `rustc_codegen_ssa`.
error: could not compile `rustc_codegen_ssa`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "check" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "2" "--release" "--color" "always" "--features" " llvm" "--manifest-path" "/checkout/src/rustc/Cargo.toml" "--message-format" "json-render-diagnostics"
failed to run: /checkout/obj/build/bootstrap/debug/bootstrap check
Build completed unsuccessfully in 0:04:33
== clock drift check ==
  local time: Tue May 26 14:50:26 UTC 2020
  local time: Tue May 26 14:50:26 UTC 2020
  network time: Tue, 26 May 2020 14:50:26 GMT
== end clock drift check ==

##[error]Bash exited with code '1'.
##[section]Finishing: Run build
##[section]Starting: Checkout rust-lang/rust@refs/pull/71497/merge to s
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
Cleaning any cached credential from repository: rust-lang/rust (GitHub)
##[section]Finishing: Checkout rust-lang/rust@refs/pull/71497/merge to s
Cleaning up task key
Start cleaning up orphan processes.
Terminate orphan process: pid (3604) (python)
##[section]Finishing: Finalize Job
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@rust-lang/infra`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2020-07-11 12:49 UTC, Dylan-DPC commented
@tinaun any progress on this?

2020-07-11 12:52 UTC, crlf0710 commented
zulip topic: https://rust-lang.zulipchat.com/#narrow/stream/242869-t-compiler.2Fwindows/topic/Tracking.20raw_dylib.20progress.2E

2020-07-30 20:53 UTC, Muirrum commented
@tinaun what's the status of this?

2020-11-21 14:35 UTC, Dylan-DPC commented
Closing this due to inactivity

2020-11-21 14:35 UTC, closed without merging