Document unsafety slice sort
rust-lang/rust pull request #71568
Opened 2020-04-26 01:20 UTC by hbina

Let me know if these documentations is accurate c:

I don't I am capable of documenting the safety of `partition_blocks`, however.

2020-04-26 01:20 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @JoshTriplett (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2020-06-13 13:51 UTC, Muirrum commented
@rustbot modify labels to +S-waiting-review -S-waiting-on-author

2020-06-13 20:38 UTC, joshtriplett commented on src/libcore/slice/sort.rs
> +    //  3. FIXME: Guarantees that the elements are properly aligned?
If the slice is properly aligned, the elements will be properly aligned. And it's the caller's responsibility to make sure the slice is properly aligned.

2020-06-13 20:38 UTC, joshtriplett commented on src/libcore/slice/sort.rs
> +    //  3. FIXME: Guarantees that the elements are properly aligned?
Same comment as above.

2020-06-13 20:39 UTC, joshtriplett commented on src/libcore/slice/sort.rs
> +        // SAFETY: We already explicitly done the bound checking with `i<len`
```suggestion
        // SAFETY: We already explicitly did the bound checking with `i<len`
```

2020-06-13 20:40 UTC, joshtriplett commented on src/libcore/slice/sort.rs
> +        // All our indexing following that is only in the range {0 <= index < len}
```suggestion
        // All our subsequent indexing is only in the range `0 <= index < len`
```

2020-06-13 20:41 UTC, joshtriplett commented on src/libcore/slice/sort.rs
> +    //  2. All the indexing that we will do is always between {0 <= index < len-1} at most.
```suggestion
    //  2. All the indexing that we will do is always between `0 <= index < len-1` at most.
```

2020-06-13 20:41 UTC, joshtriplett commented on src/libcore/slice/sort.rs
> +        // For the first one: we already do the bound checking here with `l<r`.
```suggestion
        // For the first one: we already do the bounds checking here with `l < r`.
```

2020-06-13 20:42 UTC, joshtriplett commented on src/libcore/slice/sort.rs
> +        // For the secondn one: the minimum value for `l` is 0 and the maximum value for `r` is `v.len().`
```suggestion
        // For the second one: the minimum value for `l` is 0 and the maximum value for `r` is `v.len().`
```

2020-06-13 20:42 UTC, joshtriplett commented on src/libcore/slice/sort.rs
> +        // For the first one: we already do the bound checking here with `l<r`.
```suggestion
        // For the first one: we already do the bounds checking here with `l < r`.
```

2020-06-13 20:43 UTC, joshtriplett requested changes
I posted a few review comments; with those fixed, r=me.

2020-06-13 23:03 UTC, hbina commented
Thanks @joshtriplett ! I have applied your requested changes and added some more safety comments. I read through the discussions by more senior people over at https://github.com/rust-lang/rust/pull/63793
I think some of my documentations might have been too verbose.
Lemme know if they are correct and/or concise enough.

2020-06-14 00:43 UTC, rust-highfive commented
The job `mingw-check` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=31920&view=logs&jobId=74054d28-c774-5fab-ecc2-352fe71b230e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/31920/logs/67), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/31920/logs/67)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
##[section]Starting: Linux mingw-check
##[section]Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az659'
Current agent version: '2.170.1'
##[group]Operating System
16.04.6
LTS
LTS
##[endgroup]
##[group]Virtual Environment
Environment: ubuntu-16.04
Version: 20200604.1
Included Software: https://github.com/actions/virtual-environments/blob/ubuntu16/20200604.1/images/linux/Ubuntu1604-README.md
##[endgroup]
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.
Download all required tasks.
Downloading task: Bash (3.163.3)
Checking job knob settings.
   Knob: AgentToolsDirectory = /opt/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = /home/vsts/perflog Source: ${VSTS_AGENT_PERFLOG} 
Start tracking orphan processes.
##[section]Finishing: Initialize job
##[section]Starting: Configure Job Name
==============================================================================
---
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/51f6869f-b49b-45e9-b10f-d988571068d1.sh

##[section]Finishing: Disable git automatic line ending conversion
##[section]Starting: Checkout rust-lang/rust@refs/pull/71568/merge to s
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
---
##[command]git remote add origin https://github.com/rust-lang/rust
##[command]git config gc.auto 0
##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
##[command]git config --get-all http.proxy
##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/71568/merge:refs/remotes/pull/71568/merge
---
 ---> f883e675ad62
Step 6/7 : ENV RUN_CHECK_WITH_PARALLEL_QUERIES 1
 ---> Using cache
 ---> c0b156eb069c
Step 7/7 : ENV SCRIPT python3 ../x.py test src/tools/expand-yaml-anchors &&            python3 ../x.py check --target=i686-pc-windows-gnu --host=i686-pc-windows-gnu &&            python3 ../x.py build --stage 0 src/tools/build-manifest &&            python3 ../x.py test --stage 0 src/tools/compiletest &&            python3 ../x.py test src/tools/tidy &&            python3 ../x.py doc --stage 0 src/libstd &&            /scripts/validate-toolstate.sh
 ---> 8541bab6b38c
Successfully built 8541bab6b38c
Successfully tagged rust-ci:latest
Built container sha256:8541bab6b38c07f1b7eb787539b9cbe93daa6ac4458d3d7bd8a8921622a14ba1
---
    Checking chalk-rust-ir v0.10.0
    Checking rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
    Checking rustc_hir v0.0.0 (/checkout/src/librustc_hir)
    Checking rustc_session v0.0.0 (/checkout/src/librustc_session)
    Checking rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
    Checking rustc_parse v0.0.0 (/checkout/src/librustc_parse)
    Checking rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
    Checking rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
    Checking rustc_ast_passes v0.0.0 (/checkout/src/librustc_ast_passes)
---
configure: rust.channel         := nightly
configure: rust.codegen-units-std := 1
configure: rust.verify-llvm-ir  := True
configure: llvm.assertions      := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
Hugepagesize:       2048 kB
DirectMap4k:      145344 kB
DirectMap2M:     3000320 kB
DirectMap1G:     6291456 kB
+ python3 ../x.py test src/tools/expand-yaml-anchors
Ensuring the YAML anchors in the GitHub Actions config were expanded
Ensuring the YAML anchors in the GitHub Actions config were expanded
Building stage0 tool expand-yaml-anchors (x86_64-unknown-linux-gnu)
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.11
   Compiling linked-hash-map v0.5.2
   Compiling lazy_static v1.4.0
   Compiling lazy_static v1.4.0
   Compiling yaml-rust v0.4.3
   Compiling quote v1.0.2
   Compiling thiserror-impl v1.0.5
   Compiling thiserror v1.0.5
   Compiling yaml-merge-keys v0.4.0
   Compiling expand-yaml-anchors v0.1.0 (/checkout/src/tools/expand-yaml-anchors)
Build completed successfully in 0:00:22
+ python3 ../x.py check --target=i686-pc-windows-gnu --host=i686-pc-windows-gnu
    Finished dev [unoptimized] target(s) in 0.14s
Checking rustdoc artifacts (x86_64-unknown-linux-gnu -> i686-pc-windows-gnu)
---
    Checking chalk-rust-ir v0.10.0
    Checking rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
    Checking rustc_hir v0.0.0 (/checkout/src/librustc_hir)
    Checking rustc_session v0.0.0 (/checkout/src/librustc_session)
    Checking rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
    Checking rustc_parse v0.0.0 (/checkout/src/librustc_parse)
    Checking rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
    Checking rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
    Checking rustc_ast_passes v0.0.0 (/checkout/src/librustc_ast_passes)
---
Done!
some tidy checks failed


command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/tidy" "/checkout/src" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo"


failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test src/tools/tidy
Build completed unsuccessfully in 0:00:27
Build completed unsuccessfully in 0:00:27
== clock drift check ==
  local time: Sat Jun 13 23:21:20 UTC 2020
  network time: Sat, 13 Jun 2020 23:21:20 GMT
== end clock drift check ==

##[error]Bash exited with code '1'.
##[section]Finishing: Run build
##[section]Starting: Checkout rust-lang/rust@refs/pull/71568/merge to s
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
Cleaning any cached credential from repository: rust-lang/rust (GitHub)
##[section]Finishing: Checkout rust-lang/rust@refs/pull/71568/merge to s
Cleaning up task key
Start cleaning up orphan processes.
Terminate orphan process: pid (3511) (python)
##[section]Finishing: Finalize Job
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@rust-lang/infra`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2020-06-16 03:33 UTC, joshtriplett commented
Looks good to me (and definitely not too verbose). However, it looks like the build is failing because you removed `ignore-tidy-undocumented-unsafe` but there are still some undocumented unsafe blocks. You don't have to document them, but to keep the build passing, can you leave that comment in please?

2020-06-16 17:31 UTC, joshtriplett commented on src/libcore/slice/sort.rs
> +// ignore-tidy-undocumented-unsafe
Please don't move this comment below the `use` lines like this. See the overall diff; these two lines shouldn't change at all.

2020-06-19 15:17 UTC, joshtriplett commented
@bors r+ rollup

2020-06-20 02:24 UTC, merged