Relate existential associated types with variance Invariant
rust-lang/rust pull request #71896
Opened 2020-05-04 20:32 UTC by spastorino

Fixes #71550

r? @nikomatsakis 

The test case reported in that issue now errors with the following message ...

```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter 'a in function call due to conflicting requirements
  --> /tmp/test.rs:25:5
   |
25 |     bad(&Bar(PhantomData), x)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: first, the lifetime cannot outlive the lifetime `'a` as defined on the function body at 24:11...
  --> /tmp/test.rs:24:11
   |
24 | fn extend<'a, T>(x: &'a T) -> &'static T {
   |           ^^
note: ...so that reference does not outlive borrowed content
  --> /tmp/test.rs:25:28
   |
25 |     bad(&Bar(PhantomData), x)
   |                            ^
   = note: but, the lifetime must be valid for the static lifetime...
note: ...so that the types are compatible
  --> /tmp/test.rs:25:9
   |
25 |     bad(&Bar(PhantomData), x)
   |         ^^^^^^^^^^^^^^^^^
   = note: expected  `&'static T`
              found  `&T`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0495`.
```

I could also add that test case if we want to have a weaponized one too.

2020-05-04 20:40 UTC, nikomatsakis requested changes

2020-05-04 20:40 UTC, nikomatsakis commented on src/test/ui/variance/variance-associated-types2.rs
> +trait Foo {
Can we add a comment here? I would say something like

// Test that `dyn Foo<Bar = T>` is invariant with respect to `T`.
// Failure to enforce invariance here can be weaponized, see #12345 for details.

Only with the correct issue number, of course.

2020-05-04 20:45 UTC, nikomatsakis approved these changes

2020-05-04 20:45 UTC, nikomatsakis commented
It seems certainly possible that this will cause regressions in people's code on crater. I wonder if a crater run is appropriate, or if we should just move forward. 

@Mark-Simulacrum -- weren't you saying that the crater queue is very long at present?

2020-05-04 21:08 UTC, spastorino commented
Just pushed some minor stderr files fixes.

2020-05-06 14:35 UTC, nikomatsakis commented
r=me but the only question is whether we should do a crater run -- see [zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/landing.20invariance.20fix.20.2371896)

2020-05-06 14:43 UTC, Mark-Simulacrum commented
@bors try

Let's prepare a try build for a potential crater run

2020-05-06 17:56 UTC, Mark-Simulacrum commented
@craterbot check p=1

2020-05-07 11:15 UTC, Mark-Simulacrum commented
@craterbot retry

I can't find anything in logs...

2020-05-11 12:08 UTC, bjorn3 commented
# Spurious

* Ziqul.vulkano-training.5e4a0f210c93c69cc7a6741ba09aa4c9bcadec9e
* denoland.rusty_v8.36bec8cd2ba766b9428cc0fb3f2038863e7c21ff
* electron-0.1.0
* radish-database-0.1.0
* rusty_v8-0.4.1

# Regressions

* ezksd.combinator.a2989e2e8fc92c9c8b1b4c949d9d8cc0b4de1986
* githubaccount624.rocket-rooms.181ae13300244f79e7295eff84b3d07f7b28bdd5
* gribbet.rust_api_example.6c2086f619b7e3f591cae6a7aa1deed91a504824
* mich101mich.game_rs.f5e2796d3f8437e9630777e745ed7b8b2a513d30
* spacemeowx2.slp-server-rust.2aaf02c7f0a352c6c826c45b6f12f5978604b089
* sstanfield.slsh.b3068a910f91a5bd35b2e2b61a18b5ea18071785
* attr-0.1.0
* dcmdump-0.1.0
* dicom-object-0.1.0
    * dicom-0.1.0
* happy-0.1.1
* symbolic-debuginfo-7.3.0
    * getsentry.sentry-cli.121f1b75e468f21378b2993e369b762f2c05ddf1
    * mozilla.dump_syms.2603fb01a18e4e11d95b95fc08d9dacad9076f43
    * symbolic-minidump-7.3.0
    * symbolic-7.3.0

2020-05-11 13:49 UTC, nikomatsakis commented
Fewer regressions that I feared, though more than I would like. =)

2020-05-11 22:21 UTC, nikomatsakis commented
So I'm pondering a few things:

* We could plausibly try to accept this code.
* We could plausible try a future-compatibility warning, but I don't *quite* know how to do that.
* We could ping crate authors and try to land this change.

2020-05-11 22:56 UTC, Mark-Simulacrum commented
Do we have some breakdown of the regressions into "classes"? My reading of your comment suggests that you believe that all of these cases are in practice sound (that is, the compiler is too restrictive). Is that right?

2020-05-13 12:35 UTC, nikomatsakis commented
@Mark-Simulacrum I have not read all the cases. Maybe I will do so. I'm pretty sure they're "sound" in some sense, though.

2020-05-13 13:05 UTC, nikomatsakis commented
OK, heh, I did a read into the first one and discovered it's quite complex. I started a hackmd where i'll try to report on the others (or maybe others can add in columns etc):

* https://hackmd.io/CxycII6iT8iFjbMr0eQcEQ

2020-05-22 19:14 UTC, nikomatsakis commented
OK my summary is as follows

## summary

| package | sound-ish? | trait |
| --- | --- | --- |
| ezksd | :x: | `dyn Parser<Input = X>`, but interacts with outlives
| rocket-rooms | :heavy_check_mark: | response::ResultFuture<'r> 
| gribbet.rust_api_example | :heavy_check_mark: | ResultFuture<'static>
| mich101mich.game_rs | :heavy_check_mark: | Iterator
| spacemeowx2.slp-server-rust | :heavy_check_mark: | dyn Stream
| sstanfield.slsh | :heavy_check_mark: | dyn Iterator
| attr-1.0 | :shrug: | unclear
| dcmdump-0.1.0 | :shrug: | unclear
| dicom-object-0.1.0 | :shrug: | unclear, same as previous?
| happy-0.1.0 | :x: | `dyn Parser<Input = X>`, maybe interacts with outlives
| symbolic-debuginfo-7.3.0 | :heavy_check_mark: | `dyn Iterator` |

2020-05-22 19:23 UTC, nikomatsakis commented
OK, my conclusions:

* As expected, there are many valid uses for variance here and it's kind of a shame that we have no solution. Also, this seems to interact with the outlives rules in a few cases in annoying ways, such that you wind up with "unnecessary" errors (in fact, I think both of the unsound cases actually are mostly unsound because of the outlives rules).
* However, I think that the "proper fix" (inferring some sort of variance) is a very involved design that we'd have to think over and I'm not keen to build up arbitrary unsoundness in the meantime.
* I'm not really sure how to do a warning period, it seems like it would be hard, I guess I don't remember how much infrastructure we still have for that sort of thing. The problem is that the right fix (which is embodied in this PR) basically just switches the variance at a high-level place,-- this percolates down and results in various edges in the inference graph, but it's hard to trace them back to this change.

2020-05-22 19:24 UTC, nikomatsakis commented
I suspect we should land this PR, perhaps at the start of a cycle. One thing is that I'm not sure how easy it would be to fix those various crates. Maybe that would be instructive -- we could e.g. try to patch some of them.

2020-05-23 11:29 UTC, Enet4 commented
Owner of `dcmdump` and `dicom-object` here. I may not be able to explain why v0.1.0 of these crates had issues, but the [upstream version in the master branch](https://github.com/Enet4/dicom-rs) seems to have this regression resolved, very likely as a consequence of the heavy refactoring of the `dicom-parser` crate in Enet4/dicom-rs#32.

Here is my attempt at narrowing the changes to the minimum set of commits in this [comparison page](https://github.com/Enet4/dicom-rs/compare/test-case/rustc-regression-71896...test-case/rustc-regression-71896-fix). I'm afraid that this isn't a very good study case, considering their size. Still, I suspect that the `dicom_parser::parser::DynamicDicomParser` type alias is playing a more relevant role here, considering that a lifetime parameter was introduced, which then flowed into other APIs (i.e. `dicom_parser::dataset::read::DataSetReader`, then used by `dicom_object::mem::InMemDicomObject`).

2020-05-26 18:02 UTC, nikomatsakis commented
@Enet4 thanks for the feedback. I guess that's an important data point -- how many of these regressions are taking place in older libraries.

2020-06-08 17:42 UTC, nikomatsakis commented
@bors r+ rollup=never

We decided to do this once the new release is out... and that's now.

I'm marking this as rollup=never because it's a known breaking change and I want to aid in any attempts to bisect regressions.

2020-06-08 17:43 UTC, nikomatsakis commented
Marking for release notes: This is a bugfix with known -- but limited -- impact on extant crates in crates.io.

2020-06-08 18:07 UTC, spastorino commented
ping @skade @Enet4 @shatilov-diman @denoland @getsentry as one or more of your crates as can be seen in [this comment](https://github.com/rust-lang/rust/pull/71896#issuecomment-626287453), are going to regress with this PR merged.

If you have any question do not hesitate to ask here or to jump into [our Zulip instance](https://rust-lang.zulipchat.com) and we can gladly help you to get your crate fixed.

2020-06-08 20:33 UTC, spastorino commented
@bors p=1

2020-06-09 09:17 UTC, nikomatsakis commented
Failure:

```
failures:

---- [ui (nll)] ui/variance/variance-associated-types2.rs stdout ----
diff of stderr:

-	error[E0308]: mismatched types
-	  --> $DIR/variance-associated-types2.rs:13:42
+	error: lifetime may not live long enough
+	  --> $DIR/variance-associated-types2.rs:13:12
3	   |
+	LL | fn take<'a>(_: &'a u32) {
+	   |         -- lifetime `'a` defined here
4	LL |     let _: Box<dyn Foo<Bar = &'a u32>> = make();
-	   |                                          ^^^^^^ lifetime mismatch
+	   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^ type annotation requires that `'a` must outlive `'static`
6	   |
-	   = note: expected trait object `dyn Foo<Bar = &'a u32>`
-	              found trait object `dyn Foo<Bar = &'static u32>`
-	note: the lifetime `'a` as defined on the function body at 12:9...
-	  --> $DIR/variance-associated-types2.rs:12:9
-	   |


failures:
    [ui (nll)] ui/variance/variance-associated-types2.rs
```

2020-06-09 09:17 UTC, nikomatsakis commented
My guess @spastorino is that you need to run `x.py test --bless --compare-mode=nll`

2020-06-09 16:22 UTC, spastorino commented
@bors r=nikomatsakis

2020-06-10 10:19 UTC, nikomatsakis commented
Uh...

@bors retry

2020-06-10 11:05 UTC, Dylan-DPC commented
@bors retry yield

2020-06-11 02:54 UTC, spastorino commented
@bors retry

2020-06-11 02:57 UTC, spastorino commented
@bors retry yield

2020-06-11 08:31 UTC, merged

2020-09-01 15:57 UTC, coolreader18 commented
Here's a piece of code that broke with this:

```rust
fn c_string_array_to_rust<'a>(
    arr: *const *const ::std::os::raw::c_char,
    count: usize,
) -> Box<dyn Iterator<Item = &'a str>> {
    //assert!(!arr.is_null());
    if arr.is_null() {
        Box::new(iter::empty::<&'a str>())
        // ~^ ERROR cannot infer an appropriate lifetime due to conflicting requirements [E0495]
    } else {
        let slice_of_pointers = unsafe { slice::from_raw_parts(arr, count) };
        Box::new(
            slice_of_pointers.iter()
                .map(|s| unsafe { CStr::from_ptr(*s) }.to_str().unwrap()),
        )
    }
}
```
I'm pretty sure this is sound? Since `iter::empty` doesn't never actually produce a value of its `T`

full message:
```
    Checking zware v1.3.1 (/home/coolreader18/dwelo/zware_rs)
error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
  --> src/discovery.rs:76:18
   |
76 |         Box::new(iter::empty::<&'a str>())
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: first, the lifetime cannot outlive the lifetime `'a` as defined on the function body at 70:27...
  --> src/discovery.rs:70:27
   |
70 | fn c_string_array_to_rust<'a>(
   |                           ^^
note: ...so that the expression is assignable
  --> src/discovery.rs:76:18
   |
76 |         Box::new(iter::empty::<&'a str>())
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^
   = note: expected `std::iter::Empty<&str>`
              found `std::iter::Empty<&'a str>`
   = note: but, the lifetime must be valid for the static lifetime...
note: ...so that the expression is assignable
  --> src/discovery.rs:76:9
   |
76 |         Box::new(iter::empty::<&'a str>())
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: expected `std::boxed::Box<(dyn std::iter::Iterator<Item = &'a str> + 'static)>`
              found `std::boxed::Box<dyn std::iter::Iterator<Item = &'a str>>`
```

2020-09-01 15:59 UTC, kennytm commented
@coolreader18 try using `Box<dyn Iterator<Item = &'a str> + 'a>` as the return type of `c_string_array_to_rust`?

2020-09-01 16:12 UTC, coolreader18 commented
I resolved it another way, just wanted to bring this to attention. Thanks for the suggestion though @kennytm, that does fix it as well.

2020-09-03 19:53 UTC, nikomatsakis commented
Just to clarify the problem: 

This is expected. The cause is the same as I explained for ezksd.combinator. In fact, i'm going to inline the hackmd for posterity's sake, since it has a lot more detailed that never made it into a github comment.

# regressions for https://github.com/rust-lang/rust/pull/71896

Crater report: https://crater-reports.s3.amazonaws.com/pr-71896/index.html

## summary

| package | sound-ish? | trait |
| --- | --- | --- |
| ezksd | :x: | `dyn Parser<Input = X>`, but interacts with outlives
| rocket-rooms | :heavy_check_mark: | response::ResultFuture<'r> 
| gribbet.rust_api_example | :heavy_check_mark: | ResultFuture<'static>
| mich101mich.game_rs | :heavy_check_mark: | Iterator
| spacemeowx2.slp-server-rust | :heavy_check_mark: | dyn Stream
| sstanfield.slsh | :heavy_check_mark: | dyn Iterator
| attr-1.0 | :shrug: | unclear
| dcmdump-0.1.0 | :shrug: | unclear
| dicom-object-0.1.0 | :shrug: | unclear, same as previous?
| happy-0.1.0 | :x: | `dyn Parser<Input = X>`, maybe interacts with outlives
| symbolic-debuginfo-7.3.0 | :heavy_check_mark: | `dyn Iterator` |

Key:

* :heavy_check_mark: -- "straightforwardly sound"
* :x: -- not sound
* :shrug: didn't quite figure it out yet

## ezksd.combinator.a2989e2e8fc92c9c8b1b4c949d9d8cc0b4de1986

This one is tricky. The actual interaction of subtyping is unsound. The code is
relying on `Box<dyn Parser<Input = &'static str>>` being a subtype of `Box<dyn
Parser<Input = &'a str>>`, which is incorrect, as `Self::Input` appears in a
*contravariant position*. In other words, effectively, given a fn that requires
`'static` inputs, we are "upcasting" it to a fn that takes any input.

However, the tricky bit is in the *reason* that a `Box<dyn Parser<Input = &'static str>>`
type is required in the first place. This comes about because there is a type like
so used in the `flat_map` combinator:

```
Box<dyn Parser<Input = &'a str, ...>>
```

The problem here is that there is an implicit bound of `Box<dyn Parser<..> +
'static>` going on. The underlying type in this case is something like
`Empty<&'? str>`, where the `'?` is an inference variable. Because of our
outlives rules, that `'?` gets inferred to `'static`. The clincher is that the
`Empty` types does't actually *contain* any data, it's just holding types. We
don't really have a good way to express this today given Rust's outlives rules.

Moreover, if we used the invariant rule that this PR puts in place, *but* we had better
outlives rules, then the code would be accepted.

## githubaccount624.rocket-rooms.181ae13300244f79e7295eff84b3d07f7b28bdd5

The actual error occurs in `rocket`, which is a dependency of `rocket-rooms`:

https://github.com/SergioBenitez/Rocket/blob/e7afd0d1f464b85392051be3a2f382185960ccb8/core/lib/src/response/responder.rs#L218

The relevant code is:

```rust
pub trait Responder<'r> {
    fn respond_to(self, request: &'r Request<'_>) -> response::ResultFuture<'r>;
}


impl Responder<'_> for String {
    fn respond_to(self, _: &Request<'_>) -> response::ResultFuture<'static> {
        Box::pin(async move {
            Response::build()
                .header(ContentType::Plain)
                .sized_body(Cursor::new(self))
                .ok()
        })
    }
}
```

The subtyping is occuring in a covariant position (the return type), so accepting `response::ResultFuture<'static> <: response::ResultFuture<'r>` would be sound if we inferred the variance instead of using `Invariant`.

# gribbet.rust_api_example.6c2086f619b7e3f591cae6a7aa1deed91a504824

The errors are `ResultFuture<'static>` -- the associated type in future is an output that appears in covariant position.

# mich101mich.game_rs.f5e2796d3f8437e9630777e745ed7b8b2a513d30

`Box<dyn Iterator<Item = T>>`, as above

# spacemeowx2.slp-server-rust.2aaf02c7f0a352c6c826c45b6f12f5978604b089

Not a root regression, but related to `dyn futures::Stream<Item = GraphQLResponse<'a, S>`
Not a root regression, but it looks like *maybe* this comes from `Future`? Related to `juniper_subscriptions` 

https://github.com/spacemeowx2/juniper/blob/95686b7ce530538d14bd42aafd47e07989dc9c2a/juniper_subscriptions/src/lib.rs#L149
[log](https://crater-reports.s3.amazonaws.com/pr-71896/try%2396b3c169cd2d8959926fa240f10342f1659f8ae3/gh/spacemeowx2.slp-server-rust/log.txt)

# sstanfield.slsh.b3068a910f91a5bd35b2e2b61a18b5ea18071785

` Box<dyn Iterator<Item = &Expression>>`

# attr-0.1.0

Not totally sure what's going on here but I *think* it's related to `Box<dyn Iterator<...>>` and the implicit `'static` bound. The error occurs in a test:

```
[INFO] [stderr] error[E0597]: `path` does not live long enough
[INFO] [stderr]    --> tests/mapping.rs:197:18
[INFO] [stderr]     |
[INFO] [stderr] 197 |     let result = path.traverse(&top).unwrap().map(std::result::Result::unwrap).collect::<Vec<_>>();
[INFO] [stderr]     |                  ^^^^---------------
[INFO] [stderr]     |                  |
[INFO] [stderr]     |                  borrowed value does not live long enough
[INFO] [stderr]     |                  argument requires that `path` is borrowed for `'static`
[INFO] [stderr] 198 |     assert_eq!(result, vec!["foo", "bla"]);
[INFO] [stderr] 199 | }
[INFO] [stderr]     | - `path` dropped here while still borrowed
```

# dcmdump-0.1.0

Not very clear

```
[INFO] [stderr] error[E0310]: the parameter type `S` may not live long enough
[INFO] [stderr]    --> /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/dicom-object-0.1.0/src/mem.rs:183:18
[INFO] [stderr]     |
[INFO] [stderr] 166 |     pub fn from_reader_with_dict<S>(src: S, dict: D) -> Result<Self>
[INFO] [stderr]     |                                  - help: consider adding an explicit lifetime bound...: `S: 'static`
[INFO] [stderr] ...
[INFO] [stderr] 183 |             obj: InMemDicomObject::build_object(&mut dataset, dict, false, Length::UNDEFINED)?,
[INFO] [stderr]     |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stderr]     |
[INFO] [stderr] note: ...so that the type `std::io::BufReader<S>` will meet its required lifetime bounds
[INFO] [stderr]    --> /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/dicom-object-0.1.0/src/mem.rs:183:18
[INFO] [stderr]     |
[INFO] [stderr] 183 |             obj: InMemDicomObject::build_object(&mut dataset, dict, false, Length::UNDEFINED)?,
[INFO] [stderr]     |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stderr] 
[INFO] [stderr] error: aborting due to previous error
```

# happy

really derives from a use of [combine](https://crates.io/crates/combine) v2.4.0:

```
[INFO] [stderr] error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
[INFO] [stderr]   --> src/parse_route.rs:86:26
[INFO] [stderr]    |
[INFO] [stderr] 86 |     optional(token('/')).and(many1(segment())).map(|(_, v)| v).boxed()
[INFO] [stderr]    |                          ^^^
[INFO] [stderr]    |
[INFO] [stderr] note: first, the lifetime cannot outlive the lifetime `'a` as defined on the function body at 85:8...
[INFO] [stderr]   --> src/parse_route.rs:85:8
[INFO] [stderr]    |
[INFO] [stderr] 85 | fn url<'a>() -> Box<StrParser<'a, Vec<Segment>>> {
[INFO] [stderr]    |        ^^
```

```
type StrParser<'a, R> = combine::Parser<Output=R, Input=&'a str>;
```

looks unsound given [Parser trait](https://docs.rs/combine/2.4.0/combine/trait.Parser.html), possibly a similar pattern to the first

# symbolic-debuginfo-7.3.0 

```
 DynIterator<'_, Symbol<'_>>
 ```