Document From trait for Option implementations
rust-lang/rust pull request #71909
Opened 2020-05-04 23:57 UTC by Dolpheyn

Add documentation for ```From``` trait for ```std::option::Option``` implementations

This PR solves a part of #51430 ( CC @skade )

This is my first PR ever in contributing for OSS. I'm happy to learn and make any changes if necessary :)

2020-05-04 23:57 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @LukasKalbertodt (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2020-05-05 01:47 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-8` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=28383&view=logs&jobId=698b0e4a-0480-533d-81fa-f38599aa328e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/28383/logs/71), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/28383/logs/71)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/fae70460-ef9f-41fe-8ead-4a8b2b44d001.sh

##[section]Finishing: Disable git automatic line ending conversion
##[section]Starting: Checkout rust-lang/rust@refs/pull/71909/merge to s
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
---
##[command]git remote add origin https://github.com/rust-lang/rust
##[command]git config gc.auto 0
##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
##[command]git config --get-all http.proxy
##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/71909/merge:refs/remotes/pull/71909/merge
---
 ---> cb2676f08729
Step 5/8 : ENV RUST_CONFIGURE_ARGS       --build=x86_64-unknown-linux-gnu       --llvm-root=/usr/lib/llvm-8       --enable-llvm-link-shared       --set rust.thin-lto-import-instr-limit=10
 ---> Using cache
 ---> df25ce111862
Step 6/8 : ENV SCRIPT python2.7 ../x.py test --exclude src/tools/tidy &&            python2.7 ../x.py test src/test/mir-opt --pass=build                                   --target=armv5te-unknown-linux-gnueabi &&            python2.7 ../x.py test src/tools/tidy
 ---> 599b9ac96b27
Step 7/8 : ENV NO_DEBUG_ASSERTIONS=1
 ---> Using cache
 ---> 091087e35a36
---
   Compiling rustc_feature v0.0.0 (/checkout/src/librustc_feature)
   Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
   Compiling rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
   Compiling rustc_hir v0.0.0 (/checkout/src/librustc_hir)
   Compiling rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
   Compiling rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
   Compiling rustc_parse v0.0.0 (/checkout/src/librustc_parse)
   Compiling rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
   Compiling rustc_ast_passes v0.0.0 (/checkout/src/librustc_ast_passes)
---
   Compiling rustc_feature v0.0.0 (/checkout/src/librustc_feature)
   Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
   Compiling rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
   Compiling rustc_hir v0.0.0 (/checkout/src/librustc_hir)
   Compiling rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
   Compiling rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
   Compiling rustc_parse v0.0.0 (/checkout/src/librustc_parse)
   Compiling rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
   Compiling rustc_ast_passes v0.0.0 (/checkout/src/librustc_ast_passes)
---
...................i................................................................................ 1800/9986
.................................................................................................... 1900/9986
....................................i............................................................... 2000/9986
.................................................................................................... 2100/9986
..........................iiiii..................................................................... 2200/9986
.................................................................................................... 2400/9986
.................................................................................................... 2500/9986
.................................................................................................... 2600/9986
.................................................................................................... 2700/9986
---
...............i...............i.................................................................... 5100/9986
.................................................................................................... 5200/9986
.............................................................i...................................... 5300/9986
....................................................i............................................... 5400/9986
........................................................ii.ii........i...i.......................... 5500/9986
.................................................................................................i.. 5600/9986
...i................................................................................................ 5800/9986
.......................................ii.....................................i..................... 5900/9986
.................................................................................................... 6000/9986
.................................................................................................... 6100/9986
.................................................................................................... 6100/9986
...........................................................................ii...i..ii...........i... 6200/9986
.................................................................................................... 6400/9986
.................................................................................................... 6500/9986
.................................................................................................... 6600/9986
.................................................................................................... 6600/9986
.......i..ii........................................................................................ 6700/9986
.................................................................................................... 6900/9986
........i........................................................................................... 7000/9986
.................................................................................................... 7100/9986
..................................................i................................................. 7200/9986
---
.................................................................................................... 7900/9986
.................................................................................................... 8000/9986
.................................................................................................... 8100/9986
..................i................................................................................. 8200/9986
........................................................................iiiiii.iiiii.i.............. 8300/9986
.........................i.......................................................................... 8500/9986
.................................................................................................... 8600/9986
.................................................................................................... 8700/9986
.................................................................................................... 8800/9986
---
Suite("src/test/codegen") not skipped for "bootstrap::test::Codegen" -- not in ["src/tools/tidy"]
Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gn [...]

2020-05-05 01:54 UTC, Dolpheyn commented
r? @steveklabnik

2020-05-05 03:05 UTC, rust-highfive commented
The job `x86_64-gnu-llvm-8` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=28386&view=logs&jobId=698b0e4a-0480-533d-81fa-f38599aa328e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/28386/logs/71), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/28386/logs/71)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/b3a4e04b-0c27-4c86-a49a-b796d82b3c87.sh

##[section]Finishing: Disable git automatic line ending conversion
##[section]Starting: Checkout rust-lang/rust@refs/pull/71909/merge to s
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
---
##[command]git remote add origin https://github.com/rust-lang/rust
##[command]git config gc.auto 0
##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
##[command]git config --get-all http.proxy
##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/71909/merge:refs/remotes/pull/71909/merge
---
 ---> cb2676f08729
Step 5/8 : ENV RUST_CONFIGURE_ARGS       --build=x86_64-unknown-linux-gnu       --llvm-root=/usr/lib/llvm-8       --enable-llvm-link-shared       --set rust.thin-lto-import-instr-limit=10
 ---> Using cache
 ---> df25ce111862
Step 6/8 : ENV SCRIPT python2.7 ../x.py test --exclude src/tools/tidy &&            python2.7 ../x.py test src/test/mir-opt --pass=build                                   --target=armv5te-unknown-linux-gnueabi &&            python2.7 ../x.py test src/tools/tidy
 ---> 599b9ac96b27
Step 7/8 : ENV NO_DEBUG_ASSERTIONS=1
 ---> Using cache
 ---> 091087e35a36
---
   Compiling rustc_feature v0.0.0 (/checkout/src/librustc_feature)
   Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
   Compiling rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
   Compiling rustc_hir v0.0.0 (/checkout/src/librustc_hir)
   Compiling rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
   Compiling rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
   Compiling rustc_parse v0.0.0 (/checkout/src/librustc_parse)
   Compiling rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
   Compiling rustc_ast_passes v0.0.0 (/checkout/src/librustc_ast_passes)
---
   Compiling rustc_feature v0.0.0 (/checkout/src/librustc_feature)
   Compiling fmt_macros v0.0.0 (/checkout/src/libfmt_macros)
   Compiling rustc_ast_pretty v0.0.0 (/checkout/src/librustc_ast_pretty)
   Compiling rustc_hir v0.0.0 (/checkout/src/librustc_hir)
   Compiling rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
   Compiling rustc_hir_pretty v0.0.0 (/checkout/src/librustc_hir_pretty)
   Compiling rustc_parse v0.0.0 (/checkout/src/librustc_parse)
   Compiling rustc_ast_lowering v0.0.0 (/checkout/src/librustc_ast_lowering)
   Compiling rustc_ast_passes v0.0.0 (/checkout/src/librustc_ast_passes)
---
...................i................................................................................ 1800/9986
.................................................................................................... 1900/9986
....................................i............................................................... 2000/9986
.................................................................................................... 2100/9986
..........................iiiii..................................................................... 2200/9986
.................................................................................................... 2400/9986
.................................................................................................... 2500/9986
.................................................................................................... 2600/9986
.................................................................................................... 2700/9986
---
...............i...............i.................................................................... 5100/9986
.................................................................................................... 5200/9986
.............................................................i...................................... 5300/9986
....................................................i............................................... 5400/9986
........................................................ii.ii........i...i.......................... 5500/9986
.................................................................................................i.. 5600/9986
...i................................................................................................ 5800/9986
.......................................ii.....................................i..................... 5900/9986
.................................................................................................... 6000/9986
.................................................................................................... 6100/9986
.................................................................................................... 6100/9986
...........................................................................ii...i..ii...........i... 6200/9986
.................................................................................................... 6400/9986
.................................................................................................... 6500/9986
.................................................................................................... 6600/9986
.................................................................................................... 6600/9986
.......i..ii........................................................................................ 6700/9986
.................................................................................................... 6900/9986
........i........................................................................................... 7000/9986
.................................................................................................... 7100/9986
..................................................i................................................. 7200/9986
---
.................................................................................................... 7900/9986
.................................................................................................... 8000/9986
.................................................................................................... 8100/9986
..................i................................................................................. 8200/9986
........................................................................iiiiii.iiiii.i.............. 8300/9986
.........................i.......................................................................... 8500/9986
.................................................................................................... 8600/9986
.................................................................................................... 8700/9986
.................................................................................................... 8800/9986
---
Suite("src/test/codegen") not skipped for "bootstrap::test::Codegen" -- not in ["src/tools/tidy"]
Check compiletest suite=codegen mode=codegen (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gn [...]

2020-05-05 03:24 UTC, Dolpheyn commented
So I have found 2 errors where I wrote the: 1. Comments on the wrong line and 
2. Used the normal formatting ```{}``` instead of the debug one ```{:?}``` when printing ```String```

I have fixed both, but the build pipeline still fails and I don't know what's the cause. I'd appreciate if anyone could help :D

2020-05-10 05:54 UTC, timotree3 commented on src/libcore/option.rs
> +    /// [`map`]: enum.Option.html#method.map
I think you just have to change this line.
```suggestion
    /// [`map`]: ../../std/option/enum.Option.html#method.map
```

The problem is that the current relative link is broken when rendered in the "Implementors" section of the page for `From`

2020-05-10 16:06 UTC, Dolpheyn commented
Thank you very much for helping @timotree3 . It successfully builds now! And I get what you say. So if a method is an implementation of something, the linker cannot resolve relative links even when they're supposedly in the same file? Or it only applies to the `From` implementations section?

2020-05-10 18:34 UTC, timotree3 commented
@Dolpheyn 

> Thank you very much for helping @timotree3 . It successfully builds now!

You're very welcome :)

> And I get what you say. So if a method is an implementation of something, the linker cannot resolve relative links even when they're supposedly in the same file? Or it only applies to the `From` implementations section?

Yeah more or less. When you put a relative link into rust documentation it resolves based on where it gets rendered. Usually that's only on one page, but in this case, because we're implementing a trait, that's two places:

- [In the "Trait Implementations" section for `Option`.](https://doc.rust-lang.org/std/option/enum.Option.html#impl-From%3C%26%27a%20Option%3CT%3E%3E)
- [In the "Implementors" section for `From`.](https://doc.rust-lang.org/std/convert/trait.From.html#impl-From%3C%26%27a%20Option%3CT%3E%3E)

The relative link `enum.Option.html` works on the page for `Option` but doesn't work on the page for `From`.

Does that make it clearer?

P.S. ["Linker"](https://en.wikipedia.org/wiki/Linker_(computing)) means something else entirely.

2020-05-13 13:00 UTC, steveklabnik requested changes
Hey there! Thanks so much for this PR. I'm glad you got the linking bits sorted.

I have a few suggestions for formatting, and one for re-wording, to make these more consistent. With those changes, "r=me" as we say, which means I'm happy to see this merged.

2020-05-13 22:35 UTC, steveklabnik approved these changes
Thanks so much!

@bors: r+ rollup

2020-05-13 22:35 UTC, steveklabnik commented
Oops, I forgot bors doesn't listen to review comments.

@bors: r+ rollup

2020-05-14 06:13 UTC, Dolpheyn commented
@steveklabnik 

Glad to help! I'll have the formats in mind for next time :D

2020-05-14 16:06 UTC, merged