Add Iterator::starts_with
rust-lang/rust pull request #71991
Opened 2020-05-07 19:29 UTC by rcoh

## Justification

I've frequently run into the issue where I want to check the prefix after a filter or map. It's not fundamentally necessary to convert to a `Vec` first, but ergonomically, it's difficult to avoid in practice.

## Usage Examples

```rust
"a b c".chars().filter(|c|!c.is_whitespace()).starts_with("abc".chars())
// vs.
"a b c".chars().filter(|c|!c.is_whitespace()).collect::<String>().starts_with("abc");

(0..1000).starts_with(0..5) //etc.
```
In the benchmarks I ran (patt len = 4) This is approximately:
- 3x faster on ranges
- 10x faster for strings (as in the above example) or for Vec<Char>

If this is something Rust would consider moving forward with, I can benchmark it more extensively. Someone smarter than me may also be able to optimize the implementation.

## Issues
- I'm not sure if there's a better way to do this, but it can take some massaging to get the types to line up properly, eg.

```rust
(0..5).starts_with(&[1,2,3])

3017 |     (0..5).starts_with(&[1,2,3]);
     |            ^^^^^^^^^^^ expected reference, found integer
     |
     = note: expected reference `&{integer}`
                     found type `{integer}`
```

- Currently, it doesn't consume the input iterator, but instead consumes as little of it as possible. I could also imagine that could lead to confusing behavior, and it may be better to simply consume it to prevent surprising results.

2020-05-07 19:29 UTC, rust-highfive commented
r? @withoutboats

(rust_highfive has picked a reviewer for you, use r? to override)

2020-05-07 20:32 UTC, ecstatic-morse commented
Did you consider `take` before `eq`? `starts_with` would indeed work better when the length of the prefix is not known, but I don't think `collect` is the best comparison here.

```rust
(0..5).take(3).eq(0..3)
```

2020-05-07 20:45 UTC, rcoh commented
1. With `take` you need to know the length of the other iterator (but otherwise, it's a good option). Unsurprisingly, the performance is pretty similar (within the margin) in my benchmarks. I think the primary advantage over `eq` is discoverability. You have to be a tiny bit clever (and know that `eq` exists) to think of it. I just found out about it today, tbh. But your first instinct will probably be to look for a method called `starts_with`, and you'll find it.


2. The zip/all method is actually incorrect. It will return `true` for `(0..1)` or even `Iter::empty` (since zip takes the shorter of the 2 iterators).

2020-05-07 20:48 UTC, ecstatic-morse commented
What would `(0..5).starts_with` return when passed `std::iter::once(0)` or `std::iter::empty()`?

2020-05-07 20:50 UTC, rcoh commented
`true` for both. Just to clarify, the bug with `zip/all` is:
```rust
Iter::empty().zip(0..10).all(|(a,b)|a==b) //return true
```

2020-05-07 21:25 UTC, ecstatic-morse commented
I'm sold. You'll want someone from the libs team to sign off on this, however.

2020-05-08 13:34 UTC, the8472 commented on src/libcore/benches/iter.rs
> +}
As a benchmark baseline you might want to compare to a handrolled loop over two slices while using `get_unchecked`.
A longer shared prefix may also help highlighting the iteration cost.

2020-05-08 13:34 UTC, the8472 commented
One alternative would be getting this into the *itertools* crate.

2020-06-02 17:47 UTC, ecstatic-morse commented
Hey @rust-lang/wg-triage. What's the deal here? We should be reassigning things that go this long without an action from the assigned reviewer.

@rust-lang/libs Anyone want to weigh in?

2020-06-02 17:56 UTC, dtolnay requested changes
If we are doing this, I would prefer if it consumed self by value. Using starts_with and then continuing to use the iterator is suspicious. Caller can use `by_ref()` to get the current behavior.

Also it should use PartialEq since Eq is not required.

2020-06-02 18:09 UTC, Dylan-DPC commented
@ecstatic-morse we have less reviewers at the moment, so there's a bit of overload so we are re-assigning in batches. 

r? @Amanieu

2020-06-02 19:00 UTC, rcoh commented
@dtolnay when I made the change to consume self, the method started conflicting with `&str.starts_with` for some reason. Trait priority rules? 

Output of `./x.py check`:
```
error[E0658]: use of unstable library feature 'iter_starts_with': recently added
   --> /home/russell/.cargo/registry/src/github.com-1ecc6299db9ec823/url-2.1.0/src/parser.rs:361:22
    |
361 |             if input.starts_with('#') {
    |                      ^^^^^^^^^^^
    |
    = help: add `#![feature(iter_starts_with)]` to the crate attributes to enable
```

2020-06-05 21:40 UTC, Amanieu commented
It seems that `Input` implements `Iterator` but also has a `starts_with` inherent method. I would have expected the inherent method to take precedence though...

2020-06-16 04:16 UTC, JohnCSimon commented
Ping from triage: 
@rcoh Can you please address or mark off the change request from dtolnay?  thanks.

2020-06-16 22:51 UTC, rcoh commented
I've pushed a change switching it to consume the input. Although `./x.py test --stage 1` passes, `./x.py check` does not -- I'm not sure if it's an issue with `./x.py` check or if it's a real issue. Hopefully the end result of the PR builder will show if it's a real problem or not.

2020-06-16 23:19 UTC, rcoh commented
hmm. This method seemingly takes priority (and then fails to compile) even if I change it to:
```
    fn starts_with<I>(mut self, other: I) -> bool
    where I: Iterator,
    Self::Item: PartialEq<I::Item>,
    Self: Sized
```
I think maybe we should just abandon this? Having under a different name seems kind of silly. 

Unless someone knows a trick to get it to not take priority over inherent methods with the same name?

2020-06-17 00:30 UTC, rust-highfive commented
The job `mingw-check` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=32179&view=logs&jobId=74054d28-c774-5fab-ecc2-352fe71b230e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/32179/logs/65), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/32179/logs/65)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
##[section]Starting: Linux mingw-check
##[section]Starting: Initialize job
Agent name: 'Azure Pipelines 3'
Agent machine name: 'fv-az578'
Current agent version: '2.170.1'
##[group]Operating System
16.04.6
LTS
LTS
##[endgroup]
##[group]Virtual Environment
Environment: ubuntu-16.04
Version: 20200604.1
Included Software: https://github.com/actions/virtual-environments/blob/ubuntu16/20200604.1/images/linux/Ubuntu1604-README.md
##[endgroup]
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.
Download all required tasks.
Downloading task: Bash (3.163.3)
Checking job knob settings.
   Knob: AgentToolsDirectory = /opt/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = /home/vsts/perflog Source: ${VSTS_AGENT_PERFLOG} 
Start tracking orphan processes.
##[section]Finishing: Initialize job
##[section]Starting: Configure Job Name
==============================================================================
---
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/c75f797f-cccc-4137-be6b-cf207e071cd2.sh

##[section]Finishing: Disable git automatic line ending conversion
##[section]Starting: Checkout rust-lang/rust@refs/pull/71991/merge to s
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
---
##[command]git remote add origin https://github.com/rust-lang/rust
##[command]git config gc.auto 0
##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
##[command]git config --get-all http.proxy
##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/71991/merge:refs/remotes/pull/71991/merge
---
 ---> f883e675ad62
Step 6/7 : ENV RUN_CHECK_WITH_PARALLEL_QUERIES 1
 ---> Using cache
 ---> c0b156eb069c
Step 7/7 : ENV SCRIPT python3 ../x.py test src/tools/expand-yaml-anchors &&            python3 ../x.py check --target=i686-pc-windows-gnu --host=i686-pc-windows-gnu &&            python3 ../x.py build --stage 0 src/tools/build-manifest &&            python3 ../x.py test --stage 0 src/tools/compiletest &&            python3 ../x.py test src/tools/tidy &&            python3 ../x.py doc --stage 0 src/libstd &&            /scripts/validate-toolstate.sh
 ---> 8541bab6b38c
Successfully built 8541bab6b38c
Successfully tagged rust-ci:latest
Built container sha256:8541bab6b38c07f1b7eb787539b9cbe93daa6ac4458d3d7bd8a8921622a14ba1
---
    Checking rustc_span v0.0.0 (/checkout/src/librustc_span)
    Checking rustc_errors v0.0.0 (/checkout/src/librustc_errors)
    Checking rustc_feature v0.0.0 (/checkout/src/librustc_feature)
    Checking rustc_parse_format v0.0.0 (/checkout/src/librustc_parse_format)
    Checking chalk-rust-ir v0.10.0
    Checking rustc_query_system v0.0.0 (/checkout/src/librustc_query_system)
    Checking rustc_session v0.0.0 (/checkout/src/librustc_session)
    Checking rustc_hir v0.0.0 (/checkout/src/librustc_hir)
    Checking chalk-solve v0.10.0
    Checking rustc_parse v0.0.0 (/checkout/src/librustc_parse)
---
    Checking serde v1.0.99
    Checking serde_json v1.0.40
    Checking semver v0.9.0
    Checking url v2.1.0
error[E0658]: use of unstable library feature 'iter_starts_with': recently added
    |
    |
361 |             if input.starts_with('#') {
    |
    |
    = help: add `#![feature(iter_starts_with)]` to the crate attributes to enable
error[E0277]: `char` is not an iterator
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/url-2.1.0/src/parser.rs:361:34
    |
    |
361 |             if input.starts_with('#') {
    |                                  ^^^ `char` is not an iterator
    = help: the trait `std::iter::Iterator` is not implemented for `char`
    = note: required because of the requirements on the impl of `std::iter::IntoIterator` for `char`


error[E0658]: use of unstable library feature 'iter_starts_with': recently added
    |
    |
379 |         if input.is_empty() || !input.starts_with(ascii_alpha) {
    |
    |
    = help: add `#![feature(iter_starts_with)]` to the crate attributes to enable

error[E0277]: `fn(char) -> bool {parser::ascii_alpha}` is not an iterator
    |
    |
379 |         if input.is_empty() || !input.starts_with(ascii_alpha) {
    |                                                   ^^^^^^^^^^^ `fn(char) -> bool {parser::ascii_alpha}` is not an iterator
    |
    = help: the trait `std::iter::Iterator` is not implemented for `fn(char) -> bool {parser::ascii_alpha}`
    = note: required because of the requirements on the impl of `std::iter::IntoIterator` for `fn(char) -> bool {parser::ascii_alpha}`

error[E0658]: use of unstable library feature 'iter_starts_with': recently added
    |
    |
411 |                 self.log_violation_if(ExpectedFileDoubleSlash, || !input.starts_with("//"));
    |
    |
    = help: add `#![feature(iter_starts_with)]` to the crate attributes to enable
error[E0277]: `&str` is not an iterator
   --> /cargo/registry/src/github.com-1ecc6299db9ec823/url-2.1.0/src/parser.rs:411:86
    |
    |
411 |                 self.log_violation_if(ExpectedFileDoubleSlash, || !input.starts_with("//"));
    |                                                                                      ^^^^ `&str` is not an iterator; try calling `.chars()` or `.bytes()`
    = help: the trait `std::iter::Iterator` is not implemented for `&str`
    = note: required because of the requirements on the impl of `std::iter::IntoIterator` for `&str`

error: aborting due to 6 previous errors
---
  local time: Tue Jun 16 23:00:16 UTC 2020
  network time: Tue, 16 Jun 2020 23:00:16 GMT
== end clock drift check ==

##[error]Bash exited with code '1'.
##[section]Finishing: Run build
##[section]Starting: Checkout rust-lang/rust@refs/pull/71991/merge to s
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
Cleaning any cached credential from repository: rust-lang/rust (GitHub)
##[section]Finishing: Checkout rust-lang/rust@refs/pull/71991/merge to s
Cleaning up task key
Start cleaning up orphan processes.
Terminate orphan process: pid (3382) (python)
##[section]Finishing: Finalize Job
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@rust-lang/infra`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2020-06-20 17:44 UTC, LukasKalbertodt commented
> I would have expected the inherent method to take precedence though...

The problem is that [`Input::starts_with`](https://github.com/servo/rust-url/blob/55395ed3099b26a58a82f6fef09e609d52b674b3/src/parser.rs#L249) has `&self` as receiver type. This PR was changed from `&mut self` to `self` as receiver type. In [the relevant code snippet](https://github.com/servo/rust-url/blob/55395ed3099b26a58a82f6fef09e609d52b674b3/src/parser.rs#L378-L385), `input.starts_with()` is called where `input` has the type `Input` (no reference). In that case, `Iterator::starts_with` is a perfect fit as the compiler does not need to perform autoref-coercion. For the inherent method, autoref would need to be performed to transform `input` into the right receiver type. Inherent methods are preferred over trait ones, but only if both require the same number of type coercion steps.

I don't think we can fix this: adding methods to traits always comes at the risk of clashing with inherent methods, unfortunately. Even with `Iterator::starts_with(&mut self)` (as initially proposed), we could break existing crates. 

This change could still land, if we think that its benefit outweighs the breakage. Might be worth running crater.

2020-06-22 03:57 UTC, rcoh commented
Makes sense. I case the only foolproof way to make a change like this is to create a new trait eg. `IterStartsWith` so that it can only be brought into scope with explicit import.

Slightly worse from an auto-complete discoverability perspective, but it would still get suggested as an import if you did `some_iter.starts_with(another_iter)` I think?

2020-07-07 05:57 UTC, JohnCSimon commented
Ping from triage:
@rcoh - This PR appears to have stalled, can you please address the change request from dtolnay? Thanks.

2020-07-22 14:03 UTC, closed without merging

2020-07-25 11:04 UTC, LukasKalbertodt commented
@rcoh Did you lose interest in this PR? As I said, if the benefits outweigh the breakage, we can still land this. And at least some people, including me, think it's a good addition to `Iterator`.

If you still want to continue with this PR, you could push a version with `mut self` (consuming self, as dtolnay suggested) and we could let crater run to test how many crates this change would break in the ecosystem. Then the libs team can discuss the results.

2020-07-25 13:13 UTC, rcoh commented
That's fine with me actually, one of the commits has the change to mut self, I can push that version. As I suggested in a comment above, we could also move it into a separate trait.

2020-08-25 19:18 UTC, LukasKalbertodt commented
I'm sorry, took me quite long to finally take another look at this. I experimented with this locally and changed a few things (mostly the method taking `self` by value). I committed those things and you can find the commit [on my branch](https://github.com/LukasKalbertodt/rust/tree/iterator-startswith) (that was faster than telling you what to change via review comments).

`x.py test` (the full thing) finishes successfully, while `x.py check` indeed fails in the "Checking clippy artifacts" step. This is due to the `url` crate, which clippy depends on. 

My idea on how to proceed with this PR, if you still want to:
- Fetch my commit and squash it into yours (no need to `Co-author` me, those were just trivial changes)
- Reopen this PR and then force-push (do not force push before reopening!) OR open a new PR.
- If CI is not green (not sure if it only runs `test` or also `check`), we need to patch `url` in a fork and then `[patch]` `clippy` with the new version. 
- Once CI is green, we can `bors try` and then run crater to see how many crates would fail to compile with `starts_with` added.
- Then we can discuss whether it's worth adding.