Clean up E0590 explanation
rust-lang/rust pull request #72235
Opened 2020-05-15 16:26 UTC by GuillaumeGomez

r? @Dylan-DPC

2020-05-16 23:24 UTC, Dylan-DPC-zz requested changes

2020-05-16 23:24 UTC, Dylan-DPC commented on src/librustc_error_codes/error_codes/E0590.md
> +`break` or `continue` keywords were used in a `while` loop condition without a
```suggestion
`break` or `continue` keywords were used in a condition of a `while` loop without a
```

2020-05-22 11:28 UTC, GuillaumeGomez commented
Updated!

2020-05-22 13:22 UTC, Dylan-DPC commented
@bors r+ rollup

2020-05-22 19:09 UTC, merged