core/time: Add Duration methods for zero
rust-lang/rust pull request #72790
Opened 2020-05-30 18:59 UTC by jonhoo

This patch adds two methods to `Duration`. The first, `Duration::zero`,
provides a `const` constructor for getting an zero-length duration. This
is also what `Default` provides (this was clarified in the docs), though
`default` is not `const`.

The second, `Duration::is_zero`, returns true if a `Duration` spans no
time (i.e., because its components are all zero). Previously, the way to
do this was either to compare both `as_secs` and `subsec_nanos` to 0, to
compare against `Duration::new(0, 0)`, or to use the `u128` method
`as_nanos`, none of which were particularly elegant.

2020-05-30 18:59 UTC, rust-highfive commented
r? @hanna-kruppe

(rust_highfive has picked a reviewer for you, use r? to override)

2020-05-30 18:59 UTC, jonhoo commented
I considered using "immediate" instead of "zero", but figured the latter was both shorter and (perhaps) more intuitive, even though the former is more technically accurate. Happy to change that though.

2020-05-31 08:52 UTC, marmeladema commented
On a similar subject, I wanted to do a PR for `MIN` and `MAX` associated const which would be very much like your `zero` for the `MIN` case I believe. Then you could just compare with `MIN` to replace `is_zero`.

2020-05-31 08:56 UTC, hanna-kruppe commented
Punting to randomly chosen T-libs person because I'm currently too busy: r? @LukasKalbertodt

2020-05-31 18:46 UTC, jonhoo commented
@marmeladema It feels a little odd to me to have `MIN` for `Duration` and have it be zero. Because, at least in theory (though not currently in practice), a duration can be negative in length. `ZERO`, to me, is a distinct value from the `MIN`, which is the smallest representable value.

2020-05-31 19:28 UTC, marmeladema commented
>  It feels a little odd to me to have MIN for Duration and have it be zero. Because, at least in theory (though not currently in practice), a duration can be negative in length. ZERO, to me, is a distinct value from the MIN, which is the smallest representable value.

That's fair :) `ZERO` could be an associated const though no? I am _not at all_ a T-libs person just a random contributor.

2020-06-01 12:47 UTC, jonhoo commented
Oh, yes, completely agree that `ZERO` could instead be an associated const! I'll leave that call up to the reviewers — I don't have a strong preference either way.

2020-06-20 11:32 UTC, LukasKalbertodt requested changes
Sorry for the long delay!

I am all in for adding these methods. I am not sure if you are aware, but there was [an RFC about exactly these methods](https://github.com/rust-lang/rfcs/pull/2814). It was only closed because such a small change does not require an RFC. 

`ZERO` as associated constant was discussed as well. I don't oppose it, but I think the `zero` associated function is what I would try out first. These kinds of "constructor functions" are pretty common, so I don't think adding this would hurt. The constant can still be added later.

(And for the protocol, this feature is so small that I think the doc tests are absolutely sufficient and we don't need extra tests.)

I also created a tracking issue: https://github.com/rust-lang/rust/issues/73544
Please add its ID to the `#[unstable]` attribute.

Thanks!

2020-06-20 11:32 UTC, LukasKalbertodt commented on src/libcore/time.rs
> +    /// assert!(IMMEDIATELY.is_zero());
I don't think the `const` example adds a lot here. I would rather add an `assert_eq!(duration.as_nanos(), 0)` or something like that.

2020-06-20 11:32 UTC, LukasKalbertodt commented on src/libcore/time.rs
> +    }
Please put this whole method directly after `new` (and before `from_secs`). I think that's a better spot when looking at the documentation.

2020-06-20 14:56 UTC, jonhoo commented
Oh, nice, didn't know about that RFC! I've revised according to your comments. Thanks for creating the tracking issue :)

2020-06-20 16:03 UTC, LukasKalbertodt approved these changes

2020-06-20 16:03 UTC, LukasKalbertodt commented
@bors r+

2020-06-20 16:04 UTC, LukasKalbertodt commented
CC @ghost in case you didn't see this PR implementing your RFC.

2020-06-21 02:20 UTC, merged