Use preinstalled msys2
rust-lang/rust pull request #73188
Opened 2020-06-09 22:51 UTC by mati865

r? @ghost

2020-06-09 23:00 UTC, rust-highfive commented
The job `x86_64-mingw-1` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=31579&view=logs&jobId=b1e7928f-7d26-57cb-a49e-81353e6c69ce) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/31579/logs/31), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/31579/logs/31)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
##[section]Starting: Windows x86_64-mingw-1
##[section]Starting: Initialize job
Agent name: 'Azure Pipelines 4'
Agent machine name: 'fv-az363'
Current agent version: '2.170.1'
##[group]Operating System
10.0.14393
Datacenter
Datacenter
##[endgroup]
##[group]Virtual Environment
Environment: windows-2016
Version: 20200531.1
Included Software: https://github.com/actions/virtual-environments/blob/win16/20200531.1/images/win/Windows2016-Readme.md
##[endgroup]
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Download all required tasks.
Downloading task: Bash (3.163.3)
Checking job knob settings.
   Knob: AgentToolsDirectory = C:/hostedtoolcache/windows Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = c:\vsts\perflog Source: ${VSTS_AGENT_PERFLOG} 
Start tracking orphan processes.
##[section]Finishing: Initialize job
##[section]Starting: Configure Job Name
==============================================================================
---
========================== Starting Command Output ===========================
[command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc /d/a/_temp/e9b3ccd2-ab36-416c-a8a6-c247f7fd54ac.sh

##[section]Finishing: Disable git automatic line ending conversion
##[section]Starting: Checkout rust-lang/rust@refs/pull/73188/merge to s
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
---
##[command]git remote add origin https://github.com/rust-lang/rust
##[command]git config gc.auto 0
##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
##[command]git config --get-all http.proxy
##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/73188/merge:refs/remotes/pull/73188/merge
---
configure: 
configure: run `python D:\a\1\s/x.py --help`
configure: 
Attempting with retry: make prepare
      1 [main] make (2824) C:\msys64\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x180317408/0x18033E408.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Command failed. Attempt 2/5:
      0 [main] make (1200) C:\msys64\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x180317408/0x18033E408.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Command failed. Attempt 3/5:
      0 [main] make (4700) C:\msys64\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x180317408/0x18033E408.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Command failed. Attempt 4/5:
      0 [main] make (4748) C:\msys64\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x180317408/0x18033E408.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Command failed. Attempt 5/5:
      0 [main] make (820) C:\msys64\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x180317408/0x18033E408.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
The command has failed after 5 attempts.
== clock drift check ==
  local time: Tue Jun  9 23:00:33 CUT 2020
  network time: Tue, 09 Jun 2020 23:00:33 GMT
== end clock drift check ==

##[error]Bash exited with code '1'.
##[section]Finishing: Run build
##[section]Starting: Checkout rust-lang/rust@refs/pull/73188/merge to s
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
Cleaning any cached credential from repository: rust-lang/rust (GitHub)
##[section]Finishing: Checkout rust-lang/rust@refs/pull/73188/merge to s
Cleaning up task key
Start cleaning up orphan processes.
Terminate orphan process: pid (4068) (python)
Terminate orphan process: pid (1736) (sccache)
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@rust-lang/infra`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2020-06-09 23:05 UTC, rust-highfive commented
The job `x86_64-mingw-1` of your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=31580&view=logs&jobId=b1e7928f-7d26-57cb-a49e-81353e6c69ce) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/31580/logs/31), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/31580/logs/31)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
##[section]Starting: Windows x86_64-mingw-1
##[section]Starting: Initialize job
Agent name: 'Azure Pipelines 2'
Agent machine name: 'fv-az425'
Current agent version: '2.170.1'
##[group]Operating System
10.0.14393
Datacenter
Datacenter
##[endgroup]
##[group]Virtual Environment
Environment: windows-2016
Version: 20200531.1
Included Software: https://github.com/actions/virtual-environments/blob/win16/20200531.1/images/win/Windows2016-Readme.md
##[endgroup]
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Download all required tasks.
Downloading task: Bash (3.163.3)
Checking job knob settings.
   Knob: AgentToolsDirectory = C:/hostedtoolcache/windows Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = c:\vsts\perflog Source: ${VSTS_AGENT_PERFLOG} 
Start tracking orphan processes.
##[section]Finishing: Initialize job
##[section]Starting: Configure Job Name
==============================================================================
---
========================== Starting Command Output ===========================
[command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc /d/a/_temp/d888ca66-b87d-45dc-a87e-f473ae90710e.sh

##[section]Finishing: Disable git automatic line ending conversion
##[section]Starting: Checkout rust-lang/rust@refs/pull/73188/merge to s
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
---
##[command]git remote add origin https://github.com/rust-lang/rust
##[command]git config gc.auto 0
##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
##[command]git config --get-all http.proxy
##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/73188/merge:refs/remotes/pull/73188/merge
---
configure: 
configure: run `python D:\a\1\s/x.py --help`
configure: 
Attempting with retry: make prepare
      1 [main] make (3968) C:\msys64\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x180317408/0x18033E408.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Command failed. Attempt 2/5:
      0 [main] make (2332) C:\msys64\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x180317408/0x18033E408.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Command failed. Attempt 3/5:
      0 [main] make (3116) C:\msys64\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x180317408/0x18033E408.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Command failed. Attempt 4/5:
      0 [main] make (5508) C:\msys64\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x180317408/0x18033E408.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
Command failed. Attempt 5/5:
      1 [main] make (4320) C:\msys64\usr\bin\make.exe: *** fatal error - cygheap base mismatch detected - 0x180317408/0x18033E408.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
The command has failed after 5 attempts.
== clock drift check ==
  local time: Tue Jun  9 23:05:47 CUT 2020
  network time: Tue, 09 Jun 2020 23:05:47 GMT
== end clock drift check ==

##[error]Bash exited with code '1'.
##[section]Finishing: Run build
##[section]Starting: Checkout rust-lang/rust@refs/pull/73188/merge to s
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
Author       : Microsoft
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=798199)
==============================================================================
Cleaning any cached credential from repository: rust-lang/rust (GitHub)
##[section]Finishing: Checkout rust-lang/rust@refs/pull/73188/merge to s
Cleaning up task key
Start cleaning up orphan processes.
Terminate orphan process: pid (3876) (python)
Terminate orphan process: pid (5988) (sccache)
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@rust-lang/infra`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2020-06-09 23:08 UTC, rust-highfive commented
Your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=31582&view=logs&jobId=b1e7928f-7d26-57cb-a49e-81353e6c69ce) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/31582/logs/27), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/31582/logs/27)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
##[section]Starting: Windows x86_64-mingw-1
##[section]Starting: Initialize job
Agent name: 'Azure Pipelines 8'
Agent machine name: 'fv-az172'
Current agent version: '2.170.1'
##[group]Operating System
10.0.14393
Datacenter
Datacenter
##[endgroup]
##[group]Virtual Environment
Environment: windows-2016
Version: 20200531.1
Included Software: https://github.com/actions/virtual-environments/blob/win16/20200531.1/images/win/Windows2016-Readme.md
##[endgroup]
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Download all required tasks.
Downloading task: Bash (3.163.3)
Checking job knob settings.
   Knob: AgentToolsDirectory = C:/hostedtoolcache/windows Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = c:\vsts\perflog Source: ${VSTS_AGENT_PERFLOG} 
Start tracking orphan processes.
##[section]Finishing: Initialize job
##[section]Starting: Configure Job Name
==============================================================================
---
========================== Starting Command Output ===========================
[command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc /d/a/_temp/91565528-0e72-4930-a2fb-77588821d000.sh

##[section]Finishing: Disable git automatic line ending conversion
##[section]Starting: Checkout rust-lang/rust@refs/pull/73188/merge to s
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
---
##[command]git remote add origin https://github.com/rust-lang/rust
##[command]git config gc.auto 0
##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
##[command]git config --get-all http.proxy
##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/73188/merge:refs/remotes/pull/73188/merge
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@rust-lang/infra`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2020-06-10 09:26 UTC, mati865 commented
r? @pietroalbini 

Successful CI builds: https://dev.azure.com/rust-lang/rust/_build/results?buildId=31583&view=logs&j=b1e7928f-7d26-57cb-a49e-81353e6c69ce and https://github.com/rust-lang/rust/pull/73188/checks?check_run_id=755856941

2020-06-11 13:00 UTC, emilyalbini requested changes

2020-06-11 13:00 UTC, pietroalbini commented on src/ci/scripts/install-msys2-packages.sh
>      # Detect the native Python version installed on the agent. On GitHub
Can you fold this whole file in the `install-msys2.sh` script? The only reason this was executed in a separate script was incompatibilities with git bash and msys2's bash, and that's not a problem anymore.

2020-06-11 14:51 UTC, rust-highfive commented
Your PR [failed](https://dev.azure.com/rust-lang/rust/_build/results?buildId=31711&view=logs&jobId=74054d28-c774-5fab-ecc2-352fe71b230e) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/31711/logs/38), [raw log](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/31711/logs/38)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
##[section]Starting: Linux mingw-check
##[section]Starting: Initialize job
Agent name: 'Azure Pipelines 5'
Agent machine name: 'fv-az578'
Current agent version: '2.170.1'
##[group]Operating System
16.04.6
LTS
LTS
##[endgroup]
##[group]Virtual Environment
Environment: ubuntu-16.04
Version: 20200604.1
Included Software: https://github.com/actions/virtual-environments/blob/ubuntu16/20200604.1/images/linux/Ubuntu1604-README.md
##[endgroup]
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.
Download all required tasks.
Downloading task: Bash (3.163.3)
Checking job knob settings.
   Knob: AgentToolsDirectory = /opt/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = /home/vsts/perflog Source: ${VSTS_AGENT_PERFLOG} 
Start tracking orphan processes.
##[section]Finishing: Initialize job
##[section]Starting: Configure Job Name
==============================================================================
---
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/c4edaf9c-fb3a-471e-9b7e-32fb9e928453.sh

##[section]Finishing: Disable git automatic line ending conversion
##[section]Starting: Checkout rust-lang/rust@refs/pull/73188/merge to s
Task         : Get sources
Description  : Get sources from a repository. Supports Git, TfsVC, and SVN repositories.
Version      : 1.0.0
Author       : Microsoft
---
##[command]git remote add origin https://github.com/rust-lang/rust
##[command]git config gc.auto 0
##[command]git config --get-all http.https://github.com/rust-lang/rust.extraheader
##[command]git config --get-all http.proxy
##[command]git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=2 origin +refs/heads/*:refs/remotes/origin/* +refs/pull/73188/merge:refs/remotes/pull/73188/merge
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@rust-lang/infra`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2020-06-11 14:58 UTC, mati865 commented
BTW there is bug when running `./x.py run src/tools/expand-yaml-anchors` on Windows:
```
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index 355f2829215..2d62df39459 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,7 +5,7 @@
 # This file was automatically generated by the expand-yaml-anchors tool. The
 # source file that generated this one is:
 #
-#   src/ci/github-actions/ci.yml
+#   src/ci/github-actions\ci.yml
 #
 # Once you make changes to that file you need to run:
 #
```

2020-06-11 15:46 UTC, pietroalbini commented
This looks good now! Thanks!

@bors r+ rollup=never

> BTW there is bug when running ./x.py run src/tools/expand-yaml-anchors on Windows:

Oh that's bad, do you have the time to open a PR fixing that?

2020-06-11 15:57 UTC, mati865 commented
> Oh that's bad, do you have the time to open a PR fixing that?

I'll look into `expand-yaml-anchors` code and open PR or issue depending on how long it takes to fix it 😄

2020-06-11 15:58 UTC, pietroalbini commented
> I'll look into expand-yaml-anchors code and open PR or issue depending on how long it takes to fix

I'm happy to mentor: if you need any help feel free to ping me wherever.

2020-06-11 17:48 UTC, mati865 commented
Damn, I think I saw open issue about it but there are dozens of them when searching for `path label:O-windows`:
```
use std::path::Path;

fn main() {
    let path = Path::new("/tmp/foo").join("bar.rs");
    println!("{}", path.display());
}
```
This gives:
```
$ rustc test.rs && ./test.exe
/tmp/foo\bar.rs
```

2020-06-14 01:30 UTC, Dylan-DPC commented
@bors p=1

2020-06-14 06:42 UTC, merged