Test that bounds checks are elided when slice len is checked up-front
rust-lang/rust pull request #73362
Opened 2020-06-15 05:06 UTC by erikdesjardins

Closes #69101

2020-06-15 05:06 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @nikomatsakis (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md) for more information.

2020-06-15 17:24 UTC, nikomatsakis requested changes

2020-06-15 17:24 UTC, nikomatsakis commented on src/test/codegen/issue-69101-bounds-check.rs
> +#![crate_type = "lib"]
Can you add a comment explaining what this test is testing?

2020-06-16 10:33 UTC, nikomatsakis approved these changes

2020-06-16 10:33 UTC, nikomatsakis commented
@bors r+ rollup

2020-06-17 16:49 UTC, tmiasko commented
<details><summary>Failed in #73438 on x86_64-gnu which enables debug assertions in std.</summary>

```
---- [codegen] codegen/issue-69101-bounds-check.rs stdout ----

error: verification with 'FileCheck' failed
status: exit code: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/llvm/build/bin/FileCheck" "--input-file" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/issue-69101-bounds-check/issue-69101-bounds-check.ll" "/checkout/src/test/codegen/issue-69101-bounds-check.rs"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
/checkout/src/test/codegen/issue-69101-bounds-check.rs:15:16: error: CHECK-NOT: excluded string found in input
 // CHECK-NOT: panic_bounds_check
               ^
/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/issue-69101-bounds-check/issue-69101-bounds-check.ll:141:25: note: found here
; call core::panicking::panic_bounds_check
                        ^~~~~~~~~~~~~~~~~~
/checkout/src/test/codegen/issue-69101-bounds-check.rs:26:16: error: CHECK-NOT: excluded string found in input
 // CHECK-NOT: panic_bounds_check
               ^
/checkout/obj/build/x86_64-unknown-linux-gnu/test/codegen/issue-69101-bounds-check/issue-69101-bounds-check.ll:264:25: note: found here
; call core::panicking::panic_bounds_check
                        ^~~~~~~~~~~~~~~~~~

------------------------------------------
```
</details>

2020-06-17 17:11 UTC, erikdesjardins commented
Sorry about that. Added (I hope) the right annotation to ignore those builds

2020-06-18 16:23 UTC, nikomatsakis commented
@bors r+ rollup

2020-06-19 12:12 UTC, merged