Fix Clippy handling of `ExpnKind::Desugard`
rust-lang/rust pull request #73468
Opened 2020-06-18 04:50 UTC by Aaron1011

PR #72389 exposed a latent issue in Clippy: only the top-most `ExpnKind` was checked for `ExpnKind::Macro` or `ExpnKind::AstPass`. Under certain circumstances, this could result in Clippy emitting warnings for code produced by a macro expansion, due to the topmost `ExpnId` having `ExpnKind::Desugaring`.

This PR tracks the presence of `ExpnKind::Macro` and `ExpnKind::AstPass` in the `call_site` chain through a new `ClosestAstOrMacro`. This enum is used in Clippy, allowing all of Clippy's UI tests to pass. As a result, we can re-enable Clippy tests in `src/bootstrap/test.rs`

2020-06-18 04:50 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2020-06-18 04:50 UTC, Aaron1011 commented
cc @flip1995 @nikomatsakis @Manishearth

2020-06-18 05:01 UTC, Manishearth approved these changes
clippy side looks great, thanks!

2020-06-18 11:37 UTC, flip1995 approved these changes

2020-06-18 14:17 UTC, flip1995 commented
Hm, there is still the `empty_line_after_outer_attribute.rs` clippy test, that fails because of something related to proc_macros (it seems).

Also it seems, that Clippy is not tested on `CI / PR` runs, but only on `CI / auto` runs. I think we should change that in the future, but this is probably something for a different PR.

2020-06-18 15:43 UTC, nikomatsakis requested changes

2020-06-18 15:43 UTC, nikomatsakis commented on src/librustc_span/hygiene.rs
> +    pub fn closest_ast_or_macro(self) -> ClosestAstOrMacro {
I think a comment would be good here, even if it just instructs people to visit the `ClosestAstOrMacro` type for more information

2020-06-18 15:44 UTC, nikomatsakis commented
r=me with nit, but @petrochenkov self-assigned, so probably good to wait for them to weigh in

r? @petrochenkov

2020-06-18 21:29 UTC, Aaron1011 commented
@flip1995: The `ui/empty_line_after_outer_attribute.rs` test is passing locally for me with this branch.

2020-06-20 17:55 UTC, petrochenkov commented
I haven't seen https://github.com/rust-lang/rust/pull/72389 but it appears to be a serious misuse of expansions.
I was pinged on that PR, but unfortunately didn't notice that something named "explain move errors" makes changes to entirely unrelated parts of the compiler.

I need to look at https://github.com/rust-lang/rust/pull/72389 in more detail and see what it does and whether it can be done without hacks.

(That said, `in_external_macro` and friends are also a mess.)

2020-06-20 18:02 UTC, petrochenkov commented
I would personally prefer to revert https://github.com/rust-lang/rust/pull/72389 in the meantime and fix clippy.
Otherwise this unexpected task really messes up my work queue and it would be great to delay it until mid-July.

2020-06-20 18:10 UTC, Manishearth commented
Yeah like I said before diagnostics should not take priority over existing functionality

2020-06-20 21:23 UTC, Aaron1011 commented
> I haven't seen #72389 but it appears to be a serious misuse of expansions.

@petrochenkov: Can you elaborate on this? While operators are not 'desugared' in the same way that 'if' statements and 'for' loops are desugared (operators are desugared during MIR building, rather than AST lowering), I believe it fits the way that way that `DesugaringKind` is used. For both 'for' loops and operators, we have non-user-written method calls being inserted, which can be distinguished from explicit calls (`iter.into_iter()`, `foo.add(rhs)`) by examining the `Span`.

2020-06-20 21:42 UTC, Manishearth commented
MIR desugaring is not the same as the source-to-source desugaring that occurs in `if let`, MIR is not rust source. DesugaringKind is specifically for stuff that behaves like macros, and that's why it's a part of spans/etc. MIR does _all kinds_ of transforms; closures become structs, etc, at best you should have a different mechanism for tracking that.

When it comes to diagnostics source-to-source transforms are the ones that cause the most pain and that's why they're handled this way.

I hadn't looked closely at this before but now that I look through it I find myself agreeing with @petrochenkov, it's a mistake to lump MIR transforms into DesugaringKind.

2020-06-21 02:16 UTC, Aaron1011 commented
@Manishearth @petrochenkov: PR https://github.com/rust-lang/rust/pull/73571 is up, which reverts just the operator desugaring changes.

2020-06-21 10:47 UTC, petrochenkov commented
Closing in favor of the revert.

2020-06-23 04:51 UTC, Aaron1011 commented
Now that the revert has landed in https://github.com/rust-lang/rust/pull/73594, I think we should consider landing this. Clippy's current method detecting macro expansions is very fragile - any additional `ExpnKind::Desugaring`s that we apply may trigger the underlying issue that necessitated the revert.

2020-06-23 05:16 UTC, Manishearth commented
So I still don't understand how this would lead to a false positive in clippy: could you give an example?

2020-06-23 05:17 UTC, Manishearth commented
Like, overall AST desugarings are pretty rare, and it's basically only the initial few that have always existed. Changes to desugarings necessitate changes in Clippy _anyway_ since sometimes we need to un-desugar them.

2020-07-26 13:20 UTC, petrochenkov commented
I'm going to close this for now, with https://github.com/rust-lang/rust/pull/72389 reverted it's not super urgent, and I'd like to consider eliminating lowering-time expansions entirely.

2020-07-26 13:20 UTC, closed without merging