Add docs for intra-doc-links
rust-lang/rust pull request #73810
Opened 2020-06-27 19:14 UTC by Manishearth

Fixes https://github.com/rust-lang/rust/issues/66000

2020-06-27 19:14 UTC, rust-highfive commented
r? @GuillaumeGomez

(rust_highfive has picked a reviewer for you, use r? to override)

2020-06-29 12:46 UTC, jyn514 requested changes
This should mention which scope is used to resolve the links: the parent module of the item. In the case of macros this is the crate root; in the case of re-exports it is the original module; in the case of impls I believe it's the parent of the type (but not sure).

2020-06-29 15:21 UTC, Manishearth commented
@jyn514 isn't it just the def site scope? I don't think there's any special scoping here

2020-06-29 17:29 UTC, jyn514 commented
Sure, it's obvious to us because we implemented it, but it's not obvious to everyone else. See e.g. https://github.com/rust-lang/rust/issues/72243 which is a bug report that macros aren't resolved using lexical scope instead of resolution scope.

2020-06-29 17:55 UTC, Manishearth commented
@jyn514 Oh, I do consider that special scoping, I wasn't aware of that. For everything else it's just the def site scope though. I think we can mention that `macro_rules` are scoped differently

2020-06-29 17:58 UTC, Manishearth commented
Added a note. We'll be deprecating macro_rules anyway so I don't think we should do much more here

2020-07-09 15:26 UTC, GuillaumeGomez commented on src/doc/rustdoc/src/intra-doc-links.md
> +
Please remove this empty line.

2020-07-09 15:27 UTC, GuillaumeGomez commented
Overall, it is nice. Could you also add the fact that using `crate::` or paths more generally work just like imports too please?

2020-07-09 15:31 UTC, Manishearth commented on src/doc/rustdoc/src/intra-doc-links.md
> +
```suggestion
```

2020-07-09 15:33 UTC, closed without merging