Use italics for O notation
rust-lang/rust pull request #74010
Opened 2020-07-03 19:18 UTC by pierwill

In documentation, I think it makes sense to italicize O notation as opposed to using back-ticks. Visually, back-ticks focus the reader on the literal characters being used, making them ideal for representing code. Using italics, as far I can tell, more closely follows typographic conventions in mathematics and computer science.

Just a suggestion, of course! 😇

2020-07-03 19:18 UTC, rust-highfive commented
r? @Mark-Simulacrum

(rust_highfive has picked a reviewer for you, use r? to override)

2020-07-04 00:42 UTC, Mark-Simulacrum commented
I'm going to tentatively cc @rust-lang/rustdoc and r? @GuillaumeGomez here, I guess this is more in "docs" territory but that doesn't currently exist.

2020-07-04 05:24 UTC, CAD97 commented
As I understand it, it would be Most Correct to use actual math markup for big-O notation, whether with [MathML](https://en.wikipedia.org/wiki/MathML) directly, faux-LaTeX (pre)processors like [MathJax](https://www.mathjax.org/) or [KaTeX](https://katex.org/), or even some ad-hoc markup.

Here's an example set with KaTeX: 
![image](https://user-images.githubusercontent.com/5992217/86505565-4a71c180-bd94-11ea-85dc-13142b21cbb0.png)

Or with the alt stylization:
![image](https://user-images.githubusercontent.com/5992217/86505571-66756300-bd94-11ea-85f6-b64f860ce719.png)

And the different variants easily usable in markdown:

```markdown
`O(n)`
`O(n log n)`

*O(n)*
*O(n log n)*

*O*(*n*)
*O*(*n* log *n*)
```

> `O(n)`
> `O(n log n)`
>
> *O(n)*
> *O(n log n)*
>
> *O*(*n*)
> *O*(*n* log *n*)

Correct notation italicizes the big *O* itself and the variable name *n*, but not mathematical functions such as log, constants such as 1, or the parenthesis.

2020-07-04 06:05 UTC, pierwill commented
Thanks @CAD97! I agree—I'll revise along the lines of your suggestion:

```
*O*(*n*)
*O*(*n* log *n*)
```

2020-07-04 08:50 UTC, ratijas commented
On a side note, I'd _love_ to see some advanced markup possibilities (like MathML) in rustdoc system. There's beautiful simplicity (rust) on one end, and complex alien syntax (reST) on the other end, — it feels like there should be something reasonably usable in between.

2020-07-04 11:28 UTC, GuillaumeGomez commented
You put the whole O notation in italic, but I have to admit that just having `O` and `n` in italic looks better (like @CAD97 suggested).

2020-07-06 18:39 UTC, pierwill commented
> You put the whole O notation in italic, but I have to admit that just having O and n in italic looks better (like @CAD97 suggested).

I agree. I'll update this PR when I get a chance and ping for a re-review—

2020-07-06 19:13 UTC, steveklabnik commented
> I'm going to tentatively cc @rust-lang/rustdoc and r? @GuillaumeGomez here, I guess this is more in "docs" territory but that doesn't currently exist.

Ultimately, stdlib doc contents are now the responsibility of the libs team, though obviously folks involved in docs tooling would want to be involved :)

Yes, Mathjax would be nice, but historically it has been seen as too heavy a dependency.

2020-07-06 19:48 UTC, kinnison commented
What's the situation with MathML - you used to hear quite a bit about it, but not recently.

2020-07-06 20:16 UTC, CAD97 commented
https://caniuse.com/#feat=mathml

Chrome doesn't have native support for MathML, so using it without MathJax is basically a nonstarter. You can use MathML, but you have to include the KaTeX or MathJax stylesheets to do the actual work of transforming the markup into actual math notation.

I don't have the source for it, but I remember seeing that work on MathML was basically stopped because MathJax got the same effect. (MathJax can take MathML as an input, KaTeX only takes faux-TeX.)

2020-07-06 21:29 UTC, GuillaumeGomez commented
If you want specific parsers for your format, you can have it in your own documentation, rustdoc allows to add your own scripts. However, adding an extra dependency will impact everyone and will only benefit a few. So to be clear: no additional dependency will be allowed for doing this automatically in rustdoc itself.

2020-07-15 06:27 UTC, pierwill commented
r? @GuillaumeGomez

2020-07-15 06:28 UTC, pierwill commented
> You put the whole O notation in italic, but I have to admit that just having `O` and `n` in italic looks better (like @CAD97 suggested).

I've updated this PR along these lines.

2020-07-15 08:21 UTC, GuillaumeGomez requested changes

2020-07-15 08:21 UTC, GuillaumeGomez commented on src/liballoc/collections/binary_heap.rs
> +//! converted to a sorted vector in-place, allowing it to be used for an *O*(*n* * log(*n*))
```suggestion
//! converted to a sorted vector in-place, allowing it to be used for an *O*(*n* \* log(*n*))
```

2020-07-15 08:21 UTC, GuillaumeGomez commented on src/liballoc/collections/binary_heap.rs
> +    /// * `.drain_sorted()` is *O*(*n* * log(*n*)); much slower than `.drain()`.
```suggestion
    /// * `.drain_sorted()` is *O*(*n* \* log(*n*)); much slower than `.drain()`.
```

2020-07-15 08:21 UTC, GuillaumeGomez commented on src/libcore/slice/mod.rs
> +    /// (i.e., does not allocate), and *O*(*n* * log(*n*)) worst-case.
```suggestion
    /// (i.e., does not allocate), and *O*(*n* \* log(*n*)) worst-case.
```

2020-07-15 08:21 UTC, GuillaumeGomez commented on src/libcore/slice/mod.rs
> +    /// (i.e., does not allocate), and *O*(*n* * log(*n*)) worst-case.
```suggestion
    /// (i.e., does not allocate), and *O*(*n* \* log(*n*)) worst-case.
```

2020-07-15 08:21 UTC, GuillaumeGomez commented on src/libcore/slice/mod.rs
> +    /// (i.e., does not allocate), and *O*(m * n * log(n)) worst-case, where the key function is
```suggestion
    /// (i.e., does not allocate), and *O*(m \* *n* \* log(*n*)) worst-case, where the key function is
```

2020-07-15 08:21 UTC, GuillaumeGomez commented on src/libcore/slice/mod.rs
> +    /// (i.e. does not allocate), and *O*(*n*)* worst-case. This function is also/ known as "kth
```suggestion
    /// (i.e. does not allocate), and *O*(*n*) worst-case. This function is also/ known as "kth
```

2020-07-15 08:21 UTC, GuillaumeGomez commented on src/libcore/slice/sort.rs
> +/// Sorts `v` using heapsort, which guarantees *O*(*n* * log(*n*)) worst-case.
```suggestion
/// Sorts `v` using heapsort, which guarantees *O*(*n* \* log(*n*)) worst-case.
```

2020-07-15 08:21 UTC, GuillaumeGomez commented on src/libcore/slice/sort.rs
> +/// Sorts `v` using pattern-defeating quicksort, which is *O*(*n* * log(*n*)) worst-case.
```suggestion
/// Sorts `v` using pattern-defeating quicksort, which is *O*(*n* \* log(*n*)) worst-case.
```

2020-07-20 04:44 UTC, pierwill commented
Pushed those changes!

2020-07-20 09:00 UTC, GuillaumeGomez approved these changes

2020-07-20 09:00 UTC, GuillaumeGomez commented
Thanks!

@bors: r+ rollup

2020-07-20 13:42 UTC, merged