Compare tagged/niche-filling layout and pick the best one
rust-lang/rust pull request #74069
Opened 2020-07-05 18:41 UTC by erikdesjardins

Finishes up #71045, and so fixes #63866.

cc @eddyb
r? @nikomatsakis (since @eddyb wrote the first commit)

2020-07-16 14:33 UTC, nikomatsakis requested changes
r=me after nits are fixed

2020-07-16 14:33 UTC, nikomatsakis commented on src/test/ui/type-sizes.rs
> +pub enum CanBeNicheFilledButShouldnt {
Can you add a comment explaining why it should not use a niche?

2020-07-16 14:33 UTC, nikomatsakis commented on src/test/ui/type-sizes.rs
> +pub enum AlwaysTagged {
```suggestion
pub enum AlwaysTaggedBecauseItHasNoNiche {
```

maybe make this self-documenting?

2020-07-17 20:14 UTC, nikomatsakis approved these changes

2020-07-17 20:14 UTC, nikomatsakis commented
@bors r+

2020-07-18 10:08 UTC, eddyb approved these changes

2020-07-18 10:10 UTC, eddyb commented
Thanks a lot! I've closed my original unfinished PR.

2020-07-18 16:08 UTC, merged

2020-07-21 15:19 UTC, Mark-Simulacrum commented
@rust-timer make-pr-for e775b4dbc4a991d60014225088c58eddd91f18cb

2020-07-22 00:03 UTC, Mark-Simulacrum commented
Benchmarked in https://github.com/rust-lang/rust/pull/74592, it does appear like this was a 5-10% performance regression on a large variety of crates. We should probably revert this PR. I've posted a revert here: xxx

https://perf.rust-lang.org/compare.html?start=d3df8512d2c2afc6d2e7d8b5b951dd7f2ad77b02&end=cfade73820883adf654fe34fd6b0b03a99458a51

cc @nnethercote

2020-07-27 18:40 UTC, Mark-Simulacrum commented
This turned out to not be the source of any regressions, and indeed might be a mild improvement. It will be re-landed in https://github.com/rust-lang/rust/pull/74802. See also https://github.com/rust-lang/rust/pull/74716#issuecomment-663735771 and the next few comments for discussion on this topic.