Teach bootstrap `RUST_DESTDIR`, a scoped alternative to `DESTDIR`
rust-lang/rust pull request #74252
Opened 2020-07-11 19:04 UTC by shepmaster

When running a command like `DESTDIR=foo x.py install` in a completely
clean build directory, this will cause LLVM to be installed into
`DESTDIR`, which then causes the build to fail later when it attempts
to *use* those LLVM files.

2020-07-11 19:04 UTC, rust-highfive commented
r? @Mark-Simulacrum

(rust_highfive has picked a reviewer for you, use r? to override)

2020-07-11 23:53 UTC, eddyb requested changes
This may work as a workaround but I believe `x.py build` should not expose `DESTDIR` to the LLVM build, i.e. it should unset that env var for the relevant commands, which will remove the need to have `RUST_DESTDIR` at all.

This seems to be a combination of oversight and probably `x.py install` not being used to also do the build step, most of the time (think `make && make DESTDIR=$PKG_OUT_DIR install`).

2020-07-12 15:47 UTC, Mark-Simulacrum commented
Yes, I think @eddyb is right that the preferred approach would be to unset the env variable when invoking cmake during our LLVM installation/building, since we should be in full control of where LLVM is installed (vs. Rust itself, which I guess makes sense that DESTDIR should affect that).

2020-07-12 18:35 UTC, shepmaster commented
Updated to unset `DESTDIR` for LLVM.

2020-07-12 18:52 UTC, Mark-Simulacrum commented
@bors r+

2020-07-14 23:42 UTC, merged