Added docs for `From<c_int>` for `ExitStatus`
rust-lang/rust pull request #74291
Opened 2020-07-13 11:49 UTC by regexident

Partially addresses https://github.com/rust-lang/rust/issues/51430

2020-07-13 11:49 UTC, rust-highfive commented
r? @LukasKalbertodt

(rust_highfive has picked a reviewer for you, use r? to override)

2020-07-14 08:01 UTC, LukasKalbertodt requested changes
Thanks for the PR!

To be honest, I don't think this particular documentation adds any valuable information. It would be better if you would mention the cost of the conversion (basically free as far as I can see), so that the doc comment has at least more information than the `impl` header already contains.

2020-07-14 09:30 UTC, regexident commented
Thanks a fair point, @LukasKalbertodt!

I'd argue though that it does add something by hinting at it being a "type-safety" conversion.
Anyway, I tried improving it by adding `… by wrapping it without copying.`. Is that better?

<sub>(Technically it _is_ "copying" in the Rust sense, but several other doc comments use "copying" to imply `memcpy`.)</sub>

2020-07-14 17:44 UTC, LukasKalbertodt commented
Yeah but this "type-safe" thing also kind of bothers me :/ And yes, "copy" is also slightly problematic. Sorry for being so picky! What do you think about this?

> Converts a raw `c_int` into an `ExitStatus`. The conversion is very cheap.

2020-07-14 20:03 UTC, regexident commented
"Very cheap" is very subjective though, isn't it? Cheap relative to what exactly?
Given that `ExitStatus` is a newtype the overhead should essentially be zero, no?

So how about something like… ?

> Converts a raw `c_int` into an `ExitStatus`, at near-zero overhead.

2020-07-14 21:32 UTC, LukasKalbertodt commented
Yeah, true, "very cheap" is not optimal. "near zero overhead" makes one think "overhead over what" though. Mh. I'm probably overthinking this, sorry :D 
This should be handled by a professional :P 

r? @GuillaumeGomez

2020-07-15 08:12 UTC, GuillaumeGomez approved these changes

2020-07-15 08:13 UTC, GuillaumeGomez commented
For me it's good as is. :laughing: 

Let's merge it then!

@bors: r+ rollup

2020-07-16 06:25 UTC, merged