add a Backtrace::disabled function
rust-lang/rust pull request #74490
Opened 2020-07-18 22:52 UTC by yaahc

Based upon @dtolnay's suggestion here: https://github.com/dtolnay/anyhow/pull/97#issuecomment-647172942

2020-07-18 22:52 UTC, rust-highfive commented
r? @dtolnay

(rust_highfive has picked a reviewer for you, use r? to override)

2020-07-18 22:54 UTC, yaahc commented
@mystor has raised an alternative approach based on consts

```rust
impl Backtrace {
    const DISABLED: Backtrace;
}```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f2c4c0046aa51bb12686ad375909e0e2

2020-07-22 23:09 UTC, dtolnay requested changes

2020-07-22 23:09 UTC, dtolnay commented on src/libstd/backtrace.rs
> +    pub fn disabled() -> Backtrace {
```suggestion
    pub const fn disabled() -> Backtrace {
```

Important if you are interested in using a disabled &amp;'static Backtrace as fallback for a `fn backtrace(&self) -> &Backtrace`.

2020-07-22 23:13 UTC, dtolnay commented
`const DISABLED` is fine too; I don't have a preference between those.

2020-07-23 00:20 UTC, yaahc commented
I think making this `const fn` solves the issue that `const DISABLED` was trying to solve, and so I'd prefer to have it be a `fn` to be consistent with `capture` and `force_capture`.

2020-07-23 00:22 UTC, dtolnay approved these changes

2020-07-23 00:22 UTC, dtolnay commented
@bors r+ rollup

2020-07-23 10:44 UTC, merged