one more Path::with_extension example, to demonstrate behavior
rust-lang/rust pull request #74548
Opened 2020-07-20 10:26 UTC by tshepang

2020-07-20 10:26 UTC, rust-highfive commented
r? @dtolnay

(rust_highfive has picked a reviewer for you, use r? to override)

2020-07-22 23:06 UTC, dtolnay requested changes
I think this example would be more compelling if you pick a realistic 2-part extension, such as "foo.tar.gz".

2020-07-22 23:36 UTC, tshepang commented on src/libstd/path.rs
> +    /// assert_eq!(path.with_extension(""), PathBuf::from("foo.bar"));
```suggestion
    /// let path = Path::new("foo.tar.gz");
    /// assert_eq!(path.with_extension(""), PathBuf::from("foo.tar"));
```

2020-07-22 23:40 UTC, dtolnay approved these changes

2020-07-22 23:40 UTC, dtolnay commented
@bors r+ rollup

2020-07-23 10:44 UTC, merged