cleanup: Remove duplicate library names from `Cargo.toml`s
rust-lang/rust pull request #74668
Opened 2020-07-23 07:54 UTC by petrochenkov

2020-07-23 07:54 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2020-07-23 08:38 UTC, matklad commented
Should we do this after https://github.com/rust-lang/rust/pull/73265 perhaps? We'll be able to remove `path=` as well.

2020-07-23 11:25 UTC, tshepang commented
@matklad is it a new feature for it to work without needing to specify `path=`?

2020-07-23 11:30 UTC, matklad commented
No,  #73265 in its current form just proposes to leverage standard cargo's convetion, which doesn't require explicit config.

2020-07-23 16:56 UTC, petrochenkov commented
>Should we do this after https://github.com/rust-lang/rust/pull/73265 perhaps?

Yeah, this can be done as a part of the std move (#73265) or as a part of the compiler move (majority of the changes), or separately.
Neither makes git history harder to follow, so there's probably not much difference.

2020-07-23 17:01 UTC, matklad commented
There's differnce in how annoying is #73265 to rebase though :)

2020-07-27 17:41 UTC, nikomatsakis commented
ok, marking as blocked on https://github.com/rust-lang/rust/pull/73265 I guess

2020-07-28 19:00 UTC, petrochenkov commented
Blocked on https://github.com/rust-lang/rust/pull/74862.

2020-08-30 19:21 UTC, petrochenkov commented
r? @mark-i-m

2020-08-30 19:49 UTC, mark-i-m requested changes

2020-08-30 19:49 UTC, mark-i-m commented on compiler/rustc/Cargo.toml
> -path = "src/main.rs"
Bootstrap actually assumes the name of the binary is `rustc_binary`, so you also need to change the package name on line 3 to `rustc_binary`, I think.

2020-08-30 19:50 UTC, mark-i-m commented
Other than the above, r=me (but I don't have bors priveleges).

2020-08-30 19:59 UTC, petrochenkov commented
@bors delegate mark-i-m
@bors r=mark-i-m

2020-08-30 20:00 UTC, mark-i-m approved these changes

2020-08-30 21:11 UTC, petrochenkov commented
```
---- build::close_output stdout ----
thread 'build::close_output' panicked at 'lines differ:
   Compiling foo v0.1.0 (D:\a\rust\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\cit\t215\foo)
error: The pipe is being closed. (os error 232)
warning: build failed, waiting for other jobs to finish...
hello stderr!
error: build failed
', src\tools\cargo\tests\testsuite\build.rs:5043:5
```
Looks spurious.
@bors retry

2020-08-31 01:29 UTC, merged