Miri: improve spans of required_const failures
rust-lang/rust pull request #75396
Opened 2020-08-11 10:48 UTC by RalfJung

In https://github.com/rust-lang/rust/pull/75339 I added a loop evaluating all consts required by a function body. Unfortunately, if one of their evaluations fails, then the span used for that was that of the first statement in the function body, which happened to work form some existing test but is not sensible in general.

This PR changes it to point to the whole function instead, which is at least not wrong.

r? @oli-obk

2020-08-11 10:50 UTC, RalfJung commented
To do better, we'd have to either
* pass a span through the error machinery (i.e., add a `Span` field to `InterpError`) which (if present) overwrites the span of the topmost frame, or
* make it so that the frame knows it is currently evaluating a const, and can report its span.

In the light of [this chaos](https://github.com/rust-lang/rust/issues/71800#issuecomment-671805859), I am not sure I want to add yet another `Span` field to errors, and such "overwriting" behavior is often confusing. So if we think that we should try to do better, my proposal would be to replace this field of `Frame`
```rust
    pub loc: Option<mir::Location>,
```
by something of a type like `Result<mir::Location, Span>`, so that we can say what the span is when we are not currently evaluating a statement in that frame.

2020-08-11 11:02 UTC, oli-obk commented
Yes, I also prefer that proposal. Although `Result` isn't the best type here, I'm not sure the situation warrants its own enum (though that could make it more obvious that something unusual is going on here). The current `None` situation could be represented by `Err(DUMMY_SP)`

2020-08-11 11:10 UTC, RalfJung commented
Or rather, `Err(self.body.span)`. Yes.

2020-08-11 12:54 UTC, RalfJung commented
All right, I implemented that now.

2020-08-11 14:01 UTC, oli-obk requested changes
r=me with nits

2020-08-11 14:01 UTC, oli-obk commented on src/test/ui/consts/const-err-multi.stderr
> +   | ------------------^-------
this is great!

2020-08-12 06:49 UTC, RalfJung commented on src/librustc_mir/interpret/intrinsics/caller_location.rs
> +        // (`loc` is None when we are unwinding and the frame does not require cleanup).
(edited to `Err`)

2020-08-12 06:50 UTC, RalfJung commented
@bors r=oli-obk

2020-08-12 07:22 UTC, RalfJung commented
@bors r-
investigating branch CI failure

2020-08-12 07:58 UTC, RalfJung commented
Hu, a test failure but local runs don't show anything??

2020-08-12 08:17 UTC, RalfJung commented
Ah looks like that test was changed recently even though it already existed before... very strange.

2020-08-12 08:21 UTC, RalfJung commented
@oli-obk for some reason `uninhabited-const-issue-61744.stderr` changed a lot. No idea what is happening.

2020-08-12 08:21 UTC, RalfJung commented
Also how horrible is GitHub? Why can I not go to the git log from https://github.com/rust-lang/rust/blob/d45dcb509527d847c7c3bf459a0e796801067b33/src/test/ui/consts/uninhabited-const-issue-61744.stderr ? I thought that used to be possible?

2020-08-12 08:23 UTC, RalfJung commented
Hm, that test also did not change recently. So it must be some other change on the rustc side that makes it such that in combination with this PR, the output for that test changes. WTF.

2020-08-12 08:27 UTC, RalfJung commented
Oh I see, this is a stack overflow, so it likely interacts with https://github.com/rust-lang/rust/pull/75338.

2020-08-12 08:29 UTC, RalfJung reviewed
(wow GitHub is really making my life as hard as possible today. now it started a review...)

2020-08-12 08:29 UTC, RalfJung commented on src/librustc_mir/interpret/eval_context.rs
> +        self.frame_mut().loc = Ok(mir::Location::START);
It's about the order of these two lines: for errors that happen during `after_stack_push`, so we want to use the span of the first statement, or the span of the entire body? IMO the latter makes more sense, the first statement has nothing to do with this.

For the stack overflow, probably the best span to use would be that of the call site.

2020-08-12 09:10 UTC, RalfJung commented
All right, I got it. I moved the stack check to *before* the new frame is added, so the span is at the call site.

@oli-obk probably better if you check this again since I did a bit more than just fixing those typos.

2020-08-12 09:14 UTC, oli-obk commented on src/librustc_mir/const_eval/machine.rs
> +        if !ecx.tcx.sess.recursion_limit().value_within_limit(ecx.stack().len()+1) {
rustfmt :laughing: 
```suggestion
        if !ecx.tcx.sess.recursion_limit().value_within_limit(ecx.stack().len() + 1) {
```

2020-08-12 09:14 UTC, RalfJung commented on src/librustc_mir/const_eval/machine.rs
> +        if !ecx.tcx.sess.recursion_limit().value_within_limit(ecx.stack().len()+1) {
argh...

2020-08-12 09:18 UTC, oli-obk commented on src/librustc_mir/interpret/eval_context.rs
> +        self.frame_mut().loc = Ok(mir::Location::START);
yea, the body's span is good here, though it's actually the call site's fault. But lets leave such refactorings (using the call site span) to the future, I remember trying something similar a while back and it just complicated the span scheme even more

2020-08-12 09:18 UTC, oli-obk commented
@bors r+

2020-08-12 09:20 UTC, RalfJung commented on src/librustc_mir/interpret/eval_context.rs
> +        self.frame_mut().loc = Ok(mir::Location::START);
Hm, this wouldn't even be that hard I think... we can just call `cur_span` before pushing the new frame, then we should get the call site.

2020-08-12 09:22 UTC, RalfJung commented on src/librustc_mir/interpret/eval_context.rs
> +        self.frame_mut().loc = Ok(mir::Location::START);
It's just not clear to me that we always want the call site. The callee could also be responsible for the problem -- in fact I'd usually think they are.

2020-08-12 09:31 UTC, oli-obk commented on src/librustc_mir/interpret/eval_context.rs
> +        self.frame_mut().loc = Ok(mir::Location::START);
at runtime the decision whose job it is to create the stack frame is an ABI decision, but that doesn't really make sense for CTFE. But I also think your alluding to a different thing? If an required_const will fail regardless of the concrete generic parameters, then that's indeed the function's fault and not the caller's

2020-08-12 09:52 UTC, RalfJung commented on src/librustc_mir/interpret/eval_context.rs
> +        self.frame_mut().loc = Ok(mir::Location::START);
> If an required_const will fail regardless of the concrete generic parameters, then that's indeed the function's fault and not the caller's

Yes, that is one possible scenario I had in mind where blaming the caller seems wrong.

2020-08-12 11:17 UTC, RalfJung commented
```
error: embedded-book maintainer @ryankurte is not assignable in the rust-lang/rust repo
error: embedded-book maintainer @thejpster is not assignable in the rust-lang/rust repo
error: embedded-book maintainer @korken89 is not assignable in the rust-lang/rust repo
```
Seems spurious to me... I hope.^^
@bors retry

2020-08-12 11:35 UTC, rust-log-analyzer commented
The job `mingw-check` of your PR [failed](https://github.com/rust-lang-ci/rust/runs/975575362) ([pretty log](https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://github.com/rust-lang-ci/rust/commit/0ac354c868c8238b48198d9bac75bd17719505e3/checks/975575362/logs), [raw log](https://github.com/rust-lang-ci/rust/commit/0ac354c868c8238b48198d9bac75bd17719505e3/checks/975575362/logs)). Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.

<details><summary><i>Click to expand the log.</i></summary>

```plain
Build completed successfully in 0:01:55
+ /scripts/validate-toolstate.sh
Cloning into 'rust-toolstate'...
<Nothing changed>
error: embedded-book maintainer @thejpster is not assignable in the rust-lang/rust repo
error: embedded-book maintainer @korken89 is not assignable in the rust-lang/rust repo
error: embedded-book maintainer @ryankurte is not assignable in the rust-lang/rust repo

  To be assignable, a person needs to be explicitly listed as a
  collaborator in the repository settings. The simple way to
  fix this is to ask someone with 'admin' privileges on the repo
  to add the person or whole team as a collaborator with 'read'
  privileges. Those privileges don't grant any extra permissions
  so it's safe to apply them.
The build will fail due to this.
== clock drift check ==
  local time: Wed Aug 12 11:35:32 UTC 2020
  network time: Wed, 12 Aug 2020 11:35:33 GMT
  network time: Wed, 12 Aug 2020 11:35:33 GMT
== end clock drift check ==
##[error]Process completed with exit code 1.
Terminate orphan process: pid (3052) (node)
Terminate orphan process: pid (3077) (python)
```

</details><p></p>

[I'm a bot](https://github.com/rust-ops/rust-log-analyzer)! I can only do what humans tell me to, so if this was not helpful or you have suggestions for improvements, please ping or otherwise contact **`@rust-lang/infra`**. ([Feature Requests](https://github.com/rust-ops/rust-log-analyzer/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request))

2020-08-12 11:49 UTC, RalfJung commented
@rust-lang/infra
second time in a row that I got
```
error: embedded-book maintainer @thejpster is not assignable in the rust-lang/rust repo
error: embedded-book maintainer @korken89 is not assignable in the rust-lang/rust repo
error: embedded-book maintainer @ryankurte is not assignable in the rust-lang/rust repo
```
Any idea what is happening?
@bors retry

2020-08-12 11:52 UTC, pietroalbini commented
@bors treeclosed=1000

2020-08-12 11:56 UTC, pietroalbini commented
Fixing CI in https://github.com/rust-lang/rust/pull/75450.

2020-08-12 23:03 UTC, merged