Add `[T; N]::as_ref` and `[T; N]::as_mut`
rust-lang/rust pull request #75490
Opened 2020-08-13 15:47 UTC by LukasKalbertodt

This PR adds the methods `as_ref` and `as_mut` to `[T; N]`. The ability to add methods to arrays was added in #75212. These two methods are particularly useful with `map` which was also added in that PR.

```rust
impl<T, const N: usize> [T; N] {
    pub fn as_ref(&self) -> [&T; N];
    pub fn as_mut(&mut self) -> [&mut T; N];
}
```

---

I think there are quite a few useful methods that could be added to arrays. That's why I used the feature `array_methods` as it's probably a bit annoying to add a new feature and tracking issue for each new method. Collecting a bunch of basic methods under one feature seems easier. It can still be split later, if necessary.

Some ideas for other useful methods:

- `cloned` and `copied`: I actually already wanted to add them in this PR, but noticed that it's not possible right now as they require a new `impl` block (`for [&T; N] where T: Clone`). But we would need a new lang item for that, but I don't think we want to have a new lang item for every slightly different `impl` block? Any idea how we could solve this?

- `zip` and `unzip`: `zip` I could already add if people agree that it is useful, but `unzip` has the same problem as `cloned` and `copied`: needs a new impl block.

- `chain` or `concat`: Super useful but likely not implementable with `min_const_generics` as it requires arithmetic with the array lenghts.

- Something like `array_windows`, `array_chunks` and `array_chunks_exact`. See #75026 for that method for slices. 

---

If anyone else still has ideas for basic methods to add, let me know! I could still add them to this PR. And if anyone could help with the "new impl block lang item" problem, that would be great!

CC @JulianKnodt

2020-08-13 16:00 UTC, LukasKalbertodt commented
Regarding `concat`: apparently it's not possible to add it right now. Adding this:

```rust
pub fn concat<const M: usize>(self, other: [T; M]) -> [T; N + M] {
    todo!()
}
```

leads to:

```
error: constant expression depends on a generic parameter
   --> library/core/src/array/mod.rs:505:59
    |
505 |     pub fn concat<const M: usize>(self, other: [T; M]) -> [T; N + M] {
    |                                                           ^^^^^^^^^^
    |
    = note: this may fail depending on what value the parameter takes
```

(compare #68436)

2020-08-13 16:52 UTC, LukasKalbertodt commented
Oh no, not this again :disappointed: 
`[1, 2, 3].as_ref()` already works today and returns `&[i32]`. So adding these methods is a breaking change, very similarly to #65819. Luckily, in this case we can simply change the name. Maybe `elements_as_ref` or `element_refs` or something like that? Still unfortunate: I would like to use the same name as `Option` as the methods are so similar.

2020-08-13 16:53 UTC, LukasKalbertodt commented
Oops, highfive forgot to assign someone. :game_die: 
r? @dtolnay

2020-08-13 17:05 UTC, CryZe commented
@scottmcm's arraytools calls them [`as_[mut/ref]_array`](https://docs.rs/arraytools/0.1.5/arraytools/trait.ArrayTools.html#method.as_mut_array)

2020-08-13 18:19 UTC, JulianKnodt commented
Hm I was thinking about this, and maybe it's useful to define an intermediate struct, which is like an `Iterator`, but doesn't actually implement the iterator interface. When something like `map` or `zip` is called on it, it applies the intermediate functions on it and returns `[T'; N]`. That way, we could avoid creating many lang items and also allow for intermixing of different calls(possibly). Notably, I think not having `enumerate` makes a lot of array functions more clunky, because I imagine it's a common use case to use an index to initialize an element.

2020-08-13 19:46 UTC, JulianKnodt commented
Ah also would `[S: N] where S: AsRef<T>` and/or `Borrow<T>` satisfy the issue short term?

2020-08-13 20:06 UTC, scottmcm commented
> maybe it's useful to define an intermediate struct, which is like an Iterator, but doesn't actually implement the iterator interface. 

I don't think a separate type is needed here.  As a parallel, `map` and [`cloned`](https://doc.rust-lang.org/nightly/std/option/enum.Option.html#method.cloned) and such are available directly on `Option`, without needing to go through another type.

> I imagine it's a common use case to use an index to initialize an element.

I agree, and made [`ArrayTools::indices`](https://docs.rs/arraytools/0.1.5/arraytools/trait.ArrayTools.html#method.indices) to construct such an array directly.

> if anyone could help with the "new impl block lang item" problem

Any chance the `where T: Copy` can go on the method instead of the impl block?

2020-08-13 20:31 UTC, JulianKnodt commented
Hm, if I can offer a counterpoint to `Option` offering `map` and `cloned`, `Vec` doesn't offer `map` directly, which to me is because it's expensive to perform `map` on larger vectors. I'm not sure if the common use case for `[T; N]` is closer to `Option<T>`, which would mean most operations are `O(1)` so be performed easily/directly, or for `Vec`, where operations such as `map` or `clone` take `O(n)` time.

2020-08-13 20:33 UTC, CryZe commented
I'd actually say that Vec totally should have map as well, because it can potential reuse its backing memory if the target type has the same size and alignment. So map not existing (yet?) on Vec is not really an argument.

2020-08-13 21:07 UTC, lcnr commented
> And if anyone could help with the "new impl block lang item" problem, that would be great!

So yeah, either move the bounds to the method or look at how slice does its mutliple impl blocks. If you need help while doing so, feel free to open a topic on zulip and or ping me there.

2020-08-13 22:15 UTC, LukasKalbertodt commented
> Any chance the where `T: Copy` can go on the method instead of the impl block?

The bound is not the problem. The impl block would be for `[&T; N]` and `[&mut; N]`. At least that's how it's done for `Option::cloned`. I am pretty sure we really want a different impl block here 🤔 

> Ah also would `[S: N] where S: AsRef<T>` and/or `Borrow<T>` satisfy the issue short term?

Could potentially work, but I'd rather not introduce this temporary suboptimal solution.

> look at how slice does its multiple impl blocks.

That's the first thing I did when noticing the problem, but as far as I see, slice does *not* have multiple such impl blocks. Well, there is `[T]` and `[u8]`, both being separate lang items. 

I *think* the correct solution here is to change how lang items work, in that we would allow `#[lang = "array"]` on multiple impl blocks as long as they for the same type constructor thingy. But I have no idea how I would implement that :/

2020-08-14 06:34 UTC, lcnr commented
> but as far as I see, slice does not have multiple such impl blocks

yeah, so you would probably need one lang item per impl block if you don't want to do a more complex change here

2020-08-30 19:31 UTC, LukasKalbertodt commented
I decided to only deal with the `as_ref`/`as_mut` methods in this PR. I will create separate PRs for other methods. I changed the title, my top comment and hid a couple of comments as "off topic". I hope you don't mind me doing so in order to make this discussion more focused.

I just force pushed to name the methods `as_ref_elements` and `as_mut_elements`. It was suggested to name them `as_[ref|mut]_array` but I don't particularly like these names :confused: Those rather seem to indicate that they return a reference to the whole array. I am not completely happy with `as_[ref|mut]_elements` either though! If anyone has any good ideas, let us know!

2020-08-30 19:41 UTC, LukasKalbertodt commented on library/core/src/array/mod.rs
> +    /// [`map`](#method.map). This way, you can can avoid moving the original
Does anyone know how to use intra-doc links for this? ```[`map`]``` and ```[`Self::map`]``` don't work.

2020-09-08 13:55 UTC, shepmaster commented
> I would like to use the same name as `Option` as the methods are so similar.

I agree.

2020-09-08 14:24 UTC, LukasKalbertodt commented
@shepmaster Are you suggesting we should try to run crater with `as_ref`/`as_mut` to see how much it really breaks?

2020-09-08 14:31 UTC, shepmaster commented
> run crater with `as_ref`/`as_mut` to see how much it really breaks

I think it's worth it. My gut says that the incidences will be much lower than `array::into_iter` because `AsRef` is mostly only used in generic contexts (`fn foo(_: impl AsRef<...>)`).

2020-09-08 17:10 UTC, LukasKalbertodt commented
@shepmaster I hope you are right. I don't want to be the guy that always opens the "breaks all the code" PRs :smile: 

I forced pushed to rename back to `as_ref`/`as_mut`. Crater queue luckily isn't too full right now.

2020-09-08 17:54 UTC, LukasKalbertodt commented
@bors try

2020-09-08 18:42 UTC, LukasKalbertodt commented
@craterbot check

2020-09-08 22:51 UTC, Aaron1011 commented on library/core/src/array/mod.rs
> +    /// size as `self`.
I would say `length` here, since the overall size (as computed by `std::mem::size_of_val`) will likely be different.

2020-09-18 07:24 UTC, LukasKalbertodt commented
That result is a lot better than I would have guessed. From those 22 regressions, 11 have nothing to do with this change. The remaining 11 crates fail to build with "unstable name collisions". From those 11, only two seem to be popular: [`fontfor`](https://github.com/7sDream/fontfor/tree/c13b893577e09267306190079adcf98dc5805189) has >100 GitHub stars and [`httpparse`](https://crates.io/crates/httparse/1.3.4) has many downloads and big reverse dependencies (like `hyper`).

But I think I made a mistake. Apparently, without using the `#![feature(array_methods)]`, the old behavior is kept and only a future-incompatibility warning is emitted. All failures forbid warnings and they only fail due to this. That also explains why `httpparse` does not cause its reverse-dependencies to fail. I guess I should have ran crater with `+rustflags="--deny future_incompatible"`? Is that the correct syntax even?

2020-10-11 00:20 UTC, Dylan-DPC commented
@dtolnay @LukasKalbertodt any updates?

2020-10-15 18:52 UTC, dtolnay requested changes
I understand that these signatures are conceptually consistent with Option::as_ref and Result::as_ref, but I think my preference would be not to use as_ref naming for this. My reason is that the unsize coercion from &amp;\[T; N\] to &amp;\[T\] is a quite common need and AsRef/as_ref is the natural thing to reach for when needing it. Option and Result have no such coercion so the as_ref naming is completely available for the alternate behavior.

My counterproposal would be:

```rust
let array: [String; 3] = /*...*/;
let [a, b, c] = array.each_ref();
```

2020-10-15 21:55 UTC, jplatte commented
With the current methods in the description (`as_ref_elements` and `as_mut_elements`) and @dtolnay's suggestion I had another idea: `as_refs`, since it doesn't give you a reference to the elements (which `as_ref_elements` might suggest), that's already what `as_ref` does; it gives you many references. Its mutable counterpart is then a little less clear, but I think `as_muts` would probably too weird, so `as_mut_refs`? Doesn't seem like a bad option to me.

2020-10-26 22:25 UTC, LukasKalbertodt commented
@dtolnay's argument makes sense to me. And I'm also pretty sure using `as_ref` would break the world. I like both suggestions (`each_ref` and `as_refs`) a lot better than my `as_ref_elements` name. To throw in another name: `each_as_ref` and `each_as_mut`?

2020-10-27 12:00 UTC, shepmaster commented
The `each` variants make me think the function will take a closure and perform some kind of iteration. 🤷‍♀️

2020-12-19 20:55 UTC, LukasKalbertodt commented
To move this along, I now pushed a commit where they are named `each_as_ref` and `each_as_mut`. If I should change them or you have better ideas, let me know.

2021-01-11 01:55 UTC, dtolnay requested changes
I would be prepared to land this after a rename to `each_ref` / `each_mut`. I believe those names are better than `each_as_ref` / `each_as_mut` because each_as_ref is the implementor's perspective (perform as_ref on each element?) while each_ref is the more natural caller's perspective (get back a ref to each element) which is what will make sense in the context of surrounding code at the call site.

2021-01-11 08:55 UTC, LukasKalbertodt commented
@dtolnay I'm not fully convinced yet, but we can still discuss the name before stabilization. I updated the PR with the names you suggested :)

2021-01-11 08:57 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/1680057057) [(plain)](https://github.com/rust-lang/rust/commit/5e90544c76448240389299dec0f25ffafc2452e5/checks/1680057057/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling libc v0.2.79
   Compiling std v0.0.0 (/checkout/library/std)
   Compiling compiler_builtins v0.1.39
   Compiling unwind v0.0.0 (/checkout/library/unwind)
error: the item `MaybeUninit` is imported redundantly
    |
18  | use crate::mem::MaybeUninit;
18  | use crate::mem::MaybeUninit;
    |     ----------------------- the item `MaybeUninit` is already imported here
485 |         use crate::mem::MaybeUninit;
    |             ^^^^^^^^^^^^^^^^^^^^^^^
    |
    |
    = note: `-D unused-imports` implied by `-D warnings`
error: aborting due to previous error

error: could not compile `core`


To learn more, run the command again with --verbose.
command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "check" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "16" "--release" "--color" "always" "--features" "panic-unwind backtrace compiler-builtins-c" "--manifest-path" "/checkout/library/test/Cargo.toml" "--message-format" "json-render-diagnostics"
failed to run: /checkout/obj/build/bootstrap/debug/bootstrap check
Build completed unsuccessfully in 0:01:24
```

</details>

2021-01-11 09:10 UTC, dtolnay commented
I pushed a rebase to fix the conflict with #79451.

@bors r+

2021-01-11 09:11 UTC, LukasKalbertodt commented
Oh wow, you're fast :D I also rebased locally and was just testing. Thanks!

2021-01-11 09:14 UTC, dtolnay approved these changes

2021-01-11 14:58 UTC, rust-log-analyzer commented
A job failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/runs/1681934759) [(plain)](https://github.com/rust-lang-ci/rust/commit/6bb7313d5c346ae7f2397e6d61390ff288e32016/checks/1681934759/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

```

</details>

2021-01-11 18:08 UTC, dtolnay commented
@bors retry

2021-01-11 21:32 UTC, merged