Moves the last build-pass tests to check-pass
rust-lang/rust pull request #75673
Opened 2020-08-18 17:02 UTC by otaviopace

Fixes https://github.com/rust-lang/rust/issues/62277

2020-08-18 17:02 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @nikomatsakis (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2020-08-18 17:47 UTC, JohnTitor requested changes
The diffs shouldn't be changed, could you make the failed tests `build-pass`?

2020-08-18 18:00 UTC, petrochenkov commented
@otavio 
Is this a blanket change `build-pass (FIXME(62277): could be check-pass?)` -> `check-pass`?
https://github.com/rust-lang/rust/issues/62277 is about manually reviewing each test and deciding on its category (https://github.com/rust-lang/rust/issues/62277#issuecomment-518014691 describes the criteria).

2020-08-18 18:05 UTC, otaviopace commented
Ohh okay @petrochenkov , I didn't do a deep analysis, since I don't know much about how this works.
Maybe I should close this then, or I can follow @JohnTitor suggestion of just doing a rollback change on the failed tests.

2020-08-18 18:07 UTC, JohnTitor commented
> I can follow @JohnTitor suggestion of just doing a rollback change on the failed tests.

It's helpful to reduce the number of FIXMEs imo.

2020-08-18 18:48 UTC, JohnTitor commented
@otaviopace Ah, I mean, we should revert all the changes then remove FIXMEs of the failed tests so that we could reduce FIXMEs.

2020-08-18 22:02 UTC, otaviopace commented
Okay @JohnTitor so just to see if I understood it. I should rollback all of them, even if their tests passed, but the ones which failed, I should just remove the `(FIXME(62277): could be check-pass?)` comment, is this correct?

Also, should I remove the `Fixes` from the description since this PR will not solve the issue no more?

2020-08-18 22:12 UTC, JohnTitor commented
> 
> 
> Okay @JohnTitor so just to see if I understood it. I should rollback all of them, even if their tests passed, but the ones which failed, I should just remove the `(FIXME(62277): could be check-pass?)` comment, is this correct?

Yeah, that's correct. The problem here is that we need to look at which tests should be `check-pass` or `build-pass` one by one. Otherwise, we will overlook bugs or regressions.
But if a test is failing with `check-pass`, it should be obviously `build-pass`. We found some tests failed in moving so we could remove FIXMEs and mark it as `build-pass` duly.

> Also, should I remove the `Fixes` from the description since this PR will not solve the issue no more?

Yep.

2020-08-19 07:04 UTC, otaviopace commented
@JohnTitor do you know how can I analyze if I can change from `build-pass` to `check-pass` by reading the code? Maybe we can fix this issue in this Pull Request :slightly_smiling_face: 

If it is something too complicated to pass, or maybe you don't have context on it, we could just finish this Pull Request only with the removal of unnecessary comments.

2020-08-19 07:20 UTC, JohnTitor commented
> @JohnTitor do you know how can I analyze if I can change from `build-pass` to `check-pass` by reading the code? Maybe we can fix this issue in this Pull Request slightly_smiling_face

Well, I'd say it'd be a hard way. For example, if a test is for the const, the reviewer and you should know consts, the purpose of the test, and where will the items be resolved, evaluated, etc.
So, it's a good way to address one area with one PR. That way, it's easier to know who to ask for a review and less of a burden on the reviewer.

2020-08-20 12:24 UTC, otaviopace commented
@JohnTitor so I've decided to make this Pull Request only to be to clean the tests which clearly can't use `check-pass` okay?
I've changed the title, description and commits to adequate the new purpose of it :slightly_smiling_face:

2020-08-20 17:14 UTC, Mark-Simulacrum commented
Even if they currently have differing output between check and build pass, I would prefer to avoid blanket removing the fixme. It seems likely that at least in some cases, that could be hiding bugs or unintentional differences...

2020-08-20 17:28 UTC, otaviopace commented
If that's the case I think I will close this then.

2020-08-20 17:40 UTC, JohnTitor commented
> It seems likely that at least in some cases, that could be hiding bugs or unintentional differences...

@Mark-Simulacrum Hm you mean `ignore-pass` things? IIRC `build-pass` is equivalent to `compile-pass` so just removing it should be fine though.

2020-08-20 17:49 UTC, Mark-Simulacrum commented
No, I mean that e.g. the type size printing seems like it shouldn't be build-pass and should be check-pass. I guess it can't be right now - but we shouldn't just patch over that by dropping the fixme IMO.

Dropping the fixme on incremental tests could be more reasonable, but again I would prefer to check that the difference is e.g. codegen-related, and not something more subtle and earlier in the pipeline.

2020-08-20 18:15 UTC, JohnTitor commented
Ah makes sense. In particular, the ICH things should be fine to be removed the FIXMEs but I might be missing something.

@otaviopace So, if you want to continue, then I think we could tackle incr-comp things only here. And the detailed reviews are needed. Unfortunately, I'm not an expert on incr-comp so I couldn't help... Otherwise, we could just close this. Anyway, thanks for contributing and working on it <3

2020-08-20 18:32 UTC, Mark-Simulacrum commented
Basically I would want to see the differences/test failures before signing off on dropping any FIXME annotations here.

2020-08-20 20:23 UTC, otaviopace commented
I will close this one then, thanks for the help :blush:
One day I will make one Pull Request that helps hahahha

2020-08-20 20:23 UTC, closed without merging