Use more intra-doc-links in `core::fmt`
rust-lang/rust pull request #75853
Opened 2020-08-23 22:19 UTC by LeSeulArtichaut

This is a follow-up to #75819, which encountered some broken links due to #75176, so this PR contains the links that are blocked on #75819.

r? @jyn514

2020-09-03 21:47 UTC, jyn514 commented
This can be merged once you rebase :) assuming that `--stage 0` doesn't error which it might. If so it will have to wait another 5 weeks :/

2020-10-04 18:49 UTC, camelid commented
triage: Is this still blocked?

2020-10-04 19:04 UTC, camelid requested changes
It seems like all of these are auto-imported, which might resolve the blockage?

2020-10-04 19:04 UTC, camelid commented on library/core/src/fmt/mod.rs
> +/// [`write!`]: crate::write!
Isn't this auto-imported?

```suggestion
```

2020-10-04 19:04 UTC, camelid commented on library/core/src/fmt/mod.rs
> +/// [`write!`]: crate::write!
Same here.

```suggestion
```

2020-10-04 19:04 UTC, camelid commented on library/core/src/fmt/mod.rs
>      ///
This too:

```suggestion
```

2020-10-04 19:12 UTC, jyn514 commented
This should be ready to go after a rebase :)

2020-10-04 20:33 UTC, LeSeulArtichaut commented
Rebased

2020-10-04 21:34 UTC, jyn514 approved these changes
It works :tada:

2020-10-04 21:34 UTC, jyn514 commented
@bors r+ rollup

2020-10-04 23:24 UTC, camelid commented
Aren't all these links unnecessary though, since they're in the prelude?

2020-10-05 00:04 UTC, jyn514 commented
Sure, we can fix them in a follow-up. I mostly want to finally get this merged 😆

2020-10-05 05:00 UTC, merged