Detect turbofish with multiple type params missing leading `::`
rust-lang/rust pull request #76171
Opened 2020-08-31 17:25 UTC by estebank

Fix #76072.

2020-08-31 17:25 UTC, rust-highfive commented
r? @nikomatsakis

(rust_highfive has picked a reviewer for you, use r? to override)

2020-09-01 16:14 UTC, jyn514 commented on src/test/ui/did_you_mean/issue-40396.rs
> +    let x = std::collections::HashMap<i128, i128>::new(); //~ ERROR expected one of
```suggestion
    let x = std::collections::HashMap<i128, i128>::new(); //~ ERROR expected one of
    //~^ HELP use `::<...>` instead
```

2020-09-13 16:24 UTC, jonas-schievink commented
r? @davidtwco

2020-09-14 10:01 UTC, davidtwco requested changes
r=me after fixing this

2020-09-15 08:18 UTC, davidtwco commented
@bors r+

2020-09-15 12:16 UTC, merged