Implement as_ne_bytes() for integers and floats
rust-lang/rust pull request #76610
Opened 2020-09-11 19:47 UTC by hch12907

This is related to issue #64464.

I am pretty sure that these functions are actually const-ify-able, and technically as_bits() can also be implemented for floats, but I might need some comments on both.

2020-09-11 19:47 UTC, rust-highfive commented
r? @Mark-Simulacrum

(rust_highfive has picked a reviewer for you, use r? to override)

2020-09-11 20:16 UTC, Mark-Simulacrum commented
It seems like these should probably return arrays rather than slices. Those can then be coerced to a slice by the caller if needed, whereas the reverse requires a runtime check in general.

I am wondering if providing `&mut [u8; N]` access is warranted as well. It seems like a rare use case, but in the cases where you want it...


r? @LukasKalbertodt for unstable API signoff, though probably makes sense to wait for the conversion to arrays

2020-09-12 00:36 UTC, scottmcm commented
Assuming that some form of https://github.com/rust-lang/rfcs/pull/2981 will happen, does this need a distinct API?

2020-09-12 07:34 UTC, hch12907 commented
Modified `as_ne_bytes` to return arrays instead of slices.

> I am wondering if providing &mut [u8; N] access is warranted as well. 

I can add that, but I cannot really think of a use case for this - usually [u8; N] or Vec<u8> is used when people want to write to a particular byte.

> Assuming that some form of [rust-lang/rfcs#2981](https://github.com/rust-lang/rfcs/pull/2981) will happen, does this need a distinct API?

Interesting, I wasn't aware of that RFC. No, I don't think a distinct API will be needed if the RFC is merged, but I assume that it will be a while before the RFC is implemented, so it can be worthwhile to implement as_ne_bytes() first.

2020-09-12 10:20 UTC, roblabla commented
> Assuming that some form of rust-lang/rfcs#2981 will happen, does this need a distinct API?

Even if this happens, I still think having dedicated methods for some of these "basic" transmutation would be preferable from a UX standpoint. `as_ne_bytes` method on integers and floats is more discoverable and easier to understand than the generic mechanisms of the safe transmutation RFC. If/When that RFC is implemented, this method can be rewritten as a wrapper around safe transmutation to avoid the unsafe.

2020-09-12 20:50 UTC, HeroicKatora commented
> It seems like these should probably return arrays rather than slices.

If so then it seems useful to have a signature converting an array of numbers as well. That would in particular make it possible to use the standard `Read` and `Write` interfaces with integers and floats, without another buffer layer or multiple io-calls.

```
fn as_ne_bytes(slice: &[Self]) -> &[u8];
```

2020-09-19 17:58 UTC, LukasKalbertodt requested changes
Thanks for the PR!

I'm fine with merging these methods as unstable. Before stabilization we can reconsider if we actually need them or whether the safe transmute RFC is sufficient.

A few things:

- Please create a new dedicated tracking issue (or let me know if you prefer me to open it) and merge both feature names into `num_as_ne_bytes` (or so).
- The `transmutes` can be replaced by pointer casts (`self as *const Self as *const [u8; N]`). I don't know if this is less dangerous than `transmute`, but [`transmute` docs](https://doc.rust-lang.org/std/mem/fn.transmute.html#alternatives) mention it as an alternative that should be preferred.
- Not sure if it's worth first transmuting the floats into ints and then into the array. Why not transmute/cast them directly?

2020-09-20 17:12 UTC, hch12907 commented
The PR should be ready now.

2020-10-04 11:09 UTC, LukasKalbertodt approved these changes
Looks good to me!

2020-10-04 11:10 UTC, LukasKalbertodt commented
@bors r+

2020-10-04 13:50 UTC, merged