Add missing examples for MaybeUninit
rust-lang/rust pull request #77228
Opened 2020-09-26 13:32 UTC by GuillaumeGomez

r? @Dylan-DPC

2020-10-02 21:43 UTC, GuillaumeGomez commented
ping @Dylan-DPC

2020-10-05 09:06 UTC, GuillaumeGomez commented
r? @pickfire

2020-10-05 10:37 UTC, pickfire commented on library/core/src/mem/maybe_uninit.rs
> +    /// let v = MaybeUninit::new(vec![42]);
```suggestion
    /// let v: MaybeUninit<Vec<u8>> = MaybeUninit::new(vec![42]);
```
Add a type for clarification.

2020-10-05 10:38 UTC, pickfire requested changes
Other than the mentioned change looks good to me.

2020-10-05 10:39 UTC, pickfire commented on library/core/src/mem/maybe_uninit.rs
>      /// [`assume_init`]: MaybeUninit::assume_init
I feel like removing these links.

2020-10-05 10:40 UTC, pickfire commented on library/core/src/mem/maybe_uninit.rs
>      /// [type]: union.MaybeUninit.html
```suggestion
    /// [type]: MaybeUninit
```
I think this should work?

2020-10-05 13:55 UTC, pickfire approved these changes
Looks good to me.

2020-10-05 13:58 UTC, GuillaumeGomez commented
Let's merge then, thanks for the review!

@bors: r=pickfire rollup

2020-10-06 10:18 UTC, merged