Use a single function for query manipulations
rust-lang/rust pull request #77833
Opened 2020-10-11 20:56 UTC by cjgillot

There are three ways to invoke a query: get the value, ensure it runs, or have it automatically forced.

The three corresponding methods are merged into a single a single point of entry.
The goal is to increase the code sharing between the three cases.

2020-10-11 20:56 UTC, rust-highfive commented
r? @varkor

(rust_highfive has picked a reviewer for you, use r? to override)

2020-10-12 07:55 UTC, Xanewok commented
I vaguely recall that this may have affected performance (e.g. see careful `#[inline(never)]` and `#[inline(always)]` annotations), let's see if this has any impact:

@bors try @rust-timer queue

2020-10-12 07:55 UTC, rust-timer commented
Awaiting bors try build completion

2020-10-12 08:38 UTC, rust-timer commented
Queued f8ec1548e1d547c63153b5e662eda2db7306b2f2 with parent 63962f020385042d397a54b10bac1786eaa9b998, future [comparison URL](https://perf.rust-lang.org/compare.html?start=63962f020385042d397a54b10bac1786eaa9b998&end=f8ec1548e1d547c63153b5e662eda2db7306b2f2).

2020-10-12 13:40 UTC, rust-timer commented
Finished benchmarking try commit (f8ec1548e1d547c63153b5e662eda2db7306b2f2): [comparison url](https://perf.rust-lang.org/compare.html?start=63962f020385042d397a54b10bac1786eaa9b998&end=f8ec1548e1d547c63153b5e662eda2db7306b2f2).

Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. Please note that if the perf results are neutral, you should likely undo the rollup=never given below by specifying `rollup-` to bors.

Importantly, though, if the results of this run are non-neutral **do not** roll this PR up -- it will mask other regressions or improvements in the roll up.

@bors rollup=never

2020-10-12 13:41 UTC, Julian-Wollersberger requested changes
This refactoring should improve bootstrap times a bit, because it removes 216 000 [llvm-lines](https://rustc-dev-guide.rust-lang.org/profiling.html#optimizing-rustcs-bootstrap-times-with-cargo-llvm-lines) (-1%).

```
Before:  Lines   Copies         Function name
--------------   ------         -------------
20218434 (100%)  600060 (100%)  (TOTAL)
  457651 (2.3%)     414 (0.1%)  rustc_query_system::query::plumbing::get_query_impl::{{closure}}
  168207 (0.8%)     354 (0.1%)  rustc_query_system::query::plumbing::force_query_impl::{{closure}}
   95634 (0.5%)     207 (0.0%)  rustc_query_system::query::plumbing::incremental_verify_ich
   87688 (0.4%)    4335 (0.7%)  core::ops::function::FnOnce::call_once
   75830 (0.4%)     621 (0.1%)  <rustc_query_system::query::caches::DefaultCache<K,V> as rustc_query_system::query::caches::QueryCache>::iter
   69233 (0.3%)     207 (0.0%)  rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
   41047 (0.2%)     207 (0.0%)  rustc_query_system::query::plumbing::get_query_impl

After:  Lines    Copies         Function name
-------------    ------         -------------
20001669 (100%)  595297 (100%)  (TOTAL)
  434107 (2.2%)     354 (0.1%)  rustc_query_system::query::plumbing::call_query_impl::{{closure}}
   85516 (0.4%)    4257 (0.7%)  core::ops::function::FnOnce::call_once
   81774 (0.4%)     177 (0.0%)  rustc_query_system::query::plumbing::incremental_verify_ich
   75830 (0.4%)     621 (0.1%)  <rustc_query_system::query::caches::DefaultCache<K,V> as rustc_query_system::query::caches::QueryCache>::iter
   59785 (0.3%)     179 (0.0%)  rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
   59176 (0.3%)     177 (0.0%)  rustc_query_system::query::plumbing::load_from_disk_and_cache_in_memory
   47042 (0.2%)     177 (0.0%)  rustc_query_system::query::plumbing::call_query_impl
```
(Omitted all entries from other crates, mostly core, alloc and hashbrown).

2020-10-12 13:41 UTC, Julian-Wollersberger commented on compiler/rustc_query_system/src/query/plumbing.rs
> -    C: QueryCache,
Glad to see this `C: QueryCache` clause removed ^^
It is annoying when trying to make things `dyn`.

2020-10-12 19:53 UTC, cjgillot commented on compiler/rustc_middle/src/ty/query/plumbing.rs
> +                call_query::<queries::$name<'_>, _>(tcx, span, key, caller)
The point is to monomorphize `call_query` only once for each query. The easiest way is to call it through a monomorphic function.

2020-10-12 19:57 UTC, cjgillot commented
LLVM-lines was the target, but perf is bad. Bootstrap times are not a win either. This definitely needs more work.

2020-10-13 12:42 UTC, Julian-Wollersberger commented on compiler/rustc_middle/src/ty/query/plumbing.rs
> +                call_query::<queries::$name<'_>, _>(tcx, span, key, caller)
I just tested removing the wrapper. It removed another 39 022 llvm-lines.
I guess `call_query` is only monomorphized once for each query anyway, even though it is called from multiple places.

2020-11-20 22:16 UTC, cjgillot commented
Closed in favor of #78780.

2020-11-20 22:16 UTC, closed without merging