Add #[must_bind] attribute and lint
rust-lang/rust pull request #78715
Opened 2020-11-03 23:59 UTC by vi

Prototype implementation of https://internals.rust-lang.org/t/pre-rfc-must-bind/12658

Like `#[must_use]`, but also catches `let _ =`.

Intended to be used on semaphore guards and similar things where RAII guard is detached from the protected resource.
Beginner users often think that `_` is just a funny variable name and the guard will be dropped at the end of block instead of immediately. This may introduce silent logic error into the code.

TODO:

* Require `#[feature]` instead of insta-stable
* Proper test
* Add section to reference
* Probably refactor the code
* Decide on a specific lint text and attribute name
* Detecting `#[must_bind]` without `#[must_use]` as error.

---

Is this idea worth pursuing further or it's unlikely to go through even with the TODOs resolved?

2020-11-03 23:59 UTC, rust-highfive commented
r? @davidtwco

(rust_highfive has picked a reviewer for you, use r? to override)

2020-11-04 01:50 UTC, jyn514 commented on compiler/rustc_lint/src/unused.rs
> +    "Bogus `_` binding of a type flagged as `#[must_bind]`. Use something like `_guard`.",
```suggestion
    "types marked as `#[must_bind]` should be assigned to a variable, not dropped immediately",
```

2020-11-06 13:01 UTC, microsoft-sucks commented
Did not know `_` and `_guard` are different things. :bulb:   
Would be nice to warn the user if they used the wrong variant.

I general (not necessarily with `#[must_bind]`) I think people should be made aware of this difference. Is this even mentioned in the book?

2020-11-06 16:30 UTC, Mark-Simulacrum commented
I'm going to nominate for lang team because while I tend to think this is not the right fix (it's too similar to must_use, IMO), I think it may be worth trying to get a brief discussion at least on the `_` vs `_guard` difference; I think I frequently see users (including myself) forgetting that these two are different.

2020-11-06 18:30 UTC, vi commented
>  I think people should be made aware of this difference.

`#[must_bind]` attribute allows telling it to users at the moment where they need it the most, i.e. when dealing with data-less RAII guards (which some may consider an anti-pattern *per se*).

2020-11-08 12:25 UTC, davidtwco requested changes
As Mark as noted, needs lang team involvement but w/r/t implementation:

In addition to the changes you've noted in the MR description, I've added some nitpicks below - but the implementation looks broadly correct to me.

2020-11-08 12:25 UTC, davidtwco commented on compiler/rustc_lint/src/unused.rs
> +                                "Bogus `let _ =` binding of {}`{}`{}.  Use something like `let _guard =`.",
This should be changed to the same message suggested by [this comment](https://github.com/rust-lang/rust/pull/78715/files#r517053850).

2020-11-08 12:25 UTC, davidtwco commented on compiler/rustc_lint/src/unused.rs
> +                match local.pat.kind {
I'd prefer a guard in the match arm: `if !matches!(local.pat.kind, hir::PatKind::Wild)`

2020-11-08 12:25 UTC, davidtwco commented on compiler/rustc_lint/src/unused.rs
> +        match attr_to_check {
`if matches!(attr_to_check, WhatAttrToCheck::MustUse)` would be preferable

2020-11-08 12:25 UTC, davidtwco commented on compiler/rustc_lint/src/unused.rs
> +                ty::Closure(..) => match attr_to_check {
I'd prefer a guard in the match arm: `if matches!(attr_to_check, WhatAttrToCheck::MustUse)`

2020-11-08 12:25 UTC, davidtwco commented on compiler/rustc_lint/src/unused.rs
> +                ty::Generator(..) => match attr_to_check {
Likewise, guard in match arm.

2020-11-08 12:25 UTC, davidtwco commented on compiler/rustc_lint/src/unused.rs
> +        enum WhatAttrToCheck {
I'd rename this to something like `UnusedResultsAttr` (bikeshedding welcome) and I prefer it declared outside of the function and impl.

2020-11-12 18:29 UTC, vi commented
Note: [`#[must_not_await]`](https://github.com/rust-lang/rfcs/pull/3014) implementation may also touch this code.
Shall this pull request somehow prepare for addition of the third checking mode?

2020-11-12 20:08 UTC, jyn514 commented
@vi I think this change is small enough you don't have to worry about it, the author of `must_not_await` can take care of conflicts when they open their PR.

2020-11-23 22:48 UTC, Mark-Simulacrum commented
We discussed this change in the last language team meeting. I think the general feeling is that we agree that this is a problem worth solving, but this does not quite feel like the right solution, or at least a broader exploration of the design space would be warranted first.

The next step here is likely to close this PR in favor of a future project group, which would explore the solution space a bit more before proposing a concrete solution. If you'd be interested in driving this project group, please start a thread in [`#t-lang` on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang) and we can coordinate on who will liaison the group and the charter drafting. The project group scope can be adjusted for how much time interested parties have to invest, but likely at least a solution space of fixing confusion around `_` makes sense; an extension might be to look at temporary lifetime rules in general.

I'm leaving this PR open and nominated as an informed "Final comment period" on the suggested path above, and unless there's further discussion taking us in a different path the lang team will likely close this during next triage.

Thanks @vi!

2020-12-08 18:38 UTC, Mark-Simulacrum commented
Thanks! We've discussed a bit more over Zulip since then, and the current consensus remains that we would like to see an exploration of the design space some more perhaps targeted at solving the underlying problems rather than patching over it. Going to go ahead and close this PR for the time being, though.

2020-12-08 18:38 UTC, closed without merging