Normalize function type during validation
rust-lang/rust pull request #78969
Opened 2020-11-12 02:30 UTC by tmiasko

During inlining, the callee body is normalized and has types revealed,
but some of locals corresponding to the arguments might come from the
caller body which is not. As a result the caller body does not pass
validation without additional normalization.

Issue #78442.

2020-11-12 02:30 UTC, rust-highfive commented
r? @davidtwco

(rust_highfive has picked a reviewer for you, use r? to override)

2020-11-12 09:55 UTC, lcnr commented on compiler/rustc_mir/src/transform/validate.rs
> +                let param_env = self.param_env.with_reveal_all_normalized(self.tcx);
shouldn't `self.param_env` just be reveal all from the start here?

2020-11-12 09:55 UTC, lcnr approved these changes

2020-11-12 15:39 UTC, davidtwco requested changes
Implementation LGTM; can you add a test for #78442?

2020-11-12 20:02 UTC, tmiasko commented
* Extended one of existing test cases to cover #78442.
* Removed misleading compiletest annotations which had no effect.
* Modified validator to always use reveal_all_normalized as param env.

2020-11-13 14:40 UTC, davidtwco approved these changes

2020-11-13 14:40 UTC, davidtwco commented
@bors r+

2020-11-15 04:50 UTC, merged