Add column number support to Backtrace
rust-lang/rust pull request #79002
Opened 2020-11-12 20:56 UTC by est31

Backtrace frames might include column numbers.
Print them if they are included.

2020-11-12 20:56 UTC, rust-highfive commented
r? @dtolnay

(rust_highfive has picked a reviewer for you, use r? to override)

2020-11-12 21:03 UTC, dtolnay reviewed
Is this useful? I think I would prefer not to have these in the Debug representation. It just increases the chance of output lines being wrapped and harder to read.

2020-11-12 21:08 UTC, est31 commented
@dtolnay you can have `foo(bar(), bar())`. Then which of the two bar's are you inside?

I'll remove them from Debug though.

2020-11-12 21:26 UTC, RalfJung commented
> I'll remove them from Debug though.

So, `Display` has more information than `Debug`? That seems strange.

2020-11-12 21:32 UTC, est31 commented
> So, Display has more information than Debug? That seems strange.

Personally I don't really care either way and will adjust this PR to what the libs team thinks it should contain. Note though that the Debug impl can always be changed, while an argument can be made that the Display impl can't be changed after stabilization.

2020-11-12 21:37 UTC, yaahc commented
is the column information available in the BacktraceFrame itself? If so it might be a good idea to leave this for custom backtrace formats defined outside of std.

2020-11-12 21:49 UTC, est31 commented
@yaahc it is *possible* to add it in a fully backwards compatibe way but it'd fell like technical debt to me.

2020-11-12 22:27 UTC, yaahc commented
> 
> 
> @yaahc it is _possible_ to add it in a fully backwards compatible way but it'd feel like technical debt to me.

How so? I don't see the backwards compatibility as an issue given that the interface isn't even stable yet and I don't see how it's technical debt, given we're talking about not adding it to the default display / debug formats because @RalfJung and @dtolnay feel it would make the output harder to read.

2020-11-12 22:40 UTC, dtolnay commented
> > Is this useful? I think I would prefer not to have these in the Debug representation. It just increases the chance of output lines being wrapped and harder to read.
>
> @dtolnay you can have `foo(bar(), bar())`. Then which of the two bar's are you inside?
>
> I'll remove them from Debug though.

I missed that this PR affects not just Debug but Display as well (via [backtrace-rs/src/print.rs](https://github.com/rust-lang/backtrace-rs/blob/e7f61cc6b52791e0299bbd6ecfaa25e8ae02034a/src/print.rs#L280)) -- my preference is to have the column in neither representation. I think the vast majority of the time this would just be noise.

Definitely interested in supporting custom rendering of frames though.

2020-11-12 23:35 UTC, est31 commented
@yaahc 

> I don't see the backwards compatibility as an issue given that the interface isn't even stable yet

Right now backwards compatibility is not a concern, indeed. What I wanted to say with my statement above should be seen with the condition of stabilization in mind: *once Backtrace stabilizes*, a case can be made that columns may not be added to the output of Display, but they can be added to Debug.

It's also important to mention #72981 for context.

Regarding what I said about technical debt, note that I understood your comment in a way that you were trying to say that backwards compatibility isn't a concern because one can just add custom formatting APIs to std, or wrapper types that implement Display but print it in slightly different ways, etc. The original version of your comment before the two edits may have more clearly conveyed your intent, but the one I read was the second or third version of the comment. Anyways this becomes very meta now, let's move on :).

@dtolnay 

> my preference is to have the column in neither representation. I think the vast majority of the time this would just be noise.

Thanks for clarifying. I'll give two more arguments trying to convince you that it's not noise:

Another good use case is opening the line in the editor. E.g. I copy the line with the filename/line/col string and give it as a command to kate. Then it opens precisely at the location it's called at instead of me having to move my cursor inside the line. I perceive that as way more comfortable than having to search the invocation in that line manually myself. In IDEs like vscode where you can ctrl+click a path printed in the terminal and if it has line and column info it allows more precise jumps.

Second it would be consistent with panics printing column numbers as well as rustc error messages printing them. Back in 2017, you've r+d the FCP in #46762, approving the addition of column numbers to panic printing.

I hope these can swing your opinion. If not, as a last resort one can document that the display impl of backtraces *may* print column numbers at some point in the future and implementations parsing the output have to be ready for it.

Regarding the PR, I'll revert it to the old stage, to appease @RalfJung  as the change was mainly due to a misunderstanding. @dtolnay if the revert makes matters worse please say so :).

2020-11-13 00:09 UTC, dtolnay requested changes
Thanks for the details. That's convincing to me as far as Display, but neither point applies to Debug, so I would prefer to keep the column out of Debug still. Backtrace's Debug impl is actually quite sensitive because people get it spewed into their terminal when they unwrap an error containing a backtrace (e.g. the following kind of thing). See https://github.com/rust-lang/rust/pull/69038#pullrequestreview-356307723.

```rust
#[derive(Debug, Error)]
struct Error {
    source: std::io::Error,
    backtrace: Backtrace,
}
```

2020-11-13 00:21 UTC, dtolnay approved these changes

2020-11-13 00:21 UTC, dtolnay commented
@bors r+

2020-11-13 09:31 UTC, RalfJung commented
>  @RalfJung and @dtolnay feel it would make the output harder to read.

I never said that. I am in favor of adding column information to *both* `Display` and `Debug`. I consider it part of the implicit contract of these two traits that `Debug` might show *more* information, but will never show *less* information than `Display`.

2020-11-13 09:34 UTC, RalfJung commented
Given that the `Debug` impl seems to already be quite far from the internal representation, I think there are plenty of ways to include column number information that are not unduly verbose, e.g. by putting it together with the line number, or by putting both of them together with the filename.

2020-11-13 21:31 UTC, est31 commented
@RalfJung apparently some people parse the output of the Debug format, and the lang team doesn't want the Debug format to be changed until there are better ways to get the individual frames on stable Rust: https://github.com/rust-lang/rust/issues/65280#issuecomment-638963361

I guess that's not a guarantee that the Debug format won't ever change once backtrace is stable, but that it won't change for the time being until something like #78299 is merged and stabilized.

I agree that it's a bit inconsistent, but maybe the issue can be addressed at a later point in time, e.g. part of the proposed format changes in #65280.

Until then, see this PR as a step towards fixing #71706 :). Since you filed the issue, the panic backtrace has gotten column numbers in addition to the column number of the initial panic payload that's managed outside of the backtrace system. So this PR makes the two formats more consistent.

2020-11-14 13:16 UTC, RalfJung commented
> apparently some people parse the output of the Debug format

Oh wow that's horrible.^^

This is certainly not high-priority or urgent. What about leaving a comment in the `Debug` impl saying that some information, such as column numbers, is deliberately omitted, and linking some of the issues you mentioned to explain why?

2020-11-14 15:04 UTC, est31 commented
@RalfJung sounds fair. Once this PR is merged I'll make a PR to add such a comment.

2020-11-14 21:18 UTC, jonas-schievink commented
@bors r- failed in https://github.com/rust-lang/rust/pull/79056 (https://github.com/rust-lang/rust/runs/1400795467?check_suite_focus=true)

2020-11-15 05:13 UTC, est31 commented
Filed a miri PR: https://github.com/rust-lang/miri/pull/1626

2020-11-15 11:53 UTC, RalfJung commented
Miri failures should not prevent a PR from landing, so the failure must be caused by something else.

Actually, looks like there wasn't even a bors failure? Just PR CI failed? That's okay for Miri as long as the PR does not change the Miri submodule.

2020-11-15 12:03 UTC, RalfJung commented
I'd say, let's see what bors says.

@bors r=dtolnay rollup=iffy

2020-11-15 12:09 UTC, RalfJung commented
Oh I didn't see the submodule update. @bors r-

Please never add a submodule update that hasn't landed upstream yet!

2020-11-15 12:33 UTC, est31 commented
@RalfJung so you think it's #76999 to blame for this?

2020-11-15 12:50 UTC, RalfJung commented
Well, "blame"... with that change, for the first time are we running the "tools" builder in rollup PRs (submodule updates usually were no rolled up), which leads to this new confusion.

2020-11-15 12:50 UTC, RalfJung commented
@bors r=dtolnay

2020-11-18 05:17 UTC, est31 commented
@bors retry

2020-11-19 08:10 UTC, merged

2020-11-19 08:11 UTC, rust-highfive commented
📣 Toolstate changed by rust-lang/rust#79002!

Tested on commit rust-lang/rust@bf469eb6c20ccea05400a1942c70343f36705e1c.
Direct link to PR: <https://github.com/rust-lang/rust/pull/79002>

💔 miri on windows: test-pass → test-fail (cc @oli-obk @eddyb @RalfJung).