Add `impl Div<NonZeroU{0}> for u{0}` which cannot panic
rust-lang/rust pull request #79134
Opened 2020-11-17 12:34 UTC by ohadravid

Dividing an unsigned int by a `NonZeroUxx` requires a user to write (for example, in [this SO question](https://stackoverflow.com/questions/64855738/how-to-inform-the-optimizer-that-nonzerou32get-will-never-return-zero)):

```
pub fn safe_div(x: u32, y: std::num::NonZeroU32) -> u32 {
    x / y.get()
}
```

which generates a panicking-checked-div [assembly](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(fontScale:14,j:1,lang:rust,selection:(endColumn:2,endLineNumber:6,positionColumn:2,positionLineNumber:6,selectionStartColumn:2,selectionStartLineNumber:6,startColumn:2,startLineNumber:6),source:%27pub+fn+div(x:+u32,+y:+u32)+-%3E+u32+%7B%0A++++x+/+y%0A%7D%0Apub+fn+safe_div(x:+u32,+y:+std::num::NonZeroU32)+-%3E+u32+%7B%0A++++x+/+y.get()+//+an+unchecked+division+expected%0A%7D%27),l:%275%27,n:%270%27,o:%27Rust+source+%231%27,t:%270%27)),k:50,l:%274%27,n:%270%27,o:%27%27,s:0,t:%270%27),(g:!((h:compiler,i:(compiler:r1470,filters:(b:%270%27,binary:%271%27,commentOnly:%270%27,demangle:%270%27,directives:%270%27,execute:%271%27,intel:%270%27,libraryCode:%271%27,trim:%271%27),fontScale:14,j:1,lang:rust,libs:!(),options:%27-O%27,selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:%275%27,n:%270%27,o:%27rustc+1.47.0+(Editor+%231,+Compiler+%231)+Rust%27,t:%270%27)),k:50,l:%274%27,n:%270%27,o:%27%27,s:0,t:%270%27)),l:%272%27,n:%270%27,o:%27%27,t:%270%27)),version:4).
Avoiding the `panic` currently requires `unsafe` code.

This PR adds an `impl Div<NonZeroU{0}> for u{0}` which calls the `unchecked_div` intrinsic without any additional checks,
making the following code compile:

```
pub fn safe_div(x: u32, y: std::num::NonZeroU32) -> u32 {
    x / y
}
```

The doc is set to match the regular div impl [docs](https://doc.rust-lang.org/beta/src/core/ops/arith.rs.html#460).

I've marked these as stable because (as I understand it) trait impls are automatically stable. I'm happy to change it to unstable if needed.

Following @dtolnay template from a similar issue:
this adds the following **stable** impls, which rely on dividing unsigned integers by nonzero integers being well defined and previously would have involved unsafe code to encode that knowledge:
```
impl Div<NonZeroU8> for u8 {
    type Output = u8;
}
```
and equivalent for u16, u32, u64, u128, usize, but **not** for i8, i16, i32, i64, i128, isize (since -1/MAX_INT is undefined).

r? @dtolnay

2020-11-17 22:48 UTC, leonardo-m commented
I could use % (Rem) too...

2020-11-18 08:18 UTC, leonardo-m commented
See also: https://github.com/rust-lang/rust/issues/72762

2020-11-21 20:24 UTC, dtolnay requested changes

2020-11-21 20:24 UTC, dtolnay commented on library/core/src/num/nonzero.rs
> +                    // and -1/MIN is checked by because `self` is an unsigned int.
`-1/MIN` is 0. I think you mean `MIN/-1`.

2020-11-21 20:26 UTC, dtolnay commented
@rust-lang/libs:
@rfcbot fcp merge

This PR adds the following stable impls as a zero-overhead safe API around `std::intrinsics::unchecked_div` and `std::intrinsics::unchecked_rem`. They allow dividing unsigned integers by nonzero integers in a way that is statically known to be non-panicking. Previously it would have taken unsafe code to encode that knowledge.

```rust
impl Div<NonZeroU8> for u8 {
    type Output = u8;
}

impl Rem<NonZeroU8> for u8 {
    type Output = u8;
}

// and equivalent for u16, u32, u64, u128, usize
```

but **not** for i8, i16, i32, i64, i128, isize (since MIN/-1 is fallible).

2020-12-16 15:21 UTC, ohadravid commented
ping @Amanieu /  @BurntSushi ? 🙏

2020-12-16 16:51 UTC, mqudsi commented
Just because I got the notification for the final comment period: I opened an RFC in advance of a pull request to do exactly the same just a week ago - this issue had flown under the radar and slipped through my searches.

This is basically identical to the same findings and implementation I had come up with and is a pretty obvious win.

(Nitpick: There are a few comments that are hard-wrapped after just a few words, and "checked by because" -> "checked because")


👍

2020-12-27 11:19 UTC, dtolnay approved these changes

2020-12-27 11:19 UTC, dtolnay commented
@bors r+

2020-12-27 16:03 UTC, merged

2020-12-28 10:59 UTC, leonardo-m commented
It doesn't work in const functions:

`const fn safe_div(x: u32, y: std::num::NonZeroU32) -> u32 { x / y }`

2020-12-28 11:49 UTC, jplatte commented
@leonardo-m This is not at all specific to these new trait implementations, you can't use trait methods at all in const fn right now. There's an RFC for allowing this here: https://github.com/rust-lang/rfcs/pull/2632

The only reason primitive arithmetic works in const fn is that the desugaring of arithmetic operators to trait methods is somewhat of a lie: The compiler does a different translation for most (all?) operators applied to only primitive types. Since the `NonZero*` types are not primitives, that doesn't apply in this case.

2021-01-01 20:44 UTC, leonardo-m commented
You can add a TODO, so once that RFC is usable in the std lib, you can improve this code.

2021-01-07 12:31 UTC, leonardo-m commented
Also `DivAssign<NonZeroUxx>` is missing.