Add doc aliases for print macros
rust-lang/rust pull request #79232
Opened 2020-11-20 14:08 UTC by yoshuawuyts

Adds a variety of doc aliases for our print macros: "echo" for PHP and Bash. "print" for PHP and Lua, "printf" for C and C++, "console.log" for JavaScript. This only serves to make them easier to find in the doc search. Thanks!

2020-11-20 14:08 UTC, rust-highfive commented
r? @Mark-Simulacrum

(rust_highfive has picked a reviewer for you, use r? to override)

2020-11-20 14:36 UTC, yoshuawuyts commented
I've added `puts` for Ruby as suggested [here](https://twitter.com/gustavohoa/status/1329792011977838594) and `log` as a general keyword since "logging" is a commonly used umbrella term for all the APIs we're describing here.

2020-11-20 14:51 UTC, yoshuawuyts commented
Also added a "println" alias to `dbg` so that when you search for "println" in the docs you also find `dbg`. This is what the output looks like right now:

![Screenshot_2020-11-20 Results for println - Rust](https://user-images.githubusercontent.com/2467194/99813656-3adaf580-2b48-11eb-9603-aa2f0fc37d46.png)

2020-11-21 15:08 UTC, yoshuawuyts commented
It seems we're having a doc failure here; I can't render docs locally -- so I'm not sure what the right ordering here ought to be so I can make the tests pass.

## Error
```txt
Checking "macro-print" ... FAILED
==> '{"path":"std","name":"dbg"}' was supposed to be before '{"crate":"std","name":"dbg","path":"std","desc":"Prints and returns the value of a given expression for…","ty":14,"type":null,"is_alias":true,"alias":"macro:print","displayPath":"<span>std::</span>","fullPath":"<span>std::</span>dbg","href":"../std/macro.dbg.html"}'
==> '{"path":"std","name":"eprint"}' was supposed to be before '{"crate":"std","name":"eprint","path":"std","desc":"Prints to the standard error.","ty":14,"type":null,"is_alias":true,"alias":"macro:print","displayPath":"<span>std::</span>","fullPath":"<span>std::</span>eprint","href":"../std/macro.eprint.html"}'
==> '{"path":"std","name":"println"}' was supposed to be before '{"crate":"std","name":"println","path":"std","desc":"Prints to the standard output, with a newline.","ty":14,"type":null,"is_alias":true,"alias":"macro:print","displayPath":"<span>std::</span>","fullPath":"<span>std::</span>println","href":"../std/macro.println.html"}'
==> '{"path":"std","name":"eprintln"}' was supposed to be before '{"crate":"std","name":"eprintln","path":"std","desc":"Prints to the standard error, with a newline.","ty":14,"type":null,"is_alias":true,"alias":"macro:print","displayPath":"<span>std::</span>","fullPath":"<span>std::</span>eprintln","href":"../std/macro.eprintln.html"}'
```

2020-11-22 21:32 UTC, Mark-Simulacrum commented
![image](https://user-images.githubusercontent.com/5047365/99917752-4c570580-2ce0-11eb-8734-3085b6f1221b.png)

I guess it's looking for a prefix?

2020-12-04 15:51 UTC, GuillaumeGomez commented
Considering it's doc changes, please ping the @rust-lang/docs (or the @rust-lang/rustdoc) teams in the future. Strongly like the idea though!

2020-12-04 16:01 UTC, GuillaumeGomez commented on library/std/src/macros.rs
> +#[doc(alias = "print")]
Kinda useless no? :p

2020-12-04 16:02 UTC, GuillaumeGomez commented on library/std/src/macros.rs
> +#[doc(alias = "print")]
I don't think it's a good idea to add this alias. They'll find the `print` macro which talks about the `println` one.

2020-12-04 16:02 UTC, GuillaumeGomez commented on library/std/src/macros.rs
> +#[doc(alias = "print")]
Wouldn't add it.

2020-12-04 16:02 UTC, GuillaumeGomez commented on library/std/src/macros.rs
> +#[doc(alias = "print")]
Wouldn't add it.

2020-12-04 16:02 UTC, GuillaumeGomez commented on library/std/src/macros.rs
> +#[doc(alias = "print")]
Wouldn't add it.

2020-12-04 16:03 UTC, GuillaumeGomez commented on src/test/rustdoc-js-std/macro-print.js
> +        { 'path': 'std', 'name': 'dbg' },
Why this change?

2020-12-04 16:04 UTC, GuillaumeGomez requested changes
Please add more rustdoc-js-std tests for the newly added aliases. You can make multiple tests in one file if you want (take a look at `rustdoc-js/doc-alias.js` to see how).

2020-12-18 15:52 UTC, yoshuawuyts commented
I'm actually having second thoughts about these changes. That together with the process to landing it being more involved than I'd hoped it would be (tests require some effort) I think the best path forward for me here now is to close it. Perhaps someone more motivated than me can pick this back up in the future.

2020-12-18 16:12 UTC, jyn514 commented
@GuillaumeGomez I think your review was a lot more strict than it needed to be - I really don't think it makes sense for every `doc(alias)` change to need tests.

2020-12-18 16:12 UTC, Mark-Simulacrum commented
Why do we need tests for the added aliases? I am confused - we do not generally test documentation in specific, just that a feature works...

2020-12-18 16:18 UTC, GuillaumeGomez commented
I agree: after talking with other people, it seems a bit unnecessary. The only thing to do in the end is to add the `doc-alias` label on the PR so we can keep track of them in case we need to update the feature itself (very unlikely but who knows?).

Sorry about the confusion.

2020-12-18 16:19 UTC, GuillaumeGomez commented
My code comments still need answers/updates though. ;)

2020-12-18 16:54 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-9`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/1577799561) [(plain)](https://github.com/rust-lang/rust/commit/6470cd3b78f6a58925c935c2e5663b00f3759b0d/checks/1577799561/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
GITHUB_ENV=/home/runner/work/_temp/_runner_file_commands/set_env_cd4d2b08-ea1c-4263-8f21-454e91eed318
GITHUB_EVENT_NAME=pull_request
GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
GITHUB_GRAPHQL_URL=https://api.github.com/graphql
GITHUB_HEAD_REF=printf-alias
GITHUB_JOB=pr
GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_cd4d2b08-ea1c-4263-8f21-454e91eed318
GITHUB_REF=refs/pull/79232/merge
GITHUB_REPOSITORY_OWNER=rust-lang
GITHUB_RETENTION_DAYS=90
GITHUB_RUN_ID=430859652
GITHUB_RUN_NUMBER=21619
---
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1; python_version >= "2.7"->botocore==1.12.197->awscli)
Building wheels for collected packages: PyYAML
  Running setup.py bdist_wheel for PyYAML: started
  Running setup.py bdist_wheel for PyYAML: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-34nmcu7q/PyYAML/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp7id7lrbfpip-wheel- --python-tag cp36:
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
---
.................................................................................................... 9000/11178
.................................................................................................... 9100/11178
......................................................................i......i...................... 9200/11178
.................................................................................................... 9300/11178
.........iiiiii..iiiiii.i........................................................................... 9400/11178
.................................................................................................... 9600/11178
.................................................................................................... 9700/11178
.................................................................................................... 9800/11178
.................................................................................................... 9900/11178
---
Suite("src/test/assembly") not skipped for "bootstrap::test::Assembly" -- not in ["src/tools/tidy"]
Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 27 tests
iiiiiiiiiiiiiiiiiiiiiiiiiii

 finished in 0.066 seconds
Suite("src/test/incremental") not skipped for "bootstrap::test::Incremental" -- not in ["src/tools/tidy"]
Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
---
Suite("src/test/debuginfo") not skipped for "bootstrap::test::Debuginfo" -- not in ["src/tools/tidy"]
Check compiletest suite=debuginfo mode=debuginfo (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 116 tests
iiiiiiiiii.i.i..i..i...ii...i.i....ii..........iiii..........i....i...i.......ii.i.ii.....iiii.....i 100/116
test result: ok. 78 passed; 0 failed; 38 ignored; 0 measured; 0 filtered out; finished in 2.32s

 finished in 2.387 seconds
Suite("src/test/ui-fulldeps") not skipped for "bootstrap::test::UiFullDeps" -- not in ["src/tools/tidy"]
---
Checking "from_u" ... OK
Checking "keyword" ... OK
Checking "macro-check" ... OK
Checking "macro-print" ... FAILED
==> '{"path":"std","name":"dbg"}' was supposed to be before '{"crate":"std","name":"dbg","path":"std","desc":"Prints and returns the value of a given expression for …","ty":14,"type":null,"is_alias":true,"alias":"macro:print","displayPath":"<span>std::</span>","fullPath":"<span>std::</span>dbg","href":"../std/macro.dbg.html"}'
==> '{"path":"std","name":"eprint"}' was supposed to be before '{"crate":"std","name":"eprint","path":"std","desc":"Prints to the standard error.","ty":14,"type":null,"is_alias":true,"alias":"macro:print","displayPath":"<span>std::</span>","fullPath":"<span>std::</span>eprint","href":"../std/macro.eprint.html"}'
==> '{"path":"std","name":"println"}' was supposed to be before '{"crate":"std","name":"println","path":"std","desc":"Prints to the standard output, with a newline.","ty":14,"type":null,"is_alias":true,"alias":"macro:print","displayPath":"<span>std::</span>","fullPath":"<span>std::</span>println","href":"../std/macro.println.html"}'
==> '{"path":"std","name":"eprintln"}' was supposed to be before '{"crate":"std","name":"eprintln","path":"std","desc":"Prints to the standard error, with a newline.","ty":14,"type":null,"is_alias":true,"alias":"macro:print","displayPath":"<span>std::</span>","fullPath":"<span>std::</span>eprintln","href":"../std/macro.eprintln.html"}'
Checking "never" ... OK
Checking "quoted" ... OK
Checking "return-specific-literal" ... OK
Checking "return-specific" ... OK
Checking "return-specific" ... OK
Checking "should-fail" ... OK
Checking "string-from_ut" ... OK
Checking "struct-vec" ... OK
Checking "vec-new" ... OK


command did not execute successfully: "/usr/bin/node" "/checkout/src/tools/rustdoc-js/tester.js" "--crate-name" "std" "--resource-suffix" "1.50.0" "--doc-folder" "/checkout/obj/build/x86_64-unknown-linux-gnu/doc" "--test-folder" "/checkout/src/test/rustdoc-js-std"


failed to run: /checkout/obj/build/bootstrap/debug/bootstrap --stage 2 test --exclude src/tools/tidy
Build completed unsuccessfully in 0:34:10
```

</details>

2021-01-13 02:17 UTC, Dylan-DPC commented
@yoshuawuyts any updates on this?

2021-01-29 11:43 UTC, crlf0710 commented
@yoshuawuyts Triage: I'm closing this due to inactivity. Feel free to reopen or create a new pr when you have time to work on this again. Thanks!

2021-01-29 11:43 UTC, closed without merging