BTreeMap: remove Ord bound where it's not needed
rust-lang/rust pull request #79245
Opened 2020-11-20 20:43 UTC by ssomers

Some btree methods don't need an Ord bound and don't have one, and some that more obviously don't need it, do have one. Let's see if removing a bound harms API compatibility.

r? @Mark-Simulacrum

2020-11-21 01:52 UTC, jyn514 commented
I think this should have a reviewer from T-libs.

r? @dtolnay , maybe?

2020-11-24 18:10 UTC, ssomers commented
@rustbot modify labels: +S-waiting-on-review -S-waiting-on-author

2020-12-14 01:49 UTC, dtolnay commented
@rust-lang/libs:
@rfcbot fcp merge

This affects the following individual stable APIs. There are four kinds:

- Functions in which no comparison can ever take place because no elements exist to compare. `new()`, `default()`
- Functions that have no need to do comparisons. `map.clear()`, `entry.key()`
- Functions where all comparison takes place not in terms of `K`, but some other type `Q` for which `K: Borrow<Q>`. We only ever compare by borrowing from `K` and comparing using `Q: Ord`.
- Functions that just construct an iterator without doing work, but there remains an `Ord` bound on the `Iterator` impl. `symmetric_difference`, `union`

```diff
  impl<K, V> BTreeMap<K, V> {
      pub const fn new() -> BTreeMap<K, V>
-     where
-         K: Ord;

      pub fn clear(&mut self)
-     where
-         K: Ord;

      pub fn get<Q>(&self, key: &Q) -> Option<&V>
      where
-         K: Ord + Borrow<Q>,
+         K: Borrow<Q>,
          Q: ?Sized + Ord;

      pub fn get_key_value<Q>(&self, k: &Q) -> Option<(&K, &V)>
      where
-         K: Ord + Borrow<Q>,
+         K: Borrow<Q>,
          Q: ?Sized + Ord;

      pub fn contains_key<Q>(&self, key: &Q) -> bool
      where
-         K: Ord + Borrow<Q>,
+         K: Borrow<Q>,
          Q: ?Sized + Ord;

      pub fn get_mut<Q>(&mut self, key: &Q) -> Option<&mut V>
      where
-         K: Ord + Borrow<Q>,
+         K: Borrow<Q>,
          Q: ?Sized + Ord;

      pub fn remove<Q>(&mut self, key: &Q) -> Option<V>
      where
-         K: Ord + Borrow<Q>,
+         K: Borrow<Q>,
          Q: ?Sized + Ord;

      pub fn remove_entry<Q>(&mut self, key: &Q) -> Option<(K, V)>
      where
-         K: Ord + Borrow<Q>,
+         K: Borrow<Q>,
          Q: ?Sized + Ord;

      pub fn range<T, R>(&self, range: R) -> Range<'_, K, V>
      where
-         K: Ord + Borrow<T>,
+         K: Borrow<T>,
          T: ?Sized + Ord,
          R: RangeBounds<T>;

      pub fn range_mut<T, R>(&mut self, range: R) -> RangeMut<'_, K, V>
      where
-         K: Ord + Borrow<T>,
+         K: Borrow<T>,
          T: ?Sized + Ord,
          R: RangeBounds<T>;

      pub fn split_off<Q>(&mut self, key: &Q) -> Self
      where
-         K: Ord + Borrow<Q>,
+         K: Borrow<Q>,
          Q: ?Sized + Ord;
}

  impl<K, V> Default for BTreeMap<K, V>
- where
-     K: Ord;

  impl<K, V> Debug for Entry<'_, K, V>
  where
-     K: Ord + Debug,
+     K: Debug,
      V: Debug;

  impl<K, V> Debug for VacantEntry<'_, K, V>
  where
-     K: Ord + Debug,
+     K: Debug;

  impl<K, V> Debug for OccupiedEntry<'_, K, V>
  where
-     K: Ord + Debug,
+     K: Debug,
      V: Debug;

  impl<'a, K, V> Entry<'a, K, V> {
      pub fn or_insert(self, default: V) -> &'a mut V
-     where
-         K: Ord;

      pub fn or_insert_with<F>(self, default: F) -> &'a mut V
      where
-         K: Ord,
          F: FnOnce() -> V;

      pub fn key(&self) -> &K
-     where
-         K: Ord;

      pub fn and_modify<F>(self, f: F) -> Self
      where
-         K: Ord,
          F: FnOnce(&mut V);

      pub fn or_default(self) -> &'a mut V
      where
-         K: Ord,
          V: Default;
  }

  impl<'a, K, V> VacantEntry<'a, K, V> {
      pub fn key(&self) -> &K
-     where
-         K: Ord;

      pub fn into_key(self) -> K
-     where
-         K: Ord;

      pub fn insert(self, value: V) -> &'a mut V
-     where
-         K: Ord;
  }

  impl<'a, K, V> OccupiedEntry<'a, K, V> {
      pub fn key(&self) -> &K
-     where
-         K: Ord;

      pub fn remove_entry(self) -> (K, V)
-     where
-         K: Ord;

      pub fn get(&self) -> &V
-     where
-         K: Ord;

      pub fn get_mut(&mut self) -> &mut V
-     where
-         K: Ord;

      pub fn into_mut(self) -> &'a mut V
-     where
-         K: Ord;

      pub fn insert(&mut self, value: V) -> V
-     where
-         K: Ord;

      pub fn remove(self) -> V
-     where
-         K: Ord;
  }

  impl<T> BTreeSet<T> {
      pub const fn new() -> BTreeSet<T>
-     where
-         T: Ord;

      pub fn range<K, R>(&self, range: R) -> Range<'_, T>
      where
-         T: Ord + Borrow<K>,
+         T: Borrow<K>,
          K: ?Sized + Ord,
          R: RangeBounds<K>;

      pub fn symmetric_difference<'a>(&'a self, other: &'a BTreeSet<T>) -> SymmetricDifference<'a, T>
-     where
-         T: Ord;

      pub fn union<'a>(&'a self, other: &'a BTreeSet<T>) -> Union<'a, T>
-     where
-         T: Ord;

      pub fn clear(&mut self)
-     where
-         T: Ord;

      pub fn contains<Q>(&self, value: &Q) -> bool
      where
+         T: Ord + Borrow<Q>,
-         T: Borrow<Q>,
          Q: ?Sized + Ord;

      pub fn remove<Q>(&mut self, value: &Q) -> bool
      where
-         T: Ord + Borrow<Q>,
+         T: Borrow<Q>,
          Q: ?Sized + Ord;

      pub fn split_off<Q>(&mut self, key: &Q) -> Self
      where
-         T: Ord + Borrow<Q>,
+         T: Borrow<Q>,
          Q: ?Sized + Ord;
  }

  impl<T> Default for BTreeSet<T>
- where
-     T: Ord;
```

2020-12-14 01:50 UTC, dtolnay requested changes
I would request to keep the `Ord` bound on all Entry methods that mutate the collection, and on symmetric_difference/union.

2020-12-14 03:31 UTC, ssomers commented
> I would request to keep the `Ord` bound on all Entry methods that mutate the collection

Does that include the methods that do not actually mutate but allow mutation, i.e., `OccupiedEntry::get_mut` and `into_mut`? If so I can't imagine why plain `get` is allowed to give up its Ord bound.

2020-12-14 13:16 UTC, ssomers commented
> I would request to keep the Ord bound […] on symmetric_difference/union.

Pointing out that inconsistency in the initial form of this PR, answers my implicit question: why impose unused bounds anywhere? It allows tuning the implementation later.

Another inconsistency is that `BTreeMap::get` loses the bound, but `BTreeSet::get` doesn't, and can't as long as it reuses an implementation of `Recover`. So I'm motivated to turn away from touching those.

That leaves version 2 with this set of changes:

```diff
  impl<K, V> BTreeMap<K, V> {
      pub const fn new() -> BTreeMap<K, V>
-     where
-         K: Ord;

      pub fn clear(&mut self)
-     where
-         K: Ord;
  }

  impl<K, V> Default for BTreeMap<K, V>
- where
-     K: Ord;
  }

  impl<K, V> Debug for Entry<'_, K, V>
  where
-     K: Ord + Debug,
+     K: Debug,
      V: Debug;
  }

  impl<K, V> Debug for VacantEntry<'_, K, V>
  where
-     K: Ord + Debug,
+     K: Debug;
  }

  impl<K, V> Debug for OccupiedEntry<'_, K, V>
  where
-     K: Ord + Debug,
+     K: Debug,
      V: Debug;
  }

  impl<'a, K, V> Entry<'a, K, V> {
      pub fn key(&self) -> &K
-     where
-         K: Ord;

      pub fn get(&self) -> &V
-     where
-         K: Ord;

      pub fn get_mut(&mut self) -> &mut V
-     where
-         K: Ord;

      pub fn into_mut(self) -> &'a mut V
-     where
-         K: Ord;
  }

  impl<'a, K, V> VacantEntry<'a, K, V> {
      pub fn key(&self) -> &K
-     where
-         K: Ord;

      pub fn into_key(self) -> K
-     where
-         K: Ord;
  }

  impl<'a, K, V> OccupiedEntry<'a, K, V> {
      pub fn key(&self) -> &K
-     where
-         K: Ord;
  }

  impl<T> BTreeSet<T> {
      pub const fn new() -> BTreeSet<T>
-     where
-         T: Ord;

      pub fn clear(&mut self)
-     where
-         T: Ord;
  }

  impl<T> Default for BTreeSet<T>
- where
-     T: Ord;
```

2020-12-14 13:16 UTC, BurntSushi commented
Can someone say why we would want to do this, other than minor simplifications in the type signature? Is there a concrete benefit to this? Conversely, if we do this and accidentally remove `Ord` from an API that wants it in the future, we're stuck. (The APIs proposed look fine to me, so maybe that's a weak argument, but it still seems like a risk to me.)

2020-12-14 13:41 UTC, ssomers commented
>  Is there a concrete benefit to this?

- Consistency in the current API: I've read posts, and long ago experienced myself, stumbling upon the bound on `new` while making code generic over types of containers (e.g. when comparing BTreeSet vs. HashSet). Though I can't find any concrete traces of that.
- Consistency in the future API. Methods like `drain_filter` and `first_entry` impose an Ord bound just because it seems popular somehow, but their behaviour is close to `iter` which doesn't. The recent `into_keys` and `into_values` impose an Ord bound, while `into_iter` doesn't. I'm sure explicitly listing the Ord bound everywhere would help realizing that, but the second version doesn't do that anymore.
- In implementations in btree, the inability to call `new` or `default` requires us to rewrite it sometimes, though I'm surprised to only find one occurrence that made it to master.

2020-12-14 13:45 UTC, BurntSushi commented
Thanks for explaining! I'm a little skeptical that those things are worth the risk here personally. The last bullet point (writing generic code) seems the most compelling to me I think, but I'm having a hard time of thinking of how that actually happens in practice.

2020-12-26 22:28 UTC, ssomers commented
Rebased and removed the bound from a recent test method.

2021-01-11 02:05 UTC, dtolnay commented
@ssomers, would you be able to respond to this:

> The last bullet point (writing generic code) seems the most compelling to me I think, but I'm having a hard time of thinking of how that actually happens in practice.

by sharing some examples of how the `new` or `default` bounds become problematic in practice?

2021-01-11 10:56 UTC, ssomers commented
> 
> 
> @ssomers, would you be able to respond to this:
> 
> > The last bullet point (writing generic code) seems the most compelling to me I think, but I'm having a hard time of thinking of how that actually happens in practice.
> 
> by sharing some examples of how the `new` or `default` bounds become problematic in practice?

I struggle to understand the question, because "the last bullet point" is illustrated by the very first change in this PR. It's probably about the first bullet point. I've again tried in vain to find back anyone's post about that, so I reconstructed [a playground example comparing `BTreeSet` and `HashSet`](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3004eaed5f100a45ab130ab2de387e61). The idea is you want to write some shared, generic, order-independent code, but you can afford to populate the collections with collection-specific code (read: you are impatient to get some generic code working in Rust). `BTreeSet` is being a pain here, requiring `Ord` willy-nilly, while `HashSet` doesn't bother us with its hashing mechanism.

2021-01-13 03:40 UTC, KodrAus commented
Nominating for discussion at the next Libs meeting. The FCP is finished here but it looks like there were some lingering concerns?

It would be good to get a resolution on this.

2021-01-22 00:21 UTC, KodrAus commented
We haven't been able to get this to the top of our nominated list to discuss yet, but @rust-lang/libs are we happy with https://github.com/rust-lang/rust/pull/79245#issuecomment-757874170 to unblock this from merging?

2021-01-22 11:17 UTC, KodrAus commented
[This comment from `hashbrown`](https://github.com/rust-lang/hashbrown/issues/225#issuecomment-763161858) seems very tangentially related. It’s talking about `HashMap` rather than `BTreeMap`, but looks like it ran into a case with specialization where they need to introduce missing `Hash` bounds. The hashing machinery is a bit different from comparison so it might have very little bearing here, but does seem like a valid example of why we might prefer to keep seemingly unneeded bounds.

2021-01-22 13:52 UTC, ssomers commented
That's inspiring. Let's take a closer look at `HashMap`/`HashSet`:
- They have constructors (and `default`) without any trait bound on the key type, I think that's what the comment from hashbrown is about. This PR wants the same for btree's cousins.
- They have constructors like `with_hasher` [with no bound on that hasher at all (apart from `Sized`)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d276079d7711ad2fe1f43f188bb6cb8a). That surprised me, because you actually pass an instance of a completely unconstrained type. Anyway, there's nothing remotely equivalent in the btree world.
- Members like `iter()`, `len()` and `clear()` come for free, without bounds, just like in btree's cousins.
- `Debug` implementation come for free, while currently some of btree's cousins have an `Ord` bound.
- If you want to actually insert elements, you need your bounds, both for the key type and the hasher type, just like you need to know `Ord` in btree's cousin.
- Once you did that, `clone()` doesn't need those bounds anymore, just like in btree's cousin. Makes sense because you just need to clone stuff, no need to know about hashing or comparing keys. It looked inconsistent to me that `BTreeMap::clone()` sometimes wants to invoke `BTree::new()` but is not allowed to. Now I see the implementation of `BTreeMap::clone()` is somewhat inconsistent. In other words: part of my quest was "if there is a reason why `new()` might need the `Ord` bound, how can `clone()` escape that?" and the answer is "because it should clone the conclusions of whatever decisions the original `new()` made.

So I no longer see the fact that `BTreeMap::new` has the bound it has as inconsistent with itself, but inconvenient. And inconsistent with `HashMap` but maybe the blame is on their side.

However, that still leaves the inconsistency that some of btree's `Debug` implementations claim they may need to compare keys in order to show things. Which is no doubt due to the fact that something like `OccupiedEntry::key` claims it may need to compare keys.

2021-01-28 12:41 UTC, ssomers commented
Note that this attempt to stir up the stable API was to clear the sky for another inconsistency: the new, unstable `into_keys`, `into_values` and `drain_filter` have the `K: Ord` bound., while `into_iter` and all other methods returning iterators do not.

2021-01-29 12:08 UTC, KodrAus commented
Thanks for looking into that @ssomers!

So the current state of this PR now is that just the `clear` and `Debug` impls have lost their `Ord` bounds. That seems pretty reasonable to me.

I couldn't imagine that `into_keys` or `into_values` could _need_ the `Ord` bound, since they're effectively `into_iter().map(|(k, _)| k)` and `into_iter().map(|(_, v)| v)`. As for `drain_filter`, since that's mutating the map is there any chance it could need to recompare things to rebuild the map?

I guess if we could go back we could've just always required all the bounds all the time, since chances are when using a collection you'll end up wanting to use one of its methods that needs them eventually anyway so in some sense all we're really doing is deciding which arbitrary sets of methods to leak that actual requirement on, and guess at whether we'll ever regret it.

2021-01-29 13:49 UTC, ssomers commented
> As for `drain_filter`, since that's mutating the map is there any chance it could need to recompare things to rebuild the map?

I've added that question to #70530, so we don't need to discuss it here, but the answer is a clear yes and no… My initial version needed to recompare (not to rebuild, but to find back its own position after some rebuilds). But now that it has grown up, it's as unlikely for `drain_filter` to need comparing as it is for `OccupiedEntry::remove_entry`. Or as in [this comment on the initial `Ord` bound](https://github.com/rust-lang/rust/pull/68770#issuecomment-605493463-permalink), it would be bad if these methods used their `Ord` bound.

So if they shouldn't, why allow them to, why suggest they do? I see these possible reasons now:
- For ease of understanding, always require all the bounds all the time. That's not the route taken up to now.
- To stress that method behaviour depends on the `Ord` implementation, like the order in which iterators yield elements. That's not the route taken.
- For debugging. Allow a `debug_assert` that all elements are still in order after `OccupiedEntry::remove_entry`. That's not exploited anywhere now.
- Cater for the future. I guess that depends on what you consider to be the `Ord` bound. If you state `Ord` is only about comparing elements, then `BTreeMap::new()` cannot need it because it will never have anything to compare, and `OccupiedEntry::remove_entry` cannot need it either because all the other elements were in order already. If you state the `Ord` bound is whatever future interface other BTreeMap methods requesting the `Ord` bound will want, then I can imagine the need. E.g. if `Ord` were extended with a kind of `size_hint` (not the `size_of` but the number of unequal valid instances of the type), then `BTreeMap::new()` might want to adapt node capacity to that. But it's a stretch.
- Symmetry with `HashMap`. Hardly a solid reason to keep `new` bounded but a reason to bring `clear` in the clear.

2021-01-30 13:30 UTC, ssomers commented
I've added two things:

- A commit to make the existing bounds explicit where they were sneakily declared far away.
- In the 2nd commit, apart from `clear` and `Debug` impls, also removed the bound from the unstable `into_keys` and `into_values`.

2021-01-31 12:07 UTC, KodrAus commented
> To cater for the unknown.

This is probably our most compelling reason to keep bounds right now. But the changes you've made here seem pretty defensible and are a subset of the ones originally proposed in the FCP that already completed. Until we have some concrete recommendations on when bounds are needed in our collection types we're probably just going to have to tread carefully like you're already doing.

@dtolnay are you satisfied with the state of things here so we can merge?

2021-01-31 19:18 UTC, dtolnay commented
Could someone make an updated list of every API change, like https://github.com/rust-lang/rust/pull/79245#issuecomment-744432723? This PR is difficult to review otherwise because all the API changes are taking place in lines of code that are *not* touched.

2021-01-31 19:20 UTC, dtolnay commented
For review it might even be better to do this as 2 PRs, one moving `Ord` bounds from impl blocks to functions (no API change) and then an API changing PR that only removes bounds.

2021-01-31 22:39 UTC, ssomers commented
I've isolated the first commit as #81610 and will rebase here if and when it gets merged.
@rustbot modify labels: +S-waiting-on-author -S-waiting-on-review

2021-02-06 08:42 UTC, ssomers commented
I backed out on all changes in `Entry` because the "everything `Ord`" rule applies there.
@rustbot modify labels: -S-waiting-on-author +S-waiting-on-review

2021-02-08 07:18 UTC, dtolnay approved these changes

2021-02-08 07:18 UTC, dtolnay commented
This is a subset of the changes from the prior completed FCP.

```diff
  impl<K, V> BTreeMap<K, V> {
      pub fn clear(&mut self)
-     where
-         K: Ord;
  }

  impl<T> BTreeSet<T> {
      pub fn clear(&mut self)
-     where
-         T: Ord;
  }
```

and a few unstable ones (tracking issue #75294):

```diff
  impl<K, V> BTreeMap<K, V> {
      pub fn into_keys(self) -> IntoKeys<K, V>
-     where
-         K: Ord;
- 
      pub fn into_values(self) -> IntoValues<K, V>
-     where
-         K: Ord;
  }
```

2021-02-08 07:18 UTC, dtolnay commented
@bors r+

2021-02-08 10:46 UTC, merged

2021-04-06 10:46 UTC, pthariensflame commented
`relnotes` needed here?

2021-04-06 12:16 UTC, ssomers commented
I wouldn't know the answer even if I understood the question, but as a summary: the only change to the public stable API is that `BTreeMap::clear` and `BTreeSet::clear` no longer have the Ord bound.