Add as_ref and as_mut methods for Bound
rust-lang/rust pull request #80444
Opened 2020-12-28 16:52 UTC by glittershark

Add as_ref and as_mut method for std::ops::range::Bound, patterned off
of the methods of the same name on Option.

I'm not quite sure what the process is for introducing new feature gates (this is my first contribution) so I've left these ungated, but happy to do whatever is necessary to gate them.

2020-12-28 16:52 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @dtolnay (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2020-12-28 16:55 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/1618207131) [(plain)](https://github.com/rust-lang/rust/commit/9734e35404dc53efbac1ce7156da94f56cd5880a/checks/1618207131/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling unwind v0.0.0 (/checkout/library/unwind)
error: associated function has missing stability attribute
   --> library/core/src/ops/range.rs:684:5
    |
684 | /     pub fn as_ref(&self) -> Bound<&T> {
685 | |         match *self {
686 | |             Included(ref x) => Included(x),
687 | |             Excluded(ref x) => Excluded(x),
688 | |             Unbounded => Unbounded,
690 | |     }
    | |_____^

error: associated function has missing stability attribute
error: associated function has missing stability attribute
   --> library/core/src/ops/range.rs:694:5
    |
694 | /     pub fn as_mut(&mut self) -> Bound<&mut T> {
695 | |         match *self {
696 | |             Included(ref mut x) => Included(x),
697 | |             Excluded(ref mut x) => Excluded(x),
698 | |             Unbounded => Unbounded,
700 | |     }
    | |_____^

error: aborting due to 2 previous errors
error: aborting due to 2 previous errors

error: could not compile `core`

To learn more, run the command again with --verbose.
command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "check" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "16" "--release" "--color" "always" "--features" "panic-unwind backtrace compiler-builtins-c" "--manifest-path" "/checkout/library/test/Cargo.toml" "--message-format" "json-render-diagnostics"
failed to run: /checkout/obj/build/bootstrap/debug/bootstrap check
Build completed unsuccessfully in 0:01:18
```

</details>

2021-01-11 02:57 UTC, dtolnay requested changes
This needs an `unstable` attribute (https://rustc-dev-guide.rust-lang.org/stability.html) and a Library Tracking Issue (https://github.com/rust-lang/rust/issues/new/choose).

2021-01-14 02:16 UTC, glittershark commented
@dtolnay done, I think. Let me know if I did it right

2021-01-14 03:26 UTC, dtolnay approved these changes
Thanks!

2021-01-14 03:27 UTC, dtolnay commented
@bors r+

2021-01-14 23:07 UTC, merged

2021-05-16 10:25 UTC, drmason13 commented on library/core/src/ops/range.rs
> +    /// Converts from `&mut Bound<T>` to `Bound<&T>`.
```suggestion
    /// Converts from `&mut Bound<T>` to `Bound<&mut T>`.
```

2021-06-07 15:03 UTC, glittershark commented on library/core/src/ops/range.rs
> +    /// Converts from `&mut Bound<T>` to `Bound<&T>`.
#86101 😄