clippy fixes for librustdoc
rust-lang/rust pull request #80546
Opened 2020-12-31 01:52 UTC by matthiaskrgr

fixes clippy warnings of type:
match_like_matches_macro
or_fun_call
op_ref
needless_return
let_and_return
single_char_add_str
useless_format
unnecessary_sort_by
match_ref_pats
redundant_field_names

2020-12-31 01:52 UTC, rust-highfive commented
Some changes occurred in intra-doc-links.

cc @jyn514

2020-12-31 01:52 UTC, rust-highfive commented
r? @ollie27

(rust-highfive has picked a reviewer for you, use r? to override)

2020-12-31 05:45 UTC, jyn514 commented
r? @jyn514

2020-12-31 06:01 UTC, jyn514 requested changes

2020-12-31 06:01 UTC, jyn514 commented on src/librustdoc/passes/collect_intra_doc_links.rs
> +    let sp = span_of_attrs(attrs).unwrap_or_else(|| item.source.span());
span() is trivial.

2020-12-31 06:01 UTC, jyn514 commented on src/librustdoc/passes/doc_test_lints.rs
> +            let sp = span_of_attrs(&item.attrs).unwrap_or_else(|| item.source.span());
etc. for the rest of the span() calls.

2020-12-31 10:29 UTC, matthiaskrgr commented on src/librustdoc/clean/cfg.rs
> +            Cfg::Cfg(name, _) => matches!(name, sym::debug_assertions | sym::target_endian),
`Cfg::Cfg(name, _) => name == sym::debug_assertions || name ==  sym::target_endian,` ?

2020-12-31 10:33 UTC, matthiaskrgr commented on src/librustdoc/clean/types.rs
>      crate fn is_type_alias(&self) -> bool {
It's used here https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/render/mod.rs#L3843

2020-12-31 14:22 UTC, jyn514 commented on src/librustdoc/clean/types.rs
>      crate fn is_type_alias(&self) -> bool {
Oh ugh, trait impls are a mess and people complain whenever we change the display. Ok, this is fine for now then.

2020-12-31 14:23 UTC, jyn514 commented on src/librustdoc/clean/cfg.rs
> +            Cfg::Cfg(name, _) => matches!(name, sym::debug_assertions | sym::target_endian),
Yup! That looks good :)

2020-12-31 16:14 UTC, LingMan requested changes

2020-12-31 16:14 UTC, LingMan commented on src/librustdoc/html/format.rs
> +                clean::WherePredicate::BoundPredicate { ref ty, ref bounds } => {
Unneeded deref and unneeded `ref` keywords. Same for the other arms of this `match`.

2020-12-31 16:22 UTC, jyn514 commented on src/librustdoc/clean/cfg.rs
> +        matches!(*self, Cfg::Cfg(name, _) if name == sym::target_feature)
@LingMan no, `target_feature` is a constant, not an enum variant.

2020-12-31 16:36 UTC, LingMan commented on src/librustdoc/clean/cfg.rs
> +        matches!(*self, Cfg::Cfg(name, _) if name == sym::target_feature)
@jyn514 Why would that be a problem?
```
fn should_use_with_in_description(&self) -> bool {
    matches!(self , Cfg::Cfg(sym::target_feature, _))
}
```
passes `./x.py check` just fine. Is there a semantic difference I'm not aware of?

2020-12-31 17:06 UTC, jyn514 commented on src/librustdoc/clean/cfg.rs
> +        matches!(*self, Cfg::Cfg(name, _) if name == sym::target_feature)
I didn't know that was a valid pattern :eyes: I found that [it works](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2b83c5cd77948578dc1ce82ee1f6908f) even if there's [no path in front](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c9c88098a92c53c04540e9c658213348), but I could have sworn that meant a variable binding instead ... I'm really confused :confused:

2020-12-31 17:21 UTC, LingMan commented on src/librustdoc/clean/cfg.rs
> +        matches!(*self, Cfg::Cfg(name, _) if name == sym::target_feature)
It becomes a variable binding if you remove the `use inner::C;`.

2021-01-01 19:17 UTC, matthiaskrgr commented on src/librustdoc/clean/cfg.rs
> +            Cfg::Not(ref child) => matches!(**child, Cfg::Cfg(..)),
Cfg::Not contains a `Box<Cfg>`, I'm not sure how to match on that.

2021-01-01 19:24 UTC, LingMan commented on src/librustdoc/clean/cfg.rs
> +            Cfg::Not(ref child) => matches!(**child, Cfg::Cfg(..)),
`Cfg::Not(box Cfg::Cfg(..))`

2021-01-01 20:19 UTC, matthiaskrgr commented on src/librustdoc/clean/cfg.rs
> +            Cfg::Not(ref child) => matches!(**child, Cfg::Cfg(..)),
interesting, thanks :D

2021-01-01 21:04 UTC, jyn514 commented
@bors delegate=LingMan

2021-01-01 21:59 UTC, LingMan commented
@bors r+ rollup

2021-01-02 15:31 UTC, merged