Stabilize core::task::ready!
rust-lang/rust pull request #81050
Opened 2021-01-15 18:31 UTC by yoshuawuyts

_Tracking issue: https://github.com/rust-lang/rust/issues/70922_ 

This PR stabilizes the `task::ready!` macro. Similar to https://github.com/rust-lang/rust/pull/80886, this PR was waiting on https://github.com/rust-lang/rust/pull/80886 to be fixed.

The `task::ready!` API has existed in the futures ecosystem for several years, and was added on nightly last year in https://github.com/rust-lang/rust/pull/70817. The motivation for this macro is the same as it was back then: virtually every single manual future implementation makes use of this; so much so that it's one of the few things included in the [futures-core](https://docs.rs/futures-core/0.3.12/futures_core) library.

r? @tmandry 

cc/ @rust-lang/wg-async-foundations @rust-lang/libs 

## Example
```rust
use core::task::{Context, Poll};
use core::future::Future;
use core::pin::Pin;

async fn get_num() -> usize {
    42
}

pub fn do_poll(cx: &mut Context<'_>) -> Poll<()> {
    let mut f = get_num();
    let f = unsafe { Pin::new_unchecked(&mut f) };
    
    let num = ready!(f.poll(cx));
    // ... use num

    Poll::Ready(())
}
```

2021-01-15 18:50 UTC, jyn514 commented
Looking at the implementation of the macro, I would expect to use `?` instead, since that makes it more clear that it short-circuits and returns if the task isn't ready. Have you considered implementing `Try` for `Poll`?

cc @scottmcm since I know you've been thinking a lot about Try recently

2021-01-15 22:25 UTC, yoshuawuyts commented
@jyn514 Poll already implements Try if the inner type is an Option, Result, or Result of Option. I forget the reason, but I believe this may simply not be possible to implement on any type T without specialization.

Actually that makes for an interesting proposition. When I introduced this API early last year specialization seemed unstable enough that I didn't feel comfortable to even suggest it. However now.. perhaps? I haven't kept up with the progress of min_specialization enough to know whether it's feasible. If we could just make this work with `?` that'd for sure be preferable.

2021-01-16 00:01 UTC, scottmcm commented
@jyn514 For the `Poll` impls, @cramertj knows more than I do.

2021-01-16 02:07 UTC, sfackler commented
I'd be pretty hesitant to make `?` behave wildly differently for different variants of Polls. I think we're just stuck with the fact that `?` on Poll maps through to the inner value.

2021-01-16 09:32 UTC, yoshuawuyts commented
> 
> 
> I'd be pretty hesitant to make `?` behave wildly differently for different variants of Polls. I think we're just stuck with the fact that `?` on Poll maps through to the inner value.

That's fair; in which case I think we should proceed with stabilizing `task::ready!` as per this PR.

2021-01-22 11:38 UTC, KodrAus commented
@rfcbot fcp merge

This stabilizes the `task::ready!` macro, which is used in manual futures implementations to early-return on `Poll::Pending`.

2021-01-22 12:32 UTC, m-ou-se commented
> Poll already implements Try if the inner type is an Option, Result, or Result of Option.

`?` on `Poll` types like `Poll<Option<Result>>` working on the innermost None/Err instead of the outermost Pending was stabilized as part of the `futures_api`, but was never really discussed much separately in the context of stabilization (or FCP'd separately). This behaviour was called out in [one comment](https://github.com/rust-lang/rust/issues/59725#issuecomment-480391536) on the `futures_api` stabilization PR, but that comment seems to have been ignored. :(

2021-01-22 12:50 UTC, KodrAus commented
Do we expect manual futures implementations to continue to become more niche as `async` becomes available in more contexts?

2021-01-22 20:12 UTC, yoshuawuyts commented
> Do we expect manual futures implementations to continue to become more niche as async becomes available in more contexts?

To some degree. For example `async gen fn` may replace manual `Stream` impls just like `gen fn` might for `Iter`, but for industrial-grade libraries it seems likely manual implementations will continue to be used. Returning anonymous futures/streams are not nearly as flexible as named impls.

Also for some async traits like `AsyncRead` and `AsyncWrite` there is no clear path yet how language level features could obsolete the need to implement these by hand.

I think the usage of `ready!` will likely roughly remain where it is now. Arguably it's already a bit of a niche: understanding how to implement futures takes a fair bit of learning. I suspect more language features will not so much take away from existing implementations, as make async Rust accessible to a greater number of people.

2021-02-02 01:27 UTC, tmandry commented
My concern with stabilizing this (and with the futures API it's based on) is that `std::task::ready!` is easily confused with [`std::future::ready`](https://doc.rust-lang.org/stable/std/future/fn.ready.html), a function with very different semantics.

I remember thinking of other names in the past, like `try_poll!`. But I didn't feel like opening a bikeshed back then. So I guess I'm doing that now 😅

2021-02-03 15:43 UTC, yoshuawuyts commented
@tmandry are you able to file a concern about naming? We probably should ensure we don't merge this until that's resolved.

I don't feel strongly about either `ready!` or `try_poll!`. The reasoning in favor of `try_poll!` makes sense to me and I wouldn't be opposed to going with that instead.

2021-02-03 16:48 UTC, taiki-e commented
@tmandry 

> I remember thinking of other names in the past, like `try_poll!`. But I didn't feel like opening a bikeshed back then. So I guess I'm doing that now 😅

Personally, I don't think the name `try_poll` is easy-to-understand. AFAIK, many (most?) of the use of the term "try" in the APIs of the standard library (and `futures`) relates to results, options, or `Try` traits. I think it's confusing to add another `try_*` that behaves wildly differently from the `Try` implementation of `Poll`.

FWIW, In the past `futures` had a macro called `try_poll` that did something wildly different. https://github.com/rust-lang/futures-rs/issues/1698. (There was also a macro called `try_ready`.)

2021-02-05 00:18 UTC, tmandry commented
> @tmandry are you able to file a concern about naming?

Not sure, but I can try...

@rfcbot concern naming

2021-02-05 00:19 UTC, tmandry commented
Another idea I remember is `poll_await!`, since you're basically awaiting a future inside of a `poll` implementation.

2021-02-05 09:46 UTC, m-ou-se commented
@rfcbot concern naming

2021-02-13 05:37 UTC, taiki-e commented
> Another idea I remember is `poll_await!`, since you're basically awaiting a future inside of a `poll` implementation.

I'm not sure it's preferable to use names that include `await`.
Unlike `.await`, `ready` returns early rather than suspending.
I know that some people are already writing broken code using `ready` like `.await` (i.e., the code that misunderstands that the state when `ready` is called is maintained in the next `poll*` call), but names that include `await` may be more misleading.

2021-04-02 19:10 UTC, tmandry commented
I can keep coming up with ideas :).. `pend_on!()`

In fact, it seems to me like `pending!()` would have been the better name in the first place, since we are pending on that future (though I doubt everyone agrees). Consider: "awaiting" and "pending" are roughly synonyms, but "pending" doesn't come with the same baggage @taiki-e mentioned in their last comment.

The biggest downside is probably that it will confuse existing users who are used to `ready!`. But if async is successful, we will have many more future users than the users we have today, so if we pay that cost today for less confusion tomorrow, I think it's worthwhile.

In any case my opinion right now is that we should not stabilize this as `ready!`. To me, the potential for confusion with [`std::future::ready`](https://doc.rust-lang.org/stable/std/future/fn.ready.html) outweighs the benefits of adding this macro to the standard library today.

2021-04-03 11:28 UTC, yoshuawuyts commented
> so if we pay that cost today for less confusion tomorrow, I think it's worthwhile.

That seems like a good reason to scrap `ready!` as a possibility for the API name. To me `pending!` seems like a reasonable suggestion!

2021-04-04 23:46 UTC, jonhoo commented
Another direction we could go is something like `try_await!` — to indicate that this attempts an await, but doesn't _actually_ await. Or maybe `try_resolve!` or `try_ready!`. Or if we want to avoid `try` (as it's usually used with `Result`): `complete!`. Or, if you want to go the way of monads, `lift!` ;)

2021-05-05 20:38 UTC, bstrie commented
>> Poll already implements Try if the inner type is an Option, Result, or Result of Option.
>
> ? on Poll types like Poll<Option<Result>> working on the innermost None/Err instead of the outermost Pending was stabilized as part of the futures_api, but was never really discussed much separately in the context of stabilization (or FCP'd separately). This behaviour was called out in one comment on the futures_api stabilization PR, but that comment seems to have been ignored. :(

I don't think this would be impossible to change over an edition (you'd need to selectively resolve `?` based on the edition, like is done for `.into_iter` on arrays), though it's too late for the 2021 edition. Still, someone might want to file an issue to discuss whether this should be done for the following edition, which could allow this to be deprecated in favor of `?` someday.

2021-05-05 21:29 UTC, dtolnay requested changes, later dismissed
We discussed this stabilization in the libs team meeting earlier today and are on board with stabilizing this behavior as a macro with a suitable name.

We felt vaguely positive about the name `pend!` and there were no objections or other popular contenders, so those of us present feel prepared to stabilize as `core::task::pend!`, but want to open an opportunity for public discussion as well, since this name has not been raised in the thread so far.

## Rationale

This is a macro. **The core thing that this macro does** (the reason it needs to be a macro in the first place) is a control flow operation of early-returning `Poll::Pending` if necessary. The action verb "pend" characterizes informing the caller that pending is taking place.

As a verb that pertains to the behavior of this operation *as a macro*, as opposed to anything that a function would be capable of doing, we don't expect that this name would clash with the name of any functions -- unlike `ready!` (https://doc.rust-lang.org/stable/std/future/fn.ready.html) or `pending!` (https://doc.rust-lang.org/stable/std/future/fn.pending.html).

Neither `ready!` nor `pending!`, as adjectives, characterize the early-return nature of this macro.

None of the other suggestions such as `try_ready!` or `try_resolve!` or `try_await!` or `resolve!` or `complete!` characterize what this macro does to "make a thing ready"/"resolved"/"complete", which is that all it does is inform the caller that pending is taking place, until such time as it no longer is.

2021-05-14 19:37 UTC, nikomatsakis commented
I've been giving this some thought and I've decided I have to weigh in. `pend!` seems like an ungreat name to me. As a verb, it means "to await judgement or decision". But that seems to be focused on the path where `pend!` returns. But I think it makes more sense to focus on the success path, like the name `ready!` does. 

I see the point of wanting a verb, but unfortunately there may not be a verb that is like "take the value if it is ready" (besides `await`, I suppose). 

I'm curious what other names were considered? Do we have a list of alternatives?

2021-05-14 19:38 UTC, nikomatsakis commented
I'm wondering about `if_ready!` as a name:

```rust
use std::task::{pend, Context, Poll};
use std::future::{self, Future};
use std::pin::Pin;

pub fn do_poll(cx: &mut Context<'_>) -> Poll<()> {
    let mut fut = future::ready(42);
    let fut = Pin::new(&mut fut);

    let num = if_ready!(fut.poll(cx));
    // ... use num

    Poll::Ready(())
}
```

2021-05-14 19:52 UTC, dtolnay commented
One possible alternative to shift emphasis to the straight-line path rather than the early return:

```rust
let num = whenever!(fut.poll(cx));
```

Conceptually: this gives you the requested value whenever it's ready. Before that point it'll escape out by early returning Pending.

2021-05-15 00:44 UTC, tmandry commented
> But that seems to be focused on the path where `pend!` returns. But I think it makes more sense to focus on the success path, like the name `ready!` does.

I see your point, but how is this different from `.await`?

These are analogous operations in my mind. "await" is in the definition of "pend" and they're roughly synonyms, except that `pend` brings to mind the actual value `Poll::Pending` being returned at the level of the `poll` method, which is fitting.

2021-05-15 00:46 UTC, tmandry commented
With all that said, I don't hate `if_ready!` either.

It's just more awkward to type.

2021-05-15 00:54 UTC, dtolnay commented
Mostly just to rule this out:

How nuts would it be to overload `.await` for this? `let x = fut.poll(cx).await;` &mdash; If syntactically inside of an async fn / async block / async closure, you get the current behavior of expecting a Future on the lhs and doing the generator transform. If syntactically not inside any of those, it instead expects a Poll on the lhs and early returns Pending.

2021-05-15 08:25 UTC, nikomatsakis commented
@tmandry 

The biggest problem I see with `pend` is that it is just really non-obvious. If you're reading code, I really don't think people are going to understand what is happening. 

I guess I find *await* to have a more "active" feeling. It's creating the fiction that this is a blocking function: so what happens here? Execution stops and waits for the value to be ready, and then continues. I don't get that from `pend!`. Maybe if lots of languages used it I would. =)

2021-05-15 08:27 UTC, nikomatsakis commented
@dtolnay overloading `.await` doesn't seem like a good idea to me:

* using await but forgetting to make the fn async has to be a common thing to do, so this will result in confusing diagnostics;
* it'll be confusing when reading the code in cases where you are not sure if this is an async fn or not (e.g., a diff);
* who knows, we might want that syntax later!

2021-05-16 15:25 UTC, withoutboats commented
I personally think `ready` was a great name for this macro and was discounted too fast in this discussion. The difference between the macro and the future module function is not such a big deal any more than the fact that `try` constructs try blocks & `Try` is a trait for types that can have `?` applied to them; its just something people need to learn.

2021-05-16 16:25 UTC, bstrie commented
And if people are in favor of someday pursing the deprecation of this macro in favor of `?`, then it becomes less crucial to pick a perfect name for what could just be an interim solution.

2021-06-16 01:29 UTC, tmandry commented
I am coming around to `if_ready`. It is quite obvious what it does the first time you read it, which I think is important for such a pervasive function.

In addition to the conflict issue, I guess I never found `ready` to be an intuitive name. It looks like an adjective describing a future, but doesn't imply what the relationship between the object and adjective is (are you asserting that the future is now ready? is it a verb, as in modifying the future to a ready state? etc.) This creates a fair amount of uncertainty about what's going on for an uninitiated reader.

If you've written enough manual poll implementations yourself you'll internalize what it means, and if I had done so early on in my journey with async I might have a different perspective. But "understanding the futures model without having written a lot of futures code" is a probably a significant cohort of users.

That being said, if everyone else thinks `ready` is a good name I don't want to block on it.

2021-06-16 03:26 UTC, scottmcm commented
> Mostly just to rule this out: How nuts would it be to overload `.await` for this?

In general I'd prefer not to do contextual meanings because of macros.  If one has `foo!(x.await)` (with the macro just taking an `expr`, not anything fancy) then it's not clear which behaviour is being requested, nor which behaviour will be used.

2021-06-23 10:48 UTC, yoshuawuyts commented
I'm just catching up on this thread, and it seems like we have soft consensus on `ready!` as the name for the macro? It's not necessarily everyone's first choice, but everyone appears to be mostly okay with it?

2021-06-24 18:30 UTC, nikomatsakis commented
I prefer `if_ready!` myself. I think it is easier to understand what it does.

2021-06-25 21:33 UTC, yoshuawuyts commented
Happy to change it to `if_ready!` instead! I guess similar question: even though it may not be everyone's first choice, does anyone here strongly oppose `if_ready!` as the name?

Personally I don't have a real preference whether we name it `ready!` or `if_ready!`. I mostly care that this functionality is available on stable in the nearish term. In the end I consider this macro to be important but niche, and as long as we name it something not too unreasonable I think we'll be fine.

2021-07-01 12:53 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/2962662184) [(plain)](https://github.com/rust-lang/rust/commit/a099190bf0577a86472f25f9ba8a161ab81d32c0/checks/2962662184/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling std v0.0.0 (/checkout/library/std)
error[E0583]: file not found for module `ready`
  --> library/core/src/task/mod.rs:13:1
   |
13 | mod ready;
   |
   |
   = help: to create the module `ready`, create file "library/core/src/task/ready.rs" or "library/core/src/task/ready/mod.rs"
   Compiling compiler_builtins v0.1.46
   Compiling unwind v0.0.0 (/checkout/library/unwind)
error[E0432]: unresolved import `if_ready`
  --> library/core/src/task/mod.rs:15:9
  --> library/core/src/task/mod.rs:15:9
   |
15 | pub use if_ready::if_ready;
   |         ^^^^^^^^ use of undeclared crate or module `if_ready`
error: aborting due to 2 previous errors

Some errors have detailed explanations: E0432, E0583.
For more information about an error, try `rustc --explain E0432`.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `core`

To learn more, run the command again with --verbose.
command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "check" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "16" "--release" "--color" "always" "--features" "panic-unwind backtrace compiler-builtins-c" "--manifest-path" "/checkout/library/test/Cargo.toml" "--message-format" "json-render-diagnostics"
failed to run: /checkout/obj/build/bootstrap/debug/bootstrap check
Build completed unsuccessfully in 0:01:11
```

</details>

2021-07-01 12:54 UTC, yoshuawuyts commented
Changed the PR to use `if_ready!` instead. I think it's now up to either @rust-lang/libs or @rust-lang/wg-async-foundations to make a final decision on naming, and then merge it.

2021-07-02 08:47 UTC, joshtriplett commented
Nominating for the next @rust-lang/libs-api meeting.

2021-07-02 10:22 UTC, zeenix commented
> Nominating for the next @rust-lang/libs-api meeting.

Also for @rust-lang/wg-async-foundations meeting today.

2021-07-02 17:17 UTC, zeenix commented
> > Nominating for the next @rust-lang/libs-api meeting.
> 
> Also for @rust-lang/wg-async-foundations meeting today.

FYI: we discussed this today and `if_ready!` has the blessing of @rust-lang/wg-async-foundations. Now it's up to the @rust-lang/libs-api folks. :)

2021-07-07 19:07 UTC, m-ou-se commented
@rfcbot cancel

2021-07-07 19:07 UTC, m-ou-se commented
@rfcbot merge

2021-07-07 19:08 UTC, joshtriplett commented
To confirm: this new FCP is based on the name `if_ready!`.

2021-07-08 09:48 UTC, withoutboats commented
I want to register why I think this choice is a mistake. I don't think its a disaster or anything and I don't have time to engage much, but I think it would be better to not rename this. I think the cost of renaming has been sharply underestimated in this process.

This isn't a new API. A macro with this functionality is provided by all of these crates: `futures`/`futures_core`, `tokio`, `async_std`, `smol`, and. `futures_lite`.  It's basically impossible to write a crate in the async ecosystem today without depending on at least one of these. In all of these crates, this macro is called `ready!`.

Setting aside the question of whether this strong consensus is evidence that `ready!` is a good name or just normalcy bias (though I note that the maintainers of most of these crates :+1:'d my earlier comment in support of `ready!`), renaming this macro when stabilizing it in std increases substantially the churn costs. All of those libraries I cited have a pretty strong stability commitment, which means they will all continue to provide a macro with this functionality under the name `ready!`. `ready!` isn't going anywhere therefore; users will have to learn that the `ready!` macro from all of these libraries has the same functionality as `if_ready!` from std, and the stated clarity benefits of `if_ready` over `ready` (which I personally think are minimal to non-existent) will be reduced by the fact that users working in this area will have to read and understand code containing both forms.

I would encourage the teams to be a bit more quietist and only change the naming of ecosystem-consensus APIs with a really strong motivation. I don't think the motivation here is strong enough.

2021-07-08 12:21 UTC, BurntSushi commented
One blind spot I have is that I don't actually know who the stakeholders are here. I mean, I realize they are, at minimum, the maintainers of the crates that @withoutboats listed and I do know a couple of the names involved there, but that's it. So I guess I would definitely be curious to hear from the stakeholders about this. What do you think we should do here?

I think that if `ready!` is going to have a continued and prominent spot in the ecosystem regardless of what name we pick here, then there are perhaps more severe downsides to choosing a different name than has been considered here I think. (Which I think is just echoing @withoutboats.)

2021-07-08 19:14 UTC, hawkw commented
> So I guess I would definitely be curious to hear from the stakeholders about this. What do you think we should do here?

So, here's my two cents, although please note that this is just my personal opinion and not that of the entire Tokio team.

It's worth noting that in Tokio's [stability policy](https://tokio.rs/blog/2020-12-tokio-1-0#a-stability-guarantee), we've stated that we're not going to publish a 2.0 release until at least 3 years after 1.0 was published, and that we'll continue actively supporting 1.0 for at least 5 years regardless of whether or not a 2.0 is released. So, while we could certainly deprecate `ready!` in favor of `if_ready!`, `ready!` is going to remain in Tokio's API surface for a while, even if it's deprecated. I can't speak for other async ecosystem crates, but I imagine that, for example, `async-std` isn't particularly eager to release a 2.0 just to remove `ready!`, either. :)

Now, I don't think that having a deprecated `ready!` and an `if_ready!` in the API is a *huge* issue. It makes things a little bit more confusing for new users, but IMO, it's far from the biggest learnability obstacle, so the impact of that is fairly negligible. On the other hand, while I don't particularly want to restart a bikeshed over the name of the macro, I also don't find `if_ready!` to be a significant improvement over `ready!` (personally, I actually think the `if_ready!` naming is _less_ clear>1</sup>, but it's not a big deal).

Finally, there's the amount of work to update all the various downstream crates that use `ready!`, the documentation, examples, etc, to switch from `ready!` to `if_ready!`. This would potentially be a lot of code to change, but changing it is quite easy --- in most cases, maintainers could just do a find-and-replace and everything would be fine. So I would characterize the cost of this as "annoying", but not terrible.

My personal perspective is that, overall, the gain from renaming `ready!` to `if_ready!` is pretty negligible, and the impact of keeping deprecated API `ready!` macros around is not great but also pretty negligible. So, all things being equal, if it doesn't _really_ matter, I would err on the side of avoiding ecosystem churn for a name change that doesn't really feel like a meaningful improvement --- I'm inclined to agree with @withoutboats. But...if a majority of other folks agree that the renaming is important and has real value, the resulting ecosystem churn is going to be an annoyance, not a disaster. :woman_shrugging: 

---
<sup>1</sup>I'd expect a macro of the form `if_<whatever>!(<expr>)` to _only_ evaluate `<expr>` if `<cond>` is true, which is...kind of the opposite of what this macro does.

2021-07-09 08:42 UTC, withoutboats commented
Yea, speaking as someone who maintains a big pile of downstream user code, I would find these libraries deprecating their ready macro to be annoying, not a disaster, but definitely annoying. I think it's important to keep in mind that async/await has been stable for almost 2 years now during which async Rust has had explosive growth. It's not the same phase anymore as 2018/2019.

I think the misinterpretation @hawkw describes is an important downside of if_ready, but I have a more abstract concern along the same lines: I don't think there's any succinct name for this macro that will make its operation immediately clear. Using a slightly opaque name like "ready" is *helpful* in this case because it makes it more obviously a "term of art" macro that users realize they need to look up to understand. With a name that tries to be self-explanatory, but could have misinterpretations, users are more likely to persist in their misunderstanding because they think they intuitively understand what the macro does without looking it up, but they are maybe wrong.

2021-07-09 17:06 UTC, yoshuawuyts commented
> So I guess I would definitely be curious to hear from the stakeholders about this. What do you think we should do here?

I've shared my own thoughts on this [before](https://github.com/rust-lang/rust/pull/81050#issuecomment-868845116) (I'm okay with either name), but not yet from the perspective of an `async-std` maintainer.

I don't think there's anything stopping us from deprecating [`async_std::task::ready!`](https://docs.rs/async-std/1.9.0/async_std/task/macro.ready.html) and adding `async_std::task::if_ready!` within the current major. We probably wouldn't want to use the `#[deprecated]` tag since it would cause warnings (which in turn may break downstream user's CI if they disallow warnings). Instead we'd likely want to mark it as a deprecation through docs-only, and possibly sprinkle in some CSS to make it stand out. In a future 2.0 version (which we plan to do once more async lang feature stabilize) we would then complete the transition.

I believe the `async-std` project could work with both `ready!` and `if_ready!`, and as such poses no technical restrictions on the choice of naming.

2021-07-14 19:45 UTC, joshtriplett commented
We discussed this in today's @rust-lang/libs-api meeting. We found the most recent round of arguments compelling: neither `ready` nor `if_ready` is especially clear, and `ready!` at least has precedent. In addition, `ready!` being a macro does make it clear that it *could* affect control flow. It also helps that this is `std::task::ready!`, with no plans to add it to any kind of prelude or similar.

Not everyone was concerned about the issue of deprecation; some of us felt that whether this was called `ready!` or `if_ready!` there'd still be a long transition period from framework-specific paths to the standard library path. But we all roughly agreed that renaming doesn't really seem worthwhile.

@rfcbot cancel

2021-07-14 19:45 UTC, joshtriplett commented
Shall we merge this as `std::task::ready!`?

@rfcbot merge

2021-07-15 07:10 UTC, Kestrer commented
> `ready!` is going to remain in Tokio's API surface for a while, even if it's deprecated

FWIW [Tokio doesn't actually expose `ready!`](https://github.com/tokio-rs/tokio/blob/8f10d816131868030996b5079fbc632750e69332/tokio-stream/src/macros.rs#L61). But so many other crates do that the point still stands.

2021-07-23 13:48 UTC, yoshuawuyts commented
I've updated the PR back to `core::task::ready!`, reflecting the decision made by the libs team in https://github.com/rust-lang/rust/pull/81050#issuecomment-880161319. That means that once the FCP expires this PR should be good to merge!

2021-07-28 14:55 UTC, m-ou-se commented
@bors r+

2021-07-29 00:31 UTC, merged