Reduce code generated by dbg! macro
rust-lang/rust pull request #81233
Opened 2021-01-21 01:51 UTC by lzutao

The expanded code before/after: <https://rust.godbolt.org/z/hE3j95>.

2021-01-21 01:51 UTC, rust-highfive commented
r? @m-ou-se

(rust-highfive has picked a reviewer for you, use r? to override)

2021-01-21 02:24 UTC, KodrAus commented
Thanks! @bors r+ rollup

2021-01-21 10:21 UTC, ojeda requested changes

2021-01-21 10:21 UTC, ojeda commented on library/std/src/macros.rs
> +    // of `eprintln!`. Because `file!` could contains a `{` or
```suggestion
    // of `eprintln!` because `file!` could contain a `{` or
```

2021-01-21 10:21 UTC, ojeda commented on library/std/src/macros.rs
> +    // `$val` expression could be a block (`{ .. }`). In this case, the `eprintln!`
```suggestion
    // `$val` expression could be a block (`{ .. }`), in which case the `eprintln!`
```

2021-01-21 16:45 UTC, ojeda commented on library/std/src/macros.rs
> +    // of `eprintln!`. Because `file!` could contains a `{` or
No problem at all!

2021-01-22 04:24 UTC, KodrAus commented
@bors r+ rollup

2021-01-22 19:00 UTC, merged