Refactor `PrimitiveTypeTable` for Clippy
rust-lang/rust pull request #81680
Opened 2021-02-02 21:09 UTC by camsteffen

I removed `PrimitiveTypeTable` and added `PrimTy::ALL` and `PrimTy::from_name` in its place. This allows Clippy to use `PrimTy::from_name` for the `builtin_type_shadow` lint, and a `const` list of primitive types is deleted from Clippy code. All changes should be a little faster, if anything.

2021-02-02 21:09 UTC, rust-highfive commented
r? @oli-obk

(rust-highfive has picked a reviewer for you, use r? to override)

2021-02-02 21:21 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/1817861906) [(plain)](https://github.com/rust-lang/rust/commit/fa17f1d4d71708ac2240eccfa6caf6147922b475/checks/1817861906/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.channel         := nightly
configure: rust.debug-assertions := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
Diff in /checkout/compiler/rustc_resolve/src/diagnostics.rs at line 718:
                         );
                     }
                 }
-                Scope::BuiltinTypes => suggestions.extend(PrimTy::ALL.iter().filter_map(|prim_ty| {
-                    let res = Res::PrimTy(*prim_ty);
-                    filter_fn(res).then_some(TypoSuggestion::from_res(prim_ty.name(), res))
-                })),
+                Scope::BuiltinTypes => {
+                    suggestions.extend(PrimTy::ALL.iter().filter_map(|prim_ty| {
+                        let res = Res::PrimTy(*prim_ty);
Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt" "--config-path" "/checkout" "--edition" "2018" "--unstable-features" "--skip-children" "--check" "/checkout/compiler/rustc_resolve/src/diagnostics.rs"` failed.
If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
+                        filter_fn(res).then_some(TypoSuggestion::from_res(prim_ty.name(), res))
+                    }))
             }
 
             None::<()>
failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test --stage 2 src/tools/tidy
```

</details>

2021-02-03 11:19 UTC, oli-obk requested changes
Great refactoring!

Could you also add some documentation on the new constant and function? Other than those nits, r=me

2021-02-03 11:19 UTC, oli-obk commented on compiler/rustc_hir/src/hir.rs
> +    pub const ALL: [Self; 17] = [
Please leave a comment on this mentioning that any changes should also be reflected in `from_name`. Also leave the opposite comment on `from_name`.

2021-02-03 14:35 UTC, camsteffen commented
Good! I wasn't sure if the associated const was kosher. 😄 

Changes made.

2021-02-03 14:35 UTC, oli-obk commented
@bors r+

2021-02-06 20:55 UTC, merged