formatting
rust-lang/rust pull request #81840
Opened 2021-02-06 20:47 UTC by ibraheemdev

2021-02-06 20:47 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @dtolnay (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2021-02-08 01:54 UTC, dtolnay requested changes
Thanks, this looks good but could you please update the PR subject and commit title to something a bit more descriptive of this specific change?

2021-02-08 02:16 UTC, ibraheemdev commented
Updated

2021-02-08 02:28 UTC, dtolnay approved these changes
Thanks!

2021-02-08 02:29 UTC, dtolnay commented
@bors r+ rollup

2021-02-08 23:37 UTC, merged