Stabilize `peekable_peek_mut`
rust-lang/rust pull request #81938
Opened 2021-02-09 21:20 UTC by lukaslueg

Resolves #78302. Also adds some documentation on `std::iter::Iterator::peekable()` regarding the new method.

The feature was added in #77491 in Nov' 20, which is recently, but the feature seems reasonably small. Never did a stabilization-pr, excuse my ignorance if there is a protocol I'm not aware of.

2021-02-09 21:21 UTC, rust-highfive commented
r? @Mark-Simulacrum

(rust-highfive has picked a reviewer for you, use r? to override)

2021-02-13 22:15 UTC, Mark-Simulacrum commented
r? @KodrAus

2021-02-21 09:22 UTC, KodrAus reviewed
Thanks for the PR @lukaslueg! 🙇 

I hope you don't mind I've just pushed a couple commits to your branch to fix a merge conflict and update the stable version to `1.52.0`.

Would you be happy to squash these commits down?

r=me after that

2021-02-21 09:22 UTC, KodrAus commented on library/core/src/iter/traits/iterator.rs
> +    /// Creates an iterator which can use the [`peek`]- and [`peek_mut`]-methods
```suggestion
    /// Creates an iterator which can use the [`peek`] and [`peek_mut`] methods
```

2021-02-21 11:55 UTC, lukaslueg commented
Squashed it all

2021-02-25 22:37 UTC, lukaslueg commented
ping @KodrAus

2021-03-17 04:43 UTC, JohnTitor commented on library/core/src/iter/traits/iterator.rs
> +    /// side effects (i.e.  anything other than fetching the next value) of
nit:
```suggestion
    /// side effects (i.e. anything other than fetching the next value) of
```

2021-03-17 04:43 UTC, JohnTitor commented on library/core/src/iter/traits/iterator.rs
> +    /// // peek_mut() lets us see into the future
nit:

```suggestion
    /// // `peek_mut()` lets us see into the future
```

2021-03-17 17:20 UTC, JohnTitor commented
Thanks!
So, since @KodrAus said r=me before and the next release will happen soon, I'm going to approve not to slip down.
@bors r=KodrAus,JohnTitor

2021-03-17 22:30 UTC, lukaslueg commented
Isn't there usually a vote on stabilizing things, especially since this indirectly affects `Iterator`?

2021-03-17 22:55 UTC, JohnTitor commented
> 
> 
> Isn't there usually a vote on stabilizing things, especially since this indirectly affects `Iterator`?

Hm, I thought they meant we didn't require it, @KodrAus is it wrong?

2021-03-17 22:56 UTC, Mark-Simulacrum commented
@bors r- I'd rather we don't accidentally stabilize, and I think an FCP seems appropriate here.

2021-03-25 05:26 UTC, JohnTitor commented
r? @Amanieu could you check if we need a FCP and kick off it if required?

2021-03-25 05:33 UTC, Amanieu commented
I think this is fairly uncontroversial, but just in case:

@rfcbot fcp merge

2021-03-26 16:44 UTC, lukaslueg commented
Rebased due to #83349

2021-04-01 12:02 UTC, pthariensflame requested changes

2021-04-01 12:02 UTC, pthariensflame commented on library/core/src/iter/adapters/peekable.rs
> +    #[stable(feature = "peekable_peek_mut", since = "1.52.0")]
```suggestion
    #[stable(feature = "peekable_peek_mut", since = "1.53.0")]
```

(To be resolved after FCP.)

2021-04-07 09:34 UTC, Amanieu commented
It seems that the review suggestions by @JohnTitor didn't actually get applied?

2021-04-07 16:03 UTC, lukaslueg commented
> It seems that the review suggestions by @JohnTitor didn't actually get applied?

👀 Thanks for spotting this. I have no idea why these commits slipped through, maybe during rebase.

2021-04-08 16:19 UTC, Amanieu commented
@bors r+ rollup

2021-04-08 22:07 UTC, merged