const_generics: Fix incorrect ty::ParamEnv::empty() usage
rust-lang/rust pull request #82067
Opened 2021-02-13 18:52 UTC by BoxyUwU

Fixes #80561

Not sure if I should keep the `debug!(..)`s or not but its the second time I've needed them so they sure seem useful lol

cc @lcnr 
r? @oli-obk

2021-02-13 19:01 UTC, lcnr commented on compiler/rustc_middle/src/ty/instance.rs
> +        debug!("resolve: param_env = {:?}", param_env);
yeet that one, you print it again right after

2021-02-13 19:01 UTC, lcnr commented on compiler/rustc_middle/src/ty/relate.rs
> +    debug!("super_relate_consts: relation.param_env()={:?}", relation.param_env());
same as `super_combine_consts`

2021-02-14 10:45 UTC, oli-obk requested changes
just lots of tracing changes, the actual changes lgtm

2021-02-14 10:45 UTC, oli-obk commented on compiler/rustc_infer/src/infer/combine.rs
> +        debug!("unify_const_variable: param_env={:?}", param_env);
Please use `#[instrument(level=debug, skip(self))]` on the function instead of a `debug!` invocation

2021-02-14 10:45 UTC, oli-obk commented on compiler/rustc_middle/src/mir/interpret/queries.rs
> +        debug!("const_eval_resolve: param_env={:?}", param_env);
same here

2021-02-14 10:45 UTC, oli-obk commented on compiler/rustc_middle/src/ty/instance.rs
> +        debug!("resolve_opt_const_arg: param_env={:?},substs={:?}", param_env, substs);
and here

2021-02-14 10:45 UTC, oli-obk commented on compiler/rustc_ty_utils/src/instance.rs
> +    debug!("resolve_instance: key = {:?}", key);
aaaand here :laughing:

2021-02-14 10:45 UTC, oli-obk commented on compiler/rustc_ty_utils/src/instance.rs
> +    );
after that change, you can just print the result here (though I think there's also a way to tell `#[instrument]` to do that

2021-02-14 10:45 UTC, oli-obk commented on compiler/rustc_ty_utils/src/instance.rs
> +    debug!("inner_resolve_instance: key={:?}", key);
ok, this one is pre-existing, but please chnage it to `#[instrument]` while you are at it

2021-02-14 11:21 UTC, oli-obk commented
@bors r+

2021-02-16 05:45 UTC, merged