Sidebar trait items order
rust-lang/rust pull request #83051
Opened 2021-03-12 13:27 UTC by GuillaumeGomez

We were actually sorting `Symbol` and not `String`, creating a completely invalid sort result. I added a test to prevent regressions.

r? @jyn514

2021-03-18 09:27 UTC, GuillaumeGomez commented
r? @CraftSpider

2021-03-18 09:47 UTC, GuillaumeGomez commented
Ah right, they're not a reviewer. Well, in any case. :)

2021-03-22 15:08 UTC, CraftSpider commented
Now that I _am_ a reviewer, I'll try to get to this tonight :P

2021-03-22 16:53 UTC, CraftSpider commented
> > We were actually sorting Symbol and not String, creating a completely invalid sort result. I added a test to prevent regressions.
> 
> Why would that make it invalid? Don't Symbols sort the same as strings?

Symbol's derive PartialOrd and Ord, they're sorted and hashed by their `SymbolIndex`

2021-03-22 17:15 UTC, GuillaumeGomez commented
> > We were actually sorting Symbol and not String, creating a completely invalid sort result. I added a test to prevent regressions.
> 
> Why would that make it invalid? Don't Symbols sort the same as strings?

Well, I guess the current situation answers your question. :)

`Symbol`s are IDs, so when comparing two of them, you compare integers, not their content.

2021-03-23 04:47 UTC, CraftSpider approved these changes
Looking good to me
@bors r+

2021-03-23 04:48 UTC, CraftSpider commented
@bors r+

2021-03-23 09:42 UTC, rust-log-analyzer commented
A job failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/runs/2173959335) [(plain)](https://github.com/rust-lang-ci/rust/commit/85326968a127eedd34350a4c6f2995c7e48be390/checks/2173959335/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

```

</details>

2021-03-23 10:27 UTC, GuillaumeGomez commented
@bors retry

2021-03-23 15:17 UTC, jyn514 requested changes

2021-03-23 15:17 UTC, jyn514 commented
I wonder if it makes sense to change Symbols to sort by the string instead of by the index.

2021-03-23 15:28 UTC, GuillaumeGomez commented on src/librustdoc/html/render/mod.rs
> +                Some(ref name) if filter(m) => Some(name.to_string()),
I'm not sure about that... That would perform some "hidden" operations that you might not want.

2021-03-23 15:28 UTC, GuillaumeGomez commented
I'm not sure about that... That would perform some "hidden" operations that you might not want.

2021-03-23 16:14 UTC, pnkfelix commented
@Mark-Simulacrum asked me to retry this PR so that a higher priority stable PR preempts it. Here we go.

2021-03-23 16:14 UTC, pnkfelix commented
@bors retry

2021-03-23 16:15 UTC, pnkfelix commented
(and I guess this also buys @GuillaumeGomez some time to implement the changes suggested above! 😄 )

2021-03-23 16:17 UTC, rust-log-analyzer commented
A job failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/runs/2176997662) [(plain)](https://github.com/rust-lang-ci/rust/commit/b3397622acc8221770400ce3759957120ee67b82/checks/2176997662/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

```

</details>

2021-03-23 16:18 UTC, GuillaumeGomez commented
@pnkfelix Absolutely, removing it from the queue in the meantime. :)

@bors: r-

2021-03-23 19:55 UTC, GuillaumeGomez commented
And updated! Let's go again/

@bors: r=CraftSpider,jyn514

2021-03-24 04:13 UTC, merged