Implement split_array and split_array_mut
rust-lang/rust pull request #83233
Opened 2021-03-17 16:32 UTC by jethrogb

This implements `[T]::split_array::<const N>() -> (&[T; N], &[T])` and `[T; N]::split_array::<const M>() -> (&[T; M], &[T])` and their mutable equivalents. These are another few “missing” array implementations now that const generics are a thing, similar to #74373, #75026, etc. Fixes #74674.

This implements `[T; N]::split_array` returning an array and a slice. Ultimately, this is probably not what we want, we would want the second return value to be an array of length N-M, which will likely be possible with future const generics enhancements. We need to implement the array method now though, to immediately shadow the slice method. This way, when the slice methods get stabilized, calling them on an array will not be automatic through coercion, so we won't have trouble stabilizing the array methods later (cf. into_iter debacle).

An unchecked version of `[T]::split_array` could also be added as in #76014. This would not be needed for `[T; N]::split_array` as that can be compile-time checked.

2021-03-17 16:32 UTC, rust-highfive commented
r? @sfackler

(rust-highfive has picked a reviewer for you, use r? to override)

2021-03-17 16:35 UTC, jethrogb commented on library/core/src/array/mod.rs
> +    #[unstable(feature = "array_split_array", reason = "not intended for stabilization", issue = "74674")]
* [ ] Need to create tracking issue if this is approved

2021-03-17 16:36 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/2132590348) [(plain)](https://github.com/rust-lang/rust/commit/140c62aef6ee851a160a0cb2bb569e70e1f308e2/checks/2132590348/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling libc v0.2.88
   Compiling std v0.0.0 (/checkout/library/std)
   Compiling compiler_builtins v0.1.39
   Compiling unwind v0.0.0 (/checkout/library/unwind)
error[E0425]: cannot find value `M` in this scope
     |
     |
1671 |     pub fn split_array<const N: usize>(&self) -> (&[T; N], &[T]) {
     |                              - similarly named const parameter `N` defined here
1672 |         let (a, b) = self.split_at(M);
     |                                    ^ help: a const parameter with a similar name exists: `N`

error[E0425]: cannot find value `M` in this scope
     |
     |
1699 |     pub fn split_array_mut<const N: usize>(&mut self) -> (&mut [T; N], &mut [T]) {
     |                                  - similarly named const parameter `N` defined here
1700 |         let (a, b) = self.split_at_mut(M);
     |                                        ^ help: a const parameter with a similar name exists: `N`
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
error: could not compile `core`
error: could not compile `core`

To learn more, run the command again with --verbose.
command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "check" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "16" "--release" "--color" "always" "--features" "panic-unwind backtrace compiler-builtins-c" "--manifest-path" "/checkout/library/test/Cargo.toml" "--message-format" "json-render-diagnostics"
failed to run: /checkout/obj/build/bootstrap/debug/bootstrap check
Build completed unsuccessfully in 0:01:41
```

</details>

2021-03-17 16:41 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-9`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/2132631206) [(plain)](https://github.com/rust-lang/rust/commit/5fedd60ece3ad12559a88da4d31074219fc7b47d/checks/2132631206/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling unwind v0.0.0 (/checkout/library/unwind)
error[E0282]: type annotations needed
    --> library/core/src/slice/mod.rs:1673:11
     |
1673 |         (&*(a.as_ptr() as _), b)
     |
     |
     = note: type must be known at this point
error[E0282]: type annotations needed
    --> library/core/src/slice/mod.rs:1701:14
     |
     |
1701 |         (&mut*(a.as_mut_ptr() as _), b)
     |
     |
     = note: type must be known at this point
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0282`.
error: could not compile `core`
```

</details>

2021-03-17 16:58 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/2132700509) [(plain)](https://github.com/rust-lang/rust/commit/3be8f63be056b6aab06e9494f13721ba0302fc2b/checks/2132700509/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.channel         := nightly
configure: rust.debug-assertions := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
skip untracked path src/doc/rust-by-example/ during rustfmt invocations
skip untracked path src/llvm-project/ during rustfmt invocations
Diff in /checkout/library/core/src/array/mod.rs at line 566:
     /// ```
     // Note: this is not intended to be stabilized in its current form. The
     // second element of the return value should instead be `&[T; {N - M}]`.
-    #[unstable(feature = "array_split_array", reason = "not intended for stabilization", issue = "74674")]
+    #[unstable(
+        feature = "array_split_array",
+        reason = "not intended for stabilization",
+        issue = "74674"
+    )]
     #[inline]
     pub fn split_array<const M: usize>(&self) -> (&[T; M], &[T]) {
         self[..].split_array::<M>()
Diff in /checkout/library/core/src/array/mod.rs at line 595:
     /// ```
     // Note: this is not intended to be stabilized in its current form. The
     // second element of the return value should instead be `&mut [T; {N - M}]`.
-    #[unstable(feature = "array_split_array", reason = "not intended for stabilization", issue = "74674")]
+    #[unstable(
+        feature = "array_split_array",
+        reason = "not intended for stabilization",
+        issue = "74674"
+    )]
     #[inline]
     pub fn split_array_mut<const M: usize>(&mut self) -> (&mut [T; M], &mut [T]) {
         self[..].split_array_mut::<M>()
Diff in /checkout/library/core/src/slice/mod.rs at line 1700:
     pub fn split_array_mut<const N: usize>(&mut self) -> (&mut [T; N], &mut [T]) {
         let (a, b) = self.split_at_mut(N);
         // SAFETY: a points to [T; N]? Yes it's [T] of length N (checked by split_at_mut)
-        unsafe { (&mut*(a.as_mut_ptr() as *mut [T; N]), b) }
+        unsafe { (&mut *(a.as_mut_ptr() as *mut [T; N]), b) }
 
 
     /// Returns an iterator over subslices separated by elements that match
Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt" "--config-path" "/checkout" "--edition" "2018" "--unstable-features" "--skip-children" "--check" "/checkout/library/core/src/ptr/metadata.rs" "/checkout/library/core/src/char/convert.rs" "/checkout/library/core/src/ptr/mut_ptr.rs" "/checkout/library/core/src/char/decode.rs" "/checkout/library/core/src/char/mod.rs" "/checkout/library/core/src/array/mod.rs" "/checkout/library/core/src/borrow.rs" "/checkout/library/core/src/char/methods.rs"` failed.
failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test --stage 2 src/tools/tidy
If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
```

</details>

2021-03-17 17:24 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-9`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/2132826695) [(plain)](https://github.com/rust-lang/rust/commit/4bcd4cd802c1bb946cbc9ff2d102e9f4c80f06f5/checks/2132826695/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
.................................................................................................... 9300/11690
.................................................................................................... 9400/11690
.................................................................................................... 9500/11690
.................................i......i........................................................... 9600/11690
...............................................................................iiiiiii..iiiiii.i.... 9700/11690
.................................................................................................... 9900/11690
.................................................................................................... 10000/11690
.................................................................................................... 10100/11690
.................................................................................................... 10200/11690
---
Suite("src/test/assembly") not skipped for "bootstrap::test::Assembly" -- not in ["src/tools/tidy"]
Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 31 tests
iiiiiiiiiiiiiiiiiiiiiiiiiiiii..

 finished in 0.090 seconds
Suite("src/test/incremental") not skipped for "bootstrap::test::Incremental" -- not in ["src/tools/tidy"]
Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
---
Suite("src/test/debuginfo") not skipped for "bootstrap::test::Debuginfo" -- not in ["src/tools/tidy"]
Check compiletest suite=debuginfo mode=debuginfo (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 116 tests
iiiiiiiiii.i.i..i..i..ii....i.i....ii..........iiii.........i.....i...i.......ii.i.ii.....iiii.....i 100/116
test result: ok. 78 passed; 0 failed; 38 ignored; 0 measured; 0 filtered out; finished in 2.34s

 finished in 2.393 seconds
Suite("src/test/ui-fulldeps") not skipped for "bootstrap::test::UiFullDeps" -- not in ["src/tools/tidy"]
---

   Doc-tests core

running 2847 tests
iiiiii..................F....F...................................................................... 100/2847
....ii.............................................................................................. 300/2847
.....................................................i.............................................. 400/2847
.................................................................................................... 500/2847
..........................i..i...................iiii............................................... 600/2847
---
.................................................................................................... 2000/2847
.................................................................................................... 2100/2847
.................................................................................................... 2200/2847
.................................................................................................... 2300/2847
.....................................................................................F...F.......... 2400/2847
.......................................i................i.....................i..................... 2600/2847
i.....................i.....................i................................i.....................i 2700/2847
.....................i.....................i.....................i.................................. 2800/2847
...............................................
...............................................
failures:

---- src/array/mod.rs - array::[T; N]::split_array (line 546) stdout ----
error[E0658]: use of unstable library feature 'array_split_array': not intended for stabilization
  |
  |
7 |    let (left, right) = v.split_array::<0>();
  |
  = note: see issue #74674 <https://github.com/rust-lang/rust/issues/74674> for more information
  = help: add `#![feature(array_split_array)]` to the crate attributes to enable


error[E0277]: can't compare `&[{integer}; 0]` with `[_; 0]`
  |
  |
8 |    assert_eq!(left, []);
  |    ^^^^^^^^^^^^^^^^^^^^^ no implementation for `&[{integer}; 0] == [_; 0]`
  |
  = help: the trait `PartialEq<[_; 0]>` is not implemented for `&[{integer}; 0]`


error[E0107]: this associated function takes 0 const arguments but 1 const argument was supplied
     |
     |
13   |     let (left, right) = v.split_at::<2>();
     |                           ^^^^^^^^----- help: remove these generics
     |                           expected 0 const arguments
     |
     |
note: associated function defined here, with 0 const parameters
     |
     |
1504 |     pub fn split_at(&self, mid: usize) -> (&[T], &[T]) {

error[E0061]: this function takes 1 argument but 0 arguments were supplied
    --> src/array/mod.rs:556:27
     |
     |
13   |     let (left, right) = v.split_at::<2>();
     |                           |
     |                           expected 1 argument
     |
note: associated function defined here
note: associated function defined here
    --> /checkout/library/core/src/slice/mod.rs:1504:12
     |
1504 |     pub fn split_at(&self, mid: usize) -> (&[T], &[T]) {


error[E0107]: this associated function takes 0 const arguments but 1 const argument was supplied
     |
     |
19   |     let (left, right) = v.split_at::<6>();
     |                           ^^^^^^^^----- help: remove these generics
     |                           expected 0 const arguments
     |
     |
note: associated function defined here, with 0 const parameters
     |
     |
1504 |     pub fn split_at(&self, mid: usize) -> (&[T], &[T]) {

error[E0061]: this function takes 1 argument but 0 arguments were supplied
    --> src/array/mod.rs:562:27
     |
     |
19   |     let (left, right) = v.split_at::<6>();
     |                           |
     |                           expected 1 argument
     |
note: associated function defined here
note: associated function defined here
    --> /checkout/library/core/src/slice/mod.rs:1504:12
     |
1504 |     pub fn split_at(&self, mid: usize) -> (&[T], &[T]) {

error: aborting due to 6 previous errors

Some errors have detailed explanations: E0061, E0107, E0277, E0658.
Some errors have detailed explanations: E0061, E0107, E0277, E0658.
For more information about an error, try `rustc --explain E0061`.
Couldn't compile the test.
---- src/array/mod.rs - array::[T; N]::split_array_mut (line 591) stdout ----
error[E0658]: use of unstable library feature 'slice_split_array': new API
  |
  |
5 | let (left, right) = v.split_array_mut::<2>();
  |
  = note: see issue #74674 <https://github.com/rust-lang/rust/issues/74674> for more information
  = note: see issue #74674 <https://github.com/rust-lang/rust/issues/74674> for more information
  = help: add `#![feature(slice_split_array)]` to the crate attributes to enable

error[E0277]: can't compare `&mut [{integer}; 2]` with `[{integer}; 2]`
  |
  |
6 | assert_eq!(left, [1, 0]);
  | ^^^^^^^^^^^^^^^^^^^^^^^^^ no implementation for `&mut [{integer}; 2] == [{integer}; 2]`
  |
  = help: the trait `PartialEq<[{integer}; 2]>` is not implemented for `&mut [{integer}; 2]`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0277, E0658.
Some errors have detailed explanations: E0277, E0658.
For more information about an error, try `rustc --explain E0277`.
Couldn't compile the test.
---- src/slice/mod.rs - slice::[T]::split_array (line 1648) stdout ----
error[E0658]: use of unstable library feature 'slice_split_array': new AP [...]

2021-03-18 16:02 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-9`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/2141129569) [(plain)](https://github.com/rust-lang/rust/commit/f42db119fc68bfb2907c9e6dddbd6b737320d0b6/checks/2141129569/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
.................................................................................................... 9300/11700
.................................................................................................... 9400/11700
.................................................................................................... 9500/11700
...........................................i......i................................................. 9600/11700
.........................................................................................iiiiiii..ii 9700/11700
.................................................................................................... 9900/11700
.................................................................................................... 10000/11700
.................................................................................................... 10100/11700
.................................................................................................... 10200/11700
---
Suite("src/test/assembly") not skipped for "bootstrap::test::Assembly" -- not in ["src/tools/tidy"]
Check compiletest suite=assembly mode=assembly (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 31 tests
iiiiiiiiiiiiiiiiiiiiiiiiiiiii..
test result: ok. 2 passed; 0 failed; 29 ignored; 0 measured; 0 filtered out; finished in 0.03s

 finished in 0.088 seconds
Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
---
Suite("src/test/debuginfo") not skipped for "bootstrap::test::Debuginfo" -- not in ["src/tools/tidy"]
Check compiletest suite=debuginfo mode=debuginfo (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 116 tests
iiiiiiiiii.i.i..i..i..ii....i.i....ii..........iiii.........i.....i...i.......ii.i.ii.....iiii.....i 100/116
test result: ok. 78 passed; 0 failed; 38 ignored; 0 measured; 0 filtered out; finished in 2.32s

 finished in 2.376 seconds
Suite("src/test/ui-fulldeps") not skipped for "bootstrap::test::UiFullDeps" -- not in ["src/tools/tidy"]
---

   Doc-tests core

running 2847 tests
iiiiii.................F............................................................................ 100/2847
....ii.............................................................................................. 300/2847
.....................................................i.............................................. 400/2847
.................................................................................................... 500/2847
..........................i..i...................iiii............................................... 600/2847
---
.....................i.....................i.....................i.................................. 2800/2847
...............................................
failures:

---- src/array/mod.rs - array::[T; N]::split_array_mut (line 593) stdout ----
error[E0658]: use of unstable library feature 'slice_split_array': new API
  |
  |
7 | let (left, right) = v.split_array_mut::<2>();
  |
  = note: see issue #74674 <https://github.com/rust-lang/rust/issues/74674> for more information
  = note: see issue #74674 <https://github.com/rust-lang/rust/issues/74674> for more information
  = help: add `#![feature(slice_split_array)]` to the crate attributes to enable
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
Couldn't compile the test.
---

error: test failed, to rerun pass '--doc'


command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "test" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "16" "--release" "--locked" "--color" "always" "--features" "panic-unwind backtrace compiler-builtins-c" "--manifest-path" "/checkout/library/test/Cargo.toml" "-p" "core" "--" "--quiet"


failed to run: /checkout/obj/build/bootstrap/debug/bootstrap --stage 2 test --exclude src/tools/tidy
Build completed unsuccessfully in 0:18:12
```

</details>

2021-03-22 21:23 UTC, slightlyoutofphase commented
For the array-based version of this, wouldn't it possibly make more sense to have it be entirely value-based so as to make it useful in a different way than the slice version? [Something like this for example.](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=cb5b707b08b993d9c8f6d1871dc3524b)

2021-03-23 08:03 UTC, jethrogb commented
That's pretty neat. That brings up a question about naming. For arrays you could have

* split_array
* split_array_ref
* split_array_mut

But now array::split_array and slice::split_array are even more different.

2021-03-23 15:08 UTC, slightlyoutofphase commented
> That's pretty neat. That brings up a question about naming. For arrays you could have
> 
> * split_array
> * split_array_ref
> * split_array_mut
> 
> But now array::split_array and slice::split_array are even more different.

Well, like, arrays already have easy direct access to all the slice methods anyways via `as_slice()` and `as_mut_slice()` (and via the classic direct `&arr[..]` and `&mut arr[..]` syntax of course). I'd say overall the best API might ultimately actually be something like just having:

`[T; N]::split_array<const M: usize>(self) -> ([T; M], [T; N - M])`
and
`[T]::split_array_ref<const M: usize>(&self) -> (&[T; M], &[T; N - M])`
and
`[T]::split_array_mut<const M: usize>(&mut self) -> (&mut [T; M], &mut [T; N - M])`

That way all three types of functionality are available where it's appropriate for them to be, and there's also no name confusion.

2021-03-23 15:14 UTC, jethrogb commented
You can't have `[T]::split_array_ref<const M: usize>(&self) -> (&[T; M], &[T; N - M])`

2021-03-23 16:22 UTC, slightlyoutofphase commented
> You can't have `[T]::split_array_ref<const M: usize>(&self) -> (&[T; M], &[T; N - M])`

Sorry, I got mixed up with my copy-pasting. It should have been:

`[T; N]::split_array<const M: usize>(self) -> ([T; M], [T; N - M])`
and
`[T]::split_array_ref<const M: usize>(&self) -> (&[T; M], &[T])`
and
`[T]::split_array_mut<const M: usize>(&mut self) -> (&mut [T; M], &mut [T])`

So the second two are your existing slice ones, but with the immutable version called `split_array_ref` instead.

2021-03-23 16:29 UTC, jethrogb commented
I think we'd still want the exact-remainder versions on array references. That's still possible with the names you suggest, but for slices now there's a weird naming difference between split_at and split_array_ref.

2021-03-23 16:32 UTC, slightlyoutofphase commented
> I think we'd still want the exact-remainder versions on array references. That's still possible with the names you suggest, but for slices now there's a weird naming difference between split_at and split_array_ref.

That's fair enough. I personally don't actually care too much what the names end up being TBH. Primarily my point was just that I think the value based version would be useful to also have for arrays (regardless of what it's called).

2021-03-23 23:25 UTC, slightlyoutofphase commented
Ok, here's a complete, perfectly working, Miri-passing `const_trait_impl` implementation of all three of the "exact remainder" array methods. There's definitely no technical barrier preventing any of them from being written with the desired signatures right now.

```rust
#![allow(incomplete_features)]
#![feature(
    box_syntax,
    const_evaluatable_checked,
    const_generics,
    const_intrinsic_copy,
    const_maybe_uninit_as_ptr,
    const_maybe_uninit_assume_init,
    const_mut_refs,
    const_panic,
    const_precise_live_drops,
    const_ptr_offset,
    const_raw_ptr_deref,
    // This feature should have a more general name considering what it actually does IMO.
    const_refs_to_cell,
    const_slice_from_raw_parts,
    const_trait_impl,
    slice_ptr_get,
)]

use core::mem::{self, MaybeUninit};
use core::ptr;

#[inline(always)]
const unsafe fn ptr_slice_to_array_mut<'a, T, const N: usize>(slice: *mut [T]) -> &'a mut [T; N] {
    &mut *(slice.as_mut_ptr() as *mut [T; N])
}

#[inline(always)]
const unsafe fn ptr_slice_to_array_ref<'a, T, const N: usize>(slice: *const [T]) -> &'a [T; N] {
    &*(slice.as_ptr() as *const [T; N])
}

// This is just a stand-in for `[T; N]`, to simulate how `N` *must* be initially declared somewhere
// entirely outside of `split_array` for it to work as it does below.
pub trait ArrayHelper<T, const N: usize> {
    fn split_array<const M: usize>(self) -> ([T; M], [T; N - M]);
    fn split_array_ref<const M: usize>(&self) -> (&[T; M], &[T; N - M]);
    fn split_array_mut<const M: usize>(&mut self) -> (&mut [T; M], &mut [T; N - M]);
}

impl<T, const N: usize> const ArrayHelper<T, N> for [T; N] {
    // It seems that `const_evaluatable_checked` itself makes these "just work" without even needing
    // a `where` clause.
    #[inline]
    fn split_array<const M: usize>(self) -> ([T; M], [T; N - M]) {
        assert!(M <= N, "Bounds check failure in `[T; N]::split_array'!");
        let mut left = MaybeUninit::<[T; M]>::uninit();
        let mut right = MaybeUninit::<[T; N - M]>::uninit();
        let self_ptr = self.as_ptr();
        let left_ptr = left.as_mut_ptr() as *mut T;
        let right_ptr = right.as_mut_ptr() as *mut T;
        unsafe {
            self_ptr.copy_to_nonoverlapping(left_ptr, M);
            self_ptr.add(M).copy_to_nonoverlapping(right_ptr, N - M);
            mem::forget(self);
            (left.assume_init(), right.assume_init())
        }
    }

    #[inline]
    fn split_array_ref<const M: usize>(&self) -> (&[T; M], &[T; N - M]) {
        assert!(M <= N, "Bounds check failure in `[T; N]::split_array_ref'!");
        let self_ptr = self.as_ptr();
        unsafe {
            // `ptr::slice_from_raw_parts` is a `const fn`. `slice::from_raw_parts` is not.
            let left = ptr::slice_from_raw_parts(self_ptr, M);
            let right = ptr::slice_from_raw_parts(self_ptr.add(M), N - M);
            (ptr_slice_to_array_ref(left), ptr_slice_to_array_ref(right))
        }
    }

    #[inline]
    fn split_array_mut<const M: usize>(&mut self) -> (&mut [T; M], &mut [T; N - M]) {
        assert!(M <= N, "Bounds check failure in `[T; N]::split_array_mut'!");
        let self_ptr = self.as_mut_ptr();
        unsafe {
            // `ptr::slice_from_raw_parts_mut` is a `const fn`. `slice::from_raw_parts_mut` is not.
            let left = ptr::slice_from_raw_parts_mut(self_ptr, M);
            let right = ptr::slice_from_raw_parts_mut(self_ptr.add(M), N - M);
            (ptr_slice_to_array_mut(left), ptr_slice_to_array_mut(right))
        }
    }
}

const X1: ([usize; 2], [usize; 4]) = [1, 2, 3, 4, 5, 6].split_array::<2>();
const Y1: ([usize; 0], [usize; 6]) = [1, 2, 3, 4, 5, 6].split_array::<0>();
const Z1: ([usize; 6], [usize; 0]) = [1, 2, 3, 4, 5, 6].split_array::<6>();
const X2: (&[usize; 2], &[usize; 4]) = [1, 2, 3, 4, 5, 6].split_array_ref::<2>();
const Y2: (&[usize; 0], &[usize; 6]) = [1, 2, 3, 4, 5, 6].split_array_ref::<0>();
const Z2: (&[usize; 6], &[usize; 0]) = [1, 2, 3, 4, 5, 6].split_array_ref::<6>();

fn main() {
    // Everything is boxed for the sake of making sure it passes Miri, FYI.
    let a = [box 1, box 2, box 3, box 4, box 5, box 6].split_array::<2>();
    println!("{:?}", a.0);
    println!("{:?}\n", a.1);
    let b = [box 1, box 2, box 3, box 4, box 5, box 6].split_array::<0>();
    println!("{:?}", b.0);
    println!("{:?}\n", b.1);
    let c = [box 1, box 2, box 3, box 4, box 5, box 6].split_array::<6>();
    println!("{:?}", c.0);
    println!("{:?}\n", c.1);
    let d = [box 1, box 2, box 3, box 4, box 5, box 6];
    let e = d.split_array_ref::<2>();
    println!("{:?}", e.0);
    println!("{:?}\n", e.1);
    let f = d.split_array_ref::<0>();
    println!("{:?}", f.0);
    println!("{:?}\n", f.1);
    let g = d.split_array_ref::<6>();
    println!("{:?}", g.0);
    println!("{:?}\n", g.1);
    let mut h = [box 1, box 2, box 3, box 4, box 5, box 6];
    let i = h.split_array_mut::<2>();
    for (l, r) in i.0.iter_mut().zip(i.1.iter_mut()) {
        *l.as_mut() += *r.as_ref();
        *r.as_mut() += *l.as_ref();
    }
    println!("{:?}", i.0);
    println!("{:?}\n", i.1);
    let j = h.split_array_mut::<0>();
    for (l, r) in j.0.iter_mut().zip(j.1.iter_mut()) {
        *l.as_mut() += *r.as_ref();
        *r.as_mut() += *l.as_ref();
    }
    println!("{:?}", j.0);
    println!("{:?}\n", j.1);
    let k = h.split_array_mut::<6>();
    for (l, r) in k.0.iter_mut().zip(k.1.iter_mut()) {
        *l.as_mut() += *r.as_ref();
        *r.as_mut() += *l.as_ref();
    }
    println!("{:?}", k.0);
    println!("{:?}\n", k.1);
    // Make sure constant usage works properly also
    println!("{:?}", X1.0);
    println!("{:?}\n", X1.1);
    println!("{:?}", Y1.0);
    println!("{:?}\n", Y1.1);
    println!("{:?}", Z1.0);
    println!("{:?}\n", Z1.1);
    println!("{:?}", X2.0);
    println!("{:?}\n", X2.1);
    println!("{:?}", Y2.0);
    println!("{:?}\n", Y2.1);
    println!("{:?}", Z2.0);
    println!("{:?}\n", Z2.1);
}
```
[Playground link.](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a317e6e3e13968e2a6103a75055a406d)

2021-07-25 15:14 UTC, Dylan-DPC commented
@sfackler any updates?

2021-07-27 19:14 UTC, JohnTitor commented
Triage: Re-assigning randomly, r? @yaahc

2021-09-06 08:29 UTC, JohnCSimon commented
@yaahc  any updates?

2021-09-26 23:43 UTC, jhpratt commented on library/core/src/array/mod.rs
> +        reason = "not intended for stabilization",
This should be the actual reason. The method is intended to be stabilized, just with a different return type.

2021-09-26 23:43 UTC, jhpratt commented on library/core/src/array/mod.rs
> +    /// Panics if `M > N`.
It should be possible to add a static assertion until `[T; { N - M }]` is allowed in return types, no?

2021-09-26 23:43 UTC, jhpratt commented on library/core/src/array/mod.rs
> +        feature = "array_split_array",
Any particular reason to not use a single feature?

2021-10-14 22:47 UTC, yaahc requested changes
In addition to agreeing with the comments made so far by @jhpratt I think agree with @slightlyoutofphase that a by value impl for splitting an array in two would almost certainly be useful. We should plan for it now since if we don't add it someone else probably will soon after these methods are made available on nightly, and there seem to be some non-insignificant forward compatibility hazards here to manage.

After digging into the slice split method naming consistency issue you mentioned my first instinct was to call the by value version of the method simply `split`, but that runs into the same coercion issue that you mentioned in the top level comment, since slice already has a split method.

I'm having trouble coming up with any alternatives other than the `_ref` version suggested by @slightlyoutofphase. My current lean is that it's probably fine to have one of the split methods on `slice` include a `_ref` even though similar by reference methods on slice do not. [We have a history of prioritizing forwards compatibility over internal method naming consistency on a given type](https://github.com/rust-lang/rust/pull/82703#issuecomment-827776826).

For now I'm going to suggest updating the PR to add the by value version for array and rename the by reference versions on array and slice to end in `_ref`, since I currently expect that to be the most likely resolution. I'll also cc @rust-lang/libs-api in case anyone can think of any better naming scheme here, but if nobody replies before we've updated it and resolved all the comments I'll happily r+ the `array_split`/`array_split_ref`/`array_split_mut` version.

Edit: I just realized that we probably still cant add `array_split` because of the `[T: {N - M}]` issue so feel free to ignore that part of the above advice if it's impossible and just do the `_ref` rename.

2021-10-20 10:38 UTC, jethrogb commented
Updated:

* Created a tracking issue #90091
* Used consistent naming of split_array, split_array_ref, split_array_mut (even for slices)
* Used `N - M` return types for arrays.

It's not clear to me that the `N - M` return types are useful, at least not in the current form of const generics. The compiler doesn't know that `O = N - M`, and as such you can't use the return type in a place where you expect to be able to use `[T; O]`. You can see this in the doc test where I wasn't able to use `[T; O] as PartialEq<[T; N - M]>`.

2021-10-20 11:18 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-10`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3950618558) [(plain)](https://github.com/rust-lang/rust/commit/928d4858a8794b2d83777fa020a7a335c8ad2dc7/checks/3950618558/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Some tests failed in compiletest suite=incremental mode=incremental host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu

---- [incremental] incremental/const-generics/try_unify_abstract_const_regression_tests/issue-88022.rs stdout ----

error in revision `cfail`: /checkout/src/test/incremental/const-generics/try_unify_abstract_const_regression_tests/issue-88022.rs:16: expected error not found: the trait bound

error in revision `cfail`: /checkout/src/test/incremental/const-generics/try_unify_abstract_const_regression_tests/issue-88022.rs:21: expected error not found: the trait bound

error in revision `cfail`: 0 unexpected errors found, 2 expected errors not found
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/incremental/const-generics/try_unify_abstract_const_regression_tests/issue-88022.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--cfg" "cfail" "-C" "incremental=/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental/const-generics/try_unify_abstract_const_regression_tests/issue-88022/issue-88022.inc" "-Z" "incremental-verify-ich" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental/const-generics/try_unify_abstract_const_regression_tests/issue-88022" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental/const-generics/try_unify_abstract_const_regression_tests/issue-88022/auxiliary"
    Error {
        line_num: 16,
        kind: Some(
            Error,
---
test result: FAILED. 147 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 12.34s



command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/incremental" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--suite" "incremental" "--mode" "incremental" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-10/bin/FileCheck" "--nodejs" "/usr/bin/node" "--host-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python3" "--lldb-python" "/usr/bin/python3" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "10.0.0" "--llvm-components" "aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets amdgpu amdgpuasmparser amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgpuutils analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter bpf bpfasmparser bpfcodegen bpfdesc bpfdisassembler bpfinfo cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker engine executionengine frontendopenmp fuzzmutate globalisel hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interpreter ipo irreader jitlink lanai lanaiasmparser lanaicodegen lanaidesc lanaidisassembler lanaiinfo libdriver lineeditor linker lto mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcerror orcjit passes perfjitevents powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo riscvutils runtimedyld scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target textapi transformutils vectorize webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info x86utils xcore xcorecodegen xcoredesc xcoredisassembler xcoreinfo xray" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--channel" "nightly" "--color" "always"


Build completed unsuccessfully in 0:12:54
```

</details>

2021-10-20 12:27 UTC, BoxyUwU requested changes

2021-10-20 12:29 UTC, BoxyUwU commented
I don't know why the test started failing that's pretty weird, maybe the error is just happening later on now that `core` has the feature enabled...

2021-10-21 23:14 UTC, yaahc commented
I think this is looking good, though I would like to add tests before merging. Here are the relevant tests that I can think of:

- #[should_panic] test for when M > N
- M = 0
- N - M = 0
- 0 < M < N

And of course feel free to add any other tests you can think of. I'll r+ after the tests are added. Thanks again for working on this!

2021-10-23 09:21 UTC, merged