Update closure capture error logging for disjoint captures for disjoint captures
rust-lang/rust pull request #84358
Opened 2021-04-20 05:57 UTC by ChrisPardy

Improved error logging when `#![feature(capture_disjoint_fields)]` is used.

Closes https://github.com/rust-lang/project-rfc-2229/issues/8
Closes https://github.com/rust-lang/project-rfc-2229/issues/36

2021-04-20 05:57 UTC, rust-highfive commented
r? @davidtwco

(rust-highfive has picked a reviewer for you, use r? to override)

2021-04-20 05:57 UTC, ChrisPardy commented
r? @nikomatsakis

2021-04-20 19:48 UTC, nikomatsakis requested changes
This looks pretty good! Let a few nits, but r=me once fixed.

2021-04-20 19:48 UTC, nikomatsakis commented on compiler/rustc_middle/src/mir/mod.rs
> +                            // FIXME: This should be a list of capture names/places
Is there an issue number for this FIXME?

2021-04-20 19:48 UTC, nikomatsakis commented on compiler/rustc_mir/src/borrow_check/diagnostics/explain_borrow.rs
> +                    if !borrow_span.map_or(false, |sp| sp.overlaps(var_or_use_span)) {
```suggestion
                if path_span.map(|path_span| path_span == var_or_use_span).unwrap_or(true) {
                    if borrow_span.map(|sp| !sp.overlaps(var_or_use_span)).unwrap_or(true) {
```

I have a deep, abiding, and personal hatred for `map_or` and I am going to impose it on you.

2021-04-20 19:48 UTC, nikomatsakis commented on compiler/rustc_mir/src/borrow_check/diagnostics/explain_borrow.rs
> +                if path_span.map_or(true, |path_span| path_span == var_or_use_span) {
```suggestion
                if path_span.map(|path_span| path_span == var_or_use_span).unwrap_or(true) {
```
As above =)

2021-04-20 19:48 UTC, nikomatsakis commented on compiler/rustc_mir/src/borrow_check/diagnostics/explain_borrow.rs
> +                    if !borrow_span.map_or(false, |sp| sp.overlaps(var_or_use_span)) {
```suggestion
                    if borrow_span.map(|sp| !sp.overlaps(var_or_use_span)).unwrap_or(true) {
```

2021-04-20 19:48 UTC, nikomatsakis commented on compiler/rustc_mir/src/borrow_check/diagnostics/mod.rs
> +    pub(super) fn var_or_use_path_span(self) -> Span {
A doc-comment would I think be nice here

2021-04-20 19:49 UTC, nikomatsakis commented
@bors delegate+

2021-04-30 00:28 UTC, arora-aman commented
Closes #76005 aswell

2021-04-30 00:44 UTC, ChrisPardy commented on compiler/rustc_mir/src/borrow_check/diagnostics/region_errors.rs
> +        // FIXME: This should store a captured_place not a hir id
I've created https://github.com/rust-lang/project-rfc-2229/issues/48 for the FIXMEs created in this PR

2021-04-30 00:44 UTC, ChrisPardy commented
@bors r=nikomatsakis

2021-04-30 06:57 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-nopt`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/runs/2473383131) [(plain)](https://github.com/rust-lang-ci/rust/commit/2c5be70da85cb08c621b6cd48f9b23e508020f97/checks/2473383131/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

---- [ui (nll)] ui/regions/regions-addr-of-upvar-self.rs stdout ----
diff of stderr:

23 LL |         let _f = || {
24    |                  -- value captured here
25 LL |             let p: &'static mut usize = &mut self.food;
-    |                    ------------------        ^^^^ borrowed value does not live long enough
+    |                    ------------------        ^^^^^^^^^ borrowed value does not live long enough
27    |                    |
28    |                    type annotation requires that `self` is borrowed for `'static`


The actual stderr differed from the expected stderr.
The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/regions/regions-addr-of-upvar-self.nll/regions-addr-of-upvar-self.nll.stderr
To only update this specific test, also pass `--test-args regions/regions-addr-of-upvar-self.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/regions/regions-addr-of-upvar-self.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/regions/regions-addr-of-upvar-self.nll" "-Zborrowck=mir" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/regions/regions-addr-of-upvar-self.nll/auxiliary"
------------------------------------------

------------------------------------------
stderr:
stderr:
------------------------------------------
error: lifetime may not live long enough
  --> /checkout/src/test/ui/regions/regions-addr-of-upvar-self.rs:8:20
   |
LL |         let _f = || {
   |                  -- lifetime `'1` represents this closure's body
LL |             let p: &'static mut usize = &mut self.food; //~ ERROR cannot infer
   |                    ^^^^^^^^^^^^^^^^^^ type annotation requires that `'1` must outlive `'static`
   |
   = note: closure implements `FnMut`, so references to captured variables can't escape the closure
error: lifetime may not live long enough
  --> /checkout/src/test/ui/regions/regions-addr-of-upvar-self.rs:8:20
   |
   |
LL |     pub fn chase_cat(&mut self) {
   |                      - let's call the lifetime of this reference `'1`
LL |         let _f = || {
LL |             let p: &'static mut usize = &mut self.food; //~ ERROR cannot infer
   |                    ^^^^^^^^^^^^^^^^^^ type annotation requires that `'1` must outlive `'static`

error[E0597]: `self` does not live long enough
   |
   |
LL |         let _f = || {
   |                  -- value captured here
LL |             let p: &'static mut usize = &mut self.food; //~ ERROR cannot infer
   |                    ------------------        ^^^^^^^^^ borrowed value does not live long enough
   |                    |
   |                    type annotation requires that `self` is borrowed for `'static`
LL |     }
LL |     }
   |      - `self` dropped here while still borrowed
error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0597`.

---
    [ui (nll)] ui/regions/regions-addr-of-upvar-self.rs

test result: FAILED. 11685 passed; 1 failed; 124 ignored; 0 measured; 0 filtered out; finished in 102.68s

Some tests failed in compiletest suite=ui compare_mode=Nll mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu


command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--suite" "ui" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/checkout/obj/build/x86_64-unknown-linux-gnu/llvm/build/bin/FileCheck" "--host-rustcflags" "-Crpath -Cdebuginfo=0 -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -Cdebuginfo=0 -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python3" "--lldb-python" "/usr/bin/python3" "--gdb" "/usr/bin/gdb" "--llvm-version" "12.0.0-rust-1.53.0-nightly" "--llvm-components" "aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker engine executionengine extensions filecheck frontendopenacc frontendopenmp fuzzmutate globalisel hellonew hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interfacestub interpreter ipo irreader jitlink libdriver lineeditor linker lto mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcjit orcshared orctargetprocess passes powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo runtimedyld scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target textapi transformutils vectorize webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info xray" "--cc" "" "--cxx" "" "--cflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always" "--compare-mode" "nll"


failed to run: /checkout/obj/build/bootstrap/debug/bootstrap --stage 2 test
Build completed unsuccessfully in 0:19:42
```

</details>

2021-05-02 02:27 UTC, ChrisPardy commented
@bors r=nikomatsakis

2021-05-02 04:52 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-nopt`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/runs/2485081838) [(plain)](https://github.com/rust-lang-ci/rust/commit/a134ad75469a2d429c6383baabcada8f44913c69/checks/2485081838/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

---- [ui (nll)] ui/regions/regions-addr-of-upvar-self.rs stdout ----
diff of stderr:

23 LL |         let _f = || {
24    |                  -- value captured here
25 LL |             let p: &'static mut usize = &mut self.food;
-    |                    ------------------        ^^^^ borrowed value does not live long enough
+    |                    ------------------        ^^^^^^^^^ borrowed value does not live long enough
27    |                    |
28    |                    type annotation requires that `self` is borrowed for `'static`


The actual stderr differed from the expected stderr.
The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/regions/regions-addr-of-upvar-self.nll/regions-addr-of-upvar-self.nll.stderr
To only update this specific test, also pass `--test-args regions/regions-addr-of-upvar-self.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/regions/regions-addr-of-upvar-self.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/regions/regions-addr-of-upvar-self.nll" "-Zborrowck=mir" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/regions/regions-addr-of-upvar-self.nll/auxiliary"
Some tests failed in compiletest suite=ui compare_mode=Nll mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
------------------------------------------

------------------------------------------
stderr:
stderr:
------------------------------------------
error: lifetime may not live long enough
  --> /checkout/src/test/ui/regions/regions-addr-of-upvar-self.rs:8:20
   |
LL |         let _f = || {
   |                  -- lifetime `'1` represents this closure's body
LL |             let p: &'static mut usize = &mut self.food; //~ ERROR cannot infer
   |                    ^^^^^^^^^^^^^^^^^^ type annotation requires that `'1` must outlive `'static`
   |
   = note: closure implements `FnMut`, so references to captured variables can't escape the closure
error: lifetime may not live long enough
  --> /checkout/src/test/ui/regions/regions-addr-of-upvar-self.rs:8:20
   |
   |
LL |     pub fn chase_cat(&mut self) {
   |                      - let's call the lifetime of this reference `'1`
LL |         let _f = || {
LL |             let p: &'static mut usize = &mut self.food; //~ ERROR cannot infer
   |                    ^^^^^^^^^^^^^^^^^^ type annotation requires that `'1` must outlive `'static`

error[E0597]: `self` does not live long enough
   |
   |
LL |         let _f = || {
   |                  -- value captured here
LL |             let p: &'static mut usize = &mut self.food; //~ ERROR cannot infer
   |                    ------------------        ^^^^^^^^^ borrowed value does not live long enough
   |                    |
   |                    type annotation requires that `self` is borrowed for `'static`
LL |     }
LL |     }
   |      - `self` dropped here while still borrowed
error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0597`.

---
test result: FAILED. 11695 passed; 1 failed; 122 ignored; 0 measured; 0 filtered out; finished in 105.75s



command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--suite" "ui" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/checkout/obj/build/x86_64-unknown-linux-gnu/llvm/build/bin/FileCheck" "--host-rustcflags" "-Crpath -Cdebuginfo=0 -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -Cdebuginfo=0 -Zunstable-options  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python3" "--lldb-python" "/usr/bin/python3" "--gdb" "/usr/bin/gdb" "--llvm-version" "12.0.0-rust-1.54.0-nightly" "--llvm-components" "aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker engine executionengine extensions filecheck frontendopenacc frontendopenmp fuzzmutate globalisel hellonew hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interfacestub interpreter ipo irreader jitlink libdriver lineeditor linker lto mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcjit orcshared orctargetprocess passes powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo runtimedyld scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target textapi transformutils vectorize webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info xray" "--cc" "" "--cxx" "" "--cflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--color" "always" "--compare-mode" "nll"


failed to run: /checkout/obj/build/bootstrap/debug/bootstrap --stage 2 test
Build completed unsuccessfully in 0:19:34
```

</details>

2021-05-02 09:29 UTC, ChrisPardy commented
@bors r=nikomatsakis

2021-05-02 15:01 UTC, Dylan-DPC commented
@bors retry yield

2021-05-02 15:05 UTC, rust-log-analyzer commented
A job failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/runs/2486868195) [(plain)](https://github.com/rust-lang-ci/rust/commit/67721110c86aa2bc57588bd21b19401c78228f9c/checks/2486868195/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

```

</details>

2021-05-02 17:20 UTC, merged