Deduplicate ParamCandidates with the same value except for bound vars
rust-lang/rust pull request #84559
Opened 2021-04-25 19:15 UTC by jackh726

Fixes #84398

This is kind of a hack. I wonder if we can get other types of candidates that are the same except for bound vars. This won't be a problem with Chalk, since we don't really need to know that there are two different "candidates" if they both give the same final substitution.

r? @nikomatsakis

2021-04-30 15:52 UTC, nikomatsakis requested changes

2021-04-30 15:52 UTC, nikomatsakis commented on compiler/rustc_trait_selection/src/traits/select/mod.rs
> +                    // duplicate candidates in the first place.
maybe we want to pick the one with fewer bound vars? it'd be nice to be more deterministic here

2021-05-04 15:40 UTC, pietroalbini commented
This fixes a regression that slipped into beta 1.53, nominating for backport.

2021-05-04 15:44 UTC, jackh726 commented
Status on this: discussed with @nikomatsakis a change he'd like to see here. Just have to get some time to implement it.

2021-05-06 15:00 UTC, nikomatsakis commented
@bors r+

2021-05-06 15:02 UTC, Mark-Simulacrum commented
@bors rollup=never p=1 we want this into master and backported soon, but I also want perf individually on it (no need to prerun)

2021-05-06 16:18 UTC, apiraino commented
Beta backport accepted as per compiler team [on Zulip](https://zulip-archive.rust-lang.org/238009tcompilermeetings/87937weekly2021050654818.html#237663853). Meanwhile a crater run could help assessing if this PR has any breakage.

@rustbot label +beta-accepted

2021-05-06 20:04 UTC, merged