Add HAS_RE_LATE_BOUND if there are bound vars
rust-lang/rust pull request #84653
Opened 2021-04-28 14:20 UTC by jackh726

Fixes #83737
Fixes #84604

I can rename `HAS_RE_LATE_BOUND`, to something like `HAS_LATE_BOUND_VARS`.

r? @nikomatsakis

2021-04-28 19:13 UTC, nikomatsakis requested changes
r=me with comment

2021-04-28 19:13 UTC, nikomatsakis commented on compiler/rustc_middle/src/ty/flags.rs
> +        if !value.bound_vars().is_empty() {
Let's have a comment about this. Something like:

In some cases, there are binders with variables that are unused (e.g., `for<'a> fn(u32)`). Set the flag to represent the `'a` in this example.

2021-04-28 19:53 UTC, jackh726 commented
@bors r=nikomatsakis

2021-04-28 20:00 UTC, nikomatsakis approved these changes

2021-04-29 20:01 UTC, richkadel commented
@jackh726 - As mentioned in Zulip, here's the error I get, with your patch added:

```
$ /usr/local/google/home/richkadel/rust/install/fuchsia-rust/bin/rustc --color=always --crate-name packet ../../src/lib/network/packet/src/lib.rs --crate-type rlib --emit=dep-info=host_x64-coverage-rust/obj/src/lib/network/packet/libpacket.rlib.d,link -Zdep-info-omit-d-target --cfg=rust_panic=\"unwind\" --cfg=__rust_toolchain=\"1\" -Clinker=/usr/local/google/home/richkadel/fuchsia/prebuilt/third_party/clang/linux-x64/bin/clang++ -Cdefault-linker-libraries -Clink-arg=-static-libstdc++ -Clink-arg=-Wl,-rpath=\$ORIGIN/ -Clink-arg=--sysroot=../../prebuilt/third_party/sysroot/linux -Clink-arg=--target=x86_64-unknown-linux-gnu -Clink-arg=-stdlib=libc++ -Clink-arg=-unwindlib= -Clink-arg=-rtlib=compiler-rt -Clink-arg=-fuse-ld=lld -Clink-arg=-Wl,--build-id --remap-path-prefix /usr/local/google/home/richkadel/fuchsia/=../../ -Copt-level=1 -Cdebuginfo=2 --edition=2018 -Zallow-features= --target x86_64-unknown-linux-gnu --cap-lints=deny -Wrust-2018-idioms -Dwarnings -Cdebug-assertions=yes -Clinker=/usr/local/google/home/richkadel/fuchsia/prebuilt/third_party/clang/linux-x64/bin/clang++ -Cdefault-linker-libraries -Clink-arg=-static-libstdc++ -Clink-arg=-Wl,-rpath=\$ORIGIN/ -Clink-arg=--sysroot=../../prebuilt/third_party/sysroot/linux -Clink-arg=--target=x86_64-unknown-linux-gnu -Clink-arg=-stdlib=libc++ -Clink-arg=-unwindlib= -Clink-arg=-rtlib=compiler-rt -Clink-arg=-fuse-ld=lld -Clink-arg=-Wl,--build-id -Zinstrument-coverage -Dunused_results -Aunused_results -o host_x64-coverage-rust/obj/src/lib/network/packet/libpacket.rlib -Ldependency=host_x64-coverage-rust/obj/garnet/lib/rust/never -Ldependency=host_x64-coverage-rust/obj/src/lib/zerocopy -Ldependency=host_x64-coverage-rust -Ldependency=host_x64-coverage-rust/obj/third_party/rust_crates -ldl -lpthread --extern never=host_x64-coverage-rust/obj/garnet/lib/rust/never/libnever.rlib --extern zerocopy=host_x64-coverage-rust/obj/src/lib/zerocopy/libzerocopy.rlib -Zverbose
error: internal compiler error: compiler/rustc_middle/src/ty/fold.rs:908:21: Not enough bound vars: BoundRegion { var: 0, kind: BrNamed(DefId(0:152 ~ packet[8787]::records::{impl#2}::'a), 'a) } not found in []

thread 'rustc' panicked at 'Box<Any>', /usr/local/google/home/richkadel/rust/library/std/src/panic.rs:59:5
stack backtrace:
   0:     0x7f60d2647440 - std::backtrace_rs::backtrace::libunwind::trace::ha7d16337b841d883
                               at /usr/local/google/home/richkadel/rust/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x7f60d2647440 - std::backtrace_rs::backtrace::trace_unsynchronized::h4d2aea7bfbfd56ca
                               at /usr/local/google/home/richkadel/rust/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f60d2647440 - std::sys_common::backtrace::_print_fmt::hd0fdedefad5751f4
                               at /usr/local/google/home/richkadel/rust/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7f60d2647440 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h70f980369b2ee381
                               at /usr/local/google/home/richkadel/rust/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7f60d26c251d - core::fmt::write::h1f76cfa4421eede5
                               at /usr/local/google/home/richkadel/rust/library/core/src/fmt/mod.rs:1094:17
   5:     0x7f60d263b405 - std::io::Write::write_fmt::hecda97db4f848d47
                               at /usr/local/google/home/richkadel/rust/library/std/src/io/mod.rs:1584:15
   6:     0x7f60d264b807 - std::sys_common::backtrace::_print::h9315faaa925010fd
                               at /usr/local/google/home/richkadel/rust/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7f60d264b807 - std::sys_common::backtrace::print::h79eeed0d43fae328
                               at /usr/local/google/home/richkadel/rust/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7f60d264b807 - std::panicking::default_hook::{{closure}}::hca2be370ec3225a7
                               at /usr/local/google/home/richkadel/rust/library/std/src/panicking.rs:208:50
   9:     0x7f60d264b21b - std::panicking::default_hook::hd07246c4e82d503a
                               at /usr/local/google/home/richkadel/rust/library/std/src/panicking.rs:225:9
  10:     0x7f60d3a377c9 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h3d32ebf2b803a351
                               at /usr/local/google/home/richkadel/rust/library/alloc/src/boxed.rs:1560:9
  11:     0x7f60d3a377c9 - rustc_driver::report_ice::h511fc520263bc3d7
                               at /usr/local/google/home/richkadel/rust/compiler/rustc_driver/src/lib.rs:1195:5
  12:     0x7f60d264c0ba - std::panicking::rust_panic_with_hook::h29481d192417bfde
                               at /usr/local/google/home/richkadel/rust/library/std/src/panicking.rs:595:17
  13:     0x7f60d6770310 - std::panicking::begin_panic::{{closure}}::h9a4f0968f111b4a2
                               at /usr/local/google/home/richkadel/rust/library/std/src/panicking.rs:520:9
  14:     0x7f60d67700f9 - std::sys_common::backtrace::__rust_end_short_backtrace::h44d8ac353a76c407
                               at /usr/local/google/home/richkadel/rust/library/std/src/sys_common/backtrace.rs:141:18
  15:     0x7f60d67702b2 - std::panicking::begin_panic::h6b057b5538e3ec73
                               at /usr/local/google/home/richkadel/rust/library/std/src/panicking.rs:519:12
  16:     0x7f60d6729f00 - std::panic::panic_any::hfe7d929255d2862c
                               at /usr/local/google/home/richkadel/rust/library/std/src/panic.rs:59:5
  17:     0x7f60d6731288 - rustc_errors::HandlerInner::bug::hb1f77d097a1f18cd
                               at /usr/local/google/home/richkadel/rust/compiler/rustc_errors/src/lib.rs:1002:9
  18:     0x7f60d672f0e3 - rustc_errors::Handler::bug::h94fa394c847f5441
                               at /usr/local/google/home/richkadel/rust/compiler/rustc_errors/src/lib.rs:712:9
  19:     0x7f60d636daae - rustc_middle::util::bug::opt_span_bug_fmt::{{closure}}::h4f6373782aa105fe
                               at /usr/local/google/home/richkadel/rust/compiler/rustc_middle/src/util/bug.rs:34:34
  20:     0x7f60d636b15b - rustc_middle::ty::context::tls::with_opt::{{closure}}::h1cc20541691940e4
                               at /usr/local/google/home/richkadel/rust/compiler/rustc_middle/src/ty/context.rs:1798:40
  21:     0x7f60d636b10a - rustc_middle::ty::context::tls::with_context_opt::h1558e1d5bf07588b
                               at /usr/local/google/home/richkadel/rust/compiler/rustc_middle/src/ty/context.rs:1750:22
  22:     0x7f60d636b10a - rustc_middle::ty::context::tls::with_opt::h6ee045d54e5cd5bf
                               at /usr/local/google/home/richkadel/rust/compiler/rustc_middle/src/ty/context.rs:1798:9
  23:     0x7f60d636d993 - rustc_middle::util::bug::opt_span_bug_fmt::h030a3ab043659085
                               at /usr/local/google/home/richkadel/rust/compiler/rustc_middle/src/util/bug.rs:30:5
  24:     0x7f60d636d905 - rustc_middle::util::bug::bug_fmt::h2814b13ab9fc3450
                               at /usr/local/google/home/richkadel/rust/compiler/rustc_middle/src/util/bug.rs:14:5
  25:     0x7f60d657a959 - <rustc_middle::ty::fold::ValidateBoundVars as rustc_middle::ty::fold::TypeVisitor>::visit_region::hdf285631d8adbe60
  26:     0x7f60d44516cc - rustc_middle::ty::structural_impls::<impl rustc_middle::ty::fold::TypeFoldable for &rustc_middle::ty::sty::RegionKind>::visit_with::h2b2a802667268da9
                               at /usr/local/google/home/richkadel/rust/compiler/rustc_middle/src/ty/structural_impls.rs:965:9
  27:     0x7f60d44516cc - <rustc_middle::ty::subst::GenericArg as rustc_middle::ty::fold::TypeFoldable>::super_visit_with::h21bee171c94022df
                               at /usr/ [...]

2021-04-29 20:22 UTC, richkadel commented
@jackh726 - Thanks for clarifying for me that the bug I pasted above only occurs with `debug = true`, and this PR still does fix the highlighted issues in the description, as long as `debug` is NOT enabled. And that you have a follow-up PR to fix the known issue with `debug` enabled (PR #84682). Thank you!

I'm going to hide my previous comment with the large stack trace.

2021-04-29 20:39 UTC, jackh726 commented
Closing in favor of #84682

2021-04-29 20:39 UTC, closed without merging