Optimize try_start to avoid using entry API
rust-lang/rust pull request #84806
Opened 2021-05-02 00:15 UTC by Mark-Simulacrum

The entry API generates more code and so ends up being slower to compile (this
patch saves us roughly 1.3% on the query_system, query_impl, and rustc_middle
crates put together).

This also extracts the cycle error creation into a separate function to help
avoid polluting the happy path a little more.

Plus, this should be a little better at runtime as well, as we see the happy
path - an insert into a fresh unused slot - have less recovery code on it. No
measurements there were performed, though, as the primary target here was
compile times; those will be done on the perf server.

2021-05-02 00:15 UTC, rust-highfive commented
r? @petrochenkov

(rust-highfive has picked a reviewer for you, use r? to override)

2021-05-02 00:15 UTC, Mark-Simulacrum commented
@bors try @rust-timer queue

2021-05-02 00:16 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

2021-05-02 01:03 UTC, rust-timer commented
Queued 2a30499874245ed414899e7f24a568990a4dfb9c with parent 4de75720970a223b125a811d3662fd15a08d4d18, future [comparison URL](https://perf.rust-lang.org/compare.html?start=4de75720970a223b125a811d3662fd15a08d4d18&end=2a30499874245ed414899e7f24a568990a4dfb9c).

2021-05-02 06:58 UTC, rust-timer commented
Finished benchmarking try commit (2a30499874245ed414899e7f24a568990a4dfb9c): [comparison url](https://perf.rust-lang.org/compare.html?start=4de75720970a223b125a811d3662fd15a08d4d18&end=2a30499874245ed414899e7f24a568990a4dfb9c).

Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. Please note that if the perf results are neutral, you should likely undo the rollup=never given below by specifying `rollup-` to bors.

Importantly, though, if the results of this run are non-neutral **do not** roll this PR up -- it will mask other regressions or improvements in the roll up.

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf

2021-05-02 07:22 UTC, petrochenkov commented
r? @cjgillot

2021-05-02 09:44 UTC, cjgillot requested changes
I like how this reduces the spaghettiness of the current code.
The bootstrap perf effect is small but interesting.
The runtime perf effect is marginally negative: do you have an idea why?

2021-05-02 09:44 UTC, cjgillot commented on compiler/rustc_query_system/src/query/plumbing.rs
> +            Some(QueryResult::Started(mut job)) => {
Most of the code inside this arm depends on parallel vs non-parallel.
It may be simpler to have two arms: one for parallel, one for non-parallel.

2021-05-02 09:44 UTC, cjgillot commented on compiler/rustc_query_system/src/query/plumbing.rs
> +        let query_blocked_prof_timer;
The variable can be declated directly where it is assigned, there is no code after the `match`.

2021-05-02 15:57 UTC, cjgillot commented
@bors r+

2021-05-02 16:11 UTC, Mark-Simulacrum commented
Pushed a cleanup fix to the code, but no performance fix quite yet.

I think the performance regression is because we're generating some extra code due to needing to re-fill the slot if we're encountering a cycle error; the entry API avoided this because it never inserted into an occupied slot. It's not entirely obvious though if this is the actual cause or not, hard to say.

Looking at a possible fix, in the meantime let me @bors r-

2021-05-02 16:24 UTC, Mark-Simulacrum commented
@bors try @rust-timer queue

Went back to using entry API, but still seems to be a compile-time win, just only ~0.5% instruction count wise. Will update PR description if the perf run comes back with no performance regression.

2021-05-02 16:24 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

2021-05-02 17:15 UTC, Mark-Simulacrum commented
@rust-timer build 75f6f6764205c5299fcdc2061a07476875511331

2021-05-02 17:15 UTC, rust-timer commented
Queued 75f6f6764205c5299fcdc2061a07476875511331 with parent 89ebad52a8b5a6d89d66a158d377cd7505ec4b48, future [comparison URL](https://perf.rust-lang.org/compare.html?start=89ebad52a8b5a6d89d66a158d377cd7505ec4b48&end=75f6f6764205c5299fcdc2061a07476875511331).

2021-05-02 22:39 UTC, rust-timer commented
Finished benchmarking try commit (75f6f6764205c5299fcdc2061a07476875511331): [comparison url](https://perf.rust-lang.org/compare.html?start=89ebad52a8b5a6d89d66a158d377cd7505ec4b48&end=75f6f6764205c5299fcdc2061a07476875511331).

Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. Please note that if the perf results are neutral, you should likely undo the rollup=never given below by specifying `rollup-` to bors.

Importantly, though, if the results of this run are non-neutral **do not** roll this PR up -- it will mask other regressions or improvements in the roll up.

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf

2021-05-02 22:44 UTC, Mark-Simulacrum commented
Looks like it retained the win on compile-time and is a slight bit faster, even.

2021-05-06 15:34 UTC, Mark-Simulacrum commented
r? @cjgillot

2021-05-06 17:50 UTC, cjgillot commented
@bors r+

2021-05-07 01:16 UTC, merged