Doc: Clarified the attribute which prompts the warning
rust-lang/rust pull request #85223
Opened 2021-05-12 13:03 UTC by simbleau

The example call was lacking clarification of the  `#![warn(rustdoc::invalid_codeblock_attributes)]` attribute which generates the specified warning.

2021-05-12 13:03 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @steveklabnik (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2021-05-12 13:26 UTC, jyn514 commented
It already shows it here: https://github.com/rust-lang/rust/pull/85223/files#diff-13b2c983ddb283f6812f85647105aaa7a89f2a697890095f02b9bbf82cf033ffR253
Why show it again?

Also, i don't think we should do this just this one lint, either all of them should have `warn` or none (my preference is none).

2021-05-12 13:43 UTC, simbleau commented
> It already shows it here: https://github.com/rust-lang/rust/pull/85223/files#diff-13b2c983ddb283f6812f85647105aaa7a89f2a697890095f02b9bbf82cf033ffR253
> Why show it again?
> 
> Also, i don't think we should do this just this one lint, either all of them should have `warn` or none (my preference is none).

This is one of very few outliers without the attribute specified to the user. It seems more verbose to the user, especially to notify users of the prepend `rustdoc::`. However, if there are others missing their attributes as well, I would be happy to fill in those gaps as well.

2021-05-16 16:23 UTC, jyn514 requested changes
You said

> This is one of 2 outliers without the attribute specified to the user. Every other example specifies the exact attribute in the examples given.

But that doesn't seem to be true? The only attributes I see are for demonstrating how to allow/warn/deny, or for turning on lints that are allowed by default.

2021-05-16 16:23 UTC, jyn514 commented on src/doc/rustdoc/src/lints.md
> +#![warn(private_intra_doc_links)]
Please use the rustdoc:: prefix, I'm hoping to remove the old version eventually.

2021-05-16 16:23 UTC, jyn514 commented on src/doc/rustdoc/src/lints.md
> +#![warn(bare_urls)]
Please use the rustdoc prefix.

2021-05-16 17:01 UTC, simbleau commented
What you said is true; I included them for clarity but the attribs are unnecessary due to their defaults. 
I opted to include them still (for consistency) but added a comment noting their necessity (for clarity).

Please review.

2021-05-16 19:22 UTC, jyn514 commented
I don't have time to finish this up, but @steveklabnik is assigned and he's a good reviewer for this :)

2021-07-14 01:11 UTC, Dylan-DPC commented
@steveklabnik any updates?

2021-09-12 08:08 UTC, JohnCSimon commented
Ping from triage: 
@steveklabnik any updates?

2021-09-28 02:07 UTC, JohnCSimon commented
Ping again from triage:
@steveklabnik any updates?

2021-10-01 18:25 UTC, steveklabnik approved these changes

2021-10-01 18:26 UTC, steveklabnik commented
Hi! So sorry, I don't know why but GitHub did *not* place this into my "reviews requested" notifications, and so I didn't realize I was the reviewer here.

@bors: r+ rollup

2021-10-02 01:32 UTC, merged