[MCP] introduce ty::WhereClause to align chalk and rustc dyn repr
rust-lang/rust pull request #85466
Opened 2021-05-19 11:58 UTC by csmoe

Closes https://github.com/rust-lang/wg-traits/issues/30
r? @nikomatsakis

2021-05-19 11:58 UTC, rust-highfive commented
Some changes occured to the CTFE / Miri engine

cc @rust-lang/miri

2021-05-19 12:05 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/2619895234) [(plain)](https://github.com/rust-lang/rust/commit/13b5427fc80333b89185aac3f1ab34176a8eb595/checks/2619895234/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking semver v0.11.0
    Checking toml v0.5.7
    Checking url v2.2.2
    Checking clippy_utils v0.1.54 (/checkout/src/tools/clippy/clippy_utils)
error[E0599]: no associated item named `AutoTrait` found for struct `Binder<'_, rustc_middle::ty::WhereClause<'_>>` in the current scope
   --> src/tools/clippy/clippy_utils/src/qualify_min_const_fn.rs:108:51
    |
108 |                         ty::ExistentialPredicate::AutoTrait(_) | ty::ExistentialPredicate::Projection(_) => {
    |                                                   ^^^^^^^^^ associated item not found in `Binder<'_, rustc_middle::ty::WhereClause<'_>>`

error[E0599]: no associated item named `Projection` found for struct `Binder<'_, rustc_middle::ty::WhereClause<'_>>` in the current scope
   --> src/tools/clippy/clippy_utils/src/qualify_min_const_fn.rs:108:92
    |
108 |                         ty::ExistentialPredicate::AutoTrait(_) | ty::ExistentialPredicate::Projection(_) => {
    |                                                                                            ^^^^^^^^^^ associated item not found in `Binder<'_, rustc_middle::ty::WhereClause<'_>>`

error[E0599]: no associated item named `Trait` found for struct `Binder<'_, rustc_middle::ty::WhereClause<'_>>` in the current scope
   --> src/tools/clippy/clippy_utils/src/qualify_min_const_fn.rs:116:51
    |
116 |                         ty::ExistentialPredicate::Trait(trait_ref) => {
    |                                                   ^^^^^ associated item not found in `Binder<'_, rustc_middle::ty::WhereClause<'_>>`

error[E0599]: no associated item named `Trait` found for struct `Binder<'_, rustc_middle::ty::WhereClause<'_>>` in the current scope
   --> src/tools/clippy/clippy_utils/src/ty.rs:169:50
    |
169 |                 if let ty::ExistentialPredicate::Trait(ref trait_ref) = predicate.skip_binder() {
    |                                                  ^^^^^ associated item not found in `Binder<'_, rustc_middle::ty::WhereClause<'_>>`
error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `clippy_utils`
```

</details>

2021-06-08 03:13 UTC, csmoe commented
@nikomatsakis ping for a review🔔

2021-07-03 16:56 UTC, jackh726 requested changes

2021-07-03 16:56 UTC, jackh726 commented on compiler/rustc_middle/src/ty/sty.rs
> +pub type ExistentialPredicate<'tcx> = Binder<'tcx, WhereClause<'tcx>>;
This isn't quite right. The difference between rustc and Chalk isn't solely the name. In Chalk, there's actually two layers of Binders. One that contains a single type that represents `Self`, and one that represents the vars on the predicates itself. See https://github.com/rust-lang/chalk/blob/802599ce2ca02f322c078f472e64c5cd3a208225/chalk-solve/src/rust_ir.rs#L233

2021-07-03 18:16 UTC, jackh726 commented on compiler/rustc_middle/src/ty/sty.rs
> +pub type ExistentialPredicate<'tcx> = Binder<'tcx, WhereClause<'tcx>>;
I guess the big thing missing here is the removal of `erase_self_ty`. And along with that, make the `Self` ty actually be a bound var.

2021-09-13 03:43 UTC, JohnCSimon commented
ping from triage:
@csmoe 
Returning to you to address merge conflicts and after that switch this back to `S-waiting-on-review`.
thanks.

2021-09-15 16:56 UTC, nikomatsakis commented
@csmoe sorry this PR disappeared from my radar

2021-09-15 16:57 UTC, nikomatsakis commented
Are you still around?

2021-09-24 00:27 UTC, csmoe commented
> Are you still around? 

yep, time was tough. I'm back :)

2021-09-30 20:16 UTC, nikomatsakis commented
Augh! Let me give this a quick review @csmoe

2021-09-30 20:48 UTC, nikomatsakis reviewed
OK, so, I read the PR. From what I can tell, before this PR:

* We have `Binder<ExistentialPredicate>`, where `ExistentialPredicate` is a subset of predicates that don't have `Self` position specified.

After this PR:

* We introduce `WhereClause` to be the old `ExistentialPredicate`, and we make `ExistentialPredicate` an alias for `Binder<WC>`

This seems good, but indeed only a first step in the ultimate direction. Ultimately we want to extend `WhereClause` so it includes the `Self` type, and @jackh726 is right that this will mean introducing *another* level of Binder.

I think we also want to share WhereClause with Predicate.

2021-10-07 11:05 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-10`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3826194777) [(plain)](https://github.com/rust-lang/rust/commit/8c71935f02ff0b2e71aa68209f07afc287f421f1/checks/3826194777/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-nightly (99ed79e8b 2021-10-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z macro-backtrace -Z crate-attr=doc(html_root_url="https://doc.rust-lang.org/nightly/") -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=3 -C embed-bitcode=no -C codegen-units=1 -C debuginfo=0 -C debug-assertions=on -C overflow-checks=off -C link-args=-Wl,-rpath,$ORIGIN/../lib -C prefer-dynamic -C llvm-args=-import-instr-limit=10 -C embed-bitcode=yes --crate-type lib
note: some of the compiler flags provided by cargo are hidden

query stack during panic:
query stack during panic:
#0 [inferred_outlives_crate] computing the inferred outlives predicates for items in this crate
#1 [inferred_outlives_of] computing inferred outlives predicates of `mem::maybe_uninit::MaybeUninit`
error: could not compile `core`
warning: build failed, waiting for other jobs to finish...
error: build failed
Build completed unsuccessfully in 0:03:39
```

</details>

2021-10-31 10:43 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/4059589548?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/12453ceacb8e1a5c8165c4822edd361cf3c9e24b/checks/4059589548/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking rustc_ast_lowering v0.0.0 (/checkout/compiler/rustc_ast_lowering)
    Checking rustc_ast_passes v0.0.0 (/checkout/compiler/rustc_ast_passes)
    Checking rustc_expand v0.0.0 (/checkout/compiler/rustc_expand)
    Checking rustc_builtin_macros v0.0.0 (/checkout/compiler/rustc_builtin_macros)
error[E0599]: no function or associated item named `erase_self_ty` found for struct `ExistentialTraitRef` in the current scope
   --> compiler/rustc_middle/src/ty/vtable.rs:100:69
    |
100 |                     .map_bound(|trait_ref| ty::ExistentialTraitRef::erase_self_ty(tcx, trait_ref));
    |                                                                     ^^^^^^^^^^^^^ function or associated item not found in `ExistentialTraitRef<'_>`
   ::: compiler/rustc_middle/src/ty/sty.rs:901:1
    |
    |
901 | pub struct ExistentialTraitRef<'tcx> {
    | ------------------------------------ function or associated item `erase_self_ty` not found for this
For more information about this error, try `rustc --explain E0599`.
error: could not compile `rustc_middle` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

</details>

2021-11-01 15:06 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/4069201697?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/5df47642272c620dbb5052b899814cd9327d8c97/checks/4069201697/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.58.0-nightly (8e3673c9b 2021-11-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z symbol-mangling-version=legacy -Z macro-backtrace -Z crate-attr=doc(html_root_url="https://doc.rust-lang.org/nightly/") -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=3 -C embed-bitcode=no -C codegen-units=1 -C debuginfo=0 -C debug-assertions=on -C link-args=-Wl,-rpath,$ORIGIN/../lib -C prefer-dynamic -C llvm-args=-import-instr-limit=10 -C embed-bitcode=yes --crate-type lib
note: some of the compiler flags provided by cargo are hidden

query stack during panic:
query stack during panic:
#0 [inferred_outlives_crate] computing the inferred outlives predicates for items in this crate
#1 [inferred_outlives_of] computing inferred outlives predicates of `cell::UnsafeCell`
error: could not compile `core`
warning: build failed, waiting for other jobs to finish...
error: build failed
Build completed unsuccessfully in 0:04:12
```

</details>

2021-11-14 13:04 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/4203479760?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/c6a4dbe3a87dcfff214fa59f2b4ade806bf4290f/checks/4203479760/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.58.0-nightly (6f7dc9a98 2021-11-14) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z symbol-mangling-version=legacy -Z macro-backtrace -Z crate-attr=doc(html_root_url="https://doc.rust-lang.org/nightly/") -Z binary-dep-depinfo -Z force-unstable-if-unmarked -C opt-level=3 -C embed-bitcode=no -C codegen-units=1 -C debuginfo=0 -C debug-assertions=on -C link-args=-Wl,-rpath,$ORIGIN/../lib -C prefer-dynamic -C llvm-args=-import-instr-limit=10 -C embed-bitcode=yes --crate-type lib
note: some of the compiler flags provided by cargo are hidden

query stack during panic:
query stack during panic:
#0 [inferred_outlives_crate] computing the inferred outlives predicates for items in this crate
#1 [inferred_outlives_of] computing inferred outlives predicates of `cell::UnsafeCell`
error: could not compile `core`
Build completed unsuccessfully in 0:04:06
```

</details>

2021-12-17 17:53 UTC, crlf0710 commented
@csmoe Ping from triage: Any updates here?

2022-02-22 02:15 UTC, Dylan-DPC commented
Closing this as inactive

2022-02-22 02:15 UTC, closed without merging