fix `matches!` and `assert_matches!` on edition 2021
rust-lang/rust pull request #85678
Opened 2021-05-25 14:49 UTC by lukas-code

Previously this code failed to compile on edition 2021. [(Playground)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=53960f2f051f641777b9e458da747707)
```rust
fn main() {
    matches!((), ());
}
```
```
   Compiling playground v0.0.1 (/playground)
error: `$pattern:pat` may be followed by `|`, which is not allowed for `pat` fragments
    |
    = note: allowed there are: `=>`, `,`, `=`, `if` or `in`

error: aborting due to previous error

error: could not compile `playground`

To learn more, run the command again with --verbose.
```

2021-05-25 14:49 UTC, rust-highfive commented
r? @dtolnay

(rust-highfive has picked a reviewer for you, use r? to override)

2021-05-25 14:53 UTC, dtolnay requested changes
Thanks! Is it possible to get a test for this? I believe the ui test harness supports setting the edition that tests are built with.

https://github.com/rust-lang/rust/blob/fbf1b1a7193cda17008ab590e06ad28d9924023b/src/test/ui/hello2021.rs#L2-L3

2021-05-25 15:39 UTC, lukas-code commented
I added a regression test.

2021-05-25 15:52 UTC, ehuss commented
I haven't seen any discussion about proceeding with this solution for #84429. As of this morning, there is work going on to fix the hygiene problem. Was there some discussion on this?

2021-05-25 15:57 UTC, petrochenkov commented
@ehuss 
>I haven't seen any discussion about proceeding with this solution for #84429.

https://github.com/rust-lang/rust/pull/84452#issuecomment-826362457 ?

2021-05-25 16:43 UTC, ehuss commented
Ah, forgot about that!  I do believe they should be equivalent, even when std is migrated to 2021, so I don't think it matters much one way or the other.  

Just a forewarning, I think this may conflict with #85272, so the two PRs will be racing one another.

2021-05-26 02:19 UTC, dtolnay approved these changes

2021-05-26 02:19 UTC, dtolnay commented
@bors r+

2021-05-26 04:07 UTC, Aaron1011 commented
Note that this PR only fixes the problem for the specific `matches!` macro in the standard library. Any 2018 edition crate which defines a similar macro will have the same problem when invoked from a 2021-edition crate. This PR is still fine to land, since we're just explicitly indicating (via `:pat_param`) the behavior that we should be getting from `:pat`.

PR https://github.com/rust-lang/rust/pull/85709 fixes this for all macro definitions.

2021-05-26 16:35 UTC, merged