Initial support for force-warns
rust-lang/rust pull request #85788
Opened 2021-05-28 16:26 UTC by rylev

Initial addressing of https://github.com/rust-lang/rust/issues/85512.

This PR adds a new command line option `force-warns` which will force the provided lints to warn even if they are allowed by some other mechanism such as `#![allow(warnings)]`.

Some remaining issues:
* https://github.com/rust-lang/rust/issues/85512 mentions that `force-warns` should also be capable of taking lint groups instead of individual lints. This is not implemented. 
* If a lint has a higher warning level than `warn`, this will cause that lint to warn instead. We probably want to allow the lint to error if it is set to a higher lint and is not allowed somewhere else. 
* One test is currently ignored because it's not working - when a deny-by-default lint is allowed, it does not currently warn under `force-warns`. I'm not sure why, but I wanted to get this in before the weekend. 

r? @nikomatsakis

2021-05-28 16:30 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/2696064693) [(plain)](https://github.com/rust-lang/rust/commit/69a19bfd4345a73836194f28e35c620d9005a825/checks/2696064693/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
  |
4 | use chalk_ir::Substitution;
  |     ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `-D unused-imports` implied by `-D warnings`
    Checking chalk-engine v0.55.0
error: aborting due to previous error

error: could not compile `rustc_middle`
error: could not compile `rustc_middle`

To learn more, run the command again with --verbose.
command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "check" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "16" "--release" "--color" "always" "--features" " llvm max_level_info" "--manifest-path" "/checkout/compiler/rustc/Cargo.toml" "-p" "rustc-main" "-p" "rustc_codegen_ssa" "-p" "rustc_target" "-p" "rustc_ast" "-p" "rustc_lexer" "-p" "rustc_serialize" "-p" "rustc_span" "-p" "rustc_arena" "-p" "rustc_incremental" "-p" "rustc_graphviz" "-p" "rustc_apfloat" "-p" "rustc_fs_util" "-p" "rustc_hir" "-p" "rustc_feature" "-p" "rustc_symbol_mangling" "-p" "rustc_session" "-p" "rustc_lint_defs" "-p" "rustc_errors" "-p" "rustc_middle" "-p" "rustc_type_ir" "-p" "rustc_query_system" "-p" "rustc_attr" "-p" "rustc_ast_pretty" "-p" "rustc_data_structures" "-p" "rustc_index" "-p" "rustc_macros" "-p" "rustc_driver" "-p" "rustc_parse" "-p" "rustc_save_analysis" "-p" "rustc_mir" "-p" "rustc_trait_selection" "-p" "rustc_parse_format" "-p" "coverage_test_macros" "-p" "rustc_infer" "-p" "rustc_typeck" "-p" "rustc_ty_utils" "-p" "rustc_plugin_impl" "-p" "rustc_mir_build" "-p" "rustc_metadata" "-p" "rustc_expand" "-p" "rustc_ast_passes" "-p" "rustc_error_codes" "-p" "rustc_lint" "-p" "rustc_hir_pretty" "-p" "rustc_interface" "-p" "rustc_traits" "-p" "rustc_ast_lowering" "-p" "rustc_privacy" "-p" "rustc_query_impl" "-p" "rustc_codegen_llvm" "-p" "rustc_llvm" "-p" "rustc_passes" "-p" "rustc_resolve" "-p" "rustc_builtin_macros" "--message-format" "json-render-diagnostics"
failed to run: /checkout/obj/build/bootstrap/debug/bootstrap check
Build completed unsuccessfully in 0:01:46
```

</details>

2021-06-01 16:06 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/2720427799) [(plain)](https://github.com/rust-lang/rust/commit/d8585d5c064539459970bb2b21cf8690debcaa8e/checks/2720427799/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking rustc_typeck v0.0.0 (/checkout/compiler/rustc_typeck)
error: unused variable: `symbol`
   --> compiler/rustc_lint/src/levels.rs:150:48
    |
150 |                     LintLevelSource::ForceWarn(symbol) => {
    |                                                ^^^^^^ help: if this is intentional, prefix it with an underscore: `_symbol`
    |
    = note: `-D unused-variables` implied by `-D warnings`
error: aborting due to previous error

error: could not compile `rustc_lint`


To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "check" "--target" "x86_64-unknown-linux-gnu" "-Zbinary-dep-depinfo" "-j" "16" "--release" "--color" "always" "--features" " llvm max_level_info" "--manifest-path" "/checkout/compiler/rustc/Cargo.toml" "-p" "rustc-main" "-p" "rustc_driver" "-p" "rustc_error_codes" "-p" "rustc_save_analysis" "-p" "rustc_lexer" "-p" "rustc_hir_pretty" "-p" "rustc_metadata" "-p" "rustc_expand" "-p" "rustc_lint_defs" "-p" "rustc_ast_passes" "-p" "rustc_attr" "-p" "rustc_macros" "-p" "rustc_index" "-p" "rustc_data_structures" "-p" "rustc_graphviz" "-p" "rustc_errors" "-p" "rustc_lint" "-p" "rustc_parse_format" "-p" "rustc_trait_selection" "-p" "rustc_infer" "-p" "rustc_hir" "-p" "rustc_typeck" "-p" "rustc_arena" "-p" "rustc_ty_utils" "-p" "rustc_ast" "-p" "rustc_parse" "-p" "rustc_interface" "-p" "rustc_query_impl" "-p" "rustc_query_system" "-p" "rustc_builtin_macros" "-p" "rustc_traits" "-p" "rustc_ast_lowering" "-p" "rustc_symbol_mangling" "-p" "rustc_resolve" "-p" "rustc_incremental" "-p" "rustc_fs_util" "-p" "rustc_passes" "-p" "rustc_privacy" "-p" "rustc_codegen_llvm" "-p" "rustc_llvm" "-p" "rustc_feature" "-p" "rustc_target" "-p" "rustc_serialize" "-p" "rustc_session" "-p" "rustc_plugin_impl" "-p" "rustc_mir_build" "-p" "rustc_apfloat" "-p" "rustc_mir" "-p" "coverage_test_macros" "-p" "rustc_ast_pretty" "-p" "rustc_middle" "-p" "rustc_type_ir" "-p" "rustc_span" "-p" "rustc_codegen_ssa" "--message-format" "json-render-diagnostics"
failed to run: /checkout/obj/build/bootstrap/debug/bootstrap check
Build completed unsuccessfully in 0:02:27
```

</details>

2021-06-01 16:49 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/2720763887) [(plain)](https://github.com/rust-lang/rust/commit/4675690ac4022a937f6817570e06f987c2efbc61/checks/2720763887/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking rustdoc v0.0.0 (/checkout/src/librustdoc)
error[E0308]: mismatched types
   --> src/librustdoc/config.rs:631:13
    |
631 |         let (lint_opts, describe_lints, lint_cap) = get_cmd_lint_options(matches, error_format);
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   ------------------------------------------- this expression has type `(Vec<(std::string::String, rustc_lint_defs::Level)>, bool, std::option::Option<rustc_lint_defs::Level>, Vec<std::string::String>)`
    |             |
    |             expected a tuple with 4 elements, found one with 3 elements
    |
    = note: expected tuple `(Vec<(std::string::String, rustc_lint_defs::Level)>, bool, std::option::Option<rustc_lint_defs::Level>, Vec<std::string::String>)`
               found tuple `(_, _, _)`
error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rustdoc`
```

</details>

2021-06-02 00:39 UTC, nikomatsakis requested changes
Left some notes on how to make this support lint groups (I think)

2021-06-02 00:39 UTC, nikomatsakis commented on compiler/rustc_lint/src/levels.rs
> +            store.check_lint_name_cmdline(sess, &lint_name, Level::Allow); // FIXME level is wrong
So... I think you have a few options here to handle groups. Probably the one I like best is to do this.

```rust
match store.check_lint_name(sess, &lint_name) {
    CheckLintNameResult::Ok(lint_ids) => {
        self.sets.force_warns.extend(lint_ids);
    }
    CheckLintNameResult::NoLint(...) => {
        /* report useful error */
    }
    ...
}
```

though you could modify the `check_lint_name_cmdline` to give more appropriate errors and use `store.find_lints(&lint_name)` instead.

2021-06-02 00:39 UTC, nikomatsakis commented on compiler/rustc_middle/src/lint.rs
> +    pub force_warns: FxHashSet<String>,
This should be changed to `FxHashSet<LintId>`

2021-06-02 00:39 UTC, nikomatsakis commented on compiler/rustc_middle/src/lint.rs
> +        if self.force_warns.contains(lint.name) {
and this should be changed to `self.force_warns.contains(&LintId::of(lint))`

2021-06-02 15:24 UTC, nikomatsakis requested changes

2021-06-02 15:24 UTC, nikomatsakis commented on compiler/rustc_middle/src/lint.rs
> +                    "Warning forced by `force-warns` commandline option",
```suggestion
                    "warning forced by `force-warns` commandline option",
```

our style guide requests lower case here

2021-06-02 15:27 UTC, nikomatsakis reviewed
Can you add an entry to the unstable book compiler flags listing:

https://github.com/rust-lang/rust/tree/master/src/doc/unstable-book/src/compiler-flags

I'm not sure if there is a SUMMARY.md to edit

2021-06-02 16:34 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/2729619826) [(plain)](https://github.com/rust-lang/rust/commit/ab419314e95b26d6e8662f896508b5efe3fcc3a3/checks/2729619826/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.channel         := nightly
configure: rust.debug-assertions := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
* highest error code: E0783
Found 517 error codes
Found 0 error codes with no tests
Done!
tidy error: /checkout/src/doc/unstable-book/src/compiler-flags/force-warns.md:15: trailing whitespace
some tidy checks failed



command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/rust-tidy" "/checkout" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "/checkout/obj/build" "16"


failed to run: /checkout/obj/build/bootstrap/debug/bootstrap test --stage 2 src/tools/tidy
Build completed unsuccessfully in 0:00:16
```

</details>

2021-06-02 17:37 UTC, cjgillot commented
Can this feature be implemented more simply as an additional lint level, similar to "forbid" but for warnings?

2021-06-03 08:22 UTC, rylev commented
@cjgillot I _think_ it would be possible, but I'm not convinced it would be more simple. We want these lints to behave as they currently do in all situations except in the one case where we want to force them to warn. Having another lint level would force more of a cognitive burden on users and documentation maintenance.

2021-06-03 08:33 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-10`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/2735218495) [(plain)](https://github.com/rust-lang/rust/commit/81da9b48aafa49bcd8f9394210a58fa51460b672/checks/2735218495/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
............................i....................................................................... 6200/11949
.i.................................................................................................. 6300/11949
.................................................................ii.ii.......i...i.................. 6400/11949
.................................................................................................... 6500/11949
.........i....i..................................i...........................i................FFF.FF 6600/11949
FF.F.F.............................................................................................. 6700/11949
.................................................................................................... 6900/11949
.......................ii...............................................i........................... 7000/11949
.................................................................................................... 7100/11949
.................................................................................................... 7200/11949
---
........................................i.i......................................................... 11900/11949
.................................................
failures:

---- [ui] ui/lint/force-warn/force-allowed-deny-by-default-lint.rs stdout ----

6    |                |
6    |                |
7    |                attempt to divide `1_i32` by zero
8    |
-    = note: Warning forced by `force-warns` commandline option
+    = note: warning forced by `force-warns` commandline option
Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
11    = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>
12 



The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/force-warn/force-allowed-deny-by-default-lint/force-allowed-deny-by-default-lint.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args lint/force-warn/force-allowed-deny-by-default-lint.rs`
error: 1 errors occurred comparing output.
status: exit status: 0
status: exit status: 0
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/lint/force-warn/force-allowed-deny-by-default-lint.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/force-warn/force-allowed-deny-by-default-lint" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--force-warns" "const_err" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/force-warn/force-allowed-deny-by-default-lint/auxiliary"
------------------------------------------

------------------------------------------
stderr:
stderr:
------------------------------------------
warning: any use of this value will cause an error
  --> /checkout/src/test/ui/lint/force-warn/force-allowed-deny-by-default-lint.rs:5:16
   |
LL | const C: i32 = 1 / 0;
   |                |
   |                |
   |                attempt to divide `1_i32` by zero
   |
   = note: warning forced by `force-warns` commandline option
   = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>

warning: 1 warning emitted



------------------------------------------


---- [ui] ui/lint/force-warn/force-allowed-by-default-lint.rs stdout ----


4 LL | fn foo(x: &Foo) {}
5    |            ^^^- help: indicate the anonymous lifetime: `<'_>`
6    |
-    = note: Warning forced by `force-warns` commandline option
+    = note: warning forced by `force-warns` commandline option
9 warning: 1 warning emitted
10 



The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/force-warn/force-allowed-by-default-lint/force-allowed-by-default-lint.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args lint/force-warn/force-allowed-by-default-lint.rs`
error: 1 errors occurred comparing output.
status: exit status: 0
status: exit status: 0
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/lint/force-warn/force-allowed-by-default-lint.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/force-warn/force-allowed-by-default-lint" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--force-warns" "elided_lifetimes_in_paths" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/force-warn/force-allowed-by-default-lint/auxiliary"
------------------------------------------

------------------------------------------
stderr:
stderr:
------------------------------------------
warning: hidden lifetime parameters in types are deprecated
  --> /checkout/src/test/ui/lint/force-warn/force-allowed-by-default-lint.rs:8:12
   |
LL | fn foo(x: &Foo) {}
   |            ^^^- help: indicate the anonymous lifetime: `<'_>`
   |
   = note: warning forced by `force-warns` commandline option
warning: 1 warning emitted


------------------------------------------
------------------------------------------


---- [ui] ui/lint/force-warn/force-lint-allow-all-warnings.rs stdout ----

4 LL | fn dead_function() {}
5    |    ^^^^^^^^^^^^^
6    |
6    |
-    = note: Warning forced by `force-warns` commandline option
+    = note: warning forced by `force-warns` commandline option
9 warning: 1 warning emitted
10 



The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/force-warn/force-lint-allow-all-warnings/force-lint-allow-all-warnings.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args lint/force-warn/force-lint-allow-all-warnings.rs`
error: 1 errors occurred comparing output.
status: exit status: 0
status: exit status: 0
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/lint/force-warn/force-lint-allow-all-warnings.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/force-warn/force-lint-allow-all-warnings" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--force-warns" "dead_code" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lint/force-warn/force-lint-allow-all-warnings/auxiliary"
------------------------------------------

------------------------------------------
stderr:
stderr:
------------------------------------------
warning: function is neve [...]

2021-06-03 13:29 UTC, nikomatsakis approved these changes

2021-06-03 13:29 UTC, nikomatsakis commented
@bors r+

2021-06-04 16:13 UTC, merged