2229: Reduce the size of closures with `capture_disjoint_fields`
rust-lang/rust pull request #86701
Opened 2021-06-28 20:54 UTC by arora-aman

One key observation while going over the closure size profile of rustc
was that we are disjointly capturing one or more fields starting at an
immutable reference.

Disjoint capture over immutable reference doesn't add too much value
because the fields can either be borrowed immutably or copied.

One possible edge case of the optimization is when a fields of a struct
have a longer lifetime than the structure, therefore we can't completely
get rid of all the accesses on top of sharef refs, only the rightmost
one. Here is a possible example:

```rust
struct MyStruct<'a> {
   a: &'static A,
   b: B,
   c: C<'a>,
}

fn foo<'a, 'b>(m: &'a MyStruct<'b>) -> impl FnMut() + 'static {
    let c = || drop(&*m.a.field_of_a);
    // Here we really do want to capture `*m.a` because that outlives `'static`

    // If we capture `m`, then the closure no longer outlives `'static'
    // it is constrained to `'a`
}
```

r? @nikomatsakis

2021-06-28 21:05 UTC, arora-aman commented
I profile the change in closure size before and after the change:

Baseline: https://docs.google.com/spreadsheets/d/1U5vaXu490wn8Ae1LB1mSfoP_EZrGRHbUU6ADbeY8bn4/edit#gid=545238654
After optimization: 
https://docs.google.com/spreadsheets/d/1zOOeTFz4AvprEVsiPNFlkt4x_93N7WQe2uv2pX3BzXQ/edit#gid=545238654

2021-06-28 21:11 UTC, arora-aman commented on src/test/ui/closures/2229_closure_analysis/optimization/edge_case_run_pass.rs
> +#![feature(capture_disjoint_fields)]
waiting on the editon PR to go in for this to work

2021-06-28 21:16 UTC, arora-aman commented
Notes from 2229 sync: https://hackmd.io/hpjgfcwaSK20uFtZibwhIw

2021-06-28 21:17 UTC, arora-aman commented on src/test/ui/closures/2229_closure_analysis/optimization/edge_case_run_pass.rs
> +#![feature(capture_disjoint_fields)]
To change this to use edition*

2021-07-05 21:07 UTC, nikomatsakis approved these changes

2021-07-05 21:12 UTC, nikomatsakis requested changes

2021-07-05 21:12 UTC, nikomatsakis commented on compiler/rustc_typeck/src/check/upvar.rs
> +    let idx = place.projections.iter().rposition(|proj| ProjectionKind::Deref == proj.kind);
```suggestion
    // Find the right-most deref (if any). All the projections that come after this
    // are fields or other "in-place pointer adjustments"; these refer therefore to
    // data owned by whatever pointer is being dereferenced here.
    let idx = place.projections.iter().rposition(|proj| ProjectionKind::Deref == proj.kind);
```

2021-07-05 21:12 UTC, nikomatsakis commented on compiler/rustc_typeck/src/check/upvar.rs
> +        Some(idx) if is_shared_ref(place.ty_before_projection(idx)) => {
```suggestion
        // If that pointer is a shared reference, then we don't need those fields.
        Some(idx) if is_shared_ref(place.ty_before_projection(idx)) => {
```

2021-07-05 21:13 UTC, nikomatsakis commented
@bors delegate+

r=me with comments added

2021-07-07 00:53 UTC, nikomatsakis approved these changes

2021-07-07 00:53 UTC, nikomatsakis commented
@bors r+

2021-07-09 03:54 UTC, merged