Show discriminant before overflow in diagnostic for duplicate values.
rust-lang/rust pull request #87166
Opened 2021-07-15 20:07 UTC by de-vri-es

This PR adds the value before overflow for explicit discriminant values in the error for duplicate discriminant values. It only does this for literals, since overflows in const evaluated arithmatic are already a hard error.

I found it rather confusing to see only the overflowed value.

This is my first PR to the compiler, so please let me know if the implementation can be improved :)

Before:
![image](https://user-images.githubusercontent.com/786213/125850097-bf5fb7e0-d800-4386-a738-c30f41822964.png)

After:
![image](https://user-images.githubusercontent.com/786213/125850120-e2bb765d-ad86-4888-a6cb-dec34fba3fea.png)

@rustbot label +T-compiler +A-diagnostics +C-enhancement +D-terse

2021-07-15 20:07 UTC, rust-highfive commented
r? @jackh726

(rust-highfive has picked a reviewer for you, use r? to override)

2021-07-15 21:04 UTC, de-vri-es commented on compiler/rustc_typeck/src/check/check.rs
> +    format!("{}", evaluated)
Note: I also removed the backticks around the number. They seemed unnecessary to me: the value is always a decimal number, which already stands out from normal text quite well. But I can revert this if desired.

2021-07-27 03:23 UTC, jackh726 requested changes
So, I'd like to actually see a test where the *first* discriminant overflows (like in the OP). And I think that the backticks around the value should remain (backticks generally specify a value or code).

And finally (this one is a bit more opinionated): I feel like the exact number here isn't super helpful. It might be better to say some like "overflowed from `usize`"

2021-07-28 08:10 UTC, de-vri-es commented
> So, I'd like to actually see a test where the _first_ discriminant overflows (like in the OP). And I think that the backticks around the value should remain (backticks generally specify a value or code).

Makes sense. I added another test case in `src/test/ui/error-codes/E0081.rs`. Let me know if the test case should be in a new file instead, I'll move it.

I added the backticks back, and I removed the overflow value from the main error message, leaving it only in the notes. With that, it now looks like this:

![image](https://user-images.githubusercontent.com/786213/127287180-e97b2bc0-fdc3-45d8-a7c6-45bf4ac2d8ff.png)


> And finally (this one is a bit more opinionated): I feel like the exact number here isn't super helpful. It might be better to say some like "overflowed from `usize`"

Hmm, I actually like to see the value before overflow. It lets me know that neither me nor the compiler have gone mad and we're both really talking about the same number.

2021-08-20 13:20 UTC, jackh726 commented
Sorry for the wait here. @bors r+ rollup

2021-08-20 14:12 UTC, de-vri-es commented
Thanks for the review! :)

2021-08-22 23:04 UTC, merged