Bail on any found recursion when expanding opaque types
rust-lang/rust pull request #87546
Opened 2021-07-28 12:24 UTC by hkratz

Fixes #87450. More of a bandaid because it does not fix the exponential complexity of the type folding used for opaque type expansion.

2021-07-28 12:24 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @davidtwco (or someone else) soon.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2021-07-30 14:09 UTC, davidtwco requested changes
Could you add the test case from #87450?

2021-07-30 18:44 UTC, lqd commented
Since this test is exercizing exponential compile times, how long does it take to compile with this PR ? (it would be good not to slow down CI and contributors' tests too much with a huge stress test :)

2021-07-30 18:59 UTC, hkratz commented
> Since this test is exercizing exponential compile times, how long does it take to compile with this PR ? (it would be good not to slow down CI and contributors' tests too much with a huge stress test :)

It is pretty fast on the testcase from issue 87450: From >400 seconds down to 0.06 on my machine:
```
rm build/x86_64-unknown-linux-gnu/test/ui/impl-trait/issue-87450/stamp; ./x.py test src/test/ui/impl-trait/issue-87450.rs
[...]
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 12184 filtered out; finished in 0.06s
```
One would need to add much more recursion to get a significant runtime (i.e. >20 `wrap()` calls).

2021-07-30 21:14 UTC, davidtwco approved these changes

2021-07-30 21:14 UTC, davidtwco commented
@bors r+

2021-07-31 10:39 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-aux`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/runs/3208525306) [(plain)](https://github.com/rust-lang-ci/rust/commit/92f015cefdfc37b37b6e9392a638f1fc9fdf3b7f/checks/3208525306/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
thread 'main' panicked at 'assertion failed: status.success()', src/tools/cargotest/main.rs:125:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/cargotest" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2-tools-bin/cargo" "/checkout/obj/build/ct"
expected success, got: exit status: 101
expected success, got: exit status: 101


Build completed unsuccessfully in 0:24:57
make: *** [check-aux] Error 1
Makefile:44: recipe for target 'check-aux' failed
```

</details>

2021-07-31 10:49 UTC, hkratz commented
```
testing https://github.com/servo/servo
Initialized empty Git repository in /checkout/obj/build/ct/servo/.git/
fatal: Could not parse object 'caac107ae8145ef2fd20365e2b8fadaf09c2eb3b'.
From https://github.com/servo/servo
 * branch            master     -> FETCH_HEAD
fatal: Could not parse object 'caac107ae8145ef2fd20365e2b8fadaf09c2eb3b'.
From https://github.com/servo/servo
 * branch            master     -> FETCH_HEAD
fatal: Could not parse object 'caac107ae8145ef2fd20365e2b8fadaf09c2eb3b'.
From https://github.com/servo/servo
 * branch            master     -> FETCH_HEAD
fatal: Could not parse object 'caac107ae8145ef2fd20365e2b8fadaf09c2eb3b'.
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
thread 'main' panicked at 'assertion failed: status.success()', src/tools/cargotest/main.rs:125:13
```

Intermittent connectivity issue during bors run?

2021-07-31 13:20 UTC, hkratz commented
> error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
> fatal: The remote end hung up unexpectedly

Looks like an intermittent connectivity issue?

2021-08-01 11:15 UTC, jyn514 commented
@bors retry

2021-08-01 14:16 UTC, merged