2229: Discr should be read when PatKind is Range
rust-lang/rust pull request #87554
Opened 2021-07-28 14:56 UTC by roxelo

This PR fixes an issue related to pattern matching in closures when Edition 2021 is enabled.

- If any of the patterns the discr is being matched on is `PatKind::Range` then the discr should be read

r? @nikomatsakis

Closes https://github.com/rust-lang/rust/issues/87426

2021-07-28 14:58 UTC, nikomatsakis requested changes
looks good! one nit

2021-07-28 14:58 UTC, nikomatsakis commented on compiler/rustc_typeck/src/expr_use_visitor.rs
> +                            _ => {
Nit: can we remove `_` and replace these with the expanded set of names?

2021-07-28 15:19 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3183235231) [(plain)](https://github.com/rust-lang/rust/commit/4485cf0d8b4f3f8c1ea66708ff928f020d7a117b/checks/3183235231/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.channel         := nightly
configure: rust.debug-assertions := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
* 342 features
some tidy checks failed


command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/rust-tidy" "/checkout" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "/checkout/obj/build" "16"


Build completed unsuccessfully in 0:00:10
```

</details>

2021-07-28 15:44 UTC, nikomatsakis commented
@roxelo tidy is grumpy :(

2021-07-28 16:03 UTC, jackh726 commented
Test just needs a trailing newline

2021-07-29 16:37 UTC, lqd commented
@bors r=nikomatsakis

2021-07-30 12:05 UTC, merged