Add long explanation for E0726
rust-lang/rust pull request #87655
Opened 2021-07-31 10:28 UTC by codekidX

Hey, I think some refactoring of codebase has occurred so the guidance mentioned in  #61137 is not updated I think @GuillaumeGomez .

Please let me know if any other changes needs to be added to this PR.

2021-07-31 10:28 UTC, rust-highfive commented
Some changes occurred in diagnostic error codes

cc @GuillaumeGomez

2021-07-31 10:28 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @LeSeulArtichaut (or someone else) soon.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2021-07-31 10:32 UTC, GuillaumeGomez commented on compiler/rustc_error_codes/src/error_codes/E0726.md
> +```rust
``````suggestion
```compile_fail,E0725
``````

2021-07-31 10:32 UTC, GuillaumeGomez commented on compiler/rustc_error_codes/src/error_codes/E0726.md
> +Specify the lifetime of struct `Abc` or indicate the anonymous lifetime like `abc: Abc<'_>`.
The explanation is a bit lacking no? Maybe try to explain a bit more.

2021-07-31 10:33 UTC, GuillaumeGomez commented on compiler/rustc_error_codes/src/error_codes/E0726.md
> +Specify the lifetime of struct `Abc` or indicate the anonymous lifetime like `abc: Abc<'_>`.
Also, please add a working version of the code example from above.

2021-07-31 10:34 UTC, GuillaumeGomez requested changes
The explanation needs to be extending (lifetimes are far from an easy topic in rust) and you also need to add a working version of your previous failing code example.

2021-07-31 10:35 UTC, GuillaumeGomez commented on compiler/rustc_error_codes/src/error_codes.rs
>  E0729: include_str!("./error_codes/E0729.md"),
You need to remove E0725 from the list of error codes from below (it's not supposed to be declared twice in this file).

2021-07-31 10:38 UTC, Urgau commented on compiler/rustc_error_codes/src/error_codes.rs
> +E0725: include_str!("./error_codes/E0726.md"),
It's also *726* and not *725*.
```suggestion
E0726: include_str!("./error_codes/E0726.md"),
```

2021-07-31 10:38 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3208601704) [(plain)](https://github.com/rust-lang/rust/commit/f1b752af4e6ee2265ce1be5db5c552be1be1b240/checks/3208601704/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.channel         := nightly
configure: rust.debug-assertions := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
    Finished release [optimized] target(s) in 8.31s
tidy check
tidy: Skipping binary file check, read-only filesystem
Checking which error codes lack tests...
tidy error: duplicate error code: 725
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes.rs:425: E0725: include_str!("./error_codes/E0725.md"),
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes.rs:426: E0725: include_str!("./error_codes/E0726.md"),
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:13: line longer than 80 chars
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:15: trailing whitespace
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:19: line longer than 80 chars
`/checkout/compiler/rustc_error_codes/src/error_codes/E0726.md` doesn't use its own error code in compile_fail example
Done!
* 345 features
some tidy checks failed



command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/rust-tidy" "/checkout" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "/checkout/obj/build" "16"


Build completed unsuccessfully in 0:00:10
```

</details>

2021-07-31 17:37 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3209972756) [(plain)](https://github.com/rust-lang/rust/commit/9c83e3772fe13851886274a151be6f1d7f404836/checks/3209972756/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.channel         := nightly
configure: rust.debug-assertions := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
    Finished release [optimized] target(s) in 10.76s
tidy check
tidy: Skipping binary file check, read-only filesystem
Checking which error codes lack tests...
tidy error: duplicate error code: 726
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes.rs:426: E0726: include_str!("./error_codes/E0726.md"),
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes.rs:641:     E0726, // non-explicit (not `'_`) elided lifetime in unsupported position
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:1: line longer than 80 chars
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:16: line longer than 80 chars
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:29: line longer than 80 chars
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:31: line longer than 80 chars
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:33: line longer than 80 chars
Found 0 error codes with no tests
Done!
* 345 features
some tidy checks failed
some tidy checks failed


command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/rust-tidy" "/checkout" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "/checkout/obj/build" "16"


Build completed unsuccessfully in 0:00:13
```

</details>

2021-07-31 18:02 UTC, codekidX commented
@GuillaumeGomez does `E0726` it not have a test case? if not, where should I add it?

2021-07-31 18:22 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3210102507) [(plain)](https://github.com/rust-lang/rust/commit/31c0d0ce6a0da8f0369a477c1c7f6ac314d8159f/checks/3210102507/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.channel         := nightly
configure: rust.debug-assertions := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
tidy: Skipping binary file check, read-only filesystem
Checking which error codes lack tests...
* 625 error codes
* highest error code: E0783
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:1: trailing whitespace
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:2: trailing whitespace
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:3: trailing whitespace
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:19: trailing whitespace
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:33: trailing whitespace
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:34: trailing whitespace
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:35: trailing whitespace
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:38: trailing whitespace
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:39: trailing whitespace
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md:42: trailing whitespace
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes/E0726.md: missing trailing newline
Found 0 error codes with no tests
Done!
* 345 features
some tidy checks failed
some tidy checks failed


command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/rust-tidy" "/checkout" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "/checkout/obj/build" "16"


Build completed unsuccessfully in 0:00:12
```

</details>

2021-07-31 18:39 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-10`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3210151923) [(plain)](https://github.com/rust-lang/rust/commit/6c8820026f50b949084f0eef078e694f0e2035b4/checks/3210151923/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

error: 1 errors occurred comparing output.
Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/async-await/async-fn-path-elision.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-fn-path-elision" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--edition=2018" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/async-await/async-fn-path-elision/auxiliary"
------------------------------------------

------------------------------------------
stderr:
stderr:
------------------------------------------
error[E0726]: implicit elided lifetime not allowed here
   |
   |
LL | async fn error(lt: HasLifetime) { //~ ERROR implicit elided lifetime not allowed here
   |                    ^^^^^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
   |
   = note: assuming a `'static` lifetime...
error: aborting due to previous error

For more information about this error, try `rustc --explain E0726`.

---
To only update this specific test, also pass `--test-args impl-header-lifetime-elision/trait-elided.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/impl-header-lifetime-elision/trait-elided.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-header-lifetime-elision/trait-elided" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-header-lifetime-elision/trait-elided/auxiliary"
------------------------------------------

------------------------------------------
stderr:
stderr:
------------------------------------------
error[E0726]: implicit elided lifetime not allowed here
   |
   |
LL | impl MyTrait for u32 {
   |      ^^^^^^^- help: indicate the anonymous lifetime: `<'_>`
   |
   = note: assuming a `'static` lifetime...
error: aborting due to previous error

For more information about this error, try `rustc --explain E0726`.

---
To only update this specific test, also pass `--test-args impl-header-lifetime-elision/path-elided.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/impl-header-lifetime-elision/path-elided.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-header-lifetime-elision/path-elided" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-header-lifetime-elision/path-elided/auxiliary"
------------------------------------------

------------------------------------------
stderr:
stderr:
------------------------------------------
error[E0726]: implicit elided lifetime not allowed here
   |
   |
LL | impl MyTrait for Foo {
   |                  ^^^- help: indicate the anonymous lifetime: `<'_>`
   |
   = note: assuming a `'static` lifetime...
error: aborting due to previous error

For more information about this error, try `rustc --explain E0726`.

---
To only update this specific test, also pass `--test-args issues/issue-10412.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/issues/issue-10412.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-10412" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-10412/auxiliary"
------------------------------------------

------------------------------------------
stderr:
stderr:
------------------------------------------
error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:1:20
   |
LL | trait Serializable<'self, T> { //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:2:25
   |
   |
LL |     fn serialize(val : &'self T) -> Vec<u8>; //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:3:38
   |
   |
LL |     fn deserialize(repr : &[u8]) -> &'self T; //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:6:6
   |
   |
LL | impl<'self> Serializable<str> for &'self str { //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:6:36
   |
   |
LL | impl<'self> Serializable<str> for &'self str { //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:10:25
   |
   |
LL |     fn serialize(val : &'self str) -> Vec<u8> { //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:13:37
   |
   |
LL |     fn deserialize(repr: &[u8]) -> &'self str { //~ ERROR lifetimes cannot use keyword names


error[E0726]: implicit elided lifetime not allowed here
   |
   |
LL | impl<'self> Serializable<str> for &'self str { //~ ERROR lifetimes cannot use keyword names
   |             ^^^^^^^^^^^^^^^^^ help: indicate the anonymous lifetime: `Serializable<'_, str>`
   |
   = note: assuming a `'static` lifetime...
error[E0277]: the size for values of type `str` cannot be known at compilation time
  --> /checkout/src/test/ui/issues/issue-10412.rs:6:13
   |
   |
LL | trait Serializable<'self, T> { //~ ERROR lifetimes cannot use keyword names
   |                           - required by this bound in `Serializable`
...
LL | impl<'self> Serializable<str> for &'self str { //~ ERROR lifetimes cannot use keyword names
   |
   = help: the trait `Sized` is not implemented for `str`
   = help: the trait `Sized` is not implemented for `str`
help: consider relaxing the implicit `Sized` restriction
   |
LL | trait Serializable<'self, T: ?Sized> { //~ ERROR lifetimes cannot use keyword names

error: aborting due to 9 previous errors

Some errors have detailed explanations: E0277, E0726.
---

The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unk [...]

2021-08-05 04:15 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-10`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3248483968) [(plain)](https://github.com/rust-lang/rust/commit/5d4a8db2040ba7359921ef29b4f3cee32f687196/checks/3248483968/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
To only update this specific test, also pass `--test-args issues/issue-10412.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/issues/issue-10412.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-10412" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-10412/auxiliary"
------------------------------------------

------------------------------------------
stderr:
stderr:
------------------------------------------
error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:1:20
   |
LL | trait Serializable<'self, T> { //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:2:25
   |
   |
LL |     fn serialize(val : &'self T) -> Vec<u8>; //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:3:38
   |
   |
LL |     fn deserialize(repr : &[u8]) -> &'self T; //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:6:6
   |
   |
LL | impl<'self> Serializable<str> for &'self str { //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:6:36
   |
   |
LL | impl<'self> Serializable<str> for &'self str { //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:10:25
   |
   |
LL |     fn serialize(val : &'self str) -> Vec<u8> { //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:13:37
   |
   |
LL |     fn deserialize(repr: &[u8]) -> &'self str { //~ ERROR lifetimes cannot use keyword names


error[E0726]: implicit elided lifetime not allowed here
   |
   |
LL | impl<'self> Serializable<str> for &'self str { //~ ERROR lifetimes cannot use keyword names
   |             ^^^^^^^^^^^^^^^^^ help: indicate the anonymous lifetime: `Serializable<'_, str>`
   |
   = note: assuming a `'static` lifetime...
error[E0277]: the size for values of type `str` cannot be known at compilation time
  --> /checkout/src/test/ui/issues/issue-10412.rs:6:13
   |
   |
LL | trait Serializable<'self, T> { //~ ERROR lifetimes cannot use keyword names
   |                           - required by this bound in `Serializable`
...
LL | impl<'self> Serializable<str> for &'self str { //~ ERROR lifetimes cannot use keyword names
   |
   = help: the trait `Sized` is not implemented for `str`
   = help: the trait `Sized` is not implemented for `str`
help: consider relaxing the implicit `Sized` restriction
   |
LL | trait Serializable<'self, T: ?Sized> { //~ ERROR lifetimes cannot use keyword names

error: aborting due to 9 previous errors

Some errors have detailed explanations: E0277, E0726.
---
test result: FAILED. 12009 passed; 1 failed; 103 ignored; 0 measured; 0 filtered out; finished in 126.12s



command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--suite" "ui" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-10/bin/FileCheck" "--nodejs" "/usr/bin/node" "--host-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python3" "--lldb-python" "/usr/bin/python3" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "10.0.0" "--llvm-components" "aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets amdgpu amdgpuasmparser amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgpuutils analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter bpf bpfasmparser bpfcodegen bpfdesc bpfdisassembler bpfinfo cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker engine executionengine frontendopenmp fuzzmutate globalisel hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interpreter ipo irreader jitlink lanai lanaiasmparser lanaicodegen lanaidesc lanaidisassembler lanaiinfo libdriver lineeditor linker lto mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcerror orcjit passes perfjitevents powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo riscvutils runtimedyld scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target textapi transformutils vectorize webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info x86utils xcore xcorecodegen xcoredesc xcoredisassembler xcoreinfo xray" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--channel" "nightly" "--color" "always"


Build completed unsuccessfully in 0:12:54
```

</details>

2021-08-05 04:22 UTC, codekidX commented
hey @GuillaumeGomez, I have added detailed explanation, please take a look.

Also the test is failing as
```
Some errors have detailed explanations: E0277, E0726.
For more information about an error, try `rustc --explain E0277`.
```

it should be 
```
Some errors have detailed explanations: E0726.
```
right?

Since its itself `E0277`. Do let me know if this is an issue or I need to add E0277 above as well.

2021-08-05 08:46 UTC, GuillaumeGomez commented on compiler/rustc_error_codes/src/error_codes/E0726.md
> +When a struct or a type is bound/declared with a lifetime it is important for
Please write a short summary of the error here, the explanation goes below. :)

Something like "An argument's lifetime was elided in an async function".

2021-08-05 08:49 UTC, GuillaumeGomez commented
> @GuillaumeGomez does `E0726` it not have a test case? if not, where should I add it?

In `src/test/ui/error_codes/` (there are a few others in this folder too so you can check how it works).

For the failing ui test, simply run it with `--bless` and let the tester do its job. ;)

2021-08-05 08:50 UTC, GuillaumeGomez commented on compiler/rustc_error_codes/src/error_codes/E0726.md
> +    pub async fn create(content: Content) { // error: implicit elided
Why do you need a method btw? Shouldn't an async function be enough?

2021-08-05 08:50 UTC, GuillaumeGomez commented on compiler/rustc_error_codes/src/error_codes/E0726.md
> +fn main() {
No need to declare a `main` function, please remove it (but keep its content!).

2021-08-05 08:51 UTC, GuillaumeGomez commented on compiler/rustc_error_codes/src/error_codes/E0726.md
> +Know more about lifetime elision in this
Please add a working version of your example above.

2021-09-06 08:15 UTC, JohnCSimon commented
Ping from triage: 
@codekidX can you please address the merge conflicts and build failures. Thank you.

2021-09-27 05:42 UTC, JohnCSimon commented
Ping again from triage:
@codekidX can you please address the merge conflicts and build failures. Thank you.

2021-09-27 06:01 UTC, codekidX commented
@JohnCSimon I'll rebase and resolve comments by today. Had some busy weeks, thanks for waiting.

2021-09-28 04:17 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3728159692) [(plain)](https://github.com/rust-lang/rust/commit/bfdaf67541a45c2a324961437b2cd361a465f8b9/checks/3728159692/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.channel         := nightly
configure: rust.debug-assertions := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
    Finished release [optimized] target(s) in 10.19s
tidy check
tidy: Skipping binary file check, read-only filesystem
Checking which error codes lack tests...
tidy error: duplicate error code: 726
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes.rs:427: E0726: include_str!("./error_codes/E0726.md"),
tidy error: /checkout/compiler/rustc_error_codes/src/error_codes.rs:643:     E0726, // non-explicit (not `'_`) elided lifetime in unsupported position
Found 0 error codes with no tests
Done!
* 351 features
some tidy checks failed
some tidy checks failed


command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/rust-tidy" "/checkout" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "/checkout/obj/build" "16"


Build completed unsuccessfully in 0:00:12
```

</details>

2021-09-28 05:00 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-10`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3728375476) [(plain)](https://github.com/rust-lang/rust/commit/6fe2ef5669333edfd3727db9215b3384e2ab9209/checks/3728375476/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
To only update this specific test, also pass `--test-args issues/issue-10412.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/issues/issue-10412.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-10412" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-10412/auxiliary"
------------------------------------------

------------------------------------------
stderr:
stderr:
------------------------------------------
error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:1:20
   |
LL | trait Serializable<'self, T> { //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:2:25
   |
   |
LL |     fn serialize(val : &'self T) -> Vec<u8>; //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:3:38
   |
   |
LL |     fn deserialize(repr : &[u8]) -> &'self T; //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:6:6
   |
   |
LL | impl<'self> Serializable<str> for &'self str { //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:6:36
   |
   |
LL | impl<'self> Serializable<str> for &'self str { //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:10:25
   |
   |
LL |     fn serialize(val : &'self str) -> Vec<u8> { //~ ERROR lifetimes cannot use keyword names

error: lifetimes cannot use keyword names
  --> /checkout/src/test/ui/issues/issue-10412.rs:13:37
   |
   |
LL |     fn deserialize(repr: &[u8]) -> &'self str { //~ ERROR lifetimes cannot use keyword names


error[E0726]: implicit elided lifetime not allowed here
   |
   |
LL | impl<'self> Serializable<str> for &'self str { //~ ERROR lifetimes cannot use keyword names
   |             ^^^^^^^^^^^^^^^^^ help: indicate the anonymous lifetime: `Serializable<'_, str>`
   |
   = note: assuming a `'static` lifetime...
error[E0277]: the size for values of type `str` cannot be known at compilation time
  --> /checkout/src/test/ui/issues/issue-10412.rs:6:13
   |
   |
LL | impl<'self> Serializable<str> for &'self str { //~ ERROR lifetimes cannot use keyword names
   |
   = help: the trait `Sized` is not implemented for `str`
note: required by a bound in `Serializable`
  --> /checkout/src/test/ui/issues/issue-10412.rs:1:27
  --> /checkout/src/test/ui/issues/issue-10412.rs:1:27
   |
LL | trait Serializable<'self, T> { //~ ERROR lifetimes cannot use keyword names
   |                           ^ required by this bound in `Serializable`
help: consider relaxing the implicit `Sized` restriction
   |
LL | trait Serializable<'self, T: ?Sized> { //~ ERROR lifetimes cannot use keyword names

error: aborting due to 9 previous errors

Some errors have detailed explanations: E0277, E0726.
---
test result: FAILED. 12098 passed; 1 failed; 115 ignored; 0 measured; 0 filtered out; finished in 127.22s



command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--suite" "ui" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-10/bin/FileCheck" "--nodejs" "/usr/bin/node" "--host-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python3" "--lldb-python" "/usr/bin/python3" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "10.0.0" "--llvm-components" "aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets amdgpu amdgpuasmparser amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgpuutils analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter bpf bpfasmparser bpfcodegen bpfdesc bpfdisassembler bpfinfo cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker engine executionengine frontendopenmp fuzzmutate globalisel hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interpreter ipo irreader jitlink lanai lanaiasmparser lanaicodegen lanaidesc lanaidisassembler lanaiinfo libdriver lineeditor linker lto mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcerror orcjit passes perfjitevents powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo riscvutils runtimedyld scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target textapi transformutils vectorize webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info x86utils xcore xcorecodegen xcoredesc xcoredisassembler xcoreinfo xray" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--channel" "nightly" "--color" "always"


Build completed unsuccessfully in 0:12:58
```

</details>

2021-11-18 14:58 UTC, jyn514 commented
Hi @apiraino, why did you add T-rustdoc here? This is a compiler error, rustdoc doesn't introduce any error codes that I know of.

2021-11-18 17:38 UTC, apiraino commented
> why did you add T-rustdoc here? This is a compiler error, rustdoc doesn't introduce any error codes that I know of.

@jyn514 I sweep the repository and assign the relevant `T-*` labels. Here I have assigned the wrong one.

I probably didn't have clear the context and having seen a review from Guillaume tricked me into assuming that t-rustdoc had a say on this. Sorry, I hope that didn't cause any issues!

2021-11-18 17:58 UTC, jyn514 commented
@apiraino no worries, I changed it to the right label :)

2021-11-24 15:32 UTC, jyn514 commented
Hi @codekidX, do you know how to fix the CI error? I think you just need to pass `--bless` to the tests :) feel free to ask me here or [on Zulip](https://rust-lang.zulipchat.com/#narrow/pm-with/232545-user232545) if you're having trouble!

2021-12-14 11:21 UTC, ThrashAbaddon commented
bump!

2022-02-27 19:09 UTC, JohnCSimon commented
@codekidX 
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. Thanks for your contribution.

@rustbot label: +S-inactive

2022-02-27 19:09 UTC, closed without merging