Rustdoc accessibility: use an icon for the [-]/[+] controls
rust-lang/rust pull request #87663
Opened 2021-07-31 14:25 UTC by GuillaumeGomez

This is a reopening of #87207 with improvement for the way of generating the `background-image` CSS property.

I quote from the original PR:

> This way, we can show the plus and minus buttons on screens, while voice
> control will read off actual words "Collapse" and "Expand" instead of reading
> "open brace minus close brace" and "open brace plus close brace".

Part of #87059

r? @notriddle

2021-07-31 16:09 UTC, notriddle approved these changes

2021-07-31 16:26 UTC, notriddle requested changes
Wait, actually, there's one thing that I'd like to try, but I'd like a few other people to check this out on their configuration, to see if they also prefer it this way.

The thing that I don't like about the current version of this is that it makes the icons look blurrier on hidpi screens. I'm not quite sure how to fix that, but I think adding these CSS rules might help:

```css
 image-rendering: crisp-edges;
 image-rendering: -moz-crisp-edges; /* Firefox before version 65 */
 image-rendering: -webkit-optimize-contrast; /* Safari, Chrome, Chromium Edge */
 -ms-interpolation-mode: nearest-neighbor; /* EdgeHTML Edge and Trident */
```

2021-07-31 17:02 UTC, notriddle commented
![image](https://user-images.githubusercontent.com/1593513/127747131-0dde4fd8-9bd7-425e-8ad9-e3e2ac11287c.png)

Here's a screenshot, and a web upload showing it, so that we can test this on as many browsers as we can get. Because the [caniuse site has quite a few caveats with getting good pixel art scaling in browsers](https://www.caniuse.com/css-crisp-edges).

https://notriddle.com/notriddle-rustdoc-test/pixelated-plus-minus/std/index.html

2021-07-31 17:51 UTC, Urgau commented
@notriddle Maybe with them in SVG it will help.

**Toggle minus**:
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" stroke="#000" fill="none"><path d="M4.5 2H2v12h2.5m7-12H14v12h-2.5"/><path d="M4.5 8h7"/></svg>
```

**Toggle plus:**
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" stroke="#000" fill="none"><path d="M4.5 2H2v12h2.5m7-12H14v12h-2.5"/><path d="M4.5 8h7"/><path d="M8 11.5V8.125h0V4.5"/></svg>
```

2021-08-02 08:55 UTC, GuillaumeGomez commented
@Urgau: Let's try svg! Thanks for the conversion. ;)

2021-08-02 21:24 UTC, GuillaumeGomez commented
The SVG you provided is all blurry  on my computer, it gets better when I zoom in, but it's not great... I've read around that using number without decimal makes it better, maybe it's worth a try? I tried to "fix" the SVG but it was a complete failure. ^^'

2021-08-02 22:49 UTC, Urgau commented
> The SVG you provided is all blurry on my computer, it gets better when I zoom in, but it's not great... I've read around that using number without decimal makes it better, maybe it's worth a try? I tried to "fix" the SVG but it was a complete failure. ^^'

My SVGs have a size of 16x16 like the original PNG files, this size is very small and when a software tries to display an image with such a tiny size, it renders it in this original size and then adapts it to the target size (which is much bigger) but some software "forget" that an SVG can be rendered at any size (which avoids any scaling and is the reason for SVGs) and so they render it and adapt it instead of rendering it at the target size, that's why it can appear blurry on your computer.

You can see on this [jsfiddle](https://jsfiddle.net/81Ls4be2/1/) my SVGs in their original sizes but also in 350x350, their is no blur.

*I never heard that number without decimal makes svg better, but I'm not an expert either.*

2021-08-02 23:11 UTC, notriddle commented
> The SVG you provided is all blurry on my computer, it gets better when I zoom in, but it's not great...

If it gets better when you zoom in, then it's not being caused by the browser rendering it at the original size and scaling. It's caused by the lines not being placed exactly on pixel boundaries.

This is why the original PNG files are not 16x16. They're 17x17. By using an odd number of pixels, you can draw a 1px line in the exact center of the image without aliasing.

2021-08-03 08:13 UTC, GuillaumeGomez commented
@Urgau I meant what @notriddle said: the pixel boundaries are not integers but decimals, which is what I think is the issue.

2021-08-03 11:01 UTC, Urgau commented
> This is why the original PNG files are not 16x16. They're 17x17. By using an odd number of pixels, you can draw a 1px line in the exact center of the image without aliasing.

Heu... I don't know what happen, I'm pretty sure I have enter 17x17 for the size; I don't know what to say, I should have checked, sorry.

> @Urgau I meant what @notriddle said: the pixel boundaries are not integers but decimals, which is what I think is the issue.

If that the case I don't know how to resolve that because Inkscape is generating this decimal values.

---

In any case I have redone and attached the SVGs with their correct size 17x17 (I checked this time). Let me know if it's still not good, maybe I can try something else.

**Toggle minus (17x17)**

```svg
<svg width="17" height="17" stroke="#000" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M5 2.5H2.5v12H5m7-12h2.5v12H12M5 8.5h7"/></svg>
```

**Toggle plus (17x17)**

```svg
<svg width="17" height="17" stroke="#000" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M5 2.5H2.5v12H5m7-12h2.5v12H12M5 8.5h7M8.5 12V8.625v0V5"/></svg>
```

*PS: By redoing them I even manage to shrink them down a little more*

2021-08-03 12:33 UTC, GuillaumeGomez commented
Ah nice, thanks! Let's try with these new images then.

2021-08-03 12:47 UTC, GuillaumeGomez commented
@Urgau Not blurry anymore, thanks a lot!

@notriddle I think the PR is ready. :)

2021-08-03 13:29 UTC, notriddle commented
Can you please publish a built copy of the standard library docs, like I’ve been doing? That way, we can all easily test the results.

2021-08-03 13:36 UTC, GuillaumeGomez commented
Sure, here you go: https://guillaume-gomez.fr/rustdoc-test/foo/struct.Foo.html (not std, simply a small crate).

2021-08-03 16:48 UTC, notriddle commented on src/librustdoc/html/static/images/toggle-minus.svg
> +<svg width="17" height="17" stroke="#000" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M5 2.5H2.5v12H5m7-12h2.5v12H12M5 8.5h7"/></svg>
```suggestion
<svg width="17" height="17" shape-rendering="crispEdges" stroke="#000" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M5 2.5H2.5v12H5m7-12h2.5v12H12M5 8.5h7"/></svg>
```

2021-08-03 16:49 UTC, notriddle requested changes
Add the attribute [`shape-rendering="crispEdges"`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering) to each of the `<svg>` elements, and then I'll approve it.

Here's a side-by-side comparison of the SVG, on the left is without crispEdges, and the right is with crispEdges. Both are zoomed in at 133%, so that the line would need to be aliased, and magnified with no interpolation after taking a screenshot.

![image](https://user-images.githubusercontent.com/1593513/128054536-f7c9ae6a-dbce-4a0c-8fc5-cf53ac366989.png)

2021-08-03 16:49 UTC, notriddle commented on src/librustdoc/html/static/images/toggle-minus.svg
> +<svg width="17" height="17" stroke="#000" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M5 2.5H2.5v12H5m7-12h2.5v12H12M5 8.5h7"/></svg>
```suggestion
<svg width="17" height="17" stroke="#000" fill="none" shape-rendering="crispEdges" xmlns="http://www.w3.org/2000/svg"><path d="M5 2.5H2.5v12H5m7-12h2.5v12H12M5 8.5h7"/></svg>
```

2021-08-03 16:49 UTC, notriddle commented on src/librustdoc/html/static/images/toggle-plus.svg
> +<svg width="17" height="17" stroke="#000" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M5 2.5H2.5v12H5m7-12h2.5v12H12M5 8.5h7M8.5 12V8.625v0V5"/></svg>
```suggestion
<svg width="17" height="17" stroke="#000" fill="none" shape-rendering="crispEdges" xmlns="http://www.w3.org/2000/svg"><path d="M5 2.5H2.5v12H5m7-12h2.5v12H12M5 8.5h7M8.5 12V8.625v0V5"/></svg>
```

2021-08-03 18:03 UTC, GuillaumeGomez commented
That looks better, indeed! Thanks to both of you for the help!

@bors: r=notriddle

2021-08-03 18:13 UTC, notriddle approved these changes

2021-08-04 02:03 UTC, merged