Clarify terms in rustdoc book
rust-lang/rust pull request #87865
Opened 2021-08-08 14:24 UTC by tsoutsman

Fixes #70898

I chose to completely remove the term directive over attribute because rustdoc has a lint called `invalid_codeblock_attributes` and the term attributes is used throughout the book. I slightly changed the introductory sentence to describe the relationship between annotations and attributes.

I also moved the text explaining the example from below the blocks to above the blocks which is more in line with the rest of the book. I also changed the description for the `should_panic` attribute as I found it a little confusing. Finally, some of the blocks were `text` and some were `rust` so I changed them all to `text` which is in line with the rest of the book.

2021-08-08 14:24 UTC, rust-highfive commented
r? @GuillaumeGomez

(rust-highfive has picked a reviewer for you, use r? to override)

2021-08-08 18:52 UTC, GuillaumeGomez commented on src/doc/rustdoc/src/documentation-tests.md
> +```text
It's definitely rust code. Please keep it as is. :)

2021-08-08 18:52 UTC, GuillaumeGomez commented on src/doc/rustdoc/src/documentation-tests.md
> +```text
It's definitely rust code. Please keep it as is. :)

2021-08-08 18:53 UTC, GuillaumeGomez requested changes
Looks good. Please keep the current annotations as is please (you change the other `text` ones into rust if you want but then don't forget to add an item like we did for the others (`# fn foo() {}`).

2021-08-08 22:52 UTC, tsoutsman commented
Done

2021-08-09 08:49 UTC, GuillaumeGomez approved these changes

2021-08-09 08:49 UTC, GuillaumeGomez commented
Thanks!

@bors: r+ rollup

2021-08-11 01:36 UTC, merged