Fix Windows Command::env("PATH")
rust-lang/rust pull request #87863
Opened 2021-08-08 13:27 UTC by ChrisDenton

Fixes #87859

2021-08-08 13:28 UTC, rust-highfive commented
r? @dtolnay

(rust-highfive has picked a reviewer for you, use r? to override)

2021-08-08 13:48 UTC, Urgau commented
I think this need's to be beta nominated because the [PR](https://github.com/rust-lang/rust/pull/85270) who introduce the bug is the the current beta.

2021-08-08 14:13 UTC, dtolnay requested changes
The `impl Borrow<OsStr> for EnvKey` lower in this file needs to be removed. That impl was the root cause. The impl is wrong because the Ord and Eq impls have different behavior between OsStr and EnvKey, which violates:

> In particular `Eq`, `Ord` and `Hash` must be equivalent for borrowed and owned values: `x.borrow() == y.borrow()` should give the same result as `x == y`.

2021-08-08 15:09 UTC, ChrisDenton commented
Ok I've removed the borrow and changed `sys_common::process::CommandEnv` to work with `EnvKey` instead of `OsStr`/`OsString`. I wonder if it might ultimately be worth Windows using its own implementation of `CommandEnv`.

2021-08-08 15:23 UTC, dtolnay approved these changes

2021-08-08 15:24 UTC, dtolnay commented
@bors r+

2021-08-09 08:19 UTC, rust-log-analyzer commented
A job failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/runs/3278287944) [(plain)](https://github.com/rust-lang-ci/rust/commit/03e3dd097a4919dea6607213cffdbf33e65c0121/checks/3278287944/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

```

</details>

2021-08-09 12:49 UTC, ChrisDenton commented
The failure looks like a spurious timeout or something?

2021-08-09 16:48 UTC, dtolnay commented
@bors retry

2021-08-09 17:44 UTC, rust-log-analyzer commented
A job failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/runs/3282792737) [(plain)](https://github.com/rust-lang-ci/rust/commit/32994af1891b398c863fe81080d08df924e0a069/checks/3282792737/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

```

</details>

2021-08-10 12:12 UTC, ChrisDenton commented
Hm, this seems to have failed downloading. Third time lucky?

2021-08-10 13:57 UTC, ehuss commented
@bors retry

Failed to download action 'https://api.github.com/repos/actions/checkout/tarball/5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f'. Error: The operation was canceled.

2021-08-11 15:59 UTC, ChrisDenton commented
Yeah, remove needs either an EnvKey or else a Borrow that has the same ordering as EnvKey. I could limit the allocation to right before `self.vars.remove`? That would fix the immediate problem and shouldn't have too much impact.

2021-08-11 16:18 UTC, ChrisDenton commented on library/std/src/sys/windows/process.rs
> +}
Good points. I could remove those implementations and maybe I should add a `#[cfg(not(windows))]` to `have_changed_path`? So as to guard against the possibility of it accidentally being used in the future, or at least until a longer term fix is made.

2021-08-12 16:17 UTC, merged