Stabilize try_reserve
rust-lang/rust pull request #87993
Opened 2021-08-12 23:31 UTC by kornelski

Stabilization PR for the [`try_reserve` feature](https://github.com/rust-lang/rust/issues/48043#issuecomment-898040475).

2021-08-12 23:31 UTC, rust-highfive commented
r? @Mark-Simulacrum

(rust-highfive has picked a reviewer for you, use r? to override)

2021-08-12 23:35 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3317214888) [(plain)](https://github.com/rust-lang/rust/commit/414410e39fe918e867171b8646bb0b29677ae6dd/checks/3317214888/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking rustc_ast v0.0.0 (/checkout/compiler/rustc_ast)
    Checking rustc_target v0.0.0 (/checkout/compiler/rustc_target)
    Checking rustc_feature v0.0.0 (/checkout/compiler/rustc_feature)
    Checking rustc_parse_format v0.0.0 (/checkout/compiler/rustc_parse_format)
error[E0425]: cannot find value `try_reserve` in module `sym`
   --> compiler/rustc_feature/src/accepted.rs:298:16
    |
298 |     (accepted, try_reserve, "1.56.0", Some(48043), None),
    |                ^^^^^^^^^^^ not found in `sym`
For more information about this error, try `rustc --explain E0425`.
error: could not compile `rustc_feature` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

</details>

2021-08-13 10:30 UTC, TimDiekmann commented
cc @rust-lang/wg-allocators

2021-08-19 16:30 UTC, Mark-Simulacrum commented
r? @joshtriplett perhaps, not sure what current T-libs FCP practice is. I don't think I see a completed one though.

2021-08-20 00:38 UTC, joshtriplett commented
FCP for stabilization:
@rfcbot merge

2021-08-21 21:34 UTC, dtolnay commented
@rfcbot concern need `From<LayoutError> for TryReserveError`? https://github.com/rust-lang/rust/issues/48043#issuecomment-903179033

2021-08-21 23:38 UTC, joshtriplett commented
@dtolnay Thanks for catching that. I don't think we need that `From` instance.

2021-08-23 15:06 UTC, m-ou-se commented on compiler/rustc_feature/src/accepted.rs
> +    (accepted, try_reserve, "1.56.0", Some(48043), None),
This file is only for language features.
```suggestion
```

2021-08-29 22:27 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-10`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3456648824) [(plain)](https://github.com/rust-lang/rust/commit/f734ed43af5532036ed8934ede43d6046ca38d4d/checks/3456648824/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling rustc-demangle v0.1.21
error[E0308]: mismatched types
   --> library/alloc/src/collections/mod.rs:125:9
    |
124 |     fn from(_: LayoutError) -> Self {
    |                                ---- expected `TryReserveError` because of return type
125 |         TryReserveErrorKind::CapacityOverflow
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `TryReserveError`, found enum `TryReserveErrorKind`
For more information about this error, try `rustc --explain E0308`.
error: could not compile `alloc` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

</details>

2021-08-29 23:41 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-10`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3456824403) [(plain)](https://github.com/rust-lang/rust/commit/60e9419f5eb01c6c79ec7b01316e77d23f980684/checks/3456824403/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
To only update this specific test, also pass `--test-args closures/issue-87814-2.rs`

error: 1 errors occurred comparing output.
status: exit status: 0
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/closures/issue-87814-2.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/closures/issue-87814-2" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/closures/issue-87814-2/auxiliary"
------------------------------------------

------------------------------------------
stderr:
---
test result: FAILED. 12098 passed; 1 failed; 102 ignored; 0 measured; 0 filtered out; finished in 127.41s



command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--suite" "ui" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-10/bin/FileCheck" "--nodejs" "/usr/bin/node" "--host-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python3" "--lldb-python" "/usr/bin/python3" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "10.0.0" "--llvm-components" "aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets amdgpu amdgpuasmparser amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgpuutils analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter bpf bpfasmparser bpfcodegen bpfdesc bpfdisassembler bpfinfo cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker engine executionengine frontendopenmp fuzzmutate globalisel hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interpreter ipo irreader jitlink lanai lanaiasmparser lanaicodegen lanaidesc lanaidisassembler lanaiinfo libdriver lineeditor linker lto mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcerror orcjit passes perfjitevents powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo riscvutils runtimedyld scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target textapi transformutils vectorize webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info x86utils xcore xcorecodegen xcoredesc xcoredisassembler xcoreinfo xray" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work" "--android-cross-path" "" "--channel" "nightly" "--color" "always"


Build completed unsuccessfully in 0:13:44
```

</details>

2021-09-10 18:33 UTC, paolobarbolini commented
I guess since 1.56 already branched the `since` version will have to be updated to 1.57.0

2021-10-03 12:20 UTC, Wodann requested changes

2021-10-03 12:20 UTC, Wodann commented on compiler/rustc_data_structures/src/sso/set.rs
> +//   try_reserve
```suggestion
```

2021-10-03 12:20 UTC, Wodann commented on compiler/rustc_data_structures/src/sso/set.rs
> +//   try_reserve
No longer missing this API

2021-10-03 12:20 UTC, Wodann commented on compiler/rustc_data_structures/src/sso/map.rs
> +//   try_reserve
```suggestion
```

2021-10-03 12:20 UTC, Wodann commented on compiler/rustc_data_structures/src/sso/map.rs
> +//   try_reserve
No longer missing this API

2021-10-04 02:35 UTC, joshtriplett commented
r=me with the conflict resolved.

2021-10-04 11:12 UTC, kornelski commented
I've also bumped it to 1.57, as I assume it's too late for 1.56 now.

2021-10-04 22:14 UTC, yaahc commented
@bors r=joshtriplett

2021-10-05 06:54 UTC, merged

2021-12-06 15:50 UTC, LeonineKing1199 commented
Why wasn't the actual error kind stabilized? There's no point to this feature without the ability to introspect.

2021-12-06 16:00 UTC, kornelski commented
@LeonineKing1199 You can see in the original RFC discussion that it wasn't certain if the error should be stabilized exactly as it is implemented currently, e.g. with separate cases that just mirror an inconsistency in std (where some allocation failures panic, and some abort).

I'm interested to hear what is your use-case and what data you'd like to get out of the error type, to help guide how the error type should be designed.

2021-12-06 23:11 UTC, LeonineKing1199 commented
Ha ha, looks like my case was already addressed:
> One I can think of is someone creating a custom data structure, and wanting to mimic std API. But that's not a very strong case.

It is for implementing the stdlib APIs without polluting it with polyfills that are incompatible with what's in the stdlib.

2021-12-07 01:14 UTC, kornelski commented
Great. So you're not looking to get any data out of it yourself, you just want to return a `TryReserveError` instance? If there was `TryReserveError::default()` or just a very basic `TryReserveError::new(allocation_size)`, would that work for you?

2021-12-07 09:31 UTC, Stargateur commented
> Why wasn't the actual error kind stabilized? There's no point to this feature without the ability to introspect.

In my opinion, the error is more for the end user, or very special case for something like kernel linux. For a server I will log the error and continue anyway so don't really care, even if I would consider a `CapacityOverflow` a code bug in a server or at least get a look at it.

@kornelski Do you think we could have const value `TryReserveError::CAPACITY_OVERFLOW` ? Unless if we want to be able to precise the maximum value at runtine and possibly the value used I don't expect this to change a lot.

2021-12-07 15:08 UTC, LeonineKing1199 commented
> Great. So you're not looking to get any data out of it yourself, you just want to return a `TryReserveError` instance? If there was `TryReserveError::default()` or just a very basic `TryReserveError::new(allocation_size)`, would that work for you?

Actually, this would work perfectly!