Avoid more invocations of hir_crate query.
rust-lang/rust pull request #88880
Opened 2021-09-12 10:08 UTC by cjgillot

`hir_crate` forces the recomputation of queries that depend on it.

This PR aims at avoiding useless invocations of `hir_crate` by making dependent code go through `tcx.hir()`.

2021-09-12 10:08 UTC, rust-highfive commented
Some changes occurred in src/tools/clippy.

cc @rust-lang/clippy

2021-09-12 10:08 UTC, rust-highfive commented
r? @wesleywiser

(rust-highfive has picked a reviewer for you, use r? to override)

2021-09-12 10:14 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3578997961) [(plain)](https://github.com/rust-lang/rust/commit/3adf1f36e396b9695770d6beb1eca5819da63e9d/checks/3578997961/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking clippy_lints v0.1.57 (/checkout/src/tools/clippy/clippy_lints)
error[E0425]: cannot find value `CRATE_DEF_ID` in this scope
   --> src/tools/clippy/clippy_lints/src/missing_doc.rs:107:66
    |
107 |         self.check_missing_docs_attrs(cx, attrs, cx.tcx.def_span(CRATE_DEF_ID), "the", "crate");
    |
help: consider importing one of these items
    |
8   | use rustc_hir::def_id::CRATE_DEF_ID;
```

</details>

2021-09-12 10:46 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-10`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3579028284) [(plain)](https://github.com/rust-lang/rust/commit/1469cd27fc49cc5e83f59e95f58953ce00c8b235/checks/3579028284/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
................................................i................................................... 8600/12127
.................................................................................................... 8700/12127
.................................................................................................... 8800/12127
.................................................................................................... 8900/12127
.................................F.F................................................................ 9000/12127
.......................ii...............i........................................................... 9200/12127
.................................................................................................... 9300/12127
.................................................................................................... 9400/12127
.................................................................................................... 9500/12127
---
23 
24 error: requires `sized` lang_item
25 
- error: aborting due to 3 previous errors
Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
+ error: requires `sized` lang_item
+ 
+ error: requires `sized` lang_item
+ 
+ error: requires `sized` lang_item
+ error: aborting due to 6 previous errors
27 
28 Some errors have detailed explanations: E0432, E0603.
29 For more information about an error, try `rustc --explain E0432`.
---
To only update this specific test, also pass `--test-args privacy/privacy2.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/privacy/privacy2.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/privacy/privacy2" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/privacy/privacy2/auxiliary"
------------------------------------------

------------------------------------------
stderr:
---

error[E0603]: function import `foo` is private
  --> /checkout/src/test/ui/privacy/privacy2.rs:23:20
   |
LL |     use bar::glob::foo;
   |                    ^^^ private function import
note: the function import `foo` is defined here...
  --> /checkout/src/test/ui/privacy/privacy2.rs:10:13
   |
LL |         use foo;
LL |         use foo;
   |             ^^^
note: ...and refers to the function `foo` which is defined here
   |
LL | pub fn foo() {}
   | ^^^^^^^^^^^^ consider importing it directly

---
6 
7 error: requires `sized` lang_item
8 
- error: aborting due to 2 previous errors
+ error: requires `sized` lang_item
+ 
+ error: requires `sized` lang_item
+ 
+ error: requires `sized` lang_item
+ error: aborting due to 5 previous errors
10 
11 For more information about this error, try `rustc --explain E0432`.
12 
---
To only update this specific test, also pass `--test-args privacy/privacy3.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/privacy/privacy3.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/privacy/privacy3" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/privacy/privacy3/auxiliary"
------------------------------------------

------------------------------------------
stderr:
stderr:
------------------------------------------
error[E0432]: unresolved import `bar::gpriv`
   |
   |
LL |     use bar::gpriv;
   |         ^^^^^^^^^^ no `gpriv` in `bar`
error: requires `sized` lang_item

error: requires `sized` lang_item

---
test result: FAILED. 12023 passed; 2 failed; 102 ignored; 0 measured; 0 filtered out; finished in 132.03s



command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--suite" "ui" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-10/bin/FileCheck" "--nodejs" "/usr/bin/node" "--host-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python3" "--lldb-python" "/usr/bin/python3" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "10.0.0" "--llvm-components" "aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets amdgpu amdgpuasmparser amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgpuutils analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter bpf bpfasmparser bpfcodegen bpfdesc bpfdisassembler bpfinfo cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker engine executionengine frontendopenmp fuzzmutate globalisel hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interpreter ipo irreader jitlink lanai lanaiasmparser lanaicodegen lanaidesc lanaidisassembler lanaiinfo libdriver lineeditor linker lto mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcerror orcjit passes perfjitevents powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo riscvutils runtimedyld scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target textapi transformutils vectorize webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info x86utils xcore xcorecodegen xcoredesc xcoredisassembler xcoreinfo xray" "--system-llvm" "--cc" "" "--cxx" "" "--cflags" "" "--adb-path" "adb" "--adb-test-dir" "/data/tmp/work"  [...]

2021-09-12 11:35 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-10`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3579221939) [(plain)](https://github.com/rust-lang/rust/commit/2067357c615db4c3df72eca28d54b3e8572255d2/checks/3579221939/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
failures:

---- [ui] ui-fulldeps/issue-15778-pass.rs stdout ----

error: auxiliary build of "/checkout/src/test/ui-fulldeps/auxiliary/lint-for-crate-rpass.rs" failed to compile: 
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui-fulldeps/auxiliary/lint-for-crate-rpass.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/issue-15778-pass/auxiliary" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--crate-type" "dylib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/issue-15778-pass/auxiliary"
------------------------------------------

------------------------------------------
stderr:
---
   |     ^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error[E0050]: method `check_crate` has 3 parameters but the declaration in trait `rustc_lint::LateLintPass::check_crate` has 2
  --> /checkout/src/test/ui-fulldeps/auxiliary/lint-for-crate-rpass.rs:30:28
   |
LL |               fn check_crate(&mut self, cx: &LateContext, krate: &rustc_hir::Crate) {
...
...
LL | / fake_lint_pass! {
LL | |     PassOkay,
LL | |     Symbol::intern("crate_okay")
LL | | }
   |
   |
   = note: `check_crate` from trait: `fn(&mut Self, &LateContext<'tcx>)`
   = note: this error originates in the macro `fake_lint_pass` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0050]: method `check_crate` has 3 parameters but the declaration in trait `rustc_lint::LateLintPass::check_crate` has 2
  --> /checkout/src/test/ui-fulldeps/auxiliary/lint-for-crate-rpass.rs:30:28
   |
LL |               fn check_crate(&mut self, cx: &LateContext, krate: &rustc_hir::Crate) {
...
...
LL | / fake_lint_pass! {
LL | |     PassRedBlue,
LL | |     Symbol::intern("crate_red"), Symbol::intern("crate_blue")
LL | | }
   |
   |
   = note: `check_crate` from trait: `fn(&mut Self, &LateContext<'tcx>)`
   = note: this error originates in the macro `fake_lint_pass` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0050]: method `check_crate` has 3 parameters but the declaration in trait `rustc_lint::LateLintPass::check_crate` has 2
  --> /checkout/src/test/ui-fulldeps/auxiliary/lint-for-crate-rpass.rs:30:28
   |
LL |               fn check_crate(&mut self, cx: &LateContext, krate: &rustc_hir::Crate) {
...
...
LL | / fake_lint_pass! {
LL | |     PassGreyGreen,
LL | |     Symbol::intern("crate_grey"), Symbol::intern("crate_green")
LL | | }
   |
   |
   = note: `check_crate` from trait: `fn(&mut Self, &LateContext<'tcx>)`
   = note: this error originates in the macro `fake_lint_pass` (in Nightly builds, run with -Z macro-backtrace for more info)
error: aborting due to 3 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0050`.


------------------------------------------


---- [ui] ui-fulldeps/issue-15778-fail.rs stdout ----

error: auxiliary build of "/checkout/src/test/ui-fulldeps/auxiliary/lint-for-crate.rs" failed to compile: 
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui-fulldeps/auxiliary/lint-for-crate.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/issue-15778-fail/auxiliary" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--crate-type" "dylib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/issue-15778-fail/auxiliary"
------------------------------------------

------------------------------------------
stderr:
---
   | ^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused imports: `LintArray`, `LintPass`
  --> /checkout/src/test/ui-fulldeps/auxiliary/lint-for-crate.rs:16:45
   |
LL | use rustc_lint::{LateContext, LateLintPass, LintArray, LintContext, LintPass};
   |                                             ^^^^^^^^^               ^^^^^^^^
warning: unused import: `rustc_ast::attr`
  --> /checkout/src/test/ui-fulldeps/auxiliary/lint-for-crate.rs:18:5
   |
LL | use rustc_ast::attr;
LL | use rustc_ast::attr;
   |     ^^^^^^^^^^^^^^^

error[E0050]: method `check_crate` has 3 parameters but the declaration in trait `rustc_lint::LateLintPass::check_crate` has 2
  --> /checkout/src/test/ui-fulldeps/auxiliary/lint-for-crate.rs:29:20
   |
LL |     fn check_crate(&mut self, cx: &LateContext, krate: &rustc_hir::Crate) {
   |
   |
   = note: `check_crate` from trait: `fn(&mut Self, &LateContext<'tcx>)`
error: aborting due to previous error; 3 warnings emitted

For more information about this error, try `rustc --explain E0050`.

---
test result: FAILED. 66 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 11.96s



command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/compiletest" "--compile-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib" "--run-lib-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "--rustc-path" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "--src-base" "/checkout/src/test/ui-fulldeps" "--build-base" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui-fulldeps" "--stage-id" "stage2-x86_64-unknown-linux-gnu" "--suite" "ui-fulldeps" "--mode" "ui" "--target" "x86_64-unknown-linux-gnu" "--host" "x86_64-unknown-linux-gnu" "--llvm-filecheck" "/usr/lib/llvm-10/bin/FileCheck" "--nodejs" "/usr/bin/node" "--host-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--target-rustcflags" "-Crpath -O -Cdebuginfo=0  -Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--docck-python" "/usr/bin/python3" "--lldb-python" "/usr/bin/python3" "--gdb" "/usr/bin/gdb" "--quiet" "--llvm-version" "10.0.0" "--llvm-components" "aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets amdgpu amdgpuasmparser amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgpuutils analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter bpf bpfasmparser bpfcodegen bpfdesc bpfdisassembler bpfinfo cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker engine executionengine frontendopenmp fuzzmutate globalisel hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interpreter ipo irreader jitlink lanai lanaiasmparser lanaicodegen lanaidesc lanaidisassembler lanaiinfo libdriver lineeditor linker lto mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcerror  [...]

2021-09-12 11:46 UTC, cjgillot commented
@bors try @rust-timer queue

2021-09-12 11:46 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

2021-09-12 13:06 UTC, rust-timer commented
Queued 61a27a20fa9db4b749e8bf81b59fc0bcb5d60587 with parent 0212c70b1df2aa542aef48d5fcde0af3734970c6, future [comparison URL](https://perf.rust-lang.org/compare.html?start=0212c70b1df2aa542aef48d5fcde0af3734970c6&end=61a27a20fa9db4b749e8bf81b59fc0bcb5d60587).

2021-09-12 14:45 UTC, rust-timer commented
Finished benchmarking commit (61a27a20fa9db4b749e8bf81b59fc0bcb5d60587): [comparison url](https://perf.rust-lang.org/compare.html?start=0212c70b1df2aa542aef48d5fcde0af3734970c6&end=61a27a20fa9db4b749e8bf81b59fc0bcb5d60587).

**Summary**: This benchmark run did not return any relevant changes.

If you disagree with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).

Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR led to changes in compiler perf. 

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf -perf-regression

2021-09-13 12:02 UTC, oli-obk requested changes
The title of the PR says that `hir_crate` query calls are avoided, but the PR code looks to me like it's "just" (in quotes, because it is a good) clean up and API simplification. Am I missing something or should the title get updated?

2021-09-13 12:02 UTC, oli-obk commented on compiler/rustc_hir/src/hir.rs
> +impl<'hir> Crate<'hir> {
mirroring the other impls in this crate, we can keep using implicit lifetime declaration

```suggestion
impl Crate<'hir> {
```

2021-09-13 18:49 UTC, cjgillot commented
My first aim was to remove calls to `tcx.hir().krate()` which are exactly calls to `tcx.hir_crate(())`. Hence the PR title. Cleaning-up the API to make this function harder to use is only a second-order goal.

2021-09-13 20:54 UTC, oli-obk commented
Right, I got that, but it looks to me like the same amount of calls are still happening, but they are now hidden behind new functions.

2021-10-01 01:15 UTC, wesleywiser commented on src/test/ui/privacy/privacy2.stderr
> +error: requires `sized` lang_item
I'm also curious about this.

2021-10-01 12:19 UTC, oli-obk commented
@bors r+

2021-10-01 15:20 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-aux`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/runs/3768531054) [(plain)](https://github.com/rust-lang-ci/rust/commit/cca895bdbd29df606af923faf3967edda3ee16ba/checks/3768531054/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

failures:

---- test_sort::prop_sort_no_headers stdout ----
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-546]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-560]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
error: test failed, to rerun pass '--test tests'
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-577]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-591]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-606]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-619]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-633]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-646]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-662]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-674]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-690]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-702]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-717]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-728]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-740]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-753]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-767]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-782]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-796]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-811]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-825]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-839]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-852]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-867]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-880]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-894]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-908]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-923]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-936]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-952]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-966]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-979]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-989]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-1004]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-1017]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-1032]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-1044]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-1059]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-1071]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-1085]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-1101]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-1116]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-1129]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-1143]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-1156]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-1171]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-1183]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-1196]: "/checkout/obj/build/ct/xsv/target/debug/xsv" "sort" "in.csv" "--no-headers"
[/checkout/obj/build/ct/xsv/target/debug/xit/prop_sort_no_headers/test-1210]: "/checkout/obj/build/ct/xsv/target/debug/xsv" " [...]

2021-10-01 16:04 UTC, oli-obk commented
@bors retry

2021-10-01 22:47 UTC, merged

2021-10-02 00:24 UTC, rust-timer commented
Finished benchmarking commit (c02371c442f811878ab3a0f5a813402b6dfd45d2): [comparison url](https://perf.rust-lang.org/compare.html?start=b6057bf7b7ee7c58e6a39ead02eaa13b75f908c2&end=c02371c442f811878ab3a0f5a813402b6dfd45d2).

**Summary**: This benchmark run did not return any relevant changes.

If you disagree with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).

 

@rustbot label: -perf-regression

2021-10-05 18:14 UTC, Mark-Simulacrum commented
Tagging as a perf regression. Our heuristics currently didn't flag this earlier, but it seems like many-assoc-items is indeed regressed by this PR.