Const Deref
rust-lang/rust pull request #88887
Opened 2021-09-12 15:34 UTC by fee1-dead

2021-09-12 15:34 UTC, rust-highfive commented
r? @kennytm

(rust-highfive has picked a reviewer for you, use r? to override)

2021-09-12 15:45 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3580094109) [(plain)](https://github.com/rust-lang/rust/commit/32edaa9b6a896a9a258983eddb1c092d3a1760b9/checks/3580094109/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.channel         := nightly
configure: rust.debug-assertions := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
skip untracked path src/doc/rust-by-example/ during rustfmt invocations
skip untracked path src/llvm-project/ during rustfmt invocations
Diff in /checkout/library/alloc/src/borrow.rs at line 331:
 
 #[stable(feature = "rust1", since = "1.0.0")]
 #[rustc_const_unstable(feature = "const_deref", issue = "none")]
-impl<B: ?Sized + ToOwned> const Deref for Cow<'_, B> where B::Owned: ~const Borrow<B> {
+impl<B: ?Sized + ToOwned> const Deref for Cow<'_, B>
+where
+    B::Owned: ~const Borrow<B>,
     type Target = B;
 
 
     fn deref(&self) -> &B {
Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt" "--config-path" "/checkout" "--edition" "2018" "--unstable-features" "--skip-children" "--check" "/checkout/library/alloc/src/lib.rs" "/checkout/library/alloc/src/prelude/mod.rs" "/checkout/library/alloc/src/sync.rs" "/checkout/library/alloc/src/slice.rs" "/checkout/library/alloc/src/borrow.rs" "/checkout/library/alloc/src/prelude/v1.rs" "/checkout/library/alloc/src/task.rs" "/checkout/library/alloc/src/rc/tests.rs"` failed.
If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
```

</details>

2021-09-13 08:12 UTC, kennytm commented
r? @oli-obk

2021-09-13 11:34 UTC, oli-obk requested changes
Please create a tracking issue or point to the const trait impls tracking issue.

Also include a short message in the main post explaining what this PR does.

I think this PR would also benefit from a test or two

2021-09-13 11:34 UTC, oli-obk commented on library/alloc/src/string.rs
> +impl const ops::Deref for String {
We should not make this (and `Vec`'s impl) `const`, out of the same reason we didn't make `len` `const fn`: there is no way to construct any interesting (non-empty) `String`s, so all these functions are useless. It was decided that, until we have some sort of const heap, we should not add any new const functions beyond constructors.

2021-09-13 11:34 UTC, oli-obk commented on library/core/src/panic/unwind_safe.rs
>  impl<T> Deref for AssertUnwindSafe<T> {
These are never constructed in const contexts, so with the same reasoning as for String/Vec, we should not add const methods or impls on them.

2021-09-15 06:17 UTC, oli-obk commented
@bors r+ rollup

2021-09-16 22:25 UTC, jhpratt commented
Does `#[rustc_const_unstable]` actually work on trait impls? Only asking because I know regular unstable attributes don't.

2021-09-17 06:39 UTC, oli-obk commented
> 
> 
> Does `#[rustc_const_unstable]` actually work on trait impls? Only asking because I know regular unstable attributes don't.

yes, and there are explicit tests for this

2021-09-17 09:44 UTC, merged