Add `is_absent` and `is_unicode_error` to VarError
rust-lang/rust pull request #89301
Opened 2021-09-27 15:23 UTC by ohsayan

Added the following functions to VarError:
- `is_absent`: Check if the error was caused by a missing env var
- `is_unicode_error`: Check if the error was caused by unicode parsing
failure

The addition of these methods generally simplifies some cases
where you'd just want to check if the variable is missing or if
an error has occurred while parsing it.

Signed-off-by: Sayan Nandan <nandansayan@outlook.com>

2021-09-27 15:23 UTC, rust-highfive commented
r? @joshtriplett

(rust-highfive has picked a reviewer for you, use r? to override)

2021-09-27 15:26 UTC, ohsayan commented
@rustbot label: +T-libs

2021-09-27 15:27 UTC, ohsayan commented
Opening the tracking issue now

2021-09-27 17:48 UTC, joshtriplett requested changes
I made a couple of naming suggestions for consistency with the names of the enum variants.

Separate from that, I'm going to nominate this issue for discussion, to address the general question of whether we want to offer APIs like this for enums that just trivially wrap `matches!`. I'm not sure if we need such methods or if we just want to suggest `matches!` or an `if let`.

2021-09-27 17:48 UTC, joshtriplett commented on library/std/src/env.rs
> +    pub const fn is_absent(&self) -> bool {
```suggestion
    pub const fn is_not_present(&self) -> bool {
```

2021-09-27 17:48 UTC, joshtriplett commented on library/std/src/env.rs
> +    pub const fn is_unicode_error(&self) -> bool {
```suggestion
    pub const fn is_not_unicode(&self) -> bool {
```

2021-09-29 18:52 UTC, yaahc commented
> The addition of these methods generally simplifies some cases
> where you'd just want to check if the variable is missing or if
> an error has occurred while parsing it.

Can you give an example of this? My expectation is that the difference would be rather slight. The brevity of the method impls themselves seems to support this.

2021-10-01 05:32 UTC, ohsayan commented on library/std/src/env.rs
> +    pub const fn is_absent(&self) -> bool {
Done

2021-10-01 05:32 UTC, ohsayan commented on library/std/src/env.rs
> +    pub const fn is_unicode_error(&self) -> bool {
Done

2021-10-01 12:06 UTC, ohsayan commented
> > The addition of these methods generally simplifies some cases
> > where you'd just want to check if the variable is missing or if
> > an error has occurred while parsing it.
> 
> Can you give an example of this? My expectation is that the difference would be rather slight. The brevity of the method impls themselves seems to support this.

I agree. It was just that I needed it in a place and I think it may be a far too niche addition.

2021-10-06 19:41 UTC, yaahc commented
> I agree. It was just that I needed it in a place and I think it may be a far too niche addition.

Sounds good, I'm going to go ahead and close this PR. Thank you again.

2021-10-06 19:41 UTC, closed without merging