for signed wrapping remainder, do not compare lhs with MIN
rust-lang/rust pull request #89351
Opened 2021-09-29 09:34 UTC by tspiteri

Since the wrapped remainder is going to be 0 for all cases when the rhs is -1, there is no need to compare the lhs with MIN.

2021-09-29 09:34 UTC, rust-highfive commented
r? @dtolnay

(rust-highfive has picked a reviewer for you, use r? to override)

2021-09-29 09:34 UTC, tspiteri commented
This results in slightly better code generation for [`wrapping_rem`](https://godbolt.org/z/qdbbP1xbP) and [`wrapping_rem_euclid`](https://godbolt.org/z/4Wre4415W).

2021-10-03 05:11 UTC, dtolnay requested changes
This leaves `overflowing_rem` still generating poor code though, right? The current implementation is:

```rust
if unlikely!(self == Self::MIN && rhs == -1) {
    (0, true)
} else {
    (self % rhs, false)
}
```

If I've correctly understood the optimization in this PR, it seems like we could change that to:

```rust
if unlikely!(rhs == -1) {
    (0, self == Self::MIN)
} else {
    (self % rhs, false)
}
```

after which changing `wrapping_rem` would probably no longer be necessary (but check godbolt).

2021-10-05 13:14 UTC, tspiteri commented
Yes, after that suggestion, my original change is [no longer necessary](https://godbolt.org/z/q91adfa6d) (and [similarly for `rem_euclid`](https://godbolt.org/z/Edxxs5c4d)).

2021-10-05 16:04 UTC, dtolnay approved these changes

2021-10-05 16:04 UTC, dtolnay commented
@bors r+ rollup

2021-10-06 01:32 UTC, merged