Add vectored positioned I/O on Unix
rust-lang/rust pull request #89518
Opened 2021-10-04 11:28 UTC by a1phyr

Add methods for vectored I/O with an offset on `File` for `unix` under `#![feature(unix_file_vectored_at)]`.

The new methods are wrappers around `preadv` and `pwritev`.

Tracking issue: #89517

2021-10-04 11:28 UTC, rust-highfive commented
r? @Mark-Simulacrum

(rust-highfive has picked a reviewer for you, use r? to override)

2021-10-04 12:04 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-10`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3790182762) [(plain)](https://github.com/rust-lang/rust/commit/a1061d72105febfd43ac7f733100c8c60e6d3da5/checks/3790182762/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    |
137 |                 offset as i64,
    |                 ^^^^^^^^^^^^^ expected `i32`, found `i64`
    |
help: you can convert an `i64` to an `i32` and panic if the converted value doesn't fit
    |
137 |                 (offset as i64).try_into().unwrap(),
    |                 +             +++++++++++++++++++++
error[E0308]: mismatched types
   --> library/std/src/sys/unix/fd.rs:217:17
    |
217 |                 offset as i64,
217 |                 offset as i64,
    |                 ^^^^^^^^^^^^^ expected `i32`, found `i64`
    |
help: you can convert an `i64` to an `i32` and panic if the converted value doesn't fit
    |
217 |                 (offset as i64).try_into().unwrap(),
    |                 +             +++++++++++++++++++++
For more information about this error, try `rustc --explain E0308`.
error: could not compile `std` due to 2 previous errors
Build completed unsuccessfully in 0:00:45
```

</details>

2021-10-09 09:58 UTC, a1phyr commented
Well, I copied `read_vectored` for this.

Anyway, `readv` takes a `const struct iovec*`, so this is the good type. However, according to Rust rules we cannot modify something behind a shared reference, so I think we should get a `*mut` pointer and cast it to `*const`.

2021-12-13 11:02 UTC, a1phyr commented
Rebased

2022-02-19 02:57 UTC, Dylan-DPC commented
@joshtriplett this is ready for review

2022-07-29 14:42 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/7580799656?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/f3057494781bd34af445df5fcac4ec5f34a06387/checks/7580799656/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling addr2line v0.16.0
error[E0412]: cannot find type `c_int` in this scope
   --> library/std/src/sys/unix/fd.rs:167:52
    |
167 |                 cmp::min(bufs.len(), max_iov()) as c_int,
    |
help: consider importing one of these items
    |
6   | use core::ffi::c_int;
---

error[E0412]: cannot find type `c_int` in this scope
   --> library/std/src/sys/unix/fd.rs:255:52
    |
255 |                 cmp::min(bufs.len(), max_iov()) as c_int,
    |
help: consider importing one of these items
    |
6   | use core::ffi::c_int;
---
    |
153 |         target_os = "darwin",
    |         ^^^^^^^^^^^^^^^^^^^^
    |
    = note: `-D unexpected-cfgs` implied by `-D warnings`
    = note: expected values for `target_os` are: android, cuda, dragonfly, emscripten, espidf, freebsd, fuchsia, haiku, hermit, horizon, illumos, ios, l4re, linux, macos, netbsd, none, openbsd, psp, redox, solaris, solid_asp3, tvos, uefi, unknown, vxworks, wasi, watchos, windows, xous
error: unexpected `cfg` condition value
   --> library/std/src/sys/unix/fd.rs:176:9
    |
176 |         target_os = "darwin",
176 |         target_os = "darwin",
    |         ^^^^^^^^^^^^^^^^^^^^
    |
    = note: expected values for `target_os` are: android, cuda, dragonfly, emscripten, espidf, freebsd, fuchsia, haiku, hermit, horizon, illumos, ios, l4re, linux, macos, netbsd, none, openbsd, psp, redox, solaris, solid_asp3, tvos, uefi, unknown, vxworks, wasi, watchos, windows, xous
error: unexpected `cfg` condition value
   --> library/std/src/sys/unix/fd.rs:241:9
    |
241 |         target_os = "darwin",
241 |         target_os = "darwin",
    |         ^^^^^^^^^^^^^^^^^^^^
    |
    = note: expected values for `target_os` are: android, cuda, dragonfly, emscripten, espidf, freebsd, fuchsia, haiku, hermit, horizon, illumos, ios, l4re, linux, macos, netbsd, none, openbsd, psp, redox, solaris, solid_asp3, tvos, uefi, unknown, vxworks, wasi, watchos, windows, xous
error: unexpected `cfg` condition value
   --> library/std/src/sys/unix/fd.rs:264:9
    |
264 |         target_os = "darwin",
264 |         target_os = "darwin",
    |         ^^^^^^^^^^^^^^^^^^^^
    |
    = note: expected values for `target_os` are: android, cuda, dragonfly, emscripten, espidf, freebsd, fuchsia, haiku, hermit, horizon, illumos, ios, l4re, linux, macos, netbsd, none, openbsd, psp, redox, solaris, solid_asp3, tvos, uefi, unknown, vxworks, wasi, watchos, windows, xous
For more information about this error, try `rustc --explain E0412`.
error: could not compile `std` due to 6 previous errors
Build completed unsuccessfully in 0:00:23
```

</details>

2023-02-26 05:28 UTC, workingjubilee commented
@a1phyr Sorry for this slipping through the cracks! If you can fix the latest merge conflicts I can get this approved.

r? @workingjubilee

2023-02-27 09:57 UTC, a1phyr commented
Rebased

@rustbot label -S-waiting-on-author +S-waiting-on-review

2023-02-27 22:04 UTC, workingjubilee commented
@bors r+

2023-02-27 22:54 UTC, workingjubilee commented
![Aa, eeto... bleh!](https://user-images.githubusercontent.com/46493976/221705743-a526815a-e744-438f-8b44-0eff0d9801b8.gif)

2023-02-27 23:02 UTC, compiler-errors commented
@bors r=workingjubilee rollup

2023-02-28 15:16 UTC, matthiaskrgr commented
@bors r- rollup=iffy
failed in https://github.com/rust-lang/rust/pull/108559
`CANNOT LINK EXECUTABLE: could not load library "libstd-ef8e480f4327ce79.so" needed by "/data/local/tmp/work/test0/a"; caused by cannot locate symbol "preadv" referenced by "libstd-ef8e480f4327ce79.so"...`

https://github.com/rust-lang-ci/rust/actions/runs/4292167740/jobs/7478270814#step:26:16943

2023-02-28 23:41 UTC, workingjubilee commented
@a1phyr Do you have any insight into the linkage issues?

2023-03-01 09:29 UTC, a1phyr commented
Wild guess: `preadv` was added to bionic in 2015 (cf https://android.googlesource.com/platform/bionic/+/6f4594d). The tests may run with on older version.

To fix this, we could either disable `preadv` on android or use weak linkage.

2023-03-01 21:16 UTC, workingjubilee commented
Our Android minimum is increasing to Android KitKat. That's lower than Marshmallow, the Oct 2015 release. I need more coffee before I remember the details of how weak symbol linkage works, but what we do here has to work on KitKat and Lollipop, so go with whichever feels right there.

2023-03-02 19:25 UTC, workingjubilee requested changes
Bad news, I looked it up and it seems this was only introduced relatively late in the game by macOS (and iOS). It seems even https://github.com/rust-lang/rust/pull/104385 won't raise the minimum supported versions high enough to guarantee pwritev.

2023-03-02 19:25 UTC, workingjubilee commented on library/std/src/sys/unix/fd.rs
> +        super::weak::weak!(fn pwritev64(libc::c_int, *const libc::iovec, libc::c_int, off64_t) -> isize);
I, too, feel super weak when thinking about these sorts of things.

2023-03-03 20:41 UTC, workingjubilee approved these changes
Huzzah, let's see if this goes or if it tells us to do more.

@bors r+

2023-03-03 20:42 UTC, workingjubilee commented
Not again?
@bors r+

2023-03-04 08:07 UTC, merged

2023-03-04 10:09 UTC, rust-timer commented
Finished benchmarking commit (0fbfc3e76916521b509b63286296dd0762170d34): [comparison URL](https://perf.rust-lang.org/compare.html?start=70adb4e5b4c8f8bde4ade0edcb0435ff7bf31281&end=0fbfc3e76916521b509b63286296dd0762170d34&stat=instructions:u).

### Overall result: ❌ regressions - ACTION NEEDED


**Next Steps**: If you can justify the regressions found in this perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please open an issue or create a new PR that fixes the regressions, add a comment linking to the newly created issue or PR, and then add the `perf-regression-triaged` label to this PR.

@rustbot label: +perf-regression
cc @rust-lang/wg-compiler-performance



### [Instruction count](https://perf.rust-lang.org/compare.html?start=70adb4e5b4c8f8bde4ade0edcb0435ff7bf31281&end=0fbfc3e76916521b509b63286296dd0762170d34&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.2% | [0.2%, 0.3%] | 4     |
| Regressions ❌ <br /> (secondary)  | -    | -            | 0     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 0.2% | [0.2%, 0.3%] | 4     |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=70adb4e5b4c8f8bde4ade0edcb0435ff7bf31281&end=0fbfc3e76916521b509b63286296dd0762170d34&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean  | range          | count |
|:----------------------------------:|:-----:|:--------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 1.3%  | [1.3%, 1.3%]   | 1     |
| Regressions ❌ <br /> (secondary)  | -     | -              | 0     |
| Improvements ✅ <br /> (primary)   | -5.7% | [-5.7%, -5.7%] | 1     |
| Improvements ✅ <br /> (secondary) | -2.9% | [-3.0%, -2.7%] | 2     |
| All ❌✅ (primary)                 | -2.2% | [-5.7%, 1.3%]  | 2     |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=70adb4e5b4c8f8bde4ade0edcb0435ff7bf31281&end=0fbfc3e76916521b509b63286296dd0762170d34&stat=cycles:u)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|                                    | mean | range        | count |
|:----------------------------------:|:----:|:------------:|:-----:|
| Regressions ❌ <br /> (primary)    | 0.8% | [0.6%, 1.0%] | 8     |
| Regressions ❌ <br /> (secondary)  | 0.8% | [0.8%, 0.8%] | 1     |
| Improvements ✅ <br /> (primary)   | -    | -            | 0     |
| Improvements ✅ <br /> (secondary) | -    | -            | 0     |
| All ❌✅ (primary)                 | 0.8% | [0.6%, 1.0%] | 8     |
</details>

2023-03-07 15:35 UTC, rylev commented
Small regression in Diesel which has started to show some bimodality. I think it's safe to call this triaged.

@rustbot label +perf-regression-triaged