Apply clippy suggestions for rustc and core
rust-lang/rust pull request #89709
Opened 2021-10-09 18:46 UTC by clemenswasser

2021-10-10 08:58 UTC, eddyb requested changes

2021-10-11 08:21 UTC, petrochenkov commented
@bors r+

2021-10-11 14:16 UTC, merged

2021-10-12 21:09 UTC, pnkfelix commented
> @bors rollup=iffy just in case this has some unforeseen perf implications

I think its fair to say this had some unforeseen [perf implications](https://perf.rust-lang.org/compare.html?start=86d6d2b7389fe1b339402c1798edae8b695fc9ef&end=6ae8912a3e7d2c4c775024f58a7ba4b1aedc4073)

We see instruction-count regressions in the 1.1% to 2.7% range in keccak and inflate

2021-10-13 20:05 UTC, matthiaskrgr commented
I reverted parts of the merge in https://github.com/rust-lang/rust/pull/89855 can we get a perf run there to see if that fixes the regression?