enum variant support
rust-lang/rust pull request #89745
Opened 2021-10-10 19:49 UTC by zhamlin

Proof of concept for enum variant types.

2021-10-10 19:49 UTC, rust-highfive commented
Some changes occured to the CTFE / Miri engine

cc @rust-lang/miri

2021-10-10 19:56 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3852984234) [(plain)](https://github.com/rust-lang/rust/commit/43f9467f190ccb879113906c7a5aab5240d9d9fa/checks/3852984234/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking rustc_typeck v0.0.0 (/checkout/compiler/rustc_typeck)
    Checking rustc_plugin_impl v0.0.0 (/checkout/compiler/rustc_plugin_impl)
    Checking rustc_borrowck v0.0.0 (/checkout/compiler/rustc_borrowck)
    Checking rustc_mir_transform v0.0.0 (/checkout/compiler/rustc_mir_transform)
error: unused variable: `def_scope`
     |
     |
1770 |                         let (adjusted_ident, def_scope) =
     |                                              ^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_def_scope`
     |
     = note: `-D unused-variables` implied by `-D warnings`
error: could not compile `rustc_typeck` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
Build completed unsuccessfully in 0:02:43
```

</details>

2021-10-11 09:58 UTC, oli-obk requested changes
First of all, this is amazing. I thought an MVP would be significantly more involved, but you even got surface syntax working from the start.

I left a lot of comments, I do realize this is a draft and as a first iteration the copy paste is expected to get things running quickly. Please let me know how nit-picky you want the review to be. I'm also available on zulip for chatting if you prefer, just open a thread in the compiler team stream.

One general thing is that I think we should also change `TyLayout::for_variant` to return a `ty::Variant` in the type field instead of just returning the original type.

2021-10-11 13:05 UTC, jackh726 reviewed
Oli beat me to the review here, but I'm just as excited :)

Just one comment for now!

2021-10-12 13:59 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/3871305712) [(plain)](https://github.com/rust-lang/rust/commit/14a70a9fafe203f2c1531bd16d6bd092d4d0f1f4/checks/3871305712/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking tracing-tree v0.1.9
    Checking rustdoc-json-types v0.1.0 (/checkout/src/rustdoc-json-types)
    Checking tera v1.10.0
    Checking rustdoc v0.0.0 (/checkout/src/librustdoc)
error[E0004]: non-exhaustive patterns: `Variant(_, _)` not covered
    --> src/librustdoc/clean/mod.rs:1398:15
     |
1398 |         match *ty.kind() {
     |               ^^^^^^^^^^ pattern `Variant(_, _)` not covered
    ::: /checkout/compiler/rustc_middle/src/ty/sty.rs:199:5
     |
     |
199  |     Variant(Ty<'tcx>, VariantIdx),
     |
     = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
     = note: the matched value is of type `rustc_middle::ty::TyKind`


error[E0004]: non-exhaustive patterns: `Variant(_, _)` not covered
    |
    |
539 |         Some(match *self.cx.tcx.type_of(ty_id).kind() {
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ pattern `Variant(_, _)` not covered
   ::: /checkout/compiler/rustc_middle/src/ty/sty.rs:199:5
    |
    |
199 |     Variant(Ty<'tcx>, VariantIdx),
    |
    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
    = note: the matched value is of type `rustc_middle::ty::TyKind`

```

</details>

2021-10-13 22:39 UTC, oli-obk commented
1 and 2 are invisible to users. They are essentially cleanups of the compiler's logic.

For 3 we'd at least need an accepted MCP, from the zulip discussion it sounded like there was nothing speaking against it, so maybe just asking for a "second" to be able to experiment is all that is needed at this stage?

2021-10-13 22:52 UTC, zhamlin commented
Would zulip be the best place to discuss this going forward?
I have some questions before I can get started on 1

2021-10-14 04:18 UTC, oli-obk commented
`@oli`

2021-11-19 14:09 UTC, closed without merging