Make most std::ops traits const on numeric types
rust-lang/rust pull request #89876
Opened 2021-10-14 08:41 UTC by AlexApps99

This PR makes existing implementations of `std::ops` traits (`Add`, `Sub`, etc) [`impl const`](https://github.com/rust-lang/rust/issues/67792) where possible.
This affects:
- All numeric primitives (`u*`, `i*`, `f*`)
- `NonZero*`
- `Wrapping`

This is under the `rustc_const_unstable` feature `const_ops`.
I will write tests once I know what can and can't be kept for the final version of this PR.

Since this is my first PR to rustc (and hopefully one of many), please give me feedback on how to better handle the PR process wherever possible. Thanks

[Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Const.20std.3A.3Aops.20traits.20PR)

2021-10-20 02:17 UTC, AlexApps99 commented
Looks like someone's PR beat me to it (#90009).
A bit disheartening, but only a small part of this PR.
Hopefully it can be reviewed soon.
In the mean time, I am writing a tracking issue.

2021-10-20 19:21 UTC, oli-obk commented
r? @oli-obk

2021-10-20 19:22 UTC, oli-obk commented
As discussed in the libs-api meeting today, @rust-lang/wg-const-eval may now approve *unstably* adding `const` to trait impls, including using `~const`.

2021-10-20 19:30 UTC, oli-obk requested changes
The impl looks good! We can go ahead with all of these. Just needs those tests you talked about.

2021-10-30 09:49 UTC, oli-obk commented
@bors r+ rollup

2021-10-30 09:51 UTC, AlexApps99 commented
I haven't completed the tests yet (mostly for a lack of time), are you sure it's OK to be merged without them?

2021-10-30 16:22 UTC, merged

2021-11-03 14:55 UTC, RalfJung commented
> I haven't completed the tests yet (mostly for a lack of time), are you sure it's OK to be merged without them?

Could you open an issue to track adding those tests, maybe leaving some notes for what kinds of tests you think would be good to have?

2021-11-03 20:05 UTC, AlexApps99 commented
I'll put it on the tracking issue, I'm busy with exams right now but I should be able to set aside some time to implement the tests in a week or two.

2022-07-24 15:54 UTC, ChaiTRex commented
This seems to work on `u8 >> i32`, but not on `&u8 >> i32`, even though there's an implementation for both.

2022-07-24 17:00 UTC, fee1-dead commented
> This seems to add `const` to `u8 >> i32`, but not to `&u8 >> i32`, even though there's an implementation for both.

Does [this](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4a9743179ec6f21e4ee57429e269b451) work?

2022-07-25 16:42 UTC, ChaiTRex commented
> > This seems to add `const` to `u8 >> i32`, but not to `&u8 >> i32`, even though there's an implementation for both.
> 
> Does [this](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4a9743179ec6f21e4ee57429e269b451) work?

Ahh, I see the problem. I was using `#![feature(const_ops)]` instead of `#![feature(const_trait_impl)]`. The latter works. Thanks.