implement rfc-2528 type_changing-struct-update
rust-lang/rust pull request #90035
Opened 2021-10-19 03:12 UTC by SparrowLii

This PR implement rfc2528-type_changing-struct-update.
The main change process is as follows:
1. Move the processing part of `base_expr` into `check_expr_struct_fields` to avoid returning `remaining_fields` (a relatively complex hash table)
2. Before performing the type consistency check(`check_expr_has_type_or_error`), if the `type_changing_struct_update` feature is set, enter a different processing flow, otherwise keep the original flow
3. In the case of the same structure definition, check each field in `remaining_fields`. If the field in `base_expr` is not the suptype of the field in `adt_ty`, an error(`FeildMisMatch`) will be reported.

The MIR part does not need to be changed, because only the items contained in `remaining_fields` will be extracted from `base_expr` when MIR is generated. This means that fields with different types in `base_expr` will not be used
Updates #86618
cc @nikomatsakis

2021-10-19 03:12 UTC, rust-highfive commented
r? @jackh726

(rust-highfive has picked a reviewer for you, use r? to override)

2021-10-26 19:00 UTC, jackh726 requested changes
Overall pretty straightforward, a few nits. Can you squash the commits (other than spliting out that one commit)?

2021-11-04 18:06 UTC, jackh726 requested changes
Last commit feels a bit messy to me; not sure how best to clean it up though.

Left a couple commits.

2021-11-04 18:06 UTC, jackh726 commented on compiler/rustc_typeck/src/check/expr.rs
> +                is_struct = false;
Why not just emit the error here?

Or, better yet, any way we can just return early and do away with the nesting?

2021-11-05 01:31 UTC, SparrowLii commented
I manually copied most of the implementation of check_expr_has_type_or_error, which would make the code messy, which is obviously unwise. So I went back to the previous submission and found a new way. It should be clear enough now and can be reviewed.

2021-11-09 23:16 UTC, merged