Show all Deref implementations recursively
rust-lang/rust pull request #90183
Opened 2021-10-22 22:34 UTC by GuillaumeGomez

Fixes #87783.

This is a re-implementation of #80653, so taking the original PR comment:

This changes `rustdoc` to recursively follow `Deref` targets so that methods from all levels are added to the rendered output. This implementation displays the methods from all levels in the expanded state with separate sections for each level.

![image](https://user-images.githubusercontent.com/279572/103482863-46723b00-4ddb-11eb-972b-c463351a425c.png)

cc @camelid
r? @jyn514

2021-10-29 00:40 UTC, jyn514 requested changes
@GuillaumeGomez can you also test whether this fixes https://github.com/rust-lang/rust/issues/84630?

My understanding is that this doesn't re-introduce https://github.com/rust-lang/rust/issues/82465, since the test `src/test/rustdoc/issue-82465-asref-for-and-of-local.rs` hasn't changed - is that correct?

2021-10-29 21:09 UTC, jyn514 commented on src/test/rustdoc/recursive-deref.rs
> +// @!has '-' '//*[@id="deref-methods-G"]'
Gotcha. Can you add that as a comment?

2021-10-29 21:09 UTC, jyn514 commented on src/test/rustdoc/deref-recursive.rs
> +// levels if needed.
That makes sense :+1: can you add it as a comment?

2021-10-29 21:10 UTC, jyn514 commented on src/librustdoc/passes/collect_trait_impls.rs
> +            is_deref || self.keep_impl_with_def_id(did.into())
Ok. I'm not quite sure I understand the logic but given that the test cases pass I'm ok with leaving it as is :)

2021-10-29 21:11 UTC, jyn514 commented
@bors r+

2021-10-29 21:11 UTC, jyn514 commented
Oh oops, I forgot I asked you to add a couple comments - r=me with that done.

@bors r-

2021-10-30 14:26 UTC, GuillaumeGomez commented on src/test/rustdoc/recursive-deref.rs
> +// @!has '-' '//*[@id="deref-methods-G"]'
Sure.

2021-10-30 15:06 UTC, GuillaumeGomez commented
@bors: r=jyn514

2021-10-30 18:30 UTC, camelid commented
@jyn514 why did you beta-nominate this? The previous attempt at this change had to be reverted, so it seems risky to backport this PR. Also, the regression it fixes is already on stable.

2021-10-30 18:35 UTC, jyn514 commented
@camelid because they're pretty bad regressions; several of them were announced in release notes and then missing from the next release. I'm ok with not backporting if you think it's risky, but I don't think it should be because the regressions are on stable.

2021-10-30 19:37 UTC, camelid commented
I'd rather not backport since this PR could very possibly cause yet another regression, which we'd then have to revert on beta. Having a known regression on stable for one extra release seems better to me than the chance of accidentally introducing an unknown regression on beta right before release.

2021-10-30 19:38 UTC, camelid commented
cc @rust-lang/rustdoc for backport discussion

2021-10-30 19:45 UTC, GuillaumeGomez commented
Since I'm the author of this PR, I'll remain neutral. :)

2021-10-30 22:39 UTC, merged

2021-10-31 11:36 UTC, GuillaumeGomez commented
The perf regression was expected. Maybe not this big though...

2021-10-31 15:49 UTC, jyn514 commented
@GuillaumeGomez What regression are you referring to?

2021-10-31 16:56 UTC, camelid commented
@jyn514 I assume [this one](https://github.com/rust-lang/rust/pull/90422#issuecomment-955611455), and yeah, that is a pretty severe regression. Any idea if it can be reduced or does this change necessitate it?

2021-10-31 18:52 UTC, GuillaumeGomez commented
We have to allocate a `HashSet` to ensure that we don't recurse infinitely and we also render a lot more of items. So it's most likely unavoidable. I have an idea which could reduce it a bit: currently we fill a `HashMap` with deref links and we also have a `HashSet` which checks that we don't recurse infinitely. Maybe we could use the `HashMap` directly.

When I tested it, I encountered on issue not on the fill part but on the render part. Might be worth taking another look at it.

2021-10-31 19:13 UTC, camelid commented
>  I have an idea which could reduce it a bit: currently we fill a `HashMap` with deref links and we also have a `HashSet` which checks that we don't recurse infinitely. Maybe we could use the `HashMap` directly.

That sounds potentially promising. Also, I'd suggest trying `BTreeMap` since IIRC it's often more performant with small keys like `DefId`.

2021-10-31 19:22 UTC, jsha commented
I'm not fully caught up on the details here, but is it feasible to instead set a small constant limit on recursion depth? E.g. go at most 3 levels deep?

2021-10-31 19:25 UTC, GuillaumeGomez commented
I guess we can, but do we want to?

2021-10-31 21:22 UTC, camelid commented
> I'm not fully caught up on the details here, but is it feasible to instead set a small constant limit on recursion depth? E.g. go at most 3 levels deep?

That could potentially incur unnecessary recursion since the same Deref impl could be processed 3 times when it only needs to be processed once. Also, it might be confusing for users if a particular type has more than 3 levels of Deref indirection. Having that much indirection is already confusing, but it doesn't seem great for rustdoc to make it more confusing by stopping early.

2021-11-01 01:01 UTC, jyn514 commented
Has anyone actually profiled the difference to see what's taking longer?

2021-11-01 12:32 UTC, GuillaumeGomez commented
I didn't at least.

2021-11-11 10:14 UTC, apiraino commented
Backport suspended, waiting for #90489 (see [Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202021-11-04.20.2354818/near/260278752))

2021-11-11 11:27 UTC, GuillaumeGomez commented
cc @rust-lang/rustdoc

2021-11-11 14:16 UTC, jyn514 commented
@apiraino what feedback is needed? I left some comments in the Zulip thread already last week.

2021-11-11 15:33 UTC, apiraino commented
Ok, let me [link your comments on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202021-11-04.20.2354818/near/260332428) here for reference.

Also, [discussed today on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202021-11-11.20.2354818/near/261146824)

2021-11-11 15:50 UTC, jyn514 commented
The conclusion in the compiler meeting was "we don't have enough background and this only touches rustdoc, so we defer to T-rustdoc's decision."

2021-11-18 11:16 UTC, apiraino commented
Beta backport declined as per latest discussion, seems the aggreement is to let it flow to next beta (which should be tagged in about two weeks)

@rustbot label -beta-nominated