[EXPERIMENT] rustdoc: Cleanup `external_traits`
rust-lang/rust pull request #90365
Opened 2021-10-28 04:27 UTC by camelid

r? @ghost
cc @jyn514

2021-10-28 09:18 UTC, jyn514 requested changes

2021-12-14 23:56 UTC, camelid commented
I'm going to close this for now since it's not the right approach.

2021-12-14 23:56 UTC, closed without merging

2021-12-16 14:41 UTC, jyn514 commented
@camelid did you get a chance to try out https://github.com/rust-lang/rust/pull/90365#discussion_r738825148 ? I think with that change this would be the right approach :)

2021-12-17 02:35 UTC, camelid commented
Yeah, I did. The issue is that it causes multiple mutable borrows of `self` to be live simultaneously in the folder/visitor: one reference for the `DocContext` (because it's stored as a field of the folder) and one reference for the visiting of the external traits.

I don't think there's a good way to solve that problem without coming up with a different approach.