Clean up mess for --show-coverage documentation
rust-lang/rust pull request #90438
Opened 2021-10-31 12:54 UTC by GuillaumeGomez

It was somewhat duplicated for some reasons... Anyway, this remove this duplication and clean up a bit.

r? @camelid

2021-11-01 21:21 UTC, camelid requested changes
IMO the docs for `--show-coverage` earlier on the page are clearer and more comprehensive than the docs near the end of the page. Can you keep the earlier docs and get rid of the later docs instead?

2021-11-08 14:21 UTC, GuillaumeGomez commented
Updated!

2021-11-17 16:30 UTC, camelid approved these changes
r=me with these comments fixed

2021-11-17 16:30 UTC, camelid commented on src/doc/rustdoc/src/unstable-features.md
> -+-------------------------------------+------------+------------+------------+------------+
Could you keep this example and put it in the merged section?

2021-11-17 16:30 UTC, camelid commented on src/doc/rustdoc/src/unstable-features.md
> -2. If one of the previously listed items has a code example, then it'll be counted.
It doesn't look like there's corresponding docs in the new section about this? Maybe move this part to the new section as well?

2021-11-17 16:30 UTC, camelid commented on src/doc/rustdoc/src/unstable-features.md
> +When using `--output-format json` with this option, it will display the coverage information in
```suggestion
#### JSON output

When using `--output-format json` with this option, it will display the coverage information in
```

2021-11-17 16:30 UTC, camelid commented on src/doc/rustdoc/src/unstable-features.md
> +[documentation](https://doc.rust-lang.org/nightly/rustdoc/unstable-features.html#--show-coverage-get-statistics-about-code-documentation-coverage) for more
```suggestion
[documentation](#--show-coverage-get-statistics-about-code-documentation-coverage) for more
```

2021-11-18 11:57 UTC, GuillaumeGomez commented
Updated!

@bors: r=camelid rollup

2021-11-18 23:29 UTC, merged

2021-11-19 08:57 UTC, GuillaumeGomez commented on src/doc/rustdoc/src/unstable-features.md
> -
Bad copy/paste. Will send a PR to put it back.