Properly register text_direction_codepoint_in_comment lint.
rust-lang/rust pull request #90626
Opened 2021-11-05 19:01 UTC by hkratz

This makes it known to the compiler so it can be configured like with `#![allow(text_direction_codepoint_in_comment)]`.

Fixes #90614.

2021-11-05 19:01 UTC, rust-highfive commented
r? @wesleywiser

(rust-highfive has picked a reviewer for you, use r? to override)

2021-11-05 19:07 UTC, jyn514 requested changes

2021-11-05 19:07 UTC, jyn514 commented on src/test/ui/lint/issue-90614-accept-allow-text-direction-codepoint-in-comment-lint.rs
> +// build-pass
```suggestion
// check-pass
```

2021-11-05 19:13 UTC, hkratz commented on src/test/ui/lint/issue-90614-accept-allow-text-direction-codepoint-in-comment-lint.rs
> +// build-pass
Squashed in.

2021-11-05 19:55 UTC, jyn514 commented
Thanks!

@bors r+ rollup

2021-11-06 01:12 UTC, merged

2021-11-11 15:15 UTC, apiraino commented
Beta backport approved as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202021-11-11.20.2354818/near/261145463)

@rustbot label +beta-accepted