str::lines and BufRead::lines: document trailing bare cr behaviour
rust-lang/rust pull request #91051
Opened 2021-11-19 19:11 UTC by ijackson

Apropos discussion here  https://github.com/rust-lang/rust/pull/91047#issuecomment-974321038

Sadly, str::lines gets this wrong.  I think it is probably too late to
fix this, so document it instead.

2021-11-19 19:11 UTC, rust-highfive commented
r? @m-ou-se

(rust-highfive has picked a reviewer for you, use r? to override)

2021-11-20 08:54 UTC, r00ster91 requested changes
Can we keep it neutral and not have it sound so negative? I don't think giving the "we messed up" vibe in the official docs adds a lot of value.
And instead of referring to the two ways as "correct" and "incorrect" you could be more explicit.

2021-11-20 08:54 UTC, r00ster91 commented on library/core/src/str/mod.rs
> +    /// assert_eq!(Some("bar"), lines.next()); // should really return "bar\r"
```suggestion
    /// assert_eq!(Some("bar"), lines.next()); // does not return "bar\r"
```

2021-11-20 08:54 UTC, r00ster91 commented on library/std/src/io/mod.rs
> +    /// Unlike [`str::lines`], trailing bare CR is handled correctly:
```suggestion
    /// Unlike [`str::lines`], trailing bare CR is not handled as a newline:
```

2021-11-20 08:54 UTC, r00ster91 commented on library/core/src/str/mod.rs
> +    /// (`std::io::BufRead::lines` handles this case correctly.)
```suggestion
    /// Unlike [`std::io::BufRead::lines`], trailing bare CR is handled as a newline:
```

2021-11-20 08:54 UTC, r00ster91 commented on library/std/src/io/mod.rs
> +    /// assert_eq!(lines_iter.next(), Some(String::from("ipsum\r"))); // bare CR is not a newline
```suggestion
    /// assert_eq!(lines_iter.next(), Some(String::from("ipsum\r"))); // does not return "ipsum"
```

2021-11-20 09:46 UTC, hkratz commented
I think we should just fix this and make `str::lines` like `BufRead::lines`. I don't think that much (if any) code relies on this (faulty) behavior.

2021-11-20 13:03 UTC, ijackson commented
> I think we should just fix this and make `str::lines` like `BufRead::lines`. I don't think that much (if any) code relies on this (faulty) behavior.

I think this would need an FCP, but it is indeed our other option.  I will work up an MR to do this, so we can see what it looks like (and what kind of justification I find I am able to write).

I think we should choose between fixing it, and acknowledging that it is, at the very least, anomalous.  I don't think we should pretend (even implicitly) in the docs that we think the current behaviour of `str::lines` is correct.

2021-11-20 14:03 UTC, shirshak55 commented
I don't think many libs rely on this behaviour so fixing would be a wise decision rather than mitigating it by adding docs. Not many of us are going to read the documentation and this is not expected too.  So it would be better if we fix it.  Maybe next time when we do a crater run we can investigate how much churn it would cause in the ecosystem.

2022-04-12 01:51 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/5979842920?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/9b1f6c50c5204e50f6553ca4ed92974f7fa59e3a/checks/5979842920/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
 Documenting core v0.0.0 (/checkout/library/core)
error: unresolved link to `std::io::BufRead::lines`
   --> library/core/src/str/mod.rs:996:18
    |
996 |     /// Unlike [`std::io::BufRead::lines`], trailing bare CR is handled as a newline:
    |                  ^^^^^^^^^^^^^^^^^^^^^^^ no item named `std` in scope
    |
    = note: `-D rustdoc::broken-intra-doc-links` implied by `-D warnings`
error: could not document `core`

Caused by:
Caused by:
  process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustdoc --edition=2021 --crate-type lib --crate-name core library/core/src/lib.rs --target x86_64-unknown-linux-gnu -o /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --markdown-css rust.css --markdown-no-toc -Z unstable-options --resource-suffix 1.62.0 --index-page /checkout/src/doc/index.md -C metadata=4599449636879869 -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/release/deps --cfg=bootstrap -Csymbol-mangling-version=legacy -Zunstable-options -Dwarnings '-Wrustdoc::invalid_codeblock_attributes' --crate-version '1.62.0-nightly
  (ce412f469
  2022-04-11)' '-Zcrate-attr=doc(html_root_url="https://doc.rust-lang.org/nightly/")'` (exit status: 1)
```

</details>

2022-05-10 09:37 UTC, Dylan-DPC commented
@ijackson if you can rebase this we can push this forward

2022-05-13 18:43 UTC, ChrisDenton commented
> I think we should just fix this and make `str::lines` like `BufRead::lines`.

> I don't think many libs rely on this behaviour so fixing would be a wise decision rather than mitigating it by adding docs.

Given these comments, ping @rust-lang/libs-api

2022-05-13 20:38 UTC, joshtriplett commented
I do think we could try a crater run fixing the two to be consistent.

2022-05-16 09:52 UTC, m-ou-se commented
I agree, these two being inconsistent seems like a mistake we should fix.

2022-07-23 23:32 UTC, JohnCSimon commented
Triage: 
@ijackson What is the status of this PR?

2022-07-23 23:56 UTC, JohnCSimon commented
@ijackson 
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you do please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

2022-07-23 23:56 UTC, closed without merging