Use try_normalize_erasing_regions in needs_drop
rust-lang/rust pull request #91462
Opened 2021-12-02 19:32 UTC by b-naber

Fixes https://github.com/rust-lang/rust/issues/81199

r? @jackh726

2021-12-02 19:43 UTC, jackh726 requested changes
Can you use `unwrap_or`? Otherwise LGTM

2021-12-02 19:43 UTC, jackh726 commented
r=me after changing to `unwrap_or`

@bors delegate+

2021-12-02 19:56 UTC, Aaron1011 commented on compiler/rustc_middle/src/ty/util.rs
> +                let query_ty = match tcx.try_normalize_erasing_regions(param_env, query_ty) {
You could use `.unwrap_or(query_ty)` here

2021-12-02 22:28 UTC, b-naber commented
@bors r=jackh726 rollup

2021-12-03 11:41 UTC, pietroalbini commented
This has been merged into master by bors (in https://github.com/rust-lang/rust/pull/91486), but GitHub didn't detect it for whatever reason. Closing.

2021-12-03 11:41 UTC, closed without merging