Remove unnecessary bounds for some Hash{Map,Set} methods
rust-lang/rust pull request #91593
Opened 2021-12-06 14:29 UTC by upsuper

This PR moves `HashMap::{into_keys,into_values,retain}` and `HashSet::retain` from `impl` blocks with `K: Eq + Hash, S: BuildHasher` into the blocks without them. It doesn't seem to me there is any reason these methods need to be bounded by that.

2021-12-07 08:30 UTC, upsuper commented
r? @dtolnay

2021-12-17 05:44 UTC, upsuper commented
Ping? Anyone from the libs team can have a look?

2021-12-17 07:28 UTC, Folyd commented
I'm in favor of the `K: Eq + Hash, S: BuildHasher` bound is unnecessary. BTW,  don't forget the `BTreeMap::into_key/values()`.

2021-12-20 20:52 UTC, dtolnay requested changes
`into_keys` and `into_values` seems straightforward to me, since `IntoIterator for HashMap` and `IntoIterator for &HashMap` already do not require any bound to iterate, and these functions are doing *even less* because they don't even iterate, just stick `self` inside of an iterator struct, which already has no bounds on its `Iterator` impl.

`retain` is not obvious to me. Is there an easy way to see why this wouldn't need to rehash items as part of shrinking the map, in any hash map implementation?

2021-12-20 22:56 UTC, upsuper commented
> `retain` is not obvious to me. Is there an easy way to see why this wouldn't need to rehash items as part of shrinking the map, in any hash map implementation?

It's a good question. I don't think `retain` should ever shrink the hash map in capacity. It doesn't now, nor do `retain`s of other collections, and as long as we want to guarantee deletion of a single entry wouldn't trigger a reallocation, the same guarantee should always apply to `retain` as well, since `retain` is just a batch deletion.

The question then fall to whether we ever need to rehash anything for deletion of an entry. I feel this is hard, if not impossible, to prove, as there is an open design space. However, it may not matter here, because in std's API, [`OccupiedEntry::remove_entry`](https://doc.rust-lang.org/std/collections/hash_map/struct.OccupiedEntry.html#method.remove_entry) is stable and doesn't have the bound, so any implementation that Rust can be using would likely be restricted by this API, and is unable to do any rehash when removing a single entry. (TBH, as you can't get an occupied entry without going through a function by the traits, theoretically it's possible to pre-compute all needed rehashes and store it inside `OccupiedEntry`, but that's likely a lot of unnecessary computation, and would probably be a violation of zero cost principle.)

Since `retain` is semantically just a combination of
* going through each occupied entry, which `HashMap::iter_mut` is already doing without the bounds, and
* conditionally delete entries occurred, which `OccupiedEntry::remove_entry` can do without the bounds
I believe it wouldn't ever need the bounds.

Also, if the bounds here are deemed not to be dropped for `retain`, we should also move the unstable [`HashMap::drain_filter`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.drain_filter) (tracked in #59618) into the bounded `impl` block before stabilization, since it's a more powerful version of `retain`.

2021-12-20 23:19 UTC, dtolnay commented
Let's get the rest of the team to weigh in.

```diff
  impl<K, V, S> HashMap<K, V, S> {
      pub fn into_keys(self) -> IntoKeys<K, V>
      where
-         K: Eq + Hash,
-         S: BuildHasher;

      pub fn into_values(self) -> IntoValues<K, V>
      where
-         K: Eq + Hash,
-         S: BuildHasher;

      pub fn retain<F>(&mut self, f: F)
      where
-         K: Eq + Hash,
-         S: BuildHasher,
          F: FnMut(&K, &mut V) -> bool;
  }

  impl<T, S> HashSet<T, S> {
      pub fn retain<F>(&mut self, f: F)
      where
-         T: Eq + Hash,
-         S: BuildHasher,
          F: FnMut(&T) -> bool;
  }
```

@rfcbot fcp merge

2021-12-20 23:37 UTC, joshtriplett commented
Interesting! I agree that `remove_entry` is effectively constraining possible implementations here; good catch. That does limit some hash table designs, but those designs are already limited.

@rfcbot reviewed

2022-01-01 21:15 UTC, dtolnay approved these changes
Thanks!

2022-01-01 21:15 UTC, dtolnay commented
@bors r+

2022-01-02 03:21 UTC, merged