Implement split_at_spare_mut without Deref to a slice
rust-lang/rust pull request #92097
Opened 2021-12-19 06:12 UTC by saethlin

I'm not sure I understand what's going on here correctly. And I'm pretty sure this safety comment needs to be changed. I'm just referring to the same thing that `as_mut_ptr_range` does.

I tried to run https://github.com/rust-lang/miri-test-libstd on alloc with -Zmiri-track-raw-pointers, and got a failure on the test `vec::test_extend_from_within`.

I minimized the test failure into this program:
```rust
#![feature(vec_split_at_spare)]
fn main() {
    Vec::<i32>::with_capacity(1).split_at_spare_mut();
}
```

I _think_ the problem is that the existing implementation is actually getting a pointer range where both pointers are derived from the initialized region of the Vec's allocation, but we need the second one to be valid for the region between len and capacity.

2021-12-19 06:12 UTC, rust-highfive commented
r? @m-ou-se

(rust-highfive has picked a reviewer for you, use r? to override)

2021-12-19 06:18 UTC, jyn514 commented
cc @RalfJung

2021-12-19 19:37 UTC, RalfJung commented on library/alloc/src/vec/mod.rs
> -        let Range { start: ptr, end: spare_ptr } = self.as_mut_ptr_range();
Yeah this is like a few other things around `Vec` that I fixed, which all boiled down to implicitly creating a slice and then using that to do something in the uninit part.

2021-12-19 19:37 UTC, RalfJung commented on library/alloc/src/vec/mod.rs
> +        // SAFETY: see slice::as_ptr_range() for why `add` here is safe.
This is safe because we always know that our buffer is at least `self.len` elements big.

2021-12-19 19:37 UTC, RalfJung commented on library/alloc/src/vec/mod.rs
> +        let spare_ptr = unsafe { ptr.add(self.len()) };
```suggestion
        let spare_ptr = unsafe { ptr.add(self.len) };
```
The `&self` for the `len` method is probably no issue, but there is no reason to call it either.

2021-12-19 21:41 UTC, RalfJung commented
LGTM, but I'll wait on libs team judgment on whether they want to land this (since it only is a fix wrt a proposed model, not wrt anything "official").

2021-12-31 18:29 UTC, saethlin commented
r? @the8472

2021-12-31 20:44 UTC, the8472 requested changes
Note that I'm libs-contributor, not libs-team. That said I'm fairly familiar with `Vec` so I'll go ahead anyway.

Looking at the history this was intentionally (but tangentially) changed in #82564 and reviewed by @RalfJung. Since that PR was about changing `spare_capacity_mut` undoing the  `split_at_spare_mut` changes should be fine.

And since `Vec` uses raw pointers all over the place and it's consistent with changes previously made I don't see an issue with doing it here too.

2021-12-31 23:59 UTC, the8472 commented
@bors r+ rollup=always

2022-01-01 13:28 UTC, merged