Suggest adding `{ .. }` around more bad const generic exprs
rust-lang/rust pull request #92884
Opened 2022-01-14 07:04 UTC by compiler-errors

Fixes #92776

2022-01-14 07:04 UTC, rust-highfive commented
r? @matthewjasper

(rust-highfive has picked a reviewer for you, use r? to override)

2022-01-14 15:12 UTC, lcnr commented
that's really nice :sparkles: gj

2022-02-24 16:37 UTC, compiler-errors commented
nvm, let's try

r? rust-lang/compiler

2022-02-25 20:16 UTC, jackh726 requested changes
One nit, then r=me

2022-02-25 20:16 UTC, jackh726 commented on compiler/rustc_parse/src/parser/path.rs
> +            match self.parse_expr_res(Restrictions::CONST_EXPR, None) {
Comment here would be nice.

2022-02-25 20:17 UTC, jackh726 commented
@bors delegate+

2022-02-26 01:17 UTC, compiler-errors commented
@bors r=jackh726

2022-02-26 07:00 UTC, merged