Don't constrain projection predicates with inference vars in GAT substs
rust-lang/rust pull request #92917
Opened 2022-01-15 02:24 UTC by jackh726

cc #91762 

Not a fix, but a mitigation to prevent a backwards-compatible hazard where we normalize using a predicate only because it's the only one available, but shouldn't. This would constrain an inference variable which didn't really want. We already do this when selecting a projection candidate, which isn't always correct. But changing that is a problem for a different day.

Also found out that a suggestion for `await`ing a future was using the wrong substs.

r? @nikomatsakis

2022-01-31 15:29 UTC, nikomatsakis requested changes

2022-01-31 15:29 UTC, nikomatsakis commented on compiler/rustc_trait_selection/src/traits/project.rs
> +        return Ok(ProjectedTy::NoProgress(
I think we want to treat this the same way we would treat an ambiguous set of candidates (i.e., `Err(ProjectionTyError::TooManyCandidates)`)

2022-01-31 15:29 UTC, nikomatsakis commented
@rustbot author

2022-02-07 20:11 UTC, jackh726 commented
Updated

@rustbot ready

2022-02-07 21:09 UTC, nikomatsakis approved these changes

2022-02-07 21:09 UTC, nikomatsakis commented
@bors r+

2022-02-09 04:05 UTC, merged