DRAFT: wasi: implement `sock_accept` and enable networking
rust-lang/rust pull request #93158
Opened 2022-01-21 13:29 UTC by haraldh

With the addition of `sock_accept()` to snapshot1, simple networking via a passed `TcpListener` is possible. This PR implements the basics to make a simple server work.

2022-01-21 13:29 UTC, rust-highfive commented
r? @dtolnay

(rust-highfive has picked a reviewer for you, use r? to override)

2022-01-21 13:36 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/4896931197?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/b392339ff9bf8c41fcfa24ec4dc2815b1a47a087/checks/4896931197/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

```

</details>

2022-01-28 06:03 UTC, dtolnay requested changes
Thanks, this looks good to me after the fix in decode_error_kind.

Feel free to ping anyone who would have a useful opinion about the TcpListener::accept return value. Probably any value is better than `unsupported()` though.

2022-01-28 12:00 UTC, haraldh commented on library/std/src/os/wasi/net/mod.rs
> +        self.as_inner().as_inner().as_inner().sock_accept(flags)
hehe

2022-01-28 12:00 UTC, haraldh commented on library/std/src/sys/wasi/mod.rs
> +        e if e == wasi::ERRNO_AGAIN.raw().into() => WouldBlock,
oops :)

2022-01-28 12:28 UTC, haraldh commented on library/std/src/sys/wasi/mod.rs
> +        e if e == wasi::ERRNO_AGAIN.raw().into() => WouldBlock,
removed

2022-01-28 12:29 UTC, haraldh commented
> Thanks, this looks good to me after the fix in decode_error_kind.

@dtolnay fixed and rebased

2022-01-28 13:11 UTC, dtolnay approved these changes

2022-01-28 13:11 UTC, dtolnay commented
@bors r+

2022-01-29 02:20 UTC, merged