Move overlap_mode into crate level attribute
rust-lang/rust pull request #93348
Opened 2022-01-26 21:52 UTC by spastorino

r? @nikomatsakis 

Should fix some performance regressions noted on https://github.com/rust-lang/rust/pull/93175

2022-01-26 21:52 UTC, spastorino commented
@bors try @rust-timer queue

2022-01-26 21:52 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

2022-01-26 22:00 UTC, nikomatsakis requested changes
r=me otherwise

2022-01-26 22:00 UTC, nikomatsakis commented on compiler/rustc_feature/src/active.rs
>      (active, repr_simd, "1.4.0", Some(27731), None),
This is a "perma-unstable" feature, just for testing purposes...at least thus far...so can you move it up to the group above, e.g. where `rustc_private` and so forth are found? And maybe rename to `rustc_strict_coherence`?

2022-01-26 22:00 UTC, nikomatsakis commented
@bors rollup=never

2022-01-26 22:02 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/4958306290?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/291a4c335552ba97bdf641c006ce9e86f6f7fab2/checks/4958306290/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
* highest error code: E0787
Found 503 error codes
Found 0 error codes with no tests
Done!
tidy error: /checkout/compiler/rustc_feature/src/active.rs:491: no tracking issue for feature strict_coherence
tidy error: /checkout/compiler/rustc_feature/src/active.rs:493: no tracking issue for feature with_negative_coherence
tidy error: /checkout/compiler/rustc_feature/src/active.rs:495: feature simd_ffi is not sorted by feature name (should be between repr_simd and strict_coherence)
tidy error: Found 2 features without a gate test.
Expected a gate test for the feature 'with_negative_coherence'.
Hint: create a failing test file named 'feature-gate-with_negative_coherence.rs'
      in the 'ui' test suite, with its failures due to
      missing usage of `#![feature(with_negative_coherence)]`.
Hint: If you already have such a test and don't want to rename it,
      you can also add a // gate-test-with_negative_coherence line to the test file.
Expected a gate test for the feature 'strict_coherence'.
Hint: create a failing test file named 'feature-gate-strict_coherence.rs'
      in the 'ui' test suite, with its failures due to
      missing usage of `#![feature(strict_coherence)]`.
Hint: If you already have such a test and don't want to rename it,
      you can also add a // gate-test-strict_coherence line to the test file.
some tidy checks failed


command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/rust-tidy" "/checkout" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "/checkout/obj/build" "16"


Build completed unsuccessfully in 0:00:11
```

</details>

2022-01-26 23:01 UTC, nikomatsakis requested changes
I think I have a better approach. Go back to the old attribute system, but put the attribute ON THE TRAIT, not the impls. Then check it once, when we start the coherence check, and pass the boolean down to the impls.

2022-01-26 23:21 UTC, rust-timer commented
Queued 107640c50fe413527be6069e6f181c54734f1b21 with parent a7f375789bab1a4e4a291c963081a8ca7d2b6bd7, future [comparison URL](https://perf.rust-lang.org/compare.html?start=a7f375789bab1a4e4a291c963081a8ca7d2b6bd7&end=107640c50fe413527be6069e6f181c54734f1b21).

2022-01-27 01:57 UTC, rust-timer commented
Finished benchmarking commit (107640c50fe413527be6069e6f181c54734f1b21): [comparison url](https://perf.rust-lang.org/compare.html?start=a7f375789bab1a4e4a291c963081a8ca7d2b6bd7&end=107640c50fe413527be6069e6f181c54734f1b21).

**Summary**: This benchmark run shows 128 relevant regressions 😿 to instruction counts.
- Average relevant regression: 0.7%
- Average relevant improvement: -0.8%
- Largest regression in instruction counts: 1.9% on `incr-patched: add vec item` builds of `deep-vector check`

If you disagree with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).

Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR led to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf +perf-regression

2022-01-27 11:26 UTC, lqd commented
As we thought yesterday, memoizing the overlap mode should somewhat alleviate these new losses (and turn some of them into small improvements), in addition to regaining the losses from the previous negative impl PR (as the `stm32f4` benchmarks, which had been affected the most, look to be improved now). That'd be easy to try.

(Needless to mention, Niko's idea seems also worthwhile: coherence is hot, and the pairwise overlap checks already have supralinear scaling issues.)

2022-01-28 22:15 UTC, spastorino commented
@bors try @rust-timer queue

2022-01-28 22:15 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

2022-01-28 22:23 UTC, spastorino commented
@bors try @rust-timer queue

2022-01-28 22:23 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

2022-01-28 23:48 UTC, rust-timer commented
Queued b5dac1743636517402b355fd198ada684180f709 with parent 427eba2f0bacdeaebc992a78eb2889564de7d7cf, future [comparison URL](https://perf.rust-lang.org/compare.html?start=427eba2f0bacdeaebc992a78eb2889564de7d7cf&end=b5dac1743636517402b355fd198ada684180f709).

2022-01-29 03:59 UTC, rust-timer commented
Finished benchmarking commit (b5dac1743636517402b355fd198ada684180f709): [comparison url](https://perf.rust-lang.org/compare.html?start=427eba2f0bacdeaebc992a78eb2889564de7d7cf&end=b5dac1743636517402b355fd198ada684180f709).

**Summary**: This benchmark run did not return any relevant results.

If you disagree with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).

Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR led to changes in compiler perf.

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf -perf-regression

2022-01-29 11:38 UTC, nikomatsakis reviewed
This doesn't quite look how I expected. What I expected was that...

* there would be a feature gate for the use of negative impls in coherence
* there would be a `rustc_strict_coherence` attribute that can be placed on traits (gated by the `rustc_attrs` feature gate)

If the feature gate is enabled:

* When we do the overlap check (which appears to be done as part of [building the specialization tree](https://github.com/rust-lang/rust/blob/f8402169aaa12e7bbb9630796a8caec90a3055ca/compiler/rustc_trait_selection/src/traits/specialize/mod.rs#L255-L259)), we could check *once* whether the trait has the attribute:
    * We would pass that information ("is this a strict coherence trait?") into the call to `insert`, which is purely an optimization to avoid recomputing it.
    * `insert` can pass it to [`overlapping_impls`](https://github.com/rust-lang/rust/blob/f8402169aaa12e7bbb9630796a8caec90a3055ca/compiler/rustc_trait_selection/src/traits/specialize/specialization_graph.rs#L164) 
    * in the overlapping impls check:
    * if the attribute is present, we require that either the types are not unifyable or a negative impl is found
    * if the attribute is not present, we also accept the "legacy" overlap check

If the feature gate is disabled:

* We check for the "strict" attribute but report an error if we see it
* We ignore negative impls in `overlapping_impls`

2022-01-30 22:01 UTC, spastorino commented
@bors try @rust-timer queue

2022-01-30 22:01 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

2022-01-30 22:06 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/4999083402?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/240418a81de2bbded99885f79171ba3bf3d14a46/checks/4999083402/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
* highest error code: E0787
Found 503 error codes
Found 0 error codes with no tests
Done!
tidy error: /checkout/compiler/rustc_feature/src/active.rs:494: no tracking issue for feature with_negative_coherence
tidy error: /checkout/compiler/rustc_feature/src/active.rs:496: feature specialization is not sorted by feature name (should be between simd_ffi and with_negative_coherence)
tidy error: Found 1 features without a gate test.
Expected a gate test for the feature 'with_negative_coherence'.
Hint: create a failing test file named 'feature-gate-with_negative_coherence.rs'
      in the 'ui' test suite, with its failures due to
      missing usage of `#![feature(with_negative_coherence)]`.
Hint: If you already have such a test and don't want to rename it,
      you can also add a // gate-test-with_negative_coherence line to the test file.
some tidy checks failed


command did not execute successfully: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/rust-tidy" "/checkout" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "/checkout/obj/build" "16"


Build completed unsuccessfully in 0:00:12
```

</details>

2022-01-30 23:18 UTC, rust-timer commented
Queued 07719c4f11b6c559d462b1e46ba138537cb47505 with parent 8c7f2bf44f7fafaa4546814e54add786429e5f76, future [comparison URL](https://perf.rust-lang.org/compare.html?start=8c7f2bf44f7fafaa4546814e54add786429e5f76&end=07719c4f11b6c559d462b1e46ba138537cb47505).

2022-01-31 07:44 UTC, rust-timer commented
Finished benchmarking commit (07719c4f11b6c559d462b1e46ba138537cb47505): [comparison url](https://perf.rust-lang.org/compare.html?start=8c7f2bf44f7fafaa4546814e54add786429e5f76&end=07719c4f11b6c559d462b1e46ba138537cb47505).

**Summary**: This benchmark run did not return any relevant results. 4 results were found to be statistically significant but too small to be relevant.

If you disagree with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).

Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR led to changes in compiler perf.

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf -perf-regression

2022-01-31 13:34 UTC, nikomatsakis reviewed
r=me but one possible change would be to move `overlap_mode` out so it is not stored as a field; the idea is that it is only used during construction and doesn't matter afterwards, so it doesn't have to be a field

2022-01-31 13:34 UTC, nikomatsakis commented on compiler/rustc_middle/src/traits/specialization_graph.rs
> +            overlap_mode: OverlapMode::Stable,
I...hmm. I don't know that I would store this as a field, but I guess it's also ok to do so.

2022-01-31 13:34 UTC, nikomatsakis commented on compiler/rustc_trait_selection/src/traits/specialize/specialization_graph.rs
> +                self.overlap_mode,
... I was expecting this to be a parameter to the function, I think. Maybe that's annoying to do?

2022-01-31 13:34 UTC, nikomatsakis commented
Here is a test we could use ---

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=16337df308de4a32e8117dfe8b9521c3

Without the feature gate, this gets an error.

With the feature gate, I think it should pass, because we have `impl !DerefMut for &T`

2022-01-31 14:53 UTC, nikomatsakis approved these changes
r=me

2022-01-31 14:54 UTC, nikomatsakis commented
@bors r+

2022-01-31 20:44 UTC, merged

2022-02-01 02:10 UTC, rust-timer commented
Finished benchmarking commit (498eeb72f590e518e19746b346be53713689e207): [comparison url](https://perf.rust-lang.org/compare.html?start=24b8bb13bff98bb747cd403b86596af43aceee78&end=498eeb72f590e518e19746b346be53713689e207).

**Summary**: This benchmark run did not return any relevant results. 17 results were found to be statistically significant but too small to be relevant.

If you disagree with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).



@rustbot label: -perf-regression