Fix ret > 1 bound if shadowed by const
rust-lang/rust pull request #93593
Opened 2022-02-02 16:45 UTC by JulianKnodt

Prior to a change, it would only look at types in bounds. When it started looking for consts,
shadowing type variables with a const would cause an ICE, so now defer looking at consts only if
there are no types present.

cc @compiler-errors
Should Fix #93553

2022-02-02 16:45 UTC, rust-highfive commented
r? @matthewjasper

(rust-highfive has picked a reviewer for you, use r? to override)

2022-02-02 16:46 UTC, JulianKnodt commented on compiler/rustc_typeck/src/astconv/mod.rs
> +
This is the main fix, the rest should make it more carefully stick to logic prior the change.

2022-02-02 21:42 UTC, compiler-errors commented
Can you verify that the compiler doesn't ICE in situations like:

```rust
trait Baz {
  const Bar: usize;
  const Qux: Self::Bar;
}
```

2022-02-03 01:45 UTC, JulianKnodt commented
I don't think it should ice in that case since there's no shadowing and no name overlaps, but will add a test in

2022-02-03 03:45 UTC, JulianKnodt commented
oh it does ice, I'll look into it a bit further

2022-02-03 03:48 UTC, compiler-errors commented
I think the stack trace points to an `.expect` so you can find where it ICEs. I think it's in a method that resolves a path to a ty, maybe you want to check if it resolves to a const instead and emit an error. Maybe something like this:

```rust
trait Baz {
  const Bar: usize;
  const Qux: Self::Bar;
//           ^ Expected type, found const
}
```

2022-02-03 04:09 UTC, JulianKnodt commented
yuh, i'm not sure if the best way to fix it is to turn the expect into an actual error, or handle it earlier, for now I can just turn it into an error and if the reviewer knows better I'll update

2022-02-03 14:42 UTC, oli-obk requested changes

2022-02-03 14:42 UTC, oli-obk commented on compiler/rustc_typeck/src/astconv/mod.rs
> +            let msg = format!("found associated const {assoc_ident} when type was expected");
```suggestion
            let msg = format!("found associated const `{assoc_ident}` when type was expected");
```

2022-02-03 14:42 UTC, oli-obk commented on compiler/rustc_typeck/src/astconv/mod.rs
> +            || tcx.associated_items(candidate.def_id()).filter_by_name_unhygienic(assoc_ident.name);
pass in the kind you're looking for as an argument and include the `find` part in the closure, too.

2022-02-03 14:42 UTC, oli-obk commented on compiler/rustc_typeck/src/astconv/mod.rs
> +        let next_cand = if is_ty { matching_candidates.next() } else { const_candidates.next() };
instead of having this `is_ty` variable, return `next_cand` directly from the match where you return `bound`.

2022-02-03 14:42 UTC, oli-obk commented on compiler/rustc_typeck/src/astconv/mod.rs
> +            Some(bound2) => {
please revert the `if let` -> `match` change and resulting indentation changes and squash them away.

2022-02-03 14:43 UTC, oli-obk commented
r? @oli-obk

2022-02-03 15:44 UTC, oli-obk commented
@bors r+

2022-02-04 17:40 UTC, merged