Add some known GAT bugs as tests
rust-lang/rust pull request #93757
Opened 2022-02-08 02:42 UTC by jackh726

In the spirit of rust-lang/compiler-team#476

These tests are marked as "check-fail", but also commented with "this should pass". This many of the open GAT issues that are accepted bugs.

r? @nikomatsakis

2022-02-08 02:55 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/5103288402?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/9ec487bcd83c729bcf290b8ad8a70704c9660a5f/checks/5103288402/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
tidy: Skipping binary file check, read-only filesystem
Checking which error codes lack tests...
* 629 error codes
* highest error code: E0787
tidy error: /checkout/src/test/ui/generic-associated-types/bugs/issue-87748.rs:16: trailing whitespace
tidy error: /checkout/src/test/ui/generic-associated-types/bugs/issue-87803.rs:3: line longer than 100 chars
tidy error: /checkout/src/test/ui/generic-associated-types/bugs/issue-87803.rs:10: trailing whitespace
tidy error: /checkout/src/test/ui/generic-associated-types/bugs/issue-87803.rs:19: trailing whitespace
Found 0 error codes with no tests
Done!
* 363 features
some tidy checks failed
```

</details>

2022-02-09 15:15 UTC, nikomatsakis commented
@bors rollup+ r+

2022-02-09 17:19 UTC, jackh726 commented
Need to rebless the tests with TAITs (or maybe remove them if they aren't bugs anymore), since those outputs have changed after the lazy impl trait PR landed.

2022-02-12 04:47 UTC, dtolnay requested changes
This failed in the rollup: https://github.com/rust-lang/rust/pull/93929#issuecomment-1036965155.

I saw some failures in this PR's status checks too. Not sure why those didn't get posted as a comment by @rust-log-analyzer.

```console
failures:
    [ui] ui/generic-associated-types/bugs/issue-86218.rs
    [ui] ui/generic-associated-types/bugs/issue-87803.rs
    [ui] ui/generic-associated-types/bugs/issue-89008.rs
```

2022-02-12 04:47 UTC, dtolnay commented on src/test/ui/generic-associated-types/bugs/issue-87803.stderr
> +  --> $DIR/issue-87803.rs:20:12
`fn scan` is on line 21, not line 20.

```suggestion
  --> $DIR/issue-87803.rs:21:12
```

2022-02-12 05:56 UTC, jackh726 commented
@dtolnay test failures from CI were caused by the lazy TAIT PR, which has been reverted

2022-02-12 05:57 UTC, jackh726 commented
@bors r=nikomatsakis

2022-02-12 14:01 UTC, merged