Fix `let _: ty = expr` subtyping error
rust-lang/rust pull request #93856
Opened 2022-02-10 12:41 UTC by lcnr

```rust
fn uwu<'b>(func: for<'a> fn(&'a ())) {
    let _: fn(&'b ()) = func;
}
```
Placeholder patterns `_` end up getting converted to `AscribeUserType(_1, +, UserTypeProjection { base: UserType(1), projs: [] })` in the mir. This type ascription is covariant.

In `fn check_user_type_annotations` we previously checked the type annotations without considering variance, breaking the above example. As lifetimes in the `inferred_type` get erased they don't have any relation to other lifetimes in the body, so
```rust
struct Foo<'a>(&'a ());
fn uwu<'a>(f: Foo<'static>) {
    let _: Foo<'a> = f;
}
```
does not error because `'static` in the `inferred_ty` gets erased and then replaced with an unbound inference variable.
Note that the following example wouldn't have any issues here either way as there is an implicit reborrow before the assignment.
```rust
fn uwu<'a>(v: &'static i32) {
    let _: &'a i32 = v;
}
```

2022-02-10 12:41 UTC, rust-highfive commented
r? @cjgillot

(rust-highfive has picked a reviewer for you, use r? to override)

2022-02-10 12:42 UTC, lcnr commented
r? @rust-lang/wg-compiler-nll

2022-02-10 12:52 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/5140870569?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/c928e55931a3da37f9be76729ed2bc976618f476/checks/5140870569/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
* highest error code: E0787
Found 503 error codes
Found 0 error codes with no tests
Done!
tidy error: /checkout/src/test/ui/hr-subtype/placeholder-pattern.rs: missing trailing newline
tidy error: /checkout/src/test/ui/hr-subtype/placeholder-pattern-fail.rs:6: trailing whitespace
tidy error: /checkout/src/test/ui/hr-subtype/placeholder-pattern-fail.rs: missing trailing newline
some tidy checks failed
Build completed unsuccessfully in 0:00:12
```

</details>

2022-02-10 13:00 UTC, lcnr commented on compiler/rustc_borrowck/src/type_check/mod.rs
> +                    if let Err(terr) = self.relate_types(
considering that `ty` and `inferred_ty` now differ, do we have to check for well formedness of `ty` as well?

2022-02-10 13:13 UTC, lcnr commented on compiler/rustc_borrowck/src/type_check/mod.rs
>                  UserType::Ty(mut ty) => {
this is probably also broken for `UserType::TypeOf` :thinking: tbh I don't really want variance here

2022-02-15 16:13 UTC, nikomatsakis requested changes

2022-02-15 16:13 UTC, nikomatsakis commented on src/test/ui/hr-subtype/placeholder-pattern.rs
> +    let _: fn(&'c (), &'c ()) = f;
I see, but this one doesn't.

2022-02-15 16:13 UTC, nikomatsakis commented on compiler/rustc_middle/src/ty/context.rs
> +    pub variance: Variance,
It's rather unclear to me what variance means here. I confess to have often "overloaded" it as a way to carry the expected relation between two types, but it seems necessary to comment the ordering here.

If you have "covariant", does that mean that the "inferred type" needs to be a subtype of the "user type"? etc

2022-02-15 16:13 UTC, nikomatsakis commented on compiler/rustc_mir_build/src/build/matches/mod.rs
> +                ascription.variance,
So the bug was that we were losing track of the variance here?

2022-02-15 16:13 UTC, nikomatsakis commented on compiler/rustc_borrowck/src/type_check/mod.rs
>                          ConstraintCategory::BoringNoLocation,
I'm trying to remember why we chose to use "type equality" here. I have a vague memory that there was a reason, but it seems there aren't any failing tests, at least.

2022-02-15 16:13 UTC, nikomatsakis commented
r? @nikomatsakis

2022-02-15 16:14 UTC, nikomatsakis commented
@bors rollup=never

2022-02-18 12:46 UTC, lcnr commented
@nikomatsakis this is now ready for review.

I think we always `eq` the `inferred_ty` with some other type while typechecking the mir, and that other type should be checked to be wf. So I don't think that we also have to emit a wf predicate for `inferred_ty` here.

2022-02-18 14:11 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/5248499645?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/8fe1b2c8de67ebd5afe90db238c49791ec330dec/checks/5248499645/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
.......i............................................................................................ 6400/12649
........................................................................i........................... 6500/12649
........................ii.ii........i...i.......................................................... 6600/12649
.................................................................................................... 6700/12649
...........i....i..F.....................................i................i.............i........... 6800/12649
............................................i....................................................... 7000/12649
.................................................................................................... 7100/12649
..................................................................ii................................ 7200/12649
ii.........................................................i........................................ 7300/12649
---
............................................iii..................................................... 12600/12649
.................................................
failures:

---- [ui] ui/lifetimes/re-empty-in-error.rs stdout ----


1 error[E0477]: the type `&'b ()` does not fulfill the required lifetime
2   --> $DIR/re-empty-in-error.rs:8:5
3    |
- LL |     foo(&10); 
+ LL |     foo(&10);
6    |
7 note: type must outlive the empty lifetime as required by this binding



The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lifetimes/re-empty-in-error/re-empty-in-error.stderr
To only update this specific test, also pass `--test-args lifetimes/re-empty-in-error.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/lifetimes/re-empty-in-error.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lifetimes/re-empty-in-error" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/lifetimes/re-empty-in-error/auxiliary"
Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
------------------------------------------

------------------------------------------
------------------------------------------
stderr:
------------------------------------------
error[E0477]: the type `&'b ()` does not fulfill the required lifetime
  --> /checkout/src/test/ui/lifetimes/re-empty-in-error.rs:8:5
LL |     foo(&10);
   |     ^^^
   |
note: type must outlive the empty lifetime as required by this binding
note: type must outlive the empty lifetime as required by this binding
  --> /checkout/src/test/ui/lifetimes/re-empty-in-error.rs:3:47
   |
LL | fn foo<'a>(_a: &'a u32) where for<'b> &'b (): 'a {

error: aborting due to previous error

For more information about this error, try `rustc --explain E0477`.
```

</details>

2022-02-18 15:05 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/5249207715?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/c3a91a83bab73365b0cfc52849c8150afc6de627/checks/5249207715/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Suite(test::src/test/mir-opt) not skipped for "bootstrap::test::MirOpt" -- not in [src/tools/tidy]
Check compiletest suite=mir-opt mode=mir-opt (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 166 tests
...F.......F........................i..............................................i..............F. 100/166
.........................F........i...............................
Some tests failed in compiletest suite=mir-opt mode=mir-opt host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu

---- [mir-opt] mir-opt/basic_assignment.rs stdout ----
---- [mir-opt] mir-opt/basic_assignment.rs stdout ----
37         StorageLive(_4);                 // scope 2 at $DIR/basic_assignment.rs:18:9: 18:15
38         _4 = Option::<Box<u32>>::None;   // scope 2 at $DIR/basic_assignment.rs:18:36: 18:40
39         FakeRead(ForLet(None), _4);      // scope 2 at $DIR/basic_assignment.rs:18:9: 18:15
-         AscribeUserType(_4, o, UserTypeProjection { base: UserType(1), projs: [] }); // scope 2 at $DIR/basic_assignment.rs:18:17: 18:33
+         AscribeUserType(_4, UserTypeProjection { base: UserType(1), projs: [] }); // scope 2 at $DIR/basic_assignment.rs:18:17: 18:33
41         StorageLive(_5);                 // scope 3 at $DIR/basic_assignment.rs:19:9: 19:15
42         StorageLive(_6);                 // scope 4 at $DIR/basic_assignment.rs:23:14: 23:20
43         _6 = move _4;                    // scope 4 at $DIR/basic_assignment.rs:23:14: 23:20

thread '[mir-opt] mir-opt/basic_assignment.rs' panicked at 'Actual MIR output differs from expected MIR output /checkout/src/test/mir-opt/basic_assignment.main.SimplifyCfg-initial.after.mir', src/tools/compiletest/src/runtest.rs:3375:25

---- [mir-opt] mir-opt/address-of.rs stdout ----
---- [mir-opt] mir-opt/address-of.rs stdout ----
139         StorageLive(_5);                 // scope 2 at $DIR/address-of.rs:7:5: 7:18
140         StorageLive(_6);                 // scope 2 at $DIR/address-of.rs:7:5: 7:18
141         _6 = &raw const (*_1);           // scope 2 at $DIR/address-of.rs:7:5: 7:6
-         AscribeUserType(_6, o, UserTypeProjection { base: UserType(0), projs: [] }); // scope 2 at $DIR/address-of.rs:7:5: 7:18
+         AscribeUserType(_6, UserTypeProjection { base: UserType(0), projs: [] }); // scope 2 at $DIR/address-of.rs:7:5: 7:18
143         _5 = _6;                         // scope 2 at $DIR/address-of.rs:7:5: 7:18
144         StorageDead(_6);                 // scope 2 at $DIR/address-of.rs:7:18: 7:19
145         StorageDead(_5);                 // scope 2 at $DIR/address-of.rs:7:18: 7:19

152         _10 = &raw const (*_1);          // scope 2 at $DIR/address-of.rs:9:5: 9:6
153         _9 = move _10 as *const dyn std::marker::Send (Pointer(Unsize)); // scope 2 at $DIR/address-of.rs:9:5: 9:6
154         StorageDead(_10);                // scope 2 at $DIR/address-of.rs:9:5: 9:6
-         AscribeUserType(_9, o, UserTypeProjection { base: UserType(1), projs: [] }); // scope 2 at $DIR/address-of.rs:9:5: 9:25
+         AscribeUserType(_9, UserTypeProjection { base: UserType(1), projs: [] }); // scope 2 at $DIR/address-of.rs:9:5: 9:25
156         _8 = _9;                         // scope 2 at $DIR/address-of.rs:9:5: 9:25
157         StorageDead(_9);                 // scope 2 at $DIR/address-of.rs:9:25: 9:26
158         StorageDead(_8);                 // scope 2 at $DIR/address-of.rs:9:25: 9:26

171         StorageLive(_15);                // scope 2 at $DIR/address-of.rs:13:9: 13:10
172         _15 = &raw const (*_1);          // scope 2 at $DIR/address-of.rs:13:23: 13:24
173         FakeRead(ForLet(None), _15);     // scope 2 at $DIR/address-of.rs:13:9: 13:10
-         AscribeUserType(_15, o, UserTypeProjection { base: UserType(3), projs: [] }); // scope 2 at $DIR/address-of.rs:13:12: 13:20
+         AscribeUserType(_15, UserTypeProjection { base: UserType(3), projs: [] }); // scope 2 at $DIR/address-of.rs:13:12: 13:20
175         StorageLive(_16);                // scope 3 at $DIR/address-of.rs:14:9: 14:10
176         _16 = &raw const (*_1);          // scope 3 at $DIR/address-of.rs:14:31: 14:32
177         FakeRead(ForLet(None), _16);     // scope 3 at $DIR/address-of.rs:14:9: 14:10

-         AscribeUserType(_16, o, UserTypeProjection { base: UserType(5), projs: [] }); // scope 3 at $DIR/address-of.rs:14:12: 14:28
+         AscribeUserType(_16, UserTypeProjection { base: UserType(5), projs: [] }); // scope 3 at $DIR/address-of.rs:14:12: 14:28
179         StorageLive(_17);                // scope 4 at $DIR/address-of.rs:15:9: 15:10
180         StorageLive(_18);                // scope 4 at $DIR/address-of.rs:15:30: 15:31
181         _18 = &raw const (*_1);          // scope 4 at $DIR/address-of.rs:15:30: 15:31

182         _17 = move _18 as *const dyn std::marker::Send (Pointer(Unsize)); // scope 4 at $DIR/address-of.rs:15:30: 15:31
183         StorageDead(_18);                // scope 4 at $DIR/address-of.rs:15:30: 15:31
184         FakeRead(ForLet(None), _17);     // scope 4 at $DIR/address-of.rs:15:9: 15:10
-         AscribeUserType(_17, o, UserTypeProjection { base: UserType(7), projs: [] }); // scope 4 at $DIR/address-of.rs:15:12: 15:27
+         AscribeUserType(_17, UserTypeProjection { base: UserType(7), projs: [] }); // scope 4 at $DIR/address-of.rs:15:12: 15:27
186         StorageLive(_19);                // scope 5 at $DIR/address-of.rs:16:9: 16:10
187         StorageLive(_20);                // scope 5 at $DIR/address-of.rs:16:27: 16:28
188         _20 = &raw const (*_1);          // scope 5 at $DIR/address-of.rs:16:27: 16:28

189         _19 = move _20 as *const [i32] (Pointer(Unsize)); // scope 5 at $DIR/address-of.rs:16:27: 16:28
190         StorageDead(_20);                // scope 5 at $DIR/address-of.rs:16:27: 16:28
191         FakeRead(ForLet(None), _19);     // scope 5 at $DIR/address-of.rs:16:9: 16:10
-         AscribeUserType(_19, o, UserTypeProjection { base: UserType(9), projs: [] }); // scope 5 at $DIR/address-of.rs:16:12: 16:24
+         AscribeUserType(_19, UserTypeProjection { base: UserType(9), projs: [] }); // scope 5 at $DIR/address-of.rs:16:12: 16:24
193         StorageLive(_21);                // scope 6 at $DIR/address-of.rs:18:5: 18:18
194         StorageLive(_22);                // scope 6 at $DIR/address-of.rs:18:5: 18:18
195         _22 = &raw const (*_3);          // scope 6 at $DIR/address-of.rs:18:5: 18:6

-         AscribeUserType(_22, o, UserTypeProjection { base: UserType(10), projs: [] }); // scope 6 at $DIR/address-of.rs:18:5: 18:18
+         AscribeUserType(_22, UserTypeProjection { base: UserType(10), projs: [] }); // scope 6 at $DIR/address-of.rs:18:5: 18:18
197         _21 = _22;                       // scope 6 at $DIR/address-of.rs:18:5: 18:18
198         StorageDead(_22);                // scope 6 at $DIR/address-of.rs:18:18: 18:19
199         StorageDead(_21);                // scope 6 at $DIR/address-of.rs:18:18: 18:19

206         _26 = &raw const (*_3);          // scope 6 at $DIR/address-of.rs:20:5: 20:6
207         _25 = move _26 as *const dyn std::marker::Send (Pointer(Unsize)); // scope 6 at $DIR/address-of.rs:20:5: 20:6
208         StorageDead(_26);                // scope 6 at $DIR/address-of.rs:20:5: 20:6
-         AscribeUserType(_25, o, UserTypeProjection { base: UserType(11), projs: [] }); // scope 6 at $DIR/address-of.rs:20:5: 20:25
+         AscribeUserType(_25, UserTypeProjection { base: UserType(11), projs: [] }); // scope 6 at $DIR/address-of.rs:20:5: 20:25
210         _24 = _25;                       // scope 6 at $DIR/address-of.rs:20:5: 20:25 [...]

2022-03-03 14:52 UTC, nikomatsakis requested changes
r=me with fresh comments + tests

2022-03-03 14:52 UTC, nikomatsakis commented on compiler/rustc_middle/src/ty/context.rs
> +    /// other uses of `inferred_ty` should be invariant.
It would be good to have a comment explaining:

```rust
let x: T = ...; // invariant
let _: T = ...; // covariant
```

2022-03-03 14:52 UTC, nikomatsakis commented on src/test/ui/hr-subtype/placeholder-pattern.rs
> +    let _: fn(&'c (), &'c ()) = f;
can we add a test like this...

```rust
let (x, _): (u32, fn(...)) = (22, f);
```

...to cover the case where the pattern has some bindings but not all parts are bound (we could add a few more variants too, like `(_, x)` and `(x, y)` and `(..)`.

2022-03-14 21:44 UTC, nikomatsakis commented
@rustbot author

2022-04-24 20:35 UTC, Dylan-DPC commented
@lcnr whats the status on this?

2022-04-25 05:54 UTC, lcnr commented
this needs a bigger change to the mir, intend to continue this work at some point in the near future. Can close this PR for now

2022-04-25 05:54 UTC, closed without merging