Add `Destructible` trait for replacing `~const Drop` bounds in the future
rust-lang/rust pull request #94901
Opened 2022-03-13 04:11 UTC by fee1-dead

r? @oli-obk 

Completely switching to `~const Destructible` would be rather complicated, so it seems best to add it for now and wait for it to be backported to beta in the next release.

The rationale is to prevent complications such as #92149 and #94803 by introducing an entirely new trait. And `~const Destructible` reads a bit better than `~const Drop`. Name Bikesheddable.

2022-03-13 04:14 UTC, fee1-dead commented
wait, even if I just add this as a lang item now it wouldn't work because the logic for handling them would still need to be backported... I guess we could go with a compatible approach by ignoring `~const Drop` first and do something like `~const Drop + ~const Destructible`

2022-03-13 11:17 UTC, oli-obk commented
You could implement `Destructible` for all T on bootstrap

2022-03-13 11:18 UTC, fee1-dead commented
yeah that works, which means we could land this now and I will implement the logic later

2022-03-13 12:42 UTC, shamatar commented
If the purpose of this trait to mark the types that can be trivially dropped for the purposes of CTFE, shouldn't it be "auto" trait or some other special "const auto" trait, or may be simultaneously marker trait (never manually implementable, but not sure about it)?

2022-03-13 12:50 UTC, fee1-dead commented
Yeah if we can implement it for all `T` in bootstrap it wouldn't make sense to just land this now. I will prepare an implementation when I have time.

2022-03-14 14:05 UTC, fmease commented
Minor bikeshedding: In a lot of cases, trait names are imperative forms of verbs (`Copy`, `Send`, `Unsize`, `Borrow`, `Display`, `CoerceUnsized`) instead of adjectives with ending in _-able_ or _-ible_. The latter is quite discouraged in Rust afaik. I suggest renaming `Destructible` to `Destruct` while possible.

2022-03-15 02:36 UTC, clarfonthey commented
Is there ever going to be a case where types don't implement `Destructible`, and only that they might not be const-destructible?

2022-03-15 05:16 UTC, fee1-dead commented
Don't think so. The rationale behind the use of the word destructible is as another word for drop, where any type can be dropped/destructed in runtime, but not in compile time.

2022-03-17 03:01 UTC, clarfonthey commented
My main concern is that it seems like this is just a renamed version of `~const Drop`. Like, I get that it will internally work differently, but I fail to see the main differences for an end user, other than confusion.

2022-03-18 10:15 UTC, fee1-dead commented
`~const Drop` is as confusing as any other names. If we use another trait we can write the documentation to be specifically about dropping a type in compile time and say that it is implemented non-const-ly for all `T`. The main rationale is to prevent any more special casing to make it not conflict with `: Drop` bounds.

2022-03-21 06:03 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/5622610741?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/a8b096061285dddf6d9638588a975b49da6d723a/checks/5622610741/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
* highest error code: E0787
Found 504 error codes
Found 0 error(s) in error codes
Done!
tidy error: /checkout/src/test/ui/rfc-2632-const-trait-impl/const-drop-bound.rs:17: line longer than 100 chars
some tidy checks failed
Build completed unsuccessfully in 0:00:10
```

</details>

2022-03-21 13:24 UTC, oli-obk requested changes

2022-03-21 21:23 UTC, fee1-dead commented on compiler/rustc_trait_selection/src/traits/select/confirmation.rs
> +        // This is copied from confirm_impl_candidate but remaps the predicate to `~const Drop` beforehand.
So.. basically the nested obligation causes must be correctly `~const Destruct`, but we want the obligation that is matched to actually be `~const Drop` such that `match_impl` wouldn't fail.

2022-03-23 16:53 UTC, merged

2022-03-23 18:28 UTC, rust-timer commented
Finished benchmarking commit (92804455704cc59d6d8272faf72f442c6125d395): [comparison url](https://perf.rust-lang.org/compare.html?start=c99b42cf14014987a147918fac2ad3d3290b257e&end=92804455704cc59d6d8272faf72f442c6125d395).

**Summary**: This benchmark run did not return any relevant results.

If you disagree with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).



@rustbot label: -perf-regression