Stabilize const versions of ptr::slice_from_raw_parts and slice::from_raw_parts.
rust-lang/rust pull request #94946
Opened 2022-03-15 00:51 UTC by tobz

This doesn't close #67456 as there's still the mutable variants to consider, but the immutable variants should seemingly be fine to stabilize.

Apologies if this stabilization PR is lacking something: it wasn't immediately clear if there was a different process for partial stabilizations.

2022-03-15 00:51 UTC, rust-highfive commented
Some changes occured to rustc_codegen_cranelift

cc @bjorn3

2022-03-15 00:51 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @dtolnay (or someone else) soon.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2022-03-15 00:51 UTC, tobz commented
@rustbot modify labels: +T-libs-api

2022-03-15 00:55 UTC, tobz commented on library/core/src/slice/raw.rs
> +#[rustc_const_stable(since = "1.61.0")]
Admittedly, this is a change I'm not 100% sure on: its callers are stable in a non-const context, and yet it was marked `unstable`.  I have no real clue what `unstable` even implies for a non-exported function, so this was mostly a no-thinking-involved mechanical change.

2022-03-15 01:39 UTC, tobz commented
Looking at the CI failure, it looks like this actually unwinds a bit to depending on `ptr::from_raw_parts` being const-stable, which makes sense on a surface level but it also seems to power non-const-fns, despite also being marked `unstable`?

It's not clear to me if it can also be made const stable safely? This is probably one of those "wait for help" scenarios, at this point. :)

2022-03-15 02:00 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/5546875893?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/f5975e56fef4a861e8e06d3bc0f33e2281637917/checks/5546875893/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling memchr v2.4.1
   Compiling std v0.0.0 (/checkout/library/std)
   Compiling compiler_builtins v0.1.70
   Compiling unwind v0.0.0 (/checkout/library/unwind)
error: `ptr::metadata::from_raw_parts` is not yet stable as a const fn
    |
260 |     from_raw_parts(data.cast(), len)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
```

</details>

2022-03-18 20:41 UTC, dtolnay reviewed
Anything used in the implementation of a public stable const fn needs to be marked rustc_const_stable.

```console
error: `ptr::metadata::from_raw_parts` is not yet stable as a const fn
    |
260 |     from_raw_parts(data.cast(), len)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

https://github.com/rust-lang/rust/blob/f5975e56fef4a861e8e06d3bc0f33e2281637917/library/core/src/ptr/metadata.rs#L108-L110

2022-03-19 15:11 UTC, tobz commented
> Anything used in the implementation of a public stable const fn needs to be marked rustc_const_stable.

That's reasonable.  Is that something we/I can do in this case?  Admittedly, it's not clear to me.

2022-03-27 05:35 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/5707045425?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/96951c90434917d4456bb226fb607b8844eff32f/checks/5707045425/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling memchr v2.4.1
   Compiling std v0.0.0 (/checkout/library/std)
   Compiling compiler_builtins v0.1.70
   Compiling unwind v0.0.0 (/checkout/library/unwind)
error: `const_eval_select` is not yet stable as a const fn
    |
    |
157 |         crate::intrinsics::const_eval_select((data,), noop, rt_check);
    |
    = help: const-stable functions can only call other const-stable functions

error: could not compile `core` due to previous error
```

</details>

2022-04-16 00:14 UTC, dtolnay requested changes
Yes, you will need to add rustc_const_stable attributes for all the private functions getting called by these public functions. Whether it's something we can do depends on what functions end up needing to get rustc_const_stable added. That would be reviewed after the changes are made.

2022-05-07 23:42 UTC, JohnCSimon commented
Ping from triage:
@tobz - can you please address the conflicts and build failures?

FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

2022-05-08 01:12 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/6337868995?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/2bd748d934f23ff93c36b25f6fd12d9c592a5639/checks/6337868995/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling unwind v0.0.0 (/checkout/library/unwind)
error[E0711]: feature `ptr_metadata` is declared stable, but was previously declared unstable
   --> library/core/src/ptr/metadata.rs:108:1
    |
108 | #[rustc_const_stable(feature = "ptr_metadata", since = "1.61.0")]

error[E0711]: feature `const_slice_from_raw_parts` is declared unstable, but was previously declared stable
   --> library/core/src/ptr/mod.rs:714:1
    |
    |
714 | #[rustc_const_unstable(feature = "const_slice_from_raw_parts", issue = "67456")]

error[E0711]: feature `const_slice_from_raw_parts` is declared unstable, but was previously declared stable
   --> library/core/src/slice/raw.rs:132:1
    |
    |
132 | #[rustc_const_unstable(feature = "const_slice_from_raw_parts", issue = "67456")]

error: the feature `const_slice_from_raw_parts` has been stable since 1.61.0 and no longer requires an attribute to enable
   --> library/core/src/lib.rs:137:12
    |
    |
137 | #![feature(const_slice_from_raw_parts)]
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `-D stable-features` implied by `-D warnings`
error: could not compile `core` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
Build completed unsuccessfully in 0:00:07
```

</details>

2022-05-08 01:17 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/6337937411?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/d4a95abb4eb4c038b69d9d031a988505761ddc7c/checks/6337937411/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling unwind v0.0.0 (/checkout/library/unwind)
error[E0711]: feature `ptr_metadata` is declared stable, but was previously declared unstable
   --> library/core/src/ptr/metadata.rs:108:1
    |
108 | #[rustc_const_stable(feature = "ptr_metadata", since = "1.61.0")]

error: could not compile `core` due to previous error
Build completed unsuccessfully in 0:00:07
```

</details>

2022-05-08 01:21 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/6337953379?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/658a36add00a4296e4317c6f07f1a67a3db5d164/checks/6337953379/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling unwind v0.0.0 (/checkout/library/unwind)
error[E0711]: feature `ptr_metadata` is declared stable, but was previously declared unstable
   --> library/core/src/ptr/metadata.rs:108:1
    |
108 | #[rustc_const_stable(feature = "ptr_metadata", since = "1.62.0")]

error: could not compile `core` due to previous error
Build completed unsuccessfully in 0:01:25
```

</details>

2022-05-08 02:14 UTC, tobz commented
I'm going to close this PR for now.

Working through adjusting the const stability for the transitive functions landed me at having to do so for the `ptr_metadata` feature.. which is obviously not ready to be const stable yet, and so spending any more time -- either me making the PR pass or someone reviewing it only to also coming to the same conclusion -- wouldn't make much sense.

2022-05-08 02:14 UTC, closed without merging

2022-05-21 08:25 UTC, xfix commented
Is there a problem with marking [`std::ptr::from_raw_parts`](https://doc.rust-lang.org/stable/std/ptr/fn.from_raw_parts.html) as const stable? Note that marking a function as const stable doesn't mean having to stabilize it, see https://rustc-dev-guide.rust-lang.org/stability.html#rustc_const_stable.

> This attribute can make sense even on an `unstable` function, if that function is called from another `rustc_const_stable` function.