Infer on impl for trait
rust-lang/rust pull request #95395
Opened 2022-03-28 02:46 UTC by compiler-errors

Provides a structured suggestion for when `_` is present in the function signature for `impl Trait for Ty`, using the substitutions from the trait to compute the exact type.

Fixes #95097

2022-03-28 02:46 UTC, rust-highfive commented
r? @wesleywiser

(rust-highfive has picked a reviewer for you, use r? to override)

2022-04-21 14:28 UTC, compiler-errors commented
r? rust-lang/compiler

2022-04-22 12:47 UTC, michaelwoerister commented
r? rust-lang/diagnostics

2022-04-23 09:41 UTC, oli-obk requested changes
Just some nits. r=me with those resolved

2022-04-23 09:41 UTC, oli-obk commented on compiler/rustc_typeck/src/astconv/mod.rs
> +                    if infer_replacements.len() > 1 { "s" } else { "" }
We do have some pluralizer helpers. If they don't support `type` yet, add it and use it here

2022-04-23 09:41 UTC, oli-obk commented on compiler/rustc_typeck/src/astconv/mod.rs
> +                hir.get(hir.get_parent_node(fn_hir_id)) else { return None };
This shouldbe a bug if it returns none. Use `bug!` in that case.

2022-04-24 21:51 UTC, compiler-errors commented
rebased and comments addressed.

@bors r=oli-obk

2022-04-25 00:40 UTC, merged

2022-04-25 01:01 UTC, scottmcm commented
Thanks, @compiler-errors !  This looks great; I'm excited to try it.