Make def names and HIR names consistent.
rust-lang/rust pull request #95435
Opened 2022-03-29 16:33 UTC by cjgillot

The name in the `DefKey` is interned to create the `DefId`, so it does not
require any query to access.  This can be leveraged to avoid a few useless
HIR accesses for names.

~In order to achieve that, generic parameters created from universal
impl-trait are given the pretty-printed ast as a name, instead of
`{{opaque}}`.~

~Drive-by: the `TyCtxt::opt_item_name` used a dummy span for non-local
definitions.  We have access to `def_ident_span`, so we use it.~

2022-03-29 16:33 UTC, rust-highfive commented
r? @estebank

(rust-highfive has picked a reviewer for you, use r? to override)

2022-03-29 17:06 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/5741115791?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/79010104f47e9a435ef49a7f4b40f0f84a56dda5/checks/5741115791/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain

---- [ui] ui/issues/issue-21763.rs stdout ----
diff of stderr:

8    = note: required because it appears within the type `(Rc<()>, Rc<()>)`
9    = note: required because of the requirements on the impl of `Send` for `hashbrown::raw::RawTable<(Rc<()>, Rc<()>)>`
10 note: required because it appears within the type `hashbrown::map::HashMap<Rc<()>, Rc<()>, RandomState>`
-   --> /home/k1000/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.12.0/src/map.rs:188:12
12    |
12    |
13 LL | pub struct HashMap<K, V, S = DefaultHashBuilder, A: Allocator + Clone = Global> {


The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-21763/issue-21763.stderr
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-21763/issue-21763.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args issues/issue-21763.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/issues/issue-21763.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-21763" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-21763/auxiliary"
stdout: none
--- stderr -------------------------------
error[E0277]: `Rc<()>` cannot be sent between threads safely
Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
   |
   |
LL |     foo::<HashMap<Rc<()>, Rc<()>>>();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `Rc<()>` cannot be sent between threads safely
   |
   = help: within `(Rc<()>, Rc<()>)`, the trait `Send` is not implemented for `Rc<()>`
   = note: required because it appears within the type `(Rc<()>, Rc<()>)`
   = note: required because of the requirements on the impl of `Send` for `hashbrown::raw::RawTable<(Rc<()>, Rc<()>)>`
note: required because it appears within the type `hashbrown::map::HashMap<Rc<()>, Rc<()>, RandomState>`
   |
   |
LL | pub struct HashMap<K, V, S = DefaultHashBuilder, A: Allocator + Clone = Global> {
   |            ^^^^^^^
note: required because it appears within the type `HashMap<Rc<()>, Rc<()>>`
   |
   |
LL | pub struct HashMap<K, V, S = RandomState> {
note: required by a bound in `foo`
  --> /checkout/src/test/ui/issues/issue-21763.rs:6:11
   |
   |
LL | fn foo<T: Send>() {}
   |           ^^^^ required by this bound in `foo`
error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
------------------------------------------
```

</details>

2022-03-29 17:11 UTC, cjgillot commented
@bors try @rust-timer queue

2022-03-29 17:11 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

2022-03-29 19:51 UTC, rust-timer commented
Queued 570bb0da8027dcda69858fc2b200800fd580563c with parent 11909e3588319235e28e99294e17cca11db1d7e2, future [comparison URL](https://perf.rust-lang.org/compare.html?start=11909e3588319235e28e99294e17cca11db1d7e2&end=570bb0da8027dcda69858fc2b200800fd580563c).

2022-03-29 23:52 UTC, rust-timer commented
Finished benchmarking commit (570bb0da8027dcda69858fc2b200800fd580563c): [comparison url](https://perf.rust-lang.org/compare.html?start=11909e3588319235e28e99294e17cca11db1d7e2&end=570bb0da8027dcda69858fc2b200800fd580563c).

**Summary**: This benchmark run did not return any relevant results. 4 results were found to be statistically significant but too small to be relevant.

If you disagree with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).

Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR led to changes in compiler perf.

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf -perf-regression

2022-03-30 18:04 UTC, cjgillot commented
@bors try @rust-timer queue

2022-03-30 18:04 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

2022-03-30 21:22 UTC, rust-timer commented
Finished benchmarking commit (b3ca67599d9fad163470e4584416fc676a8fb6a9): [comparison url](https://perf.rust-lang.org/compare.html?start=3e7514670db841a7f0d7656f3b13b1c8b2c11599&end=b3ca67599d9fad163470e4584416fc676a8fb6a9).

**Summary**: This benchmark run did not return any relevant results. 3 results were found to be statistically significant but too small to be relevant.

If you disagree with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).

Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR led to changes in compiler perf.

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf -perf-regression

2022-04-01 12:49 UTC, oli-obk commented on src/test/ui/issues/issue-21763.stderr
> +  --> /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.12.0/src/map.rs:188:12
the old `def_ident_span` was using `get_if_local`, but the new logic works with defs from other crates, too

2022-04-01 13:04 UTC, cjgillot commented on src/test/ui/issues/issue-21763.stderr
> +  --> /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.12.0/src/map.rs:188:12
I mean: shouldn't this path be redacted somehow?

2022-04-01 13:21 UTC, oli-obk commented on src/test/ui/issues/issue-21763.stderr
> +  --> /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.12.0/src/map.rs:188:12
ah, well... we only do that for things in the /build directory, and this is actually fetched from crates.io.

so yea, we should teach compiletest about arbitrary directories that should be replaced in the stderr output

2022-04-03 06:28 UTC, oli-obk commented
r? @oli-obk

2022-04-03 10:41 UTC, oli-obk requested changes
I'll look into compiletest changes next week. I wanted to add a way to add defaults for the comment-configs of ui tests anyway, and we could use that to insert a filter for all crates.io crate paths

2022-04-03 10:41 UTC, oli-obk commented on compiler/rustc_resolve/src/def_collector.rs
> +                            //DefPathData::ImplTrait,
Commented out code

2022-04-03 10:41 UTC, oli-obk commented on src/test/ui/associated-type-bounds/assoc-type-eq-with-dyn-atb-fail.stderr
> +   = note: required for the cast to the object type `dyn Bar<Assoc = <AssocNoCopy as Thing>::Out::impl Copy>`
This is somewhat suboptimal as you can't figure out which impl trait it is if there are multiple with the same bounds. Maybe leave out this change from this PR by adjusting path printing for opaque types?

2022-04-09 10:47 UTC, cjgillot commented on src/test/ui/issues/issue-21763.stderr
> +  --> /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.12.0/src/map.rs:188:12
I removed the generalized use of `def_ident_span` from this PR.

2022-04-09 18:39 UTC, oli-obk commented
@bors r+

2022-04-10 01:17 UTC, merged

2022-04-10 02:31 UTC, rust-timer commented
This benchmark run did not return any relevant results.

If you disagree with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).