Fix intra doc link ICE when trying to get traits in scope for primitive
rust-lang/rust pull request #95645
Opened 2022-04-04 13:19 UTC by GuillaumeGomez

Fixes #95633.

I think @notriddle was the one who worked on this part of the code last so:

r? @notriddle

2022-04-04 13:58 UTC, notriddle commented
@bors r+

2022-04-04 14:58 UTC, jyn514 requested changes

2022-04-04 14:59 UTC, GuillaumeGomez commented
@bors: r-

2022-04-04 15:00 UTC, GuillaumeGomez commented on src/librustdoc/passes/collect_intra_doc_links.rs
> +        None => return Default::default(),
This was also my guess but I went for this in order to prevent the ICE in the time being. Do you prefer I add a FIXME comment and open an issue?

2022-04-04 15:06 UTC, GuillaumeGomez commented on src/librustdoc/passes/collect_intra_doc_links.rs
> +        None => return Default::default(),
Ok. I'll investigate more and if I can't find what's going on, I'll add the FIXME and open an issue.

2022-04-04 15:31 UTC, GuillaumeGomez commented on src/librustdoc/passes/collect_intra_doc_links.rs
> +        None => return Default::default(),
Ok found the problem, we need to handle things a bit differently in case we have this option enabled.

2022-04-04 15:39 UTC, GuillaumeGomez commented
So I found the root problem for this ICE: we only added public traits or traits from public modules. However, we forgot to take that into account when the `--document-private-items` is used. This should be the correct fix now.

2022-04-04 15:43 UTC, jyn514 approved these changes

2022-04-04 16:01 UTC, GuillaumeGomez commented
@bors: r=jyn514

2022-04-04 16:32 UTC, petrochenkov commented
By the way, does `--document-private-items` enables documentation on private items only in the current crate, or in its dependency crates too?

2022-04-04 16:41 UTC, GuillaumeGomez commented
Only on the current crate.

2022-04-05 12:11 UTC, merged

2022-04-05 13:34 UTC, GuillaumeGomez commented
Nominating for beta backport as well.

2022-04-05 14:12 UTC, petrochenkov commented
You may be interested in the perf data in https://github.com/rust-lang/rust/pull/95667#issuecomment-1088748929 before backporting.

2022-04-05 14:15 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

2022-04-05 14:41 UTC, notriddle commented
I don’t think we’re getting a `try` build.

2022-04-05 14:43 UTC, GuillaumeGomez commented
Doesn't seem so... :-/ I'll ask around how to run perf check on this PR.

2022-04-05 14:47 UTC, petrochenkov commented
I need to check what happens here, the `document_private_items`-based fix may be incorrect and fix the issue accidentally.

2022-04-05 17:52 UTC, GuillaumeGomez commented
@petrochenkov You were right, this PR is the one introducing the perf regression: https://github.com/rust-lang/rust/pull/95682#issuecomment-1089112751

I'm very curious why though...

2022-04-05 18:11 UTC, rylev commented
@GuillaumeGomez given how large the impact is, do you think it might be wise to revert this until we figure out what the issue is?

2022-04-05 18:14 UTC, GuillaumeGomez commented
Basically we have the choice between an ICE and a perf regression. I think it's better to keep the perf regression. I think @petrochenkov is already investigating this too so hopefully it should be fine before the next beta release in 6 weeks. I'll remove the beta backport nomination though.

2022-04-05 18:36 UTC, notriddle commented
When documenting a bin crate, cargo always passes `--document-private-items`. It took me a while to find this, even though I knew it *had* to be running with document_private on those perf tests; there's no way a highly predictable branch could have a perf impact like that.

https://github.com/rust-lang/cargo/blob/e2e2dddebe66dfc1403a312653557e332445308b/src/cargo/ops/cargo_compile.rs#L643-L649

To confirm this theory, the worst-impacted crate is helloworld. A bin crate that depends on no lib crates (except the standard library, which doesn't get documented).

2022-04-05 18:37 UTC, GuillaumeGomez commented
Thanks for the information! I completely forgot that about binaries...

2022-04-05 18:41 UTC, rylev commented
> I think it's better to keep the perf regression. 

That's fine, but I am worried about this getting lost. The recommended procedure in that case where a fix is not immediately obvious is to create an issue and assign yourself (or @petrochenkov) to it (though I realize this is also not a guarantee that the issue won't be lost).

2022-04-05 18:42 UTC, GuillaumeGomez commented
This is an excellent point. Opening an issue right away.