Mention `std::env::var` in `env!`
rust-lang/rust pull request #95646
Opened 2022-04-04 14:29 UTC by mgeisler

When searching for how to read an environment variable, I first encountered the `env!` macro. It would have been useful to me if the documentation had included a link to `std::env::var`, which is what I was actually looking for.

2022-04-04 14:29 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @joshtriplett (or someone else) soon.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2022-04-04 15:24 UTC, jyn514 requested changes

2022-04-04 15:28 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/5818208493?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/bb9ab534ef19691d5cafc846df2fb753249fd73e/checks/5818208493/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
 Documenting core v0.0.0 (/checkout/library/core)
error: unresolved link to `std::env::var`
   --> library/core/src/macros/mod.rs:913:11
    |
913 |     /// [`std::env::var`] instead if you want to read the value at runtime.
    |           ^^^^^^^^^^^^^ no item named `std` in scope
    |
    = note: `-D rustdoc::broken-intra-doc-links` implied by `-D warnings`
error: unresolved link to `std::env::var`
   --> library/core/src/macros/mod.rs:955:11
    |
    |
955 |     /// [`std::env::var`] instead if you want to read the value at runtime.
    |           ^^^^^^^^^^^^^ no item named `std` in scope
error: could not document `core`

Caused by:
Caused by:
  process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustdoc --edition=2021 --crate-type lib --crate-name core library/core/src/lib.rs --target x86_64-unknown-linux-gnu -o /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/doc --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --markdown-css rust.css --markdown-no-toc -Z unstable-options --resource-suffix 1.62.0 --index-page /checkout/src/doc/index.md -C metadata=4599449636879869 -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/release/deps --cfg=bootstrap -Csymbol-mangling-version=legacy -Zunstable-options -Dwarnings '-Wrustdoc::invalid_codeblock_attributes' --crate-version '1.62.0-nightly
  (f9c6acb17
  2022-04-04)' '-Zcrate-attr=doc(html_root_url="https://doc.rust-lang.org/nightly/")'` (exit status: 1)
```

</details>

2022-04-04 16:37 UTC, mgeisler commented on library/core/src/macros/mod.rs
> +    /// [`std::env::var`] instead if you want to read the value at runtime.
Thanks for the help!

2022-04-06 12:25 UTC, mgeisler commented on library/core/src/macros/mod.rs
> +    /// [`std::env::var`] instead if you want to read the value at runtime.
Yes, I believe you're correct! Using `../std/` matches other links in the same file. I've pushed a new version so the tests will tell soon :smile:

2022-04-07 04:02 UTC, Dylan-DPC commented
@bors r+ rollup

2022-04-07 07:34 UTC, merged