Remove mutable_borrow_reservation_conflict lint and allow the code pattern
rust-lang/rust pull request #96268
Opened 2022-04-21 02:13 UTC by jackh726

This was the only breaking issue with the NLL stabilization PR. Lang team decided to go ahead and allow this.

r? @nikomatsakis

2022-04-21 02:14 UTC, jackh726 commented
Not sure if this needs FCP or not. There's technically no new behavior.

2022-04-21 03:54 UTC, pnkfelix commented
I *really* want to go through the exercise of verifying that the current version of stacked-borrows does indeed allow the coding pattern.

Its not that I don't believe @RalfJung when they told me that it's fine and stacked-borrows has to handle this, but ... its still better to double check that key assumption first...

2022-04-21 04:12 UTC, pnkfelix commented
Okay well I at least started digging into it and got far enough in the playground to convince myself that there's nothing in today's miri that is going to "obviously" explode. :)

More simply put, miri successfully executed this:

```rust
    #![allow(mutable_borrow_reservation_conflict)]
    let mut v = vec![0, 1, 2];
    let shared = &v;
    v.push(shared.len());
    dbg!(v);
```

so I'm a little less worried than I was 17 minutes ago.

2022-04-21 05:54 UTC, joshtriplett commented
Let's go ahead and confirm consensus on this:

@rfcbot merge

2022-04-21 05:55 UTC, joshtriplett commented
Let's go ahead and confirm consensus on this (momentarily switching labels to T-lang for rfcbot):

@rfcbot merge

2022-04-21 05:56 UTC, joshtriplett commented
@rfcbot f? @RalfJung

2022-04-21 05:59 UTC, joshtriplett commented
@rfcbot concern confirmation-from-ralf

@RalfJung, can we get explicit confirmation in this issue that Stacked Borrows won't have an issue with this anymore?

2022-04-21 14:08 UTC, jackh726 commented
Concern didn't go through...maybe because it's now tagged `T-compiler` again?

2022-04-21 15:35 UTC, cramertj commented
@RalfJung 
> So as long as we are okay with (in the worst case) not doing any alias-based optimizations on 2phase-borrows, we are fine.

Does this mean that we would potentially plan to actually detect places where two-phase is not necessary and optimize only those places, or is this a de-facto "we're not going to do alias-based optimizations"?

If the former, that sounds scary. If the latter, it seems odd to me that one might have to revert to using non-two-phase-borrows-style code in order to unlock optimizations, but that seems like probably a niche enough occurrence that it wouldn't be a huge deal in practice? I have a very hard time judging the impact of these kinds of decisions. Are you able to shed any light on the kinds of optimizations that could be missed in common two-phase-borrows usecases?

2022-04-21 16:33 UTC, bjorn3 commented
How easy would it be to support this pattern if we were to move borrowck to THIR after we switch to polonius? (If moving it to THIR is possible in the first place that is.)

2022-04-21 16:42 UTC, RalfJung commented
> Does this mean that we would potentially plan to actually detect places where two-phase is not necessary and optimize only those places, or is this a de-facto "we're not going to do alias-based optimizations"?

Many (most?) borrows are not two-phase borrows (including all the `noalias` we currently emit, since they are at function boundaries); those are unaffected.

But I admit I am not entirely familiar with the details of when two-phase borrows vs regular mutable borrows are used inside a function. (Shared references are fine anyway.)

The optimizations are the usual ones for aliasing guarantees -- reordering reads and write around other code. The [Stacked Borrows paper](https://plv.mpi-sws.org/rustbelt/stacked-borrows/) contains some examples.

> How easy would it be to support this pattern if we were to move borrowck to THIR after we switch to polonius? (If moving it to THIR is possible in the first place that is.)

Is this directed at me? The questions are about the run-time aliasing model, so borrowck has no bearing on this.

2022-04-22 01:23 UTC, saethlin commented
How do we teach this? The only thing that I can imagine is that we now need to teach that "`&mut` requires uniqueness, except if you write code in _waves hands_ this sort of pattern, in that case `&mut` isn't unique".

That does not sound good.

2022-04-22 02:36 UTC, rdrpenguin04 commented
That's basically where I'm at.

Hello, I'm writing the borrow checker for LCCC, and this behavior seems underspecified. If someone could define why this pattern works, then I'd be all for allowing it; as it stands, this is a nightmare to be compatible with.

I strongly recommend holding off on removing this lint until we have a document specifying exactly why this is valid.

2022-04-22 02:51 UTC, asquared31415 commented
I would like to point out that it is always sufficient as far as I am aware to transform the code that requires this:
```rust
    let mut v = vec![0, 1, 2];
    let shared = &v;
    v.push(shared.len());
    dbg!(v);
```
into code that instead uses a temporary binding for the inner expression:
```rust
    let mut v = vec![0, 1, 2];
    let shared = &v;
    let inner = shared.len();
    v.push(inner);
    dbg!(v);
```
and there is precedent for requiring users to rearrange code to satisfy the borrow checker or other things, such as reordering unique borrows to not overlap or creating a binding to hold a temporary.

2022-04-22 03:18 UTC, rdrpenguin04 commented
To be fair, there is precedent for requiring reordering, but that's not something we should aspire to do. Once I learned the rules for activating borrows, it made sense; the only question now is teaching it, which should be doable.

2022-05-01 19:23 UTC, saethlin commented
> So as long as we are okay with (in the worst case) not doing any alias-based optimizations on 2phase-borrows, we are fine.

@RalfJung does this mean it is incorrect to emit `noalias` for a `&mut` which is actually a 2-phase-borrow?

2022-05-04 18:39 UTC, nikomatsakis commented
@rfcbot fcp reviewed

2022-05-04 20:30 UTC, RalfJung commented
> does this mean it is incorrect to emit noalias for a &mut which is actually a 2-phase-borrow?

Yes, but we don't currently do that. Function arguments are always proper mutable borrows, on the callee side.

2022-05-05 15:12 UTC, nikomatsakis requested changes
r=me if the lint is deprecated "properly"

2022-05-05 18:28 UTC, jackh726 commented on compiler/rustc_lint_defs/src/builtin.rs
> -        MUTABLE_BORROW_RESERVATION_CONFLICT,
It gets registered as removed here: https://github.com/rust-lang/rust/pull/96268/files#diff-cfb1d20a5949dd50b9769edb62eaf10a0de66734637fe71d35bdcf8fb06d767bR494

2022-05-05 18:31 UTC, jackh726 commented
@bors r=nikomatsakis rollup=iffy

Note to those that might try to add this to a rollup: tests *might* have changed that require a re-bless, but I'm not sure.

2022-05-06 14:53 UTC, merged

2022-05-06 14:53 UTC, rust-highfive commented
📣 Toolstate changed by rust-lang/rust#96268!

Tested on commit rust-lang/rust@9a251644fa2adde5f46eea8d342b7e60e4716039.
Direct link to PR: <https://github.com/rust-lang/rust/pull/96268>

💔 miri on windows: test-pass → test-fail (cc @oli-obk @RalfJung @eddyb).
💔 miri on linux: test-pass → test-fail (cc @oli-obk @RalfJung @eddyb).