socket `set_mark` addition.
rust-lang/rust pull request #96334
Opened 2022-04-23 10:07 UTC by devnexen

to be able to set a marker/id on the socket for network filtering
 (iptables/ipfw here) purpose.

2022-04-23 10:07 UTC, rust-highfive commented
Hey! It looks like you've submitted a new PR for the library teams!

If this PR contains changes to any `rust-lang/rust` public library APIs then please comment with `r? rust-lang/libs-api @rustbot label +T-libs-api -T-libs` to request review from a libs-api team reviewer. If you're unsure where your change falls no worries, just leave it as is and the reviewer will take a look and make a decision to forward on if necessary.

Examples of `T-libs-api` changes:

* Stabilizing library features
* Introducing insta-stable changes such as new implementations of existing stable traits on existing stable types
* Introducing new or changing existing unstable library APIs (excluding permanently unstable features / features without a tracking issue)
* Changing public documentation in ways that create new stability guarantees
* Changing observable runtime behavior of library APIs

2022-04-23 10:07 UTC, rust-highfive commented
r? @thomcc

(rust-highfive has picked a reviewer for you, use r? to override)

2022-04-23 18:34 UTC, thomcc commented
r? rust-lang/libs-api @rustbot label +T-libs-api -T-libs

2022-04-27 04:41 UTC, dtolnay requested changes
This seems okay to me. Needs documentation and a tracking issue; I assume that's why the PR is still marked Draft.

2022-04-27 04:46 UTC, devnexen commented
Not only that but waited to see if the idea itself would get traction. ok will do these.

2022-04-27 05:15 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/6187801773?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/807b8b7f26ced355ee37385c226e3568db5ac5a0/checks/6187801773/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
    |
894 |     /// ```
    |         ^^^
    |
    = note: `-D rustdoc::invalid-rust-codeblocks` implied by `-D warnings`
    |
894 |     /// ```text
    |            ++++

---

error: could not document `std`

Caused by:
  process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustdoc --edition=2021 --crate-type dylib --crate-type rlib --crate-name std library/std/src/lib.rs --target x86_64-unknown-linux-gnu -o /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/doc --cfg 'feature="addr2line"' --cfg 'feature="backtrace"' --cfg 'feature="compiler-builtins-c"' --cfg 'feature="gimli-symbolize"' --cfg 'feature="miniz_oxide"' --cfg 'feature="object"' --cfg 'feature="panic_unwind"' --cfg 'feature="std_detect_dlsym_getauxval"' --cfg 'feature="std_detect_file_io"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --markdown-css rust.css --markdown-no-toc -Z unstable-options --resource-suffix 1.62.0 --index-page /checkout/src/doc/index.md -C metadata=ef9e9d7291aa14f5 -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/release/deps --extern addr2line=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libaddr2line-f10831a42b1025a6.rmeta --extern alloc=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/liballoc-9cd0cf8c38b27881.rmeta --extern cfg_if=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libcfg_if-93b9fb0724cf2f7f.rmeta --extern compiler_builtins=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libcompiler_builtins-d2c2e17e5f70a681.rmeta --extern core=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libcore-07ea62845071a1d9.rmeta --extern hashbrown=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libhashbrown-d1fb8db9a8c70750.rmeta --extern libc=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/liblibc-351ecab6f56f0521.rmeta --extern miniz_oxide=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libminiz_oxide-dc7906d34abe6f74.rmeta --extern object=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libobject-02d4d9d31f0023f8.rmeta --extern panic_abort=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libpanic_abort-66e5923eafd23aa3.rmeta --extern panic_unwind=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libpanic_unwind-fe816d509c189590.rmeta --extern rustc_demangle=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/librustc_demangle-7a495c96c19fb96b.rmeta --extern std_detect=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libstd_detect-c0e476ad061ab66d.rmeta --extern unwind=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libunwind-1f41ffed9c07e716.rmeta --cfg=bootstrap -Csymbol-mangling-version=legacy -Zunstable-options -Dwarnings '-Wrustdoc::invalid_codeblock_attributes' --crate-version '1.62.0-nightly
  (9d6f9fa8f
  2022-04-27)' '-Zcrate-attr=doc(html_root_url="https://doc.rust-lang.org/nightly/")' --cfg backtrace_in_libstd` (exit status: 1)
```

</details>

2022-05-13 20:46 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/6429391400?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/dd8315dc605a2bfbe31bf34f0aa22d551959a23d/checks/6429391400/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
    |
894 |     /// ```
    |         ^^^
    |
    = note: `-D rustdoc::invalid-rust-codeblocks` implied by `-D warnings`
    |
894 |     /// ```text
    |            ++++

---

error: could not document `std`

Caused by:
  process didn't exit successfully: `/checkout/obj/build/bootstrap/debug/rustdoc --edition=2021 --crate-type dylib --crate-type rlib --crate-name std library/std/src/lib.rs --target x86_64-unknown-linux-gnu -o /checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/doc --cfg 'feature="addr2line"' --cfg 'feature="backtrace"' --cfg 'feature="compiler-builtins-c"' --cfg 'feature="gimli-symbolize"' --cfg 'feature="miniz_oxide"' --cfg 'feature="object"' --cfg 'feature="panic_unwind"' --cfg 'feature="std_detect_dlsym_getauxval"' --cfg 'feature="std_detect_file_io"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --markdown-css rust.css --markdown-no-toc -Z unstable-options --resource-suffix 1.62.0 --index-page /checkout/src/doc/index.md -C metadata=5ca138720f33db92 -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps -L dependency=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/release/deps --extern addr2line=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libaddr2line-f10831a42b1025a6.rmeta --extern alloc=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/liballoc-9cd0cf8c38b27881.rmeta --extern cfg_if=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libcfg_if-93b9fb0724cf2f7f.rmeta --extern compiler_builtins=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libcompiler_builtins-d2c2e17e5f70a681.rmeta --extern core=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libcore-07ea62845071a1d9.rmeta --extern hashbrown=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libhashbrown-d1fb8db9a8c70750.rmeta --extern libc=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/liblibc-bd31d0d8d8c8644e.rmeta --extern miniz_oxide=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libminiz_oxide-dc7906d34abe6f74.rmeta --extern object=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libobject-02d4d9d31f0023f8.rmeta --extern panic_abort=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libpanic_abort-c1954216233e23ec.rmeta --extern panic_unwind=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libpanic_unwind-54dd43a81b6e0d59.rmeta --extern rustc_demangle=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/librustc_demangle-7a495c96c19fb96b.rmeta --extern std_detect=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libstd_detect-a83e4d92410b77bf.rmeta --extern unwind=/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-std/x86_64-unknown-linux-gnu/release/deps/libunwind-d882e5fe64525dbb.rmeta --cfg=bootstrap -Csymbol-mangling-version=legacy -Zunstable-options -Dwarnings '-Wrustdoc::invalid_codeblock_attributes' --crate-version '1.62.0-nightly
  (3448a5392
  2022-05-13)' '-Zcrate-attr=doc(html_root_url="https://doc.rust-lang.org/nightly/")' --cfg backtrace_in_libstd` (exit status: 1)
```

</details>

2022-05-14 12:25 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/6434413267?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/1077e03f57a2372a6f31d0b0fae6baa3732aff1c/checks/6434413267/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
...........................................................iiiiii....................... 1144/1200
........................i...............................
failures:

---- src/os/unix/net/datagram.rs - os::unix::net::datagram::UnixDatagram::set_mark (line 889) stdout ----
error[E0658]: use of unstable library feature 'unix_socket_ancillary_data'
  |
  |
7 |     sock.set_passcred(32 as u32).expect("set_mark function failed");
  |
  = note: see issue #76915 <https://github.com/rust-lang/rust/issues/76915> for more information
  = note: see issue #76915 <https://github.com/rust-lang/rust/issues/76915> for more information
  = help: add `#![feature(unix_socket_ancillary_data)]` to the crate attributes to enable
error[E0308]: mismatched types
   --> src/os/unix/net/datagram.rs:894:23
    |
    |
7   |     sock.set_passcred(32 as u32).expect("set_mark function failed");
    |          ------------ ^^^^^^^^^ expected `bool`, found `u32`
    |          arguments to this function are incorrect
    |
note: associated function defined here
   --> /checkout/library/std/src/os/unix/net/datagram.rs:870:12
---

Some errors have detailed explanations: E0308, E0658.
For more information about an error, try `rustc --explain E0308`.
Couldn't compile the test.
---- src/os/unix/net/stream.rs - os::unix::net::stream::UnixStream::set_mark (line 439) stdout ----
error[E0658]: use of unstable library feature 'unix_socket_ancillary_data'
  |
  |
7 |     sock.set_passcred(32 as u32).expect("set_mark function failed");
  |
  = note: see issue #76915 <https://github.com/rust-lang/rust/issues/76915> for more information
  = note: see issue #76915 <https://github.com/rust-lang/rust/issues/76915> for more information
  = help: add `#![feature(unix_socket_ancillary_data)]` to the crate attributes to enable
error[E0308]: mismatched types
   --> src/os/unix/net/stream.rs:444:23
    |
    |
7   |     sock.set_passcred(32 as u32).expect("set_mark function failed");
    |          ------------ ^^^^^^^^^ expected `bool`, found `u32`
    |          arguments to this function are incorrect
    |
note: associated function defined here
   --> /checkout/library/std/src/os/unix/net/stream.rs:420:12
```

</details>

2022-06-18 23:01 UTC, JohnCSimon commented
ping from triage:
@devnexen 
Can you post the status of this PR?

FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

2022-06-18 23:05 UTC, devnexen commented
@rustbot ready

2022-07-06 17:34 UTC, dtolnay requested changes

2022-07-06 17:34 UTC, dtolnay commented on library/std/src/os/unix/net/datagram.rs
> +    /// and is only a setter.
It's not clear to me what useful information _"and is only a setter"_ is meant to convey here. Can this sentence be just the following?&mdash;

> Set the id of the socket for network filtering purposes.

2022-07-06 17:34 UTC, dtolnay commented on library/std/src/os/unix/net/datagram.rs
> +    ///     sock.set_mark(32 as u32).expect("set_mark function failed");
It's odd to see `expect` here in a function that returns io::Result anyway. How about returning the error?

```suggestion
    /// fn main() -> std::io::Result<()> {
    ///     let sock = UnixDatagram::unbound()?;
    ///     sock.set_mark(32 as u32)?;
```

2022-07-06 17:34 UTC, dtolnay commented on library/std/src/os/unix/net/datagram.rs
> +    #[unstable(feature = "unix_set_mark", issue = "none")]
Thanks for opening the tracking issue. You need to put the issue number here inside the `issue` attribute. Check out the other `unstable` attributes in this file.

Same applies to the other new `unstable` attribute below.

2022-07-06 17:34 UTC, dtolnay commented on library/std/src/os/unix/net/stream.rs
> +    ///     sock.set_mark(32 as u32).expect("set_mark function failed");
`32 as u32` is redundant. This can just be `sock.set_mark(32)` and the integer will be of type u32 automatically.

2022-07-06 17:34 UTC, dtolnay commented on library/std/src/sys/unix/net.rs
> +    }
The signature is identical across all of these platforms, and the implementation is nearly identical. How about deduplicating it this way?&mdash;

```rust
pub fn set_mark(&self, mark: u32) -> io::Result<()> {
    #[cfg(target_os = "linux")]
    let option = libc::SO_MARK;
    #[cfg(target_os = "linux")]
    let option = libc::SO_USER_COOKIE;
    #[cfg(target_os = "linux")]
    let option = libc::SO_RTABLE;
    setsockopt(self, libc::SOL_SOCKET, option, mark as libc::c_int)
}
```

or maybe this:

```rust
pub fn set_mark(&self, mark: u32) -> io::Result<()> {
    setsockopt(
        self,
        libc::SOL_SOCKET,
        #[cfg(target_os = "linux")]
        libc::SO_MARK,
        #[cfg(target_os = "freebsd")]
        libc::SO_USER_COOKIE,
        #[cfg(target_os = "openbsd")]
        libc::SO_RTABLE,
        mark as libc::c_int,
    )
}
```

2022-07-06 21:34 UTC, dtolnay approved these changes
Thanks!

2022-07-06 21:34 UTC, dtolnay commented
@bors r+

2022-07-07 12:35 UTC, Dylan-DPC commented
failed in [rollup](https://github.com/rust-lang/rust/pull/99007#issuecomment-1177533989)

@bors r-

2022-08-13 16:05 UTC, JohnCSimon commented
> @[devnexen](https://github.com/devnexen) devnexen requested a review from [dtolnay](https://github.com/dtolnay) [last month](https://github.com/rust-lang/rust/pull/96334#event-6952141408)

Triage: 
@devnexen I'm assuming you meant for this to be ready for review 

FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

@rustbot ready

2022-08-26 22:07 UTC, dtolnay approved these changes
Thanks!

2022-08-26 22:07 UTC, dtolnay commented
@bors r+

2022-08-29 07:54 UTC, merged