simplify `describe_field` func in borrowck's diagnostics part
rust-lang/rust pull request #96386
Opened 2022-04-25 08:25 UTC by SparrowLii

This PR simplify the `describe_field` func in borrowck's diagnostics part, besides fix the FIXME in it.

2022-04-25 08:25 UTC, rust-highfive commented
r? @jackh726

(rust-highfive has picked a reviewer for you, use r? to override)

2022-04-25 16:37 UTC, jackh726 requested changes
One small thing

2022-04-26 01:11 UTC, SparrowLii commented on compiler/rustc_borrowck/src/diagnostics/mod.rs
> +        let place_ty = match place {
Yea we need to know the value of `variant_index`, and the structure of `PlaceTy` fits well. But it also makes sense to separate `Ty` and `variant_index` for semantic clarity

2022-04-26 02:32 UTC, jackh726 commented on compiler/rustc_borrowck/src/diagnostics/mod.rs
> +        let place_ty = match place {
Whoops I missed the variant index.

2022-04-26 02:32 UTC, jackh726 commented
@bors r+ rollup

2022-04-26 18:48 UTC, merged