Quick fix for #96223.
rust-lang/rust pull request #96679
Opened 2022-05-03 19:31 UTC by ricked-twice

This PR is a quick fix regarding #96223.

As mentioned in the issue, others modification could be added to not elide types with bound vars from suggestions.

Special thanks to @jackh726 for mentoring and @Manishearth for minimal test case.

r? @jackh726

2022-05-03 19:36 UTC, jackh726 requested changes
Small comments but overall LGTM

2022-05-03 19:36 UTC, jackh726 commented on src/test/ui/suggestions/issue-96223.rs
> +    icey_bounds(&p); //~ERROR
Can you change the comment to `//~ERROR the trait bound

2022-05-03 19:36 UTC, jackh726 commented on src/test/ui/suggestions/issue-96223.rs
> +// Thanks to @Manishearth for the minimal test case.
I think this comment can be left out.

Can you also change this to be `// check-pass`? We don't need to actually build it.

2022-05-03 19:36 UTC, jackh726 commented on compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs
> +            // This is a quick fix to resolve an ICE ([issue#96223](https://github.com/rust-lang/rust/issues/96223)).
You can just write `#96223` instead of the full link.

2022-05-03 20:29 UTC, jackh726 commented
Awesome. @bors r+ rollup

2022-05-03 23:09 UTC, jackh726 commented
@bors r+ rollup

2022-05-04 12:26 UTC, merged

2022-05-05 15:44 UTC, Manishearth commented
@rust-lang/release Can this be uplifted to the beta so it makes the coming release? Without this patch ICU4X is quite prone to hitting this ICE, obscuring any real errors.

2022-05-05 15:46 UTC, jackh726 commented
Ah I meant to beta nominate, whoops. Thanks @Manishearth.

2022-05-05 15:47 UTC, jackh726 commented
This will need compile team approval though

2022-05-05 15:49 UTC, Manishearth commented
cc @rust-lang/compiler

2022-05-05 18:37 UTC, oli-obk commented
Accepting for beta backport.

This is solely on the diagnostics path, fixes a frequent ICE and is a tiny change.