turn `append_place_to_string` from recursion into iteration
rust-lang/rust pull request #96733
Opened 2022-05-05 12:37 UTC by SparrowLii

This PR fixes the FIXME in the impl of `append_place_to_string` which turns `append_place_to_string` from recursion into iteration, meanwhile simplifying the code.

2022-05-05 12:37 UTC, rust-highfive commented
r? @davidtwco

(rust-highfive has picked a reviewer for you, use r? to override)

2022-05-05 12:51 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/6306240891?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/eb38fcf0fb338d8efa0d469837ab56fde5163777/checks/6306240891/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
...........................F............................................................ 704/13057
..............................i......................................................... 792/13057
..........................i............................................................. 880/13057
........................................................................................ 968/13057
.........F.........F....F...F...F.......................F...F...F.................F...F. 1056/13057
..................................F........F...............F............................ 1144/13057
..............................................................F......F.....F...F......F. 1232/13057
..................i..........F...F........F...............................F............. 1320/13057
.........................F................................................i............. 1408/13057
...................................................F.................................... 1496/13057
....F................................................................................... 1584/13057
..............F....................F....F............................................... 1672/13057
........................................................................................ 1848/13057
.......................................................i................................ 1936/13057
........................................................................................ 2024/13057
........................................................................................ 2112/13057
---
........................................................................................ 4840/13057
........................................................................................ 4928/13057
........................................................................i............... 5016/13057
................................................i....................................... 5104/13057
.................................F.F.................................................... 5192/13057
.........................................................F.............................. 5368/13057
........................................................................................ 5456/13057
.........................................................F.............................. 5544/13057
........................................................................................ 5632/13057
........................................................................................ 5632/13057
.................................................................................i...... 5720/13057
........................................................................................ 5808/13057
........................................................................................ 5896/13057
........................................................................................ 5984/13057
........................................................................................ 6072/13057
...............................................................................F........ 6160/13057
...............................F..........F............................................i 6248/13057
........................................................................................ 6424/13057
i....................................................................................... 6512/13057
........................................................................i............... 6600/13057
......................................ii.ii........i...i................................ 6688/13057
---
........................i............................................................... 7656/13057
........................................................................................ 7744/13057
........................................................................................ 7832/13057
.........................ii................i....i..ii................................... 7920/13057
...........F............................................................................ 8008/13057
........................F...........................F............F...................... 8096/13057
...............................F........................................................ 8184/13057
.........................................................i..ii.......................... 8360/13057
....................................ii.................................................. 8448/13057
..........................................iiii.......................................... 8536/13057
............................................................................i........... 8624/13057
---
...........i............................................................................ 10648/13057
....................iiiiii.i..iiiiii.i.................................................. 10736/13057
........................................................................................ 10824/13057
........................................................................................ 10912/13057
.F...........F.......................................................................... 11000/13057
.............F.......................................................................... 11176/13057
........................................................................................ 11264/13057
........................................................................................ 11352/13057
.............F.......................................................................... 11440/13057
---
........................................................................................ 12144/13057
............................................................................i........... 12232/13057
........................................................................................ 12320/13057
........................................................................................ 12408/13057
...................................................FF................................... 12496/13057
..............F..........FF............................................................. 12584/13057
........................................................................................ 12760/13057
........................................................................................ 12848/13057
........................................................................................ 12936/13057
..............iii....................................................................... 13024/13057
..............iii....................................................................... 13024/13057
.................................
failures:

---- [ui] src/test/ui/async-await/issue-74072-lifetime-name-annotations.rs stdout ----
diff of stderr:

10 LL |     y
11    |     - returning this value requires that `*x` is borrowed for `'1`
12 
- error[E0506]: cannot assign to `*x` because it is borrowed
+ error[E0506]: cannot assign to value because it is borrowed
15    |
15    |
16 LL |         let y = &*x;

-    |                 --- borrow of `*x` occurs here
+    |                 --- borrow of value occurs here
18 LL |         *x += 1;
-    |         ^^^^^^^ assignment to borrowed `*x` occurs here
+    |         ^^^^^^^ assignment to borrowed value occurs here
20 LL |         y
-    |         - returning this value requires that `*x` is borrowed for `'1`
+    |         - retu [...]

2022-05-06 01:55 UTC, davidtwco requested changes
LGTM, two minor comments

2022-05-06 01:55 UTC, davidtwco commented on compiler/rustc_borrowck/src/diagnostics/mod.rs
>      ) -> Option<String> {
GitHub won't let me comment on the documentation comment for this function, but it is written as if this function returns a `Result`, could you update it to reflect that the function returns `Option`?

2022-05-06 01:55 UTC, davidtwco commented on compiler/rustc_borrowck/src/diagnostics/mod.rs
> +                ProjectionElem::Downcast(..) => {
nit: could you make this into two branches?

```rust
match elem {
    // ...
    ProjectionElem::Downcast(..) if including_downcast.0 => return None,
    ProjectionElem::Downcast(..) => (),
    // ...
}
```

2022-05-06 04:13 UTC, SparrowLii commented
have fixed it, thanks!

2022-05-06 05:25 UTC, davidtwco approved these changes

2022-05-06 05:26 UTC, davidtwco commented
@bors r+ rollup

2022-05-06 22:41 UTC, merged