Fixes reexports in search
rust-lang/rust pull request #96748
Opened 2022-05-05 22:40 UTC by GuillaumeGomez

Fixes #96681.

At some point we stopped reexporting items in search so this PR fixes it.

It also adds a regression test.

r? @notriddle

2022-05-05 22:40 UTC, rust-highfive commented
Some changes occurred in HTML/CSS/JS.

cc @GuillaumeGomez,@Folyd,@jsha

2022-05-05 23:04 UTC, notriddle requested changes
Simple nit in an otherwise good PR.

If there's no reason not to use `if let` chaining, switch over, then r=me.

2022-05-06 09:12 UTC, GuillaumeGomez commented on src/librustdoc/formats/cache.rs
> +        }) {
That's great! This feature is really nice. :)

2022-05-06 09:27 UTC, GuillaumeGomez commented
My PR actually had another bug: the sidebar wasn't listing `Re-exports` even if there was some on the page. Same bug, fixed the same way.

2022-05-06 09:58 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/6320478915?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/cebf538d8ce53a90359583f99d8ad32426b3c6f0/checks/6320478915/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Rustbook (x86_64-unknown-linux-gnu) - embedded-book
Rustbook (x86_64-unknown-linux-gnu) - edition-guide
Building stage0 tool linkchecker (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.14s
core/prelude/v1/index.html:9: id is not unique: `reexport.Copy`
core/prelude/v1/index.html:9: id is not unique: `reexport.Clone`
core/prelude/v1/index.html:9: id is not unique: `reexport.Eq`
core/prelude/v1/index.html:9: id is not unique: `reexport.Ord`
core/prelude/v1/index.html:9: id is not unique: `reexport.PartialEq`
core/prelude/v1/index.html:9: id is not unique: `reexport.PartialOrd`
core/prelude/v1/index.html:9: id is not unique: `reexport.Default`
std/prelude/v1/index.html:9: id is not unique: `reexport.Clone`
std/prelude/v1/index.html:9: id is not unique: `reexport.Copy`
std/prelude/v1/index.html:9: id is not unique: `reexport.Default`
std/prelude/v1/index.html:9: id is not unique: `reexport.Eq`
std/prelude/v1/index.html:9: id is not unique: `reexport.Ord`
std/prelude/v1/index.html:9: id is not unique: `reexport.PartialEq`
std/prelude/v1/index.html:9: id is not unique: `reexport.PartialOrd`
number of HTML files scanned: 32296
number of HTML redirects found: 10094
number of links checked: 2248867
number of links ignored due to external: 112699
```

</details>

2022-05-06 13:13 UTC, GuillaumeGomez commented
And fixed. :)

2022-05-06 15:16 UTC, notriddle approved these changes

2022-05-06 22:41 UTC, merged