Document the current aliasing rules for `Box<T>`.
rust-lang/rust pull request #97229
Opened 2022-05-20 19:28 UTC by Nilstrieb

Currently, `Box<T>` gets `noalias`, meaning it has the same rules as `&mut T`. This is sparsely documented, even though it can have quite a big impact on unsafe code using box. Therefore, these rules are documented here, with a big warning that they are not normative and subject to change, since we have not yet committed to an aliasing model and the state of `Box<T>` is especially uncertain.

If you have any suggestions and improvements, make sure to leave them here. This is mostly intended to inform people about what is currently going on (to prevent misunderstandings such as [Jon Gjengset's Box aliasing](https://www.youtube.com/watch?v=EY7Wi9fV5bk)). 

This is supposed to _only document current UB_ and not add any new guarantees or rules.

2022-05-20 19:28 UTC, rust-highfive commented
Hey! It looks like you've submitted a new PR for the library teams!

If this PR contains changes to any `rust-lang/rust` public library APIs then please comment with `r? rust-lang/libs-api @rustbot label +T-libs-api -T-libs` to request review from a libs-api team reviewer. If you're unsure where your change falls no worries, just leave it as is and the reviewer will take a look and make a decision to forward on if necessary.

Examples of `T-libs-api` changes:

* Stabilizing library features
* Introducing insta-stable changes such as new implementations of existing stable traits on existing stable types
* Introducing new or changing existing unstable library APIs (excluding permanently unstable features / features without a tracking issue)
* Changing public documentation in ways that create new stability guarantees
* Changing observable runtime behavior of library APIs

2022-05-20 19:28 UTC, rust-highfive commented
r? @kennytm

(rust-highfive has picked a reviewer for you, use r? to override)

2022-05-20 19:28 UTC, Nilstrieb commented
r? rust-lang/libs-api @rustbot label +T-libs-api -T-libs

2022-05-22 23:31 UTC, dtolnay requested changes
I think it needs to be more clear that nothing in this alarming-looking section is relevant to a causal reader who isn't writing their own unsafe code (which is 99%+ of people learning about `Box` from its rustdoc).

Perhaps a section like `# Considerations for unsafe code` would be more appropriate, saying "raw pointer" instead of "pointer", and being explicit like "For more guidance on working with Box from unsafe code, see ucg#326".

2022-05-30 23:48 UTC, dtolnay requested changes

2022-05-30 23:48 UTC, dtolnay commented on library/alloc/src/boxed.rs
> +//! asserts uniqeness over its content. Using raw pointers derived from a box
```suggestion
//! asserts uniqueness over its content. Using raw pointers derived from a box
```

2022-05-30 23:49 UTC, dtolnay approved these changes
Looks good :) thanks!

2022-05-30 23:50 UTC, dtolnay commented
@bors r+ rollup

2022-05-31 09:34 UTC, merged