Separate object lifetime default from lifetime resolution
rust-lang/rust pull request #97393
Opened 2022-05-25 11:52 UTC by cjgillot

Resolution of object lifetime default is currently done during lifetime resolution.
However, this computation happens at a higher level, fetching `generics_of` query to be well defined.

This separation allows to remove the computation of "early index" from lifetime resolution,
relying on the computation performed by `generics_of` instead.
Having a completely separate computation allows to avoid cycles between lifetime resolution and `generics_of`.

Caveat: this implementation still replicates the nested `Binder` model from lifetime resolution
to correctly handle late-bound Debruijn indices.  I don't know yet how to clean this up.

Based on https://github.com/rust-lang/rust/pull/96296

2022-05-25 11:52 UTC, rust-highfive commented
Some changes occurred in src/tools/clippy.

cc @rust-lang/clippy

2022-05-25 11:52 UTC, rust-highfive commented
r? @petrochenkov

(rust-highfive has picked a reviewer for you, use r? to override)

2022-05-25 12:04 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/6591532595?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/5cf6a8d5005b17a867456d3f21f64095b466c456/checks/6591532595/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
tidy: Skipping binary file check, read-only filesystem
Checking which error codes lack tests...
* 629 error codes
* highest error code: E0787
tidy error: /checkout/compiler/rustc_resolve/src/late/lifetimes.rs: ignoring file length unnecessarily
Found 0 error(s) in error codes
Done!
Done!
tidy error: /checkout/compiler/rustc_typeck/src/collect.rs: too many lines (3005) (add `// ignore-tidy-filelength` to the file to suppress this error)
some tidy checks failed
Build completed unsuccessfully in 0:00:11
```

</details>

2022-05-25 18:30 UTC, jackh726 commented
Neat

2022-05-29 19:00 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/6645170792?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/9b29e9a11df89568c44d8044682fc605983daf10/checks/6645170792/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
 finished in 0.627 seconds
Check compiletest suite=incremental mode=incremental (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)

running 154 tests
........................................F...............F............................... 88/154
Some tests failed in compiletest suite=incremental mode=incremental host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
failures:

---- [incremental] src/test/incremental/hashes/enum_defs.rs stdout ----


error in revision `cfail2`: test compilation failed although it shouldn't!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/incremental/hashes/enum_defs.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--cfg" "cfail2" "-C" "incremental=/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental/hashes/enum_defs/enum_defs.inc" "-Z" "incremental-verify-ich" "--error-format" "json" "--json" "future-incompat" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental/hashes/enum_defs" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-Z" "query-dep-graph" "-O" "-Zincremental-ignore-spans" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental/hashes/enum_defs/auxiliary"
stdout: none
--- stderr -------------------------------
error: `generics_of(EnumAddLifetimeBoundToParameter)` should be dirty but is not
   |
   |
LL | / enum EnumAddLifetimeBoundToParameter<'a, T: 'a> {
LL | |     Variant1(T),
LL | |     Variant2(&'a u32),
LL | | }


error: `generics_of(EnumAddLifetimeBoundToParameterWhere)` should be dirty but is not
   |
   |
LL | / enum EnumAddLifetimeBoundToParameterWhere<'a, T> where T: 'a {
LL | |     Variant1(T),
LL | |     Variant2(&'a u32),
LL | | }

error: aborting due to 2 previous errors
------------------------------------------



---- [incremental] src/test/incremental/hashes/trait_defs.rs stdout ----

error in revision `cfail2`: test compilation failed although it shouldn't!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/incremental/hashes/trait_defs.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--cfg" "cfail2" "-C" "incremental=/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental/hashes/trait_defs/trait_defs.inc" "-Z" "incremental-verify-ich" "--error-format" "json" "--json" "future-incompat" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental/hashes/trait_defs" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-Z" "query-dep-graph" "-O" "-Zincremental-ignore-spans" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/incremental/hashes/trait_defs/auxiliary"
stdout: none
--- stderr -------------------------------
error: `generics_of(TraitAddLifetimeBoundToTypeParameterOfTrait)` should be dirty but is not
   |
   |
LL | trait TraitAddLifetimeBoundToTypeParameterOfTrait<'a, T: 'a> { }


error: `generics_of(TraitAddSecondLifetimeBoundToTypeParameterOfTrait)` should be dirty but is not
   |
   |
LL | trait TraitAddSecondLifetimeBoundToTypeParameterOfTrait<'a, 'b, T: 'a + 'b> { }


error: `generics_of(TraitAddLifetimeBoundToTypeParameterOfTraitWhere)` should be dirty but is not
   |
   |
LL | trait TraitAddLifetimeBoundToTypeParameterOfTraitWhere<'a, T> where T: 'a { }


error: `generics_of(TraitAddSecondLifetimeBoundToTypeParameterOfTraitWhere)` should be dirty but is not
   |
   |
LL | trait TraitAddSecondLifetimeBoundToTypeParameterOfTraitWhere<'a, 'b, T> where T: 'a + 'b { }

error: aborting due to 4 previous errors
------------------------------------------

```

</details>

2022-06-04 13:28 UTC, cjgillot commented
@bors try @rust-timer queue

2022-06-04 13:28 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

2022-06-04 14:58 UTC, rust-timer commented
Queued c572965bed3faeadf9101c64e711316e43d6f1d9 with parent 4a52e0fd7d80e50f22999ce3a765ea1341bd442a, future [comparison URL](https://perf.rust-lang.org/compare.html?start=4a52e0fd7d80e50f22999ce3a765ea1341bd442a&end=c572965bed3faeadf9101c64e711316e43d6f1d9).

2022-06-04 17:08 UTC, rust-timer commented
Finished benchmarking commit (c572965bed3faeadf9101c64e711316e43d6f1d9): [comparison url](https://perf.rust-lang.org/compare.html?start=4a52e0fd7d80e50f22999ce3a765ea1341bd442a&end=c572965bed3faeadf9101c64e711316e43d6f1d9&stat=instructions:u).


### [Instruction count](https://perf.rust-lang.org/compare.html?start=4a52e0fd7d80e50f22999ce3a765ea1341bd442a&end=c572965bed3faeadf9101c64e711316e43d6f1d9&stat=instructions:u)

- Primary benchmarks: mixed results
- Secondary benchmarks: mixed results

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions 😿 <br /> (primary) | 0.4%     | 0.9% | 54        |
| Regressions 😿 <br /> (secondary) | 0.6%     | 1.0% | 31        |
| Improvements 🎉 <br /> (primary) | -0.3%    | -0.3% | 11        |
| Improvements 🎉 <br /> (secondary) | -0.7%    | -1.9% | 27        |
| All 😿🎉 (primary) | 0.3%     | 0.9% | 65        |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=4a52e0fd7d80e50f22999ce3a765ea1341bd442a&end=c572965bed3faeadf9101c64e711316e43d6f1d9&stat=max-rss)
<details>
<summary>Results</summary>


- Primary benchmarks: 🎉 relevant improvements found
- Secondary benchmarks: 😿 relevant regressions found

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions 😿 <br /> (primary) | N/A      | N/A | 0         |
| Regressions 😿 <br /> (secondary) | 1.6%     | 2.0% | 2         |
| Improvements 🎉 <br /> (primary) | -2.4%    | -6.6% | 9         |
| Improvements 🎉 <br /> (secondary) | N/A      | N/A | 0         |
| All 😿🎉 (primary) | -2.4%    | -6.6% | 9         |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=4a52e0fd7d80e50f22999ce3a765ea1341bd442a&end=c572965bed3faeadf9101c64e711316e43d6f1d9&stat=cycles:u)
<details>
<summary>Results</summary>


- Primary benchmarks: no relevant changes found
- Secondary benchmarks: 🎉 relevant improvement found

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions 😿 <br /> (primary) | N/A      | N/A | 0         |
| Regressions 😿 <br /> (secondary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (primary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (secondary) | -2.4%    | -2.4% | 1         |
| All 😿🎉 (primary) | N/A      | N/A | 0         |
</details>

[^1]: *the arithmetic mean of the percent change*
[^2]: *number of relevant changes*

If you disagree with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).

Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf +perf-regression

2022-06-04 21:07 UTC, petrochenkov commented
I guess this is the part of `compiler/rustc_resolve/src/late/lifetimes.rs` that has nothing to do with name resolution.
r? @jackh726

2022-06-04 21:45 UTC, cjgillot commented on compiler/rustc_middle/src/query/mod.rs
> +        desc { "looking up lifetime defaults for a region on an item" }
```suggestion
        desc { "compute object lifetime defaults for a generic parameter" }
```

2022-06-05 11:32 UTC, cjgillot commented on compiler/rustc_typeck/src/collect/object_lifetime_defaults.rs
> +                let param = generics.params.get(i)?;
This is wrong.  The index of argument in HIR may not correspond to the index in `ty::Generics`.

2022-06-05 11:33 UTC, cjgillot commented on compiler/rustc_typeck/src/collect/object_lifetime_defaults.rs
> +                    let index = *generics.param_def_id_to_index.get(&def_id)?;
This is also wrong, the other way around.

2022-06-05 11:35 UTC, cjgillot commented
@jackh726 I think the handling of generic arguments could be re-implemented without touching HIR at all, and would be more robust.  However, I need a bit of guidance here.

2022-06-06 22:44 UTC, jackh726 requested changes
Going through this. Is it possible that we can split out commits 1,2,3,8 , and 9 into a separate PR? That seems like an "easy" first step here.

2022-06-26 19:47 UTC, jackh726 commented
Blocked on https://github.com/rust-lang/rust/pull/97839

2022-07-27 21:41 UTC, closed without merging