Make outlives::{components,verify} agree
rust-lang/rust pull request #97406
Opened 2022-05-25 18:39 UTC by aliemjay

fixes #97405

r? @ghost

2022-05-26 03:37 UTC, aliemjay commented
r? @oli-obk

2022-05-27 09:28 UTC, oli-obk commented
Nominating for T-types discussion:

```rust
fn opaque<F>(_: F) -> impl Iterator { b"".iter() }
fn assert_static<T: 'static>(_: T) {}

fn good_generic_fn<T>() {
    // proving `<OpaqueTy<type_of(async {})> as Iterator>::Item: 'static`
    // somehow requires `T: 'static`.
    assert_static(opaque(async {}).next());
    assert_static(opaque(|| {}).next());
    assert_static(opaque(opaque(async {}).next()).next());
}
```

does not compile right now, because the `T` of `good_generic_fn` is inherited by generators and closures, even if they do not capture any types that relate to `T`. This PR does not change that, but it instead adjusts the algorithm figuring out which types and lifetimes must be considered for an outlives bound to only look at captured things in the generators or closures.

This scheme already works on stable for simpler cases, but in associated types it breaks down. Thus I nominate for T-types instead of T-lang, since imo this is just-an-impl-bug and the behaviour intended by the lang team.

2022-05-27 09:30 UTC, oli-obk requested changes

2022-05-27 09:30 UTC, oli-obk commented on compiler/rustc_infer/src/infer/outlives/components.rs
> +pub(crate) fn compute_components_recursive<'tcx>(
```suggestion
pub(super) fn compute_components_recursive<'tcx>(
```

2022-05-27 09:30 UTC, oli-obk commented on compiler/rustc_infer/src/infer/outlives/verify.rs
>                  }
Please pull this match out into a separate method

2022-05-27 10:11 UTC, aliemjay commented
a less contrived example that should be fixed now:
```rust
fn from_fn<F>(_: F) -> impl IntoIterator<Item = u8> { [] }

fn generic_fn<T>() -> Box<dyn Iterator<Item = u8>> {
    Box::new(from_fn(|| {}).into_iter())
    //~^ ERROR the associated type `<impl IntoIterator<Item = u8> as IntoIterator>::IntoIter` may not live long enough
}
```

2022-05-30 08:24 UTC, aliemjay commented
@rustbot review

2022-06-15 06:44 UTC, oli-obk commented
Let's see if this opens a zulip thread automagically

2022-06-15 10:32 UTC, aliemjay commented
oli-obk is in vacation, so
r? @nikomatsakis 

@nikomatsakis  choosed you because you recently touched `VerifyBound`s and  types tests, and this PR basically fixes malformed verify bounds for projection tys. Feel free to reassign if you like.

2022-06-15 11:48 UTC, oli-obk commented
@bors try @rust-timer queue

2022-06-15 11:48 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

2022-06-15 13:44 UTC, rust-timer commented
Queued adb581d2e9a6bc04d25a117528c5bb41de56d059 with parent ebe184a69316fab85129896e5045502c5db9d6f4, future [comparison URL](https://perf.rust-lang.org/compare.html?start=ebe184a69316fab85129896e5045502c5db9d6f4&end=adb581d2e9a6bc04d25a117528c5bb41de56d059).

2022-06-15 15:00 UTC, rust-timer commented
Finished benchmarking commit (adb581d2e9a6bc04d25a117528c5bb41de56d059): [comparison url](https://perf.rust-lang.org/compare.html?start=ebe184a69316fab85129896e5045502c5db9d6f4&end=adb581d2e9a6bc04d25a117528c5bb41de56d059&stat=instructions:u).


### [Instruction count](https://perf.rust-lang.org/compare.html?start=ebe184a69316fab85129896e5045502c5db9d6f4&end=adb581d2e9a6bc04d25a117528c5bb41de56d059&stat=instructions:u)

- Primary benchmarks: 🎉 relevant improvements found
- Secondary benchmarks: no relevant changes found

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions 😿 <br /> (primary) | N/A      | N/A | 0         |
| Regressions 😿 <br /> (secondary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (primary) | -0.8%    | -0.9% | 5         |
| Improvements 🎉 <br /> (secondary) | N/A      | N/A | 0         |
| All 😿🎉 (primary) | -0.8%    | -0.9% | 5         |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=ebe184a69316fab85129896e5045502c5db9d6f4&end=adb581d2e9a6bc04d25a117528c5bb41de56d059&stat=max-rss)
<details>
<summary>Results</summary>


- Primary benchmarks: no relevant changes found
- Secondary benchmarks: 😿 relevant regression found

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions 😿 <br /> (primary) | N/A      | N/A | 0         |
| Regressions 😿 <br /> (secondary) | 4.1%     | 4.1% | 1         |
| Improvements 🎉 <br /> (primary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (secondary) | N/A      | N/A | 0         |
| All 😿🎉 (primary) | N/A      | N/A | 0         |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=ebe184a69316fab85129896e5045502c5db9d6f4&end=adb581d2e9a6bc04d25a117528c5bb41de56d059&stat=cycles:u)
<details>
<summary>Results</summary>


- Primary benchmarks: no relevant changes found
- Secondary benchmarks: mixed results

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions 😿 <br /> (primary) | N/A      | N/A | 0         |
| Regressions 😿 <br /> (secondary) | 2.5%     | 2.5% | 1         |
| Improvements 🎉 <br /> (primary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (secondary) | -1.7%    | -1.7% | 1         |
| All 😿🎉 (primary) | N/A      | N/A | 0         |
</details>

[^1]: *the arithmetic mean of the percent change*
[^2]: *number of relevant changes*

If you disagree with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).

Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf -perf-regression

2022-06-20 12:57 UTC, oli-obk commented
@rfcbot merge

```rust
fn opaque<F>(_: F) -> impl Iterator { b"".iter() }
fn assert_static<T: 'static>(_: T) {}

fn good_generic_fn<T>() {
    // proving `<OpaqueTy<type_of(async {})> as Iterator>::Item: 'static`
    // somehow requires `T: 'static`.
    assert_static(opaque(async {}).next());
    assert_static(opaque(|| {}).next());
    assert_static(opaque(opaque(async {}).next()).next());
}
```

does not compile right now, because the `T` of `good_generic_fn` is inherited by generators and closures, even if they do not capture any types that relate to `T`.

This PR does not change that, but it instead adjusts the algorithm figuring out which types and lifetimes must be considered for an outlives bound to only look at captured things in the generators or closures.

This scheme already works on stable for simpler cases, but in associated types it breaks down. Thus I nominate for T-types instead of T-lang, since imo this is just-an-impl-bug and the behaviour intended by the lang team.

2022-07-13 10:08 UTC, oli-obk commented
@bors r+

2022-07-13 14:13 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/runs/7322474697?check_suite_focus=true) [(plain)](https://github.com/rust-lang-ci/rust/commit/51e0b1a3794f76bfad920a8982c08da68a4ab836/checks/7322474697/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
diff of stderr:

2   --> $DIR/closure-in-projection-issue-97405.rs:24:5
3    |
4 LL |     assert_static(opaque(async move { t; }).next());
+    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
6    |
6    |
7    = help: consider adding an explicit lifetime bound `<impl Iterator as Iterator>::Item: 'static`...
-    = note: ...so that the type `Option<<impl Iterator as Iterator>::Item>` will meet its required lifetime bounds...
- note: ...that is required by this bound
-   --> $DIR/closure-in-projection-issue-97405.rs:11:21
-    |
- LL | fn assert_static<T: 'static>(_: T) {}
-    |                     ^^^^^^^
+    = note: ...so that the type `<impl Iterator as Iterator>::Item` will meet its required lifetime bounds
14 
15 error[E0310]: the associated type `<impl Iterator as Iterator>::Item` may not live long enough

Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
17    |
17    |
18 LL |     assert_static(opaque(move || { t; }).next());
+    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20    |
20    |
21    = help: consider adding an explicit lifetime bound `<impl Iterator as Iterator>::Item: 'static`...
-    = note: ...so that the type `Option<<impl Iterator as Iterator>::Item>` will meet its required lifetime bounds...
- note: ...that is required by this bound
-   --> $DIR/closure-in-projection-issue-97405.rs:11:21
-    |
- LL | fn assert_static<T: 'static>(_: T) {}
-    |                     ^^^^^^^
+    = note: ...so that the type `<impl Iterator as Iterator>::Item` will meet its required lifetime bounds
28 
29 error[E0310]: the associated type `<impl Iterator as Iterator>::Item` may not live long enough

31    |
31    |
32 LL |     assert_static(opaque(opaque(async move { t; }).next()).next());
+    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
34    |
34    |
35    = help: consider adding an explicit lifetime bound `<impl Iterator as Iterator>::Item: 'static`...
-    = note: ...so that the type `Option<<impl Iterator as Iterator>::Item>` will meet its required lifetime bounds...
- note: ...that is required by this bound
-   --> $DIR/closure-in-projection-issue-97405.rs:11:21
-    |
- LL | fn assert_static<T: 'static>(_: T) {}
-    |                     ^^^^^^^
+    = note: ...so that the type `<impl Iterator as Iterator>::Item` will meet its required lifetime bounds
43 error: aborting due to 3 previous errors
44 



The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/regions/closure-in-projection-issue-97405/closure-in-projection-issue-97405.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args regions/closure-in-projection-issue-97405.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/regions/closure-in-projection-issue-97405.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/regions/closure-in-projection-issue-97405" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--edition=2018" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/regions/closure-in-projection-issue-97405/auxiliary"
stdout: none
--- stderr -------------------------------
error[E0310]: the associated type `<impl Iterator as Iterator>::Item` may not live long enough
   |
   |
LL |     assert_static(opaque(async move { t; }).next());
   |
   |
   = help: consider adding an explicit lifetime bound `<impl Iterator as Iterator>::Item: 'static`...
   = note: ...so that the type `<impl Iterator as Iterator>::Item` will meet its required lifetime bounds

error[E0310]: the associated type `<impl Iterator as Iterator>::Item` may not live long enough
   |
   |
LL |     assert_static(opaque(move || { t; }).next());
   |
   |
   = help: consider adding an explicit lifetime bound `<impl Iterator as Iterator>::Item: 'static`...
   = note: ...so that the type `<impl Iterator as Iterator>::Item` will meet its required lifetime bounds

error[E0310]: the associated type `<impl Iterator as Iterator>::Item` may not live long enough
   |
   |
LL |     assert_static(opaque(opaque(async move { t; }).next()).next());
   |
   |
   = help: consider adding an explicit lifetime bound `<impl Iterator as Iterator>::Item: 'static`...
   = note: ...so that the type `<impl Iterator as Iterator>::Item` will meet its required lifetime bounds
error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0310`.
------------------------------------------
```

</details>

2022-07-14 01:04 UTC, aliemjay commented
I have rebased to adjust for NLL diagnostic regressions. The first commit has not changed.

r? @oli-obk

2022-07-14 13:36 UTC, oli-obk commented
@bors r+

2022-07-15 01:06 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-tools`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/runs/7350267373?check_suite_focus=true) [(plain)](https://github.com/rust-lang-ci/rust/commit/f097ed2c9de38bd491399e96de8e1f1d1321d2f9/checks/7350267373/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
.......... (60/66)
.....     (66/66)


/checkout/src/test/rustdoc-gui/search-result-display.goml search-result-display... FAILED
[ERROR] (line 5) Error: The following CSS selector "#search-settings" was not found: for command `wait-for: "#search-settings"`
Build completed unsuccessfully in 0:00:46
```

</details>

2022-07-15 02:46 UTC, jackh726 commented
Spurious?

@bors retry

2022-07-15 06:15 UTC, merged

2022-07-15 07:31 UTC, rust-timer commented
Finished benchmarking commit (b90a0ede02f122a91b376cb2a8632a370269dd60): [comparison url](https://perf.rust-lang.org/compare.html?start=30243dd87e7dbd17d68e1a1d16ba066a7d2cebe5&end=b90a0ede02f122a91b376cb2a8632a370269dd60&stat=instructions:u).


### [Instruction count](https://perf.rust-lang.org/compare.html?start=30243dd87e7dbd17d68e1a1d16ba066a7d2cebe5&end=b90a0ede02f122a91b376cb2a8632a370269dd60&stat=instructions:u)

- Primary benchmarks: no relevant changes found
- Secondary benchmarks: 🎉 relevant improvement found

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions 😿 <br /> (primary) | N/A      | N/A | 0         |
| Regressions 😿 <br /> (secondary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (primary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (secondary) | -0.5%    | -0.5% | 1         |
| All 😿🎉 (primary) | N/A      | N/A | 0         |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=30243dd87e7dbd17d68e1a1d16ba066a7d2cebe5&end=b90a0ede02f122a91b376cb2a8632a370269dd60&stat=max-rss)
<details>
<summary>Results</summary>


- Primary benchmarks: 😿 relevant regressions found
- Secondary benchmarks: mixed results

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions 😿 <br /> (primary) | 3.5%     | 4.4% | 2         |
| Regressions 😿 <br /> (secondary) | 3.1%     | 3.8% | 3         |
| Improvements 🎉 <br /> (primary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (secondary) | -2.1%    | -2.1% | 1         |
| All 😿🎉 (primary) | 3.5%     | 4.4% | 2         |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=30243dd87e7dbd17d68e1a1d16ba066a7d2cebe5&end=b90a0ede02f122a91b376cb2a8632a370269dd60&stat=cycles:u)
<details>
<summary>Results</summary>


- Primary benchmarks: mixed results
- Secondary benchmarks: no relevant changes found

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions 😿 <br /> (primary) | 1.3%     | 1.3% | 1         |
| Regressions 😿 <br /> (secondary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (primary) | -2.5%    | -2.5% | 1         |
| Improvements 🎉 <br /> (secondary) | N/A      | N/A | 0         |
| All 😿🎉 (primary) | -0.6%    | -2.5% | 2         |
</details>

[^1]: *the arithmetic mean of the percent change*
[^2]: *number of relevant changes*

If you disagree with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).



@rustbot label: -perf-regression