[RFC 2011] Basic compiler infrastructure
rust-lang/rust pull request #97450
Opened 2022-05-27 11:52 UTC by c410-f3r

Splitting https://github.com/rust-lang/rust/pull/96496 into smaller pieces as was done in https://github.com/rust-lang/rust/pull/97233. Hope review will be easier.

This PR practically contains no logic and only serves as a building ground for the actual code that will be placed in a posterior step.

* Adds `context.rs` to place the new `assert!` logic. Has a lot of unused elements but all of them are used by the implementation.
* Modifies `assert.rs` to branch to `context.rs` if the unstable flag is enabled.
* Creates an unstable flag because the feature is not yet complete and also to allow external feedback.
* Adds a test to satisfy tidy but the test does nothing in reality.
* Creates the necessary `sym` identifiers that are mostly based on the library elements -> https://github.com/rust-lang/rust/blob/master/library/core/src/asserting.rs

2022-05-27 11:52 UTC, rust-highfive commented
r? @michaelwoerister

(rust-highfive has picked a reviewer for you, use r? to override)

2022-05-27 12:07 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/6624977531?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/90c2edfe0fcb58a60e2029a7e744b7feb0111f0f/checks/6624977531/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
-    ptr::P,
-    Expr,
-    Path, Stmt,
-};
+use rustc_ast::{ptr::P, Expr, Path, Stmt};
 use rustc_data_structures::fx::FxHashSet;
 use rustc_expand::base::ExtCtxt;
-use rustc_span::{
-    symbol::Ident,
-};
-};
+use rustc_span::{symbol::Ident, Span};
 
 pub(super) struct Context<'cx, 'a> {
     // An optimization.
Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/compiler/rustc_builtin_macros/src/concat_bytes.rs" "/checkout/compiler/rustc_lint/src/levels.rs" "/checkout/compiler/rustc_builtin_macros/src/assert/context.rs" "/checkout/compiler/rustc_builtin_macros/src/deriving/default.rs" "/checkout/compiler/rustc_builtin_macros/src/deriving/clone.rs" "/checkout/compiler/rustc_builtin_macros/src/deriving/debug.rs" "/checkout/compiler/rustc_builtin_macros/src/deriving/bounds.rs" "/checkout/compiler/rustc_builtin_macros/src/format_foreign/printf/tests.rs"` failed.
If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
```

</details>

2022-06-02 11:30 UTC, oli-obk requested changes
Thanks for splitting this up. As a next smaller step, maybe just add binary operations and nothing else?

2022-06-02 11:30 UTC, oli-obk commented on src/test/ui/rfc-2011-nicer-assert-messages/feature-gate-generic_assert.rs
> +  assert!(_copy_debug == CopyDebug(3));
maybe leave a comment that `generic_assert` is completely unimplemented and just doesn't generate any logic at all, thus this test passes

2022-06-02 11:30 UTC, oli-obk commented on compiler/rustc_builtin_macros/src/assert/context.rs
> +            _paths: <_>::default(),
please remove the unused fields for now. Adding more fields to an existing data structure in the follow up PR won't make this harder to review.

2022-06-02 11:30 UTC, oli-obk commented on compiler/rustc_span/src/symbol.rs
> +        Capture,
Please only add symbols actually used in this PR

2022-06-02 11:43 UTC, c410-f3r commented
> Thanks for splitting this up. As a next smaller step, maybe just add binary operations and nothing else?

Done. Thank you for the review

2022-06-02 12:07 UTC, oli-obk approved these changes

2022-06-02 12:09 UTC, oli-obk commented
@bors r+

2022-06-02 12:09 UTC, oli-obk commented
@bors rollup

2022-06-02 18:45 UTC, merged