option: implement ToOwned for convenience
rust-lang/rust pull request #97768
Opened 2022-06-05 17:25 UTC by Vanadiae

Similar to the Clone implementation for Option, this ToOwned implementation
is very convenient as it allows going from a borrowed Option<&str> directly
to an owned Option<String>. It is especially useful in a zero-copy parser
context, where everything's borrowed from the input data so it's not
possible to simply clone() to get our own owned data, as Clone is only
available when the input and output types are the same (which isn't the
case for &str, which instead implements ToOwned).

-----------------------

Note I didn't have the opportunity to test these changes as I'm pretty sure compiling it would take hours on my computer. I did not open an issue (and could not find one) because this change seems pretty uncontroversial to me, and at least things can be discussed here if needed. There's two commented lines left in my code here, as I'm not sure if the `unstable` attribute is required when implementing traits, and to make sure that my `clone_into()` code is correct (as I've never used that code).

FYI I thought it was weird this feature did not exist when implementing an XML format parser, where I parse "meaningless" XML nodes into proper structs fields, so I currently have code like so:
```rust
struct Metadata {
    title: Option<String>,
}

// snip […]
let meta = Metadata::default();
// snip, iterate on all childs nodes
if let Some(text) = node.text() {
    match node.tag_name().name() {
        "title" => meta.title = Some(text.to_owned()),
    }
}
```
where I could instead have:
```rust
match node.tag_name().name() {
    "title" => meta.title = text.to_owned(),
}
```

It might not sound like much but when there's lots of different struct fields it starts to be really heavy on the eyes that `opt.to_owned()` can't be used here. It does work fine for an Option where T implements Clone (which isn't the case for `&str`), it's just that there's no similar counterpart for ToOwned.

(using [roxmltree](https://docs.rs/roxmltree/latest/roxmltree/struct.Node.html#method.text) which does not copy the input data, as it takes the whole XML as a &str and not a stream).

2022-06-05 17:25 UTC, rust-highfive commented
Hey! It looks like you've submitted a new PR for the library teams!

If this PR contains changes to any `rust-lang/rust` public library APIs then please comment with `r? rust-lang/libs-api @rustbot label +T-libs-api -T-libs` to request review from a libs-api team reviewer. If you're unsure where your change falls no worries, just leave it as is and the reviewer will take a look and make a decision to forward on if necessary.

Examples of `T-libs-api` changes:

* Stabilizing library features
* Introducing insta-stable changes such as new implementations of existing stable traits on existing stable types
* Introducing new or changing existing unstable library APIs (excluding permanently unstable features / features without a tracking issue)
* Changing public documentation in ways that create new stability guarantees
* Changing observable runtime behavior of library APIs

2022-06-05 17:25 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @m-ou-se (or someone else) soon.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2022-06-05 17:28 UTC, Vanadiae commented
r? rust-lang/libs-api @rustbot label +T-libs-api -T-libs

Seems like my MR corresponds to the following part:
> Introducing insta-stable changes such as new implementations of existing stable traits on existing stable types

2022-06-05 17:28 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/6746277496?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/9d75d4acb2a2254f2c8c782f79c246968684941c/checks/6746277496/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
   Compiling unwind v0.0.0 (/checkout/library/unwind)
error[E0405]: cannot find trait `ToOwned` in this scope
    --> library/core/src/option.rs:1905:18
     |
1905 | impl<T: ToOwned> ToOwned for Option<T> {

error[E0405]: cannot find trait `ToOwned` in this scope
    --> library/core/src/option.rs:1905:9
     |
     |
1905 | impl<T: ToOwned> ToOwned for Option<T> {

error[E0425]: cannot find value `source` in this scope
    --> library/core/src/option.rs:1920:22
     |
     |
1920 |         match (self, source) {
     |                      ^^^^^^ not found in this scope

error[E0546]: missing 'feature'
    --> library/core/src/option.rs:1904:1
     |
1904 | #[stable(since = "1.61.0")]


error[E0599]: no variant named `Owned` found for enum `Option<T>`
     |
518  | pub enum Option<T> {
518  | pub enum Option<T> {
     | ------------------ variant `Owned` not found here
...
1909 |     fn to_owned(&self) -> Self::Owned {
     |                                 ^^^^^ variant not found in `Option<T>`

error[E0599]: no variant named `Owned` found for enum `Option<T>`
     |
518  | pub enum Option<T> {
518  | pub enum Option<T> {
     | ------------------ variant `Owned` not found here
...
1919 |     fn clone_into(&self, target: &mut Self::Owned) {
     |                                             ^^^^^ variant not found in `Option<T>`
Some errors have detailed explanations: E0405, E0425, E0546, E0599.
For more information about an error, try `rustc --explain E0405`.
error: could not compile `core` due to 6 previous errors
Build completed unsuccessfully in 0:00:04
```

</details>

2022-06-05 17:38 UTC, Vanadiae commented
Ah right, ToOwned is in the alloc crate. Should I move this code to alloc's borrow.rs or create a new option.rs in std to implement it there?

2022-12-29 12:55 UTC, eggyal commented
`ToOwned` generalises the act of "cloning" so that one can go from a (borrowed) `?Sized` type to its (owned) `Sized` equivalent (which `Clone` cannot always do, as there may be a change of type).

But `Option<T>` is already `Sized`, so I would argue that no change of type is required: going from borrowed to owned is merely a regular clone operation—and indeed [this is provided](https://doc.rust-lang.org/std/option/enum.Option.html#impl-ToOwned-for-Option%3CT%3E) by the blanket implementation of `ToOwned` for all types that implement `Clone`.

Moreover, for any `Option<T>`, `T` is itself necessarily `Sized`—so we have ditto for it going from borrowed to owned forms, via both `Clone` and the blanket implementation of `ToOwned`.

Perhaps you are seeking to go from `Option<&T>` to `Option<T::Owned>`?  But I don't think that's the correct semantics for an implementation of `ToOwned` for `Option<&T>`, since *the contained reference* is already owned.  Nevertheless this operation is trivial to implement with [`Option::map`](https://doc.rust-lang.org/std/option/enum.Option.html#method.map):

```rust
option.map(T::to_owned)
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9531f18a5fc367d9ce209aa385f52fd2)

This should be more ergonomic/concise than explicit `match`ing.

2022-12-29 15:07 UTC, Vanadiae commented
Hi, thanks for your answer.

> Perhaps you are seeking to go from Option<&T> to Option<T::Owned>?

Yes, that's exactly what I want: to go from Option<&str> to Option<String>, by simply having:
```rust
let s: Option<&str> = Some("test");
let s: Option<String> = s.to_owned();
```

> But I don't think that's the correct semantics for an implementation of ToOwned for Option<&T>, since the contained reference is already owned.

Well no, by definition a reference is not owned (the underlying data is borrowed), so IMO it makes sense to have ToOwned on Option<&str> return an Option<String>, since that would be Option<&T> => Option<T::Owned> where T: str.

2023-09-17 03:01 UTC, dtolnay requested changes
It sounds like this PR is motivated by wanting a ToOwned implementation for Option\<\&str\>.

Option\<\&str\> already implements ToOwned though. That is why this PR fails to compile.

https://github.com/rust-lang/rust/blob/d7229c479c5f330aac55f009892f82916057cf0a/library/alloc/src/borrow.rs#L81-L94

2023-09-17 03:02 UTC, dtolnay commented
I'll go ahead and close, since I don't see any way to make this work in the way that you envisioned. Please let me know if I'm mistaken and we can reopen.

Thanks anyway for the PR!

2023-09-17 03:02 UTC, closed without merging

2023-09-19 20:23 UTC, Vanadiae commented
> It sounds like this PR is motivated by wanting a ToOwned implementation for Option<&str>.

Yes. The idea is to be able to do `let s: Option<String> = Some("string literal").to_owned();`

> Option<&str> already implements ToOwned though. That is why this PR fails to compile.

Well Option<&str> implements ToOwned through a blanket implementation because all reference types are Clone+Copy and ToOwned is implemented for types that implement Clone (so here both &str and Option<T> where T is Clone). So in practice what's actually currently working is `let s: Option<&str> = Some("string literal").to_owned();` which serves no purpose really and isn't what I'm looking for. The PR fails to compile because I implemented ToOwned in the core crate, but there ToOwned isn't available as core doesn't depend on the alloc crate), so the fix is to move my code to the alloc crate.

In any case, I'll give a shot at making it work tomorrow (or later this week).

2023-09-20 20:17 UTC, Vanadiae commented
So I tried and I can't make it work, as the `impl ToOwned for T where T: Clone` you mentioned blocks things as there'd be two implementations of ToOwned for Option<&str>… I tried implementing on Option<&str> directly (instead of Option<T> where T: ToOwned) but it then requires that I implement Borrow<Option<&str>> for Option<String>, which isn't possible as borrow() would require that I return a &Option<&str> but I can't return a reference to a Some() I'm building inside the function (obviously). I guess I'll use `opt.map(str::to_owned)` then. It's a shame it can't be made to work, but it is how it is.

FTR I pushed my work again, at https://github.com/Vanadiae/rust/commit/9a7ef39b319183ad8745a5fec112f5e26fbdb11c (the same branch, but GitHub won't show the change from this PR as it's closed)

2023-09-20 20:21 UTC, Vanadiae commented
Also FTR I found [this old forum post](https://users.rust-lang.org/t/is-there-to-owned-for-options/9279/15) where others had the same issues (and wanted Option<&str> -> Option<String> with ToOwned too).