Always evaluate constant operands in const-prop
rust-lang/rust pull request #98426
Opened 2022-06-23 15:02 UTC by b-naber

r? @lcnr

2022-06-24 09:18 UTC, lcnr reviewed
one nit, then r=me

2022-06-24 09:18 UTC, lcnr commented on src/test/ui/consts/const-eval/issue-50814.rs
> +    //~| WARNING this was previously accepted by the compiler
```suggestion
    //~| WARN this was previously accepted by the compiler but is being phased out
```
keep the two lines consistent

2022-06-24 11:28 UTC, lcnr commented
@bors try @rust-timer queue

this might actually impact perf, if unlikely

2022-06-24 11:28 UTC, rust-timer commented
Awaiting bors try build completion.

@rustbot label: +S-waiting-on-perf

2022-06-24 14:36 UTC, rust-timer commented
Finished benchmarking commit (67ad21cde5ced3782151744e37f78e23af0e8b24): [comparison url](https://perf.rust-lang.org/compare.html?start=d017d59ed013a4bc2431d023077eb7209fe9c60d&end=67ad21cde5ced3782151744e37f78e23af0e8b24&stat=instructions:u).


### [Instruction count](https://perf.rust-lang.org/compare.html?start=d017d59ed013a4bc2431d023077eb7209fe9c60d&end=67ad21cde5ced3782151744e37f78e23af0e8b24&stat=instructions:u)

- Primary benchmarks: 😿 relevant regressions found
- Secondary benchmarks: 🎉 relevant improvements found

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions 😿 <br /> (primary) | 0.3%     | 0.4% | 6         |
| Regressions 😿 <br /> (secondary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (primary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (secondary) | -0.4%    | -0.4% | 2         |
| All 😿🎉 (primary) | 0.3%     | 0.4% | 6         |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=d017d59ed013a4bc2431d023077eb7209fe9c60d&end=67ad21cde5ced3782151744e37f78e23af0e8b24&stat=max-rss)
<details>
<summary>Results</summary>


- Primary benchmarks: 😿 relevant regression found
- Secondary benchmarks: 😿 relevant regression found

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions 😿 <br /> (primary) | 1.3%     | 1.3% | 1         |
| Regressions 😿 <br /> (secondary) | 9.6%     | 9.6% | 1         |
| Improvements 🎉 <br /> (primary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (secondary) | N/A      | N/A | 0         |
| All 😿🎉 (primary) | 1.3%     | 1.3% | 1         |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=d017d59ed013a4bc2431d023077eb7209fe9c60d&end=67ad21cde5ced3782151744e37f78e23af0e8b24&stat=cycles:u)
<details>
<summary>Results</summary>


- Primary benchmarks: no relevant changes found
- Secondary benchmarks: 🎉 relevant improvement found

|            | mean[^1] | max | count[^2] |
|:----------:|:--------:|:---:|:---------:|
| Regressions 😿 <br /> (primary) | N/A      | N/A | 0         |
| Regressions 😿 <br /> (secondary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (primary) | N/A      | N/A | 0         |
| Improvements 🎉 <br /> (secondary) | -3.3%    | -3.3% | 1         |
| All 😿🎉 (primary) | N/A      | N/A | 0         |
</details>

[^1]: *the arithmetic mean of the percent change*
[^2]: *number of relevant changes*

If you disagree with this performance assessment, please file an issue in [rust-lang/rustc-perf](https://github.com/rust-lang/rustc-perf/issues/new).

Benchmarking this pull request likely means that it is perf-sensitive, so we're automatically marking it as not fit for rolling up. While you can manually mark this PR as fit for rollup, we strongly recommend not doing so since this PR may lead to changes in compiler perf.

**Next Steps**: If you can justify the regressions found in this try perf run, please indicate this with `@rustbot label: +perf-regression-triaged` along with sufficient written justification. If you cannot justify the regressions please fix the regressions and do another perf run. If the next run shows neutral or positive results, the label will be automatically removed.

@bors rollup=never
@rustbot label: +S-waiting-on-review -S-waiting-on-perf +perf-regression

2022-06-24 15:01 UTC, lcnr commented
the way that mostly `incr-unchanged` is impacted and all perf impacts are really small I think this isn't too relevant.

I consider this a bug fix.

@bors r+

2022-06-28 13:01 UTC, RalfJung commented
Const-prop does not run in the body of a `const`/`static`, does it?
Those items contain promoteds that might fail to evaluate, so it is crucial that we only evaluate those nested constants that are actually needed to compute the `const`/`static` initializer. I tried to fix this but too much code out there has such potentially failing promoteds. :(  See https://github.com/rust-lang/rust/issues/80619.

I am fairly sure I added a test for this so it's probably fine, just double-checking. :)

2022-06-28 14:30 UTC, Dylan-DPC commented
@bors retry

2022-06-28 15:36 UTC, b-naber commented
@Dylan-DPC this doesn't look spurious. Can you r- this, please?

2022-06-28 17:24 UTC, rust-log-analyzer commented
The job **`dist-i586-gnu-i586-i686-musl`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/runs/7093523598?check_suite_focus=true) [(plain)](https://github.com/rust-lang-ci/rust/commit/efa8ecf1ad8601a2b9aa8549d40052761450cc9d/checks/7093523598/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
+ Future breakage diagnostic:
+ error: any use of this value will cause an error
+   --> $DIR/issue-50814.rs:15:21
+    |
+ LL |     const MAX: u8 = A::MAX + B::MAX;
+    |                     |
+    |                     |
+    |                     attempt to compute `u8::MAX + u8::MAX`, which would overflow
+    |
+    = note: `#[deny(const_err)]` on by default
+    = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>
+ 
58 

---
To only update this specific test, also pass `--test-args consts/const-eval/issue-50814.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/consts/const-eval/issue-50814.rs" "-Zthreads=1" "--target=i586-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/const-eval/issue-50814" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/i586-unknown-linux-gnu/native/rust-test-helpers" "-Clinker=cc" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/const-eval/issue-50814/auxiliary"
stdout: none
--- stderr -------------------------------
error: any use of this value will cause an error
   |
   |
LL |     const MAX: u8 = A::MAX + B::MAX;
   |                     |
   |                     |
   |                     attempt to compute `u8::MAX + u8::MAX`, which would overflow
   |
   = note: `#[deny(const_err)]` on by default
   = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>


error[E0080]: evaluation of `foo::<T>` failed
   |
   |
LL |     &Sum::<U8,U8>::MAX

error: any use of this value will cause an error
  --> /checkout/src/test/ui/consts/const-eval/issue-50814.rs:15:21
   |
   |
LL |     const MAX: u8 = A::MAX + B::MAX;
   |                     |
   |                     |
   |                     attempt to compute `u8::MAX + u8::MAX`, which would overflow
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>

error[E0080]: evaluation of `foo::<i32>` failed
error[E0080]: evaluation of `foo::<i32>` failed
  --> /checkout/src/test/ui/consts/const-eval/issue-50814.rs:23:6
   |
LL |     &Sum::<U8,U8>::MAX


note: the above error was encountered while instantiating `fn foo::<i32>`
   |
LL |     foo(0);
   |     ^^^^^^


error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0080`.
Future incompatibility report: Future breakage diagnostic:
error: any use of this value will cause an error
   |
   |
LL |     const MAX: u8 = A::MAX + B::MAX;
   |                     |
   |                     |
   |                     attempt to compute `u8::MAX + u8::MAX`, which would overflow
   |
   = note: `#[deny(const_err)]` on by default
   = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>

Future breakage diagnostic:
error: any use of this value will cause an error
error: any use of this value will cause an error
  --> /checkout/src/test/ui/consts/const-eval/issue-50814.rs:15:21
   |
LL |     const MAX: u8 = A::MAX + B::MAX;
   |                     |
   |                     |
   |                     attempt to compute `u8::MAX + u8::MAX`, which would overflow
   |
   = note: `#[deny(const_err)]` on by default
   = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>
------------------------------------------


```

</details>

2022-07-24 00:17 UTC, JohnCSimon commented
Triage: 
@b-naber can you post the status of this PR?

2022-07-28 09:33 UTC, b-naber commented
I don't know why these lints are output on that machine (which seems to be a 64-bit machine):

```
Future incompatibility report: Future breakage diagnostic:
error: any use of this value will cause an error
  --> /checkout/src/test/ui/consts/const-eval/issue-50814.rs:15:21
   |
LL |     const MAX: u8 = A::MAX + B::MAX;
   |     ----------------^^^^^^^^^^^^^^^-
   |                     |
   |                     attempt to compute `u8::MAX + u8::MAX`, which would overflow
   |
   = note: `#[deny(const_err)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>

Future breakage diagnostic:
error: any use of this value will cause an error
  --> /checkout/src/test/ui/consts/const-eval/issue-50814.rs:15:21
   |
LL |     const MAX: u8 = A::MAX + B::MAX;
   |     ----------------^^^^^^^^^^^^^^^-
   |                     |
   |                     attempt to compute `u8::MAX + u8::MAX`, which would overflow
   |
   = note: `#[deny(const_err)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>
```

This looks like a miri-related lint, @RalfJung do you have any idea why we get those lints on that machine, but not on the ones in the PR CI?

2022-07-28 22:07 UTC, RalfJung commented
Maybe different flags? Debug vs release mode can make a difference.
Also the lints are emitted by const-prop-lint, which uses Miri but then also does a lot of other stuff, and I'm not much involved with that. Maybe @oli-obk knows more.

2022-07-28 22:08 UTC, RalfJung commented
Also make sure you rebase, there have been some changes wrt binop overflow checking a few weeks ago.

2022-07-29 12:59 UTC, oli-obk commented on compiler/rustc_mir_transform/src/const_prop.rs
> -
you need to do the same change in `const_prop_lint.rs`

2022-08-04 09:47 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/7668972434?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/5726ed77123634caaf16dca426e8a57ff2fd2ac2/checks/7668972434/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
26 
+ warning: any use of this value will cause an error
+   --> $DIR/erroneous-const.rs:6:22
+    |
+ LL |     const VOID: () = [()][2];
+    |     --------------   ^^^^^^^ index out of bounds: the length is 1 but the index is 2
+    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
+    = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>
+ 
27 error[E0080]: could not evaluate static initializer
---

+ warning: any use of this value will cause an error
+   --> $DIR/erroneous-const.rs:6:22
+    |
+ LL |     const VOID: () = [()][2];
+    |     --------------   ^^^^^^^ index out of bounds: the length is 1 but the index is 2
Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
+ note: the lint level is defined here
+   --> $DIR/erroneous-const.rs:2:9
+    |
+    |
+ LL | #![warn(const_err, unconditional_panic)]
+    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
+    = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>
+ 
+ Future breakage diagnostic:
---
To only update this specific test, also pass `--test-args consts/const-eval/erroneous-const.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/consts/const-eval/erroneous-const.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/const-eval/erroneous-const" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/const-eval/erroneous-const/auxiliary"
stdout: none
--- stderr -------------------------------
warning: this operation will panic at runtime
   |
   |
LL |     const VOID: () = [()][2]; //~WARN any use of this value will cause an error
   |                      ^^^^^^^ index out of bounds: the length is 1 but the index is 2
note: the lint level is defined here
  --> /checkout/src/test/ui/consts/const-eval/erroneous-const.rs:2:20
   |
LL | #![warn(const_err, unconditional_panic)]
LL | #![warn(const_err, unconditional_panic)]
   |                    ^^^^^^^^^^^^^^^^^^^

warning: any use of this value will cause an error
  --> /checkout/src/test/ui/consts/const-eval/erroneous-const.rs:6:22
   |
LL |     const VOID: () = [()][2]; //~WARN any use of this value will cause an error
   |     --------------   ^^^^^^^ index out of bounds: the length is 1 but the index is 2
note: the lint level is defined here
  --> /checkout/src/test/ui/consts/const-eval/erroneous-const.rs:2:9
   |
LL | #![warn(const_err, unconditional_panic)]
LL | #![warn(const_err, unconditional_panic)]
   |         ^^^^^^^^^
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>

warning: any use of this value will cause an error
  --> /checkout/src/test/ui/consts/const-eval/erroneous-const.rs:6:22
   |
LL |     const VOID: () = [()][2]; //~WARN any use of this value will cause an error
   |     --------------   ^^^^^^^ index out of bounds: the length is 1 but the index is 2
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>

error[E0080]: could not evaluate static initializer
error[E0080]: could not evaluate static initializer
  --> /checkout/src/test/ui/consts/const-eval/erroneous-const.rs:15:17
   |
LL |         let _ = PrintName::<T>::VOID; //~ERROR could not evaluate static initializer
   |                 |
   |                 referenced constant has errors
   |                 inside `no_codegen::<i32>` at /checkout/src/test/ui/consts/const-eval/erroneous-const.rs:15:17
...
---
Future incompatibility report: Future breakage diagnostic:
warning: any use of this value will cause an error
  --> /checkout/src/test/ui/consts/const-eval/erroneous-const.rs:6:22
   |
LL |     const VOID: () = [()][2]; //~WARN any use of this value will cause an error
   |     --------------   ^^^^^^^ index out of bounds: the length is 1 but the index is 2
note: the lint level is defined here
  --> /checkout/src/test/ui/consts/const-eval/erroneous-const.rs:2:9
   |
LL | #![warn(const_err, unconditional_panic)]
---
Future breakage diagnostic:
warning: any use of this value will cause an error
  --> /checkout/src/test/ui/consts/const-eval/erroneous-const.rs:6:22
   |
LL |     const VOID: () = [()][2]; //~WARN any use of this value will cause an error
   |     --------------   ^^^^^^^ index out of bounds: the length is 1 but the index is 2
note: the lint level is defined here
  --> /checkout/src/test/ui/consts/const-eval/erroneous-const.rs:2:9
   |
LL | #![warn(const_err, unconditional_panic)]
---
diff of stderr:

18   --> $DIR/issue-50814.rs:15:21
19    |
20 LL |     const MAX: u8 = A::MAX + B::MAX;
-    |                     |
-    |                     |
-    |                     attempt to compute `u8::MAX + u8::MAX`, which would overflow
+    |     -------------   ^^^^^^^^^^^^^^^ attempt to compute `u8::MAX + u8::MAX`, which would overflow
25    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
26    = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>

41 
41 
42 For more information about this error, try `rustc --explain E0080`.
43 Future incompatibility report: Future breakage diagnostic:
+ error: any use of this value will cause an error
+   --> $DIR/issue-50814.rs:15:21
+    |
+ LL |     const MAX: u8 = A::MAX + B::MAX;
+    |     -------------   ^^^^^^^^^^^^^^^ attempt to compute `u8::MAX + u8::MAX`, which would overflow
+    = note: `#[deny(const_err)]` on by default
+    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
+    = note: for more information, see issue #71800 <https://github.com/rust-lang/rust/issues/71800>
+ 
---
To only update this specific test, also pass `--test-args consts/const-eval/issue-50814.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/consts/const-eval/issue-50814.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/const-eval/issue-50814" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/consts/const-eval/issue-50814/auxiliary"
stdout: none
--- stderr -------------------------------
  --> /checkout/src/test/ui/consts/const-eva [...]

2022-08-04 10:09 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/7669570483?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/4e43e3a698b3e94507251199e2f26919a1dceda5/checks/7669570483/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
---- [mir-opt] src/test/mir-opt/remove-never-const.rs stdout ----

error: compilation failed!
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/mir-opt/remove-never-const.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "-O" "-Copt-level=1" "-Zdump-mir=all" "-Zvalidate-mir" "-Zdump-mir-exclude-pass-number" "-Zmir-pretty-relative-line-numbers=yes" "-Zmir-opt-level=4" "-Zdump-mir-dir=/checkout/obj/build/x86_64-unknown-linux-gnu/test/mir-opt/remove-never-const" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/mir-opt/remove-never-const" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "--emit" "mir,link" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/mir-opt/remove-never-const/auxiliary"
stdout: none
--- stderr -------------------------------
  --> /checkout/src/test/mir-opt/remove-never-const.rs:11:8
   |
   |
11 | struct PrintName<T>(T);
   |
   = note: `#[warn(dead_code)]` on by default

warning: function `no_codegen` is never used
warning: function `no_codegen` is never used
  --> /checkout/src/test/mir-opt/remove-never-const.rs:18:4
   |
18 | fn no_codegen<T>() {

warning: associated constant `VOID` is never used
  --> /checkout/src/test/mir-opt/remove-never-const.rs:14:11
   |
```

</details>

2022-08-04 10:14 UTC, b-naber commented
The error we get in the failing mir-opt test looks wrong.

2022-08-25 10:18 UTC, oli-obk requested changes
I guess the failing mir opt test shows that we fail to add some constants to https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/struct.Body.html#structfield.required_consts though I don't know why, how or where.

2022-08-25 10:18 UTC, oli-obk commented on .github/workflows/ci.yml
> +            env: {}
did this accidentally get added during a rebase?

2022-08-25 10:18 UTC, oli-obk commented on src/ci/github-actions/ci.yml
> +
same here

2022-08-25 12:22 UTC, RalfJung commented
> I guess the failing mir opt test shows that we fail to add some constants to https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/struct.Body.html#structfield.required_consts though I don't know why, how or where.

Promoteds don't get added there. That is by design since their evaluation cannot fail (in `fn`), or must only be attempted if they are in live code (in `const`/`static`).

Not sure if that's the issue here, though.

2022-08-30 18:49 UTC, b-naber commented
I'm going to close this, not familiar enough with const prop to tell what's really going on here.

2022-08-30 18:49 UTC, closed without merging