core::str::{chars_uppercase,chars_lowercase} iterators
rust-lang/rust pull request #98490
Opened 2022-06-25 15:46 UTC by markokr

They are based on new UnicodeConverter + UnicodeIterator
internal API that supports context-sensitivity and char expansion.

2022-06-25 15:46 UTC, rust-highfive commented
Hey! It looks like you've submitted a new PR for the library teams!

If this PR contains changes to any `rust-lang/rust` public library APIs then please comment with `@rustbot label +T-libs-api -T-libs` to tag it appropriately. If this PR contains changes to any unstable APIs please edit the PR description to add a link to the relevant [API Change Proposal](https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html) or [create one](https://github.com/rust-lang/libs-team/issues/new?assignees=&labels=api-change-proposal%2C+T-libs-api&template=api-change-proposal.md&title=%28My+API+Change+Proposal%29) if you haven't already. If you're unsure where your change falls no worries, just leave it as is and the reviewer will take a look and make a decision to forward on if necessary.

Examples of `T-libs-api` changes:

* Stabilizing library features
* Introducing insta-stable changes such as new implementations of existing stable traits on existing stable types
* Introducing new or changing existing unstable library APIs (excluding permanently unstable features / features without a tracking issue)
* Changing public documentation in ways that create new stability guarantees
* Changing observable runtime behavior of library APIs

2022-06-25 15:46 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @thomcc (or someone else) soon.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2022-06-25 16:12 UTC, thomcc commented
This is a new API, so please file an API change proposal (see the links in the bot post). That said, I'm very much in favor of this, and a quick skim (will need more thorough review once it gets API sign off) looks fine.

@rustbot label +T-libs-api -T-libs

2022-06-25 16:22 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/7054931693?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/5e2185ae6ac554d895ad495b080179518e744d40/checks/7054931693/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
configure: rust.debug-assertions := True
configure: rust.overflow-checks := True
configure: llvm.assertions      := True
configure: dist.missing-tools   := True
configure: build.configure-args := ['--enable-sccache', '--disable-manage-submodu ...
configure: writing `config.toml` in current directory
configure: 
configure: run `python /checkout/x.py --help`
configure: 
---
skip untracked path cpu-usage.csv during rustfmt invocations
Diff in /checkout/library/core/src/str/mod.rs at line 70:
 pub use iter::SplitInclusive;
 
 #[unstable(feature = "unicode_converter", issue = "none")]
-pub use iter::{CharsUppercase, CharsLowercase};
+pub use iter::{CharsLowercase, CharsUppercase};
 
 #[unstable(feature = "str_internals", issue = "none")]
 pub use validations::{next_code_point, utf8_char_width};
Diff in /checkout/library/core/src/str/mod.rs at line 842:
     pub fn char_indices(&self) -> CharIndices<'_> {
         CharIndices { front_offset: 0, iter: self.chars() }
-
 
 
     /// Returns an iterator over the [`char`]s of a string slice,
     /// converted to uppercase.
Running `"/checkout/obj/build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt" "--config-path" "/checkout" "--edition" "2021" "--unstable-features" "--skip-children" "--check" "/checkout/library/core/src/str/pattern.rs" "/checkout/library/core/src/str/validations.rs" "/checkout/library/core/src/str/error.rs" "/checkout/library/core/src/str/count.rs" "/checkout/library/core/src/str/lossy.rs" "/checkout/library/core/src/str/iter.rs" "/checkout/library/core/src/str/mod.rs" "/checkout/library/core/src/str/converts.rs"` failed.
If you're running `tidy`, try again with `--bless`. Or, if you just want to format code, run `./x.py fmt` instead.
```

</details>

2022-06-25 16:49 UTC, markokr commented
Thanks for quick feedback!

Created API proposal here: https://github.com/rust-lang/libs-team/issues/58

2022-06-25 17:01 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/7055022431?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/5a32cba9154c424d6d1fc56e991e1362e6d7318b/checks/7055022431/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Rustbook (x86_64-unknown-linux-gnu) - embedded-book
Rustbook (x86_64-unknown-linux-gnu) - edition-guide
Building stage0 tool linkchecker (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.17s
std/string/struct.String.html:1207: broken link - `std/std/primitive.str.html`
std/string/struct.String.html:1238: broken link - `std/std/primitive.str.html`
alloc/string/struct.String.html:1319: broken link - `alloc/std/primitive.str.html`
alloc/string/struct.String.html:1350: broken link - `alloc/std/primitive.str.html`
number of HTML files scanned: 32361
number of HTML redirects found: 10102
number of links checked: 2261739
number of links ignored due to external: 113110
```

</details>

2022-06-25 17:39 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-12`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/7055204893?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/38404ada89fbf4e22bfd16979a78d6782482f1e9/checks/7055204893/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Rustbook (x86_64-unknown-linux-gnu) - embedded-book
Rustbook (x86_64-unknown-linux-gnu) - edition-guide
Building stage0 tool linkchecker (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.16s
std/primitive.str.html:406: broken link - `/checkout/obj/build/x86_64-unknown-linux-gnu/std/primitive.str.html`
std/primitive.str.html:437: broken link - `/checkout/obj/build/x86_64-unknown-linux-gnu/std/primitive.str.html`
core/primitive.str.html:406: broken link - `/checkout/obj/build/x86_64-unknown-linux-gnu/std/primitive.str.html`
core/primitive.str.html:437: broken link - `/checkout/obj/build/x86_64-unknown-linux-gnu/std/primitive.str.html`
number of HTML files scanned: 32361
number of HTML redirects found: 10102
number of links checked: 2261739
number of links ignored due to external: 113110
```

</details>

2022-08-08 10:21 UTC, thomcc requested changes
Hmm, the implementation here is more generic than it needs to be, and more complex as a result. You should not do this via a trait IMO -- The way you've decoupled it here also requires more bounds-checks which shouldn't be needed, and avoiding them in this interface would require otherwise-unnecessary unsafe code (to be clear: I'm not asking for you to add unsafe to this).

I think `chars_lowercase` should be a bit more like what you'd get by manually performing `s.chars().flat_map(|c| c.to_lowercase())`. Uppercase is the complex one, but should be handled directly, closer to the implementation in liballoc.

Let me know if you need an example of what I mean.

2022-08-08 10:21 UTC, thomcc commented on library/core/src/str/iter.rs
> +trait UnicodeConverter {
I think this shouldn't use a trait. I think this ends up complicating things quite a bit and makes the implementation overly generic.

2022-08-08 10:21 UTC, thomcc commented on library/core/src/str/iter.rs
> +    fwd: [Option<char>; 2],
nit: forward/backward instead of `fwd/bwd`.

2022-08-08 10:21 UTC, thomcc commented on library/alloc/src/lib.rs
> +#![feature(unicode_converter)]
This feature name is too generic, perhaps something more like `#![feature(str_chars_casemapped)]`?

2022-10-02 21:14 UTC, JohnCSimon commented
Ping from triage: 
@markokr what is the status of this PR?

2023-01-01 18:46 UTC, JohnCSimon commented
@markokr 
Ping from triage: I'm closing this due to inactivity, Please reopen when you are ready to continue with this. 
Note: if you do please open the PR **BEFORE** you push to it, else you won't be able to reopen - this is a quirk of github. 
Thanks for your contribution.

@rustbot label: +S-inactive

2023-01-01 18:46 UTC, closed without merging