Remove ReEmpty
rust-lang/rust pull request #98559
Opened 2022-06-27 01:28 UTC by jackh726

Based on #98542

r? rust-lang/types

2022-06-27 02:18 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/7064830716?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/a0a59515be4288754ff2c3417d97909dbb3f36b6/checks/7064830716/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking askama_shared v0.12.0
   Compiling askama_derive v0.11.0
    Checking askama v0.11.0
    Checking rustdoc v0.0.0 (/checkout/src/librustdoc)
error[E0531]: cannot find tuple struct or tuple variant `ReEmpty` in module `ty`
   --> src/librustdoc/clean/mod.rs:238:19
    |
238 |             | ty::ReEmpty(_)
    |                   ^^^^^^^ not found in `ty`

error[E0599]: no method named `is_empty` found for reference `&rustc_middle::ty::Region<'tcx>` in the current scope
   --> src/librustdoc/clean/mod.rs:332:14
    |
332 |         if a.is_empty() && b.is_empty() {
    |              ^^^^^^^^ method not found in `&rustc_middle::ty::Region<'tcx>`

error[E0599]: no method named `is_empty` found for reference `&rustc_middle::ty::Region<'tcx>` in the current scope
   --> src/librustdoc/clean/mod.rs:332:30
    |
332 |         if a.is_empty() && b.is_empty() {
    |                              ^^^^^^^^ method not found in `&rustc_middle::ty::Region<'tcx>`

error[E0599]: no method named `is_empty` found for reference `&rustc_middle::ty::Region<'tcx>` in the current scope
   --> src/librustdoc/clean/mod.rs:349:15
    |
349 |         if lt.is_empty() {
    |               ^^^^^^^^ method not found in `&rustc_middle::ty::Region<'tcx>`
Some errors have detailed explanations: E0531, E0599.
For more information about an error, try `rustc --explain E0531`.
error: could not compile `rustdoc` due to 4 previous errors
Build completed unsuccessfully in 0:03:16
```

</details>

2022-06-27 03:35 UTC, HgAmiui9 approved these changes

2022-06-28 00:09 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/7083088442?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/531c765624a918bf450be55337f9763e30baebb0/checks/7083088442/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking askama_shared v0.12.0
   Compiling askama_derive v0.11.0
    Checking askama v0.11.0
    Checking rustdoc v0.0.0 (/checkout/src/librustdoc)
error[E0531]: cannot find tuple struct or tuple variant `ReEmpty` in module `ty`
   --> src/librustdoc/clean/mod.rs:238:19
    |
238 |             | ty::ReEmpty(_)
    |                   ^^^^^^^ not found in `ty`

error[E0599]: no method named `is_empty` found for reference `&rustc_middle::ty::Region<'tcx>` in the current scope
   --> src/librustdoc/clean/mod.rs:332:14
    |
332 |         if a.is_empty() && b.is_empty() {
    |              ^^^^^^^^ method not found in `&rustc_middle::ty::Region<'tcx>`

error[E0599]: no method named `is_empty` found for reference `&rustc_middle::ty::Region<'tcx>` in the current scope
   --> src/librustdoc/clean/mod.rs:332:30
    |
332 |         if a.is_empty() && b.is_empty() {
    |                              ^^^^^^^^ method not found in `&rustc_middle::ty::Region<'tcx>`

error[E0599]: no method named `is_empty` found for reference `&rustc_middle::ty::Region<'tcx>` in the current scope
   --> src/librustdoc/clean/mod.rs:349:15
    |
349 |         if lt.is_empty() {
    |               ^^^^^^^^ method not found in `&rustc_middle::ty::Region<'tcx>`
Some errors have detailed explanations: E0531, E0599.
For more information about an error, try `rustc --explain E0531`.
error: could not compile `rustdoc` due to 4 previous errors
Build completed unsuccessfully in 0:03:47
```

</details>

2022-06-28 04:43 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/7085921743?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/b503be7349d826a0d6401d6b39ffdb287cc9ef5f/checks/7085921743/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking askama_shared v0.12.0
   Compiling askama_derive v0.11.0
    Checking askama v0.11.0
    Checking rustdoc v0.0.0 (/checkout/src/librustdoc)
error[E0531]: cannot find tuple struct or tuple variant `ReEmpty` in module `ty`
   --> src/librustdoc/clean/mod.rs:238:19
    |
238 |             | ty::ReEmpty(_)
    |                   ^^^^^^^ not found in `ty`

error[E0599]: no method named `is_empty` found for reference `&rustc_middle::ty::Region<'tcx>` in the current scope
   --> src/librustdoc/clean/mod.rs:332:14
    |
332 |         if a.is_empty() && b.is_empty() {
    |              ^^^^^^^^ method not found in `&rustc_middle::ty::Region<'tcx>`

error[E0599]: no method named `is_empty` found for reference `&rustc_middle::ty::Region<'tcx>` in the current scope
   --> src/librustdoc/clean/mod.rs:332:30
    |
332 |         if a.is_empty() && b.is_empty() {
    |                              ^^^^^^^^ method not found in `&rustc_middle::ty::Region<'tcx>`

error[E0599]: no method named `is_empty` found for reference `&rustc_middle::ty::Region<'tcx>` in the current scope
   --> src/librustdoc/clean/mod.rs:349:15
    |
349 |         if lt.is_empty() {
    |               ^^^^^^^^ method not found in `&rustc_middle::ty::Region<'tcx>`
Some errors have detailed explanations: E0531, E0599.
For more information about an error, try `rustc --explain E0531`.
error: could not compile `rustdoc` due to 4 previous errors
Build completed unsuccessfully in 0:03:28
```

</details>

2022-06-28 04:46 UTC, jackh726 commented on compiler/rustc_borrowck/src/region_infer/opaque_types.rs
> +                        .unwrap_or(infcx.tcx.lifetimes.re_erased),
This is problematic (leads to an ICE when compiling rustc_data_structures). I have to look into this code a bit and figure out a fix.

2022-07-02 02:52 UTC, jackh726 commented
Blocked on #98795 and some fiddling with the best way to the `infer_opaque_types` code.

2022-07-02 03:11 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/7159234041?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/fdf85dc532328689185746eb48de5d0db86e3e63/checks/7159234041/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking askama_shared v0.12.0
   Compiling askama_derive v0.11.0
    Checking askama v0.11.0
    Checking rustdoc v0.0.0 (/checkout/src/librustdoc)
error[E0531]: cannot find tuple struct or tuple variant `ReEmpty` in module `ty`
   --> src/librustdoc/clean/mod.rs:238:19
    |
238 |             | ty::ReEmpty(_)
    |                   ^^^^^^^ not found in `ty`

error[E0599]: no method named `is_empty` found for reference `&rustc_middle::ty::Region<'tcx>` in the current scope
   --> src/librustdoc/clean/mod.rs:332:14
    |
332 |         if a.is_empty() && b.is_empty() {
    |              ^^^^^^^^ method not found in `&rustc_middle::ty::Region<'tcx>`

error[E0599]: no method named `is_empty` found for reference `&rustc_middle::ty::Region<'tcx>` in the current scope
   --> src/librustdoc/clean/mod.rs:332:30
    |
332 |         if a.is_empty() && b.is_empty() {
    |                              ^^^^^^^^ method not found in `&rustc_middle::ty::Region<'tcx>`

error[E0599]: no method named `is_empty` found for reference `&rustc_middle::ty::Region<'tcx>` in the current scope
   --> src/librustdoc/clean/mod.rs:349:15
    |
349 |         if lt.is_empty() {
    |               ^^^^^^^^ method not found in `&rustc_middle::ty::Region<'tcx>`
Some errors have detailed explanations: E0531, E0599.
For more information about an error, try `rustc --explain E0531`.
error: could not compile `rustdoc` due to 4 previous errors
Build completed unsuccessfully in 0:03:53
```

</details>

2022-09-08 03:22 UTC, jackh726 commented
I think this is good to go. The problem I was facing before went away on its own.

2022-09-08 07:25 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/8241324774?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/fa7b0bb634228071d59fd8a4f42a9fa2348468f2/checks/8241324774/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking cargo_metadata v0.14.0
    Checking rustfix v0.6.1
    Checking rustc-workspace-hack v1.0.0 (/checkout/src/tools/rustc-workspace-hack)
    Checking clippy_lints v0.1.65 (/checkout/src/tools/clippy/clippy_lints)
error[E0609]: no field `re_root_empty` on type `rustc_middle::ty::context::CommonLifetimes<'_>`
   --> src/tools/clippy/clippy_lints/src/needless_pass_by_value.rs:176:82
    |
176 |                         let ty_empty_region = cx.tcx.mk_imm_ref(cx.tcx.lifetimes.re_root_empty, ty);
    |
    |
    = note: available fields are: `re_static`, `re_erased`
For more information about this error, try `rustc --explain E0609`.
error: could not compile `clippy_lints` due to previous error
Build completed unsuccessfully in 0:03:49
```

</details>

2022-09-08 07:45 UTC, oli-obk requested changes

2022-09-08 07:45 UTC, oli-obk commented on compiler/rustc_infer/src/infer/error_reporting/mod.rs
> +                        let sub_r = self.tcx.mk_region(ty::ReErased);
```suggestion
                        let sub_r = self.tcx.lifetimes.re_erased;
```

2022-09-08 07:45 UTC, oli-obk commented on compiler/rustc_trait_selection/src/traits/wf.rs
> +#[tracing::instrument(skip(infcx))]
```suggestion
#[instrument(skip(infcx), ret)]
```

2022-09-08 07:45 UTC, oli-obk commented on compiler/rustc_trait_selection/src/traits/wf.rs
> +    obligations
The `ret` in `#[instrument]` does exactly this

2022-09-08 07:45 UTC, oli-obk commented on compiler/rustc_typeck/src/check/wfcheck.rs
> +    #[tracing::instrument(level = "debug", skip(self))]
```suggestion
    #[instrument(level = "debug", skip(self))]
```

2022-09-08 07:45 UTC, oli-obk commented on compiler/rustc_typeck/src/collect.rs
> +#[tracing::instrument(level = "debug", skip(tcx))]
```suggestion
#[instrument(level = "debug", skip(tcx))]
```

2022-09-08 07:45 UTC, oli-obk commented on compiler/rustc_typeck/src/collect.rs
> +#[tracing::instrument(level = "debug", skip(tcx))]
```suggestion
#[instrument(level = "debug", skip(tcx))]
```

2022-09-08 07:45 UTC, oli-obk commented on compiler/rustc_infer/src/infer/lexical_region_resolve/mod.rs
> +                };
except for placeholder handling, this is exactly the same as the `lub` computation in `fn expansion`. Maybe pull it out into a function (that returns `Result<Region, Placeholder>`?)

2022-09-08 07:45 UTC, oli-obk commented on compiler/rustc_infer/src/infer/lexical_region_resolve/mod.rs
> +                return a_ui.min(b_ui) == b_ui;
no `return` needed in this function, these are all the trailing expression

2022-09-08 22:30 UTC, rust-log-analyzer commented
The job **`mingw-check`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/8259763217?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/e9752396f17a19eb8afd9d708368694d17f9c317/checks/8259763217/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
    Checking cargo_metadata v0.14.0
    Checking rustfix v0.6.1
    Checking rustc-workspace-hack v1.0.0 (/checkout/src/tools/rustc-workspace-hack)
    Checking clippy_lints v0.1.65 (/checkout/src/tools/clippy/clippy_lints)
error[E0609]: no field `re_root_empty` on type `rustc_middle::ty::context::CommonLifetimes<'_>`
   --> src/tools/clippy/clippy_lints/src/needless_pass_by_value.rs:176:82
    |
176 |                         let ty_empty_region = cx.tcx.mk_imm_ref(cx.tcx.lifetimes.re_root_empty, ty);
    |
    |
    = note: available fields are: `re_static`, `re_erased`
For more information about this error, try `rustc --explain E0609`.
error: could not compile `clippy_lints` due to previous error
Build completed unsuccessfully in 0:03:39
```

</details>

2022-09-08 23:34 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/runs/8260286057?check_suite_focus=true) [(plain)](https://github.com/rust-lang/rust/commit/92ced717ef4d0fffe342b1e67499d81171127e88/checks/8260286057/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Some tests failed in compiletest suite=mir-opt mode=mir-opt host=x86_64-unknown-linux-gnu target=i686-unknown-linux-gnu
.........
failures:

---- [mir-opt] src/test/mir-opt/nll/region-subtyping-basic.rs stdout ----
7 | Inferred Region Values
8 | '_#0r | U0 | {bb0[0..=8], bb1[0..=7], bb2[0..=3], bb3[0..=3], bb4[0..=1], bb5[0..=2], bb6[0..=5], bb7[0], '_#0r, '_#1r}
9 | '_#1r | U0 | {bb0[0..=8], bb1[0..=7], bb2[0..=3], bb3[0..=3], bb4[0..=1], bb5[0..=2], bb6[0..=5], bb7[0], '_#1r}
- | '_#2r | U0 | {}
- | '_#3r | U0 | {bb1[0..=7], bb2[0..=2]}
- | '_#4r | U0 | {bb1[1..=7], bb2[0..=2]}
- | '_#5r | U0 | {bb1[4..=7], bb2[0..=2]}
+ | '_#2r | U0 | {bb1[0..=7], bb2[0..=2]}
+ | '_#3r | U0 | {bb1[1..=7], bb2[0..=2]}
+ | '_#4r | U0 | {bb1[4..=7], bb2[0..=2]}
15 | Inference Constraints
15 | Inference Constraints
16 | '_#0r live at {bb0[0..=8], bb1[0..=7], bb2[0..=3], bb3[0..=3], bb4[0..=1], bb5[0..=2], bb6[0..=5], bb7[0]}

17 | '_#1r live at {bb0[0..=8], bb1[0..=7], bb2[0..=3], bb3[0..=3], bb4[0..=1], bb5[0..=2], bb6[0..=5], bb7[0]}
- | '_#3r live at {bb1[0]}
- | '_#4r live at {bb1[1..=3]}
- | '_#5r live at {bb1[4..=7], bb2[0..=2]}
- | '_#3r: '_#4r due to Assignment at Single(bb1[0]) ($DIR/region-subtyping-basic.rs:18:13: 18:18 (#0)
- | '_#4r: '_#5r due to Assignment at Single(bb1[3]) ($DIR/region-subtyping-basic.rs:19:13: 19:14 (#0)
+ | '_#2r live at {bb1[0]}
+ | '_#3r live at {bb1[1..=3]}
+ | '_#4r live at {bb1[4..=7], bb2[0..=2]}
+ | '_#2r: '_#3r due to Assignment at Single(bb1[0]) ($DIR/region-subtyping-basic.rs:18:13: 18:18 (#0)
+ | '_#3r: '_#4r due to Assignment at Single(bb1[3]) ($DIR/region-subtyping-basic.rs:19:13: 19:14 (#0)
24 fn main() -> () {
24 fn main() -> () {
25     let mut _0: ();                      // return place in scope 0 at $DIR/region-subtyping-basic.rs:+0:11: +0:11

33     let _10: bool;                       // in scope 0 at $DIR/region-subtyping-basic.rs:+7:9: +7:18
34     scope 1 {
35         debug v => _1;                   // in scope 1 at $DIR/region-subtyping-basic.rs:+1:9: +1:14
-         let _2: &'_#4r usize;            // in scope 1 at $DIR/region-subtyping-basic.rs:+2:9: +2:10
+         let _2: &'_#3r usize;            // in scope 1 at $DIR/region-subtyping-basic.rs:+2:9: +2:10
37         scope 2 {
38             debug p => _2;               // in scope 2 at $DIR/region-subtyping-basic.rs:+2:9: +2:10
-             let _6: &'_#5r usize;        // in scope 2 at $DIR/region-subtyping-basic.rs:+3:9: +3:10
+             let _6: &'_#4r usize;        // in scope 2 at $DIR/region-subtyping-basic.rs:+3:9: +3:10
40             scope 3 {
41                 debug q => _6;           // in scope 3 at $DIR/region-subtyping-basic.rs:+3:9: +3:10

56     }
57 
58     bb1: {
58     bb1: {
-         _2 = &'_#3r _1[_3];              // bb1[0]: scope 1 at $DIR/region-subtyping-basic.rs:+2:13: +2:18
+         _2 = &'_#2r _1[_3];              // bb1[0]: scope 1 at $DIR/region-subtyping-basic.rs:+2:13: +2:18
60         FakeRead(ForLet(None), _2);      // bb1[1]: scope 1 at $DIR/region-subtyping-basic.rs:+2:9: +2:10
61         StorageLive(_6);                 // bb1[2]: scope 2 at $DIR/region-subtyping-basic.rs:+3:9: +3:10
62         _6 = _2;                         // bb1[3]: scope 2 at $DIR/region-subtyping-basic.rs:+3:13: +3:14

thread '[mir-opt] src/test/mir-opt/nll/region-subtyping-basic.rs' panicked at 'Actual MIR output differs from expected MIR output /checkout/src/test/mir-opt/nll/region_subtyping_basic.main.nll.0.32bit.mir', src/tools/compiletest/src/runtest.rs:3516:25


failures:
    [mir-opt] src/test/mir-opt/nll/region-subtyping-basic.rs
```

</details>

2022-09-09 00:53 UTC, jackh726 commented
I'm a bit stumped. The failing test passes for me locally.

2022-09-09 00:57 UTC, jackh726 commented
I guess that's the 32bit test failing. Should be fixed now.

2022-09-09 10:30 UTC, oli-obk commented
@bors r+

2022-09-09 12:00 UTC, rust-log-analyzer commented
The job **`x86_64-gnu-llvm-13-stage1`** failed! Check out the build log: [(web)](https://github.com/rust-lang-ci/rust/runs/8269374409?check_suite_focus=true) [(plain)](https://github.com/rust-lang-ci/rust/commit/632a942a2a7c2b0ee1f84a9234d4a04804177a41/checks/8269374409/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
---- [ui] src/test/ui/impl-trait/in-trait/success.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 101
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/bin/rustc" "/checkout/src/test/ui/impl-trait/in-trait/success.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-trait/in-trait/success" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/impl-trait/in-trait/success/auxiliary"
stdout: none
--- stderr -------------------------------
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', /cargo/registry/src/github.com-1ecc6299db9ec823/ena-0.14.0/src/snapshot_vec.rs:199:10
   0:     0x7f4038cd0acd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7aceaaec384abd8d
   1:     0x7f4038d36239 - core::fmt::write::h1935094ec1b611e9
   2:     0x7f4038cc1b11 - std::io::Write::write_fmt::h924a08855ab35277
   2:     0x7f4038cc1b11 - std::io::Write::write_fmt::h924a08855ab35277
   3:     0x7f4038cd3a7e - std::panicking::default_hook::{{closure}}::hdcba8bc567463877
   4:     0x7f4038cd3747 - std::panicking::default_hook::h5e023012d652ad1c
   5:     0x7f403968e2c4 - rustc_driver[2b12b44ab49049e7]::DEFAULT_HOOK::{closure#0}::{closure#0}
   6:     0x7f4038cd4221 - std::panicking::rust_panic_with_hook::hc50598e1e398727d
   7:     0x7f4038cd4047 - std::panicking::begin_panic_handler::{{closure}}::h2c1a8ae8110b48ef
   8:     0x7f4038cd1034 - std::sys_common::backtrace::__rust_end_short_backtrace::h4f0e14b26c3ea417
   9:     0x7f4038cd3d22 - rust_begin_unwind
  10:     0x7f4038c87cc3 - core::panicking::panic_fmt::h577a3b3df57afc41
  11:     0x7f4038c87c02 - core::panicking::panic_bounds_check::hea803f8b900e4221
  12:     0x7f403bfb80b0 - <ena[4ab445f0354216d2]::snapshot_vec::SnapshotVec<ena[4ab445f0354216d2]::unify::backing_vec::Delegate<rustc_middle[df447d51b984e2b2]::infer::unify_key::RegionVidKey>, &mut alloc[45623a189840f9f9]::vec::Vec<ena[4ab445f0354216d2]::unify::VarValue<rustc_middle[df447d51b984e2b2]::infer::unify_key::RegionVidKey>>, &mut rustc_infer[a1a39e651f51b0c1]::infer::undo_log::InferCtxtUndoLogs> as core[c1e30f1bd259d119]::ops::index::Index<usize>>::index
  13:     0x7f403bfd13d1 - <ena[4ab445f0354216d2]::unify::UnificationTable<ena[4ab445f0354216d2]::unify::backing_vec::InPlace<rustc_middle[df447d51b984e2b2]::infer::unify_key::RegionVidKey, &mut alloc[45623a189840f9f9]::vec::Vec<ena[4ab445f0354216d2]::unify::VarValue<rustc_middle[df447d51b984e2b2]::infer::unify_key::RegionVidKey>>, &mut rustc_infer[a1a39e651f51b0c1]::infer::undo_log::InferCtxtUndoLogs>>>::uninlined_get_root_key
  14:     0x7f403bf2a93e - <rustc_infer[a1a39e651f51b0c1]::infer::region_constraints::RegionConstraintCollector>::opportunistic_resolve_var
  15:     0x7f403bf07896 - <rustc_infer[a1a39e651f51b0c1]::infer::resolve::OpportunisticRegionResolver as rustc_middle[df447d51b984e2b2]::ty::fold::TypeFolder>::fold_region
  16:     0x7f403bf0fa1f - <rustc_middle[df447d51b984e2b2]::ty::Ty as rustc_middle[df447d51b984e2b2]::ty::fold::TypeSuperFoldable>::super_fold_with::<rustc_infer[a1a39e651f51b0c1]::infer::resolve::OpportunisticRegionResolver>
  17:     0x7f403bf07822 - <rustc_infer[a1a39e651f51b0c1]::infer::resolve::OpportunisticRegionResolver as rustc_middle[df447d51b984e2b2]::ty::fold::TypeFolder>::fold_ty
  18:     0x7f403bdcaba4 - <rustc_middle[df447d51b984e2b2]::ty::Term as rustc_middle[df447d51b984e2b2]::ty::fold::TypeFoldable>::fold_with::<rustc_infer[a1a39e651f51b0c1]::infer::resolve::OpportunisticRegionResolver>
  19:     0x7f403bcf7f0d - rustc_trait_selection[9ce78282165ecf4e]::traits::project::confirm_candidate
  20:     0x7f403bd048c3 - rustc_trait_selection[9ce78282165ecf4e]::traits::project::opt_normalize_projection_type
  21:     0x7f403bcf509a - rustc_trait_selection[9ce78282165ecf4e]::traits::project::normalize_projection_type
  22:     0x7f403ab01c7c - <rustc_infer[a1a39e651f51b0c1]::infer::InferCtxtBuilder as rustc_trait_selection[9ce78282165ecf4e]::infer::InferCtxtBuilderExt>::enter_canonical_trait_query::<rustc_middle[df447d51b984e2b2]::ty::ParamEnvAnd<rustc_middle[df447d51b984e2b2]::ty::sty::ProjectionTy>, rustc_middle[df447d51b984e2b2]::traits::query::NormalizationResult, rustc_traits[f93aaf4a965790c7]::normalize_projection_ty::normalize_projection_ty::{closure#0}>
  23:     0x7f403aae9b38 - rustc_traits[f93aaf4a965790c7]::normalize_projection_ty::normalize_projection_ty
  24:     0x7f403b3525a7 - rustc_query_system[75c107cad7cbc69e]::query::plumbing::get_query::<rustc_query_impl[42ef33d4955bd146]::queries::normalize_projection_ty, rustc_query_impl[42ef33d4955bd146]::plumbing::QueryCtxt>
  25:     0x7f403b1bbc0f - <rustc_query_impl[42ef33d4955bd146]::Queries as rustc_middle[df447d51b984e2b2]::ty::query::QueryEngine>::normalize_projection_ty
  26:     0x7f403bdf8a8d - <rustc_trait_selection[9ce78282165ecf4e]::traits::query::normalize::QueryNormalizer as rustc_middle[df447d51b984e2b2]::ty::fold::FallibleTypeFolder>::try_fold_ty
  27:     0x7f403aa01d68 - <&rustc_middle[df447d51b984e2b2]::ty::list::List<rustc_middle[df447d51b984e2b2]::ty::Ty> as rustc_middle[df447d51b984e2b2]::ty::fold::TypeFoldable>::try_fold_with::<rustc_trait_selection[9ce78282165ecf4e]::traits::query::normalize::QueryNormalizer>
  28:     0x7f403aa9cc46 - <rustc_middle[df447d51b984e2b2]::ty::sty::FnSig as rustc_middle[df447d51b984e2b2]::ty::fold::TypeFoldable>::try_fold_with::<rustc_trait_selection[9ce78282165ecf4e]::traits::query::normalize::QueryNormalizer>
  29:     0x7f403ab12645 - <rustc_infer[a1a39e651f51b0c1]::infer::at::At as rustc_trait_selection[9ce78282165ecf4e]::traits::query::normalize::AtExt>::normalize::<rustc_middle[df447d51b984e2b2]::ty::sty::FnSig>
  30:     0x7f403aa30327 - rustc_traits[f93aaf4a965790c7]::type_op::type_op_normalize::<rustc_middle[df447d51b984e2b2]::ty::sty::FnSig>
  31:     0x7f403aafcde3 - <rustc_infer[a1a39e651f51b0c1]::infer::InferCtxtBuilder as rustc_trait_selection[9ce78282165ecf4e]::infer::InferCtxtBuilderExt>::enter_canonical_trait_query::<rustc_middle[df447d51b984e2b2]::ty::ParamEnvAnd<rustc_middle[df447d51b984e2b2]::traits::query::type_op::Normalize<rustc_middle[df447d51b984e2b2]::ty::sty::FnSig>>, rustc_middle[df447d51b984e2b2]::ty::sty::FnSig, rustc_traits[f93aaf4a965790c7]::type_op::type_op_normalize<rustc_middle[df447d51b984e2b2]::ty::sty::FnSig>>
  32:     0x7f403aa30527 - rustc_traits[f93aaf4a965790c7]::type_op::type_op_normalize_fn_sig
  33:     0x7f403b3567f7 - rustc_query_system[75c107cad7cbc69e]::query::plumbing::get_query::<rustc_query_impl[42ef33d4955bd146]::queries::type_op_normalize_fn_sig, rustc_query_impl[42ef33d4955bd146]::plumbing::QueryCtxt>
  34:     0x7f403b1c263f - <rustc_query_impl[42ef33d4955bd146]::Queries as rustc_middle[df447d51b984e2b2]::ty::query::QueryEngine>::type_op_normalize_fn_sig
  35:     0x7f403be3ecd6 - <rustc_middle[df447d51b984e2b2]::ty::sty::FnSig as rustc_trait_selection[9ce78282165ecf4e]::traits::query::type_op::normalize::Normalizable>::type_op_method
  36:     0x7f403a731019 - <rustc_middle[df447d51b984e2b2]::traits::query::type_op::Normalize<rustc_middle[df447d51b984e2b2]::ty::sty::FnSig> as rustc_trait_selection[9ce78282165ecf4e]::tra [...]

2022-09-09 12:53 UTC, oli-obk commented
cc @compiler-errors ICEy interactions with 🐸 types (RPITIT)

2022-09-09 13:27 UTC, compiler-errors commented
I'll look into it this weekend

2022-09-10 19:31 UTC, jackh726 commented
#101614 has merged

@bors retry

2022-09-10 20:18 UTC, fbstj commented on compiler/rustc_infer/src/infer/lexical_region_resolve/mod.rs
> +                a_ui.min(b_ui) == b_ui
is this not `a >= b` ? or am I misunderstanding what `min` is doing?

2022-09-10 23:13 UTC, merged

2022-09-11 03:20 UTC, rust-timer commented
Finished benchmarking commit (2287107588d92889d282e6cd3c1ca5df34cd34a5): [comparison URL](https://perf.rust-lang.org/compare.html?start=4a6ac3c225d6322caaf0ef86623cddc74e5260c6&end=2287107588d92889d282e6cd3c1ca5df34cd34a5&stat=instructions:u).

### Overall result: ✅ improvements - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=4a6ac3c225d6322caaf0ef86623cddc74e5260c6&end=2287107588d92889d282e6cd3c1ca5df34cd34a5&stat=instructions:u)
This is a highly reliable metric that was used to determine the overall result at the top of this comment.

|            | mean[^1] | range | count[^2] |
|:----------:|:--------:|:-----:|:---------:|
| Regressions ❌ <br /> (primary) | -        | -     | 0         |
| Regressions ❌ <br /> (secondary) | -        | -     | 0         |
| Improvements ✅ <br /> (primary) | -0.7%    | [-1.3%, -0.3%] | 5         |
| Improvements ✅ <br /> (secondary) | -3.3%    | [-3.8%, -3.0%] | 6         |
| All ❌✅ (primary) | -0.7%    | [-1.3%, -0.3%] | 5         |

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=4a6ac3c225d6322caaf0ef86623cddc74e5260c6&end=2287107588d92889d282e6cd3c1ca5df34cd34a5&stat=max-rss)
<details>
<summary>Results</summary>

This is a less reliable metric that may be of interest but was not used to determine the overall result at the top of this comment.

|            | mean[^1] | range | count[^2] |
|:----------:|:--------:|:-----:|:---------:|
| Regressions ❌ <br /> (primary) | 2.7%     | [2.7%, 2.7%] | 1         |
| Regressions ❌ <br /> (secondary) | -        | -     | 0         |
| Improvements ✅ <br /> (primary) | -        | -     | 0         |
| Improvements ✅ <br /> (secondary) | -2.0%    | [-3.3%, -0.7%] | 2         |
| All ❌✅ (primary) | 2.7%     | [2.7%, 2.7%] | 1         |
</details>

### [Cycles](https://perf.rust-lang.org/compare.html?start=4a6ac3c225d6322caaf0ef86623cddc74e5260c6&end=2287107588d92889d282e6cd3c1ca5df34cd34a5&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.

[^1]: *the arithmetic mean of the percent change*
[^2]: *number of relevant changes*

2022-09-17 13:47 UTC, yshui commented
@jackh726 seeing an ICE which bisected to this merge, stacktrace:

```
thread 'rustc' panicked at 'Box<dyn Any>', /rustc/2287107588d92889d282e6cd3c1ca5df34cd34a5/compiler/rustc_errors/src/lib.rs:1460:9
stack backtrace:
   0:     0x7fe0b51b8eb0 - std::backtrace_rs::backtrace::libunwind::trace::h1c0da60f68cd52d0
                               at /rustc/2287107588d92889d282e6cd3c1ca5df34cd34a5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7fe0b51b8eb0 - std::backtrace_rs::backtrace::trace_unsynchronized::he45e10f3230d4a33
                               at /rustc/2287107588d92889d282e6cd3c1ca5df34cd34a5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fe0b51b8eb0 - std::sys_common::backtrace::_print_fmt::hb7277fb151a2024e
                               at /rustc/2287107588d92889d282e6cd3c1ca5df34cd34a5/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fe0b51b8eb0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb354ed7aeb9d4ccd
                               at /rustc/2287107588d92889d282e6cd3c1ca5df34cd34a5/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fe0b5213f0e - core::fmt::write::hec67a20123752277
                               at /rustc/2287107588d92889d282e6cd3c1ca5df34cd34a5/library/core/src/fmt/mod.rs:1202:17
   5:     0x7fe0b51a9595 - std::io::Write::write_fmt::h86bc6ecfe8b97adf
                               at /rustc/2287107588d92889d282e6cd3c1ca5df34cd34a5/library/std/src/io/mod.rs:1679:15
   6:     0x7fe0b51bbb63 - std::sys_common::backtrace::_print::he9b60e75426b4e2c
                               at /rustc/2287107588d92889d282e6cd3c1ca5df34cd34a5/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fe0b51bbb63 - std::sys_common::backtrace::print::h0094cd5e7dc5d2a3
                               at /rustc/2287107588d92889d282e6cd3c1ca5df34cd34a5/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fe0b51bbb63 - std::panicking::default_hook::{{closure}}::he873f51ceb39b7ab
                               at /rustc/2287107588d92889d282e6cd3c1ca5df34cd34a5/library/std/src/panicking.rs:295:22
   9:     0x7fe0b51bb84f - std::panicking::default_hook::hbd7e8dfbbdcbdd8d
                               at /rustc/2287107588d92889d282e6cd3c1ca5df34cd34a5/library/std/src/panicking.rs:314:9
  10:     0x7fe0b7a27561 - rustc_driver[45772c003865a0c4]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fe0b51bc39d - std::panicking::rust_panic_with_hook::h440e574bebabd5f6
                               at /rustc/2287107588d92889d282e6cd3c1ca5df34cd34a5/library/std/src/panicking.rs:702:17
  12:     0x7fe0b8a49871 - std[2c47335e2f8b42a0]::panicking::begin_panic::<rustc_errors[4c251b6c70f47263]::ExplicitBug>::{closure#0}
  13:     0x7fe0b8a48b96 - std[2c47335e2f8b42a0]::sys_common::backtrace::__rust_end_short_backtrace::<std[2c47335e2f8b42a0]::panicking::begin_panic<rustc_errors[4c251b6c70f47263]::ExplicitBug>::{closure#0}, !>
  14:     0x7fe0b89d46d6 - std[2c47335e2f8b42a0]::panicking::begin_panic::<rustc_errors[4c251b6c70f47263]::ExplicitBug>
  15:     0x7fe0b8a457e6 - std[2c47335e2f8b42a0]::panic::panic_any::<rustc_errors[4c251b6c70f47263]::ExplicitBug>
  16:     0x7fe0b8a4456d - <rustc_errors[4c251b6c70f47263]::HandlerInner>::bug::<&alloc[a4747db759a2a335]::string::String>
  17:     0x7fe0b8a43e20 - <rustc_errors[4c251b6c70f47263]::Handler>::bug::<&alloc[a4747db759a2a335]::string::String>
  18:     0x7fe0b8aac14d - rustc_middle[391f554ef2afaf2c]::ty::context::tls::with_context_opt::<rustc_middle[391f554ef2afaf2c]::ty::context::tls::with_opt<rustc_middle[391f554ef2afaf2c]::util::bug::opt_span_bug_fmt<rustc_span[df2b32850c624801]::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
  19:     0x7fe0b8aad5a6 - rustc_middle[391f554ef2afaf2c]::util::bug::opt_span_bug_fmt::<rustc_span[df2b32850c624801]::span_encoding::Span>
  20:     0x7fe0b63db8b3 - rustc_middle[391f554ef2afaf2c]::util::bug::bug_fmt
  21:     0x7fe0b654d177 - <rustc_infer[536d5a554b49bbbd]::infer::lexical_region_resolve::LexicalResolver>::lub_concrete_regions
  22:     0x7fe0b654a12b - rustc_infer[536d5a554b49bbbd]::infer::lexical_region_resolve::resolve
  23:     0x7fe0b715443b - <rustc_infer[536d5a554b49bbbd]::infer::InferCtxt>::resolve_regions_and_report_errors
  24:     0x7fe0b7141c09 - <rustc_infer[536d5a554b49bbbd]::infer::InferCtxt>::check_region_obligations_and_report_errors
  25:     0x7fe0b7394e11 - <rustc_infer[536d5a554b49bbbd]::infer::InferCtxtBuilder>::enter::<(), rustc_typeck[75df897160b4c8ff]::check::check::check_opaque_meets_bounds::{closure#0}>
  26:     0x7fe0b7374065 - rustc_typeck[75df897160b4c8ff]::check::check::check_item_type
  27:     0x7fe0b7370b2e - rustc_typeck[75df897160b4c8ff]::check::check::check_mod_item_types
  28:     0x7fe0b6959361 - <rustc_query_system[5706997ce835dcb4]::dep_graph::graph::DepGraph<rustc_middle[391f554ef2afaf2c]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[391f554ef2afaf2c]::ty::context::TyCtxt, rustc_span[df2b32850c624801]::def_id::LocalDefId, ()>
  29:     0x7fe0b695812d - rustc_query_system[5706997ce835dcb4]::query::plumbing::try_execute_query::<rustc_query_impl[2e6536e8c723df85]::plumbing::QueryCtxt, rustc_query_system[5706997ce835dcb4]::query::caches::DefaultCache<rustc_span[df2b32850c624801]::def_id::LocalDefId, ()>>
  30:     0x7fe0b749e3ce - rustc_query_system[5706997ce835dcb4]::query::plumbing::get_query::<rustc_query_impl[2e6536e8c723df85]::queries::check_mod_item_types, rustc_query_impl[2e6536e8c723df85]::plumbing::QueryCtxt>
  31:     0x7fe0b774367c - <rustc_middle[391f554ef2afaf2c]::hir::map::Map>::for_each_module::<rustc_typeck[75df897160b4c8ff]::check_crate::{closure#6}::{closure#0}>
  32:     0x7fe0b6d380d5 - rustc_typeck[75df897160b4c8ff]::check_crate
  33:     0x7fe0b6d376c7 - rustc_interface[2e430490b24d666b]::passes::analysis
  34:     0x7fe0b77f93e2 - <rustc_query_system[5706997ce835dcb4]::dep_graph::graph::DepGraph<rustc_middle[391f554ef2afaf2c]::dep_graph::dep_node::DepKind>>::with_task::<rustc_middle[391f554ef2afaf2c]::ty::context::TyCtxt, (), core[5a729203526575bf]::result::Result<(), rustc_errors[4c251b6c70f47263]::ErrorGuaranteed>>
  35:     0x7fe0b77f8aaa - rustc_query_system[5706997ce835dcb4]::query::plumbing::try_execute_query::<rustc_query_impl[2e6536e8c723df85]::plumbing::QueryCtxt, rustc_query_system[5706997ce835dcb4]::query::caches::DefaultCache<(), core[5a729203526575bf]::result::Result<(), rustc_errors[4c251b6c70f47263]::ErrorGuaranteed>>>
  36:     0x7fe0b77f856c - rustc_query_system[5706997ce835dcb4]::query::plumbing::get_query::<rustc_query_impl[2e6536e8c723df85]::queries::analysis, rustc_query_impl[2e6536e8c723df85]::plumbing::QueryCtxt>
  37:     0x7fe0b67dd847 - <rustc_interface[2e430490b24d666b]::passes::QueryContext>::enter::<rustc_driver[45772c003865a0c4]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[5a729203526575bf]::result::Result<(), rustc_errors[4c251b6c70f47263]::ErrorGuaranteed>>
  38:     0x7fe0b67d127c - rustc_interface[2e430490b24d666b]::interface::create_compiler_and_run::<core[5a729203526575bf]::result::Result<(), rustc_errors[4c251b6c70f47263]::ErrorGuaranteed>, rustc_driver[45772c003865a0c4]::run_compiler::{closure#1}>
  39:     0x7fe0b67cfbc1 - <scoped_tls[18b9aee780902605]::ScopedKey<rustc_span[df2b32850c624801]::SessionGlobals>>::set::<rustc_interface[2e430490b24d666b]::interface::run_compiler<core[5a729203526575bf]::result::Result<(), rustc_errors[4c251b6c70f47263]::ErrorGuaranteed>, rustc_driver[45772c003865a0c4]::run_compiler::{closure#1}>::{closure#0}, core[5a729203526575bf]::result::Result<(), rustc_errors[4c251b6c70f47263]::ErrorGuaranteed>>
  40:     0x7fe0b67cf8af - std[2c47335e2f8b42a0]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[2e430490b24d666b]::util::run_in_thread_pool_with_globals<rustc_interface[2e430490b24d666b]::interface::run_compiler<core[5a729203526575bf]::result::Result<(), rustc_errors[4c251b6 [...]

2022-10-11 22:16 UTC, QuentinPerez commented
I just tried the latest nightly (2022-10-11) after 1 month and this patch still causes an ICE. Is it something that can be solved easily or planned to be fixed?