add `ReadBuf::buf*` accessor functions for getting the original buffer
rust-lang/rust pull request #98962
Opened 2022-07-05 20:51 UTC by programmerjake

I noticed these functions were missing so I had to use an annoying workaround...

2022-07-05 20:51 UTC, rust-highfive commented
r? @joshtriplett

(rust-highfive has picked a reviewer for you, use r? to override)

2022-07-05 21:38 UTC, 5225225 commented
buf_mut looks unsound, as you can deinitialize bytes that are assume to be init.

`buf` and `into_buf` would be fine, as would `buf_mut` but being unsafe (or resetting the initialized part to 0).

2022-07-05 23:09 UTC, programmerjake commented
> buf_mut looks unsound, as you can deinitialize bytes that are assume to be init.

nice catch, i changed `buf_mut` to be `unsafe`

2022-07-08 20:57 UTC, programmerjake commented
@rustbot label +T-libs-api -T-libs

2023-01-29 04:54 UTC, pitaj commented
Hi, this is an API change and so needs to go through the ACP process, as described by the bot:

> If this PR contains changes to any unstable APIs please edit the PR description to add a link to the relevant [API Change Proposal](https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html) or [create one](https://github.com/rust-lang/libs-team/issues/new?assignees=&labels=api-change-proposal%2C+T-libs-api&template=api-change-proposal.md&title=%28My+API+Change+Proposal%29) if you haven't already.

Please open one if you haven't already, and link it here. Then, label this PR `S-waiting-on-ACP`.

@rustbot label -S-waiting-on-review +S-waiting-on-ACP

2023-01-29 04:58 UTC, programmerjake commented
> Hi, this is an API change and so needs to go through the ACP process, as described by the bot. Please open one if you haven't already, and link it here.

https://github.com/rust-lang/libs-team/issues/65

2023-09-17 03:18 UTC, dtolnay requested changes
Could you look into rebasing this past #97015?

Would these methods be needed only on `BorrowedBuf`, or also on `BorrowedCursor`?

2024-01-21 18:53 UTC, dtolnay reviewed
Let's pick this up in https://github.com/rust-lang/libs-team/issues/65, or a new ACP, if there is still a use case for this.

Thanks anyway for the PR!

2024-01-21 18:53 UTC, closed without merging