Add Read Impl for &Stdin
rust-lang/rust pull request #99153
Opened 2022-07-11 13:30 UTC by Dajamante

r? @oli-obk
fixes #95622

2022-07-11 13:30 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @oli-obk (or someone else) soon.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2022-07-11 13:31 UTC, Dajamante commented
@rustbot label +T-libs-api -T-libs

2022-07-11 13:33 UTC, oli-obk commented
r? @m-ou-se

2022-10-08 23:13 UTC, JohnCSimon commented
triage: 
@m-ou-se this has sat since July - can you post the status of the review?

2023-08-24 05:45 UTC, Dylan-DPC commented
r? @thomcc

2023-08-28 05:30 UTC, thomcc commented
This needs ACP.

2024-01-24 21:21 UTC, Ekleog commented
If it does, then I think https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html?highlight=acp should be updated? The current documentation seems to indicate that ACP are entirely optional, and are only to avoid working on a PR without it eventually landing (the "Note that an ACP is not strictly required" paragraph in particular).

AFAIU that document's suggestions are that this PR should just go through a T-libs FCP, which seems to be confirmed by [this comment in the related issue](https://github.com/rust-lang/rust/issues/95622#issuecomment-1087031086)

2024-01-26 03:14 UTC, dtolnay requested changes

2024-01-26 03:14 UTC, dtolnay commented on library/std/src/io/stdio.rs
> +#[stable(feature = "rust1", since = "1.0.0")]
Please choose some other unique feature name and set the stabilization version to "CURRENT_RUSTC_VERSION".

2024-01-26 03:18 UTC, dtolnay commented
@rust-lang/libs-api:
@rfcbot fcp merge

Quoting @RalfJung in https://github.com/rust-lang/rust/issues/95622#issue-1191032532:

> It is possible to write to a `&Stdout` thanks to `impl Write for &Stdout`, but it is not possible to read from a `&Stdin` as the corresponding `impl Read for &Stdin` is missing. This seems to be entirely an accident, given that [`read_line`](https://doc.rust-lang.org/nightly/std/io/struct.Stdin.html#method.read_line) *does* work on `&Stdin`.

We implement `std::io::Read` for references already where appropriate, such as for `&File` and `&TcpStream`.

2024-02-26 07:56 UTC, dtolnay commented
I filled in a feature name to resolve https://github.com/rust-lang/rust/pull/99153#pullrequestreview-1845022029, and an implementation of `Read::read_buf` which was added in `impl Read for Stdin` by #108326 after this PR was originally opened.

2024-02-26 07:56 UTC, dtolnay approved these changes
Thank you!

2024-02-26 07:56 UTC, rust-log-analyzer commented
The job **`mingw-check-tidy`** failed! Check out the build log: [(web)](https://github.com/rust-lang/rust/actions/runs/8045389156/job/21970579646) [(plain)](https://github.com/rust-lang/rust/commit/21644605ced49fe53409952bb47c06fa5f260cdd/checks/21970579646/logs)

<details><summary><i>Click to see the possible cause of the failure (guessed by this bot)</i></summary>

```plain
Getting action download info
Download action repository 'msys2/setup-msys2@v2.22.0' (SHA:cc11e9188b693c2b100158c3322424c4cc1dadea)
Download action repository 'actions/checkout@v4' (SHA:b4ffde65f46336ab88eb53be808477a3936bae11)
Download action repository 'actions/upload-artifact@v3' (SHA:a8a3f3ad30e3422c9c7b888a15615d19a852ae32)
Complete job name: PR - mingw-check-tidy
git config --global core.autocrlf false
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
---
COPY scripts/sccache.sh /scripts/
RUN sh /scripts/sccache.sh

COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt \
    && pip3 install virtualenv
COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
COPY host-x86_64/mingw-check/validate-error-codes.sh /scripts/

# NOTE: intentionally uses python2 for x.py so we can test it still works.
# NOTE: intentionally uses python2 for x.py so we can test it still works.
# validate-toolstate only runs in our CI, so it's ok for it to only support python3.
ENV SCRIPT TIDY_PRINT_DIFF=1 python2.7 ../x.py test \
           --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes reuse-requirements.in
---

#10 [5/8] COPY host-x86_64/mingw-check/reuse-requirements.txt /tmp/
#10 DONE 0.0s

#11 [6/8] RUN pip3 install --no-deps --no-cache-dir --require-hashes -r /tmp/reuse-requirements.txt     && pip3 install virtualenv
#11 0.659   Downloading binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
#11 0.672 Collecting boolean-py==4.0
#11 0.675   Downloading boolean.py-4.0-py3-none-any.whl (25 kB)
#11 0.688 Collecting chardet==5.1.0
---
#11 3.673 Building wheels for collected packages: reuse
#11 3.674   Building wheel for reuse (pyproject.toml): started
#11 4.007   Building wheel for reuse (pyproject.toml): finished with status 'done'
#11 4.008   Created wheel for reuse: filename=reuse-1.1.0-cp310-cp310-manylinux_2_35_x86_64.whl size=181117 sha256=f5f58750481f69515c2c0d1d503daf565e2565c370d07fc6aeb95fe3498b4269
#11 4.011   Stored in directory: /tmp/pip-ephem-wheel-cache-8ez87um2/wheels/c2/3c/b9/1120c2ab4bd82694f7e6f0537dc5b9a085c13e2c69a8d0c76d
#11 4.011 Installing collected packages: boolean-py, binaryornot, setuptools, reuse, python-debian, markupsafe, license-expression, jinja2, chardet
#11 4.036   Attempting uninstall: setuptools
#11 4.037     Found existing installation: setuptools 59.6.0
#11 4.038     Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
---
#11 5.276   Downloading virtualenv-20.25.1-py3-none-any.whl (3.8 MB)
#11 5.339      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 61.5 MB/s eta 0:00:00
#11 5.389 Collecting filelock<4,>=3.12.2
#11 5.393   Downloading filelock-3.13.1-py3-none-any.whl (11 kB)
#11 5.409 Collecting distlib<1,>=0.3.7
#11 5.413   Downloading distlib-0.3.8-py2.py3-none-any.whl (468 kB)
#11 5.419      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.9/468.9 KB 108.1 MB/s eta 0:00:00
#11 5.447 Collecting platformdirs<5,>=3.9.1
#11 5.451   Downloading platformdirs-4.2.0-py3-none-any.whl (17 kB)
#11 5.536 Installing collected packages: distlib, platformdirs, filelock, virtualenv
#11 5.699 Successfully installed distlib-0.3.8 filelock-3.13.1 platformdirs-4.2.0 virtualenv-20.25.1
#11 DONE 5.8s

#12 [7/8] COPY host-x86_64/mingw-check/validate-toolstate.sh /scripts/
#12 DONE 0.0s
---
DirectMap4k:      180160 kB
DirectMap2M:     7159808 kB
DirectMap1G:    11534336 kB
##[endgroup]
Executing TIDY_PRINT_DIFF=1 python2.7 ../x.py test            --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
+ TIDY_PRINT_DIFF=1 python2.7 ../x.py test --stage 0 src/tools/tidy tidyselftest --extra-checks=py:lint
    Finished dev [unoptimized] target(s) in 0.03s
##[endgroup]
downloading https://ci-artifacts.rust-lang.org/rustc-builds-alt/0250ef2571185b05701ed9d74fc904c17508a397/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz
extracting /checkout/obj/build/cache/llvm-0250ef2571185b05701ed9d74fc904c17508a397-true/rust-dev-nightly-x86_64-unknown-linux-gnu.tar.xz to /checkout/obj/build/x86_64-unknown-linux-gnu/ci-llvm
---
    Finished release [optimized] target(s) in 27.80s
##[endgroup]
fmt check
tidy check
tidy error: file `tests/ui/stdlib-unit-tests/issue-95622.rs` must begin with a descriptive name, consider `{reason}-issue-95622.rs`
removing old virtual environment
removing old virtual environment
creating virtual environment at '/checkout/obj/build/venv' using 'python3.10'
Requirement already satisfied: pip in ./build/venv/lib/python3.10/site-packages (24.0)
Collecting black==23.3.0 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 7))
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 35.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 35.5 MB/s eta 0:00:00
Collecting click==8.1.3 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 34))
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
Collecting importlib-metadata==6.7.0 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 38))
  Downloading importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
  Downloading importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
Collecting mypy-extensions==1.0.0 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 42))
  Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Collecting packaging==23.1 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 46))
  Downloading packaging-23.1-py3-none-any.whl (48 kB)
Collecting pathspec==0.11.1 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 50))
  Downloading pathspec-0.11.1-py3-none-any.whl (29 kB)
  Downloading pathspec-0.11.1-py3-none-any.whl (29 kB)
Collecting platformdirs==3.6.0 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 54))
  Downloading platformdirs-3.6.0-py3-none-any.whl (16 kB)
Collecting ruff==0.0.272 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 58))
  Downloading ruff-0.0.272-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.9 MB)
Collecting tomli==2.0.1 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 77))
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting typed-ast==1.5.4 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 81))
  Downloading typed_ast-1.5.4-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (877 kB)
  Downloading typed_ast-1.5.4-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (877 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 877.7/877.7 kB 117.3 MB/s eta 0:00:00
Collecting typing-extensions==4.6.3 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 107))
  Downloading typing_extensions-4.6.3-py3-none-any.whl (31 kB)
Collecting zipp==3.15.0 (from -r /checkout/src/tools/tidy/config/requirements.txt (line 114))
  Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
Installing collected packages: zipp, typing-extensions, typed-ast, tomli, ruff, platformdirs, pathspec, packaging, mypy-extensions, click, importlib-metadata, black
Successfully installed black-23.3.0 click-8.1.3 importlib-metadata-6.7.0 mypy-extensions-1.0.0 packaging-23.1 pathspec-0.11.1 platformdirs-3.6.0 ruff-0.0.272 tomli-2.0.1 typed-ast-1.5.4 typing-extensions-4.6.3 zipp-3.15.0
some tidy checks failed
Build completed unsuccessfully in 0:01:03
  local time: Mon Feb 26 07:56:16  [...]

2024-02-26 08:02 UTC, dtolnay commented
@bors r+

2024-03-09 07:44 UTC, Dylan-DPC commented
@bors r=dtolnay

2024-03-09 07:46 UTC, Dylan-DPC commented
@bors r=dtolnay

2024-03-09 20:33 UTC, Nadrieril commented
@bors rollup

2024-03-09 23:19 UTC, merged