Explain how Vec::with_capacity is faithful
rust-lang/rust pull request #99790
Opened 2022-07-27 02:20 UTC by workingjubilee

There are concerns that the doc changes in rust-lang/rust@95dc353006c23a4493b3d08ba33680e51c2107c8
are breaking changes in the promised API. In this commit, I explain in more detail
the exact promise that Vec::with_capacity is really making:
Vec is trying to act unsurprising by relaying information faithfully to the allocator,
it is not committing to internal details of Vec itself beyond that.
As it happens, we don't get useful capacity information from allocators,
but once upon a time Rust did capacity recalculation from available data,
and we should reserve the right to do so again if it seems profitable and correct.

This path avoids adding a duplicate `with_capacity_exact` to Vec's already-formidable API surface.

If merged, this closes rust-lang/rust#99385.

2022-07-27 02:20 UTC, rust-highfive commented
r? @thomcc

(rust-highfive has picked a reviewer for you, use r? to override)

2022-07-28 23:06 UTC, thomcc commented
I'm in favor of this, for sure. I'm also not certain if this is a contractual change, or a clarification of the existing contract. I'd lean toward the former, but it's close enough that I'll reassign to someone on libs-api (e.g. someone who can start an FCP about it), just to be sure.

r? @m-ou-se

2022-07-30 21:34 UTC, thomcc commented
I believe this won't work, because https://github.com/rust-lang/rfcbot-rs/issues/306 has not been implemented. That said, I'm going to try anyway, since the error message is likely point me in the right direction for what code in the rfcbot needs to change. Sorry in advance if this does something unexpected, thank you.

@rfcbot fcp merge

2022-08-24 08:26 UTC, JanBeh commented
The current contract is somewhat inconsistent because the documentation (as of Rust 1.63) currently says [here](https://github.com/rust-lang/rust/blob/1.63.0/library/alloc/src/vec/mod.rs#L361-L365):

> `vec![x; n]`, `vec![a, b, c, d]`, and `Vec::with_capacity(n)`, will all produce a `Vec` with **exactly** the requested capacity.

But in [`Vec::with_capacity`](https://github.com/rust-lang/rust/blob/1.63.0/library/alloc/src/vec/mod.rs#L428):

> Constructs a new, empty `Vec<T>` with **at least** the specified capacity.

2022-08-24 08:41 UTC, JanBeh requested changes
> `vec![x; n]` and `Vec::with_capacity(n)` produce a `Vec` that allocates `n` capacity.

This should probably read "at least `n` capacity" (if this is how `Vec` behaves, not sure). Also not sure about the grammar here.

>  `Vec` has preferred either answer at different times and may change again.

I don't think it's necessary to explain how things changed in past, and I would thus remove that sentence above. The previous sentence ("In that case, `capacity` may return either the requested capacity or actual allocated size.") is already clear enough in my opinion.

> However, `Vec::with_capacity(5)` will not deliberately "round up" to `Vec::with_capacity(8)` for any non-zero-sized type, to respect programmer intent.

I'm not as fond of giving an example here (and if an example is given, it should be phrased with "for example"). Maybe better phrase it like the following:

"However, `Vec::with_capacity(n)` will not deliberately "round up" in anticipation of the `Vec` growing beyond `n` elements. It thus behaves like `Vec::new` followed by `Vec::reserve_exact`, but may be faster."

I didn't check how `Vec` actually behaves. This still needs to be reviewed. I just wanted to comment on the wording here.

2022-09-02 13:13 UTC, Kixunil commented
@JanBeh noticed that too and opened an issue which this PR would close: #101316

2022-09-02 16:27 UTC, dpc commented
It seems slightly relevant: [I've been wondering if growing collections trying to please memory allocator's "2^n-C" requirements would be useful](https://internals.rust-lang.org/t/allocators-bin-sizes-aware-collections-capacity-resizing/17321). auto-`grow` is distinct from manually requesting capacity, but possibly similar reasoning applies: doesn't matter if `with_capacity` tries to be exact, if at the end the allocator rounds it up anyway, no?

2022-09-12 06:00 UTC, workingjubilee commented
> @JanBeh noticed that too and opened an issue which this PR would close: #101316 @workingjubilee I suggest you add closes statement to the PR description.

I have the power to close issues.

@dpc: An allocator for a system may deliberately choose to match, byte for byte, the requested allocation size, due to being run on a platform that has e.g. different RAM constraints. It is my understanding that the glibc malloc implementation does this and is widely considered to be of reasonable performance, especially across the variety of different hardware glibc is deployed on. So the design of things like jemalloc is not a universal good, and I believe it is inappropriate for Rust to adopt in a default container. Designing Vec in such a way that the API naturally works with either being bound against jemalloc or glibc seems a far superior choice.

2023-04-12 20:11 UTC, jmaargh commented
Hi, I'm the original author of #96173. Since this accidentally apparently caused a breaking change I feel I should probably start by apologising for the extra confusion I caused. I am sorry.

With the already suggested change of "with exactly the requested capacity" -> "with capacity at least `n`" the changes here look good to me.

I'm still a little unclear on the libs team's consensus (if there is one) on the intended behaviour here (having read the various issues linked above, as well as [zulip](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Vec.3A.3Awith_capacity.20promise). If this is the wrong place to discuss that, please do let me know where that discussion can be more helpful.

Generally (this discussion for non-ZSTs for the moment), the user can request capacity `n`, then the allocator allocates space for `m >= n` elements, and the `Vec` struct stores and reports of `p`. According to [this comment](https://github.com/rust-lang/rust/blob/83addf2540ce7ce7d0f875fdbe2a7cd0e7f52d97/library/alloc/src/raw_vec.rs#L193) right now `n = m = p` for all non-ZSTs. However, it's also been noted that allocators can totally reasonably give `m > n`. The question is, in those cases what is the guarantee that should be given for `p`?
1. "What you asked for": `p = n` will probably avoid surprise for many uses and was what the previous documentation guaranteed (though `reserve` and `reserve_exact` both were documented with the weaker guarantee).
2. "What's actually there": `p = m` will probably avoid surprise for users who are sensitive to exactly what is allocated.

My main motivating example for moving to 2 is mentioned in #95614, where you need to break a vec into raw parts (e.g. for FFI) and then re-construct. The docs for `from_raw_parts` are quite clear that the "capacity" passed in there must match what the allocator gave. The (not-stabilised) `into_raw_parts` guarantees that the "capacity" it returns is that from the allocator, presumably exactly for this reason. These together strongly suggest to me that `p = m` is the correct choice, since `m` will need to be tracked anyway for these use-cases.

Assuming this is all right and there is consensus on it, then [this behaviour](https://github.com/rust-lang/rust/blob/83addf2540ce7ce7d0f875fdbe2a7cd0e7f52d97/library/alloc/src/raw_vec.rs#L198) is already incorrect, is it not? The comment states that allocators "currently" return the requested size, but the `Allocator::allocate` docs explicitly state that "The returned block may have a larger size than specified by `layout.size()`". To bring everything into alignment, the extra cost of doing `capacity: ptr.len() / mem::size_of::<T>()` will have to be swallowed, surely?

2023-10-08 23:46 UTC, workingjubilee commented
I do not believe that suggestion applies, although I am not entirely sure what line people are suggesting it _for_, given people are talking inexactly about substrings instead of highlighting them in the UI.

What this attempts to explain is that Vec acts on the programmer's intention, and that sometimes this constitutes a surprising reality, i.e. that Vec, the programmatic entity, allocates with that capacity, and then the **Allocator** decides the capacity.

2023-10-09 20:02 UTC, jmaargh reviewed
Apologies, I now understand your intention. I've made some suggested changes which I believe makes that intention more explicit.

2023-10-09 20:02 UTC, jmaargh commented on library/alloc/src/vec/mod.rs
> +/// such as [`into_boxed_slice`].
Here are some suggestions for re-wording based on your stated intent, which I hope read a little clearer with a clearer distinction between "requested", "allocated", and "reported" capacities (none of which are guaranteed to equal any other).

Para 1: These are the ways of constructing with a specific capacity, they provide this guarantee on the allocation request.

Para 2: Allocator may return more space, and Vec is not guaranteed to report capacity as exactly the requested or the allocated capacity 

```suggestion
/// `vec![x; n]` and [`Vec::with_capacity(n)`] produce a `Vec` that allocates `n` capacity;
/// that is, they request a capacity for `n` elements from the allocator. Similarly,
/// `vec![a, b, c, d, e]` requests an allocation to cover the number of given elements (in this case 5).
/// `Vec` is guaranteed request exactly these capacities and not "round up" the allocation request
/// to speculatively avoid potential future allocations in these cases, to respect programmer
/// intent.
///
/// Any allocator may return an allocation with a size larger than the requested capacity, so
/// the allocated capacity may exceed the requested capacity. The reported capacity, as returned
/// by [`capacity`], is guaranteed to be at least the requested capacity and not more than the
/// allocated capacity, but is not guaranteed to be either. So if the programmer requests a
/// capacity of `n` the the allocator will be asked for `n` but may allocate space for `m >= n`, and
/// [`capacity`] may therefore also return `c >= n` (but `c <= m` is guaranteed).
///
/// Excess capacity an allocator has given `Vec` is still discarded by [`shrink_to_fit`].
/// If <code>[len] == [capacity]</code>, then a `Vec<T>` can be converted
/// to and from a [`Box<[T]>`][owned slice] without reallocating or moving the elements.
/// `Vec` exploits this fact as much as reasonable when implementing common conversions
/// such as [`into_boxed_slice`].
```

2024-07-24 06:12 UTC, Dylan-DPC commented
@workingjubilee if you can resolve the conflicts we can push this forward. Thanks

2025-01-24 11:53 UTC, closed without merging

2025-01-24 11:53 UTC, Dylan-DPC commented
Closed in favour of #135933