fix universe map in ifcx.instantiate_canonical_*
rust-lang/rust pull request #99814
Opened 2022-07-27 15:35 UTC by aliemjay

Previously, `infcx.instantiate_canonical_*` maps the root universe in `canonical` into `ty::UniverseIndex::Root`, I think because it assumes it works with a fresh `infcx` but this is not true for the use cases in mir typeck. Now the root universe is mapped into `infcx.universe()`.

I catched this accidentally while reviewing the code. I'm not sure if this is the right fix or if it is really a bug!

2022-07-27 15:35 UTC, rust-highfive commented
r? @petrochenkov

(rust-highfive has picked a reviewer for you, use r? to override)

2022-07-27 15:36 UTC, aliemjay commented
r? @rust-lang/types

2022-08-03 04:14 UTC, jackh726 commented
Any chance there's some test we can add?

2022-08-03 11:09 UTC, b-naber commented on compiler/rustc_infer/src/infer/canonical/mod.rs
> -        let universes: IndexVec<ty::UniverseIndex, _> = std::iter::once(ty::UniverseIndex::ROOT)
Currently reading about Universes/Placeholders and am curious, why can we do that? Why can't we encounter canonicalized variables with `UniverseIndex::Root` inside `instantiate_canonical_vars`?

2022-08-07 19:24 UTC, jackh726 commented
I think this looks fine, but I'd like @nikomatsakis's eyes on this

2022-10-10 20:51 UTC, nikomatsakis requested changes

2022-10-10 20:51 UTC, nikomatsakis commented on compiler/rustc_infer/src/infer/canonical/mod.rs
> +        let universes: IndexVec<ty::UniverseIndex, _> = std::iter::once(self.universe())
I think we should update the comment above to read something like

"Instantiate the root-universe content into the current universe, and create fresh universes for other things."

It took me a bit to understand what this code did. It makes sense, though.

2022-10-10 20:51 UTC, nikomatsakis commented on compiler/rustc_infer/src/infer/canonical/mod.rs
> +        let universes: IndexVec<ty::UniverseIndex, _> = std::iter::once(self.universe())
```suggestion
        //
        // Instantiate the root-universe content into the current universe,
        // and create fresh universes for the higher universes.
        let universes: IndexVec<ty::UniverseIndex, _> = std::iter::once(self.universe())
```

2022-10-10 20:52 UTC, nikomatsakis commented
I'm not sure what a test would look like for this, but I see the logic in the proposed behavior.

2022-10-23 22:57 UTC, jackh726 commented
@aliemjay any idea if you can come up with a test for this?

2022-10-24 06:51 UTC, aliemjay commented
@jackh726 I don't think a test is possible because the only place this method is used on a non-fresh InferCtxt is when instantiating UserTypeAnnotation in MIR typeck, but type annotations are currently only used in root universe AFAIK. For example if we're type-checking closures in a different way (using universes), the test would be like:
```rust
fn test() { // U0
    for<'a> |s: &'a str| { //U1
        let _: &'_ str = s; // `'_` lives in a higher universe
    };
}
```

2022-10-24 22:00 UTC, jackh726 commented
Could this be done with https://github.com/rust-lang/rfcs/pull/3216?

2022-11-29 15:32 UTC, apiraino commented
hello, checking progress. What's the current status? Based on the [previous comment](https://github.com/rust-lang/rust/pull/99814#issuecomment-1289673510), I'd switch to waiting for a feedback from @aliemjay  (hope I am reading the status correctly). Feel free to request a review with `@rustbot ready`, thanks!

@rustbot author

2022-11-30 13:02 UTC, jackh726 commented
Going to go ahead and approve this. The new code looks more right and writing a test for this is hard.

@bors r+ rollup=never

(no rollup so it's easier to bisect if it is indeed wrong somehow)

2022-11-30 17:20 UTC, merged

2022-11-30 18:40 UTC, rust-timer commented
Finished benchmarking commit (90711a86e5bdd4b0b65d293f0c2c48fd2db761b3): [comparison URL](https://perf.rust-lang.org/compare.html?start=24606deaf48e56f604a6125fa11fb9f70cf4f1f4&end=90711a86e5bdd4b0b65d293f0c2c48fd2db761b3&stat=instructions:u).

### Overall result: no relevant changes - no action needed


@rustbot label: -perf-regression



### [Instruction count](https://perf.rust-lang.org/compare.html?start=24606deaf48e56f604a6125fa11fb9f70cf4f1f4&end=90711a86e5bdd4b0b65d293f0c2c48fd2db761b3&stat=instructions:u)
This benchmark run did not return any relevant results for this metric.

### [Max RSS (memory usage)](https://perf.rust-lang.org/compare.html?start=24606deaf48e56f604a6125fa11fb9f70cf4f1f4&end=90711a86e5bdd4b0b65d293f0c2c48fd2db761b3&stat=max-rss)
This benchmark run did not return any relevant results for this metric.

### [Cycles](https://perf.rust-lang.org/compare.html?start=24606deaf48e56f604a6125fa11fb9f70cf4f1f4&end=90711a86e5bdd4b0b65d293f0c2c48fd2db761b3&stat=cycles:u)
This benchmark run did not return any relevant results for this metric.